### ISSUE TITLE
Document how cilium agent behaves when it's dependencies are missing

### ISSUE THREAD

**Issue by rlguarino** [cilium/cilium#1001]
What happens if kube-api/ kv-store goes away?
Can the cilium daemon survive a restart/outage of either of these services?
How long can the kv-store/kube-api be down before cilium has a problem?
What will happen to already running container?
What happens when creating a new container while kube-api/ kv-store is down?

**Comment by rlguarino** [comment]
If you want we could setup some time to talk about this over VC, and then I can write the docs. It's going to require a lot of knowledge of all of the moving pieces so I think it would go much faster if we could chat first.

**Comment by tgraf** [comment]
> What happens if kube-api/ kv-store goes away?

- Normal networking operations continue
- If policy enforcement is enabled: you lose the ability to add additional pods which belong to security identities which are unknown on the node
- If services are enabled: you lose the ability to add additional services/loadbalancers

> Can the cilium daemon survive a restart/outage of either of these services?

If it doesn't, it's a bug.

> How long can the kv-store/kube-api be down before cilium has a problem?

There is no strict time. We plan to introduce TTL/Leases for keys to automatically expire state created by nodes which crash and never come back. Until then, there is no strict time.

> What will happen to already running container?

Nothing.

> What happens when creating a new container while kube-api/ kv-store is down?

With k8s, the pod won't even get scheduled. W/o k8s, the container will not receive networking if the security identity cannot be resolved (kvstore access)

Happy to hop on a VC and chat as well.
