### ISSUE TITLE
Add TODOs Badge to the README

### ISSUE THREAD

**Issue by patrickdevivo** [cilium/cilium#10018]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `// TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/cilium/cilium)](https://www.tickgit.com/browse?repo=github.com/cilium/cilium)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for new contributors to find areas of code to improve.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/cilium/cilium)](https://www.tickgit.com/browse?repo=github.com/cilium/cilium)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

```release-note
Add TODOs badge to README
```

**Comment by aanm** [comment]
Discussed with Joe offline. https://github.com/cilium/cilium/pull/10103#issuecomment-587968694
