### ISSUE TITLE
Support for OpenShift 4.x

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10013]
This issue tracks demand for and progress related to running Cilium in OpenShift 4.x environments. Please :+1: if you want this feature.

**Comment by MartijnStraatman** [comment]
Any roadmap on Openshift 4.x integration?

**Comment by LorbusChris** [comment]
Let's keep this open :)

**Comment by bigg01** [comment]
It would be great to see cilium for OCP4! Cilium will new default for GKE. :-)

**Comment by giannisalinetti** [comment]
It would be awesome!

**Comment by hupiper** [comment]
I have a large customer asking about it.

**Comment by errordeveloper** [comment]
Initial version of the docs for OKD: https://github.com/cilium/cilium/pull/13410

**Comment by errordeveloper** [comment]
The docs had been tested quite extensively now and I believe it's good to close this. We will have some follow-up items, but the baseline is now good enough.
