### ISSUE TITLE
make ciliumidentities scalable

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10012]
ciliumidentities won't scale well due the fact that all cilium-agents are watching for this resource and all nodes update its status as soon they are using the identity.

**Comment by joestringer** [comment]
Is it primarily just status? This seems like a recurring theme which it'd be nice to come up with a general approach for how we address it. 

Offloading to kvstore is an approach we've used before, CNPNodeStatus in particular:
http://docs.cilium.io/en/latest/kvstore/#ciliumnetworkpolicynodestatus

**Comment by aanm** [comment]
> Is it primarily just status? This seems like a recurring theme which it'd be nice to come up with a general approach for how we address it.
> 
> Offloading to kvstore is an approach we've used before, CNPNodeStatus in particular:
> http://docs.cilium.io/en/latest/kvstore/#ciliumnetworkpolicynodestatus

That's also a good plan as well.

**Comment by joestringer** [comment]
@aanm This issue was resolved in v1.8.0 wasn't it?

**Comment by aanm** [comment]
Yes, Cilium identities no longer have the nodes' status. Closing...

**Comment by rajatjindal** [comment]
Hi Aanm/Joe, thanks for updating this issue. 

was this fix backported to 1.6.x and/or 1.7.x branch? 

we are currently on 1.6.x and use etcd as kv store (with plans to move to 1.7.x and then to 1.8.x in next quarter). 

I am wondering if we should wait for upgrades to 1.8.x before starting to use cilium identities CRD. 

someone from our team mentioned that the cilium can work with both cilium-identity CRD (for allocation) and existing kv store (for scaling).

any pointers (may be some documentation or link to PR that fixes this issue) to help make a decision (to enable CRD on 1.6.x or not), will be very helpful.

many Thanks
Rajat Jindal
