### ISSUE TITLE
agent: avoid bpftool emitting dmesg messages on general helper probes

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#10048]
Otherwise on production systems this will just confuse users. Don't probe any tracing related helpers:
```
[...]
[   83.355325] bpfilter: Loaded bpfilter_umh pid 1880

[   97.398664] **********************************************************
[   97.398664] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[   97.398665] **                                                      **
[   97.398665] ** trace_printk() being used. Allocating extra memory.  **
[   97.398665] **                                                      **
[   97.398665] ** This means that this is a DEBUG kernel and it is     **
[   97.398666] ** unsafe for production use.                           **
[   97.398666] **                                                      **
[   97.398666] ** If you see this message and you are not debugging    **
[   97.398666] ** the kernel, report this immediately to your vendor!  **
[   97.398667] **                                                      **
[   97.398667] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
[   97.398667] **********************************************************
[   97.400295] bpftool[2032] is installing a program with bpf_probe_write_user helper that may corrupt user memory!
[   97.400300] bpftool[2032] is installing a program with bpf_probe_write_user helper that may corrupt user memory!
[   97.403454] bpftool[2032] is installing a program with bpf_probe_write_user helper that may corrupt user memory!
[   97.403459] bpftool[2032] is installing a program with bpf_probe_write_user helper that may corrupt user memory!
[   97.405394] bpftool[2032] is installing a program with bpf_probe_write_user helper that may corrupt user memory!
[   97.405399] bpftool[2032] is installing a program with bpf_probe_write_user helper that may corrupt user memory!
[   97.417317] bpftool[2032] is installing a program with bpf_probe_write_user helper that may corrupt user memory!
[   97.417323] bpftool[2032] is installing a program with bpf_probe_write_user helper that may corrupt user memory!
[   98.206251] IPv6: ADDRCONF(NETDEV_UP): cilium_host: link is not ready
[   98.207067] IPv6: ADDRCONF(NETDEV_UP): cilium_net: link is not ready
[...]
```

**Comment by mrostecki** [comment]
That will require a change in bpftool - it's currently not able to probe just a subset of helpers. I can make a change for that and send it upstream after bpf-next gets open again. But since this issue is a release blocker, do you want me to prepare a patch to apply in container images of Cilium?

**Comment by brb** [comment]
@qmonnet ^^

**Comment by qmonnet** [comment]
I don't know for the patch for the container images, I'm not familiar enough with the release process yet.

Just commenting on the bpftool change: Would be nice to be able to select features to dump, e.g. to pass an option to bpftool to tell it to probe just one helper or one program type. Some elements to sort out:

- Syntax for the probe. For helpers it should be easy, just pass the name of the helper. For program/map types: name of the type from the enum (`BPF_PROG_TYPE_XDP`)? Or something else, but we would have to document it somwhere? And what about e.g. `bpf()` syscall availability? If we want that quick, maybe we could start with just the helpers.
- Currently for helpers bpftool considers each prog type, and for a given type, iterates on all helpers (`probe_helpers_for_progtype()`). Probing a helper should do kind of the opposite, probing availability of this helper by iterating on prog types. Or should we just mark it as available if it is supported by at least one program type?

**Comment by borkmann** [comment]
We can do a cilium/bpf/ repo on Github and have the change there for the time being. Once bpf-next reopens next week and it gets merged upstream, we can point that back to the upstream tree from where we build bpftool (e.g. for 1.7.1).

**Comment by mrostecki** [comment]
@borkmann Great, sounds like a good solution. I will start preparing a patch.

**Comment by mrostecki** [comment]
@qmonnet I was thinking about how to select features too. Looking at the structure of the JSON object printed by `bpftool feature -j`:

```
|- system_config
|- syscall_config
|- program_types
|- map_types
|- helpers
|  |- socket_filter_available_helpers
|  |- kprobe_available_helpers
|  |- sched_cls_available_helpers
|  |- sched_act_available_helpers
|  |- tracepoint_available_helpers
|  |- xdp_available_helpers
|  |- perf_event_available_helpers
|  |- cgroup_skb_available_helpers
|  |- cgroup_sock_available_helpers
|  |- lwt_in_available_helpers
|  |- lwt_out_available_helpers
|  |- lwt_xmit_available_helpers
|  |- sock_ops_available_helpers
|  |- sk_skb_available_helpers
|  |- cgroup_device_available_helpers
|  |- sk_msg_available_helpers
|  |- raw_tracepoint_available_helpers
|  |- cgroup_sock_addr_available_helpers
|  |- lwt_seg6local_available_helpers
|  |- lirc_mode2_available_helpers
|  |- sk_reuseport_available_helpers
|  |- flow_dissector_available_helpers
|  |- cgroup_sysctl_available_helpers
|  |- raw_tracepoint_writable_available_helpers
|  |- cgroup_sockopt_available_helpers
|- misc
```

I was thinking about having subcommands for each "main" attribute of the object, with the main syntax of `bpftool feature probe` like:

```
bpftool feature probe [COMPONENT] [SUBSYSTEM] [OPTIONS] [macros [prefix PREFIX]]
COMPONENT := { kernel | dev NAME }
SUBSYSTEM := { all | system-config | syscall-config | program-types | map-types | helpers | misc }
OPTIONS := { --filter-in PATTERN | --filter-out PATTERN }
```

So, for example, to do checks for helpers without tracepoint helpers, user would do:

```
bpftool feature probe kernel helpers --filter-out="*tracepoint*"
```

What do you think?

**Comment by qmonnet** [comment]
So you would reuse the names used in JSON output? Sounds like a good idea. We won't document the list of names, but people can find them by running `bpftool feature probe -p` without filtering, so it seems ok to me.

A few questions/remarks:
- Would the filters also work if no subsystem is provided (e.g. `bpftool f probe --filter-out "*trace_printk*"`)? (I suppose so, it's the same thing as using `all`?)
- Can we add a keyword in front of `SUBSYSTEM`, e.g. `class` or `group` or `subsystem` or whatever fits best? It really helps for parsing arguments (e.g. if we want to filter without indicating any subsystem), and even for bash completion.
- Can we turn the options into keywords (i.e. removing the double-dashes)? Most options used in bpftool are quite generic, in this case filtering would only be part of the probe command.

**Comment by mrostecki** [comment]
> So you would reuse the names used in JSON output? Sounds like a good idea. We won't document the list of names, but people can find them by running `bpftool feature probe -p` without filtering, so it seems ok to me.

Yes, I was thinking about treating the JSON object as the "basis".

> A few questions/remarks:
> 
>     * Would the filters also work if no subsystem is provided (e.g. `bpftool f probe --filter-out "*trace_printk*"`)? (I suppose so, it's the same thing as using `all`?)

I think yes, for consistency.

>     * Can we add a keyword in front of `SUBSYSTEM`, e.g. `class` or `group` or `subsystem` or whatever fits best? It really helps for parsing arguments (e.g. if we want to filter without indicating any subsystem), and even for bash completion.

Yes, good idea. So finally, it would look like:

```
bpftool feature probe [COMPONENT] subsystem [SUBSYSTEM] [OPTIONS] [macros [prefix PREFIX]]
COMPONENT := { kernel | dev NAME }
SUBSYSTEM := { all | system-config | syscall-config | program-types | map-types | helpers | misc }
OPTIONS := { --filter-in PATTERN | --filter-out PATTERN }
```

Where `bpftool feature` would do the same as `bpftool feature probe kernel subsystem all`, based on default values of `COMPONENT` and `SUBSYSTEM`.

> 
>     * Can we turn the options into keywords (i.e. removing the double-dashes)? Most options used in bpftool are quite generic, in this case filtering would only be part of the probe command.

Hmm... so you would rather see the option implemented in syntax like that?

```
bpftool feature probe [COMPONENT] subsystem [SUBSYSTEM] [filter-in PATTERN] [filter-out PATTERN] [macros [prefix PREFIX]]
COMPONENT := { kernel | dev NAME }
SUBSYSTEM := { all | system-config | syscall-config | program-types | map-types | helpers | misc }
```

With the following example of usage?

```
bpftool feature probe kernel subsystem helpers filter-out "*tracepoint*"
```

**Comment by mrostecki** [comment]
I'm fine with the last syntax, it seems to meet all your remarks.

**Comment by qmonnet** [comment]
Yes, looks good to me for the syntax! Thanks

**Comment by qmonnet** [comment]
Ah one more nit sorry, can we have `filter_in` and `filter_out` instead of `filter-in` and `filter-out`? I think we do not have keywords with dashes in them, so probably better to stick to underscores.

**Comment by mrostecki** [comment]
Sure. Would you prefer to use underscores in subsystem names as well?

**Comment by qmonnet** [comment]
Oh, yes please!

**Comment by mrostecki** [comment]
My WIP branch:

https://gitlab.com/mrostecki/bpf-next/-/commits/bpftool-feature-subcommands

It works according to syntax I posted. I need to update manpages and write some selftests to ensure that it really works.

**Comment by qmonnet** [comment]
I commented your commits. One thing that must be changed at least, is that your patch adds filtering too late: it filters the output, but the probe has already run at that time. So the warning will still appear in the kernel logs.

Note that I'm not familiar with GitLab, so let me know if I missed the correct tools to do the review (I know GitHub has a “review” mode, couldn't see one for GitLab).

**Comment by soumynathan** [comment]
The suggestions from @qmonnet seems reasonable and @mrostecki I will review your WIP branch.
