### ISSUE TITLE
CIDR: Add upper limit on number CIDR matches

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1006]
Enforce the upper max CIDR limit on the golang side with a clear error message in the logfile instead of a BPF compilation error.

**Comment by aalemayhu** [comment]
I am not so familiar with CIDR, is the upper limit documented somewhere? If not what should it be?
Thanks.

**Comment by tgraf** [comment]
@jrajahalme can provide the details

**Comment by tgraf** [comment]
@tgraf to ping @scanf when policy spec docs are being merged
