### ISSUE TITLE
Remove go-bindata

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#10075]
Use of `go-bindata` dates back from times when people ran Cilium as static binary. This has become uncommon and users either use the container image or a package manager which will both ship `/var/lib/cilium` directly so there is no need to unpack any assets via the binary.

**Comment by brb** [comment]
Many of us still runs Cilium as a static binary for local development. Therefore, it would be good to have a Makefile target which would install the assets into `/var/lib/cilium`.
