### ISSUE TITLE
Multi Node Kubernetes CI tests

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1007]
Master issue

- [x] Pod to pod connectivity across nodes
  - [x] encap
- [x] Pod - service - pod
- [x] L3/L4 policy
- [x] L7 policy
- [x] getting started guide in multi node
- [x] Stresstest for L7 (need to find out the right l7 policy)
- [x] test deployment using DaemonSet
- [x] policy across namespaces
- [x] Super combo test: service + proxy + l3 rule + l7 rule

**Comment by danehans** [comment]
@aanm Has the community settled on adding multi-node support to Cilium? If so, has an implementation beed decided? I'm interested in having Cilium use BGP for multi-host networking.

**Comment by tgraf** [comment]
> @aanm Has the community settled on adding multi-node support to Cilium? If so, has an implementation beed decided? I'm interested in having Cilium use BGP for multi-host networking.

We just merged the new encapsulation mode with #1020. The existing direct mode is still as-is and is what ou would want to use in combination with BGP.

**Comment by aanm** [comment]
All tasks completed!
