### ISSUE TITLE
1.6.6 release doesn't honor enable-ipv6=false

### ISSUE THREAD

**Issue by jdef** [cilium/cilium#10074]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**

1. upgrade from cilium 1.6.5 to 1.6.6 using the quickstart yaml, ensure that ipv6 is configured to "false"
2. observe that it fails when running on my ipv6-disabled host

Looks like we need a backport of #9034 to the 1.6.x stream.

```
level=info msg="  --enable-ipv4='true'" subsys=daemon
level=info msg="  --enable-ipv6='false'" subsys=daemon
...
level=info msg="Initializing daemon" subsys=daemon
level=fatal msg="Error when enabling sysctl parameters" error="could not open the sysctl file /proc/sys/net/ipv6/conf/all/forwarding: open /proc/sys/net/ipv6/conf/all/forwarding: no such file or directory" subsys=daemon
```

**Comment by pires** [comment]
FYI this seems to have been introduced in https://github.com/cilium/cilium/commit/5ededa517331d711113c4e465288fcddb278cca9#diff-a63217c3602485326469fc1a8fc38733R28-R30.

**Comment by pires** [comment]
Done in https://github.com/cilium/cilium/pull/10135. Guess all is needed now it 1.6.7 to be cut.

**Comment by joestringer** [comment]
v1.6.7 is out. Please comment or reopen an issue if you observe any subsequent problems.
