### ISSUE TITLE
Controller fails: error dumping ipcache BPF map: .... errno 524

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10080]
Cilium v1.7.0-rc3, after upgrade direct from v1.5.11.

Report here: https://github.com/cilium/cilium/pull/10010#issuecomment-582633077

A controller fails. In the debug logs there is this:

```
level=debug msg="Controller run failed" consecutiveErrors=47 error="error dumping ipcache BPF map: Unable to get next key from map with file descriptor 7: errno 524" name=ipcache-bpf-garbage-collection subsys=controller uuid=[REDACTED]
```

Marked this release-blocker so we can evaluate, we can make a call whether this is widespread enough or severe enough to block v1.7.0 final or not.

**Comment by joestringer** [comment]
@johngmyers I filed this issue based on the comment you made on the referred thread.

Would you be able to provide at least a kernel version, perhaps also a sysdump?

**Comment by johngmyers** [comment]
I'm sorry, but I'm probably not going to be able to get to this for a few days. I unfortunately have urgent in-flight projects.

Os/kernel is `Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-70-generic x86_64)`

sysdump runs afoul of our admission controllers. I still need to review my rushed upgrade to see if I missed a change to our Helm charts or some other prerequisite.

**Comment by Rolinh** [comment]
The reason this error surfaces now is probably due to this change: https://github.com/cilium/cilium/commit/21141e36f51dbbf937f5eb56b8c0734641f70790#diff-de9af49c1a0e9c02fcb8258e1d3815c5R554.
Errors on `GetNextKeyFromPointers()` used to be ignored as one could not distinguish an error that signaled the end of a map iteration from a real error.

**Comment by tgraf** [comment]
Discussing during meeting:
`524` is `operation not supported`. This is likely signaling the inability to dump LPM. Unclear why we hit this as we should probe and not use LPM?
