### ISSUE TITLE
Fix complaints from LGTM.com

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10099]
LGTM.com generates alerts for potential issues in code, and recently added support for Golang.

Here's the cilium page:
https://lgtm.com/projects/g/cilium/cilium/alerts

Fix up the remaining complaints.

**Comment by brb** [comment]
The one-by-off error for the NodePort range (https://lgtm.com/projects/g/cilium/cilium/alerts?mode=list&severity=error) seems to be a false positive - the static analysis tool is probably unable to detect that `log.Fatal()` inside the if-block will terminate the execution.

**Comment by joestringer** [comment]
Agreed. That said, it should also be straightforward to adjust the code to avoid the false positive.

**Comment by maxwolffe** [comment]
@joestringer - looks like LGTM.com has shut down - should we close this issue?

**Comment by joestringer** [comment]
Thanks for the heads up. It looks like the future of these is under https://github.com/cilium/cilium/security/code-scanning , so there is no longer a need to track this as a github issue. Closing.
