### ISSUE TITLE
Run CI on GKE without kube-proxy

### ISSUE THREAD

**Issue by brb** [cilium/cilium#10121]
Add a CI job to run CI tests on GKE w/o kube-proxy.

**Comment by pchaigno** [comment]
Is the intended goal here to run our kube-proxy replacement on GKE, or actually to remove kube-proxy? If it's the latter, wouldn't that require having two different CI jobs for GKE?

**Comment by brb** [comment]
It's the latter - to remove kube-proxy. Yes, we would need to have two different jobs.
