### ISSUE TITLE
Check `unsafe.Pointer` use with go 1.14 `-d=checkptr` compiler option

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#10133]
The upcoming Go 1.14 release will include `-d=checkptr` as a compile-time option for adding instrumentation to check that Go code is following `unsafe.Pointer` safety rules dynamically. This might help in finding problematic uses of `unsafe.Pointer` in Cilium's code base, e.g. causing memory corruption.

This option should probably not be enabled by default, but could e.g. be run as part of CI.

Also see https://tip.golang.org/doc/go1.14#compiler for details.

/cc @brb

**Comment by tklauser** [comment]
I also started checking our dependencies and sent some PRs already:

* vishvananda/netlink#523 (re-vendored by #10138)
* fsnotify/fsnotify#325

Probably more to come.

**Comment by brb** [comment]
@tklauser Cool, have you already tried compiling with `checkptr` cilium-agent?

**Comment by tklauser** [comment]
@brb not yet, so far I only ran it with the tests. Will try cilium-agent next.
