### ISSUE TITLE
Service IP range is not reachable from localhost

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#1013]
@tgraf Not sure if this is an expected behavior, but currently the host (in my case a minikube VM) cannot reach Kubernetes services.

**Comment by michi-covalent** [comment]
I deployed a service without cilium, and the service ip is reachable from the host:

```
$ curl 10.0.0.34:9080/health
Details is healthy
```

**Comment by tgraf** [comment]
> I deployed a service without cilium, and the service ip is reachable from the host:

Thanks for confirming

**Comment by tgraf** [comment]
TODO:
- [ ] Retrieve service range from API server
- [ ] Add service range route and point to `cilium_host` interface
