### ISSUE TITLE
k8s-install-restart-pods.rst: WARNING: document isn't included in any toctree

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10152]
`make render-docs` returns the following error:

Documentation/gettingstarted/k8s-install-restart-pods.rst: WARNING: document isn't included in any toctree

**Comment by Rolinh** [comment]
I don't see this error in `master`. This file as actually included by `Documentation/gettingstarted/k8s-install-gke.rst`.

**Comment by aanm** [comment]
I was probably running a non-master version. Thanks for taking a look!
