### ISSUE TITLE
Regression in syncing remote cluster identities

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#10174]
The 1.7 and master branch currently contain a regression which prevents security identities from being properly synchronized. This breaks policy enforcement across clusters.

From @raybejjani:
> 1- We use the global kvstore client when doing ListAndWatch (https://github.com/cilium/cilium/blob/v1.7/pkg/kvstore/allocator/allocator.go#L527). This explains why I see two ` watcher=cilium/state/identities/v1/id` to the same etcd. The other clustermesh syncs (nodes and ipcache) use the remote-cluster etcd backend directly and so they see the right data.
2- The remote cluster etcd backend is passed into pkg/allocator.Allocator.WatchRemoteKVStore  but it is ignored (https://github.com/cilium/cilium/blob/v1.7/pkg/allocator/allocator.go#L790-L793) and then the watch call in pkg/allocator/cache.cache.start is on the method pointer (https://github.com/cilium/cilium/blob/v1.7/pkg/allocator/cache.go#L179-L197). This happens to be the main identity allocator cache, passed into remoteCluster.restartRemoteConnection (https://github.com/cilium/cilium/blob/v1.7/pkg/clustermesh/remote_cluster.go#L133) through many layers of indirection. Further, the Allocator.WatchRemoteKVStore call adds the main identity allocator to itself in remoteCaches  (https://github.com/cilium/cilium/blob/v1.7/pkg/allocator/allocator.go#L795-L797). This explains why I saw double entries in cilium identity list

An initial fix has been locally tested:
https://github.com/cilium/cilium/commit/1b46ef2fe90e8e3b9bea8bfe24db89b4f7a5b292

**Comment by joestringer** [comment]
Discussed removing release-blocker for v1.7 release during community meeting. We can look into backports post-1.7.0.

**Comment by joestringer** [comment]
I believe that this is addressed in v1.7.1. Please comment or reopen if you observe subsequent issues in this release.
