### ISSUE TITLE
Subnet Management Using Kubernetes

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#1019]
I am interested in having Cilium use the Kubernetes API for subnet assignment. Will the project accept a PR for adding this feature?

**Comment by tgraf** [comment]
> I am interested in having Cilium use the Kubernetes API for subnet assignment. Will the project accept a PR for adding this feature?

I assume you are talking about using `--allocate-node-cidrs=true`?
We are tracking the encapsulation side of this feature in #972. Very happy to take a PR which works on the subnet side of this.

**Comment by danehans** [comment]
That is correct. Let me wrap-up my upstream k8s pr's and try taking a stab at this.
