### ISSUE TITLE
Support graceful termination in kube-proxy replacement

### ISSUE THREAD

**Issue by brb** [cilium/cilium#10217]
Currently, we remove a backend IP from a LB service map immediately after the cilium-agent's k8s watcher has received an event that a corresponding Endpoint was removed. This can prematurely terminate existing connections even if a service pod was deployed with `terminationGracePeriodSeconds`, which should guarantee that the pod won't get killed for the given amount of seconds after it has received `SIGTERM`.

The problem becomes even more obvious, when cilium-agent receives the Endpoint rm event _before_ kubelet, which is responsible for executing `CNI DEL`.

To nicely handle the termination, we should postpone the removal of a backend IP from the `lb_backends_v{4,6}` maps either for `terminationGracePeriodSeconds` (if set) or for a configurable per protocol timeout.

**Comment by theminecoder** [comment]
This PR which is showing up in k8s 1.20 might be of interest to help solve this issue kubernetes/kubernetes#92968

**Comment by brb** [comment]
Thanks. Note to ourselves: when implementing the feature, we need to consider the endpoint-related changes in k8s v1.20 https://github.com/cilium/cilium/issues/14239.

**Comment by aditighag** [comment]
Tracking the fix for this issue in https://github.com/cilium/cilium/issues/14844.
