### ISSUE TITLE
bpf: command execution failed for bpf/init.sh

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#10228]
Seen in `cilium.log` on a failed CI test run for #10204, looks unrelated to that PR:

```
Feb 17 22:37:01 runtime cilium-agent[15047]: level=error msg="Error while initializing daemon" error="Command execution failed for [/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.15.185.178 fc00::10ca:1 vxlan    1500 false false  false false /var/run/cilium/cgroupv2 /sys/fs/bpf ]: context canceled" subsys=daemon
Feb 17 22:37:01 runtime cilium-agent[15047]: level=fatal msg="Error while creating daemon" error="Command execution failed for [/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.15.185.178 fc00::10ca:1 vxlan    1500 false false  false false /var/run/cilium/cgroupv2 /sys/fs/bpf ]: context canceled" subsys=daemon
```

when running said command line locally I get

```
$ sudo /var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.15.185.178 fc00::10ca:1 vxlan 1500 false false false false /var/run/cilium/cgroupv2 /sys/fs/bpf
[...]
+ ip link set cilium_host mtu false
Error: argument "false" is wrong: Invalid "mtu" value
```

It seems like the number of arguments passed to `bpf/init.sh` is not 17 (`pkg/datapath/loader.initArgMax`) in all cases, while the script assumes them to always be:

https://github.com/cilium/cilium/blob/b6f2e75d5b98bc200817da41f96c6522866cdd4a/bpf/init.sh#L17-L34

It looks like the unused arguments are passed as empty string rather than some placeholder value.

/cc @cilium/bpf @cilium/bpf-loader

**Comment by brb** [comment]
@tklauser Was your PR rebased against the latest master which includes https://github.com/cilium/cilium/pull/10218?

**Comment by tklauser** [comment]
@brb yes, it was rebased against master and included #10218

**Comment by tklauser** [comment]
The failure can e.g. be seen in `cilium.log` of https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/17220/testReport/junit/(root)/Suite-runtime/RuntimeConntrackInVethModeTest_Conntrack_related_configuration_options_for_endpoints/ and other failed tests of the same run: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/17220/#showFailuresLink

Please note that the tests did not fail due to this issue but due to missing changes in PR #10204

**Comment by tklauser** [comment]
test-me-please
