### ISSUE TITLE
cilium, daemon: remove arping lib dependency

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#10236]
The j-keck/arping library which we currently pull in via cilium/arping is a mess, implement something properly and get rid of this dependency.

Also, v6 support is missing.

**Comment by vladdy** [comment]
I'd like to try to help with this.

**Comment by jrfastab** [comment]
I'm happy to review any code or discuss this, reach out on slack or here. It was a pretty ugly bit of work I did here.

**Comment by nathanjsweet** [comment]
This is fixed

**Comment by brb** [comment]
@nathanjsweet I think it was closed by a mistake (I don't see any PR which replaced the arping lib)?

**Comment by vladdy** [comment]
Cool. Going to get back to this this week if there has not been a PR with the fix (will check that first)

**Comment by nathanjsweet** [comment]
@brb sorry I was under the impression that the arping library itself was pulling in the suspect library, not that it was a clone of that library.

**Comment by brb** [comment]
@vladdy Hey, are you still working on this issue?

**Comment by vladdy** [comment]
@brb, sorry for the luck of the updates. Yes, I'm. I'll send an update by monday.

**Comment by aanm** [comment]
@vladdy any updates?

**Comment by vladdy** [comment]
I'll have an update to the PR by Wednesday. Sorry about the delay.

**Comment by vladdy** [comment]
I need a little more time. Will try to provide an update tomorrow.

**Comment by vladdy** [comment]
Although this got closed, I wanted to confirm with @borkmann on his thoughts about IPv6 from the initial posting. I don't think it uses ARP and the code around calls to arping operates with IPv4 addresses. Should there still be a task for IPv6?

**Comment by brb** [comment]
There is the issue for it: https://github.com/cilium/cilium/issues/14429
