### ISSUE TITLE
BPF system config check is NOT OK

### ISSUE THREAD

**Issue by RayRay10460** [cilium/cilium#10250]
## Bug report 

**General Information**

- Cilium version: 1.7.0

- Kernel version: 4.20.2-042002-generic

- Orchestration system version in use :
 Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- error log:
level=info msg="|  _| | | | | |     |" subsys=daemon
level=info msg="|___|_|_|_|___|_|_|_|" subsys=daemon
level=info msg="Cilium 1.7.0 adeaf8c04 2020-02-18T21:41:10+01:00 go version go1.13.8 linux/amd64" subsys=daemon
level=info msg="cilium-envoy  version: c31482c3e49670980c05cafc914320f7949b266f/1.12.2/Modified/RELEASE/BoringSSL" subsys=daemon
level=info msg="clang (7.0.0) and kernel (4.20.2) versions: OK!" subsys=linux-datapath
level=info msg="linking environment: OK!" subsys=linux-datapath
level=info msg="bpf_requirements check: OK!" subsys=linux-datapath
level=info msg="bpf_features check: OK!" subsys=linux-datapath
level=warning msg="BPF system config check: NOT OK." error="CONFIG_BPF kernel parameter is required" subsys=linux-datapath
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Valid label prefix configuration:" subsys=labels-filter
level=info msg=" - :io.kubernetes.pod.namespace" subsys=labels-filter
level=info msg=" - :io.cilium.k8s.namespace.labels" subsys=labels-filter
level=info msg=" - :app.kubernetes.io" subsys=labels-filter
level=info msg=" - !:io.kubernetes" subsys=labels-filter
level=info msg=" - !:kubernetes.io" subsys=labels-filter
level=info msg=" - !:.*beta.kubernetes.io" subsys=labels-filter
level=info msg=" - !:k8s.io" subsys=labels-filter
level=info msg=" - !:pod-template-generation" subsys=labels-filter
level=info msg=" - !:pod-template-hash" subsys=labels-filter
level=info msg=" - !:controller-revision-hash" subsys=labels-filter
level=info msg=" - !:annotation.*" subsys=labels-filter
level=info msg=" - !:etcd_node" subsys=labels-filter
level=info msg="Auto-enabling \"enable-node-port\", \"enable-external-ips\", \"enable-host-reachable-services\" features" subsys=daemon
level=info msg="Using auto-derived device for BPF node port" interface=ens3 subsys=daemon
level=warning msg="BPF host reachable services for UDP needs kernel 4.19.57, 5.1.16, 5.2.0 or newer. If you run an older kernel and only need TCP, then specify: --host-reachable-services-protos=tcp Disabling the feature." subsys=daemon
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.82.0.0/16
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Detected MTU 1500" subsys=mtu
level=info msg="Restored services from maps" failed=0 restored=0 subsys=service
level=info msg="Removing stale endpoint interfaces" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://10.233.0.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Retrieved node information from kubernetes" nodeName=node1 subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=10.224.222.82 ipAddr.ipv6="<nil>" nodeName=node1 subsys=k8s v4Prefix=10.255.64.0/24 v6Prefix="<nil>"
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNetworkPolicy/v2 subsys=k8s

**How to reproduce the issue**
curl -LO https://github.com/cilium/cilium/archive/v1.7.tar.gz
tar xzvf v1.7.tar.gz
cd cilium-1.7/install/kubernetes
helm template cilium \
  --namespace kube-system \
 --set global.etcd.enabled=true\
    --set global.etcd.managed=true    > cilium.yaml
kubectl apply -f cilium.yaml

1. instruction 1
2. instruction 2

**Comment by brb** [comment]
@RayRay10460 The warning `CONFIG_BPF kernel parameter is required` is harmless, as cilium-agent was not able to access the kernel config. In your case it is most likely available only in `/boot`, which is not mounted to the cilium-agent container.
