### ISSUE TITLE
CI: K8sIstioTest Istio Bookinfo Demo Tests bookinfo inter-service connectivity: hung at "Waiting for Istio pods to be ready"

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10270]
Seen in backport PR #10223 on one k8s tests run:

```
11:41:12  K8sIstioTest Istio Bookinfo Demo 
11:41:12    Tests bookinfo inter-service connectivity
11:41:12    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.12-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
11:41:14  STEP: Installing Cilium
11:41:14  STEP: Installing DNS Deployment
11:41:14  STEP: Performing Cilium preflight check
11:41:14  STEP: Performing Cilium status preflight check
11:41:15  STEP: Performing Cilium controllers preflight check
11:41:16  STEP: Performing Cilium health check
11:41:20  STEP: Performing Cilium service preflight check
11:41:20  STEP: Performing K8s service preflight check
11:41:20  STEP: Performing K8s service preflight check
11:41:20  STEP: Creating the istio-system namespace
11:41:20  STEP: Creating namespace istio-system
11:41:20  STEP: Creating the Istio CRDs
11:41:21  STEP: Waiting for Istio CRDs to be ready
11:41:31  STEP: Creating the Istio system PODs
11:41:33  STEP: Waiting for Istio pods to be ready
11:46:01  === Test Finished at 2020-02-20T19:45:48Z====
11:46:52  ===================== TEST FAILED =====================
11:47:53  cmd: kubectl get pods -o wide --all-namespaces
11:47:53  Exitcode: 1 
11:47:53  Stdout:
11:47:53   	 
11:47:53  Stderr:
11:47:53   	 
11:47:53  
11:47:53  Fetching command output from pods []
13:04:36  STEP: Test suite timed out after 1h38m0s
```

Unfortunately the main artifact gathering failed because the jenkins node ran out of space.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2874/execution/node/108/log/

[fec264e9_K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip](https://github.com/cilium/cilium/files/4233445/fec264e9_K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip)
[test_results_Cilium-PR-Ginkgo-Tests-K8s_2874_BDD-Test-k8s-1.12.zip](https://github.com/cilium/cilium/files/4233447/test_results_Cilium-PR-Ginkgo-Tests-K8s_2874_BDD-Test-k8s-1.12.zip)
[test_results_Cilium-PR-Ginkgo-Tests-K8s_2874_BDD-Test-k8s-1.11.zip](https://github.com/cilium/cilium/files/4233450/test_results_Cilium-PR-Ginkgo-Tests-K8s_2874_BDD-Test-k8s-1.11.zip)

**Comment by jrajahalme** [comment]
Could it also be that the PODs could not be started due to lack of disk space?

**Comment by joestringer** [comment]
Failing to start pods also due to lack of disk space is a reasonable theory. If we see evidence of this kind of failure again, we can file another issue or reopen.

Closing.
