### ISSUE TITLE
doc: slack link

### ISSUE THREAD

**Issue by alban** [cilium/cilium#103]
README.md says:

> If you have any questions feel free to contact us on [Slack](https://cilium.slack.com)!

Should this be a public Slack group or a private one? It seems to be configured as invite-only.

**Comment by tgraf** [comment]
Right, kernel guys shouldn't be allowed to configure slack. What's the best way to make it public? I can only seem to configure it to auto accept certain domains.

**Comment by tgraf** [comment]
@alban 
I've opened #104 which enables a slackin instance at https://cilium.herokuapp.com/. Does that work for you?

**Comment by alban** [comment]
@tgraf It worked for me!

The link will need to be updated on this page as well: https://hub.docker.com/r/cilium/cilium/

**Comment by tgraf** [comment]
Looks like the auto triggered build fixed the docker hub document as well.
Thanks @alban!
