### ISSUE TITLE
Add support for earlier versions of CNI

### ISSUE THREAD

**Issue by amreshakim** [cilium/cilium#1030]
Currently, cilium-cni supports only 0.3.1 spec.

- Mesos does not support CNI 0.3.x. (https://issues.apache.org/jira/browse/MESOS-7079)
- Also, cilium-cni reports supporting all cni versions which is misleading when using cilium-cni with mesos: a task crashes and it is not immediately clear why.

It would be nice to support, at least 0.2.x and 0.3.x specs and report cilium-cni compatible only with the supported versions.

**Comment by amreshakim** [comment]
The only difference between 0.3.0 and 0.3.1 is a corrected typo in the CNI spec ("ip" should be "ips") so we can safely assume cilium-cni supports 0.3.x as of now.

**Comment by aanm** [comment]
@amreshakim Can we close this one since #1036 fix it?

**Comment by amreshakim** [comment]
Sure @aanm.
