### ISSUE TITLE
Documentation links to https://docs.cilium.io/en/stable/contributing/contributing/ fail

### ISSUE THREAD

**Issue by CybrPunk** [cilium/cilium#10316]
## Bug report

**General Information**

Documentation links to https://docs.cilium.io/en/stable/contributing/contributing/ fail to find the requested page.

**How to reproduce the issue**

1. Navigate to https://github.com/cilium/cilium
2. Open the link to `contributing` - http://docs.cilium.io/en/stable/contributing/contributing/

**Comment by CybrPunk** [comment]
This is also true for links generated in messages for pull requests, etc.

**Comment by pchaigno** [comment]
Do you want to open a pull request to fix those? I can do it otherwise :-)

**Comment by CybrPunk** [comment]
@pchaigno I'm not quite sure how to fix all of them, especially true for the urls in generated messages in pull request comments.

**Comment by pchaigno** [comment]
If you're referring to @maintainer-s-little-helper's messages, you can change the link here:
https://github.com/cilium/cilium/blob/9d8114f04c5dfd6e545e873f7eca665b35cff3f6/.github/cilium-actions.yml#L36

**Comment by CybrPunk** [comment]
Got it, you can assign it to me then
