### ISSUE TITLE
Warnings: WARN[0063] Unable to close policy map /sys/fs/bpf/tc/globals/cilium_policy_63465: bad file descriptor 

### ISSUE THREAD

**Issue by NBruijn** [cilium/cilium#1031]
I experience some warnings after I detach from a container.

I run cilium with the following flags:
`cilium-agent --kvstore local -t vxlan`
 
Version:
`Cilium 0.9.90 08c1e0c4 Sat, 17 Jun 2017 21:16:47 +0200 go version go1.8.3 linux/amd64`

Whenever I create a container, for example:
`docker run -itd --name cil26 --net cilium-net -l "id=app1" nbruijn/cilium /bin/bash`

Then attach to it:
`docker attach cil26`

And then detach from it by typing exit or ^+d then this results in the following warnings in the cilium-agent:

`WARN[0063] Unable to close policy map /sys/fs/bpf/tc/globals/cilium_policy_63465: bad file descriptor `
`WARN[0063] Unable to remove endpoint from map: Unable to delete element: no such file or directory`

The warnings seems to do no harm as everything is still working correctly. However, I'm wondering what causes these warnings.

Additional information can be provided.

**Comment by NBruijn** [comment]
Some additional info,

I noticed that whenever the container is build the map is stored in: 
`/sys/fs/bpf/tc/globals/`
as:
`cilium_policy_63465` 
and after detaching from it, the map does get deleted correctly from this location. So it seems that it tries to delete it a second time.

**Comment by tgraf** [comment]
I think this was fixed via #1135. Please re-open if incorrect.
