### ISSUE TITLE
Cilium operator --version does not print anything in <= 1.6 branches

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10339]

**Comment by fristonio** [comment]
![image](https://user-images.githubusercontent.com/21292343/75335152-fd925180-58ae-11ea-921d-c7cc50f5d02f.png)
I am able to get the correct version information about `cilium-operator` using `--version` flag.

**Comment by aanm** [comment]
@fristonio you are right, now I'm confused :thinking:

@joestringer do you remember where we saw this?

**Comment by joestringer** [comment]
Maybe it works on master but breaks in the release?

**Comment by aanm** [comment]
ah! found it!


> Maybe it works on master but breaks in the release?

```
$ docker run -ti quay.io/cilium/operator:v1.7 cilium-operator --version
Cilium 1.7.0 05f83d08f 2020-02-21T13:00:21+01:00 go version go1.13.8 linux/amd64
```


```
$ docker run -ti docker.io/cilium/operator:v1.6.6 cilium-operator --version
Cilium
```
