### ISSUE TITLE
Pods created shortly before cilium-agent restart may have their connectivity broken upon agent restart

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10337]
User reports the following sequence of events:

* Cilium starts up
* A new pod is created
* Cilium creates the endpoint
* Cilium fails to compile the endpoint (`-ENOMEM`)
* Cilium rewrites the BPF program `Rewrote endpoint BPF program` log message
* Cilium is able to rewrite the endpoint program and log `Successful endpoint creation`
* Cilium rewrites the BPF program again `Rewrote endpoint BPF program` log message
* Cilium restarts shortly (1 second) later
* New cilium starts up, and tries to restore the endpoint
* C header cannot be found: `"C header file not found. Ignoring endpoint"`
* Endpoint is ignored.

The pod then fails to connect anywhere. `tcpdump` on the `lxc.....` device shows unreplied ARP.

**Comment by tgraf** [comment]
I've had a look at this as well. I would expect that we do the following:
* Guarantee writing of the header file on the initial endpoint regeneration and fail the `PUT /endpoint` if that cannot be completed to only let the CNI ADD operation succeed if the file could be written correctly.
* This should guarantee that we can always restore an endpoint if CNI ADD has succeeded once.

Analyzing this path...

The CNI plugin calls with:

```
        ep.SyncBuildEndpoint = true
```

This is passed on while initially building the endpoint:
```
        if err := ep.RegenerateAfterCreation(ctx, epTemplate.SyncBuildEndpoint); err != nil {
```

This will cause the initial build to be blocking:
```
       [...]
        // Wait for endpoint to be in "ready" state if specified in API call.
        if !syncBuild {
                return nil
        }

        return e.waitForFirstRegeneration(ctx)
```

This should block until the following condition becomes true:

```
        revCh := e.WaitForPolicyRevision(ctx, 1, nil)
```

The channel will be closed once the following function is called with revision 1 or higher:

```
func (e *Endpoint) setPolicyRevision(rev uint64) {
```

This happens in these paths:

1. When the realized state has been updated

   ```
   func (e *Endpoint) updateRealizedState(stats *regenerationStatistics, origDir string, revision uint64, compilationExecuted bool) error {
   ```

   which is called as the last step of `e.regenerate()`, so it seems not possible that the CNI ADD call can succeed without writing the header file.

2. When the policy revision is bumped via:

    ```
    func (e *Endpoint) PolicyRevisionBumpEvent(rev uint64) {
    ```

    This is used to not build endpoint which do not need a policy update:

    ```
    func reactToRuleUpdates(epsToBumpRevision, epsToRegen *policy.EndpointSet, rev uint64) {
        var enqueueWaitGroup sync.WaitGroup

        // Bump revision of endpoints which don't need to be regenerated.
        epsToBumpRevision.ForEachGo(&enqueueWaitGroup, func(epp policy.Endpoint) {
                if epp == nil {
                        return
                }
                epp.PolicyRevisionBumpEvent(rev)
        })
     ```

    It seems plausible that this signal could be given before the initial build is actually done and the CNI ADD would return before the initial build really completes.

**Comment by tgraf** [comment]
One more datapoint: The header file is written when it is assumed to have changed:

```
        datapathRegenCtxt.bpfHeaderfilesHash, err = e.owner.Datapath().Loader().EndpointHash(e)
        if err != nil {
                e.getLogger().WithError(err).Warn("Unable to hash header file")
                datapathRegenCtxt.bpfHeaderfilesHash = ""
                changed = true
        } else {
                changed = (datapathRegenCtxt.bpfHeaderfilesHash != e.bpfHeaderfileHash)
                e.getLogger().WithField(logfields.BPFHeaderfileHash, datapathRegenCtxt.bpfHeaderfilesHash).
                        Debugf("BPF header file hashed (was: %q)", e.bpfHeaderfileHash)
        }
        if changed {
                datapathRegenCtxt.regenerationLevel = regeneration.RegenerateWithDatapathRewrite
                if err = e.writeHeaderfile(nextDir); err != nil {
                        return fmt.Errorf("unable to write header file: %s", err)
                }
        }
```

It seems possible that the hash is stored in the endpoint:
```
                e.bpfHeaderfileHash = datapathRegenCtxt.bpfHeaderfilesHash
```

but the failed endpoint regeneration causes the endpoint regeneration directory to be removed on disk which could explain this.
