### ISSUE TITLE
Empty resource block in generated quick-install.yaml

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10350]
It seems this was introduced by #10296 . @maxbischoff can you take a look?

The quick-install.yaml is generated by running `make -C install/kubernetes clean all`

**Comment by maxbischoff** [comment]
It was definitely introduced by my PR. I did not provide resource requests for agent and operator there on purpose as those will probably depend on cluster & node size.
Maybe I am missing something, but in my opinion an empty resource block should be equivalent to the state before my merge request, is there a problem with it? Or is it just the missing update on the `quick-install.yaml`? I can add a PR that adds the new quick-install.

I can also add a PR that changes the chart to not render the `resources` if they are empty, though I do not see the point to be honest.

**Comment by aanm** [comment]
> I can also add a PR that changes the chart to not render the `resources` if they are empty, though I do not see the point to be honest.

@maxbischoff yes this was why I created the GH issue. Leaving the "resources" empty might give the impression to users that we don't want to have any resources being applied into Cilium.
