### ISSUE TITLE
Document the `io.cilium/shared-service` global service annotation

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10365]
The `io.cilium/shared-service` service annotation is not explained in the documentation anywhere.

Add documentation for it.

**Comment by dhxgit** [comment]
I found the explanation here ```https://github.com/cilium/cilium/blob/master/pkg/annotation/k8s.go#L56```
```
	// SharedService if set to false, prevents a service from being shared,
	// the default is true if GlobalService is set, otherwise false,
	// Setting the annotation SharedService to false while setting
	// GlobalService to true allows to expose remote endpoints without
	// sharing local endpoints.
	SharedService = Prefix + "/shared-service"
```

**Comment by dhxgit** [comment]
Would ```global false / shared true``` only expose the local endpoints without making global ones accessible?

**Comment by joestringer** [comment]
I believe so, yes. /cc @tgraf
