### ISSUE TITLE
Consider support for kernel 3.10 with ebpf enabled

### ISSUE THREAD

**Issue by EppO** [cilium/cilium#10373]
## Proposal / RFE

**Is your feature request related to a problem?**

Currently, we can't install cilium on RHEL 7 & CentOS 7 systems that run on kernel 3.10.
eBPF support has been backported to kernel 3.10 since `3.10.0-940.el7.x86_64`. See this [blog post](https://www.redhat.com/en/blog/introduction-ebpf-red-hat-enterprise-linux-7).
Using kernel `3.10.0-1062.9.1.el7.x86_64`, I was able to get all system requirements listed [there](https://cilium.readthedocs.io/en/stable/install/system_requirements/#linux-kernel). 

```
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_JIT=y
CONFIG_BPF_EVENTS=y
CONFIG_BPF_KPROBE_OVERRIDE=y
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_NET_SCH_INGRESS=m
CONFIG_CRYPTO_SHA1=y
CONFIG_CRYPTO_USER_API_HASH=y
```
I had to load `cls_bpf` and `sch_ingress` modules and I was all set.
I could also `mount bpffs /sys/fs/bpf -t bpf` without any issues.

The problem is that Cilium is strictly checking for the kernel version, not its capabilities:
```
level=fatal msg="kernel version: NOT OK: minimal supported kernel version is 4.8.0; kernel version that is running is: 3.10.0" subsys=linux-datapath
```

**Describe the solution you'd like**

It would be ideal that Cilium checks for eBPF capabilities instead of relying on the kernel version that doesn't indicate whether upstream patches were backported or not.

**Comment by borkmann** [comment]
Unfortunately, the blog post also says `eBPF in Red Hat Enterprise Linux 7.6 is enabled only for tracing purposes, which allows attaching eBPF programs to probes, tracepoints and perf events. Other use cases such as eBPF socket filters or eXpress DataPath (XDP) are not enabled at this stage.`, meaning `cls_bpf` only supports old classic BPF there (which I backported to RHEL back in the days ;-)).

RHEL8 is supposed to have full eBPF support, so you might want to check that. For RHEL7, the only option you might have is to open a bugzilla request there asking for eBPF networking to be supported / backported there.

**Comment by EppO** [comment]
Thank you very much for this thorough information. This is indeed a strong argument to upgrade to RHEL 8.
