### ISSUE TITLE
vxlan + IPsec - can Cilium to integrate with Wireguard instead

### ISSUE THREAD

**Issue by divfor** [cilium/cilium#10398]
since wireguard has entered into Linux kernel v5.6, will cilium integrate it to replace vxlan + IPsec for high security and performance? Wireguard uses public key as identity of tunnel endpoints that allow tunnel-IPs and tunnel-endpoint-IP to change dynamically.

from https://www.wireguard.com/#cryptokey-routing, it says:

when sending packets, the list of allowed IPs behaves as a sort of routing table, and when receiving packets, the list of allowed IPs behaves as a sort of access control list.
This is what we call a Cryptokey Routing Table: the simple association of public keys and allowed IPs.
Any combination of IPv4 and IPv6 can be used, for any of the fields. WireGuard is fully capable of encapsulating one inside the other if necessary.
Because all packets sent on the WireGuard interface are encrypted and authenticated, and because there is such a tight coupling between the identity of a peer and the allowed IP address of a peer, system administrators do not need complicated firewall extensions, such as in the case of IPsec, but rather they can simply match on "is it from this IP? on this interface?", and be assured that it is a secure and authentic packet. This greatly simplifies network management and access control, and provides a great deal more assurance that your iptables rules are actually doing what you intended for them to do.

for example, the orignal config file for node1:
```bash
[Interface]
PrivateKey = yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk=
ListenPort = 51820 # listen on node1's IP

[Peer]
PublicKey = xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=
AllowedIPs = 10.192.124.0/24   # Pod IP cidrs
Endpoint = 192.95.5.2:51820 # node2's node IP

[Peer]
PublicKey = TrMvSoP4jYQlY6RIzBgbssQqY3vxI2Pi+y71lOWWXX0=
AllowedIPs = 10.192.125.0/24  # Pod IP cidrs
Endpoint = 192.95.5.3:51820 # node3's node IP
```
could be changed to:
```bash
[Interface]
PrivateKey = yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk=
ListenPort = 51820 # listen on node1's IP

[Peer]
PublicKey = xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=
AllowedIPs = 10.192.124.0/24  # Pod IP cidrs
Endpoint = 10.4.0.1:12345 # clusterIP:port
# cilium to load-balance clusterIP to 192.95.5.2:51820 and 192.95.5.3:51820

[Peer]
PublicKey = TrMvSoP4jYQlY6RIzBgbssQqY3vxI2Pi+y71lOWWXX0=
AllowedIPs = 10.192.125.0/24  # Pod IP cidrs
Endpoint = 10.4.0.1:12345 # clusterIP:port
# cilium to load-balance clusterIP to 192.95.5.2:51820 and 192.95.5.3:51820
```

**Comment by pchaigno** [comment]
Please see #7519. Wireguard support is [currently planned for v1.8 or v1.9](https://github.com/cilium/cilium/projects/93).

**Comment by joestringer** [comment]
To avoid having many issues tracking the same underlying feature request, I will close this and mark as duplicate. If you have any further insights or even just want to :+1: the issue #7519, please follow up on that thread.
