### ISSUE TITLE
Move labels to endpoint structure

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1041]
Labels are currently stored in the `container` structure. This is done for the reason that initially, labels were retrieved from the container runtime and then correlated to the endpoint when the network plugin was launched and created the `endpoint` structure.

With the addition of CNI 2.x support, integration with mesos makes labels available during the CNI add event.

Steps:
- [ ] Move labels themselves to the endpoint structure and decouple form the container structure to allow attachment of labels to the endpoint before the container ID is known.

- [ ] When handling container create event in `daemon/docker_watcher.go`. Lookup the endpoint and update the labels.

- [ ] Ensure that we continue waiting for docker labels (`RegenerateIfReady`) if the endpoint is a docker container

- [ ] For the special case where the container create event and the CNI event are received with a large time delta. The create event will time out to find the endpoint structure before the CNI event can trigger the endpoint creation. In this case, the create container event should keep the container ID around to ensure that when we create the endpoint, we can retrieve the labels.

**Comment by aanm** [comment]
are we talking about all container's / k8s labels or only the filtered ones?
