### ISSUE TITLE
Clarify Helm version requirements

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#10418]
Our docs assume Helm 3, which should be made a more clear to the user.

We might need to document "what if I have Helm 2 in this cluster?" case. Presumably the answer is that charts can be installed with Helm 3, alongside of Helm 2 charts, but that needs to be validated.

**Comment by errordeveloper** [comment]
Actually we made it quite clear, but somehow I skipped when I was reading it. We still need to clarify regarding Helm 2+3, which I'll need to test before making a PR.

**Comment by aanm** [comment]
@errordeveloper sorry I didn't notice this GH issue was open. I've made this comment https://github.com/cilium/cilium/pull/10431#pullrequestreview-368621615

**Comment by errordeveloper** [comment]
To me this was mostly about getting started guides, and it turned out that I just missed that we did specify 3.0.0 as minimum version.

**Comment by errordeveloper** [comment]
To me this was mostly about getting started guides, and it turned out that I just missed that we did specify 3.0.0 as minimum version, I just skipped that paragraph.

**Comment by joestringer** [comment]
This is a common thread; you're definitely not the first to "just skip that paragraph". We need to make this more clear to users.

**Comment by errordeveloper** [comment]
Can either try make the *bold* or make it a _note_? I'll try a few things locally and post some screenshots :)

**Comment by errordeveloper** [comment]
> We might need to document "what if I have Helm 2 in this cluster?" case.

It's definitely supported as a [migration use-case](https://helm.sh/docs/topics/v2_v3_migration/), so it should be perfectly safe for someone with TIller in their cluster to install Cilium using Helm 3.

I'll include this in this next doc update PR.

**Comment by errordeveloper** [comment]
I think this looks a bit clearer:

![Screenshot 2020-03-05 11 45 53](https://user-images.githubusercontent.com/251467/75974449-12866a80-5ed7-11ea-9a34-b385cf5647b7.png)
