### ISSUE TITLE
Azure IPAM

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#10411]
Tasks:

- [x] Initial implementation
- [x] Unit test coverage
- [ ] CI runtime coverage (AKS)
- [x] Documentation

**Comment by joestringer** [comment]
@tgraf already fixed by  #10089? Or are there additional items remaining?

**Comment by tgraf** [comment]
> @tgraf already fixed by #10089? Or are there additional items remaining?

I've added a task list to track what is missng
