### ISSUE TITLE
Cilium no longer accepts toService flows pointing to IPs belonging to cluster nodes

### ISSUE THREAD

**Issue by olemarkus** [cilium/cilium#10465]
## Bug report

**General Information**

- Cilium version 1.7.0
- Kernel version 4.9 (debian stretch)
- Orchestration system version in use kubernetes 1.17

**How to reproduce the issue**

1. create a deployment or similar with hostNetwork
2. create a service without selector and endpoints pointing to pods in this deployment 
3. kubernetes.default.svc should be an example of the above
4. Create a policy from some pod to the service above using a toService.

With 1.6.6, the policy accepts flows through. With 1.7.0, the traffic is denied.
It looks like cilium recognizes the IPs as world in 1.6, while in 1.7 it sees them as part of host/remote-nodes. Could be that this changes the policy matching/service resolution.

**Comment by gandro** [comment]
From Slack: This also occurs with `global.kubeProxyReplacement=disabled`, therefore making it unlikely that this is directly related to host-reachable services.

**Comment by joestringer** [comment]
Firstly, thanks for the report!

I'm surprised that v1.6.x considered such remote nodes as `world` in the first place, I would have expected `host` (and hence deny).

Potential mitigations:
- You may add a policy that allows traffic `toEntities: remote-node` to allow this traffic. This would allow traffic from the selected pod to any remote node in the cluster on the ports etc. specified in your policy.
- You may attempt to set `enable-remote-node-identity` to `false` to disable the new identity. Initial reports have had some trouble with this, so if you try it then please be clear whether you attempt on a fresh cluster (first deployment of Cilium with the option set to `false`), or attempt to upgrade an existing Cilium deployment to disable. Sysdump would also be helpful in that case, in particular `cilium map get cilium_ipcache ...` and `cilium bpf ipcache list` for the relevant IP.

I think that there's a bigger change that's necessary to enable `toServices` to apply to remote nodes going forward, but we're already having discussions on this in the context of v1.8.

**Comment by olemarkus** [comment]
So `enable-remote-identity` is already `false`. This is an existing cluster and did nothing to the config map.
The workaround with using `toEntities: host` works just fine, but this policy is slightly more relaxed. The main concern is the unexpected flow denials breaking the cluster.
I would hope this regression could be fixed earlier than v1.8, although it is not the end of the world if we use the workaround for a while.

**Comment by joestringer** [comment]
@tgraf I believe that this is the issue that we discussed which was resolved in https://github.com/cilium/cilium/pull/11057 and is currently queued for backport to v1.7.3.

**Comment by tgraf** [comment]
Fixed in #11057
