### ISSUE TITLE
MySQL L7 filter

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium#10496]
## MySQL L7 filter

Add proxylib L7 filter for MySQL.

MySQL protocol documentation:
https://dev.mysql.com/doc/dev/mysql-server/8.0.11/PAGE_PROTOCOL.html

Capture samples:
https://wiki.wireshark.org/SampleCaptures#MySQL_protocol

**Comment by mrostecki** [comment]
Envoy already allows to filter MySQL protocol with *network filters* in *listeners*:

https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/mysql_proxy_filter

`NetworkFilters` field can be used in v3 API, but it's not supported v2 API. To allow to use Envoy network filters, we need to update protobufs in cilium/proxy first.

**Comment by travisghansen** [comment]
Not sure if envoy is technically required for how cilium does it's thing or if you can add other things. If the framework allows using other proxies then `ProxySQL` is probably the sanest choice for MySQL logic.

**Comment by mrostecki** [comment]
@travisghansen Cilium already uses Envoy for L7 filtering. Currently, Cilium provides support for L7 protocols mostly through Go extensions for Envoy which are part of Cilium (inside `proxylib` dir): https://docs.cilium.io/en/v1.7/envoy/extensions/?highlight=r2d2

But Envoy API v3 adds its native network filters for several L7 protocols, which are listed here: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/network_filters

For each L7 policy, Cilium creates a Listener in Envoy, in this module: https://github.com/cilium/cilium/blob/master/pkg/envoy/server.go

After upgrading to Envoy API v3, we could add network filters to the `Listener` object.

**Comment by travisghansen** [comment]
Ah cool. I’ll keep watching the space..

**Comment by vadorovsky** [comment]
Unfortunately I won't be able to find time to work on that. Since there was no much interest in the feature, I'm closing.
