### ISSUE TITLE
Cilium pods missing ressources in cluster roles

### ISSUE THREAD

**Issue by Docteur-RS** [cilium/cilium#10497]
## Bug report
While installing a Kubernetes cluster I instrucked Kubespray to deploy Cilium 1.7.1.

**When installation ended, all cilium pods were in crashCoopbackOff.**  
```
cilium-4xrlg                            0/1     CrashLoopBackOff    12         43m
cilium-6mk2t                            0/1     CrashLoopBackOff    12         43m
cilium-6rt7q                            0/1     CrashLoopBackOff    12         43m
cilium-72cq9                            0/1     CrashLoopBackOff    12         43m
cilium-9bj7r                            0/1     CrashLoopBackOff    12         43m
cilium-dn6p4                            0/1     CrashLoopBackOff    12         43m
cilium-kpxb8                            0/1     CrashLoopBackOff    12         43m
cilium-lkc5k                            0/1     CrashLoopBackOff    12         43m
cilium-n7plm                            0/1     CrashLoopBackOff    12         43m
cilium-operator-5d74fc4fd6-lfp2x        0/1     ContainerCreating   0          43m
cilium-r6226                            0/1     CrashLoopBackOff    12         43m
```

Logs showed:
```
level=fatal msg="Unable to create CiliumNode resource" error="ciliumnodes.cilium.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot create resource \"ciliumnodes\" in API group \"cilium.io\" at the cluster scope" subsys=nodediscovery
```

So I edited the cilium clusterole:
 ```
$ kubectl edit clusterrole cilium -n kube-system
...
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  - ciliumnetworkpolicies/status
  - ciliumendpoints
  - ciliumendpoints/status
  - ciliumnodes   <============
   verbs:
  - '*'
```  
Then I got:
```
level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/watchers/cilium_clusterwide_network_policy.go:132: Failed to list *v2.CiliumClusterwideNetworkPolicy: ciliumclusterwidenetworkpolicies.cilium.io is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot list resource \"ciliumclusterwidenetworkpolicies\" in API group \"cilium.io\" at the cluster scope" subsys=k8s
```

So I updated the cluster role again:
```
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  - ciliumnetworkpolicies/status
  - ciliumendpoints
  - ciliumendpoints/status
  - ciliumnodes
  - ciliumclusterwidenetworkpolicies  <===============
  verbs:
  - '*'
```
After this edit the pods were all running !  

**General Information**

- Cilium version
1.7.1
- Kernel version (run `uname -a`)
Linux master2 5.5.7-1.el7.elrepo.x86_64 #1 SMP Fri Feb 28 12:21:58 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Kubernetes:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**How to reproduce the issue**

1. Install a Kubernetes cluster using Kubespray 1.12.1 and upgrading its cilium version to 1.7.1
2. Pods are crashing
3. Edit the cilium clusterrole and add the missing ressources of cilium.io.
4. Everything should go back to normal

**Comment by aanm** [comment]
@Docteur-RS thanks for opening the issue. Did you follow the upgrade guide https://docs.cilium.io/en/v1.7/install/upgrade/ to upgrade cilium to version 1.7.1?

**Comment by Docteur-RS** [comment]
@aanm Hey !  
I don't have anything to upgrade from because there was no cilium installed previously.  

When I used the "upgrade" keyword I meant that Kubespray was initially using the 1.5.x version but I updated this value **before** I started the installation. So the version installed was directly the 1.7.1.

**Comment by aanm** [comment]
@Docteur-RS this will be fixed by https://github.com/kubernetes-sigs/kubespray/pull/5438 once it's merged

**Comment by Docteur-RS** [comment]
@aanm Ok then.  
I tried with 1.6.5 and had the same errors.  
Before I close this issue would you know what release I should try to be clear of this problem ?  
Thx

**Comment by aanm** [comment]
@Docteur-RS Can't you can still install cilium with kubespray and use [this](https://docs.cilium.io/en/v1.7/install/upgrade/) upgrade guide to upgrade to 1.7.1?

**Comment by Docteur-RS** [comment]
Sure ! I also tried to uninstall and resintall cilium the following way:
```
kubectl delete -f https://raw.githubusercontent.com/cilium/cilium/v1.7/install/kubernetes/quick-install.yaml
kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.7/install/kubernetes/quick-install.yaml
```
Its working great ! All the pods were up. 😄 

---

But I am searching for something working out of the box... In my previous Kubespray It was bundled with cilium v1.3.0 and it was working smoothly.  
I guess that there is at least one working cilium release that **has** the missing RBAC requirements and that is newer then my old v1.3.0 ?
