### ISSUE TITLE
Helm: Add support for exposing runtime configuration flags via extraArgs per-container

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#10502]
## Proposal / RFE

Presently when deploying Cilium via helm, there are a number of runtime configuration parameters supported by the various containers which are not directly exposed as configurable items via the Helm chart.

**Describe the solution you'd like**
Propose adding support to configure the runtime flags of each container using an extraArgs value. The extraArgs will tune parts of the config map, allowing the cilium operator to have visibility of the change and make the appropriate infrastructure level changes.

**Comment by pchaigno** [comment]
@seanmwinn Was this implemented as part of https://github.com/cilium/cilium/pull/13259 or is there anything still missing?
