### ISSUE TITLE
cilium-agent hangs on startup and provides no useful logging

### ISSUE THREAD

**Issue by rktidwell** [cilium/cilium#10506]
[cilium-sysdump-20200306-215302.zip](https://github.com/cilium/cilium/files/4300663/cilium-sysdump-20200306-215302.zip)

## Bug report

**General Information**

- Cilium version 1.16.3
- Kernel version 5.3.18
- Kubernetes 1.16.2
- Deployed quick-install manifest https://raw.githubusercontent.com/cilium/cilium/v1.6.3/install/kubernetes/quick-install.yaml

**How to reproduce the issue**

1. Deploy Kubernetes 1.16.2
2. Run 'kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.6.3/install/kubernetes/quick-install.yaml'
3. Cilium agent starts and registers healthy on the master node. However, on worker nodes it starts but never registers as healthy.

`....
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Detected MTU 9000" subsys=mtu
level=debug msg="creating new EventQueue" name=repository-change-queue numBufferedEvents=100 subsys=eventqueue
level=debug msg="creating new EventQueue" name=repository-reaction-queue numBufferedEvents=100 subsys=eventqueue
level=debug msg="Performing regular background work" subsys=nodemanager syncInterval=1m0s
level=debug msg="Registered BPF map" path=/run/cilium/bpffs/tc/globals/cilium_lxc subsys=bpf
level=debug msg="Registered BPF map" path=/run/cilium/bpffs/tc/globals/cilium_ipcache subsys=bpf
level=debug msg="Registered BPF map" path=/run/cilium/bpffs/tc/globals/cilium_metrics subsys=bpf
level=debug msg="Registered BPF map" path=/run/cilium/bpffs/tc/globals/cilium_tunnel_map subsys=bpf
level=debug msg="Registered BPF map" path=/run/cilium/bpffs/tc/globals/cilium_lb4_services_v2 subsys=bpf
level=debug msg="Registered BPF map" path=/run/cilium/bpffs/tc/globals/cilium_lb4_backends subsys=bpf
level=debug msg="Registered BPF map" path=/run/cilium/bpffs/tc/globals/cilium_lb4_reverse_nat subsys=bpf
level=debug msg="Registered BPF map" path=/run/cilium/bpffs/tc/globals/cilium_lb4_rr_seq_v2 subsys=bpf
level=debug msg="Starting new controller" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Restored backend IDs" backendIDs="map[]" subsys=daemon
level=debug msg="Controller func execution time: 84.275µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=info msg="Restore service IDs from BPF maps" duration="211.036µs" failed=0 removed=0 restored=0 skipped=0 subsys=daemon
level=info msg="Removing stale endpoint interfaces" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://10.96.0.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=debug msg="Controller func execution time: 245.316µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Controller func execution time: 160.975µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Controller func execution time: 171.002µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Controller func execution time: 211.557µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Controller func execution time: 207.11µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Controller func execution time: 257.866µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Controller func execution time: 260.612µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Controller func execution time: 251.174µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Controller func execution time: 281.478µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229c
level=debug msg="Controller func execution time: 270.928µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=c163df0a-5ff3-11ea-b2b4-0cc47a6f229`

There are few issues I see:

1. Most importantly, the cilium-agent never seems to come online despite no errors being registered in the logs.
2. I have enabled debug logging, and I don't get enough information from it to point me in a helpful direction. Admittedly, this could be that I don't know what I'm doing :smile: It could also mean that a little more instrumentation is needed. The logs give me no indication as to what cilium-agent is doing and what next steps might be.

**Comment by aanm** [comment]
@rktidwell thanks for opening the GH issue.

I do see the following in cilium-agent logs:

```
2020-03-06T21:45:11.44117384Z level=warning msg="BPF filesystem is going to be mounted automatically in /run/cilium/bpffs. However, it probably means that Cilium is running inside container and BPFFS is not mounted on the host. for more information, see: https://cilium.link/err-bpf-mount" subsys=bpf
2020-03-06T21:45:11.44133154Z level=warning msg="================================= WARNING ==========================================" subsys=bpf
2020-03-06T21:45:11.441338071Z level=warning msg="BPF filesystem is not mounted. This will lead to network disruption when Cilium pods" subsys=bpf
2020-03-06T21:45:11.441338071Z level=warning msg="are restarted. Ensure that the BPF filesystem is mounted in the host." subsys=bpf
2020-03-06T21:45:11.441351964Z level=warning msg="https://docs.cilium.io/en/stable/kubernetes/requirements/#mounted-bpf-filesystem" subsys=bpf
2020-03-06T21:45:11.441351964Z level=warning msg="====================================================================================" subsys=bpf
```

This needs to be fixed, but before digging more, can you try it out with https://raw.githubusercontent.com/cilium/cilium/v1.7.1/install/kubernetes/quick-install.yaml

Thanks!

**Comment by christarazi** [comment]
@rktidwell Has using Cilium v1.7.1 resolved your issue?
