### ISSUE TITLE
Cilium agent in ENI-mode fails to allocate ip addresses with managed etcd as kvstore

### ISSUE THREAD

**Issue by rreinurm** [cilium/cilium#10528]
## Bug report

**General Information**

- Cilium version v1.7.1
- Kernel version Linux 5.3.0-40-generic #32~18.04.1-Ubuntu
- Orchestration system version in use
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump 
[cilium-sysdump-20200310-152050.zip]

**How to reproduce the issue**

1. Create cluster with kubeadm for example I use `kubeadm init --pod-network-cidr=<your-subnet> --skip-phases=addon/kube-proxy `
2. Join couple of worker nodes
3. Generate kubernetes config:
```helm template cilium/cilium \
  --version v1.7.1 \
  --namespace kube-system \
  --set global.prometheus.enabled=true \
  --set global.kubeProxyReplacement=strict \
  --set global.k8sServiceHost=<your-k8s-master-ip> \
  --set global.k8sServicePort=6443 \
  --set global.etcd.enabled=true \
  --set global.etcd.managed=true \
  --set global.tunnel=disabled \
  --set global.eni=true \
  --set global.egressMasqueradeInterfaces=<your-interface> \
  --set global.masquerade=false \
  --set global.nodePort.mode=snat \
  --set global.nodeinit.enabled=true
```
4. Following logs should appear:
```level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumClusterwideNetworkPolicy/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumClusterwideNetworkPolicy/v2 subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=v2.CiliumEndpoint subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=v2.CiliumEndpoint subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=v2.CiliumEndpoint subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=v2.CiliumNode subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=v2.CiliumNode subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=v2.CiliumNode subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=v2.CiliumIdentity subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=v2.CiliumIdentity subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=v2.CiliumIdentity subsys=k8s
level=info msg="k8s mode: Allowing localhost to reach local endpoints" subsys=daemon
level=info msg="Initializing node addressing" subsys=daemon
level=info msg="Initializing CRD-based IPAM" subsys=ipam
level=info msg="Subscribed to CiliumNode custom resource" name=k8s-cilium1mt subsys=ipam
level=info msg="Successfully created CiliumNode resource" subsys=nodediscovery
level=info msg="Waiting for CiliumNode custom resource to become available..." name=k8s-cilium1mt subsys=ipam
level=info msg="Successfully synchronized CiliumNode custom resource" name=k8s-cilium1mt subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 name=k8s-cilium1mt required=8 subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 name=k8s-cilium1mt required=8 subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 name=k8s-cilium1mt required=8 subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 name=k8s-cilium1mt required=8 subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 name=k8s-cilium1mt required=8 subsys=ipam
```

Waitig for IPs continue until
```level=info msg="Exiting due to signal" signal=terminated subsys=daemon```

As soon as I disable etcd as kvstore and use crd (default) cilium agents are able to allocate ip addresses.
```  --set global.etcd.enabled=false
  --set global.etcd.managed=false 
```

**Comment by joestringer** [comment]
@aanm I suspect that the combination of

```--set global.etcd.managed=true \```

 and

```--set global.eni=true \```

...leads to problems here. The managed etcd instances need IPs, and I think by default they're launched as regular pods, not host-networking right? So then to allocate an IP, you need to use the operator because of ENI mode. However in etcd mode this would presumably try to share the IPs with the daemon via the etcd instance, which is unavailable until we give it an IP. Chicken and egg.

I'd guess for this to work, we'd at least initially require allocation to be performed via CRD, then switch over to etcd later when it's available.

**Comment by joestringer** [comment]
FWIW this affects more than just large-scale users; Users who intend to spin up several smaller clusters and use clustermesh to connect them could hit this kind of issue as well (as in this case).

**Comment by joestringer** [comment]
I've suggested that the workaround would be to chain on top of aws-cni for this type of setup.

```
  --set global.eni=false \
  --set global.cni.chainingMode=aws-cni \
  --set global.masquerade=false \
  --set global.tunnel=disabled \
  --set global.nodeinit.enabled=true \
```

**Comment by rreinurm** [comment]
https://github.com/cilium/cilium/issues/10802

**Comment by danwent** [comment]
I've updated the title here to indicate the the issue is with a managed etcd kv-store (i.e., cilium-etcd-operator).   We have many people using ENI mode with external etcd kv-store, and based on @joestringer 's comment, it seems that this is a chicken and egg problem related to etcd pods being managed cilium endpoints.

**Comment by e36-cicd** [comment]
I've just been affected by this issue using Cilium 1.8.0 (indeed using Cilium-managed etcd).
Any idea if it has been fixed in a more recent version?
