### ISSUE TITLE
Enable IPv6-only k8s runtime tests once kubeadm supports IPv6

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1053]

**Comment by aanm** [comment]
@eloycoto FYI

**Comment by aanm** [comment]
We can enable IPv6 since kubeadm 1.9

**Comment by ianvernon** [comment]
Look into adding this to the Datapath Configuration tests in Ginkgo - it's easy to add a new test to pull in the DaemonSet that you want to test against.
