### ISSUE TITLE
CI: K8sFQDNTest BeforeAll fail: Error getting IPs for test

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10538]
## CI failure

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/17833/testReport/junit/Suite-k8s-1/11/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/
[6b438aba_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip](https://github.com/cilium/cilium/files/4315112/6b438aba_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip)

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:384
Error getting IPs for test
Expected
    <*net.DNSError | 0xc000c1c740>: {
        Err: "server misbehaving",
        Name: "vagrant-cache.ci.cilium.io",
        Server: "147.75.207.208:53",
        IsTimeout: false,
        IsTemporary: true,
        IsNotFound: false,
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/fqdn.go:50
```

~@jrajahalme @raybejjani I find it interesting that this shows up in PRs shortly after the recent FQDN changes, does this look familiar at all?~ Initial triage suggests this is unrelated to cilium runtime.

**Comment by joestringer** [comment]
I'm actually not finding much in the associated sysdump which suggests a failure pretty early in the ginkgo run, before Cilium is running properly.

from `test-output.log`:

```
time="2020-03-10T14:12:28Z" level=debug msg="running command: kubectl label --overwrite node k8s3 cilium.io/ci-node=k8s3"
time="2020-03-10T14:12:28Z" level=error msg="Error executing command 'kubectl label --overwrite node k8s3 cilium.io/ci-node=k8s3'" error="exit status 1"
time="2020-03-10T14:12:28Z" level=error msg="Error executing command 'kubectl label --overwrite node k8s3 cilium.io/ci-node=k8s3'" error="exit status 1"
cmd: "kubectl label --overwrite node k8s3 cilium.io/ci-node=k8s3" exitCode: 1 duration: 48.166899ms stdout:

stderr:
Error from server (NotFound): nodes "k8s3" not found
```

**Comment by nebril** [comment]
Found this in https://jenkins.cilium.io/job/Ginkgo-CI-Tests-k8s1.11-Pipeline/378/execution/node/110/log/?consoleFull

**Comment by nebril** [comment]
This seems to be resolved.
