### ISSUE TITLE
Cilium errors with "Unable to enqueue endpoint policy visibility event" on every endpoint create

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10543]
it seems that cilium is printing the error `level=error msg="Unable to enqueue endpoint policy visibility event"` every time a pod is created. The underlying error is `error="unable to Enqueue event"` which means the event queue was nil for some reason.

We should find out why this happens (I've a suspicion that we are regenerating the policy for all endpoints before this endpoint has its event queue created)

**Comment by joestringer** [comment]
I believe that this is a breakage between v1.7.0-rc1 and v1.7.0-rc2 introduced in commit acbf8802f042fa94548f17ea3cd5a20058715a60.

**Comment by joestringer** [comment]
An attempt to update the visibility policy is being made here when handling the endpoint join API request:

https://github.com/cilium/cilium/blob/beb401bf019839f6aba0d6abfdfab6bb22320d7d/daemon/endpoint.go#L269

However, the endpoint is not added to the endpointmanager until this later point in the same function:

https://github.com/cilium/cilium/blob/beb401bf019839f6aba0d6abfdfab6bb22320d7d/daemon/endpoint.go#L303

Note that the eventqueue does not run until `endpoint.Expose()` is run, because the eventqueue is named using the endpoint ID, and the endpoint ID is not allocated until that point.

**Comment by joestringer** [comment]
Mitigation for anyone following at home should be to ensure that the pods are created first, and then apply the visibility annotation onto the *pod* manually later per the guide:

http://docs.cilium.io/en/stable/policy/visibility/

Applying the annotation via deployment will likely always trigger this issue.

**Comment by michi-covalent** [comment]
@aanm @joestringer i follow https://github.com/cilium/hubble/tree/master/tutorials/deploy-hubble-servicemap to deploy the latest cilium and jobs-demo that uses the pod annotation for visibility policy. after that, i do `kubectl get cep` to see if visibility policy is enabled:
```
kubectl get cep -n jobs-demo

NAME                            ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4            IPV6
coreapi-57466fd965-kn4mx        2386          46615         false                 false                                    ready            10.15.143.101
crawler-67cf8bbcdd-pw5r6        469           8632          false                 false                                    ready            10.15.204.190
elasticsearch-dbf4fc4df-bk5d2   170           62699         false                 false                                    ready            10.15.135.204
jobposting-57bd4c8596-75rvx     1030          62556         false                 false                                    ready            10.15.132.206
kafka-0                         2666          6714          false                 false                                    ready            10.15.114.144
loader-69fb98c8b5-wj5xw         708           24523         false                 false                                    ready            10.15.167.125
recruiter-54f94f7b87-8b5v7      2415          1049          false                 false                                    ready            10.15.180.16
zookeeper-66b5f99f97-hzwzb      300           6220          false                 false                                    ready            10.15.135.70
```
