### ISSUE TITLE
global.containerRuntime.socketPath ignored

### ISSUE THREAD

**Issue by ktsakalozos** [cilium/cilium#10544]
## Bug report

This is issue affects the kubernetes installation done via the manifests produced with helm.

**General Information**

- Cilium version (run `cilium version`): v1.6 vs v1.7
- Kernel version (run `uname -a`): Linux ip-172-31-20-243 4.15.0-1060-aws #62-Ubuntu SMP Tue Feb 11 21:23:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): 1.17

**How to reproduce the issue**

On v1.16 we were able to set the `global.containerRuntime.socketPath` when producing the cilium yaml manifest with helm. This option sets a non default path of the containerd socket. On 1.7 this option is ignored. It is still in the `values.yaml` in [1] but is ignored in v1.7. `socketPath` is present and used in v1.6 daemonset.

Is there a reason this was dropped? Since MicroK8s needs it, I patched the helm output yaml and it worked fine.

Here is a script that will place the `cilium.yaml` under `/tmp/`: 
```
# change the following to v1.6 to get the yaml with the right socketPath
CILIUM_VERSION="v1.7"
CILIUM_ERSION=$(echo $CILIUM_VERSION | sed 's/v//g')
SOURCE_URI="https://github.com/cilium/cilium/archive"
CILIUM_DIR="cilium-$CILIUM_ERSION"
CILIUM_CNI_CONF="plugins/cilium-cni/05-cilium-cni.conf"
CILIUM_LABELS="k8s-app=cilium"
NAMESPACE=kube-system

SNAP_DATA="/var/snap/microk8s/current"
SNAP_COMMON="/var/snap/microk8s/common"

mkdir -p /tmp/cilium
cd /tmp/cilium
curl -L $SOURCE_URI/$CILIUM_VERSION.tar.gz -o "/tmp/cilium/cilium.tar.gz"
gzip -f -d /tmp/cilium/cilium.tar.gz
tar -xf /tmp/cilium/cilium.tar "$CILIUM_DIR/install" "$CILIUM_DIR/$CILIUM_CNI_CONF"
cp /tmp/cilium/$CILIUM_DIR/$CILIUM_CNI_CONF "$SNAP_DATA/args/cni-network/05-cilium-cni.conf"

cd "/tmp/cilium/$CILIUM_DIR/install/kubernetes"
helm template cilium \
   --namespace $NAMESPACE \
   --set global.cni.confPath="$SNAP_DATA/args/cni-network" \
   --set global.cni.binPath="$SNAP_DATA/opt/cni/bin" \
   --set global.cni.customConf=true \
   --set global.containerRuntime.integration="containerd" \
   --set global.containerRuntime.socketPath="$SNAP_COMMON/run/containerd.sock" > "/tmp/cilium.yaml"
```

[1] https://github.com/cilium/cilium/blob/v1.7/install/kubernetes/cilium/values.yaml#L180
[2] https://github.com/cilium/cilium/blob/v1.6/install/kubernetes/cilium/charts/agent/templates/daemonset.yaml#L301

**Comment by joestringer** [comment]
@ktsakalozos what's the behaviour if the flag is ignored? Does Cilium fail to start up?

**Comment by ktsakalozos** [comment]
Thank you for the quick response @joestringer. It made me double check what steps I was following. It seems ignoring the socketPath was not the real issue. The problem was with the `/var/run/cilium` path that had to be changed to `$SNAP_DATA/var/run/cilium` as we do in  https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.cilium.sh#L80.

Closing this. I will try to contribute to cilium in a more meaning full way next time. Apologies for wasting your time.

**Comment by joestringer** [comment]
No worries @ktsakalozos , thanks for digging in to validate whether we broke something. There's enough different ways to run Cilium that it's always possible that we unintentionally regressed somewhere so we're happy to have folks like you digging in, deploying, and providing feedback :-)
