### ISSUE TITLE
Doc tests should not take long

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#10555]
It looks like running documentation tests in CI is pretty slow right now. I don't have an exact number yet, but it seems much longer than 10m. I think it should only take a few minutes to tests doc changes, I'd also consider auto-merge on approval.

**Comment by errordeveloper** [comment]
Here is an example: https://jenkins.cilium.io/job/Cilium-PR-Doc-Tests/1984/

26 min waiting;
27 min build duration;
27 min total from scheduled to completion.

It looks like it mostly just waits for Jenkins to run the job...

**Comment by pchaigno** [comment]
For pull requests that don't change the documentation's dependencies, maybe we could have a different, already-provisioned Docker image? That would eliminate the time to download and install dependencies for most cases.

**Comment by errordeveloper** [comment]
Perhaps, but from the above it seems like it is mostly due to Jenkins being busy?

**Comment by joestringer** [comment]
Could we set up a travis target for the docs instead of relying on the jenkins infrastructure?

**Comment by errordeveloper** [comment]
Yeah, that's pretty much what I am thinking, but GitHub Actions would be my
preference :)
