### ISSUE TITLE
ARP responder replying to requests for IP on the same endpoint that owns that IP.

### ISSUE THREAD

**Issue by jcaamano** [cilium/cilium#10574]
## Bug report

It looks like the ARP responder is answering to ARP requests for IPs on the same endpoint that owns that IP. If that IP is reassigned within the pod, it may fail if there is some duplicate address detection going on which expects that nobody to answer ARP broadcasts for the IP that is being assigned.

This can happen when using kubevirt for VM instances with interfaces configured in bridge mode, where the IP of the pod is reassigned to the VM hosted within the pod.

**General Information**

- Cilium version: 1.5.3)
- Kernel version: 4.12
- Orchestration system version in use: 1.15
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. Deploy kubernetes with cilium and kubevirt.
2. Run a VM instance with pod network mode and bridge interface mode. Use a VM that does duplicate address detection. In our case we were using SLES images, probably openSUSE as well. Another way to verify is to run an arping from the VM and no answer should be expected as nobody except the VM is holding that IP.

**Comment by aanm** [comment]
> ## Bug report
> It looks like the ARP responder is answering to ARP requests for IPs on the same endpoint that owns that IP. If that IP is reassigned within the pod, it may fail if there is some duplicate address detection going on which expects that nobody to answer ARP broadcasts for the IP that is being assigned.
> 

@jcaamano thanks for opening the GH issue. Can you clarify what you mean by "IPs on the same endpoint that owns that IP"?

> This can happen when using kubevirt for VM instances with interfaces configured in bridge mode, where the IP of the pod is reassigned to the VM hosted within the pod.
> 
> **General Information**
> 
> * Cilium version: 1.5.3)
> * Kernel version: 4.12
> * Orchestration system version in use: 1.15
> * Link to relevant artifacts (policies, deployments scripts, ...)
> * Upload a system dump (run `curl -sLO https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip && python cilium-sysdump.zip` and then attach the generated zip file)
> 
> **How to reproduce the issue**
> 
> 1. Deploy kubernetes with cilium and kubevirt.
> 2. Run a VM instance with pod network mode and bridge interface mode. Use a VM that does duplicate address detection. In our case we were using SLES images, probably openSUSE as well. Another way to verify is to run an arping from the VM and no answer should be expected as nobody except the VM is holding that IP.

**Comment by jcaamano** [comment]
Sorry for the crude description.

So, within a pod:

```
bash-5.0# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
12: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 46:f7:31:2a:64:92 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.201.2.206/32 brd 10.201.2.206 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::44f7:31ff:fe2a:6492/64 scope link 
       valid_lft forever preferred_lft forever
```

Still in the pod:
```
bash-5.0# arping -I eth0 -c 1 10.201.2.206
ARPING 10.201.2.206 from 10.201.2.206 eth0
Unicast reply from 10.201.2.206 [4A:E8:4B:06:B8:C0]  0.571ms
Sent 1 probes (1 broadcast(s))
Received 1 response(s)
```

Someone is answering arp requests for the pod's IP with mac 4A:E8:4B:06:B8:C0, this is not the pod's mac.

On that pod's node:
```
sles@cluster1-worker-1:~> ip l show lxc8f587c18c59a
13: lxc8f587c18c59a@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 4a:e8:4b:06:b8:c0 brd ff:ff:ff:ff:ff:ff link-netnsid 3
```
It's the mac of a pod's veth on the host side.

Getting the enpoing info
```
kabir@kabir:~> kctl1 -n kube-system exec -ti cilium-gl4fm -- cilium endpoint get 3611
...
      "networking": {
        "addressing": [
          {
            "ipv4": "10.201.2.206"
          }
        ],
        "host-mac": "4a:e8:4b:06:b8:c0",
        "interface-index": 13,
        "interface-name": "lxc8f587c18c59a",
        "mac": "46:f7:31:2a:64:92"
      },
....
```

So it's the mac of that pod's veth on the host side.

From the pods perspective, I think it is reasonable to expect that nobody answers for an arp request on it's own IP if there is nothing else holding that IP on the same L2 segment.

I am assuming this is happening [here](https://github.com/cilium/cilium/blob/a66d581324d8c2bf43eb82726923a60126bd3679/bpf/bpf_lxc.c#L773) and then [here](https://github.com/cilium/cilium/blob/a66d581324d8c2bf43eb82726923a60126bd3679/bpf/lib/arp.h#L51). 

So one solution could be to compare the target ip on the arp request with LXC_IPV4 and drop or let the kernel handle it on match.

I am guessing a lot here but it sounds reasonable I can attempt to fix

**Comment by tgraf** [comment]
The reason for the current behavior, answer to any IP, is that was difficult to correctly restore the router IP. If for some reason, the router IP cannot be restored after a restore, it is allocated from the range. This new router IP can be different than an existing configured router IP inside of an existing pod. This resulted in connectivity issues.

While we can certainly fix this, we need to be sure to not break the router IP restore problematic.

**Comment by jcaamano** [comment]
> The reason for the current behavior, answer to any IP, is that was difficult to correctly restore the router IP. If for some reason, the router IP cannot be restored after a restore, it is allocated from the range. This new router IP can be different than an existing configured router IP inside of an existing pod. This resulted in connectivity issues.
> 
> While we can certainly fix this, we need to be sure to not break the router IP restore problematic.

@tgraf if I understand it correctly, not answering to the pod IP would be an improvement and I don't think it would break the above mechanic. Anyway, do you have a code pointer where this is going on so I can understand it better? Thanks!

**Comment by tgraf** [comment]
> @tgraf if I understand it correctly, not answering to the pod IP would be an improvement and I don't think it would break the above mechanic. Anyway, do you have a code pointer where this is going on so I can understand it better? Thanks!

Yes, I agree. A good fix here could be to ignore the pod IP but keep on responding to all other IPs. That would solve the DAD problem while not relying on restoring the router IP consistently.

**Comment by jcaamano** [comment]
@tgraf In regards to router IP restore problematic, if the problem is that the router IP allocated by the agent might be different to the gateway set on existing pods routing tables, would it be enough and make sense to have something like LXC_IPV4_GATEWAY in lxc_config (as part of the endpoint config static data) to reflect this?
