### ISSUE TITLE
Create unstripped cilium image binary

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10606]
follow up of https://github.com/cilium/cilium/pull/10167#issuecomment-600012343

**Comment by tgraf** [comment]
Moving the discussion from #10167 to this issue

> @tgraf we need an unstripped binary in case we want to debug a live cilium process. If that live process is running the stripped binary we should have the unstripped binary also available.

What exact operation is to debug? Are you talking about running a debugger? Are you talking about gops debugging? How commonly do we need this information available right now?

I assume users will typically run the unstripped version and we would require them to run a different image and reproduce? Is a Makefile target to build unstripped images on demand sufficient?

**Comment by aanm** [comment]
> Moving the discussion from #10167 to this issue
> 
> > @tgraf we need an unstripped binary in case we want to debug a live cilium process. If that live process is running the stripped binary we should have the unstripped binary also available.
> 
> What exact operation is to debug? Are you talking about running a debugger? Are you talking about gops debugging? How commonly do we need this information available right now?

My reply was based on the entire discussion of that PR, yes running with delve or gdb.

> 
> I assume users will typically run the unstripped version and we would require them to run a different image and reproduce? Is a Makefile target to build unstripped images on demand sufficient?

It's not a matter of how commonly we need it but a matter of when we will need it would be better to have it prepared. My understanding is that users will run the **stripped** version, not the **unstripped** version. Having a **unstripped** binary already build will make sure that:

1) The stripped version was definitely created from the unstripped version.
2) The developer helping the user does not need to setup an development environment to build the exact unstripped version of the cilium-agent the user is running. This might include exact golang version for example.
3) Making the binary available for the user for live debugging would already exist so there is not need for the developer to share binaries build on step 2). The user would simply need to run `docker create --name cilium-v1.7.1 docker.io/cilium/cilium-unstripped:v1.7.1 && docker cp cilium-v1.7.1:/usr/bin/cilium-agent ./`
