### ISSUE TITLE
ipam: review pkg/ipam

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#10619]
Right now `pkg/ipam` is used by daemon as well as operator, it maybe appropriate to separate some of the functions into another package, as some daemon-specific functions are dealing with node-level aspects, most notably the [`ReserveLocalRoutes`](https://github.com/cilium/cilium/blob/630681c304c6edb5966364fce6654bd2f172fb4a/pkg/ipam/ipam.go#L147-L195) function, while other functions operate in the cluster context.

**Comment by soumynathan** [comment]
Is this PR about just reviewing or refactoring the code.
I would like to take up this work.
