### ISSUE TITLE
After installing cilium 1.7.1 on minikube + cri-o, coredns never stops respawning

### ISSUE THREAD

**Issue by renich** [cilium/cilium#10624]
## Bug report

Basically, coredns will terminate and start until the point of running. Then, the loop starts.

**General Information**

- Cilium version (run `cilium version`): 1.7.1
- Kernel version (run `uname -a`): Linux introdesk.g02.org 5.5.8-200.fc31.x86_64 #1 SMP Thu Mar 5 21:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)

**How to reproduce the issue**

- start minikube with cri-o: https://kubernetes.io/docs/setup/learning-environment/minikube/#starting-a-cluster-on-alternative-container-runtimes
- install cilium:

**Comment by aanm** [comment]
@renich did you follow this tutorial to install cilium?

https://docs.cilium.io/en/v1.7/kubernetes/configuration/#crio

**Comment by renich** [comment]
Not that one. Let me follow it and I'll report back in a moment.

**Comment by renich** [comment]
OK, confirmed. It works fine. I suggest adding a note to this at: https://docs.cilium.io/en/v1.7/gettingstarted/minikube/. No way I could've known that.

**Comment by renich** [comment]
BTW, thank you very much for the support.
