### ISSUE TITLE
CI: Test failure output doesn't point at the code

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#10637]
The way we use Ginkgo at the moment results in output like this:
```
13:36:30  • Failure [798.823 seconds]
13:36:30  K8sDatapathConfig
13:36:30  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
13:36:30    ManagedEtcd
13:36:30    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
13:36:30      Check connectivity with managed etcd [It]
13:36:30      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
13:36:30  
13:36:30      cilium pre-flight checks failed
```

Namely, we see file:line reference like `test/ginkgo-ext/scopes.go:430`, which is not where the tests are, it's the helper function. This can be fixed by using Gingko matchers instead of helper functions.

**Comment by errordeveloper** [comment]
Here are some example matchers in [`eksctl` unit tests](https://github.com/weaveworks/eksctl/blob/68c3bce3e2540ec423665dab2fb79f9319fe6d07/pkg/cfn/template/matchers/matchers.go), and here is an example of the usage:

https://github.com/weaveworks/eksctl/blob/68c3bce3e2540ec423665dab2fb79f9319fe6d07/pkg/cfn/template/api_test.go#L55-L80

**Comment by aanm** [comment]
@errordeveloper it would be helpful to have a link where this situation occurred. The output might be tricky to get it first.

**Comment by errordeveloper** [comment]
@aanm this is not a question about the particular error, I'm suggesting how the output can be improved.

The output currently says the error occurred at [`test/ginkgo-ext/scopes.go:430`](https://github.com/cilium/cilium/blob/970a25934cb475e8142b7104d1ed3f4acf354546/test/ginkgo-ext/scopes.go#L430), inside of `wrapItFunc`.

While it should be referring to [`test/k8sT/DatapathConfiguration.go:433`](https://github.com/cilium/cilium/blob/970a25934cb475e8142b7104d1ed3f4acf354546/test/k8sT/DatapathConfiguration.go#L433).

This can be fixed, we are just not using Ginkgo properly.

**Comment by brb** [comment]
> This can be fixed, we are just not using Ginkgo properly.

That would be awesome if it gets fixed!

**Comment by errordeveloper** [comment]
Fixing this would imply reworking most of `ginkgo-ext`.

**Comment by errordeveloper** [comment]
Unstale.
