### ISSUE TITLE
enhance k8s 1.18 metrics & error context integration

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10655]
- [x] update libraries to 1.18 https://github.com/cilium/cilium/pull/10654
- [ ] Check each usage of the `context.Context` for the k8s client methods
    - [x] Client calls made from a function with a context.Context already available
    - [ ] Client calls using a context.TODO()
- [ ] Expose more metrics as available in k8s.io/client-go/tools/metrics/metrics.go:L50-59

**Comment by christarazi** [comment]
I can take this and start on the `context.TODO()`

**Comment by christarazi** [comment]
@aanm Taking a look at your PR #10654, I see in your message that some `context.TODO()`s need some more investigation into. Any instances in particular you had in mind?

**Comment by aanm** [comment]
> @aanm Taking a look at your PR #10654, I see in your commit message that some `context.TODO()`s need some more investigation into. Any instances in particular you had in mind?

All of them, if there are ones that don't make sense change them to `context.Background()` for example the ones in `createUpdateCRD` should be changed to `context.Background()` as they are only used when cilium-agent starts.

**Comment by joestringer** [comment]
@aanm What is the actual impact of the remaining tasks?

Right now if any users search for k8s 1.18 support they are likely to find this issue and assume that Cilium does not work with k8s 1.18. I don't think that's the case. Should we rename the issue title to make it clear what kind of followup items these are to eg "refactor to use more k8s 1.18 structures" or "enhance k8s 1.18 metrics & error context integration"?

**Comment by cortopy** [comment]
@joestringer you are totally right. I landed here when checking if cilium supports 1.18. But according to released docs, cilium does not support 1.18 yet

https://github.com/cilium/cilium/blob/v1.7/Documentation/kubernetes/compatibility.rst says no 1.18 (master says it does)

**Comment by aanm** [comment]
@cortopy Although 1.7 does not say it specifically you can run it with k8s 1.18.

**Comment by cortopy** [comment]
ah! that's good to know. I've actually been holding upgrading to 1.18 because of cilium :+1:
