### ISSUE TITLE
CI: Travis failed on arm64: ENISuite.TestNodeManagerManyNodes

### ISSUE THREAD

**Issue by Jianlin-lv** [cilium/cilium#10677]
CI failure Link:
https://travis-ci.com/github/cilium/cilium/jobs/300891605#L643

```
----------------------------------------------------------------------
FAIL: node_manager_test.go:544: ENISuite.TestNodeManagerManyNodes
node_manager_test.go:598:
    c.Assert(metricsapi.AllocatedIPs("available"), check.Equals, numNodes*minAllocate)
... obtained int = 4
... expected int = 1000
OOPS: 18 passed, 1 FAILED
--- FAIL: Test (7.45s)
FAIL
coverage: 6.2% of statements in ./...
FAIL	github.com/cilium/cilium/pkg/aws/eni	7.901s
FAIL
Makefile:146: recipe for target 'unit-tests' failed
make: *** [unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.
```

**Comment by pchaigno** [comment]
I've seen a different occurrence of (likely) the same bug, on aarch64 as well:
```
FAIL: node_manager_test.go:546: ENISuite.TestNodeManagerManyNodes

node_manager_test.go:611:
    c.Assert(metricsapi.AvailableInterfaces(), check.Not(check.Equals), 0)
... obtained int = 0
... expected int = 0
```

**Comment by Jianlin-lv** [comment]
> I've seen a different occurrence of (likely) the same bug, on aarch64 as well:
> 
> ```
> FAIL: node_manager_test.go:546: ENISuite.TestNodeManagerManyNodes
> 
> node_manager_test.go:611:
>     c.Assert(metricsapi.AvailableInterfaces(), check.Not(check.Equals), 0)
> ... obtained int = 0
> ... expected int = 0
> ```

Yes, I have been observing the results of constructing Travis CI in the community and I have seen those similar situation, which can be reproduced in our lab. I am investigating those issue.

**Comment by Jianlin-lv** [comment]
@joestringer  @ungureanuvladvictor 

In the process of troubleshooting this issue, I encountered a confusion and hope to get your help,

First of all, the summary of the IP allocation process is as follows: (If there is something wrong, please correct it)
```
MaintainIPPool
->n.maintainIPPool	 **Step1**
->n.recalculate()
->n.manager.resyncTrigger.Trigger()
	->resyncNode
		->node.recalculate()	**Step2**
		->node.poolMaintainer.Trigger()==MaintainIPPool
			->n.maintainIPPool	       **Step3**
			->n.recalculate()	       **Step4**
			->n.manager.resyncTrigger.Trigger()
				->resyncNode
				->node.recalculate()	**Step5**
```

Add debug information to recalculate-> ResyncInterfacesAndIPs and print out the assigned IP address: e.Address
```
@@ -432,6 +432,8 @@ func (n *Node) ResyncInterfacesAndIPs(ctx context.Context, scopedLog *logrus.Ent
                        if !ok {
                                return nil
                        }
+                       fmt.Println("lvlin e.id: ", e.ID, "e.Addresses: ", len(e.Addresses), "e.Number: ", e.Number)
+                       fmt.Println("e.Address: ", e.Addresses)
                        n.enis[e.ID] = *e

```
TestNodeManagerManyNodes is a case that allocates 10 IPs

Step1,  9IPs are allocated;
Step2. Print the assigned address details
e.Address:  [10.63.26.206 10.17.39.100 10.250.100.44 10.108.240.246 10.200.166.215 10.7.79.184 10.178.148.208 10.150.46.84 10.19.187.140]

Step3. Continue to allocate one IP; success
e.Address:  [10.63.26.206 10.17.39.100 10.250.100.44 10.108.240.246 10.200.166.215 10.7.79.184 10.178.148.208 10.150.46.84 10.19.187.140 10.217.34.243]

Step4. Print the assigned address details
e.Address:  [10.63.26.206 10.17.39.100 10.250.100.44 10.108.240.246 10.200.166.215 10.7.79.184 10.178.148.208 10.150.46.84 10.19.187.140]

Step5. 10 valid IPs, no need to continue to assign addresses
e.Address:  [10.63.26.206 10.17.39.100 10.250.100.44 10.108.240.246 10.200.166.215 10.7.79.184 10.178.148.208 10.150.46.84 10.19.187.140 10.217.34.243]

Done

I don’t know what happened between Step4 and Step5, what triggered the update of rev.Resource.(* EniTypes.ENI)?

When this test case was abnormal, I found that the addresses output by Step4 and Step5 were the same, so the poolMaintainer was triggered again, which eventually caused the use case execution to fail.

**Comment by Jianlin-lv** [comment]
A similar issue on the amd64 platform:
https://travis-ci.com/github/cilium/cilium/jobs/335548630#L3923
https://travis-ci.com/github/cilium/cilium/jobs/335282883#L3848
https://travis-ci.com/github/cilium/cilium/jobs/334651333#L3952

**Comment by pchaigno** [comment]
> A similar issue on the amd64 platform:
> https://travis-ci.com/github/cilium/cilium/jobs/335548630#L3923
> https://travis-ci.com/github/cilium/cilium/jobs/335282883#L3848
> https://travis-ci.com/github/cilium/cilium/jobs/334651333#L3952

The amd64 issue is tracked at #11560.

**Comment by Jianlin-lv** [comment]
After the #11685 patch was merged, I verified this problem on the latest code,
Repeatedly execute the `"make unit-tests TESTPKGS = pkg / aws / eni"` command for more than 12 hours without reproducing the issue;
Additionally, Travis-ci in the community has not had this issue recently.
I think it can be temporarily closed.
@pchaigno
