### ISSUE TITLE
Document test-focus jenkins target

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10700]
Add the newer comments you can post on github to the documentation so newer developers can know how to run specific tests on their PRs:

* `test-focus K8sDatapathConfig.*`
* `test-gke`
* `test-gke K8sDatapathConfig.*`

https://docs.cilium.io/en/v1.7/contributing/testing/ci/#triggering-pull-request-builds-with-jenkins

**Comment by pchaigno** [comment]
I think this has been superseded by `test-only`, right?
