### ISSUE TITLE
hostport support for init containers

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#10714]
Reported by @aanm. We are currently not copying the init containers to our types.Containers.

**Comment by aanm** [comment]
Copying is not enough. Init containers are a special case. Each init container is executed sequentially which means the host port for initContainer[0] might not be defined in initContainer[1] for example. This also means that all host ports defined in initContainers should not be set when the pod's "main" containers start.

**Comment by borkmann** [comment]
Handing to @aanm since he has an implementation already.

**Comment by borkmann** [comment]
via https://github.com/cilium/cilium/pull/11092
