### ISSUE TITLE
mkdir /sys/fs/bpf: operation not permitted

### ISSUE THREAD

**Issue by zhxqgithub** [cilium/cilium#10731]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
1.14 
create cilium pod by https://raw.githubusercontent.com/cilium/cilium/v1.4/examples/kubernetes/1.14/cilium.yaml

- Kernel version (run `uname -a`)
4.14.2-1.el7.centos.x86_64

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
   v1.14.9
**the issue is **
```
kubectl describe pod cilium-7tkkj -nkube-system




Events:
  Type     Reason       Age                    From                             Message
  ----     ------       ----                   ----                             -------
  Warning  FailedMount  13m (x72 over 143m)    kubelet, node1 MountVolume.SetUp failed for volume "bpf-maps" : mkdir /sys/fs/bpf: operation not permitted
  Warning  FailedMount  3m21s (x62 over 141m)  kubelet, node1  Unable to mount volumes for pod "cilium-7tkkj_kube-system(5a9b57c5-6fdd-11ea-bec1-fa163e5cfec1)": timeout expired waiting for volumes to attach or mount for pod "kube-system"/"cilium-7tkkj". list of unmounted volumes=[bpf-maps]. list of unattached volumes=[cilium-run bpf-maps docker-socket cni-path etc-cni-netd etcd-config-path etcd-secrets clustermesh-secrets cilium-token-rmldq]
```

**Comment by brb** [comment]
@zhxqgithub Cilium v1.14 is an ancient version. Have you tried with more recent version (e.g. v1.7.1)?

**Comment by zhxqgithub** [comment]
@brb ok，I will have a try.  the key point, the bfp dir does not exists in /sys/fs/ .

**Comment by christarazi** [comment]
@zhxqgithub Has upgrading to the more recent version of Cilium helped?

**Comment by zhxqgithub** [comment]
have the same problem when use https://github.com/cilium/cilium/blob/master/install/kubernetes/quick-install.yaml 


```
 Warning  FailedMount  46s (x8 over 109s)  kubelet, tj1-cc-k8s-test04.kscn  MountVolume.SetUp failed for volume "bpf-maps" : mkdir /sys/fs/bpf: operation not permitted

```

**Comment by autumn0207** [comment]
I have the same problem
```
  Warning  FailedMount  15s (x6 over 31s)  kubelet, k8s-ssb4  MountVolume.SetUp failed for volume "bpf-maps" : mkdir /sys/fs/bpf: operation not permitted
```

**Comment by errordeveloper** [comment]
Could folks please provide information about their cluster, e.g. Kubernetes version, PSP config, is SELinux enabled?

**Comment by errordeveloper** [comment]
@autumn0207 also, please confirm whether you are using CentOS 7 or another OS?

**Comment by ctrahey** [comment]
I get this same failure on a fresh cluster.

- Running `kubectl create -f https://raw.githubusercontent.com/cilium/cilium/1.7.2/install/kubernetes/quick-install.yaml`
- Hypriot 1.12.0
- Kubernetes (client & server) 1.18.2

**Comment by ctrahey** [comment]
I see now on the Cilium requirements listing that:

> Cilium requires a Linux kernel >= 4.9

**Comment by danwent** [comment]
It would be great if you could post the details of your kernel config, as it may be that you have a new enough kernel, but the right BPF config options may not be set.   

See this section of the docs for the details: https://docs.cilium.io/en/v1.7/install/system_requirements/#linux-kernel 

Related link: https://github.com/clearlinux/cloud-native-setup/issues/40

**Comment by ctrahey** [comment]
Thanks for the tip Dan! I've attached my config. Note this is stock Hypriot 1.12 (latest).

So far it looks like you're right - the only option from the required options is `CONFIG_BPF=y`. I will try to enable the others and report back :-)


[kernel.config.txt](https://github.com/cilium/cilium/files/4540865/kernel.config.txt)

**Comment by danwent** [comment]
@ctrahey , btw, it looks like from your config that you're running ARM?   If so, running Cilium may be more difficult than just making sure the right BPF config options are set.   

There is a PR for work being done to add ARM64 support to Cilium: https://github.com/cilium/cilium/issues/9898  .  If you're interested, I suggest you reach out to those authors, as I am not personally familiar with the ARM64 work.

**Comment by Jianlin-lv** [comment]
> Thanks for the tip Dan! I've attached my config. Note this is stock Hypriot 1.12 (latest).
> 
> So far it looks like you're right - the only option from the required options is `CONFIG_BPF=y`. I will try to enable the others and report back :-)
> 
> [kernel.config.txt](https://github.com/cilium/cilium/files/4540865/kernel.config.txt)

Here list kernel config of Marvell MACCHIATObin(arm64) to support cilium, for your reference.

https://github.com/Jianlin-lv/Kernel-for-Edge-System/blob/master/MACCHIATObin/defconfig-mcbin-edge
