### ISSUE TITLE
cilium: Encrypt node support without external etcd may not come online after restart

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#10743]
Encrypt node can be problematic on agent pod restart in case of no etcd or etcd is in the cilium managed cluster. On restart the observed behavior is the following:

  1. The datapath is still configured with encryption routes and xfrm state/policy
  2. Packets sent from host networking are routed by a route in the main routing table to cilium_host
  3. Here they _should_ be encrypted and sent on wire, however because the ipcache is empty(?!) we do an ipcache lookup and drop the packet.
  4. pod never comes online and cilium monitor reports packet drops.

**Comment by jrfastab** [comment]
So here is the good state
```
# cilium bpf ipcache list
IP PREFIX/ADDRESS   IDENTITY
10.250.254.70/32    24533 6 0.0.0.0
192.168.86.26/32    6 6 192.168.86.26
0.0.0.0/0           2 6 0.0.0.0
10.26.34.190/32     6 6 192.168.86.26
10.250.44.159/32    4 6 0.0.0.0
10.250.193.72/32    24533 6 0.0.0.0
10.250.204.172/32   1 6 0.0.0.0
10.250.211.154/32   28783 6 0.0.0.0
10.26.78.252/32     4 6 192.168.86.26
10.250.128.86/32    8032 6 0.0.0.0
10.250.181.75/32    28783 6 0.0.0.0
10.250.194.159/32   28783 6 0.0.0.0
192.168.86.250/32   1 6 0.0.0.0
```
now if I do a restart,
```
# cilium bpf ipcache list
IP PREFIX/ADDRESS   IDENTITY      
10.250.204.172/32   1 6 0.0.0.0   
192.168.86.250/32   1 6 0.0.0.0   
0.0.0.0/0           2 6 0.0.0.0   
10.250.66.225/32    4 6 0.0.0.0  
```

Question: Why/how does the bpf ipcache get flushed? We expected it to stay populated at least until we've connected with the api-server and sync'd ipcache updates.

**Comment by Joshi425** [comment]
is there any progress on this?
