### ISSUE TITLE
CI: Travis failed K8sSuite.Test_runHeartbeat

### ISSUE THREAD

**Issue by Jianlin-lv** [cilium/cilium#10750]
CI failure Link:
arm64: 
    https://travis-ci.com/github/cilium/cilium/jobs/306711137#L1205
x86: 
    https://travis-ci.com/github/cilium/cilium/jobs/305920402#L1314

----------------------------------------------------------------------
FAIL: client_test.go:183: K8sSuite.Test_runHeartbeat
client_test.go:202:
    c.Error("Heartbeat should have closed all connections")
... Error: Heartbeat should have closed all connections
OOPS: 60 passed, 1 skipped, 1 FAILED
--- FAIL: Test (3.43s)

**Comment by pchaigno** [comment]
#10690 should address this issue.
