### ISSUE TITLE
K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests with MetalLB Connectivity to endpoint via LB

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10763]
```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Can not connect to service "http://192.168.36.240" from outside cluster
Expected command: docker exec -i  client-from-outside curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://192.168.36.240 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000017()', Connect: '0.000000',Transfer '0.000000', total '5.003482'
Stderr:
 	 

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:463
```

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/11072/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_MetalLB_Connectivity_to_endpoint_via_LB/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/11061/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_MetalLB_Connectivity_to_endpoint_via_LB/

**Comment by joestringer** [comment]
We need to augment the CI to gather VirtualBox logs to dig further here.

**Comment by brb** [comment]
@gandro Do you remember the error msg re unsolicited ARP requests you saw in vbox log?

**Comment by gandro** [comment]
> @gandro Do you remember the error msg re unsolicited ARP requests you saw in vbox log?

So what I found out is, at least on my machine, that VirtualBox would get confused by the ARP announcements made by MetalLB's Layer 2 mode. Because VirtualBox apparently infers the IP address of its NAT device by sniffing ARP requests, it would assign the LB IP to the Guest NAT device, therefore temporary breaking the connectivity between guest and host.

VirtualBox would output the following message:
```
00:49:43.906628 NAT: Guest address guess changed from 192.168.36.241 to 10.0.2.15 by arp request
```

Eventually, the VM would re-announce its own IP address via ARP, restoring connectivity again.

The message itself comes seems to come from SLIRP, where I have not found a way to disable it: https://github.com/sailfishos/virtualbox/blob/b2fb20f6ee20eadabe81577f50e30c519b064a4f/virtualbox/src/VBox/Devices/Network/slirp/slirp.c#L1511-L1512

**Comment by brb** [comment]
@gandro Thanks! Just to confirm, did it also result in a test failure where the external node (`k8s3`) was not able to reach the LB SVC via `192.168.36.241`?

**Comment by gandro** [comment]
> @gandro Thanks! Just to confirm, did it also result in a test failure where the external node (`k8s3`) was not able to reach the LB SVC via `192.168.36.241`?

This I don't remember :(

**Comment by brb** [comment]
Alternative solution is to ditch MetalLB and to implement a dummy LB which assigns VIPs to LB svcs, and then on `k8s3` we could manually `ip r a $VIP via $K8S1_IP`.

**Comment by tgraf** [comment]
Seen here:
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/4729/testReport/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_MetalLB_Connectivity_to_endpoint_via_LB/

**Comment by jrajahalme** [comment]
Also here: https://jenkins.cilium.io/job/Cilium-PR-K8s-oldest-net-next/198/execution/node/110/log/?consoleFull

**Comment by brb** [comment]
>  Alternative solution is to ditch MetalLB and to implement a dummy LB which assigns VIPs to LB svcs, and then on k8s3 we could manually ip r a $VIP via $K8S1_IP.

I've created such LB: https://github.com/cilium/dummylb
