### ISSUE TITLE
v1.7: global.nodePort.dsr flag has no effect

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10797]
https://github.com/cilium/cilium/blob/c2275445ba4e376fc58bc5dfe28f5c1d50aad65c/install/kubernetes/cilium/values.yaml#L255-L256

@brb I think this is meant to be `mode: dsr` and commented out?

Reported on Slack by Travis Glenn Hansen.

**Comment by travisghansen** [comment]
That's me from slack if any questions arise..

**Comment by aanm** [comment]
I don't know why GH didn't close this. It's fixed in master.

**Comment by brb** [comment]
> I don't know why GH didn't close this. It's fixed in master.

@aanm It was merged to the `v1.7` branch (`master` is not affected).
