### ISSUE TITLE
documentation github action does not run cmdref check

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10799]
It seems the github action for documentation does not run the cmdref check as it has passed successfully:

https://github.com/cilium/cilium/pull/10727/checks?check_run_id=549531023

And our jenkins job failed since it checked for the cmdref check:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18394/execution/node/160/log/

```
23:32:27      runtime: docker container run --rm --workdir /src/Documentation --volume /home/vagrant/go/src/github.com/cilium/cilium/Documentation/..:/src --user "1000:1000" cilium/docs-builder ./update-cmdref.sh
23:32:29      runtime: docker container run --rm --workdir /src/Documentation --volume /home/vagrant/go/src/github.com/cilium/cilium/Documentation/..:/src --user "1000:1000" cilium/docs-builder ./check-cmdref.sh
23:32:30      runtime: diff --git a/Documentation/cmdref/cilium_preflight_validate-cnp.md b/Documentation/cmdref/cilium_preflight_validate-cnp.md
23:32:30      runtime: index 9a397b538..1c25ad411 100644
23:32:30      runtime: --- a/Documentation/cmdref/cilium_preflight_validate-cnp.md
23:32:30      runtime: +++ b/Documentation/cmdref/cilium_preflight_validate-cnp.md
23:32:30      runtime: @@ -8,8 +8,8 @@ Validate Cilium Network Policies deployed in the cluster
23:32:30      runtime:  
23:32:30      runtime:  Before upgrading Cilium it is recommended to run this validation checker
23:32:30      runtime:  to make sure the policies deployed are valid. The validator will verify if all policies
23:32:30      runtime: -deployed in the cluster all valid, in case they are not an error is printed and the
23:32:30      runtime: -has an exit code -1.
23:32:30      runtime: +deployed in the cluster are valid, in case they are not, an error is printed and the
23:32:30      runtime: +has an exit code -1 is returned.
23:32:30      runtime:  
23:32:30      runtime:  ```
23:32:30      runtime:  cilium preflight validate-cnp [flags]
23:32:30      runtime: HINT: to fix this, run 'make -C Documentation update-cmdref ; git commit Documentation/cmdref --message "docs: Update cmdref"'
23:32:30      runtime: Makefile:26: recipe for target 'check-cmdref' failed
23:32:30      runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
23:32:30      runtime: make[1]: *** [check-cmdref] Error 1
23:32:30      runtime: Makefile:468: recipe for target 'postcheck' failed
23:32:30      runtime: make: *** [postcheck] Error 2
23:32:30  The SSH command responded with a non-zero exit statu
```

@errordeveloper feel free to close the issue if this is suppose to be like this. I honestly thought the github action would be in charge of all documentation checking.

**Comment by brb** [comment]
It sill the case today. @errordeveloper Is there any blocker to do the check from the docs GH action?

**Comment by errordeveloper** [comment]
@brb I don't think anything changed, documentation build is still separated from the rest of the build (and so it should be). We need to find a sensible way for making binaries available during documentation builds. If the docs were built with Go tooling it wouldn't not be a big deal to mix docs build with everything else, but it is Python and there are lots of dependencies.

**Comment by pchaigno** [comment]
@errordeveloper Is that a "no"? :grin: 

I guess what I don't get is if
> documentation build is still separated from the rest of the build (and so it should be)

means you think we should keep the cmdref check separated from the current docs CI test?

**Comment by errordeveloper** [comment]
@pchaigno let me try to step back, what I'm saying is that documentation builds used to assume shared context with the general build, that implied Python and Sphinx had to be present. An improvement was made (https://github.com/cilium/cilium/pull/10572) that isolates the dependencies and the overall context for the documentation build from the general build. However, since building Go sources is not part of documentation build, the binaries are no long automatically available and need to be supplied to the documentation build somehow.

> means you think we should keep the cmdref check separated from the current docs CI test?

No as such, but one solution can be to just do this in a separate step. All I'm trying to say that adding Python and Sphinx back into the set of dependency of the general build is not a good idea. Adding Go to the docs dependencies might be okay (as long as it doesn't impact build times for docs too badly, perhaps build cache can be shared somehow), or otherwise precompiled binaries can be supplied somehow.

**Comment by pchaigno** [comment]
> All I'm trying to say that adding Python and Sphinx back into the set of dependency of the general build is not a good idea. Adding Go to the docs dependencies might be okay (as long as it doesn't impact build times for docs too badly, perhaps build cache can be shared somehow), or otherwise precompiled binaries can be supplied somehow.

Got it :+1: Thanks for the explanation :pray:
