### ISSUE TITLE
cilium-agent: Align and limit line width of --help output

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#10812]
The output of `cilium-agent --help` currently has very long and unaligned option descriptions. It would look nicer if those were aligned with a limited line width. The current `--help` handling can be found in [`CustomCommandHelpTemplate()`](https://github.com/cilium/cilium/blob/e567f8bfa7e8cc4d71566f224f60d7222d3d874b/daemon/cmd/cmdhelp_template.go#L46) and is called from `daemon/cmd/daemon_main.go`.

@joestringer suggested using [`tabwriter`](https://golang.org/pkg/text/tabwriter/) to do this.

**Comment by raokolagan** [comment]
I am planning to take-up this issue and provide the solution for the same.
@pchaigno, Please assign to me

**Comment by pchaigno** [comment]
@raokolagan Done. Don't hesitate to reach out on Slack (e.g., #development) if you need help or have questions.

**Comment by raokolagan** [comment]
@pchaigno, by mistake removed from my end.
Kindly reassign

**Comment by ti-mo** [comment]
@pchaigno Is this still worthwhile? IMO the current state is acceptable and users aren't expected to interact with cilium-agent directly.
```
Flags:
      --agent-health-port int                                   TCP port for agent health status API (default 9879)
      --agent-labels strings                                    Additional labels to identify this agent
      --agent-not-ready-taint-key string                        Key of the taint indicating that Cilium is not ready on the node (default "node.cilium.io/agent-not-ready")
...
```

**Comment by pchaigno** [comment]
IIRC, this was initially requested by Joe but I lost context so let's close.
