### ISSUE TITLE
Investigate cilium-health enablement in ENI mode

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10810]
`cilium-health` appears to be enabled by default in ENI mode, but there are easily reproducible issues in multinode clusters where the cilium-health instances on some nodes are unable to communicate with simulated endpoints on other nodes.

We should investigate these, and:
* Determine whether there is a bug in the cilium-health logic
* If so, fix it; if not, document here why not with proof;
* And/or consider disabling cilium-health in ENI mode until we can confirm that it works reliably.

**Comment by joestringer** [comment]
We can use tools like `cilium monitor` and gather a sysdump, follow the routes, IPs being reached, etc with the cilium-health architecture in mind (each node uses host networking to ping other host IPs and allocated endpoint IPs on other nodes) to dig into what happens to the packets that report connectivity failure.

`cilium-health status --probe` in the cilium container may also help here to trigger the traffic.

Not sure whether the health IP is allocated from the ENI range in this mode or not, this could be a relevant detail as well.

**Comment by christarazi** [comment]
I have a patch to fix this, prepping a PR. 

The TLDR of the issue:  `cilium-health` was missing a rule and a routing table entry which direct the traffic to the appropriate ENI device that was assigned the healthchecking IP.

**Comment by brb** [comment]
Perhaps for now we should mention in the ENI/EKS getting started guides that endpoint health checks `cilium status` are expected to fail.
