### ISSUE TITLE
`disable-iptables-feeder-rules` in the wrong section

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10826]
This should be a couple lines bellow, and not inside the if statement for hubble metrics

https://github.com/cilium/cilium/blob/ae4fbbed82e2e759dc68a83aa0365e26cfe61d7e/install/kubernetes/cilium/charts/config/templates/configmap.yaml#L388-L389

Added in https://github.com/cilium/cilium/pull/10639

**Comment by aanm** [comment]
cc @brb @joestringer @mrostecki

**Comment by aanm** [comment]
It will likely require a regeneration of the `quick-install.yaml`

**Comment by mrostecki** [comment]
I will send a PR soon.

**Comment by mrostecki** [comment]
Fixed by #10794
