### ISSUE TITLE
Unable to run make unit-tests locally

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#10836]
```
$ make unit-tests
...
make: execvp: /bin/bash: Argument list too long
make: *** [Makefile:157: unit-tests] Error 127
```

**Comment by joestringer** [comment]
Can you use something like `remake -x unit-tests` to trace which target is causing this?

**Comment by Weil0ng** [comment]
I think it's the `foreach` statement in `unit-tests` target, I can get around this by adding $(NL):
```
$(QUIET)$(foreach pkg,$(patsubst %,github.com/cilium/cilium/%,$(TESTPKGS)),\
                $(GO) test $(GOFLAGS) $(TEST_UNITTEST_LDFLAGS) $(pkg) $(GOTEST_BASE) $(GOTEST_COVER_OPTS) || exit 1; \
                tail -n +2 coverage.out >> coverage-all-tmp.out;$(NL))
```
NL is defined as:
```
define NL


endef
```

**Comment by joestringer** [comment]
I can successfully run `make unit-tests` in my development environment. Happy to compare envs to see what kind of differences there might be. Checked with master commit b9d2105f7ad9 ("pkg/bpf: remove unused metrics labels").

**Comment by joestringer** [comment]
@Weil0ng adding a newline with an approach like that looks reasonable. Feel free to send a PR, but please also add a comment above that describes why it's there with a reference to this issue.

**Comment by Weil0ng** [comment]
re env, I'm running `make unit-tests` in a docker with a base image `debian:buster` plus a bunch of dependencies I ripped off from `cilium-builder`, I also tried using the vagrant runtime dev image, but it got stuck at compiling `govet`...
