### ISSUE TITLE
Disabling NodePort's "hybrid" mode feature due to tunneling mode being enabled

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10847]
This warning log was seen in k8s-1.11 net-next CI runs:

```
2020-04-03T08:41:11.340831926Z level=warning msg="Disabling NodePort's \"hybrid\" mode feature due to tunneling mode being enabled" subsys=daemon
```

What does it mean to "disable hybrid mode"? 

We should avoid printing unnecessary warnings to the cilium-agent log for common Cilium configurations.

**Comment by brb** [comment]
The tests run with `global.nodePort.mode=hybrid` which means that DSR is enabled for TCP connections (SNAT for UDP). As DSR is still not implemented for the tunneling mode, we disable DSR for TCP, so SNAT is used for both - TCP and UDP.

I'd keep the warning, as the configuration changes during runtime, which is not expected by a user.

**Comment by joestringer** [comment]
The quick-install configures `node-port-mode` to `hybrid` and `tunnel` to `vxlan` as well.

Should we amend the helm templates to change node-port-mode to snat if tunnel is enabled?

**Comment by brb** [comment]
I think `hybrid` was kept in the quick-install, because we expect to enable DSR for the vxlan soon (before v1.8).

**Comment by joestringer** [comment]
OK cool, sounds like that would resolve my concern. I'll leave this here as release-blocker so we can review it when we get closer to the v1.8 final push and determine if any further changes are necessary.

**Comment by joestringer** [comment]
From Cilium meeting:

Hybrid mode is not default any more any way, so less of a concern for v1.8.

This missing feature requires DSR for tunneling mode, then we will resolve this dependency. Should be doable in Cilium v1.9 timeframe.

**Comment by borkmann** [comment]
Closing for now since hybrid is not default & we have other issues addressing implementation of tunneling for DSR.
