### ISSUE TITLE
Not detecting BPF correctly when using cri-o

### ISSUE THREAD

**Issue by cortopy** [cilium/cilium#10852]
## Bug report

**General Information**

After using cilium with docker runtime, I'm now trying to install it in a cluster with cri-o. I've followed the docs as to how to configure it, but the container doesn't seem to detect that BPF is already mounted.

The container logs the following lines:
```
level=warning msg="BPF system config check: NOT OK." error="CONFIG_BPF kernel parameter is required" subsys=linux-datapath
level=warning msg="================================= WARNING ==========================================" subsys=bpf
level=warning msg="BPF filesystem is not mounted. This will lead to network disruption when Cilium pods" subsys=bpf
level=warning msg="are restarted. Ensure that the BPF filesystem is mounted in the host." subsys=bpf
level=warning msg="https://docs.cilium.io/en/stable/kubernetes/requirements/#mounted-bpf-filesystem" subsys=bpf
level=warning msg="====================================================================================" subsys=bpf
level=info msg="Mounting BPF filesystem at /sys/fs/bpf" subsys=bpf
```

The dir `/sys/fs/bpf` exists in host, although I'm not sure how to check it's the right file system. Perusing the code, I can see that if cilium detects that if `/sys/fs/bpf` exists and it's not BPF then it mounts somewhere else. Could it be the mount is not happening because of crio?

Cilium seems to start ok after that, but I rather not have that disruption when Cilium pods are restarted.

- Cilium version: 1.7.2
- Kernel version: Linux master0 5.3.0-45-generic #37~18.04.1-Ubuntu
- Orchestration system version in use: kubernetes
- Upload a system dump (I'm getting an error when running the provided command)

1. Install linux-generic-hwe to get a more recent kernel (5.3)
2. Mount BPF using /etc/fstab (systemd method also tried). 
3. Launch kubernetes with kubeadm and crio
4. Run `helm install cilium cilium/cilium --version 1.7.2 \
  --namespace kube-system \
  --set global.containerRuntime.integration=crio` as per [docs](https://docs.cilium.io/en/stable/kubernetes/configuration/#crio)

**Comment by aanm** [comment]
@cortopy thanks for opening the issue. Which crio version is it?

**Comment by qmonnet** [comment]
You can check the filesystem type of `/sys/fs/bpf` by simply typing `mount | grep bpf`. If the bpffs is mounted you should see something like:

```
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
```

What do you get on your host?

**Comment by cortopy** [comment]
thanks @qmonnet for the pointer. This is what I see on the host:

```
bpffs on /sys/fs/bpf type bpf (rw,relatime)
```

@aanm it's crio 1.17 on ubuntu using AppArmor

**Comment by cortopy** [comment]
that indeed did the trick! thanks @aanm for the tip.

FYI this is what I see after recreating the cluster using the default `containerRuntime` values
```
level=info msg="bpf_requirements check: OK!" subsys=linux-datapath
level=info msg="bpf_features check: OK!" subsys=linux-datapath
level=warning msg="BPF system config check: NOT OK." error="CONFIG_BPF kernel parameter is required" subsys=linux-datapath
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Valid label prefix configuration:" subsys=labels-filter
```

The other thing that puzzles me is all the restarts that are recommended in the [docs](https://docs.cilium.io/en/stable/kubernetes/configuration/#crio). Just out of curiosity, I've recreated the cluster with the default `containerRuntime` values *and* also I've not restarted any of the cilium containers or crio.

And it all works!! I have a healthy cluster with about 12 helm charts deployed and all pods talking to each other as expected

As I said I'm a bit confused about the docs at this stage

**Comment by aanm** [comment]
@cortopy @AntonioMeireles I've opened https://github.com/cilium/cilium/pull/10920 to fix this issue. Thank you for reporting it.
