### ISSUE TITLE
Test for ENABLE_EXTRA_HOST_DEV condition

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#10865]
We're missing a test case to cover the following code. Specifically, we need to check that, when SNAT is enabled, ingress packets that don't have a mark (i.e., identity not deduced by [`inherit_identity_from_host()`](https://github.com/cilium/cilium/blob/e049cfa7e253d224f7fdfdc30390e62556c5e6ee/bpf/lib/identity.h#L32)) will **not** match policies for the host.
https://github.com/cilium/cilium/blob/b8a3accbaffbfe54a016ce23b1c78a153d8a03f6/bpf/bpf_netdev.c#L275-L287

The `#ifndef` was recently inverted in #10776 and put back in #10843 without triggering any CI failure.

**Comment by julianwiedmann** [comment]
Addressed by 79e4db9399df ("bpf: Remove ENABLE_EXTRA_HOST_DEV").
