### ISSUE TITLE
datapath: broken link in docs

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#10888]
I can see this log message:

```
level=warning msg="BPF filesystem is going to be mounted automatically in /run/cilium/bpffs. However, it probably means that Cilium is running inside container and BPFFS is not mounted on the host. for more information, see: https://cilium.link/err-bpf-mount" subsys=bpf
```

The link gives me a 404.

**Comment by brb** [comment]
Can you run `curl -vvv https://cilium.link/err-bpf-mount` from your host?

It works on my machine, i.e. it correctly redirects to https://docs.cilium.io/en/stable/kubernetes/requirements/#mounted-bpf-filesystem.

**Comment by errordeveloper** [comment]
sorry, I copy/pasted it without one character at the end!
