### ISSUE TITLE
Create DSR CT entry even if CT entry is found

### ISSUE THREAD

**Issue by brb** [cilium/cilium#10897]
Currently, we check for the DSR IP option and then create the CT entry with `ct_entry.dsr=1` only for new connections (`CT_NEW`): https://github.com/cilium/cilium/blob/v1.7.2/bpf/bpf_lxc.c#L868.

If a stale CT entry (to be GC'd) exists, then the DSR is not handled for the new flow which leads to the rev-DNAT xlation not applied.

**Comment by travisghansen** [comment]
The GC issue seems to only happen (in my particular use-case) on nodes that are forwarding the packets to a pod on another node.

In my crude setup/test, I have 5 nodes with a single pod backing a `mysql` service (predominantly testing with `NodePort` service type). I've put `haproxy` in 'front' of the cluster `NodePort` service (pointing at all 5 nodes) to do some initial testing etc and I can get the stats from the health checks. To my knowledge health checks never failed to the node which *actually* backed the single pod running the service.

It could be that entries are getting cleaned out inherently after the packet is sent back to the original client from the node truly backing the pod, but when nodes are forwarding packets entries that could be pre-emptively wiped out are not.

Just some random rambling and thoughts from someone who doesn't know what they're talking about but still may be helpful :)

**Comment by julianwiedmann** [comment]
Let's revisit once https://github.com/cilium/cilium/pull/22978 is merged.

**Comment by julianwiedmann** [comment]
Think we got all such cases covered in https://github.com/cilium/cilium/pull/22978, closing for now.
