### ISSUE TITLE
CI: K8sDatapathConfig DirectRouting Check connectivity with sockops and direct routing

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/cilium#10903]
## [CI failure](https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/277/testReport/junit/Suite-k8s-1/17/K8sDatapathConfig_DirectRouting_Check_connectivity_with_sockops_and_direct_routing/)

Cilium agent failed to load the bpf_sockops.o object. The bpftool printed the following error:
```
libbpf has unrecognized, non-zero options
```
This issue is a flake, as a rerun of the tests was successful with no intermediate changes.

Here is the log dump:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/277/artifact/test_results_Cilium-PR-Ginkgo-Tests-Kernel_277_BDD-Test-PR.zip

**Comment by jrfastab** [comment]
`libbpf has unrecognized, non-zero options` is not a hard error libbpf should still load ok.

**Comment by pchaigno** [comment]
There's also `libbpf: kernel doesn't support global data` in there, also for `bpf_sockops.o`. Could be related to a bug I'm seeing in #10861; I'll try to debug today.

**Comment by nathanjsweet** [comment]
Looks like #10916 fixed it.

**Comment by pchaigno** [comment]
#10941 should have fixed the `libbpf: kernel doesn't support global data` issue. #10916 fixed the memory allocation issue.
