### ISSUE TITLE
Passthrough NDP for IPv6 

### ISSUE THREAD

**Issue by anfernee** [cilium/cilium#10935]
## Proposal / RFE

**Is your feature request related to a problem?** Yes

**Describe the problem you'd like**

```
# Pod's IPv6 address is 2620:0:1000:2630:2::ebb9, and it's not responding the following NS 
# request, because cilium node didn't pass the request thru. As a result,  the traffic to the pod 
# cannot be delivered.
2620:0:1000:2630:250:56ff:fe82:eec6 > ff02::1:ff00:ebb9: ICMP6, neighbor solicitation, who has 2620:0:1000:2630:2::ebb9, length 32

# I tried the following config, but it seems not working.
sysctl net.ipv6.conf.all.proxy_ndp=1
```

## Cilium configs
cilium version: v1.7.2
k8s version: v1.18.1 
```
cat /etc/cni/net.d/05-cilium.conf
{
  "cniVersion": "0.3.1",
  "name": "cilium",
  "type": "cilium-cni",
  "enable-debug": false
}
```

**Comment by joestringer** [comment]
Thanks for the report. I have a few clarifying questions:
* How did you deploy Cilium?
* Where is the request coming from? Are you running it e.g. on the host?
* What does `cilium monitor` report for the relevant NS traffic?

**Comment by anfernee** [comment]
- I did this to install cilium: ```kubectl create -f https://raw.githubusercontent.com/cilium/cilium/1.7.2/install/kubernetes/quick-install.yaml```
- I ran `ping6 2620:0:1000:2630:250:56ff:fe82:eec6 # nodeip` in the pod.
- nothing show up in `cilium monitor`. Seems it's only monitoring tcp/udp traffic.

**Comment by joestringer** [comment]
@anfernee The quick install YAML disables IPv6 by default. You likely need to at least edit the configmap to change `enable-ipv6` to `true`.

**Comment by anfernee** [comment]
Sorry I forgot to mention I did that as well as everything stated in official k8s document to enable ipv6. also the ipv6 packet can successfully go out.

**Comment by joestringer** [comment]
Did you enable IPv6 in Cilium? Which commands did you use?

**Comment by anfernee** [comment]
I did `edit daemonset cilium` like the following: 
```
      - args:
        - --config-dir=/tmp/cilium/config-map
        - --enable-ipv6=true
        - --ipv6-cluster-alloc-cidr=2620:0:1000:2630:1000::/64
```

**Comment by joestringer** [comment]
Based on my cursory understanding of the IPv6 implementation, I would expect Cilium to respond to all Neighbour Solicitation messages to respond with Cilium's IPv6 router IP. But I must be missing something because otherwise it would just work :-)

Sounds like it just needs some more investigation. Thanks for the report!

**Comment by anfernee** [comment]
I tried to use ipvlan as datapath, and it still didn't work. but I started sending unsolicited Neighbor Advertisement ICMPv6 multicast packet, it started to work! both curl and ping6 worked. 

I am wondering if this is a valid feature request to do unsolicited NA msg as an option, so that especially on-prem users which relied on NDP could benefit.

**Comment by anfernee** [comment]
I would like to take this bug if you guys are okay with it. I still need your @all 's advice of how to implement this. 

## NDP: missing NA issue
The problem is: when a packet from a node outside the cluster tries to reach a pod inside the cluster, NDP will be used. A NS message is sent, but it didn't get a NA reply, so it didn't know which node to send the packet to at L2 layer. 

```
        +-------------+       +--------------+
        |             |       |              |
        |             |       |      +-----+ |
        |             |       |      | Pod | |
        |             |       |      +-----+ |
        | Node1       |       | Node2        |
        +--+----------+       +--------------+
           |                           ^
           |                           |
           |     +-------------+       |
           |     | ICMPv6      |       |
           |     |-------------|       |
           +---->| Type: NS    +------>+
                 | Dest: mcast |
                 | Target: Pod |
                 +-------------+

                 +-------------+
                 | ICMPv6      |
                 |-------------|
                 | Type: NA    |
                 | (missing)   |
                 +-------------+
```
previous diagram illustrates an example where node1 tries to access pod. 

### Proposal: Reply NA for all the pods 
Cilium only replies NS message only when the target IPv6 address [matches](https://github.com/cilium/cilium/blob/master/bpf/lib/icmp6.h#L341-L344) the router IP. If it also looks up for all endpoints on the node, and reply NA if it matches the endpoint, the previous problem will be solved.  

## NDP: filtered NS Issue
Another problem is the NS delivery problem. Some on-prem network virtualization does [multicast filtering](https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.networking.doc/GUID-97724211-5167-428F-A217-871963A7DFF7.html), so that NS multicast message will only deliver to the node which has joined the multicast group. In the case of NS: if the pod's IP is `900::99ab:cdef`, the NS message will take the last 3 bytes and send it to `ff02::1:ffab:cdef`. If the node hasn't joined that multicast group, the message won't be delivered. 

### Proposal: MLDv2 join group
For every pod started in the node, take the last 3 bytes and send a MLDv2 message to join mcast group like: `ff02::1:ffab:cdef`, and send [Multicast Listener Report](https://tools.ietf.org/html/rfc3810#page-19) to join this group. Ideally it should also respond to multicast query message, but I found it's not necessary for the hypervisor case. If it's necessary, it should be attached to bpf_netdev. Join and leave group should be ref counting on the last 3 bytes of IPv6 addresses of all pods. When no pods' IPv6 address having the same last 3 bytes, leave group message should be sent. All the previous should be guarded by an option.

**Comment by tgraf** [comment]
> Cilium only replies NS message only when the target IPv6 address [matches](https://github.com/cilium/cilium/blob/master/bpf/lib/icmp6.h#L341-L344) the router IP. If it also looks up for all endpoints on the node, and reply NA if it matches the endpoint, the previous problem will be solved.

How does this address the multi-node aspect?

> For every pod started in the node, take the last 3 bytes and send a MLDv2 message to join mcast group like: `ff02::1:ffab:cdef`, and send [Multicast Listener Report](https://tools.ietf.org/html/rfc3810#page-19) to join this group. Ideally it should also respond to multicast query message, but I found it's not necessary for the hypervisor case. If it's necessary, it should be attached to bpf_netdev. Join and leave group should be ref counting on the last 3 bytes of IPv6 addresses of all pods. When no pods' IPv6 address having the same last 3 bytes, leave group message should be sent. All the previous should be guarded by an option.

Makes sense. This may be easier to do from user space instead of attempting to construct the packet from the BPF datapath.

**Comment by joestringer** [comment]
> Cilium only replies NS message only when the target IPv6 address matches the router IP. If it also looks up for all endpoints on the node, and reply NA if it matches the endpoint, the previous problem will be solved.

Be aware that Cilium should not respond to NS for the endpoint's own IP, otherwise it can break duplicate address detection (see also https://github.com/cilium/cilium/issues/10574 )

**Comment by anfernee** [comment]
> How does this address the multi-node aspect?
From my limited knowledge of cilium, for pod-to-pod on different nodes, L3 should just work even without NDP(NS/NA). For the pod that sends NS message to another pod, it should work if the same icmp handler applied to the `bpf_lxc`, just like echo/ping work.

> Be aware that Cilium should not respond to NS for the endpoint's own IP, otherwise it can break duplicate address detection (see also #10574 )
Got it! Very helpful notes!
