### ISSUE TITLE
Use feature probes to detect kernel support for sockops

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#10931]
To test kernel support for sockops, we currently attempt to compile and load sockops BPF program and fail with a warning in case of error, assuming we failed because of missing kernel support.
https://github.com/cilium/cilium/blob/5958dd6fa2105cdf2c769b22568d2ad3858608d6/daemon/cmd/daemon.go#L190-L198

This behavior is non-ideal because 1) we get compilation errors in logs and 2) we may miss compilation and loading errors caused by actual bugs.

Instead, we should be using [our feature probes](https://github.com/cilium/cilium/blob/master/pkg/datapath/linux/probes/probes.go) to check for the appropriate support. Here's what's needed:
- [x] Find and list required kernel features (including [attach points used in Go code](https://github.com/cilium/cilium/blob/5958dd6fa2105cdf2c769b22568d2ad3858608d6/pkg/sockops/sockops.go#L62) and [map type used in C code](https://github.com/cilium/cilium/blob/5958dd6fa2105cdf2c769b22568d2ad3858608d6/bpf/sockops/bpf_sockops.h#L34)).
- [x] Check kernel support in [initEnv()](https://github.com/cilium/cilium/blob/7e5f30dfc1b89c1ace10c37774247a7ab2c7d8f0/daemon/cmd/daemon_main.go#L796), as we already do for e.g., `EnableNodePort`.
- [x] Update [daemon initialization](https://github.com/cilium/cilium/blob/5958dd6fa2105cdf2c769b22568d2ad3858608d6/daemon/cmd/daemon.go#L190-L198) to error in case of failure to load+compile.
- [x] Disable the [whitelisting of compilation errors in sockops tests](https://github.com/cilium/cilium/blob/6fc0b5b09d41dc4968290ced850da5c181847a40/test/k8sT/DatapathConfiguration.go#L78-L81).

**Comment by soumynathan** [comment]
I can work on this. Can you assign me to this.
