### ISSUE TITLE
CI: Travis failed on arm64: No output has been received in the last 10m0s

### ISSUE THREAD

**Issue by Jianlin-lv** [cilium/cilium#10945]
CI failure Link:
https://travis-ci.com/github/cilium/cilium/jobs/318259886#L5347
https://travis-ci.com/github/cilium/cilium/jobs/318170649#L2574

failed on arm64 build, 
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by joestringer** [comment]
I've seen this in some recent builds as well. Unfortunately I don't have any insight into why.

**Comment by joestringer** [comment]
FWIW at least in the link from the issue description, the last test that records output prior to the apparent stall is this:

```
=== RUN   TestMemcache
=== RUN   TestMemcache/text_set_pass
=== RUN   TestMemcache/text_set_drop
=== RUN   TestMemcache/text_get_pass
=== RUN   TestMemcache/text_get_more
=== RUN   TestMemcache/text_get_drop
=== RUN   TestMemcache/text_gat_pass
=== RUN   TestMemcache/text_gat_more
=== RUN   TestMemcache/text_gat_drop
=== RUN   TestMemcache/text_delete_pass
=== RUN   TestMemcache/text_delete_drop
=== RUN   TestMemcache/text_incr_pass
=== RUN   TestMemcache/text_incr_drop
=== RUN   TestMemcache/text_touch_pass
=== RUN   TestMemcache/text_touch_drop
=== RUN   TestMemcache/text_slabs_pass
=== RUN   TestMemcache/text_slabs_drop
=== RUN   TestMemcache/text_lru_crawler_response_req_more_and_pass
=== RUN   TestMemcache/text_stats_response_req_more_and_pass
=== RUN   TestMemcache/text_flush_all_pass
=== RUN   TestMemcache/text_flush
```

**Comment by joestringer** [comment]
I also see in some recent builds that it seems like arm64 test runs can take significantly longer than the x86 equivalents, eg:

https://travis-ci.com/github/cilium/cilium/builds/160245156

Not sure whether this is related, maybe some cases somehow trigger a path that stalls or relies on a test failure timeout to proceed?

**Comment by joestringer** [comment]
#10971 also had memcache test as the last tests, but it got a bit further. Weirdly this one printed a single character of the next test step, which suggests that the unit test executable got interrupted..?

https://travis-ci.com/github/cilium/cilium/jobs/319239397

```
--- PASS: TestMemcache (0.11s)

    --- PASS: TestMemcache/text_set_pass (0.02s)

    --- PASS: TestMemcache/text_set_drop (0.01s)

    --- PASS: TestMemcache/text_get_pass (0.01s)

    --- PASS: TestMemcache/text_get_more (0.00s)

    --- PASS: TestMemcache/text_get_drop (0.00s)

    --- PASS: TestMemcache/text_gat_pass (0.00s)

    -
```

**Comment by tklauser** [comment]
Looking at recent Travis CI builds for arm64, I don't see this issue happening anymore: https://travis-ci.com/github/cilium/cilium/builds

I'll thus close this issue, please feel free to reopen if you see this issue again or think it is not fixed yet.
