### ISSUE TITLE
cilium: fix up all --help sections properly

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#10944]
Reminder for 1.8 release (hence release blocker) to go over all --help sections of cilium agent together and fix them up properly. E.g. to pick one, the kube-proxy free knobs are randomly spread all over the place right now which must be fixed before 1.8 goes out, same likely for other areas.

**Comment by soumynathan** [comment]
Is this after the grouping of help sections for cilium-agent. So do you want to group it based on the kube-proxy feature?

**Comment by joestringer** [comment]
Sounds good to review this again before release. @soumynathan and I did several rounds to where I was reasonable happy as a first cut, but there's always potential for improvement on the groupings so it'd be good to collect specific examples of things we think are out-of-place / should live somewhere else.

**Comment by soumynathan** [comment]
Ok, I think I might have a list of items that can be grouped for kube-proxy, but that might negate our first attempt to group under high level groupings. But let's try that out. I will post my grouping structure here for kube-proxy and we can start from there and then fine tune it.

**Comment by soumynathan** [comment]
Here is the list I do have for the kube-proxy:
Let me know if I am missing anything or added something that is not required or related to kube-proxy enable or disable.
```
kube-proxy:

kube-proxy-replacement
install-iptables-rules
enable-external-ips
enable-host-reachable-services
enable-node-port
host-reachable-services-protos
ipv4-service-loopback-address
ipv4-service-range
ipv6-service-range

**Comment by aanm** [comment]
This is no longer an issue since we don't have sections in our help flag.
