### ISSUE TITLE
Performance of cilium without kube-proxy  slower than non cilium/iptables cni 

### ISSUE THREAD

**Issue by venkatnsrinivasan** [cilium/cilium#10943]
## Support

Hello, I am trying to evaluate the performance improvements of using Cilium on kubernetes without kube-proxy. I have 1 master 3 worker node cluster  with kubernetes 1.15 and kernel 5.6.3  on ubuntu and I installed cilium 1.7.2 as per these instructions . https://docs.cilium.io/en/v1.7/gettingstarted/kubeproxy-free/  with managed etcd . Everything seems to have deployed fine .I then deployed a test nginx pod and service and ran a ab test from another pod to this  service. ab  -n 100000 -c 1  http://nginx-svc-1/  .
 I ran similar tests on a setup using kube-proxy and  iptables with calico and I see the cilium deployment much much slower.  For e.g .  with kube-proxy and iptables , with 3000 services and a huge iptables list i see a performance of 680us but with a single service in cilium the performance is close 800us. Is there something i am missing or any particular optimization to be done ?
I tried using dsr etc as well but with  no difference.

**Comment by brb** [comment]
@venkatnsrinivasan Can you share more details, in particular:

- What environment? Baremetal or cloud? Machine details?
- `iptables-save` output?
- Service and Endpoint objects 
- `cilium-agent` logs
- Do pods run on the same node? If not, how the nodes are interconnected (vxlan or direct routing)?

**Comment by venkatnsrinivasan** [comment]
- I am running this on Vsphere 6.7.1 . My setup consists of 1  master  and 3  worker nodes . The master node has 4 cpu , 8gb ram. The workers have 8 cpu, 32GB Ram each.  They are all running K8S 1.15.5. I also upgraded to 1.16.8 but no difference . They all run kernel 5.6.3-050603-generic and use containerd 1.3 as the runtime.
- iptables output is  attached .
- Yamls  of service and endpoint  objects  attached
-  cilium logs  of all nodes  attached.
- Pods run on different  nodes. I run the test from  one pod to another .I tried  both vxlan  and DSR, with  no  difference in results , current config - KubeProxyReplacement:   Strict   [NodePort (DSR, 30000-32767), ExternalIPs, HostReachableServices (TCP, UDP)]
[iptables-save-output.log](https://github.com/cilium/cilium/files/4468926/iptables-save-output.log)
[objects.tar.gz](https://github.com/cilium/cilium/files/4468927/objects.tar.gz)
[agent-logs.tar.gz](https://github.com/cilium/cilium/files/4468928/agent-logs.tar.gz)

**Comment by brb** [comment]
@venkatnsrinivasan Thanks. Can you re-run your experiment with the following configuration:
```
<..>
--set global.bpf.preallocateMaps=true \
--set global.kubeProxyReplacement=strict \
--set global.nodePort.mode=snat \
--set global.tunnel=disabled \
--set global.autoDirectNodeRoutes=true \
--set global.l7Proxy.enabled=false
```

**Comment by venkatnsrinivasan** [comment]
I performed the same test with the configuration you suggested and there is no change . Its still close to 800us. The results are almost exactly the same when using the pod ip directly.

**Comment by travisghansen** [comment]
@venkatnsrinivasan can you share the yaml you are using to deploy services/nginx/Apache/ab etc? I want to replicate your setup as closely as I can for my own testing.

**Comment by venkatnsrinivasan** [comment]
@travisghansen  Attached the relevant config files. I have a nginx deployment and ubuntu deployment which have different node affinity settings based on node labels which you will need set  . I install ab on the ubuntu pod and run "ab -n 100000 -c 1 http://nginx-svc/"

[app.tar.gz](https://github.com/cilium/cilium/files/4510156/app.tar.gz)

**Comment by travisghansen** [comment]
Got it thanks. I’ll apply and let you know if I have any questions.

**Comment by brb** [comment]
@venkatnsrinivasan did you check what is a baseline performance when running w/o k8s and cilium?

**Comment by travisghansen** [comment]
I've got a baseline now with `cilium + snat`. I'll wait for the `DSR` fix an re-run with that. Then blast cilium altogether and run it again `canal`.

**Comment by brb** [comment]
What I meant by the baseline is the raw network / system performance when running nginx not in a container, but as a standalone process (same for ab, just on another node).

**Comment by travisghansen** [comment]
Yeah I understood. I think @venkatnsrinivasan is more concerned about the delta than the absolute values. They mentioned going from 680 in calico + kube-proxy + iptables with 3000 services to 800 in a cilium setup with only a single service.

I haven't done without k8s/etc yet, but here are the 2 results I do have (which don't mean much at this point):

- to localhost running directly inside the nginx container 279
- using cilium + snat 1076

I'll fire off a direct host to host (in the same nodes as the cilium + snat) to see where that lands and report back.

**Comment by travisghansen** [comment]
Ok, so 'bare metal' (vm to vm in the same nodes as the cilium + snat) I came in at 661.

**Comment by travisghansen** [comment]
Actually this is interesting..the 661 came from a node not part of my cluster (still in the same proxmox install/etc). Running the same test from 2 nodes in cluster (ie: 2 nodes with bpf rules etc) I'm coming in around 830. I'll do some more tests as time permits.

**Comment by travisghansen** [comment]
Cluster internal using pod IP instead of service IP landed at 1048.

**Comment by venkatnsrinivasan** [comment]
Unfortunately , i cant reproduce this anymore. I did a baseline on the same two nodes where the pods were deployed directly on the VMs by installing nginx and ab and the base line was around 725. 
I setup a brand new cluster without any CNI drivers or bpf mounts and the baseline comes to around the same and now with calico and iptables its coming equivalent to the same as the cilium setup without kube-proxy using the last set of configurations suggested by @brb . I can't seem to get the 580-600 nos anywhere . 
I will have to circle back with our net admins to check if something has changed and check if the underlying hosts on which the virtual machines are being provisioned have issues .

**Comment by borkmann** [comment]
> I will have to circle back with our net admins to check if something has changed and check if the underlying hosts on which the virtual machines are being provisioned have issues .

Ok, sounds good. @venkatnsrinivasan I'll close it for now. Please reopen if you are able to repro again.
