### ISSUE TITLE
Request: Cilium multi-node "kind" guide

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10948]
It'd be awesome if we could spin up multi-node [kind](https://github.com/kubernetes-sigs/kind) environments for testing Cilium without the requirement for local VMs.

Microk8s gets us half the way (no VM) but it's single-node only. We can run multiple nodes of Microk8s and connect them together, but then you still need to provision the multiple nodes somehow.

**Comment by dctrwatson** [comment]
I have such an environment that I've been using for a few weeks now. I can make it generic to share.

Should the kind configuration just go inline in the doc? Or should I place it somewhere else in the repo to reference?

**Comment by joestringer** [comment]
@dctrwatson awesome! I think it'd make sense to add another link on the page below and follow a similar path to the minikube/microk8s/etc pages:

https://docs.cilium.io/en/latest/gettingstarted/k8s-install-sandbox/
