### ISSUE TITLE
Error mounting sys-fs-bpf.mount on Ubuntu 20.04 Focal

### ISSUE THREAD

**Issue by bai** [cilium/cilium#10955]
## Bug report

I'm trying to run cilium on Ubuntu 20.04 Focal (pre-release) and getting an error with sys-fs-bpf mounts:

```
● sys-fs-bpf.mount - Cilium BPF mounts
     Loaded: bad-setting (Reason: Unit sys-fs-bpf.mount has a bad unit file setting.)
[...]
sys-fs-bpf.mount: Cannot create mount unit for API file system /sys/fs/bpf. Refusing.
```

According to https://github.com/systemd/systemd/issues/8394, in newer systemd API mounts are not supported via .mount units:

> No, API VFS are not supported as .mount units. Currently the only way to configure mount options for them is by adding an /etc/fstab file. And I think this is unlikely to change.

Reporting this as a bug, but also wonder if fstab will be the recommended way of mounting for cilium once 20.04 is released.

**General Information**

Note: this is not related to cilium or orchestration itself, just to the way Cilium currently recommends mounting `/sys/fs/bpf` with https://github.com/cilium/cilium/blob/master/contrib/systemd/sys-fs-bpf.mount.

- Cilium version: 1.7.2
- Kernel version: 5.4.0.21.25
- Orchestration system version in use: Kubernetes v1.18.1

**How to reproduce the issue**

1. Bootstrap Ubuntu Focal 20.04.
2. Create a systemd unit with https://github.com/cilium/cilium/blob/master/contrib/systemd/sys-fs-bpf.mount.
3. Run `systemctl daemon-reload && systemctl start sys-fs-bpf.mount`.
4. Run `systemctl status sys-fs-bpf.mount` to see failure details.

**Comment by joestringer** [comment]
I was under the impression that newer systemd will auto-mount the BPFFS anyway, so maybe we just need to:
1. Confirm this is true
1. Extend the instructions to help users understand whether BPFFS is already mounted, in which case this setup step is a no-op.

**Comment by joestringer** [comment]
@bai Were you following a specific guide on docs.cilium.io that lead you down this path? It would be useful to have that link to ensure that we update the docs that you were using.

**Comment by bai** [comment]
Indeed, `/sys/fs/bpf` is mounted on Ubuntu 20.04 Focal and I think [this step](https://docs.cilium.io/en/stable/kubernetes/requirements/#mounted-bpf-filesystem) is no longer required from what I see.

 I'll let you folks confirm that since you most certainly have more expertise, but I think this issue can be closed off.

**Comment by joestringer** [comment]
FWIW We also hit this with the "node init" scripts, we may need to reconsider how those deploy the BPFFS mount unit.
