### ISSUE TITLE
test: Refactor Cilium tests with `grep`

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/cilium#10976]
## Proposal / RFE

The function `CiliumExecContext` is used to call `grep` in several cases (search [k8sT](https://github.com/cilium/cilium/tree/master/test/k8sT)). `grep` does not exit with a zero-code when it doesn't find what it is looking for. Often times this is the desired behavior, so checking the `Success` method for the exec result is not useful. We should refactor these tests so that `CiliumExecMustSucceed` can be used in these instances.

**Comment by soumynathan** [comment]
I can take up this. Assign it to me.

**Comment by nathanjsweet** [comment]
@soumynathan done! Thanks!

**Comment by soumynathan** [comment]
test-me-please

**Comment by errordeveloper** [comment]
@soumynathan you need to open a PR, `test-me-please` doesn't work on issues.

**Comment by pchaigno** [comment]
> Often times this is the desired behavior, so checking the `Success` method for the exec result is not useful. We should refactor these tests so that `CiliumExecMustSucceed` can be used in these instances.

I'm not sure I understand this issue. I think the reason we sometimes don't use `CiliumExecMustSucceed` is that it has a fixed offset of 1 for `ExpectWithOffset` and we would need e.g. an offset of 2.
