### ISSUE TITLE
Add e2e tests for fromEntities policies

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10979]
We have tests for `toEntities` behaviour:
https://github.com/cilium/cilium/blob/9ff51d2520dd732bb0685f77f79da60c1f3feafb/test/k8sT/Policies.go#L627

However, there are no corresponding `fromEntities` policies.

Tasks:
* [x] Test fromEntities: host https://github.com/cilium/cilium/commit/5b527f3f561397923a2b0252d811468df63920ba
* [x] Test fromEntities: remote-node https://github.com/cilium/cilium/commit/5b527f3f561397923a2b0252d811468df63920ba
* [ ] Test fromEntities: cluster
* [x] Test fromEntities: world https://github.com/cilium/cilium/commit/c0ef36f6e9c93f83aa2cf2a5e180c2910093f4c0
* [ ] Test fromEntities: all

**Comment by brandshaide** [comment]
@joestringer I'd like to work on this. Can you assign it to me?

**Comment by joestringer** [comment]
@brandshaide sorry, missed your earlier comment. I've assigned you.

**Comment by chez-shanpu** [comment]
@joestringer @pchaigno  If no one is working on this now, I'd like to do it.
And when opening a pull request, should I open it for each test (`fromEntities: cluster` and `fromEntities: all`) ?

**Comment by pchaigno** [comment]
@chez-shanpu I assigned you. Don't hesitate to reach out on Slack (e.g., #testing or #development) if you have any question.

>  And when opening a pull request, should I open it for each test (fromEntities: cluster and fromEntities: all) ?

That's really up to you. You can split the work in two PRs if that helps or implement everything in a single go.

**Comment by pchaigno** [comment]
FYI, https://github.com/cilium/cilium/pull/15398 will address this issue.
