### ISSUE TITLE
CI: Checks service across nodes Tests NodePort BPF Tests with XDP, direct routing and SNAT: k8s1 host cannot connect to service

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#11029]
Potentially still related to #10942. Seen in master.

- Checks service across nodes Tests NodePort BPF Tests with XDP, direct routing and Hybrid
- Checks service across nodes Tests NodePort BPF Tests with XDP, direct routing and SNAT

Links from master CI (seen once so far):

- https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/4533/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_XDP__direct_routing_and_Hybrid/

Links from reoccuring CI runs:

- https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/11202/testReport/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_XDP__direct_routing_and_SNAT/
- https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/11201/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_XDP__direct_routing_and_SNAT/

Outputs suggest there were prior connection attempts that were successful:

```
k8s1 host can not connect to service "tftp://[::ffff:192.168.36.12]:31006/hello" (failed in request 9/10)
k8s1 host can not connect to service "http://192.168.36.11:32057" (failed in request 10/10)
k8s1 host can not connect to service "tftp://10.10.1.89:30959/hello" (failed in request 8/10)
```

**Comment by joestringer** [comment]
I saw this for the following test:
* Suite-k8s-1.11.K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests NodePort

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18881/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_NodePort/

**Comment by brb** [comment]
Should have been fixed by https://github.com/cilium/cilium/commit/1e700fe1bd6594811a31fd98eff6403dced1dbfa.

**Comment by joestringer** [comment]
Will close if we think it's fixed then. We can always reopen or file a new issue if someone hits similar behaviour again.

**Comment by brb** [comment]
The test got reenabled in https://github.com/cilium/cilium/pull/11347.
