### ISSUE TITLE
traffic policy local health check returns wrong status

### ISSUE THREAD

**Issue by pbecotte** [cilium/cilium#11043]
## Bug report

Cilium 1.7.2
K8s 1.15 on EKS

Running in AWS. Service of type LoadBalancer with an NLB allocated and `externalTrafficPolicy: Local`. This should cause a health check to run on each node that answers 1 or 0 depending on if there is a local instance. Today, had one service that this worked correctly (load balancer health checks only pass on the node with the pod) and another identical one that didn't. Eventually, realized it is because kubeproxy and cilium both attempt to handle this. On the nodes that kubeproxy sets up the health check, the answer is correct. On the nodes that cilium does, the answer is wrong.

(whether we should have both of those running seems like an interesting question as I resolve this- but in the mean time)

The PR that added this feature says it should return 0 if there are no local pods, but that is not the observed behavior. Ran it without kube-proxy... all the health checks always pass. Ran it without cilium- they are all correct.

**Comment by christarazi** [comment]
What is the PR that you're referring to? Could you link it please?

**Comment by pbecotte** [comment]
https://github.com/cilium/cilium/pull/9906

**Comment by gandro** [comment]
Thanks for the report! To to understand you correctly, you are saying that the `HealthCheckNodePort` returns a non-zero count on a node which is not running any local pods for that service?

If so, could you please provide the following outputs:

The service description of the service which shows the behavior, i.e. `kubectl describe svc foo`

And on the node (or cilium pod) where you don't see the expected result, the following outputs:
```
curl localhost:34567`  #where 34567 is the HealthCheckNodePort of the service
cilium service list
sudo cilium bpf lb list
```

**Comment by gandro** [comment]
A user reported that this still occurs on a node which had the above commit applied. Reopening.
