### ISSUE TITLE
Kops e2e tests failing tests related to session affinity.

### ISSUE THREAD

**Issue by olemarkus** [cilium/cilium#11042]
The kops e2e tests have a couple of test failures related to SessionAffinity. The tests have been broken since those tests were merged into the test suite.

The e2e suite is running kops master with cilium 1.7.1

See https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-cni-cilium and https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/e2e-kops-aws-cni-cilium/1251089583362281476

the cilium config-map contains this:
```
  auto-direct-node-routes: "false"
  bpf-ct-global-any-max: "262144"
  bpf-ct-global-tcp-max: "524288"
  cluster-name: default
  container-runtime: none
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-node-port: "false"
  enable-remote-node-identity: "false"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  kube-proxy-replacement: partial
  masquerade: "true"
  monitor-aggregation: medium
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "false"
```

**Comment by brb** [comment]
These will be fixed by https://github.com/cilium/cilium/issues/9076.

**Comment by olemarkus** [comment]
Thanks. So that issue is both using BPF nodeport and kube-proxy?

**Comment by brb** [comment]
Yes. In the case of kube-proxy, the old loadbalancing mechanism (`lb4_local()` in bpf_lxc.c) is still in place (unless you pass `--disable-k8s-services=true`), and it does not respect sessionAffinity. #9076 changes that.
