### ISSUE TITLE
CI: GKE: could not find pods in namespace: signal: killed

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#11105]
https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-GKE/469/testReport/Suite-k8s-1/14/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/

https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-GKE/461/testReport/Suite-k8s-1/14/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications/

## Stracktrace
```
Cilium cannot be installed
Expected
    <*errors.errorString | 0xc0004c6100>: {
        s: "could not find pods in namespace 'cilium' with label 'io.cilium/app=operator': signal: killed",
    }
to be nil
```
## Standard Output
```
```
## Standard Error
```
STEP: Downloading cilium-istioctl
STEP: Installing Cilium
```
[1aeca68d_K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip](https://github.com/cilium/cilium/files/4516548/1aeca68d_K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip)

[6cdbaf20_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications.zip](https://github.com/cilium/cilium/files/4516575/6cdbaf20_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications.zip)

**Comment by joestringer** [comment]
Seen also in K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) .

**Comment by joestringer** [comment]
Similar failure in `K8sIdentity Identity expiration Expiration of CiliumIdentity` here:

https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/7844/testReport/junit/Suite-k8s-1/20/K8sIdentity_Identity_expiration_Expiration_of_CiliumIdentity/

```
/home/jenkins/workspace/Cilium-PR-K8s-GKE@2/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
Failure while waiting for all cilium endpoints to reach ready state
Expected
    <*errors.errorString | 0xc00012f0e0>: {
        s: "could not find pods in namespace 'kube-system' with label 'k8s-app=cilium': signal: killed",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-GKE@2/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:207
```

Later in the output, the CI is able to locate & execute commands inside the cilium-agent pods in order to gather info. So the core problem here seems to be that the kubectl binary itself gets killed while attempting to retrieve state.
