### ISSUE TITLE
Add documentation for all used k8s resources

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11114]
Add a page that describes each of the kubernetes resources / Cilium custom resources used by Cilium, describing what information is available for a general overview of features that Cilium implements from kubernetes, features that Cilium introduces which are managed via resources, and introspection that a user can perform with access to the k8s apiserver.

Example of how k8s represents information like this: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/

Resource types:
* [ ] ConfigMaps
* [ ] DaemonSets
* [ ] Deployments

Resource Definitions:
* [ ] Node
* [ ] CiliumNode (incl. [IPAM](https://docs.cilium.io/en/v1.7/concepts/ipam/crd/))
* [ ] Pods
* [ ] CiliumEndpoints (note that these are not directly related to services / k8s `Endpoints` resources; they map to non-host-network pods)
* [ ] Service
* [ ] Endpoints / EndpointSlices
* [ ] CiliumIdentities
* [ ] NetworkPolicy
* [ ] CiliumNetworkPolicy / CiliumClusterwideNetworkPolicy

**Comment by aanm** [comment]
Having this will also help users to understand why some resources are specified in the ClusterRole
