### ISSUE TITLE
Clarify where pod CIDR is used

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11113]
Cilium can come up with a CIDR to use for pod allocation in several ways, and there are several potential flags that may impact this selection:
* `--require-pod-cidr` for k8s
* `--allocate-node-cidrs`
* `--ipv4-range`
* Chaining / ENI modes

In cases like chaining / ENI / endpoint-routes mode, if Cilium doesn't acquire an allocation range from somewhere, how does it determine the IPs to assign to, eg., the cilium-health device? Do we still have code that generates matches on CIDR ranges using the internal pod cidr range, even if that wasn't explicitly configured somewhere?

Related: #11021

**Comment by aanm** [comment]
`--ipv4-range` as well?

**Comment by joestringer** [comment]
With v1.8 defining `--ipam` with the `cluster-pool` option and its own set of rules, documented here:

https://docs.cilium.io/en/latest/concepts/ipam/

I think we'll need to revisit which flags to deprecate and whether any further ambiguities remain in the configuration options.
