### ISSUE TITLE
close the gap between cilium monitor and hubble observe API

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#11193]
the goal here is to start utilizing hubble more for CI testing instead of using cilium monitor as hubble provides additional contexts and ability to fetch flows from the past. however hubble currently does not expose all the events from cilium monitor: https://github.com/cilium/cilium/blob/master/pkg/hubble/parser/threefour/parser.go#L90

**Comment by michi-covalent** [comment]
i'm guessing these are the tests that capture monitor output:
```
% git grep MonitorStart
helpers/cilium.go:// MonitorStart starts the  monitor command in background and returns a callback
helpers/cilium.go:func (s *SSHMeta) MonitorStart() func() error {
helpers/kubectl.go:// MonitorStart runs cilium monitor in the background and returns the command
helpers/kubectl.go:func (kub *Kubectl) MonitorStart(namespace, pod string) (res *CmdRes, cancel func()) {
k8sT/DatapathConfiguration.go:  monitorRes, monitorCancel = kubectl.MonitorStart(helpers.CiliumNamespace, ciliumPodK8s1)
k8sT/Policies.go:                               monitorRes, monitorCancel := kubectl.MonitorStart(helpers.CiliumNamespace, ciliumPod)
k8sT/Services.go:                       monitorRes, monitorCancel := kubectl.MonitorStart(helpers.CiliumNamespace, ciliumPodK8s1)
runtime/Policies.go:            monitorStop = vm.MonitorStart()
runtime/benchmark.go:           monitorStop = vm.MonitorStart()
runtime/connectivity.go:                        monitorStop = vm.MonitorStart()
runtime/fqdn.go:                monitorStop = vm.MonitorStart()
runtime/kafka.go:               monitorStop = vm.MonitorStart()
runtime/lb.go:          monitorStop = vm.MonitorStart()
```

**Comment by brb** [comment]
We sometimes run `cilium monitor -D -v` in the CI tests ad hoc to capture all debug output from the monitor which is very helpful for troubleshooting.

**Comment by michi-covalent** [comment]
thanks @brb yeah that's a legitimate use case that hubble does not support right now.

**Comment by glibsm** [comment]
> thanks @brb yeah that's a legitimate use case that hubble does not support right now.

Sorry, don't follow. Exactly which part is not supported? We should create some actionable items to get it on par

**Comment by michi-covalent** [comment]
yes i'll open an issue. right now hubble ignores debug messages from cilium monitor: https://github.com/cilium/cilium/blob/1e225a2cd5437f32fb212534f31f28ce6d4f7af6/pkg/hubble/parser/threefour/parser.go#L90 

debug events from monitor: https://github.com/cilium/cilium/blob/450c79ce5e2fbdeb32833df45c04bd529ff6ff4b/pkg/monitor/api/types.go#L37

**Comment by michi-covalent** [comment]
... or rather i guess it's more about dumping the entire monitor events, kind of like how in hubble we used to have the raw payload.
