### ISSUE TITLE
Red herring: BUG: stat() has unstable behavior

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11198]
These warnings are not actually warnings since the file does not exist.
```
Apr 28 19:37:28 k8s2 cilium-agent[18029]: level=warning msg="BUG: stat() has unstable behavior" endpointID=1 error="stat /var/run/cilium/state/1/lxc_config.h: no such file or directory" file-path=/var/run/cilium/state/1/lxc_config.h subsys=endpoint
Apr 28 19:37:28 k8s2 cilium-agent[18029]: level=warning msg="BUG: stat() has unstable behavior" endpointID=1 error="stat /var/run/cilium/state/1/lxc_config.h: no such file or directory" file-path=/var/run/cilium/state/1/lxc_config.h subsys=endpoint
```

```
$ sudo ls -la /var/run/cilium/state/1/lxc_config.h
ls: cannot access '/var/run/cilium/state/1/lxc_config.h': No such file or directory
```

This comment was not addressed https://github.com/cilium/cilium/pull/11028#discussion_r412464230 
cc @christarazi

**Comment by aanm** [comment]
cc @pchaigno

**Comment by pchaigno** [comment]
How did you run into this issue? That message is in the `badLogMessages`, so we should see failures in CI if it happens.

Could this be happening because two instances of a `File not found` error on the same file are not actually equal? https://github.com/cilium/cilium/blob/d81a5cdea511b43b1e0f0190861a306b2f3e5029/pkg/endpoint/restore.go#L76

**Comment by christarazi** [comment]
Hmm, it looks like I preemptively marked it as resolved. I figured the following update to that area of the code resolved it. 

To clarify, the desired behavior is to *not* warn if the file doesn't exist?

**Comment by pchaigno** [comment]
@aanm I hit this bug while rebasing the host firewall PR (I'm assuming that's how you hit it too given `endpointID=1`). #11281 should fix it.
