### ISSUE TITLE
Simple command to understand Cilium capabilities for running kernel 

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#11214]
## Proposal / RFE

**Is your feature request related to a problem?**

It is increasingly hard for someone to know whether their kernel supports a variety of different BPF-related capabilities that enable them to leverage more advanced Cilium capabilities.  A simple 'cilium kernel-check' command could be run to report the results.  

Output could be like: 

```
$ cilium kernel-check 
eBPF Networking:   Supported
IPv4 Networking:  Supported
IPv6 Networking:  Supported 
LPM CIDR lookups:  Supported
BPF Map deletes:  Supported
tproxy-based L7 redirect:   Supported
TCP Host Reachable Services:  Not Supported
UDP Host Reachable Services:  Not Supported
Kube-proxy Free:  Not Supported
iptables Free:  Not Supported 
Sockmap:   Not Supported
IPsec Encryption:  Supported 
Wireguard Encryption:  Not Supported 
```

This would essentially leverage the same code the kernel is using to implement "probe" for each one of these features.  

Right now this info is in a mix of kernel config options, kernel modules, and kernel version listed here: https://docs.cilium.io/en/stable/install/system_requirements/

It would be ideal if this command could be run even if cilium-agent fails to start, and in fact, that it could be easy to spin up a simple K8s Deployment that just runs this command and dumps the output to standard out, like: 

```
kubectl create -f cilium-kernel-check.yaml 
kubectl logs cilium-kernel-check
```

It would also be nice if this command could confirm that the bpf filesystem is mounted in the host namespace, and also validate any other critical kernel assumptions.  

If something basic was missing from the kernel config for BPF support, it should make it clear which kernel options were not enabled (see this bug as example where this is not clear):  https://github.com/cilium/cilium/issues/10731

**Comment by brandshaide** [comment]
@danwent I'd really like to dig into this, but some assistance would be highly appreciated 🙂 

> [...] leverage the same code the kernel is using to implement "probe" for each one of these features.

May you can give me some direction/hint on where to find functions like this?
And where is this feature supposed to reside in the cilium project, e. g. in `cilium/examples` ?

**Comment by joestringer** [comment]
Some basic code can be found from `probeManager`:

```
$ git grep probeManager
pkg/datapath/linux/probes/probes.go:    probeManager *ProbeManager
pkg/datapath/linux/probes/probes.go:            probeManager = &ProbeManager{features: features}
pkg/datapath/linux/probes/probes.go:    return probeManager
pkg/datapath/linux/requirements.go:             probeManager := probes.NewProbeManager()
pkg/datapath/linux/requirements.go:             if err := probeManager.SystemConfigProbes(); err != nil {
pkg/datapath/linux/requirements.go:             if err := probeManager.CreateHeadersFile(); err != nil {
```

A first cut might be just creating a new `cilium/cmd/kernel_check.go` CLI that uses this code:

https://github.com/cilium/cilium/blob/97f8299d6c1a0da4a3f23c296f1e719c72e94c35/pkg/datapath/linux/requirements.go#L177-L183

Then creating a new example YAML which pulls the standard Cilium container and just runs the new command.

We could of course iterate on top of this to get the full set of features including the other bits that @danwent pointed out in the issue description (and potentially others).

I think that placing it somewhere under `cilium/examples` is reasonable. /cc @aanm in case he has other opinions on where it might live.

**Comment by brandshaide** [comment]
thanks, @joestringer for your help!

**Comment by aanm** [comment]
@danwent Couldn't this live under the precheck daemonset? A deployment will only run in a node without checking if all nodes have the same capabilities.

@brandshaide Let's start with Deployment for now. The probes that Joe mentioned seem to be a good option. The deployment helm template could have a variable that would be used to select on which node the Deployment would be installed. This can be achieved with the NodeSelector field available in the k8s Deploymentn Spec.

**Comment by brandshaide** [comment]
@joestringer I've made a first cut, could you please check whether this goes in the overall right direction? 😎 

> [...] iterate on top of this to get the full set of features including the other bits that @danwent pointed out in the issue description (and potentially others).

see above: when on the right path, I'd like to keep on working on this, i. e. add more features/checks on top of this. 🙂 

In the current state `cilium kernel-check` does not **yet** provide any options/subcommands - but a `cilium kernel-check --help` does provide flags for e. e. appending a config file or enabling `DEBUG` mode although these options are not (yet) accessible with `kernel-check`. Is that OK? 

@aanm I'll start with a Doployment, spinning up cilium with the `kernel-check` command being invoked. 

> [...] The deployment helm template could have a variable that would be used to select on which node the Deployment would be installed [...]

To clarify: so you mean cilium is only being installed on nodes which are satisfying the kernel-capabilities check of `cilium kernel-check`

**Comment by aanm** [comment]
>To clarify: so you mean cilium is only being installed on nodes which are satisfying the kernel-capabilities check of cilium kernel-check

No, I meant the kernel-check deployment would only be installed on the nodes specified by the user. For example: If the user has 100 nodes running kernel A and 100 other nodes running kernel B the user would only need to specify a nodeSelector that would select one node of each type.

**Comment by joestringer** [comment]
> In the current state cilium kernel-check does not yet provide any options/subcommands - but a cilium kernel-check --help does provide flags for e. e. appending a config file or enabling DEBUG mode although these options are not (yet) accessible with kernel-check. Is that OK?

That's fine, my thought is that this CLI should be pretty simple anyway, I'm not sure I understand any need for more complicated flags or subcommands yet.
