### ISSUE TITLE
SessionAffinity follow up issues

### ISSUE THREAD

**Issue by brb** [cilium/cilium#11215]
- [x] Fix sleep in the CI tests (PR: https://github.com/cilium/cilium/pull/11216, however it takes too long, new issue: https://github.com/cilium/cilium/issues/11296)
- [x] https://github.com/cilium/cilium/pull/11085#discussion_r417156337 (comment)
- [x] Extend cilium status
- [x] Documentation (kube-proxy free gsg, the BPF map sizes, the upgrade guide)
- [ ] Add tests for when running w/ kube-proxy
- [x] IPv6 CI tests

**Comment by jrajahalme** [comment]
Tests seem to be quite slow, each STEP taking about 4 minutes:
```
22:34:00    Tests NodePort with sessionAffinity
22:34:00    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:431
22:34:00  STEP: Making 10 HTTP requests from testclient-8hfhc to "http://192.168.36.11:32753" (sessionAffinity)
22:38:14  STEP: Making 10 HTTP requests from k8s3 to "http://192.168.36.11:32753" (sessionAffinity)
22:42:13  === Test Finished at 2020-05-01T05:42:07Z====
...
22:45:20    Tests NodePort with sessionAffinity
22:45:20    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:431
22:45:20  STEP: Making 10 HTTP requests from testclient-8hfhc to "http://192.168.36.11:32753" (sessionAffinity)
22:49:34  STEP: Making 10 HTTP requests from k8s3 to "http://192.168.36.11:32753" (sessionAffinity)
22:53:32  === Test Finished at 2020-05-01T05:53:27Z====
```

**Comment by brb** [comment]
@jrajahalme Thanks for letting me know. @joestringer has created an issue: https://github.com/cilium/cilium/issues/11296.

**Comment by brb** [comment]
The 1.8 release blocker is `Extend cilium status`.

**Comment by brb** [comment]
We don't care about the kube-proxy case, so the issue is resolved.
