### ISSUE TITLE
CI: K8sFQDNTest Restart Cilium validate that FQDN is still working: "app2" cannot curl to "147.75.38.95" during restart

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#11213]
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
"app2" cannot curl to "147.75.38.95" during restart
Expected command: kubectl exec -n default app2-776cf4f9c6-tblgm -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 147.75.38.95 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000016()', Connect: '0.000000',Transfer '0.000000', total '5.000107'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/k8sT/fqdn.go:162
```
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19269/testReport/junit/Suite-k8s-1/17/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by jrajahalme** [comment]
[2b5d5ab3_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip](https://github.com/cilium/cilium/files/4549831/2b5d5ab3_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip)

**Comment by jrajahalme** [comment]
```
STEP: Testing that connection from "app2-776cf4f9c6-tblgm" to "http://vagrant-cache.ci.cilium.io" should work
STEP: Testing that connection from "app2-776cf4f9c6-tblgm" to "http://jenkins.cilium.io" shouldn't work
STEP: Testing that connection from "app2-776cf4f9c6-tblgm" to "147.75.38.95" works
STEP: Testing that connection from "app2-776cf4f9c6-tblgm" to "54.148.123.155" should not work
STEP: Deleting cilium pods
STEP: Testing connectivity when cilium is restoring using IPS without DNS
```
Last step above fails:
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
"app2" cannot curl to "147.75.38.95" during restart
```
app2 (= Endpoint 1822) has egress policy enabled and it allows ID 16777217:
```
/sys/fs/bpf/tc/globals/cilium_policy_01822:

DIRECTION   IDENTITY   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Ingress     0          ANY          NONE         0       0         
Ingress     1          ANY          NONE         0       0         
Egress      0          53/TCP       39397        0       0         
Egress      0          53/UDP       39397        0       0         
Egress      16777217   ANY          NONE         0       0         
```
ID 16777217 is `147.75.38.95`:
```
IP PREFIX/ADDRESS               IDENTITY                
...
147.75.38.95/32                 16777217 0 0.0.0.0      
```
There is one conntrack entry that looks interesting:
```
TCP OUT 10.10.0.109:35354 -> 147.75.38.95:80 expires=3538 RxPackets=0 RxBytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=3 TxBytes=222 TxFlagsSeen=0x02 LastTxReport=3475 Flags=0x0000 [ ] RevNAT=0 SourceSecurityID=38321 
```
No received packets, but three sent packets. App2's bpf policy map stats are all zeroes, though.

**Comment by nebril** [comment]
Didn't see this happening in quarantine pipelines for 3 weeks

**Comment by pchaigno** [comment]
This flake also happened at least once on the v1.7 branch: https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/1663/testReport/Suite-k8s-1/17/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.
[3282a178_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip](https://github.com/cilium/cilium/files/5028434/3282a178_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip)

**Comment by joestringer** [comment]
Also here: https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/1677/testReport/junit/Suite-k8s-1/11/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by tklauser** [comment]
Another failure on 1.7 backport (#13871): https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3672/testReport/Suite-k8s-1/13/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by pchaigno** [comment]
No recent reports, closing.
