### ISSUE TITLE
hubble-relay: update helm charts to deploy hubble-relay

### ISSUE THREAD

**Issue by rolinh** [cilium/cilium#11226]
The existing helm charts need to be updated so that hubble-relay can be deployed as a deployment.
Hubble-relay needs access to one hubble instance via unix Domain socket to access the peer gRPC service for peers discovery (typically, this means that the hubble socket of the cilium agent needs to be accessible by the hubble-relay container).

**Comment by michi-covalent** [comment]
@Rolinh is this the docker repo? https://hub.docker.com/r/cilium/hubble-relay i guess we are still waiting for the dockerfile PR to land.

**Comment by Rolinh** [comment]
Yes I think that #11192 needs to land for that to happen. This issue also depends on #10648.
