### ISSUE TITLE
GKE tests fail because of a deadlock between Cilium and metrics-server

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#11262]
GKE pipeline (https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline-GKE/) is failing because Cilium pods are in crashing.

The failure message from Cilium is
```
level=fatal msg="Unable to initialize Kubernetes subsystem" error="unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request" subsys=daemon
```

Our Kubernetes initialization code tries to retrieve information from API endpoint which is backed by `metrics-server-v0.3.1` deployment. Pods from this deployment are not starting because Cilium has not started providing networking in the cluster yet.

This can be fixed by ignoring (preferably with logging) failures while retrieving non-critical K8s capabilities in Kubernetes subsystem initialization code.

**Comment by zbindenren** [comment]
We have the same issue for k8s on premise setup with kubeadm.

It last worked for us for docker images with the following sha: 
* `sha256:73012faf74204832839f01eb1938df614271953cac1acd09a0540d3d0ae83c9d`

It does not work for:
* `sha256:fa61df59725e58bbb9cc24bfb4dd3eb4e88bf5b50054e1eb995c2e5282c8bec1`
* latest

**Comment by joestringer** [comment]
@jrajahalme and I hit this too.

**Comment by nebril** [comment]
Seems like https://github.com/cilium/cilium/pull/11253 fixed this
