### ISSUE TITLE
Pods fail to reply to outside IPv6 requests

### ISSUE THREAD

**Issue by Ulexus** [cilium/cilium#11263]
## Bug report

Hosts on the same IPv6 subnet as kubernetes Nodes (and other Pods within the kubernetes cluster) are able to communicate with Pods with no problem.  Hosts outside that subnet fail.  True for both Pods and Services on IPv6.  IPv4 works fine.

Tracing reveals the request packets arrive to the application Pod, and the application responds.  However, the reply path fails with Cilium dropping the packet:

```
xx drop (Stale or unroutable IP) flow 0x2bc1756b to endpoint 0, identity 57868->0: 2605:xxxx:xxxx::e8c0 -> 2601:xxxx:xxxx::7208 EchoReply
```

Debugging with @aanm reveals that:
  - The `cilium_host` interface on the host Node shares the IP address of the host Node
  - The application Pod's _default route_ has an IP address on the Pod subnet which does not exist on **any** host interface
  - Manually changing the IP address of the `cilium_host` to be the otherwise non-existent gateway address on the Pod subnet does not resolve the issue.
  - ~~The Node is _not_ marked up by kubernetes with its IPv6 address, only its IPv4 address (however, Cilium does accurately discover the IPv6 address)~~

Note that traffic _originating_ from the application Pod _is_ able to communicate bidirectionally with outside IPv6 hosts.

Note also that IPv4 traffic works fine in any direction.

**General Information**

- Cilium version: v1.7.2 and build from #11240 
- Kernel version: v5.5.15-talos
- Orchestration system version in use: Kubernetes v1.18.0
- Link to relevant artifacts:
    - default policies, deployment script, etc.
    - very slightly modified Cilium Config  (policies, deployments scripts, ...)
      ```
      $ diff quick-install.yaml quick-install-ref.yaml
      45c45
      <   enable-ipv6: "true"
      ---
      >   enable-ipv6: "false"
      139,140c139,140
      <   enable-host-reachable-services: "true"
      <   enable-external-ips: "true"
      ---
      >   enable-host-reachable-services: "false"
      >   enable-external-ips: "false"
      ```
    - application Pod is just a default ubuntu container:  `image: ubuntu`
- Upload a system dump: system dump acquired and available via DM

**How to reproduce the issue**

1. Install default dual-stack cluster with custom IPv4 and IPv6 Pod and Service subnets
2. Create a test Pod

I'm certain there are more significant pieces to reproduce the issue, but this is all I am actually doing.

**Comment by aanm** [comment]
`cilium_host` interface got the IPv6 address from the SLAAC, not from Cilium. Thus, `cilium_host` does not get the internal IPv6 (allocated by cilium) because the `init.sh` script checks if `cilium_host` contains an IP and it will not re-add this internal IPv6 address. If an IPv6 address is available in `cilium_host` because of the SLAAC we should could it as the default gateway of pods, would that work? (question for the developers)

**Comment by Ulexus** [comment]
I have verified that the unavailability of the IPv6 address in the Node `Status.Addresses` field is not the source of the problem.

```
level=info msg="Received own node information from API server" ipAddr.ipv4=172.16.199.72 ipAddr.ipv6="2605:xxxx::c2" nodeName=core0 subsys=k8s v4Prefix=172.22.0.0/24 v6Prefix="2605:xxxx:yyyy:c100::/64"
```

**Comment by Ulexus** [comment]
Testing on a single-stack IPv6-only cluster shows the same problem with the _additional_ failure of no longer being able to reach hosts outside the local host subnet when the connection is outbound from the application Pod.

**Comment by Ulexus** [comment]
It turns out I'm just an idiot:  `accept_ra` was 1 instead of 2, and Cilium enabled ipv6/forwarding.   Strange that I could still ping out to IPv6 addresses, but changing `accept_ra` to `2` fixed the issue.

**Comment by Ulexus** [comment]
Spoke too soon;  it does _not_ work even with `accept_ra=2`.  Now Cilium is intercepting traffic even to the _host_ and dropping it with the "Stale or unroutable IP) message.

**Comment by Ulexus** [comment]
Technically, it is dropping packets _from_ the host.  It appears that packets from a service run on the host (outside kubernetes) are being run through Cilium's routing.  This is further curious because these packets which are egressing from the host are being marked as _from_ ID 2 (world), not ID 1 (host), if I am reading this properly:

```
xx drop (Stale or unroutable IP) flow 0x6aa79439 to endpoint 0, identity 2->0: [2605:xxx::fef2:c2]:50000 -> [2601:yyyy::7208]:56674 tcp SYN, ACK
```

The 2605 address here is the host.  Port 50000 is the port on which the host-side, outside-of-kubernetes service is running.  The 2601 address is my outside workstation.  This service works fine until the cilium agent reports ready; then all traffic fails, even if cilium is shut down thereafter.

**Comment by Ulexus** [comment]
Just tried with SLAAC turned off; static IPv6 settings for both local address and default route (no IPv4 addresses).  Cilium still destroys the host's default gateway, and without `accept_ra`, the host never gets it back.

**Comment by dimm0** [comment]
https://github.com/cilium/cilium/issues/6320 this?

**Comment by Ulexus** [comment]
I don't believe that is the same problem, no.  There is no problem routing IPv6 packets within the network, be it other Pods or other hosts in the same subnet.  The problem is with hosts outside the subnet.  In any case, no NAT should be involved here, neither as a remedy nor by design.

**Comment by eleblebici** [comment]
We have had the same problem. Re-installed cluster with kube-proxy. Installed cilium with the parameter `--set global.kubeProxyReplacement="partial"` and not enabled any of `    --set global.hostServices.enabled=false \
    --set global.nodePort.enabled=false \
    --set global.externalIPs.enabled=false \
    --set global.hostPort.enabled=false \`

So we did not make kube-proxy replacement and we achieved to connect pods from outside via IPv6.

**Comment by qmonnet** [comment]
@Ulexus Are you still on v1.7.2 and if not, is the issue still present on later versions? If so, would you happen to have a sandbox cluster where the issue is occurring, that I could access to try and troubleshoot, by any chance? (You can reach me as qmo on Slack if that's the case.)

**Comment by Ulexus** [comment]
No, I've moved on to more recent versions now, and I don't think this is still an issue in recent versions.

**Comment by olemarkus** [comment]
We no longer supports masqed IPv6, so it is no longer relevant for me.
