### ISSUE TITLE
Cilium fails to start with "RTNETLINK answers: Operation not supported"

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11294]
Q: Cilium fails to start with these logs:

```
level=warning msg="+ tc qdisc replace dev cilium_vxlan clsact" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
level=warning msg="+ true" subsys=datapath-loader
level=warning msg="++ tc filter show dev cilium_vxlan ingress" subsys=datapath-loader
level=warning msg="++ grep -v 'pref 1 bpf chain 0 $\\|pref 1 bpf chain 0 handle 0x1'" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
level=warning msg="Dump terminated" subsys=datapath-loader
level=warning msg="+ '[' -z '' ']'" subsys=datapath-loader
level=warning msg="+ cilium-map-migrate -s bpf_overlay.o" subsys=datapath-loader
level=warning msg="+ set +e" subsys=datapath-loader
level=warning msg="+ tc filter replace dev cilium_vxlan ingress prio 1 handle 1 bpf da obj bpf_overlay.o sec from-overlay" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
level=warning msg="We have an error talking to the kernel, -1" subsys=datapath-loader
level=warning msg="+ RETCODE=2" subsys=datapath-loader
level=warning msg="+ set -e" subsys=datapath-loader
level=warning msg="+ cilium-map-migrate -e bpf_overlay.o -r 2" subsys=datapath-loader
level=warning msg="+ return 2" subsys=datapath-loader
level=error msg="Error while initializing daemon" error="exit status 2" subsys=daemon
level=fatal msg="Error while creating daemon" error="exit status 2" subsys=daemon
```

A: The kernel version that Cilium is running on does not have full eBPF support.

For a full kernel requirements list, see the documentation:
https://docs.cilium.io/en/stable/operations/system_requirements/#linux-distribution-compatibility-matrix

**Comment by Jille** [comment]
The previous link is broken. Use https://docs.cilium.io/en/stable/operations/system_requirements/#linux-distribution-compatibility-matrix

**Comment by sgielen** [comment]
The link above contains a list of kernel config options that must be enabled. For me, `CONFIG_NET_CLS_ACT` was not set. Often, you can check this against your `/boot/config-$(uname -r)`.

Perhaps it would be better if `cilium install` checked such kernel options before attempting to install. @joestringer do you think I should open a new issue for this?

**Comment by pchaigno** [comment]
@sgielen Please see https://github.com/cilium/cilium/issues/14753 :slightly_smiling_face:

**Comment by joestringer** [comment]
@Jille thanks for the report, I've also updated the issue description with the right link.
