### ISSUE TITLE
build: improve builder and runtime images

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#11305]
We are highly reliant on runtime and builder images, yet at present these two images have undesired properties.

- date-based tags (`date -u "+%Y-%m-%d"`)
   - it's possible for multiple images to be produced on the same day
 - all images that depend on these have to be updated manually with new tags
 - build scripts are non-deterministic
   - package versions are not specified
   - only some components are checked out based on specific git revision, some only specify branch
 - `contrib/packaging/docker/Dockerfile.runtime` is hard to read
- it also looks like we don't publish these images from CI

**Comment by errordeveloper** [comment]
I have started looking into this as part of #11000, and will open a PR to start tidying things up.

**Comment by aanm** [comment]
FYI https://github.com/cilium/packaging

**Comment by errordeveloper** [comment]
@aanm there is no readme, could you please provide context?
