### ISSUE TITLE
CI: test suite should be unaware of infra details

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#11319]
The Cilium test suite currently holds many references to infrastructure details, namely Vagrant. The test suite should not have any awareness of how infrastructure is built.

**Comment by errordeveloper** [comment]
To begin with, it would be good to know if e.g. the following functions is used for anything:

https://github.com/cilium/cilium/blob/4bdb3617786dd7c3a6f2de78923f5981cdbfc8a6/test/helpers/vagrant.go#L35

Also, there are flags like `-cilium.provision` and `-cilium.provision-k8s` , are these used?

**Comment by pchaigno** [comment]
`-cilium.provision` is definitely used often when running locally (to speed up subsequent test runs once provisioned). Don't know for the second. Maybe asking on the #development channel would be best?

**Comment by errordeveloper** [comment]
@pchaigno is it `-cilium.provision=false` that you are actually using?

**Comment by pchaigno** [comment]
@errordeveloper I use both, but I think `-cilium.provision=true` is actually the default so I shouldn't need to explicitly specify it.

**Comment by errordeveloper** [comment]
I thought there was a bash script that handles provisioning. In any case, this is a more general issue to say that we need to draw clearer boundaries in that area. I think it makes sense to have a mode where test suite invocation involves some setup steps, but whatever it does shouldn't be tied into a particular implementation of infrastructure, right now it is directly tied into vagrant. I am intending to run a  survey soon to find out what setups people have and what is important for them.

**Comment by pchaigno** [comment]
According to the survey Ray did recently, most folks use `ginkgo` to run tests locally.
