### ISSUE TITLE
CI: provide agent logs when cilium pods are in crash loopback

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#11320]
When agent's pod goes into crash loopback and therefore CI results into failure, it would be helpful to see why that is happening. Right now the output is not useful, e.g. the zip file doesn't collect the agent log. [Example dump](https://github.com/cilium/cilium/files/4576627/f3ee8175_K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running.1.zip) from such CI run where the pod went into this state when init.sh was failing due to compilation error. The issue does not happen when the CI is run locally.

**Comment by errordeveloper** [comment]
> Right now the output is not useful, e.g. the zip file doesn't collect the agent log.

Could you be a little more specific here, is vast majority of the files included of no-use at all or of limited use? Is there anything that you think we really shouldn't bother to include?

**Comment by borkmann** [comment]
> > Right now the output is not useful, e.g. the zip file doesn't collect the agent log.
> 
> Could you be a little more specific here, is vast majority of the files included of no-use at all or of limited use? Is there anything that you think we really shouldn't bother to include?

In case of compilation issue or verifier issue where the agent doesn't start up, the current file in the zip (example one attached) are of very little to no use at all mainly since it doesn't dump any agent log to the zip. Somehow CI seems to fail doing the full bugtool dump in this case.

**Comment by ianvernon** [comment]
If pods are in crash loop back off, then bug tool won't work because it requires the pod to be running. The best we can do are getting the logs via `kubectl logs` for the pod, or getting dumps from the nodes directly (perhaps developing a service which you can launch on a specific node and gets information from the BPFFS that persists outside of the pod's lifecycle).

**Comment by borkmann** [comment]
> If pods are in crash loop back off, then bug tool won't work because it requires the pod to be running. The best we can do are getting the logs via `kubectl logs` for the pod, or getting dumps from the nodes directly (perhaps developing a service which you can launch on a specific node and gets information from the BPFFS that persists outside of the pod's lifecycle).

Thanks @ianvernon ! :-) Getting the plain logs via `kubectl logs` for the pod in this case would already suffice.

**Comment by nebril** [comment]
We actually do gather previous container logs if container in question has more than 0 restarts. The issue in log archives like one provided in main issue is that pod gathering command which is used for generating all log gathering commands times out. Made a PR which increases the timeout, let's see if this helps.

**Comment by aanm** [comment]
Re-opening: https://jenkins.cilium.io/job/Cilium-PR-K8s-newest-kernel-4.9/560/testReport/junit/Suite-k8s-1/18/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/
