### ISSUE TITLE
build: migrate away from hosting image builds in Quay.io and Docker Hub 

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#11334]
Cilium images are currently built in Quay.io as well as Docker Hub.

There are several benefits of using hosted builds, e.g. Cilium team doesn't need to maintain infrastructure that relies on these builds, and of security the supply chain is guaranteed by vendors of the said product.

However, it present it appears that the challenges listed below outweigh the benefits.

- hosted builds provide limit control of the resources and environment
   - only `x86_64` build hosts are available (see https://github.com/cilium/cilium/issues/9898)
   - it's not possible to request more CPU or memory
- configuration is manual
- configuration cannot be checked in git
   - it maybe possible to use the API, but that would be a custom integration
   - it's not possible to observe it when reading build-related code/config 
   - it's not possible to make changes to it when build system changes are made
- not possible to control build process
  - cannot set image tags using a custom scheme, e.g. git tree hashes
  - cannot sequence image builds, e.g. build runtime image first, then other images
  - cannot set build arguments
- cannot trigger a job directly after image is built
   - it maybe possible to watch the registry, but that would be a custom integration
   - would be convenient to e.g. redesign the pipeline to build all the images first, then start different integration tests in parallel

**Comment by nebril** [comment]
`cannot sequence image builds, e.g. build runtime image first, then other images` Aren't we doing this already for our Cilium images built on Quay?

`would be convenient to e.g. redesign the pipeline to build all the images first, then start different integration tests in parallel` This makes a lot of sense and I feel it would greatly improve the CI experience.

**Comment by joestringer** [comment]
Looks like this has been addressed now, since all builds are generated via GitHub actions and pushed directly into Quay/Docker. Closing. Feel free to reopen if I'm mistaken :-)
