### ISSUE TITLE
The node manager issues 2 update notifications per single node update

### ISSUE THREAD

**Issue by rolinh** [cilium/cilium#11336]
## Bug report

**General Information**

With latest master (3a4fbd5fefec59ab50efc2c5bd271826e6f495ed at the time of reporting this issue), the node manager issues updates notification twice for a single change. I did not attempt to bissect in order to pinpoint when this issue first occurred as I haven't tested if this behavior is reproducible with older cilium releases. 

**How to reproduce the issue**

Just run cilium. The behavior can be easily observed with hubble enabled by using the hubble CLI:

1.  Start cilium with hubble enabled (`--enable-hubble`).
2. Use the hubble CLI to monitor for hubble peer notifications with `hubble peers watch` (requires latest hubble master).
3. Trigger a change. For example, when using the dev vagrant VMs, restart the cilium service on one node. In my case, I see the following:
```
$ hubble peers watch
PEER_ADDED   k8s1 192.168.34.11
PEER_ADDED   k8s2 192.168.34.12
PEER_ADDED   k8s3 192.168.34.13
PEER_UPDATED k8s2 192.168.34.12    # <-- this is expected
PEER_UPDATED k8s2 192.168.34.12    # <-- but this is not
```

**Comment by Rolinh** [comment]
I fail to reproduce. Will re-open if I do.
