### ISSUE TITLE
build: avoid dependency on structure of GOPATH

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#11341]
A contributor is currently required to checkout  code at `${GOPATH}/src/github.com/cilium/cilium` (see https://github.com/cilium/cilium/pull/11174#discussion_r420186748), which shouldn't have to be the case as Go toolchain has eliminated the general need for this.

**Comment by joestringer** [comment]
I'm pretty sure this is resolved now, I haven't had a $GOPATH for some time now and I haven't hit issues so far. I think that most of the remaining dependencies are limited to cases which run inside a docker container that simulates the $GOPATH based on the host directory.
