### ISSUE TITLE
Add support for ServiceAppProtocol 

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11344]
https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol

It's an alpha feature in 1.18

**Comment by borkmann** [comment]
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20191227-app-protocol.md

**Comment by nathanjsweet** [comment]
`AppProtocol` in K8s was implemented to solve an annotation issue. Specifically ensuring that cloud-providers, etc could properly provision external resources for services at the application level (for example ensuring that L7 load-balancers are provisioned for a port). These types of problems were solved by annotations, but the per-port mapping that many users wanted could only be achieved clumsily by annotation. `AppProtocol` can be thought of as a per-port annotation. See [this issue](https://github.com/kubernetes/kubernetes/issues/40244) for more context. A look through [the original commit](https://github.com/kubernetes/kubernetes/pull/88503) shows that `AppProtocol` doesn't "do anything".

At this time cilium does not need to do anything with the new "AppProtocol" field. It could be helpful to us in the future if we ever want to utilize the "annotation" to drill down into endpoint and service visibility at the application layer by default, but we do not have such plans. [Our current annotation system](https://docs.cilium.io/en/v1.8/policy/visibility/?highlight=protocol) for layer 7 visibility solves this problem already, but it is a good example of something "AppProtocol" *could* help us solve in the future. We should continue to monitor its use in the broader community to see if it might reveal itself to be useful to us in some other capacity.
