### ISSUE TITLE
Skipped reading configuration file" reason="Config File \"cilium-operator\" Not Found in \"[/]\"" subsys=config

### ISSUE THREAD

**Issue by Ruilkyu** [cilium/cilium#11356]
Skipped reading configuration file" reason="Config File \"cilium-operator\" Not Found in \"[/]\"" subsys=config

**Comment by tklauser** [comment]
Thank you for the report. Could you please provide some additional info, i.e. as found in the bug issue template:

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. instruction 1
2. instruction 2

**Comment by tklauser** [comment]
> Skipped reading configuration file" reason="Config File "cilium-operator" Not Found in "[/]"" subsys=config

This message is informational and no error as such, e.g. if you didn't specify the `--config` or `--config-dir` flag. Did you provide a config file or directory for `cilium-operator` and it didn't get read?

**Comment by tklauser** [comment]
As written in the previous comment, this message is informational and no sign of something not working as expected. Thus closing this issue. Feel free to reopen with additional information if you think something is not working as expected.
