### ISSUE TITLE
Update documentation for kubectl usage

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11379]
As of kubectl v1.8.x, when running commands like this from the documentation:

https://docs.cilium.io/en/v1.7/gettingstarted/clustermesh/#test-pod-connectivity-between-clusters

```
$ kubectl -n kube-system exec -ti cilium-g6btl cilium node list
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
...
```

Presumably some future version of kubectl will break this which is why they're complaining.

We should consider going through the docs to update such examples; for example in the sample above:

```
$ kubectl -n kube-system exec -ti cilium-g6btl -- cilium node list
```

At a glance using this command I see several cases that are not using this `--` form:

```
$ git grep "kubectl.*exec" Documentation/ | grep -v "kubectl exec[^-]--.*$"
```

(This command is not perfect but it at least gets rid of some of the correct instances in the docs)

**Comment by JieJhih** [comment]
I can take this. Please assign it to me.

**Comment by joestringer** [comment]
@JieJhih Thanks, assigned.
