### ISSUE TITLE
Docs: Add Integration Guide for Rancher Kubernetes Engine

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#11380]
## Proposal / RFE

Add a guide for Cilium installation with Rancher Kubernetes Engine <https://rancher.io>

**Comment by pchaigno** [comment]
An initial version of the guide was written at https://github.com/cilium/cilium/pull/11381. Marking as `good-first-issue` as someone just needs to resuscitate that pull request and address the few remaining review comments.
