### ISSUE TITLE
remove GET /endpoints/{id}/labels API call and use LabelConfiguration as part of Endpoint object in API

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1138]
per discussion with @tgraf , we should not have a separate Labels structure in the Endpoint API; instead we should use the existing LabelConfiguration object:

**Comment by tgraf** [comment]
0.11 is the last release we can still change this. Setting release blocker flag

**Comment by ianvernon** [comment]
I'll take this on since I know this code.
