### ISSUE TITLE
Unexpected {{end}} in helm chart

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#11398]
Just found out about this, while playing around  with current helm in EKS.

```shell script
$ helm lint
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: parse error at (cilium/charts/hubble-ui/templates/serviceaccount.yaml:10): unexpected {{end}}

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by sayboras** [comment]
Feel like we can run basic linting and helm test as part of PR as well.

**Comment by tklauser** [comment]
Regarding linting: on a somewhat similar topic there's also #10425 reported with a draft PR at #10431. Maybe these linting/consistency checks could be combined in a single CI action?

/cc @fristonio who has been working on said PR.

**Comment by sayboras** [comment]
@tklauser thanks for your info. I feel like it's exactly the same idea, but I took github action route to simplify some of the scripting effort.

As developer, it's _always_ great to have steps runnable locally as well
