### ISSUE TITLE
Verify endpoint state restore

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1140]
- [x] Verify that restarting Cilium pod/ds correctly restores state of previous endpoints/pods
- [x] Add test to k8s CI test

**Comment by aanm** [comment]
@tgraf To add tests in k8s CI test I need to change the daemon set to have the `restore` flag in there. Should we also change our primary ds to have the restore flag by default?

**Comment by tgraf** [comment]
> @tgraf To add tests in k8s CI test I need to change the daemon set to have the restore flag in there. Should we also change our primary ds to have the restore flag by default?

Yes, any reason not to default on and require `--restore=false`? I can't recall anything.

**Comment by aanm** [comment]
> Yes, any reason not to default on and require --restore=false? I can't recall anything.

I think the only reason was that it was taking too much time to restore the endpoints. If cilium takes too much time, cilium-docker bails out and doesn't connect to cilium.

**Comment by tgraf** [comment]
> I think the only reason was that it was taking too much time to restore the endpoints. If cilium takes too much time, cilium-docker bails out and doesn't connect to cilium.

Then we should fix cilium-docker to continue trying.
