### ISSUE TITLE
CI: RuntimeMemcache Testing binary memcache Tests policy allowing all actions

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#11412]
Seems like a test setup failure, memcache client container is not running, all memcache tests fail because of that.

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10121/

**Comment by christarazi** [comment]
Ran this test focused locally 117 times without failure

**Comment by joestringer** [comment]
Potential duplicate of https://github.com/cilium/cilium/issues/9812 ?

**Comment by christarazi** [comment]
Ah, yes it is. I converted this issue from the "Disabled tests" project.

**Comment by joestringer** [comment]
Cool, I marked the other one as duplicate and closed it.

**Comment by christarazi** [comment]
Dropping this for now as it's not as high priority as https://github.com/cilium/cilium/issues/11512
