### ISSUE TITLE
CI: Test NodePort BPF with global.endpointRoutes.enabled=true from outside

### ISSUE THREAD

**Issue by brb** [cilium/cilium#11420]
https://github.com/cilium/cilium/pull/11419 revealed that we currently don't test from outside the NodePort BPF when the per endpoint routes feature is enabled.

**Comment by borkmann** [comment]
potential dup with #10462

**Comment by borkmann** [comment]
context here: adding test to CI

**Comment by brb** [comment]
We added such tests long time ago, e.g., - https://github.com/cilium/cilium/blob/v1.15.1/.github/workflows/conformance-e2e.yaml#L173.
