### ISSUE TITLE
Cilium agent logs complain about `Unable to fetch kubernetes labels`

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11430]
Affected versions:
* Cilium 1.7.x
* Potentially later versions, not yet observed.

At this stage, only observed in CI (https://github.com/cilium/cilium/issues/10442).

#### Always observed

1. Every 15s or so, the cilium-agent log prints a warning about `Unable to fetch kubernetes labels`:
   ```
   level=warning msg="Unable to fetch kubernetes labels" containerID=015ef4fdbf datapathPolicyRevision=2 desiredPolicyRevision=1 endpointID=1596 error="pod.core \"app3-c6c587577-fq6kr\" not found" identity=5 ipv4=10.10.0.197 ipv6="f00d::a0a:0:0:aeec" k8sPodName=default/app3-c6c587577-fq6kr subsys=resolve-labels-default/app3-c6c587577-fq6kr
   ```
1. `cilium status` reports failing controllers with `resolve-labels-xxx`:
   ```
   Failed controllers:
    controller resolve-labels-default/app1-68cb4f68c5-cftnr failure 'pod.core "app1-68cb4f68c5-cftnr" not found'
   ```
1. There is no corresponding pod for these endpoints.
1. Endpoints show up in the cilium endpoint list with the identity `reserved:init`, and they never get a proper identity:

   ```
   cmd: kubectl exec -n kube-system cilium-56pmk -- cilium endpoint list
   Exitcode: 0 
   Stdout:
    	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                            
   IPv6                 IPv4          STATUS   
   	            ENFORCEMENT        ENFORCEMENT                                                                                                            
   	 898        Enabled            Enabled           5          reserved:init                                          f00d::a0a:0:0:af1    10.10.0.151   ready   
   	 1479       Enabled            Enabled           5          reserved:init                                          f00d::a0a:0:0:969e   10.10.0.149   ready   
   ```

#### May also be observed

1. Cannot deploy new Kubernetes pods. Pod deploy logs report IPAM exhaustion.

### Impact

~There is no known impact other than the failure logs potentially consuming disk space.~ The related application pods were already deleted so there is no traffic impact.
*UPDATE 2020-02-14*: One impact if pods continue to be deployed to this node while the node is in this state, is that each "phantom" endpoint consumes an IP address. If the total number of "phantom" endpoints reaches the size of the podCIDR allocated to the node, then IPAM will begin to fail and subsequent pod deployments onto the node may fail until user action is taken to mitigate.

### Migitation

Restarting the cilium-agent should cause Cilium to reevaluate the existence of this endpoint and clean up.

If you have more details on this issue, for example because you observe it in a real Cilium deployment, please post details below and react to this issue with :+1: so we know how widely it afffects the community.

**Comment by diversario** [comment]
Seeing this currently happening to one Cilium 1.7.4 agent in k8s 1.16:

```
Controller Status:      157/159 healthy
  Name                                                                  Last success   Last error   Count   Message
  resolve-labels-deployment-4459/webserver-deployment-c7997dcc8-tgq7m   never          2m26s ago    231     pod.core "webserver-deployment-c7997dcc8-tgq7m" not found
  sync-to-k8s-ciliumendpoint (3912)                                     never          2m8s ago     231     namespaces "deployment-4459" not found
```

the pod and namespace in question were created and removed by Sonobuoy. It doesn't appear to be causing actual issues. Running `cilium endpoint disconnect 3912` resolved the complaints.

**Comment by joestringer** [comment]
Observed again with Cilium v1.7.11.

**Comment by joestringer** [comment]
@diversario have you seen this issue again recently? Are you still using Cilium v1.7.x or have you moved to a newer release at this point?

**Comment by uhthomas** [comment]
Observed in v1.9.1. Will update to v1.9.4 and hope for the best.

**Comment by diversario** [comment]
> @diversario have you seen this issue again recently? Are you still using Cilium v1.7.x or have you moved to a newer release at this point?

I've not looked into this recently so I can't tell one way or another. I'm currently at 1.8.x.

**Comment by mnaser** [comment]
I just ran into this too with Cilium 1.9.6 and Kubernetes 1.19.10 too.

The 'phantom' pods were all previously-deleted jobs.

**Comment by mnaser** [comment]
This is a really hacky thing, but maybe someone can use it too.

```
 kubectl -n kube-system get pods -l k8s-app=cilium -oname | xargs -I{} kubectl -n kube-system exec {} -- /bin/bash -c "cilium endpoint list | grep serviceaccount=failed-job-reaper -B2 | grep uid | cut -d' ' -f1 | xargs -n1 -P20 cilium endpoint disconnect"
```

failed-job-reaper was the service account, play with it and let it do your thing.

**Comment by joestringer** [comment]
I've reopened the issue since it seems like community users are still observing this.

As for next steps, I think we need a short set of reliable steps to reproduce the issue. It's a bit tricky to understand how Cilium manages to get into this state in the first place at the moment. Is it due to use of k8s jobs or batches? Or are there other common steps that trigger this behaviour? It may also help if someone can upload a [sysdump](https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection) from a cluster where the problem is actively occurring.

**Comment by ulfox** [comment]
We will get a sysdump next time this triggers

**Comment by aanm** [comment]
@ulfox @mnaser @uhthomas I'm going to close this GH issue. Feel free to open a new GH issue with a sysdump in case you see it again. Thank you!

**Comment by brandshaide** [comment]
We're observing this behaviour on one of our AKS clusters. Unfortunately, before doing a sysdump, we've killed the agent. We'd provide a sysdump once this happens again. Can you re-open this issue, @joestringer ?

**Comment by brandshaide** [comment]
@joestringer fyi: generated
 sysdump while facing described issue

**Comment by DerrickMartinez** [comment]
I'm seeing this in k8s 1.26.3 with cilium 1.13.2

level=warning msg="Unable to fetch kubernetes labels" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=527 error="pod.core \"api-687d68f54d-4fp9h\" not found" identity=5 ipv4= ipv6= k8sPodName=/ subsys=resolve-labels

**Comment by DerrickMartinez** [comment]
Doing a cilium ip list
Error: Cannot get ipcache entries. err: Cilium API client timeout exceeded

**Comment by round-corgi** [comment]
Just want to say we're occasionally running into this as well.  At some point, a Cilium pod stops being able to communicate with the apiServer.

We're seeing this error - `Unable to fetch kubernetes labels`

`cilium ip list` returns a time out, and new pods cannot be created on the node with this error:

```
3m38s       Warning   FailedCreatePodSandBox   pod/blah                  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "75ae743023fa39316767c49aefb58833863f09f28793a4c019e8bb52c536b5da" network for pod "blah": networkPlugin cni failed to set up pod "blah" network: Unable to create endpoint: Cilium API client timeout exceeded
```

`cilium status` looks green, IPAM shows 17/254 IPs allocated.

**Comment by eiqops** [comment]
We were experiencing the same problem in EKS `1.24` and `1.25`, we created a cronjob to restart the cilium agent every 3h and this helped us to reduce 95% of the incidents. 

However since we upgraded cilium to `1.13.4` the issue disappeared completely, posting this after two weeks of testing and monitoring in prod, as we can't reproduce the issue anymore.

**Comment by rbrtbnfgl** [comment]
Hi we had a similar issue with Cilium `1.13.2`. One of the worker node isn't able to contact the API server with `cilium ip list` and every new pods scheduled on that node can't contact any other services. With `cilium monitor -t drop` on the agent of the broken node all the packets are dropped with `Policy denied`.

**Comment by nijich** [comment]
Observe this in v1.14.6.
