### ISSUE TITLE
Use a single cilium DaemonSet file for standard k8s and minikube

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1144]
- [x] test with recent minikube and check if etcd >=3.1.0
- [x] change the daemonset to use the available etcd address / configuration file.

**Comment by tgraf** [comment]
Has this been completed?

**Comment by tgraf** [comment]
@aanm What needs to be done here?

**Comment by aanm** [comment]
@tgraf The GSG is working in our multi node environment. I think the only missing part is to check if minikube has `etcd >= 3.1.0`
