### ISSUE TITLE
ignored KUBERNETES_SERVICE_HOST option

### ISSUE THREAD

**Issue by sergey-safarov** [cilium/cilium#11447]
## Bug report
**General Information**
Operator container ignores specified deployment `KUBERNETES_SERVICE_HOST` options and still wants connect using IP on WAN interface.

- Cilium version (run `cilium version`)
```
1.7.2
```
- Kernel version (run `uname -a`)
```
Linux safarov-server.home 5.7.0-0.rc1.20200416git9786cab67457.1.el8.x86_64 #1 SMP Tue Apr 21 07:52:08 GMT 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump
[cilium-sysdump-20200509-194025.zip](https://github.com/cilium/cilium/files/4604374/cilium-sysdump-20200509-194025.zip)

**How to reproduce the issue**

1. specify `KUBERNETES_SERVICE_HOST` inside quick-install.yaml
2. install cilium
3. check operator logs

**Comment by sergey-safarov** [comment]
As workaround may be edit cilium-operator daemonset.
Required to change `KUBERNETES_SERVICE_HOST` value.
```
kubectl edit Deployments cilium-operator -n kube-system
```

**Comment by sergey-safarov** [comment]
`KUBERNETES_SERVICE_HOST` must be specified multiple times inside quick-install.yaml

**Comment by brb** [comment]
@sergey-safarov Thanks for the report. How did you install cilium? If you follow https://docs.cilium.io/en/v1.7/gettingstarted/kubeproxy-free/, then the helm method will set the missing env var.

**Comment by sergey-safarov** [comment]
I saved "help template" to disk as quick-install.yaml.
Then I updated actual IP in yum file and uploaded into k8s.

Be mistake I updated in one place.

**Comment by brb** [comment]
Yep, you need to update it in two places.
