### ISSUE TITLE
Restarting unmanaged kube-dns pod

### ISSUE THREAD

**Issue by Ruilkyu** [cilium/cilium#11444]
Restarting unmanaged kube-dns pod kube-system/coredns-868cf49589-tz76t started 30.413485636s ago" subsys=cilium-operator

**Comment by tklauser** [comment]
Thank you for the report. Could you please provide some additional info, i.e. as found in the bug issue template:

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. instruction 1
2. instruction 2

**Comment by aanm** [comment]
This happens if Cilium considers that kube-dns is not managed by Cilium.

@Ruilkyu make sure `--disable-endpoint-crd=false` is set in the cilium-agent flags.
