### ISSUE TITLE
exit status 255

### ISSUE THREAD

**Issue by Ruilkyu** [cilium/cilium#11458]
level=error msg="Command execution failed" cmd="[/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 172.30.0.152 <nil> vxlan bond0 <nil> <nil> 1500 false <nil> true true /var/run/cilium/cgroupv2 /sys/fs/bpf true true v2 bond0=0xc040a0a <nil>]" error="exit status 255" subsys=datapath-loader

**Comment by tklauser** [comment]
Thank you for the report. Could you please provide some additional info, i.e. as found in the bug issue template:

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. instruction 1
2. instruction 2
