### ISSUE TITLE
BPF system config check: NOT OK

### ISSUE THREAD

**Issue by Ruilkyu** [cilium/cilium#11462]
level=warning msg="BPF system config check: NOT OK." error="CONFIG_BPF kernel parameter is required" subsys=linux-datapath

**Comment by christarazi** [comment]
Hi @Ruilkyu, this message means that the kernel you're running Cilium on does not have the CONFIG_BPF param turned on. Please take a look at this page to verify your setup: https://docs.cilium.io/en/v1.7/install/system_requirements/?highlight=CONFIG_BPF#linux-kernel

**Comment by brb** [comment]
More likely that it's https://github.com/cilium/cilium/issues/10256. @Ruilkyu which Linux distro do you run?

**Comment by Ruilkyu** [comment]
But,when I use cilium1.7.2, It can work normally

**Comment by brb** [comment]
The warning https://github.com/cilium/cilium/issues/10256 has been fixed.
