### ISSUE TITLE
operator: identityHeartbeat is nil in k8s_cep_gc.go

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium#11472]
## Bug report

**General Information**

- Cilium version (run `cilium version`) - current master
- Kernel version (run `uname -a`) - `Linux k8s1 4.9.212-0409212-generic #202001300045 SMP Thu Jan 30 00:48:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) - vagrant dev VM
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. Set up the Vagrant development VM - `K8S=1 ./contrib/vagrant/start.sh`
2. Observe the following error occuring many times (after each time, operator gets restarted) in `journalctl -u cilium-operator`:

```
May 11 14:51:05 k8s1 cilium-operator[8153]: level=debug msg="Marking identity alive" identity=104 subsys=identity-heartbeat
May 11 14:51:05 k8s1 cilium-operator[8153]: panic: runtime error: invalid memory address or nil pointer dereference
May 11 14:51:05 k8s1 cilium-operator[8153]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18f8e10]
May 11 14:51:05 k8s1 cilium-operator[8153]: goroutine 174 [running]:
May 11 14:51:05 k8s1 cilium-operator[8153]: github.com/cilium/cilium/operator/identity.(*IdentityHeartbeatStore).MarkAlive(0x0, 0xc00082a750, 0x3, 0xbfa67776308d0bd0, 0xa91ec13, 0x302fd00)
May 11 14:51:05 k8s1 cilium-operator[8153]:         /home/vagrant/go/src/github.com/cilium/cilium/operator/identity/heartbeat.go:50 +0x170
May 11 14:51:05 k8s1 cilium-operator[8153]: main.enableCiliumEndpointSyncGC.func1(0x20b02a0, 0xc0001bd740, 0x302fd00, 0x0)
May 11 14:51:05 k8s1 cilium-operator[8153]:         /home/vagrant/go/src/github.com/cilium/cilium/operator/k8s_cep_gc.go:102 +0xbce
May 11 14:51:05 k8s1 cilium-operator[8153]: github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc00071ce00)
May 11 14:51:05 k8s1 cilium-operator[8153]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/controller/controller.go:205 +0xa2a
May 11 14:51:05 k8s1 cilium-operator[8153]: created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
May 11 14:51:05 k8s1 cilium-operator[8153]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/controller/manager.go:120 +0xb09
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Failed with result 'exit-code'.
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Service hold-off time over, scheduling restart.
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Scheduled restart job, restart counter is at 7.
May 11 14:51:05 k8s1 systemd[1]: Stopped cilium operator.
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Start request repeated too quickly.
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Failed with result 'exit-code'.
May 11 14:51:05 k8s1 systemd[1]: Failed to start cilium operator.
```

**Comment by aanm** [comment]
It will be fixed by https://github.com/cilium/cilium/pull/11376

**Comment by mrostecki** [comment]
Not sure if #11376 will fix the entire issue in Vagrant.

It seems that we initialize `idendityHeartbeat` only in CRD allocation mode:

https://github.com/cilium/cilium/blob/fb8481a2e9e0f006dde144f64b196addc5fe8529/operator/main.go#L288-L293
https://github.com/cilium/cilium/blob/fb8481a2e9e0f006dde144f64b196addc5fe8529/operator/k8s_identity.go#L111

In Vagrant dev VM, we are using Consul as the kvstore and in the kvstore mode block, we don't initialize `identityHeartbeat`. As far as I see in your PR, it will be still `nil` for kvstore. Probably... I hope I'm wrong. ;)

**Comment by mrostecki** [comment]
OK, please disregard the previous comment - I definitely missed something - your branch fixes the problem.
