### ISSUE TITLE
istiod not running 

### ISSUE THREAD

**Issue by thanhlong9x** [cilium/cilium#11481]
Hi, I'm testing cilium with istio but I have some problem when install istio. When I run cilium-istioctl, I see istiod not running, I checked logs of istiod. Below:

![istiod](https://user-images.githubusercontent.com/29721257/81653477-febf2d80-945e-11ea-9625-4212a02e0c79.PNG)

How to fix this problem ?
Thanks for watching

**Comment by aanm** [comment]
@jrajahalme can you take a look?

**Comment by jrajahalme** [comment]
@thanhlong9x Please update this issue with steps to reproduce if you still have this problem.

**Comment by thanhlong9x** [comment]
@jrajahalme I'm sorry, I can't reproduce this issue. I guess cause from network k8s, I often meet error time-out when get k8s service (10.96.0.1). I often reset network to resolve althought I don't know reason of problem.

**Comment by qmonnet** [comment]
I'm closing this issue, please open a new one if the problem happens again.
