### ISSUE TITLE
llc: bpf_lxc.ll: error: Invalid record

### ISSUE THREAD

**Issue by autumn0207** [cilium/cilium#11483]

**Comment by aanm** [comment]
@autumn0207 can you provide more info?

**Comment by joestringer** [comment]
Here's the standard template:

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. instruction 1
2. instruction 2

**Comment by autumn0207** [comment]
@aanm @joestringer 
sorry, I forget to provide more details yesterday.
I just want to try build cilium myself. 
`cd cilium/bpf && make`
and the err info:
`llc: bpf_lxc.ll: error: Invalid record
Makefile:175: recipe for target 'bpf_lxc.ll' failed
make[1]: *** [bpf_lxc.ll] Error 1
make[1]: Leaving directory '/root/cilium/bpf'
Makefile:21: recipe for target 'build_all' failed
make: *** [build_all] Error 2`

**Comment by aanm** [comment]
@autumn0207 make sure you have all dev requirements setup in your system https://docs.cilium.io/en/latest/contributing/development/dev_setup/

**Comment by myugan** [comment]
@aanm me too have the same problem with @autumn0207 I already install all of requirements and when compiling shown the error like this:

```
....
....
clang -DENABLE_IPV4 -DENABLE_IPV6 -DENABLE_HOST_REDIRECT -DENABLE_NAT46 -DENABLE_ROUTING -DENABLE_IPSEC -I/root/cilium/bpf/include -I/root/cilium/bpf -D__NR_CPUS__=1 -O2 -g -target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_lxc.c -o bpf_lxc.ll
In file included from bpf_lxc.c:5:
In file included from /root/cilium/bpf/include/bpf/api.h:15:
/root/cilium/bpf/include/linux/../bpf/builtins.h:260:24: error: passing 'const void *' to parameter of type 'void *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        return __builtin_bcmp(x, y, len);
                              ^
/root/cilium/bpf/include/linux/../bpf/builtins.h:260:27: error: passing 'const void *' to parameter of type 'void *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        return __builtin_bcmp(x, y, len);
                                 ^
In file included from bpf_lxc.c:5:
In file included from /root/cilium/bpf/include/bpf/api.h:17:
/root/cilium/bpf/include/linux/../bpf/tailcall.h:32:10: error: unknown register name 'r0' in asm
                     : "r0", "r1", "r2", "r3", "r4", "r5");
                       ^
3 errors generated.
Makefile:188: recipe for target 'bpf_lxc.ll' failed
make[1]: *** [bpf_lxc.ll] Error 1
make[1]: Leaving directory '/root/cilium/bpf'
Makefile:139: recipe for target 'bpf' failed
make: *** [bpf] Error 2
```

**Comment by pchaigno** [comment]
@myugan Please make sure you are using LLVM/Clang >= 10.0.

**Comment by myugan** [comment]
Ok, solved! @pchaigno
