### ISSUE TITLE
nat: Do not inc error metric from CT GC if related NAT entry not found

### ISSUE THREAD

**Issue by brb** [cilium/cilium#11485]
Currently, when removing an entry from a BPF map via `(*pkg/bpf.Map) Delete(...)`, a related error metric is incremented if the entry does not exist (`ENOENT`). This leads to many false positive map entry deletion errors when CT GC tries to remove a related NAT entry without checking whether it exists (e.g. `snat_v4_external_delete` reported by @tgraf).

To fix this we could extend `(*pkg/bpf.Map) Delete(...)` by adding a param which controls whether `ENOENT` is expected, and if it's so, then the error metric won't be incremented if the entry is not found.

**Comment by pchaigno** [comment]
There is an initial implementation at https://github.com/cilium/cilium/pull/11526 that can probably be used as a base for this `good-first-issue` (make sure to check the open review comments though).
