### ISSUE TITLE
Introduce sha/date-based Docker tags for Hubble CLI

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#11499]
We want to use a recent version of the Hubble CLI in Cilium CI, but not the `latest` tag. We should introduce a sha/date based tag for the Hubble CI so we can pin specific versions for use in Cilium CI.

**Comment by michi-covalent** [comment]
ok i updated the build trigger, i couldn't figure out how to include timestamp, but it looks reasonable. so what we have is:

- `latest`: the latest build from the head of master branch.
- `$branch`: floating tag that points to the latest build of the branch (e.g. `master`, `v0.5`).
- `$branch-$sha`: non-floating tag for the branch at a specific commit (`master-6441b9f `,  `v0.5-8adcfe8`).
- `$tag`: non-floating tag for a specific tag (e.g. `v0.5.1`).

i guess we'll branch `v1.8` to be in sync with cilium after the feature freeze.

**Comment by michi-covalent** [comment]
https://quay.io/repository/cilium/hubble?tab=tags
