### ISSUE TITLE
libp2p cannot use

### ISSUE THREAD

**Issue by Ruilkyu** [cilium/cilium#11492]
When I run filecoin in the container, it cannot connect to other nodes through libp2p normally。

 github.com/filecoin-project/lotus/node.New
        /builds/ForceMining/lotus-force/node/builder.go:504
  - could not build arguments for function "reflect".makeFuncStub (/usr/lib/golang/src/reflect/asm_amd64.s:12): failed to build *miner.Miner: could not build arguments for function "reflect".makeFuncStub (/usr/lib/golang/src/reflect/asm_amd64.s:12): failed to build beacon.RandomBeacon: function "reflect".makeFuncStub (/usr/lib/golang/src/reflect/asm_amd64.s:12) returned a non-nil error: failed to get group response from beacon peer: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"

**Comment by joestringer** [comment]
How are you deploying Cilium?

Please report using the standard github bug template:

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. instruction 1
2. instruction 2
