### ISSUE TITLE
CI: Runtime pipeline does not gather artifacts

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11503]
## Ginkgo-CI-Tests-runtime-Pipeline

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-runtime-Pipeline/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-runtime-Pipeline/282/

This build (and other recent builds) failed but no artifacts were gathered.

**Comment by joestringer** [comment]
Possibly related to a timeout? Seems like the job stopped fairly close to 1h in.

**Comment by tklauser** [comment]
Another 2 cases where artifacts seem to be missing:

https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/72/
https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/76/
