### ISSUE TITLE
Connectivity instability

### ISSUE THREAD

**Issue by seanpowell-f5** [cilium/cilium#11511]
Greetings,

We are running into some connection stability issues running cilium. We are running metal kubernetes clusters on premise. Details of our environment below:

K8S: 1.17.5 (Deployed with kubespray)
Cilium: 1.7.3 (chaining in portmap for hostPort support)
Host OS: Ubuntu 18.04
Kernel: 4.15.0-99-generic

We have been seeing intermittent connectivity issues to multiple internal and external endpoints. Connect()'s will time out or be reset for no apparent reason across multiple applications. Throughput also appears to suffer from excessive re-transmissions. 

This issue started after upgrading from 1.15.5 (running cilium 1.5.5.) There has been no other change to the upstream infrastructure since this upgrade, and when pods are run in hostNetwork: true they do not experience this behavior. It is only pods that are running networking provided by Cilium that this issue appears.

After some discussion with @aanm on slack, he asked me to create a ticket here. We went over the normal troubleshooting steps provided in the wiki. I have included some output from those tests for reference. Sometimes the endpoint tests will fail, and sometimes the node tests will fail. I have never seen both fail at the same time.

> kubectl -n kube-system exec -ti cilium-bv45g -- cilium status
> KVStore:                Ok   etcd: 3/3 connected, lease-ID=1cae71f5e1608be8, lock lease-ID=1bd771f5e160a9c2, has-quorum=true: https://192.168.180.205:2379 - 3.3.12; https://192.168.180.206:2379 - 3.3.12; https://192.168.180.224:2379 - 3.3.12 (Leader)
> Kubernetes:             Ok   1.17 (v1.17.5) [linux/amd64]
> Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
> KubeProxyReplacement:   Partial   []
> Cilium:                 Ok        OK
> NodeMonitor:            Disabled
> Cilium health daemon:   Ok
> IPAM:                   IPv4: 19/255 allocated from 10.66.5.0/24,
> Controller Status:      95/95 healthy
> Proxy Status:           OK, ip 10.66.5.151, 0 redirects active on ports 10000-20000
> Cluster health:                 7/8 reachable     (2020-05-12T21:39:53Z)
>   Name                          IP                Reachable   Endpoints reachable
>   seacmkube24.pdsea.f5net.com   192.168.180.227   true        false

>  kubectl -n kube-system exec -ti cilium-bv45g -- cilium-health status
> Probe time:   2020-05-12T21:40:53Z
> Nodes:
>   seacmkube22.pdsea.f5net.com (localhost):
>     Host connectivity to 192.168.180.225:
>       ICMP to stack:   OK, RTT=436.86µs
>       HTTP to agent:   OK, RTT=142.325µs
>     Endpoint connectivity to 10.66.5.208:
>       ICMP to stack:   OK, RTT=385.396µs
>       HTTP to agent:   OK, RTT=214.497µs
>   seacmkube05.pdsea.f5net.com:
>     Host connectivity to 192.168.180.205:
>       ICMP to stack:   OK, RTT=441.539µs
>       HTTP to agent:   OK, RTT=352.808µs
>     Endpoint connectivity to 10.66.0.1:
>       ICMP to stack:   OK, RTT=527.883µs
>       HTTP to agent:   OK, RTT=348.015µs
>   seacmkube06.pdsea.f5net.com:
>     Host connectivity to 192.168.180.206:
>       ICMP to stack:   OK, RTT=375.327µs
>       HTTP to agent:   OK, RTT=344.278µs
>     Endpoint connectivity to 10.66.2.173:
>       ICMP to stack:   OK, RTT=424.745µs
>       HTTP to agent:   OK, RTT=318.657µs
>   seacmkube07.pdsea.f5net.com:
>     Host connectivity to 192.168.180.207:
>       ICMP to stack:   OK, RTT=528.337µs
>       HTTP to agent:   OK, RTT=287.051µs
>     Endpoint connectivity to 10.66.3.242:
>       ICMP to stack:   OK, RTT=459.085µs
>       HTTP to agent:   OK, RTT=451.723µs
>   seacmkube08.pdsea.f5net.com:
>     Host connectivity to 192.168.180.208:
>       ICMP to stack:   OK, RTT=367.625µs
>       HTTP to agent:   OK, RTT=323.518µs
>     Endpoint connectivity to 10.66.4.131:
>       ICMP to stack:   OK, RTT=412.042µs
>       HTTP to agent:   OK, RTT=301.392µs
>   seacmkube21.pdsea.f5net.com:
>     Host connectivity to 192.168.180.224:
>       ICMP to stack:   OK, RTT=404.249µs
>       HTTP to agent:   OK, RTT=220.906µs
>     Endpoint connectivity to 10.66.1.24:
>       ICMP to stack:   OK, RTT=562.143µs
>       HTTP to agent:   OK, RTT=336.4µs
>   seacmkube23.pdsea.f5net.com:
>     Host connectivity to 192.168.180.226:
>       ICMP to stack:   OK, RTT=481.044µs
>       HTTP to agent:   OK, RTT=281.945µs
>     Endpoint connectivity to 10.66.6.253:
>       ICMP to stack:   OK, RTT=400.679µs
>       HTTP to agent:   OK, RTT=313.473µs
>   seacmkube24.pdsea.f5net.com:
>     Host connectivity to 192.168.180.227:
>       ICMP to stack:   OK, RTT=443.792µs
>       HTTP to agent:   OK, RTT=431.773µs
>     Endpoint connectivity to 10.66.7.145:
>       ICMP to stack:   OK, RTT=499.525µs
>       HTTP to agent:   Get http://10.66.7.145:4240/hello: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> 

> Cluster health:                 7/8 reachable     (2020-05-11T19:21:53Z)
>   Name                          IP                Reachable   Endpoints reachable
>   seacmkube08.domain.com   192.168.180.208   false       true

Any advice for how to troubleshoot this further would be greatly appreciated.

**Comment by seanpowell-f5** [comment]
Some more information. We are seeing some errors in the cilium agent logs. See samples below.

> level=error msg="Command execution failed" cmd="[tc filter replace dev lxc08f45478ebea ingress prio 1 handle 1 bpf da obj /var/run/cilium/state/782/bpf_lxc.o sec from-container]" error="exit status 2" subsys=datapath-loader
> level=error msg="Error while reloading endpoint BPF program" containerID=f517923519 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=782 error="Failed to load tc filter: exit status 2" identity=23217 ipv4=10.66.5.238 ipv6= k8sPodName=se3-floater/runner-a99pvtsa-project-11952-concurrent-20wglz6 subsys=endpoint
> level=error msg="endpoint regeneration failed" containerID=f517923519 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=782 error="Failed to load tc filter: exit status 2" identity=23217 ipv4=10.66.5.238 ipv6= k8sPodName=se3-floater/runner-a99pvtsa-project-11952-concurrent-20wglz6 subsys=endpoint
> 



> level=error msg="endpoint regeneration failed" containerID=bcd8143e17 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=3964 error="Failed to replace Qdisc for lxc89cb8e5e0df9: Link not found" identity=54306 ipv4=10.66.5.211 ipv6= k8sPodName=se3-runner/runner-d3347dec-project-11952-concurrent-167kmdl subsys=endpoint
> level=error msg="Error while rewriting endpoint BPF program" containerID=bcd8143e17 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=3964 error="Failed to replace Qdisc for lxc89cb8e5e0df9: Link not found" identity=54306 ipv4=10.66.5.211 ipv6= k8sPodName=se3-runner/runner-d3347dec-project-11952-concurrent-167kmdl subsys=endpoint

**Comment by aanm** [comment]
@gandro how reliable is the is the cluster health for this case/

**Comment by gandro** [comment]
> @gandro how reliable is the is the cluster health for this case?

Not sure I understand the question, i.e. what do you mean with "for this case". The health check creates an artificial endpoint which typically is not regenerated (to my knowledge). Which is to say that the health check status is not affected by the "Error while reloading endpoint BPF program" errors of other endpoints.

**Comment by aanm** [comment]
> > @gandro how reliable is the is the cluster health for this case?
> 
> Not sure I understand the question, i.e. what do you mean with "for this case". The health check creates an artificial endpoint which typically is not regenerated (to my knowledge). Which is to say that the health check status is not affected by the "Error while reloading endpoint BPF program" errors of other endpoints.

Sorry, I meant if the output of `cilium-health status`. How many failures can the ping fail before it shows `Client.Timeout exceeded while awaiting headers`?

**Comment by aanm** [comment]
@seanpowell-f5 do you have any cilium network policies installed or firewall rules that would block this traffic?

**Comment by seanpowell-f5** [comment]
Zero policies, no firewalls hardware or software. iptables only has k8s managed entries.
