### ISSUE TITLE
Cilium drops pod traffic that should be allowed by policy (due to CIDR / FQDN identity)

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11517]
## Summary

Cilium 1.7.3. Issue reported from the community during upgrade testing from v1.6.x.
Kernel 4.15.

Connectivity from pod to pod is rejected by policy despite the policy allowing that traffic.

## Symptoms

Cilium monitor reports drops for traffic that should be allowed by policy:

```
# cilium monitor --type=drop
Listening for events on 16 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Policy denied) flow 0xb6b3b6b3 to endpoint 1585, identity 16777388->33623: 10.0.x.y:55454 -> 10.0.a.b:c tcp SYN
```

Source ip `10.0.x.y` Userspace report of ipcache reports that the IP is mapped to a pod identity:

```
# cilium map get cilium_ipcache | grep 10.0.x.y
10.0.x.y/32                                6464 0 10.0.x.y    sync
```

BPF map dump fails due to lack of kernel support:

```
# cilium bpf ipcache list
error dumping contents of map: Unable to get next key from map with file descriptor 5: errno 524
```

The IP also appears in the identity list as a CIDR identity:
```
cilium-identity-list.md:16777388   cidr:10.0.x.y/32
```

Furthermore it is listed in `cilium fqdn cache list`:

```
cilium-fqdn-cache-list.md:3906       lookup       foo.namespace.svc.cluster.local.              3600     2020-05-12T19:02:17.413Z   10.0.x.y  
```

Cilium status reports that the ipcache-bpf-garbage-collection controller has recently run successfully on the node, so userspace should be in sync with the datapath:

```
 ipcache-bpf-garbage-collection              1m47s ago      never        0       no error
```

Endpoint was regenerated regularly per expected ipcache GC controller behaviour:

```
$ grep -e "Endpoint Log" -e "ipcache" cilium-debuginfo-20200512-180805.689+0000-UTC.md | grep -A 200 1585 | head -n+8
#### Endpoint Log 1585
2020-05-12T18:06:16Z   OK       waiting-to-regenerate   Successfully regenerated endpoint program (Reason: datapath ipcache)
2020-05-12T18:06:13Z   OK       regenerating            Regenerating endpoint: datapath ipcache
2020-05-12T18:06:13Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to datapath ipcache
2020-05-12T18:01:12Z   OK       waiting-to-regenerate   Successfully regenerated endpoint program (Reason: datapath ipcache)
2020-05-12T18:01:10Z   OK       regenerating            Regenerating endpoint: datapath ipcache
2020-05-12T18:01:08Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to datapath ipcache
2020-05-12T17:56:06Z   OK       ready                   Successfully regenerated endpoint program (Reason: datapath ipcache)
```

If we look more broadly at the regenerations occurring around the time of the ipcache-triggered regenerations, we also see other reasons and there is not a 1-1 correlation between triggers and moving the endpoint into "ready" state, for example:

```
2020-05-12T18:06:27Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to one or more identities created or deleted
2020-05-12T18:06:16Z   OK       ready                   Successfully regenerated endpoint program (Reason: one or more identities created or deleted)
2020-05-12T18:06:16Z   OK       ready                   Completed endpoint regeneration with no pending regeneration requests
2020-05-12T18:06:16Z   OK       regenerating            Regenerating endpoint: one or more identities created or deleted
2020-05-12T18:06:16Z   OK       waiting-to-regenerate   Successfully regenerated endpoint program (Reason: datapath ipcache)
2020-05-12T18:06:16Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to one or more identities created or deleted
2020-05-12T18:06:13Z   OK       regenerating            Regenerating endpoint: datapath ipcache
2020-05-12T18:06:13Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to datapath ipcache
2020-05-12T18:05:33Z   OK       ready                   Successfully regenerated endpoint program (Reason: one or more identities created or deleted)
```

**Comment by joestringer** [comment]
As a bit of background, every upsert into the ipcache is governed by a set of precedence rules:

```
$ git grep -A 3 "IPIdentityCache.Upsert" | grep -v -e "_test.go" -e "^--"
daemon/datapath.go:             ipcache.IPIdentityCache.Upsert(ipIDPair.PrefixString(), nil, hostKey, nil, ipcache.Identity{
daemon/datapath.go-                     ID:     ipIDPair.ID,
daemon/datapath.go-                     Source: source.Local,
daemon/datapath.go-             })
pkg/ipcache/cidr.go:            IPIdentityCache.Upsert(prefixString, nil, 0, nil, Identity{
pkg/ipcache/cidr.go-                    ID:     id.ID,
pkg/ipcache/cidr.go-                    Source: source.Generated,
pkg/ipcache/cidr.go-            })
pkg/ipcache/kvstore.go:                         IPIdentityCache.Upsert(ip, ipIDPair.HostIP, ipIDPair.Key, k8sMeta, Identity{
pkg/ipcache/kvstore.go-                                 ID:     ipIDPair.ID,
pkg/ipcache/kvstore.go-                                 Source: source.KVStore,
pkg/ipcache/kvstore.go-                         })
pkg/k8s/watchers/cilium_endpoint.go:                            ipcache.IPIdentityCache.Upsert(pair.IPV4, nodeIP, encryptionKey, k8sMeta,
pkg/k8s/watchers/cilium_endpoint.go-                                    ipcache.Identity{ID: id, Source: source.CustomResource})
pkg/k8s/watchers/cilium_endpoint.go-                    }
pkg/k8s/watchers/cilium_endpoint.go-
pkg/k8s/watchers/cilium_endpoint.go:                            ipcache.IPIdentityCache.Upsert(pair.IPV6, nodeIP, encryptionKey, k8sMeta,
pkg/k8s/watchers/cilium_endpoint.go-                                    ipcache.Identity{ID: id, Source: source.CustomResource})
pkg/k8s/watchers/cilium_endpoint.go-                    }
pkg/k8s/watchers/cilium_endpoint.go-            }
pkg/k8s/watchers/pod.go:                selfOwned := ipcache.IPIdentityCache.Upsert(podIP, hostIP, hostKey, k8sMeta, ipcache.Identity{
pkg/k8s/watchers/pod.go-                        ID:     identity.ReservedIdentityUnmanaged,
pkg/k8s/watchers/pod.go-                        Source: source.Kubernetes,
pkg/k8s/watchers/pod.go-                })
```

The function below is used to resolve conflicts between different sources of ipcache entries:

https://github.com/cilium/cilium/blob/2141ecac532028b885f10d927ee590de63e3eb38/pkg/source/source.go#L46-L79

In this case, basically the CIDR identities are "generated", and they're the lowest priority; any other kind of identity update can overwrite the CIDR identity in the ipcache, and the CIDR identity can basically only be overwritten by another CIDR Identity.

That said, as far as userspace is concerned, the identity was already overridden with a real pod identity, likely from the kvstore:

```
# cilium map get cilium_ipcache | grep 10.0.x.y
10.0.x.y/32                                6464 0 10.0.x.y    sync
```

If we look at what this command reports:

https://github.com/cilium/cilium/blob/2141ecac532028b885f10d927ee590de63e3eb38/cilium/cmd/map_get.go#L77-l78

We have a `DesiredAction` here. With a little grep magic we find that basically the `sync` is telling us that the entry is synchronized with the BPF map:

```
$ git grep -A 5 DesiredAction pkg/ | head -n 20
pkg/bpf/map.go:// DesiredAction is the action to be performed on the BPF map
pkg/bpf/map.go:type DesiredAction int
pkg/bpf/map.go-
pkg/bpf/map.go-const (
pkg/bpf/map.go- // OK indicates that to further action is required and the entry is in
pkg/bpf/map.go- // sync
pkg/bpf/map.go: OK DesiredAction = iota
pkg/bpf/map.go-
pkg/bpf/map.go- // Insert indicates that the entry needs to be created or updated
pkg/bpf/map.go- Insert
pkg/bpf/map.go-
pkg/bpf/map.go- // Delete indicates that the entry needs to be deleted
--
pkg/bpf/map.go:func (d DesiredAction) String() string {
pkg/bpf/map.go- switch d {
pkg/bpf/map.go- case OK:
pkg/bpf/map.go-         return "sync"
pkg/bpf/map.go- case Insert:
pkg/bpf/map.go-         return "to-be-inserted"
```

The above suggests to me that the ipcache bpf map that userspace is reporting as "in sync" is not the exact same bpf map which is currently in use on the datapath side.

**Comment by joestringer** [comment]
Kernel 4.15 is in use here, which is interesting, because it lacks full support for LPM maps, and therefore we periodically trigger garbage collection for the ipcache map by creating a new map, repopulating it from `pkg/ipcache.IPIdentityCache`, then deleting the old map and reloading the BPF programs.

https://github.com/cilium/cilium/blob/c99b97a1ddd743944f9c211f47905fc6e1025945/pkg/datapath/ipcache/listener.go#L255-L261

The corresponding controller reports recent success here:

```
$ grep ipcache cilium-status---verbose.md
  ipcache-bpf-garbage-collection              1m47s ago      never        0       no error
```

Digging through the sysdump I'm actually seeing multiple LPM maps still loaded, though I'm not exactly sure why:

```
$ grep lpm bpftool-map-show.md
2: lpm_trie  flags 0x1
3: lpm_trie  flags 0x1
4: lpm_trie  flags 0x1
5: lpm_trie  flags 0x1
6: lpm_trie  flags 0x1
7: lpm_trie  flags 0x1
319: lpm_trie  flags 0x1
```
This could either indicate that there are endpoints using an outdated ipcache, or alternatively just that userspace is not cleaning up its old fd references to older ipcache maps (which would be unrelated to the reported issue here).

AFAICT there's only 3 maps that may use LPM in the Cilium v1.7 branch, and the other two are for XDP programs which are not in use:

```
 $ git grep -e LPM_TRIE -e LPM_MAP_TYPE bpf/
bpf/Makefile:    -DHAVE_LPM_MAP_TYPE \
bpf/Makefile:    -DENABLE_IPV4:-DHAVE_LPM_MAP_TYPE \
bpf/Makefile:    -DENABLE_IPV4:-DHAVE_LPM_MAP_TYPE:-DHAVE_LRU_MAP_TYPE \
bpf/Makefile:    -DENABLE_IPV6:-DHAVE_LPM_MAP_TYPE \
bpf/Makefile:    -DENABLE_IPV6:-DHAVE_LPM_MAP_TYPE:-DHAVE_LRU_MAP_TYPE \
bpf/Makefile:    -DENABLE_IPV4:-DENABLE_IPV6:-DHAVE_LPM_MAP_TYPE:-DHAVE_LRU_MAP_TYPE \
bpf/bpf_xdp.c:#ifndef HAVE_LPM_MAP_TYPE
bpf/bpf_xdp.c:  .type           = BPF_MAP_TYPE_LPM_TRIE,
bpf/bpf_xdp.c:  .type           = BPF_MAP_TYPE_LPM_TRIE,
bpf/include/linux/bpf.h:/* Key of an a BPF_MAP_TYPE_LPM_TRIE entry */
bpf/include/linux/bpf.h:        BPF_MAP_TYPE_LPM_TRIE,
bpf/lib/eps.h:#ifndef HAVE_LPM_MAP_TYPE
bpf/lib/eps.h:#else /* HAVE_LPM_MAP_TYPE */
bpf/lib/eps.h:#endif /* HAVE_LPM_MAP_TYPE */
bpf/lib/maps.h:#ifdef HAVE_LPM_MAP_TYPE
bpf/lib/maps.h:#define LPM_MAP_TYPE BPF_MAP_TYPE_LPM_TRIE
bpf/lib/maps.h:#define LPM_MAP_TYPE BPF_MAP_TYPE_HASH
bpf/lib/maps.h:#ifndef HAVE_LPM_MAP_TYPE
bpf/lib/maps.h:#endif /* HAVE_LPM_MAP_TYPE */
bpf/lib/maps.h: .type           = LPM_MAP_TYPE,
bpf/probes/raw_lpm_map.t:               .emits  = "HAVE_LPM_MAP_TYPE",
bpf/probes/raw_lpm_map.t:                               .type           = BPF_MAP_TYPE_LPM_TRIE,
bpf/sockops/Makefile:    -DHAVE_LPM_MAP_TYPE \
```

One of the things I'm wondering about is how the `cilium map get cilium_ipcache` view is kept up-to-date and whether it is representative of the core `pkg/ipcache:IPIdentityCache` in-memory structure. We actually have an API for this but it seems that no-one wrote a CLI against it. Using this, we may be able to tell whether it's the in-memory state that's wrong or whether it's more likely that we have some kind of datapath reload type issue where the reload doesn't occur properly and so endpoints retain a reference to an old ipcache BPF map.

I've filed a draft PR to add this CLI, this can potentially provide us a way to get more info at least (compiled; not yet tested): https://github.com/cilium/cilium/pull/11566

**Comment by tklauser** [comment]
> any other kind of identity update can overwrite the CIDR identity in the ipcache, and the CIDR identity can basically only be overwritten by another CIDR Identity.

I'm not quite sure I understand this part. If the CIDR identity can be overwritten by any other kind of identity, why can it only be overwritten by another CIDR identity?

**Comment by joestringer** [comment]
> >    any other kind of identity update can overwrite the CIDR identity in the ipcache, and the CIDR identity can basically only be overwritten by another CIDR Identity.

> @joestringer I'm not quite sure I understand this part. If the CIDR identity can be overwritten by any other kind of identity, why can it only be overwritten by another CIDR identity?

Sorry, I miswrote. Here's what I intended:

any other kind of identity update can overwrite the CIDR identity in the ipcache, and the CIDR identity can basically only overwrite another CIDR Identity.

For the concrete details, see the `AllowOverwrite()` function I linked in my prior comment.

**Comment by joestringer** [comment]
The CLI PR is now ready for review, with this we will be able to determine with more certainty whether the problem is with the source of the ipcache entries or whether it is with the datapath replacement:

https://github.com/cilium/cilium/pull/11566

**Comment by borkmann** [comment]
> Digging through the sysdump I'm actually seeing multiple LPM maps still loaded, though I'm not exactly sure why:
> 
> ```
> $ grep lpm bpftool-map-show.md
> 2: lpm_trie  flags 0x1
> 3: lpm_trie  flags 0x1
> 4: lpm_trie  flags 0x1
> 5: lpm_trie  flags 0x1
> 6: lpm_trie  flags 0x1
> 7: lpm_trie  flags 0x1
> 319: lpm_trie  flags 0x1
> ```

If you look at where the id 2-7 LPM is used in the prog list then this is:
```
2: cgroup_skb  tag 7be49e3934a125ba
	loaded_at 2020-05-12T14:41:34+0000  uid 0
	xlated 296B  jited 229B  memlock 4096B  map_ids 2,3
3: cgroup_skb  tag 2a142ef67aaad174
	loaded_at 2020-05-12T14:41:34+0000  uid 0
	xlated 296B  jited 229B  memlock 4096B  map_ids 2,3
4: cgroup_skb  tag 7be49e3934a125ba
	loaded_at 2020-05-12T14:41:34+0000  uid 0
	xlated 296B  jited 229B  memlock 4096B  map_ids 4,5
5: cgroup_skb  tag 2a142ef67aaad174
	loaded_at 2020-05-12T14:41:34+0000  uid 0
	xlated 296B  jited 229B  memlock 4096B  map_ids 4,5
6: cgroup_skb  tag 7be49e3934a125ba
	loaded_at 2020-05-12T14:41:36+0000  uid 0
	xlated 296B  jited 229B  memlock 4096B  map_ids 6,7
7: cgroup_skb  tag 2a142ef67aaad174
	loaded_at 2020-05-12T14:41:36+0000  uid 0
	xlated 296B  jited 229B  memlock 4096B  map_ids 6,7
```
These are the highly likely installed by systemd [0]. Checking the source, it matches the 8 byte value and the ipv4 and ipv6 LPM key size (bpf_lpm_trie_key==4b + 4b/16b):
```
2: lpm_trie  flags 0x1
	key 8B  value 8B  max_entries 1  memlock 4096B
3: lpm_trie  flags 0x1
	key 20B  value 8B  max_entries 1  memlock 4096B
4: lpm_trie  flags 0x1
	key 8B  value 8B  max_entries 1  memlock 4096B
5: lpm_trie  flags 0x1
	key 20B  value 8B  max_entries 1  memlock 4096B
6: lpm_trie  flags 0x1
	key 8B  value 8B  max_entries 1  memlock 4096B
7: lpm_trie  flags 0x1
	key 20B  value 8B  max_entries 1  memlock 4096B
```
The last LPM map seems to come from our datapath:
```
219: prog_array  flags 0x0
	key 4B  value 4B  max_entries 22  memlock 4096B
	owner_prog_type sched_cls  owner jited
319: lpm_trie  flags 0x1
	key 24B  value 12B  max_entries 512000  memlock 36868096B
```
Few things indicate that this is the only one and that regenerations likely seem to have occured: the map if of `319` and the gap in id space to `219` suggest that there were maps created and torn down in between. The Cilium BPF programs loaded in the system are using `319`. The programs start from id `5739` to id `5962` and prior to `5739`  there is only prog id `11`. The load time of `5739` is `2020-05-12T18:06:13+0000` and the one of `5962` is `2020-05-12T18:06:17+0000` so a range of 4sec for the entire set of Cilium's BPF programs which indicates that the data path was reloaded at once.

  [0] https://github.com/systemd/systemd/blob/master/src/core/bpf-firewall.c
