### ISSUE TITLE
Enable staticcheck as part of build

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#11527]
I noticed that there were some PR to address staticcheck issue regularly

https://github.com/cilium/cilium/pull/11390
https://github.com/cilium/cilium/pull/10858
https://github.com/cilium/cilium/pull/10085
https://github.com/cilium/cilium/pull/7884

It will be better to enforce this as part of PR build I think. As disccussed on slack, we can enable some basic linters such as staticcheck, gofmt, govet, ineffassign as starting point.

**Comment by mrostecki** [comment]
I see that you are working on it, so I'm assigning you. ;)
