### ISSUE TITLE
Unknown IPAM backend kubernetes

### ISSUE THREAD

**Issue by ulm0** [cilium/cilium#11539]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
`v1.7.3`
- Kernel version (run `uname -a`)
`Linux host-10-51-160-28 4.12.14-195-default #1 SMP Tue May 7 10:55:11 UTC 2019 (8fba516) x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
rke 1.17.5

**How to reproduce the issue**

According to [docs](https://docs.cilium.io/en/v1.7/concepts/ipam/kubernetes/#configuration) one can set `ipam: kubernetes` in cilium config, but when doing so cilium-agent complains about it with error `Unknown IPAM backend kubernetes`

1. instructions

- Set PodCIDR for cluster
- Set `ipam: kubernetes` in cilium config

**Comment by tklauser** [comment]
Thanks for the report. The `ipam: kubernetes` config option is only available on master and thus in the upcoming Cilium 1.8 release. It seems that section of the documentation got added by mistake in commit a2193a638bdf5188a16e87e8fc3038b7680708a3 through the 1.7 backport PR #11233.

/cc @tgraf @mrostecki

**Comment by aanm** [comment]
It's fixed now, thank you for opening the GH issue @ulm0

**Comment by ulm0** [comment]
Hey guys, is there a way to set this value from helm? By default it uses `cluster-pool` and i need to use PodCIDR from node i've tried `ipam=kubernetes` and `global.ipam.operator.backend=kubernetes` so far and neither works
