### ISSUE TITLE
Docs: Documentation for --egress-masquerade-interfaces

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#11548]
## Bug report
Provide better documentation for --egress-masquerade-interfaces

**General Information**

Documentation for egress-masquerade-interfaces does not provide enough detail for a user to understand what the option does, how to properly specify values, or how it behaves with default values.

**How to reproduce the issue**

1. Search egress-masquerade-interfaces in the documentation.
2. None of the results accurately describes the option. There is a command reference with a minimal description and a reference to using the option in the ENI guide.

**Comment by brb** [comment]
@seanmwinn There were some recent changes to the masquerading documentation: https://docs.cilium.io/en/v1.8/concepts/networking/masquerading/. Could you check whether it addresses your concerns in the issue description?

**Comment by thuydang** [comment]
I'm looking at https://docs.cilium.io/en/v1.13/network/concepts/masquerading/ but still don't know how to set `egress-masquerade-interfaces`. It is not showed in helm-value option so I guess it is set in ConfigMap?

**Comment by gandro** [comment]
The according Helm value is `egressMasqueradeInterfaces`:

https://github.com/cilium/cilium/blob/c0ae00df7d6753d8c1ffa5bb45ac004eb7b479e2/install/kubernetes/cilium/values.yaml#L645

Yeah, we could improve the docs here a bit. PRs welcome.
