### ISSUE TITLE
CI: reserved:host in restoring state, cilium fails readiness probe

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#11559]
IMO the test failure should not be related to the specific test, so decided to title this issue unconventionally.

CI test fails due to cilium never becoming ready. Cilium endpoint list shows an endpoint with identity `reserved:host` is stuck in `restoring` state. Presumably this is related to the host firewall feature?

https://jenkins.cilium.io/job/Cilium-PR-K8s-newest-kernel-4.9/149/testReport/Suite-k8s-1/18/K8sDatapathConfig_ManagedEtcd_Check_connectivity_with_managed_etcd/

Attached artifacts: [53635f7e_K8sDatapathConfig_ManagedEtcd_Check_connectivity_with_managed_etcd.zip](https://github.com/cilium/cilium/files/4636079/53635f7e_K8sDatapathConfig_ManagedEtcd_Check_connectivity_with_managed_etcd.zip)

**Comment by pchaigno** [comment]
That test has been flaky for a while (cf. #11181). The error seems to be the same, so the endpoint being in `restoring` state could be a consequence.

I didn't find anything interested related to the host endpoint in the logs and the host endpoint from the second node was restored successfully. It looks like it may just be that the test ended before that host endpoint finished restoring.

#11544 should fix that flake, so let's keep the present issue open and we'll see if there are other reports. If not, we can close.

**Comment by aanm** [comment]
@pchaigno I believe the issue is related with the host endpoint waiting for a kvstore connection to perform its restoration as the host identity is neither "fixed" nor "well known".

https://github.com/cilium/cilium/blob/9be690a47ab78a2a62a207658c20cac4dd5ba8d9/pkg/endpoint/restore.go#L234-L250
