### ISSUE TITLE
Optimize node manager background sync

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11556]
![image](https://user-images.githubusercontent.com/5714066/82076011-739f9b00-96dd-11ea-856f-4996187f476e.png)

```
runtime.growslice:181
syscall.ParseNetlinkRouteAttr:167
net.interfaceTable:34
net.InterfaceByName:157
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).insertNeighbor:570
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).nodeUpdate:707
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).NodeValidateImplementation:1145
github.com/cilium/cilium/pkg/node/manager.(*Manager).backgroundSync.func1:297
github.com/cilium/cilium/pkg/node/manager.(*Manager).Iter:164
github.com/cilium/cilium/pkg/node/manager.(*Manager).backgroundSync:296
```

For large clusters this controller seems to increase the memory consumption substantially.

Related https://github.com/cilium/cilium/issues/10236

**Comment by aanm** [comment]
![image](https://user-images.githubusercontent.com/5714066/82077101-202e4c80-96df-11ea-958f-f33ae4de0b21.png)

(Roughly 61% (28%+33% for the GC collector) of the CPU usage when the cluster is "silent" is caused by this controller)

**Comment by vladdy** [comment]
Grabbing this one as I've started working on #10236 as well.

**Comment by aanm** [comment]
@vladdy any update?

**Comment by vladdy** [comment]
@aanm, sorry for the delay. I'll start looking into this tomorrow. Btw, is there a way to replicate your tests?

**Comment by aanm** [comment]
@vladdy I notice this when running Cilium on a large cluster and I think you can easily achieve this by manually faking the creation of a lot of CiliumNodes objects in Kubernetes (`kubectl get ciliumnode -o yaml`) which have different IPs and names among each other.

**Comment by aanm** [comment]
@vladdy any update? No pressure :slightly_smiling_face:

**Comment by vladdy** [comment]
@aanm, now after #13112 is closed, I wonder if you would have a chance to test it either after it is released or on a build with that change. It makes the ARP resolution to asynchronous, so there can be some performance gain.
