### ISSUE TITLE
CI: Travis: ENISuite.TestNodeManagerManyNodes fails

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#11560]
## CI failure

```
level=info msg="Synchronized ENI information" numInstances=100 numSecurityGroups=2 numSubnets=4 numVPCs=1 subsys=eni

----------------------------------------------------------------------

FAIL: node_manager_test.go:563: ENISuite.TestNodeManagerManyNodes
node_manager_test.go:602:

    c.Errorf("Node %s allocation mismatch. expected: %d allocated: %d", s.name, minAllocate, node.Stats().AvailableIPs)

... Error: Node node53 allocation mismatch. expected: 10 allocated: 18

node_manager_test.go:602:

    c.Errorf("Node %s allocation mismatch. expected: %d allocated: %d", s.name, minAllocate, node.Stats().AvailableIPs)

... Error: Node node59 allocation mismatch. expected: 10 allocated: 18

node_manager_test.go:617:
    c.Assert(metricsapi.AllocatedIPs("available"), check.Equals, numNodes*minAllocate)

... obtained int = 1016
... expected int = 1000

...
OOPS: 17 passed, 1 FAILED
--- FAIL: Test (2.60s)
FAIL
coverage: 4.3% of statements in ./...

FAIL	github.com/cilium/cilium/pkg/aws/eni	2.684s
FAIL

Makefile:204: recipe for target 'unit-tests' failed
make: *** [unit-tests] Error 1
The command "./.travis/build.sh" exited with 2.

Done. Your build exited with 1.
```

https://travis-ci.com/github/cilium/cilium/jobs/335282883

Seen in https://github.com/cilium/cilium/pull/11555

**Comment by sayboras** [comment]
Not so rare for me
https://travis-ci.com/github/cilium/cilium/jobs/336004501

**Comment by errordeveloper** [comment]
I've seen it twice today.

**Comment by joestringer** [comment]
FWIW:
```
$ find . -name node_manager_test.go
./pkg/ipam/node_manager_test.go
./pkg/aws/eni/node_manager_test.go
```

I tried running these locally and they both passed:

```
$ make unit-tests TESTPKGS=pkg/aws/eni
```
```
$ make unit-tests TESTPKGS=pkg/ipam
```

I'm guessing that there's either an angle here of raciness or an angle of a prior test not cleaning up properly after itself.

**Comment by christarazi** [comment]
> FWIW:
> 
> ```
> $ find . -name node_manager_test.go
> ./pkg/ipam/node_manager_test.go
> ./pkg/aws/eni/node_manager_test.go
> ```
> 
> I tried running these locally and they both passed:
> 
> ```
> $ make unit-tests TESTPKGS=pkg/aws/eni
> ```
> 
> ```
> $ make unit-tests TESTPKGS=pkg/ipam
> ```
> 
> I'm guessing that there's either an angle here of raciness or an angle of a prior test not cleaning up properly after itself.

Hmm, there's definitely some raciness going on. I ran the tests with `-race` enabled, and it found many, many data races. A decent amount of data races are in the `TestNodeManagerManyNodes` so this might explain this Travis failure. I'm working on a PR to fix some data races under just `TestNodeManagerManyNodes`, as there are many data races around this code.

**Comment by christarazi** [comment]
Update on this flake: it looks like PR https://github.com/cilium/cilium/pull/11749 ran into this again. What's interesting is that the usual number of errors when this flake occurs has been reduced dramatically, most likely due to https://github.com/cilium/cilium/pull/11685. Bad news, the flake is not fixed. Good news is that https://github.com/cilium/cilium/pull/11685 made progress. It is likely that there are more data races in the test suite or in the ENI code itself.

**Comment by aanm** [comment]
another occurrence https://github.com/cilium/cilium/pull/11682/checks?check_run_id=718254605

**Comment by errordeveloper** [comment]
I think the test is compares number of allocations to `minAllocate` and expect and exact value, from reading the code I believe it shouldn't be `< minAllocate`.

https://github.com/cilium/cilium/blob/master/pkg/aws/eni/node_manager_test.go#L611-L614

https://github.com/cilium/cilium/blob/05daeef1c29a48928391cb1820c77752675d6bcd/pkg/aws/eni/node_manager_test.go#L627

I'll open a PR and we take it from there :)

**Comment by christarazi** [comment]
If this occurs again which is possible, see https://github.com/cilium/cilium/pull/11773#issuecomment-636153564 for more context.

**Comment by jrajahalme** [comment]
Here as well: https://travis-ci.com/github/cilium/cilium/jobs/341510221

**Comment by christarazi** [comment]
Occurred in https://github.com/cilium/cilium/pull/11786: https://travis-ci.com/github/cilium/cilium/jobs/341598176

**Comment by errordeveloper** [comment]
I removed word 'mismatch' in my PR, so those errors are from an unrebased PR build, perhaps?

**Comment by gandro** [comment]
@pchaigno Any pointers on where this occurred again? We recently removed the primary IP from the allocation pool, might be related?

**Comment by pchaigno** [comment]
@gandro I restarted the Travis CI build where it happened. I'll keep it next time and ping here.

**Comment by gandro** [comment]
Hit again in #16472 

https://travis-ci.com/github/cilium/cilium/jobs/513573358
[log.txt](https://github.com/cilium/cilium/files/6649637/log.txt)

**Comment by brb** [comment]
Hit in #16865. The full log of the failing test case - https://gist.github.com/brb/ebe4764e17d757e3c87c0bfaf45b6d95 (GH doesn't allow me to attach it).

The failure:
```
FAIL: node_manager_test.go:574: ENISuite.TestNodeManagerManyNodes

node_manager_test.go:613:
    c.Errorf("Node %s allocation shortage. expected at least: %d, allocated: %d", s.name, minAllocate, node.Stats().AvailableIPs)
... Error: Node node93 allocation shortage. expected at least: 10, allocated: 0

node_manager_test.go:625:
    c.Assert(metricsapi.Nodes("in-deficit"), check.Equals, 0)
... obtained int = 1
... expected int = 0
```

Interesting part from the log is:
```
level=warning msg="Could not determine first interface index, maximum allocatable ipv4 addresses will be 0 (unlimited) this could lead to ip allocation overflows if the max-allocate flag is not set" first-interface-index=unknown subsys=eni
level=warning msg="Instance type network adapters limit is lower than the configured FirstInterfaceIndex, maximum allocatable ipv4 addresses will be 0 (unlimited) this could lead to ip allocation overflows if the max-allocate flag is not set" adaptors-limit=3 first-interface-index=4 subsys=eni
level=warning msg="Could not determined instance limits, maximum allocatable ipv4 addresses will be 0 (unlimited) this could lead to ip allocation overflows if the max-allocate flag is not set" adaptors-limit=unknown first-interface-index=0 subsys=eni
``

**Comment by brb** [comment]
Checked logs provided in https://github.com/cilium/cilium/issues/11560#issuecomment-860795257, they have the same log message `Instance not found!` for the failing node (`node85`).

**Comment by brb** [comment]
From checking the code it seems that it might be a race. The # of available IPs is retrieved from https://github.com/cilium/cilium/blob/master/pkg/aws/eni/node.go#L513 which errors. This means that the node didn't have any ENI attached, so it returned 0 of available IPs which made the test to fail.

I am not familiar with the node creation lifecycle in the ENI node, but if ENIs are set asynchronously, then the number can be 0.

**Comment by jrajahalme** [comment]
Hit in #16258 (https://app.travis-ci.com/github/cilium/cilium/jobs/532499964):
```
FAIL: node_manager_test.go:563: ENISuite.TestNodeManagerManyNodes
node_manager_test.go:602:
    c.Errorf("Node %s allocation shortage. expected at least: %d, allocated: %d", s.name, minAllocate, node.Stats().AvailableIPs)
... Error: Node node98 allocation shortage. expected at least: 10, allocated: 0
```

**Comment by brb** [comment]
Hit it again https://app.travis-ci.com/github/cilium/cilium/jobs/535750325.

**Comment by errordeveloper** [comment]
And again: https://app.travis-ci.com/github/cilium/cilium/jobs/536459423

**Comment by tklauser** [comment]
Hit in #18062 https://app.travis-ci.com/github/cilium/cilium/jobs/550242889

**Comment by joestringer** [comment]
Removing @christarazi 's stale assignment here. If you plan on working on this, feel free to reassign it back to yourself.
