### ISSUE TITLE
Docs Proposal:  Mark Flannel (beta) integration as non-preferred/deprecated in favor of generic-veth-chaining

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#11565]
Right now it is confusing for a user looking to chain Cilium on top of flannel, as we have two possible mechanisms: 

- https://docs.cilium.io/en/latest/gettingstarted/flannel-integration/
- https://docs.cilium.io/en/latest/gettingstarted/cni-chaining-generic-veth/

Talking to cilium developers, the preference is for the generic veth chaining, but someone searching or reading the docs would likely come to the conclusion that the other flannel integration is the recommended approach.  

Also, this page on chaining (https://docs.cilium.io/en/latest/gettingstarted/cni-chaining/) highlights Calico and Weave, but not Flannel, re-enforcing the notion that veth chaining is probably not the right direction thing to do for Flannel, even though it is the dev team recommendation.   So we should probably highlight flannel as a key use of generic veth-based chaining, or even have a flannel specific example that just uses generic veth chaining in the config.

**Comment by andreek** [comment]
I did configure usage of Flannel with CNI chaining: [chaining.yaml](https://gist.github.com/andreek/93924cf228b2aa0cdbe5fef4c4f9e0b0)

To install cilium I used this helm chart settings:
```shell
helm install cilium cilium/cilium --version 1.8.3 \
  --namespace=kube-system \
  --set global.cni.chainingMode=generic-veth \
  --set global.cni.customConf=true \
  --set global.cni.configMap=cni-configuration \
  --set global.tunnel=disabled \
  --set global.nativeRoutingCIDR=10.244.0.0/16 \
  --set global.masquerade=true \
  --set global.enableEndpointRoutes=true
```
connectivity test:
```shell
NAME                                                     READY   STATUS    RESTARTS   AGE
echo-a-7cfcbc66f-ndql9                                   1/1     Running   0          31s
echo-b-869d875845-wmzg9                                  1/1     Running   0          31s
echo-b-host-ff5b64d5d-pdxjk                              1/1     Running   0          30s
host-to-b-multi-node-clusterip-67548bfd68-9mlg9          1/1     Running   0          29s
host-to-b-multi-node-headless-55bc584bbb-9rlzn           1/1     Running   0          29s
pod-to-a-79444666cb-s6s6x                                1/1     Running   0          30s
pod-to-a-allowed-cnp-7f58895888-scst2                    1/1     Running   0          30s
pod-to-a-denied-cnp-75cb89dfd-tvjtw                      1/1     Running   0          30s
pod-to-b-intra-node-nodeport-7dbdcff754-fzrnp            1/1     Running   0          29s
pod-to-b-multi-node-clusterip-5c949446c4-6hhj5           1/1     Running   0          30s
pod-to-b-multi-node-headless-549ff7f798-spmkm            1/1     Running   0          30s
pod-to-b-multi-node-nodeport-69d7c5df8-cpc45             1/1     Running   0          29s
pod-to-external-1111-654646d47d-mpv8v                    1/1     Running   0          30s
pod-to-external-fqdn-allow-google-cnp-6557d6b7d6-qhbpv   0/1     Running   0          30s
```

It looks like there is still the lack of L7 policy support.
