### ISSUE TITLE
Cilium-agent fails to start in air-gapped network without default gateway set 

### ISSUE THREAD

**Issue by soumynathan** [cilium/cilium#11588]
## Bug report
Cilium-agent fails to start in air-gapped network without default gateway set.

> level=warning msg="Unable to automatically detect MTU" error="unable to lookup route to xxxx:xxxx:xxxx::xxxx: network is unreachable, unable to lookup route to 1.1.1.1: network is unreachable" subsys=mtu
> level=fatal msg="Unable to open service maps" error="Unable to create map /sys/fs/bpf/tc/globals/cilium_proxy4: cannot allocate memory" subsys=daemon

Based on the log analysis it seems that it is first failing to 'autoDetect' the 'mtu' and so fails to start the agent.
We see a fatal failure to open 'service maps'. Not sure if gateway is required.

- [ ] Need to document this behavior in the document and suggest the users to start the agent with manual 'mtu' setting to override the 'autoDetect', if the failure is due to 'autoDetec'.

- [ ] Update the error log with additional information on how to recover.

**Comment by joestringer** [comment]
At a glance, it's not obvious to me why the two log messages from Cilium are related. The second one looks legitimately like there's not enough memory on the system to create the service map. Do we have any alternative explanation for where the `-ENOMEM` error could be coming from?

If we want to improve the MTU probing, I wonder if we could look for the default route instead of `1.1.1.1`? Another thought is whether these `externalProbeIPv4` (and IPv6) probe IPs should be configurable to at least provide a workaround without recompiling Cilium.

**Comment by joestringer** [comment]
I guess here's a question, when you specify the MTU, does the "cannot allocate memory" error go away? Does it return if you remove the MTU setting? Ie can you link the two directly together as cause/effect?

**Comment by soumynathan** [comment]
> I guess here's a question, when you specify the MTU, does the "cannot allocate memory" error go away? Does it return if you remove the MTU setting? Ie can you link the two directly together as cause/effect?
I don't think those two logs are related. Even though the MTU autoDetect fails, I think the default 'mtu' is set. So hopefully it moves forward with that warning message.

I was able to see a similar problem in the master branch, in my development environment when I removed the gateway for the Virtualbox VM and tried to restart the Cilium.service.  It seems the cilium.service is failing to start without the gateway and is complaining that it can't find the 'cilium.sock'.  
```
vagrant@k8s1:/var/run/cilium$ cilium status
Get "http:///var/run/cilium/cilium.sock/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?

**Comment by soumynathan** [comment]
> At a glance, it's not obvious to me why the two log messages from Cilium are related. The second one looks legitimately like there's not enough memory on the system to create the service map. Do we have any alternative explanation for where the `-ENOMEM` error could be coming from?
> 
> If we want to improve the MTU probing, I wonder if we could look for the default route instead of `1.1.1.1`? Another thought is whether these `externalProbeIPv4` (and IPv6) probe IPs should be configurable to at least provide a workaround without recompiling Cilium.

If this is an issue with "Memory" then just by enabling the 'gateway' and restarting the cilium-agent should not succeed. But we are seeing that just by configuring back the gateway and restarting the cilium-agent, it succeeds.

**Comment by soumynathan** [comment]
In the master branch, this is where it fails when restarting the cilium without the gateway set.
```
May 19 23:03:51 k8s1 cilium-agent[3494]: level=info msg="Setting up base BPF datapath (BPF v1 instruction set, ktime clock source)" subsys=datapath-loader
May 19 23:03:51 k8s1 cilium-agent[3494]: level=info msg="Setting sysctl net.core.bpf_jit_enable=1" subsys=datapath-loader
May 19 23:03:51 k8s1 cilium-agent[3494]: level=info msg="Setting sysctl net.ipv4.conf.all.rp_filter=0" subsys=datapath-loader
May 19 23:03:51 k8s1 cilium-agent[3494]: level=info msg="Setting sysctl kernel.unprivileged_bpf_disabled=1" subsys=datapath-loader
May 19 23:03:51 k8s1 cilium-agent[3494]: level=info msg="Setting sysctl net.ipv6.conf.all.disable_ipv6=0" subsys=datapath-loader
May 19 23:03:51 k8s1 cilium-agent[3494]: level=info msg="Before Command Context: " subsys=datapath-loader
May 19 23:03:51 k8s1 cilium-agent[3494]: level=error msg="Command execution failed" cmd="[/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.16.201.23 fd01::b vxlan <ni
l> <nil> <nil> 65536 false <nil> false false /var/run/cilium/cgroupv2 /sys/fs/bpf false true v1 <nil> <nil>]" error="exit status 2" subsys=datapath-loader

**Comment by pchaigno** [comment]
@soumynathan Are you running in debug mode?

**Comment by soumynathan** [comment]
@pchaigno yes I am running in debug mode.
I think I found out the issue. If the default gateway is not set, the 'autoDetect' detects the MTU of the 'loopback' interface and forwards the 65536 mtu instead of "EthernetMTU - 1500".
So it is failing when setting the MTU to the vethpairs in the 'init.sh' scipt.
I will be pushing a PR to fix this soon.

**Comment by soumynathan** [comment]
@joestringer also to answer your previous question, so the MTU issue and the 'Unable to open service maps' might be related based on what I see.
