### ISSUE TITLE
Document process for updating cilium-runtime images for all releases

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11609]
The `cilium-runtime` image used by the `v1.6` releases was last built on 2020-02-17. Over time, package updates are released for the packages included in this image, and unless we perform `apt update && apt upgrade` inside the image, these updates are not picked up. This is not performed in the main `cilium` image, so none of the base packages have been updated for around 3 months.

We should document the process for how we keep the base OS packages up to date in our container images.

Some of the options:
* Move the apt upgrade into the cilium image itself so every image is up to date
* Update cilium-runtime for every release and rebase cilium against that image
* Update cilium-runtime on a dedicated periodic basis
* Monitor image scanners for real issues and update cilium-runtime when packages have CVEs above a severity threshold

**Comment by borkmann** [comment]
> Some of the options:
> 
> * Move the apt upgrade into the cilium image itself so every image is up to date

This adds more layers and therefore would bloat the final image.

> * Update cilium-runtime for every release and rebase cilium against that image

I vote for this one to have it as part of the release process. Good thing at least is that we don't need to rebuild llvm anymore from there, so it should be fast.

**Comment by joestringer** [comment]
> > Move the apt upgrade into the cilium image itself so every image is up to date
> This adds more layers and therefore would bloat the final image.

Long-term I agree. How big do we expect the average update to be? I'm guessing kilobytes, or maybe a few MB. The benefit here would be to avoid the complication associated with generating the cilium-runtime images and rebasing during the release process.

If we did this and periodically folded the updates back into the cilium-runtime image, then we could mitigate this concern with less release overhead.
