### ISSUE TITLE
CI: ensure broken code builds are detected early

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#11640]
We should create a GitHub Action that compiles all of the Go code as well as tests, so that contributors don't have to wait for CI run to find out they made a typo in test code or missed something.

**Comment by joestringer** [comment]
IMO `govet` should also be part of this, at the moment it's lost somewhere in the middle of the Travis unit-tests output.

**Comment by errordeveloper** [comment]
@joestringer yes, for sure! we have a PR for `golangci-lint` (#11528), which may include `govet` (something to check).

**Comment by nebril** [comment]
I would say that this is done by our smoke tests now, closing the issue.

**Comment by errordeveloper** [comment]
@nebril I think it's still not early enough, I was implying the we should run `go test -c`.

**Comment by joestringer** [comment]
I've added this as a good-first-issue to figure out how to get `go test -c` (test compilation) to occur early on during the github actions builds.

**Comment by ti-mo** [comment]
This is no longer an issue today, closing.
