### ISSUE TITLE
cilium-bugtool gathers netstat, but netstat is not provided in cilium container

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11648]
This line attempts to gather netstat output during a `cilium bugtool` / sysdump invocation:

https://github.com/cilium/cilium/blob/054dd163fdb792c44b3c493b8d6fd111e5e1a2bc/bugtool/cmd/configuration.go#L60

However, `netstat` (part of `net-tools` package) is not available in the standard Cilium container images.

We could potentially increase the availability of useful information in sysdumps by installing this package in default images (assuming it isn't too big). Alternatively we could either dump similar information from another source or remove this ineffective line from the bugtool.

**Comment by joestringer** [comment]
Extra points: Assuming we stick with `netstat`, adding `-p` (show process) and `-n` (no name resolution) would be worth adding to this bugtool line.

**Comment by borkmann** [comment]
Another option is to simply include `ss` tool from https://github.com/cilium/packaging/blob/master/Dockerfile.iproute2 .

**Comment by soumynathan** [comment]
> Another option is to simply include `ss` tool from https://github.com/cilium/packaging/blob/master/Dockerfile.iproute2 .

Do you mean 'include the ss' tool  which is not available today in the cilium container?

**Comment by soumynathan** [comment]
@joestringer  I can pick up this work.
