### ISSUE TITLE
bpf: CT drops final FIN+ACK

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1165]
The BPF conntrack code seems to remove the conntrack entry prematurely which leads to the final FIN+ACK being dropped due to lack of conntrack entry:

```
xx drop (CT: Can't create entry from packet) to endpoint 0, identity 0->0: 172.201.28.238:46368 -> 172.201.135.34:8080 tcp ACK, FIN
```

**Comment by borkmann** [comment]
- How reproducible is this issue? (Rare occurrences or almost each time in test env?)
- Latest master or older cilium version?
- Is L7 proxy involved?
- Connection is local on a single node (container <-> container) or spans accross multiple nodes (container <--wire--> container)?
- Is global or local CT table used?
- CT table is LRU or hash table with timeout (probably unlikely we hit the tmo first, though)?
- Did we hit RST in the packet flow earlier (probably not, but would immediately close the entry)?
- Small sample client/server tcpdump packet flow, or pcap would be good for inspection.

**Comment by tgraf** [comment]
> How reproducible is this issue? (Rare occurrences or almost each time in test env?)
Every TCP connection

> Latest master or older cilium version?

Latest master

> Is L7 proxy involved?

It definitely occurs with proxy involved. Likely also with proxy not involved. I suspect it's a general CT handling issue.

> Connection is local on a single node (container <-> container) or spans accross multiple nodes (container <--wire--> container)?

Container to container for both, local node and multi node.

> Is global or local CT table used?

Global CT. Unverified with local table.

> CT table is LRU or hash table with timeout (probably unlikely we hit the tmo first, though)?

Doesn't matter. The failure occurs because we delete the CT entry before the final FIN is processed.

> Did we hit RST in the packet flow earlier (probably not, but would immediately close the entry)?
> Small sample client/server tcpdump packet flow, or pcap would be good for inspection.

No RST. The issue occurs in every TCP connection when FIN is being processed.

**Comment by borkmann** [comment]
Via #1186
