### ISSUE TITLE
Log is spammed with Failed to list *v1.NetworkPolicy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1168]
```
time="2017-07-23T23:27:24Z" level=error msg="github.com/cilium/cilium/daemon/k8s_watcher.go:139: Failed to list *v1.NetworkPolicy: the server could not find the requested resource"
```

**Comment by aanm** [comment]
@tgraf On which version does this happen? Master's doesn't have anything on line `github.com/cilium/cilium/daemon/k8s_watcher.go:139`

**Comment by aanm** [comment]
@tgraf This happens because kubernetes version running with cilium is <1.7. The v1.NetworkPolicy was only introduced in 1.7.

**Comment by tgraf** [comment]
> @tgraf This happens because kubernetes version running with cilium is <1.7. The v1.NetworkPolicy was only introduced in 1.7.

I understand that. We can't spam the log like this for anybody running <1.7.
