### ISSUE TITLE
CI: Suite-k8s-1.14.K8sHubbleTest Hubble Observe Test {L3/L4,L7} Flow: "cannot curl metrics" (GKE)

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#11718]
## CI failure

On GKE, the K8sHubble testsuite seems unable to access the metrics exposed on the hostNetwork port 9091:

### Stacktrace

```
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:471
hubble-cli-m8wnp/hubble-cli-m8wnp cannot curl metrics "10.3.249.181"
Expected command: kubectl exec -n cilium hubble-cli-m8wnp -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 10.128.0.36:9091/metrics -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 7 
Stdout:
 	 time-> DNS: '0.000040()', Connect: '0.000000',Transfer '0.000000', total '3.052069'
Stderr:
 	 command terminated with exit code 7
	 

/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/k8sT/hubble.go:175
```

The above failure happened at `2020-05-27T12:29:56Z`. The metric server was up an running at this point:
```
2020-05-27T12:27:46.053717165Z level=info msg="Starting Hubble Metrics server" address=":9091" metrics="[dns:query;ignoreAAAA drop tcp flow port-distribution icmp http]" subsys=hubble
```

Curl error code 7 indicates that the `connect()` call failed: 
`CURLE_COULDNT_CONNECT (7) : Failed to connect() to host or proxy. `

[d9882088_K8sHubbleTest_Hubble_Observe_Test_L3-L4_Flow.zip](https://github.com/cilium/cilium/files/4689535/d9882088_K8sHubbleTest_Hubble_Observe_Test_L3-L4_Flow.zip)
https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-GKE/1520/

**Comment by nebril** [comment]
We are back to running GKE pipeline, hopefully we will get some data from there.
