### ISSUE TITLE
Ensure `contrib/scripts/lock-check.sh` runs as a precheck and as a GitHub Action

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#11730]
This would eliminate PRs like this in the future, and provide quicker feedback to the offending PR. https://github.com/cilium/cilium/pull/11729

Items:

 - [x] Create Makefile target to run this precheck
 - [ ] Create a GH Action that runs the above

**Comment by joestringer** [comment]
For what it's worth, this should be part of a standard `make` execution, which:
1) All developers should run prior to submission; and
2) We should have a GH action that runs this target.

**Comment by tklauser** [comment]
FWIW, the script is already invoked as part of the `postcheck` target:

https://github.com/cilium/cilium/blob/e871f2830d1d6a6705a700b1e56f88c6cea21ceb/Makefile#L507-L512

which in turn is part of the `all` target (which is the default target if you run `make` without a specific target):

https://github.com/cilium/cilium/blob/e871f2830d1d6a6705a700b1e56f88c6cea21ceb/Makefile#L130

which leaves me wondering why it only failed in the CI runtime test, but not Travis CI.

**Comment by pchaigno** [comment]
> which leaves me wondering why it only failed in the CI runtime test, but not Travis CI.

Travis CI doesn't do a full `make`. It only compiles what it needs to run the unprivileged unit tests AFAIK.
