### ISSUE TITLE
CI: Verifier error in connect6: back-edge from insn 624 to 570

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#11731]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/1740/testReport/

Cilium logs contain the following verifier error message and tests are failing: 
```
msg="+ tc exec bpf pin /sys/fs/bpf/tc/globals/cilium_cgroups_connect6 obj bpf_sock.o type sockaddr attach_type connect6 sec connect6" subsys=datapath-loader
subsys=datapath-loader
msg="Prog section 'connect6' rejected: Invalid argument (22)!" subsys=datapath-loader
msg=" - Type:         18" subsys=datapath-loader
msg=" - Attach Type:  11" subsys=datapath-loader
msg=" - Instructions: 740 (0 over limit)" subsys=datapath-loader
msg=" - License:      GPL" subsys=datapath-loader
subsys=datapath-loader
msg="Verifier analysis:" subsys=datapath-loader
subsys=datapath-loader
msg="back-edge from insn 624 to 570" subsys=datapath-loader
subsys=datapath-loader
msg="Error fetching program/map!" subsys=datapath-loader
```
I've seen the above error in these tests:
```
Suite-k8s-1.17.K8sHealthTest checks cilium-health status between nodes
Suite-k8s-1.17.K8sKafkaPolicyTest Kafka Policy Tests KafkaPolicies
Suite-k8s-1.17.K8sDatapathConfig MonitorAggregation Checks that monitor aggregation restricts notifications
Suite-k8s-1.17.K8sDatapathConfig MonitorAggregation Checks that monitor aggregation flags send notifications
```
Because we have another error that causes tests with broken Cilium deploy to stay stuck for 40min, the build reached the 3h timeout after running only these 4 tests. I'm guessing other tests would have failed with the same error otherwise.

I'm unsure whether this is a flake or a complete breakage. I haven't had time to investigate further. ~~I guess we'll soon see.~~ It's a complete breakage; 4.19 pipeline is down :'-(

[75e6fd64_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip](https://github.com/cilium/cilium/files/4691875/75e6fd64_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip)
[199f0502_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip](https://github.com/cilium/cilium/files/4691876/199f0502_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.zip)
[58819d2a_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/4691877/58819d2a_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)
[89886bcc_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications.zip](https://github.com/cilium/cilium/files/4691878/89886bcc_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications.zip)

**Comment by pchaigno** [comment]
Likely introduced by #11678 as this is the first PR I could find that failed with these errors. It's not obvious from the changes how they could have introduced a loop :-/

**Comment by pchaigno** [comment]
Issues seems to be this `goto`, to retry the backend selection:
https://github.com/cilium/cilium/blob/5a8501a9565591c1c2897ba8cf0e433429f37469/bpf/bpf_sock.c#L295-L318
Passing on bpf-next kernel since we have support for bounded loops there. `goto` is only hit once since after that `backend_from_affinity` will be false.

**Comment by borkmann** [comment]
Given it's not an issue on bpf-next, we should probably just revert #11678 for now and find a better solution. I'm puzzled why 4.19 didn't break on its CI run.

**Comment by borkmann** [comment]
> Given it's not an issue on bpf-next, we should probably just revert #11678 for now and find a better solution. I'm puzzled why 4.19 didn't break on its CI run.

Ah so it was merged even though the run was broken, sigh.

**Comment by borkmann** [comment]
> > Given it's not an issue on bpf-next, we should probably just revert #11678 for now and find a better solution. I'm puzzled why 4.19 didn't break on its CI run.
> 
> Ah so it was merged even though the run was broken, sigh.

Sent revert here to unblock others, see PR #11678.
