### ISSUE TITLE
add a lint for cilium metrics

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11743]
This can be achieved by starting cilium with `--prometheus-serve-addr=:9090`
```
$ curl  -s http://localhost:9090/metrics  | ./promtool check metrics 
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_bpf_map_ops_total label names should be written in 'snake_case' not 'camelCase'
cilium_endpoint_count non-histogram and non-summary metrics should not have "_count" suffix
cilium_endpoint_regenerations counter metrics should have "_total" suffix
cilium_identity_count non-histogram and non-summary metrics should not have "_count" suffix
cilium_k8s_client_api_calls_counter counter metrics should have "_total" suffix
cilium_k8s_client_api_calls_counter metric name should not include type 'counter'
cilium_nodes_all_events_received_total label names should be written in 'snake_case' not 'camelCase'
cilium_nodes_all_events_received_total label names should be written in 'snake_case' not 'camelCase'
cilium_policy_count non-histogram and non-summary metrics should not have "_count" suffix
cilium_policy_import_errors counter metrics should have "_total" suffix
```

promtool is can be build from https://github.com/prometheus/prometheus/tree/master/cmd/promtool

We can also add the promtool inside the vendor directory similar to what with do with the k8s code generators. For example:
https://github.com/cilium/cilium/blob/3a1bde594b61b1e3425a216b8ae4f7c84b0b8136/tools/go-to-protobuf#L1-L5
https://github.com/cilium/cilium/blob/2b460d7b0a1607e5618492bce38a158ba8f3fb1c/tools/tools.go#L19-L29
https://github.com/cilium/cilium/blob/2b460d7b0a1607e5618492bce38a158ba8f3fb1c/Makefile#L114-L115

**Comment by joestringer** [comment]
By the way, one of the trickier parts of this is how to handle existing metrics. Is it OK to potentially break these metrics by addressing the lint errors? Or do we just add all of these to an exclude list? 

We'll presumably also need to address the grafana side for our standard dashboards if we make any changes.

**Comment by aanm** [comment]
> By the way, one of the trickier parts of this is how to handle existing metrics. Is it OK to potentially break these metrics by addressing the lint errors? Or do we just add all of these to an exclude list?
> 
> We'll presumably also need to address the grafana side for our standard dashboards if we make any changes.

Yes it is ok to brake as long we mention them in the upgrade guide.

**Comment by sayboras** [comment]
I have a look at promtool CLI, it will check on predefined metric dump format only, there is no support for code static analysis. 

Seems like we need to export to metrics first, and perform lint check. What could be the best way to run this ? 
- github action after conformance test
- Or in jenkins CI

Another issue I have with prometheus beofre is its dependency hell :cry:, so might just get the binary via normal `go get` instead of tracking it in go.mod and tools.go.
