### ISSUE TITLE
NodePort svc with externalTrafficPolicy=Local cannot be reached from inside cluster when there are no local backends

### ISSUE THREAD

**Issue by brb** [cilium/cilium#11746]
In kube-proxy, a remote endpoint of a externalTrafficPolicy=Local svc is allowed to be accessed from inside a cluster.

To fix this, we can reorder the endpoints in the `lb{4,6}_service` maps in a way, that first in the list are local backends, and then maintain two counters - for local and for all. This would allow to select only local backends from bpf_host, while bpf_sock can select all.

**Comment by gandro** [comment]
kube-proxy implements this since 1.15: kubernetes/kubernetes#77523
