### ISSUE TITLE
Unable to ping node

### ISSUE THREAD

**Issue by nicolerenee** [cilium/cilium#11802]
## Bug report

**General Information**

- Cilium version: `Daemon: 1.7.4 c7ee6d62b 2020-05-15T16:07:35+02:00 go version go1.13.10 linux/amd64`
- Kernel version `5.4.0-33-generic #37-Ubuntu SMP`
- Orchestration system version in use: Kubernetes 1.18.3

**How to reproduce the issue**

1. Install cilium in Kubeproxy-free deployment following [this guide](https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free)
2. Try to ping kubernetes nodes, ping fails

If I set `kube-proxy-replacement: disabled` in the cilium-config then the nodes ping again, but pod to pod traffic is dropped since cube-proxy isn't running in the cluster. 

[Slack thread](https://cilium.slack.com/archives/C1MATJ5U5/p1591027432067800) with initial troubleshooting

Attached is a pcap during ping attempts
[ping.pcap.zip](https://github.com/cilium/cilium/files/4713291/ping.pcap.zip)

**Comment by borkmann** [comment]
Hello @nicolerenee, I'm currently getting back on this issue now that 1.8 went out. I've tried to reproduce the issue locally, but I'm able to ping nodes under `kube-proxy-replacement: strict`. Did you reproduce this also with 1.8.1?

The pcap is from the host namespace of one node doing the ping to the other node's IP, right? How does it look on the other node's side? Did the icmp packet even arrive there (what does tcpdump say)?

Also, anything from `cilium metrics list | grep drop` side that is increasing counters while running the failing icmp probes? What is the output of `cilium monitor` on the receiving node?

Would be good to have some more debugging info to reproduce the issue.

**Comment by nicolerenee** [comment]
Hey @borkmann, I'm not sure this is a cilium problem after this weekend. I was doing some testing and the exact same setup script on a VM cluster works just fine. I'm now convinced that this is specific to my LACP bonded connection using mellanox connectx-3 adapters. I'm not 100% sure how to test it and dig into it though.

**Comment by borkmann** [comment]
> Hey @borkmann, I'm not sure this is a cilium problem after this weekend. I was doing some testing and the exact same setup script on a VM cluster works just fine. I'm now convinced that this is specific to my LACP bonded connection using mellanox connectx-3 adapters. I'm not 100% sure how to test it and dig into it though.

Ok, is it possible to break up the bond and just use a single mlx4 netdev for checking?

Also might be interesting to check at both node A and node B's bond & phys dev whether the icmp packet goes out the box and even makes it to the other end.

**Comment by nicolerenee** [comment]
I have updated to 1.8.1 and it looks like I'm having issues with traffic all around now. Services are not responding 100% through the ingress controller, especially if the pod is on a node that isn't the same node as the ingress controller is on. 

It looks like I was mistaken when I said it wasn't an issue when running with kube-proxy. It is present in both configurations, it's just after making the change things will start working completely normal for a brief minute before starting to have an issue again. I have verified that the ping packets are leaving node A and arriving at node B but still being dropped.

Also to clarify this is not only impacting ping packets. It seems to impact all services on the node itself. Meaning talking to the kube apiserver stops working at times, ssh connections will get dropped, and so on. 

I have reconfigured two of the nodes to no longer use a bond and the issue is still present.  I don't know if there is a driver besides mlx4 that I am able to use, but I may be able to get the datacenter to go out and wire some ethernet from the onboard nics to a switch for me to let me test some stuff that way as well.

These nodes have absolutely no problems running with any other CNI provider and I've ran them through some hardware tests, so it doesn't appear to be a hardware issue.

**Comment by borkmann** [comment]
Thanks a lot for this info, appreciate the help on debugging! With regards to `I have verified that the ping packets are leaving node A and arriving at node B but still being dropped`. Could you provide a sysdump for this node or the output of `cilium metrics list | grep drop` as well as `cilium monitor` when this is occuring?

**Comment by borkmann** [comment]
@nicolerenee Any new debugging data that might help narrowing this issue down?

Also, would you be able to test a custom image?

**Comment by nicolerenee** [comment]
I needed to get the cluster up and running so I have to move back to calico for the time being. But I will pull calico out and put cilium in place again to get this data. Give me a few days. 

Happy to test with any image you'd like also.

**Comment by borkmann** [comment]
Potentially related: https://github.com/cilium/cilium/issues/12854
