### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with vxlan Tests NodePort with sessionAffinity from outside

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11847]
```
/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
Failed waiting for  ipcache entry on k8s1
Expected
    <*errors.errorString | 0xc00047a590>: {
        s: "ipcache entry for  was not found in time: 4m0s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:1115
```
[cd82f5f1_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_NodePort_with_sessionAffinity_from_outside.zip](https://github.com/cilium/cilium/files/4721765/cd82f5f1_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_NodePort_with_sessionAffinity_from_outside.zip)

**Comment by borkmann** [comment]
Closing for now, seems like hasn't been hit in a while. We can reopen if we think it's still current.

**Comment by tklauser** [comment]
Hit this on #14303 targeting `v1.9` branch: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1542/
