### ISSUE TITLE
sysdump utility should include a recent cache of Hubble data

### ISSUE THREAD

**Issue by jedsalazar** [cilium/cilium#11841]
"Proposal"
Now that Hubble is becoming more ubiquitous, it's likely a good time to think about including a recent cache of Hubble data as part of a sysdump. During the assessment of a sysdump, it would be helpful to quickly gauge what traffic is being sent, particularly what is forwarded and dropped as indicated by Hubble. The fidelity of the output doesn't have to be rich, it could be close to what gets pushed to prometheus

This data would be helpful because the alternative to capturing it in a sysdump involves the operator having to live-debug to capture this information per node.

## Proposal

**Is your feature request related to a problem?**
It's related to operator enablement as well as aiding the Isovalent team to quickly diagnose customer issues.

**Describe the solution you'd like**
An inclusion in the sysdump utility that captures recent flows as exported by Hubble to quickly diagnose what traffic is being allowed and dropped, either due to policy or otherwise.

**Comment by jedsalazar** [comment]
Hoping to not lose sight of this request as it will aid in troubleshooting.

**Comment by joestringer** [comment]
There's a couple of possible directions for this:
* Add to bugtool: https://github.com/cilium/cilium/blob/3030ba6420bc857977269ea40984bb3e5e86e046/bugtool/cmd/configuration.go#L42
* Extend the https://github.com/cilium/cilium-sysdump python tool to run the extra commands

The tradeoff here may depend on whether we are trying to run against the whole cluster (eg hubble-relay) vs. local node.

**Comment by joestringer** [comment]
Other relevant slack discussions: How do we choose what information to include? Pulling full L7 flow information may get sensitive.

I think that from debugging perspective if we have allows without full L7 info (but merely the fact it's an L7 flow) and L7 denies with things like HTTP path, that's likely enough to debug datapath-related issues around policy and so on.

**Comment by willdeuschle** [comment]
For my purposes, it would be very helpful to capture the flows written to disk via the `--flow-export` feature of hubble as part of the sysdump. The challenge would be knowing where on disk those are written to (which may need to be passed as an optional flag to the sysdump tool if that is tolerable).

As it stands, I'm going to be wrapping the sysdump command to both take the sysdump and extract those flows from the provided agent IP.

**Comment by joestringer** [comment]
This was implemented some time ago, closing.
