### ISSUE TITLE
CI: K8sFQDNTest BeforeAll failure (ginkgo DNS timeout)

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11848]
```
/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:459
Error obtaining IPs for test: error looking up vagrant-cache.ci.cilium.io: lookup vagrant-cache.ci.cilium.io on 147.75.207.208:53: read udp 147.75.71.195:46575->147.75.207.208:53: i/o timeout
Expected
    <*errors.errorString | 0xc00190a7f0>: {
        s: "Could not get vagrant-cache.ci.cilium.io and jenkins.cilium.io IPs: 30s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/fqdn.go:68
```

[808a676b_K8sFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip](https://github.com/cilium/cilium/files/4721786/808a676b_K8sFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip)

**Comment by pchaigno** [comment]
We probably want retries and/or make these resolutions optional:
https://github.com/cilium/cilium/blob/40b6f58af21aa16925cdd3d11e55951c66810386/test/k8sT/fqdn.go#L49-L68
We already have the IPs hardcoded above and they're quite stable. Probably okay to use if the resolutions fail.

**Comment by jrajahalme** [comment]
hit again: https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-newest-kernel-4.9/734/testReport/junit/Suite-k8s-1/18/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/

**Comment by jrajahalme** [comment]
This is a BeforeAll failure, not a fail in the "multiple specs" test, will edit the title.

**Comment by jrajahalme** [comment]
This is a DNS timeout from ginkgo itself, not subject to the DNS proxy, which is not even set up yet, and would not affect ginkgo anyway.

**Comment by nebril** [comment]
This seems to be resolved, didn't see an occurence in last month.
