### ISSUE TITLE
helm global.eni=true does not set ipam: eni

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11868]
This does not seem correct to me, currently the https://docs.cilium.io/en/latest/gettingstarted/aws-eni/ guide has the option `global.eni` set but the `ipam` is set to `"cluster-pool"`. Is this intended?

```
helm install cilium ./cilium \
  --namespace kube-system \
  --set global.eni=true \
  --set global.egressMasqueradeInterfaces=eth0 \
  --set global.tunnel=disabled \
  --set global.nodeinit.enabled=true
```

**Comment by joestringer** [comment]
Sounds like a bug in the IPAM chart, it should be autoconfigured by `global.eni=true`.

**Comment by christarazi** [comment]
Looking into it. As Joe mentioned, it seems like we just need to set the `ipam` option when the user specifies ENI. This also seems to affect Azure as well.

**Comment by christarazi** [comment]
Taking a closer look, this was recently changed by https://github.com/cilium/cilium/pull/11725. It seems like in that PR, we want to the user to pass the IPAM as well into Helm.

This might just be a disagreement in the docs (probably accidentally forgotten) as you can see the [updated docs](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-eks/?highlight=config.ipam#deploy-cilium) vs. [the docs @aanm pointed out](https://docs.cilium.io/en/latest/gettingstarted/aws-eni/#deploy-cilium).

Can you confirm @tgraf?
