### ISSUE TITLE
Re-add v1beta1 NetworkPolicy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1187]
The transition is very difficult if we don't support  both over a period of time.

**Comment by genbit** [comment]
This might also affect the minkube getting started guide, since it uses kubernetes 1.6.4. Getting this in the logs from the latest cilium image (a2f110e810bec050):
```
time="2017-07-25T22:44:30Z" level=error msg="github.com/cilium/cilium/daemon/k8s_watcher.go:138: Failed to list *v1.NetworkPolicy: the server could not find the requested resource" 
```
