### ISSUE TITLE
How to use cilium_dbg() 

### ISSUE THREAD

**Issue by autumn0207** [cilium/cilium#11885]
## Support

I want to use **cilium_dbg** function to log some info, but I can not get it by **cilium -D monitor**, can you help me?

**Comment by pchaigno** [comment]
Did you try `cilium monitor -v`?

**Comment by joestringer** [comment]
In Cilium v1.7.x or earlier, `cilium monitor -v` should be sufficient when the daemon is run with `--debug` enabled.

/cc @borkmann did we end up creating an agent configuration option in v1.8 to enable datapath debug monitor messages? What is that setting?

**Comment by qmonnet** [comment]
@joestringer Do you mean `cilium config Debug=Enabled` from [this commit](https://github.com/cilium/cilium/commit/ee5e396a9b6c8244b083124c0f00bab3d7a96059)?

**Comment by joestringer** [comment]
@qmonnet I was thinking of a commandline argument which that commit alludes to, but sounds like it was not merged.

So likely one would need to use `cilium config Debug=Enabled`, yes. Thanks for the reference.

If this doesn't work, please file an issue with full set of steps to reproduce the issue.

**Comment by brb** [comment]
> I was thinking of a command-line argument which that commit alludes to, but sounds like it was not merged.

IMO we should add a flag, as setting `cilium config Debug=Enabled` on each node is cumbersome. Also, `cilium config Debug=Enabled` is currently not documented in the Troubleshooting doc.
