### ISSUE TITLE
When Cilium handles K8s Nodeport services, IPTables sees packets that trigger invalid connection tracking state checks

### ISSUE THREAD

**Issue by varunmar** [cilium/cilium#11914]
When Cilium is configured with
  tunnel: disabled
  enable-host-reachable-services: "true"
  enable-external-ips: "true"
  enable-node-port: "true"

AND
an IPTables rule of the form `-m conntrack --ctstate INVALID -j DROP`
exists, then a tcp handshake can not be completed for traffic from an external client addressed to a nodeport service delivered to a node hosting a backend pod.

We believe the sequence of operations that happens is something like this -
1. SYN from client {client_ip, nodeport_service_ip}
2. eth0 bpf hook translates this to {client_ip, pod_ip}, delivers to linux stack for routing since the pod is hosted locally
3. nf_conntrack entry for {client_ip, pod_ip} with initial state UNREPLIED
4. pod sends SYN_ACK with {pod_ip, client_ip}
5. veth bpf hook sees that this is a reply, translates to {nodeport_service_ip, client_ip}
6. nf_conntrack does *not* consider this part of the same flow, so does not transition entry out of UNREPLIED, but instead creates a new entry.
7. SYN_ACK packet makes its way back to the client
8. client sends ACK packet with {client_ip, nodeport_service_ip}
9. eth0 bpf hook translates this to {client_ip, pod_ip} by looking up BPF connection table
10. IPTables sees an ACK packet {client_ip, pod_ip} from client for a connection entry in state UNREPLIED, drops it.

At step 5) the un-dnat is happening at a point in the packet state machine that is different from where the dnat happened.

Is our understanding correct? Is this a known issue with Cilium, and is there a way to configure it to handle all K8s services (nodeport, loadbalancer and clusterip) but to only do the nat translation in one place?

The --ctstate INVALID -j DROP is unfortunately quite common for many users of IPTables (including kube-proxy, which writes this rule). As such, it seems like a very dangerous state to run in.

**Comment by brb** [comment]
Thanks for the issue. The reasoning looks correct: `--ctage INVALID -j DROP` should be responsible for dropping the packets.

We can work around this by getting rid of `NO_REDIRECT`. This would make the request to bypass the stack (step 2.), and thus no netfilter CT entry should be created in your case. The PR is out (https://github.com/cilium/cilium/pull/11557), but it needs some troubleshooting to figure out why the tests were failing.

**Comment by varunmar** [comment]
It looks like we do want the ability to support IPTables even in cases where eBPF is handling the Kubernetes services. Getting rid of NO_REDIRECT would mean that no traffic (even not bound to k8s services) would skip over the netfilter hooks, correct?

An ideal solution would be for the un-dnat to happen at the same point in the linux stack that did the dnat. This probably requires some more state to be maintained in the ct maps though, is there some existing experiment/analysis done already that we can start from?

**Comment by valas** [comment]
We've discussed two possible solutions:
1. Mark NodePort (and similar) packets with an FWMARK. Then insert an IPtables rule to match on this FWMARK and bypass conntrack table (i.e. -A PREROUTING -m mark --mark BYPASS_MARK -j NOTRACK)

2. Keep the current ingress behavior. On egress:
* Extract connection state from conntrack.
* If packet is NodePort, skip "un-DNAT" in bpf_lxc, and mark the packet.
* In bpf_host match packet with the mark, lookup in conntrack, and do "un-DNAT".

(2) Seems to be more solid long-term solution. We could start with simpler (1), but one concern is that it might be hard to upgrade to (1) without node reboot.

**Comment by errordeveloper** [comment]
@valas I assume this on your radar now?

**Comment by valas** [comment]
It's on our radar but we have not made any progress.

I think the last state is as follows:
1. @brb had a prototype
2. Prototype in (1) was not yet discussed/approved by broader set of Cilium decision makers.
3. This feature is very important and is a GA blocker for us because as it stands right now one can't do IPtables conntrack when Cilium runs in kube-proxy free mode.

**Comment by errordeveloper** [comment]
@valas thanks for the update, feel free to bring this up e.g. in sig-datapath meeting.

**Comment by brb** [comment]
The prototype: https://github.com/cilium/cilium/tree/pr/brb/bpf-lxc-no-redirect.

**Comment by brb** [comment]
Considering that  #15354 has been reverted (cc @krishgobinath), reopening the issue.

**Comment by joestringer** [comment]
@brb @valas @varunmar is there activity on this issue? I'm not sure it will make sense to commit this to release-blocker/1.13 unless someone is actively solving the problem and driving it to completion. That said, if this is a plain bug then we can backport such a fix to the latest release at any time.

**Comment by brb** [comment]
@joestringer : @julianwiedmann is working on a proper fix - https://github.com/cilium/cilium/issues/21955

**Comment by aojea** [comment]
has this been fixed by https://github.com/cilium/cilium/issues/21955 ?

**Comment by brb** [comment]
@aojea Yep, it should have been fixed by #21955 for new connections, while for old connections - https://github.com/cilium/cilium/issues/24062 is still open. Anyway, I think it's OK to consider only new connections in this issue, so let's close it as fixed.
