### ISSUE TITLE
Verify correctness of KVStore rate limiter

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11916]
It seems in some occasions the KVStore rate limiter was not working, verify its behavior with a unit test against etcd should be enough.

https://github.com/cilium/cilium/blob/3430980860e68dbb92d7f0faa79a49d09b6e6786/pkg/kvstore/etcd.go#L160-L166

**Comment by JieJhih** [comment]
I can take this. Please assign it to me.

**Comment by aanm** [comment]
Thanks!

**Comment by aanm** [comment]
@JieJhih any update?

**Comment by JieJhih** [comment]
I'm still under survey the code. You could unassign me.

**Comment by aditighag** [comment]
> I'm still under survey the code. You could unassign me.

Sure. Please feel free to take up the issue whenever you are ready.
