### ISSUE TITLE
Kubernetes service is not reachable from same host

### ISSUE THREAD

**Issue by juergenthomann** [cilium/cilium#11921]
## Bug report

**General Information**

- Cilium version: 1.7.3
- Kernel version: 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
- Orchestration system version in use: Kubernetes v1.18.2
- Upload a system dump: I have one, but due to company restrictions I can't upload it to a public place. 

I have a service that has one endpoint in kubernetes and somehow pods on the same node are not able to connect to this service anymore. Pods from other nodes can still connect. A direct connection to the pod behind the service still works. 

Running  `cilium service list` also does not show the service on any node. Deleting the node behind the service seems to solve the problem.

If specific parts of a systemdump can help I will post them here. I should also be able to arrange that I can send the full dump to specific persons.

**How to reproduce the issue**
I can't reproduce the issue, but it appeared on 2 different kubernetes cluster in the last days.

Config options over configmap:
  auto-direct-node-routes: "false"
  bpf-ct-global-any-max: "262144"
  bpf-ct-global-tcp-max: "524288"
  cluster-name: default
  container-runtime: none
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-node-port: "false"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  masquerade: "true"
  monitor-aggregation: medium
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  sidecar-istio-proxy-image: <redacted>
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "false"

**Comment by aanm** [comment]
@juergenthomann can you send privately over slack to myself or martynas? Thanks

**Comment by aanm** [comment]
@juergenthomann This issue is fixed in master and will be part of the 1.7.5 release in the next days. Thanks for reporting the bug.
