### ISSUE TITLE
add monitoring for LB mode 

### ISSUE THREAD

**Issue by jenningsloy318** [cilium/cilium#1192]
Hi All,

Have a requirement  when cilium  runs as LB mode, it can serve a stat page similar as ingress-nginx-controller vts page or traefik admin ui. This page show the upstreams, connections, and other info, we can have a brief concept of the LB agent running status. 

another thing is to  expose metrics of LB mode agent which can be scrapped by prometheus or can save its metircs to influxdb or some other time series  database.

**Comment by tgraf** [comment]
What do you think about including this in the status field of the Kubernetes service resource instead of serving a status page? Pros/cons?

**Comment by jenningsloy318** [comment]
actually I prefer to use standalone status pages separately. I didn't compared two options but from common use cases, it is better to use a separate one.
