### ISSUE TITLE
test: Use world IP closer to test VM

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#11956]
A lot of our end-to-end tests expect to have a working connection to either `1.1.1.1` or `8.8.8.8` (or some other domain name).
```
$ git grep "1\.1\.1\.1" test/ | wc -l
18
$ git grep "8\.8\.8\.8" test/ | wc -l
12
```
These tests sometimes fail despite retries because of connectivity blips. Instead of relying on those IP addresses, we could use something closer to our VM, such as the host IP or an IP on [the mock world network](https://github.com/cilium/cilium/blob/c6e18f934a36bcf0b2ec1d2bcf0a7bf369448c59/test/provision/k8s_install.sh#L426-L429).

This was discussed in the context of the `Tests EntityNone as a deny-all` Runtime test. Maciej commented:
> Using vm ip didn't work for some reason for us in dns tests (I think this was caused by Cilium realizing  that this IP was inside the vm and not applying dns policies for it - not 100% sure about that, I might have mixed some issues here). We could use packet node ip, but this would need to be configurable at top level of ginkgo call, because runtime tests need to be able to be run on local vms too.

- [ ] Create a mock world network in Runtime VM.
- [ ] Switch tests that can use the mock world network (or use host IP for all).
- [ ] Switch tests that need the host IP.
- [ ] Figure out a way to have a world HTTP server for tests that rely on http://1.1.1.1.

**Comment by Frankkkkk** [comment]
Shall I add that maybe it would be good to use a (dual stack) FQDN instead of an IPv4 because sadly this specific test fails on IPv6-only clusters :-)

**Comment by ti-mo** [comment]
This is still an issue, but we should focus our efforts on addressing this in cilium-cli instead. Closing this in favor of https://github.com/cilium/cilium-cli/issues/1720.
