### ISSUE TITLE
Helm: Implement imagePullSecrets to support private repositories

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#11961]
## Proposal / RFE

Implement support in the Helm charts for imagePullSecrets, a common method used by operators where they define their docker repository login credentials in a Kubernetes secret, and this key provides the name of the secret where this information is stored.

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by youssefazrak** [comment]
@seanmwinn are you actively working on it?
If not, I can take care of this one.
Cheers.

**Comment by sayboras** [comment]
:wave: Thanks for your interest in working on this issue. However, I think it's already done as part of the below PRs, as I can see the attribute imagePullSecrets in the values.yaml file. Feel free to highlight if there is gap in the current implementation.

Related PR: https://github.com/cilium/cilium/pull/13259
Related Code: https://github.com/cilium/cilium/blob/220b2978a9c51f5b52473ff637efdbd17a70db39/install/kubernetes/cilium/values.yaml#L31

**Comment by sayboras** [comment]
Also, feel free to take a look at good-first-issue or help-wanted if there is anything you are interested in.
