### ISSUE TITLE
CI: Fetching command output from pods stuck for 40min

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#11976]
When Cilium fails to start, the log collection spends 40 minutes on `Fetching command output from pods`. This happens in Jenkins CI, locally, and with the new smoke test in GitHub Actions.

The reason is that the log collection keeps trying (10 times) to retrieve information from the Cilium pods and waits for them 4 minutes each time. We should teach it to recognize the Cilium pods are persistently down and we would save ~40 minutes per test. When Cilium is broken for all tests (e.g., BPF compilation error), we often spend 2h40min running just 4 failing tests...

Here is one example for the Smoke test:
https://github.com/cilium/cilium/pull/11969/checks?check_run_id=752762283
[logs_8634.zip](https://github.com/cilium/cilium/files/4750859/logs_8634.zip)

**Comment by Weil0ng** [comment]
I wouldn't mind taking a stab at this if no one is on it :)

**Comment by pchaigno** [comment]
Awesome! I assigned you. As usual, don't hesitate to reach out on Slack or here if you need help/pointers.

**Comment by Weil0ng** [comment]
hmm...so I messed up several bpf progs (bpf_lxc.c, bpf_network.c, bpf_sock.c) and then ran e2e with following cmd

```
ginkgo --focus="K8sServicesTest" --noColor
```

The tests failed in roughly 12min, I actually don't see retries of log collection, am I missing something?

**Comment by pchaigno** [comment]
I think that's because you broke it enough that the preflight check fails :smile: 

I managed to reproduce locally by making the following change.
```diff
diff --git a/test/k8sT/Policies.go b/test/k8sT/Policies.go
index 1dcf64daf..298a3b57d 100644
--- a/test/k8sT/Policies.go
+++ b/test/k8sT/Policies.go
@@ -1186,7 +1186,7 @@ var _ = Describe("K8sPolicyTest", func() {
                                        By("Reconfiguring Cilium to disable remote-node identity")
                                        newCfg := map[string]string{
                                                "global.remoteNodeIdentity": "false",
-                                               "global.hostFirewall":       "false",
+                                               "global.hostFirewall":       "true",
                                        }
                                        for k, v := range daemonCfg {
                                                if _, ok := newCfg[k]; !ok {
```
I then ran:
```shell
$ ginkgo -v --focus="K8sPolicyTest" --focus="validates fromEntities policies with remote-node identity disabled" -- -cilium.testScope="k8s"
#         |                             |                                                                              \--- Required for the second --focus.
#         |                             +--- To run only that test.
#         +--- We all use this because it gives more visibility into what's happening.
#              We should probably make it the default.
```
That diff makes Cilium fatal because the combination of options `remoteNodeIdentity=false` and `hostFirewall=true` isn't currently supported. The test suite then spends 40 minutes from the moment it fails, to the actual end of the test, after the collection of all logs:
```
11:14:36 STEP: Running JustAfterEach block for EntireTestsuite K8sPolicyTest
11:14:37 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
===================== TEST FAILED =====================
11:14:37 STEP: Running AfterFailed block for EntireTestsuite K8sPolicyTest
11:14:37 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
[...]
===================== Exiting AfterFailed =====================
11:54:39 STEP: Running AfterEach for block EntireTestsuite K8sPolicyTest Multi-node policy test
11:54:39 STEP: Cleaning up after the test
[...]
Summarizing 1 Failure:

[Fail] K8sPolicyTest Multi-node policy test validates fromEntities policies with remote-node identity disabled [BeforeEach] Allows from all hosts with cnp fromEntities host policy 
/home/paul/cilium3/test/k8sT/assertionHelpers.go:116

Ran 1 of 398 Specs in 11297.649 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 397 Skipped
--- FAIL: TestTest (11297.65s)
FAIL

Ginkgo ran 1 suite in 3h8m22.271851973s
Test Suite Failed

**Comment by Weil0ng** [comment]
Thanks! This is very helpful! I indeed introduced compilation errors and preflight failed.

While I'm retrying with your example, I'm trying to understand the issue better:

- so if the problem occurs in the log collection phase in AfterFailed(), then prefight fail should also trigger the same issue?
- also I'm looking at the log collection code, it seems like it has a deadline of 10min (https://github.com/cilium/cilium/blob/master/test/helpers/kubectl.go#L2924) instead of 40m? Am I missing something here?

**Comment by pchaigno** [comment]
> so if the problem occurs in the log collection phase in AfterFailed(), then prefight fail should also trigger the same issue?

I don't know why exactly the bugs you injected didn't trigger this issue. I just had noticed that it wasn't happening for all Cilium fails. My intuition here is that maybe the bugs you injected made the tests fail so early that there weren't any corresponding `AfterFailed()` to execute.

> also I'm looking at the log collection code, it seems like it has a deadline of 10min (https://github.com/cilium/cilium/blob/master/test/helpers/kubectl.go#L2924) instead of 40m? Am I missing something here?

I don't know. Maybe the issue is that this context isn't properly passed to called functions for log gathering.
I've noticed that each command to the Cilium pods seems to timeout after 4 minutes (there are 10 such commands, thus the 40min wait), so maybe we overwrite the 10min context with that 4min timeout?
Finding the answers to these questions is probably the key to solving this issue :smile:

**Comment by Weil0ng** [comment]
oki, I think the problem is the following:

- Test failed, calls `CiliumReport()` in `AfterFailed()`
- `CiliumReport()` tries to execute https://github.com/cilium/cilium/blob/master/test/helpers/cons.go#L317 in `reportMapContext()`
- `reportMapContext()` loops over all the cmds and calls ExecInPods(**wait=true**) synchronously, each with a 4min timeout

I'm trying to rerun the test with **wait=false** in that function call to parallelize the cmds, any idea why it was serialized in the first place (aka is there a reason we should not run those in parallel?)

**Comment by pchaigno** [comment]
See my answer in #12547. In short, I'm thinking that maybe we only need to set `wait=true` the first time we call `ExecInPods()`. So we would go from a 40min wait, to a 4min wait when Cilium didn't deploy correctly.
