### ISSUE TITLE
CI: K8sPolicyTest Basic Test checks all kind of Kubernetes policies

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#11975]
Seen in #11951

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:459
failed to ensure the namespace kube-system exists: Process exited with status 1
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.13-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:632
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3180/

[b768e2c1_K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies.zip](https://github.com/cilium/cilium/files/4750607/b768e2c1_K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies.zip)

See https://github.com/cilium/cilium/pull/11951#issuecomment-640961448 for a first analysis.

**Comment by nebril** [comment]
Didn't see this happen in last month, closing.

**Comment by aditighag** [comment]
Hit on the PR - https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3818/

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3818/
