### ISSUE TITLE
Cilium MonitorAggregationLevel=medium still shows kubelet exec session traffic

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#11999]
## Bug report

**General Information**

- 1.7.4
- (`master`) as well
- `Linux ip-192-168-31-155.us-east-2.compute.internal 4.14.177-139.254.amzn2.x86_64 #1 SMP Thu May 7 18:48:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- K8s 1.16 on EKS

**How to reproduce the issue**

1. Follow EKS / ENI instructions
2. Run `cilium monitor`
3. Observe that the output is bombarded with a continuous outpouring of events from the kubelet exec session

**Expected**

The `MonitorAggregationLevel=medium` should aggregate these events

**Comment by pchaigno** [comment]
I don't know what path is not being aggregated here, but it's possible #13485 will fix it.

**Comment by pchaigno** [comment]
I'm unable to reproduce. I've installed Cilium master (pre 1.10 at the time of writing) on EKS by following [our getting started guide](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-eks/#k8s-install-eks). I've run `cilium monitor` on both nodes and I'm not seeing the flood of traces for the kubelet sessions in either.

I'll close. @christarazi please reopen if you still encounter the issue on your side.
