### ISSUE TITLE
Cilium 1.7 upgrade test issues with kube-proxy replacement as strict

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#12018]
See also https://github.com/cilium/cilium/pull/11977#issuecomment-642284897 . Basically if we'd enable kube-proxy-replacement as strict, then upgrade test from 1.7.4 to master breaks on 1.7.4 image. There is v4+v6+debug+strict enabled. Needs fixing on 1.7 side or further investigation whether disabling debugging in BPF datapath gets it back to working state.

**Comment by joestringer** [comment]
The original issue we were looking at was a complexity issue with specific datapath configurations on Cilium v1.7 dev versions, and we have a couple of ideas about how to address those. 

After applying some fixes for the above, we also saw an apiserver connectivity issue that occurs shortly after downgrading to Cilium 1.7 with the corresponding PR. One angle that @borkmann and I discussed was to update the master branch to run this upgrade test from a 1.8-dev version -> 1.8 dev version and evaluate whether the tests with the same CI modifications (disabling kube-proxy) fail in the same manner. This could tell us whether there is an "upgrades cause apiserver connectivity breakage" bug here across v1.7+v1.8, or if there is a v1.7-specific bug when running with kube-proxy-free.

**Comment by borkmann** [comment]
Full explanation here: https://github.com/cilium/cilium/pull/12045/commits/c81e10fe69b59340b993d5b1963007c1ca0a542d

**Comment by pchaigno** [comment]
Could that also explain failures on v1.7 (cf. #11126)? In particular, steps (ii) to (iv). Step (i) fixes a bug I introduced in v1.8 only. If so, we might want to backport.

**Comment by borkmann** [comment]
1.7 not supported anymore, closing.
