### ISSUE TITLE
Monitor test relies on dumping host endpoint debug messages

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12037]
It's not possible to reconfigure host endpoint datapath options because it has reserved labels and we disable it in the API:

```
$ cilium endpoint config 2644 Debug=Enabled
Error: Cannot update endpoint 2644: [PATCH /endpoint/{id}/config][400] patchEndpointIdConfigInvalid 
```

This by itself is fine, but in PR #11977 we disable datapath debug mode by default, which means we can't turn it back on.

Combined with the RuntimeMonitor tests which iterate through *all* endpoints to make sure that debug mode outputs events for all endpoints, this causes a test failure.

**Comment by pchaigno** [comment]
I'm not sure what was the rationale to disallow configuration of endpoints with reserved labels, so went ahead and submitted a PR to allow the following configs only:

Config                    | Default  | Can modify
--------------------------|----------|------------
Conntrack                 | Enabled  |
ConntrackAccounting       | Enabled  |
ConntrackLocal            | Disabled |
Debug                     | Disabled |     x
DebugLB                   | Disabled |     x
DropNotification          | Enabled  |     x
MonitorAggregationLevel   | None     |     x
NAT46                     | Disabled |
PolicyAuditMode           | Disabled |     x
PolicyVerdictNotification | Enabled  |     x
TraceNotification         | Enabled  |     x

PTAL.
