### ISSUE TITLE
CI: RuntimePrivilegedUnitTests: timeout in DNSProxyTestSuite.TestRespondViaCorrectProtocol

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#12042]
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-runtime-Pipeline/451/

```
	 START: proxy_test.go:340: DNSProxyTestSuite.TestRespondViaCorrectProtocol
	 proxy_test.go:364:
	     c.Assert(err, IsNil, Commentf("DNS request from test client failed when it should succeed"))
	 ... value *net.OpError = &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc0005914a0), Addr:(*net.TCPAddr)(0xc0005914d0), Err:(*poll.TimeoutError)(0x2f792a0)} ("read tcp [::1]:56226->[::1]:44421: i/o timeout")
	 ... DNS request from test client failed when it should succeed
```

[18e22c6d_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/4770052/18e22c6d_RuntimePrivilegedUnitTests_Run_Tests.zip)

**Comment by pchaigno** [comment]
Seen again in #12600 even though #12305 was backported to 1.8.
/cc @qmonnet

**Comment by qmonnet** [comment]
If nothing else I can keep increasing the timeout (it was at 1s originally, maybe we should restore it to that value). Looks like raising it to 500ms suppressed a lot of flakes already, maybe we just need to be more patient. I'm not sure why it takes so long though, I never went over 300ms during my tests :/.
