### ISSUE TITLE
Cilium pods in CrashLoopBackOff with EKS GSG on 1.8.0-rc3

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#12078]
When following the [EKS GSG](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-eks) instructions to validate Cilium 1.8.0-rc3 for #11903, the Cilium pods are crash looping with:

```
level=fatal msg="BPF masquerade does not allow to specify devices via --egress-masquerade-interfaces. Use --devices instead." subsys=daemon
```

Complete logs: [cilium-rmkqv-logs.txt](https://github.com/cilium/cilium/files/4781651/cilium-rmkqv-logs.txt)

/cc @brb @tgraf

**Comment by brb** [comment]
Fixed by https://github.com/cilium/cilium/pull/12081.
