### ISSUE TITLE
CI: WaitforPods broken with unknown flag: --field-selector via kubectl describe

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#12072]
Potentially related: https://github.com/cilium/cilium/commit/a15ccd4cbee4529390e966a0c8a1dd06a225438c
```
13:21:20 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3'") => timed out waiting for pods with filter -l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3' to be ready: 4m0s timeout expired
13:21:20 STEP: cmd: kubectl describe pods -n kube-system -l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3'
Exitcode: 1 
Stdout:
Stderr:
 	 Error: unknown flag: --field-selector
	 See 'kubectl describe --help' for usage.
```
Log output from up/downgrade test:
```
13:12:30 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
13:12:35 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
13:12:40 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
13:12:55 STEP: Cilium DaemonSet not ready yet: unable to retrieve daemonset kube-system/cilium: Exitcode: -1 
Stdout:
 	 
Stderr:
 	 
[...]
13:16:40 STEP: Running AfterFailed block for EntireTestsuite K8sUpdates
13:17:20 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3'")
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: -1 
Stdout:
 	 
Stderr:
 	 

Fetching command output from pods []
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-oldest-net-next/800/testReport/junit/Suite-k8s-1/11/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

**Comment by brb** [comment]
This should be harmless, as the `kubectl describe` is invoked only for debug purpose, and was introduced recently by https://github.com/cilium/cilium/commit/c2cc4ebf93a81f21d0f23fb7569b87cce84813bb.

@errordeveloper Is it OK if I change `kubectl describe` to `kubectl get pods -o yaml`?

**Comment by errordeveloper** [comment]
@brb the reason for using 'kubeclt describe' there is to obtain events and therefore revile potential root causes. From what I remember, 'kubectl get pods' doesn't show events. I am sure there is an alternative way of getting events, perhaps 'kubectl get events' ?
