### ISSUE TITLE
Upgrade guide does not guarantee backwards compatibility

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#12079]
The upgrade instructions since 1.6 in the recommended path are causing non-backwards compatible changes to a deployment.

## 1.7 -> 1.8

1. Auto enabling dynamic BPF map sizes
```
+  # Specifies the ratio (0.0-1.0) of total system memory to use for dynamic
+  # sizing of the TCP CT, non-TCP CT, NAT and policy BPF maps.
+  bpf-map-dynamic-size-ratio: "0.03"
```

2. Auto opt into cluster pool IPAM
```
+  k8s-require-ipv4-pod-cidr: "true"
+  ipam: "cluster-pool"
+  cluster-pool-ipv4-cidr: "10.0.0.0/8"
+  synchronize-k8s-nodes: "true"
```
3. Disabling CNP
```
+  disable-cnp-status-updates: "true"
```

## 1.6 -> 1.7

1. Remote node identities
```
+  enable-remote-node-identity: "true"
```

2. Monitor aggregation difference:
```
monitor-aggregation-flags: all
```
vs
```
pkg/option/config.go:   MonitorAggregationFlagsDefault = []string{"syn", "fin", "rst"}
```

## 1.5 -> 1.6

1. Auto opt-in to CRD
2. Change in aggregation
```
-  monitor-aggregation: "none"
+  monitor-aggregation: medium
```
3. Disabling container runtime
```
+  container-runtime: none
```

**Comment by joestringer** [comment]
> `monitor-aggregation`
> `monitor-aggregation-flags`

What's your threshold for backwards compatibility? These options reduced the number of notifications from the BPF datapath to the userspace / monitor but they should not impact forwarding/routing/policy during upgrade or post-upgrade.

**Comment by aanm** [comment]
RFC for this hackity hack https://github.com/cilium/cilium/pull/12080

I also have another branch with a differen proposal which seems the be the "correct" way of solving but I would like Sean's input (on all proposals actually)
https://github.com/cilium/cilium/commit/d9472bc1058ac59e0ffdea488d0e14a34a7a75bd

**Comment by tgraf** [comment]
> What's your threshold for backwards compatibility? These options reduced the number of notifications from the BPF datapath to the userspace / monitor but they should not impact forwarding/routing/policy during upgrade or post-upgrade.

I haven't necessarily classified it much but listed the unintended behavioral changes. I'm not sure we made the conscious decision to change this during upgrades.

**Comment by tgraf** [comment]
This is something that could work:
``` diff
diff --git a/install/kubernetes/cilium/charts/config/templates/configmap.yaml b/install/kubernetes/cilium/charts/config/templates/configmap.yaml
index c1eb5ec2c..63819c8cd 100644
--- a/install/kubernetes/cilium/charts/config/templates/configmap.yaml
+++ b/install/kubernetes/cilium/charts/config/templates/configmap.yaml
@@ -514,6 +514,6 @@ data:
 {{- end }}
 {{- end }}

-{{- if .Values.global.cnpStatusUpdates }}
-  disable-cnp-status-updates: {{ not .Values.global.cnpStatusUpdates.enabled | quote }}
+{{- if or .Values.disableCnpStatusUpdates (not .Values.upgradeCompatibility) }}
+  disable-cnp-status-updates: {{ default true (.Values.disableCnpStatusUpdates) | quote }}
 {{- end }}
diff --git a/install/kubernetes/cilium/charts/config/values.yaml b/install/kubernetes/cilium/charts/config/values.yaml
index 806f198c1..a7099719f 100644
--- a/install/kubernetes/cilium/charts/config/values.yaml
+++ b/install/kubernetes/cilium/charts/config/values.yaml
@@ -7,3 +7,9 @@
 # - azure
 # - crd
 ipam: "cluster-pool"
+
+# disableCnpStatusUpdates disables CiliumNetworkPolicy status updates
+#
+# Default: true (updates disabled)
+#
+#disableCnpStatusUpdates: true
diff --git a/install/kubernetes/cilium/values.yaml b/install/kubernetes/cilium/values.yaml
index 5afa834f8..fa817114b 100644
--- a/install/kubernetes/cilium/values.yaml
+++ b/install/kubernetes/cilium/values.yaml
@@ -568,9 +568,6 @@ global:
   healthChecking:
     enabled: true

-  cnpStatusUpdates:
-    enabled: false
-
   affinity:
     podAntiAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
```

Setting `disableCnpStatusUpdates` either in `values.yaml` or using `--set` will force the value. Otherwise it will default to `true` (to disable CNP) unless `config.upgradeCompatibility` is set.

**Comment by tgraf** [comment]
Developing this further, we could provide version-specific new defaults with something like this:
```
{{- if or .Values.disableCnpStatusUpdates (or (not .Values.upgradeCompatibility) (semverCompare ">=1.8" $upgradeCompatibility)) }}
   disable-cnp-status-updates: {{ default true (.Values.disableCnpStatusUpdates) | quote }}
{{- end }}
```

It is possible but adds considerable complexity

**Comment by errordeveloper** [comment]
Separating breaking vs non-breaking sections is definitely a very good idea. It's a bit unfortunate that Helm templates are the only means of defining this logic right now, but ways of getting past that would involve some new machinery that cannot be brought in for 1.8.
