### ISSUE TITLE
bpf: Fix packet tracing for TO/FROM_NETWORK

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#12084]
`bpf_host` should use `TRACE_{TO,FROM}_NETWORK` on native devices (`{to,from}-netdev`) and `TRACE_{TO,FROM}_HOST` on host devices (`{to,from}-host`). We also need to trace `TRACE_TO_NETWORK` packets on `bpf_network`.

**Comment by Weil0ng** [comment]
I would love take a stab at this if no one else is on it :)

**Comment by pchaigno** [comment]
Assigned to you. See https://cilium.slack.com/archives/C2B917YHE/p1592250031137400 for context.
