### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing and DSR

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#12100]
```
/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
NAT entry was not evicted
Expected command: kubectl exec -n kube-system cilium-z6m6w -- cilium bpf nat list | grep 64000
To have failed, but it was successful:
Exitcode: 0 
Stdout:
 	 TCP IN 192.168.36.11:6443 -> 192.168.36.12:64000 XLATE_DST 192.168.36.12:60978 Created=4464sec HostLocal=1
	 
Stderr:
 	 

/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:1359
```

[6a2ae8e6_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR.zip](https://github.com/cilium/cilium/files/4786746/6a2ae8e6_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR.zip)

https://jenkins.cilium.io/job/Cilium-PR-K8s-oldest-net-next/823/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_and_DSR/

**Comment by pchaigno** [comment]
I hit this again on v1.13:
```
NAT entry was not evicted
Expected command: kubectl exec -n kube-system cilium-lcktw -- cilium bpf nat list | grep 64000
To have failed, but it was successful:
Exitcode: 0 
Stdout:
 	 UDP IN 8.8.4.4:6081 -> 10.0.2.15:64000 XLATE_DST 10.0.1.117:12687 Created=7291sec HostLocal=0
	 UDP OUT 10.0.1.117:12687 -> 8.8.4.4:6081 XLATE_SRC 10.0.2.15:64000 Created=7291sec HostLocal=0
```

Most likely just a cause of a too-general grep. The likelihood of that port being used by some other connections is high enough that it can happen once in a while given the scale of our CI.
