### ISSUE TITLE
Global (anti-)affinity blocks cilium-etcd-operator from deploying on nodes with cilium

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12124]
In v1.8 YAMLs we have introduced this anti-affinity for cilium pods:

https://github.com/cilium/cilium/blob/df97ca1b945a772a2d55ce2157fdb9b9e1d5f0ee/install/kubernetes/cilium/values.yaml#L574-L583

However this applies globally, ie also to the cilium-etcd-operator pods:

https://github.com/cilium/cilium/blob/df97ca1b945a772a2d55ce2157fdb9b9e1d5f0ee/install/kubernetes/cilium/charts/managed-etcd/templates/cilium-etcd-operator-deployment.yaml#L26-L29

This latter piece was introduced to help scheduling cilium-etcd-operator on the same nodes as Cilium in PR #9901.

I don't think this is intended; while attempting to deploy managed etcd cilium for clustermesh testing, I had to manually edit the cilium-etcd-operator deployment to drop this affinity constraint.

**Comment by christarazi** [comment]
I ran into this in https://github.com/cilium/cilium/pull/11906, but since we removed ManagedEtcd tests in 1.8, we didn't hit it...*until now with clustermesh*. @nebril is working on backporting anti-affinity changes

**Comment by joestringer** [comment]
@brb can we either remove the affinity section from the cilium-etcd-operator chart, or switch it to a subchart value instead?

**Comment by brb** [comment]
> This latter piece was introduced to help scheduling cilium-etcd-operator on the same nodes as Cilium in PR #9901.

This was introduced to avoid scheduling cilium-etcd-operator on a node which is not managed by Cilium (i.e. on `k8s3` node in the CI net-next).

The only test which is using etcd is `Etcd` from the `K8sDatapathConfiguration` suite, and it's no longer using the operator. So, I think it's fine to remove the affinity section.

**Comment by brb** [comment]
> I don't think this is intended; while attempting to deploy managed etcd cilium for clustermesh testing, I had to manually edit the cilium-etcd-operator deployment to drop this affinity constraint.

Did you set the global affinity when doing the testing?
