### ISSUE TITLE
CI: Number of ready Cilium pods: 2, Only 2/3 nodes appeared in cilium-health status. nodes = '[k8s1 k8s2 k8s3]'

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#12128]
The test that failed was:
```
Suite-k8s-1.11.K8sDatapathConfig Etcd Check connectivity
```

but it's unlikely specific to that test.

Cilium comes up:
```
23:07:34 STEP: Number of ready Cilium pods: 2
```

and the CI then expects that 3 nodes are reporting a healthy connectivity check:
```
23:07:56 STEP: Cilium is not ready yet: connectivity health is failing: cilium-agent 'cilium-4rfsm': Only 2/3 nodes appeared in cilium-health status. nodes = '[k8s1 k8s2 k8s3]'
```

[2743c254_K8sDatapathConfig_Etcd_Check_connectivity.zip](https://github.com/cilium/cilium/files/4790704/2743c254_K8sDatapathConfig_Etcd_Check_connectivity.zip)

**Comment by tgraf** [comment]
Sysdump reveals:
```
Cluster health:      2/2 reachable   (2020-05-26T14:03:22Z)
  Name               IP              Reachable   Endpoints reachable
  k8s1 (localhost)   192.168.36.11   true        true
  k8s2               192.168.36.12   true        true
```

```
Cluster health:      1/2 reachable   (2020-05-26T14:02:52Z)
  Name               IP              Reachable   Endpoints reachable
  k8s2 (localhost)   192.168.36.12   true        true
  k8s1               192.168.36.11   true        false
```

**Comment by brb** [comment]
@tgraf This could have happened if you have changed `global.synchronizeK8sNodes` helm option (ctx: https://github.com/cilium/cilium/commit/970a25934cb475e8142b7104d1ed3f4acf354546), which is indeed the case in #12097: https://github.com/cilium/cilium/pull/12097/files#diff-de4879a053803424e69022c9c84267cfR508.

**Comment by tgraf** [comment]
@brb Great find!

**Comment by tgraf** [comment]
The flag defaults to `true` so enabling should not be required
```
        flags.Bool(operatorOption.SyncK8sNodes, true, "Synchronize Kubernetes nodes to kvstore and perform CNP GC")
```
