### ISSUE TITLE
Research if autocomplete can be done without requiring to install files

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#1214]
This was a feedback provided by an end-user.  This is particularly important when using cilium with a framework other than kubernetes (e.g., docker, mesos) where policy must be specified via cilium CLI.   

Also relevant for troubleshooting commands, which must be done directly via cilium commands.

**Comment by aanm** [comment]
@danwent auto-complete on which command and environment? We have auto complete.

```
$ cilium policy <TAB> <TAB>
delete    get       import    trace     validate
```

**Comment by tgraf** [comment]
@aanm Do we require to install any files? I assume a user downloaded the binary and did not get auto complete. I know that it works inside the vagrant box. Can we enable this for a pure binary somehow?
