### ISSUE TITLE
EKS guide is not compatible with BPF masquerade

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#12147]
Given that BPF masquerade is the new default, this will break the EKS guide which relies on `--egress-masquerade`

```
level=fatal msg="BPF masquerade does not allow to specify devices via --egress-masquerade-interfaces. Use --devices instead." subsys=daemon
```

**Comment by brb** [comment]
Because of https://github.com/cilium/cilium/pull/12081/commits/4c61216af60c887dea438bf661c44729529717ae the guide is no longer broken.
