### ISSUE TITLE
docs: Hubble relay port-forwarding doesn't work on GKE

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#12152]
Right now we document using the following command:
```
 kubectl -n kube-system port-forward service/hubble-relay 4245:80
```

On GKE the namespace is `cilium`, so this command won't work.

**Comment by Rolinh** [comment]
In the GKE getting started guide, the command is the following:
```
kubectl exec -n $CILIUM_NAMESPACE -t ds/cilium -- hubble observe
```
Where `CILIUM_NAMESPACE` is defined in a previous step (the instructions are made more clear with #12149).

I think that what you are referring to is the instruction on the troubleshooting with Hubble Relay guide. Adding a note about the namespace being different if using GKE may be sufficient I think.

**Comment by errordeveloper** [comment]
@Rolinh yes, I'm indeed referring to troubleshooting guide, don't think it's high priority though, it's something user should be able to figure out.

**Comment by gandro** [comment]
Note that this is not hubble specific. All commands in that document use `kube-system`.
