### ISSUE TITLE
Remote endpoints' identities resolved to WORLD when devices are set and tunneling disabled

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#12205]
@jrajahalme reported that, when `--devices` is configured on GKE, all remote endpoints' security identities are resolved to `WORLD` (2):
```
$ kubectl exec -it cilium-zv68c -n cilium -- cilium monitor | grep -e "10\.52\.14\.148"
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
^C
$ kubectl exec -it cilium-zv68c -n cilium -- cilium bpf policy get 905
DIRECTION   LABELS (source:key[=value])                       PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Ingress     reserved:host                                     ANY          NONE         0       0         
Ingress     k8s:class=spaceship                               80/TCP       18510        0       0         
            k8s:io.cilium.k8s.policy.cluster=default                                                           
            k8s:io.cilium.k8s.policy.serviceaccount=default                                                    
            k8s:io.kubernetes.pod.namespace=default                                                            
            k8s:org=empire                                                                                     
Ingress     k8s:class=spaceship                               80/TCP       18510        0       0         
            k8s:io.cilium.k8s.policy.cluster=default                                                           
            k8s:io.cilium.k8s.policy.serviceaccount=default                                                    
            k8s:io.kubernetes.pod.namespace=default                                                            
            k8s:org=alliance                                                                                   
Egress      reserved:unknown                                  ANY          NONE         0       0 
```

The following dump has some incorrectly auto-detected devices. We already established that the bug still happens when devices are properly detected.
[gke-star-wars-demo.zip](https://github.com/cilium/cilium/files/4804739/gke-star-wars-demo.zip)

/cc @brb

**Comment by pchaigno** [comment]
We couldn't validate that the identity is in the ipcache because the kernel is too old, but we did check that it is in `cilium ip list`. Given that, the lack of debug messages pointing to an ipcache population issue, and the fact that it happens when devices are set, I'm going to assume (for now) that the identity is in the ipcache and something else is happening.

The policy verdict logs above indicate that we are executing this line, in `ipv4_policy()`:
https://github.com/cilium/cilium/blob/1cc79c1fb522043ec8dd899285f9c0ba5cae8e88/bpf/bpf_lxc.c#L903
That function is called after tail calls to `CILIUM_CALL_IPV4_TO_LXC_POLICY_ONLY` and `CILIUM_CALL_IPV4_TO_ENDPOINT`. In the second case, we actually resolve the identity for the source from the ipcache right before calling `ipv4_policy()`. Given my initial assumption and that I don't see anything that could prevent the ipcache lookup, I think we're coming from `CILIUM_CALL_IPV4_TO_LXC_POLICY_ONLY` (in which case the identity is transferred across tail calls via the packet's metadata).

`CILIUM_CALL_IPV4_TO_LXC_POLICY_ONLY` is called from `handle_policy()`:
https://github.com/cilium/cilium/blob/1cc79c1fb522043ec8dd899285f9c0ba5cae8e88/bpf/bpf_lxc.c#L1273-L1274
That tail call program is called from `ipv4_local_delivery()` when delivering packets to a local endpoint (from another endpoint, `bpf_host`, or `bpf_overlay`) while bypassing the stack. The tail call (and "stack bypass") happens when these conditions are met:
https://github.com/cilium/cilium/blob/f5537c26020d5297b70936c6b7d03a1e412a1035/bpf/lib/l3.h#L127-L128
In case of GKE, as can be seen in dump above, the two macros are defined and the tail call happens. One important thing to note is that the security identity is carried across the tail call and therefore determined at the source.

Given the bug happens when devices are set, the next logical place to look at is `bpf_host`. `ipv4_local_delivery()` is called from `handle_ipv4`, called among others on the ingress path from the native device:
https://github.com/cilium/cilium/blob/0fa8ac7f4310206e8ce7ecaf5276d785d5c0464b/bpf/bpf_host.c#L819
`secctx` is carried through one more tail call (`CILIUM_CALL_IPV4_FROM_LXC`) and actually determined by `resolve_srcid_ipv4()`:
(Condensed version)
```c
static __always_inline __u32
resolve_srcid_ipv4(struct __ctx_buff *ctx, __u32 srcid_from_proxy,
		   const bool from_host)
{
	__u32 src_id = WORLD_ID, srcid_from_ipcache = srcid_from_proxy;
	[...]

	if (identity_is_reserved(srcid_from_ipcache)) {
		info = lookup_ip4_remote_endpoint(ip4->saddr);
		if (info != NULL) {
			__u32 sec_label = info->sec_label;
			if (sec_label) {
#ifndef ENABLE_EXTRA_HOST_DEV
				if (from_host && sec_label != HOST_ID)
#endif
					srcid_from_ipcache = sec_label;
			}
		}
	}

	if (from_host)
		src_id = srcid_from_ipcache;
#ifdef ENABLE_SECCTX_FROM_IPCACHE
	else if (!identity_is_reserved(srcid_from_ipcache))
		src_id = srcid_from_ipcache;
#endif

	return src_id;
}
```
In our case, `srcid_from_proxy` likely is `WORLD_ID` (not from proxy). It is therefore reserved and we do the ipcache lookup. We're not in ipvlan mode so both `ENABLE_EXTRA_HOST_DEV` and `ENABLE_SECCTX_FROM_IPCACHE` are undefined. We're not coming from the host, so the resolved ID is assigned to `srcid_from_ipcache`, but that ID is never assigned to `src_id` which is returned with its default value, `WORLD_ID`. *Voilà !*

Now let's see who messed this up. I have a feeling `git blame` is going to point to a @pchaigno...

**Comment by pchaigno** [comment]
André confirmed that we only carry the source ID across nodes if we're in tunneling mode. That's not the case in GKE, so we would have `srcid_from_proxy=WORLD_ID` and the above bug :disappointed:

**Comment by pchaigno** [comment]
The reason we don't have this issue when our kube-proxy replacement is enabled is probably because of this condition: https://github.com/cilium/cilium/blob/72949b4b49d43e6dbb4714929222acb688ce6dd2/bpf/bpf_host.c#L458-L468 which makes us skip the call to `ipv{4,6}_local_delivery` and the transmission of the incorrect source identity. `ENABLE_REDIRECT_FAST` cannot be enable if our kube-proxy replacement is disabled.

**Comment by aanm** [comment]
@pchaigno worth pointing out this is a duplicate of https://github.com/cilium/cilium/issues/8911

**Comment by pchaigno** [comment]
> @pchaigno worth pointing out this is a duplicate of #8911

It is not. Iptables isn't "disabled" here.

**Comment by pchaigno** [comment]
@qmonnet I suspect https://github.com/cilium/cilium/pull/16136 may have fixed this issue by skipping the problematic path (redirect from `bpf_host`). Could you double check? /cc @jibi

**Comment by qmonnet** [comment]
```
$ git diff
diff --git a/test/k8sT/DatapathConfiguration.go b/test/k8sT/DatapathConfiguration.go
index 414522edfd9b..b6ea0ccc3c42 100644
--- a/test/k8sT/DatapathConfiguration.go
+++ b/test/k8sT/DatapathConfiguration.go
@@ -325,7 +325,7 @@ var _ = Describe("K8sDatapathConfig", func() {
 				options["masquerade"] = "false"
 				// This test fails if the hostfw is enabled (and devices specified).
 				// See #12205 for details.
-				options["hostFirewall"] = "false"
+				options["hostFirewall"] = "true"
 			}
 			deploymentManager.DeployCilium(options, DeployCiliumOptionsAndDNS)
 
$ KUBEPROXY=1 KERNEL="49" ginkgo --focus "K8s.*Check connectivity with automatic direct nodes routes"
[...]
Ran 1 of 414 Specs in 272.009 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 413 Skipped
PASS

Ginkgo ran 1 suite in 4m34.24195379s
Test Suite Passed
```

I confirm that the test, modified to run with the `hostFirewall`, passes with Gilberto's PR :tada:.
(I tried before pulling the PR, with an earlier version of Cilium from today, and it was still failing, so this is indeed Gilberto's work that fixed it.)

**Comment by pchaigno** [comment]
@qmonnet Could you send a PR to re-enable the few tests affected by this?

**Comment by qmonnet** [comment]
@pchaigno Yes I will. I believe there are two of them, `Check connectivity with automatic direct nodes routes` and `Check connectivity with transparent encryption and direct routing with bpf_host` - Let me know if you had another one in mind.

**Comment by qmonnet** [comment]
The issue has been solved and the related e2e tests have been re-enabled, I'm closing the issue.
