### ISSUE TITLE
Cilium bugtool / sysdump doesn't gather all route tables in native routing mode

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12250]
When direct routing / native routing mode is enabled, routes are configured in multiple tables but the sysdump doesn't gather the contents of all of these route tables.

**Comment by joestringer** [comment]
We only dump encryption / proxy tables:

```
$ git grep "route show"
bugtool/cmd/configuration.go:           "ip -4 route show table 2005",
bugtool/cmd/configuration.go:           "ip -6 route show table 2005",
bugtool/cmd/configuration.go:           "ip -4 route show table 200",
bugtool/cmd/configuration.go:           "ip -6 route show table 200",
vendor/github.com/vishvananda/netlink/route_linux.go:// Equivalent to: `ip route show`.
vendor/github.com/vishvananda/netlink/route_linux.go:// Equivalent to: `ip route show`.
```

**Comment by christarazi** [comment]
Another useful thing we could have the bugtool pull as well is tables used in `ip rule`. This is useful for modes like ENI and Azure which operate by directing traffic in / out of certain interfaces. 

For example, a node may have rules like:

```
20: from all to 192.1.0.0/16 lookup 3
```

The bugtool could detect that routing table 3 exists and pull it down via:

```
ip -{4|6} route show table 3
```

**Comment by pchaigno** [comment]
Should this issue be moved to https://github.com/cilium/cilium-sysdump/?

**Comment by youssefazrak** [comment]
I'm willing to take this one.
Might ask for help on Slack if needed.

**Comment by youssefazrak** [comment]
@joestringer @christarazi naive thought maybe, but is there a reason to go for specific tables instead of getting the full output with a command like `ip -{4|6} route show table all`?

**Comment by christarazi** [comment]
> route show table all

I did not know that existed, nice! I can't think of a reason why we wouldn't want that. I don't think we care about which tables the rules / routes are from.

**Comment by joestringer** [comment]
I could see a possible reason we might want to know specific tables, if we aren't sure about whether Cilium properly programmed a particular table. Then being able to inspect only that table might make it easier to tell whether something is missing. With the whole route table, it could potentially be fairly large.

That said, I'm not sure at a glance which other tables we might interact with and I think based on the initial PR description and followup post by @christarazi , I think `route show table all` should achieve what we want.

**Comment by joestringer** [comment]
@pchaigno 

> Should this issue be moved to https://github.com/cilium/cilium-sysdump/?

This can be counter-intuitive, but for most of the cilium-sysdump state gathering, it is actually achieved via the bugtool binary that is shipped in the Cilium container. So the logic is in this repository, not in the other repository. cilium/cilium-sysdump mainly holds the co-ordination code, stuff like how to get into different nodes in a k8s environment to be able to get the state from each one.

**Comment by christarazi** [comment]
> I could see a possible reason we might want to know specific tables, if we aren't sure about whether Cilium properly programmed a particular table. Then being able to inspect only that table might make it easier to tell whether something is missing. With the whole route table, it could potentially be fairly large.
> 
> That said, I'm not sure at a glance which other tables we might interact with and I think based on the initial PR description and followup post by @christarazi , I think `route show table all` should achieve what we want.

Good point, we might have a scenario where some rules / routes are conflicting and depending on their table number (priority), one might take effect over another. Having the table number would ease that case.

**Comment by youssefazrak** [comment]
Good, in this case, I will get the specific routes, and probably as @christarazi, get those dynamically.
