### ISSUE TITLE
Cilium bugtool / sysdump should dump all relevant Cilium-managed CRDs like CiliumNode

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#12251]
The tool currently dumps CEPs and CNPs. We should add support for CNs, CiliumIdentities, and CCNP.

This is especially useful for debugging sysdumps from cloud providers like AWS on ENI mode.

**Comment by tklauser** [comment]
Collection of CiliumIdentities and CiliumNodes just got added to `cilium-sysdump` yesterday, see cilium/cilium-sysdump#90.
