### ISSUE TITLE
removing cilium does not completely clean up host files

### ISSUE THREAD

**Issue by zhujik** [cilium/cilium#12260]
/host/etc/cni/net.d/05-cilium.conf is not cleaned up via preStop handler that calls uninstall.sh. This fails over newly scheduled pods.

**General Information**

- Cilium version 1.8.0
- Orchestration system version in use kubectl, helm

**How to reproduce the issue**

1. start e.g. EKS cluster
2. remove aws-node
3. install cilium 
4. schedule some pods
5. remove cilium
6. install aws-node
7. reschedule some pods
8. Pod Sandbox has changed error (cilium-cni could not be found)

**Comment by aanm** [comment]
Hi @zhujik that behavior is intentional. If Cilium removes the `/host/etc/cni/net.d/05-cilium.conf` in the preStop, during an upgrade of Cilium new pods would start to be scheduled for other CNI other than Cilium

**Comment by zhujik** [comment]
@aanm  thank you for your answer. If thats the case, then why is it that after reinstalling aws-node, we get the following error for scheduled pods?

`Warning  FailedCreatePodSandBox  55m                   kubelet, ip-192-168-149-141.eu-central-1.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "8f01b4166accece2453740ead08a5608b64ee92ba1df95a60934c47cee7e27be" network for pod "tiller-deploy-66bd7fd645-8zb6r": NetworkPlugin cni failed to set up pod "tiller-deploy-66bd7fd645-8zb6r_kube-system" network: failed to find plugin "cilium-cni" in path [/opt/cni/bin], failed to clean up sandbox container "8f01b4166accece2453740ead08a5608b64ee92ba1df95a60934c47cee7e27be" network for pod "tiller-deploy-66bd7fd645-8zb6r": NetworkPlugin cni failed to teardown pod "tiller-deploy-66bd7fd645-8zb6r_kube-system" network: failed to find plugin "cilium-cni" in path [/opt/cni/bin]]
  Normal   SandboxChanged          40m (x72 over 55m)    kubelet, ip-192-168-149-141.eu-central-1.compute.internal  Pod sandbox changed, it will be killed and re-created.`

I'm not sure why the pods are trying to find the cilium-cni although it was removed. My guess was that it is referenced in said file.

When I manually remove this file from all nodes (why execing into the aws-node pods), then the pods get scheduled, but no pod can ping any other pod, not even themselves:

`  Warning  Unhealthy               5m44s (x45 over 38m)  kubelet, ip-192-168-149-141.eu-central-1.compute.internal  Readiness probe failed: Get http://192.168.137.205:44135/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff                 49s (x150 over 36m)   kubelet, ip-192-168-149-141.eu-central-1.compute.internal  Back-off restarting failed container`

In our case, after removing cilium, the cluster is virtually broken, because even after re-installing cilium the connectivity issues remain. Do you have any advice?

**Comment by aanm** [comment]
@zhujik try deploying the following file:
```
helm template cilium \
  --namespace=kube-system \
  --set global.cleanState=true \
  --set agent.sleepAfterInit=true \
  --set operator.enabled=false \
  > delete-cilium-from-cluster.yaml
```

after the file is deployed and all nodes are running that Pod, delete the daemonset `kubectl delete -f delete-cilium-from-cluster.yaml` and remove the `/host/etc/cni/net.d/05-cilium.conf` to see if the issue persists.
