### ISSUE TITLE
Improve host policies documentation

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12278]
https://docs.cilium.io/en/v1.8/policy/language/#hostpolicies

Two angles are not covered here:
* Ensuring that host firewall is enabled in either helm / daemon options
* Ensuring that the nodes have the labels for the policy added

**Comment by joestringer** [comment]
I guess this isn't a "getting started guide" so I don't know if it's appropriate to have full-on kubectl commands to show how to get it to work but the above points weren't immediately clear to me when reading the doc.

**Comment by pchaigno** [comment]
I'm planning to cover this in the getting started guide for 1.8.1. Given several users already locked themselves out of their nodes, it might make sense to first set audit mode in the guide (?). I haven't yet tested that for the host firewall though.
