### ISSUE TITLE
Review docs for beta vs. tech preview

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12280]
We currently have some docs that refer to features in "beta" status and some that refer to "tech preview".

We should review our approach to communicating "beta" vs "tech preview" and the kinds of guarantees that we provide for these features, the kind of criteria we are looking for to move features out of these statuses. Then make the various parts of the docs consistent with this.

**Comment by pchaigno** [comment]
This is now fixed AFAIK. We only have beta and a dedicated `.rst`
 file.
