### ISSUE TITLE
[v1.8.0] Support MSI authentication for Azure deployments

### ISSUE THREAD

**Issue by EPinci** [cilium/cilium#12297]
## Proposal / RFE

Most recent Azure AKS deployments relay on Managed Identities (https://docs.microsoft.com/en-us/azure/aks/use-managed-identity).
Current deployment method for v1.8.0 requires an SPN and, as much as it can be made to work, it deviates from that design.
SPNs might also require AAD permissions that infrastructure teams usually do not have and can be avoided with MSI deployments.

This is a feature request to support MSI authentication for Azure IPAM integration.

Thank you.

**Comment by ungureanuvladvictor** [comment]
Hey @EPinci, thank you for filing this FR. I'll give it a look and see which changes we would have to support.

**Comment by ungureanuvladvictor** [comment]
@EPinci I took a look at the code and here where the authorizer for the Azure client gets created: https://github.com/cilium/cilium/blob/master/pkg/azure/api/api.go#L74-L81

We try 2 diff auth modes:
- creating an authorizer from a file which checks client credentials and then client certificates
- creating an authorizer from the environment which checks client credentials, client certificates, username password and then in the end MSI

How are you trying to run Cilium? Are you following the instructions from the official docs? I think what you can do is do not specify the `clientID` + `clientSecret` and we should fallback to MSI auth.

We ran internally the operator on MSI auth when developing this.

**Comment by EPinci** [comment]
@ungureanuvladvictor, thank you for getting back to me.

I gave this a spin following https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-azure/
Got cilium deployed but it's failing to connect to azure so question is, how is failing back to MSI?
Does it use the native kubelet identity or it expects me to bind a pod identity?

```
level=info msg="Cilium Operator 1.8.0 f455c7e69 2020-06-22T16:14:29+02:00 go version go1.14.4 linux/amd64" subsys=cilium-operator-azure
level=info msg="Establishing connection to apiserver" host="https://10.0.0.1:443" subsys=k8s
level=info msg="Starting apiserver on address 127.0.0.1:9234" subsys=cilium-operator-azure
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Unable to retrieve EndpointSlices for default/kubernetes. Disabling EndpointSlices" error="the server could not find the requested resource (get endpointslices.discovery.k8s.io kubernetes)" subsys=k8s
level=info msg="Unable to retrieve EndpointSlices for default/kubernetes. Disabling EndpointSlices" error="the server could not find the requested resource (get endpointslices.discovery.k8s.io kubernetes)" subsys=k8s
level=info msg="Starting Azure IP allocator..." subsys=ipam-allocator-azure
level=warning msg="Unable to synchronize Azure virtualnetworks list" error="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/4d3ee0e9-08d0-43b9-95f3-2df210acfbb0/providers/Microsoft.Network/virtualNetworks?api-version=2019-09-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}" subsys=azure
level=fatal msg="Unable to start azure allocator" error="Initial synchronization with instances API failed" subsys=cilium-operator-azure
```

**Comment by ungureanuvladvictor** [comment]
I'll give it a spin this week. As for your question it should rely on the Azure metadata endpoint to exchange creds.

In our env we always relied on the existence of the config file on disk and the authorizer got created from that one, maybe there is a bug here somewhere.

**Comment by ungureanuvladvictor** [comment]
@EPinci did some more investigation here -- what I suspect is happening is that the managed identity gets assigned to just the k8s control plane (apiserve, scheduler and controller-manager) but not to the worker nodes (where cilium runs).

I created an aks cluster with the `--enable-managed-identity` flag passed to the `az aks create` command. After the cluster was done creating I checked the VMSS created and that one did not have the system identity flag turned to on.

Do you mind checking on your end the above? That said I also tried the vanilla cilium installation and I can confirm that once I turned on the managed system identity on my aks VMSS and gave owner perms over my subscription the operator started working:
```
level=info msg="Synchronized Azure IPAM information" numInstances=3 numSubnets=1 numVirtualNetworks=1 subsys=azure
```

Let me know if this makes sense.

**Comment by ungureanuvladvictor** [comment]
@EPinci did you get a chance to look at my previous comment ?

**Comment by EPinci** [comment]
@ungureanuvladvictor, apologies, I had health issues and couldn't followup.

I checked your comment and my test cluster has, indeed, been created with `--enable-managed-identity`.
The system identity is not enabled and, IMHO, shouldn't be enabled due to the multiple user identities assigned by default.
I think that the design, in here, should be to have a dedicated user identity as all the other services (OMS, policy...) are getting. Also everything that runs in the node should use the kubelet user identity (the one that is used for registry pulls, as an example).
What do you think?

Also, owner permissions on sub are not doable for us, what is the minimum permission to assign and to what resource?

Thank you!

**Comment by ungureanuvladvictor** [comment]
Thank you for the detailed response @EPinci. From what I can see Cilium is handling the retrieval of credentials as expected (either by a user supplying them or Cilium getting them via IMS).

The question boils more down to what scoped permissions are needed for the `cilium-operator` to work as expected, right? As to how those credentials are supplied to the `cilium-operator` it is up to the manager of the cluster to decide that. What I think is currently missing in the `cilium-operator` is the option to specify if it should use the system identity or the user identity (and in the case of user identity which is the name of it).

I'll take a stab at documenting what perms the `cilium-operator` needs in the subscription and get back to you on that.

**Comment by ungureanuvladvictor** [comment]
@EPinci I think the following are the scoped perms you need to provide to the `cilium-operator` in order to work as expected:
```
# VMSS
Microsoft.Compute/virtualMachineScaleSets/read

# VMSSVM
Microsoft.Compute/virtualMachineScaleSets/virtualMachines/read
Microsoft.Compute/virtualMachineScaleSets/virtualMachines/write

# VNET
Microsoft.Network/virtualNetworks/read

# NetworkInterfaces
Microsoft.Network/networkInterfaces/read
Microsoft.Network/networkInterfaces/write
```

They should be provided on the resource group that hosts the VMSS, VMSS VMs and the VNET. Also if you are deploying self managed nodes you need to give those perms on the RG which hosts those nodes.

I did not test these perms in an EKS cluster -- extracted them by looking at the API interactions we are doing and correlated them via https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations.

**Comment by ungureanuvladvictor** [comment]
@bpineau I know you are running Cilium on AKS + self managed nodes. What perms are you giving to the `cilium-operator` when deploying it?

**Comment by EPinci** [comment]
@ungureanuvladvictor I see, these permissions sound reasonable to me: they probably map to a simplified `Network contributor` to the vnet (likely unique) and `VM Contributor` to the MC_ resource group (to catch all nodepool's VMSSes).

Any idea about selecting a specific UMI for the `cilium-operator`?

Thank you!

**Comment by EPinci** [comment]
@ungureanuvladvictor Are there any updates on this?

**Comment by ungureanuvladvictor** [comment]
@EPinci I just rebased https://github.com/cilium/cilium/pull/12592. Will try to get it merged in the next week. That should allow you specifying a UMI to the operator as a command line flag when it starts.

**Comment by bpineau** [comment]
@ungureanuvladvictor sorry I missed the notification. I don't use AKS (but rather self managed k8s), and grant Cilium operator Contributor rights on a dedicated per cluster network resource group. Agents have https://kubernetes-sigs.github.io/cloud-provider-azure/topics/azure-permissions/ already + `Microsoft.Network/virtualNetworks/subnets/join/action`.

**Comment by ungureanuvladvictor** [comment]
@bpineau no prob, I was able to update the Cilium docs with what I needed.

@EPinci the user managed identity work merged into the master branch of Cilium, give it a try when you get a chance.

I'll close this issue in a weeks time if no movement on it until then.

**Comment by r3mattia** [comment]
Is any further clarification added on the permissions required in this case? I am currently encountering the same issue as @EPinci. I was also able to deploy using a SP with no issue.

In this case, I have created a new UMI, and assigned:
- vNet reader scoped on the vNet used by AKS
- vNet contributor scoped on the vNet used by AKS (same as above)
- VM contributor scoped on the the resource group used by AKS

However, I still get the same issue:

```
level=warning msg="Unable to discover API groups and resources" error="unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request" subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumIdentity/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumExternalWorkload/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumLocalRedirectPolicy/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNode/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumEndpoint/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumClusterwideNetworkPolicy/v2 subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="attempting to acquire leader lease  kube-system/cilium-operator-resource-lock..." subsys=klog
level=info msg="Leader re-election complete" newLeader=aks-nodepool-22448961-vmss000000-ChfEqzgqrF operatorID=aks-nodepool-22448961-vmss000001-bpgbRlNlRz subsys=cilium-operator-azure
level=info msg="successfully acquired lease kube-system/cilium-operator-resource-lock" subsys=klog
level=info msg="Leading the operator HA deployment" subsys=cilium-operator-azure
level=info msg="Initializing IPAM" mode=azure subsys=cilium-operator-azure
level=info msg="Starting Azure IP allocator..." subsys=ipam-allocator-azure
level=warning msg="Unable to synchronize Azure virtualnetworks list" error="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/48e27386-2f08-41ff-b80a-64bc3bbb028a/providers/Microsoft.Network/virtualNetworks?api-version=2019-09-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}" subsys=azure
level=fatal msg="Unable to start azure allocator" error="Initial synchronization with instances API failed" subsys=cilium-operator-azure
```

It should also be noted that I get this warning:
```
level=warning msg="Unable to discover API groups and resources" error="unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request" subsys=k8s
```

I am not sure if it is useful, but added for completeness.

**Comment by jelisejev** [comment]
Having the same problem as well. I've created a managed identity with Contributor and Managed Identity Operator permissions to the subscriptions and put its ID into userAssignedIdentityID. Also tried not specifying the userAssignedIdentityID in hopes that it will pick up the correct identity itself, but that did not work.

**Comment by ombre9** [comment]
@r3mattia Your problem is this this:
`level=warning msg="Unable to synchronize Azure virtualnetworks list" error="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<>/providers/Microsoft.Network/virtualNetworks?api-version=2019-09-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"}" subsys=azure` Note the **_Identity not found_** part.

Make sure you use the clientId of your UMI and it is attached to the vmss.
