### ISSUE TITLE
Investigate reports of connectivity outage during upgrade

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12308]
Recently a few users have reported that connectivity may be disrupted during upgrade.

The Cilium upgrade documentation specifies that there should be "minimal to none" disruption to connectivity during upgrade, unless L7 policy is in place. If L7 policy is in place (HTTP, DNS, etc.) then during the Cilium pod restart, connections routed via the proxy will be disrupted. In the case of HTTP, this is the data connection. In the case of DNS, this is only the DNS request/response; access via an FQDN should not be affected. In the event of L7 connection disruption due to proxy restart, applications are expected to reconnect to re-establish connectivity.

https://docs.cilium.io/en/v1.8/install/upgrade/#version-specific-notes

Factors that may impact upgrade:
* Kernel version
* K8s version
* Specific Cilium versions being upgraded from/to
* Cilium configuration. In particular, `--tunnel` mode (enabled / direct-routing).
* Cilium configuration as it relates to managed providers, eg. GKE / EKS / AKS modes.
* Whether the traffic under test is forwarded via a service or directly to the backend pod
* Whether the traffic is subject to no policy, L3 policy or L7 policy
* Possibly more, if you notice another factor please edit this list and comment below to highlight the addition.

Currently there are upgrade tests in the tree, but I don't know how comprehensively they evaluate connectivity breakage during upgrade. There is certainly an attempt but it may not be covering all of the mentioned factors.

In the past we had used the deployments from the following repo to assist troubleshooting:

https://github.com/cilium/chaos-monkeys

Suggested path:
* [ ] Pick an environment and define the factors above fully, including helm install configuration.
  * The monkeys will come with specific network policies so that aspect is dependent on the individual monkey.
* [ ] Deploy the latest Cilium v1.7 release with the chaos monkey scripts.
  * Note, it may take some reading / investigation to understand which monkeys are appropriate for upgrade testing and what kind of churn they may add to the cluster.
* [ ] For a sanity check, establish that:
  * [ ] The monkeys are stable in a stable cluster for 5-10 mins.
  * [ ] Whether restarting the agent (eg `kubectl delete pods -l k8s-app=cilium`) causes any monkeys to crash / complain.
  * [ ] If some monkeys are unstable, take note which ones so we can investigate further whether it is (a) a script issue or (b) a Cilium issue; remove those from the pool so that we get reliable feedback.
* [ ] Perform the upgrade by following the Cilium 1.8 documentation.
* [ ] Observe chaos monkey failures and take note.
* [ ] Evaluate reproducibility of any monkey failures.

There was one area where the monkeys were known to alarm on false positives, which is when they made too many DNS requests and were subject to cloud ratelimiting.

**Comment by joestringer** [comment]
It may turn out that the basic connectivity-check.yaml is enough for some basic validation before using the monkeys. That could be a useful step to start with to establish a baseline; the monkey scripts may end up going a bit further in specific areas.

**Comment by joestringer** [comment]
FWIW I followed the above steps for 1.8 and 1.8 -> 1.9.0-rc3 and identified one stability issue in the agent, no sign of connectivity loss when following the upgrade guide correctly.

**Comment by brb** [comment]
I've recently improved migrate-svc-test (https://github.com/cilium/migrate-svc-test/commit/edc628b2df7bd1002d3499c7f65df8c0396502ff) which is used by the `k8sT/Updates.go` to catch interrupted connections. As pointed by @kAworu , the test started to fail in https://github.com/cilium/cilium/pull/14059: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.11-net-next/1475/testReport/Suite-k8s-1/11/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/ and https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.19/45/testReport/Suite-k8s-1/17/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/.

**Comment by joestringer** [comment]
Possibly related: https://github.com/cilium/cilium/pull/13032

I say this because as far as I can tell, the tail calls map was not resized between v1.8.5..v1.9.0, but it *was* resized between v1.7.11..v1.8.5.

**Comment by joestringer** [comment]
@pchaigno do you think it's worth leaving this open? The outline can be used for investigating suspicions of upgrade connectivity issues, but I don't think that anything is going to happen with it if we just leave it unassigned but open.

I also note that community members have recently proposed fixes for upgrade connectivity outages as part of the v1.11 dev cycle, so I expect that the community is testing this broadly and proposing improvements over time.

**Comment by pchaigno** [comment]
I agree we should close it. As you said, we've had a few fixes to upgrades/restarts recently and have other issues and pull requests to track additional fixes and test improvements.
