### ISSUE TITLE
tcpdump cannot see packet dropped by tc ?

### ISSUE THREAD

**Issue by thomasdba** [cilium/cilium#12312]
If packet is dropped at tc , tcpdump should see it before it is dropped ,rt ? But I tested many times , not as expected .
Pls correct me if there is any misunderstanding .
Thanks !

**Comment by pchaigno** [comment]
Depending on your configuration and the origin & destination of packets, Cilium may bypass parts of the stack to improve performance. For this reason, packets may not appear in tcpdump's output for all interfaces.

To see packets dropped by Cilium's datapath, you can instead use `cilium monitor -t drop` from one of the Cilium pods.

**Comment by thomasdba** [comment]
> Depending on your configuration and the origin & destination of packets, Cilium may bypass parts of the stack to improve performance. For this reason, packets may not appear in tcpdump's output for all interfaces.
> 
> To see packets dropped by Cilium's datapath, you can instead use `cilium monitor -t drop` from one of the Cilium pods.

thanks pchaigno !
Yes ,cilium monitor -t drop works , but I guess packets were dropped by tc filter ,then do some experiments to verify .
As you said ,they may bypass the stack ,then the tc bpf filter is not used to filter ? 
My test case is pod A @ nodeA, pod B @ node B ,pod A access Pod B through vxlan ,I can find the packet at cilium_vxlan @ node B, but cannot see it on Pod B's veth interface ,so the packet was dropped after cilium_vxlan but before it got to Pod B's veth interface ?
cilium monitor is easy to use , but is there any tools like bpftools to learn more details ?

**Comment by qmonnet** [comment]
The tc filter _is_ used to filter packets, but if they are dropped they may never reach the socket layer where tcpdump would be able to capture them.

Bpftool won't help much to see packets, it's more about inspecting eBPF objects (programs and maps, typically). You could use it to inspect the contents of the maps, but I will be raw data and won't be easy to read. I would recommend the different `cilium bpf` or `cilium map` commands instead.

To get more details about what happens in the datapath itself, have you tried the _verbose_ (`-v`) option for `cilium monitor`? ([Related documentation](https://docs.cilium.io/en/v1.8/contributing/development/dev_setup/#datapath-code))

**Comment by thomasdba** [comment]
thanks qmonnet!  tcpdump should capture them at NIC level ,rt ?

**Comment by qmonnet** [comment]
No, tcpdump captures the traffic from raw sockets, after the packets have passed through most of the Linux stack. If you wanted to hook at the driver level, this is something you could do with an XDP filter. There are various tools that may help do that ([xdp-dump](https://github.com/xdp-project/xdp-tools/tree/master/xdp-dump), [another xdpdump](https://github.com/Netronome/bpf-samples/tree/master/xdpdump), [yet another xdpdump](https://github.com/facebookincubator/katran/tree/master/tools/xdpdump), [xdpcap](https://github.com/cloudflare/xdpcap)). I have not tried them with Cilium, I usually find `cilium monitor` to be better suited to understand what happens on the datapath, but you're free to experiment, of course :).

**Comment by thomasdba** [comment]
thank you so much ! Will do some test .

**Comment by thomasdba** [comment]
In this blog , seems tcpdump is very close NIC ,between NIC and TC.
![image](https://user-images.githubusercontent.com/39427522/86243953-cd9ae800-bbd9-11ea-966b-85a5e05dcef5.png)
https://medium.com/criteo-labs/demystification-of-tc-de3dfe4067c2

**Comment by pchaigno** [comment]
For packets coming from the tunnel, we may also bypass parts of the stack and deliver packets directly to their destination (e.g., host device or pods). In that case you will not see the packets in tcpdump. As @qmonnet said, `cilium monitor` and `cilium monitor -vv` are the tools to use here.

Could you describe what you are trying to do and why you think the packet drops are unexpected?

**Comment by thomasdba** [comment]
@pchaigno I just want to understand how cilium works ,as I didn't find it from Doc , so I want to some test ...
Anyway thank you all .

**Comment by qmonnet** [comment]
If you haven't already, you may want to look at the [eBPF datapath](https://docs.cilium.io/en/v1.8/concepts/ebpf/) section of the documentation.
