### ISSUE TITLE
PodSecurityPolicy does not allow hostPort for Prometheus 

### ISSUE THREAD

**Issue by alex1989hu** [cilium/cilium#12324]
## Bug report

**General Information**
PodSecurityPolicy does not enable `hostPort` if Prometheus is enabled, `cilium` daemonset and `cilium-operator` deployment is affected.
- Cilium version (run `cilium version`): 1.8.0
- Kernel version (run `uname -a`): 5.5.15-talos
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): 1.18.0
- Link to relevant artifacts (policies, deployments scripts, ...):
  - https://github.com/cilium/cilium/blob/v1.8.0/install/kubernetes/cilium/charts/agent/templates/podsecuritypolicy.yaml
    - https://github.com/cilium/cilium/blob/v1.8.0/install/kubernetes/cilium/charts/agent/templates/daemonset.yaml#L181
    - https://github.com/cilium/cilium/blob/v1.8.0/install/kubernetes/cilium/charts/agent/templates/daemonset.yaml#L187
  - https://github.com/cilium/cilium/blob/v1.8.0/install/kubernetes/cilium/charts/operator/templates/podsecuritypolicy.yaml
    - https://github.com/cilium/cilium/blob/v1.8.0/install/kubernetes/cilium/charts/operator/templates/deployment.yaml#L130
- Generate and upload a system zip:
```
N/A
```

**How to reproduce the issue**

1. Deploy Ciliium Helm Chart `v1.8.0` with `--set global.psp.enabled=true --set global.prometheus.enabled=true --set global.hubble.enabled=true --set global.hubble.serviceMonitor.enabled=true`
2. Check Kubernetes events

```
Warning   FailedCreate                   daemonset/cilium                       Error creating: pods "cilium-" is forbidden: unable to validate against any pod security policy: [spec.containers[0].hostPort: Invalid value: 9090: Host port 9090 is not allowed to be used. Allowed ports: [] spec.containers[0].hostPort: Invalid value: 9091: Host port 9091 is not allowed to be used. Allowed ports: []]
```

```
Warning   FailedCreate                   replicaset/cilium-operator-59c749c5b   Error creating: pods "cilium-operator-59c749c5b-" is forbidden: unable to validate against any pod security policy: [spec.containers[0].hostPort: Invalid value: 6942: Host port 6942 is not allowed to be used. Allowed ports: []]
```

**Comment by alex1989hu** [comment]
Is it necessary to have `hostPort` for `Prometheus`?

**Comment by aanm** [comment]
@alex1989hu thanks for opening the issue. You are correct. There's a PR that will fix the issue https://github.com/cilium/cilium/pull/12175 but we are currently working on https://github.com/cilium/cilium/pull/11140 first to test it against our CI.


> Is it necessary to have `hostPort` for `Prometheus`?

I think this might be an oversight from our side. Once the PSP are fixed we will study the removal of the `hostPort` for `Prometheus` (which I believe it's not necessary)

**Comment by aanm** [comment]
@alex1989hu PodSecurityPolicy will be removed from Kubernetes https://github.com/kubernetes/kubernetes/pull/90603 so we will remove its support in Cilium as well. Feel free to open a new GH issue if you see other isses.

> Is it necessary to have `hostPort` for `Prometheus`?

Regarding this, I have noticed that `hostPort` is automatically added for all container ports of pods that are running in host network.
