### ISSUE TITLE
Document how to wildcard labels in identity logic

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12329]
Add documentation with the specific steps / syntax for how the `--labels` option can be configured.

**Comment by pchaigno** [comment]
Isn't this covered by https://docs.cilium.io/en/latest/operations/performance/scalability/identity-relevant-labels/ already?

**Comment by joestringer** [comment]
Thanks, yes, looks like it was addressed now. The docs there look pretty clear to me about how the configuration should look in the actual config. Let's close this out :tada:
