### ISSUE TITLE
cilium-operator high availability

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12330]

**Comment by fristonio** [comment]
@joestringer Is it something related to `leaderelection` pkg provided by Kubernetes to run multiple instances of the operator?
https://github.com/kubernetes/client-go/blob/master/examples/leader-election/main.go#L122

**Comment by tgraf** [comment]
@fristonio Yes, using exactly that pattern.

**Comment by fristonio** [comment]
Great, I can help with this if anyone is not working on it.
