### ISSUE TITLE
failed endpoint restore after OOM

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#12367]
## Bug report

**General Information**

- Cilium 1.7.5
- kernel 4.15

**How to reproduce the issue**

1. Issue appears when Cilium was restarted due to OOM.  

2. Restore failed for single endpoint with " "Unable to parse the C header file" endpointID=625 error="invalid format \"\". Should contain a single ':'" file-path=/var/run/cilium/state/625/lxc_config.h subsys=endpoint" 

3.  It seems like the OOM may have happened while the FQDN GC was happening.  The last log message is: " "FQDN garbage collector work deleted 12 name entries" controller=dns-garbage-collector-job subsys=daemon"

**Comment by aanm** [comment]
Wasn't this fixed by https://github.com/cilium/cilium/pull/12218?

**Comment by joestringer** [comment]
@aanm do you think this was a concurrent userspace write to the same file or do you think it's possible Cilium was terminated mid-write of the file?

My initial thought is that the intent would be to for the periodic `lxc_config.h` write to write to a *new* file, then atomically replace the existing `lxc_config.h` with the new one to ensure that there is no situation where a prematurely terminated Cilium run could leave a corrupted `lxc_config.h` file on the filesystem.

I know we do this from the datapath preparation side but I haven't vetted the periodic FQDN write path to confirm this holds there too.

**Comment by aanm** [comment]
@joestringer ah, I thought this was because of the OOM itself. You are right, yeah, the FQDN controller should, it doesn't currently, create a new file, write contents and only after do a `mv new_lxc_config.h lxc_config.h`.

**Comment by aanm** [comment]
Fixed by https://github.com/cilium/cilium/pull/12380

**Comment by joestringer** [comment]
Dropped backport labels as it looks like the PR was already backported; refer to the related PR #12380 for more details.
