### ISSUE TITLE
Mention usage of CLI kernel-check in Docs/System Requirements

### ISSUE THREAD

**Issue by brandshaide** [cilium/cilium#12384]
## Proposal / RFE

As introduced by #11339 it might be a good idea to mention the usage of the CLI in the [System Requirements](https://docs.cilium.io/en/stable/install/system_requirements/) section of our Documentation. 

Idea is to have a infobox mentioning the tool and also pointing out the to the Deployment with a hint to the `nodeSelector`, so the user can use it right away.  Something like that: 

```
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/master/examples/kubernetes/kernel-check/kernel-check.yaml
```

**Comment by sayboras** [comment]
Just a quick question on this, I install kernel check deployment in example file by running `kubectl apply --recursive -f examples/kubernetes/kernel-check/kernel-check.yaml`. 

Output of command seems as per expected, however, the pod just keep restarting. As it's deployment type, control plane will keep scaling it to minimun number (e.g. 1) if I am not wrong.

Not sure if _Deployment_ is the correct one for this case, I am thinking about using _Job_ insteadly. What do you have in mind ?

```sample output
Events:
  Type     Reason     Age                     From                  Message
  ----     ------     ----                    ----                  -------
  Normal   Scheduled  7m28s                   default-scheduler     Successfully assigned default/bpf-kernel-check-67776f8888-8mksm to kind-worker
  Normal   Created    6m32s (x4 over 7m24s)   kubelet, kind-worker  Created container cilium
  Normal   Started    6m32s (x4 over 7m24s)   kubelet, kind-worker  Started container cilium
  Normal   Pulling    5m51s (x5 over 7m28s)   kubelet, kind-worker  Pulling image "docker.io/cilium/cilium:latest"
  Normal   Pulled     5m48s (x5 over 7m24s)   kubelet, kind-worker  Successfully pulled image "docker.io/cilium/cilium:latest"
  Warning  BackOff    2m15s (x24 over 7m20s)  kubelet, kind-worker  Back-off restarting failed container
```

**Comment by brandshaide** [comment]
@sayboras thanks for digging into this: I agree with you, `Job` indeed seems to be a better fit for this use-case. I'll change this in a follow-up I'm currently working on.

**Comment by aanm** [comment]
@brandshaide any update on this?

**Comment by brandshaide** [comment]
> @brandshaide any update on this?

just submitted a PR 🙂
