### ISSUE TITLE
Typo in UpdateEC2AdapterLimitViaAPI command line flag

### ISSUE THREAD

**Issue by ungureanuvladvictor** [cilium/cilium#12396]
Currently the `cilium-operator-aws` command line flag is named [`update-ec2-apdater-limit-via-api`](https://github.com/cilium/cilium/blob/76df1345ad49afb48ce5a3e14ee70e99e73113f4/operator/option/config.go#L147-L149) which has a typo in `apdater` (should be `adapter`).

I suspect we should deprecate the old typo'ed flag and introduce a new one. I am not sure what is the official Cilium policy on flag deprecations (@tgraf, @aanm mind sharing some insight here?).

**Comment by tgraf** [comment]
@ungureanuvladvictor Good catch! The standard policy is to:
- Introduce the new correct flag name for 1.9
- Mark the old flag as deprecated in 1.9 to cause a warning
- Mention it in the upgrade guide for 1.9 and ask users to switch to new flag
- Remove the old deprecated flag in version 1.9+2

**Comment by ungureanuvladvictor** [comment]
Sounds good, I'll try to put together something in the next week.
