### ISSUE TITLE
Enable tunneling mode with XDP

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#12429]
Missing feature gap to tc based implementation

**Comment by Danielybl** [comment]
@borkmann is there any update for this feature? Thanks

**Comment by borkmann** [comment]
> @borkmann is there any update for this feature? Thanks

In master branch we have a LB-only mode which has IPIP encap (similar to Katran). For the K8s case, the tunneling is still on our roadmap & tbd.

**Comment by julianwiedmann** [comment]
Should have probably closed this with https://github.com/cilium/cilium/pull/21364. Doing so now.
