### ISSUE TITLE
kube-proxy free snat issue nodeport & loadbalancer backing same pod

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#12424]
potentially stale ct issue, needs investigation
- rev nat entry first of nodeport
- later on load balancer 
- needs doc entry as well into 'limitations'

**Comment by julianwiedmann** [comment]
@borkmann is this still relevant? Looking at the description, I don't think anyone would be able to work on it :grin: .

**Comment by julianwiedmann** [comment]
Closing for now, let's see if it comes back with more context.
