### ISSUE TITLE
Inter-node Endpoint Connectivity failure after installation of Cilium 1.7.4

### ISSUE THREAD

**Issue by anunay-bhatt** [cilium/cilium#12437]
## Support

Hi, 

I am installing Cilium 1.7.4 on an EKS cluster with self-managed nodes. Post installation, the Cilium pods come up alright but pods in one node are unable to communicate with pods in another node (was able to test this with ping/curl). Also cilium-health monitor status shows issues with endpoint connectivity for **all** nodes when trying to reach endpoints in other nodes (see output below for one such node):

  ip-10-100-113-131.us-west-2.compute.internal (localhost):
    Host connectivity to 10.100.113.131:
      ICMP to stack:   OK, RTT=196.286µs
      HTTP to agent:   OK, RTT=200.25µs
    Endpoint connectivity to 10.52.116.180:
      ICMP to stack:   OK, RTT=257.621µs
      HTTP to agent:   OK, RTT=173.494µs
  ip-10-100-110-89.us-west-2.compute.internal:
    Host connectivity to 10.100.110.89:
      ICMP to stack:   OK, RTT=436.8µs
      HTTP to agent:   OK, RTT=490.168µs
    Endpoint connectivity to 10.52.111.111:
      ICMP to stack:   Connection timed out
      HTTP to agent:   **Get http://10.52.111.111:4240/hello: net/http: request canceled while waiting for connection** (Client.Timeout exceeded while awaiting headers)
  ip-10-100-96-250.us-west-2.compute.internal:
    Host connectivity to 10.100.96.250:
      ICMP to stack:   OK, RTT=1.178813ms
      HTTP to agent:   OK, RTT=2.211193ms
    Endpoint connectivity to 10.52.96.43:
      ICMP to stack:   Connection timed out
      HTTP to agent:   **Get http://10.52.96.43:4240/hello: net/http: request canceled while waiting for connection** (Client.Timeout exceeded while awaiting headers)

**EKS cluster has the below config**
1. Kubernetes version 1.1.4
2. 3 self-managed nodes with custom AMIs- AmazonLinux2 image (k8s: 1.14.9, docker:18.09.9ce-2.amzn2)

**Below steps were followed to install Cilium 1.7.4 on the above cluster:**
1. kubectl -n kube-system delete daemonset aws-node

2. Scale down cluster to 0 nodes:
aws autoscaling update-auto-scaling-group --auto-scaling-group-name <group name> --desired-capacity 0 --min-size 0

3. Installed Helm chart for Cilium 1.7.4 on the "kube-system" namespace

4. Scaled up cluster back to 3 nodes:
aws autoscaling update-auto-scaling-group --auto-scaling-group-name <group name> --desired-capacity 3 --min-size 3

Attached below is the cilium system dump for the three nodes:
[cilium-sysdump-20200706-150213.zip](https://github.com/cilium/cilium/files/4881431/cilium-sysdump-20200706-150213.zip)

The exact same steps were working fine on an EKS cluster (1.14) with **managed nodes**

**Comment by christarazi** [comment]
Additional info:

* Kernel version: 

```
Linux version 4.14.181-140.257.amzn2.x86_64 (mockbuild@ip-10-0-1-230) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-6) (GCC)) #1 SMP Wed May 27 02:17:36 UTC 2020
```
* Ruled out the possibility of stale rules (a common issue on ENI-based deployments) via by running [cilium/stale-rules](github.com/cilium/stale-rules).

**Comment by aanm** [comment]
@anunay007 are you still facing these issues?

**Comment by errordeveloper** [comment]
From the sysdump it looks like ENI mode was used. I'd suspect this more likely to be related to a security group configuration issue, unless it's to do with autoscaling and stale VPC CNI config files. Was the cluster deployed using `eksctl` or somehow else?
