### ISSUE TITLE
agent: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by mvisonneau** [cilium/cilium#12460]
## Bug report

Scaling out the amount of nodes of a kubernetes cluster, some of the cilium agent (~18%) failed on the first run with the following error : `fatal error: concurrent map writes`. They all seemed to be working fine after the very next automated restart of the agent process.

at first sight, the error seems quite similar to https://github.com/cilium/cilium/issues/8278

**General Information**

- Cilium version: **1.8.1**
- Kernel version: **5.4.0-1015-aws**
- Orchestration system version in use: **EKS/1.16.8 (eks.1)**
- Link to relevant artifacts: [previous logs of a failed cilium agent pod](https://github.com/cilium/cilium/files/4892180/trace.log)

I am happy to provide the sysdump if necessary as it won't fit on this GitHub issue (>10MB).

**How to reproduce the issue**

I am very uncertain about which environment specifics may be in cause, all I can tell for now is that it never happened until today as I attempted to scale from 5 nodes to 75. All t3a.xlarge in a single AZ. Scaled out via the cluster-autoscaler after increasing the amount of replicas of an `httpbin` deployment.

**Comment by tklauser** [comment]
Thanks for the report. I think I spotted the issue and will send a PR shortly.

**Comment by mvisonneau** [comment]
awesome, thanks for the fix @tklauser! 🙇
