### ISSUE TITLE
CRD-based Identity Garbage Collection by Cilium-Operator broken on 1.6.9 and 1.6.10

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#12465]
Observed behavior is that a config where the CRD-identity GC runs and works fine on 1.6.8 does not result in the CRD-identity GC running at all in 1.6.9 and 1.6.10. 

Logs from 1.6.8 show crd-identity-gc running: 

```
level=info msg="Starting security identity garbage collector with 15m0s interval..." subsys=cilium-operator
level=debug msg="Starting new controller" name=crd-identity-gc subsys=controller uuid=81f2dbc9-c18b-11ea-a3f3-588a5a8ec880
level=debug msg="Controller func execution time: 2.853µs" name=crd-identity-gc subsys=controller uuid=81f2dbc9-c18b-11ea-a3f3-588a5a8ec880
```

Logs with 1.6.9 or 1.6.10 do not even with the exact same config.  

Simplest explanation would be that it is caused by this 1.6.x backport:  

https://github.com/cilium/cilium/commit/1f907666e82253fb2698cd346068ba10930f1dbd#diff-4b583376b2767b923c3e1da60d10de59

This backport seems to assume that "identityAllocationMode" and "option.Config.IdentityAllocationMode" are interchangeable, but I'm guessing that is not the case, as that would seem like the most logical reason of why "startCRDIdentityGC()" would not be called .    I'm not familiar enough with this code to comment more than that though.

**Comment by joestringer** [comment]
Fixed by #12496.
