### ISSUE TITLE
Failing k8s e2e test:: [sig-network] Services should be able to switch session affinity for NodePort service [LinuxOnly]

### ISSUE THREAD

**Issue by olemarkus** [cilium/cilium#12489]
## Bug report

Kops master switched to using BPF/kubeproxy-free and this test started failing.
https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-cilium

See also #11302

Note that this issue is a part of conformance suite as of k8s 1.19.

**Comment by brb** [comment]
Thanks for the report. Do you happen to have `cilium status` output from the test run? If not, what is exact cilium configuration you deploy?

**Comment by olemarkus** [comment]
Unfortunately, the K8s e2e system doesn't let me access the cluster directly. But the default config looks like this:
```
  auto-direct-node-routes: "false"
  bpf-ct-global-any-max: "262144"
  bpf-ct-global-tcp-max: "524288"
  cluster-name: default
  container-runtime: none
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-node-port: "true"
  enable-remote-node-identity: "true"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  ipam: kubernetes
  kube-proxy-replacement: strict
  masquerade: "true"
  monitor-aggregation: medium
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "false"
```

**Comment by johngmyers** [comment]
Kubernetes recently tightened the conformance test that's failing here in kubernetes/kubernetes#92427

**Comment by adamwg** [comment]
I'm hitting this as well. Output of `cilium status` (after the test run - hard to catch it during):

```root@master-test-1-19-2-2c58ef22:~# kubectl -n kube-system exec -it cilium-2qmd4 -- cilium status
KVStore:                               Ok   etcd: 1/1 connected, lease-ID=4f7774b7915ec94d, lock lease-ID=4f7774b7915ec94f, has-quorum=true: https://56a0b5e8-4b56-4b83-b1c4-e0b198eeb0b2.internal.k8s.ondigitalocean.com:2379 - 3.4.9 (Leader)
Kubernetes:                            Ok   1.19 (v1.19.2) [linux/amd64]
Kubernetes APIs:                       ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:                  Partial   []   [SessionAffinity]
Cilium:                                Ok        OK
NodeMonitor:                           Disabled
Cilium health daemon:                  Ok
IPAM:                                  IPv4: 2/127 allocated from 10.244.0.128/25,
Masquerading:                          IPTables
Controller Status:                     24/24 healthy
Proxy Status:                          OK, ip 10.244.0.165, 0 redirects active on ports 10000-20000
Hubble:                                Disabled
Cluster health:                        2/3 reachable    (2020-09-22T23:09:55Z)
  Name                                 IP               Node          Endpoints
  cilium-master-test-1-19-2-2c58ef22   10.135.218.227   unreachable   reachable
```

Note that the unreachable node is normal - that node is not schedulable in the cluster.

Config:
```
  auto-direct-node-routes: "false"
  bpf-ct-global-any-max: "262144"
  bpf-ct-global-tcp-max: "524288"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cluster-name: default
  cni-chaining-mode: portmap
  debug: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-external-ips: "true"
  enable-health-check-nodeport: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-node-port: "false"
  enable-remote-node-identity: "false"
  enable-session-affinity: "true"
  enable-well-known-identities: "true"
  enable-xt-socket-fallback: "true"
  identity-allocation-mode: kvstore
  install-iptables-rules: "true"
  kube-proxy-replacement: partial
  kvstore: etcd
  kvstore-opt: '{"etcd.config": "/var/lib/etcd-config/etcd.config"}'
  masquerade: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "false"
```

Any potential workarounds for this?

**Comment by fristonio** [comment]
Hey @adamwg 
I am working on this, didn't get the time to investigate deep into this though. Looking to pick this up later this week, I will update the thread if I find something useful.

**Comment by adamwg** [comment]
Pretty sure I've figured this out.

With debug logging enabled, if I change the `labels` for a Service, I see a `Kubernetes service definition changed` message in the logs. However, if I change only the `sessionAffinity` of the service, no such message is produced.

Digging into the cilium code, [this function](https://github.com/cilium/cilium/blob/master/pkg/k8s/service.go#L297) is used to determine whether a service has changed when the k8s watcher reports an update. Note that the `sessionAffinity` and `sessionAffinityTimeoutSec` are not considered in the comparison.

I'll attempt a fix for this.

**Comment by adamwg** [comment]
The change in #13271 fixes this issue in my setup. Once that's merged I'd appreciate a backport to 1.8 and a patch release - let me know if there's anything I can do to help make that happen.

**Comment by fristonio** [comment]
Hey, @adamwg thanks for your contribution :rocket: . The PR is labeled with `backport/1.8` and will be picked up by backporters team soon to land into 1.8 release.

**Comment by brb** [comment]
@olemarkus Does https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-cilium run with the `cilium/cilium:latest` image?

**Comment by olemarkus** [comment]
No, it runs with the default version in kops, which is currently 1.8.3.
The reason it shows green is because we filter failing tests that are outside of our control. Once the backports have been released, I can update cilium and remove the filters.
