### ISSUE TITLE
CI: Two tests running on same GKE cluster stomping on each other 

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#12485]
There is evidence in [GKE build 1790](https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/1790) that another test build has started to interfere with the same cluster. Output from an failing test indicates that Istio PODs have just been deployed in the middle of an unrelated test:
```
13:04:11  	 cilium                                                            log-gatherer-mtz6v                                          1/1     Running             0          53m     10.128.0.57   gke-cilium-ci-20-cilium-ci-20-f29e3692-dt5m   <none>           <none>
13:04:11  	 istio-system                                                      istio-ingressgateway-cb667b966-sdskf                        0/1     ContainerCreating   0          2s      <none>        gke-cilium-ci-20-cilium-ci-20-f29e3692-dt5m   <none>           <none>
13:04:11  	 istio-system                                                      istiod-54c66cdfff-bfm6d                                     1/1     Running             0          22s     10.44.1.172   gke-cilium-ci-20-cilium-ci-20-f29e3692-t49t   <none>           <none>
13:04:11  	 istio-system                                                      prometheus-6b8fbb5d7b-2lnkc                                 0/2     ContainerCreating   0          1s      <none>        gke-cilium-ci-20-cilium-ci-20-f29e3692-t49t   <none>           <none>
13:04:11  	 kube-system                                                       event-exporter-v0.2.5-599d65f456-9mfz5                      2/2     Running             0          51m     10.44.1.167   gke-cilium-ci-20-cilium-ci-20-f29e3692-t49t   <none>           <none>
```
Note the running time of the istio-system PODs: 1-22 seconds.

Istio test in this test run starts 1.5 hours later:
```
14:46:50  K8sIstioTest Istio Bookinfo Demo 
```

Indeed the previous build [(GKE build 1789)](https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/1789) is running on the same cluster and it started Istio deployment at 13:03:24:
```
13:03:24  20:03:24 STEP: Deplying Istio
13:04:14  20:04:12 STEP: Waiting for Istio pods to be ready
```

**Comment by nebril** [comment]
I think I found what happened there. https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/1789/ ran with older version of `lock.yaml` file, which was created in `default` k8s namespace, which caused this build to think that the cluster is not locked (the second build looked for the lock in `cilium-ci-lock` ns). This might happen with older, non-rebased prs, but I don't think there is anything to be done aside from waiting it out. Let me know if you want to keep this open to track this.

**Comment by joestringer** [comment]
I'm gonna guess this is resolved by this point since there's no update since July last year. Closing.
