### ISSUE TITLE
Improve cilium status KubeProxyReplacement output

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#12499]
In the probed partial kube-proxy-replacement mode, the individual feature state (e.g., hostPort) in the output of 'cilium state' is ambiguous. 

>cilium status
:
KubeProxyReplacement:   Partial   ()   []
:

We can explicitly print out what features are enabled in the partial mode so that there is no ambiguity.

**Comment by brb** [comment]
`KubeProxyReplacement: Partial () []` means that no kube-proxy replacement feature was enabled.

> We can explicitly print out what features are enabled in the partial mode so that there is no ambiguity.

Are you suggesting to print each feature status, i.e. `enabled` or `disabled`?

**Comment by aditighag** [comment]
> 
> Are you suggesting to print each feature status, i.e. `enabled` or `disabled`?

Per Slack conversation, yes, that's what I had in mind.

**Comment by borkmann** [comment]
Fixed via https://github.com/cilium/cilium/pull/13131
