### ISSUE TITLE
Reject Cilium network policies with unknown fields

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#12516]
Every once in a while, we spend time debugging policy issues with users where the cause end up being a malformed Cilium network policy (usually an YAML indentation problem). These happen because we don't reject policies with unknown fields.

In https://github.com/cilium/cilium/pull/11638#issuecomment-634949368, @christarazi mentioned that we would need to set `preserveUnknownFields: false` to fix this.

Related: #11142

**Comment by pchaigno** [comment]
I took a first stab at this.

Adding `preserveUnknownFields: false` itself is trivial:
```diff
diff --git a/pkg/k8s/apis/cilium.io/v2/client/register.go b/pkg/k8s/apis/cilium.io/v2/client/register.go
index 29caabae2..a69540f13 100644
--- a/pkg/k8s/apis/cilium.io/v2/client/register.go
+++ b/pkg/k8s/apis/cilium.io/v2/client/register.go
@@ -88,6 +88,7 @@ func createCNPCRD(clientset apiextensionsclient.Interface) error {
        var (
                // CustomResourceDefinitionShortNames are the abbreviated names to refer to this CRD's instances
                CustomResourceDefinitionShortNames = []string{"cnp", "ciliumnp"}
+               preserveUnknownFields              = false
        )
 
        res := &apiextensionsv1beta1.CustomResourceDefinition{
@@ -109,8 +110,9 @@ func createCNPCRD(clientset apiextensionsclient.Interface) error {
                        Subresources: &apiextensionsv1beta1.CustomResourceSubresources{
                                Status: &apiextensionsv1beta1.CustomResourceSubresourceStatus{},
                        },
-                       Scope:      apiextensionsv1beta1.NamespaceScoped,
-                       Validation: CNPCRV,
+                       Scope:                 apiextensionsv1beta1.NamespaceScoped,
+                       Validation:            CNPCRV,
+                       PreserveUnknownFields: &preserveUnknownFields,
                },
        }
        // Kubernetes < 1.12 does not support having the field Type set in the root
```
Loading most policies then fails because our schema doesn't cover the `Description` field. We thus need to add a `JSONSchemaProps` for the description. Also trivial.

At this point, all policies I tried loaded fine, but their `status` section was missing in `kubectl describe` because we don't have a schema for it. All tests with policies fail because of that.

Adding a schema for `status` is a lot more involved. In particular, we use maps to define `status` (for the status per node, the status of derived policies, and the annotations inside those statuses).
https://github.com/cilium/cilium/blob/82e36cd18ea96aab29b9dff9a0a3180685f54a6b/pkg/k8s/apis/cilium.io/v2/types.go#L112-L114
Defining a schema for those map would require us to write something along the line of:
```go
"nodes": {
    PatternProperties: map[string]apiextensionsv1beta1.JSONSchemaProps{
        "\\w+": nodeStatus,
    },
},
```
However, that results in the following error because it looks like `PatternProperties` is not supported in the versions of K8s or the library we use.
```
Creating CRD (CustomResourceDefinition)...
Unable to create custom resource definition: CustomResourceDefinition.apiextensions.k8s.io
  \"ciliumnetworkpolicies.cilium.io\" is invalid [
    spec.validation.openAPIV3Schema.properties[status].properties[derivativePolicies].patternProperties:
    Forbidden: patternProperties is not supported,
    spec.validation.openAPIV3Schema.properties[status].properties[nodes].patternProperties:
    Forbidden: patternProperties is not supported
  ]
```
Switching those maps to use slices instead would be fairly invasive change and might have a performance impact at scale.
@christarazi @aanm I'd be happy to try out other approaches if you have ideas.

**Comment by aanm** [comment]
@pchaigno we need to address this https://github.com/cilium/cilium/pull/11477 and https://github.com/cilium/cilium/pull/11476 first.

**Comment by pchaigno** [comment]
@aanm Ah, I thought #11476 was the long term way of getting this. But yeah, if it's not far down the road, makes sense to wait for that to be merged yet. AFAIU, we shouldn't need to wait for #11477 to set `preserveUnknownFields: false` though; #11476 should be enough to get us the required schemas.

**Comment by christarazi** [comment]
@pchaigno That's correct. There's multiple layers to this, but the TLDR is:

v1beta1 CRDs can set `preserveUnknownFields: false`, but the CRDs **must also** have a structural validation schema. A structural validation schema is as defined here: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema It is not trivial to generate a structural validation schema, hence the work to automate it.

The work is being done in https://github.com/cilium/cilium/pull/11607 as a precursor to the others mentioned above.
