### ISSUE TITLE
CI: K8sServicesTest Checks fails with "Can not connect to service X from outside cluster"

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#12511]
```
/home/jenkins/workspace/Ginkgo-CI-Tests-k8s1.11-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Can not connect to service "http://192.168.37.11:30146" from outside cluster
Expected command: kubectl exec -n kube-system log-gatherer-rlhxl -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.37.11:30146 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000023()', Connect: '0.000000',Transfer '0.000000', total '5.001665'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Ginkgo-CI-Tests-k8s1.11-Pipeline/src/github.com/cilium/cilium/test/k8sT/Services.go:514
```

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-k8s1.11-Pipeline/727/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-k8s1.11-Pipeline/724/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

**Comment by nebril** [comment]
Adding a log dump from one of the builds: 
[c8b8f8ac_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip](https://github.com/cilium/cilium/files/4912437/c8b8f8ac_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip)

**Comment by jrajahalme** [comment]
Also at https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/199/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

**Comment by pchaigno** [comment]
Also hit at https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/349/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_NodePort/
Dump: 
[2ba31a1f_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_NodePort.zip](https://github.com/cilium/cilium/files/5160451/2ba31a1f_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_NodePort.zip)

**Comment by aditighag** [comment]
Also hit on https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/352/testReport/junit/Suite-k8s-1/12/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

**Comment by jrajahalme** [comment]
Hit on: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/126/testReport/junit/Suite-k8s-1/13/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

**Comment by jrajahalme** [comment]
Same but exit code 7: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/145/testReport/Suite-k8s-1/13/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

**Comment by jrajahalme** [comment]
Another one: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/131/testReport/junit/Suite-k8s-1/13/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

**Comment by brb** [comment]
![np-sec](https://user-images.githubusercontent.com/122571/101868164-07a2e980-3b7d-11eb-8583-6a6a989da86e.png)

This started to happen more often since 7. / 8. Dec.

**Comment by jrajahalme** [comment]
Same line, different curl return code:
```
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Can not connect to service "http://192.168.37.11:31397" from outside cluster
Expected command: kubectl exec -n kube-system log-gatherer-fgh4s -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.37.11:31397 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 7 
Err: exit status 7
Stdout:
 	 time-> DNS: '0.000032()', Connect: '0.000000',Transfer '0.000000', total '0.000138'
Stderr:
 	 command terminated with exit code 7
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/k8sT/Services.go:776
```
at https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/282/testReport/junit/Suite-k8s-1/13/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

**Comment by christarazi** [comment]
Same as Jarno above. Hit in https://github.com/cilium/cilium/pull/14477. 
[b2b4cb83_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip](https://github.com/cilium/cilium/files/5736659/b2b4cb83_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip)

**Comment by ungureanuvladvictor** [comment]
Got the same failure as Jarno and Chris in https://github.com/cilium/cilium/pull/14482.

[cbd1447d_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_with_secondary_NodePort_device.zip](https://github.com/cilium/cilium/files/5737283/cbd1447d_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_with_secondary_NodePort_device.zip)

**Comment by ungureanuvladvictor** [comment]
Was hit by this again in https://github.com/cilium/cilium/pull/14491.

[f7c0830d_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip](https://github.com/cilium/cilium/files/5748246/f7c0830d_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip)

**Comment by ungureanuvladvictor** [comment]
Was hit by this in https://github.com/cilium/cilium/pull/14500.

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/326/ is the link to the failure.

**Comment by jrajahalme** [comment]
Here as well: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/375/testReport/Suite-k8s-1/13/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

**Comment by pchaigno** [comment]
Can also happen with test:
```
Checks service across nodes Tests NodePort BPF Tests with vxlan Tests NodePort with Maglev Tests NodePort
```
(Just so GH searches on that test return this issue.)

**Comment by pchaigno** [comment]
Can also happen with test:
```
K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing and DSR
```

**Comment by pchaigno** [comment]
Also happening for K8sServicesTest Checks service across nodes `Tests NodePort BPF Tests with direct routing Tests NodePort`.

**Comment by Weil0ng** [comment]
Was hit by same error in https://github.com/cilium/cilium/pull/17235

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1470/

**Comment by joestringer** [comment]
@brb was assigned in mid-2020, removing assignee since it's clear there is no active investigation into this issue.

**Comment by brb** [comment]
@joestringer Actually I've been working on preparing how to trace down what's going on in the suite. Going to troubleshoot it after the v1.11 release.

**Comment by joestringer** [comment]
@brb OK, in that case I will move it into the "1.11 CI -> deferred" column. Feel free to re-assign when you plan on working on it.

**Comment by brb** [comment]
We got to the conclusion why it happens - cilium-agent becomes ready before the host endpoints get regenerated (e.g., bpf_netdev_eth0.o). This leads to old programs to handling requests which might fail in different ways. For example the following request failed in the `K8sServicesTest_Checks_N_S_loadbalancing_Tests_with_direct_routing_and_DSR` suite:

```
{"flow":{"time":"2022-02-06T11:11:41.194021072Z","verdict":"FORWARDED","ethernet":{"source":"08:00:27:99:aa:05","destination":"08:00:27:79:79:50"},"IP":{"source":"192.168.56.13","destination":"10.0.1.105","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":40150,"destination_port":80,"flags":{"SYN":true}}},"source":{"identity":6,"labels":["reserved:remote-node"]},"destination":{"identity":19067,"namespace":"default","labels":["k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default","k8s:io.cilium.k8s.policy.cluster=default","k8s:io.cilium.k8s.policy.serviceaccount=default","k8s:io.kubernetes.pod.namespace=default","k8s:zgroup=testDS"],"pod_name":"testds-dkbnh"},"Type":"L3_L4","node_name":"k8s1","event_type":{"type":4,"sub_type":4},"trace_observation_point":"TO_OVERLAY","interface":{"index":40},"Summary":"TCP Flags: SYN"},"node_name":"k8s1","time":"2022-02-06T11:11:41.194021072Z"}
```

The previous suite was running in the tunnel mode, so the old program was still trying to send the packet over the tunnel which no longer existed. This resulted in the silent drop.

@joestringer suggested the potential fix:
> one maybe-option is look into whether cilium endpoint regenerate ... triggers+waits for full regeneration of an endpoint. I'm imagining, we do cilium endpoint list -o json, find the host endpoint, trigger regeneration, hopefully that waits until regeneration is complete, then continue on.
If we want to avoid triggering host endpoint regeneration on every change, maybe make it conditional based on optionChangesRequiresPodRedeploy() and make that function return yes when tunnel mode changes.

**Comment by bimmlerd** [comment]
Apologies for the necrobump, but it seems like i just saw this on my PR to `main`: https://github.com/cilium/cilium/pull/25007,

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.27-kernel-net-next/110/testReport/junit/Suite-k8s-1/27/K8sDatapathServicesTest_Checks_N_S_loadbalancing_with_L7_policy_Tests_NodePort_with_L7_Policy_from_outside/

sysdump: [d32321f6_K8sDatapathServicesTest_Checks_N-S_loadbalancing_with_L7_policy_Tests_NodePort_with_L7_Policy_from_outside.zip](https://github.com/cilium/cilium/files/11324056/d32321f6_K8sDatapathServicesTest_Checks_N-S_loadbalancing_with_L7_policy_Tests_NodePort_with_L7_Policy_from_outside.zip)
