### ISSUE TITLE
Verify CNI installation on startup

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1252]
When running in a Kubernetes or Mesos environment. Verify proper CNI installation and warn if not valid.

- [ ] When running in Kubernetes mode, check whether the Cilium CNI configuration file has been written and whether it is the first file in the cni/net.d when listed alphabetically.

**Comment by aanm** [comment]
This is becoming more common, I'm increasing priority for this.

**Comment by ianvernon** [comment]
#8857 sleeps for two seconds to avoid most cases of this problem. A more detailed fix is outlined here: https://github.com/cilium/cilium/pull/8857#issuecomment-520020623
