### ISSUE TITLE
Clarify docs for kubeProxyReplacement disabled vs.partial

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12543]
Per discussion in SIG-datapath:

https://docs.cilium.io/en/v1.7/gettingstarted/kubeproxy-free/?highlight=kube-proxy-replacement

There are two sections here that state that "v1.6 or earlier" or "pre-v1.6" behaviour can be implemented by either setting `kubeProxyReplacement` to disabled or partial. We should pick one to minimize confusion for users.

(The above link is v1.7, I didn't look whether v1.8 or later docs also make this unclear).

**Comment by brb** [comment]
We have deprecated and removed the "partial" mode, so closing the issue.
