### ISSUE TITLE
Use value receivers rather than pointer receivers for simple types

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12558]
Files like `pkg/policy/api/cidr.go` define functions on the `cidr` using a pointer receiver, but as a general style guidance for simple types like these we should make use of value receivers:

https://golang.org/doc/faq#methods_on_values_or_pointers

**Comment by pchaigno** [comment]
Was this addressed by https://github.com/cilium/cilium/pull/12563?

**Comment by joestringer** [comment]
Yes, yes it was.
