### ISSUE TITLE
Add a Github action to verify that every commit in a PR compiles on its own

### ISSUE THREAD

**Issue by rolinh** [cilium/cilium#12554]
The contributing guide makes the following statement [here](https://docs.cilium.io/en/latest/contributing/development/contributing_guide/#submitting-a-pull-request):

> Before hitting the submit button, please make sure that the following requirements have been met:
>
 >   1.  **Each commit compiles and is functional on its own to allow for bisecting of commits**.
>    2. ...

When rebasing a PR with multiple commits; it's tedious to checkout each commit and ensure the code builds fine. I propose to investigate if it's feasible to have a GitHub action that would do exactly this: checkout and build every commit in a PR (could be optional and obviously only for PR with more than 1 commit). It's important that the code still compiles when bisecting.

**Comment by pchaigno** [comment]
I've had that on my own TODO for a while. If we can get the base commit, it should be fairly trivial with:
```
git rebase --exec "make clean && make -j$(nproc)" base
```
I think it would also be useful to run `make -C bpf build_all` in that setup. That's what I do locally for every PR rebase and it does catch a lot of stuff.

**Comment by ankurkothiwal** [comment]
@pchaigno I would like to work on this issue. Can you please assign this to me?

**Comment by pchaigno** [comment]
@ankurkothiwal Don't hesitate to reach out on Slack (e.g., #development or #testing) if you have any question.
