### ISSUE TITLE
Strange performance issue

### ISSUE THREAD

**Issue by blairw-brk** [cilium/cilium#12564]
My test environment:

>  master node : 172.11.22.100
>  worker-node-0 : 172.11.22.101
>  worker-node-1 : 172.11.22.102
>  nginx-0 (container in node-0) 10.217.1.43
>  nginx-1 (container in node-1) 10.217.2.98

k8s: 1.8.5; cilium : 1.7.6/1.8.1
worker nodes: centos 8 + kernel 5.7.8

Test tools : iperf3

Test Results:

> 172.11.22.100 <=> 172.11.22.101 : 9.4Gb
> 172.11.22.100 <=> 172.11.22.102 : 9.4Gb
> 172.11.22.101 <=> 172.11.22.102 : 9.4Gb

>   [iperf3 -c] ------------- [iperf3 -s]
> 172.11.22.100  =>   10.217.2.98    :  2.2Gb
> 172.11.22.100  <=   10.217.2.98    :  2.6Gb (iperf3 -c .. -R)

> 172.11.22.100  =>   10.217.1.43    :  6.4Gb
> 172.11.22.100  <=   10.217.1.43    :  2.6Gb (iperf3 -c .. -R)

> 10.217.2.98    =>   172.11.22.100  :  3.5Gb
> 10.217.2.98    <=   172.11.22.100  :  9.4Gb (iperf3 -c .. -R)

> 10.217.1.43    =>   172.11.22.100  :  8.3Gb
> 10.217.1.43    <=   172.11.22.100  :  9.2Gb (iperf3 -c .. -R)

> 10.217.1.43    =>   10.217.2.98    :  2.4Gb
> 10.217.1.43    <=   10.217.2.98    :  9.0Gb (iperf3 -c .. -R)

> 10.217.2.98    =>   10.217.1.43    :  9.0Gb
> 10.217.2.98    <=   10.217.1.43    :  2.2Gb (iperf3 -c .. -R)

The throughput of two directions have big difference.

I'm new to k8s and cilium, and I'm not sure if this is a issue. Please help me.

**Comment by blairw-brk** [comment]
The cilium was installed with option global.kubeProxyReplacement=strict. 

kubectl get pods -n kube-system :
 
 NAME                                  READY   STATUS    RESTARTS   AGE
 cilium-fk2ss                          1/1     Running   0          19h
 cilium-hv7q6                          1/1     Running   2          19h
 cilium-ls92q                          1/1     Running   0          19h
 cilium-operator-6fb9b5c6b-9h7hf       1/1     Running   0          62m
 coredns-66bff467f8-4jlxq              1/1     Running   31         42d
 coredns-66bff467f8-wx5h4              1/1     Running   32         42d
 etcd-master-node                      1/1     Running   154        42d
 kube-apiserver-master-node            1/1     Running   152        42d
 kube-controller-manager-master-node   1/1     Running   34         42d
 kube-scheduler-master-node            1/1     Running   34         42d

**Comment by brb** [comment]
- Did you see any retransmissions in iperf?
- What is your setup? Baremetal or VM? What NICs etc?
- If you set `global.kubeProxyReplacement=disabled`, does it make a difference?
- Have you tried using direct routing instead of tunnel?

**Comment by blairw-brk** [comment]
1. sorry, It's my fault. I use the k8s 1.18.5, not 1.8.5. :(
2. the number of retransmissions from iperf is very small

Bad performance:

root@nginx-at-0-6b76ff8665-dckdt:/# iperf3 -c 10.0.0.48
Connecting to host 10.0.0.48, port 5201
[  5] local 10.0.1.96 port 57058 connected to 10.0.0.48 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   340 MBytes  2.85 Gbits/sec   72   1.12 MBytes
[  5]   1.00-2.00   sec   341 MBytes  2.86 Gbits/sec    7   1.02 MBytes
[  5]   2.00-3.00   sec   340 MBytes  2.85 Gbits/sec    2    946 KBytes
[  5]   3.00-4.00   sec   341 MBytes  2.86 Gbits/sec    0   1.16 MBytes
[  5]   4.00-5.00   sec   341 MBytes  2.86 Gbits/sec   28   1.06 MBytes
[  5]   5.00-6.00   sec   341 MBytes  2.86 Gbits/sec   34    973 KBytes
[  5]   6.00-7.00   sec   339 MBytes  2.84 Gbits/sec   29    848 KBytes
[  5]   7.00-8.00   sec   340 MBytes  2.85 Gbits/sec    0   1.08 MBytes
[  5]   8.00-9.00   sec   341 MBytes  2.86 Gbits/sec   30   1002 KBytes
[  5]   9.00-10.00  sec   340 MBytes  2.85 Gbits/sec   28    882 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  3.33 GBytes  2.86 Gbits/sec  230             sender
[  5]   0.00-10.00  sec  3.32 GBytes  2.85 Gbits/sec                  receiver

Good performance:

root@nginx-at-1-5f7c454db7-qq2ls:/# iperf3 -c 10.0.1.96
Connecting to host 10.0.1.96, port 5201
[  5] local 10.0.0.48 port 47130 connected to 10.0.1.96 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  1.03 GBytes  8.89 Gbits/sec   46   1.10 MBytes
[  5]   1.00-2.00   sec  1.06 GBytes  9.09 Gbits/sec   20   1.24 MBytes
[  5]   2.00-3.00   sec  1.06 GBytes  9.09 Gbits/sec   23   1.28 MBytes
[  5]   3.00-4.00   sec  1.06 GBytes  9.08 Gbits/sec    0   1.30 MBytes
[  5]   4.00-5.00   sec  1.06 GBytes  9.09 Gbits/sec    4   1.31 MBytes
[  5]   5.00-6.00   sec  1.06 GBytes  9.09 Gbits/sec    0   1.32 MBytes
[  5]   6.00-7.00   sec  1.06 GBytes  9.09 Gbits/sec    3   1.33 MBytes
[  5]   7.00-8.00   sec  1.06 GBytes  9.09 Gbits/sec    0   1.34 MBytes
[  5]   8.00-9.00   sec  1.06 GBytes  9.09 Gbits/sec    0   1.35 MBytes
[  5]   9.00-10.00  sec  1.06 GBytes  9.08 Gbits/sec    0   1.36 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  10.6 GBytes  9.07 Gbits/sec   96             sender
[  5]   0.00-10.00  sec  10.6 GBytes  9.06 Gbits/sec                  receiver

3. Baremetal, there's one 82599 4x10G NIC in every node
4. No. I want Cilium to replace the kube-proxy. but, I could make a try.
5. No. I'll make a try.

**Comment by borkmann** [comment]
> worker nodes: centos 8 + kernel 5.7.8

Does the master node have the same? Can you get `ethtool -k <dev>` dump to check whether gro/gso/tso is potentially off on some of the devs on the nodes?

[...]
> 1. Baremetal, there's one 82599 4x10G NIC in every node
> 2. No. I want Cilium to replace the kube-proxy. but, I could make a try.
> 3. No. I'll make a try.

The last two data-points are definitely needed for comparison.

Also if you could get additionally a sysdump from the three test nodes that would help (https://docs.cilium.io/en/v1.8/troubleshooting/#reporting-a-problem).

**Comment by blairw-brk** [comment]
* The master node is Ubuntu server 20.04 + kernel 5.4.0
* I've checked the gro, gso, tso , all been enabled on all the cluster nodes.
    only a little difference, one NIC is X710 (worker-node-0), the tx-tcp-ecn-segmentation is on. 
    but for the other two 82599s, this option is off.
* sysdump in the attachment.
[cilium-sysdump-20200717-093227.zip](https://github.com/cilium/cilium/files/4936931/cilium-sysdump-20200717-093227.zip)

* I'll make a try for direct routing and no-disable for kube-proxy, next week.

**Comment by blairw-brk** [comment]
This testing for the setup with kube-proxy
------------------------------------------------------
  * sudo kubeadm init --apiserver-advertise-address=172.11.22.100 --pod-network-cidr=10.217.0.0/16 --node-name=master-node
  * helm template cilium/cilium   --version 1.8.1 --namespace kube-system --set global.hubble.enabled=true > cilium-1_8_1.yaml
     kubectl apply -f ./cilium.yaml

Check running
--------------------

kubectl get pods -n kube-system
NAME                                  READY   STATUS    RESTARTS   AGE
cilium-lcrfs                          1/1     Running   0          10m
cilium-operator-657978fb5b-d7b7x      1/1     Running   0          10m
cilium-qbdl8                          1/1     Running   0          10m
cilium-xgvr8                          1/1     Running   0          10m
coredns-66bff467f8-jj7pg              1/1     Running   0          18m
coredns-66bff467f8-ztb59              0/1     Running   0          18m
etcd-master-node                      1/1     Running   0          18m
kube-apiserver-master-node            1/1     Running   0          18m
kube-controller-manager-master-node   1/1     Running   0          18m
kube-proxy-bl5tc                      1/1     Running   0          18m
kube-proxy-q69tg                      1/1     Running   0          15m
kube-proxy-rqrmw                      1/1     Running   0          14m
kube-scheduler-master-node            1/1     Running   0          18m

Testing result
------------------
nginx-0(worker-node-0)   => nginx-1(worker-node-1)  :  2.4Gb
nginx-1(worker-node-1)   => nginx-0(worker-node-0) :   9.4Gb

worker-node-0 <=> worker-node-1 : 9.4Gb

same as the original testing result.

**Comment by blairw-brk** [comment]
@borkmann Could you give me a simple guide for how to set up the direct routing mode?
   What value should I configure for the "native-routing-cidr" ?

**Comment by borkmann** [comment]
> @borkmann Could you give me a simple guide for how to set up the direct routing mode?
> What value should I configure for the "native-routing-cidr" ?

Did you use the kubeproxy-free GSG:

https://docs.cilium.io/en/v1.8/gettingstarted/kubeproxy-free/

For example:

```
kubeadm init --skip-phases=addon/kube-proxy
[...]
helm repo add cilium https://helm.cilium.io/
helm install cilium cilium/cilium --version 1.8.1 \
    --namespace kube-system \
    --set global.tunnel=disabled \
    --set global.autoDirectNodeRoutes=true \
    --set global.kubeProxyReplacement=strict \
    --set global.k8sServiceHost=API_SERVER_IP \
    --set global.k8sServicePort=API_SERVER_PORT
```

What error did you get?

**Comment by blairw-brk** [comment]
blair_wang@test15-ubs:~/kube$ kubectl get pods -n kube-system
NAME                                  READY   STATUS              RESTARTS   AGE
cilium-94t5x                          0/1     CrashLoopBackOff    4          3m15s
cilium-d8hlh                          0/1     CrashLoopBackOff    4          3m15s
cilium-operator-7c7f5b75f9-2jcpr      1/1     Running             0          3m15s
cilium-vs8h7                          0/1     CrashLoopBackOff    4          3m15s
coredns-66bff467f8-2h95t              0/1     ContainerCreating   0          6m38s
coredns-66bff467f8-qwxlq              0/1     ContainerCreating   0          6m38s
etcd-master-node                      1/1     Running             0          6m46s
kube-apiserver-master-node            1/1     Running             0          6m46s
kube-controller-manager-master-node   1/1     Running             0          6m46s
kube-scheduler-master-node            1/1     Running             0          6m45s


error message:

kubectl logs cilium-94t5x -n kube-system
...
level=fatal msg="Error while creating daemon" error="invalid daemon configuration: native routing cidr must be configured with option --native-routing-cidr in combination with --masquerade --tunnel=disabled --ipam=cluster-pool --enable-ipv4=true" subsys=daemon

**Comment by brb** [comment]
@blairw-brk You need to set it with your podCIDR. Judging from the issue description it's `10.217.0.0/16` (`--set global.nativeRoutingCIDR="10.217.0.0/16"`).

**Comment by blairw-brk** [comment]
@brb It's working now, thanks.

But after install cilium with the direct routing setting, the container can't reach each other.
any cluster node can reach any container.

testing result
-----------------

master-node  =>   nginx-1    :  9.4Gb
master-node  <=   nginx-1    :  5.1Gb (iperf3 -c .. -R)

master-node  =>   nginx-0    :  9.4Gb
master-node  <=   nginx-0    :  8.7Gb (iperf3 -c .. -R)

nginx-1    =>   master-node  :  6.5Gb
nginx-1    <=   master-node  :  9.4Gb (iperf3 -c .. -R)

nginx-0    =>   master-node  :  8.6Gb
nginx-0    <=   master-node  :  9.4Gb (iperf3 -c .. -R)

routing information
-------------------------
nginx-0 (eth0 : 10.0.1.216)
  default via 10.0.1.106 dev eth0 mtu 1500
  10.0.1.106 dev eth0 scope link

nginx-1(eth0: 10.0.0.151)
  default via 10.0.0.131 dev eth0 mtu 1500
  10.0.0.131 dev eth0 scope link

worker-node-0:
default via 192.168.49.4 dev eno1 proto dhcp metric 101
10.0.0.0/24 via 172.11.22.102 dev ens4f0
10.0.1.0/24 via 10.0.1.106 dev cilium_host src 10.0.1.106 mtu 1500
10.0.1.106 dev cilium_host scope link
10.0.2.0/24 via 172.11.22.100 dev ens4f0
11.11.11.0/24 dev ens4f1 proto kernel scope link src 11.11.11.101
172.11.0.0/16 dev ens4f0 proto kernel scope link src 172.11.22.101 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.49.0/24 dev eno1 proto kernel scope link src 192.168.49.146 metric 101
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown

worker-node-1:
default via 192.168.49.4 dev eno1 proto dhcp metric 101
10.0.0.0/24 via 10.0.0.131 dev cilium_host src 10.0.0.131 mtu 1500
10.0.0.131 dev cilium_host scope link
10.0.1.0/24 via 172.11.22.101 dev ens1f0
10.0.2.0/24 via 172.11.22.100 dev ens1f0
11.11.11.0/24 dev ens1f1 proto kernel scope link src 11.11.11.102 linkdown
172.11.0.0/16 dev ens1f0 proto kernel scope link src 172.11.22.102 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.49.0/24 dev eno1 proto kernel scope link src 192.168.49.194 metric 101
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown

**Comment by brb** [comment]
Did you pass `--set global.autoDirectNodeRoutes=true`? If yes, maybe your fabric network is dropping packets from unknown subnet which in your case is podCIDR?

**Comment by brb** [comment]
@blairw-brk Any update on the issue?

**Comment by blairw-brk** [comment]
No.

I think the cause maybe there're individual management NIC and data NIC in my network environment.
In other words, the node NIC I used is not the NIC, which has the default route.

I use the --node-ip to force k8s use the NIC.




________________________________

**Comment by brb** [comment]
@blairw-brk So then I guess we can close this issue?

**Comment by blairw-brk** [comment]
Yes. close, please.
________________________________
