### ISSUE TITLE
bpf_host "to-host" prog sends TRACE_TO_STACK prematurely with host firewall enabled

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12562]
When host firewall is disabled, the `send_trace_notify()` call here is correct as it's the last thing to be done before handing the traffic to the stack.

https://github.com/cilium/cilium/blob/f55ec9066e3a23461a0d14e20b3be8ab49a04c97/bpf/bpf_host.c#L976-L980

However, if host firewall is enabled, then it's possible that the packet will be dropped due to the firewall, in which case the semantics of `TRACE_TO_STACK` are broken because we did not in fact hand the packet to the stack; rather we dropped the packet. We should not log both `TRACE_TO_STACK` and a drop notification for the same packet.

Tasks:
* [x] Move the `send_trace_notify()` to the end of the function to ensure it is only notified when the packet is delivered, https://github.com/cilium/cilium/pull/18484.
* [x] Investigate the `traced = true` path in the previous programs to ensure that they do not send the `TRACE_TO_STACK` notifications if the packet will instead be redirected into the bpf_host program.

**Comment by joestringer** [comment]
I noticed this while working on BPF_TPROXY so unless someone else has a clear idea of particularly the second aspect here, I will likely take a look into this issue.

**Comment by ti-mo** [comment]
I'm taking a look at this.

**Comment by Rishav0809** [comment]
Hi @joestringer , I want to work on this issue.

Can you suggest some ways in which I should proceed?

**Comment by pchaigno** [comment]
@Rishav0809 The initial issue comment has a code pointer and explanation on the unexpected behavior. Once you've read that, you can tackle the two items listed under "Tasks". If you have any specific questions, I'd be happy to try and answer.

**Comment by rscampos** [comment]
Hello @pchaigno,
I am planning take-up this issue, please, could you assign it to me.

**Comment by pchaigno** [comment]
@rscampos Please be aware that this issue is already partially addressed by https://github.com/cilium/cilium/pull/15486.

**Comment by rscampos** [comment]
Hello @pchaigno, thank you for letting me know, this is going to be my first collaboration (I'm excited for that :D ), do you suggest take another first-good-issue or the 12562 is good to start? If so, could you assign to 12562 pls?

**Comment by pchaigno** [comment]
@rscampos It might be easier to look for another `good-first-issue` as the author of #15486 is likely already looking into the second item here.

**Comment by rscampos** [comment]
@pchaigno , thank you. I'll get another one :D

**Comment by Maddy007-maha** [comment]
Hi @pchaigno,

Can you assign this issue to me?
I want to work on this.

-Thanks

**Comment by c4llous** [comment]
hey i wanna take part in gsoc 2022 so someone can pls tell me is this project is going to take part in gsoc 2022 ??

**Comment by YutaroHayakawa** [comment]
https://github.com/cilium/cilium/pull/18484 can resolve the first item in the original issue.

For the second item, I understood what it implies: "We shouldn't generate TRACE_TO_STACK trace message twice." In conclusion, I think there's no such a path. Following is how I checked that.

1. List up the `send_trace_notify` and exclude the calls that observe point is not `TRACE_TO_STACK` or variable.

```
bpf/bpf_lxc.c:453:	send_trace_notify(ctx, TRACE_TO_STACK, SECLABEL, *dst_id, 0, 0,
bpf/bpf_lxc.c:917:	send_trace_notify(ctx, TRACE_TO_STACK, SECLABEL, *dst_id, 0, 0,
bpf/bpf_lxc.c:1769:	send_trace_notify(ctx, trace, identity, 0, 0,
bpf/bpf_host.c:869:		send_trace_notify(ctx, trace, identity, 0, 0,
bpf/bpf_host.c:953:		send_trace_notify(ctx, TRACE_TO_STACK, HOST_ID, 0, 0, 0, 0, 0);
bpf/bpf_host.c:1146:		send_trace_notify(ctx, TRACE_TO_STACK, src_id, 0, 0,
```

2. Check the variable observe point and see if they can be a `TRACE_TO_STACK`. If not, we can exclude them from the list. In this case, all of them were not.

Remaining
```
bpf/bpf_lxc.c:453:	send_trace_notify(ctx, TRACE_TO_STACK, SECLABEL, *dst_id, 0, 0,
bpf/bpf_lxc.c:917:	send_trace_notify(ctx, TRACE_TO_STACK, SECLABEL, *dst_id, 0, 0,
bpf/bpf_host.c:953:		send_trace_notify(ctx, TRACE_TO_STACK, HOST_ID, 0, 0, 0, 0, 0);
bpf/bpf_host.c:1146:		send_trace_notify(ctx, TRACE_TO_STACK, src_id, 0, 0,
```

3. Manually the code flow after the traces and check there's no additional trace or tail-call jumps into the bpf_host program, or `ctx_redirect` jumps into the cilium_host/net devices. In this case, all of them didn't have such a code path.

The cilium version I checked was as of HEAD = ffa4243fb57a161ac6b846e1fe8e4fe48cc09e9c.

Overall, I think once we merge the https://github.com/cilium/cilium/pull/18484, we can close this issue.
