### ISSUE TITLE
Cilium 1.8.1 + metallb BGP, incoming traffic to externalIP not reaching pods

### ISSUE THREAD

**Issue by timricese** [cilium/cilium#12560]
## Bug report

After upgrading from 1.7.6 (without any configuration changes other than enabling hubble) to 1.8.1 a large amount (80%+) of requests to nginx-ingress and istio-gateway ingresses from outside the cluster time out.

`cilium monitor --drop` shows no sign of anything being dropped

tcpdump on the external interfaces (eth0) revealed that connections were only reaching the pods if the traffic arrived on the same node that the ingress controller pod was running on. 

tcpdump on the cilium_vxlan shows it on the cilium_vxlan interface via tcpdump, but the source address is the IP for the interface used for bgp peering. When comparing to another cluster running 1.7.6 there is no trace of those addresses, only internal cluster ips, which might indicate a problem with masquerading

comparing iptables-save between the 1.7.6 cluster and the non-working 1.8.1 cluster gives the following diff (trimmed some irrelevant rows):

```
~ $ diff non-working-1.8.1 working-1.7.6
9,11c9,11
< -A CILIUM_OUTPUT_raw -o lxc+ -m mark --mark 0xa00/0xfffffeff -m comment --comment "cilium: NOTRACK for proxy return traffic" -j NOTRACK
< -A CILIUM_OUTPUT_raw -o cilium_host -m mark --mark 0xa00/0xfffffeff -m comment --comment "cilium: NOTRACK for proxy return traffic" -j NOTRACK
< -A CILIUM_PRE_raw -m mark --mark 0x200/0xf00 -m comment --comment "cilium: NOTRACK for proxy traffic" -j NOTRACK
---
> -A CILIUM_OUTPUT_raw ! -s 10.35.8.54/32 -o lxc+ -m mark --mark 0xa00/0xfffffeff -m comment --comment "cilium: NOTRACK for proxy return traffic" -j NOTRACK
> -A CILIUM_OUTPUT_raw ! -s 10.35.8.54/32 -o cilium_host -m mark --mark 0xa00/0xfffffeff -m comment --comment "cilium: NOTRACK for proxy return traffic" -j NOTRACK
> -A CILIUM_PRE_raw ! -d 10.35.8.54/32 -m mark --mark 0x200/0xf00 -m comment --comment "cilium: NOTRACK for proxy traffic" -j NOTRACK
26,27c26,27
< -A CILIUM_PRE_mangle -p tcp -m mark --mark 0xd19c0200 -m comment --comment "cilium: TPROXY to host cilium-dns-egress proxy" -j TPROXY --on-port 40145 --on-ip 0.0.0.0 --tproxy-mark 0x200/0xffffffff
< -A CILIUM_PRE_mangle -p udp -m mark --mark 0xd19c0200 -m comment --comment "cilium: TPROXY to host cilium-dns-egress proxy" -j TPROXY --on-port 40145 --on-ip 0.0.0.0 --tproxy-mark 0x200/0xffffffff
---
> -A CILIUM_PRE_mangle -p tcp -m mark --mark 0xb9ab0200 -m comment --comment "cilium: TPROXY to host cilium-dns-egress proxy" -j TPROXY --on-port 43961 --on-ip 0.0.0.0 --tproxy-mark 0x200/0xffffffff
> -A CILIUM_PRE_mangle -p udp -m mark --mark 0xb9ab0200 -m comment --comment "cilium: TPROXY to host cilium-dns-egress proxy" -j TPROXY --on-port 43961 --on-ip 0.0.0.0 --tproxy-mark 0x200/0xffffffff
55,56c55,56
< -A CILIUM_INPUT -m mark --mark 0x200/0xf00 -m comment --comment "cilium: ACCEPT for proxy traffic" -j ACCEPT
< -A CILIUM_OUTPUT -m mark --mark 0xa00/0xfffffeff -m comment --comment "cilium: ACCEPT for proxy return traffic" -j ACCEPT
---
> -A CILIUM_INPUT ! -d 10.35.8.54/32 -m mark --mark 0x200/0xf00 -m comment --comment "cilium: ACCEPT for proxy traffic" -j ACCEPT
> -A CILIUM_OUTPUT ! -s 10.35.8.54/32 -m mark --mark 0xa00/0xfffffeff -m comment --comment "cilium: ACCEPT for proxy return traffic" -j ACCEPT
80a81,86
> -A CILIUM_POST_nat -s 10.35.8.0/24 ! -d 10.35.8.0/24 ! -o cilium_+ -m comment --comment "cilium masquerade non-cluster" -j MASQUERADE
> -A CILIUM_POST_nat ! -o cilium_host -m comment --comment "exclude non-cilium_host traffic from masquerade" -j RETURN
> -A CILIUM_POST_nat -m mark --mark 0xa00/0xe00 -m comment --comment "exclude proxy return traffic from masquarade" -j ACCEPT
> -A CILIUM_POST_nat ! -s 10.35.8.54/32 ! -d 10.35.8.0/24 -o cilium_host -m comment --comment "cilium host->cluster masquerade" -j SNAT --to-source 10.35.8.54
> -A CILIUM_POST_nat -s 127.0.0.1/32 -o cilium_host -m comment --comment "cilium host->cluster from 127.0.0.1 masquerade" -j SNAT --to-source 10.35.8.54
> -A CILIUM_POST_nat -o cilium_host -m mark --mark 0xf00/0xf00 -m conntrack --ctstate DNAT -m comment --comment "hairpin traffic that originated from a local pod" -j SNAT --to-source 10.35.8.54
```
the `CILIUM_POST_nat` rules are present in 1.7.6 but not in 1.8.1 

**General Information**

- Cilium version: 1.8.1
- Kernel version: 5.3.0-42-generic
- Orchestration system version in use: k8s 1.7.4
- Generate and upload a system zip: provided on slack to danwent
- MetalLB in BGP peering mode
- With kube-proxy

**How to reproduce the issue**

1. expose a service via externalip provided by metallb in bgp mode
2. curl the ip - if the pod behind the service is not on the same node that the traffic arrives on the request will time out

also discussed here: https://cilium.slack.com/archives/C1MATJ5U5/p1594932147133200

**Comment by brb** [comment]
@timricese Thanks for the issue. It seems that you are running with the BPF-based masquerading, and it's combination with kube-proxy does not support your use case.

Could you verify whether running Cilium with `config.bpfMasquerade=false` fixes the issue? Also, it would be interesting to know whether running w/o kube-proxy, but w/ BPF masquerading works in your case.

**Comment by timricese** [comment]
Hi!

Can confirm that config.bpfMasquerade=false fixes the issue!

I would be happy to try without kube-proxy but the https://docs.cilium.io/en/v1.8/gettingstarted/kubeproxy-free/ guide recommends for >1.16 installing without kube proxy (aka `kubeadm init --skip-phases=addon/kube-proxy`), .. would it still be advisable to remove kube-proxy  as documented for kubernetes <1.15 like this? ```kubectl -n kube-system delete ds kube-proxy
iptables-restore <(iptables-save | grep -v KUBE)```

**Comment by brb** [comment]
> would it still be advisable to remove kube-proxy as documented for kubernetes <1.15 like this? kubectl -n kube-system delete ds kube-proxy iptables-restore <(iptables-save | grep -v KUBE)

Yes, that would work too. Just make sure that you run the `iptables-restore <(iptables-save | grep -v KUBE)` cmd on each node. Thanks.

**Comment by timricese** [comment]
So i managed to remove kube-proxy etc and am testing now with bpfMasquerade=true. Unfortunately not working at all (with kube-proxy it would work if the traffic happened to arrive on the same node where an nginx-ingress pod was running).

tcpdump shows the packets arrive on the node via the interface used for bgp peering

Am now seeing from `cilium monitor --drop` however the following
```
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, identity 0->0: 10.28.2.2 -> 192.168.139.133 TimeExceeded(TTLExceeded)
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, identity 0->0: 10.28.2.2 -> 192.168.139.133 TimeExceeded(TTLExceeded)
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, identity 0->0: 10.28.2.2 -> 192.168.139.133 TimeExceeded(TTLExceeded)
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, identity 0->0: 10.28.2.2 -> 192.168.139.133 TimeExceeded(TTLExceeded)
```
the 192.168 address being my client, 10.28.2.2 being the node running `cilium monitor`

**Comment by brb** [comment]
Discussed offline: the problem in the kube-proxy free setup was that the ingress devices were missing in `global.devices`. Setting them fixed the issue.
