### ISSUE TITLE
Enforcement status of host policies is incorrect

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#12588]
Once host policies are loaded, they are always reported as `Enforced` in `kubectl describe ccnp ...`, regardless of whether they match the labels of the given node or whether the host firewall is disabled.

**How to reproduce the issue**

1. `kubectl create -f examples/policies/host/lock-down-ingress.yaml`
2. `kubectl describe ccnp lock-down-ingress`
```
$ kubectl describe ccnp lock-down-ingress | tail -n 15
      Type:  ingress-worker
Status:
  Nodes:
    k8s1:
      Enforcing:              true
      Last Updated:           2020-07-20T12:36:15.097795504Z
      Local Policy Revision:  4
      Ok:                     true
    k8s2:
      Enforcing:              true
      Last Updated:           2020-07-20T12:36:15.094067967Z
      Local Policy Revision:  4
      Ok:                     true
Events:                       <none>
```
If the host firewall is disabled or if the policy doesn't match the labels of the node, `Enforcing` should be `false`.

**Comment by aanm** [comment]
@pchaigno The logic should not be the one that what you are expecting. Similarly, a CNP will state "Enforcing: true" even if there are not endpoints that are being selected by such policy. The "Enforcing: true" field represents that a policy is currently being enforced in the agent, i.e., it's _acknowledged_ in the datapath regardless of its selection.

**Comment by pchaigno** [comment]
@aanm I see. Thanks for the clarification. Would it still make sense to report `false` if the host firewall is disabled?

**Comment by aanm** [comment]
@pchaigno it won't be worth it, for example, a single CCNP can have multiple policy rules in it and only one of those rules be a host network policy, should "Enforce" be set to `true` or `false`?

**Comment by pchaigno** [comment]
AFAIK, a CCNP cannot have both host policies and pod policies because you can only have one of `nodeSelector` or `endpointSelector`.
