### ISSUE TITLE
nat: Some ICMP entries are not GC'd

### ISSUE THREAD

**Issue by brb** [cilium/cilium#12625]
While doing some testing with the latest Cilium I've noticed that after running `cilium bpf ct flush global` some ICMP NAT entries were not garbage collected:
```
ICMP IN 192.168.34.12:0 -> 192.168.34.11:38193 XLATE_DST 192.168.34.11:38193 Created=6292sec HostLocal=1
ICMP OUT 192.168.34.11:38193 -> 192.168.34.12:0 XLATE_SRC 192.168.34.11:38193 Created=6292sec HostLocal=1
```

Previously, there was the following CT entry which got removed upon flush:

```
ICMP OUT 192.168.34.11:0 -> 192.168.34.12:38193 expires=16783063 RxPackets=0 RxBytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=1 TxBytes=50 TxFlagsSeen=0x00 LastTxReport=16783005 Flags=0x0000 [ ] RevNAT=0 SourceSecurityID=0 IfIndex=0
```

**Comment by ArthurChiao** [comment]
Hi @brb  any progress on this issue?

As discussed in slack, I noticed a similar problem: there are tons of (should-be-GC-ed ?) ICMP NAT records on my node, which summed up to `360K+` entries. Those entries are created several hours or even longer ago:

```shell
ICMP OUT 10.14.196.108:33567 -> 10.46.4.43:0 XLATE_SRC 10.14.196.108:33567 Created=81229sec HostLocal=1
ICMP OUT 10.14.196.108:44461 -> 10.46.4.43:0 XLATE_SRC 10.14.196.108:44461 Created=21709sec HostLocal=1
ICMP IN 10.46.4.43:0 -> 10.14.196.108:46141 XLATE_DST 10.14.196.108:46141 Created=83809sec HostLocal=1
...
```

* Cilium: 1.7.4
* Kernel: 4.19.118 mainline

**Comment by ArthurChiao** [comment]
The difference from yours is that, according to my test (just tested one node), these entries could be deleted by running `cilium bpf nat flush`. But the problem is that `flush` will break all existing connections?

**Comment by ArthurChiao** [comment]
Another phenomenon: i disabled `enable-health-check` and `enable-endpoint-health-check` on some nodes, but `cilium bpf nat list` shows that those nodes still actively do health checks to other nodes, thus still generating ICMP NAT entries.

**Comment by brb** [comment]
> Hi @brb any progress on this issue?

The fix is coming soon, but first I want to extend the CT unit tests.

> But the problem is that flush will break all existing connections?

Yes, it will break the existing connections which require SNAT (i.e. those which src IP/port was changed).

> i disabled enable-health-check and enable-endpoint-health-check on some nodes, but cilium bpf nat list shows that those nodes still actively do health checks to other nodes

Did you check that the health check packets are sent (e.g. tcpdump). Maybe they are leftover from previous health checks?

**Comment by ArthurChiao** [comment]
> Did you check that the health check packets are sent (e.g. tcpdump). Maybe they are leftover from previous health checks?

The ICMP packets could be captured with tcpdump. And double checked that they are not previously left by flushing the NAT entries and monitoring the NAT entry count.

Cilium status:

```shell
$ cilium status
KVStore:                Ok   etcd: 3/3 connected, ... - 3.2.24 (Leader)
Kubernetes:             Ok   1.17+ (v1.17.6-3) [linux/amd64]
Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Probe   [NodePort (SNAT, 30000-32767), ExternalIPs, HostReachableServices (TCP, UDP)]
Cilium:                 Ok      OK
NodeMonitor:            Listening for events on 32 CPUs with 64x4096 of shared memory
IPAM:                   IPv4: 2/255 allocated from xxx,
Controller Status:      19/19 healthy
Proxy Status:           OK, ip xxx, 0 redirects active on ports 10000-20000
Cluster health:         Warning   cilium-health daemon unreachable
```

@brb

**Comment by brb** [comment]
> The ICMP packets could be captured with tcpdump. And double checked that they are not previously left by flushing the NAT entries and monitoring the NAT entry count

Please create a separate issue for disabling `enable-health-check` and `enable-endpoint-health-check`.

**Comment by ArthurChiao** [comment]
Got it.
