### ISSUE TITLE
hubble/metrics: Add protocol labels to `flows_processed_total`

### ISSUE THREAD

**Issue by glibsm** [cilium/cilium#12656]
Unlike the drop metric, this one is not annotated with protocol.

There may be others that we want to include the protocol on as well.

**Comment by sayboras** [comment]
@glibsm Please find the list of metrics, which doesn't have protocol label currently. 

- dns_queries_total 
- dns_responses_total
- dns_response_types_total
- http_requests_total
- http_responses_total
- http_request_duration_seconds
- icmp_total
- tcp_flags_total

The metric names already implies which protocol is used, need your help to confirm if _protocol_ label is still needed for these metrics.

**Comment by glibsm** [comment]
> The metric names already implies which protocol is used, need your help to confirm if _protocol_ label is still needed for these metrics.

I think your summary is correct. There doesn't seem to be protocol ambiguity in that list. `flows_processed_total` on the other hand was squashing the protocols together making it hard to dissect what kind of traffic was actually being processed
