### ISSUE TITLE
node-port-acceleration for kernel bonded device

### ISSUE THREAD

**Issue by srinathhs** [cilium/cilium#12662]
## Proposal / RFE

**Is your feature request related to a problem?**
We have cilium setup on bare metal kubernetes cluster. The physical 10g Intel NIC's are bonded (static rr) for failover,
I am unable to set node port acceleration for bond0 as it is not yet supported.

**Describe the solution you'd like**

**Comment by brb** [comment]
>  I am unable to set node port acceleration for bond0 as it is not yet supported.

@srinathhs Could you share 1) your devices (`ip l`), 2) what cilium configuration did you use, 3) what exactly failed (probably cilium pod logs)?

**Comment by borkmann** [comment]
(needs kernel support for bonded devices for XDP)

**Comment by borkmann** [comment]
Fyi, native XDP support for bonding driver has been merged into net-next: https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=9e2ee5c7e7c35d195e2aa0692a7241d47a433d1e
