### ISSUE TITLE
How to test Kube-proxy removal performance benchmark?

### ISSUE THREAD

**Issue by yongming** [cilium/cilium#12701]
## Support
https://cilium.io/blog/2020/06/22/cilium-18#kubeproxy-removal
I found there are some performance testing bechmark on XDP/IPVS/IPTables. The testing result is very good. But there is no information of testing environment and testing tooling. Hope detail work node config(cpu/mem etc) and testcases can be provided.

Thanks.

**Comment by yongming** [comment]
I suppose the testing is run on a two core node with one direction request, right?

**Comment by borkmann** [comment]
> ## Support
> https://cilium.io/blog/2020/06/22/cilium-18#kubeproxy-removal
> I found there are some performance testing bechmark on XDP/IPVS/IPTables. The testing result is very good. But there is no information of testing environment and testing tooling. Hope detail work node config(cpu/mem etc) and testcases can be provided.

Hello, the blog post does have a detailled description of the test env, see the figure below the text on `Why does it matter?`. Let me know if you have any further questions beyond the setup stated there.

**Comment by yongming** [comment]
Get it, Thanks so much!
