### ISSUE TITLE
Cilium v1.7 unit test failure: ipcache_test.go:148

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12733]
https://travis-ci.com/github/cilium/cilium/builds/178015361

```
FAIL: ipcache_test.go:39: IPCacheTestSuite.TestIPCache

ipcache_test.go:148:

    c.Assert(cachedEndpointIPs, checker.DeepEquals, expectedIPList)

... obtained []string = []string{"127.0.0.1", "27.2.2.2"}

... expected []string = []string{"27.2.2.2", "127.0.0.1"}

... Unified diff:

--- obtained

+++ expected

@@ -1 +1 @@

-[]string{"127.0.0.1", "27.2.2.2"}

+[]string{"27.2.2.2", "127.0.0.1"}
```

Seen in #12731 but that test makes no changes to this file so it must be present on v1.7 branch.

**Comment by tklauser** [comment]
Fixed by #12734 (commit adac95f in `v1.7`) which was already merged. It seems Github only automatically closes issues based on `Fixes` tags when merged to the default branch.
