### ISSUE TITLE
docs: Extend kube-proxy-free GSG with guides for major managed k8s cloud providers

### ISSUE THREAD

**Issue by brb** [cilium/cilium#12740]
Extend the guide by adding instructions how to remove kube-proxy and use Cilium's kube-proxy replacement on the following platforms:

- [ ] GKE
- [ ] EKS
- [ ] AKS

**Comment by tklauser** [comment]
FWIW, [EKS](https://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/#nodeport-xdp-on-aws) and [AKS](https://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/#nodeport-xdp-on-azure) are already partially covered in the context of the _LoadBalancer & NodePort XDP Acceleration_ instructions in the kube-proxy-free GSG.

**Comment by borkmann** [comment]
@tklauser have a chance to help out on that? This would be awesome

**Comment by tklauser** [comment]
> @tklauser have a chance to help out on that? This would be awesome

Sure, I can give a hand. I assume it's best to work on this when we're doing the GSG review before the 1.9 release?
