### ISSUE TITLE
Host firewall in kube-proxy less mode breaks pod to remote-host pod connectivity

### ISSUE THREAD

**Issue by skmatti** [cilium/cilium#12759]
## Bug report

**General Information**

- Cilium version 1.8.2
- Kernel version 4.19.112
- Orchestration system version in use GKE 1.17.9

Some notable config:
```
cni-chaining-mode: generic-veth
masquerade: "false"
enable-bpf-masquerade: "false"
tunnel: disabled
kube-proxy-replacement: strict
enable-host-firewall: "true"
```

**How to reproduce the issue**

The issue can be reproduced with the above specified configuration and without having to create any host firewall policies.

Consider $SOURCE-POD-IP sends packet to $DEST-POD-IP on $REMOTE-NODE-IP.

The packet reaches the remote node but does not reach the destination pod.

The `cilium monitor` command on $REMOTE-NODE shows:
```
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, identity 0->0: $REMOTE-NODE-IP -> $SOURCE-POD-IP TimeExceeded(TTLExceeded)
```
The packet seems to be dropped on the way back but it never reached the actual pod (cilium monitor on this ep returns nothing). Also, NAT should not been required as pods are reachable.

**Comment by brb** [comment]
@skmatti Thanks for the report. Does the connectivity goes back to normal once you disable the host firewall feature?

**Comment by skmatti** [comment]
@brb thanks for responding. No, the connectivity is not restored even after disabling the host firewall and restarting the cilium agents.

I think the previous state in data plane is not cleared some how. I verified that a cluster bootstrapping to the same config (w/o host firewall) works fine. So, once host firewall is enabled with the aforementioned config it breaks the cluster irreversibly.

Would restarting the nodes clear the bpf scripts and maps in data plane ? Is there a way to regenerate the scripts ?

**Comment by joestringer** [comment]
> Also, NAT should not been required as pods are reachable.

AFAIK this is governed by the `native-routing-cidr` which you would need to configure to cover the CIDR range for directly routable traffic. (Though it doesn't make sense to me why any masquerade would be occurring if it's disabled in the configmap and you have restarted Cilium to ensure that the ConfigMap configuration is being respected)

**Comment by pchaigno** [comment]
**If I run without `global.cni.chainingMode=generic-veth`**, I'm unable to reproduce. I deployed Cilium 1.8.2 using the following command (per GKE GSG with host firewall-compatible options), then successfully deployed the connectivity check (which has multi-node checks).
```
helm install cilium ./cilium \
  --namespace cilium \
  --set global.nodeinit.enabled=true \
  --set nodeinit.reconfigureKubelet=true \
  --set nodeinit.removeCbrBridge=true \
  --set global.cni.binPath=/home/kubernetes/bin \
  --set config.ipam=kubernetes \
  --set global.nativeRoutingCIDR=$NATIVE_CIDR \
  --set global.hostFirewall=true \
  --set global.tunnel=disabled \
  --set config.blacklistConflictingRoutes=false \
  --set config.bpfMasquerade=false \
  --set global.masquerade=false \
  --set global.kubeProxyReplacement=strict \
  --set nodeinit.restartPods=true
```
So I'm guessing that the `chainingMode=generic-veth` setting is causing some bug here when used in combination with the host firewall. What CNI are you chaining Cilium with? Any chance you could include a sysdump of that environment?

> The packet reaches the remote node but does not reach the destination pod.

How did you establish that? Could you include `cilium monitor` output for the packet reaching the remote node? Are there any drops besides the one you reported in the original post? Can you see the packet in ingress policy verdicts of the host endpoint?

**Comment by skmatti** [comment]
The issue got resolved after I add `native-routing-cidr`.

Is this still needed if we are not using masquerade or bpfMasquerade?.

>> The packet reaches the remote node but does not reach the destination pod.

> How did you establish that? Could you include cilium monitor output for the packet reaching the remote node? Are there any drops besides the one you reported in the original post? Can you see the packet in ingress policy verdicts of the host endpoint?
I am able to see the packet on eth0 of the node but did not reach lxc interface for the pod. No other drops are seen. Also, I don't see policy verdict being applied on this packet(rightly so) if I enforce host firewall by creating a policy. But, the issue exists without any policies.

**Comment by skmatti** [comment]
We identified that this is a configuration issue with chaining mode. Once that is resolved, the issue seems to be fixed.

**Comment by jaygorrell** [comment]
Once what is resolved, exactly? What was the issue with chaining mode configuration?
