### ISSUE TITLE
Better feedback loop when compilation fails

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#128]
Due to the lack of the labels being available at network plumbing time. We have to request the labels asynchronously and then generate & compile the code after the container has already been started. If compilation or generation fails for some reason, we have no choice but to log the error in the logfile which is often not observed by the user. This leaves the user with an unconnected container.

Provide better feedback:
- Work on getting labels earlier and do generation synchronously when orchestration system asks for networking to be setup.
- Status field in cilium endpoint structure indicating the failure
- Consider delaying returning from networking call until labels have been retrieved

**Comment by aanm** [comment]
> Work on getting labels earlier and do generation synchronously when orchestration system asks for networking to be setup.
> 
> Consider delaying returning from networking call until labels have been retrieved

1) The last call libnetwork cilium driver makes to cilium daemon is the `EndpointJoin`. At that moment there isn't any linking between the container and the docker's network endpoint ID. Also, docker gets in a deadlock if I try to list the current containers while a plugin is setting up a vethpair for that new container endpoint.

``` go
// EndpointJoin sets up the endpoint working directory.
func (d *Daemon) EndpointJoin(ep types.Endpoint) error {
    cont, err := d.dockerClient.ContainerList(dTypes.ContainerListOptions{})
    // Docker is in a lock, so this call is waiting for its lock to be unlock which won't happen 
    if err != nil {
        log.Error("Error while getting a normal container list %s", err)
    }
    for _, c := range cont {
        log.Debugf("Container ID %s", c.ID)
        log.Debugf("Full container %+v", c)
    }
```

2) What happens if the labels' db is offline at the moment?

> Status field in cilium endpoint structure indicating the failure

I like this. This is better, when a user types `endpoint list` we would immediately see something like this:

```
$ cilium endpoint list
ENDPOINT ID   LABEL ID        LABELS (source:key[=value])   IPv6                     IPv4   
7406          Err-12                                 f00d::c0a8:210b:0:1cee 
$ cilium endpoint list 7406
ENDPOINT ID   LABEL ID        LABELS (source:key[=value])   IPv6                     IPv4   
7406          Err-12                                 f00d::c0a8:210b:0:1cee 
Errors found:
Err-12: Unable to get labels from current kv-store provider. See more details below.
7406-Status: Unable to retrieve last free Index: Get http://192.168.33.11:8500/v1/kv/cilium-net/operational/Labels/LastUUID?index=2543: dial tcp 192.168.33.11:8500: getsockopt: connection refused
```

**Comment by tgraf** [comment]
1. A status field is definitely needed to show which endpoints are connected and which are unconnected. Colors will help here. Upon inspect, more details can be provided such as the exact error log message. We can define a couple of well known error conditions such as error while obtaining label id or error while attaching the BPF program.
2. Additionally we need to report back into orchestration systems. I haven't checked CNI and what it allows to do there.
