### ISSUE TITLE
Clarify operator leader election event log for non-leaders

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12818]
This particular log does not use structured logs, meaning that the message itself contains variable text which changes the log for every instance of the log in a cluster:

https://github.com/cilium/cilium/blob/0dc3adc6388ad3ed83189f0b7b80a87afb77f1ac/operator/main.go#L250

We should fix it up to use `log.WithFields(...)` and in particular to make it very clear which structured field is the new leader vs. which field represents the current instance.

**Comment by chowmean** [comment]
Hi @joestringer, Do you mean to use something like this? 
```
log.WithFields(logrus.Fields{
			"new_leader": operatorID,
			"identity": identity,
		})
```

**Comment by joestringer** [comment]
@chowmean yeah, just like that.

**Comment by chowmean** [comment]
@joestringer I am on it.
