### ISSUE TITLE
Containers running with Minikube + Cilium Can't Reach the Outside World

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#1282]
This works on standard minikube: 

minikube start --memory 6000
kubectl create -f https://raw.githubusercontent.com/cilium/cilium/master/examples/minikube/demo.yaml
kubectl get pods
NAME                    READY     STATUS    RESTARTS   AGE
app1-4051634923-jj04m   1/1       Running   0          5m
app1-4051634923-x4fm3   1/1       Running   0          5m
app2-528805645-vkq9b    1/1       Running   0          5m
app3-640085774-64vct    1/1       Running   0          5m
kubectl exec -it app3-640085774-64vct /bin/bash
bash-4.3# ping 8.8.8.8                                                                                                          
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=61 time=8.76 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=61 time=9.50 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=61 time=9.10 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms

But it does not work on the minikube setup as describe in http://docs.cilium.io/en/latest/gettingstarted/#getting-started-using-kubernetes

minikube start --network-plugin=cni
kubectl create -f https://raw.githubusercontent.com/cilium/cilium/master/examples/minikube/cilium-ds.yaml
kubectl get pods -n kube-system
NAME                          READY     STATUS    RESTARTS   AGE
cilium-4b4mh                  1/1       Running   0          26m
cilium-consul-8sf5x           1/1       Running   0          26m
kube-addon-manager-minikube   1/1       Running   0          27m
kube-dns-1301475494-01m6m     3/3       Running   0          27m
kubernetes-dashboard-slwsg    1/1       Running   0          27m
kubectl create -f https://raw.githubusercontent.com/cilium/cilium/master/examples/minikube/demo.yaml
NAME                    READY     STATUS    RESTARTS   AGE
app1-4051634923-9dk3z   1/1       Running   0          16m
app1-4051634923-zbhn4   1/1       Running   0          16m
app2-528805645-hzdlr    1/1       Running   0          16m
app3-640085774-qnz56    1/1       Running   0          16m
bash-4.3# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 6182ms

Seems like perhaps there is some NAT behavior that works in the default minikube setup, but does not play nicely with Cilium.

**Comment by tgraf** [comment]
Very likely that the default minikube iptables rules conflict here.

**Comment by tgraf** [comment]
From @danwent:

@tgraf ok, it took some digging, but it seems like I can pass `--extra-config=kubelet.MakeIPTablesUtilChains=false`  to minikube.   The result are these iptables rules, suggesting that it did the trick:
```
$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */

Chain DOCKER (1 references)
target     prot opt source               destination        

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain KUBE-SERVICES (2 references)
target     prot opt source               destination
```
```
# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=59 time=9.649 ms
64 bytes from 8.8.8.8: seq=1 ttl=59 time=8.371 ms
64 bytes from 8.8.8.8: seq=2 ttl=59 time=9.775 ms
64 bytes from 8.8.8.8: seq=3 ttl=59 time=8.887 ms
```

TODO:
- [ ] Research if we can work around the standard kube-proxy iptables rules here
