### ISSUE TITLE
Filter cilium monitor/hubble observe by tcp flags 

### ISSUE THREAD

**Issue by jcodybaker** [cilium/cilium#12827]
The most meaningful packets of a TCP stream are the opening SYN/ACk and final FIN/RST.  For the cilium monitor/hubble observe CLIs (and companying APIs), it would reduce CPU load and visual noise to offer filtering by tcp flags.  

## Proposal / RFE

**Is your feature request related to a problem?**
The utility of cilium monitor/hubble observe is significantly lowered on a busy host.  Each packet adds non-trivial overhead, and in many cases the middle packets of a TCP stream add little value. 

We hope to use this functionality to build an audit log for egress-to-internet communication, but this functionality would seem to improve the utility of cilium monitor/hubble observe for many use cases.

**Describe the solution you'd like**
It would be desirable to be able to filter by TCP flags.  Even more so, it'd be ideal if this filtering was able to be accomplished within the BPF stack to avoid pushing unnecessary load to the userspace.

**Comment by nyrahul** [comment]
@jcodybaker @Rolinh I was badly in need of this filter. Hence I have taken a dig at it and got it working. However, wanted to confirm/cross-check with you the command-line rationale.

I have added a new `tcp-ctrl` filter in the protocols such that one can apply the filter in the following way:
```
hubble observe --protocol tcp-ctrl
```
using tcp-ctrl will show up only tcp packets with any of (SYN || FIN || RST || URG || ECE || CWR) flag set. TCP packets with just (ACK || PSH) flag set will be ignored with tcp-ctrl.

Sample Output:
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ hubble observe --protocol tcp-ctrl
TIMESTAMP             SOURCE                                     DESTINATION                                TYPE            VERDICT     SUMMARY
Aug 18 18:24:59.289   10.16.26.55:41116                          kube-system/coredns-567985b78-59x8m:8080   from-host       FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:24:59.289   10.16.26.55:41116                          kube-system/coredns-567985b78-59x8m:8080   to-endpoint     FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:24:59.289   kube-system/coredns-567985b78-59x8m:8080   10.16.26.55:41116                          from-endpoint   FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:24:59.289   kube-system/coredns-567985b78-59x8m:8080   10.16.26.55:41116                          to-stack        FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:25:00.867   10.16.26.55:53806                          kube-system/coredns-567985b78-59x8m:8181   from-host       FORWARDED   TCP Flags: SYN
Aug 18 18:25:00.867   10.16.26.55:53806                          kube-system/coredns-567985b78-59x8m:8181   to-endpoint     FORWARDED   TCP Flags: SYN
Aug 18 18:25:00.867   kube-system/coredns-567985b78-59x8m:8181   10.16.26.55:53806                          from-endpoint   FORWARDED   TCP Flags: SYN, ACK
Aug 18 18:25:00.867   kube-system/coredns-567985b78-59x8m:8181   10.16.26.55:53806                          to-stack        FORWARDED   TCP Flags: SYN, ACK
Aug 18 18:25:00.867   kube-system/coredns-567985b78-59x8m:8181   10.16.26.55:53806                          from-endpoint   FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:25:00.867   kube-system/coredns-567985b78-59x8m:8181   10.16.26.55:53806                          to-stack        FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:25:00.867   10.16.26.55:53806                          kube-system/coredns-567985b78-59x8m:8181   from-host       FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:25:00.867   10.16.26.55:53806                          kube-system/coredns-567985b78-59x8m:8181   to-endpoint     FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:25:09.290   10.16.26.55:41142                          kube-system/coredns-567985b78-59x8m:8080   from-host       FORWARDED   TCP Flags: SYN
Aug 18 18:25:09.290   10.16.26.55:41142                          kube-system/coredns-567985b78-59x8m:8080   to-endpoint     FORWARDED   TCP Flags: SYN
Aug 18 18:25:09.290   kube-system/coredns-567985b78-59x8m:8080   10.16.26.55:41142                          from-endpoint   FORWARDED   TCP Flags: SYN, ACK
Aug 18 18:25:09.290   kube-system/coredns-567985b78-59x8m:8080   10.16.26.55:41142                          to-stack        FORWARDED   TCP Flags: SYN, ACK
Aug 18 18:25:09.290   kube-system/coredns-567985b78-59x8m:8080   10.16.26.55:41142                          from-endpoint   FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:25:09.290   kube-system/coredns-567985b78-59x8m:8080   10.16.26.55:41142                          to-stack        FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:25:09.290   10.16.26.55:41142                          kube-system/coredns-567985b78-59x8m:8080   from-host       FORWARDED   TCP Flags: ACK, FIN
Aug 18 18:25:09.290   10.16.26.55:41142                          kube-system/coredns-567985b78-59x8m:8080   to-endpoint     FORWARDED   TCP Flags: ACK, FIN
```

Does this make sense?

**Comment by nyrahul** [comment]
On second thought, I changed the cli interface to following:
```
hubble observe --protocol tcp:SYN,FIN
```
results in TCP packets getting shown which has SYN and FIN bit set.

Possible flags(case-insensitive) are `SYN,FIN,RST,URG,ECE,CWR,NS,ACK,PSH`. If no flags are specified i.e., only `--protocol tcp` is specified then it results in current/default behavior of show all tcp packets.

**Comment by gandro** [comment]
@nyrahul Awesome! I do like your second proposal `--protocol tcp:SYN,FIN`. Thanks a lot for the input, your use-case about filtering out ACK/PSH makes a ton of sense to me.

So I think there are two discussion points here.

1. How to implement TCP filtering in the API.
2. How to expose TCP filtering in the CLI flags.

The first one is important because upcoming versions of Hubble UI already supports client-side TCP-flags filtering. So if we add the same functionality server-side, we want to make sure our API covers the UI use-case and the use-case presented in this thread. It does look like your implemention seems to do the same. Still, I'm curious how implemented this in the gRPC API e.g. in `message FlowFilter`?

Or is this a client-side (CLI) only implemention? Because I do believe we should add this server-side.

**Comment by nyrahul** [comment]
@gandro thanks for the feedback. I pushed my commit which shows how this is implemented in flow filter. Please check if this is as per expected for Hubble UI. If not, I can update/align the changes as per expected. Should I raise a draft PR for this?

**Comment by gandro** [comment]
Thanks for the PR! I have left some thoughts inline, but for cross-reference, I'll link it here as well: https://github.com/cilium/cilium/pull/12932#discussion_r473977129
