### ISSUE TITLE
"kubectl get networkpolicies" doesn't show applied policy

### ISSUE THREAD

**Issue by techcet** [cilium/cilium#1285]
Steps to reproduce:
Cynthias-MBP:demo cynthiathomas$ kubectl apply -f default-allow-policy.yaml
ciliumnetworkpolicy "xxx-cilium-policy-default-allow" configured

Cynthias-MBP:demo cynthiathomas$ kubectl get networkpolicies
No resources found.

But cilium sees the policy:

Cynthias-MBP:demo cynthiathomas$ kubectl exec -it cilium-9kmtk -n kube-system /bin/bash
root@ip-172-0-41-235:/# cilium policy get                                                                                                                                                  
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "staging"
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "k8s:io.kubernetes.pod.namespace": "staging"
            }
          }
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "9080",
                "protocol": "TCP"
              }
            ],
            "rules": {
              "http": [
                {
                  "path": ".*",
                  "method": "GET"
                }
              ]
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s-policy-name",
        "value": "covalent-cilium-policy-default-allow",
        "source": "unspec"
      }
    ]
  }
]
Revision: 9

**Comment by tgraf** [comment]
You seem to have applied a `CiliumNetworkPolicy`. They are different from `NetworkPolicy`.

- To retrieve `CiliumNetworkPolicy`: `kubectl get ciliumnetworkpolicies`
- To retrieve `NetworkPolicy`: `kubectl get networkpolicies`

**Comment by techcet** [comment]
Thank you!
