### ISSUE TITLE
Enabling Layer7 Visibility while installing cilium

### ISSUE THREAD

**Issue by vishnugs** [cilium/cilium#12855]
Proposal

**Is your feature request related to a problem?**
In kubernetes pods keeps changing/reinstalled . 
Problem is facing with manual annotation of the pod for the L7 visibility.

 **enable l7 protocol visibiltiy by default during cilium installation (by setting some config for automatic annotation)**
If not, does it needs to be done always on any pod addition?
**Describe the solution you'd like**
Would like to have automatic annotation for Layer 7 visibility. For now i have to go on each pod to enable the same.

**Comment by vishnugs** [comment]
Hi, Please let me know when it can be addressed.

**Comment by Rolinh** [comment]
Hi @vishnugs,

Related: there's an open RFC PR by @christarazi which implements policy-free DNS visibility: https://github.com/cilium/cilium/pull/13260

> In kubernetes pods keeps changing/reinstalled .
Problem is facing with manual annotation of the pod for the L7 visibility.

I guess this wouldn't be a problem if you annotate the deployment, right? Or is there a reason you can't add custom annotations?
