### ISSUE TITLE
Verify CCNP with toGroups

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#12857]
Something tells me they won't work... This function is used for both CCNP and CNP. If a CCNP has a `toGroups` field, it will create a derivative CNP, not a derivative CCNP.

https://github.com/cilium/cilium/blob/5d1025eda37fa8bdfebddc4b413b143113e06a09/pkg/policy/groups/actions.go#L130-L177

**Comment by fristonio** [comment]
Verified the issue. We currently don't handle this correctly, for CCNP also we try to create a derivative CNP. I am testing out a patch to fix this.
