### ISSUE TITLE
Selectorless Service manual endpoints not reflected in cilium

### ISSUE THREAD

**Issue by cehoffman** [cilium/cilium#12876]
## Bug report

**General Information**

- Cilium version (run `cilium version`)

Client: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
Daemon: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64

- Kernel version (run `uname -a`)

Linux k8s-worker-1 5.7.10-201.fc32.x86_64 #1 SMP Thu Jul 23 00:58:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

Kubernetes v1.18.6

- Link to relevant artifacts (policies, deployments scripts, ...)

Zalando Postgres Operator minimal DB instance

```sh
kubectl apply -k github.com/zalando/postgres-operator/manifests
kubectl apply -f https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/minimal-postgres-manifest.yaml
```
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

[cilium-sysdump-20200813-131937.zip](https://github.com/cilium/cilium/files/5070760/cilium-sysdump-20200813-131937.zip)

**How to reproduce the issue**

```sh
kubectl apply -k github.com/zalando/postgres-operator/manifests
kubectl apply -f https://raw.githubusercontent.com/zalando/postgres-operator/master/manifests/minimal-postgres-manifest.yaml
```

The setup will fail because the operator can not reach the master postgres instance behind the `acid-minimal-cluster` service whose endpoint is managed by the operator. The endpoint will exist and point to one of the statefulset pods. If you list the service from `cilium service list` it does not show the acid-minimal-cluster service.

**Comment by brb** [comment]
@cehoffman Duplicate of https://github.com/cilium/cilium/issues/12513?

**Comment by cehoffman** [comment]
Yep, I think so. I tried searching for the feature but didn’t try the exact components hah. Well fun bug in k8s then.
