### ISSUE TITLE
test flake: 18-kvstore-fail.sh failure in master build

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1287]
A [build of master](https://jenkins.cilium.io/job/cilium/job/cilium/job/master/517/console) failed during the newly added kv-store test:
```
22:09:29 ==> cilium-master-build-master-517: time="2017-08-09T15:09:29-07:00" level=info msg="Waiting for consul client to be ready..." 
22:09:31 ==> cilium-master-build-master-517: time="2017-08-09T15:09:31-07:00" level=info msg="Waiting for consul client to be ready..." 
22:09:34 ==> cilium-master-build-master-517: time="2017-08-09T15:09:33-07:00" level=info msg="Waiting for consul client to be ready..." 
22:09:35 ==> cilium-master-build-master-517: ------------------------------------------------------------------------
22:09:35 ==> cilium-master-build-master-517:                             Test Failed
22:09:35 ==> cilium-master-build-master-517: Waiting for agent process to be killed, timed out
22:09:35 ==> cilium-master-build-master-517: 
22:09:35 ==> cilium-master-build-master-517: ------------------------------------------------------------------------
```

**Comment by aalemayhu** [comment]
Not so familiar with the k8s runtime tests. Is there any difference between the expected time-out for k8s? Can look closer into this tonight.

**Comment by ianvernon** [comment]
Ah, I pasted the combined Console Output. The step of the build that failed was the Runtime Tests, not the K8s tests - https://jenkins.cilium.io/job/cilium/job/cilium/job/master/517/execution/node/28/log/ has the logs for the Runtime Tests, which is when `18-kvstore-fail` test ran.

**Comment by aalemayhu** [comment]
I suspect this is a timing issue. We could bump the wait time to 240, but will try reproducing it first.
What do you think @ianvernon?

**Comment by ianvernon** [comment]
Can you elaborate on the timing issue?
