### ISSUE TITLE
[Azure -AKS] Cilium Operator Failing 

### ISSUE THREAD

**Issue by vishnugs** [cilium/cilium#12875]
## Bug report

**General Information**

- Cilium version (run `cilium version`) : 1.8.2 
- Kernel version (run `uname -a`)  : 4.15.0-1091-azure
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) : Kubernetes 
- Link to relevant artifacts (policies, deployments scripts, ...) https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-aks/
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Setup Managed Cluster in AKS 
2. Created CNI Chaining as per url above 

Cilium operator is failing with following lgos
level=info msg="  --version='false'" subsys=cilium-operator-azure
level=info msg="Cilium Operator 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64" subsys=cilium-operator-azure
level=info msg="Starting apiserver on address 127.0.0.1:9234" subsys=cilium-operator-azure
level=info msg="Establishing connection to apiserver" host="https://10.0.0.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=fatal msg="cluster-pool allocator is not supported by this version of cilium-operator-azure" subsys=cilium-operator-azure

Havent changed anything extra. 

Helm command used 

helm install cilium cilium/cilium --version 1.8.2 \ --namespace cilium \ --set global.cni.chainingMode=generic-veth \ --set global.cni.customConf=true \ --set global.nodeinit.enabled=true \ --set global.azure.enabled=true \ --set global.cni.configMap=cni-configuration \ --set global.tunnel=disabled \ --set global.masquerade=false

**Comment by vishnugs** [comment]
After remove -azure from the image and command for the cilium operator it started running

**Comment by sayboras** [comment]
@vishnugs seems fixed in https://github.com/cilium/cilium/pull/13024. Please give it a try whenever you have time. Thanks.

**Comment by vishnugs** [comment]
@sayboras , Thanks for updating. Will check it out.!!
