### ISSUE TITLE
Verify ipcache correctness if a pod changes its IP address

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#12914]
Pods in hostNetwork can change their IP address if the node change its IP address. We need to be sure that we are handling that behavior in the k8s events and have the ipcache up to date with the most recent IP address.

**Comment by errordeveloper** [comment]
@fristonio are you still keeping this on your radar?

**Comment by fristonio** [comment]
Thanks for bringing this to attention again, I missed tracking this somehow. I will try to take this up sometime this week.

**Comment by aanm** [comment]
fixed by https://github.com/cilium/cilium/pull/15803
