### ISSUE TITLE
Why not use veth native xdp for network policy

### ISSUE THREAD

**Issue by firemiles** [cilium/cilium#12910]
Hello everyone. I am a kubernetes developer and use cilium as cluster network controller. 

I found cilium use **ebpf** replace iptables. It is fast. But I am confusing why use **tc** to implement network policy, not **xdp**. now **veth pair** support **native xdp**, if we put the policy into native xdp, I think the performance will be better.

**Comment by borkmann** [comment]
> But I am confusing why use **tc** to implement network policy, not **xdp**. now **veth pair** support **native xdp**, if we put the policy into native xdp, I think the performance will be better.

Do you mean for the egress side from a Pod, or ingress traffic into a Pod? egress traffic from a Pod won't bring much given the kernel's stack allocates an skb already which we're operating on at this point. For the ingress side, meaning, external traffic into the machine, it's on our todo to enforce/'offload' policy into the phys devs XDP program (but not veth one). (Cc @pchaigno )

**Comment by pchaigno** [comment]
> it's on our todo to enforce/'offload' policy into the phys devs XDP program (but not veth one). (Cc @pchaigno )

Cf. https://github.com/cilium/cilium/issues/12604.

**Comment by firemiles** [comment]
@pchaigno @borkmann thks for your answer. enforce ingress policy into the phys devs XDP program is a good idea.

**Comment by borkmann** [comment]
> In the case of veth, some of TCP packets (for example, TCP retransmission flags are set) bypass XDP because the Linux virtual network interface driver's packet processing logic is implemented in such a way. Thus, while we may be able to enforce network policies for non-TCP packets using XDP, it would increase the complexity of the policy enforcement process and would reduce the overall performance due to duplicated policy matching processes.

Right, it makes only sense for native phys devs when the packet comes in from external. From inside the host we already have a skb at this point, so XDP wouldn't buy anything in that case but rather as you say make it more complex.

**Comment by firemiles** [comment]
@sdxdata you said native veth will by pass TCP retransmission. This behavior is import for me, but I look into veth driver not found the logical code. Could you point me where is the related code snippet in kernel?

**Comment by sdxdata** [comment]
@firemiles It would totally depend on the kernel version that you use. You can check the kernel code (netif_receive_generic_xdp() in /net/core/dev.c). When I quickly looked through the kernel code changes, it seemed that that situation happens by kernel v5.5, but it is patched after kernel v5.6.

**Comment by firemiles** [comment]
> @firemiles It would totally depend on the kernel version that you use. You can check the kernel code (netif_receive_generic_xdp() in /net/core/dev.c). When I quickly looked through the kernel code changes, it seemed that that situation happens by kernel v5.5, but it is patched after kernel v5.6.
@sdxdata  Thks，I think I got the patch [commit](https://github.com/torvalds/linux/commit/ad1e03b2b3d4430baaa109b77bc308dc73050de3) by your point.

**Comment by borkmann** [comment]
> > It would totally depend on the kernel version that you use. You can check the kernel code (netif_receive_generic_xdp() in /net/core/dev.c). When I quickly looked through the kernel code changes, it seemed that that situation happens by kernel v5.5, but it is patched after kernel v5.6.
> 
> @sdxdata Thks，I think I got the patch [commit](https://github.com/torvalds/linux/commit/ad1e03b2b3d4430baaa109b77bc308dc73050de3) by your point.

This is talking about generic XDP though which we're not using given its limitations. It would make the datapath slower. See also our recent plumbers presentation where I've mentioned rationale: https://linuxplumbersconf.org/event/7/contributions/674/attachments/568/1002/plumbers_2020_cilium_load_balancer.pdf
