### ISSUE TITLE
Cilium API with tcp mode similar to Docker API

### ISSUE THREAD

**Issue by myugan** [cilium/cilium#12924]
## Proposal / RFE

**Is your feature request related to a problem?**

Yes, in some cases I need to use TCP mode instead of socket because it's difficult to integrate with Python or other languages, as we know cilium just has a library in Golang not support with other languages.

**Describe the solution you'd like**

Do you have any plan to implement these things similar to Docker API? Cilium also can provide TCP or HTTP API it will easier to use in other languages.

**Comment by aanm** [comment]
@myugan you can access Cilium via its unix domain socket, there's no need to expose it as a TCP socket. Curl example:
```
$ curl --unix-socket /var/run/cilium/cilium.sock -H "Brief:true" http://localhost//v1/healthz
{"cilium":{"msg":"OK","state":"Ok"},"cluster":{"ciliumHealth":{"state":"Ok"},"nodes":null}}
```

**Comment by myugan** [comment]
Okay @aanm maybe some information about this must be add to documentation such as how to request manually to cilium socket with curl, also other parameter to make PUT, GET, DELETE requests. Thanks in advance

**Comment by myugan** [comment]
i got an error when apply policy with those comment but with PUT requests, also i use example of policy in documentation.

```
{"code":400,"message":"parsing policy body from \"\" failed, because json: cannot unmarshal array into Go value of type string"}
```
