### ISSUE TITLE
Cilium not shared the policy between nodes

### ISSUE THREAD

**Issue by myugan** [cilium/cilium#12934]
## Support

I use `etcd 3.4.10` as KVStore in Cilium, when applying policy with the command `cilium policy import default.json`  I guess the policy shared to each node when checking it in other nodes that connect to 1 etcd leader (same etcd) it's not shown any policy like on master node.

`cilium version`:
```
Client: 1.7.7 88ecd7f46 2020-08-14T17:19:15+02:00 go version go1.14.3 linux/amd64
Daemon: 1.7.7 88ecd7f46 2020-08-14T17:19:15+02:00 go version go1.14.3 linux/amd64
```

**Comment by aanm** [comment]
@myugan Currently Cilium does not distribute the policies across nodes, that can only be done through Kubernetes.

**Comment by joestringer** [comment]
@myugan I'm not aware of any plans to do so, most users are running Kubernetes. Given sufficient interest I think that it would be reasonable for someone to add such functionality and we would welcome such PR submissions.

**Comment by myugan** [comment]
Hi @aanm as you said this is can only be done through Kubernetes, is it use etcd to put those policies?

**Comment by aanm** [comment]
@myugan with Kubernetes you can install Cilium Network Policies which are distributed for all nodes.
