### ISSUE TITLE
Conflicting endpoint when complete Job pod shares IP with an active pod

### ISSUE THREAD

**Issue by excieve** [cilium/cilium#12953]
## Bug report
After launching our new EKS clusters with Cilium + AWS CNI in chaining mode we noticed that some packets are being dropped supposedly due to a "policy deny". Thing is the flows in question are actually allowed by the network policy, moreover other pods of the same (and other) workload affected by this policy are communicating just fine.

While troubleshooting we found that the destination/source pods sometimes didn't have an endpoint associated with `hubble observe` just showing the pod IP. So that's the immediate reason why traffic gets dropped. However, it wasn't clear why no endpoint is associated provided we can successfully get "allowed" conclusion when doing `cilium policy trace` using pod names as source and destination with all the labels correctly detected. Also sometimes we'd see correct behaviour on the same pods after restarting Cilium.

Sometimes Cilium restart wouldn't help though, so we started digging deeper. Accidentally we found that k8s `Job` and `CronJob` resources in the cluster leave a trail of "complete" pods (which is the default k8s behaviour to keep history of successful and failed jobs). Although the pods aren't live their specs still have IPs recorded from when they were running. Suspiciously, some of the IPs matched the IPs of the pods that had issues with erroneous network policy deny cases.

We manually deleted the inactive job pods, then restarted Cilium and all the flows started working again, endpoints correctly showing up too. Simply deleting the pods didn't work without restart. K8s removing them eventually also doesn't affect the colliding pod until Cilium is restarted.

This is quite problematic since we're running lots of jobs frequently and our workloads are fairly dynamic — getting created and restarted all the time. The more different jobs we run (and they scale along with the workloads related to this), the higher probability of having an IP collision. So this issue is basically a multiple times a day recurrence.

I believe Cilium should ignore IPs of inactive job pods when building the IP -> endpoint cache.

In the meantime, is there a workaround for this? Would running Cilium with ENI IPAM work better than chaining?

**General Information**

- Cilium version:
```
Client: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
Daemon: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
```
- Kernel version: `4.14.186-146.268.amzn2.x86_64`
- Orchestration system version in use:
```
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

This is what I think is the way to reproduce, but obviously there's a stochastic element to which IPs get allocated:
1. Use AWS CNI chaining (not entirely sure this is required)
2. Launch 50 k8s jobs each running a couple of times until there are 100-200 inactive job pods
3. Launch 20-30 workload pods
4. Set up a `NetworkPolicy` to deny all traffic between the workloads
5. Set up a `NetworkPolicy` to allow some traffic between the workloads (e.g. a specific port ingress and egress)
6. Observe some pods having no communication issues, while others timeout (if an inactive job pod IP got allocated to a workload pod)

**Comment by aanm** [comment]
@excieve thanks GH issue. We will take a look.
