### ISSUE TITLE
Enabling ipsec encryption in EKS causes node to node traffic to break

### ISSUE THREAD

**Issue by allanyung** [cilium/cilium#12955]
## Bug report

**General Information**

- Cilium version: 1.8.2
- Kernel version: 4.14.186-146.268.amzn2.x86_64
- Orchestration system version in use: v1.17.9-eks-4c6976

Enabling ipsec encryption causes node to node traffic to break. This happens in both `aws-eni` mode, and in `cni-chaining` mode. Disabling encryption restores connectivity between the nodes.

**How to reproduce the issue**

Create the `cilium-ipsec-keys` Secret

```bash
kubectl create -n kube-system secret generic cilium-ipsec-keys --from-literal=keys="3 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null| xxd -p -c 64)) 128"
```

Install cilium with the following Helm chart `values.yaml` onto an EKS cluster

```yaml
global:
  masquerade: false

  tunnel: disabled

  cni:
    chainingMode: aws-cni

  encryption:
    enabled: true
    nodeEncryption: false

  nodeinit:
    enabled: true
```
Enabling `nodeEncryption` doesn't resolve the issue.

The connectivity test shows something strange (there are no Network Policies other than those created by the test)

```
NAME                                                     READY   STATUS    RESTARTS   AGE
echo-a-58dd59998d-xhrff                                  1/1     Running   0          3m47s
echo-b-865969889d-77b96                                  1/1     Running   0          3m46s
echo-b-host-659c674bb6-fdwkn                             1/1     Running   0          3m46s
host-to-b-multi-node-clusterip-6fb94d9df6-sjsp9          1/1     Running   0          3m46s
host-to-b-multi-node-headless-7c4ff79cd-x6p2k            1/1     Running   0          3m46s
pod-to-a-5c8dcf69f7-765vz                                1/1     Running   0          3m46s
pod-to-a-allowed-cnp-75684d58cc-bl59z                    0/1     Running   0          3m46s
pod-to-a-external-1111-669ccfb85f-xfj2l                  1/1     Running   0          3m45s
pod-to-a-l3-denied-cnp-7b8bfcb66c-qcx2v                  1/1     Running   0          3m46s
pod-to-b-intra-node-74997967f8-rjvhp                     1/1     Running   0          3m46s
pod-to-b-intra-node-nodeport-775f967f47-ggld7            1/1     Running   0          3m46s
pod-to-b-multi-node-clusterip-587678cbc4-nmgts           1/1     Running   0          3m45s
pod-to-b-multi-node-headless-574d9f5894-xbpkr            1/1     Running   0          3m45s
pod-to-b-multi-node-nodeport-7944d9f9fc-sh9qh            1/1     Running   0          3m45s
pod-to-external-fqdn-allow-google-cnp-6dd57bc859-h76jk   1/1     Running   0          3m44s
```
`cilium-health status` suggests things are fine

```
Nodes:
  ip-10-1-155-156.eu-central-1.compute.internal (localhost):
    Host connectivity to 10.1.155.156:
      ICMP to stack:   OK, RTT=114.537µs
      HTTP to agent:   OK, RTT=187.031µs
  ip-10-1-30-74.eu-central-1.compute.internal:
    Host connectivity to 10.1.30.74:
      ICMP to stack:   OK, RTT=894.978µs
      HTTP to agent:   OK, RTT=917.123µs
  ip-10-1-69-144.eu-central-1.compute.internal:
    Host connectivity to 10.1.69.144:
      ICMP to stack:   OK, RTT=573.843µs
      HTTP to agent:   OK, RTT=751.594µs
```

[cilium-sysdump-20200821-102421.zip](https://github.com/cilium/cilium/files/5117542/cilium-sysdump-20200821-102421.zip)

The sysdump shows the 2 `Gateway` Pods in the `openfaas` namespace are in CrashLoop. They attempt to connect to the `nats` service on startup, but fail because they are on different Nodes to the `nats` Pod. The `queue-worker` Pod also connects to `nats` on startup, but in this case succeeds because it is on the same Node as the underlying `nats` Pod

This is a test cluster so we're able to do whatever is needed to investigate further.

**Comment by pchaigno** [comment]
@allanyung Are you still able to reproduce with v1.9.7 or v1.10.0? We have fixed a lot of IPsec issues when running EKS in the recent versions.

**Comment by pchaigno** [comment]
It seems I missed before that the issue happens in chaining mode. This is expected as IPsec is not supported in that setup, as documented at https://docs.cilium.io/en/latest/gettingstarted/encryption-ipsec/#limitations.
