### ISSUE TITLE
Add documentation for io.cilium/shared-service

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#12958]
The current clustermesh documentation doesn't describe the shared-service annotation or how it can be used. The code comments describe what it does, but users are not likely to look there. It would likely make sense to add a short section to address this in the docs.

**Comment by chowmean** [comment]
Hi @joestringer, I would like to take this up. Can you please point me to the code section?

**Comment by joestringer** [comment]
Awesome, @chowmean ! Here's the relevant code (found via `git grep shared-service`):

https://github.com/cilium/cilium/blob/cf5f475eab64680045bdce05da4274fcbe077c7e/pkg/annotation/k8s.go#L56-L61
