### ISSUE TITLE
Clean up hostscope-legacy ipam option

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#12974]
Related to https://github.com/cilium/cilium/blob/master/pkg/ipam/option/option.go#L18-L20

**Comment by sayboras** [comment]
@tklauser just want to check with you if we can remove this option for 1.9 preparation. Currently, this `hostscope-legacy` is still used as default value, will the new default value for ipam option be `cluster-pool` ? Thanks.

**Comment by tklauser** [comment]
I'm not entirely sure what the new default options should be as I'm not terribly familiar with the different IPAM modes. FWIW, this was deprecated in #10407, so pinging @tgraf and @aanm who might be able to say more.
