### ISSUE TITLE
Setting devices breaks ipsec

### ISSUE THREAD

**Issue by tobiaskohlbau** [cilium/cilium#13027]
## Bug report

If run in `kube-proxy-replacement: probe` or `kube-proxy-replacement: disabled` mode in combination with `enable-ipsec` and selected `devices` it looks like `bpf_host` is overriding `bpf_network` which results in the receiving node not being able to decrypt the ESP packets.

**General Information**

- Cilium version (run `cilium version`)
> 1.8.2
- Kernel version (run `uname -a`)
> Linux node1 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
> 1.19

**How to reproduce the issue**

1. Create K8S cluster with for e.g. version 1.19
2. Deploy cilium with `kube-proxy-replacement: disabled`/`kube-proxy-replacement: probe`, `enable-ipsec` and `devices: enp1s0,enp7s0`.
3. Inspect the tc filter chain on one of the nodes `tc filter show dev enp7s0 ingress`.

Expectation: 
```
filter protocol all pref 1 bpf chain 0
filter protocol all pref 1 bpf chain 0 handle 0x1 bpf_network.o:[from-network] direct-action not_in_hw id 9122 tag e74cd2a91d9265f8 jited
```

Observed: 
```
filter protocol all pref 1 bpf chain 0
filter protocol all pref 1 bpf chain 0 handle 0x1 bpf_netdev_enp7s0.o:[from-netdev] direct-action not_in_hw id 9498 tag 57b67d5dbedda604 jited
```

```
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.19 (v1.19.0) [linux/amd64]
Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled   [enp1s0, enp7s0]   []
Cilium:                 Ok         OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok
IPAM:                   IPv4: 5/255 allocated from 10.129.4.0/24,
Masquerading:           IPTables
Controller Status:      32/32 healthy
Proxy Status:           OK, ip 10.129.4.56, 0 redirects active on ports 10000-20000
Hubble:                 Disabled
Cluster health:         9/9 reachable   (2020-08-31T17:01:56Z)
```

Many thanks to @pchaigno for helping me debug this issue and pointing me in the right direction to remove the devices list in order to get the ESP pakets decrypted.

**Comment by pchaigno** [comment]
I think we want to fatal if IPSec is enabled while the devices are set to prevent this from happening. This issue should only happen if a user sets the devices explicitly (e.g., because we failed to auto-detect) as we otherwise automatically disable our kube-proxy replacement when IPSec is enabled (with a warning in case of `=probe` and a fatal in case of `=strict`).

We should also disable the bandwidth manager if IPSec is enabled. Host firewall is already disabled in that case.

/cc @brb @borkmann

**Comment by brb** [comment]
@pchaigno SGTM!

**Comment by tobiaskohlbau** [comment]
I would like to work on this. Feel free to assign this issue to myself.
