### ISSUE TITLE
Backport smoketest in master to 1.8

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#13020]
There are a few things related to smoke test got introduced after 1.8:
- IPv4 Multi-node cluster
- IPv6 only multi-node cluster

The above can be considered to be backported to 1.8 branch. This will help with recent changes for HA operator, which requires multi node cluster.

Related PR comment https://github.com/cilium/cilium/pull/13004#issuecomment-682606753

/cc @aanm @kAworu

**Comment by joestringer** [comment]
Do you mean that we hope that we can validate the HA operator behaviour on v1.8 with more certainty if we backport the smoketest, therefore we should do so?

Basically I'm wondering what the difference is between running such tests against master (where all code lands, including fixes that will be backported) vs. on the v1.8 branch (where the actual code for v1.8.x releases lives, so we know we're testing the full same paths).

**Comment by kAworu** [comment]
I am neutral about this am not familiar with the smoke tests. The only reason I've been ignoring smoke test related diff from #13004 was because the goal was backporting https://github.com/cilium/cilium/pull/12948 (which is unrelated to smoke tests).

**Comment by sayboras** [comment]
Thanks for your comment, consider that there is flake in #12279, I just park this issue here till flake is resolved, and also can hear from others well.

**Comment by sayboras** [comment]
Closing this one, I think the current smoke test setup with master + 1.9 is good enough.
