### ISSUE TITLE
Add ability to specify GRPC port and namespace to helm charts

### ISSUE THREAD

**Issue by tom-hadlaw-hs** [cilium/cilium#13026]
Currently to run hubble using a non standard GRPC port and namespace you need to generate the charts via helm and make the changes manually to the output. It would be helpful if these where exposed configuration variables.

**Comment by gandro** [comment]
Transferred from `ciilum/hubble`, as the Helm charts now live in this repository.

**Comment by kAworu** [comment]
The gRPC port may be set through Helm (see `.Values.global.hubble.listenAddress`) and the namespace is the same as cilium (also configurable via Helm) so both point raised by this issue have been addressed.

**Comment by gandro** [comment]
For future reference: To change the ports on the `hubble-relay` service, we also have the `hubble-relay.listenPort` and `hubble-relay.servicePort` Helm values.
