### ISSUE TITLE
Provide stable URL for stable release tarballs

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1303]
- [ ] Setup URL
- [ ] Change guides to use stable releases via URL

**Comment by aalemayhu** [comment]
@tgraf Could we use an S3 bucket and setup a DNS entry for releases.cilium.io? This way we would just need to focus on the directory / file layout and if we ever want a separate website on releases.cilium.io it could read from the bucket. Should also be straightforward to reuse or write a script that uploads there. wdyt?

**Comment by tgraf** [comment]
> @tgraf Could we use an S3 bucket and setup a DNS entry for releases.cilium.io? This way we would just need to focus on the directory / file layout and if we ever want a separate website on releases.cilium.io it could read from the bucket. Should also be straightforward to reuse or write a script that uploads there. wdyt?

Sounds great

**Comment by aalemayhu** [comment]
The script for uploading is ready to be tested. Would be good if you could try it and review the directory structure. I don't have access to the AWS setup to do any of the bucket and SSL setup. @tgraf who can do the setup? Also even with the script, the upload part is manual, but that could easily be solved by using a Jenkins job that is only triggered when new tags are detected.

**Comment by tgraf** [comment]
Done via releases.cilium.io
