### ISSUE TITLE
In v1.8.2 dual-stack mode external traffic to a IPv6 loadBalancerIP fails

### ISSUE THREAD

**Issue by uablrek** [cilium/cilium#13047]
## Bug report

In a dual-stack private-cloud (no public cloud-provider) a service is defined as;

```
$ kubectl get svc mconnect-ipv6 -o json | jq .spec,.status
{
  "clusterIP": "fd00:4000::c83f",
  "externalTrafficPolicy": "Cluster",
  "ipFamily": "IPv6",
  "loadBalancerIP": "1000::",
  "ports": [
    {
      "nodePort": 30139,
      "port": 5001,
      "protocol": "TCP",
      "targetPort": 5001
    }
  ],
  "selector": {
    "app": "mconnect"
  },
  "sessionAffinity": "None",
  "type": "LoadBalancer"
}
{
  "loadBalancer": {
    "ingress": [
      {
        "ip": "1000::"
      }
    ]
  }
}
```
The service should be reachable from an external machine on address `[1000::]:5001` but there is no response (no syn-ack, nothing).

The service _is_ however reachable on the loadBalancerIP from a node inside the cluster;
```
$ telnet 1000:: 5001
mconnect-deployment-d6c79bdc5-ll9pc
```
(the endpoint replies with it's hostname)

The problem also exists for NodePort, it can be accessed from a node within the cluster but not from an external source.

This works (same service) in Cilium 1.7.8.

**General Information**

- Cilium version (run `cilium version`); v1.8.2
- Kernel version (run `uname -a`); 
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...); K8s v1.19.0
- Link to relevant artifacts (policies, deployments scripts, ...);
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Install K8s with dual-stack
2. Install Cilium with [quick-install.yaml.txt](https://github.com/cilium/cilium/files/5161210/quick-install.yaml.txt)
3. Install some app with a service similar to that above. My setup; [mconnect-dual.yaml.txt](https://github.com/cilium/cilium/files/5161241/mconnect-dual.yaml.txt)
4. Assign the loadBalancerIP, e.g with [assign-lb-ip](https://github.com/Nordix/assign-lb-ip)
5. Setup a ipv6 route on an external machine to the loadBalancerIP via some K8s nodes
6. Access the loadBalancerIP

**Comment by aanm** [comment]
@uablrek can you also provide a sysdump?

**Comment by uablrek** [comment]
This was hard for me :smile: I use a _very_ limited system based on basic busybox but I could run this inside your cilium POD by `apt install` curl and python and copy `kubectl` to the POD with "kubectl cp ...". It worked (to my amazement).

[cilium-sysdump-20200902-094025.zip](https://github.com/cilium/cilium/files/5161435/cilium-sysdump-20200902-094025.zip)

**Comment by uablrek** [comment]
Also relevant may be that I used Linux kernel 5.8.1 but I build it myself. I have missed some kernel config in the past but since it works in cilium 1.7.8 I think I have got it right this time. Here is my kernel config; [linux-5.8.1.txt](https://github.com/cilium/cilium/files/5161527/linux-5.8.1.txt)

**Comment by uablrek** [comment]
I can help with testing if you provide a modified cilium image downloadable with docker (or skopeo).

**Comment by uablrek** [comment]
#### Update

In v1.7.8 ipv6 from an external source to a loadBalancerIP (or NodePort) does not work _if proxy-mode=iptables_.

Sounds weird? It becomes weirder; Access only fails if the handling POD is on the same node as the incoming packets.

It works without problem for proxy-mode=ipvs or if kube_proxy is not started at all. These are my "normal" test setups so I did not notice the problem with proxy-mode=iptables until today.

The same test works with Cilium v1.7.4.

**Comment by fristonio** [comment]
Hey @uablrek 
Thanks for the update. I was able to reproduce the issue with 1.8.3 and also the behavior you mentioned for v1.7 releases. This is pretty weird to me as well, I am looking at the datapath and see if I can find the reason why this is happening.

**Comment by uablrek** [comment]
When it fails the syn-ack is received but subsequent packets seems to be lost. I attach traces when it works and fails (they are very short).

* [fails.pcap.gz](https://github.com/cilium/cilium/files/5217138/fails.pcap.gz)
* [works.pcap.gz](https://github.com/cilium/cilium/files/5217140/works.pcap.gz)
