### ISSUE TITLE
CI: K8sBandwidthTest Checks Bandwidth Rate-Limiting Checks Pod to Pod bandwidth

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#13062]
The following failure occurred a couple times, for both:
```
K8sBandwidthTest Checks Bandwidth Rate-Limiting Checks Pod to Pod bandwidth, direct routing
K8sBandwidthTest Checks Bandwidth Rate-Limiting Checks Pod to Pod bandwidth, vxlan tunneling
```

### Stacktrace
```
Rate mismatch
Expected
    <*errors.errorString | 0xc001824dd0>: {
        s: "Expected result 19 (19.62) is not in the range of [20, 30]",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/k8sT/Bandwidth.go:142
```

It may be a simple matter of increasing the range.

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/360/testReport/junit/Suite-k8s-1/12/K8sBandwidthTest_Checks_Bandwidth_Rate_Limiting_Checks_Pod_to_Pod_bandwidth__direct_routing/
[391e10a3_K8sBandwidthTest_Checks_Bandwidth_Rate-Limiting_Checks_Pod_to_Pod_bandwidth,_direct_routing.zip](https://github.com/cilium/cilium/files/5166557/391e10a3_K8sBandwidthTest_Checks_Bandwidth_Rate-Limiting_Checks_Pod_to_Pod_bandwidth._direct_routing.zip)

https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.12-net-next/358/testReport/junit/Suite-k8s-1/12/K8sBandwidthTest_Checks_Bandwidth_Rate_Limiting_Checks_Pod_to_Pod_bandwidth__vxlan_tunneling/
[388c6fd4_K8sBandwidthTest_Checks_Bandwidth_Rate-Limiting_Checks_Pod_to_Pod_bandwidth,_vxlan_tunneling.zip](https://github.com/cilium/cilium/files/5166559/388c6fd4_K8sBandwidthTest_Checks_Bandwidth_Rate-Limiting_Checks_Pod_to_Pod_bandwidth._vxlan_tunneling.zip)

**Comment by borkmann** [comment]
@pchaigno Agree, I recently tightened the bounds slightly to check how far we would potentially deviate in the VM. Worst case we need to increase this window a bit.

**Comment by pchaigno** [comment]
Happened again at https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/395/.

It's [happening quite a lot in master](https://datastudio.google.com/s/gvnEQNFeD-A) too:
![image](https://user-images.githubusercontent.com/1764210/92373904-4bf69780-f0ff-11ea-80b7-65636fd244cc.png)
I sampled a few numbers from the failing tests (should be in range [20; 30]):
```
19.92 19.73 19.38 19 19.88 19.94 
```
Based on these, I'll send a PR to extend the range to [18; 32].

**Comment by christarazi** [comment]
Hit in https://github.com/cilium/cilium/pull/11477: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/463/testReport/junit/Suite-k8s-1/12/K8sBandwidthTest_Checks_Bandwidth_Rate_Limiting_Checks_Pod_to_Pod_bandwidth__geneve_tunneling/

**Comment by pchaigno** [comment]
Let's reopen and I'll try to assess in a couple days by how much we need to increase the interval again.

**Comment by tklauser** [comment]
Hit in #13203: https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.12-net-next/507/testReport/junit/Suite-k8s-1/12/K8sBandwidthTest_Checks_Bandwidth_Rate_Limiting_Checks_Pod_to_Pod_bandwidth__vxlan_tunneling/

**Comment by pchaigno** [comment]
A couple more failures in the last week:
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/639/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/620/testReport/junit/Suite-k8s-1/12/K8sBandwidthTest_Checks_Bandwidth_Rate_Limiting_Checks_Pod_to_Pod_bandwidth__geneve_tunneling/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/638/testReport/junit/Suite-k8s-1/12/K8sBandwidthTest_Checks_Bandwidth_Rate_Limiting_Checks_Pod_to_Pod_bandwidth__geneve_tunneling/

I'm considering making the range a lot larger, e.g. `[10;40]` for 25. I'm guessing most legitimate failures will be either a complete lack of rate limiting (>> 25) or a connectivity loss, so it maybe doesn't matter much if the interval is too large. With that argument though, we could completely remove the interval and check an upper bound only (interestingly, we seem to always fail on the lower bound today). @borkmann What do you think?
