### ISSUE TITLE
Hubble: define an upgrade strategy from v1.8 to v1.9 with regard to TLS

### ISSUE THREAD

**Issue by rolinh** [cilium/cilium#13068]
Starting with Cilium v1.8, Hubble server is embedded into the Cilium agent but remains disabled by default. Cilium v1.8 also introduced Hubble Relay as beta software. Hubble Relay relies on individual Hubble server instances to expose flows of an entire cluster.

Users have the possibility to enable Hubble server to either listen on a local unix domain socket (`--enable-hubble`) or to have it listen on both a local unix domain socket and on a TCP socket (`--enable-hubble` + `--hubble-listen-address`).
However, listening on a TCP socket was not recommended as the Hubble API provides access to potentially sensitive network flow metadata and is exposed on the host network without any security mechanism in place (in v1.8). Cilium v1.9 introduces mTLS support for Hubble server (#12906) and Hubble Relay (#12900). 

Users deploying Cilium v1.9 for the first time and enabling Hubble server to listen on a TCP socket and Hubble Relay will end up with a state where the connection between Hubble server and Hubble Relay instances are secured via mutual TLS without having to provide any certificate. This is made possible by the fact that the Helm charts now have a new option to automatically create a certificate authority and TLS certificates for Hubble server and Hubble Relay that are signed by this CA. These certificates are distributed as Kubernetes secrets and made accessible to Hubble server and Hubble Relay instances respectively.

Users upgrading to Cilium v1.9 from v1.8 and which have enabled Hubble server to listen on a TCP socket and Hubble Relay will experience a Hubble service disruption until all nodes are upgraded (and thus configured for mTLS support between Hubble server and Hubble Relay). The goal of this issue is to define an upgrade strategy for these users such that they don't experience a service disruption during the upgrade process.

**Comment by Rolinh** [comment]
This issue was discussed offline. The conclusion was that no matter which path is taken to attempt to resolve this, users upgrading from v1.8 to v1.9 will experience Hubble Relay service disruptions when enable mTLS. Considering that Hubble Relay is opt-in and was marked as beta feature in Cilium v1.8 and that we want to make sure mTLS is enabled by default, a temporary Hubble Relay service disruption during the upgrade process is deemed acceptable. The temporary Hubble Relay service disruption during upgrade must be mentioned in the upgrade documentation.

**Comment by Rolinh** [comment]
PR #12900 adds this note to the upgrade guide notes for 1.9:
>* Connections between Hubble server and Hubble Relay instances is now secured
  via mutual TLS (mTLS) by default. Users who have opted to enable Hubble Relay
  in v1.8 (a beta feature) will experience disruptions of the Hubble Relay
  service during the upgrade process.
  Users may opt to disable mTLS by using the following Helm options when
  upgrading (strongly discouraged):
>
>  - ``global.hubble.tls.enabled=false``
>  - ``global.hubble.tls.auto.enabled=false``

Which should be enough according to the message above.
