### ISSUE TITLE
throughput test sockops-enable

### ISSUE THREAD

**Issue by jlatusek** [cilium/cilium#13063]
I'm trying to recreate throughput test results from article https://cilium.io/blog/2019/02/12/cilium-14/ with sockops-enable and without it. Unfortunately my results look kind of different. I've got better bandwidth with sockops disabled. I made bandwidth test on baremetal cluster with kubernetes version 1.18.1. and cilium version 1.8.0. Iperf3 was used as test tool with parameters:
```
TIME=900
iperf3 -c $ADDR -b 0 -p 5201 -Z --logfile $TCP_LOG_FILENAME -t $TIME -A 2 -l $i -N
```
test was made with different $i parameter
and on server pod:
```
iperf3 -s -A 0 --log $LOG_FILENAME
```
Cluster work on machines with ubuntu 18.04, kernel 5.3
Kernel config: [config-5.3.0-28-generic.txt](https://github.com/cilium/cilium/files/5166620/config-5.3.0-28-generic.txt)
Cilium sysdump result: [cilium-sysdump-20200727-125449.zip](https://github.com/cilium/cilium/files/5166621/cilium-sysdump-20200727-125449.zip)
I will be grateful for your help

**Comment by brb** [comment]
The sockops feature was removed from Cilium (https://github.com/cilium/cilium/issues/23556). Closing the issue.
