### ISSUE TITLE
Hubble fails to resolve identities across a cluster mesh.

### ISSUE THREAD

**Issue by bmcustodio** [cilium/cilium#13076]
## Bug report

After deploying Hubble (in distributed mode) on a mesh of three clusters (`kvstore: etcd`, `identity-allocation-mode: kvstore`), the Cilium agents are generating a huge amount of logs like the following one:

```
cilium-agent level=warning msg="failed to resolve identity" error="identity 185344 not found" identity=185344 subsys=hubble
```

I tried to run `cilium get identity 185344` on the cluster where the log message originated and got a `404` error. Then I tried running the same on another cluster of the mesh and got a successful result (probably because the workload is running on that cluster).

**General Information**

- Cilium version (run `cilium version`)

```
# cilium version
Client: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
Daemon: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
```

- Kernel version (run `uname -a`)

```
Linux vm-k8s-STAG-LD4-Z0-00-master-2 5.7.10-050710-generic #202007220834 SMP Wed Jul 22 08:52:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Link to relevant artifacts (policies, deployments scripts, ...)

N/A

- Generate and upload a system zip:

```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Create a mesh of two or more clusters according to https://docs.cilium.io/en/v1.8/gettingstarted/clustermesh/.
2. Enable Hubble in distributed mode according to https://docs.cilium.io/en/v1.8/gettingstarted/hubble-enable/.

**Comment by aanm** [comment]
@bmcustodio can you also provide a sysdump?

**Comment by bmcustodio** [comment]
@aanm can I send it to you privately over Slack?
