### ISSUE TITLE
Is it possible to run Cilium without Kubernetes?

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13072]
### Is it possible to run Cilium without Kubernetes?

Yes, any platform that supports CNI can use the [Cilium CNI plugin](https://github.com/cilium/cilium/tree/master/plugins/cilium-cni) to handle networking for the cluster. Note that in Kubernetes mode, Kubernetes CRDs provide a convenient method for sharing state between all nodes in the cluster such as daemon configuration and network policy. In the non-Kubernetes mode, each node must be independently configured with such state through agent invocation arguments or `cilium-agent` CLI/API. Other state like identities and endpoints are shared across nodes using a key/value store like Etcd.

Docker libnetwork was previously supported with instructions below, however these docs are no longer actively maintained due to lack of interest from the community. These instructions run Cilium in a VM with Consul as the KVstore backend:

https://docs.cilium.io/en/v1.9/gettingstarted/docker/

**Comment by till** [comment]
@joestringer Link is dead? Did this change?

**Comment by nbusseneau** [comment]
@till The documentation entry regarding installing Cilium manually via Docker + Consul was removed during 1.10 development cycle as it was considered obsolete: https://github.com/cilium/cilium/pull/15370

You can still find the documentation available in the v1.9 documentation: https://docs.cilium.io/en/v1.9/gettingstarted/docker/

**Comment by till** [comment]
@nbusseneau Thank you!
