### ISSUE TITLE
Typing mistake in doc Documentation/concepts/networking/ipam/azure.rst

### ISSUE THREAD

**Issue by chowmean** [cilium/cilium#13084]
## Documentation Error: 

If you check this Documentation/concepts/networking/ipam/azure.rst I can see `--aws-release-excess-ips=true`. Shouldn't this be `--azure-release-excess-ips=true`

**Comment by chowmean** [comment]
@fristonio Am I correct here I can give a small PR :)

**Comment by fristonio** [comment]
Hey @chowmean, thanks for opening an issue for this. Taking a quick look at the [operator code](https://github.com/cilium/cilium/blob/master/operator/provider_azure_flags.go), it looks like we don't have the same option for Azure. Azure IPAM is relatively new for Cilium and I think the documentation is not very mature. I believe that we need to remove these docs related to the releasing of excess IPs as for Azure we don't provide this functionality. See the last option [here](https://github.com/cilium/cilium/blob/master/pkg/ipam/allocator/azure/azure.go#L86) for azure allocator.

cc/ @tgraf

**Comment by chowmean** [comment]
Got it. Should I remove this part of the Documentation then?

**Comment by fristonio** [comment]
Yeah, I think we should remove those lines as they don't apply to Azure allocator.
