### ISSUE TITLE
Hubble TLS advertised ServerName may mismatch their certificate

### ISSUE THREAD

**Issue by kaworu** [cilium/cilium#13080]
Related to how the peer service handler infer Hubble TLS ServerName, see https://github.com/cilium/cilium/pull/12906#discussion_r483453877.

From https://kubernetes.io/docs/concepts/architecture/nodes:
> The name of a Node object must be a valid [DNS subdomain name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names).

My understanding is that we could encounter a dot (.) in the nodeName, e.g. `nodeName=mos.eisley` which will give `mos.eisley.tatooine.hubble-grpc.cilium.io` for which the generated certificate `*.tatooine.hubble-grpc.cilium.io` will not match.

**Comment by kAworu** [comment]
Since the certificate is `*.tatooine.hubble-grpc.cilium.io` we can pick an arbitrary name. Note that having two peers with the same TLS ServerName should not be much of a problem. @Rolinh any preference between removing, replacing, or encoding the dots?

cc @gandro

**Comment by aanm** [comment]
@kAworu I assume the PR description should be for which the generated certificate `*eisley.tatooine.hubble-grpc.cilium.io` will not match.

**Comment by kAworu** [comment]
@aanm I am confused, are you suggesting that `*.eisley.tatooine.hubble-grpc.cilium.io` would not match `mos.eisley.tatooine.hubble-grpc.cilium.io`?

**Comment by aanm** [comment]
Discussed offline. It's likely that we have the same issue in clustermesh. where we generate certificates for `*.mesh.cilium.io`

**Comment by Rolinh** [comment]
>  @Rolinh any preference between removing, replacing, or encoding the dots?

No strong opinion but I think I'd favor replacing the dots. Ideally, it should be easy to do the revert operation which would be near impossible if the dots are removed.
