### ISSUE TITLE
CiliumNetworkPolicies documentation

### ISSUE THREAD

**Issue by techcet** [cilium/cilium#1309]
For Cilium v0.10 release announcement.
CiiumNetworkPolicies :  this object is not really documented outside of the example in this blogpost:  https://www.cilium.io/blog/2017/7/7/57h5usdogcy8a0daqrgfu7ikxpgzmw .   We need full documentation of this, in the Admin Guide.    Thomas said he would send a pointer to the k8s integration tests so you can see lots of example usage.  You can probably get the same pointer from Ian.  

Thomas provided k8s tests here:
https://github.com/cilium/cilium/tree/master/tests/k8s/tests

**Comment by techcet** [comment]
K8s TPR explained here: 
http://docs.cilium.io/en/latest/policy/#kubernetes

**Comment by techcet** [comment]
To Do:
- include an example
- reference a support matrix, depending on k8s version for TPR vs CRD.

**Comment by tgraf** [comment]
Done: http://docs.cilium.io/en/v1.1/policy/language/#kubernetes
