### ISSUE TITLE
ARM64 cross-build cilium binaries report platform as AMD64

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13122]
1. Deploy `cilium/cilium-dev:v1.9.0-rc0@sha256:1ac616fc6457a546ca453bde37a013ede855c0d427e6522a063e13c739304b33`
1. Check the `cilium-agent` logs
1. Observe that the version reports platform as `amd64`

```
# docker run -ti docker.io/cilium/cilium-dev:v1.9.0-rc0@sha256:1ac616f
c6457a546ca453bde37a013ede855c0d427e6522a063e13c739304b33 cilium version
Client: 1.8.90 c1d63f79e 2020-08-18T20:42:38+02:00 go version go1.15 linux/amd64
Daemon: Not responding
```

Looking more closely at the ELF shows it to be actually built for ARM64, and running the AMD64 build causes the error message ` exec user process caused "exec format error"` so this is clearly the arm64 build, it's just reporting the platform wrong.

This is the case both for the `cilium` binary and `cilium-agent` (and I'm guessing other binaries too).

**Comment by tklauser** [comment]
I assume this is because we cross-build the ARM64 binaries on AMD64 and set `version.Version` to the output of `$(GO) version` (as run on the host system) via linker flags:

https://github.com/cilium/cilium/blob/4b1256b8af7ef5c3201253a652cccb83b54e7002/Makefile.defs#L72-L73
