### ISSUE TITLE
Doc: Review document note for using namespace as a label in Policy

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#13133]
This came up in the discussion around specifying namespace via the label `k8s:io.kubernetes.pod.namespace` while creating a policy [1].

`While specification of the namespace via the label k8s:io.kubernetes.pod.namespace in the fromEndpoints and toEndpoints fields is deliberately supported. Specification of the namespace in the endpointSelector is prohibited as it would violate the namespace isolation principle of Kubernetes. The endpointSelector always applies to pods of the namespace which is associated with the CiliumNetworkPolicy resource itself.`

This note doesn't apply to CiliumClusterwideNetworkPolicy, and it's better to call that out in the note specifically?

/cc @danwent 

[1] https://docs.cilium.io/en/v1.8/policy/kubernetes/

**Comment by pchaigno** [comment]
But if you use `k8s:io.kubernetes.pod.namespace` in the `endpointSelector` of a CCNP, isn't that the same as using a CNP?

**Comment by aditighag** [comment]
>Specification of the namespace in the endpointSelector is prohibited as it would violate the namespace isolation principle of Kubernetes.

The namespace related note isn't applicable to CCNP.

**Comment by pchaigno** [comment]
@aditighag I understand that `k8s:io.kubernetes.pod.namespace` wouldn't be prohibited in CCNPs. I'm asking whether they make sense and whether we want to call that out (i.e., recommend using CNPs instead of CCNPs with `k8s:io.kubernetes.pod.namespace`).
