### ISSUE TITLE
rp_filter (default) strict mode breaks certain load balancing cases in kube-proxy-free mode

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#13130]
In a multi-node environment, an external incoming request (N-S) that's destined to a nodeport service IP, when arrives on a node that's running one of the service backends, is dropped by the `rp_filter strict mode`. 

When a request arrives on the node where a backend is running, the destination address is translated to one of the locally running backend pods, which is then dropped by `rp_filter strict mode`. The strict mode checks for a reverse path for an incoming packet against FIB table, which would be an `lxc-xxx` interface when an endpoint route exists for the backend pod or a `cilium_host` interface otherwise. In such cases, the translated packets are dropped.

You can monitor the drops using logs/stats - 

```
nstat -rsz | grep IPReversePathFilter

sysctl -w 'net.ipv4.conf.all.log_martians=1
tail -fn0  /var/log/messages
:
Sep  2 23:57:53 ip-192-168-55-95 kernel: IPv4: martian source 192.168.156.88 from 192.168.2.138, on dev eth0

ip route get 192.168.156.88 from 192.168.2.138 iif eth0
RTNETLINK answers: Invalid cross-device link

```

The potential fix is to set the rp_filter mode to `Loose mode` [1] in the cilium agent that allows for asymmetric routing cases such as the cilium case. However, this might not help the environments, where systemd overrides such settings after cilium starts [2]. 

This was discussed in the sig-datapath meeting on 09/09 [3]. 

[1] https://tools.ietf.org/html/rfc3704#page-6
[2] https://github.com/cilium/cilium/issues/10645
[3] https://docs.google.com/document/d/1IZZ-FTM_U3zN06-M_mDOgep_DcDM0Oe3YOFVM1BTIt8/edit#heading=h.39952dxvg45a

**Comment by brb** [comment]
Related to this issue, in the case of multi-dev DSR, cilium-agent might warn about the strict rp_filter mode: https://github.com/cilium/cilium/blob/v1.8.3/daemon/cmd/kube_proxy_replacement.go#L348

**Comment by aditighag** [comment]
Current state - 

- With #13346, when endpoint routes are enabled, because of tunneling based symmetric routing rp_filter shouldn't be seen.
- PR #13234 already fixed this issue on EKS environments.

Since I originally opened this issue for EKS environment, I'm not sure where else in the current code we need to set the filter to the loose mode.

**Comment by joestringer** [comment]
@aditighag Sounds like the original bug as reported is fixed, that's usually enough to close out.

That said it sounds like there's some concern the bug may still be present in some form in some configurations - Do you have a particular case in mind for that?

**Comment by aditighag** [comment]
> @aditighag Sounds like the original bug as reported is fixed, that's usually enough to close out.
> 
> That said it sounds like there's some concern the bug may still be present in some form in some configurations - Do you have a particular case in mind for that?

I would imagine this issue to be present due to asymmetric routing wherever `rp_filter` is set to the strict mode in non-EKS environments as well clusters where endpoint routes are not enabled by default in >= v1.9.

**Comment by joestringer** [comment]
In `Loader.Reinitialize()` we already do this don't we? 

```
$ git grep rp_filter | grep -v contrib/
bpf/init.sh:            echo 0 > /proc/sys/net/ipv4/conf/${NAME}/rp_filter
bpf/lib/nodeport.h:                      * rp_filter=1.
daemon/cmd/kube_proxy_replacement.go:           // if the destination node's direct routing device's rp_filter = 1
daemon/cmd/kube_proxy_replacement.go:           if val, err := sysctl.Read(fmt.Sprintf("net.ipv4.conf.%s.rp_filter", iface)); err != nil {
daemon/cmd/kube_proxy_replacement.go:                   log.Warnf("Unable to read net.ipv4.conf.%s.rp_filter: %s. Ignoring the check",
daemon/cmd/kube_proxy_replacement.go:                                   `Run 'sysctl -w net.ipv4.conf.%s.rp_filter=2' (or set to '0') on each node to fix`,
pkg/datapath/connector/add.go:  return sysctl.Disable(fmt.Sprintf("net.ipv4.conf.%s.rp_filter", ifName))
pkg/datapath/loader/base.go:    // # sysctl -w net.ipv4.conf.eth0.rp_filter=2
pkg/datapath/loader/base.go:            fmt.Sprintf("net.ipv4.conf.%s.rp_filter", iface.Attrs().Name),
pkg/datapath/loader/base.go:            {"net.ipv4.conf.all.rp_filter", "0", false},
plugins/cilium-cni/cni-uninstall.sh:        echo 1 > "/proc/sys/net/ipv4/conf/${CNI_MASTER_DEVICE}/rp_filter" && \
plugins/cilium-cni/cni-uninstall.sh:        echo 1 > "/proc/sys/net/ipv4/conf/all/rp_filter"
plugins/cilium-cni/cni-uninstall.sh:        echo 1 > "/proc/sys/net/ipv4/conf/${POD_VETH_SIDE_PAIR}/rp_filter"
```

https://github.com/cilium/cilium/blob/992c321178f1330e3dd1f987cea43a130e3e3417/pkg/datapath/loader/base.go#L185

**Comment by aditighag** [comment]
> In `Loader.Reinitialize()` we already do this don't we?
> 
> ```
> $ git grep rp_filter | grep -v contrib/
> bpf/init.sh:            echo 0 > /proc/sys/net/ipv4/conf/${NAME}/rp_filter
> bpf/lib/nodeport.h:                      * rp_filter=1.
> daemon/cmd/kube_proxy_replacement.go:           // if the destination node's direct routing device's rp_filter = 1
> daemon/cmd/kube_proxy_replacement.go:           if val, err := sysctl.Read(fmt.Sprintf("net.ipv4.conf.%s.rp_filter", iface)); err != nil {
> daemon/cmd/kube_proxy_replacement.go:                   log.Warnf("Unable to read net.ipv4.conf.%s.rp_filter: %s. Ignoring the check",
> daemon/cmd/kube_proxy_replacement.go:                                   `Run 'sysctl -w net.ipv4.conf.%s.rp_filter=2' (or set to '0') on each node to fix`,
> pkg/datapath/connector/add.go:  return sysctl.Disable(fmt.Sprintf("net.ipv4.conf.%s.rp_filter", ifName))
> pkg/datapath/loader/base.go:    // # sysctl -w net.ipv4.conf.eth0.rp_filter=2
> pkg/datapath/loader/base.go:            fmt.Sprintf("net.ipv4.conf.%s.rp_filter", iface.Attrs().Name),
> pkg/datapath/loader/base.go:            {"net.ipv4.conf.all.rp_filter", "0", false},
> plugins/cilium-cni/cni-uninstall.sh:        echo 1 > "/proc/sys/net/ipv4/conf/${CNI_MASTER_DEVICE}/rp_filter" && \
> plugins/cilium-cni/cni-uninstall.sh:        echo 1 > "/proc/sys/net/ipv4/conf/all/rp_filter"
> plugins/cilium-cni/cni-uninstall.sh:        echo 1 > "/proc/sys/net/ipv4/conf/${POD_VETH_SIDE_PAIR}/rp_filter"
> ```
> 
> https://github.com/cilium/cilium/blob/992c321178f1330e3dd1f987cea43a130e3e3417/pkg/datapath/loader/base.go#L185

Yes, I also did a search for `rp_filter`, and found some places where we set it. I'm not familiar with this code paths though. But if this were the case, why would see the issue on EKS?

**Comment by joestringer** [comment]
Good questions, I don't understand why this would not mitigate the issue on EKS. We would need to investigate further to find out.

That said, this issue was filed with EKS in mind and that was why we marked it as release-blocker (to follow up & make sure that case is resolved). As far as the release-blocker label is concerned, per your report above it sounds like that is resolved so I'll drop the label.

Furthermore if we don't have an example configuration that is broken and we don't have a plan for how to investigate which configurations might be broken, then I see no point in leaving the issue open.

@brb if you're concerned about a specific configuration that we haven't yet validated, then I would suggest re-opening with details to provide next steps to investigate further.

**Comment by brb** [comment]
I'd suggest to close the issue after we have validated that #13234 resolved the issue when running kube-proxy-free on EKS, as #13234 was mainly created because of NodePort being broken when running with kube-proxy, and probably didn't have the kube-proxy-free mode in mind.

**Comment by aditighag** [comment]
Sure, I'll verify that the NodePort issue that I originally called out in the description is fixed before closing this bug.

**Comment by aditighag** [comment]
Deployed a cluster with v1.9.1. and verified that the rp_filter config is set to `Loose` mode as recommended in the issue description. 

```
[ec2-user@ip-192-168-6-215 ~]$ sysctl  net.ipv4.conf.eth0.rp_filter
net.ipv4.conf.eth0.rp_filter = 2
```

**Comment by brb** [comment]
> Deployed a cluster with v1.9.1. and verified that the rp_filter config is set to Loose mode as recommended in the issue description.

Cool! Did you validate that NodePort BPF when accessed from outside works?
