### ISSUE TITLE
Add FQDN policy troubleshooting guide

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13144]
At a glance, I don't see good documentation for debugging this case here:

https://docs.cilium.io/en/v1.8/troubleshooting/

One of the common cases for FQDN policy is where the `ToPorts` section of the policy doesn't include the L7 DNS rules:

https://docs.cilium.io/en/v1.8/policy/language/#example

It would be great to have a guide that takes from app behaviour (connect times out) through `cilium monitor` debugging with example output similar to:

```
xx drop (Policy denied) flow 0x4c7f85a0 to endpoint 0, identity 15266->2: 4.3.2.1:34534 -> 1.2.3.4:22 tcp SYN
```

Could potentially use `cilium identity get` to identify the source/destination, possibly use `cilium policy trace` to figure out whether the rules are applying.

In this case, if we are attempting to allow the traffic via FQDN policy, and the destination identity is `2`, that indicates that the destination is `reserved:world` rather than some CIDR identity (`16xxxxxx`). This means that the FQDN policy is not properly matching At least for the FQDN example this logically leads to ensuring that the DNS L7 policy applies properly to the DNS traffic from the pods.

**Comment by joestringer** [comment]
Example app behaviour:
```
bash-5.0# curl -vvv cilium.io
*   Trying 104.198.14.52:80...
```
Then it just times out after some time.

**Comment by chowmean** [comment]
@joestringer I would like to take this up. Any pointers that you can give me to start this?

**Comment by joestringer** [comment]
@chowmean awesome, sure.

I would start by following the [FQDN policy getting started guide](https://docs.cilium.io/en/v1.8/gettingstarted/dns/), but when you reach the section around [applying the policy](https://docs.cilium.io/en/v1.8/gettingstarted/dns/#apply-dns-egress-policy), remove this section:

```
      rules:
        dns:
        - matchPattern: "*"
```

If you remove this section of the policy, the policy will not work as intended. At that point, you can try some of the commands mentioned in the issue description above to observe how Cilium behaves and get example command output.

Then to write the section, assume that you're in this situation to begin with; what kind of commands could you run to establish that this is the problem? (Mostly rewording the stuff in the description above), then towards the end, edit the policy to include the above lines. Once the policy has been updated to include these lines, you should be able to re-run the commands from the getting started guide and they will work.
