### ISSUE TITLE
Scale back / rate limit the amount of CNP updates sent / processed by Cilium & Operator 

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#13148]
In a large-scale environment with the following properties: 

- Many CNPs (1k+)
- CNP status updating enabled + K8s event handover
- Kvstore enabled

We should consider reducing / rate limiting the amount of updates sent by the Cilium agents and the amount of CNPs that are loaded at start-up time in the Operator. OOM kills have been observed in environments with these properties due to excessive memory usage of the Operator.

This image shows memory usage gradually increase as CNPs are being applied en masse; no OOM kill in this scenario:
![image](https://user-images.githubusercontent.com/3885308/92828876-655e4480-f388-11ea-87e8-0b980abe7015.png)

This image shows memory usage spike as the Operator loads / processes all CNPs in K8s; OOM kill follows shortly after a few seconds:
![image](https://user-images.githubusercontent.com/3885308/92829542-30062680-f389-11ea-82a3-27c67abce4d9.png)

Related: https://github.com/cilium/cilium/pull/13135

**Comment by marseel** [comment]
This has been fixed by deleting this functionality in https://github.com/cilium/cilium/issues/24503
