### ISSUE TITLE
Expose CLI debug interface for LRP

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#13156]
Discussed with @aditighag offline, when trying to debug LRP, currently there's no easily accessible interface to introspect the internal states of LRP manager and policies.

Proposal is to add a CLI interface (`cilium lrp list/get`) to dump internals of existing LRPs.

If this proposal makes sense, I can take a stab at the implementation.

**Comment by aditighag** [comment]
Thanks Weilong for taking this up.

Here is some information that we can dump - 

- LRP config
- redirectpolicy/manager internal state : frontends, services, podPolicy

**Comment by joestringer** [comment]
One minor thing to consider, LRPs are basically a type of service right? Perhaps some of the state could be exposed via `cilium service list`, then perhaps just extend the API so that the CLI can print the type of the service?

@aditighag LRP config itself I would think should be sufficient to just `kubectl get clrp`, or is there something else you have in mind there?

**Comment by aditighag** [comment]
> One minor thing to consider, LRPs are basically a type of service right? Perhaps some of the state could be exposed via `cilium service list`, then perhaps just extend the API so that the CLI can print the type of the service?
> 

This is already taken care of in my PR. 

cilium service list
ID   Frontend               Service Type    Backend
1    172.20.0.20:5001       ClusterIP       1 => 10.16.168.80:5001
                                            2 => 10.16.174.168:5001
:
9    172.20.0.211:80        LocalRedirect   1 => 10.16.113.155:80
10   169.254.169.254:8080   LocalRedirect   1 => 10.16.113.155:80


> @aditighag LRP config itself I would think should be sufficient to just `kubectl get clrp`, or is there something else you have in mind there?

LRP is further parsed, and redirectpolicy/manager stores a bunch of internal state, which is updated based on LRP/service/pod add/delete/update events. Being able to dump this internal state in CLI would help with debugging any issues such as "why LocalRedirect service entry is missing?".
