### ISSUE TITLE
Coredns failing after installing Cilium with Azure IPAM

### ISSUE THREAD

**Issue by Buffer0x7cd** [cilium/cilium#13154]
## Bug report

Hey everyone, Currently I am trying to deploy Cilium in Azure AKS with native Azure CNI mode ( Without chaining) by following the instructions mentioned at https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-azure/. After installation, I am seeing a persistent issue where Coredns is not able to come up once the installation of Cilium CNI is done. I am getting the following error in Coredns logs
```
 pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://xxxxx.hcp.southeastasia.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp: lookup xxxxxxxxxxxx.hcp.southeastasia.azmk8s.io on 168.63.129.16:53: read udp 10.207.0.44:45417->168.63.129.16:53: i/o timeout
[INFO] plugin/ready: Still waiting on: "kubernetes"
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
[INFO] plugin/ready: Still waiting on: "kubernetes"
```
For the confirmation of the issue, I had tried removing Cilium and then restarting Coredns, In which case it's able to successfully start. 
Arguments Passed to Cilium for Installations are below
```
helm install cilium cilium/cilium --version 1.8.3 \    
  --namespace kube-system \
  --set global.azure.enabled=true \
  --set global.azure.resourceGroup=$AZURE_NODE_RESOURCE_GROUP \
  --set global.azure.subscriptionID=$AZURE_SUBSCRIPTION_ID \
  --set global.azure.tenantID=$AZURE_TENANT_ID \
  --set global.azure.clientID=$AZURE_CLIENT_ID \
  --set global.azure.clientSecret=$AZURE_CLIENT_SECRET \
  --set global.tunnel=disabled \
  --set config.ipam=azure \
  --set global.masquerade=false \
  --set global.nodeinit.enabled=true
```

**General Information**

- Cilium version 1.8.3
- Kernel version 1.8.3
- Orchestration system version in use: Kubectl v1.18.0, Azure AKS

**How to reproduce the issue**

1. Deploy an AKS cluster in azure with any method and configure the cluster to use Azure CNI Networking
2. Follow the instructions mentioned at https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-azure/ to deploy Cilium in native Azure CNI mode
3. After the installation steps, we can see that the Coredns pod is not launching and can see the above-mentioned logs in the failing Coredns pod

**Comment by tgraf** [comment]
Did you deploy CoreDNS before Cilium was deployed? Did you restart CoreDNS after deploying Cilium? Or in other words, does the issue resolve itself if you restart CoreDNS to create a new set of pods? You can also validate this passively by running `kubectl get cep` and validate that you have `CiliumEndpoint` representations for the CoreDNS pods.

**Comment by Buffer0x7cd** [comment]
Coredns is already deployed in k8s cluster as part of AKS launch. The issue is still persisting after restarting the CoreDNS pods. I am getting below logs for the CoreDNS
```
kubectl describe pod coredns
Events:
  Type     Reason     Age                   From                                         Message
  ----     ------     ----                  ----                                         -------
  Normal   Scheduled  3m14s                 default-scheduler                            Successfully assigned kube-system/coredns-7d54bdd87c-np22b to aks-cnidefault-36707446-vmss000000
  Normal   Pulled     3m12s                 kubelet, vmss000000  Container image "mcr.microsoft.com/oss/kubernetes/coredns:1.6.6" already present on machine
  Normal   Created    3m12s                 kubelet, vmss000000  Created container coredns
  Normal   Started    3m12s                 kubelet, 000000  Started container coredns
  Warning  Unhealthy  10s (x19 over 3m10s)  vmss000000  Readiness probe failed: HTTP probe failed with statuscode: 503
```
logs from the CoreDNS pod

`E0917 16:35:54.586224       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://xxxxxxxx.hcp.southeastasia.azmk8s.io:443/api/v1/services?limit=500&resourceVersion=0: dial tcp: lookup cnitest-efdced13.hcp.southeastasia.azmk8s.io on 168.63.129.16:53: read udp 10.x.x.x:57155->168.63.129.16:53: i/o timeout`

Also, the cilium endpoint state is ready. I have attached the output below
```
 kubectl get cep -w
NAME                       ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4           IPV6
coredns-5bd7b6f855-hlwqw   1630          48361                                                                        ready            10.207.0.153
coredns-7d54bdd87c-ss4c8   2817          48361                                                                        ready            10.207.0.78
coredns-7d54bdd87c-wfnqw   2326          48361                                                                        ready            10.207.0.47
```
