### ISSUE TITLE
Cannot connect docker container to another network

### ISSUE THREAD

**Issue by azyobuzin** [cilium/cilium#13161]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
  - both 1.8.3 and 1.9.0-rc0 (1.8.90)
- Kernel version (run `uname -a`)
  - `Linux ubuntu-18 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
  - Docker 19.03.12
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
  - All files in the zip are empty

**How to reproduce the issue**

1. Launch virtual machine with [getting-started](https://github.com/cilium/cilium/tree/f55458f9bfd412b7334b535c43bab593910c6b31/examples/getting-started)
2. Create networks
    - `docker network create --driver cilium --ipam-driver cilium cilium-net`
    - `docker network create another-bridge`
3. Launch a container connected to `cilium-net`
    - `docker run -d --name app1 --net cilium-net cilium/demo-httpd`
4. Connect the container to another bridge network
    - `docker network connect another-bridge app1`

Then, I got the following message.

```
Error response from daemon: failed to set gateway while updating gateway: file exists
```

The reverse order also results in an error.

```
$ docker run -d --name app1 --net another-bridge cilium/demo-httpd
$ docker network connect cilium-net app1
Error response from daemon: failed to add static route 0.0.0.0/0: file exists
```

**Expected behavior**

The container should be connected to both `cilium-net` and `another-bridge`.

I think the comment in driver.go is relevant to this issue.

https://github.com/cilium/cilium/blob/f55458f9bfd412b7334b535c43bab593910c6b31/plugins/cilium-docker/driver/driver.go#L510-L519

**Comment by aanm** [comment]
@azyobuzin thanks for opening the issue. What's the use case to have 2 networks in a single container?

**Comment by azyobuzin** [comment]
> What's the use case to have 2 networks in a single container?

Thanks. I have two use cases in mind.

- Communicating with containers outside of the Cilium network. It is needed during migrating containers to Cilium network.
- Publishing ports of containers with `--publish` option using another bridge network because Cilium Docker plugin does not support that option.
