### ISSUE TITLE
CiliumEndpoint IP does not match Pod IP

### ISSUE THREAD

**Issue by splushii** [cilium/cilium#13167]
## Bug report

There is a CiliumEndpoint IP and Pod IP mismatch for one of the `kube-dns` Pods. This results in dropped traffic because Cilium thinks the target IP is unmanaged and thus not affected by network policies allowing traffic.

```
kubectl -n kube-system get po kube-dns-7c976ddbdb-77p6w -owide
NAME                        READY   STATUS    RESTARTS   AGE   IP          NODE                        NOMINATED NODE   READINESS GATES
kube-dns-7c976ddbdb-77p6w   4/4     Running   0          5d    10.12.3.7   gke-dev-dev-39261880-f5rb   <none>           <none>
```

```
kubectl -n kube-system get cep kube-dns-7c976ddbdb-77p6w
NAME                        ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   ENDPOINT STATE   IPV4         IPV6
kube-dns-7c976ddbdb-77p6w   1645          16773543                                                 ready            10.12.3.93
```

Have only seen this happen for one of the `kube-dns` Pods (although the phenomenon is present in multiple clusters), but it may affect other Pods without us noticing yet.

**General Information**

- Cilium version (run `cilium version`)
Client: 1.8.1 5ce2bc7b3 2020-07-02T20:04:47+02:00 go version go1.14.4 linux/amd64
Daemon: 1.8.1 5ce2bc7b3 2020-07-02T20:04:47+02:00 go version go1.14.4 linux/amd64
- Kernel version (run `uname -a`)
Linux gke-dev-dev-39261880-f5rb 4.19.112+ #1 SMP Thu May 21 12:32:38 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:

**How to reproduce the issue**

1. Create a GKE cluster
2. Install Cilium (following https://docs.cilium.io/en/stable/gettingstarted/k8s-install-gke/). Cilium is installed in the `cilium` namespace. Only difference being `nodeinit.restartPods=true` and `global.kubeProxyReplacement=disabled`
3. Check the `kube-dns` Pod IP:s and their respective CiliumEndpoint IP:s.
`kubectl -n kube-system get po -l k8s-app=kube-dns -owide`
`kubectl -n kube-system get cep | grep kube-dns`

**Comment by pchaigno** [comment]
I'm unable to reproduce this issue. I used the same version of Cilium, in the `kube-system` namespace with the two additional options you specified compare to the GSG. Both of my kube-dns pods have the same IP reported in the Pod and CiliumEndpoint resources. Does it happen all the time?

Note that to disable our kube-proxy replacement, you want `kubeProxyReplacement=disabled`, not `false`. You can check the actual kube-proxy-replacement state in `cilium status`. Also, our getting started guide recommend deploying Cilium in its own namespace and not the `kube-system` namespace because we've had issues with that in the past. I'm not sure whether these issues are resolved.

**Comment by aanm** [comment]
@splushii thank you for opening the GH issue.

have you tried upgrade to 1.8.2? There's one PR that could explain this https://github.com/cilium/cilium/pull/12595. However I'm not convinced that it would explain what you were seeing.

How did the pod changed IP address? For some reason it looked that it had `10.12.3.93` and now it has `10.12.3.7`.

Can you provide a cilium sysdump for the node that is running that coredns instance?

**Comment by splushii** [comment]
> I'm unable to reproduce this issue. I used the same version of Cilium, in the `kube-system` namespace with the two additional options you specified compare to the GSG. Both of my kube-dns pods have the same IP reported in the Pod and CiliumEndpoint resources. Does it happen all the time?

Tried to reproduce this some more times. It does not always happen directly. But it seem to always happen eventually.

For example, had this issue in another cluster yesterday. A `kubectl -n kube-system rollout restart deploy/kube-dns` got us new `kube-dns` pods where the pods' IP:s matches their respective `CiliumEndpoints`. Today when checking there is a mismatch for one of the `kube-dns` pods:
```
$ kubectl -n kube-system get cep | grep kube-dns
kube-dns-55b477b7b6-952h7                                   86            1049221                                                  ready            10.68.1.120   
kube-dns-55b477b7b6-cn4wk                                   2495          1049221                                                  ready            10.68.0.57    
...
```

My initial thought was that this is happening when Kubernetes nodes are added/removed (we use some preemptible nodes) and thus moving the `kube-dns` workloads. But no nodes have been added/removed since yesterday (when there were no mismatch). So either the `CiliumEndpoint` IP or the `kube-dns` pod IP has changed since then. Unfortunately I didn't keep track of the exact IP:s.

```
$ kubectl -n kube-system get po -l k8s-app=kube-dns -owide
NAME                        READY   STATUS    RESTARTS   AGE   IP            NODE    NOMINATED NODE   READINESS GATES
kube-dns-55b477b7b6-952h7   4/4     Running   0          19h   10.68.1.120   node1   <none>           <none>
kube-dns-55b477b7b6-cn4wk   4/4     Running   0          19h   10.68.0.4     node2   <none>           <none>
```

> Note that to disable our kube-proxy replacement, you want `kubeProxyReplacement=disabled`, not `false`. You can check the actual kube-proxy-replacement state in `cilium status`. Also, our getting started guide recommend deploying Cilium in its own namespace and not the `kube-system` namespace because we've had issues with that in the past. I'm not sure whether these issues are resolved.

My bad. We actually have `kubeProxyReplacement=disabled` and Cilium is running in the `cilium` namespace. Will update the description.

**Comment by splushii** [comment]
> have you tried upgrade to 1.8.2? There's one PR that could explain this #12595. However I'm not convinced that it would explain what you were seeing.

We see the same problem on 1.8.2 unfortunately.

> How did the pod changed IP address? For some reason it looked that it had `10.12.3.93` and now it has `10.12.3.7`.

I'm not sure. Maybe this is something related to how `kube-dns` in GKE is managed?

> Can you provide a cilium sysdump for the node that is running that coredns instance?

Of course, missed to include it initially. Attaching a sysdump of the node (the exact one mentioned in the description).

[cilium-sysdump-20200914-161830.zip](https://github.com/cilium/cilium/files/5230657/cilium-sysdump-20200914-161830.zip)

**Comment by splushii** [comment]
@pchaigno @aanm This is not just happening with `kube-dns` pods. I checked one cluster and we have IP mismatch on 8/20 Cilium managed pods.

Can there be a configuration error?

**Comment by aanm** [comment]
@splushii this PR [1] explains a little bit of what you are seeing but I'm not so sure that would fix your issue. Would you be able to test it once it's backported and report back? Thanks

[1] https://github.com/cilium/cilium/pull/13220

**Comment by splushii** [comment]
@aanm Yes, no problem!

**Comment by splushii** [comment]
@aanm 

Upgraded to `1.8.4` yesterday in a cluster with these issues. A day later there is no mismatch :+1: 

Will apply it to some more clusters and wait a few days before closing. But it looks promising!

**Comment by aanm** [comment]
@splushii are things better so far?

**Comment by splushii** [comment]
Yes, no problems! Thanks!

**Comment by splushii** [comment]
@aanm Unfortunately I think I was to fast on the trigger. But fortunately it's clear why I missed it and the factor that triggers these symptoms.

From a sample of 4 (GKE) clusters there are 2 using preemptible node pools, and 2 using non-preemptible node pools. All running Cilium `1.8.4`.

1. Using preemptible node pools:
  - 30/42 IP mismatches
  - 13/26 IP mismatches
2. Using non-preemptible node pools
  - 0/25 IP mismatches
  - 0/9 IP mismatches

So it seems that using preemptible node pools is a sure trigger. I'm not sure what's the root cause though.

When testing before, all clusters used preemptible node pools. That's probably why we initially saw it in all clusters.

As you probably understand, this problem makes NetworkPolicies in the affected clusters useless (and even dangerous as it blocks traffic that should be allowed).

**Comment by aanm** [comment]
@splushii there were some more fixes backported to the 1.8. If you can, please try the `docker.io/cilium/cilium-operator:v1.8` image until we release 1.8.5 to see if the problem is fixed.

**Comment by splushii** [comment]
@aanm Using `cilium/operator-generic:v1.8` in one of the clusters with preemptible node pools.

It didn't garbage collect the mismatches. I manually restarted workloads to force all IP:s to match again. Let's see if they stay correct.

Logs from the `cilium-operator` attached.
[dev-operator-1.8-logs-2020-10-23.txt](https://github.com/cilium/cilium/files/5428405/dev-operator-1.8-logs-2020-10-23.txt)

**Comment by splushii** [comment]
Didn't work I'm afraid. There are now 19/43 IP mismatches.

Are you able to reproduce this?

Also, would `--disable-endpoint-crd` help in this situation or would it do more harm?

**Comment by splushii** [comment]
Saw there was a new `1.8` [operator-generic](https://hub.docker.com/layers/cilium/operator-generic/v1.8/images/sha256-80fe8941262119df42cca8a25894c0e4b8361c14f048d3512cd5466a6c2abf00?context=explore) since 10/23/2020 at 8:51 pm. Looking a lot better!

There are only 1/44 IP mismatches. Not sure if it's relevant, but it's the only `StatefulSet` in the cluster that's having an IP mismatch.

Logs from the `cilium-operator` attached.
[dev-operator-1.8-logs-2020-10-26.txt](https://github.com/cilium/cilium/files/5437735/dev-operator-1.8-logs-2020-10-26.txt)

**Comment by splushii** [comment]
A lot of back and forth here. Got 20/45 IP mismatches currently (in the same cluster as above).

What we see is that the Pods change IP (not sure why) and the CiliumEndpoints don't follow. This is an extract of the changes seen between 2020-10-26 14:04:09 and 2020-10-27 11:02:22:
```
<namespace> <resource name> <resource type> <IP>

 cert-manager cert-manager-5fb9b669c6-zcp85 CEP	10.8.1.91
-cert-manager cert-manager-5fb9b669c6-zcp85 POD	10.8.1.91
+cert-manager cert-manager-5fb9b669c6-zcp85 POD	10.8.1.16
 cert-manager cert-manager-cainjector-859bb67cf5-hngcj CEP	10.8.0.194
-cert-manager cert-manager-cainjector-859bb67cf5-hngcj POD	10.8.0.194
+cert-manager cert-manager-cainjector-859bb67cf5-hngcj POD	10.8.0.3
 cert-manager cert-manager-webhook-5c9df84957-87stn CEP	10.8.1.199
-cert-manager cert-manager-webhook-5c9df84957-87stn POD	10.8.1.199
+cert-manager cert-manager-webhook-5c9df84957-87stn POD	10.8.1.15
```

**Comment by fallard84** [comment]
We have the same issue. We deployed Cilium 1.9.2 on our GKE cluster. We also have preemptible nodes. Is there any update on this?

**Comment by fallard84** [comment]
Upon investigating further, only pods which have their network created before the kubelet gets restarted with Cilium (through the node-init daemonset) end up not being sync. The `nodeinit.restartPods` was not working on GKE with cos_containerd, so I hard turned it off, but now I see why it is mandatory to have it on. I will look into opening some PRs to fix the nodeinit.restartPods for GKE with code_containerd as I have previously identified the problem.
