### ISSUE TITLE
Byte counters (per-endpoint) for ingress and egress traffic

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#13173]
## Proposal / RFE

Per-endpoint **byte counters** for ingress and egress traffic, to account for the data coming to and leaving from a pod.

We already have partial accounting through the policy maps (`cilium bpf policy get <id>`), but this is not used if no policy lookup is performed in the datapath.

The counters would likely be stored to BPF maps (Per-endpoint maps? Hash map with endpoint id as key?), and we would need to dump the counters as metrics or from the command line.

Ideally, it would be interesting to have some flexibility and find a way to customise what traffic should be accounted for (All traffic? Only traffic to or from a given endpoint? Byte counter? Packet counter?).

**Comment by ti-mo** [comment]
Tentatively removed the `area/loader` label to clear up the overview as I don't think this is directly related. Let me know if it needs to be re-added.
