### ISSUE TITLE
Consider cilium cleanup in Helm post-delete hook

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13183]
Helm provides hooks for triggering additional logic when certain actions are performed:

https://helm.sh/docs/topics/charts_hooks/

It likely makes sense to add a post-delete hook to run a job with the cilium container to run `cilium cleanup` to remove the eBPF state from the system when the helm chart is removed.

**Comment by sayboras** [comment]
Is helm the recommended way to install cilium? As we also ship `quick-install.yaml` or `experimential-install.yaml` as well ?

**Comment by joestringer** [comment]
The documentation provides examples for both Helm-based install and just either quick-install YAML or helm template generation + kubectl apply. This suggestion would only directly work for `helm uninstall`, although if the implementation is a k8s job then maybe we could just provide that as a standalone YAML to assist uninstall for direct kubectl users as well.

**Comment by aanm** [comment]
Are we sure that `post-delete` hook is not executed on upgrades? That would be dangerous...

**Comment by sayboras** [comment]
I use pre hook before for upgrade path at work, but didn't try with post hook in general. I can spend sometime to give this one a try if you guys are fine.

**Comment by aanm** [comment]
@sayboras go for it :)

**Comment by sayboras** [comment]
Maybe wait for this one https://github.com/cilium/cilium/issues/13210 first, as this is big change.

**Comment by pchaigno** [comment]
There's an initial implementation at https://github.com/cilium/cilium/pull/13609 that could serve as a base for this `good-first-issue`.

**Comment by sayboras** [comment]
thanks for your reminder, this was clearly falling into crack during new year transition, let me continue with this.

**Comment by sayboras** [comment]
Forgot adding my findings on this, https://github.com/cilium/cilium/issues/15330 reminds me about this.

While doing the testing with post-delete hook, the cilium pod (with command as `cilium cleanup`) was failed to schedule. However, I also discovered cleanup should be done for `every` node, but helm hook didn't work well with clean-up step as daemon set. 

In short, while this issue seems to be trivial, it's not possible to achieve it with helm hook in my opinion.

**Comment by sayboras** [comment]
I am closing this issue as per above comment. Feel free to re-open if you think otherwise.
