### ISSUE TITLE
Cilium fails to start due to unavailable addresses

### ISSUE THREAD

**Issue by felixheinonen** [cilium/cilium#13217]
## Bug report

**General Information**

General Information

Cilium version 1.8.3 f842660 2020-09-16T15:05:27-07:00 go version go1.14.9 linux/amd64
docker tag v1.8 cilium@sha256:d80f2cc60a590f013d971e3006484b006ee724309459b02cd2b0128cc634ff40
Kernel version 4.14.193-149.317.amzn2.x86_64
Orchestration system version in use kube 1.15.11 on EKS

**How to reproduce the issue**
Cilium fails to start due to unavailable addresses. The following log is for t3a.small instance.  I can fix it by going in to ciliumnodes and changing to` first-interface-index: 0`  and to `pre-allocate: 4`.
```
cilium-agent
[Sep 18, 2020 2:23:09 PM GMT+3]
level=info msg="Using autodetected VPC CIDR." subsys=ipam vpc-cidr=10.253.0.0/16
cilium-agent
[Sep 18, 2020 2:23:09 PM GMT+3]
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=4 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-10-xxx-xxx-xxx.eu-west-1.compute.internal required=8 subsys=ipam
cilium-agent
[Sep 18, 2020 2:23:14 PM GMT+3]
level=info msg="Ignoring autodetected VPC CIDR." native-routing-cidr=10.xxx.0.0/16 subsys=ipam vpc-cidr=10.xxx.0.0/16

```
1. Install using Get started for EKS using helm, on existing self-managed nodes using t3a.micro and t3a.small instances

**Comment by christarazi** [comment]
I was able to reproduce this, thanks for the information. I will dig into this.

**Comment by ryanmt** [comment]
Just ran into it myself.  I suspected t3a.small as that was my instance type as well.  I can confirm that by changing to t3a.medium, the cilium-agent container was able to initialize successfully without any other modifications.

**Comment by ryanmt** [comment]
However, it appears that on a smaller instance on EKS, the kubelet believes it can schedule 17 pods, but the IP addresses are more constrained, meaning that `cilium status` reports 12/12 IPs consumed, while the scheduler is pushing more than 12 pods onto the node.  I'm starting to suspect that small nodes are unusable w/ cilium CNI out of the box.
