### ISSUE TITLE
cilium_cgroups_$WHERE is not listed in the bpf file system

### ISSUE THREAD

**Issue by Jianlin-lv** [cilium/cilium#13214]
**General Information**

- Cilium version: the latest master branch
- Kernel version
uname -a
Linux jianlin 5.9.0-rc1+ #3 SMP Thu Aug 20 09:05:37 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

cilium uses the following commands to load Cgroups prog:
```
# tc exec bpf pin /sys/fs/bpf/tc/globals/cilium_cgroups_sendmsg4  obj  bpf_sock.o  type sockaddr attach_type sendmsg4 sec sendmsg4
# bpftool cgroup attach /var/run/cilium/cgroupv2 sendmsg4  pinned /sys/fs/bpf/tc/globals/cilium_cgroups_sendmsg4  

root@jianlin:/home/cilium# bpftool cgroup tree
CgroupPath
ID       AttachType      AttachFlags     Name
/run/cilium/cgroupv2
5943     connect4
5938     connect6
5945     post_bind4
5940     post_bind6
5946     sendmsg4
5941     sendmsg6
5947     recvmsg4
5942     recvmsg6
5944     getpeername4
5939     getpeername6
```
According to my understanding, cilium_cgroups_sendmsg4 has been pinned, this file should be viewed in the /sys/fs/bpf/tc/globals/ directory, But actually there is no cilium_cgroups_sendmsg4 file in this directory;

After I execute the tc command again:
`tc exec bpf pin /sys/fs/bpf/tc/globals/cilium_cgroups_sendmsg4  obj  bpf_sock.o  type sockaddr attach_type sendmsg4 sec sendmsg4`
cilium_cgroups_sendmsg4  can be find in the /sys/fs/bpf/tc/globals/ directory.

```
root@jianlin:/var/run/cilium/state# ls /sys/fs/bpf/tc/globals/cilium_cgroups_sendmsg4
ls: cannot access '/sys/fs/bpf/tc/globals/cilium_cgroups_sendmsg4': No such file or directory
root@jianlin:/var/run/cilium/state#
root@jianlin:/var/run/cilium/state# tc exec bpf pin /sys/fs/bpf/tc/globals/cilium_cgroups_sendmsg4  obj  bpf_sock.o  type sockaddr attach_type sendmsg4 sec sendmsg4
root@jianlin:/var/run/cilium/state# ls /sys/fs/bpf/tc/globals/cilium_cgroups_sendmsg4
/sys/fs/bpf/tc/globals/cilium_cgroups_sendmsg4
```
Why does this happen?
I am not sure if this is an issue.

**Comment by borkmann** [comment]
Hello @Jianlin-lv the agent temporarily pins the prog in bpf fs: https://github.com/cilium/cilium/blob/master/bpf/init.sh#L355 We do not need to keep it there which is why it is removed after it got attached via bpftool. So very much intentional since there is no other benefit to keep it pinned after it was attached.

**Comment by Jianlin-lv** [comment]
Thanks for your reply, I will close this question. @borkmann
