### ISSUE TITLE
cilium IPAM - multiple ippools for one cluster in Cluster Mesh setup

### ISSUE THREAD

**Issue by maran-maran** [cilium/cilium#13227]
Hello. With calico-ipam, it is possible to setup multiple ippools(If there is no more space in one pool, node will get ips forom the other pool).
Is there any way how to get the same behavior with cilium ipam?

Our  setup/use-case:
- We have one shared address space for all our k8s clusters (for example 10.0.0.0/13).
- We do not know how they will scale. So we need to allocate IPs effectively (for example 10.0.0.0/19 for the 1st cluster, 10.0.32.0/19 for the 2nd... And in case there will be lack of IPs in the 1st cluster. We can add another /19 to it.).
- Using Native BGP Routing.
- We want to use cilium in Cluster Mesh setup.

I got an info via slack channel from @aanm that this feature is almost DONE .)
```
aanm  12 hours ago
oh got it, that makes sense. Can you open a GH issue with asking for that feature?
like I said, the underlying feature is almost done, only a couple changes will be needed
```

**Comment by wenxinlee2015** [comment]
In addition to the scenario where multiple IP pools are used to supplement IP addresses, I have another scenario here: In the same k8s cluster, computing nodes in different racks or regions will have different assigned IP blocks due to physical network restrictions. For example, rack1 needs to allocate the ip block in 192.168.0.0/24 for Pod, and rack2 needs to allocate the ip block for Pod in 192.168.2.0/24. Can this be handled by a similar processing method like pod ip pool + node selector?

**Comment by sznmaran** [comment]
Yes, it should be possible to label each subnet(IPPool). And use this label to assign IP from this pool to POD(s).

**Comment by jshin47** [comment]
Since this issue is still open, should I assume that when using Cluster Mesh, we must ensure that each cluster's `clusterPoolIPv4PodCIDR` is unique between clusters?  Like if I have cluster 0 with host IP CIDR 10.0.0.0/16, then maybe `clusterPoolIPv4PodCIDR` should be set to 10.200.0.0/16 , cluster 1 with host CIDR 10.1.0.0/16 with `clusterPoolIPv4PodCIDR` 10.201.0.0/16 ,etc ?

**Comment by oblazek** [comment]
> Since this issue is still open, should I assume that when using Cluster Mesh, we must ensure that each cluster's `clusterPoolIPv4PodCIDR` is unique between clusters? Like if I have cluster 0 with host IP CIDR 10.0.0.0/16, then maybe `clusterPoolIPv4PodCIDR` should be set to 10.200.0.0/16 , cluster 1 with host CIDR 10.1.0.0/16 with `clusterPoolIPv4PodCIDR` 10.201.0.0/16 ,etc ?

Something like that I suppose. But overall yes, each clusterPool should be unique so that any pod from any cluster has a unique IP and can communicate with the rest of the network.

**Comment by lx1036** [comment]
> In addition to the scenario where multiple IP pools are used to supplement IP addresses, I have another scenario here: In the same k8s cluster, computing nodes in different racks or regions will have different assigned IP blocks due to physical network restrictions. For example, rack1 needs to allocate the ip block in 192.168.0.0/24 for Pod, and rack2 needs to allocate the ip block for Pod in 192.168.2.0/24. Can this be handled by a similar processing method like pod ip pool + node selector?

@wenxinlee2015   cilium kubernetes ipam mode can resolve this issue. 
(1) use cilium kubernetes ipam, the cilium agent will use k8s node cidr allocated by kube-controller-manager. it will create CiliumNode with node spec podCidr, and then node.Annotations["io.cilium.network.ipv4-pod-cidr"] if has no node spec podCidr. 
see code: 
https://github.com/cilium/cilium/blob/v1.12.0-rc0/pkg/k8s/init.go#L190-L260
https://github.com/cilium/cilium/blob/v1.12.0-rc0/pkg/k8s/node.go#L52-L206

(2) deploy kube-controller-manager with --allocate-node-cidrs=false, and kube-controller-manager will not allocate pod cidr for every node.

(3) write an operator, watch IPPool crd and K8s Node, and choose ippool by k8s node selector, allocate pod cidr for node from the specified ippool, and update the K8s node annotation with the allocated cidr.

IPPool is like(inspired by calico ippool):
```yaml
apiVersion: ipam.k9s.io/v1
kind: IPPool
metadata:
  name: ippool1
spec:
  cidr: "100.20.30.0/24"
  blockSize: 27
  nodeSelector: "group/network=='default'"
```

So, it can use multi ippools in the cluster.

**Comment by Garagoth** [comment]
Well, possible, but seeing @lx1036 comments data is on Aprils Fools Day, I hope that this was not intended as a final solution.
I too have a need for separate IP pools based on labels to build topology aware network (that is a requirement from infrastructure).
Calico IPPools work here perfectly (but Calico has other issues that Cilium does not have), is it possible to achieve something similar in Cilium?
`pool1: {cidr: 1.2.3.0/16, nodeSelector: { matchLabels: {topology.kubernetes.io/region: r1}}}`
etc.
Nodes that have no pools cannot get any IP for a pod.

**Comment by ti-mo** [comment]
Ping, is this still relevant?

**Comment by oblazek** [comment]
As multipool ipam has been implemented I think this is ready to be closed.

**Comment by ti-mo** [comment]
Thanks!
