### ISSUE TITLE
kubeProxyReplacement=strict,scheduler and controller can't be healthy          

### ISSUE THREAD

**Issue by liweilun1** [cilium/cilium#13231]
I use this command to install kubernetes 
kubeadm init --image-repository registry.aliyuncs.com/google_containers  --kubernetes-version=stable  --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=172.16.30.29 --skip-phases=addon/kube-proxy;

and i use helm install cilium
helm install cilium cilium/cilium     --namespace kube-system --set nodeinit.restartPods=true     --set global.autoDirectNodeRoutes=true --set global.hostServices.enabled=true     --set global.kubeProxyReplacement=strict     --set global.nodePort.mode=hybrid     --set global.k8sServiceHost=172.16.30.29     --set global.k8sServicePort=6443

i don't apply any Network policies

[root@master ~]# kubectl get pods -A
kube-system     cilium-lbk6b                            1/1     Running   0          3h4m
kube-system     cilium-operator-59794ff449-jm8wf        0/1     Pending   0          3h4m
kube-system     cilium-operator-59794ff449-r62nx        1/1     Running   1          9h
kube-system     coredns-6d56c8448f-4xmxt                1/1     Running   1          9h
kube-system     coredns-6d56c8448f-qntgc                1/1     Running   1          9h
kube-system     etcd-master                             1/1     Running   1          9h
kube-system     kube-apiserver-master                   1/1     Running   1          9h
kube-system     kube-controller-manager-master          1/1     Running   1          9h
kube-system     kube-scheduler-master                   1/1     Running   1          9h

[root@master ~]# kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                       ERROR
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused
controller-manager   Unhealthy   Get "http://127.0.0.1:10252/healthz": dial tcp 127.0.0.1:10252: connect: connection refused
etcd-0               Healthy     {"health":"true"}

the firewall and selinux always closed

how can i make the scheduler and  controller healthy？

**Comment by liweilun0408** [comment]
the firewall and selinux always closed

**Comment by aanm** [comment]
@liweilun0408 That behavior is not because of Cilium. Check https://github.com/kubernetes/kubeadm/issues/2222 for more info.
