### ISSUE TITLE
CI: K8sPolicyTest Multi-node policy test validates ingress CIDR-dependent L4 connectivity is restored after importing ingress policy

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#13256]
CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Monitor output does not show traffic as allowed
Expected
    <int>: 47
to be >=
    <int>: 49
/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/k8sT/Policies.go:1276
```
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/542/testReport/junit/Suite-k8s-1/12/K8sPolicyTest_Multi_node_policy_test_validates_ingress_CIDR_dependent_L4_connectivity_is_restored_after_importing_ingress_policy/attachments/f5c2e1d1_K8sPolicyTest_Multi-node_policy_test_validates_ingress_CIDR-dependent_L4_connectivity_is_restored_after_importing_ingress_policy.zip

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/542/testReport/junit/Suite-k8s-1/12/K8sPolicyTest_Multi_node_policy_test_validates_ingress_CIDR_dependent_L4_connectivity_is_restored_after_importing_ingress_policy/

Hit on #12831

**Comment by christarazi** [comment]
Is this the same as https://github.com/cilium/cilium/issues/12596?

**Comment by aditighag** [comment]
> Is this the same as #12596?

K8sPolicyTest Multi-node policy test validates ingress CIDR-dependent L4 (FromCIDR + ToPorts) connectivity is restored after importing ingress policy vs K8sPolicyTest Multi-node policy test validates ingress CIDR-dependent L4 connectivity is restored after importing ingress policy (this PR)

The link from #12596 isn't available anymore so I can't check the test details. @pchaigno Are these same tests?

**Comment by pchaigno** [comment]
Yes, that's the same test according to the title and the same failure according to the stacktrace. Sorry about this @aditighag, it looks like I don't remember all the flake issues I've opened :-/
