### ISSUE TITLE
Fix unit tests for arm64 with race detector

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#13252]
They are being enabled in PR https://github.com/cilium/cilium/pull/12789 and seem to be currently failing.
```
Successfully built 7ecfbcaed6e7
Successfully tagged cilium/docs-builder:latest
rm -rf cmdref/cilium*.md
docker container run --rm --workdir /src/Documentation --volume /home/travis/gopath/src/github.com/cilium/cilium/Documentation/..:/src --env READTHEDOCS_VERSION= --env SKIP_LINT= --user "2000:2000" cilium/docs-builder ./update-cmdref.sh
Error relocating /src/cilium/cilium: __vfprintf_chk: symbol not found
Error relocating /src/cilium/cilium: __fprintf_chk: symbol not found
make[1]: *** [Makefile:30: update-cmdref] Error 127
make[1]: Leaving directory '/home/travis/gopath/src/github.com/cilium/cilium/Documentation'
make: *** [Makefile:563: postcheck] Error 2
travis_time:end:0a33cb72:start=1600785661326828654,finish=1600785908767495842,duration=247440667188,event=script
[0K[31;1mThe command "./.travis/build.sh" exited with 2.[0m


Done. Your build exited with 1.
```

**Comment by errordeveloper** [comment]
This is definitely the case of of binaries being compiled agains a different glibc, namely we compile e.g. `cilium-agent` on the host, and then we trying to run that binary inside docs builder container. Can this race detector job skip `update-cmdref` make target?

**Comment by aanm** [comment]
> This is definitely the case of of binaries being compiled agains a different glibc, namely we compile e.g. `cilium-agent` on the host, and then we trying to run that binary inside docs builder container. Can this race detector job skip `update-cmdref` make target?

Sure, if it doesn't matter is just a matter of adding an if statement to skip the `update-cmdref` on unit testing

**Comment by gandro** [comment]
This issue seems still present on master: https://app.travis-ci.com/github/cilium/cilium/jobs/538335647

**Comment by ti-mo** [comment]
We're building the test suite with CGO_ENABLED=0 for a while now. (murmur3 test used to link against a C implementation for comparison)

Do we still want to run with race detector enabled on arm64? We already run them on amd64, not sure if there's a benefit.

**Comment by aanm** [comment]
Agreed with what Timo wrote. Closing.
