### ISSUE TITLE
All egress traffic dropped after cilium-agent quits

### ISSUE THREAD

**Issue by anfernee** [cilium/cilium#13254]
## Bug report

When both ENABLE_IPV4 and ENABLE_IPV6 is enabled, after cilium-agent quits, all the egress traffic will be dropped. The traffic is back to normal after tc egress hook on native nic is deleted.

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.8.90 e9243ff8c 2020-09-09T17:29:45+03:00 go version go1.15.2 linux/amd64
Daemon: 1.8.90 e9243ff8c 2020-09-09T17:29:45+03:00 go version go1.15.2 linux/amd64
```
- Kernel version (run `uname -a`)
```
Linux host-3 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.4400", GitCommit:"c69ed9f0e9f49361d6457e486b56ac1cfc16a32a", GitTreeState:"clean", BuildDate:"2020-08-27T09:22:13Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

1. create k8s cluster, deploy cilium and enable both ipv4 and ipv6
2. Delete one cilium-agent pod: `kubectl -n kube-system delete pod cilium-abc`
3. The deleted pod will be stuck at `Terminating` state

## Cause

The root cause is the following tail call is not called: https://github.com/cilium/cilium/blob/86858947d0e52d48c0b31fd496467b07bbed3c79/bpf/lib/nodeport.h#L1488-L1501 

Further debugging showed that one of the ebpf map disappeared after the cilium-agent quits. 

Before cilium-agent quits:
```
root@host-3:/sys/fs/bpf/tc/globals# bpftool map show pinned ./cilium_calls_netdev_00005
98: prog_array  flags 0x0
	key 4B  value 4B  max_entries 25  memlock 4096B
	owner_prog_type sched_cls  owner jited
root@host-3:/sys/fs/bpf/tc/globals# bpftool map show pinned ./cilium_calls_netdev_00002
99: prog_array  flags 0x0
	key 4B  value 4B  max_entries 25  memlock 4096B
	owner_prog_type sched_cls  owner jited
```

After cilium-agent quits
```
# bpftool map show id 98
Error: ...: No such file or directory
```

**Comment by joestringer** [comment]
Thanks for the report! PROG_ARRAY maps have special properties for reference management to ensure that the resources are cleaned up properly when the programs are removed. I wonder if there's some piece we're missing when comparing the netdev calls map vs. the other calls maps that the agent creates.

**Comment by anfernee** [comment]
Some additional information about this bug: 

netdev_00002 is the external nic, the map was there, but all items were deleted.
netdev_00005 is cilium_net, the was deleted

I found it only happens when bpffs was not mounted on host. Those 2 maps are will be there if bpffs was mounted on the host.

**Comment by pchaigno** [comment]
> I found it only happens when bpffs was not mounted on host. Those 2 maps are will be there if bpffs was mounted on the host.

I don't understand. How can bpffs not be mounted on the host when Cilium was running?

**Comment by anfernee** [comment]
bpffs was mounted in cilium-agent container, not in the host to begin with. I saw the following warning in the cilium log: 

https://github.com/cilium/cilium/blob/1536acec32f47e098b811ceaaa5ce536ab565de7/pkg/bpf/bpffs_linux.go#L121-L128

Still I think there is something on cilium side (or kernel) to fix. Without the mount, it shouldn't behave like that. Because the bpffs was mounted inside the container, the filesystem was unmounted together with the container destroyed, so the refcount to the bpf map is gone as well. The strange thing is map `bpf_netdev_00005(cilium_net)` was deleted. map `bpf_netdev_00002 (eth0)` was emptied which caused the egress problem.

**Comment by joestringer** [comment]
@anfernee oh, I think the lack of persistent BPFFS explains it. BPFFS is keeping the reference count alive for the tail call programs via the tail call map, so if the BPFFS is not persistent and hence the tail call map is not kept bound to the filesystem, then the map will be tidied up and to prevent leaking of BPF programs, the programs references will be cleaned up.

I'm not sure I understand the timing of events for the cilium_net / eth0 map observations you have though.

**Comment by anfernee** [comment]
Thanks @joestringer for the explanation. When you say tidied up, do you mean empty calls map with no entries, or the map itself was deleted. The reason I ask is I saw cilium_net's map got deleted, eth0's map exists, but has 0 entries. Of course, everything works when I mount BPFFS on host.

**Comment by joestringer** [comment]
@anfernee How are you observing this exactly, ie, where are you running the commands to observe this, what is the state of Cilium at the points when you are making the observations, and what is the command+output?

**Comment by anfernee** [comment]
Before cilium-agent quits:
```
root@host-3:/sys/fs/bpf/tc/globals# bpftool map show pinned ./cilium_calls_netdev_00005
98: prog_array  flags 0x0
	key 4B  value 4B  max_entries 25  memlock 4096B
	owner_prog_type sched_cls  owner jited
root@host-3:/sys/fs/bpf/tc/globals# bpftool map show pinned ./cilium_calls_netdev_00002
99: prog_array  flags 0x0
	key 4B  value 4B  max_entries 25  memlock 4096B
	owner_prog_type sched_cls  owner jited
```

After cilium-agent quits. 
```
# bpftool map show id 98
Error: ...: No such file or directory
# bpftool map dump id 99
0 Entries
```

In the meantime, the following commands are not responding: 
```
curl google.com
ping 8.8.8.8
```

Until: 
```
# tc filter del dev eth0 egress
```

**Comment by mrostecki** [comment]
Maybe it would make sense to "manually" remove the tc filter when cilium-agent is handling SIGTERM or as a part of the preStop hook?

**Comment by anfernee** [comment]
this behavior was observed when bpffs was not mounted on host. without refcount from bpffs, the call map was dropped when cilium-agent exited. When bpffs is mounted, it works fine.

**Comment by joestringer** [comment]
@mrostecki I think we're open to such a change, as long as we make absolutely 100% sure this isn't going to remove the Cilium datapath during a standard restart or upgrade.

**Comment by joestringer** [comment]
However, reading @anfernee 's latest update I think this is simply a problem of not deploying Cilium with BPFFS enabled on the underlying host. This is definitely the expectation for any production environment and really I don't see a reason why *not* mount it all the time. Many distributions would already do this by default, which I guess may imply why it's not currently listed under the [System Requirements](https://docs.cilium.io/en/v1.8/operations/system_requirements/). Maybe the only change we need is to clarify that the BPFFS is required to prevent traffic interruption during Cilium restart/upgrade.

**Comment by pchaigno** [comment]
> Many distributions would already do this by default, which I guess may imply why it's not currently listed under the [System Requirements](https://docs.cilium.io/en/v1.8/operations/system_requirements/). Maybe the only change we need is to clarify that the BPFFS is required to prevent traffic interruption during Cilium restart/upgrade.
> 
> EDIT: Oh, weirder still, it _is_ listed as a requirement, only it's under the k8s section here:
> https://docs.cilium.io/en/v1.8/concepts/kubernetes/requirements/#mounted-bpf-filesystem

Yep. Given that, I'm tempted to think we should close this issue as resolved. @anfernee Is there anything else you think we should implement or document for this situation?

**Comment by anfernee** [comment]
The only thing is to clarify the potential impact. In https://docs.cilium.io/en/v1.8/concepts/kubernetes/requirements/#mounted-bpf-filesystem it says:

```
This in turn will cause BPF resources to be re-created which will cause network connectivity to be disrupted. 
```

The actual situation could be more serious than that.

**Comment by mrostecki** [comment]
@joestringer OK, then I agree that such a change is not needed.

@anfernee Maybe it's a good idea just add 1-2 sentences that lack of /sys/fs/bpf is more serious (in this case - it prevents successful quits of cilium-agent) and is mandatory for all clusters, even non-production environments.

**Comment by joestringer** [comment]
@anfernee Do you have more specific concerns?

I suspect that "network connectivity disruption" is correct, although in context of the sentence may give the impression of temporary impact rather than ongoing impact. I suspect that this factor varies depending on how Cilium is configured, and was perhaps more true in the past than it is now so it could make sense to broaden the scope with something like the following (suggestion, open to further feedback):

"This in turn may will cause BPF resources to remove which may impact forwarding until the BPF filesystem is remounted and Cilium restarts."
