### ISSUE TITLE
Restore clusterIP service after the local-redirect service entry is removed

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#13268]
When a user installs a `LocalRedirectPolicy` for a clusterIP service, cilium agent overrides the current clusterIP service entry with a local-redirect service with node-local backends. However, when the local-redirect service entry is removed, either when node-local backends are deleted or the LRP is deleted, we should restore the original clusterIP service with all the available (local + remote) backends at the time of restore.

**Comment by aditighag** [comment]
@Weil0ng We can do something similar to how `correlateEndpoints` is called upon updateService - https://github.com/cilium/cilium/blob/master/pkg/k8s/service_cache.go#L185

**Comment by Weil0ng** [comment]
Question, do we need to retain the same service id in lbmap when restoring original service? I don't see a particular reason that we have to but maybe I missed something?
