### ISSUE TITLE
update helpers.bash function to ensure all functions time out after a specified duration

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1326]
Some of the functions in `tests/helpers.bash` infinitely loop until a certain desired state is realized. However, if this state is never realized, the code infinitely loops. When such a loop occurs in a PR, the test hits the Jenkins timeout, and we can't get any logs from the build. This also ensures that code changes do not introduce performance issues in the code, as we can set the timeout for each command as a ceiling for the amount of time each command should take.

**Comment by ianvernon** [comment]
Adding 'high priority' label because we can't get any bugs due to this issue in CI failures, and as such can't increase the stability of our CI.

**Comment by aalemayhu** [comment]
This a duplicate of #1189 but will close the older one in favor of this.

**Comment by ianvernon** [comment]
Thanks for choosing #1189 @scanf ! I should have checked the backlog before making this.
