### ISSUE TITLE
[DOC] Missing docs about installation using kubeadm 

### ISSUE THREAD

**Issue by manuelbuil** [cilium/cilium#13278]
## Bug report

When searching for information about how to install Cilium CNI with kubeadm, the documentation promises to find the instructions to install Cilium on K8s in [the official Kubernetes documentation](https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-kubeadm/). However, the link shows no instructions, just general CNI information. I think that link used to show the instructions for several CNI plugins but probably it was removed and thus the link is useless now.

This is the link ==> https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-kubeadm/

**Comment by mrostecki** [comment]
Huh, that page in k8s documentation:

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

used to have information how to deploy the most popular CNI plugins (IIRC also Calico, Weave), but it's not there anymore. @aanm were you aware of it being removed?

**Comment by aanm** [comment]
@mrostecki yes, that page was removed from Kubernetes. We should update the documentation to have kubeadm instructions that were on that page.

**Comment by mrostecki** [comment]
OK, I will add it then.
