### ISSUE TITLE
CI: v1.7: "K8sDatapathConfig ManagedEtcd Check connectivity with managed etcd" backport needed

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/cilium#13282]
[This](https://github.com/cilium/cilium/pull/11544) needs to be backported to v1.7.
The problem is also reported [here](https://github.com/cilium/cilium/issues/12777)
Failures:
https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/1887/
https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/1886/
https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/1885/

**Comment by nathanjsweet** [comment]
https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/1901/

**Comment by christarazi** [comment]
Fixed by https://github.com/cilium/cilium/pull/13574
