### ISSUE TITLE
L7 CNP not working correctly

### ISSUE THREAD

**Issue by manuelbuil** [cilium/cilium#13280]
## Bug report

**General Information**

- Cilium version
Client: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64
Daemon: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64

- Kernel version (run `uname -a`)
4.12.14-lp151.28.44-default #1 SMP Fri Mar 20 18:20:20 UTC 2020 (dbf1aea) x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use K8s 1.18.6
- Link to relevant artifacts: Installed Cilium through:
`kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.8/examples/kubernetes/connectivity-check/connectivity-check.yaml`

**Description**
I have two pods running in the same node. httpbin acts as a HTTP server and the multitool as a HTTP client.:
```
NAME                         READY   STATUS    RESTARTS   AGE   IP             NODE                           NOMINATED NODE   READINESS GATES   LABELS
httpbin-66cdbdb6c5-jqtn2     1/1     Running   0          2d    10.244.1.170   caasp-worker-caasp-cluster-0   <none>           <none>            app=httpbin,pod-template-hash=66cdbdb6c5,version=v1
multitool-7f647bbbd7-8jtpg   1/1     Running   0          2d    10.244.1.156   caasp-worker-caasp-cluster-0   <none>           <none>            app=multitool,pod-template-hash=7f647bbbd7

```
From the multitool pod, I can execute these two commands successfully:
```
kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -I http://10.244.1.170:80/ip
kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -I http://10.244.1.170:80/status/200
```

Now, based on this yaml: https://github.com/cilium/cilium/blob/master/test/k8sT/manifests/l7-policy.yaml, I created the following L7 policy:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "myCNP"
metadata:
  name: "rule1"
spec:
  endpointSelector:
    matchLabels:
      app: httpbin
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: multitool
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/status"
```
My expectation is that when querying the /ip it will fail but I can still query /status/200 successfully. However:

```
$> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -I http://10.244.1.170:80/ip
HTTP/1.1 403 Forbidden
content-length: 15
content-type: text/plain
date: Thu, 24 Sep 2020 15:55:38 GMT
server: envoy

$> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -I http://10.244.1.170:80/status/200
HTTP/1.1 403 Forbidden
content-length: 15
content-type: text/plain
date: Thu, 24 Sep 2020 15:55:44 GMT
server: envoy
```
I can see that cilium-envoy process started and there is an envoy listener configured on port 18848:
`cilium-http-ingress:18848::[::]:18848`

When checking the envoy configuration, I am surprised that I don't see port 80 or the "status" path in the http filter, so I suspect something is wrong in envoy but as I am not familiar, I am not sure. Here is the config:
```
   "dynamic_listeners": [
    {
     "name": "cilium-http-ingress:18848",
     "active_state": {
      "version_info": "2",
      "listener": {
       "@type": "type.googleapis.com/envoy.api.v2.Listener",
       "name": "cilium-http-ingress:18848",
       "address": {
        "socket_address": {
         "address": "::",
         "port_value": 18848,
         "ipv4_compat": true
        }
       },
       "filter_chains": [
        {
         "filters": [
          {
           "name": "cilium.network"
          },
          {
           "name": "envoy.http_connection_manager",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
            "stat_prefix": "proxy",
            "route_config": {
             "virtual_hosts": [
              {
               "name": "default_route",
               "domains": [
                "*"
               ],
               "routes": [
                {
                 "match": {
                  "prefix": "/",
                  "grpc": {}
                 },
                 "route": {
                  "cluster": "ingress-cluster",
                  "timeout": "3600s",
                  "retry_policy": {
                   "retry_on": "5xx",
                   "num_retries": 3,
                   "per_try_timeout": "0s"
                  },
                  "max_grpc_timeout": "0s"
                 }
                },
                {
                 "match": {
                  "prefix": "/"
                 },
                 "route": {
                  "cluster": "ingress-cluster",
                  "timeout": "3600s",
                  "retry_policy": {
                   "retry_on": "5xx",
                   "num_retries": 3,
                   "per_try_timeout": "0s"
                  }
                 }
                }
               ]
              }
             ]
            },
            "http_filters": [
             {
              "name": "cilium.l7policy",
              "typed_config": {
               "@type": "type.googleapis.com/cilium.L7Policy",
               "access_log_path": "/var/run/cilium/access_log.sock"
              }
             },
             {
              "name": "envoy.router"
             }
            ],
            "stream_idle_timeout": "0s"
           }
          }
         ]
        },
```

Any idea what might be wrong or where to look at? Logs don't show anything bad:
```
level=info msg="Policy Add Request" ciliumNetworkPolicy="[&{EndpointSelector:{\"matchLabels\":{\"any:app\":\"httpbin\",\"k8s:io.kubernetes.pod.namespace\":\"default\"}} NodeSelector:{} Ingress:[{FromEndpoints:[{\"matchLabels\":{\"any:app\":\"multitool\",\"k8s:io.kubernetes.pod.namespace\":\"default\"}}] FromRequires:[] ToPorts:[{Ports:[{Port:80 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:0xc001b0eaf0}] FromCIDR: FromCIDRSet:[] FromEntities:[] aggregatedSelectors:[]}] Egress:[] Labels:[k8s:io.cilium.k8s.policy.derived-from=CiliumNetworkPolicy k8s:io.cilium.k8s.policy.name=rule1 k8s:io.cilium.k8s.policy.namespace=default k8s:io.cilium.k8s.policy.uid=46ad18f8-17e2-40d8-b984-659347708a50] Description:}]" policyAddRequest=272ff13e-fe80-11ea-94f0-525400729be5 subsys=daemon
level=info msg="Policy imported via API, recalculating..." policyAddRequest=272ff13e-fe80-11ea-94f0-525400729be5 policyRevision=8 subsys=daemon
level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=rule1 k8sApiVersion= k8sNamespace=default subsys=k8s-watcher
level=warning msg="[[external/envoy/source/server/listener_impl.cc:196] Listener connection limit runtime key envoy.resource_limits.listener.cilium-http-ingress:18848.connection_limit is empty. There are currently no limitations on the number of accepted connections for listener cilium-http-ingress:18848." subsys=envoy-config threadID=536
level=info msg="[[external/envoy/source/server/lds_api.cc:73] lds: add/update listener 'cilium-http-ingress:18848'" subsys=envoy-upstream threadID=536
level=info msg="Rewrote endpoint BPF program" containerID=caa1305f64 datapathPolicyRevision=7 desiredPolicyRevision=8 endpointID=253 identity=31435 ipv4=10.244.1.170 ipv6= k8sPodName=default/httpbin-66cdbdb6c5-jqtn2 subsys=endpoint
```

**Comment by aanm** [comment]
@manuelbuil does `kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -I http://10.244.1.170:80/status` work?

**Comment by manuelbuil** [comment]
> @manuelbuil does `kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -I http://10.244.1.170:80/status` work?

Same:

```
$> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -I http://10.244.1.170:80/status
HTTP/1.1 403 Forbidden
content-length: 15
content-type: text/plain
date: Thu, 24 Sep 2020 16:25:02 GMT
server: envoy
```

**Comment by christarazi** [comment]
@manuelbuil Doing `curl -I` will send a `HEAD` request, which is not allowed by your policy. The policy only allows `GET`.

**Comment by manuelbuil** [comment]
> @manuelbuil Doing `curl -I` will send a `HEAD` request, which is not allowed by your policy. The policy only allows `GET`.

I think you are confusing -I with -H. As far as I know, -I sends the GET request but only prints what is called the "document info only" where the HTTP code of the response can be easily seen. Look:

```
$> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl http://10.244.1.170:80/status/200
Access denied
$> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -X GET http://10.244.1.170:80/status/200
Access denien
$> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -X GET -I http://10.244.1.170:80/status/200
HTTP/1.1 403 Forbidden
content-length: 15
content-type: text/plain
date: Fri, 25 Sep 2020 11:53:43 GMT
server: envoy
```

**Comment by christarazi** [comment]
> > @manuelbuil Doing `curl -I` will send a `HEAD` request, which is not allowed by your policy. The policy only allows `GET`.
> 
> I think you are confusing -I with -H. As far as I know, -I sends the GET request but only prints what is called the "document info only" where the HTTP code of the response can be easily seen. Look:
> 
> ```
> $> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl http://10.244.1.170:80/status/200
> Access denied
> $> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -X GET http://10.244.1.170:80/status/200
> Access denien
> $> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -X GET -I http://10.244.1.170:80/status/200
> HTTP/1.1 403 Forbidden
> content-length: 15
> content-type: text/plain
> date: Fri, 25 Sep 2020 11:53:43 GMT
> server: envoy
> ```

You may be right. On my version of `curl`, if I just have a standalone `-I` it will send a `HEAD` request. If I have `-X GET -I`, only then will it do what you described.

Either way I am unable to reproduce the issue on `1.8.3`. I applied the same policy as you and it's working for me.

![image](https://user-images.githubusercontent.com/3885308/94318147-b3ed1080-ff3c-11ea-998c-c104f6d283ad.png)

**Comment by manuelbuil** [comment]
> > > @manuelbuil Doing `curl -I` will send a `HEAD` request, which is not allowed by your policy. The policy only allows `GET`.
> > 
> > 
> > I think you are confusing -I with -H. As far as I know, -I sends the GET request but only prints what is called the "document info only" where the HTTP code of the response can be easily seen. Look:
> > ```
> > $> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl http://10.244.1.170:80/status/200
> > Access denied
> > $> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -X GET http://10.244.1.170:80/status/200
> > Access denien
> > $> kubectl exec -ti multitool-7f647bbbd7-8jtpg -- curl -X GET -I http://10.244.1.170:80/status/200
> > HTTP/1.1 403 Forbidden
> > content-length: 15
> > content-type: text/plain
> > date: Fri, 25 Sep 2020 11:53:43 GMT
> > server: envoy
> > ```
> 
> You may be right. On my version of `curl`, if I just have a standalone `-I` it will send a `HEAD` request. If I have `-X GET -I`, only then will it do what you described.
> 
> Either way I am unable to reproduce the issue on `1.8.3`. I applied the same policy as you and it's working for me. In order for you to allow requests to `/status/200` and etc, the `path` part of the policy accepts a regex, so you'd need something like:
> 
> ```
> path: /status/[0-9]+
> ```
> 
> ![image](https://user-images.githubusercontent.com/3885308/94318147-b3ed1080-ff3c-11ea-998c-c104f6d283ad.png)

Thanks for the reply. I wonder what is different in my deployment...

Can you show me the dynamic_listeners in your envoy configuration please? I'd like to see if you have something different there because I suspect my envoy config is wrong as, foe example, I see no "/status/" path whatsoever in the filter even though I configured it. I normally get that config by executing `curl -X GET --unix-socket /var/run/cilium/envoy-admin.sock http:/help/config_dump` inside the cilium-agent where the proxy is running

**Comment by christarazi** [comment]
Here's my dynamic listeners (no `/status` either):

```
   "dynamic_listeners": [
    {
     "name": "cilium-http-ingress:13579",
     "active_state": {
      "version_info": "2",
      "listener": {
       "@type": "type.googleapis.com/envoy.api.v2.Listener",
       "name": "cilium-http-ingress:13579",
       "address": {
        "socket_address": {
         "address": "::",
         "port_value": 13579,
         "ipv4_compat": true
        }
       },
       "filter_chains": [
        {
         "filters": [
          {
           "name": "cilium.network"
          },
          {
           "name": "envoy.http_connection_manager",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
            "stat_prefix": "proxy",
            "route_config": {
             "virtual_hosts": [
              {
               "name": "default_route",
               "domains": [
                "*"
               ],
               "routes": [
                {
                 "match": {
                  "prefix": "/",
                  "grpc": {}
                 },
                 "route": {
                  "cluster": "ingress-cluster",
                  "timeout": "3600s",
                  "retry_policy": {
                   "retry_on": "5xx",
                   "num_retries": 3,
                   "per_try_timeout": "0s"
                  },
                  "max_grpc_timeout": "0s"
                 }
                },
                {
                 "match": {
                  "prefix": "/"
                 },
                 "route": {
                  "cluster": "ingress-cluster",
                  "timeout": "3600s",
                  "retry_policy": {
                   "retry_on": "5xx",
                   "num_retries": 3,
                   "per_try_timeout": "0s"
                  }
                 }
                }
               ]
              }
             ]
            },
            "http_filters": [
             {
              "name": "cilium.l7policy",
              "typed_config": {
               "@type": "type.googleapis.com/cilium.L7Policy",
               "access_log_path": "/var/run/cilium/access_log.sock"
              }
             },
             {
              "name": "envoy.router"
             }
            ],
            "stream_idle_timeout": "0s"
           }
          }
         ]
        },
        {
         "filter_chain_match": {
          "transport_protocol": "tls"
         },
         "filters": [
          {
           "name": "cilium.network"
          },
          {
           "name": "envoy.http_connection_manager",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
            "stat_prefix": "proxy",
            "route_config": {
             "virtual_hosts": [
              {
               "name": "default_route",
               "domains": [
                "*"
               ],
               "routes": [
                {
                 "match": {
                  "prefix": "/",
                  "grpc": {}
                 },
                 "route": {
                  "cluster": "ingress-cluster-tls",
                  "timeout": "3600s",
                  "retry_policy": {
                   "retry_on": "5xx",
                   "num_retries": 3,
                   "per_try_timeout": "0s"
                  },
                  "max_grpc_timeout": "0s"
                 }
                },
                {
                 "match": {
                  "prefix": "/"
                 },
                 "route": {
                  "cluster": "ingress-cluster-tls",
                  "timeout": "3600s",
                  "retry_policy": {
                   "retry_on": "5xx",
                   "num_retries": 3,
                   "per_try_timeout": "0s"
                  }
                 }
                }
               ]
              }
             ]
            },
            "http_filters": [
             {
              "name": "cilium.l7policy",
              "typed_config": {
               "@type": "type.googleapis.com/cilium.L7Policy",
               "access_log_path": "/var/run/cilium/access_log.sock"
              }
             },
             {
              "name": "envoy.router"
             }
            ],
            "stream_idle_timeout": "0s"
           }
          }
         ],
         "transport_socket": {
          "name": "cilium.tls_wrapper"
         }
        }
       ],
       "listener_filters": [
        {
         "name": "cilium.bpf_metadata",
         "typed_config": {
          "@type": "type.googleapis.com/cilium.BpfMetadata",
          "bpf_root": "/sys/fs/bpf",
          "is_ingress": true
         }
        },
        {
         "name": "envoy.listener.tls_inspector"
        }
       ],
       "transparent": true,
       "socket_options": [
        {
         "description": "Listener socket mark",
         "level": "1",
         "name": "36",
         "int_value": "2560"
        }
       ]
      },
      "last_updated": "2020-09-25T21:18:52.577Z"
     }
    }
   ]
```

**Comment by jrajahalme** [comment]
@manuelbuil Cilium will not add any port or path into Envoy listeners, as the Cilium filters you see on the filter take care of the policy enforcement according to the policy sent by Cilium agent. Some additional notes:

- Your policy allows only the path `/status` with method `GET` nothing else. You will need to add a regex to allow anything starting with `/status`: `/status.*`
- Use `curl` with `-v` to see more about what is going on
  - Using this I see that `curl -I` will use `HEAD` method, which is forbidden
- Use `kubectl exec -it -n kube-system cilium-xxxxx -- cilium monitor -v --type drop --type l7` on the destination node to see what is being dropped, e.g.:
```
$ kubectl exec -it -n kube-system cilium-7cgpg -- cilium monitor -v --type drop --type l7 
Listening for events on 2 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
<- Request http from 0 ([k8s:appz=runtime k8s:io.cilium.k8s.policy.cluster=default k8s:io.kubernetes.pod.name=runtime k8s:io.kubernetes.pod.namespace=default]) to 101 ([k8s:io.cilium.k8s.policy.serviceaccount=clustermesh-apiserver k8s:io.cilium.k8s.policy.cluster=default k8s:name=clustermesh-apiserver k8s:io.kubernetes.pod.namespace=kube-system]), identity 27677->25779, verdict Denied HEAD http://10.0.0.238/status => 403
```

**Comment by manuelbuil** [comment]
> @manuelbuil Cilium will not add any port or path into Envoy listeners, as the Cilium filters you see on the filter take care of the policy enforcement according to the policy sent by Cilium agent. Some additional notes:
> 
> * Your policy allows only the path `/status` with method `GET` nothing else. You will need to add a regex to allow anything starting with `/status`: `/status.*`
> * Use `curl` with `-v` to see more about what is going on
>   
>   * Using this I see that `curl -I` will use `HEAD` method, which is forbidden by your policy
> * Use `kubectl exec -it -n kube-system cilium-xxxxx -- cilium monitor -v --type drop --type l7` on the destination node to see what is being dropped, e.g.:
> 
> ```
> $ kubectl exec -it -n kube-system cilium-7cgpg -- cilium monitor -v --type drop --type l7 
> Listening for events on 2 CPUs with 64x4096 of shared memory
> Press Ctrl-C to quit
> <- Request http from 0 ([k8s:appz=runtime k8s:io.cilium.k8s.policy.cluster=default k8s:io.kubernetes.pod.name=runtime k8s:io.kubernetes.pod.namespace=default]) to 101 ([k8s:io.cilium.k8s.policy.serviceaccount=clustermesh-apiserver k8s:io.cilium.k8s.policy.cluster=default k8s:name=clustermesh-apiserver k8s:io.kubernetes.pod.namespace=kube-system]), identity 27677->25779, verdict Denied HEAD http://10.0.0.238/status => 403
> ```

Thanks a lot @jrajahalme . This is really useful information and other people might benefit from it. What if I add it to the wiki or to a docs section? If you guys believe this could be useful, I could spend time on that.

A question I still have: is it possible to dump the config of the cilium.l7policy filter? Somewhere where, for example, I could see that "path: status/.*" was correctly configured in the Envoy filter

@christarazi you were right regarding the -I flag. I had misunderstood it, sorry for confusing you and thanks for your help too

**Comment by jrajahalme** [comment]
@manuelbuil Currently it is not possible to dump the policy config Cilium sends to Envoy. Closest thing we have is the `policy.realized` part of the `cilium endpoint get <NN>` output, some of which is *not* sent to Envoy (e.g., DNS rules).

It would be useful if you could contribute some text that you find helpful!

**Comment by christarazi** [comment]
@manuelbuil Glad to assist. Yes it would be greatly appreciated if you'd like to update docs!

**Comment by manuelbuil** [comment]
@christarazi @jrajahalme could you have a look at the PR please? https://github.com/cilium/cilium/pull/13409. Thanks!
