### ISSUE TITLE
Add endpoint status after restoring endpoint

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1329]

**Comment by raybejjani** [comment]
Could you explain this more? Is restore here when the agent restarts and restores information from BPF or something else?
As for the status, I imagine this is setting the status immediately instead of waiting for the per-5-minute regeneration which probably then sets it anyway.

**Comment by raybejjani** [comment]
Oh, this is the log status thing. So this issue is just to add that as an event/state transition that we log.
