### ISSUE TITLE
enable hubble by default

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#13311]
i'd like to enable hubble local mode by default (i.e. `hubble.enabled=true`) in v1.9.

probably makes sense to wait for https://github.com/cilium/cilium/pull/13259 to land first.

**Comment by joestringer** [comment]
We should do a sanity check in minikube to assess resource usage, run with/without hubble enabled by default.

**Comment by gandro** [comment]
Assigning also @michi-covalent for the doc changes needed

**Comment by gandro** [comment]
> We should do a sanity check in minikube to assess resource usage, run with/without hubble enabled by default.

@Rolinh will take a shot at this.

**Comment by Rolinh** [comment]
> We should do a sanity check in minikube to assess resource usage, run with/without hubble enabled by default.

Here is what I've done:

- Create a 1 node cluster using kubernete's kind
- Install using `quick-install.yaml` + **pprof enabled**, once as is and once with `hubble.enabled=true`.
- Deploy Cilium's connectivity test
- Watch `curl -s http://localhost:6060/debug/pprof/heap?debug=1 | grep "# Sys = " | tr -dc '0-9' | numfmt --to=si` until the value stabilizes. With Hubble enabled, I made sure to wait until the ring buffer is full (this can be checked via `hubble status`). Hubble's ring buffer stores up to 4096 entries with the default settings.

The `Sys` value that is grepped for in pprof's heap output is from a [`runtime.MemStats`](https://golang.org/pkg/runtime/#MemStats) dump:
> Sys is the total bytes of memory obtained from the OS.

The results I obtained are the following:

| Hubble   | Sys  |
|-------------|-------|
| disabled | 81M |
| enabled |  82M |

**Comment by michi-covalent** [comment]
validated the updated doc. thanks @Rolinh 👍
