### ISSUE TITLE
BPF masquerade works only in veth mode

### ISSUE THREAD

**Issue by AirbornWdd** [cilium/cilium#13316]
When I enabled bpf-masquerade in ipvlan mode. I got the error message. Do you have some milestones to support bpf-masq in ipvlan mode? Thanks for any reply.

**Comment by brb** [comment]
It's been planned with a very low priority. However, the new datapath mode based on veth which performance is on par with ipvlan is coming this week (https://linuxplumbersconf.org/event/7/contributions/674/attachments/568/1002/plumbers_2020_cilium_load_balancer.pdf slide 79).

**Comment by AirbornWdd** [comment]
excellent !!
