### ISSUE TITLE
Add Cilium blurb to Mesos cni.md docs

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#1334]
Now that there is a getting started guide for Mesos + Cilium, we should update the Mesos upstream docs to point to Cilium as an option: https://github.com/apache/mesos/blob/master/docs/cni.md

**Comment by techcet** [comment]
Draft: https://github.com/techcet/mesos/blob/cilium-mesos/docs/cni.md#a-cilium-network

**Comment by tgraf** [comment]
@techcet Looks great.

**Comment by tgraf** [comment]
We might want to link to actual installation instructions for Mesos. This is currently hidden in the `Vagrantfile` and the `start_marathon.sh` in `examples/mesos`. We should add a chapter to the *Installation Guide* that is Mesos specific. Without knowing the exact instructions, we may actually be able to include a short version of the instructions directly into the Mesos docs.

**Comment by techcet** [comment]
Thanks for the feedback. I missed it before creating the PR and it got merged pretty quickly. It might take a bit longer to do your suggestion, so in the mean time, we're live on apache/mesos:
https://github.com/apache/mesos/commit/07c9c27aaf13d5eb0dfd195be7e3449de09003bd

First commit to external org!
