### ISSUE TITLE
Documentation: Provide a migration guide for replacing calico with cilium 

### ISSUE THREAD

**Issue by brandshaide** [cilium/cilium#13367]
## Proposal / RFE

Quite often in Slack we're facing questions about how to migrate from Calico --> Cilium. As our Docs are providing installation guides basically only for greenfield setups (apart from the CNI chaining instructions), this most likely isn't reflecting the reality with k8s Cluster running in staging and prod environments out there in the wild with other CNIs than Cilium. 

Proposal is to provide a step-by-step migration guide which is as smooth as possible. 
Referring to [this conversation](https://cilium.slack.com/archives/C2B917YHE/p1601532105054100?thread_ts=1601483098.050100&cid=C2B917YHE)

**Comment by aanm** [comment]
@muffin87 @brandshaide he just had this blogpost submitted https://cilium.io/blog/2020/10/06/skybet-cilium-migration

**Comment by joestringer** [comment]
I think that the referred blog post should provide the necessary context to resolve this question. If you try this out and find there are any other interesting discussion points or issues, then feel free to post your observations on this issue below, or file a new issue.

Closing.
