### ISSUE TITLE
Deleting no longer present service warning with limited value

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#13399]
The following warning:
```
level=warning msg="Deleting no longer present service" l3n4Addr="{IP:10.119.242.191 L4Addr:{Protocol:NONE Port:80} Scope:0}" serviceID=50 subsys=service
```

indicates that something unexpected happened. Is that the case? If it is expected and the service just disappeared then let's remove it quietly. If something unexpected is happening here then let's describe that.

**Comment by brb** [comment]
Which Cilium version? I've fixed at least one instance of it in the past - https://github.com/cilium/cilium/pull/11467.

**Comment by tgraf** [comment]
> Which Cilium version? I've fixed at least one instance of it in the past - #11467.

@brb The PR that failed was based on eb2714e1cab09860b833595907359e28d765c153 which did not include your fix. Feel free to close if already fixed.
