### ISSUE TITLE
localhost is filtered by default

### ISSUE THREAD

**Issue by tibers** [cilium/cilium#13393]
## Bug report

**General Information**

- Cilium version 1.8

**How to reproduce the issue**

We have an in-house written nodejs application which talks to the google cloudsql sidecar and itself over `localhost`. We're using cilium to whitelist egressing traffic and so we have a few `matchName`s. We did not think to whitelist `localhost` though and it was causing the application to have problems talking to the google cloudsql sidecar. Adding `localhost` as a `matchName` fixed the problem.

I would suggest that `localhost` should be implied. :)

**Comment by aditighag** [comment]
Are you able to share output of `cilium monitor` that indicates the policies that are dropping the traffic?

**Comment by aditighag** [comment]
Would you know why DNS requests would be generated for resolving `localhost`? These entries are typically specified in the `/etc/hosts` file on Linux or equivalent files on other platforms? cilium monitor output should help us understand/confirm which policy is exactly dropping the traffic.

**Comment by tibers** [comment]
It's very likely some sort of problem with the node app. However I am not a
developer.

**Comment by aanm** [comment]
@tibers can we close the issue since it's fixed?

**Comment by tibers** [comment]
Uh, sure. It's fixed for me by adding localhost to the whitelist. I don't
have a good way of duplicating it since the dev folks don't want to "undo
the fix".

**Comment by joestringer** [comment]
It sounds like you've been able to resolve this with a workaround. If anyone is able to provide more specific information like what was requested above (eg hubble/monitor output showing the drops) then please do post below and we can consider reopening an investigation.

In the mean time, closing since more information is needed.
