### ISSUE TITLE
bpf: Ability to perform source PAT

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1341]
- Must be able to generate host unique 5-tuples after a DNAT operation by performing source PAT
- Ideally, tuple allocation is split from packet mangling

0.12: Design

**Comment by joestringer** [comment]
Related: #7527 (in iptables mode)

**Comment by joestringer** [comment]
@borkmann I think this feature is now addressed as part of v1.7 kube-proxy free? Any aspect of source PAT that you think is still missing?

**Comment by brb** [comment]
> Any aspect of source PAT that you think is still missing?

The BPF MASQUERADE is missing in the veth mode.
