### ISSUE TITLE
Support External IPAM with CNI Integration (enable DC/OS)

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#1343]
Cilium supports CNI, which allows it to work with vanilla apache Mesos.   But to work with Mesosphere DC/OS requires supporting external IP Address Management (IPAM).  

From: https://dcos.io/docs/1.9/networking/virtual-networks/: 
"DC/OS Overlay does not require an external IP address management (IPAM) solution because IP allocation is handled via the Mesos Master replicated log. DC/OS Overlay does not support external IPAMs."

**Comment by tgraf** [comment]
DC/OS also uses a host scope allocator

From: https://dcos.io/docs/1.9/networking/virtual-networks/
> The limitation on the total number of containers on DC/OS Overlay is the same value as the number of IP addresses available on the overlay subnet. However, the limitation on the number of containers on an agent depends on the subnet (which will be a subset of the overlay subnet) allocated to the agent. For a given agent subnet, half the address space is allocated to the MesosContainerizer and the other half is allocated to the DockerContainerizer.

This means that changes should be limited to the CNI plugin itself.
