### ISSUE TITLE
Initial support for Openstack

### ISSUE THREAD

**Issue by oblazek** [cilium/cilium#13433]
## Proposal / RFE

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
I would like to discuss a design of how cilium integration of openstack could look like. I have been discussing this a few times on slack and I'm starting to work on this fulltime.
For the initial support I am thinking of keeping standard neutron core plugins and implementing a part where cilium is "only" registering each labeled instance as an endpoint. This means keeping e.g. calico plugin to handle IPAM and interface creation etc, but creating cilium endpoints and handling everything around policies using cilium. 

![arch1](https://user-images.githubusercontent.com/15906154/95299448-08b65280-087e-11eb-83ee-4e6eb77663c7.png)

There could be a new cilium plugin (e.g. cilium-openstack in the picture above) running on each compute node, together with cilium-agent. This plugin would similarly to what docker plugin does be consuming events when new instance, targeting that worker, gets created/updated/deleted. 
All necessary information can be read from rabbitmq which is a transport backend for oslo.messaging which is used in communication between openstack components. I would use one of the most used go libraries for this purpose which could be `github.com/streadway/amqp` which works pretty well. This plugin would be tapped to `notifications` queue of oslo.messaging because that's exactly what it's for: [The notification messages are meant to be used for integration with external services, including services that are not part of OpenStack.](https://docs.openstack.org/oslo.messaging/latest/user/FAQ.html#why-does-the-notification-publisher-create-queues-too-shouldn-t-the-subscriber-do-that)

![arch2](https://user-images.githubusercontent.com/15906154/95304190-88472000-0884-11eb-9655-3cee4779fb9b.png)

Each message would get unmarshaled from json into a struct, leaving out unnecessary data and that would build up an `EndpointChangeRequest`. 

This way we could use cilium's clustermesh across our own k8s and openstack clusters.

Any comments on the design or does that make sense? Thanks.

**Comment by gongysh2004** [comment]
it is a good idea to have openstack run with cilium. It seems you are suggesting neutron + calico + cilium for the whole solution, right? why not a pure neutron + cilium?

**Comment by oblazek** [comment]
That's possible of course, I am not suggesting that calico has to be used. It's just that we use it together with calico atm in our company. So I only meant that as one of the possibilities.

**Comment by joestringer** [comment]
I think the architecture in the diagrams makes sense, ideally the `cilium-openstack` component would act like the CRI in k8s world, potentially even receiving Openstack scheduling events and issuing CNI ADD/DELETE events to the `plugins/cilium-cni` plugin so that the common cilium-agent API interactions can reuse that code.

Regarding pairing Cilium with Calico, I think this option should work but longer-term you will reduce operational complexity by migrating to only using Cilium (fewer moving components).

**Comment by gongysh2004** [comment]
@oblazek are you talking about using cilium-agent to implement the security group or plugin the VM?
currently,  take the ovs, one of the neutron ml2 plugin mechanism driver, as an instance, the nova will plugin the tap device on the host end into the ovs bridge 'ovs-int' (to pair the tap device is the eth0 device inside the VM); the ovs-agent, running on the compute host, is responsible to set up the OpenFlow rules (set up VLAN, etc.)and security group rules(set up iptables rules, etc.) for the VM's tap device. 
so in your idea: what the nova-compute does? what the cilium-agent does? how to support L2 communication, multicast for VM?

thanks

**Comment by oblazek** [comment]
I totally agree with you guys, I am thinking there could be 2 modes how cilium-openstack plugin could work. The first one (which I am working on now) could be the simple one, which would work as a "bridge" between openstack and cilium. In this mode this plugin would just create/update/delete cilium endpoint with instance metadata labels and project name so that endpoint identity can be easily generated. The other mode which would come later on could possibly totally replace calico networking which is based on L3. In this mode the plugin would implement creation of the interface, IPAM and synchronization to cilium.
 
Supporting ovs/L2 would be quite difficult I think, not sure how to handle that. But any suggestion is welcome.
