### ISSUE TITLE
CI: "K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing" fails in cilium-master-K8s-all

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#13430]
https://jenkins.cilium.io/job/cilium-master-K8s-all/

All recent jobs are failing due to 
```
Kubernetes DNS did not become ready in time
```

**Comment by nebril** [comment]
the failure is caused by `dig` not returning correct ip:
```
;; reply from unexpected source: 192.168.36.12#53, expected 10.96.0.10#53
;; reply from unexpected source: 192.168.36.12#53, expected 10.96.0.10#53
;; reply from unexpected source: 192.168.36.12#53, expected 10.96.0.10#53
;; connection timed out; no servers could be reached
```

**Comment by nebril** [comment]
The failure seems to be caused by https://github.com/cilium/cilium/pull/13238 , this PR https://github.com/cilium/cilium/pull/13473/files which reverts #13238 passes k8s-all

**Comment by pchaigno** [comment]
@jrfastab Does #13500 address this issue as well?

**Comment by joestringer** [comment]
We believe this was already fixed by https://github.com/cilium/cilium/pull/13500 , if you see it again then reopen.

**Comment by jrajahalme** [comment]
Happened on https://github.com/cilium/cilium-cli/pull/485/checks?check_run_id=3323023154

**Comment by pchaigno** [comment]
@jrajahalme Did you mean another link? This is an old Jenkins flake and the link points to a recent CI 3.0 failure.
