### ISSUE TITLE
Handle case when IP of API server is not announced in node resource

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1347]
In some minikube environments, when the VM is configured with multiple network interface, the IP on which the API server is listening is not announced as either the InternalIP or ExternalIP in any of the Kubernetes node resources. If this is the case, Cilium is not aware of the IP and will not consider it local, it will thus not be reachable from any pods.

Possible Solution:
The "kubernetes" service is always configure. We can consider the IP always local.

**Comment by danwent** [comment]
this seems to be working with tag v0.11

**Comment by tgraf** [comment]
Verified, fixed in 0.11.
