### ISSUE TITLE
Reuse k8s resource cleanup code in updates test

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13474]
This code seems like it should use `CleanupCiliumComponents()` instead:

https://github.com/cilium/cilium/blob/13a1ebff5b417b9be41814678f51bf0be8acfea6/test/k8sT/Updates.go#L123-L132

**Comment by chowmean** [comment]
The resources deleted in CleanupCiliumComponent is not deleting the helpers (preflight)
```
resourcesToDelete = map[string]string{
			"configmap":          "cilium-config",
			"daemonset":          "cilium cilium-node-init",
			"deployment":         "cilium-operator",
			"clusterrolebinding": "cilium cilium-operator",
			"clusterrole":        "cilium cilium-operator",
			"serviceaccount":     "cilium cilium-operator",
		}
```
Everything else it is taken care of. 
@joestringer how should we proceed here?

**Comment by joestringer** [comment]
@chowmean For the preflight, that deployment should be unique for the updates.go test so I think it'd make sense for that code to remain inside `removeCilium()`. For the rest, I wonder if `removeCilium()` could call `CleanupCiliumComponents()` instead of individually deleting specific resources here.
