### ISSUE TITLE
Rework JSON output for "cilium bpf metrics list"

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#13492]
Current output for the command looks as follows:

```json
$ cilium bpf metrics list -o json       
{
  "reason:0 dir:1": [
    "count:3682036 bytes:344283040"
  ],
  "reason:0 dir:2": [
    "count:4900066 bytes:1675309710"
  ],
  "reason:139 dir:1": [
    "count:16 bytes:1668"
  ],
  "reason:166 dir:2": [
    "count:6 bytes:648"
  ],
  "reason:168 dir:2": [
    "count:1 bytes:236"
  ],
  "reason:3 dir:1": [
    "count:4110054 bytes:2194866462"
  ]
}
```

It is very difficult to process and extract meaningful data out of it. One has to parse the strings in addition to parsing the JSON. I can't imagine working with `-o jsonpath` on such output.

Instead, we could imagine something like the following:

```json
[
  {
    "reason": 0,
    "values": {
      "ingress": {
        "count": 3682036,
        "bytes": 344283040
      },
      "egress": {
        "count": 4900066,
        "bytes": 1675309710
      }
    }
  },
  {
    "reason": 139,
    "values": {
      "ingress": {
        "count": 16,
        "bytes": 1668
      }
    }
  }
]
```

(Maybe a `description` attribute for the text accompanying the reason id, if doable?)

Note that this is an API change, but after discussing it [on Slack](https://cilium.slack.com/archives/CDKG8NNHK/p1602239430041500) with André and Joe we agreed that this was one worth doing.

**Comment by youssefazrak** [comment]
@qmonnet I'm willing to give it a try.
Any pointers? Cheers.

**Comment by jibi** [comment]
Hi @youssefazrak :wave:
I am already done with the changes to rework the output, I just need to add some unit tests and fill a PR (hopefully by next week)

**Comment by youssefazrak** [comment]
Hi @jibi, cheers thanks for letting me know.
