### ISSUE TITLE
Helm: update expectAzureVnet flag to azure.expectVnet

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#13495]
## Bug report

**General Information**

Helm: update expectAzureVnet flag to azure.expectVnet to be more consistent with new values structure

**Comment by ti-mo** [comment]
Hi, I've proposed to removed this flag in https://github.com/cilium/cilium/pull/14105 as we've detected a fundamental issue with its behaviour. Don't worry about renaming it!
