### ISSUE TITLE
Add feature flag in sockops bpf code for when the socket object is available for use.

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/cilium#13490]
Now that we [differentiate services by protocol](https://github.com/cilium/cilium/pull/12628) we created a side effect that our sockops programs now only work for TCP. The reason for this is that [the bpf verifier](https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c) did not allow access to the socket object contained in the context objects (`bpf_sock_ops` and `sk_mg_md` respectively) of those programs until later versions (5.3 and 5.8 respectively). Adding a compile flag into the bpf code (ala [something like this](https://github.com/cilium/cilium/pull/12628#discussion_r498711407)) so that when the appropriate kernel version is running we can allow other protocols to work as well will mitigate this regression and future-proof it.

**Comment by jrfastab** [comment]
@nathanjsweet Just to be clear currently the kernel only supports TCP so there is no way to run sockmap policy programs on non-TCP packets. However, UDP support is on my list so at some point we should get it.
