### ISSUE TITLE
Helm: Document multiple TODO fields in values.yaml

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#13496]
## Bug report

**General Information**

Multiple fields in values.yaml are marked with TODO: Add documentation.

Update the values.yaml with commented documentation about what each of these does.

**Comment by pchaigno** [comment]
I think this can be easily addressed without much prior knowledge by checking the cilium-agent help (or grepping in the documentation) to get a quick idea of what [each flag marked with a TODO](https://github.com/cilium/cilium/blob/c69dfd106131f174ec315b8522b36405b67207f2/install/kubernetes/cilium/values.yaml#L398) does.

Taking `endpointHealthChecking` as an example:
Checking `cilium-configmap.yaml` we can see that it corresponds to flag `enable-endpoint-health-checking` in the cilium-agent. In the agent, that flag is documented as `Enable connectivity health checking between virtual endpoints`.

**Comment by ti-mo** [comment]
Looks like this has been addressed, closing.
