### ISSUE TITLE
api-limiter: TestAutoAdjust unit test fails consistently

### ISSUE THREAD

**Issue by twpayne** [cilium/cilium#13508]
Running `make unit-tests` in the standard Vagrant VM on my local machine consistently fails with the following test failing:

```
FAIL: api_limiter_test.go:96: ControllerSuite.TestAutoAdjust

api_limiter_test.go:128:
    // burst should not adjust this quickly
    c.Assert(a.limiter.Burst(), check.Equals, initialRateBurst)
... obtained int = 1
... expected int = 2
```

The failing test is at [this line](https://github.com/cilium/cilium/blob/master/pkg/rate/api_limiter_test.go#L128).

The test here looks potentially a little racy (there are a few `time.Sleep`s), and the code being tested looks to be both new and quite subtle.

@tgraf and @aanm it looks like you're currently working on this area of the codebase. Would you like me to investigate further? Do you need any further information?

**Comment by tgraf** [comment]
It's completely new code and it's relatively tough to test some of these reliably as it depends on the timing of rate-limiting auto adjustment. If you find a way to improve, go for it, otherwise, we can also remove the particular line in the test. As usual, it was very stable and solid on my dev machine with margins and behaves differently in the loaded CI.

**Comment by twpayne** [comment]
Ack, thank you. I'll investigate.

**Comment by aanm** [comment]
it seems that is still failing for the race detection mode:
```

----------------------------------------------------------------------
FAIL: api_limiter_test.go:724: ControllerSuite.TestStressRateLimiter

api_limiter_test.go:762:
    c.Assert(testutils.WaitUntil(func() bool {
        return atomic.LoadInt32(&completed) == 1000
    }, 5*time.Second), check.IsNil)
... value *errors.errorString = &errors.errorString{s:"timeout reached while waiting for condition"} ("timeout reached while waiting for condition")

OOPS: 26 passed, 1 FAILED
--- FAIL: Test (7.45s)
FAIL
coverage: 4.8% of statements in ./...
FAIL	github.com/cilium/cilium/pkg/rate	7.805s
FAIL
make: *** [Makefile:220: unit-tests] Error 1
travis_time:end:039574f2:start=1602773207836526053,finish=1602774571241876284,duration=1363405350231,event=script
[0K[31;1mThe command "./.travis/build.sh" exited with 2.[0m
```

Full logs: https://api.travis-ci.com/v3/job/400218104/log.txt

**Comment by twpayne** [comment]
This is a different test that's failing, but lets keep it in this issue.

**Comment by tklauser** [comment]
`TestStressRateLimiter` still seems to fail consistently (e.g. on latest `master`: https://travis-ci.com/github/cilium/cilium/jobs/506728789) when run with the race detector, potentially hiding other races in unit tests. I've sent  #16262 disabling said test when run under the race detector until we figured out what is causing the issue.
