### ISSUE TITLE
Enabling ip-masq-agent causes agent to crash

### ISSUE THREAD

**Issue by andrewrynhard** [cilium/cilium#13502]
## Bug report

```
level=fatal msg="Failed to create ip-masq-agent" error="Failed to add \"/etc/config\" dir to fsnotify watcher: no such file or directory" subsys=daemon
```

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.8.4 17d623853 2020-09-30T17:31:44-07:00 go version go1.14.9 linux/amd64
Daemon: 1.8.4 17d623853 2020-09-30T17:31:44-07:00 go version go1.14.9 linux/amd64
```
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Generate manifests with helm flags:
```
  --set global.masquerade=true \
  --set global.ipMasqAgent.enabled=true \
```
2. Apply the manifests

**Comment by brb** [comment]
You need to create a ConfigMap which then has to be mounted to cilium-agent pods. Please see: https://docs.cilium.io/en/v1.8/concepts/networking/masquerading/#ebpf-based.

**Comment by andrewrynhard** [comment]
@brb This feels like an issue with the helm chart. The docs say that if the config is empty, a set of default rules are used. My expectation was that the `ConfigMap` setup would be configured by the helm templates if `ip-masq-agent` is enabled. I could then optionally modify the `ConfigMap`. I could make a feature request for this if you think it sounds reasonable.

**Comment by aanm** [comment]
Re-opened the issue since @andrewrynhard won't be able to open it per GH behavior cc @brb users can't re-open issues closed by collaborators

**Comment by brb** [comment]
@andrewrynhard That would a safer option. Just one question - how would you make sure that that empty `ConfigMap` in the helm chat would not override a previously provisioned by a user `ConfigMap`?

**Comment by andrewrynhard** [comment]
> @andrewrynhard Yeah, that would be a safer option. Just one question - how would you make sure that that empty `ConfigMap` in the helm chat would not override a previously provisioned by a user `ConfigMap`?

I don't know 🙂. Will helm clobber something it doesn't manage?

**Comment by brb** [comment]
> Will helm clobber something it doesn't manage?

I'm not an expert here, but maybe @errordeveloper might know.

**Comment by aanm** [comment]
@andrewrynhard yes, if the configmap is installed by helm then it's assumed the user should not never modify the config map manually afterwards.

**Comment by andrewrynhard** [comment]
@aanm that makes sense. So will helm clobber an existing configmap?

**Comment by aanm** [comment]
@andrewrynhard if that configmap was installed by helm, I think so, yes.

**Comment by andrewrynhard** [comment]
I think the concern brought up by @brb is that if we get the configmap managed by helm, how would that effect current deployments of Cilium? If they had to bring their own configmap, will us having the configmap by default break them?

**Comment by brb** [comment]
My concern was what if we create the empty ConfigMap when `--set global.ipMasqAgent.enabled=true` is set and a user has previously installed the same ConfigMap with some values. Does helm prevent the latter from being overridden by the former?
