### ISSUE TITLE
Support multiple nativeRoutingCIDR

### ISSUE THREAD

**Issue by gpl** [cilium/cilium#13565]
## Proposal / RFE

We're looking for a way to disable masquerading for multiple, disjointed CIDRs. (i.e. 10.10.0.0/16,240.0.0.0/8,100.64.0.0/16)

**Is your feature request related to a problem?**
Not that I'm aware.

**Describe the solution you'd like**

We saw a mention of a `native-routing-cidrs` from a few months ago in this comment: https://github.com/cilium/cilium/pull/12230#discussion_r444780134

The ability to provide a comma separated list of CIDRs would be useful.

**Comment by brb** [comment]
@gpl This is exactly the use case for ip-masq-agent. Please see: https://docs.cilium.io/en/v1.8/concepts/networking/masquerading/#ebpf-based.
