### ISSUE TITLE
Consider refactoring agent (daemon) initialization code due to brittleness in dependency ordering

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#13573]
The daemon initialization code is quite brittle as there are many steps that depend on the ordering of other steps. This can be a nightmare to debug when making seemingly innocent changes. An example of this can be seen in https://github.com/cilium/cilium/pull/13418. 

Shorter term approach would be to separate out the daemon setup from the "init" setup. In other words, we would need to identity which steps are absolutely required for the agent to "pre-initialize", if you will, and then proceed with the rest of the dameon setup. (Idea by @brb)

One long term approach would be to [topologically sort](https://en.wikipedia.org/wiki/Topological_sorting) the dependencies in order to figure out the order in which they can be done. An advantage would be that developers would no longer need to intimately understand the inherent ordering of the dependencies when attempting to make a change. They can just "register" their step (along with its prerequisites), and the "scheduler" will figure out when to execute it. Another advantage of this is that we can identity "detached" steps (meaning they don't have dependencies; are standalone) and execute them in parallel, potentially speeding up the daemon initialization. This code can be made to panic (or fatal) if a developer introduces a cycle. This can greatly speed up debugging as well.

A final approach can likely include the combination of the above in some way.

**Comment by joamaki** [comment]
Superceded by #23425
