### ISSUE TITLE
Add Cert-Manager Documentation for Hubble Certificate management

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/cilium#13590]
When TLS is enabled for cilium's helm chart we should add documentation for how to deploy cilium with TLS enabled and using cert-manager to cycle the certificates.

**Comment by nathanjsweet** [comment]
This will involve setting up a mountpath in the deployment that is **not** prepopulated.

**Comment by gandro** [comment]
> This will involve setting up a mountpath in the deployment that is **not** prepopulated.

Not sure if it is helpul, but the existing `certgen` approach also works with optional secrets. See https://github.com/cilium/cilium/pull/13449/commits/711781d789548377ed8f7d424c13707d70e74aee

**Comment by nathanjsweet** [comment]
This issue is irrelevant now.
