### ISSUE TITLE
Dump CLI output as part of cleanup of each test

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1359]
When a test finishes, it would be helpful for us to dump the state of Cilium and its endpoints.
As part of each test cleanup, before endpoints are destroyed and cilium policies / objects are deleted, run the following and dump to a log file that is grouped with the logs from that test:

* `cilium endpoint list`
* `cilium endpoint get <ID>` where ID is the ID of each endpoint
* `cilium service list`
* `cilium service get <ID>` where ID is the ID of each service
* `cilium identity get <ID>` where ID is a security identity
* `cilium config` 
* `cilium bpf lb list`
* `cilium bpf ct list global`
* `cilium bpf tunnel list`
* `cilium bpf policy list <ID>` where ID is the ID of each endpoint
* `cilium policy get`

- [ ] Add for runtime-tests
- [ ] Add for K8s tests

**Comment by aalemayhu** [comment]
That should cover most of the output, would only add `cilium status`.

**Comment by ianvernon** [comment]
Self-assigning so we can help debug the CI failures that have been occurring as of late.
