### ISSUE TITLE
DSR Not working in AWS Native routing mode

### ISSUE THREAD

**Issue by Buffer0x7cd** [cilium/cilium#13600]
## Bug report
Hi Team, Currently I am trying to setup Cilium in EKS as a replacement for Kube-Proxy. After the initial setup, I was working on setting DSR in EKS, After the DSR setup I had noticed that the node port services are only working through local nodes (Local nodes are those nodes where the actual backend node is running) and any request to Intermediate Nodes (Nodes where the backend is not running locally and needs to use NAT) are getting timed out. I have spent a few days trying to debug this issue and had a discussion with @brb regarding this issue. The details of the discussion can be found in the following [thread](https://app.slack.com/client/T1MATJ4SZ/C1MATJ5U5/thread/C1MATJ5U5-1602593455.459400). As the thread is very long, I would add the key points below

- During the debugging we took packet capture on both the Intermediate node and Target/Local Node. While doing this we noticed that no relevant request is reaching the target node. 

- From the packet capture of the Intermediate node we can see the packet reaching to Intermediate node containing the DST address of the intermediate node and the packet leaving the intermediate node after DNAT, Containing the address of pod as a Destination

- In the VPC flow log of the Intermediate node's ENI, we can see the incoming traffic coming, but we can't see any packet going out after DNAT(Even though we can see this packet in packet capture of the intermediate node)

- The above event caused us to raise suspicion towards AWS VPC dropping packets which have the Ip options filed set.

- To test the above scenario, we launched two standalone nodes in two different subnets (This was done Because we wanted the packets to flow through the VPC router and not directly communicate, which is the case if two nodes are in the same Subnet)

- For the test purpose we generated a dummy packet with Scapy which looks like the below entry

`IP(dst="10.102.108.162", options=IPOption(b'\x00'))/UDP(dport=8000, sport=RandNum(1024,65535))/("OptionsEnabled")`

Here `10.102.107.164 ` is the client and `10.102.108.162` destination which is running Netcat UDP listener on port 8000. After taking the packet capture, We can see that the packet is able to reach the destination server, even in the presence of the Ip options field. This led us to suspect packets are not getting dropped due to the vpc system.

-->

**General Information**

- Cilium 1.8.4
- Kernel 5.3
- EKS 1.16

How to Reproduce 

1. Create an EKS cluster
2. Install cilium using the following helm command
```
 helm install cilium cilium/cilium --version 1.8.4 \                                                                                                                                                                    
  --namespace kube-system \
  --set global.eni=true \
  --set config.ipam=eni \
  --set global.masquerade=false \
  --set global.tunnel=disabled \
  --set global.nodeinit.enabled=true  --set global.kubeProxyReplacement=strict --set global.k8sServiceHost=xxxxxxxxxxxxx.yl4.ap-south-1.eks.amazonaws.com --set global.k8sServicePort=443 --set global.nodePort.mode=dsr
```

3. Launch service with Type NodePort and try to connect to that Nodeport from any Intermediate Node.

**Comment by brb** [comment]
@Buffer0x7cd Can you paste `sysctl net` output from both nodes?

**Comment by Buffer0x7cd** [comment]
Hi @brb. Please find
[local_node.txt](https://github.com/cilium/cilium/files/5407253/local_node.txt)
[intermediate_node.txt](https://github.com/cilium/cilium/files/5407255/intermediate_node.txt)

 the attached output of `sysctl net` from both sides.

**Comment by brb** [comment]
Discussed offline - the src/dst IP check was enabled which made the packets to be dropped.
