### ISSUE TITLE
CI: k8s upstream tests failing in session affinity test cases

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#13641]
Example failures:
https://jenkins.cilium.io/job/cilium-master-K8s-Upstream/485/execution/node/67/log/
https://jenkins.cilium.io/job/cilium-master-K8s-Upstream/484
https://jenkins.cilium.io/job/cilium-master-K8s-Upstream/483

https://github.com/cilium/cilium/pull/13480 was supposed to help here, but the test still failed: https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/2601/

**Comment by brb** [comment]
A few datapoints - it seems to be a new test. Also, it's worth checking whether the affinity was indeed enabled by #13480.
