### ISSUE TITLE
ARM regressions in v1.9.0-rc2

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13650]
Nick on Slack reports with v1.9.0-rc2:

* [x] `disable-envoy-version-check` is necessary for ARM platform, but it is no longer present in the Helm charts (I had mistakenly thought it is no longer necessary, we need to re-add it)
  * Cilium startup fails if this option is not specified, due to missing cilium-envoy binary
* [x] `cilium-map-migrate` in ARM image is built for the wrong architecture
  * `level=warning msg="/var/lib/cilium/bpf/init.sh: line 361: /usr/bin/cilium-map-migrate: cannot execute binary file: Exec format error" subsys=datapath-loader`
* [ ] `cilium-operator-dev` images for cloud-specific operators fail because dockerhub does not have `cilium-operator-dev-aws`, `cilium-operator-dev-azure`, etc. repositories.
  * https://github.com/cilium/cilium/blob/f909e32daadfc457aae1ec04ad35b8e37640d66e/install/kubernetes/cilium/templates/cilium-operator-deployment.yaml#L134-L140 
   * This one might not be a regression, but it clearly breaks if someone enables eni/azure integrations.

**Comment by mrostecki** [comment]
I will push a fix for the 2nd point (`cilium-map-migrate` not being cross-compiled) soon.

**Comment by joestringer** [comment]
Split out the final issue into https://github.com/cilium/cilium/issues/13829 since it doesn't look like an actual regression.
