### ISSUE TITLE
transparent encryption: interface detection

### ISSUE THREAD

**Issue by kkourt** [cilium/cilium#13662]
Using:
```
$ helm install cilium cilium/cilium --version 1.9.0-rc2 --namespace kube-system --set encryption.enabled=true --set encryption.nodeEncryption=false
```

fails due to cilium guessing the interface wrong:
```
...
level=info msg="  --encrypt-interface='eth0'" subsys=daemon
...
level=warning msg="Device \"eth0\" does not exist." subsys=datapath-loader
```

There was no `eth0` interface on the machine, and specifying the interface  `--set encryption.interface=ens4` seems to solve the issue.

The guide states the following:

> If direct routing is being used, an additional argument can be used to identify
> the network-facing interface. If no interface is specified, the default route
> link is chosen by inspecting the routing tables.

Which might be interpreted so that it means that the interface can only be set when using direct routing. 
An attempt to clarify this can be found in: https://github.com/cilium/cilium/pull/13660
Long term, we might want to improve the interface detection.

**Comment by pchaigno** [comment]
> There was no `eth0` interface on the machine, and specifying the interface `--set encryption.interface=ens4` seems to solve the issue.

That's very surprising to me; it would mean we have code somewhere that hardcodes `eth0`. The detection happens here: https://github.com/cilium/cilium/blob/6fbcdae324807c66ded389bf44b22cde48ad25ad/daemon/cmd/daemon_main.go#L1183

On what machine were you running those tests (some cloud or locally)? Did you check the routes and whether there were any reference to a `eth0` interface in there?

**Comment by kkourt** [comment]
This was on Google Cloud VMs.

```
$ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 42:01:0a:ac:0f:c8 brd ff:ff:ff:ff:ff:ff
```

**Comment by kkourt** [comment]
This looks like the culprint:
https://github.com/cilium/cilium/blob/2ad3fe93d4cf85664ecebb00646d1e1332d4baf3/install/kubernetes/cilium/values.yaml#L355

**Comment by pchaigno** [comment]
Sounds like this should be unspecified by default to ensure device detection kicks in. @kkourt Could you send a PR to that effect?
