### ISSUE TITLE
NOTRACK rules for node-local-dns

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#13686]
We need to manage the NOTRACK iptable rules nodelocalDSN handles when it's deployed in root ns, because with Cilium, nodelocalDNS will be deployed in pod ns and cannot program root ns iptables. Cilium-agent seems like a good actor for this.

**Comment by brb** [comment]
@Weil0ng For those who didn't attend the yesterday's sig-datapath, could you add the motivation for the NOTRACK rules in the issue description?

**Comment by Weil0ng** [comment]
So the context is for node-local-dns. One of the optimization it does is to install these NOTRACK rules in the root ns iptables to bypass kernel conntrack.

Our current way of supporting node-local-dns deploys it in its own pod namespace, which means it is no longer able to manage such iptables rules in the root ns, hence we need Cilium-agent to step in and manage these rules.

These rules will be hit when we are running in `endpoint` routing mode where the pkts will be handed to the stack after existing the pod namespace.

**Comment by Weil0ng** [comment]
The motivation for the NOTRACK rules in the first place can be found in the original [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0030-nodelocal-dns-cache.md#motivation), tldr: `Skipping iptables DNAT and connection tracking will help reduce conntrack races and avoid UDP DNS entries filling up conntrack table.`

**Comment by brb** [comment]
The conntrack race should have been fixed in 4.18 kernel by [this patch](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=ed07d9a021df6da53456663a76999189badc432a).

So, the only problem which we are trying to solve with NOTRACK is the conntrack table overflow. I wonder whether it's not enough to advise users to increase the table size if they are hitting the overflow issue?

**Comment by Weil0ng** [comment]
I think the argument is that we see customers with crazy amount of DNS qps request, keeping those connections in the kernel conntrack causes contention with other non-DNS traffic. Increasing the table size might mitigate the problem but is less effective than simply not tracking them (both with the conventional way of deploying nodelocaldns and with kube-proxy free Cilium, kernel conntrack does nothing for these connections essentially).
