### ISSUE TITLE
"Bad file descriptor" after cilium agent restart

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1372]
We have observed "Bad file descriptor" errors when updating the BPF policy map after the agent has been restarted and recovered state.

**Comment by borkmann** [comment]
Related issue is #1031 by the way. If I'm not missing anything, I recently had a discussion with @aanm on this, and the issue is that recovery cannot use old, inactive (map etc) fd numbers, and needs to reopen those.

**Comment by tgraf** [comment]
> Related issue is #1031 by the way.

It was obvserved with the fix from #1031 included.

**Comment by borkmann** [comment]
I don't think #1135 and #1031 were related to each other. Second part that #1031  talked about was fixed in #1206 though.
