### ISSUE TITLE
Hubble dashboard shows no data - metrics do not match

### ISSUE THREAD

**Issue by zhujik** [cilium/cilium#13722]
The hubble dashboard contained in this repository does not work for all hubble exported metrics, or it should describe how hubble metrics should be configured for all panels to work. The labels in the dashboad queries do not match the metrics provided by hubble.

![image](https://user-images.githubusercontent.com/31599908/97000802-91e4af00-1537-11eb-9eac-229be637c53e.png)

**Comment by aanm** [comment]
@zhujik can you give us more information such as how did you deploy Cilium and / or hubble? Also, can you update Cilium's sysdump?

**Comment by aanm** [comment]
Related with https://github.com/cilium/cilium/issues/13738

**Comment by zhujik** [comment]
@aanm Thank you for your reply. Cilium is installed like so:
```
helm install --name cilium \
      cilium/cilium \
      --version 1.8.4 \
      --namespace kube-system \
      --set global.eni=true \
      --set config.ipam=eni \
      --set global.cni.configMap=cilium-cni-configuration \
      --set global.egressMasqueradeInterfaces=eth0 \
      --set global.tunnel=disabled \
      --set global.nodeinit.enabled=true \
      --set global.prometheus.enabled=true \
      --set global.operatorPrometheus.enabled=true \
      --set global.hubble.enabled=true \
      --set global.hubble.metrics.enabled="{dns:query;ignoreAAAA;sourceContext=pod;destinationContext=pod,drop:sourceContext=pod;destinationContext=pod,tcp:sourceContext=pod;destinationContext=pod,flow:sourceContext=pod;destinationContext=pod,port-distribution,icmp,http:sourceContext=pod;destinationContext=pod}"   
```

The panels in the dashboard, for example for "Top 10 Source Pods with Denied Packets" is configured in the dashboard like so:
```
topk(10, sum(rate(hubble_drop_total{reason="Policy denied (L3)"}[5m])) by (pod, source))
```
However, the `hubble_drop_total` metric with the given configuration looks like so:
```hubble_drop_total{destination="xxxx", instance="192.168.109.39:9091", job="kubernetes-service-endpoints", k8s_app="hubble", kubernetes_name="hubble-metrics", kubernetes_namespace="kube-system", kubernetes_node="ip-xxxx.eu-central-1.compute.internal", protocol="Unknown flow", reason="Policy denied", source="xxxx"}
```
My confusion with this is the following:
* there is no pod label that is referenced in the panels query
* there is no "Policy denied (L3)" label, it is just "Policy denied" 

If i change the values to the following: 
```
topk(10, sum(rate(hubble_drop_total{reason=\"Policy denied\"}[5m])) by (source))
```
The panel shows something. I'm not 100 % sure if I configured all panels like the are intended to, so I opened this issue.

**Comment by nathanjsweet** [comment]
@zhujik This is the grafana and prometheus templates found in the examples folder? Could you point me to which on in particular? It wouldn't surprise me if these templates are out of sync.

**Comment by zhujik** [comment]
@nathanjsweet sure. Here it is: 
https://github.com/cilium/cilium/blob/311d1277f2ea7159c8bcb1319aaf981718c3d065/examples/kubernetes/addons/prometheus/files/grafana-dashboards/hubble-dashboard.json#L1856

**Comment by nathanjsweet** [comment]
@zhujik yep they all got updated in [this commit](https://github.com/cilium/cilium/commit/ffc077817df6982d43739ace577ef321ddd66030). I'll open a PR later to fix them all. Thanks for the feedback, and good catch!

**Comment by YvanNys** [comment]
Hubble L7 HTTP Metrics dashboard showing No data, I have the same problem

**Comment by patrykkrajnik7** [comment]
Same here. It seems like there is no metric called hubble_http_requests_total, I can't even find anything similar.

**Comment by pattkrajnik** [comment]
Same here. It seems like there is no metric called hubble_http_requests_total, I can't even find anything similar.

**Comment by joestringer** [comment]
Please file a new issue including the version details for where you experience this.
