### ISSUE TITLE
hubble http metrics not being served

### ISSUE THREAD

**Issue by zhujik** [cilium/cilium#13738]
## Bug report

hubble metric server does not provide http metrics, but the option is set. This happens on 3 different installations (= clusters) the same.

**General Information**

- Cilium version 1.8,4
- Orchestration system version in use k8s 1.18 (AWS EKS)

cilium pod log:
```
level=info msg="Starting Hubble Metrics server" address=":9091" metrics="[dns:query;ignoreAAAA;sourceContext=pod;destinationContext=pod drop:sourceContext=pod;destinationContext=pod tcp:sourceContext=pod;destinationContext=pod flow:sourceContext=pod;destinationContext=pod port-distribution icmp http:sourceContext=pod;destinationContext=pod]" subsys=hubble
level=info msg="Configured metrics plugin" name=icmp status= subsys=hubble
level=info msg="Configured metrics plugin" name=http status="destination=pod,source=pod" subsys=hubble
level=info msg="Configured metrics plugin" name=dns status="query,ignoreAAAA,destination=pod,source=pod" subsys=hubble
level=info msg="Configured metrics plugin" name=drop status="destination=pod,source=pod" subsys=hubble
level=info msg="Configured metrics plugin" name=tcp status="destination=pod,source=pod" subsys=hubble
level=info msg="Configured metrics plugin" name=flow status="destination=pod,source=pod" subsys=hubble
level=info msg="Configured metrics plugin" name=port-distribution status= subsys=hubble
level=info msg="Configuring Hubble server" eventQueueSize=2048 maxFlows=4095 subsys=hubble
level=info msg="Starting local Hubble server" address="unix:///var/run/cilium/hubble.sock" subsys=hubble
```

**How to reproduce the issue**

1. set hubble metrics 
```
      --set global.hubble.enabled=true \
      --set global.hubble.metrics.enabled="{dns:query;ignoreAAAA;sourceContext=pod;destinationContext=pod,drop:sourceContext=pod;destinationContext=pod,tcp:sourceContext=pod;destinationContext=pod,flow:sourceContext=pod;destinationContext=pod,port-distribution,icmp,http:sourceContext=pod;destinationContext=pod}"   
```
2. port-forward to cilium pod metrics endpoint:
```
kubectl --namespace kube-system port-forward cilium-xxxx 9091
```
3. open localhost:9091/metrics
-> http metrics missing

**Comment by sayboras** [comment]
I am not expert here, just want to share my experience. 

Basically, I had similar question before, and then I found out that http metrics only coming if one of below two points is satisfied:

- HTTP-aware L7 Policy enabled. Related [docs](https://docs.cilium.io/en/latest/gettingstarted/http/) 
- Annotations applied in pod. Related [docs](https://docs.cilium.io/en/latest/policy/visibility/#limitations)

```shell script
root@kind-control-plane:/home/cilium# curl -s localhost:9091/metrics | grep http
# HELP hubble_http_request_duration_seconds Quantiles of HTTP request duration in seconds
# TYPE hubble_http_request_duration_seconds histogram
hubble_http_request_duration_seconds_bucket{method="POST",le="0.005"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="0.01"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="0.025"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="0.05"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="0.1"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="0.25"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="0.5"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="1"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="2.5"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="5"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="10"} 64
hubble_http_request_duration_seconds_bucket{method="POST",le="+Inf"} 64
hubble_http_request_duration_seconds_sum{method="POST"} 0.033516459
hubble_http_request_duration_seconds_count{method="POST"} 64
# HELP hubble_http_requests_total Count of HTTP requests
# TYPE hubble_http_requests_total counter
hubble_http_requests_total{method="POST",protocol="HTTP/1.1"} 64
hubble_http_requests_total{method="PUT",protocol="HTTP/1.1"} 39
# HELP hubble_http_responses_total Count of HTTP responses
# TYPE hubble_http_responses_total counter
hubble_http_responses_total{method="POST",status="200"} 64
```

**Comment by gandro** [comment]
@zhujik Can you confirm that you do have either L7 policies or L7 visibility annotations present? I assume that other metrics (e.g. `port-distribution`) are working as expected?

**Comment by zhujik** [comment]
@sayboras I tried it and now I'm seeing *something*. However, I have a hard time to grasp the concept of those proxy-visibility annotations. I tried reading the doc and googling a bit, however, I'm not sure about the impact of that change on our application.
So just for the sake of understanding: if set this annotation, what does it actually mean? 
For example, I have a apache tomcat pod that is serving on containerport 8080 tcp, which is behind a kubernetes service routing this on port 80. This apache pod connects to a oracle database pod which has a tcp port on 1521 for jdbc connections. So I used the following annotation for that apache pod: <Ingress/8080/TCP/HTTP>,<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>
After that, I was able to see http requests on responses on that apache pod. However, I don't really understand that egress part. 53/UDP/DNS is the egress for CoreDNS, as fas as I can see. However what does egress 80 tcp http do? And strangely, it seems that those annotation define policy rules as well, first I had Ingress on Port 80 and our load balancer couldn't reach the pod anymore. 
Furthermore, I don't understand how that annotation controls what I'm seeing. I seem to see all http traffic to that pod, also traffic going to database:1521, even when removing the egress setting. When setting <Ingress/1521/TCP/HTTP> on the database pod, my apache pod loses connection with the database. How does that happen?

**Comment by zhujik** [comment]
@gandro I'm really in need for more documentation here, since it was really intransparent how the setup should look like and what it means.

**Comment by zhujik** [comment]
@gandro thank you, that is very helpful. For that port 80 matter: I couldn't reproduce it yet, so I guess I had a configuration error on my side. 
Regarding the documentation: What you have written here is actually something that you could place into the documentation, if you ask me.
