### ISSUE TITLE
Documentation: cluster mesh guide for inter-regional deployments missing key details

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/cilium#13740]
The [cluster mesh guide](https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/clustermesh/) does not specifically prohibit inter-regional deployments from the guide, but an inter-regional deployment will not work if the guide is followed to the letter. If the clusters are in the same region the guide will work, but if they are not then something called "global access" for the internal loadbalancers need to be turned on ala [this guide](https://cloud.google.com/load-balancing/docs/internal/setting-up-internal#ilb-global-access).

We should fix the guide with at least a note, but there may be annotation that we can add to the `service.yaml` file for GCP/GKE that would automatically turn this on.

**Comment by michi-covalent** [comment]
@nathanjsweet good catch 👍 i guess this is this is the annotation? 

https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#global_access
