### ISSUE TITLE
Network policies (loopback, egress) that might need looking at

### ISSUE THREAD

**Issue by jayunit100** [cilium/cilium#13767]
## Bug report

In cilium PR https://github.com/cilium/cilium/pull/13758   @aanm is testing https://github.com/cilium/cilium/pull/13758 out our new network policy validation stuff and finding some discrepancies. 

-  Does  cilliums service proxy “short circuit” the cillium networkpolicy stack for self connections? 
- For now I think its best that we "look the other way" because these haven't been issues in the past, but they might be demonstrating a hole in the definition of the Upstream K8s Network Policy API semantics around loopback connectivity after policies are applied.   (Secondarily a couple of bugs around egress but that might be open for debate)

I've filed another issue in upstream k8s to define this https://github.com/kubernetes/kubernetes/issues/95879 .

But in any case, both antrea and calico in general seem to , by default , block "self" connections through a service endpoint  , whereas cillim does not.

1) Loopback networkpolicy's seem to apply differently on cillim then other providers.  For example, calico and antrea.  Its worth comparing how loopbacks work with and without service endpoints, to see if theres an unwritten standard of expectations that needs to be resolved.

As an example, it seems in general that the following connectivity matrix is different down the diagonal, which indicates that cillim deviates from what is expected for loopback connections in other CNIs, over a service endpoint: 

Note: Probing in these tests is done via:

```
'/usr/bin/kubectl --server=https://192.168.36.11:6443 --kubeconfig=/home/vagrant/.kube/config --namespace=services-2560 exec execpod-affinitymrzpm -- /bin/sh -x -c nc -zv -t -w 2 affinity-nodeport-timeout 80
```

The results are like so, for the failing tests where loopback discrepencies were seen
```
12:43:43  -		netpol-2127-x/a	netpol-2127-x/b	netpol-2127-x/c	netpol-2127-y/a	netpol-2127-y/b	netpol-2127-y/c	netpol-2127-z/a	netpol-2127-z/b	netpol-2127-z/c
12:43:43  netpol-2127-x/a	X		X		X		X		X		X		X		X		X	
12:43:43  netpol-2127-x/b	X		X		X		X		X		X		X		X		X	
12:43:43  netpol-2127-x/c	X		X		X		X		X		X		X		X		X	
12:43:43  netpol-2127-y/a	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-y/b	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-y/c	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-z/a	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-z/b	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-z/c	.		.		.		.		.		.		.		.		.	
12:43:43  
12:43:43  
12:43:43  
12:43:43  Oct 26 16:43:42.889: INFO: observed:
12:43:43  
12:43:43  -		netpol-2127-x/a	netpol-2127-x/b	netpol-2127-x/c	netpol-2127-y/a	netpol-2127-y/b	netpol-2127-y/c	netpol-2127-z/a	netpol-2127-z/b	netpol-2127-z/c
12:43:43  netpol-2127-x/a	.		X		X		X		X		X		X		X		X	
12:43:43  netpol-2127-x/b	X		.		X		X		X		X		X		X		X	
12:43:43  netpol-2127-x/c	X		X		.		X		X		X		X		X		X	
12:43:43  netpol-2127-y/a	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-y/b	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-y/c	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-z/a	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-z/b	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-z/c	.		.		.		.		.		.		.		.		.	
12:43:43  
12:43:43  
12:43:43  
12:43:43  Oct 26 16:43:42.889: INFO: comparison:
12:43:43  
12:43:43  -		netpol-2127-x/a	netpol-2127-x/b	netpol-2127-x/c	netpol-2127-y/a	netpol-2127-y/b	netpol-2127-y/c	netpol-2127-z/a	netpol-2127-z/b	netpol-2127-z/c
12:43:43  netpol-2127-x/a	X		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-x/b	.		X		.		.		.		.		.		.		.	
12:43:43  netpol-2127-x/c	.		.		X		.		.		.		.		.		.	
12:43:43  netpol-2127-y/a	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-y/b	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-y/c	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-z/a	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-z/b	.		.		.		.		.		.		.		.		.	
12:43:43  netpol-2127-z/c	.		.		.		.		.		.		.		.		.	
```

2) From the recent tests https://jenkins.cilium.io/job/Cilium-PR-Kubernetes-Upstream/2621/consoleFull which do comprehensive NetworkPolicy validation , the two following policies seem to have different connectivity matrices then other CNIs... 

```
13:25:41  spec:
13:25:41    egress:
13:25:41    - ports:
13:25:41      - port: 53
13:25:41        protocol: UDP
13:25:41    podSelector: {}
13:25:41    policyTypes:
13:25:41    - Egress
13:25:41    - Ingress
```

And

```
13:34:02  spec:
13:34:02    egress:
13:34:02    - to:
13:34:02      - ipBlock:
13:34:02          cidr: 10.0.1.120/4
13:34:02          except:
13:34:02          - 10.0.0.30/32
13:34:02    - ports:
13:34:02      - port: 53
13:34:02        protocol: UDP
13:34:02    podSelector:
13:34:02      matchLabels:
13:34:02        pod: a
13:34:02    policyTypes:
13:34:02    - Egress
```

**General Information**

- Cilium version (run `cilium version`) (master build)

**Comment by cmluciano** [comment]
I have not dug too deep into the logs linked from here, but on the surface I would not expect equivalency from the two policies listed above. In the 2nd example we are specifically using the Egress policy type and in the first we list Ingress and Egress or else we just accepted the defaulting for policyType.

**Comment by tgraf** [comment]
I think the behavior will be different depending on whether host services / socket-level load-balancing is enabled. If enabled, the service IP to pod IP translation happens inside the pod and the connection will use the loopback, e.g. it never leaves the pod and is identical as if the pod would connect to `::1` or `127.0.0.1`. When host services is not enabled, the packets will leave the pod and will be subject to network policies.

**Comment by jayunit100** [comment]
@cmluciano good catch on that first json snippet, I was pasting the wrong one :) . 
in any case we now have adopted the tests to report differences in loopback without reporting them as failures.

I think we can close this now, will let @aanm  make the call ?

**Comment by aanm** [comment]
> @cmluciano good catch on that first json snippet, I was pasting the wrong one :) .
> in any case we now have adopted the tests to report differences in loopback without reporting them as failures.
> 
> I think we can close this now, will let @aanm or @tgraf make the call ? once we get these in ci we'll be able to iterate and so on in case any other discrepencies pop up

@jayunit100 thanks for the update. Let's close it for now.
