### ISSUE TITLE
Feature Req: Detect and log IPAM-allocated pod CIDRs overlap with Cluster/Service IP's for Pods/Services

### ISSUE THREAD

**Issue by DaveWK** [cilium/cilium#13766]
### Setup

When in Cluster Scope (the default IPAM from quickstart) Cilium makes by default a potentially conflicting IP range for pods vs Service IP's (CLUSTER-IP)

In example, for my single-node setup,

my kubelet has:
`--service-cluster-ip-range=10.96.0.0/16`

Cilium made for me an IPv4 CIDR of:
`10.0.0.0/8`

and my kubelet-api is at: `10.96.0.1`

I have removed the taint to allow pods to start on master.

I was previously running flannel, which I removed.

### Problem

It assigns CoreDNS pods to the `10.0.0.0/8` cidr and I get errors about `dial tcp 10.96.0.1:443: i/o timeout` in the logs for CoreDNS, and generally this causes many other things to break that need CoreDNS.

Some of other pods that I launch can connect to kube API via `10.96.0.1`, and I can from the host.

My assumption is that this is a routing issue and the kube-api may be using a different gateway than the pod, something is broken in iptables config, or a similar issue. This is possibly also due to things that have been previously been allocated in the deleted flannel setup.

### Documentation issue

The documentation around Cluster Scope is very confusing and brief.
https://docs.cilium.io/en/stable/concepts/networking/ipam/cluster-pool/#cluster-scope-default

Do I set `Spec.IPAM.PodCIDRs` or `v2.CiliumNode`? Where and how do I do that?

If it has previously started without this value will it re-assign any pods to the new CIDR or do I need to clean out old pods? (From my current experience, it seems I cannot somehow make Cillium perform an update to re-allocate pods to the new range without doing a delete)

It really needs to explain things like how does one set `v2.CiliumNode` or  `Spec.IPAM.PodCIDRs` before starting, or how does one update `v2.CiliumNode` on a cluster that has previously been started without this param defined. 

### Workaround

Without a clear way to make sure that it re-assigned anything to the new space automatically or report any conflicts, I gave up and used `ipam: kubernetes` -- which as a side note, the Cillium doc does not a do a good job explaining __where__ to define this param or how.

### Proposal

Fix the docs and default startup to be more careful about the inital IP range. I would imagine a /16 is probably a more appropriate default for most use cases to avoid conflicts with anything else that might need a private IP.

Cillium should detect and log when the PodCIDRs conflicts with any kubernetes/kubelet values such as:
`--service-cluster-ip-range=10.96.0.0/16`
`--cluster-cidr=10.244.0.0/16`

Cillium should also log (or attempt to fix) any allocated pods that have IP ranges that do not comply with the defined `PodCIDRs`

**Comment by aanm** [comment]
Thanks for opening the issue. Unfortunately, it's not possible to know the `service-cidr` since Kubernetes does not expose these values as part of its API so Cilium can't properly detect service CIDR collisions. 

More information about the cluster scope can be found here https://docs.cilium.io/en/stable/gettingstarted/ipam-cluster-pool/#gsg-ipam-crd-cluster-pool

**Comment by DaveWK** [comment]
Thanks! 
I am surprised about kube-api -- for anyone else's ref: 
https://github.com/kubernetes/kubernetes/issues/46508

is tracking a whole IPAM API feature which should allow this to be exposed (..but was opened in 2017 so who knows when this will be actually completed). A possible workaround is checking the containers->command params in the `kube-controller-manager` pod, but it is kind of a string parsing hack rather than a source-of-truth.

It would be nice if there was some info or a ref on the other page:
https://docs.cilium.io/en/stable/concepts/networking/ipam/cluster-pool/#cluster-scope-default 

about that, and possibly how to change/set it without helm? I didn't use helm and just followed the guide here: https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/ 

I tried editing `CiliumNode` manually and changing the `podCIDRs` under `ipam` and deleting/restarting the cilium pod (which didn't work, and now know to use the ConfigMap rather than directly editing CiliumNode)

One thing I am noticing is that in my template it is telling me is when I run:

```
 kubectl get cn -o yaml
```
I see:
```
    ipam:
      operator-status:
        error: node has CIDRs allocated ([xxx]) that conflict with requested
          CIDRs [xxx]
```
is there a way to somehow allow it to just fix this automatically by deleting/updating/remaking the pods? It keeps using the bad IP on restarts, even when it's stuck in a Error or CrashLoop state. I ended up manually deleting them which seemed to solve the issue.

**Comment by aanm** [comment]
@DaveWK you can change the podCIDR, defined in Cilium config map, followed by deleting the Cilium Nodes (`kubectl delete cn --all`), a restart of Cilium Operator (`kubectl delete pod -n kube-system --label io.cilium/app=operator`), a restart of Cilium agents (`kubectl delete pod -n kube-system --label k8s-app=cilium` in the cluster, and a deletion of all pods so they are have the new CIDR (`kubectl delete pod -A --all`).

**Comment by osaffer** [comment]
Hi

helm install cilium cilium/cilium -n kube-system --set securityContext.privileged=true --set ipam.mode=cluster-pool --set ipam.operator.clusterPoolIPv4PodCIDRList=172.20.0.0/12 --set ipam.operator.clusterPoolIPv4MaskSize=12
NAME: cilium
LAST DEPLOYED: Wed Aug 31 09:06:44 2022
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.12.0.

For any further help, visit https://docs.cilium.io/en/v1.12/gettinghelp

But  : the pods are still receiving addresses in 10.0.0.0
coredns-5fcdd8f5c8-5878w                     1/1     Running   0               12m   10.0.4.66

inside the configmap:

cluster-pool-ipv4-cidr:
----
172.20.0.0/12
cluster-pool-ipv4-mask-size:
----
12


Of course all pods have been restarted.

Any adivces ?

Thank you

**Comment by Tiny-Wei** [comment]
> Hi
> 
> helm install cilium cilium/cilium -n kube-system --set securityContext.privileged=true --set ipam.mode=cluster-pool --set ipam.operator.clusterPoolIPv4PodCIDRList=172.20.0.0/12 --set ipam.operator.clusterPoolIPv4MaskSize=12 NAME: cilium LAST DEPLOYED: Wed Aug 31 09:06:44 2022 NAMESPACE: kube-system STATUS: deployed REVISION: 1 TEST SUITE: None NOTES: You have successfully installed Cilium with Hubble.
> 
> Your release version is 1.12.0.
> 
> For any further help, visit https://docs.cilium.io/en/v1.12/gettinghelp
> 
> But : the pods are still receiving addresses in 10.0.0.0 coredns-5fcdd8f5c8-5878w 1/1 Running 0 12m 10.0.4.66
> 
> inside the configmap:
> 
> ## cluster-pool-ipv4-cidr:
> ## 172.20.0.0/12
> cluster-pool-ipv4-mask-size:
> 12
> 
> Of course all pods have been restarted.
> 
> Any adivces ?
> 
> Thank you

After executing the above command, I run `ip link delete cilium_host` in each node. It's working.
