### ISSUE TITLE
Double-check mountPropagation settings

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13787]
Commit 5b85120e95fd42e31bb8d7e2a118dcb729fc71d7 added the `mountPropagation: HostToContainer` setting to the init container, but not to the main container. Should we also apply this setting to the main Cilium container?

The original change was motivated to fix the init container waiting on BPFFS mount (/cc @jraby), but I'm not sure if we ever evaluated whether it should be applied to the main container as well.

**Comment by jraby** [comment]
I'm not sure how cilium reacts if the contents of `/sys/fs/bpf` changes/is replaced while it is running.
For example, if `CILIUM_WAIT_BPF_MOUNT`  isn't set, the main container could start and bpffs could appear later. Would that ok?

If it is, then adding the mount propagation should be safe.
(I hadn't considered this use case at all when adding it)

**Comment by joestringer** [comment]
> For example, if `CILIUM_WAIT_BPF_MOUNT` isn't set, the main container could start and bpffs could appear later. Would that ok?

I guess from that perspective, if you want to ensure that the BPF filesystem is available before Cilium runs, you would just configure CILIUM_WAIT_BPF_MOUNT. I don't necessarily see a specific use case for trying to support mounting the BPFFS later on.

So maybe there's no real motivation to configure mountPropagation for the main container.

**Comment by jraby** [comment]
That was my conclusion.
