### ISSUE TITLE
CI: Add automated check for copyright headers

### ISSUE THREAD

**Issue by twpayne** [cilium/cilium#13819]
## Proposal 

I occasionally forget to add copyright headers to new files in PRs, and reviewers have had to manually comment on this. Such a check can be automated, saving reviewer time.

[golangci-lint](https://golangci-lint.run) includes support for the [go-header](https://github.com/denis-tingajkin/go-header) linter which can probably leveraged to implement this, at least for Go source files.

Comments? Happy to implement this if folk think it would be useful.

**Comment by aditighag** [comment]
I've added a copyright profile in Goland that automatically adds the header in new files, but this is useful in general. 

<img width="1536" alt="Screen Shot 2020-10-30 at 11 45 30 AM" src="https://user-images.githubusercontent.com/20311845/97745069-8815fb00-1aa5-11eb-889c-47c2758492a5.png">

**Comment by sayboras** [comment]
Voted for golangci-lint with go-header, one good thing is that we don't need to introduce more tools required as part of development. 

PS: I might be biased here.

**Comment by twpayne** [comment]
Quick update on this: adding the check is fairly straightforward, but it turns out that there are a lot of files that either don't have a copyright header, or have a slightly weird one. I have a WIP PR but there are still a lot of files to update. As there are other higher-priority tasks this is only getting idle cycles from me.
