### ISSUE TITLE
Jenkins: parallelize K8s 1.6 and 1.7 tests 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1382]
Run the K8s 1.6 and K8s 1.7 tests in parallel as part of the Jenkins jobs to reduce the turnaround time for builds.

**Comment by ianvernon** [comment]
Useful link: https://www.cloudbees.com/blog/parallelism-and-distributed-builds-jenkins

**Comment by eloycoto** [comment]
@tgraf @ianvernon  this issue can be closed. Already in place with the ginkgo testing
