### ISSUE TITLE
Development images missing for cloud-specific operator images

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13829]
`cilium-operator-dev` images for cloud-specific operators cannot be used because dockerhub does not have `cilium-operator-dev-aws`, `cilium-operator-dev-azure`, etc. repositories. In particular when running on arm64 if you use `operator-dev` as the operator image, the following helm bits will generate an image name that doesn't exist:

https://github.com/cilium/cilium/blob/f909e32daadfc457aae1ec04ad35b8e37640d66e/install/kubernetes/cilium/templates/cilium-operator-deployment.yaml#L134-L140

**Comment by Diaoul** [comment]
I'm facing the same issue. Is there any workaround?

**Comment by joestringer** [comment]
@Diaoul Other than manually updating the deployment to point to a valid repo, there is no workaround today. If you're interested in making changes to the helm charts to address the issue, we can help to walk you through that process. Feel free to reach out on Slack #development channel.

**Comment by aanm** [comment]
No longer valid
