### ISSUE TITLE
Make CLI more graceful on handling environments with IPv6 disabled

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13834]
Currently, for many of the CLI commands, if you run them in an environment where IPv6 is disabled, they will complain to stderr:

```
# cilium bpf nat list 1>/dev/null
Unable to open /sys/fs/bpf/tc/globals/cilium_snat_v6_external: Unable to get object /sys/fs/bpf/tc/globals/cilium_snat_v6_external: no such file or directory. Skipping.
```

This happens even if IPv6 is administratively disabled.

Ideally the commandline implementations like `cilium bpf nat ...` would detect this and silently ignore the missing IPv6 map.

Note that `cilium bpf ...` CLI tools in particular should be able to succeed if cilium-agent is unavailable. Regardless of the method for detecting that IPv6 is disabled, it should either be done reliably from state on the filesystem, or *optionally* by consulting the daemon (but if the daemon is unavailable, continue executing the command anyway).

**Comment by gaurang2001** [comment]
@pchaigno I would like to take this up

**Comment by CBVenkataReddy** [comment]
All configuration parameters are defined in the Config.Map and map file is store at the location "tmp/cilium/config-map".
and the state of all the parameters can fetched from that directory files.
The state of IPv6 can be read from filesystem at "tmp/cilium/config-map/enable-ipv6",
Now we can check IPV6 status and NAT map, if IPv6 is disabled then we ignore the error msg from NAT map also.
If IPv6 enabled and NAT map not found then we should display the error msg.
Pls correct us if we are missing anything.

**Comment by pchaigno** [comment]
> All configuration parameters are defined in the Config.Map and map file is store at the location "tmp/cilium/config-map".
and the state of all the parameters can fetched from that directory files.

I don't think we can assume the file will always be there. You can check the code of other `cilium` subcommands to see how to get that information from the cilium-agent daemon.

**Comment by CBVenkataReddy** [comment]
As per the issue description we want to do even if cilium-agent not running it should done reliably from the filesystem state,
Can you pls suggest any specific Cilium command to browse?

**Comment by pchaigno** [comment]
> As per the issue description we want to do even if cilium-agent not running it should done reliably from the filesystem state,

Yes, it should try to reach the daemon and fallback to the filesystem otherwise.

>  Can you pls suggest any specific Cilium command to browse?

`cilium status` reaches the daemon for example.

**Comment by Maddy007-maha** [comment]
Hi @pchaigno,

Can you assign this issue to me?
I want to work on this.

-Thanks

**Comment by Maddy007-maha** [comment]
@pchaigno 

As am looking into this issue for some time.
Can you assign this to me?

-Thanks
