### ISSUE TITLE
make sure tests do not directly use `kubectl create` or `kubectl delete`

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1383]
add a test that checks to make sure that no calls to kubectl create or kubectl delete are made outside of tests/helpers.bash - this will ensure that people use our helper functions that wait for desired state. Something like this is done to ensure that tests do use `sleep` in `tests/00-no-sleep.sh`.

**Comment by tgraf** [comment]
Switch to ginkgo fixes this
