### ISSUE TITLE
Remove / clean up snat maps if snat is disabled in the agent

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13835]
When toggling from using BPF-based NAT to using kube-proxy, Cilium does not clean up the existing snat maps. Cilium should remove such maps when the feature is disabled.

**Comment by mazzy89** [comment]
Hey guys. I can take a look at this.

**Comment by brb** [comment]
@mazzy89 Thanks! I've assigned you.

**Comment by mazzy89** [comment]
Hey @brb. I gave a look at this. I had to familiarize myself with the specific code path. My idea here to run [`flush`](https://github.com/cilium/cilium/blob/ec4167714163a1bb5a30656722673fb007d25764/pkg/maps/nat/nat.go#L203)  for all the `maps/nat` `GlobalMaps` when the `KubeProxyReplacement` Mode is set to `KubeProxyReplacementDisabled`. Ideally, the best IMO would be to run it during the daemon bootstrap. what do you think?

**Comment by brb** [comment]
@mazzy89 You don't need to `flush` the maps. It's enough to conditionally add the map name to https://github.com/cilium/cilium/blob/master/pkg/datapath/maps/map.go#L134.
