### ISSUE TITLE
Cannot configure Cilium log-opts

### ISSUE THREAD

**Issue by kovalyukm** [cilium/cilium#13831]
## Bug report
Hello,

Please fix issue with helm chart value `logOptions`.
Cannot set Cilium agent log format to json.

**General Information**

- Cilium/chart version (run `cilium version`)
1.8.4, 1.8.5

**How to reproduce the issue**

1. Set/add options https://github.com/cilium/cilium/blob/v1.8.5/install/kubernetes/cilium/values.yaml#L417-L418
```yaml
  logOptions:
    format: json
```
2. Get error from `helm upgrade`
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ConfigMap.data.log-opt): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"

Thanks!

**Comment by sayboras** [comment]
this issue happens for master and v1.9 branches as well.
