### ISSUE TITLE
insufficient quota to match these scopes

### ISSUE THREAD

**Issue by tibers** [cilium/cilium#13852]
## Bug report

We're getting `Error creating: insufficient quota to match these scopes: [{PriorityClass In [system-node-critical system-cluster-critical]}]` once we have upgraded to 1.8.5

**General Information**

- cilium versions 1.8.5
- K8s version 1.17.12-gke.1504

We were using 1.8.3 on a 1.17 cluster and we made a fresh cluster and bumped the version to 1.8.5 on the install.

**EDIT:** Just tried it with cilium 1.8.3 and got the same error, I now suspect it's GKE?
**EDIT EDIT:** it looks like the `priorityClass`es are getting created:
```
joshua_knarr@cloudshell:~ (ips-non-prod-mydf)$ kubectl get priorityclass
NAME                      VALUE        GLOBAL-DEFAULT   AGE
system-cluster-critical   2000000000   false            4h1m
system-node-critical      2000001000   false            4h1m
```
**EDIT EDIT EDIT**: Turning it to false in the helm chart (whatever the option name is) doesn't disable the behavior.

**How to reproduce the issue**

1. provision a 1.17.12-gke.1504 GKE cluster 
1. Remember to set your `NATIVE_CIDR` and install cilium with:
```
helm install cilium https://github.com/cilium/charts/raw/master/cilium-1.8.5.tgz --namespace cilium --create-namespace --set global.nodeinit.enabled=true --set nodeinit.reconfigureKubelet=true --set nodeinit.removeCbrBridge=true --set global.cni.binPath=/home/kubernetes/bin --set global.gke.enabled=true --set config.ipam=kubernetes --set global.nativeRoutingCIDR=$NATIVE_CIDR --set nodeinit.restartPods=true --set global.hubble.enabled=true --set global.hubble.metrics.enabled='{dns,drop,tcp,flow,port-distribution,icmp,http}'
```

**Comment by tibers** [comment]
Still trying to nail down the behavior - the org I'm working in has a seriously locked down cluster for compliance reasons, this *does not* happen on generic GKE clusters. I believe it's an org policy issue. My humble suggestion is to just allow us to turn off the feature if we're not allowed to use it with the caveat that this will allow pod pre-emption.

**Comment by aanm** [comment]
`helm install cilium https://github.com/cilium/charts/raw/master/cilium-1.8.5.tgz --namespace kube-system --create-namespace --set global.nodeinit.enabled=true --set nodeinit.reconfigureKubelet=true --set nodeinit.removeCbrBridge=true --set global.cni.binPath=/home/kubernetes/bin --set global.gke.enabled=true --set config.ipam=kubernetes --set global.nativeRoutingCIDR=$NATIVE_CIDR --set nodeinit.restartPods=true --set global.hubble.enabled=true --set global.hubble.metrics.enabled='{dns,drop,tcp,flow,port-distribution,icmp,http}'`

Fixes the issue?

**Comment by tibers** [comment]
Yeah running this and specifying `--namespace kube-system` does resolve my error.
