### ISSUE TITLE
Hubble `node_name` field should contain cluster name

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#13872]
The `Flow` and `GetFlowsResponse` messages both have a `node_name` field which conatins the name of the Cilium node which produced this flow/event:

https://github.com/cilium/cilium/blob/0507c620b6a0fb0acc247a6276fcf4ef9c86bd3c/api/v1/flow/flow.proto#L46-L47

However, this field currently only contains the node name, without it's cluster-mesh prefix. If the cluster name is _not_ the default cluster name, then we should prefix the node name with its cluster name.

Current output:
```console
$ hubble observe --last 2 -o compact --print-node-name
Nov  3 11:40:45.407 [ip-172-0-51-175.us-west-2.compute.internal]: [...]
Nov  3 11:40:46.554 [ip-172-0-121-242.us-west-2.compute.internal ]: [...]
```

Expected output:
```console
$ hubble observe --last 2 -o compact --print-node-name
Nov  3 11:40:45.407 [cluster5/ip-172-0-51-175.us-west-2.compute.internal]: [...]
Nov  3 11:40:46.554 [cluster7/ip-172-0-121-242.us-west-2.compute.internal ]: [...]
```

The node_name is currently assigned in multiple places, such as e.g. the observer and the monitor consumer:
https://github.com/cilium/cilium/blob/70510d6ee22fda75cb623f900bd2445d4d11ba5a/pkg/hubble/observer/local_observer.go#L406
https://github.com/cilium/cilium/blob/bda4733ef4d47db3bfd6722c208271e0db9cb623/pkg/hubble/monitor/consumer.go#L105

Instead of invoking `nodesTypes.GetName()`, we should introduce a helper that returns the node name with a cluster-mesh prefix (if available), i.e. prefix the result of `nodesTypes.GetName()` with `option.Config.ClusterName + /` if `option.Config.ClusterName != defaults.ClusterName`.

**Comment by Maddy007-maha** [comment]
Hi,

I want to work on this issue, can you assign this to me?
