### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [cilium/cilium#13879]
The README file in this repo has some bad links - [404:NotFound]

Status code [404:NotFound] - Link: https://docs.cilium.io/en/stable/install/upgrade/
Status code [404:NotFound] - Link: http://docs.cilium.io/en/doc-1.0/install/system_requirements

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by joestringer** [comment]
Thanks for the report!

These should point to the `stable` version. The upgrade guide has been moved to operations/upgrade.
