### ISSUE TITLE
Empty endpointSelector in CCNP (ciliumclusterwidenetworkpolicy) does not select all endpoints in cluster

### ISSUE THREAD

**Issue by petreski** [cilium/cilium#13883]
## Bug report

**General Information**

- Cilium version: v1.8.5
- Kernel version: 5.9.2-1.el7.elrepo.x86_64
- Orchestration system version in use: Rancher v2.4.8, kubernetesVersion v1.18.6, 
- Link to relevant artifacts (policies, deployments scripts, ...): https://github.com/petreski/cilium-examples/blob/main/ccnp.yaml https://github.com/petreski/cilium-examples/blob/main/cnp.yaml
- Link to the generated sysdump: https://github.com/petreski/cilium-examples/blob/main/cilium-sysdump-20201104-213950.zip and the archive from the bugtool: https://github.com/petreski/cilium-examples/blob/main/cilium-bugtool-20201104-205401.735%2B0000-UTC-105119674.tar

**How to reproduce the issue**

1. apply the CCNP
2. apply the CNP on the namespace playground
3. try to reach https://cilium.io from a pod in the namespace playground: kubectl exec -it mynginxapp2-79d77649-jvjvk -n playground -- curl -s https://cilium.io

My expectation is that having endpointSelector: {} in the CCNP should allow all pods from any namespace to reach https://cilium.io
However, this doesn't work (for me) as expected.

As a workaround, adding
  endpointSelector:
   matchLabels:
     org: company

and applying org=company label on the pods in the namespace playground gives expected results.

**Comment by joestringer** [comment]
Hi @petreski , when you extend the endpointSelector to `{}`, it will select all endpoints in the cluster, which will include kube-dns. Therefore you also need to extend the CCNP to allow kube-dns to access the upstream DNS server, otherwise kube-dns will be unable to resolve outside domains and the traffic from kube-dns to the outside world would be dropped.

Depending on the applications you have deployed, some of them like kube-dns (coredns) may also need access to the apiserver, this caused some trouble for me while trying to reproduce the issue as well.

**Comment by petreski** [comment]
> Hi @petreski , when you extend the endpointSelector to `{}`, it will select all endpoints in the cluster, which will include kube-dns. Therefore you also need to extend the CCNP to allow kube-dns to access the upstream DNS server, otherwise kube-dns will be unable to resolve outside domains and the traffic from kube-dns to the outside world would be dropped.
> 
> Depending on the applications you have deployed, some of them like kube-dns (coredns) may also need access to the apiserver, this caused some trouble for me while trying to reproduce the issue as well.

Is it possible to find such example somewhere in the documentation?

**Comment by pchaigno** [comment]
The [documentation on policies](https://docs.cilium.io/en/stable/policy/) has a lot of different examples. How exactly you want to restrict kube-dns's egress communications is up to you, but you need to allow kube-dns to access the apiserver (with an L3-only rule or with an L3+L4 rule for example) and the upstream DNS server(s) (probably toPorts rule or toCIDR+toPorts rule if you know those servers' IP addresses). You can also allow all on kube-dns's egress of course.

**Comment by petreski** [comment]
Thanks a lot! I was able to solve this by adding:

    - toCIDR:
      - 10.0.2.3/32
      toPorts:
      - ports:
        - port: "53"
          protocol: UDP
