### ISSUE TITLE
bpf: DumpReliablyWithCallback iterates until maxLookup when callback deletes last entry

### ISSUE THREAD

**Issue by brb** [cilium/cilium#13905]
I've noticed that **sometimes** the `(*bpf.Map).DumpReliablyWithCallback()` iterates until the `maxLookup` is reached when an invocation of a callback removes the last entry from the map. This can potentially lead to wasted CPU cycles.

I haven't looked in great details, but it seems that this happens because we don't effectively check for the `nextKeyErr`, as `continue` is invoked because of `LookupElementFromPointers()` failing due to EOF.

**Comment by Rolinh** [comment]
From what I recall, `ErrMaxLookup` was added to deal with the fact that when the map is being updated at the same time it's being iterated (this can happen as this `DumpReliablyWithCallback()` is lockless), the iteration loop backtracks to catch the change. So to prevent re-starting the iteration too many times for the case where the map is very frequently updated, `maxLookup` was added. I'm unsure if it's possible to avoid restarting the whole map iteration process when the the entry being modified/deleted has not yet been iterated over.

**Comment by brb** [comment]
@rolinh Missed your comment. Thanks for the explanation. I think it's fine to keep the issue closed.
