### ISSUE TITLE
Expose runtime config via `cilium config` CLI

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13913]
At the moment, `cilium config` only exposes a subset of all of the agent configuration:

```
# cilium config
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Disabled
DebugLB                  Disabled
DropNotification         Enabled
MonitorAggregationLevel  Medium
PolicyAuditMode          Disabled
PolicyTracing            Disabled
PolicyVerdictNotification Enabled
TraceNotification        Enabled
k8s-configuration
k8s-endpoint
PolicyEnforcement        default
MonitorNumPages          64
```

Most of the above is related to datapath-specific configuration.

As far as I know, we can't currently query the active cilium configuration from the agent. Users can run things like `kubectl -n kube-system get configmap cilium-config`  to fetch a subset of the configuration, or they can look at the beginning of the cilium-agent logs (if they were not rotated out already). But I'm not sure whether there is a comprehensive way to get the exact currently-active configuration options.

Extending cilium config could help with debugging live environments based on the configuration settings that are currently active.

Note, we would likely want to make all of this configuration read-only to begin with (writes denied server-side in cilium-agent) as the central code may not generically handle dynamically modifying arbitrary configuration options.

**Comment by brb** [comment]
Also, we should move some items which denote configuration from `cilium status (--verbose)` to `cilium config` (e.g. `KubeProxyReplacement`).

**Comment by h3llix** [comment]
@joestringer @pchaigno Can you give more insights on this issue or on which configurations need to be exposed. Also what is the expected result when this issue gets resolved?

**Comment by pchaigno** [comment]
> Can you give more insights on this issue or on which configurations need to be exposed.

All Cilium agent configurations need to be exposed. See `pkg/option/`.

> Also what is the expected result when this issue gets resolved?

`cilium config` would show the full configuration of the agent, similarly to what you have at the beginning of the Cilium logs, except with the current values.
