### ISSUE TITLE
vagrant script: detect colliding active virtualbox VMs and warn users

### ISSUE THREAD

**Issue by kkourt** [cilium/cilium#13928]
Running the vagrant script with `NWORKERS=1` did not work for me. Specifically, `k8s2` could not connect to the API server even though everything (e.g., certificates) looked fine on the host. After a long debugging session, we figure out that the issue was a residual `k8s1` machine that was running on virtualbox but was not visible to vagrant.

It would be good to detect these types of residual VMs and warn the users when they run the script.

**Comment by pchaigno** [comment]
Kornilios figured we could probably use `VBoxManage list runningvms` to detect any VM that's already running before starting our new VMs. We would probably need to run this command in our `start.sh` script and print a big warning if we detect anything (with appropriate action: pause, stop, or destroy residual VM).
