### ISSUE TITLE
Pod to Pod performance issues with VXLAN enabled

### ISSUE THREAD

**Issue by gottwald** [cilium/cilium#13947]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
` 1.8.5 fc1a8ac7c 2020-10-28T14:44:12-07:00 go version go1.14.10 linux/amd64`
- Kernel version (run `uname -a`)
`Linux pool-jq4hf6ndv-3kmjl 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
`
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`
- Link to relevant artifacts (policies, deployments scripts, ...)
Discussion in slack: https://cilium.slack.com/archives/C1MATJ5U5/p1604585328154000
- Generate and upload a system zip:
[cilium-sysdump-20201109-110600.zip](https://github.com/cilium/cilium/files/5510040/cilium-sysdump-20201109-110600.zip)

**How to reproduce the issue**

1. Create a fresh k8s cluster (in our case running on VMs that are connected through a VPC based on STT)
1. Run cilium in tunnelling mode with VXLAN
1. Do simple iperf tests between to pods on different nodes
1. We expected to see a performance of about 2 Gbits/s (what the VMs are able to do), but we're seeing speeds in the range of 1.2 Gbits/s with dips down to 250 Mbit/s
1. When we alter the cilium-config to disable tunnelling, we get about 2 Gbits/s.

`top` on both nodes doesn't look concerning.
Only on the server side software interrupts (si) go up to 45%.
`perf top` looks like this on the client side:
```
Samples: 117K of event 'cycles', 2750 Hz, Event count (approx.): 17578188326
Overhead  Shared Object              Symbol
   9.77%  [kernel]                   [k] do_csum
   8.21%  [kernel]                   [k] copy_user_enhanced_fast_string
   4.50%  [kernel]                   [k] __slab_free
   3.10%  [kernel]                   [k] skb_segment
   2.51%  [kernel]                   [k] skb_release_data
   1.98%  [kernel]                   [k] __copy_skb_header
   1.91%  [kernel]                   [k] ipt_do_table
   1.90%  [kernel]                   [k] start_xmit
```
`perf top` on the server side:
```
Samples: 61K of event 'cycles', 1500 Hz, Event count (approx.): 38627478524
Overhead  Shared Object              Symbol
  11.31%  [kernel]                   [k] ipt_do_table
   3.04%  [kernel]                   [k] copy_user_enhanced_fast_string
   2.91%  [kernel]                   [k] do_csum
   2.71%  [kernel]                   [k] fib_table_lookup
   2.32%  [kernel]                   [k] nf_hook_slow
   2.18%  [kernel]                   [k] dev_gro_receive
   2.04%  [kernel]                   [k] fib_rules_lookup
```

We also tried a 5.9 kernel which included this patch (http://patchwork.ozlabs.org/project/netdev/patch/20200923201815.388347-1-zenczykowski@gmail.com/) but it didn't fix our problem.

**Comment by borkmann** [comment]
@gottwald could you generate a flamegraph over the iperf run? I'd like to know whether the do_csum() is related to the vxlan driver or bpf code itself. Thx

**Comment by gottwald** [comment]
I believe we can close this.
We were able to reproduce this problem in our environment with VXLAN on STT manually without any cilium components.
@borkmann still interested in the flamegraph?

**Comment by borkmann** [comment]
@gottwald thanks for confirming! Yeah in that case we might be able to close the issue if not Cilium related. Looks like VXLAN on STT is not in upstream kernel.. currently don't have any insights there. In any case, if you see anything related to Cilium we can just reopen. Thanks!
