### ISSUE TITLE
Do not SNAT host netns application connections when running in lb-only mode with DSR

### ISSUE THREAD

**Issue by brb** [cilium/cilium#14006]
Currently we track host netns application connections to outside with BPF SNAT in order to avoid cases when non-host netns connection (e.g. NodePort BPF (SNAT) to remote node or pod to outside) is SNAT-ed to existing host netns application. However, when running in the lb-only mode with DSR being enabled, the tracking is not needed, as the NodePort BPF does not SNAT requests, and BPF-masq is disabled.

Disabling the tracking should improve perf for ingress and egress.

**Comment by julianwiedmann** [comment]
Pretty sure that this is no longer an issue. With (non-hybrid) DSR enabled and BPF-Masquerade disabled, the SNAT code in `to-netdev` is skipped: https://github.com/cilium/cilium/blob/14e24a6659b3e44f8e302ad1ad5de1dba5a659ca/bpf/lib/nodeport.h#L2339-L2345
