### ISSUE TITLE
JSON based logging not applied everywhere

### ISSUE THREAD

**Issue by ungureanuvladvictor** [cilium/cilium#14028]
## Bug report

When running the `cilium-operator` with `--log-opt=format=json` CLI param I see JSON logs but interleaved some text logs:
```
{"level":"debug","msg":"Controller func execution time: 1.003627711s","name":"ipam-node-interval-refresh","subsys":"controller","uuid":"26d222cf-2605-11eb-9fee-124cf99b3437"}
{"instanceID":"i-0e658366a511b30d4","level":"debug","msg":"Refreshing node","name":"ip-10-0-35-70.ec2.internal","subsys":"ipam"}
{"instanceID":"i-0e658366a511b30d4","level":"debug","msg":"Updating node in apiserver","name":"ip-10-0-35-70.ec2.internal","poolSize":14,"subsys":"ipam"}
{"instanceID":"i-07c8bc1020981ea1d","level":"debug","msg":"Updating node in apiserver","name":"ip-10-0-37-108.ec2.internal","poolSize":14,"subsys":"ipam"}
{"instanceID":"i-07c8bc1020981ea1d","level":"warning","msg":"Instance not found! Please delete corresponding ciliumnode if instance has already been deleted.","name":"ip-10-0-37-108.ec2.internal","subsys":"ipam"}
{"instanceID":"i-07c8bc1020981ea1d","level":"warning","msg":"Instance not found! Please delete corresponding ciliumnode if instance has already been deleted.","name":"ip-10-0-37-108.ec2.internal","subsys":"ipam"}
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: kvstore.EventChan
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: kvstore.EventChan
{"eventType":2,"key":"cilium/state/nodes/v1/default/ip-10-0-37-108.ec2.internal","level":"debug","msg":"Received key update via kvstore [value ]","storeName":"store-cilium/state/nodes/v1","subsys":"shared-store"}
{"level":"debug","msg":"Controller func execution time: 2.545µs","name":"restart-unmanaged-kube-dns","subsys":"controller","uuid":"02d0905c-2605-11eb-9fee-124cf99b3437"}
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: kvstore.EventChan
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: kvstore.EventChan
```

**General Information**

- Cilium version (run `cilium version`)
`1.8.4`
- Kernel version (run `uname -a`)
`Linux ip-10-0-2-53.ec2.internal 4.15.0-2000-aws-fips #4-Ubuntu SMP Tue Jan 28 12:41:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"a9e59e859b0b7f535905a99afd434d7caeb0642c", GitTreeState:"clean", BuildDate:"2020-08-24T14:13:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"a9e59e859b0b7f535905a99afd434d7caeb0642c", GitTreeState:"clean", BuildDate:"2020-08-24T14:10:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
None
- Generate and upload a system zip:
None

**How to reproduce the issue**

1. Deploy `cilium-operator` version `1.8.4` and enable `--log-opt=format=json` with external `etcd` as the data store
2. Observe `STDOUT`

**Comment by ungureanuvladvictor** [comment]
I suspect that somewhere in the kvstore code we log the `kvstore.EventChan` as a log field and logrus errors out:
- https://github.com/sirupsen/logrus/issues/642
- https://github.com/sirupsen/logrus/issues/871

**Comment by joestringer** [comment]
I'd take a guess that this is a combination of enabling debug logging + the following statement trying to log the `Watcher` structure, which embeds the `EventChan` structure:

https://github.com/cilium/cilium/blob/c5ed9aeb217eb307e496ad17b19e1d8d93436894/pkg/kvstore/events.go#L121

This is likely because `Watcher` does not have a `MarshalJSON()` function, so it falls back to some default Go marshalling implementation. This wouldn't occur when running regular string logging because `Watcher` does implement `String()`. Should be an easy fix.
