### ISSUE TITLE
Consider auto-posting failures from Jenkins CI runs to PRs to assist developer workflow

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14049]
From @eloycoto in Slack:

> Because the tests take a lot, if something fails, the output of the test is uploaded to S3 (By the test suite), and reported in the PR as a comment.
>
> The good points here are:
> * If a developer knows the fail, they can check if it's a flake before stoped it. 
> * If you want to run the whole testsuite, you can, but still debugging the issue meanwhile.

This was following a discussion about the merits of fail-fast, where fail-fast can shorten the feedback loop for development when there is a legitimate failure, but causes unnecessary additional CI runs if there is a CI flake (because the whole CI run must be restarted). 

The idea is that instead of running CI with fail-fast, if a comment is posted to the PR as soon as there is a failure, then in the case of legitimate failures, the developer will see the failure more quickly without having to wait for the full CI run to complete, and they can begin investigating the failure when the comment is posted.

**Comment by ti-mo** [comment]
With the GHA setup we have today, this is mostly the case. Inspecting individual test failures are 2-3 clicks away and the sysdumps are relatively fine-grained. Re-runs can be done on individual sub-suites.

Closing this as completed.
