### ISSUE TITLE
postStart sometimes not work

### ISSUE THREAD

**Issue by gangseok514** [cilium/cilium#14079]
## Bug report

Sometimes cni-install.sh in postStart not work. so cilium-cni file is not copied to /opt/cni/bin.
the application containers on the same node not working properly and the below event is shown.

"... failed to find plugin "cilium-cni" in path [/opt/cni/bin]"

There is no errors in kubelet except the above errors and no differences of logs between normal cases.
I cannot find the cause.

When I run cni-install.sh manually using kubectl exec, it is fixed.

Is it possible to run preStop in previous pod while running postStart?
I cannot find the log in kubelet but I can find a PR about it

https://github.com/cilium/cilium/pull/11830

I can fix the issue with the PR?

**General Information**

- Cilium version (run `cilium version`): 1.15.9
- Kernel version (run `uname -a`): 4.15
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) k8s 1.15.11
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. instruction 1
2. instruction 2

**Comment by aanm** [comment]
@gangseok514 thanks for opening the GH issue I'm having troubles to understand which Cilium version are you running as `1.15.9` is not a valid version.

The PR #11830 would likely fix your issue so it would probably be better to upgrade Cilium.

**Comment by gangseok514** [comment]
@aanm Thanks for your kindly answer and sorry about the wrong version. it is 1.5.9 not 1.15.9 (I was confused with k8s version)
Yes, I know the version is a little bit older... 
I failed to reproduce the issue. so I just wanted to check it can be fixed by the PR. 
I'll test it with the PR. Thanks again.
