### ISSUE TITLE
Cilium fails to start if IPv6 is disabled via kernel option

### ISSUE THREAD

**Issue by jochenseeber** [cilium/cilium#14094]
## Bug report

Cilium does not start with IPv6 disabled in the kernel ("ipv6.disable=1")

From the log

```
level=info msg=" --enable-ipv6='false'" subsys=daemon
...
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t mangle -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `mangle': Address family not supported by protocol" subsys=iptables
```

The problem is in in [iptables.go](https://github.com/cilium/cilium/blob/c5ed9aeb217eb307e496ad17b19e1d8d93436894/pkg/datapath/iptables/iptables.go#L375):

```
    if err := modulesManager.FindOrLoadModules(
		"ip6_tables", "ip6table_mangle", "ip6table_raw", "ip6table_filter"); err != nil {
		if option.Config.EnableIPv6 {
			log.WithError(err).Warning(
				"IPv6 is enabled and ip6tables modules could not be initialized")
		}
		log.WithError(err).Debug(
			"ip6tables kernel modules could not be loaded, so IPv6 cannot be used")
		ip6tables = false
	}
	m.haveIp6tables = ip6tables
```

On Ubuntu, ip6_tables loads, so m.haveIp6tables is never set to false. Later, ip6tables is executed [here](https://github.com/cilium/cilium/blob/c5ed9aeb217eb307e496ad17b19e1d8d93436894/pkg/datapath/iptables/iptables.go#L460).

Init should probably check something like `/sys/module/ipv6/parameters/disable` (this is beyond my Linux skills :-).

**General Information**

- Cilium version: 1.9.0
- Kernel version: Linux XXX 5.4.0-54-generic #60-Ubuntu SMP Fri Nov X XX:XX:XX UTC XXXX x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s3", GitCommit:"0e4fbfefe1dd8734756dfa4f9ab4fc89665cece4", GitTreeState:"clean", BuildDate:"2020-11-13T07:19:02Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}, Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s3", GitCommit:"0e4fbfefe1dd8734756dfa4f9ab4fc89665cece4", GitTreeState:"clean", BuildDate:"2020-11-13T07:19:02Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by joestringer** [comment]
Hi @jochenseeber , thanks for the report. Can you confirm whether the `ipv6.disable=1` flag is the same as `sysctl net.ipv6.conf.all.disable_ipv6`? If so, it might just be a matter of extending the function to import `pkg/sysctl` and then check that `value, err := sysctl.Read("net.ipv6.conf.all.disable_ipv6")` has no error with the value "1", then using that as a basis to disable IPv6 in this function.

**Comment by jochenseeber** [comment]
I believe kernel option `ipv6.disable=1` completely removes IPv6 capabilities from the kernel, whereas `net.ipv6.conf.all.disable_ipv6` dynamically turns it on or off. If booted with `ipv6.disable=1`, `/proc/sys/net/ipv6` no longer exists.

I might have time on the weekend to try a fix. Depends on how fast I can get a build environment up and running.

**Comment by joestringer** [comment]
Ah perfect, if it doesn't exist then the `sysctl.Read()` should return a non-nil error. That seems like a promising direction.

Feel free to drop into the #development channel in Slack if you need any help or pointers on getting a dev environment set up.
