### ISSUE TITLE
cilium kernel-check has false negative when config file is missing

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14099]
```
# uname -a
Linux gke-joe-k-e-default-pool-8b860500-h90s 5.3.0-1036-gke #38-Ubuntu SMP Sun Sep 6 05:59:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
# cilium kernel-check
FEATURE                       SUPPORTED                     REQUIRED
CONFIG_NET_SCH_INGRESS        false                         true
CONFIG_NET_CLS_BPF            false                         true
CONFIG_NET_CLS_ACT            false                         true
CONFIG_BPF_JIT                false                         true
CONFIG_HAVE_EBPF_JIT          false                         true
CONFIG_BPF                    false                         true
CONFIG_BPF_SYSCALL            false                         true
CONFIG_LWTUNNEL_BPF           false                         false
CONFIG_BPF_EVENTS             false                         false
CONFIG_CGROUP_BPF             false                         false
```

This is running from a Cilium pod in a successfully-running GKE cluster.

The tool should at least warn if it is unable to detect support via kernel config (eg due to missing config file).

**Comment by Shreyas1717** [comment]
Hi @joestringer when I tried the same code in GKE, I am getting the following response. 
$ kubectl -n cilium exec cilium-vbwqb  -- uname -a
Linux gke-cluster1-default-pool-cfa9ff5d-mwxf 4.19.112+ #1 SMP Sat Oct 10 13:45:37 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl -n cilium exec cilium-vbwqb  -- cilium kernel-check
FEATURE                             SUPPORTED                     REQUIRED
CONFIG_BPF_JIT                       true                                 true
CONFIG_HAVE_EBPF_JIT           true                                 true
CONFIG_BPF                             true                                 true
CONFIG_BPF_SYSCALL             true                                 true
CONFIG_NET_SCH_INGRESS       false                             true
CONFIG_NET_CLS_BPF                false                             true
CONFIG_NET_CLS_ACT               true                              true
CONFIG_LWTUNNEL_BPF           true                              false
CONFIG_BPF_EVENTS                 true                              false
CONFIG_CGROUP_BPF               true                              false

**Comment by Shreyas1717** [comment]
Hi @joestringer when I tried the same code in GKE, I get the following response. 

![Screenshot](https://user-images.githubusercontent.com/62245216/103768872-4a0af980-5049-11eb-8584-4b07ba08e61b.jpeg)

**Comment by pchaigno** [comment]
@Shreyas1717 Based on the difference in kernel versions, I'm guessing Joe tested on the rapid release channel, which has a more recent COS image with a newer kernel.

**Comment by joestringer** [comment]
Ah, good point. I tend to run the GKE Ubuntu images rather than the COS ones, just so it's easier to swap out the kernel for development purposes. So this may be more related to the Ubuntu image.

**Comment by nyrahul** [comment]
On the native kubeadm based setup using cilium I get:

```
rahul@vbox:~$ kubectl exec -it -n kube-system cilium-xtlv7 -- cilium kernel-check
FEATURE                       SUPPORTED                     REQUIRED
CONFIG_BPF                    false                         true
CONFIG_BPF_SYSCALL            false                         true
CONFIG_NET_SCH_INGRESS        false                         true
CONFIG_NET_CLS_BPF            false                         true
CONFIG_NET_CLS_ACT            false                         true
CONFIG_BPF_JIT                false                         true
CONFIG_HAVE_EBPF_JIT          false                         true
CONFIG_CGROUP_BPF             false                         false
CONFIG_LWTUNNEL_BPF           false                         false
CONFIG_BPF_EVENTS             false                         false

rahul@vbox:~$ grep CONFIG_BPF /boot/config-`uname -r`
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT_ALWAYS_ON=y
# CONFIG_BPFILTER is not set
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_BPF_EVENTS=y
# CONFIG_BPF_KPROBE_OVERRIDE is not set

rahul@vbox:~$ uname -a
Linux vbox 5.4.84 #1 SMP Sat Dec 19 17:30:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

In the vagrant dev env as well a similar output is seen:
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ cilium  kernel-check
level=error msg="Command execution failed" cmd="[bpftool -j feature probe]" error="exit status 255" subsys=probes
level=warning msg="{\"error\":\"full feature probing requires root privileges\"}" subsys=probes
level=fatal msg="could not run bpftool" error="exit status 255" subsys=probes
```

**Comment by brandshaide** [comment]
isn't this already covered by #14314

**Comment by pchaigno** [comment]
Yep, looks like a duplicate. Closing.
