### ISSUE TITLE
Describe clustermesh-apiserver architecture

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14096]
I couldn't find any (even short) description of how clustermesh-apiserver works (architecture; is it serving an etcd API and internally querying k8s apiserver? Or serving a k8s apiserver API and internally querying etcd? how does it fit into the cluster?), it would be good to add this at least to maybe the `clustermesh-apiserver/README.md` or perhaps under the documentation as a new page in the "concepts" section.

**Comment by oblazek** [comment]
I have been looking exactly for this information :) ..had to go through the code of cilium-cli and clustermesh code to understand it.

**Comment by oblazek** [comment]
@jrajahalme any progress with this or is it ok to take this over?

**Comment by pchaigno** [comment]
@oblazek I've assigned you.
