### ISSUE TITLE
Exposing new BPF failed: invalid LXC MAC: invalid MAC address 

### ISSUE THREAD

**Issue by ArthurChiao** [cilium/cilium#14100]
Caused by security-relevant-labels configuration changes. Not sure if this is the expected behavior, or a bug.

# General Information

- Cilium version: 1.8.4
- Kernel version: 4.19.118

# Dig inside

According to https://docs.cilium.io/en/v1.8/operations/scalability/identity-relevant-labels/#configuring-identity-relevant-labels,
after specifying a security relevant label list to cilium agent and restart the agent, all endpoints on this node will be regenerated with the given labels + default labels.

One problem is that, if `reserved:.host` (or `reserved:.*`) is not included in the provided label list, the `cilium_host` endpoint will lose `reserved:host` label. This is ok for now.

But when rolling back the change, that is, removing the specified label list and restarting the agent, it will raise the above errors.
Note that subsequently, all pods' traffic on this node will be interrupted.

My understanding is that `IsHost()` returns `false` for `cilium_host` endpoint during this case: https://github.com/cilium/cilium/blob/master/pkg/endpoint/bpf.go#L629

In the next, it will treat this endpoint as a normal endpoint, and try to get its `lxcMAC`, then failed as `cilium_host` has no corresponding `lxcMAC`. 

# Try-outs

Quickly tested that follow two ways could avoid the problem:

1. Via config: add `reserved:host` (or `reserved:.*`) to the custom label list.
2. Via patch: add `reserved:host` (or `reserved:.*`) to the (hard-coded) default label list, and re-compile cilium agent, https://github.com/cilium/cilium/blob/master/pkg/labelsfilter/filter.go#L163

Thanks!

@joestringer

**Comment by aanm** [comment]
@ArthurChiao did you miss some outputs? The text that you have written in the PR description says "it will raise the above errors." but I don't understand which errors you are referring to.

**Comment by ArthurChiao** [comment]
Sorry, "the above errors" means the title `Exposing new BPF failed: invalid LXC MAC: invalid MAC address`.

Full error messages look like this:

```
level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=0s bpfWaitForELF=0s bpfWriteELF=0s buildDuration="573.714µs" containerID= datapathPolicyRevision=0 desiredPolicyRevision=3 endpoi
ntID=1826 error="Exposing new BPF failed: invalid LXC MAC: invalid MAC address " identity=281659 ipv4= ipv6= k8sPodName=/ mapSync="15.369µs" policyCalculation="8.24µs" prepareBuild="230.602µs" proxyConfiguration
="16.706µs" proxyPolicyCalculation="98.879µs" proxyWaitForAck=0s reason="one or more identities created or deleted" subsys=endpoint waitingForCTClean=507ns waitingForLock="1.929µs"
level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=1826 error="Exposing new BPF failed: invalid LXC MAC: invalid MAC address " identity=281659
 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

**Comment by pchaigno** [comment]
Thanks for the report @ArthurChiao!
Could you send a pull request with the fix? Happy to help on any blocker (and to review of course)!

**Comment by pchaigno** [comment]
@ArthurChiao Could you detail how you specified the list of security-relevant labels? I'm unable to reproduce with our `--labels` flag unless I explicitly exclude `reserved:host`. I don't think the patch at #14114 currently protects against explicit exclusion of `reserved:host` though.

**Comment by ArthurChiao** [comment]
All my previous tests were based on `config-map`,

```shell
$ ls
bpf-ct-global-any-max   clustermesh-config               enable-health-checking  enable-node-port                    k8s-kubeconfig-path     masquerade             sidecar-istio-proxy-image
bpf-ct-global-tcp-max   cluster-name                     enable-hubble           flannel-manage-existing-containers  kube-proxy-replacement  monitor-aggregation    tofqdns-enable-poller
clean-cilium-bpf-state  custom-cni-conf                  enable-ipv4             flannel-master-device               kvstore                 policy-audit-mode      tunnel
clean-cilium-state      debug                            enable-ipv6             flannel-uninstall-on-exit           kvstore-opt             preallocate-bpf-maps   wait-bpf-mount
cluster-id              enable-endpoint-health-checking  enable-legacy-services  identity-allocation-mode            labels                  prometheus-serve-addr

# workable label list
$ cat labels
reserved:.* k8s:!io.cilium.k8s.namespace.labels.* k8s:io.cilium.k8s.policy k8s:app k8s:name [our-specific-labels] 
```

```shell
# broken label list
$ cat labels
k8s:!io.cilium.k8s.namespace.labels.* k8s:io.cilium.k8s.policy k8s:app k8s:name [our-specific-labels] 
```

where, `[our-specific-labels]` is a list with all labels in the format like `k8s:xxx.ourcorp.com/yyy`. I can send the intact label list or any other configuration via DR if you are interested. @pchaigno Thanks!
