### ISSUE TITLE
Azure: tunnelfront connectivity and traffic visibility issue

### ISSUE THREAD

**Issue by ti-mo** [cilium/cilium#14106]
## Bug report

Two-fold:
- `kubectl exec` only works on Pods running on a node where `tunnelfront` is running
- no visibility into `tunnelfront` traffic

Affected version(s): 1.9.0 and earlier.

## Description

While investigating some Pod connectivity issues on AKS, mysterious apiserver -> kubelet connection failures started popping up.

@dctrwatson reported this as well in https://github.com/cilium/cilium/issues/12113#issuecomment-730879059.

Since we're currently affected by multiple connectivity issues due to interactions with the default `azure-vnet` CNI plugin, fixes are underway for the connectivity part.

## To Do

The operator currently restarts CoreDNS after Cilium is deployed so we can introspect DNS traffic. The same needs to happen on Azure for the `tunnelfront` pod.

**Comment by dctrwatson** [comment]
Can also confirm this affects 1.8.5

**Comment by ti-mo** [comment]
Restarting unmanaged non-host-networked Pods will be handled by cilium-cli going forward: https://github.com/cilium/cilium-cli/blob/71312fd29ce070b8efa93e05e789f4915f17d597/install/install.go#L1445. Closing this.
