### ISSUE TITLE
Investigate reports that hostport doesn't work with ENI integration

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14109]
From Slack, report:

* Cilium 1.9.0
* EKS 1.17
* AMI: Amazon Linux 2 `amazon-eks-node-1.17-v20201211 (ami-0bf566baf2c93ba40)`

User reports that HostPort does not work correctly.

We should be able to deploy and deploy the [connectivity-check tool YAMLs](https://github.com/cilium/cilium/tree/master/examples/kubernetes/connectivity-check) to verify whether there is an easy reproduce of this issue on EKS.

Update 2020-12-15: It appears easily reproducible, but it seems that there is an expectation that hostport requires either chaining on top of portmap CNI or running kube-proxy free. Most likely we just need to make sure the docs are updated to reflect this requirement.

**Comment by christarazi** [comment]
Seems like it's easily reproducible:

```
❯ k -n cilium-test get pods
NAME                                                         READY   STATUS    RESTARTS   AGE
echo-a-76c5d9bd76-xgft8                                      1/1     Running   0          88s
echo-b-795c4b4f76-dcqq6                                      1/1     Running   0          87s
echo-b-host-6b7fc94b7c-ch7kl                                 1/1     Running   2          87s
echo-c-86cf9b9dc9-d2756                                      1/1     Running   0          87s
echo-c-host-77865d5bb9-jjt82                                 1/1     Running   0          87s
host-to-b-multi-node-clusterip-85476cd779-7n7wl              1/1     Running   0          82s
host-to-b-multi-node-headless-dc6c44cb5-dm2kz                1/1     Running   0          82s
pod-to-a-79546bc469-2hrvl                                    1/1     Running   0          86s
pod-to-a-allowed-cnp-58b7f7fb8f-hhj78                        1/1     Running   0          85s
pod-to-a-denied-cnp-6967cb6f7f-lf54c                         1/1     Running   0          86s
pod-to-a-intra-node-proxy-egress-policy-6bbf48ff97-mp6v9     2/2     Running   0          85s
pod-to-a-multi-node-proxy-egress-policy-67869b6cd6-dq4rz     2/2     Running   0          84s
pod-to-b-intra-node-hostport-76b9ddd5dc-ktnjw                0/1     Running   1          81s
pod-to-b-intra-node-nodeport-9b487cf89-wgz7s                 1/1     Running   0          81s
pod-to-b-multi-node-clusterip-7db5dfdcf7-kjvh4               1/1     Running   0          83s
pod-to-b-multi-node-headless-7d44b85d69-857zb                1/1     Running   1          83s
pod-to-b-multi-node-hostport-69b97ff479-x7hbw                0/1     Running   1          82s
pod-to-b-multi-node-nodeport-7ffc76db7c-tj8pv                1/1     Running   0          81s
pod-to-c-intra-node-proxy-ingress-policy-598c596cd9-fqgfv    2/2     Running   0          84s
pod-to-c-intra-node-proxy-to-proxy-policy-6cb688865b-6scgw   2/2     Running   0          83s
pod-to-c-multi-node-proxy-ingress-policy-6c66c8bfd-6fkdr     2/2     Running   0          84s
pod-to-c-multi-node-proxy-to-proxy-policy-55b596656c-fbhjg   2/2     Running   0          83s
pod-to-external-1111-d56f47579-fkbmp                         1/1     Running   0          86s
pod-to-external-fqdn-allow-google-cnp-78986f4bcf-zqt4j       1/1     Running   0          85s
```

**Comment by joestringer** [comment]
The connectivity check page states that for the hostport check to work,

> Requires either eBPF hostport to be enabled or portmap CNI chaining.

@christarazi did you configure either of these options?

**Comment by aditighag** [comment]
You can check the output of `cilium status` in the verbose mode to see if the functionality is enabled. 

` cilium status --verbose`

>KubeProxyReplacement Details:
  Status:             Partial
  Session Affinity:   Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Disabled
  - LoadBalancer:   Disabled
  - externalIPs:    Disabled
  - HostPort:       Disabled

**Comment by aditighag** [comment]
I just deployed an eks cluster with cilium 1.9.1, and verified that hostport is working.

@christarazi Can you attach sysdump from your cluster if you are still able to reproduce this issue? As a first step, you can also check the output of cilium status command I've listed in the last comment.

@joestringer Can you add a link to the Slack message where the user reported this issue? I can follow up with them if needed. 

```
cilium service list
ID   Frontend              Service Type   Backend

12   192.168.6.215:8080    HostPort       1 => 192.168.65.83:80
13   0.0.0.0:8080          HostPort       1 => 192.168.65.83:80

[ec2-user@ip-192-168-63-140 ~]$ curl 192.168.6.215:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

kubectl get pods -n cilium-test
NAME                                                         READY   STATUS    RESTARTS   AGE
echo-a-76c5d9bd76-9mj9h                                      1/1     Running   0          2m53s
echo-b-795c4b4f76-9xxvh                                      1/1     Running   0          2m53s
echo-b-host-6b7fc94b7c-gcc6n                                 1/1     Running   0          2m53s
echo-c-86cf9b9dc9-7hlxx                                      1/1     Running   0          27s
echo-c-host-77865d5bb9-bmv8z                                 1/1     Running   0          27s
host-to-b-multi-node-clusterip-85476cd779-px47h              1/1     Running   0          2m51s
host-to-b-multi-node-headless-dc6c44cb5-zg99l                1/1     Running   0          2m51s
pod-to-a-79546bc469-pzbz9                                    1/1     Running   0          2m53s
pod-to-a-allowed-cnp-58b7f7fb8f-qk24f                        1/1     Running   0          2m52s
pod-to-a-denied-cnp-6967cb6f7f-ws9j6                         1/1     Running   0          2m52s
pod-to-a-intra-node-proxy-egress-policy-6bbf48ff97-hq2vd     2/2     Running   0          25s
pod-to-a-multi-node-proxy-egress-policy-67869b6cd6-8f4wz     2/2     Running   0          25s
pod-to-b-intra-node-hostport-76b9ddd5dc-xrj5z                1/1     Running   0          23s
pod-to-b-intra-node-nodeport-9b487cf89-659jr                 1/1     Running   0          2m50s
pod-to-b-multi-node-clusterip-7db5dfdcf7-rgrq4               1/1     Running   0          2m51s
pod-to-b-multi-node-headless-7d44b85d69-bw5sp                1/1     Running   0          2m51s
pod-to-b-multi-node-hostport-69b97ff479-vfnlx                1/1     Running   0          23s
pod-to-b-multi-node-nodeport-7ffc76db7c-z9b5d                1/1     Running   0          2m50s
pod-to-c-intra-node-proxy-ingress-policy-598c596cd9-nkvm7    2/2     Running   0          25s
pod-to-c-intra-node-proxy-to-proxy-policy-6cb688865b-c7trv   2/2     Running   0          24s
pod-to-c-multi-node-proxy-ingress-policy-6c66c8bfd-lkljq     2/2     Running   0          25s
pod-to-c-multi-node-proxy-to-proxy-policy-55b596656c-xvsqc   2/2     Running   0          24s
pod-to-external-1111-d56f47579-xsq77                         1/1     Running   0          2m53s
pod-to-external-fqdn-allow-google-cnp-78986f4bcf-66bw6       1/1     Running   0          2m52s

```

**Comment by joestringer** [comment]
@aditighag did you deploy with kube-proxy-free / on a new kernel? How did you install it?

I suspect that the main action point here is to highlight that depending on the kernel version you deploy on, you need to either chain on top of portmap CNI or it will just work.

**Comment by aditighag** [comment]
> @aditighag did you deploy with kube-proxy-free / on a new kernel? How did you install it?
> 
> I suspect that the main action point here is to highlight in the docs that depending on the kernel version you deploy on, you need to either chain on top of portmap CNI or it will just work.

Yes, I deployed the cluster with kube-proxy-free mode and aws net-next kernel since this issue didn't have enough details regarding reproduction environment. Now that you cc'd me on the thread, I see that the user reported the issue with the chaining mode? I don't have enough context for the chaining mode.

**Comment by joestringer** [comment]
The Slack thread started out with a different problem under chaining mode with `aws-cni` plugin, but later I asked why not to use the ENI mode directly and they stated that they had a problem with hostport in direct Cilium ENI mode. I filed this issue specifically regarding the latter as I wanted to check whether there was a general problem that users may face there, particularly since we had recently fixed a few issues with hostport.

**Comment by joestringer** [comment]
> Yes, I deployed the cluster with kube-proxy-free mode and aws net-next kernel since this issue didn't have enough details regarding reproduction environment

:+1: I see, that at least fits with what I suspect is going on. @christarazi did you try with a default Amazon Linux 2 AMI?

**Comment by aditighag** [comment]
Ok, thanks for the context. I've followed up with the user on Slack with regard to the next steps.

**Comment by pchaigno** [comment]
What's the conclusion from this? Do we just need to add a note in the documentation to highlight requirements?
