### ISSUE TITLE
Cillium fails to start on aarch64(Raspberry Pi 4)

### ISSUE THREAD

**Issue by inductor** [cilium/cilium#14117]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
1.9.0
- Kernel version (run `uname -a`)
`Linux raspberrypi 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Kubernetes 1.19.4
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

Add a RasPi 4 K8s node on Kubernetes
It fails to exec cillium pod

```
standard_init_linux.go:211: exec user process caused "exec format error"                                                                                                                                                                                                    stream closed    
```

**Comment by iam-TJ** [comment]
I suspect this is related to  #9898 - currently images are only built for amd64 not aarch64.

**Comment by aanm** [comment]
@inductor @iam-TJ Since the Cilium doesn't have 100% support yet for arm64, since they lack support for envoy proxy, please try with the image `docker.io/cilium/cilium-dev:v1.9.0` instead.

**Comment by nniehoff** [comment]
I'm using the `docker.io/cilium/cilium-dev:v1.9.1` image on a mixed cluster with amd64 and some raspberry pi 4s.  The pods get further and at least run however now on both architectures the pods fail to completely start with the following fatal message in the logs:

```
level=fatal msg="Envoy: Binary \"cilium-envoy\" cannot be executed" error="exec: \"cilium-envoy\": executable file not found in $PATH" subsys=envoy-manager
```

**Comment by joestringer** [comment]
FYI you can pass `disable-envoy-version-check` (`disableEnvoyVersionCheck: true` in helm) to avoid this issue for v1.9.x dev releases.
