### ISSUE TITLE
EKS nodes constantly regenerating endpoints

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#14120]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
  - 1.7.11
  - 1.8.5
  - 1.8.6
- Kernel version (run `uname -a`)
  - 4.14.198-152.320.amzn2.x86_64
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
  - `Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

The cilium agents are constantly logging `level=info msg="regenerating all endpoints" reason="datapath ipcache" subsys=endpoint-manager` every 10-30s.

There aren't any known ill side-effects of this but it's concerning that this does not happen in non-EKS clusters. Though those other clusters are newer kernels 4.15 and 4.19, so that may have something to do with it.

**Comment by kkourt** [comment]
Thanks for the report.

Since you are not reporting any errors or warnings on the logs, would it be safe to assume that they are not any?

**Comment by joestringer** [comment]
> Though those other clusters are newer kernels 4.15 and 4.19, so that may have something to do with it.

This indeed has something to do with it, here's the relevant trigger:

https://github.com/cilium/cilium/blob/f66515219c21041f17d424cb8f2ca2b1b81c4687/pkg/datapath/ipcache/listener.go#L327

Basically on some kernels, the Longest Prefix Match map implementation lacks support for delete operations, so to ensure that the ipcache does not fill up, there is periodic garbage collection.

This should occur once every 5 minutes for a given node. If it is occurring more frequently, then there may be some issue with the garbage collection; in that case, does `cilium status` output report any problems under the "controllers" section?

**Comment by dctrwatson** [comment]
> Since you are not reporting any errors or warnings on the logs, would it be safe to assume that they are not any?

Correct, no non-info level log lines

> This should occur once every 5 minutes for a given node. If it is occurring more frequently, then there may be some issue with the garbage collection; in that case, does `cilium status` output report any problems under the "controllers" section?

`cilium status --all-controllers` shows `never` in the last error column for all controllers

---

If i restart the agents, it looks like they do start with a 5m interval, but the longer uptime, the more frequent regeneration occurs.

**Comment by dctrwatson** [comment]
> I believe it could be reset more frequently than every 5 minutes if the Identity store connection is disrupted and Cilium re-lists the initial set of Identities in the stor

Would the reconnect show up in the logs at info level?

**Comment by joestringer** [comment]
> Would the reconnect show up in the logs at info level?

I'm not sure they would. Looking directly at the relevant logs around how the GC occurs, it's only at debug level. There might be some other indication elsewhere in the code or some way to infer it from the `cilium status` output.

If my theory above holds, I would for instance expect that the `ipcache-bpf-garbage-collection` controller `Last success` time under `cilium status --all-controllers` would reset more frequently than once every 5 minutes.

**Comment by dctrwatson** [comment]
Is there supposed to be 14 of them?

```
  ipcache-bpf-garbage-collection                                     16s ago          never           0       no error   
  ipcache-bpf-garbage-collection                                     1m28s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     1m46s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     2m21s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     2m38s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     2m3s ago         never           0       no error   
  ipcache-bpf-garbage-collection                                     2m54s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     36s ago          never           0       no error   
  ipcache-bpf-garbage-collection                                     3m17s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     3m38s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     4m13s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     4m29s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     4m49s ago        never           0       no error   
  ipcache-bpf-garbage-collection                                     5m5s ago         never           0       no error   
```

**Comment by dctrwatson** [comment]
Oh, does it start one per remote cluster in a Cilium Mesh?

That's still more `ipcache-bpf-garbage-collection` than clusters...

**Comment by joestringer** [comment]
That looks like it would explain the issue :-) I definitely didn't anticipate that, good find. With the above output in hand, I think it should just be a matter of reviewing the code related to this controller to understand how it could be created so many times (likely the manager for the controller is unique each time so it doesn't see the conflict with the existing controller of the same name).

**Comment by dctrwatson** [comment]
I don't think there was anything related to this issue in 1.8.6 release, just noting this is still happening

**Comment by joestringer** [comment]
Thanks for the report @dctrwatson . I believe the next step is to take a look around this code and understand how it could spawn multiple controllers:

https://github.com/cilium/cilium/blob/f66515219c21041f17d424cb8f2ca2b1b81c4687/pkg/datapath/ipcache/listener.go#L354

It may be something as simple as the Manager for the Controller being duplicated. AFAIK if you re-initialize a Controller with the same name under the same Manager, it should replace the existing Controller rather than creating a new one. By the looks of the code, it currently creates a new manager each time this code is invoked.

**Comment by dctrwatson** [comment]
@joestringer I tried my hand at a fix: https://github.com/cilium/cilium/pull/14300
