### ISSUE TITLE
Random Connection Issues from Ingress Controller

### ISSUE THREAD

**Issue by christiancloudical** [cilium/cilium#14122]
Bug report

**General Information**

- Cilium version 
  Client: 1.8.5 fc1a8ac7c 2020-10-28T14:44:12-07:00 go version go1.14.10 linux/amd64
  Daemon: 1.8.5 fc1a8ac7c 2020-10-28T14:44:12-07:00 go version go1.14.10 linux/amd64

- Kernel version (run `uname -a`)
Linux prod-master-1-deb 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4",    
GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z",  GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4",   GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**How to reproduce the issue**

1. I have 3 Master Nodes deployed on VMware ESX with underlaying nxt as far as I know
2. 4 Worker Nodes running on Baremetal
3. Worker have two nics, only one is configured, but uses a vlan on top ( eth0 -> eth0.10 )
4. It seems, that clustercommunication works without any issues, even Rook is running without problems.
5. Installing nginx ingress in version 0.41.2
6. Curling ingress Node Port is a lucky thing - when the container is newly created, it works for 2 or three times, afterwards I am running mostly in a stuck connection. With timeout in command I get following:
```
curl: (28) Operation timed out after 5500 milliseconds with 0 bytes received
```
Doesn't matter if nginx has a default backend or not
Inside of Kubernetes, it seems there are no packetdrops or anything. We run the same installation on a virtualised environment on top of VMWare and we don't have these issues there.

Would be awesome if I could get help on that, as it is a real strange behaviour...

**Comment by kkourt** [comment]
Thank you for the report.

Would it be possible to provide additional information regarding dropped packets? You can use hubble for that (if it's enabled), otherwise there is also cilium monitor: https://docs.cilium.io/en/v1.8/cmdref/cilium_monitor/#cilium-monitor.

**Comment by brb** [comment]
@christiancloudical Can you please include the sysdump?

**Comment by christiancloudical** [comment]
https://nextcloud.cloudical.net/s/F58EQMXcgt5igoS
Stupid me, forgot that, sorry

**Comment by christiancloudical** [comment]
@kkourt , unfortunatly, I don't see any dropped packages
can you gimme an example how to get the most effective information out of hubble?
Need something where I see 
REQ arrived - forwarded to ingress controller - recieved from controller - sent back to client
hubble observe --service ingress-nginx/ingress-nginx-controller -f
Failed : 
'''
Nov 23 14:33:04.193 [ns61293295]: ingress-nginx/ingress-nginx-controller:32529 -> 192.168.100.99:39064 11 FORWARDED (TCP Flags: SYN, ACK)
Nov 23 14:33:04.193 [ns61293295]: ingress-nginx/ingress-nginx-controller:32529 -> 192.168.100.99:39064 11 FORWARDED (TCP Flags: ACK)
Nov 23 14:33:09.737 [ns61293295]: ingress-nginx/ingress-nginx-controller:32529 -> 192.168.100.99:39064 11 FORWARDED (TCP Flags: ACK)
'''
not failed:
''' 
Nov 23 14:33:17.206 [ns61293295]: ingress-nginx/ingress-nginx-controller:32529 -> 192.168.100.99:39074 11 FORWARDED (TCP Flags: SYN, ACK)
Nov 23 14:33:17.206 [ns61293295]: ingress-nginx/ingress-nginx-controller:32529 -> 192.168.100.99:39074 11 FORWARDED (TCP Flags: ACK)
Nov 23 14:33:17.207 [ns61293295]: ingress-nginx/ingress-nginx-controller:32529 -> 192.168.100.99:39074 11 FORWARDED (TCP Flags: ACK, PSH)
Nov 23 14:33:17.207 [ns61293295]: ingress-nginx/ingress-nginx-controller:32529 -> 192.168.100.99:39074 11 FORWARDED (TCP Flags: ACK, FIN)
'''

**Comment by christiancloudical** [comment]
It figured out, that that issue was a combination of custom kernel and a too low max_pid specification on crio.
So no issue with cilium in here.

**Comment by kkourt** [comment]
>  can you gimme an example how to get the most effective information out of hubble?

@christiancloudical  For future reference, you can use `--type drop` with hubble. 

See example here: https://docs.cilium.io/en/v1.8/operations/troubleshooting/#observing-flows-of-a-specific-pod
