### ISSUE TITLE
CI: RuntimePrivilegedUnitTests: arping failed in TestArpPingHandling

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14125]
https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/2657/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/
[372c1e59_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/5582285/372c1e59_RuntimePrivilegedUnitTests_Run_Tests.zip)

```
level=error msg="arping failed" error=timeout interface=veth0 ipAddr=9.9.9.250 subsys=linux-datapath
node_linux_test.go:1038:
 c.Assert(found, check.Equals, true)
... obtained bool = false
... expected bool = true

START: node_linux_test.go:133: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
PASS: node_linux_test.go:133: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.052s

FAIL: node_linux_test.go:950: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
```

**Comment by brb** [comment]
The test was recently introduced by https://github.com/cilium/cilium/pull/14070.

**Comment by pchaigno** [comment]
I bumped this to daily flakes since I'm seeing it several times per day, just now in e.g. https://github.com/cilium/cilium/pull/14113.

**Comment by brb** [comment]
https://github.com/cilium/cilium/pull/14201 might fix this.

**Comment by tklauser** [comment]
Hit this on #14197 (https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/2765/) and #14200 (https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/2770/) today.

**Comment by aanm** [comment]
@brb still happening

**Comment by brb** [comment]
Managed to reproduce it locally running in the loop, continuing investigation.

**Comment by brb** [comment]
Switching arping implementation to https://github.com/cilium/cilium/pull/13112 didn't resolve the issue. Also, I see with tcpdump that the arping response, which waiting times out according to the failure log, is received by the host.

**Comment by brb** [comment]
First, I checked whether we don't mix netns in Go by running tcpdump in all netns - it's not the case.

Second, I changed the arping library so that it can encode a surrogate request ID in the dest MAC addr to see which ARP request does not get a reply. From it I saw that the request which fails with the "i/o timeout" error is even not sent.

**Comment by brb** [comment]
Tried running tests with strace for the whole day - no luck reproducing the issue.

**Comment by ungureanuvladvictor** [comment]
Hit this in https://github.com/cilium/cilium/pull/14478 -- https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/3137/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

**Comment by ungureanuvladvictor** [comment]
Happened again in https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/3145/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/ for the same PR as ^^.

**Comment by jrajahalme** [comment]
Still happening: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/3176/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/
