### ISSUE TITLE
docs: readme BPF graphic says tc ingress twice

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#1413]
Should be "tc ingress -> network stack -> tc egress".

**Comment by nebril** [comment]
Is this fixed? I can't find where is this located.

**Comment by aalemayhu** [comment]
@nebril I think Daniel is referring to the [bpf-overview.png](https://github.com/cilium/cilium/raw/master/Documentation/images/bpf-overview.png) in the README file. If you look at the green boxes titled `netdevice` you should see `TC Ingress` beside. One of them should instead say `TC Egress`.

**Comment by nebril** [comment]
Thanks, I was grepping through the repo and thinking about what I was missing :D
