### ISSUE TITLE
With kubeproxyreplacement, cannot access externalServiceIP if client and host shares a node

### ISSUE THREAD

**Issue by gpl** [cilium/cilium#14136]
## Bug report

( only on v4.  This behaviour does not appear on v6 )

When a service pod and the client share a host, be it a pod on the host or the host itself, connecting to the external service IP does not work.  We test this via `curl <externalServiceIP>`

We observe no drops. From `cilium monitor | grep <externalServiceIP>

-> stack flow 0x2f70556c identity 59185->2 state new ifindex 0 orig-ip 0.0.0.0: 10.192.11.9:44756 -> <externalServiceIP>:80 tcp SYN
-> stack flow 0xdca12cce identity 59185->2 state new ifindex 0 orig-ip 0.0.0.0: 10.192.11.9:44782 -> <externalServiceIP>:80 tcp SYN

**General Information**

- Cilium version (run `cilium version`)
1.9.0

- Kernel version (run `uname -a`)
Linux 5.8.14-050814-generic #202010070730 SMP Wed Oct 7 07:35:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
kubeadm

- Link to relevant artifacts (policies, deployments scripts, ...)
Here's a link to a file that contains a deployment and a service:

https://gist.github.com/gpl/73a83edc8f0e4a8fbbc333ca0a92ec15

**How to reproduce the issue**

1. Bootstrap a new cluster with cilium, DSR, maglev, and kubeproxyreplacement 
2. Create a deployment and a service pointing at that deployment 
3. Find the host running an instance of the deplyoment
4. From the same host, or a pod on the host, attempt to `curl <externalServiceIP>`

**Comment by brb** [comment]
@gpl externalIP service translation from inside a cluster is not allowed if externaIP does not belong to the node. See for more details: https://twitter.com/ciliumproject/status/1337054087590899715.

**Comment by gpl** [comment]
@brb Could you clarify what "belongs to" means?  In the above cluster the externalIPs service should be on every host.

In either case, this would make it impossible to query apis from the host itself... is there any better way to allow this?

**Comment by brb** [comment]
> Could you clarify what "belongs to" means? In the above cluster the externalIPs service should be on every host.

This is a corner case when externalIP = nodeIP, so this is accessible only from a single node with the nodeIP.

> In either case, this would make it impossible to query in-cluster apis or resources from the host itself... is there any better way to allow this?

DNS + ClusterIP?

**Comment by gpl** [comment]
> This is a corner case when externalIP = nodeIP, so this is accessible only from a single node with the nodeIP.
Sorry, I'm not quite clear on what this means.  In this case, I don't believe the nodeIP and externalIP are equal?  Unless I'm misunderstanding the concepts here.

We have the following nodes with their respective nodeIPs:
k8s-1: 20.0.0.1
k8s-2: 20.0.0.2
k8s-3: 20.0.0.3 

We also have an ingress/envoy instance on every host.  In this instance, it's 40.0.0.1.  When we query that ip from the hosts themselves, some hosts are successful, others are not.  When we do this on IPv6, we have no connectivity issues at all.  The behavior from v6 and v4 don't seem to mirror each other, and the behaviour on v4 seems pretty inconsistent.  

I was under the impression that https://docs.cilium.io/en/v1.9/gettingstarted/host-services/ would allow the behavior above, is that no longer the case?

The DNS + internal cluster IP solution doesn't work for us unfortunately due to some design and corp constraints.

**Comment by gpl** [comment]
> This is a corner case when externalIP = nodeIP, so this is accessible only from a single node with the nodeIP.

@brb I believe this is the opposite of what is happening.  In our case, if we have service x pointing to pod y on host k8s-1, k8s-1 cannot reliably access k8s-1 its service x on v4, but it goes through sometimes.  Both k8s-2 and k8s-3 are able to access the service reliably.  Additionally, on any node, accessing a v6 external ip seems to work all the time.

Is the intended behavior is to never allow the host network ns to access an externalIP, even with hostServices enabled?  Could there be a cilium option or some flag to allow the behavior instead?

**Comment by brb** [comment]
> I believe this is the opposite of what is happening. In our case, if we have service x pointing to pod y on host k8s-1, k8s-1 cannot reliably access k8s-1 its service x on v4, but it goes through sometimes. Both k8s-2 and k8s-3 are able to access the service reliably.

What happens here is that the socket lb (aka host-reachable svc) bypasses the translation for the service x on all hosts (the MITM mitigation), so the request with dst = externalIP is sent out from the hosts. In the case of k8s-{2,3}, the request is routed to the k8s-1 which is properly handled by the NodePort BPF program (aka N-S LB). While in the case of k8s-1, the request is sent back to the same host from which is originated, so it should get dropped (either it loops until TTL becomes 0) or depending on rp_filter setting it might be immediately dropped.

> Additionally, on any node, accessing a v6 external ip seems to work all the time.

Even from k8s-1 to which traffic for service x is routed?

> Is the intended behavior is to never allow the host network ns to access an externalIP, even with hostServices enabled? 

Yes, due to the MITM mentioned above.

> Could there be a cilium option or some flag to allow the behavior instead?

We would consider accepting such flag. Would you be interested in contributing?

**Comment by gpl** [comment]
Sorry for the extremely late reply, I got very busy suddenly and seem to have missed it, apologies.

> Even from k8s-1 to which traffic for service x is routed?

Yes, I believe so.  

We are definitely interested in contributing this feature, I'll try to see if we can get something put together this week.

**Comment by brb** [comment]
> We are definitely interested in contributing this feature, I'll try to see if we can get something put together this week. Is this feature something that we can still try to upstream?

Yes.

**Comment by gpl** [comment]
I still am trying to learn how to get this flag working, however -- if anyone else runs into this issue & has integrations to install service prefixes into your network, I've disabled host reachable services to regain accessibility for those endpoints.
