### ISSUE TITLE
IPcache BPF map may become full on Linux 4.11 to 4.15 if no kvstore is configured

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14147]
This line of code triggers garbage collection of the BPF ipcache map on kernel versions 4.11 to 4.15 inclusive:

https://github.com/cilium/cilium/blob/5a089ae1dbcc275efa77a0f2b4cba4b8d1ce7263/pkg/ipcache/kvstore.go#L271
->
https://github.com/cilium/cilium/blob/5a089ae1dbcc275efa77a0f2b4cba4b8d1ce7263/pkg/datapath/ipcache/listener.go#L345
->
https://github.com/cilium/cilium/blob/5a089ae1dbcc275efa77a0f2b4cba4b8d1ce7263/pkg/datapath/ipcache/listener.go#L255-L261

However, this code is not triggered if the KVStore mode is set to `""` (the default, implying CRD mode).

By inspection it seems to only be triggered based on the kvstore client:

https://github.com/cilium/cilium/blob/5a089ae1dbcc275efa77a0f2b4cba4b8d1ce7263/pkg/ipcache/kvstore.go#L377

Which presumably can only have clients registered from within the same package...?

https://github.com/cilium/cilium/blob/5a089ae1dbcc275efa77a0f2b4cba4b8d1ce7263/pkg/kvstore/backend.go#L107

So I tried this patch with a default install of Cilium (master, v1.10 dev cycle):

```
diff --git a/pkg/ipcache/kvstore.go b/pkg/ipcache/kvstore.go
index 20670cc7789d..7ba7a9c7a6f9 100644
--- a/pkg/ipcache/kvstore.go
+++ b/pkg/ipcache/kvstore.go
@@ -266,6 +266,7 @@ restart:
                        //   the deletion event.
                        switch event.Typ {
                        case kvstore.EventTypeListDone:
+                               log.Warn("Finished listing initial identities")
                                IPIdentityCache.Lock()
                                for _, listener := range IPIdentityCache.listeners {
                                        listener.OnIPIdentityCacheGC()
```

I could not find the warning in my Cilium logs. By this it appears to me that this garbage collection logic is not occurring in non-kvstore environments.

Found by inspection (that is, as far as I'm aware no users have explicitly reported an issue related to this).

**Comment by aanm** [comment]
Since we dropped support for kernel < 4.19 I think we can close this GH issue. @joestringer please re-open if you think otherwise.
