### ISSUE TITLE
CI: IPSec tests are skipped when running with our kube-proxy replacement

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14155]
https://github.com/cilium/cilium/pull/13241#issuecomment-696523262

> By the way, I noticed the IPSec tests are skipped when running with our kube-proxy replacement. Why is that? I think that's why we missed this regression, because we only run with newer kernels in CI builds where we also run without kube-proxy.

@jrfastab are you aware of this?

**Comment by brb** [comment]
It's because NodePort BPF cannot be used together with IPSec, see https://github.com/cilium/cilium/pull/12985.

**Comment by pchaigno** [comment]
Could we switch one of our 4.19 or net-next CI pipelines to run *with* kube-proxy? That would allow us to (1) run tests that are incompatible with our kube-proxy replacement on newer kernels and (2) have tests for Cilium's kube-proxy replacement when kube-proxy is also present on the node.

**Comment by brb** [comment]
@pchaigno SGTM. Also, this would help to test what new deployments with default settings on newer kernels are running  (kpr=probe + kube-proxy). I'd nominate 4.19 for it.
