### ISSUE TITLE
Agent should delete owned CEPs if no local endpoint exists for it

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#14184]
When the Cilium agent is reinstalled on a node after the old installation has been removed with `cleanState`, it can happen that CEPs exist for that node, without the endpoints actually being managed by Cilium (this was discovered in https://github.com/cilium/cilium/issues/13833#issuecomment-733809602).

The sequence of events in order to reproduce this:

1. Uninstall Cilium and delete any BPF state with the `cleanState` Helm setting. Any pods managed by Cilium will remain running.
2. Reinstall agent and operator. The operator CEP GC _will retain_ the CEPs for the pods managed in the previous installation, because the pods are still running.
3. The newly started agent however _will not restore_ any endpoints for these previously running pods, because there is no BPF state to restore endpoints from. 

Therefore we end up in a situation where we have CEPs for endpoints which are not actually currently managed by Cilium.

As discussed with @aanm, the K8s watcher inside the Cilium agent should remove CEPs which are assigned to it (I think this can be done by looking at the node ip?) but for which it does not have any local endpoint. This needs to be done after endpoint restoration from BPF state has completed, to ensure that CEPs are not deleted prematurely.

**Comment by joestringer** [comment]
Given the age of this issue I'm guessing it's no longer relevant?
