### ISSUE TITLE
Add Cilium API for adding / removing node to trigger arping in lb-only mode

### ISSUE THREAD

**Issue by brb** [cilium/cilium#14203]
When running in the `lb-only` mode (i.e. no connection to kube-apiserver) we need to send arping to nodes which run service endpoints to populate neighbor table with `nexthop IP addr => nexthop MAC addr` mappings. Otherwise, the datapath might not be able to forward packets to such nodes (aka `DROP_NO_FIB`).

Therefore, we need to extend Cilium API to support node registration / removal which would trigger https://github.com/cilium/cilium/blob/v1.9.0/pkg/datapath/linux/node.go#L564 / https://github.com/cilium/cilium/blob/v1.9.0/pkg/datapath/linux/node.go#L613. At this point, it's probably fine to assume that the user of the API would re-register nodes each time cilium-agent restarts, so that no persistent storage is required to store nodes (also, see https://github.com/cilium/cilium/pull/14201 for the case when the same nexthop can be used by multiple remote nodes).

An alternative approach would be to trigger arping when adding a new backend to a service, but that would require calling netlink to get a nexthop IP addr ("ip route get $BACKEND_IP") which would slow down the service update.

**Comment by christarazi** [comment]
Closing as the PR for this issue was closed.
