### ISSUE TITLE
Mark Cilium etcd operator as deprecated

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#14205]
It's still mentioned in
https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-etcd-operator/
and
https://docs.cilium.io/en/v1.9/gettingstarted/clustermesh/#gs-clustermesh

etcd-operator is replaced with with CRD-only mode and with the newly introduced cluster API.

**Comment by pchaigno** [comment]
@aanm Should we add a warning in the documentation stating it's deprecated for now, or should we just remove all documentation on etcd-operator?

**Comment by aanm** [comment]
@pchaigno we can remove all documentation regarding cilium-etcd-operator but we can only do it once we have clustermesh-apiserver documentation

**Comment by joestringer** [comment]
We will also need to think about migration.

**Comment by johngmyers** [comment]
Is external etcd (https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-external-etcd/) still supported or also to be deprecated? With either or both identity allocation modes?

**Comment by joestringer** [comment]
From Cilium community meeting:

Mark etcd-operator as deprecated for v1.10, but do not remove the underlying infrastructure yet. This will allow users to find out about the deprecation and plan for its removal.
