### ISSUE TITLE
add api to get service by l3n4addr

### ISSUE THREAD

**Issue by roodkcab** [cilium/cilium#14225]
## Proposal

**tcp connections got disconnect when service updated**

When rolling update a replicaset, long connection like grpc got disconnect because of service backend ip changed to newly created pod.

if cilium could offer an api like /service/{addr}/{scope} to get backend ip by l3n4addr, then services could easily do load balance by themselves. where addr is {tcp/udp}://{ip}:{port}, thus connection could avoid being corrupted by service update, and choose time to close such outdated connection.

For now we have only two apis, i.e. /service and /service/{id}. I have to to use /service to get all of them, then create a hashmap between service dsn and id, which is quite slow when number of services getting bigger and bigger.

**Comment by aanm** [comment]
You can get the list of backends with `kubectl get endpoints`, wouldn't that work?

**Comment by roodkcab** [comment]
yes, it does work. but how about use cilium as local cache for api-server on each node?

**Comment by aanm** [comment]
I think a better solution will exist once https://github.com/cilium/cilium/issues/10217 is fixed.

**Comment by roodkcab** [comment]
I can't agree more.
