### ISSUE TITLE
non-masquerade CIDRs can't be modified by the ip-masq-agent configmap

### ISSUE THREAD

**Issue by liweilun1** [cilium/cilium#14227]
helm install cilium cilium/cilium --namespace kube-system      --set nodeinit.restartPods=true  --set tunnel=disabled  --set bpfMasquerade=true  --set autoDirectNodeRoutes=true  --set localRedirectPolicy=true  --set enableK8sEndpointSlice=true  --set wellKnownIdentities.enabled=true  --set bpf.clockProbe=true  --set bpf.waitForMount=true  --set bpf.preallocateMaps=true  --set sockops.enabled=true  --set ipMasqAgent.enabled=true  --set nativeRoutingCIDR=192.168.0.100/30  --set nodePort.directRoutingDevice=em1  --set endpointRoutes.enabled=true  --set enable-node-port=true  --set hostServices.enabled=true  --set nodePort.enabled=true  --set hostPort.enabled=true  --set kubeProxyReplacement=strict  --set loadBalancer.mode=dsr  --set k8sServiceHost=192.168.0.100  --set k8sServicePort=6443

after i install cilium:v1.9.0 by helm，i create the configmap ip-masq-agent to the kube-system namespace

![image](https://user-images.githubusercontent.com/61909393/100721378-36d98e00-33fa-11eb-894a-b80f72057852.png)

![image](https://user-images.githubusercontent.com/61909393/100721242-0bef3a00-33fa-11eb-9669-bf5eba890158.png)

i saw the official document said that
# Wait ~60s until the ConfigMap is mounted into a cilium pod

![image](https://user-images.githubusercontent.com/61909393/100721178-f8dc6a00-33f9-11eb-9f92-f8115feb5d37.png)

but after 60s i check the ipmasq list is this , however.
Does the configmap can't modify the  non-masquerade CIDRs , or it is a bug?

**Comment by brb** [comment]
@renzhendev Thanks for the issue. Could you exec into cilium-agent pod and run `cat /etc/config/ip-masq-agent`?

**Comment by renzhendev** [comment]
> @renzhendev Thanks for the issue. Could you exec into cilium-agent pod and run `cat /etc/config/ip-masq-agent`?

when i run the command ,  the file dosen't exist   
![image](https://user-images.githubusercontent.com/61909393/100871227-e1c17900-34da-11eb-9904-7f8a8c9845bf.png)

when i check the dir , it doesn't show any files yet
![image](https://user-images.githubusercontent.com/61909393/100872107-44674480-34dc-11eb-896a-2bbf8ce0cf64.png)

![image](https://user-images.githubusercontent.com/61909393/100872121-4af5bc00-34dc-11eb-9785-f69a94b950cd.png)

**Comment by brb** [comment]
Can you try to create the configmap before installing Cilium?

**Comment by renzhendev** [comment]
> Can you try to create the configmap before installing Cilium?

i try the both way, create the configmap before installing Cilium and create the configmap after installing Cilium. it doesn't has any difference,however

**Comment by brb** [comment]
I've just tried the following and it worked:
```
$ mkdir agent-config
$ cat <<EOT >> agent-config/config
nonMasqueradeCIDRs:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
masqLinkLocal: false
EOF
$ kubectl create configmap ip-masq-agent --from-file=agent-config --namespace=kube-system
$ helm install <... same params as you provided>
$ cilium bpf ipmasq list
IP PREFIX/ADDRESS
10.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
$ kubectl -n kube-system edit configmap ip-masq-agent
... change 192 to 11
# Wait a bit
$ cilium bpf ipmasq list
IP PREFIX/ADDRESS
11.168.0.0/16
169.254.0.0/16
172.16.0.0/12
10.0.0.0/8
```
