### ISSUE TITLE
Complexity issue in bpf_lxc with kubeproxy-free + partial hostReachableServices (tcp or udp only)

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#14234]
It seems like enabling service lookup in bpf_lxc in kubeproxy-free mode pushes bpf_lxc over the complexity limit for CI on net-next kernel.

Symptom:

```
2020-11-24T05:08:11.714524346Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc83a2dc5fcb04 ingress prio 1 handle 1 bpf da obj 2607_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2020-11-24T05:08:11.714577225Z level=warning subsys=datapath-loader
2020-11-24T05:08:11.714584865Z level=warning msg="Prog section '2/7' rejected: Argument list too long (7)!" subsys=datapath-loader
2020-11-24T05:08:11.714588516Z level=warning msg=" - Type:         3" subsys=datapath-loader
2020-11-24T05:08:11.714591174Z level=warning msg=" - Attach Type:  0" subsys=datapath-loader
2020-11-24T05:08:11.714686976Z level=warning msg=" - Instructions: 3530 (0 over limit)" subsys=datapath-loader
2020-11-24T05:08:11.714695182Z level=warning msg=" - License:      GPL" subsys=datapath-loader
```

Reproduce steps:
See https://github.com/cilium/cilium/pull/13882#discussion_r529793208

This is blocking PR #13882

**Comment by Weil0ng** [comment]
cc @pchaigno @joestringer @borkmann

**Comment by pchaigno** [comment]
> pushes bpf_lxc over the complexity limit for 4.19 kernel.

@Weil0ng The initial Slack thread on this issue mentions a CI test running on our net-next kernel and I reproduced on the net-next VM (roughly same kernel version as in our tests). Did you also notice this issue in our 4.19 CI?

Also, you mentioned before that you couldn't reproduce on a 5.4 COS. Did you verify that you were using the same configuration as in the failing test (i.e., kubeproxy-free + partial hostReachableServices + IPv6 enabled)?

**Comment by Weil0ng** [comment]
@pchaigno I didn't try on 4.19, I thought you meant 4.19 when you said dev VM in the comment but I guess I misunderstood, edited the issue to reflect this.

Yes, trying with kubeproxy-free + partial hostReachableServices + IPv6 is still in my todo list (sorry was out sick last few days), will update here when I confirm (FWIW, the working setup is kubeproxy-free + bpf-lb-sock-hostns-only, which is effectively partial hostReachableServices for bpf_lxc).

**Comment by Weil0ng** [comment]
It turns out that my local env I cannot bring up ipv6 clusters/nodes at all...so I cannot try with IPv6 on 5.4, now I'm trying to see if the working config (without ipv6) would work on net-next kernel.

**Comment by Weil0ng** [comment]
Finally managed to replicate net-next kernel locally, I tried the working setup (kubeproxy-free + partial hostReachableServices + ipv4) and it seems to be working just fine.

But I think @pchaigno you did manage to reproduce the issue using same setup on net-next in CI? I'm a bit confused though why this would fail on next kernel, doesn't net-next kernel have the higher inst limit (1M)?

**Comment by pchaigno** [comment]
> Finally managed to replicate net-next kernel locally, I tried the working setup (kubeproxy-free + partial hostReachableServices + ipv4) and it seems to be working just fine.

Did you try with IPv6 enabled? I think that's the configuration in which the issue was happening, right?

> you did manage to reproduce the issue using same setup on net-next in CI?

Yes, net-next kernel, but it was with the development VM.

> I'm a bit confused though why this would fail on next kernel, doesn't net-next kernel have the higher inst limit (1M)?

We are going above the 1M instructions limit.

**Comment by Weil0ng** [comment]
It's gonna take some additional effort for me to run ipv6 in my env, I'll try but might take some time...

But yet at least we know without IPv6, we are good, so is there a big difference in terms of logic between ipv4/6 in bpf_lxc?

**Comment by Weil0ng** [comment]
based on https://github.com/cilium/cilium/pull/13882#discussion_r529793208, it seems like you also did not turn on ipv6 and it failed too? @pchaigno

**Comment by pchaigno** [comment]
We have a new test for complexity which should make it easier to reproduce and iterate on this regression. You can remove this line from `bpf/Makefile`:
https://github.com/cilium/cilium/blob/08a14ad0ce3f78ff0af3c094a1e56951e827f091/bpf/Makefile#L92
then run the following commands on a kernel 5.3+:
```
make -C bpf KERNEL=netnext
./test/bpf/verifier-test.sh
```
[K8sVerifier](https://github.com/cilium/cilium/blob/master/test/k8sT/Verifier.go) essentially automates these steps to run in our CI.

**Comment by pchaigno** [comment]
This was fixed in https://github.com/cilium/cilium/pull/16084.
