### ISSUE TITLE
cilium: endpoint routes + veth fast redirect support

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#14240]
Both settings should work with fast redirect for 5.10+.

**Comment by lyveng** [comment]
@borkmann Is the PR #14382 related to this issue?

**Comment by pchaigno** [comment]
@lyveng It is, and it handles the endpoint routes case.

**Comment by borkmann** [comment]
> @borkmann Is the PR #14382 related to this issue?

Yeah, still needs more work though since policy case does not fully function there yet. Will resume in Jan.

**Comment by m-yosefpor** [comment]
any updates on this?

**Comment by borkmann** [comment]
> any updates on this?

PR for testing is here: https://github.com/cilium/cilium/issues/14240

**Comment by borkmann** [comment]
> When is this going to be upstreamed? I anticipated `1.13.2` but it looks like it's still not here.

Hi @buroa, it has been merged into Cilium OSS master branch ~2 weeks ago, so it can be tested via images built from master (https://github.com/cilium/cilium#development) and next v1.14.0-snapshot.2 once the latter is out.
