### ISSUE TITLE
Uneven traffic distribution after container / pod restarts

### ISSUE THREAD

**Issue by nicktrav** [cilium/cilium#14250]
When running with Cilium as the CNI, I'm observing an uneven distribution of traffic to an identical set of Pods in a Deployment.

After restarting a single Pod in the Deployment after seeing steady state traffic, the new Pod receives fewer requests than the other two pods:

![Screenshot from 2020-12-02 15-53-35](https://user-images.githubusercontent.com/804457/100946605-9bf3b900-34b8-11eb-941a-39ed2cf51ff2.png)

The load test tool ([vegeta](https://github.com/tsenart/vegeta)) is set up to create a new connection per request (`-keepalive=false`).

Compare this to a cluster not running Cilium, which is in line with how I would expect the traffic to be distributed:

![Screenshot from 2020-12-02 15-32-16](https://user-images.githubusercontent.com/804457/100946616-a01fd680-34b8-11eb-850a-83a4182340c3.png)

The above is when running without any network policies, but I also see the same issue when using an L7 CNP in the backend namespace.

**General Information**

- Cilium version (run `cilium version`)

```shelll
$ kubectl -n kube-system exec ds/cilium -- cilium version
Client: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
Daemon: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
```

- Kernel version (run `uname -a`)

```shell
$ uname -a
Linux nickt 5.8.0-29-generic #31-Ubuntu SMP Fri Nov 6 12:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Installed with the following:

```shell
helm upgrade cilium cilium/cilium \
  --install \
  --version "$_version" \
  --namespace kube-system \
  --set nodeinit.enabled=true \
  --set kubeProxyReplacement=partial \
  --set hostServices.enabled=false \
  --set externalIPs.enabled=true \
  --set nodePort.enabled=true \
  --set hostPort.enabled=true \
  --set bpf.masquerade=false \
  --set image.pullPolicy=IfNotPresent \
  --set ipam.mode=kubernetes \
  --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http:sourceContext=pod;destinationContext=pod}" \
  --set hubble.listenAddress=":4244" \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
  --set prometheus.enabled=true \
  --set operator.prometheus.enabled=true \
  --set debug.enabled=true
```

**How to reproduce the issue**

I've put together a reproducer here:

https://github.com/nicktrav/cilium-debugging/tree/nickt.debugging

Note there's some extra, unused, stuff in that repo (CNPs, custom metrics, etc.), but it should still show the issue.

**Comment by aditighag** [comment]
>Load should initially be evenly distributed across all three backend Pods.

Does the load generator create a Kubernetes service backed by the backend pods, and send the requests to the clusterIP, or directly to the pod IPs?

**Comment by nicktrav** [comment]
> Does the load generator create a Kubernetes service backed by the backend pods, and send the requests to the clusterIP, or directly to the pod IPs?

The load test is calling the service by DNS name ([`backend-1.backend` in my demo](https://github.com/nicktrav/cilium-debugging/blob/nickt.debugging/manifests/load-test/templates/load-test-1-configmap.yaml#L7)), so I assume it's using the ClusterIP for the Service after it's resolved. I'm still feeling my way around Cilium, so I'm not sure if there's some hijacking that goes on w.r.t. DNS.

But tldr, not doing anything fancy, just calling the K8s svc.

> Also, do you see uneven load on pod addition too, or just removal?

Good question. I hadn't tested that before now, but it looks like it has the same issue (I restarted the load test with three pods @ `:38` and added a pod to the Deployment `--scale=4` @ `:41`):

![Screenshot from 2020-12-02 16-44-30](https://user-images.githubusercontent.com/804457/100948969-eaf01d00-34bd-11eb-8725-26e7445fff5a.png)

**Comment by aditighag** [comment]
> --set kubeProxyReplacement=partial \
  --set hostServices.enabled=false \
  --set externalIPs.enabled=true \
  --set nodePort.enabled=true \
  --set hostPort.enabled=true \

Looking at the kernel version along with these helm options, cilium _should_ completely replace kube-proxy functionality. Could you attach sysdump from your cluster?

**Comment by aditighag** [comment]
Based on the helm options and kernel version, assuming cilium has completely replaced kube-proxy, the backend selection logic in cilium is different for TCP and UDP traffic. I'm not sure the logic for TCP traffic that randomly selects a backend will exactly guarantee an even distribution of load, though. Regardless, it'll be good to understand this better. 

Could you please repeat the experiment for following 2 different cases, and report the findings - 

1) Make the load generator send requests directly to the clusterIP (and not service fqdn)
2) Switch to UDP (or TCP)

**Comment by nicktrav** [comment]
> Make the load generator send requests directly to the clusterIP (and not service fqdn)

This didn't seem to make much difference unfortunately:

![Screenshot from 2020-12-02 21-43-19](https://user-images.githubusercontent.com/804457/100969216-99f51e80-34e7-11eb-8d54-2997e4070976.png)

> Switch to UDP (or TCP)

Can you clarify this point? The workload is inherently TCP-based (HTTP/1.1/ client and h/2 server). Are you suggesting trying a completely different, UDP-based workload?

> Could you attach sysdump from your cluster

I'll follow up on this.

**Comment by brb** [comment]
@nicktrav You are hitting the same issue as described in https://github.com/cilium/cilium/issues/10343. Enabling the socket-based loadbalancing (`--set hostServices.enabled=true`) should resolve the issue.

**Comment by nicktrav** [comment]
Yep - looks like that did it.

![Screenshot from 2020-12-03 08-58-13](https://user-images.githubusercontent.com/804457/101061788-bcb62000-3545-11eb-925e-ea20f4f90c2d.png)

Just to summarize my understanding of the problem when host services are _not_ enabled:
- load generator quickly chews through ephemeral port range due to the new connection per request type of load
- source port mappings aren't GC'd from conntrack fast enough so new connections that use existing entries from the conntrack table are sent to the existing pods

Lowering the conntrack TCP timeout from the default of 6 hours to 1 minute and forcing the GC interval to be 1 minute also fixed the problem. I assume if I'd waited 6 hours, I would have seen the connections re-balance.

Some thoughts / suggestions in closing:

- advertising `hostServices.enabled=true` as the default in the getting started guides - possibly a little controversial if the assumption is that folks are coming from older kernel versions, but not sure what the tolerance is here?
- adding a section to the troubleshooting guides for how to handle connection imbalance issues
- allowing `--bpf-ct-timeout-service-tcp` to be set via Helm
- closing out #10343

Happy to close this out and take on any of the above.

**Comment by brb** [comment]
Thanks for the detailed summary.

> Just to summarize my understanding of the problem when host services are not enabled:

Yes, your understanding is correct.

> Lowering the conntrack TCP timeout from the default of 6 hours to 1 minute and forcing the GC interval to be 1 minute also fixed the problem. I assume if I'd waited 6 hours, I would have seen the connections re-balance.

Yes. Just keep in mind that with 1min interval you are trading CPU cycles for more even distribution. Also, if you have long-lived connections sending packets less frequent than 1min, then such connections will be disrupted.

> advertising hostServices.enabled=true as the default in the getting started guides - possibly a little controversial if the assumption is that folks are coming from older kernel versions, but not sure what the tolerance is here?

This is already a default via `kube-proxy-replacement: probe` setting which checks whether the feature can be enabled, and if so, it will enable it.

> adding a section to the troubleshooting guides for how to handle connection imbalance issues

Mind creating a PR for it? This page might be a proper place: https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/.

> allowing --bpf-ct-timeout-service-tcp to be set via Helm

Also, you could create a PR for it.

> closing out #10343

There was some WIP for it https://github.com/cilium/cilium/compare/pr/gc-on-svc-update by @borkmann to resolve the issue.

**Comment by brb** [comment]
> allowing --bpf-ct-timeout-service-tcp to be set via Helm

One more thought regarding this - I expect this will be modified only in rare occasions, so maybe it can be set via extraConfig (https://github.com/cilium/cilium/pull/14077) w/o introducing a new Helm var? /cc @aanm @joestringer

**Comment by nicktrav** [comment]
> maybe it can be set via extraConfig (#14077) w/o introducing a new Helm var?

Nice. TIL. That seems much better than adding additional config to the Helm templates.

I'll put up a PR for the docs change.

Thanks! Closing.
