### ISSUE TITLE
Add an Istio test to verify poxy redirection

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#14285]
We need to extend test coverage for scenarios such as - https://github.com/cilium/cilium/pull/14271, where proxy redirection can break. 

@jrajahalme : "The test scenario is that there are two incoming TCP connections for an Istio POD destination, both with the same source address and port. The second one would get misclassified as HOST due to SNAT using the destination host address (not sure if loopback, though). Allowed traffic could be dropped, and at worst denied traffic could be allowed since we allow everything from HOST!"

**Comment by jrajahalme** [comment]
The destination port has to be different, otherwise the the 5-tuples would collide already at the source. The point is that iptables REDIRECT changes the destination port to a specific value, necessitating SNAT to keep 5-tuples distinct.
