### ISSUE TITLE
Mark cilium pod as CriticalPod in the DaemonSet

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1428]
@michi-covalent experienced the cilium pod getting evicted away due to nodefs pressure. We should mark the pod as critical (the requirement for it is to run in the `kube-system` namespace) as cilium is required for the operating of all other pods on the node.

k8s Documentation:
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
Marking add-on as critical
To be critical an add-on has to run in kube-system namespace (configurable via flag) and * have the scheduler.alpha.kubernetes.io/critical-pod annotation set to empty string, and * have the PodSpec’s tolerations field set to [{"key":"CriticalAddonsOnly", "operator":"Exists"}]
The first one marks a pod a critical. The second one is required by Rescheduler algorithm.

**Comment by manalibhutiyani** [comment]
Just to be clear, we are talking about changes in the `examples/kubernetes/cilium.yaml` in the cilium repo, correct. @michi-covalent
