### ISSUE TITLE
Empty kubelet logs 

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#14293]
The logs from this test run does not contain kubelet logs. https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.9/49/testReport/junit/Suite-k8s-1/20/K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts/

**Comment by nebril** [comment]
Uploading for posterity [08578d56_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip](https://github.com/cilium/cilium/files/5653706/08578d56_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip)
