### ISSUE TITLE
Cilium klog conflicts with other crd operators

### ISSUE THREAD

**Issue by fafucoder** [cilium/cilium#14317]
## Bug report

**General Information**

- v1.8.3
- Linux node1 5.8.10-1.el7.elrepo.x86_64 #1 SMP Thu Sep 17 10:40:48 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- kubernetes v1.18.5

**How to reproduce the issue**
When other crd operators are used together with cilium api, there will be a problem of duplication of log_dir definition

![image](https://user-images.githubusercontent.com/16442491/101565442-03a18b00-3a08-11eb-86b9-87485e28d4cf.png)

Because the init func did not initialize the klog FlagSet, but default is flag.CommandLine

![image](https://user-images.githubusercontent.com/16442491/101564337-ecfa3480-3a05-11eb-8255-beca69e42a92.png)

**Comment by aanm** [comment]
Thanks for opening this GitHub issue. Do you want to try and submit a Pull Request to fix it?

**Comment by fafucoder** [comment]
@aanm Thanks for reply. I'd like to fix it
