### ISSUE TITLE
Identify misbehaving applications that do not respect DNS TTL

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#14320]
A user report of a bug came from apps not respecting the DNS TTL which led to the following fix: https://github.com/cilium/cilium/pull/13914. This fix is an example of Cilium doing a best-effort attempt to keep connectivity for these apps. To improve troubleshooting, it can be helpful to identify when applications are misbehaving, so that the appropriate steps can be taken. A log msg can be sufficient as an indication.

**Comment by youssefazrak** [comment]
@christarazi I will take care of this one. Might need some help ;)

**Comment by youssefazrak** [comment]
@christarazi I started looking at this one. I have some questions though as I'm trying to understand how this DNS proxy works:
- What do you mean exactly by "applications are misbehaving"? Not respecting the DNS TTL and re-doing a DNS lookup?

- If my above assumption is correct, we consider the scenario of PR #13914 and that would give us two possible scenarios of "misbehaving":

1. DNS TTL is expired but IP1 is still alive (didn't change). No disconnection or whatsoever and the traffic is still flowing to this same IP1.  In this case, we would need to check if the traffic from the app is still going to this IP1 and issue a warning. Or maybe another way as the DNS proxy is handling only DNS traffic? 
2. DNS TTL is expired and we have switched to IP2 (or IPx, where x is >= 2), and in this case, we also issue a warning.  

Also, one generic questions regarding the DNS proxy as documentation is not clear: 
- Does it intercept the traffic going to the DNS forwarders/resolvers and cache the results, say for example, kube-dns traffic? Or it acts itself as a DNS forwarder/resolver (which doesn't seem to be the case)?

**Comment by christarazi** [comment]
> @christarazi I started looking at this one. I have some questions though as I'm trying to understand how this DNS proxy works:
> 
>     * What do you mean exactly by "applications are misbehaving"? Not respecting the DNS TTL and re-doing a DNS lookup?

Yes, not respecting the DNS TTL and continuing to use the IPs returned in the response.

>     * If my above assumption is correct, we consider the scenario of PR #13914 and that would give us two possible scenarios of "misbehaving":
> 
> 
>     1. DNS TTL is expired but IP1 is still alive (didn't change). No disconnection or whatsoever and the traffic is still flowing to this same IP1.  In this case, we would need to check if the traffic from the app is still going to this IP1 and issue a warning. Or maybe another way as the DNS proxy is handling only DNS traffic?

The DNS proxy only handles the DNS traffic.

>     2. DNS TTL is expired and we have switched to IP2 (or IPx, where x is >= 2), and in this case, we also issue a warning.

:+1: 

> Also, one generic questions regarding the DNS proxy as documentation is not clear:
> 
>     * Does it intercept the traffic going to the DNS forwarders/resolvers and cache the results, say for example, kube-dns traffic? Or it acts itself as a DNS forwarder/resolver (which doesn't seem to be the case)?

The former. It intercepts DNS requests and forwards them to the resolvers on behalf of the application. 

Apologies for the late reply, I hope it's still useful.
