### ISSUE TITLE
Add a mechanism in neighbor management to allow refreshing ARP cache

### ISSUE THREAD

**Issue by jaffcheng** [cilium/cilium#14322]
## Proposal / RFE

**Is your feature request related to a problem?**
In our case, the MAC address of the interface (which cilium does arping on) changes after rebooting the node, but cilium neighbor management doesn't detect the change, and ARP cache keeps the old MAC address, which makes node to node traffic fails. 
Furthermore, after handling gateway arping: https://github.com/cilium/cilium/pull/14201, the concern would be, if gateway MAC address changes for some reason, this may affect traffic to the networks via the gateway.

**Describe the solution you'd like**
Add a mechanism to refresh or make arp entries stale.

**Comment by jaffcheng** [comment]
Related PR: https://github.com/cilium/cilium/pull/14224

**Comment by brb** [comment]
@jaffcheng Thanks for opening the issue. The linked PR might be not applicable in your case as it is now, as it targets deployments in which Cilium runs as a stand-alone loadbalancer and does not have a connectivity to kube api-server, and calling the API might overwrite the fields.

**Comment by jaffcheng** [comment]
Got it, thanks for the clarification. We'll try recreating the corresponding k8s/cilium node after MAC address changes and see if it works around.

**Comment by brb** [comment]
A periodical arping could be a long term solution to the problem. Do you mind doing a PR for it?

**Comment by jaffcheng** [comment]
@brb Sure, I'll take this.

**Comment by jaffcheng** [comment]
Hi, @brb some of my thoughts on fixing this:
First of all, I think periodically sending arping to all neighbors(nodes/gws) should be able to fix this, if a neighbor changes its MAC address, the connectivity would be interrupted and recover after next arping cycle. Given that we cannot drive arp resolution in BPF program, I don't see a way to avoid this interruption. My concern with this approach is that it introduces many ARP broadcast requests (approximately node_num*node_num per cycle in a subnet).
Then I thought about inserting `NUD_REACHABLE` ARP entries for neighbors and periodically send gratuitous ARP request from nodes, this would reduce ARP broadcasts to approximately node_num per cycle, but if cilium-agent crashes, ARP entries may get GCed and BPF NodePort will start dropping packets to these neighbor IPs.
What do you think?

**Comment by brb** [comment]
> Then I thought about inserting NUD_REACHABLE ARP entries for neighbors and periodically send gratuitous ARP request from nodes

My main concern about gratuitous ARP requests is that they might get blocked by distros or routers due to easy to do spoofing. Do you have it enabled in your network?

**Comment by aditighag** [comment]
How often do we want these arp packets to be sent out? There can still be connectivity drop when a mac address change occurs in between two subsequent refresh pings. I wonder if we could listen for `fib_lookup` ARP failure events, and trigger an arp ping immediately?

**Comment by jaffcheng** [comment]
> > Then I thought about inserting NUD_REACHABLE ARP entries for neighbors and periodically send gratuitous ARP request from nodes
> 
> My main concern about gratuitous ARP requests is that they might get blocked by distros or routers due to easy to do spoofing. Do you have it enabled in your network?

You are right, I believe our network devices would accept unsolicited and gratuitous arp, but I checked our node configuration and it seems the default configuration would discard them.

**Comment by jaffcheng** [comment]
Hi @aditighag , I agree with your idea of making the behavior as close to kernel neighbor module as possible, this should reduce drops. Maybe we could notify on `DROP_NO_FIB`. @brb

**Comment by brb** [comment]
> Maybe we could notify on DROP_NO_FIB.

If we get notified about `DROP_NO_FIB`, then IMHO it's already too late. Heavy loaded nodes might drop a significant portion of a traffic. Just to remind, the case for which we introduced the arping is when an intermediate node needs to forward a NodePort/LoadBalancer/externalIP request to a destination node (IPSec has it's own use case though). Both nodes are managed by Cilium.

I'd suggest to solve this problem in two steps (and PRs):

1. Introduce a periodical arping. The period can be derived from `base_reachable_time_ms` (`base_reachable_time_ms` is 30s on my distro, so a neigh entry should stay in Linux neigh table as `NUD_REACHABLE`  for  `x` time, where AFAIK `30s/2 < x < 3*30s`). With such period, it should not spam too much.
2. If the spamming becomes an issue, then introduce an optimization which would allow the datapath to notify the control-plane about a seen packet from the destination node. This would update the arp entry timeout in the cilium-agent. We could notify the agent via a perf ring buffer (same as we currently do with the CT GC wakeups). However, this is only possible when we run in the SNAT mode (not in DSR), as we would update only when a reply to a LB request is sent via the intermediate node.

**Comment by jaffcheng** [comment]
Thanks for the detailed write-up! Will start working on the first step.
I would prefer keeping `NUD_PERMANENT` to make sure arp entries are never GCed even when cilium-agent is down.

Just to clarify, I think the main purpose of notifying the control-plane about `DROP_NO_FIB` is to eliminate drops between MAC address change and next arping, I'm not sure if this can be detected by seen packet from the destination node (This can be further discussed in next step).

**Comment by brb** [comment]
>  I would prefer keeping NUD_PERMANENT to make sure arp entries are never GCed even when cilium-agent is down.

:+1: 

> I think the main purpose of notifying the control-plane about DROP_NO_FIB is to eliminate drops between MAC address change and next arping

In the case of a stale permanent ARP entry, you won't see `DROP_NO_FIB`, as `bpf_fib_lookup()` will return the stale entry.
