### ISSUE TITLE
Pod startup liveness-probe hold-off

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#14342]
This gives the ability to hold off all the other probes until the pod has finished its startup. This affects only the Cilium pods, not workload pods. Implementing this would speed up for CI because it eliminates the initial delay.

See [KEP](https://github.com/kubernetes/enhancements/issues/950).
Se [K8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes).

**Comment by youssefazrak** [comment]
@christarazi I will take care of this one.
