### ISSUE TITLE
Implement BPF based masquerading for IPv6 traffic

### ISSUE THREAD

**Issue by fristonio** [cilium/cilium#14350]
Follow up from #14124

**Comment by pchaigno** [comment]
This item can be addressed by following the `ENABLE_MASQUERADE` in the datapath for the IPv4 masquerading implementation and implementing the same for the IPv6 paths. Then, some work is needed on the Go side to add a new flag and check that all `EnableBPFMasquerade` checks are appropriately extended. End-to-end tests would probably require very few changes on [the existing IPv6 masquerading test](https://github.com/cilium/cilium/blob/b3f03879f460011bd9f4b51d021933ab066393d3/test/k8sT/Services.go#L1881).

We should also watch (and test) for the interactions with host firewall. See `host_firewall.h` for details.
