### ISSUE TITLE
Cilium install Helm chart autogenerated readme has incorrect field descriptions

### ISSUE THREAD

**Issue by fristonio** [cilium/cilium#14369]
The README that is autogenerated for the Cilium helm chart contains incorrect descriptions for some of the values fields. This happens when there is a commented-out field the exists just before a value field.

* Description in the README

![image](https://user-images.githubusercontent.com/21292343/101836542-960a7180-3b63-11eb-8ec4-aef41e605ee5.png)

* `values.yaml` file

![image](https://user-images.githubusercontent.com/21292343/101836620-bb977b00-3b63-11eb-9e4b-8e6b0fc63584.png)

The required behavior is that a field description should not include content from a comment-out field in the `values.yaml` file.

**Comment by joestringer** [comment]
I have a thought how to address this by just uncommenting the defaults. The difficulty is how this affects the configuration of such values during upgrade of existing clusters.

To do this safely, we would need to ensure that the upgrade guide prioritizes the user's existing settings for these values, which I *think* might be possible now by requesting helm to fetch the "effective" values for all of the existing parameters.

**Comment by joestringer** [comment]
Other obvious path would be just to fix up the upstream tool we use to generate the README.

**Comment by pchaigno** [comment]
It shouldn't be too hard to fix this in the upstream tool we use, eventually under a flag.

We [use helm-docs](https://github.com/cilium/cilium/blob/fc6736955e9807ebe84e2bd74332a19f39a59f21/install/kubernetes/Makefile#L63-L65) to generate the README. The parsing for the description seems to happen in [`getDescriptionFromNode()`](https://github.com/norwoodj/helm-docs/blob/f7c7cff0c72ec588bfef4858d27a63d041654bdd/pkg/document/values.go#L122). I tried to update to v1.5.0 but it has the same issue.

**Comment by sayboras** [comment]
seems like this is addressed in https://github.com/norwoodj/helm-docs/pull/99 by Bruno

**Comment by ti-mo** [comment]
This has been fixed.
