### ISSUE TITLE
Spam "Cilium DaemonSet not ready yet" in test outputs

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14384]
If you looked at test outputs recently, you may have noticed that the output is spammed with:
```
STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
```

This is caused by https://github.com/cilium/cilium/commit/002bd9c37c4d56c12878da1ec24772f7c7369d97, which changed `WaitForCiliumReadiness` to use `gomega.Eventually` instead of `helpers.RepeatUntil`. The issue is that contrary to `RepeatUntil`, `Eventually` repeats the check continuously with only 10ms sleeps. That 10ms sleep is however configurable with a [third argument to `Eventually`](https://onsi.github.io/gomega/#eventually).

Why not send a PR instead of opening an issue? I'm unsure what the proper fix is.
- What is the value of printing this `Cilium DaemonSet not ready yet` message repeatedly?
- Do we really want longer sleeps if the goal is to minimize total CI runtime?

**Comment by joestringer** [comment]
IMO the only piece of information that multiple messages will provide is some timestamping on how long this step takes. In retrospect sometimes this is useful to know. Printing several times a second is not necessary for this, probably printing once every 5-10 seconds is probably sufficient. Arguably printing once and then relying on the next step to run and print the next step's timestamp would also provide the same information, though when looking back through it is less obvious when there is a long delay between two steps if there is just one message.

Running the actual command in this case every 10ms is probably a little on the aggressive side given how this step typically takes in the order of 10s.

**Comment by pchaigno** [comment]
Here is an extract from the test logs from yesterday:
```
17:56:38  17:56:38 STEP: Running AfterAll block for EntireTestsuite K8sServicesTest Checks service across nodes Tests IPv6 NodePort Services
17:56:41  17:56:41 STEP: Installing Cilium
17:56:43  17:56:42 STEP: Waiting for Cilium to become ready
17:56:43  17:56:42 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
[ ... x710 ... ]
17:57:29  17:57:29 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
17:57:29  17:57:29 STEP: Number of ready Cilium pods: 2
17:57:29  17:57:29 STEP: Validating if Kubernetes DNS is deployed
17:57:29  17:57:29 STEP: Checking if deployment is ready
```
> IMO the only piece of information that multiple messages will provide is some timestamping on how long this step takes. In retrospect sometimes this is useful to know.

All test steps are timestamped, so we can already figure out how long we waited for Cilium to be ready by checking the difference between `Waiting for Cilium to become ready` and `Number of ready Cilium pods`'s timestamps.

We've now reduced the frequency of these messages to once per second. AFACS, this is still ~45 such messages for every single Cilium installation.

> Running the actual command in this case every 10ms is probably a little on the aggressive side given how this step typically takes in the order of 10s.

But if we don't log anything while we're waiting, is there a downside to very short sleeps? We do these sleep-based waits in a LOT of places in our tests (in most cases with 5s sleeps). If we always take 5s to figure out we reached the expected state, it likely adds up to several minutes.
