### ISSUE TITLE
Investigate workaround in privileged tests for netlink.RuleAdd() returning EINVAL

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#14383]
See https://github.com/cilium/cilium/pull/14337#discussion_r541360235. For now the workaround is to shell out to `ip rule add` instead of using the netlink library.

**Comment by pchaigno** [comment]
For quicker, future reference: we'd like to replace the `tc` call with the following (or similar):
```go
c.Assert(netlink.RuleAdd(&netlink.Rule{
	Src:      &net.IPNet{IP: net.ParseIP("172.2.0.2"), Mask: net.CIDRMask(32, 32)},
	Priority: linux_defaults.RulePriorityEgress,
	Table:    dummy.Index,
}), IsNil)
```

**Comment by christarazi** [comment]
This can be useful to trace netlink requests to the kernel: https://github.com/socketpair/nltrace

**Comment by brb** [comment]
Alternatively, the recent enough strace version should help you to compare both netlink requests. If that doesn't work, then https://docs.pyroute2.org/debug.html might be useful.

**Comment by ti-mo** [comment]
@christarazi Turns out the default value of netlink.Rule cannot be used: https://github.com/cilium/cilium/pull/26486.
