### ISSUE TITLE
maglev: Improve agent scalability

### ISSUE THREAD

**Issue by brb** [cilium/cilium#14397]
This is an issue to track Maglev related scalability improvements for the agent:

- [x] Figure out all heavy hitters when running on ZH lab machines (@glibsm @christarazi,@brb)
- [x] Parallelize `maglev.getPermutations()`, as suggested by @christarazi (@christarazi,@brb)
- [ ] Use batch ops or mmap for Maglev lookup table updates (@brb)

**Comment by christarazi** [comment]
Golang 1.16 will improve memory usage reporting:

> On Linux, the runtime now defaults to releasing memory to the operating system promptly (using MADV_DONTNEED), rather than lazily when the operating system is under memory pressure (using MADV_FREE). This means process-level memory statistics like RSS will more accurately reflect the amount of physical memory being used by Go processes. Systems that are currently using GODEBUG=madvdontneed=1 to improve memory monitoring behavior no longer need to set this environment variable. 

Source: https://tip.golang.org/doc/go1.16

In the meantime, we can consider setting `GODEBUG=madvdontneed=1` when running our benchmarks / tests.

**Comment by christarazi** [comment]
Re: Parallelize maglev.getPermutations() (CPU bottleneck)

I started with a simple approach of splitting the perm slice in half and starting to concurrent goroutines to populate each half. However, it will not work because the algorithm seems to have a dependency on serial slice access (`perm`). This means that element N requires element N-1 to be populated in the slice and given, it isn't possible to parallelize the for-loop. This was validated by running the unit tests in the `maglev` package: `go test ./pkg/maglev`.

**Comment by brb** [comment]
Hmm, with a dummy parallelization (goroutine per backend) and changing the M in the benchmark function to 65521 I'm getting almost 4x improvement:

```
# BEFORE OPTIMIZATION
> go test -v -check.v -check.b -check.btime 5s -check.bmem
=== RUN   Test
PASS: maglev_test.go:61: MaglevTestSuite.BenchmarkGetMaglevTable              10         704485813 ns/op        524706310 B/op         9 allocs/op
OK: 1 passed
--- PASS: Test (7.78s)
PASS
ok      github.com/cilium/cilium/pkg/maglev     7.785s

# AFTER OPTIMIZATION
> go test -v -check.v -check.b -check.btime 5s -check.bmem
=== RUN   Test
PASS: maglev_test.go:61: MaglevTestSuite.BenchmarkGetMaglevTable              50         214803515 ns/op        524710663 B/op        20 allocs/op
OK: 1 passed
--- PASS: Test (10.93s)
```

Let me push the optimization after I've bound goroutines count to number of CPU cores.
