### ISSUE TITLE
doc: document that tcp:4244 needs to be open on the host to allow Relay to connect to peers

### ISSUE THREAD

**Issue by rolinh** [cilium/cilium#14402]
Hubble Relay will fail to connect to peers if a host firewall is blocking `tcp:4244`. The documentation should contain a heads-up/note about this so that users using a host firewall don't forget to open `tcp:4244` when enabling Hubble Relay.

**Comment by pchaigno** [comment]
That requirement is already documented here: https://docs.cilium.io/en/latest/operations/system_requirements/#firewall-requirements. Is the idea of the present issue to document it in the following two sections?
- https://docs.cilium.io/en/latest/operations/troubleshooting/#observing-flows-with-hubble-relay
- https://docs.cilium.io/en/latest/gettingstarted/hubble/#inspecting-the-cluster-s-network-traffic-with-hubble-relay

**Comment by Rolinh** [comment]
@pchaigno This is easily missed by users who follow a getting started guide and enable relay (probably even more so if relay is enabled after the fact). Adding a link to this page is probably a good idea but I feel like there should be a `note` that mentions it in the hubble relay install instructions.

**Comment by youssefazrak** [comment]
I will take care of this one.

**Comment by youssefazrak** [comment]
@Rolinh @pchaigno 
Just to be sure we are on the same page, I will modify the `Getting Started Guides` and the 3rd link provided by Paul. For example all the installation documents.
Although does it really need to be written inside a `note`? That would be inconsistent with the current documentation as I haven't seen any notes in regards to firewall rules needing to be opened.

**Comment by Rolinh** [comment]
> Just to be sure we are on the same page, I will modify the `Getting Started Guides` and the 3rd link provided by Paul.

Yup, that's the way I see it.

> Although does it really need to be written inside a note? That would be inconsistent with the current documentation as I haven't seen any notes in regards to firewall rules needing to be opened.

I think so yes. If it does not stick out, users will miss it. It is not uncommon to use note/tip in the documentation, see for example [the getting started guide for kind](https://docs.cilium.io/en/latest/gettingstarted/kind/).
