### ISSUE TITLE
cilium-agent gets scheduled to nodes running OSes other than Linux

### ISSUE THREAD

**Issue by pires** [cilium/cilium#14410]
## Bug report

[`cilium-agent` is deployed through a DaemonSet](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml). Currently, there doesn't seem to be a way for a cluster admin to ensure it only gets scheduled onto Linux nodes. Why?
- DaemonSet doesn't set a `nodeSelector` to avoid OSes other than Linux, ie
  ```yaml
  nodeSelector:
      kubernetes.io/os: linux
  ```
  FYI the kubelet sets the [`kubernetes.io/os`](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#kubernetes-io-os) node label, based on `GOOS`.
- DaemonSet [specifies a catch-all toleration that invalidates the usage of taints](https://github.com/cilium/cilium/blob/5b911b80127d7d79120252334b92f7fd6495831c/install/kubernetes/cilium/values.yaml#L123-L124).

**General Information**

- Cilium version (run `cilium version`): 1.8.4
- Kernel version (run `uname -a`): `uname -a` doesn't work on Windows
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): Kubernetes 1.19.x
- Link to relevant artifacts (policies, deployments scripts, ...): all linked above.
- Generate and upload a system zip: doesn't seem relevant and actually I can't do it.
- Relevant slack thread: https://cilium.slack.com/archives/C53TG4J4R/p1607980778460600

**How to reproduce the issue**

1. Add a Windows node to a Kubernetes cluster and immediately cilium-agent is deployed there, obviously failing to run.
2. Alternatively, deploy a virtual-kubelet provider (eg [AWS Fargate](https://github.com/virtual-kubelet/aws-fargate)) and immediately cilium-agent is deployed there, when it shouldn't.))

**Comment by sayboras** [comment]
Having a node selector as `kubernetes.io/os: linux` prevents cilium from being installed in non-linux node, this might unintentionally swallow error internally without users' notice, and leave k8s cluster networking in limbo stage in my opinion. 

This [page](https://docs.cilium.io/en/latest/operations/system_requirements/) states that only linux clusters are support if I am not wrong.

**Comment by pires** [comment]
The only difference I find between the two options is the nodeSelector will prevent Cilium from being scheduled onto non-Linux machines vs not having it and have Pods fail to run.

The way I see it, for a Kubernetes admin, a nodeSelector is deterministic, can't be missed and is always up-to-date, contrary to what may happen with a systems requirements document.

**Comment by astralko** [comment]
I know its an old topic, but what would happen if you have a windows node without cilium in a cluster with cilium as its CNI?
will pods on linux nodes be able to get to pods on windows nodes?
