### ISSUE TITLE
cilium 1.8.2-1.9.1, Linux 5.9.x, outbound traffic being dropped from docker container in a pod

### ISSUE THREAD

**Issue by smira** [cilium/cilium#14417]
## Bug report

**General Information**

- Cilium version (run `cilium version`): 1.8.2, 1.8.6, 1.9.1
- Kernel version (run `uname -a`): 5.9.3, 5.9.11
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): K8s 1.19.4, 1.20.0
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:

**How to reproduce the issue**

Kubernetes cluster with Linux kernel 5.9.x (confirmed 5.9.3, 5.9.11), Kubernetes versions (confirmed with 1.20.0, 1.19.4), Clium versions tested: 1.8.2, 1.8.6, 1.9.1

Deploy docker as a pod to Kubernetes from image `docker:19.03.14-dind`. `kubectl exec` into a pod, and launch a Docker container within the pod: `docker run -it --rm alpine`. From the docker container try to download the URL: 

```
$ wget https://registry-1.docker.io/v2/docker/dockerfile-upstream/manifests/1.1.4-experimental
```

This hangs forever on `Connecting to registry-1.docker.io (52.72.232.213:443)`, sometimes it goes through, but most of the time fails. Expected result is to get `wget: server returned error: HTTP/1.1 401 Unauthorized`. It fails/succeeds randomly with other URLs.

`cilium monitor --type drop` shows:

```
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, identity 0->0: 147.75.98.173 -> 3.218.162.19 DestinationUnreachable(FragmentationNeeded)
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, identity 0->0: 147.75.98.173 -> 3.218.162.19 DestinationUnreachable(FragmentationNeeded)
```

(it was from a different attempt, `3.218.162.19` is one of the IPs for registry-1.docker.io)

This all with default `kubeProxyReplacement=probe`, and `kube-proxy` is running in the cluster.

This issue is only seen from the container running within the k8s pod, traffic from the pod itself is always fine.

If Linux kernel is changed to 5.8.x, traffic flows normally.

With `kubeProxyReplacement=disabled`, traffic flows normally as well.

**Comment by brb** [comment]
@smira Can you include sysdump?

**Comment by smira** [comment]
@brb I can do this later today, it is reproducible in a VM-based cluster

**Comment by smira** [comment]
Update: with `kubeProxyReplacement=disabled` my original test case works, but eventually the same issue appears when outbound connections get stuck, it is once again docker container inside a pod, this time failing randomly on `apk update`, `go mod download`, nothing in `cilium monitor --type drop`

**Comment by smira** [comment]
@brb sysdump

[cilium-sysdump-20201215-222435.zip](https://github.com/cilium/cilium/files/5698098/cilium-sysdump-20201215-222435.zip)

**Comment by brb** [comment]
I didn't find `147.75.98.173` in the given sysdump. Anyway, from the drops you pasted, it might be an MTU issue. I see that `tunl0` and `sit0` devices have lower MTU (1480) than cilium managed devices MTU (1500). Maybe try setting MTU in the ConfigMap of Cilium (`mtu: 1480`).

**Comment by joestringer** [comment]
@smira were you able to resolve or mitigate this issue?

**Comment by smira** [comment]
> @smira were you able to resolve or mitigate this issue?

We had to install different CNI unfortunately, so nothing I can help with.

**Comment by joestringer** [comment]
OK, thanks for the update anyway. If you decide to pick up Cilium again in future, don't hesitate to reach out over Slack or via Github issues if you encounter any obstacles.
