### ISSUE TITLE
Arping equivalent for IPv6

### ISSUE THREAD

**Issue by brb** [cilium/cilium#14429]
Currently we don't do any neigh discovery for IPv6 for NodePort / IPSec. So in the IPv6 mode we are relying on the fact that L2 entry for a destination node exists which obviously is not reliable.

Instead, we should introduce an equivalent of arping for IPv6 which should be based on NDP.

**Comment by borkmann** [comment]
Fixed via https://github.com/cilium/cilium/pull/17842
