### ISSUE TITLE
Make test ordering and fatal errors in CI more obvious

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14422]
In the following job, two tests failed:
* K8sDemosTest
* K8sUpdatesTest

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.19/75

As it turns out, the updates test failed because of Cilium going into CrashLoopBackoff and fataling. However the CI does not bubble this error up to the top and make it obvious:

```
2020-12-15T18:54:52.782864835Z level=fatal msg="Unknown IPAM backend hostscope" subsys=ipam
```

* The Updates test is not directly linked under the "Test result" section, so at a glance it doesn't look like that test even failed
* Clicking through to the [K8sUpdates test failure page](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.19/75/) does have evidence of the pods in CrashLoopBackoff way down in the page, but it doesn't have any representation of the "fatal" message or "ipam" or similar.

Furthermore, from the main test failure page, the order of tests was not obvious. This made it difficult to pinpoint that:
* First, the failure in the k8sUpdatesTest occurred due to the problem above, then
* Secondly, because k8sUpdatesTest  failed and did not put the environment back into a clean state afterwards, the second (K8sDemosTest) test failed with other errors that suggested some kind of map upgrade type issue.

It's hard to know where to start with investigating a CI failure like this, but in general it is very useful to start with the first failure and then work forward with that context so that you may know what types of failures occurred in earlier tests and how they may impact later tests.

For what it's worth, I think the fatal error message item here is easily actionable (and @aditighag volunteered to look into it), but I'm less sure how we would make the test ordering type stuff more obvious.

**Comment by aditighag** [comment]
>However the CI does not bubble this error up to the top and make it obvious:

Indeed! We seem to be filtering error messages as seen from this comment in the test output - 

`FAIL: Found 20 Cilium logs matching list of errors that must be investigated`

Fatal messages should be highlighted more prominently.

**Comment by aditighag** [comment]
I looked at how we highlight certain errors, and as it turns out, we have a repository of static strings [1] to match these errors. However, there doesn't seem to be any straightforward way (e.g., marker) of distinguishing fatal messages from regular error messages. I'll continue to look into this.

[1] https://github.com/cilium/cilium/blob/master/test/helpers/cons.go#L296

**Comment by ti-mo** [comment]
This is no longer an issue today with individual test suites getting their own VMs on GHA. What happens in one suite does not affect the other. Closing as completed.
