### ISSUE TITLE
Add JSON and JSONpath output for cilium API commands

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1448]
To make it easier to check for certain output in our APIs as part of our CI, we should add a flag to format the output of certain commands in JSON or JSONPath formats.

**Comment by eloycoto** [comment]
Hey @ianvernon

If you provide a list of commands that you want I can do it  tomorrow. 

Regards

**Comment by ianvernon** [comment]
Per our convo on Slack:
```
cilium service list | get
cilium bpf tunnel list|get
cilium bpf endpoints
cilium bpf lb list
cilium identity list
```
#1463 will have to be merged before the work can be done for `cilium identity list`.
