### ISSUE TITLE
Extend vagrant dev environment to deploy Cilium and Kubernetes in dual-stack mode

### ISSUE THREAD

**Issue by fristonio** [cilium/cilium#14511]
Currently, the vagrant dev environment cannot configure Kubernetes in Dual-Stack mode. Once #14461 is merged we will have Dual-Stack k8s running in our test clusters. To help developers complement the environment we run in our testing environment it makes sense to extend that vagrant start script(`./contrib/vagrant/start.sh`) to deploy a cluster with Dual stack enabled.

This can make use of an environment variable `DUALSTACK=1` to configure the desired infrastructure.

I have a rough list of steps to achieve this manually [here](https://gist.github.com/fristonio/69c60a47651913238732ddd50af8a417).
There is also a [script I use locally](https://gist.github.com/fristonio/7ab019cc73f55a25b815792442f091f6) to configure the dev environment.

**Comment by aanm** [comment]
Maybe we could simply enable it by default as well.

**Comment by Ankurk99** [comment]
I would like to work on this. @pchaigno Can you please assign this to me?

**Comment by pchaigno** [comment]
@Ankurk99 Done. As usual, don't hesitate to reach out on Slack if you have any question.

**Comment by aanm** [comment]
@Ankurk99 Apologies, I had a patch locally and I've made the PR #15827 since I was cleaning up my local branches. The patch works fine for me but it would be great to have someone double checking as well.
