### ISSUE TITLE
ctmap: GC orphan DSR SNAT entries

### ISSUE THREAD

**Issue by brb** [cilium/cilium#14512]
In the same manner as we did in https://github.com/cilium/cilium/pull/13912, remove SNAT DSR entries which don't have a corresponding CT entry.

**Comment by borkmann** [comment]
we should be able to close this one since dsr doesn't add to nat map anymore.

**Comment by borkmann** [comment]
(we might still do on the backend nodes)

**Comment by julianwiedmann** [comment]
@jibi fixed this a while ago with https://github.com/cilium/cilium/pull/21626.
