### ISSUE TITLE
Improve controller management in cilium-operator

### ISSUE THREAD

**Issue by fristonio** [cilium/cilium#14532]
The major working of the Cilium operator consists of controllers(identity-gc, endpoints-gc etc.) that periodically manage the state of a particular component. These controllers currently are not used to get any meaningful information from the operator.

Extend the Cilium operator to use stats from these controllers and expose them.

- [ ] Expose metrics for controller runs similar to what we have for `cilium-agent`.
- [ ] Add the ability to query the information about controllers from `cilium-operator` CLI. (depends on - #14484)
- [ ] Update cilium operator docs to documents the metrics exposed by the operator. (depends on - #14530)

**Comment by gandro** [comment]
Identity GC metrics in CRD-mode were added in https://github.com/cilium/cilium/pull/15905
