### ISSUE TITLE
Add identity GC metrics for CRD allocation mode

### ISSUE THREAD

**Issue by fristonio** [cilium/cilium#14549]
Recently #14254 added metrics related to identity GC in cilium-operator. This however is currently done for identity allocation mode KVstore and not for CRD. The CRD based identity GC lives here: 

https://github.com/cilium/cilium/blob/f2163862a42494030fd4177ddf25f021c85ae2e3/operator/k8s_identity.go#L70-L132

It would be good to have metrics for this mode as well to have consistency for cilium-operator metrics.

**Comment by rscampos** [comment]
Hello @fristonio @pchaigno,
I'm planning to pick up this issue, do you guys think that is a good handle issue? Because this is going to be my second issue :D

**Comment by fristonio** [comment]
Hey @rscampos 
Yeah, this seems like a good issue to handle as your second. You can see https://github.com/cilium/cilium/pull/14254 for the reference implementation as to how this was done for KVStore allocation mode. Feel free to reach out on slack if you need any help :)

**Comment by rscampos** [comment]
Cool @fristonio, thank you for the hint. If I have some problem I let you know :D

**Comment by rscampos** [comment]
Hello @fristonio @pchaigno,

I start looking at this issue and before some code, I used [#14254](https://github.com/cilium/cilium/pull/14254) as a reference and I could understand what was done. Using **kvstore** I could see the metrics without problem. To test theses metrics I did some pod creation/deletion, and the metrics just work fine.

After that, I start the cilium-operator using _--identity-allocation-mode='crd'_ and follow the flow with some print in the source. Inside identityGCIteration() I insert some code to get len(identityStore) but it always return []. So I think that the way I used to test **kvstore** is not the same here, with **crd**, is it?

As soon as I find a way to test it, I think I have a clue (based on [#14254](https://github.com/cilium/cilium/pull/14254)). If you have any suggest, feel free to tell me please... this is my second issue :D

**Comment by rscampos** [comment]
Hello guys!

Just send a draft PR, If something doesn't go well, just let me know :D
