### ISSUE TITLE
Add helm option to enable k8s events handover

### ISSUE THREAD

**Issue by fristonio** [cilium/cilium#14547]
Currently, there is no way to configure the operator to handle the CNP status updates using helm.
Cilium operator handles the CNP status updates only when:

- `kvstore` is enabled 
- `enable-k8s-event-handover` is set to true
- `disable -cnp-status-updates` is set to false

Add helm option to configure `enable-k8s-event-handover` config map value.

**Comment by youssefazrak** [comment]
@pchaigno can you please assign this ticket to me?
