### ISSUE TITLE
CI: Fix CodeQL analysis

### ISSUE THREAD

**Issue by youssefazrak** [cilium/cilium#14567]
Hey guys,

I was checking merged PR #14514 _adding CodeQL analysis_ and it seems to have a typo [found here](https://github.com/cilium/cilium/blob/master/.github/workflows/codeql-analysis.yml#L13-L14):
```
  schedule:
    - cron: "6 45 * * 3"
```
From the `cron` documentation and the official [CodeQL repo readme](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning) this can't work as 45 not in the hour ranges.

Quick fix: swap 6 and 45 and have the 6h45min that was probably the initial target.
```
  schedule:
    - cron: "45 6 * * 3"
```
I can take care of the PR to fix it.

Cheers!

**Comment by aditighag** [comment]
\cc @twpayne

**Comment by youssefazrak** [comment]
You can see the [failures directly on Github Actions](https://github.com/cilium/cilium/actions?query=workflow%3A.github%2Fworkflows%2Fcodeql-analysis.yml):
