### ISSUE TITLE
Add taskset to bugtool

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14566]
To assist with additional debugging around processor affinity, it would be useful to add this command to the bugtool:

```
$ taskset -p 1
pid 1's current affinity mask: f
```

There's a list of `defaultCommands` in `bugtool/cmd/configuration.go` which could be extended with this tool. The binary should already be present in the Cilium container.

**Comment by youssefazrak** [comment]
@joestringer I will take care of this one
