### ISSUE TITLE
NodePort doesn't work correctly when VLANs are involved

### ISSUE THREAD

**Issue by pavels** [cilium/cilium#14579]
## Bug report

Cilium version: `1.9.1`
Kernel: `5.9.0-0.bpo.2-amd64`

If you have an interface, say `enp36s0f0`, for internal traffic and than `enp36s0f0.10` (that is tagged VLAN on the same physical interface) for external traffic than if the traffic is coming from the external side and is routed into internal, POD ips can be accessed, but NodePort (and anything that relies on them) does not work.

I have originally asked about this on slack, here is the original question 192.168.55.0/24 network is on the tagged VLAN interface (enp36s0f0.10) and 192.168.46.0/24 is on the untagged one (enp36s0f0):

i have two networks (192.168.46.0/24 and 192.168.55.0/24) - the kubernetes cluster with cilium is in the 46 network - there is a router (with 192.168.46.1 and 192.168.55.124 as ip addresses) which doubles as control plane node, one normal worker node (192.168.46.10) and i also have one computer in 46 network, that is not running kubernetes or any cilium daemons (192.168.46.200) - the default gw in the 55 knows to route 46 network as well as POD CIDR (10.92.0.0/16) through 192.168.55.124
Now i try to create NodePort service - POD is running on the worker node (.46.10). externalTrafficPolicy: Cluster. I see that cilium creates all the correct services (cilium service list) and it got port - 30698
Now from the .46.1 computer i can access this service on all addresses (192.168.46.1:30698, 192.168.55.124:30698, 192.168.46.10:30698), same on the .46.10 worker node and same for the .46.200 (which has .46.1 as default gw, but is not running any kubernetes or cilium)
But if i try to access this NodePort service from the 192.168.55.0/24 network, it doesn't work as expected. I can access the service on 192.168.46.10:30698 but i can't access the NodePort service neither on 192.168.55.124:30698 or 192.168.46.1:30698.

**Comment by kvaster** [comment]
Just to accept the bug and to add the reason.

Cilium status:

```
KVStore:                     Ok   Disabled
Kubernetes:                  Ok   1.20 (v1.20.2) [linux/amd64]
Kubernetes APIs:             ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:        Strict   [wan0, wan0.4000 (Direct Routing)]
Cilium:                      Ok       OK
NodeMonitor:                 Listening for events on 32 CPUs with 64x4096 of shared memory
IPAM:                        IPv4: 20/255 allocated from 10.244.0.0/24,
BandwidthManager:            Disabled
Host Routing:                BPF
Masquerading:                BPF   [wan0, wan0.4000]   10.244.0.0/16
Controller Status:           89/89 healthy
Proxy Status:                OK, ip 10.244.0.31, 0 redirects active on ports 10000-20000
Hubble:                      Ok              Current/Max Flows: 637/4096 (15.55%), Flows/s: 10.63   Metrics: Disabled
Cluster health:              0/3 reachable   (2021-01-18T18:41:29Z)
  Name                       IP              Node        Endpoints
  xxxxxx-dev-1 (localhost)   10.118.10.10    reachable   unreachable
  xxxxxx-dev-2               10.118.10.11    reachable   unreachable
  xxxxxx-dev-3               10.118.10.12    reachable   unreachable
```

Cilium metrics list:

```
cilium_drop_bytes_total                               direction="EGRESS" reason="Unsupported L3 protocol"                                               7560.000000
cilium_drop_bytes_total                               direction="EGRESS" reason="Unsupported protocol for NAT masquerade"                               25819.000000
cilium_drop_count_total                               direction="EGRESS" reason="Unsupported L3 protocol"                                               104.000000
cilium_drop_count_total                               direction="EGRESS" reason="Unsupported protocol for NAT masquerade"                               253.000000
```

When using tcpdump I can see that packet which is targeted for wan0.4000 (vlan tagged interface) will appear on wan0 and after that cilium will drop it. With cilium disabled on wan0 packet will appear on wan0 (tagged) and after that I can see it on wan0.4000. CIlium should skip processing vlan tagged packets on interfaces and allow them to be processed in kernel before cilium will be able to process them on proper interface (untagged).

**Comment by joestringer** [comment]
I wonder, what happens if you configure the `--devices` flag to specify the VLAN device?

**Comment by kvaster** [comment]
This problem will not occur. Cilium will not filter packets on wan0 in case only wan0.4000 will be in devices list. But this will lead to another bug (at least for me) - cilium will not masquerade packets on wan0 which is used to connect to internet from pods. The only way to have setup working is adding two options: `--set bpf.masquerade=false` and `--set devices=wan0.4000`. But this isn't what we want :)

**Comment by pavels** [comment]
During all my tests, i had `masquerade: "false"` in the ConfigMap
for devices i tried only untahhed and tagged + untagged interfaces

**Comment by brb** [comment]
Discussed offline: `validate_ethertype()` on `wan0` drops the tagged packet. One possible solution is to pass the packet to the stack. The kernel should pop the VLAN header and then reinsert into RX queue, which eventually should lead to the bpf_host invocation attached to `wan0.4000`.

**Comment by kvaster** [comment]
I'm trying to fix the problem, but it seems that my knowledge is not enough.

Setup: `wan0` and `wan0.4000`, bpf programs are attached to both interfaces, direc routing device is `wan0.4000`.

First of all I was wrong - packet is not filtered by validate_ethertype. Packet sent to `wan0.4000` will appear on wan0 node1 first:

```
52:54:00:63:7b:cc > 52:54:00:12:34:56, ethertype 802.1Q (0x8100), length 78: vlan 4000, p 0, ethertype IPv4 (0x0800)
```

We can see vlan header here. But it will be NOT dropped. VLAN header will be ignored and packet will be load balanced to service pod and will appear on wan0 of node2:

```
52:54:00:12:34:56 > 52:54:00:12:34:58, ethertype 802.1Q (0x8100), length 90: vlan 4000, p 0, ethertype 802.1Q (0x8100), vlan 4000, p 0, ethertype IPv4 (0x0800)
```

And... We have two vlan headers here now... It seems that after load balancing packet is sent with it's original headers through wan0.4000 and this will lead to double vlan headers. That's why I (personally) was not able to see those packets using tcpdump filters.

I've added following code in `handle_netdev` before `do_netdev` and I do not completely understand why packet is still load balanced insteadof passing it to kernel stack:

```
	if (proto == bpf_htons(ETH_P_8021Q)) {
		return CTX_ACT_OK;
	}
```

**Comment by jochenseeber** [comment]
I would really like to see this fixed, as this prevents us from using Cilium

**Comment by EHerzog76** [comment]
My work-a-round's are<br>
   - use only a Vlan as cilium device e.g. bond0.4000<br>
   - or use a different device for Vlan-tagged traffic e.g. bond1.4000
