### ISSUE TITLE
Egress proxy doesn't set destination identity to reserved:world

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#1458]
Right now the egress proxy does not set the destination identity to reserved:world when there is an HTTP request that goes out of the Kubernetes cluster.

**Comment by tgraf** [comment]
This tasks includes extending the `getSourceInfo()` and `getDestinationInfo()` functions to:
 - [x] When the identity is not known, look at the IP address and compare it against the host IPs as available via `pkg/nodeaddress` and set the identity to `ID_HOST`
 - [x] Introduce a new ID `ID_CLUSTER` which represents an unknown identity with an IP inside the cluster prefix (the cluster prefixes are available via `pkg/nodeaddress`)
