### ISSUE TITLE
Allow ClusterIP access from outside

### ISSUE THREAD

**Issue by brb** [cilium/cilium#14581]
There was recently an ask by a few Cilium users to allow ClusterIP from outside.

kube-proxy doesn't seem to reject requests to ClusterIP from outside cluster, in opposite what is stated in [the docs](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types):

> ClusterIP: Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable from within the cluster. This is the default ServiceType.

**Comment by borkmann** [comment]
Duplicate of https://github.com/cilium/cilium/issues/14563 ?

>> Choosing this value makes the Service only reachable from within the cluster.

> kube-proxy doesn't seem to reject requests to ClusterIP from outside cluster.

So that is a kube-proxy security issue then if external traffic can still access ClusterIP services from outside? I would stick to the doc in this case, but rather implement NAT-based handling as discussed in #14563 for certain Pods that need it, also a safer choice given we don't need to expose the ClusterIP service to external traffic.

**Comment by brb** [comment]
> Duplicate of #14563 ?

This linked issue is different, as it is about enabling ClusterIP xlation from bpf_lxc. While this issue is about allowing ClusterIP xlation in bpf_host.

**Comment by pchaigno** [comment]
@brb Is this just a matter of introducing a new flag that skips that line in the datapath? https://github.com/cilium/cilium/blob/72949b4b49d43e6dbb4714929222acb688ce6dd2/bpf/lib/lb.h#L331

**Comment by brb** [comment]
Yep.

**Comment by Sh4d1** [comment]
I can take this one! Though wouldn't it be better to skip here https://github.com/cilium/cilium/blob/0218d373d2f8452720855a4a07b2719fd9826095/bpf/lib/nodeport.h#L1785 with a new flag (as well as the ipv6 one) ?

From my very naive point of view, in this case, the service flags will only be set to `SVC_FLAG_ROUTABLE`, thus `__lb_svc_is_routable` will always return false even if some lines are skipped in `svc_is_routable_mask` right?

**Comment by brb** [comment]
@Sh4d1 Cool, I've assigned you.

I took a closer look, and it seems that we don't set the ClusterIP type in the BPF maps. We could do that, and then conditionally (e.g. `ENABLE_CLUSTER_IP_FROM_OUTSIDE`) extend the mask.

Another approach would be to mark ClusterIP services as routable. But currently, the routable flag is used to distinguish between a surrogate services (aka 0.0.0.0; used to access NodePort via any IP on a host) and "normal" services. So taking this approach would be hacky.

**Comment by Sh4d1** [comment]
Yep indeed adding a flag for ClusterIP sounds good! `flags` is already full, so I guess it'll go in `flags2`, so is:
```c
static __always_inline bool __lb_svc_is_routable2(__u8 flags2)
```
good for you ? 
And then returning:
```c
return __lb_svc_is_routable(svc->flags) || __lb_svc_is_routable2(svc->flags)
```

Or should I rather handle `flags` and `flags2` in `__lb_svc_is_routable` ? 🤔

**Comment by borkmann** [comment]
> Yep indeed adding a flag for ClusterIP sounds good! `flags` is already full, so I guess it'll go in `flags2`, so is:
> 
> ```c
> static __always_inline bool __lb_svc_is_routable2(__u8 flags2)
> ```
> 
> good for you ?
> And then returning:
> 
> ```c
> return __lb_svc_is_routable(svc->flags) || __lb_svc_is_routable2(svc->flags)
> ```
> 
> Or should I rather handle `flags` and `flags2` in `__lb_svc_is_routable` ?

I would prefer if this is resolved w/o adding additional performance penalty to the critical fast-path especially given we can avoid it, so ideally just a single test (as before) and if otherwise not possible wrt flags, then lets mark ClusterIP with routable flag from agent side if this option is enabled on the agent.

**Comment by brb** [comment]
> lets mark ClusterIP with routable flag from agent side if this option is enabled on the agent.

Then let's flag other routable service entries (e.g. NodePort) with the same routable flag. Otherwise, we will have the routable logic spread over the places.
