### ISSUE TITLE
Observability documentation duplicates text

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14587]
Glancing through this page:
https://docs.cilium.io/en/v1.9/concepts/observability/intro/

The second and third paragraphs seem substantially similar, it seems like maybe a merge was mishandled to include multiple copies of the text. This affects the master version of the docs as well. It would be good to review the text and streamline it to avoid duplication.

**Comment by ti-mo** [comment]
This page seems to be gone, closing.

**Comment by joestringer** [comment]
Still affects v1.13 or newer on this link: https://docs.cilium.io/en/v1.12/concepts/observability/intro/

**Comment by vipul-21** [comment]
Can I take a look at this ?

**Comment by vipul-21** [comment]
Based on the commit : https://github.com/vipul-21/cilium/commit/160d6b920e9c8ab0fb1d22c5c488448b690c4aed it does not seem like a merge was. 
Might need rephrasing of the two paragraphs i think
