### ISSUE TITLE
Unclear documentation on the scope of entities when using cluster-mesh

### ISSUE THREAD

**Issue by mzahorik** [cilium/cilium#14595]
When trying to understand how entities and identities are managed with a cluster mesh, the documentation at:

https://docs.cilium.io/en/v1.9/policy/language/#policy-examples

says that the cluster entity says it refers to all endpoints within the cluster, but then explains the set include host, remote-node, and init among others.

On that same page, remote-node says "any node in any of the connected clusters".  Additionally, on the page:

https://docs.cilium.io/en/v1.9/concepts/terminology/

The remote-node identity is defined as "The collection of all remote cluster hosts. Any traffic that originates from or is designated to one of the IPs of any host in _any connected cluster_ other than the local node." (emphasis mine)

Can the documentation be clarified on the definition of remote-node when in cluster-mesh.  If I deploy a policy with a destination of toEntitities[0] = "remote-node" will I get only endpoints considered local/bound to the local Kubernetes cluster, or will I get all endpoints from all connected clusters?

**Comment by bumarcell** [comment]
I have the same question!
