### ISSUE TITLE
CLI: cilium encrypt command

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14638]
We should provide a new Cilium subcommand, `cilium encrypt status, flush` to interact with IPSec's state in the kernel when it is enabled. `cilium encrypt status` would display information on the current status of the IPSec configuration while `cilium encrypt flush` would flush all XFRM state (`ip xfrm state flush` and `ip xfrm policy flush`).

See https://github.com/cilium/cilium/tree/master/cilium/cmd for the code of existing subcommands (the filenames match the commands).

**Comment by jrfastab** [comment]
As a first take cilium status could report any errors found in the xfrm MIB counters. Also reporting keyIDs in use would be useful something like,

``` 
cilium encrypt status
  Keys: 1/1
  Packets: 5555 rcvd / 6666 sent
  Errors: None
```

**Comment by elfadel** [comment]
@pchaigno Could you assign it to me please?

**Comment by joestringer** [comment]
One more request, report the IP selected for local ipsec address: https://github.com/cilium/cilium/pull/15048/files/653cd5bddf3f3cee7e4dddd80010ff1d495dce04..11fab3cf008399c1b2da3f0057b7fc0680db6ed3#diff-14a5efc51ce7ea3959385022d4800b355c766c60e8b7ba0e6052afced05ddbf0

**Comment by pchaigno** [comment]
@elfadel I've unassigned you. Please comment here if you're still working on this.

**Comment by h3llix** [comment]
@pchaigno can you help me on how to query IPSec configurations, Also I am thinking to take up this issue in extension to my gsoc proposal as it revolves mostly around improvements in cli.

**Comment by pchaigno** [comment]
> Also I am thinking to take up this issue in extension to my gsoc proposal as it revolves mostly around improvements in cli.

I would advise against that unless it's clear that the original project idea will take less than 175 hours. It's better to have a strong proposal with a small scope than lacking the time to prepare a proposal with a large scope.

> A little help on how to get the above information ? or do I need to extract the required data from dump of `ip -s xfrm state`

The netlink library we use, [vishvananda/netlink](https://github.com/vishvananda/netlink), should already provide that information. Please check https://pkg.go.dev/github.com/vishvananda/netlink.

**Comment by h3llix** [comment]
Hi @pchaigno. I just realized but I think that these are doable under 175hours but I will reconsider. For now, I just added references to this issue in my draft proposal. Can you provide some reviews on my draft proposal? Thank you.

**Comment by trvll** [comment]
Hi @pchaigno, Could you assign it to me, pls?

**Comment by pchaigno** [comment]
We had a call with @h3llix who is looking into this issue as part of his GSoC project. The first version for this CLI will include `status` and `flush` subcommands, with a slightly simplified `status` subcommand compared to above. It will only display information pertaining to IPsec in its first version.
```
cilium encrypt status
  Encryption: ipsec
  NodeEncryption: disabled
  Keys in use: 2
  Max. sequence number: 0xffffbd4f/0xffffffff
  Errors: 12
    XfrmInStateProtoError 12
```
Notes:
- The `NodeEncryption` status can be skipped for now if we can't retrieve it through the API. Once https://github.com/cilium/cilium/issues/13913 is addressed, we can add it easily.
- `Keys in Use` would give the number of IPsec keys currently in use on the host. That is, the number of different keys in `ip xfrm state`. It should be >1 only during key rotations.
- `Max. sequence number` would give the maximum anti-replay output sequence number on the node. That is, the number for `oseq` in `ip xfrm state`. Key rotation resets that number. It should happen well before that number reaches its max. value or all traffic will be dropped for the corresponding node-to-node connection.
- `Errors` would count the total number of errors in `/proc/net/xfrm_stat` and display the breakdown if any are non-zero. We may need to rework this field later on since what really matters is whether counters are increasing. A static total count is probably good enough for a first version though.

**Comment by gandro** [comment]
> It will only display information pertaining to IPsec in its first version.

This makes sense to me. For future reference, if we ever want to add support for Wireguard as well, the plumbing done for the WireGuard section in `cilium debuginfo` could easily be reused for `cilium encrypt status`:

https://github.com/cilium/cilium/blob/a12f4e4ba457df43495348c7baf2fdb57ce4ae93/pkg/wireguard/agent/agent.go#L466-L469

**Comment by h3llix** [comment]
@pchaigno I need help with testing the PR. For development I added xfrm states on my local machine but I was unable able to test it with cilium.

**Comment by pchaigno** [comment]
@h3llix Let's discuss it on Slack; it will be easier to troubleshoot. Can you open a thread with the specific issues you hit?
