### ISSUE TITLE
CI: RuntimePrivilegedUnitTests TestArpPingHandling failed with i/o timeout error

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#14640]
Hit on #14635:

```
	 level=error msg="arping failed" error="i/o timeout" interface=veth0 ipAddr=9.9.9.250 subsys=linux-datapath
	 node_linux_test.go:1039:
	     c.Assert(found, check.Equals, true)
	 ... obtained bool = false
	 ... expected bool = true
	 
	 FAIL: node_linux_test.go:951: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
```

https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/3337/
[test_results_Cilium-PR-Runtime-4.9_3337_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/5831529/test_results_Cilium-PR-Runtime-4.9_3337_BDD-Test-PR.zip)

Related to #14510? Previously: #14125.

**Comment by brb** [comment]
@tklauser Does your PR include https://github.com/cilium/cilium/pull/14601?

**Comment by tklauser** [comment]
Oh, looks like the PR itself doesn't include #14601. But AFAIK PRs are rebased on latest `master` in CI, so it should be included, right?

**Comment by brb** [comment]
I've tried running it in a loop for almost forever and I couldn't reproduce the failure. Previously, I could reproduce it easily when running in a loop.

**Comment by tklauser** [comment]
Seems likely that the failing run of #14635 wasn't run with #14601 included. Let's close this for now. Thanks for trying to reproduce @brb!

**Comment by pchaigno** [comment]
https://github.com/cilium/cilium/pull/14639 failed with this flake: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/3353/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/
It does include #14601:
```
44a9a4e240118c38519991ce06c89da81cbe500e (HEAD -> pr/pchaigno/mark-gke-ci-as-419, origin/pr/pchaigno/mark-gke-ci-as-419) test: Skip fragment tracking test on GKE
fd387dc0d78c121d3f736a9546b94598745278cc test: Fix fragment tracking test on GKE
5470f29558e3e6f4b42370d67d8acbbb3d7f9635 test: Mark GKE CI pipeline as running Linux 4.19
9a4c693580ba7e931faf8c9f27832470a05660f1 hubble/filter: filters based on ip version
8e5360bb1ff2c68ba3d80fc2f9a7e162df3b293d docs: AKS - remove azure0 from CNI chaining config
c9f54e3451e27f813b2cb12d7521d759b46faf4e Documentation: Update list of Jenkins jobs
6754e8e9bd8cdb28676d39da4211d3a6b56665d4 pkg/loadbalancer: Optimize L3n4Addr.Hash for performance
d03aeec1d4d3648267d3e2f50e677f9214a3a7d8 pkg/loadbalancer: Add simple benchmark for L3n4Addr.Hash
ac8d0938b9a6d42c7a5988243d853fe0444209c3 Bump CNI plugin version to v0.9.0 in runtime images
c20e67a45bb4cc2a0c070ba9e943d3741e193633 vendor: bump github.com/containernetworking/* to latest version
4b769cb53a15a7dcc30b8d2eac36094cb4cc071e datapath: Do not use proxy original source address with tunneling
2284c76d4b528d56cb859836df54b6a8a58cc317 arp: Add retries to arping
```

**Comment by brb** [comment]
@pchaigno Could you rebase against the latest master which includes the fix  https://github.com/cilium/cilium/pull/14651?

**Comment by pchaigno** [comment]
Yep, just realized the pull request is missing #14651 so likely the reason for the flake. I'll close again. Sorry for the noise.
