### ISSUE TITLE
Packets to pods processed twice with per-endpoint routes + VXLAN

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14657]
The following is an example trace on a node receiving packets from a VXLAN tunnel, with per-endpoint routes enabled and monitor aggregation disabled:
```
<- overlay flow 0x0 identity 0->0 state new ifindex cilium_vxlan orig-ip 0.0.0.0: 10.128.11.130:45516 -> 10.128.7.78:80 tcp SYN
-> endpoint 4089 flow 0x0 identity 10554->1104 state new ifindex lxc86cdad1b40a5 orig-ip 10.128.11.130: 10.128.11.130:45516 -> 10.128.7.78:80 tcp SYN
<- stack flow 0x0 identity 2->0 state new ifindex cilium_vxlan orig-ip 0.0.0.0: 10.128.11.130:45516 -> 10.128.7.78:80 tcp SYN
-> endpoint 4089 flow 0x0 identity 10554->1104 state established ifindex 0 orig-ip 10.128.11.130: 10.128.11.130:45516 -> 10.128.7.78:80 tcp SYN
```
For IPv4, we have a single point in the code where we display `TRACE_TO_LXC` traces. We can therefore conclude that the packet was processed twice, likely once via a tail call to the destination BPF program, then a second time when the packet is received on the destination container's interface. The `state established` for the SYN packet in the second `TRACE_TO_LXC` also seems to confirm that.

**Comment by joestringer** [comment]
I'm a bit conflicted on this: On one side, I feel like a given packet should only be handled once per flow through the overall packet processing code and ideally we would print something like the following to represent that we receive the packet from the tunnel and deliver to the endpoint:

```
<- overlay ...
-> endpoint ...
```

At the same time, in endpoint routes mode, the traffic really is entering and exiting BPF space twice. It would be more accurate to say:

```
<- overlay ...
-> stack ...
<- stack ...
-> endpoint ...
```

**Comment by pchaigno** [comment]
It seems we're not hitting the same issue in the native routing case because of this condition: https://github.com/cilium/cilium/blob/72949b4b49d43e6dbb4714929222acb688ce6dd2/bpf/bpf_host.c#L458-L468 which leads us to skip the call to `ipv4_local_delivery`. `ENABLE_REDIRECT_FAST` is currently incompatible with per-endpoint routes and `NO_REDIRECT` is almost always true, so the condition is true.

**Comment by pchaigno** [comment]
We process packets twice because (1) `FORCE_LOCAL_POLICY_EVAL_AT_SOURCE` is defined (default) so packets are processed at `bpf_overlay` and (2) endpoint routes are enabled so `bpf_lxc` is installed on the egress of the lxc device. The same issue exists for the native routing case as well but is mitigated by the above `skip_redirect`.
