### ISSUE TITLE
istio-proxy can't connect to upstream/pilot on AKS

### ISSUE THREAD

**Issue by Subreptivus** [cilium/cilium#14660]
## Bug report

**General Information**

- Cilium version (run `cilium version`):
Client: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
Daemon: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
- Kernel version (run `uname -a`):
Linux aks-vmss01-42431932-vmss000000 5.4.0-1035-azure #36~18.04.1-Ubuntu SMP Wed Dec 16 23:49:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T16:06:08Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...):
https://docs.cilium.io/en/stable/gettingstarted/k8s-install-aks/
https://docs.cilium.io/en/stable/gettingstarted/k8s-install-azure/
- Generate and upload a system zip:
[cilium-sysdump-20210120-112307.zip](https://github.com/cilium/cilium/files/5841353/cilium-sysdump-20210120-112307.zip)

**How to reproduce the issue**

1. Install AKS Cluster
2. Install Cilium into AKS Cluster using either of manuals https://docs.cilium.io/en/stable/gettingstarted/k8s-install-aks/ or https://docs.cilium.io/en/stable/gettingstarted/k8s-install-azure/. The very Helm command I've used last time is:
```
helm install cilium cilium --repo https://helm.cilium.io/ --version 1.9.1   --namespace cilium   --set azure.enabled=true   --set azure.resourceGroup=$AZURE_NODE_RESOURCE_GROUP   --set azure.subscriptionID=$AZURE_SUBSCRIPTION_ID   --set azure.tenantID=$AZURE_TENANT_ID   --set azure.clientID=$AZURE_CLIENT_ID   --set azure.clientSecret=$AZURE_CLIENT_SECRET   --set tunnel=disabled   --set ipam.mode=azure   --set masquerade=false   --set nodeinit.enabled=true   --set nodeinit.restartPods=true
```
3. Install Cilium's modified version of Istio using manual: https://github.com/cilium/cilium/blob/master/Documentation/gettingstarted/istio.rst

**More Details**
On freshly created Azure AKS cluster v1.19.6 (but it doesn’t really meter, I believe, did the same on v1.18.10), after installing Cilium using either ordinary CNI chaining method https://docs.cilium.io/en/stable/gettingstarted/k8s-install-aks/ or Azure IPAM https://docs.cilium.io/en/stable/gettingstarted/k8s-install-azure/ Istio components becomes really flaky communicating to each other. Actually all the component suffering from DNS errors like `curl: (6) Could not resolve host: git.io` or `;; connection timed out; no servers could be reached`, but I'm interested in Istio most.
I’ve used latest two Cilium’s Istio releases v1.6.14 and v1.7.6 the picture is the same.
The main problem that `istio-proxy` couldn’t reliably connect to `istiod` (pilot).
Log is full of errors like:
```
2021-01-19T17:13:55.405297Z	warning	envoy config	StreamSecrets gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp 10.0.227.62:15012: i/o timeout"
2021-01-19T17:16:18.727112Z	warning	envoy config	StreamSecrets gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.0.0.10:53: no such host"
```
And so on...
Cordoning/rebooting nodes and trying to reschedule those pods on different nodes sometimes help sometimes not.
Just to have source of truth created another cluster without Cilium and installed not modified version of Istio v1.7.6 there. Everything is working fine there as was expected.
So here the question, is there some tested configuration for AKS and Cilium’s version of Istio (I need L7 policies in the end) which I can use? Or maybe someone can advice me what should I check?

**Comment by Subreptivus** [comment]
I bet it has something to do with Azure's CNI, but I don't know how to troubleshoot it properly. We have pretty old AKS cluster (v1.17.11) where Cilium v1.9.1 and Cilium's Istio v1.5.9 work just fine.

**Comment by aditighag** [comment]
We recently fixed Istio redirection in Cilium. Here is the PR - https://github.com/cilium/cilium/pull/14271
Could you try with Cilium v1.9.2 and Istio v1.6.15?

**Comment by Subreptivus** [comment]
Looks like unrelated or partially related to Cilium. Sometimes it isn't working even without Cilium at all. Sometimes it's working fine on one Cilium version, but failing on another.
Can't confirm, or reliably reproduce, hence closing.
