### ISSUE TITLE
Egress network policy allows traffic that should be denied

### ISSUE THREAD

**Issue by mattfenwick** [cilium/cilium#14678]
## Bug report

A network policy which should only allow traffic to a single pod based on labels, also allows traffic to other pods without the label.

Expected connectivity matrix:

There are 9 pods, so 9x9 = 81 possible requests from pod to pod.
The pod issuing the request is in the left column; the pod receiving the request is in the top row.
An `X` means the request was denied; a `.` means the request was allowed.

```
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|  -  | X/A | X/B | X/C | Y/A | Y/B | Y/C | Z/A | Z/B | Z/C |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| x/a | X   | X   | X   | X   | .   | X   | X   | X   | X   |
| x/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| x/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
```

Measured connectivity:

```
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|  -  | X/A | X/B | X/C | Y/A | Y/B | Y/C | Z/A | Z/B | Z/C |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| x/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| x/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| x/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
```

This is based on namespaces/pods with labels:

Namespace x (labels: {"ns": "x"})
  - pod a (labels {"pod": "a"})
  - pod b (labels {"pod": "b"})
  - pod c (labels {"pod": "c"})
Namespace y (labels: {"ns": "y"})
  - pod a (labels {"pod": "a"})
  - pod b (labels {"pod": "b"})
  - pod c (labels {"pod": "c"})
Namespace z (labels: {"ns": "z"})
  - pod a (labels {"pod": "a"})
  - pod b (labels {"pod": "b"})
  - pod c (labels {"pod": "c"})

**General Information**

- Cilium version 1.9.1
- Kernel version: `Linux netpol-cilium-control-plane 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use:

        kubectl version
        Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
        Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- KinD version: 0.9.0
- containerd

**How to reproduce the issue**

1. create kind cluster with cilium

        #!/usr/bin/env bash
        
        set -e
        
        CLUSTER=${CLUSTER:-netpol-cilium}
        CONFIG=${CONFIG:-netpol-cilium-conf.yaml}
        
        cat << EOF > "$CONFIG"
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
        - role: worker
        - role: worker
        - role: worker
        networking:
          disableDefaultCNI: true
        EOF
        
        
        
        kind create cluster --name="$CLUSTER" --config="$CONFIG"
        until kubectl cluster-info;  do
            echo "$(date) waiting for cluster..."
            sleep 2
        done
        
        
        CILIUM_VERSION="1.9.1"
        
        # Add Cilium Helm repo
        helm repo add cilium https://helm.cilium.io/
        
        # Pre-load images
        docker pull cilium/cilium:"v${CILIUM_VERSION}"
        
        # Install cilium with Helm
        helm install cilium cilium/cilium \
          --version ${CILIUM_VERSION} \
          --namespace kube-system \
          --set nodeinit.enabled=true \
          --set kubeProxyReplacement=partial \
          --set hostServices.enabled=false \
          --set externalIPs.enabled=true \
          --set nodePort.enabled=true \
          --set hostPort.enabled=true \
          --set bpf.masquerade=false \
          --set image.pullPolicy=IfNotPresent \
          --set ipam.mode=kubernetes

2. create network policy in `netpol.yaml`

        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: vary-egress-8-0-0-2-0
          namespace: x
        spec:
          egress:
          - ports:
            - {}
            to:
            - namespaceSelector:
                matchLabels:
                  ns: "y"
              podSelector:
                matchLabels:
                  pod: b
          - ports:
            - port: 53
              protocol: UDP
          podSelector:
            matchLabels:
              pod: a
          policyTypes:
          - Egress

3. download [cyclonus 0.0.7](https://github.com/mattfenwick/cyclonus/releases/tag/v0.0.7) and invoke it with `cyclonus_0.0.7 probe --noisy=true --policy-path netpol.yaml`

**Comment by aanm** [comment]
@mattfenwick thanks for opening the issue. I've tried to reproduce it and it seems the policy is not correctly defined as Cilium prints an error message with the following:
```
Jan 21 12:19:17 k8s2 cilium-agent[23936]: level=error msg="Error while parsing k8s kubernetes NetworkPolicy" ciliumNetworkPolicy="&NetworkPolicy{ObjectMeta:{vary-egress-8-0-0-2-0 x c8995302-ace9-4f73-8738-9e47d574a441 268293 map[] map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"networking.k8s.io/v1\",\"kind\":\"NetworkPolicy\",\"metadata\":{\"annotations\":{},\"name\":\"vary-egress-8-0-0-2-0\",\"namespace\":\"x\"},\"spec\":{\"egress\":[{\"ports\":[{}],\"to\":[{\"namespaceSelector\":{\"matchLabels\":{\"ns\":\"y\"}},\"podSelector\":{\"matchLabels\":{\"pod\":\"b\"}}}]},{\"ports\":[{\"port\":53,\"protocol\":\"UDP\"}]}],\"podSelector\":{\"matchLabels\":{\"pod\":\"a\"}},\"policyTypes\":[\"Egress\"]}}\n]},Spec:NetworkPolicySpec{PodSelector:{map[io.kubernetes.pod.namespace:x pod:a] []},Ingress:[]NetworkPolicyIngressRule{},Egress:[]NetworkPolicyEgressRule{NetworkPolicyEgressRule{Ports:[]NetworkPolicyPort{NetworkPolicyPort{Protocol:*TCP,Port:<nil>,},},To:[]NetworkPolicyPeer{NetworkPolicyPeer{PodSelector:&v1.LabelSelector{MatchLabels:map[string]string{pod: b,},MatchExpressions:[]LabelSelectorRequirement{},},NamespaceSelector:&v1.LabelSelector{MatchLabels:map[string]string{io.cilium.k8s.namespace.labels.ns: y,},MatchExpressions:[]LabelSelectorRequirement{},},IPBlock:nil,},},},NetworkPolicyEgressRule{Ports:[]NetworkPolicyPort{NetworkPolicyPort{Protocol:*UDP,Port:53,},},To:[]NetworkPolicyPeer{},},},PolicyTypes:[Egress],},}" error="Port must be specified" k8sApiVersion= subsys=k8s-watcher
```

I've tested with the fixed policy:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: vary-egress-8-0-0-2-0
 namespace: x
spec:
 egress:
 - to:
   - namespaceSelector:
       matchLabels:
         ns: "y"
     podSelector:
       matchLabels:
         pod: b
 - ports:
   - port: 53
     protocol: UDP
 podSelector:
   matchLabels:
     pod: a
 policyTypes:
 - Egress
```
and this gives the expected results.

**Comment by mattfenwick** [comment]
@aanm thanks for taking a look !

I'm trying to figure out what the netpol spec is, my reading of the comments in https://github.com/kubernetes/api/blob/master/networking/v1/types.go and kubeval seem to say that this should be legal?

```
kubeval --strict netpol.yaml
PASS - ignore/netpol.yaml contains a valid NetworkPolicy (x.vary-egress-8-0-0-2-0)
```

**Comment by aanm** [comment]
> @aanm thanks for taking a look !
> 
> I'm trying to figure out what the netpol spec is, my reading of the comments in https://github.com/kubernetes/api/blob/master/networking/v1/types.go and kubeval seem to say that this should be legal?
> 
> ```
> kubeval --strict netpol.yaml
> PASS - ignore/netpol.yaml contains a valid NetworkPolicy (x.vary-egress-8-0-0-2-0)
> ```

@mattfenwick I think you are right.
```golang
	// List of destination ports for outgoing traffic.
	// Each item in this list is combined using a logical OR. If this field is
	// empty or missing, this rule matches all ports (traffic not restricted by port).
	// If this field is present and contains at least one item, then this rule allows
	// traffic only if the traffic matches at least one port in the list.
	// +optional
	Ports []NetworkPolicyPort `json:"ports,omitempty" protobuf:"bytes,1,rep,name=ports"`
[...]
// NetworkPolicyPort describes a port to allow traffic on
type NetworkPolicyPort struct {
	// The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this
	// field defaults to TCP.
	// +optional
	Protocol *slim_corev1.Protocol `json:"protocol,omitempty" protobuf:"bytes,1,opt,name=protocol,casttype=k8s.io/api/core/v1.Protocol"`

	// The port on the given protocol. This can either be a numerical or named port on
	// a pod. If this field is not provided, this matches all port names and numbers.
	// +optional
	Port *intstr.IntOrString `json:"port,omitempty" protobuf:"bytes,2,opt,name=port"`
}
```
The `netpol.yaml` contains the following:
```
   egress:
   - ports:
     - {}
```
The field `ports` is nor empty nor missing, from the documentation the rule should allow traffic only if the traffic matches at least one port in the list.

Going through the list, we have
```
   - {}
```

Which is a `NetworkPolicyPort` that has the following data:
```
NetworkPolicyPort {
     Protocol: nil,
     Port: nil,
}
```

Both of its fields can be optional, if `Protocol` is not specified then it will match `TCP`, in Port is not set then it will match all port names and numbers.

Thus, the policy `netpol.yaml` should:
- allow all TCP to any ports from pods with the label `pod=a` on `namespace=x` to all pods with in the with the label `pod=b` in the `namespace=y`.
- allow all UDP to port 53 from pods with the label `pod=a` on `namespace=x` to all pods.

The fix should be as simple as this:
```patch
--- a/pkg/k8s/network_policy.go
+++ b/pkg/k8s/network_policy.go
@@ -287,7 +287,7 @@ func parsePorts(ports []slim_networkingv1.NetworkPolicyPort) []api.PortRule {
                        protocol, _ = api.ParseL4Proto(string(*port.Protocol))
                }
 
-               portStr := ""
+               portStr := "0"
                if port.Port != nil {
                        portStr = port.Port.String()
                }
```
Can you submit a PR with the above fix and 1 or 2 test cases that covers this failure?

**Comment by mattfenwick** [comment]
Push a first pass at this to https://github.com/cilium/cilium/pull/14720 -- haven't gotten it all to work yet, something somewhere else rejects the `0`

**Comment by tgraf** [comment]
@mattfenwick Are you still working on this? Would you like somebody else to take over?

**Comment by jrajahalme** [comment]
@aanm would it not be better to leave the `portStr` as an empty string, or do we want to have the same (wildcarding) behavior for a port that is explicitly passed as `0` in the policy?

**Comment by aanm** [comment]
>Or do you mean that we would make this fix for k8s Network Policy only and keep the current behavior for CNP & CCNP?

@jrajahalme looking at CNP & CCNP documentation, there is no reference that we accept an "empty" port. Even the schema validation requires something:
https://github.com/cilium/cilium/blob/2f643770e865a45b9955a931331341a0df429371/pkg/policy/api/l4.go#L34-L44

My proposal is to have this fix only in the k8s network policy since we are not following the specification.

**Comment by mattfenwick** [comment]
hi @tgraf 👋 !!  I got stuck at https://github.com/cilium/cilium/pull/14720#issuecomment-785827059 , happy to pick this up again with some help, if it's easier for you to just take over then that's cool too ... totally fine with this either way!
