### ISSUE TITLE
CI: RuntimeFQDNPolicies toFQDNs populates toCIDRSet (data from proxy) L3-dependent L7/HTTP with toFQDN updates proxy policy

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14676]
https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/3372/testReport/junit/(root)/Suite-runtime/RuntimeFQDNPolicies_toFQDNs_populates_toCIDRSet__data_from_proxy__L3_dependent_L7_HTTP_with_toFQDN_updates_proxy_policy/
[test_results_Cilium-PR-Runtime-4.9_3372_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/5845587/test_results_Cilium-PR-Runtime-4.9_3372_BDD-Test-PR.zip)
From https://github.com/cilium/cilium/pull/14670.

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Runtime-4.9/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Expected
    <string>: <- proxy flow 0x1f45ab63 identity 46726->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.15.2.142:46988 -> 10.15.82.9:9092 tcp ACK, FIN
    xx drop (Stale or unroutable IP) flow 0x1f45ab63 to endpoint 0, identity 46726->unknown: 10.15.2.142:46988 -> 10.15.82.9:9092 tcp ACK, FIN
    <- endpoint 1415 flow 0x23f9688 identity 8310->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:58926 -> 172.17.0.5:53 udp
    Policy verdict log: flow 0x23f9688 local EP ID 1415, remote ID world, proto 17, egress, action redirect, match L4-Only, 10.15.155.20:58926 -> 172.17.0.5:53 udp
    -> proxy flow 0x23f9688 identity 8310->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:58926 -> 172.17.0.5:53 udp
    <- endpoint 1415 flow 0xee62397c identity 8310->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:42016 -> 172.17.0.5:53 udp
    Policy verdict log: flow 0xee62397c local EP ID 1415, remote ID world, proto 17, egress, action redirect, match L4-Only, 10.15.155.20:42016 -> 172.17.0.5:53 udp
    -> proxy flow 0xee62397c identity 8310->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:42016 -> 172.17.0.5:53 udp
    -> Request dns from 1415 ([container:app=test container:id.app1]) to 0 ([reserved:world]), identity 8310->2, verdict Forwarded DNS Query: world1.cilium.test. A
    -> Request dns from 1415 ([container:app=test container:id.app1]) to 0 ([reserved:world]), identity 8310->2, verdict Forwarded DNS Query: world1.cilium.test. AAAA
    -> Response dns to 1415 ([container:app=test container:id.app1]) from 0 ([reserved:world]), identity 8310->2, verdict Forwarded DNS Proxy: world1.cilium.test. AAAA TTL: 4294967295 Answer: ''
    -> Response dns to 1415 ([container:id.app1 container:app=test]) from 0 ([reserved:world]), identity 8310->2, verdict Forwarded DNS Proxy: world1.cilium.test. A TTL: 3 Answer: '172.18.0.2'
    <- proxy flow 0x0 identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: 172.17.0.5:53 -> 10.15.155.20:42016 udp
    -> endpoint 1415 flow 0x0 identity world->8310 state reply ifindex lxc8e07cd01ca52 orig-ip 172.17.0.5: 172.17.0.5:53 -> 10.15.155.20:42016 udp
    <- proxy flow 0x0 identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: 172.17.0.5:53 -> 10.15.155.20:58926 udp
    -> endpoint 1415 flow 0x0 identity world->8310 state reply ifindex lxc8e07cd01ca52 orig-ip 172.17.0.5: 172.17.0.5:53 -> 10.15.155.20:58926 udp
    <- endpoint 1415 flow 0x51a6e2ba identity 8310->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:59888 -> 172.18.0.2:80 tcp SYN
    Policy verdict log: flow 0x51a6e2ba local EP ID 1415, remote ID 16777217, proto 6, egress, action redirect, match L3-L4, 10.15.155.20:59888 -> 172.18.0.2:80 tcp SYN
    -> proxy flow 0x51a6e2ba identity 8310->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:59888 -> 172.18.0.2:80 tcp SYN
    <- proxy flow 0x145ad07b identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: 172.18.0.2:80 -> 10.15.155.20:59888 tcp SYN, ACK
    -> endpoint 1415 flow 0x145ad07b identity 16777217->8310 state reply ifindex lxc8e07cd01ca52 orig-ip 172.18.0.2: 172.18.0.2:80 -> 10.15.155.20:59888 tcp SYN, ACK
    <- endpoint 1415 flow 0x51a6e2ba identity 8310->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:59888 -> 172.18.0.2:80 tcp ACK
    -> proxy flow 0x51a6e2ba identity 8310->unknown state established ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:59888 -> 172.18.0.2:80 tcp ACK
    <- endpoint 1415 flow 0x51a6e2ba identity 8310->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:59888 -> 172.18.0.2:80 tcp ACK
    -> proxy flow 0x51a6e2ba identity 8310->unknown state established ifindex 0 orig-ip 0.0.0.0: 10.15.155.20:59888 -> 172.18.0.2:80 tcp ACK
    <- proxy flow 0x145ad07b identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: 172.18.0.2:80 -> 10.15.155.20:59888 tcp ACK
to contain substring
    <string>: verdict Forwarded GET http://world1.cilium.test/ => 200
/home/jenkins/workspace/Cilium-PR-Runtime-4.9/runtime-gopath/src/github.com/cilium/cilium/test/runtime/fqdn.go:996
```
### Standard Output
```
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 2
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 1
Top 2 errors/warnings:
[[external/envoy/source/common/runtime/runtime_features.cc:20] Unable to use runtime singleton for feature envoy.reloadable_features.activate_fds_next_event_loop
[[external/envoy/source/server/server.cc:537] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
```

**Comment by pchaigno** [comment]
Happened a couple times on master as well: https://datastudio.google.com/s/gfsFHCAmZ3g.

**Comment by nbusseneau** [comment]
This happens almost consistently in the race detection version of the pipeline: https://jenkins.cilium.io/view/Race%20Detection/job/Ginkgo-CI-Tests-runtime-Pipeline-Race-Detection/

**Comment by twpayne** [comment]
I spent a lot of time trying to reproduce this locally so as to be able to debug it with a faster iteration time than waiting for Jenkins/CI. Specifically, I tried multiple tens runs of the test in the VM created by Gingko on both macOS and Linux, including with the race detector enabled, but did not observe a single failure. It looks like this flake might be specific to running on Jenkins.

**Comment by pchaigno** [comment]
@twpayne What ginkgo commands did you run locally?

**Comment by twpayne** [comment]
I ran:

    cd test
    ginkgo -focus="RuntimeFQDNPolicies" -race

(with and without `-race`)

**Comment by pchaigno** [comment]
Ok. Might be worth trying `ginkgo --focus="Runtime"` a couple times in case what runs before matters.

**Comment by twpayne** [comment]
OK, I ran the `ginkgo --focus="Runtime"`in a loop ten times. There were no occurrences of this flake, but it did discover a couple of data races in the use of the Ginkgo test framework. I'll open issues for these.

**Comment by pchaigno** [comment]
The test here is failing because the `cilium monitor` output doesn't contain an expected substring. The previous request has the expected result so we would expect the `cilium monitor` output to contain the corresponding packet traces. The test is flaky (vs. failing consistently) so this is likely some timing issue.

## Investigation

We can use the CI dashboard link at the top to retrieve a more recent example that will still have all the associated data. For example: https://jenkins.cilium.io/job/cilium-master-runtime-quarantine/305/testReport/(root)/Suite-runtime/RuntimeFQDNPolicies_toFQDNs_populates_toCIDRSet__data_from_proxy__L3_dependent_L7_HTTP_with_toFQDN_updates_proxy_policy/.

### According to the packet traces, does Cilium behave as expected?

This test is testing both an FQDN and an HTTP policy. The forwarding of DNS requests through the DNS proxy is visible in the `cilium monitor` logs so we know that the redirect works. We also know that the policy was enforced. It seems unlikely that just the HTTP portion would be failing. So Cilium appears to be behaving as expected.

### Are we just failing to properly match those logs?

Manually going through the short `cilium monitor` output included in the error message shows that we are correctly matching the substring: it is actually missing.

This short output is however only an excerpt from `cilium monitor`'s output for a longer period (reading the test code reveals that `cilium monitor` runs in the background for the whole duration of RuntimeFQDN). So next question:

### Is the expected substring contained in the full `cilium monitor` output?

Do we have that full output first? If we don't, we'll need to add it. Turns out we're in luck and we have it, as `monitor.log` in the artifacts.

If we search for the substring, we can find it, at the very end of the file. It's quite a few lines (100+) below the last line from the `cilium output` excerpt we have in the test failure message, even though both happened on the same second.

```
[2021-04-23 01:42:24] Policy verdict log: flow 0x2b50516b local EP ID 2460, remote ID 16777217, proto 6, egress, action redirect, match L3-L4, 10.15.79.209:60034 -> 172.18.0.2:80 tcp SYN
[...]
[2021-04-23 01:42:24] -> Response http to 2460 ([container:app=test container:id.app1]) from 0 ([reserved:world]), identity 5724->2, verdict Forwarded GET http://world1.cilium.test/ => 200
```

## Root cause

So the expected substring is here but isn't contained in the `cilium monitor` excerpt we use for the match. Looking at the code again shows that we don't wait between the request and when we check the `cilium monitor` output. If we look at other places running `cilium monitor` in tests, we can see that some of them use:
```go
monitorRes.WaitUntilMatch(expectedSubstring)
monitorRes.ExpectContains(expectedSubstring)
```

https://github.com/cilium/cilium/pull/15848 attempts a fix.

**Comment by twpayne** [comment]
Thank you very much for the investigation and explanation.

**Comment by pchaigno** [comment]
https://github.com/cilium/cilium/pull/15848 fixed it. It was merged on the 27th and we can see the effect in the CI dashboard:

![image](https://user-images.githubusercontent.com/1764210/116859361-312de180-ac00-11eb-9faa-33f5491ff686.png)
