### ISSUE TITLE
Create best-practices / requirements for shell scripts

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1470]
In order to have a reliable CI and easy-to-use test infrastructure, we need to install best-practices / requirements for scripts. We can create a document that should be referred to during code reviews and used to fix up existing scripts. For instance we can take from (and credit, of course), the following:
* http://www.davidpashley.com/articles/writing-robust-shell-scripts/
* https://google.github.io/styleguide/shell.xml

**Comment by aalemayhu** [comment]
:+1: would also be nice if this was enforced by tools so contributors don't need to read separate documents to add new tests effectively.

**Comment by ianvernon** [comment]
Closing as we have moved away from Bash scripts for tests.
