### ISSUE TITLE
datapath: Set timeout for default netlink socket

### ISSUE THREAD

**Issue by brb** [cilium/cilium#14710]
As communication over vishvananda/netlink can block indefinitely (see https://github.com/cilium/cilium/pull/14502#issuecomment-756548459 for more details), we need to set a timeout for a netlink socket.

@ArthurChiao is going to open a PR for `vishvananda/netlink` to add a way to set a timeout for a default netlink socket. This would allow us to set the timeout without modifying each netlink invocation in the code base.

**Comment by ArthurChiao** [comment]
Upstream issue: https://github.com/vishvananda/netlink/issues/613

**Comment by brb** [comment]
@ArthurChiao Thanks! Considering that the vishvananda/netlink project is not actively maintained, I'd suggest to open the PR to it, as your issue might get lost.

**Comment by ArthurChiao** [comment]
OK, I'll file a PR, thanks! @brb

**Comment by ArthurChiao** [comment]
Upstream PR: https://github.com/vishvananda/netlink/pull/614, created a few days ago, but hasn't got responded.

**Comment by brb** [comment]
@ArthurChiao Thanks. If we don't get any response from the library maintainers in a few days, then we can temporarily use forked version in `vendor/`.

**Comment by ArthurChiao** [comment]
Hi @brb, upstream PR merged, thanks for your help!

**Comment by brb** [comment]
@ArthurChiao Good news! Let's move on with changes in Cilium :rocket:

**Comment by joestringer** [comment]
FYI #15048 already bumped the netlink library in Cilium codebase to include the upstream PR https://github.com/vishvananda/netlink/pull/614 . So we would just need the Cilium agent side changes now.

**Comment by brb** [comment]
@ArthurChiao Do you plan to work on adding the timeout to the cilium-agent side?

**Comment by ArthurChiao** [comment]
Hi @brb , you mean explicitly configure a timeout value rather using the default one (`60s`) ?

I'd like to help, but I'm not sure what's expected in the next.

**Comment by brb** [comment]
Ah, I think 60s is good enough. Let's close the issue then.
