### ISSUE TITLE
Feature Request: use mattfenwick/cyclonus to test network policies 

### ISSUE THREAD

**Issue by twpayne** [cilium/cilium#14722]
As [discussed on Slack](https://cilium.slack.com/archives/C2B917YHE/p1611353849014400) with @mattfenwick and @aanm .

## Proposal / RFE

**Is your feature request related to a problem?**

https://github.com/mattfenwick/cyclonus is a sophisticated tool for testing Kubernetes `NetworkPolicy`s, and has already found a bug in Cilium's implementation (#14678). It would be fantastic to integrate cyclonus into Cilium's CI to catch problems as early as possible, and to benefit from the rich range of tests in cyclonus.

**Describe the solution you'd like**

As a first step, integrate cyclonus into Cilium's CI. It is possible that some tests will fail (e.g. as identified by #14678) so a mechanism will be needed to mark such failures as expected until Cilium is fixed. As cyclonus expands its range of tests, it might hit expected failures due to, for example [missing functionality in Cilium's implementation of `NetworkPolicy`s](https://docs.cilium.io/en/v1.9/concepts/kubernetes/policy/#k8s-policy).

**Comment by mattfenwick** [comment]
Hi @twpayne , I'm excited to pitch in on this!

👍 👍

**Comment by mattfenwick** [comment]
@twpayne I don't have a solution to https://github.com/mattfenwick/cyclonus/issues/1 yet, **but** I do have a smaller subset of tests that can be run as a k8s job which all currently pass on cilium!! :) 🎉 

What will it look like to run cyclonus in CI for cilium in terms of infra, i.e. should I start putting together a github action to run cyclonus on KinD?  (started looking at https://github.com/cilium/cilium/tree/master/.github/workflows)

**Comment by nebril** [comment]
Hi! This looks like a good candidate for Github Action. I guess we don't need to cover all supported k8s versions (at least in the beginning), so a test run in Kind cluster sounds like a good idea.

I would suggest to base the setup on https://github.com/cilium/cilium/blob/master/.github/workflows/smoke-test.yaml

**Comment by mattfenwick** [comment]
I copied/pasted and added a few things to the smoke-test and put up a WIP to start figuring out the github action part, thanks for the pointer @nebril !
