### ISSUE TITLE
Expose xfrm stats as Prometheus metrics for IPSec

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14725]
When IPSec is enabled, we should expose [xfrm errors](https://www.kernel.org/doc/Documentation/networking/xfrm_proc.txt) as Prometheus metrics. If those counters are increasing, they can be indications of misconfigured keys, corrupted data, etc.

**Comment by Ankurk99** [comment]
@pchaigno I would like to work on this issue.

**Comment by Ankurk99** [comment]
@pchaigno can you please provide some pointers on how may I approach this?

**Comment by pchaigno** [comment]
@Ankurk99 I would find another, recently-added Prometheus metric and follow its implementation.

**Comment by vishjain** [comment]
This seems to be unfinished since January, @pchaigno can I take this up as a first issue? Thanks.

**Comment by sayboras** [comment]
I can give a crack on this :)
