### ISSUE TITLE
Display host firewall status in cilium status

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14749]
Before we move the host firewall out of beta, it would be good to have its status reported in `cilium status`. Ideally, we would also inherit its enforcement status (enabled/disabled/audit, ingress/egress) from the host endpoint. If the host firewall is disabled, we could print its status only in `cilium status --verbose` to reduce noise.

**Comment by AnishShah** [comment]
I would like to work on this.

**Comment by pchaigno** [comment]
@AnishShah I've assigned you. Don't hesitate to reach out on Slack/#development or here if you have any question.

**Comment by AnishShah** [comment]
any idea where do we implement GetHealthz call?

https://github.com/cilium/cilium/blob/90c1acaa557edd101fd0e3bd409f9c643a88efda/cilium/cmd/status.go#L82

**Comment by pchaigno** [comment]
I would say here:
https://github.com/cilium/cilium/blob/90c1acaa557edd101fd0e3bd409f9c643a88efda/api/v1/client/daemon/daemon_client.go#L163

It might be easier to tackle this issue by looking for a commit that implemented a similar feature though. Commit c285ca04757f6caed38c45f84cbe255ce4d34c25, for example, added the host routing status.

**Comment by AnishShah** [comment]
Thanks @pchaigno. That was helpful.

> Ideally, we would also inherit its enforcement status (enabled/disabled/audit, ingress/egress) from the host endpoint

Any idea how do I fetch this information? `options.Config.EnableHostFirewall` will tell me whether enforcement status is enabled or disabled. What about audit, ingress, egress?

**Comment by pchaigno** [comment]
> > Ideally, we would also inherit its enforcement status (enabled/disabled/audit, ingress/egress) from the host endpoint
> 
> Any idea how do I fetch this information? `options.Config.EnableHostFirewall` will tell me whether enforcement status is enabled or disabled. What about audit, ingress, egress?

I'm not sure exactly, but it should be possible given `cilium endpoint list` and `cilium endpoint get -l reverse:host` have this information. Maybe see: https://github.com/cilium/cilium/blob/265d6775c2e0eb4e9d1dfef3ebeaa19a9b976e5f/cilium/cmd/endpoint_get.go#L46-L51

**Comment by pchaigno** [comment]
@AnishShah Are you still working on this? I'd like to get it in 1.10, but can take care of it if you're on other things.

**Comment by AnishShah** [comment]
Sorry @pchaigno. I was not able to make progress on this. Please unassign me
