### ISSUE TITLE
Cilium seems to lose identities, and thus starts dropping flows

### ISSUE THREAD

**Issue by csomm** [cilium/cilium#14775]
## Bug report

**General Information**

- Cilium version (run `cilium version`)

> Client: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64
> Daemon: 1.9.1 975b66772 2020-12-04T18:16:09+01:00 go version go1.15.5 linux/amd64

- Kernel version (run `uname -a`)

> Linux aks-sys-13759587-vmss000005 4.15.0-1103-azure #114~16.04.1-Ubuntu SMP Wed Dec 16 02:39:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-17T02:13:01Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}

> Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T15:59:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**How to reproduce the issue**

The cluster is an AKS cluster on Azure.

We are not sure how to reproduce the issue, but we had a problem with Cilium losing identities (and endpoints) of pods for some time with Cilium 1.8. When this happens, the flows of the corresponding pods get dropped (policy denied). Deleting the pods works around the issue, because then the new pods get new Cilium identities and Cilium endpoints, and the network policies work as expected again. But after some time the issue appears again.

We thought the issue was #14284 , so we upgraded to Cilium 1.9.1 yesterday (Jan 27 2021) evening. The upgrade went fine, the network policies worked as expected after the upgrade (i.e. we saw no unexpected policy denied flows). Then early next morning (Jan 28 2012) around 5:14 UTC a lot of unexpected dropped flows appeared in the Hubble metrics dashboard and at least three pods (gatekeeper-system/gatekeeper-controller-5948ddcd54-lzkvc, gatekeeper-system/gatekeeper-audit-7b4bc6f977-blsh4 and kube-system/metrics-server-7f5b4f6d8c-6qb29) on one node (aks-sys-13759587-vmss000005) had lost their identities and their flows got denied. The metrics-server pod then entered a crash loop, because it couldn't connect to the API server (DNS requests got denied).

After deleting the gatekeeper pods, they were recreated, got new Cilium endpoints and worked fine again. After that we created the Cilium sysdump, that I will attach to the bug report. The sysdump is from the affected node. We also have a sysdump of the whole cluster, please let me know, if you need that. 

Here are come examples of dropped flows of the metrics-server pod (which still has the problem):
```
Jan 28 15:54:24.070: 10.15.83.24:53542 -> kube-system/coredns-54fcbb59b6-mwwq7:53 Policy denied DROPPED (UDP)
Jan 28 15:54:24.070: 10.15.83.24:53542 -> kube-system/coredns-54fcbb59b6-mwwq7:53 Policy denied DROPPED (UDP)
Jan 28 15:54:24.070: 10.15.83.24:57304 -> kube-system/coredns-54fcbb59b6-mwwq7:53 Policy denied DROPPED (UDP)
Jan 28 15:54:24.070: 10.15.83.24:57304 -> kube-system/coredns-54fcbb59b6-mwwq7:53 Policy denied DROPPED (UDP)
Jan 28 15:54:29.070: 10.15.83.24:51933 -> kube-system/coredns-54fcbb59b6-b6x9s:53 Policy denied DROPPED (UDP)
Jan 28 15:54:29.070: 10.15.83.24:51933 -> kube-system/coredns-54fcbb59b6-b6x9s:53 Policy denied DROPPED (UDP)
Jan 28 15:54:29.070: 10.15.83.24:53433 -> kube-system/coredns-54fcbb59b6-b6x9s:53 Policy denied DROPPED (UDP)
Jan 28 15:54:29.070: 10.15.83.24:53433 -> kube-system/coredns-54fcbb59b6-b6x9s:53 Policy denied DROPPED (UDP)
```
```
> kubectl get pods -A -owide |grep 10.15.83.24
kube-system                   metrics-server-7f5b4f6d8c-6qb29                                  0/1     CrashLoopBackOff   176        3d      10.15.83.24    aks-sys-13759587-vmss000005       <none>           <none>
```
And the command
```
kubectl get ciliumendpoints -A |grep 10.15.83.24
```
does not produce any output.

The issue seems to start mostly in the early morning and seems to be related to some suddenly appearing network problems. (Maybe some Azure/AKS related maintenance? We don't really know.) When looking into the systemd journal of the node at the time the issue started, it seems that the kubelet connections to the API server got terminated and new connection attempts resulted in "connection refused" for a brief amount of time. I will attach an excerpt of the journal from the node.

[cilium-sysdump-20210128-104820.zip](https://github.com/cilium/cilium/files/5888680/cilium-sysdump-20210128-104820.zip)
[journal_aks-sys-13759587-vmss000005.txt](https://github.com/cilium/cilium/files/5888687/journal_aks-sys-13759587-vmss000005.txt)

**Comment by pchaigno** [comment]
I'm assuming the policy drops are on egress?

I see a single policy for the metrics-server. Is that correct?
```
  spec:
    egress:
    - toEntities:
      - host
      - remote-node
      toPorts:
      - ports:
        - port: "10250"
          protocol: TCP
    endpointSelector:
      matchLabels:
        k8s:k8s-app: metrics-server
```
Unless they are running in host network namespace, it doesn't seem to allow egress to the coredns pods.

**Comment by csomm** [comment]
The metrics-server and coredns pods are running in the kube-system namespace, and we have the following network policy to allow all intra-namespace communication:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-internal
  namespace: kube-system
spec:
  egress:
  - toEndpoints:
    - {}
  endpointSelector: {}
  ingress:
  - fromEndpoints:
    - {}
```
The metrics-server is not running in the host network. I just deleted it (and made no other changes), and now it is running fine again:
```
> kubectl get pod -n kube-system -owide |grep metrics-server
metrics-server-7f5b4f6d8c-wgn9f        1/1     Running   0          38s    10.15.82.223   aks-sys-13759587-vmss000003       <none>           <none>
```
And now we also have a Cilium endpoint for the pod again:
```
> kubectl get ciliumendpoints -A |grep 10.15.82.223
kube-system                   metrics-server-7f5b4f6d8c-wgn9f                                  877           32694                                                                        ready            10.15.82.223   
```
And we don't see any dropped flows for the pod, and the DNS requests get forwarded to the coredns pods, and `hubble observe` correctly resolves the IP of the pod to its name, e.g.:
```
Jan 28 17:29:26.346   kube-system/metrics-server-7f5b4f6d8c-wgn9f:44601       kube-system/coredns-54fcbb59b6-zxf4k:53                 L3-L4          FORWARDED   UDP
Jan 28 17:29:26.346   kube-system/metrics-server-7f5b4f6d8c-wgn9f:44601       kube-system/coredns-54fcbb59b6-zxf4k:53                 to-proxy       FORWARDED   UDP
Jan 28 17:29:26.346   kube-system/metrics-server-7f5b4f6d8c-wgn9f:36905       kube-system/coredns-54fcbb59b6-mwwq7:53                 L3-L4          FORWARDED   UDP
Jan 28 17:29:26.346   kube-system/metrics-server-7f5b4f6d8c-wgn9f:36905       kube-system/coredns-54fcbb59b6-mwwq7:53                 to-proxy       FORWARDED   UDP
```
So I assume the problem was indeed, as describes above, that the Cilium endpoint (and identity) were missing for the pod. 

This is exactly the same behavior we observed with the gatekeeper pods on the same node. And all of this started today (Jan 28 2012) at about 5:14 UTC. At that time nobody was working on the cluster. From our point of view, this happened on its own, maybe related to some AKS related maintenance in the background. I think in the past this also happened around this time early in the morning.

**Comment by pchaigno** [comment]
The ipcache map has the following information for metrics-server:
```
10.15.83.24/32       3 0 0.0.0.0            sync
```
Meaning the pod has identity `UNMANAGED`. That can happen when a pod is created before Cilium is running. When was the last restart of the Cilium agent on that node? Could it match when the pod lost its previous identity?

**Comment by csomm** [comment]
Here is the timeline of events:

On Jan 25 2021 we made a Kubernetes upgrade on the cluster (control plane and node pools), which created a new metrics-server pod (metrics-server-7f5b4f6d8c-6qb29) at about 2021-01-25T16:52:36+01:00 (first log message of that pod instance). The pod worked fine after that (no dropped flows). At that time Cilium 1.8.6 was running in the cluster.

Then on Jan 27 2021 17:20 UTC we deployed Cilium 1.9.1, which went fine too, and the metrics-server continued to work fine (again no dropped flows).

Then on Jan 28 2012 5:14 UTC the metrics-server pod lost its connection to the API server, crashed and entered the crash loop (according to the pod logs). This was the same time when Cilium started to drop flows for the pod (according to the metrics in the Hubble dashboard). But I cannot really tell, if the connection loss to the API server was caused by dropped flows, or if the connection loss was caused by something else, and the dropped flows just happened after the pod was restarted. Looking at the node journal/syslog I can see that the kubelet on that node also lost its connection to the API server at 5:14 UTC, and got a connection refused error for a brief moment when trying to reconnect to the API server, but then recovered.

A couple of hours later we noticed that the pod was in a crash loop, noticed the aforementioned dropped flows on the Hubble dashboard, and tried to find out what was happening. At that point of time we noticed that the metrics-server (and gatekeeper pods) on this node had no Cilium endpoints. Deleting those pods brought things back to normal (no dropped flows).

The Cilium agent on that node had no restarts since the deployment of Cilium 1.9.1:
```
> kubectl get pods -n sys-cilium -owide |grep aks-sys-13759587-vmss000005| grep "cilium-"
cilium-68jgz                       1/1     Running   0          40h     10.15.83.16    aks-sys-13759587-vmss000005       <none>           <none>
cilium-node-init-xmdsq             1/1     Running   0          40h     10.15.83.16    aks-sys-13759587-vmss000005       <none>           <none>
cilium-operator-796799fd69-rxtwp   1/1     Running   1          40h     10.15.83.16    aks-sys-13759587-vmss000005       <none>           <none>
```
```
> kubectl get pod -n sys-cilium cilium-68jgz -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "9092"
    prometheus.io/scrape: "true"
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: "2021-01-27T17:20:23Z"

[...]

status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-27T17:20:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-27T17:20:40Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-27T17:20:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-27T17:20:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://1df01bd93f03a2f825e96f6e190dc3f66402d154f809b2a07d312afbf2d17b2d
    image: quay.io/cilium/cilium:v1.9.1
    imageID: docker-pullable://quay.io/cilium/cilium@sha256:04734c47c93dd7dd7198bff555ab5b03943abd22a07124b37cdc44fe8a6ad731
    lastState: {}
    name: cilium-agent
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-01-27T17:20:26Z"
  hostIP: 10.15.83.16
  initContainerStatuses:
  - containerID: docker://57de68707279a5fdb681054ca329c0dc8d9f4fd6922faba9e9943c2fe47749e2
    image: quay.io/cilium/cilium:v1.9.1
    imageID: docker-pullable://quay.io/cilium/cilium@sha256:04734c47c93dd7dd7198bff555ab5b03943abd22a07124b37cdc44fe8a6ad731
    lastState: {}
    name: wait-for-node-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://57de68707279a5fdb681054ca329c0dc8d9f4fd6922faba9e9943c2fe47749e2
        exitCode: 0
        finishedAt: "2021-01-27T17:20:24Z"
        reason: Completed
        startedAt: "2021-01-27T17:20:24Z"
  - containerID: docker://bd30b3159ff76bd4b116eb9db1772854e3cd526a8957f56b1f60d5d4772586ac
    image: quay.io/cilium/cilium:v1.9.1
    imageID: docker-pullable://quay.io/cilium/cilium@sha256:04734c47c93dd7dd7198bff555ab5b03943abd22a07124b37cdc44fe8a6ad731
    lastState: {}
    name: clean-cilium-state
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://bd30b3159ff76bd4b116eb9db1772854e3cd526a8957f56b1f60d5d4772586ac
        exitCode: 0
        finishedAt: "2021-01-27T17:20:25Z"
        reason: Completed
        startedAt: "2021-01-27T17:20:25Z"
  phase: Running
  podIP: 10.15.83.16
  podIPs:
  - ip: 10.15.83.16
  qosClass: Burstable
  startTime: "2021-01-27T17:20:23Z"
```

**Comment by jaffcheng** [comment]
Hi @csomm , I think we are facing a similar issue, would be nice if you could help checking cilium-operator log to see if lost identities were GCed by the operator. BTW, what is your kvstore backend, and did it happened to lose connection with the operator at that period of time?

**Comment by csomm** [comment]
Hi @jaffcheng , I'm not sure how I can easily check which of the GCed identities was for which pod. The logs show only the ID. And we are not running in kvstore mode but in CRD mode. But yes, the cilium-operator lost the connection to the API server on on Jan 28 2012 5:14 UTC, when the problems with dropped flows started happening.

But I'm trying to find out when Cilium endpoints were created or deleted by checking the API server audit log, and I connect find any API requests for Cilium endpoints for metrics-server-7f5b4f6d8c-6qb29 (time span from Jan 25, before the Kubernetes upgrade, to Jan 28, after the problems with the dropped flows began). Which seems so suggest that the metrics-server-7f5b4f6d8c-6qb29 was unmanaged the whole time since the Kubernetes upgrade. But then I don't understand why the pod had no dropped flows at first, and the dropped flows only started happening after about 2.5 days.

The next thing is, that we have some default taints on the node pool, which should prevent pods like the metrics-server from getting scheduled on a new node as long as Cilium is not ready. Only after the CNI configuration is correct and Cilium is ready, the taint gets removed. And as far as I can see, the metrics-server pod has no tolerations, which could undercut our mechanism, so this also makes me wonder how the pod could be unmanaged from the beginning. I will try to analyse our logs more in depth, to see if the metrics-server pod got scheduled on the new node before or after Cilium was ready.

**Comment by jaffcheng** [comment]
Hi, @csomm , just FYI, my issue turned out to be related to the kvstore lease, which might not be your case. When somehow our cilium-agent fails to keep the etcd keys (that represent cilium endpoints) alive, they are deleted by etcd, and then identities are GCed by the operator. Sorry for the noise.
