### ISSUE TITLE
Make sure that all runtime / k8s tests have 'set -e' option enabled

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1477]
Make sure that all tests have `set -e` inside of them and also have a script that checks for this option in each test and fails the build if the option is not set.

**Comment by ashwinp** [comment]
I'd suggest adding the `set -u` to catch unbound variables as well.

**Comment by ianvernon** [comment]
This has done by `tests/00-script-linter.sh` in commit 75b7d94be3e37158ec07e8edd079af98c7d9c69a .  Closing.
