### ISSUE TITLE
continue leveraging kubernetes annotations to store operational data?

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1480]
We have been leveraging kuberentes components annotations to store some metadata for cilium usage. Since this is only used by cilium, should we still leverage the k8s annotations to store that metadata?

Accordingly with https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
we can use annotations to store data but it also states:

>Instead of using annotations, you could store this type of information in an external database or directory, but that would make it much harder to produce shared client libraries and tools for deployment, management, introspection, and the like.

I just thought we could move the metadata we have been leveraging to the kvstore, this way we could leverage the same code to sync this metadata for different deployments besides k8s.

Thoughts?

**Comment by tgraf** [comment]
> I just thought we could move the metadata we have been leveraging to the kvstore, this way we could leverage the same code to sync this metadata for different deployments besides k8s.

Adding support to store this in a kvstore is a no brainer as we'll need it for environments like Mesos/Marathon. We should file a ticket and target it for 0.12 if possible.

I do like the coupling of annotations with the resources as it makes lifecycle management of annotated data very simple. It also simplifies verification whether the data that is being annotated correctly correlates to the k8s resource (node, pod, ...). A simple example where this is valuable is node resource annotations if the node disappears the annotation will disappear as well. We never have to keep the state in the kvstore in sync with changes in k8s resources. Same for pods.

So my opinion is that while we should definitely add support for kvstore based annotations, the coupling with resources has some advantages in terms of simplification of the problem.

**Comment by nebril** [comment]
Would it make sense to write custom k8s controller which would sync data from k8s objects into the kvstore (and possibly the other way around)?

**Comment by tgraf** [comment]
> Would it make sense to write custom k8s controller which would sync data from k8s objects into the kvstore (and possibly the other way around)?

If possible, we should avoid storing persistent state in multiple places. It only complicates the handling when the state gets out of sync.

**Comment by aanm** [comment]
@raybejjani your PR #2772 will deprecate this

**Comment by raybejjani** [comment]
It could supersede this for endpoints, yes. My implementation suffers from the sync problem, however, so in that sense it is more complex than a simple annotation on the pod would be. 

In the context of non-k8s platforms, this does raise a question about #2772. Do we have one-off controllers per runtime we work with or do they store data into something generic and that generic thing is a CRD with k8s but could be a kvstore or whatever.

**Comment by tgraf** [comment]
Node annotations are not longer required with #4270

**Comment by tgraf** [comment]
Only essential data that is required to establish kvstore connectivity is still stored in annotations.
