### ISSUE TITLE
ipam/aws/eni: IP allocation silently failing when using "unsupported" instance types

### ISSUE THREAD

**Issue by mvisonneau** [cilium/cilium#14802]
## Bug report

As I attempted to get CIlium to run onto arm64 EC2 instances of the `t4g` family with IPAM/ENI mode, I encountered an issue where the agent is waiting for the operator to allocate new addresses indefinitely.

agent logs on the `t4g.large` instance:

```json
{"level":"info","msg":"Successfully synchronized CiliumNode custom resource","name":"ip-10-6-29-165.eu-west-1.compute.internal","subsys":"ipam"}
{"available":0,"helpMessage":"Check if cilium-operator pod is running and does not have any warnings or error messages.","level":"info","msg":"Waiting for IPs to become available in CRD-backed allocation pool","name":"ip-10-6-29-165.eu-west-1.compute.internal","required":10,"subsys":"ipam"}
```

operator logs:

```json
{"level":"info","msg":"Discovered new CiliumNode custom resource","name":"ip-10-6-29-165.eu-west-1.compute.internal","subsys":"ipam"}
```

I tried to scale out existing autoscaling groups of a knowingly working instance type: `m5.large` (amd64), and surprisingly got into the same issue.

After removing the `t4g.large` from the cluster and it's associated CiliumNode resource, the operator managed to allocate ip addresses over the `m5.large` successfully.

I then looked at the following file: https://github.com/cilium/cilium/blob/8531ff82215943beb12650b784d2255bfae313db/pkg/aws/eni/limits/limits.go#L40

I tried to add another `arm64` instance type which was referenced into it: `m6g.large`. And this time it worked perfectly.

What is surprising is:
1. The lack of errors and/or warnings showing up on the operator's logs.
2. The fact that it seems to completely break the IP allocation for whole cluster

I haven't gone any further for now but I will follow up on this with more details next week! We briefly talked about it on Slack with @joestringer https://cilium.slack.com/archives/C53TG4J4R/p1611607263013800

**General Information**

- Cilium version: `v1.9.3`
- Kernel version: `5.4.0-1037-aws`
- Orchestration system version in use: `EKS v1.18.9`

**How to reproduce the issue**

1. Register an EC2 instance of the `t4g` family
2. Validate that no errors is showing up from the cilium-controller yet no IP allocation is occurring anymore

**Comment by christarazi** [comment]
Thanks for filing the issue. 

> The lack of errors and/or warnings showing up on the operator's logs.

Yes, I think properly logging this is a good solution.

**Comment by mvisonneau** [comment]
with `--update-ec2-adapter-limit-via-api=true`, it works correctly 👍

**Comment by christarazi** [comment]
I added this as a good-first-issue. One potential solution is to log a msg when an "unsupported" instance type is detected and say something along the lines of "consider setting `--update-ec2-adapter-limit-via-api=true`".
