### ISSUE TITLE
cilium may not pick intended mtu when there are multiple interfaces

### ISSUE THREAD

**Issue by nnbu** [cilium/cilium#14829]
## Bug report

I have multiple VMs connected over vxlan. vxlan interface is created for this purpose on the VM. vxlan interface has mtu of 1410, whereas ens4 interface has mtu of 1460. 

So, I am expecting cilium to pickup mtu of vxlan device. But instead, cilium picks up the mtu of ens4.

level=info msg="Establishing connection to apiserver" host="https://172.26.232.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Inheriting MTU from external network interface" device=ens4 ipAddr=10.128.0.8 mtu=1460 subsys=mtu
...
level=info msg="Retrieved node information from kubernetes node" nodeName=abm-cp3 subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=10.200.0.5 ipAddr.ipv6="<nil>" k8sNodeIP=10.200.0.5 nodeName=abm-cp3 subsys=k8s v4Prefix=192.168.2.0/24 v6Prefix="<nil>"

As per the log above, cilium connects to api server first, then picks up the mtu of ens4, and then it retrieves node information from kubernetes node. 

I see 2 issues as per the code.

1. firstGlobalAddr() gets excluded IP list from GetExcludedIPs(). GetExcludedIPs() checks only for devices whose link state is UP. For vxlan devices, this state is unknown.

     vxlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state **UNKNOWN** group default qlen 1000
      inet 10.200.0.4/24 scope global vxlan0

     This UNKNOWN state looks to be due to vxlan driver not publishing the state properly.

2. I explicitly allowed vxlan devices not to be added in excluded IP list, as mentioned above. So, firstGlobalAddr() logic is to get all the interface ip addresses, and sort them. and then it picks up the first ip address. This makes the chosen interface random. This can be avoided by having preferredIP argument filled in properly while calling firstGlobalAddr(). But as the logs (pasted initially) show node information is received later. and 'mtu' is decided earlier. So, at this time, there is not preferredIP.

I am using cilium version 1.8.2. But issue might affect other versions too.

**Comment by liuyuan10** [comment]
The key problem here today is that cilium doesn't pick MTU based on k8s node IPs. When there are multiple interfaces, there is always chance cilium picks the wrong MTU in current state. --mtu and --device flag can help to workaround but doesn't solve the problem for those with different configurations on nodes.

Is it the right direction to always wait for k8s node information before setting MTU and use k8s node IP as preferred IP?

**Comment by brb** [comment]
@nishantburte Does passing `--mtu` resolve the issue?

@liuyuan10 Let's move discussion to #14399, as it's a different issue.

**Comment by liuyuan10** [comment]
@brb We think it's the same issue of #14339. passing --mtu will work but that's not what we want. Let's close this one and move to #14339

**Comment by brb** [comment]
> We think it's the same issue of #14339

My reasoning was that #14829 is about the MTU detection code ignoring ifaces with the UNKNOWN state, while #14339 is about the MTU code ignoring `--devices` setting. In any case, #14339 should resolve #14829, so I agree - let's close it.
