### ISSUE TITLE
Add ability to disable NodePorts for LoadBalancer services and NodePort services with ExternalIPs

### ISSUE THREAD

**Issue by RaveNoX** [cilium/cilium#14857]
## Proposal / RFE
Hello! 

It will be nice to have ability to disable NodePort for LoadBalancer services and NodePort services with ExternalIPs specified.
This request is related with [Kubernetes KEP-1864](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1864-disable-lb-node-ports) but also extends it for ExternalIPs enabled services.

It may be useful for Internet facing Bare-Metal installations.

Setting may be implemented on cluster level or by annotations on the service level, or using both approaches.

**Comment by brb** [comment]
@RaveNoX Thanks for opening the issue. Are you aware of https://github.com/cilium/cilium/pull/14465? Can you check whether `spec.allocateLoadBalancerNodePorts` can be set for services with externalIPs? If yes, then adding this to cilium should be trivial. /cc @fristonio

**Comment by RaveNoX** [comment]
looks like  #14465 works fine for services with `type=LoadBalancer` with externalIPs defined

**Comment by brb** [comment]
@RaveNoX Thanks for the update. Can this issue be closed then?

**Comment by RaveNoX** [comment]
Yes, sorry, closing.
