### ISSUE TITLE
Extend kernel requirements description for transparent encryption

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14852]
This page doesn't describe the kernel config requirements for transparent encryption:

https://docs.cilium.io/en/v1.9/operations/system_requirements/#linux-kernel

Transparent encryption presumably needs at least `CONFIG_XFRM`, maybe other parameters as well.

**Comment by Vesnica** [comment]
Kernel config flag should be set as below:
```
CONFIG_XFRM=y
CONFIG_XFRM_OFFLOAD=y
CONFIG_XFRM_ALGO=m
CONFIG_XFRM_USER=m
CONFIG_INET_ESP=m
CONFIG_INET_TUNNEL=m
CONFIG_INET_XFRM_MODE_TRANSPORT=m
CONFIG_INET_XFRM_MODE_TUNNEL=m
CONFIG_CRYPTO_AEAD=y
CONFIG_CRYPTO_AEAD2=y
CONFIG_CRYPTO_GCM=m
CONFIG_CRYPTO_CBC=y
CONFIG_CRYPTO_HMAC=y
CONFIG_CRYPTO_SHA256=y
CONFIG_CRYPTO_AES=y
CONFIG_CRYPTO_DES=m

```
Note: 5.10.x kernel removed ipsec related config entry(like: CONFIG_INET_XFRM_MODE_TRANSPORT and CONFIG_INET_XFRM_MODE_TUNNEL), these modules maybe integrated directly into the kernel(I'm not sure), but other flags(especially crypto related) must be set as stated above.

**Comment by ReillyTevera** [comment]
@Vesnica Are there any issues if the following are modules (`m`) instead of `y`?
```
CONFIG_CRYPTO_AEAD
CONFIG_CRYPTO_CBC
CONFIG_CRYPTO_AES
```

**Comment by Vesnica** [comment]
@ReillyTevera both should work.
