### ISSUE TITLE
Discrepancy in available IPs between cilium status and hostScopeAllocator behavior

### ISSUE THREAD

**Issue by lbernail** [cilium/cilium#14866]
Hello,

We've noticed a discrepancy between the available IPs reported by the agent and the IPs that can really be allocated when using PodCIDR IPAM.

When we allocate a /28 to a node:
- Cilium status reports that 15 IPs are allocatable (probably from https://github.com/cilium/cilium/blob/641c0f9b3072a014c9541ecaa4e00a2b24c98d97/pkg/ip/ip.go#L34-L45)
- however the ipallocator from kubernetes (forked in cilium/ipam) does not use the base and network address (https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/service/ipallocator/allocator.go#L57-L72) which means only 14 IPs are usable

This is a bit misleading because Cilium status will report 14/15 addresses used, but allocation will fail with:
```
unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  range is full
```

I assume a simple patch would be to modify CountIPsInCIDR (and substract 2 instead of 1). However it might be better to change the ipallocator to avoid wasting an IP? (pretty sure this should work on GCP with IP alias ranges but this allocator may be used in other setups where it could be a problem)

**Comment by aanm** [comment]
This issue hasn't seen any comment for over three years. Closing it due lack of interest.
