### ISSUE TITLE
Throw error if IPSec key changed but key ID didn't

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14873]
The key rotation for transparent encryption should always be performed with a new key ID [as per the documentation](https://docs.cilium.io/en/latest/gettingstarted/encryption/#key-rotation). When reading the IPSec key, we should throw an error if we detect that the key changed while the key ID didn't.

The key is loaded in [`loadIPSecKeys()`](https://github.com/cilium/cilium/blob/5b911b80127d7d79120252334b92f7fd6495831c/pkg/datapath/linux/ipsec/ipsec_linux.go#L445) and we compare the key IDs at: https://github.com/cilium/cilium/blob/5b911b80127d7d79120252334b92f7fd6495831c/pkg/datapath/linux/ipsec/ipsec_linux.go#L548

- [ ] Implement the error case.
- [ ] Test it by doing a key rotation with an unchanged key ID.
- [ ] Add a unit test in [`ipsec_linux_test.go`](https://github.com/cilium/cilium/blob/5b911b80127d7d79120252334b92f7fd6495831c/pkg/datapath/linux/ipsec/ipsec_linux_test.go).

**Comment by msune** [comment]
@pchaigno, some questions:

* Does it make sense to move it to Community cilium?
* Are you actively working on this?
