### ISSUE TITLE
Helm chart should not fail on prometheus CRDs

### ISSUE THREAD

**Issue by matoszz** [cilium/cilium#14875]
## Proposal / RFE

Small feature request... folks who are using your helm chart to install may not have the prometheus CRD's present but would still like to render the chart out and have the service monitors output. If the chart fails to render entirely due to the presence (or not) of prometheus CRDs, how would one get the service monitors to install if prometheus is setup _after_ cilium? Would be great to not have the validate component of the helm chart hard fail just because a dependency is not toggled on.

**Comment by joestringer** [comment]
From Cilium community meeting: Background on this is that the Cilium charts were getting out of sync with the upstream Prometheus CRDs, and it's not really Cilium's responsibility to manage prometheus CRD installation. A good approach would be to improve the Cilium documentation with clearer instructions how to bootstrap this in the Cilium docs for prometheus, probably on this page:

https://docs.cilium.io/en/stable/operations/metrics/

Related discussion:

https://github.com/cilium/cilium/pull/13549
