### ISSUE TITLE
Upgrade/downgrade test for patch releases

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14882]
On master, K8sUpdates tests the transition from master to the development branch of our latest stable release and back. For example on current master, [it tests](https://github.com/cilium/cilium/blob/265d6775c2e0eb4e9d1dfef3ebeaa19a9b976e5f/test/k8sT/Updates.go#L124-L129): `master -> v1.9 -> master`. On [the v1.9 development branch](https://github.com/cilium/cilium/tree/v1.9), K8sUpdates [tests](https://github.com/cilium/cilium/blob/v1.9/test/k8sT/Updates.go#L113-L119) the transition `v1.9 -> v1.8 -> v1.9`.

We should also test transitions between patch versions. Our latest v1.9.x release is v1.9.4, so on v1.9, K8sUpdates should test the transition `v1.9 -> v1.9.4 -> v1.9`. When we release a new patch version, we would update the test accordingly to always test the transition to/from the latest patch release.

On master, the test for patch releases would be disabled as we usually don't have corresponding patch releases.

This issue is a matter of:
- [ ] Running K8sUpdates locally by following [the documentation](https://docs.cilium.io/en/latest/contributing/testing/e2e/#running-kubernetes-tests).
- [ ] Adding a new `It` block in `K8sUpdates.go` to test the above transition.
- [ ] Validating by running the test again.

The new test can be developed on master with the transition `v1.9 -> v1.9.x -> v1.9` (on whatever the latest stable minor release is at the time of development). We will then disable it on master and enable it only in backports.

**Comment by ti-mo** [comment]
@brb is tackling this in ci-e2e: https://github.com/cilium/cilium/pull/25790. Set this issue to close when merged.

**Comment by qmonnet** [comment]
{Up/down}grade from patch release was merged to `main`, the 3 related backport PRs are pending the last reviews/CI checks.

**Comment by qmonnet** [comment]
Tests have been merged on all branches (#28815, #28876, #29003, #29005). Happy to close this as completed.
