### ISSUE TITLE
Upgrade/downgrade test with non-default options

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14884]
Apart for a few exceptions, our [current upgrade/downgrade test](https://github.com/cilium/cilium/blob/master/test/k8sT/Updates.go) runs with Cilium's default Helm options. We should also run the same test with non-default options (e.g., `endpointRoutes.enabled=true`, `tunnel=disabled`, `encryption.enabled=true`, `remoteNodeIdentity=false`).

Related: https://github.com/cilium/cilium/issues/14883 and https://github.com/cilium/cilium/issues/14882.

**Comment by julianwiedmann** [comment]
@brb wdyt, do we have enough progress in the upgrade workflows to close this issue out? Or are there still tasks remaining that we should list here?

**Comment by pchaigno** [comment]
I don't think we cover `remoteNodeIdentity` and that has caused upgrade issues in the past (a long time ago though).

**Comment by julianwiedmann** [comment]
> I don't think we cover `remoteNodeIdentity` and that has caused upgrade issues in the past (a long time ago though).

At least for `main` that's no concern anymore :grin: https://github.com/cilium/cilium/pull/31228

**Comment by brb** [comment]
Yep, we can close it - ci-e2e-upgrade, ci-ipsec-ugprade, ci-clustermesh do test the upgrade/downgrade with non-defaults.
