### ISSUE TITLE
Embed cni-(un)install.sh behaviour in the agent process instead

### ISSUE THREAD

**Issue by ti-mo** [cilium/cilium#14892]
# Proposal

The behaviour introduced [in this PR](https://github.com/cilium/cilium/pull/14192) caused some custom CNI deployments to break. Example: https://github.com/cilium/cilium/issues/14838. This also broke the deployment script bundled with `microk8s` (cc @joestringer), which we do aim to keep in a working state, although not being a part of this repo.

Since this was considered a (possibly) breaking change for some deployments, we didn't backport to 1.9 and earlier. Now we have some extra data points of how and where this can break, the scope for a refactor of `cni-(un)install.sh` has become clearer. Below is a blueprint of the work to be done.

Additionally, this behaviour needs some documentation in general, and Cilium's touch points with the CNI stack need to be more clearly defined. Currently, reading the script is required to understand how to correctly integrate Cilium with custom nodepool images.

## Baseline

A few rules we should aim for with the new implementation:

- `/etc/cni/net.d` should no longer written to by `cni-(un)install.sh`
- A CNI config is only installed by the agent when Cilium is ready
- `--read-cni-conf` and `--write-cni-conf-when-ready` and the machinery behind it should be used as the central code path behind managing a CNI config.
- Must implement CNI-exclusive mode (agent renames all non-Cilium CNI's to `*.cilium_bak`)
- Must implement CNI config cleanup right before agent stops

Misc:
- `cni-(un)install.sh` could be renamed to `k8s-poststart.sh` and `k8s-prestop.sh` if it no longer touches CNI resources. There are some leftover bits in there that shell out to `ip` for Flannel chaining and whatnot that we might need to preserve, but are not that critical.

## Scenarios to support

Below is a list of deployment/configuration scenarios we want to support. These scenarios were established by looking at the use cases of our users, as well as some bug reports we've received.

### 100% Cilium-managed (default)

Cilium takes full ownership of `/etc/cni/net.d/` on the host and takes exclusivity. A 'custom' CNI config can still be specified by pointing `--read-cni-conf` at a file by e.g. mounting a ConfigMap into the container, or by provisioning a template file on the host where the agent can access it. (e.g. using cloud-init)

-> Helm `cni.manual=false` (default)
-> Helm `cni.exclusive=true` (default)

- An appropriate CNI config is automatically chosen based on the chaining config when `--read-cni-conf` is empty. (default)
- If `--read-cni-conf` is set, read the file at the given path instead of automatically choosing one
- The selected config is written to `--write-cni-conf`'s path (default `/etc/cni/net.d/05-cilium.conf(list)

### Unmanaged/manual/custom CNI mode

Cilium doesn't touch `/etc/cni/net.d/` in any way. neither at startup nor during shutdown.

-> Helm `cni.manual=true` set, but also needs to obey existing `CILIUM_CUSTOM_CNI_CONF` for compatibility purposes.

- Disables all interactions with `/etc/cni/net.d/`, but still debating whether or not to still install the `cilium-cni` binary.
- `--read-cni-conf` and `--write-cni-conf..` should remain empty, but will be ignored either way

### Non-exclusive CNI

Cilium installs and cleans up its own CNI config when the agent is ready, but doesn't touch any others.

-> `cni.manual=false` (default)
-> `cni.exclusive=false` -> no CNI exclusivity

- A fitting CNI config is chosen at runtime just like in managed mode
- `--write-cni-conf..` and `--read-cni-conf` are obeyed

## Alternate proposal: `cilium cni`

Instead of embedding the logic into the agent daemon itself, create `cilium cni install/uninstall` commands to use as postStart and preStop respectively. This would be a simple lift&shift from the current shell scripts.

- `install`
  - Remove existing/active Cilium config(s)
  - Rename non-Cilium CNI configs to `*.cilium_bak`
  - Copy Cilium's CNI binary from the container to the host file system
  - Write out appropriate CNI config for the current environment
- `uninstall`
  - Remove active Cilium config
  - Remove Cilium CNI binary

@aanm

**Comment by aanm** [comment]
@ti-mo great write-up.

Only 2 comments:


> * Must implement CNI config cleanup right before agent stops

Just to be clear, although it must implement CNI config cleanup, it does not mean that we should do this. We still want to be sure that kubelet, or the container runtime, will not pick any other CNI configuration except Cilium's when Cilium is down or being upgraded.

> Instead of embedding the logic into the agent daemon itself, create `cilium cni install/uninstall` commands to use as postStart and preStop respectively. This would be a simple lift&shift from the current shell scripts.

I would propose a dedicated binary. We need to take into account the memory footprint of running `cilium cni` vs running bash script. I know it sounds ridiculous but it is something that we need to take into account.

**Comment by ti-mo** [comment]
> Just to be clear, although it must implement CNI config cleanup, it does not mean that we should do this. We still want to be sure that kubelet, or the container runtime, will not pick any other CNI configuration except Cilium's when Cilium is down or being upgraded.

True, I'm also changing my mind on this since we have `cilium cleanup`. Though as you've pointed out before, CNI exclusivity is the only real way of guaranteeing no other CNI gets picked. The upshot is, if *all* CNIs are gone (e.g. during agent restart with automatic CNI config clean up), I remember the node actually being marked as 'network not ready', but I need to check that again. This is cleaner than having Pods stuck in scheduling status.

> I would propose a dedicated binary. We need to take into account the memory footprint of running cilium cni vs running bash script. I know it sounds ridiculous but it is something that we need to take into account.

I would like to see some data to back this up, because the OS should only page in code segments it really needs to execute. If the same binary is used to run both the Cilium agent and `cilium cni`, the page cache should already contain parts of the Go runtime used by both programs. Virtual memory usage will slightly increase while `cilium cni` is run, but this shouldn't count towards cgroup memory limits.

On the contrary, shipping this as a separate Go binary will inflate both the container image size (since there's an extra copy of the Go runtime included) as well as the resident set, since this second binary needs to be paged in separately.

**Comment by sduranc** [comment]
@ti-mo Just to add to the discussion if it's helpful: I can confirm that I've seen some issues related to the `cni-install.sh`. What happened is that the `postStart` hook was interrupted (failed) and the CNI files weren't in place after the agent started running, which ended up in an apparently "healthy" agent (for the health checks) which was useless. It was hard to detect what was the issue since the agent appeared to be healthy. Most likely this wouldn't happen (the cni-install script failing to complete) but if it does it sounds like a critical error for the agent IMHO.

**Comment by squeed** [comment]
I'm taking a look at this. My basic plan is:

### Cilium-managed mode

The agent drops in a CNI configuration file when it is ready to handle new pods.

If there are no other CNI configuration files on disk, then the CNI configuration is removed on shutdown. This is to prevent the case where another file exists on disk, but we have priority. If we removed our file in this case on upgrade, then pods may start with the "old" configuration.

By default, the contents of the CNI configuration are managed by us. The existing helm plumbing (`cni.readCniConf`, `cni.configMap`) will still work to provide the contents.

The open question is whether or not this should be a goroutine in the agent process, or a sidecar pod that watches agent health and the CNI directory.

### Unmanaged mode
When `cni.install` is false, the agent does nothing. 

Question: should it still install the binaries?

**Comment by ti-mo** [comment]
> .. or a sidecar pod that watches agent health and the CNI directory.

This feels like overkill. Hosting this in the agent process sounds good.

> Question: should it still install the binaries?

Yep, it might be more convenient to do this in tandem with dropping/removing the CNI config.

**Comment by squeed** [comment]
> > Question: should it still install the binaries?
> 
> Yep, it might be more convenient to do this in tandem with dropping/removing the CNI config.

Given that their presence does nothing without a CNI config file, it's safe to always install them and leave them be.

**Comment by ti-mo** [comment]
> Given that their presence does nothing without a CNI config file, it's safe to always install them and leave them be.

IIRC there was a case where kubelet had stale config of some sort (it's been a few years) and was still trying to create a Pod using Cilium's CNI binary. This takes much longer than necessary to bail out, since the CNI binary has a relatively long timeout establishing a connection to the agent's management socket. With the CNI binary gone, this returns a much clearer error in the pod's state transitions.

If memory serves me right, Pods need to be deleted for CNI selection to occur for that allocation (I guess CNI evaluation happens when the Pod is allocated?), so this state sticks around for longer than expected.

Also, if the binary disappears when the agent Pod stops, the user doesn't need to go in and run `cilium cleanup` in all nodes' hostns if they want to clean up.

**Comment by squeed** [comment]
Hah. It turns out the agent already has the option to do this: https://github.com/cilium/cilium/blob/master/daemon/cmd/daemon_main.go#L1829

**Comment by squeed** [comment]
> If memory serves me right, Pods need to be deleted for CNI selection to occur for that allocation (I guess CNI evaluation happens when the Pod is allocated?), so this state sticks around for longer than expected.

What kubelet does now isn't important anymore, all that code has been deleted :-). Containerd and podman both use fsnotify (or something similar) to watch the CNI configuration directory, so updates are pretty quick.

**Comment by ti-mo** [comment]
@squeed It's not about what's in the CNI config, it's about what's in the Pod state. What happens when:

- Cilium (and CNI config) is installed
- Pod is scheduled and allocated on the node
- Pod takes a long time to pull/create, goes into backoff, whatever
- Cilium is uninstalled; agent stopped, CNI config removed, etc.
- Cilium CNI binary is still on the machine

Will kubelet continue to retry creating the Pod using the Cilium CNI binary? IIRC it does, and it hangs.
Likewise, a running Pod needs the Cilium CNI binary to be gracefully deleted, no matter what the CNI config says.

**Comment by squeed** [comment]
I’m not sure of the exact behavior around when containerd and kubelet give up, but removing the binaries seems like an indirect solution to the problem we’re facing — namely, that we want to fail fast and “cleanly” when the agent is down for whatever reason.

I think we can better handle this in the plugin binary itself. For example, we could fail immediately if the agent socket is missing. The agent could also write a downfile for plugins to check. That way we can fail fast with a user-friendly error message.

I’ll make a separate issue for improving “agent down” UX.

**Comment by ti-mo** [comment]
@squeed True, that would be even better! Then maybe we could return an even clearer error message to be displayed in the Pod status.

**Comment by squeed** [comment]
#21375 is ready for review. The only thing it doesn't do is improve CNI binary performance around down agents.

**Comment by squeed** [comment]
Reopening as this was reverted; Fix incoming.
