### ISSUE TITLE
Document of matchLabels in Cilium Policies

### ISSUE THREAD

**Issue by acholt** [cilium/cilium#14890]
I've followed the documentation on `matchLabels` as seen [1].

This issue was investigated on issue #14860 after apply `enable-policy: always` to the cilium config.

I was getting denies on my policies and no matches.
```bash
0/22 rules selected
Found no allow rule
Found no deny rule
```

...after changing the `matchLabels` to be explicit as show in the `cilium trace` from `role: backend` --> `"k8s:role": backend` my policies start to work perfectly.

I'm not sure if its intended to work this way or if its a regression? If it is the documentation isn't that clear.

**Cilium Documentation**
```bash
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l4-rule"
spec:
  endpointSelector:
    matchLabels:
      role: backend
  ingress:
  - fromEndpoints:
    - matchLabels:
        role: frontend
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
```

**What actually is working**
```bash
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l4-rule"
spec:
  endpointSelector:
    matchLabels:
      "k8s:role": backend
  ingress:
  - fromEndpoints:
    - matchLabels:
       " k8s:role": frontend
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
```

**General Information**
Cilium version: `1.9.4`
Hosted on AWS EKS
Kernel version: `5.4.80-40.140.amzn2.x86_64`
Orchestration system version in use: `v1.18.9-eks-d1db3c`

[1] https://docs.cilium.io/en/v1.9/policy/language/#layer-4-examples

**Comment by pchaigno** [comment]
This is not expected. Do you have a corresponding sysdump?

**Comment by acholt** [comment]
[Uploading cilium-sysdump-20210208-142358.zip…]()

**Comment by pchaigno** [comment]
I think you posted the comment before the GitHub upload finished. I can't download the sysdump.

**Comment by acholt** [comment]
> I think you posted the comment before the GitHub upload finished. I can't download the sysdump.

Try to download it now.

**Comment by pchaigno** [comment]
Which policy in the sysdump should I be looking at that is not working as expected?

**Comment by acholt** [comment]
> Which policy in the sysdump should I be looking at that is not working as expected?

`mid-ingress-glowroot-to-cassandra` was one policy that wasn't working as expected, I have since changed the label from `name: cassandra` --> `"k8s:app.kubernetes.io/name": cassandra` and everything is working as expected.

**Comment by pchaigno** [comment]
Ok. So this issue can be closed?

**Comment by acholt** [comment]
> Ok. So this issue can be closed?

I would like to understand why we getting this behaviour and if this is expected we should update the documentation, or is it a bug with Cilium?

**Comment by pchaigno** [comment]
None of your pods have label `name=cassandra`, so it's expected that it won't match anything when used in a policy. Using `"k8s:app.kubernetes.io/name"=cassandra` or `"app.kubernetes.io/name"=cassandra` in the policy instead should work. Is that not the case?

**Comment by acholt** [comment]
> None of your pods have label `name=cassandra`, so it's expected that it won't match anything when used in a policy. Using `"k8s:app.kubernetes.io/name"=cassandra` or `"app.kubernetes.io/name"=cassandra` in the policy instead should work. Is that not the case?

🤦  You are correct, I was looking at Hubble and took it as the truth, just checked the deployments. 
![Screen Shot 2021-02-08 at 19 04 43](https://user-images.githubusercontent.com/8980867/107268742-8367c800-6a40-11eb-9172-495c86ccd3b7.png)

Thanks for your help @pchaigno, appreciate it.

**Comment by pchaigno** [comment]
No problem. I'm glad we got to the bottom of this :detective:
