### ISSUE TITLE
Minikube serves apiserver via https by default, getting started with k8s guide example uses http

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#1491]
https://raw.githubusercontent.com/cilium/cilium/master/examples/minikube/cilium-ds.yaml uses `--k8s-api-server` flag, which results in cilium DS not being ready when following the guide.

**Comment by nebril** [comment]
The easiest way to fix this is to change `minikube start --network-plugin=cni` command in docs to `minikube start --network-plugin=cni --extra-config=apiserver.InsecureServing.BindPort=8080`, which corresponds to the address used in example cilium manifest.

It's not ideal config, but should be enough for getting started guide.

**Comment by tgraf** [comment]
Is this a new problem with the latest `minikube` release? I've never seen this. Can we fix this in the DaemonSet file instead somehow?
