### ISSUE TITLE
BPF Service implementation - Gateway problem with FHRP

### ISSUE THREAD

**Issue by skuffe** [cilium/cilium#14911]
## Bug report

When running Cilium with the KubeProxyReplacement set to "strict". The BPF based service implementation, uses a "non standard L2 packet forwarding in a vPC environment".

So essentially what happens is that a packet comes into our k8 host (in this case a UDP packet with a DNS request) from a source MAC address that is different from the currently active FHRP peer . The response is generated and sent off directly with the source MAC address now as the destination.

In a vPC (Virtual Port Channel) environment with FHRP (in our case Cisco HSRP) the gateway has a virtual MAC address learned via ARP, so the response should have been sent towards the virtual gateway mac learned via ARP. This is what the Linux kernel normally does, and also works in the iptables implementation with kube-proxy.

There's a potential workaround we could do, by enabled "Peer Gateway" on our nexus distribution switches.

But perhaps this is something that could/should be handled by Cilium?

I believe the "correct" way to send the reply would be to use the MAC learned from default gateway here and not assume the reply should be sent towards the source MAC?

![image](https://user-images.githubusercontent.com/1579080/107394742-7a3c3100-6afc-11eb-83ce-fda509d9ed02.png)

In the excerpt above 10.161.192.2 is the currently active HSRP peer, and 10.161.192.1 is the HSRP Gateway VIP

Some more information can also be found here, where the scenario is also described;
https://community.cisco.com/t5/networking-documents/peer-gateway-feature-on-the-nexus-7000/ta-p/3113290
https://www.dclessons.com/vpc-enhancements

Happy to assist on this in any way i can.

- Cilium version
`Client: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
Daemon: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64`

- Kernel version
`Linux srvp00569 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

- Orchestration system version in use
`Client Version: v1.20.2+k3s1
Server Version: v1.20.2+k3s1`

- Generate and upload a system zip:
[cilium-sysdump-20210209-155555.zip](https://github.com/cilium/cilium/files/5952535/cilium-sysdump-20210209-155555.zip)

**Comment by skuffe** [comment]
I should mention as well. The MAC "flip behavior" only occurs when the traffic comes in and leaves on the same node. So either with `loadBalancer.mode=snat` or with `loadBalancer.mode=dsr ` and the backend pod on the same node that received the ingress. In the case of DSR mode where traffic leaves a different node, the traffic leaves towards the default gateway as one would expect (from my observations)

Now I am not sure about the details on how this is implemented, but perhaps the behavior could be toggled with a setting?

**Comment by brb** [comment]
@skuffe Thanks for the detailed issue.

What happens in your case is that the NodePort BPF associates the source IP with the source MAC of the request (https://github.com/cilium/cilium/blob/v1.9.4/bpf/lib/nodeport.h#L1409), and then later on, when sending a reply to the client it reuses the association instead of doing a FIB lookup (https://github.com/cilium/cilium/blob/v1.9.4/bpf/lib/nodeport.h#L1504).

We would consider accepting a PR which would add a flag to the cilium-agent to disable this optimization.

**Comment by skuffe** [comment]
Ahh thanks @brb, looks like it could be fairly simple to implement a switch that disables it, ill try and have a stab at it.
