### ISSUE TITLE
Converge similar documentation for ENI mode

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14921]
The following two pages are very similar, but provide subtly different documentation:

* [Managed Kubernetes](https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-managed/) -> [Installation on AWS EKS](https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-eks/)
* [Getting Started Guides](https://docs.cilium.io/en/v1.9/gettingstarted/) -> [Setting up Cilium in AWS ENI mode](https://docs.cilium.io/en/v1.9/gettingstarted/aws-eni/)

It's confusing to have both, should we consolidate them (even if we link from both current locations)?

**Comment by Kikiodazie** [comment]
Hey @joestringer, can I have this assigned to me?

**Comment by joestringer** [comment]
Sure thing, assigned to you. Feel free to reach out here or on Slack #development / #sig-docs if you have further questions about this topic.

**Comment by Kikiodazie** [comment]
> Sure thing, assigned to you. Feel free to reach out here or on Slack #development / #sig-docs if you have further questions about this topic.

Sure will do. Thanks, @joestringer.

**Comment by joestringer** [comment]
Ah great, OK. Thanks for investigating, sometimes these issues just need fix confirmation to validate that they're already solved. I hope you were able to learn something while figuring out this issue :-) Closing fixed.

**Comment by Kikiodazie** [comment]
> Ah great, OK. Thanks for investigating, sometimes these issues just need fix confirmation to validate that they're already solved. I hope you were able to learn something while figuring out this issue :-) Closing fixed.

Yes, I was @joestringer, thanks for helping out.
