### ISSUE TITLE
No IPv6 connectivity to BPF HostPort when kube-proxy is installed

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14929]
While working on our new mixed (kube-proxy+kpr) CI pipeline (cf. https://github.com/cilium/cilium/pull/14543), I found a new bug in the IPv6 connectivity to BPF HostPort. When trying to connect to a HostPort on node2 from node1, the following packet traces are observed on node2:
```
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: [fd04::11]:51968 -> [fd04::12]:8080 tcp SYN
<- host flow 0x0 identity world->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: [fd04::11]:51968 -> [fd02::1c1]:80 tcp SYN
-> endpoint 571 flow 0x0 identity remote-node->846 state established ifindex lxcd4289a2b4ce0 orig-ip fd04::11: [fd04::11]:51968 -> [fd02::1c1]:80 tcp SYN
<- endpoint 571 flow 0xe5b07edd identity 846->unknown state new ifindex 0 orig-ip 0.0.0.0: [fd02::1c1]:80 -> [fd04::11]:51968 tcp SYN, ACK
-> network flow 0xe5b07edd identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: [fd04::12]:8080 -> [fd04::11]:51968 tcp SYN, ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: [fd04::11]:51968 -> [fd04::12]:8080 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: [fd04::11]:51968 -> [fd04::12]:8080 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: [fd04::11]:51968 -> [fd04::12]:8080 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: [fd04::11]:51968 -> [fd04::12]:8080 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: [fd04::11]:51968 -> [fd04::12]:8080 tcp ACK
```
The SYN packet is DNATed and goes through the stack on its way to the lxc device. The SYN+ACK is reverse DNATed and sent to the native device. Finally, the ACK is received at the native device, DNATed, and sent to the lxc device through the stack. So the stack saw:
1. SYN: clientIP -> backendIP
2. SYN+ACK: VIP -> clientIP
3. ACK: clientIP -> backendIP

When the ACK packet arrives, the connection is invalid from conntrack's point of view, because it never saw the SYN+ACK for the clientIP<->backendIP. At that point, the packet is dropped by kube-proxy's rule:
```
[299:36874] -A KUBE-FORWARD -m conntrack --ctstate INVALID -j DROP
[0:0] -A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
[0:0] -A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[0:0] -A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```
The same doesn't happen in the IPv4 case because we explicitly skip the kube-proxy rule to drop invalid connections.

**Comment by brb** [comment]
@fristonio Does this sound familiar to you?

**Comment by pchaigno** [comment]
The first commit of #14675 fixes this bug.

**Comment by fristonio** [comment]
@brb I don't think so, cilium kpr with kube-proxy is one of the cases which I did not consider when working on the dual-stack stuff. Good thing @pchaigno found and fixed this :partying_face:
