### ISSUE TITLE
Improve API ratelimit error messages

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14922]
Currently, if you deploy too many pods at a time, Cilium will ratelimit the requests and Kubernetes will report errors like the following:

```
  Warning  FailedCreatePodSandBox  12m                kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef": Unable to create endpoint: response status code does not match any response statuses defined for this endpoint in the swagger spec (status 429): {}
```

The `response status code does not match any response statuses defined for this endpoint in the swagger spec` error is generated because the Cilium swagger spec does not define the error message for this error code.

I believe that this could be fixed by applying changes like the following to each ratelimited API call and regenerating the API:

```
diff --git a/api/v1/openapi.yaml b/api/v1/openapi.yaml
index 016422b4c798..de615c3a55c4 100644
--- a/api/v1/openapi.yaml
+++ b/api/v1/openapi.yaml
@@ -131,6 +131,8 @@ paths:
         '409':
           description: Endpoint already exists
           x-go-name: Exists
+        '429':
+          description: Too many requests
         '500':
           description: Endpoint creation failed
           x-go-name: Failed
```

The relevant ratelimit calls can be found by inspecting the `apiRateLimitDefaults` variable in `daemon/cmd/api_limits.go`.

Tasks:
* [ ] Define error names for error `429` for all relevant API calls
* [ ] `make generate-api`
* [ ] Build images & test that when you deploy many pods at once, the new error messages show up.
  * You may consider reducing the api ratelimits while testing by applying configuration from the [API Rate Limiting documentation](https://docs.cilium.io/en/v1.9/configuration/api-rate-limiting).

**Comment by Maddy007-maha** [comment]
Please assign this issue to me

**Comment by pchaigno** [comment]
@Maddy007-maha I've assigned you. Don't hesitate to reach out on Slack (e.g., #development) if you have any question.

**Comment by Maddy007-maha** [comment]
> @Maddy007-maha I've assigned you. Don't hesitate to reach out on Slack (e.g., #development) if you have any question.

Sure thanks

**Comment by ybialik** [comment]
Hey, when this happens, pods are remaining in "containerCreating", is there a way to pass that?

**Comment by joestringer** [comment]
@ybialik it depends. The underlying cause for timeouts while provisioning new pods can come from a variety of places. This is not an exhaustive list, but I could imagine that it comes up if the IPAM plugin cannot allocate an IP for the new pod (eg because of ENI instance limits), or it could come up because too many pods are being provisioned at once on a node with low resources (eg if Cilium has CPU resource limits). Depending on the root cause, the solution may be different.
