### ISSUE TITLE
Autoconfigure --ipv4-pod-subnets / --ipv6-pod-subnets in cloud environments

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14941]
When Cilium is configured with cloud integration modes (ENI, Azure) and encryption, ideally it would autoconfigure `--ipv4-pod-subnets` / `--ipv6-pod-subnets` (as necessary) based on information provided from the cloud APIs.

**Comment by jrfastab** [comment]
Completed. 

commit 58f7f700a37023f79886bd6ce4b543fd7e08bff6
Author: John Fastabend <john.fastabend@gmail.com>
Date:   Mon Mar 15 23:09:26 2021 -0700

    cilium: auto-detect network interfaces for IPAMENI case
    
    [ upstream commit 2c878a512de941d3557965cdba0f02d84528bc90 ]
