### ISSUE TITLE
ci: Run smoke tests in GH actions with kube-proxy-replacement=strict

### ISSUE THREAD

**Issue by brb** [cilium/cilium#14957]
https://github.com/cilium/cilium/pull/14951 will enable KPR on Kind (with some limitations - https://github.com/cilium/cilium/issues/14956). This means that we could run [the KPR test suite](https://github.com/cilium/cilium/blob/master/test/k8sT/Services.go) in a GH action which could drastically reduce time and effort it takes to test.

To make it happen, the following problems have to be resolved:

- [x] Find a way to run GH action with cgroup v2 only (Fedora is not going to be supported any time soon - https://github.com/actions/virtual-environments/issues/2307). Maybe relax the requirement for the absence of net_cls or net_prio or run VM inside GH action, as https://github.com/kubernetes-sigs/kind/blob/master/.github/workflows/cgroup2.yaml does.
- [x] Run GH action with Docker 20.10, as it supports cgroup v2. Currently, it's being run with 19.10.
- [x] Patch Kind to disable kube-proxy.
- [x] Patch Kind to enable multiple networks per node (to test NodePort BPF on secondary devices). (UPDATE: currently we create additional network manually in the L4LB suite).
- [x] Make it easier to run XDP on veth (requires some manual undocumented steps).

**Comment by brb** [comment]
The PR to disable kube-proxy is out: https://github.com/kubernetes-sigs/kind/pull/2088.

**Comment by aanm** [comment]
@brb this is has been marked stale, do you want to keep track of it or close it?

**Comment by brb** [comment]
Let's keep it. All dependencies have been resolved, we could just run the tests on Kind.

**Comment by brb** [comment]
Closing in favor of https://github.com/cilium/cilium/issues/20606.
