### ISSUE TITLE
helm: PodSecurityPolicy management regression

### ISSUE THREAD

**Issue by mvisonneau** [cilium/cilium#14963]
I was looking to upgrade to a more recent version of the helm chart but it looks like there is a regression which occured with the [v1.9.0-rc1](https://github.com/cilium/cilium/tree/v1.9.0-rc1/install/kubernetes/cilium). (Related to the refactoring of the chart implementation I assume https://github.com/cilium/cilium/pull/13259).

From this version, we cannot dynamically create the pod security policies as part of the chart. This feature was originally introduced by https://github.com/cilium/cilium/pull/10330 and [received several contribution afterwards](https://github.com/cilium/cilium/pulls?q=is%3Apr+psp+is%3Aclosed).

I could not find any deprecation notice for it, I assume this is a mistake? 🤔

**Comment by aanm** [comment]
@mvisonneau see https://github.com/cilium/cilium/pull/12469

**Comment by mvisonneau** [comment]
ah great thank you @aanm! 🙇 my bad, will close this then 👍
