### ISSUE TITLE
Improve permanent arp entry handling  

### ISSUE THREAD

**Issue by dsexton** [cilium/cilium#14962]
## Proposal / RFE

Building on top of the changes made for #14322 via #14322, there should be additional checks to ensure stale permanent arp entries are not left, thus breaking node-to-node communication. Even after upgrading from `1.9.1` > `1.9.3` > `1.9.4` we found stale entries, especially with worker pools where HPA & cluster autoscaler are present.

Some suggestions:

- [ ] Ability to have the periodic arp pinging also cleanup all permanent arp entries 
- [ ] Enable preflight to cleanup all permanent arp entries 
- [ ] Handle entry cleanup when `kube-proxy-replacement` is changed from `probe` > `disabled` 
- [ ] Add metric for number of permanent arp entries (count invalid & corrected entries too?)
- [ ] Handle situations where the agent crashes, not allowing proper cleanup of arp entries on shutdown
- [ ] Have a CI pipeline that can simulate cluster autoscaler / IP address reuse

**Comment by brb** [comment]
@dsexton Thanks for the proposal. I'm thinking maybe we should stop adding permanent entries if the ARP refresher could run more often than the kernel's ARP GC? /cc @jaffcheng

**Comment by brb** [comment]
Also, @borkmann had some ideas how to fix this in the kernel.

**Comment by jaffcheng** [comment]
> @dsexton Thanks for the proposal. I'm thinking maybe we should stop adding permanent entries if the ARP refresher could run more often than the kernel's ARP GC? /cc @jaffcheng

If ARP probes refresh the kernel neighbor table, I think so, but I think we would need to handle agent crashes then. @brb

**Comment by brb** [comment]
> I think so, but I think we would need to handle agent crashes then.

Yeah, that's a good point. JFYI after the v1.10 release we are planning to spend some cycles improving ARP handling.

**Comment by waynr** [comment]
:wave: howdy folks. I'm currently trying to understand why all the ARP cache entries on all my kubernetes nodes are marked PERMANENT. I tried to find a clue as to why this might happen by default in Linux ARP processing code, but so far it appears that it can only happen if an ARP entry are added "manually" via ioctl. The only thing in my cluster that I can imagine may be trying to manage ARP entries via ioctl is Cilium, which is how I landed on this issue.

The problem for my use case is that there are times when I need to recycle a control plane or worker node -- ie, replace it with a new node. What I have observed on Kubernetes 1.21.2 with Cilium 1.10.1 is that there is a non-zero possibility that a new node comes up with a recently-used IP address but with a different MAC address which can cause some worker nodes to get stuck in a "not ready" state. I am able to fix this by manually deleting the erroneous ARP cache entry in the worker node. If I don't do this then the ARP cache seems to never expire.

It's not clear to me why some worker nodes get stuck with the old MAC address while others end up with the new one. Any insight y'all might be able to provide would be greatly appreciated!

**Comment by skgsergio** [comment]
We have the very same issue as @waynr with the PERMANENT ARP entries, we sometimes recycle nodes reprovisioning them with the same IP and we had to add to our node decommissioning playbook a task that runs in all the remaining nodes this: `ip neigh del to NODE_IP dev ETH_DEV`

**Comment by waynr** [comment]
We just identified a potential cause of ARP cache entries becoming stuck. It looks like when we recycle our master nodes specifically it is possible for `cilium-agent` to die unexpectedly then get stuck in a crashlooping state where it can't communicate with the master/etcd and reassert control over the ARP cache, which would be necessary for it to communicate with the master/etcd in the first place. Nodes where `cilium-agent` never crashes during a master node recycle are the ones that remain in their `Ready` state.

**Comment by waynr** [comment]
> we sometimes recycle nodes reprovisioning them with the same IP and we had to add to our node decommissioning playbook a task that runs in all the remaining nodes this: ip neigh del to NODE_IP dev ETH_DEV

Thanks for the suggestion, but this isn't an option for us since we have a purely image-based worker provisioning workflow -- we don't allow SSH access to our worker nodes.

**Comment by brb** [comment]
@waynr Thanks for reporting. I've created https://github.com/cilium/cilium/issues/17300 to fix your issue.

**Comment by brb** [comment]
@waynr To dissable the ARP handling, you can set `--enable-l2-neigh-discovery=false`.

**Comment by timoreimann** [comment]
@brb thanks for the note about how to disable ARP handling. Are there any downsides to doing so?

**Comment by borkmann** [comment]
@dsexton @jaffcheng We've completely reworked neighbor resolution in order to "offload" it entirely to the kernel. Details are in https://github.com/cilium/cilium/commit/794ce347d1e59b3ce9f15c3b8b4c845582c51d64 ( https://github.com/cilium/cilium/pull/17713). If you have a chance, please check the lastest master image.

**Comment by Purushotham233** [comment]
@borkmann is 1.10-backport possible and planned?

**Comment by borkmann** [comment]
> is 1.10-backport possible and planned?

It could be discussed during the weekly Cilium meeting, but for now I'd like to have it sit for a while in 1.11 to fully stabilize.

**Comment by borkmann** [comment]
(IPv6 neighbor discovery merged as well now: https://github.com/cilium/cilium/pull/17842)
