### ISSUE TITLE
Does cilium_k8s_event_lag_seconds metric work?

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#14972]
When I run `cilium metrics list` in a local microk8s environment (Cilium dev version, v1.10 cycle), it reports:

```
cilium_k8s_event_lag_seconds     source="k8s"     0.000000
```

The other `cilium_k8s_client_api_latency_time_seconds` metrics all report >0 values, so this one seems just wrong.

I saw similar reports in another more serious dev environment from another community user (v1.9.x).

**Comment by aanm** [comment]
That metric reports the lag of a pod event that was received after a CNI add. If the pod event is received before the CNI add them it is assumed there is no latency.
