### ISSUE TITLE
Cilium Basics

### ISSUE THREAD

**Issue by dwdrajesh** [cilium/cilium#14971]
For beginners, I was looking if there is any online material, or a video course that explains container networking in Linux and how Cilium is different from the usual networking, any recommendation from developers here please?
Thanks.

**Comment by joestringer** [comment]
Some thoughts, maybe there are other resources available or someone could create more targeted resources:

https://cilium.io/blog/2020/11/10/ebpf-future-of-networking/
https://ebpf.io/#featured-ebpf-community-blogs
https://www.isovalent.com/resources

**Comment by pchaigno** [comment]
We also have https://github.com/cilium/cilium/blob/master/FURTHER_READINGS.rst which may be relevant here.
