### ISSUE TITLE
godoc: repository structure not rendering properly

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#1498]
[godoc](https://godoc.org/github.com/cilium/cilium/pkg/policy#Repository). Probably fixed by adding newline [after Mutex](https://github.com/cilium/cilium/blob/master/pkg/policy/repository.go#L30)

**Comment by nebril** [comment]
@scanf I can't see anything wrong with the godoc. The only public field in `Repository` seems to be `Mutex`, which is shown there. Can you elaborate?

**Comment by aalemayhu** [comment]
Did not have enough coffee, my bad. Missed that they were supposed to be private.
