### ISSUE TITLE
Support testing egress policies with policy trace

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#14987]
[`cilium policy trace`](https://docs.cilium.io/en/latest/cmdref/cilium_policy_trace/#cilium-policy-trace) allows users to test how their policies are applied and verify they restrict communications as they intended it. It however currently only supports egress policies. This issue is to track work on supporting the same functionality for egress policies.

**Comment by margamanterola** [comment]
The policy trace command was removed in this PR: https://github.com/cilium/cilium/pull/23550

Closing this issue.
