### ISSUE TITLE
Pod-to-pod communication not working with IPVLAN

### ISSUE THREAD

**Issue by pszymanski-intel** [cilium/cilium#15025]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
Client: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
Daemon: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64

- Kernel version (run `uname -a`)
Linux bert 5.10.0 #1 SMP Mon Feb 15 13:49:14 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```
[cilium-sysdump-20210218-130424.zip](https://github.com/cilium/cilium/files/6003148/cilium-sysdump-20210218-130424.zip)

**How to reproduce the issue**
1. Create a cluster with 2 nodes
2. Create 2 pods - one on each node. 
3. Run NGINX in one pod and fortio curl in the other pod
4. TCP connection setup fails.

When I run cilium monitor on both nodes, I only see TCP SYNC messages on the node where fortio is running, but no response from the other node. Also on the other node TCP SYNC packets are not visible (neither using cilium monitor nor tcpdump).

The problem also happens when both pods are on the same node.

**Comment by pszymanski-intel** [comment]
I noticed that all ip addresses assigned to cilium_host and interfaces inside pods got subnet mask 32 like: 10.0.0.42/32. Is it expected? When I created my test ipvlan manually I had to set the mask to 24 or 16. With 32 the ipvlan did not work.

**Comment by pszymanski-intel** [comment]
I did more investigation with eBPF code armed with traces and I noticed that handle_ipv4_from_lxc function is called multiple times (probably when the TCP SYNC is repeated) and the function exits by calling redirect_neigh with ifIndex of the physical device which is the ipvlan master. Is it expected?

**Comment by pszymanski-intel** [comment]
As a next step I commented out the piece of code calling redirect_neigh and forced the code to go to pass_to_stack label. After the change I can see on tcpdump SYNC packets coming from the pod, but with Cluster IP instead of backend pod (NGINX) IP. My understanding is that the Cluster IP shall be replaced with pod IP by sock4_connect function. Need to figure out why this does not happen.

**Comment by pszymanski-intel** [comment]
When I added a trace in sock4_connect function I can see the function being called, but it also caused that problem has disappeared. What's more, when I removed the trace the problem did not return. It looks like for some reason the function was called. Is it possible that there was a problem with loading and attaching the bpf program? 
And when I reverted the change in handle_ipv4_from_lxc, the problem is still back. So it looks like there is a bug in this part of code. Maybe ENABLE_REDIRECT_FAST shall not be defined when ipvlan is used?

**Comment by pszymanski-intel** [comment]
I verified that setting EnableHostLegacyRotuing = true solves the problem. If ipvlan is not compatible with Host Legacy Routing than the cilium-agent shall reject such combination.

**Comment by pchaigno** [comment]
> Maybe ENABLE_REDIRECT_FAST shall not be defined when ipvlan is used?

AFAIU, yes, `ENABLE_REDIRECT_FAST` shouldn't be enabled with ipvlan. /cc @borkmann can confirm.

**Comment by brb** [comment]
Also, if you can use `ENABLE_REDIRECT_FAST`, then there is no much gain in using ipvlan. See https://cilium.io/blog/2020/11/10/cilium-19#virtual-ethernet-device-optimization-with-ebpf.

**Comment by pszymanski-intel** [comment]
I already run ipvlan performance tests and I can see that ipvlan performance is about 9% lower than veth with ENABLE_REDIRECT_FAST. What's more I can see higher CPU utilization in case of ipvlan (about 20%). It seems that the higher CPU utilization is caused by cilium-agent activity. Is it expected?

**Comment by brb** [comment]
> ipvlan performance tests

Which tests on what setup?

**Comment by pszymanski-intel** [comment]
I am running fortio in one pod and nginx on another pod. The pods are on different nodes. Fortio opens 5K connections and downloads 256B file from NGINX.

**Comment by brb** [comment]
Are you using Cilium's ipvlan implementation or a generic ipvlan CNI plugin?

**Comment by pszymanski-intel** [comment]
I am using Cilium ipvlan ( i.e. I am setting --set datapathMode=ipvlan in helm)

**Comment by brb** [comment]
> I solved the problem. I had monitor aggregation set to none. (from Slack)

I guess the higher CPU load got resolved?

**Comment by pszymanski-intel** [comment]
Correct. Higher CPU utilization is solved. For some reason I thought that if I do not have "cilium monitor" command started, the performance impact shall be low  even if monitor aggregation is none. Now I can see higher ipvlan performance by about 25% vs. veth. The only unexpected behavior is lower performance (both ipvaln and veth) when setting CONFIG_PREEMPT_NONE=y.

**Comment by brb** [comment]
> The only unexpected behavior is lower performance (both ipvaln and veth) when setting CONFIG_PREEMPT_NONE=y.

Maybe you have noisy neighbors on the machines?

**Comment by pszymanski-intel** [comment]
I don't have any neighbors. The machines I am using are physical machines (not virtual) and there is no other workload running on them.
Regarding the difference between ipvlan vs. veth. I was incorrect. The 25% was measured with vlan enabled. When I disabled vxlan and masquerading (which is also not supported with ipvlan), ipvlan and veth are really close - it is hard to tell exactly due to high run-to-run variation.
By the way, I think I found some inconsistency in documentation.  In this location https://docs.cilium.io/en/v1.9/concepts/networking/routing/#configuration there is information that native routing requires setting enable-endpoint-routes: true. However recently there was added a condition that BPF host routing (i.e. legacy-host-routing=true) is not supported with tunnels and with enable-endpoint-routes: true. So I set in order to use BPF host routing you need to disable tunnel (i.e. enable native routing) and disable endpoint routes.

**Comment by borkmann** [comment]
@pszymanski-intel do you run ipvlan in l3 mode or l3s?

**Comment by pszymanski-intel** [comment]
I run in l3 mode
