### ISSUE TITLE
AKS single node cluster not accepting any requests on external ips

### ISSUE THREAD

**Issue by adamskibickipd** [cilium/cilium#15022]
**General Information**

- Cilium version
Client: 1.9.3 ae8661f14 2021-01-22T18:34:11+01:00 go version go1.15.6 linux/amd64
Daemon: 1.9.3 ae8661f14 2021-01-22T18:34:11+01:00 go version go1.15.6 linux/amd64
- Kernel version
Linux aks-nodepool1-13517115-vmss000000 5.4.0-1036-azure #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use
k8s version: 19.6 (the issue also persists on default 1.18.14 version in AKS)

**How to reproduce the issue**
1. Use official guide: https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-aks/ and but set AKS node count to 1 and install cilium.
2. Create any LoadBalancer service with external ip (if you create a such service azure automatically creates a associated with it public ip).
3. Try to send or connect to this external ip - requests don't reach the cluster.
*This issue can be avoided by using this options:
hostServices.enabled: true
kubeProxyReplacement: partial
So the problems seems to be in BPF-based kube-proxy replacement.

**Comment by brandshaide** [comment]
This affects also a multi-node setup 

```
aks-primary-29773559-vmss000006   Ready    agent,primary   14h   v1.19.7   10.129.0.4     <none>        Ubuntu 18.04.5 LTS   5.4.0-1039-azure   containerd://1.4.3+azure
aks-primary-29773559-vmss000007   Ready    agent,primary   14h   v1.19.7   10.129.0.106   <none>        Ubuntu 18.04.5 LTS   5.4.0-1039-azure   containerd://1.4.3+azure
aks-primary-29773559-vmss000008   Ready    agent,primary   14h   v1.19.7   10.129.0.157   <none>        Ubuntu 18.04.5 LTS   5.4.0-1039-azure   containerd://1.4.3+azure
aks-worker-29773559-vmss000001    Ready    agent,worker    14h   v1.19.7   10.129.0.208   <none>        Ubuntu 18.04.5 LTS   5.4.0-1039-azure   containerd://1.4.3+azure
```
