### ISSUE TITLE
oss-fuzz: cilium: Fuzzing build failure

### ISSUE THREAD

**Issue by twpayne** [cilium/cilium#15021]
oss-fuzz is reporting that recent builds of Cilium are failing: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31077

The failure is:

```
Step #1: Step 6/8 : RUN go get github.com/cilium/cilium/pkg/labels/...
Step #1:  ---> Running in b335346fdb74
Step #1: [91mgo: downloading github.com/cilium/cilium v1.9.4
Step #1: [0m[91mgo get: github.com/cilium/cilium@v1.6.12 updating to
Step #1: 	github.com/cilium/cilium@v1.9.4 requires
Step #1: 	github.com/optiopay/kafka@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
Step #1: The command '/bin/sh -c go get github.com/cilium/cilium/pkg/labels/...' returned a non-zero code: 1
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
Step #1: [0m
```

Creating this issue so we can track this in our own issue tracker.

cc @AdamKorcz

**Comment by aanm** [comment]
This is likely related with the `replaces` that we have in our go.mod

**Comment by twpayne** [comment]
Yes, and I think that this is triggered by the [changes to `go.mod` handling in Go 1.16](https://golang.org/doc/go1.16#go-command).

**Comment by twpayne** [comment]
A quick fix for this would be to pin the version of Go used by the fuzzer to 1.15.8, but there [doesn't seem to be a config option for this](https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/#dockerfile). The docs state only:

> The OSS-Fuzz builder image has the latest stable release of Golang installed. In order to install dependencies of your project, add RUN go get ... command to your Dockerfile.

The correct fix is probably to enable Cilium to build with Go 1.16 as invoked by oss-fuzz.

**Comment by twpayne** [comment]
Couple of notes:
* I haven't yet found where the `/bin/sh -c go get github.com/cilium/cilium/pkg/labels/...` command comes from. The [`compiile_go_fuzzer` script is here](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile_go_fuzzer).
* Cilium builds, and the `go get` command work on my machine (tm) just fine. I installed Go 1.16, edited `GO_VERSION` to contain `1.16.0`, and ran `make GO=go1.16`. The `go1.16 get github.com/cilium/cilium/pkg/labels/...` command completes successfully.

**Comment by AdamKorcz** [comment]
I will be happy to take on fixing this. There have been a few of these lately. I will update here.

**Comment by twpayne** [comment]
Closing as stale.
