### ISSUE TITLE
Create nightly test run infrastructure for Jenkins

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1503]
We need a nightly run that runs some of the more resource-heavy tests that are currently ran as part of the build (specifically L7 stress tests).

Phase 1:
- [x] create a Jenkins job that runs nightly using HEAD of master.
    - Created: https://jenkins.cilium.io/job/Cilium-Nightly-Tests/
- [ ] L7 stress tests should only run during this nightly run, not on merges.
- [ ] determine which tests should be ran as part of this
    - Proposal: #2029

Phase 2:
- [ ] Test against a variety of kernels ( see #1850)
- [ ] Integration with Elastic / Grafana for statistics and logs for each build. Grafana is useful because it allows us to set alerts if certain conditions are met, e.g. if 50 % of resources used, datapath performance is less than some % . (TODO - this warrants its own ticket)
    - [ ] Memory usage over time
    - [ ] Resource utilization over time

Phase 3:
- [ ] build a new box every night to test latest kernel out of Cilium kernel branch to see if changes introduced result in performance degradation.

**Comment by ianvernon** [comment]
Could be useful : https://hopstorawpointers.blogspot.com/2016/10/performing-nightly-build-steps-with.html

**Comment by borkmann** [comment]
Related: #824

**Comment by ianvernon** [comment]
Suggested by @jrfastab for these nightly runs: perf tests for kproxy

**Comment by borkmann** [comment]
Would also be great to capture and track performance data for super_netperf tests TCP_STREAM / TCP_RR for i) node local endpoints, ii) endpoints on different nodes. For the latter, would be good to have tests for direct routing and for each supported overlay mode (vxlan, geneve) to track potential performance regressions of kernel/bpf data path.

**Comment by tgraf** [comment]
Lowered the priority as the base infrastructure is ready

**Comment by ianvernon** [comment]
@eloycoto will check in on this to see if we can close this and / or split it up into smaller, more up-to-date issues.
