### ISSUE TITLE
datapath: Support L2-less with fast redirect

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15075]
Once #14858 has been merged, make it possible to run the fast redirect (aka BPF host routing) with L2-less devices.

From the first glance it might be trivial to add the support. In the redirect functions we should bypass setting L2 addrs if egress iface doesn't have L2 addr.

UPDATE: the kernel fix by @joamaki has been merged. What's left is detecting whether the fix is present in the kernel (maybe via a helper as we do for other features), and then enabling the functionality by removing https://github.com/cilium/cilium/blob/v1.13.0-rc5/daemon/cmd/kube_proxy_replacement.go#L455.

**Comment by joamaki** [comment]
This requires a kernel change (https://lore.kernel.org/bpf/20210427135550.807355-1-joamaki@gmail.com/T/#t) as the `bpf_skb_change_head` helper did not work properly with an skb from a L3 device (mac_len unset which caused `skb->data` to point to middle of IP header in `tcp_v4_rcv`). It currently looks like there aren't a workaround for this. The only other helper that could be useful is `bpf_skb_adjust_room`, but that also cannot be used to mangle the skb into proper shape.

**Comment by ReillyBrogan** [comment]
It looks like that kernel change has been merged and applied to edge and all stable trees.

**Comment by julianwiedmann** [comment]
Once fixed, we also need to remove the limitation from the docs:
https://github.com/cilium/cilium/blob/master/Documentation/security/network/encryption-wireguard.rst#limitations
