### ISSUE TITLE
Cilium fails to start with IPv4 disabled

### ISSUE THREAD

**Issue by ken-letter** [cilium/cilium#15082]
## Bug report

**General Information**

- Cilium version `1.9.3`
- Kernel version `5.10.12-200.fc33.x86_64`
- Orchestration system version in use `kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts: (similar to) [kubeadm configuration](https://github.com/aojea/k8s-aws-ipv6/blob/master/aws-k8s-ipv6.yaml#L244-L296)
- Generate and upload a system zip:` -`

**How to reproduce the issue**

1. Setup kubernetes with `kubeadm`, using only IPv6 subnets
2. install cilium with helm as follows: `helm install cilium cilium/cilium --version 1.9.4 --namespace kube-system --set ipv4.enabled=false --set ipv6.enabled=true`
3. observe cilium pods fail to start successfully:

```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                                     READY   STATUS              RESTARTS   AGE
kube-system   cilium-operator-5cdf66574-4hq7n                                          1/1     Running             0          55s
kube-system   cilium-operator-5cdf66574-j4sl2                                          0/1     Pending             0          55s
kube-system   cilium-xwg4g                                                             0/1     Error               2          55s
...

$ kubectl logs --namespace kube-system cilium-xwg4g
...
level=info msg="  --enable-ipv4='false'" subsys=daemon
level=info msg="  --ipv4-node='auto'" subsys=daemon
...
level=fatal msg="postinit failed" error="external IPv4 node address could not be derived, please configure via --ipv4-node" subsys=daemon

```

**Comment by nebril** [comment]
By looking at the code: https://github.com/cilium/cilium/blob/v1.9.3/pkg/node/address.go#L305 it seems like we do not support IPv6 only when tunneling is enabled (tunneling is enabled by default). Can you run with tunneling disabled (`--set tunnel=disabled`)?

**Comment by pchaigno** [comment]
@tgraf changed this condition in https://github.com/cilium/cilium/commit/0c22956df3f1ab873a2763e4d3fb7d464b612309, maybe he has more info on why this is unsupported.

**Comment by ken-letter** [comment]
Disabling does allow cilium to proceed launching, but this leaves the networking in a fairly useless state.

**Comment by Jeansen** [comment]
I have the same problem and from what I see it looks like the binding of the pod through the host network is only with IPv6. Here is what it looks like on one of my nodes (there is nothing more installed than Kubernetes 1.29, cert-manager and cilium)

```
systemd       1            root  114u  IPv4  13541      0t0  TCP *:111 (LISTEN)
systemd       1            root  118u  IPv6  17718      0t0  TCP *:111 (LISTEN)
rpcbind     662            _rpc    4u  IPv4  13541      0t0  TCP *:111 (LISTEN)
rpcbind     662            _rpc    6u  IPv6  17718      0t0  TCP *:111 (LISTEN)
sshd        736            root    3u  IPv4  16885      0t0  TCP *:22 (LISTEN)
sshd        736            root    4u  IPv6  16887      0t0  TCP *:22 (LISTEN)
crio        745            root   11u  IPv4  16928      0t0  TCP 127.0.0.1:40829 (LISTEN)
crio        745            root   12u  IPv6  12557      0t0  TCP *:9090 (LISTEN)
crio        745            root   35u  IPv4  56373      0t0  TCP *:4000 (LISTEN)
kubelet    1868            root   15u  IPv6  12913      0t0  TCP *:10250 (LISTEN)
kubelet    1868            root   20u  IPv4  17355      0t0  TCP 127.0.0.1:10248 (LISTEN)
cilium-ag  8563            root    3u  IPv4  52256      0t0  TCP 127.0.0.1:9890 (LISTEN)
cilium-ag  8563            root   45u  IPv4  48868      0t0  TCP 127.0.0.1:37789 (LISTEN)
cilium-ag  8563            root   50u  IPv4  46922      0t0  TCP 127.0.0.1:9879 (LISTEN)
cilium-ag  8563            root   58u  IPv6  49752      0t0  TCP *:4244 (LISTEN)
cilium-ag  8563            root   74u  IPv4  48050      0t0  TCP 192.168.178.181:4240 (LISTEN)
cilium-en 21988            root   58u  IPv4 105712      0t0  TCP *:9964 (LISTEN)
cilium-en 21988            root   59u  IPv4 105713      0t0  TCP *:9964 (LISTEN)
cilium-en 21988            root   60u  IPv4 105714      0t0  TCP *:9964 (LISTEN)
cilium-en 21988            root   61u  IPv4 105715      0t0  TCP *:9964 (LISTEN)
cilium-en 21988            root   62u  IPv4 105716      0t0  TCP *:9964 (LISTEN)
cilium-en 21988            root   63u  IPv4 105717      0t0  TCP *:9964 (LISTEN)
cilium-en 21988            root   64u  IPv4 105718      0t0  TCP *:9964 (LISTEN)
cilium-en 21988            root   65u  IPv4 105719      0t0  TCP *:9964 (LISTEN)
```

For some reason for port 4244 from the POD which is used by the peer Service behind 443 only listens on IPv6.

When I curl it, the DNS gets resolved, bu I get an empty reply. Also, I have not enabled IPv6 in the Cilium values when deploying with Helm.

**Comment by notpeelz** [comment]
Can this issue be reopened? Why is the ipv4 stack required for `--routing-mode tunnel`?

**Comment by alexandremahdhaoui** [comment]
@notpeelz I'm also facing the issue on a ipv6 only network.

**Comment by jordangarside** [comment]
Normally wouldn't say same, but the issue is closed.
