### ISSUE TITLE
[v1.9] CI: Suite-k8s-1.13.K8sDatapathConfig MonitorAggregation Checks that monitor aggregation restricts notifications

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#15114]
## CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-1.13-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Error creating resource /home/jenkins/workspace/Cilium-PR-K8s-1.13-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/manifests/l3-policy-demo.yaml: Cannot retrieve cilium pod cilium-w648c policy revision: cannot get the revision 
Expected
    <*errors.errorString | 0xc0016e5800>: {
        s: "Cannot retrieve cilium pod cilium-w648c policy revision: cannot get the revision ",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.13-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:717
```
[5c75b5d9_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip](https://github.com/cilium/cilium/files/6044847/5c75b5d9_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip)

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-kernel-4.9/17/testReport/junit/Suite-k8s-1/13/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/

**Comment by christarazi** [comment]
Seen in https://github.com/cilium/cilium/pull/15099#issuecomment-786067315

**Comment by pchaigno** [comment]
From `test-output.log`, we have:
```
time="2021-02-24T21:31:25Z" level=debug msg="running command: kubectl exec -n kube-system cilium-w648c -- cilium policy get -o json"
time="2021-02-24T21:31:35Z" level=error msg="Error executing command 'kubectl exec -n kube-system cilium-w648c -- cilium policy get -o json'" error="signal: killed"
time="2021-02-24T21:31:35Z" level=error msg="Error executing command 'kubectl exec -n kube-system cilium-w648c -- cilium policy get -o json'" error="signal: killed"
cmd: "kubectl exec -n kube-system cilium-w648c -- cilium policy get -o json" exitCode: -1 duration: 10.002306905s stdout:

err:
signal: killed
time="2021-02-24T21:31:35Z" level=error msg="cannot retrieve cilium pod policy revision" error="cannot get the revision "
time="2021-02-24T21:31:35Z" level=error msg="cannot retrieve cilium pod policy revision" error="cannot get the revision "
FAIL: Error creating resource /home/jenkins/workspace/Cilium-PR-K8s-1.13-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/manifests/l3-policy-demo.yaml: Cannot retrieve cilium pod cilium-w648c policy revision: cannot get the revision 
Expected
    <*errors.errorString | 0xc0016e5800>: {
        s: "Cannot retrieve cilium pod cilium-w648c policy revision: cannot get the revision ",
    }
to be nil
```
As can be seen from the `signal: killed` and the timestamp between the first two lines, we reached the 10s timeout while calling `cilium policy get`.

From the bugtool, there seem to be a bit of load on the agent and at least one endpoint was being created/generated at the time `cilium policy get` was executed. We can also see that the load average is increasing. Despite that, 10s still seems a bit high :thinking: https://github.com/cilium/cilium/pull/15127 should give us a bit more visibility into the agent's load by reenabling debug mode for the present test.

We may just need to bump the timeout a bit.

**Comment by pchaigno** [comment]
Did not happen again recently according to https://datastudio.google.com/s/loYNtDAdc2M. Closing.
