### ISSUE TITLE
CI: Missing artifact for K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) 

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15128]
The following tests are always missing artifacts:
```
K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy)
K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) with the host firewall and externalTrafficPolicy=Local
K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) with externalTrafficPolicy=Local
K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) with IPSec and externalTrafficPolicy=Local
```
You can view a list of recent failures (which should have artifacts) here: https://datastudio.google.com/s/gJ_3b2imuI0.

**Comment by pchaigno** [comment]
Still happening and annoying at times.

**Comment by brb** [comment]
Does this happen always? Is there any special non-generic step in the CI for collecting artifacts?

**Comment by pchaigno** [comment]
I think this is happening because of the parenthesis in the test's name. I just need to find Jenkins logs to fix it---they have all been recycled.

If anyone hits this, please share the link to the Jenkins logs before it expires :pray:
