### ISSUE TITLE
Pass context into BackendOperations.Close()

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#15133]
The `BackendOperations` interface does not currently pass a Context object into the `Close()` function, but the `Close()` function may perform blocking operations with the kvstore. It seems like at the very least for handling proper daemon shutdown or termination of individual clustermesh controllers, we should pass the context down from `restartRemoteConnection()` into the kvstore backend close operations.

**Comment by aanm** [comment]
We might not want that behavior as Close needs to block to make sure sessions are expired.
