### ISSUE TITLE
Migrate over to glide for dependency management

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1514]
vndr does not import transitive dependencies, which makes importing large projects a nightmare. Move over to [glide](https://github.com/Masterminds/glide), which is much more widely used.

**Comment by ianvernon** [comment]
Closing this. I think actually that `vndr` not supporting transitive dependencies isn't a bad thing; we have to add dependencies one at a time.

To add dependencies effectively in a manner that works, I have done the following:
1) Add whatever new dependency I need with `vndr <repo> <tag / commit ID>`. 
2) Compile Cilium in the dev VM (`make`)
3) If I hit a compilation failure due to a dependency of the new dependency (transitive dependency) not being found, manually go to the dependency's list of dependencies, and figure out what version of that dependency they are using.
4) `vndr` the new dependency and try compiling again.

While tedious, this ensures that we do not have a tool like glide making decisions when two dependencies that we use need a different version of the same dependency, which is the case.

**Comment by aanm** [comment]
@ianvernon vndr also warns you if a dependency is not in vendor.conf.
