### ISSUE TITLE
Convert maps to libbpf/BTF-style map definitions

### ISSUE THREAD

**Issue by ti-mo** [cilium/cilium#15149]
## Proposal / RFE

Currently, we use iproute2-style BPF map definitions that are not (going to be) compatible with libbpf. The community's consensus is to consider libbpf being 'the spec', and libbpf-style map definitions are much more flexible since they leverage BTF. Maps that use any of the below features will need to be converted to libbpf-compatible definitions in order to be properly loaded by `cilium/ebpf`. (meaning they would no longer rely on `bpf_elf_map`)

- pinning
- map-in-map declarations
- inner map prepopulation and configuration (`inner_idx`)
- map config flags, like conditional prealloc (`flags`)

This constitutes most of the maps we use, and only the Maglev maps are currently using `inner_id(x)`.

@borkmann @joestringer `cilium-map-migrate` is also likely a critical piece that needs to be tackled. Could you shed some light on what this does and what would be required of `cilium/ebpf` to enable its functionality? I have a vague idea, but could use some background info.

---

## Work

- [x] Load inner map definitions from ELF (https://github.com/cilium/ebpf/pull/218)
- [x] Statically declare the contents of a `PROG_ARRAY` (https://github.com/cilium/ebpf/issues/214) through (https://github.com/cilium/ebpf/pull/357)
- [x] Statically declare the contents of a `ARRAY_OF_MAPS`, `HASH_OF_MAPS` (https://github.com/cilium/ebpf/issues/112)
- [x] Support trailing values after `struct bpf_map_def` for out-of-band parsing
  This would allow us to load 'unmodified' ELFs with `cilium/ebpf` to stay compatible with `cilium-map-migrate` and other parts of the iproute2 tooling. However, we'd have to implement pinning and map-in-map loading directly in the Cilium agent, which might be more trouble than it's worth.
  This PR (https://github.com/cilium/ebpf/pull/360) proposes an alternative approach. Parsing `bpf_elf_map` is supported up to its pinning field, allowing us to re-use existing map definitions except for the one map that relies on map-in-map, Maglev. That one will have to be converted to BTF.

**Comment by joestringer** [comment]
@ti-mo sorry, I missed this somehow.

The background to `cilium-map-migrate` can be found in PR https://github.com/cilium/cilium/pull/3267 .

**Comment by brb** [comment]
This issue might be blocked by https://github.com/cilium/cilium/issues/16668, as BTF generated by LLVM 10 (shipped in the cilium-agent image) is rejected by libbpf.

**Comment by ti-mo** [comment]
@brb Are you sure the BTF is broken? The issue you linked is about bytecode.

**Comment by brb** [comment]
The issue is for LLVM 12 which we want to start using. LLVM 12 should generate a valid BTF which libbpf would accept.

**Comment by ti-mo** [comment]
Parsing extra iproute2 bpf_elf_map fields is possible since https://github.com/cilium/ebpf/pull/362.

`cilium-map-migrate` porting is in progress, and I'm going to take a stab at porting init.sh to Go.

@brb's work on iproute2+libbpf could make converting maps to libbpf-style possible in parallel. Landing this simultaneously with a full transition to `cilium/ebpf` could be tricky, so it could be done before that. WDYT?

**Comment by brb** [comment]
Yep we could convert all maps to libbpf today (minus the maglev and the tail calls).
