### ISSUE TITLE
Missing backend(s) for manually created EndpointSlice

### ISSUE THREAD

**Issue by mariuskiessling** [cilium/cilium#15142]
## Bug report

This bug report is a follow-up of the discussion on [Cilium's Slack channel](https://cilium.slack.com/archives/C1MATJ5U5/p1614344823093300).

We are running K8s 1.18 which does not support automatically mirroring Endpoints to EndpointSlices yet. The cluster routing is done without kube-proxy using the replacement from Cilium. We have a service which is backed by a manually created endpoint pointing to an external endpoint (in my example below `1.1.1.1:443`. Thus, we also create a manual EndpointSlice object which should be picked up cilium to create its internal service from it. However, even though cilium properly assigns the frontend address (in the example below `172.30.90.95:443` to the newly created service (`801`), the backend address is not assigned. This can be 'fixed' by manually updating the service using the Cilium CLI and the command:

```
$ cilium service update --id 801 --frontend "172.30.90.95:443" --backends "1.1.1.1:443"
Updating existing service with id '801'
Updated service with 1 backends
```

Interestingly, the Cilium CLI is reporting an error when not specifying the frontend address in the update command, although this might be unrelated.

```
$ cilium service update --id 801 --backends "1.1.1.1:443"
Updating existing service with id '801'
Error: L4 backend found (1.1.1.1:443) with L3 frontend
```

**General Information**

- Cilium version:
  ```
  Client: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
  Daemon: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
  ```
- Cilium status:
  ```
  KVStore:                Ok   etcd: 3/3 connected, lease-ID=2f2c77d29a100ebf, lock lease- 
  ID=522177d28aea08fc, has-quorum=true: http://xxx:2379 - 3.3.25; http://xxx:2379 - 3.3.25; 
  http://xxx:2379 - 3.3.25 (Leader)
  Kubernetes:             Ok   1.18 (v1.18.6) [linux/amd64]
  Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", 
  "cilium/v2::CiliumNetworkPolicy", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", 
  "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
  KubeProxyReplacement:   Strict   [ens4 (Direct Routing)]
  Cilium:                 Ok       OK
  NodeMonitor:            Listening for events on 4 CPUs with 64x4096 of shared memory
                          2060207 events lost, 0 unknown notifications
  Cilium health daemon:   Ok
  IPAM:                   IPv4: 4/255 allocated from 172.20.6.0/24,
  BandwidthManager:       Disabled
  Host Routing:           Legacy
  Masquerading:           BPF   [ens4]   172.20.6.0/24
  Controller Status:      37/37 healthy
  Proxy Status:           OK, ip 172.20.6.59, 0 redirects active on ports 10000-20000
  Hubble:                 Ok                Current/Max Flows: 4096/4096 (100.00%), Flows/s: 2602.21   
  Metrics: Ok
  Cluster health:         21/21 reachable   (2021-03-01T11:29:38Z)
  ```
- Kernel version:
  ```
  Linux master0 5.4.0-1037-gcp #40~18.04.1-Ubuntu SMP Fri Feb 5 15:41:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  ```
- Orchestration system version in use:
  - K8s v1.18.6
- Link to relevant artifacts:
  - [Endpointslice, Endpoint and Service resource definition](https://gist.github.com/mariuskiessling/d4a09a54ae5506d1060aa2e7055d6c7c)
  - [Cilium agent log excerpt after resource creation](https://gist.github.com/mariuskiessling/47292075b62fe9bed1af7ec4ff10c169)
  - Filtered output of `cilium service list`:
    `801   172.30.90.95:443      ClusterIP` ← notice the missing backend

I omitted the sysdump for now as it would take me quite a bit of work to redact the details due to the nature of the cluster. If you need it for you investigation, I will happily supply it.

**How to reproduce the issue**

1. Boostrap a K8s 1.18 cluster with Cilium 1.9.4 running with the kube-proxy replacement enabled.
2. Deploy the example resource definition from above.
3. Observe outgoing `SYN` packets using tcpdump that never reach the target host.

**Comment by aanm** [comment]
Thanks for opening the GH issue, as far as Cilium behavior it is working as expected since the EndpointSlice condition is non-nil and it's not marked as ready.

https://github.com/cilium/cilium/blob/58d8b1dd33bf3abb02e3a82f919814bd39b1364d/pkg/k8s/endpoints.go#L166-L173

```bash
$ kubectl create -f https://gist.githubusercontent.com/mariuskiessling/d4a09a54ae5506d1060aa2e7055d6c7c/raw/0ecb96e3ca88ef274f959fc4cdf84708b8566405/cilium_eps_ep_s.yaml
endpointslice.discovery.k8s.io/example created
endpoints/example created
service/example created
$ kubectl get endpointslice example  -o yaml
addressType: IPv4
apiVersion: discovery.k8s.io/v1beta1
endpoints:
- addresses:
  - 1.1.1.1
  conditions: {}
kind: EndpointSlice
metadata:
  creationTimestamp: "2021-03-01T14:28:52Z"
  generation: 1
  labels:
    kubernetes.io/service-name: example
  managedFields:
  - apiVersion: discovery.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:addressType: {}
      f:endpoints: {}
      f:metadata:
        f:labels:
          .: {}
          f:kubernetes.io/service-name: {}
      f:ports: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-01T14:28:52Z"
  name: example
  namespace: default
  resourceVersion: "307416"
  uid: 250a1f79-42a4-4504-8e3c-d8eeba4a7019
ports:
- name: https
  port: 443
  protocol: TCP
```

**Comment by mariuskiessling** [comment]
Good catch, thanks for the hint and the quick investigation! I have updated the [resource definition file](https://gist.githubusercontent.com/mariuskiessling/d4a09a54ae5506d1060aa2e7055d6c7c/raw/1921fd29cff71ecc831c357095bb4befbf0102d3/cilium_eps_ep_s.yaml) with a static definition of the ready condition, setting it to `true`. However, Cilium is still not picking up the backend for that service. Can you replicate this on your end?

**Comment by aanm** [comment]
likely because the endpoint slice contains a named port that doesn't exist in the service.

**Comment by aditighag** [comment]
@mariuskiessling It might be helpful to run `kubectl get endpoints` command first to see if everything is set up correctly for k8s API server to generate the relevant updates.

**Comment by mariuskiessling** [comment]
Thank you very much you two. The missing backend was indeed caused by the fact that the port in the service, even though it held the same protocol and port, was missing. With the name added to the service, everything works as expected. Thank you very much for all the support!
