### ISSUE TITLE
helm: `extraArgs` refactoring

### ISSUE THREAD

**Issue by nbusseneau** [cilium/cilium#15150]
Follow-up issue from discussion in https://github.com/cilium/cilium/pull/14974#issuecomment-786024908.

To do:

- [ ] Replace current top-level object-based `extraArgs` in `values.yaml` with array-based `extraArgs`, and edit `cilium-agent-daemonset.yaml` template accordingly
- [ ] Document Helm chart breaking change (release notes?)
- [ ] Implement and document identical array-based `extraArgs` for all sub-components

Implementing this will fix #14944.

**Comment by Skymirrh** [comment]
Ping @D1abloRUS @funkypenguin since you were both authoring PRs on this topic, in case you are interested in implementing this.

**Comment by D1abloRUS** [comment]
Hey! I will try to implement in the near future
