### ISSUE TITLE
CI: Precheck fails on 1.9

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#15169]
Example failing run: https://jenkins.cilium.io/view/Cilium-v1.9/job/cilium-v1.9-k8s-1.19-kernel-4.9/533/

Most k8s jobs failing here due to this bug: https://jenkins.cilium.io/view/Cilium-v1.9/

Is precheck actually necessary in 1.9 with all backported github actions?

**Comment by nebril** [comment]
This fails also on 1.8 and 1.7, definitely requires a proper fix

**Comment by nebril** [comment]
Ran `docker compose` with `verbose` flag: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/1566/execution/node/66/log/ looks like it gets stuck on 
```
14:27:19  compose.cli.main.call_docker: /usr/bin/docker start --attach --interactive e1ade34d692a0fdb0d79dc94a3ac0c022d5b9f9e60b601fa12c96d7aed8f1456
```

**Comment by nebril** [comment]
This seems to be caused by https://github.com/moby/moby/issues/42093

**Comment by pchaigno** [comment]
Fix was merged, closing.
