### ISSUE TITLE
host machine could not reached by ip after removing cilium with ipv6 enabled

### ISSUE THREAD

**Issue by lrouter** [cilium/cilium#15181]
## Bug report

**General Information**

- Cilium version 
Client: 1.9.1 442d5398a 2021-01-05T20:42:14+08:00 go version go1.15.5 linux/arm64
Daemon: 1.9.1 442d5398a 2021-01-05T20:42:14+08:00 go version go1.15.5 linux/arm64
- Kernel version (run `uname -a`)
Linux n149-136-211 4.19.117.bsk.2-amd64 #4.19.117.bsk.2 SMP Debian 4.19.117.bsk.2 Tue Jun 30 01:28:10 UT x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**How to reproduce the issue**

1. official cilium yaml file. change cilium config to enable ipv6:
  enable-ipv6: "true"
  enable-ipv6-ndp: "false"
  cluster-pool-ipv6-cidr: "fd00::/64"
  cluster-pool-ipv6-mask-size: "80"
2.install cilium
3. remove cilium
4. host machine could not reached by host ip. ping fails.

**Comment by pchaigno** [comment]
How did you remove Cilium? By deleting the YAML file?

Could you run `bpftool net` on the host machine? If any BPF programs have been left behind, that should tell us.

**Comment by lrouter** [comment]
> How did you remove Cilium? By deleting the YAML file?
> 
> Could you run `bpftool net` on the host machine? If any BPF programs have been left behind, that should tell us.

Yes, by deleting yaml file. The machine could not be reached anyway by ssh. So I have to reboot it.

**Comment by pchaigno** [comment]
>     1. official cilium yaml file.

Do you mean that one? https://github.com/cilium/cilium/blob/v1.9.1/install/kubernetes/quick-install.yaml

It might be worth trying to disable `kube-proxy-replacement` to see if the problem remains.

**Comment by lrouter** [comment]
> > ```
> > 1. official cilium yaml file.
> > ```
> 
> Do you mean that one? https://github.com/cilium/cilium/blob/v1.9.1/install/kubernetes/quick-install.yaml
> 
> It might be worth trying to disable `kube-proxy-replacement` to see if the problem remains.

OK, I will try it.
