### ISSUE TITLE
PolicyAuditMode can't be turned off at runtime if cilium-agent starts with it enabled

### ISSUE THREAD

**Issue by ArthurChiao** [cilium/cilium#15197]
## Bug report

If PolicyAuditMode is enabled when cilium-agent starts, then disable it with CLIs does work, such as

1. `cilium config PolicyAuditMode=false`
2. `cilium endpoint config <ep_id> PolicyAuditMode=false`

## Root cause

In short,

1. If audit mode is enabled at startup, agent will write `#define POLICY_AUDIT_MODE 1` to `node_config.h`
2. When disable it with CLI, the agent will not pass `PolicyAuditMode` changes to `init.sh`, and the later is responsible for manipulating the `node_config.h`
3. Endpoints will include `node_config.h` when generating BPF, so the macro `POLICY_AUDIT_MODE` is always defined for them.
4. Audit handling code in BPF is conditionally compiled with `#ifdef POLICY_AUDIT_MODE`

As a quick test, the following patch (based on `1.8.4`) would make `cilium config PolicyAuditMode=false` work:

```diff
diff --git a/bpf/init.sh b/bpf/init.sh
index 7ecffc942..1b50f0dbb 100755
--- a/bpf/init.sh
+++ b/bpf/init.sh
@@ -37,6 +37,7 @@ MCPU=${19}
 NODE_PORT_IPV4_ADDRS=${20}
 NODE_PORT_IPV6_ADDRS=${21}
 NR_CPUS=${22}
+POLICY_AUDIT_MODE=${23}

 ID_HOST=1
 ID_WORLD=2
@@ -482,6 +483,11 @@ case "${MODE}" in
                        MAC_BY_IFINDEX_MACRO="${MAC_BY_IFINDEX_MACRO}${MAC_BY_IFINDEX_MACRO_END}"
                        echo -e "${MAC_BY_IFINDEX_MACRO}" >> $RUNDIR/globals/node_config.h
                fi
+
+        sed -i '/POLICY_AUDIT_MODE/d' $RUNDIR/globals/node_config.h
+        if [ "$POLICY_AUDIT_MODE" = "1" ]; then
+            echo "#define POLICY_AUDIT_MODE 1" >> $RUNDIR/globals/node_config.h
+        fi
 esac

 # Address management
diff --git a/pkg/datapath/loader/base.go b/pkg/datapath/loader/base.go
index de10de033..7d159ada6 100644
--- a/pkg/datapath/loader/base.go
+++ b/pkg/datapath/loader/base.go
@@ -67,6 +67,7 @@ const (
        initArgNodePortIPv4Addrs
        initArgNodePortIPv6Addrs
        initArgNrCPUs
+       initArgPolicyAuditMode
        initArgMax
 )

@@ -339,6 +340,7 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,

        args[initBPFCPU] = GetBPFCPU()
        args[initArgNrCPUs] = fmt.Sprintf("%d", common.GetNumPossibleCPUs(log))
+       args[initArgPolicyAuditMode] = fmt.Sprintf("%v", option.Config.Opts.Opts[option.PolicyAuditMode])
```

But to make `cilium endpoint config <ep> PolicyAuditMode=false` work, further changes are needed.

**This problem exists in all versions of Cilium**, and I'd like to file a formal PR to fix it if the problem is confirmed.

Thanks!

**Comment by pchaigno** [comment]
I think we should move `POLICY_AUDIT_MODE` from `node_config.h` to the individual `ep_config.h` header files. The fact it can be configured per endpoint with `cilium endpoint config` implies it's a per-endpoint setting and shouldn't be in `node_config.h` IMO.

**Comment by ArthurChiao** [comment]
> I think we should move POLICY_AUDIT_MODE from node_config.h to the individual ep_config.h header files.

It seems that `POLICY_AUDIT_MODE` is already in `ep_config.h` and `lxc_config.h` of each endpoint, e.g.

```shell
root@node:/var/run/cilium/state  # cilium endpoint config 154 PolicyAuditMode=false
root@node:/var/run/cilium/state  # grep POLICY_AUDIT_MODE 154/lxc_config.h
#undef POLICY_AUDIT_MODE

root@node:/var/run/cilium/state  # cilium endpoint config 154 PolicyAuditMode=true
root@node:/var/run/cilium/state  # grep POLICY_AUDIT_MODE 154/lxc_config.h
#define POLICY_AUDIT_MODE 1
```

but this declaration will be overridden when generating BPF if the macro is defined in node_config.h.

> The fact it can be configured per endpoint with cilium endpoint config implies it's a per-endpoint setting and shouldn't be in node_config.h

Makes sense to me, I'll take a further look, thanks! @pchaigno

**Comment by ArthurChiao** [comment]
Hi @pchaigno, according to my test, directly remove the macro from node_config.h works (PR #15218). Not sure if there are cases that still rely on this flag in node_config.h? @pchaigno

**Comment by pchaigno** [comment]
If the macro is already in all `ep_config.h` files, I think #15218 will be enough.
