### ISSUE TITLE
FIB lookup failed DROPPED on nodes that are in the same AZ with nodes where the Service pods work

### ISSUE THREAD

**Issue by kovalyukm** [cilium/cilium#15200]
## Bug report

Hello,
There is an issue on AWS EKS clusters.
NodePort of Services (type NodePort and LoadBalancer) is not responding with connection timed out on the nodes which are in the same availability zones with nodes where Service pods work (so, NodePort works on nodes in different AZs and nodes with Service pods).

There are used the latest versions of components:
Kubernetes version 1.19
Amazon VPC CNI plug-in 1.7.9
KubeProxy deleted
AMI v1.19.6-eks-49a6c0
KERNEL-VERSION 5.4.91-41.139.amzn2.x86_64
and Cilium 1.9.4 (kubeProxyReplacement: strict).

There are no suspicious errors in logs:
```yaml
kubectl -n kube-system logs cilium-l2c7n --tail -1 | grep error

level=info msg="BPF system config check: NOT OK." error="Kernel Config file not found" subsys=linux-datapath
level=info msg="Auto-disabling \"enable-bpf-clock-probe\" feature since KERNEL_HZ cannot be determined" error="Cannot probe CONFIG_HZ" subsys=daemon
level=error msg="Command execution failed" cmd="[iptables -t mangle -n -L CILIUM_PRE_mangle]" error="exit status 1" subsys=iptables
```

Cilium configuration:
```yaml
    policyAuditMode: true
    policyEnforcementMode: "always"

    kubeProxyReplacement: strict
    k8sServiceHost: xxx.eks.amazonaws.com
    k8sServicePort: 443
    svcSourceRangeCheck: false

    cni:
      chainingMode: aws-cni
    masquerade: false
    tunnel: disabled
    nodeinit:
      enabled: true
```

```text
curl -I http://<NODE_IP>:30080
curl: (28) Connection timed out after 2000 milliseconds

# cilium monitor --type drop -v 
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (FIB lookup failed) flow 0x849b849b to endpoint 0, identity 0->0: <NODE_IP>:39578 -> <POD_IP>:9090 tcp SYN
xx drop (FIB lookup failed) flow 0x849b849b to endpoint 0, identity 0->0: <NODE_IP>:39578 -> <POD_IP>:9090 tcp SYN
...
```

```text
➭ hubble observe -f --type drop
Handling connection for 4245
Mar  4 10:07:18.457: <NODE_IP>:38580 -> kubernetes-dashboard/kubernetes-dashboard-6466669887-w75xt:9090 FIB lookup failed DROPPED (TCP Flags: SYN)
Mar  4 10:07:21.247: <NODE_IP>:38586 -> kubernetes-dashboard/kubernetes-dashboard-6466669887-w75xt:9090 FIB lookup failed DROPPED (TCP Flags: SYN)
...
```

```text
# cilium monitor --type drop -vv
------------------------------------------------------------------------------
CPU 01: MARK 0x262e262e FROM 946 DROP: 74 bytes, reason FIB lookup failed
level=info msg="Initializing dissection cache..." subsys=monitor
Ethernet        {Contents=[..14..] Payload=[..62..] SrcMAC=0a:a6:c1:92:6a:34 DstMAC=0a:3c:23:76:ec:6b EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=7239 Flags=DF FragOffset=0 TTL=255 Protocol=TCP Checksum=20911 SrcIP=<NODE_IP> DstIP=<POD_IP> Options=[] Padding=[]}
TCP     {Contents=[..40..] Payload=[] SrcPort=39590 DstPort=9090(websm) Seq=4211881838 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=26883 Checksum=52559 Urgent=0 Options=[..5..] Padding=[]}
------------------------------------------------------------------------------
CPU 01: MARK 0x262e262e FROM 946 DROP: 74 bytes, reason FIB lookup failed
Ethernet        {Contents=[..14..] Payload=[..62..] SrcMAC=0a:a6:c1:92:6a:34 DstMAC=0a:3c:23:76:ec:6b EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=7240 Flags=DF FragOffset=0 TTL=255 Protocol=TCP Checksum=20910 SrcIP=<NODE_IP> DstIP=<POD_IP> Options=[] Padding=[]}
TCP     {Contents=[..40..] Payload=[] SrcPort=39590 DstPort=9090(websm) Seq=4211881838 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=26883 Checksum=51556 Urgent=0 Options=[..5..] Padding=[]}
------------------------------------------------------------------------------
...
```

Seems there is no issue with accessibility from cluster nodes.

If scale Deployment to more then 1 replica there are still 'FIB lookup failed DROPPED' but NodePort is responding sometimes and it is enough to be 'InService' in AWS Load balancer, so sometimes cliens get time outs.

Thanks!

**Comment by brb** [comment]
@kovalyukm Thanks for the detailed issue. Could you run from the node which registered the drops: `ip route get <POD_IP>`?

**Comment by kovalyukm** [comment]
@brb Thanks!

```sh
# ip route get <POD_IP>
<POD_IP> dev eth0 src <NODE_IP> uid 0 
    cache 
```

BTW, to temporary fix the issue on the node:
```sh
# ping <POD_IP>
...
58 packets transmitted, 58 received, 0% packet loss, time 58187ms
rtt min/avg/max/mdev = 0.226/0.430/5.617/0.702 ms
```
till node reboot or pod restart.

**Comment by brb** [comment]
>  ip route get <POD_IP>
> <POD_IP> dev eth0 src <NODE_IP> uid 0 cache

I assume `<NODE_IP>` corresponds to an IP of a remote node running the pod? 

Could you grep the cilium-agent logs for `node-neigh` messages?

**Comment by kovalyukm** [comment]
<NODE_IP> is the node with the issue (all outputs above are from this node).
<POD_IP> is the pod that running on another node that is in the same AZ with the node with <NODE_IP>.

```sh
➭ kubectl -n kube-system logs cilium-l2c7n --tail -1 | grep neigh                                                                                          <aws:test>
level=info msg="option bpf-neigh-global-max set by dynamic sizing to 131072" subsys=config
level=info msg="  --bpf-neigh-global-max='524288'" subsys=daemon
```

**Comment by brb** [comment]
OK, so in the VPC mode the routing between Pods is handled by VPC, and we don't install a route to a remote pod in the same AZ, and the kernel assumes that Pods are L2-reachable.

Could you dump the neighbor table (`ip neigh show`) after pinging the Pod?

**Comment by kovalyukm** [comment]
There is no <POD_IP> in the neighbor table befor pinging, and after it:
```
<POD_IP> dev eth0 lladdr 02:1c:78:6c:e9:85 REACHABLE
```

**Comment by kovalyukm** [comment]
There is the same issue when using Cilium instead of kube-proxy and AWS-CNI.
```yaml
...
    kubeProxyReplacement: strict
    eni: true
    ipam:
      mode: eni
...
```

**Comment by kovalyukm** [comment]
@brb Hello!

There is the same issue for Installation using Getting Started Guides » Managed Kubernetes » Installation on AWS EKS on newly-created cluster:
Kubernetes version 1.19
KubeProxy v1.19.6-eksbuild.2
KERNEL-VERSION 5.4.95-42.163.amzn2.x86_64
Amazon VPC CNI plug-in - deleted
and Cilium 1.9.4

```yaml
    eni: true
    ipam:
      mode: eni
    egressMasqueradeInterfaces: eth0
    tunnel: disabled
    nodeinit:
      enabled: true
```
kubernetes-dashboard/kubernetes-dashboard-9b7fd6947-jx7jn:9090 FIB lookup failed DROPPED (TCP Flags: SYN)

**Comment by brb** [comment]
Could you set `kubeProxyReplacement=disabled`?

**Comment by kovalyukm** [comment]
It helped.
All LB target instances are InService, no timeouts from NodePorts and `hubble observe -f --type drop` shows only "Unsupported L3 protocol DROPPED (ICMPv6 RouterSolicitation)".

**Comment by brb** [comment]
Thanks for the confirmation. We are going to fix the issue in the v1.11 development cycle.

**Comment by brb** [comment]
@kovalyukm Could you check the latest cilium stable release (v1.10.3)  whether it has resolved your problem?

**Comment by kovalyukm** [comment]
For now cannot check and do not have test cluster.
I'll try to check during next upgrade and will write a comment.
Thanks.

**Comment by brb** [comment]
@kovalyukm Any update?

**Comment by borkmann** [comment]
Hi @kovalyukm, should be fixed with managed neighbor rework in latest master, please try with `quay.io/cilium/cilium-ci:latest` or 1.11-rc1 or later. If the issue still persists, please reopen in here. Thanks for your help!

**Comment by pinglamb** [comment]
Hi @brb @borkmann, I am running a EKS cluster with:

* K8S: 1.22
* Amazon VPC CNI: v1.11.0
* Cilium: v1.11.4
* Kube Proxy Replacement: `strict`

But still have the problem of reaching nodes in same AZ. Please help, thank you very much 🙏

**Comment by rayjanoka** [comment]
I needed something like this @pinglamb - there was some extra configuration for running on smaller instances (pre-allocate) if you are using those.

```json
eni:
  enabled: true
ipam:
  mode: eni
kubeProxyReplacement: strict
k8sServiceHost: https://api.whatever.com
k8sServicePort: 443
loadBalancer:
  algorithm: maglev
nodeinit:
  enabled: true
spec:
  ipam:
    pre-allocate: 4
tunnel: disabled
```

**Comment by pinglamb** [comment]
Here you are, it is of `chaining mode`:

```
cni:
  chainingMode: aws-cni
kubeProxyReplacement: strict
k8sServiceHost: [xxxx].eks.amazonaws.com
k8sServicePort: 443
tunnel: disabled
enableIPv4Masquerade: false
enableIPv6Masquerade: false
bpf:
  masquerade: false
nodeinit:
  enabled: false
```
