### ISSUE TITLE
Cilium: Encryption, remove ingress IPsec rules when no longer needed

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#15216]
When encryption is disabled we remove xfrm entries for remote nodes,
```
 NodeConfigurationChanged()
   n.removeEncryptRules()
   ipsec.DeleteXfrm()
```
This stops the node from sending encrypted traffic, because it no longer has rules/xfrm-state/policy to do this. However, we have to leave the ingress decrypt rules in place because its unclear when the remote nodes will be updated and we don't want to drop traffic if a remote node sends us an encrypted traffic. For example in large deployments a rolling update can take some time and so its not possible to just break traffic. Worse it can cause more than a disruption if we lose connection with critical services, apiService, kvstore, etc.

The current solution is to simply leave the decrypt rules in place. They will only ever be used if an encrypted packet is received then after all nodes have transitioned should never be used. This is mostly harmless, except for in a corner case here,
 
 1. enable encrypt with keyID=1 and key=foo
 2. disable encrypt with keyID=1
 3. (re)enable encrypt with keyID=1 and key=bar
 
When step3 is run and we (re)enable encrypt we attempt to install a new decrypt rule with the same ID but different key. This will collide with the left-over key from step1 and install will fail leaving a warning in the logs. To work-around above case we recommend setting keyID to some other value, replacing step3 with the following,

 3'. (re)enable encrypt with ikeyID=2 and key=bar
 
 The new keyID will get installed correctly and the old keyID will be removed after a timeout.
 
 This feature request is to delete keyID=1 in step2 after we recognize all nodes have been updated. We can determine this by reviewing the ipCache. If the key is no longer listed in the ipcache then all nodes have sent us an update with the new key state, in this case no key because we have deleted the key.
 
 This will remove the above corner case and also has the nice side benefit of removing stale rules in the policy/state of ipsec.

**Comment by Sangu80** [comment]
@jrfastab can i solve this issue ?

**Comment by pchaigno** [comment]
@Sangu80 I assigned you the issue. Don't hesitate to reach out on Slack (#sig-datapath, or #gsoc) if you have any questions. You can also reach out on #development if you have issues setting up the development environment.

**Comment by weirdwiz** [comment]
If there isn't any progress, could I have a stab at this?

**Comment by pchaigno** [comment]
@weirdwiz No news from @Sangu80 in the last month, so I'll assign you.
