### ISSUE TITLE
CI: Race Detector tests out of memory

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#15214]
Using Go race detector requires more memory (https://golang.org/doc/articles/race_detector#Runtime_Overheads):

> The cost of race detection varies by program, but for a typical program, memory usage may increase by 5-10x and execution time by 2-20x.
> 
> The race detector currently allocates an extra 8 bytes per defer and recover statement. Those extra allocations are not recovered until the goroutine exits. This means that if you have a long-running goroutine that is periodically issuing defer and recover calls, the program memory usage may grow without bound. These memory allocations will not show up in the output of runtime.ReadMemStats or runtime/pprof.
> 

CI race detector pipelines (https://jenkins.cilium.io/view/Race%20Detection/) have various Kafka test failures. Test output indicates that some of the kafka pods are stuck at `regenerating`:
```
cmd: kubectl exec -n kube-system cilium-hjdw4 -- cilium endpoint list
...
 63  Disabled  Disabled  6302  k8s:app=kafka   fd02::10   10.0.0.87   regenerating   
```
Logs of the Cilium pod (cilium-hjdw4) tell that Envoy is crashing when opening proxylib (which runs the Kafka parser):
```
 level=info msg="[GoFilter: Opening go module libcilium.so" subsys=envoy-filter threadID=15313
 level=info msg="==15313==ERROR: ThreadSanitizer failed to allocate 0x2af9000 (45060096) bytes at address 21fffd053c000 (errno: 12)" subsys=envoy-filter threadID=15313
 level=warning msg="Envoy: Proxy crashed" error="exit status 66" subsys=envoy-manager
```
`errno: 12` is `ENOMEM`, indicating that Go runtime within `libcilium.so` can not allocate memory.

This test fail is the most frequent cause for the race detector test run failure in the recent test runs. Running low on memory can also cause other types of errors that may seem "random" failures.

Proposed solution is to run race detector test pipelines with VMs that have more memory than normal test VMs.

**Comment by Skymirrh** [comment]
The current machines on Equinix Metal have 32GB RAM, and those on GKE have 15GB RAM. We could have separate pools with higher RAM for race detections, which would obviously cost more. Perhaps it would be worth first to check actual RAM usage and partitioning at the moment of crash, see if there's not something fishy?

**Comment by nbusseneau** [comment]
Tried to increase VM memory size from 8GB to 15GB and see if Kafka tests are still failing with OOM => they are. I would tend to think this confirms the hypothesis that we have an issue with these specific tests, and not the amount of memory (or lack, thereof). Otherwise, why would they be the only ones suddenly needing more than 15GB RAM? :thinking_face:

**Comment by nbusseneau** [comment]
Discussed in community meeting:

- LibCilium in Proxy may be incompatible with race detector in Golang
- Race detector is more useful for validating cilium-agent runtime behaviour, libcilium is very different so unlikely to benefit from this testing
- Can disable race detector for these test runs (kafka)
