### ISSUE TITLE
Populate prog_name during bpf prog load 

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#15229]
The `bpf()` syscall `struct bpf_attr` has a `prog_name` field which allows associating a name string with a program during load. This functionality appears to have been [available since Linux v4.15](github.com/torvalds/linux/commit/067cae47771c864604969fd902efe10916e0d79c). Adding support for this in our loader might be useful to assist debugging.

**Comment by qmonnet** [comment]
Would be fantastic to have :+1:.

Have you given some thought into what names should be used? In particular:
- Should the names be, for example, derived from the ELF section names the program code was stored in?
- Should they be prefixed with a `cilium-` marker or something like that?
- More generally, should these names be used for debug assistance only, or do we want to reserve the possibility to give them some semantic? I think @brb had a use case in mind at some point?

One detail to keep in mind is that the names can only be 16-byte long strings, including the ending `\0`.

**Comment by aditighag** [comment]
@joestringer The loader (cilium/ebpf) already [populates](https://github.com/cilium/ebpf/blob/master/prog.go#L189) `prog_name` field. I confirmed this by running a unit test.

**Comment by pchaigno** [comment]
@aditighag We don't use cilium/ebpf to load programs AFAIK. We use bpftool and tc.

**Comment by aditighag** [comment]
`Bpftool` already populates program names, I'm not sure about `tc`.

>Adding support for this in our loader 

I think @joestringer was referring to cilium/ebpf loader?

**Comment by aditighag** [comment]
Makes sense, yeah. I checked cilium/ebpf based on our eventual goal. I also updated my comment - `tc-bpf` doesn't seem to support populating prog names (most of our programs are currently loaded using that tc bpf loader). It may need kernel changes?

**Comment by joestringer** [comment]
I don't think tc-bpf or the kernel TC hookpoint should have any impact on this. Attaching an eBPF program to a TC hook point is a two step process - (1) Load the program; (2) Attach it at the TC hook point. iproute2 performs both of these steps, it likely just needs to figure out a name based on the ELF sections prior to (1) and pass it in with the syscall as part of (1).

**Comment by aditighag** [comment]
Yes, agreed that it's all managed by our internal iproute2. But the user facing API (tc-bpf in this case) only takes section names as arguments as opposed to other loaders like cilium/ebpf and bpftool. A BPF program can have multiple sections (e.g., `bpf_overlay.c` has `from-overlay` and `two-overlay`).

**Comment by pchaigno** [comment]
@aditighag A section is a program (can also be a map or maps of course). `bpf_overlay.o` for example, has multiple BPF programs, named `from-overlay`, `to-overlay`, etc.

**Comment by pchaigno** [comment]
The new version of iproute2 we use, with libbpf support, does set the program names when loading.
