### ISSUE TITLE
Source IP 169.254.254.1 received via overlay

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1526]
It seems possible to get into a state where a NodePort service is balanced onto another node and the source IP is masqueraded to the private IP of `cilium_host` (169.254.254.1).

**Comment by michi-covalent** [comment]
I got into this stage after restarting cilium pods.

**Comment by tgraf** [comment]
PR #1570 is likely addressing this issue, to be confirmed.

**Comment by tgraf** [comment]
Fixed by #1570
