### ISSUE TITLE
bugtool: Dump iptables-legacy rules

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15270]
In [bugtools](https://github.com/cilium/cilium/blob/888e8c95b3040ea408596a611448e0f16dbfe727/bugtool/cmd/configuration.go#L97), we dump the configuration from `iptables` and `ip6tables`. We should also dump the content of any `iptables-legacy` (and `ip6tables-legacy`) in case there are any rules. Such rules can introduce unintended behavior that is hard to debug without a dump.

**Comment by h3llix** [comment]
I would like to take up this issue

**Comment by h3llix** [comment]
I had a doubt . 
I tried dumping **iptables** inside my cilium pod using : 
`kubectl -n kube-system exec cilium-wx8gg -- iptables -L` and using 
`kubectl -n kube-system exec cilium-wx8gg -- iptables-legacy  -L`
and they both  were identical . 

Also i tried running `kubectl -n kube-system exec cilium-wx8gg -- iptables -V`. Output being ### iptables v1.8.4 (legacy)

So why are we explicitly trying to dump iptables-legacy ? Please correct me if i understood anything wrong

**Comment by pchaigno** [comment]
Ah, I see. [Depending on the system](https://github.com/cilium/cilium/blob/master/images/runtime/iptables-wrapper), we will map `iptables` to either `iptables-legacy` or `iptables-nft`. In that case, we probably want to dump both, just to be sure we always have a dump of all possible rules.

**Comment by h3llix** [comment]
Thanks . I got it
