### ISSUE TITLE
Log errors on upsert/delete of endpoint routes

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15282]
When configuring per-endpoint routes, we should log errors:
https://github.com/cilium/cilium/blob/fde0bdac8aa538996ce29cf8275c6f92e0663512/pkg/datapath/loader/loader.go#L348-L356

https://github.com/cilium/cilium/pull/15228 added code to remove the routes when per-endpoint routes are disabled. We should also log errors in that case, unless the error is `ENOENT` when attempting to remove a route that doesn't exist.

**Comment by h3llix** [comment]
I would like to take up this issue

**Comment by pchaigno** [comment]
@h3llix I assigned you. Don't hesitate to reach out on Slack (e.g., #development or #gsoc) if you hit any blocker or have questions.

**Comment by h3llix** [comment]
@pchaigno Can you please review my PR ?

**Comment by raokolagan** [comment]
I did some analysis on this issue and i will provide the solution.
@pchaigno, Please assign to me

**Comment by pchaigno** [comment]
@raokolagan This issue is already being worked on by someone else and there's a pull request available at #15339. You're welcome to review the PR in question though :smiley_cat:

**Comment by raokolagan** [comment]
@pchaigno , Thank you, i will review this PR and share my comments on this.

**Comment by aanm** [comment]
reopened by https://github.com/cilium/cilium/pull/15517
