### ISSUE TITLE
Add package builds to runtime tests

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1529]
It looks like cilium rpm was not working with rpm as described in #1528 

We should add the deb and rpm builds to the runtime tests.

**Comment by ianvernon** [comment]
This can be done as a parallel step for the build. Should we publish this as an artifact like we do with the logs?

**Comment by ianvernon** [comment]
Alternatively, we can create another Jenkins job that when triggered, builds these artifacts, e.g. when triggered with "test-me-please" we can trigger jobs:

* Cilium-Deb-Build
* Cilium-RPM-Build

This decouples the tests from the building of artifacts themselves. Having separate jobs makes the configuration of the Jenkinsfile less complicated as well.

This could be ran nightly as well.

Should we also build these packages for each given release of Cilium? E.g., the next `vx.y.z`.

**Comment by aanm** [comment]
@eloycoto FYI

**Comment by eloycoto** [comment]
Yes Yes, in my radar :-)

**Comment by ianvernon** [comment]
`v1.5` has us depending on a custom version of `iproute2` - this may cause issues in building these packages.
