### ISSUE TITLE
Hostnames resolution failed and Connections timeouts on pods after Cilium deletion

### ISSUE THREAD

**Issue by kovalyukm** [cilium/cilium#15330]
## Bug report

Hello,
There is an issue on EKS Kubernetes clusters after deletion Cilium helm release with chart version 1.9.x.

After deletion newly-created pods are failing with hostname resolution error and there are no errors in coredns logs.

After restarting of coredns the issue above disappears, but new issue starts on all other pods - 'i/o timeouts' between pods in the cluster.

Replacing of cluster worker nodes fixes the issues.

Seems the issue is on both Kubernetes version 1.18 and 1.19 and with any Cilium 1.9 version.

Thanks!

**Comment by pchaigno** [comment]
If the issue is happening after Cilium is deleted, what makes you think Cilium is responsible. Isn't some other CNI responsible for networking?

**Comment by kovalyukm** [comment]
Coz Cilium make changes on K8s worker nodes and is used as network policy engine along with AWS CNI. Apparently Cilium does not clenup after deletion, isn't it?

**Comment by pchaigno** [comment]
Did you try on the latest 1.9.X or 1.10.0?

**Comment by kovalyukm** [comment]
No. Were there related fixes?

**Comment by pchaigno** [comment]
Yes, specifically with AWS-CNI in v1.9.8.

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
