### ISSUE TITLE
In-using PodCIDR overrode by auto generated one in "legacy-scope" type IPAM during k8s apiserver flapping

### ISSUE THREAD

**Issue by ArthurChiao** [cilium/cilium#15345]
# Phenomenon

With IPAM type `IPAMHostScopeLegacy` (+ direct routing),
when **k8s apiserver is flapping** (jumping between `reachable` & `unreachable`), cilium-agent will restart.
And during this case, there is a possibility that **the PodCIDR the node is using will be overridden by an auto-generated one from cilium-agent**, which leads to all pod traffic be interrupted.

# Code logic (1.8.4) & trigger conditions

```
runDaemon                                                // daemon/daemon_main.go
  |-k8s.Init                                             // pkg/k8s/init.go
  |-NewDaemon                                            // daemon/daemon.go
    |-GetNodeSpec
    |  |-node := waitForNodeInformation
    |  |         |-retrieveNodeInformation
    |  |           |-GetNode                             // pkg/k8s/node.go
    |  |           | |-c.CoreV1().Nodes().Get(nodeName)
    |  |           |-ParseNode                           // pkg/k8s/node.go
    |  |             |- cidr.ParseCIDR
    |  |-if node != nil
    |  |   useNodeCIDR                                   // pkg/k8s/init.go
    |  |     |-node.SetIPv4AllocRange(n.IPv4AllocCIDR)
    |  |         |-ipv4AllocRange = cidr                 // pkg/node/address.go
    |  |-else
    |  |    if option.Config.K8sRequireIPv4PodCIDR
    |  |        log.Fatal()
    |  |
    |-bootstrapIPAM                                      // daemon/cmd/ipam.go
    |  |-if option.Config.IPv4Range != AutoCIDR
    |  |   allocCIDR := cidr.ParseCIDR(option.Config.IPv4Range)
    |  |   if !allocCIDR:
    |  |      log.Fatal()
    |  |
    |  |   node.SetIPv4AllocRange(allocCIDR)
    |  |         |-ipv4AllocRange = cidr                 // pkg/node/address.go
    |  |-AutoComplete                                    // pkg/node/address.go
    |  |  |-InitDefaultPrefix(option.Config.DirectRoutingDevice)
    |  |     if ipv4AllocRange == nil
    |  |       ipv4AllocRange = cidr.NewCIDR(ip4net) // Using autogenerated IPv4 allocation range
    |  |-d.ipam = ipam.NewIPAM
    |
    |-k8s.Client().AnnotateNode(cidr ...)       // daemon/daemon.go
    | |-updateNodeAnnotation                    // pkg/k8s/annotate.go
    |   |-c.CoreV1().Nodes().Update(node)
```

During agent start/restart, the following steps are executed in sequence:

1. Init k8s module: `k8s.Init()`

    Agent will **connect to k8s apiserver**, and if failed (with retries), **it will exit** (then restart again).
    The exit will **not hurt traffic of existing pods**, as BPF is not regenerated.

    If this step succeeds, it will go to step 2.

2. Some other initialization. Not related to this issue, skip them. After this step finishes, go to step 3.
3. Init PodCIDR by retrieving node info from apiserver.

    **If apiserver it not reachable with up to 15 retries** at this time (in `waitForNodeInformation()`),
    agent will stop retrying.
    Then, **with default `K8sRequireIPv4PodCIDR=false`, the agent will fall back to step 4**:

4. First fall back to parse PodCIDR from `ipv4-range` (default `auto`, which means empty), then further fall back to **auto-generate**.

# General Information

- Cilium version: 1.8.4 (~~the same for 1.9.x and `master`~~)
- Orchestration system version: k8s

# Considerations

Noticed that `K8sRequireIPv4PodCIDR` defaults to `true` for some types of IPAMs.

Not sure if I missed something, but it seems it's also reasonable to make it default to `true` for `hostscope-legacy` and `kubernetes` type IPAMs. This will **stop the fallback from step 3 to step 4**, in which case cilium-agent will just exit, complaining that `"Unable to derive PodCIDR from Kubernetes node resource, giving up"`. All existing pods on this node will not be affected.

If this behavior sounds reasonable, I'd like to file a PR.

Thanks in advance!

**Comment by pchaigno** [comment]
@ArthurChiao It seems this bug report fell through the cracks. Is it not an issue anymore?

**Comment by ArthurChiao** [comment]
This issue got no response during the last one month, so I just closed it :( 

And turning back to the problem described: it is still there - but only affects cilium `versions < 1.9`, as 1.9+ removed hostscope-legacy support.

I think append `ipamOption.IPAMHostScopeLegacy` to https://github.com/cilium/cilium/blob/v1.8/pkg/option/config.go#L2634 could solve the problem
Should I open a PR against branch `1.8`?

**Comment by christarazi** [comment]
@ArthurChiao yes feel free to open a PR against 1.8
