### ISSUE TITLE
cilium-ui is not working; envoy issue?

### ISSUE THREAD

**Issue by cyrilcros** [cilium/cilium#15353]
[cilium-sysdump-20210315-220238.zip](https://github.com/cilium/cilium/files/6144814/cilium-sysdump-20210315-220238.zip)

## Bug report

**General Information**

- Cilium version (run `cilium version`): **helm chart v1.9.5**
- Kernel version (run `uname -a`) **5.8.0-26-generic**
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) **Kubernetes v1.20.0**
- Link to relevant artifacts (policies, deployments scripts, ...): **just the helm chart with default values, with hubble and its metrics enabled, relay enabled, ui enabled with enabled ingress and working annotations (ingress-nginx / certmanager)**
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
**See top**
```

**How to reproduce the issue**

 Go to your hubble-ui ingress, get `upstream connect error or disconnect/reset before headers. reset reason: connection failure`.

- I can `kubectl exec` into a pod, cilium, hubble and hubble relay are fine.
- hubble-ui frontend is just nginx starting up, backend shows `hubble grpc client successfully created`
- the proxy may not be working. On a guess it could be an envoy failure as in https://github.com/grpc/grpc-web/issues/706 when googling `shutting down parent after drain`
-  I use cloudflare but disabled proxying / purged the cache / used dev mode
- I can't access the ui via `kubectl port-forward`, I get stuck on loading; the ingress doesn't matter
- I do not have any cluster mesh system, just cilium as my CNI

**Proxy end of logs**

`[2021-03-15 04:01:42.759][1][info][main] [source/server/server.cc:543] all clusters initialized. initializing init manager 
[2021-03-15 04:01:42.759][1][info][config] [source/server/listener_manager_impl.cc:725] all dependencies initialized. starting workers
[2021-03-15 04:01:42.763][1][info][main] [source/server/server.cc:564] starting main dispatch loop
[2021-03-15 04:16:42.762][1][info][main] [source/server/drain_manager_impl.cc:68] shutting down parent after drain `

**Comment by geakstr** [comment]
Hi @cyrilcros ! What port-forward command do you use?

**Comment by cyrilcros** [comment]
I reinstalled the chart and just tried `kubectl port-forward -n kube-system svc/hubble-ui --address 0.0.0.0 --address :: 12000:80 ` and it now works.
@geakstr Thanks for your help, I will just close this.
