### ISSUE TITLE
Kubernetes e2e suite.[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]

### ISSUE THREAD

**Issue by olemarkus** [cilium/cilium#15362]
Note this is a Kubernetes 1.21 conformance test.

Cilium 1.10 rc0
Kubernetes 1.21 beta.1
Kops master branch

Test logs/outputs, artifacts etc:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-scenario-cilium10-amd64/1371727866923847680

**Comment by olemarkus** [comment]
Probably a duplicate of https://github.com/cilium/cilium/issues/14287

**Comment by aditighag** [comment]
If the test is validating connectivity to loopback address on host port, and expecting protocol differentiation, then yes, it's a duplicate of #14287. 

From the logs - 
>Mar 16 07:54:37.240: INFO: Can not connect from e2e-host-exec to pod(pod1) to serverIP: 127.0.0.1, port: 54323
Mar 16 07:54:37.240: FAIL: Failed to connect to exposed host ports

Same as https://github.com/cilium/cilium/issues/14287#issuecomment-739027677.

>stderr:
+ nc -v -t -w 2 203.0.113.250 80
+ echo hostName
nc: connect to 203.0.113.250 port 80 (tcp) timed out: Operation in progress
command terminated with exit code 1

I don't have enough context to comment on this. @olemarkus Can you give some more information about this test?

**Comment by olemarkus** [comment]
Looks like. See https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/hostport.go#L61
