### ISSUE TITLE
Bugtool: Hash IPsec-related key so we can compare them, instead of omitting them

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#15375]
Bugtool is a utility that we may run in clusters to collect information on the Cilium agent and on the system, to help debug issues. One element it collects is the state of the IP XFRM framework, which transforms packets to encrypt them to implement IPsec in the cluster.

For confidentiality reasons, [the keys are trimmed out of the collected output](https://github.com/cilium/cilium/blob/v1.10.0-rc0/bugtool/cmd/configuration.go#L104). This prevents us from comparing keys, and from understanding whether they are all the same for all sources or if some differ (because they are older keys, or because some other bug occurred, for example).

Instead of omitting the keys, we could hash them, so that we could compare them and see which ones are identical. I'm not sure exactly how we would do it. The [AWK script could do it](https://stackoverflow.com/a/25276465/3716552) but the resulting command line would be huge, and since we're turning command into filenames for the output this may not be reasonable. We could maybe implement the hash as a filter in `runAll` for command containing `xfrm state` (we already have a specific processing for commands containing `tables`).

On a side note, and depending on how we implement it, this could be an occasion to revise the patterns in use for excluding the keys. Excluding `auth-trunc` seems redundant when we exclude `auth`, and `aead` might lead to the rare exclusion of hexadecimal string not otherwise related to [AEAD](https://www.kernel.org/doc/html/v5.11/crypto/api-aead.html).

**Comment by h3llix** [comment]
@qmonnet 
![bugtool](https://user-images.githubusercontent.com/55123900/112225850-6b947e00-8c53-11eb-8c1f-1c81f7661a4b.png)  I tried solving this issue , as well i have attached a screenshot to what i tried to reproduce . Is this the desired end result ? Also i am interested in solving this issue , Please assign it to me

**Comment by qmonnet** [comment]
Thanks! Assigned.
Yes, this is the idea. A few notes:

- There are other lines to process (see the current awk pattern, matching on `'!/auth|enc|aead|auth-trunc|comp/'`). I understand that you may well be aware of that and the screenshot is just for validating the concept :).

- Awk can work technically, but the resulting command may be too big to be reused as a filename. We would need to either truncate the filename in length, or maybe consider implementing this hashing in Go directly. I think the latter would probably be cleaner, and would avoid depending on too many tools (e.g. openssl) being available on the machine.

- It would be nice to have some visual indicator that the final value observed is a hash, maybe something like `[hash:4f45b...313b]` instead of just the hash string?

**Comment by h3llix** [comment]
@qmonnet sorry for the delay . I was having approach 1 in my mind , but can guide me how to hash keys during runtime in go (like maybe some refrences to existing functions)?

**Comment by qmonnet** [comment]
I'm no expert in hashing strings in go, but I see that we have several package using functions from the `crypto/sha256` or `crypto/sha512` packages. You could have a look at the relevant code.

```
$ git grep crypto/sha pkg
pkg/datapath/connector/add.go:  "crypto/sha256"
pkg/labels/labels.go:   "crypto/sha512"
pkg/datapath/loader/hash.go:    "crypto/sha256"
pkg/elf/elf_test.go:    "crypto/sha256"
```

The first two in the list, in particular, show that it is pretty straightforward to compute a SHA sum.

As explained above, this could be used to implement some post-processing on the output we get in `runAll()` the commands containing `xfrm state` (just like we already process commands containing `tables` in a specific way). We would need to:

1. Filter the lines containing keys, based on the patterns currently used in the `awk` command
2. “Parse” those lines to extract the keys (likely: retrieve an hexadecimal string at the expected position in the line)
3. Replace the keys by their hash
4. If we find a line with a key pattern in 1. but fail to parse it to extract the key in 2., it is probably safer to suppress the line entirely from the output to avoid leaking keys by mistake.

Does this help?

**Comment by h3llix** [comment]
@qmonnet, I have just tried to solve the issue. Can you please review it ?
