### ISSUE TITLE
Unnecessary iptables masquerade from pod to remote host in direct routing mode

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15403]
It was observered, that when running with iptables masquerade, the following rule will masquerade traffic sent from a pod to a remote Cilium host:
```
[3:252] -A CILIUM_POST_nat -s 10.154.2.0/24 ! -d 10.154.0.0/16 ! -o cilium_+ -m comment --comment "cilium masquerade non-cluster" -j MASQUERADE
```

Not only the masquerade is unnecessary in the direct routing mode, but also it might break the host-fw.

The BPF-based masquerade does not SNAT such packets.

**Comment by jibi** [comment]
To properly address this we'd need to keep an ipset with all the node IPs. While a proper solution is implemented, this issue can be worked around by either:
* switching to BPF masquerade
* using k8s ip-masq-agent

**Comment by brb** [comment]
@pchaigno Is it something we can get in v1.11?
