### ISSUE TITLE
Remove references to quick-install in documentation

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15417]
Some of the documented guides still reference the old quick-install.yaml file: https://docs.cilium.io/en/latest/gettingstarted/http/#setup-cilium. This should be removed to instead point to the existing installation guides.

**Comment by Palerion** [comment]
@pchaigno new contributor here, I'd love to take this one on!

**Comment by h3llix** [comment]
@pchaigno. Can you elaborate more on this issue? quick-install.yaml looks the same to me in the quick install guide and in the above mentioned link.

**Comment by pchaigno** [comment]
@h3llix That file doesn't exist anymore. The https://raw.githubusercontent.com/cilium/cilium/HEAD/install/kubernetes/quick-install.yaml link referenced in the guide returns a 404.

**Comment by h3llix** [comment]
okay sorry for not noticing that. Just one more question, Deploying via minkube no longer works?

**Comment by pchaigno** [comment]
I assume it's possible to deploy on Minikube via Helm instead. Maybe a question for #development?
