### ISSUE TITLE
Test flake 17-cilium_policy-id-remove.sh

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1542]
```
23:07:40 ==> cilium-master-build-PR-1530-8: ----- 17-cilium_policy-id-remove.sh: main: checking that only one cilium_policy map exists after containers have been removed
23:07:40 ==> cilium-master-build-PR-1530-8: ------------------------------------------------------------------------
23:07:40 ==> cilium-master-build-PR-1530-8:                             Test Failed
23:07:40 ==> cilium-master-build-PR-1530-8: want /sys/fs/bpf/tc/globals/cilium_policy got /sys/fs/bpf/tc/globals/cilium_policy
23:07:40 ==> cilium-master-build-PR-1530-8: /sys/fs/bpf/tc/globals/cilium_policy_18544
23:07:40 ==> cilium-master-build-PR-1530-8: /sys/fs/bpf/tc/globals/cilium_policy_62502
```
More info https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-1530/8/execution/node/28/log/

**Comment by aalemayhu** [comment]
@aanm are you sure this is a flake in the test and not a regression in the pull request that invoked the build? I can look into it but wanted to check first.

**Comment by aanm** [comment]
@scanf The previous build was successful https://github.com/cilium/cilium/pull/1530/commits and the only change made was a function refactoring.

From 06d7361ce6c3aaea46595402187a635309cf659b to 6948a4c8c4dfefc2871dfb87ee17cceeabb5369f in #1530

**Comment by aanm** [comment]
Reopening this as #1544 was not a real fix

**Comment by aalemayhu** [comment]
I think this is a timing issue where the endpoint deletion just takes a little longer and the removal check is reached. Waiting a bit longer might resolve it but need a reproduce to be certain.

**Comment by aalemayhu** [comment]
I think this is now resolved. Keeping it open in case it reoccurs in the near future but could be closed after some weeks.

**Comment by tgraf** [comment]
> I think this is now resolved. Keeping it open in case it reoccurs in the near future but could be closed after some weeks.

Let's close it, we can always reopen when it reoccurs.
