### ISSUE TITLE
Optimize for endpoints running egress gateway

### ISSUE THREAD

**Issue by anfernee** [cilium/cilium#15426]
In bpf_lxc.c: 
```c
#ifdef ENABLE_EGRESS_GATEWAY
    {
        struct egress_info *info;
        struct endpoint_key key = {};

        info = lookup_ip4_egress_endpoint(ip4->saddr, ip4->daddr);
        if (!info)
            goto skip_egress_gateway;

        /* Encap and redirect the packet to egress gateway node through a tunnel.
         * Even if the tunnel endpoint is on the same host, follow the same data
         * path to be consistent. In future, it can be optimized by directly
         * direct to external interface.
         */
        ret = encap_and_redirect_lxc(ctx, info->tunnel_endpoint, encrypt_key,
                         &key, SECLABEL, monitor, info->egress_ip);
        if (ret == IPSEC_ENDPOINT)
            goto encrypt_to_stack;
        else
            return ret;
    }
skip_egress_gateway:
#endif
```

Always going thru tunnel makes the egress gateway logic easier, and it's consistent for packets coming from both local and remote. However, it's obviously not efficient because the overlay overhead is not necessary. The issue here is it's hard to tell if the other end of tunnel is the node itself. Currently the egress IP to node mapping is not managed by any ebpf.

**Comment by pchaigno** [comment]
> The issue here is it's hard to tell if the other end of tunnel is the node itself. Currently the egress IP to node mapping is not managed by any ebpf.

Userspace can tell. From userspace, we can set `tunnel_endpoint` to 0 if it already points to the current node. Then, the datapath can take a decision based on that.
