### ISSUE TITLE
Don't require host reachable service (socket-LB) for ebpf masquerading

### ISSUE THREAD

**Issue by liuyuan10** [cilium/cilium#15437]
## Proposal / RFE

**Is your feature request related to a problem?**
Yes

**Describe the solution you'd like**
Today cilium requires host reachable svc to enable bpf masquerading, the restriction is added in this [commit](https://github.com/cilium/cilium/commit/50e59c309e6d86adad84dc175678a91dce6def03).

The reason is that when hostns pods talking to clusterIP, kernel picks node IP as source IP but not cilium_host IP. The packets are still tunneled to remote backend. Due to #12544, the return packet is masqueraded on the remote node. The real fix should be letting kernel pick cilium_host IP for such traffic so that we have symmetric data path.

The feature is useful for kernel < 4.19 where people can enable bpf nodeport and masquerading while keep host-reachable-svc off in kubeproxy partial mode.

Proposal:
Passing a --cilium-host-route-cidr flag to cilium-agent and install a route based on that flag:
```
[cilium-host-route-cidr] via 192.168.4.111 dev cilium_host src 192.168.4.111 mtu 1450
```

To make the implementation simpler, maybe we could always install this route when --cilium-host-route-cidr is passed regardless of other flags. So for whoever want to enable bpf masquerading without host-reachable-svc, he needs to pass --cilium-host-route-cidr

**Comment by borkmann** [comment]
Seems reasonable. Given this can be configured (https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address), I presume there is no programmatic way to retrieve this otherwise?

> To make the implementation simpler, maybe we could always install this route when --cilium-host-route-cidr is passed regardless of other flags.

Sounds ok to me as long as properly documented. @brb thoughts?

**Comment by liuyuan10** [comment]
@brb, please let me know what you think. thanks

**Comment by brb** [comment]
Requiring socket-LB for BPF masq hides two problems:

1. Unexpected SNAT of a reply packet to a pod in host netns when running in the tunneling mode. The culprit of this is that we don't do a CT lookup on egress to distinguish reply packets. However, even if we did the lookup, the reply would have run into the problem listed in the comment: https://github.com/cilium/cilium/blob/v1.9.5/bpf/lib/nodeport.h#L919-L926 \[1\]. Thus, the second problem below.
2. Routing asymmetry in the tunneling mode. Pod2pod and host2pod traffic goes via a tunnel, while pod2host is sent over a native device after the traffic has been masqueraded (otherwise, we would run into the \[1\] problem). This problem was mentioned in this PR https://github.com/cilium/cilium/pull/14611#issuecomment-760766052 too.

I'd be in favor of fixing both problems (they need to be resolved anyway) instead of introducing a new configuration option to install a custom route, as otherwise we would add more complexity into the datapath.

**Comment by liuyuan10** [comment]
@brb For host->clusterIP, I think it should go through tunnels in both ways so I don't think #1 matters here. For #2, yes, I think if we fix it, the FR should be also fixed where host->clusterIP goes through tunnel in both ways and source IP is node IP. Could you help to evaluate how hard it is to fix it? I haven't dig it deep enough but from the commit you referred, it seems to be a small change at [this line](https://github.com/cilium/cilium/blob/master/pkg/node/manager/manager.go#L369) to install the tunnel IP for node external IP. If it's a small scale change, I can take a stub.

**Comment by pchaigno** [comment]
> I haven't dig it deep enough but from the commit you referred, it seems to be a small change at this line to install the tunnel IP for node external IP.

The first part is a small change, but you'll also need something like https://github.com/cilium/cilium/pull/14756 to fix the issue introduced by sending all through the tunnel (cf. https://github.com/cilium/cilium/issues/14674).

**Comment by liuyuan10** [comment]
Thanks for the pointers. I think both changes are fairly small and I'll give it a try if that's all needed.

**Comment by liuyuan10** [comment]
One question, if all pod->node traffic goes through tunnel, how can a pod talk to nodeport? Especially when bpf nodeport is enabled, they are not run if packets are tunnelled to remote node.

**Comment by brb** [comment]
> One question, if all pod->node traffic goes through tunnel, how can a pod talk to nodeport?

Grep for `nodeport_lb` in `bpf_overlay.c` (NodePort BPF should be enabled on a tunnel device).

**Comment by brb** [comment]
> For host->clusterIP, I think it should go through tunnels in both ways so I don't think (1) matters here. 

Yes, just you will need to remove the following `ifndef`: https://github.com/cilium/cilium/blob/v1.9.5/bpf/lib/nodeport.h#L918.

**Comment by liuyuan10** [comment]
@pchaigno @brb  I tried to include similar fix as #14756 but that immediately breaks host -> pod flow. Say traffic comes from remote node cilium_host IP to local pod, it's redirected to lxc from overlay device bypassing kernel. But for return traffic, due to that change, it's pushed to kernel because the destination  is cilium_host IP, which is present in the IP cache. Because the traffic passes through kernel only in return path, it's dropped due to iptables rules programmed by kube-proxy. 

It seems #14756 is introducing more issues when nodeport is disabled.

**Comment by pchaigno** [comment]
@liuyuan10 I think we just need to avoid the `redirect()` from `cilium_vxlan` to `lxc` device on forward path, no? If per-endpoint routes are enabled, that should already be the case: https://github.com/cilium/cilium/blob/0218d373d2f8452720855a4a07b2719fd9826095/bpf/bpf_lxc.c#L1437-L1451

**Comment by borkmann** [comment]
> I think we just need to avoid the redirect() from cilium_vxlan to lxc device on forward path, no?

**Comment by borkmann** [comment]
> @liuyuan10 I think we just need to avoid the `redirect()` from `cilium_vxlan` to `lxc` device on forward path, no?

If we go that route, ideally just in a constraint setting (e.g. old kernels only) given this will introduce a performance regression for all tunnel traffic.

**Comment by pchaigno** [comment]
> > @liuyuan10 I think we just need to avoid the `redirect()` from `cilium_vxlan` to `lxc` device on forward path, no?
> 
> If we go that route, ideally just in a constraint setting (e.g. old kernels only) given this will likely introduce a performance regression (it's also incompatible with BPF host routing, but that's latest kernels only).

I think we only need to do that for `!defined(ENABLE_NODEPORT)` which is in phase with what we discussed a couple SIG-Datapath meetings ago: removing all path asymmetries when using kube-proxy.

**Comment by liuyuan10** [comment]
@pchaigno Thanks for the link. With that patch, I think when endpoint route is enabled, even pod to pod traffic is having asymetric path where vxlan->lxc is passing through kernel where return traffic doesn't not.

I think what you mean is when !ENABLE_NODEPORT, all traffic between vxlan and lxc should pass through kernel? let me prepare the patch

**Comment by liuyuan10** [comment]
I have a draft PR in  #15504 but there are several traffic flows having asynmetric paths (passing through kernel only one way). To me, the most worrisome case is hostns -> nodeport -> local pod when bpf node port is enabled.  hostns -> nodeport is through eth0 interface but return traffic is through tunnel. This looks very strange.  Please let me know what you do you guys think.

**Comment by batistein** [comment]
@pchaigno @liuyuan10 @borkmann  what is the current plan to support katacontainer even kube-proxy free? We really need this feature since we want to use a kube-proxy free environment now with the 1.11 release and the istio support.

**Comment by borkmann** [comment]
@batistein Did you try out v1.11 with https://isovalent.com/blog/post/2021-12-release-111#istio-kpr aka kube-proxy-free with `bpf-lb-sock-hostns-only: true` so that for Pod namespace it falls back to per-packet translation?

**Comment by sepich** [comment]
Unfortunately `hostServices.hostNamespaceOnly=true` still not enough for kata to reach k8s services (`kube-dns` for example). 
It only works with `hostServices.enabled=false` in cilium 1.11.1 (which breaks k8s svc access for hostNet pods)

**Comment by sepich** [comment]
Correction: `bpf-lb-sock-hostns-only: "true"` does not work for kata for kernel v5.4 (ubuntu 20.04).
Update kernel to v5.13 (linux-image-generic-hwe-20.04) fixes the issue. Now we can have kata containers able to reach k8s svc, and hostNet pods able to reach k8s svc at the same time on the same nodes with:
```
kubeProxyReplacement: "strict"
hostServices:
  hostNamespaceOnly: true
```

**Comment by danieljkemp** [comment]
```
kubeProxyReplacement: "strict"
hostServices:
  hostNamespaceOnly: true
```

This didn't seem to work as expected on cilium 1.15.5

Is `bpf-lb-sock-hostns-only: true` also required, or will kata+kube-proxy free not work currently? 

Thanks!

**Comment by brb** [comment]
> Is bpf-lb-sock-hostns-only: true also required, or will kata+kube-proxy free not work currently?

It's required for Kata containers to access K8s services. Please keep in mind that since opening this issue the Helm params have changed:
```
kubeProxyReplacement: true
socketLB:
  hostNamespaceOnly: true
```

**Comment by danieljkemp** [comment]
That full bit worked, thanks!

```
kubeProxyReplacement: true
bpf-lb-sock-hostns-only: true 
socketLB:
  hostNamespaceOnly: true
```

Sorry for spamming this issue but I had ended up here when trying to get it cilium+kata working because some parts of the docs were unclear. Specifically [here](https://docs.cilium.io/en/latest/network/kubernetes/kata/) the docs indicate that kube-proxy-replacement must be disabled. I also don't really understand the practical impact of the `socketLB.hostNamespaceOnly=true` and `bpf-lb-sock-hostns-only: true` settings so I have a bit more reading to do.

Thanks again! :)

**Comment by brb** [comment]
> Specifically [here](https://docs.cilium.io/en/latest/network/kubernetes/kata/) the docs indicate that kube-proxy-replacement must be disabled

Thanks for pointing this out. We will update the docs.

> I also don't really understand the practical impact

This section explains why it's needed - https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#socket-loadbalancer-bypass-in-pod-namespace
