### ISSUE TITLE
Cilium needs etcd, etcd needs coredns, coredns needs cilium

### ISSUE THREAD

**Issue by chenger** [cilium/cilium#15432]
So I have cluster with cilium 1.8.3 and after restart of all components coredns could not get address, cilium-etcd is stuck on init waiting for resolv of self and cilium could not start due to etcd not responding.

Any advices for workarounds?

**Comment by pchaigno** [comment]
Could you share a [sysdump](https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection) of the cluster?

**Comment by chenger** [comment]
ciliums ar down due to cilium-etcd is in init state so sysdump got many errors.
now kube-system looks that way:
cilium-2cm6w                                  0/1     CrashLoopBackOff    19         102m
cilium-4qc85                                  0/1     CrashLoopBackOff    19         102m
cilium-8fxbj                                  0/1     Running             17         102m
cilium-etcd-bt8gxn5dkn                        0/1     Init:0/1            0          16m
cilium-etcd-operator-565df66b46-vqk5g         1/1     Running             0          16m
cilium-gl7sd                                  0/1     CrashLoopBackOff    16         102m
cilium-hbnrf                                  0/1     CrashLoopBackOff    17         102m
cilium-jhb6m                                  0/1     CrashLoopBackOff    17         102m
cilium-node-init-7spq2                        1/1     Running             0          78m
cilium-node-init-f8pxz                        1/1     Running             0          78m
cilium-node-init-fbztf                        1/1     Running             0          78m
cilium-node-init-nlt2p                        1/1     Running             0          78m
cilium-node-init-nncz7                        1/1     Running             1          78m
cilium-node-init-sqd5f                        1/1     Running             1          78m
cilium-operator-64fd5f4dd4-g8pjl              0/1     CrashLoopBackOff    29         102m
coredns-7d9c8977bd-6qz6z                      0/1     ContainerCreating   0          66m
coredns-7d9c8977bd-sgz26                      0/1     ContainerCreating   0          66m

**Comment by chenger** [comment]
only worckaround is to disable etcd in cilium by now..

**Comment by errordeveloper** [comment]
> only worckaround is to disable etcd in cilium

You only need etcd if you cluster above 1k nodes, is that the case?

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
