### ISSUE TITLE
Log errors from bpf.TestDummyProg

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15448]
We currently rely on our function `bpf.TestDummyProg` to probe kernel support for some BPF hooks:
https://github.com/cilium/cilium/blob/08d0af46e46d460f87b506933c3701704ec52d8f/daemon/cmd/kube_proxy_replacement.go#L231-L250

When this function fails, we should log the returned error with `log.WithError(err)`.

**Comment by rgo3** [comment]
Hey @pchaigno, can I fix this?

**Comment by pchaigno** [comment]
@rgo3 Go ahead :rocket: As usual, don't hesitate to reach out on Slack if you have any question.

**Comment by rgo3** [comment]
Just to make sure:

you want to basically assign the `TestDummyProg(...)` calls to an `err` and call `log.WithError(err)` in case we enter the if statements right?

**Comment by pchaigno** [comment]
Yes, that's basically it. We should just log the actual error somewhere or we can't figure out what happened after the fact.

**Comment by rgo3** [comment]
Ok I'll go through the dev setup and will open a PR.
