### ISSUE TITLE
CI: K8sPolicyTest Multi-node policy test with L7 policy using connectivity-check to check datapath: connectivity-check pods are not ready after timeout

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#15459]
## CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-1.20-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
connectivity-check pods are not ready after timeout
Expected
    <*errors.errorString | 0xc000d89050>: {
        s: "timed out waiting for pods with filter  to be ready: 4m0s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.20-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/Policies.go:1698
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.9/1088/testReport/junit/Suite-k8s-1/20/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/

[35de3e43_K8sPolicyTest_Multi-node_policy_test_with_L7_policy_using_connectivity-check_to_check_datapath.zip](https://github.com/cilium/cilium/files/6201044/35de3e43_K8sPolicyTest_Multi-node_policy_test_with_L7_policy_using_connectivity-check_to_check_datapath.zip)

**Comment by christarazi** [comment]
Seen in https://github.com/cilium/cilium/pull/15384

**Comment by pchaigno** [comment]
This test failed because one endpoint is in CrashLoopBackOff. It tries to listen on port 41001 of the hostns, but fails. `ss--t--p--a--i--s.md` tells us that the cilium-agent is already listening on that port:
```
    LISTEN    0      128                         *:41001                          *:*                                                                                users:(("cilium-agent",pid=1,fd=24))
    	 cubic rto:1000 mss:536 cwnd:10 lastsnd:3124844 lastrcv:3124844 lastack:3124844
```
Not sure why the cilium-agent would listen on that port :thinking: I don't see any reference to that port in the source code...

**Comment by christarazi** [comment]
Oh that's interesting @pchaigno, good find. I think `41001` might be the Cilium  proxy port in this case. This theory aligns with the fact that this test failure is from the L7 suite. 

The port is not going to be in the source code because we don't usually care what the port is. We simply ask the OS to give us a free port.

**Comment by aditighag** [comment]
>I think 41001 might be the Cilium proxy port in this case. 

Yup, @christarazi beat me to it. :)

We should see check the [log](https://github.com/cilium/cilium/blob/master/pkg/fqdn/dnsproxy/proxy.go#L424) "DNS Proxy bound to address".

**Comment by christarazi** [comment]
Good find, filed https://github.com/cilium/cilium/issues/15986 for it

**Comment by pchaigno** [comment]
One mystery remained---fear not, this comment will solve quickly that---why are the flakes happening almost always with this `echo-c-host-container` container when we have several other pods running in host-network namespace, in the connectivity checks and in other tests?

Following the kernel sources, we can see that the bind(2) syscall [ends up calling `sk->sk_prot->get_port`](https://elixir.bootlin.com/linux/v5.12.1/source/net/ipv4/af_inet.c#L531), which in the case of TCP I believe is [`inet_csk_get_port`](https://elixir.bootlin.com/linux/v5.12.1/source/net/ipv4/inet_connection_sock.c#L354). That last function as an interesting comment:
```
/* Obtain a reference to a local port for the given sock,
 * if snum is zero it means select any available local port.
 * We try to allocate an odd port (and leave even ports for connect())
 *
```
Let's see what ports we use apart from 41001 in connectivity checks:
```
$ git grep -A1 "name: PORT" | grep -oP "(?<=value: \")\d+" | sort | uniq
41000
41001
8080
```
`echo-c-host-container` is the only hostns container using port 41001 and others use odd-numbered ports.

I'll send a PR to use 41002 instead and we'll see if that does the trick.

**Comment by aditighag** [comment]
Nice find! Although, in the case of DNS proxy, it's a UDP port. I don't see a similar comment for [UDP](https://elixir.bootlin.com/linux/v5.12.1/source/net/ipv4/udp.c#L345) (regular UDP doesn't have a `connect` call anyway).

**Comment by pchaigno** [comment]
> Although, in the case of DNS proxy, it's a UDP port. I don't see a similar comment for [UDP](https://elixir.bootlin.com/linux/v5.12.1/source/net/ipv4/udp.c#L345) (regular UDP doesn't have a `connect` call anyway).

It's both TCP and UDP actually: https://github.com/cilium/cilium/blob/4f27865e975cc095891b68df5f4a7bc0e26ecca5/pkg/fqdn/dnsproxy/proxy.go#L420-L424
The `echo-c-host-container` container is also only listening on TCP so the conflict is definitely on a TCP port.

**Comment by aditighag** [comment]
Yes, that's right. DNS proxy also supports TCP requests.
