### ISSUE TITLE
Remove force-local-policy-eval-at-source flag

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15452]
As its name indicates, the `force-local-policy-eval-at-source` flag force policy evaluation at the source (whether its bpf_lxc, bpf_host, or bpf_overlay): https://github.com/cilium/cilium/blob/a05461a3199b3da8d2558add032c8fffc7ff5c3d/bpf/lib/l3.h#L91-L105
Regardless of whether a BPF program is loaded on the egress of the lxc device (`USE_BPF_PROG_FOR_INGRESS_POLICY`), policies are enforced via a tail call. This causes packets to be processed twice when per-endpoint routes are enabled (cf. https://github.com/cilium/cilium/issues/14657).
The flag is currently enabled by default.

This flag was introduced in https://github.com/cilium/cilium/commit/c525c7555fc6ea84660a0a3721038f3b432caea8 and meant to introduce L7 issues on some kernels. Before disabling and removing that flag, we should:
- [x] Add policy tests to cilium connectivity test including L7 proxy tests.
- [x] Validate L7 proxy functionality with this flag disabled on various platforms (EKS, AKS, GKE).
- [x] Disable the flag by default.
- [x] Deprecate it.
- [ ] Remove it after another release in master.

**Comment by CBVenkataReddy** [comment]
I am planning take-up this issue
@pchaigno, Please assign to me.

**Comment by pchaigno** [comment]
@CBVenkataReddy I've assigned you, but please note this is not a `good-first-issue`, so may not be the best way to get started with Cilium.

**Comment by CBVenkataReddy** [comment]
I think we can make use of existing "connectivity-check.yaml" and "connectivity-check-proxy.yaml" tests 
[connectivity-check.txt](https://github.com/cilium/cilium/files/6293021/connectivity-check.txt)

**Comment by pchaigno** [comment]
@CBVenkataReddy We should extend cilium/cilium-cli to run L7 tests. That way we'll have L7 tests running on all major platforms.

**Comment by pchaigno** [comment]
The first two items have been addressed by https://github.com/cilium/cilium-cli/pull/251 and the subsequent use of that code in cilium/cilium.
