### ISSUE TITLE
CI: K8sDatapathConfig Iptables Skip conntrack for pod-to-pod traffic

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#15469]
```
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Missing -j NOTRACK iptables rule
Expected
    <bool>: false
to be true
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:697
...
15:41:04 STEP: WaitforPods(namespace="202103251540k8sdatapathconfigiptablesskipconntrackforpod-to-pod", filter="-l zgroup=testDSClient")
15:41:04 STEP: WaitforPods(namespace="202103251540k8sdatapathconfigiptablesskipconntrackforpod-to-pod", filter="-l zgroup=testDSClient") => <nil>
15:41:04 STEP: WaitforPods(namespace="202103251540k8sdatapathconfigiptablesskipconntrackforpod-to-pod", filter="-l zgroup=testDS")
15:41:04 STEP: WaitforPods(namespace="202103251540k8sdatapathconfigiptablesskipconntrackforpod-to-pod", filter="-l zgroup=testDS") => <nil>
FAIL: Missing -j NOTRACK iptables rule
Expected
    <bool>: false
to be true
=== Test Finished at 2021-03-25T15:41:09Z====
```
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/1167/testReport/junit/Suite-k8s-1/13/K8sDatapathConfig_Iptables_Skip_conntrack_for_pod_to_pod_traffic/

[e54ed197_K8sDatapathConfig_Iptables_Skip_conntrack_for_pod-to-pod_traffic.zip](https://github.com/cilium/cilium/files/6206896/e54ed197_K8sDatapathConfig_Iptables_Skip_conntrack_for_pod-to-pod_traffic.zip)

**Comment by pchaigno** [comment]
cc @jibi

**Comment by pchaigno** [comment]
I suspect the same as in https://github.com/cilium/cilium/issues/15472#issuecomment-807627413 is happening:
> This happens because the PRs have not been rebased. We can see the new test execute in Jenkins but the agent behaves as if it didn't know the new customCalls code. For example, the flag isn't displayed at the beginning of the logs with the other flags, the new map isn't loaded, etc. The test thus fails.

**Comment by pchaigno** [comment]
Closing given above message.
