### ISSUE TITLE
The check of udp header is 0 from cilium_vxlan,  cause gro receive failed on the server side and bad POD to POD performance

### ISSUE THREAD

**Issue by LinFCai** [cilium/cilium#15485]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
`Client: 1.9.90 9e138a965 2021-02-22T07:00:32+00:00 go version go1.15.8 linux/amd64`
- Kernel version (run `uname -a`)
`Linux nw-vm-3.novalocal 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Mon Mar 1 17:16:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, ...)
`{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
- Generate and upload a system zip:
[cilium-sysdump-20210327-044803.zip](https://github.com/cilium/cilium/files/6215145/cilium-sysdump-20210327-044803.zip)

**How to reproduce the issue**
1. create a flush k8s cluster by kubeadm
2. run cilium by `kubectl apply -f quick-install.yaml`
3. Do simple iperf tests between to pods on different nodes
4. We expected to see a performance of about 7 Gbits/s (what the VMs are able to do), but we're seeing speeds in the range of 2 Gbits/s

We found add vxlan in **external** mode without specified ID will not set udp checksum,  that cause udphdr check of packets from cilium_vxlan equal to zero.  Because of udphdr check is zero, gro receive will be failed on node Ethernet of server side and software interrupts (si)  will be quite high.
When we add vxlan with specified ID(but set noudpcsum) between two nodes, bad performance like cilium.

```
[root@nw-vm-3 centos]# top 1
top - 05:00:22 up  1:27,  1 user,  load average: 0.54, 0.16, 0.05
Tasks: 186 total,   1 running, 185 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.7 us,  2.3 sy,  0.0 ni, 96.7 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu1  :  1.0 us,  4.3 sy,  0.0 ni, 94.3 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu2  :  1.0 us,  8.8 sy,  0.0 ni, 89.9 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu3  :  0.7 us,  2.7 sy,  0.0 ni, 96.3 id,  0.0 wa,  0.3 hi,  0.0 si,  0.0 st
%Cpu4  :  0.0 us,  2.3 sy,  0.0 ni,  9.0 id,  0.0 wa,  4.3 hi, 84.3 si,  0.0 st
%Cpu5  :  0.3 us, 12.4 sy,  0.0 ni, 86.9 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu6  :  1.3 us,  9.4 sy,  0.0 ni, 84.3 id,  0.0 wa,  2.7 hi,  2.3 si,  0.0 st
%Cpu7  :  1.3 us,  2.0 sy,  0.0 ni, 96.0 id,  0.0 wa,  0.3 hi,  0.3 si,  0.0 st
```

```
[root@nw-vm-3 centos]# ethtool -k eth0
Features for eth0:
rx-checksumming: on [fixed]
tx-checksumming: off
        tx-checksum-ipv4: off [fixed]
        tx-checksum-ip-generic: off [fixed]
        tx-checksum-ipv6: off [fixed]
        tx-checksum-fcoe-crc: off [fixed]
        tx-checksum-sctp: off [fixed]
scatter-gather: off
        tx-scatter-gather: off [fixed]
        tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: off
        tx-tcp-segmentation: off [fixed]
        tx-tcp-ecn-segmentation: off [fixed]
        tx-tcp-mangleid-segmentation: off [fixed]
        tx-tcp6-segmentation: off [fixed]
generic-segmentation-offload: off [requested on]
generic-receive-offload: on
large-receive-offload: off [fixed]
rx-vlan-offload: off [fixed]
tx-vlan-offload: off [fixed]
ntuple-filters: off [fixed]
receive-hashing: off [fixed]
highdma: on [fixed]
rx-vlan-filter: on [fixed]
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-gre-csum-segmentation: off [fixed]
tx-ipxip4-segmentation: off [fixed]
tx-ipxip6-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-udp_tnl-csum-segmentation: off [fixed]
tx-gso-partial: off [fixed]
tx-sctp-segmentation: off [fixed]
tx-esp-segmentation: off [fixed]
tx-udp-segmentation: off [fixed]
tls-hw-rx-offload: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off [fixed]
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: off [fixed]
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off [fixed]
tls-hw-tx-offload: off [fixed]
rx-gro-hw: off [fixed]
tls-hw-record: off [fixed]

```

**Comment by brb** [comment]
cc @borkmann

**Comment by borkmann** [comment]
@LinFCai hello, this was fixed in: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=89e5c58fc1e2857ccdaae506fb8bc5fed57ee063 . This commit has been backported to all official stable kernel releases back to v4.4 and I also got confirmation from Canonical that they include this into all their releases, too. Could you try with the fix?

**Comment by LinFCai** [comment]
Okay thankyou for your information. The next time, I will try with the fix @borkmann

**Comment by LinFCai** [comment]
When I try with the fix, the problem was solved. Thank you very much. @borkmann

**Comment by borkmann** [comment]
Thanks for testing @LinFCai !
