### ISSUE TITLE
test: Reconsider special case for host identity when remote-node identity is disabled

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15491]
We should check if this special case is still needed with latest Cilium:
https://github.com/cilium/cilium/blob/fce7fe070c14d09adf79395106b056111ad86caa/test/k8sT/Policies.go#L1632-L1640

**Comment by romanspb80** [comment]
Hi Paul!
As I understood the task it is necessary to check the relevance of the policy:

`apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "from-entities-world"
spec:
  endpointSelector:
    matchLabels:
      {}
  ingress:
  - fromEntities:
    - world`

But I didn't find info regarding deprecated entity "world" in [Release notes](https://github.com/cilium/cilium/releases) 
Could you tell  what the latest changes are related to this task?

Thanks

**Comment by pchaigno** [comment]
The `world` entity isn't deprecated. The goal of this issue is to check if the special case I linked to is still needed. That is, is the IP of cilium_host now used for traffic from the host in native routing mode. It should be a simple matter of removing the special case and running the test to check.

**Comment by oneiro-naut** [comment]
Hi, could this issue be assigned to me.

**Comment by pchaigno** [comment]
@oneiro-naut - @romanspb80 is already working on it. I've assigned them to clarify that.
