### ISSUE TITLE
Remove NEEDS_RELAX_VERIFIER

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15498]
In the datapath, we use `` to determine if we need to compile in the insertion of state pruning point, i.e., `relax_verifier()`.
https://github.com/cilium/cilium/blob/a78f75e1eb1dd37e107be01eec6ba7db53ad6f4f/bpf/include/bpf/verifier.h#L13-L17
That macro is defined whenever the kernel supports 1M instructions because we know the verifier stopped needing state pruning points around the same time.
https://github.com/cilium/cilium/blob/0218d373d2f8452720855a4a07b2719fd9826095/daemon/cmd/daemon_main.go#L1359-L1360

We however don't need to go through userspace to generate this macro, since it's already defined in `bpf_features.h` as `HAVE_LARGE_INSN_LIMIT`. We should remove `NEEDS_RELAX_VERIFIER` and `NeedsRelaxVerifier` and use `HAVE_LARGE_INSN_LIMIT` instead.

**Comment by rscampos** [comment]
Hello @pchaigno,
Could you assign it to me, pls?

**Comment by CBVenkataReddy** [comment]
I am planning take-up this issue
@pchaigno, Please assign to me.

**Comment by pchaigno** [comment]
@rscampos I've assigned the issue to you. Don't hesitate to reach out on Slack (e.g., #development or #sig-datapath) if you have any question.

@CBVenkataReddy You can find other `good-first-issues` to work on with this link: https://github.com/cilium/cilium/issues?q=is%3Aopen+label%3Agood-first-issue+no%3Aassignee.
