### ISSUE TITLE
bpf map operation not permitted

### ISSUE THREAD

**Issue by emogua** [cilium/cilium#15510]
pod logs:
level=error msg="Error while opening/creating BPF maps" error="Unable to create map /sys/fs/bpf/tc/globals/cilium_lxc: operation not permitted" subsys=daemon
level=fatal msg="Error while creating daemon" error="Unable to create map /sys/fs/bpf/tc/globals/cilium_lxc: operation not permitted" subsys=daemon

debian 10.9
kubernetes 1.20.5

please help

**Comment by pchaigno** [comment]
Please share a sysdump as per the issue template.
