### ISSUE TITLE
Kafka parser for proxy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1551]

**Comment by ashwinp** [comment]
related issue: https://github.com/cilium/cilium/issues/1606

**Comment by manalibhutiyani** [comment]
Parent Issue #1551 : Kafka parser for proxy
Related issue #1606 : Kafka : Define access log record format 
Related Issue #1633: Kafka: Initial base code for policy enforcement and api

**Comment by tgraf** [comment]
Initial implementation has been merged
