### ISSUE TITLE
Grafana dashboard not working with Cilium 1.9.5

### ISSUE THREAD

**Issue by cyrilcros** [cilium/cilium#15532]
I can't get the v1.9 dashboards from https://grafana.com/orgs/cilium to work for the agent/operator/hubble.

I am using separate charts for prometheus, and grafana, which are fine (prometheus node exporter works for instance). I can see the metrics and cilium agent / cilium operator / hubble all show up as up in Prometheus's status/targets tab, clicking on the URLs shows the metrics are working.

I am adding the dashboard via `gnetId: 13537` (resp 13538 / 13539). Grafana is v.7.5.1, from  https://grafana.github.io/helm-charts  v6.7.0.  I get no data in all panes.

**Comment by aanm** [comment]
Can you provide more information? Also steps to replicate the issue? A sysdump?

**Comment by cyrilcros** [comment]
- I am using serviceMonitors
- Helm configs for Grafana cilium are here: https://gist.github.com/cyrilcros/c12728af504340c20083fb7f181380d3
- Simplest way to replicate would be to be to deploy service monitors and use your own Grafana: go to Dashboard, manage, Import, paste an ID like 13537 into "import via grafana.com".
- the labels for my prometheus targets are container/endpoint/instance/job/namespace/pod/service
- I see similar resolved issues like #14747

[cilium-sysdump-20210331-182301.zip](https://github.com/cilium/cilium/files/6238716/cilium-sysdump-20210331-182301.zip)

**Comment by cyrilcros** [comment]
Something seems wrong.
- v1.9.5  I am not seeing the `targetLabels` https://github.com/cilium/cilium/blob/079bdafc95ade724cefff9e3d52bd2f7deb68ce2/install/kubernetes/cilium/templates/cilium-operator-servicemonitor.yaml#L23
- master I see it
https://github.com/cilium/cilium/blob/231a217ea99dfc6edc1a0d06cde4e945e21962f6/install/kubernetes/cilium/templates/cilium-operator-servicemonitor.yaml#L24

#14747 was merged Jan 30 and https://github.com/cilium/cilium/releases/tag/1.9.5 is from 21 days ago. Did the fix not make it into the release despite being merged before it?

**Comment by pchaigno** [comment]
> #14747 was merged into the master Jan 30 and https://github.com/cilium/cilium/releases/tag/1.9.5 is from 21 days ago. @aanm Did the fix not make it into the release despite being merged before it?

#14747 wasn't backported to v1.9 and isn't planned for backports currently.

**Comment by cyrilcros** [comment]
Then I will just close, thanks!

**Comment by aanm** [comment]
@cyrilcros it will be part of the next 1.9 release. Thanks for reporting it
