### ISSUE TITLE
cilium: encryption (ipsec) unit tests and CI test inclusion

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#15548]
Cilium ginkgo based tests have only a handful of tests for encryption (and it doesn't test EKS, AKS, GKE, at all) to improve the situation we need to add CI test coverage for the various mode.

- [x]  EKS IPSec CI connectivity test
- [x]  AKS IPSec CI connectivity test
- [x]  GKE IPSec CI connectivity test
- [x]  EKS key upgrade
- [x]  GKE key upgrade

Further unit tests should be extended for,
- [ ] encryption enable/disable to ensure state is cleaned up on removal
- [x] encryption key update to ensure old keys are removed
- [x] encryption interface detection and loading.

**Comment by jrajahalme** [comment]
@jrfastab AKS IPSec CI connectivity test has started failing on my PRs: #17022

**Comment by pchaigno** [comment]
Closing as these tests are either already covered or tracked elsewhere.
