### ISSUE TITLE
bpf_host.c mixes declaration and code when HOST_REDIRECT_TO_INGRESS is defined

### ISSUE THREAD

**Issue by chkhalt** [cilium/cilium#15559]
The function `do_netdev` mixes declaration and code when `HOST_REDIRECT_TO_INGRESS` is defined. The used standard (gnu89) prohibits this.

The fix should be trivial. It's just a matter of move the declarations of `int trace = TRACE_FROM_HOST;` and `bool from_proxy;` to the beginning of the scope in https://github.com/cilium/cilium/blob/198fe64d79b53c983ba74f09f5c7a1c34408666d/bpf/bpf_host.c#L800

As the issue #15095 also happens when `HOST_REDIRECT_TO_INGRESS` is defined, would be better not to define this macro on the Makefile. To test the compilation problem (and the fix) we can run the following command inside `bpf` folder:

```
clang -DHOST_REDIRECT_TO_INGRESS -I./include -I. -D__NR_CPUS__=2 -O2 -g \
-target bpf -std=gnu89 -nostdinc -emit-llvm -Wall -Wextra -Werror -Wshadow \
-Wno-address-of-packed-member -Wno-unknown-warning-option \
-Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -c bpf_host.c
```

**Comment by johngv2** [comment]
@pchaigno, I can deliver both issues on separated PR. Please, could you assign it to me.
