### ISSUE TITLE
Connectivity issues on 1.9.5 with IPSec

### ISSUE THREAD

**Issue by dbaumgarten** [cilium/cilium#15568]
## Bug report

Hi,
I have hit a problem with cilium 1.9.5 and after hours of debugging I am completely out of ideas and must assume that it's a bug in cilium.

I installed cilium 1.9.5 into a fresh Kubernetes 1.21-rc.0 cluster (with slightly modified quickstart-config, see attachment). The cilium-pods are Ready, but the cilium connectivity-check does not work. Running "cilium-health status" shows that all nodes can talk to each other, but most health-endpoints are unreachable. (Note: Most, not all).
Here is an example from one of the nodes:
```
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
Probe time:   2021-04-06T10:28:17Z
Nodes:
  twozero-test-kube-master-1 (localhost):
    Host connectivity to 192.168.3.6:
      ICMP to stack:   OK, RTT=4.433831ms
      HTTP to agent:   OK, RTT=435.397µs
    Endpoint connectivity to 10.192.4.30:
      ICMP to stack:   OK, RTT=4.439645ms
      HTTP to agent:   OK, RTT=453.086µs
  twozero-test-kube-master-0:
    Host connectivity to 192.168.3.5:
      ICMP to stack:   OK, RTT=4.490365ms
      HTTP to agent:   OK, RTT=1.288817ms
    Endpoint connectivity to 10.192.0.206:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.192.0.206:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  twozero-test-kube-master-2:
    Host connectivity to 192.168.3.3:
      ICMP to stack:   OK, RTT=4.484343ms
      HTTP to agent:   OK, RTT=1.418706ms
    Endpoint connectivity to 10.192.3.141:
      ICMP to stack:   OK, RTT=4.38019ms
      HTTP to agent:   OK, RTT=2.280835ms
  twozero-test-kube-minion-0:
    Host connectivity to 192.168.3.8:
      ICMP to stack:   OK, RTT=4.483895ms
      HTTP to agent:   OK, RTT=1.451143ms
    Endpoint connectivity to 10.192.1.136:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.192.1.136:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  twozero-test-kube-minion-1:
    Host connectivity to 192.168.3.7:
      ICMP to stack:   OK, RTT=7.55434ms
      HTTP to agent:   OK, RTT=652.561µs
    Endpoint connectivity to 10.192.2.102:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.192.2.102:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
master-1 can reach the health-endpoint of master-2 and master-2 can reach the endpoint of master-1. Also minion-0 and minion-1 can reach each others endpoints. All other routes dont work.
All nodes are complete fresh, automated installs and should be as equal as it gets. Also, which node can reach which other nodes seems to be random on every new cluster-deployment.

What is really interesting: If I use the exact same cilium-config, but use cilium 1.8.4, everything is working fine. AND if I then update from 1.8.4 to 1.9.5 everything keeps running fine (even for newly created pods). Only when deploying 1.9.5 directly things dont work.

**General Information**

- Cilium version (run `cilium version`): 1.9.5
- Kernel version (run `uname -a`): 5.4.0-70-generic  (ubuntu focal)
- Orchestration system version in use (e.g. `kubectl version`, ...): Kubernetes v1.21-rc.0
- Link to relevant artifacts (policies, deployments scripts, ...): 
[cilium.txt](https://github.com/cilium/cilium/files/6263892/cilium.txt)

- Generate and upload a system zip:  
[cilium-sysdump.zip](https://github.com/cilium/cilium/files/6263937/cilium-sysdump.zip)

**How to reproduce the issue**

1. Install cilium 1.9.5 (without updating from 1.8.4)
2. Check "cilium-health status"

**Comment by pchaigno** [comment]
I see IPSec is enabled. Do you also hit this issue if you disable IPSec?

**Comment by dbaumgarten** [comment]
Hi,
I just tried it, and when disabling IPsec everything works just fine.
Unfortunately I am required to use encryption on the overlay network for productive clusters.
Is there any way to have a working 1.9.5 installation with ipsec enabled?

**Comment by pchaigno** [comment]
v1.9.5 has an IPSec regression which we are currently fixing. The fix should land in the next patch release.

**Comment by dbaumgarten** [comment]
Ok, then I'll stay at 1.8.4 for now and patiently wait for the patch.
Thanks for your help.

**Comment by Jasper-Ben** [comment]
> v1.9.5 has an IPSec regression which we are currently fixing. The fix should land in the next patch release.

Hi @pchaigno, what's the status on this issue? Has the ipsec regression been fixed yet? Thanks!

**Comment by dbaumgarten** [comment]
Yes, v1.9.6 is working fine 👍

**Comment by Jasper-Ben** [comment]
> Yes, v1.9.6 is working fine +1

hm okay. we have a similar issue and I thought this might be the same issue: https://github.com/cilium/cilium/issues/16279#issuecomment-846447635
So IPsec works for you without any issue, even after node reboot?

**Comment by dbaumgarten** [comment]
I don't think I have tried to reboot a node.
Will test this tomorrow

**Comment by Jasper-Ben** [comment]
Thanks!

**Comment by dbaumgarten** [comment]
@Jasper-Ben You were right! Rebooting a node breaks cilium on that node (until the pod on that node is restarted).
I rarely reboot nodes, so I didn't notice that, but it's good to know there is an issue. Thanks.

**Comment by johannwagner** [comment]
We also created an issue for this problem:

https://github.com/cilium/cilium/issues/16279
