### ISSUE TITLE
Compatibility issue between Cilium>=1.8.3  and Kubernetes <= 1.18.5.

### ISSUE THREAD

**Issue by lbernail** [cilium/cilium#15583]
We identified a compatibility issue between client-go 0.18.6+ and apiservers <= 1.18.5.

When a client disconnects from an apiserver and reconnects to another one with an older RV the Informer will never recover because clients 0.18.6+ expect a more complete error message from apiservers to understand TooLargeResourceVersion errors. So the Informer keeps trying to relist with the RV it knows and getting 504 from the apiserver (while it should relist with RV=“” when this happens). Of course for resources that change a lot, the Informer recovers once the RV of the apiserver it is connected to gets updated to a recent one but this can still create transient issues.

This manifest as errors on apiservers and (we think but are not completely sure) as errors retrieving pod labels when the pod informer is temporarily stuck this way (leading to pods with "init" identity).

This means that Cilium 1.8.3+ can have issues with Kubernetes <=1.18.5 (this is how we noticed it)

We built a 1.8.3+ version of Cilium with an older version of client-go (0.18.5) and verified that 504 errors disappear. We should know in a few days if the "init" identity issue goes away completely too.

Upstream PR introducing the new behavior: https://github.com/kubernetes/kubernetes/pull/92537
The apiserver now sends:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
  },
  "status": "Failure",
  "message": "Timeout: Too large resource version: 6070938882, current: 2843990914",
  "reason": "Timeout",
  "details": {
    "causes": [
      {
        "reason": "ResourceVersionTooLarge",
        "message": "Too large resource version"
      }
    ],
    "retryAfterSeconds": 1
  },
  "code": 504
}
```
While before it was sending:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
  },
  "status": "Failure",
  "message": "Timeout: Too large resource version: 6070938882, current: 6063474977",
  "reason": "Timeout",
  "details": {
    "retryAfterSeconds": 1
  },
  "code": 504
}
```
But in the same PR the client code is modified to expect
```
details.causes.reason== ResourceVersionTooLarge
```
Since it is not getting it, it does not behave as expected (relisting with RV="")

I discussed the problem with @wojtek-t and he confirmed (and explained the detail of) the problem. The change was not backported to older apiservers as the official support policy is client-go version <= apiserver version.

**General Information**

- Cilium version: `1.8.6`
- Kernel version: `5.4`
- Orchestration system version in use: `kubernetes 1.14`

cc @aanm as we discussed this on slack

**Comment by lbernail** [comment]
Ok the issue actually came back with client-go 0.18.5 so we dived again in the commit history. It turns out:
- https://github.com/kubernetes/kubernetes/pull/83520 introduced a bug that was reverted in 1.17.1 but kept in master and fixed for real in 1.18.6 _but_ the fix introduce an incompatibility with client-go <=0.18.5 triggering the same problem
- impacted versions are client-go 0.17.0 (0.17.1+ are fine) and 0.18.[0-5]
- client-go 0.18.6 is fine but does not work with apiservers <= 1.18.6

So I think we can say:
- Cilium 1.8.3+ only works with Kubernetes >= 1.18.6
- Cilium 1.8.0-2 uses a client-go version that has a known bug in informers (regardless of apiserver version)

**Comment by lbernail** [comment]
We're validating this with a custom Cilium v1.8.6 build using a client-go version no impacted by the bug or its fix (0.17.17)

**Comment by aanm** [comment]
And is Cilium 1.7.x affected at all?

**Comment by lbernail** [comment]
> And is Cilium 1.7.x affected at all?

It should not be as it seems to be using client-go versions between 0.17.3 and 0.17.17 (not 100% sure as it is referencing a specific commit but other references to kubernetes packages use these versions)

**Comment by lbernail** [comment]
👋 We can confirm that since we deployed 1.8.7 with client-go 0.17.17 we don't get any 504 any more on our 1.14 clusters
We are going to deploy more widely to verify this also addresses the problem where pods get the Init identity because the cilium-agent can't find the local pod in its informer

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
