### ISSUE TITLE
Switch to EndpointSlice v1beta1 -> v1

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#15594]
New builds of Cilium latest are reporting this log message:

```
discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/110/testReport/junit/Suite-k8s-1/21/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing/

I guess that we need to attempt to use v1, then if the cluster doesn't support it, attempt v1beta1, and if that is not supported, fall back to Endpoints.

**Comment by aanm** [comment]
@joestringer this should be fixed by #15524. Is that a recent jenkins run?

**Comment by joestringer** [comment]
Yes, here's the git checkout step of the job:
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/110/execution/node/7/log/

```
Cloning the remote Git repository
Using shallow clone
Cloning repository https://github.com/cilium/cilium
 > git init /home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9 # timeout=10
Fetching upstream changes from https://github.com/cilium/cilium
 > git --version # timeout=10
using GIT_ASKPASS to set credentials Used for GH PR Commit Status
 > git fetch --tags --progress https://github.com/cilium/cilium +refs/heads/*:refs/remotes/origin/* --depth=1 # timeout=20
 > git config remote.origin.url https://github.com/cilium/cilium # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/cilium/cilium # timeout=10
Fetching upstream changes from https://github.com/cilium/cilium
using GIT_ASKPASS to set credentials Used for GH PR Commit Status
 > git fetch --tags --progress https://github.com/cilium/cilium +refs/pull/*:refs/remotes/origin/pr/* --depth=1 # timeout=20
Checking out Revision c17f6ed5933c4cae69456b25748f85b43bf45cfd (refs/remotes/origin/pr/15072/merge)
 > git rev-parse refs/remotes/origin/pr/15072/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/15072/merge^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c17f6ed5933c4cae69456b25748f85b43bf45cfd
Commit message: "Merge 65f1aed17b604b2e5c6543e7e551449fd1972334 into 9be51834146c482582d7db10139927479e2a858f"
```

Commit 9be5183414 appears to include 5ee4c6f (https://github.com/cilium/cilium/pull/15524).

**Comment by joestringer** [comment]
Do we still use this for generating images or is jenkins pulling from the cilium-ci build now too? The PR might not have been rebased.

**Comment by joestringer** [comment]
Linked Jenkins job is from PR https://github.com/cilium/cilium/pull/15072.

**Comment by aanm** [comment]
@joestringer the source code to build images is **not** rebased

**Comment by joestringer** [comment]
I'll close this out then, should be already resolved.

**Comment by joestringer** [comment]
Seen again in #15630, based against upstream c603c5e378b2ecdfbc0367d85f18fe7bf1ff4fe2 (yesterday).
