### ISSUE TITLE
docs: Update kube-router guide to point to newer release

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#15613]
The Cilium kube-router integration guide points to kube-router v0.4.0:
https://docs.cilium.io/en/v1.9/gettingstarted/kube-router/

There have been several releases since v0.4.0 upstream.

Upstream kube-router documentation points towards the YAMLs from the master branch:
https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#running-as-daemonset

We should probably just use this link instead so we don't have to keep updating the Cilium docs as kube-router introduces new versions:
https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/generic-kuberouter-only-advertise-routes.yaml

Tasks:
* [ ] Prepare a PR to point to the newer kube-router YAML
* [ ] Test that the guide still works with the new YAML

**Comment by weirdwiz** [comment]
Hi, I'd like to work on this issue.

**Comment by pchaigno** [comment]
@weirdwiz Hi :wave: I've assigned you. Don't hesitate to reach out on Slack (e.g., #sig-docs or #development) if you have any question.
