### ISSUE TITLE
unable to update pod ... resource name may not be empty, retrying...

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1561]
This happens for the `kube-dns` pod which exists before cilium is started

```
time="2017-09-21T00:05:09Z" level=warning msg="k8s: unable to update pod kube-system:kube-dns-2425271678-mk9x9 / endpoint 33115 with \"cilium.io/identity\" annotation: resource name may not be empty, retrying..."
```

**Comment by nebril** [comment]
@tgraf how to replicate this one? cilium logs don't have anything like that on fresh minikube cluster install on versions 1.6, 1.7 and 1.8.

**Comment by tgraf** [comment]
> how to replicate this one? cilium logs don't have anything like that on fresh minikube cluster install on versions 1.6, 1.7 and 1.8.

We saw this on a majority of runs but I'm not seeing it either anymore. I think we can close this.
