### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer Connectivity to endpoint via LB

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15620]
```
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Cannot retrieve LB IP for test-lb
Expected
    <*errors.errorString | 0xc0020196f0>: {
        s: "could not get service LoadBalancer IP addr: 30s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/k8sT/Services.go:2573
```
We recently switched to the integrated MetalLB in the test. /cc @christarazi 

Maybe 30sec is not enough?

[2e1ea6ff_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB.zip](https://github.com/cilium/cilium/files/6285883/2e1ea6ff_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_LoadBalancer_Connectivity_to_endpoint_via_LB.zip)

**Comment by christarazi** [comment]
I'm not so sure this is a flake. Inspecting the sysdump, I'm not seeing the `bgp-announce-lb-ip` flag in the Cilium logs output which would indicate that Cilium is aware of the option. Looking at https://github.com/cilium/cilium/pull/15260, it is not rebased on top of latest master which includes the BGP code. I imagine the same has happened with https://github.com/cilium/cilium/pull/15590, but it's been merged and its corresponding branch deleted, so I can't confirm.

**Comment by pchaigno** [comment]
Did not happen recently according to https://datastudio.google.com/s/gmSGs21IOLA, so likely another case of https://github.com/cilium/cilium/issues/15474. Closing.
