### ISSUE TITLE
Add more user-friendly log messages on map creation

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#15629]
```
Apr 09 18:21:00 k8s2 cilium-agent[18719]: level=error msg="Error while opening/creating BPF maps" error="unable to create map: use pinned map cilium_metrics: expected flags 1, got 0" subsys=daemon
Apr 09 18:21:00 k8s2 cilium-agent[18719]: level=fatal msg="Error while creating daemon" error="unable to create map: use pinned map cilium_metrics: expected flags 1, got 0" subsys=daemon
```

From Joe:
There is a cilium_metrics map already with flags configured with the value 0, looks like on startup the daemon attempted to reuse the map but since the flags value was different from what it expected the flags to be (1), it took exception to this and failed out.
Fataling out here seems like a bit extreme, normally I would expect such maps just to be recreated with the new map flags and log a big angry warning

**Comment by christarazi** [comment]
If we recreate maps, then we lose the contents. In this case, it's the metrics map so not a big deal if it's gone, but other maps, this might be a more sensitive situation. So it might make sense to make the metrics map not fatal on this error, but others probably keep the fatal.

**Comment by pchaigno** [comment]
When does this happen? On upgrade from v1.9 to master? Why didn't the K8sUpdates test catch it?

**Comment by aanm** [comment]
IIRC was when switching the `preallocate-bpf-maps` flag from `true` to `false` or vice-versa.

**Comment by jibi** [comment]
> When does this happen? On upgrade from v1.9 to master? Why didn't the K8sUpdates test catch it?

There is small window of commits (after the switch to `cilium/ebpf` for the metrics map https://github.com/cilium/cilium/pull/14582 and before this fix https://github.com/cilium/cilium/pull/14853) where the metrics map would be created without the `BPF_F_NO_PREALLOC` flag, so I think that could explain why this happened

**Comment by pchaigno** [comment]
> IIRC was when switching the `preallocate-bpf-maps` flag from `true` to `false` or vice-versa.

If that's all there is to it, maybe we can just delete the map when it happens? I doubt it's worth a full map migration.

**Comment by jibi** [comment]
> I doubt it's worth a full map migration.

Not sure what you are referring to :thinking:

**Comment by pchaigno** [comment]
I thought I saw that discussed as a potential solution last time we discussed it on Slack, but can't find it again :disappointed:

**Comment by jibi** [comment]
Ah, I think I know what you are referring to now :+1: (different issue :slightly_smiling_face:)
