### ISSUE TITLE
Propose an automatic policy discovery module.

### ISSUE THREAD

**Issue by seungsoo-lee** [cilium/cilium#15638]
## Proposal / RFE

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Basic operation: generate a network policy based on the network traffic information from Cilium Hubble.

Inputs: 
- network logs (traffic) from Cilium Hubble
- pod(including labels), endpoint, and service information from K8s Client APIs

Can be discovered policy types: 
- to/fromEndpoints (L3/L4)
- to/fromEntities
- toCIDR
- toServices (external service)
- toFQDN (DNS)
- toHTTPs (L7)

Advanced discovery features:
- Label aggregation: 
Let's assume that there are three pods(A, B, and C), and each pod has their own labels: Pod A(group=alice, app=user), Pod B(group=alice, app=book), Pod C(group=bob, app=web). We have two connection info from Cilium Hubble (Pod A -> Pod B, Pod A -> Pod C). From the network logs, the discovery module does not discover the two distinct network policies; [Pod A -> Pod C] and [Pod A -> Pod C]. 
Instead, since Pod A and Pod B have the intersection of the labels, which is 'group=alice', the module discovers and generates a network policy that has the selector with matchLabels 'group=alice'. Finally, we can get one network policy that covers two distinct network flows [group=alice -> Pod C].

- toPorts(L4) merging:
Similar to the previous case, we can merge the multiple ToPorts rules per each same destination. Let's assume that there are the source and destination pods and three different traffic info (Pod A -> Pod C/TCP/443, Pod A -> Pod C/TCP/8080, and Pod A -> Pod C/TCP/80). In this case, the module does not generate three different network policies per each ToPorts rule.
More efficiently, the module discovers one network policy and has one matchLabel rule and three ToPorts rules; port numbers are 443, 8080, and 80. From this merge, it can be enabled to produce a minimum network policy set covering maximum network flows.

- Outdated policy management:
Since the module can do the discovery job at time intervals, there could be some overlappings. For example, let's assume we discovered policy A (toCIDR) and policy B (toFQDN) at the time t1 (before) and t2 (after) respectively.
However, policy B has domain names for the toCIDRs. In this case, the module updates policy B by overlapping policy A, and then it marks policy A as outdated and puts the relevant latest policy name. Thus, users can retrieve only the latest network policies from the database.

**Comment by pchaigno** [comment]
The basics are already support via the Flow uploads feature at https://editor.cilium.io:

![image](https://user-images.githubusercontent.com/1764210/122769134-928b3c00-d2a4-11eb-866c-355ed5ce9382.png)
![image](https://user-images.githubusercontent.com/1764210/122769168-9b7c0d80-d2a4-11eb-978e-b401ac778ac3.png)
