### ISSUE TITLE
cilium ip address allocation 

### ISSUE THREAD

**Issue by DavidLeeUX** [cilium/cilium#15664]
If I have only one kubenetes cluster, but the ip address segment is allocated according to the computer room, each room has a /24 segment, then how to configure the cidr according to the computer room when using cilium, and whether it is possible to assign cidr according to the label

**Comment by ti-mo** [comment]
Hi @DavidLeeUX, thanks for creating an issue. I'm going to close this as this is a bug/development tracker, not a support forum.

Please reach out to the community through our public Slack (https://github.com/cilium/cilium#slack) for these kinds of questions.
