### ISSUE TITLE
Cilium North-South Load balancing does uneven connection across backend pods

### ISSUE THREAD

**Issue by karthikt-yahoo** [cilium/cilium#15683]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
cilium version
Client: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
Daemon: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
```
```
- Kernel version (run `uname -a`) - 4.18.0-240.15.1.el8_3.x86_64 ; Red Hat Enterprise Linux release 8.3
- Orchestration system version in use (e.g. `kubectl version`, ...) v1.17.14
```

**How to reproduce the issue**

1. Deploy nginx with two or three pods
2. Create k8s service with external ip (i choose External ip with ip of a dedicated host(with XDP enabled), and all the traffic for External IP goes via the dedicated host)
3. Generate load to created service external ip(In my setup, external ip is part of the node where cilium agent runs)
     I have used httperf(https://github.com/httperf/httperf) for traffic generation. it creates individual connection and make one request per connection and closes it, connections are not reused. I am logging the client connection’s remote port for each request, none of the requests has the same remote port at same time which proves each connection had just one request.
   httperf --server <external-ip> --port 80 --num-conns 40000 --rate 300 --timeout 1 

Connection distribution between Two pods is 74.9% & 25.1%
Connection distribution between Three pods is 66.7% & 16.5% & 16.7% 
Connection distribution between Five pods is 59.9% , 9.9% , 10.1% , 10.1%, 10.1%
Connection distribution between Fifty pods is 50% on one pod and 1% each across other pods.

All these test returns with 100% 200 response and no errors.   

cilium status --verbose 
```
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.17 (v1.17.14) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens9 (Direct Routing)]
Cilium:                 Ok       OK
NodeMonitor:            Listening for events on 96 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 2/255 allocated from 10.0.1.0/24, 
Allocated addresses:
  10.0.1.32 (health)
  10.0.1.6 (router)
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           Disabled
Clock Source for BPF:   ktime
Controller Status:      17/18 healthy
  Name                                  Last success   Last error   Count   Message
  cilium-health-ep                      2m3s ago       31s ago      1       Get "http://10.0.1.32:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)   
  dns-garbage-collector-job             13s ago        never        0       no error                                                                                                        
  endpoint-1253-regeneration-recovery   never          never        0       no error                                                                                                        
  endpoint-264-regeneration-recovery    never          never        0       no error                                                                                                        
  k8s-heartbeat                         13s ago        never        0       no error                                                                                                        
  mark-k8s-node-as-available            1h14m6s ago    never        0       no error                                                                                                        
  metricsmap-bpf-prom-sync              3s ago         never        0       no error                                                                                                        
  neighbor-table-refresh                6s ago         never        0       no error                                                                                                        
  resolve-identity-264                  31s ago        never        0       no error                                                                                                        
  restoring-ep-identity (1253)          1h14m6s ago    never        0       no error                                                                                                        
  sync-endpoints-and-host-ips           7s ago         never        0       no error                                                                                                        
  sync-lb-maps-with-k8s-services        1h14m6s ago    never        0       no error                                                                                                        
  sync-policymap-1253                   5s ago         never        0       no error                                                                                                        
  sync-policymap-264                    31s ago        never        0       no error                                                                                                        
  sync-to-k8s-ciliumendpoint (1253)     6s ago         never        0       no error                                                                                                        
  sync-to-k8s-ciliumendpoint (264)      1s ago         never        0       no error                                                                                                        
  template-dir-watcher                  never          never        0       no error                                                                                                        
  update-k8s-node-annotations           1h14m12s ago   never        0       no error                                                                                                        
Proxy Status:   OK, ip 10.0.1.6, 0 redirects active on ports 10000-20000
Hubble:         Ok   Current/Max Flows: 1156/4096 (28.22%), Flows/s: 0.26   Metrics: Disabled
KubeProxyReplacement Details:
  Status:              Strict
  Protocols:           TCP, UDP
  Devices:             ens9 (Direct Routing)
  Mode:                DSR
  Backend Selection:   Maglev (Table Size: 509)
  Session Affinity:    Enabled
  XDP Acceleration:    Native
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   1772123
  TCP connection tracking       3544246
  Endpoint policy               65535
  Events                        96
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           3544246
  Neighbor table                3544246
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        96
  Sockmap                       65535
  Sock reverse NAT              1772123
  Tunnel                        65536
```

**Comment by oblazek** [comment]
@karthikt-yahoo what happens when you use another host as the traffic generator (httperf)?

**Comment by karthikt-yahoo** [comment]
> @karthikt-yahoo what happens when you use another host (2 in total) as the traffic generator (httperf)?

I tested by generating traffic with two httperf clients on two individual hosts to External-IP service with two backend pods. request/connection distribution to backed pods is 74% and 26%

**Comment by brb** [comment]
@karthikt-yahoo Check source ports distribution. Maybe add logging of source ports to `httperf` if it doesn't do that.

**Comment by karthikt-yahoo** [comment]
> @karthikt-yahoo Check source ports distribution. Maybe add logging of source ports to `httperf` if it doesn't do that.

I am logging the source port(client port on the TCP) on my nginx server for each request, none of the requests has the same source port at same time which proves connection source port is not reused.

**Comment by karthikt-yahoo** [comment]
@brb do you suspect it could be because of the kernel version 4.18.0-240.15.1.el8_3.x86_64 ; Red Hat Enterprise Linux release 8.3. thanks

**Comment by sureshvis** [comment]
External IP - 3.3.3.3  
pod 1 --> 1.1.1.1 
pod 2 --> 2.2.2.2 

siege -b -c 1  http://3.3.3.3 -t 1s -v

{	"transactions":			         471,
	"availability":			      100.00,
	"elapsed_time":			        0.27,
	"data_transferred":		        0.27,
	"response_time":		        0.00,
	"transaction_rate":		     1744.44,
	"throughput":			        1.02,
	"concurrency":			        0.93,
	"successful_transactions":	         471,
	"failed_transactions":		           0,
	"longest_transaction":		        0.01,
	"shortest_transaction":		        0.00
}

connection table 

root@lb1:/home/cilium# cilium bpf ct list global | grep -i 3.3.3.3 |  wc -l

472 --> total connection, clear sport are changing 

root@lb1:/home/cilium# cilium bpf ct list global | grep -i 1.1.1.1  |  wc -l

122 --> connection to pod 1 from LB 

root@lb1:/home/cilium# cilium bpf ct list global | grep -i 2.2.2.2  |  wc -l

350 --> connection to pod 2 from LB

**Comment by borkmann** [comment]
`Connection distribution between Fifty pods is 50% on one pod and 1% each across other pods.` btw, for more than ~5 backend pods, you might want to consider increasing the Maglev table size to something larger (rough rule of thumb: next prime near ~backend size * 100, see https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/#maglev-consistent-hashing-beta)
```
  Mode:                DSR
  Backend Selection:   Maglev (Table Size: 509)
```
Do you have a dump of `cilium bpf lb maglev list` for the 2/3/5 backend pod case?

**Comment by sureshvis** [comment]
increased to 16381 with 2 backend, still the same behavior  @borkmann

**Comment by sureshvis** [comment]
@borkmann with random, its working fine and observed 50% to pod 1 and 50% to pod2 with 2 backend test. 

This observation is specific to Maglev

**Comment by borkmann** [comment]
> increased to 16381 with 2 backend, still the same behavior with Maglev @borkmann

Could you dump `cilium bpf lb maglev list`?

**Comment by karthikt-yahoo** [comment]
> > increased to 16381 with 2 backend, still the same behavior with Maglev @borkmann
> 
> Could you dump `cilium bpf lb maglev list`?

Dumped the External service info that we use for testing, please let us know if you need further more information.
https://git.vzbuilders.com/gist/karthikt/83ebada16bb079d439511b4af54eff41

**Comment by borkmann** [comment]
@karthikt-yahoo @sureshvis the observed issue should be fixed with https://github.com/cilium/cilium/pull/15808 . Thanks a lot for reporting!
