### ISSUE TITLE
`cilium ip list` returns a misleading source

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#15698]
Doing some code auditing it looks like we are setting k8s source when dumping ipcache entries [1]. This can be a little bit misleading since `k8sMeta` can also be populated in by CEPs in [2]

[1] https://github.com/cilium/cilium/blob/4c30f50020af527b537d8cb027d7649b2c9c9e3c/daemon/cmd/ipcache.go#L84-L94

[2] https://github.com/cilium/cilium/blob/969c2f78f545f29925ab1fab43ca508e0eb34efb/pkg/k8s/watchers/cilium_endpoint.go#L161-L162

**Comment by gandro** [comment]
FWIW: There is no `cilium ipcache list` command ;) Only `cilium bpf ipcache list`. This API was used for Hubble standalone (which never read the field in the first place). But yes, we should fix this regardless.

**Comment by pchaigno** [comment]
> There is no `cilium ipcache list` command ;) Only `cilium bpf ipcache list` (which does not use this API).

We actually noticed this in `cilium ip list -n -o json`.
