### ISSUE TITLE
cilium-node-init does not restart pods on EKS with CNI chaining

### ISSUE THREAD

**Issue by rustrial** [cilium/cilium#15692]
## Bug report

The [cilium-node-init DaemonSet](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-nodeinit-daemonset.yaml#L239) uses an introspection endpoint of the AWS CNI plugin which no longer exists to list the running Pods.  The endpoint `localhost:61679/v1/pods` [has been removed in AWS CNI version 1.7.0](https://github.com/aws/amazon-vpc-cni-k8s/commit/e38a4d8a8a9358f9b1e24f465a8d42a95a837533#diff-6b48ec865dc66afbb863739b126b6b9b750bd43a0ccb0a7460d84d86b79320bc) and therefore listing the running Pods no longer works. 

## Additional Information

Container IDs could instead be obtained from the `/v1/enis` endpoint, which still exists. However, I am not 100% sure whether that endpoint returns the correct set of Pods (all Pods that needs restart). 

`curl "localhost:61679/v1/enis" | jq '.ENIs[].IPv4Addresses[].IPAMKey.containerID' -r | grep -v '^$'`

Looking at the shell script code in https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-nodeinit-daemonset.yaml, it also looks like it is not yet well prepared for all combinations of cloud providers and container runtimes (docker, containerd, ...). E.g. on EKS one could have both runtimes in the same cluster depending on the AMI in use for specific node groups.

**General Information**

- Cilium version (run `1.9.5`)
- AWS CNI version `1.7.10` (but all `1.7.*` version are affected starting with `1.7.0-rc1`)
- Kernel version (run `Linux ip-10-176-4-232.eu-central-1.compute.internal 5.4.105-48.177.amzn2.x86_64 #1 SMP Tue Mar 16 04:56:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`)
- Orchestration system version in use (e.g. Kubernetes `v1.19.6-eks-49a6c0`)

## Potentially related issues:

- https://github.com/cilium/cilium/issues/15366
- https://github.com/cilium/cilium/issues/15330

**Comment by pchaigno** [comment]
@rustrial Is this still an issue?
