### ISSUE TITLE
daemon: Make --devices to accept names with wildcards

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15693]
Currently, the cilium-agent's flag `--devices` allows a user to specify devices to which `bpf_host` program should be attached (the latter is responsible for NodePort BPF, host-fw, etc).

This works fine in a homogeneous cluster in which all to-be attached devices are named the same. The problem arises when this is not the case, as cilium-agent panics if it cannot find any user specified device.

To fix this, we could add iptables-style matching:
> If the interface name ends in a "+", then any interface which begins with this name will match.

So for example, if user specifies `--devices=eth+,en+`, then the program should be attached to any matching device (`eth0`, `eth1`, `eth2`, `en0`, etc).

If a given interface name doesn't match any device, the cilium-agent should not panic.

**Comment by joamaki** [comment]
Alternatively I suppose the wildcard syntax could be in the style of shell globs (e.g. implemented with https://golang.org/pkg/path/filepath/#Match) or as regexp. Any idea how much flexibility is needed? Do we know of a specific case where the current `--devices` flag fell short?
