### ISSUE TITLE
KVstore-free For ClusterMesh

### ISSUE THREAD

**Issue by sstoner** [cilium/cilium#15703]
With cilium 1.6 release, cilium entirely without a KVstore in the context of Kubernetes. 

But in the clustermesh situation, we still need to use etcd as kvstore in cilium. I just want to know if KVstore-free for ‘cilium clustermesh’  is possible?

## Proposal / RFE

**Is your feature request related to a problem?**

KVstore-free 100% in the context of kubernetes 

**Describe the solution you'd like**

Replace `store.JoinSharedStore` into kubernetes list-watch api as local cache

**Comment by aanm** [comment]
Cilium 1.10 will have this feature. The documentation is already available here. https://docs.cilium.io/en/latest/gettingstarted/clustermesh/clustermesh/

**Comment by sstoner** [comment]
> Cilium 1.10 will have this feature. The documentation is already available here. https://docs.cilium.io/en/latest/gettingstarted/clustermesh/clustermesh/

From this doc It obviously simplify the process to deploy clustermesh by clustermesh-apiserver, but it did't mention kvstore-free is possible. Because I still see we sign the certs for different clusters in the doc's logs, I think we can just generate a possible kubeconfig for different remote clusters that is more simple for users.

**Comment by sstoner** [comment]
> > Cilium 1.10 will have this feature. The documentation is already available here. https://docs.cilium.io/en/latest/gettingstarted/clustermesh/clustermesh/
> 
> From this doc It obviously simplify the process to deploy clustermesh by clustermesh-apiserver, but it did't mention kvstore-free is possible. Because I still see we sign the certs for different clusters in the doc's logs, I think we can just generate a possible kubeconfig for different remote clusters that is more simple for users.

Moreover why don't I see this feature `kvstore-free for clustermesh` in the v1.10 milestones ?  
Maybe we can implement it together with community if it don't have strange problems to replace `store.JoinSharedStore`
