### ISSUE TITLE
CI: K8sPolicyTest: Zero exit code despite curl timeout

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15724]
```
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
HTTP ingress connectivity to "10.0.0.117" from k8s3 host
Expected command: kubectl exec -n kube-system log-gatherer-jlcvv -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 10.0.0.117 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'"
To have failed, but it was successful:
Exitcode: 0 
Stdout:
 	 time-> DNS: '0.000019()', Connect: '0.000000',Transfer '0.000000', total '5.001828'
Stderr:
 	 

/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/k8sT/Policies.go:1660
```
[33a8f534_K8sPolicyTest_Multi-node_policy_test_validates_fromEntities_policies_with_remote-node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy.zip](https://github.com/cilium/cilium/files/6320719/33a8f534_K8sPolicyTest_Multi-node_policy_test_validates_fromEntities_policies_with_remote-node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy.zip)

Looks like it might be yet another instance of https://github.com/cilium/cilium/issues/12511, as the request was sent from k8s3 (outsideNode) to any of k8s{1,2}.

**Comment by pchaigno** [comment]
> Looks like it might be yet another instance of #12511, as the request was sent from k8s3 (outsideNode) to any of k8s{1,2}.

Seems different to me: the request succeeded when it was expected to fail. #12511 is the other way around.

Given it's a test of the host policies, could be related to https://github.com/cilium/cilium/issues/15575.

**Comment by pchaigno** [comment]
This is actually a bit weird:
```
Expected command: kubectl exec -n kube-system log-gatherer-jlcvv -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 10.0.0.117 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'"
To have failed, but it was successful:
Exitcode: 0 
Stdout:
 	 time-> DNS: '0.000019()', Connect: '0.000000',Transfer '0.000000', total '5.001828'
```
So `curl` clearly failed because the total time for the `curl` command is just a bit more than the timeout (5s). Despite that, it returns a zero exit code and is therefore detected as "successful", an unexpected result.

**Comment by pchaigno** [comment]
Also happened for test `K8sPolicyTest Namespaces policies Tests the same Policy in different namespaces` (cf. https://github.com/cilium/cilium/issues/15758).

**Comment by pchaigno** [comment]
Also happened in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/1435/testReport/junit/Suite-k8s-1/21/K8sPolicyTest_Basic_Test_checks_policies_with_named_ports/.
```
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Unexpected connection from "app3-5d69599cdd-hx7nh" to 'http://10.111.146.180/private'
Expected command: kubectl exec -n 202109210850k8spolicytestbasictestchecksallkindofkubernetespoli app3-5d69599cdd-hx7nh -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://10.111.146.180/private -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'"
To have failed, but it was successful:
Exitcode: 0 
Stdout:
 	 
Stderr:
 	 

/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/Policies.go:483
```

Interestingly, that occurrence didn't even have the timing output from curl. But we can validate that we hit the timeout by checking timestamps for commands in `test-output.log`.

**Comment by brb** [comment]
Haven't seen it in awhile, closing.
