### ISSUE TITLE
socket-lb is broken on minikube in Docker mode

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15769]
When running minikube in the [Docker mode](https://minikube.sigs.k8s.io/docs/drivers/docker/) (aka k8s docker-in-docker), ClusterIP services cannot be reached with socket-lb enabled (aka host-reachable svc; enabled by default on newer kernels due to the `--kube-proxy-replacement` defaulting to probe). This is due to the same reason as documented in https://github.com/cilium/cilium/pull/14951.

- [x] In the GSG minikube disable socket-lb or ask users to chose another minikube mode (release blocker).
- [ ] Fix socket-lb for minikube in the Docker mode (requires host to run in cgroup v2).

**Comment by rolinh** [comment]
@aditighag I believe the problem arises with kernel 5.10+. Which version do you run?

**Comment by tgraf** [comment]
If we do any work on this before the release, it should be the doc change as mentioned in the top comment:
>  In the GSG minikube disable socket-lb or ask users to chose another minikube mode (release blocker).

**Comment by aditighag** [comment]
Looks like the minikube GSG was removed in v1.10.0-rc1.

**Comment by brb** [comment]
More digging. After changing the Docker cgroup driver to `cgroupfs` (what we have on vagrant dev VMs), it still works. Example of cilium-agent cgroups:
```
> cat /proc/305989/cgroup
0::/docker/7e50a71c256fc473a62382c1e08efec5e046f1fc063d000cc263c4a185d56488/kubelet/kubepods/burstable/pod7cfcf9c8-7afd-447e-81ec-06189684942f/a519ec8e4ed46d409787f1683c136ab0b6d2ea5afa3fd1cf15978690c01371fd
$~/tmp/kind [05:10:04]
> cat /proc/306506/cgroup
0::/docker/9326f9d808c871c1d464b3593b6ff59a02685116b308e54b6a563c08d56ca192/kubelet/kubepods/burstable/podcf46c98d-1933-41bb-b3a1-90b8eee4a1ac/6c08e7e4ddc7454540c7a011fbb92346aaff9ae45e522a86ee49d0b4433803d9
```

**Comment by brb** [comment]
@ti-mo Maybe you have chance to validate the fix?

**Comment by ti-mo** [comment]
Thanks, will do and report back. :+1:
