### ISSUE TITLE
v1.10 clustermesh followups

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#15774]
We had a discussion with a user on Slack trying out the latest (v1.10-style) clustermesh documentation last week, and these followup items were raised which we should consider addressing before the final release:

* [x] Possible certificate issue for clustermesh where the agents in the same cluster as the local clustermesh etcd can't connect. I'm not sure if we even intend for this connectivity to occur, why would the local cluster need to connect to the local clustermesh etcd?
* [x] Network policy across clusters requires `--identity-allocation-mode=kvstore` to pull the remote identities from remote kvstores. We seem to have just dropped that instruction from the new v1.10 instructions so it's just broken right now.

**Comment by cmluciano** [comment]
cc @jrajahalme @tgraf 

I think on the first topic, we would expect to only expect someone to access that local clustermesh etcd if they were at a scale whereby distribution via k8s watchers wasn't sufficient and therefore etcd would perform these updates. As tgraf explained it instead of "apiserver -> agents, we would have apiserver -> clustermesh-apiserver -> agents". Do we want to document how you can leverage this if you need to run at this scale ?

On the second point, the docs for external-workloads specifically state that we should use `identity-allocation-mode=crd`. For v1.9 we explicitly state that kvstore is the preferred store, but in the latest cilium-cli we use `crd` mode like external-workloads. Is there an expectation that `crd` should work for cross cluster policy?

**Comment by joestringer** [comment]
> Do we want to document how you can leverage this if you need to run at this scale ?

If we have a legitimate reason for this point, I think my main remaining question is whether the Cilium CLI is properly configuring the certificates for access to the local cluster. I didn't try this myself, but a community user on Slack just mentioned that they were getting complaints from etcd. Maybe this is just a matter of doing a minor enhancement to the CLI. Alternatively sure if there's some manual step that the user needs to run, then I'm fine with documenting that but I don't really understand what that will look like.

> On the second point, the docs for external-workloads specifically state that we should use identity-allocation-mode=crd. For v1.9 we explicitly state that kvstore is the preferred store, but in the latest cilium-cli we use crd mode like external-workloads. Is there an expectation that crd should work for cross cluster policy?

From my perspective, I think it's OK for the local agent to use CRD for allocating identities etc. However, for remote clusters, we must connect to remote etcds as provisioned by the clustermesh-apiserver feature, and then monitor those etcds for identity updates. My understanding is that today, Cilium-agent configures both of these aspects via only one flag, the `identity-allocation-mode`. As a consequence, this means that if you don't configure it to etcd then Cilium-agent won't monitor remote clusters for their identities so it can't make policy determinations for the remote identities. We can of course double-check whether this assertion is correct, and if so maybe the answer is to adjust the way that the remote cluster identity monitoring works to ensure that it picks up the remote identities regardless of the `identity-allocation-mode` setting.

**Comment by sstoner** [comment]
> > Do we want to document how you can leverage this if you need to run at this scale ?
> 
> If we have a legitimate reason for this point, I think my main remaining question is whether the Cilium CLI is properly configuring the certificates for access to the local cluster. I didn't try this myself, but a community user on Slack just mentioned that they were getting complaints from etcd. Maybe this is just a matter of doing a minor enhancement to the CLI. Alternatively sure if there's some manual step that the user needs to run, then I'm fine with documenting that but I don't really understand what that will look like.
> 
> > On the second point, the docs for external-workloads specifically state that we should use identity-allocation-mode=crd. For v1.9 we explicitly state that kvstore is the preferred store, but in the latest cilium-cli we use crd mode like external-workloads. Is there an expectation that crd should work for cross cluster policy?
> 
> From my perspective, I think it's OK for the local agent to use CRD for allocating identities etc. However, for remote clusters, we must connect to remote etcds as provisioned by the clustermesh-apiserver feature, and then monitor those etcds for identity updates. My understanding is that today, Cilium-agent configures both of these aspects via only one flag, the `identity-allocation-mode`. As a consequence, this means that if you don't configure it to etcd then Cilium-agent won't monitor remote clusters for their identities so it can't make policy determinations for the remote identities. We can of course double-check whether this assertion is correct, and if so maybe the answer is to adjust the way that the remote cluster identity monitoring works to ensure that it picks up the remote identities regardless of the `identity-allocation-mode` setting.

`local agent` is also the remote cluster. If `local agent` is using crd, how does another remote cluster monitor the `local agent`'s identities?  I think the document needs to notify user to set `kvstore: etcd`, because if we don't explicitly state the `kvstore`, `identity-allocation-mode` will force to set to `crd`

https://github.com/cilium/cilium/blob/31625355bec914998bbf372a0519a87a4a8e1c3f/pkg/option/config.go#L2647-L2651

Further, do we consider that remove entirely kvstore from clustermesh?  is that possible?

**Comment by joestringer** [comment]
> local agent is also the remote cluster. If local agent is using crd, how does another remote cluster monitor the local agent's identities? I think the document needs to notify user to set kvstore: etcd, because if we don't explicitly state the kvstore, identity-allocation-mode will force to set to crd

This is the beauty of clustermesh-apiserver: It automatically deploys an etcd instance in the cluster and mirrors the local CRD content into this etcd. Then the remote clusters can be configured to connect to the etcd instance to pull the local cluster's information instead, and we don't have to expose the local cluster's apiserver to other clusters or handle apiserver RBAC configuration for each cluster etc.

> Further, do we consider that removing entirely kvstore from clustermesh? is that possible?

I don't know if anyone has thought all the way through the implications yet.

**Comment by jrajahalme** [comment]
I just tested clustermesh with two Kind clusters via `cilium-cli`, which defaults installs to Cilium 1.9.5, CRD allocation mode, and `kvstore=""`. Identity propagation between clusters works fine:
```
vagrant@runtime:~/go/src/github.com/cilium/cilium-cli$ kubectl --context=$CLUSTER2 logs cilium-94tvw -n kube-system | grep -i -e allocation-mode -e clustermesh -e kvstore
level=info msg="  --clustermesh-config='/var/lib/cilium/clustermesh/'" subsys=daemon
level=info msg="  --identity-allocation-mode='crd'" subsys=daemon
level=info msg="  --kvstore=''" subsys=daemon
level=info msg="  --kvstore-connectivity-timeout='2m0s'" subsys=daemon
level=info msg="  --kvstore-lease-ttl='15m0s'" subsys=daemon
level=info msg="  --kvstore-opt='map[]'" subsys=daemon
level=info msg="  --kvstore-periodic-sync='5m0s'" subsys=daemon
level=info msg="Skipping kvstore configuration" subsys=daemon
level=info msg="Initializing ClusterMesh routing" path=/var/lib/cilium/clustermesh/ subsys=daemon
level=info msg="New remote cluster configuration" clusterName=cluster1 config=/var/lib/cilium/clustermesh/cluster1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/cluster1 endpoints="[https://cluster1.mesh.cilium.io:30567]" subsys=kvstore
level=info msg="Got lease ID 7c0279144db5582c" subsys=kvstore
level=info msg="Got lock lease ID 7c0279144db5582e" subsys=kvstore
level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/cluster1 endpoints="[https://cluster1.mesh.cilium.io:30567]" subsys=kvstore
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/cluster1 endpoints="[https://cluster1.mesh.cilium.io:30567]" etcdEndpoint="https://cluster1.mesh.cilium.io:30567" subsys=kvstore version=3.4.13
level=info msg="Connection to remote cluster established" clusterName=cluster1 config=/var/lib/cilium/clustermesh/cluster1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
level=info msg="Established connection to remote etcd" clusterName=cluster1 config=/var/lib/cilium/clustermesh/cluster1 kvstoreErr="<nil>" kvstoreStatus="Waiting for initial connection to be established" subsys=clustermesh
level=info msg="New endpoint" containerID=591a8d0e85 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=5 identity=133975 ipv4=10.202.0.68 ipv6= k8sPodName=kube-system/clustermesh-apiserver-957767d9b-swwk2 subsys=endpoint
level=info msg="Reserved new local key" key="k8s:io.cilium.k8s.policy.cluster=cluster2;k8s:io.cilium.k8s.policy.serviceaccount=clustermesh-apiserver;k8s:io.kubernetes.pod.namespace=kube-system;k8s:k8s-app=clustermesh-apiserver;" subsys=allocator
level=info msg="Reusing existing global key" key="k8s:io.cilium.k8s.policy.cluster=cluster2;k8s:io.cilium.k8s.policy.serviceaccount=clustermesh-apiserver;k8s:io.kubernetes.pod.namespace=kube-system;k8s:k8s-app=clustermesh-apiserver;" subsys=allocator
level=info msg="Rewrote endpoint BPF program" containerID=591a8d0e85 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=5 identity=133975 ipv4=10.202.0.68 ipv6= k8sPodName=kube-system/clustermesh-apiserver-957767d9b-swwk2 subsys=endpoint
```
```
vagrant@runtime:~/go/src/github.com/cilium/cilium-cli$ kubectl --context=$CLUSTER2 exec cilium-94tvw -n kube-system -it -- cilium identity list
Defaulted container "cilium-agent" out of: cilium-agent, ebpf-mount (init), clean-cilium-state (init)
ID       LABELS
1        reserved:host
2        reserved:world
3        reserved:unmanaged
4        reserved:health
5        reserved:init
6        reserved:remote-node
70045    k8s:io.cilium.k8s.policy.cluster=cluster1
         k8s:io.cilium.k8s.policy.serviceaccount=coredns
         k8s:io.kubernetes.pod.namespace=kube-system
         k8s:k8s-app=kube-dns
71841    k8s:app=local-path-provisioner
         k8s:io.cilium.k8s.policy.cluster=cluster1
         k8s:io.cilium.k8s.policy.serviceaccount=local-path-provisioner-service-account
         k8s:io.kubernetes.pod.namespace=local-path-storage
129471   k8s:io.cilium.k8s.policy.cluster=cluster1
         k8s:io.cilium.k8s.policy.serviceaccount=clustermesh-apiserver
         k8s:io.kubernetes.pod.namespace=kube-system
         k8s:k8s-app=clustermesh-apiserver
131452   k8s:app=local-path-provisioner
         k8s:io.cilium.k8s.policy.cluster=cluster2
         k8s:io.cilium.k8s.policy.serviceaccount=local-path-provisioner-service-account
         k8s:io.kubernetes.pod.namespace=local-path-storage
133975   k8s:io.cilium.k8s.policy.cluster=cluster2
         k8s:io.cilium.k8s.policy.serviceaccount=clustermesh-apiserver
         k8s:io.kubernetes.pod.namespace=kube-system
         k8s:k8s-app=clustermesh-apiserver
145676   k8s:io.cilium.k8s.policy.cluster=cluster2
         k8s:io.cilium.k8s.policy.serviceaccount=coredns
         k8s:io.kubernetes.pod.namespace=kube-system
         k8s:k8s-app=kube-dns
```

**Comment by jrajahalme** [comment]
There should be no reason for a node to connect to the local `clustermesh-apiserver`. If kvstore is wanted for cluster's identity allocation, the local kvstore should be configured independently of clustermesh. That is, the etcd instance within `clustermesh-apiserver` is not to be used for cluster's local identity allocation, but only for cross-cluster identity propagation.

**Comment by jrajahalme** [comment]
> From my perspective, I think it's OK for the local agent to use CRD for allocating identities etc. However, for remote clusters, we must connect to remote etcds as provisioned by the clustermesh-apiserver feature, and then monitor those etcds for identity updates. My understanding is that today, Cilium-agent configures both of these aspects via only one flag, the `identity-allocation-mode`. As a consequence, this means that if you don't configure it to etcd then Cilium-agent won't monitor remote clusters for their identities so it can't make policy determinations for the remote identities. We can of course double-check whether this assertion is correct, and if so maybe the answer is to adjust the way that the remote cluster identity monitoring works to ensure that it picks up the remote identities regardless of the `identity-allocation-mode` setting.

The test output above shows that this is already done as required at least when `identity-allocation-mode = crd`.

**Comment by joestringer** [comment]
Thanks for trying it out @jrajahalme , sounds like our answer to the second item in the description is "cannot reproduce". I've checked that box.

For the first item in the description of the issue, we need to decide whether to:
a) Document that etcd will always complain like that with the current release
b) Update cilium-cli to avoid configuring Cilium to connect to the local etcd
c) Update cilium-cli to properly configure the secrets to allow connecting to the local etcd.

It sounds like (c) may be a bigger job that is not worth doing in the v1.10 timeline, so that would leave options (a) or (b). (b) would be my preference but I don't know how complicated it would be to change the way that these settings are configured.

**Comment by jrajahalme** [comment]
> b) Update cilium-cli to avoid configuring Cilium to connect to the local etcd

What does "local etcd" here mean? etcd managed by `cilium-etcd-operator` or the etcd pod deployed with `clustermesh-apiserver`? Or something else?

**Comment by joestringer** [comment]
I'll admit I'm a little out of my depth here since I'm not reproducing or observing the errors, but what I hear is that if you configure encryption using the cilium cluster CLI you will see errors like the below in the etcd logs, likely due to a misconfigured cilium-agent:

```
2021-04-15 04:48:39.013053 I | embed: rejected connection from "10.37.88.58:42468" (error "EOF", ServerName "")
2021-04-15 04:48:39.014336 I | embed: rejected connection from "10.37.92.207:40140" (error "EOF", ServerName "")
2021-04-15 04:48:39.034042 I | embed: rejected connection from "10.37.37.219:15002" (error "tls: first record does not look like a TLS handshake", ServerName "")
2021-04-15 04:48:39.233785 I | embed: rejected connection from "10.37.37.219:15008" (error "tls: first record does not look like a TLS handshake", ServerName "")
2021-04-15 04:48:39.560465 I | embed: rejected connection from "10.37.199.244:39610" (error "EOF", ServerName "")
2021-04-15 04:48:39.561120 I | embed: rejected connection from "10.37.102.237:34945" (error "EOF", ServerName "")
```

It seems like these are not "real" problems that inhibit connectivity, but noise in the cluster that may make it more difficult to debug the real errors since they suggest there's a problem when there doesn't seem to be a problem. So my suggestion is to investigate and quieten these errors by whatever mechanism we think makes sense.

The corresponding Slack thread is here:
https://cilium.slack.com/archives/C53TG4J4R/p1618461366253900

**Comment by joestringer** [comment]
Couldn't reproduce the issue with errors in the etcds. If you have more information about this, please post in below and we can reopen the issue.

**Comment by sstoner** [comment]
> > Further, do we consider that removing entirely kvstore from clustermesh? is that possible?
> 
> I don't know if anyone has thought all the way through the implications yet.

@joestringer hi, I read and deployed clustermesh(v1.9.6) with multiple clusters, and I found the following points:     

ClusterMesh's ETCD only stores the local cluster's resources like "`cilium/state/nodes/v1`, `cilium/state/services/v1`, `cilium/state/ip/v1`", and other clusters' resources is merged in the memory like `IPCache`/`globalServiceCache`. So we're not necessary to require ETCD storage if we implement it, but we may modify some structures and interfaces, is that acceptable?

**Comment by joestringer** [comment]
@sstoner I think we'll have to see a more concrete proposal of the changes to give you better guidance on this, I'm not sure I understand which structures or interfaces you are considering to change.

**Comment by sstoner** [comment]
> @sstoner I think we'll have to see a more concrete proposal of the changes to give you better guidance on this, I'm not sure I understand which structures or interfaces you are considering to change.

I'm considering to remove ETCD from cilium-clusterMesh, but I have some questions, why didn’t we start this architecture at  the beginning? Anything I haven't  thought maybe not implementable. And I will provided my proposal ASAP. What I want to refactor is likely following:  
if we set ETCD as KvStore to use clusterMesh, `cilium operator` and `Endpoint.runIPIdentitySync` will start controller for synchronizing `services/ciliumNode/identities` from K8s to KvStore, then ETCD watchers of ClusterMesh will update and merge `IPCache/globalServiceCache/ServiceCache`. So why don't we start controller to sync `IPCache/globalServiceCache/ServiceCache` directly?

**Comment by joestringer** [comment]
> why didn’t we start this architecture at the beginning?

@sstoner I'm aware of at least a couple of considerations, one being that the apiserver has a tendency to become overloaded at high cluster scale so this will only get worse if you build on that model to connect even more clusters to the same apiservers; etcd makes this more efficient and scalable. Another one is that the etcd model separates the concerns more clearly in that remote clusters are not provided credentials directly to the main apiserver in all remote clusters, they are only provided credentials to read state from what is effectively a mirror of internal cluster state so the blast radius is lower in the event of something being misconfigured. There may be other benefits/tradeoffs as well that I'm missing.
