### ISSUE TITLE
Agent: Include Cilium version in the output of cilium status

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#15815]
Presently, it is difficult to know which version of cilium is running on each node from the sysdump contents. Including the cilium version in the output of cilium status (or cilium status --verbose) would be helpful in the troubleshooting stage.

**Comment by aanm** [comment]
@seanmwinn which Cilium version is affected by this? 1.10 has the version in the `status` output?

**Comment by aanm** [comment]
I've marked the PRs that introduced this in 1.10 to be backported to 1.8 and 1.9. I'll close this since it's already fixed.
