### ISSUE TITLE
Bandwidth Manager :The egress restriction does not effective when the pod is on the same node

### ISSUE THREAD

**Issue by ppancake** [cilium/cilium#15824]
**General Information**

- Cilium version:1.9.6
```
Client: 1.9.6 38dd27a 2021-04-20T14:57:11-07:00 go version go1.15.11 linux/amd64
Daemon: 1.9.6 38dd27a 2021-04-20T14:57:11-07:00 go version go1.15.11 linux/amd64
```
- Kernel version :`5.4.54`
- Kubectl version :`v1.21.0`

**Phenomenon**
When I use kubernetes.io/egress-bandwidth to limit the entry rate of pod， it work when  pods on different nodes.

I created 3 pods, pod1 on node1,pod2 and pod3 on node2, and only do 2M egress limit on pod2. And I use netperf to test.
When test pod2 -> pod1, in different nodes , the restrictions take effect.
```
Recv   Send    Send                          
Socket Socket  Message  Elapsed              
Size   Size    Size     Time     Throughput  
bytes  bytes   bytes    secs.    10^6bits/sec  
131072  16384  16384    14.00       1.91  
```
But test pod2-> pod3, in same nodes, the restriction not in effect
```
Recv   Send    Send                          
Socket Socket  Message  Elapsed              
Size   Size    Size     Time     Throughput  
bytes  bytes   bytes    secs.    10^6bits/sec  
131072  16384  16384    10.00    10140.43  
```
Is this normal?

**Comment by pchaigno** [comment]
Yes, this is expected as rate limiting is enforced on the native device. From [the documentation](https://docs.cilium.io/en/stable/gettingstarted/bandwidth-manager/#bandwidth-manager):
> Cilium’s bandwidth manager supports the `kubernetes.io/egress-bandwidth` Pod annotation which is enforced on egress at the native host networking devices.

**Comment by ppancake** [comment]
Thanks，and I would like to know if Ingress-bandwidth will support in the future.

**Comment by pchaigno** [comment]
> Thanks，and I would like to know if Ingress-bandwidth will support in the future.

Please see https://github.com/cilium/cilium/issues/15636#issuecomment-818605362.

**Comment by ppancake** [comment]
> > Thanks，and I would like to know if Ingress-bandwidth will support in the future.
> 
> Please see [#15636 (comment)](https://github.com/cilium/cilium/issues/15636#issuecomment-818605362).

Hello, I've used the documentation for flow control using an **ifb** network device, and the results seem to be working.
[Bandwidth Manager (beta)](https://docs.cilium.io/en/stable/gettingstarted/bandwidth-manager/#bandwidth-manager)

In the Cilium(1.9.6) cluster，for pod1,  it's network device is lxc9ba892673f6b, do the ifb setting:

```
tc filter add dev lxc9ba892673f6b ingress protocol ip prio 0 u32 match u32 0 0 flowid ffff: action mirred egress redirect dev ifb1
tc qdisc add dev ifb1 root tbf rate 100kbit latency 20ms burst 1540
```
Test with iperf3, the results of the lxc9ba892673f6b  rxkB/s = 12.24kB/s = 100kbit

```
Average:        IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s
Average:           lo     22.66     22.66      1.27      1.27      0.00      0.00      0.00
Average:         ifb1    189.35    189.35     12.20     12.20      0.00      0.00      0.00
Average:         eth0    406.81    206.49    576.77     25.13      0.00      0.00      0.00
Average:      docker0      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:    cilium_vxlan    196.80    189.83    538.60      9.64      0.00      0.00      0.00
Average:    lxc9ba892673f6b    189.99    196.40     12.24    541.26      0.00      0.00      0.00
```

So I would like to know about this ifb scheme, its **network latency and performance loss**. 
And will this ifb solution be adopted in the later version？Or will there be other Ingress flow limiting solutions?

Thanks.
