### ISSUE TITLE
hubble-ui doesn't start on arm64

### ISSUE THREAD

**Issue by oivindoh** [cilium/cilium#15840]
## Bug report

**General Information**

- Cilium version `v1.10.0-rc0` (helm chart, no options)
- Kernel version: `5.4.0-1030-raspi #33-Ubuntu SMP PREEMPT Wed Feb 24 11:20:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
- Orchestration system version in use: `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0-rc1+k3s1", GitCommit:"2705431d9645d128441c578309574cd262285ae6", GitTreeState:"clean", BuildDate:"2021-04-21T23:32:49Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/arm64"}`

1. Following https://docs.cilium.io/en/stable/gettingstarted/k3s/#k3s-install
2. Get to "Enable Hubble for Cluster-Wide Visibility", run listed command
3. hubble-ui stuck in CrashLoopBack: `k3s kubectl -n kube-system logs hubble-ui-567d4f7df4-6lhs7 -c backend
standard_init_linux.go:228: exec user process caused: exec format error`

The chart deploys v0.7.3 of the hubble containers from quay.io, and I attempted to override with the latest I could see (v0.7.6) to no avail. Is this not being multiarch intentional?

**Comment by aanm** [comment]
@oivindoh thanks for reporting it, can you test with this images? `quay.io/cilium/hubble-ui-backend-ci:1f1838dbdcbc3bf39a190f127fffbcd4823f6dc` and `quay.io/cilium/hubble-ui-ci:1f1838dbdcbc3bf39a190f127fffbcd4823f6dcb`. Thanks

**Comment by oivindoh** [comment]
I can confirm those two images start successfully 👍 

There's one remaining issue with envoy, where the assigned 1.14.5 release doesn't appear to have an arm64 version. Looking at the [dockerhub repo](https://hub.docker.com/r/envoyproxy/envoy/tags?page=1&ordering=last_updated&name=v1.), it seems one has to use v.1.16.0 or later to get multiarch containers from them

**Comment by oivindoh** [comment]
I've successfully got hubble ui up and running using the provided [ci images](https://github.com/cilium/cilium/issues/15840#issuecomment-825364086) you kindly provided, in addition to envoy [v.1.16.3](https://hub.docker.com/layers/envoyproxy/envoy/v1.16.2/images/sha256-40c5435edba65db6d07f35a504a7da08a4923cdb57791380a5bd834d2140820f?context=explore) - envoy v1.18.2 was a bit too optimistic due to v2 xDS being deprecated/disabled (and probably other reasons - I'm not yet very familiar with envoy).

**Comment by aanm** [comment]
for the envoy one I've created this GH issue https://github.com/cilium/cilium/issues/15842
