### ISSUE TITLE
L7 policies are difficult to read in output of "cilium endpoint get"

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#1584]
The policies have a lot of escaped characters, etc. that make it very difficult to parse what is happening.  Here is a basic example of a 

    "l4": {
      "egress": [
        "{\n  \"Port\": 9080,\n  \"Protocol\": \"TCP\",\n  \"L7Parser\": \"http\",\n  \"L7RedirectPort\": 0,\n  \"L7Rules\": [\n    {\n      \"expr\": \"PathRegexp(\\\"^/jobs$\\\") \\u0026\\u0026 MethodRegexp(\\\"GET\\\")\"\n    },\n    {\n      \"expr\": \"PathRegexp(\\\"^/applicants$\\\") \\u0026\\u0026 MethodRegexp(\\\"POST\\\")\"\n    }\n  ],\n  \"Ingress\": false\n}",
        "{\n  \"Port\": 53,\n  \"Protocol\": \"UDP\",\n  \"L7Parser\": \"\",\n  \"L7RedirectPort\": 0,\n  \"L7Rules\": null,\n  \"Ingress\": false\n}"
      ],
      "ingress": []
    }

**Comment by tgraf** [comment]
FYI: #1580 already contains code to do this as it was required for the Envoy integration

**Comment by joestringer** [comment]
There's two pieces to this:
* [x] Proxy-specific formatting (Resolved in #1580)
* [x] Escaping is being shown at all in L4 rules (#2198)
