### ISSUE TITLE
getting started connectivity test fails on arm64 (cilium 1.10.0-rc0

### ISSUE THREAD

**Issue by oivindoh** [cilium/cilium#15843]
## Bug report

**General Information**

- Cilium version `v1.10.0-rc0` (helm chart, no options)
- Kernel version: `5.4.0-1030-raspi #33-Ubuntu SMP PREEMPT Wed Feb 24 11:20:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
- Orchestration system version in use: `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0-rc1+k3s1", GitCommit:"2705431d9645d128441c578309574cd262285ae6", GitTreeState:"clean", BuildDate:"2021-04-21T23:32:49Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/arm64"}`

**How to reproduce the issue**

To reproduce, follow the k3s getting started doc on an arm64-based kubernetes cluster, which will fail at [the connectivity test step](https://docs.cilium.io/en/stable/gettingstarted/k3s/#deploy-the-connectivity-test)

The following images are used in the connectivity test yaml, and lack arm64 variants. I'm following [the k3s Getting started doc](https://docs.cilium.io/en/stable/gettingstarted/k3s/#k3s-install) on a rapsberry pi 4 cluster.

- byrnedo/alpine-curl (there was a marged PR for this in its repo, but it doesn't seem to actually be available from that travis config)
- cilium/json-mock

This is a followup for issue #15840, and I believe the final missing piece for arm64 support in 1.10.0

**Comment by munjalpatel** [comment]
We are still experiencing this issue. Is this resolved? Is there a workaround?

```
cilium-cli: v0.12.6 compiled with go1.19.1 on darwin/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.3
cilium image (running): v1.12.3
```
