### ISSUE TITLE
AWS: Add context to the ENI metadata call

### ISSUE THREAD

**Issue by Smana** [cilium/cilium#15850]
Hi,

Following this pull-request https://github.com/cilium/cilium/pull/15828 and thanks to @christarazi's review, we may want to add context when the AWS metadata API is called .At least that would be wise to add a timeout in order to avoid hanging while waiting for an answer.

Currently we just have 

```golang
func newClient() (*imds.Client, error) {
	cfg, err := config.LoadDefaultConfig(context.TODO())
```

**Comment by aanm** [comment]
This issue hasn't seen any comment for over 3 years, closing for lack of interest.
