### ISSUE TITLE
Add node cilium annotation for VXLAN integration with external loadbalancer

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#15852]
## Proposal / RFE

flannel has annotation like below:
<pre>
Annotations:        alpha.kubernetes.io/provided-node-ip: 10.169.72.127
                     flannel.alpha.coreos.com/backend-data: {"VtepMAC":"3e:aa:32:a8:1f:a5"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.169.72.127
</pre>

Third party external loadbalancer like BIG-IP has project like https://github.com/F5Networks/k8s-bigip-ctlr
to extract the flannel backend-data VtepMAC and public-ip to pre-populate BIG-IP FDB entries so BIG-IP VXLAN implementation could integrate with flannel VXLAN  https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/pkg/vxlan/vxlanMgr.go#L138,  BIG-IP could communicate with k8s POD over VXLAN network, as a result, BIG-IP could use POD IP as BIG-IP virtual pool member. see the diagram in https://clouddocs.f5.com/containers/latest/userguide/what-is.html

Does the cilium VXLAN tunnel mode work with third party VXLAN implementation? if it works, Could cilium add additional VXLAN annotation like flannel so third party k8s controller could extract the annotation and pre-populate the FDB entries in third party VXLAN implementation?

**Is your feature request related to a problem?**

Unable to integrate cilium VXLAN tunnel mode with BIG-IP VXLAN 

**Describe the solution you'd like**

see Proposal note or suggest better solution to integrate cilium VXLAN with third party VXLAN implementation.

**Comment by vincentmli** [comment]
@tklauser 

after dig a little deeper into the cilium VXLAN datapath, I don't think the tunnel mode would work with standard third party VXLAN implementation, please correct me if I am wrong.  

My understanding is that the tunnel mode  datapath is not using Linux stack vxlan datapath implementation (driver/net/vxlan.c), but use BPF  and attached the code https://github.com/cilium/cilium/blob/v1.9.1/bpf/lib/encap.h#L146 and XDP redirect. also the VNI is selected to use the endpoint identity

  2     65  bpf/bpf_overlay.c <<handle_ipv6>>
             *identity = key.tunnel_id = get_identity(ctx);
   3     69  bpf/bpf_overlay.c <<handle_ipv6>>
             *identity = key.tunnel_id;
   4     79  bpf/bpf_overlay.c <<handle_ipv6>>
             cilium_dbg(ctx, DBG_DECAP, key.tunnel_id, key.tunnel_label);
   5    189  bpf/bpf_overlay.c <<handle_ipv4>>
             *identity = key.tunnel_id = get_identity(ctx);
   6    193  bpf/bpf_overlay.c <<handle_ipv4>>
             *identity = key.tunnel_id;
   7    199  bpf/bpf_overlay.c <<handle_ipv4>>
             cilium_dbg(ctx, DBG_DECAP, key.tunnel_id, key.tunnel_label);
   8    130  bpf/lib/encap.h <<__encap_with_nodeid>>
             key.tunnel_id = seclabel;
   9   2085  bpf/lib/nodeport.h <<health_encap_v4>>
             key.tunnel_id = seclabel == HOST_ID ? LOCAL_NODE_ID : seclabel;
  10   2102  bpf/lib/nodeport.h <<health_encap_v6>>
             key.tunnel_id = seclabel == HOST_ID ? LOCAL_NODE_ID : seclabel;

and no FDB involved 

So in BIG-IP VXLAN integration, this seems would not work since BIG-IP VXLAN and Flannel VXLAN integration uses one single VNI ID to communicate with all the pods in K8S.

Am I understanding it correct that cilium BPF tunnel datapath mode would not integrate well with external third party VXLAN implementation? if so any opinion to improve it ?

**Comment by joestringer** [comment]
Cilium expects that the VNI field is used for identity and not a virtual network, correct. This means that if you are integrating with a third party VXLAN implementation, that implementation should send packets towards Cilium nodes in a way that respects the identity of the packets, maybe one approach would be to inject the "world" identity when transmitting packets towards Cilium nodes. If you are configuring the nodes to attract outbound traffic to the BIG-IP devices, then the devices should expect to receive packets with the VNI field populated with any value.

As for teaching BIG-IP about the MAC addresses of the VTEPs of the individual nodes, is that just a matter of populating an annotation on either Node or CiliumNode resources? That aspect sounds straightforward to implement. Beyond that, I believe that Cilium uses the `InternalIP` associated with the Node resource so I'm not sure that we need to annotate the VTEP underlay IP separately from that.

**Comment by vincentmli** [comment]
> Cilium expects that the VNI field is used for identity and not a virtual network, correct. This means that if you are integrating with a third party VXLAN implementation, that implementation should send packets towards Cilium nodes in a way that respects the identity of the packets, maybe one approach would be to inject the "world" identity when transmitting packets towards Cilium nodes. If you are configuring the nodes to attract outbound traffic to the BIG-IP devices, then the devices should expect to receive packets with the VNI field populated with any value.
> 

In BIGIP vxlan tunnel integration with flannel,  if I create a VXLAN tunnel in BIGIP, the tunnel usually requires an uniq VNI ID, let's say VNI ID as 1, then when packet egress from BIGIP,  the VNI will be 1, and BIGIP expect to receive VXLAN packet with VNI 1, all non VNI 1 VXLAN packet will get dropped.  

What is the "world" identity? is the "world" identity has value as 0?  in BIGIP, I could try assign  VNI value 0, if 0 means "world", that may enable cilium POD in k8s receiving traffic from BIGIP fine, but I guess BIGIP will  still drop the packet from cilium POD with  VNI with value of POD identity. I could test creating tunnel in BIGIP with VNI 0  to validate the what BIGIP does to VNI when sending/receiving VXLAN packet

**Comment by vincentmli** [comment]
I did a quick test between flannel and BIGIP, so the VNI value has to be the same value between the flannel VXLAN tunnel and BIGIP VXLAN  tunnel, say flannel VXLAN  tunnel has VNI value 1, BIGIP VXLAN tunnel has VNI value 2, when flannel VXLAN tunnel received the packet with VNI value 2, the packet will be dropped by flannel ( kernel driver/net/vxlan.c), the same to BIGIP if BIGIP receives VNI value 1 from flannel. setting the BIGIP VXLAN VNI to value 0, still the same.

As you mentioned earlier, the VNI used by Cilium with identity is not really to the true meaning of VXLAN VNI identifier and virtual network, my question are:

1, What is the purpose to use identity as the VNI in Cilium managed POD in overlay ? 

2, Is it possible under Cilium tunnel mode, a common same VNI value could be used instead of using each POD identity  or in some way, under some condition, to make tunnel act like a true meaning of virtual network with third party VXLAN integration?

**Comment by vincentmli** [comment]
> 
> 1, What is the purpose to use identity as the VNI in Cilium managed POD in overlay ?
> 
> 2, Is it possible under Cilium tunnel mode, a common same VNI value could be used instead of using each POD identity or in some way, under some condition, to make tunnel act like a true meaning of virtual network with third party VXLAN integration?

after reading more about kernel drivers/net/vxlan.c,  and bpf/init.sh, I start to understand that Cilium VXLAN implementation is not based on VNI key/FDB, but metadata/external, the bpf/init.sh actually shows how cilium_vxlan is created

<pre>
if [ "$MODE" = "vxlan" -o "$MODE" = "geneve" ]; then
        ENCAP_DEV="cilium_${MODE}"
        ip link show $ENCAP_DEV || {
                ip link add name $ENCAP_DEV address $(rnd_mac_addr) type $MODE external || encap_fail
        }
        ip link set $ENCAP_DEV mtu $MTU || encap_fail

        setup_dev $ENCAP_DEV || encap_fail

        ENCAP_IDX=$(cat /sys/class/net/${ENCAP_DEV}/ifindex)
        sed -i '/^#.*ENCAP_IFINDEX.*$/d' $RUNDIR/globals/node_config.h
        echo "#define ENCAP_IFINDEX $ENCAP_IDX" >> $RUNDIR/globals/node_config.h

        CALLS_MAP="cilium_calls_overlay_${ID_WORLD}"
        COPTS="-DSECLABEL=${ID_WORLD} -DFROM_ENCAP_DEV=1"
        if [ "$NODE_PORT" = "true" ]; then
                COPTS="${COPTS} -DDISABLE_LOOPBACK_LB"
        fi
        bpf_load $ENCAP_DEV "$COPTS" "ingress" bpf_overlay.c bpf_overlay.o from-overlay ${CALLS_MAP}
        bpf_load $ENCAP_DEV "$COPTS" "egress" bpf_overlay.c bpf_overlay.o to-overlay ${CALLS_MAP}
else

</pre>

ip link manual explains the "external" https://man7.org/linux/man-pages/man8/ip-link.8.html
<pre>
                      [no]external - specifies whether an external
                      control plane (e.g. ip route encap) or the
                      internal FDB should be used.
</pre>

and drivers/net/vxlan.c has commits below 
<pre>
commit ee122c79d4227f6ec642157834b6a90fcffa4382
Author: Thomas Graf <tgraf@suug.ch>
Date:   Tue Jul 21 10:43:58 2015 +0200

    vxlan: Flow based tunneling

commit da8b43c0e1dcea3bcac5f37ea59934ddaa137aed
Author: Alexei Starovoitov <ast@plumgrid.com>
Date:   Tue Aug 4 22:51:07 2015 -0700

    vxlan: combine VXLAN_FLOWBASED into VXLAN_COLLECT_METADATA

commit b9167b2e775999d267874b5a1a3a79020f54753a
Author: Jiri Benc <jbenc@redhat.com>
Date:   Tue Feb 16 21:59:03 2016 +0100

    vxlan: treat vni in metadata based tunnels consistently

commit db3c6139e6ead91b42e7c2ad044ed8beaee884e6
Author: Daniel Borkmann <daniel@iogearbox.net>
Date:   Fri Mar 4 15:15:07 2016 +0100

    bpf, vxlan, geneve, gre: fix usage of dst_cache on xmit

commit 47e5d1b06305e73afc917f47b65490adb06c7194
Author: Jiri Benc <jbenc@redhat.com>
Date:   Tue Apr 5 14:47:11 2016 +0200

    vxlan: move fdb code to common location in vxlan_xmit

commit 3ad7a4b141ebd6091494913672d7166d5c2764e4
Author: Roopa Prabhu <roopa@cumulusnetworks.com>
Date:   Tue Jan 31 22:59:52 2017 -0800

    vxlan: support fdb and learning in COLLECT_METADATA mode

commit fda2ec62cf1aa7cbee52289dc8059cd3662795da
Author: Taehee Yoo <ap420073@gmail.com>
Date:   Sat Aug 1 07:07:50 2020 +0000

    vxlan: fix memleak of fdb

</pre>

**Comment by joestringer** [comment]
> 1, What is the purpose to use identity as the VNI in Cilium managed POD in overlay ?

It's to identify the security context of the source of the traffic so that policy can be applied at the node which receives the traffic. See also the documentation around identity:
https://docs.cilium.io/en/v1.9/concepts/terminology/#identity

> 2, Is it possible under Cilium tunnel mode, a common same VNI value could be used instead of using each POD identity or in some way, under some condition, to make tunnel act like a true meaning of virtual network with third party VXLAN integration?

I think it may be viable to fit such a feature under the "egress gateway" feature, by allowing a custom configuration of the VNI to use when forwarding traffic to an egress gateway and by designating these BIG-IP nodes as gateways for the cluster. The relevant general issue is https://github.com/cilium/cilium/issues/13575 which has links to various PRs to implement the feature as well. So far I believe the merged code for egress gateway all assumes that a Cilium node is nominated as an egress gateway and performs those functions, so the feature may need some extension to remove this assumption and allow other network nodes to participate in this role.

**Comment by vincentmli** [comment]
reference https://github.com/cilium/cilium/issues/16517
