### ISSUE TITLE
Include Hubble CLI v0.8 in Cilium docker image

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#15858]
Marking this a s a release blocker for the final Cilium 1.10 version so we don't miss this. During the Cilium 1.10 release cycle, the Hubble CLI gained a few improvements that we want to ship with the Cilium 1.10.

The Hubble CLI is included for local troubleshooting in the `cilium` container:
https://github.com/cilium/cilium/blob/96eb526b9e84502716b60c07746415838556e746/images/cilium/hubble-version.sh#L2

This needs a Hubble CLI 0.8 release first to pick up the latest changes. This is expected to happen once Cilium branches off the v1.10 branch (due to there being a cyclic dependency between the Hubble and Cilium source tree).

**Comment by joestringer** [comment]
There's a v1.10 branch for Cilium now, we intend to tag -rc1 in the next day or so.
