### ISSUE TITLE
Generate command reference via cobra/doc

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1586]
The framework we utilize allows generating markdown from the code to automatically document all command line options:

https://chromium.googlesource.com/external/github.com/spf13/cobra/+/refs/heads/master/doc/md_docs.md

**Comment by aalemayhu** [comment]
Tried generating markdown from the example but hitting a dependency issue. Guessing it's because doc is a package in the already imported cobra. Will look for a workaround in the vendor conf.

```
make: Entering directory '/home/scanf/opt/og/src/github.com/cilium/cilium/cilium'
go build -i -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=0.13.90 6a7d1459a48e Fri, 10 Nov 2017 18:47:25 -0800 go version go1.9 linux/amd64"' -o cilium
# github.com/cilium/cilium/cilium/cmd
cmd/root.go:47:28: cannot use rootCmd (type *"github.com/cilium/cilium/vendor/github.com/spf13/cobra".Command) as type *"github.com/spf13/cobra".Command in argument to doc.GenMarkdownTree
make: *** [Makefile:6: cilium] Error 2
make: Leaving directory '/home/scanf/opt/og/src/github.com/cilium/cilium/cilium'
```
