### ISSUE TITLE
postIpamFailure  range is full when spawning more than 250 pods

### ISSUE THREAD

**Issue by SamDecrock** [cilium/cilium#15881]
## Bug report

I'm trying to spawn more than 250 pods on a single node and I'm getting:

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4bb3d166d60c422be07170acc2ff881035c5feb198eddc8f39c8337d44fc511b" network for pod "nginx-deployment-68c767dd76-x9rvg": networkPlugin cni failed to set up pod "nginx-deployment-68c767dd76-x9rvg_test" network: unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  range is full
```

**General Information**

- Cilium version: 1.8 (also tested this with 1.9)
- Kernel version: `Linux dco2-prep 5.4.0-1042-gcp #45~18.04.1-Ubuntu SMP Tue Apr 13 18:51:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**How to reproduce the issue**

Install Kubernetes with kubeadm. Make sure you set your network big enough to hold more than 256 IP addresses:
```yaml
controllerManager:
  extraArgs:
    allocate-node-cidrs: "true"
    node-cidr-mask-size: "16"
networking:
  podSubnet: 10.244.0.0/16
```
Also make sure the pod limit is higher than `110`:
```yaml
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 1000
```

Adjust the cilium manifest with the same values:
```yaml
  cluster-pool-ipv4-cidr: "10.244.0.0/16"
  cluster-pool-ipv4-mask-size: "16"
```

Create a deployment and set its replicas to 500. After 250 pods have been spawned, you will get the following error when doing `kubectl describe pod <pod name>`: 

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4bb3d166d60c422be07170acc2ff881035c5feb198eddc8f39c8337d44fc511b" network for pod "nginx-deployment-68c767dd76-x9rvg": networkPlugin cni failed to set up pod "nginx-deployment-68c767dd76-x9rvg_test" network: unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  range is full
```
Also `kubectl describe nodes` shows me the following entry in its annotations:
```
Annotations:        io.cilium.network.ipv4-cilium-host: 10.0.0.90
                    io.cilium.network.ipv4-health-ip: 10.0.0.7
                    io.cilium.network.ipv4-pod-cidr: 10.0.0.0/24
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
```

**Comment by LucasRouckhout** [comment]
I seem to have the same issue +1

**Comment by aanm** [comment]
can you provide a cilium sysdump? did you check cilium-operator logs to see if there were any warnings present in the logs?

**Comment by SamDecrock** [comment]
There was nothing weird inside the cilium logs.

Last time I installed Cilium 1.8 and switched to 1.9. Now I installed 1.9 from a fresh Kubernetes install and it works. I'm currently running 600 pods on 1 node!

I'm going to try to investigate a little further if upgrading is possible, if not I'll have to reinstall Kubernetes

**Comment by SamDecrock** [comment]
Ok, I tried upgrading from cilium 1.8 to 1.9 by first doing a
```
kubectl delete -f cilium1.8.yaml
```
and then installing it with 
```
kubectl apply -f cilium1.9.yaml
```
But the pods kept getting IP's from the `10.0.0.0/24` range.
Also the node annotations stayed at `io.cilium.network.ipv4-pod-cidr: 10.0.0.0/24`

Only when I reinstalled kubernetes with `kubeadm reset` / `kubeadm init` and installed cilium 1.9, the pods were getting IP's from my new `10.128.0.0/19` range. Also the annotations of the node now state
```
io.cilium.network.ipv4-pod-cidr: 10.128.0.0/19
```

Do these annatations have any meaning? Are they used in any way?

**Comment by christarazi** [comment]
@SamDecrock Cilium will fetch the pod CIDR from the CiliumNode resource if IPAM mode is `cluster-pool` or from the K8s node resource if any another IPAM mode. That would explain why when you upgraded Cilium by deleting and re-applying, Cilium 1.9 used the existing pod CIDR from the resources and then when you reinstalled K8s with `kubeadm`, Cilium picked up the new pod CIDR range.

**Comment by SamDecrock** [comment]
Hmm. There's a `CiliumNode` I didn't know that. Do you mean the CiliumNode stayed alive when I upgraded from 1.8 to 1.9 and see the pod CIDR range was kept?

**Comment by twpayne** [comment]
Yes, the `CiliumNode` CRD is persisted over upgrades.

**Comment by SamDecrock** [comment]
Thanks, that explains it.
