### ISSUE TITLE
node-neigh: Do not arping on AKS

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15910]
In AKS each node's primary interface gets a dummy MAC addr (`12:34:56:78:9a:bc`). Therefore, there is no need to arping each node. Instead, in the `NodeUpdate` event handler we could create a permanent ARP entry and call it a day.

**Comment by pchaigno** [comment]
> Instead, in the `NodeUpdate` event handler we could create a permanent ARP entry and call it a day.

Is that the `NodeUpdate` handler you're referring to? https://github.com/cilium/cilium/blob/687446593b4d7bc25843a17663d0b051695c45b7/pkg/datapath/linux/node.go#L882

**Comment by brb** [comment]
> Is that the NodeUpdate handler you're referring to? 

Yes. Ideally, the new code should be placed inside the `insertNeighbor()` method which is invoked by `nodeUpdate()`.

**Comment by rscampos** [comment]
Hello @brb @pchaigno 
I was looking at this issue... do you guys think that´s ok for a third issue? If so, could please assign to me? Tkss

**Comment by brb** [comment]
Sure. Thanks for working on this.

Before you start, could you validate AKS docs that this is indeed the case for all instance types?

**Comment by rscampos** [comment]
Hello @brb,

Of course, I'll check AKS docs before and reach you if a have any doubt, thank you for the support :D

**Comment by pchaigno** [comment]
@rscampos This issue is specific to AKS, so you'll need an AKS cluster.

**Comment by rscampos** [comment]
Hello @brb @pchaigno, just to get a better understanding of the issue. Is ideally to put changes in `insertNeighbor()` (that is the function that actually do the arping). `insertNeighbor()` is called by `nodeUpdate()` (as mentioned in issue's description),
