### ISSUE TITLE
Investigate syscall and sys/unix usage against EINTR handling

### ISSUE THREAD

**Issue by brb** [cilium/cilium#15932]
From https://golang.org/doc/go1.14#runtime:
> A consequence of the implementation of preemption is that on Unix systems, including Linux and macOS systems, programs built with Go 1.14 will receive more signals than programs built with earlier releases. This means that programs that use packages like syscall or golang.org/x/sys/unix will see more slow system calls fail with EINTR errors. Those programs will have to handle those errors in some way, most likely looping to try the system call again. For more information about this see man 7 signal for Linux systems or similar documentation for other systems. 

We should check whether in all cases where we use `syscall` or `sys/unix` we retry upon getting `EINTR`.

**Comment by ti-mo** [comment]
Since switching to ebpf-go, we no longer have any `unix.Syscall`s in the tree. The lib handles EINTR correctly, as well as blocking SIGPROF before entering PROG_LOAD and PROG_RUN. Closing.
