### ISSUE TITLE
Per node specification or automatic expansion of podCIDRs

### ISSUE THREAD

**Issue by jhead-slg** [cilium/cilium#15949]
## Proposal / RFE

**Is your feature request related to a problem?**
For some Kubernetes nodes I would like to be able to run a larger amount of pods. For instance, I would like to deploy a node pool that handles a specific workload where perhaps 500 pods will run on each node. Cilium is configured to handle IPAM via its default cluster scope (cluster-pool) method handing out a /24 by default. I don't want to waste IP space by handing out a larger CIDR by default to all nodes.

Cilium IPAM reference: https://docs.cilium.io/en/v1.10.0-rc1/gettingstarted/ipam-cluster-pool/#enable-cluster-pool-ipam-mode

GKE reference: https://cloud.google.com/kubernetes-engine/docs/how-to/flexible-pod-cidr#setting_the_maximum_number_of_pods_in_a_new_node_pool_for_an_existing_cluster

**Describe the solution you'd like**

I can think of three solutions:
* Auto-add CIDRs based off the default mask size when the current node has exhausted its supply; don't worry about releasing over-provisioned CIDRs
* Read and compute the node's required CIDR based off the kubelet's `status.capacity.pods` value
* Ability to specify, via annotation or some other method, a ***new*** node's CIDR mask (I.E. per node `ipam.operator.clusterPoolIPv4MaskSize=<IPv4MaskSize>`)

**Comment by knfoo** [comment]
I am really interested in this feature as well.

**Comment by gandro** [comment]
I somehow missed this ticket, but yes, that's correct Dynamic Cluster Pool sounds very similar to option 1. In addition, we're also considering adding option 3 in addition (in case one knows that a node will run many pods), but no concrete implementation on that yes.

**Comment by gandro** [comment]
Option 1 has been implemented as part of #18887 and will be shipped with the v1.12 release as a beta feature. Please feel free to try it out and provide feedback.
