### ISSUE TITLE
Is cilium can only be developed with VirtualBox + Vagrant ？ Can it be developed with VMware + CentOS ?

### ISSUE THREAD

**Issue by h2cw2l** [cilium/cilium#15953]
I want to add some logs to cilium so as to learn code of cilium, I have the env VMware + CentOS.
When I input make, it always hangs as shown in the figure bellow.
So I want to know, is cilium can only be developed with VirtualBox + Vagrant ?
Any reply will be appreciated.
![图片](https://user-images.githubusercontent.com/58133919/116658066-fdfe0f00-a9c1-11eb-9ead-7f3652dacb5f.png)

**Comment by pchaigno** [comment]
I don't know of anyone developing on that environment. Did you try to see why it hangs?

**Comment by h2cw2l** [comment]
> 
> 
> I don't know of anyone developing on that environment. Did you try to see why it hangs?

Thank you for reply, it hangs because the memory I give to the CentOS is not enough.
