### ISSUE TITLE
operator-azure: remove requirement for Azure Service Principal

### ISSUE THREAD

**Issue by nbusseneau** [cilium/cilium#15966]
When deploying on Azure AKS,  `cilium-operator-azure` requires using an Azure Service Principal to authenticate with the API and allocate IPs.

Removing this requirement would allow removing all Azure Service Principal-related Helm values:

- `azure.tenantID`
- `azure.clientID`
- `azure.clientSecret`

Getting rid of the SP requirement would help in three ways I think:
- No need for the user installing into AKS to have specific Azure permissions for popping new SP (both `Microsoft.Authorization/roleAssignments/write` and `Microsoft.Authorization/roleAssignments/delete` required), which helps for Azure security.
- No need to learn about SPs at all, which helps for Azure users that simply consume but don't manage Azure. This has several sub-advantages:
  - No risk of having a single SP ending up with access to multiple clusters.
  - No conflict in case someones creates a new SP for RBAC from the CLI with the name of an already existing SP, which cancels and replaces the previous SP access.
  - No need to remember to clean up SPs when deleting clusters / no SPs piling up.
- And of course a simplified Helm chart, which would also streamline the Cilium Azure installation guides.

Once done, CLI should also be updated: https://github.com/cilium/cilium-cli/issues/203

**Comment by ungureanuvladvictor** [comment]
@nbusseneau -- I spent some time today thinking about this. I think going forward there are 2 main avenues:
- `cilium-operator` inherits Azure API creds from the node it's running on (this is basically the same as AWS ENI IPAM)
- `cilium-operator` runs with a pre-defined SP (service principal) that has the required permissions

In both cases the role which will be attached to either the node identity or the SP will need to have the perms listed in https://docs.cilium.io/en/latest/concepts/networking/ipam/azure/#required-privileges.

I'm aligned with the arguments you lined up in the main comment but I don't think there is a easy way out of this given that when an AKS cluster is launched the perms that the `cilium-operator` needs are not present on any of the identities in the system (this is diff than AWS where the EKS nodes have the right IAM perms and the installation is seamless).

Overall if we remove the ability to provide a SP to the `cilium-operator` we'll have to make it work with https://docs.microsoft.com/en-us/azure/aks/use-managed-identity on the AKS nodes and that will expose other workloads on that node to the perms that the `cilium-operator` needs (users might not be OK with this).

Happy to chat more on this topic -- back in the day I've spent some time on this problem.

**Comment by EppO** [comment]
I think both modes have some valid use cases. 
I would add another one which I think can supersede the Service Principal: a custom User Assigned Id. During AKS creation, you can provide a custom User Assigned Id that has been created prior to the AKS cluster and given some permissions (like private DNS zone contributor for private AKS cluster). You could use that one or create a brand new one dedicated for cilium usage with the appropriate rights. 
The latter would be similar to the dedicated SP, but I find creating and managing User Assigned Ids easier than Service Principals in general. 
Improving the docs regarding the proper rights to give to these User Assigned Ids and SPs would be good too, there is no mention of it on https://docs.cilium.io/en/stable/gettingstarted/k8s-install-aks/

Regarding the kubelet Identity ("Azure API creds from the node it's running on"), I assume you shouldn't even have to set it using `azure-user-assigned-identity-id`, as it should be automatically provided during the Azure MSI API request.

**Comment by verysonglaa** [comment]
+1 on the possibility to use the MI of the node

**Comment by jmcshane** [comment]
One note here is that aad-pod-identity is moving towards being a supported add-on for Azure: https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity. I am hoping to be able to use this pod identity feature to grant access to cilium to the compute resources within the node resource group.
