### ISSUE TITLE
Changing clusterPoolIPv4PodCIDR post deployment

### ISSUE THREAD

**Issue by ClaudiuLSH** [cilium/cilium#15977]
Hi,

I am trying to change clusterPoolIPv4PodCIDR on a live kubernetes cluster. Is there a way to achieve this? I wasn't able to find anything related to this in issues or documentation.

Cilium was deployed with helm and I updated that value, after upgraded the chart. The value was updated in ConfigMap but all pods have IPs from old pool. I even rebooted a node, nothing changed. I am assuming this can't be change once cilium was deployed?

**Comment by vsxen** [comment]
Add A ippool CRD  like calico ? 
😃
