### ISSUE TITLE
Verifying the Setup 

### ISSUE THREAD

**Issue by Cyrus008** [cilium/cilium#15996]
## Compilation of < tools/testing/selftests/bpf/  > is failed :
The compilation error log is given below :

CLNG-BPF [test_maps] loop2.o
  CLNG-BPF [test_maps] sample_map_ret0.o
  CLNG-BPF [test_maps] btf__core_reloc_enumval___err_missing.o
  CLNG-BPF [test_maps] test_rdonly_maps.o
  CLNG-BPF [test_maps] atomics.o
fatal error: error in backend: line 26: Invalid usage of the XADD return value
Stack dump:
0.	Program arguments: clang -g -D__TARGET_ARCH_x86 -mlittle-endian -I/media/byte/DataDisk/net/tools/testing/selftests/bpf/tools/include -I/media/byte/DataDisk/net/tools/testing/selftests/bpf -I/media/byte/DataDisk/net/tools/include/uapi -I/media/byte/DataDisk/net/tools/testing/selftests/usr/include -idirafter /usr/local/include -idirafter /usr/lib/llvm-10/lib/clang/10.0.0/include -idirafter /usr/include/x86_64-linux-gnu -idirafter /usr/include -Wno-compare-distinct-pointer-types -DENABLE_ATOMICS_TESTS -O2 -target bpf -c progs/atomics.c -o /media/byte/DataDisk/net/tools/testing/selftests/bpf/atomics.o -mcpu=v3 
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'progs/atomics.c'.
4.	Running pass 'BPF PreEmit Checking' on function '@add'
 #0 0x00007f34368734ff llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x9814ff)
 #1 0x00007f34368717b0 llvm::sys::RunSignalHandlers() (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x97f7b0)
 #2 0x00007f3436872c4d llvm::sys::CleanupOnSignal(unsigned long) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x980c4d)
 #3 0x00007f34367c8cea (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8d6cea)
 #4 0x00007f34367c8c8b (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8d6c8b)
 #5 0x00007f343686e3fe (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x97c3fe)
 #6 0x00000000004125b2 (/usr/lib/llvm-10/bin/clang+0x4125b2)
 #7 0x00007f34367d29b4 llvm::report_fatal_error(llvm::Twine const&, bool) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8e09b4)
 #8 0x00007f34367d2a80 llvm::report_fatal_error(llvm::StringRef, bool) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8e0a80)
 #9 0x00007f34380794ed (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x21874ed)
#10 0x00007f3436b0e5e8 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0xc1c5e8)
#11 0x00007f3436978d76 llvm::FPPassManager::runOnFunction(llvm::Function&) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0xa86d76)
#12 0x00007f3436978ff3 llvm::FPPassManager::runOnModule(llvm::Module&) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0xa86ff3)
#13 0x00007f34369794a0 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0xa874a0)
#14 0x00007f343b96e433 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x13e8433)
#15 0x00007f343bbede1c (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x1667e1c)
#16 0x00007f343addbc13 clang::ParseAST(clang::Sema&, bool, bool) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x855c13)
#17 0x00007f343c251e58 clang::FrontendAction::Execute() (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x1ccbe58)
#18 0x00007f343c20a8a1 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x1c848a1)
#19 0x00007f343c2b5daf clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x1d2fdaf)
#20 0x000000000041229d cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-10/bin/clang+0x41229d)
#21 0x00000000004105b1 (/usr/lib/llvm-10/bin/clang+0x4105b1)
#22 0x00007f343bf5b8f2 (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19d58f2)
#23 0x00007f34367c8c67 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8d6c67)
#24 0x00007f343bf5ae2f clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19d4e2f)
#25 0x00007f343bf3352f clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19ad52f)
#26 0x00007f343bf336da clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19ad6da)
#27 0x00007f343bf4693c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19c093c)
#28 0x000000000041002f main (/usr/lib/llvm-10/bin/clang+0x41002f)
#29 0x00007f34359da0b3 __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:342:3
#30 0x000000000040d7ce _start (/usr/lib/llvm-10/bin/clang+0x40d7ce)
make: *** [Makefile:455: /media/byte/DataDisk/net/tools/testing/selftests/bpf/atomics.o] Error 1

Here is my compiler version :
1.    LLVM version 10.0.0
2.  clang version 10.0.0-4ubuntu1

**Comment by pchaigno** [comment]
Unrelated to Cilium.

**Comment by Cyrus008** [comment]
Thanks for the comment ...where is put   this issue please let me know
