### ISSUE TITLE
Add missing `bpftool map dump` in the bugtool

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#16008]
Not all maps are captured as part of the bugtool too, some are missing in this list https://github.com/cilium/cilium/blob/9fb332bec16f097c1cee88462649a39b4784f766/bugtool/cmd/configuration.go#L114

The list of maps can be retrieved from `ls -al /sys/fs/bpf/tc/globals/`, just be careful that list is not extensive and some maps are endpoint specific.

**Comment by h3llix** [comment]
I would like to work on this. @aanm Can you assign it to me please ?

**Comment by h3llix** [comment]
Is there any way to get exhaustive list of all the maps ? 

I can list the below mentioned maps under `/sys/fs/bpf/tc/globals/`
![bpf_map](https://user-images.githubusercontent.com/55123900/117493927-42c11180-af91-11eb-8c36-c3f1e650e2d5.png)

**Comment by pchaigno** [comment]
Yes, `bpftool map dump`...

**Comment by Mierdin** [comment]
Hey all - just poking around some issues and noticed this was open but seems like https://github.com/cilium/cilium/pull/16055 intended to close it but GH failed to link it. Probably because GH is expecting a space before the issue number.  Looks to me like this can be closed.

**Comment by pchaigno** [comment]
Indeed! Thanks for the report @Mierdin! :pray:

**Comment by h3llix** [comment]
Thanks @Mierdin ! Noted my mistake.
