### ISSUE TITLE
Use of Azure IPAM in non-default Azure clouds

### ISSUE THREAD

**Issue by joshmue** [cilium/cilium#16003]
**General Information**

- Cilium version 1.9.6
- AKS with Kubernetes 1.19.9

I attempted to deploy Cilium with Azure IPAM onto an AKS cluster in the `AzureChinaCloud` which differs from the public Azure cloud in some details.
Ref: https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud
Ref: https://docs.microsoft.com/en-us/azure/china/resources-developer-guide

When using Azure CNI and Cilium in chaining mode, these differences do not matter, but with Cilium Azure IPAM, they do.

When preparing, I found that the [Cilium Helm chart](https://github.com/cilium/cilium/blob/238d6b5ae12ddd8c02c8fb710276cfffd426ce36/install/kubernetes/cilium/values.yaml#L200) does not allow passing `azure.cloudName` yet, even though this is a [valid flag for the operator already](https://github.com/cilium/cilium/blob/4f27865e975cc095891b68df5f4a7bc0e26ecca5/operator/option/config.go#L413).

In the operator itself, the `cloudName` [is used](https://github.com/cilium/cilium/blob/38dd27af2f6c8246b8dc92ebf43ccbe8fab432ea/pkg/azure/api/api.go#L66) to configure the Azure client authorizer to acquire tokens from the correct AAD.
However, when [creating the resource clients](https://github.com/cilium/cilium/blob/38dd27af2f6c8246b8dc92ebf43ccbe8fab432ea/pkg/azure/api/api.go#L98) themselves, `NewSomethingClient(subscriptionId)` is called which defaults to the public Azure endpoints. Using `NewSomethingClientWithBaseURI(baseURI, subscriptionId)` should also allow calls to other Azure clouds. The respective endpoints can be loaded from [here](https://github.com/Azure/go-autorest/blob/c7f947c0610de1bc279f76e6d453353f95cd1bfa/autorest/azure/environments.go#L34).

If you want, I could take a look into generalizing the code.

**Comment by ungureanuvladvictor** [comment]
@joshmue -- I've put a draft PR to add support for custom clouds but I do not have any way to test it at the moment. Can you give it a spin?

**Comment by joshmue** [comment]
Sure! I'll provide feedback ASAP.

**Comment by joshmue** [comment]
The operator certainly does not log authentication errors anymore. Also, `.status.azure.interfaces` of the `CiliumNode` resources is populated.
Connecting to destinations outside of the cluster does not work yet, but I am not sure whether this is related to this issue. I will investigate further.
