### ISSUE TITLE
Go native interaction with the kernel

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1600]
Overall issue tracking the progress of moving away from using `iproute2` and shell scripts to interact with the kernel to:
 - Setup environment
 - Loading programs

**Comment by aalemayhu** [comment]
Related   #326 #999 #325

**Comment by borkmann** [comment]
Re llvm library: API is instable and keeps changing often, e.g. bcc is thinking to limit support to llvm 5+ and drop support for older versions.
