### ISSUE TITLE
Make backporting process easier on Mac OS users

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#16018]
Currently, we require users to spin up a dev VM if they're on Mac OS because our backporting scripts require Linux. Ideally, we should not have to dictate a user's dev environment to handle weekly duties. The scripts should be usable on all relevant platforms. The only incompatibility that I can see is the use of `sed` in the backporting scripts. One approach would be to write a Go script that replaces the functionality that we need from `sed` and use it as `go run ./contrib/backporting/blah-script.go`.

Another approach is to containerize all the scripts as well (https://github.com/cilium/cilium/pull/16016#discussion_r626394034).

**Comment by glibsm** [comment]
With some recent additions to the team some folks have already actively started chipping away at similar problems which is awesome to see.

The main issue with forcing a dev VM usage is the inability to use the primary development environment. Resolving conflicts (using stock vim), running git commands (no aliases), etc. 

The current middle ground is using a combination of running commands locally (to edit/merge files) and in VM (cherry-pick/tag editing/etc) which sort of works, but still results in quite sub-optimal experience.

--- 

Additional data point: I accidentally sent it to my local terminal and not the VM and this error popped up, so it may be more than just sed that's blocking.
```
❯ ./contrib/backporting/cherry-pick 69f10edf21ad5d012c300ae9d2d3b9ca78c1bf16
readlink: illegal option -- e
usage: readlink [-n] [file ...]
usage: dirname path
./contrib/backporting/cherry-pick: line 4: /common.sh: No such file or directory
```

**Comment by aditighag** [comment]
This has been on my to-do list for some time now. I'll take a stab at it. Not assigning the issue to myself until I've committed some cycles to it. @christarazi suggested a good option - https://github.com/cilium/cilium/pull/16016#discussion_r626193078.

**Comment by pchaigno** [comment]
> Resolving conflicts (using stock vim)

Isn't directory sharing enabled on macOS for the development VMs? That should allow you to edit files on the host with whatever editor you prefer, no?

> running git commands (no aliases), etc.

Maybe https://github.com/cilium/cilium/pull/14272 would be useful here? (Documented at https://docs.cilium.io/en/latest/contributing/development/dev_setup/#option-1-using-the-provided-vagrantfiles-recommended.)

**Comment by aditighag** [comment]
I've started looking into this. Parking it in my queue.
