### ISSUE TITLE
`cilium service list` contain rejected service that are not available in the bpf LB map

### ISSUE THREAD

**Issue by elfadel** [cilium/cilium#16028]
This issue is somewhat related to issue #15864.
When the bpf LB map is full, service cannot be added anymore. Try to eat will raise error indicating that the service cannot be added. However, the rejected service will appear in the list shown by `cilium service list` command.

**Comment by joestringer** [comment]
In principle I think this is probably fine and almost intended in a sense. If the underlying issue (ie map being full) is resolved, then it would be possible to re-synchronize the maps from the userspace understanding of the services without having to re-pull all state from k8s.

If there's a clear discrepancy between `cilium service list` and the underlying bpf maps, that's also useful because it helps to pinpoint that the problem was in implementing the changes into the datapath, and not a control plane problem.

What kind of behaviour would you expect Cilium to implement in this case?

**Comment by elfadel** [comment]
It depends. 

From my understanding, the `cilium service list` is intended only to show the correctly added and running services and should therefore be sync with commands like `cilium bpf lb list`. 

But if the fact that `cilium service list` contains services not running/added to the bpf maps, is intentionally implemented like that, so we should let it as it is and closed the issue.

**Comment by joestringer** [comment]
I think the real underlying problem in this case is the improper sizing of the service maps. Maybe there's a better way to propagate that error up to the user so that they can correctly configure Cilium to account for the service scale they are deploying.

**Comment by brb** [comment]
Re `cilium service list` vs `cilium bpf lb list`, maybe we should deprecate the former, as the latter is the source of truth. OTOH the latter can issue an extensive amount of syscalls.

**Comment by elfadel** [comment]
@joestringer 
> I think the real underlying problem in this case is the improper sizing of the service maps. Maybe there's a better way to propagate that error up to the user so that they can correctly configure Cilium to account for the service scale they are deploying.

It looks like that is what I implemented to fix issue #15864. No?

**Comment by joestringer** [comment]
> Re cilium service list vs cilium bpf lb list, maybe we should deprecate the former, as the latter is the source of truth. OTOH the latter can issue an extensive amount of syscalls.

I don't think this makes sense. These two tools are introspecting different layers of the stack, and this can assist debugging when they are inconsistent like reported in this issue - it allows us to divide the problem space.

**Comment by brb** [comment]
I think that having `cilium bpf lb list` + error log msgs should be enough to debug such inconsistencies. Also, there is `kubectl get svc` which output should be equivalent to `cilium service list`.

**Comment by aditighag** [comment]
I agree with @joestringer. 

`cilium service list` indicates control plane state, while `cilium bpf lb list` pertains to datapath state.

>Also, there is kubectl get svc which output should be equivalent to cilium service list.

Not for cases like LRP.

**Comment by aanm** [comment]
> I think that having `cilium bpf lb list` + error log msgs should be enough to debug such inconsistencies. Also, there is `kubectl get svc` which output should be equivalent to `cilium service list`.

Even if the connectivity with kube-apiserver is faulty?...

**Comment by joestringer** [comment]
The way I see this is similar to `cilium ip list`. For a long time, we didn't have ipcache visibility (admittedly at all on some kernels). Even when we got visibility into the datapath either via `cilium bpf ipcache list` or `cilium map ... cilium_ipcache`, we still had difficulty understanding the way that the Cilium internal daemon layer would resolve conflicts between inputs to then populate the datapath. This became easier with the introduction of a CLI to introspect that layer. Similarly here with services, there can be conflicts between the services and LRPs. 

I don't expect 95% of users to use this tool, but for the few who may need it, I think we should just set an expectation that it's telling you the truth about some internal state and it's up to you to interpret what that means and whether that indicates that Cilium is operating correctly or incorrectly.
