### ISSUE TITLE
Cilium managed POD between nodes network fails with flannel CNI integration

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#16032]
## Bug report
Following https://docs.cilium.io/en/v1.9/gettingstarted/flannel-integration/ to setup new k8s cluster with flannel and cilium, the cilium managed pod can ping flannel managed pod between master node and worker node, cilium managed pod cannot ping cilium managed pod between master node and worker node

kubectl  get po -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP           NODE               NOMINATED NODE   READINESS GATES
busybox-master-f97ff47c5-g9kg2   1/1     Running   1          80m   10.0.1.197   cilium-bigip       <none>           <none>
busybox-master-f97ff47c5-txl8l   1/1     Running   1          91m   10.244.0.4   cilium-bigip       <none>           <none>
busybox-worker-ccb4ffc6c-7s52n   1/1     Running   1          91m   10.244.1.2   cilium-fl-worker   <none>           <none>
busybox-worker-ccb4ffc6c-qqtfm   1/1     Running   1          80m   10.0.0.105   cilium-fl-worker   <none>           <none>

pod 10.0.0.105 can ping pod 10.244.0.4 (initial flannel managed pod)
pod 10.0.0.105 cannot ping pod 10.0.1.197 (cilium managed pod)

cilium monitor -vv shows the ICMP echo request triggered to-overlay, then that is it. no packet seen on the physical interface from tcpdump, no packet seen on the cilium_vxlan interface which shows as "DOWN"

11: cilium_vxlan: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ba:d0:d2:0a:92:82 brd ff:ff:ff:ff:ff:ff

cilium monitor -vv

CPU 03: MARK 0x0 FROM 2679 to-overlay: 98 bytes (98 captured), state new, interface cilium_vxlan, identity 16079->0, orig-ip 0.0.0.0
Ethernet	{Contents=[..14..] Payload=[..86..] SrcMAC=ca:0b:dd:cf:42:ea DstMAC=76:19:92:92:cf:3e EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=27725 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=47150 SrcIP=10.0.0.105 DstIP=10.0.1.197 Options=[] Padding=[]}
ICMPv4	{Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=21469 Id=4608 Seq=26}

root@cilium-fl-worker:/home/cilium# bpftool net show
xdp:

tc:
ens192(3) clsact/ingress bpf_netdev_ens192.o:[from-netdev] id 477
ens192(3) clsact/egress bpf_netdev_ens192.o:[to-netdev] id 483
cilium_net(9) clsact/ingress bpf_host_cilium_net.o:[to-host] id 471
cilium_host(10) clsact/ingress bpf_host.o:[to-host] id 447
cilium_host(10) clsact/egress bpf_host.o:[from-host] id 453
cilium_vxlan(11) clsact/ingress bpf_overlay.o:[from-overlay] id 429
cilium_vxlan(11) clsact/egress bpf_overlay.o:[to-overlay] id 434
lxc184a57bd9539(13) clsact/ingress bpf_lxc.o:[from-container] id 459
lxc1e9eb00bbada(15) clsact/ingress bpf_lxc.o:[from-container] id 461
lxc931b564fd4fe(17) clsact/ingress bpf_lxc.o:[from-container] id 489

flow_dissector:

**General Information**

- Cilium version (run `cilium version`)
Client: 1.9.6 38dd27a 2021-04-20T14:57:11-07:00 go version go1.15.11 linux/amd64

- Kernel version (run `uname -a`)
Linux cilium-fl-worker 5.8.1-050801-generic #202008111432 SMP Tue Aug 11 14:34:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, ...)

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)

busybox pod deployed to worker node

[busybox-worker.yaml.txt](https://github.com/cilium/cilium/files/6430543/busybox-worker.yaml.txt)

busybox bod deployed to master node
[busybox-master.yaml.txt](https://github.com/cilium/cilium/files/6430544/busybox-master.yaml.txt)

Cilium deployment templated from helm template

[cilium-fl.yaml.txt](https://github.com/cilium/cilium/files/6430545/cilium-fl.yaml.txt)

Flannel deployment yaml

[cilium-flannel.yaml.txt](https://github.com/cilium/cilium/files/6430546/cilium-flannel.yaml.txt)

- Generate and upload a system zip:
[cilium-sysdump-20210505-210620.zip](https://github.com/cilium/cilium/files/6430627/cilium-sysdump-20210505-210620.zip)

**How to reproduce the issue**

1, kubeadm to init k8s master

apiserver on interface ens160 and  ip 10.3.72.128
kubelet node ip on  interface ens192 and 10.169.72.128 (added --node-ip=10.169.72.128 to kubelet in /etc/default/kubelet)

kubeadm init --v=5 --apiserver-advertise-address=10.3.72.128 --pod-network-cidr=10.244.0.0/16

2 apply flannel ( see above attached, flannel specified --iface to ens192)

kubectl apply -f cilium-flannel.yaml

3 kubeadm to join worker node

kubeadm join 10.3.72.128:6443 --token.....

4, now both master and worker node runs flannel, label master and worker node to deploy one busybox on master node and one busybox on worker node, the flannel managed pod get ip address 10.244.x.x

kubectl label node cilium-bigip dedicated=master
kubectl label node cilium-fl-worker dedicated=worker

kubectl apply -f  busybox-master.yaml
kubectl apply -f busybox-worker.yaml

busybox-master-f97ff47c5-txl8l   1/1     Running   1          113m   10.244.0.4   cilium-bigip       <none>           <none>
busybox-worker-ccb4ffc6c-7s52n   1/1     Running   1          113m   10.244.1.2   cilium-fl-worker   <none>           <none>

5 now deploy cilium (templated from helm with --set flannel.enabled=true, also disabled health checking for less noise), and cilium agent runs fine on both nodes

kubectl apply -f cilium-fl.yaml

NAME           READY   STATUS    RESTARTS   AGE    IP              NODE               NOMINATED NODE   READINESS GATES
cilium-88dg6   1/1     Running   0          109m   10.169.72.128   cilium-bigip       <none>           <none>
cilium-rvnjj   1/1     Running   0          109m   10.169.72.129   cilium-fl-worker   <none>           <none>

6, manual edit busybox-master and busybox-worker deployment (deployed at step 4) to add replicas to 2 so both master and worker node get new busybox pod managed by cilium

kubectl edit deployment busybox-master or busybox-worker

spec:
  progressDeadlineSeconds: 600
  replicas: 2

new busybox pod created on both nodes and managed by cilium

busybox-master-f97ff47c5-g9kg2   1/1     Running   1          102m   10.0.1.197   cilium-bigip       <none>           <none>

busybox-worker-ccb4ffc6c-qqtfm   1/1     Running   1          102m   10.0.0.105   cilium-fl-worker   <none>           <none>

7 kubectl to login busybox-worker-ccb4ffc6c-qqtfm  pod 10.0.0.105 to ping pod 10.0.1.197, not network connectivity

**Comment by pchaigno** [comment]
Please note we are removing support for the direct Flannel integration in Cilium v1.10. You can instead run Flannel on top of Cilium with [the Genetic Veth Chaining guide](https://docs.cilium.io/en/v1.9/gettingstarted/cni-chaining-generic-veth/).

**Comment by vincentmli** [comment]
> the Genetic Veth Chaining guide

@pchaigno Thank you, after reading https://docs.cilium.io/en/v1.9/gettingstarted/cni-chaining-generic-veth/, I would like to try that in the existing lab that already has flannel and cilium running, but I am not clear what steps I should do in the Genetic Veth Chaining guide, it has:

1. Validate that the current CNI plugin is using veth
2. Create a CNI configuration to define your chaining configuration
3. Deploy Cilium with the portmap plugin enabled

I think I need to do 1, and 2. Do I need to do 3?

The guide is not very clear on what actual steps need to be performed for a Cilium newbie like me :), no real example shown

**Comment by vincentmli** [comment]
> > the Genetic Veth Chaining guide
> 
> @pchaigno Thank you, after reading https://docs.cilium.io/en/v1.9/gettingstarted/cni-chaining-generic-veth/, I would like to try that in the existing lab that already has flannel and cilium running, but I am not clear what steps I should do in the Genetic Veth Chaining guide, it has:
> 
> 1. Validate that the current CNI plugin is using veth
> 2. Create a CNI configuration to define your chaining configuration
> 3. Deploy Cilium with the portmap plugin enabled
> 
> I think I need to do 1, and 2. Do I need to do 3?
> 
I think I need to do 3, since the the cilium helm referenced the CNI chaining configmap in step 2

**Comment by vincentmli** [comment]
no need for this due to https://github.com/cilium/cilium/issues/16517
