### ISSUE TITLE
Pods are stuck in ContainerCreating state

### ISSUE THREAD

**Issue by ybialik** [cilium/cilium#16038]
## Bug report

**General Information**

- Cilium version 1.9.6
- EKS 1.18

We recently installed cilium version 1.9.6 using these flags with helm
helm install cilium cilium/cilium --version 1.9.6 \
  --namespace kube-system \
  --set egressMasqueradeInterfaces=eth0 \
  --set nodeinit.enabled=true  \
   --set hubble.enabled=true \
   --set hubble.listenAddress=":4244" \
   --set hubble.relay.enabled=true \
   --set hubble.ui.enabled=true --set prometheus.enabled=true \
  --set operator.prometheus.enabled=true --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http}"

we currently facing pods that sometimes upon creation are stuck on ContainerCreating state:
![image](https://user-images.githubusercontent.com/81084950/117310335-dad4d300-ae8b-11eb-98e7-925bcaf14a4e.png)

when describing the pod I am getting this error:
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "e8ab8ca00aaa917c95cf15d0a596f94ee408575a261e76bb1e16b8b1a57d8ee3" network for pod "****-service-1620308400-2kf2z": networkPlugin cni failed to set up pod "****-service-1620308400-2kf2z_production-services" network: Unable to create endpoint: Cilium API client timeout exceeded

I noticed that if I delete the cilium agent pods and let the recreate, the container is starting.

any ideas?

**Comment by pchaigno** [comment]
Could you please fill in the rest of the issue template?

**Comment by ybialik** [comment]
I will open a new issue with all the data
