### ISSUE TITLE
CI: RuntimePrivilegedUnitTests TestArpPingHandling failed, expected 'true' got 'false'

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#16040]
```
 node_linux_test.go:1049:
	     c.Assert(found, check.Equals, true)
	 ... obtained bool = false
	 ... expected bool = true
	 
START: node_linux_test.go:137: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
PASS: node_linux_test.go:137: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.044s

FAIL: node_linux_test.go:955: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
```

https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4618/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

[867e2c23_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/6435560/867e2c23_RuntimePrivilegedUnitTests_Run_Tests.zip)

**Comment by brb** [comment]
I think I need to find a better way than sleep 100ms to wait for async insertNeighbor() execution.

**Comment by nbusseneau** [comment]
This is happening on `master` as well:

- https://jenkins.cilium.io/job/cilium-master-runtime/1922/
- https://jenkins.cilium.io/job/cilium-master-runtime/1923/

Must be something merged very recently:
![image](https://user-images.githubusercontent.com/4659919/117341897-f697a380-aea2-11eb-90b2-27394821c1c0.png)

**Comment by jrajahalme** [comment]
Similar fail in https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/560/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

**Comment by brb** [comment]
We recently changed the neigh management. /cc @borkmann

**Comment by borkmann** [comment]
> We recently changed the neigh management. /cc @borkmann

@jrajahalme have you seen this only once? Maybe we can just bump the timeout a bit further.
