### ISSUE TITLE
v1.9: CI: K8sVerifier Runs the kernel verifier against Cilium's BPF datapath on 5.4

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#16050]
https://jenkins.cilium.io/view/Cilium-v1.9/job/cilium-v1.9-k8s-1.17-kernel-5.4/2/testReport/Suite-k8s-1/17/K8sVerifier_Runs_the_kernel_verifier_against_Cilium_s_BPF_datapath/

K8sVerifier is failing in v1.9 on the 5.4 CI job with the following error:
```
Log buffer too small to dump verifier log 16777215 bytes (1 tries)!
Error filling program arrays!
Unable to load program
command terminated with exit code 1
```
This error happens because, contrary to real program loads, in K8sVerifier we load programs with verbose enabled by default, even when there are no errors.

The test passed in the v1.9 backport PR that introduced it (cf. https://github.com/cilium/cilium/pull/15957), but started failing as soon as it was merged.

I reproduced locally and loaded programs with a patched iproute2 to avoid the log buffer error. Another BPF program fails to load with a different `EINVAL` error, before even hitting the verifier (could be because of how I tested).

Next step could be to build a custom Docker image for test-verifier instead of using cilium-builder. That way we could use a patched iproute2 version and avoid the log buffer error. We don't need cilium-builder in the test VMs anyway.

**Comment by jrajahalme** [comment]
This was hit in 1.9 backport PR (https://github.com/cilium/cilium/pull/16048), should we hold the backports because of this, or is this unrelated to this backport?

**Comment by tklauser** [comment]
Seen on https://github.com/cilium/cilium/pull/16642 with a slightly different error message:

```
16:09:39    	 BPF program is too large. Processed 1000001 insn
16:09:39    	 processed 1000001 insns (limit 1000000) max_states_per_insn 40 total_states 60448 peak_states 2529 mark_read 97
16:09:39    	 
16:09:39    	 Error filling program arrays!
16:09:39    	 Unable to load program
16:09:39    	 command terminated with exit code 1
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-5.4/48/

**Comment by jrajahalme** [comment]
Seen on https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-5.4/70/ with this in the CI console logs:
```
java.io.IOException: Cannot read more than 2Gib at a time
	at org.jenkinsci.plugins.workflow.log.FileLogStorage.stepLog(FileLogStorage.java:290)
	at org.jenkinsci.plugins.workflow.support.actions.LogStorageAction.getLogText(LogStorageAction.java:62)
	at org.jenkinsci.plugins.workflow.support.actions.LogStorageAction.writeLogTo(LogStorageAction.java:70)
...
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by brb** [comment]
I haven't seen any failure in https://jenkins.cilium.io/view/Cilium-v1.9/job/cilium-v1.9-k8s-1.17-kernel-5.4/, so closing. @pchaigno Please reopen if you see any.
