### ISSUE TITLE
Cilium Azure IPAM seems to require permissions at subscription level

### ISSUE THREAD

**Issue by joshmue** [cilium/cilium#16079]
As [documented](https://docs.cilium.io/en/v1.9/concepts/networking/ipam/azure/#required-privileges), cilium uses some "List All" calls when communicating with the Azure resource manager (differently than documented, these permissions seemingly are not used on [VMSS's](https://github.com/cilium/cilium/blob/38dd27af2f6c8246b8dc92ebf43ccbe8fab432ea/pkg/azure/api/api.go#L183), but on [VNET's](https://github.com/cilium/cilium/blob/38dd27af2f6c8246b8dc92ebf43ccbe8fab432ea/pkg/azure/api/api.go#L310)).

I think that it is possible to eliminate such subscription-level queries, in order to grant only the least amount of permissions possible.
Instead of iterating through all existing VNET's in the subscription, the VNET/subnet (or maybe more than one) could be configured explicitly, I imagine.

The issues #12593 and #12297 do have some overlap with this one, but they are both closed for a few months already and were not conclusive for me.

Maybe this is some kind of design tradeoff related to factors I did not take into account? If not, I'd be happy to contribute to tackling this issue.

**Comment by AnishShah** [comment]
Interesting! I deployed Cilium in my Azure cluster with ResourceGroup-level permissions on the VNET and it works properly. Not sure why

**Comment by christarazi** [comment]
Good find @joshmue. Feel free to take this issue up and assign yourself if you're interested. Reach out to us if you require assistance either here or preferably on the #development channel.

**Comment by ungureanuvladvictor** [comment]
@joshmue -- as @AnishShah mentioned you can create a custom RBAC role for example `cilium-operator` with the the following content (the current scope is at the subscription but you can also just create this role at the resource group level):
```json
{
    "id": "/subscriptions/REDACTED/providers/Microsoft.Authorization/roleDefinitions/REDACTED",
    "properties": {
        "roleName": "cilium-operator",
        "description": "",
        "assignableScopes": [
            "/subscriptions/REDACTED"
        ],
        "permissions": [
            {
                "actions": [
                    "Microsoft.Network/networkInterfaces/read",
                    "Microsoft.Network/networkInterfaces/write",
                    "Microsoft.Network/networkInterfaces/delete",
                    "Microsoft.Network/virtualNetworks/read",
                    "Microsoft.Compute/virtualMachineScaleSets/read",
                    "Microsoft.Compute/virtualMachineScaleSets/networkInterfaces/read",
                    "Microsoft.Compute/virtualMachineScaleSets/publicIPAddresses/read",
                    "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/read",
                    "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/networkInterfaces/read",
                    "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/networkInterfaces/ipConfigurations/read",
                    "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/networkInterfaces/ipConfigurations/publicIPAddresses/read",
                    "Microsoft.Compute/virtualMachines/read",
                    "Microsoft.Compute/virtualMachines/instanceView/read",
                    "Microsoft.Network/virtualNetworks/subnets/read",
                    "Microsoft.Network/virtualNetworks/subnets/virtualMachines/read",
                    "Microsoft.Network/virtualNetworks/virtualMachines/read",
                    "Microsoft.Network/virtualNetworks/customViews/read"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
    }
}
```

Once you have the role you can go to the individual resource groups and do a role assignment of the `cilium-operator` role on the RG resource. In my case listing the role assignments of the `cilium-operator`:
```json
[
  {
    "canDelegate": null,
    "condition": null,
    "conditionVersion": null,
    "description": null,
    "id": "/subscriptions/REDACTED/resourceGroups/cilium/providers/Microsoft.Authorization/roleAssignments/REDACTED",
    "name": "REDACTED",
    "principalId": "REDACTED",
    "principalName": "REDACTED",
    "principalType": "ServicePrincipal",
    "resourceGroup": "cilium",
    "roleDefinitionId": "/subscriptions/REDACTED/providers/Microsoft.Authorization/roleDefinitions/REDACTED",
    "roleDefinitionName": "cilium-operator",
    "scope": "/subscriptions/REDACTED/resourceGroups/cilium",
    "type": "Microsoft.Authorization/roleAssignments"
  }
]
```

In the above case the SP is a user assigned identity for the kubelet (but it can be any SP).

@joshmue do you mind giving this setup a try and let me know if it works?

**Comment by joshmue** [comment]
Thank you all for your feedback so far!

> @joshmue do you mind giving this setup a try and let me know if it works?

@ungureanuvladvictor Indeed, this seems to work, thanks!

I was not aware of the behaviour of Azure that doing a "list all" with...
- a principal having no permissions in a subscription results in a 403
- a principal having some permissions on resources within the subscription results in a 200 with partial/incomplete results
- a principal having full access to the subscription results in a 200 with complete results.

When starting from scratch, the error message `The client 'REDACTED' with object id 'REDACTED' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/read' over scope '/subscriptions/REDACTED' or the scope is invalid. If access was recently granted, please refresh your credentials.` lead me to think that the permissions really needed to be assigned on subscription scope.

Still, I imagine explicitly configuring VNET's/subnets could be more intuitive or easier to debug? If I understand it correctly, Cilium right now syncs all VNET's in a subscription it has access to: If RBAC is not airtight, it may unintentionally sync VNET's from completely other contexts which may not be critical, but maybe confusing. Would you tend to agree?

> Good find @joshmue. Feel free to take this issue up and assign yourself if you're interested. Reach out to us if you require assistance either here or preferably on the #development channel.

Thanks for the offer!

**Comment by ungureanuvladvictor** [comment]
@joshmue -- re: Azure behavior I could not find that documented anywhere but surprised me as well when I started working with Azure Cloud and my findings are in line with what you described here as well.

The syncing of vnets + subnets you are right that it slurps up everything it can but I think the detail is a bit hidden in the behavior of the code: we sync those so we have that information available when we need to take an action on a VM which can be part of a VMSS or standalone. There is no write operation outside that loop to those vnet or subnet resources.

IMO I think we are overdue a bit an overhaul of the documentation related to the Azure IPAM which should include:
- the ways it is possible to have credentials for the operator (SP, managed identity and user assigned identity)
- custom role creation + assigning the role on the SP at the right scope
- listing the individual API perms that the custom role needs

I suspect if we had docs on the above then users would understand better how to configure this running into Azure.

**Comment by christarazi** [comment]
> IMO I think we are overdue a bit an overhaul of the documentation related to the Azure IPAM which should include:
> 
>     the ways it is possible to have credentials for the operator (SP, managed identity and user assigned identity)
>     custom role creation + assigning the role on the SP at the right scope
>     listing the individual API perms that the custom role needs
> 
> I suspect if we had docs on the above then users would understand better how to configure this running into Azure.

Hmm, maybe it makes sense to file an issue with this, if this issue isn't already the best place. I think this is good feedback and we should definitely do it.

**Comment by ungureanuvladvictor** [comment]
@christarazi / @joshmue I collected my thoughts into https://github.com/cilium/cilium/issues/16164. I'm inclined to close this and we should move the conv there given it has more details, wdyt?

**Comment by joshmue** [comment]
> I collected my thoughts into #16164. I'm inclined to close this and we should move the conv there given it has more details, wdyt?

Fine by me! Also I'll edit this issue's title, as it is actually not really accurate right now.

**Comment by christarazi** [comment]
Sounds good, thanks for collecting it into one issue. 

Superseded by https://github.com/cilium/cilium/issues/16164
