### ISSUE TITLE
The return for ctx_load_bytes() isn't being checked

### ISSUE THREAD

**Issue by trvll** [cilium/cilium#16076]
In the datapath, the function ipv6_dec_hoplimit() makes a call to ctx_load_bytes() without checking for return errors. This will let this function code make a evaluation of an uninitialized variable (__u8 hl) when ctx_load_bytes() returned a error. In this case the eBPF compiler will generate a code that won't be accepted by Linux kernel verifier, throwing a "invalid size of register spill" error in the /var/log/syslog.

https://github.com/cilium/cilium/blob/e9e4c46a5b6427d9d753852556c567a18d0490df/bpf/lib/ipv6.h#L151

Please, add error checks when calling ctx_load_bytes().

**Comment by trvll** [comment]
Hello @pchaigno, Could you assign it to me, pls?

**Comment by pchaigno** [comment]
No, I mean the compiler would not generated bytecode that results in `invalid size of register spill`. Uninitialized variable might happen but not `invalid size of register spill`.

> compiler should complain about possible usage of an uninitialized variable

I think it is initialized by the helper from compiler's point of view.

Anyway, the C code is clearly incorrect and we should fix it :slightly_smiling_face:
