### ISSUE TITLE
CI: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#16075]
## CI failure
Output from failure:
```
17:05:08  	 
17:05:08  	 START: node_linux_test.go:955: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
17:05:08  	 START: node_linux_test.go:116: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
17:05:08  	 PASS: node_linux_test.go:116: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
17:05:08  	 
17:05:08  	 node_linux_test.go:1161:
17:05:08  	     c.Assert(neighHwAddr(ip1.String()), check.Equals, mac.String())
17:05:08  	 ... obtained string = "f6:27:bb:80:88:10"
17:05:08  	 ... expected string = "4a:4c:8c:84:d1:20"
17:05:08  	 
```

Link to CI build: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4628/execution/node/99/log/?consoleFull

Link to PR where this happened: https://github.com/cilium/cilium/pull/16041

**Comment by aanm** [comment]
cc @brb

**Comment by tklauser** [comment]
Seen again on #16175 (https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4742/) with ~latest master (#16072 seems to be included)

cc @brb

**Comment by gandro** [comment]
Also seeing this on v1.8 backports which also has #16072 applied
