### ISSUE TITLE
Silence LLVM warning: 'probe' is not a recognized processor for this target (ignoring processor)

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#1609]
During the build of the BPF code, LLVM repeatedly prints this extraneous warning:
> 'probe' is not a recognized processor for this target (ignoring processor)

This seems to indicate that target probing doesn't work,s however we are specifying this we could probably remove it to make the build output more useful.

**Comment by borkmann** [comment]
This is basically to probe the kernel to use recently added BPF insns for newer LLVM versions (see ffa74b1f733dfac71a33013). The warning itself is harmless, and LLVM will just ignore it when it doesn't support the flag. There's unfortunately no option from LLVM to turn off the warning itself. Redirecting the output to /dev/null might omit other compiler output we don't want to have omitted. If so, we could add something like this (https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/tree/tools/testing/selftests/bpf/Makefile#n40), which is kind of ugly, but if we really want to.

**Comment by joestringer** [comment]
Hmm. Completely losing the output sounds not ideal. I guess the easiest solutions are either "| grep -v ..." or just dropping this.

**Comment by borkmann** [comment]
Yeah, so we could do as in the Makefile which is `PROBE := $(shell llc -march=bpf -mcpu=probe -filetype=null /dev/null 2>&1)`. What this tries is to compile an empty unit, and then based on the outcome we could either set `probe` or `generic`, it would solve the silencing problem, although still a bit fragile in case LLVM has some other output for some reason and we switch to a suboptimal mcpu, so I don't like it too much; we could do regex though.

**Comment by joestringer** [comment]
Developers upgrading clang to 5.0 or later should no longer observe this issue. Closing.
