### ISSUE TITLE
Bandwidth Manager: Ingress restriction 

### ISSUE THREAD

**Issue by ppancake** [cilium/cilium#16106]
## General Information

Cilium version:1.9.6
Kernel version :5.4.54
Kubectl version :v1.21.0

## Phenomenon
According to the documentation [Bandwidth Manager (beta)](https://docs.cilium.io/en/v1.9/gettingstarted/bandwidth-manager/#bandwidth-manager-beta), I tested the Bandwidth Manager feature:

First, the **egress-bandwidth** feature is effective:

tcp client send packets -> tcp server receive packets，pod2 is tcp server and set egress-bandwidth: 800Kbit.

The result shows that the pod2's egress is limited, tx = 97.62 kB/s ≈ 800Kbit

| client -> server |pod2 sar -n DEV results |node2 sar -n DEV results |
|---------|-----|------|
| pod1->pod2 |FACE   rxpck/s   txpck/s    rxkB/s    txkB/s  <br>lo     0.00   0.00  0.00  0.00    <br>eth0   1997.57  1514.55  13817.52    `97.62` | IFACE                   rxpck/s       txpck/s       rxkB/s       txkB/s <br>lxc35ffbd0a25aa   1512.51      2012.15     `97.49`   13929.25    <br>eth0    10122.23   1525.83     14946.91    174.01 |

However, for **pod ingress bandwidth** , according to the documentation [Bandwidth Manager (beta)](https://docs.cilium.io/en/v1.9/gettingstarted/bandwidth-manager/#bandwidth-manager-beta), I try to use `ifb` device to limit.

pod3's peer veth set ingress redirected.
```
  tc filter add dev lxc35942519b775 ingress protocol ip prio 0 u32 match u32 0 0 flowid ffff: action mirred egress redirect dev ifb0
  tc qdisc add dev ifb0 root tbf rate 800kbit latency 20ms burst 1540
```
**_the result shows that pod's egress is limited, not ingress._**: tx = 97.61 kB/s

| client -> server |pod3 sar -n DEV results |node3 sar -n DEV results |
|---------|-----|------|
| pod1->pod3 |FACE   rxpck/s   txpck/s    rxkB/s    txkB/s  <br>lo     0.00   0.00  0.00  0.00    <br>eth0     2092.07   1514.40    14470.52     `97.61` | IFACE                    rxpck/s       txpck/s      rxkB/s    txkB/s<br>eth0                       10620.18   1535.03    15674.27        186.67    <br>ifb0         1516.12    1516.12    ` 97.72`     `97.72`   <br>lxc35942519b775   1514.09    2124.75    `97.59`  14607.22 |

And if I only use tc egress to limit pod4 peer veth's egress, **_the result shows that pod4's ingress is really limited._**: rx = 93.19 kB/s

```tc qdisc add dev lxc5a010d4ceb27 root tbf rate 800kbit latency 20ms burst 1540```
| client -> server |pod4 sar -n DEV results |node4 sar -n DEV results |
|---------|-----|------|
| pod1->pod4 |FACE   rxpck/s   txpck/s    rxkB/s    txkB/s  <br>lo     0.00   0.00  0.00  0.00    <br>eth0   eth0     65.18     36.89     `93.19`      2.46 |IFACE rxpck/s  txpck/s rxkB/s   txkB/s <br>lxc5a010d4ceb27     37.23     65.24      2.48     `93.27`     <br>eth0         79.90     48.84    101.38      6.65      0.00  |

## Question
1. Using ifb device to limit ingress functionality is valid  for host, but failed on pod. So Maybe the documentation [Bandwidth Manager (beta)](https://docs.cilium.io/en/v1.9/gettingstarted/bandwidth-manager/#bandwidth-manager-beta) suggestion is wrong?
2. It's look like  limiting pod's peer veth egress is effective. Why doesn't the community do this？

Thanks

**Comment by pchaigno** [comment]
What makes you think this is a Cilium issue?

**Comment by aanm** [comment]
>Using ifb device to limit ingress functionality is valid for host, but failed on pod. So Maybe the documentation Bandwidth Manager (beta) suggestion is wrong?

@ppancake accordingly the [Bandwidth Manager (beta)](https://docs.cilium.io/en/v1.9/gettingstarted/bandwidth-manager/#bandwidth-manager-beta) documentation it's clear that ingress is not supported: _The kubernetes.io/ingress-bandwidth annotation is not supported and also not recommended to use._

>2. It's look like limiting pod's peer veth egress is effective. Why doesn't the community do this？

Can you clarfiy this question better? Bandwidth Manager does support egress limit.

**Comment by ppancake** [comment]
Sorry, my question may not clear.

>  accordingly the Bandwidth Manager (beta) documentation it's clear that ingress is not supported: The kubernetes.io/ingress-bandwidth annotation is not supported and also not recommended to use.

@aanm. Yes, cilium dose not support ingress currently.  But now I need  this functionality , the documentation mentions the ifb method. So I test the  IFB device method, and Add the IFB redirect manually.
However, the result show that it not work, pod's egress is limited :`tx = 97.61 kB/s`.  So i'm confused.

> Can you clarfiy this question better? Bandwidth Manager does support egress limit.

I found that ifb netdevice didn't work, so I test directly limit veth0's egress according to tc,  so packets transmit to veth1 will limit.

And the result show tha pod's ingress is limited: `rx = 93.19 kB/s`. I'm not sure the whole process is correct...

        ┌───────────────────┐
        │         pod       │
        │   ┌────────────┐  │
        │   │            │  │
        │   │    veth1   │  │
        │   └───┬────▲───┘  │
        │       │    │      │
        └───────┼────┼──────┘
         ingress│    │egress
            ┌───▼────┴───┐
            │            │
            │   veth0    │
            └────────────┘

**Comment by ppancake** [comment]
> What makes you think this is a Cilium issue?

Sorry, it is not cilium's issue. But I only want to discuss how to implement bandwidth ingress function.

**Comment by aanm** [comment]
> > What makes you think this is a Cilium issue?
> 
> Sorry, it is not cilium's issue. But I only want to discuss how to implement bandwidth ingress function.

maybe @borkmann can give you some pointers on how to implement this

**Comment by borkmann** [comment]
Dup of https://github.com/cilium/cilium/issues/15636. Some pointers can be found [here](https://linuxplumbersconf.org/event/7/contributions/677/attachments/570/1006/LPC_2020__Fair-share_Rate_Limiting_in_BPF.pdf).

**Comment by pchaigno** [comment]
Closing in favor of https://github.com/cilium/cilium/issues/15636.
