### ISSUE TITLE
If I use quick-install.yaml other than helm to install cilium ? How can set kubeProxyReplacement=strict ?

### ISSUE THREAD

**Issue by h2cw2l** [cilium/cilium#16117]
Hello,

When I set want kubeProxyReplacement, must I use helm to install cilium ?
When I use "kubectl create -f quick-install.yaml" , how can I set it ?
Any reply will be appreciated.
![图片](https://user-images.githubusercontent.com/58133919/117964120-d1e47580-b353-11eb-9263-650ef0293eb3.png)

**Comment by pchaigno** [comment]
You can edit the `quick-install.yaml` file to specify `kube-proxy-replacement: strict`.

**Comment by gandro** [comment]
Alternatively, you may also use `helm template` to generate the YAML and apply it manually. For example:

```console
$ helm template cilium cilium/cilium --version 1.9.6 \
    --namespace kube-system \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost=REPLACE_WITH_API_SERVER_IP \
    --set k8sServicePort=REPLACE_WITH_API_SERVER_PORT > custom-install.yaml
$ kubectl apply -f custom-install.yaml
```

**Comment by h2cw2l** [comment]
@gandro @pchaigno 

Thanks.
