### ISSUE TITLE
CI: Github warning about `persist-credentials`

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#16128]
In this Github workflow run:

https://github.com/cilium/cilium/runs/2568647717?check_suite_focus=true

I see the following warning (which doesn't break the build, but it's a github annotation which suggests something is wrong):

```
 Validate & Build HTML
Unexpected input(s) 'persist-credentials', valid inputs are ['repository', 'ref', 'token', 'clean', 'submodules', 'lfs', 'fetch-depth', 'path']
```

@pchaigno is this a regression from #16052 ?

**Comment by pchaigno** [comment]
Yep, probably due to the use of checkout v1: https://github.com/cilium/cilium/blob/b553845559a55dd0f56ca1174181c1209d28c918/.github/workflows/docs.yaml#L14-L16.
