### ISSUE TITLE
Install on EKS 1.19 not working

### ISSUE THREAD

**Issue by sylr** [cilium/cilium#16120]
## Bug report

I've followed the install doc for EKS but the cilium daemonset pods refuse to become ready with the following error:

```
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-10-24-38-159.eu-west-1.compute.internal required=2 subsys=ipam
```

Steps:

- I removed the aws-node daemonset
- Then installed cilium with the helm command:
```
helm install cilium cilium/cilium --version 1.9.6 \
  --namespace kube-system \
  --set eni=true \
  --set ipam.mode=eni \
  --set egressMasqueradeInterfaces=eth0 \
  --set tunnel=disabled \
  --set nodeinit.enabled=true
```

**General Information**

- Cilium version: 1.19.6
- Kernel version : Linux ip-10-24-15-69.eu-west-1.compute.internal 5.4.110-54.182.amzn2.x86_64 #1 SMP Fri Apr 9 17:56:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes: 1.19.6

**Comment by christarazi** [comment]
Adding need-more-info as a sysdump is required to debug further. We know that EKS works, so there must be something specific with this environment that's causing issues.
