### ISSUE TITLE
ipam/aws/eni: attempting to overallocate IP and ENI

### ISSUE THREAD

**Issue by mvisonneau** [cilium/cilium#16124]
## Bug report

After upgrading to `v1.10.0-rc1`, I noticed the following in the logs of the `cilium-operator-aws`:

```json
{
   "error":"operation error EC2: AssignPrivateIpAddresses, https response error StatusCode: 400, RequestID: f6257018-ac17-4e4c-8278-bb6d7349bd9d, api error PrivateIpAddressLimitExceeded: Number of private addresses will exceed limit.",
   "instanceID":"i-04d6bf44302171424",
   "ipsToAllocate":2,
   "level":"warning",
   "msg":"Unable to assign additional IPs to interface, will create new interface",
   "name":"ip-10-16-35-166.eu-west-1.compute.internal",
   "selectedInterface":"eni-062290b11cfc63e75",
   "subsys":"ipam"
}
{
   "addresses":4,
   "instanceID":"i-04d6bf44302171424",
   "level":"info",
   "msg":"No more IPs available, creating new ENI",
   "name":"ip-10-16-35-166.eu-west-1.compute.internal",
   "securityGroupIDs":[
      "sg-015d0f34fbe13438e"
   ],
   "subnetID":"subnet-0c284330b997f75c2",
   "subsys":"ipam"
}
{
   "addresses":4,
   "eniID":"eni-009191aca186b3cef",
   "instanceID":"i-04d6bf44302171424",
   "level":"info",
   "msg":"Created new ENI",
   "name":"ip-10-16-35-166.eu-west-1.compute.internal",
   "securityGroupIDs":[
      "sg-015d0f34fbe13438e"
   ],
   "subnetID":"subnet-0c284330b997f75c2",
   "subsys":"ipam"
}
{
   "instanceID":"i-04d6bf44302171424",
   "level":"warning",
   "msg":"Unable to create interface on instance: unable to attach ENI at index 3: operation error EC2: AttachNetworkInterface, https response error StatusCode: 400, RequestID: 78315ba4-e7db-43a9-88d4-774e9f085646, api error AttachmentLimitExceeded: Interface count 4 exceeds the limit for t3a.medium",
   "name":"ip-10-16-35-166.eu-west-1.compute.internal",
   "subsys":"ipam"
}
```

At first sight it seems to attempt overallocating both IP addresses on an ENI and ENI attachment on an instances.

**General Information**

- Cilium version: `v1.10.0-rc1`
- Kernel version: `5.4.0`
- Orchestration system version in use: `EKS 1.19.6`

**How to reproduce the issue**

Use `v1.10.0-rc1` with AWS ENI IPAM enabled

**Comment by mvisonneau** [comment]
After some digging, it seems related to the pointer de-referencing in lieu of `DeepCopy()` done through: https://github.com/cilium/cilium/commit/623dcd3581b6a48994d5e1e28b720b1c0525b6df

I was able to test it out locally by reverting the DeepCopy() and it sorted the issue out, not sure this is something we would like to have back though ([according to this comment](https://github.com/cilium/cilium/pull/13865/files#r519715835)) :thinking: 

cc @aanm & @christarazi

**Comment by gandro** [comment]
I believe this is a duplicate of #15877 which was fixed after rc1 was cut.

**Comment by mvisonneau** [comment]
absolutely, my bad :facepalm: it is also likely that I have performed my manual tests from master which already included the fix.. closing this! many thanks :bow:
