### ISSUE TITLE
Cilium documentation: scrape interval for Hubble metrics for Cilium v1.9 Hubble Metrics dashboard

### ISSUE THREAD

**Issue by christian-2** [cilium/cilium#16148]
## Bug report

**General Information**

- Cilium version 1.9 (documentation)

**How to reproduce the issue**

I have installed a job into Prometheus in order to pick up Hubble metrics by following an example from the [documentation](https://docs.cilium.io/en/v1.9/operations/metrics/) (`https://docs.cilium.io/en/v1.9/operations/metrics/`). The example (`scrape_config` for `job_name: 'kubernetes-endpoints'`) does not specify a `scrape_interval`, so Prometheus' default of `1m` applies. 

I am also using the [Cilium v1.9 Hubble Metrics](https://grafana.com/grafana/dashboards/13539) dashboard for visualization in Grafana. Its metric e.g. for the panel "Flows processed Per Node" specifies a time duration also of `1m`: `rate(hubble_flows_processed_total[1m]`. 

With this configuration, the panel shows “no data”. The situation has also been mentioned in prometheus/prometheus#1428: “a scrape interval of 1m ... will often not have two data points to work with”. 

The issue goes away when reducing the scrape interval from `1m` (default) e.g. to `10s`. The example in the documentation should perhaps include a specific and suitable `scrape_interval` instead of relying on the Prometheus default.

**Comment by christian-2** [comment]
I've by now located the documentation in the Git repo and could submit a PR, if that's welcome.

**Comment by aanm** [comment]
@christian-2 please do
