### ISSUE TITLE
http proxy: don't include request headers in response log record

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#16195]
right now `LogRecordHTTP` contains both request and response headers in the `Headers` field for HTTP responses. this can get confusing because you get duplicate headers like multiple `Content-Length` headers. Hubble uses `X-Request-Id` headers to correlate requests and response so we need that information in HTTP responses, but all the other request headers can be removed. so i'm thinking something like:

- Add `RequestID` field in `LogRecordHTTP`.
- Remove request headers from HTTP responses.

cc @jrajahalme

**Comment by jrajahalme** [comment]
@michi-covalent Should the `x-request-id` still be present also in the `headers` of the request access log, or do we only include it in the new request id field?

**Comment by michi-covalent** [comment]
> @michi-covalent Should the `x-request-id` still be present also in the `headers` of the request access log, or do we only include it in the new request id field?

hmm ok after sleeping on this, i see 2 options here:

a. remove `x-request-id` from the request `headers` field and include it in the new request id field.
b. include `x-request-id` header in both request and response access log, removing all the other request headers from response access log.

i'm leaning slightly towards the option b. this way hubble will continue to work without any modification: https://github.com/cilium/cilium/blob/4a831f48ea9c0d333147d844c10b3424b1350982/pkg/hubble/parser/seven/parser.go#L157.

**Comment by jrajahalme** [comment]
OK, will implement option b.

**Comment by jrajahalme** [comment]
`cilium/proxy` PR up: https://github.com/cilium/proxy/pull/48

**Comment by jrajahalme** [comment]
PR up: https://github.com/cilium/cilium/pull/16211

@michi-covalent How far back we need to backport this? So far I only marked 1.10.

**Comment by michi-covalent** [comment]
@jrajahalme let's just do 1.10 👍
