### ISSUE TITLE
HostPort doesn't work for initContainers

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#16191]
Trough code auditing it's obvious that we don't handle initContainer hostports:

https://github.com/cilium/cilium/blob/465cac1b740bdd370326607cdcedef1059df9e12/pkg/k8s/watchers/pod.go#L473-L475

cc @borkmann

**Comment by aanm** [comment]
@pchaigno they do share the same network namespace so on one hand I don't see it being a problem. However, we could be smarter and only populate the HostPorts services only when the respective container is up and running, which we can derive by checking the container status from the pod status.

**Comment by aanm** [comment]
> > However, we could be smarter and only populate the HostPorts services only when the respective container is up and running, which we can derive by checking the container status from the pod status.
> 
> The trick if we do that is that we may have a few seconds between when the pod is Ready and when it's reachable on the HostPort. I'm not sure that would be expected either from a user's point of view. /cc @borkmann

@pchaigno IMO it should be up to the user to setup the appropriated [readiness probes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes) for the initcontainers which would be signalized by kubelet once the hostport was ready to receive connections.

**Comment by pchaigno** [comment]
> The pod remains indefinitely in state `Init:0/1`, exposing the container's port 80 on port 8888 of the host. However, since we configure the datapath service mapping for the container and the init container at the same time, the service ends up being also exposed on port 8080.

I've filled https://github.com/cilium/cilium/issues/18850 for this bug.
