### ISSUE TITLE
Node didn't match pod anti-affinity rules.

### ISSUE THREAD

**Issue by designanderror** [cilium/cilium#16202]
## Bug report

**General Information**

- Cilium version : ```cilium-cli: v0.6.0-dev compiled with go1.16.3 on linux/amd64```
- Kernel version: ``` Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux ```
- Orchestration system version in use : 
``` Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}```
``` Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"} ```

I am checking the cilium connectivity tests. 6 pods aren't running.

![cilium-test](https://user-images.githubusercontent.com/61535265/118643531-4eff6700-b7fa-11eb-98bd-9355652c778b.png)

When I run  ``` kubectl describe pods <pod-name> ```, I get the below error for all the 6 pods. 

```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  21s (x11 over 12m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't match pod anti-affinity rules.
```

**Comment by aanm** [comment]
Hello, that's expected as it's likely that you have a single node running? connectivity check pods for multi-node requires a cluster with more than one node.

**Comment by designanderror** [comment]
@aanm Yes, I have installed it in Minikube.

**Comment by aanm** [comment]
ok, that's expected.

**Comment by pchaigno** [comment]
Closing as it's expected for cross-node connectivity tests to fail in a single node cluster.
