### ISSUE TITLE
Reduce Cilium-Operator QPS by default in Azure IPAM Mode

### ISSUE THREAD

**Issue by itsthatriver** [cilium/cilium#16206]
## Proposal / RFE

**Is your feature request related to a problem?**

In Azure there are very low rate limits at the Subscription level for accessing the VMSS API (described [here](https://docs.microsoft.com/en-us/azure/aks/troubleshooting#im-receiving-429---too-many-requests-errors)). When I followed the [AKS quickstart](https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-aks/) in Azure IPAM mode I ran into issues very quickly because the cilium-operators in my cluster were saturating the request capacity of my entire shared dev subscription (the subscription has 19 aks clusters with autoscaling, and the cilium-operator was responsible for about 90% of the request volume). I'm not sure whether this caused issues for autoscaling behavior, but I did observe it actually break Terraform as I tried to make changes to the environment (the Azure RM Terraform provider crashes if it hits a 429).

It looks like there are [changes upstream](https://github.com/cilium/cilium/pull/15760/files) to handle 429's natively in Cilium, but because the high volume of requests has side-effects on other operations in the same Subscription I think that Cilium-Operator should reduce the request volume to the VMSS backend by default (in Azure IPAM mode) to avoid triggering those sorts of failures. I don't think backing off is sufficient given the fragility of other clients in the Azure ecosystem.

**Describe the solution you'd like**

Currently my system seems to be healthy while running with these limiters (and I'm not seeing any terraform failures):
```
  limit-ipam-api-burst: "1"
  limit-ipam-api-qps: "0.5"
```

In the near term I think these are a good default starting point, but if there's any way for cilium-operator to reduce the overall number of required requests that would be helpful.

For my particular use case, we install AKS clusters in customer resource groups, so we're very sensitive to any issues that could cause the systems we're managing to have side effects on any customer processes outside of the resource group we're installed in.

**Comment by thejosephstevens** [comment]
Adding some more details here, with this current config I am still seeing some throttling, but massively less than I saw with the default config
![image](https://user-images.githubusercontent.com/5632093/118712197-58c2a380-b7d5-11eb-82a0-c5d10e7fffb2.png)

I'm not sure if there's another way to view this graph, but you can get it by starting the AKS support ticket flow
![image](https://user-images.githubusercontent.com/5632093/118712429-a0e1c600-b7d5-11eb-9ee3-e9356ce9d578.png)

Enter a summary on the generated ticket page, select "cluster management", and "My cluster is in a failed or unresponsive state" (I don't think these choices matter), click on "Next (Solutions)", and then find "Azure Resource Request Throttling" in the list. It may or may not be highlighted depending on if there is throttling occurring.
![image](https://user-images.githubusercontent.com/5632093/118712713-f5854100-b7d5-11eb-8adc-ab23e679603f.png)

When I navigated here after setting up a cluster with default settings, I saw about 6 different user agents were getting throttled, but cilium-operator was producing about 10x the requests of any other user agent. This was from a pretty basic cluster with three nodes and ~100-150 pods
