### ISSUE TITLE
Support building from a macOS host

### ISSUE THREAD

**Issue by jayunit100** [cilium/cilium#16208]
This might be a n00b bug but...  `make` fails on some Golang dependencies/packages.  

Can we make the `make` target compile the golang artifacts OOTB, or  Do we *need* vagrant to build cillium from source ? https://docs.cilium.io/en/stable/contributing/development/dev_setup/#requirements ... 

... for me OOTB, make fails, but i figured the go parts would probably work locally...

```
/Users/jayunit100/SOURCE/cilium/pkg/wireguard/agent/agent.go:157:16: Rule not declared by package route
/Users/jayunit100/SOURCE/cilium/pkg/wireguard/agent/agent.go:168:19: ReplaceRule not declared by package route
/Users/jayunit100/SOURCE/cilium/pkg/wireguard/agent/agent.go:177:22: Upsert not declared by package route
/Users/jayunit100/SOURCE/cilium/pkg/wireguard/agent/agent.go:182:19: ReplaceRuleIPv6 not declared by package route
/Users/jayunit100/SOURCE/cilium/pkg/wireguard/agent/agent.go:191:22: Upsert not declared by package route
main: 1061 errors during loading
```

Wahts the prefered way to build the project from scratch ?  I didnt see it in `README.rst` after a quick scan.

**Comment by aanm** [comment]
Hey @jayunit100 which OS is it?

**Comment by jayunit100** [comment]
OS X ? But didn't see any OS errors it seemed

**Comment by joestringer** [comment]
For anyone else who finds this issue, I would suggest that if you're building on osx, use the docker build targets (eg `make dev-docker-image`).
