### ISSUE TITLE
Multinode network issues on minikube using --cni=cilium flag

### ISSUE THREAD

**Issue by code-merc** [cilium/cilium#16223]
## Bug report

**General Information**

- Minikube 1.20
- Cilium version (run `cilium version`)
```
Client: 1.8.0 f455c7e69 2020-06-22T16:14:29+02:00 go version go1.14.4 linux/amd64
Daemon: 1.8.0 f455c7e69 2020-06-22T16:14:29+02:00 go version go1.14.4 linux/amd64
```
- Kernel version (run `uname -a`)
```
Linux minikube-m02 4.19.182 #1 SMP Wed May 5 21:20:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Generate and upload a system zip:
[cilium-sysdump-20210519-103345.zip](https://github.com/cilium/cilium/files/6509575/cilium-sysdump-20210519-103345.zip)

**How to reproduce the issue**

1. `minikube start --driver=kvm2 --nodes=2 --cni=cilium --addons=default-storageclass,registry,storage-provisioner --container-runtime=containerd` you can also use the docker driver, as well as docker container runtime and the issue will be the same.
2. Run the cilium tests with 
```bash
kubectl create ns cilium-test

kubectl apply --namespace=cilium-test -f https://raw.githubusercontent.com/cilium/cilium/v1.7/examples/kubernetes/connectivity-check/connectivity-check.yaml
```
3. See the failing tests
```
NAME                                                     READY   STATUS    RESTARTS   AGE
echo-a-8b6595b89-qjtv2                                   1/1     Running   0          5m11s
echo-b-57d8cc56dc-7gk5g                                  1/1     Running   0          5m11s
echo-b-host-7bccc85c7c-hv4d4                             1/1     Running   0          5m11s
host-to-b-multi-node-clusterip-7b87db6659-nbbcb          1/1     Running   0          5m11s
host-to-b-multi-node-headless-8b4797fd9-w67wv            1/1     Running   1          5m11s
pod-to-a-5567c85856-4w9js                                1/1     Running   0          5m10s
pod-to-a-allowed-cnp-7b85c8db8-frv4l                     1/1     Running   0          5m11s
pod-to-a-external-1111-77b455b8bb-mk24c                  1/1     Running   0          5m9s
pod-to-a-l3-denied-cnp-7f64d7b7c4-ckhqm                  1/1     Running   0          5m11s
pod-to-b-intra-node-6f68b7c94f-fcmn8                     1/1     Running   0          5m10s
pod-to-b-intra-node-nodeport-7f77495d64-9nlfx            0/1     Running   5          5m10s
pod-to-b-multi-node-clusterip-9c4b88cc7-mbfzh            1/1     Running   0          5m10s
pod-to-b-multi-node-headless-757985b7bf-44ds6            1/1     Running   1          5m10s
pod-to-b-multi-node-nodeport-666566f6c8-9vrcg            0/1     Running   5          5m10s
pod-to-external-fqdn-allow-google-cnp-6557d6b7d6-kbkl7   1/1     Running   0          5m9s
```
4. You will also be unable to pull from the registry inside the cluster with a connection refused error, but this isn't an issue when there is only 1 node.

Afaik minikube is just running the `quick-install` script when you specify `--cni=cilium` so that's why I brought it up here as well.

**Comment by aanm** [comment]
what are the logs of the containers restarting?

**Comment by code-merc** [comment]
Neither container outputs any logs as far as I can tell, the liveliness probe fails with 
```
Liveness probe failed: curl: (7) Failed to connect to echo-b-host-headless port 31313: Connection refused
```

So I'm assuming that's why it's being restarted

**Comment by pchaigno** [comment]
Did you check if another process is listening on that TCP port on the host?

**Comment by pchaigno** [comment]
This bug is likely happening because you are running Cilium v1.8.0 but deploying connectivity checks for v1.7.0. Please try with https://raw.githubusercontent.com/cilium/cilium/v1.8.0/examples/kubernetes/connectivity-check/connectivity-check.yaml.

I would also strongly recommend to update the Cilium version.

**Comment by code-merc** [comment]
Ok that appears to have fixed the tests, thanks. Still having issues with the registry plugin but cluster networking seems to be mostly fine.

So the issue with the registry looks like it's only happening on the worker node. When pods are scheduled on the main `minikube` node they can pull images just fine from the in cluster registry, but when the pod is schedules on the `minikube-m02` I get 

```
Failed to pull image "localhost:5000/openvpn:tilt-458996d7579b3e4d": rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5000/openvpn:tilt-458996d7579b3e4d": failed to resolve reference "localhost:5000/openvpn:tilt-458996d7579b3e4d": failed to do request: Head http://localhost:5000/v2/openvpn/manifests/tilt-458996d7579b3e4d: dial tcp 127.0.0.1:5000: connect: connection refused
```
It's not an issue with the default CNI, so seems like something cilium is doing.

**Comment by code-merc** [comment]
Actually it looks like this is an issue with the minikube registry after further investigation, so I'll close this. Thanks for the help!
