### ISSUE TITLE
Upgrade to Cilium 1.10.0 breaks external dns resolution

### ISSUE THREAD

**Issue by Antiarchitect** [cilium/cilium#16255]
Just upgraded from 1.9.7 to 1.10.0. Everything works normally internally, but our GitLab runners log now  full of:
```
fatal: unable to access 'https://gitlab.xxx.xxx/some.git/': Could not resolve host: gitlab.xxx.xxx
```
Not all of the runners are failing (about 80% are failing) and I don't see any pattern in this
I know I should provide more info on this but rolled back to 1.9.7 ASAP

**Comment by aanm** [comment]
We would need some better reproducible steps in order to debug the issue.

**Comment by Antiarchitect** [comment]
I know, for now just write this to catch people with similar issue. I will provide more info when able to experiment.

**Comment by Antiarchitect** [comment]
@aanm Upgrading 1.9.8 -> 1.10.1 solved the issue somehow. I'm sure all the configs were the same as for the 1.10.0
