### ISSUE TITLE
datapath: Support devices for bpf_host which ifindex > max(u16)

### ISSUE THREAD

**Issue by brb** [cilium/cilium#16260]
Currently, we disallow devices which ifindex cannot fit in u16. This is because we store ifindex in the CT entry struct which only had the u16 spare field left (https://github.com/cilium/cilium/pull/11267/commits/7282119184a4221c2a61f5b93d6889e8558705be#diff-78122dbc1bf6a53a08f02c035e071f869eaa123b52822d789b79c04ff1cbdf69R550).

To overcome the limitation, we can introduce an intermediate mapping for u32(ifindex) => u16(surrogate_ifindex). In the CT entry we would store surrogate_ifindex, and in the datapath we would use a generated macro function by the agent to derive the real ifindex (similar as we do today with e.g. `NATIVE_DEV_MAC_BY_IFINDEX`).

Extra care should be taken for considering upgrade / downgrade.

**Comment by brb** [comment]
Yep, this is the same issue.

**Comment by davem-git** [comment]
Any update on this? This seems like a blocker for enterprise  usage of cilium

**Comment by alex-berger** [comment]
Got hit by this today. The affected node is only 17 days old and 18'653 Pods have been started (created) on that node so far. It's a shame that Cilium hits such a (low) limit, while neither Linux nor Kubernetes (kubelet, containerd, ...) have any problems with this.

In our case we make sure no node is older than 30 days to avoid such kind of problems, but still with many CronJobs, scaling activities (HPA) and other kinds of dynamically created Pods (e.g. by security scanners) one can easily run into this.

Any chance this gets addressed soon?

**Comment by julianwiedmann** [comment]
The `ct_entry->ifindex` is still used in the LB path for replies by local / NAT backends, to route them back to the client on the correct interface: https://github.com/cilium/cilium/blob/909a5c539d13ee0f316d939a8dd5e7a8031793d5/bpf/lib/nodeport.h#L2847

We also have a FIB lookup in that code path. But the ifindex is still used as fallback on older kernels: https://github.com/cilium/cilium/blob/909a5c539d13ee0f316d939a8dd5e7a8031793d5/bpf/lib/fib.h#L89

So one step towards resolving this issue would be to lift the limitation for environments with `HAVE_FIB_IFINDEX`.

**Comment by michaelsaah** [comment]
totally orthogonal to fixing this, but curious why the CT entry struct can't be altered, as the issue description seems to imply.

**Comment by borkmann** [comment]
> totally orthogonal to fixing this, but curious why the CT entry struct can't be altered, as the issue description seems to imply.

It would break ongoing connections in the datapath upon agent upgrade.

**Comment by davem-git** [comment]
{"level":"fatal","msg":"failed to start: daemon creation failed: failed to finalise LB initialization: eth5 link ifindex 86859 exceeds max(uint16)","subsys":"daemon"} 

still an issue on 1.13.7

**Comment by SkalaNetworks** [comment]
Running v1.14.3 we still encounter the issue:

failed to start: daemon creation failed: failed to finalise LB initialization: tailscale0 link ifindex 101982 exceeds max(uint16); failed to stop: unable to find controller ipcache-inject-labels

Helm install:
```
  egressGateway:
    enabled: true
  bpf:
    masquerade: true
  kubeProxyReplacement: true
  bgpControlPlane:
    enabled: true
  hubble:
    enabled: false
  #l7Proxy: false
  operator:
    replicas: 1
 ```

**Comment by julianwiedmann** [comment]
> Running v1.14.3 we still encounter the issue:
> 
> failed to start: daemon creation failed: failed to finalise LB initialization: tailscale0 link ifindex 101982 exceeds max(uint16); failed to stop: unable to find controller ipcache-inject-labels
> 
> Helm install:
> 
> ```
>   egressGateway:
>     enabled: true
>   bpf:
>     masquerade: true
>   kubeProxyReplacement: true
>   bgpControlPlane:
>     enabled: true
>   hubble:
>     enabled: false
>   #l7Proxy: false
>   operator:
>     replicas: 1
> ```

Are you on a pre-5.10 kernel? Then https://github.com/cilium/cilium/issues/27642 applies.

Otherwise could you please open a fresh issue? Following the template to provide all required debug info.

**Comment by SkalaNetworks** [comment]
```
$ uname -r
5.4.0-152-generic
```

I guess that's the issue, thanks
