### ISSUE TITLE
NodeInit: Implement as an init container to the cilium agent

### ISSUE THREAD

**Issue by seanmwinn** [cilium/cilium#16267]
## Proposal / RFE
Presently the NodeInit daemonset is installed in addition to the Cilium agent and remains scheduled on nodes throughout the lifecycle of Cilium.

By making use of an init container, node init processes can be moved to a container that will run on the node before the cilium agent starts up, but will not remain scheduled on the nodes throughout the lifecycle of Cilium. This has the added benefits of reducing the number of scheduled pods that are associated with a Cilium deployment by 1 pod per node and freeing up an additional IP address for new workloads.

**Comment by aanm** [comment]
@seanmwinn currently, the NodeInit DaemonSet requires `hostPID` set, which Cilium DaemonSet does not. Also NodeInit runs in hostNetwork so it does not consume an additional IP address in the node, but I understand that it does count as 1 more pod running in the node.

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
