### ISSUE TITLE
Skipping symbol substitution cilium_egress_v4

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#16277]
Reported by mikek on Slack:
```
level=warning msg="Skipping symbol substitution" subsys=elf symbol=cilium_egress_v4
```
We need to add `cilium_egress_v4` to `ignoredELFPrefixes`.

**Comment by Divya063** [comment]
I would like to work on this issue.

**Comment by pchaigno** [comment]
@Divya063 Chris assigned you. Don't hesitate to reach out on Slack (#development or #sig-datapath) if you have questions.

**Comment by Divya063** [comment]
Sure @pchaigno
