### ISSUE TITLE
No HTTP Agent connectivity in Loopback-routed L3 network

### ISSUE THREAD

**Issue by vifino** [cilium/cilium#16275]
## Bug report

**General Information**
Hey.
I'm trying to use `cilium 1.9.6` in a fully routed network with loopback routing and can't get it to work.

- Cilium version `1.9.6 38dd27a`
- Kernel version `5.10.36-0-lts #1-Alpine`
- Orchestration system version in use `k8s v1.21.1, kubeadm v1.21.0, helm v3.4`
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip: Sorry, the dump seems to contain a lot of info I do not feel like sharing. The below hopefully contains all necessary info, if it does not, I'll gladly provide more after removing sensitive info.

Following is rather complete description of the setup. Hostnames and IP addresses changed to protect the innocent.

I have 3 nodes running `Alpine Linux 3.13` with the above kernel.

## Network setup

Each node has several IP addresses assigned to interface `lo` along with routes (including a default route) set with the appropriate source IP to use.
FRR runs on each member and - after enough cursing - speaks eBGP with the switches.

```sh
node1# ip a l lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    <SNIP>
    inet WW.XX.YY.ZZ/32 scope global lo
       valid_lft forever preferred_lft forever
    inet 10.253.1.10/32 scope global lo
       valid_lft forever preferred_lft forever
    <SNIP>

node1# ip r
default nhid 13 via 10.251.4.0 dev eth2.5 proto bgp src WW.XX.YY.ZZ metric 20
<SNIP>
10.253.1.11 nhid 14 via 10.251.4.0 dev eth2.5 proto bgp src 10.253.1.10 metric 20
<SNIP>
```

## Kubernetes setup

`tl;dr`: Done with `kubeadm`, setting up `kubernetes 1.21` on `CRI-O 1.20.0` without `kube-proxy` and with dualstack enabled.

There is a `haproxy` in front of all the nodes, properly set as the `controlPlaneEndpoint`.

node1 initializes the cluster, the networking related part of the init config is this:
```sh
node1# magic-cat --only-relevant-info kubeadm-init.yaml 
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.253.1.10"
  bindPort: 6445
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
  kubeletExtraArgs:
    cgroup-driver: "cgroupfs"
    node-ip: "10.253.1.10"

node1# kubeadm init --skip-phases=addon/kube-proxy --config kubeadm-init.yaml --upload-certs
<SNIP>
```

Following nodes use a similar config (but as a `JoinConfiguration`).
Up until here everything works fine.

Side note: This is not much config, but it took me a long time to get the `etcd` cluster to properly bind and work. :(

## Cilium setup

This is where things got really tricky for me.
I want to use native routing, because, after all, the only L2 networks are point-to-point links. And dual-stack IPv6, but I'm not sure if that's fully working.

Using Helm to install cilium seemed to be the easiest.
Below are the changed values from `values.yaml`, I didn't wanna paste the whole config here, but my actual config is a tweaked default `values.yaml`, in case that matters.

```yaml
k8sServiceHost: my-k8s-haproxy.tld
k8sServicePort: 6443

bpf:
  masquerade: true
  hostRouting: true
  tproxy: true

containerRuntime:
  integration: crio
  socketPath: /var/run/crio/crio.sock

endpointRoutes:
  enabled: true

hostPort:
  enabled: true

hostServices:
  enabled: true

ipam:
  clusterPoolIPv4PodCIDR: "10.240.0.0/16"
  clusterPoolIPv6PodCIDR: "AAAA:BBBB:CCCC:DDDD::/104"

ipMasqAgent:
  enabled: true

ipv6:
  enabled: true

k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: true

kubeProxyReplacement: "strict"

nativeRoutingCIDR: "10.0.0.0/8"

tunnel: "disabled"
```

I've tried a few things before this, but I seem to get the furthest with this config.

After deploying the chart with helm, I get these pods:
```sh
node1# helm install cilium cilium/cilium --version 1.9.6 --namespace kube-system --values cilium-values.yaml
<SNIP>
node1# kubectl get pods -A
NAMESPACE     NAME                              READY   STATUS    RESTARTS   AGE
kube-system   cilium-jc2s4                      1/1     Running   0          5d21h
kube-system   cilium-ktrt6                      1/1     Running   0          5d21h
kube-system   cilium-operator-d4548c5bd-k2qmw   1/1     Running   0          5d21h
kube-system   cilium-operator-d4548c5bd-pszk8   1/1     Running   0          5d21h
kube-system   cilium-zgf46                      1/1     Running   0          5d21h
kube-system   coredns-558bd4d5db-85kmb          1/1     Running   0          6d
kube-system   coredns-558bd4d5db-pctzf          1/1     Running   0          6d
<SNIP>
```

That seems fine to me, but after consulting `cilium-health` on the cilium pod running on node1:
```sh
macu-01:~# kubectl exec -itn kube-system cilium-zgf46 -- cilium-health status
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
Probe time:   2021-05-21T15:31:32Z
Nodes:
  node1 (localhost):
    Host connectivity to 10.253.1.10:
      ICMP to stack:   OK, RTT=440.178µs
      HTTP to agent:   OK, RTT=489.691µs
    Endpoint connectivity to 10.240.0.131:
      ICMP to stack:   OK, RTT=585.353µs
      HTTP to agent:   OK, RTT=651.984µs
  node2:
    Host connectivity to 10.253.1.11:
      ICMP to stack:   OK, RTT=611.354µs
      HTTP to agent:   OK, RTT=763.209µs
    Endpoint connectivity to 10.240.1.26:
      ICMP to stack:   OK, RTT=652.309µs
      HTTP to agent:   Get "http://10.240.1.26:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  node3:
    Host connectivity to 10.253.1.12:
      ICMP to stack:   OK, RTT=548.609µs
      HTTP to agent:   OK, RTT=1.089773ms
    Endpoint connectivity to 10.240.2.225:
      ICMP to stack:   OK, RTT=615.129µs
      HTTP to agent:   Get "http://10.240.2.225:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

This really confuses me.

From the node itself, I can ping the addresses too, just like the cilium container. `nmap` shows no open ports, just filtered:
```
node1:~# nmap 10.240.1.26
Starting Nmap 7.91 ( https://nmap.org ) at 2021-05-21 17:38 CEST
Nmap scan report for 10.240.1.26
Host is up (0.00030s latency).
All 1000 scanned ports on 10.240.1.26 are filtered

Nmap done: 1 IP address (1 host up) scanned in 21.31 seconds
```

The logs of the containers are long (since it has been running a while), these are all the warnings I could find:

### `cilium-zgf46`
```
# Seems to not like my /sys/fs/bpf mount, weird, but that's another issue.
level=warning msg="================================= WARNING ==========================================" subsys=bpf
level=warning msg="BPF filesystem is not mounted. This will lead to network disruption when Cilium pods" subsys=bpf
level=warning msg="are restarted. Ensure that the BPF filesystem is mounted in the host." subsys=bpf
level=warning msg="https://docs.cilium.io/en/stable/operations/system_requirements/#mounted-ebpf-filesystem" subsys=bpf
level=warning msg="====================================================================================" subsys=bpf

# Frequently occurs, but irrelevant.
level=warning msg="discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice" subsys=klog

# Those two lines seem odd, but I think they are also unimportant.
level=error msg="Command execution failed" cmd="[iptables -t mangle -n -L CILIUM_PRE_mangle]" error="exit status 1" subsys=iptables
level=warning msg="iptables: No chain/target/match by that name." subsys=iptables

# These seem to be problematic. eth2.5 is correct, though.
level=info msg="k8s mode: Allowing localhost to reach local endpoints" subsys=daemon
level=warning msg="Cannot determine a device from k8s Node IP addr for BPF NodePort device detection" error="Cannot find device with 10.253.1.10 addr" subsys=daemon
level=info msg="Using auto-derived devices for BPF node port" devices="[eth2.5]" directRoutingDevice=eth2.5 subsys=daemon


# Load Balancer of the Control Plane seems to fail a request once or twice during the day. 
level=warning msg="Network status error received, restarting client connections" error="Get \"https://my-k8s-haproxy.tld:6443/healthz?timeout=32s\": write tcp 10.253.1.1:49168->10.253.1.1:6443: write: broken pipe" subsys=k8s

# This seems to be a couple days in. Probably unimportant.
level=info msg="arping failed" error="interrupted system call" interface=eth2.5 ipAddr=10.251.4.0 subsys=node-neigh-debug
```

Regarding the bpf mount:
```sh
node1# grep bpf /etc/fstab
bpffs           /sys/fs/bpf     bpf     rw,shared 0 0
node1# mount | grep bpf
none on /sys/fs/bpf type bpf (rw,relatime)
```

The `Cannot find device with 10.253.1.10` warning seems bad, but I don't think it relates to the issue.

The operator logs seem fine.

I have torn down and reinstalled k8s and cilium many times.
Again, if I failed to provide any info that might help, I'll gladly provide it upon request.
I hope you can help me. :)

**Comment by pchaigno** [comment]
@brb Do we support `lo` for BPF NodePort now?

**Comment by brb** [comment]
> Do we support lo for BPF NodePort now?

We should in v1.10 (requires the L2-less dev patch which was merged in v1.10). @vifino Try with Cilium v1.10.

**Comment by vifino** [comment]
Hey @brb,

I tried with v1.10, took the new `values.yaml` and changed the same values (apart from the runtime stuff, I properly marked the `/sys/fs/bpf` mount as shared, option `shared` in fstab didn't do the trick).

Shortly after the containers are up, I get the health check to succeed, but after a few seconds it goes back to the HTTP check not succeeding.
Just like before, routes are announced to the other hosts just fine, ICMP ping works, but no HTTP traffic. Spawned a basic container, same thing happens then. ICMP works, no HTTP.
Now there are no errors or warnings in the `cilium` pod logs anymore, either.

What can I do?

**Comment by brb** [comment]
@vifino I would suggest to check with `tcpdump` and `cilium monitor` what happens to the failing requests.

**Comment by vifino** [comment]
Sorry for the late response.
I've tried to capture what exactly went wrong, but best I could tell was cilium containers requests being NATed to the host's IP, which is set as the `src` attribute of the corrosponding route. Sorry.

The IP range is definitly in the "don't NAT" range (`nativeRoutingCIDR`), but it seems to do it anyway. Probably something to do with the `src` attribute and handling thereof.
Should only use it when NATing, not when routing.

I'd really appreciate someone else attempting this - a fully routed topology over the loopback interface - with more k8s and cilium knowledge.
I will gladly provide configs or help setting up a testing environment, but I can't figure it out, unfortunately.

**Comment by brb** [comment]
> cilium containers requests being NATed to the host's IP, which is set as the src attribute of the corrosponding route. Sorry.

Mind elaborating which exactly request it was (who is a sender and who is a receiver)?

**Comment by vifino** [comment]
The request was from node02 to the cilium pod on node01, source natted to node02's IP address.

**Comment by brb** [comment]
I think your setup might be very similar to the one mentioned in https://github.com/cilium/cilium/issues/16539 (cc @Frankkkkk).

**Comment by Frankkkkk** [comment]
Disclaimer: My setup is only IPv6 without NAT. It works quite well however indeed the biggest "trick" is to remove the kernel route of the IPs to `lo` (so that the route to `cililum_host` is used instead). Without it the Node IPs will ping (cause it reaches the host), but not the services.
Also, contrary to your setup, we add < /128 (I think /110 or something like that) IPs to `lo`. This was a technical issue because we couldn't BGP announce thousands of IPs, so each node announces a (pod) range and pod ips are allocated from this range (`ipam.mode = kubernetes`).
On an early iteration, we had a dummy interface named `bgp-announce` (`ip link add bgp-announce type dummy`) that kept all the IPs to be announced (and it worked fine), but we decided to add them to `lo` instead.
