### ISSUE TITLE
Unable to restore endpoint when cilium running on generic-veth cni-chaining mode

### ISSUE THREAD

**Issue by FirmlyReality** [cilium/cilium#16281]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
- 
Client: 1.9.7 f993696 2021-05-12T18:21:30-07:00 go version go1.15.12 linux/amd64
Daemon: 1.9.7 f993696 2021-05-12T18:21:30-07:00 go version go1.15.12 linux/amd64

- Kernel version (run `uname -a`): Linux VM-1-162-ubuntu 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...):  v1.18.4
- Link to relevant artifacts (policies, deployments scripts, ...): https://docs.cilium.io/en/v1.9/gettingstarted/cni-chaining-generic-veth/
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. I deployed the cilium according to the docs(https://docs.cilium.io/en/v1.9/gettingstarted/cni-chaining-generic-veth/) on tencent kubernetes engine.
```
helm template cilium cilium/cilium --version 1.9.7 \
  --namespace=kube-system \
  --set cni.chainingMode=generic-veth \
  --set cni.customConf=true \
  --set cni.configMap=cni-configuration \
  --set tunnel=disabled \
  --set masquerade=false > cilium.yaml
```

```
kubectl create -f cilium.yaml
```

with the `chaing.yaml` creating configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cni-configuration
  namespace: kube-system
data:
  cni-config: |-
    {
      "name": "generic-veth",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "tke-route-eni",
          "routeTable": 100,
          "ipam": {
                  "type": "tke-eni-ipamc",
                  "backend": "localhost:50050"
          }
        },
        {
          "type": "cilium-cni"
        }
      ]
    }
```

2. And I deployed a test pod which is a simple ubuntu busybox. But I found it cannot connect to default k8s service through ClusterIP:
![image](https://user-images.githubusercontent.com/14286074/119343594-3d6e0180-bcc9-11eb-892b-b6aa175cd2e4.png)

3. Then I checked logs of the cilium-agent. It showed that "Unable to update ipcache map entry on pod add":
![image](https://user-images.githubusercontent.com/14286074/119344217-fdf3e500-bcc9-11eb-81e1-027347f521e7.png)

4. I checked the related codes:
![image](https://user-images.githubusercontent.com/14286074/119345419-6db69f80-bccb-11eb-9c11-e3962c883c1a.png)

I think It may report error when validating endpoints in `restoreOldEndpoints` func，and then make it unable to restore to load bpf program in `regenerateRestoredEndpoints` func.

**Comment by pchaigno** [comment]
https://github.com/cilium/cilium/pull/16227 should fix this issue. You can test it with:
- On master: `docker.io/pchaigno/cilium-dev:fix-aws-cni-v2@sha256:261bff038ee476b505a4123d2f7ab932bb6a1a6dc0712a7ac3df5cbeaf8a0693`.
- On v1.9: `docker.io/pchaigno/cilium-dev:v1.9-fix-aws-cni-v2@sha256:5849d9361c6023bd185ff9fdb07f7071808131c1c1b7304c7e29fd25b708e4a6`.
