### ISSUE TITLE
Blocked kube-dns udp traffic in Cilium 1.10.0

### ISSUE THREAD

**Issue by itsthatriver** [cilium/cilium#16287]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         OK
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 2, Ready: 2/2, Available: 2/2
Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Deployment        hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium-operator    Running: 2
                  hubble-relay       Running: 1
                  cilium             Running: 2
Image versions    cilium             quay.io/cilium/cilium:v1.10.0@sha256:587627d909ffe0418c0bd907516496844867a21812946af82096d367760e4c1e: 2
                  cilium-operator    quay.io/cilium/operator-generic:v1.10.0@sha256:65143311a62a95dbe23c69ff2f624e0fdf030eb225e6375d889da66a955dd828: 2
                  hubble-relay       quay.io/cilium/hubble-relay:v1.10.0@sha256:e92e6778c71aa9e181618d61e9403761ad061c3960a9203aa2cf8e6cde95c9d7: 1
- Kernel version (run `uname -a`)
Linux ip-192-168-9-139.ec2.internal 5.4.110-54.189.amzn2.x86_64 #1 SMP Mon Apr 26 21:25:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...)
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
We have a couple network policies, but inspection of the policies and tracing with the cilium cli indicate that there should be no blocks occurring. Since the traffic appears to be originating from kube-dns, this ends up being the only policy that matters (kube-system is a trusted namespace)
```
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            trusted-traffic: "true"
    podSelector: {}
    policyTypes:
    - Ingress
```
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
[cilium-sysdump-20210524-175407.zip](https://github.com/cilium/cilium/files/6535742/cilium-sysdump-20210524-175407.zip)
```

**How to reproduce the issue**

1. Create 1.19.7 EKS cluster with private nodes
2. helm install cilium cilium/cilium --version 1.9.7 \ 
  --namespace kube-system \
  --set egressMasqueradeInterfaces=eth0 \
  --set nodeinit.enabled=true
2. helm upgrade cilium cilium/cilium --version 1.10.0 \ 
  --namespace kube-system \
  --set egressMasqueradeInterfaces=eth0 \
  --set nodeinit.enabled=true

I'm seeing services that are unhealthy, and the one service I'm actually getting logs from is reporting issues with inability to resolve dns for the kube api (kubernetes.default.svc.cluster.local). Looking at the hubble UI I see the below. In that UI, that list of ports with denied traffic grows indefinitely as I watch.

![image](https://user-images.githubusercontent.com/5632093/119424540-823e6c00-bcba-11eb-96b7-4a4e0ea8c3f3.png)

From `hubble observe --type drop`, I see lots of results that look like this (with various endpoints on the right hand side)
```
May 25 00:50:32.890: kube-system/kube-dns:53 <> monitoring/thanos-query-5c645d6f79-hww9w:50077 Policy denied DROPPED (UDP)
May 25 00:50:32.890: kube-system/kube-dns:53 <> monitoring/thanos-query-5c645d6f79-hww9w:40673 Policy denied DROPPED (UDP)
May 25 00:50:32.891: kube-system/kube-dns:53 <> monitoring/thanos-query-5c645d6f79-hww9w:44912 Policy denied DROPPED (UDP)
May 25 00:50:32.891: kube-system/kube-dns:53 <> monitoring/thanos-query-5c645d6f79-hww9w:57103 Policy denied DROPPED (UDP)
May 25 00:50:34.450: kube-system/kube-dns:53 <> monitoring/thanos-compact-0:38926 Policy denied DROPPED (UDP)
May 25 00:50:34.450: kube-system/kube-dns:53 <> monitoring/thanos-compact-0:47933 Policy denied DROPPED (UDP)
```

I'm seeing similar failures in GKE, EKS, and AKS (GKE runs operator-generic w/ native routing and kubernetes ipam, EKS runs operator-generic w/ cluster-pool ipam and vxlan tunnels, AKS runs operator-azure w/ native routing and azure ipam)

These configs all worked on Cilium 1.9.7 (before the small config updates that came with 1.10.0, using the same values inputs to helm)

cc @aanm

**Comment by thejosephstevens** [comment]
Turns out this was an issue of not adding the compatibility flag for 1.9. When I added that and reapplied the configs everything worked fine.

**Comment by acholt** [comment]
Thanks @thejosephstevens I had the exact same issue. @pchaigno the was nothing specific in the documentation for 1.9 upgrades, well at least this is not the way I read it. Should the documentation not be updated?

- https://docs.cilium.io/en/v1.10/operations/upgrade/#version-specific-notes

**Comment by pchaigno** [comment]
@acholt It's mentioned in https://docs.cilium.io/en/v1.10/operations/upgrade/#step-2-use-helm-to-upgrade-your-cilium-deployment. Where you expecting something different?

**Comment by acholt** [comment]
@pchaigno - Yes, I expect 1.9 to be in the valid options, I wasn't sure so I checked the version-specific notes I linked earlier so didn't see anything for 1.9 specifically so assumed it wasn't required.

It reads as users of version 1.8 and older use this flag.

> Valid options are:
> 1.7 if the initial install was Cilium 1.7.x or earlier.
> 1.8 if the initial install was Cilium 1.8.x.

**Comment by pchaigno** [comment]
Ok. Then we should edit https://docs.cilium.io/en/v1.10/operations/upgrade/#step-2-use-helm-to-upgrade-your-cilium-deployment to make it clear that all versions starting with 1.7 are valid options.

**Comment by acholt** [comment]
I was looking to editing it but see @aanm has already added 1.9 it just hasn't been published yet.  #https://github.com/cilium/cilium/commit/076f475863d6627ac2163554e69038333f30118c

**Comment by pchaigno** [comment]
Ah, nice find! It will appear in the 1.10 version of the docs once backported to the v1.10 branch.
