### ISSUE TITLE
eBPF-based host-routing and tunnel mode

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#16280]
while reading https://cilium.io/blog/2021/05/11/cni-benchmark and https://docs.cilium.io/en/latest/operations/performance/tuning/#ebpf-host-routing

my understanding is that host routing also support tunnel mode and packet egress from container, and encapsulated overlay packet   should skip the netfilter/iptables processing, but I still see the overlay packet to destination VXLAN port 8472 seems still processed by netfilter chains, maybe my understanding is incorrect or my observation is not accurate, please correct me if I am wrong.

Here is my test:

two nodes runs cilium in tunnel mode,  kubeproxy strict

cilium status to show host routing BPF
<pre>
kubectl  exec -it $CA2 -n kube-system -- cilium status
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20 (v1.20.2) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens192 10.169.72.129 (Direct Routing)]
Cilium:                 Ok   1.10.0-rc2 (v1.10.0-rc2-d65e51a)
NodeMonitor:            Listening for events on 4 CPUs with 64x4096 of shared memory
IPAM:                   IPv4: 3/254 allocated from 10.0.1.0/24, 
BandwidthManager:       EDT with BPF   [ens192]
Host Routing:           BPF
Masquerading:           BPF   [ens192]   10.0.1.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:      23/23 healthy
Proxy Status:           No managed proxy redirect
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 7.21   Metrics: Disabled
Encryption:             Disabled
Cluster health:               Warning   cilium-health daemon unreachable
</pre>

from busybox pod to ping a remote nginx pod,

<pre>
root@cilium-bigip:/home/vincent# kubectl  get po -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP           NODE               NOMINATED NODE   READINESS GATES
busybox-worker-ccb4ffc6c-ww8hd   1/1     Running   0          15m   10.0.1.87    cilium-fl-worker   <none>           <none>
nginx-master-6698c4ccdc-x6vw5    1/1     Running   0          15m   10.0.0.113   cilium-bigip       <none>           <none>
root@cilium-bigip:/home/vincent# kubectl exec -it $BUSYBOX -- /bin/sh
/ # ping -c 1  10.0.0.113  
PING 10.0.0.113 (10.0.0.113): 56 data bytes
64 bytes from 10.0.0.113: seq=0 ttl=63 time=1.275 ms

--- 10.0.0.113 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.275/1.275/1.275 ms
</pre>

 run iptables trace to trace packet to destination port 8472 on the node  cilium-fl-worker busybox pod is on, I see following iptables trace:

<pre>

May 24 01:52:13 cilium-fl-worker kernel: [10511.914227] TRACE: raw:OUTPUT:policy:2 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914248] TRACE: mangle:OUTPUT:policy:1 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914258] TRACE: nat:OUTPUT:policy:2 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914265] TRACE: filter:OUTPUT:rule:1 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914272] TRACE: filter:KUBE-FIREWALL:return:3 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914276] TRACE: filter:OUTPUT:policy:2 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914282] TRACE: mangle:POSTROUTING:policy:1 IN=cilium_vxlan OUT=ens192 MAC=b2:7a:2a:88:d6:73:ca:0a:89:ad:b0:6e:08:00 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914288] TRACE: nat:POSTROUTING:rule:1 IN=cilium_vxlan OUT=ens192 MAC=b2:7a:2a:88:d6:73:ca:0a:89:ad:b0:6e:08:00 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914296] TRACE: nat:KUBE-POSTROUTING:rule:1 IN=cilium_vxlan OUT=ens192 MAC=b2:7a:2a:88:d6:73:ca:0a:89:ad:b0:6e:08:00 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914300] TRACE: nat:POSTROUTING:policy:3 IN=cilium_vxlan OUT=ens192 MAC=b2:7a:2a:88:d6:73:ca:0a:89:ad:b0:6e:08:00 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=51649 PROTO=UDP SPT=41595 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914978] TRACE: raw:PREROUTING:policy:2 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914989] TRACE: mangle:PREROUTING:policy:1 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.914996] TRACE: nat:PREROUTING:rule:1 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.915000] TRACE: nat:DOCKER:return:2 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.915004] TRACE: nat:PREROUTING:policy:2 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.915010] TRACE: mangle:INPUT:policy:1 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.915038] TRACE: filter:INPUT:rule:1 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.915043] TRACE: filter:KUBE-FIREWALL:return:3 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.915046] TRACE: filter:INPUT:policy:2 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
May 24 01:52:13 cilium-fl-worker kernel: [10511.915049] TRACE: nat:INPUT:policy:1 IN=ens192 OUT= MAC=00:50:56:86:66:45:00:50:56:86:48:98:08:00 SRC=10.169.72.128 DST=10.169.72.129 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=59241 PROTO=UDP SPT=37135 DPT=8472 LEN=114 
</pre>

**Comment by borkmann** [comment]
> my understanding is that host routing also support tunnel mode and packet egress from container, and encapsulated overlay packet should skip the netfilter/iptables processing

Not quite, before the support Pod-to-Pod packets had to go twice through the stack: 1) UDP stack for overlay for the outer one, 2) upper host for netfilter/routing for the inner one. With BPF host routing, the 2nd part is removed as well as the case when you access Pods from the outside not going through the tunnel (e.g. NodePort svc - also here it went to upper stack before the change, and now it goes directly to the Pod). The latter benefits from the BPF host routing in particular as shown in the benchmark.

**Comment by vincentmli** [comment]
@borkmann 

Thank you very much for your clarification!  just curious, does it make sense to skip netfilter for outer one too or not worth the effort and not much gain there

**Comment by vincentmli** [comment]
Just add more lab observation, I downgraded my kernel to 5.8 which does not support eBPF host routing, so cilium fall back to legacy host routing

<pre>
kubectl  exec -it $CA2 -n kube-system -- cilium status
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20 (v1.20.7) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens192 10.169.72.129 (Direct Routing)]
Cilium:                 Ok   1.10.0-rc2 (v1.10.0-rc2-d65e51a)
NodeMonitor:            Listening for events on 4 CPUs with 64x4096 of shared memory
IPAM:                   IPv4: 2/254 allocated from 10.0.1.0/24, 
BandwidthManager:       EDT with BPF   [ens192]
Host Routing:           Legacy
Masquerading:           BPF   [ens192]   10.0.1.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:      19/19 healthy
Proxy Status:           No managed proxy redirect
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 0.61   Metrics: Disabled
Encryption:             Disabled
Cluster health:               Warning   cilium-health daemon unreachable
</pre>

and I ran iptables trace in host namespace, I saw similar iptables trace for outer overlay packet, but no iptables trace for inner pod-to-pod packet, my understanding is that the veth interface in host side for container has ingress "from-container"  that does the encapsulation and redirect to cilium_vxlan interface, it appears netfilter in hostname space does not process pod-to-pod for cilium tunnel mode. if I ran kubernetes with kube-proxy and flannel, no cilium, indeed pod-to-pod traffic and overlay traffic both processed by netfilter in hostname space. but I see no difference for cilium tunnel mode between legacy routing and ebpf host routing for inner pod-to-pod processing in host namespace, of course I could be missing something, just my observation :)

for example, run both iptables trace in container and in hostname space with following rules:
<pre>
 iptables -t raw -j TRACE -I PREROUTING 1
iptables -t raw -j TRACE -I OUTPUT 1
</pre>

ping remote pod from netshoot pod
<pre>
 kubectl  exec -it netshoot -- /bin/bash
bash-5.1# ping -c 1 10.0.0.38
PING 10.0.0.38 (10.0.0.38) 56(84) bytes of data.
64 bytes from 10.0.0.38: icmp_seq=1 ttl=63 time=0.888 ms

--- 10.0.0.38 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.888/0.888/0.888/0.000 ms
bash-5.1# iptables -t raw -n -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
TRACE      all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
TRACE      all  --  0.0.0.0/0            0.0.0.0/0           
</pre>

iptables trace inside container:

<pre>
May 26 14:53:21 cilium-fl-worker kernel: [55613.473004] TRACE: raw:OUTPUT:policy:2 IN= OUT=eth0 SRC=10.0.1.34 DST=10.0.0.38 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=24469 DF PROTO=ICMP TYPE=8 CODE=0 ID=21198 SEQ=1 UID=0 GID=0 

May 26 14:53:21 cilium-fl-worker kernel: [55613.473866] TRACE: raw:PREROUTING:policy:2 IN=eth0 OUT= MAC=f2:92:2b:4d:18:fc:6e:26:08:e4:56:64:08:00 SRC=10.0.0.38 DST=10.0.1.34 LEN=84 TOS=0x00 PREC=0x00 TTL=63 ID=990 PROTO=ICMP TYPE=0 CODE=0 ID=21198 SEQ=1 
</pre>

iptables trace in hostname space:

<pre>
May 26 14:53:21 cilium-fl-worker kernel: [55613.473148] TRACE: raw:OUTPUT:policy:2 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 
May 26 14:53:21 cilium-fl-worker kernel: [55613.473155] TRACE: mangle:OUTPUT:policy:1 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 
May 26 14:53:21 cilium-fl-worker kernel: [55613.473160] TRACE: nat:OUTPUT:policy:2 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 
May 26 14:53:21 cilium-fl-worker kernel: [55613.473163] TRACE: filter:OUTPUT:rule:1 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 
May 26 14:53:21 cilium-fl-worker kernel: [55613.473166] TRACE: filter:KUBE-FIREWALL:return:3 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 
May 26 14:53:21 cilium-fl-worker kernel: [55613.473168] TRACE: filter:OUTPUT:policy:2 IN= OUT=ens192 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 
May 26 14:53:21 cilium-fl-worker kernel: [55613.473172] TRACE: mangle:POSTROUTING:policy:1 IN=cilium_vxlan OUT=ens192 MAC=6e:26:08:e4:56:64:f2:92:2b:4d:18:fc:08:00 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 
May 26 14:53:21 cilium-fl-worker kernel: [55613.473175] TRACE: nat:POSTROUTING:rule:1 IN=cilium_vxlan OUT=ens192 MAC=6e:26:08:e4:56:64:f2:92:2b:4d:18:fc:08:00 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 
May 26 14:53:21 cilium-fl-worker kernel: [55613.473181] TRACE: nat:KUBE-POSTROUTING:rule:1 IN=cilium_vxlan OUT=ens192 MAC=6e:26:08:e4:56:64:f2:92:2b:4d:18:fc:08:00 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 
May 26 14:53:21 cilium-fl-worker kernel: [55613.473186] TRACE: nat:POSTROUTING:policy:3 IN=cilium_vxlan OUT=ens192 MAC=6e:26:08:e4:56:64:f2:92:2b:4d:18:fc:08:00 SRC=10.169.72.129 DST=10.169.72.128 LEN=134 TOS=0x00 PREC=0x00 TTL=64 ID=62790 PROTO=UDP SPT=52588 DPT=8472 LEN=114 

</pre>

**Comment by borkmann** [comment]
> but I see no difference for cilium tunnel mode between legacy routing and ebpf host routing for inner pod-to-pod processing in host namespace, of course I could be missing something, just my observation :)

That observation is correct. For Pod-Pod over tunnel in legacy mode only the outer one goes through the host stack. And the BPF prog from cilium_vxlan/geneve will redirect at tc layer to the Pod. From the Pod in bpf_lxc, it will redirect back to the tunnel dev. The one difference here for Pod-Pod case is that due to the use of redirect_peer() it will decrease the latency slightly due to not having to switch to the different netns via net_rx_action.

**Comment by BurlyLuo** [comment]
> The one difference here for Pod-Pod case is that due to the use of redirect_peer() it will decrease the latency slightly due to not having to switch to the different netns via net_rx_action.

Is it menas that, if we use the legacy mode, it needs send the packet to the lxc-xxxxxxxx interface. but with the BPF mode, it will be redirected to the pod's eth0 interface by redirect_peer() helpers. if wrong, please correct me here, thanks.

**Comment by BurlyLuo** [comment]
```
CPU 04: MARK 0x0 FROM 809 DEBUG: Conntrack lookup 1/2: src=10.0.1.253:45 dst=10.0.0.215:0
CPU 04: MARK 0x0 FROM 809 DEBUG: Conntrack lookup 2/2: nexthdr=1 flags=1
CPU 04: MARK 0x0 FROM 809 DEBUG: CT verdict: New, revnat=0
CPU 04: MARK 0x0 FROM 809 DEBUG: Successfully mapped addr=10.0.0.215 to identity=29735
CPU 04: MARK 0x0 FROM 809 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=29735 lb=0.0.0.0
CPU 04: MARK 0x0 FROM 809 DEBUG: Encapsulating to node 2886860806 (0xac120006) from seclabel 29735
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=be:2c:08:54:47:03 DstMAC=72:e7:d4:b4:30:c1 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=32240 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=42469 SrcIP=10.0.1.253 DstIP=10.0.0.215 Options=[] Padding=[]}
ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=15248 Id=45 Seq=0}
  Failed to decode layer: No decoder for layer type Payload
CPU 04: MARK 0x0 FROM 809 to-overlay: 98 bytes (98 captured), state new, interface cilium_vxlan, , identity 29735->unknown, orig-ip 0.0.0.0
CPU 04: MARK 0x0 FROM 464 DEBUG: Conntrack lookup 1/2: src=172.18.0.8:43200 dst=172.18.0.6:8472
CPU 04: MARK 0x0 FROM 464 DEBUG: Conntrack lookup 2/2: nexthdr=17 flags=1
CPU 04: MARK 0x0 FROM 464 DEBUG: CT entry found lifetime=219092, revnat=0
CPU 04: MARK 0x0 FROM 464 DEBUG: CT verdict: Established, revnat=0
CPU 04: MARK 0x0 FROM 464 DEBUG: Successfully mapped addr=172.18.0.6 to identity=6
CPU 04: MARK 0x0 FROM 0 DEBUG: Tunnel decap: id=29735 flowlabel=0
CPU 04: MARK 0x0 FROM 0 DEBUG: Attempting local delivery for container id 809 from seclabel 29735
CPU 04: MARK 0x0 FROM 809 DEBUG: Conntrack lookup 1/2: src=10.0.0.215:0 dst=10.0.1.253:45
CPU 04: MARK 0x0 FROM 809 DEBUG: Conntrack lookup 2/2: nexthdr=1 flags=0
CPU 04: MARK 0x0 FROM 809 DEBUG: CT entry found lifetime=219714, revnat=0
CPU 04: MARK 0x0 FROM 809 DEBUG: CT verdict: Reply, revnat=0
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=72:e7:d4:b4:30:c1 DstMAC=be:2c:08:54:47:03 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=34574 Flags= FragOffset=0 TTL=63 Protocol=ICMPv4 Checksum=56775 SrcIP=10.0.0.215 DstIP=10.0.1.253 Options=[] Padding=[]}
ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoReply Checksum=17296 Id=45 Seq=0}
  Failed to decode layer: No decoder for layer type Payload
CPU 04: MARK 0x0 FROM 809 to-endpoint: 98 bytes (98 captured), state reply, interface lxcb527e53a7df7, , identity 29735->29735, orig-ip 10.0.0.215, to endpoint 809
```
About this part:
```
CPU 04: MARK 0x0 FROM 464 DEBUG: Conntrack lookup 1/2: src=172.18.0.8:43200 dst=172.18.0.6:8472
CPU 04: MARK 0x0 FROM 464 DEBUG: Conntrack lookup 2/2: nexthdr=17 flags=1
```
We can see that this CT is deal by cilium_host interface. is it mean that the VxLAN packet need deal with cilium_host interface?
```
root@cilium-vxlan-host-routing-control-plane:~# cilium endpoint get 464 | grep -C 1 "interface-name"
        "host-mac": "d2:b6:fc:31:39:75",
        "interface-name": "cilium_host",
        "mac": "d2:b6:fc:31:39:75"
root@cilium-vxlan-host-routing-control-plane:~# 
```
