### ISSUE TITLE
Proposal: Alternative and/or pluggable load-balancing policies

### ISSUE THREAD

**Issue by tsenart** [cilium/cilium#163]
It would be useful to plug-in different load balancing policies in the load balancing eBPF program.

**Comment by aanm** [comment]
Can you give some examples/use cases?

**Comment by tgraf** [comment]
I met @tsenart yesterday and we discussed this a bit. The idea is to make the backend selection process pluggable so it can support more than the current hash based method. This would require an extension to both, the policy layer to configure this and the eBPF part to implement the selected method. We have all the necessary building blocks for stateful LB as well, it's only a matter of putting it together.

**Comment by tsenart** [comment]
@aanm: The LB algorithm ought to be pluggable so that load distribution is optimal for different workloads and network communication patterns.

I'd like, for instance, to have a stateful weighted round robin algorithm that could take into account a number of load metrics per slave (backend).

**Comment by tsenart** [comment]
In normal L7 load-balancing, it's relatively easy to keep track of outstanding "requests" per backend, average request latency, etc. I'm thinking how we could use some sort of deep packet inspection to do the same in L3/L4. Not sure this is a good idea or if there are simpler alternatives.

**Comment by josephjacks** [comment]
Interesting. Would this effectively mean that Cilium's security policies could natively span L3/4 and L5/7 for connections and packet flows? @tgraf

**Comment by tgraf** [comment]
@josephjacks Yes, that's already doable with the current code. What @tsenart is proposing on top of that is to implement a LB at L3/L4 with L7 filtering techniques without terminating the actual connection. Instead use regular L3/L4 load balancing techniques. This offers much greater performance and scale and is much harder to attack. It also offers the advantage of direct server return possibility.
