### ISSUE TITLE
Disconnect between what Cilium and K8S see for an IP of a Pod

### ISSUE THREAD

**Issue by petreski** [cilium/cilium#16303]
## Bug report

**General Information**

- Cilium version (run `cilium version`): 1.10
- Kernel version (run `uname -a`): Linux minikube 4.19.182 #1 SMP
- Orchestration system version in use (e.g. `kubectl version`, ...) 1.19.7
- Link to relevant artifacts (policies, deployments scripts, ...): https://github.com/petreski/cilium-examples
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```
https://github.com/petreski/cilium-examples/blob/main/cilium-sysdump-20210525-174507.zip

**How to reproduce the issue**

1. start minikube

minikube config set vm-driver virtualbox
minikube start --network-plugin=cni

2. follow this guide to setup bridged network interface https://dpb587.me/post/2020/04/11/minikube-and-bridged-networking/
3. restart minikube
4. install cilium using helm (enable egressGateway as described here https://docs.cilium.io/en/latest/gettingstarted/egress-gateway/)
5. deploy simple deployment as described https://docs.cilium.io/en/latest/gettingstarted/egress-gateway/
6. setup egress NAT policy and apply egress-ip-assign
7. ensure that in minikube eth2 has additional IPs assigned
8. try to access external web-server in the same subnet
9. expected result in external's web-server access-log is an entry which shows that NAT policy gets applied (in my case it doesn't)
[cilium-sysdump-20210525-174507.zip](https://github.com/cilium/cilium/files/6540694/cilium-sysdump-20210525-174507.zip)

**Comment by pchaigno** [comment]
This came up in the context of the egress IP gateway, but doesn't seem related. There's clearly something broken:
```
$ kubectl get cep
NAME       ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4         IPV6
mediabot   2905          28328                                                                        ready            10.0.0.110   
$ kubectl get pods -A -o wide --show-labels | grep mediabot
default       mediabot                           1/1     Running   2          23h   10.88.0.11       minikube   <none>           <none>            Class=mediabot,Org=empire,class=mediabot,org=empire
```

**Comment by aanm** [comment]
As requested in slack, please check if the issue still persists *without* following the guide to setup bridged network interface

**Comment by petreski** [comment]
Cannot reproduce on a new cluster created using kubeadm.
