### ISSUE TITLE
Investigate AKS transient failures resolving service names via DNS with IPsec

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#16306]
## Bug report

**General Information**

- Cilium v1.9.6, v1.10.0, master

**How to reproduce the issue**

1. Follow the guide to install Cilium on AKS: https://docs.cilium.io/en/latest/gettingstarted/k8s-install-default/#create-the-cluster
2. Install Cilium via CLI, make sure to pass `--encryption ipsec`
3. Run `cilium connectivity test` multiple times and observe that it mostly fails, and occasionally succeeds. 

From what I can tell, this is not a CLI issue because if you repeat the same commands that the CLI does, then you can eventually replicate the same issue. Namely for pod-to-service tests, just running `nslookup <svc name>` from one of the client pods in a loop, you will eventually get a connection that hangs and times out. It also seems that this happens with IPsec only, but unclear why it could be non-deterministic.

**Comment by pchaigno** [comment]
What tests are failing? All of them?

Probably worth checking if any statistics in `/proc/net/xfrm_stat` are increasing as the failures happen.
