### ISSUE TITLE
cilium-node-init fails for AKS-nodes

### ISSUE THREAD

**Issue by smnmtzgr** [cilium/cilium#16321]
## Bug report

On AKS (tested with k8s 1.19.9 and k8s 1.20.5) the nodeinit container doesnt restarted unmanaged (kubenet managed) pods. It gives the following output:
```
Restarting kubenet managed pods
bash: line 59: docker: command not found
find: '/var/lib/cni/networks/': No such file or directory
Ensuring azure-vnet is configured in 'transparent' mode...
Node initialization complete
!!! startup-script succeeded!
```

**General Information**

- Cilium version (run `cilium version`): 1.10.0
- OS: Ubuntu 18.04.05 with containerd
- Orchestration system version in use (e.g. `kubectl version`, ...): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"6c90dbd9d6bb1ae8a4c0b0778752be06873e7c55", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...): https://github.com/cilium/cilium/blob/v1.10.0/install/kubernetes/cilium/templates/cilium-nodeinit-daemonset.yaml

**How to reproduce the issue**

1. create an AKS cluster with Kubernetes 1.19.9 or 1.20.5
2. Install cilium on it with recommended settings and enable nodeinit with restartPods: true, e.g. for helm:
```
nodeinit:
  enabled: true
  restartPods: true
```
3. scale you cluster manually to add a node and move pods to it or restart your cluster with azure-cli: az aks stop/start ...
4. check that there are "unmanaged nodes":
```
CIL_ENDPOINTS=$(k get ciliumendpoints -A | grep -v ENFORCEMENT)
K8S_PODS=$(kubectl get pods --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork,STATUS:.status.phase --no-headers=true | grep '<none>' | grep 'Running')
echo "CILIUM MANAGED ENDPOINTS: $(echo $CIL_ENDPOINTS | wc -l)"
echo "K8S PODS (WITHOUT HOST NETWORKING): $(echo $K8S_PODS | wc -l)"

CIL_ENDPOINT_NAMES=$(echo $CIL_ENDPOINTS | awk '{print $1" "$2}')
K8S_POD_NAMES=$(echo $K8S_PODS | awk '{print $1" "$2}')

diff <(echo $CIL_ENDPOINT_NAMES) <(echo $K8S_POD_NAMES)
```

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
