### ISSUE TITLE
Dead links in documentation for tests

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#16335]
Some of the jenkins.cilium.io in the documentation are currently 404

Direct link: https://github.com/cilium/cilium/blob/4d52791d27de836d2fb1190230769e32ad813c25/Documentation/contributing/testing/ci.rst#L210-L229

same for https://github.com/cilium/cilium/blob/4d52791d27de836d2fb1190230769e32ad813c25/Documentation/contributing/testing/ci.rst#L421-L438

**Comment by joestringer** [comment]
We're removing Jenkins now, no need to complete this.
