### ISSUE TITLE
CI: Make LRP connectivity test case reliable

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#16348]
This issue tracks the changes required to fix the LRP connectivity test case. Details from #16194 - 

Looking at the LRP test case where we check if traffic only goes to the local backend, it doesn't seem reliable since it's possible that the curl request that the test made wasn't redirected to the remote backend by chance. I think the reliable way to validate the correctness is to check for a LocalRedirect service entry and its corresponding backends in the cilium service list .

**Comment by brb** [comment]
@aditighag Is the test case still flaky? If yes, do you plan to work on this?

**Comment by aditighag** [comment]
The test is not flaky, it's a matter of making the test validation more reliable. Yes, I'll keep it in my queue.

**Comment by aditighag** [comment]
We extended cilium-cli connectivity test suite with LRP tests.
