### ISSUE TITLE
Ethernet adapter gets reset and node becomes unreachable

### ISSUE THREAD

**Issue by cyrilcros** [cilium/cilium#16366]
## Bug report

**General Information**

- Cilium version (run `cilium version`): 1.10.0
- Kernel version (run `uname -a`): Linux dolores 5.8.0-26-generic #27-Ubuntu SMP Wed Oct 21 22:29:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...): v1.21.0"
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

I run a bare metal install of Kubernetes 1.21.0, CIlium 1.10.0, with kube-proxy replacement set to strict.  My OS is Ubuntu 20.04 server, with the networking configured via cloud-init (and delegated to netplan). One of my nodes will regularly stop being reachable.  It has a single ethernet interface, which at times gets reset and loses its IP address. It looks like the configuration of the `cilium_host` interface may be causing that. 
Also, how do I disable IPV6 for cilium.? I only want IPV4,  thanks. 

Reversed `journalctl` logs (I have no Xorg installed, sorry for the phone screenshot...). I will add the dump ASAP too.

![IMG_1532](https://user-images.githubusercontent.com/10993194/120034362-f3d42e00-bfca-11eb-92bf-c5372b5c5477.jpg)

EDIT: I can't ping my node via IPV4, but IPV6 is fine. The node is reachable via `kubectl get node`....

**Comment by cyrilcros** [comment]
Closing, I am not sure what is going on...

**Comment by cyrilcros** [comment]
https://github.com/cilium/cilium/issues/10645 is my final guess as the root cause

**Comment by brb** [comment]
@cyrilcros What is your systemd version?

**Comment by cyrilcros** [comment]
That was systemd 245. I am not sure what happened, I ended up switching my nodes from DHCP to static IPs. Things were fine after this.
