### ISSUE TITLE
Install `gops` as a dependency in Cilium and into the Cilium Docker container 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1637]
[gops](https://github.com/google/gops) is a useful library which dumps the stack for a running go program. It is quite helpful in debugging deadlock situations, or for analyzing Cilium when it is in an unexpected state. 

- [x] add gops to Cilium repository and launch a goroutine with it upon the startup of the Cilium agent
- [ ] package gops binary into the Cilium docker container so stack traces can be ran in production environments 
- [ ] package gops binary into the Cilium developer VMs
- [ ] gather output from `gops` as part of the log gathering scripts for the build:

```
Commands:
    stack       Prints the stack trace.
    gc          Runs the garbage collector and blocks until successful.
    memstats    Prints the allocation and garbage collection stats.
    version     Prints the Go version used to build the program.
    stats       Prints the vital runtime stats.
    help        Prints this help text.

Profiling commands:
    trace       Runs the runtime tracer for 5 secs and launches "go tool trace".
    pprof-heap  Reads the heap profile and launches "go tool pprof".
    pprof-cpu   Reads the CPU profile and launches "go tool pprof".
```

**Comment by ianvernon** [comment]
Should we add `gops` support to the node monitor and to other cilium plugins (e.g., cilium-docker)?

**Comment by tgraf** [comment]
It looks like `gops` is now part of the Cilium container image, what is left to do here?

**Comment by ianvernon** [comment]
You're right - this can be closed.
