### ISSUE TITLE
make dev-docker-image not giving error with bad cilium_dbg input

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#16385]
## Bug report
while using cilium_dbg with unintentional bad input  to trace datapath, make dev-docker-image seems to be able to build  cilium docker image fine, but after deploying the new custom cilium image, cilium agent logs something like "failing to load compiled BPF...etc", open this report and hope make dev-docker-image can complains BPF build error with bad code input in cilium_dbg

for example with cilium_dbg with bad input ip->protocol (ip does not exist in handle_ipv4, ip4 exist, unintentional copy and paste error)

<pre>
diff --git a/bpf/bpf_host.c b/bpf/bpf_host.c
index 2feaa7053..04548a69d 100644
--- a/bpf/bpf_host.c
+++ b/bpf/bpf_host.c
@@ -534,8 +534,10 @@ handle_ipv4(struct __ctx_buff *ctx, __u32 secctx,
                /* Let through packets to the node-ip so they are processed by
                 * the local ip stack.
                 */
-               if (ep->flags & ENDPOINT_F_HOST)
+               if (ep->flags & ENDPOINT_F_HOST) {
+                       cilium_dbg(ctx, DBG_DECAP, ip->protocol, ipcache_srcid);
                        return CTX_ACT_OK;
+               }
 
                return ipv4_local_delivery(ctx, ETH_HLEN, secctx, ip4, ep,
                                           METRIC_INGRESS, from_host);
</pre>

then make dev-docker-image, the image seems building fine with no error, but after deploying the image and watch cilium agent logs, it will complain unable to load previous compiled  BPF error or something like that

**General Information**

- Cilium version (run `cilium version`)
<pre>
# kubectl  exec -it cilium-sfxp5 -n kube-system -- cilium status 
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20 (v1.20.7) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens192 10.169.72.129 (Direct Routing)]
Cilium:                 Ok   1.10.90 (v1.10.90-c042c05f8)
NodeMonitor:            Listening for events on 4 CPUs with 64x4096 of shared memory
IPAM:                   IPv4: 4/254 allocated from 10.0.1.0/24, 
BandwidthManager:       EDT with BPF   [ens192]
Host Routing:           BPF
Masquerading:           BPF   [ens192]   10.0.1.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:      30/30 healthy
Proxy Status:           No managed proxy redirect
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 61.21   Metrics: Disabled
Encryption:             Disabled
Cluster health:               Warning   cilium-health daemon unreachable

</pre>

- Kernel version (run `uname -a`)
Linux cilium-master 5.12.0-051200-generic

- Orchestration system version in use (e.g. `kubectl version`, ...)
# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)

- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1, add cilium_dbg with bad input in handle_ipv4 in bpf/bpf_host.c
2  make dev-docker-image
3, deploy the new build cilium image in k8s

**Comment by pchaigno** [comment]
This is what `make -C bpf build_all` is for. It should complain with a compilation error if the code is incorrect.

**Comment by vincentmli** [comment]
@pchaigno thanks, that is what I am looking for then
