### ISSUE TITLE
Add additional health metrics to the Prometheus exporter

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#16393]
## Proposal / RFE

The [form3tech-oss/extra-cilium-metrics](https://github.com/form3tech-oss/extra-cilium-metrics) project collects a few additional useful and Cilium metrics around node connectivity and cluster mesh and seem quite useful to Cilium cluster operators.

The metrics are built on top of the Cilium API (`/healthz` and `cilium-health` specifically) and do not contain any workload specific information and therefore could easily be upstreamed. This allows all users to profit from these metrics without having to maintain a side-car.

List of metrics:

> 
> | Name                                             | Description                                                                                                                     |
> |--------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------|
> | `remote_cluster_etcd_has_quorum`                 | Whether the remote cluster's 'cilium-etcd' cluster has quorum                                                                   |
> | `remote_cluster_etcd_total_observed_leases`      | The total number of observed lease IDs on the remote cluster's 'cilium-etcd' cluster belonging to the current Cilium agent      |
> | `remote_cluster_etcd_total_observed_lock_leases` | The total number of observed lock lease IDs on the remote cluster's 'cilium-etcd' cluster belonging to the current Cilium agent |
> | `remote_cluster_last_failure_timestamp`          | The timestamp of the last failure of the remote cluster                                                                         |
> | `remote_cluster_readiness_status`                | The readiness status of the remote cluster                                                                                      |
> | `remote_cluster_total_failures`                  | The total number of failures related to the remote cluster                                                                      |
> | `remote_cluster_total_nodes`                     | The total number of nodes in the remote cluster                                                                                 |
> | `total_global_services`                          | The total number of global services in the cluster mesh                                                                         |
> | `total_remote_clusters`                          | The total number of remote clusters meshed with the local cluster                                                               |
> | `latency`                                        | The last observed latency (in nanoseconds) between the current Cilium agent and other Cilium agents                             |
> | `status`                                         | The last observed status of the connectivity between the current Cilium agent and other Cilium agents                           |

**Comment by sayboras** [comment]
let me give it a crack on this issue  :)
