### ISSUE TITLE
Error should be info: `local-redirect service exists for frontend, skip update for svc lrp-demo-service`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#16400]
@aditighag confirmed that the following error message should be info level: 
```
level=error msg="Error while inserting service in LB map" error="local-redirect service exists for frontend {{10.123.250.188 {UDP 69} 0} 0}, skip update for svc lrp-demo-service" k8sNamespace=default k8sSvcName=lrp-demo-service subsys=k8s-watcher
```

**Comment by geyslan** [comment]
Something like this? If yes, please assign this to me.

```diff
❯ git diff
modified: pkg/redirectpolicy/manager.go

@@ -526,7 +526,7 @@ func (rpm *Manager) upsertService(config *LRPConfig, frontendMapping *feMapping)
    }
 
    if _, _, err := rpm.svcManager.UpsertService(p); err != nil {
-       log.WithError(err).Error("Error while inserting service in LB map")
+       log.WithError(err).Info("Error while inserting service in LB map")
    }
 }
```

**Comment by aditighag** [comment]
It's not as simple as converting the log level to info/debug. The same code path (`UpsertService`) is called during CLI invocation.

**Comment by geyslan** [comment]
@aditighag I see.

You mean there should be different log levels based on code path? CLI invocation, core invocation...

Could you please elaborate? Thanks.

**Comment by geyslan** [comment]
@aditighag Thanks for contacting. Unfortunately, I won't be able to continue with this issue.

**Comment by mhulscher** [comment]
Wanted to give a +1 to this issue. This particular error frequently triggers my prometheus alert, effectively rendering it useless :(

```
rate(cilium_errors_warnings_total{job="cilium-agent",level="error"}[5m]) > 0
```

log:
```
cilium-vljzk cilium-agent level=error msg="Error while inserting service in LB map" error="local-redirect service exists for frontend {{172.20.0.10 {UDP 53} 0} 0}, skip update for svc kube-dns" k8sNamespace=kube-system k8sSvcName=kube-dns subsys=k8s-watcher
```

**Comment by tbalthazar** [comment]
Here's a proposed fix, please let me know if that makes sense:
https://github.com/cilium/cilium/pull/21898
