### ISSUE TITLE
Cilium

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#16449]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. instruction 1
2. instruction 2

**Comment by juliuss86** [comment]
Exit
