### ISSUE TITLE
helm: Values files have bad punctuation

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/cilium#16461]
As reported in [this PR](https://github.com/cilium/cilium/pull/16238#discussion_r644212820) helm values description comments are often missing correct punctuation. This wouldn't necessarily be a problem, except it is inconsistent. Some phrases have punctuation and some don't. Garners Modern English Usage recommends that phrases in bullet points or lists have punctuation<sup>1</sup>.

<sup>1</sup>Garner, B. A. (2009). Punctuation B.4 In _Garner's Modern English Usage_. New York: Oxford University Press.

**Comment by joestringer** [comment]
Do you know of any tools that could lint this? If we don't have automated tooling that tells you how things must be formatted, then we will always reintroduce punctuation that doesn't follow this style.

**Comment by joestringer** [comment]
@nathanjsweet do you plan to work on this? I'm guessing not, given the age of the issue. I've marked it as 'help-wanted' for now.

**Comment by nathanjsweet** [comment]
To add to this it would be nice to have some kind of linter to ensure that the inconsistency is not reintroduced.
