### ISSUE TITLE
Remove local redirect policy entry and potentially restore original clusterIP service entry sooner upon last local backend delete

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#16463]
## Proposal / RFE

**Is your feature request related to a problem?**
Currently, nodelocaldns deployment with Cilium utilizes LRP to redirect DNS traffic to the local `dns-cache` pods. When the local `dns-cache` pods are down (e.g., due to rolling upgrade), there might be a disruption in DNS queries because `cilium-agent` would only restore the original DNS service upon the local pod's delete event. The delay from when local `dns-cache` is gone to when cilium-agent restores the DNS service seems to be the root problem here.

**Describe the solution you'd like**
Since LRP reacts on "local" pods, maybe we could hook into local CNI pod events (e.g., delete) and try to restore the original service (from `svcCache`) sooner.

Ofc I'm open to other possible solutions too :)

**Comment by Weil0ng** [comment]
Had discussion with @aditighag @aanm offline over slack, creating an issue to track the discussion more formally here.

**Comment by Weil0ng** [comment]
re @aanm , we would still treat the controlplan's svc info as the ground truth and always restore to that, so even if the original clusterIP is invalid (and some new clusterIP is allocated), we should be able to pick up that too? I'm a bit confused why is that an issue?

**Comment by aditighag** [comment]
Thanks for filing the issue. 
Title is confusing. LRP is a control-plane abstraction for users to configure node-local redirection. The LRP manager behind the scenes monitors relevant services/pods to set up the networking/datapath. Also, I'm looking for more details in the proposal to understand whether it's feasible or not. :)

**Comment by aditighag** [comment]
I'm also wondering if you have any data around latency incurred in different LRP orchestration stages? It'll be good to attribute delays to watcher related events vs local-redirect service removal and original service restore window, etc.

**Comment by Weil0ng** [comment]
> I'm also wondering if you have any data around latency incurred in different LRP orchestration stages? It'll be good to attribute delays to watcher related events vs local-redirect service removal and original service restore window, etc.

good point, I'll do some profiling and post back here.

Also changed the title to be a bit more precise.

My thought is that we don't change how LRP manager currently handles restoration, but we try to invoke the restoration earlier upon last local backend delete, then when agent gets the event from control plane, it'll try to restore it again and fail (but it's okay since it is already restored). We can control this early restoration with a flag or something so that it can be switched on in scenarios where it is required to not have an outdated LRP policy in place (like in the DNS case).

**Comment by aanm** [comment]
> > I'm also wondering if you have any data around latency incurred in different LRP orchestration stages? It'll be good to attribute delays to watcher related events vs local-redirect service removal and original service restore window, etc.
> 
> good point, I'll do some profiling and post back here.
> 
> Also changed the title to be a bit more precise.
> 
> My thought is that we don't change how LRP manager currently handles restoration, but we try to invoke the restoration earlier upon last local backend delete, then when agent gets the event from control plane, it'll try to restore it again and fail (but it's okay since it is already restored). We can control this early restoration with a flag or something so that it can be switched on in scenarios where it is required to not have an outdated LRP policy in place (like in the DNS case).

Removing LRP out of the picture, isn't this a problem that could happen with any application backend that is behind a service?

**Comment by Weil0ng** [comment]
> Removing LRP out of the picture, isn't this a problem that could happen with any application backend that is behind a service?

Hmm...good point...maybe the proper solution here is to add a controller that monitors dns-cache and manipulates the svc entry directly as a special case?

**Comment by Weil0ng** [comment]
Will send out PR soon.
