### ISSUE TITLE
Cilium v1.10.0: kubernetes "quick-install.yml" file removed/missing

### ISSUE THREAD

**Issue by ntx-ben** [cilium/cilium#16498]
I've been using the `quick-install.yaml` as a foundation for my work's `kustomize` custom manifests. Now I see that for version `v1.10.0`, this file is now missing or has been removed completely (previously located in `install/kubernetes`)?

I have severe convulsions when using Helm. Please bring back the very simple `quick-install.yaml` file? Or even better, provide a `kustomize` base file?

Much appreciated.

EDIT
----

I can see it was removed here: https://github.com/cilium/cilium/commit/0665067a3a7e41557f082d8ed1d3c35c5a6a0be6#diff-b9728fac5e1ddbf6dcf285d75651a60a0bbee497ed9c1ccc50297bff8b80b828

I'm automating the deployment of Cilium during a custom installation process. Is there any way to preemptively generate the static `quick-install.yaml` file from the CLI? Helm is not an option.

**Comment by aanm** [comment]
Hi, the `quick-install.yaml` can be generated by `helm template cilium cilium --namespace=kube-system`.

> Is there any way to preemptively generate the static quick-install.yaml file from the CLI?

Not currently but PRs are welcome.

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
