### ISSUE TITLE
Proposal: Write Prometheus exporter

### ISSUE THREAD

**Issue by tsenart** [cilium/cilium#165]
Write a Prometheus exporter that integrates with `cilium monitor` and exposes a set of Cilium metrics to be scraped by a Prometheus server.

**Comment by tgraf** [comment]
Both events exported by the cilium monitor facility as well as lxcinfo, ctmap, policymap and lbmap will be interesting. You can dump those already with:

```
cilium endpoint ct dump <ID>
cilium endpoint policy dump <ID>
cilium endpoint dump <ID>
cilium lb dump
```

**Comment by tsenart** [comment]
Great. Also, for reference, I think it's better to have an external Prometheus exporter (individual process) instead of directly instrumenting the cilium daemon so that we don't couple it too much with a single monitoring technology.

**Comment by raybejjani** [comment]
Addressed by
https://github.com/cilium/cilium/pull/2127
https://github.com/cilium/cilium/pull/2192
https://github.com/cilium/cilium/pull/2236
