### ISSUE TITLE
Getting started guides in v1.10 CLI-based docs install v1.9

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#16512]
The getting started guides for the default (CLI-based) installation in the v1.10 documentation recommend to run:
```
cilium install
```
That command will install v1.9.x, not v1.10.

Instead, we should pass a version explicitly:
```
cilium install --version v1.10.0
```

**Comment by joestringer** [comment]
It should be possible to use parsed-literals to pick up the current version and fix this up.

**Comment by ti-mo** [comment]
Isn't it intended behaviour for `cilium install` to pick the latest version it knows about? If the user is running a cilium-cli that's too old with a newer version of the docs, it will probably throw an error or result in an unhealthy deployment.

**Comment by pchaigno** [comment]
That's the intended default behavior, but if someone is reading the v1.11 installation guide, I think the commands provided should install v1.11, not v1.13.

**Comment by aanm** [comment]
Fixed with https://github.com/cilium/cilium/pull/26934
