### ISSUE TITLE
Vagrant/CI: Support cgroup v2 and systemd cgroup driver in dev VM and CI test

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#16528]
Currently, the dev VM comes up with Docker as the default container runtime, and cgroupfs as the cgroup driver for kubelet. The default cgroup driver for Docker is `systemd` on v2 and `cgroupfs` on v1.  Additionally, Kubernetes has updated the default cgroup driver for kubelet to be `systemd` [1].

[1] https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/#configuring-the-kubelet-cgroup-driver

**Comment by brb** [comment]
In addition, could we completely disable cgroup v1 if a VM runs k8s >= 1.20?

**Comment by aditighag** [comment]
CI is running on kind with cgroup v2 enabled.
