### ISSUE TITLE
datapath: change metric of route to cilium_host to be < 256

### ISSUE THREAD

**Issue by Frankkkkk** [cilium/cilium#16539]
## Proposal / RFE

Our use-case of cilium is very simple: each node announces some ranges:

- POD range
- service range
- externalIP range

This is done using the FRR router. Ranges are propagated following a simple route map:
```
route-map map-bgp-announce permit 10
 match interface lo
```
In this case, every IP (or range, if the IP is /110 instead of /128 for example) in the `lo` interface is announced.

However, by adding an IP to an interface, the kernel automatically adds a route to it with a default metric of `IP6_RT_PRIO_ADDRCONF = 256`.

Then, when cilium adds the route to the cilium_host device, it doesn't specify a metric so the default one is used (`IP6_RT_PRIO_USER = 1024`).

The consequence is that the packets don't go to the cilium_host iface and thus the connectivity doesn't work.

A workaround we use until now was to have a simple daemonset which did the following:
```bash
while true; do
  ip -6 r del $cni_pod_range dev lo || true
  sleep 1h
done
```
And as you can see it's not very sexy.

Would it be possible to change the metric when adding a route to the cilium_host interface (or at least make it changeable) ? The change seems quite straightforward (https://github.com/cilium/cilium/blob/master/pkg/datapath/linux/node.go#L369). What about making the value as a param ?

What do you think ?

Thanks and cheers

**Comment by brb** [comment]
@Frankkkkk Sounds reasonable what you proposed. Would you mind opening PR for this?

**Comment by Frankkkkk** [comment]
Hi Martynas,

Thanks for your reply.
I'm actually on holidays, but I'll happily submit a PR next week or the one after :-)

Cheers !

On September 28, 2021 3:35:31 PM GMT+02:00, Martynas Pumputis ***@***.***> wrote:
***@***.*** Sounds reasonable what you proposed. Would you mind opening PR for this?
