### ISSUE TITLE
Upgrade 1.9.4->1.9.8 unstable on kernel 5.10.4

### ISSUE THREAD

**Issue by briantopping** [cilium/cilium#16541]
## Bug report

**General Information**

- Cilium version: 1.9.8
- Kernel version 5.10.4
- Orchestration system version in use: Kube v1.19.8
- Generate and upload a system zip: [here](https://drive.google.com/file/d/1zFJLDxyMfvygOB0xYTy-UcXNnnCF_2Xz/view?usp=sharing)

**How to reproduce the issue**

Did a `helm upgrade` of Cilium, accidentally to v1.10 to start with. Saw problems, finally uninstalled completely and reinstalled with v1.9.8, problems persisted, including locking up network access for the entire node (including SSH) when using cleanup (required warm boot of each node to recover). In [conversation](https://cilium.slack.com/archives/C53TG4J4R/p1623736006336300) with @joestringer, realized I hadn't tried a clean install with v1.9.4 and the cluster started restoring immediately. Don't have any remaining artifacts of the problem other than the system zip linked here.

**Comment by pchaigno** [comment]
You were hitting https://github.com/cilium/cilium/issues/14726 on v1.9.8. We haven't backported the fix for that issue to v1.9 yet.

**Comment by briantopping** [comment]
Got it, thank you. I believe I am running in this configuration due to #14563.

**Comment by pchaigno** [comment]
The fix for this complexity issue has been backported to v1.9 and will be released as part of v1.9.9.

**Comment by briantopping** [comment]
Thanks Paul. Could this be linked to a 1.9.9 meta-issue instead of closing it? I can close it when 1.9.9 comes out if not.

**Comment by pchaigno** [comment]
We can keep it opened until v1.9.9 is out if you prefer.

**Comment by briantopping** [comment]
I don’t know if I would have recognized the problem in an issue before losing some days to it, but if it’s closed, it won’t help someone who does recognize it before they get into a similar situation.

**Comment by joestringer** [comment]
v1.9.9 is now released, please try out the new release and let us know if you continue to experience problems.
