### ISSUE TITLE
Helm template with serviceMonitor enabled fails

### ISSUE THREAD

**Issue by splushii** [cilium/cilium#16552]
## Bug report

**General Information**

- Cilium version: 1.10.0

Using `helm template` with `serviceMonitor` enabled fails due to the validation logic at https://github.com/cilium/cilium/blob/v1.10.0/install/kubernetes/cilium/templates/validate.yaml#L15.

The way I understand it, `helm install ...` and `helm upgrade ...` works as they speak with the k8s control plane and can check if the CRD is present, but `helm template ...` does not.

**How to reproduce the issue**

```shell
helm template cilium/cilium --version 1.10.0 --set prometheus.enabled=true --set prometheus.serviceMonitor.enabled=true
```
```shell
Error: template: cilium/templates/validate.yaml:16:9: executing "cilium/templates/validate.yaml" at <fail "Service Monitor requires monitoring.coreos.com/v1 CRDs. Please refer to https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml">: error calling fail: Service Monitor requires monitoring.coreos.com/v1 CRDs. Please refer to https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

Use --debug flag to render out invalid YAML
```

**Comment by sergeyshevch** [comment]
Also faced with this when installed cilium with ArgoCD. I guess we need a flag to disable such validation

**Comment by ksaio** [comment]
Also faced this with ArgoCD

**Comment by gandro** [comment]
Please note: When using `helm template, it is **highly** recommended you set `--kube-version` and `--api-versions` with the values matching your target Kubernetes cluster. Helm charts such as ours often conditionally enable certain Kubernetes features based on their availability (beta vs stable) on the target cluster.

By specifying `--api-versions=monitoring.coreos.com/v1` you should be able to pass validation with `helm template.

**Comment by aanm** [comment]
Solution has been provided [here](https://github.com/cilium/cilium/issues/16552#issuecomment-998037683) closing the GH issue. Feel free to open a new GitHub issue if you are still facing issues. Thank you
