### ISSUE TITLE
CI: `go: RLock /cilium/go.mod: no locks available` (e.g. K8sVerifier Runs the kernel verifier against Cilium's BPF datapath)

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#16551]
## CI failure

Various `make` commands in CI are failing due to an NFS error: `go: RLock /cilium/go.mod: no locks available`. 

For example:
```
Expected command: kubectl exec -n default test-verifier -- make -C tools/maptool/ 
To succeed, but it failed:
Exitcode: 2 
Err: exit status 2
Stdout:
 	 make: Entering directory '/cilium/tools/maptool'
	 CGO_ENABLED=1  go build  -mod=vendor -ldflags ' -X "github.com/cilium/cilium/pkg/version.ciliumVersion=1.10.90 " -s -w -X "github.com/cilium/cilium/pkg/envoy.RequiredEnvoyVersionSHA=e83275091139101e7ff29284ef35c56f4cd6bfc3" -X "github.com/cilium/cilium/pkg/datapath/loader.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" ' -tags=osusergo  -o maptool
	 make: Leaving directory '/cilium/tools/maptool'
	 
Stderr:
 	 /bin/bash: git: command not found
	 /bin/bash: git: command not found
	 go: RLock /cilium/go.mod: no locks available
	 make: *** [Makefile:14: maptool] Error 1
	 command terminated with exit code 2
```

This can also happen during provisioning, e.g. here:
https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4989/console
```
runtime: go: RLock /home/vagrant/go/src/github.com/cilium/cilium/go.mod: no locks available
```

Observed on v1.8, v1.10 and master branch so far. Likely unrelated to a specific code change, as I have observed this on PRs even without rebasing.

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-5.4/372/
https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4989/console
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.18-kernel-4.9/1668/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-5.4/378/

Slack thread: https://cilium.slack.com/archives/C7PE7V806/p1623750712181700

**Comment by gandro** [comment]
This does not seem to occur anymore and we also have a mitigation in place now.

**Comment by aditighag** [comment]
Hit this in a v1.9 backport PR - https://jenkins.cilium.io/job/Cilium-PR-K8s-1.15-kernel-4.9/289/testReport/junit/Suite-k8s-1/15/K8sVerifier_Runs_the_kernel_verifier_against_Cilium_s_BPF_datapath/

**Comment by aditighag** [comment]
>we also have a mitigation in place now.

@gandro Can you add a link to the PR? Maybe we'll need to backport it to v1.9 branch.

**Comment by gandro** [comment]
> > we also have a mitigation in place now.
> 
> @gandro Can you add a link to the PR? Maybe we'll need to backport it to v1.9 branch.

Yes; https://github.com/cilium/cilium/pull/16554 - let's mark it for backport
