### ISSUE TITLE
During deployment upgrade with high max surge, some pods are stuck in ContainerCreating state

### ISSUE THREAD

**Issue by ybialik** [cilium/cilium#16550]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
# cilium version
Client: 1.9.8 3fcfff7 2021-05-28T02:03:28+02:00 go version go1.15.12 linux/amd64
Daemon: 1.9.8 3fcfff7 2021-05-28T02:03:28+02:00 go version go1.15.12 linux/amd64

- Kernel version (run `uname -a`)
```
# uname -a
Linux ip-10-80-179-178.ec2.internal 4.14.232-176.381.amzn2.x86_64 #1 SMP Wed May 19 00:31:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip ---- attached
I added logs for one node with cilium-8bmkj which is doing the issue currently (it really random on which pod it is happening)

[cilium-sysdump-20210616-103544.zip](https://github.com/cilium/cilium/files/6661248/cilium-sysdump-20210616-103544.zip)
**How to reproduce the issue**

1. Install cilium using the following helm command

helm install cilium cilium/cilium --version 1.9.8 \
  --namespace kube-system \
  --set egressMasqueradeInterfaces=eth0 \
  --set nodeinit.enabled=true

2. Install a deployment with around 100 pods with max surge of 50% and max unavailable of 25%
3. change the image tag of the deployment to trigger pods replacement

**Comment by pchaigno** [comment]
I'm seeing the following error a lot in logs. Not sure yet what could cause this.
```
Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded
```

> Install a deployment with around 100 pods with max surge of 50% and max unavailable of 25%

Any chance you could share such a deployment?

**Comment by ybialik** [comment]
sure,some values were changed to placeholders.
the deployment is using the commonChart as a library chart.
[tempcase.zip](https://github.com/cilium/cilium/files/6661591/tempcase.zip)

**Comment by ybialik** [comment]
Issue persists even after upgrading to 1.10.0

**Comment by ybialik** [comment]
cilium status command give this output:
controller bpf-map-sync-cilium_ipcache is failing since 3s (6333x): 8832 map sync errors

**Comment by ybialik** [comment]
cilium connectivity give this output:
[cluster-arn] Waiting for Cilium pod kube-system/cilium-t9965 to have all the pod IPs in eBPF ipcache...

Error: Connectivity test failed: timeout reached waiting for pod IDs in ipcache of Cilium pod kube-system/cilium-t9965

**Comment by ybialik** [comment]
![image](https://user-images.githubusercontent.com/81084950/122913422-12c3a700-d362-11eb-9ecc-de8a23a2a71a.png)
![image](https://user-images.githubusercontent.com/81084950/122913436-16efc480-d362-11eb-9b7b-c8e105f48cb8.png)

**Comment by ybialik** [comment]
@pchaigno  what else can I do to assist with troubleshooting this issue?

**Comment by pchaigno** [comment]
https://github.com/cilium/cilium/issues/16375 might be the same root cause. I found the same `proxy state changes failed` message in some of the logs and it shares some of the symptoms.

**Comment by ybialik** [comment]
@pchaigno thanks, I will keep checking the other thread as well

**Comment by ybialik** [comment]
@pchaigno I upgraded to 1.10.2 and now I have a clearer message in the kubectl describe pod:

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ede16d4f3c9626b5adc140c16e103c2ac03d6f9b0e62db5d9f93fef0e9480ab7" network for pod "production-stateless-trail-writer-service-aws-775687f9b5-2g2wf": networkPlugin cni failed to set up pod "production-stateless-trail-writer-service-aws-775687f9b5-2g2wf_production-services" network: Unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests

**Comment by christarazi** [comment]
@ybialik 429 error code means rate limiting has kicked in. This is expected with such a high surge of pods. You can tune these parameters via https://docs.cilium.io/en/v1.10/configuration/api-rate-limiting/#id1

**Comment by ybialik** [comment]
Thanks @christarazi , we already played with the limits without any success.
we did see major improvements in 1.10.3 on our staging cluster. I hope to upgrade the version on production cluster this Sunday and see if it fixes the issue for good.

**Comment by christarazi** [comment]
@ybialik Sounds good. Please close the issue if you no longer see this or edit the issue with the most up-to-date information (after your upgrade).

**Comment by ravkishu** [comment]
I wanted to add these points here: Initially, when I just used `helm upgrade` with appropriate flags I've ran into the same problem above i.e, many pods were going in `ContainerCreating` or `CrashLoopBackOff` status including `cilium-xxxx` 

The correct way to upgrade Cilium from 1.9.x to 1.10.3 is
``` shell
helm upgrade cilium cilium/cilium --version 1.10.3 \
  --namespace=kube-system \
  --set upgradeCompatibility=1.9
```
Then check the running status via `cilium status`

* Also kindly note I've faced errors when I've upgraded using `kubectl` so I highly suggest going with `helm`

Reference used: https://docs.cilium.io/en/stable/operations/upgrade

Hope this will help you to upgrade to the latest release @ybialik 🤞 
cc: @pchaigno

**Comment by ybialik** [comment]
After upgrading to the latest release I can verify that for the last 2-3 weeks we didn't get the issue so it was resolved. 
Thank you all for the hard work.
