### ISSUE TITLE
Reusing IP in the event of CEP propagation delay might result in inconsistent ipcache

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#16565]
As we discussed in today's dev meeting, although we have not seen this yet, but the propagation delay of `CEP` might cause some complications if IP is reused. Summarizing below:

Consider the following event sequence:

- Pod A is created with IP `1.2.3.4` and security id 1234
- local agent creates and sync `CEP` with apiserver
- remote agents got `CEP` via watch
- remote agent propagates ipcache with entry `1.2.3.4 -> 1234`
- Pod A is deleted and another Pod B is created reusing IP `1.2.3.4` but with identity id 4321
- local agent sends `DELETE` and `CERATE` events out

Problem 1: before remote node got new `CEP` via `CREATE` or remove old ipcache entry upon `DELETE`, there could be false-allows if a netpol is whitelisting identity 1234, not Pod B is falsely whitelisted because remote still has the entry `1.2.3.4 -> 1234`.

- remote agent got `CREATE` first, overwriting its ipcache with entry `1.2.3.4 -> 4321`
- remote agent got `DELETE`, removing entry with key `1.2.3.4` from ipcache

Problem 2: If live above `DELETE` arrives after `CREATE`, remote ipcache will remove entry for Pod B which it should not.

The above sequence could happen in theory today, but it might become more noticeable with [CFP-2021-08](https://docs.google.com/document/d/1DCDrgydIrLHID6k0sP1MMiOjRu5Q03nAjwpAsRVfkQc/edit#heading=h.5mwz58y9syps), if `DELETE` is batched for another, say, 60s in the operator. 

A possible mitigation to problem 2 is to be smart about it in the operator and turn `DELETE` into an `UPDATE` event if we find an IP is reused while batching `CEP` `DELETE`.

**Comment by aanm** [comment]
Thanks for opening the GH issue.

I don't think Problem 2 is a problem since the `DELETE` would, or at least should, always be sent before a `CREATE`. @Weil0ng I think this should be a comment of https://github.com/cilium/cilium/issues/16302 since it's essential the same problem.

**Comment by Weil0ng** [comment]
> I don't think Problem 2 is a problem since the `DELETE` would, or at least should, always be sent before a `CREATE`. 

True, but AFAIK apiserver doesn't guarantee  ordering of delivering these events to listener, so remote node might still get `CREATE` before `DELETE`.

**Comment by Weil0ng** [comment]
Can the agent be smart about this and only remove entry from ipcache if ip is only referenced to by the CEP that is being removed? Agent should have information about all CEP and should be able to tell whether there's another CEP with the same ip?

**Comment by Weil0ng** [comment]
@aanm Thoughts? I think this relates to the CEB implementation and I'd like to make sure we understand this correctly :)

**Comment by aanm** [comment]
> Can the agent be smart about this and only remove entry from ipcache if ip is only referenced to by the CEP that is being removed?

@Weil0ng that sounds like a great proposal. The agent already stores some pod metadata in https://github.com/cilium/cilium/blob/a8e3fa283cf40b330035265bf83d63800b296bcf/pkg/ipcache/ipcache.go#L66

**Comment by Weil0ng** [comment]
> @Weil0ng that sounds like a great proposal. The agent already stores some pod metadata in
> 
> https://github.com/cilium/cilium/blob/a8e3fa283cf40b330035265bf83d63800b296bcf/pkg/ipcache/ipcache.go#L66

Ah nice!

Without digging the code, I guess this map will also be updated with `Pod B`'s meta when the agent got the `CREATE` event first? So essentially when it got the `DELETE` (for `Pod A`) later, it should be able to lookup in this map and compare `ipToK8sMetadata[1.2.3.4]` with `Pod A`'s meta and see that they are different, which is an indicator that this IP now is referenced by another pod.

**Comment by aanm** [comment]
Correct
