### ISSUE TITLE
vendor/miekg/dns directory is not synced with cilium/dns repo

### ISSUE THREAD

**Issue by asgarciap** [cilium/cilium#16587]
Why aren't the changes made to the [miekg/dns](https://github.com/cilium/cilium/commit/4eb97b91843981b999f39e4acebf59681571f91f#diff-82e6c3eba50ac56d30e63f9efa5a2f60a7365b3ccc83511ce38f425adcd52237) library in the vendor directory pushed into the [github.com/cilium/dns](https://github.com/cilium/dns) repo?

**Comment by aanm** [comment]
Hi @asgarciap, they are available in https://github.com/cilium/dns/commits/udp-interface-1.1.8

**Comment by christarazi** [comment]
@aanm @jrajahalme @aspsk Are there any plans to upstream the patches to upstream?
