### ISSUE TITLE
gke: Not possible to detach getpeername{4,6} BPF progs on <= 5.4.89+ kernel

### ISSUE THREAD

**Issue by brb** [cilium/cilium#16597]
The backport \[1\] of `"bpf: Add get{peer, sock}name attach types for sock_addr"` didn't append the new attach types to `bpf_prog_detach()` which results in a failure when detaching a prog of any of the types. E.g.:

    bpf(BPF_PROG_DETACH, {target_fd=3</run/cilium/cgroupv2>,
        attach_type=0x1d /* BPF_??? */}, 120) = -1 EINVAL (Invalid argument)

This became visible when we disabled the kube-proxy-replacement feature on Cilium which was running on GKE COS 5.4.

\[1\]: https://cos.googlesource.com/third_party/kernel/+/b6b28282e02f4f816346136a94de601bacf91a17

A patch has been provided to the Google kernel team.

**Comment by brb** [comment]
If you get hit by that, AFAIK the only solution is to reboot the node.

**Comment by brb** [comment]
Just tested - the issue is still present :disappointed:

**Comment by joestringer** [comment]
@jtaleric reported that this is still present today.
