### ISSUE TITLE
Synchronise event & manual sync of container events

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1662]
The manual periodic container event runtime must be synchronized with the event handler to ensure that we maintain correct ordering of process events.

```
func syncWithRuntime() {
        var wg sync.WaitGroup
```

Code marked with `FIXME GH-1662`

**Comment by ianvernon** [comment]
There are changes in the client API in later versions of Moby / Docker that change the `Events` function to return a channel of events: https://github.com/moby/moby/commit/d6bd79c18f5ab5dbdaa472ccd921ad2858117507

**Comment by raybejjani** [comment]
Closed by https://github.com/cilium/cilium/pull/1691
