### ISSUE TITLE
Cilium iptables rules are not reconciled

### ISSUE THREAD

**Issue by mskrocki** [cilium/cilium#16644]
## Bug report
Cilium iptables rules are not reconciled when any of them are flushed. Real-life example is RPM-based system (e.g CentOS 8) with firewalld enabled, where any change to firewalld flushes the iptables rules. kube-proxy properly re-installs its rules, for cilium I have to restart the agent's Pod on that node.

**General Information**

- Cilium version 1.9

**How to reproduce the issue**

1. install cilium with `--install-iptables-rules` enabled
2. flush iptables rules (or restart firewalld on RPM-based OS)

**Comment by brb** [comment]
We had a PR for this https://github.com/cilium/cilium/pull/9803, but we haven't merged it. The motivation for not merging was that Cilium won't need any iptables rules in the nearest future.

**Comment by pengfeiopen** [comment]
when you ( restart firewalld), Cilium iptables rules are clean
