### ISSUE TITLE
Cilium reports "Found incomplete restore directory /var/run/cilium/state/3123_next_fail. Removing it..."

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#16658]
Seen on multiple PR jobs for current dev cycle (v1.11):

Example:
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/840/testReport/junit/Suite-k8s-1/21/K8sConformance_Portmap_Chaining_Check_connectivity_check_compliance_with_portmap_chaining/
[1ed1a3b5_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.zip](https://github.com/cilium/cilium/files/6717909/1ed1a3b5_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.zip)

```
Top 2 errors/warnings:
Found incomplete restore directory /var/run/cilium/state/3123_next_fail. Removing it...
Found incomplete restore directory /var/run/cilium/state/274_next_fail. Removing it...
```

When there is an endpoint `_next_fail` state directory on the filesystem, this indicates that during the previous cilium-agent run, Cilium was attempting to regenerate the BPF progs/map content for the endpoint, but this failed so it stored the failure state to these directories so that we could subsequently investigate the failure.

If we're removing it, this means that we're glossing over some previous failure during the prior cilium-agent run (possibly from the previous test).

**Comment by pchaigno** [comment]
Do we want to add this warning message to the list of bad log messages? That would fail the tests and maybe help us get a better picture of the present issue?

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
