### ISSUE TITLE
CI: Suite-k8s-1.21.K8sFQDNTest Validate that multiple specs are working correctly

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#16659]
## CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Can't connect to to a valid target when it should work
Expected command: kubectl exec -n default app2-58757b7dd5-nrwln -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 --retry 5 http://vagrant-cache.ci.cilium.io -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000019()', Connect: '0.000000',Transfer '0.000000', total '5.002315'
Stderr:
 	 command terminated with exit code 28
```

DNS resolution to external fqdns are tricky to handle in tests since the failures could be transient. 

[eedec955_K8sFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip](https://github.com/cilium/cilium/files/6718076/eedec955_K8sFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip)

**Comment by joestringer** [comment]
I found that the coredns pod in this environment is configured with endpoint-routes while the rest of the endpoints were not, which suggests a link to #16717 (if not the same root cause). I used this technique: https://github.com/cilium/cilium/issues/16717#issuecomment-871794749

**Comment by pchaigno** [comment]
According to [the CI dashboard](https://datastudio.google.com/s/jmn3FXS9X04), could be the same root cause as https://github.com/cilium/cilium/issues/16713#issuecomment-873293963, since it started failing more often around the same time (June 24th).

![image](https://user-images.githubusercontent.com/1764210/124443905-5e247f00-dd7e-11eb-80ea-2539f2e6d017.png)
