### ISSUE TITLE
[v1.9] CI: K8sServicesTest Checks ClusterIP Connectivity Checks service accessing itself (hairpin flow)

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#16680]
```
/home/jenkins/workspace/Cilium-PR-K8s-1.12-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Request from echo-5dc44bffc6-5j8n6 pod to service http://10.104.86.116/ failed
Expected command: kubectl exec -n default echo-5dc44bffc6-5j8n6 -- /bin/bash -c 'fails=""; id=$RANDOM; for i in $(seq 1 10); do if curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://10.104.86.116/ -H "User-Agent: cilium-test-$id/$i"; then echo "Test round $id/$i exit code: $?"; else fails=$fails:$id/$i=$?; fi; done; if [ -n "$fails" ]; then echo "failed: $fails"; fi; cnt="${fails//[^:]}"; if [ ${#cnt} -gt 0 ]; then exit 42; fi' 
To succeed, but it failed:
Exitcode: 42 
Err: exit status 42
```

Seen on https://github.com/cilium/cilium/pull/16642: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1750

It seems that the 4th out of 10 `curl` invocations failed with error code `28` (operation timeout):

```
failed: :11985/4=28
```

[test_results_Cilium-PR-K8s-1.12-net-next_1750_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/6731825/test_results_Cilium-PR-K8s-1.12-net-next_1750_BDD-Test-PR.zip)

**Comment by jrajahalme** [comment]
7 out of 10 test runs failed on https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.9/101/testReport/junit/Suite-k8s-1/22/K8sServicesTest_Checks_ClusterIP_Connectivity_Checks_service_accessing_itself__hairpin_flow_/:
```
failed: :29808/1=28:29808/2=28:29808/3=28:29808/6=28:29808/7=28:29808/8=28:29808/10=28 
```

It's possible that it is those 7 that selected the source echo pod as destinations, and those all failed. Unfortunately there is no logs on the echo pods on incoming requests, nor are there flow logs to check out which backend was selected for which connection :-(

**Comment by jrajahalme** [comment]
Still happening on #17191, on k8s 1.22 kernel 4.9 pipeline only.

**Comment by brb** [comment]
It's yet another pod2pod (bpf_sock xlation) issue. The recent K8sServices refactoring might have resolved it. Let's close it.
