### ISSUE TITLE
docs: Obsolete targets for building runtime and builder images

### ISSUE THREAD

**Issue by brb** [cilium/cilium#16726]
It is no longer possible to build `cilium-runtime` image  with `make docker-image-runtime`, as it is no longer a valid target. The obsolete target is documented in https://docs.cilium.io/en/latest/contributing/development/images/, and  the PR which changed this - https://github.com/cilium/cilium/pull/15023.

Instead of making everyone to read `build-image.sh` and friends, we should fix the docs.

**Comment by aanm** [comment]
@jrajahalme it seems this was removed by https://github.com/cilium/cilium/commit/9f7604bae81f0c71f5ce36dffe82d7d6be9dcf6b I'm not sure if by accident or not.
