### ISSUE TITLE
eBPF: how to find the name(or obj file/section) of a prog 

### ISSUE THREAD

**Issue by ChaosEternal** [cilium/cilium#16736]
After done a xlated dump of a bpf progam, there are usually some code look like this:
```
152: (18) r7 = map[id:125]
 154: (bf) r1 = r6
 155: (bf) r2 = r7
 156: (b7) r3 = 6
 157: (85) call bpf_tail_call#12
```
Then I dump the content of map 125:
```
root@node1:~# bpftool map dump id 125
key: 01 00 00 00  value: 60 05 00 00
key: 06 00 00 00  value: 68 05 00 00
key: 0f 00 00 00  value: 64 05 00 00
key: 11 00 00 00  value: 66 05 00 00
Found 4 elements
```
the key 06 pointing to a prog id 0x568 , which is 1384:
```
# bpftool prog show id 1384
1384: sched_cls  tag 8ce0e44a9589a7fc  gpl
        loaded_at 2021-07-01T14:16:24+0000  uid 0
        xlated 1528B  jited 923B  memlock 4096B  map_ids 91,125
```
it tells so few information. 

how can I find which object file owns this prog and how to find the function name of the prog?

**Comment by pchaigno** [comment]
Is this a BPF program loaded and attached by Cilium?

**Comment by ChaosEternal** [comment]
I think so.

**Comment by pchaigno** [comment]
Then you can get a lot more information by disassembling the version of the program stored in `/var/cilium/run/state/...`.

**Comment by ChaosEternal** [comment]
can you say something more?
for example, the /run/cilium/state/710/bpf_lxc.o defined several functions:
```
# bpftool btf dump file 710/bpf_lxc.o |grep 'FUNC\>'
[16] FUNC '__send_drop_notify' type_id=14 linkage=global
[18] FUNC 'tail_nodeport_nat_ipv4' type_id=17 linkage=global
[20] FUNC 'tail_rev_nodeport_lb4' type_id=19 linkage=global
[22] FUNC 'tail_handle_arp' type_id=21 linkage=global
[24] FUNC 'handle_xgress' type_id=23 linkage=global
[26] FUNC 'handle_policy' type_id=25 linkage=global
[28] FUNC 'handle_to_container' type_id=27 linkage=global
``` 
how can I tell which function is the prog I found in the first post?

**Comment by ChaosEternal** [comment]
A related problem is according to the doc, the bpf_redir.c and bpf_sockops. are   also used, but I can't find the related .o files under /var/run/cilium/state, does this mean these two files are not loaded?
