### ISSUE TITLE
Need maglev more detailled explanation in documentation... or bug ?

### ISSUE THREAD

**Issue by mcarbonneaux** [cilium/cilium#16746]
i've build k8s cluster + cilium with vagrant of 3 node with control-plane, 1 user node (for doing client test), and a router node  (bgp ecmp).

I've activated maglev according to the documentation: 
https://docs.cilium.io/en/v1.10/gettingstarted/kubeproxy-free/#maglev-consistent-hashing-beta

I've activated bgp (metallb) and dsr (and direct routing), in kube-proxy replacement in 'strict' mode.

```
SEED=$(head -c16 /dev/urandom | base64 -w0)

helm install cilium cilium/cilium --version $cilium_version \
                                      --namespace kube-system \
				      --set nodeinit.enabled=true \
				      --set hostServices.enabled=false \
				      --set externalIPs.enabled=true \
				      --set nodePort.enabled=true \
				      --set hostPort.enabled=true \
				      --set bgp.enabled=true \
				      --set bgp.announce.loadbalancerIP=true \
				      --set bpf.masquerade=true \
				      --set image.pullPolicy=IfNotPresent \
				      --set ipam.mode=kubernetes \
				      --set kubeProxyReplacement=strict \
				      --set tunnel=disabled \
				      --set autoDirectNodeRoutes=true \
				      --set devices=enp0s8 \
				      --set nativeRoutingCIDR="10.10.0.0/16" \
				      --set maglev.tableSize=65521 \
				      --set maglev.hashSeed=$SEED \
				      --set loadBalancer.algorithm=maglev \
				      --set loadBalancer.mode=dsr \
				      --set hubble.listenAddress=":4244" \
				      --set hubble.relay.enabled=true \
				      --set hubble.ui.enabled=true \
				      --set hubble.enabled=true \
				      --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
				      --set prometheus.enabled=true \
				      --set operator.prometheus.enabled=true \
				      --set k8sServiceHost=$(cat /vagrant/.kubeapiserver| awk -F':' '{print $1}') \
				      --set k8sServicePort=$(cat /vagrant/.kubeapiserver| awk -F':' '{print $2}')
```

When i check with cilium status maglev seem activated :
```
root@server-1:/home/cilium# cilium status --verbose | grep -i maglev
  Backend Selection:     Maglev (Table Size: 16381)
```
to maglev table seem to exist:
```
root@server-1:/home/cilium# cilium bpf lb maglev list
SVC ID   LOOKUP TABLE
9        [10 10 11 10 10 11 10 11 11 10 11 11 12 11 11 11 12 11 10 10 10 11 10 10 11 10 10 11 10 10 11 11 10 ....
...
7        [10 10 11 10 10 11 10 11 11 10 11 11 12 11 11 11 12 11 10 10 10 11 10 10 11 10 10 11 10 10 11 11 10 ....
...
```

I've created pod with loadbalancing:
https://docs.cilium.io/en/v1.10/gettingstarted/bgp/#create-loadbalancer-and-backend-pods

I've scaled the pod to 3 (on 3 node).

I've added dynamique page on nginx (using configmap and ssi to print HOSTNAME varaible) to print pod name in response of curl:
```
$ curl 10.10.10.1
nginx-69ddf6b8c9-62d92
```

loadbalancing work fine, bgp work fine, dsr work fine....
but maglev not work, every request i receive diferent pod name...

what wrong ?
I must configure another thing or is a bug ?

my testbed are her: https://github.com/mcarbonneaux/vagrant-kubeadm-cluster-mca

**Comment by pchaigno** [comment]
> but maglev not work, every request i receive diferent pod name...

What do you mean exactly? How did you test? If every new request is assigned to a different backend, I'd say the load balancing is working as expected.

**Comment by aditighag** [comment]
You'll need to remove/add new service backends, and ensure that existing connections are not disrupted with Maglev enabled.

**Comment by mcarbonneaux** [comment]
i test the globale fonctionality of cilium to evaluate it.

in my evaluation i try to use loadbalancing dsr with magled enabled to loadbalance to pod with magled afinity.

normaly with maglev loadbalancing for one client/ip one backend are selected, and the backend only change if the backend death...

in my test i've done the backend change at random... is not what i expected with maglev lb...

maglev are affinity algorithm stateless... i want to avoid sessionafinity that use session table...

**Comment by mcarbonneaux** [comment]
> 
> 
> You'll need to remove/add new service backends, and ensure that existing connections are not disrupted with Maglev enabled.

in fact with pod with 3 replicas, i receive traffic at random on each replica (i print the replica name in the response).
i've not tested the death of replica, because they not work on alive replica...

**Comment by mcarbonneaux** [comment]
the maglev afinity is done per tcp connection ? or per client ip ?

**Comment by pchaigno** [comment]
> the maglev afinity is done per tcp connection ? or per client ip ?

The former. You can find an explanation of Maglev at https://cilium.io/blog/2020/11/10/cilium-19#maglev.

**Comment by brb** [comment]
Also, this is a good resource to understand Maglev: https://storage.googleapis.com/pub-tools-public-publication-data/pdf/44824.pdf. 

Anyway, if you want to send a request to the same service backend, then you need to reuse the client IP and port and the same service VIP.

> if the first... is miss my undertanding of the maglev....

Considering this, I think we can close the issue.

**Comment by mcarbonneaux** [comment]
you use maglev between external ip and cluster ip ? not between cluster ip and pod replica ?

**Comment by brb** [comment]
You can use Maglev only for traffic coming from outside cluster to services (LoadBalancer, NodePort and externalIP). See https://cilium.io/blog/2020/11/10/cilium-19#maglev-load-balancing for more details.

**Comment by mcarbonneaux** [comment]
i know but my question is from outside to the replicat set, to correctly understand the path where the traffic go on...

**Comment by brb** [comment]
After a node received a request from outside, it selects a service endpoint, does DNAT and then forwards a request to a node which runs the endpoint.

**Comment by mcarbonneaux** [comment]
when select a service endpoint is her you use maglev to forward the traffic to the service endpoint ?
them when the service endpoint selected are on other node, you encapsulate the trafic to this node, or you DNAT before and after use simple routing to the node ?
when reply to the client you SNAT with the VIP to reply directly to the client ?

**Comment by brb** [comment]
> when select a service endpoint are her you use maglev to forward the traffic to the service endpoint ?

Maglev is used only when you enable it, and it is used to select a service endpoint.

> you encapsulate the trafic to this node, or you DNAT before and after use simple routing to the node ?

It depends in which mode you run. E.g. in the tunneling mode, the packet will be encapsulated and sent via the tunneling device, while in the direct routing mode it is not. The DNAT happens before encapsulation.

> when reply to the client you SNAT with the VIP to reply directly to the client (how you know how to SNAT if you are on other node ?) ?

In the DSR mode, the reverse SNAT translation for the reply is happening on the service endpoint node, while in the non-DSR mode, the reply is reverse-SNAT translated on the node which received the request.
