### ISSUE TITLE
Fix custom BPF mount

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#16751]
Currently, we've hardcoded the default [BPF filesystem mount point](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml#L452) in the Cilium agent daemonset yaml. However, there is a helm option `bpf-root` that users can specify to mount BPF fs at a custom location. In such cases, we should do a bidirectional mount at the user specified path from the host. Agent will then [mount](https://github.com/cilium/cilium/blob/master/pkg/bpf/bpffs_linux.go#L172) BPF fs at the volume mount path if not already mounted.

**Comment by Ankurk99** [comment]
I would like to work on this issue.

**Comment by pchaigno** [comment]
I assigned you :rocket:

**Comment by aditighag** [comment]
@Ankurk99 👍 Please reach out on Slack if you have any questions. Also, I would suggest waiting  until https://github.com/cilium/cilium/pull/16656 is merged to avoid having conflicts.

**Comment by Ankurk99** [comment]
> However, there is a helm option `bpf-root` that users can specify to mount BPF fs at a custom location. In such cases, we should do a bidirectional mount at the user specified path from the host.
The flag  'bpf-root' is in cilium-agent and I couldn't find it in helm, so do I need to add the flag for custom bpf location in Values.yaml?
