### ISSUE TITLE
mount-cgroup nsenter: failed to execute sh: No such file or directory

### ISSUE THREAD

**Issue by alex1989hu** [cilium/cilium#16771]
## Bug report

**General Information**

Wanted to upgrade Cilium from `1.10.1` to `1.10.2` but `cilium` Pod, `mount-cgroup` container fails with message:
>nsenter: failed to execute sh: No such file or directory

thus `cilium` Pod Status is `Init:CrashLoopBackOff`, Exit Code:  127.

- Cilium version (run `cilium version`)
1.10.2
- Kernel version (run `uname -a`)
> Linux prod-k8s-master-3 5.10.29-talos #1 SMP Mon Jun 21 14:23:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...)
> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
N/A
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. All I changed is the `cilium` Helm Chart version, from `1.10.1` to `1.10.2`
2. Inspect failing Pod

**Comment by aditighag** [comment]
Thanks for the report. 

>nsenter: failed to execute sh: No such file or directory

This is the relevant [code](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml#L390). I'm not sure why `sh` would be missing since we use cilium image for the init container. We also didn't see this error in any of our tests.

If you need a workaround in the meantime, you can disable `auto mount, see the note in the getting started guide - https://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/#quick-start.

**Comment by alex1989hu** [comment]
> I just realized that we run the command on the host using nsenter so it looks like you are missing sh on your host (underlying kubernetes node)?
Can you run which sh on your host? Also, what's the output of echo $PATH?

In Talos we do not have interactive shell, thus I can not execute either `echo` or `which` command.

On the other hand, I started interactive shell in `cilium` Pod: `cilium-agent` container.

Is `cgroup2` there? - Yes
```sh
root@prod-k8s-master-3:/home/cilium# grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
```

Check the particular command copied from Helm Chart:

```sh
root@prod-k8s-master-3:/home/cilium# mount | grep "/run/cilium/cgroupv2 type cgroup2"
none on /run/cilium/cgroupv2 type cgroup2 (rw,relatime)
```

**Comment by aditighag** [comment]
>In Talos we do not have interactive shell, thus I can not execute either echo or which command.

I'm not familiar with Talos. Are you able to edit the cilium agent daemonset yaml, and replace `sh` with `/bin/sh`? Does that fix the problem?

**Comment by aanm** [comment]
> > In Talos we do not have interactive shell, thus I can not execute either echo or which command.
> 
> I'm not familiar with Talos. Are you able to edit the cilium agent daemonset yaml, and [replace](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml#L390) `sh` with `/bin/sh`? Does that fix the problem?

Talos does not seem to come with any shell `docker export $(docker create ghcr.io/talos-systems/talos:v0.10.4) | tar tf - | grep sh`

**Comment by aditighag** [comment]
> Is `cgroup2` there? - Yes
> 
> ```shell
> root@prod-k8s-master-3:/home/cilium# grep cgroup /proc/filesystems
> nodev   cgroup
> nodev   cgroup2
> ```
> 

@alex1989hu I assume you ran this command on the host (i.e. the kubernetes node where cilium agent pod is deployed)?

If you don't have `sh` installed on your kubernetes nodes, you can disable auto mount as documented in the guide - https://docs.cilium.io/en/latest/gettingstarted/kubeproxy-free/#quick-start. 

You can check if cgroup2 filesystem is mounted on your host by running - `mount | grep cgroup2`

Here is the note from the documentation - 

```
If you need to disable the auto-mount, specify --set cgroup.autoMount.enabled=false, and set the host mount point where cgroup v2 filesystem is already mounted by using --set cgroup.hostRoot. For example, if not already mounted, you can mount cgroup v2 filesystem by running the below command on the host, and specify --set cgroup.hostRoot=/sys/fs/cgroup.

mount -t cgroup2 none /sys/fs/cgroup
```

**Comment by aditighag** [comment]
@alex1989hu Can you try this cilium image - quay.io/cilium/cilium-ci:865635fb4ed3cffea69359eb79d3fd89cdcb4cd2. This image has a fix.

(In case you need to also specify cilium-operator image - quay.io/cilium/operator-generic-ci:865635fb4ed3cffea69359eb79d3fd89cdcb4cd2)

**Comment by alex1989hu** [comment]
@aditighag: I created k8s manifest from #16815 ref: 865635fb4ed3cffea69359eb79d3fd89cdcb4cd2 with images you wrote.

Created new Talos cluster /1 control-plane, 1 worker/ with the same version as in OP. There was no error. 

Looks healthy:

![image](https://user-images.githubusercontent.com/10764100/124779203-de471200-df41-11eb-89bc-6e49312f89ef.png)

**Comment by anthr76** [comment]
I'm also facing this on OpenSUSE Kubic. If there's anything I can do to help, I'll be happy!
