### ISSUE TITLE
Add log file for CNI executions

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#16798]
Without the access to kubelet and / or container runtime logs, right now it's not possible to know when CNI executions are made into `cilium-cni`. It would be nice to export these logs into a specific log file (`/run/cilium/cilium-cni.log`), with log rotation, which would store all the CNI executions including log messages in there. When implementing this, take into account that `cilium-cni` binary can be executed concurrently so storing into a single file has to handle concurrent writes.

**Comment by vishjain** [comment]
New to the project, can I try out this ticket? Thanks!

**Comment by aanm** [comment]
@vishjain sure, let us now if you need any help with it. We are in the #development channel of http://slack.cilium.io

**Comment by christarazi** [comment]
@vishjain  Have you been able to make progress on this issue? If you are not actively working on it, please unassign yourself. Otherwise, please reach out to the #development channel on Cilium slack for help.

**Comment by sayboras** [comment]
seems like no one is working on this, let me give it a crack.
