### ISSUE TITLE
refactor and cleanup cilium helm chart

### ISSUE THREAD

**Issue by dungdm93** [cilium/cilium#16792]
As a suggestion of @gandro in #16752, this is meta issue to track progress of helm chart refactoring

---
Cilium helm charts is quite large (>70 files) with lots of components but all that file are in flatten structure. Some how, it make hard to organized and hard to add new feature. So this PR aim to refactor and cleanup cilium helm chart with following notable changes:
1. **Restructure folder**: move each component in it own folder
![Screenshot from 2021-07-02 10-22-23](https://user-images.githubusercontent.com/6848311/124216018-70ed4880-db1f-11eb-9f8f-e5a0971f2661.png)
2. **Remove deprecated & unused resources**:
  * Delete `hubble-ca-configmap.yaml`, it has bean marked as deprecated and will be removed in v1.11
  * Delete `cilium-etcd-sa` Service Account, `etcd-operator` ClusterRole/ClusterRoleBinding which are use in nowhere.
3. **Refactor tls logic**: provided, helm and cronjob.  
  Currently, this chart support 3 different kind of TLS: provided, helm-gen, cronjob-gen. But the logic between those 3 types is not the same, for example: helm-gen method always generate both CA and certs (ignore user provided), but cronjob-gen reuse and disable generate cert when user provide CA/cert (this mean no cert auto-rotate).
https://github.com/cilium/cilium/blob/703b38fd47da1f91a342a8546f53542d624d8b22/install/kubernetes/cilium/templates/_hubble-generate-certs-job-spec.tpl#L47-L53  
  So I simplify and unify this logic as following:
    * Split each tls method to its own folder:
    ![Screenshot from 2021-07-02 10-45-30](https://user-images.githubusercontent.com/6848311/124217492-a6476580-db22-11eb-9da4-31055cd0efc9.png)
    * When tls provided (`not auto.enabled`), both `cert` and `key` are required
    * When tls auto (both helm and cronjob methods), if user provide CA, use it; else generate new one. Other client/server/remote TLS are generated.
4. cleanup code
    * Move `nodeinit` prestop and startup scripts to external file (inside `files/nodeinit` folder) aim to better highlight and easier to update
    * Indent go template and use `nindent` (instead of `indent`) for better look and easier to collapse/expand when using IDE
    * Using `include "cilium.image"` named template for generate docker image name
    * Support `priorityClassName`. `priorityClassName` is defined in `values.yaml` but used in nowhere. Now it's supported.

**Comment by sayboras** [comment]
Thanks a lot for your help, seems like all items were done. Closing this issue, feel free to highlight if there is anything else pending.
