### ISSUE TITLE
cilium-operator: only GC identities of its own cluster

### ISSUE THREAD

**Issue by ArthurChiao** [cilium/cilium#16805]
### Problem statement

With kvstore (etcd) as identity allocator, `cilium-operator` is responsible for garbage collecting the identity master keys (`cilium/states/identites/v1/id/<id>`). If **multiple cilium clusters share a same kvstore** (not a usual case, and should be avoided in most scenarios), there would be race conditions as multiple cilium-operators try to GC the same set of master keys.

### Describe the solution you'd like

`cilium-operator` of each cluster **only GCs the master keys of its own cluster**.

This information is already available as `ClusterID` is configured for each cilium-operator, with which we could calculate the identity range of this cluster. Then, we can distinguish the keys by the valid identity range.

### Other aspects

* Compatibility: compatible with the upstream.
* GC Performance downgrade: neglectable.
* **disclaimer**: it would benefit [another draft proposal](https://docs.google.com/document/d/1Zc8Sdhp96yKSeC1-71_6qd97HPWQv-L4kiBZhl7swrg/edit#).

We'd like to contribute a patch if this proposal (issue) is approved. Thanks!

**Comment by ArthurChiao** [comment]
For your reference: a draft PR is created in #16825. Thanks!

**Comment by pchaigno** [comment]
Reopening given the PR with the fix was reverted in master.
