### ISSUE TITLE
Unable to run cilium 1.10.2 via helm on ppc64le

### ISSUE THREAD

**Issue by helix-loop** [cilium/cilium#16812]
## Bug report

Trying to "Validate the Installation" I get the following errors:

NAME                              READY   STATUS                  RESTARTS   AGE
cilium-xyz                       0/1     Init:ImagePullBackOff   0          63m
cilium-operator-xyza       0/1     ImagePullBackOff        0          63m
cilium-operator-xyzb       0/1     Pending                 0          63m
coredns-a                        0/1     Pending                 0          3m52s
coredns-b           	       0/1     Pending                 0          3m52s
etcd-host4                      1/1     Running                 1          80m
kube-apiserver-host4      1/1     Running                 1          80m
kube-controller-manager-host4    1/1     Running                 1          80m
kube-proxy-abc                   1/1     Running                 1          80m
kube-scheduler-host4             1/1     Running                 1          80m
cilium-xyz                       0/1     Init:ErrImagePull       0          66m
cilium-operator-xyza   0/1     ErrImagePull            0          66m
cilium-xyz                       0/1     Init:ImagePullBackOff   0          66m
cilium-operator-xyza   0/1     ImagePullBackOff        0          66m
cilium-xyz                       0/1     Init:ErrImagePull       0          71m
cilium-operator-xyza   0/1     ErrImagePull            0          71m
cilium-xyz                       0/1     Init:ImagePullBackOff   0          71m
cilium-operator-xyza   0/1     ImagePullBackOff        0          71m
cilium-operator-xyza   0/1     ErrImagePull            0          76m
cilium-xyz                       0/1     Init:ErrImagePull       0          76m
cilium-operator-xyza   0/1     ImagePullBackOff        0          76m
cilium-xyz                       0/1     Init:ImagePullBackOff   0          76m

Looking at https://github.com/cilium/cilium/tree/master/images "multi-platform" Dockerfile is amd64 and arm64 (aarch64). Is ppc64le architecture unsupported?

**General Information**

cilium-cli: v0.8.4 compiled with go1.16.2 on linux/ppc64le

Linux host4 5.11.0-22-generic #23-Ubuntu SMP Thu Jun 17 00:25:44 UTC 2021 ppc64le ppc64le ppc64le GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, ...)
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/ppc64le"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/ppc64le"}

- Link to relevant artifacts (policies, deployments scripts, ...)
https://docs.cilium.io/en/stable/gettingstarted/k8s-install-helm/
https://helm.sh/docs/intro/install/
https://github.com/cilium/cilium-cli

**How to reproduce the issue**

1. helm install cilium cilium/cilium --version 1.10.2 --namespace kube-system
2. kubectl -n kube-system get pods --watch

**Comment by pchaigno** [comment]
> Is ppc64le architecture unsupported?

At the moment, yes, it is not supported.

**Comment by joestringer** [comment]
I think it would be reasonable to support ppc64le, but I'm not currently aware of anyone working on it. This is expected behaviour for now since it's not supported.
