### ISSUE TITLE
Make it easier to check the status of chaining mode

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#16816]
It would be helpful know the status of chaining mode. With this sort of visibility, it could be useful as clue to the user that something has gone wrong when they've configured Cilium with chaining. A simple field in `cilium status` for chaining status could be enough, e.g.`chaining` or `non-chaining`.

**Comment by arpit1912** [comment]
Hi @christarazi  I'm new to this community and would like to work on this issue as the first task thanks!

**Comment by pchaigno** [comment]
@arpit1912 I've assigned you. Don't hesitate to reach out on Slack (e.g., #development) if you have any questions.

**Comment by arpit1912** [comment]
Sure! I'm still figuring out how I can create a local cluster on the system and how I can interact with it( Do let me know if you know any quick links otherwise I will ask later on, on slack as well), Once that is done I will start working on the issue.

**Comment by h3llix** [comment]
Hi @arpit1912 :wave: . I was looking into this issue and I believe you can set up minikube with calico cni from here https://docs.projectcalico.org/getting-started/kubernetes/minikube. And then setup Cilium with CNI chaining on top of Calico from here https://docs.cilium.io/en/v1.10/gettingstarted/cni-chaining-calico/#calico. 

cc: @christarazi @pchaigno Please verify if the instructions are correct.

**Comment by christarazi** [comment]
@arpit1912 Have you been able to make progress on this issue? If you are not actively working on it, please unassign yourself.
