### ISSUE TITLE
CI: L4LB XDP suite times out on Fedora : mounting "/proc/1/ns" ... caused: permission denied: unknown

### ISSUE THREAD

**Issue by brb** [cilium/cilium#16828]
The suite is failing on master:
```
 ++ kubectl -n kube-system get pod -l k8s-app=cilium '-o=jsonpath={.items[0].metadata.name}'
+ CILIUM_POD_NAME=cilium-6hcl7
+ kubectl -n kube-system wait --for=condition=Ready pod cilium-6hcl7 --timeout=5m
error: timed out waiting for the condition on pods/cilium-6hcl7
```
https://github.com/cilium/cilium/runs/3010343837?check_suite_focus=true

To reproduce:
```
$ cd cilium
$ ln -sf ./test/l4lb/Vagrantfile
$ vagrant up
$ vagrant ssh
$ sudo -s
# cd /vagrant/test/l4lb/
# ./test.sh cilium 8c3c917f14cde685d6ded0711f57d5f3cf280e4f
```
Wait until test.sh fails. Then:
```
# kubectl -n kube-system describe pod cilium-m45nj
[...]
Warning  Failed     3m54s (x5 over 5m15s)  kubelet            Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/proc/1/ns" to rootfs at "/run/containerd/io.containerd.runtime.v2.task/k8s.io/mount-cgroup/rootfs/hostpid1ns" caused: permission denied: unknown
```

**Comment by aditighag** [comment]
># ./test.sh cilium 8c3c917f14cde685d6ded0711f57d5f3cf280e4f

@brb What's 8c3c917f14cde685d6ded0711f57d5f3cf280e4f?

**Comment by aditighag** [comment]
Should be resolved by - https://github.com/cilium/cilium/pull/16815. But I'm having trouble running the ci-l4lb job - https://github.com/cilium/cilium/pull/16833.

**Comment by aditighag** [comment]
I was able to verify that the fix works by using the image from my PR - `./test.sh cilium 6048567e3fa82aa23f871039d283ab91c33caa92`. I've opened [this PR](https://github.com/cilium/cilium/issues/16828) on the upstream PR to get link to a successful job link, but I'm not able to run the ci-l4lb job.

**Comment by aditighag** [comment]
This is a dup of https://github.com/cilium/cilium/issues/16814 as the l4lb job also runs Fedora.
