### ISSUE TITLE
snat port and nodeport conflict

### ISSUE THREAD

**Issue by zhangjianghua** [cilium/cilium#16827]
## Bug report

**General Information**

- Cilium version (run `cilium version`)

> -Client: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
     Daemon: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64

- Kernel version (run `uname -a`)

> Linux k8s25ss.ultron.shbt.qihoo.net 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, 

> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How to reproduce the issue**
Appear randomly and cannot be reproduced.
![image](https://user-images.githubusercontent.com/22954271/124892745-b670b080-e00c-11eb-9e3d-01e1090842e3.png)

**Detailed Description**
1. Pod accesses services outside the cluster, and occasionally dial tcp 10.202.5.223:80: i/o timeout appears.tcpdump packet capture found tcp retransmission [tcp port numbers reused].
30241 is included in the range of nodeport 30000-32767

> cilium status
> KubeProxyReplacement:   Probe   [eth2 (DR)]   [NodePort (SNAT, 30000-32767, XDP: DISABLED), HostPort, ExternalIPs, HostReachableServices (TCP), SessionAffinity]

> cilium service list
> 5592   0.0.0.0:30241    NodePort       1 => 192.168.10.172:8888

![image](https://user-images.githubusercontent.com/22954271/124891014-2b42eb00-e00b-11eb-8fd5-787606598f8d.png)

2.Solution- No, it will still appear
Add sysctl net.ipv4.ip_local_reserved_ports = 30000-32767
Existed net.ipv4.ip_local_port_range = 32768	60999

**Comment by zhangjianghua** [comment]
It seems that when using Kube-proxy, iptables will cause the port range of the kernel to do not take effect.
Remove Kube-proxy and iptables -F, TCPDUMP capture won't use the port between 30000-32767
![image](https://user-images.githubusercontent.com/22954271/125020612-c12e5280-e0ab-11eb-9752-32b04cf21a81.png)

**Comment by brb** [comment]
@zhangjianghua How did you end up with the src port 30241 for the request in the wireshark screenshot? `net.ipv4.ip_local_port_range = 32768 60999` should prevent this from happening.
