### ISSUE TITLE
CI: Suite-k8s-1.21.K8sPolicyTest Multi-node policy test with L7 policy using connectivity-check to check datapath

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#16847]
```
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
connectivity-check pods are not ready after timeout
Expected
    <*errors.errorString | 0xc007fb7810>: {
        s: "timed out waiting for pods with filter  to be ready: 4m0s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/Policies.go:1823
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/1020/testReport/junit/Suite-k8s-1/21/K8sPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/

All the pods got to a running state , except -

```
default pod-to-a-multi-node-proxy-egress-policy-5b5f7d94d8-5gf22 1/2 Running 4 4m5s 10.0.0.126 k8s2
default pod-to-c-intra-node-proxy-ingress-policy-5f95cf647c-5qrzw 1/2 Running 4 4m5s 10.0.0.131 k8s2
```

Both these pods had containers that failed to curl the same clusterIP service -

```
containerID="e91bc8696896d5b3ed49a35233b48aab2c7752a9023fdae9fbe2662bcb2cd8eb" cmd=[curl -sS --fail --connect-timeout 5 -o /dev/null echo-a:8080/public]

containerID="e91bc8696896d5b3ed49a35233b48aab2c7752a9023fdae9fbe2662bcb2cd8eb" cmd=[curl -sS --fail --connect-timeout 5 -o /dev/null echo-a:8080/public]
```

But the backend pod is already running and `echo-a` has a clusterIP service -

```
default echo-a-d576c5f8b-vq7hm 1/1 Running 0

"clusterIP": "10.110.201.127",
```

[bb0cd8da_K8sPolicyTest_Multi-node_policy_test_with_L7_policy_using_connectivity-check_to_check_datapath.zip](https://github.com/cilium/cilium/files/6794090/bb0cd8da_K8sPolicyTest_Multi-node_policy_test_with_L7_policy_using_connectivity-check_to_check_datapath.zip)

**Comment by tklauser** [comment]
Seen on v1.10 backport #18276 on k8s 1.19: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/1943/

**Comment by kkourt** [comment]
Seen on v1.11 backport: https://github.com/cilium/cilium/pull/18569#issuecomment-1020058619
