### ISSUE TITLE
CI: K8sDatapathConfig AutoDirectNodeRoutes Check connectivity with sockops and direct routing

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#16852]
`cilium policy get -o json` returns empty output, causing JSON parsing to fail with `unexpected end of JSON input`.
```
/home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-5.4/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Error creating resource /home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-5.4/src/github.com/cilium/cilium/test/k8sT/manifests/l3-policy-demo.yaml: Cannot retrieve cilium pod cilium-8q5k8 policy revision: cannot get revision from json: could not parse JSON from command "kubectl exec -n kube-system cilium-8q5k8 -- cilium policy get -o json"
unexpected end of JSON input

Expected
    <*errors.errorString | 0xc000257210>: {
        s: "Cannot retrieve cilium pod cilium-8q5k8 policy revision: cannot get revision from json: could not parse JSON from command \"kubectl exec -n kube-system cilium-8q5k8 -- cilium policy get -o json\"\nunexpected end of JSON input\n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-5.4/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:1058
```
[487d5039_K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_sockops_and_direct_routing (3).zip](https://github.com/cilium/cilium/files/6801509/487d5039_K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_sockops_and_direct_routing.3.zip)

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-5.4/611/testReport/junit/Suite-k8s-1/19/K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_sockops_and_direct_routing/

**Comment by pchaigno** [comment]
A couple data points from [our CI dashboard](https://datastudio.google.com/s/r5VAHBAuh6c):
- This flake also occurs in v1.10 [[link]](https://jenkins.cilium.io/job/cilium-v1.10-k8s-1.19-kernel-5.4/33/testReport/junit/Suite-k8s-1/19/K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_sockops_and_direct_routing/). 
[23c100b4_K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_sockops_and_direct_routing.zip](https://github.com/cilium/cilium/files/6811179/23c100b4_K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_sockops_and_direct_routing.zip)
- It's fairly rare: 3 occurrences on master in 1 month.
- It seems specific to the CI job k8s-1.19-kernel-5.4. All cases I could validate were on that kernel.

Also worth noting that when this flake happens, the bugtool collection for k8s1 always fails, even though the agent status on that node is reported as healthy.

**Comment by twpayne** [comment]
Observed in [this run](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-5.4/783/) as part of #16914.

[c1c5d956_K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_sockops_and_direct_routing.zip](https://github.com/cilium/cilium/files/6955867/c1c5d956_K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_sockops_and_direct_routing.zip)

**Comment by jrajahalme** [comment]
Observed same fail/flake in the same test in kernel-5.4 pipeline in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-5.4/504/testReport/junit/Suite-k8s-1/21/K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_sockops_and_direct_routing/
