### ISSUE TITLE
Single node unable to join local or remote endpoints

### ISSUE THREAD

**Issue by edude03** [cilium/cilium#16859]
Sorry for the not so informative bug report title, I've been chatting with @pchaigno on slack and he asked that I open a bug report with a sysdump, but since I don't know why it doesn't work it's hard for to come up with a more informative title. Please change it if the issue becomes obvious (or I will if I figured it out)

**General Information**

I have a three node kubernetes v1.21 cluster, provisioned with kubeadm, skipping the kube-proxy addon (and using kubeproxyreplacement=strict) 

leader is the "master"
node-1, 2 are the "workers"

All three nodes are the same hardware and software connected with a simple switch. On node-1 pods deploy but the overlay network doesn't work (they can't connect to the internet, or the kubernetes api at 10.96.0.1)

- Cilium version (run `cilium version`)  1.10.2
- Kernel version (run `uname -a`) 5.10.48
- Orchestration system version in use (e.g. `kubectl version`, ...) kubernetes 1.21
- Link to relevant artifacts (policies, deployments scripts, ...) [I used the helm chart via kustomize with these values](https://gist.github.com/edude03/68d2cd70578e6583858b5396a6a160d4)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

http://transfer.sh/1Gl1PVG/cilium-sysdump-20210713-114211.zip

**Comment by pchaigno** [comment]
From Slack: the SYNs or SYN+ACKs of connections to remote health endpoints seem to be lost:
```
$ hubble observe --port 4240
[...]
Jul 12 16:20:34.603: 192.168.4.216:41028 <> 172.17.0.162:4240 to-overlay FORWARDED (TCP Flags: SYN)
Jul 12 16:20:35.648: 192.168.4.216:41028 <> 172.17.0.162:4240 to-overlay FORWARDED (TCP Flags: SYN)
Jul 12 16:20:37.697: 192.168.4.216:41028 <> 172.17.0.162:4240 to-overlay FORWARDED (TCP Flags: SYN)
Jul 12 16:20:41.729: 192.168.4.216:41028 <> 172.17.0.162:4240 to-overlay FORWARDED (TCP Flags: SYN)
Jul 12 16:20:43.900: 192.168.4.216:51052 <> 172.17.1.126:4240 Stale or unroutable IP DROPPED (TCP Flags: ACK, PSH)
Jul 12 16:20:47.460: 192.168.4.216:51052 <> 172.17.1.126:4240 Stale or unroutable IP DROPPED (TCP Flags: ACK, FIN)
Jul 12 16:20:50.177: 192.168.4.216:41028 <> 172.17.0.162:4240 to-overlay FORWARDED (TCP Flags: SYN)
```

**Comment by pchaigno** [comment]
The sysdump is missing the bugtool reports which would be useful to rule out any datapath issue.

**Comment by edude03** [comment]
Sorry about that @pchaigno, I ran it from the node that was having issues and it doesn't have permissions to do many of the things it needs for this tool. I reran it from my own computer and it seems to have worked better http://transfer.sh/1Gl1PVG/cilium-sysdump-20210713-114211.zip

**Comment by christarazi** [comment]
@edude03 The links to the sysdumps have expired. Could you attach them to the issue?

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
