### ISSUE TITLE
CI: Potential infinite loop during VM provisioning

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#16871]
`test/kubernetes-test.sh`, used in the k8s-upstream CI job, has an infinite loop which can lead us to only terminate the CI job after the multiple-hours timeout, if the Cilium pods fail to get ready.
https://github.com/cilium/cilium/blob/2acf25391441213966008ff50c13499de05a212d/test/kubernetes-test.sh#L32-L41

We should at least rewrite that to use a bash function and `timeout`.

[provisioning-loop-consoleText.txt](https://github.com/cilium/cilium/files/6815254/provisioning-loop-consoleText.txt)

**Comment by h3llix** [comment]
hi @pchaigno. I would like to work on this.
