### ISSUE TITLE
Enable cilium vxlan tunnel proxy ARP reply for pod

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#16890]
## Proposal / RFE

**Is your feature request related to a problem?**

When establishing cilium vxlan tunnel connectivity to external VNI key based VXLAN device like Linux vxlan device,  for example:

On  Linux machine external to k8s cluster with cilium managed pod, set up vxlan device
<pre>
#!/bin/bash
  
ip link add vxlan66 type vxlan id 66 dstport 8472 local 10.169.72.236 dev ens192
ip link set vxlan66 up
ip a add 10.0.4.236/24 dev vxlan66
ip route add 10.0.1.0/24 dev vxlan66  proto kernel  scope link  src 10.0.4.236
#arp -i vxlan66 -s 10.0.1.246 22:83:c3:65:e5:f1
#bridge fdb append 22:83:c3:65:e5:f1 dst 10.169.72.233 dev vxlan66
bridge fdb append 00:00:00:00:00:00 dst 10.169.72.233 dev vxlan66
</pre>

then ping cilium pod from external Linux machine
<pre>
[root@kernel-dev home]# ping -c 1 10.0.1.246
PING 10.0.1.246 (10.0.1.246) 56(84) bytes of data.
19:35:18.261812 00:50:56:86:b4:60 > 00:50:56:86:3d:0c, ethertype IPv4 (0x0800), length 92: (tos 0x0, ttl 64, id 9544, offset 0, flags [none], proto UDP (17), length 78)
    10.169.72.236.49157 > 10.169.72.233.8472: [bad udp cksum 0xa772 -> 0xf9ee!] OTV, flags [I] (0x08), overlay 0, instance 66
86:6d:5e:ff:1b:bf > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.0.1.246 tell 10.0.4.236, length 28

</pre>

tcpdump on cilium_vxlan interface on Cilium node hosting the pod 10.0.1.246

<pre>
[root@centos-dev cilium]# tcpdump -nn -e -i cilium_vxlan 
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on cilium_vxlan, link-type EN10MB (Ethernet), capture size 262144 bytes
19:35:17.436522 86:6d:5e:ff:1b:bf > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.0.1.246 tell 10.0.4.236, length 28
</pre>

 You can see the cilium_vxlan can receive the ARP broadcast for pod 10.0.1.246, but no ARP reply for pod .

The ARP problem can be worked around by add static ARP for pod and append fdb entry for cilium node when setting up the Linux vxlan device
<pre>

arp -i vxlan66 -s 10.0.1.246 22:83:c3:65:e5:f1
bridge fdb append 22:83:c3:65:e5:f1 dst 10.169.72.233 dev vxlan66
</pre>

But it would be nice to have Cilium doing proxy ARP response for pod to external ARP request

Having this feature enabled allows external Linux machine running proxy software like Ngnix/Haproxy..etc to do north-south bound load balancing to Cilium pod through Cilium vxlan tunnel

**Describe the solution you'd like**

I have come up a partial patch (copy code from bpf/bpf_lxc.c for ARP) below to send ARP response for pod 

<pre>
diff --git a/bpf/bpf_overlay.c b/bpf/bpf_overlay.c
index 52121bc7b..873406638 100644
--- a/bpf/bpf_overlay.c
+++ b/bpf/bpf_overlay.c
@@ -23,6 +23,7 @@
 #include "lib/common.h"
 #include "lib/edt.h"
 #include "lib/maps.h"
+#include "lib/arp.h"
 #include "lib/ipv6.h"
 #include "lib/eth.h"
 #include "lib/dbg.h"
@@ -281,6 +282,27 @@ int tail_handle_ipv4(struct __ctx_buff *ctx)
                                              CTX_ACT_DROP, METRIC_INGRESS);
        return ret;
 }
+
+#ifdef ENABLE_ARP_RESPONDER
+/*
+ * ARP responder for ARP requests from overlay
+ * Respond to remote VTEP endpoint with CILIUM_VXLAN MAC
+ */
+__section_tail(CILIUM_MAP_CALLS, CILIUM_CALL_ARP)
+int tail_handle_arp(struct __ctx_buff *ctx)
+{
+        union macaddr mac = NODE_MAC;
+        union macaddr smac;
+        __be32 sip;
+        __be32 tip;
+
+        /* Pass any unknown ARP requests to the Linux stack */
+        if (!arp_validate(ctx, &mac, &smac, &sip, &tip))
+                return CTX_ACT_OK;
+
+        return arp_respond(ctx, &mac, tip, &smac, sip, 0);
+}
+#endif /* ENABLE_ARP_RESPONDER */
 #endif /* ENABLE_IPV4 */
 
 /* Attached to the ingress of cilium_vxlan/cilium_geneve to execute on packets
@@ -314,6 +336,12 @@ int from_overlay(struct __ctx_buff *ctx)
        }
 
        switch (proto) {
+#if defined(ENABLE_ARP_RESPONDER)
+       case bpf_htons(ETH_P_ARP):
+               ep_tail_call(ctx, CILIUM_CALL_ARP);
+                ret = DROP_MISSED_TAIL_CALL;
+                break;
+#endif
        case bpf_htons(ETH_P_IPV6):
 #ifdef ENABLE_IPV6
                ep_tail_call(ctx, CILIUM_CALL_IPV6_FROM_LXC);
</pre>

and I can see the ARP response for pod on cilium_vxlan interface:
<pre>
[root@centos-dev cilium]# tcpdump -nn -e -i cilium_vxlan 

19:35:17.436522 86:6d:5e:ff:1b:bf > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.0.1.246 tell 10.0.4.236, length 28
19:35:17.436538 22:83:c3:65:e5:f1 > 86:6d:5e:ff:1b:bf, ethertype ARP (0x0806), length 42: Reply 10.0.1.246 is-at 22:83:c3:65:e5:f1, length 28
</pre>

but the ARP response packet is not encapsulated and not sent to external Linux vxlan device, tcpdump on the physical network interface on Cilium node on VXLAN port 8472 shows _no_ packet with ARP response encapsulated, any suggestions  would be appreciated!

**Comment by vincentmli** [comment]
I got ARP working for one Cilium node with following patch
<pre>
diff --git a/bpf/bpf_overlay.c b/bpf/bpf_overlay.c
index 52121bc7b..ffe5e02f5 100644
--- a/bpf/bpf_overlay.c
+++ b/bpf/bpf_overlay.c
@@ -23,6 +23,8 @@
 #include "lib/common.h"
 #include "lib/edt.h"
 #include "lib/maps.h"
+#include "lib/arp.h"
+#include "lib/encap.h"
 #include "lib/ipv6.h"
 #include "lib/eth.h"
 #include "lib/dbg.h"
@@ -281,6 +283,40 @@ int tail_handle_ipv4(struct __ctx_buff *ctx)
                                              CTX_ACT_DROP, METRIC_INGRESS);
        return ret;
 }
+
+#ifdef ENABLE_ARP_RESPONDER
+/*
+ * ARP responder for ARP requests from overlay
+ * Respond to remote VTEP endpoint with CILIUM_VXLAN MAC
+ */
+__section_tail(CILIUM_MAP_CALLS, CILIUM_CALL_ARP)
+int tail_handle_arp(struct __ctx_buff *ctx)
+{
+        union macaddr mac = NODE_MAC;
+        union macaddr smac;
+        __be32 sip;
+        __be32 tip;
+       __u32 monitor = 0;
+        struct endpoint_key key = {};
+       struct endpoint_key *tunnel;
+
+        /* Pass any unknown ARP requests to the Linux stack */
+        if (!arp_validate(ctx, &mac, &smac, &sip, &tip))
+                return CTX_ACT_OK;
+       if (arp_prepare_response(ctx, &mac, tip, &smac, sip) < 0)
+                return CTX_ACT_DROP;
+
+        key.ip4 = sip & IPV4_MASK;
+        key.family = ENDPOINT_KEY_IPV4;
+        tunnel = map_lookup_elem(&TUNNEL_MAP, &key);
+        if (!tunnel)
+                return DROP_NO_TUNNEL_ENDPOINT;
+       if (tunnel->vni)
+               return __encap_and_redirect_with_nodeid(ctx, tunnel->ip4, tunnel->vni, monitor);
+
+       return CTX_ACT_OK;
+}
+#endif /* ENABLE_ARP_RESPONDER */
 #endif /* ENABLE_IPV4 */
 
 /* Attached to the ingress of cilium_vxlan/cilium_geneve to execute on packets
@@ -314,6 +350,12 @@ int from_overlay(struct __ctx_buff *ctx)
        }
 
        switch (proto) {
+#if defined(ENABLE_ARP_RESPONDER)
+       case bpf_htons(ETH_P_ARP):
+               ep_tail_call(ctx, CILIUM_CALL_ARP);
+                ret = DROP_MISSED_TAIL_CALL;
+                break;
+#endif
        case bpf_htons(ETH_P_IPV6):
 #ifdef ENABLE_IPV6
                ep_tail_call(ctx, CILIUM_CALL_IPV6_FROM_LXC);
</pre>

but then I have another problem when I have two Cilium node that both Cilium node would proxy the ARP response for pod IP regardless if the pod is local pod or not, for example:

<pre>
[root@kernel-dev home]# ping -c 1 10.0.0.174
PING 10.0.0.174 (10.0.0.174) 56(84) bytes of data.
11:15:25.883364 86:6d:5e:ff:1b:bf > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.0.0.174 tell 10.0.4.236, length 28
11:15:25.884242 22:83:c3:65:e5:f1 > 86:6d:5e:ff:1b:bf, ethertype ARP (0x0806), length 42: Reply 10.0.0.174 is-at 22:83:c3:65:e5:f1, length 28
11:15:25.884474 5e:73:a2:d7:bf:4e > 86:6d:5e:ff:1b:bf, ethertype ARP (0x0806), length 42: Reply 10.0.0.174 is-at 5e:73:a2:d7:bf:4e, length 28
</pre>
both Cilium node responded with ARP reply for pod 10.0.0.174, so I am wondering how I can allow Cilium node only proxy ARP reply for local pod, not for all pod, what condition check I could add in tail_handle_arp?

**Comment by vincentmli** [comment]
> [root@kernel-dev home]# ping -c 1 10.0.0.174
> PING 10.0.0.174 (10.0.0.174) 56(84) bytes of data.
> 11:15:25.883364 86:6d:5e:ff:1b:bf > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.0.0.174 tell 10.0.4.236, length 28
> 11:15:25.884242 22:83:c3:65:e5:f1 > 86:6d:5e:ff:1b:bf, ethertype ARP (0x0806), length 42: Reply 10.0.0.174 is-at 22:83:c3:65:e5:f1, length 28
> 11:15:25.884474 5e:73:a2:d7:bf:4e > 86:6d:5e:ff:1b:bf, ethertype ARP (0x0806), length 42: Reply 10.0.0.174 is-at 5e:73:a2:d7:bf:4e, length 28
> both Cilium node responded with ARP reply for pod 10.0.0.174, so I am wondering how I can allow Cilium node only proxy ARP reply for local pod, not for all pod, what condition check I could add in tail_handle_arp?

I found  __lookup_ip4_endpoint() to do the trick, here is a working patch:

<pre>
diff --git a/bpf/bpf_overlay.c b/bpf/bpf_overlay.c
index 52121bc7b..302b721c1 100644
--- a/bpf/bpf_overlay.c
+++ b/bpf/bpf_overlay.c
@@ -23,6 +23,9 @@
 #include "lib/common.h"
 #include "lib/edt.h"
 #include "lib/maps.h"
+#include "lib/arp.h"
+#include "lib/encap.h"
+#include "lib/eps.h"
 #include "lib/ipv6.h"
 #include "lib/eth.h"
 #include "lib/dbg.h"
@@ -281,6 +284,42 @@ int tail_handle_ipv4(struct __ctx_buff *ctx)
                                              CTX_ACT_DROP, METRIC_INGRESS);
        return ret;
 }
+
+#ifdef ENABLE_ARP_RESPONDER
+/*
+ * ARP responder for ARP requests from overlay
+ * Respond to remote VTEP endpoint with CILIUM_VXLAN MAC
+ */
+__section_tail(CILIUM_MAP_CALLS, CILIUM_CALL_ARP)
+int tail_handle_arp(struct __ctx_buff *ctx)
+{
+        union macaddr mac = NODE_MAC;
+        union macaddr smac;
+        __be32 sip;
+        __be32 tip;
+       __u32 monitor = 0;
+        struct endpoint_key key = {};
+       struct endpoint_key *tunnel;
+
+        /* Pass any unknown ARP requests to the Linux stack */
+        if (!arp_validate(ctx, &mac, &smac, &sip, &tip))
+                return CTX_ACT_DROP;
+       if(!__lookup_ip4_endpoint(tip))
+               return CTX_ACT_DROP;
+       if (arp_prepare_response(ctx, &mac, tip, &smac, sip) < 0)
+                return CTX_ACT_DROP;
+
+        key.ip4 = sip & IPV4_MASK;
+        key.family = ENDPOINT_KEY_IPV4;
+        tunnel = map_lookup_elem(&TUNNEL_MAP, &key);
+        if (!tunnel)
+                return DROP_NO_TUNNEL_ENDPOINT;
+       if (tunnel->vni)
+               return __encap_and_redirect_with_nodeid(ctx, tunnel->ip4, tunnel->vni, monitor);
+
+       return CTX_ACT_OK;
+}
+#endif /* ENABLE_ARP_RESPONDER */
 #endif /* ENABLE_IPV4 */
 
 /* Attached to the ingress of cilium_vxlan/cilium_geneve to execute on packets
@@ -314,6 +353,12 @@ int from_overlay(struct __ctx_buff *ctx)
        }
 
        switch (proto) {
+#if defined(ENABLE_ARP_RESPONDER)
+       case bpf_htons(ETH_P_ARP):
+               ep_tail_call(ctx, CILIUM_CALL_ARP);
+                ret = DROP_MISSED_TAIL_CALL;
+                break;
+#endif
        case bpf_htons(ETH_P_IPV6):
 #ifdef ENABLE_IPV6
                ep_tail_call(ctx, CILIUM_CALL_IPV6_FROM_LXC);
</pre>

tcpdump on both Cilium node

<pre>
[root@centos-dev cilium]# tcpdump -nn -e -i cilium_vxlan arp

12:11:25.654983 86:6d:5e:ff:1b:bf > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.0.0.174 tell 10.0.4.236, length 28

[root@cilium-dev home]# tcpdump -nn -e -i cilium_vxlan arp 

12:11:26.018859 86:6d:5e:ff:1b:bf > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Request who-has 10.0.0.174 tell 10.0.4.236, length 28
12:11:26.018889 5e:73:a2:d7:bf:4e > 86:6d:5e:ff:1b:bf, ethertype ARP (0x0806), length 42: Reply 10.0.0.174 is-at 5e:73:a2:d7:bf:4e, length 28

</pre>
only one cilium node proxied the ARP reply for local pod 10.0.0.174

here is the complete Linux machine vxlan setup for above test for reference
cilium node: 10.169.72.239 pod cidr 10.0.0.0/24
cilium node: 10.10.169.72.233 pod cidr 10.0.1.0/24
<pre>

ip link add vxlan66 type vxlan id 66 dstport 8472 local 10.169.72.236 dev ens192
ip link set vxlan66 up
ip a add 10.0.4.236/24 dev vxlan66
ip route add 10.0.1.0/24 dev vxlan66  proto kernel  scope link  src 10.0.4.236
ip route add 10.0.0.0/24 dev vxlan66  proto kernel  scope link  src 10.0.4.236
bridge fdb append 00:00:00:00:00:00 dst 10.169.72.233 dev vxlan66
bridge fdb append 00:00:00:00:00:00 dst 10.169.72.239 dev vxlan66

</pre>

**Comment by qmonnet** [comment]
Hi, if you have a working patch, I would encourage you to submit it as a PR?

**Comment by vincentmli** [comment]
> Hi, if you have a working patch, I would encourage you to submit it as a PR?

Yes, I will, this patch is depending on a PR https://github.com/cilium/cilium/pull/16916 to be merged, once I have that PR merged, I could send this as PR.

**Comment by vincentmli** [comment]
new diff when saving VTEP MAC in macro in `/var/run/cilium/state/globals/node_config.h`

[root@cilium-dev home]# grep 'VTEP' /var/run/cilium/state/globals/node_config.h
```
#define ENABLE_VTEP 1
#define VTEP_ENDPOINT (__u32[]){0xec48a90a, 0xee48a90a, }
#define VTEP_MAC (__u64[]){0x562e984c3682, 0x552e984c3682, }
#define VTEP_NUMS 2
```
diff

```
diff --git a/bpf/bpf_overlay.c b/bpf/bpf_overlay.c
index be5fd76cd5..49dfe2084e 100644
--- a/bpf/bpf_overlay.c
+++ b/bpf/bpf_overlay.c
@@ -32,6 +32,12 @@
 #include "lib/identity.h"
 #include "lib/nodeport.h"
 
+#ifdef ENABLE_VTEP
+#include "lib/arp.h"
+#include "lib/encap.h"
+#include "lib/eps.h"
+#endif /* ENABLE_VTEP */
+
 #ifdef ENABLE_IPV6
 static __always_inline int handle_ipv6(struct __ctx_buff *ctx,
                                       __u32 *identity)
@@ -208,21 +214,16 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx, __u32 *identity)
                {
                        struct remote_endpoint_info *info;
                        int i;
-                       bool is_vtep = false;
 
                        info = lookup_ip4_remote_endpoint(ip4->saddr);
                        if (!info)
                                return DROP_NO_TUNNEL_ENDPOINT;
                        for (i = 0; i < VTEP_NUMS; i++) {
                                if (info->tunnel_endpoint == VTEP_ENDPOINT[i]) {
-                                       is_vtep = true;
-                                       break;
+                                       if (*identity != WORLD_ID)
+                                               return DROP_INVALID_VNI;
                                }
                        }
-                       if (is_vtep) {
-                               if (*identity != WORLD_ID)
-                                       return DROP_INVALID_VNI;
-                       }
                }
 #endif
        }
@@ -302,6 +303,54 @@ int tail_handle_ipv4(struct __ctx_buff *ctx)
                                              CTX_ACT_DROP, METRIC_INGRESS);
        return ret;
 }
+
+#ifdef ENABLE_VTEP
+#ifdef ENABLE_ARP_RESPONDER
+/*
+ * ARP responder for ARP requests from overlay
+ * Respond to remote VTEP endpoint with cilium_vxlan MAC
+ */
+__section_tail(CILIUM_MAP_CALLS, CILIUM_CALL_ARP)
+int tail_handle_arp(struct __ctx_buff *ctx)
+{
+       union macaddr mac = NODE_MAC;
+       union macaddr smac;
+       __be32 sip;
+       __be32 tip;
+       __u32 monitor = 0;
+       int i;
+       struct remote_endpoint_info *info;
+       struct bpf_tunnel_key key = {};
+
+       if (unlikely(ctx_get_tunnel_key(ctx, &key, sizeof(key), 0) < 0))
+               return DROP_NO_TUNNEL_KEY;
+       if (key.tunnel_id == HOST_ID)
+               return DROP_INVALID_IDENTITY;
+       if (key.tunnel_id != WORLD_ID)
+               return DROP_INVALID_VNI;
+
+       if (!arp_validate(ctx, &mac, &smac, &sip, &tip))
+               return CTX_ACT_DROP;
+       if(!__lookup_ip4_endpoint(tip))
+               return CTX_ACT_DROP;
+       if (arp_prepare_response(ctx, &mac, tip, &smac, sip) < 0)
+               return CTX_ACT_DROP;
+
+       info = lookup_ip4_remote_endpoint(sip);
+
+       if (!info)
+               return DROP_NO_TUNNEL_ENDPOINT;
+
+       for (i = 0; i < VTEP_NUMS; i++) {
+               if (info->tunnel_endpoint == VTEP_ENDPOINT[i])
+                       return __encap_and_redirect_with_nodeid(ctx, info->tunnel_endpoint, info->sec_label, monitor);
+       }
+
+       return CTX_ACT_OK;
+}
+#endif /* ENABLE_ARP_RESPONDER */
+#endif /* ENABLE_VTEP */
+
 #endif /* ENABLE_IPV4 */
 
 /* Attached to the ingress of cilium_vxlan/cilium_geneve to execute on packets
@@ -335,6 +384,12 @@ int from_overlay(struct __ctx_buff *ctx)
        }
 
        switch (proto) {
+#if defined(ENABLE_VTEP) && defined(ENABLE_ARP_RESPONDER)
+       case bpf_htons(ETH_P_ARP):
+               ep_tail_call(ctx, CILIUM_CALL_ARP);
+               ret = DROP_MISSED_TAIL_CALL;
+               break;
+#endif
        case bpf_htons(ETH_P_IPV6):
 #ifdef ENABLE_IPV6
                ep_tail_call(ctx, CILIUM_CALL_IPV6_FROM_LXC);

```

**Comment by vincentmli** [comment]
https://github.com/cilium/cilium/pull/18758
