### ISSUE TITLE
Use logging fields consistently across codebase

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1692]

**Comment by raybejjani** [comment]
Closed by
https://github.com/cilium/cilium/pull/1836
https://github.com/cilium/cilium/pull/1835
https://github.com/cilium/cilium/pull/1834
https://github.com/cilium/cilium/pull/1833
https://github.com/cilium/cilium/pull/1832
https://github.com/cilium/cilium/pull/1831
https://github.com/cilium/cilium/pull/1830
https://github.com/cilium/cilium/pull/1829
https://github.com/cilium/cilium/pull/1828
https://github.com/cilium/cilium/pull/1827
https://github.com/cilium/cilium/pull/1826
https://github.com/cilium/cilium/pull/1801
