### ISSUE TITLE
Implementation of CiliumEndpointBatch (CFP-2021-08)

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#16931]
Using this issue to track Implementation of CiliumEndpointBatch [CFP](https://docs.google.com/document/d/1DCDrgydIrLHID6k0sP1MMiOjRu5Q03nAjwpAsRVfkQc/edit?usp=sharing) is planned in the following PRs to a dedicated feature [branch](https://github.com/cilium/cilium/tree/feature/cep-scalability) for easier testing and minimum disruption to master.

- [x] Adds CiliumEndpointBatch CRD (#16864)
- [x] Operator batches CiliumEndpoints into CiliumEndpointBatches (https://github.com/cilium/cilium/pull/16945)
- [x] Agent watches for CiliumEndpointBatch instead of CiliumEndpoints (https://github.com/cilium/cilium/pull/17207)
- [x] Additional CEB metrics (https://github.com/cilium/cilium/pull/17410, https://github.com/cilium/cilium/pull/17498)
- [x] Rename CiliumEndpointBatch to CiliumEndpointSlice and make it namespace-scoped (https://github.com/cilium/cilium/pull/17554)
- [x] Identity grouping (https://github.com/cilium/cilium/pull/17345, https://github.com/cilium/cilium/pull/17520)
- [x] Pass master CI tests and merge into master (https://github.com/cilium/cilium/pull/17658)
- [x] Enable CES for new PRs in 1.21+ CI (https://github.com/cilium/cilium/pull/17698)
- [x] Documentation (https://github.com/cilium/cilium/pull/17430)

Follow up items:

For 1.12, we need at least:
- [ ] Move API to v2beta1
- [x] Fix https://github.com/cilium/cilium/issues/17669
- [ ] Enable CES by default

Other nice-to-have or may come after 1.12 release:
- [ ] Design some kind of auto-governor to self-adjust CES work queue rate limit, aka for small scale, set higher qps for quicker CEP propagation, for large scale, set lower qps for better scalability
- [ ] Expose internal knobs to users
- [ ] Add fine-tuning doc in performance/scalability section (https://docs.cilium.io/en/latest/operations/performance/scalability/)

**Comment by Weil0ng** [comment]
@krishgobinath

**Comment by aanm** [comment]
@Weil0ng Should we keep this GH issue open for 1.12 development cycle? Thanks

**Comment by Weil0ng** [comment]
> @Weil0ng Should we keep this GH issue open for 1.12 development cycle? Thanks

Sorry just was this, yes, let's track these for 1.12.
