### ISSUE TITLE
Cannot delete service in cilium

### ISSUE THREAD

**Issue by fr19k** [cilium/cilium#16940]
Hello

I have a little kuberentes cluster with 3 masters & 3 workers
I have created NodePort service in kubernetes on port 32006.. 

It was weird for me... beacuse from only one worker... i was able to connect to NodePort 32006...
From other workers i receives.. connection refused

When i deleted that service from kuberentes(kubectl delete svc .....)(successfully) in cilium service list |grep 32006(on "bad" worker), i can find a registered service with port 32006 (but it is deleted from kubectl get svc and noone other service is registered on port 32006)

261   10.250.75.70:32006    NodePort
On healthy worker this service does not exists

When i try to delete that service  (id 261), i'm receiving message

Error: [DELETE /service/{id}][500] deleteServiceIdFailure  Unable to delete service entry 10.250.75.70:1661: unable to delete element 10.250.75.70:32006 from map cilium_lb4_services_v2: no such file or directory

How can i deal with that?

cilium 1.10.3
kernel 5.12.13
kubernetes 1.19.2

Greetings

**Comment by aanm** [comment]
Hello @fr19k , can you provided some replication steps or a cluster sysdump? Thank you

**Comment by fr19k** [comment]
I have found cause... why i have connection refused on 2 from 3 workers...

replicaCount : 1 (thats why only one worker was "healthy")
also .. in service spec... i have found ...

externalTrafficPolicy: Local

Maybe it is "normal" after that policy is being used?

**Comment by brb** [comment]
Have you tried to upgrade Cilium to the latest? Closing the issue. Please reopen if the issue persists.
