### ISSUE TITLE
Enable NetfilterCompatibleMode on all versions of Kernels.

### ISSUE THREAD

**Issue by krishgobinath** [cilium/cilium#16952]
NetFilterCompatibleMode is a feature added in this [PR](https://github.com/cilium/cilium/pull/15354), this guarantees that traffic will pass through netfilter and iptable rules will be enforced.

However in this  [PR](https://github.com/cilium/cilium/pull/15354) added support only from kernels 5.4 and above. To support on all kernels,  we need to make tail call in `to_netdev` function in bpf_host.c. However introducing a new tailcall  in bpf_host causing few cilium upgrade test to fail.

Once we have fix for tail call Issue, which is addressed [here](https://github.com/cilium/cilium/pull/13032).
We can solve this Issue, by introducing a new tailcall in bpf_host.c.

**Comment by brb** [comment]
This is blocked by https://github.com/cilium/cilium/issues/16561.
