### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests L2-less with Wireguard provisioned via kube-wireguarder Tests NodePort BPF

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#16971]
## CI failure

Observed in https://github.com/cilium/cilium/pull/16900 

```
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Can not connect to service "http://172.16.42.1:30542" from outside cluster (1/10)
Expected command: kubectl exec -n kube-system log-gatherer-2dmlx -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://172.16.42.1:30542 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 7 
Err: exit status 7
Stdout:
 	 time-> DNS: '0.000017()', Connect: '0.000000',Transfer '0.000000', total '0.001527'
Stderr:
 	 command terminated with exit code 7
```

- Jenkins: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1133/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_L2_less_with_Wireguard_provisioned_via_kube_wireguarder_Tests_NodePort_BPF/
- Sysdump: 
[4124a77e_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_L2-less_with_Wireguard_provisioned_via_kube-wireguarder_Tests_NodePort_BPF.zip](https://github.com/cilium/cilium/files/6861305/4124a77e_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_L2-less_with_Wireguard_provisioned_via_kube-wireguarder_Tests_NodePort_BPF.zip)

**Comment by gandro** [comment]
There are a few error messages that I find concerning, such as `4354 kubelet.go:1577] error killing pod: failed to "KillPodSandbox" for "1c6dd876-a07c-4695-9eb6-5656bc7ab24b" with KillPodSandboxError: "rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"app2-5cc5d58844-l466m_default\" network: failed to find plugin \"cilium-cni\" in path [/opt/cni/bin]"`

**Comment by brb** [comment]
Hit it in https://github.com/cilium/cilium/pull/17003. It was the first request as in the issue description. Unfortunately, hubble observe logs are missing from the relevant (= one which received the failed request) node:
```
> cat cilium-6lqmn-hubble_observe.json
requested data has been overwritten and is no longer available
command terminated with exit code 1
```
[9fb9e765_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_L2-less_with_Wireguard_provisioned_via_kube-wireguarder_Tests_NodePort_BPF(1).zip](https://github.com/cilium/cilium/files/6894376/9fb9e765_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_L2-less_with_Wireguard_provisioned_via_kube-wireguarder_Tests_NodePort_BPF.1.zip)

**Comment by jrajahalme** [comment]
Same but with exit code 28: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1223/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_L2_less_with_Wireguard_provisioned_via_kube_wireguarder_Tests_NodePort_BPF/:
```
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Can not connect to service "http://192.168.36.11:30740" from outside cluster (1/10)
Expected command: kubectl exec -n kube-system log-gatherer-scjgw -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://192.168.36.11:30740 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000021()', Connect: '0.000000',Transfer '0.000000', total '5.001501'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/k8sT/service_helpers.go:299
```

**Comment by tklauser** [comment]
Seen on #18276: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/2173/

**Comment by brb** [comment]
The test case was removed. Closing the issue.
