### ISSUE TITLE
Failed to populate masquerading settings

### ISSUE THREAD

**Issue by digibank-rons** [cilium/cilium#17007]
Hey,

trying to upgrade to 1.10.3 on EKS 1.20, upgrading from 1.8.11, here is my Helm for creating the manifest -

helm template cilium/cilium --version 1.10.3 \
  --set upgradeCompatibility=1.8 \
  --set nodeinit.enabled=true \
  --set egressMasqueradeInterfaces=eth0 \
  --set hubble.enabled=true \
  --set hubble.listenAddress=":4244" \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
  --namespace kube-system \
  > cilium.yaml

When the pods start spinning up they fail on - 

level=fatal msg="Failed to populate masquerading settings" error="--enable-ipv4-masquerade and --masquerade (deprecated) are mutually exclusive" subsys=config

Thanks

**Comment by aanm** [comment]
Hello @digibank-rons please try to upgrade to 1.9 first since upgrading from 1.x.y to 1.x+2.y is not supported.

**Comment by rickydjohn** [comment]
i am seeing the same error while upgrading from `1.9.6 `to `1.10.8`

**Comment by pchaigno** [comment]
@rickydjohn Please open a new issue with the steps to reproduce :pray:
