### ISSUE TITLE
L4LB mode broken on v1.10 branch

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#17013]
Trying the L4LB mode on the v1.10 branch, `cilium-agent` crashes with the following error:

```
level=fatal msg="C and Go structs alignment check failed" error="ctmap.CtEntry.RxBytes offset(8) does not match ct_entry.rx_bytes(0)" subsys=datapath-loader
```

Invocation:
```
sudo ./cilium-agent --enable-ipv4=true --enable-ipv6=true --datapath-mode=lb-only --bpf-lb-algorithm=maglev --bpf-lb-maglev-table-size=2039 --bpf-lb-mode=dsr --bpf-lb-acceleration=testing-only --devices=enp0s8 --bpf-lb-dsr-dispatch=ipip --disable-envoy-version-check=true --enable-bpf-clock-probe=true --enable-recorder=true --enable-hubble=true --enable-hubble-recorder-api=true -D
```

cc @brb @borkmann

**Comment by aanm** [comment]
How isn't the v1.10 branch CI failing? :thinking:

**Comment by gandro** [comment]
> How isn't the v1.10 branch CI failing? thinking

https://github.com/cilium/cilium/pull/16950 removed the CI test from the v1.10 branch

**Comment by gandro** [comment]
CI still seems fine: https://github.com/cilium/cilium/runs/3188613036?check_suite_focus=true

Not sure if this is a problem for me locally (but I did run `make clean` and `git clean` both).

**Comment by gandro** [comment]
The error is also a false-positive for some reason. `ct_entry.rx_bytes` does _not_ have offset 0 in the sources, it is 8 as expected.

**Comment by gandro** [comment]
I did another test by running the pre-built v1.10 images, which don't suffer from the issue, so this is likely an issue with my toolchain or the dev-VMs. Closing.
