### ISSUE TITLE
CI: RuntimePrivilegedUnitTests TestArpPingHandling failed, timeout reached while waiting for condition 

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#17020]
```
	 START: node_linux_test.go:956: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.002s
	 
	 node_linux_test.go:1071:
	     // insertNeighbor is invoked async, so thus this wait based on last ping
	     wait(nodev1.Identity(), &now, false)
	 node_linux_test.go:1054:
	     c.Assert(err, check.IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"timeout reached while waiting for condition"} ("timeout reached while waiting for condition")
```
Seen in https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/5434/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

[f25b1682_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/6907360/f25b1682_RuntimePrivilegedUnitTests_Run_Tests.zip)

Similar to #16221, but this timeout happens after `NodeAdd()`.

**Comment by krishgobinath** [comment]
Noticed same issue in this [PR](https://github.com/cilium/cilium/pull/15354) also. Same error

`node_linux_test.go:1071:
	     // insertNeighbor is invoked async, so thus this wait based on last ping
	     wait(nodev1.Identity(), &now, false)
	 node_linux_test.go:1054:
	     c.Assert(err, check.IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"timeout reached while waiting for condition"} ("timeout reached while waiting for condition")
	 `
