### ISSUE TITLE
Enable Cilium images to be built from ARM instance

### ISSUE THREAD

**Issue by srini-ram** [cilium/cilium#17056]
## Bug report

**General Information**

Cilium image builds fine on x86s build platform (including ARM cross compilation from x86s). However if ARM instance is used as build platform to build ARM target, compilation fails. 

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
```
uname -a
Linux ip-x-x-x-x.us-west-2.compute.internal 4.14.238-182.422.amzn2.aarch64 #1 SMP Tue Jul 20 20:36:04 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, ...)  NA
- Link to relevant artifacts (policies, deployments scripts, ...) NA
- Generate and upload a system zip:  NA
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

* Start a new m6g.4xlarge instance running AL2. Launch instance with 256 Gi EBS volume to avoid below build error (error: failed to solve: failed to copy files: copy file range failed: no space left on device)
* Install docker - https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html
* Install docker buildx (https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/)
* Get cilium source code (git clone https://github.com/cilium/cilium.git)
* ARCH=aarch64 DOCKER_IMAGE_TAG=test-1 make docker-images-all

Build would fail as "binutils-x86-64-linux-gnu" is not installed on container.  Compilation error points to images/cilium/download-hubble.sh  
```
x86_64-linux-gnu-strip /out/linux/amd64/bin/hubble. (<<<---- Fails here. ---->>>)
aarch64-linux-gnu-strip /out/linux/arm64/bin/hubble
```

Fixed build error by installing the required binary 

```
[ec2-user@ip cilium]$ git diff images/cilium/download-hubble.sh 
[ec2-user@ip cilium]$ git diff
diff --git a/images/cilium/Dockerfile b/images/cilium/Dockerfile
index 16600e68d..3f509f362 100644
--- a/images/cilium/Dockerfile
+++ b/images/cilium/Dockerfile
@@ -16,8 +16,10 @@ FROM quay.io/cilium/cilium-envoy:e83275091139101e7ff29284ef35c56f4cd6bfc3@sha256
 FROM --platform=${BUILDPLATFORM} ${CILIUM_BUILDER_IMAGE} as hubble
 COPY images/cilium/hubble-version.sh /tmp/hubble-version.sh
 COPY images/cilium/download-hubble.sh /tmp/download-hubble.sh
+RUN apt-get update && apt-get install -y binutils-aarch64-linux-gnu
+RUN apt-get update && apt-get install -y binutils-x86-64-linux-gnu
 RUN /tmp/download-hubble.sh
```

Similar changes are required in below files
```
	modified:   images/clustermesh-apiserver/Dockerfile
	modified:   images/hubble-relay/Dockerfile
	modified:   images/operator/Dockerfile
	modified:   images/runtime/Dockerfile
```
Happy to submit a PR for the above changes.

**Comment by aanm** [comment]
@srini-ram there's a PR being worked on. See #17980
