### ISSUE TITLE
Cilium does not recognize alternative network interface names

### ISSUE THREAD

**Issue by jochenseeber** [cilium/cilium#17066]
## Proposal / RFE

Linux allows assigning alternative names to network interfaces using `ip link property add dev eth0 altname`. However, Cilium does not recognize those names when used eg in the `--devices` flag.

Since Cilium requires network interface names to be the same across all nodes, it would be great if we could achieve that using altnames, which has less impact on the host than outright renaming network interfaces.

**Comment by pchaigno** [comment]
Could you share the error message you get if you try to pass the altname to `--devices`?

**Comment by jochenseeber** [comment]
Same error message I get when I pass a completely unknown interface name (e.g. "--devices notthere"). I'll add the exact log on Monday.

**Comment by brb** [comment]
> Since Cilium requires network interface names to be the same across all nodes

It can be worked around. See https://github.com/cilium/cilium/pull/15697.

**Comment by jochenseeber** [comment]
> > Since Cilium requires network interface names to be the same across all nodes
> 
> It can be worked around. See #15697.

Thanks for the pointer. Our problem is that we need to add an "ethX" interface to Cilium, and not add "ethY", with X and Y differing on each node. We solved it by renaming the interfaces, but that is a lot more pain than just adding an altname.

**Comment by ti-mo** [comment]
@jochenseeber Could you give a more practical example? From what I understand, your nodes have `ethX` interfaces where X differs across nodes. Have you looked into udev persistent naming rules? You can create your own interface naming schemes this way, no need for aliasing.

**Comment by jochenseeber** [comment]
* We're using VLAN, so we can't use `eth+` as a pattern, since `eth0` should be used by Cilium, whereas `eth0.4020` should not. On other nodes it may be `eth2` and `eth2.4020` respectively.
* Renaming interfaces of course is possible, but inconvenient. It requires multiple configuration changes, working with MAC addresses to identify interfaces and rebooting the system.
* Using altnames would be pretty easy and straightforward (one single command), since you just have to 'tag' the correct interface with e.g. 'public' or 'internal', and then could tell Cilium to use `--devices=public,internal`
* Since altnames are part of the operating system, why not use the existing mechanism instead of e.g. supporting node specific devices settings in Cilium?
