### ISSUE TITLE
Checks for conflicting packet mark bits to validate interoperability

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#17109]
Cilium [uses](https://github.com/cilium/cilium/blob/v1.10/bpf/lib/common.h#L478-L488) a set of bits in the skb `mark` field to store metadata. However, these bits can conflict with other systems filtering packets based on selective bits (e.g., [Kubernetes](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)).  Conflicts can lead to packet drops, but these drops can be indeterministic based on whether the set bits by cilium overlap with the bits used for filtering packets. 

We should add preliminary checks to warn users about such scenarios. These checks can be part of the agent bootstrap (agent already iterates over some of the cilium-specific rules), or they can be added to a conformance test that validates the underlying system state when cilium is being installed.

**Comment by joestringer** [comment]
One of the options we discussed on friday was using the local kubelet's `/configz` endpoint to fetch some information:

```
$ curl -s http://127.0.0.1:10249/configz | gron | grep -i iptables | norg | jq '.'
{
  "kubeletconfig": {
    "iptablesDropBit": 15,
    "iptablesMasqueradeBit": 14,
    "makeIPTablesUtilChains": true
  },
  "kubeproxy.config.k8s.io": {
    "IPTables": {
      "MasqueradeAll": false,
      "MasqueradeBit": 14,
      "MinSyncPeriod": "1s",
      "SyncPeriod": "30s"
    }
  }
}
```

A more generic approach could consider something like parsing the iptables rules that exist and searching for mark usage.

**Comment by aditighag** [comment]
Based on this open [issue](https://github.com/kubernetes/kubernetes/issues/82125), it's not entirely clear if the relevant options are read from kubelet or kube-proxy configurations. Regardless, it might be better to keep the checks generic since there can be other filtering systems besides k8s.

**Comment by oblazek** [comment]
Adding my user experience when trying to run cilium in openstack with calico neutron driver. :) Calico also uses packet marks and this has caused identity to be falsely resolved when 2 vms on the same host tried to communicate.

**Comment by joestringer** [comment]
Indeed, any time that multiple software attempts to use the packet marks between different subsystems, it can be tricky to figure out exactly how the integration can work smoothly. The [fwmark/registry](https://github.com/fwmark/registry) documents some of the ways that the mark is used by different software, but doesn't provide a blueprint for how to integrate them. Depending on which subsystems the mark is being passed between, it may be possible to reuse mark bits for different purposes but it tends to require a lot of thought and attention to do correctly.

Quick plug, I did a [talk at Linux Plumbers Conference 2020](https://linuxplumbersconf.org/event/7/contributions/683/) on this topic which may be relevant. It doesn't provide all the answers, but at least outlines some of the problems and some ways which developers can use to mitigate mark overloading.
