### ISSUE TITLE
Cilium agents set wrong MTU for kubeproxy-less XDP Nodeport on AWS

### ISSUE THREAD

**Issue by DaveWK** [cilium/cilium#17107]
## Bug report
**General Information**

- Cilium version: v1.10.3
- Kernel version: 5.4.129-63.229.amzn2.x86_64
- Orchestration system version in use: helm

**How to reproduce the issue**

1. Create eks cluster using quickstart guide using eksctl
2. Install cilium using helm guide at: https://docs.cilium.io/en/v1.10/gettingstarted/kubeproxy-free/#nodeport-xdp-on-aws
3. Use the `for ip in $IPS ; do ssh ec2-user@$ip "sudo ip link set dev eth0 mtu 3818"; done` as suggested in the guide to set the MTU
4. Notice that cilium pods reset the MTU back to 9001 when they run, and then fails to start because the MTU is too high

Workaround:

I can add `--mtu=3818` to the cilium-agent daemonset, which sets the value correctly
I can add:
```
    preBootstrapCommands:
     - "ethtool -L eth0 combined 1"
```
to the eksctl yaml (kind of hacky because the combined value might change depending on ec2 instance size)

Notes:
Setting the MTU via CLI as currently suggested means if the node resets the MTU would go back to 9001
Same for the combined XDP setting

**Comment by joestringer** [comment]
Thanks for the report @DaveWK . I think there's some room for improvement in either autodetection of the right settings or in providing better tools for users to configure these things up-front.

> Notice that cilium pods reset the MTU back to 9001 when they run, and then fails to start because the MTU is too high

Is there a specific error message in the cilium-agent logs associated with this? Can you also add that here?

**Comment by DaveWK** [comment]
in the `dmesg` for the node you'll see:
```
ena 0000:00:05.0 eth0: Failed to set xdp program, the current MTU (9001) is larger than the maximum allowed MTU (3818) while xdp is on
```

**Comment by DaveWK** [comment]
Also an issue in v1.10.5 -- I do not see a setting for MTU in the ConfigMap generated by helm.

Is there a setting I can add to set the correct MTU in the cilium-config, or a way to specify the MTU as a helm value?

**Comment by joestringer** [comment]
It looks like there's no explicit MTU configuration in the helm templates today, but you should be able to configure it using `extraConfig`. 

Something like this in a values file should do the trick:
```
extraConfig:                                                                                                                                                                                                 
  mtu: "1280"
```
