### ISSUE TITLE
Question: Why NET_ADMIN and SYS_MODULE capabilities added in the securitycontext of  cilium agent container ？

### ISSUE THREAD

**Issue by yongming** [cilium/cilium#17118]
Per the below link, Cilium agent is running in privileged container,  in its securitycontext,  NET_ADMIN and SYS_MODULE capabilities are added,  is it really necessary? I suppose priviliged container has the host's root privilege.

https://github.com/cilium/cilium/blob/b2a5743f3bae0e803acc29d7cdeddfd066dcfa73/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L243

**Comment by gandro** [comment]
Yes, these are really needed. Cilium must be able to create and configure network devices in the host namespace, as well as load eBPF programs (which is also a privileged operation). It also needs to be able to load the `ip_tables` and `xt_socket` modules, for the functionality documented here: https://docs.cilium.io/en/v1.10/concepts/ebpf/iptables/#iptables-usage

See also https://docs.cilium.io/en/v1.10/operations/system_requirements/#privileges

**Comment by gandro** [comment]
We are however planning to remove the `privileged` container and reduce the set of needed capabilities further: https://github.com/cilium/cilium/pull/14446

**Comment by gandro** [comment]
It was pointed out to me that I might have read your question wrong - if you are asking why we need the capabilities _in addition_ to `privileged:true`, then this actually is a good question, we don't actually need to add the additional ones.

**Comment by yongming** [comment]
> It was pointed out to me that I might have read your question wrong - if you are asking why we need the capabilities _in addition_ to `privileged:true`, then this actually is a good question, we don't actually need to add the additional ones.

Yeah, my question is on the additional capabilities to  `privileged:true` . Thank for your comfirmation.
