### ISSUE TITLE
Cilium agent: controller bpf-map-sync-cilium_ipcache is failing: map sync errors

### ISSUE THREAD

**Issue by rkulow** [cilium/cilium#17111]
## Bug report

**General Information**

- Cilium version:
  `Client: 1.10.3 4145278 2021-07-15T16:11:03+02:00 go version go1.16.6 linux/amd64`
   `Daemon: 1.10.3 4145278 2021-07-15T16:11:03+02:00 go version go1.16.6 linux/amd6`
- Kernel version:
  `Linux k8s 4.14.138-rancher #1 SMP Sat Aug 10 11:25:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use:
  K8s Version `v1.20.9`, deployment using `Rancher RKE` and `Rancher OS v1.5.8`
  3 Nodes Cluster (1x master+worker, 2x worker)

**How to reproduce the issue**

1. deploy Cilium using the official Cilium Helm Chart (`v1.10.3`), use default values from provided values.yaml
2. run `cilium status`
```
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         3 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 3, Ready: 3/3, Available: 3/3
Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Containers:       cilium-operator    Running: 2
                  cilium             Running: 3
Image versions    cilium             quay.io/cilium/cilium:v1.10.3@sha256:8419531c5d3677158802882bdfe2297915c43f2ebe3649551aaac22de9f6d565: 3
                  cilium-operator    quay.io/cilium/operator-generic:v1.10.3@sha256:337ebf27eae4fbad51cc4baf9110b3ec6753320dd33075bc136e2a1865be5eb5: 2
Errors:           cilium             cilium-fb25q    controller bpf-map-sync-cilium_ipcache is failing since 7s (9x): 10 map sync errors
                  cilium             cilium-gwfv5    controller bpf-map-sync-cilium_ipcache is failing since 2s (10x): 11 map sync errors
                  cilium             cilium-mf4k2    controller bpf-map-sync-cilium_ipcache is failing since 2s (10x): 11 map sync errors

```

3. run  `cilium connectivity test -v`
```
...
⌛ [merkur-k8s1] Waiting for Cilium pod kube-system/cilium-gwfv5 to have all the pod IPs in eBPF ipcache...

Error: Connectivity test failed: timeout reached waiting for pod IDs in ipcache of Cilium pod kube-system/cilium-gwfv5

```

    
    
I have run quite a few K8s clusters with Cilium, however in this setup there seems to be a problem:
The Cilium status report reports synchronization errors for `bpf-map-sync-cilium_ipcache`, the operator runs without errors. The Cilium agent K8s health check does not fail, the pod is still reported as operable. The problem is reported right after starting the Cilium pods. 
I have Cilium itself also with "debug mode" enabled deployed, but no errors are reported, only debug & info messages.
It would be very appreciated if someone could clarify what is going wrong here. 
If needed, I could also provide the full log of a Cilium agent.

**Comment by pchaigno** [comment]
Could you upload a Cilium sysdump as per the template?

> I have run quite a few K8s clusters with Cilium, however in this setup there seems to be a problem:

Anything different in that cluster compared to the others?

**Comment by othmane399** [comment]
I have the same error, I've tried with 1.9.9 and it's working so maybe a bug

**Comment by rkulow** [comment]
> Anything different in that cluster compared to the others?

Actually the main change is the use of RancherOS. However, the [System Requirements](https://docs.cilium.io/en/stable/operations/system_requirements/#system-requirements) also list this, so it should also be possible in principle. 
I have not changed any values in the Cilium Helm Chart to avoid possible errors with my configuration, the error already occurs with the default values. 
 


> Could you upload a Cilium sysdump as per the template?

I can firstly provide the log from one of the Cilium agents:
[cilium-sjl6b_cilium-agent.log](https://github.com/cilium/cilium/files/6962495/cilium-sjl6b_cilium-agent.log)
This node is called `merkur-k8s1-master1`.
If the Cilium sysdump is still required according to the template, I would have to get it separately - just let me know.

**Comment by vincentmli** [comment]
> > Anything different in that cluster compared to the others?
> 
> Actually the main change is the use of RancherOS. However, the [System Requirements](https://docs.cilium.io/en/stable/operations/system_requirements/#system-requirements) also list this, so it should also be possible in principle.
> I have not changed any values in the Cilium Helm Chart to avoid possible errors with my configuration, the error already occurs with the default values.

@rkulow 
it looks rancher has coredns addon deploy job pod using host network, and cilium unable to remove the ipcache map for the pod that is using host network
level=debug msg="Skipped ipcache map delete on pod delete" error="pod is using host networking" hostIP=10.20.10.13 k8sNamespace=kube-system k8sPodName=rke-coredns-addon-deploy-job-pfbqt podIP=10.20.10.13 podIPs="[{10.20.10.13}]" subsys=k8s-watcher
level=debug msg="Skipped ipcache map delete on pod delete" error="pod is using host networking" hostIP=10.20.10.13 k8sNamespace=kube-system k8sPodName=rke-ingress-controller-deploy-job-xq8qq podIP=10.20.10.13 podIPs="[{10.20.10.13}]" subsys=k8s-watcher

does rke-corredns-addon-deploy-job and rke-ingress-controller-deploy-job pod require host network?

**Comment by othmane399** [comment]
So as I said before I have the same issue as you, but on EKS 1.18 with this kernel:
`Linux ip-172-20-109-31.eu-central-1.compute.internal 4.14.238-182.422.amzn2.x86_64 #1 SMP Tue Jul 20 20:35:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Today I've upgraded to 1.20 with this kernel version:
`Linux ip-172-20-69-58.eu-central-1.compute.internal 5.4.129-63.229.amzn2.x86_64 #1 SMP Tue Jul 20 21:22:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

and it's **working** !
@rkulow can you try to upgrade your kernel version to confirm

**Comment by rkulow** [comment]
Thank you for your responses. 

Now that RancherOS is in maintain-only-as-essential mode, I instructed today to switch the whole thing to Ubuntu. 
We are now using the Ubuntu 20.04 cloud image (kernel version 5.4.0) and everything works as desired. 

This means, however, that support for RancherOS from Cilium cannot be guaranteed at the moment. This should definitely be noted in the [documentation](https://docs.cilium.io/en/stable/operations/system_requirements/#system-requirements), RancherOS should at least get a footnote in the "Linux Distribution Compatibility Matrix". 
It might also be necessary to test if the problem is not caused by the older kernel version (linux 4.14), as @othmane399 noticed the same problem under a different OS. 

If all this is ok, then @vincentmli this issue can be closed.

**Comment by vincentmli** [comment]
> Thank you for your responses.
> 
> Now that RancherOS is in maintain-only-as-essential mode, I instructed today to switch the whole thing to Ubuntu.
> We are now using the Ubuntu 20.04 cloud image (kernel version 5.4.0) and everything works as desired.
> 

do you get  "Skipped ipcache map delete on pod delete" error="pod is using host networking" in cilium agent log  in Ubuntu 20.04 ? the answer probably is no, I suspect the pod with host network may somehow correlate with ipcache map sync error.

**Comment by katherinealbany** [comment]
I am experiencing the same issue installing Cilium using the CLI:

Cilium CLI: v0.8.6
Cilium Image: v1.10.3
Kubernetes: v1.18.20-eks-8c579e (AWS EKS Cluster)
Linux Kernal: 4.14.243-185.433.amzn2.x86_64

I have enabled debug logging and the only reference to `pod is using host networking` in the logs is for the `kube-proxy` pod ...

`level=debug msg="Skipped ipcache map delete on pod delete" error="pod is using host networking" hostIP=10.33.110.83 k8sNamespace=kube-system k8sPodName=kube-proxy-lkmkc podIP=10.33.110.83 podIPs="[{10.33.110.83}]" subsys=k8s-watcher`

I have also attached the full pod log
[cilium-7pzm7.log](https://github.com/cilium/cilium/files/7090560/cilium-7pzm7.log)

**Comment by pchaigno** [comment]
The last reports were on now-old Cilium versions, so we probably fixed this along the way and forgot to close this issue.
