### ISSUE TITLE
Move conntrack logic to separate BPF program to reduce complexity

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#17142]
[The conntrack logic](https://github.com/cilium/cilium/blob/master/bpf/lib/conntrack.h) represents a core part of our BPF datapath and has a strong impact on BPF complexity (number of instructions the verifier needs to analyze to establish the program is safe).  The conntrack lookup in particular is one of the very first steps of our datapath and requires a good number of conditional jumps; as a consequence, its impact on complexity is expected to be high.

To try and drastically reduce complexity across all datapath setups, we could move the conntrack logic to its own BPF program. It would run the conntrack lookup, store the result in a single-item BPF array, and tail call into the subsequent datapath pieces. Subsequent BPF program would then retrieve any conntrack state they need from the BPF array.

We will need to benchmark the cost of doing this map update + tail call + map lookup, but it's not expected to be big given the array map accesses can be inlined.

- [ ] Benchmark cost of array update + tail call + array lookup.
- [ ] Implement and test.
  - [x] For bpf_lxc: https://github.com/cilium/cilium/pull/19818
  - [ ] For bpf_host: https://github.com/cilium/cilium/pull/23831

**Comment by brb** [comment]
That would also allow us to do more sophisticated connection tracking. E.g., the lack of it might result in uneven LB distribution (https://github.com/cilium/cilium/issues/12518).
