### ISSUE TITLE
network package can not reach localhost from pod

### ISSUE THREAD

**Issue by gzdaodao** [cilium/cilium#17163]
**General Information**

- Cilium version (run `cilium version`)

Client: 1.10.2 319d2ac 2021-07-02T03:00:06+02:00 go version go1.16.5 linux/amd64
Daemon: 1.10.2 319d2ac 2021-07-02T03:00:06+02:00 go version go1.16.5 linux/amd64

- Kernel version (run `uname -a`)

Linux cephn1 5.4.38-gentoo-x86_64 #5 SMP Thu Jun 25 17:27:28 CST 2020 x86_64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz GenuineIntel GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, ...)

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"archive", BuildDate:"2021-08-10T13:06:35Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)

- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. instruction 1 
install  kubernetes and cilium

2. instruction 2
in the node ping pod ip that in same node,no response return

I have inserted  log rules in iptable mange input, mangle output, mangle prerouting,mangle postrouting, raw prerouting to the first rule of these chains to track which chian lost the package.

I run ping in the node cephn1 where the coredns pods(10.66.0.86)  run in the cephn1 node
#ping 10.66.0.85 -c1

system log show below:
```
8月 15 11:00:08 cephn1 kernel: OUTPUT_MAN: IN= OUT=cilium_host SRC=10.66.0.208 DST=10.66.0.86 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=53111 DF PROTO=ICMP TYPE=8 CODE=0 ID=14 SEQ=1 
8月 15 11:00:08 cephn1 kernel: POSTROUTING_MAN: IN= OUT=cilium_host SRC=10.66.0.208 DST=10.66.0.86 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=53111 DF PROTO=ICMP TYPE=8 CODE=0 ID=14 SEQ=1 MARK=0xc00 
8月 15 11:00:08 cephn1 kernel: PREROUTING_RAW: IN=lxc48dbfd495b6a OUT= MAC=de:91:2e:24:98:c1:be:1b:4a:cd:c4:90:08:00 SRC=10.66.0.86 DST=10.66.0.208 LEN=84 TOS=0x00 PREC=0x00 TTL=63 ID=34176 PROTO=ICMP TYPE=0 CODE=0 ID=14 SEQ=1 MARK=0x38c30f00 
8月 15 11:00:08 cephn1 kernel: PREROUTING_MAN: IN=lxc48dbfd495b6a OUT= MAC=de:91:2e:24:98:c1:be:1b:4a:cd:c4:90:08:00 SRC=10.66.0.86 DST=10.66.0.208 LEN=84 TOS=0x00 PREC=0x00 TTL=63 ID=34176 PROTO=ICMP TYPE=0 CODE=0 ID=14 SEQ=1 MARK=0x38c30f00
```
the system logs show that ping package can reach the coredns pod 
and received a reply package from the pods pair interface lxc48dbfd495b6a,
but the ping reply package lost after pretrouting chain in mangle table.

this sesms that bpf drop the reply package.

i have checked the policy of cilium which is set to default
and i have run cilium monitor -t drop in cilium pod in cephn1 but no drop logs 
i have run  cilium monitor to log all flow and the result below:

```
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
Listening for events on 48 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
-> overlay flow 0x26edb5dd identity remote-node->unknown state new ifindex cilium_vxlan orig-ip 0.0.0.0: 10.66.0.208:35418 -> 10.66.1.223:4240 tcp ACK
-> endpoint 852 flow 0x9acdeb19 identity host->health state new ifindex lxc_health orig-ip 10.66.0.208: 10.66.0.208:57262 -> 10.66.0.85:4240 tcp SYN
-> stack flow 0x8d52ca1f identity health->host state reply ifindex 0 orig-ip 0.0.0.0: 10.66.0.85:4240 -> 10.66.0.208:57262 tcp SYN, ACK
-> endpoint 1768 flow 0x0 identity host->14531 state established ifindex lxc48dbfd495b6a orig-ip 10.66.0.208: 10.66.0.208 -> 10.66.0.86 EchoRequest
-> stack flow 0x0 identity 14531->host state reply ifindex 0 orig-ip 0.0.0.0: 10.66.0.86 -> 10.66.0.208 EchoReply
-> endpoint 852 flow 0x438799b1 identity host->health state established ifindex lxc_health orig-ip 10.66.0.208: 10.66.0.208:57234 -> 10.66.0.85:4240 tcp SYN
-> stack flow 0x257c593e identity health->host state reply ifindex 0 orig-ip 0.0.0.0: 10.66.0.85:4240 -> 10.66.0.208:57234 tcp SYN, ACK
-> endpoint 852 flow 0x0 identity remote-node->health state new ifindex lxc_health orig-ip 10.66.1.188: 10.66.1.188:58644 -> 10.66.0.85:4240 tcp SYN
-> overlay flow 0x6ebdd72d identity health->unknown state new ifindex cilium_vxlan orig-ip 0.0.0.0: 10.66.0.85:4240 -> 10.66.1.188:58644 tcp SYN, ACK
-> endpoint 852 flow 0x0 identity remote-node->health state established ifindex lxc_health orig-ip 10.66.1.188: 10.66.1.188:58644 -> 10.66.0.85:4240 tcp ACK
-> endpoint 852 flow 0x0 identity remote-node->health state established ifindex lxc_health orig-ip 10.66.1.188: 10.66.1.188:58644 -> 10.66.0.85:4240 tcp ACK
-> overlay flow 0x6ebdd72d identity health->unknown state new ifindex cilium_vxlan orig-ip 0.0.0.0: 10.66.0.85:4240 -> 10.66.1.188:58644 tcp ACK
```

**Comment by gzdaodao** [comment]
but ping can receive reply form the pods in other nodes 


# kubectl -n kube-system exec -it cilium-qw9v8 -- cilium-health status

Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
Probe time:   2021-08-15T03:41:40Z
Nodes:
  cephn1 (localhost):
    Host connectivity to 192.168.22.11:
      ICMP to stack:   OK, RTT=546.237µs
      HTTP to agent:   OK, RTT=494.021µs
    Endpoint connectivity to 10.66.0.85:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.66.0.85:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  cephn2:
    Host connectivity to 192.168.22.12:
      ICMP to stack:   OK, RTT=676.5µs
      HTTP to agent:   OK, RTT=1.30649ms
    Endpoint connectivity to 10.66.1.223:
      ICMP to stack:   OK, RTT=560.32µs
      HTTP to agent:   OK, RTT=1.542557ms

**Comment by pchaigno** [comment]
>  install kubernetes and cilium

How exactly? That is, what commands did you run?

Could you share a sysdump of the cluster?

**Comment by gzdaodao** [comment]
> > install kubernetes and cilium
> 
> How exactly? That is, what commands did you run?
> 
> Could you share a sysdump of the cluster?

sorry i can't download the dump tool (https://git.io/cilium-sysdump-latest.zip) in china, 
the domain had been deny by the GFW.

I have install 2 new server with the latest gentoo system and got the same problem,
I installed kubernetes with external etcd.
here is my inistall script 

##################################################################
#003.deploy.kubeadm.sh
##################################################################
#!/bin/bash


cp kubelet /etc/kubernetes/kubelet

mkdir -p /etc/kubernetes/pki/etcd/
cp /etc/etcd/ssl/ca.pem /etc/kubernetes/pki/etcd/ca.crt
cp /etc/etcd/ssl/etcd.pem /etc/kubernetes/pki/apiserver-etcd-client.crt
cp /etc/etcd/ssl/etcd-key.pem /etc/kubernetes/pki/apiserver-etcd-client.key

export CONTAINER_RUNTIME_ENDPOINT=unix:///run/containerd/containerd.sock
#kubeadm init --config kubeadm-config.yaml --upload-certs --v=10 #firt try fail
kubeadm init --config kubeadm-config.yaml --upload-certs --skip-phases=addon/kube-proxy --v=10


##################################################################
#kubelet config file
##################################################################
###
# kubernetes kubelet (minion) config

# The address for the info server to serve on (set to 0.0.0.0 or "" for all interfaces)
#KUBELET_ADDRESS="--address=0.0.0.0"

# The port for the info server to serve on
#KUBELET_PORT="--port=10250"

# You may leave this blank to use the actual hostname
#KUBELET_HOSTNAME="--hostname-override=127.0.0.1"

# Edit the kubelet.kubeconfig to have correct cluster server address
#KUBELET_KUBECONFIG=/etc/kubernetes/kubelet.kubeconfig

# Add your own!
KUBELET_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --image-service-endpoint=unix:///run/containerd/containerd.sock  --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --network-plugin=cni"

##################################################################
#kubeadm config file
##################################################################
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: mh6xge.mkn42ih411111111
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.22.11
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  name: cephn1
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: "192.168.22.222:6443"
controllerManager: {}
dns:
  type: CoreDNS
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: 1.21.3
etcd:
  external:
    endpoints:
    - https://192.168.22.11:2379
    - https://192.168.22.12:2379
    - https://192.168.100.28:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/16
  podSubnet: 10.66.0.0/16
scheduler: {}
#---
#apiVersion: kubeproxy.config.k8s.io/v1alpha1
#kind: KubeProxyConfiguration
#mode: ipvs

##################################################################
#005.install.cilium.py
##################################################################
!/usr/bin/python
import sys
import os
import time

cilium = None
try:
    cilium = os.popen('kubectl -n kube-system get pods -l k8s-app=cilium').read().split('\n')[1].split()[0]
except Exception as e:
    pass

if cilium:
    pass
else:
    os.system('helm repo add cilium https://helm.cilium.io/')
   # 1.10.3  not work
   #res = os.popen('helm template cilium cilium/cilium --version 1.10.3 --namespace kube-system  --set hostServices.enabled=true --set kubeProxyReplacement=strict --set k8sServiceHost=192.168.22.222 --set k8sServicePort=6443').read()
    #res = os.popen('helm template cilium cilium/cilium --version 1.10.3 --namespace kube-system').read()
    #
    #try 1.10.2
    res = os.popen('helm template cilium cilium/cilium --version 1.10.2 --namespace kube-system  --set hostServices.enabled=true --set kubeProxyReplacement=strict --set k8sServiceHost=192.168.22.222 --set k8sServicePort=6443').read()
    #use kubernetes mode for ipam
    res = res.replace('ipam: "cluster-pool"', 'ipam: "kubernetes"').replace('cluster-pool-ipv4-', '#cluster-pool-ipv4-')
    with open('cilium-1.10.2.yaml', 'w') as f:
        f.write(res)
    #run install in k8s
    os.system('kubectl -n kube-system apply -f cilium-1.10.2.yaml')

**Comment by pchaigno** [comment]
The sysdump you shared doesn't have any Cilium-managed pods.

**Comment by gzdaodao** [comment]
> The sysdump you shared doesn't have any Cilium-managed pods.

sysdump update here  https://github.com/gzdaodao/cilium_issue_logs/blob/master/cilium-sysdump-20210817-092922.zip

but the dump process show an error
ERROR Error: Command 'kubectl get cep -o yaml --all-namespaces > ./cilium-sysdump-20210817-092922/cep-20210817-092925.yaml' returned non-zero exit status 1.. Could not collect cilium endpoints cep-20210817-092925.yaml


``` log
cephn1 /cephfs/k8s # kubectl -n kube-system get all
NAME                                  READY   STATUS    RESTARTS   AGE
pod/cilium-operator-685f6c78b-jmz47   1/1     Running   0          23m
pod/cilium-operator-685f6c78b-r2qnk   1/1     Running   0          23m
pod/cilium-rq4jj                      1/1     Running   0          23m
pod/cilium-sq9sc                      1/1     Running   0          20m
pod/coredns-558bd4d5db-ct8tr          0/1     Pending   0          24m
pod/coredns-558bd4d5db-xbwjg          0/1     Pending   0          24m
pod/kube-apiserver-cephn1             1/1     Running   0          24m
pod/kube-apiserver-cephn2             1/1     Running   0          20m
pod/kube-controller-manager-cephn1    1/1     Running   0          25m
pod/kube-controller-manager-cephn2    1/1     Running   0          20m
pod/kube-scheduler-cephn1             1/1     Running   0          24m
pod/kube-scheduler-cephn2             1/1     Running   0          20m

NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
service/kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   25m

NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/cilium   2         2         2       2            2           <none>          23m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cilium-operator   2/2     2            2           23m
deployment.apps/coredns           0/2     2            0           25m

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/cilium-operator-685f6c78b   2         2         2       23m
replicaset.apps/coredns-558bd4d5db          2         2         0       24m
```

**Comment by pchaigno** [comment]
The above `kubectl -n kube-system get all` output shows that there are no running Cilium-managed pods. The only two pods that are not running in the host network namespace are the CoreDNS pods and they are stuck in Pending state with:

    0/2 nodes are available: 2 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.

Is that expected? What pod(s) did you ran your ping from/to?

**Comment by gzdaodao** [comment]
> The above `kubectl -n kube-system get all` output shows that there are no running Cilium-managed pods. The only two pods that are not running in the host network namespace are the CoreDNS pods and they are stuck in Pending state with:
> 
> ```
> 0/2 nodes are available: 2 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
> ```
> 
> Is that expected? What pod(s) did you ran your ping from/to?

In this cluster, i have 2 nodes as controlPlane node and also allow them to work as worknode.
I have tried to install cilium before or after i run, the follow command to allow all node work as worknode:
```
kubectl taint node --all node-role.kubernetes.io/master:NoSchedule-
```
The problem still exists.

I think the reason of nodes remain not-ready is the problem i have report in this issues: cilium can't pass network package to the localhost stack. 
Cilium health check can't pass and send "CNI not ready" to kubernetes that nodes remain not-ready.

My ping is from the one of the node "cephn1" and to the cephn1's  cilium pod's health process IP that show  by cilium-health status that show me the timeout error.


In addition, I don't understand what is the " Cilium-managed pods"?  
I have successed install cilium in another 2 nodes cluster lasts month, that cluster have only two types of cilium pods like this cluster： cilium and cilium-operator.
Is there a third type of cilium pods?

**Comment by gzdaodao** [comment]
I have found the problem @pchaigno thank you very much.
I have missed the note in https://docs.cilium.io/en/v1.10/operations/system_requirements/#admin-system-reqs

My new installed system's systemd version is systemd 248
this version need some fix by running the follow commands:
```
echo 'net.ipv4.conf.lxc*.rp_filter = 0' > /etc/sysctl.d/99-override_cilium_rp_filter.conf
systemctl restart systemd-sysctl
```
