### ISSUE TITLE
Trying to understand how Cilium transparently redirect traffic to Envoy by Sockmap

### ISSUE THREAD

**Issue by yunbo-xufeng** [cilium/cilium#17172]
Hello All,

### Question
Based on https://cilium.io/blog/2018/08/07/istio-10-cilium，I know Cilium uses Sockmap to transparently redirect app traffic to Envoy，so I refer to latest Cilium source codes and trying to understand how Cilium implement it，but I can't totally understand the implementation after reading the source codes, really appreciate it if anybody could give me an answer, basically, the question is where Cilium create the socket connection to Envoy proxy port from the source code side?

### Details
It's very clear for the bpf side, sockops bpf prog catch tcp connection events(BPF_SOCK_OPS_PASSIVE_ESTABLISHED_CB and BPF_SOCK_OPS_ACTIVE_ESTABLISHED_CB) and update sockmap by inserting the tuple key and socket value，after that, Skmsg bpf prog intercept sendmsg/sendfile request，assemble the tuple key and redirect the message the the destination socket(Envoy proxy port), all these sockmap bpf stuff initialization is done in daemon/cmd/daemon.go.
However, it's not clear where Cilium trigger the socket connection create event to Envoy proxy port, I found this call chain in the source code: 
        `CreateOrUpdateRedirect() --> ackProxyPort() --> InstallProxyRules() --> iptProxyRules() --> addProxyRules()`
after read these codes, as far as I understand，Cilium actually uses TPROXY to redirect packets，I didn't find where the socket connect to Envoy proxy port created so as to trigger the bpf sockops program.

Was I miss something?

Thanks!
Xufeng

**Comment by vincentmli** [comment]
> Hello All,
> 
> ### Question
> Based on [https://cilium.io/blog/2018/08/07/istio-10-cilium，I](https://cilium.io/blog/2018/08/07/istio-10-cilium%EF%BC%8CI) know Cilium uses Sockmap to transparently redirect app traffic to Envoy，so I refer to latest Cilium source codes and trying to understand how Cilium implement it，but I can't totally understand the implementation after reading the source codes, really appreciate it if anybody could give me an answer, basically, the question is where Cilium create the socket connection to Envoy proxy port from the source code side?
> 
> ### Details
> It's very clear for the bpf side, sockops bpf prog catch tcp connection events(BPF_SOCK_OPS_PASSIVE_ESTABLISHED_CB and BPF_SOCK_OPS_ACTIVE_ESTABLISHED_CB) and update sockmap by inserting the tuple key and socket value，after that, Skmsg bpf prog intercept sendmsg/sendfile request，assemble the tuple key and redirect the message the the destination socket(Envoy proxy port), all these sockmap bpf stuff initialization is done in daemon/cmd/daemon.go.
> However, it's not clear where Cilium trigger the socket connection create event to Envoy proxy port, I found this call chain in the 

I may not understand your question and I am not familiar with sockmap. I just assume you may be asking when the BPF_SOCK_OPS_PASSIVE_ESTABLISHED_CB event is created to trigger sockops bpf prog, if so, the event is created here in the kernel if I undertand it correct
```
   5   6408  net/ipv4/tcp_input.c <<tcp_rcv_state_process>>
             tcp_init_transfer(sk, BPF_SOCK_OPS_PASSIVE_ESTABLISHED_CB,

        case TCP_SYN_RECV:                                                       
                tp->delivered++; /* SYN-ACK delivery isn't tracked in tcp_ack */ 
                if (!tp->srtt_us)                                                
                        tcp_synack_rtt_meas(sk, req);                            
                                                                                 
                if (req) {                                                       
                        tcp_rcv_synrecv_state_fastopen(sk);                      
                } else {                                                         
                        tcp_try_undo_spurious_syn(sk);                           
                        tp->retrans_stamp = 0;                                   
                        tcp_init_transfer(sk, BPF_SOCK_OPS_PASSIVE_ESTABLISHED_CB,
                                          skb);                                  
                        WRITE_ONCE(tp->copied_seq, tp->rcv_nxt);                 
                }                                                                
                smp_mb();                                                        
                tcp_set_state(sk, TCP_ESTABLISHED);                              
                sk->sk_state_change(sk);                                        

void tcp_init_transfer(struct sock *sk, int bpf_op, struct sk_buff *skb)         
{                                                                                
        struct inet_connection_sock *icsk = inet_csk(sk);                        
        struct tcp_sock *tp = tcp_sk(sk);                                        
                                                                                 
        tcp_mtup_init(sk);                                                       
        icsk->icsk_af_ops->rebuild_header(sk);                                   
        tcp_init_metrics(sk);                                                    
                                                                                 
        /* Initialize the congestion window to start the transfer.               
         * Cut cwnd down to 1 per RFC5681 if SYN or SYN-ACK has been             
         * retransmitted. In light of RFC6298 more aggressive 1sec               
         * initRTO, we only reset cwnd when more than 1 SYN/SYN-ACK              
         * retransmission has occurred.                                          
         */                                                                      
        if (tp->total_retrans > 1 && tp->undo_marker)                            
                tp->snd_cwnd = 1;                                                
        else                                                                     
                tp->snd_cwnd = tcp_init_cwnd(tp, __sk_dst_get(sk));              
        tp->snd_cwnd_stamp = tcp_jiffies32;                                      
                                                                                 
        icsk->icsk_ca_initialized = 0;                                           
        bpf_skops_established(sk, bpf_op, skb);                                  
        if (!icsk->icsk_ca_initialized)                                          
                tcp_init_congestion_control(sk);                                 
        tcp_init_buffer_space(sk);                                               
}                                                          

static void bpf_skops_established(struct sock *sk, int bpf_op,                   
                                  struct sk_buff *skb)                           
{                                                                                
        struct bpf_sock_ops_kern sock_ops;                                       
                                                                                 
        sock_owned_by_me(sk);                                                    
                                                                                 
        memset(&sock_ops, 0, offsetof(struct bpf_sock_ops_kern, temp));          
        sock_ops.op = bpf_op;                                                    
        sock_ops.is_fullsock = 1;                                                
        sock_ops.sk = sk;                                                        
        /* sk with TCP_REPAIR_ON does not have skb in tcp_finish_connect */      
        if (skb)                                                                 
                bpf_skops_init_skb(&sock_ops, skb, tcp_hdrlen(skb));             
                                                                                 
        BPF_CGROUP_RUN_PROG_SOCK_OPS(&sock_ops);                                 
}                                                   


```

**Comment by yunbo-xufeng** [comment]
> > Hello All,
> > ### Question
> > Based on [https://cilium.io/blog/2018/08/07/istio-10-cilium，I](https://cilium.io/blog/2018/08/07/istio-10-cilium%EF%BC%8CI) know Cilium uses Sockmap to transparently redirect app traffic to Envoy，so I refer to latest Cilium source codes and trying to understand how Cilium implement it，but I can't totally understand the implementation after reading the source codes, really appreciate it if anybody could give me an answer, basically, the question is where Cilium create the socket connection to Envoy proxy port from the source code side?
> > ### Details
> > It's very clear for the bpf side, sockops bpf prog catch tcp connection events(BPF_SOCK_OPS_PASSIVE_ESTABLISHED_CB and BPF_SOCK_OPS_ACTIVE_ESTABLISHED_CB) and update sockmap by inserting the tuple key and socket value，after that, Skmsg bpf prog intercept sendmsg/sendfile request，assemble the tuple key and redirect the message the the destination socket(Envoy proxy port), all these sockmap bpf stuff initialization is done in daemon/cmd/daemon.go.
> > However, it's not clear where Cilium trigger the socket connection create event to Envoy proxy port, I found this call chain in the
> 
> I may not understand your question and I am not familiar with sockmap. I just assume you may be asking when the BPF_SOCK_OPS_PASSIVE_ESTABLISHED_CB event is created to trigger sockops bpf prog, if so, the event is created here in the kernel if I undertand it correct

Thanks for your reply!

Actually, I want to know when the user space side(Cilium source codes) triggers the 'connect' syscall to Envoy proxy port, so that BPF_SOCK_OPS_PASSIVE_ESTABLISHED_CB or BPF_SOCK_OPS_ACTIVE_ESTABLISHED_CB event is caught by sockops bpf program and insert the accordingly socket into sockmap, this is how sockmap redirection works.

**Comment by yunbo-xufeng** [comment]
Maybe @jrfastab knows the question very well.

**Comment by vincentmli** [comment]
> 
> Actually, I want to know when the user space side(Cilium source codes) triggers the 'connect' syscall to Envoy proxy port, so that BPF_SOCK_OPS_PASSIVE_ESTABLISHED_CB or BPF_SOCK_OPS_ACTIVE_ESTABLISHED_CB event is caught by sockops bpf program and insert the accordingly socket into sockmap, this is how sockmap redirection works.

Are you sure the user space will trigger "connect" syscall to Envoy proxy? not some kind of BPF magic to do this in kernel to "redirect" the request to Envoy? triggering syscall from userspace for each connection seems not efficient, of course I don't know the detail  so I am talking out of imagination :)  maybe you can turn on some kind debug or tracing in Cilium for Envoy proxy processing and follow through the code, if it is user space triggering regular connect syscall, you could  use strace or use BPF tracing magic to see if there is connect syscall, I am interested to know how it works too :)

**Comment by jrfastab** [comment]
Late reply, just noticed while cleaning up github issues for the new year. As noted above sockmap only comes into the picture after the socket enters ESTABLISHED state (technically just before ESTABLISHED state from kernel side). So this is not really a question about sockmap, but instead how does Cilium redirect SYN (3 way handshake) to Envoy. This is done with TPROXY redirects in the kernel based on the network policy. However, once the 3WHS is done Sockmap kicks in and redirects data directly to Envoy, when this is enabled.
