### ISSUE TITLE
Proposal: make tc filter priority configurable

### ISSUE THREAD

**Issue by intel-dlanders** [cilium/cilium#17193]
## Proposal / RFE

cilium needs to allow for some tc filters to be applied prior to cilium's filters. One way would be to allow the priority of cilium's filters to be configurable so that a user can define a higher priority filter to be applied, first.

Please see https://cilium.slack.com/archives/C1MATJ5U5/p1627654296014100.

Below is an example where I changed the cilium tc filter priority to 2 so that I could define my own priority 1 filter.

```
git diff 6944e273bc7e2cc18d6181de3ec6f5bd550b174c pkg/datapath/loader/netlink.go
diff --git a/pkg/datapath/loader/netlink.go b/pkg/datapath/loader/netlink.go
index d7291790c..cbabe1af0 100644
--- a/pkg/datapath/loader/netlink.go
+++ b/pkg/datapath/loader/netlink.go
@@ -81,9 +82,10 @@ func (l *Loader) replaceDatapath(ctx context.Context, ifName, objPath, progSec,
 
        // FIXME: replace exec with native call
        args := []string{"filter", "replace", "dev", ifName, progDirection,
-               "prio", "1", "handle", "1", "bpf", "da", "obj", objPath,
-               "sec", progSec,
+               "prio", "2", "handle", "1", "bpf", "da", "obj", objPath, // dla - def prio 1`
+               "sec", progSec, //"pipe", "action", "continue",
        }
        cmd = exec.CommandContext(ctx, "tc", args...).WithFilters(libbpfFixupMsg)
        _, err = cmd.CombinedOutput(log, true)
        if err != nil {
```
Would also need to address bpf/init.sh:
```
261 tc replace dev $DEV clsact \|\| true
262 [ -z "$(tc filter show dev $DEV $WHERE \| grep -v 'pref 1 bpf chain 0 $\\|pref 1 bpf chain 0 handle 0x1')" ] \|\| tc filter del dev $DEV $WHERE
263 cilium-map-migrate -s $OUT
```

**Is your feature request related to a problem?**
I am unable to apply my own custom filters.

**Describe the solution you'd like**
Some way to configure the priority of cilium's tc filters, besides rebuilding binaries.

**Comment by joestringer** [comment]
From my perspective I think it's quite reasonable to expose a commandline flag (via `daemon/cmd/daemon_main.go`) to be able to configure this parameter.

By default to minimize changes, I would expect the value to be "prio 1" since I'm not sure what would happen if we upgraded from one version of Cilium with "prio 1" to another version with "prio 2" -- worst case we could end up unintentionally attaching the BPF programs to both priorities and running the datapath logic twice.

**Comment by pchaigno** [comment]
@intel-dlanders Do you want to send a pull request for this new agent flag?

**Comment by intel-dlanders** [comment]
ok, yeah, that's what I was using. just wanted to make sure there wasn't something more specific I should call it.
