### ISSUE TITLE
cillium-operator fail to start "Unable to listen on localhost:9234 for healthz apiserver"

### ISSUE THREAD

**Issue by LuckySB** [cilium/cilium#17194]
## Bug report

Node in my cluster have name as `node-1.k8s.domain.net`, `node-2.k8s.domain.net`, etc
in DNS no records for this name.
All records in /etc/hosts on all nodes in cluster.

But i have wildcard DNS record 
```
*.domain.net. IN A 11.22.33.44
```
So, cillium operator fail to start with this log:

```
level=info msg="  --operator-api-serve-addr='localhost:9234'" subsys=cilium-operator
...
level=info msg="Cilium Operator 1.9.9 5bcf83c 2021-07-19T16:45:00-07:00 go version go1.15.14 linux/amd64" subsys=cilium-operator
level=info msg="Establishing connection to apiserver" host="https://10.233.0.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=fatal msg="Unable to listen on localhost:9234 for healthz apiserver" error="listen tcp 11.22.33.44:9234: bind: cannot assign requested address" subsys=cilium-operator
```

pod with cillium operator work in hostnetwork mode, and 
I suppose that cillium-operator get `localhost` as address to bind, and not see into /etc/host to get 127.0.0.1 
```
# Kubernetes-managed hosts file (host network).
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
```
but do DNS lookup for node hostname - `node-2.k8s.domain.net`, get ip address from wildcard record in domain zone,
and try to bind on 11.22.33.44:9234.

WorkAround - i set in config
`operator-api-serve-addr='127.0.0.1:9234'`

**General Information**

- Cilium version 1.9.9
- Kernel version kernel-lt-5.4 from elrepo
- k8s version 1.21.1
- Orchestration system version in use Centos 7, kernel-lt-5.4 from elrepo, CRI containerd
- Link to relevant artifacts - cluster installed by kubespray from master branch
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. add wildcard record to DNS for kube node hostname zone
2. install cluster by kubespray ansible scenario

**Comment by aanm** [comment]
@LuckySB were you able to figure out what the issue was? Thank you

**Comment by LuckySB** [comment]
no.
I thought the cilium authors should fix this bug.

**Comment by project-administrator** [comment]
For us it's failing with this error:
```
level=fatal msg="Unable to start healthz status API server" address="127.0.0.1:9879" error="listen tcp 127.0.0.1:9879: bind: address already in use" subsys=daemon
```
I logged onto the faulty node, and netstat show me this:
```
[root@admin]# netstat -npat|grep 9879
tcp        0      0 127.0.0.1:9879          0.0.0.0:*               LISTEN      1280/containerd
```
Is this **containerd** occupying the same port that **cilium** is trying to use? ..
