### ISSUE TITLE
CI: Travis CI - Pull Request Build Errored

### ISSUE THREAD

**Issue by xinyuanzzz** [cilium/cilium#17228]
## CI failure

Occurred on #17114

```
Worker information
hostname: 7a6eae02-c9f5-479e-b35a-f1a26e50926c@901537.ip-10-67-28-103
version: ? ?
instance: ip-10-67-28-255.ec2.internal ec2 (via amqp)
startup: 45.399733198s
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

https://app.travis-ci.com/github/cilium/cilium/jobs/533340780

**Comment by tklauser** [comment]
Thanks for the report. This looks like an issue with the Travis CI infrastructure to me. I've re-triggered the job to check.

**Comment by xinyuannn** [comment]
Thanks! But I don't see the test is retriggered in the PR. Could you please check it?

**Comment by tklauser** [comment]
Done: https://app.travis-ci.com/github/cilium/cilium/jobs/533340780

Note that in the PR itself, the Travis CI status might still be shown as failed. It should be updated once the CI run completed.

**Comment by xinyuannn** [comment]
Got it with thanks!

**Comment by tklauser** [comment]
Travis CI now passed after retriggering, so it indeed looks like this was a temporary Travis infrastructure glitch.

Thus closing this issue. Please comment here if you see this again on some other PR.
