### ISSUE TITLE
hubble/datapath: Clarify NodePort BPF related events in flow log

### ISSUE THREAD

**Issue by brb** [cilium/cilium#17237]
Currently, it's not so obvious at what point(s) we emit events to Hubble from the datapath when processing a NodePort BPF request. One example of such a confusion is https://github.com/cilium/cilium/issues/17060#issuecomment-900845354 (check the hubble observe output).

This task is about clarifying when do we emit events in the processing path (i.e., before/after (rev-)SNAT/DNAT), and then documenting our findings.

**Comment by pchaigno** [comment]
Closing in favor of https://github.com/cilium/cilium/issues/14885. I've added another point there to remember to clarify positions of observation points with regard to (rev-)SNAT/DNAT.
