### ISSUE TITLE
Support CNI v0.4.0 with new CHECK action

### ISSUE THREAD

**Issue by Nyatsume** [cilium/cilium#17251]
Currently, cilium-cni supports 0.1.x-0.3.x.

- Kubernetes supports CNI v.0.4.0
- Coil(https://github.com/cybozu-go/coil) uses only CNI v0.4.0, so it cannot be used in combination with cilium.
- By supporting v0.4.0, cilium will be able to use the CHECK command.

It would be nice if cIlium could support v0.4.0.

**Comment by Nyatsume** [comment]
> > Currently, cilium-cni supports 0.1.x-0.3.x.
> 
> Are there errors when trying with v0.4.0 or did you see these versions documented somewhere?

- An error occurred when I tried to configure the following settings.
Config:
```
{
  "cniVersion": "0.4.0",
  "name": "generic-veth",
  "plugins": [
    {
      "type": "coil",
      "socket": "/run/coild.sock"
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type": "cilium-cni"
    }
  ]
}
```
error:
`incompatible CNI versions; config is "0.4.0", plugin supports ["0.1.0" "0.2.0" "0.3.0" "0.3.1"]`

- The relevant code is [here.](https://github.com/cilium/cilium/blob/a8e3fa283cf40b330035265bf83d63800b296bcf/plugins/cilium-cni/cilium-cni.go#L72)
- Currently, we are adding v0.3.1 support to coil as a workaround.

**Comment by mKeRix** [comment]
In case people find this thread through Google: aws-cni v1.10.2 (latest at the time of writing) switched to CNI config 0.4.0 as well. To get CNI chaining with aws-cni working you will need to downgrade to v1.10.1.

**Comment by pchaigno** [comment]
Adding support for CNI v0.4.0 would require us to support the new CHECK API (cf. https://github.com/containernetworking/cni/pull/579). Once that is done, it should be as simple as updating [the list of supported versions](https://github.com/cilium/cilium/blob/a1a47b76dde961baa77d33de5d21df53ab616980/plugins/cilium-cni/cilium-cni.go#L83) and [the version we test in CI](https://github.com/cilium/cilium/blob/a1a47b76dde961baa77d33de5d21df53ab616980/plugins/cilium-cni/cni-install.sh#L209).

**Comment by squeed** [comment]
Taking a look at this; first we can get CHECK plumbed up, then add more things to, well, check.

**Comment by squeed** [comment]
Will have a first attempt at this shortly.

One open question: should we validate the route table (against the CNI Result) as well? My instinct is no.

**Comment by squeed** [comment]
OK, PR filed. Not too bad :-)
