### ISSUE TITLE
How can I compile cilium and deploy it in k8s cluster by myself 

### ISSUE THREAD

**Issue by leguandemomotou** [cilium/cilium#17254]
## Proposal / RFE

**Is your feature request related to a problem?**

**Describe the solution you'd like**
hello,i add some code in cilium，but make is error,the error message is as follows，I want to consult how to compile cilium？
root@i-ja9q1988:~/cilium# make
/bin/bash: docker: command not found
contrib/scripts/check-logging-subsys-field.sh
contrib/scripts/check-fmt.sh
contrib/scripts/check-log-newlines.sh
contrib/scripts/check-missing-tags-in-tests.sh
contrib/scripts/check-assert-deep-equals.sh
contrib/scripts/lock-check.sh
contrib/scripts/custom-vet-check.sh
main: ./... matched no packages
exit status 1

**Comment by pchaigno** [comment]
It seems you at least need to install Docker.

**Comment by leguandemomotou** [comment]
thank you
