### ISSUE TITLE
Switch from using awk and grep to jsonpath for command-line output parsing

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1725]
Currently in our tests, we use a combination of `awk` and `grep` to get output from `cilium` and `kubectl` commands. Switch to using `jsonpath` so we are not reliant upon ordering of output from `awk` and `grep`.

**Comment by rlenglet** [comment]
@ianvernon I don't know whether you had a specific tool in mind, but I'd recommend looking at [jq](https://stedolan.github.io/jq/) for JSON parsing / processing.

**Comment by tgraf** [comment]
@ianvernon Given the switch to ginkgo, can we close this?

**Comment by ianvernon** [comment]
Some of the ginkgo stuff is running CLI commands which still uses `awk` and `grep`, which needs to be fixed still, so we still need to tackle this.
