### ISSUE TITLE
Cilium refuses to start with a network interface ifindex that exceeds max(uint16)

### ISSUE THREAD

**Issue by clrxbl** [cilium/cilium#17259]
## Bug report

If Cilium is started with the `--devices` parameter set to a specific network interface that has an ifindex higher than max(uint16), Cilium refuses to start by crashing with a fatal error message. Temporary workaround for this is to restart the server where the cilium-agent is trying to run on, but this is obviously not acceptable in the long run.

**General Information**

- Cilium version:
```
Client: 1.10.3 4145278 2021-07-15T16:11:03+02:00 go version go1.16.6 linux/amd64
Daemon: 1.10.3 4145278 2021-07-15T16:11:03+02:00 go version go1.16.6 linux/amd64
```
- Kernel version
```
Linux dev1 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux dev2 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux dev3 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"archive", BuildDate:"2021-08-19T21:28:12Z", GoVersion:"go1.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...): Not applicable.
- Generate and upload a system zip: Not applicable.

**How to reproduce the issue**

1. You start Cilium with the `--devices` parameter set to a specific network interface that has an ifindex that exceeds max(uint16)
2. Cilium crashes with the following message:

```
level=fatal msg="tailscale0 link ifindex 93715 exceeds max(uint16)" subsys=daemon
```
(tailscale0 being the network interface in question)

**Comment by pchaigno** [comment]
It seems that check was introduced in https://github.com/cilium/cilium/commit/4709f0ba3f1ccfdad5741093ee7e9ea5375d0a16 and the longer term fix is described in the commit message:
> The first restriction will go away once we introduce the surrogate id => ifindex BPF map.

So I'm guessing the limitation here is from the `ifindex` field of `ct_entry` and `ct_state`. /cc @brb

**Comment by clrxbl** [comment]
I do wonder, why has uint16 been chosen when an ifindex can exceed uint16?

**Comment by pchaigno** [comment]
`git blame` can probably answer that. I suspect the map entry was sized before we started using the interface index.

**Comment by brb** [comment]
@clrxbl The ifindex needs to be stored in `ct_entry.ifindex`. Unfortunately, the `ct_entry` struct only had u16 available (we cannot easily change the struct, as it would interrupt open connections after the upgrade).

**Comment by brb** [comment]
Closing as it duplicates https://github.com/cilium/cilium/issues/16260.
