### ISSUE TITLE
Extend `cilium encrypt` to provide information on WireGuard Transparent Encryption.

### ISSUE THREAD

**Issue by h3llix** [cilium/cilium#17274]
PR #16770 Introduced `cilium encrypt status` that provides information about the IPsec-based transparent encryption. But this could be extended to provide information on WireGuard too.

**Comment by pchaigno** [comment]
@gandro @brb What would make sense to display here? Any source(s) of errors we should highlight? For IPsec, we display the following information.
```
cilium encrypt status
  Encryption: ipsec
  NodeEncryption: disabled
  Keys in use: 2
  Max. sequence number: 0xffffbd4f/0xffffffff
  Errors: 12
    XfrmInStateProtoError 12
```

**Comment by brb** [comment]
- `Encryption: WireGuard`
- `NodeEncryption: disabled`
- PubKey base64
- Number of endpoints

**Comment by h3llix** [comment]
@pchaigno please assign it to me.

**Comment by pchaigno** [comment]
@h3llix Don't hesitate to reach... well, you know the drill :smile: Thanks for tackling this!
