### ISSUE TITLE
Node Pod CIDR conflicts  when IPAM is "cluster-pool" mode 

### ISSUE THREAD

**Issue by lrouter** [cilium/cilium#17277]
HiI have also encounter the same problem. The cilium IPAM mode is “cluster pool”, and there are 225 ndoes in the cluster. Some nodes have conflict pod cidrs.
The cilium version: 1.8.9
The cilium configmap:
```
apiVersion: v1
data:
  auto-direct-node-routes: "false"
  bpf-ct-global-tcp-max: "10485760"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cluster-name: default
  **cluster-pool-ipv4-cidr: 172.16.0.0/16
  cluster-pool-ipv4-mask-size: "24"**
  debug: "false"
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  **ipam: cluster-pool
  k8s-require-ipv4-pod-cidr: "true"
  k8s-require-ipv6-pod-cidr: "false"**
  kube-proxy-replacement: disabled
  masquerade: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "false"
```

The control-manager options:
`kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=172.16.0.0/16 --cluster-name=kubernetes --controllers=*,bootstrapsigner,tokencleaner --leader-elect=true --node-cidr-mask-size=24 --port=0 --service-cluster-ip-range=172.26.0.0/16`

The list of conflict pod cidrs and corresponded nodes are:
```
172.16.128.0/24   172.16.128.146   10.157.21.33
172.16.128.0/24   172.16.128.163   10.157.21.38
172.16.211.0/24   172.16.211.233   10.157.146.151
172.16.211.0/24   172.16.211.79    10.157.114.145
172.16.237.0/24   172.16.237.67    10.144.181.205
172.16.237.0/24   172.16.237.74    10.157.114.151
172.16.239.0/24   172.16.239.228   10.157.114.157
172.16.239.0/24   172.16.239.250   10.157.114.131
172.16.3.0/24     172.16.3.117     10.11.54.97
172.16.3.0/24     172.16.3.55      10.157.114.158
172.16.38.0/24    172.16.38.110    10.157.87.67
172.16.38.0/24    172.16.38.125    10.157.21.34
172.16.53.0/24    172.16.53.31     10.157.114.134
172.16.53.0/24    172.16.53.40     10.157.115.141
```

There are two questions:
Why node's podcidr are conflict ? There are mutex to protect ipam allocator.
Why there are dirty data for old pod ips in ipcache map after I have try to delete ciliumnode and reboot cilium-agent
and reboot node ?

**Comment by aanm** [comment]
@lrouter where did you get the podCIDRs output from? From `CiliumNode` or `Kubernetes Nodes`? If you got them from both structures be aware that the IPAM is allocated from two independent allocators, the `CiliumNode` CIDRs are allocated from the Cilium Operator, the `Kubernetes` CIDRs are allocated from kube-controller-manager.

**Comment by lrouter** [comment]
It's the output from CiliumNode. As you see, it's a single list and there are conficts.

> @lrouter where did you get the podCIDRs output from? From `CiliumNode` or `Kubernetes Nodes`? If you got them from both structures be aware that the IPAM is allocated from two independent allocators, the `CiliumNode` CIDRs are allocated from the Cilium Operator, the `Kubernetes` CIDRs are allocated from kube-controller-manager.

**Comment by aanm** [comment]
@lrouter Can you provide a Cilium sysdump? Thank you!

**Comment by aanm** [comment]
I'll close the GH issue at the lack of activity. Feel free to re-open a new GH issue if you still face the issue again. Thank you
