### ISSUE TITLE
K8s Egress Gateway CiliumEgressNATPolicy not working after k8s cluster reboot

### ISSUE THREAD

**Issue by aigarm** [cilium/cilium#17291]
**General Information**

- Cilium version (run `cilium version`): 1.10.3
- Kernel version (run `uname -a`): 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...): Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6"
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```
I can't provide much information, but can share application behavior.

**How to reproduce the issue**

1. Using CiliumEgressNATPolicy with kind: Deployment (egress-ip-assign)
2. After k8s cluster reboot (both masters and workers) CiliumEgressNATPolicy is not forwarding traffic through egress-ip.
2.1 egress-ip deployemnt is deployed to separate namespace: cilium-egress.
2.2 application pods are deployed into application-namespace.

Seems that after cluster reboot application pod is starting quicker than egress-ip deployment pod and not creating "route rule". After killing application deployment pod, traffic is starting moving through egress-ip pod IP.

Cilium deployment:
helm install {{ helm_repo.cilium.name }} cilium/cilium --version {{ helm_repo.cilium.version }} \
   --namespace {{ helm_repo.cilium.namespace }} \
   --set nodeinit.enabled=true \
   --set hostServices.enabled=false \
   --set externalIPs.enabled=true \
   --set nodePort.enabled=true \
   --set hostPort.enabled=true \
   --set image.pullPolicy=IfNotPresent \
   --set ipam.mode=kubernetes \
   --set bgp.enabled=true \
   --set bgp.announce.lbIP=true \
   --set bgp.announce.loadbalancerIP=true \
   --set egressGateway.enabled=true \
   --set kubeProxyReplacement=strict \
   --set bpf.masquerade=true

Is there something that i do wrongly?

**Comment by aigarm** [comment]
# egress-ip-deployment:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "egress-ip"
  labels:
    name: "egress-ip"
  namespace: cilium-egress
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "egress-ip"
  template:
    metadata:
      labels:
        name: "egress-ip"
    spec:
      hostNetwork: true
      containers:
      - name: tvx-web-egress-ip
        image: docker.io/library/busybox:1.31.1
        command: ["/bin/sh","-c"]
        securityContext:
          privileged: true
        env:
        - name: EGRESS_IPS
          value: "10.1.106.105/24"
        args:
        - "for i in $EGRESS_IPS; do ip address add $i dev ens160 label ens160:1; done; sleep 10000000"
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "for i in $EGRESS_IPS; do ip address del $i dev ens160 label ens160:1; done"
              
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-nat
  namespace: cilium-egress
spec:
  egress:
    - namespaceSelector:
        matchLabels:
          "app.kubernetes.io/environment": "dev"
          "app.kubernetes.io/name": "stack"
  destinationCIDRs:
    - 10.1.113.50/32
  egressSourceIP: 10.1.106.105

**Comment by aigarm** [comment]
I tried option: kubeProxyReplacement=probe - same behavior

```
$ kubectl get configmap cilium-config -n cilium-system -o json
{
    "apiVersion": "v1",
    "data": {
        "auto-direct-node-routes": "false",
        "bgp-announce-lb-ip": "true",
        "bpf-lb-external-clusterip": "false",
        "bpf-lb-map-max": "65536",
        "bpf-map-dynamic-size-ratio": "0.0025",
        "bpf-policy-map-max": "16384",
        "cgroup-root": "/run/cilium/cgroupv2",
        "cilium-endpoint-gc-interval": "5m0s",
        "cluster-id": "",
        "cluster-name": "default",
        "custom-cni-conf": "false",
        "debug": "false",
        "disable-cnp-status-updates": "true",
        "enable-auto-protect-node-port-range": "true",
        "enable-bandwidth-manager": "false",
        "enable-bpf-clock-probe": "true",
        "enable-bpf-masquerade": "true",
        "enable-egress-gateway": "true",
        "enable-endpoint-health-checking": "true",
        "enable-health-check-nodeport": "true",
        "enable-health-checking": "true",
        "enable-hubble": "true",
        "enable-ipv4": "true",
        "enable-ipv4-masquerade": "true",
        "enable-ipv6": "false",
        "enable-ipv6-masquerade": "true",
        "enable-l7-proxy": "true",
        "enable-local-redirect-policy": "false",
        "enable-policy": "default",
        "enable-remote-node-identity": "true",
        "enable-session-affinity": "true",
        "enable-well-known-identities": "false",
        "enable-xt-socket-fallback": "true",
        "hubble-disable-tls": "false",
        "hubble-listen-address": ":4244",
        "hubble-socket-path": "/var/run/cilium/hubble.sock",
        "hubble-tls-cert-file": "/var/lib/cilium/tls/hubble/server.crt",
        "hubble-tls-client-ca-files": "/var/lib/cilium/tls/hubble/client-ca.crt",
        "hubble-tls-key-file": "/var/lib/cilium/tls/hubble/server.key",
        "identity-allocation-mode": "crd",
        "install-iptables-rules": "true",
        "install-no-conntrack-iptables-rules": "false",
        "ipam": "kubernetes",
        "kube-proxy-replacement": "probe",
        "kube-proxy-replacement-healthz-bind-address": "",
        "monitor-aggregation": "medium",
        "monitor-aggregation-flags": "all",
        "monitor-aggregation-interval": "5s",
        "node-port-bind-protection": "true",
        "operator-api-serve-addr": "127.0.0.1:9234",
        "preallocate-bpf-maps": "false",
        "sidecar-istio-proxy-image": "cilium/istio_proxy",
        "tunnel": "vxlan",
        "wait-bpf-mount": "false"
    },
```

**Comment by anfernee** [comment]
cc @MasterZ40

**Comment by brb** [comment]
> Seems that after cluster reboot application pod is starting quicker than egress-ip deployment pod and not creating "route rule". After killing application deployment pod, traffic is starting moving through egress-ip pod IP.

@aigarm The problem is that the example deployment which sets the egress static IP addr is started after the application pod has been started. So, until the deployment is ready, no traffic will flow through the egress GW node. Keep in mind, that the deployment is just an example how to set the egress IP addr and it should not be recommended for a production use. Alternatively, you could set the egress IP addr with node's network manager.
