### ISSUE TITLE
node-neigh: Arping previously stored nodes upon agent startup

### ISSUE THREAD

**Issue by brb** [cilium/cilium#17300]
@waynr reported in https://github.com/cilium/cilium/issues/14962

> We just identified a potential cause of ARP cache entries becoming stuck. It looks like when we recycle our master nodes specifically it is possible for cilium-agent to die unexpectedly then get stuck in a crashlooping state where it can't communicate with the master/etcd and reassert control over the ARP cache, which would be necessary for it to communicate with the master/etcd in the first place. Nodes where cilium-agent never crashes during a master node recycle are the ones that remain in their Ready state.

As we started to store the neigh discovery iface in the state file (see `NodeCleanNeighbors`), we could fix this by arpinging all PERMANENT entries IP addrs before even trying to connect to kube-apiserver.

**Comment by waynr** [comment]
Thanks for the hint! I've put together a patch that works on the version of Cilium I'm using. I need to put together a patched version of 1.10.1 for the product I work on since we're planning a release on Tuesday, but once that's done I'll submit a patch to master branch on this repo also.

**Comment by brb** [comment]
@waynr Thanks! Let me know if you need any help (I'm `martynas` on the Cilium slack).

**Comment by borkmann** [comment]
Fixed with managed neighbor rework where Cilium doesn't install PERM entries anymore. Closing.
