### ISSUE TITLE
investigate bugtool memory usage

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#17309]
several users have reported that cilium pods got OOM killed while running cilium-bugtool. let's investigate if there are any quick change we can make to reduce the memory consumption of the bugtool.

**Comment by tklauser** [comment]
It also looks like that in most cases, we don't even need to read in the command output as it is directly written out to a file again. For these cases instead of `execCommand`, we could use something like the following:

```go
cmd := exec.Command("bash", "-c", prompt)

f, err := os.Create(filepath.Join(cmdDir, name+".md"))
if err != nil {
    ...
}
defer f.Close()

cmd.Stdout = f
cmd.Stderr = f
err = cmd.Start()
if err != nil {
    ...
}
cmd.Wait()
```

This would avoid allocating memory for large strings altogether.
