### ISSUE TITLE
enabling hubble fails due to missing cert

### ISSUE THREAD

**Issue by ensonic** [cilium/cilium#17340]
## Bug report

**General Information**

- Cilium version:
  cilium-cli: v0.9.0 compiled with go1.17 on linux/amd64
  cilium image (default): v1.10.4
  cilium image (stable): v1.10.4
  cilium image (running): v1.10.4
- Kernel version:
   SMP Debian 5.10.40 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...)
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
  cilium is installed via helm on a single node minikube cluster with these settings:
  --namespace kube-system \
  --set encryption.enabled=true \
  --set encryption.nodeEncryption=false  \
  --set encryption.type=ipsec \
  --set kubeProxyReplacement=probe \
  --set operator.replicas=1
- Generate and upload a system zip:  
  [cilium-sysdump-20210908-133641.zip](https://github.com/cilium/cilium/files/7128547/cilium-sysdump-20210908-133641.zip)

**How to reproduce the issue**

```
$ cilium hubble enable
❌ Cilium CA not found: unable to get secret kube-system/cilium-ca: secrets "cilium-ca" not found

Error: Unable to enable Hubble:  unable to get secret kube-system/cilium-ca: secrets "cilium-ca" not found

$ kubectl -n kube-system logs cilium-t9k5v | grep Hubble
level=info msg="Configuring Hubble server" eventQueueSize=16384 maxFlows=4095 subsys=hubble
level=info msg="Starting local Hubble server" address="unix:///var/run/cilium/hubble.sock" subsys=hubble
level=info msg="Waiting for Hubble server TLS certificate and key files to be created" subsys=hubble
```

**Comment by pchaigno** [comment]
I think this is a duplicate of https://github.com/cilium/cilium-cli/issues/300#issuecomment-869042145.

**Comment by ensonic** [comment]
Thanks, that's right. I'll comment there.

**Comment by rolinh** [comment]
Mixing and matching Helm and the Cilium CLI is not supported. This issue is tracked [here on the Cilium CLI tracker](https://github.com/cilium/cilium-cli/issues/515).
