### ISSUE TITLE
Refactor service / LB code to package

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1734]
Currently all of the LB / service code is part of the daemon, which is undesirable as it is hard to unit test. This aligns with the goal to move as much code out of the daemon as possible. Move the service / LB code to a package.

**Comment by ianvernon** [comment]
One thought I have for doing this would be to have something similar to how the daemon manages endpoints with an endpoint manager package. We could have something similar to 'service' and 'service manager' package.

**Comment by tgraf** [comment]
The new kvstore layer will require this refactoring

**Comment by ianvernon** [comment]
This was completed a while back.
