### ISSUE TITLE
Poor udp throughput in cilium compared to weave-net

### ISSUE THREAD

**Issue by ensonic** [cilium/cilium#17342]
## Bug report

**General Information**

Cilium version:
cilium-cli: v0.9.0 compiled with go1.17 on linux/amd64
cilium image (default): v1.10.4
cilium image (stable): v1.10.4
cilium image (running): v1.10.4
Kernel version:
SMP Debian 5.10.40 x86_64 GNU/Linux
Orchestration system version in use (e.g. kubectl version, ...)
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Link to relevant artifacts (policies, deployments scripts, ...)
cilium is installed via helm on a single node minikube cluster with these settings:
--namespace kube-system
--set encryption.enabled=true
--set encryption.nodeEncryption=false
--set encryption.type=ipsec
--set kubeProxyReplacement=probe
--set operator.replicas=1
Generate and upload a system zip:
[cilium-sysdump-20210908-133641.zip](https://github.com/cilium/cilium/files/7128591/cilium-sysdump-20210908-133641.zip)

**How to reproduce the issue**

```
git clone https://github.com/InfraBuilder/k8s-bench-suite.git
cd k8s-bench-suite
nodename=$(kubectl get node -o name | cut -d'/' -f2)
./knb --verbose --client-node $nodename --server-node $nodename -o data -f ws-minikube-cilium-1.10.4.knbdata
./knb -fd ws-minikube-cilium-1.10.4.knbdata --plot --plot-args '--width 900 --height 600'
```

The script used iperf3, here is the command:
https://github.com/InfraBuilder/k8s-bench-suite/blob/master/knb#L273

bandwidth for cilium:
![cilium_bandwidth](https://user-images.githubusercontent.com/1279486/132504992-ba0803b8-f6b3-4d52-8b7c-7a1e4a306268.png)

bandwidth for weave:
![weave_bandwidth](https://user-images.githubusercontent.com/1279486/132505027-058fca81-4b63-43d0-b3d2-7d264c5fd5b5.png)

I ran the `cilium connectivity test` and it reported no issues.

**Comment by pchaigno** [comment]
What configuration are you using fro Weave Net? Did you check https://docs.cilium.io/en/latest/operations/performance/tuning/?

**Comment by ensonic** [comment]
Also on weave-net we had encryption enabled. I also disabled it for cilium, but get similar results. I am mostly concerned about the asymetry for udp (and that it is ~3 times less then for weave).
I am aware of https://docs.cilium.io/en/latest/operations/performance/tuning/ but I see no low hanging fruit. For the multicluster setups we'll try native routing (https://docs.cilium.io/en/v1.9/concepts/networking/routing/#native-routing), but for a single-node setup I am not sure what changes I should try first.

**Comment by brb** [comment]
Did I understand you correctly - you were running the benchmark on a single node? Meaning, that the client and the server both were on the same node?

**Comment by ensonic** [comment]
Yes

**Comment by borkmann** [comment]
What is your MTU for all the devices involved in the local node test for i) weave-net and ii) Cilium? Were both configured with the same MTU?

**Comment by ensonic** [comment]
Yes, all 1500
```
ifconfig | grep mtu
cilium_host: flags=4291<UP,BROADCAST,RUNNING,NOARP,MULTICAST>  mtu 1500
cilium_net: flags=4291<UP,BROADCAST,RUNNING,NOARP,MULTICAST>  mtu 1500
cilium_vxlan: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
eno1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
lxc1ec6393f4f6a: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
lxc763476b46b24: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
lxc7c04a1e7c685: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
lxc858b73a79010: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
lxc_health: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
lxca9b30debca98: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
lxce6db8158b224: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
lxcf2d1d78abefa: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
```

**Comment by borkmann** [comment]
> Yes, all 1500

And just to confirm, this is exactly the same in your weave-net test environment?

**Comment by pchaigno** [comment]
Pod-to-pod traffic on the same node will not be encrypted. When IPsec is enabled, only traffic across nodes is encrypted. (Not sure if Weave Net does the same, but I would expect so.) If you disable IPsec, KPR and BPF host routing should kick in and might give a performance boost.

**Comment by ensonic** [comment]
Yes, that was using the same MTU. Also weave was installed with default settings (disabled NPC due to bugs - that the major motivation for switching to cilium). We got the weave config from:
https://cloud.weave.works/k8s/net?password-secret=weave-passwd&disable-npc=true&k8s-version=1.20.0&env.IPALLOC_RANGE=192.168.9.0/24

**Comment by brb** [comment]
So in the case of Weave Net you are benchmarking Linux's L2 bridge. Have you tried disabling the encryption?

**Comment by ensonic** [comment]
I only disabled encryption on cilium side with only tiny differences (aka measurement error). I can measure anything on weave anymore, since I uninstalled it.

**Comment by pchaigno** [comment]
BPF host routing is explained in the tuning guide I linked to above: https://docs.cilium.io/en/latest/operations/performance/tuning/#ebpf-host-routing. It depends on KPR (kube-proxy replacement) being enabled.
