### ISSUE TITLE
pod network down

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#17358]
## Bug report

**General Information**

- Cilium version (run `cilium version`): 1.9.5
- Kernel version (run `uname -a`): 
```
Linux com3 4.19.113-300.el7.x86_64 #1 SMP Mon Mar 30 21:50:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

pod network is down

![image](https://user-images.githubusercontent.com/6076617/132785650-1342a5ae-bb01-4be7-a837-353d432a1595.png)

**Comment by pchaigno** [comment]
As per the issue template, could you: provide reproduction steps and upload a sysdump?

Also, what makes you think this is a Cilium issue? That interface is not installed or managed by Cilium as far as I know.
