### ISSUE TITLE
Cheatsheet for people getting started

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#1736]
Create a cheatsheet of common command line arguments.

**Comment by aalemayhu** [comment]
Have a draft but need more examples before opening up a pull request.

**Comment by jrfastab** [comment]
@scanf this is submitted now as PR https://github.com/cilium/cilium/pull/2164 correct?

**Comment by aalemayhu** [comment]
@jrfastab yes bundled it with some other things. HTML version here https://alemayhu.com/cilium-staging/cheatsheet.html
