### ISSUE TITLE
Egress gateway isn't used, and cilium bpf egress list returns no entries

### ISSUE THREAD

**Issue by Nigma1337** [cilium/cilium#17375]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
Client: 1.10.1 e6f34c3 2021-06-16T02:26:40+02:00 go version go1.16.5 linux/amd64

Daemon: 1.10.1 e6f34c3 2021-06-16T02:26:40+02:00 go version go1.16.5 linux/amd64

- Kernel version (run `uname -a`)

4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, ...)

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"archive", BuildDate:"2021-08-19T21:28:12Z", GoVersion:"go1.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
https://docs.cilium.io/en/stable/gettingstarted/egress-gateway/

- Generate and upload a system zip:
[cilium.zip](https://github.com/cilium/cilium/files/7153031/cilium.zip)
- Cloud provider (if any):
Digitalocean

**How to reproduce the issue**

1. Follow guide from https://docs.cilium.io/en/stable/gettingstarted/egress-gateway/, up until creation of Egress NAT Policy, replacing the different IPS with the ip of the node you're planning on using as egress gateway
2. Create egress NAT policy with destinationCIDRs set to 0.0.0.0/0
3. Attempt to check if it works as the client pod, realise the ip is still the one where the client pod is deployed, not the one with the egress gateway

**Comment by pchaigno** [comment]
I did see `enable-egress-gateway: "true"` in the Cilium configmap, but the equivalent macro in the datapath (`ENABLE_EGRESS_GATEWAY`) is absent. In the agent logs, there's also:
```
2021-07-06T13:04:18.373055434Z level=info msg="  --enable-egress-gateway='false'" subsys=daemon
```
My guess is you forgot to restart all Cilium agent pods after changing the egress gateway (?)

**Comment by brb** [comment]
@Nigma1337 Please reopen the issue if restarting Cilium agent pods don't help.
