### ISSUE TITLE
egress gw: Non-tunnel mode is broken

### ISSUE THREAD

**Issue by brb** [cilium/cilium#17386]
The egress GW datapath is broken when running in the direct routing mode.

To illustrate this, let's imagine a client pod sending a request to the internet via the egress GW:

```
client pod @ node A (runs cilium) -- vxlan tunnel --> egress GW @ node B (runs cilium) ----> the internet
```

The request gets SNAT-ed to the egress GW IP addr, and then sent to the internet. When the reply hits the egress GW node, it gets rev-SNAT-ed in bpf_host by:

```
"from-netdev" -> handle_netdev() -> do_netdev() -> .... handle_ipv4() -> nodeport_lb4() -> ... -> snat_v4_process()
```

And then is passed to the stack by `handle_ipv4()` which is called after the rev-SNAT-ed packet is recircled via tail calls.

In the upper-stack we have the iptables filter rules which default policy is DROP. As no Cilium's FORWARD rule matches the reply, the reply is DROP-ed by the default policy. In the case of tunneling, we have a rule (`cilium: any->cluster on cilium_host forward accept`) which matches the reply, and thus it is successfully sent to the client.

During [the initial testing of the feature](https://github.com/cilium/cilium/pull/14830#issuecomment-805745010) the direct routing mode was not broken, as all traffic was flowing through the tunnel (see https://github.com/cilium/cilium/pull/16328 for the context).

One way to fix the issue is to send the reply over the tunnel instead of passing to the stack (it also removes asymmetry of the return path). For this we would need to identify that a reply is part of the egress GW traffic. As @pchaigno suggested, this can be done by the following:

> if rev-SNATed IP ∈ native CIDR && rev-SNATed IP !∈ node pod CIDR => send to tunnel

Another alternative is to add a flag to the `struct nat_entry` denoting that the traffic belong to the egress GW. This would allow us to avoid the IPCache lookup (required by `rev-SNATed IP !∈ node pod CIDR`). However, not sure whether it's easy to propagate that flag after the rev-SNAT  to `handle_ipv4()`.

**Comment by brb** [comment]
The issue became obvious after running the CI tests in the PR: https://github.com/cilium/cilium/pull/16447#issuecomment-918332659

**Comment by anfernee** [comment]
Thanks @brb for the analysis. @MasterZ40 can you take a look at this? We manually verifying this in non-tunnel environment already, and it worked for us. The initial e2e test also works for some time until at some point I rebased on master. We need to figure out what changed and fix the issue.

**Comment by brb** [comment]
> The initial e2e test also works for some time until at some point I rebased on master

To our understanding, it was working before https://github.com/cilium/cilium/pull/16328 had been introduced.

> @MasterZ40 can you take a look at this? 

@kkourt is currently looking into the issue. Please sync with him if you are going to take a look.
