### ISSUE TITLE
Helm chart: AZURE_CLIENT_SECRET is not loaded from a secret

### ISSUE THREAD

**Issue by alkarp** [cilium/cilium#17393]
Cilium operator credentials for Azure are stored in a plain env variable and not loaded from a secret like it's done for AWS or Alibaba: https://github.com/cilium/cilium/blob/v1.10.4/install/kubernetes/cilium/templates/cilium-operator-deployment.yaml#:~:text=%7B%7B-%20if%20.Values.azure.clientSecret,%7B%7B-%20end%20%7D%7D

Can this be replaced with something like:

{{- if .Values.alibabacloud.enabled }}
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: AZURE_CLIENT_ID
              name: cilium-azure
              optional: true
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: AZURE_CLIENT_SECRET
              name: cilium-azure
              optional: true
{{- end }}

**Comment by aanm** [comment]
@alkarp Would you like to submit a PR with those changes?
