### ISSUE TITLE
CI: K8sPolicyTest Basic Test Traffic redirections to proxy Tests

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#17404]
## CI failure

Observed in https://github.com/cilium/cilium/pull/16635

```
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
traffic was not redirected to the proxy when it should have been
Expected
    <*errors.errorString | 0xc001545320>: {
        s: "Expected string \"202109141225k8spolicytestbasictestchecksallkindofkubernetespoli RESPONSE http://10.0.1.42/public 200 GET\" is not in the filter output of \"{.destination.namespace} {.l7.type} {.l7.http.url} {.l7.http.code} {.l7.http.method}\": 10s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/k8sT/Policies.go:1276
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1429/testReport/junit/Suite-k8s-1/16/K8sPolicyTest_Basic_Test_Traffic_redirections_to_proxy_Tests_proxy_visibility_interactions_with_policy_lifecycle_operations/

The same test run also contained a few `Connectivity was expected to be allowed consistently` errors in subsequent K8sPolicyTest tests. Not sure if related, I assume they are.

**Comment by Weil0ng** [comment]
Saw same failure in https://github.com/cilium/cilium/pull/17235, job: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/1416/
