### ISSUE TITLE
Host Endpoints not detected correctly

### ISSUE THREAD

**Issue by Jakob3xD** [cilium/cilium#17415]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
`Daemon: 1.10.4 2a46fd6 2021-09-01T12:58:41-07:00 go version go1.16.7 linux/amd64`
- Kernel version (run `uname -a`)
`5.4.0-72-generic`
- Orchestration system version in use (e.g. `kubectl version`, ...)
`GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GoVersion:"go1.16.1"
`

**How to reproduce the issue**
#### Servers
3 Masters and 3 Worker Nodes running in the Hetzner Cloud connected via a [Cloud Network](https://docs.hetzner.com/cloud/networks/faq#what-are-hetzner-cloud-networks) and running the [hcloud CCM](https://github.com/hetznercloud/hcloud-cloud-controller-manager). The Cloud Network was crated as 10.0.0.0/8 only using the subnet 10.10.10.0/24 which contains all nodes.
The external Interface has the name `eth0` and the internal one `ens10`.
#### Cilium
Cilium deployment was generated by Helm using the following settings:
```
  --version 1.10.4
  --namespace kube-system
  --set ipam.mode=kubernetes
  --set hubble.relay.enabled=true
  --set hubble.ui.enabled=true
  --set l7Proxy=false
  --set encryption.enabled=true
  --set encryption.type=wireguard
  --set prometheus.enabled=true
  --set operator.prometheus.enabled=true
  --set hubble.metrics.enabled='{dns,drop,tcp,flow,icmp,http}'
  --set hostFirewall=true
  --set tunnel=disabled
  --set nativeRoutingCIDR=10.244.0.0/16
  --set devices='{ens+,eth+}'
```
### Cilium Endpoints
Cilium does not detect the ens10 and eth0 correctly. Therefor it is not possible to apply firewall rules.
```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                         
3911       Disabled           Disabled          1          k8s:node-role.kubernetes.io/worker                                     ready   
                                                           k8s:node.kubernetes.io/instance-type=cx41-sandy                                
                                                           k8s:topology.kubernetes.io/region=nbg1                                         
                                                           k8s:topology.kubernetes.io/zone=nbg1-dc3                                       
                                                           reserved:host                                                                  
3951       Disabled           Disabled          4          reserved:health                                          10.244.4.18   ready
```
I would expect to see two endpoints labeled with `reserved:host`. One containing the IP of the internal interface and the other one with the external IP.

**Comment by pchaigno** [comment]
> I would expect to see two endpoints labeled with `reserved:host`. One containing the IP of the internal interface and the other one with the external IP.

That's not how it works. There is a single host endpoint identified by label `reserved:host` and it represents the entire host network namespace. All host IPs of detected devices should be assigned to that endpoint.

Did you check in the logs that `devices='{ens+,eth+}'` had the intended behavior?

> Therefor it is not possible to apply firewall rules.

Could you clarify what you mean by this?

**Comment by Jakob3xD** [comment]
Thanks for the fast response.
> That's not how it works.

Okay, than I had a wrong memory about that. I thought it was possible to firewall specific interfaces but if they are all bound to a single endpoint, it makes it difficulty.
I also further debugged my issue and fount out it is not a bug. I am sorry for opening the Issue.
Have a nice rest of the day.
