### ISSUE TITLE
Diagrams documentation

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#1741]
- Examples for Policy, provide a diagram
- Network traffic as per Policy Rules
- How cilium fits into the K8s setup/world
            dataflow(?)
- Cilium observability tool - Matrix that maps a tool/CLI/API to a specific problem they find.
- Difference between K8s policy support & cilium network policy support (#1740)
- K8s support versus cilium L7 support (Different)
- Service/proxy/load balancing integration
- Start of BPF/XDP -> More diagramatic representation of BPF

**Comment by ianvernon** [comment]
Would be cool to have a diagram of the endpoint state machine as well which shows the lifecycle of an endpoint. For instance, what causes a change of an endpoint into the following states (from `endpoint/endpoint.go`):
```
	// StateCreating is used to set the endpoint is being created.
	StateCreating = string(models.EndpointStateCreating)

	// StateDisconnecting indicates that the endpoint is being disconnected
	StateDisconnecting = string(models.EndpointStateDisconnecting)

	// StateDisconnected is used to set the endpoint is disconnected.
	StateDisconnected = string(models.EndpointStateDisconnected)

	// StateWaitingForIdentity is used to set if the endpoint is waiting
	// for an identity from the KVStore.
	StateWaitingForIdentity = string(models.EndpointStateWaitingForIdentity)

	// StateReady specifies if the endpoint is read to be used.
	StateReady = string(models.EndpointStateReady)

	// StateRegenerating specifies when the endpoint is being regenerated.
	StateRegenerating = string(models.EndpointStateRegenerating)
```

**Comment by jrfastab** [comment]
closing someone can open specific issues as needed, clearly I'm not doing these seeing its 2022.
