### ISSUE TITLE
Hide clean-cilium-state options from default configmap

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#17412]
The options `clean-cilium-bpf-state` / `clean-cilium-state` were introduced very early on as a last resort option to clear out bad state on nodes. These days it is rare that any user legitimately needs this functionality and uses it properly. It is now more likely that users will see the options and think they will help solve their problem when it really only digs them deeper into a hole.

I propose that we do a pass through the git repository to hide or remove references to these options, or if we leave them anywhere in place then ensure there is a strong warning to avoid using it unless you know exactly what you are doing.

At a glance, the documentation under `Documentation/concepts/kubernetes/configuration.rst` is quite clear. To solve this issue, we most likely just need to update the helm charts to avoid adding these options into the configmap by default.

**Comment by chowmean** [comment]
Hi as per the charts these options will not be set by defaults. They will be set only if the values file have these are true. https://github.com/cilium/cilium/blob/0a4d381ad988a591c451e0034efe63031ec06867/install/kubernetes/cilium/templates/cilium-configmap.yaml#L200
In the values files also these are false by default. 
Please correct me If I am wrong here. Thanks
https://github.com/cilium/cilium/blob/0a4d381ad988a591c451e0034efe63031ec06867/install/kubernetes/cilium/values.yaml#L304

**Comment by joestringer** [comment]
Thanks for digging into this @chowmean , I agree that seems pretty clear and I see no other remaining references. This looks good to close out.
