### ISSUE TITLE
doc: create diagrams for services / load balancing 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1742]

**Comment by ianvernon** [comment]
@brb this might be useful for LB v2 - what do you think? We can also close if you think it is unrelated.

**Comment by brb** [comment]
@ianvernon Oops, totally missed your comment. I think it's good to have at least some architecture diagrams for svc load-balancing.

Also, I have some design doc for LB2 https://docs.google.com/document/d/1zAqme6Blk-brIG6K-Y_1k3lpUB2Ql0xXwpvR0YpCLNs/edit which parts I could try to convert to documentation as well.

**Comment by brb** [comment]
This is going to be addressed when we update the KPR/LB docs.
