### ISSUE TITLE
kernel 4.9 error="unable to read BPF endpoint list: Unable to get next key from map with file descriptor 10: bad address"

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#17431]
## Bug report
upstream master image build, cilium agent on kernel 4.9 complains error below and fail to start
```
# kubectl  logs  cilium-q6dfb   -n kube-system | grep 'fatal'
level=fatal msg="Error while creating daemon" error="unable to read BPF endpoint list: Unable to get next key from map with file descriptor 10: bad address" subsys=daemon
```
not sure if this is bug or configuration issue, the upstream image build runs fine on another two node with kernel 5.14, 5.12

**General Information**

- Cilium version (run `cilium version`)

Client: 1.10.90 c40ed7911 2021-09-15T21:12:15+02:00 go version go1.17.1 linux/amd64
Daemon: 1.10.90 c40ed7911 2021-09-15T21:12:15+02:00 go version go1.17.1 linux/amd64

- Kernel version (run `uname -a`)

 4.9.0

- Orchestration system version in use (e.g. `kubectl version`, ...)
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```
[cilium-sysdump-20210917-180502.zip](https://github.com/cilium/cilium/files/7188635/cilium-sysdump-20210917-180502.zip)

**How to reproduce the issue**
[cilium-upstream.yaml.txt](https://github.com/cilium/cilium/files/7188640/cilium-upstream.yaml.txt)

kubectl apply -f attached cilium-upstream.yaml.txt

**Comment by pchaigno** [comment]
As per [the documentation](https://docs.cilium.io/en/stable/operations/system_requirements/#summary), Cilium requires Linux 4.9.17 minimum. If you try with the latest 4.9.x, do you still have this error?

**Comment by vincentmli** [comment]
@pchaigno the reason I run 4.9 is because my PR has error https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/1422/, I assumed Cilium-PR-K8s-1.21-kernel-4.9 uses kernel 4.9, no? that test is using 4.9.17 ?

**Comment by vincentmli** [comment]
I will try 4.9.282 that seems to be the most recent 4.9 release

**Comment by vincentmli** [comment]
4.9.282 solved the problem, thanks @pchaigno close the issue

**Comment by pchaigno** [comment]
Cilium-PR-K8s-1.21-kernel-4.9 runs Linux 4.9.270.
