### ISSUE TITLE
Connectivity issues when using vlan_filtering bridges

### ISSUE THREAD

**Issue by Jean-Daniel** [cilium/cilium#17435]
## Bug report

I have a network configuration based on `vlan_filtering` bridge. And I have trouble at least with ICMP requests to other hosts.

I have a bridge netdev with 2 `slave ports`: 
- one ethernet device configured as a `trunk` with a single VLAN (21) allowed.
- one veth device configured in  `access mode` (`PVID 21, Egress Untagged`)

The other side of the veth device is the main server interface with the node IP.

cilium is configured in direct routing mode with masquerading enabled using iptables and strict kube-proxy replacement.

When I try to ping an external address from a pod, I see this behaviour (note the echo reply id) :

172.22.0.20 is the node IP.
178.32.222.11 is the remote host IP.

- On the ethernet device (everything looks fine):
```
09:15:12.956876 ethertype 802.1Q (0x8100), length 102: vlan 21, p 0, ethertype IPv4 172.22.0.20 > 178.32.222.11: ICMP echo request, id 39153, seq 29, length 64
09:15:12.961917 ethertype 802.1Q (0x8100), length 102: vlan 21, p 0, ethertype IPv4 178.32.222.11 > 172.22.0.20: ICMP echo reply, id 39153, seq 29, length 64
09:15:13.957058 ethertype 802.1Q (0x8100), length 102: vlan 21, p 0, ethertype IPv4 172.22.0.20 > 178.32.222.11: ICMP echo request, id 39456, seq 30, length 64
09:15:13.962103 ethertype 802.1Q (0x8100), length 102: vlan 21, p 0, ethertype IPv4 178.32.222.11 > 172.22.0.20: ICMP echo reply, id 39456, seq 30, length 64
```

- On the Bridge device  (everything looks fine):
```
09:17:32.981593 ethertype 802.1Q (0x8100), length 102: vlan 21, p 0, ethertype IPv4 172.22.0.20 > 178.32.222.11: ICMP echo request, id 35476, seq 169, length 64
09:17:32.986586 ethertype 802.1Q (0x8100), length 102: vlan 21, p 0, ethertype IPv4 178.32.222.11 > 172.22.0.20: ICMP echo reply, id 35476, seq 169, length 64
09:17:33.981786 ethertype 802.1Q (0x8100), length 102: vlan 21, p 0, ethertype IPv4 172.22.0.20 > 178.32.222.11: ICMP echo request, id 48506, seq 170, length 64
09:17:33.986827 ethertype 802.1Q (0x8100), length 102: vlan 21, p 0, ethertype IPv4 178.32.222.11 > 172.22.0.20: ICMP echo reply, id 48506, seq 170, length 64
```

- On the veth port bound to the bridge (echo reply id changed):
```
09:18:54.996070 ethertype IPv4 (0x0800), length 98: 172.22.0.20 > 178.32.222.11: ICMP echo request, id 768, seq 251, length 64
09:18:55.001171 ethertype IPv4 (0x0800), length 98: 178.32.222.11 > 172.22.0.20: ICMP echo reply, id 29222, seq 251, length 64
09:18:55.996255 ethertype IPv4 (0x0800), length 98: 172.22.0.20 > 178.32.222.11: ICMP echo request, id 768, seq 252, length 64
09:18:56.001286 ethertype IPv4 (0x0800), length 98: 178.32.222.11 > 172.22.0.20: ICMP echo reply, id 54564, seq 252, length 64
```

The same configuration without native VLAN tagging (ethernet port in access mode) works fine.

I tried with a nightly cilium build and using `--vlan-bpf-bypass 0` but the result is the same.

Tell me if you need more information.

**General Information**

- Cilium version (run `cilium version`): v1.10.4 and also master.
- Kernel version (run `uname -a`): 5.11.0-34-generic # 36~20.04.1-Ubuntu SMP 
- Orchestration system version in use (e.g. `kubectl version`, ...): k8s 1.22.2

**Comment by pchaigno** [comment]
Any chance you could upload a sysdump?

**Comment by Jean-Daniel** [comment]
Yes, you can find one [here](https://xenonium.com/files/cilium-sysdump-20210918-151124.zip).
