### ISSUE TITLE
doc: release notes / roadmap section

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#1744]
Add a section for releases to the doc. It should be on top level, so it can be found easily, should contain link to GH for the release docs of the different releases we have, perhaps roadmap. Description of stable releases, their EOL wrt backports, etc.

- [ ] Thomas will setup quick meeting to write down infos and identify gaps

**Comment by aalemayhu** [comment]
Will get to this next week, a scheduled session with Thomas.
