### ISSUE TITLE
loadBalancerSourceRanges allow access to services through nodeports

### ISSUE THREAD

**Issue by JrCs** [cilium/cilium#17440]
## Bug report

**General Information**

- Cilium version 1.10.4
- Kernel version 5.10.61
- Orchestration system version in use k8s 1.20.8

**How to reproduce the issue**

1. Cilium was deployed in kube-proxy free mode (strict)
2. Cilium was deployed with option **svcSourceRangeCheck** set  to **true**
3. Create a service of type LoadBalancer with a CIDR value for spec.**loadBalancerSourceRanges**

The LoadBalancer was created by the k8s cloud-provider (openstack in our case) and the source IPs were correctly filtered by the loadbalancer (using the CIDRs set in the services)  
In the cilium documentation, they said:

> When a LoadBalancer service is configured with spec.loadBalancerSourceRanges, Cilium’s eBPF kube-proxy replacement restricts access from outside (e.g. external world traffic) to the service to the white-listed CIDRs specified in the field

But we can access the service using the nodeports (bypassing the LoadBalancer) from the outside, so the access from external world is not filtered.  

Can the source IPs to the nodeports can be filter to allow only an access from the LoadBalancer ?

**Comment by brb** [comment]
@JrCs I think https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation should address your use case.
