### ISSUE TITLE
cilium status showing "direct routing" when configured with tunnel

### ISSUE THREAD

**Issue by kailunshi** [cilium/cilium#17461]
## Bug report
**General Information**

- Cilium version: [1.10.4]
- Kernel version: 5.10.35
- Orchestration system version in use: kubernetes v1.21.3

**How to reproduce the issue**

1. in cilium-config configmap, set tunnel: vxlan
2. cilium status --verbos
[cilium-sysdump-20210923-101654.zip](https://github.com/cilium/cilium/files/7219606/cilium-sysdump-20210923-101654.zip)

**Comment by pchaigno** [comment]
Kailun is referring to this example output:
```
kubectl exec -it -n kube-system cilium-fmh8d -- cilium status | grep KubeProxyReplacement
KubeProxyReplacement:   Strict      [eth0 (Direct Routing), eth1]
```
@brb I'm not sure how to best explain why it says `Direct Routing` here even though tunneling is used.

Also, is there a way we could make this less confusing? Maybe by renaming?

**Comment by brb** [comment]
> @brb I'm not sure how to best explain why it says Direct Routing here even though tunneling is used.

@pchaigno From a quick grepping it seems that the `Direct Routing` iface (`DIRECT_ROUTING_DEV_IFINDEX`) is no longer used for KPR only. The other user is the fast redirect. Another thing, is that the DR iface should not be used in the tunneling mode. Considering both, it makes sense to move the DR field from the KPR to a dedicated field which would be used to show the datapath mode (tunnel; what kind of tunnel; DR iface).

**Comment by brb** [comment]
Created https://github.com/cilium/cilium/issues/17480 to properly fix it.

**Comment by pchaigno** [comment]
@kailunshi Does this answer your question? Should we close this issue now?

**Comment by borkmann** [comment]
(Closing given question.)
