### ISSUE TITLE
Include `tc filter ...` output in bugtool

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#17468]
We currently don't show any `tc filter ...` output which could be useful.

cc @joestringer to add additional context when we were digging into a sysdump where this information would have been useful.

**Comment by joestringer** [comment]
FWIW I think that technically `bpftool net show` provides the same information from a pure BPF perspective, and is a bit more human-readable.

`tc filter show ...` is more specific to tc though and could possibly provide details that `bpftool net show` doesn't.

**Comment by pchaigno** [comment]
Agree with Joe here. Is there any specific information we are missing today?

**Comment by joestringer** [comment]
Looks like there's some tags, filter preference/chain values, plausibly any non-bpf filters (though these are highly unlikely in any default Cilium install).

```
root@kind-control-plane:/home/cilium# tc filter show dev lxc5869b5857a3d ingress
filter protocol all pref 1 bpf chain 0 
filter protocol all pref 1 bpf chain 0 handle 0x1 bpf_lxc.o:[from-container] direct-action not_in_hw id 15843 tag a7a920f725fab0ef jited 
root@kind-control-plane:/home/cilium# tc filter show dev lxc5869b5857a3d egress
root@kind-control-plane:/home/cilium# bpftool net show
xdp:

tc:
cilium_net(2) clsact/ingress bpf_host_cilium_net.o:[to-host] id 15871
cilium_host(3) clsact/ingress bpf_host.o:[to-host] id 15859
cilium_host(3) clsact/egress bpf_host.o:[from-host] id 15865
lxc5869b5857a3d(18) clsact/ingress bpf_lxc.o:[from-container] id 15843
eth0(21) clsact/ingress bpf_netdev_eth0.o:[from-netdev] id 15877
eth0(21) clsact/egress bpf_netdev_eth0.o:[to-netdev] id 15883
lxc_health(23) clsact/ingress bpf_lxc.o:[from-container] id 15853

flow_dissector:

```

**Comment by pchaigno** [comment]
Hm, it may actually make sense if we ever run into a conflict in the tc configuration with some other software.

**Comment by tommyp1ckles** [comment]
@joestringer @pchaigno Taking a look at this for my first issue.

Lacking the full context on this so gonna take my best guess at it.

In my draft PR added commands for:
```
tc -s qdisc
tc qdisc show
```

As well, for the filter/class/chain info, these need to be done per interface, so doing something like:

```
tc filter show dev ifacexxx0
tc chain show dev ifacexxx0
tc class show dev ifacexxx0
...
```
for every interface.

**Comment by tommyp1ckles** [comment]
@christarazi as well.
