### ISSUE TITLE
Add global scope ip addresses attached to dummy or lo interface to local host entries

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#17475]
## Proposal

**Is your feature request related to a problem?**

In our environment, nodes have two interfaces(eth0, eth1) that connect to ToR switches and we attach a global scope address to a dummy interface(node0). Bird running on each node advertises the global scope address to ToRs.
Cilium excludes IP addresses attached to dummy or lo interfaces because those statuses are not UP.  So Cilium network policy enforcement doesn't work because a localhost address is not recognized as the host identity.

https://github.com/cilium/cilium/blob/f3887bd83f6f7495f5d487fe1002896488b9495f/pkg/node/ip_linux.go#L27

Attaching a global scope address to a dummy or lo interface is a common use case. For example, it is a good practice to configure an IP address to the never failing and always present lo interface in a case using BGP-unnumbered. I think it's worse to supporting it.
https://docs.metal-stack.io/stable/overview/networking/#BGP-Unnumbered

```
# Our node interface setting
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:2e:aa:6c brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 10.69.1.197/26 brd 10.69.1.255 scope link eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe2e:aa6c/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:46:aa:eb brd ff:ff:ff:ff:ff:ff
    altname enp0s4
    altname ens4
    inet 10.69.2.5/26 brd 10.69.2.63 scope link eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe46:aaeb/64 scope link
       valid_lft forever preferred_lft forever
4: node0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 4a:16:b9:4a:58:89 brd ff:ff:ff:ff:ff:ff
    inet 10.69.1.133/32 scope global node0
       valid_lft forever preferred_lft forever
    inet6 fe80::4816:b9ff:fe4a:5889/64 scope link
       valid_lft forever preferred_lft forever
```

**Describe the solution you'd like**

Add `IncludeLocalInterface` option and user can speficy local interface names that have global scope addresses.

**Comment by brb** [comment]
@ysksuzuki Thanks for the issue. This should resolve it: https://github.com/cilium/cilium/pull/17418 (/cc @jibi).

**Comment by ysksuzuki** [comment]
@brb Right, #17418 should fix this. I will close this issue. Thank you for your reply.
