### ISSUE TITLE
Failed to replace Qdisc for XXXXXXX

### ISSUE THREAD

**Issue by chenmj11** [cilium/cilium#17472]
## Bug report

hi,I am chaining cilium with kube-ovn cni，whose interface is veth-pair . Don't know why can't regenerate endpoint,

```
level=debug msg="Error regenerating endpoint: Failed to replace Qdisc for 7d1a79bc83b2_h: netlink: Replacing qdisc for 7d1a79bc83b2_h failed: invalid argument" code=Failure containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=1283 endpointState=ready identity=63191 ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=200
```

**General Information**
```
uname -a
Linux node1 5.4.129-1.el7.elrepo.x86_64 #1 SMP Tue Jun 29 10:28:41 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

cilium version
Client: 1.10.1 e6f34c3 2021-06-16T02:26:40+02:00 go version go1.16.5 linux/amd64
Daemon: 1.10.1 e6f34c3 2021-06-16T02:26:40+02:00 go version go1.16.5 linux/amd64

```
Generate and upload a system zip
```
    curl -sLO https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip
    python cilium-sysdump.zip --output /tmp/cilium-sysdump-out
```
[cilium-sysdump-out.zip](https://github.com/cilium/cilium/files/7231090/cilium-sysdump-out.zip)

**Comment by pchaigno** [comment]
Does your kernel have all [the required configs](https://docs.cilium.io/en/stable/operations/system_requirements/#linux-kernel)?

**Comment by kylin-D-ZZ** [comment]
> Does your kernel have all [the required configs](https://docs.cilium.io/en/stable/operations/system_requirements/#linux-kernel)?

yes，there has been no problem before,but after the upgrade kube-ovn cni ,this error occurred.
And kube-ovn cni  no setting Qdisc.

**Comment by pchaigno** [comment]
> but after the upgrade kube-ovn cni ,this error occurred.

Could you share which version of kube-ovn worked and which doesn't?

**Comment by kylin-D-ZZ** [comment]
> > but after the upgrade kube-ovn cni ,this error occurred.
> 
> Could you share which version of kube-ovn worked and which doesn't?
kube-ovn v1.7.2 is no  problem，since v1.8.0.

**Comment by ftiannew** [comment]
@pchaigno ，please hold it for the moment，we will check it ourself ，in case that waste your time,thanks.

**Comment by kylin-D-ZZ** [comment]
@pchaigno  thanks，this is ours problem ,because ovs set a rule`qdisc ingress ffff: dev b16cb8d4de39_h parent ffff:fff1 ----------------`，make cilium not execute ` tc qdisc replace dev b16cb8d4de39_hclsact `

**Comment by pchaigno** [comment]
Ah, good to know. Does that mean this issue can be closed?

**Comment by kylin-D-ZZ** [comment]
> 啊，很高兴知道。这是否意味着可以关闭此问题？
