### ISSUE TITLE
Cilium preflight validation is misleading

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#17471]
This line suggests that everything is OK and no user action is required:
https://github.com/cilium/cilium/blob/f3887bd83f6f7495f5d487fe1002896488b9495f/cilium/cmd/preflight_k8s_valid_cnp.go#L93

However, if for instance you reference one of the checks that we have in this preflight check:

https://github.com/cilium/cilium/pull/12890

![image](https://user-images.githubusercontent.com/21292343/90757664-87b9f080-e2fb-11ea-959e-42476e024357.png)

On the first line, there is a warning, which is trying to communicate to the user that if they do not change their policy, cilium could drop traffic for apps in their cluster.

But then the preflight check continues and states `All CCNPs and CNPs valid!`, which implies that the warning is nothing to worry about and everything is 100% OK.

Possible steps to resolve:
* If there are any checks that fail in preflight checks, even as warnings, fail the entire check.
* Change the wording `All CCNPs and CNPs valid!` to more clearly communicate that the format of the policies was checked and is correct YAML, and avoid the implication to users that this means they don't need to take any action.

**Comment by doniacld** [comment]
Hi @joestringer & @christarazi !
I would be happy to solve my first issue in cilium and it seems to be a good candidate! :)

Concerning the first step, I will assume as a user if there is a warning I have no action to take and I can continue without any trouble! 
We might want to change the warnings for real errors ? And of course still inform the user that the policies syntax is correct. 

What do you think ?

**Comment by joestringer** [comment]
Hi @doniacld, awesome, you're welcome to pick this up :) 

I think that your proposal to change the warnings to errors sounds good. After that it would be good to check to make sure that  if such errors or warnings occur, the preflight check doesn't print that "`All CCNPs and CNPs are valid!`".

**Comment by doniacld** [comment]
Thanks @joestringer, will work on it! :)

**Comment by doniacld** [comment]
Hey @joestringer 
I have been struggling to test what I have implemented.
I followed the [getting started using kind](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/).
But I have the following errors and I am wondering if I am on the right path to test.
```
[donia@localhost cilium]$ ./cilium preflight validate-cnp
Using config file: /home/donia/.cilium.yaml
INFO[0002] Setting up Kubernetes client                 
FATA[0002] unable to connect to Kubernetes apiserver     error="unable to create k8s client: unable to create k8s client rest configuration: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory"
```

If you have any hints, thanks ? :)

**Comment by joestringer** [comment]
Hi @doniacld , usually we will run the preflight from the preflight `DaemonSet` rather than directly: https://docs.cilium.io/en/stable/operations/upgrade/#running-pre-flight-check-required

For development, if you have changed some things, then you would need to build & push the image somewhere, then use helm to generate the templates for the preflight DS, pointing to your custom image. If you search [this page](https://github.com/cilium/cilium/tree/master/install/kubernetes/cilium) for "preflight", you will find the various Helm options available for the preflight DS.
