### ISSUE TITLE
datapath: Do not require direct routing device in tunneling mode

### ISSUE THREAD

**Issue by brb** [cilium/cilium#17480]
Currently, we require the direct routing device (KPR) regardless of in tunneling mode. The device is used to forward some traffic (e.g., NodePort BPF request from intermediate node to a node which runs a selected service endpoint) among k8s nodes. The current users of it - KPR and the fast redirect.

From the quick code inspection it seems that the device is needed only when tunneling mode is disabled  Therefore, do not require it when running in the tunneling mode.

Just to note, #17441 will be feasible only for new kernels.

**Comment by AnishShah** [comment]
Sorry. I made some changes but I haven't got time to test it yet. I will likely won't get time until next year due to holiday. Please feel free to unassign me.
