### ISSUE TITLE
[Minor] datapath log format improvement

### ISSUE THREAD

**Issue by leonliao** [cilium/cilium#17506]
## Bug report

**General Information**

- Cilium version: v1.10.4
- Kernel version: Linux k8s002 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Wed Aug 11 01:59:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use: Kubernetes v1.22.2

**How to reproduce the issue**

1. cilium monitor -vv with settings of cilium agent:
 ```  
debug: "true"
 debug-verbose: "datapath"
```
2. The traffic log shows 
`CPU 01: MARK 0x0 FROM 3103 to-proxy: 66 bytes (66 captured), state established, interface lxcb40932b0a2c5identity 30168->30747, orig-ip 10.0.1.169`. 
There should be a comma and space before identity, making the log to be
`CPU 01: MARK 0x0 FROM 3103 to-proxy: 66 bytes (66 captured), state established, interface lxcb40932b0a2c5, identity 30168->30747, orig-ip 10.0.1.169`.

**Comment by pchaigno** [comment]
The problematic code is located here: https://github.com/cilium/cilium/blob/a8e3fa283cf40b330035265bf83d63800b296bcf/pkg/monitor/datapath_drop.go#L63 and here: https://github.com/cilium/cilium/blob/cebd290c39dbb2f3214ac670a3b40ed77b79024f/pkg/monitor/datapath_trace.go#L219

Could you send a fix?
