### ISSUE TITLE
install cilium error

### ISSUE THREAD

**Issue by mxdblcf** [cilium/cilium#17503]
My machine only support Generic XDP,

Can I install cilium for study ？

**Comment by pchaigno** [comment]
Depends what you want to study. If you plan to run any performance benchmark, then no, Generic XDP is really not the same as Native XDP.

**Comment by mxdblcf** [comment]
> 看你想学什么。 如果您计划运行任何性能基准测试，那么不，Generic XDP 与 Native XDP 确实不同。
