### ISSUE TITLE
Explore if there is a way to get coverage for runtime tests

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1750]
While go offers coverage reports for unit tests out of the box, it does not have such a way of generating coverage reports for binaries that are running in our VMs. See if there is a way to instrument the Cilium binary to make sure we have adequate coverage during our runtime tests.

**Comment by nebril** [comment]
Two potentially helpful links (easiest for CLI, but also possible for agent with some work):
https://stackoverflow.com/questions/43381335/how-to-capture-code-coverage-from-a-go-binary
https://blog.cloudflare.com/go-coverage-with-external-tests/

**Comment by pchaigno** [comment]
We are slowly deprecating the Runtime tests.
