### ISSUE TITLE
Fix CoreOS getting started guide with instructions for how to setup K8s cluster

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1752]
The CoreOS guide links to instructions that no longer correspond to the guide. Remove these links and update the instructions for CoreOS.

**Comment by tgraf** [comment]
Done

**Comment by ianvernon** [comment]
This is not done, the CoreOS instructions now direct to use Tectonic. We need to include the instructions for setting up K8s in the actual docs now instead of linking them.

**Comment by tgraf** [comment]
> This is not done, the CoreOS instructions now direct to use Tectonic. We need to include the instructions for setting up K8s in the actual docs now instead of linking them.

Something similar to what #1724 is providing?

**Comment by tgraf** [comment]
Guide was removed
