### ISSUE TITLE
pkg/elf: BenchmarkWriteELF fails with "failed to open ELF file ../../test/bpf/elf-demo.o: open ../../test/bpf/elf-demo.o: no such file or directory"

### ISSUE THREAD

**Issue by odeke-em** [cilium/cilium#17535]
## Bug report

**General Information**

- Cilium version (run `cilium version`) N/A
- Kernel version (run `uname -a`) N/A
- Orchestration system version in use (e.g. `kubectl version`, ...) N/A
- Link to relevant artifacts (policies, deployments scripts, ...) N/A
- Generate and upload a system zip: N/A
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

Run `go test -run=^$ -bench=. ./...`
We've seen failures on every single attempted Cilium benchmark run on our continuous benchmarking product ["Bencher"](https://bencher.orijtech.com/) for example https://dashboard.github.orijtech.com/benchmark/73634fe4ebc44e9ebd1da7b9ccc65815
<img width="1267" alt="Screen Shot 2021-10-04 at 11 28 26 PM" src="https://user-images.githubusercontent.com/4898263/135971625-2d346845-5cf9-40d0-9460-ffa2203a8c1d.png">

or inlined below
```shell
--- FAIL: BenchmarkWriteELF
    elf_test.go:201: failed to open ELF file ../../test/bpf/elf-demo.o: open ../../test/bpf/elf-demo.o: no such file or directory
```

Our product is available for FREE on the Github marketplace at https://github.com/marketplace/gobencher, and it'll be able to help y'all continuously benchmark the very critical infrastructure and highly performant Cilium so that you don't regress, yet don't have to sweat with the cumbersome ergonomics of trying to benchmark before and after.

Kindly cc-ing my colleagues @cuonglm @kirbyquerby and a Go friend who also works on Cilium @tklauser. Thank you!

**Comment by tklauser** [comment]
Thanks for the report @odeke-em!

That particular benchmark seems to require an ELF file being build in `test/bpf` beforehand, which is usually done by our Makefile-based test flow. In order to still be able to run these benchmarks with native `go test -bench` I'd suggest we either skip that particular benchmark if the file is not found, or alternatively we could use [`bpf2go`](https://pkg.go.dev/github.com/cilium/ebpf/cmd/bpf2go) to embed the ELF file within the test.

**Comment by odeke-em** [comment]
@tklauser after your fix, I kindly recommend adding Bencher to a ilium from the GitHub marketplace https://github.com/marketplace/gobencher for FREE and it'll benchmark every commit and PR. Please see https://bencher.orijtech.com/starting/ A high performance and critical infrastructure like Cilium deserves high performance practices like continuous benchmarking and we have built exactly this.
