### ISSUE TITLE
Cilium starts announcing LB's IPs via BGP before creating rules for manage traffic

### ISSUE THREAD

**Issue by ArsenyBelorukov** [cilium/cilium#17547]
## Bug report

**General Information**

- Cilium version: v1.10.4
- Kernel version: 5.14.8
- Orchestration system version in use v1.18.2.  

bare metal servers

I set up cilium with separate nodes to receive LB traffic, that announces LB’s IPs via BGP (metalLb https://docs.cilium.io/en/stable/gettingstarted/bgp/)
And faced with a problem, when cilium is starting up, it starts to announce IPs before creating rules for manage traffic for these IPs.
This causes there to be a period (~15 seconds) when traffic goes to the server, but drops.

**How to reproduce the issue**

1. Set up cilium with 2 separated nodes, which are announcing LB's IPs via BGP (nodeA and nodeB)
2. Create service with type LoadBalancer (ServiceA)
3. Reboot nodeA
4. Start requesting ServiceA 
5. Start kubelet on nodeA
6. Observe period when requests to ServiceA are failed

This is clearly visible in the cilium agent's log:
```
2021-10-06T08:53:37.362544524Z stderr F level=debug msg="ip 10.120.128.1 pool default protocol event updatedAdvertisements numAds msg making advertisements using BGP" subsys=bgp-speaker
2021-10-06T08:53:37.362552318Z stderr F level=debug msg="ip 10.120.128.1 pool default protocol event serviceAnnounced msg service has IP, announcing" subsys=bgp-speaker
.....
2021-10-06T08:53:51.507019089Z stderr F level=debug msg="Finished writing ELF" error="<nil>" new-elf-path=800_next/bpf_host.o subsys=elf template-path=/var/run/cilium/state/templates/37b36b69377e02a34854ade150fee265cf6405cf0e97e2d70adba74e2a24da0b/bpf_host.o
```
[cilium.log](https://github.com/cilium/cilium/files/7293747/cilium.log)

I have more logs from my test stand if they are needed

**Comment by brb** [comment]
@ArsenyBelorukov Thanks for the report.

@christarazi @ldelossa We should start the BGP announcer after the datapath has been regenerated. Yet another use case for a proper init system in the daemon.

**Comment by ldelossa** [comment]
@brb is the current way to do this just placing any bgp init code after the datapath init methods?

**Comment by brb** [comment]
@ldelossa It depends whether the datapath init is async. If so, then we should signal the daemon once all bpf_host instances have been reloaded. Otherwise, yes, placing the BGP init after the DP init should be good.

**Comment by christarazi** [comment]
Why doesn't Kubernetes update that `Endpoint` object to say that the backend is not healthy? If that happens, then we wouldn't need to change anything on the BGP side. It's already hooked up to take into account the health of the backend(s) and will withdraw routes  if unhealthy. Before we suggest changing the datapath / BGP init, I'd first investigate why Kubernetes is not telling us the health of the backends.

**Comment by ArsenyBelorukov** [comment]
@christarazi backed is healthy. Dataplan has not been ready when announcement already works.
