### ISSUE TITLE
[ BGP - PodCidrs  ] - NIL sessions being returned by MetalLB Speaker

### ISSUE THREAD

**Issue by ldelossa** [cilium/cilium#17556]
> @sbskas - Can you please try with the latest code. The line number you have listed in that log does not exist.
> 
> If you continue to experience this issue can you open an issue and assign me? Thanks.

Sorry for mismatch. logs were produced with a custom that printf the calling arguments (line  VLN....).
Here's the log produced with commit 59ace73967d1c3f3dda3f68680881a3cf8649647

[log-crash-podcidr-bgp-02.txt](https://github.com/cilium/cilium/files/7304048/log-crash-podcidr-bgp-02.txt)

_Originally posted by @sbskas in https://github.com/cilium/cilium/issues/16525#issuecomment-937838367_

**Comment by sbskas** [comment]
Ok, here's the configuration we used.
I think you need a little extra information about our config.
This test cluster is composed of 3 masters and 3 workers.
  master1 and worker1 are running on datacenter1 but on different lans
  master2 and worker2 are running on datacenter2 
  master3 and worker3 are running on datacenter3
Each machine is running cilium without encapsulation and announce a bgp route of it's pod's lan to the other.
We have this setup running at this time with a bird process on each cluster's node.
The peering bgp is a pair of cisco leaves running NXOS.

[bgp-config.txt](https://github.com/cilium/cilium/files/7306991/bgp-config.txt)

**Comment by sbskas** [comment]
@ldelossa if you want me to run a debug process with trace or take some capture packets, I'll be glad to help.

**Comment by sbskas** [comment]
Here's the cilium-config file.
[cilium-config.yaml](https://github.com/cilium/cilium/files/7307318/cilium-config.txt)

**Comment by sbskas** [comment]
I compiled agent branch up to commit 9579d739e. Is that the right commits to pick up ?
Crash is still present.
Logs are included. 
 [logs-cilium-test-9579d739e.txt](https://github.com/cilium/cilium/files/7315579/logs-cilium-test-9579d739e.txt).
I'm still seeing a crash in the agent.
`level=debug msg="adding event to queue" component=MetalLBSpeaker.OnAddNode node=worker1 subsys=bgp-speaker
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 182 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2257140, 0x40149f0})
  /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000172a00})
  /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x2257140, 0x40149f0})
  /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/cilium/cilium/pkg/bgp/speaker.(*MetalLBSpeaker).OnUpdateNode(0xc00007efa0, 0x0, 0xc0005fbb00)
  /go/src/github.com/cilium/cilium/pkg/bgp/speaker/speaker.go:260 +0x147
github.com/cilium/cilium/pkg/bgp/speaker.(*MetalLBSpeaker).OnAddNode(0xc00007efa0, 0xc0005fbb00)
  /go/src/github.com/cilium/cilium/pkg/bgp/speaker/speaker.go:245 +0x19c
github.com/cilium/cilium/pkg/k8s/watchers/subscriber.(*NodeChain).OnAddNode(0x26000e0, 0xc0005fbb00)
  /go/src/github.com/cilium/cilium/pkg/k8s/watchers/subscriber/node.go:52 +0x209
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).NodesInit.func1.1({0x26000e0, 0xc0005fbb00})
  /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:46 +0x8a
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
  /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:231
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x2299e00, 0xc000588a38})
  /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:108 +0x2a5
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000172a00, 0xc0006f25c0)
  /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:544 +0x2ea
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00069a480)
  /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:183 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f961fc9f5b8)
  /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xf544a8, {0x2a32600, 0xc000bdcf00}, 0x1, 0xc000099020)
  /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00069a4e8, 0x3b9aca00, 0x0, 0x0, 0x7f961fcb1b60)
  /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
  /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc00069a480, 0xc000099020)
  /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:154 +0x2fb
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).NodesInit.func1
  /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:81 +0x33a
`

**Comment by sbskas** [comment]
@Idelossa Please find the corresponding log.
`level=debug msg="event nodeLabelsChanged msg Node labels changed, resyncing BGP peers" subsys=bgp-speaker
level=debug msg="event peerAdded peer 10.90.140.1 msg peer configured, starting BGP session" subsys=bgp-speaker
level=debug msg="event peerAdded peer 10.90.140.2 msg peer configured, starting BGP session" subsys=bgp-speaker
level=debug msg="announcing pod CIDR(s)" cidrs="&[10.39.66.128/25]" component=MetalLBSpeaker.handleNodeEvent labels="&map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux fluentd:true kubernetes.io/arch:amd64 kubernetes.io/hostname:kw01-vso-pr kubernetes.io/os:linux metallb-speaker:true role:ingress-controller topology.kubernetes.io/zone:acheres]" subsys=bgp-speaker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1bb7abf]

goroutine 208 [running]:
github.com/cilium/cilium/pkg/bgp/speaker.(*MetalLBSpeaker).announce(0x0, {0x0, 0x0}, {0xc0007890d0, 0x1, 0x0})
	/go/src/github.com/cilium/cilium/pkg/bgp/speaker/pod_cidr.go:82 +0xbf
github.com/cilium/cilium/pkg/bgp/speaker.(*MetalLBSpeaker).announcePodCIDRs.func1.1()
	/go/src/github.com/cilium/cilium/pkg/bgp/speaker/pod_cidr.go:58 +0x31
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/src/github.com/cilium/cilium/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/cilium/cilium/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x92
`

[logs-cilium-test-778c9c665c.txt](https://github.com/cilium/cilium/files/7323843/logs-cilium-test-778c9c665c.txt)

**Comment by ldelossa** [comment]
```
level=info msg="All Cilium CRDs have been found and are available" subsys=k8s
level=info msg="Creating or updating CiliumNode resource" node=worker1 subsys=nodediscovery
level=debug msg="waiting for cache to synchronize" kubernetesResource="core/v1::Node" subsys=k8s
level=debug msg="adding event to queue" component=MetalLBSpeaker.OnAddNode node=worker1 subsys=bgp-speaker
level=info msg="processing new event." component=MetalLBSpeaker.run subsys=bgp-speaker
level=debug msg="syncing bgp sessions" cidrs="&[10.246.0.128/25]" component=MetalLBSpeaker.handleNodeEvent labels="&map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux fluentd:true kubernetes.io/arch:amd64 kubernetes.io/hostname:worker1 kubernetes.io/os:linux metallb-speaker:true role:ingress-controller topology.kubernetes.io/zone:acheres]" subsys=bgp-speaker
level=debug msg="event nodeLabelsChanged msg Node labels changed, resyncing BGP peers" subsys=bgp-speaker
level=debug msg="event peerAdded peer 172.16.0.1 msg peer configured, starting BGP session" subsys=bgp-speaker
level=debug msg="event peerAdded peer 172.16.0.2 msg peer configured, starting BGP session" subsys=bgp-speaker
level=debug msg="announcing pod CIDR(s)" cidrs="&[10.246.0.128/25]" component=MetalLBSpeaker.handleNodeEvent labels="&map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux fluentd:true kubernetes.io/arch:amd64 kubernetes.io/hostname:worker1 kubernetes.io/os:linux metallb-speaker:true role:ingress-controller topology.kubernetes.io/zone:acheres]" subsys=bgp-speaker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1bb7abf]
```

This is odd, seems like MetalLB is enforming us that he BGP sessions are setup, but is returning nil when we ask for them. It's possible there's a timing issue here, were we are attempting to utilize sessions before MetalLB makes them available to us. 

Let me investigate further.

**Comment by ldelossa** [comment]
@sbskas - first I want to make sure we never crash the Cilium agent. Please test with latest head: `6133087293d95bd384b0beea4e7c5d1eb0303b6d`

My hunch is that when MetalLB determines a BGP peer should not occur due to labels it returns a `nil` session object. Latest code ignores these `nil` session. I'm assuming since your config works when only particular `node-selector` fields are present, this will work as well.

**Comment by ldelossa** [comment]
@sbskas is your BGP peering working?

**Comment by ldelossa** [comment]
@sbskas are you utilizing the following feature? https://docs.cilium.io/en/v1.8/cmdref/cilium_preflight_migrate-identity/

This involves you latest issue. However this is not related to the BGP PodCidr pr. I do not want to splinter this thread. 

Instead, can you deploy a fresh install with a config which only enables BGP and confirm the peering is working as expected. If it is, we close out this issue and open a new one for the identity issue.
