### ISSUE TITLE
Make URLs version specific to provide backwards compatibility in docs

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1755]
URLs such as:
https://raw.githubusercontent.com/cilium/cilium/master/examples/kubernetes/rbac.yaml

in:
http://docs.cilium.io/en/stable/gettingstarted/#getting-started-using-kubernetes

must be rewritten to be version specific as `master` will be modified in ways that may no longer be compatible with older versions of the docs.

**Comment by ianvernon** [comment]
Should we namespace our documentation ? I.e. have separate directories for each version of Cilium (0.10,0.11,0.12). Kubernetes has something like this for their docs, but I’m not sure of how it’s implemented in their repository.

**Comment by aalemayhu** [comment]
Sounds like a lot of work and duplication. We can discuss separate directories at the next open session on the developer calls. This issue should be resolved independently of that. Thanks.

**Comment by tgraf** [comment]
> Should we namespace our documentation ? I.e. have separate directories for each version of Cilium (0.10,0.11,0.12). Kubernetes has something like this for their docs, but I’m not sure of how it’s implemented in their repository.

The different versions of the doc are isolated by the branches, no? The 0.10 docs are in the `v0.10` branch. We just have to make sure that links to examples are branched off as well.
