### ISSUE TITLE
CI: re-enable AKS testing with encryption enabled

### ISSUE THREAD

**Issue by nbusseneau** [cilium/cilium#17644]
https://github.com/cilium/cilium-cli/issues/342 is hit almost consistently on AKS when running the second `cilium connectivity test` with encryption enabled.

We disabled AKS testing with encryption enabled in #17645. The PR should be reverted whenever possible.

**Comment by nbusseneau** [comment]
This issue can be easily reproduced by spinning up an AKS cluster and then installing Cilium with encryption enabled before running a connectivity test:

```sh
kubectl create -n kube-system secret generic cilium-ipsec-keys --from-literal=keys="15 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64)) 128"
cilium install --azure-subscription "${SUBSCRIPTION}" --azure-resource-group "${NAME}" --wait=false --encryption=ipsec
cilium hubble enable
cilium hubble port-forward&
sleep 10s
[[ $(pgrep -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay" | wc -l) == 2 ]]
cilium connectivity test --force-deploy --flow-validation=disabled
```

When encryption is enabled, the issue happens almost every time. With encryption not enabled, the issue happens only very rarely.

**Comment by gandro** [comment]
Will likely fixed by https://github.com/cilium/cilium/pull/17865 ?

**Comment by nbusseneau** [comment]
> Will likely fixed by #17865 ?

We can run the CI with AKS enabled on top of the PR to check 🚀

**Comment by joestringer** [comment]
Still flaky, https://github.com/cilium/cilium/pull/19125 will re-quarantine these tests.

**Comment by julianwiedmann** [comment]
@nbusseneau just to confirm - we're now [running](https://github.com/cilium/cilium/actions/workflows/conformance-aks.yaml) ci-aks on PRs, and IPsec is also enabled in the workflow. The last remaining piece is marking the workflow as required, right?

Then I'd say we should close this issue as :heavy_check_mark:, and open a dedicated issue that lines out what's needed to mark the workflow as required.

**Comment by nbusseneau** [comment]
Yes!
