### ISSUE TITLE
Question regarding deny policy behavior

### ISSUE THREAD

**Issue by AshokAccuknox** [cilium/cilium#17653]
I using cilium last few days. I need to block a particular pod but I can't create a black list policy. So I think cilium doesn't support the black list policy. So I suggest adding a black list policy if possible. Or if cilium supports the black list policy can you give me step for creating a black list policy

**Comment by AshokAccuknox** [comment]
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "rule1"
spec:
  description: "L3-L4 policy to restrict deathstar access to empire ships only"
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP

In the above policy, it will allow only if the pod has the same label otherwise it will deny.
Here I want to deny if the pod has the same label otherwise we do not need to deny it.

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
