### ISSUE TITLE
Egress Gateway doesn't work with CiliumEndpointSlices

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#17669]
## Proposal / RFE

**Retrieve endpoint labels from numerical id within egressPolicyManager instead of relying on watched obj**

Currently when CiliumEndpointSlices is enabled, egress gateway feature would break. The egress policy updater relies on `endpoint.Identity.labels` to match endpoint to egress policy selector (https://github.com/cilium/cilium/blob/master/pkg/egresspolicy/manager.go#L242) but by design `CES` won't carry pod labels in its `CoreCEP` struct. So egress policy won't match in this case and egress map is always empty.

We discussed this issue with @MasterZ40 offline, the fix is to use `Identity.id` as a middle groud. `CoreCEP` carries the numerical id of an endpoint's security identity, and agent is already watching for all `ciliumidentities` (https://github.com/cilium/cilium/blob/master/pkg/k8s/identitybackend/identity.go#L272), so egress policy manager could just grab the numerical security id from the endpoint, then look up the full identity in the cache, then retrieve the labels.

@MasterZ40 @anfernee @aanm @krishgobinath

**Comment by pchaigno** [comment]
Easy to reproduce in master with:
```
NETNEXT=true KUBEPROXY=0 K8S_NODES=3 NO_CILIUM_ON_NODE=k8s3 ginkgo -v --focus="K8sEgressGatewayTest tunnel disabled with endpointRoutes enabled" --tags=integration_tests -- --cilium.provision=true --cilium.holdEnvironment=true -cilium.testScope="k8s" -cilium.skipLogs=true
```

**Comment by Weil0ng** [comment]
This is currently captured as a caveat in the CES guide document for 1.11, will remove that once this is fixed.

**Comment by joestringer** [comment]
Does this impact whether we can enable the feature by default in future installs?
