### ISSUE TITLE
sessionAffinity value is always true for installation via Cilium helm chart.

### ISSUE THREAD

**Issue by mzs114** [cilium/cilium#17690]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
- 1.10.x helm chart

**How to reproduce the issue**

1. ` helm fetch cilium/cilium --version 1.10.5`  (I tested with 1.10.4 and verified whether this repeats on 1.10.5)
2. `tar xf cilium-1.10.5.tgz`
3.  Edit `values.yaml` and uncomment `sessionAfinity` value in `values.yaml` file, leave the value at 'false'.
4.  Now either install using helm or to test without install run `helm template . -f values.yaml `, in the generated manifest search for `enable-session-affinity` and check the value, this is always true.

**Comment by hemslo** [comment]
This is fixed after `1.12.0`, the commit is https://github.com/cilium/cilium/commit/19d94afdf7d31d3f9688c37265c73acf5a7241a1, part of this pr https://github.com/cilium/cilium/pull/16179
