### ISSUE TITLE
Enable policy for VTEP integration feature

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#17694]
https://github.com/cilium/cilium/pull/17370 VTEP integration feature bypass `pkg/ipcache`, cause inconsistency with policy, thus not supporting network policy. open this issue to track the future work to have VTEP integration feature supporting network policy, 

see https://github.com/cilium/cilium/pull/17370#discussion_r727406374 from Joe 

"
I think that what we want is a new IP -> VTEP info map inside type IPCache struct ... and to instead update (ipc *IPCache) Upsert(...) to take optional VTEP info. Then also update IPIdentityMappingListener() to pass the new VTEP info structure down towards each implementer so that (l *BPFListener) OnIPIdentityCacheChange can prepare the RemoteEndpointInfo correctly for VTEP updates, and push the correct data down to BPF.

It's definitely a bit more complicated to pass this through pkg/ipcache and raises a few other questions, like cache *NPHDSCache also implements OnIPIdentityCacheChange(), but that proxy path doesn't need to handle updates for VTEPs since the proxies aren't responsible for redirecting outbound traffic towards the VTEPs.
"

**Comment by vincentmli** [comment]
start to think about this, instead of adding  `IP -> VTEP` in type  `IPCache` struct and update `Upsert(...)` to take optional VETP info in `pkg/ipcache/ipcache.go`,  We could simplify this by adding something similar to the `specialIdentities` in   `syncEndpointsAndHostIPs()` in `daemon/cmd/datapath.go`, and invoke `Upsert(...)` to insert the `IP -> VTEP` .  this way, we don't need to change  `IPCache` struct, `Upsert(...)`, and 
`IPIdentityMappingListener()`, I might be missing something in the context of security policy, but it seems much simpler, and less intrusive implementation. 

https://github.com/cilium/cilium/blob/master/daemon/cmd/datapath.go#L230-L255

**Comment by vincentmli** [comment]
did an experiment with following diff

```
diff --git a/daemon/cmd/datapath.go b/daemon/cmd/datapath.go
index 40c8ece7fb..6e1024f585 100644
--- a/daemon/cmd/datapath.go
+++ b/daemon/cmd/datapath.go
@@ -269,10 +269,21 @@ func (d *Daemon) syncEndpointsAndHostIPs() error {
        }
 
        if option.Config.EnableVTEP {
-               err := setupIPCacheVTEPMapping()
-               if err != nil {
-                       return err
+               encryptKey := uint8(0) // no encrypt support
+               for i, ep := range option.Config.VtepEndpoints {
+                       log.WithFields(logrus.Fields{
+                               logfields.IPAddr: ep,
+                       }).Debug("Updating ipcache map entry for VTEP")
+
+                       hostIPCIDR := option.Config.VtepCIDRs[i]
+
+                       ipcache.IPIdentityCache.Upsert(hostIPCIDR.IP.String(), ep, encryptKey, nil, ipcache.Identity{
+                               ID:     identity.ReservedIdentityWorld,
+                               Source: source.Local,
+                       })
+
                }
+
        }
 
        return nil

```

with vtep in `cilium-config` configmap

```
  enable-vtep:   "true"
  vtep-endpoint: "10.169.72.236     10.169.72.238"
  vtep-cidr:     "10.1.5.0/24       10.1.8.0/24"
  vtep-mac:      "82:36:4c:98:2e:56 82:36:4c:98:2e:55"

```
ended up in ipcache

```
IP PREFIX/ADDRESS   IDENTITY
10.1.5.0/32         identity=2 encryptkey=0 tunnelendpoint=10.169.72.236   
10.1.8.0/32         identity=2 encryptkey=0 tunnelendpoint=10.169.72.238 
  ```
note `10.1.5.0/32` should have been `10.1.5.0/24`, something not right in `Upsert()` dealing with `CIDR`

**Comment by vincentmli** [comment]
> ```
> IP PREFIX/ADDRESS   IDENTITY
> 10.1.5.0/32         identity=2 encryptkey=0 tunnelendpoint=10.169.72.236   
> 10.1.8.0/32         identity=2 encryptkey=0 tunnelendpoint=10.169.72.238 
> ```
> 
> note `10.1.5.0/32` should have been `10.1.5.0/24`, something not right in `Upsert()` dealing with `CIDR`

following diff correct the mistakes

```
diff --git a/daemon/cmd/datapath.go b/daemon/cmd/datapath.go
index 40c8ece7fb..88e84cfc98 100644
--- a/daemon/cmd/datapath.go
+++ b/daemon/cmd/datapath.go
@@ -269,10 +269,24 @@ func (d *Daemon) syncEndpointsAndHostIPs() error {
        }
 
        if option.Config.EnableVTEP {
-               err := setupIPCacheVTEPMapping()
-               if err != nil {
-                       return err
+               encryptKey := uint8(0) // no encrypt support
+               for i, ep := range option.Config.VtepEndpoints {
+
+                       vtepCIDR := option.Config.VtepCIDRs[i]
+
+                       ipIDPair := identity.IPIdentityPair{
+                               IP:   vtepCIDR.IP,
+                               Mask: vtepCIDR.Mask,
+                               ID:   identity.ReservedIdentityWorld,
+                       }
+
+                       ipcache.IPIdentityCache.Upsert(ipIDPair.PrefixString(), ep, encryptKey, nil, ipcache.Identity{
+                               ID:     ipIDPair.ID,
+                               Source: source.Local,
+                       })
+
                }
+
        }
 
        return nil
```

the ipcache:

```
IP PREFIX/ADDRESS   IDENTITY
10.1.5.0/24         identity=2 encryptkey=0 tunnelendpoint=10.169.72.236   
10.1.8.0/24         identity=2 encryptkey=0 tunnelendpoint=10.169.72.238 
```

**Comment by vincentmli** [comment]
continue investigating the VTEP integration feature with above patches with `toCIDR` network policy, for example I have network policy

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "cidr-rule"
spec:
  endpointSelector:
    matchLabels:
      app: netshoot 
  egress:
  - toCIDR:
    - 10.1.0.0/16. <===toCIDR contains VTEP CIDR 10.1.5.0/24

```

VTEP:

```
  enable-vtep:   "true"
  vtep-endpoint: "10.169.72.236 "
  vtep-cidr:     "10.1.5.0/24"
  vtep-mac:      "82:36:4c:98:2e:56"

```

apply above `toCIDR` policy and VTEP result in ipcache record:

```
10.1.0.0/16         identity=16777220 encryptkey=0 tunnelendpoint=0.0.0.0     <===toCIDR
10.1.5.0/24         identity=2 encryptkey=0 tunnelendpoint=10.169.72.236  <====VTEP
```

 the `toCIDR` network policy egress `10.1.0.0/16` is applied to pod `netshoot`

```
kubectl exec -it cilium-fvrrs -n kube-system -- cilium bpf policy get --all

/sys/fs/bpf/tc/globals/cilium_policy_02266:

POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Allow    Ingress     reserved:unknown              ANY          NONE         700     10        
Allow    Ingress     reserved:host                 ANY          NONE         0       0         
Allow    Egress      cidr:10.1.0.0/16              ANY          NONE         0       0         <======
                     reserved:world         


 kubectl exec -it cilium-fvrrs -n kube-system -- cilium endpoint list
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                    IPv6   IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                     
                                  
2266       Disabled           Enabled           46007      k8s:app=netshoot                                                                      10.0.1.86    ready   
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                     
                                                           k8s:io.cilium.k8s.policy.cluster=default                                                                   
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                            
                                                           k8s:io.kubernetes.pod.namespace=default            
```

from netshoot pod, ping ip address in VTEP CIDR `10.1.5.236`, since ipcache map is LPM, 10.1.5.236 matches ipcache record `10.1.5.0/24`, but the `toCIDR` network policy map type is hash map which is keyed by `10.1.0.0/16` that does not match `10.1.5.0/24`, thus the packet is dropped by policy deny, seen from cilium datapath debug log:

```
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=3e:be:42:fd:9a:99 DstMAC=5a:e0:3b:98:24:d2 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=61861 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=11713 SrcIP=10.0.1.86 DstIP=10.1.5.236 Options=[] Padding=[]}
ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=58470 Id=61862 Seq=1}
  Failed to decode layer: No decoder for layer type Payload
CPU 05: MARK 0x0 FROM 2266 from-endpoint: 98 bytes (98 captured), state new, , identity 46007->unknown, orig-ip 0.0.0.0
CPU 05: MARK 0x0 FROM 2266 DEBUG: Conntrack lookup 1/2: src=10.0.1.86:61862 dst=10.1.5.236:0
CPU 05: MARK 0x0 FROM 2266 DEBUG: Conntrack lookup 2/2: nexthdr=1 flags=1
CPU 05: MARK 0x0 FROM 2266 DEBUG: CT verdict: New, revnat=0
CPU 05: MARK 0x0 FROM 2266 DEBUG: Successfully mapped addr=10.1.5.236 to identity=2 <= IPCACHE 10.1.5.0/24
CPU 05: MARK 0x0 FROM 2266 DEBUG: Policy evaluation would deny packet from 46007 to 2
Policy verdict log: flow 0x0 local EP ID 2266, remote ID world, proto 1, egress, action deny, match none, 10.0.1.86 -> 10.1.5.236 EchoRequest <==toCIDR policy hash map keyed by 10.1.0.0/16, not match 10.1.5.0/24
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=3e:be:42:fd:9a:99 DstMAC=5a:e0:3b:98:24:d2 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=61861 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=11713 SrcIP=10.0.1.86 DstIP=10.1.5.236 Options=[] Padding=[]}
ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=58470 Id=61862 Seq=1}
  Failed to decode layer: No decoder for layer type Payload
CPU 05: MARK 0x0 FROM 2266 DROP: 98 bytes, reason Policy denied, identity 46007->world
------------------------------------------------------------------------------
```

**Comment by vincentmli** [comment]
continue from previous example, now let me change the `toCIDR` policy like below to the specific IP address `10.1.5.236` we are going to ping from `netshoot` pod

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "cidr-rule"
spec:
  endpointSelector:
    matchLabels:
      app: netshoot 
  egress:
  - toCIDR:
    - 10.1.5.236/32 <==fall in VTEP CIDR 10.1.5.0/24
```

the ipcache map are 

```

10.1.5.236/32       identity=16777221 encryptkey=0 tunnelendpoint=0.0.0.0  <===toCIDR
10.1.5.0/24         identity=2 encryptkey=0 tunnelendpoint=10.169.72.236  <===VTELP CIDR

```

the network policy applied to `netshoot` pod

```
/sys/fs/bpf/tc/globals/cilium_policy_02266:

POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Allow    Ingress     reserved:unknown              ANY          NONE         700     10        
Allow    Ingress     reserved:host                 ANY          NONE         0       0         
Allow    Egress      cidr:10.1.5.236/32            ANY          NONE         0       0         <====
                     reserved:world        
``` 

now when I ping `10.1.5.236` from `netshoot` pod, ipcache map found      `10.1.5.236/32`, and policy map found `Allow    Egress      cidr:10.1.5.236/32`, so no policy deny, but the ipcache map record `10.1.5.236/32` has  `tunnelendpoint=0.0.0.0`, not VTEP endpoint `10.169.72.236`, and packet is dropped, seen from the datapath debug log:

```
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=3e:be:42:fd:9a:99 DstMAC=5a:e0:3b:98:24:d2 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=14710 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=58864 SrcIP=10.0.1.86 DstIP=10.1.5.236 Options=[] Padding=[]}
ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=6255 Id=41072 Seq=1}
  Failed to decode layer: No decoder for layer type Payload
CPU 07: MARK 0x0 FROM 2266 from-endpoint: 98 bytes (98 captured), state new, , identity 46007->unknown, orig-ip 0.0.0.0
CPU 07: MARK 0x0 FROM 2266 DEBUG: Conntrack lookup 1/2: src=10.0.1.86:41072 dst=10.1.5.236:0
CPU 07: MARK 0x0 FROM 2266 DEBUG: Conntrack lookup 2/2: nexthdr=1 flags=1
CPU 07: MARK 0x0 FROM 2266 DEBUG: CT verdict: New, revnat=0
CPU 07: MARK 0x0 FROM 2266 DEBUG: Successfully mapped addr=10.1.5.236 to identity=16777222
Policy verdict log: flow 0x0 local EP ID 2266, remote ID 16777222, proto 1, egress, action allow, match L3-Only, 10.0.1.86 -> 10.1.5.236 EchoRequest <===POLICY MATCHES
CPU 07: MARK 0x0 FROM 2266 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=46007 lb=0.0.0.0
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=3e:be:42:fd:9a:99 DstMAC=5a:e0:3b:98:24:d2 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=14710 Flags=DF FragOffset=0 TTL=63 Protocol=ICMPv4 Checksum=59120 SrcIP=10.0.1.86 DstIP=10.1.5.236 Options=[] Padding=[]}
ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=6255 Id=41072 Seq=1}
  Failed to decode layer: No decoder for layer type Payload
CPU 07: MARK 0x0 FROM 2266 to-stack: 98 bytes (98 captured), state new, , identity 46007->16777222, orig-ip 0.0.0.0
------------------------------------------------------------------------------
CPU 07: MARK 0x0 FROM 2266 DEBUG: 98 bytes, Delivery to ifindex 0
Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=3e:be:42:fd:9a:99 DstMAC=5a:e0:3b:98:24:d2 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=14710 Flags=DF FragOffset=0 TTL=63 Protocol=ICMPv4 Checksum=59120 SrcIP=10.0.1.86 DstIP=10.1.5.236 Options=[] Padding=[]}
ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=6255 Id=41072 Seq=1}
  Failed to decode layer: No decoder for layer type Payload

```

**Comment by vincentmli** [comment]
> continue investigating the VTEP integration feature with above patches with `toCIDR` network policy, for example I have network policy
> 
> ```
> apiVersion: "cilium.io/v2"
> kind: CiliumNetworkPolicy
> metadata:
>   name: "cidr-rule"
> spec:
>   endpointSelector:
>     matchLabels:
>       app: netshoot 
>   egress:
>   - toCIDR:
>     - 10.1.0.0/16. <===toCIDR contains VTEP CIDR 10.1.5.0/24
> ```
> 
> VTEP:
> 
> ```
>   enable-vtep:   "true"
>   vtep-endpoint: "10.169.72.236 "
>   vtep-cidr:     "10.1.5.0/24"
>   vtep-mac:      "82:36:4c:98:2e:56"
> ```
> 
> apply above `toCIDR` policy and VTEP result in ipcache record:
> 
> ```
> 10.1.0.0/16         identity=16777220 encryptkey=0 tunnelendpoint=0.0.0.0     <===toCIDR
> 10.1.5.0/24         identity=2 encryptkey=0 tunnelendpoint=10.169.72.236  <====VTEP
> ```
> 
> the `toCIDR` network policy egress `10.1.0.0/16` is applied to pod `netshoot`
> 
> ```
> kubectl exec -it cilium-fvrrs -n kube-system -- cilium bpf policy get --all
> 
> /sys/fs/bpf/tc/globals/cilium_policy_02266:
> 
> POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
> Allow    Ingress     reserved:unknown              ANY          NONE         700     10        
> Allow    Ingress     reserved:host                 ANY          NONE         0       0         
> Allow    Egress      cidr:10.1.0.0/16              ANY          NONE         0       0         <======
>                      reserved:world         
> 
> 
>  kubectl exec -it cilium-fvrrs -n kube-system -- cilium endpoint list
> Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
> ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                    IPv6   IPv4         STATUS   
>            ENFORCEMENT        ENFORCEMENT                                                                                                                     
>                                   
> 2266       Disabled           Enabled           46007      k8s:app=netshoot                                                                      10.0.1.86    ready   
>                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                     
>                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                   
>                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                            
>                                                            k8s:io.kubernetes.pod.namespace=default            
> ```
> 
> from netshoot pod, ping ip address `10.1.5.236` that is in VTEP CIDR `10.1.5.0/24`, since ipcache map is LPM, 10.1.5.236 matches ipcache record `10.1.5.0/24`, but the `toCIDR` network policy map type is hash map which is keyed by :
> 
> ```
> struct policy_key {
>         __u32           sec_label;
>         __u16           dport;
>         __u8            protocol;
>         __u8            egress:1,
>                         pad:7;
> };    
> 
>   #ifdef POLICY_MAP
> /* Per-endpoint policy enforcement map */
> struct {
>         __uint(type, BPF_MAP_TYPE_HASH); <====HASH MAP
>         __type(key, struct policy_key);
>         __type(value, struct policy_entry);
>         __uint(pinning, LIBBPF_PIN_BY_NAME);
>         __uint(max_entries, POLICY_MAP_SIZE);
>         __uint(map_flags, CONDITIONAL_PREALLOC);
> } POLICY_MAP __section_maps_btf;
> #endif  
> ```
> 
> `10.1.0.0/16` `sec_label` or identity `16777220` does not match `10.1.5.236` `sec_label` or identity `2` , thus no egress policy for `10.1.5.236`, the packet is dropped by policy deny, seen from cilium datapath debug log:
> 
> ```
> Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=3e:be:42:fd:9a:99 DstMAC=5a:e0:3b:98:24:d2 EthernetType=IPv4 Length=0}
> IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=61861 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=11713 SrcIP=10.0.1.86 DstIP=10.1.5.236 Options=[] Padding=[]}
> ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=58470 Id=61862 Seq=1}
>   Failed to decode layer: No decoder for layer type Payload
> CPU 05: MARK 0x0 FROM 2266 from-endpoint: 98 bytes (98 captured), state new, , identity 46007->unknown, orig-ip 0.0.0.0
> CPU 05: MARK 0x0 FROM 2266 DEBUG: Conntrack lookup 1/2: src=10.0.1.86:61862 dst=10.1.5.236:0
> CPU 05: MARK 0x0 FROM 2266 DEBUG: Conntrack lookup 2/2: nexthdr=1 flags=1
> CPU 05: MARK 0x0 FROM 2266 DEBUG: CT verdict: New, revnat=0
> CPU 05: MARK 0x0 FROM 2266 DEBUG: Successfully mapped addr=10.1.5.236 to identity=2 <= IPCACHE 10.1.5.0/24
> CPU 05: MARK 0x0 FROM 2266 DEBUG: Policy evaluation would deny packet from 46007 to 2
> Policy verdict log: flow 0x0 local EP ID 2266, remote ID world, proto 1, egress, action deny, match none, 10.0.1.86 -> 10.1.5.236 EchoRequest <==toCIDR policy hash map keyed by 10.1.0.0/16 sec_label, not match 10.1.5.0/24 sec_label
> ------------------------------------------------------------------------------
> Ethernet        {Contents=[..14..] Payload=[..86..] SrcMAC=3e:be:42:fd:9a:99 DstMAC=5a:e0:3b:98:24:d2 EthernetType=IPv4 Length=0}
> IPv4    {Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=61861 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=11713 SrcIP=10.0.1.86 DstIP=10.1.5.236 Options=[] Padding=[]}
> ICMPv4  {Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=58470 Id=61862 Seq=1}
>   Failed to decode layer: No decoder for layer type Payload
> CPU 05: MARK 0x0 FROM 2266 DROP: 98 bytes, reason Policy denied, identity 46007->world
> ------------------------------------------------------------------------------
> ```

following diff could address above issue, the solution is to skip policy enforcement if `toCIDR` rules contains VTEP CIDR

```
diff --git a/bpf/bpf_lxc.c b/bpf/bpf_lxc.c
index b170448e14..570919d3aa 100644
--- a/bpf/bpf_lxc.c
+++ b/bpf/bpf_lxc.c
@@ -651,6 +651,21 @@ skip_service_lookup:
        if (hairpin_flow)
                goto skip_policy_enforcement;
 
+       /* When an endpoint connects to external VTEP, we need to skip the
+        * policy enforcement if toCIDR policy rules contains VTEP CIDR
+        */
+
+#ifdef ENABLE_VTEP
+        {
+                int i;
+
+                for (i = 0; i < VTEP_NUMS; i++) {
+                        if (tunnel_endpoint == VTEP_ENDPOINT[i])
+                               goto skip_policy_enforcement;
+                }
+       }
+#endif
+

```

**Comment by joestringer** [comment]
Skimming through the above writeups, I would like to make sure we understand that skipping policy enforcement due to another non-policy feature is not a viable solution to solve this.

What I think we need is a way to better manage multiple sources of information - VTEP, policy, apiserver policy feature, etc. and combine it so that we can generate VTEP IPcache entries with the tunnel EP of the VTEP feature + the identity from the CIDR policy feature. Issue #18301 talks about some related work, though doesn't directly describe a solution to this problem.
