### ISSUE TITLE
do not version cilium/dependencies image

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1769]
Versioning the Cilium dependencies image makes it hard to do releases. Do not version this image, and just use `latest`.

**Comment by aanm** [comment]
Why? I think we should version this image, properly. Right now all versions are simply pointing to master without any awareness of a git tag or cilium version. And document this steps

**Comment by tgraf** [comment]
> Why? I think we should version this image, properly. Right now all versions are simply pointing to master without any awareness of a git tag or cilium version. And document this steps

When discussing with @ianvernon, what I meant is to no longer require a strict 1:1 mapping between cilium version and dependency version. I'd rather store this dependency in a file in the git tree so that each cilium branch can point to the required version of the dependency image.

**Comment by ianvernon** [comment]
@tgraf I think we can close this, as https://github.com/cilium/cilium/pull/2452 changed how we do the Docker build. The dependency image names are no longer explicitly tied to the version of Cilium being built. Please confirm.
