### ISSUE TITLE
Use private address space for VIPs in tests

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#17701]
This test is using an IP address from Orange's public range to validate some functionality:

https://github.com/cilium/cilium/blob/da26d0ae6f25c1fa28ba1d686e5505eb245e4908/test/l4lb/test.sh#L97

There are other examples as well, eg in `test/runtime/lb.go`.

We should avoid using IP addresses that are allocated to other purposes in the testing code.

More appropriate address ranges would be, eg:
* RFC1918 address space (`10.0.0.0/8`, `192.168.0.0/16`, `172.16.0.0/12`)
* Maybe TEST-NET-1 (`192.0.2.0/24`)

**Comment by duttaANI** [comment]
@pchaigno Could you trigger the end to end tests . Also there were many IP addresses like 1.1.1.1 , 3.3.3.3 , 4.4.4.4 used for testing which could be converted to 10.0.0.1 , 10.0.0.3 , 10.0.0.4 respectively

**Comment by pchaigno** [comment]
> Also there were many IP addresses like 1.1.1.1 , 3.3.3.3 , 4.4.4.4 used for testing which could be converted to 10.0.0.1 , 10.0.0.3 , 10.0.0.4 respectively

Note some of these are on purpose, to test connections to outside the cluster.

**Comment by joestringer** [comment]
Indeed, I would say that it's worth reviewing but most likely the cases with `1.1.1.1` are deliberately attempting to access the CloudFlare website. However `2.2.2.2` / `3.3.3.3` / `4.4.4.4` are not likely to be deliberately using those addresses.

**Comment by duttaANI** [comment]
> Note some of these are on purpose, to test connections to outside the cluster.

I will check the description provided about each test case and modify .



> Indeed, I would say that it's worth reviewing but most likely the cases with `1.1.1.1` are deliberately attempting to access the CloudFlare website. However `2.2.2.2` / `3.3.3.3` / `4.4.4.4` are not likely to be deliberately using those addresses.

So should I proceed with changing 2.2.2.2 / 3.3.3.3 / 4.4.4.4 and leave 1.1.1.1?

**Comment by pchaigno** [comment]
> > Note some of these are on purpose, to test connections to outside the cluster.
>
> I will check the description provided about each test case and modify .

It should be fine to just change the 2.2.2.2, 3.3.3.3, and 4.4.4.4 and leave 1.1.1.1 as is for now.

**Comment by duttaANI** [comment]
In the PR travis CI is failing . Is there any method to identify which unit test is causing this failure ? @pchaigno @joestringer

**Comment by duttaANI** [comment]
I have created a new PR to address the issue of commit history .

**Comment by pchaigno** [comment]
> I have created a new PR to address the issue of commit history .

You can simply force push the updated branch to the first PR.

**Comment by duttaANI** [comment]
> You can simply force push the updated branch to the first PR.

This is convenient . Thank you , I was not aware that we could force push a branch to other branch.

**Comment by pchaigno** [comment]
I've triggered the end-to-end tests on the pull request.
