### ISSUE TITLE
syncWithRuntime waits forever to finish

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1772]
```
goroutine 57 [semacquire, 4937 minutes]:
sync.runtime_Semacquire(0xc420b4969c)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420b49690)
	/usr/local/go/src/sync/waitgroup.go:131 +0x72
github.com/cilium/cilium/pkg/workloads/containerd.syncWithRuntime()
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:152 +0x272
github.com/cilium/cilium/pkg/workloads/containerd.EnableEventListener.func1(0xc42032b260)
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:112 +0x39
created by github.com/cilium/cilium/pkg/workloads/containerd.EnableEventListener
	/tmp/cilium-net-build/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:109 +0x291
```

this stack trace was based from commit e8b46ee470b3f96657fcaf7d446b6e57cbddade0

**Comment by raybejjani** [comment]
Hmm. Did you see any other wierdo exits? for it to block on the wait group means a goroutine exited without a `wg.Done()` (so it would have paniced). This behaviour is slightly better in https://github.com/cilium/cilium/pull/1691 but it could still happen in cases where the `handleCreateContainer` blocks. That would require it to block that long trying to talk to docker or with EndpointManager, neither of which seems likely.

Was this in a particular runtime test or all of them?

**Comment by aanm** [comment]
This is on a deployment running cilium where cilium is deadlocked. I just got the whole stack trace and saw that one. I don't see any panics so I think it might be some concurrent issue.
