### ISSUE TITLE
Does cilium support kata? 

### ISSUE THREAD

**Issue by jwcesign** [cilium/cilium#17725]
## question
I read the article about eBPF, it can be used to reduce the memory cost by replace pod sidecar with cilium.

But it looks like the implementation needs the container share kernel with eBPF.

So for the runtime which as own kernel, does it work?

**Comment by nejisama** [comment]
@pchaigno is that means Cilium can works with Kata without the eBPF ?

**Comment by pchaigno** [comment]
You can't run Cilium without eBPF. But at this point most OSes have the minimum eBPF features required for Cilium (Linux v4.9+).
