### ISSUE TITLE
LB service  redirect to a wrong backend

### ISSUE THREAD

**Issue by jack-ra** [cilium/cilium#17729]
## Bug report

my connection to service is redirect to a wrong backend pod.

**current service:**
```
root@master1:/home/cilium# cilium service get 59
10.254.162.28:8080 =>
		1 => 192.168.154.116:8080 (59)
		2 => 192.168.177.116:8080 (59)
                3 => 192.168.214.171:8080 (59)

root@master1:/home/cilium# cilium bpf lb list  |grep -C 5 10.254.162.28
                       10.37.17.13:9100 (28)                      
10.254.39.41:8080      192.168.154.117:8680 (37)                  
                       192.168.177.88:8680 (37)                   
                       0.0.0.0:0 (37) [ClusterIP, non-routable]   
                       192.168.154.80:8680 (37)                   
10.254.162.28:8080     0.0.0.0:0 (59) [ClusterIP, non-routable]   
                       192.168.214.171:8080 (59)                  
                       192.168.154.116:8080 (59)                  
                       192.168.177.116:8080 (59)          
```

service 10.254.162.28:8080 has 3 backends 192.168.214.171:8080, 192.168.154.116:8080, 192.168.177.116:8080

**conntrack in cilium bpf:**
```
root@master1:/home/cilium# cilium bpf ct list global |grep 57878|grep TCP
TCP OUT 10.254.162.28:8080 -> 192.168.154.121:57878 service expires=470921 RxPackets=0 RxBytes=144 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=449321 Flags=0x0010 [ SeenNonSyn ] RevNAT=59 SourceSecurityID=0 IfIndex=0 
TCP OUT 192.168.154.121:57878 -> 192.168.177.108:7080 expires=470921 RxPackets=2273 RxBytes=549722 RxFlagsSeen=0x1a LastRxReport=449321 TxPackets=4544 TxBytes=606497 TxFlagsSeen=0x1a LastTxReport=449321 Flags=0x0010 [ SeenNonSyn ] RevNAT=59 SourceSecurityID=35012 IfIndex=0 
```
the forward flow ct is 10.254.162.28:8080 -> 192.168.154.121:57878, the reply flow is  192.168.154.121:57878 -> 192.168.177.108:7080

this service  conntrack has right RevNAT 59 and use 144 as its backend. Apprently the backend is not the right backend to this service. 

I think the reason is:
1. A backend of the service removed and backend ID release, but service conntracks are not deleted.
2. Another backend is added and use the same backend ID.
3. A new connection hit the an old service conntrack that is using the  old backend ID.

then it happened.

a solution to the problem:

When we do check backend, we also make sure that it is a backend of the service
```
	/* If the lookup fails it means the user deleted the backend out from
	 * underneath us. To resolve this fall back to hash. If this is a TCP
	 * session we are likely to get a TCP RST.
	 */
	backend = lb4_lookup_backend(ctx, state->backend_id);
	if (!backend) {
		key->backend_slot = 0;
		svc = lb4_lookup_service(key, false);

```

**General Information**

- Cilium version: 1.10.3
- Kernel version: 4.14.224

**Comment by brb** [comment]
@jack-ra Could you include the sysdump? Is it easy to reproduce? Could you run with the debug enabled? I am wondering which backend has the ID=144.

In the datapath we check whether the backend selected from the CT belongs to the service, so I doubt that it's the stale CT issue.

**Comment by brb** [comment]
@jack-ra Could you try using `quay.io/cilium/cilium-ci:d75aa385a9fee027b9d35f96e63e5f78c12c8f50@sha256:cb8b6e70273604b7833547cb6c9bfb4d9cab4f4230f1a4f01f773e01af23dff9` (built by https://github.com/cilium/cilium/runs/4301548530?check_suite_focus=true; based on the v1.10 branch) to see whether it resolves your issue?

**Comment by brb** [comment]
Closing, as it should be fixed by https://github.com/cilium/cilium/pull/18113. Please reopen, if the issue persists.
