### ISSUE TITLE
using cilium API modifies the labels

### ISSUE THREAD

**Issue by alonana** [cilium/cilium#17734]
I am using cilium API to create CiliumNetworkPolicy, but somehow, the labels in the endpointSelector are modified to have "any:" prefix. For some other labels the prefix "k8s:" is added. 
This happens only when using the API (from Go). It does not happen if I create a policy using kubectl apply.
I don't understand why. How can I prevent this?

In the following example, the "my-label" is created as "any:my-label".

The relevant code is:

```
	policy := ciliumApiPolicy.CiliumNetworkPolicy{
		TypeMeta: k8sApiMachinery.TypeMeta{
			Kind:       "CiliumNetworkPolicy",
			APIVersion: "cilium.io/v2",
		},
		ObjectMeta: k8sApiMachinery.ObjectMeta{
			Name:      name,
			Namespace: p.namespace,
		},
		Spec: &ciliumApiRules.Rule{
			EndpointSelector: ciliumApiRules.EndpointSelector{
				LabelSelector: &ciliumApiLabels.LabelSelector{
					MatchLabels: map[string]ciliumApiLabels.MatchLabelsValue{
						"my-label": "my-value",
					},
				},
			},
			Ingress: []ciliumApiRules.IngressRule{
				{
					IngressCommonRule: ciliumApiRules.IngressCommonRule{
						FromEndpoints: []ciliumApiRules.EndpointSelector{
							{
								LabelSelector: &ciliumApiLabels.LabelSelector{
									MatchLabels: sourceLabels,
								},
							},
						},
					},
					ToPorts: []ciliumApiRules.PortRule{
						{
							Ports: []ciliumApiRules.PortProtocol{
								{
									Port:     fmt.Sprintf("%v", port),
									Protocol: "TCP",
								},
							},
						},
					},
				},
			},
		},
	}

	log.V1("applying policy %+v", policy)
	log.V1("applying policy labels %+v", policy.Spec.EndpointSelector.MatchLabels)

	options := k8sApiMachinery.CreateOptions{}
	createdPolicy, err := p.ciliumClient.CiliumNetworkPolicies(p.namespace).Create(p.useContext, &policy, options)
	if err != nil {
		return fmt.Errorf("create failed: %v", err)
	}

```

and the result policy is:
```

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  creationTimestamp: "2021-10-28T12:12:03Z"
  generation: 1
  name: kseal-855-66-port-9200
  namespace: default
  resourceVersion: "97903"
  uid: a6d35a46-fa52-4011-93eb-617ce71091db
spec:
  endpointSelector:
    matchLabels:
      any:my-label: my-value
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:app.kubernetes.io/name: kibana
    toPorts:
    - ports:
      - port: "9200"
        protocol: TCP

```

**General Information**

- Cilium version (run `cilium version`)
cilium-cli: v0.9.2 compiled with go1.17.2 on linux/amd64
cilium image (default): v1.10.5
cilium image (stable): v1.10.5
cilium image (running): v1.10.5

- Kernel version (run `uname -a`)
Linux alonta 5.4.0-89-generic 100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, ...)
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by oblazek** [comment]
I belive it's because you are not specifying a label source. Take a look here https://github.com/cilium/cilium/blob/master/pkg/labels/labels.go#L318

**Comment by alonana** [comment]
I have tried adding the "any:" prefix, but it did not work.
Why do we have this difference between apply using kubectl and create policy using API?
It is also making a mess for the standard kubernetes labels, for example: app.kubernetes.io/name

**Comment by joestringer** [comment]
Does this cause a connectivity problem? Why do you want to avoid this?

For a bit more background, internally in Cilium, the policy model supports importing sources of identity metadata from multiple locations - previously we would import labels from k8s, or from docker, or other container runtimes. As such, when importing a standard network policy through the Cilium API, if you do not specify the source for labels, it will set the source to "any" source, which means that it should match on traffic with that label regardless of whether the label came from kubernetes or whether it came from docker or somewhere else. Functionally if you are only populating the identity labels from kubernetes, it should have no real impact. 

You can perhaps avoid the "any:" prefixes by defining the source for the labels in your policies that you add via the Cilium API, for instance by prefixing the labels with `k8s:`.

All that said, if you have the option between programmatically configuring Kubernetes CiliumNetworkPolicy objects and letting Cilium fetch & apply those policies vs. programmatically configuring Cilium network policies directly through the Cilium API to each Cilium instance on the node, I would suggest programming the Kubernetes APIs instead. These get a lot more testing, and I think that the guarantees you will get are better with this option, in particular for instance the way that Cilium will automatically synchronize the latest policies with k8s on startup.

**Comment by alonana** [comment]
I want to avoid this issue since the policy created has wrong values in the match labels:

```
spec:
  endpointSelector:
    matchLabels:
      any:my-label: my-value

```

Hence the policy is not applied for the actual pods that have the labels "my-label: my-value".
Notice that I do use the k8s API:


```
	options := k8sApiMachinery.CreateOptions{}
	createdPolicy, err := p.ciliumClient.CiliumNetworkPolicies(p.namespace).Create(p.useContext, &policy, options)
	if err != nil {
		return fmt.Errorf("create failed: %v", err)
	}

```

but it still does not work.

**Comment by joestringer** [comment]
I see, my mistake, I'm not super familiar with the CNP API code.

It's interesting to me that in the example from the first post in this issue, it only occurs for the `EndpointSelector`, but not for the selectors inside the `IngressRule`s. I'm not sure why this is, but if the code is defining the policy structure explicitly like in that example, then the `any:` part is presumably not there before calling `Create()`, so then there must be some part of the `Create()` call that manipulates the labelselector to add the `any:` section in. You might be able to debug this further by exploring that code, perhaps using a debugger like `dlv`, or print statements, or perhaps grepping around for `LabelSourceAny` or the `any` string to see what code is introducing that particular piece into the policy. Given that it's showing up in `kubectl get ...` output, it must be injected as part of the policy creation code.

**Comment by aanm** [comment]
@alonana can you provide a hello-world golang code snippet that we can take a look? Thanks

**Comment by alonana** [comment]
Here is a sample code

```
package main

import (
	"context"
	"fmt"
	ciliumApiPolicy "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	ciliumApiClient "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2"
	ciliumApiLabels "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
	ciliumApiRules "github.com/cilium/cilium/pkg/policy/api"
	k8sApiMachinery "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/tools/clientcmd"
	"os"
	"path/filepath"
)

func main() {
	name := "policy1"
	sourceLabels := map[string]string{
		"label1": "value1",
	}
	targetLabels := map[string]string{
		"label2": "value2",
	}
	port := 80
	namespace := "default"

	policy := ciliumApiPolicy.CiliumNetworkPolicy{
		TypeMeta: k8sApiMachinery.TypeMeta{
			Kind:       "CiliumNetworkPolicy",
			APIVersion: "cilium.io/v2",
		},
		ObjectMeta: k8sApiMachinery.ObjectMeta{
			Name:      name,
			Namespace: namespace,
		},
		Spec: &ciliumApiRules.Rule{
			EndpointSelector: ciliumApiRules.EndpointSelector{
				LabelSelector: &ciliumApiLabels.LabelSelector{
					MatchLabels: targetLabels,
				},
			},
			Ingress: []ciliumApiRules.IngressRule{
				{
					IngressCommonRule: ciliumApiRules.IngressCommonRule{
						FromEndpoints: []ciliumApiRules.EndpointSelector{
							{
								LabelSelector: &ciliumApiLabels.LabelSelector{
									MatchLabels: sourceLabels,
								},
							},
						},
					},
					ToPorts: []ciliumApiRules.PortRule{
						{
							Ports: []ciliumApiRules.PortProtocol{
								{
									Port:     fmt.Sprintf("%v", port),
									Protocol: "TCP",
								},
							},
						},
					},
				},
			},
		},
	}

	configPath := filepath.Join(os.Getenv("HOME"), ".kube", "config")
	restConfig, err := clientcmd.BuildConfigFromFlags("", configPath)
	if err != nil {
		panic(err)
	}

	ciliumClient, err := ciliumApiClient.NewForConfig(restConfig)
	if err != nil {
		panic(err)
	}

	options := k8sApiMachinery.CreateOptions{}
	_, err = ciliumClient.CiliumNetworkPolicies(namespace).Create(context.Background(), &policy, options)
	if err != nil {
		panic(err)
	}
}

```

and the result policy is:

```
$ kubectl get cnp policy1 -o yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  creationTimestamp: "2022-01-09T05:28:54Z"
  generation: 1
  managedFields:
  - apiVersion: cilium.io/v2
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:endpointSelector:
          .: {}
          f:matchLabels:
            .: {}
            f:any:label2: {}
        f:ingress: {}
      f:status: {}
    manager: ___go_build_main_go__1_
    operation: Update
    time: "2022-01-09T05:28:54Z"
  name: policy1
  namespace: default
  resourceVersion: "82302"
  uid: 6769a65f-a3b8-401f-817c-e3d43d855acc
spec:
  endpointSelector:
    matchLabels:
      any:label2: value2
  ingress:
  - fromEndpoints:
    - matchLabels:
        any:label1: value1
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP

```

**Comment by aanm** [comment]
@alonana It works as expected:
```
$ ./main
$ kubectl get cnp -o yaml
apiVersion: v1
items:
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    creationTimestamp: "2022-01-12T11:46:00Z"
    generation: 1
    name: policy1
    namespace: default
    resourceVersion: "29960"
    uid: fa338294-0a5a-4d72-accc-b584ee84c1bd
  spec:
    endpointSelector:
      matchLabels:
        any:label2: value2
    ingress:
    - fromEndpoints:
      - matchLabels:
          any:label1: value1
      toPorts:
      - ports:
        - port: "80"
          protocol: TCP
  status:
    nodes:
      k8s1:
        enforcing: true
        lastUpdated: "2022-01-12T11:46:00Z"
        localPolicyRevision: 2
        ok: true
      k8s2:
        enforcing: true
        lastUpdated: "2022-01-12T11:46:00Z"
        localPolicyRevision: 2
        ok: true
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
$
$ kubectl run nginx --image=nginx --restart=Never -l label2=value2
pod/nginx created
$
$ cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                              IPv6         IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                      
85         Enabled            Disabled          22571      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default   fd00::f666   10.11.0.176   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=default                                                                    
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                             
                                                           k8s:io.kubernetes.pod.namespace=default                                                                     
                                                           k8s:label2=value2 
```
