### ISSUE TITLE
CI / Vagrant VMs: add --help or --info option to contrib/vagrant/start.sh script

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1775]
The Vagrant VM script has a ton of functionality that the user can leverage to customize the VM setup being used. It would be helpful to have some type of informational output for users when running the script so they can see the various options that are configured, as well as some documentation about the script and what it does in the various modes it has.

**Comment by aanm** [comment]
@ianvernon the information provided here is not sufficient? http://cilium.readthedocs.io/en/latest/contributing/#options

Would it help if `--help` or `--info` would print he same text presented in http://cilium.readthedocs.io/en/latest/contributing/#options?

**Comment by ianvernon** [comment]
Contributing docs are sufficient; closing.
