### ISSUE TITLE
Question: Where to find docs for "sidecarless" istio?

### ISSUE THREAD

**Issue by batistein** [cilium/cilium#17764]
I came across this article (seems to be official) https://thenewstack.io/how-ebpf-streamlines-the-service-mesh/
on the topic with sidecarless istio. Unfortunately, I have found no documentation or even any other mention in my research so far. Therefore the issue in the hope that someone can guide me in the right direction.

**Comment by pchaigno** [comment]
For now, Cilium supports only L7 network policies, which are documented at https://docs.cilium.io/en/stable/policy/language/#layer-7-examples. Additional support should come in v1.11 for L7 load balancing, but since v1.11 isn't out yet, it's not documented yet.

**Comment by batistein** [comment]
For all those who come here and wonder the same. Since today there is the [beta program of cilium](https://cilium.io/blog/2021/12/01/cilium-service-mesh-beta). Apparently they were a little too fast with the release of the blog article... 
Now it all makes sense because in the near future there will be a service mesh of cilium that brings these benefits with it!
