### ISSUE TITLE
ip link add eth_dummy type dummy results in connectivity drop

### ISSUE THREAD

**Issue by hwaastad** [cilium/cilium#17767]
## Bug report

**General Information**

- Cilium version
  1.10.5 b0836e8 2021-10-13T16:20:49-07:00 go version go1.16.9 linux/amd64
- Kernel version
  Linux i99998doc06 5.10.75-flatcar SMP Sat Oct 23 06:59:50 -00 2021 x86_64 x86_64 x86_64 GNU/Linu
- Orchestration system version in use
  k8s: v1.20.12
  Rancher 2.6.2
  FlatcarOS 2905.2.6
- Link to relevant artifacts
  Standard helm install. No changes in values
- Generate and upload a sysdump:

  - [Install Cilium CLI](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-the-cilium-cli).
  - Run `cilium sysdump` command:

    ```
    cilium sysdump
    ```

**How to reproduce the issue**

1. Run 
`ip  link add eth_dummy type dummy ` and you loose external traffic from/to node
I've asked question on slack (https://cilium.slack.com/archives/C1MATJ5U5/p1635756609153800)
It's hard to get debuginfo from host but I will try to get vcenter access if needed.

**Comment by pchaigno** [comment]
I'm unable to reproduce. Could you share more detailed reproduction steps (how did you deploy Cilium) and a sysdump?

**Comment by hwaastad** [comment]
Hi,

**Comment by hwaastad** [comment]
Hi,
1. Disable canal as CNI for cluster
2. Install cilium with helm (only change tunnel to geneve)
3. Delete canal daemonset and canal controller deployment
4. Reboot
5. On one of the nodes:
`modprobe dummy && ip link add eth_dummy type dummy`
6. Verify that you cannot ping default gateway from the node

```
    🔍 Collecting Kubernetes nodes
    🔍 Collect Kubernetes nodes
    🔍 Collecting Kubernetes events
    🔍 Collecting Kubernetes namespaces
    🔍 Collecting Kubernetes network policies
    🔍 Collecting Cilium egress NAT policies
    🔍 Collecting Kubernetes services
    🔍 Collecting Cilium identities
    🔍 Collect Kubernetes version
    🔍 Collecting Cilium cluster-wide network policies 
    🔍 Collecting Kubernetes pods
    🔍 Collecting Cilium network policies
    🔍 Collecting Cilium endpoints
    🔍 Collecting Cilium nodes
    🔍 Collecting Cilium local redirect policies
    🔍 Collecting Cilium etcd secret
    🔍 Collecting Kubernetes pods summary
    🔍 Collecting the Cilium configuration
    🔍 Collecting the Cilium daemonset
    🔍 Collecting the Hubble daemonset
    🔍 Collecting the Hubble Relay configuration
    🔍 Collecting the Hubble Relay deployment
    🔍 Collecting the Hubble UI deployment
    🔍 Collecting the Cilium operator deployment
    🔍 Collecting the 'clustermesh-apiserver' deployment
    🔍 Collecting gops stats from Cilium pods
    🔍 Collecting gops stats from Hubble pods
    🔍 Collecting gops stats from Hubble Relay pods
    🔍 Collecting 'cilium-bugtool' output from Cilium pods
    🔍 Collecting logs from Cilium pods
    🔍 Collecting logs from Cilium operator pods
    🔍 Collecting logs from 'clustermesh-apiserver' pods
    🔍 Collecting logs from Hubble pods
    ⚠️ Deployment "hubble-relay" not found in namespace "kube-system" - this is expected if Hubble is not enabled
    ⚠️ Deployment "hubble-ui" not found in namespace "kube-system" - this is expected if Hubble UI is not enabled
    🔍 Collecting logs from Hubble Relay pods
    🔍 Collecting logs from Hubble UI pods
    ⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
    🔍 Collecting platform-specific data
    🔍 Collecting Hubble flows from Cilium pods
    ⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-q9mkk": reading file in tar archive: /var/folders/b6/c474xt6166v6513h_dmk1mh00000gn/T/1669774925/cilium-sysdump-20211103-185338/cilium-bugtool-cilium-q9mkk-20211103-185338/cmd/cat--proc-kallsyms.md: writing file: unexpected EOF
    ⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-8p7l7": reading file in tar archive: /var/folders/b6/c474xt6166v6513h_dmk1mh00000gn/T/1669774925/cilium-sysdump-20211103-185338/cilium-bugtool-cilium-8p7l7-20211103-185338/cmd/state/templates/1c4a2227cc744e80f13086cc0f992ef6f8d42b09875c9f4f74feb44b15e899d3/bpf_lxc.o: writing file: unexpected EOF
    ⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-v4c5q": reading file in tar archive: /var/folders/b6/c474xt6166v6513h_dmk1mh00000gn/T/1669774925/cilium-sysdump-20211103-185338/cilium-bugtool-cilium-v4c5q-20211103-185338/cmd/state/templates/4f7f85fd116b545927de1543a5161f931710d256d2822c896d8dad46575564f3/bpf_lxc.asm: writing file: unexpected EOF
    ⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-phg2j": reading file in tar archive: /var/folders/b6/c474xt6166v6513h_dmk1mh00000gn/T/1669774925/cilium-sysdump-20211103-185338/cilium-bugtool-cilium-phg2j-20211103-185338/cmd/state/templates/ea2d6820279ce1cb22dfe254f49ef65667fb391a9bb706df65a240749d626250/bpf_host.o: writing file: unexpected EOF
    ⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-q9cxq": reading file in tar archive: /var/folders/b6/c474xt6166v6513h_dmk1mh00000gn/T/1669774925/cilium-sysdump-20211103-185338/cilium-bugtool-cilium-q9cxq-20211103-185338/cmd/state/templates/3a139bab157f85bc0344c511625f3fcb9ae2140041affc5491453bbaea5685be/bpf_lxc.asm: writing file: unexpected EOF
    ⚠️ The following tasks failed, the sysdump may be incomplete:
    ⚠️ [10] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: missing apiVersion or kind and cannot assign it; no kind is registered for the type v2alpha1.CiliumEgressNATPolicyList in scheme "pkg/runtime/scheme.go:100"
    ⚠️ [19] Collecting the Hubble Relay configuration: failed to collect the Hubble Relay configuration: configmaps "hubble-relay-config" not found
    ⚠️ Please note that depending on your Cilium version and installation options, this may be expected
    🗳 Compiling sysdump
```

The sysdump, where should I upload the zip?

**Comment by hwaastad** [comment]
> > The sysdump, where should I upload the zip?
> 
> You can attach it to any of the comments here.

OK, I'll see if I'll manage. the zipfile is 43MB and it seems that there is a limit somehow.

**Comment by pchaigno** [comment]
> If you need when down, I'll see if I can get from the container tomorrow

Yes, we'll need when down. One node should be enough :-)

**Comment by hwaastad** [comment]
Hi, here is sysdump from controller when one of the nodes is down.
[cilium-sysdump-20211104-145956.zip](https://github.com/cilium/cilium/files/7475344/cilium-sysdump-20211104-145956.zip)
[cilium-debuginfo-20211104-135813.519+0000-UTC.md](https://github.com/cilium/cilium/files/7475384/cilium-debuginfo-20211104-135813.519%2B0000-UTC.md)

I do not know if I can run sysdump from a disconnected node. I have a debuginfo file from the disconnected node if needed.

**Comment by pchaigno** [comment]
I can't see anything that would suggest this is caused by Cilium. Cilium's BPF programs are not even attached to the native devices, so unlikely to cut access to the external network. A sysdump (or even just a bugtool) from the disconnected node would certainly help confirm this.

**Comment by hwaastad** [comment]
Hi @pchaigno, and thanks for following up. Did another check now, and here is the bugtool output from the node Im adding the link to.
[cilium-bugtool-20211105-165341.412+0000-UTC-1233336352.zip](https://github.com/cilium/cilium/files/7487709/cilium-bugtool-20211105-165341.412%2B0000-UTC-1233336352.zip)

**Comment by pchaigno** [comment]
Thanks! I can confirm Cilium is not interfering with the dummy device or with any of the native devices (no BPF programs attached, no ip routes that should affect the dummy one, and I don't see drop caused by Cilium in iptables). I don't see anything that should prevent connectivity for that matter.

**Comment by hwaastad** [comment]
Hm. OK, thanks for investigating.
Something fishy is definitly going on :-)
I notice that if I ping the down node from another host in the sub net I get:
```
PING 10.210.151.106 (10.210.151.106) 56(84) bytes of data.
From 10.210.151.106: icmp_seq=2 Redirect Host(New nexthop: 10.210.151.106)
From 10.210.151.106: icmp_seq=3 Redirect Host(New nexthop: 10.210.151.106)
From 10.210.151.106: icmp_seq=4 Redirect Host(New nexthop: 10.210.151.106)
From 10.210.151.106: icmp_seq=6 Redirect Host(New nexthop: 10.210.151.106)
From 10.210.151.106: icmp_seq=7 Redirect Host(New nexthop: 10.210.151.106)
^C
--- 10.210.151.106 ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 6103ms
```

1.  route -F, output is hanging. no routes is seen.
2. ip route del default via 10.210.151.1 dev ens32
3. route -F is showing routes connected to cilium
4.  ip route add default via 10.210.151.1 dev ens32
5. route -F, empty and hanging

Go figure :-)

**Comment by pchaigno** [comment]
Glad to know you figured it out!

**Comment by borkmann** [comment]
x-ref: https://github.com/flatcar-linux/Flatcar/issues/372#issuecomment-971436356

Should be fixed via: https://www.flatcar-linux.org/releases/#release-2905.2.1
