### ISSUE TITLE
Add owners of Vagrantfiles and contrib/vagrant to CODEOWNERS

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1778]
The Vagrantfiles and associated scripts at `contrib/vagrant` are vital for the developer workflow / CI. Add a group to the CODEOWNERS file after #1751 is merged.

Group: cilium/vagrant will manage files `Vagrantfile`, `tests/k8s/Vagrantfile`, `contrib/vagrant` . @aanm  and myself will be members of this group.

**Comment by tgraf** [comment]
> Group: cilium/vagrant will manage files Vagrantfile, tests/k8s/Vagrantfile, contrib/vagrant . @aanm and myself will be members of this group.

Created group @cilium/vagrant
