### ISSUE TITLE
CI: L4LB XDP: curl: (28) Failed to connect to 2.2.2.2 port 80: Connection timed out

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#17799]
The L4LB workflow sometimes fail with:
```
curl: (28) Failed to connect to 2.2.2.2 port 80: Connection timed out
```
For example:
- https://github.com/cilium/cilium/runs/4013401187?check_suite_focus=true - 
[cilium-sysdump-out.zip.zip](https://github.com/cilium/cilium/files/7488066/cilium-sysdump-out.zip.zip)
- https://github.com/cilium/cilium/runs/4010036474?check_suite_focus=true - 
[cilium-sysdump-out.zip(1).zip](https://github.com/cilium/cilium/files/7488070/cilium-sysdump-out.zip.1.zip)

/cc @brb

**Comment by brb** [comment]
In both cases (https://github.com/cilium/cilium/runs/4013401187?check_suite_focus=true and https://github.com/cilium/cilium/runs/4010036474?check_suite_focus=true), the test failed for the secondary device which was introduced by https://github.com/cilium/cilium/pull/17655.

**Comment by brb** [comment]
Haven't seen the failure in awhile. Closing for now.
