### ISSUE TITLE
datapath: Redirect from bpf_overlay to egress gw SNAT netdev

### ISSUE THREAD

**Issue by brb** [cilium/cilium#17848]
Currently, when the egress GW node receives a packet from a remote pod which needs to be SNAT-ed to the egress GW IP, the packet is first handled by bpf_overlay@cilium_vxlan. The prog passes the packet to the stack, and eventually it should make to bpf_host@eth0 which does the SNAT.

However, if there is an iptables SNAT rule in the host netns, it might get into the way of egress GW. This is the case for AWS EKS iptables rules:
```
# iptables-save | grep AWS-SNAT-CHAIN
:AWS-SNAT-CHAIN-0 - [0:0]
:AWS-SNAT-CHAIN-1 - [0:0]
-A POSTROUTING -m comment --comment "AWS SNAT CHAIN" -j AWS-SNAT-CHAIN-0
-A AWS-SNAT-CHAIN-0 ! -d 192.168.0.0/16 -m comment --comment "AWS SNAT CHAIN" -j AWS-SNAT-CHAIN-1
-A AWS-SNAT-CHAIN-1 ! -o vlan+ -m comment --comment "AWS, SNAT" -m addrtype ! --dst-type LOCAL -j SNAT --to-source 192.168.188.111 --random-fully
```
The SNAT rule was snatting the packet which made it to bypass the egress GW policy.

To prevent from this happening, we should do the `ctx_redirect()` from bpf_overlay.

**Comment by brb** [comment]
@julianwiedmann @jibi Have we already fixed this?

**Comment by jibi** [comment]
Not yet, we still let the packet in the egress gateway node to go through the stack at the moment

**Comment by julianwiedmann** [comment]
>To prevent from this happening, we should do the ctx_redirect() from bpf_overlay.

Just to note that we might have set up [custom IP routes](https://docs.cilium.io/en/v1.12/gettingstarted/egress-gateway/#compatibility-with-cloud-environments) in the gateway node, so that traffic gets steered to the **correct** external interface. Bypassing those with a straight` bpf_redirect()` would be problematic.

**Comment by jibi** [comment]
Thinking out loud, but would a FIB lookup or `bpf_redirect_neigh()` be of any help here? (Not sure if they take into account also the IP rules)

**Comment by pchaigno** [comment]
Related: https://github.com/cilium/cilium/issues/23504 (potential solution for the above problem of traffic steering, as per Jibi's suggestion).
