### ISSUE TITLE
Enable in-cluster traffic for LoadBalancer whithout enable-node-port

### ISSUE THREAD

**Issue by l1b0k** [cilium/cilium#17853]
## Proposal / RFE

**Is your feature request related to a problem?**
No
**Describe the solution you'd like**
For now the feature is work when `enable-node-port` is enabled.
Add a seperate flag to enable in-cluster traffic for ExternalIP, LoadBalanceIP .

**Comment by pchaigno** [comment]
Could you describe the use case?

**Comment by brb** [comment]
I guess you want to be able to provision LoadBalancer service without creating related NodePort services? You could technically do it even today with: https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation. @l1b0k Could you validate it?

**Comment by l1b0k** [comment]
@pchaigno @brb    thanks for reply .  
Kube-proxy will take over external ip or loadbalance ip for in cluster traffic, user may or may not want the traffic go outside.
If do go outside ,they can benefit form diffient load balancing algorithm.  If not , can solve hairpin issue with lb.
Current implement bind this to `enable-node-port` https://github.com/cilium/cilium/blob/49788abb757aa2713492fcc6b2cd93abe06f7f7f/pkg/k8s/service.go#L431-L434

I prefer to have a diffient flag to control this behave, so i can use this feature whithout enable whole nodePort feature.
