### ISSUE TITLE
Support the wildcard option for nodePort.directRoutingDevice

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#17852]
## Proposal / RFE

**Is your feature request related to a problem?**

We can't specify a fixed device name for nodePort.directRoutingDevice because the device names aren't the same on all Cilium-managed nodes in our environment. Plus we attach k8s internalIP to a dummy interface on each node, so Cilium picks the dummy interface if nodePort.directRoutingDevice is not specified.

**Describe the solution you'd like**

Support the wildcard option for nodePort.directRoutingDevice. Cilium expands direct routing devices and picks the first device.

**Comment by pchaigno** [comment]
We already support the `device=eth+` syntax for the `device` option. We'd just need the same for `nodePort.directRoutingDevice` to address this issue. Thus, marking as `good-first-issue`.

**Comment by sterchelen** [comment]
May I take this issue and implement the `+` wildcard feature as @pchaigno proposes?

**Comment by ysksuzuki** [comment]
Hi @sterchelen

Can I work on this feature? We need this feature to introduce Cilium in our environment.

**Comment by sterchelen** [comment]
Hi @ysksuzuki,

Sure, go ahead!
