### ISSUE TITLE
networking broken by cilium-operator running with multiple replicas when ignoring HA due to API server connectivity issues

### ISSUE THREAD

**Issue by timoreimann** [cilium/cilium#17870]
## Bug report

**General Information**

- Cilium version: 1.10.1
- Kernel version: `Linux pool-tiny-uxbsu 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: Kubernetes 1.21.5

**How to reproduce the issue**

1. Stop the API server.
2. (Re-)Start cilium-operator with a replica count of 2+, expecting it to do leader election.
3. Wait a bit.
4. Start the API server.
5. After some time, connectivity within the network can start to fail, notably by duplicate CIDR allocations as can be seen on the cilium-operator status (`kubectl describe pod`):

```
operator-status:
        error: node has CIDRs allocated ([10.244.14.128/25]) that conflict with requested
          CIDRs [10.244.3.0/25]
```

This seems to be happening because the operator [deliberately ignores errors during API resource discovery](https://github.com/cilium/cilium/blob/c9474acb45b06bdecc7c58a2d6fd3e7bf828f008/pkg/k8s/version/version.go#L299-L318) needed to do leader election. The [fallback discovery](https://github.com/cilium/cilium/blob/c9474acb45b06bdecc7c58a2d6fd3e7bf828f008/pkg/k8s/version/version.go#L231-L240) that is in place is likely to fail as well if the Kubernetes API is inaccessible; as a consequence, multiple operators can start up and do IPAM without coordination, leading to pods not being able to reach certain targets anymore.

The issue does not resolve on its own but requires a restart of the operator with the API server being available.

**Comment by timoreimann** [comment]
I see two possible ways to handle this situation better:

1. Allow cilium-operator to crash and retry. I _think_ there are scenarios where this may be acceptable without leading to a deadlock. Curious to hear people's thoughts, though.
1. Have the operator rediscover leadership capabilities periodically and, once successful, return to running in singleton mode. This seems okay-ish, though I guess it comes with the downside that cilium-operator could run redundantly for some (short?) period of time and thus be able to continue to break network connectivity until single leadership is retained.

Looking forward to thoughts you may have.

**Comment by aanm** [comment]
@timoreimann the minimum k8s support by Cilium in v1.10 is 1.16. The leases are available since k8s 1.14. It is safe to remove the resource discovery for leases and always assume they are available. Will you be able to submit a PR to remove that? Thanks

**Comment by timoreimann** [comment]
@aanm for sure I can give it a try. 👍 

Will report back with a PR once I have some spare time to work on this.

Thanks!

**Comment by timoreimann** [comment]
PR out at #18122.

**Comment by aanm** [comment]
This issue hasn't seen any comment for over two years. Feel free to create a new GitHub issue if you still see the issue persisting with a recent version.
