### ISSUE TITLE
cilium pod relies on `sh` on the host

### ISSUE THREAD

**Issue by smira** [cilium/cilium#17883]
## Bug report

The bug seems to be almost same as #16771.

Cilium v0.10.5, as installed with `cilium install` generates a pod definition with `init` container relying on `sh` on the host filesystem:

```
Init Containers:
  ebpf-mount:
    Container ID:  containerd://bbc7f53c14d4ce0095966e27aedfedeaa488b5a86e53687dbecb321e4f199e87
    Image:         quay.io/cilium/cilium:v1.10.5
    Image ID:      quay.io/cilium/cilium@sha256:0612218e28288db360c63677c09fafa2d17edda4f13867bcabf87056046b33bb
    Port:          <none>
    Host Port:     <none>
    Command:
      nsenter
      --mount=/hostproc/1/ns/mnt
      --
      sh
      -c
      mount | grep "/sys/fs/bpf type bpf" || { echo "Mounting eBPF filesystem..."; mount bpffs /sys/fs/bpf -t bpf; }
    State:          Terminated
      Reason:       Error
      Exit Code:    127
      Started:      Mon, 15 Nov 2021 15:18:43 +0300
      Finished:     Mon, 15 Nov 2021 15:18:43 +0300
```

**General Information**

- Cilium version (run `cilium version`)

```
cilium version    
cilium-cli: v0.9.3 compiled with go1.17.3 on linux/amd64
cilium image (default): v1.10.5
cilium image (stable): v1.10.5
```
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, ...) 1.23.0-alpha.4
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a sysdump:

  - [Install Cilium CLI](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-the-cilium-cli).
  - Run `cilium sysdump` command:

    ```
    cilium sysdump
    ```

**How to reproduce the issue**

1. Install Talos with CNI: `none`.
2. Run `cilium install`
3. `cilium` pods fail to start due to init container error

**Comment by aanm** [comment]
@smira would you be willing to submit a PR to cilium/cilium-cli with a patch similar to https://github.com/cilium/cilium/pull/16815? Thanks

**Comment by smira** [comment]
> @smira would you be willing to submit a PR to cilium/cilium-cli with a patch similar to #16815? Thanks

@aanm I'm not a Cilium user myself, I filed this issue on behalf of the Talos community member. I can certainly try, but it might take some time

**Comment by shivanshu1333** [comment]
I can pick this up,
@aanm can you please assign this to me? :)

**Comment by acabrele** [comment]
I've hit the same issue using rancheros (deploying cilium using the cilium cli to a cluster prepared with rancher gui, having set network.plugin: none).  The guide [here](https://docs.cilium.io/en/v1.10/gettingstarted/k8s-install-rancher-existing-nodes/) suggests using "existing nodes", but if they are rancheros nodes this issues still occurs.  I can't see a way to disable with nodeinit.enabled=false like when using helm deployment.

**Comment by Davincible** [comment]
@shivanshu1333 has there been progress on this issue? I see there was a PR opened but that has been unfortunately closed already

**Comment by bengentil** [comment]
This seems to be fixed already, I don't reproduce with CLI v0.12.11 (cilium v1.12.2).

`cilium install --helm-set-string securityContext.privileged=true` needs to be used because of https://github.com/siderolabs/talos/issues/5948, but this doesn't seems to be related to the issue decribed above.

**Comment by PhilipSchmid** [comment]
This should be fixed in the meantime and can be closed, right? I wasn't able to reproduce it using Cilium 1.14.3 with Talos 1.5.3. I tested both, Cilium Kube-Proxy replacement enabled and disabled.

At the same time `securityContext.privileged=true`, should not be required anymore because of https://github.com/cilium/cilium/pull/21506 (also see Talos' Cilium installation guide where they explicitly configure Linux capabilities: https://www.talos.dev/v1.5/kubernetes-guides/network/deploying-cilium/#method-1-helm-install

**Comment by smira** [comment]
Thanks, this is fixed.
