### ISSUE TITLE
kubectl get ciliumendpoint returns empty columns of INGRESS ENFORCEMENT, EGRESS ENFORCEMENT, VISIBILITY POLICY

### ISSUE THREAD

**Issue by nannancy** [cilium/cilium#17880]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
v1.10.5

command: kubectl get cep -A
output:
```
 $ kubectl get cep -n test
NAME                        ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4              IPV6
deathstar-c74d84667-94gsn   388           3714                                                                         ready            100.124.213.131   
deathstar-c74d84667-dkwdb   1857          3714                                                                         ready            100.124.236.142   
mediabot                    3691          17733                                                                        ready            100.124.252.187   
tiefighter                  613           16586                                                                        ready            100.124.234.76    
xwing                       2515          17533                                                                        ready            100.124.248.237   
```

**Comment by pchaigno** [comment]
For context, see https://github.com/cilium/cilium/issues/11212#issuecomment-621954889:
> Note that by default, Cilium runs with `--endpoint-status` disabled. To allow these columns to populate, users can run with `--endpoint-status=policy`.
> 
> We should figure out how to represent this more clearly for users though.

When the option is disabled, maybe we could set the value of `INGRESS ENFORCEMENT` to something like `Endpoint status disabled`. (I'm guessing we can't simply control whether those columns are visible in the kubectl output.)
/cc @joestringer

**Comment by gandro** [comment]
> When the option is disabled, maybe we could set the value of `INGRESS ENFORCEMENT` to something like `Endpoint status disabled`. (I'm guessing we can't simply control whether those columns are visible in the kubectl output.)

The output is controlled via the CRD schema:
https://github.com/cilium/cilium/blob/f45630ed01a52d7ede0b767bfb1dfdd9bf889092/pkg/k8s/apis/cilium.io/v2/types.go#L25-L28

There might be away to make the jsonpath more conditional to print something like `unknown` or `status disabled`, but likely more than just a one-line fix.

**Comment by joestringer** [comment]
:+1: I'd be in favour of rendering this better when it's disabled, or even re-enabling these options by default for small clusters (ie unless you explicitly state that you're trying to target scale). I think the default right now assumes that you're running at high scale where disabling these checks is necessary, but most users who hit this issue could have avoided it if Cilium just turned these status reports on by default.

**Comment by aanm** [comment]
I would suggest to hardcode "Status N.A." on all values for the fields that are disabled.
