### ISSUE TITLE
Install cilium v1.10.5 unable to retrieve cilium status: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)

### ISSUE THREAD

**Issue by chary1112004** [cilium/cilium#17882]
## Bug report

**General Information**

- Cilium version (run `cilium version`): v1.10.5
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, ...) Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a sysdump: 
[cilium-sysdump-20211115-102831.zip](https://github.com/cilium/cilium/files/7537928/cilium-sysdump-20211115-102831.zip)
  - [Install Cilium CLI](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-the-cilium-cli).
  - Run `cilium sysdump` command:

    ```
    cilium sysdump
    ```

**How to reproduce the issue**

1. In AWS EKS v1.18, install cilium using helm
$ helm repo add cilium https://helm.cilium.io/
$ helm install cilium cilium/cilium --version 1.10.5 --namespace kube-system

2. Check status
$ cilium status
![image](https://user-images.githubusercontent.com/76929085/141766516-26572060-a90b-443d-8215-0222a6652da7.png)

3. I am trying to add clusterrolebinding 
$ kubectl create clusterrolebinding apiserver-kubelet-admin --user=kube-apiserver-kubelet-client --clusterrole=system:kubelet-api-admin

However issue does not appear.

> DaemonSet         cilium             Desired: 2, Unavailable: 2/2
Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Containers:       cilium             Running: 2
                  cilium-operator    Running: 2
Cluster Pods:     2/2 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.10.5@sha256:0612218e28288db360c63677c09fafa2d17edda4f13867bcabf87056046b33bb: 2
                  cilium-operator    quay.io/cilium/operator-generic:v1.10.5@sha256:2d2f730f219d489ff0702923bf24c0002cd93eb4b47ba344375566202f56d972: 2
Errors:           cilium             cilium          2 pods of DaemonSet cilium are not ready
                  cilium             cilium-2cl77    unable to retrieve cilium status: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)
                  cilium             cilium-gzk7t    unable to retrieve cilium status: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)

**Comment by pchaigno** [comment]
>  $ helm install cilium cilium/cilium --version 1.10.5 --namespace kube-system

Are you still able to reproduce if you follow the installations steps documented for AWS/EKS (see the tab with same name) at https://docs.cilium.io/en/latest/gettingstarted/k8s-install-helm/?

**Comment by chary1112004** [comment]
If I follow step documented for AWS/EKS then it will show another issue **controller bpf-map-sync-cilium_ipcache is failing**
![cilium-install-eks](https://user-images.githubusercontent.com/76929085/141771151-81b3eedf-b951-485b-a95a-f8449b3d3143.png)

And even after that it is showing test result is passed
![cilium-install-eks-test-activity](https://user-images.githubusercontent.com/76929085/141771311-1f401153-9634-4cb5-bb44-10159feb43f1.png)

**Comment by pchaigno** [comment]
> If I follow step documented for AWS/EKS then it will show another issue controller bpf-map-sync-cilium_ipcache is failing

That's https://github.com/cilium/cilium/issues/17111. It shouldn't impact connectivity.

**Comment by chary1112004** [comment]
Thanks. Do we have official note about this one not impact to work of cilium?

**Comment by chary1112004** [comment]
@pchaigno 

I have just installed cilium v1.10.5 and upgraded AWS EKS to v1.20.0 then it really works without error

$ kubectl -n kube-system delete daemonset aws-node

$ helm install cilium cilium/cilium --version 1.10.5 \
  --namespace kube-system \
  --set eni.enabled=true \
  --set ipam.mode=eni \
  --set egressMasqueradeInterfaces=eth0 \
  --set tunnel=disabled \
  --set nodeinit.enabled=true

$ helm upgrade cilium cilium/cilium --version 1.10.5 \
   --namespace kube-system \
   --reuse-values \
   --set hubble.relay.enabled=true \
   --set hubble.ui.enabled=true

$ cilium status
![image](https://user-images.githubusercontent.com/76929085/141779193-c797a873-6491-469b-8312-35834fe3ea9b.png)

$ cilium connectivity test -v
![image](https://user-images.githubusercontent.com/76929085/141779715-724b35e6-da13-48c1-ad06-5599a843409b.png)

**Comment by pchaigno** [comment]
Great to know it works for you now!
