### ISSUE TITLE
Discuss NEWS update process

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1789]
How do we keep the `NEWS.rst` updated throughout a development cycle without creating merge conflicts for every PR? Ideally, it also contains a simple process to keep the NEWS file up to date for stable backports.

@cilium/team: Please provide your thoughts

**Comment by rlenglet** [comment]
Not every change should make it into NEWS. The NEWS is currently too detailed IMHO. We should reduce the rate of changes, which should reduce the rate of merge conflicts. Cf. how this file is defined in the [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/NEWS-File.html#NEWS-File):

> [...] the package should have a file named NEWS which contains a list of *user-visible changes worth mentioning*. [...]

I suggest that we start by deciding criteria for what makes a change _worth mentioning_, and enforcing that in code reviews.

**Comment by borkmann** [comment]
I would suggest we should have a label `need news update` that could be added to issues and/or PRs. Once they are closed, we could look up all closed issues with this label for a given release milestone for the NEWS update that the one doing the release could write up? It would help identifying all relevant issues/PRs that have been solved during that period and dealing with merge conflicts. Wdyt?

**Comment by rlenglet** [comment]
GNU projects require that the NEWS be updated in the same patch series as any significant user-visible change. So a branch could be released at any time without any extra work. NEWS is always up-to-date. I would prefer to follow that approach too.

**Comment by tgraf** [comment]
> I would suggest we should have a label need news update that could be added to issues and/or PRs. Once they are closed, we could look up all closed issues with this label for a given release milestone for the NEWS update that the one doing the release could write up? It would help identifying all relevant issues/PRs that have been solved during that period and dealing with merge conflicts. Wdyt?

It takes hours to write the NEWS file because the context has to be looked up every time. I want to find a way to write the NEWS blob at PR time.

> GNU projects require that the NEWS be updated in the same patch series as any significant user-visible change. So a branch could be released at any time without any extra work. NEWS is always up-to-date. I would prefer to follow that approach too.

We have tried this approach and it resulted in massive merge challenges because of the conflicts. I agree that the NEWS update must be bundled with the PR somehow but we need to find a way to not touch a single file.

I see two options:
 - Add a special marker in the commit message which indicates that this now contains a NEWS update, e.g.

   Release-note: (Kubernetes)
   This is the release note description

- add `.news-<#pr>` files which get accumulated automatically by a release script.

**Comment by borkmann** [comment]
Another option could be to use the GH pull request message with a Release-note: and tag the PR with `release note` label. Meaning, the one that opens the PR is still required to write the related release note for it. For single commits, GH automatically pulls in the actual commit message and for sets one is required to write a summary right now, but we could set the workflow that once such label is set by the one who opens the PR, he also has to place the message there for both cases that goes later into NEWS file.

From the two options mentioned earlier, my personal preference would probably be to have it in the commit log itself then, although it may duplicate information a bit but wouldn't add churn to the source tree itself.

**Comment by rlenglet** [comment]
If we used a Release-note: label in commit messages, how would we deal with commits that are reverted? They would still remain in the git history with their Release-notes: labels in the commit message. How do we deal with commits that are backported? How will the NEWS file get updated on all branches where the commit is committed / backported?

**Comment by aanm** [comment]
I vote for a directory that contains the `news-<#pr>` files for significant PRs. These files are created by the PR author and on each release those files are merged and cleaned up.

**Comment by borkmann** [comment]
@rlenglet Process with backports is essentially the same when cherry-picking from master, but agree on the reverts, this needs additional indication somewhere which is kind of annoying as it would require to go through the log to verify there are no reverts for such tagged commits. Not sure either of the two options are too optimal.

I'd go for earlier mentioned GH pull request message to add a proper high-level description as part of the workflow, so this would be needed for all PRs, also those that don't go into release notes. And the ones that should be part it would get a `release note` label. This would allow for i) code reviewers from that area to quickly get a high level description of what the PR is doing, ii) easy filtering of PRs based on milestone and labels from UI, iii) integrating that workflow in general in GH and also that could be scripted potentially as there's a GH REST API to fetch PRs. I think it could also make the workflow easier for external contributors as one wouldn't need to tell whether a `news-<#pr>` file is needed or not. iiuc, the process of backports will get distributed as well, which will automatically result in multiple PRs instead of a single one, thus would fit as well.

**Comment by ianvernon** [comment]
> I vote for a directory that contains the news-<#pr> files for significant PRs. These files are created by the PR author and on each release those files are merged and cleaned up.

+1. I like this because it resolves the merge conflict issue. We can have a folder for each each version, e.g. `news/0.11`, `news/0.12` etc. and generate the `NEWS` file based on the `VERSION` at the root of the repo.

**Comment by nebril** [comment]
+1 for separate news directory.

**Comment by tgraf** [comment]
> +1. I like this because it resolves the merge conflict issue. We can have a folder for each each version, e.g. news/0.11, news/0.12 etc. and generate the NEWS file based on the VERSION at the root of the repo.

OK, I'm fine with news files. It also has the benefit that we can have inline comments to review NEWS changes.

I don't think we need separate directories necessarily, we can have a release script which:
1. collects news files and prepares the `NEWS` file
2. schedules all individual news snippet files for removal
3. Bumps the `VERSION` file
4. Leaves everything in scheduled so whoever prepares only has to review and then commit & push.

**Comment by aanm** [comment]
I've talked with @borkmann. We will still have one problem, after merging all news files, how do we split them by area (k8s / CLI / daemon / bug-fixes)?

**Comment by tgraf** [comment]
> I've talked with @borkmann. We will still have one problem, after merging all news files, how do we split them by area (k8s / CLI / daemon / bug-fixes)?

I propose something simple such as first line of the file representing the category. That said, fixing up the categories is something that can be done very easily when preparing the release. This only takes minutes. It's just copy paste in an editor and amend the commit.

**Comment by aanm** [comment]
FYI, this is how k8s does it: https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#write-release-notes-if-needed

**Comment by borkmann** [comment]
Their script to crawl GH PRs and generate release notes is here as well: https://github.com/kubernetes/release/blob/master/relnotes

**Comment by tgraf** [comment]
> Their script to crawl GH PRs and generate release notes is here as well: https://github.com/kubernetes/release/blob/master/relnotes

I'm sold on using this as-is. Any objections?

**Comment by ianvernon** [comment]
> I'm sold on using this as-is. Any objections?

I'm all for this; no sense in reinventing the wheel.

**Comment by rlenglet** [comment]
LGTM.
