### ISSUE TITLE
Cilium TCP: too many orphaned sockets

### ISSUE THREAD

**Issue by bazzuka** [cilium/cilium#17893]
**General Information**

- Cilium version 1.10.5
- Kernel version (run `uname -a`) Linux 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...). v1.20.11
```
          + <<-EOT
                "autoDirectNodeRoutes": false
                "bpf":
                  "clockProbe": true
                  "hostRouting": true
                  "masquerade": true
                  "monitorAggregation": "none"
                  "preallocateMaps": true
                  "waitForMount": true
                "cluster":
                  "name": "feu"
                "debug":
                  "enabled": false
                "enableIPv4Masquerade": true
                "enableIPv6Masquerade": true
                "hostPort":
                  "enabled": true
                "hostServices":
                  "enabled": true
                "hubble":
                  "enabled": false
                  "listenAddress": ":4244"
                  "metrics":
                    "enabled":
                    - "drop"
                  "relay":
                    "enabled": false
                  "ui":
                    "enabled": false
                "ipMasqAgent":
                  "enabled": true
                "ipam":
                  "mode": "kubernetes"
                "ipv4":
                  "enabled": true
                "k8s":
                  "requireIPv4PodCIDR": true
                "kubeProxyReplacement": "partial"
                "localRedirectPolicy": true
                "nodePort":
                  "enableHealthCheck": true
                  "enabled": true
                  "mode": "dsr"
                "nodeinit":
                  "enabled": true
                  "priorityClassName": "system-cluster-critical"
                "operator":
                  "numReplicas": 2
                  "priorityClassName": "system-cluster-critical"
                  "prometheus":
                    "enabled": true
                  "rollOutPods": true
                "pprof":
                  "enabled": true
                "priorityClassName": "system-cluster-critical"
                "prometheus":
                  "enabled": true
                "tunnel": "vxlan"
            EOT,
```

I got a new problem with network cards. Cards are flapping and I am seeing ```[235611.755637] TCP: too many orphaned sockets ``` and TCP allocation raising up to 250k (normal 30-40k).
I have disabled BPF Host routing and disabled TCP offloading and checksumming. Seems like now is better but the issue happens from time to time. I need a server reboot because the server disappears from the internet.
The average load is 500-800 Mbit/s.
```
c3:00.0 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)

~ # lshw -class network
  *-network
       description: Ethernet interface
       physical id: 0
       bus info: pci@0000:c3:00.0
       logical name: enp195s0
       version: 01
       serial: d4:5d:64:bf:0a:50
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=igb driverversion=5.11.0-38-generic duplex=full firmware=1.63, 0x800009fa ip=157.90.90.249 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
       resources: irq:110 memory:b4400000-b441ffff ioport:e000(size=32) memory:b4460000-b4463fff memory:b4440000-b445ffff memory:b4420000-b443ffff
```

Thanks in advance.

**Comment by aditighag** [comment]
>[235611.755637] TCP: too many orphaned sockets

Have you looked at these socket connections using `netstat`/`ss`? What are the destination port numbers? Maybe there are a large number of connections in the `TIME_WAIT` state?

**Comment by bazzuka** [comment]
I send sysdump to @aanm in slack
<img width="1668" alt="Screenshot 2021-11-15 at 21 06 09" src="https://user-images.githubusercontent.com/15695060/141839693-f395ec3f-05f6-4b20-92fa-81b01ec51378.png">

worker17 in sysdump. 11:40 UTC

**Comment by bazzuka** [comment]
Normal situation for this server
<img width="810" alt="Screenshot 2021-11-15 at 21 11 21" src="https://user-images.githubusercontent.com/15695060/141840171-19370bb1-0e4f-4553-b25d-4ae5807a8155.png">
<img width="1643" alt="Screenshot 2021-11-15 at 21 10 31" src="https://user-images.githubusercontent.com/15695060/141840180-595fc818-6c89-4869-baf6-6352d82bc424.png">

**Comment by bazzuka** [comment]
Also masters requires periodic reboots. IRQ 100 percent on 4 cpu cores

**Comment by borkmann** [comment]
> I have disabled BPF Host routing and disabled TCP offloading and checksumming. Seems like now is better but the issue happens from time to time.

From the agent's log where you have the `TCP: too many orphaned sockets` flood, Cilium's status says `Host Routing:           Legacy`, so either way the BPF Host routing was not enabled in the first place due to missing kernel requirement.

What's your current `/proc/sys/net/ipv4/tcp_max_orphans`? Did you try to bump it? Do you happen to know what's causing the orphans? Occasional large spikes in traffic?

(e.g. https://tor-relays.torproject.narkive.com/k296Au89/syslog-kernel-tcp-too-many-orphaned-sockets)

**Comment by borkmann** [comment]
One other thought: did you try to customise the BPF map sizing?

Your `bpf-map-dynamic-size-ratio` is at `0.0025` (seen in `cilium status --verbose`). If you'd for example double it to `0.005`, are you still running into the issue? (Note that changing this setting is disruptive to ongoing connections.)

The agent log seems to have a lot of `Deleted orphan SNAT entries from map` log entries which might indicate a too small sized CT map.

(https://docs.cilium.io/en/stable/concepts/ebpf/maps/#bpf-map-limitations)

**Comment by bazzuka** [comment]
@borkmann hi, thanks for your comments but we have removed cilium from our stack. There are really huge losses for us. Cilium has perfect idea but implementation bring us unexpected downtime. I think you can close the issue.

**Comment by qmonnet** [comment]
We're sorry to hear that :/. Thanks for letting us know. I'm closing the issue. Anyone hitting this again, do not hesitate to comment/reopen.
