### ISSUE TITLE
Bugtool for dumping IPv6 routes is broken

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#17896]
Found in https://github.com/cilium/cilium/issues/17895:

```
$ cat bugtool-cilium-h5t8f/cmd/ip--6-route-show-\[116-97-98-108-101-32-50-48-48*
Error: inet6 prefix is expected rather than "[116".
> Error while running 'ip -6 route show [116 97 98 108 101 32 50 48 48 52]':  exit status 1

Error: inet6 prefix is expected rather than "[116".
> Error while running 'ip -6 route show [116 97 98 108 101 32 50 48 48 53]':  exit status 1

Error: inet6 prefix is expected rather than "[116".
> Error while running 'ip -6 route show [116 97 98 108 101 32 50 48 48]':  exit status 1

```

These lines should not be using the `%v` formatter but should instead format the IPv6 addresses in a standard format that `ip -6 route ...` can understand:

https://github.com/cilium/cilium/blob/789eef0d148d0aa590d2a1b2da7fd69da6dafc47/bugtool/cmd/configuration.go#L262

Tasks:
* [ ] Fix IPv6 route debug gathering commands
* [ ] Grep around the bugtool for other `%v` formatting primitives to check that there are no other similar problems for other commands

**Comment by shivanshu1333** [comment]
I'd like to work on it
/assign

**Comment by shivanshu1333** [comment]
@joestringer can you please assign the issue to me :)

**Comment by tklauser** [comment]
This issue is caused by #17546, namely commit 8bcc4e5dd830.

I've also noticed this issue when trying to debug something locally and came up with #18059 which fixes this issue and another instance where that commit's change from `string` to `[]byte` potentially causes problem.
