### ISSUE TITLE
CiliumEndpointSlice renders CiliumEgressNATPolicies ineffective

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#17921]
Enabling CiliumEndpointSlice breaks the egress gateway feature by making all egress NAT policies ineffective.

### Reproduction

This bug can be reproduced locally with the following command because CiliumEndpointSlices are enabled on K8s >=1.21 and ginkgo is running 1.22 by default.
```
NETNEXT=true KUBEPROXY=0 K8S_NODES=3 NO_CILIUM_ON_NODE=k8s3 ginkgo -v --focus="K8sEgressGatewayTest tunnel disabled with endpointRoutes enabled" --tags=integration_tests -- --cilium.provision=true --cilium.holdEnvironment=true -cilium.testScope="k8s" -cilium.skipLogs=true
```
The test fails with the following because packets are not sent to the egress gateway or SNATed to the egress IP:
```
[Expected
    <string>: 
    
    Hostname: k8s3
    
    Pod Information:
    	-no pod information available-
    
    Server values:
    	server_version=nginx: 1.13.3 - lua: 10008
    
    Request Information:
    	client_address=::ffff:192.168.56.11
    	method=GET
    	real path=/
    	query=
    	request_version=1.1
    	request_scheme=http
    	request_uri=http://192.168.56.13:80/
    
    Request Headers:
    	accept=*/*
    	host=192.168.56.13
    	user-agent=curl/7.61.1
    
    Request Body:
    	-no body in request-
    
    time-> DNS: '0.000019(192.168.56.13)', Connect: '0.000584',Transfer '0.001304', total '0.001346'
to match regular expression
    <string>: client_address=::ffff:192.168.56.100
    ]
```

### Initial Debugging

Checking the egress gateway BPF map, we can see this happens because the map are empty:
```
$ ks exec cilium-bt9v6 -- cilium bpf egress list
No entries found.

Note that for Linux kernel versions between 4.11 and 4.15 inclusive, the native
LPM map type used for implementing this feature does not provide the ability to
walk / dump the entries, so on these kernel versions this tool will never
return any entries, even if entries exist in the map.
```
Further debugging showed that `K8sWatcher.endpointUpdated` is receiving endpoints without any labels. They therefore don't match any egress NAT policy and the BPF maps stay empty.

### Misc.

Other features relying on endpoint labels might be affected as well.

cc @Weil0ng @anfernee

**Comment by Weil0ng** [comment]
I think this is duplicate of https://github.com/cilium/cilium/issues/17669.

**Comment by pchaigno** [comment]
Oh, right! I had completely forgot about that one :facepalm: I've flagged it as `bug`. Thanks @Weil0ng!
