### ISSUE TITLE
Improve logging when failing to create a veth device

### ISSUE THREAD

**Issue by bbck** [cilium/cilium#17925]
## Proposal / RFE

**Is your feature request related to a problem?**

The base Ubuntu distribution for Raspberry Pi's does not ship with the veth kernel module. Trying to install cilium results in it failing with only a "operation not supported" message.

Thread in Slack: https://cilium.slack.com/archives/C53TG4J4R/p1637010685276600

**Describe the solution you'd like**

1. Cilium should log the failure to create the veth device.
2. The system requirements documentation should make mention of the veth kernel module.

**Comment by pchaigno** [comment]
The unhelpful messages are:
```
level=error msg="Error while initializing daemon" error="operation not supported" subsys=daemon
level=fatal msg="Error while creating daemon" error="operation not supported" subsys=daemon
```
To improve those, we could add some context to the places where we return errors, at https://github.com/cilium/cilium/blob/c78195592e65349c72724784c834cd8cd5b20218/pkg/datapath/loader/base.go#L403-L405 or even inside `setupBaseDevice()`.
