### ISSUE TITLE
Question: traffic split support?

### ISSUE THREAD

**Issue by fredwangwang** [cilium/cilium#17953]
Hi!

I am looking at possibility of using cilium directly without more expensive mesh. Cilium covers transparent encryption using IPSec/Wireguard and enforce network policies very well, however another aspect I am interested in is traffic splitting.

Mesh like Istio ([traffic management](https://istio.io/latest/docs/concepts/traffic-management/)) and Consul ([service splitter](https://www.consul.io/docs/connect/config-entries/service-splitter)) both support percentage based traffic splitting. 

Curious if cilium supports traffic split right now or would that be something to consider in near future/at all?

**Comment by brb** [comment]
cc @jrajahalme

**Comment by jrajahalme** [comment]
We are currently working on L7 LB features. The first case we'll target is vanilla k8s Ingress (so no % splitting), but will target this use case soon after.

**Comment by fredwangwang** [comment]
Thanks @jrajahalme! Since this is more of a question and sounds like will see the feature coming out _soon_, going to close the issue here but keeping an eye on the releases 😄
