### ISSUE TITLE
bpf: sockmap "gift" skb to xmit path

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#1797]
Currently we do a full sendmsg call from sockmap redirect egress. This involves rebuilding the skb and doing another memcpy. However, because we are already in the kernel there is no reason to do the memcpy. This issue is to "gift" the skb to the xmit path of the new socket. This requires doing proper memory accounting.

**Comment by mestery** [comment]
Hi @jrfastab, is this fixed upstream yet? I cannot find any issues here. What I notice when trying to use sockmap to offload sockets in my custom SNI proxy is exactly the behavior which is noted here and also in this one [1] by @SPYFF.

[1] https://github.com/Ysurac/openmptcprouter/issues/285

**Comment by jrfastab** [comment]
I have this and a couple other improvements on my stack at the moment. The idea is to land them for kernel releases 5.10/5.11. The other major improvement is to drop the worker thread which will currently cause some latency spikes if its not scheduled quickly. The "fix" here is to do a run-to-completion model so we keep latency down.

**Comment by mestery** [comment]
Excellent, I really appreciate the quick response! If you have anything available for testing, let me know, I'd love to try these out and see if they improve my situation using sockmap offload for my proxy! :)

**Comment by mestery** [comment]
@jrfastab apologies, but I wasn't clear where else to ask, so asking here. Is there a git tree somewhere with the patches to address this by chance? Can you point me at it if so please? I would love to try them out! Thank you for the help!

**Comment by mestery** [comment]
Just checking in here to see if there is a link to a proposed fix or anything to try out before it lands upstream. Thanks for all your hard work @jrfastab! :)

**Comment by okanaganrusty** [comment]
Bump, @mestery @jrfastab.  I am just inquiring if there is any movement forward on this.  

Thanks in advance.
