### ISSUE TITLE
verification error for Cilium v1.11.0-rc3  on 4.19.0-18-cloud-amd64

### ISSUE THREAD

**Issue by kkourt** [cilium/cilium#18047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Default install with cilium-cli results in verification errors.

### Cilium Version

1.11.0-rc3

### Kernel Version

 4.19.0-18-cloud-amd64

### Kubernetes Version

# k3s kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

> level=warning msg="BPF program is too large. Processed 131073 insn" subsys=datapath-loader

[full agent log](https://github.com/cilium/cilium/files/7619814/cilium-f6pxq.log)

There is an existing issue for the same kernel https://github.com/cilium/cilium/issues/17647, but since this is on the default install of 1.11, I thought it might be worth another issue.

**Comment by pchaigno** [comment]
> 4.19.0-18-cloud-amd64

Where is that kernel coming from? I thought https://github.com/cilium/cilium/issues/17647 was introduced by a verifier change between 4.19.190 and 4.19.200 :-/

**Comment by kkourt** [comment]
> > 4.19.0-18-cloud-amd64
> 
> Where is that kernel coming from? I thought #17647 was introduced by a verifier change between 4.19.190 and 4.19.200 :-/

GCP (right after booting a new VM).

**Comment by kkourt** [comment]
Let's track this in the existing issue.
