### ISSUE TITLE
fail install cilium

### ISSUE THREAD

**Issue by mxdblcf** [cilium/cilium#18078]
If my development environment is a virtual machine and my network card is virtual. Can I install the cilium ?

**Comment by mxdblcf** [comment]
why the cilium show install successful ?
But run " cilium connectivity test " show fail.
Where should I look for errors?

**Comment by pchaigno** [comment]
> If my development environment is a virtual machine and my network card is virtual. Can I install the cilium ?

Yes, that's how we test Cilium in CI.

Please fill out the issue template properly and we'll be happy to help.
