### ISSUE TITLE
Make ginkgo test declarations more consistent

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#18085]
Recently I've been trying to quarantine ginkgo tests. Given the way that we structure the test definitions with nested `Context` and `It` statements, with long files it can be difficult to locate the specific test that's failing based on the name, for instance:

* CI reports flakiness in `Suite-k8s-1.22.K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with secondary NodePort device`.
* If I search for the whole test name (even without the `Suite-k8s-1.22.` part), no matches will come up because the test name is split across multiple lines.
* If I search for `Tests with secondary NodePort device`, two different matches show up from different tests. How do I know which one is the test that is regularly failing?
  ```
  $ git grep  "Tests with secondary NodePort device"
  test/k8sT/Services.go:                                  }, "Tests with secondary NodePort device", func() {
  test/k8sT/Services.go:                          }, "Tests with secondary NodePort device", func() {
  ```
* In theory, if I can grep for `Context`, `It` statements, then I could at least scan down the set of strings used to declare the tests and figure it out by scanning through the test structure, eg:
  ```
  $ git grep -e Context -e It test/k8sT/Services.go
  ...
  test/k8sT/Services.go:          SkipContextIf(helpers.DoesNotRunWithKubeProxyReplacement, "Tests NodePort BPF",
  test/k8sT/Services.go:                          Context("Tests with vxlan", func() {
  test/k8sT/Services.go:                                  It("Tests NodePort", func() {
  ```
* If I grep for `Context`, `It` statements and search the output for `Tests with secondary NodePort device`, there are no matches because the test name is not guaranteed to occur on the same line as the `It` or `Context` statement.
  ```
  $ git grep -e Context -e It test/k8sT/Services.go | grep "Tests with secondary NodePort device"
  ```
* Looking at the surrounding declaration, here is the reason why they don't show up on the same line:
  ```
  $ git grep -B 5  "Tests with secondary NodePort device"
  test/k8sT/Services.go-                                  SkipItIf(func() bool {
  test/k8sT/Services.go-                                          // Quarantine when running with the third node as it's
  test/k8sT/Services.go-                                          // flaky. See #12511.
  test/k8sT/Services.go-                                          return helpers.GetCurrentIntegration() != "" ||
  test/k8sT/Services.go-                                                  (helpers.SkipQuarantined() && helpers.ExistNodeWithoutCilium())
  test/k8sT/Services.go:                                  }, "Tests with secondary NodePort device", func() {
  --
  test/k8sT/Services.go-                          SkipItIf(func() bool {
  test/k8sT/Services.go-                                  // Quarantine when running with the third node as it's
  test/k8sT/Services.go-                                  // flaky. See #12511.
  test/k8sT/Services.go-                                  // It's also flaky for IPv6 traffic, see #18072
  test/k8sT/Services.go-                                  return helpers.SkipQuarantined()
  test/k8sT/Services.go:                          }, "Tests with secondary NodePort device", func() {
  ```

In theory perhaps I can learn better $EDITOR foo and find a shortcut to jump to the next outer function declaration and iteratively run this for each of the inner test statements so that I can understand the differences between the two `It` declarations. However, I would also like to make it easier to find and quarantine individual tests from a simple command like the newly-introduced `contrib/scripts/quarantine.sh`. The simplest version of this script looks for the `It` / `Context` call and the test name on the same line, and then injects the quarantine snippet (typcially means swapping `It(` -> `SkipItIf(helpers.SkipQuarantined(),`). However, this does not work on multi-line declarations like the above.

The motivation behind the quarantine script is to make it very easy to quarantine tests, however the current structure of the test declarations makes this (a) difficult for a script to automate and (b) difficult for a human to manually quarantine the correct test.

I wonder if there are ideas about how we could make this easier to handle. One simple step could be to encourage structuring the tests through table-driven testing or at least use unique strings for each `Context` / `It` statement. This would solve the manual quarantining problem above but still makes it difficult for the script to handle it. Maybe this is a reasonable enough fix. Certainly a more complicated way would be to write a much smarter quarantine program which scans the Go code structure and understands where the function declarations and strings are, and is able to walk up/down the AST to find the correct function to tweak. This seems more complicated than necessary.

Arguably depending on our long term intentions around how we maintain the testsuite, it may also not make sense to improve on this (for instance, if we intend to move away from Ginkgo). However, I think that the above problem is a bit of a microcosm into the (lack of) readability of the tests for anyone who's unfamiliar with them. While this issue is posted from the consideration of how to easily quarantine tests, it's also trying to poke at the question of how we structure the tests to make them approachable to both humans and scripts to make it easier to make changes. These concerns may be applicable beyond the scope of the ginkgo framework we currently use for the majority of end-to-end testing.

**Comment by joestringer** [comment]
So far from a scripting perspective, I've just assumed that it's "good enough" to not handle the multi-line declarations like above, and only have the script work where the test name and test function declaration are on the same line. And maybe that's the simplest answer: either the script doesn't always work or we could encourage always declaring the test name on the same line as the `It` / `Context`.

**Comment by joestringer** [comment]
One other note, let's say I try to use `ginkgo .. -dryRun` to locate the test. This doesn't seem to work today, even though the test is clearly somewhere in the suite:

```
$ ginkgo -tags=integration_tests -dryRun -- -cilium.runQuarantined  | grep secondary
$
```

In the raw output of the above command, I see the following, so maybe the test is still excluded from the dry run somehow?

```
Ran 408 of 418 Specs in 0.008 seconds
SUCCESS! -- 0 Passed | 0 Failed | 10 Pending | 0 Skipped
```

**Comment by joestringer** [comment]
In the end I can expand the initial grep terms to get the answer:

```
$ grep -e Context -e It -e "Tests with secondary NodePort device" test/k8sT/Services.go 
...
                SkipContextIf(helpers.DoesNotRunWithKubeProxyReplacement, "Tests NodePort BPF",
                                Context("Tests with vxlan", func() {
                                        It("Tests NodePort", func() {
                                        It("Tests NodePort with externalTrafficPolicy=Local", func() {
                                        It("Tests NodePort with sessionAffinity", func() {
                                        SkipItIf(helpers.DoesNotExistNodeWithoutCilium, "Tests NodePort with sessionAffinity from outside", func() {
                                        It("Tests HealthCheckNodePort", func() {
                                        It("Tests that binding to NodePort port fails", func() {
                                        It("Tests HostPort", func() {
                                        SkipItIf(helpers.DoesNotExistNodeWithoutCilium, "Tests externalIPs", func() {
                                        SkipContextIf(helpers.RunsOnGKE, "With host policy", func() {
                                                It("Tests NodePort", func() {
                                        Context("with L7 policy", func() {
                                                It("Tests NodePort with L7 Policy", func() {
                                        Context("Tests NodePort with Maglev", func() {
                                                It("Tests NodePort", func() {
                                                SkipItIf(helpers.DoesNotExistNodeWithoutCilium,
                                        SkipItIf(func() bool {
                                        }, "Tests with secondary NodePort device", func() {
                                SkipContextIf(helpers.SkipQuarantined, "Tests with direct routing", func() {
                                        It("Tests NodePort", func() {
                                        It("Tests NodePort with externalTrafficPolicy=Local", func() {
                                        It("Tests NodePort with sessionAffinity", func() {
                                        SkipItIf(helpers.DoesNotExistNodeWithoutCilium, "Tests NodePort with sessionAffinity from outside", func() {
                                        It("Tests HealthCheckNodePort", func() {
                                        It("Tests that binding to NodePort port fails", func() {
                                        It("Tests HostPort", func() {
                                        SkipItIf(helpers.DoesNotExistNodeWithoutCilium, "Tests externalIPs", func() {
                                        SkipContextIf(helpers.RunsOnGKE, "With host policy", func() {
                                                It("Tests NodePort", func() {
                                        Context("with L7 policy", func() {
                                                It("Tests NodePort with L7 Policy", func() {
                                        Context("Tests NodePort with Maglev", func() {
                                                It("Tests NodePort", func() {
                                                SkipItIf(helpers.DoesNotExistNodeWithoutCilium,
                                        SkipItIf(helpers.DoesNotExistNodeWithoutCilium, "Tests GH#10983", func() {
                                        SkipContextIf(helpers.DoesNotExistNodeWithoutCilium, "Tests LoadBalancer", func() {
                                                        res := kubectl.CiliumExecContext(
                                                        res = kubectl.CiliumExecContext(
                                                It("Connectivity to endpoint via LB", func() {
                                SkipContextIf(func() bool { return helpers.DoesNotRunOnNetNextKernel() || helpers.DoesNotExistNodeWithoutCilium() },
                                                It("Tests NodePort BPF", func() {
                                SkipItIf(func() bool {
                                        // It's also flaky for IPv6 traffic, see #18072
                                }, "Tests with secondary NodePort device", func() {
```

**Comment by brb** [comment]
@joestringer The test suite has been completely restructured, so I guess we are OK with the GH bot closing the issue.

**Comment by joestringer** [comment]
Yeah, this is maybe more of a wishlist item than anything. I still don't have a great workflow for figuring out which test is relevant when some portion of the test name is identical, which could be either solved by coming up with a better workflow or discouraging duplicate test name statements. Either way, this is not a super common workflow for me so I'm okay to just figure it out again as needed.
