### ISSUE TITLE
Cilium complains "Failed to remove old router IPs (restored IP: <nil>) from cilium_host. Manual intervention is required to remove all other old IPs."

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#18118]
Found in this v1.11 backport CI job:
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-4.9/49/testReport/junit/Suite-k8s-1/23/K8sDemosTest_Tests_Star_Wars_Demo/

```
Top 2 errors/warnings:
Failed to remove old router IPs (restored IP: <nil>) from cilium_host. Manual intervention is required to remove all other old IPs.
```

This seems like an extraneous warning that we should not report randomly in CI.

cc @christarazi

**Comment by esteban1983cl** [comment]
I have this strange message in eks 1.19, cilium v1.11.0
Somebody can explain this ?

**Comment by christarazi** [comment]
Could you upload a [sysdump](https://docs.cilium.io/en/v1.11/operations/troubleshooting/#automatic-log-state-collection) of when this happens again?

**Comment by christarazi** [comment]
From https://github.com/cilium/cilium/pull/19007

[dbdabccf_K8sPolicyTestExtended_Validate_toEntities_KubeAPIServer_Allows_connection_to_KubeAPIServer.zip](https://github.com/cilium/cilium/files/8523730/dbdabccf_K8sPolicyTestExtended_Validate_toEntities_KubeAPIServer_Allows_connection_to_KubeAPIServer.zip)

**Comment by joestringer** [comment]
This happened to me again on a fresh kind cluster, running `make kind` + `make kind-image` + setting the image to a dev image based on the latest code.

**Comment by christarazi** [comment]
Fix: https://github.com/cilium/cilium/pull/20734
