### ISSUE TITLE
k3s install guide doesn't work properly on Ubuntu 21.10

### ISSUE THREAD

**Issue by randomthingsandstuff** [cilium/cilium#18131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Follow guide from https://docs.cilium.io/en/stable/gettingstarted/k3s/

1) Setup master per guide
2) Setup worker per guide
3) Install Cilium per guide with slight modification to handle for config path
`KUBECONFIG=/etc/rancher/k3s/k3s.yaml sudo -E cilium install`

Expected behavior:
`cilium status` reports ok

Actual behavior:
`cilium status` reports `controller cilium-health-ep is failing` on both master and worker.

### Cilium Version

1.10.5

### Kernel Version

5.13.0-20

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+k3s1", GitCommit:"ac70570999c566ac3507d2cc17369bb0629c1cc0", GitTreeState:"clean", BuildDate:"2021-11-29T16:40:13Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7+k3s1", GitCommit:"ac70570999c566ac3507d2cc17369bb0629c1cc0", GitTreeState:"clean", BuildDate:"2021-11-29T16:40:13Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20211206-114450.zip](https://github.com/cilium/cilium/files/7660402/cilium-sysdump-20211206-114450.zip)

### Relevant log output

```shell
cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         2 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 2, Ready: 2/2, Available: 2/2
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 2
                  cilium-operator    Running: 1
Cluster Pods:     5/5 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.10.5: 2
                  cilium-operator    quay.io/cilium/operator-generic:v1.10.5: 1
Errors:           cilium             cilium-kx8lg    controller cilium-health-ep is failing since 4s (2x): Get "http://10.0.1.252:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-tqsmz    controller cilium-health-ep is failing since 9s (3x): Get "http://10.0.0.199:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

----
Defaulted container "cilium-agent" out of: cilium-agent, ebpf-mount (init), clean-cilium-state (init)
Probe time:   2021-12-06T11:26:33Z
Nodes:
  k8s1 (localhost):
    Host connectivity to 10.10.0.199:
      ICMP to stack:   OK, RTT=969.994µs
      HTTP to agent:   OK, RTT=264.057µs
    Endpoint connectivity to 10.0.1.252:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.0.1.252:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  k8s2:
    Host connectivity to 10.10.0.187:
      ICMP to stack:   OK, RTT=1.003886ms
      HTTP to agent:   OK, RTT=996.444µs
    Endpoint connectivity to 10.0.0.199:
      ICMP to stack:   OK, RTT=1.047324ms
      HTTP to agent:   OK, RTT=1.793835m
```

### Anything else?

Possibly related to #17926 per search.

All of this is performed on fresh cloud image instance of Ubuntu 21.10.

Reviewed issue on slack with @pchaigno prior to issue submission.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment]
@randomthingsandstuff 
out of curiosity, since I also use k3s, I tried to simulate your setup with your setting based on your sysdump cilium agent setting below

```
cilium-sysdump-20211206-114450 vli$ grep 'true' cilium-configmap-20211206-114450.yaml
  disable-cnp-status-updates: "true"
  enable-auto-protect-node-port-range: "true"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-l7-proxy: "true"
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-xt-socket-fallback: "true"
  install-iptables-rules: "true"
  node-port-bind-protection: "true"
  wait-bpf-mount: "true"

```
I could not reproduce your issue with two k3s node

```
[root@openEuler k3s]# kubectl exec -it  cilium-zl9hm    -n kube-system -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.21 (v1.21.5+k3s2) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled   
Cilium:                 Ok   1.10.5 (v1.10.5-b0836e8)
NodeMonitor:            Listening for events on 1 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 7/254 allocated from 10.0.0.0/24, 
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      43/43 healthy
Proxy Status:           OK, ip 10.0.0.228, 0 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 81.42   Metrics: Disabled
Encryption:             Disabled
Cluster health:         2/2 reachable   (2021-12-06T19:59:07Z)

```

**Comment by vincentmli** [comment]
I tried to install following the steps in https://docs.cilium.io/en/stable/gettingstarted/k3s/, I can't even install cilium with cilium cli

```
[root@openEuler ~]# cilium install --cluster-name="k3s-test"
ℹ️  using Cilium version "v1.10.5"
🔮 Auto-detected IPAM mode: cluster-pool
🔑 Generating CA...
↩️ Rolling back installation...

Error: Unable to install Cilium: unable to store CA in secret: unable to create secret kube-system/cilium-ca: Post "http://localhost:8080/api/v1/namespaces/kube-system/secrets": dial tcp [::1]:8080: connect: connection refused

```

I usually install cilium in k3s with cilium manifest yaml like `kubectl apply -f cilium.yaml`, no problem

**Comment by randomthingsandstuff** [comment]
Ah crap. Yeah, I updated the description to note that I used `KUBECONFIG=/etc/rancher/k3s/k3s.yaml sudo -E cilium install`. My bad.

**Comment by vincentmli** [comment]
> KUBECONFIG=/etc/rancher/k3s/k3s.yaml sudo -E cilium install

thanks, I can `cilium install`, but still, I can't reproduce your issue, weird.

**Comment by vincentmli** [comment]
@randomthingsandstuff what about your `KUBECONFIG=/etc/rancher/k3s/k3s.yaml cilium connectivity test`, maybe you are hitting https://github.com/cilium/cilium/issues/18079 ? 

I noticed you and  https://github.com/cilium/cilium/issues/18079  both have new `iptables-nft` utility installed, not `iptables-legacy` utility, maybe that could interfere with `Host Routing:           Legacy `?  I am running k3s on centos8 with `iptables-legacy` utility

```
KVStore:                Ok   Disabled                                            
Kubernetes:             Ok   1.21 (v1.21.7+k3s1) [linux/amd64]                   
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled                                                 
Cilium:                 Ok   1.10.5 (v1.10.5-b0836e8)                            
NodeMonitor:            Disabled                                                 
Cilium health daemon:   Ok                                                       
IPAM:                   IPv4: 2/254 allocated from 10.0.1.0/24,                  
Allocated addresses:                                                             
  10.0.1.232 (router)                                                            
  10.0.1.252 (health)                                                            
BandwidthManager:       Disabled                                                 
Host Routing:           Legacy  <=============                                                 
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]                 

```

**Comment by randomthingsandstuff** [comment]
Good catch. The transition to the new iptables stuff is always a good suspect.

Unfortunately, doesn't seem to have resolved it. I'm going to try to generate and apply a manifest per your original thoughts and mess with that too.  Possibly just switch over to CentOS 8 (or Rocky or whatever) as well since the distro isn't really relevant for my test case.

Connectivity check post-legacy change:

```
 Monitor aggregation detected, will skip some flow validation steps
✨ [default] Creating namespace for connectivity check...
✨ [default] Deploying echo-same-node service...
✨ [default] Deploying same-node deployment...
✨ [default] Deploying client deployment...
✨ [default] Deploying client2 deployment...
✨ [default] Deploying echo-other-node service...
✨ [default] Deploying other-node deployment...
⌛ [default] Waiting for deployments [client client2 echo-same-node] to become ready...
Connectivity test failed: waiting for deployment echo-same-node to become ready has been interrupted: context deadline exceeded
```

```
sudo k3s kubectl get -A pods
NAMESPACE     NAME                                      READY   STATUS             RESTARTS   AGE
kube-system   cilium-operator-8dd4dc946-5pkhb           1/1     Running            1          16m
kube-system   cilium-d5dqc                              1/1     Running            1          16m
kube-system   cilium-dmb2z                              1/1     Running            1          16m
cilium-test   client-6488dcf5d4-hwwhh                   1/1     Running            0          6m16s
cilium-test   client2-5998d566b4-cmbdv                  1/1     Running            0          6m16s
cilium-test   echo-same-node-745bd5c77-st6wv            0/1     Running            0          6m16s
cilium-test   echo-other-node-f4d46f75b-svlgc           0/1     Running            0          6m15s
kube-system   helm-install-traefik-2dp8g                1/1     Running            3          18m
kube-system   helm-install-traefik-crd-x9mqm            1/1     Running            3          18m
kube-system   coredns-7448499f4d-qmwtm                  0/1     CrashLoopBackOff   7          18m
kube-system   metrics-server-86cbb8457f-92k5f           0/1     CrashLoopBackOff   9          18m
kube-system   local-path-provisioner-5ff76fc89d-lj47p   0/1     CrashLoopBackOff   9          18m
```

**Comment by vincentmli** [comment]
sorry now i am not sure if `iptables-nft` really play a role here, I switched to `ubuntu 21.04` like yours with  `iptables-nft` ,  upgraded ubuntu 21.04 to kernel `5.13`, I think I reproduced the `health ep` issue once, then I realized I have some left over `/etc/kubernetes` config from `kubeadm` that may interfere with k3s, so I removed `/etc/kubernetes`, re-installed k3s, rebooted, then everything works fine, connectivity test works fine, no health ep issue.

**Comment by randomthingsandstuff** [comment]
Can confirm that tests pass fine on 21.04 with 5.13 and iptables-nft.

**Comment by vincentmli** [comment]
I am not sure how exact the cilium health ep works, without reliable repro locally, it is hard to figure out the problem :)

**Comment by randomthingsandstuff** [comment]
> I am not sure how exact the cilium health ep works, without reliable repro locally, it is hard to figure out the problem :)

Yeah but we're in a much better place.. some difference between underlying ubuntu 21.04 and 21.10. I'll try to look at them side-by-side and see what's up.

If you're interested in more details on my 21.10 repro, I spin up 2 VMs with libvirt and the ubuntu cloud image from here:

https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-amd64.img

cloud-init only messes with some SSH, node IP picked up via DHCP, underlay network is simple linux bridge hooked up to a VLAN.

**Comment by vincentmli** [comment]
oh, I thought you were having issue on 21.04, I will upgrade to 21.10, yes, I ran similar KVM/libvirt/bridge setup in my home server lab

**Comment by vincentmli** [comment]
I can reproduce your issue after upgrading to 21.10. it looks something related to ubuntu `21.10`

```
root@cilium-demo:~# KUBECONFIG=/etc/rancher/k3s/k3s.yaml cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         2 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 2, Ready: 2/2, Available: 2/2
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 2
                  cilium-operator    Running: 1
Cluster Pods:     10/12 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.10.5: 2
                  cilium-operator    quay.io/cilium/operator-generic:v1.10.5: 1
Errors:           cilium             cilium-fbmkq    controller cilium-health-ep is failing since 11s (1x): Get "http://10.0.1.159:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-l4mvg    controller cilium-health-ep is failing since 11s (1x): Get "http://10.0.0.170:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

```

**Comment by vincentmli** [comment]
@randomthingsandstuff I think you are running into https://github.com/cilium/cilium/issues/10645 where the  default `rp_filter` setting coming with systemd is set to `2` https://github.com/systemd/systemd/issues/21550, you can override the setting by add `/etc/sysctl.d/90-override.conf ` like below, then reboot, the problem should be resolved, I tested works.

```
root@cilium-demo:~# cat /etc/sysctl.d/90-override.conf 
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.*.rp_filter = 0
```

this is second time I came across this issue lately :)

**Comment by randomthingsandstuff** [comment]
We have a winner. Added config per your instructions and works out great. Thank you for your assistance and effort.

**Comment by stiliajohny** [comment]
following
