### ISSUE TITLE
RFE: collect sysctl rp_filter in bugtool?

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#18157]
## Proposal / RFE

**Is your feature request related to a problem?**

Some Linux distributions ships systemd sysctl `rp_filter` setting with 

https://github.com/systemd/systemd/blob/main/sysctl.d/50-default.conf#L24-L27

```
# Source route verification
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.*.rp_filter = 2
-net.ipv4.conf.all.rp_filter
```
Distributions like `ubuntu 21.10` and `openEuler` I tested include the systemd default `rp_filter` setting, this breaks cilium network connectivity like reported in:

https://github.com/cilium/cilium/issues/18131 health ep issue 
https://github.com/openeuler-mirror/community/issues/2
https://github.com/cilium/cilium/issues/10645

It could take fair amount of time to trouble shoot this kind of issue without knowing sysctl `rp_filter`

**Describe the solution you'd like**

before https://github.com/cilium/cilium/issues/10645 fix, I  suggest to collect sysctl output from bugtool to aid  trouble shooting network issue that could related to kernel sysctl setting like `rp_filter`

**Comment by vincentmli** [comment]
I can send  PR if agreed since this is simple enough :)

**Comment by pchaigno** [comment]
We already collect the output of `sysctl -a` in the bugtool: https://github.com/cilium/cilium/blob/e38e3c44f712b5f0ecf33efd1867c0ae16b241f7/bugtool/cmd/configuration.go#L100
Wouldn't that be enough?

**Comment by vincentmli** [comment]
> 
> Wouldn't that be enough?

sorry, I missed it
