### ISSUE TITLE
Creating any Networkpolicy block break health-probe connection from host

### ISSUE THREAD

**Issue by philipp1992** [cilium/cilium#18183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

i have installed latest k3s on latest ubuntu and installed cilium as following: 

 helm install --wait cilium cilium/cilium --namespace=cilium --set nativeRoutingCIDR=${cluster_subnet_cidr} --set tunnel=disabled --set endpointRoutes.enabled=true --set ipam.mode=kubernetes --set hubble.ui.enabled=true --set hubble.relay.enabled=true

Everything seems to be working fine and i can communicate between pods and hosts. 
Once i apply a networkpolicy (that only contains an ingress rule), the healthchecks to my pods, which come from the worker host, will get dropped. 
When i delete all networkpolicies from the namespace, the health-probe will work again.

![image](https://user-images.githubusercontent.com/11994884/145282267-5ed497cf-6c5d-4add-97b6-844c2d0aeecd.png)

How can i tell cilium to allow any connections from hosts to pods by default?

thanks and kind regards
Philipp

### Cilium Version

v1.11

### Kernel Version

5.4.0-90-generic
Ubuntu 20.04.3 LTS

### Kubernetes Version

v1.21.7+k3s

containerd://1.4.12-k3s1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Could you share the full details from those drop events? You might need to click on them in the UI or to use `hubble observe -o jsonpb`.

**Comment by joestringer** [comment]
I have another question here - Recently we realized that the default instructions for k3s in Cilium did not disable flannel's network policy handling. Unfortunately this meant that both Flannel and Cilium would attempt to apply the policy, causing conflicts and additional problems. Do you observe this issue even if you provision k3s using `--flannel-backend=none --disable-network-policy`?

**Comment by philipp1992** [comment]
> I have another question here - Recently we realized that the default instructions for k3s in Cilium did not disable flannel's network policy handling. Unfortunately this meant that both Flannel and Cilium would attempt to apply the policy, causing conflicts and additional problems. Do you observe this issue even if you provision k3s using `--flannel-backend=none --disable-network-policy`?

--disable-network-policy fixed it. Thanks a lot
