### ISSUE TITLE
Cilium agent crashloopback running on m6a instances

### ISSUE THREAD

**Issue by ese** [cilium/cilium#18197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium agent enters on crashloopback state due to fail health and liveness check becouse waiting for IPs to become available in allocation pool

cilium agent log
```
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-172-21-83-242.eu-west-1.compute.internal required=8 subsys=ipam
```

cilium-operator log
```
level=warning msg="Could not determined instance limits, maximum allocatable ipv4 addresses will be 0 (unlimited) this could lead to ip allocation overflows if the max-allocate flag is not set" adaptors-limit=unknown first-interface-index=0 subsys=eni
level=warning msg="Unable to maintain ip pool of node" error="Unable to determine limits" instanceID=i-0f0b5c1029b437017 name=ip-172-21-101-196.eu-west-1.compute.internal subsys=ipam
```

This instance is not listed in the aws-sdk used in cilium 
https://github.com/cilium/cilium/blob/master/vendor/github.com/aws/aws-sdk-go-v2/service/ec2/types/enums.go#L2400

### Cilium Version

v1.10.4

### Kernel Version

5.4.149-73.259.amzn2.x86_64

### Kubernetes Version

v1.21.2-eks-55daa9d

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
It seems this is a simple matter of updating our aws/aws-sdk-go-v2 dependency.

**Comment by gandro** [comment]
@ese: Please note that you can add or override the limits for new machines also manually using the `aws-instance-limit-mapping` configmap option on the operator:

https://docs.cilium.io/en/v1.10/cmdref/cilium-operator-aws/

```
      --aws-instance-limit-mapping map            Add or overwrite mappings of AWS instance limit in the form of {"AWS instance type": "Maximum Network Interfaces","IPv4 Addresses per Interface","IPv6 Addresses per Interface"}. cli example: --aws-instance-limit-mapping=a1.medium=2,4,4 --aws-instance-limit-mapping=a2.somecustomflavor=4,5,6 configmap example: {"a1.medium": "2,4,4", "a2.somecustomflavor": "4,5,6"} (default map[])
```

**Comment by ese** [comment]
Nice, Thanks @gandro
