### ISSUE TITLE
level=warning msg="iptables v1.8.4 (legacy): unknown option \"--tproxy-mark\"" subsys=iptables

### ISSUE THREAD

**Issue by tanguofu** [cilium/cilium#18229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
helm install cilium cilium/cilium --version 1.11.0 \
   --namespace kube-system  \
   --set tunnel=disabled   \
   --set autoDirectNodeRoutes=true  \
   --set kubeProxyReplacement=strict  \
   --set loadBalancer.mode=hybrid  \
   --set nativeRoutingCIDR=10.233.64.0/18  \
   --set ipam.operator.clusterPoolIPv4PodCIDR=10.233.64.0/18  \
   --set ipam.operator.clusterPoolIPv4MaskSize=18  \
   --set k8sServiceHost=9.100.10.26  \
   --set k8sServicePort=6443
```
the cilium pod logs:
```
...
level=info msg="regenerating all endpoints" reason="kube-apiserver identity updated" subsys=endpoint-manager
level=info msg="Adding new proxy port rules for cilium-dns-egress:40445" proxy port name=cilium-dns-egress subsys=proxy
level=error msg="Command execution failed" cmd="[iptables -w 5 -t mangle -A CILIUM_PRE_mangle -p tcp -m mark --mark 0xfd9d0200 -m comment --comment cilium: TPROXY to host cilium-dns-egress proxy -j TPROXY --tproxy-mark 0x200 --on-port 40445]" error="exit status 2" subsys=iptables
level=warning msg="iptables v1.8.4 (legacy): unknown option \"--tproxy-mark\"" subsys=iptables
level=warning msg="Try `iptables -h' or 'iptables --help' for more information." subsys=iptables
level=fatal msg="Error while creating daemon" error="Cannot install proxy rules for cilium-dns-egress: exit status 2" subsys=daemon
```

### Cilium Version

v1.11.0

### Kernel Version

Linux node1 5.4.119-19-0008 #1 SMP Mon Sep 13 14:54:39 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
This is probably happening because your kernel is missing support for some TPROXY feature. Where is the kernel from? Do you have the following options enabled in your kernel config? Could you share your kernel config?
```
CONFIG_NETFILTER_XT_TARGET_TPROXY=m
CONFIG_NETFILTER_XT_TARGET_CT=m
CONFIG_NETFILTER_XT_MATCH_MARK=m
CONFIG_NETFILTER_XT_MATCH_SOCKET=m
```
