### ISSUE TITLE
CI:  Cilium L4LB XDP: Collect sysdump as part of workflow

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#18221]
The L4LB workflow uses [a Bash script](https://github.com/cilium/cilium/blob/701967f31b7121dc811b3de6ca0fbbb284009749/test/l4lb/test.sh) to run tests (step `Run tests` of the workflow). That Bash script also [collects the sysdump in case of error](https://github.com/cilium/cilium/blob/701967f31b7121dc811b3de6ca0fbbb284009749/test/l4lb/test.sh#L93). We should instead collect the sysdump as a separate step in the workflow, for consistency with other workflows and to get the proper information [when it fails](https://github.com/cilium/cilium/runs/4477255000?check_suite_focus=true).

cc @brb

**Comment by oblazek** [comment]
mind if I take this? :)

**Comment by brb** [comment]
@oblazek Go for it!
