### ISSUE TITLE
[BGP] PodCidr routes withdrawn when svc loadbalancing feature enabled

### ISSUE THREAD

**Issue by ldelossa** [cilium/cilium#18250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As reported by community members and confirmed by your's truly, the PodCidr announcement are withdrawn when service load balancer announcements are enabled in tandem. 

This is most likely a symptom of our MetalLB integration. Will begin investigating. 

### Cilium Version

Cilium 1.11

### Kernel Version

applicable to all kernels

### Kubernetes Version

Applicable to all kubernetes versions. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nniehoff** [comment]
I wonder if this is the same problem described on the metallb page about Calico https://metallb.universe.tf/configuration/calico/ does Cilium create 2 sessions with the routers reporting the podcidrs once and the loadbalancer IPs a second time?

**Comment by christarazi** [comment]
@ldelossa Is this fixed by https://github.com/cilium/cilium/pull/18358 or is it a separate issue?

**Comment by ldelossa** [comment]
@christarazi two separate issues. This one has a community member proposing a fix. Waiting for the patch to be applied to our MetalLB Fork. https://cilium.slack.com/archives/C53TG4J4R/p1643050292080000?thread_ts=1639163541.078600&cid=C53TG4J4R

**Comment by christarazi** [comment]
Should we propose this change upstream to MetalLB rather than changing our fork behavior?

**Comment by Elegant996** [comment]
@christarazi based on https://github.com/metallb/metallb/issues/1211#issuecomment-1034181020, this does not appear to be in scope of the project. In a way, it makes sense, `metallb` is designed to provide a loadbalancer IP for baremetal clusters and advertising pod CIDRs is technically out of scope.

Perhaps `cilium` should use the controller feature of `metallb` and the create a separate module to announce pod and service CIDRs?

**Comment by ldelossa** [comment]
@Elegant996 we are in the process of migrating to a new BGP control plane. 

We have implemented our own controller and are migrating the PodCIDR announcement features currently.

Moving forward we will be migrating the facilities `MetalLB` provides as well, a bare metal load balancer and BGP advertisements. 

The new BGP control plane can be viewed here and is currently under review. #18860

**Comment by dylandreimerink** [comment]
I believe this issues has been resolved after a bug fix was created and backported to Cilium v1.11,  see #20836
