### ISSUE TITLE
DNS proxy use fixed port 

### ISSUE THREAD

**Issue by judexzhu** [cilium/cilium#18286]
## Proposal / RFE

I found if I set `l7Proxy: true`, cilium-agent will open a random tcp and udp port for DNS proxy from 32769~65535(I guess...)

if this can be a fixed port, it will be much easier to set up the host firewall rules or ACL.

I think the port is defined here
https://github.com/cilium/cilium/blob/aa329c87529cb316e4d92f9e5806a344897c6534/pkg/datapath/iptables/iptables.go#L924 

Sorry for not being able to provide a PR for this (still learning how to program right now) 

Slack thread link : https://cilium.slack.com/archives/C01JALNQAR1/p1639600869383900

**Comment by pchaigno** [comment]
Joining the `ss` image from the Slack thread as well: 
![image](https://user-images.githubusercontent.com/1764210/146440283-39accfc6-2199-4e94-ad1d-99cbc8156c33.png)

@jrajahalme @nebril Is there a reason why we're not listening only on 127.0.0.1 here for the DNS proxy? Also, could we only listen on those ports if there are actually DNS policies?

**Comment by jrajahalme** [comment]
There is a Cilium-agent command line option for setting the DNS proxy port:
```
      --tofqdns-proxy-port int                               Global port on which the in-agent DNS proxy should listen. Default 0 is a OS-assigned port.
```
Currently there is no corresponding Helm value, but if you are installing with Cilium CLI, you can add a `--config` option, e.g.:
```
cilium install --config tofqdns-proxy-port=5353
```
Note that you should specify a port that is not used for anything else in your k8s/Cilium nodes.

As to host firewall / ACL rules, connections to this port need to be allowed from local pods only.

@pchaigno We use TPROXY redirection to accept connections to foreign addresses in the (DNS) proxy. My **assumption** is that this requires the listening socket to be listening at the ANY address. Currently the DNS proxy setup is done unconditionally at the agent bootstrap. It may be possible to change this to happen only if there are DNS policies present, but there would be some nontrivial nuance w.r.t. agent restarts, before all the policies have been received from the k8s apiserver.
