### ISSUE TITLE
Cannot build unstripped container images

### ISSUE THREAD

**Issue by YutaroHayakawa** [cilium/cilium#18315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm now learning Cilium and trying to attach `delve` to `cilium-agent` process. So, I'm building the Cilium unstripped images.

There are two potentially related issues.

1. In the latest `master`, `make docker-images-all-unstripped` fails with following error.

```
make: *** No rule to make target 'docker-operator-image-unstripped', needed by 'docker-operator-images-all-unstripped'.  Stop.
```

2. Above seems like only `operator` images are failing to build. But actually unstriped images are not built at all (unstripped images should have `-unstripped` suffix).

```
$ docker images
REPOSITORY                             TAG       IMAGE ID       CREATED              SIZE
quay.io/cilium/clustermesh-apiserver   latest    03a550907894   About a minute ago   53.9MB
quay.io/cilium/hubble-relay            latest    155c8d88a440   3 minutes ago        32.2MB
quay.io/cilium/docker-plugin           latest    904a25e22672   3 minutes ago        15.3MB
quay.io/cilium/cilium                  latest    8bace7fe76c4   3 minutes ago        437MB
```

Seems like `NOSTRIP` flags are not set. For example, `clustermesh-apiserver` image is built like this.

```
docker buildx build -f images/clustermesh-apiserver/Dockerfile  --load --build-arg BASE_IMAGE=scratch --build-arg NOSTRIP= --build-arg NOOPT= --build-arg LOCKDEBUG= --build-arg RACE= --build-arg V= --build-arg LIBNETWORK_PLUGIN= --build-arg CILIUM_SHA=99c034f398 --build-arg OPERATOR_VARIANT=clustermesh-apiserver -t quay.io/cilium/clustermesh-apiserver:latest .
```

I'm trying to solve this problem, but I haven't found the cause yet. Since there's no one reporting this issue, I'll leave here a report.

### Cilium Version

I'm not running Cilium.

### Kernel Version

```
$ uname -a
Linux yutaro-XPS-13-9310 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

I'm not running k8s.

### Relevant log output

```shell
GNU Make version


$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhanghe9702** [comment]
i met same problem, it should be make tool ignored the pattern rule, i don't known the reason, but it could be solved by add an dummy cmd in receipt part

**Comment by aanm** [comment]
@zhanghe9702 and @YutaroHayakawa feel free to submit a PR with the fix. Thank you!
