### ISSUE TITLE
Unable to deploy Cilium 1.11 on EKS 1.21 with managed etcd

### ISSUE THREAD

**Issue by musabmasood** [cilium/cilium#18332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After several tries, we were unable to deploy Cilium with managed etcd. When the etcd operator is deployed, it seems its stuck in the `check-dns` initContainer with a failing nslookup:

```
nslookup: can't resolve 'cilium-etcd-rxvppdg87c.cilium-etcd.cilium.svc'
Server:    10.4.0.10
Address 1: 10.4.0.10 kube-dns.kube-system.svc.cluster.local
```
We tested this on a brand new EKS cluster following the [official AWS Cilium docs](https://aws.amazon.com/blogs/containers/a-multi-cluster-shared-services-architecture-with-amazon-eks-using-cilium-clustermesh/).  It works until cilium is deployed without CRD mode initially, and starts failing after we enable the managed etcd mode.

Our environment:

* EKS version `1.21`
* Node image: `Amazon Linux 2`
* Kernel version: `5.4.156-83.273.amzn2.x86_64`
* Cilium version `1.11`
* Cilium helm chart:

```yaml
dependencies:
name: cilium
repository: https://helm.cilium.io/
version: 1.11.0
```

Note that If we log into the `check-dns` container and append `cluster.local`, it does resolve correctly.

### Cilium Version

1.11

### Kernel Version

5.4.156-83.273.amzn2.x86_64

### Kubernetes Version

1.21

### Anything else?

[This](https://github.com/coreos/etcd-operator/issues/2043) is the closest GH issue I could find that resonates our case

Cilium deploys etcd operator version `0.9.4` which (by the docs) doesn’t seem to support 
`spec.Pod.ClusterDomain` to explicitly set it. It seems that this feature is only in the master branch ([unreleased?](https://github.com/coreos/etcd-operator/blob/master/CHANGELOG.md#added)). Therefore we could not set it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MichaelHindley** [comment]
The cilium helm chart lost the etcd.managed value in the values.yml file between version 1.09 and 1.10, but it is still referenced all over the templates files in both 1.10 and 1.11, but the behaviour will be faulty since the value will always be false

**Comment by musabmasood** [comment]
> The cilium helm chart lost the etcd.managed value in the values.yml file between version 1.09 and 1.10, but it is still referenced all over the templates files in both 1.10 and 1.11, but the behaviour will be faulty since the value will always be false

Not sure that matters since we were installing it with which should set the right value:

```
etcd:
  enabled: true
  managed: true
```

**Comment by joestringer** [comment]
Hi, etcd-operator is no longer supported by the upstream team (see https://github.com/coreos/etcd-operator) and so we have [deprecated the options to configure it in Cilium](https://github.com/cilium/cilium/pull/15464) for a few releases now. I would suggest following the latest [Cilium documentation on Cluster Mesh](https://docs.cilium.io/en/stable/gettingstarted/clustermesh/clustermesh/#gs-clustermesh) instead if you wish to deploy and peer multiple clusters together.

**Comment by musabmasood** [comment]
The documentation you referred doesn't talk about etcd at all. Does this mean we don't need etcd anymore to implement cluster-mesh? Also, is there a declarative way to setup clustermesh (we used cilium helm chart to deploy it)? Thanks.

**Comment by joestringer** [comment]
@musabmasood technically under the hood, this new model still runs etcd itself, but you no longer need to worry about this - see the implementation here: https://github.com/cilium/cilium/tree/master/clustermesh-apiserver . It should be possible to declaratively deploy this, however I'm not aware of any specific documentation describing exactly how to do this today.

**Comment by musabmasood** [comment]
Thanks for your help, I've been looking at 1.9 documentation everytime and thought I need managed etcd. Resolving.
