### ISSUE TITLE
cilium don't create nodeport

### ISSUE THREAD

**Issue by erictarrence** [cilium/cilium#18341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After the linux/k8s system restarts, cilium don't create nodeport

# kubectl exec -it -n kube-system cilium-n6cn5  -- cilium status --verbose
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20 (v1.20.5) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [enp1s0 (Direct Routing)]
Cilium:                 Ok   1.9.7 (v1.9.7-f993696)
NodeMonitor:            Listening for events on 6 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 13/255 allocated from 10.0.3.0/24, 

Proxy Status:   OK, ip 10.0.3.85, 0 redirects active on ports 10000-20000
Hubble:         Ok   Current/Max Flows: 4096/4096 (100.00%), Flows/s: 30.70   Metrics: Ok
KubeProxyReplacement Details:
  Status:              Strict
  Protocols:           TCP, UDP
  Devices:             enp1s0 (Direct Routing)
  Mode:                SNAT
  Backend Selection:   Random
  Session Affinity:    Enabled
  XDP Acceleration:    Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled

# kubectl exec -it -n kube-system cilium-n6cn5  -- cilium service list | grep -i nodeport
11   192.168.1.14:30093   NodePort       1 => 10.0.4.135:9093     
12   0.0.0.0:30093        NodePort       1 => 10.0.4.135:9093     
14   192.168.1.14:32000   NodePort       1 => 10.0.3.195:3000     
15   0.0.0.0:32000        NodePort       1 => 10.0.3.195:3000     
18   192.168.1.14:32080   NodePort       1 => 10.0.3.130:8081     
19   0.0.0.0:32080        NodePort       1 => 10.0.3.130:8081     
25   192.168.1.14:30090   NodePort       1 => 10.0.4.5:9090       
26   0.0.0.0:30090        NodePort       1 => 10.0.4.5:9090       

hubble-ui configmap.yaml

spec:
  clusterIP: 10.100.0.197
  clusterIPs:
  - 10.100.0.197
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32080
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: hubble-ui
  sessionAffinity: None
  type: NodePort

kubectl edit svc grafana       -n monitoring
spec:
  clusterIP: 10.100.0.98
  clusterIPs:
  - 10.100.0.98
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32000
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort

 kubectl get svc -n monitoring | grep -i nodeport
alertmanager-main       NodePort    10.100.0.126   <none>        9093:30093/TCP               28d
grafana                 NodePort    10.100.0.98    <none>        3000:32000/TCP               28d
prometheus-k8s          NodePort    10.100.0.34    <none>        9090:30090/TCP               28d

k8s node netstat -ntlp didn't see grafana and hubble-ui nodeport 

netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:9876          0.0.0.0:*               LISTEN      1885/cilium-agent   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      806/sshd            
tcp        0      0 127.0.0.1:9890          0.0.0.0:*               LISTEN      1885/cilium-agent   
tcp        0      0 127.0.0.1:34693         0.0.0.0:*               LISTEN      815/containerd      
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      873/kubelet         
tcp        0      0 192.168.1.14:9100       0.0.0.0:*               LISTEN      3091/kube-rbac-prox 
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      3051/node_exporter  
tcp6       0      0 :::4244                 :::*                    LISTEN      1885/cilium-agent   
tcp6       0      0 :::22                   :::*                    LISTEN      806/sshd            
tcp6       0      0 :::9090                 :::*                    LISTEN      1885/cilium-agent   
tcp6       0      0 :::9091                 :::*                    LISTEN      1885/cilium-agent   
tcp6       0      0 :::46791                :::*                    LISTEN      1885/cilium-agent   
tcp6       0      0 :::10250                :::*                    LISTEN      873/kubelet         
tcp6       0      0 :::4240                 :::*                    LISTEN      1885/cilium-agent

### Cilium Version

cilium 1.9.6 and 1.9.7

### Kernel Version

 4.18.0-193.el8.x86_64 #1 SMP

### Kubernetes Version

v1.20.5

### Sysdump

[Uploading cilium-sysdump-20211228-113331.zip…]()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ericra95** [comment]
[root@test-centos8-kvm11 ~]#  kubectl get pod -n kube-system -o wide | grep cilium-node-init-79cvf 
cilium-node-init-79cvf            1/1     Running   12         86d   192.168.1.11   master1   <none>           <none>

[root@test-centos8-kvm11 ~]#  kubectl exec -it cilium-node-init-79cvf  --  sh
Error from server (NotFound): pods "cilium-node-init-79cvf" not found
[root@test-centos8-kvm11 ~]#
