### ISSUE TITLE
CI: failed to ensure kubectl version: failed to run kubectl version

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#18386]
### Test Name

```shell
K8sFQDNTest Restart Cilium validate that FQDN is still working
and all subsequent tests
```

### Failure Output

```shell
15:14:26  • Failure in Spec Setup (BeforeEach) [0.006 seconds]
15:14:26  K8sFQDNTest [BeforeEach]
15:14:26  /home/jenkins/workspace/Cilium-PR-K8s-1.23-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:473
15:14:26    Restart Cilium validate that FQDN is still working
15:14:26    /home/jenkins/workspace/Cilium-PR-K8s-1.23-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
15:14:26  
15:14:26    failed to ensure kubectl version: failed to run kubectl version
15:14:26  
15:14:26    /home/jenkins/workspace/Cilium-PR-K8s-1.23-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:647
```

`test-output.log` provides additional information:
```
time="2022-01-03T15:14:20Z" level=error msg="Error executing command 'kubectl version --client -o json'" error="exit status 2"
cmd: "kubectl version --client -o json" exitCode: 2 duration: 2.551155ms stdout:

err:
exit status 2
stderr:
/tmp/kubectl/1.23/kubectl: line 1: syntax error near unexpected token `<'
/tmp/kubectl/1.23/kubectl: line 1: `<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.23.0/bin/linux/amd64/kubectl</Details></Error>'
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next/97/consoleFull
- ZIP file(s): 
[test_results_Cilium-PR-K8s-1.23-kernel-net-next_97_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/7817026/test_results_Cilium-PR-K8s-1.23-kernel-net-next_97_BDD-Test-PR.zip)

**Comment by joestringer** [comment]
Hit in [this k8s-1.23-kernel-net-next job](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next/178/) from the first test.

**Comment by joestringer** [comment]
It seems like sometimes the kubectl binary we fetch from `https://storage.googleapis.com/kubernetes-release/release/%s/bin/linux/amd64/kubectl` (for some version `%s`) isn't actually a binary, but is really just an error message from the server about not being able to find the relevant file.

Maybe we should enhance this function to grab the checksums, double-check them, and do retries if the sha fails?
https://github.com/cilium/cilium/blob/dddbbe709e2827873420fef9b635152340f37f91/test/helpers/kubectl.go#L4475

Official upstream kubectl install instructions:
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

**Comment by bmcustodio** [comment]
This was also observed in [this PR](https://github.com/cilium/cilium/pull/18486#issuecomment-1023292144).
