### ISSUE TITLE
Bugtool to support .tar.gz compression

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#18391]
Bugtool currently only produces  .tar|.gz format, which is still too big for transferring over the wire. As per below discussion, it will be great to have support for .tar.gz directly.

```
root@kind-control-plane:/var/run/cilium# cilium-bugtool -h
Collects agent & system information useful for bug reporting

Usage:
  cilium-bugtool [OPTIONS] [flags]
  cilium-bugtool [command]

Examples:
	# Collect information and create archive file
	$ cilium-bugtool
	[...]

	# Collect and retrieve archive if Cilium is running in a Kubernetes pod
	$ kubectl get pods --namespace kube-system
	NAME                          READY     STATUS    RESTARTS   AGE
	cilium-kg8lv                  1/1       Running   0          13m
	[...]
	$ kubectl -n kube-system exec cilium-kg8lv -- cilium-bugtool
	$ kubectl cp kube-system/cilium-kg8lv:/tmp/cilium-bugtool-243785589.tar /tmp/cilium-bugtool-243785589.tar

Available Commands:
  completion  generate the autocompletion script for the specified shell
  help        Help about any command

Flags:
      --archive                   Create archive when false skips deletion of the output directory (default true)
      --archive-prefix string     String to prefix to name of archive if created (e.g., with cilium pod-name)
  -o, --archiveType string        Archive type: tar | gz (default "tar")
      --config string             Configuration to decide what should be run (default "./.cilium-bugtool.config")

```

Related to https://github.com/cilium/cilium-cli/pull/671#discussion_r777418100

**Comment by spotted-cat** [comment]
Hello I am new to Open Source contributions :)
I have looked into the root.go file of bugtool where this feature could be implemented by updating the isValidArchiveType, runTool, and cleanup functions. Is there something else more I am missing here?

**Comment by spotted-cat** [comment]
I looked in the `CreateArchive` and `CreateGzip` function implementations inside the `helper.go` file where it seems that the `CreateGzip` function is first calling `CreateArchive` to make a tarball file which after gets compressed with the gzip compression. So I think when set to gz as Archive type it is actually creating a .tar.gz file

**Comment by sayboras** [comment]
@spotted-cat  :wave: thanks for your checking on this. You are right, seems like underlying implementation is already doing .tar.gz, good spot :100: . 

While this issue is no longer required, we can directly leverage .tar.gz from bugtool, and remove the below block that I recently added. Feel free to let us know if you want to work on this. Please reach out on Slack if you have any question

https://github.com/cilium/cilium-cli/blob/master/sysdump/sysdump.go#L910-L915

```
root@kind-control-plane:/tmp# ls -lrt
total 25708
drwxr-xr-x 3 root root     4096 Jan 10 20:32 cilium
-rw-r--r-- 1 root root 22809600 Jan 10 20:34 cilium-bugtool-20220110-203404.604+0000-UTC-3830928748.tar
-rw-r--r-- 1 root root  3508587 Jan 10 20:34 cilium-bugtool-20220110-203413.452+0000-UTC-3784983476.tar.gz
```

**Comment by spotted-cat** [comment]
Yes I would like to work on this issue, mostly it's just removing that blob and updating the help to say that gz means .tar.gz?

**Comment by spotted-cat** [comment]
Shall I open an issue in the `cilium-cli` repo where removing that redundant compression blob?

**Comment by sayboras** [comment]
hi,

Yes, two things we are can do here for each repo

cilium:
- Update the help to make it clearer if archive type is passed as gz. 
- Skim through some docs if we need to do similar thing

cilium-cli:
- Simplify the steps of capture bugtool by using -archiveType gz directly. This might require to pass flags to bugtool, however, the tricky part is that we have support CiliumBugtoolFlags, so what happen if there is conflict. Last time, I check, cilium cli will take value from the later.
- Remove unncessary code like gz the output.

**Comment by spotted-cat** [comment]
I will alter the help and scan the docs in this repo. After that I will look into the `cilium-cli` repo for what could be done, Though will raise the issue in `cilium-cli` for cleaning up that gzip blob now.

**Comment by sayboras** [comment]
This is fixed as part of https://github.com/cilium/cilium-cli/pull/970
