### ISSUE TITLE
Add small ArgoCD notes in the official documentation

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#18393]
There have been a lot of reports for users hitting issues with ArgoCD. It would be nice to have a dedicate section for it on the official documentation. Some of the known issues and solutions for it can be found on the GH issues from [this](https://github.com/cilium/cilium/issues?q=is%3Aissue+argocd+is%3Aclosed) list.

**Comment by pi1814** [comment]
Hello, Can I work on this?

**Comment by pi1814** [comment]
Hello, Can I work on this?

**Comment by Kikiodazie** [comment]
Hey @aanm, I would love to try my hands on this issue? can it be assigned to me?

**Comment by sayboras** [comment]
thanks, I have assigned issue to you, feel free to reach out in cilium slack channels (e.g. development, sig-docs)
