### ISSUE TITLE
Improve error msg when endpoint fails to be created due to full policymap size

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#18407]
There have been reports where endpoints fail to be created (due to a Cilium API timeout) because the policymap is full. The error msg seen by the user ("Cilium API timed out") is not helpful at all if the policymap is filled up, because the API could time out for a myriad of reasons. 

In one specific case, the reason why the policymap was full was due to an FQDN leak which was fixed by https://github.com/cilium/cilium/pull/17699 & https://github.com/cilium/cilium/pull/17788.

In the future, if we encounter a scenario like this again, we will at least have a specific error msg indicating the root cause of the problem.

**Comment by chowmean** [comment]
Hi, @christarazi if possible can you please point me the piece of code. I will try to fix the error message.

**Comment by christarazi** [comment]
Turns out this is a dup of https://github.com/cilium/cilium/issues/15864. See the linked PR. It is available since 1.10.4. Closing, apologies @chowmean, thanks for the interest! Please check out other good fist issues.
