### ISSUE TITLE
Ginkgo CI: update developer documentation

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1843]
Parent: #1839 

Update `Documentation/contributing.rst` to reflect how to use the new Ginkgo CI framework. A lot of this information will be in `test/readme.md` once #1733 is merged.

**Comment by joestringer** [comment]
The baseline should work via the already-documented `$ make runtime-tests` once we properly switch over.

I'll plan to add a few things, something along the lines of this:

* Gingko must be run from test/
* Basic run example: `ginkgo --focus "Policy"`
* For cilium flags: `ginkgo -- --help | grep -A 1 cilium`
>   -cilium.holdEnvironment
        On failure, hold the environment in its current state
  -cilium.provision
        Provision Vagrant boxes and Cilium before running test (default true)
* Run eg. `ginkgo --focus "Policy" -- -cilium.holdEnvironment`
