### ISSUE TITLE
Service CT entries leaking

### ISSUE THREAD

**Issue by maxwellxxx** [cilium/cilium#18442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Visiting clusterIP in a POD leads to a **service CT** entry generated in CT map with a long timeout. Because the service CT entry does not see close in INGRESS direction, I think this is a **critical bug**.
```
$ cilium bpf ct list global |grep 192.168.15.94
TCP OUT 192.168.15.94:80 -> 172.16.0.16:60462 service expires=113956 RxPackets=0 RxBytes=4209 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=92356 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=116 SourceSecurityID=0 IfIndex=0
```
If the visiting is very frequently, such as a high load application. The count of service CT entries will has a significant growth.
```
$ cilium bpf ct list global |grep 192.168.15.94 |grep service |wc -l
14116
```
As time goes on, the CT map will be full. Then the new connection will be reset like https://github.com/cilium/cilium/issues/17457

**I am going to fix it with the following logic**: 
1. After deNAT, we have the clusterIP, then lookup the CT map again with the new tuple, if the entry is existed, set entry->rx_closing with 1.

### Cilium Version

Client: 1.9.0 go version go1.15.4 linux/amd64
Daemon: 1.9.0 go version go1.15.4 linux/amd64

### Kernel Version

Linux 4.14.105-19-0019 SMP Fri Jan 15 11:39:34 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6b913dbde30aa95b247be30a5318fb912f8fe29e", GitTreeState:"clean", BuildDate:"2021-08-11T10:20:21Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.18-57+776098ae2e7bf3-dirty", GitCommit:"776098ae2e7bf358cce0af0b0faf139fe66c6c48", GitTreeState:"dirty", BuildDate:"2021-09-01T07:38:52Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxwellxxx** [comment]
@tgraf

**Comment by pchaigno** [comment]
> Visiting clusterIP in a POD leads to a service CT entry generated in CT map with a long timeout. Because the service CT entry does not see close in INGRESS direction, I think this is a critical bug.

Why is the TCP FIN exchange not seen here? Under what Cilium configuration did you reproduce this?

cc @brb

**Comment by aditighag** [comment]
It'll also be useful to check `conntrack-gc-interval`. Could you also attach the sysdump *while* the issue is happening? Please highlight the service traffic tuple that you suspect is leaking.

**Comment by ChangyuWang** [comment]
> It'll also be useful to check `conntrack-gc-interval`. Could you also attach the sysdump _while_ the issue is happening? Please highlight the service traffic tuple that you suspect is leaking.

Reduce the value of `conntrack-gc-interval` could not solve the problem in depth.  Just transmit a lot requests via accessing service clusterIP to reproduce the problem.

**Comment by answer1991** [comment]
![image](https://user-images.githubusercontent.com/2566352/149154057-e85da620-14e2-4f34-a2aa-f8f12a5a0cd2.png)

It's very easy to reproduce the leak:
1. Create a deployment to generate Server pod, and create a service relate to the Server pod which has ClusterIP *192.168.0.1*
2. Use any pod as Client, exec in the Client pod, run `curl 192.168.0.1`
3. Exec in the cilium-agent pod which on the same node of the Client pod, run `cilium bpf ct list global|grep 192.168.0.1` will see the leak entry looks like:
```bash
TCP OUT 10.96.118.172:80 -> 10.244.1.139:57438 service expires=17135534 RxPackets=0 RxBytes=3 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=17114441 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=6 SourceSecurityID=0 IfIndex=0
```
4. **The leaked entry will not be GC until 6h later.**

**Think about many pods visit many service ClusterIPs, it's very easy to touch the max TCP CT entry, and then the new connections will receive the unexpected rest, as eBPF lru map drop the item randomly.**

**Comment by answer1991** [comment]
Besides, as I know, CT entry will also leak when receive rst.

**Comment by brb** [comment]
> Why is the TCP FIN exchange not seen here?
@pchaigno https://github.com/cilium/cilium/blob/master/bpf/lib/conntrack.h#L266

**Comment by brb** [comment]
> As time goes on, the CT map will be full.

This should not be a problem if you use the LRU maps for the CT entries.

**Comment by brb** [comment]
@BSWANG https://github.com/cilium/cilium/pull/19451 and https://github.com/cilium/cilium/pull/19800 should help you with this problem.
