### ISSUE TITLE
Validate example policies in Cilium documentation

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1845]
Cilium documentation example policies can become out of date and may inadvertently contain typos. Instead of having these policies directly as part of the docs, substitute these files into the docs via some type of script when the Documentation is built. That way we could do some validation on the files themselves as part of the build instead of realizing retroactively that we have to change them.

**Comment by aalemayhu** [comment]
sphinx has [literalinclude](http://www.sphinx-doc.org/en/stable/markup/code.html#directive-literalinclude). We are already using it in the install guide for the mount file. For validation would be nice to run `cilium policy validate` on all examples. 

Thanks.

**Comment by aalemayhu** [comment]
Tried looking for a way to validate YAML files via `kubectl` but could not find something that worked with `CiliumNetworkPolicy`. Would a regular YAML linter be sufficient?

**Comment by aalemayhu** [comment]
Found [yamllint](https://github.com/adrienverge/yamllint). The default checks seems too strict though

```bash
yamllint `find examples/policies/ -name '*.yaml'`
examples/policies/kafka.yaml
  1:1       warning  missing document start "---"  (document-start)
  3:81      error    line too long (81 > 80 characters)  (line-length)
  11:3      error    wrong indentation: expected 4 but found 2  (indentation)
  12:5      error    wrong indentation: expected 6 but found 4  (indentation)
  15:5      error    wrong indentation: expected 6 but found 4  (indentation)
  16:7      error    wrong indentation: expected 8 but found 6  (indentation)
  20:9      error    wrong indentation: expected 10 but found 8  (indentation)

examples/policies/l3.yaml
  1:1       warning  missing document start "---"  (document-start)
  10:3      error    wrong indentation: expected 4 but found 2  (indentation)
  11:5      error    wrong indentation: expected 6 but found 4  (indentation)

```
