### ISSUE TITLE
Failed to generate cert on arm64 due to certgen-image being amd64 only

### ISSUE THREAD

**Issue by rlex** [cilium/cilium#18508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Helm chart defaults to certgen-image 0.1.5:

https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/values.yaml#L553

However, looking at https://quay.io/repository/cilium/certgen?tag=latest&tab=tags it seems arm64 is only built since 0.1.6

So when deploying on arm64 cluster with cronjob it will fail with exec error.

Works if i bump it to 0.1.6, but not to 0.1.7.

Might be worth bumping default version?

### Cilium Version

1.11.0

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@rlex feel free to open a PR that bumps the cergen image to 0.1.7. Thank you!

**Comment by rlex** [comment]
@aanm 0.1.7 will not work - looks like arguments has changed. 0.1.6, previous release, works fine.

**Comment by gandro** [comment]
For reference, certgen 0.1.7 contains some breaking changes needed for an in-progress refactoring tracked here https://github.com/cilium/cilium/issues/18278

But yes, 0.1.6 should be fully compatible with the arguments passed to 0.1.5.

**Comment by aanm** [comment]
@rlex yes, I meant 0.1.6. Thanks!

**Comment by ctmach** [comment]
Fixes as part of #18607

**Comment by sayboras** [comment]
Fixed as part of #18607 , thanks Lex for highlighting.
