### ISSUE TITLE
cilium-agents crashing / cmd="[ip6tables -w 5 -t nat -S]" error="exit status 3" subsys=iptable

### ISSUE THREAD

**Issue by ludurr** [cilium/cilium#18513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i am currently implementing cilium CNI with a rke2 without kube-proxy mode. And currently facing the issue below.

### Cilium Version

cilium:v1.10.4 

### Kernel Version

workernodes
Ubuntu 20.04.3 LTS/ Kernel: Linux 5.4.0-84-generic
Oracle Linux Server 8.5/  Kernel: Linux 5.4.17-2136.300.7.el8uek.x86_64

### Kubernetes Version

v1.22.4+rke2r1

### Sysdump

n/a

### Relevant log output

```shell
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t nat -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t mangle -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `mangle': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t raw -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `raw': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t filter -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t nat -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t mangle -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `mangle': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t raw -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `raw': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t filter -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Address family not supported by protocol" subsys=iptables
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report. At a glance, assuming that you've correctly disabled Cilium IPv6 support, this looks like a minor bug where Cilium attempts to at least list IPv6 iptables rules even if IPv6 support is disabled / detected as not available. These errors should not by themselves cause any subsequent problems for Cilium operation, but it would be good to clean these up to remove the noise from the logs in environments that don't support IPv6 like this.

**Comment by pchaigno** [comment]
@ludurr Could you check if the fix at https://github.com/cilium/cilium/pull/18716 works for you? You can test it with agent image `quay.io/cilium/cilium-ci:047ce210698d4d349ba92628f3ae24cd5fcbe2f5@sha256:67defa04e2c56f08c9a7d0f8a787bee8c3537abdbee744149d03fa6f496ae7b8`.

**Comment by pchaigno** [comment]
Reopening because the fix at https://github.com/cilium/cilium/pull/18716 is incorrect and shouldn't be required to fix this. See https://github.com/cilium/cilium/pull/18716#discussion_r803215901 for details.

@ludurr Could you share a Cilium sysdump for this cluster to understand what's happening? If you can't share that, could you at least share the output of `lsmod`?

**Comment by jaredledvina** [comment]
I'm pretty certain this happens when you have passed in `ipv6.disable=1` as a kernel parameter. In that setup, the ip6table modules still load causing `haveIp6tables` to be set to `true` and the cleanup logic to happen. However, any calls to ip6tables fail with the `Address family not supported by protocol` since ipv6 is disabled in the kernel. 

I don't know if there's a simple way for Cilium to detect if the kernel has had this option enabled and thus skip all of the ip6table stuff.
