### ISSUE TITLE
Cilium scale / stress testing plan

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1851]
We need to test Cilium itself at scale (i.e., large number of endpoints with large number of API requests sent to Cilium at once). This serves as a parent issue for what we might need for such tests.

Determine the following:
- [ ] Cadence of these tests
- [ ] Type of environment (packet.net, cloud provider, etc.)
- [ ] Accepted load Cilium can handle (i.e., what do we guarantee Cilium can handle under stress 
- [ ] Proxy performance / load (TODO - does this go here? might go under datapath stress testing as opposed to testing of Cilium itself)

**Comment by ianvernon** [comment]
cc: @aanm @raybejjani

**Comment by aanm** [comment]
packet.net for nightly builds were we could have scripts to run this once in a while in cloud prividers.

Regarding the proxy, we already have some runtime tests that do the proxy performance the problem is that those results are not processed (or compared against master).

**Comment by tgraf** [comment]
Superseded by quest to scale project
