### ISSUE TITLE
Implement `cilium ip metadata` command to introspect the identity metadata (IDMD) structure

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#18529]
## Proposal / RFE

As discussed in https://github.com/cilium/cilium/issues/17829#issuecomment-1012458724, it would be helpful to have a command that allows us to introspect the state of the [IDMD](https://github.com/cilium/cilium/blob/1de39dfd7b0455ce3a4deb4f68c453274e11ec3a/pkg/ipcache/metadata.go#L42) for the purposes of debugging the kube-apiserver policy matching feature (and more in the future as they utilize the IDMD).

**Comment by chowmean** [comment]
Hi, what I understand from this is command is needed to show the content of IDMD. If I am correct, can you please assign this to me? Also any more details would be great to start with. Thanks.

**Comment by chowmean** [comment]
Hi @christarazi  Can you look at these commits if I am going in correct direction. https://github.com/chowmean/cilium/commit/7918e5de9b72514a1f9b1fe4501cf8a4610d8a0d

What is left here is 

- Adding proper formatting to print the IDMETADATA information. 
- Documentation

Also what flags/options do we need to provide here.

**Comment by christarazi** [comment]
This is a good start. I would agree that formatting should be figured out and the documentation is auto-generated. When you have these changes, please open a PR and then we can discuss if there's a need for flags / options.

**Comment by chowmean** [comment]
@christarazi Added a PR https://github.com/cilium/cilium/pull/18637. Please take a look. Thanks!

**Comment by joestringer** [comment]
I think we probably need to do a bit more work on cleaning up the ipcache package to make the overall structure clearer before we expose more internal visibility into the state. This will still be quite important, it's just a little tough to figure out exactly how these changes should be made at this point.

It may turn out that implementing this will just be a matter of expanding the APIs used in `cilium ip list`.
