### ISSUE TITLE
Add CLI validation tests

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#1855]
As per comments on #1788 we should add CLI validation tests for things such as the BPF debug utilities.

**Comment by ianvernon** [comment]
We should have tests for each possible CLI command. Some of this might be covered already. Below are the following CLI commands available in Cilium:

- [ ] `cilium bpf ct flush {<endpoint ID>, global}`
- [ ] `cilium bpf endpoint list`
- [ ] `cilium bpf lb list`
- [ ] `cilium bpf policy  add <endpoint id> <identity>`
- [ ] `cilium bpf policy delete <endpoint id> <identity>`
- [ ] `cilium bpf policy list <id>`
- [ ] `cilium bpf policy list <id> -n`
- [ ] `cilium bpf tunnel list`
- [ ] `cilium config`
- [ ] `cilium config <key=value>` for all keys / possible values
- [ ] `cilium endpoint config <endpoint id> [<option>=(enable|disable) ...]` for all keys / possible values
- [ ] `cilium endpoint disconnect <id>`
- [ ] `cilium endpoint get ( <endpoint identifier> | -l <endpoint labels> )`
- [ ] `cilium endpoint labels <id> -a <labels to add> -d <labels to delete>`
- [ ] `cilium endpoint list`
- [ ] `cilium endpoint regenerate <id>`
- [ ] `cilium monitor`
- [ ] `cilium policy delete {--all, <id>}`
- [ ] `cilium policy get [<labels>]`
- [ ] `cilium policy trace` (this is covered a lot by unit tests, but still would be good to validate at least that the CLI works as expected for given user inputs)
- [ ] `cilium policy validate`
- [ ] `cilium policy wait`
- [ ] `cilium prefilter {delete, list, update}`
- [ ] `cilium service delete {--all, <id>}`
- [ ] `cilium service get <id>`
- [ ] `cilium service list`
- [ ] `cilium service update {backends, frontend, id, rev}`
- [ ] `cilium status`
- [ ] `cilium version`

**Comment by ianvernon** [comment]
The existing tests need to be audited to see what coverage exists currently.
