### ISSUE TITLE
docs: add section on minimum resource requirements

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#1857]
It would be useful to know for deployments for running cheap / small hosts.
Also would be great to know the rough numbers for deploying Cilium+kvstore and
without default ksvtore. Memory requirements for the agent?  How much CPU time does Cilium
need?

Related-to: #1851 (Cilium scale / stress testing plan)

**Comment by tgraf** [comment]
Blocked on #2029 to have a reproducible way of generating the load in nightly tests and exporting the required metrics
