### ISSUE TITLE
Add cilium to the list of network providers for kubeadm

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1860]
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by techcet** [comment]
Also update Section on "Verified HostPort CNI providers" (if applicable) on page:
https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm/

**Comment by ackerman80** [comment]
The PR has been submitted and I am working to get it approved https://github.com/kubernetes/website/pull/9806

**Comment by ackerman80** [comment]
Looks like there is a parallel effort https://github.com/kubernetes/website/pull/9889
