### ISSUE TITLE
DNS Requests failing to hit node-local-dns-cache (LRP appears to not address it)

### ISSUE THREAD

**Issue by itsthatriver** [cilium/cilium#18603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We're attempting to roll out Cilium 1.10 on all managed cloud k8s providers with settings that are as similar across clouds as possible, so we're testing with VXLAN, and generic IPAMs in order to limit differences. All application workloads currently work fine, but because we run batch jobs, we're highly sensitive to DNS bursts, and without node-local-dns-cache working we tend to run into problems with our central DNS.

We began to test node-local-dns-cache specifically in GKE with this set of config
```
helm template cilium cilium/cilium --version 1.11.0 \
  --namespace kube-system \
  --set ipam.mode=kubernetes \
  --set tunnel=vxlan \
  --set egressMasqueradeInterfaces=eth+ \
  --set nodeinit.enabled=true \
  --set nodeinit.reconfigureKubelet=true \
  --set nodeinit.removeCbrBridge=true \
  --set cni.binPath=/home/kubernetes/bin \
  --set hubble.tls.auto.method="cronJob" \
  --set hubble.listenAddress=":4244" \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
  --set upgradeCompatibility="1.9" \
  --set encryption.enabled=true \
  --set encryption.nodeEncryption=false \
  --set encryption.type=ipsec \
  --set prometheus.enabled=true \
  --set operator.prometheus.enabled=true \
  --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http}" \
  --set labels="k8s:io.kubernetes.pod.namespace k8s:k8s-app k8s:app k8s:name"
```

When we make requests to fetch public DNS results (e.g. `dig google.com`), we did not see the node local cache request counter increment.

We also tested with localredirectpolicy enabled (using the config from [here](https://raw.githubusercontent.com/cilium/cilium/v1.11/examples/kubernetes-local-redirect/node-local-dns-lrp.yaml)) and got the same results. Specifically, all of the `coredns_dns_requests_total` counters remained the same.

### Cilium Version

1.11.0

### Kernel Version

Linux version 5.4.144+ (builder@7d732a1aec13) (Chromium OS 12.0_pre408248_p20201125-r7 clang version 12.0.0 (/var/tmp/portage/sys-devel/llvm-12.0_pre408248_p20201125-r7/work/llvm-12.0_pre408248_p20201125/clang f402e682d0ef5598eeffc9a21a691b03e602ff58)) #1 SMP Sat Sep 25 09:56:01 PDT 2021

### Kubernetes Version

v1.21.6-gke.1500

### Sysdump

[cilium-sysdump-20220124-105037.zip](https://github.com/cilium/cilium/files/7928109/cilium-sysdump-20220124-105037.zip)

### Relevant log output

```shell
There don't appear to be any obvious logs related to this
```

### Anything else?

I did see [this issue](https://github.com/cilium/cilium/issues/15195), not totally clear if it's related or not. I tried to check the settings they were using there to see if there were differences I could apply to get the same results shown [here](https://github.com/cilium/cilium/issues/15195#issuecomment-790324741), but the link to apply yaml didn't show any of the actual config.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kkourt** [comment]
Thanks for the report!

Going over the sysdump, it seems to me that indeed DNS requests are forwarded to kube-dns (instead of going over the node-local-dns).

Could you add what is the output of `hubble-observe` for a client pod that performs DNS requests (see https://docs.cilium.io/en/v1.10/operations/troubleshooting/#observing-flows-of-a-specific-pod) as well as the output of `cilium monitor` for the corresponding endpoint (see https://docs.cilium.io/en/v1.10/contributing/development/debugging/#monitor-events).

**Comment by brb** [comment]
cc @aditighag

**Comment by aditighag** [comment]
Did you follow these instructions - https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache? Also, I don't see kube-proxy replacement being enabled in your helm config.

>We began to test node-local-dns-cache specifically in GKE with this set of config

AFAIK, you need to enable node-local dns plugin on GKE clusters, else GKE control plane deletes the manually deployed node-local dns pods. /cc @Weil0ng

**Comment by Weil0ng** [comment]
It seems like the node-local-dns pods are deployed in host network namespace? Can you confirm that? If so, please follow instructions here https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache to deploy node-local-dns pods and see it if resolves the problem.

**Comment by thejosephstevens** [comment]
> Could you add what is the output of hubble-observe for a client pod that performs DNS requests

```
Jan 25 20:20:55.466: default/my-shell:58407 -> kube-system/kube-dns-599484b884-7fbnl:53 to-stack FORWARDED (UDP)
Jan 25 20:20:55.469: default/my-shell:58407 <- kube-system/kube-dns-599484b884-7fbnl:53 to-endpoint FORWARDED (UDP)
Jan 25 20:21:07.844: default/my-shell:34621 -> kube-system/kube-dns-599484b884-7fbnl:53 to-stack FORWARDED (UDP)
Jan 25 20:21:07.845: default/my-shell:34621 <- kube-system/kube-dns-599484b884-7fbnl:53 to-endpoint FORWARDED (UDP)
```
> as well as the output of cilium monitor for the corresponding endpoint

```
-> stack flow 0x0 , identity 35195->17190 state new ifindex 0 orig-ip 0.0.0.0: 10.0.1.123:52770 -> 10.0.0.200:53 udp
level=info msg="Initializing dissection cache..." subsys=monitor
-> endpoint 1894 flow 0x0 , identity 17190->35195 state reply ifindex lxce4ac913d99eb orig-ip 10.0.0.200: 10.0.0.200:53 -> 10.0.1.123:52770 udp
-> stack flow 0x0 , identity 35195->17190 state new ifindex 0 orig-ip 0.0.0.0: 10.0.1.123:50997 -> 10.0.0.200:53 udp
-> endpoint 1894 flow 0x0 , identity 17190->35195 state reply ifindex lxce4ac913d99eb orig-ip 10.0.0.200: 10.0.0.200:53 -> 10.0.1.123:50997 udp
```

> Did you follow these instructions - https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache? Also, I don't see kube-proxy replacement being enabled in your helm config.

So I actually didn't realize the node local dns cache setup was different, but reading through that I'm seeing some of the changes, I'll go ahead and give that a try. As far as kube-proxy replacement, we're using `kube-proxy-replacement:  "probe"` (defaulted by helm). I briefly tried full (strict) kube-proxy replacement, but I ran into problems because that's not compatible with transparent encryption, which is one of the core features we wanted out of Cilium. At least it's not compatible [according to the docs](https://docs.cilium.io/en/v1.10/gettingstarted/kubeproxy-free/#limitations), the error it threw at runtime was a little more specific, from `daemon/cmd/kube_proxy_replacement.go#95`, IPSec can't be used with bpf nodeport. Do you have any clarity on whether LRP relies on full strict kube-proxy replacement?

I'll set up a test with an updated version of node-local-dns cache without host networking and see if that works.

**Comment by thejosephstevens** [comment]
So a couple issues, if I remove the node-local dns plugin from gke my pods aren't killed, I get errors like this on boot
```
listen tcp 169.254.20.10:28080: bind: cannot assign requested address
```
Initially these were complaining about a dummy stub-zone we define, but after removing that it just complained about binding on that address.

With the node-local-dns plugin in place it almost immediately resets changes to the DS config, so I can't change the node-local-dns daemonset to remove hostnetwork, modify the command line arguments, or add the cilium annotation for port 53. I did try changing the label `addonmanager.kubernetes.io/mode=Reconcile` to `addonmanager.kubernetes.io/mode= EnsureExists`, but it was also reset back by the system immediately.

Any ideas? I'm open to shifting from encapsulation to native routing if that might fix this, but it seems like this should work.

**Comment by Weil0ng** [comment]
If you are working with GKE's nodelocaldns addon, then no you cannot change its config without all changes being reconciled away, so there are 2 options:
- Using OSS Cilium, then deploy OSS nodelocaldns per the [instructions](https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache)
- Using GKE's bundled DPv2 + nodelocaldns addon

**Comment by thejosephstevens** [comment]
So I was able to get OSS nodelocaldns running but it doesn't work with custom stubZones because it fails to bind on the kube-dns IP
```
Listen: listen tcp 169.254.20.10:53: bind: cannot assign requested address
```

It's picking up upstream stubZones and producing a bind on the default local DNS IP
```
google.com:53 {
    errors
    cache 30
    bind 169.254.20.10 192.168.2.10
    forward . 8.8.8.8 4.2.2.2
}
```

I'll keep testing and see if I can find a way around this.

Before that though I'll figure out if LRP works with this setup (without stubZones) to at least address this specific issue, and open a separate issue if there's other problems that come up.

**Comment by aditighag** [comment]
>Do you have any clarity on whether LRP relies on full strict kube-proxy replacement?

LRP relies on socket-based load balancing. KPR=probe setting should be fine with your cluster to get node-local dns use case working with LRP - https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache.

```
$ cilium status --verbose
:
KubeProxyReplacement Details:
  Socket LB Protocols:    TCP, UDP

```

**Comment by thejosephstevens** [comment]
Alright, so I've gone back through, enabled LocalRedirectPolicy and followed the full localredirectpolicy directions for node-local-dns to the letter and I'm still not seeing dns request counts going up on the local cache pod.

For what it's worth I was able to get node-local-dns to run while there were upstream stubZones on coredns by changing to `-localip=0.0.0.0`, but I did change that back to `-localip=169.254.20.10,$KUBE_DNS_IP` for the test results I'm showing below. I also made sure to restart all pods involved to ensure everything was tracked.

They're all stuck at 1
```
root@my-shell:/# curl http://10.0.3.130:9253/metrics | grep coredns_dns_request_count_total
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP coredns_dns_request_count_total Counter of DNS requests made per zone, protocol and family.
# TYPE coredns_dns_request_count_total counter
coredns_dns_request_count_total{family="1",proto="udp",server="dns://0.0.0.0:53",zone="."} 1
coredns_dns_request_count_total{family="1",proto="udp",server="dns://0.0.0.0:53",zone="cluster.local."} 1
coredns_dns_request_count_total{family="1",proto="udp",server="dns://0.0.0.0:53",zone="in-addr.arpa."} 1
coredns_dns_request_count_total{family="1",proto="udp",server="dns://0.0.0.0:53",zone="ip6.arpa."} 1
```

For thoroughness sake I've added a new sysdump, observe, and monitor results. For each of these, I ran `dig google.com` and `nslookup api.default.svc.cluster.local`, both of which returned just fine in my test pod.

```
❯ kubectl exec -n kube-system cilium-7lg46 -- hubble observe --since 3m --pod default/my-shell
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), wait-for-node-init (init), clean-cilium-state (init)
Jan 28 03:36:09.727: default/my-shell:57635 -> kube-system/kube-dns-599484b884-5xnxc:53 to-stack FORWARDED (UDP)
Jan 28 03:36:09.728: default/my-shell:57635 <- kube-system/kube-dns-599484b884-5xnxc:53 to-endpoint FORWARDED (UDP)
Jan 28 03:36:09.728: default/my-shell:48787 -> kube-system/kube-dns-599484b884-5xnxc:53 to-stack FORWARDED (UDP)
Jan 28 03:36:09.729: default/my-shell:48787 <- kube-system/kube-dns-599484b884-5xnxc:53 to-endpoint FORWARDED (UDP)
Jan 28 03:36:09.729: default/my-shell:46482 -> kube-system/kube-dns-599484b884-5xnxc:53 to-stack FORWARDED (UDP)
Jan 28 03:36:09.730: default/my-shell:46482 <- kube-system/kube-dns-599484b884-5xnxc:53 to-endpoint FORWARDED (UDP)
Jan 28 03:36:09.730: default/my-shell:56749 -> kube-system/kube-dns-599484b884-5xnxc:53 to-stack FORWARDED (UDP)
Jan 28 03:36:09.734: default/my-shell:56749 <- kube-system/kube-dns-599484b884-5xnxc:53 to-endpoint FORWARDED (UDP)
Jan 28 03:36:09.734: default/my-shell:47732 -> kube-system/kube-dns-599484b884-5xnxc:53 to-stack FORWARDED (UDP)
Jan 28 03:36:09.737: default/my-shell:47732 <- kube-system/kube-dns-599484b884-5xnxc:53 to-endpoint FORWARDED (UDP)
Jan 28 03:36:09.737: default/my-shell:55108 -> kube-system/kube-dns-599484b884-5xnxc:53 to-stack FORWARDED (UDP)
Jan 28 03:36:09.738: default/my-shell:55108 <- kube-system/kube-dns-599484b884-5xnxc:53 to-endpoint FORWARDED (UDP)
Jan 28 03:36:14.082: default/my-shell:57620 -> kube-system/kube-dns-599484b884-5xnxc:53 to-stack FORWARDED (UDP)
Jan 28 03:36:14.085: default/my-shell:57620 <- kube-system/kube-dns-599484b884-5xnxc:53 to-endpoint FORWARDED (UDP)
```

```
level=info msg="Initializing dissection cache..." subsys=monitor
-> stack flow 0x0 , identity 57552->17190 state new ifindex 0 orig-ip 0.0.0.0: 10.0.3.88:50259 -> 10.0.2.228:53 udp
-> endpoint 3330 flow 0x0 , identity 17190->57552 state reply ifindex lxc48b007061457 orig-ip 10.0.2.228: 10.0.2.228:53 -> 10.0.3.88:50259 udp
-> stack flow 0x0 , identity 57552->17190 state new ifindex 0 orig-ip 0.0.0.0: 10.0.3.88:54660 -> 10.0.2.228:53 udp
-> endpoint 3330 flow 0x0 , identity 17190->57552 state reply ifindex lxc48b007061457 orig-ip 10.0.2.228: 10.0.2.228:53 -> 10.0.3.88:54660 udp
-> stack flow 0x0 , identity 57552->17190 state new ifindex 0 orig-ip 0.0.0.0: 10.0.3.88:33066 -> 10.0.2.228:53 udp
-> endpoint 3330 flow 0x0 , identity 17190->57552 state reply ifindex lxc48b007061457 orig-ip 10.0.2.228: 10.0.2.228:53 -> 10.0.3.88:33066 udp
-> stack flow 0x0 , identity 57552->17190 state new ifindex 0 orig-ip 0.0.0.0: 10.0.3.88:60324 -> 10.0.2.228:53 udp
-> endpoint 3330 flow 0x0 , identity 17190->57552 state reply ifindex lxc48b007061457 orig-ip 10.0.2.228: 10.0.2.228:53 -> 10.0.3.88:60324 udp
-> stack flow 0x0 , identity 57552->17190 state new ifindex 0 orig-ip 0.0.0.0: 10.0.3.88:50671 -> 10.0.2.228:53 udp
-> endpoint 3330 flow 0x0 , identity 17190->57552 state reply ifindex lxc48b007061457 orig-ip 10.0.2.228: 10.0.2.228:53 -> 10.0.3.88:50671 udp
-> stack flow 0x0 , identity 57552->17190 state new ifindex 0 orig-ip 0.0.0.0: 10.0.3.88:41389 -> 10.0.2.228:53 udp
-> endpoint 3330 flow 0x0 , identity 17190->57552 state reply ifindex lxc48b007061457 orig-ip 10.0.2.228: 10.0.2.228:53 -> 10.0.3.88:41389 udp
-> stack flow 0x0 , identity 57552->17190 state new ifindex 0 orig-ip 0.0.0.0: 10.0.3.88:49491 -> 10.0.2.228:53 udp
-> endpoint 3330 flow 0x0 , identity 17190->57552 state reply ifindex lxc48b007061457 orig-ip 10.0.2.228: 10.0.2.228:53 -> 10.0.3.88:49491 udp
```

[cilium-sysdump-20220127-193520.zip](https://github.com/cilium/cilium/files/7955509/cilium-sysdump-20220127-193520.zip)

**Comment by aditighag** [comment]
What's the output of `cilium lrp list` when run from the cilium pods? Have you tried tracing DNS packets to see if they are being sent to the node-local dns cache pods or not?

**Comment by Weil0ng** [comment]
I noticed the following in the agent log:
```
2022-01-27T15:47:15.860241015Z level=info msg="  --enable-local-redirect-policy='false'" subsys=daemon
```
Can you confirm how did you enable LRP? Seems like the config change was not picked up by agent, did you restart the agent after changing the config?

**Comment by thejosephstevens** [comment]
Restarting the cilium agents fixed it!!!! Thank you all so much for your help!

I'll do a bit more testing to verify that it works as expected, but given what I found about setting `-local-ip=0.0.0.0` in order to have this setup be compatible with private DNS zones I'd be happy to make a PR to update the yaml referenced in the docs to use that instead of `-localip=169.254.20.10,$KUBE_DNS_IP` in case that helps someone else who has to deal with private DNS servers from their clusters.

**Comment by aditighag** [comment]
Great to see that you were able to get the node-local dns use case working with LRP. Can we close this bug if your issue is fully resolved?

>but given what I found about setting -local-ip=0.0.0.0 in order to have this setup be compatible with private DNS zones I'd be happy to make a PR to update the yaml referenced in the docs to use that instead of -localip=169.254.20.10,$KUBE_DNS_IP

I don't think these instructions are relevant for the LRP-based node-local dns documentation.
