### ISSUE TITLE
kube-proxy in IPVS mode: pod-to-NodePort svc connectivity issue

### ISSUE THREAD

**Issue by rastislavs** [cilium/cilium#18610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In a cluster with Cilium + kube-proxy in IPVS mode, the following issue was discovered by running `cilium connectivity test`:

When a client pod in the cluster is connecting to a nodePort service via `<node-ip>:<NodePort>`, with the `<node-ip>` being the internal IP of the node where the client pod is running, the connection may or may not work:
- if the request is load-balanced to a pod running on the same node, it works,
- if the request is load-balanced to a pod running on a remote node, it does not work.

When tracing the non-working case (backend pod on a remote node), it seems that SYN packet leaves the client node via VXLAN overlay SNATed to the `<node-ip>` (not the IP on the `cilium_host` interface). Because of that, SYN-ACK reply from the backend node is forwarded back via the node underlay network (not via the VXLAN), which can cause the drop of the SYN+ACK packet in the underlay.
 
For detailed traces, please see https://github.com/kubermatic/kubermatic/issues/8767#issuecomment-1018614502

### Cilium Version

`cilium image (running): v1.11.0`

### Kernel Version

`Linux 5.11.0-1027-aws #30~20.04.1-Ubuntu SMP Thu Jan 13 11:46:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.21.8`

### Sysdump

[cilium-sysdump-20220125-101144.zip](https://github.com/cilium/cilium/files/7932151/cilium-sysdump-20220125-101144.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rastislavs** [comment]
Some iptables logs of a packet:
 - client pod IP `172.25.1.123`
 - node IP: `172.31.87.243` (nodeport: `30400`)
 - backend pod on another node: `172.25.0.56`

Log at the beggining of the `KUBE-NODE-PORT` chain:

```
Jan 24 14:58:44 ip-172-31-87-243 kernel: [14385.928918] ** KUBE-NODE-PORT **IN=lxca19824b42df7 OUT= MAC=26:8b:f3:6d:98:37:86:a9:4a:8a:45:02:08:00 SRC=172.25.1.123 DST=172.31.87.243 LEN=60 TOS=0x00 PREC=0
x00 TTL=63 ID=40942 DF PROTO=TCP SPT=55066 DPT=30400 WINDOW=62377 RES=0x00 SYN URGP=0 MARK=0x4e160f00
```

The packet is matching this rule (packet already has mark `0xf00`, `0x4000` is added here):
```
Chain KUBE-NODE-PORT (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
1        2   120 KUBE-MARK-MASQ  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* Kubernetes nodeport TCP port for masquerade purpose */ match-set KUBE-NODE-PORT-TCP dst
```

Log at the beggining of the `CILIUM_OUTPUT` chain (DNAT to backend pod IP already happened):
```
Jan 24 14:58:44 ip-172-31-87-243 kernel: [14385.928954] ** CILIUM_OUTPUT\ **IN= OUT=cilium_host SRC=172.25.1.123 DST=172.25.0.56 LEN=60 TOS=0x00 PREC=0x00 TTL=62 ID=40942 DF PROTO=TCP SPT=55066 DPT=80 WI
NDOW=62377 RES=0x00 SYN URGP=0 MARK=0x4e164f00
```

The packet is matching this rule (mark `0xf00` is replaced with `0xc00` here):
```
Chain CILIUM_OUTPUT (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
2     114K   26M MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match ! 0xe00/0xf00 mark match ! 0xd00/0xf00 mark match ! 0xa00/0xe00 /* cilium: host->any mark as from host */ MARK xset 0xc00/0xf00
```

Log at the beggining of the `CILIUM_POST_nat chain`:

```
Jan 24 14:58:44 ip-172-31-87-243 kernel: [14385.928962] ** CILIUM_POST_nat **IN=lxca19824b42df7 OUT=cilium_host MAC=26:8b:f3:6d:98:37:86:a9:4a:8a:45:02:08:00 SRC=172.25.1.123 DST=172.25.0.56 LEN=60 TOS=0
x00 PREC=0x00 TTL=62 ID=40942 DF PROTO=TCP SPT=55066 DPT=80 WINDOW=62377 RES=0x00 SYN URGP=0 MARK=0x4e164c00 
```

The packet is NOT matching any SNAT rule - sice the mark `0xf00` was changed to `0xc00` in `CILIUM_OUTPUT`, this rule is not matched:
```
Chain CILIUM_POST_nat (1 references)
num   pkts bytes target     prot opt in     out     source               destination         
5        0     0 SNAT       all  --  *      cilium_host  0.0.0.0/0            0.0.0.0/0            mark match 0xf00/0xf00 ctstate DNAT /* hairpin traffic that originated from a local pod */ to:172.25.1.2
45
```

Since the packet has mark `0x4000`, it will match the SNAT rule in `KUBE-POSTROUTING` (even though the src IP already is `172.25.1.123`):

```
Chain KUBE-POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    2   120 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK xor 0x4000
    2   120 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ random-fully
```

**Comment by rastislavs** [comment]
Given my previous comment, I was able to make this working with the following workaround:

1. Add `-m mark ! --mark 0xf00/0xf00` to the `cilium: host->any mark as from host` rule in `CILIUM_OUTPUT`, e.g.:

```
iptables -A CILIUM_OUTPUT -m mark ! --mark 0xe00/0xf00 -m mark ! --mark 0xd00/0xf00 -m mark ! --mark 0xa00/0xe00 -m mark ! --mark 0xf00/0xf00 -m comment --comment "cilium: host->any mark as from host" -j MARK --set-xmark 0xc00/0xf00
iptables -D CILIUM_OUTPUT -m mark ! --mark 0xe00/0xf00 -m mark ! --mark 0xd00/0xf00 -m mark ! --mark 0xa00/0xe00 -m comment --comment "cilium: host->any mark as from host" -j MARK --set-xmark 0xc00/0xf00
```

This will make sure that mark `0xf00` is not replaced with `0xc00` there.

2. Remove `-m conntrack --ctstate DNAT` from the `hairpin traffic that originated from a local pod` rule i n`CILIUM_POST_nat`, e.g.:

```
iptables -A CILIUM_POST_nat -o cilium_host -m mark --mark 0xf00/0xf00 -m comment --comment "hairpin traffic that originated from a local pod" -j SNAT --to-source 172.25.1.245
iptables -D CILIUM_POST_nat -o cilium_host -m mark --mark 0xf00/0xf00 -m conntrack --ctstate DNAT -m comment --comment "hairpin traffic that originated from a local pod" -j SNAT --to-source 172.25.1.245
```

I wonder if something along these lines could be a viable solution?

**Comment by kkourt** [comment]
Thank you for the detailed report!

CC: @brb @borkmann

**Comment by zjd0112** [comment]
+1, meet the same problem

**Comment by vitality411** [comment]
+1, facing the same problem

**Comment by brb** [comment]
Any reason why you don't use [Cilium's eBPF kube-proxy replacement](https://docs.cilium.io/en/v1.11/gettingstarted/kubeproxy-free/) instead of the kube-proxy with ipvs?

**Comment by vitality411** [comment]
We will switch to [Cilium's eBPF kube-proxy replacement](https://docs.cilium.io/en/v1.11/gettingstarted/kubeproxy-free/) because of this issue. But still kube-proxy with ipvs is supportet right?

**Comment by rastislavs** [comment]
OK, so it seems that the issue was caused by `rp_filter` settings. The upgrade triggered resetting of `net.ipv4.conf.all.rp_filter` to default (`2`) on the control plane nodes. It seems that it broke Cilium datapath until they restart. Since the cilium pods set it back to `0` when they start, restart of the cilium pods after the upgrade resolves the issue. 

Our workaround for that would be something like:
```
echo 'net.ipv4.conf.all.rp_filter = 0' > /etc/sysctl.d/99-override_cilium_rp_filter.conf
```

Note that the workaround for newer systemd versions mentioned in https://docs.cilium.io/en/stable/operations/system_requirements/#admin-system-reqs (overriding `net.ipv4.conf.lxc*.rp_filter = 0`) would not be sufficient in this case.

IMHO it would be nice to make `rp_filter` requirement more explicit in the documentation as it can break datapath in a way that is not easy to debug.

**Comment by rastislavs** [comment]
> We don't have any CI pipeline which would test Cilium with kube-proxy in the ipvs mode, so no guarantees.

As IPVS does not really seem to be supported, what about iptables kube-proxy mode? Is that supported / tested as an alternative to kube-proxy replacement?

**Comment by Rid** [comment]
> Any reason why you don't use [Cilium's eBPF kube-proxy replacement](https://docs.cilium.io/en/v1.11/gettingstarted/kubeproxy-free/) instead of the kube-proxy with ipvs?

An example why we cannot run kube-proxy replacement https://github.com/cilium/cilium/issues/21541

**Comment by Rid** [comment]
@brb could this be reopened? I am now hitting this issue when running an istio ingress gateway, when a pod in the cluster tries to connect to the gateway pod on another node, the connection fails.

We're forced to use IPVS mode due to https://github.com/cilium/cilium/issues/21541.

So at the moment it seems we can either break NFS, or break pod communication, neither is a great option.

**Comment by Rid** [comment]
> Given my previous comment, I was able to make this working with the following workaround:
> 
> 1. Add `-m mark ! --mark 0xf00/0xf00` to the `cilium: host->any mark as from host` rule in `CILIUM_OUTPUT`, e.g.:
> 
> ```
> iptables -A CILIUM_OUTPUT -m mark ! --mark 0xe00/0xf00 -m mark ! --mark 0xd00/0xf00 -m mark ! --mark 0xa00/0xe00 -m mark ! --mark 0xf00/0xf00 -m comment --comment "cilium: host->any mark as from host" -j MARK --set-xmark 0xc00/0xf00
> iptables -D CILIUM_OUTPUT -m mark ! --mark 0xe00/0xf00 -m mark ! --mark 0xd00/0xf00 -m mark ! --mark 0xa00/0xe00 -m comment --comment "cilium: host->any mark as from host" -j MARK --set-xmark 0xc00/0xf00
> ```
> 
> This will make sure that mark `0xf00` is not replaced with `0xc00` there.
> 
> 2. Remove `-m conntrack --ctstate DNAT` from the `hairpin traffic that originated from a local pod` rule in `CILIUM_POST_nat`, e.g.:
> 
> ```
> iptables -A CILIUM_POST_nat -o cilium_host -m mark --mark 0xf00/0xf00 -m comment --comment "hairpin traffic that originated from a local pod" -j SNAT --to-source 172.25.1.245
> iptables -D CILIUM_POST_nat -o cilium_host -m mark --mark 0xf00/0xf00 -m conntrack --ctstate DNAT -m comment --comment "hairpin traffic that originated from a local pod" -j SNAT --to-source 172.25.1.245
> ```
> 
> I wonder if something along these lines could be a viable solution?

I've confirmed that this fixes the issue, we could hack together a fix, would a better solution be to integrate these changes into cilium?

**Comment by rastislavs** [comment]
@Rid 
> I've confirmed that this fixes the issue, we could hack together a fix, would a better solution be to integrate these changes into cilium?

I would be happy to help with that if we had an ACK from some Cilium maintainer
