### ISSUE TITLE
Install cilium version 1.10.0 with calico already installed in cluster.

### ISSUE THREAD

**Issue by wkhno** [cilium/cilium#18638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened! I followed the instruction https://docs.cilium.io/en/stable/gettingstarted/cni-chaining-calico/ .
My cluster is build with kubeadm and has three nodes in cluster. I first deploy calico to it and then follow the instruction use helm install cilium. But I have only cilium-operator ready , do i need to taint my node "node.cilium.io/agent-not-ready=true:NoSchedule"? 

### Cilium Version

1.10.0 

### Kernel Version

Linux node1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Linux node3 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Linux node2 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

### Anything else?

![cilium status](https://user-images.githubusercontent.com/32003423/151317941-e37d8389-0e02-4899-8d84-408a0325e1e2.png)
this is the cilium status and I tried to describe or get pod -oyaml . Is mount success crucial to initialize cilium pod?
![kubectl describe pod with warning mount failure ](https://user-images.githubusercontent.com/32003423/151318302-4f150a4f-834e-4f9c-abcc-43db4ab36a44.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@wkhno please try with 1.11.1, the documentation that you have pointed it out is for 1.11.x, not for 1.10.0. Thank you
