### ISSUE TITLE
Inconsistent behavior of policy matching link-local address of node-local-dns

### ISSUE THREAD

**Issue by rastislavs** [cilium/cilium#18644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to modify the `pod-to-external-fqdn-allow-google-cnp` policy from [connectivity-check](https://github.com/cilium/cilium/tree/master/examples/kubernetes/connectivity-check) tests to allow connections to [node-local-dns](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) bound to link-local address `169.254.20.10:53` running in the host network namespace.

What I found out is that whether my policy works or not depends on the order in which the pods start:

- if the node-local-dns pod starts before the cilium pod, the following policy allowing CIDR `169.254.0.0/16` works,
- if the node-local-dns starts after the cilium pod, the following policy does not work. After I restart the cilium pod on the node, it starts working.

Policy:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pod-to-external-fqdn-allow-google-cnp
  labels:
    name: pod-to-external-fqdn-allow-google-cnp
    topology: any
    component: policy-check
    traffic: external
    quarantine: "false"
    type: autocheck
spec:
  endpointSelector:
    matchLabels:
      name: pod-to-external-fqdn-allow-google-cnp
  egress:
  - toFQDNs:
    - matchPattern: '*.google.com'
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
    toCIDR:
    - 169.254.0.0/16
    - fd00::/8
```

Steps to reproduce:
- Deploy a cluster with CIlium CNI, without node-local DNS
- AFTER Cilium pods are running, add node-local-dns daemonset that runs in the host network namesapce and binds to `169.254.20.10:53`
- In this case, the above mentioned policy does not allow connection to the node-local-dns:

```bash
# hubble observe --pod cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj
Jan 27 15:50:12.716: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:38346 <> 169.254.20.10:53 Policy denied DROPPED (UDP)
Jan 27 15:50:12.792: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:39429 <> 169.254.20.10:53 Policy denied DROPPED (UDP)


# cilium monitor --related-to 401
Policy verdict log: flow 0x0 local EP ID 401, remote ID host, proto 17, egress, action deny, match none, 172.25.1.159:59035 -> 169.254.20.10:53 udp
xx drop (Policy denied) flow 0x0 to endpoint 0, , identity 12828->host: 172.25.1.159:59035 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x0 local EP ID 401, remote ID host, proto 17, egress, action deny, match none, 172.25.1.159:59035 -> 169.254.20.10:53 udp
xx drop (Policy denied) flow 0x0 to endpoint 0, , identity 12828->host: 172.25.1.159:59035 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x0 local EP ID 401, remote ID host, proto 17, egress, action deny, match none, 172.25.1.159:53883 -> 169.254.20.10:53 udp
xx drop (Policy denied) flow 0x0 to endpoint 0, , identity 12828->host: 172.25.1.159:53883 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x0 local EP ID 401, remote ID host, proto 17, egress, action deny, match none, 172.25.1.159:53883 -> 169.254.20.10:53 udp
xx drop (Policy denied) flow 0x0 to endpoint 0, , identity 12828->host: 172.25.1.159:53883 -> 169.254.20.10:53 udp


# ip addr
29: nodelocaldns: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 3a:d8:82:97:d8:2b brd ff:ff:ff:ff:ff:ff
    inet 169.254.20.10/32 brd 169.254.20.10 scope global nodelocaldns
       valid_lft forever preferred_lft forever
```

Then restart the Cilium pod - without any changes, the policy starts working:
```bash
# hubble observe --pod cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj -f
Jan 27 15:54:30.366: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:54119 -> 169.254.20.10:53 L3-L4 REDIRECTED (UDP)
Jan 27 15:54:30.366: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:54119 -> 169.254.20.10:53 to-proxy FORWARDED (UDP)
Jan 27 15:54:30.367: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:54119 -> 169.254.20.10:53 to-proxy FORWARDED (UDP)
Jan 27 15:54:30.367: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:54119 -> 169.254.20.10:53 dns-request FORWARDED (DNS Query www.google.com.cilium-test.svc.cluster.local. A)
Jan 27 15:54:30.367: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:54119 -> 169.254.20.10:53 dns-request FORWARDED (DNS Query www.google.com.cilium-test.svc.cluster.local. AAAA)
Jan 27 15:54:30.372: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:54119 <- 169.254.20.10:53 dns-response FORWARDED (DNS Answer RCode: Non-Existent Domain TTL: 4294967295 (Proxy www.google.com.cilium-test.svc.cluster.local. AAAA))
Jan 27 15:54:30.372: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:54119 <- 169.254.20.10:53 to-endpoint FORWARDED (UDP)
Jan 27 15:54:30.373: cilium-test/pod-to-external-fqdn-allow-google-cnp-5ff4986c89-pm5zj:54119 <- 169.254.20.10:53 dns-response FORWARDED (DNS Answer RCode: Non-Existent Domain TTL: 4294967295 (Proxy www.google.com.cilium-test.svc.cluster.local. A))

# cilium monitor --related-to 401
Policy verdict log: flow 0x0 local EP ID 401, remote ID 16777217, proto 17, egress, action redirect, match L3-L4, 172.25.1.159:54053 -> 169.254.20.10:53 udp
-> proxy port 37761 flow 0x0 , identity 12828->unknown state new ifindex 0 orig-ip 0.0.0.0: 172.25.1.159:54053 -> 169.254.20.10:53 udp
-> proxy port 37761 flow 0x0 , identity 12828->unknown state established ifindex 0 orig-ip 0.0.0.0: 172.25.1.159:54053 -> 169.254.20.10:53 udp
-> Request dns from 401 ([k8s:io.kubernetes.pod.namespace=cilium-test k8s:name=pod-to-external-fqdn-allow-google-cnp k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-test k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default]) to 0 ([reserved:world]), identity 12828->2, verdict Forwarded DNS Query: www.google.com.cilium-test.svc.cluster.local. AAAA
-> Request dns from 401 ([k8s:io.kubernetes.pod.namespace=cilium-test k8s:name=pod-to-external-fqdn-allow-google-cnp k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-test k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default]) to 0 ([reserved:world]), identity 12828->2, verdict Forwarded DNS Query: www.google.com.cilium-test.svc.cluster.local. A
-> Response dns to 401 ([k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-test k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=cilium-test k8s:name=pod-to-external-fqdn-allow-google-cnp]) from 0 ([reserved:world]), identity 12828->2, verdict Forwarded DNS Proxy: www.google.com.cilium-test.svc.cluster.local. AAAA TTL: 4294967295 Answer: ''
-> endpoint 401 flow 0x0 , identity 16777217->12828 state reply ifindex lxcc7c4aaa47af9 orig-ip 169.254.20.10: 169.254.20.10:53 -> 172.25.1.159:54053 udp
-> Response dns to 401 ([k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-test k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=cilium-test k8s:name=pod-to-external-fqdn-allow-google-cnp]) from 0 ([reserved:world]), identity 12828->2, verdict Forwarded DNS Proxy: www.google.com.cilium-test.svc.cluster.local. A TTL: 4294967295 Answer: ''
```

### Cilium Version

`cilium image (running): v1.11.0`

### Kernel Version

`Linux 5.11.0-1027-aws #30~20.04.1-Ubuntu SMP Thu Jan 13 11:46:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.21.8`

### Sysdump

[cilium-sysdump-20220127-165230.zip](https://github.com/cilium/cilium/files/7951920/cilium-sysdump-20220127-165230.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Some initial observations - 

- Node-local dns is not deployed using [LRP](https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache). In case of LRP, there is no binding to `168.254`.

>if the node-local-dns pod starts before the cilium pod, the following policy allowing CIDR 169.254.0.0/16 works,
if the node-local-dns starts after the cilium pod, the following policy does not work. After I restart the cilium pod on the node, it starts working.

It's not entirely clear to me why the ordering of node-local dns pods matter as they are deployed in the host network namespace, and hence won't be managed by cilium.

**Comment by joestringer** [comment]
> > if the node-local-dns pod starts before the cilium pod, the following policy allowing CIDR 169.254.0.0/16 works,
> > if the node-local-dns starts after the cilium pod, the following policy does not work. After I restart the cilium pod on the node, it starts working.
> 
> It's not entirely clear to me why the ordering of node-local dns pods matter as they are deployed in the host network namespace, and hence won't be managed by cilium.

Agree. Here's what I would expect: Cilium starts up, it scans all of the devices on the system, and if any IP addresses are assigned to local devices, then it will consider those IPs to be "host", consider them as part of the cluster, exclude them from CIDR policy, and apply policy based on the host for traffic to/from those IP addresses.

If the IPs are not directly attached to devices on the system, I'd expect that Cilium should not consider them as host, so then the CIDR policy should apply. 

Here's the relevant code: https://github.com/cilium/cilium/blob/18512750ce0085eaf7c4760e29c6431241e8b517/daemon/cmd/datapath.go#L170-L187

**Comment by joestringer** [comment]
Related to the above, maybe `--exclude-local-address` should be used when deploying node-local DNS to ensure consistent behaviour?

**Comment by aanm** [comment]
Could this be related to https://github.com/cilium/cilium/issues/17839?

**Comment by mhulscher** [comment]
I encountered the same issue; where deploying node-local-dns with a bind on 169.254.20.10 on the hostNetwork would sometimes work, sometimes it wouldn't. I worked around this by deploying node-local-dns with the CiliumLocalRedirectPolicy, as per the docs, and adding a secondary CLRP to forward traffic destined for the legacy address of 169.254.20.10 to node-local-dns as well.

```yaml
---
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: kube-dns
      namespace: kube-system
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
      - port: "53"
        name: dns
        protocol: UDP
      - port: "53"
        name: dns-tcp
        protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: node-local-dns-legacy
  namespace: kube-system
spec:
  redirectFrontend:
    addressMatcher:
      ip: "169.254.20.10"
      toPorts:
        - port: "53"
          name: dns
          protocol: UDP
        - port: "53"
          name: dns-tcp
          protocol: TCP
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
      - port: "53"
        name: dns
        protocol: UDP
      - port: "53"
        name: dns-tcp
        protocol: TCP
```

**Comment by rastislavs** [comment]
OK, so it seems that there are two possible solutions here:
- use `--exclude-local-address` to get consistent behaviour,
- use `CiliumLocalRedirectPolicy` for node-local-dns instead of binding to a link-local address in the host namespace.

The first option seems to be just a workaround to me. I even think that instead of excluding, the link-local address of the node-local-dns should be rather included as a local address.

I am a bit hesitant to use LRP because it is still marked as a beta feature. And since our platform aims to support multiple CNIs, that would mean creating a special-case just for Cilium. But if that is the recommended solution for production use, I am willing to accept that.

**Comment by JBOClara** [comment]
Is there any activity on this issue ?

`cilium connectivity test` fail with node-local-dns and cilium v1.12 - k8s 1.22.11 - kops 1.24.0 + LRP

I'm using kops clusterSpec to set up nodelocaldns
https://github.com/kubernetes/kops/blob/v1.24.0/upup/models/cloudup/resources/addons/nodelocaldns.addons.k8s.io/k8s-1.12.yaml.template#L154-L157

Do we have to enable `spec.kubeDNS.nodeLocalDNS.forwardToKubeDNS` to true ?
 https://kops.sigs.k8s.io/releases/1.22-notes/#breacking-change-in-nodelocaldns

I've also tested this https://docs.cilium.io/en/stable/gettingstarted/local-redirect-policy/#node-local-dns-cache setup with LRP

**Comment by aditighag** [comment]
> I've also tested this https://docs.cilium.io/en/stable/gettingstarted/local-redirect-policy/#node-local-dns-cache setup with LRP
> 
> ```
> 
>   📄 No flows recorded during action http-to-one-one-one-one-0
>   📄 No flows recorded during action http-to-one-one-one-one-0
>   [.] Action [to-entities-world/pod-to-world/https-to-one-one-one-one-0: cilium-test/client-6488dcf5d4-nctjd (100.96.131.4) -> one-one-one-one-https (one.one.one.one:443)]
>   [.] Action [to-entities-world/pod-to-world/https-to-one-one-one-one-index-0: cilium-test/client-6488dcf5d4-nctjd (100.96.131.4) -> one-one-one-one-https-index (one.one.one.one:443)]
>   [.] Action [to-entities-world/pod-to-world/http-to-one-one-one-one-1: cilium-test/client2-5998d566b4-6n56m (100.96.131.212) -> one-one-one-one-http (one.one.one.one:80)]
>   ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://one.one.one.one:80" failed: command terminated with exit code 28
>   ℹ️  curl output:
>   curl: (28) Resolving timed out after 5000 milliseconds
> :0 -> :0 = 000
> ```
> 
> ```
> kubectl -n kube-system exec cilium-wnqqc -- cilium lrp list
> Defaulted container "cilium-agent" out of: cilium-agent, cilium-monitor, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
> LRP namespace   LRP name       FrontendType                Matching Service
> kube-system     nodelocaldns   clusterIP + all svc ports   kube-system/kube-dns
>                 |              100.64.0.10:53/UDP -> 10.134.156.194:53(kube-system/node-local-dns-hmps7),
>                 |              100.64.0.10:53/TCP -> 10.134.156.194:53(kube-system/node-local-dns-hmps7),
>                 |              100.64.0.10:9153/TCP ->
> ```


Does the connectivity test consistently fail? We've had flakes with the dns test in our CI.

**Comment by JBOClara** [comment]
Yes, they fail consistently.

**Comment by aditighag** [comment]
@JBOClara You don't need the hard-coded `169.254` address in node-local-dns.yaml if you are deploying with LRP. I would suggest following these exact instructions - https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache. 

>But I've got errors too on a test cluster with this installation

I didn't follow - did you follow the LRP guide, and run into errors? What are the errors?

**Comment by JBOClara** [comment]
> @JBOClara You don't need the hard-coded `169.254` address in node-local-dns.yaml if you are deploying with LRP. I would suggest following these exact instructions - https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache.
> 
> > But I've got errors too on a test cluster with this installation
> 
> I didn't follow - did you follow the LRP guide, and run into errors? What are the errors?

Yes, I tested both. There is error with https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache too.

It seems related to the bug about 169.254.20.10 labeled as world as described here https://github.com/cilium/cilium/issues/20055

**Comment by aditighag** [comment]
> > @JBOClara You don't need the hard-coded `169.254` address in node-local-dns.yaml if you are deploying with LRP. I would suggest following these exact instructions - https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache.
> > > But I've got errors too on a test cluster with this installation
> > 
> > 
> > I didn't follow - did you follow the LRP guide, and run into errors? What are the errors?
> 
> Yes, I tested both. There is error with https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#node-local-dns-cache too.
> 

For LRP deployment, you need to add `k8s-app: node-local-dns` to the connectivity test policy endpoint selector label.

**Comment by eminaktas** [comment]
> I think that it's fair to say that CiliumLocalRedirectPolicy is the intended way to use node-local-dns with Cilium today, so that path is probably the most reliable. I don't recall any known issues with that feature, but if the beta status is an issue then perhaps it's time for the community to revisit that classification and consider whether to promote it to GA.
> 
> Another thought, given that the behaviour changes depending on the order of running the hostNetwork pod... I'm assuming that the reason for this is that if you start the hostNetwork pod first, then it creates the virtual device, attaches this IP address, and this is all done in the host netns. Then Cilium starts up, detects the IPs in the host netns (including from this pod), and consider each IP as "host". If the ordering is the other way around, then the address isn't yet assigned when Cilium runs. Cilium doesn't find the address. Then presumably there is no trigger in Cilium to learn about the new address once the pod does eventually start up & assign the address.
> 
> So taking this thought further, another option beyond the above two would be to re-trigger the code that I linked above somehow. Perhaps either by subscribing to some Linux notification mechanism that would allow Cilium to learn about newly attached IP addresses, or alternatively perhaps by monitoring for hostNetwork pods deployed on the same node, and then triggering the logic from there just in case the hostNetwork pods do anything special. For the latter idea though, it could be a bit racy - there's no way to know when the node-local-dns pod assigns the address.

I just noticed that when XDP is enabled, Cilium identifies the node-local-dns IP as host. I put some of the resources of Cilium as you see below.

cillum-agent logs
```bash
cilium-dglzf cilium-agent level=info msg="  Local IPv4 addresses:" subsys=daemon
cilium-dglzf cilium-agent level=info msg="  - omited" subsys=daemon
cilium-dglzf cilium-agent level=info msg="  - omited" subsys=daemon
cilium-dglzf cilium-agent level=info msg="  - 169.254.25.10" subsys=daemon -> node-local-dns IP
```

```bash
root@benchmark-master:/home/cilium# cilium bpf endpoint list
IP ADDRESS        LOCAL ENDPOINT INFO
*omited-lines*
169.254.25.10:0   (localhost) -> node-local-dns IP
`
``

node-local-dns endpoint doesn't appear here.

```bash
root@benchmark-master:/home/cilium# cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                  IPv6   IPv4           STATUS
           ENFORCEMENT        ENFORCEMENT
124        Disabled           Disabled          4323       k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system          10.233.64.2    ready
                                                           k8s:io.cilium.k8s.policy.cluster=default
                                                           k8s:io.cilium.k8s.policy.serviceaccount=coredns
                                                           k8s:io.kubernetes.pod.namespace=kube-system
                                                           k8s:k8s-app=kube-dns
772        Disabled           Disabled          4          reserved:health                                                                     10.233.64.35   ready
1519       Disabled           Disabled          16924      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system          10.233.64.34   ready
                                                           k8s:io.cilium.k8s.policy.cluster=default
                                                           k8s:io.cilium.k8s.policy.serviceaccount=dns-autoscaler
                                                           k8s:io.kubernetes.pod.namespace=kube-system
                                                           k8s:k8s-app=dns-autoscaler
2107       Disabled           Disabled          1          k8s:node-role.kubernetes.io/control-plane                                                          ready
                                                           k8s:node-role.kubernetes.io/master
                                                           k8s:node.kubernetes.io/exclude-from-external-load-balancers
                                                           reserved:host
```


when XDP is disabled, node-local-dns IP doesn't appear in any of these sources. For both cases, BPF is enabled.

**Comment by JBOClara** [comment]
Connectivity test always fails

```
Flow Details
Timestamp
2022-11-20T17:22:45.497Z
Verdict
dropped
Drop reason
Policy denied
Traffic direction
egress
Source pod
client-594cbbdf44-b8w6n
Source identity
30407
Source labels
io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-test
io.cilium.k8s.policy.cluster=default
io.cilium.k8s.policy.serviceaccount=client
namespace=cilium-test
kind=client
name=client
Source IP
100.100.50.47
Destination identity
2
Destination labels
reserved:world
Destination IP
169.254.20.10
Destination port
53
```

Even with LRP setup https://docs.cilium.io/en/stable/gettingstarted/local-redirect-policy/#node-local-dns-cache

```
[=] Test [allow-all-except-world]
.......
  ℹ️  📜 Applying CiliumNetworkPolicy 'allow-all-except-world' to namespace 'cilium-test'..
  [-] Scenario [allow-all-except-world/pod-to-pod]
  [.] Action [allow-all-except-world/pod-to-pod/curl-0: cilium-test/client-594cbbdf44-b8w6n (100.100.50.47) -> cilium-test/echo-other-node-79767595bf-hvddd (100.98.237.232:8080)]
  [.] Action [allow-all-except-world/pod-to-pod/curl-1: cilium-test/client-594cbbdf44-b8w6n (100.100.50.47) -> cilium-test/echo-same-node-59d8df6bc7-nfzzg (100.100.50.28:8080)]
  [.] Action [allow-all-except-world/pod-to-pod/curl-2: cilium-test/client2-8484df99d-v6crg (100.100.50.27) -> cilium-test/echo-other-node-79767595bf-hvddd (100.98.237.232:8080)]
  [.] Action [allow-all-except-world/pod-to-pod/curl-3: cilium-test/client2-8484df99d-v6crg (100.100.50.27) -> cilium-test/echo-same-node-59d8df6bc7-nfzzg (100.100.50.28:8080)]
  [-] Scenario [allow-all-except-world/client-to-client]
  [.] Action [allow-all-except-world/client-to-client/ping-0: cilium-test/client-594cbbdf44-b8w6n (100.100.50.47) -> cilium-test/client2-8484df99d-v6crg (100.100.50.27:0)]
  [.] Action [allow-all-except-world/client-to-client/ping-1: cilium-test/client2-8484df99d-v6crg (100.100.50.27) -> cilium-test/client-594cbbdf44-b8w6n (100.100.50.47:0)]
  [-] Scenario [allow-all-except-world/pod-to-service]
  [.] Action [allow-all-except-world/pod-to-service/curl-0: cilium-test/client-594cbbdf44-b8w6n (100.100.50.47) -> cilium-test/echo-other-node (echo-other-node:8080)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://echo-other-node:8080" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Resolving timed out after 5000 milliseconds
:0 -> :0 = 000

  📄 No flows recorded during action curl-0
  📄 No flows recorded during action curl-0
  Pausing after action failure, press the Enter key to continue:
```
