### ISSUE TITLE
Include `cilium lrp list` in bugtool cmd output

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#18649]
It is currently missing from bugtool dumps. Would be handy to have it for issues like #18603.

**Comment by aditighag** [comment]
Already taken care of in this PR - https://github.com/cilium/cilium/pull/18563/commits/795239b23ee6d2048c56056602f4040ac63cf1ae. :)

**Comment by Weil0ng** [comment]
Awesome!
