### ISSUE TITLE
Expose BPF-map current and max size as prometheus metrics

### ISSUE THREAD

**Issue by mhulscher** [cilium/cilium#18646]
## Proposal

**Is your feature request related to a problem?**

When clusters grow the BPF maps may start filling up. I have not found an easy way of monitoring the state of these maps.

**Describe the solution you'd like**

Preferably the cilium-agent should expose a prometheus metric of each maps' max size and current size.

**Comment by aanm** [comment]
@mhulscher thanks for opening the GH issue. Cilium already provides `cilium_bpf_maps_virtual_memory_max_bytes` which contains the max memory usage of all bpf maps. Unfortunately, not all bpf map types allow to know what is the current memory usage.

**Comment by mhulscher** [comment]
That's too bad, it would make debugging issues like https://github.com/cilium/cilium/issues/18581 somewhat easier . It's kind of scary to me that cilium could stop working because of a resource limit being hit, and me not being able to monitor this.

**Comment by christarazi** [comment]
@mhulscher I think this exists via https://github.com/cilium/cilium/pull/14131. Does that not work for you?

**Comment by mhulscher** [comment]
@christarazi thank you for bringing this up. I believe that yes, this would help me. I don't know how I missed this. Consider this closed.

**Comment by alex-berger** [comment]
@christarazi Are you sure https://github.com/cilium/cilium/pull/14131 resp. `bpf_map_pressure` metric is working as expected? I am using Cilium version `1.11.1` with `metrics: +bpf_map_pressure` (in the `cilium-config` ConfigMap) but the `cilium_bpf_map_pressure` metric does not show up (there is no such metric reported/scraped).

**Comment by alex-berger** [comment]
> @christarazi Are you sure #14131 resp. `bpf_map_pressure` metric is working as expected? I am using Cilium version `1.11.1` with `metrics: +bpf_map_pressure` (in the `cilium-config` ConfigMap) but the `cilium_bpf_map_pressure` metric does not show up (there is no such metric reported/scraped).

My bad resp. bad documentation using `+cilium_bpf_map_pressure` (instead of `+bpf_map_pressure`) it works.
