### ISSUE TITLE
select nodes to expose NodePort service in kube-proxy free mode

### ISSUE THREAD

**Issue by alegrey91** [cilium/cilium#18641]
## Proposal / RFE

Add the possibility to select specific nodes to expose `NodePort` service.

**Is your feature request related to a problem?**
Suppose that we have a multi-tenant cluster, where each tenant has one or more dedicated worker nodes. If a tenant creates a NodePort service the ports will be opened in all the cluster nodes instead of just its own nodes. For security reasons, we wouldn't want to make it possible because other worker nodes are owned by other tenants. So they wouldn't want to share their ports with others.
Essentially we are developing a Kubernetes operator for the multi-tenancy (link here: [capsule](https://github.com/clastix/capsule)) and we would avoid the problem described above.

**Describe the solution you'd like**
A possible solution could be to create a multi-tenant oriented `NodePort` service, where each tenant can enable it on their worker nodes instead of all the cluster nodes.

**Comment by alegrey91** [comment]
Hi @aanm, any thought about our feature request? Is it a possible solution also for you?

**Comment by brb** [comment]
@alegrey91 Thanks for the proposal. How would you specify which node should expose the NodePort service?

**Comment by brb** [comment]
The approach sounds reasonable for me. Just one question - how would you prevent one tenant from provisioning services (and opening NodePort) on other tenant nodes with the label-based approach?

**Comment by alegrey91** [comment]
We would prevent this using a policy engine such as **Kiverno**, **OPA** or in our case [Capsule](https://capsule.clastix.io/docs/general/tutorial/#assign-nodes-pool).

**Comment by MaxFedotov** [comment]
That's would be a great feature for all multi-tenant clusters, because right now you had to disable nodePort services at all. One more thing that I could think about would be supporting not only nodePort services, but also clusterIP, because it will help to add more isolation

**Comment by alegrey91** [comment]
@brb can I ask you for the CFP template link, if you have it?

**Comment by alegrey91** [comment]
@brb, Here's the [CFP](https://docs.google.com/document/d/1NLMbDnDPYydxKQ7TmR2omP3cGWpjE2Ktyl72Sh8s3nk/edit?usp=sharing). It's set in suggesting mode for everybody, as requested.

**Comment by alwaysastudent** [comment]
@alegrey91 was this ever implemented? Is this a possible feature?

**Comment by alegrey91** [comment]
No, It was not @alwaysastudent
