### ISSUE TITLE
Add ESP to firewall requirements in documentation for IPSec enabled Cilium

### ISSUE THREAD

**Issue by jasonaliyetti** [cilium/cilium#18678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have Cilium deployed on EKS with some workers belonging to a fine grained AWS Security Group.  When I enabled IPSec in Cilium, requests to workloads on these nodes started to fail with timeouts.

At the end of the day, in addition to the rules called out [in the docs](https://docs.cilium.io/en/v1.11/operations/system_requirements/#firewall-rules), I needed to allow ESP traffic from other security groups [as suggested here](https://aws.amazon.com/blogs/security/creating-an-opportunistic-ipsec-mesh-between-ec2-instances/).  This should be added to the required firewall rules (for IPSec enabled Cilium deployments) listed in the docs. 

### Cilium Version

1.11.1

### Kernel Version

5.10

### Kubernetes Version

EKS 1.21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@jasonaliyetti would you like to submit a PR with the proposed changes? Thank you!

**Comment by SweetGeneral** [comment]
Hey, I'd like to take this up. But I don't know where to start. Could you please guide me or provide documentation to which i can refer to?

**Comment by Kikiodazie** [comment]
Hey @aanm, I would love to try my hands on this issue, can it be assigned to me?

**Comment by aanm** [comment]
> Hey @aanm, I would love to try my hands on this issue, can it be assigned to me?

@Kikiodazie sure

**Comment by Kikiodazie** [comment]
Thanks @aanm
