### ISSUE TITLE
Cilium install fails with Vagrant hosted Kubernetes cluster

### ISSUE THREAD

**Issue by dbrowne** [cilium/cilium#18670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

vagrant@mstr:~$ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         6 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet         cilium             Desired: 6, Ready: 6/6, Available: 6/6
Containers:       cilium-operator    Running: 1
                  cilium             Running: 6
Cluster Pods:     2/2 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2: 6
                  cilium-operator    quay.io/cilium/operator-generic:v1.11.1@sha256:977240a4783c7be821e215ead515da3093a10f4a7baea9f803511a2c2b44a235: 1
Errors:           cilium             cilium-w467l    unable to retrieve cilium status: unable to upgrade connection: pod does not exist
                  cilium             cilium-6kcgc    controller cilium-health-ep is failing since 33s (3x): Get "http://10.0.5.206:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-822m4    unable to retrieve cilium status: unable to upgrade connection: pod does not exist
                  cilium             cilium-f5zg7    unable to retrieve cilium status: unable to upgrade connection: pod does not exist
                  cilium             cilium-kbfx4    unable to retrieve cilium status: unable to upgrade connection: pod does not exist
                  cilium             cilium-v4wxb    unable to retrieve cilium status: unable to upgrade connection: pod does not exist

### Cilium Version

Version 1.11.1

### Kernel Version

5.13.0-27-generic #29-Ubuntu SMP Wed Jan 12 17:36:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20220131-052833.zip](https://github.com/cilium/cilium/files/7968360/cilium-sysdump-20220131-052833.zip)

### Relevant log output

```shell
vagrant@mstr:~$ kubectl get pods -n kube-system -o wide
NAME                           READY   STATUS    RESTARTS        AGE   IP           NODE   NOMINATED NODE   READINESS GATES
coredns-64897985d-qrfnc        0/1     Running   7 (3m34s ago)   16m   10.0.0.129   n4     <none>           <none>
coredns-64897985d-xkbr6        0/1     Running   7 (3m9s ago)    16m   10.0.2.195   n5     <none>           <none>
etcd-mstr                      1/1     Running   0               28m   10.0.2.15    mstr   <none>           <none>
kube-apiserver-mstr            1/1     Running   0               28m   10.0.2.15    mstr   <none>           <none>
kube-controller-manager-mstr   1/1     Running   0               28m   10.0.2.15    mstr   <none>           <none>
kube-flannel-ds-bgf8h          1/1     Running   0               25m   10.0.2.15    n4     <none>           <none>
kube-flannel-ds-dm7qp          1/1     Running   0               25m   10.0.2.15    n3     <none>           <none>
kube-flannel-ds-h786f          1/1     Running   0               25m   10.0.2.15    n2     <none>           <none>
kube-flannel-ds-ld4gp          1/1     Running   0               25m   10.0.2.15    n5     <none>           <none>
kube-flannel-ds-lm97w          1/1     Running   0               26m   10.0.2.15    mstr   <none>           <none>
kube-flannel-ds-tk6v6          1/1     Running   0               26m   10.0.2.15    n1     <none>           <none>
kube-proxy-29vhh               1/1     Running   0               28m   10.0.2.15    mstr   <none>           <none>
kube-proxy-4m5vq               1/1     Running   0               25m   10.0.2.15    n2     <none>           <none>
kube-proxy-4qr8n               1/1     Running   0               25m   10.0.2.15    n3     <none>           <none>
kube-proxy-8qt7p               1/1     Running   0               25m   10.0.2.15    n5     <none>           <none>
kube-proxy-kqvsj               1/1     Running   0               25m   10.0.2.15    n4     <none>           <none>
kube-proxy-lrpjf               1/1     Running   0               26m   10.0.2.15    n1     <none>           <none>
kube-scheduler-mstr            1/1     Running   0               28m   10.0.2.15    mstr   <none>           <none>

⌛ Waiting for Cilium to be installed and ready...
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         6 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 6, Ready: 6/6, Available: 6/6
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 6
                  cilium-operator    Running: 1
Cluster Pods:     2/2 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2: 6
                  cilium-operator    quay.io/cilium/operator-generic:v1.11.1@sha256:977240a4783c7be821e215ead515da3093a10f4a7baea9f803511a2c2b44a235: 1
Errors:           cilium             cilium-6kcgc    controller cilium-health-ep is failing since 28s (6x): Get "http://10.0.5.206:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-822m4    unable to retrieve cilium status: unable to upgrade connection: pod does not exist
                  cilium             cilium-f5zg7    unable to retrieve cilium status: unable to upgrade connection: pod does not exist
                  cilium             cilium-kbfx4    unable to retrieve cilium status: unable to upgrade connection: pod does not exist
                  cilium             cilium-v4wxb    unable to retrieve cilium status: unable to upgrade connection: pod does not exist
                  cilium             cilium-w467l    unable to retrieve cilium status: unable to upgrade connection: pod does not exist
↩️ Rolling back installation...
```

### Anything else?

Running Kubernetes in Vagrant initiated virtual machines on a baremetal linux server. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Disgruntled** [comment]
I think I am hitting the same problem, still working on it. My theory is that cilium is trying to assign the pod to the IP address that vagrant uses for it's vagrant management tasks - which is non-routable. Check out the ip in the address in the pods.

**Comment by Disgruntled** [comment]
Partial fix:  you need to modify /etc/systemd/system/kubelet.service.d/10-kubeadm.conf and add the line

Environment="KUBELET_EXTRA_ARGS=--node-ip=_YOUR_NODE_IP"

Kubeadm clusters want to grab the lowest IP possible to bind to by default, which is normally not the routeable node ip and is instead vagrant.

**Comment by Disgruntled** [comment]
After this is fixed on all k8s nodes, you'll need to delete all cilium node resources (kubectl delete cn --all) and then restart all cluster pods.

Then you should be golden.

cilium status may report that everything is good even if you don't do all that - don't believe it, in my experience today it still did route properly, but after killing all the pods it did no problemo.

**Comment by joamaki** [comment]
Given the workaround, does this seem like something that Cilium can or should try to work around or is it just specific to vagrant+kubeadm?

**Comment by noolius** [comment]
In the Vagrant+kubeadm case, it seems like considerable additional logic for Cilium to work around the IP associated with the default route. One might argue the argument parsed in `KUBELET_EXTRA_ARGS=--node-ip=` [implies](https://github.com/kubernetes/kubeadm/issues/203) [as much](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/). Other CNI plugins nod to this, e.g., Calico has [IP_AUTODETECTION_METHOD](https://projectcalico.docs.tigera.io/reference/node/configuration#ip-autodetection-methods)'s `interface=`.

**Comment by dbrowne** [comment]
@Disgruntled Thank you very much!  The solution worked.
