### ISSUE TITLE
Getting 'libbpf: load bpf program failed: Permission denied' error while starting cilium-agent

### ISSUE THREAD

**Issue by Jagman13** [cilium/cilium#18680]
Hi experts, 
I'm trying to run a cilium on my k8s cluster, I’m trying to run a cilium on my k8s cluster. I am seeing the following error while running cilium-agent.
Due to security and compliance, I have forked the official repo for cilium and have built it in-house and I'm deploying it on my host as a docker container. I did not make any changes to the source code

cilium verison - 1.11.0
k8s version - 1.18.10

```
level=warning msg="libbpf: failed to load program '__send_drop_notify'" subsys=datapath-loader
level=warning msg="libbpf: failed to load object '3107_next/bpf_lxc.o'" subsys=datapath-loader
level=warning msg="Unable to load program" subsys=datapath-loader

level=warning msg="JoinEP: Failed to load program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3107 error="Failed to load prog with tc: exit status 1" file-path=3107_next/bpf_lxc.o identity=4 ipv4= ipv6= k8sPodName=/ subsys=datapath-loader veth=lxc_health

level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3107 error="Failed to load prog with tc: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3107 file-path=3107_next_fail identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=21.501412ms bpfWaitForELF="4.93µs" bpfWriteELF=4.180564ms containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3107 error="Failed to load prog with tc: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ mapSync="3.565µs" policyCalculation="8.877µs" prepareBuild=1.986161ms proxyConfiguration="10.712µs" proxyPolicyCalculation="19.6µs" proxyWaitForAck=0s reason="retrying regeneration" subsys=endpoint total=32.545017ms waitingForCTClean=2.300702ms waitingForLock="1.318µs"
level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3107 error="Failed to load prog with tc: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint

level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 3107_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader

level=warning msg="libbpf: load bpf program failed: Permission denied" subsys=datapath-loader
```

It's failing while generating the cilium-health ep. Can someone please help to understand what is missing?

**Comment by vincentmli** [comment]
@Jagman13 cilium fail to load/attach bpf_lxc.o object file to the pod, any chance you can get sysdump with cilium-cli utility `cilium sysdump`? also enable debug in cilium agent like `kubectl edit configmap cilium-config -n kube-system` to set  `debug: "true"` and restart cilium agent with ` kubectl -n kube-system rollout restart ds/cilium`, wait till cilium agent is up and has error reported , then  `cilium sysdump`

**Comment by Jagman13** [comment]
@vincentmli - I am getting following while trying to get the sysdump

`Error: unknown command "sysdump" for "cilium"
Run 'cilium --help' for usage.
unknown command "sysdump" for "cilium"`

Also, I have a container image based on ol8 inside which i am trying to run cilium using following command - 
`./cilium-agent --enable-l7-proxy=true --kube-proxy-replacement=disabled --disable-envoy-version-check=true --enable-ipv6=false --enable-policy=always --k8s-kubeconfig-path=/kubeconfig`

Below are the few more logs that i could see after enabling `debug` for cilium-agent
`level=debug msg="Finished writing ELF" error="<nil>" new-elf-path=3198_next/bpf_lxc.o subsys=elf template-path=/var/run/cilium/state/templates/857f8cd272898a763e47955212f7a07f7e89354f5f9888b1c59293b3159ea162/bpf_lxc.o
level=debug msg="netlink: Replacing qdisc for lxc_health succeeded" subsys=datapath-loader
level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 3198_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
level=warning msg="libbpf: load bpf program failed: Permission denied" subsys=datapath-loader
level=warning msg="libbpf: -- BEGIN DUMP LOG ---" subsys=datapath-loader
level=warning msg="libbpf: " subsys=datapath-loader
level=warning msg="; int __send_drop_notify(struct __ctx_buff *ctx)" subsys=datapath-loader
level=warning msg="0: (bf) r6 = r1" subsys=datapath-loader
level=warning msg="; return ctx->cb[off];" subsys=datapath-loader
level=warning msg="1: (61) r1 = *(u32 *)(r6 +56)" subsys=datapath-loader
level=warning msg="2: (bf) r2 = r1" subsys=datapath-loader
level=warning msg="3: (67) r2 <<= 32" subsys=datapath-loader
level=warning msg="; if (error < 0)" subsys=datapath-loader
level=warning msg="4: (c7) r2 s>>= 63" subsys=datapath-loader
level=warning msg="5: (0f) r1 += r2" subsys=datapath-loader
level=warning msg="6: (af) r1 ^= r2" subsys=datapath-loader
level=warning msg="; return ctx->len;" subsys=datapath-loader
level=warning msg="7: (61) r3 = *(u32 *)(r6 +0)" subsys=datapath-loader
level=warning msg="; __notify_common_hdr(CILIUM_NOTIFY_DROP, error)," subsys=datapath-loader
level=warning msg="8: (61) r2 = *(u32 *)(r6 +68)" subsys=datapath-loader
level=warning msg="; return ctx->cb[off];" subsys=datapath-loader
level=warning msg="9: (61) r4 = *(u32 *)(r6 +48)" subsys=datapath-loader
level=warning msg="; return ctx->cb[off];" subsys=datapath-loader
level=warning msg="10: (61) r5 = *(u32 *)(r6 +52)" subsys=datapath-loader
level=warning msg="; return ctx->cb[off];" subsys=datapath-loader
level=warning msg="11: (61) r0 = *(u32 *)(r6 +60)" subsys=datapath-loader
level=warning msg="12: (b7) r7 = 0" subsys=datapath-loader
level=warning msg="; msg = (typeof(msg)) {" subsys=datapath-loader
level=warning msg="13: (63) *(u32 *)(r10 -4) = r7" subsys=datapath-loader
level=warning msg="last_idx 13 first_idx 0" subsys=datapath-loader
level=warning msg="regs=80 stack=0 before 12: (b7) r7 = 0" subsys=datapath-loader
level=warning msg="14: (63) *(u32 *)(r10 -8) = r0" subsys=datapath-loader
level=warning msg="15: (63) *(u32 *)(r10 -12) = r5" subsys=datapath-loader
level=warning msg="16: (63) *(u32 *)(r10 -16) = r4" subsys=datapath-loader
level=warning msg="17: (63) *(u32 *)(r10 -28) = r2" subsys=datapath-loader
level=warning msg="18: (18) r2 = 0xffff9a0a2b296d24" subsys=datapath-loader
level=warning msg="20: (6b) *(u16 *)(r10 -30) = r2" subsys=datapath-loader
level=warning msg="invalid size of register spill" subsys=datapath-loader
level=warning msg="processed 20 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="libbpf: -- END LOG --" subsys=datapath-loader
level=warning msg="libbpf: failed to load program '__send_drop_notify'" subsys=datapath-loader
level=warning msg="libbpf: failed to load object '3198_next/bpf_lxc.o'" subsys=datapath-loader
level=warning msg="Unable to load program" subsys=datapath-loader
level=warning msg="JoinEP: Failed to load program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 error="Failed to load prog with tc: exit status 1" file-path=3198_next/bpf_lxc.o identity=4 ipv4= ipv6= k8sPodName=/ subsys=datapath-loader veth=lxc_health
level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 error="Failed to load prog with tc: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Reverting endpoint changes after BPF regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Reverting proxy redirect removals" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Finished reverting proxy redirect removals" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Reverting xDS network policy update" subsys=envoy-manager
level=debug msg="preparing new cache transaction: upserting 0 entries, deleting 1 entries" subsys=xds xdsCachedVersion=307 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy
level=debug msg="deleting resource from cache" subsys=xds xdsCachedVersion=307 xdsResourceName=10.244.0.161 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy
level=debug msg="committing cache transaction and notifying of new version" subsys=xds xdsCachedVersion=307 xdsTypeURL=type.googleapis.com/cilium.NetworkPolicy
level=debug msg="Finished reverting xDS network policy update" subsys=envoy-manager
level=debug msg="Reverting proxy redirect additions" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Finished reverting proxy redirect additions" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Finished reverting endpoint changes after BPF regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 file-path=3198_next_fail identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="removing directory" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 directory=3198_next_fail endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="removing directory" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 directory=3198_next endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Completed endpoint regeneration with no pending regeneration requests" code=OK containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 endpointState=ready identity=4 ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=23.903978ms bpfWaitForELF="5.131µs" bpfWriteELF=3.002902ms containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 error="Failed to load prog with tc: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ mapSync="29.545µs" policyCalculation="55.987µs" prepareBuild=2.081235ms proxyConfiguration="7.645µs" proxyPolicyCalculation="58.878µs" proxyWaitForAck=0s reason="retrying regeneration" subsys=endpoint total=34.085098ms waitingForCTClean=2.403553ms waitingForLock=903ns
level=debug msg="Error regenerating endpoint: Failed to load prog with tc: exit status 1" code=Failure containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 endpointState=ready identity=4 ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=200
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="12.958µs" eventEnqueueWaitTime="10.958µs" eventHandlingDuration=34.332906ms eventType="*endpoint.EndpointRegenerationEvent" name=endpoint-3198 subsys=eventqueue
level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 error="Failed to load prog with tc: exit status 1" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Controller func execution time: 70.559819ms" name=endpoint-3198-regeneration-recovery subsys=controller uuid=c0515f6a-b7f6-4753-979f-cae155602b62
level=debug msg="Controller run failed" consecutiveErrors=1 error="regeneration recovery failed" name=endpoint-3198-regeneration-recovery subsys=controller uuid=c0515f6a-b7f6-4753-979f-cae155602b62
level=debug msg="received signal that regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Triggering endpoint regeneration due to retrying regeneration" code=OK containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 endpointState=waiting-to-regenerate identity=4 ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
level=debug msg="Dequeued endpoint from build queue" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Regenerating endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=3198 identity=4 ipv4= ipv6= k8sPodName=/ reason="retrying regeneration" startTime="2022-02-01 21:46:43.433065977 +0000 UTC m=+878.664019396" subsys=endpoint
`

**Comment by vincentmli** [comment]
> @vincentmli - I am getting following while trying to get the sysdump
> 
> `Error: unknown command "sysdump" for "cilium" Run 'cilium --help' for usage. unknown command "sysdump" for "cilium"`

sorry should have told you the link https://github.com/cilium/cilium-cli for cilium command


> Also, I have a container image based on ol8 inside which i am trying to run cilium using following command - `./cilium-agent --enable-l7-proxy=true --kube-proxy-replacement=disabled --disable-envoy-version-check=true --enable-ipv6=false --enable-policy=always --k8s-kubeconfig-path=/kubeconfig`
> 

I have not tried to run cilium agent this way myself, I usually deploy cilium through kubectl with cilium manifest yaml  generated from helm template or use helm. not sure your way of running cilium agent is relevant here for the issue though. 

> Below are the few more logs that i could see after enabling `debug` for cilium-agent `level=debug msg="Finished writing ELF" error="<nil>" new-elf-path=3198_next/bpf_lxc.o subsys=elf template-path=/var/run/cilium/state/templates/857f8cd272898a763e47955212f7a07f7e89354f5f9888b1c59293b3159ea162/bpf_lxc.o level=debug msg="netlink: Replacing qdisc for lxc_health succeeded" subsys=datapath-loader level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 3198_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader level=warning msg="libbpf: load bpf program failed: Permission denied" subsys=datapath-loader level=warning msg="libbpf: -- BEGIN DUMP LOG ---" subsys=datapath-loader level=warning msg="libbpf: " subsys=datapath-loader level=warning msg="; int __send_drop_notify(struct __ctx_buff *ctx)" subsys=datapath-loader level=warning msg="0: (bf) r6 = r1" subsys=datapath-loader level=warning msg="; return ctx->cb[off];" subsys=datapath-loader level=warning msg="1: (61) r1 = *(u32 *)(r6 +56)" subsys=datapath-loader level=warning msg="2: (bf) r2 = r1" subsys=datapath-loader level=warning msg="3: (67) r2 <<= 32" subsys=datapath-loader level=warning msg="; if (error < 0)" subsys=datapath-loader level=warning msg="4: (c7) r2 s>>= 63" subsys=datapath-loader level=warning msg="5: (0f) r1 += r2" subsys=datapath-loader level=warning msg="6: (af) r1 ^= r2" subsys=datapath-loader level=warning msg="; return ctx->len;" subsys=datapath-loader level=warning msg="7: (61) r3 = *(u32 *)(r6 +0)" subsys=datapath-loader level=warning msg="; __notify_common_hdr(CILIUM_NOTIFY_DROP, error)," subsys=datapath-loader level=warning msg="8: (61) r2 = *(u32 *)(r6 +68)" subsys=datapath-loader level=warning msg="; return ctx->cb[off];" subsys=datapath-loader level=warning msg="9: (61) r4 = *(u32 *)(r6 +48)" subsys=datapath-loader level=warning msg="; return ctx->cb[off];" subsys=datapath-loader level=warning msg="10: (61) r5 = *(u32 *)(r6 +52)" subsys=datapath-loader level=warning msg="; return ctx->cb[off];" subsys=datapath-loader level=warning msg="11: (61) r0 = *(u32 *)(r6 +60)" subsys=datapath-loader level=warning msg="12: (b7) r7 = 0" subsys=datapath-loader level=warning msg="; msg = (typeof(msg)) {" subsys=datapath-loader level=warning msg="13: (63) *(u32 *)(r10 -4) = r7" subsys=datapath-loader level=warning msg="last_idx 13 first_idx 0" subsys=datapath-loader level=warning msg="regs=80 stack=0 before 12: (b7) r7 = 0" subsys=datapath-loader level=warning msg="14: (63) *(u32 *)(r10 -8) = r0" subsys=datapath-loader level=warning msg="15: (63) *(u32 *)(r10 -12) = r5" subsys=datapath-loader level=warning msg="16: (63) *(u32 *)(r10 -16) = r4" subsys=datapath-loader level=warning msg="17: (63) *(u32 *)(r10 -28) = r2" subsys=datapath-loader level=warning msg="18: (18) r2 = 0xffff9a0a2b296d24" subsys=datapath-loader level=warning msg="20: (6b) *(u16 *)(r10 -30) = r2" subsys=datapath-loader level=warning msg="invalid size of register spill" subsys=datapath-loader level=warning msg="processed 20 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0" subsys=datapath-loader level=warning subsys=datapath-loader level=warning msg="libbpf: -- END LOG --" 

`"invalid size of register spill" ` is not good, but I don't know what the root cause is, someone with more knowledge on this might know, having cilium sysdump would help to see your cilium agent configuration

**Comment by vincentmli** [comment]
> `"invalid size of register spill" ` is not good, but I don't know what the root cause is, someone with more knowledge on this might know, having cilium sysdump would help to see your cilium agent configuration

@Jagman13, I think this might be a bug, it appears you did not open this issue with bug label which might bring attention to cilium dev community, CC experts @pchaigno @brb @borkmann, sorry about that guys :-)

**Comment by pchaigno** [comment]
> Due to security and compliance, I have forked the official repo for cilium and have built it in-house and I'm deploying it on my host as a docker container.

Could you detail the steps you followed to do this?

**Comment by Jagman13** [comment]
@vincentmli Is there any file location where I can find the logs for sysdump. These must be getting stored somewhere. I cannot run the cilium-cli. 

@pchaigno 
1. I cloned the cilium official repo & build it using an in-house build tool. I didn't make any changes to the code here. 
2.  I created a container with OL8 based image.
3.  The host on which I am running this container has the following Linux kernel version

`5.4.17-2136.302.6.1.el7uek.x86_64`

and Linux distribution 
`cat /etc/oracle-release 
Oracle Linux Server release 7.9
`
command to run the container 

`docker run --network="host" -it --privileged --cap-add=ALL --volume=/etc/oci-pki:/etc/oci-pki 0a2d2712f10e /bin/sh`

4. As my image is OL8 based - Linux distribution inside the image is 
`Oracle Linux Server release 8.5`

5. Inside this container - I am running the following command to start the agent

`./cilium-agent --enable-l7-proxy=true --kube-proxy-replacement=disabled --disable-envoy-version-check=true --enable-ipv6=false --enable-policy=always --k8s-kubeconfig-path=/kubeconfig`

**Comment by vincentmli** [comment]
> @vincentmli Is there any file location where I can find the logs for sysdump. These must be getting stored somewhere. I cannot run the cilium-cli.

if you installed the cilium-cli, then run cilium sysdump, the command will show you where the sysdump zip, for example:
```
# cilium sysdump
🔍 Collecting Kubernetes nodes
.....CUT....
🗳 Compiling sysdump
✅ The sysdump has been saved to /root/cilium-sysdump-20220202-124126.zip
```
since you have some kind of special setup, not sure if you can run cilium sysdump, but worth giving it  a try

**Comment by pchaigno** [comment]
> I cloned the cilium official repo & build it using an in-house build tool.

Cilium relies on several specific dependencies (iproute2, libbpf, etc.), so I'm wondering which versions of those dependencies you used and how you built them.

**Comment by Jagman13** [comment]
I have installed every dependency inside the image & then run make commands to build it. 

Snippet from my Dockerfile 

`COPY . /cilium

RUN dnf -y update && \
    dnf -y install make gcc gcc-c++ rpm-build git llvm-toolset bpftool iptables iproute-tc ipset

RUN yum -y install elfutils-libelf-devel

RUN cd /cilium &&  \
    make all && \
    make install`
    
iproute info 
`Name         : iproute
Version      : 5.12.0
Release      : 4.0.1.el8
Architecture : x86_64
Size         : 2.3 M
Source       : iproute-5.12.0-4.0.1.el8.src.rpm
Repository   : @System
From repo    : ol8-yum-remote-virtual
Summary      : Advanced IP routing and network device configuration tools
URL          : http://kernel.org/pub/linux/utils/net/iproute2/
License      : GPLv2+ and Public Domain
Description  : The iproute package contains networking utilities (ip and rtmon, for example)
             : which are designed to use the advanced networking capabilities of the Linux
             : kernel.
`

```
libbpf-0.4.0-1.el8.x86_64
bpftool-4.18.0-348.12.2.el8_5.x86_64
```

```
sh-4.4# clang --version
clang version 12.0.1 (Red Hat 12.0.1-4.0.1.module+el8.5.0+20428+2b4ecd47)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by vincentmli** [comment]
@Jagman13 since you did not mention how you run cilium operator that cilium agent relies on for CRD resources, I assume you didn't run cilium operator. let me suggest alternative that I usually run my custom build cilium image based on https://docs.cilium.io/en/v1.11/contributing/development/images/

run `make dev-docker-image` to generate the cilium-agent image, run `make docker-operator-generic-image` to generate the cilium-operator image, then either upload the image to your local container image registry or to docker hub or to `quay.io` if you have account.  then use `helm template` according to https://docs.cilium.io/en/v1.11/gettingstarted/k8s-install-helm/ to enable/disable cilium agent options  to create a manifest yaml file, change the `image` location in the manifest yaml file to your image in your local registry or docker hub or quay.io to match the image tag you build locally and uploaded, then kubectl apply -f <the manifest yaml file>, then you should have your own cilium agent image and cilium operator running in your cluster, I felt you were missing something in your way of deployment :-).

**Comment by Jagman13** [comment]
@vincentmli - Its able to get the CRD information. 

Cilium operator is running on master node. I am running it using the cilium-operator cli.

I could see the logger saying "`level=info msg=" All Cilium CRDs have been found and are available" subsys=k8s"` 

Daemon gets initialized as well. 

```
level=info msg="Launching Cilium health daemon" subsys=daemon
level=info msg="Datapath signal listener running" subsys=signal
level=info msg="Launching Cilium health endpoint" subsys=daemon
level=info msg="Started healthz status API server" address="127.0.0.1:9876" subsys=daemon
level=info msg="Initializing Cilium API" subsys=daemon
level=info msg="Daemon initialization completed" bootstrapTime=3.779789839s subsys=daemon
```

**Comment by vincentmli** [comment]
@Jagman13   I suggest the alternative way is that you can `make dev-docker-image` on your local build host environment and publish the image somewhere like docker hub, so I could deploy your image in my local lab to see if I can use the same image to reproduce your issue, I do not have oracle linux server host, but I can deploy your image on centos host, if I can't reproduce the issue on centos host with your image, it may relate to oracle linux kernel or something, it is easier for us to isolate the problem

**Comment by Jagman13** [comment]
@vincentmli I don't think i will be able to share the image due to security concerns. Is there any other alternative option for us

**Comment by vincentmli** [comment]
> @vincentmli I don't think I will be able to share the image due to security reasons. Is there any other alternative option for us?

you could remove any potential security info that could be contained in the image before you build the image, I am wondering though how `make dev-docker-image` with nothing changed in cilium from upstream would contain security info, I guess you know better than me :)
