### ISSUE TITLE
cilium on k3s, multi-server nodes can't communicate with master - TLS handshake error

### ISSUE THREAD

**Issue by asloan7** [cilium/cilium#18709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Installing k3s with multiple server nodes (3), the master will come up but the others can't reach it, with an error like:
"k3s[455828]: time="2022-02-01T22:58:40.763705554Z" level=info msg="Cluster-Http-Server 2022/02/01 22:58:40 http: TLS handshake error from 172.31.87.192:54470"

Single node works with cilium.
Multi-server nodes works with default k3s networking.

"journalctl -u k3s, systemctl status k3s -l" shows a lot of other possible hints, like:
"level=info msg="Cluster-Http-Server 2022/02/02 14:46:41 http: TLS handshake error from 172.31.19.107:55610: remote error: tls: bad certificate"

----
Install:
First server went fine, command: 
sudo curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.20.15+k3s1" K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC=" --disable traefik --flannel-backend=none --disable-network-policy --cluster-init" sh -
curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
cilium install
cilium status --wait
sleep 30
kubectl get all -A -o wide

Second (and third) installed fine, but can't talk to first to join cluster:
sudo curl -sfL https://get.k3s.io/ | INSTALL_K3S_VERSION=v1.20.15+k3s1 K3S_KUBECONFIG_MODE=644 K3S_TOKEN=...::server:... K3S_URL=https://172.31.1.97:6443/ INSTALL_K3S_EXEC="server --disable traefik" sh -

nc -z -v 172.31.1.97 6443
Ncat: Connected to 172.31.1.97:6443.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.

For laughs I tried copying the KUBECONFIG over to the 2nd server node and changing the IP to the master 172.31.1.97 and doing a "cilium install" there and got:
ℹ️  using Cilium version "v1.11.1"
🔮 Auto-detected cluster name: default
🔮 Auto-detected IPAM mode: cluster-pool
🔑 Found CA in secret cilium-ca
🔑 Generating certificates for Hubble...
↩️ Rolling back installation...
Error: Unable to install Cilium: unable to create secret kube-system/hubble-server-certs: secrets "hubble-server-certs" already exists

### Cilium Version

v1.11.1

### Kernel Version

Tried on AWS AmazonLinux2 and Ubuntu 18.04

AWS AmazonLinux2: uname -a
Linux ip-172-31-1-97 4.14.248-189.473.amzn2.x86_64 #1 SMP Mon Sep 27 05:52:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 18.04: uname -a
Linux ip-172-31-7-184 5.4.0-1060-aws #63~18.04.1-Ubuntu SMP Mon Nov 15 14:31:31 UTC 2021 x86_64

### Kubernetes Version

v1.20.15+k3s1

### Sysdump

Would have to review for possible redactions first.

But (no hubble, clustermesh)
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [10] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource (get ciliumegressnatpolicies.cilium.io)
⚠️ [11] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)

### Relevant log output

```shell
"k3s[455828]: time="2022-02-01T22:58:40.763705554Z" level=info msg="Cluster-Http-Server 2022/02/01 22:58:40 http: TLS handshake error from 172.31.87.192:54470"

journalctl -u k3s
 shows a lot of other possible hints, like:
"level=info msg="Cluster-Http-Server 2022/02/02 14:46:41 http: TLS handshake error from 172.31.19.107:55610: remote error: tls: bad certificate"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joamaki** [comment]
The errors are not from Cilium, so this might be specific to k3s. Perhaps related issue: https://github.com/k3s-io/k3s/issues/1442?

**Comment by asloan7** [comment]
For posterity, got this working (on ubuntu 20.04, k3s 1.22.8, cilium 1.11.3) and was really to do with starting up the additional "server" nodes with the exact same startup parameters as the initial node - it doesn't get params from communicating with the first node (even tho you do supply URL and token) as I had assumed.
