### ISSUE TITLE
support BGP configuration reloading

### ISSUE THREAD

**Issue by thirdeyenick** [cilium/cilium#18705]
## Proposal / RFE

We are already using metalLB in our clusters to announce IPs for services of type loadbalancer via BGP. As we are also using cilium for networking in our Kubernetes clusters, we evaluated if we can move the BGP part to cilium, too. As metalLB does [not yet support IPAMs](https://github.com/metallb/metallb/issues/157), we wrote a reconciler which dynamically manages the content of metalLBs configmap (adding/removing IPs there). MetalLB reloads the config on change of the conifgured configMap.

We noticed that cilium only [reads the metalLB config on start](https://github.com/cilium/cilium/blob/22757592c111cc44128f3bb19a7103324260ad4f/pkg/bgp/speaker/metallb.go#L73) and so doesn't pick up config changes.

Would it be possible to support config reloading during runtime?

**Describe the solution you'd like**

Cilium reloads the metalLB configuration on change or periodically

**Comment by cyclinder** [comment]
hi, I want to working on this, Can someone give me some code pointers on where to start?

**Comment by wkhno** [comment]
Hi，I wonder BGP network is this a mode of underlay network?

**Comment by brb** [comment]
@dylandreimerink @ldelossa is it still relevant?

**Comment by ldelossa** [comment]
Unless the community contributes this feature, we are focusing on the `BGP Control Plane` feature set introduced in v1.11. 
This feature set already supports dynamic configuration updates via Kubernetes CRDs.
