### ISSUE TITLE
Host network broken after one of the underlying interfaces of a bond goes down

### ISSUE THREAD

**Issue by pothos** [cilium/cilium#18706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On Equinix Metal the network setup is a bond of two NICs using LACP.
When Cilium is used as CNI for Kubernetes on Flatcar Container Linux, and one of the two NIC interfaces goes down, the host network is broken and remains broken even if the underlying interface goes up again.

The network looks normal but `ping 1.1` leads to no outgoing packets visible in `tcpdump -i bond0` (ping reports 100% packet loss) and `ping 127.0.0.1` leads to `ping: sendmsg: Operation not permitted`.

We could not restore the network even after terminating the Pods and kubelet on the node, flushing nft and deleting the Cilium interfaces (maybe BPF programs are still loaded and not cleaned up?)

IPv6 is not affected, `ping6 2606:4700:4700::1111` works.

### Cilium Version

1.9, 1.10, 1.11 

### Kernel Version

from 5.10.52 to 5.10.84

### Kubernetes Version

1.22

### Sysdump

```
🔍 Collecting Kubernetes nodes
failed to create sysdump collector: failed to collect Kubernetes nodes: Get "https://136.144.49.47:6443/api/v1/nodes": dial tcp 136.144.49.47:6443: i/o timeout
```

### Relevant log output

Kernel
```
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status down for interface, disabling it in 200 ms
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status down for interface, disabling it in 200 ms
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status down for interface, disabling it in 200 ms
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status down for interface, disabling it in 200 ms
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): invalid new link 1 on slave
Feb 04 15:50:06 kernel: mlx5_core 0000:02:00.0: modify lag map port 1:2 port 2:2
Feb 04 15:50:06 kernel: bond0: (slave enp2s0f0np0): link status definitely down, disabling slave
Feb 04 15:51:09 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): lxc_health: link becomes ready
Feb 04 15:51:10 kernel: lxc_health: Caught tx_queue_len zero misconfig
Feb 04 15:51:33 kernel: mlx5_core 0000:02:00.0 enp2s0f0np0: Link down
Feb 04 15:51:33 kernel: mlx5_core 0000:02:00.0 enp2s0f0np0: Link up
Feb 04 15:51:33 kernel: bond0: (slave enp2s0f0np0): link status up again after 200 ms
Feb 04 15:51:33 kernel: bond0: (slave enp2s0f0np0): link status definitely up, 10000 Mbps full duplex
Feb 04 15:51:35 kernel: mlx5_core 0000:02:00.0: modify lag map port 1:1 port 2:2
```

### Anything else?

Flatcar releases 2905.x.y to 3033.x.y are affected, running systemd from 247 to 249 (maybe relevant because systemd-networkd is used)

Flatcar releases 2764.x.y are not affected (kernel 5.10.43, systemd 247)

Reproduce it by provisioning an Equinix Metal machine with Flatcar Stable (used `c3.small.x86`).
Ensure it is on the latest version:

```
update_engine_client -update
sudo rm -f /etc/systemd/system/containerd.service.d/10-use-cgroupfs.conf
sudo sed -i 's/systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller//' /usr/share/oem/grub.cfg
sudo systemctl reboot
```

Set up a one-node Cilium cluster, using the script contents at the end:

```
sudo ./install.sh
```

Then, this action is valid and should not any harm, but now does:
```
sudo ip link set enp2s0f0np0 down
```
(and `sudo ip link set enp2s0f0np0 up` does not help)

The `install.sh` script used above:
```
#!/bin/bash

set -xe

systemctl enable --now docker
modprobe br_netfilter

cat <<EOF | tee /etc/modules-load.d/k8s.conf
br_netfilter
EOF

cat <<EOF | tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system

CNI_VERSION="v0.8.2"
CRICTL_VERSION="v1.17.0"
RELEASE_VERSION="v0.4.0"
DOWNLOAD_DIR=/opt/bin
RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"

mkdir -p /opt/cni/bin
mkdir -p /etc/systemd/system/kubelet.service.d

curl() {
	command curl -sSfL "$@"
}

curl "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-linux-amd64-${CNI_VERSION}.tgz" | tar -C /opt/cni/bin -xz
curl "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C $DOWNLOAD_DIR -xz
curl "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | tee /etc/systemd/system/kubelet.service
curl "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | tee /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
curl --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}

curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
sudo tar xzvfC cilium-linux-amd64.tar.gz /opt/bin
rm cilium-linux-amd64.tar.gz{,.sha256sum}

chmod +x {kubeadm,kubelet,kubectl}
mv {kubeadm,kubelet,kubectl} $DOWNLOAD_DIR/

systemctl enable --now kubelet
#systemctl status kubelet

cat <<EOF | tee kubeadm-config.yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
networking:
  podSubnet: "192.168.254.0/24"
EOF

# For explicit cgroupdriver selection
# ---
# kind: KubeletConfiguration
# apiVersion: kubelet.config.k8s.io/v1beta1
# cgroupDriver: systemd

# For containerd
# apiVersion: kubeadm.k8s.io/v1beta2
# kind: InitConfiguration
# nodeRegistration:
#  criSocket: "unix:///run/containerd/containerd.sock

export PATH=$PATH:$DOWNLOAD_DIR

kubeadm config images pull
kubeadm init --config kubeadm-config.yaml

mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.9.4/install/kubernetes/quick-install.yaml

kubectl taint nodes --all node-role.kubernetes.io/master-
kubectl get pods -A
kubectl get nodes -o wide

kubectl apply -f https://k8s.io/examples/application/deployment.yaml
kubectl expose deployment.apps/nginx-deployment

curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz{,.sha256sum}
tar xzvfC cilium-linux-amd64.tar.gz /opt/bin
rm cilium-linux-amd64.tar.gz{,.sha256sum}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
Thanks for the report! How does `ip r` and `ip n` look like before the iface goes down and after it's back up again (maybe sysdump before / after would be best if it's just a test env)?

**Comment by pothos** [comment]
Before:
```
$ ip r    
default via 145.40.93.210 dev bond0 proto static 
10.0.0.0/24 via 10.0.0.18 dev cilium_host src 10.0.0.18 
10.0.0.0/8 via 10.25.75.128 dev bond0 proto static 
10.0.0.18 dev cilium_host scope link 
10.25.75.128/31 dev bond0 proto kernel scope link src 10.25.75.129 
145.40.93.210/31 dev bond0 proto kernel scope link src 145.40.93.211 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
$ ip n
145.40.93.210 dev bond0 lladdr 06:00:de:ad:be:ef REACHABLE
fe80::400:deff:fead:beef dev bond0 lladdr 06:00:de:ad:be:ef router STALE
2604:1380:4091:a200:: dev bond0 lladdr 06:00:de:ad:be:ef router STALE
```

[cilium-sysdump-20220207-094529.zip](https://github.com/cilium/cilium/files/8014141/cilium-sysdump-20220207-094529.zip)
[bpftool-output-before.txt](https://github.com/cilium/cilium/files/8014142/bpftool-output-before.txt)


After:
```
$ ip r
default via 145.40.93.210 dev bond0 proto static 
10.0.0.0/24 via 10.0.0.18 dev cilium_host src 10.0.0.18 
10.0.0.0/8 via 10.25.75.128 dev bond0 proto static 
10.0.0.18 dev cilium_host scope link 
10.25.75.128/31 dev bond0 proto kernel scope link src 10.25.75.129 
145.40.93.210/31 dev bond0 proto kernel scope link src 145.40.93.211 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
$ ip n
10.25.75.129 dev bond0  INCOMPLETE
145.40.93.210 dev bond0 lladdr 06:00:de:ad:be:ef REACHABLE
145.40.93.211 dev bond0  INCOMPLETE
fe80::400:deff:fead:beef dev bond0 lladdr 06:00:de:ad:be:ef router STALE
2604:1380:4091:a200:: dev bond0 lladdr 06:00:de:ad:be:ef router STALE
```

[bpftool-output-after.txt](https://github.com/cilium/cilium/files/8014145/bpftool-output-after.txt)

Since `cilium sysdump`doesn't work afterwards I attached some `bpftool` output but I don't know what you need.

**Comment by borkmann** [comment]
> 10.25.75.129 dev bond0  INCOMPLETE
> 145.40.93.211 dev bond0  INCOMPLETE

Are these two addresses you're reaching out to?

From the agent log, I see that the Cilium version is 1.9.4. Could you try with latest 1.11.1, and dump the same outputs before/after if it reproduces there as well? (The bpftool one is not needed.)

**Comment by pothos** [comment]
Replaced it with `(sudo) /opt/bin/cilium install` → logs `using Cilium version "v1.11.1"`

Before:
```
$ ip r
default via 145.40.93.210 dev bond0 proto static 
10.0.0.0/24 via 10.0.0.195 dev cilium_host src 10.0.0.195 
10.0.0.0/8 via 10.25.75.128 dev bond0 proto static 
10.0.0.195 dev cilium_host scope link 
10.25.75.128/31 dev bond0 proto kernel scope link src 10.25.75.129 
145.40.93.210/31 dev bond0 proto kernel scope link src 145.40.93.211 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
$ ip n
145.40.93.210 dev bond0 lladdr 06:00:de:ad:be:ef STALE
10.25.75.128 dev bond0 lladdr 06:00:de:ad:be:ef STALE
fe80::400:deff:fead:beef dev bond0 lladdr 06:00:de:ad:be:ef router STALE
fe80::d6af:f7ff:fedb:4897 dev bond0  FAILED
2604:1380:4091:a200:: dev bond0 lladdr 06:00:de:ad:be:ef router STALE
```

After:
```
$ ip r
default via 145.40.93.210 dev bond0 proto static 
10.0.0.0/24 via 10.0.0.195 dev cilium_host src 10.0.0.195 
10.0.0.0/8 via 10.25.75.128 dev bond0 proto static 
10.0.0.195 dev cilium_host scope link 
10.25.75.128/31 dev bond0 proto kernel scope link src 10.25.75.129 
145.40.93.210/31 dev bond0 proto kernel scope link src 145.40.93.211 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
$ ip n
10.25.75.129 dev bond0  FAILED
145.40.93.210 dev bond0 lladdr 06:00:de:ad:be:ef REACHABLE
10.25.75.128 dev bond0 lladdr 06:00:de:ad:be:ef REACHABLE
145.40.93.211 dev bond0  INCOMPLETE
fe80::400:deff:fead:beef dev bond0 lladdr 06:00:de:ad:be:ef router STALE
fe80::d6af:f7ff:fedb:4897 dev bond0  FAILED
2604:1380:4091:a200:: dev bond0 lladdr 06:00:de:ad:be:ef router REACHABLE
```

**Comment by ysksuzuki** [comment]
You can use `ManageForeignRoutingPolicyRules=no` to protect policies.
https://github.com/systemd/systemd/commit/d94dfe7053d49fa62c4bfc07b7f3fc2227c10aff

However, things are a little bit complicated because of [this bug](https://github.com/systemd/systemd/commit/771a36439e955906290afc16a6fb3b10401892cf). This big is backported to systems v249.5. With systemd v249.4,  you need to set both IgnoreCarrierLoss=yes and KeepConfiguration=yes as well and never use `networkctl reconfigure` or `networkctl reload`. Or you need to create policy rules before network starts. I think the latter is difficult in our case.

**Comment by borkmann** [comment]
Thanks a lot for this information, much appreciated!

@pothos are you able to confirm that your issue is not seen anymore with the workaround suggested by @ysksuzuki?

**Comment by pothos** [comment]
Thanks, good to test this with Flatcar Alpha then which has a newer systemd. I'll try to get it working with one of the settings (Flatcar Stable doesn't have the bug fix yet).

So is this a variation of the topic where Flatcar has to ship networkd units that set Cilium interfaces to `Unmanaged=yes` instead of Cilium creating them at runtime under `/run/systemd/networkd/`?
I'm not sure the workaround of a global `ManageForeignRoutingPolicyRules=no` setting is the right way, or whether we should define the policy rules through networkd units (those don't get deleted, see https://www.freedesktop.org/software/systemd/man/networkd.conf.html#ManageForeignRoutingPolicyRules=). How would such a `[RoutingPolicyRule]` section look like for Cilium?

**Comment by pothos** [comment]
Can confirm that `ManageForeignRoutingPolicyRules=no` under `[Network]` in `/etc/systemd/networkd.conf` prevents the problem on Flatcar Alpha 3127.0.0

**Comment by pothos** [comment]
On the topic of the disappearing `lo` entry without `ManageForeignRoutingPolicyRules=no` (on Flatcar Alpha), without Cilium running the down/up action of the underlying device has no impact and `0:	from all lookup local` stays in the list. With Cilium the rule is gone…

**Comment by borkmann** [comment]
@pothos Thanks a ton for testing! I presume in this case we cannot just exclude the affected devices as with ...

https://github.com/flatcar-linux/init/pull/43/commits/0eb4436c6b9f5cbfca9c5e64fa371e8967a776fc

... but rather need the `ManageForeignRoutes`/`ManageForeignRoutingPolicyRules` generally from networkd. It's a bit cumbersome that networkd is interfering such much. Presumably every user that is also running their own BGP daemon on a node would have this disable the setting. Would be nice if systemd just had some sort of "server" profile where netword is less interfering. Hmm, do you happen to know if this was ever brought up with them?

**Comment by pothos** [comment]
Right, with `Unmanaged=yes` the rules are ignored and the only way for Cilium to tell networkd to preserve them is by putting them into an active `.network` unit (e.g., for a dummy interface)…

For reference, this is the translation into the networkd syntax:
```
[RoutingPolicyRule]
From=0.0.0.0/0
Table=local
Priority=100
[RoutingPolicyRule]
From=0.0.0.0/0
Table=2004
FirewallMark=512/3840
Priority=9
[RoutingPolicyRule]
From=0.0.0.0/0
Table=2005
FirewallMark=2560/3840
Priority=10
```

I think the networkd people had their reasons already from a "server" profile perspective. The way forward is that Flatcar, as a distro that expects Cilium to be running, would predefine the global setting like we do for similar cases. Maybe it makes sense for Cilium to add a check in the `cilium install` phase whether networkd is used and then recommending to change the default (plus having `Unmanaged=yes` is also a good idea even though it is only needed if people try to match too generically in their own networkd units as happend with Flatcar's default unit).

**Comment by pothos** [comment]
Thanks @ysksuzuki for the findings

**Comment by pothos** [comment]
For Flatcar Stable this works in `/etc/systemd/networkd.conf`:
```
[Network]
ManageForeignRoutes=no
ManageForeignRoutingPolicyRules=no
```
Then the additional `IgnoreCarrierLoss=yes` and `KeepConfiguration=yes ` workarounds mentioned in https://github.com/cilium/cilium/issues/18706#issuecomment-1031470456 are not needed.

**Comment by andy-v-h** [comment]
@borkmann would it make sense to have a preflight check for `cilium` around these settings, given that they can vary OS to OS by default and the combination of `systemd` and `cilium` configuration seem to be in conflict with eachother?

**Comment by borkmann** [comment]
> @borkmann would it make sense to have a preflight check for `cilium` around these settings, given that they can vary OS to OS by default and the combination of `systemd` and `cilium` configuration seem to be in conflict with eachother?

Good question, yes, I think it would make sense to have some automation on this regard to avoid users running into it. I haven't checked yet how reliably one could detect systemd versions and/or whether older versions of systemd would just ignore some of the not-yet-supported networkd.conf settings. A preflight check seems sensible. cc @aanm

**Comment by aanm** [comment]
> > @borkmann would it make sense to have a preflight check for `cilium` around these settings, given that they can vary OS to OS by default and the combination of `systemd` and `cilium` configuration seem to be in conflict with eachother?
> 
> Good question, yes, I think it would make sense to have some automation on this regard to avoid users running into it. I haven't checked yet how reliably one could detect systemd versions and/or whether older versions of systemd would just ignore some of the not-yet-supported networkd.conf settings. A preflight check seems sensible. cc @aanm

The preflight check is only intended for Cilium upgrades. I assume the issue can happen when the kernel upgrades but Cilium is not. Unless you were referring to a preflight inside the cilium-agent pod?

**Comment by andy-v-h** [comment]
> > > @borkmann would it make sense to have a preflight check for `cilium` around these settings, given that they can vary OS to OS by default and the combination of `systemd` and `cilium` configuration seem to be in conflict with eachother?
> > 
> > 
> > Good question, yes, I think it would make sense to have some automation on this regard to avoid users running into it. I haven't checked yet how reliably one could detect systemd versions and/or whether older versions of systemd would just ignore some of the not-yet-supported networkd.conf settings. A preflight check seems sensible. cc @aanm
> 
> The preflight check is only intended for Cilium upgrades. I assume the issue can happen when the kernel upgrades but Cilium is not. Unless you were referring to a preflight inside the cilium-agent pod?

I was thinking of a start-up check. The issue is we faced was when switch maintenance, we lost an entire Kubernetes cluster because every node had lost host networking, and restarting was the fastest fix to restore service. In effect, these `systemd-networkd` + `cilium` configurations are dangerous for a production environment where I anticipated to have LACP up and working. 

The `networkd` drop-ins do resolve my particular use case, however, I can't be the only `cilium` user on a similar setup.

**Comment by Frankkkkk** [comment]
(just passing by, but I have the same problem while trying ubuntu 21.04 (systemd 247.3). A restart of `systemd-networkd` makes it loose the ip rules, thus it won't accept RAs anymore, thus no SLAAC IPv6, etc. Potho's fix https://github.com/cilium/cilium/issues/18706#issuecomment-1031572546 makes it work again.)

**Comment by pothos** [comment]
To add on what I said in https://github.com/cilium/cilium/issues/18706#issuecomment-1031600043 here for docs purposes what I think could work with systemd-networkd default settings and no rule to set the affected interface `Unmanaged`.
At runtime Cilium could create a networkd unit for the interfaces under `/run/systemd/network/` with the `[RoutingPolicyRule]` entries and the following settings to have it not managed by systemd-networkd but communicate which routing policies need to be restored:
```
[Match]
Name=cilium_host
[Link]
ActivationPolicy=manual
[Network]
DHCP=no
LinkLocalAddressing=no
LLMNR=no
LLDP=no
IPv6AcceptRA=no
KeepConfiguration=yes
[RoutingPolicyRule]
…as in the linked comment above…
```

**Comment by gpl** [comment]
For completeness, in our use case (ubuntu 20.10/kern 5.13.0-35-generic/systemd 248 (248.3-1ubuntu8.2)/cilium 1.11.2), this issue also accepts IPv6 for us, so we've needed to restore the IPv6 routing rules as well.
```
[RoutingPolicyRule]
From=::/0
Table=2004
FirewallMark=512/3840
Priority=9
[RoutingPolicyRule]
From=::/0
Table=2005
FirewallMark=2560/3840
Priority=10
```

**Comment by vincentmli** [comment]
@RouxAntoine could you check if `systemd 250.5-1` has `ManageForeignRoutingPolicyRules` setting that you can set to `false` ?

**Comment by bmcustodio** [comment]
I faced this today on a regular Ubuntu 22.04 install - simply running `sudo netplan apply` manually was enough to break the host network. Setting

```
ManageForeignRoutingPolicyRules=no
ManageForeignRoutes=no
```

in `/etc/systemd/networkd.conf` did indeed fix it, so I wonder if we should document that?

**Comment by maxpain** [comment]
The same problem on Ubuntu 22.04.

**Comment by jansmets** [comment]
I'm having the same problem - ubuntu 22.04.1 LTS - it took me a very long time to figure this one out!

**Comment by SGStino** [comment]
I'm seeing the same issue, ubuntu 22.04, but not with bonds, just with a single ens224 is enough to break it.
As soon as the interface goes down and comes up again, host networking is entirely broken. 
Even ping 127.0.0.1 times out,  updating only
```
ManageForeignRoutes=no
ManageForeignRoutingPolicyRules=no
```
and restarting was enough to fix it.

**Comment by pothos** [comment]
It seems that the suggestions from https://github.com/cilium/cilium/issues/18706#issuecomment-1031600043 and https://github.com/cilium/cilium/issues/18706#issuecomment-1066986342 to solve it are not interesting? Then at least the suggestion for a `cilium install` check would be a good idea, or? From a first look I don't even see it in the docs: https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/

**Comment by MikeZappa87** [comment]
What is the output of 
`cat /proc/net/bonding/{bondname}`

**Comment by steffann** [comment]
I just ran into this problem, and it broke both IPv4 and IPv6. The solution in https://github.com/cilium/cilium/issues/18706#issuecomment-1031572546 did fix IPv4. It would have saved me a lot of time if this had been documented in an obvious place. Please consider documenting it in the installation manual, or better yet, fix it automatically.

**Comment by mblaschke** [comment]
can confirm issue when running cilium on AKS clusters

**Comment by kamikaze** [comment]
Having same problem with:
```
[Network]
ManageForeignRoutes=no
ManageForeignRoutingPolicyRules=no
```
on Ubuntu Server 22.04.2 LTS:
```bash
$ systemd --version
systemd 249 (249.11-0ubuntu3.9)
$ uname -a
Linux srv-cla-k3s01-worker1 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

with 1.14.0.snapshot.2

**Comment by rabbagliettiandrea** [comment]
Same here as @kamikaze (Ubuntu 22.04 LTS Systemd 249.11), once I stop k3s network access is lost the the VM and I need to "phisically" reboot it

**Comment by rabbagliettiandrea** [comment]
Hi I have solved here: https://github.com/k3s-io/k3s/pull/7618#issuecomment-1566925879

**Comment by jacobcrawford** [comment]
Does anyone know when this will be released?

**Comment by borkmann** [comment]
> Does anyone know when this will be released?

This is part of `quay.io/cilium/cilium:v1.14.0-snapshot.3` and will go into 1.14.0.

https://github.com/cilium/cilium/releases/tag/v1.14.0-snapshot.3

**Comment by ninja-** [comment]
I've hit that issue shortly after apt-get upgrade for some reason.
Unfortunately, latest version of microk8s ships ancient cilium which still has the issue....

```
➜  ~ microk8s cilium version
Client: 1.11.12 40d94ad 2022-12-15T15:58:31-08:00 go version go1.17.13 linux/amd64
Daemon: 1.11.12 40d94ad 2022-12-15T15:58:31-08:00 go version go1.17.13 linux/amd64
```

**Comment by ninja-** [comment]
if you are stuck with microk8s as well, I found the "version" hack that can be used to upgrade cilium. 1.13.8 is the newest that can install right now because of API change

```
Error: execution error at (cilium/templates/cilium-configmap.yaml:886:8): Value ipam.operator.clusterPoolIPv4PodCIDR removed, use ipam.operator.clusterPoolIPv4PodCIDRList instead
```

```
➜  ~ microk8s cilium version
Client: 1.11.12 40d94ad 2022-12-15T15:58:31-08:00 go version go1.17.13 linux/amd64
Daemon: 1.11.12 40d94ad 2022-12-15T15:58:31-08:00 go version go1.17.13 linux/amd64
➜  ~ microk8s disable cilium
➜  ~ microk8s enable cilium 1.13.8
➜  ~ microk8s cilium version
Client: 1.13.8 96f0558d 2023-10-17T09:48:08+03:00 go version go1.20.10 linux/amd64
Daemon: 1.13.8 96f0558d 2023-10-17T09:48:08+03:00 go version go1.20.10 linux/amd64
```
