### ISSUE TITLE
no route to cilium-health-ep controller in Vagrant hosted, bare metal K8s environment 

### ISSUE THREAD

**Issue by dbrowne** [cilium/cilium#18711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium installs without error after performing kubectl configuration change described in Issue #18670.
cilium status is initially fine
`vagrant@mstr:~$ cilium status --wait
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 7, Ready: 7/7, Available: 7/7
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 7
                  cilium-operator    Running: 1
Cluster Pods:     2/2 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2: 7
                  cilium-operator    quay.io/cilium/operator-generic:v1.11.1@sha256:977240a4783c7be821e215ead515da3093a10f4a7baea9f803511a2c2b44a235: 1
`
`vagrant@mstr:~$ kubectl get nodes -o wide
NAME   STATUS   ROLES                  AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
mstr   Ready    control-plane,master   3h28m   v1.23.3   192.168.33.10   <none>        Ubuntu 21.10   5.13.0-27-generic   docker://20.10.12
n1     Ready    <none>                 3h24m   v1.23.3   192.168.33.11   <none>        Ubuntu 21.10   5.13.0-27-generic   docker://20.10.12
n2     Ready    <none>                 3h24m   v1.23.3   192.168.33.12   <none>        Ubuntu 21.10   5.13.0-27-generic   docker://20.10.12
n3     Ready    <none>                 3h24m   v1.23.3   192.168.33.13   <none>        Ubuntu 21.10   5.13.0-27-generic   docker://20.10.12
n4     Ready    <none>                 3h24m   v1.23.3   192.168.33.14   <none>        Ubuntu 21.10   5.13.0-27-generic   docker://20.10.12
n5     Ready    <none>                 3h23m   v1.23.3   192.168.33.15   <none>        Ubuntu 21.10   5.13.0-27-generic   docker://20.10.12
n6     Ready    <none>                 3h23m   v1.23.3   192.168.33.16   <none>        Ubuntu 21.10   5.13.0-27-generic   docker://20.10.12
`

`vagrant@mstr:~$ cilium status 
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         6 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 7, Ready: 7/7, Available: 7/7
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 7
                  cilium-operator    Running: 1
Cluster Pods:     2/2 managed by Cilium
Image versions    cilium-operator    quay.io/cilium/operator-generic:v1.11.1@sha256:977240a4783c7be821e215ead515da3093a10f4a7baea9f803511a2c2b44a235: 1
                  cilium             quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2: 7
Errors:           cilium             cilium-tp7jf    controller cilium-health-ep is failing since 4s (5x): Get "http://10.0.2.64:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-zdnvt    controller cilium-health-ep is failing since 4s (5x): Get "http://10.0.3.64:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-426bf    controller cilium-health-ep is failing since 32s (4x): Get "http://10.0.6.80:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-984sn    controller cilium-health-ep is failing since 36s (4x): Get "http://10.0.4.161:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-hxztc    controller cilium-health-ep is failing since 5s (5x): Get "http://10.0.1.16:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-m7hth    controller cilium-health-ep is failing since 34s (4x): Get "http://10.0.5.188:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
`

Cilium connectivity test does not complete

### Cilium Version

vagrant@mstr:~$ cilium version
cilium-cli: v0.10.2 compiled with go1.17.6 on linux/amd64
cilium image (default): v1.11.1
cilium image (stable): v1.11.1
cilium image (running): v1.11.1

### Kernel Version

Linux mstr 5.13.0-27-generic #29-Ubuntu SMP Wed Jan 12 17:36:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20220205-062453.zip](https://github.com/cilium/cilium/files/8007514/cilium-sysdump-20220205-062453.zip)

### Relevant log output

```shell
vagrant@mstr:~$ cilium status 
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         6 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 7, Ready: 7/7, Available: 7/7
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 7
                  cilium-operator    Running: 1
Cluster Pods:     17/17 managed by Cilium
Image versions    cilium-operator    quay.io/cilium/operator-generic:v1.11.1@sha256:977240a4783c7be821e215ead515da3093a10f4a7baea9f803511a2c2b44a235: 1
                  cilium             quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2: 7
Errors:           cilium             cilium-984sn    controller cilium-health-ep is failing since 14s (31x): Get "http://10.0.4.161:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-hxztc    controller cilium-health-ep is failing since 18s (31x): Get "http://10.0.1.16:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-m7hth    controller cilium-health-ep is failing since 12s (31x): Get "http://10.0.5.188:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-tp7jf    controller cilium-health-ep is failing since 18s (31x): Get "http://10.0.2.64:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-zdnvt    controller cilium-health-ep is failing since 18s (31x): Get "http://10.0.3.64:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
                  cilium             cilium-426bf    controller cilium-health-ep is failing since 10s (31x): Get "http://10.0.6.80:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

vagrant@mstr:~$ ip route show
default via 10.0.2.2 dev enp0s3 proto dhcp src 10.0.2.15 metric 100 
10.0.0.0/24 via 10.0.1.197 dev cilium_host src 10.0.1.197 mtu 1450 
10.0.1.0/24 via 10.0.1.197 dev cilium_host src 10.0.1.197 
10.0.1.197 dev cilium_host scope link 
10.0.2.0/24 via 10.0.1.197 dev cilium_host src 10.0.1.197 mtu 1450 
10.0.2.2 dev enp0s3 proto dhcp scope link src 10.0.2.15 metric 100 
10.0.3.0/24 via 10.0.1.197 dev cilium_host src 10.0.1.197 mtu 1450 
10.0.4.0/24 via 10.0.1.197 dev cilium_host src 10.0.1.197 mtu 1450 
10.0.5.0/24 via 10.0.1.197 dev cilium_host src 10.0.1.197 mtu 1450 
10.0.6.0/24 via 10.0.1.197 dev cilium_host src 10.0.1.197 mtu 1450 
10.244.0.0/24 dev cni0 proto kernel scope link src 10.244.0.1 linkdown 
10.244.1.0/24 via 10.244.1.0 dev flannel.1 onlink 
10.244.2.0/24 via 10.244.2.0 dev flannel.1 onlink 
10.244.3.0/24 via 10.244.3.0 dev flannel.1 onlink 
10.244.4.0/24 via 10.244.4.0 dev flannel.1 onlink 
10.244.5.0/24 via 10.244.5.0 dev flannel.1 onlink 
10.244.6.0/24 via 10.244.6.0 dev flannel.1 onlink 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.33.0/24 dev enp0s8 proto kernel scope link src 192.168.33.10 

logs-cilium-gq29j-cilium-agent-20220205-062453.log:2022-02-05T05:43:12.774202194Z level=warning msg="Failed to remove old router IPs (restored IP: <nil>) from cilium_host. Manual intervention is required to remove all other old IPs." error="Link not found" subsys=daemon

logs-cilium-984sn-cilium-agent-20220205-062453.log:2022-02-05T05:43:17.201860066Z level=warning msg="Waiting for k8s node information" error="required IPv4 PodCIDR not available" subsys=k8s

Error: bpf obj get (/sys/fs/bpf/tc/globals/cilium_capture4_rules): No such file or directory
> Error while running 'bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_capture4_rules':  exit status 255
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by noolius** [comment]
I'm not sure there's fault per se in Cilium's handling of the referenced Vagrant+kubeadm configuration from the other bug. This bug's cilium-agent logs show, e.g., `Initializing cluster-pool IPAM" subsys=ipam v4Prefix=10.0.6.0/24`, overlapping the default Vagrant interface (your `ip r`). To resolve this specific symptom (which, as a side effect also resolves the other bug by providing detail to both kubelet and Cilium), you could specify a pod CIDR when configuring kubeadm, e.g., `/usr/bin/kubeadm init ... --pod-network-cidr=10.192.0.0/16`. Make sure to pass this same pod CIDR to Cilium, e.g., if using Helm, `ipam.operator.clusterPoolIPv4PodCIDRList=10.192.0.0/16`.

Based on your k8s-nodes-... log, a complete resolution for both symptoms in their respective bug reports requires also specifying the apiserver and pod CIDR to kubeadm/kubelet and Cilium, e.g.,

- `kubeadm init --apiserver-advertise-address=192.168.33.10 --pod-network-cidr=10.192.0.0/16 ...`
- Passing `k8sServiceHost=192.168.33.10` and `ipam.operator.clusterPoolIPv4PodCIDRList=10.192.0.0/16` to Cilium setup.

This approach is just one; see [further details](https://docs.cilium.io/en/stable/concepts/networking/ipam/).
