### ISSUE TITLE
VTEP integration: implement VTEP  map  lookup

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#18730]
copy and paste note from https://github.com/cilium/cilium/pull/17370 to track follow-up VTEP BPF hash map implementation for VTEP lookup

"
Joe: originally we were concerned about putting all of this information into the ipcache value, as you could have thousands of ipcache map entries and we would be increasing the total memory usage based on needing just a small N (<10) number of entries about the tunnel content.

If we wanted to do this, I would suggest that the ipcache piece stays the same as now - basically identifying the VTEP IP to be used. Then in this conditional case, if there is a VTEP then use the VTEP IP to look up a separate map specifically with the other VTEP details like MAC addresses. This should keep the memory usage down, while also avoiding to execute these additional instructions when VTEP is disabled.

Paul: If there's a new map for VTEPs specifically, why is the ipcache entry needed? AFAIU, the ipcache entry is what is causing all the troubles with policies. If we simply have a dedicated map for VTEPs, it will work the same as the egress gateway or the SRv6 egress encapsulation.
"

**Comment by vincentmli** [comment]
@joestringer @pchaigno I am thinking about VTEP map implementation,  for example now we have in ipcache map for VTEP like below

```
IP PREFIX/ADDRESS   IDENTITY
10.1.4.0/24         identity=2 encryptkey=0 tunnelendpoint=10.169.72.235      
10.1.5.0/24         identity=2 encryptkey=0 tunnelendpoint=10.169.72.236
```

the new VTEP map output I have in my mind is something like

```
10.1.4.0/24         vtepmac=xx:xx:xx:xx:xx:xx  tunnelendpoint=10.169.72.235
10.1.5.0/24         vtepmac=yy:yy:yy:yy:yy:yy  tunnelendpoint=10.169.72.236
```

since the new VTEP map key is more like a CIDR, I think maybe BPF `LPM_MAP_TYPE` is better fit than `BPF_MAP_TYPE_HASH`, so when cilium does VTEP lookup for destination VTEP endpoint IP `10.1.5.236`, it will match the `10.1.5.0/24`,  even if I change `10.1.5.0/24` to `10.1.5.0/28`, `10.1.5.236` still matches, so this gives user flexibility to configure whatever VTEP CIDR with variation of mask they want, does that make sense to you?

**Comment by joestringer** [comment]
That makes sense. There are some routines already in `pkg/cidr/` to even help you with detecting conflicting VTEP CIDRs.

**Comment by vincentmli** [comment]
@joestringer thanks for the comment, I have draft VTEP map golang code below, and trying to generate `pkg/maps/vtep/zz_generated.deepcopy.go` with `make generate-k8s-api`, no success, something I am missing ?

```

diff --git a/pkg/maps/vtep/vtep.go b/pkg/maps/vtep/vtep.go
new file mode 100644
index 0000000000..ace145d810
--- /dev/null
+++ b/pkg/maps/vtep/vtep.go
@@ -0,0 +1,155 @@
+// SPDX-License-Identifier: Apache-2.0
+// Copyright 2022 Authors of Cilium
+
+package vtep
+
+import (
+       "fmt"
+       "net"
+       "unsafe"
+
+       "github.com/cilium/cilium/pkg/bpf"
+       "github.com/cilium/cilium/pkg/cidr"
+       "github.com/cilium/cilium/pkg/logging"
+       "github.com/cilium/cilium/pkg/logging/logfields"
+       "github.com/cilium/cilium/pkg/mac"
+       "github.com/cilium/cilium/pkg/types"
+)
+
+var log = logging.DefaultLogger.WithField(logfields.LogSubsys, "map-vtep")
+
+const (
+       // MaxEntries is the maximum number of keys that can be present in the
+       // VTEP map.
+       MaxEntries = 8
+
+       // Name is the canonical name for the VTEP map on the filesystem.
+       Name = "cilium_vtep_map"
+)
+
+type MAC uint64
+
+func (m MAC) String() string {
+       return fmt.Sprintf("%02X:%02X:%02X:%02X:%02X:%02X",
+               uint64((m & 0x0000000000FF)),
+               uint64((m&0x00000000FF00)>>8),
+               uint64((m&0x000000FF0000)>>16),
+               uint64((m&0x0000FF000000)>>24),
+               uint64((m&0x00FF00000000)>>32),
+               uint64((m&0xFF0000000000)>>40),
+       )
+}
+
+// Key implements the bpf.MapKey interface.
+//
+// Must be in sync with struct vtep_key in <bpf/lib/common.h>
+// +k8s:deepcopy-gen=true
+// +k8s:deepcopy-gen:interfaces=github.com/cilium/cilium/pkg/bpf.MapKey
+type Key struct {
+       Prefixlen uint32     `align:"lpm_key"`
+       IP        types.IPv4 `align:"vtep_ip"`
+}
+
+// GetKeyPtr returns the unsafe pointer to the BPF key
+func (k *Key) GetKeyPtr() unsafe.Pointer { return unsafe.Pointer(k) }
+
+// NewValue returns a new empty instance of the structure representing the BPF
+// map value
+func (k Key) NewValue() bpf.MapValue { return &VtepEndpointInfo{} }
+
+func getStaticPrefixBits() uint32 {
+       staticMatchSize := unsafe.Sizeof(Key{})
+       staticMatchSize -= unsafe.Sizeof(Key{}.Prefixlen)
+       staticMatchSize -= unsafe.Sizeof(Key{}.IP)
+       return uint32(staticMatchSize) * 8
+}
+
+func (k Key) String() string {
+       prefixLen := k.Prefixlen - getStaticPrefixBits()
+       ipStr := net.IP(k.IP[:net.IPv4len]).String()
+       return fmt.Sprintf("%s/%d", ipStr, prefixLen)
+}
+
+// getPrefixLen determines the length that should be set inside the Key so that
+// the lookup prefix is correct in the BPF map key. The specified 'prefixBits'
+// indicates the number of bits in the IP that must match to match the entry in
+// the VTEP BPF map.
+func getPrefixLen(prefixBits int) uint32 {
+       return getStaticPrefixBits() + uint32(prefixBits)
+}
+
+// NewKey returns an Key based on the provided IP address and mask.
+func NewKey(ip net.IP, mask net.IPMask) Key {
+       result := Key{}
+
+       ones, _ := mask.Size()
+       if ip4 := ip.To4(); ip4 != nil {
+               if mask == nil {
+                       ones = net.IPv4len * 8
+               }
+               result.Prefixlen = getPrefixLen(ones)
+               copy(result.IP[:], ip4)
+       }
+
+       return result
+}
+
+// VtepEndpointInfo implements the bpf.MapValue interface. It contains the
+// VTEP endpoint MAC and IP.
+// +k8s:deepcopy-gen=true
+// +k8s:deepcopy-gen:interfaces=github.com/cilium/cilium/pkg/bpf.MapValue
+type VtepEndpointInfo struct {
+       VtepMAC        MAC        `align:"vtep_mac"`
+       TunnelEndpoint types.IPv4 `align:"tunnel_endpoint"`
+}
+
+func (v *VtepEndpointInfo) String() string {
+       return fmt.Sprintf("vtepmac=%d tunnelendpoint=%s",
+               v.VtepMAC, v.TunnelEndpoint)
+}
+
+// GetValuePtr returns the unsafe pointer to the BPF value.
+func (v *VtepEndpointInfo) GetValuePtr() unsafe.Pointer { return unsafe.Pointer(v) }
+
+// Map represents an VTEP BPF map.
+type Map struct {
+       bpf.Map
+}
+
+// NewMap instantiates a Map.
+func NewMap(name string) *Map {
+       return &Map{
+               Map: *bpf.NewMap(
+                       name,
+                       bpf.MapTypeLPMTrie,
+                       &Key{},
+                       int(unsafe.Sizeof(Key{})),
+                       &VtepEndpointInfo{},
+                       int(unsafe.Sizeof(VtepEndpointInfo{})),
+                       MaxEntries,
+                       bpf.BPF_F_NO_PREALLOC, 0,
+                       bpf.ConvertKeyValue,
+               ).WithCache().WithPressureMetric(),
+       }
+}
+
+var (
+       // VtepMAP is a mapping of all VTEP endpoint MAC, IPs
+       VtepMAP = NewMap(Name)
+)
+
+// Function to update IPCache map with VTEP CIDR
+func UpdateVTEPMapping(newCIDR *cidr.CIDR, newTunnelEndpoint net.IP, vtepMAC mac.MAC) error {
+
+       key := NewKey(newCIDR.IP, newCIDR.Mask)
+
+       value := VtepEndpointInfo{
+               VtepMAC: MAC(vtepMAC),
+       }
+       if ip4 := newTunnelEndpoint.To4(); ip4 != nil {
+               copy(value.TunnelEndpoint[:], ip4)
+       }
+
+       return VtepMAP.Update(&key, &value)
+
+}
                                                                                                                                                           
```

**Comment by joestringer** [comment]
I think that each package which needs autogeneration needs to be added specifically in the Makefile target for k8s-generate-api.

**Comment by vincentmli** [comment]
> I think that each package which needs autogeneration needs to be added specifically in the Makefile target for k8s-generate-api.

@joestringer thanks for the tip, I added map `maps:vtep\` in `Makefile` target `generate-k8s-api`, still no success, I will figure it out later, I actually ran into another bigger problem in draft PR https://github.com/cilium/cilium/pull/18824#issuecomment-1043212460 and I am stuck, could you take a look at that draft PR when you have time  and see anything I am missing?

**Comment by vincentmli** [comment]
> > I think that each package which needs autogeneration needs to be added specifically in the Makefile target for k8s-generate-api.
> 
> @joestringer thanks for the tip, I added map `maps:vtep\` in `Makefile` target `generate-k8s-api`, still no success, I will figure it out later, I actually ran into another bigger problem in draft PR [#18824 (comment)](https://github.com/cilium/cilium/pull/18824#issuecomment-1043212460) and I am stuck, could you take a look at that draft PR when you have time and see anything I am missing?

I made some progress on the draft PR,  it looks simply copy/pasting/edit of TUNNEL_MAP implementation to VTEP map does  not  get the job done, it requires actually understanding how it works underneath, if not all, but at least at some level :)

**Comment by vincentmli** [comment]
https://github.com/cilium/cilium/pull/18824 addressed this issue
