### ISSUE TITLE
DNS - based security policies cannot take effect

### ISSUE THREAD

**Issue by Ljohn001** [cilium/cilium#18759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the cluster uses nodelocaldns cache, cilium's dns-based strategy cannot resolve domain names, and cannot cache domain name resolution records.However, I turned off Nodelocaldns cache and the redeployment was able to test through

### Cilium Version

# cilium version
Client: 1.9.11 95d8778 2021-11-05T15:51:14-07:00 go version go1.15.15 linux/amd64
Daemon: 1.9.11 95d8778 2021-11-05T15:51:14-07:00 go version go1.15.15 linux/amd64

### Kernel Version

# System and kernel version
Ubuntu 20.04.3 LTS \n \l
Linux node1 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

# kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
# kubespray 2.18.0 deploy
```
ansible-playbook --timeout 60 -i inventory/mycluster/hosts.yaml --become --become-user=root cluster.yml -vv
````

### Relevant log output

```shell
# Testing process
kubectl create -f -<<EOF 
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn"
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: mediabot
  egress:
  - toFQDNs:
    - matchName: "b.ljohn.cn"
    - matchPattern: "*.qq.com"
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": node-local-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
--- 
apiVersion: v1
kind: Pod
metadata:
  name: mediabot
  labels:
    org: empire
    class: mediabot
spec:
  containers:
  - name: mediabot
    image: docker.io/tgraf/netperf
EOF
# curl www.qq.comm
kubectl exec -ti mediabot -- curl www.qq.com

curl: (6) Could not resolve host: www.qq.com; Unknown error
command terminated with exit code 6
# cilium fqdn cache is empty
bash k8s-cilium-exec.sh cilium fqdn cache list
==== detail from pod cilium-98kxh , on node 10.165.6.27
Endpoint   Source   FQDN   TTL   ExpirationTime   IPs

==== detail from pod cilium-nl9xn , on node 10.165.6.26
Endpoint   Source   FQDN   TTL   ExpirationTime   IPs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jibi** [comment]
Hi @Ljohn001 and thanks for the report!

Are you able to reproduce this (i.e. does enabling NodeLocal DNSCache bring back the issue)?

**Comment by Ljohn001** [comment]
> Hi @Ljohn001 and thanks for the report!
> 
> Are you able to reproduce this (i.e. does enabling NodeLocal DNSCache bring back the issue)?

Thanks for your reply, I open nodelocaldns can reappear.

**Comment by aditighag** [comment]
Did you enable node-local dns using LRP - https://docs.cilium.io/en/v1.11/gettingstarted/local-redirect-policy/#node-local-dns-cache?

**Comment by Ljohn001** [comment]
> 

Thanks for your reply, I'm not using LRP

**Comment by Ljohn001** [comment]
> Did you enable node-local dns using LRP - https://docs.cilium.io/en/v1.11/gettingstarted/local-redirect-policy/#node-local-dns-cache?

Thanks for your reply, I'm not using LRP

**Comment by pretty66** [comment]
I also encountered the same problem. Is there a way to solve this problem!

**Comment by mhulscher** [comment]
This might be related to this issue? https://github.com/cilium/cilium/issues/18644

**Comment by Ljohn001** [comment]
> This might be related to this issue? #18644

Thanks for your reply, I'm not using LRP.Now not sure what causes this problem
