### ISSUE TITLE
Split --bpf-lb-map-max into multiple options

### ISSUE THREAD

**Issue by brb** [cilium/cilium#18761]
Currently, the `--bpf-lb-map-max` option is used to configure multiple maps (service frontends, service endpoints, session affinity, etc). For some setups using the only option to configure might be less than ideal. E.g., if a user has a few services, but many service endpoints, it would be wasteful to create big service maps. Instead, we should give a mean to the user to configure the service endpoints size.

**Comment by koncha99** [comment]
@brb Hi! Can I pick this one?

**Comment by brb** [comment]
@koncha99 Sure. Thanks!

**Comment by brb** [comment]
@koncha99 Are you still on it?

**Comment by koncha99** [comment]
@brb sorry for being silent for a while. I'm a bit struggling with this issue though but would make a draft PR this weekend. Does 1.13 milestone have any due or plan for release?

**Comment by brb** [comment]
@koncha99 The 1.12 feature freeze is next week, so we can try to aim for v1.12 instead. Thanks.
