### ISSUE TITLE
Make Cilium more robust when there are many resources to sync from Kubernetes upon startup

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#18776]
## Proposal / RFE

**Is your feature request related to a problem?**

Users can hit `Timed out waiting for pre-existing resources to be received; exiting` which is a fatal error, when their cluster contains many resources such as CNPs, KNPS, etc. such that downloading and syncing the entire state from Kubernetes takes a relatively long time.

This timeout value can be configured via `--k8s-sync-timeout` which is actually a hidden flag, because it is intended for advanced users [1].

Figuring out what to configure this value to can be a challenge because Cilium will fatal as soon as the time interval expires and it's essentially impossible to know how much progress was made.

**Describe the solution you'd like**

It make this easier and Cilium more robust, we can do the following:

* We can add a variable, "how many seconds ago Cilium received a Kubernetes event of type X", which can also be a prometheus metric for visibility.
* Make the timeout (`--k8s-sync-timeout`, N) triggerable if a cache of type X is not synced and we have yet to receive an event of type X in N minutes. This will prevent Cilium from crashing after 3 minutes (default value of N). Otherwise crashing will cause Cilium to re-download everything from scratch again (like described above) and will additionally exacerbate the kube-apiserver load which can actually lead to the reason why the state is taking so long to be download / synced anyway.
* At the same time, for visibility purposes, expose as a prometheus metric that shows the rate of events per second of events received from Kubernetes.

Suggested-by: André Martins <andre@cilium.io> @aanm 

[1]: https://github.com/cilium/cilium/commit/bd89e83a424

**Comment by aditighag** [comment]
Another thing I would like to propose is having variable cache timeouts. Depending on the cluster deployments, certain resources like CNPs/KNPs can take longer time to download as compared to the other resources. Also, cache timeouts are internal details, and it'll be nice if we had some kind of adaptive mechanism for incrementally increasing the values without users having to tinker with them.

**Comment by aanm** [comment]
> Another thing I would like to propose is having variable cache timeouts. Depending on the cluster deployments, certain resources like CNPs/KNPs can take longer time to download as compared to the other resources. Also, cache timeouts are internal details, and it'll be nice if we had some kind of adaptive mechanism for incrementally increasing the values without users having to tinker with them.

That's what is in the proposal. The timeout will only be hit if there are no events from k8s within N minutes *and* the k8s caches are not synced.

**Comment by tommyp1ckles** [comment]
@christarazi For the rate of events per second of events received metric, do we not already get this from the `kubernetes_events_received_total`metric. I.e. this would just be like `rate(cilium_kubernetes_events_received_total[5m])` in Prometheus.

**Comment by christarazi** [comment]
@tommyp1ckles Good point, yes I think we already have this then.
