### ISSUE TITLE
Error: Kubernetes cluster unreachable:

### ISSUE THREAD

**Issue by sorryforyou** [cilium/cilium#18806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 helm install cilium cilium/cilium --version 1.11.1 \
>   --namespace kube-system
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused

Why is this？

### Cilium Version

-bash: cilium: 未找到命令

### Kernel Version

Linux k8s-master 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Kubernetes v1.23.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jibi** [comment]
Hi @sorryforyou, can you add some more detail on the setup please? Is this a managed environment?

**Comment by sorryforyou** [comment]
> Hi @sorryforyou, can you add some more detail on the setup please? Is this a managed environment?

HI @jibi ，This is the cluster I built on my own server. The cluster has been initialized and has not joined any nodes. The installation command is based on the information on the official document。

**Comment by sorryforyou** [comment]
> Hi @sorryforyou, can you add some more detail on the setup please? Is this a managed environment?

helm install cilium cilium/cilium \
>     --namespace kube-system \
> --set nodeinit.restartPods=true \
>     --set global.autoDirectNodeRoutes=true \
> --set global.hostServices.enabled=true \
>     --set global.kubeProxyReplacement=strict \
>     --set global.nodePort.mode=hybrid \
>     --set global.k8sServiceHost=192.168.77.120 \
>     --set global.k8sServicePort=6443
Error: Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused

**Comment by jibi** [comment]
> HI @jibi ，This is the cluster I built on my own server. The cluster has been initialized and has not joined any nodes. The installation command is based on the information on the official document。

This seems unrelated to Cilium :thinking: 
Is access to the cluster correctly configured on the machine where you are running the `helm` command? (e.g. does `kubectl` work?)

**Comment by aanm** [comment]
Hi @sorryforyou but this doesn't seem related to Cilium. Double check if your terminal has access to the kubernetes cluster so that helm command can work. Try using [cilium/cilium-cli](https://github.com/cilium/cilium-cli#install-cilium) instead.

**Comment by pbolduc** [comment]
I was running into this issue https://github.com/techno-tim/k3s-ansible/discussions/448#discussioncomment-8655513. I think the installer uses the `KUBECONFIG` environment variable to locate the k3s cluster. If it can't find it, it defaults the cluster address to `http://localhost:8080/`
