### ISSUE TITLE
Unify the term points to the BPF Host Routing

### ISSUE THREAD

**Issue by YutaroHayakawa** [cilium/cilium#18818]
Historically, BPF Host Routing was called Fast Redirect at some point. However, currently, we decided to go with "BPF Host Routing". We need to fix the code or comments that use the term Fast Redirect (or similar) to "BPF Host Routing".

Example of the place using Fast Redirect term
- https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L910
- https://github.com/cilium/cilium/blob/master/daemon/cmd/devices.go#L73

**Comment by chenk008** [comment]
Can I pick this issue and submit a PR?

**Comment by chenk008** [comment]
Should we rename `bpf.hostRouting` to `bpf.hostLegacyRouting` in ciliumconfig?

**Comment by YutaroHayakawa** [comment]
I agree that it is confusing, but I think we should think about it in a different issue since it changes the user interface.
