### ISSUE TITLE
Support `CB_POLICY` for deny policies

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#18811]
In our policy enforcement layer in the datapath, we use the `CB_POLICY` metadata bit to skip all policy enforcement.
https://github.com/cilium/cilium/blob/c8ddc064cdc42564338fe95be2ff3383232e8cca/bpf/lib/policy.h#L215-L216
This however won't work as expected with deny policies. We might need to fix it.

"Might" because it's also not clear why `CB_POLICY` is needed. In all cases I checked, we set that bit after the policy enforcement. I.e., I couldn't find a case where we read `CB_POLICY` and it could be set.

**Comment by julianwiedmann** [comment]
https://github.com/cilium/cilium/pull/35239 finally removed `CB_POLICY`.
