### ISSUE TITLE
cilium bpftool Error: failed to get btf

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#18817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am trying to use bpftool to debug map lookup issue but get following error:

kubectl exec -it cilium-r7zgn -n kube-system -- bpftool map list --bpffs -j | jq '.[] | select( .type == "lpm_trie" )' | jq

```

Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
{
  "id": 545,
  "type": "lpm_trie",
  "flags": 1,
  "bytes_key": 24,
  "bytes_value": 12,
  "max_entries": 512000,
  "bytes_memlock": 20480000,
  "frozen": 0,
  "pinned": [
    "/sys/fs/bpf/tc/globals/cilium_ipcache"
  ]
}
{
  "id": 552,
  "type": "lpm_trie",
  "flags": 1,
  "bytes_key": 12,
  "bytes_value": 1,
  "max_entries": 65536,
  "bytes_memlock": 1048576,
  "frozen": 0,
  "pinned": [
    "/sys/fs/bpf/tc/globals/cilium_lb4_source_range"
  ]
}
```
dump map
 kubectl exec -it cilium-r7zgn -n kube-system -- bpftool map dump id 545 | head -5

```
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
key:
40 00 00 00 00 00 00 01  0a 00 00 04 00 00 00 00
00 00 00 00 00 00 00 00
value:
e8 f1 00 00 00 00 00 00  00 00 00 00
```
lookup map with key
kubectl exec -it cilium-r7zgn -n kube-system -- bpftool map lookup id 545 key hex 40 00 00 00 00 00 00 01 0a 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00

Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
Error: failed to get btf

### Cilium Version

cilium version
cilium-cli: v0.10.0 compiled with go1.17.4 on linux/amd64
cilium image (default): v1.11.0
cilium image (stable): v1.11.1
cilium image (running): stable

### Kernel Version

Linux cilium-dev 5.12.9-1.el8.elrepo.x86_64 #1 SMP Mon May 31 19:00:24 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Anything else?

I recall cilium bpftool map lookup might worked before but not sure.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment]
@qmonnet I did further testing on cilium v1.10.0 which ship bpftool version `v5.9.0` that does not have this problem

```
kubectl exec -it cilium-7ggw9 -n kube-system -- bpftool map lookup id 482 key hex 20 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
key:
20 00 00 00 00 00 00 01  00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00
value:
02 00 00 00 00 00 00 00  00 00 00 00

[root@cilium-dev home]# kubectl exec -it cilium-7ggw9 -n kube-system -- bpftool version
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
bpftool v5.9.0
features:

```
cilium v1.11.1 ships bpftool version `v5.15.0-rc3`
```
kubectl exec -it cilium-rbj6p  -n kube-system -- bpftool version
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
bpftool v5.15.0-rc3
features:

```

**Comment by qmonnet** [comment]
Thanks a lot for the report!

Would you have a chance to try on your v1.10.0 setup with the latest version of bpftool, to see how it goes? Just to confirm it's a bpftool regression. If you don't have the kernel sources at hand, you can now compile bpftool [from its mirror](https://github.com/libbpf/bpftool), it should be straightforward (Otherwise I'll look myself when I have a moment).

**Comment by vincentmli** [comment]
> Thanks a lot for the report!
> 
> Would you have a chance to try on your v1.10.0 setup with the latest version of bpftool, to see how it goes? Just to confirm it's a bpftool regression. If you don't have the kernel sources at hand, you can now compile bpftool [from its mirror](https://github.com/libbpf/bpftool), it should be straightforward (Otherwise I'll look myself when I have a moment).

my understanding is  the bpftool is shipped within the v1.10.0 cilium agent container image, if I compile latest bpftool on my host, how do I make sure when I run `kubectl exec -it cilium-rbj6p  -n kube-system -- bpftool version`, the bpftool is invoked from the host build bpftool, not from the cilium agent container image? maybe I am missing something obvious ? :)

**Comment by vincentmli** [comment]
I got it, indeed I can run bpftool on host/node to query the same cilium map, I will compile latest bpftool

**Comment by qmonnet** [comment]
Interesting (thanks a lot!). If you have bpf-next ready, would you mind checkout out the sources around v5.15.0-rc3 to compile bpftool and double-check if it works on cilium v1.10?
