### ISSUE TITLE
nodes had taint{harm.cn/system: }

### ISSUE THREAD

**Issue by wkhno** [cilium/cilium#18829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I had a cluster build with kubeadm and k8s version 2.12 I run the demo and follow the instruction https://docs.cilium.io/en/v1.11/gettingstarted/http/#gs-http. Here is the bug report:Warning  FailedScheduling  65s   default-scheduler  0/3 nodes are available: 3 node(s) had taint {harm.cn/system: }, that the pod didn't tolerate. 
How can I use  kubeadm init to taint my nodes so that I do not need to add tolerations to my pod evey time I start a new demo?
I only find one "system=true" label and nothing related to harm.cn when I run "kubectl get nodes --show-labels" . Thank you very much!

### Cilium Version

v1.11.1

### Kernel Version

Linux 10.1.11.169-slave 5.16.9-1.el7.elrepo.x86_64 #1 SMP PREEMPT Thu Feb 10 10:39:14 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.21.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hi, thank you for opening the GH issue. This doesn't seem to be an Cilium issue since Cilium doesn't setup any taints on the nodes. Feel free to open a new GH issue if you find that it is caused by Cilium or open a new GH issue in the kubeadm repository. Thank you!

**Comment by wkhno** [comment]
thanks for your answer. I tried to remove my node taints and get the things work. It seems that is the problem I deploy my k8s cluster not the problem of cilium.
