### ISSUE TITLE
Feature request: Security groups for pods

### ISSUE THREAD

**Issue by mhulscher** [cilium/cilium#18833]
## Proposal / RFE

Currently Cilium allows attaching one or more SecurityGroups to pods running on nodes, by specifying these SecurityGroupIds in a custom cni configuration for cilium-agent: https://docs.cilium.io/en/v1.8/concepts/networking/ipam/eni/#eni-allocation-parameters

The AWS VPC CNI allows assigning a different SecurityGroup to Pods, based on a LabelSelector, see https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html . Preferably, I would like this feature to be available in Cilium as well.

**Is your feature request related to a problem?**

Without the ability to assign SecurityGroups to Pods, we are limited to assigning different SGs to worker nodes, which is more cumbersome.

**Describe the solution you'd like**

Preferably I would like to see a namespace-scoped CRD that allows assigning one or more SecurityGroupIds to Pods based on a LabelSelector. It would be up to the cluster-admin to provision these SGs and to ensure that the correct SGRules are present.

**Comment by dzoeteman** [comment]
This would be a great feature to have, but afaik dependent on aws/containers-roadmap#1146
