### ISSUE TITLE
CI: Missing KIND features to have the same coverage as Vagrant

### ISSUE THREAD

**Issue by brb** [cilium/cilium#18846]
This issue tracks all shortcomings of KIND which contribute to lower test coverage of the CI ginkgo suite when compared to when running on Vagrant.

- [x] XDP hack for veth ifaces (described in https://github.com/cilium/cilium/blob/master/test/l4lb/test.sh#L12).
- [x] Add secondary iface to KIND network, so that we can test the NodePort via secondary iface.

**Comment by julianwiedmann** [comment]
> Add secondary iface to KIND network, so that we can test the NodePort via secondary iface.

We'll also need the secondary iface to exercise the FIB lookup path when coming from `bpf_lxc`:
https://github.com/cilium/cilium/blob/c11c9f7b68292b09d32be6f577895677a424acfb/bpf/bpf_lxc.c#L1111

**Comment by lmb** [comment]
I'll try to tackle the XDP issue, second interface is out of scope.

**Comment by lmb** [comment]
XDP hack has been in place for a while now, unassigning myself.

**Comment by ysksuzuki** [comment]
> Add secondary iface to KIND network, so that we can test the NodePort via secondary iface.

Can we add secondary iface like this and test the NodePort via secondary iface on it?

```
docker network create -d=bridge kind-cilium-secondary
NODES=$(docker ps -a --filter label=io.x-k8s.kind.cluster=kind --format {{.Names}})
for NODE in $NODES; do
  docker network connect kind-cilium-secondary $NODE
done

docker exec kind-worker ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
9: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:12:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.4/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fc00:c111::4/64 scope global nodad
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:4/64 scope link
       valid_lft forever preferred_lft forever
20: eth1@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:13:00:05 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.5/16 brd 172.19.255.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe13:5/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by brb** [comment]
@ysksuzuki Yep! PR please :-)

**Comment by ysksuzuki** [comment]
Now we've got the secondary network in the kind network. Can we move the N/S load balancing test to the kind-based test?

**Comment by brb** [comment]
@ysksuzuki Good point! Let me close this issue. We will do the coordination of moving in a separate issue.
