### ISSUE TITLE
Restore support for consul as a kvstore backend

### ISSUE THREAD

**Issue by jrandall** [cilium/cilium#18851]
## Proposal

With the 1.11 release, support for consul as a kvstore backend has been documented as being deprecated. Mentions of consul were removed from the documentation and the reason for deprecation was listed as being "due to a lack of community interest".

The commit message (in https://github.com/cilium/cilium/pull/17993) provides a bit more detail:

> Consul support has been primarily used for developer environments in
> local testing, but we are not aware of any users running clusters
> depending on Consul for Cilium control plane co-ordination. Deprecate it
> in preparation to remove support in a future release, to minimize the
> maintenance burden of this code.

I guess one (possibly intended?) side effect of making this deprecation could be to solicit interest from the community that you may not be aware of, and it is my intent in filing this request to register interest and request that support be continued because I believe there are good use cases for this support.

My use case for this is not in developer environments. Rather, I am interested in using Cilium as a networking layer with Nomad (which can be an alternative to Kubernetes). Nomad uses Consul internally, so Nomad clusters will already have Consul available (and scaled appropriately to handle the cluster size) but would have to run etcd as a second configuration service. Cilium's support for Consul makes it an appear to be a good option for use with Nomad, and Nomad's blog post announcing support for CNI plugins even mentions cilium by name: https://www.hashicorp.com/blog/multi-interface-networking-and-cni-plugins-in-nomad-0-12

It was Cilium's Consul support that make it the more attractive option over Calico since it makes Cilium appear much more Hashicorp-friendly rather than being completely locked into the Kubernetes ecosystem. It also seems like it should drop into the Nomad ecosystem fairly straightforwardly (although I have not tried yet - I was stopped in my tracks when I found out that this support has been deprecated). 

There is another issue around documenting how to use Cilium in Nomad that is also relevant (and other comments there indicate other potential Cilium users who value Consul support): https://github.com/cilium/cilium/issues/18334

**Comment by aanm** [comment]
We have discussed in the community meeting March 2nd, 2022 that we won't remove Consul support for 1.12. Thank you for opening this issue.

**Comment by brotherdust** [comment]
Thank you for reconsidering support for Consul. I'm in the process of building a Hashistack cluster and Cilium is a perfect fit (especially because of the new VXLAN support)!

**Comment by mxplusb** [comment]
I second brotherdust's comment, I'm also building this out.

**Comment by brotherdust** [comment]
> We have discussed in the community meeting March 2nd, 2022 that we won't remove Consul support for 1.12. Thank you for opening this issue.

Can you also restore the documentation for Consul integration, please?

**Comment by maxadamo** [comment]
this is a project to integrate Cilium on Nomad, and it relies on Consul: https://github.com/cosmonic/netreap
Ideally, we should for support for the Nomad KV store.

**Comment by pchaigno** [comment]
After more than two years (6 releases) of being officially deprecated, we've finally removed support for Consul in Cilium. Hopefully, that gave enough time for users to implement the etcd alternative, as the netreap project mentioned above did.

This removal won't be officially released until v1.17 in several months. It is still possible someone or some group will have the willingness and time to maintain Consul support in Cilium and will allow us to revert course. That would at least require  documenting the support, rewriting the Consul end-to-end tests to stop using the deprecated Runtime suite, before being able to revert the removal pull request and the deprecation warning.
