### ISSUE TITLE
Cilium 1.11 bgp announce wrong pod cidr

### ISSUE THREAD

**Issue by lx1036** [cilium/cilium#18852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, i have a question: bgp announce wrong pod cidr. I deploy cilium v1.11.1 with cluster-pool ipam, and
```
cluster-pool-ipv4-cidr: 10.216.136.0/21 
cluster-pool-ipv4-mask-size: '27', 
bgp-announce-pod-cidr: 'true' 
bgp-announce-lb-ip: false 
```

And the bgp connection is established. BGP announce 10.216.137.0/24 for NodeA which is ipamed by kube-controller-manager with --allocate-node-cidrs=true, but the pod cidr for NodeA is 10.216.136.160/27 by Cilium Cluster-Pool IPAM, Cilium BGP with Metallb should announce 10.216.136.160/27. I want to know if there is a bug when Cilium decide announce k8s node spec.cidr in https://github.com/cilium/cilium/blob/v1.11.1/pkg/bgp/speaker/speaker.go#L492-L507 :

```go
func podCIDRs(node *v1.Node) *[]string {
    if node == nil {
        return nil
    }
    podCIDRs := make([]string, 0, len(node.Spec.PodCIDRs))
```

if i close kube-controller-manager node ipam with --allocate-node-cidrs=false, the node spec cidr is empty, and cilium bgp announce none for NodeA, which is not expected.
So, cilium should BGP announce 10.216.136.160/27 for NodeA, not 10.216.137.0/24 by kube-controller-manager.

Someone have encountered this same case about Cilium BGP Announce Unexpected Pod Cidr? 

### Cilium Version

1.11

### Kernel Version

4.19

### Kubernetes Version

1.19.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
Hi @lx1036 - the BGP feature on v1.11 only supports `ipam: kubernetes` unfortunately. With `ipam: cluster-pool`, the pod CIDR is populated in the `CiliumNode` CRD, _not_ the K8s Node object.
Support for `ipam: cluster-pool` didn't make it to v1.11, but will be available in v1.12: https://github.com/cilium/cilium/pull/17899

However, I don't think we support mixing `cluster-pool` with `kubernetes` IPAM around BGP. The current BGP annoucne implementation in `master` only looks at either the CiliumNode CRD (populated by `cilium-operator` in `cluster-pool` IPAM mode), _or_ the K8s Node object (populated by kube-controller-manager with `--allocate-node-cidrs=true`), but not both.

Hope this answers your question.

/cc @ldelossa

**Comment by lx1036** [comment]
@gandro  very thanks for your answer.  appreciate your great work.

**Comment by lx1036** [comment]
yes, the mixing `cluster-pool` with `kubernetes` is not good. i saw your pr code, and think about either CiliumNode or K8s Node, so i don't need to close kube-controller-manager ipam by `--allocate-node-cidrs=false`. 

it's great. thanks for your great work.

**Comment by gandro** [comment]
Great to hear! Just to confirm: Besides the missing/broken BGP announce support for clusterpool in v1.11, there are no other issues, correct?

**Comment by lx1036** [comment]
yes, correct. thanks.
