### ISSUE TITLE
Refactor Hubble Relay peer service to use CiliumNode subscriber

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#18866]
The Hubble Relay peer service server currently relies on the datapath node update subscriber to discover Cilium peers:

https://github.com/cilium/cilium/blob/794ce347d1e59b3ce9f15c3b8b4c845582c51d64/pkg/datapath/node.go#L107-L136

Implemented here - as you can see, most methods are just stubbed out (because Relay doesn't care about datapath configuration changes, it just needs to know about node updates):

https://github.com/cilium/cilium/blob/8e25d64386426ea97fa7b3a35f77d074ef4a7546/pkg/hubble/peer/handler.go#L94-L125

Cilium v1.12 however has a new subscriber interface for CiliumNode resources which doesn't include any datapath callbacks, which is likely the better fit than the above interface.

https://github.com/cilium/cilium/blob/d423afb94f378cebff3108130022eff82ed93b12/pkg/k8s/watchers/subscriber/ciliumnode.go#L16-L20

/cc @rolinh @kaworu

**Comment by cyclinder** [comment]
Hi everyone! Can I work on this ?
