### ISSUE TITLE
how does cilium_net work? 

### ISSUE THREAD

**Issue by liuyixian123** [cilium/cilium#18883]
we all know that cilium agent will create veth-pair on host( cilium_host and cilum_net)? but what cilium_net is used for really make me  puzzled

**Comment by vincentmli** [comment]
@liuyixian123 maybe this? https://github.com/cilium/cilium/blob/master/pkg/datapath/iptables/iptables.go#L977-L1031

**Comment by chenk008** [comment]
It seems CILIUM_CALL_IPV4_FROM_HOST will invoke `rewrite_dmac_to_host` to write dmac to cilium_net's mac, so the cilium_net will redirect the package.

**Comment by imcom** [comment]
> 

it does not really justify the purpose of using a veth-pair (cilium_host & cilium_net) on the node (host) netns, could you please share some use cases maybe to clarify?

**Comment by imcom** [comment]
> @liuyixian123 maybe this? https://github.com/cilium/cilium/blob/master/pkg/datapath/iptables/iptables.go#L977-L1031

ah, so does it mean that the veth-pair is essentially for intercepting the OUTGOING traffic from the current node ? To be more specific, when I send some packets via `cilium_host`, the packets come out of `cilium_net` (from `cilium_net` perspective, it is ingress traffic), so `ebpf` gets fired and can apply policy if any for further handling? Am I correct on this? @vincentmli

**Comment by aristapimenta** [comment]
> > @liuyixian123 maybe this? https://github.com/cilium/cilium/blob/master/pkg/datapath/iptables/iptables.go#L977-L1031
> 
> ah, so does it mean that the veth-pair is essentially for intercepting the OUTGOING traffic from the current node ? To be more specific, when I send some packets via `cilium_host`, the packets go into `cilium_net` (from `cilium_net` perspective, it is ingress traffic), so `ebpf` gets fired and can apply policy if any for further handling? Am I correct on this? @vincentmli

I'd also like to know the answer to this question @vincentmli :pray: thanks in advance!
