### ISSUE TITLE
Cilium NAT issue to reach 169.254.169.254 on EKS

### ISSUE THREAD

**Issue by prune998** [cilium/cilium#18906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`kubelet` on the nodes and some pods like Datadog agents starts complaining to not be able to call the AWS IMDS metadata API at `http://169.254.169.254:80/`:

```
kubelet: I0223 12:37:05.777720    3773 cloud_request_manager.go:115] "Node addresses from cloud provider for node not collected" nodeName=ip-10-249-5-117.ec2.internal err="error querying AWS metadata for \"network/interfaces/macs/0e:ea:7b:77:d2:79/device-number\": \"RequestError: send request failed\\ncaused by: Get \\\"http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:ea:7b:77:d2:79/device-number\\\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\""
```

doing a curl locally on the node or from a pod works... It seems to be only some running applications that are impacted with this issue.

Checking on the NAT or CT map, I see a large number entries and a large inbalance between the INs and OUTs:

```
cilium bpf nat list | wc -l
   17507

cilium bpf nat list | grep OUT | wc -l
44
  
cilium bpf nat list | grep IN | wc -l
17455

cilium bpf nat list | grep 169.254 | wc -l
17433
```

On the OS side, nothing is special:

```
netstat -a | grep tcp |wc -l
239
```

When looking into Hubble, I can see some `NO_MAPPING_FOR_NAT_MASQUERADE` denied traffic when the Datadog agent tries to reach the API.
The `kubelet` traffic is not displayed in Hubble. 

issue is impacting both trafic from pod -> IMDS and host -> IMDS

So far the solution is to run `cilium bpf nat flush`, but I fear the issue will trigger once again later. I have 4 clusters having the same issue, in different AWS accounts. They are all installed the same:

cluster in EKS with two nodepools. 
Host network is in `10.249.0.0/22` range, IP assigned on first ENI (eth0)
Pod network is assigned to eth1+ in the `100.64.0.0/16` CIDR

### Cilium Version

1.10.5 (v1.10.5-b0836e8)

### Kernel Version

5.4.156-83.273.amzn2.x86_64

### Kubernetes Version

1.21+ (v1.21.5-eks-bc4871b) [linux/amd64]

### Anything else?

I'm unsure about our Setup...

By setting up the config without `kube-proxy`, I end up having to set the masquerading CIDR equal to the default VPC CIDR, 10.249.0.0, while all my pods are in the 100.64.0.0 CIDE on the1+.

CIDR 100.64.0.0 is split in different VPC subnets (one per region) and had some route defined, exactly as the default 10.249.0.0 CIDR)

Cilium status is showing:

```
Host Routing:           Legacy
Masquerading:           BPF   [eth0]   10.249.0.0/20 [IPv4: Enabled, IPv6: Disabled]
...
Proxy Status:   OK, ip 100.64.129.123, 0 redirects active on ports 10000-20000
...
KubeProxyReplacement Details:
  Status:                Strict
  Socket LB Protocols:   TCP, UDP
  Devices:               eth0 10.249.5.117 (Direct Routing)
  Mode:                  DSR
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prune998** [comment]
It seems I can't attach the 40mb sysdump...

**Comment by prune998** [comment]
link to the slack thread: https://cilium.slack.com/archives/C53TG4J4R/p1645533192637289
I'm adding the sysdump there too

**Comment by borkmann** [comment]
I think on AWS, DSR generally doesn't work due to their underlying fabric. Did you try with SNAT mode to see if that works?
