### ISSUE TITLE
docs: Adding a note for required configuration to create a host-only network with latest VirtualBox

### ISSUE THREAD

**Issue by koncha99** [cilium/cilium#18932]
Since a later version of VirtualBox(v6.1.28 or above) restricts IPv6 range to only link-local addresses for host-only networks by default, `contrib/vagrant/start.sh` failed to configure a host-only network interface with IPv6 addresses, `FD00::/16`.

```
$ ./contrib/vagrant/start.sh
WARN: VirtualBox interface with "FD00::" not found
Create a new VBox hostonly network interface? [y/N] y
Creating VBox hostonly network...
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
VBoxManage: error: Code NS_ERROR_FAILURE (0x80004005) - Operation failed (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfigV6(Bstr(pszIpv6).raw(), (PRUint32)uNetmasklengthv6)" at line 256 of file VBoxManageHostonly.cpp
```

To avoid this error, IP ranges needs to be specified in `/etc/vbox/networks.conf` explicitly. In this case, the configuration below works for me. (Although IPv4 range used by the script is in default range allowed ranges, it also needs to be specified because default allowed ranges are ignored when a config file exists.)

```
# /etc/vbox/networks.conf
* 192.168.56.0/21
* FD00::/16
```

I think it's good to add a note to the "Developer Setup" page of the documentation.

reference
[VirtualBox Manual 6.7 Host-Only Networking](https://www.virtualbox.org/manual/ch06.html#network_hostonly)
[VirtualBox Changelog](https://www.virtualbox.org/wiki/Changelog-6.1#v30)

**Comment by koncha99** [comment]
If this sounds reasonable, I will submit a PR.

**Comment by aanm** [comment]
> If this sounds reasonable, I will submit a PR.

@koncha99 sure, sounds good!
