### ISSUE TITLE
how does cilium split parameter cluster-pool-ipv4-cidr or cluster-pool-ipv6-cidr for every node when using ipam cluster-pool ？please show me the code position

### ISSUE THREAD

**Issue by liuyixian123** [cilium/cilium#18959]
thank uuuuuuuuuuuuuuuuu

**Comment by kaworu** [comment]
by "space", for the Golang unicode definition of space.

Some code positions:
https://github.com/cilium/cilium/blob/89989608a36090944d9d6cb91bfa4b92400fc878/operator/option/config.go#L406-L407
https://github.com/cilium/cilium/blob/89989608a36090944d9d6cb91bfa4b92400fc878/vendor/github.com/spf13/viper/viper.go#L990-L995
https://github.com/cilium/cilium/blob/89989608a36090944d9d6cb91bfa4b92400fc878/vendor/github.com/spf13/cast/cast.go#L160-L164
https://github.com/cilium/cilium/blob/89989608a36090944d9d6cb91bfa4b92400fc878/vendor/github.com/spf13/cast/caste.go#L1170

Some documentation:
https://pkg.go.dev/strings#Fields
https://pkg.go.dev/unicode#IsSpace

You're welcome, please use the Cilium slack channel for question and leave GitHub issues for actual issues next time.
