### ISSUE TITLE
DROP_INVALID for packet sent via AF_PACKET + mmap ring buffer in pod

### ISSUE THREAD

**Issue by liuyuan10** [cilium/cilium#18951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

One of our customers has a program bouncing packets using AF_PACKET  + mmap ring buffer. The packet is immediately dropped in bpf_lxc  at revalidate_data()

The sample code is [gvnic-sample-vnf.tar.gz](https://github.com/cilium/cilium/files/8143211/gvnic-sample-vnf.tar.gz). It gets packets received from wire, swap src and dst for udp 6080 and dump back to wire again.

Reproduce steps:

* `make all` to build the code
* copy `bin/vnf` to any linux based pod you have. I'm using `ubuntu:focal`
* run `./vnf -f eth0` (you need privileged pods)
* open up udp port 6080 `nc -u -l 6080`
* generate udp traffic to port 6080 to this pod. For example `nc -u [pod-ip] 6080`

It's expected to see the traffic bounced back so you should see the same text echoed on the nc client.

But the echoed traffic is dropped immediately at bpf_lxc.cc:

```
Ethernet        {Contents=[..14..] Payload=[..118..] SrcMAC=7e:39:3b:18:2d:e8 DstMAC=d2:7e:9b:31:f7:7b EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..98..] Version=4 IHL=5 TOS=0 Length=134 Id=61537 Flags= FragOffset=0 TTL=63 Protocol=UDP Checksum=30089 SrcIP=10.184.0.5 DstIP=10.184.0.8 Optio
ns=[] Padding=[]}
UDP     {Contents=[..8..] Payload=[..90..] SrcPort=6080(gue) DstPort=20000(dnp) Length=114 Checksum=52637}
  Packet has been truncated
CPU 07: MARK 0x0 FROM 528 DROP: 148 bytes, reason Invalid packet identity 4209->unknown
```

By adding more debug traces in cilium, I can identify that (skb.data_end - skb.data) is only 14 bytes for such packets while skb.len is correct, which is why cilium is dropping the packet. Note that the skb is still holding the valid packet but just data_end is wrong. that's why the trace still showing legit packets.

Another data point is the same program runs fine directly on linux (outside of pod).

The cilium config can be found in this cilium log file: [cilium.log](https://github.com/cilium/cilium/files/8143416/cilium.log)

### Cilium Version

See the same on cilium 1.11.0, 1.10.3
Don't think it's related to cilium version

### Kernel Version

5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ubuntu 20.04.1

### Kubernetes Version

v1.21.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dariush-a** [comment]
@liuyuan10 
I'm curious that same program runs fine directly on linux (outside of pod) as you've mentioned. 
Also "(skb.data_end - skb.data) is only 14 bytes for such packets while skb.len is correct, which is why cilium is dropping the packet." does this mean it is related to the data_end being too short for Cilium to perform its logic,
If it's still too short, cilium can legitimately drop the traffic as "invalid".
Is this related to the [issue here](https://github.com/cilium/cilium/commit/5aebc46cacba2c164a6bb789f3bc185e5f0256e2)
https://github.com/cilium/cilium/commit/5aebc46cacba2c164a6bb789f3bc185e5f0256e2

**Comment by liuyuan10** [comment]
Sorry for the delay. That's a great find and I'm able to fix it by calling revalidate_data_pull at the start of bpf_lxc. I prepared PR #19308.

@varunmar to follow up while I'm on paternity leave

**Comment by varunmar** [comment]
I'm actually also on medical leave for the next month. That's a good find, tagging @anfernee and @Weil0ng as well - can one of you push this forward?

**Comment by Weil0ng** [comment]
Reviewed PR, will keep an eye out.

**Comment by dariush-a** [comment]
Hi @varunmar,
I see we are still waiting on code owner review from cilium/bpf.
