### ISSUE TITLE
seeing "error while initializing daemon: invalid argument" while upgrading from v1.10 to v1.11

### ISSUE THREAD

**Issue by evelynchen** [cilium/cilium#18976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
Followed the [Cilium upgrade guide](https://docs.cilium.io/en/stable/operations/upgrade/) to generate the cilium.yaml
diff the new template changes VS our template yaml to update the v1.11 changes.
Applying the changes to Cilium Operator went well, and most of the Cilium agent nodes are up.

But we have seen this happening on a few nodes post-upgrade from v1.10 to v1.11, this fatal error led the pod to run into CrashLoopBackOff status.
```
level=info msg="Initializing identity allocator" subsys=identity-cache
level=info msg="Cluster-ID is not specified, skipping ClusterMesh initialization" subsys=daemon
level=info msg="Setting up BPF datapath" bpfClockSource=ktime bpfInsnSet=v2 subsys=datapath-loader
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.core.bpf_jit_enable sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.all.rp_filter sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.fib_multipath_use_neigh sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=kernel.unprivileged_bpf_disabled sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=kernel.timer_migration sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_host.forwarding sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_host.rp_filter sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_host.accept_local sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_host.send_redirects sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_net.forwarding sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_net.rp_filter sysParamValue=0
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_net.accept_local sysParamValue=1
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.cilium_net.send_redirects sysParamValue=0
level=fatal msg="Error while creating daemon" error="error while initializing daemon: invalid argument" subsys=daemon
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
level=info msg="All pre-existing resources have been received; continuing" subsys=k8s-watcher
```

In debug mode, we also see an error message `k8s cache not fully synced`
```
level=debug msg="Controller run failed" consecutiveErrors=19 error="failed to inject labels into ipcache: k8s cache not fully synced" name=ipcache-inject-labels subsys=controller uuid=a173254b-f2c5-4d63-9e53-a6581d510caf
```

Suspecting that initializing with invalid argument, I have tried to remove `--config-dir` and it won't run into CrashLoopBackOff status. Have checked the cilium-agent document, I don't see the problem here.
```
        command:
        - cilium-agent --config-dir=/tmp/cilium/config-map
```

Does anyone know what may be causing this issue?

### Cilium Version

v1.11.1

### Kernel Version

4.18.0-305.19.1.el8_4.x86_64

### Kubernetes Version

  Container Runtime Version:  containerd://1.4.6
  Kubelet Version:            v1.19.16
  Kube-Proxy Version:         v1.19.16
  GoVersion: "go1.15.15"

### Relevant log output

full debug mode log link:
[https://files.slack.com/files-pri/T1MATJ4SZ-F034S2XLSJF/log](https://files.slack.com/files-pri/T1MATJ4SZ-F034S2XLSJF/log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by evelynchen** [comment]
I have tried to upgrade from v1.10.1, and jump each version to figure out which version went wrong.
v1.10.2, v1.10.3 then v1.10.4 are running fine. but it failed at v1.10.5 with the same error message

**Comment by vnandha** [comment]
I think the issue seems to be with the nodes that have loop back interface with different IP.

```
level=info msg="Addressing information:" subsys=daemon
level=info msg="  Cluster-Name: default" subsys=daemon
level=info msg="  Cluster-ID: 0" subsys=daemon
level=info msg="  Local node-name: kubemaster1.alpha1.org" subsys=daemon
level=info msg="  Node-IPv6: <nil>" subsys=daemon
level=info msg="  External-Node IPv4: 10.194.151.245" subsys=daemon
level=info msg="  Internal-Node IPv4: 10.0.1.1" subsys=daemon
level=info msg="  IPv4 allocation prefix: 10.0.1.0/24" subsys=daemon
level=info msg="  Loopback IPv4: 169.254.42.1" subsys=daemon
level=info msg="  Local IPv4 addresses:" subsys=daemon
level=info msg="  - 10.194.198.149" subsys=daemon
level=info msg="  - 10.0.1.1" subsys=daemon
```

10.194.198.149 is the loop back address. if I remove that on the node agent starts without any issue

For temporary work around by passing actual node IP on --ipv4-node works 
```
      containers:
      - command:
        - /bin/sh
        - -cx
        - exec cilium-agent --config-dir=/tmp/cilium/config-map --devices=$(ip route
          list match 0.0.0.0/0 | awk '{print $5}' | xargs) --ipv4-node=$(hostname
          -I |tr ' ' '\n'|grep -v 10.0.1.1 |grep -v 2001 |grep -v ^$)
```


we also use that hack to point --devices option. If there is better workaround, pls help. as @evelynchen pointed, this change happened from 1.10.5 onwards. with 1.10.4 it seems to be working without --ipv4-node option ( we still pass --devices today)

**Comment by aanm** [comment]
Can you provide a Cilium sysdump? Thank you!
