### ISSUE TITLE
cilium-operator deployment significantly delays node draining on infra failure

### ISSUE THREAD

**Issue by jweite-amazon** [cilium/cilium#18995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In AWS EKS, and in CAPI (CAPC) clusters, and maybe others not tested, when a VM backing a worker node fails, and that node is hosting the cilium-operator pod, node deletion is delayed significantly (15 mins+) by spurious attempts of the cilium-operator deployment to keep a cilium-operator pod running on the failed node while repeated drain attempts are being made.  This results in (typically) 15 terminating instances of the cilium-operator pod, all of which have to reach their deletion grace timeout (typically 5m) before they're forcibly terminated, one-by-one.

While this is merely inefficient in EKS (where the autoscaler has already replaced the failed node), in CAPI clusters node replacement by MachineHealthCheck doesn't occur _until_ the failed node has been successfully deleted, so scale and availability are impacted for this extended period of time.  In both environments the cilium-operator's controller would not be active until this extended draining period completes.

**Demonstrating with EKS:**
1) Provision an EKS cluster as described in https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/.
    I configured 3 nodes, to match my CAPI test configuration.
    
2) Install and verify Cilium, as described in the same document.

3) Confirm cluster health with _kubectl get nodes_

4) Identify the node hosting the cilium-operator pod with _kubectl -n kube-system get pods -o wide_

5) In the AWS console, terminate the EC2 instance implementing that node.  (Match the node name to the instance's DNS name).
     In my test run I terminated node _ip-192-168-102-184.us-east-2.compute.internal._  

6) Inspect the cluster nodes, observing that the terminated node becomes un-schedulable.

6) Begin repetitively monitoring the pods with _kubectl -n kube-system get pods -o wide_
     Observe that additional cilum-operator pods, all-but-one in terminating state / one pending, begin accumulating.  
     These are reported to be placed on the failed node.
     
7) After about 15 of these accumulate, observe that they begin being force-deleted.

8) When all are deleted, the failed node is finally drained and gets deleted.

Attached find the output of a _kubectl -n kube-system get pods -o wide_ illustrating the many cilium-operator pods in terminating state (except one pending) that ultimately accumulated in my test run, all placed on ip-192-168-102-184.us-east-2.compute.internal, the VM that was stopped.

[ciliumGetPods.txt](https://github.com/cilium/cilium/files/8164972/ciliumGetPods.txt)

### Cilium Version

cilium version
cilium-cli: v0.9.3 compiled with go1.17.3 on darwin/amd64
cilium image (default): v1.10.5
cilium image (stable): v1.11.2
cilium image (running): v1.10.5

### Kernel Version

I do not have ssh access to the EKS instances that hosted the workers to determine this.

### Kubernetes Version

v1.21.5-eks-9017834

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the well-written bug report! Looking through the attached `ciliumGetPods.txt` output, it seems to me like for some reason Kubernetes is scheduling this deployment to the node that is down. I wonder whether there is some configuration in Kubernetes that needs to be tweaked in order to handle this failure condition more gracefully?

While Cilium does provide the deployment for the kube-apiserver, this only has nominal impact on the scheduling selection. On the other hand, it appears in this scenario that for some reason Kubernetes is not considering the failed node to be unschedulable, but somehow continues to attempt to run pods on that node. Presumably Kubernetes also has settings that govern the node failure condition detection and decide when to give up on the node and so on.

**Comment by christarazi** [comment]
It seems to be this could be controller via node taints as Joe is suggesting above. https://github.com/kubernetes/kubernetes/pull/60009 has been implemented for some time. Is that being used in these environments?

**Comment by jweite-amazon** [comment]
Thanks for your replies @joestringer and @christarazi.  I'm not having luck finding either of these PRs in release notes, so I'm not entirely clear on which releases incorporate them.  I do see [#67734](https://github.com/kubernetes/kubernetes/pull/67734) in 1.12, which seems to address the matter of tainting failed nodes.  My test bed is running 1.21.5 (specifically v1.21.5-eks-bc4871b), so I do imagine it would incorporate this.

My test bed taints nodes with unreachable (stopped) VMs with _node.kubernetes.io/unreachable:NoExecute_.

The cilium-operator pods in my test bed have tolerations of op:Exists, so I believe they'll ignore all taints.

**Comment by christarazi** [comment]
@jweite-amazon The cilium-operator default tolerations seems to be the root cause here I'd imagine. `op:Exists` will tolerate all taints. When installing via Helm, it's possible to configure the Operator pod's tolerations via `--set operator.tolerations=...`. Can you try that and see if it resolves your issue?

**Comment by jweite-amazon** [comment]
@christarazi, Helm game me a bit of grief wrt how to define a map parameter on the cli against the 1.10.5 chart.  I eventually gave up and provisioned cilium with Helm without a toleration override defined and then edited the toleration on the deployment to be the same as I saw used for _core-dns: CriticalAddonsOnly:NoSchedule op=Exists_.  

I confirmed that the running pods now had this.  (_node.kubernetes.io/not-ready:NoExecute op=Exists for 300s_ and _node.kubernetes.io/unreachable:NoExecute op=Exists for 300s_ showed up on the running pods too...) and stopped an EC2 instance for a node hosting one of the cilium-operator pods.

K8s quickly scheduled a replacement pod on an available node.  No spurious nodes were created.  Nice.

kubectl -n kube-system get pods -o wide:
Before:
```
cilium-operator-778867f959-dtpkp   1/1     Running   0          29m   192.168.128.79    ip-192-168-128-79.us-east-2.compute.internal    <none>           <none>
cilium-operator-778867f959-nvjfh   1/1     Running   0          63m   192.168.104.236   ip-192-168-104-236.us-east-2.compute.internal   <none>           <none>
```

During:
`
cilium-operator-778867f959-dtpkp   1/1     Running             0          30m   192.168.128.79    ip-192-168-128-79.us-east-2.compute.internal    <none>           <none>
cilium-operator-778867f959-gd625   0/1     ContainerCreating   0          7s    192.168.177.57    ip-192-168-177-57.us-east-2.compute.internal    <none>           <none>
cilium-operator-778867f959-nvjfh   1/1     Terminating         0          63m   192.168.104.236   ip-192-168-104-236.us-east-2.compute.internal   <none>           <none>
`
Shortly after:
`
cilium-operator-778867f959-dtpkp   1/1     Running       0          30m   192.168.128.79    ip-192-168-128-79.us-east-2.compute.internal    <none>           <none>
cilium-operator-778867f959-gd625   1/1     Running       0          29s   192.168.177.57    ip-192-168-177-57.us-east-2.compute.internal    <none>           <none>
cilium-operator-778867f959-nvjfh   1/1     Terminating   0          64m   192.168.104.236   ip-192-168-104-236.us-east-2.compute.internal   <none>           <none>
`

10m after:
`
cilium-operator-778867f959-dtpkp   1/1     Running       0          40m     192.168.128.79    ip-192-168-128-79.us-east-2.compute.internal    <none>           <none>
cilium-operator-778867f959-gd625   1/1     Running       0          10m     192.168.177.57    ip-192-168-177-57.us-east-2.compute.internal    <none>           <none>
cilium-operator-778867f959-nvjfh   1/1     Terminating   0          74m     192.168.104.236   ip-192-168-104-236.us-east-2.compute.internal   <none>           <none>
`

I'm not sure why k8s hasn't force deleted the terminating pod after 10 mins...

**Comment by christarazi** [comment]
@jweite-amazon Are you able to run `kubectl describe` on the pod that gets stuck in terminating?

**Comment by christarazi** [comment]
@jweite-amazon Coming back to this, it seems to me that the above circular dependency can likely be resolved if the Operator deployment run with HA, i.e. with more than one replica. That way there's never a situation where the sole Operator is decommissioned and when a new node is created, it cannot be bootstrapped because the Operator and Agent (on the new node) require each other to bootstrap.

**Comment by jweite-amazon** [comment]
Thanks @christarazi, that looks good.  I ran the above EKS test scenario with three cilium operator replicas on the three nodes node terminations were dealt with cleanly: the new operator pod was always launched on the newly provisioned node with no spurious launch attempts on the terminated node.
