### ISSUE TITLE
CI: RuntimePolicies L3/L4 Checks: Skipping build due to invalid state: ready

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#19006]
https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1398/testReport/junit/(root)/Suite-runtime/RuntimePolicies_L3_L4_Checks/
[c63837ce_RuntimePolicies_L3-L4_Checks.zip](https://github.com/cilium/cilium/files/8170418/c63837ce_RuntimePolicies_L3-L4_Checks.zip)

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
Found 1 Cilium logs matching list of errors that must be investigated:
level=error
/home/jenkins/workspace/Cilium-PR-Runtime-net-next/runtime-gopath/src/github.com/cilium/cilium/test/helpers/utils.go:477
```
The error log in question is:
```
level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2230 error="Skipping build due to invalid state: ready" identity=5 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

**Comment by joestringer** [comment]
Curious. `identity=5` suggests that (1) identity is `ReservedIdentityInit` (which is I think typically only used if the identity cannot be determined by dumping labels from k8s + allocating identity). I'm actually surprised to see that show up at all these days, we eliminated most such cases several releases ago. But then `k8sPodName=/` suggests perhaps that this is the host endpoint or something? Since there is no corresponding pod.

**Comment by pchaigno** [comment]
> But then k8sPodName=/ suggests perhaps that this is the host endpoint or something? Since there is no corresponding pod.

I think `k8sPodName=/` is just because it's the Runtime tests and Kubernetes isn't installed. I confirmed from the sysdump that endpoint 2230 isn't the host endpoint since 2230 has a network interface starting with `lxc`. (The host endpoint is 2132.)

**Comment by joestringer** [comment]
Ah, okay, then that probably also explains the use of identity=5. The init identity like that is used initially for pods before we're able to establish the labels of the pod and allocate an identity. In K8s mode, this is a blocking operation upon pod creation, so we are guaranteed to have labels and a proper identity for the pod. In non-k8s mode, there is no such blocking check against the source of labels.

**Comment by joestringer** [comment]
Endpoint regeneration trigger here seems to be expecting that the pod was previously set into some kind of state that reflects that regeneration is occurring. But regeneration was already completed? Maybe there's some race condition with the container creation steps in this env now then.
