### ISSUE TITLE
if k8s internal ip is just a IPv6 address，cilium datapath is vxlan，how does cilium_vxlan work? 

### ISSUE THREAD

**Issue by liuyixian123** [cilium/cilium#19090]
![image](https://user-images.githubusercontent.com/94579721/157365165-8de7ec2e-c770-466b-88fa-76240b791ce8.png)
The srcNodeIP and dstNodeIP is IPv6 address which is got form k8s internal IP? am I right?

**Comment by aanm** [comment]
Correct
