### ISSUE TITLE
Small bug in agent.Agent.Init()

### ISSUE THREAD

**Issue by japem** [cilium/cilium#19106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I believe there is a small bug in the code in `pkg/wireguard/agent/agent.go:263`:

```go
subnet := net.IPNet{
	IP:   net.IPv4zero,
	Mask: net.CIDRMask(0, net.IPv4len), <---
}
```

The second argument to `net.CIDRMask()` is expected to be a number of bits in the address, but the value of `net.IPv4len` is 4 (the number of bytes in the address).

I think this has gone unnoticed because it's not actually a functional issue: this causes `net.CIDRMask()` to return `nil`, which functions the same as the intended mask of 0, although I haven't looked thoroughly to verify that.

cc @brb (got your name from git blame)

### Cilium Version

commit 409b2e60f8340aa8e2a6749516611cc19b35ac25

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@japem that is correct, the same bug is happening a couple lines below for IPv6Len. Would you like to submit a PR with the fix? Thank you!

**Comment by brb** [comment]
Nice catch @japem . Please send a PR.
