### ISSUE TITLE
if option.Config.Tunnel is “vxlan”，why do we check the "ipv4Address" ? as I know, ipv6Address can be used as the vxlan outer IP, too

### ISSUE THREAD

**Issue by liuyixian123** [cilium/cilium#19102]
cilium/pkg/node/address.go: 
`func ValidatePostInit() error {
	if option.Config.EnableIPv4 || option.Config.Tunnel != option.TunnelDisabled {
		if ipv4Address == nil {
			return fmt.Errorf("external IPv4 node address could not be derived, please configure via --ipv4-node")
		}
	}

	if option.Config.EnableIPv4 && ipv4RouterAddress == nil {
		return fmt.Errorf("BUG: Internal IPv4 node address was not configured")
	}

	return nil
}`

**Comment by joestringer** [comment]
Hi, I don't think that IPv6 VXLAN underlay is supported today for encapsulation. I don't think that there is any technical limitation to this, it's just that no-one has implemented it yet.

**Comment by liuyixian123** [comment]
> 

it's a pity. I've done the verification about IPv6 VXLAN underlay. I delete the code above and  make it choose a IPv6 address as the Outer IP, and ping the pod in another k8s node, it failed.

![image](https://user-images.githubusercontent.com/94579721/157780506-2df0f95e-f4ed-4cd0-bb29-15cb133de5dd.png)
 u can see the f100::41 is the IPv6 address in this k8s node. i make it as the cilium external ip.

node_config.h
![image](https://user-images.githubusercontent.com/94579721/157780738-7757a02c-7cc2-479d-8a25-6e3e6ffded68.png)
