### ISSUE TITLE
if option.Config.Tunnel is “ipvlan”，ipam is "cluster-pool"，cilium network is double-stack. we can't visit the pod in another node by IPv6 address.

### ISSUE THREAD

**Issue by liuyixian123** [cilium/cilium#19130]

**Comment by joestringer** [comment]
FYI IPVLAN support was deprecated in v1.11 due to lack of community interest and because veth has been optimized to achieve parity with ipvlan ([details in the Cilium v1.9 release blog](https://cilium.io/blog/2020/11/10/cilium-19#veth)).
