### ISSUE TITLE
Start serving status API immediately

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1914]
Serving of the API is currently delayed until after the endpoints have been restored to avoid mutations to objects while this is happening. This requires health checks to be delayed for a given amount of time to avoid probing the health check API during the restoration of endpoints.

New restore logic:
- [ ] request list of local containers
- [x] restore endpoint structures, add to endpoint list with state `restoring`
- [x] signal restore to be complete so API can be started
- [x] complete time-consuming operations in the background

**Comment by ianvernon** [comment]
3 minutes seems arbitrary; what if the instance of cilium is managing a large number of endpoints? We should empirically determine how long it takes for a large amount of endpoints to restore on a given node to determine the answer to this question.

**Comment by tgraf** [comment]
> 3 minutes seems arbitrary; what if the instance of cilium is managing a large number of endpoints? We should empirically determine how long it takes for a large amount of endpoints to restore on a given node to determine the answer to this question.

Good point, 30 seconds per endpoint is a safe bet.
