### ISSUE TITLE
Get rid of annoying harmless bpf tunnel errors

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1915]
During bootstrap, we print these harmless but annoying errors which should be avoided:

```
time="2017-10-31T01:45:14Z" level=error msg="bpf: Unable to delete 10.15.0.0/16 in tunnel endpoint map: Unable to delete element: invalid argument"
```

**Comment by joestringer** [comment]
@tgraf is this just something that should sit at debug level, or are we concerned about why we get in this situation in the first place?

**Comment by tgraf** [comment]
> @tgraf is this just something that should sit at debug level, or are we concerned about why we get in this situation in the first place?

It is supposed to be a legitimate error so we may be trying to update the map too early. We should avoid the error in the first place.

**Comment by tgraf** [comment]
This can be turned into a debug message to relieve this instantly.

**Comment by joestringer** [comment]
I wonder if the following FIXME has any impact on this:

https://github.com/cilium/cilium/blob/aee4d25b8c9acb15e6a359459ba23cb278137c91/pkg/node/manager.go#L270-L280

EDIT: Never mind, if the node was inserted with empty CIDR then a subsequent `deleteNodeCIDR` would skip the actual map delete.
