### ISSUE TITLE
Cannot update CEP - etcdserver: request is too large

### ISSUE THREAD

**Issue by joaoubaldo** [cilium/cilium#19151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have an EKS cluster running Cilium 1.10.3 on a small deployment (usually less than 10 nodes) and I’ve been getting error messages about CEP failing to update due to request size, with reasonable frequency (e.g hundreds everyday). 

```
cilium	level=error msg="Cannot update CEP" containerID= controller="sync-to-k8s-ciliumendpoint (3179)" datapathPolicyRevision=26 desiredPolicyRevision=26 endpointID=3179 error="etcdserver: request is too large" identity=5020 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer.

cilium	level=error msg="Cannot update CEP" containerID= controller="sync-to-k8s-ciliumendpoint (3179)" datapathPolicyRevision=26 desiredPolicyRevision=26 endpointID=3179 error="Request entity too large: limit is 3145728" identity=5020 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
```

Cilium is configured to use CRDs to keep state. 

Based on the shared logs, the associated identity (datadog-agent) is this:
```
$ cilium identity get 5020
ID     LABELS
5020   k8s:agent.datadoghq.com/component=agent
       k8s:agent.datadoghq.com/name=datadog
       k8s:app.kubernetes.io/instance=agent
       k8s:app.kubernetes.io/managed-by=datadog-operator
       k8s:app.kubernetes.io/name=datadog-agent-deployment
       k8s:app.kubernetes.io/part-of=datadog
       k8s:app.kubernetes.io/version
       k8s:io.cilium.k8s.policy.cluster=default
       k8s:io.cilium.k8s.policy.serviceaccount=datadog-agent
       k8s:io.kubernetes.pod.namespace=datadog
```

And its CEP resources are:
```
$ kubectl -ndatadog get cep | egrep '(^NAME|5020)'
NAME                                               ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4             IPV6
datadog-agent-gqq9m                                1609          5020          true                  true                                     ready            10.210.141.64
datadog-agent-nsvnt                                798           5020          true                  true                                     ready            10.210.114.235
datadog-agent-qmvld                                1287          5020          true                  true                                     ready            10.210.157.78
datadog-agent-vmr9z                                1463          5020          true                  true                                     ready            10.210.170.207
datadog-agent-wr9dx                                2061          5020          true                  true                                     ready            10.210.136.213
datadog-agent-xzhfn                                1768          5020          true                  true                                     ready            10.210.117.231
```

The yaml file of each of these CEPs is over 1.7MB (e.g. `kubectl get cep datadog-agent-gqq9m -o yaml`) - and these are the largest CEP compared to every other CEP in the cluster.

Gathering some stats on one of these CEP show that:
```File datadog-agent-gqq9m.yaml
File size 1798322 bytes
Egress count 127
Average egress label count 2
Egress identity-labels (yaml encoded) average size 103
Ingress count 2229
Average ingress label count 10
Ingress identity-labels (yaml encoded) average size 591
```

We have a few hundred deployments and most of these are services that communicate directly with the `datadog-agent` and its associated CNP is:
```apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  generation: 2
  name: datadog
  namespace: datadog
spec:
  egress:
  - toEndpoints:
    - matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: Exists
      matchLabels:
        jumo.world/monitoring_type: jmx
    toPorts:
    - ports:
      - port: "9012"
  - toEndpoints:
    - matchExpressions:
      - key: io.kubernetes.pod.namespace
        operator: Exists
      matchLabels:
        jumo.world/monitoring_type: nginx
    toPorts:
    - ports:
      - port: "8000"
  - toPorts:
    - ports:
      - port: "443"
    toServices:
    - k8sService:
        namespace: default
        serviceName: kubernetes
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "9153"
        protocol: TCP
    - ports:
      - port: "53"
        protocol: UDP
      rules:
        dns:
        - matchPattern: '*'
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: datadog-operator
        io.kubernetes.pod.namespace: datadog
    toPorts:
    - ports:
      - port: "8383"
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: external-dns
        io.kubernetes.pod.namespace: kube-system
    toPorts:
    - ports:
      - port: "7979"
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: kube-state-metrics
        io.kubernetes.pod.namespace: kube-system
    toPorts:
    - ports:
      - port: "8080"
  - toEndpoints:
    - matchLabels:
        app: gatekeeper
        io.kubernetes.pod.namespace: gatekeeper-system
    toPorts:
    - ports:
      - port: "8888"
  - toEndpoints:
    - matchLabels:
        app: teleport-cluster
        io.kubernetes.pod.namespace: teleport
    toPorts:
    - ports:
      - port: "3000"
  - toEndpoints:
    - matchLabels:
        app: teleport-kube-agent
        io.kubernetes.pod.namespace: teleport-agent
    toPorts:
    - ports:
      - port: "3000"
  - toEndpoints:
    - {}
  - toEntities:
    - host
    toPorts:
    - ports:
      - port: "53"
      - port: "9153"
      - port: "80"
      - port: "10250"
      - port: "9253"
      - port: "9091"
      - port: "5000"
      - port: "5005"
      - port: "9090"
      - port: "51678"
  - toFQDNs:
    - matchPattern: '*.datadoghq.eu'
    - matchPattern: '*.*.datadoghq.eu'
    toPorts:
    - ports:
      - port: "443"
      - port: "51678"
      - port: "80"
  - toFQDNs:
    - matchPattern: '*.datadog.pool.ntp.org'
    - matchPattern: '*.pool.ntp.org'
    toPorts:
    - ports:
      - port: "123"
  - toCIDRSet:
    - cidr: 169.254.169.254/32
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  - toCIDRSet:
    - cidr: 169.254.169.123/32
    toPorts:
    - ports:
      - port: "123"
        protocol: UDP
  - toFQDNs:
    - matchName: ec2.eu-west-1.amazonaws.com
    toPorts:
    - ports:
      - port: "443"
  endpointSelector:
    matchLabels:
      agent.datadoghq.com/component: agent
      agent.datadoghq.com/name: datadog
  ingress:
  - fromEntities:
    - cluster
    toPorts:
    - ports:
      - port: "8125"
      - port: "8126"
```

I was expecting Cilium to handle CEP updates without errors, using CRD to keep state given that the amount of nodes is considerably lower than the proposed maximum before moving to a kvstore (500).

### Cilium Version

Daemon: 1.10.3 4145278 2021-07-15T16:11:03+02:00 go version go1.16.6 linux/amd64

### Kernel Version

Linux ip-10-210-150-18.eu-west-1.compute.internal 5.4.176-91.338.amzn2.x86_64 #1 SMP Fri Feb 4 16:59:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
cilium	level=error msg="Cannot update CEP" containerID= controller="sync-to-k8s-ciliumendpoint (3179)" datapathPolicyRevision=26 desiredPolicyRevision=26 endpointID=3179 error="etcdserver: request is too large" identity=5020 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
cilium	level=error msg="Cannot update CEP" containerID= controller="sync-to-k8s-ciliumendpoint (3179)" datapathPolicyRevision=26 desiredPolicyRevision=26 endpointID=3179 error="Request entity too large: limit is 3145728" identity=5020 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
```

### Anything else?

These errors seem to be coming from [here](https://github.com/cilium/cilium/blob/v1.10.3/pkg/k8s/watchers/endpointsynchronizer.go#L248-L253) while a CEP is patched with a [new value](https://github.com/cilium/cilium/blob/v1.10.3/pkg/k8s/watchers/endpointsynchronizer.go#L130), that potentially contains excess bytes (around or more than [1.5MB](https://etcd.io/docs/v3.3/dev-guide/limit/#request-size-limit) or 3MB apparently). I’ve also seen some GitHub issues related with Cannot update CEP messages, but not necessarily related with request sizes. There’s a reference to these two error messages in [kubernetes](https://github.com/kubernetes/kubernetes/blob/3a52f8bcc6d9513eacd54dae6b96dfa3b87537d3/test/integration/controlplane/synthetic_controlplane_test.go#L313-L362) tests and it seems that they are thrown depending on where the overflow is (e.g. labels vs finalizers).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report! Looking at the output from above, it looks like you have turned on `--endpoint-status=policy`, which means that the size of the CEP is proportional to the number of peers in the cluster that can reach these endpoints. Given the permissive policy of `fromEntities: - cluster`, this selects each identity present in the cluster, and hence can grow to be quite large. As a mitigation, you could try turning this feature off. This feature is disabled by default particularly for this reason.

I can see the potential value in having endpoint policy status available in the CRDs somehow for cases like this, but I don't think that anyone in the community has picked up this partictular use case and attempted to solve it in a general way so far--ie having such an open policy with the endpoint policy status enabled at the same time. I recognize that such a policy is useful for components like datadog, dns. If you're interested in improving this behaviour, then I think we'd be interested in hearing proposals to improve Cilium's handling of this case.

**Comment by joaoubaldo** [comment]
Thanks @joestringer, this is useful information. I will post an update on this issue later.

**Comment by joaoubaldo** [comment]
No further errors since `endpoint-status: policy` was disabled (I am not actually using it anyways). Thanks for mentioning the ability to restrict identity labels @joestringer, that should definitely help in scenarios with permissive policies and/or significant number of identity labels such my initial setup.
