### ISSUE TITLE
Ginkgo CI: Migrate tests/21-ct-clean-up.sh

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1916]
Parent issue #1841

**Comment by ianvernon** [comment]
I do not have the bandwidth to migrate individual tests as I am focusing on things that the CI itself needs, not the tests themselves. I am removing myself from the list of assignees. @aanm can you please take care of this? Migrating tests you have written is a good way to get introduced to how Ginkgo works and will distribute the load of writing / validating tests.
