### ISSUE TITLE
How to redirect POD traffic to Node proxy under cilium-sidecarless architecture?

### ISSUE THREAD

**Issue by wangfakang** [cilium/cilium#19167]
I found that only the 'proxy_port' was set in the redirect code of [Cilium](https://github.com/cilium/cilium/blob/beta/service-mesh/bpf/lib/proxy.h#L210), but the 'proxy_ip' of proxy was not set.
![image](https://user-images.githubusercontent.com/8215757/158757340-35f44e91-7759-4fa8-a507-06bc1e228c60.png)

![image](https://user-images.githubusercontent.com/8215757/158757616-f5858ddd-85dc-4711-bcc1-8f469059b72b.png)

**Comment by vincentmli** [comment]
not familiar with this, maybe TPROXY only requires port to redirect traffic? https://www.kernel.org/doc/Documentation/networking/tproxy.txt, see "2. Redirecting traffic"

**Comment by vincentmli** [comment]
not sure if related but interesting https://cilium.io/blog/2020/06/22/cilium-18#ebpf-based-tproxy-replacement

**Comment by wangfakang** [comment]
> not familiar with this, maybe TPROXY only requires port to redirect traffic? https://www.kernel.org/doc/Documentation/networking/tproxy.txt, see "2. Redirecting traffic"

Thanks for your answer. In most scenarios, host and continer are different network namespaces, but `tproxy` can only take effect in the same network namespace.

**Comment by vincentmli** [comment]
@wangfakang the diagram attached describe the current working flow of cilium envoy proxy, in regard to the src ip after envoy proxying, the src ip is ip on `cilium_host`, so `A->B`after the envoy in the diagram is incorrect for current implementation

![Screen Shot 2022-06-06 at 8 16 58 AM](https://user-images.githubusercontent.com/3729694/172190772-0cfa2088-cf27-459c-a831-93bd51d9d722.png)
