### ISSUE TITLE
IPVLAN Support

### ISSUE THREAD

**Issue by BurlyLuo** [cilium/cilium#19200]
## Proposal / RFE

**Is your feature request related to a problem?**
No.
**Describe the solution you'd like**

## IPVLAN Backend
From the RN of Cilium,We can see that: [deprecated option](https://docs.cilium.io/en/v1.11/operations/upgrade/#deprecated-options)

### IPVLAN support has been deprecated due to lack of feature support and lack of community interest. [Recent improvements Virtual Ethernet device performance](https://cilium.io/blog/2020/11/10/cilium-19#veth) have granted many of the benefits of IPVLAN to the standard veth mode.

As we know that, the CNI chain for cilium, we can use the IPVLAN to provide the fastpath datapath, and use the CNI chain provide the Service and Network Policy. 
1.IPVLAN is more famlimer to everyone which compare with the bfp_redirect_peer() helpers.
2.The Iaas combine with the PaaS always use the IPVALN as the CNI. Like Terway, Multus, DANM,CNI-Genie.
3.The bfp_redirect_peer() helps need higher kernel version, maybe some environment can't use this feature to achieve the fastpath interface.

Would the team think twice to support the feature ?
thanks the team.

**Comment by aanm** [comment]
Hello @BurlyLuo, let's chat on [Cilium slack](http://slack.cilium.io) my username is `aanm`.

**Comment by BurlyLuo** [comment]
> Hello @BurlyLuo, let's chat on [Cilium slack](http://slack.cilium.io) my username is `aanm`.

Fine.my username is Rowan.

**Comment by vsxen** [comment]
Can I enable eBPF Host-Routing on Redhat 8?

Red Hat v8.2 with Linux kernel v4.18.0-193 or above (Red Hat have backported the required features to that build).

But source code seems only check kernel verison?

**Comment by chendotjs** [comment]
Kindly ping @aanm , is there any conclusion?

**Comment by aanm** [comment]
@chendotjs from the community it doesn't look like it, no.

**Comment by BurlyLuo** [comment]
> I have the same demand of IPVLAN...

Maybe the DANM can be used which from Nokia@https://github.com/nokia/danm

**Comment by brb** [comment]
For those who I interested in contributing - the long term solution could be reviving https://github.com/cilium/cilium/pull/14436 and then using the CNI's IPVLAN plugin via the CNI chaining.

**Comment by BurlyLuo** [comment]
> For those who I interested in contributing - the long term solution could be reviving #14436 and then using the CNI's IPVLAN plugin via the CNI chaining.

oh no, for this repo, we can see that it just a gimmick. no longer update here.

**Comment by BurlyLuo** [comment]
any update?
