### ISSUE TITLE
Expose MetalLB allocator metrics by cilium-operator

### ISSUE THREAD

**Issue by aleksey-novikov** [cilium/cilium#19232]
## Expose MetalLB allocator metrics by cilium-operator

**Currently no way to monitor LB pool allocation usage**
MetalLB [register](https://github.com/cilium/cilium/blob/4e6b6b5c6359857230b1b502d1fce1a57e5c78c2/vendor/go.universe.tf/metallb/pkg/allocator/stats.go#L36) some allocator metrics:
metallb_allocator_addresses_total
metallb_allocator_addresses_in_use_total
metallb_allocator_services_allocated_total

But cilium-operator does not expose these metrics because cilium-operator [use own registry instance](https://github.com/cilium/cilium/blob/4e6b6b5c6359857230b1b502d1fce1a57e5c78c2/operator/metrics/metrics.go#L37) instead promethus_client built-in one used by MetalLB

**Describe the solution you'd like**
cilium-operator should expose allocation metrics from MetalLB under cilium_operator namespace

**Comment by christarazi** [comment]
In future versions of Cilium, we will move away from MetalLB as we'll integrate our own BGP implementation. cc @ldelossa

**Comment by ldelossa** [comment]
Yes, @aleksey-novikov we plan on removing MetalLB integration. 

We are still in planning phases, however the MetalLB features, along with allocatation pools, will be implemented as a Cilium native feature coming soon.
