### ISSUE TITLE
Implement a dedicated function to handle the MTU selection logic

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#19243]
The MTU selection logic in the Agent is tied to a generic function (`firstGlobalAddr()`), which is also used with BPF masquerade and NodePort logic. Given that selecting an MTU is unique enough from BPF masq and NodePort, we should have a dedicated logic in the Agent for selecting the MTU properly, without sharing a generic function, which can result in subtle breakages if the generic function is tweaked.

**Comment by cyclinder** [comment]
Hi @christarazi , I would like to pick this up. Can you give me some code pointers on where to start?
