### ISSUE TITLE
Support custom node taint prefix to support scaling to zero nodes in GKE

### ISSUE THREAD

**Issue by itsthatriver** [cilium/cilium#19241]
## Proposal / RFE

**Is your feature request related to a problem?**
We run Cilium with `NoSchedule` cilium taints in GKE to ensure pods are started after Cilium is able to bootstrap the node. The problem is that we run multi-zone node pools, and multi-zone pools are configured in GKE as a union of multiple Cluster-Autoscaler pools under the hood, and we regularly scale the multi-zone pool down to 1 node (and consequently, several of the CA pools internally scale down to zero). Autoscaling works fine with the Cilium node taints when there are nodes in a pool, but if it scales down to zero the Cluster Autoscaler changes behavior from inspecting a running node (which doesn't have a cilium taint any more, and is eligible for app pod scheduling), so if there are insufficient resources it can easily determine that a new node would alleviate resource pressure and allow pending pods to schedule.

The problem shows up because Once there are no running nodes, the CA inspects the node group template, which includes the Cilium taint, and then the CA determines that adding a node would not allow pending pods to run because they would not tolerate the cilium taint (even though it would be removed in bootstrap by a daemonset).

There is config in the cluster autoscaler to ignore taints [by way of command line argument](https://github.com/kubernetes/autoscaler/blob/5cf3b9657f53324e4d6d7cc06bee8837d0e51503/cluster-autoscaler/main.go#L179) to the CA with `--ignore-taint`, however that is not exposed for configuration in GKE (all [they expose](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_cluster_autoscaling) is "PROFILE", which is just "balanced" or "high-utilization").

There is another option in the CA though, shown [here](https://github.com/kubernetes/autoscaler/blob/3e53cc4b8d580e4ece67f09ef2103138ee65e3db/cluster-autoscaler/utils/taints/taints.go#L34), where if you prefix a taint with `ignore-taint.cluster-autoscaler.kubernetes.io/`, the CA will ignore it when simulating scheduling, allowing you to scale up from zero.

**Describe the solution you'd like**

I would like an option to override the taint (or taint prefix) used by Cilium to manage agent readiness taints so that the CA ignores that taint when making scaling decisions, but it is still respected by the k8s scheduler when placing pods.

**Comment by stonith** [comment]
@thejosephstevens have you tried using using prefix `ignore-taint.cluster-autoscaler.kubernetes.io/` in GKE? If try to edit a node pool in the web console I get an error "Node taints with key "ignore-taint.cluster-autoscaler.kubernetes.io/cilium-agent-not-ready" are managed by Kubernetes and must not be manually specified."

**Comment by thejosephstevens** [comment]
> @thejosephstevens have you tried using using prefix `ignore-taint.cluster-autoscaler.kubernetes.io/` in GKE? If try to edit a node pool in the web console I get an error `Node taints with key "ignore-taint.cluster-autoscaler.kubernetes.io/cilium-agent-not-ready" are managed by Kubernetes and must not be manually specified.` I guess this may need to be done at the cluster level instead of node level?
> 
> UPDATE: I confirmed that cluster and nodepool creation will allow the `ignore-taint.cluster-autoscaler.kubernetes.io/` taint prefix but editing will not.

We tested on GKE (I'm actually making a new node pool now to sanity check). What version are you running?

Just got this on a brand new node pool
![image](https://user-images.githubusercontent.com/5632093/174928887-23b70a71-22ec-48df-9dcf-1eed64cb1256.png)

**Comment by stonith** [comment]
> We tested on GKE (I'm actually making a new node pool now to sanity check). What version are you running?
> 
> 
> 
> Just got this on a brand new node pool

Cluster or node pool creation allows the prefix. Editing existing node pool doesn't seem to allow it.

**Comment by thejosephstevens** [comment]
> Cluster or node pool creation allows the prefix. Editing existing node pool doesn't seem to allow it which is an unlikely requirement.

Ahhhh, interesting. So we've found that a lot of changes like this require node pool recreation across different providers, so we didn't test that case. I unfortunately don't think we can do anything about that. Best shot would be opening a ticket with GCP
