### ISSUE TITLE
Extend unit tests for routing setup

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#19261]
We should extend the unit tests in `pkg/datapath/linux/routing` to cover the sort of bug described and fixed in https://github.com/cilium/cilium/pull/19162.

The TL;DR is that we had a mismatch between the creation (`Configure`) and deletion (`Delete`) of IP rules. In unit tests today, we test those two functions separately. We would need to add a new unit test which call one after the other and checks the system is back to its original state.

**Comment by alexander-demichev** [comment]
isn't it tested here https://github.com/cilium/cilium/blob/28116f5d50d9d9922c85c4469be71f9f5d85a780/pkg/datapath/linux/routing/routing_test.go#L38?

**Comment by pchaigno** [comment]
Oh, you're right! Then we should check why it wasn't enough to detect the bug fixed in https://github.com/cilium/cilium/pull/19162 and improve the test accordingly. I suspect it's a matter of agent configuration we start the test with.

**Comment by krabradosty** [comment]
Hi @pchaigno, I'm not sure whether you've got a notification for my pull request. Please take a look #24933
