### ISSUE TITLE
Image Signing

### ISSUE THREAD

**Issue by ReillyBrogan** [cilium/cilium#19282]
## Proposal / RFE

**Is your feature request related to a problem?**
Kubernetes itself is currently adding support for signing release artifacts (including cluster component images) using [cosign](https://github.com/sigstore/cosign). It would be excellent if Cilium could sign their release images as well during the build pipeline so that those users desiring more secure clusters could use an admission controller (like [connaisseur](https://github.com/sse-secure-systems/connaisseur) that validates image signatures as an additional layer of security. 

Connaisseur allows for enabling verification for whitelisted namespaces and because Cilium is typically deployed into the kube-system namespace it would enable enabling verification for the kube-system namespace once the Kubernetes images are signed as well.

https://github.com/kubernetes/enhancements/issues/3031
https://github.com/kubernetes/release/issues/2227
https://github.com/kubernetes/release/issues/2383

https://github.com/sigstore/cosign
https://github.com/sse-secure-systems/connaisseur

**Comment by aanm** [comment]
@ReillyBrogan Would you like to give it a try and submit a PR?

**Comment by aanm** [comment]
If you @Dentrax or @developer-guy wants to try it out just give it a go.

**Comment by ReillyBrogan** [comment]
I've been trying to wrap my head around cosign's Fulcio CA model, but it seems like a lot of additional complexity (I see a few notes in places that some parts aren't completely production ready too). I think the more traditional method of having an admin generate a public/private key and then using that as a Github secret during the release pipeline. The public key can be posted in documentation or something.

**Comment by skant7** [comment]
Hi ,
Came here from the CNCF mentorship repo, I'm interested in working on this.
Any pointers on where to start to get familiar with the project scope ?

**Comment by xmulligan** [comment]
Hi @skant7 thanks for your interest. The application will open on August 25th. Please submit then https://lfx.linuxfoundation.org/tools/mentorship/. In the meantime, please feel free to check out the good first issues https://github.com/cilium/cilium/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue

**Comment by monalisha31** [comment]
Hi, I would like apply for this project under the LFX mentorship program. This project seems interesting. Looking forward to contributing to it.

**Comment by xmulligan** [comment]
@monalisha31 thanks for your interest! You can find the application here https://mentorship.lfx.linuxfoundation.org/project/680e32e5-d056-46fa-a94d-4af453d4e81d

**Comment by aanm** [comment]
GitHub blogpost with some information about cosign using GH actions https://github.blog/2021-12-06-safeguard-container-signing-capability-actions

**Comment by qascade** [comment]
I know I should not post this here and will delete later but I have a problem with my lfx application. The application for this issue was registered twice (showing the prerequisite tasks twice) in my case. So, I thought to withdraw and apply again but  I am not able to apply. The email said to contact program supervisor but I don't know how and who to get in touch with.

**Comment by xmulligan** [comment]
@qascade for issues with the LFX platform, please reach out to the LFX support directly - [support.linuxfoundation.org](http://support.linuxfoundation.org/)

**Comment by yimikao** [comment]
Hi @xmulligan after applying to a project of choice and uploading resume. Is there going to be another task for applicants to complete before mentees are selected? I don't really know how it works and the LFX page isn't really clear on that.

**Comment by qascade** [comment]
@yimikao check `my tasks` tab on your mentorships page. Also check your spam folder. My initial mails from lfx were going to spam.

**Comment by qascade** [comment]
> @qascade for issues with the LFX platform, please reach out to the LFX support directly - [support.linuxfoundation.org](http://support.linuxfoundation.org/)

Thanks for your advice. The issue was resolved.

**Comment by yimikao** [comment]
@qascade so new tasks will be added over there as a the next qualification step, right?

**Comment by qascade** [comment]
> @qascade so new tasks will be added over there as a the next qualification step, right?
On succesful application, you have to upload a cover letter and resume under `my tasks`. Anyways you should get a mail regarding prerequisite tasks from lfx itself.

**Comment by acald-creator** [comment]
Good morning

I've applied to the mentorship program. I'm familiar with using cosign tool, and would like to contribute if chosen.

**Comment by ReillyBrogan** [comment]
I don't see any reason why this couldn't be backported to the stable branches as well.
