### ISSUE TITLE
hubble.metrics.port 9091 and prometheus.port 9090 failed

### ISSUE THREAD

**Issue by zhuw0312** [cilium/cilium#19295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when i cilium config set hubble.metrics.port 9091 and prometheus.port 9090，pod can not start 9090 or 9091 port after restarted.

### Cilium Version

cilium-cli: v0.10.4 compiled with go1.17.7 on linux/amd64
cilium image (default): v1.11.2
cilium image (stable): v1.11.3
cilium image (running): v1.11.2

### Kernel Version

5.16.8-1.el7.elrepo.x86_64

### Kubernetes Version

v1.22.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
> when i cilium config set hubble.metrics.port 9091 and prometheus.port 9090，pod can not start 9090 or 9091 port after restarted.

Could you clarify what you mean? Do you have pods who are using those ports on the host? Or is it the Cilium pods that can't start? If it's the second case, could you please upload a Cilium sysdump?

**Comment by zhuw0312** [comment]
sorry . Cilium pods is running well.

(https://gz-yp.oss-cn-beijing.aliyuncs.com/cilium-sysdump-20220406-113248.zip?Expires=1649216480&OSSAccessKeyId=TMP.3KhRD7Nhe6pG1Jj6yawZmRDdKQvzC5484sFBcu5ttRxUtcpNbhRsRmc9QYaQ5HB1U1gXVpBk7P1kJnQuZYcsGVhWkrfpPK&Signature=1x0cpJbVYB%2F9vUvK09SHJ9JRNKM%3D&response-content-type=application%2Foctet-stream)

**Comment by zhuw0312** [comment]
`[root@wf-zhuwei-test-1 ~]# kubectl -n kube-system exec -it  cilium-2cz2s -- cilium status --all-controllers --all-health --all-redirects --debug
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.2) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [eth0 172.16.251.189 (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.11.2 (v1.11.2-17b0dbd)
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 8/254 allocated from 10.0.3.0/24, 
BandwidthManager:       EDT with BPF   [eth0]
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      51/51 healthy
  Name                                          Last success   Last error    Count   Message
  bpf-map-sync-cilium_lxc                       7s ago         never         0       no error   
  bpf-map-sync-cilium_throttle                  6s ago         never         0       no error   
  cilium-health-ep                              26s ago        never         0       no error   
  dns-garbage-collector-job                     39s ago        never         0       no error   
  endpoint-1018-regeneration-recovery           never          never         0       no error   
  endpoint-1158-regeneration-recovery           never          never         0       no error   
  endpoint-1429-regeneration-recovery           never          never         0       no error   
  endpoint-391-regeneration-recovery            never          never         0       no error   
  endpoint-426-regeneration-recovery            never          never         0       no error   
  endpoint-51-regeneration-recovery             never          never         0       no error   
  endpoint-720-regeneration-recovery            never          never         0       no error   
  endpoint-897-regeneration-recovery            never          never         0       no error   
  endpoint-gc                                   4m39s ago      never         0       no error   
  ipcache-inject-labels                         1h9m34s ago    1h9m38s ago   0       no error   
  k8s-heartbeat                                 9s ago         never         0       no error   
  mark-k8s-node-as-available                    1h9m27s ago    never         0       no error   
  metricsmap-bpf-prom-sync                      3s ago         never         0       no error   
  resolve-identity-1018                         4m27s ago      never         0       no error   
  restoring-ep-identity (1158)                  1h9m28s ago    never         0       no error   
  restoring-ep-identity (1429)                  1h9m28s ago    never         0       no error   
  restoring-ep-identity (391)                   1h9m28s ago    never         0       no error   
  restoring-ep-identity (426)                   1h9m28s ago    never         0       no error   
  restoring-ep-identity (51)                    1h9m28s ago    never         0       no error   
  restoring-ep-identity (720)                   1h9m28s ago    never         0       no error   
  restoring-ep-identity (897)                   1h9m28s ago    never         0       no error   
  sync-endpoints-and-host-ips                   28s ago        never         0       no error   
  sync-lb-maps-with-k8s-services                1h9m28s ago    never         0       no error   
  sync-policymap-1018                           16s ago        never         0       no error   
  sync-policymap-1158                           17s ago        never         0       no error   
  sync-policymap-1429                           17s ago        never         0       no error   
  sync-policymap-391                            18s ago        never         0       no error   
  sync-policymap-426                            16s ago        never         0       no error   
  sync-policymap-51                             18s ago        never         0       no error   
  sync-policymap-720                            4s ago         never         0       no error   
  sync-policymap-897                            17s ago        never         0       no error   
  sync-to-k8s-ciliumendpoint (1018)             6s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (1158)             7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (1429)             7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (391)              7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (426)              7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (51)               7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (720)              7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (897)              7s ago         never         0       no error   
  template-dir-watcher                          never          never         0       no error   
  update-k8s-node-annotations                   1h9m38s ago    never         0       no error   
  waiting-initial-global-identities-ep (1158)   1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (1429)   1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (391)    1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (426)    1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (51)     1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (897)    1h9m28s ago    never         0       no error   
Proxy Status:                    OK, ip 10.0.3.187, 0 redirects active on ports 10000-20000
Hubble:                          Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 10.72   Metrics: Disabled
Encryption:                      Disabled
Cluster health:                  3/3 reachable    (2022-04-06T03:40:06Z)
  Name                           IP               Node        Endpoints
  wf-zhuwei-test-3 (localhost)   172.16.251.189   reachable   reachable
  wf-zhuwei-test-1               172.16.247.229   reachable   reachable
  wf-zhuwei-test-2               172.16.247.231   reachable   reachable
`

**Comment by zhuw0312** [comment]
> [root@wf-zhuwei-test-1 ~]# kubectl -n kube-system exec -it  cilium-2cz2s -- cilium status --all-controllers --all-health --all-redirects --debug
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.2) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [eth0 172.16.251.189 (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.11.2 (v1.11.2-17b0dbd)
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 8/254 allocated from 10.0.3.0/24, 
BandwidthManager:       EDT with BPF   [eth0]
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      51/51 healthy
  Name                                          Last success   Last error    Count   Message
  bpf-map-sync-cilium_lxc                       7s ago         never         0       no error   
  bpf-map-sync-cilium_throttle                  6s ago         never         0       no error   
  cilium-health-ep                              26s ago        never         0       no error   
  dns-garbage-collector-job                     39s ago        never         0       no error   
  endpoint-1018-regeneration-recovery           never          never         0       no error   
  endpoint-1158-regeneration-recovery           never          never         0       no error   
  endpoint-1429-regeneration-recovery           never          never         0       no error   
  endpoint-391-regeneration-recovery            never          never         0       no error   
  endpoint-426-regeneration-recovery            never          never         0       no error   
  endpoint-51-regeneration-recovery             never          never         0       no error   
  endpoint-720-regeneration-recovery            never          never         0       no error   
  endpoint-897-regeneration-recovery            never          never         0       no error   
  endpoint-gc                                   4m39s ago      never         0       no error   
  ipcache-inject-labels                         1h9m34s ago    1h9m38s ago   0       no error   
  k8s-heartbeat                                 9s ago         never         0       no error   
  mark-k8s-node-as-available                    1h9m27s ago    never         0       no error   
  metricsmap-bpf-prom-sync                      3s ago         never         0       no error   
  resolve-identity-1018                         4m27s ago      never         0       no error   
  restoring-ep-identity (1158)                  1h9m28s ago    never         0       no error   
  restoring-ep-identity (1429)                  1h9m28s ago    never         0       no error   
  restoring-ep-identity (391)                   1h9m28s ago    never         0       no error   
  restoring-ep-identity (426)                   1h9m28s ago    never         0       no error   
  restoring-ep-identity (51)                    1h9m28s ago    never         0       no error   
  restoring-ep-identity (720)                   1h9m28s ago    never         0       no error   
  restoring-ep-identity (897)                   1h9m28s ago    never         0       no error   
  sync-endpoints-and-host-ips                   28s ago        never         0       no error   
  sync-lb-maps-with-k8s-services                1h9m28s ago    never         0       no error   
  sync-policymap-1018                           16s ago        never         0       no error   
  sync-policymap-1158                           17s ago        never         0       no error   
  sync-policymap-1429                           17s ago        never         0       no error   
  sync-policymap-391                            18s ago        never         0       no error   
  sync-policymap-426                            16s ago        never         0       no error   
  sync-policymap-51                             18s ago        never         0       no error   
  sync-policymap-720                            4s ago         never         0       no error   
  sync-policymap-897                            17s ago        never         0       no error   
  sync-to-k8s-ciliumendpoint (1018)             6s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (1158)             7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (1429)             7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (391)              7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (426)              7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (51)               7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (720)              7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (897)              7s ago         never         0       no error   
  template-dir-watcher                          never          never         0       no error   
  update-k8s-node-annotations                   1h9m38s ago    never         0       no error   
  waiting-initial-global-identities-ep (1158)   1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (1429)   1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (391)    1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (426)    1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (51)     1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (897)    1h9m28s ago    never         0       no error   
Proxy Status:                    OK, ip 10.0.3.187, 0 redirects active on ports 10000-20000
Hubble:                          Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 10.72   Metrics: Disabled
Encryption:                      Disabled
Cluster health:                  3/3 reachable    (2022-04-06T03:40:06Z)
  Name                           IP               Node        Endpoints
  wf-zhuwei-test-3 (localhost)   172.16.251.189   reachable   reachable
  wf-zhuwei-test-1               172.16.247.229   reachable   reachable
  wf-zhuwei-test-2               172.16.247.231   reachable   reachable

**Comment by zhuw0312** [comment]
`kubectl -n kube-system exec -it  cilium-2cz2s -- cilium status --all-controllers --all-health --all-redirects --debug`


> 

Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.2) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [eth0 172.16.251.189 (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.11.2 (v1.11.2-17b0dbd)
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 8/254 allocated from 10.0.3.0/24, 
BandwidthManager:       EDT with BPF   [eth0]
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      51/51 healthy
  Name                                          Last success   Last error    Count   Message
  bpf-map-sync-cilium_lxc                       7s ago         never         0       no error   
  bpf-map-sync-cilium_throttle                  6s ago         never         0       no error   
  cilium-health-ep                              26s ago        never         0       no error   
  dns-garbage-collector-job                     39s ago        never         0       no error   
  endpoint-1018-regeneration-recovery           never          never         0       no error   
  endpoint-1158-regeneration-recovery           never          never         0       no error   
  endpoint-1429-regeneration-recovery           never          never         0       no error   
  endpoint-391-regeneration-recovery            never          never         0       no error   
  endpoint-426-regeneration-recovery            never          never         0       no error   
  endpoint-51-regeneration-recovery             never          never         0       no error   
  endpoint-720-regeneration-recovery            never          never         0       no error   
  endpoint-897-regeneration-recovery            never          never         0       no error   
  endpoint-gc                                   4m39s ago      never         0       no error   
  ipcache-inject-labels                         1h9m34s ago    1h9m38s ago   0       no error   
  k8s-heartbeat                                 9s ago         never         0       no error   
  mark-k8s-node-as-available                    1h9m27s ago    never         0       no error   
  metricsmap-bpf-prom-sync                      3s ago         never         0       no error   
  resolve-identity-1018                         4m27s ago      never         0       no error   
  restoring-ep-identity (1158)                  1h9m28s ago    never         0       no error   
  restoring-ep-identity (1429)                  1h9m28s ago    never         0       no error   
  restoring-ep-identity (391)                   1h9m28s ago    never         0       no error   
  restoring-ep-identity (426)                   1h9m28s ago    never         0       no error   
  restoring-ep-identity (51)                    1h9m28s ago    never         0       no error   
  restoring-ep-identity (720)                   1h9m28s ago    never         0       no error   
  restoring-ep-identity (897)                   1h9m28s ago    never         0       no error   
  sync-endpoints-and-host-ips                   28s ago        never         0       no error   
  sync-lb-maps-with-k8s-services                1h9m28s ago    never         0       no error   
  sync-policymap-1018                           16s ago        never         0       no error   
  sync-policymap-1158                           17s ago        never         0       no error   
  sync-policymap-1429                           17s ago        never         0       no error   
  sync-policymap-391                            18s ago        never         0       no error   
  sync-policymap-426                            16s ago        never         0       no error   
  sync-policymap-51                             18s ago        never         0       no error   
  sync-policymap-720                            4s ago         never         0       no error   
  sync-policymap-897                            17s ago        never         0       no error   
  sync-to-k8s-ciliumendpoint (1018)             6s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (1158)             7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (1429)             7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (391)              7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (426)              7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (51)               7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (720)              7s ago         never         0       no error   
  sync-to-k8s-ciliumendpoint (897)              7s ago         never         0       no error   
  template-dir-watcher                          never          never         0       no error   
  update-k8s-node-annotations                   1h9m38s ago    never         0       no error   
  waiting-initial-global-identities-ep (1158)   1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (1429)   1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (391)    1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (426)    1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (51)     1h9m28s ago    never         0       no error   
  waiting-initial-global-identities-ep (897)    1h9m28s ago    never         0       no error   
Proxy Status:                    OK, ip 10.0.3.187, 0 redirects active on ports 10000-20000
Hubble:                          Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 10.72   Metrics: Disabled
Encryption:                      Disabled
Cluster health:                  3/3 reachable    (2022-04-06T03:40:06Z)
  Name                           IP               Node        Endpoints
  wf-zhuwei-test-3 (localhost)   172.16.251.189   reachable   reachable
  wf-zhuwei-test-1               172.16.247.229   reachable   reachable
  wf-zhuwei-test-2               172.16.247.231   reachable   reachable

**Comment by zhuw0312** [comment]
i got this question soloved.

**Comment by pchaigno** [comment]
What was the issue?
