### ISSUE TITLE
ioctl FIONREAD returning incorrect value when sockops is enabled

### ISSUE THREAD

**Issue by travisghansen** [cilium/cilium#19304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I was experiencing degraded service to a single pod gitlab install fronted by traefik ingress controller. I would get seemingly sporadic responses, timeouts were getting hit, etc. After some investigation it became clear that all the failure scenarios resulted from the `traefik` pod running on the same node as the `gitlab` pod. The `gitlab` pod runs `nginx` and the local webserver.

Traffic pattern looks like this: client -> LB IP -> traefik pod -> gitlab pod (nginx, then downward from there)

Putting `strace` on `nginx` worker I discovered that the divergent entry (from a `traefik` pod on another node, or sockops disabled) was the following:

```
# good
23:53:04.483136 ioctl(24<TCP:[6330084]>, FIONREAD, [844]) = 0 <0.000069>

# bad
23:48:10.930982 ioctl(19<TCP:[6295929]>, FIONREAD, [0]) = 0 <0.000148>
```

`nginx` is reading the headers from the `traefik` request with a default value of `1024` (`client_header_buffer_size 1k;`) bytes and then (seemingly) asks via the ioctl how much data is left. Since the return is `0` the request is never fully read and does not proceed further.

```
# full cycle good (request coming from traefik pod on different node OR sockops disabled on the same node
23:53:04.481036 recvfrom(24<TCP:[6330084]>, "GET /thansen/kb/-/tree/master HTTP/1.1\r\n...<more header data>", 1024, 0, NULL, NULL) = 1024 <0.000043>
23:53:04.483136 ioctl(24<TCP:[6330084]>, FIONREAD, [844]) = 0 <0.000069>
23:53:04.484932 recvfrom(24<TCP:[6330084]>, "<remaining header data>\r\n\r\n", 7588, 0, NULL, NULL) = 844 <0.000032>

# full cycle bad
23:48:10.927413 recvfrom(19<TCP:[6295929]>, "GET /thansen/kb/-/tree/master HTTP/1.1\r\n...<more header data>", 1024, 0, NULL, NULL) = 1024 <0.000156>
23:48:10.930982 ioctl(19<TCP:[6295929]>, FIONREAD, [0]) = 0 <0.000148>
23:48:10.934761 epoll_wait(14<anon_inode:[eventpoll]>, [{events=EPOLLIN, data={u32=1790157744, u64=139687011525552}}], 512, 14397) = 1 <5.239812>
```

When the pods on are the same node and sockops enabled, the behavior is 100% consistent and reproducible, meaning what on the surface originally appeared sporadic is indeed not sporadic at all when broken down to the specific flow.

### Cilium Version

`1.11.3`

### Kernel Version

`5.16.16`

### Kubernetes Version

`v1.22.7+rke2r1`

### Anything else?

I haven't explicitly tried this but I'm assuming the same would happen with the body as well. For example if a request had headers < 1024 but a body > body buffer size likely the request would stall after the same ioctl call.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by travisghansen** [comment]
Not stale.

**Comment by travisghansen** [comment]
Not stale.

**Comment by travisghansen** [comment]
Not stale.

**Comment by travisghansen** [comment]
Not stale.

**Comment by travisghansen** [comment]
Not stale.

**Comment by travisghansen** [comment]
Not stale.

**Comment by brb** [comment]
The sockops feature was removed from Cilium (https://github.com/cilium/cilium/issues/23556). Closing the issue.
