### ISSUE TITLE
Conntrack table reset on agent restart

### ISSUE THREAD

**Issue by zuzzas** [cilium/cilium#19367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Established connections are forgotten after agent restart. Policy drops start happening on packets on established connections. I believe it's related to CT table drops. Here is what happened to etcd CT entries after agent restart:

```
root@cilium-master-2:~# crictl exec "$(crictl ps | grep cilium-agent | awk '{print $1}')" cilium bpf ct list global  | grep :2379  | wc -l
691
root@cilium-master-2:~# crictl exec "$(crictl ps | grep cilium-agent | awk '{print $1}')" cilium bpf ct list global  | grep :2379  | wc -l
7
root@cilium-master-2:~# crictl exec "$(crictl ps | grep cilium-agent | awk '{print $1}')" cilium bpf ct list global  | grep :2379  | wc -l
254
root@cilium-master-2:~# crictl exec "$(crictl ps | grep cilium-agent | awk '{print $1}')" cilium bpf ct list global  | grep :2379  | wc -l
396
```

### Cilium Version

```
Client: 1.11.2  go version go1.17.7 linux/amd64
Daemon: 1.11.2  go version go1.17.7 linux/amd64
```

### Kernel Version

```
Linux cilium-master-2 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"0000000000000000000000000000000000000000", GitTreeState:"archive", BuildDate:"2022-04-01T14:22:50Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

I will include sysdump in a separate comment. Have some trouble uploading to GitHub.

### Relevant log output

```text
Ethernet        {Contents=[..14..] Payload=[..118..] SrcMAC=00:00:5e:00:01:00 DstMAC=d0:0d:ba:34:90:bc EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..98..] Version=4 IHL=5 TOS=0 Length=2519 Id=54017 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=18846 SrcIP=10.160.128.31 DstIP=10.160.128.34 Options=[] Padding=[]}
TCP     {Contents=[..32..] Payload=[..66..] SrcPort=2379(etcd-client) DstPort=24824 Seq=2205186449 Ack=1078895699 DataOffset=8 FIN=false SYN=false RST=false PSH=true ACK=true URG=false ECE=false CWR=false NS=false Window=368 Checksum=8011
 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:388221802/215800007 0x1723cb6a0cdcd8c7)] Padding=[]}
  Packet has been truncated
  Failed to decode layer: No decoder for layer type Payload
CPU 01: MARK 0x0 FROM 137 from-network: 2533 bytes (128 captured), state new, interface eth0, orig-ip 0.0.0.0
CPU 01: MARK 0x0 FROM 137 DEBUG: Successfully mapped addr=10.160.128.31 to identity=7
CPU 01: MARK 0x0 FROM 137 DEBUG: Successfully mapped addr=10.160.128.34 to identity=1
CPU 01: MARK 0x0 FROM 137 DEBUG: Conntrack lookup 1/2: src=10.160.128.31:2379 dst=10.160.128.34:24824
CPU 01: MARK 0x0 FROM 137 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0x0 FROM 137 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x0 FROM 137 DEBUG: Successfully mapped addr=10.160.128.31 to identity=7
CPU 01: MARK 0x0 FROM 137 DEBUG: Policy evaluation would deny packet from 7 to 1
```

### Anything else?

Here is a discussion on Cilium's Slack that led to this issue: https://cilium.slack.com/archives/CDKG8NNHK/p1649402467641139

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zuzzas** [comment]
The file size of the sysdump exceeds the size of max file uploads. I've previously uploaded the file on Cilium's Slack: https://cilium.slack.com/files/U021ND67600/F03AQG5DGSW/sysdump-3.zip

**Comment by zuzzas** [comment]
I've also managed to get `cilium monitor -D -vv` immediately after monitor socket becomes available after agent restart. You can grep for `action deny`. You'll find a lot of `:2379`  flows that are _new_ to the CT table
[cilium.log](https://github.com/cilium/cilium/files/8451447/cilium.log)

.

**Comment by zuzzas** [comment]
Here is a sysdump from a single Node immediately (less than a minute) after restarting the agent.

[sysdump-4.zip](https://github.com/cilium/cilium/files/8451866/sysdump-4.zip)

**Comment by aditighag** [comment]
>CPU 01: MARK 0x0 FROM 137 DEBUG: Conntrack lookup 1/2: src=10.160.128.31:2379 dst=10.160.128.34:24824
CPU 01: MARK 0x0 FROM 137 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0x0 FROM 137 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x0 FROM 137 DEBUG: Successfully mapped addr=10.160.128.31 to identity=7
CPU 01: MARK 0x0 FROM 137 DEBUG: Policy evaluation would deny packet from 7 to 1

I don't quite follow why CT table reset would lead to policy drops. CT map is an LRU map so it's possible that CT entries are not found for ongoing connections. I would have expected policy verdicts to be based on identity mappings. If there are policy drops, shouldn't we look into whether ipcache entries are correctly preserved after agent restart?

**Comment by zuzzas** [comment]
Perhaps it's related to https://github.com/cilium/cilium/pull/19360? Checking out v1.11.4 right now, will update.

**Comment by borkmann** [comment]
> Perhaps it's related to #19360? Checking out v1.11.4 right now, will update.

I think that is very likely. Did you check results in meantime?

**Comment by zuzzas** [comment]
I've done some digging around and believe I've found the culprit: https://github.com/cilium/cilium/blob/a8e3fa283cf40b330035265bf83d63800b296bcf/pkg/maps/ctmap/gc/gc.go#L234-L244

That means that all connection tracking data non-endpoints will get scrubbed on every agent restart? And all existing connections will break due to aforementioned Host Policy enforcement intricacies. What's the reasoning here? Am I the only one who has this issue?

**Comment by kvaps** [comment]
cc @tgraf

**Comment by jrajahalme** [comment]
@pchaigno It seems likely that this CT scrubbing should have been extended to know about host endpoint entries when host networking namespace connections started to be tracked in #11507??

**Comment by zuzzas** [comment]
I've created a horrible, wrong and inefficient patch that solves the problem: https://gist.github.com/zuzzas/54c1081a6115b663fe06ac82661a4826

Essentially, it boils down to not removing that are not in the Endpoint list, but those that are not in ipcache CIDR list.

I am not proficient enough in the Cilium code to create a proper solution nor to verify whether the approach works it is similar to skipping initial CT map GC completely. I'd be happy if someone from the Cilium team would help.

**Comment by pchaigno** [comment]
> @pchaigno It seems likely that this CT scrubbing should have been extended to know about host endpoint entries when host networking namespace connections started to be tracked in https://github.com/cilium/cilium/pull/11507??

That's correct I think. The host endpoint doesn't have an IPv4 and an IPv6 addresses because it has multiple, we don't support that yet, so I preferred not to add any to avoid confusion. As a result, this code will add an empty entry:
https://github.com/cilium/cilium/blob/82c742f2e9fb65fb3fc392c7dcb3b4e22b69c650/pkg/maps/ctmap/gc/gc.go#L242-L243
We should fix this to add all host endpoint IP addresses, only when the host firewall is enabled. I was not aware of this logic when I worked on https://github.com/cilium/cilium/pull/11507.

@zuzzas Do you still have this issue if you disable the host firewall?

<br>

> Essentially, it boils down to not removing CT entries that are not in the Endpoint list, but those that are not in the ipcache CIDR list.

What's the rationale for this? AFAICS, it will make things worse because it will remove entries for all connections between restored pods. I also wouldn't expect it to fix your issue unless you were testing a connection from the host network namespace to an IP outside the cluster and had a policy CIDR rule for that destination IP.

**Comment by zuzzas** [comment]
>Do you still have this issue if you disable the host firewall?

I do not. Also, when policy audit mode is set to `true`.

>What's the rationale for this?

None at all. Just exploring. It won't remove anything at all, since the ipcache apparently contains 0.0.0.0/0 :laughing: 
```
IP                 IDENTITY                                                                                   SOURCE
0.0.0.0/0          world 
```

**Comment by zuzzas** [comment]
@pchaigno 

That'll solve most of the issues with intra-cluster connections. I am still wary of probable interruptions when connecting to external services. Such as databases or message-queues.

The main issue that I have is that kernel's netfilter does not behave this way. All connections are persisted regardless of any user-space program restarts. Why does cilium has to have this _forced_ GC and kernel's connection tracking does not?

**Comment by zuzzas** [comment]
>Could you try the fix

Will do that today.

>It should fix the issue for connections from the host to external services as well.

Ah, it excludes both src and dst host IPs from GC!
