### ISSUE TITLE
cilium server mesh High delay

### ISSUE THREAD

**Issue by tony-code25** [cilium/cilium#19362]
Test QPS peak with  connections:64,  envoy workers:16
istio (1.13.2)  result  19564.4qps   avg: 3.271 ms  P90 : 5.812ms 
cilium-server-mesh result  13784.0qps   avg: 4.642 ms  P90 : 20.980ms
cilium-server-mesh Request success probability 80%
why cilium result so ？

**Comment by jtaleric** [comment]
Hey @FanHTao - Can you define the SUT here a bit -- for both scenarios (isitio and cilium)? Platform, kernel, etc..

On one of the cilium pods can you run `cilium status --verbose` 

`> kubectl get pods -n kube-system -l k8s-app=cilium`
`> kubectl exec -it -n kube-system <one of the pods from the above list> -- cilium status --verbose`

**Comment by FanHTao** [comment]
client pod and server pod on different node，client is the most possible request server with 64 connections.
platform : k8s v1.20.15
kernel : Linux master 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

kubectl exec -it -n kube-system cilium-9dr4v -- cilium status --verbose
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20 (v1.20.15) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumEnvoyConfig", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Probe   [ens4f0 10.232.60.147 (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.11.0 (v1.11.0-d8460a4)
NodeMonitor:            Disabled
Cilium health daemon:   Ok
IPAM:                   IPv4: 12/254 allocated from 10.0.0.0/24,
Allocated addresses:
  10.0.0.104 (kube-system/otelcol-hubble-collector-qllbq[restored])
  10.0.0.130 (health)
  10.0.0.164 (default/fortio-server-7c5799bc79-jpjv8[restored])
  10.0.0.165 (istio-system/prometheus-9f4947649-7zqj7[restored])
  10.0.0.170 (cilium-monitoring/prometheus-655fb888d7-2m9fv[restored])
  10.0.0.176 (istio-system/grafana-556f8998cd-l6hms[restored])
  10.0.0.182 (kube-system/coredns-74ff55c5b-z9qdb[restored])
  10.0.0.192 (router)
  10.0.0.239 (cilium-monitoring/grafana-d69c97b9b-grl69[restored])
  10.0.0.250 (istio-system/kiali-8679df7b97-7chhb[restored])
  10.0.0.29 (default/foo-app[restored])
  10.0.0.64 (default/bar-app[restored])
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Clock Source for BPF:   ktime
Controller Status:      81/81 healthy
  Name                                          Last success   Last error   Count   Message
  bpf-map-sync-cilium_lxc                       7s ago         never        0       no error
  cilium-health-ep                              41s ago        never        0       no error
  dns-garbage-collector-job                     59s ago        never        0       no error
  endpoint-1086-regeneration-recovery           never          never        0       no error
  endpoint-1096-regeneration-recovery           never          never        0       no error
  endpoint-1390-regeneration-recovery           never          never        0       no error
  endpoint-1503-regeneration-recovery           never          never        0       no error
  endpoint-1764-regeneration-recovery           never          never        0       no error
  endpoint-294-regeneration-recovery            never          never        0       no error
  endpoint-3107-regeneration-recovery           never          never        0       no error
  endpoint-3343-regeneration-recovery           never          never        0       no error
  endpoint-382-regeneration-recovery            never          never        0       no error
  endpoint-482-regeneration-recovery            never          never        0       no error
  endpoint-604-regeneration-recovery            never          never        0       no error
  endpoint-781-regeneration-recovery            never          never        0       no error
  endpoint-gc                                   1m59s ago      never        0       no error
  ipcache-inject-labels                         1m40s ago      1m46s ago    0       no error
  k8s-heartbeat                                 29s ago        never        0       no error
  mark-k8s-node-as-available                    1m42s ago      never        0       no error
  metricsmap-bpf-prom-sync                      4s ago         never        0       no error
  neighbor-table-refresh                        12s ago        never        0       no error
  resolve-identity-1086                         1m41s ago      never        0       no error
  resolve-identity-1096                         1m40s ago      never        0       no error
  resolve-identity-1390                         1m37s ago      never        0       no error
  resolve-identity-1503                         1m41s ago      never        0       no error
  resolve-identity-1764                         1m40s ago      never        0       no error
  resolve-identity-294                          1m36s ago      never        0       no error
  resolve-identity-3107                         1m36s ago      never        0       no error
  resolve-identity-3343                         1m36s ago      never        0       no error
  resolve-identity-382                          1m40s ago      never        0       no error
  resolve-identity-482                          1m37s ago      never        0       no error
  resolve-identity-781                          1m37s ago      never        0       no error
  restoring-ep-identity (1096)                  1m42s ago      never        0       no error
  restoring-ep-identity (1390)                  1m42s ago      never        0       no error
  restoring-ep-identity (1503)                  1m42s ago      never        0       no error
  restoring-ep-identity (1764)                  1m41s ago      never        0       no error
  restoring-ep-identity (294)                   1m41s ago      never        0       no error
  restoring-ep-identity (3107)                  1m41s ago      never        0       no error
  restoring-ep-identity (3343)                  1m41s ago      never        0       no error
  restoring-ep-identity (382)                   1m42s ago      never        0       no error
  restoring-ep-identity (482)                   1m42s ago      never        0       no error
  restoring-ep-identity (604)                   1m42s ago      never        0       no error
  restoring-ep-identity (781)                   1m42s ago      never        0       no error
  sync-endpoints-and-host-ips                   46s ago        never        0       no error
  sync-lb-maps-with-k8s-services                1m42s ago      never        0       no error
  sync-policymap-1086                           35s ago        never        0       no error
  sync-policymap-1096                           35s ago        never        0       no error
  sync-policymap-1390                           35s ago        never        0       no error
  sync-policymap-1503                           35s ago        never        0       no error
  sync-policymap-1764                           35s ago        never        0       no error
  sync-policymap-294                            35s ago        never        0       no error
  sync-policymap-3107                           34s ago        never        0       no error
  sync-policymap-3343                           35s ago        never        0       no error
  sync-policymap-382                            35s ago        never        0       no error
  sync-policymap-482                            34s ago        never        0       no error
  sync-policymap-604                            33s ago        never        0       no error
  sync-policymap-781                            35s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (1086)             11s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (1096)             2s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (1390)             7s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (1503)             2s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (1764)             2s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (294)              6s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (3107)             6s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (3343)             6s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (382)              12s ago        never        0       no error
  sync-to-k8s-ciliumendpoint (482)              7s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (604)              2s ago         never        0       no error
  sync-to-k8s-ciliumendpoint (781)              7s ago         never        0       no error
  template-dir-watcher                          never          never        0       no error
  update-k8s-node-annotations                   1m58s ago      never        0       no error
  waiting-initial-global-identities-ep (1096)   1m42s ago      never        0       no error
  waiting-initial-global-identities-ep (1390)   1m42s ago      never        0       no error
  waiting-initial-global-identities-ep (1503)   1m42s ago      never        0       no error
  waiting-initial-global-identities-ep (1764)   1m41s ago      never        0       no error
  waiting-initial-global-identities-ep (294)    1m41s ago      never        0       no error
  waiting-initial-global-identities-ep (3107)   1m41s ago      never        0       no error
  waiting-initial-global-identities-ep (3343)   1m41s ago      never        0       no error
  waiting-initial-global-identities-ep (382)    1m42s ago      never        0       no error
  waiting-initial-global-identities-ep (482)    1m42s ago      never        0       no error
  waiting-initial-global-identities-ep (781)    1m42s ago      never        0       no error
Proxy Status:   OK, ip 10.0.0.192, 0 redirects active on ports 10000-20000
Hubble:         Disabled
KubeProxyReplacement Details:
  Status:                 Probe
  Socket LB Protocols:    TCP, UDP
  Devices:                ens4f0 10.232.60.147 (Direct Routing)
  Mode:                   SNAT
  Backend Selection:      Random
  Session Affinity:       Enabled
  Graceful Termination:   Enabled
  XDP Acceleration:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767)
  - LoadBalancer:   Enabled
  - externalIPs:    Enabled
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   1184367
  TCP connection tracking       2368735
  Endpoint policy               65535
  Events                        56
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           2368735
  Neighbor table                2368735
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        56
  Sockmap                       65535
  Sock reverse NAT              1184367
  Tunnel                        65536
Encryption:                      Disabled
Cluster health:                  2/2 reachable   (2022-04-09T06:19:49Z)
  Name                           IP              Node      Endpoints
  kubernetes/node1 (localhost)   10.232.60.147   unknown   unknown
  kubernetes/master              10.232.60.146   unknown   unknown

**Comment by vincentmli** [comment]
> client pod and server pod on different node，client is the most possible request server with 64 connections. platform : k8s v1.20.15 kernel : Linux master 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

@FanHTao I am not familiar with service mesh, maybe you need to run on a newer kernel version than `5.4.0-107-generic`, try a most recent kernel ?

**Comment by jtaleric** [comment]
@FanHTao as @vincentmli mentioned, try a newer kernel. I have tested with - `5.16.0-051600-generic`

Considering the significant difference in latency and throughput, we only see a small difference in utilization (CPU) comparing the two. 

![image](https://user-images.githubusercontent.com/3965163/162956242-0f96d80b-7614-4af5-8be4-e0664e251fd6.png)

**Comment by FanHTao** [comment]
There are some occasional errors in my pressure test log.
          _http  resp 503   body: upstream connect error or disconnect/reset before headers. reset reason: connection failure_
I observed that the server is normal，What makes this error？

**Comment by jtaleric** [comment]
Hey @FanHTao - Not following the question here? 

You are seeing these 503s from the test tool, or something else?

**Comment by FanHTao** [comment]
Envoy Log：
[2022-04-20 01:37:02.344][929][debug][connection] [C512661] immediate connection error: 99
[2022-04-20 01:37:02.344][921][debug][client] [C512663] connecting
[2022-04-20 01:37:02.344][924][debug][connection] [C512662] immediate connection error: 99
[2022-04-20 01:37:02.344][921][debug][connection] [C512663] connecting to 10.0.0.205:8080
[2022-04-20 01:37:02.344][922][debug][pool] creating a new connection
[2022-04-20 01:37:02.344][921][debug][connection] [C512663] immediate connection error: 99
[2022-04-20 01:37:02.344][929][debug][connection] [C512659] raising immediate error
[2022-04-20 01:37:02.344][929][debug][connection] [C512659] closing socket: 0
[2022-04-20 01:37:02.344][924][debug][http] [C512597] new stream
[2022-04-20 01:37:02.344][922][debug][client] [C512664] connecting
[2022-04-20 01:37:02.344][922][debug][connection] [C512664] connecting to 10.0.0.205:8080
[2022-04-20 01:37:02.344][929][debug][client] [C512659] disconnect. resetting 0 pending requests
[2022-04-20 01:37:02.344][929][debug][pool] [C512659] client disconnected, failure reason: 
[2022-04-20 01:37:02.344][922][debug][connection] [C512664] immediate connection error: 99
[2022-04-20 01:37:02.344][929][debug][router] [C512598][S15092282274758931564] upstream reset: reset reason: connection failure, transport failure reason: 
[2022-04-20 01:37:02.345][929][debug][http] [C512598][S15092282274758931564] encoding headers via codec (end_stream=false):
':status', '503'
'test', 'fortio'
'content-length', '91'
'content-type', 'text/plain'
'date', 'Wed, 20 Apr 2022 01:37:02 GMT'
'server', 'envoy'

**Comment by jtaleric** [comment]
Hey @FanHTao Sorry, but it isn't clear to me why you would see this error with your test. How repeatable is the test you are building with Fortio?

**Comment by FanHTao** [comment]
Hey@jtaleric When concurrent requests are greater than envoy workers，100% appear。
this is port reuse conflict，  cilium manage envoy client port range？

**Comment by jtaleric** [comment]
cc @jrajahalme on the message mentioned above.

**Comment by vincentmli** [comment]
@FanHTao 

I happen to have envoy enabled in Cilium, could you describe what load test tool you used in your client test pod? what steps you performed in the load test  and how do you check envoy logs that has `503` ? sorry I am newbie to envoy too but I would like to dig into this further

**Comment by FanHTao** [comment]
@vincentmli  Problems caused by setting   src_address  port
![image](https://user-images.githubusercontent.com/25880450/169441444-5153e6e1-7702-4bbe-aae6-947c9ca1544a.png)

Modify the following code to repair
proxy/cilium/socket_option.h
![image](https://user-images.githubusercontent.com/25880450/169441818-ae3cf8f1-7233-4894-bacb-509a4aa39791.png)

**Comment by vincentmli** [comment]
@FanHTao nice! did you file issue or send PR to https://github.com/cilium/proxy?

**Comment by jrajahalme** [comment]
@FanHTao seems this was observed on Cilium Service Mesh beta. Cilium ingress will be released with Cilium 1.12, and it no longer tries to use the original source address (or port) for Ingress traffic, so this issue should no longer happen with it.

**Comment by James-Dao** [comment]
This issue also happen with cilium 1.12.

**Comment by James-Dao** [comment]
After following https://docs.cilium.io/en/v1.12/gettingstarted/servicemesh/envoy-traffic-management/ steps,   access the cluster ip on host .  If the selected backend is running the remote node ,i will response success, if the backend is running on the local node ,the envoy can not proxy the  request.  

curl -v <cluster ip of echo-service-1>:8080/foo

curl -v 10.96.131.12:8080
* About to connect() to 10.96.131.12 port 8080 (#0)
*   Trying 10.96.131.12...
* Connected to 10.96.131.12 (10.96.131.12) port 8080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.96.131.12:8080
> Accept: */*
> 
< HTTP/1.1 504 Gateway Timeout
< content-length: 24
< content-type: text/plain
< date: Sun, 07 Aug 2022 03:22:57 GMT
< server: envoy
< 
* Connection #0 to host 10.96.131.12 left intact


The log from hubble observer is as following:

Aug  6 15:00:26.869: 127.0.0.1:39220 (world) -> default/echo-service-2-5dfc4d5d4b-gf2p7:8080 (ID:81201) http-request FORWARDED (HTTP/1.1 GET http://10.96.131.12:8080/)
Aug  6 15:00:26.873: 127.0.0.1:39220 (world) <- default/echo-service-2-5dfc4d5d4b-gf2p7:8080 (ID:81201) http-response FORWARDED (HTTP/1.1 200 4ms (GET http://10.96.131.12:8080/))

Aug  6 15:00:48.484: 127.0.0.1:53388 (world) <- 127.0.0.1:17960 (world) http-response FORWARDED (HTTP/1.1 504 0ms (GET http://10.96.131.12:8080/)).
