### ISSUE TITLE
BPF host routing broken when sending from pod to local node's non-mananged netdev

### ISSUE THREAD

**Issue by brb** [cilium/cilium#19427]
When the BPF host routing feature is enabled (`--enable-host-legacy-routing=false`), a packet send from a pod to an IP address belonging to an interface of the same node, which the pod runs on, might be blackholed.

This happens, when there is no entry in the IPCache for that destination IP addr, and the destination is treated as `WORLD_ID`. This makes the packet to output via `skb_do_redirect()` which is invoked by the following function https://github.com/cilium/cilium/blob/v1.12.0-rc1/bpf/bpf_lxc.c#L944.

The redirect to e.g. a dummy device blackhols the packet.

To reproduce:
```
ip link add dev dummy0 type dummy
ip addr add 192.168.17.2/24 dev dummy0 scope link
ip link set dev dummy0 up

cilium bpf ipcache get 192.168.17.2
192.168.17.2 maps to identity identity=2 encryptkey=0 tunnelendpoint=0.0.0.0 # WORLD_ID == identity=2

# kubectl exec into pod or nsenter -t $POD_PID -n
ping 192.168.17.2
```
NOTE: changing the scope to `global` makes the cilium-agent to eventually add the IP addr as `HOST_ID` into the IPCache. The packet with the dst `HOST_ID` takes a different path in bpf_lxc which doesn't result in the drop.

**Comment by borkmann** [comment]
Related: https://github.com/cilium/cilium/commit/234e851aa7aa0cfcdd61e5efdedee869f147f8a4
