### ISSUE TITLE
bpf_skb_set_tunnel_key + redirect to a non-tunnel device might crash the kernel

### ISSUE THREAD

**Issue by brb** [cilium/cilium#19428]
While developing the WireGuard host2host encryption feature (https://github.com/cilium/cilium/pull/19407), I noticed that if redirecting after calling `bpf_skb_set_tunnel_key()` to a device which doesn't support the tunnel metadata crashes a VM. Unfortunately, I couldn't retrieve the dmesg as VirtualBox had immediately rebooted the machine.

I had the following modification in the `to-overlay` section:
```

__section("to-overlay")
int to_overlay(struct __ctx_buff *ctx)
{
	int ret;

	ret = encap_remap_v6_host_address(ctx, true);
	if (unlikely(ret < 0))
		goto out;

#ifdef ENABLE_WIREGUARD
	ret = wg_maybe_redirect_to_encrypt(ctx);
	if (ret == CTX_ACT_REDIRECT)
		return ret;
	else if (IS_ERR(ret))
		return send_drop_notify_error(ctx, src_id, ret, CTX_ACT_DROP,
					      METRIC_EGRESS);
#endif /* ENABLE_WIREGUARD */

...
```

The crash was triggered immediately after a pod has sent a packet to a remote pod via the tunnel.

Affected kernels: 5.15 and 5.17

**Comment by borkmann** [comment]
Not really related given you mentioned 5.17, but there were occasions we fixed in the past:
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c4c877b2732466b4c63217baad05c96f775912c7
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a188bb5638d41aa99090ebf2f85d3505ab13fba5

**Comment by borkmann** [comment]
@brb So basically datapath populated collect_md meta data, redirected to vxlan device, but then the above snippet decided to forward the skb to the wg dev instead which lead to eventual crash, right? (So I guess it could be repro'ed with a simple BPF prog, populating the tunnel key and then sending to a wg.)

**Comment by brb** [comment]
> Not really related given you mentioned 5.17

:man_facepalming: It was one of the 5.17 rc kernels. Let me try with 5.17.0.

**Comment by brb** [comment]
Crashed `Linux ceuse 5.17.1-arch1-1` which is my laptop. The laptop didn't freeze, but immediately rebooted. Unfortunately, nothing in `journalctl -r -b -1 -k`.

The diff from https://github.com/cilium/cilium/pull/19407:
```
diff --git a/bpf/bpf_overlay.c b/bpf/bpf_overlay.c
index 469603d45b..6d49269f54 100644
--- a/bpf/bpf_overlay.c
+++ b/bpf/bpf_overlay.c
@@ -38,6 +38,10 @@
 #include "lib/eps.h"
 #endif /* ENABLE_VTEP */
 
+#ifdef ENABLE_WIREGUARD
+#include "lib/wireguard.h"
+#endif
+
 #ifdef ENABLE_IPV6
 static __always_inline int handle_ipv6(struct __ctx_buff *ctx,
 				       __u32 *identity)
@@ -535,6 +539,15 @@ int to_overlay(struct __ctx_buff *ctx)
 	if (unlikely(ret < 0))
 		goto out;
 
+#ifdef ENABLE_WIREGUARD
+	ret = wg_maybe_redirect_to_encrypt(ctx);
+	if (ret == CTX_ACT_REDIRECT)
+		return ret;
+	else if (IS_ERR(ret))
+		return send_drop_notify_error(ctx, 0, ret, CTX_ACT_DROP,
+					      METRIC_EGRESS);
+#endif /* ENABLE_WIREGUARD */
+
 #ifdef ENABLE_BANDWIDTH_MANAGER
 	/* In tunneling mode, we should do this as close as possible to the
 	 * phys dev where FQ runs, but the issue is that the aggregate state
diff --git a/bpf/lib/encap.h b/bpf/lib/encap.h
index 5ec41ac5a7..e2614d31be 100644
--- a/bpf/lib/encap.h
+++ b/bpf/lib/encap.h
@@ -153,24 +153,24 @@ __encap_and_redirect_with_nodeid(struct __ctx_buff *ctx, __u32 tunnel_endpoint,
 {
 	int ret = 0;
 
-#ifdef ENABLE_WIREGUARD
-	/* Redirect the packet to the WireGuard tunnel device for encryption
-	 * if needed.
-	 *
-	 * A packet which previously was a subject to VXLAN/Geneve
-	 * encapsulation (e.g., pod2pod) is going to be encapsulated only once,
-	 * i.e., by the WireGuard tunnel netdev. This is so just to be
-	 * compatible with < the v1.12 behavior in which the pod2pod bypassed
-	 * VXLAN/Geneve encapsulation when the WG feature was on.
-	 */
-	ret = wg_maybe_redirect_to_encrypt(ctx);
-	if (ret == CTX_ACT_REDIRECT) {
-		return ret;
-	}
-	else if (IS_ERR(ret))
-		return send_drop_notify_error(ctx, seclabel, ret, CTX_ACT_DROP,
-					      METRIC_EGRESS);
-#endif /* ENABLE_WIREGUARD */
+//#ifdef ENABLE_WIREGUARD
+//	/* Redirect the packet to the WireGuard tunnel device for encryption
+//	 * if needed.
+//	 *
+//	 * A packet which previously was a subject to VXLAN/Geneve
+//	 * encapsulation (e.g., pod2pod) is going to be encapsulated only once,
+//	 * i.e., by the WireGuard tunnel netdev. This is so just to be
+//	 * compatible with < the v1.12 behavior in which the pod2pod bypassed
+//	 * VXLAN/Geneve encapsulation when the WG feature was on.
+//	 */
+//	ret = wg_maybe_redirect_to_encrypt(ctx);
+//	if (ret == CTX_ACT_REDIRECT) {
+//		return ret;
+//	}
+//	else if (IS_ERR(ret))
+//		return send_drop_notify_error(ctx, seclabel, ret, CTX_ACT_DROP,
+//					      METRIC_EGRESS);
+//#endif /* ENABLE_WIREGUARD */
 
 	ret = __encap_with_nodeid(ctx, tunnel_endpoint, seclabel,
 				  trace->reason, trace->monitor);
```

**Comment by NikAleksandrov** [comment]
Thanks, it's really easy to reproduce actually, setup 2 wireguard peers (connected/working) and then redirect to egress
on one of them, e.g. attach this to some other interface and run packets through it:
`static __inline int redir_data(struct __sk_buff *skb)
{
	struct bpf_tunnel_key key = {};

        key.tunnel_id = 50000;
        key.remote_ipv4 = 10203040;
        key.tunnel_ttl = 64;

        bpf_skb_set_tunnel_key(skb, &key, sizeof(key), BPF_F_ZERO_CSUM_TX);

	return bpf_redirect(TARGET_DEV_IFIDX, 0);
}

__section("egress")
int tc_egress(struct __sk_buff *skb)
{
        return redir_data(skb);
}
`
Interesting that my crashdump generated an empty vmcore. I was able to pull the trace via netconsole:
`[  263.693506] BUG: kernel NULL pointer dereference, address: 00000000000000e0
[  263.693908] #PF: supervisor read access in kernel mode
[  263.694174] #PF: error_code(0x0000) - not-present page
[  263.694424] PGD 0 P4D 0 
[  263.694653] Oops: 0000 [#1] PREEMPT SMP NOPTI
[  263.694876] CPU: 5 PID: 951 Comm: mausezahn Kdump: loaded Not tainted 5.18.0-rc1+ #522
[  263.695190] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1.fc35 04/01/2014
[  263.695529] RIP: 0010:dst_blackhole_mtu+0x17/0x20
[  263.695770] Code: 00 00 00 0f 1f 44 00 00 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 48 8b 47 10 48 83 e0 fc 8b 40 04 85 c0 75 09 48 8b 07 <8b> 80 e0 00 00 00 c3 66 90 0f 1f 44 00 00 48 89 d7 be 01 00 00 00
[  263.696339] RSP: 0018:ffffa4a4422fbb28 EFLAGS: 00010246
[  263.696600] RAX: 0000000000000000 RBX: ffff8ac9c3553000 RCX: 0000000000000000
[  263.696891] RDX: 0000000000000401 RSI: 00000000fffffe01 RDI: ffffc4a43fb48900
[  263.697178] RBP: ffffa4a4422fbb90 R08: ffffffff9622635e R09: 0000000000000002
[  263.697469] R10: ffffffff9b69a6c0 R11: ffffa4a4422fbd0c R12: ffff8ac9d18b1a00
[  263.697766] R13: ffff8ac9d0ce1840 R14: ffff8ac9d18b1a00 R15: ffff8ac9c3553000
[  263.698054] FS:  00007f3704c337c0(0000) GS:ffff8acaebf40000(0000) knlGS:0000000000000000
[  263.698470] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  263.698826] CR2: 00000000000000e0 CR3: 0000000117a5c000 CR4: 00000000000006e0
[  263.699214] Call Trace:
[  263.699505]  <TASK>
[  263.699759]  wg_xmit+0x411/0x450
[  263.700059]  ? bpf_skb_set_tunnel_key+0x46/0x2d0
[  263.700382]  ? dev_queue_xmit_nit+0x31/0x2b0
[  263.700719]  dev_hard_start_xmit+0xd9/0x220
[  263.701047]  __dev_queue_xmit+0x8b9/0xd30
[  263.701344]  __bpf_redirect+0x1a4/0x380
[  263.701664]  __dev_queue_xmit+0x83b/0xd30
[  263.701961]  ? packet_parse_headers+0xb4/0xf0
[  263.702275]  packet_sendmsg+0x9a8/0x16a0
[  263.702596]  ? _raw_spin_unlock_irqrestore+0x23/0x40
[  263.702933]  sock_sendmsg+0x5e/0x60
[  263.703239]  __sys_sendto+0xf0/0x160
[  263.703549]  __x64_sys_sendto+0x20/0x30
[  263.703853]  do_syscall_64+0x3b/0x90
[  263.704162]  entry_SYSCALL_64_after_hwframe+0x44/0xae
[  263.704494] RIP: 0033:0x7f3704d50506
[  263.704789] Code: 48 c7 c0 ff ff ff ff eb b7 66 2e 0f 1f 84 00 00 00 00 00 90 41 89 ca 64 8b 04 25 18 00 00 00 85 c0 75 11 b8 2c 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 72 c3 90 55 48 83 ec 30 44 89 4c 24 2c 4c 89
[  263.705652] RSP: 002b:00007ffe954b0b88 EFLAGS: 00000246 ORIG_RAX: 000000000000002c
[  263.706141] RAX: ffffffffffffffda RBX: 0000558bb259b490 RCX: 00007f3704d50506
[  263.706544] RDX: 000000000000004a RSI: 0000558bb259b7b2 RDI: 0000000000000003
[  263.706952] RBP: 0000000000000000 R08: 00007ffe954b0b90 R09: 0000000000000014
[  263.707339] R10: 0000000000000000 R11: 0000000000000246 R12: 00007ffe954b0b90
[  263.707735] R13: 000000000000004a R14: 0000558bb259b7b2 R15: 0000000000000001
[  263.708132]  </TASK>
[  263.708398] Modules linked in: bridge netconsole bonding [last unloaded: bridge]
[  263.708942] CR2: 00000000000000e0
`
I'll prepare a fix and selftest.

**Comment by borkmann** [comment]
Fixed in https://github.com/WireGuard/wireguard-linux/commit/c6476d123a28905e73b4e5b3169b6ebc45e8d674 . The commit will be routed to net tree, and then subsequently stable can pick it up.

**Comment by NikAleksandrov** [comment]
The fix has been applied to wireguard's tree.
