### ISSUE TITLE
Conn tracking for ICMP reply, but not request

### ISSUE THREAD

**Issue by lizrice** [cilium/cilium#19433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Here are some example Hubble flows showing some health-check pings:
```
Apr 13 13:02:23.818: 10.119.193.96 <> 10.174.52.143 to-overlay FORWARDED (ICMPv4 EchoRequest)
Apr 13 13:02:23.819: 10.119.193.96 -> 10.174.52.143 to-endpoint FORWARDED (ICMPv4 EchoRequest)
Apr 13 13:02:23.819: 10.119.193.96 <- 10.174.52.143 to-overlay FORWARDED (ICMPv4 EchoReply)
```
The `<>` in the first line suggests we don't know whether it's a request or reply, and @gandro tells me this info comes from connection tracking in the datapath. But the reply (third line) does have connection tracking, hence we get `<-` indicating that it's a reply. So this raises the question of why doesn't the request also have conn tracking? 

### Cilium Version

v1.12.0-rc1

### Kernel Version

5.4.181-99.354.amzn2.x86_64 (this was EKS)

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-dispatcher", GitCommit:"2a8027f41d28b788b001389f3091c245cd0a9a60", GitTreeState:"clean", BuildDate:"2022-01-21T20:32:40Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20220413-163052.zip](https://github.com/cilium/cilium/files/8483904/cilium-sysdump-20220413-163052.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
Could potentially be fixed in https://github.com/cilium/cilium/pull/19185 (cc @qmonnet).

**Comment by qmonnet** [comment]
#19185 should already be present in v1.12.0-rc1, so I guess not :/.

**Comment by qmonnet** [comment]
Maybe https://github.com/cilium/cilium/pull/19158?
