### ISSUE TITLE
Error: INSTALLATION FAILED: Chart.yaml file is missing

### ISSUE THREAD

**Issue by akoserwal** [cilium/cilium#19457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

helm install cilium cilium/cilium --namespace=kube-system
Error: INSTALLATION FAILED: Chart.yaml file is missing

 helm install cilium cilium/cilium --version 1.10.9 \
  --namespace kube-system

### Cilium Version

cilium-cli: v0.11.1 compiled with go1.18.1 on darwin/amd64
cilium image (default): v1.11.3
cilium image (stable): v1.11.3

### Kernel Version

 Darwin Kernel Version 20.6.0 x86_64

### Kubernetes Version

osd 4.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
```
$ helm install cilium cilium/cilium --namespace=kube-system
NAME: cilium
LAST DEPLOYED: Fri Apr 15 16:41:05 2022
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.11.3.

For any further help, visit https://docs.cilium.io/en/v1.11/gettinghelp
```

I'm unable to reproduce this issue. Make sure you run `helm install` on a directory that doesn't have another directory named 'cilium' in it.

**Comment by akoserwal** [comment]
yes, you are right
