### ISSUE TITLE
L7 visibility annotations break cluster's external connectivity

### ISSUE THREAD

**Issue by szucsitg** [cilium/cilium#19455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I added annotation to gain L7 visibility metrics for Hubble, and it breaks cluster external connection.

Our cluster is EKS, with kube-proxy replacement strict mode and ENI network mode, on Bottlerocket OS. No network policy deployed. I start a container, e.g. `kubectl run multitool --image=praqma/network-multitool`.

I exec into the container, and issue `curl -Lv https://cilium.io` or any other externally hosted url and it returns successfully.
Then I add the annotation: `io.cilium.proxy-visibility: <Egress/443/TCP/HTTP>` and it breaks the connection.

Cluster internal services running https on 443 port works without any issue.

We tested it with default kube-proxy settings, it provides the same result. Cilium monitor and Hubble UI both shows that the connection was forwarded successfully.

### Cilium Version

1.11.3 62aa82d

### Kernel Version

5.10.102

### Kubernetes Version

v1.21.9-eks-0d102a7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by szucsitg** [comment]
I tested this with AL2 based EKS nodes, and also in KinD, and it breaks the traffic similarly. Therefore it's likely not AWS specific.

**Comment by gandro** [comment]
I think this is expected and the connectivity breakage is due to the proxy not being able to decode the request. The visibility annotations cannot be used with HTTP**S** traffic, only plain-text HTTP traffic.

To get visibility into HTTPS traffic, you will need to use the following guide and use a CiliumNetworkPolicy (instead of a visibility annotation): https://docs.cilium.io/en/v1.11/gettingstarted/tls-visibility/

**Comment by szucsitg** [comment]
Thank you very much for the response. I doubled checked the [page](https://docs.cilium.io/en/v1.11/policy/visibility/), and there's no mention that it'll practically break encrypted connections. What doesn't add up; could you explain why cluster internal encrypted traffic worked fine with the annotation?

**Comment by gandro** [comment]
> What doesn't add up; could you explain why cluster internal encrypted traffic worked fine with the annotation?

I don't expect this to work either. There is simply no way Cilium can decrypt encrypted traffic of a HTTPS connection without you providing Cilium with the TLS private keys first, it does not matter where the HTTPS endpoint is.

You would have to provide more details about your in cluster setup to answer your question for certain. What you may have done is terminate the HTTPS traffic first (e.g. via K8s Ingress) and then inspect the plain-text internal HTTP traffic. That is possible, but this does not work for encrypted egress traffic to the Internet.

**Comment by szucsitg** [comment]
in my test cluster the encrypted service was argocd-server (with self-signed cert) and it actually worked fine. I'm not saying that it provided visibility, as you mentioned without decrypting the traffic it's impossible, but the connection was working. therefore it must be something that provided fallback instead of reseting the TCP connection, as with cluster external services.

**Comment by gandro** [comment]
Generally speaking, the way the annotation works is that it will redirect any traffic on the provided port to a proxy which expects the corresponding parser (e.g. in your example, every TCP connection with destination port 443 will be decoded as HTTP traffic). If the parser is unable to decode the traffic, the connection will be dropped by the proxy (this is arguably not great for a visibility annotation, but the behavior stems from the fact that this mechanism was originally built for enforcing L7 policies, in which case dropping unknown traffic is the correct thing to do)

It might be that you were using different ports on the backend (e.g. 443 on the service, but 8443 on the container) on the service and thus the self-signed HTTPS traffic was not actually redirected to the proxy. Again, more details would be needed here.

**Comment by szucsitg** [comment]
I think that's the reason, as I targeted the service, but the pod has 8443 port. I appreciate the detailed explanation. If you don't mind, I'd add these information to the docs, so it'll be more clear for others as well, and close the issue with that PR. If you agree, I'll do this some time this week.

**Comment by aanm** [comment]
@szucsitg will you submit a PR? Thanks!

**Comment by szucsitg** [comment]
@aanm yes, I'm still planning but got swamped. I'll try to allocate some time this week.
