### ISSUE TITLE
publish cilium arm/arm64 images on quay

### ISSUE THREAD

**Issue by akoserwal** [cilium/cilium#19467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Failed to pull image "[quay.io/cilium/operator-generic:v1.11.3@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787](http://quay.io/cilium/operator-generic:v1.11.3@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787)": rpc error: code = NotFound desc = failed to pull and unpack image "[quay.io/cilium/operator-generic@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787](http://quay.io/cilium/operator-generic@sha256:5b81db7a32cb7e2d00bb3cf332277ec2b3be239d9e94a8d979915f4e6648c787)": no match for platform in manifest: not found

### Cilium Version

cilium-cli: v0.11.1 
cilium image (default): v1.11.3
cilium image (stable): v1.11.3

### Kernel Version

GNU/Linux 11 (bullseye) 5.15.32-v7l+

### Kubernetes Version

NAME STATUS ROLES AGE VERSION INTERNAL-IP EXTERNAL-IP OS-IMAGE KERNEL-VERSION CONTAINER-RUNTIME
raspberrypi Ready control-plane,master 94m v1.22.7+k3s1 Raspbian GNU/Linux 11 (bullseye) 5.15.32-v7l+ containerd://1.5.9-k3s1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
as per https://quay.io/repository/cilium/operator-generic?tab=tags&tag=latest, arm64 is already published, is your issue mainly related to arm only?

**Comment by akoserwal** [comment]
Yes, thank you
