### ISSUE TITLE
if i set kubeProxyReplacement=strict , pod connected to k8s api server(u can curl -k https://10.254.0.1:443 in pod) failed

### ISSUE THREAD

**Issue by liuyixian123** [cilium/cilium#19469]
so what cause this problem？i found if i manully add iptables rule( iptables -t nat -I POSTROUTING -s 192.168.0.0/16 -j MASQURADE), it conneted to 10.254.0.1 success。

**Comment by aditighag** [comment]
@liuyixian123 When you created this issue, you should've been prompted with a template. Can you fill in those details? At the very least, can you write a proper one-line description of the problem in the title, and provide details regarding cilium version, sysdump, etc?
