### ISSUE TITLE
If I set KubeProxyReplacement=disabled，I've found pod visit another node IP failed

### ISSUE THREAD

**Issue by liuyixian123** [cilium/cilium#19468]
but when I add iptables rule( iptables -t nat -I POSTROUTING -s 192.168.0.0/16 -j MASQURADE)，it connected ok!。what should i configure something to avoid this problem?

**Comment by vincentmli** [comment]
@liuyixian123 could you provide more detail on your deployment detail like  cilium config? cilium sysdump would be even better

**Comment by liuyixian123** [comment]
> @liuyixian123 could you provide more detail on your deployment detail like cilium config? cilium sysdump would be even better
cilium version is v1.10.2
![image](https://user-images.githubusercontent.com/94579721/163740557-d6908955-145b-4e5a-b872-f21d4c54517a.png)

**Comment by vincentmli** [comment]
what about cilium agent log or cilium sysdump?
