### ISSUE TITLE
CFP: seperate the masquerade interface from the devices params

### ISSUE THREAD

**Issue by konghui** [cilium/cilium#19497]
## Cilium Feature Proposal
        

**Is your feature request related to a problem?**

My server has two network interface `lan0` and `wan0` , `wan0` has a public IP address, `lan0`  has a internal IP address. But recently I found a security problem that user can connect Kubernetes NodePort  via public IP address.  So I add a config devices: `lan0` on the cilium-config.  After doing this the security problem seems was fixed. But it introduced a new problem that all the pod with cluster IP can't connect public address, such as 1.1.1.1.  The reason is that cilium not masquerade the package which connect to the public IP address.  If I  removed the config devices: `lan0` , it would  masquerade to `wan0`  IP correctly.

**Describe the feature you'd like**
 BPF NodPort device, BPF masquerading device should seperate as two params.
User should have a option to set which interface they want BPF masquerading running.

**(Optional) Describe your proposed solution**
`--devices` params should be  replaced as `--bpf-nodeport-devices`, `--bpf-nasquerade-devices` and `--host-firewall-devices`

**Comment by brb** [comment]
We have a very similar issue - https://github.com/cilium/cilium/issues/13732.
