### ISSUE TITLE
BGP not working in 1.10.10

### ISSUE THREAD

**Issue by lewisdiamond** [cilium/cilium#19509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Install cilium 1.10.10 using the documented helm command https://docs.cilium.io/en/v1.10/gettingstarted/bgp/
2. Create the configmap with the required addresses and peers
3. deploy a service of type loadbalancer

Expected:
The service gets an IP assigned
A BGP session is created between peers
Routes to the service are propagated

Actual:
The service gets an IP assigned
A BGP session is created between peers
Routes are NOT propagated

### Cilium Version

1.10.10

### Kernel Version

5.10.102

### Kubernetes Version

1.21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lewisdiamond** [comment]
By the way, this works perfectly fine in `1.11.4`

**Comment by borkmann** [comment]
@ldelossa might this be related to https://github.com/cilium/cilium/pull/18358, looks like it went to 1.11 but potentially not marked for 1.10?
