### ISSUE TITLE
GSOD'22

### ISSUE THREAD

**Issue by Shorla** [cilium/cilium#19506]
I am interested in applying to cilium project for GSOD but realised there isn't information on applying to the project or submitting proposal for the project

**Comment by Shorla** [comment]
I can work on this, is it fine?

**Comment by xmulligan** [comment]
@Shorla the link for the application is [here](https://docs.google.com/forms/d/e/1FAIpQLSdxhTPfMv9s4r3UMIAkScY_lTWfUB43MEIlK8NiQoOHsToj-g/viewform?usp=send_form) thanks for pointing this out
