### ISSUE TITLE
CFP: Allow to specify host nic as egress gateway source (instead of just pods)

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#19515]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**
Yes

If so, please describe the problem
I'd like to use a k8s cluster with cilium installed as a k8s based router / gateway for non pod traffic.

**Describe the feature you'd like**
I'd like to have the possibility to specify host nics as an EgressGatewayNATPolicy rule so that requests on the specified host interface are masked and forwarded via the specified egress gateway.

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

**Comment by iFrozenPhoenix** [comment]
@aanm any plans on supporting this?

**Comment by jibi** [comment]
Hey @iFrozenPhoenix :wave: 
I don't think there's any plan for now to support this as the required changes would quite involved and we haven't received any PR from the community
