### ISSUE TITLE
Setting kubeProxyReplacement=strict does not take effect

### ISSUE THREAD

**Issue by fsckzy** [cilium/cilium#19548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed it according to this document, then went to verify and found
https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/
```
[root@k8sm1 cilium]# kubectl exec -it -n kube-system cilium-zdfxc -- cilium status | grep KubeProxyReplacement
KubeProxyReplacement:   Disabled
```

### Cilium Version

cilium 1.11.4

### Kernel Version

```
centos 7
5.4.190-1.el7.elrepo.x86_64
```

### Kubernetes Version

```
k8s 1.19.16
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment]
@fsckzy can you share your cilium agent log? it might tell you the problem

**Comment by aditighag** [comment]
The kube-proxy-replacement feature has a set of kernel level requirements due to which the agent can override user configured flags. Either attach a sysdump from your cluster, or check the agent logs for further information as @vincentmli suggested.
