### ISSUE TITLE
Endpoint regeneration unit test benchmark

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1954]
- [ ] Mock datapath interactions required for endpoint generation
- [ ] Add unit test and benchmark around endpoint generation

**Comment by raybejjani** [comment]
partially addressed in https://github.com/cilium/cilium/pull/2361

**Comment by tgraf** [comment]
Endpoint regenerations are not really a problem anymore due to massive policy engine improvements and BPF templating.
