### ISSUE TITLE
Ginkgo CI: merge Packer scripts from `cilium/packer-ci-build` into `cilium/packer-ubuntu-16.10` Packer scripts

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1956]
Parent: #1839 

cc: @tgraf @jrajahalme 
The Ginkgo CI uses a different VM image than that of the current tests. This is not conducive to the developer workflow, as the existing VM (built by scripts stored at `cilium/packer-ubuntu-16.10` repository) has a bunch of useful functionality for testing locally that the current Ginkgo CI image uses. 

Merge these two Packer builds together in the `cilium/packer-ubuntu-16.10` repository and build a new image based off of these changes. This is being tracked in the packer-ubuntu-16.10 repository by this issue: https://github.com/cilium/packer-ubuntu-16.10/issues/23

Once the above issue is completed, consume the image built and pushed to the Vagrant Cloud in this repository in `test/Vagrantfile`.

**Comment by ianvernon** [comment]
I'm becoming more and more in favor of just using the existing VM we have instead of having a new one for the runtime tests, as it's not worth the hassle of maintaining two separate VMs. Any thoughts on this?

**Comment by tgraf** [comment]
The required changes have been merged into:
https://github.com/cilium/packer-ubuntu-16.10

**Comment by tgraf** [comment]
> I'm becoming more and more in favor of just using the existing VM we have instead of having a new one for the runtime tests, as it's not worth the hassle of maintaining two separate VMs. Any thoughts on this?

What was the reason to switch over to another image? I'm not sure I understand the tradeoffs yet.

**Comment by ianvernon** [comment]
I don't know why this was added either, but it was approved. I want to get rid of this separate image. It's going to be a hassle to maintain and doesn't add any benefits for the build AFAICT. If we can package what was done in this separate image into the one we currently use, then we have the best of both worlds. I've been working locally in a private branch of `packer-ubuntu-16.10` to do this. Will have a PR hopefully soon so we can get rid of the other VM.

**Comment by eloycoto** [comment]
@tgraf @ianvernon 

The main reason to switch to another image was to make the test faster. 

With the cilium image not all the dependencies are installed, so each time that a new build is executed need to wait to install dependencies. 

With the new image, dependencies are installed, certs for docker registry are in place and tests are faster. The only thing that it's not installed is kubernetes, which runs per each scope.  

Regards

**Comment by ianvernon** [comment]
Instead of building a new image entirely, we can just update the Packer build for the VM that already exists for the Cilium build, which I have done locally. I'm currently testing this locally. This will result in us having only to maintain one VM image for use in testing / development instead of two.

**Comment by ianvernon** [comment]
I stopped working on this due to too much churn with the Envoy work being done at the same time. Working on getting the runtime tests to use the latest `packer-ubuntu-16.10` image first.

**Comment by ianvernon** [comment]
@eloycoto can I close this?

**Comment by eloycoto** [comment]
Yes!
