### ISSUE TITLE
Catch ginkgo test regressions on macOS

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#19569]
We've had [instances](https://github.com/cilium/cilium/commit/3222f50d05d722e39563fa65fe99b52c0858941a) of [PRs](https://github.com/cilium/cilium/commit/ea75a7204849356d5bb2cfe3230b44d1ef2c32c2) breaking ginkgo test runs on macOS. Add a GitHub action for `darwin` target to catch such regressions on the PRs introducing platform specific code changes. 

Some of the options that were discussed for the GH action - 

- Run `GOOS=darwin go build` in the `test` directory as ginkgo does.
- `GOOS=darwin ginkgo -dryRun`

**Comment by jrajahalme** [comment]
I was not aware how ginkgo builds the Go code. If `go build` in `test` is all it does natively, then I don't see a need for adding dependency to Ginkgo itself, like I earlier proposed (the 2nd option above).

**Comment by aditighag** [comment]
@cscetbon Here is the directory where the e2e ginkgo tests are triggered - https://github.com/cilium/cilium/tree/master/test. I can assign you the issue whenever you ready to start working on it. Feel free to follow-up in the #development slack channel if you have questions, or need any feedback.

**Comment by cscetbon** [comment]
@aditighag you can assign it to me 😉

**Comment by aditighag** [comment]
> @aditighag you can assign it to me 😉

Go for it!

**Comment by cscetbon** [comment]
@aditighag It seems didn't like my force push with a new commit having the required sign off. I made the PR a draft for now but it needs an approval to kick off the [build-commits](https://github.com/cilium/cilium/actions/runs/3178254090) workflow
