### ISSUE TITLE
Review all usages of `fmt.Sprintf()` or similar `fmt` function inside hot paths

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#19571]
`fmt.Sprintf()` is well-known for not being opimal in terms of CPU and memory allocations. If these functions are called in hot paths such as `pkg/policy/api` or even parts of `pkg/policy`, it can be quite impactful, especially in environments that experience high or bursty churn. 

Writing a benchmark and replacing the current code with `strings.Builder` or `bytes.NewBuffer` can show us if we can achieve some quick wins.

Some examples: 

* https://github.com/cilium/cilium/pull/19570
* https://github.com/cilium/cilium/pull/19423

**Comment by MikeLing** [comment]
Hi @christarazi ,I'm new to cilium and I think this issue can be my starting point about cilium contribution. Can you please assign this issue to me. Thanks

**Comment by MikeLing** [comment]
I just change some code in `decision.go` and the benchmark output like:
<img width="622" alt="截屏2022-04-30 下午4 01 03" src="https://user-images.githubusercontent.com/2166227/166097322-11100868-3a96-4123-a7bf-47c0778f3653.png">

Does it make sense to you to optimize? I will commit PR if so.
Thank you

**Comment by christarazi** [comment]
Splitting makes sense to me.

**Comment by MikeLing** [comment]
@christarazi Does this commit make sense to you? https://github.com/MikeLing/cilium/commit/b86b803fdd1b08411a4a4c48d808fe13c0439baa

**Comment by christarazi** [comment]
Yes please submit a PR.

**Comment by MikeLing** [comment]
> Yes please submit a PR.

Done ;) 

https://github.com/cilium/cilium/pull/19822

**Comment by MikeLing** [comment]
Hi @christarazi , these 3 PRs (https://github.com/cilium/cilium/pull/19822, https://github.com/cilium/cilium/pull/19704, https://github.com/cilium/cilium/pull/19661) have been approved. Could we merge them although some CI tests failed due to container timeout? 

Just want to avoid too many PR pending parallel, so I can head to other part of code. Thank you

**Comment by christarazi** [comment]
Please rebase all PRs and ping me so I can retrigger the tests. Sorry, CI has not been very stable lately.

**Comment by MikeLing** [comment]
> Please rebase all PRs and ping me so I can retrigger the tests. Sorry, CI has not been very stable lately.

No problem :D, I just rebase and push all of them.

**Comment by MikeLing** [comment]
Hmmm, the CI failed again :(

**Comment by aanm** [comment]
@christarazi @MikeLing can we close this issue or are still usages of `fmt.Sprintf` to be fixed?

**Comment by christarazi** [comment]
@aanm This command output is giving me relevant files to investigate: 

```
rg 'fmt.Sprintf' --glob '!vendor' --glob '!api' --glob '!test' --glob '!cilium' --glob '!bugtool' --glob '!tools' -l | sort -u | rg -v 'test.go'
```

**Comment by MikeLing** [comment]
> @christarazi @MikeLing can we close this issue or are still usages of `fmt.Sprintf` to be fixed?

Will follow up this issue and start to solve the reset of `fmt` issue

**Comment by MikeLing** [comment]
@christarazi Does this draft PR make sense to you? I skip the benchmark part since it's in `main.go`. But the code places I changed may be called multiple times and may effect the performance with `fmt.Sprintf`.

**Comment by christarazi** [comment]
Thanks for your contributions. For that one, that code is not necessarily in the hot path. That code is likely only ever called once, so performance improvements there don't really have much benefit.

**Comment by schlosna** [comment]
Is there a list of places that you all would like to target? If one wanted to contribute PRs in this area, is there a structure you would want them submitted (e.g by pkg)?

**Comment by christarazi** [comment]
I would look at `pkg/policy` and `pkg/endpoint`. There may be code that these packages import that is worth looking into, so problematic code may not actually reside in these packages, but rather they're involved in the code path.
