### ISSUE TITLE
CFP: Document behaviour of Egress NAT Gateway when using 0.0.0.0/0

### ISSUE THREAD

**Issue by threeseed** [cilium/cilium#19588]
It is not clear from reading the [Egress Gateway](https://docs.cilium.io/en/v1.10/gettingstarted/egress-gateway/) page what the behaviour of this feature will be when using 0.0.0.0/0 for destinationCIDRs.

Will it block internal traffic as per this [issue](https://github.com/cilium/cilium/issues/17295) ? API Server ? etc.

**Comment by aanm** [comment]
@jibi can you take a look?

**Comment by jibi** [comment]
Hey @nadenf :wave: 

There's a PR currently being reviewed to update the Egress Gateway documentation: https://github.com/cilium/cilium/pull/19862. It will be part of the 1.12 release and it also explains what's the behavior for 0.0.0.0/0 policies (any internal cluster IP will be excluded from the egress gateway SNAT logic)

**Comment by aanm** [comment]
Fixed by https://github.com/cilium/cilium/pull/19862
