### ISSUE TITLE
Remove attached bpf_xdp upon "cilium cleanup"

### ISSUE THREAD

**Issue by brb** [cilium/cilium#19586]
`cilium cleanup` doesn't remove a previously attached XDP progs by Cilium. This will lead to packet drops, as the cmd removes the prog maps leading to the XDP prog missing tail calls.

The removal of the XDP prog should happen before the maps removal.

Similar to https://github.com/cilium/cilium/issues/10067.

**Comment by zhanghe9702** [comment]
@brb , i'd like to start a pr for this, but it seems only cilium-agent known which devices were attached bpf_xdp.o , is it exist simple method for this info :-)?

**Comment by brb** [comment]
@zhanghe9702 Thanks for taking the task. Please see https://github.com/cilium/cilium/issues/10067#issuecomment-1018255492 where we discussed potential ways to identify that a program belongs to Cilium. The cmd should work when cilium-agent is not running.

**Comment by brb** [comment]
We could change the `bpf_xdp_entry` to e.g., `cilium_bpf_xdp_entry`. This would be used in the XDP prog name which you can retrieve with `bpftool prog show id 220`. Another idea is to set the tag field (haven't checked whether it's feasible).

Maybe @borkmann has other ides.
