### ISSUE TITLE
[dev-VM] make CIDRs & IPs consistent (k8s vs Cilium)

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#19594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The dev-VM environment doesn't configure the same CIDRs / IPs for `kubelet` and `cilium`. See eg. the PodCIDRs in the log output.

Harmonize these, so that users see consistent information and the different IPAM modes show the same behaviour.

### Cilium Version

Client: 1.11.90 6a97d2bace 2022-04-26T19:28:01+03:00 go version go1.18beta2 linux/amd64
Daemon: 1.11.90 6a97d2bace 2022-04-26T19:28:01+03:00 go version go1.18beta2 linux/amd64

### Kernel Version

Linux k8s1 5.17.0-rc2-g1127170d457e #1 SMP PREEMPT Thu Feb 10 21:30:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
$ kubectl get ciliumnodes.cilium.io -o yaml
apiVersion: v1
items:
- apiVersion: cilium.io/v2
  kind: CiliumNode
  metadata:
  ...
    name: k8s1
  ...
  spec:
    addresses:
    - ip: 192.168.60.11
      type: InternalIP
    - ip: fd00::b
      type: InternalIP
    - ip: 10.11.0.188
      type: CiliumInternalIP
    - ip: fd04::c624
      type: CiliumInternalIP
    ...
    health:
      ipv4: 10.11.0.137
      ipv6: fd04::ddc6
    ipam:
      podCIDRs:
      - 10.11.0.0/24
      - fd04::/112


$ kubectl get nodes k8s1 -o yaml
apiVersion: v1
kind: Node
...
spec:
  podCIDR: 10.16.0.0/16
  podCIDRs:
  - 10.16.0.0/16
  - fd02::/96
status:
  addresses:
  - address: 192.168.60.11
    type: InternalIP
  - address: k8s1
    type: Hostname
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NikhilSharmaWe** [comment]
@julianwiedmann I would like to work on making CIDRs & IPs consistent. Do we need to have 
(CiliumNode) spec.ipam.podCIDRs == (Node) spec.podCIDRs ?

Could you please provide some idea or code pointers for making this change.
