### ISSUE TITLE
CFP: Enable ARP on MetalLB

### ISSUE THREAD

**Issue by lewisdiamond** [cilium/cilium#19630]
## Cilium Feature Proposal

For many non-production and even some production environments, ARP support would provide an easier access to virtual IPs for services of type LoadBalancer.

Cilium's MetalLB integration disables ARP ( https://github.com/cilium/cilium/blob/master/pkg/bgp/speaker/metallb.go#L66 ). Could this restriction be lifted in a near future? I'm assuming there's a good reason for disabling it, was this decision documented somewhere?

**Comment by christarazi** [comment]
Hi @lewisdiamond, we are moving away from the MetalLB implementation in favor of an built-in BGP solution in v1.12 and beyond.

**Comment by aanm** [comment]
Closing as we are moving away from MetalLB

**Comment by maxpain** [comment]
Will Cilium support L2/ARP mode for LoadBalancer services?
