### ISSUE TITLE
Queue k8s watcher updates

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1966]
We currently process updates from k8s synchronously, processing may invoke blocking kvstore operations which can take a long time. Instead, build a queue of events and process them in background go subroutines.

- [x] Maintain a queue of received events for each resource type.
- [x] Make a deep copy
- [x] Process events of each resource type in a background go subroutine which is allowed to block for a long time.
- [ ] Add a timeout for the processing (2 minutes?) and cancel event processing.

**Comment by aanm** [comment]
> Maintain a queue of received events for each resource type.

Each watcher already has its own queue, can't we use that queue plus the timeout?

**Comment by tgraf** [comment]
> Each watcher already has its own queue, can't we use that queue plus the timeout?

Are you talking about the queue inside the controller? Looking at how Kubernetes itself handles event notifications, it queues up events and handles them async in a handler to make sure that the controller loop can continue receiving. We don't do this right now, we execute all of the required actions directly in the handler as below and require the controller to wait until the operations have been completed.

```golang
        ciliumNetworkPolicyHandler := cache.ResourceEventHandlerFuncs{
                AddFunc:    d.addCiliumNetworkPolicy,
                UpdateFunc: d.updateCiliumNetworkPolicy,
                DeleteFunc: d.deleteCiliumNetworkPolicy,
        }
```

**Comment by aanm** [comment]
Each controller contains an internal queue. I'll add a new queue for each resource type to have a keep retry feature.
