### ISSUE TITLE
datapath: Split snat_v{4,6}_process() into two functions (SNAT and rev-SNAT)

### ISSUE THREAD

**Issue by brb** [cilium/cilium#19660]
Split the `snat_v{4,6}_process()` functions into `nat_snat_v{4,6}()` and `nat_rev_snat_v{4,6}()`.

The proposed change would not only improve the readability of the datapath code, but also should reduce the verifier complexity of the code path which is responsible for doing the rev-SNAT translations, as no new SNAT mapping needs to be find for this code path (only the lookup in the BPF SNAT map).

After inspecting the `bpf/lib/nodeport.h`, we have the following code paths which involve the SNAT:
- `to-netdev@bpf_host`: the `snat_v*_process()` is called with `NAT_DIR_EGRESS`. It is used to SNAT outgoing packets.
- `from-netdev@bpf_host` (via `nodeport_lb{4,6}()`):
   - When a service is not found, the function is called with `NAT_DIR_INGRESS`. It is used to rev-SNAT incoming packets (e.g., outside => pod, replies from remote service backends).
   - When a service is found, with `NAT_DIR_EGRESS`. It is used to SNAT a service request to a remote node.

From the above, `nat_snat_v*()` would be called for `NAT_DIR_EGRESS`, while `nat_rev_snat_v*()` for `NAT_DIR_INGRESS`.

**Comment by sahid** [comment]
Hello Team, I do start working on it. This will be needed [by ](https://github.com/cilium/cilium/pull/18414) to reduce complexity.

**Comment by brb** [comment]
The current view for NodePort BPF ingress packet flow (WIP):

```mermaid
flowchart TD
    A[from-netdev] -->|CILIUM_CALL_IPV4_FROM_NETDEV| B{"bpf_skip_nodeport()?"}
    B --> |No| C["nodeport_lb4()"]
    B --> |Yes| B1["// further packet process"]
    C --> D["lb4_lookup_service()"]
    D --> E{"svc ?"}
    E --> |No| F[" "]
    F --> |dir=NAT_DIR_INGRESS\nCILIUM_CALL_IPV4_NODEPORT_NAT4| G["tail_nodeport_nat_ipv4()"]
    G --> H["snat_v4_process()"]
    H --> J{"Reverse mapping exist?"}
    J --> |No| K["bpf_skip_nodeport_set()"]
    K --> |CILIUM_CALL_IPV4_FROM_NETDEV| B
    J --> |"Yes\n(This can be rev-SNAT for outside2pod)"| L["tail_rev_nodeport_lb4()"]
```
