### ISSUE TITLE
Ensure that cilium can handle older node-monitor readers

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#1967]
### Description of requested functionality
We encode node-monitor -> reader data with Go's gob. This works but it is easy to break compatibility with an older reader as we update the payload structs. We also, separately, encode the ` monitor/payload.Meta` struct and then the ` monitor/payload.Payload` struct on the wire. This requires a client to encode this behaviour as part of the protocol.
We should decide on the compatibility policy here, and support it. Some possible avenues:
- Readers must indicate a version to the node-monitor on connection, and will receive an error or data in return. This might work as a HTTP protocol upgrade.

- The data encoding format, and the data we're encoding are guaranteed to be backwards compatible. This is easier on the readers and keeps our protocol simple. It does limit the changes we can make, however, and might mean we have redundant fields used by older and newer agents.

- We simply include a version field in each payload and clients are expected to check that and report an error if they cannot support it.

@scanf  What do you think?

**Comment by aalemayhu** [comment]
Thanks for following up. Not sure, need to think about this some more. 
Adding API team.

cc: @cilium/api

**Comment by rlenglet** [comment]
How about moving to gRPC and using a gRPC stream? gRPC will offer multiple solutions to versioning. The gRPC method could take a version parameter. Or we could have multiple gRPC services or methods, one per version.
There were separate discussions about pushing filtering to node monitor. That will require something sophisticated like gRPC.

**Comment by raybejjani** [comment]
gRPC works too! I'll make this a 1.0-gap ticket so we at least look at it again before then.

**Comment by aalemayhu** [comment]
I don't think I will have enough cycles for adding this. @raybejjani maybe you and @rlenglet can work on this together?

**Comment by raybejjani** [comment]
I'm also currently a little bogged down with other things, but I expect a gRPC switch would be best in the long term (this also implies using protobuf instead of gob/json).
Would either of you have more time in around November 27? I expect to have cleared out most of my backlog by then.
