### ISSUE TITLE
test: Upgarde gingko to v2

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#19687]
Related to the comment https://github.com/cilium/cilium/pull/19248#issuecomment-1081561295

As gingko v1 is EOL, we should consider to upgrade it to v2.

**Comment by sayboras** [comment]
thanks for your interest, I am assigning issue to you. Feel free to reach out in #development Cilium OSS channel.

**Comment by brb** [comment]
Not sure whether it's worth tackling, as we are currently in a long process to migrate the e2e ginkgo tests to cilium-cli's connectivity checks.

**Comment by sayboras** [comment]
Closing this issue as it's not required anymore.
