### ISSUE TITLE
Wrong dest MAC used in server existing egress connection after a new connection established from same client to same server IP/port

### ISSUE THREAD

**Issue by VMAthreyas** [cilium/cilium#19696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While running cilium with **"enable-bpf-masquerade: "true"** we could see if a second connection started with same client, then communication from server to first session of the client goes through wrong MAC address. 

```
bash-5.1# ip -o link | awk '$2 != "lo:" {print $2, $(NF-2)}'
lxc_health@if532735: ff:ff:ff:ff:ff:ff
lxc96f5f0332029@if476415: ff:ff:ff:ff:ff:ff
lxcf474c04bd961@if476417: ff:ff:ff:ff:ff:ff
bond0: 12:d9:8b:92:d3:94
dummy0: 96:3d:50:ec:51:b8
eth0: 0c:42:a1:29:bf:0c
eth1: 0c:42:a1:29:bf:0d
lxc14f26ecd512d@if476421: ff:ff:ff:ff:ff:ff
eth2: 0c:42:a1:41:a0:de
eth3: 0c:42:a1:41:a0:df
lxc171f263a8860@if476423: ff:ff:ff:ff:ff:ff
teql0: qlen
tunl0@NONE: 0.0.0.0
sit0@NONE: 0.0.0.0
ip6tnl0@NONE: ::
veth-b@if13: ff:ff:ff:ff:ff:ff
lxcc86bf6bce904@if531981: ff:ff:ff:ff:ff:ff
cilium_net@cilium_host: f6:ed:8a:14:23:c8
cilium_host@cilium_net: 32:b3:f9:c5:8e:df
cilium_vxlan: 86:d1:85:5e:43:5e
lxc19bd78513794@if487959: ff:ff:ff:ff:ff:ff
lxc54c2e3c7d2f3@if475581: ff:ff:ff:ff:ff:ff
lxc53e6307d6809@if488157: ff:ff:ff:ff:ff:ff
lxc00b7cc5da958@if476413: ff:ff:ff:ff:ff:ff
bash-5.1# exit

bash-5.1# ip neigh
169.254.0.1 dev eth3 lladdr 0c:29:ef:c2:b5:21 PERMANENT proto zebra
169.254.0.1 dev eth1 lladdr 0c:29:ef:c2:d7:a1 PERMANENT proto zebra
169.254.0.1 dev eth0 lladdr 0c:29:ef:c2:b5:21 PERMANENT proto zebra
10.183.184.204 dev eth0 lladdr 0c:29:ef:c2:b5:21 STALE
10.130.63.62 dev veth-b lladdr 56:1f:8a:a2:8b:50 REACHABLE
169.254.0.1 dev eth2 lladdr 0c:29:ef:c2:d7:a1 PERMANENT proto zebra
fe80::541f:8aff:fea2:8b50 dev veth-b lladdr 56:1f:8a:a2:8b:50 STALE
fe80::e29:efff:fec2:b521 dev eth0 lladdr 0c:29:ef:c2:b5:21 router REACHABLE
fe80::e29:efff:fec2:b521 dev eth3 lladdr 0c:29:ef:c2:b5:21 router REACHABLE
fe80::e29:efff:fec2:d7a1 dev eth1 lladdr 0c:29:ef:c2:d7:a1 router REACHABLE
fe80::e29:efff:fec2:d7a1 dev eth2 lladdr 0c:29:ef:c2:d7:a1 router REACHABLE
bash-5.1# exit

```
Traffic captured at server pod end during initial client and server communication.

`15:44:37.345686 0c:29:ef:c2:d7:a1 > 0c:42:a1:41:a0:de, ethertype IPv4 (0x0800), length 73: 10.133.243.6.48646 > 10.183.176.1.5678: Flags [P.], seq 34:41, ack 51, win 221, options [nop,nop,TS val 2863763961 ecr 2734884165], length 7
15:44:37.345874 0c:42:a1:41:a0:de > 0c:29:ef:c2:d7:a1, ethertype IPv4 (0x0800), length 66: 10.183.176.1.5678 > 10.133.243.6.48646: Flags [.], ack 41, win 506, options [nop,nop,TS val 2737182416 ecr 2863763961], length 0
`

At this time, if we initiate second session from same client, eventhough we see acknowledgment of packet message never reaches the server.

Traffic cpatured at server pod end during second session between same client and server communication

`15:45:36.852543 0c:29:ef:c2:b5:21 > 0c:42:a1:29:bf:0c, ethertype IPv4 (0x0800), length 74: 10.133.243.6.48648 > 10.183.176.1.5678: Flags [P.], seq 41:49, ack 1, win 221, options [nop,nop,TS val 2863823467 ecr 2734981878], length 8
15:45:36.852646 0c:42:a1:29:bf:0c > 0c:29:ef:c2:b5:21, ethertype IPv4 (0x0800), length 66: 10.183.176.1.5678 > 10.133.243.6.48648: Flags [.], ack 49, win 506, options [nop,nop,TS val 2737241923 ecr 2863823467], length 0
`

Now if we try to send some packets from server to first session of the client, it will try to go through eth2 with mac address of eth0 and data is not sent.

`15:45:57.825074 0c:42:a1:41:a0:de > 0c:29:ef:c2:b5:21, ethertype IPv4 (0x0800), length 75: 10.183.176.1.5678 > 10.133.243.6.48646: Flags [P.], seq 51:60, ack 41, win 506, options [nop,nop,TS val 2737262895 ecr 2863763961], length 9
15:45:58.030740 0c:42:a1:41:a0:de > 0c:29:ef:c2:b5:21, ethertype IPv4 (0x0800), length 75: 10.183.176.1.5678 > 10.133.243.6.48646: Flags [P.], seq 51:60, ack 41, win 506, options [nop,nop,TS val 2737263101 ecr 2863763961], length 9
15:45:58.238751 0c:42:a1:41:a0:de > 0c:29:ef:c2:b5:21, ethertype IPv4 (0x0800), length 75: 10.183.176.1.5678 > 10.133.243.6.48646: Flags [P.], seq 51:60, ack 41, win 506, options [nop,nop,TS val 2737263309 ecr 2863763961], length 9
15:45:58.678773 0c:42:a1:41:a0:de > 0c:29:ef:c2:b5:21, ethertype IPv4 (0x0800), length 75: 10.183.176.1.5678 > 10.133.243.6.48646: Flags [P.], seq 51:60, ack 41, win 506, options [nop,nop,TS val 2737263749 ecr 2863763961], length 9
15:45:59.510760 0c:42:a1:41:a0:de > 0c:29:ef:c2:b5:21, ethertype IPv4 (0x0800), length 75: 10.183.176.1.5678 > 10.133.243.6.48646: Flags [P.], seq 51:60, ack 41, win 506, options [nop,nop,TS val 2737264581 ecr 2863763961], length 9
15:46:01.174760 0c:42:a1:41:a0:de > 0c:29:ef:c2:b5:21, ethertype IPv4 (0x0800), length 75: 10.183.176.1.5678 > 10.133.243.6.48646: Flags [P.], seq 51:60, ack 41, win 506, options [nop,nop,TS val 2737266245 ecr 2863763961], length 9
15:46:04.502773 0c:42:a1:41:a0:de > 0c:29:ef:c2:b5:21, ethertype IPv4 (0x0800), length 75: 10.183.176.1.5678 > 10.133.243.6.48646: Flags [P.], seq 51:60, ack 41, win 506, options [nop,nop,TS val 2737269573 ecr 2863763961], length 9
`

**Workaround** : If we disable **bpf-masquerade** and use iptables this issue does not appear. 

### Cilium Version

Client: 1.10.9 0338ca7 2022-03-26T01:51:32+01:00 go version go1.16.15 linux/amd64
Daemon: 1.10.9 0338ca7 2022-03-26T01:51:32+01:00 go version go1.16.15 linux/amd64

### Kernel Version

```
root@test-deployment-76cdbc6456-bj4pw:/# uname -a
Linux test-deployment-76cdbc6456-bj4pw 5.10.52-talos #1 SMP Mon Aug 9 15:24:47 UTC 2021 x86_64 GNU/Linux
root@test-deployment-76cdbc6456-bj4pw:/#

```

### Kubernetes Version

1.21.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
This issue needs a sysdump and explanation of the packet path and what actors are involved (what is the client? is it a pod? what is its IP addr, etc).
