### ISSUE TITLE
vtep: Proper policy routing  for VTEP CIDR route with pod egress L7 policy 

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#19708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

while investigating pod egress L7 policy support for VTEP and in  https://github.com/cilium/cilium/pull/19473#issuecomment-1117645877 to setup VTEP specific route table by cilium agent, probably when packet directed to  L7 policy enforcement,  the packet is dropped  in kernel here `net/ipv4/ip_forward.c`

```
int ip_forward(struct sk_buff *skb)
{
        u32 mtu;
        struct iphdr *iph;      /* Our header */
        struct rtable *rt;      /* Route we use */
        struct ip_options *opt  = &(IPCB(skb)->opt);
        struct net *net;

        /* that should never happen */
        if (skb->pkt_type != PACKET_HOST)
                goto drop;

        if (unlikely(skb->sk)) {
                netdev_info(skb->dev, "ip_forward: skb->sk\n");
                goto drop; <=====PACKET DROP HERE
        }
```

pwru output:

```
0xffff9ee307901ae0       [<empty>]      fib_validate_source     792867990914 10.0.1.240:45782->10.1.1.6:8080(tcp)
0xffff9ee307901ae0       [<empty>]    __fib_validate_source     792867993810 10.0.1.240:45782->10.1.1.6:8080(tcp)
0xffff9ee307901ae0       [<empty>]               ip_forward     792868001294 10.0.1.240:45782->10.1.1.6:8080(tcp)
0xffff9ee307901ae0       [<empty>]                kfree_skb     792868004710 10.0.1.240:45782->10.1.1.6:8080(tcp)
```

the route table and ip rule looks like:

#ip rule list

```
1:	from all to 10.1.34.0/24 lookup 202
1:	from all to 10.1.1.0/24 lookup 202
9:	from all fwmark 0x200/0xf00 lookup 2004
10:	from all fwmark 0xa00/0xf00 lookup 2005
100:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default

```
#ip r s table 202

```
10.1.1.0/24 dev cilium_host 
10.1.34.0/24 dev cilium_host 

```
this issue does not happen to setup VTEP specific route in `main` route table and no `ip rule` policy routing

### Cilium Version

cilium-cli: v0.10.0 compiled with go1.17.4 on linux/amd64
cilium image (default): v1.11.0
cilium image (stable): v1.11.4
cilium image (running): netdev

### Kernel Version

Linux centos-dev.localdomain 5.17.0-rc6+ #80 SMP PREEMPT Wed May 4 23:41:24 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20220505-120839.zip](https://github.com/cilium/cilium/files/8632859/cilium-sysdump-20220505-120839.zip)

### Relevant log output

added log in ip_forward to confirm the packet drop 

```

        if (unlikely(skb->sk)) {
                netdev_info(skb->dev, "ip_forward: skb->sk\n");
                goto drop; <=====PACKET DROP HERE
        }
```
from pod, send curl request

```
kubectl exec -it client2-5998d566b4-bnfm6 -n cilium-test -- curl -v http://10.1.1.6:8080/
*   Trying 10.1.1.6:8080...
```
kernel log:

```
May  5 11:05:14 centos-dev kernel: lxc90ee684cdbb5: ip_forward: skb->sk
May  5 11:05:15 centos-dev kernel: lxc90ee684cdbb5: ip_forward: skb->sk
May  5 11:05:17 centos-dev kernel: lxc90ee684cdbb5: ip_forward: skb->sk
May  5 11:05:21 centos-dev kernel: lxc90ee684cdbb5: ip_forward: skb->sk
May  5 11:05:29 centos-dev kernel: lxc90ee684cdbb5: ip_forward: skb->sk
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment]
found the kernel commit, I wonder if I setup the policy routing wrong?

```
commit 2ab957492d13bb819400ac29ae55911d50a82a13
Author: Sebastian PÃ¶hn <sebastian.poehn@gmail.com>
Date:   Mon Apr 20 09:19:20 2015 +0200

    ip_forward: Drop frames with attached skb->sk

    Initial discussion was:
    [FYI] xfrm: Don't lookup sk_policy for timewait sockets

    Forwarded frames should not have a socket attached. Especially
    tw sockets will lead to panics later-on in the stack.

    This was observed with TPROXY assigning a tw socket and broken
    policy routing (misconfigured). As a result frame enters
    forwarding path instead of input. We cannot solve this in
    TPROXY as it cannot know that policy routing is broken.

    v2:
    Remove useless comment

    Signed-off-by: Sebastian Poehn <sebastian.poehn@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

diff --git a/net/ipv4/ip_forward.c b/net/ipv4/ip_forward.c
index 939992c456f3..3674484946a5 100644
--- a/net/ipv4/ip_forward.c
+++ b/net/ipv4/ip_forward.c
@@ -82,6 +82,9 @@ int ip_forward(struct sk_buff *skb)
        if (skb->pkt_type != PACKET_HOST)
                goto drop;

+       if (unlikely(skb->sk))
+               goto drop;
+

```

**Comment by vincentmli** [comment]
@joestringer this seems be your area of expertise :), could you take a look when you have time. did I set up the policy routing wrong or the policy routing rule conflicting with existing policy fwmark  or hit a potential kernel bug

**Comment by vincentmli** [comment]
I think it is something to do with the policy rule I setup, not kernel issue

I setup the rule like below:

```
9:	from all fwmark 0x200/0xf00 lookup 2004
10:	from all fwmark 0xa00/0xf00 lookup 2005
100:	from all lookup local
32763:	from all to 10.1.34.0/24 lookup 2006
32763:	from all to 10.1.1.0/24 lookup 2006
32766:	from all lookup main
32767:	from all lookup default
```

ip r s table 2006

```
10.1.1.0/24 dev cilium_host scope link 
10.1.34.0/24 dev cilium_host scope link 
```

now the SYN packet can be encaped and send to VTEP device, but  it has incorrect checksum and is dropped by VTEP device probably due to bad checksum, wonder what caused the bad checksum.

 tcpdump -nn -vv -i cilium_vxlan port 8080

```
21:38:12.762861 IP (tos 0x0, ttl 64, id 40106, offset 0, flags [DF], proto TCP (6), length 60)
    
10.0.1.171.54434 > 10.1.1.6.8080: Flags [S], cksum 0x16e0 (incorrect -> 0xe0e9), seq 4156431077, win 64240, options [mss 1460,sackOK,TS val 3265563640 ecr 0,nop,wscale 7], length 0

```

**Comment by vincentmli** [comment]
after further testing, it appears incorrect cksum should not affect connectivity, I have a few kernel version tested 

grubby --info ALL | grep '^kernel'

```
kernel="/boot/vmlinuz-5.18.0-rc3+"
kernel="/boot/vmlinuz-5.17.0-rc6+". <=== this appears giving me problem
kernel="/boot/vmlinuz-5.17.0"
kernel="/boot/vmlinuz-5.15.0+"
```
I will do more testing, at least now I know I should setup the policy routing properly, which based on my test, is to set the policy routing priority after priority `100`, the local route table, so now I have 

 ip rule list
```
9:	from all fwmark 0x200/0xf00 lookup 2004
10:	from all fwmark 0xa00/0xf00 lookup 2005
100:	from all lookup local
112:	from all to 10.1.34.0/24 lookup 202
112:	from all to 10.1.1.0/24 lookup 202
32766:	from all lookup main
32767:	from all lookup default
```
ip r s table 202
```
10.1.1.0/24 dev cilium_host scope link 
10.1.34.0/24 dev cilium_host scope link 
```
and the VTEP route is simple enough to manage at runtime in case users decide to change VTEP CIDR

cilium config set vtep-cidr "10.1.32.0/24 10.1.1.0/24"

```
✨ Patching ConfigMap cilium-config with vtep-cidr=10.1.32.0/24 10.1.1.0/24...
♻️  Restarted Cilium pods

```
and result in correct VTEP CIDR route update

ip rule list
```
9:	from all fwmark 0x200/0xf00 lookup 2004
10:	from all fwmark 0xa00/0xf00 lookup 2005
100:	from all lookup local
112:	from all to 10.1.1.0/24 lookup 202
112:	from all to 10.1.32.0/24 lookup 202
32766:	from all lookup main
32767:	from all lookup default
```
ip r s table 202
```
10.1.1.0/24 dev cilium_host scope link 
10.1.32.0/24 dev cilium_host scope link 
```

**Comment by vincentmli** [comment]
did more testing with kernel `5.4`, `5.10`, `5.17`, `5.18`, no problem, having issue with kernel `5.17.0-rc6+`, maybe a bad build since I made some changes while debugging,  the current VTEP policy routing setup works well.

**Comment by devoncrouse** [comment]
Same issue here - in case it helps, we found setting the following in the netns where the drop occurs avoids it:
```bash
sysctl -w net.ipv4.ip_early_demux=0
```
