### ISSUE TITLE
VLANBPFBypass: the data filed in ConfigMap not able to take array of int

### ISSUE THREAD

**Issue by shen-cloud** [cilium/cilium#19709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the `data` filed in ConfigMap is `map[string]string`. Passing `VLANBPFBypass` values as an array of integers is not possible in ConfigMap. A validation error will happen. `got "array", expected "string"`

### Cilium Version

1.11.1 9ce9549ce6 2022-02-10T18:14:35-08:00 go version go1.17.6 linux/amd64

### Kernel Version

5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.200", GitCommit:"87bd5277f85536686030dd1fd7d6e39776dd44d1", GitTreeState:"clean", BuildDate:"2022-03-17T20:36:33Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @shen-cloud , can you provide exact examples of CLI flags that you used and/or the content of this field in the ConfigMap?

Do you observe this when configuring the option as documented in https://docs.cilium.io/en/stable/configuration/vlan-802.1q/#vlan-802-1q ?

cc @kvaster

**Comment by kvaster** [comment]
ConfigMap can't accept array. This setting should be a string of numbers separated by comma.
