### ISSUE TITLE
Move from vndr to golang dep

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1972]
## List of sub tasks

- [X] Transform cilium into a dep project
- [x] Update etcd to 3.2.9
- [ ] Update cni to 0.6.0
- [ ] Write steps on how to add a new dependency using dep on the project

**Comment by sdboyer** [comment]
if y'all need any help or guidance on this, i'm happy to provide it 😄

**Comment by aanm** [comment]
@sdboyer Thanks! We are just waiting for the release of golang 1.10 which will contain `dep` and we will start moving from `vndr`. Is `dep` already built in `go1.10rc1`?

**Comment by sdboyer** [comment]
sorry for slow response, but you can see why now, I think - vgo has been brewing. 

it's still going to be worth moving to dep in the interim - it'll likely provide the smoothest path into vgo, due to greater model similarities.
