### ISSUE TITLE
Connectivity to kubernetes service endpoints broken after k8s version upgrade

### ISSUE THREAD

**Issue by rastislavs** [cilium/cilium#19761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In an environment with 3 control-plane (master) nodes and 3 worker nodes, the communication from pods running on the master nodes to the kubernetes service endpoints is broken after upgrading k8s version from 1.23.5 to 1.23.6 (or from 1.22.2 to 1.22.3). The connectivity still works from the worker (non-master) nodes. The issue can be recovered by restarting the cilium pods running on the master nodes. 

Nodes setup:
```
$ kubectl get nodes -o wide
NAME                                           STATUS   ROLES                  AGE   VERSION   INTERNAL-IP      EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ip-172-31-141-179.eu-west-3.compute.internal   Ready    control-plane,master   91m   v1.23.6   172.31.141.179   <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-141-32.eu-west-3.compute.internal    Ready    <none>                 84m   v1.23.5   172.31.141.32    <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-142-157.eu-west-3.compute.internal   Ready    control-plane,master   90m   v1.23.6   172.31.142.157   <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-142-232.eu-west-3.compute.internal   Ready    <none>                 84m   v1.23.5   172.31.142.232   <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-143-187.eu-west-3.compute.internal   Ready    control-plane,master   89m   v1.23.6   172.31.143.187   <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-143-91.eu-west-3.compute.internal    Ready    <none>                 84m   v1.23.5   172.31.143.91    <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
```

kubernetes service endpoints:
```
$ kubectl get endpoints kubernetes                                                                                                                                                                                  
NAME         ENDPOINTS                                                     AGE
kubernetes   172.31.141.179:6443,172.31.142.157:6443,172.31.143.187:6443   101m
```

apiservers are running in the host namespace of the master nodes:
```
NAMESPACE     NAME                                                                   READY   STATUS             RESTARTS         AGE
kube-system   kube-apiserver-ip-172-31-141-179.eu-west-3.compute.internal            1/1     Running            0                93m    172.31.141.179   ip-172-31-141-179.eu-west-3.compute.internal   <none>           <none>
kube-system   kube-apiserver-ip-172-31-142-157.eu-west-3.compute.internal            1/1     Running            0                88m    172.31.142.157   ip-172-31-142-157.eu-west-3.compute.internal   <none>           <none>
kube-system   kube-apiserver-ip-172-31-143-187.eu-west-3.compute.internal            1/1     Running            0                72m    172.31.143.187   ip-172-31-143-187.eu-west-3.compute.internal   <none>           <none>
``` 

Pods running on the master nodes cannot connect to the kubernetes service after kubernetes version upgrade.
```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   109m
```

```
curl --connect-timeout 5 --insecure https://10.96.0.1:443
curl: (28) Connection timeout after 5001 ms
```

Connecting directly to the endpoint IPs does not work either (none of them):
```
curl --connect-timeout 5 --insecure https://172.31.141.179:6443
curl: (28) Connection timeout after 5001 ms
```

Connectivity to other pods and services works fine from the same pod.

Pods running on worker nodes can connect to the kubernetes service (and its endpoints) successfully:
```
curl --connect-timeout 5 --insecure https://10.96.0.1:443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}#

curl --connect-timeout 5 --insecure https://172.31.141.179:6443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}#
```

After restart of the cilium pod on the affected master node, the issue recovers and broken pods can communicate with the kubernetes service successfully.

### Cilium Version

v1.11.1

### Kernel Version

Linux ip-172-31-141-179 5.13.0-1022-aws #24~20.04.1-Ubuntu SMP Thu Apr 7 22:10:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.23.6

### Sysdump

[cilium-sysdump-20220510-154929.zip](https://github.com/cilium/cilium/files/8662162/cilium-sysdump-20220510-154929.zip)

### Anything else?

`cilium monitor --type drop` does not show anything on affected node.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rastislavs** [comment]
Reproduced with CIlium v1.11.5 as well, sysdump: [cilium-sysdump-20220524-112958.zip](https://github.com/cilium/cilium/files/8761369/cilium-sysdump-20220524-112958.zip)

**Comment by aanm** [comment]
>Pods running on the master nodes cannot connect to the kubernetes service after kubernetes version upgrade.

Which pods in particular?

**Comment by aanm** [comment]
@rastislavs can you get the a cilium monitor output without the `--type drop`?

**Comment by rastislavs** [comment]
Sure, here it is:
- the pod struggling to reach the apiserver is:
```
kube-system   machine-controller-6bff68bdc5-nr78w   0/1     Running     2 (15s ago)    76s    10.244.0.190     ip-172-31-119-89.eu-west-3.compute.internal    <none>           <none>
```
- full cilium monitor from the node where it runs: [monitor-172-31-119-89.txt](https://github.com/cilium/cilium/files/8770807/monitor-172-31-119-89.txt)
 - some related logs from that file:
```
>> Endpoint regenerated: {"id":3025,"labels":["k8s:app=machine-controller","k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system","k8s:io.kubernetes.pod.namespace=kube-system","k8s:io.cilium.k8s.policy.serviceaccount=machine-controller","k8s:io.cilium.k8s.policy.cluster=default"]}

-> stack flow 0x2c962165 , identity 24282->kube-apiserver state new ifindex 0 orig-ip 0.0.0.0: 10.244.0.190:42286 -> 172.31.118.223:6443 tcp SYN
```
- full cilium monitor log from the destination node (`172.31.118.223`) captured at the same time: [monitor-172-31-118-223.txt](https://github.com/cilium/cilium/files/8770840/monitor-172-31-118-223.txt)
- full sysdump of this cluster: [cilium-sysdump-20220525-115553.zip](https://github.com/cilium/cilium/files/8770844/cilium-sysdump-20220525-115553.zip)

**Comment by rastislavs** [comment]
@aanm do you have any ideas based on my previous comment?
This issue affects control plane upgrades of all clusters using Cilium CNI on [KubeOne](https://github.com/kubermatic/kubeone) so if you need to reproduce it yourself, it should be fairly easy.

**Comment by rastislavs** [comment]
OK, so it seems that the issue was caused by `rp_filter` settings. The upgrade triggered resetting of `net.ipv4.conf.all.rp_filter` to default (`2`) on the control plane nodes. It seems that it broke Cilium datapath until they restart. Since the cilium pods set it back to `0` when they start, restart of the cilium pods after the upgrade resolves the issue. 

Our workaround for that would be something like:
```
echo 'net.ipv4.conf.all.rp_filter = 0' > /etc/sysctl.d/99-override_cilium_rp_filter.conf
```

Note that the workaround for newer systemd versions mentioned in https://docs.cilium.io/en/stable/operations/system_requirements/#admin-system-reqs (overriding `net.ipv4.conf.lxc*.rp_filter = 0`) would not be sufficient in this case.

IMHO it would be nice to make `rp_filter` requirement more explicit in the documentation as it can break datapath in a way that is not easy to debug.

**Comment by aanm** [comment]
This will be fixed by https://github.com/cilium/cilium/pull/20072

**Comment by tafkam** [comment]
@aanm we had the same issue, and already set "net.ipv4.conf.lxc*.rp_filter = 0" like you do in your PR. This is not sufficient for this issue. Using "net.ipv4.conf.all.rp_filter = 0" fixed this.

**Comment by brb** [comment]
@rastislavs @tafkam Did you identify which dev's rp_filter=2 was causing the issue?

**Comment by tafkam** [comment]
physical network devices had rp_filter = 1, all other devices had rp_filter = 0, and additionally net.ipv4.conf.all.rp_filter = 1 was set when all pods lost network connectivity on that node

**Comment by rastislavs** [comment]
Just assuming from the fact that apart from `lxc*` and `cilium_*` netdevs we only have 3 more on the nodes:
 - `lo`
 - `ens5`
 - `nodelocaldns`

and neither `nodelocaldns` nor `lo` are used to actually forward any traffic, it is probably `rp_filter=2` on the `ens5` which is causing the issue?

**Comment by brb** [comment]
@rastislavs Do you know which exact packet is getting dropped? You could run [pwru](https://github.com/cilium/pwru) `pwru --filter-func=".*kfree_skb.*" --output-tuple --per-cpu-buffer=10000 --filter-proto=tcp --output-stack`.

**Comment by rastislavs** [comment]
So I did some more debugs:

Initial state, everything is working:
```
$ sudo sysctl -a | grep rp_filter
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.cilium_host.arp_filter = 0
net.ipv4.conf.cilium_host.rp_filter = 0
net.ipv4.conf.cilium_net.arp_filter = 0
net.ipv4.conf.cilium_net.rp_filter = 0
net.ipv4.conf.cilium_vxlan.arp_filter = 0
net.ipv4.conf.cilium_vxlan.rp_filter = 0
net.ipv4.conf.default.arp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.eth0.arp_filter = 0
net.ipv4.conf.eth0.rp_filter = 0
net.ipv4.conf.kube-ipvs0.arp_filter = 0
net.ipv4.conf.kube-ipvs0.rp_filter = 0
net.ipv4.conf.lo.arp_filter = 0
net.ipv4.conf.lo.rp_filter = 0
net.ipv4.conf.lxc94a9b8960b75.arp_filter = 0
net.ipv4.conf.lxc94a9b8960b75.rp_filter = 0
net.ipv4.conf.lxc_health.arp_filter = 0
net.ipv4.conf.lxc_health.rp_filter = 0
net.ipv4.conf.nodelocaldns.arp_filter = 0
net.ipv4.conf.nodelocaldns.rp_filter = 0
```

Now we break the pod -> apiserver connectivity on the node where the pod is running:
```
sysctl -w net.ipv4.conf.all.rp_filter=2
```

So we now have the following rp_filter settings:
```
$ sudo sysctl -a | grep rp_filter
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.cilium_host.arp_filter = 0
net.ipv4.conf.cilium_host.rp_filter = 0
net.ipv4.conf.cilium_net.arp_filter = 0
net.ipv4.conf.cilium_net.rp_filter = 0
net.ipv4.conf.cilium_vxlan.arp_filter = 0
net.ipv4.conf.cilium_vxlan.rp_filter = 0
net.ipv4.conf.default.arp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.eth0.arp_filter = 0
net.ipv4.conf.eth0.rp_filter = 0
net.ipv4.conf.kube-ipvs0.arp_filter = 0
net.ipv4.conf.kube-ipvs0.rp_filter = 0
net.ipv4.conf.lo.arp_filter = 0
net.ipv4.conf.lo.rp_filter = 0
net.ipv4.conf.lxc_health.arp_filter = 0
net.ipv4.conf.lxc_health.rp_filter = 0
net.ipv4.conf.lxcbeaab24adf0b.arp_filter = 0
net.ipv4.conf.lxcbeaab24adf0b.rp_filter = 0
net.ipv4.conf.lxced39fa47491b.arp_filter = 0
net.ipv4.conf.lxced39fa47491b.rp_filter = 0
net.ipv4.conf.lxcfcd5ee7bd2c6.arp_filter = 0
net.ipv4.conf.lxcfcd5ee7bd2c6.rp_filter = 0
net.ipv4.conf.nodelocaldns.arp_filter = 0
net.ipv4.conf.nodelocaldns.rp_filter = 0
```

Pod IP is `10.244.3.168`, apiserver is running at `172.31.167.195:6443` (IP address of one of the master nodes).

What I can see after `sysctl -w net.ipv4.conf.all.log_martians=1` in `/var/log/messages` is:
```
Jun  8 13:13:51 ip-172-31-167-236 kernel: IPv4: martian source 172.31.167.195 from 10.244.3.168, on dev lxcfcd5ee7bd2c6
Jun  8 13:13:51 ip-172-31-167-236 kernel: ll header: 00000000: 62 dd f3 d8 95 eb ae e1 52 cb 80 59 08 00        b.......R..Y..
Jun  8 13:13:52 ip-172-31-167-236 kernel: IPv4: martian source 172.31.167.195 from 10.244.3.168, on dev lxcfcd5ee7bd2c6
Jun  8 13:13:52 ip-172-31-167-236 kernel: ll header: 00000000: 62 dd f3 d8 95 eb ae e1 52 cb 80 59 08 00        b.......R..Y..
```

After setting `sysctl -w net.ipv4.conf.all.rp_filter=0` everything starts working normally.

Here are pwru outputs for non-working and working case with the filters on the pod IP (separate connection request made for each pwru run):
[pwru-filter-non-working.txt](https://github.com/cilium/cilium/files/8862021/pwru-filter-non-working.txt)
[pwru-filter-working.txt](https://github.com/cilium/cilium/files/8862024/pwru-filter-working.txt)

And a complete sysdump:  [cilium-sysdump-20220608-151704.zip](https://github.com/cilium/cilium/files/8862030/cilium-sysdump-20220608-151704.zip)

**Comment by rastislavs** [comment]
I think this explains it:
From https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt:
```
	The max value from conf/{all,interface}/rp_filter is used
	when doing source validation on the {interface}.
```
So even when `net.ipv4.conf.lxcfcd5ee7bd2c6.rp_filter` is `0`, if `net.ipv4.conf.all.rp_filter` equals `2`, the loose mode (`2`) is in effect on `lxcfcd5ee7bd2c6`.
