### ISSUE TITLE
Expose policy add/update/delete events via Hubble

### ISSUE THREAD

**Issue by ungureanuvladvictor** [cilium/cilium#19772]
In our environment we have a high chrun of Spark jobs that run and each job has its own set of cilium policies. It's common for us to run ~2k jobs at the same time and each job has a minimum of 3 CNPs. We are running with `--disable-cnp-status-updates` to not crash the apiserver when the cluster is at peak workload. By doing this we lost visibility to when a policy is applied and enforced.

I'd be interested to get policy events in the hubble output. We're collecting hubble export data and ingesting it into a separate system where we can do just in time investigations.

@michi-covalent

**Comment by michi-covalent** [comment]
adding to @rolinh's comment above, there is `--hubble-export-file-path` flag in `>=v1.10`. with this option you can write unfiltered hubble events (including all the agent events) to a rotated file: https://docs.cilium.io/en/v1.10/cmdref/cilium-agent/#options

**Comment by michi-covalent** [comment]
synced up with @ungureanuvladvictor offline, `--hubble-export-file-path` should work for his use case. let's close this issue for now, we can re-open it if `--hubble-export-file-path` doesn't work ✅
