### ISSUE TITLE
k8s_watcher.go:273: watch of *k8s.CiliumNetworkPolicy ended with: too old resource version

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1977]
This roughly happens every 300 seconds. It doesn't affect the watcher.

So far it's happening with k8s 1.8

**Comment by tgraf** [comment]
Any idea what the underlying etcd event is that trigger this?

**Comment by aanm** [comment]
@tgraf it's not our code, it's from the kubernetes watcher

It's difficult to replicate because I've the exact same code for cilium CRD and a dummy CRD. On the dummy CRD this never happens. I'm still debugging this.

**Comment by thoslin** [comment]
I'm also seeing this error in my installation which is running k8s 1.7.2
```
time="2017-11-17T01:34:33Z" level=warning msg="unable to update CNP, retrying..." ciliumNetworkPolicyName=secure-empire-kafka error="Operation cannot be fulfilled on ciliumnetworkpolicies.cilium.io \"secure-empire-kafka\": the object has been modified; please apply your changes to the latest version and try again" k8sNamespace=default subsys=k8s
```

**Comment by aanm** [comment]
This can't be fixed. The error message is being written directly into os.stderr by the k8s dependency

```
os.Stderr.Write([]byte("ERROR: logging before flag.Parse: "))
os.Stderr.Write(data)
```
