### ISSUE TITLE
CI: Conformance AWS-CNI: computed checksum did NOT match

### ISSUE THREAD

**Issue by sahid** [cilium/cilium#19771]
Looks like sha256 verification failed. It's a WARNING but no more command was executed after that so I imagine we were waiting for a status code `0`.

- https://github.com/cilium/cilium/runs/6377377857?check_suite_focus=true

```
Run curl -sSL --remote-name-all [https://github.com/cilium/cilium-cli/releases/download/v0.11.4/cilium-linux-amd64.tar.gz{,.sha256sum}](https://github.com/cilium/cilium-cli/releases/download/v0.11.4/cilium-linux-amd64.tar.gz%7B,.sha256sum%7D)
  curl -sSL --remote-name-all [https://github.com/cilium/cilium-cli/releases/download/v0.11.4/cilium-linux-amd64.tar.gz{,.sha256sum}](https://github.com/cilium/cilium-cli/releases/download/v0.11.4/cilium-linux-amd64.tar.gz%7B,.sha256sum%7D)
  sha256sum --check cilium-linux-amd64.tar.gz.sha256sum
  sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
  rm cilium-linux-amd64.tar.gz{,.sha256sum}
  cilium version
  shell: /usr/bin/bash -e {0}
  env:
    clusterName: cilium-cilium-2303174449
    region: us-east-2
    cilium_cli_version: v0.11.4
    check_url: https://github.com/cilium/cilium/actions/runs/2303174449
    eksctl_version: v0.94.0
    kubectl_version: v1.23.6
sha256sum: WARNING: 1 computed checksum did NOT match
cilium-linux-amd64.tar.gz: FAILED
Error: Process completed with exit code 1.
```

- The PR related: https://github.com/cilium/cilium/pull/19712

**Comment by joestringer** [comment]
It seems like this may have just been an unlucky build where the download was corrupted somehow, as there are other similar jobs that have succeeded on the same step for the same CLI version. Maybe it's enough to just restart the job in this case?

ref. https://github.com/cilium/cilium/runs/6427605331?check_suite_focus=true from https://github.com/cilium/cilium/actions/workflows/conformance-aws-cni.yaml?query=is%3Asuccess .

**Comment by sahid** [comment]
Sure, or perhaps we could add some sort of retry process, don't you think?

**Comment by joestringer** [comment]
Does this happen regularly? Feel free to submit a change to the workflows to add retries if you think that this is something we need to regularly mitigate.

**Comment by sahid** [comment]
Yes, I was asking myself the same question and I have finally considered that this have made lost engineering time for at least two persons so perhaps having this retry would have made sense to avoid this happen again
