### ISSUE TITLE
Untangle complexity around TUNNEL_MODE macro

### ISSUE THREAD

**Issue by jibi** [cilium/cilium#19786]
There's some hidden complexity in the way `bpf/init.sh` handles the `TUNNEL_MODE` parameter, as contrary to what it would be reasonable to expect, it will not pass always pass that value to the datapath.

This ticket is about untangling some of that complexity to make it easier to follow which values are going to be set in the datapath for that macro.

**Comment by julianwiedmann** [comment]
I believe 0aa9e946c856d0ca6d8754d40acc9cc896c483bf and 84a5a2403dca0c6308eac4f5bc0fdbbc507e677f cleaned this up sufficiently :tada: .
