### ISSUE TITLE
Crashloop for Cilium v1.12-rc2 and Centos 8

### ISSUE THREAD

**Issue by rjes** [cilium/cilium#19808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi!
I'm trying to use v1.12-rc2 with CentOS 8 (in the steps below, ks is an alias for `kubectl -n kube-system `)
I had 1.11.4 before and upgraded to this version with
``` 
$ helm upgrade cilium cilium/cilium -n kube-system --version 1.12.0-rc2 --reset-values
```
I used --reset-values to make sure my old values wasn't causing the trouble (played around with bgp in 1.11.4)

The operator deployment is stable.
```
$ ks get pods
NAME                              READY   STATUS              RESTARTS   AGE
cilium-operator-5868c8cbd-5pntg   1/1     Running             0          70s
cilium-operator-5868c8cbd-8t4zp   1/1     Running             0          70s
```
And the logs from the operator tells me everything seems fine:
```
$ ks logs deploy/cilium-operator | grep -v 'level=info' | wc -l
Found 2 pods, using pod/cilium-operator-5868c8cbd-5pntg
0
```
The cilium daemonSet is crashlooping:
```
$ ks get pods -l k8s-app=cilium
NAME           READY   STATUS             RESTARTS   AGE
cilium-r8w7z   0/1     CrashLoopBackOff   9          22m
cilium-rzxx8   0/1     CrashLoopBackOff   9          22m

$ ks logs -p cilium-r8w7z | grep -v level=info
level=fatal msg="Cannot initialise BPF perf ring buffer sockets" error="failed to create perf ring for CPU 0: can't mmap: operation not permitted" startTime="2022-05-12 21:57:54.463823399 +0000 UTC m=+3.211794063" subsys=monitor-agent
```
I'm running kubernetes 1.21.11 on CentOS steam 8

```
$ k get nodes -o wide
NAME                          STATUS   ROLES    AGE     VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION          CONTAINER-RUNTIME
k8s01-worker01.k8s01.k8s.se   Ready    <none>   7d23h   v1.21.11   172.31.5.161   <none>        CentOS Stream 8   4.18.0-383.el8.x86_64   containerd://1.4.4
k8s01-worker02.k8s01.k8s.se   Ready    <none>   7d23h   v1.21.11   172.31.5.162   <none>        CentOS Stream 8   4.18.0-383.el8.x86_64   containerd://1.4.4
```
And the running image is:
```
$ ks describe pod cilium-operator-5868c8cbd-5pntg | grep 'Image: ' 
    Image:         quay.io/cilium/operator-generic:v1.12.0-rc2
$ ks describe pod cilium-r8w7z | grep 'Image: '  | uniq
    Image:         quay.io/cilium/cilium:v1.12.0-rc2
```

### Cilium Version

v1.12.0-rc2

### Kernel Version

4.18.0-383.el8.x86_64

### Kubernetes Version

1.21.11

### Sysdump

[cilium-sysdump-20220513-001017.zip](https://github.com/cilium/cilium/files/8682842/cilium-sysdump-20220513-001017.zip)

### Relevant log output

```shell
level=fatal msg="Cannot initialise BPF perf ring buffer sockets" error="failed to create perf ring for CPU 0: can't mmap: operation not permitted" startTime="2022-05-12 22:08:15.518205973 +0000 UTC m=+3.270311059" subsys=monitor-agent
```

### Anything else?

I'm having the controlplane for kubernetes in another cluster namespace.
This is a test/lab cluster so there is no problem to tear it down, use a elrepo kernel and things like that.
The worker nodes are VM's on oVirt (kvm), but I don't think I have set any special options since cilium works with previous versions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rjes** [comment]
I increased memory of the nodes from 2GB to 4GB and still same fatal line

**Comment by rjes** [comment]
Using the kernel-ml from elrepo fixes the issue and the pods are stable.
Current kernel is 5.17.7-1.el8.elrepo.x86_64

**Comment by sayboras** [comment]
:wave: can you try with one more flag securityContext.privileged=true as per below ?


```
helm upgrade cilium cilium/cilium -n kube-system --version 1.12.0-rc2 --set securityContext.privileged=true --reset-values
```

**Comment by sayboras** [comment]
Appreciate if you can just update daemonset as mentioned in PR https://github.com/cilium/cilium/pull/19812, and let me know if it's working.

**Comment by joestringer** [comment]
I was also observing this on Ubuntu 20.04.4 LTS (focal) under kind, kernel `5.14.0-1034-oem`. Weirdly it only affected the kind control-plane node, but not the other node. After applying #19812 to the DaemonSet, Cilium no longer went into CrashLoopBackoff. Thanks @sayboras !
