### ISSUE TITLE
Improve documentation of toServices policy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1981]
- [ ] Add comments on relationship between `k8sServiceSelector` and `k8sService`. Mutually exclusive?
- [ ] What is the behavior if both fields are omitted?

```golang
// Service wraps around selectors for services
type Service struct {
        // K8sServiceSelector selects services by k8s labels. Not supported yet
        K8sServiceSelector ServiceSelector `json:"k8sServiceSelector,omitempty"`
        // K8sService selects service by name and namespace pair
        K8sService K8sServiceNamespace `json:"k8sService,omitempty"`
}
```

**Comment by nebril** [comment]
k8sServiceSelector is not yet in the docs since it's not implemented yet. I think adding it to docs before it's functional doesn't make sense.
