### ISSUE TITLE
MasterKeyProtection never works with the CRD backend

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#19827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium never recreates master keys that are still in local use. It calls [crdBackend.UpdateKey](https://github.com/cilium/cilium/blob/dfa6b157e8e9484c65fd938b2b45a4f5f50c61f9/pkg/allocator/cache.go#L151) when a CiliumIdentity is removed, but UpdateKey does nothing because AcquireReference always returns nil. 
https://github.com/cilium/cilium/blob/dfa6b157e8e9484c65fd938b2b45a4f5f50c61f9/pkg/k8s/identitybackend/identity.go#L126

### Cilium Version

```
Client: 1.11.4 https://github.com/cilium/cilium/commit/9d2546357ef7302514f87b04534933c995340ec6 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64
Daemon: 1.11.4 9d25463 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64
```

### Kernel Version

```
$ uname -a
Linux rack0-cs5 5.15.32-flatcar #1 SMP Tue Apr 5 17:17:31 -00 2022 x86_64 AMD EPYC 7413 24-Core Processor AuthenticAMD GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"archive", BuildDate:"2022-03-23T08:04:34Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
cc @timoreimann @aanm I believe this is the issue we are tracking from Cilium Slack.

**Comment by ysksuzuki** [comment]
Do you think Cilium should check if the CiliumIdentity is referenced from CiliumEndpoints before recreating the master key? I think Cilium should recreate it regardless of that if the removed identity that is still referenced from the localKey is missing. Otherwise there is a risk that CiliumEndpoints use an identity that does not exist.

The callers of UpdateKey intend to recover the case in which CiliumIdentity that is still in local use is missing. 
https://github.com/cilium/cilium/blob/6f9fedd43cc369b27f5a5a4c8a0634fe7629fe01/pkg/allocator/allocator.go#L499
https://github.com/cilium/cilium/blob/314ca7baeff4f568ffc0bad95124e40665b1f88c/pkg/allocator/cache.go#L151
