### ISSUE TITLE
[Vagrant]: fatal: unsafe repository ('/home/vagrant/go/src/github.com/cilium/cilium' is owned by someone else)

### ISSUE THREAD

**Issue by elfadel** [cilium/cilium#19829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

For some git versions, using the provided Vagrantfiles to set up Cilium environment will lead to the below error:

`fatal: unsafe repository ('/home/vagrant/go/src/github.com/cilium/cilium' is owned by someone else)`

I use to fix it by adding, as recommended, the cmd `git config --global --add safe.directory /home/vagrant/go/src/github.com/cilium/cilium` in the Vagranfile.

If, you, guys, think it is an acceptable solution, let me know to make a PR.

### Cilium Version

Client: 1.11.90 dfa6b157e8 2022-05-13T13:42:00-07:00 go version go1.18.1 linux/amd64
Daemon: 1.11.90 dfa6b157e8 2022-05-13T13:42:00-07:00 go version go1.18.1 linux/amd64

### Kernel Version

Linux 5.18.0-rc1-gd54d06a4c4bc

### Kubernetes Version

v1.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
:wave: thanks for your issue.

There is development guide mentioning about .devvmrc file, which can be used to setup git config in VM. Majority of cilium developers might probably have git user details configured in this file, however, there is no harm to have additional `safe.directory` attribute as an alternative option.

https://docs.cilium.io/en/stable/contributing/development/dev_setup/
