### ISSUE TITLE
Cilium 1.10.11 is unable to enable eBPF JIT: open /proc/sys/net/core/bpf_jit_enable: no such file or directory

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#19847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium logs report:

```
level=warning msg="Failed to sysctl -w" error="could not open the sysctl file /proc/sys/net/core/bpf_jit_enable: open /proc/sys/net/core/bpf_jit_enable: no such file or directory" subsys=sysctl sysParamName=net.core.bpf_jit_enable sysParamValue=1
```

### Cilium Version

1.10.11

### Kernel Version

Ubuntu 5.14.0-1034-oem

### Kubernetes Version

v1.21.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
@aanm did any of the changes in the latest releases modify the way that sysctl is accessed?

**Comment by joamaki** [comment]
Started looking into this. At least in kind the cilium-agent container does not have host-proc volume mounted and the /proc it has is the unprivileged variant that doesn't contain e.g. bpf_jit_enable. My initial guess was that perhaps the dropping of "privileged" from the daemonset caused to have a different view of /proc, but that commit was not backported to 1.10. 

Looking at just v1.10.11 there in cilium-agent-daemonset.yaml the mounting of hostproc is conditional on cgroup.autoMount.enabled, but that's from mid 2021. The sysctl code related to setting bpf_jit_enable and other parameters also haven't changed in a long time. So at least after a quick investigation it doesn't seem like anything has changed recently regarding this, so it may be that this has been broken for a long time now.

One way to fix this would be to always mount the hostproc over /proc in the cilium-agent container, but perhaps there's a reason why this isn't done by default?

**Comment by joestringer** [comment]
Ah I see, from further out-of-band discussion with @joamaki it sounds like this should only happen when some environment (a) sets up containers for the nodes for k8s, then (b) runs Cilium in a nested container inside. In this setup, Cilium gets "hostNetwork" of the outer node container, not hostNetwork on the underlying host. Hence it's not true hostNetwork which would be necessary to expose kernel-wide flags like the bpf JIT flag.

I don't think that this is likely to crop up in real environments, since the virtualization/containerization of individual nodes is only useful for testing purposes in order to simulate larger clusters within a single host in a developer setup.

**Comment by joestringer** [comment]
Discussed that we can just enhance the error detection logic and logging here to make it less concerning in development environment.
