### ISSUE TITLE
Unable to use hostPort in cilium plugin installed by helm

### ISSUE THREAD

**Issue by MrYuanZhen** [cilium/cilium#19863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Step
* Deploy Cilium with Rancher Catalogs and add the following answers

```yaml
---
  externalIPs: 
    enabled: "true"
  hostPort: 
    enabled: "true"
  hostServices: 
    enabled: "true"
  hubble: 
    enabled: "true"
    relay: 
      enabled: "true"
    ui: 
      enabled: "true"
```
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/37647017/169034638-3c98553b-0741-4c18-b13f-4232cc1374a2.png">

* save and deploy

## Expected
* Can be deployed normally and use the service type of hostPort；

## Result
* Enter the Cilium Pod and execute the command cilium status --verbose | grep HostPort returns the Disabled status;

## Possible reason

* By viewing the logs of the Cilium Pod, I found the following information, and the functions of enable-node-port, enable-external-ips, enable-host-reachable-services, enable-host-port and enable-session-affinity were automatically turned off；
```
level=info msg="Connected to apiserver" subsys=k8s 
level=info msg="Auto-disabling \"enable-node-port\", \"enable-external-ips\", \"enable-host-reachable-services\", \"enable-host-port\", \"enable-session-affinity\" features and falling back to \"enable-host-legacy-routing\"" subsys=daemon 
level=info msg="Inheriting MTU from external network interface" device=ens32 ipAddr=11.22.232.204 mtu=1500 subsys=mtu 
level=info msg="Restored services from maps" failed=0 restored=74 subsys=service 
```

* After reviewing the code, when KubeProxyReplacement is configured as Disabled, these configurations will be automatically set to false;

```go
func initKubeProxyReplacementOptions() (bool, error) {
	if option.Config.KubeProxyReplacement != option.KubeProxyReplacementStrict &&
		option.Config.KubeProxyReplacement != option.KubeProxyReplacementPartial &&
		option.Config.KubeProxyReplacement != option.KubeProxyReplacementProbe &&
		option.Config.KubeProxyReplacement != option.KubeProxyReplacementDisabled {
		return false, fmt.Errorf("Invalid value for --%s: %s", option.KubeProxyReplacement, option.Config.KubeProxyReplacement)
	}

	if option.Config.KubeProxyReplacement == option.KubeProxyReplacementDisabled {
		log.Infof("Auto-disabling %q, %q, %q, %q, %q features and falling back to %q",
			option.EnableNodePort, option.EnableExternalIPs,
			option.EnableHostReachableServices, option.EnableHostPort,
			option.EnableSessionAffinity, option.EnableHostLegacyRouting)

		disableNodePort()
		option.Config.EnableHostReachableServices = false
		option.Config.EnableHostServicesTCP = false
		option.Config.EnableHostServicesUDP = false
		option.Config.EnableSessionAffinity = false

		return false, nil
	}
```
* But by looking at the values.yaml in the Helm Chart, it is found that it cannot be configured by passing the parameter kubeProxyReplacement because it is blocked;

```yaml
 # -- Configure the kube-proxy replacement in Cilium BPF datapath
 # Valid options are "disabled", "probe", "partial", "strict".
 # ref: https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/
 #kubeProxyReplacement: "disabled"

 # -- healthz server bind address for the kube-proxy replacement.
 # To enable set the value to '0.0.0.0:10256' for all ipv4
 # addresses and this '[::]:10256' for all ipv6 addresses.
 # By default it is disabled.
 kubeProxyReplacementHealthzBindAddr: ""
```

I'm not really sure why this parameter is masked out, but it's available in the documentation. And because this parameter cannot be passed, functions such as hostPort cannot be used;

### Cilium Version

* quay.io/cilium/cilium:v1.11.2
* quay.io/cilium/operator-generic:v1.11.2

### Kernel Version

* 4.19.94-300.el7.x86_64

### Kubernetes Version

* kubernetes v1.20.15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshwinAmbal** [comment]
This issue still exists in Cilium version v1.14.5 when installing with helm. I've tested the portMap plugin and HostPort still says Disabled in the cilium pod. 

I will work with the kubeproxy replacement to see if that works for me.
