### ISSUE TITLE
Broken link on https://docs.cilium.io/en/v1.11/gettingstarted/clustermesh docs

### ISSUE THREAD

**Issue by girikuncoro** [cilium/cilium#19878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I was following the cluster mesh tutorial in https://docs.cilium.io/en/v1.9/gettingstarted/clustermesh/ but it's no longer the newest page. Following the link below took me to the broken link
<img width="750" alt="image" src="https://user-images.githubusercontent.com/3192347/169231062-7a5643a6-438c-4f01-94e2-5e7d428fb41a.png">

### Cilium Version

N/A

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jibi** [comment]
Hey @girikuncoro :wave: these should be the docs you are looking for: https://docs.cilium.io/en/v1.11/gettingstarted/clustermesh/clustermesh/
I think the warning you get on the v1.9 docs is just automatically generated and assumes the new docs are under the same path (which is not the case here)

**Comment by joestringer** [comment]
Thanks for the report, I've created a redirect for this broken link.
