### ISSUE TITLE
NoExecute taint causes mass pod eviction after GKE control plane upgrades

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#19890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After GKE upgrades the control plane, so after the 2nd time the kubelet reconnects, `system:gcp-controller-manager` will update the node object adding back the `node.cilium.io/agent-not-ready:NoExecute` taint. Usually within 100ms the cilium agent will then remove the taint. However, that is more than enough time for the `node-controller` and sometimes even the `daemon-set-controller` sometimes to notice and issue deletes for all pods on the node that don't tolerate the taint.

### Cilium Version

```
Client: 1.11.3 62aa82d 2022-03-26T01:56:48+01:00 go version go1.17.8 linux/amd64
Daemon: 1.11.3 62aa82d 2022-03-26T01:56:48+01:00 go version go1.17.8 linux/amd64
```

### Kernel Version

`5.4.0-1054-gke`

### Kubernetes Version

`Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
cc @bmcustodio

**Comment by bmcustodio** [comment]
This has been extensively documented in https://docs.cilium.io/en/v1.11/gettingstarted/taints/#taint-effects, in particular

> If NoExecute is used, pods won’t be executed (nor scheduled) on a node until Cilium has had the chance to remove the taint. One practical effect of this is that whenever the taint is added back to the node by some external process (such as during an upgrade or eventually a routine operation), pods will be evicted from the node until Cilium has had the chance to remove the taint.
