### ISSUE TITLE
Cilium Agent pods affected by performance tests

### ISSUE THREAD

**Issue by pavelmish552** [cilium/cilium#19929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

During the performance tests, we can see increased CPU usage on cilium-agent containers. This contradicts our understanding of the cilium architecture that the cilium-agent pod is not responsible for the traffic proxying and only acts as a controller around BPF instructions.
Plus we also don't have any related network policies/cilium network policies - as cilium uses Envoy for L7 network policies was a possible explanation:

> k get ciliumnetworkpolicies.cilium.io -A
No resources found

### Cilium Version

Client: 1.11.3 62aa82d 2022-03-26T01:56:48+01:00 go version go1.17.8 linux/amd64
Daemon: 1.11.3 62aa82d 2022-03-26T01:56:48+01:00 go version go1.17.8 linux/amd64

### Kernel Version

Linux lg-l-p-oms50195 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

k8s v1.21

### Anything else?

![image](https://user-images.githubusercontent.com/73887665/169983020-c3887737-d334-4596-a40b-0ad150fdcae8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krumstein** [comment]
Hi @aanm ,
the tests are jmeter based towards pods in the cluster. 
In order to simply reproduce it, I used `siege`  tool from ubuntu:
`root@my-shell:/# siege -b nginx-ingress-controller-payload-controller.labe2esi.svc.cluster.local/statusz`

then I run `top` inside cilium pod:
```top - 13:11:38 up 9 days, 23:02,  0 users,  load average: 0.79, 1.51, 0.99
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s): 11.8 us,  4.1 sy,  0.0 ni, 81.8 id,  0.0 wa,  0.0 hi,  2.3 si,  0.0 st
MiB Mem : 127346.4 total,  69689.9 free,  32913.8 used,  24742.7 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  93615.3 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0  868632 180584  64080 S  47.3   0.1 362:15.06 cilium-agent
  452 root      20   0  708880   8144   3772 S   0.0   0.0   1:18.62 cilium-health-r
18622 root      20   0    6820   6244   2984 S   0.0   0.0   0:00.02 bash
18634 root      20   0    6116   3332   2812 R   0.0   0.0   0:00.02 top
```


As you can see, cilium-agent uses around 50% of the CPU. As soon as I stop the benchmark it get back to 1-2% CPU:


```top - 13:13:38 up 9 days, 23:04,  0 users,  load average: 3.25, 2.62, 1.49
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.5 us,  0.1 sy,  0.0 ni, 99.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 127346.4 total,  69695.4 free,  32888.2 used,  24762.7 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  93636.9 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    1 root      20   0  868632 179304  64080 S   1.0   0.1 362:50.54 cilium-agent
18634 root      20   0    6116   3332   2812 R   0.3   0.0   0:00.04 top
  452 root      20   0  708880   8064   3772 S   0.0   0.0   1:18.63 cilium-health-r
18622 root      20   0    6820   6244   2984 S   0.0   0.0   0:00.02 bash```

**Comment by aanm** [comment]
@pavelmish552 can you provide a sysdump? Thank you

**Comment by aanm** [comment]
@pavelmish552 can you run with hubble disabled? `--set hubble.enabled=false`

**Comment by pavelmish552** [comment]
> @pavelmish552 can you provide a sysdump? Thank you

@aanm Just sent you a sysdump in private.

**Comment by krumstein** [comment]
@aanm do you have ideas? Thanks!
