### ISSUE TITLE
Clean up extraneous "group: unknown group cilium" log

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#19957]
The recent Cilium 1.9.15, 1.10.11, 1.11.5 releases all removed the Cilium group. Now I see this in the 1.11.5 log:

```
level=info msg="Group not found" error="group: unknown group cilium" file-path=/var/run/cilium/health.sock group=cilium subsys=api
```

We should drop this logic since the cilium group isn't enabled in the latest code.

**Comment by Revolyssup** [comment]
Hey @joestringer , Can I take this up? Should I also remove the const `CiliumGroupName` or that might be useful somewhere else in future?

**Comment by sayboras** [comment]
👋 thanks, I have assigned the issue to you.

Ideally, if the const is not used, we can just remove it, adding it back later in future will not be too troublesome as well.

**Comment by kerthcet** [comment]
Sorry @Revolyssup I have worked on this already but forget to assign to myself, but maybe you can help to review then.
/assign

**Comment by kerthcet** [comment]
What's more, I found we have scattered `groupadd -f cilium` located in the project , , should we also remove them?e.g. https://github.com/cilium/cilium/blob/5ba662563e273658086052c27028fa459d84de0e/daemon/Makefile#L24

**Comment by tklauser** [comment]
I think this was already addressed by https://github.com/cilium/cilium/pull/19927 which changed the message to debug level. In some cases (e.g. in the dev VM) users might still want to assign the socket to group `cilium` so they can use the per-node `cilium` command without `sudo`.

**Comment by kerthcet** [comment]
It seems we can close the issue then.
