### ISSUE TITLE
spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functinoal in v1.16+

### ISSUE THREAD

**Issue by alphabet5** [cilium/cilium#19990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

```
helm install cilium cilium/cilium \
  --version 1.11.5 \
  --namespace kube-system \
  --set ipam.mode=kubernetes \
  --set kubeProxyReplacement=strict \
  --set k8sServiceHost=10.111.111.13 \
  --set k8sServicePort=6443 \
  --set ipMasqAgent.enabled=true \
  --set hostServices.enabled=true \
  --set installIptablesRules=false \
  --set loadBalancer.mode=dsr \
  --set l7Proxy=false \
  --set cgroup.autoMount.enabled=false \
  --set cgroup.hostRoot=/sys/fs/cgroup \
  --set enableIPv4Masquerade=true
```

After this warnings came up about depreciated and non-functional options. 

### Cilium Version

1.11.5.

### Kernel Version

5.15.0-33-generic

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20220527-104811.zip](https://github.com/cilium/cilium/files/8787849/cilium-sysdump-20220527-104811.zip)

### Relevant log output

```shell
W0527 10:45:23.073316   13910 warnings.go:70] spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[1].matchExpressions[0].key: beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead
W0527 10:45:23.073384   13910 warnings.go:70] spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
NAME: cilium
LAST DEPLOYED: Fri May 27 10:45:17 2022
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.11.5.

For any further help, visit https://docs.cilium.io/en/v1.11/gettinghelp
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
:wave:   Thanks for your issue.

I think the above is just a generic warning, as we set priorityClassName attribute as well as per below, so basically, cilium will just work as expected.

In the master branch, this annotation is removed, but the changes are not back-ported to v1.11 branch, I just add required back-ported label for 1.11.

v1.11.5: https://github.com/cilium/cilium/blob/v1.11.5/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L442
Related PR: https://github.com/cilium/cilium/pull/18667
