### ISSUE TITLE
Feature: BPF fragmentation handling

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#200]
- [ ] Capability to do IP fragment reassembly in front of a BPF program
- [ ] Ability for a BPF program to queue skbs for reassembly
- [ ] Metadata for a BPF to know whether reassembly was performed
- [ ] Prevent an skb from being queued into reassmebly multiple times
- [ ] Don't require MTU of net_device to cover maximum reassembled packet size

**Comment by joestringer** [comment]
We've had users hitting some fragmentation issues lately, I think we should consider how to solve some of these fragmentation issues in an upcoming release.

**Comment by tgraf** [comment]
We have not seen fragmentation related issues in the past couple of months. The new MTU model seems to work great. Closing for now.
