### ISSUE TITLE
All logs are logged to systemd at level "info", regardless of error level

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2000]
```
runtime cilium $ journalctl -u cilium --priority=6 | grep debug | wc -l
21931
runtime cilium $ journalctl -u cilium --priority=7 | grep debug | wc -l
21931
runtime cilium $ journalctl -u cilium --priority=7 | grep info | wc -l
1891
runtime cilium $ journalctl -u cilium --priority=6 | grep info | wc -l
1891
runtime cilium $ journalctl -u cilium --priority=6 | grep err | wc -l
13
runtime cilium $ journalctl -u cilium --priority=5 | grep err | wc -l
0
```

According to the journalctl documentation [here](https://www.freedesktop.org/software/systemd/man/journalctl.html):

```
-p, --priority=
Filter output by message priorities or priority ranges. Takes either a single numeric or textual log level (i.e. between 0/"emerg" and 7/"debug"), or a range of numeric/text log levels in the form FROM..TO. The log levels are the usual syslog log levels as documented in syslog(3), i.e. "emerg" (0), "alert" (1), "crit" (2), "err" (3), "warning" (4), "notice" (5), "info" (6), "debug" (7). If a single log level is specified, all messages with this log level or a lower (hence more important) log level are shown. If a range is specified, all messages within the range are shown, including both the start and the end value of the range. This will add "PRIORITY=" matches for the specified priorities.
```

**Comment by joestringer** [comment]
I don't know if this is a Cilium issue or a logrus issue.

**Comment by ianvernon** [comment]
Reviving this because I'm trawling through old issues , but it looks like this is because Cilium logs to stdout / stderr directly, and not to journald / systemd themselves. See 
https://github.com/docker/for-linux/issues/127#issuecomment-337045289

We could perhaps add journald / systemd as a log driver within Cilium logging configuration and then use that in the developer VM systemd files in the repo: https://github.com/wercker/journalhook

**Comment by joestringer** [comment]
@ianvernon completely agree, that looks like the appropriate fix. If someone wants to take up this work, feel free to re-open this ticket and assign to yourself. For now, it's not a high enough priority to schedule in an upcoming release.
