### ISSUE TITLE
IP Address was released for an active pod

### ISSUE THREAD

**Issue by abebars** [cilium/cilium#20026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We ran into an issue recently, and it only occurred at the time of deployment of different components. A pod would come up without connectivity to other nodes on various occasions. However, the pod would be able to accept/connect to pods on the same node.

The pod will not be able to connect to any services on the other nodes. External Connectivity is not impacted.

### Cilium Version

1.10.6 and 1.11.4

### Kernel Version

Linux 5.4.181-99.354.amzn2.x86_64

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
The IP Address was released after the pod was created approximately 7 sec after
{
timestamp:1653592408941,
log:"level=info msg=\"Releasing excess IPs from node\" available=13 excess=1 instanceID=i-0eb6c923a2154d01e name=ip-10-250-32-87.ec2.internal releasing=\"[100.64.153.132]\" selectedInterface=eni-0749b238b26c13530 selectedPoolID=subnet-0dcac01aa41b82bdb subsys=ipam used=4",
stream:"stderr",
time:"2022-05-26T19:13:28.941635012Z"
}
```

The pod was created `Thu, 26 May 2022 15:13:21 -0400`

### Anything else?

We weren't able to replicate the issue by hand. However, we discovered that setting `eni.awsReleaseExcessIPs` to `false` would eliminate the problem because the IP address will remain attached to the ENI.

We verified the fix by adding the released IP address to the Instance ENI and found that the pod regained connectivity to other nodes and services on the same cluster.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
This is possibly related to #13412 (fixed by https://github.com/cilium/cilium/pull/17939). @abebars, was the 1.11.4 environment where you observed this freshly installed? Or did you notice the problem on 1.10.6 and then the problem persisted following upgrade to 1.11.4?

**Comment by abebars** [comment]
> This is possibly related to #13412 (fixed by #17939). @abebars, was the 1.11.4 environment where you observed this freshly installed? Or did you notice the problem on 1.10.6 and then the problem persisted following upgrade to 1.11.4?

@joestringer We noticed the problem originally on 10.6. Then even after upgrading another environment from 106 to 11.4 , We have seen the same problem.

**Comment by joestringer** [comment]
I see. The reason I ask is that if you freshly install a recent 1.11.x (1.11.1 or later) version, then #13412 should be fixed. If you cannot reproduce this issue on such a version directly, then probably this issue is a duplicate of #13412. On the other hand, if you can freshly install a recent v1.11.x release and reproduce again, then this must be a different issue.

**Comment by abebars** [comment]
@joestringer I think we are ok since the last upgrade and we didn’t notice the issue but we also disabled the ip release to avoid the problem in it’s entirety. I will close it for now and reopen or create a new issue if notice the issue again. thanks for the help.
