### ISSUE TITLE
FailedPostStartHook on cilium pods after helm install

### ISSUE THREAD

**Issue by leopaul36** [cilium/cilium#20024]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

`cilium-xxxxx` pods are stuck in `CrashLoopBackOff` right after the `helm install cilium cilium/cilium --version 1.11.5 --namespace kube-system` command:

```
NAME                                          READY   STATUS              RESTARTS       AGE
cilium-2pvrn                                  0/1     CrashLoopBackOff    10 (16s ago)   27m
cilium-c4x72                                  0/1     CrashLoopBackOff    10 (14s ago)   27m
cilium-h9jqd                                  0/1     CrashLoopBackOff    10 (26s ago)   27m
cilium-operator-75876f779d-jjzrd              1/1     Running             0              27m
cilium-operator-75876f779d-kp2ls              1/1     Running             0              27m
cilium-pt5bm                                  0/1     CrashLoopBackOff    10 (16s ago)   27m
```

On describe, I get that the PostStartHook (and the PreStopHook) fails with:
```
  Warning  FailedPreStopHook    25m (x2 over 25m)    kubelet            Exec lifecycle hook ([/cni-uninstall.sh]) for Container "cilium-agent" in Pod "cilium-2pvrn_kube-system(d2ebc633-538e-420b-8cfa-e1391982301f)" failed - error: rpc error: code = Unknown desc = command error: EOF, stdout: , stderr: , exit code -1, message: ""
  Normal   Pulled               25m (x3 over 25m)    kubelet            Container image "quay.io/cilium/cilium:v1.11.5" already present on machine
  Warning  FailedPostStartHook  25m (x3 over 25m)    kubelet            Exec lifecycle hook ([/cni-install.sh --enable-debug=true --cni-exclusive=true]) for Container "cilium-agent" in Pod "cilium-2pvrn_kube-system(d2ebc633-538e-420b-8cfa-e1391982301f)" failed - error: rpc error: code = Unknown desc = command error: EOF, stdout: , stderr: , exit code -1, message: ""
  Normal   Started              25m (x3 over 25m)    kubelet            Started container cilium-agent
```

I did not find anything relevant in the `cilium-agent` pod logs except:
```
level=info msg="Exiting due to signal" signal=terminated subsys=daemon
level=debug msg="canceling context in signal handler" subsys=daemon
```

Which I believe is caused by the `FailedPostStartHook` event.

### Cilium Version

```
cilium-cli: v0.10.7 compiled with go1.18.1 on linux/amd64
cilium image (default): v1.10.11
cilium image (stable): v1.11.5
cilium image (running): v1.11.5
```

### Kernel Version

`Linux XXXXXXXXXX 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Tue Mar 8 12:56:54 EST 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leopaul36** [comment]
[cilium-sysdump-20220531-163128.zip](https://github.com/cilium/cilium/files/8806156/cilium-sysdump-20220531-163128.zip)

**Comment by sayboras** [comment]
:wave: 

can you also share cni log file /var/run/cilium/cilium-cni.log as well ?

**Comment by sayboras** [comment]
I just notice that you are using generic helm installation, might I know which k8s cluster you are using ? There might be more suitable/platform specific helm installation as mentioned in other tabs.

https://docs.cilium.io/en/latest/gettingstarted/k8s-install-helm/

**Comment by leopaul36** [comment]
> I just notice that you are using generic helm installation, might I know which k8s cluster you are using ? There might be more suitable/platform specific helm installation as mentioned in other tabs.
> 
> https://docs.cilium.io/en/latest/gettingstarted/k8s-install-helm/

I'm using a vanila Kubernetes 1.24.0 installed with kubeadm on bare metal nodes with cri-o as a CRI.

**Comment by aanm** [comment]
@leopaul36 can you provide us with the kubelet logs and the cri-o logs as well? Thank you.

**Comment by leopaul36** [comment]
> @leopaul36 can you provide us with the kubelet logs and the cri-o logs as well? Thank you.

Hello @aanm,

I ran a new `helm install...`, here are the `kubelet` and `crio` logs of the control-plane node as well as a fresh capture of `cilium sysdump`.

Thanks for your help
[cilium-sysdump-20220607-101859.zip](
[crio_logs.txt](https://github.com/cilium/cilium/files/8851491/crio_logs.txt)
[kubelet_logs.txt](https://github.com/cilium/cilium/files/8851492/kubelet_logs.txt)
https://github.com/cilium/cilium/files/8851490/cilium-sysdump-20220607-101859.zip)
.
