### ISSUE TITLE
CI: ConformanceKind1.19: installation-and-connectivity fails on "Enable Relay" for second test

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#20034]
Example run: https://github.com/cilium/cilium/runs/6679723958?check_suite_focus=true#logs

While running the workflow, the first test without encryption passes, then Cilium apparently cleans up. However, the `hubble-peer` service is not removed. Then when installing Cilium a second time, this time with encryption, enabling relay fails with:

```
🚀 Creating Peer Service...

Error: Unable to enable Hubble:  services "hubble-peer" already exists
Error: Process completed with exit code 1.
```

**Comment by michi-covalent** [comment]
https://github.com/cilium/cilium/pull/20036 appears to fix the issue
