### ISSUE TITLE
Ginkgo CI: migrate test changes from #1674 to Ginkgo test suite

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#2005]
#1674 introduced changes to runtime tests that may need to be back ported to the Ginkgo test suite.

**Comment by eloycoto** [comment]
Changes that need to be done: 

- 01-ct --> Disable wait for endpoints
- 08-nat46 --> Fix names
- 10-proxy --> Changes related with ConntrackLocal + Policies. 
- 11-getting-started --> Disabled wait_for_cilium
- 14-policy-enforcement-docker.sh -> Disabled wait_for_endpoints
- 16-cidr-ingress-policy.sh --> Disabled policy_delete_and_wait

**Comment by eloycoto** [comment]
Fixed by https://github.com/cilium/cilium/pull/2403

Regards
