### ISSUE TITLE
Etcd no network causing kubeapi to not start

### ISSUE THREAD

**Issue by Ramshield** [cilium/cilium#20053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

I have a clean K8S cluster running on Proxmox with KVM.
I installed Cilium via helm and at that moment my cluster wasn't working for mysterious reasons.

I initialized the cluster with `kubeadm init --control-plane-endpoint k8s-master.example.com --service-dns-domain k8s.example.com.
So the kibe-api isn't starting, because etcd isn't running. But etcd can't start/connect to other hosts because it has no network connection. So basically I'm in a deadlock here.

Although I have also these errors in my syslog on Kubernetes control-plane:
```
Jun  2 13:21:21 k8s-master-02 kernel: [ 2305.724560] Dead loop on virtual device cilium_vxlan, fix it urgently!
```

EDIT:

my Kubernetes control planes can't ping each other:
```
root@k8s-master-01:~# ping 10.0.0.209 -c 1
PING 10.0.0.209 (10.0.0.209) 56(84) bytes of data.
From 10.0.0.141 icmp_seq=1 Time to live exceeded

--- 10.0.0.209 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

root@k8s-master-01:~# ping 10.0.0.210 -c 1
PING 10.0.0.210 (10.0.0.210) 56(84) bytes of data.
From 10.0.0.141 icmp_seq=1 Time to live exceeded

--- 10.0.0.210 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

I can ping outside so network is still working:
```
root@k8s-master-01:~# ping 8.8.8.8 -c 4
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=56 time=10.9 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=56 time=10.9 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=56 time=10.7 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=56 time=10.7 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3000ms
rtt min/avg/max/mdev = 10.706/10.818/10.938/0.096 ms
```

but somehow internal networking isn't anymore.
```
root@k8s-master-01:~# ip route
default via 10.0.0.1 dev ens18
10.0.0.0/24 via 10.0.0.141 dev cilium_host src 10.0.0.141
10.0.0.141 dev cilium_host scope link
10.0.1.0/24 via 10.0.0.141 dev cilium_host src 10.0.0.141 mtu 1450
```

### Cilium Version

1.11.5

### Kernel Version

Linux k8s-master-02.example.com 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

### Kubernetes Version

1.24.1

### Relevant log output

```shell
https://pastebin.com/VUEFUn09
```

### Anything else?

```
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@brb can you look at the "dead loop" error?

**Comment by Ramshield** [comment]
So this was nowhere in the documentation, but my cluster is running on 10.0.0.0/24, and the default helm chart uses `10.0.0.0/8`. This clashes. 
Changing this so a different value and creating a new k8s cluster and everything works.
