### ISSUE TITLE
CFP: Extend bpf_map_pressure metric to cover connection tracking, NAT maps

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#20069]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

If the CT or NAT maps become full, this can cause packet drops. Provide better visibility into the datapath when this occurs.

**Describe the feature you'd like**

The work in https://github.com/cilium/cilium/pull/14131 provided `bpf_map_pressure` metrics into maps managed purely by userspace. It would be nice to extend this to also provide feedback on the pressure on CT, NAT maps.

CT and NAT maps are more tricky than the other map types, partially because these maps are managed by the datapath, and also due to the use of LRU map type. It's not possible to accurately count adds and deletes for LRU maps, because some deletes are hidden. More specifically, when the map becomes full, you can still insert, but that insert has the side effect of bumping out an old entry, and this behaviour is not made visible to eBPF programs.

**(Optional) Describe your proposed solution**

One option for this is to just periodically perform a dump of these maps to count the number of entries at a point in time and export this. While this is not entirely accurate given that this takes time and the map is changing while the dump occurs, it could at least give some sense of how full the maps are. Variability in the metrics could also be insightful.

In order to do this efficiently, this feature could make use of newer kernel features like [batched map lookups](https://github.com/torvalds/linux/blob/50fd82b3a9a9335df5d50c7ddcb81c81d358c4fc/include/uapi/linux/bpf.h#L585) (available in Linux 5.6 or later).

**Comment by Jiang1155** [comment]
This CFP looks interesting. If no one already worked on this, I will spend some time on this one.

**Comment by aanm** [comment]
@Jiang1155 feel free to give it a go. I'll assign the issue to you. Thank you! cc @joestringer

**Comment by ysksuzuki** [comment]
@Jiang1155 May I know the current status of this issue? If there's anything I can do, I'd be happy to help.

**Comment by ysksuzuki** [comment]
I will work on this after finishing my on-call shift.

**Comment by ysksuzuki** [comment]
Can I assign this issue to myself?

**Comment by ysksuzuki** [comment]
Unassigned myself, since others are already working on this issue
