### ISSUE TITLE
Rename key pairs `.old` vs `.new` in k8s_watcher.go

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2006]
- [ ] https://github.com/cilium/cilium/pull/1986#discussion_r149506612
- [ ] When the object received was not the expected, add the reflect.TypeOf(object) result to the log message

**Comment by raybejjani** [comment]
:( yeah. I had hoped someone would call it out in original PRs, but I also hoped that log importers would be able to prefix match. Another scheme (which I started with) is to print an array under the same key, following a [old, new] convention. I doubt that makes importing simpler, though).
