### ISSUE TITLE
 Issue 2008 Feature Request: Add option to disable loadbalancing 

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2008]
When integrating with higher level orchestration systems, we currently don't allow to opt out of performing load balancing operations.

- [x] Add flag to disable translating Kubernetes services to Cilium services

**Comment by manalibhutiyani** [comment]
@tgraf  We do not need to add an additional flag. 
if !d.conf.IsLBEnabled()  {
}

can be used instead?

**Comment by manalibhutiyani** [comment]
Since we already have `d.conf.IsLBEnabled()` an additional flag is not needed.

**Comment by tgraf** [comment]
> @tgraf We do not need to add an additional flag.
> if !d.conf.IsLBEnabled() {
> }
> 
> can be used instead?

The existing LB flag is really to enable ingress support. We should rename this eventually but have to discuss ingress support in general first.
