### ISSUE TITLE
Label all Cilium resources with a known label for tracking purposes and sysdump

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#20088]
Kubernetes [has](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) `app.kubernetes.io/part-of: X` to be used for this purpose. We can make use of this with Cilium to make it obvious which resources belong to / used by Cilium. We can also utilize this label to fetch all relevant resources during a sysdump to ensure we don't miss any important information.

Proposal: label resources with `app.kubernetes.io/part-of: cilium`

**Comment by sayboras** [comment]
> I would like to know which resources need label?

The list of resources can be found from cilium helm chart in below link. I have assigned the issue to you. Please feel free to reach out if you need any help in cilium #development slack channel.

Helm chart: https://github.com/cilium/cilium/tree/master/install/kubernetes/cilium/templates

Contributing docs: https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#howto-contribute
