### ISSUE TITLE
Ginkgo CI: consul Docker containers are left running on Jenkins slaves

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2009]
While triaging issues on Jenkins a few days back, I noticed that there were some Consul Docker containers running. This is an issue introduced by the Ginkgo tests. Make sure that Consul docker images left behind from unit tests are cleaned up during each build.

**Comment by eloycoto** [comment]
@ianvernon is this still a problem? the docker-compose has the option to remove the containers, so I'm not sure about this :\

**Comment by ianvernon** [comment]
@eloycoto hm, I'm wondering if when the build is aborted, if this causes docker-compose to not run its cleanup. This could be tested by running the Ginkgo build, and then aborting it during the unit tests. That is just a hypothesis though. On the node where the Ginkgo tests run, there are no containers running:

```
root@jenkins-slave-4:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@jenkins-slave-4:~# 
```

We could introduce a check during the `post` section of the Jenkinsfile to clean up containers spawned during the build if they exist. I'm not too concerned about this as there isn't any cruft leftover currently, though.
