### ISSUE TITLE
update networkpolicy then can not reach ip address 

### ISSUE THREAD

**Issue by Q0heleth** [cilium/cilium#20122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**I create a network policy like this:** 
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "tofqdn-dns-visibili"
spec:
  endpointSelector:
    matchLabels:
      org: empire
  egress:
  \- toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: "53"
           protocol: ANY
        rules:
          dns:
            - matchPattern: "*"

  \- toFQDNs:
      - matchName: "www.baidu.com"
      - matchName: "www.7k7k.com"
      - matchName: "bilibili.com"

**it works well when first create,then I update it by kubectl apply -f cnp.yaml :**

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "tofqdn-dns-visibili"
spec:
  endpointSelector:
    matchLabels:
      org: empire
  egress:
  \- toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: "53"
           protocol: ANY
        rules:
          dns:
            - matchPattern: "*"

  \- toFQDNs:
      - matchName: "www.7k7k.com"
      - matchName: "bilibili.com"

**as you see , I just delete one FQDN .but I found I can not reach www.7k7k.com or bilibili.com which still stay in networkpolicy.and when I  run `cilium bpf policy get 3259`(endpoint id) ,  "can not get label by identity id" .then I run `cilium bpf ipcache list` I can not found the ip address of www.7k7k.com or bilibili.com**

### Cilium Version

KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.2) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled
Host firewall:          Disabled
Cilium:                 Ok   1.11.0 (v1.11.0-27e0848)
NodeMonitor:            Listening for events on 48 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 47/254 allocated from 10.165.112.0/24,
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      239/239 healthy
Proxy Status:           OK, ip 10.165.112.169, 24 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 223.79   Metrics: Disabled
Encryption:             Disabled

### Kernel Version

Linu xxxxx 5.10.87-051087-generic #202112170531 SMP Fri Dec 17 11:17:54 UTC 2021 x86_64 Linux

### Kubernetes Version

1.22

### Relevant log output

level=warning msg="Unexpected release of numeric identity that is no longer allocated" identity=16778707 subsys=ipcache

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
@Q0heleth Which version of Cilium are you running?

**Comment by Q0heleth** [comment]
1.11.0 (v1.11.0-27e0848)

**Comment by Q0heleth** [comment]
> @Q0heleth Which version of Cilium are you running?

1.11.0 (v1.11.0-27e0848)

**Comment by christarazi** [comment]
Can you try with 1.11.5?

**Comment by wenhuwang** [comment]
> Can you try with 1.11.5?

@christarazi  hello, is this a bug? are you have a bugfix link?

**Comment by christarazi** [comment]
@wenhuwang Have you confirmed that upgrading to v1.11.5 fixed your issue? If so, please close this issue.

**Comment by christarazi** [comment]
@Q0heleth :point_up:
