### ISSUE TITLE
generic-veth chaining not compatible with BPF host routing

### ISSUE THREAD

**Issue by chendotjs** [cilium/cilium#20135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cannot visit local pod from host node.

For example,  the `nginx` pod is running on node `192.168.0.6`, 
```
root@192.168.0.6:~# kubectl get pod -o wide
NAME    READY   STATUS    RESTARTS   AGE     IP             NODE          NOMINATED NODE   READINESS GATES
nginx   1/1     Running   0          2m40s   192.168.0.14   192.168.0.6   <none>           <none>
root@192.168.0.6:~#
root@192.168.0.6:~# ip route get 192.168.0.14
192.168.0.14 dev vethc440f455693 src 192.168.0.6 uid 0
    cache
root@192.168.0.6:~# ping 192.168.0.14 -c 3
PING 192.168.0.14 (192.168.0.14) 56(84) bytes of data.

--- 192.168.0.14 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2055ms

root@192.168.0.6:~#
```

### How to reproduce:
 Install Cilium with generic veth chaining and strict kube-proxy replacement. 
```sh
helm install cilium cilium/cilium \
  --version 1.11.5 \
  --namespace=kube-system \
  --set cni.chainingMode=generic-veth \
  --set cni.customConf=true \
  --set tunnel=disabled \
  --set enableIPv4Masquerade=false \
  --set kubeProxyReplacement=strict
```

After some dig into the code,  I found that the icmp echo reply from the conainter was sent out directly via primary NIC of the host, which is caused by `redirect_neigh` in `redirect_direct_v4`. 

I also found that BPF host routing is currently not supported with `enable-endpoint-routes`, while in most cases generic veth CNI creates a route per endpoint/pod.

Should we add a check when chaining with veth CNI and enable BPF host routing in the meantime? 

### Code snippets

https://github.com/cilium/cilium/blob/v1.11.5/bpf/bpf_lxc.c#L873-L874
https://github.com/cilium/cilium/blob/v1.11.5/daemon/cmd/kube_proxy_replacement.go#L549-L550

### Cilium Version

Client: 1.11.5 b0d3140 2022-05-10T02:47:42+02:00 go version go1.17.9 linux/amd64
Daemon: 1.11.5 b0d3140 2022-05-10T02:47:42+02:00 go version go1.17.9 linux/amd64

### Kernel Version

Linux cce-ig-jfhf62d1-xd4s88uq-2 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
root@cce-ig-jfhf62d1-xd4s88uq-2:/home/cilium# cilium status --verbose
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.20 (v1.20.8) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [eth0 192.168.0.6 (Direct Routing)]
Host firewall:          Disabled
Cilium:                 Ok   1.11.5 (v1.11.5-b0d3140)
NodeMonitor:            Listening for events on 32 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 1/254 allocated from 10.0.1.0/24, 
Allocated addresses:
  10.0.1.225 (router)
BandwidthManager:       Disabled
Host Routing:           BPF
Masquerading:           Disabled
Clock Source for BPF:   jiffies   [250 Hz]
Controller Status:      19/19 healthy
  Name                                      Last success   Last error   Count   Message
  dns-garbage-collector-job                 5s ago         never        0       no error   
  endpoint-309-regeneration-recovery        never          never        0       no error   
  endpoint-477-regeneration-recovery        never          never        0       no error   
  endpoint-gc                               4m5s ago       never        0       no error   
  ipcache-inject-labels                     58m59s ago     59m3s ago    0       no error   
  k8s-heartbeat                             4s ago         never        0       no error   
  metricsmap-bpf-prom-sync                  4s ago         never        0       no error   
  neighbor-table-refresh                    26s ago        never        0       no error   
  resolve-identity-309                      4m15s ago      never        0       no error   
  restoring-ep-identity (477)               58m57s ago     never        0       no error   
  sync-endpoints-and-host-ips               57s ago        never        0       no error   
  sync-lb-maps-with-k8s-services            58m57s ago     never        0       no error   
  sync-node-with-ciliumnode (192.168.0.6)   59m3s ago      59m4s ago    0       no error   
  sync-policymap-309                        51s ago        never        0       no error   
  sync-policymap-477                        51s ago        never        0       no error   
  sync-to-k8s-ciliumendpoint (309)          5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (477)          6s ago         never        0       no error   
  template-dir-watcher                      never          never        0       no error   
  update-k8s-node-annotations               59m3s ago      never        0       no error   
Proxy Status:   OK, ip 10.0.1.225, 0 redirects active on ports 10000-20000
Hubble:         Ok   Current/Max Flows: 219/4095 (5.35%), Flows/s: 0.00   Metrics: Disabled
KubeProxyReplacement Details:
  Status:                 Strict
  Socket LB Protocols:    TCP, UDP
  Devices:                eth0 192.168.0.6 (Direct Routing)
  Mode:                   SNAT
  Backend Selection:      Random
  Session Affinity:       Enabled
  Graceful Termination:   Enabled
  XDP Acceleration:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   295773
  TCP connection tracking       591546
  Endpoint policy               65535
  Events                        32
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           591546
  Neighbor table                591546
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        32
  Sockmap                       65535
  Sock reverse NAT              295773
  Tunnel                        65536
Encryption:       Disabled
Cluster health:      Probe disabled
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
I think it's unlikely that generic chaining will ever work with this feature, because typically the chaining plugin should be responsible for routing. To support this means that Cilium is the one handling routing. A better way to handle that is to remove the other chained plugin and just run Cilium directly.

Given that BPF host routing was auto-enabled via the `kubeProxyReplacement=strict` flag, maybe we need to come up with a way to avoid configuring bpf host routing whenever Cilium is chaining on top of another plugin.

**Comment by chendotjs** [comment]
> Given that BPF host routing was auto-enabled via the kubeProxyReplacement=strict flag, maybe we need to come up with a way to avoid configuring bpf host routing whenever Cilium is chaining on top of another plugin.

Yes, it will be better to automatically fall back to legacy host routing when chaining on top of another plugin with some log declaring the reason.

**Comment by ysksuzuki** [comment]
Would it be OK to take this issue?

**Comment by brb** [comment]
@ysksuzuki Sure! Do you plan to fix the issue, or just disable the BPF host routing when the veth chaining is used?

**Comment by ysksuzuki** [comment]
@brb Let me investigate what is happening first, and decide how we are going to fix (or work around) it. According to https://github.com/cilium/cilium/issues/20135#issuecomment-1152744479, I'd say it's more likely to be the latter.

**Comment by ysksuzuki** [comment]
## What is happening?

If kubeProxyReplacement is strict, the BPF host route is enabled, and the per endpoint route is disabled, but the endpoint route is delegated to the Linux stack regardless of the endpoint route setting for the generic-veth. 
https://github.com/cilium/cilium/blob/master/plugins/cilium-cni/chaining/generic-veth/generic-veth.go#L170

So packets to local endpoints are not handled by the tail-calling from bpf_lxc in ipv4_local_delivery,
https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L991

but redirect_direct_v4 instead. 
https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L1112

However, redirect_direct_v4 assumes to handle packets to remote endpoints. It calls redirect_neigh with the direct routing device for single-device environments. This is why packets to a local pod are sent out directly via the primary NIC of the host.
https://github.com/cilium/cilium/blob/master/bpf/lib/fib.h#L128

## Possible solutions

1. Redirect packets only destined to remote endpoints in bpf_lxc. https://github.com/ysksuzuki/cilium/commit/e2a1d1a1fa87fa6fee7687e90ba0d5c0362a3def

2. Fall back to legacy host routing when chaining on top of another CNI plugin, checking CNIChainingStatus or NetConf.Name.
https://github.com/cilium/cilium/blob/master/daemon/cmd/status.go#L204
https://github.com/cilium/cilium/blob/8ae024c57111999f532cf578d492464580b7dea1/daemon/cmd/daemon.go#L373
https://github.com/cilium/cilium/blob/master/plugins/cilium-cni/main.go#L407

## How to reproduce

1. Create a kind cluster
```
cat > kind-config.yaml << EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
EOF

kind create cluster --config ./kind-config.yaml
```

2. Prepare a calico manifest.
```
curl https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml -O
# Edit calico.yaml, set CALICO_IPV4POOL_IPIP to Never

kubectl apply -f calico.yaml
```

3. Apply cni configuration
```
cat > cniconf.yaml << EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: cni-configuration
  namespace: kube-system
data:
  cni-config: |-
    {
      "name": "generic-veth",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "datastore_type": "kubernetes",
          "mtu": 1440,
          "ipam": {
              "type": "calico-ipam"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "cilium-cni"
        }
      ]
    }
EOF

kubectl apply -f cniconf.yaml
```

4. Install Cilium
```
helm install cilium cilium/cilium --version 1.12.1 \
  --namespace=kube-system \
  --set cni.chainingMode=generic-veth \
  --set cni.customConf=true \
  --set cni.configMap=cni-configuration \
  --set tunnel=disabled \
  --set enableIPv4Masquerade=false \
  --set enableIdentityMark=false \
  --set kubeProxyReplacement=strict \
  --set k8sServiceHost=<control plane IP> \
  --set k8sServicePort=6443
```

**Comment by ysksuzuki** [comment]
I also found code that might be related to #18042 when I'm investigating this issue. Posted https://github.com/cilium/cilium/issues/18042#issuecomment-1241851787

**Comment by ysksuzuki** [comment]
@brb @joestringer I posted the findings from my investigation https://github.com/cilium/cilium/issues/20135#issuecomment-1242882749. Do you think we should leave a chance for generic-veth users to take advantage of the BPF host routing or just fall back to the legacy host routing? I'd appreciate your input.

**Comment by brb** [comment]
> Do you think we should leave a chance for generic-veth users to take advantage of the BPF host routing or just fall back to the legacy host routing?

cc @borkmann

**Comment by joestringer** [comment]
> Do you think we should leave a chance for generic-veth users to take advantage of the BPF host routing or just fall back to the legacy host routing?

In general with generic-veth chaining we cannot know whether the chained plugin is expecting traffic to flow through the stack or not. Since the other chained plugin is responsible for underlying connectivity, I don't think it makes sense for Cilium to override its settings to put BPF host routing in place. I'd suggest that either the chained plugin understands these things well enough to enable BPF host routing itself, or users leverage only Cilium directly to take advantage of BPF host routing.

**Comment by ysksuzuki** [comment]
@joestringer Thank you for your comment.

As you mentioned, it makes sense for generic-veth users to disable BPF host routing and delegate the routing to the stack since the chained plugin would have set up entries in the kernel routing table and expect the kernel to handle it. But I'm not sure if falling back to the legacy routing mode with generic-veth breaks existing use cases. How about adding a note recommending generic-veth users to enable the legacy host routing? 

https://docs.cilium.io/en/stable/gettingstarted/cni-chaining-generic-veth/#generic-veth-cni-chaining

**Comment by joestringer** [comment]
I think there's a couple of options.
1. In the helm charts, when `cni.chainingMode` is set, configure this flag as well. The user doesn't need to do anything additional. Or
2. Extend the current set of options in that guide to include the option to disable bpf host routing.

The first one seems slightly simpler, though I don't have a strong preference either way.

**Comment by ysksuzuki** [comment]
> In the helm charts, when cni.chainingMode is set, configure this flag as well. The user doesn't need to do anything additional.

That's a good idea. I will create a PR than. Thanks for your help!

**Comment by kvaps** [comment]
Hey I use cilium in chaining with kube-proxy replacement mode, I faced with the problem that if host routing disabled it can't route external traffic to non-local nodes.

Could you help me to debug this https://github.com/cilium/cilium/issues/32714? 🙏
