### ISSUE TITLE
k8s runtime test should have failed when runtime tests failed as well

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2013]
On this build, the k8s test has passed successfully although it as failed on for the normal runtime tests https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-2007/3/execution/node/31/log/?consoleFull

How was the image build successful on the k8s runtime tests if the build os failing on the runtime tests?

**Comment by ianvernon** [comment]
The runtime tests failed during the unit tests. I'm guessing this is something that was only catchable at runtime in the unit tests? The code itself compiled, which is the only commonality between the runtime tests and Kubernetes tests. I don't see how this is a CI bug; looks like an issue with the unit tests.

**Comment by ianvernon** [comment]
@aanm can this be closed? The link in the description now 404's.
