### ISSUE TITLE
NodePort broken when no of the backend endpoints are local

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2015]
- All Cilium versions
- All kernel versions
- Kubernetes

**Comment by tgraf** [comment]
The issue seems to be that kube-proxy DNATed packets sometimes get SNATed with the private router IP `169.254.254.1` instead of the NodeIP

**Comment by f0** [comment]
#2032  does not fix the issue @tgraf  @eloycoto

**Comment by tgraf** [comment]
> #2032 does not fix the issue @tgraf @eloycoto

@f0  Should be fixed in master, #2112 was required as well.
