### ISSUE TITLE
Cilium-agent: Add CAP_SYS_CHROOT to mount-cgroup container

### ISSUE THREAD

**Issue by krouma** [cilium/cilium#20150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When deploying cilium in a cluster that uses cri-o, cilium pod fails in Init. The `mount-cgroup` container cannot execute `setns(2)` due to missing capability. This presumably doesn't happen on containerd since it has this capability enabled by default for every container. However, relying on default security settings is not desired behaviour in my opinion and this capability should be explicitly set in the DaemonSet.

### Cilium Version

1.12.0-rc2

### Kernel Version

5.17.11-200.fc35.x86_64

### Kubernetes Version

1.23.7

### Relevant log output

```shell
nsenter: reassociate to namespace 'ns/mnt' failed: Operation not permitted
```

### Anything else?

[Default capabilities of cri-o](https://github.com/cri-o/cri-o/blob/main/docs/crio.conf.5.md#crioruntime-table)

This issue can be mitigated by running cilium as privileged

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
should it fixed by https://github.com/cilium/cilium/pull/19903 ? Can you try it out with master branch and let us know if it's working ? Thanks.

**Comment by krouma** [comment]
Oh, I missed this PR. It now works but I had to manually specify tag because `latest` tag is not present in docker.io or quay.io

**Comment by sayboras** [comment]
yeah, we are no longer publishing latest tag, but you can use _quay.io/cilium/cilium-ci:latest_ intead. Other images are following the same convention (e.g. -ci suffix).

I am closing this issue now, thanks for reporting this.
