### ISSUE TITLE
send_trace_notify in __encap_with_nodeid() set dst security identity to unknown

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#20169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

dst security identity is set to `0` in `send_trace_notify` result in dst security identity to be `unknown` in cilium datapath  monitor log:

```
to-overlay: 78 bytes (78 captured), state unknown, interface cilium_vxlan, , identity 12073->unknown, orig-ip 0.0.0.0
```

line 151

```
119 static __always_inline int
120 __encap_with_nodeid(struct __ctx_buff *ctx, __u32 tunnel_endpoint,
121                     __u32 seclabel, __u32 vni __maybe_unused,
122                     enum trace_reason ct_reason, __u32 monitor)
123 {
................
150 
151         send_trace_notify(ctx, TRACE_TO_OVERLAY, seclabel, 0, 0, ENCAP_IFINDEX,
152                           ct_reason, monitor);
153         return 0;
154 }

```

### Cilium Version

1.11.x

### Kernel Version

Linux cilium-dev 5.18.0+ #1 SMP PREEMPT_DYNAMIC Wed Jun 1 21:37:44 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment]
not stale

**Comment by aditighag** [comment]
> not stale

I've pinned the issue so that it's not marked as stale. :)
