### ISSUE TITLE
helm vlan.bpfBypass ignored

### ISSUE THREAD

**Issue by coelho** [cilium/cilium#20173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using `--set bpf.vlanBypass=0` in Helm is ignored. The flag shows up in viper, but not in the runtime config.

`# cat viper-agent-config.yaml | grep vlan-bpf`
vlan-bpf-bypass: 0

`# cat agent-runtime-config.json | grep VLAN`
 "VLANBPFBypass": [],

### Cilium Version

Client: 1.11.5 b0d3140 2022-05-10T02:47:42+02:00 go version go1.17.9 linux/amd64
Daemon: 1.11.5 b0d3140 2022-05-10T02:47:42+02:00 go version go1.17.9 linux/amd64

### Kernel Version

Linux 5.17.8-051708-generic #202205151940 SMP PREEMPT Mon May 16 13:36:10 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Thanks for reporting this issue, a quick triage shows below hidden error from https://github.com/cilium/cilium/blob/b411ca306ce68a41e174f98dc42db8fa0be156af/pkg/option/config.go#L2940.

This issue is happening in master branch as well.

```
error="unable to cast \"0\" of type string to []int" subsys=config
```

**Comment by sayboras** [comment]
@pippolo84 just notice that you are keen to work on this.

If it's not much of trouble, can you also correct the typo in helm values.yaml as well i.e. vlan-bpf-bypass should be vlanBypass.

https://github.com/cilium/cilium/blob/d06cc727d3696bd27310c8dfa628ee97deda53ae/install/kubernetes/cilium/values.yaml#L326

https://github.com/cilium/cilium/blob/d06cc727d3696bd27310c8dfa628ee97deda53ae/install/kubernetes/cilium/templates/cilium-configmap.yaml#L853

**Comment by sfxworks** [comment]
Is there a current workaround for this?

**Comment by sayboras** [comment]
> Oh I see, just adding the value to the configmap

Adding the value to the configmap might not work due to underlying flag parsing, the complete [fix](https://github.com/cilium/cilium/pull/20304) should be merged soon

**Comment by gandro** [comment]
Yeah, due to another bug passing it in the ConfigMap does not work. A potential workaround is to pass the `--vlan-bpf-bypass` argument directly via command-line, bypassing the currently broken ConfigMap validation logic. To do that, you can add it to the `extraArgs` Helm value, e.g. `helm install --set "extraArgs={--vlan-bpf-bypass=1\\,2}"`, which will add `--vlan-bpf-bypass=1,2` as an additional argument to the agent.

As Tam mentioned, the proper fix is on the way.
