### ISSUE TITLE
CFP:  Support Localization of Documentation

### ISSUE THREAD

**Issue by xmulligan** [cilium/cilium#20182]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

Many people like to read documentation in their mother tongue. For example, in Kubernetes documentation, only 50% of the page views are in English. Supporting localization of the Cilium documentation will help grow our community and provide good entry points for new contributors from different backgrounds to the Cilium community.

**Describe the feature you'd like**

To help people start a new localization, they need:

1) Community guidelines on how to start a localization
2) Technical tutorials how to create and build the localization
3) Minimum requirements for having a localization be part of the documentation
4) Build fall back into the docs for when a page hasn't been translated

**(Optional) Describe your proposed solution**

The Kubernetes project has a good framework that we could follow:
1) See https://kubernetes.io/docs/contribute/localization/. Some key parts would be:
    a) If you want the Kubernetes documentation localized into a new language, here's what you need to do. Because contributors can't approve their own pull requests, you need at least two contributors to begin a localization. All localization teams must be self-sustaining. The Kubernetes website is happy to host your work, but it's up to you to translate it and keep existing localized content current.
    b) Localizing all of the Kubernetes documentation is an enormous task. It's okay to start small and expand over time. When you start a new localization, you must localize all the [minimum required content](https://kubernetes.io/docs/contribute/localization/#minimum-required-content) before the Kubernetes project can publish your changes to the live website.
    c) Localizing the README and CoC

2) Create a README ([Kubernetes example](https://github.com/kubernetes/website/blob/main/README.md)) that tells people how to build, test, and troubleshoot the documentation.

3) Decide upon a set of minimum required content for localized documentation to be mereged into master. I would suggest the Cilium Overivew, Cilium Installation, Community, and Development Guide sections.

4) Make sure the docs fall back to English rather than 404 when a page has not been translated yet. 

**Reference**

These two talks from Zach Corleissen are also helpful to understand how Kubernetes did it:

[Multilingual Kubernetes: The kubernetes.io stack, how we got there, and what it took to get there
](https://archive.fosdem.org/2019/schedule/event/multikuber/)

[Localize your open source documentation: a Kubernetes case study](https://www.youtube.com/watch?v=0k9UkMrMBYM&t=1s)

**Comment by xmulligan** [comment]
This is also related to #19976 and #19922

**Comment by xmulligan** [comment]
Also related to https://github.com/cilium/cilium/pull/17542

**Comment by xmulligan** [comment]
I also just saw https://gitlocalize.com/

**Comment by Oms-343** [comment]
> 

 gitlocalize seems promising. we need to dig a liitle bit more on translation aspect of the website
