### ISSUE TITLE
openshift documentation - securitycontextcontraints

### ISSUE THREAD

**Issue by ctml91** [cilium/cilium#20196]
When deploying cilium on openshift, the docs only mention SCC's for the cilium test but can't seem to find requirements for the operator and cilium workloads themselves.

https://docs.cilium.io/en/stable/gettingstarted/k8s-install-openshift-okd/

When deploying hubble, the relay throws this error on startup which I assume is due to elevated privileges required on the node. I've already granted the hostaccess scc to the hubble relay service account which at least allowed the pods to startup (does not out of box) but the container still exits with this message. I am using CNI chaining with openshift-sdn (generic veth).

```
Error: failed to start gops agent: open /1: permission denied
```

Thanks in advance!

**Comment by rolinh** [comment]
PR #18620 has been merged and backported to the v1.10 and v1.11 branches of Cilium and available with Cilium v1.10.11+ and v1.11.5+ as well as the upcoming v1.12 release.
