### ISSUE TITLE
help-wanted: qustion about cilium service-mesh

### ISSUE THREAD

**Issue by zhanghe9702** [cilium/cilium#20193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

is it possible to  configure CiliumEnvoyConfig like istio (VirtualService+ DestinationRule) , route traffic to service subset?
[cilium slack discussion](https://cilium.slack.com/archives/C2B917YHE/p1654142203636789)

### Cilium Version

origin/master 
commit b411ca306ce68a41e174f98dc42db8fa0be156af (origin/master, origin/HEAD)
Author: Paul Chaignon <paul@cilium.io>

### Kernel Version

Linux zhanghe 5.15.0-35-generic #36-Ubuntu SMP Sat May 21 02:24:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Thanks for your issue, I am exploring this, and will share my findings later on.

**Comment by zhanghe9702** [comment]
hi, @sayboras , could you sharing your slides or documentions about this ? thanks very much!

**Comment by sayboras** [comment]
Sorry for late reply, I didn't explore on this further as there is another parallel work related to Gateway API #20655. 

Multiple initiatives are going on in [upstream Gateway API and GAMMA](https://docs.google.com/document/d/1s5hQU0CB9ehjFukRmRHQ41f1FA8GX5_1Rv6nHW6NWAA/edit).

**Comment by zhanghe9702** [comment]
:), as far as i known, it's not possible, cause `CiliumClusterwideEnvoyConfig/CiliumEnvoyConfig` CRD using `services` field as an frontend service reference by `resources`, and every service in `services` field will be an `envoy cluster` resource, but istio split every k8s service by `subset` label seletor to different `envoy cluster`, they are  different controller logic.

**Comment by sayboras** [comment]
:wave: sorry for late reply, I was on PTO during that time.

The changes for #20655 is merged to master, and will be part of 1.13. 

I am closing the issue, feel free to re-open if you have any related concern. Thanks a lot.
