### ISSUE TITLE
Feature: Policy specification for L4 port mappings

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#202]
- [ ] Allow specificy in policy what port mappings should occur, e.g. pod with label "role=backend" should map port 80 to port 8080.
- [ ] Map policy spec to exiting BPF port mapping facilty
- [ ] Tests

**Comment by danwent** [comment]
can you clarify this item?

**Comment by tgraf** [comment]
> can you clarify this item?

The main objective is to allow mapping a port, e.g. a pod listening on 8080 is mapped to port 80 without requiring to change the pod spec.

**Comment by tgraf** [comment]
The best-practice is to use k8s services for this these days so this is no longer required
