### ISSUE TITLE
[Docs] By default Cilium doesn't work if node is in 10.0.0.0/24 network

### ISSUE THREAD

**Issue by wokalski** [cilium/cilium#20204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using: k3s on bare metal
All nodes are provisioned using DHCP in 10.0.0.0/24

---

This is mostly a documentation "bug", it's logical to me that it doesn't work but it should be documented somewhere. We provisioned our bare metal nodes in 10.0.0.0/24 range. After installing cilium using helm with:

```
helm install cilium cilium/cilium --version 1.11.5 \
      --set hubble.relay.enabled=true \
      --set hubble.ui.enabled=true \
      --set egressGateway.enabled=true \
      --set bpf.masquerade=true \
      --set kubeProxyReplacement=strict
```

I lost all connectivity to other nodes, except for the gateway. I can see all traffic originates from the cilium_host  interface but never arrives at eno1  (the physical interface). so for example ping -I eno1 10.0.0.86 works but ping 10.0.0.86 doesn’t.

`ip route` looked like this:

```
core@cplane1 ~ $ ip route
default via 10.0.0.1 dev eno1 proto dhcp src 10.0.0.3 metric 1024
10.0.0.0/24 via 10.0.2.177 dev cilium_host src 10.0.2.177 mtu 1450
10.0.0.0/24 dev eno1 proto kernel scope link src 10.0.0.3 metric 1024
10.0.0.1 dev eno1 proto dhcp scope link src 10.0.0.3 metric 1024
```

I believe docs should say that one should either have nodes in a different subnet OR set `ipam.operator.clusterPoolIPv4PodCIDRList` explicitly.

### Cilium Version

cilium-cli: v0.10.7 compiled with go1.18.1 on linux/amd64
cilium image (default): v1.10.11
cilium image (stable): v1.11.5
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"

### Kernel Version

Linux cplane2 5.15.43-flatcar #1 SMP Tue May 31 00:28:53 -00 2022 x86_64 Intel(R) Xeon(R) CPU E5-2440 0 @ 2.40GHz GenuineIntel GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@wokalski yes, that's a fair point. Would you like to submit a documentation PR regarding this?
