### ISSUE TITLE
Can anyone invite me to the slack,thx

### ISSUE THREAD

**Issue by difficultwork** [cilium/cilium#20226]
my email is yemo@foxmail.com
plz invite me to Cilium & eBPF on slack

**Comment by difficultwork** [comment]
my email is yemo@foxmail.com
plz invite me to Cilium & eBPF on slack

**Comment by sayboras** [comment]
please use this one https://cilium.herokuapp.com/ :)

**Comment by difficultwork** [comment]
> please use this one https://cilium.herokuapp.com/ , which is from cilium home page https://cilium.io/.

thx, but i use mobile slack and i‘ve joined other group. if no one invite me, i should use a new email to join Cilium & eBPF :(

**Comment by difficultwork** [comment]
> @difficultwork I've tried to invite you but the invitation didn't work <img alt="image" width="527" src="https://user-images.githubusercontent.com/5714066/174028927-40bb3da0-fde9-481f-a350-d442388f717b.png">

so kind u are, thank u very much.
it’s pity, so i will try other way.
thx again.
