### ISSUE TITLE
Document default (and hidden) metrics

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#20235]
We have the [metrics reference](https://docs.cilium.io/en/latest/operations/metrics/#metrics-reference) page which is useful for Cilium users. We can make it even more useful by adding a column to distinguish which metrics are enabled by default and which are not (hidden).

https://github.com/cilium/cilium/pull/20225 can be taken as an example, but it only goes as far as FQDN metrics. We should do this for all the metrics. 

The metrics enabled by default can be found at [`pkg/metrics.DefaultMetrics()`](https://github.com/cilium/cilium/blob/590388d728de5ae17f950cb8bf1cc694049522d3/pkg/metrics/metrics.go#L583).

**Comment by kanurag94** [comment]
@christarazi Can I take this up? -- hopefully will get accustomed to codebase with this
