### ISSUE TITLE
CFP: Vulnerability management

### ISSUE THREAD

**Issue by jsonmp-k8** [cilium/cilium#20271]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**
Cilium runs as a daemonset and with daemonset running on huge cluster which is 2500 or more nodes, the number of instances of daemonsets increases. So if the cilium image has 4 vulnerabilities, the number of vulnerabilities multiplies by the number of nodes. For Eg: in the above case we will have 10k instances of vulnerabilities on a single cluster. This multiplies by the number of clusters. With companies focusing more on cyber security and vulnerability, it would be really great to have a vulnerability management process for all the  new releases.

**Describe the feature you'd like**

With more focus on cyber security and vulnerability, it would be really great to have a vulnerability management process for all the  new releases. This can include scanning images before the release process or having distroless images(not sure if its feasible)

**(Optional) Describe your proposed solution**
N/A

**Comment by jsonmp-k8** [comment]
Thanks @aanm. Any progress in that direction will be greatly appreciated.

**Comment by aanm** [comment]
@jsonmp-k8 feel free to submit a PR that enables this.
