### ISSUE TITLE
Cilium agent crashloopback running on m6a instances

### ISSUE THREAD

**Issue by stroobl** [cilium/cilium#20280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
The issue I see looks exactly like what was supposed to be fixed in #18197 and as far as I see the m6a.large instance type where it fails is in fact included in the instance types of the included aws-sdk. However only m6 instances fail, m5 instances in the same cluster work fine.

Cilium agent enters on crashloopback state due to fail health and liveness check becouse waiting for IPs to become available in allocation pool

cilium agent log
```
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-10-128-180-17.us-west-2.compute.internal required=8 subsys=ipam
```
cilium-operator log
```
level=warning msg="Could not determined instance limits, maximum allocatable ipv4 addresses will be 0 (unlimited) this could lead to ip allocation overflows if the max-allocate flag is not set" adaptors-limit=unknown first-interface-index=0 subsys=eni
level=warning msg="Unable to maintain ip pool of node" error="Unable to determine limits" instanceID=i-0ac56c84ea94c6121 name=ip-10-128-180-17.us-west-2.compute.internal subsys=ipam
```

### Cilium Version

1.11.6

### Kernel Version

kernel 5.10.118 (Bottlerocket OS 1.8.0 (aws-k8s-1.21))

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump
[cilium-sysdump-20220622-115904.zip](https://github.com/cilium/cilium/files/8956706/cilium-sysdump-20220622-115904.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
:wave: 

The related changes were not back-ported to v1.11 branch, hence there is no m6a limits defined. Can you try the workaround mentioned [here](https://github.com/cilium/cilium/issues/18197#issuecomment-992448303) for time being ? 

https://github.com/cilium/cilium/blob/v1.11/pkg/aws/eni/limits/limits.go

**Comment by stroobl** [comment]
Oh, sorry about that. I got confused by the PR that mentioned 1.11, but that's apparently the SDK version.
I've been looking into that workaround, but it's not really clear how it should be applied. There is no config-map (aws-instance-limit-mapping or another one) for the operator as far as I see? (Only cilium-config).

**Comment by sayboras** [comment]
This flag is for operator. You can either pass it directly as part of command in operator deployment manifest, or using helm option `.Values.extraConfig`

https://github.com/cilium/cilium/blob/v1.11/install/kubernetes/cilium/templates/cilium-configmap.yaml#L816

**Comment by stroobl** [comment]
Ok, thanks. I had to experiment a little to the format right in the helm values file, but this appears to work for multiple instance types:
```
extraConfig:
  aws-instance-limit-mapping: |
    {
     "m6a.large": "2,4,4",
     "m6a.2xlarge": "2,4,4",
     "m6g.medium": "2,4,4"
    }
```
