### ISSUE TITLE
Support etcd V3

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#203]

**Comment by aanm** [comment]
Already done

**Comment by tgraf** [comment]
Excellent, it was still marked todo in the roadmap PR. I will mark it as done there as well.

**Comment by aanm** [comment]
Ah, right. I'm still waiting for the release 3.1.0 so I can update the test images accordingly but so far the tests have been working with our v3 client and 3.1.0-rc1.

**Comment by tgraf** [comment]
OK, can you update this issue to track the waiting and task to update the test images then?

**Comment by aanm** [comment]
Yep makes sense.
