### ISSUE TITLE
CI: Multicluster / Cluster mesh provisioning fails with `The network "default" does not have available private IP space`

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#20338]
## CI failure

A (ephemeral?) provisioning failure which can occur in the CI Multicluster (maybe also ConformanceGKE) test:

```
zone: 'us-west2-a'>] finished with error: The network "default" does not have available private IP space in 10.0.0.0/9 to reserve a /14 block for pods for cluster {Zone=us-west2-a, ProjectNum=185287498374, ProjectName=***, ClusterName=cilium-cilium-2547825658-mesh-2, ClusterHash=49b8b652c99f4a2499e61bb405d765399a0c4832836647f99dd4ee06e0e5f328}.
```

Observed in: https://github.com/cilium/cilium/runs/7019814122  -- [logs_510456.zip](https://github.com/cilium/cilium/files/9008971/logs_510456.zip)

**Comment by tklauser** [comment]
FWIW, this is also occurring in cilium-cli CI: https://github.com/cilium/cilium-cli/issues/940

**Comment by tklauser** [comment]
Also observed on https://github.com/cilium/cilium/pull/21212 for GKE, multicluster and external workloads workflows, e.g. https://github.com/cilium/cilium/runs/8207578433?check_suite_focus=true
