### ISSUE TITLE
CFP: Support automatically creating grafana dashboard configmaps

### ISSUE THREAD

**Issue by chancez** [cilium/cilium#20354]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

As a user of cilium, I would like to have grafana dashboards created automatically as part of my cilium install.

**Describe the feature you'd like**

Support automatically creating Grafana dashboard configmaps with correct default labels to enable grafana helm chart sidecar to detect the dashboards and install them in grafana automatically.

**(Optional) Describe your proposed solution**

Grafana supports loading dashboards from configmaps "automagically" using a sidecar that watches for configmaps and secrets with specific labels when installing Grafana using it's helm chart. See https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-dashboards for an example.

**Comment by aanm** [comment]
Aren't the dashboards specific to a particular grafana version? If yes, how could we automatically have the right configmap based on that?

**Comment by chancez** [comment]
> Aren't the dashboards specific to a particular grafana version? If yes, how could we automatically have the right configmap based on that?

Not really. For the most part, the dashboard JSON is backwards compatible, and not really tied too specifically to any particular Grafana version. Dashboards written for Grafana 6 still work for Grafana 9, mostly.

The only caveat is that in more recent versions of Grafana, they have introduced newer panel types that do not exist in older Grafana versions, and they have deprecated 1-2 panel types with the introduction of better designed panels that support the use cases of the deprecated panels better.

I would need to check, but I don't believe Grafana gas removed the deprecated panel types yet, but might be planning on it.

FWIW, some projects do provide Grafaba dashboards configmaps as part of their helm charts. It's relatively common within the prometheus ecosystem in K8s. 

Eg: 
- https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14 
- https://github.com/thanos-io/thanos/tree/main/mixin/dashboards
