### ISSUE TITLE
CFP: HELM - podDisruptionBudget / pdb - resources

### ISSUE THREAD

**Issue by mvink-guida** [cilium/cilium#20381]
## Cilium Feature Proposal
        
HELM - podDisruptionBudget resources - operator and others

**Is your feature request related to a problem?**

There are podDisruptionBudget's described in the values.yaml and the readme but they don't exist in the templating / resources section. We have e.g. the cilium-operator running in kube-system and for the using cluster autoscaler it requires a pdb else it can not drain a node totally, and the node keeps running. So a pdb saves in cost eventually next to the stability of the operator.

So for now i can deploy the pdb myself, but would be a "nice to have" when it is integrated in the helm chart.

**Describe the feature you'd like**
Add the actual pdb functionality in the helm templating

**Comment by mvink-guida** [comment]
Ok good news, then i have to wait for the 12.x release, since it is there but only in the 12.x Release candidates.

https://github.com/cilium/cilium/tree/v1.11.6/install/kubernetes/cilium/templates/cilium-operator

Thanks

**Comment by sayboras** [comment]
Related PR https://github.com/cilium/cilium/pull/18317.

**Comment by sayboras** [comment]
Closed this github issue as there is no action pending.

If you think it's critical for 1.11 branch, please highlight either here or cilium slack channel.
