### ISSUE TITLE
Terminating endpoint receives new connections with KPR and DSR

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#20382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We see our contour/envoy receives new connections when those states are terminating with the CIlium KPR and DSR mode. Contour/Envoy waits for connections to drain in its preStop hook, but some new connections are still coming in.

Graceful termination does not seem to work as expected in a particular case where a client accidentally picks a stale source port. CT_SERVICE entries remain for six hours because FIN/ACK never comes to intermediate nodes. So clients are likely to hit the same source ports with the DSR mode.
https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/#graceful-termination
> When Cilium agent receives a Kubernetes update event for a terminating endpoint, the datapath state for the endpoint is removed such that it won’t service new connections, but the endpoint’s active connections are able to terminate gracefully.

## How to reproduce

- Pick a source port from ct entries on an intermediate node. (49444)
```
$ kubectl -n kube-system exec cilium-pgz55 -- cilium bpf ct list global
TCP OUT 10.72.32.1:80 -> 10.72.3.2:49444 service expires=17140361 RxPackets=0 RxBytes=289 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=17055986 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=65 SourceSecurityID=0 IfIndex=0
```

- Rollout restart Envoy
```
$ kubectl -n ingress rollout restart deployment/envoy
$ kubectl -n ingress get po
NAME                       READY   STATUS    RESTARTS   AGE    IP            NODE          NOMINATED NODE   READINESS GATES
envoy-87d75f94d-fwn9j      3/3     Running   0          11s    10.64.0.226   10.69.0.196   <none>           <none>
envoy-b884c4585-v6h64      3/3     Terminating   0          9m13s   10.64.0.229   10.69.0.196   <none>           <none>
```

- Send a request to Envoy using the same source port after it becomes Terminating
```
$ curl -v --local-port 49444 http://l4lb-bench.sandbox.gcp0.cybozu-ne.co/
```

- Terminating Envoy receives a new connection
```
Jul  4 05:08:56.656: 10.72.3.2:49444 -> ingress/envoy-b884c4585-v6h64:8080 L3-L4 FORWARDED (TCP Flags: SYN)
Jul  4 05:08:56.656: 10.72.3.2:49444 -> ingress/envoy-b884c4585-v6h64:8080 to-endpoint FORWARDED (TCP Flags: SYN)
Jul  4 05:08:56.657: ingress/envoy-b884c4585-v6h64:46134 -> sandbox/suzuki-test-966c475fd-d4whg:8000 to-stack FORWARDED (TCP Flags: ACK, PSH)
Jul  4 05:08:56.657: ingress/envoy-b884c4585-v6h64:46134 -> sandbox/suzuki-test-966c475fd-d4whg:8000 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Jul  4 05:08:56.657: ingress/envoy-b884c4585-v6h64:46134 <- sandbox/suzuki-test-966c475fd-d4whg:8000 to-stack FORWARDED (TCP Flags: ACK, PSH)
Jul  4 05:08:56.657: ingress/envoy-b884c4585-v6h64:46134 <- sandbox/suzuki-test-966c475fd-d4whg:8000 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Jul  4 05:08:56.658: 10.72.3.2:49444 -> ingress/envoy-b884c4585-v6h64:8080 to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Jul  4 05:08:56.658: 10.72.3.2:49444 -> ingress/envoy-b884c4585-v6h64:8080 to-endpoint FORWARDED (TCP Flags: ACK)
```

### Cilium Version

$ cilium version
cilium-cli: v0.11.4 compiled with go1.18.1 on linux/amd64
cilium image (default): v1.11.3
cilium image (stable): unknown
cilium image (running): 1.11.6.1

### Kernel Version

Linux rack2-cs5 5.15.48-flatcar 

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"archive", BuildDate:"2022-03-23T08:04:34Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

### Anything else?

Here is our values.yaml

```
bgp:
  announce:
    loadbalancerIP: true
  enabled: true
bpf:
  hostRouting: true
cni:
  chainingMode: "generic-veth"
  customConf: true
datapathMode: "veth"
devices: "eth+ eno1+ eno2+"
enableIPv4Masquerade: false
enableIdentityMark: false
externalIPs:
  enabled: true
hostPort:
  enabled: false
hostServices:
  enabled: true
  hostNamespaceOnly: true
hubble:
  relay:
    enabled: true
    tls:
      server:
        enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
  tls:
    auto:
      method: "cronJob"
  metrics:
    enabled:
      - "dns"
      - "drop:destinationContext=pod|dns|ip;sourceContext=pod|dns|ip"
      - "tcp"
      - "flow:destinationContext=pod|dns|ip;sourceContext=pod|dns|ip"
      - "icmp"
      - "http"
k8sServiceHost: 127.0.0.1
k8sServicePort: 16443
kubeProxyReplacement: "partial"
loadBalancer:
  # We can't enable XDP Acceleration because of the issue https://github.com/cilium/cilium/issues/19453
  acceleration: disabled
  algorithm: maglev
  mode: dsr
maglev:
  hashSeed: 3HCx6JennjWtot2U
nodePort:
  directRoutingDevice: "e+"
  enabled: true
operator:
  rollOutPods: true
  prometheus:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
policyAuditMode: false
policyEnforcementMode: "default"
prometheus:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 400Mi
rollOutCiliumPods: true
tunnel: "disabled"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
@aditighag, ptal.

**Comment by borkmann** [comment]
@ysksuzuki we recently changed some of the logic related to it in https://github.com/cilium/cilium/pull/19800 . You could probably lower the default `bpf-ct-timeout-service-tcp-grace` ... but I kind of agree that for terminating backends it should drain.

**Comment by ysksuzuki** [comment]
@aditighag @borkmann Thank you for your comment!

Yes, #19451 can resolve our case. Cilium selects a new backend if the ct_service entry is closing and CT_SERVICE_CLOSE_REBALANCE(30) seconds have passed since the last tx, correct?

We are using v1.11.6, and this PR seems not to be backported to v1.11. So I will apply the patch to v1.11.6 and see if this problem can be fixed in our environment.

**Comment by brb** [comment]
> If we set bpf-ct-timeout-service-tcp-grace 0, Cilium always selects a new backend when it receives an SYN packet that has the same old tuple. Am I right?

Yes. Just keep in mind that a delayed packet from the previous connection which 5-tuple matches the new connection might be accepted by the new connection (it's one of the reasons why the TIME_WAIT state exists in TCP; see https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux#purpose).

If we set the grace period T > 0, then during the T the same backend will be used. This might lead to the SYN packet of the new connection to be dropped, if the previous connection hasn't been fully terminated.
