### ISSUE TITLE
Generate values.yaml from an installation

### ISSUE THREAD

**Issue by ddellarocca** [cilium/cilium#20385]
Hi,
I've to update cilium in a k8s cluster that were not installed using helm and I don't have the `values.yaml` file anymore, the version that is installed is `1.10.4` and i need to update it to `1.11.6` in order to upgrade k8s to 1.22.
Now is there a way to generate or create a `values.yaml` file for helm starting with the installed one?
Thanks.

**Comment by sayboras** [comment]
:wave: 

If cilium is installed with helm, you can get the manifests again via below command. If not, you can still check the runtime configuration/flags from pods. [Cilium sysdump](https://docs.cilium.io/en/latest/operations/troubleshooting/#automatic-log-state-collection) can also give a lot of info about configuration.

Helm

```
$ kubectl secrets -n kube-system sh.helm.release.v1.cilium.v1 -o json | jq .data.release | tr -d '"' | base64 -d | base64 -d | gzip -d
```

Runtime agent configuration

```
kubectl -n kube-system exec ds/cilium -- cat /var/run/cilium/state/agent-runtime-config.json
```

**Comment by ddellarocca** [comment]
Ok, thanks, I'll try it out.
