### ISSUE TITLE
Ginkgo CI: focus should use selected specs to determine VMs to run

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2040]
When a developer runs the ginkgo tests, something like:

`cilium/test $ ginkgo --focus "PolicyEnforcement"`

The test/ginkgoext function `GetScope()` reads this focus string and fetches the prefix. If the prefix of this string is "k8s", then the `BeforeSuite()` logic will launch the k8s VMs to test from; otherwise, it will launch the runtime VM.

In the above case, PolicyEnforcement is actually an `It()` statement inside `test/k8sT/Policies.go`, and so it should launch the k8s VMs to perform the test. However, because the focus string didn't start with the prefix `k8s`, the runtime VMs are run. As a result, the test eventually fails because the k8s VMs were not provisioned.

Ideally, when `ginkgo --focus xxx` is run, the actual test 'xxx' should be looked up and the VM dependencies determined from there.

We can work around this by renaming/prefixing all of the `It()` statements in the `test/k8sT/` directory with `k8s`, but it'd be nice to get a more long term solution.

**Comment by eloycoto** [comment]
I had this problem before, and I didn't find a better way. The thing that I use to do is to change `It` for XIT and focus the only test that I want to test. 

Maybe added a new flag, with scope fix the problem, but if the test name match in runtime you're going to have the same problem, Ginkgo will try to run both tests at runtime and k8s. 

Related issue in Ginkgo: 
https://github.com/onsi/ginkgo/issues/144

**Comment by joestringer** [comment]
This is documented, and it's a known behaviour of the CI at this point. It's unlikely someone will take up the work to improve this case because the barrier to fixing it is much higher than just working around via the "k8s" prefix. Closing.
