### ISSUE TITLE
Loadbalancer service egress connection via DSR breaks when rollout restart of pods.

### ISSUE THREAD

**Issue by polarroyo** [cilium/cilium#20418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When targets of a LoadBalancer service with DSR enabled are rollout restarted, as soon as the pod is removed from the service endpoint list, egress connectivity of the Pod stops working.

Expectation:
The pod should have egress connectivity till the pod is completely terminated. This is the default behavior of pods behind a LoadBalancer service without DSR.

### Cilium Version

v1.11.3-62aa82d

### Kernel Version

5.4.0-90-generic

### Kubernetes Version

v1.21.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
Have you enabled https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/#graceful-termination?

**Comment by polarroyo** [comment]
Hello, thanks for pointing to that documentation!

I have enabled feature gate: EndpointSliceTerminatingCondition in the cluster, restarted cilium, confirmed that Graceful Termination is enabled, but we still see the same behavior.The pod can not send the
