### ISSUE TITLE
Ingress: Persistent Envoy filters

### ISSUE THREAD

**Issue by tnorlin** [cilium/cilium#20427]
There are some cases where the standard Envoy filters are not enough, and I encountered such a case when I wanted to implement Home Assistant (https://github.com/home-assistant/core) in my cluster when there is a need to enable Websockets.

Due to implementation of CiliumEnvoyConfig it is possible to enable other filters (such as enabling Websocket) within the HttpConnectionManager like this:

>      - filterChainMatch:
>         transportProtocol: tls
>       filters:
>       - name: envoy.filters.network.http_connection_manager
>         typedConfig:
>           '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
>           httpFilters:
>           - name: envoy.filters.http.router
>           rds:
>             routeConfigName: cilium-ingress-hass-hass-ingress_route
>           statPrefix: cilium-ingress-hass-hass-ingress
>           upgrade_configs:
>           - upgrade_type: websocket

This works fine as long as there are no changes to the Ingress object, but the issue is that all kinds of changes (even updates of annotations and labels) clears out the object to its default state and resets every customization and I fail to see how to make the change persistent.

It would be neat if there was some fields within the Ingress object where such rules can be added (for instance within .spec.rules.http.paths or perhaps through some kind of annotation)?

**Comment by nikhiljha** [comment]
In addition to making this configurable, we might want to have

```
      upgrade_configs:
      - upgrade_type: websocket
```

be the default for Ingresses. No other popular ingress controller (AFAICT?) blocks websockets by default, so this breaks software that assumes it'll work out of the box.

**Comment by sayboras** [comment]
:wave: sorry for late reply.

Adding annotation seems to be a reasonable choice to me. PR is welcome, and feel free to reach out if you need any help to get started.

**Comment by nikhiljha** [comment]
I can make a PR, but how do we want this to be designed? I think we want arbitrary overrides for the EnvoyConfig from the Ingress, so something like `io.cilium.envoy_config/path.to.config.opt.to.override=value` is my initial thought but that doesn't seem clean.

**Comment by sayboras** [comment]
As per envoy [doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-upgradeconfig-upgrade-type), there is no much we can configure with upgrade_configs (complex struct such as filter should not be configured here). Hence, I am thinking about below simple annotation.

Existing ingress annotation can be found in [here](https://github.com/cilium/cilium/blob/master/operator/pkg/ingress/annotations/annotations.go)

```
io.cilium/websocket: enabled|disabled
```

**Comment by Yoshino-s** [comment]
Hey, I hava a almost same issue here. In my case here I need add a new upgradeType to support [headscale deployment](https://github.com/juanfont/headscale/blob/main/docs/reverse-proxy.md).
So I need to add config liki
```
upgradeConfigs:
- upgradeType: tailscale-control-protocol
```

This cannot be realized by add annotations. Is there any solution?
