### ISSUE TITLE
bugtool: Flag to avoid including object files for each endpoint

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#20450]
Our sysdumps are starting to be pretty big even for small clusters (e.g., >25MB for 2 nodes in CI). That can be annoying because it limits options to upload sysdumps (e.g., GitHub has a 25MB limit).

In those sysdumps, we keep two object files (`template.o` & `bpf_lxc.o`) per endpoint, in the per-node bugtool reports. They account for a large part of the final compressed sysdump because they are also harder to compress than text files.

We could thus remove object files from the sysdump by default. We would still have template object files in the `state/template/` directories. To that end, we would need a new bugtool flag (e.g., `--exclude-object-files`) and we would then use it by default in the `cilium sysdump` CLI. This issue is for the bugtool flag only as it resides in this repository.

**Comment by NikhilSharmaWe** [comment]
@pchaigno I would like to work on this new flag for removing object files from the `sysdump` by default. 
Actually, I am new to the code base
so, could you please provide some idea or code pointers for adding this feature.

**Comment by pchaigno** [comment]
I measured the impact of this change on a small toy cluster of 2 to 20 nodes recently. There were around 17-18 pods per node, not much traffic going on.

![image](https://user-images.githubusercontent.com/1764210/222226416-513d3450-d5d1-49f4-aecc-e33e24a5be1c.png)

We can also already notice the results in sysdumps coming from CI, which we can now attach to GitHub issues (limited to 25MB).

Thanks a lot @tbalthazar! This was very useful!

**Comment by tbalthazar** [comment]
Glad it's useful, thanks for the support while working on the issue @pchaigno !
