### ISSUE TITLE
bpf xdf not works through docker bridge

### ISSUE THREAD

**Issue by huchen2021** [cilium/cilium#20454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Does bpf_redirect work in docker?
I have 3 dockers, client, elb and e2e-cluster-control-plane.

- In docker elb , it has 2 nics, eth0 and eth1.
- In docker e2e-cluster-control-plane, it has 1 nic, eth0
- In docker client, it has 1 nic, eth0.

I have two docker networks, innet and kind,  as followed:

- eth0 of client and eth1 of elb is on network innet.
- eth0 of e2e-cluster-control-plane and eth0 of elb is on network kind.

I write a xdp program which is not works, any hints?

- Attach xdp program to eth0 and eth1 of elb.
- eth0 of client send package to eth1 of elb. OK.
- eth1 of elb receive the package from eth0 of client.  OK.
- elb modify the package, change the source ip, source port and source mac to eth0 of elb info. OK.
- elb modify the package, change the dest ip, dest port and dest mac to eth0 of e2e-cluster-control-plane info. OK.
- elb send the package by bpf_redirect(eth0 of elb), it return 4 which is XDP_REDIRECT, Not sure if it is OK. Maybe this is not send  successfully even bpf_redirect return good?
-  e2e-cluster-control-plane didn’t receive any package. Not OK. No seen any package loss by tcpdump.
 I try to curl from eth0 of elb to eth0 of e2e-cluster-control-plane, and it is ok.

I don’t know why bpf_redirect didn’t send package successfully from  eth0 of elb to eth0 of e2e-cluster-control-plane?
Any one has any hints?

### Cilium Version

none

### Kernel Version

5.16.0-051600-generic

### Kubernetes Version

kindest/node:v1.21.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
Please see https://github.com/cilium/cilium/blob/master/test/l4lb/test.sh#L14. Closing this issue, as it's not related to Cilium.
