### ISSUE TITLE
CFP: Add a value for overriding the namespace in the helm chart.

### ISSUE THREAD

**Issue by alphabet5** [cilium/cilium#20511]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

Adding cilium to an umbrella helm chart but installing to a different namespace isn't currently possible.

**Describe the feature you'd like**

Adding `namespaceOverride: ""` to values.yaml (similar to how bitnami makes their helm charts) or how cert-manager adds the 'namespace' value.

bitnami example:
```
## @param namespaceOverride String to fully override common.names.namespace
##
namespaceOverride: ""
```

cert-manager example: 
```
# This namespace allows you to define where the services will be installed into
# if not set then they will use the namespace of the release
# This is helpful when installing cert manager as a chart dependency (sub chart)
namespace: ""
```

**(Optional) Describe your proposed solution**

I think either the way bitnami or cert-manager handles it works well and could be useful.

**Comment by sayboras** [comment]
thanks, this seems reasonable to me :100:

**Comment by sayboras** [comment]
@basit9958 Assigned issue to you, feel free to reach out in #development Cilium slack channel.

**Comment by cyclinder** [comment]
Can I working on this? I see https://github.com/cilium/cilium/pull/20828 has not seen any activity.

**Comment by pr0PM** [comment]
Hi created a PR for a fixing this, can someone please review, was unable to use the @cilium/helm to tag codeowners.

**Comment by pentago** [comment]
ANy progress on this one? I hate deploying stuff to kube-system..

**Comment by lucasfcnunes** [comment]
> Any progress on this one? I hate deploying stuff to kube-system...

@pentago Same here!
