### ISSUE TITLE
CFP: automatically add healthCheckNodePort to CiliumClusterwideNetworkPolicies

### ISSUE THREAD

**Issue by zuzzas** [cilium/cilium#20525]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

Cilium provides no way to allow traffic to healthCheckNodePorts, which is generated uniquely for` type: LoadBalancer` services. This forces us into the situation of providing these ports manually and manually adding them into CiliumClusterwideNetworkPolicies.

**Describe the feature you'd like**

An option to automatically allow access to healthCheckNodePorts.

We can allow all nodePorts from a hypothetical range of IPs that belong to health checking CIDRs in a cloud, but, unfortunately, Cilium does not support port ranges.

**Comment by aanm** [comment]
@zuzzas if port ranges would be supported, would that be considered a good alternative?

**Comment by zuzzas** [comment]
Yeah, most certainly.

**Comment by aanm** [comment]
@zuzzas port range are being introduced [here](https://github.com/cilium/cilium/pull/20633) feel free to test it out and leave early feedback if you would like.
