### ISSUE TITLE
eni: infinite trigger resync node when eni count of node is reached eni limits 

### ISSUE THREAD

**Issue by wu0407** [cilium/cilium#20535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. If node need more ip to allocation but no eni is available, it need create more eni.
2. But the count of eni in instance is reached eni limits, so  `n.ops.CreateInterface`  and `n.createInterface(ctx, a.allocation)` alway return error and  https://github.com/cilium/cilium/blob/2cacf2bc62faed23c2137382d720a8314c8f1108/pkg/ipam/node.go#L485-L498 https://github.com/cilium/cilium/blob/2cacf2bc62faed23c2137382d720a8314c8f1108/pkg/ipam/node.go#L813-L840 
3. `maintainIPPool` return error and alway trigger resync node
https://github.com/cilium/cilium/blob/2cacf2bc62faed23c2137382d720a8314c8f1108/pkg/ipam/node.go#L845-L867
https://github.com/cilium/cilium/blob/2cacf2bc62faed23c2137382d720a8314c8f1108/pkg/ipam/node.go#L893-L921

### Cilium Version

master  2cacf2bc62faed23c2 [](https://github.com/cilium/cilium/tree/2cacf2bc62faed23c2137382d720a8314c8f1108)

### Kernel Version

no

### Kubernetes Version

no

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wu0407** [comment]
I think to fix like this in `handleIPAllocation`, `nodehandler` add a method `IsReachENILimits()` to test whether reach the limit.
If reach the limit, not to create eni  `return false, nil`. 
 ``` go
 func (n *Node) handleIPAllocation(ctx context.Context, a *maintenanceAction) (instanceMutated bool, err error) { 
 	scopedLog := n.logger() 
 	if a.allocation == nil { 
 		scopedLog.Debug("No allocation action required") 
 		return false, nil 
 	} 
  
 	// Assign needed addresses 
 	if a.allocation.AvailableForAllocation > 0 { 
 		a.allocation.AvailableForAllocation = math.IntMin(a.allocation.AvailableForAllocation, a.allocation.MaxIPsToAllocate) 
  
 		err := n.ops.AllocateIPs(ctx, a.allocation) 
 		if err == nil { 
 			n.manager.metricsAPI.IncAllocationAttempt("success", string(a.allocation.PoolID)) 
 			n.manager.metricsAPI.AddIPAllocation(string(a.allocation.PoolID), int64(a.allocation.AvailableForAllocation)) 
 			return true, nil 
 		} 
  
 		n.manager.metricsAPI.IncAllocationAttempt("ip assignment failed", string(a.allocation.PoolID)) 
 		scopedLog.WithFields(logrus.Fields{ 
 			"selectedInterface": a.allocation.InterfaceID, 
 			"ipsToAllocate":     a.allocation.AvailableForAllocation, 
 		}).WithError(err).Warning("Unable to assign additional IPs to interface, will create new interface") 
 	} 
  
 	if !n.nodehandler.IsReachENILimits() {
		err = n.createInterface(ctx, a.allocation)
		return err == nil, err
	}
	return false, nil
 } 
```

**Comment by gandro** [comment]
Generally speaking, we already in-cooperate the limits here:
https://github.com/cilium/cilium/blob/24a7e412b1196e829d76c22ad44613d56937d58b/pkg/aws/eni/node.go#L259

And the code _should_ bail out here:
https://github.com/cilium/cilium/blob/eac0dee9d6110d340ea7df6885486b4327052d2f/pkg/ipam/node.go#L472-L484

So it would be interesting to know under what circumstances the `AvailableInterfaces` field is not set up correctly.

**Comment by wu0407** [comment]
Sorry, I misunderstand. that is not consider that condition. https://github.com/cilium/cilium/blob/24a7e412b1196e829d76c22ad44613d56937d58b/pkg/aws/eni/node.go#L259


> Generally speaking, we already in-cooperate the limits here:
> 
> https://github.com/cilium/cilium/blob/24a7e412b1196e829d76c22ad44613d56937d58b/pkg/aws/eni/node.go#L259
> 
> And the code _should_ bail out here:
> 
> https://github.com/cilium/cilium/blob/eac0dee9d6110d340ea7df6885486b4327052d2f/pkg/ipam/node.go#L472-L484
> 
> So it would be interesting to know under what circumstances the `AvailableInterfaces` field is not set up correctly.

**Comment by gandro** [comment]
@wu0407 Great! Just to double check, did you encounter any issues? We did have bugs in the past where the limit wasn't properly respected and we did enter a faulty resync loop. If that happened to you, it would be useful to understand why, as there might be an undiscovered bug.
