### ISSUE TITLE
CFP: problem with helm reference page

### ISSUE THREAD

**Issue by intel-dlanders** [cilium/cilium#20530]
Not sure if this is the correct way to go about it, but I didn't want to wade through a "Bug Report". :\

The Helm reference page, https://docs.cilium.io/en/stable/helm-reference/, has a problem with the formatting such that the entry for 
ipv4NativeRoutingCIDR is partially missing. That is the option 'ipv4NativeRoutingCIDR' is not displayed but the explanation appears to be displayed under the 'monitor' option (and I see now that the option is appended to the explanation):
![image](https://user-images.githubusercontent.com/88565969/179022847-6b26f766-0245-47ae-9e3c-61f1f1634c92.png)

**Comment by sayboras** [comment]
Thanks for reporting this, there was an issue with helm-docs, which is fixe as part of https://github.com/norwoodj/helm-docs/pull/99.

The latest branch in cilium seems ok now, probably we need to backport related fix in cilium to 1.11 branch.

**Comment by Akshit42-hue** [comment]
Hey @sayboras, Can I work on it

**Comment by sayboras** [comment]
sure, I just assigned this issue to you, please feel free to reach out to #development slack channel if you need any help or have any question.

**Comment by sayboras** [comment]
oh sorry, actually, this might be already fixed after 1.12 release. 

https://docs.cilium.io/en/stable/helm-reference/

**Comment by intel-dlanders** [comment]
Doesn't look fixed to me.:
1. ipv4NativeRoutingCIDR is now totally missing from stable. Was the option removed?
2. v1.11 still shows ipv4NativeRoutingCIDR crammed into the explanation of 'monitor'.

**Comment by sayboras** [comment]
> ipv4NativeRoutingCIDR is now totally missing from stable. Was the option removed?

If the option is commented in values.yaml, I don't think we document it due to the logic of [helm-docs](https://github.com/norwoodj/helm-docs)

> v1.11 still shows ipv4NativeRoutingCIDR crammed into the explanation of 'monitor'.
The related changes were not back-ported to v1.11 branch, it's hard to back-port all fixes to older branch except application bug fix or security fix.
