### ISSUE TITLE
ClusterMesh - TCP not working between clusters endpoints

### ISSUE THREAD

**Issue by joaoubaldo** [cilium/cilium#20547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I’ve been trying to get cluster-mesh to work between 2 clusters running the exact same configuration (Kubernetes 1.22 and Cilium 1.11.6). I am using [this demo](https://docs.cilium.io/en/v1.11/gettingstarted/clustermesh/services/) deployment to test connectivity and another minimal service.
My issue so far is that any HTTP request that gets load balanced to a remote endpoint fails ([step 3](https://docs.cilium.io/en/v1.11/gettingstarted/clustermesh/services/#deploying-a-simple-example-service)).

Output from `cilium status` , `cilium clustermesh status` and `cilium-health status` show no issues (see relevant logs)
Things I’ve tried:
- check for any dropped traffic (eg. on hubble this traffic is marked as being forwarded)
- disable policies completely
- look for any unmanaged pods - none
- check state propagation — looks ok: one service identity per cluster (2 total), cilium node list show local and remote notes
- ensure all ports (health, etcd, vxlan) are allowed at the host level — all ok
- run `cilium monitor` on both sides filtering by corresponding endpoint id — on the source agent I see SYNs being sent when I do a request however nothing is captured at the destination
- ping is working between local-remote endpoints
- checked logs for errors - none

Further notes:
- `cilium bpf tunnel list` isn’t giving any output (rc=1) — no errors in logs
- there’s no interface named `cilium_vxlan`

Any guidance on how to further troubleshoot this would be very helpful. 
Happy to share more details if needed.

### Cilium Version

Client: 1.11.6 fee2d77 2022-06-13T16:02:58-07:00 go version go1.17.11 linux/amd64
Daemon: 1.11.6 fee2d77 2022-06-13T16:02:58-07:00 go version go1.17.11 linux/amd64

### Kernel Version

5.4.196-108.356.amzn2.x86_64 #1 SMP Thu May 26 12:49:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20220715-174336.tar.gz](https://github.com/cilium/cilium/files/9123057/cilium-sysdump-20220715-174336.tar.gz)

### Relevant log output

```shell
cilium status:
:                Ok   Disabled
Kubernetes:             Ok   1.22+ (v1.22.10-eks-84b4fe6) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled
Host firewall:          Disabled
Cilium:                 Ok   1.11.6 (v1.11.6-fee2d77)
NodeMonitor:            Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 6/26 allocated,
ClusterMesh:            1/1 clusters ready, 28 global-services
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      41/41 healthy
Proxy Status:           OK, ip 10.210.179.133, 0 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 20.36   Metrics: Ok
Encryption:             Disabled
Cluster health:         8/8 reachable   (2022-07-15T16:47:27Z)

cilium clustermesh status -n cilium-system:
```
Hostname based ingress detected, trying to resolve it
Hostname resolved, using the found ip(s)
✅ Cluster access information is available:
  - 34.254.37.17:2379
  - 52.19.0.110:2379
  - 54.155.201.140:2379
✅ Service "clustermesh-apiserver" of type "LoadBalancer" found
✅ All 4 nodes are connected to all clusters [min:1 / avg:1.0 / max:1]
🔌 Cluster Connections:
- powerful-malamute: 4/4 configured, 4/4 connected
🔀 Global services: [ min:28 / avg:28.0 / max:28 ]```

cilium-health status:
```
Probe time:   2022-07-15T16:49:27Z
Nodes:
  feasible-reindeer/ip-10-210-168-217.eu-west-1.compute.internal (localhost):
    Host connectivity to 10.210.168.217:
      ICMP to stack:   OK, RTT=506.268µs
      HTTP to agent:   OK, RTT=230.249µs
    Endpoint connectivity to 10.210.175.14:
      ICMP to stack:   OK, RTT=491.167µs
      HTTP to agent:   OK, RTT=282.723µs
  feasible-reindeer/ip-10-210-142-228.eu-west-1.compute.internal:
    Host connectivity to 10.210.142.228:
      ICMP to stack:   OK, RTT=503.232µs
      HTTP to agent:   OK, RTT=419.027µs
    Endpoint connectivity to 10.210.143.200:
      ICMP to stack:   OK, RTT=616.602µs
      HTTP to agent:   OK, RTT=493.258µs
  feasible-reindeer/ip-10-210-153-113.eu-west-1.compute.internal:
    Host connectivity to 10.210.153.113:
      ICMP to stack:   OK, RTT=800.895µs
      HTTP to agent:   OK, RTT=470.005µs
    Endpoint connectivity to 10.210.132.125:
      ICMP to stack:   OK, RTT=665.453µs
      HTTP to agent:   OK, RTT=502.812µs
  feasible-reindeer/ip-10-210-99-158.eu-west-1.compute.internal:
    Host connectivity to 10.210.99.158:
      ICMP to stack:   OK, RTT=559.869µs
      HTTP to agent:   OK, RTT=484.191µs
    Endpoint connectivity to 10.210.98.214:
      ICMP to stack:   OK, RTT=641.194µs
      HTTP to agent:   OK, RTT=608.315µs
  powerful-malamute/ip-10-210-106-251.eu-west-1.compute.internal:
    Host connectivity to 10.210.106.251:
      ICMP to stack:   OK, RTT=640.522µs
      HTTP to agent:   OK, RTT=606.03µs
    Endpoint connectivity to 10.210.126.15:
      ICMP to stack:   OK, RTT=574.266µs
      HTTP to agent:   OK, RTT=556.792µs
  powerful-malamute/ip-10-210-137-106.eu-west-1.compute.internal:
    Host connectivity to 10.210.137.106:
      ICMP to stack:   OK, RTT=573.258µs
      HTTP to agent:   OK, RTT=469.355µs
    Endpoint connectivity to 10.210.131.244:
      ICMP to stack:   OK, RTT=860.132µs
      HTTP to agent:   OK, RTT=486.204µs
  powerful-malamute/ip-10-210-138-123.eu-west-1.compute.internal:
    Host connectivity to 10.210.138.123:
      ICMP to stack:   OK, RTT=540.466µs
      HTTP to agent:   OK, RTT=455.779µs
    Endpoint connectivity to 10.210.158.26:
      ICMP to stack:   OK, RTT=883.573µs
      HTTP to agent:   OK, RTT=587.481µs
  powerful-malamute/ip-10-210-191-112.eu-west-1.compute.internal:
    Host connectivity to 10.210.191.112:
      ICMP to stack:   OK, RTT=505.418µs
      HTTP to agent:   OK, RTT=241.755µs
    Endpoint connectivity to 10.210.169.17:
      ICMP to stack:   OK, RTT=520.655µs
      HTTP to agent:   OK, RTT=311.012µs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Thanks.

While the issue is closed, do you think any docs improvement required  ?

https://docs.cilium.io/en/latest/gettingstarted/clustermesh/clustermesh/#cluster-addressing-requirements

**Comment by joaoubaldo** [comment]
@sayboras docs are fine as they mention network requirements between nodes when tunneling is disabled.

**Comment by sayboras** [comment]
thanks it's good to hear that :medal_military:

**Comment by Paulius0112** [comment]
Hi. Could you maybe provide details of configuration you needed to change? Also, the documentation link you provided https://docs.cilium.io/en/latest/gettingstarted/clustermesh/clustermesh/#cluster-addressing-requirements no longer exists
