### ISSUE TITLE
ENI mode attaches secondary ENIs in dubious subnets by default

### ISSUE THREAD

**Issue by benesch** [cilium/cilium#20553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Cilium AWS ENI IPAM mode will, by default, attach ENIs in the least full subnet whose VPC/AZ matches the subnet of the VPC/AZ of the primary ENI. When running in an EKS cluster with both public and private subnets, this means that Cilium is quite likely to attach an ENI in the "wrong" subnet: i.e., an ENI in a public subnet on a private node, or an ENI in a private subnet on a public node. This causes all sorts of surprising connectivity issues for the pods when a node gets full enough that pods start getting attached to the secondary ENI.

There are several other folks on the community Slack who have run into this:

 * https://cilium.slack.com/archives/C53TG4J4R/p1654800394686379
 * https://cilium.slack.com/archives/C1MATJ5U5/p1652110014858529

Using the `subnet-ids` or `subnet-filters` configuration options is not a workaround, AFAICT, because there is no set of subnets that is valid for _all_ nodes. We need the public nodes to consider only the public subnets and the private nodes to consider only the private subnets.

### Cilium Version

v11.4

### Kernel Version

Linux ip-10-2-68-192.ec2.internal 5.4.190-107.353.amzn2.x86_64 #1 SMP Wed Apr 27 21:16:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.22.10-eks-84b4fe6

### Anything else?

I hacked up a version of Cilium to unconditionally have the desired behavior: https://github.com/MaterializeInc/cilium/commit/49ca0ca4fe129dbda4861eb82879e1d93909a1c4. The patch is quite simple and has the desired effect:

```diff
diff --git a/pkg/aws/metadata/metadata.go b/pkg/aws/metadata/metadata.go
index e109b62478e..ea119b54111 100644
--- a/pkg/aws/metadata/metadata.go
+++ b/pkg/aws/metadata/metadata.go
@@ -39,7 +39,7 @@ func getMetadata(client *imds.Client, path string) (string, error) {
 }
 
 // GetInstanceMetadata returns required AWS metadatas
-func GetInstanceMetadata() (instanceID, instanceType, availabilityZone, vpcID string, err error) {
+func GetInstanceMetadata() (instanceID, instanceType, availabilityZone, vpcID, subnetID string, err error) {
 	client, err := newClient()
 	if err != nil {
 		return
@@ -64,6 +64,11 @@ func GetInstanceMetadata() (instanceID, instanceType, availabilityZone, vpcID st
 	if err != nil {
 		return
 	}
+	subnetIDPath := fmt.Sprintf("network/interfaces/macs/%s/subnet-id", eth0MAC)
+	subnetID, err = getMetadata(client, subnetIDPath)
+	if err != nil {
+		return
+	}
 
 	availabilityZone, err = getMetadata(client, "placement/availability-zone")
 	if err != nil {
diff --git a/pkg/nodediscovery/nodediscovery.go b/pkg/nodediscovery/nodediscovery.go
index b59d2087381..09194ac79a9 100644
--- a/pkg/nodediscovery/nodediscovery.go
+++ b/pkg/nodediscovery/nodediscovery.go
@@ -461,7 +461,7 @@ func (n *NodeDiscovery) mutateNodeResource(nodeResource *ciliumv2.CiliumNode) er
 	case ipamOption.IPAMENI:
 		// set ENI field in the node only when the ENI ipam is specified
 		nodeResource.Spec.ENI = eniTypes.ENISpec{}
-		instanceID, instanceType, availabilityZone, vpcID, err := metadata.GetInstanceMetadata()
+		instanceID, instanceType, availabilityZone, vpcID, subnetID, err := metadata.GetInstanceMetadata()
 		if err != nil {
 			log.WithError(err).Fatal("Unable to retrieve InstanceID of own EC2 instance")
 		}
@@ -479,6 +479,7 @@ func (n *NodeDiscovery) mutateNodeResource(nodeResource *ciliumv2.CiliumNode) er
 		// determine the appropriate value to place inside the resource.
 		nodeResource.Spec.ENI.VpcID = vpcID
 		nodeResource.Spec.ENI.FirstInterfaceIndex = getInt(defaults.ENIFirstInterfaceIndex)
+		nodeResource.Spec.ENI.SubnetIDs = []string{subnetID}
 
 		if c := n.NetConf; c != nil {
 			if c.IPAM.MinAllocate != 0 {
```

I imagine to submit this as a PR we'd need to make this behavior toggleable with an option like `constrain-to-primary-eni-subnets: {true,false}`—plus tests. I'm afraid I won't have the time to do that, but hopefully someone else can run with this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wu0407** [comment]
I think need new crd ip pool, that controll which subnet is used.

**Comment by gandro** [comment]
I agree that we can make the selection a bit smarter and picking the same subnet as the primary ENI is probably a good choice as well.

But I don't think I understand why using a filter in `spec.eni.subnet-tags` is not a feasible here. You can tag all the relevant subnets, and you can also define the tag filter per node if you use a node-specific CNI configuration:
https://docs.cilium.io/en/v1.11/concepts/networking/ipam/eni/#eni-creation

**Comment by gandro** [comment]
> What do folks running on AWS normally do to customize the CNI per node? Run another DaemonSet that installs the config? Bake a custom AMI per node group?

Besides the globally shared CNIconfig (which can be deployed via Helm), users who are using a custom CNI config per node group seem to relying on cloud-init or the `overrideBootstrapCommand` in eksctl.

But yes, I agree that it is a bit fiddly. 

I would not want Cilium the actually set the `nodeResource.Spec.ENI.SubnetIDs` based on the auto-detection (since this will prevent the operator from picking different subnets if the initial one runs out of IPs), but having a mechanism which makes the operator prefer the primany ENI's subnet if nothing else is specified does sound like very reasonable behavior to me.

**Comment by benesch** [comment]
Not stale. Can we disable the stale bot on this issue?
