### ISSUE TITLE
test: Missing section names in the test/bpf/check-complexity.sh output

### ISSUE THREAD

**Issue by brb** [cilium/cilium#20557]
When running the following, the output doesn't contain the tail call names:
```
docker run --name foobar --rm -ti --privileged -v $PWD:/cilium quay.io/cilium/cilium-ci:latest /bin/bash
mount -t bpf bpf /sys/fs/bpf
cd /cilium
make -C bpf/ KERNEL=netnext
./test/bpf/check-complexity.sh
```

The naming is done by the `annotate_section_names()` function in `check-complexity.sh`.

Previously, it was working before switching our [iproute2](https://github.com/cilium/iproute2) fork's backend to `libbpf`.

This issue is about figuring out how to get section identifiers from the BPF verifier log. If it's not possible, then adding the section identities to the output of `iproute2` loader and `cilium/ebpf` (once https://github.com/cilium/cilium/pull/19159 has been merged, it will be used to Cilium's BPF load programs; /cc @ti-mo ).

**Comment by ti-mo** [comment]
Thanks for the issue! Is this worth the effort in the short term? The plan is to replace `verifier-test.sh` with a Go progam in the near future, which will also make X/Y section names unnecessary. This new tool should give all the error output needed to properly debug verifier errors.

Currently, the lib can also dump insns with lineinfo annotations directly from ELF BTF, which no existing userspace tool supports at the moment. (only the verifier)

Will assign and send an update here when it's done.

**Comment by ti-mo** [comment]
This is no longer an issue.
