### ISSUE TITLE
ENI: Optimize Eni update latency after new eni created 

### ISSUE THREAD

**Issue by wu0407** [cilium/cilium#20595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When successfully call createInterface not triggered n.manager.resyncTrigger. It cause spec.ipam.pool update delay, so agent not able allocate ip for new pod until periodic trigger NodeManager.Resync. It mean the max duration from create interface to update cliumNode for this node need 1 min.

The relate code: https://github.com/cilium/cilium/blob/2cacf2bc62faed23c2137382d720a8314c8f1108/pkg/ipam/node.go#L836-L840

the relate pull request https://github.com/cilium/cilium/pull/17939/files/bcdb763ca31cd05107236c73886b621058eeac0c#diff-01e105c00ecf377284f9b2f24279d5ac0ff6c96a8bc076265905ab3e982ff384R727-R728

### Cilium Version

master https://github.com/cilium/cilium/commit/2cacf2bc62faed23c2137382d720a8314c8f1108

### Kernel Version

none

### Kubernetes Version

none

### Anything else?

I think `createInterface` return two value
``` go
func (n *Node) handleIPAllocation(ctx context.Context, a *maintenanceAction) (instanceMutated bool, err error) {
     ....
    return n.createInterface(ctx, a.allocation)
}
```
``` go
func (n *Node) createInterface(ctx context.Context, a *AllocationAction) (bool, error) {
	if a.AvailableInterfaces == 0 {
		// This is not a failure scenario, warn once per hour but do
		// not track as interface allocation failure. There is a
		// separate metric to track nodes running at capacity.
		n.mutex.Lock()
		if time.Since(n.lastMaxAdapterWarning) > warningInterval {
			n.loggerLocked().Warning("Instance is out of interfaces")
			n.lastMaxAdapterWarning = time.Now()
		}
		n.mutex.Unlock()
		return false, nil
	}

	scopedLog := n.logger()
	toAllocate, errCondition, err := n.ops.CreateInterface(ctx, a, scopedLog)
	if err != nil {
		scopedLog.Warningf("Unable to create interface on instance: %s", err)
		n.manager.metricsAPI.IncAllocationAttempt(errCondition, string(a.PoolID))
		return false, err
	}

	n.manager.metricsAPI.IncAllocationAttempt("success", string(a.PoolID))
	n.manager.metricsAPI.AddIPAllocation(string(a.PoolID), int64(toAllocate))

	return true,nil
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
I agree with the proposed fix. Would you be willing to submit a PR?

**Comment by wu0407** [comment]
ok, wait my not busy.
