### ISSUE TITLE
CiliumNetworkPolicy ToFQDNs behavior of `*` different from documentation

### ISSUE THREAD

**Issue by rahulkjoshi** [cilium/cilium#20604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I was digging into the API spec for FQDN Egress policies and I saw it mentioned that
> As a special case a “*” as the leftmost character, without a following “.” matches all subdomains as well as the name to the right.

-[reference](https://github.com/cilium/cilium/blob/d4b786137dbc95beb4e2797bf1837a40528af5cb/pkg/policy/api/fqdn.go#L53-L54)

I wasn’t able to get this to work for me in practice. There didn’t seem to be any special behavior, it acted like a standard `*` expansion.

I wrote a rule which allowed traffic to `*google.com`. By the above comment, traffic to `www.google.com` should have been allowed (along with `mail.google.com`). However, none of those queries worked (you can see that the entries are in the per-EP caches, but they aren't in the policy map). Querying `google.com` though does work -- as expected.

Poking naively at [the code](https://github.com/cilium/cilium/blob/d4b786137dbc95beb4e2797bf1837a40528af5cb/pkg/fqdn/matchpattern/matchpattern.go#L60) (I think that’s the right place), doesn’t look like anything special is happening.

Most likely this is out-of-date documentation that should be fixed.

### Cilium Version

1.11.6

### Kernel Version

5.10.123+

### Kubernetes Version

1.24.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wenhuwang** [comment]
you are right, the API spec for FQDN Egress policies code comments really wrong. 
`*google.com` will not match `www.google.com` or `blog.google.com`.

**Comment by wenhuwang** [comment]
assign @wenhuwang

**Comment by wenhuwang** [comment]
assign @wenhuwang
