### ISSUE TITLE
ci-e2e workflow configuration

### ISSUE THREAD

**Issue by brb** [cilium/cilium#20606]
Current configuration table of [ci-e2e](https://github.com/cilium/cilium/blob/master/.github/workflows/conformance-e2e.yaml):

| Name | Kernel | Routing | EP routes | IPv6 | Encryption | kube-proxy | LB mode | MASQ | Egress GW | Host FW |
| - | - | - | - | - | - | - | - | - | - | - |
| 1 | 4.19 | vxlan | - | + | - | iptables | - | iptables | - | - |
| 2 | 5.4 | direct | - | + | - | iptables | - | iptables | - | - |
| 3 | 5.10 | direct | + | + | - | iptables | - | iptables | - | - |
| 4 | 5.10 | vxlan | + | + | - | mixed | SNAT | BPF | + | - |
| 5 | 5.15 | direct | + | + | - | mixed | DSR | BPF | + | + |
| 6 | 6.0 | vxlan | - | + | - | KPR | SNAT | BPF | + | + |
| 7 | bpf-next | direct | - | + | - | KPR | SNAT | BPF | + | - |
| 8 | bpf-next | geneve | + | + | - | iptables | - | iptables | - | - |
| 9 | 4.19 | vxlan | - | + | IPsec | iptables | - | iptables | - | - |
| 10 | 5.4 | direct | - | + | IPsec | iptables | - | iptables | - | - |
| 11 | 5.10 | direct | + | + | IPsec | iptables | - | iptables | - | - |
| 12 | 5.10 | vxlan | + | + | WireGuard | mixed | SNAT | BPF | + | - |
| 13 | 5.15 | direct | + | + | WireGuard | mixed | DSR | BPF | + | - |
| 14 | 6.0 | vxlan | - | + | WireGuard host-to-host | KPR | SNAT | BPF | + | - |
| 15 | bpf-next | direct | - | + | WireGuard host-to-host | KPR | SNAT | BPF | + | - |
| 16 | bpf-next | geneve | + | + | IPsec | iptables | - | iptables | - | - |

**Comment by pchaigno** [comment]
Longer term, we may want to cover IPsec on bpf-next. We don't in any CI job today. We should cover that because we currently rely on an internal characteristic of the kernel's IPsec implementation (that is, `cb[4]` is preserved) and we have no guarantee that it won't change: https://github.com/cilium/cilium/blob/c46eb0bd0590ae9dac3b3f02fc6fc558ec48fa44/bpf/lib/encap.h#L27-L30

**Comment by brb** [comment]
> Longer term, we may want to cover IPsec on bpf-next

What other configurations would be relevant for IPsec + bpf-next?

**Comment by pchaigno** [comment]
> > Longer term, we may want to cover IPsec on bpf-next
> 
> What other configurations would be relevant for IPsec + bpf-next?

Any one of the configurations that use `skb->cb[4]`. Currently that's only IPAM={EKS,Azure,AlibabaCloud}, but with the upcoming IPsec changes, all configurations will use `skb->cb[4]` so testing should become possible on ConformanceDatapath.

**Comment by brb** [comment]
We are no longer updating the issue to reflect the ci-e2e configurations.
