### ISSUE TITLE
Helm chart validation fails

### ISSUE THREAD

**Issue by gsalisbury** [cilium/cilium#20632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Helm chart fails linting.

### Cilium Version

1.12.0

### Kernel Version

NA

### Kubernetes Version

NA

### Sysdump

NA

### Relevant log output

```shell
When running helm lint as part of our release pipeline, it fails with
`Error: parse error at (cilium/templates/validate.yaml:38): unclosed action`
```

### Anything else?

cilium/templates/validate.yaml:
--- snip ---
 37 {{/* validate hubble-ui specific config */}}
 38 {{- if and .Values.hubble.ui.enabled < ------- Missing closing }}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
👋 

Thanks for reporting this issue, can you try with latest helm version ?

**Comment by gsalisbury** [comment]
Hi, apologies, the helm version was the problem as you suggested.

Thanks!

**Comment by sayboras** [comment]
I noticed that older helm versions (<3.6) might have such an issue. Hence, just want to confirm if the latest helm version can help here.

**Comment by gsalisbury** [comment]
Yes you're correct, our pipeline uses an older helm version, running with helm 3.9.1 however, `helm lint` completes successfully.

**Comment by hemslo** [comment]
Multiline support in template is added in go 1.16, [doc](https://go.dev/doc/go1.16). Details in [this commit](https://github.com/golang/go/commit/9384d34c58099657bb1b133beaf3ff37ada9b017)

> Newlines characters are now allowed inside action delimiters, permitting actions to span multiple lines.

Helm updated to go 1.16 after [3.7.0](https://github.com/helm/helm/releases/tag/v3.7.0).

If we want to support older versions of helm, then we need to inline the section:
```
{{- if and .Values.hubble.ui.enabled (ne .Values.hubble.ui.backend.image.tag "latest") (ne .Values.hubble.ui.frontend.image.tag "latest") }}
```

**Comment by sayboras** [comment]
Considering that the latest helm version (e.g. 3.9.2) is compiled with go 1.17.x, and go 1.16 is EOL now, I don't think it's worth spending time to support older helm version such as 3.6.x (compiled with go 1.15.x).
