### ISSUE TITLE
Cilium 1.12.0 fails to install on clusters that blocks `SYS_MODULE`

### ISSUE THREAD

**Issue by frezbo** [cilium/cilium#20636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On Kubernetes cluster where containerd is started with `SYS_MODULE` capability dropped, installing Cilium 1.12.0 fails in the `clean-cilium-state` initContainer since it explicitly requests `SYS_MODULE` capability. Modifying the helm chart to set `securityContext.privileged: true` fixes this issue, since the container then only inherits only the capabilities available to the containerd process (which doesn't explicitly try to use `SYS_MODULE`). 

Since setting `securityContext.privileged: true` makes the cilium install works and looking at the [comments](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L603=) in the helm chart, it seems the `SYS_MODULE` capability is only needed in some specific operation mode of cilium (I guess something that would involve iptables, but I'm not completely sure).

I would like to propose a solution which makes the `SYS_MODULE` capability optional and configurable by the user. This would allow the pods to be run without `securityContext.privileged: true` but still a limited down capability as defined in the `securityContext.capabilities.add`. 

If this idea makes sense I can work on putting up a draft PR

### Cilium Version

1.12.0

### Kernel Version

5.15.54

### Kubernetes Version

1.24.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hello @frezbo,

thank you for opening the GH issue. Unfortunately, the `SYS_MODULE` is indeed required to install some iptables rules which affects Cilium operations so we can't make it optional.

**Comment by frezbo** [comment]
Isn't that the case only when the `iptables` module is not loaded? From my testing it was not using that capability when ran as privileged pod and when the containerd was started with the `SYS_MODULE` capability dropped.

**Comment by frezbo** [comment]
> Isn't that the case only when the `iptables` module is not loaded? From my testing it was not using that capability when ran as privileged pod and when the containerd was started with the `SYS_MODULE` capability dropped.

Probably that was confusing, in the test scenario, the `iptables` modules was already loaded, so cilium had no need to load it

**Comment by aanm** [comment]
@frezbo you are right, it might have been an oversight from our side. Consider submitting a PR removing it from everything. If the CI doesn't complain I don't see why we can't merge it. Thank you

**Comment by aanm** [comment]
@frezbo I've brought this up in this week's developer meeting. It looks that `SYS_MODULE` is indeed used when iptables is executed which can load some modules automatically.

**Comment by frezbo** [comment]
> @frezbo I've brought this up in this week's developer meeting. It looks that `SYS_MODULE` is indeed used when iptables is executed which can load some modules automatically.

It probably explains why it worked in Talos when ran with privileged mode even though `SYS_MODULE` was already dropped (there are no user loadable modules and all modules are already built in to kernel). I'm not sure what would be the right approach here. I can do a PR that by default still allows `SYS_MODULE` and have an option to optionally disable them.

**Comment by frezbo** [comment]
I believe it works since all the modules are already loaded (the kernel is compiled with all modules in-tree and not as a module)

**Comment by aanm** [comment]
@frezbo ofc in that case that makes more sense then. Could you submit a PR and describe all of this information in the commit message? Thank you!

**Comment by jonkerj** [comment]
I'm working on a PR to fix this specific issue

**Comment by frezbo** [comment]
> I'm working on a PR to fix this specific issue

cool, thanks, I didn't get around to fixing it :sweat_smile:

**Comment by sayboras** [comment]
Thanks both.

I have assigned the issue to you @jonkerj. Feel free to shout out in #development channel if you need any help.
