### ISSUE TITLE
cilium agent initcontainers unexpected restart

### ISSUE THREAD

**Issue by yanhongchang** [cilium/cilium#20644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In my k8s（1.20.8） environment， I found the cilium-agent's two init containers（k8s_clean-cilium-state，k8s_mount-cgroup） expected restart，and those pods running in this node will be Error，describe those error pods，will see some failed message such as “mysql or redis connection timeout”。
by the way，this phenomenon usually occurs at the cronjob nodes。

this is unexpected restart:

```
016372a6b75b   f41c862f6e85                                                                "/init-container.sh"     5 days ago    Exited (0) 5 days ago               k8s_clean-cilium-state_cilium-4zz45_kube-system_d7be1d7b-6fac-42e4-9ee2-070a6f99197c_0
8235456666ff   f41c862f6e85                                                                "sh -c 'cp /usr/bin/…"   5 days ago    Exited (0) 5 days ago               k8s_mount-cgroup_cilium-4zz45_kube-system_d7be1d7b-6fac-42e4-9ee2-070a6f99197c_0
e6f8f0839e4b   f41c862f6e85                                                                "cilium-agent --conf…"   13 days ago   Up 13 days                          k8s_cilium-agent_cilium-4zz45_kube-system_d7be1d7b-6fac-42e4-9ee2-070a6f99197c_1
13b57b22ac4b   registry.aliyuncs.com/google_containers/pause:3.2                           "/pause"                 13 days ago   Up 13 days                          k8s_POD_cilium-4zz45_kube-system_d7be1d7b-6fac-42e4-9ee2-070a6f99197c_1
```

the init containers was 5days ago，but the cilium agent up at 13days ago. so I think those init containers was unexpected restart or unexpected  started.

this is normal node :

```
563f83138ea6   f41c862f6e85                                                                   "cilium-agent --conf…"   3 weeks ago              Up 3 weeks                                    k8s_cilium-agent_cilium-t527p_kube-system_90902643-b6ca-4b61-8f23-eac3a9e10465_0
e63f612f938a   f41c862f6e85                                                                   "/init-container.sh"     3 weeks ago              Exited (0) 3 weeks ago                        k8s_clean-cilium-state_cilium-t527p_kube-system_90902643-b6ca-4b61-8f23-eac3a9e10465_0
581ac030bfdd   quay.io/cilium/cilium                                                          "sh -c 'cp /usr/bin/…"   3 weeks ago              Exited (0) 3 weeks ago                        k8s_mount-cgroup_cilium-t527p_kube-system_90902643-b6ca-4b61-8f23-eac3a9e10465_0
1cc3ba31f8e2   registry.aliyuncs.com/google_containers/pause:3.2                              "/pause"                 3 weeks ago              Up 3 weeks                                    k8s_POD_cilium-t527p_kube-system_90902643-b6ca-4b61-8f23-eac3a9e10465_0
```

### Cilium Version

1.10.4

### Kernel Version

5.10.23-4

### Kubernetes Version

1.20.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wu0407** [comment]
You has any docker clean image or container? 
https://github.com/istio/istio/issues/19717

**Comment by aanm** [comment]
@yanhongchang that's the expected behavior as the init containers exited with the error code zero.

**Comment by yanhongchang** [comment]
> 

@wu0407 Thanks a  lot！I have not clean image or containers , but maybe the kubelet or docker will clean those resource，I will try to reproduce this problem by this way，thank you for your guidance～

**Comment by yanhongchang** [comment]
> @yanhongchang that's the expected behavior as the init containers exited with the error code zero.

@aanm Thanks for you attention！I found the start-up time of init containers and cilium-agent is inconsistent，and on normal nodes, the start-up of init containers and cilium agent is consistent, So I infer that this init containers was started again。this is unexpected behavior.

**Comment by aanm** [comment]
@yanhongchang could you check for the kubelet logs to see if there is any relevant information that describes when an initContainer took so much time?

**Comment by yanhongchang** [comment]
@all The problem I reported is not a problem for cilium.  the two init containers restart was caused by my operate , I clean all exited containers and the cilium init-containers will recreate again after the  clean action. so I close the issues, thinks all again!
