### ISSUE TITLE
CFP: Cilium BGP control Plane support inter nodes BGP

### ISSUE THREAD

**Issue by abasitt** [cilium/cilium#20653]
## Cilium Feature Proposal
        
The current implementation of BGP control plane only support peering with external TOR. We want to have BGP feature that can do peering between cilium nodes, without any dependencies on the TOR.
Currently the inter-node traffic is routed using overlays e.g. vxlan which adds additional overhead. In some-cases vxlan may have limited support e.g. as of today Cilium doesn't support vxlan tunneling for IPv6 single stack cluster.

**Describe the feature you'd like**
If Cilium implement inter-node BGP peering e.g. using iBGP and also support advance feature like Route-reflector, the nodes CIDR can be shared between different nodes. When all the nodes know about the POD-CIDR, native routing can happen between all nodes without using VXLAN tunneling. 
This feature is required in environments where it's not possible to have BGP peering with TOR switch and also either vxlan is not possible or want to avoid vxlan for better performance.
Currently I noticed few things in the existing implementation.
- Cilium virtual router doesn't listen by default on BGP port. this should be enabled and it should listen on default BGP port
- Auto detect nodes for auto-bgp peering, this could be enable e.g. on a default virtual router using specific ASN.
- Cilium agent should be able to create auto router-ids for IPv6 single stack. Please follow the RFC implementation because I faced the issue with Calico. https://github.com/projectcalico/calico/issues/5146

**issue that I am facing**
I have an IPv6 only environment where vxlan is not possible and also we can't do peering with TOR because of the scalability limitation on the TOR RIB/FIB. So as a workaround I am using static routing between different nodes, I am looking in to kube-router to do the same but having this native support in cilium will be absolutely amazing.

**Comment by YutaroHayakawa** [comment]
FYI, if all nodes share a single L2 network, then you can use `auto-direct-node-routes` option to achieve the same thing.

**Comment by abasitt** [comment]
@YutaroHayakawa thank you for sharing this.

**Comment by Duanzhiwei** [comment]
I also want to ask if the Route-reflector  can be supported at present?

**Comment by abasitt** [comment]
@Duanzhiwei AFAIK it is not natively supported in Cilium but can be done with kube-router or BIRD. 
https://docs.cilium.io/en/stable/gettingstarted/kube-router/

**Comment by andersjohansson2021** [comment]
A implementation of this https://github.com/osrg/gobgp/blob/master/docs/sources/route-reflector.md or the like would be nice.

**Comment by jinsiang2008** [comment]
Hi there, just wanna follow up with the status of this function requirement. We are facing the problem for now, so wanna see if there are other walk around. Thanks.

**Comment by yassan** [comment]
Will specifications such as eBGP & BGP Unnumbered & loopback unicast in IP CLOS (Full L3) environments also be considered?

cf. BGP Unnumbered via RFC 5549 + a loopback unicast - Google Slide
https://docs.google.com/presentation/d/12pZUE5bOQBBwsKdTEq2RZC_vRsu-gfyGaIB6LEowQXg/edit#slide=id.g13d84d984ce_0_69

**Comment by YutaroHayakawa** [comment]
@yassan We are considering to implement it, but not decided when. Feel free to make an issue to track it.

**Comment by dylandreimerink** [comment]
Cillium agents already are aware of all routing information there is within the cluster which is all exchanged via the k8s API server and resources, so I am not sure if exchange via BGP would add anything that we otherwise don't have. Also note that we don't add any BGP routes to the hosts routing table, so I think we are really talking about two different features here.

I do however see route exchange being interesting when running cilium without k8s, like in L4LB mode to communicate routing info or as a control plane of some sorts @brb.

**Comment by YutaroHayakawa** [comment]
@abasitt Isn't `auto-direct-node-routes` enough for the inter-node routing use case? For inter-node routing, as Dylan said, we don't need BGP because Cilium agents know the equivalent information through the k8s API server. And what `auto-direct-node-routes` do is insert `<pod cidr> via <remote node ip>` routes to each node. This is exactly the same as what we can do with iBGP full-mesh or RR-based route exchange.

If it is enough for you, we can close this issue. Otherwise, please let us know why it is not enough.

**Comment by YutaroHayakawa** [comment]
@yassan Created an [issue](https://github.com/cilium/cilium/issues/22132) to track BGP Unnumbered. Feel free to add anything missing.

**Comment by abasitt** [comment]
@YutaroHayakawa I can mention few use-cases which comes to the top of my mind right now and I see attraction from others as well around this issue so I would love to hears other cilium users point of view. I agree with a fact auto-direct-node-routes covers most cases but for more advance use-cases, we really need BGP support.

- auto-direct-node-routes are limited to single layer2 domain. We do have cluster nodes that can span multiple subnets and we don't want to be dependent on the TOR for BGP.
- L3 data centers: Some datacenters design only have L2 available at TOR level and in some cases layer2 is only available at port level. This brings the limitations and to scale cluster expanded beyond single TOR is to do peering with NS BGP. There are few problems with it. e.g. if network is managed by third party and POD CIDRs are not allowed may be because it's private ranges. Another bigger problem that I have seen is the scalability in the network FIB, some fabric switches have terrible limits for IPv6 and just won't work if we start peering all the clusters in high scale Telco datacenters.
- Advanced IPAM use-cases: e.g. static POD IP addresses. AFAIK today cilium nodes add CIDR learned from K8s API assigned to per node in a cluster but it can't detect if a POD has a static IP and the moved to the other node and generate /32 or /128 route for that. I know cilium today don't support static IP but such unique cases will be raised by the community in the near future. With BGP we have a lot more flexibility on what to advertise and what not to advertise to the TOR or to other nodes etc.

**Comment by YutaroHayakawa** [comment]
> auto-direct-node-routes are limited to single layer2 domain. We do have cluster nodes that can span multiple subnets and we don't want to be dependent on the TOR for BGP.
>
> L3 data centers: Some datacenters design only have L2 available at TOR level and in some cases layer2 is only available at port level. This brings the limitations and to scale cluster expanded beyond single TOR is to do peering with NS BGP. There are few problems with it. e.g. if network is managed by third party and POD CIDRs are not allowed may be because it's private ranges. Another bigger problem that I have seen is the scalability in the network FIB, some fabric switches have terrible limits for IPv6 and just won't work if we start peering all the clusters in high scale Telco datacenters.

Yeah, the problems you describe make sense to me, but how does this work without L2 connectivity or a tunnel? The routes exchanged with iBGP, in this case, look like `<pod CIDR> via <node ip>` right? In that case, `<node ip>` needs to be reachable with L2 or tunnel (Calico does this IIRC). Am I missing something?

> Advanced IPAM use-cases: e.g. static POD IP addresses. AFAIK today cilium nodes add CIDR learned from K8s API assigned to per node in a cluster but it can't detect if a POD has a static IP and the moved to the other node and generate /32 or /128 route for that. I know cilium today don't support static IP but such unique cases will be raised by the community in the near future. With BGP we have a lot more flexibility on what to advertise and what not to advertise to the TOR or to other nodes etc.

Makes sense as well, but if that static IP address is managed by Cilium, I think it is still possible to extend `auto-direct-node-routes` to populate it and I would do that. If it is not managed by Cilium, Cilium's BGP CPlane also cannot advertise it I think. Any specific preference for using BGP in that case?

**Comment by abasitt** [comment]
> > auto-direct-node-routes are limited to single layer2 domain. We do have cluster nodes that can span multiple subnets and we don't want to be dependent on the TOR for BGP.
> > L3 data centers: Some datacenters design only have L2 available at TOR level and in some cases layer2 is only available at port level. This brings the limitations and to scale cluster expanded beyond single TOR is to do peering with NS BGP. There are few problems with it. e.g. if network is managed by third party and POD CIDRs are not allowed may be because it's private ranges. Another bigger problem that I have seen is the scalability in the network FIB, some fabric switches have terrible limits for IPv6 and just won't work if we start peering all the clusters in high scale Telco datacenters.
> 
> Yeah, the problems you describe make sense to me, but how does this work without L2 connectivity or a tunnel? The routes exchanged with iBGP, in this case, look like `<pod CIDR> via <node ip>` right? In that case, `<node ip>` needs to be reachable with L2 or tunnel (Calico does this IIRC). Am I missing something?
> That's right L2 tunneling is required for cross-subnet nodes, something similar what Cilium also can do for clustermesh. The design should be flexible enough to use no-tunneling for nodes in same subnet and use L2 tunneling for cross-subnet nodes. 
> > Advanced IPAM use-cases: e.g. static POD IP addresses. AFAIK today cilium nodes add CIDR learned from K8s API assigned to per node in a cluster but it can't detect if a POD has a static IP and the moved to the other node and generate /32 or /128 route for that. I know cilium today don't support static IP but such unique cases will be raised by the community in the near future. With BGP we have a lot more flexibility on what to advertise and what not to advertise to the TOR or to other nodes etc.
> 
> Makes sense as well, but if that static IP address is managed by Cilium, I think it is still possible to extend `auto-direct-node-routes` to populate it and I would do that. If it is not managed by Cilium, Cilium's BGP CPlane also cannot advertise it I think. Any specific preference for using BGP in that case?
BGPCplane will advertise any IP that is learned in the linux FIB, isn't it ? So taking the example of static POD, AFAIK when generated specific pod route it will be advertised by Cplane. In our use-case what we do is that we have a custom CNI plugin with custom IPAM block which is global in nature i.e. we don't carve /24 per node, and the POD can just go on any node and pick the static IP from the global pool and that generate /32 or /128 route which is advertised in the bird to all other nodes.

**Comment by dylandreimerink** [comment]
> BGPCplane will advertise any IP that is learned in the linux FIB, isn't it ? So taking the example of static POD, AFAIK when generated specific pod route it will be advertised by Cplane.

That is not correct. BGP Control Plane will announce the PodCIDRs from the k8s Node or Cilium Node resources it gets from the k8s API server, the BGP Control Plane doesn't sync routes to or from the FIB.

**Comment by abasitt** [comment]
> > BGPCplane will advertise any IP that is learned in the linux FIB, isn't it ? So taking the example of static POD, AFAIK when generated specific pod route it will be advertised by Cplane.
> 
> That is not correct. BGP Control Plane will announce the PodCIDRs from the k8s Node or Cilium Node resources it gets from the k8s API server, the BGP Control Plane doesn't sync routes to or from the FIB.

Which resources from k8s API server ? does cilium node looks at every podIP or just read the Node CIDR ranges from the kube-api server ?

**Comment by abasitt** [comment]
@dylandreimerink @YutaroHayakawa if we can achieve below without BGP, i am fine to put this on hold if it works for everyone else too. I do see the advantage of current approach being more simpler than BGP based.

- auto-direct-nodes-routes not restricted to single layer2 domain
- auto-direct-nodes-routes can add routes over tunnel interface and it supports hybrid mode e.g. nodes within same l2 domain works natively and only nodes cross-subnet required tunneling
- No scalability limits, i have no idea what's the scale but just saying because BGP can be design to extremely high scale

**Comment by YutaroHayakawa** [comment]
> auto-direct-nodes-routes not restricted to single layer2 domain
auto-direct-nodes-routes can add routes over tunnel interface and it supports hybrid mode e.g. nodes within same l2 domain works natively and only nodes cross-subnet required tunneling

These two problems can be resolved partially with tunnel mode because we anyways need to have a tunnel for inter-l2 domain communication. The thing we're missing right now is the "hybrid mode".

But the problem with having a tunnel is a tunnel header overhead, we can't avoid that problem with hybrid mode. Because we anyways need to reduce Pod's MTU to the lowest possible value (the value with the tunnel).

You also mentioned the problem that tunnel mode is not supported in the IPv6 single cluster. It is tracked in this issue https://github.com/cilium/cilium/issues/17240.

> No scalability limits, i have no idea what's the scale but just saying because BGP can be design to extremely high scale

We need numbers, but I guess what we're doing for exchanging the route in the `auto-direct-nodes-routes` or tunnel mode is pretty much the same as what the route reflector is doing. We exchange the route through the k8s API server, which behaves very similarly to the RR.

**Comment by abasitt** [comment]
> These two problems can be resolved partially with tunnel mode because we anyways need to have a tunnel for inter-l2 domain communication. The thing we're missing right now is the "hybrid mode".

> But the problem with having a tunnel is a tunnel header overhead, we can't avoid that problem with hybrid mode. Because we anyways need to reduce Pod's MTU to the lowest possible value (the value with the tunnel).

I believe two things with tunnel mode, one is the MTU overhead and another is performance overhead of encap/decap. Unless eBPF and xdp can do the magic, I believe hybrid mode will still be performing better than just tunnel mode for everything.

> You also mentioned the problem that tunnel mode is not supported in the IPv6 single cluster. It is tracked in this issue https://github.com/cilium/cilium/issues/17240.

Yeah that was another reason I raised the issue, but I am hoping this issue can fixed together with auto-direct-nodes-route over tunneling.

> We need numbers, but I guess what we're doing for exchanging the route in the auto-direct-nodes-routes or tunnel mode is pretty much the same as what the route reflector is doing. We exchange the route through the k8s API server, which behaves very similarly to the RR.

This sounds really promising, thank you. Also just to add on, this approach is a lot more simpler than managing BGP.

**Comment by abasitt** [comment]
reopened
