### ISSUE TITLE
CFP: Cilium Cli/Node agent BGP verification support 

### ISSUE THREAD

**Issue by abasitt** [cilium/cilium#20652]
Cilium BGP control plane have no client side verification in place. Currently the verification can only be done from the TOR side. This is important for few reasons e.g.

- Configuring a wrong peer IP address, the TOR will not show anything and user will have hard time to figure out what went wrong. One simple command on the cli to show status of BGP can really help.
- Client and TOR doesn't agree on the BGP parameters. The cilium user may not have access to the TOR to debug. 
- iBGP between cilium nodes to avoid dependency either on TOR or kube-router daemon-set. I am gonna raise another feature request for this one. It will be very important to check if BGP is up amongst all the cilium nodes.

**Describe the feature you'd like**

Cilium cli or node agent should be able to show. Since the direction is more towards BGP control plane feature so we would love to see this feature in the bgp control plane.

- Status of BGP summary with peer address, number of routes (could be optional), status as up/down with an error message if failed.
- Describe BGP peer with more details e.g. possible agreed capabilities. (could be optional)
- Status of BGP peering states and error code at what state the peering failed, logged on the cilium agent node.

**Comment by ldelossa** [comment]
Bump, keeping this alive for further roadmapping.
