### ISSUE TITLE
cilium-operator crashes due to eni-tags upgrading from 1.23.2 to 1.24.3

### ISSUE THREAD

**Issue by chrism417** [cilium/cilium#20666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

using kOps to upgrade from 1.23.2 to 1.24.3 we're seeing the following error in the cilium-operator causing kOps to stop the upgrade:

`level=info msg="Started gops server" address="127.0.0.1:9891" subsys=cilium-operator
level=fatal msg="unable to parse eni-tags: 'Environment=Staging,JiraProject=SysOps,KubernetesCluster=k8s.staging.local,Product=Shared' is not formatted as key=value,key1=value1" subsys=option`

### Cilium Version

cilium-operator is running v1.11.6

### Kernel Version

N/A

### Kubernetes Version

1.24.3

### Relevant log output

```shell
`level=info msg="Started gops server" address="127.0.0.1:9891" subsys=cilium-operator
level=fatal msg="unable to parse eni-tags: 'Environment=Staging,JiraProject=SysOps,KubernetesCluster=k8s.staging.local,Product=Shared' is not formatted as key=value,key1=value1" subsys=option`
```

### Anything else?

I also found this issue: https://github.com/cilium/cilium/issues/19793 so I tried with json format:

`'{"Environment":"Staging","JiraProject":"SysOps","KubernetesCluster":"k8s.staging.local","Product":"Shared"}'`

however cilium-operator still crashed with:

`level=fatal msg="unable to parse eni-tags: ''{ \"Environment\":\"Shared\",\"JiraProject\":\"SysOps\",\"KubernetesCluster\":\"k8s.staging.local\",\"Product\":\"Shared\"}'=' is not formatted as key=value,key1=value1" subsys=option`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tklauser** [comment]
Thanks for the report @chrism417! It looks like this was introduced by #19955. I'll send a fix.

**Comment by chrism417** [comment]
Thanks @tklauser for getting this done so fast
