### ISSUE TITLE
Unable to contact k8s api-server and Unable to initialize Kubernetes subsystem

### ISSUE THREAD

**Issue by delfws** [cilium/cilium#20679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Follow the operation
[Kubernetes Without kube-proxy](https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/)

### install step
~ # kubeadm init ... --skip-phases=addon/kube-proxy
~ # helm install cilium cilium/cilium --version 1.12.0 \
--namespace kube-system \
--set kubeProxyReplacement=strict \
--set k8sServiceHost=${API_SERVER_IP} \
--set k8sServicePort=${API_SERVER_PORT}

### Check the operation

~ # kubectl get pods -l k8s-app=cilium -n kube-system
NAME           READY   STATUS             RESTARTS         AGE
cilium-48vnb   0/1     CrashLoopBackOff   40 (4m39s ago)   176m
cilium-t5vz8   0/1     CrashLoopBackOff   40 (4m33s ago)   176m

### Check pod logs
~ # kubectl get svc -A -o wide
NAMESPACE     NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE     SELECTOR
default       kubernetes       ClusterIP   10.96.0.1      <none>        443/TCP                  26h     <none>
kube-system   hubble-peer      ClusterIP   10.96.97.112   <none>        443/TCP                  3h10m   k8s-app=cilium
kube-system   kube-dns         ClusterIP   10.96.0.10     <none>        53/UDP,53/TCP,9153/TCP   26h     k8s-app=kube-dns

~ # kubectl describe pod cilium-48vnb -n kube-system

```
Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Warning  Unhealthy  9m33s (x1395 over 174m)  kubelet  Startup probe failed: Get "http://127.0.0.1:9879/healthz": dial tcp 127.0.0.1:9879: connect: connection refused
  Warning  BackOff    4m31s (x597 over 171m)   kubelet  Back-off restarting failed container
```

~ # kubectl --namespace kube-system logs cilium-48vnb

```
level=error msg="Unable to contact k8s api-server" error="Get \"https://10.96.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.96.0.1:443: connect: connection refused" ipAddr="https://10.96.0.1:443" subsys=k8s
level=fatal msg="Unable to initialize Kubernetes subsystem" error="unable to create k8s client: unable to create k8s client: Get \"https://10.96.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.96.0.1:443: connect: connection refused" subsys=daemon
```
### my problem
I didn't get a friendly answer by searching the relevant documents and issues. why did `Startup probe failed` and `Unable to contact k8s api-server` fail

### Cilium Version

1.12.0

### Kernel Version

Linux k8s-master 5.18.14-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 12:52:41 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

🔍 Collecting sysdump with cilium-cli version: v0.12.0, args: [sysdump]
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes network policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium network policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium identities
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium nodes
🔍 Collecting Kubernetes endpoints
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting Ingresses
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting Cilium etcd secret
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
⚠️ Deployment "hubble-relay" not found in namespace "kube-system" - this is expected if Hubble is not enabled
🔍 Collecting the Cilium operator deployment
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
🔍 Collecting 'cilium-bugtool' output from Cilium pods
⚠️ Deployment "hubble-ui" not found in namespace "kube-system" - this is expected if Hubble UI is not enabled
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting the CNI configmap
🔍 Collecting gops stats from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting logs from Hubble UI pods
🔍 Collecting platform-specific data
🔍 Collecting Hubble flows from Cilium pods
⚠️ Container "cilium-agent" for pod "cilium-48vnb" in namespace "kube-system" is not running. Trying EphemeralContainer or separate Pod instead...
⚠️ Container "cilium-agent" for pod "cilium-t5vz8" in namespace "kube-system" is not running. Trying EphemeralContainer or separate Pod instead...
⚠️ EphemeralContainer "sysdump-1658998469" on pod "cilium-48vnb" in namespace "kube-system" never reached Running status (falling back to separate Pod)
⚠️ Container "cilium-agent" on pod "cilium-48vnb" in namespace "kube-system" is not running. Creating exec Pod.
⚠️ EphemeralContainer "sysdump-1658998469" on pod "cilium-t5vz8" in namespace "kube-system" never reached Running status (falling back to separate Pod)
⚠️ Container "cilium-agent" on pod "cilium-t5vz8" in namespace "kube-system" is not running. Creating exec Pod.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@delfws the IP address and port for the kube-apiserver should be the real IP address, not `10.96.0.1:443`

**Comment by delfws** [comment]
> @delfws the IP address and port for the kube-apiserver should be the real IP address, not `10.96.0.1:443`

Sorry, I think I know the reason. This should not be a problem with cilium, it should be a configuration problem

**Comment by milan-stikic-cif** [comment]
Hello @delfws ,
Could you share what was the configuration problem. I'm tackling the similar issue right now and can't get my head around it. 
I changed serviceAccountIssuer(JWKS) and after cluster update, cilium pod can't authenticate to API server at all

**Comment by delfws** [comment]
> Hello @delfws , Could you share what was the configuration problem. I'm tackling the similar issue right now and can't get my head around it. I changed serviceAccountIssuer(JWKS) and after cluster update, cilium pod can't authenticate to API server at all

However, when I run the kubeadm init -- control plane endpoint k8s master command, I configure DNS names. After changing to IP addresses, there is no problem. It may be a host configuration problem

**Comment by N0mansky** [comment]
> Hello @delfws , Could you share what was the configuration problem. I'm tackling the similar issue right now and can't get my head around it. I changed serviceAccountIssuer(JWKS) and after cluster update, cilium pod can't authenticate to API server at all

This problem has wasted a lot of time. The real solution is to specify k8s api server endpoint and port.
For example
```
API_SERVER_IP=<your_api_server_ip>
# Kubeadm default is 6443
API_SERVER_PORT=<your_api_server_port>
helm install cilium cilium/cilium --version 1.12.4 \
    --namespace kube-system \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT}
```

You can find that on official document: https://docs.cilium.io/en/v1.12/gettingstarted/kubeproxy-free/#kubeproxy-free

**Comment by Jiang1155** [comment]
> > Hello @delfws , Could you share what was the configuration problem. I'm tackling the similar issue right now and can't get my head around it. I changed serviceAccountIssuer(JWKS) and after cluster update, cilium pod can't authenticate to API server at all
> 
> This problem has wasted a lot of time. The real solution is to specify k8s api server endpoint and port. For example
> 
> ```
> API_SERVER_IP=<your_api_server_ip>
> # Kubeadm default is 6443
> API_SERVER_PORT=<your_api_server_port>
> helm install cilium cilium/cilium --version 1.12.4 \
>     --namespace kube-system \
>     --set kubeProxyReplacement=strict \
>     --set k8sServiceHost=${API_SERVER_IP} \
>     --set k8sServicePort=${API_SERVER_PORT}
> ```
> 
> You can find that on official document: https://docs.cilium.io/en/v1.12/gettingstarted/kubeproxy-free/#kubeproxy-free

Thanks. This saved my life. I used to have those lines in my script. But when I try to create a new cluster today, I thought it was not important and removed them.  Also at first installation of cilium, it worked somehow. Then I need to reinstall cilium again, and got those errors. After adding back those lines, the cilium is working fine now.

**Comment by hainamtvvt** [comment]
In Cilium version 1.14.0 I have same issue

**Comment by jiangxiaoqiang** [comment]
> > Hello @delfws , Could you share what was the configuration problem. I'm tackling the similar issue right now and can't get my head around it. I changed serviceAccountIssuer(JWKS) and after cluster update, cilium pod can't authenticate to API server at all
> 
> This problem has wasted a lot of time. The real solution is to specify k8s api server endpoint and port. For example
> 
> ```
> API_SERVER_IP=<your_api_server_ip>
> # Kubeadm default is 6443
> API_SERVER_PORT=<your_api_server_port>
> helm install cilium cilium/cilium --version 1.12.4 \
>     --namespace kube-system \
>     --set kubeProxyReplacement=strict \
>     --set k8sServiceHost=${API_SERVER_IP} \
>     --set k8sServicePort=${API_SERVER_PORT}
> ```
> 
> You can find that on official document: https://docs.cilium.io/en/v1.12/gettingstarted/kubeproxy-free/#kubeproxy-free

if I have already installed, how to change the address? I did not found in the configmap configuration file.

**Comment by N0mansky** [comment]
> > > Hello @delfws , Could you share what was the configuration problem. I'm tackling the similar issue right now and can't get my head around it. I changed serviceAccountIssuer(JWKS) and after cluster update, cilium pod can't authenticate to API server at all
> > 
> > 
> > This problem has wasted a lot of time. The real solution is to specify k8s api server endpoint and port. For example
> > ```
> > API_SERVER_IP=<your_api_server_ip>
> > # Kubeadm default is 6443
> > API_SERVER_PORT=<your_api_server_port>
> > helm install cilium cilium/cilium --version 1.12.4 \
> >     --namespace kube-system \
> >     --set kubeProxyReplacement=strict \
> >     --set k8sServiceHost=${API_SERVER_IP} \
> >     --set k8sServicePort=${API_SERVER_PORT}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can find that on official document: https://docs.cilium.io/en/v1.12/gettingstarted/kubeproxy-free/#kubeproxy-free
> 
> if I have already installed, how to change the address? I did not found in the configmap configuration file.

Sorry, It's been a while, and I don't remember the details of this issue, but I guess you could use grep to find the 'keyword' of the address in various locations in the files, modifying them accordingly. I think it's better to reinstall, though.

**Comment by yossicohn** [comment]
You can see the reference here
[refernce](https://docs.cilium.io/en/stable/configuration/per-node-config/#example-kubeproxyreplacement-rollout
)

**Comment by is-it-ayush** [comment]
I'm facing a similar issue. The [cilium kube-proxy replacement guide](https://docs.cilium.io/en/v1.12/gettingstarted/kubeproxy-free/#quick-start) advises to set  `API_SERVER_IP` & `API_SERVER_PORT` to the **real** IP address of control plane node. Now suppose you're running multiple control plane nodes, Which node's real IP do you set `API_SERVER_IP` too and what happens when that control-plane node goes down?
```
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT}
```

**Comment by marcofranssen** [comment]
I'm experiencing this issue as well on my EKS cluster.

I configured cilium `1.16.1` as following:

```
helm upgrade --install --create-namespace --namespace kube-system cilium cilium/cilium \
        --values cilium-bootstrap-values.yaml \
        --set cluster.id=1 \
        --set cluster.name="$cluster_name" \
        --set eni.iamRole="$cilium_role_arn" \
        --set "serviceAccounts.operator.annotations.eks\.amazonaws\.com/role-arn"="$cilium_role_arn" \
        --set k8sServiceHost="$cluster_api_endpoint"
```

The important part is the k8sServiceHost which I pointed at my eks cluster api endpoint.

In my case this results in nodes being destroyed and created continously by Karpenter which is our autoscaler.

**Comment by marcofranssen** [comment]
Small update, noticing same in the cilium-operator now. Maybe we are hitting some API rate limiting or something 🤔 .

Happy to provide more details if someone can provide me instructions on what is required and where to grab it.

**Comment by joestringer** [comment]
Hi @marcofranssen , how do you tell which IP is the correct one to use? Is it a directly routable IP on the network? What if AWS changes the control plane location to another IP?

**Comment by Ajithkumar2803** [comment]
Hello all, i have solved the issues for cilium CrashLoopBackOff and below
k get po
NAME                               READY   STATUS                  RESTARTS        AGE
cilium-6275l                       0/1     Init:CrashLoopBackOff   6 (3m48s ago)   17m
cilium-envoy-jnshp                 1/1     Running                 0               17m
cilium-operator-5c7843567ccd5-cznht   0/1     CrashLoopBackOff        7 (2m44s ago)   17m
cilium-operator-5c7867cc43534d5-ghnkp   0/1     Pending                 0               17m


using 
cilium version  1.16.1
EKS version 1.31

following DOC
https://medium.com/@stavocha/getting-hands-on-with-eks-hybrid-nodes-setup-challenges-and-insights-caf7c946a259

Status is **not ready after complete this doc steps.** 
I have updated below command and cilium-values.yaml file 

we should add bpf in cilium-values.yaml

bpf:
  vlanBypass: [4001, 4002]


# cilium-values.yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/compute-type
          operator: In
          values:
          - hybrid
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: 25
    clusterPoolIPv4PodCIDRList:
    - POD_CIDR
operator:
  unmanagedPodWatcher:
    restart: false
bpf:
  vlanBypass: [4001, 4002]


After updating cilium-values.yaml install cilium with below command

API_SERVER_IP=8CC4AA30E867FEF1A8AF7B5C2A5FA3BC.gr7.us-east-1.eks.amazonaws.com
API_SERVER_PORT=443 
or 
API_SERVER_PORT=6443 

helm install cilium cilium/cilium --version 1.16.1 \
    --namespace kube-system \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT}

After updating able view in ready state 

k get node
NAME                   STATUS   ROLES    AGE     VERSION
mi-xxxxx28af   Ready    <none>   2d10h   v1.31.2-eks-94953ac

k get pod
NAME                               READY   STATUS    RESTARTS   AGE
cilium-84m845n                       1/1     Running   0          18m
cilium-envoy-2hdepqs                 1/1     Running   0          18m
cilium-operator-675dddrf6f44b4c-24pbl   1/1     Running   0          18m

**Comment by marcofranssen** [comment]
> Hi [@marcofranssen](https://github.com/marcofranssen) , how do you tell which IP is the correct one to use? Is it a directly routable IP on the network? What if AWS changes the control plane location to another IP?

I'm using the DNS record provided by Amazon EKS.

**Comment by madchap** [comment]
In my case, I had forgotten to patch the `aws-node` DS after switching away from AWS CNI, namely doing

```
kubectl -n kube-system patch daemonset aws-node --type='strategic' -p='{"spec":{"template":{"spec":{"nodeSelector":{"io.cilium/aws-node-enabled":"true"}}}}}'
```

after the brand new cluster would come up.
