### ISSUE TITLE
ENI: new node not does not immediately trigger the creation of Eni

### ISSUE THREAD

**Issue by wu0407** [cilium/cilium#20678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. New node add to cluster, it not immediately trigger the creation of Eni.  Until resync period is triggered, eni be created in new node. so agent in waiting eni create max duration is 1min. 
2. It happend in aws and alibabacloud and azure.
3. it also find log in issue https://github.com/cilium/cilium/issues/18239#issuecomment-992927403 https://github.com/cilium/cilium/issues/14028 https://github.com/cilium/cilium/issues/11560#issuecomment-902693365
```
Instance not found! Please delete corresponding ciliumnode if instance has already been deleted
``` 
4.  `instance does not exist` in azure
5. Because it not update `instanceManger.instances` when new node find. So in `ops.ResyncInterfacesAndIPs` return error in aws and alibabacloud.
https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/aws/eni/node.go#L509-L542
https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/aws/eni/instances.go#L216-L230
https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/ipam/types/types.go#L433-L449

### Cilium Version

master https://github.com/cilium/cilium/tree/94ea7fc93e0af5bf3ddab5b67508003ca47678cd

### Kernel Version

none

### Kubernetes Version

none

### Anything else?

I think need add new method `UpdateInstance(ctx context.Context, obj *v2.CiliumNode) error` for `instanceManager` that call cloud api to get instance for this node and update `instanceManager.instances` .  do update instances logic in `n.ops.UpdatedNode(resource)`
https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/ipam/node.go#L355-L377

``` go
// UpdatedNode is called when an update to the CiliumNode is received.
func (n *Node) UpdatedNode(obj *v2.CiliumNode) {
	n.mutex.Lock()
	n.k8sObj = obj
        n.mutex.Unlock()
        err := n.manager.UpdateInstance(context.Todo(), obj)
        ..........
}
```
other ideas is  add new method  `UpdateInstance(ctx context.Context, obj *v2.CiliumNode) error`   for  `AllocationImplementation` interface and do logic `node.UpdatedResource`
``` go
func (n *Node) UpdatedResource(resource *v2.CiliumNode) bool {
	// Deep copy the resource before storing it. This way we are not
	// dependent on caller not using the resource after this call.
	resource = resource.DeepCopy()

	n.ops.UpdatedNode(resource)
        err := n.manager.instancesAPI.UpdateInstance(context.Todo(), obj)
        if err != nil {
           return false
         }

	n.mutex.Lock()
	// Any modification to the custom resource is seen as a sign that the
	// instance is alive
	n.instanceRunning = true
	n.resource = resource
	n.mutex.Unlock()

	n.recalculate()
	allocationNeeded := n.allocationNeeded()
	if allocationNeeded {
		n.requirePoolMaintenance()
		n.poolMaintainer.Trigger()
	}

	return allocationNeeded
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@wu0407 Could you submit a PR with some fixes? Thank you!

**Comment by christarazi** [comment]
Reopening due to [revert](https://github.com/cilium/cilium/pull/21477) of https://github.com/cilium/cilium/pull/21027.
