### ISSUE TITLE
Cilium Agent 1.10.13 fails to run w/ ipv6.disable=1 kernel parameter

### ISSUE THREAD

**Issue by jaredledvina** [cilium/cilium#20672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading from 1.10.12 to 1.10.13, our cilium-agent processes now fail with a `FATAL` log due to `ip6table` usage. My understanding is that this is because we have configured the kernel parameter `ipv6.disable=1`. 

Prior to 1.10.13, these were just error's that were ignored, I highlighted this back on https://github.com/cilium/cilium/issues/18513#issuecomment-1151357567. However, the iptables logic was reworked in https://github.com/cilium/cilium/pull/19693 which results in the same logic being handled as FATAL. 

Specifically, prior to 1.10.13:
* https://github.com/cilium/cilium/blob/v1.10.12/pkg/datapath/iptables/iptables.go#L202-L205 <--  just return'ed 
* https://github.com/cilium/cilium/blob/v1.10.12/pkg/datapath/iptables/iptables.go#L498 <-- no error handling, results in the errors getting logged but ignored otherwise. 

But in 1.10.13 we now return an error that get's bubbled up to FATAL:
* https://github.com/cilium/cilium/blob/v1.10.13/pkg/datapath/iptables/iptables.go#L219-L222 <-- now returns an err
* https://github.com/cilium/cilium/blob/v1.10.13/pkg/datapath/iptables/iptables.go#L366-L370 <-- now returns the err from above
* https://github.com/cilium/cilium/blob/v1.10.13/daemon/cmd/daemon_main.go#L1674 <-- where we end up and thus exit

Related to all of this is some additional complexity, even with the `ipv6.disable=1` kernel parameter configured, the ip6table modules loaded in https://github.com/cilium/cilium/blob/v1.10.13/pkg/datapath/iptables/iptables.go#L291 do exist on disk and successfully load but when used result in the error `ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n (exit status 3)` getting thrown. We do run the agent's w/ `--enable-ipv6=false` configured but, the logic in this file still results in `haveIp6tables` to staying set to `true`. 

### Cilium Version

1.10.13

### Kernel Version

`Linux ip-10-128-59-96 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.21.9`

### Relevant log output

```shell
level=fatal msg="Error while creating daemon" error="failed to install iptables rules: unable to run 'ip6tables -t nat -S' iptables command: ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n (exit status 3)" subsys=daemon
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jibi** [comment]
Reproduced on 1.10.13:

```
Jul 28 09:28:08 k8s1 cilium-agent[3637]: level=warning msg="Failed to install iptables rules" error="unable to run 'ip6tables -t nat -S' iptables command: ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n (exit status 3)" subsys=iptables
```

**Comment by jibi** [comment]
Hey @jaredledvina :wave: the fix has been merged in master, once backported it should land in the next 1.10 release

**Comment by jaredledvina** [comment]
Sounds great, thanks @jibi !
