### ISSUE TITLE
cilium installation failed on specefic EKS instance type

### ISSUE THREAD

**Issue by fazizsoltani** [cilium/cilium#20684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I got these error messages on the cilium pod when the EKS instance type is m6i.2xlarge
my cilium version is 1.9.18 based on documentation.
```
level=info msg="All pre-existing resources related to policy have been received; continuing" subsys=k8s-watcher
level=info msg="Successfully synchronized CiliumNode custom resource" name=ip-172-30-21-228.ec2.internal subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-172-30-21-228.ec2.internal required=2 subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-172-30-21-228.ec2.internal required=2 subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-172-30-21-228.ec2.internal required=2 subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-172-30-21-228.ec2.internal required=2 subsys=ipam
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=0 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-172-30-21-228.ec2.internal required=2 subsys=ipam
```

### Cilium Version

1.9.18

### Kernel Version

Linux ip-172-30-21-228.ec2.internal 5.4.196-108.356.amzn2.x86_64 #1 SMP Thu May 26 12:49:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
As the error message indicates, are there any errors or warnings in the operator logs?

My guess is that m6i.2xlarge is too new to be understood by Cilium 1.9 (which is EOL). You can work around that issue by manually providing the instance limit metadata for `m6i.2xlarge` via the `aws-instance-limit-mapping` configmap value, see the following comment for an example:

https://github.com/cilium/cilium/issues/20280#issuecomment-1163052908

**Comment by fazizsoltani** [comment]
Thank you. It works
