### ISSUE TITLE
Always migrate tail call maps

### ISSUE THREAD

**Issue by ti-mo** [cilium/cilium#20691]
Context: https://github.com/cilium/cilium/pull/20425#issuecomment-1198135951

During ELF loading, the loader can encounter a tail call map with a different maxentries compared to the already-pinned tail call map for the endpoint, which leads it to recreate the map with the new size. Currently, when the agent starts up (or when a contributor changes some BPF .c during development and triggers an endpoint regenerate), there are 2 possible scenarios:

- The tail call map's properties (type, k, v, maxentries, flags) are different, so the map needs to be recreated. In this case: build ELF, load ELF from disk, see map properties have changed, move old map, create new map, pin new map, load all progs in the ELF (including entrypoint) into the kernel, put all prog fds into new tail call map (one by one..), atomically replace bpf entrypoint on the qdisc/xdp.
- Map properties are the same (not grown or shrunk), so the same pinned map is re-used. Build ELF, load ELF, open pinned map, load all progs into the kernel, put all prog fds into the pinned map one by one (which is still actively used by an existing qdisc/xdp), only then replace the entrypoint.

In the latter scenario, populating the tail call map is a sequential operation, not all prog array slots are replaced at once. Re-using a pinned tail call map causes an inconsistent view of the world while the new progs are being inserted into the existing map. If we move some logic from e.g. tail call 1 to tail call 11, packets are still handled while we're repopulating the tail call map. This could cause packets to be accepted or dropped erroneously.

I propose we remove the map migration concept entirely. Not only because it complicates the loader process, but also because the gains are negligible. The difference between both scenarios is the bpffs dir rename (and removal afterwards) and creation of the new tail call map, which consumes only a small amount of memory.

**Comment by joestringer** [comment]
The high-level goal of the migration step is to prepare a brand new set of maps, progs, etc. in preparation for a successful atomic transition to the new datapath, then attempt the transition, then if the transition fails roll back. Ideally even if the new version is broken there is no impact to the datapath. If I follow your proposal correctly, you're suggesting that we just _always_ follow that path (your first bulletpoint) so we don't have two different possibilities. Then we can simplify the code and reduce likelihood of weird bugs during the transition. That seems like a reasonable proposal to me :+1:

**Comment by Jack-R-lantern** [comment]
Can you assign this issue to me?

**Comment by Jack-R-lantern** [comment]
Can you assign that issue to me?

**Comment by joestringer** [comment]
Hey @Jack-R-lantern , if you have a work in progress PR then I think it'd make sense to assign the issue sure! Feel free to join Slack #development to ask questions, or join the weekly community meetings to discuss next steps to contribute to this issue.

With regards to the entry point, this is mostly related to `OpenOrCreate()` calls on Cilium agent startup.

**Comment by ti-mo** [comment]
@Jack-R-lantern So sorry to send you on a goose chase for no reason. This was a really straightforward fix, but one that does require a bit of background to integrate and document accurately. While I was typing up some pointers for you, I realized we needed to move some code around. For your next contribution, I'd recommend you go through the issue tracker to find ones [labeled with `good-first-issue` or `help-wanted`](https://github.com/cilium/cilium/issues?q=is%3Aopen+is%3Aissue+label%3Ahelp-wanted%2Cgood-first-issue).

The Go bpf loader code is currently undergoing a lot of changes and is generally in a bit of a rough shape, so onboarding new contributors is quite challenging at this time. Please do go through the issue tracker and find something that suits you!

If you'd like to follow along with this one, I've just submitted a PR: https://github.com/cilium/cilium/pull/26459.

Sorry again, and thank you for your interest!
