### ISSUE TITLE
Endpoint list shows Status OK even if bpf program can't be build

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#207]
When listing `cilium endpoint list` to see the endpoint status. The status presented can be deceiving because of the `Policy regenerated` messages.

```
Endpoint status: 
2016-12-01T15:42:40Z - OK - Policy regenerated
2016-12-01T15:42:05Z - OK - Policy regenerated
2016-12-01T15:41:38Z - OK - Policy regenerated
2016-12-01T15:40:39Z - Failure - error: "exit status 1" command output: "Join EP id=29898_update ifname=lxcefaff
``` 

We should add priority to the status messages, for example on this case, bpf recompilation is more important than Policy regenerated and therefore we should show Status Failure on endpoint list.

Or stop the policy regenerated for the endpoint until the bpf program is properly recompiled.

**Comment by tgraf** [comment]
Agreed.

I think we should also perform test compilation of the program at cilium daemon startup time and have it fail right away to catch the most obvious dependency errors. Compilation errors are rarely specific to the container but most often a missing dependency in the kernel that applies to all programs that are compiled.
