### ISSUE TITLE
CI: Create control plane tests for IPsec

### ISSUE THREAD

**Issue by brb** [cilium/cilium#20707]
To have a better coverage of the IPSec integration, we could implement privileged control plane tests in a similar manner as we have done for testing the neighbor entries management - https://github.com/cilium/cilium/blob/v1.12.0/pkg/datapath/linux/node_linux_test.go#L1067. 

The test would start multiple node manager instances running in different network namespaces which would configure IPSec among the netns. Then, it would do basic connectivity checks.

**Comment by pchaigno** [comment]
Do we have any examples of past bugs that would have been caught by such tests, but not by BPF unit tests or end-to-end tests?

**Comment by jschwinger233** [comment]
> Do we have any examples of past bugs that would have been caught by such tests

If I remember correctly, @brb caught a bug by control plane test, but I couldn't find the record.

**Comment by brb** [comment]
This was a unit test - https://github.com/cilium/cilium/issues/27280. Anyway, considering that I didn't come up with any scenario, we can close this issue.
