### ISSUE TITLE
eni: need redesign eni metric, many wrong and ambiguities metrics

### ISSUE THREAD

**Issue by wu0407** [cilium/cilium#20704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Many wrong metrics that has no label value or metrics name is ambiguities in eni metrics.
such as:
1.  Failed to release ip that call `IncAllocationAttempt` in `handleIPRelease`. `IncAllocationAttempt` is mean "Number of interfaces allocated", it not represent an error in releasing IP. https://github.com/cilium/cilium/blob/78d075d1bedf7f6e3890dd2a9fab20383201f3c4/pkg/ipam/node.go#L776-L806
2. It to call `IncAllocationAttempt` to add `cilium_operator_ipam_interface_creation_ops` value  when success call `AllocateIPs` in `handleIPAllocation`. it is difficult to distinguish whether the network card is created successfully or the IP is allocated successfully. https://github.com/cilium/cilium/blob/78d075d1bedf7f6e3890dd2a9fab20383201f3c4/pkg/ipam/node.go#L821-L836
3. https://github.com/cilium/cilium/issues/20384
4. https://github.com/cilium/cilium/issues/20431

### Cilium Version

master https://github.com/cilium/cilium/tree/78d075d1bedf7f6e3890dd2a9fab20383201f3c4

### Kernel Version

none

### Kubernetes Version

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@wu0407 Could you submit a PR with some fixes? Thank you!
