### ISSUE TITLE
CFP: Software Bill of Materials (SBOM)

### ISSUE THREAD

**Issue by xmulligan** [cilium/cilium#20712]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

No

**Describe the feature you'd like**

With each release of Cilium, it would be great to have a software bill of materials.

**Comment by yimikao** [comment]
Hi @xmulligan. I got to know about this project through the LFX Mentorship programme and I found it interesting. I would love to work on this issue. Could you provide some guidance prior to submitting my application.

**Comment by xmulligan** [comment]
Hi @yimikao thanks for reaching out. This issue will be worked on during the program by the accepted mentee. The application will open on August 25th. Please submit then https://lfx.linuxfoundation.org/tools/mentorship/

**Comment by aanm** [comment]
This will help to generate the SBOM for Golang: https://pkg.go.dev/debug/buildinfo

**Comment by xmulligan** [comment]
You can find the application here https://mentorship.lfx.linuxfoundation.org/project/680e32e5-d056-46fa-a94d-4af453d4e81d

**Comment by prince-7** [comment]
@aanm @xmulligan I have applied on the mentorship portal please consider my application. I would like to contribute to this issue, I am willing to contribute to other issues that are under this program as well.

**Comment by acald-creator** [comment]
Good morning.

I've applied for the mentorship. I'm familiar with the concepts of SBOM and how to generate. I would like to assist with this task.

**Comment by xmulligan** [comment]
Thank you @prince-7 and @acald-creator for applying. The mentee will be chosen by September 1st

**Comment by xmulligan** [comment]
@sandipanpanda is working on this in #21374
