### ISSUE TITLE
kernel (5.18.14) versions: OK! but error="BPF NodePort services needs kernel 4.17.0 or newer." subsys=daemon

### ISSUE THREAD

**Issue by delfws** [cilium/cilium#20726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My kernel version is 5.18.14, but he said my kernel version is not new enough

```bash
level=info msg="Cilium 1.12.0 9447cd1 2022-07-19T12:22:00+02:00 go version go1.18.4 linux/amd64" subsys=daemon
level=info msg="cilium-envoy  version: e90612180b82d07c124bbf8e1ffe94a8d603f8ae/1.21.3/Distribution/RELEASE/BoringSSL" subsys=daemon
level=info msg="clang (10.0.0) and kernel (5.18.14) versions: OK!" subsys=linux-datapath
level=info msg="linking environment: OK!" subsys=linux-datapath
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Mounted cgroupv2 filesystem at /run/cilium/cgroupv2" subsys=cgroups
level=info msg="Parsing base label prefixes from default label list" subsys=labels-filter
level=info msg="Parsing additional label prefixes from user inputs: []" subsys=labels-filter
level=info msg="Final label prefixes to be used for identity evaluation:" subsys=labels-filter
......

level=error msg="unable to initialize Kube proxy replacement options" error="BPF NodePort services needs kernel 4.17.0 or newer." subsys=daemon
level=fatal msg="Error while creating daemon" error="unable to initialize Kube proxy replacement options: BPF NodePort services needs kernel 4.17.0 or newer." subsys=daemon
```

### Cilium Version

1.12.0

### Kernel Version

Linux k8s-master 5.18.14-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 12:52:41 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

🔍 Collecting sysdump with cilium-cli version: v0.12.0, args: [sysdump]
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium network policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium nodes
🔍 Collecting Cilium identities
🔍 Collecting Ingresses
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting Cilium etcd secret
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
🔍 Collecting gops stats from Cilium pods
🔍 Collecting gops stats from Hubble pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting 'cilium-bugtool' output from Cilium pods
⚠️ Deployment "hubble-relay" not found in namespace "kube-system" - this is expected if Hubble is not enabled
⚠️ Deployment "hubble-ui" not found in namespace "kube-system" - this is expected if Hubble UI is not enabled
🔍 Collecting gops stats from Hubble Relay pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting platform-specific data
🔍 Collecting logs from Hubble UI pods
🔍 Collecting Hubble flows from Cilium pods
⚠️ Container "cilium-agent" for pod "cilium-v7lqh" in namespace "kube-system" is not running. Trying EphemeralContainer or separate Pod instead...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report @delfws . The following check appears to be failing on this kernel:

https://github.com/cilium/cilium/blob/master/daemon/cmd/kube_proxy_replacement.go#L224-L225

I wonder if either `bpftool feature probe` is not working correctly to detect this feature support on this kernel? Could you try to gather the output from this command on the host and post it? (Also post exactly how you ran the command, in case that is relevant).

**Comment by delfws** [comment]
I ran this command, and then I checked the system requirements of cilium, and found that I forgot to modify the basic requirements configuration.

```bash
[root@k8s-master ~]# bpftool -j feature probe
null
[root@k8s-master ~]# cat /boot/config-$(uname -r) | egrep "^CONFIG_BPF=|^CONFIG_BPF_SYSCALL=|^CONFIG_NET_CLS_BPF=|^CONFIG_BPF_JIT=|^CONFIG_NET_CLS_ACT=|^CONFIG_NET_SCH_INGRESS=|^CONFIG_CRYPTO_SHA1=|^CONFIG_CRYPTO_USER_API_HASH=|^CONFIG_CGROUPS=|^CONFIG_CGROUP_BPF="
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_CGROUPS=y
CONFIG_CGROUP_BPF=y
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_CRYPTO_SHA1=y
CONFIG_CRYPTO_USER_API_HASH=y
```

**Comment by sunnoy** [comment]
how to modify the basic requirements configuration ? i meet this also

**Comment by sunnoy** [comment]
> I ran this command, and then I checked the system requirements of cilium, and found that I forgot to modify the basic requirements configuration.
> 
> ```shell
> [root@k8s-master ~]# bpftool -j feature probe
> null
> [root@k8s-master ~]# cat /boot/config-$(uname -r) | egrep "^CONFIG_BPF=|^CONFIG_BPF_SYSCALL=|^CONFIG_NET_CLS_BPF=|^CONFIG_BPF_JIT=|^CONFIG_NET_CLS_ACT=|^CONFIG_NET_SCH_INGRESS=|^CONFIG_CRYPTO_SHA1=|^CONFIG_CRYPTO_USER_API_HASH=|^CONFIG_CGROUPS=|^CONFIG_CGROUP_BPF="
> CONFIG_BPF=y
> CONFIG_BPF_SYSCALL=y
> CONFIG_BPF_JIT=y
> CONFIG_CGROUPS=y
> CONFIG_CGROUP_BPF=y
> CONFIG_NET_SCH_INGRESS=m
> CONFIG_NET_CLS_BPF=m
> CONFIG_NET_CLS_ACT=y
> CONFIG_CRYPTO_SHA1=y
> CONFIG_CRYPTO_USER_API_HASH=y
> ```

how to modify the basic requirements configuration ? i meet this also

**Comment by joestringer** [comment]
@sunnoy the answer to that will depend on your Linux distribution vendor and how you prepare your kernel. Most common distributions will already satisfy these constraints, but if you use an unusual/custom Linux environment then you will need to take care of these details yourself.

The requirements are listed here:
https://docs.cilium.io/en/stable/operations/system_requirements/#admin-system-reqs
