### ISSUE TITLE
Better handle when K8s Nodes have more than one IP address per address type in their status field

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#20787]
https://github.com/kubernetes/kubernetes/issues/61921 indicates that K8s assumes that a Node has one IP per type, as seen in https://github.com/kubernetes/kubernetes/blob/8f3b2813dcd6e3f2c9b260bedaeddbdd0ea5c0cc/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L711 and https://github.com/kubernetes/kubernetes/blob/master/pkg/util/node/node.go#L81.

There are two approaches:

1) Add a warning log to the user to say that we detected multiple IPs per type and this may impact the ipcache by having potential conflicts with pod IPs. As seen in https://github.com/cilium/cilium/issues/20243.
2) Enforce the 1 IP per type and reject all other IPs of the same type. Use the same preference [logic](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/node/node.go#L81) as K8s.

Follow up from https://github.com/cilium/cilium/issues/20243.

**Comment by matchyc** [comment]
Could you highlight the related code in cilium?

**Comment by danehans** [comment]
Hi all! I would like to take a shot at resolving this issue. Can @christarazi or another maintainer assign me?

**Comment by danehans** [comment]
@christarazi To confirm my understanding of the issue, a node should have two address types, ExternalIP and InternalIP. Each address type can have an IPv4 address and an IPv6 address. Any additional node addresses will be ignored and with a warning-level log message.
