### ISSUE TITLE
Can't keep original IP when crossing hosts on a cluster

### ISSUE THREAD

**Issue by r3pek** [cilium/cilium#20789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running a 2-worker-node k8s cluster, if a pod is running on host B, but I access it via host A, the accessing IP that is presented on the service is the cilium_host interface ip from host A. 
Am I missing some configuration that allows the IP to be known?

### Cilium Version

v1.12.0

### Kernel Version

Linux k8s-master 5.14.0-134.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 21 12:57:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment]
are you using any kind of cilium layer 7 policy? you could turn on cilium datapath debug
```
  debug: "true"
 debug-verbose: "datapath"
```

then `kubectl exec -it cilium-agent-pod-on-host-A -n kube-system -- cilium monitor -vv > /tmp/debug.log`

**Comment by r3pek** [comment]
No policy (l7 or otherwise) applied to the cluster.

Log attached, but some insights:
- source ip I tested was 178.166.49.12
- pod is running on host B (10.1.0.6)
- host A IP is 10.1.0.

[cilium-debug.log](https://github.com/cilium/cilium/files/9268215/cilium-debug.log)
5

**Comment by vincentmli** [comment]
I am trying to understand your problem description, from the debug log below, it looks to me 

src  178.166.49.12:56342 -> dst  10.1.0.5:443 -> dst 10.244.32.224:443. 

client: 178.166.49.12
node A: 10.1.0.5
pod IP: 10.244.32.244 on node B 10.1.0.6

is  10.1.0.5:443 node port service that has endpoint  10.244.32.224:443 ?

are you saying client  IP 178.166.49.12 is translated to cilium_host interface IP on node A when you check src ip  on pod 10.244.32.224 ? do you have tcpdump capture or any data to show the client  IP 178.166.49.12 changed to cilium_host interface IP ? the debug log belows shows VXLAN inner packet source ip is still 172.166.49.12, no change.


```
Ethernet        {Contents=[..14..] Payload=[..54..] SrcMAC=d2:74:7f:6e:37:e3 DstMAC=86:00:00:1b:5e:b0 EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..32..] Version=4 IHL=5 TOS=0 Length=52 Id=65199 Flags=DF FragOffset=0 TTL=49 Protocol=TCP Checksum=15246 SrcIP=178.166.49.12 DstIP=10.244.32.224 Options=[] Padding=[]}
TCP     {Contents=[..32..] Payload=[] SrcPort=56342 DstPort=443(https) Seq=2995212645 Ack=1985822875 DataOffset=8 FIN=false SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=496 Checksum=34880 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:909358339/1723855448 0x3633b50366bff258)] Padding=[]}
CPU 03: MARK 0x0 FROM 779 to-overlay: 66 bytes (66 captured), state new, interface cilium_vxlan, , identity world->unknown, orig-ip 0.0.0.0
CPU 03: MARK 0x85ff1689 FROM 779 DEBUG: Conntrack lookup 1/2: src=10.1.0.5:49029 dst=10.1.0.6:8472
CPU 03: MARK 0x85ff1689 FROM 779 DEBUG: Conntrack lookup 2/2: nexthdr=17 flags=1 
CPU 03: MARK 0x85ff1689 FROM 779 DEBUG: CT entry found lifetime=218042, revnat=0 
CPU 03: MARK 0x85ff1689 FROM 779 DEBUG: CT verdict: Established, revnat=0        
CPU 03: MARK 0x0 FROM 779 DEBUG: Successfully mapped addr=10.1.0.4 to identity=7 
CPU 03: MARK 0x0 FROM 779 DEBUG: Successfully mapped addr=10.1.0.4 to identity=7 
CPU 03: MARK 0x0 FROM 779 DEBUG: Successfully mapped addr=178.166.49.12 to identity=2
CPU 03: MARK 0x0 FROM 779 DEBUG: Conntrack lookup 1/2: src=178.166.49.12:56342 dst=10.1.0.5:443
CPU 03: MARK 0x0 FROM 779 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=4         
CPU 03: MARK 0x0 FROM 779 DEBUG: CT entry found lifetime=239582, revnat=19       
CPU 03: MARK 0x0 FROM 779 DEBUG: CT verdict: Reply, revnat=19                    
CPU 03: MARK 0x0 FROM 779 DEBUG: Conntrack lookup 1/2: src=178.166.49.12:56342 dst=10.244.32.224:443
CPU 03: MARK 0x0 FROM 779 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1         
CPU 03: MARK 0x0 FROM 779 DEBUG: CT entry found lifetime=239582, revnat=19       
CPU 03: MARK 0x0 FROM 779 DEBUG: CT verdict: Established, revnat=19              
CPU 03: MARK 0x0 FROM 779 DEBUG: Encapsulating to node 167837702 (0xa010006) from seclabel 2
```

**Comment by r3pek** [comment]
src 178.166.49.12 -> dst (net) 116.202.xxx.xxx -> (gets NAT translated to 10.1.0.5) -> LB service 10.96.94.129 -> pod 10.244.32.224

This is the full path.

when hitting that IP, the one that gets translated to 10.1.0.5, i only see the 10.244.28.242 IP (cilium_hohst interface on host A), not the original one (178.166.49.12)
when hitting the public IP for host B, that gets translated to 10.1.0.6, the pod sees the original IP from the src (178.166.49.12).

I can do some tcpdumps if you want. Just tell me where to capture and I'll attach them here. Meanwhile, the logs I see are this:
```
10.244.28.242 - - [05/Aug/2022:16:03:02 +0000] "GET / HTTP/2.0" 303 35 "-" "curl/7.82.0" 174492 "code-drone-b90dacd0430fe0e301ad@kubernetescrd" "http://10.244.43.150:80" 2ms
178.166.49.12 - - [05/Aug/2022:16:03:02 +0000] "GET / HTTP/2.0" 303 35 "-" "curl/7.82.0" 174493 "code-drone-b90dacd0430fe0e301ad@kubernetescrd" "http://10.244.43.150:80" 1ms
178.166.49.12 - - [05/Aug/2022:16:03:03 +0000] "GET / HTTP/2.0" 303 35 "-" "curl/7.82.0" 174495 "code-drone-b90dacd0430fe0e301ad@kubernetescrd" "http://10.244.43.150:80" 1ms
178.166.49.12 - - [05/Aug/2022:16:03:04 +0000] "GET / HTTP/2.0" 303 35 "-" "curl/7.82.0" 174496 "code-drone-b90dacd0430fe0e301ad@kubernetescrd" "http://10.244.43.150:80" 1ms
10.244.28.242 - - [05/Aug/2022:16:03:05 +0000] "GET / HTTP/2.0" 303 35 "-" "curl/7.82.0" 174497 "code-drone-b90dacd0430fe0e301ad@kubernetescrd" "http://10.244.43.150:80" 1ms
10.244.28.242 - - [05/Aug/2022:16:03:05 +0000] "GET / HTTP/2.0" 303 35 "-" "curl/7.82.0" 174500 "code-drone-b90dacd0430fe0e301ad@kubernetescrd" "http://10.244.43.150:80" 1ms
178.166.49.12 - - [05/Aug/2022:16:03:06 +0000] "GET / HTTP/2.0" 303 35 "-" "curl/7.82.0" 174501 "code-drone-b90dacd0430fe0e301ad@kubernetescrd" "http://10.244.43.150:80" 1ms
```

The pod is a Traefik instance.

**Comment by vincentmli** [comment]
> src 178.166.49.12 -> dst (net) 116.202.xxx.xxx -> (gets NAT translated to 10.1.0.5) -> LB service 10.96.94.129 -> pod 10.244.32.224
> 

ok, but I don't understand how -> 10.1.0.5:443 would be directed to LB service 10.96.94.129, the -> 10.1.0.5:443 is the first entry point that the packet enter into the cluster and 10.1.0.5 is node ip, I guess you have some kind configuration to redirect node:port to LB service?

> This is the full path.
> 
> when hitting that IP, the one that gets translated to 10.1.0.5, i only see the 10.244.28.242 IP (cilium_host interface on host A), not the original one (178.166.49.12) when hitting the public IP for host B, that gets translated to 10.1.0.6, the pod sees the original IP from the src (178.166.49.12).
> 
it sounds like when the endpoint pod is not local pod but on remote node, and cilium needs to redirect the traffic to remote node, this could happen, maybe work by design?  you could setup node port service with pod on node B only, and send traffic to the node port service on node A to double check if client ip is preserved or not

**Comment by r3pek** [comment]
> ok, but I don't understand how -> 10.1.0.5:443 would be directed to LB service 10.96.94.129, the -> 10.1.0.5:443 is the first entry point that the packet enter into the cluster and 10.1.0.5 is node ip, I guess you have some kind configuration to redirect node:port to LB service?

well, the traffic needs to get to the host right? It get's NAT translated from the public IP to the private one. Then the LB service that actually opened the port (443) on the host picks up the packet and forwards it to the pod.

I don't know if this is by design or not. If it's by design, fine. If it's not, it might be a problem on my end or an actual bug somewhere :zipper_mouth_face:. Just asked because I know Calico can do it, just not sure about Cilium.

**Comment by vincentmli** [comment]
> 10.96.94.129



> > ok, but I don't understand how -> 10.1.0.5:443 would be directed to LB service 10.96.94.129, the -> 10.1.0.5:443 is the first entry point that the packet enter into the cluster and 10.1.0.5 is node ip, I guess you have some kind configuration to redirect node:port to LB service?
> 
> well, the traffic needs to get to the host right? It get's NAT translated from the public IP to the private one. Then the LB service that actually opened the port (443) on the host picks up the packet and forwards it to the pod.

from the debug log, there is no trace of 10.96.94.129:443, only trace of 10.1.0.5:443, so I am wondering how LB service  10.96.94.129:443 would handle the request.

> 
> I don't know if this is by design or not. If it's by design, fine. If it's not, it might be a problem on my end or an actual bug somewhere 🤐. Just asked because I know Calico can do it, just not sure about Cilium.

you could verify cilium behavior by setting up node port service or cluster service where cilium is required to redirect the request to remote node pod and you should see what cilium normal behavior is vs your particular setup

**Comment by r3pek** [comment]
can we reopen this since it's still an issue?
