### ISSUE TITLE
Updating labels of many pods is causing large spikes in LIST /ciliumendpoints

### ISSUE THREAD

**Issue by mateuszlitwin** [cilium/cilium#20790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Updating labels of many pods is causing large spike in traffic generated by `LIST /ciliumendpoints` responses.

I was able to partially decrease the traffic by filtering out labels as described in https://docs.cilium.io/en/v1.9/operations/scalability/identity-relevant-labels/. 

However there is still considerable amount of stress on the API server. I am suspecting it is caused by synchronization of pod labels with cilium endpoint labels (introduced in https://github.com/cilium/cilium/pull/12406). I think synchronizing cilium endpoint labels is causing cilium endpoint watchers to receive a lot of updates.

It would be great, if it was possible to filter out pod labels from being synchronized with cilium endpoint labels. For example, use the filters described in https://docs.cilium.io/en/v1.9/operations/scalability/identity-relevant-labels/.

It can be reproduced by creating >500 pods (total number of nodes in a cluster might be a factor as well), and each pod running `kubectl label pod --overwrite $MY_POD_NAME test-label=$RANDOM` in a loop.

### Cilium Version

v1.9.4

### Kernel Version

5.4.0-1072-azure 18.04.1-Ubuntu

### Kubernetes Version

v1.21.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@mateuszlitwin Thanks for the GH issue, can you give us an example for the filter that you are using to filter the labels and an example of labels that you are using to put in the pods? Thank you.

**Comment by mateuszlitwin** [comment]
I am excluding custom labels used in my org using pattern like this:

```
labels: "k8s:!.*myorg.com"
```

This is enough to prevent cilium from creating of new security identities when `.*myorg.com` labels change. However there is still substantial amount of traffic generated because these labels are still synchronized with CiliumEndpoint labels (see https://github.com/cilium/cilium/pull/12406).

**Comment by mateuszlitwin** [comment]
Are there any benefits from mirroring pod labels that are not identity-relevant labels?

**Comment by aanm** [comment]
@mateuszlitwin that's a good point! No, if they are ignored they should be not be mirrored into the CiliumEndpoint. Would you like to submit a PR with the fix? Thanks

**Comment by aanm** [comment]
Yes that should do it, the only change would be to assign `idtyLabels.K8sStringMap()` to a new variable and use that variable in the places where `idtyLabels.K8sStringMap()` is being executed. I don't know what `K8sStringMap()` does but it's not worth it running it twice.

**Comment by aanm** [comment]
@NikhilSharmaWe, if @mateuszlitwin does not mind feel free to do it.

**Comment by xmulligan** [comment]
@mateuszlitwin Great to see that you are using Cilium. Would you be interested in doing a Cilium User Story? https://www.cncf.io/case-studies?_sft_lf-project=cilium

The process is just a 30 minute interview then I will write it up for you for approval
