### ISSUE TITLE
No incoming pod traffic metrics when bpf masquerade is enabled

### ISSUE THREAD

**Issue by maxpain** [cilium/cilium#20791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When `bpf.masquerade` is enabled there are no metrics for NAT traffic incoming to pod

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/5875582/182970999-7cb9a159-f1eb-427c-adce-8ee03fb784b5.png">

(on the screenshot I disabled `bpf.masquerade` and after this receive bandwidth is showing)

### Cilium Version

Client: 1.12.0 9447cd1 2022-07-19T12:22:00+02:00 go version go1.18.4 linux/amd64
Daemon: 1.12.0 9447cd1 2022-07-19T12:22:00+02:00 go version go1.18.4 linux/amd64

### Kernel Version

Linux s1-comnet-tas 5.15.57-talos #1 SMP Mon Jul 25 15:49:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by carnerito** [comment]
@maxpain Bandwidth metrics in the graphs you have posted here are exposed by Cilium or Cadvisor (or something else)?
