### ISSUE TITLE
eni:  nodeManager not sync all node on operator starting

### ISSUE THREAD

**Issue by wu0407** [cilium/cilium#20815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. The operator `nodeManager.nodes` not containt all CiliumNode  on starting run `nodeManager.Resync()`.
2. Because  `nodeManager.Resync()` and `nodeManager.Create() or nodeManager.Update()` are asynchronous
3. It cause  IP shortage problem for part of nodes was not solved immediately and metrics `cilium_operator_ipam_nodes` and `cilium_operator_ipam_available_interfaces` not corrected.
4. https://github.com/cilium/cilium/blob/960afc5c4bb830aa835e39f56f1100426400be38/pkg/ipam/node_manager.go#L361-L369 https://github.com/cilium/cilium/blob/960afc5c4bb830aa835e39f56f1100426400be38/pkg/ipam/node_manager.go#L318-L323

### Cilium Version

master https://github.com/cilium/cilium/tree/960afc5c4bb830aa835e39f56f1100426400be38

### Kernel Version

none

### Kubernetes Version

node

### Anything else?

I think need update NodeManager.nodes on 
`NewNodeManager`  or 
 `startSynchronizingCiliumNodes` after cache synced https://github.com/cilium/cilium/blob/960afc5c4bb830aa835e39f56f1100426400be38/pkg/ipam/node_manager.go#L150-L164
https://github.com/cilium/cilium/blob/960afc5c4bb830aa835e39f56f1100426400be38/operator/cilium_node.go#L208-L220

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NikhilSharmaWe** [comment]
@wu0407 I would like to work on updating the `NewManager.nodes` inside the function `NewNodeManager`. 
For that do we need to execute [Update](https://github.com/cilium/cilium/blob/master/pkg/ipam/node_manager.go#L258) function inside the [NewNodeManager](https://github.com/cilium/cilium/blob/960afc5c4bb830aa835e39f56f1100426400be38/pkg/ipam/node_manager.go#L150-L164) function.

Please inform if this is reasonable. If not, what will be the right approach.

**Comment by wu0407** [comment]
yes, i will do inside the function NewNodeManager, but not use cache. But list all node may impact apiserver in the large cluster.
so i will use the page request to list all nodes.
