### ISSUE TITLE
Automate release Cilium release process

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#20850]
Right now the release process is done by manually following, depending on the type of release, one of these issues templates https://github.com/cilium/release/tree/master/.github/ISSUE_TEMPLATE

It would be great if we could decrease those checklist items by improving it with automation.

**Comment by xmulligan** [comment]
This will be part of the LFX mentorship. You can find the application here https://mentorship.lfx.linuxfoundation.org/project/680e32e5-d056-46fa-a94d-4af453d4e81d

**Comment by aminoxix** [comment]
heya @aanm @xmulligan,

I would love to take this under the LFX mentorship program! 🙂 
Applying for the same (update)

Thanks!

**Comment by Rahulkhinchi03** [comment]
Hi @aanm,
I have applied for the LFX Mentorship Program for this Project ( i.e. CNCF - Cilium: Improving Security posture of the Cilium/Hubble/Tetragon release process).

I have previously worked on a similar project "Automate release process of Checkstyle" as a Google Summer of Code 22 Student.

Ref: https://summerofcode.withgoogle.com/programs/2022/projects/nWt378bQ
