### ISSUE TITLE
Ginkgo CI: direct logs from each test to a file

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2085]
Since the Ginkgo CI uses logrus, we can set up a hook which logs all logs of a specific level to a file for each test, including debug-level logs. We can only log Info level logs to console to make the CI runs less verbose. The debug logs can be investigated in the case of failure.

**Comment by eloycoto** [comment]
Hi, 

Another alternative here, on the test suite we can have a global `AfterEach`, so I propose to have a Report Writer, that get a copy of all `node.std[out|err]` writer, and on that `aftereach` reset the writer and send the contents to a file with the name of the test. 

The logrus information will be sent to Junit Output, so maybe this is the best way to track all commands + results. 

Regards

**Comment by ianvernon** [comment]
What will the contents of `node.std[out|err]` be? I was thinking of the following, for example:
```
log.Infof("write to console")
log.Debugf("write to file")
```

We would have two logrus hooks, one which just logs to console as is done now, and logs up to info level, and another hook which logs up to debug level (using something like https://github.com/rifflock/lfshook ).

We could allow for configuration of the logging level with a flag provided to Ginkgo as well.

**Comment by eloycoto** [comment]
Hi @ianvernon  

I'll close this, It's already done. PR #2290 

Regards.
