### ISSUE TITLE
Upgrade Iptables shipped in Cilium runtime image to >= 1.8.5

### ISSUE THREAD

**Issue by jibi** [cilium/cilium#20884]
Currently we are shipping Cilium with Iptables `1.8.4`, which doesn't fully support the iptables-legacy - nft translation of `NOTRACK` rules (it only allows to add rules for that target, but doesn't work with the deletion of such rules).

While a workaround is in place (we can ignore those rules when cleaning up any old Cilium ruleset as eventually the agent will delete the whole `OLD_` chain), this is not optimal, and we should look into upgrading to a version that supports that:
* either by bumping the iptables version in the 20.04 Ubuntu base image (which requires adding the repositories for 22.04)
* or by updating the base image to 22.04

The earliest version which fully supports `NOTRACK` is `1.8.5`. From the release notes:
```
iptables-translate:
- Support `time' match and `NOTRACK' target.
```

**Comment by joestringer** [comment]
I we should aim to bump the base image to 22.04 during the v1.13 release cycle.

**Comment by sayboras** [comment]
after https://github.com/cilium/cilium/pull/20943 is merged, the default iptables version is iptables v1.8.7 (nf_tables).

So I think we can close this issue.

**Comment by jibi** [comment]
https://github.com/cilium/cilium/pull/20943 has been merged, so I'll just close this :+1:
