### ISSUE TITLE
"Failed to install iptables rules" causes anetd crashes

### ISSUE THREAD

**Issue by liuyuan10** [cilium/cilium#20894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sometimes, we notice anetd crashes on RHEL/centos nodes due to error:

```
level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: failed to install iptables rules: unable to run 'iptables -t filter -D OLD_CILIUM_OUTPUT -m mark ! --mark 0xe00/0xf00 -m mark ! --m# Warning: iptables-legacy tables present, use iptables-legacy to see them' iptables command: iptables v1.8.4 (nf_tables): unknown option \"--m#\"\nTry `iptables -h' or 'iptables --help' for more information.\n (exit status 2)" subsys=daemon
```

Clearly the stderr output (# Warning: iptables-legacy tables present, use iptables-legacy to see them) of iptables mixed into stdout causes the failure.

The issue has been around a while but become noticeable after commit d812b925dec2d8be09834277050050d67681fd7c

There is no clear way to reproduce. it shows up in our CIs randomly. Also golang exec.CombinedOutput should be thread-safe and stdout and stderr shouldn't be interleaved.

For now, I'm seeing a mitigation is not to merge stderr into the output but putting it into err.

### Cilium Version

1.11.7

### Kernel Version

4.18.0-305 

centos 8.4

### Kubernetes Version

v1.23.5-gke.1504

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liuyuan10** [comment]
this is the log file
[cilium.log](https://github.com/cilium/cilium/files/9330049/cilium.log)

**Comment by aanm** [comment]
Can you check if https://github.com/cilium/cilium/pull/20885 fixes this? Thank you

**Comment by liuyuan10** [comment]
it's unrelated. I don't have any `-j NOTRACK` on my node. Also if that's the case, it will crash everytime. If you parse my error message carefully, you will see the printed command is:

```
iptables -t filter -D OLD_CILIUM_OUTPUT -m mark ! --mark 0xe00/0xf00 -m mark ! --m# Warning: iptables-legacy tables present, use iptables-legacy to see them
```

The stderr cuts into the stdout and breaks the command
