### ISSUE TITLE
Cluster mesh: Cilium agent not detecting nodes deleted from the meshed cluster

### ISSUE THREAD

**Issue by demimraz** [cilium/cilium#20899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have two K8s clusters C1&C2 with Cilium cluster-mesh enabled. 
When I delete one node from C2, Cilium agent in C2 detects node has been deleted by using command 'cilium status' or 'cilium node list' to confirm. But Cilium agent in C1 does not detect this and shows unreachable node which in fact is deleted in C2. Only If I restart C2 clustemesh pod and C1 cilium agent, C1 cilium status becomes correct, that is, the deleted node is no longer shown as unreachable, but actually deleted.

### Cilium Version

Cilium version 1.11.4

### Kernel Version

5.13.0-40-generic
ubuntu

### Kubernetes Version

1.21.14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
:wave: 

Can you try with 1.11.5 and check if the issue is still happening ? Recently, we have added cilium node garbage collector, but it's only available in 1.11.5+.

https://github.com/cilium/cilium/pull/19576

**Comment by demimraz** [comment]
Hi @sayboras,
Thanks for your input.
I upgraded C1&C2 to cilium version 1.11.6, but it looks like the issue still exists.

**Comment by sayboras** [comment]
Seems like there is another fix coming soon here as well. 

Appreciate if you can help to test it out, kindly note that the fix is currently on top of master branch (e.g. v1.12, but not v1.11), you can also wait for it to land in 1.11 branch later.

https://github.com/cilium/cilium/pull/20968
