### ISSUE TITLE
docs: Add documentation for supported Ingress annotations

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#20902]
Current Ingress implementation supports a couple of annotations as per [this](https://github.com/cilium/cilium/blob/master/operator/pkg/ingress/annotations/annotations.go#L15-L19). More and more annotations are contributed by community for different use cases.

It's better to have a page to document all available options for reference. We can start with manual update, and investigate on how to automatically update the page, having CI job to check discrepancies is a big plus.

**Comment by NikhilSharmaWe** [comment]
@sayboras I would like to work on this.

**Comment by NikhilSharmaWe** [comment]
Is this location makes sense: https://github.com/NikhilSharmaWe/cilium/blob/docIngressAnnotations/Documentation/annotations/ingress_annotations.md

**Comment by sayboras** [comment]
> Does this location makes sense: https://github.com/NikhilSharmaWe/cilium/blob/docIngressAnnotations/Documentation/annotations/ingress_annotations.md

I think it's making more sense to have annotations in the below page (or its child).

https://docs.cilium.io/en/latest/installation/servicemesh/ingress/

> And do we need to define a new ci job and new make rules like: make -C Documentation update-cmdref which is used to update doc in Documentatio/cmdref? So, the similar one for updating the new annotations.

Yes, it will be ideal to have auto-generation target to avoid the drift. However, it's not straightforward like cmdref as the annotations are embedded inside go file(s). I think manual update will be a good first step.
