### ISSUE TITLE
ClusterMesh: GC'd Identity triggering warnings in all agents

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#20909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Identity is created
2. ~60s later, endpoint using identity is removed
3. ~30s later, operator marks identity for later deletion
4. ~35m later, operator GC's identity and all agents log `UpdateIdentities: Skipping Delete of a non-existing identity`

### Cilium Version

```
Client: 1.11.7 506fcf6 2022-07-15T10:05:01-07:00 go version go1.17.12 linux/amd64
Daemon: 1.11.7 506fcf6 2022-07-15T10:05:01-07:00 go version go1.17.12 linux/amd64
```

### Kernel Version

` 5.13.0-1031-aws #35~20.04.1-Ubuntu`

### Kubernetes Version

`Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

### Relevant log output

```shell
Local agent: 

2022-08-15 19:01:36	
level=info msg="Removed endpoint" containerID= datapathPolicyRevision=1930 desiredPolicyRevision=1930 endpointID=2662 identity=260260 ipv4= ipv6= k8sPodName=/ subsys=endpointShow context
2022-08-15 19:00:24	
level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=1930 desiredPolicyRevision=1930 endpointID=2662 identity=260260 ipv4= ipv6= k8sPodName=/ subsys=daemon
2022-08-15 19:00:24	
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1930 endpointID=2662 identity=260260 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2022-08-15 19:00:23	
level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2662 identity=260260 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2022-08-15 19:00:23	
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2662 identity=260260 identityLabels="..." ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
```

Operator:
```
2022-08-15 19:47:01	
level=info msg="Garbage collected identity" identity=260260 subsys=cilium-operator-aws
2022-08-15 19:31:58	
level=info msg="Marking identity for later deletion" identity="&{{ } {260260    c944e14b-f54d-472f-8637-0ad4cc241b74 731486562 1 2022-08-15 19:00:23 +0000 UTC <nil> <nil> map[...] map[] [] []  [{cilium-agent Update cilium.io/v2 2022-08-15 19:00:23 +0000 UTC map[...]}" subsys=cilium-operator-aws
```

All other agents:
`2022-08-15 19:47:01	
level=warning msg="UpdateIdentities: Skipping Delete of a non-existing identity" identity=260260 subsys=policy`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@dctrwatson are the warnings form the agents form that cluster or from a different cluster?

**Comment by dctrwatson** [comment]
> @dctrwatson are the agent's warnings form that cluster or from a different cluster?

No warnings from agents in the local cluster

**Comment by sayboras** [comment]
:wave: 

I managed to simulate the issue locally. Just want to check if the warning logs are emitting continuous for you, or they just stopped after a few warning (e.g. number of replicas/endpoints - 1).

In my local clusters, my global service is having two endpoints, hence two events were fired:
- the first event was handled successfully with `UpdateIdentities: Deleting identity`
- the second event emitted warning log `Skipping Delete of a non-existing identity` as identity was removed above.

```
2022-08-16T09:14:31.297614412Z level=debug msg="Emitting delete event for cilium/state/identities/v1/id/157604=[]" config=/var/lib/cilium/clustermesh/kind-2 endpoints="[https://kind-2.mesh.cilium.io:31196]" prefix=cilium/state/identities/v1/id revision=61 subsys=kvstore watcher=cilium/state/identities/v1/id
2022-08-16T09:14:31.297663554Z level=debug msg="UpdateIdentities: Deleting identity" identity=157604 labels="[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=kind-2 k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:name=rebel-base]" subsys=policy
2022-08-16T09:14:31.299089038Z level=debug msg="Emitting delete event for cilium/state/identities/v1/id/157604=[]" config=/var/lib/cilium/clustermesh/kind-2 endpoints="[https://kind-2.mesh.cilium.io:31196]" prefix=cilium/state/identities/v1/id revision=61 subsys=kvstore watcher=cilium/state/identities/v1/id
2022-08-16T09:14:31.299181433Z level=warning msg="UpdateIdentities: Skipping Delete of a non-existing identity" identity=157604 subsys=policy
```

**Comment by dctrwatson** [comment]
:wave: 

> I managed to simulate the issue locally.

:relieved: 

> Just want to check if the warning logs are emitting continuous for you, or they just stopped after a few warning (e.g. number of replicas/endpoints - 1).

Yup, it's just ~once per replica per endpoint.

**Comment by sayboras** [comment]
Having warning logs is not ideal, but it's just limited to couple of them, I don't think we need to fix and change anything here.

There could be some improvements that we can make to avoid publishing n-1 times for the same event, and it could be long-term performance improvement.

I am closing this ticket soon, feel free to let us know if you have other concerns. Thanks.

**Comment by dctrwatson** [comment]
It's not the logs I'm worried about (they can easily be filterd), it's the noise in `cilium_errors_warnings_total`

![Screenshot_2022-08-17_11 28 28](https://user-images.githubusercontent.com/395054/185215549-7a070aee-b9f3-47ca-b051-791db2284959.png)

**Comment by sayboras** [comment]
actually, the above metric is already having the level label, so to avoid some noise, you can filter based on level (e.g. level=error).

**Comment by dctrwatson** [comment]
> actually, the above metric is already having the level label, so to avoid some noise, you can filter based on level (e.g. level=error).

oh? did not see that before. Thank you!

**Comment by sayboras** [comment]
there were a couple of improvements recently on multiple fronts

Seems like the original concern you have is good now, I am closing the ticket.
