### ISSUE TITLE
Wireguard connectivity issue between pods on different nodes

### ISSUE THREAD

**Issue by maximumG** [cilium/cilium#20925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We rollout our kubernetes cluster CNI from cilium version 1.10.11 to version 1.11.7 and started to encounter some network connectivity issue between pods running on different nodes.

Cilium is configured with wireguard enabled. We are using node auto-scaling as well, so nodes might join/disappear from the cluster randomly (spot instances). From our testing kube cluster, it seems that impacted nodes are missing some wireguard peers. A restart of the cilium agent on the impacted nodes is solving the issue.

As an example we have:
* pod client-test-555d4d8447-7859f (IP 100.96.12.242) on node ip-10-0-6-168.eu-west-1.compute.internal
* pod server-test-8xkn9 (IP 100.96.16.21) on node ip-10-0-4-16.eu-west-1.compute.internal

### Client to server ICMP

Here is the result of an ICMP request from client to server:

```
# ping -c 4 100.96.16.21
PING 100.96.16.21 (100.96.16.21) 56(84) bytes of data.
--- 100.96.16.21 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3066ms
```

The local cilium agent actually has a wireguard tunnel to the remote node, running the server pod.

```
cilium debuginfo --output json | jq .encryption | grep endpoint
            "endpoint": "10.0.4.205:51871",
            "endpoint": "10.0.6.121:51871",
            "endpoint": "10.0.4.27:51871",
            "endpoint": "10.0.5.111:51871",
            "endpoint": "10.0.6.206:51871",
            "endpoint": "10.0.4.143:51871",
            "endpoint": "10.0.4.16:51871", # node running the server pod
```

### Server to client ICMP

Here is the result of an ICMP request from server to client:

```
# ping 100.96.12.242
PING 100.96.12.242 (100.96.12.242) 56(84) bytes of data.
From 100.96.16.209 icmp_seq=1 Destination Host Unreachable
From 100.96.16.209 icmp_seq=2 Destination Host Unreachable
From 100.96.16.209 icmp_seq=3 Destination Host Unreachable
From 100.96.16.209 icmp_seq=4 Destination Host Unreachable
From 100.96.16.209 icmp_seq=5 Destination Host Unreachable
From 100.96.16.209 icmp_seq=6 Destination Host Unreachable
From 100.96.16.209 icmp_seq=7 Destination Host Unreachable
From 100.96.16.209 icmp_seq=8 Destination Host Unreachable
From 100.96.16.209 icmp_seq=9 Destination Host Unreachable
From 100.96.16.209 icmp_seq=10 Destination Host Unreachable
^C
--- 100.96.12.242 ping statistics ---
10 packets transmitted, 0 received, +10 errors, 100% packet loss, time 9210ms
```

The local cilium agent does not have any up-to-date tunnel to remote node, especially the one running the client pod. I guess this is why it responds with an ICMP destination host unreachable to the pod.

```
cilium debuginfo --output json | jq .encryption | grep "endpoint"
            "endpoint": "10.0.6.206:51871",
            "endpoint": "10.0.4.27:51871",
            "endpoint": "10.0.6.121:51871",
            "endpoint": "10.0.5.111:51871",
            "endpoint": "10.0.4.205:51871",
```

I'm wondering how does the cilium agent is updating wireguard peers, when these peers might join/disappear randomly ? We didn't faced the issue in cilium v1.10.11

### Cilium Version

v1.11.7

### Kernel Version

5.10.130-118

### Kubernetes Version

v1.23.8

### Sysdump

[cilium-sysdump-20220816-175255.zip](https://github.com/cilium/cilium/files/9352675/cilium-sysdump-20220816-175255.zip)

I filtered out sysdump to only include the two impacted nodes from the example in description.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maximumG** [comment]
I dig a bit further in the issue and here are my preliminary conclusion. In our current testing setup, when a node terminates, it is automatically replaced by a new one thanks to node auto-scaling.

Here is what is currently happening when a new node (A) comes up.

1. The node A is registered as `Ready` in the kubernetes cluster
2. A new cilium pod A' is created on node A and start its registration process
3. The cilium pod A' registered itself in our dedicated cilium etcd backend
4. :red_circle: **In the etdc backend, the node is registered without its WIreguardPukKey attribute set**
```
cilium/state/nodes/v1/default/ip-10-0-6-59.eu-west-1.compute.internal => 
{"Name":"ip-10-0-6-59.eu-west-1.compute.internal","Cluster":"default","IPAddresses":[{"Type":"InternalIP","IP":"10.0.6.59"},{"Type":"CiliumInternalIP","IP":"100.96.7.172"}],"IPv4AllocCIDR":{"IP":"100.96.7.0","Mask":"////AA=="},"IPv6AllocCIDR":null,"IPv4HealthIP":"100.96.7.203","IPv6HealthIP":"","ClusterID":0,"Source":"local","EncryptionKey":0,"Labels":{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"m6a.xlarge","beta.kubernetes.io/os":"linux","failure-domain.beta.kubernetes.io/region":"eu-west-1","failure-domain.beta.kubernetes.io/zone":"eu-west-1c","kops.k8s.io/instancegroup":"nodes","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"ip-10-0-6-59.eu-west-1.compute.internal","kubernetes.io/os":"linux","kubernetes.io/role":"node","node-role.kubernetes.io/node":"","node.kubernetes.io/instance-type":"m6a.xlarge","topology.ebs.csi.aws.com/zone":"eu-west-1c","topology.kubernetes.io/region":"eu-west-1","topology.kubernetes.io/zone":"eu-west-1c"},"NodeIdentity":1,"WireguardPubKey":""}
```
5. :red_circle: On any other nodes we cannot see any wireguard tunnel with this peer and any pod on node A is unreachable from the other pods running on different nodes
6. :green_circle: As soon as the cilium pod A' is deleted and re-created, it is registered correctly with its WIreguardPukKey attribute set
7. :green_circle: On every oether nodes we can see the wireguard tunnel pointing to node A. As a result pods running on node A are now reachable

I guess that this missing WireguardPubKey in the ETCD store is the cause of the pod connectivity issue. I'm still wondering why restarting the cilium pod is fixing the issue ?

**Comment by ReillyBrogan** [comment]
OK now that I know what to look for I think it's highly likely that the issue that I've seen is the same one. I checked the wireguard endpoints in the debuginfo for two nodes that were having connectivity issues and I can see that node a has node b as an endpoint while node b does not have a corresponding entry for node a.

**Comment by aanm** [comment]
@maximumG @ReillyBrogan can you test with `synchronize-k8s-nodes: false` set in Cilium's configmap? You will need to restart CiliumOperator after this change. Thank you

**Comment by maximumG** [comment]
> can you test with synchronize-k8s-nodes: false set in Cilium's configmap ?

@aanm I deactivated the k8s nodes synchronization in the cilium configmap & restarted both cilium-operator pods, but the issue still remains. After further testing I can confirm that:

* Switching back from kvstore to CRD solves the issue. But obviously I'd like to stay in kvstore :smiley: 
* When using kvstore & `synchronize-k8s-nodes: true` (default), every nodes has a proper CRD meaning the _WireguardPubKey_ is always registered correctly and does not disappear (see below).

```
Name:         ip-10-0-6-188.eu-west-1.compute.internal
Namespace:    
Labels:       beta.kubernetes.io/arch=amd64
              beta.kubernetes.io/instance-type=m6a.xlarge
              beta.kubernetes.io/os=linux
              failure-domain.beta.kubernetes.io/region=eu-west-1
              failure-domain.beta.kubernetes.io/zone=eu-west-1c
              kops.k8s.io/instancegroup=nodes
              kubernetes.io/arch=amd64
              kubernetes.io/hostname=ip-10-0-6-188.eu-west-1.compute.internal
              kubernetes.io/os=linux
              kubernetes.io/role=node
              node-role.kubernetes.io/node=
              node.kubernetes.io/instance-type=m6a.xlarge
              topology.kubernetes.io/region=eu-west-1
              topology.kubernetes.io/zone=eu-west-1c
Annotations:  io.cilium.network.wg-pub-key: yx3Lc147VjSd+TZ50eegfzfw1H/WODOjfAw1rYHuagY=
```

**Comment by ReillyBrogan** [comment]
That one seems like a decent candidate. Have you considered bisecting between the `v1.11.4` and `v1.11.5` git tags? I tried to do it myself at one point but for whatever reason it could sometimes take a while before the issue cropped up (or more likely before it was noticed as it doesn't affect all node adjacencies and this cluster only has a few test workloads running on it). You can clone the repo and run `make docker-cilium-image` and `make docker-operator-image` to build test images that you can then push to a repository of your choice.

**Comment by aanm** [comment]
@maximumG I can confirm that is the PR that introduced the regression.

**Comment by ReillyBrogan** [comment]
I'm giving the v1.11 branch a try with that commit reverted. So far so good.

**Comment by ReillyBrogan** [comment]
@maximumG FYI it looks like 1.11.9 will be released today and that version will have the fixes for this. I've been running a custom build of the `v1.11` branch built just after the PRs fixing it were merged and it's been running fine on my test cluster.
