### ISSUE TITLE
Service mesh envoy-metrics ports 9964 of cilium 1.12.0 is not up

### ISSUE THREAD

**Issue by erictarrence** [cilium/cilium#20938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Port 9964 of cilium-agent envoy-metrics is not started, only ports 9962 and 9965 are started

cilium's service mesh is installed according to this document

https://docs.cilium.io/en/stable/gettingstarted/servicemesh/l7-traffic-management/

```
        - containerPort: 9964
          hostPort: 9964
          name: envoy-metrics
          protocol: TCP

 netstat -tnlp | grep 996
tcp        0      0 0.0.0.0:9962            0.0.0.0:*               LISTEN      17683/cilium-agent  
tcp        0      0 0.0.0.0:9965            0.0.0.0:*               LISTEN      17683/cilium-agent  

prometheus get 9964 port error
Get "http://192.168.0.105:9964/metrics": dial tcp 192.168.0.105:9964: connect: connection refused
```

cilium install command:

```
helm install cilium cilium/cilium --version 1.12.0 \
--namespace kube-system \
--set nodeinit.enabled=true \
--set externalIPs.enabled=true \
--set nodePort.enabled=true \
--set hostPort.enabled=true \
--set pullPolicy=IfNotPresent \
--set config.ipam=cluster-pool \
--set hubble.enabled=true \
--set hubble.listenAddress=:4244 \
--set hubble.relay.enabled=true \
--set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
--set hubble.ui.enabled=true \
--set kubeProxyReplacement=strict \
--set k8sServiceHost=192.168.0.101 \
--set k8sServicePort=6443 \
--set operator.prometheus.enabled=true \
--set prometheus.enabled=true \
--set ipam.operator.clusterPoolIPv4MaskSize=25 \
--set ipam.operator.clusterPoolIPv4PodCIDR=10.2.0.0/16 \
--set-string extraConfig.enable-envoy-config=true 
```

### Cilium Version

cilium version
cilium-cli: v0.12.1 compiled with go1.18.5 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.12.1
cilium image (running): v1.12.0

### Kernel Version

uname -r
5.14.0-70.13.1.el9_0.x86_64
almalinux9.0

### Kubernetes Version

kubectl v1.24.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rolinh** [comment]
Thanks for the report @Ericra95. Could you please open one issue per question? The first one relates to Hubble UI and the second one to service mesh and it looks like they are unrelated.

**Comment by aanm** [comment]
@Ericra95 let's keep this one open and use the https://github.com/cilium/hubble-ui for the hubble-related one

**Comment by sayboras** [comment]
:wave: 

for the second question, please confirm if you have created either Ingress resource, or cilium L7 network policy created. By default, we don't start envoy proxy if not required, hence envoy metric port will not be available upon cilium installation.

**Comment by Ericra95** [comment]
> kubectl -n kube-system get pod | grep ui
> hubble-ui-5fccdb86fc-g6nhp        1/2     CrashLoopBackOff   12 (75s ago)   40m
> 
> 
> kubectl -n kube-system logs  hubble-ui-5fccdb86fc-g6nhp 
> Defaulted container "frontend" out of: frontend, backend
> /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
> /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
> 10-listen-on-ipv6-by-default.sh: info: ipv6 not available
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
> /docker-entrypoint.sh: Configuration complete; ready for start up
> 2022/08/17 09:10:09 [emerg] 1#1: socket() [::]:8081 failed (97: Address family not supported by protocol)
> nginx: [emerg] socket() [::]:8081 failed (97: Address family not supported by protocol)



> @Ericra95 let's keep this one open and use the https://github.com/cilium/hubble-ui for the hubble-related one

Thank you for the reminder, a new issue has been opened at the link
https://github.com/cilium/hubble-ui/issues/278

**Comment by Ericra95** [comment]
> wave
> 
> for the second question, please confirm if you have created either Ingress resource, or cilium L7 network policy. By default, we don't start envoy proxy if not required, hence envoy metric port will not be available upon cilium installation.
```
https://docs.cilium.io/en/stable/gettingstarted/servicemesh/l7-traffic-management/
```

This document mentions that installing cilium without installing ingress requires setting the --set-string extraConfig.enable-envoy-config=true parameter


At the same time, do you have to set cilium L7 network policy, will envoy-metrics ports 9964 be activated? I have some doubts about this
1. The test/production system does not have to set the cilium L7 network policy
2. The envoy of istio can automatically get the pod metric data after the business is deployed
3. https://isovalent.com/blog/post/cilium-service-mesh/ The cilium service mesh mentioned in the document is very functional, does not require sidecar, and mentions an Envoy Configuration CRD (New)
But I didn't see the Envoy Configuration CRD after I installed cilium1.12

Envoy Configuration CRD (New)
A new exciting Envoy Configuration CRD is available, making the entire Envoy proxy feature set available anywhere in the network. This enables users to write Envoy Configuration directly, and apply this anywhere in the network to enable advanced use cases that are not even covered by service meshes such as Istio.

**Comment by sayboras** [comment]
Provisioning CEC resource will also start envoy proxy, and in turn expose metric listener accordingly. I have missed this scenario in my previous reply, the gist is still staying the same _envoy is started if required_.

**Comment by Ericra95** [comment]
> CEC resource


https://isovalent.com/blog/post/cilium-release-112/ This documentation mentions Envoy CRD – CiliumEnvoyConfig (CEC)

But after reading the following two links, I did not see the methods and parameters of CiliumEnvoyConfig (CEC) configuration

https://docs.cilium.io/en/stable/gettingstarted/
https://github.com/cilium/cilium/tree/v1.12.0/install/kubernetes/cilium

Do you have the setup documentation for CiliumEnvoyConfig (CEC) there?

**Comment by Ericra95** [comment]
> Provisioning CEC resource will also start envoy proxy, and in turn expose metric listener accordingly. I have missed this scenario in my previous reply, the gist is still staying the same _envoy is started if required_.


Testing according to the CEC installation documentation will not start port 9964, only port 9090.

https://docs.cilium.io/en/stable/gettingstarted/servicemesh/envoy-custom-listener/

```
# ss -nltp | grep 996
LISTEN 0      32768        0.0.0.0:9962       0.0.0.0:*    users:(("cilium-agent",pid=17683,fd=52))                 
LISTEN 0      32768        0.0.0.0:9965       0.0.0.0:*    users:(("cilium-agent",pid=17683,fd=51))                 
LISTEN 0      32768        0.0.0.0:10259      0.0.0.0:*    users:(("kube-scheduler",pid=18996,fd=7))                
# ss -nltp | grep 9090
LISTEN 0      32768        0.0.0.0:9090       0.0.0.0:*    users:(("cilium-envoy",pid=64365,fd=58))                 
LISTEN 0      32768        0.0.0.0:9090       0.0.0.0:*    users:(("cilium-envoy",pid=64365,fd=55))                 
LISTEN 0      32768        0.0.0.0:9090       0.0.0.0:*    users:(("cilium-envoy",pid=64365,fd=52))                 
LISTEN 0      32768        0.0.0.0:9090       0.0.0.0:*    users:(("cilium-envoy",pid=64365,fd=51))                 
LISTEN 0      32768        0.0.0.0:9090       0.0.0.0:*    users:(("cilium-envoy",pid=64365,fd=50))                 
LISTEN 0      32768        0.0.0.0:9090       0.0.0.0:*    users:(("cilium-envoy",pid=64365,fd=49))                 
# ps aux | grep 64365
root       64365  0.1  0.2 2290140 46584 ?       Sl   09:47   0:08 cilium-envoy -l info -c /var/run/cilium/bootstrap.pb --base-id 0 --log-format %t|%l|%n|%v



curl -I http://192.168.0.102:9090/metrics
HTTP/1.1 200 OK
content-type: text/plain; charset=UTF-8
cache-control: no-cache, max-age=0
x-content-type-options: nosniff
date: Fri, 19 Aug 2022 02:59:43 GMT
server: envoy
x-envoy-upstream-service-time: 3
transfer-encoding: chunked
```

Then I changed 9090 to 9964

```
netstat -tnlp | grep 996
tcp        0      0 0.0.0.0:9962            0.0.0.0:*               LISTEN      17683/cilium-agent  
tcp        0      0 0.0.0.0:9964            0.0.0.0:*               LISTEN      64365/cilium-envoy  
tcp        0      0 0.0.0.0:9965            0.0.0.0:*               LISTEN      17683/cilium-agent  
tcp        0      0 0.0.0.0:10259           0.0.0.0:*               LISTEN      18996/kube-schedule 
```

Because my server only supports the ipv4 protocol, there are some ipv6 errors in ds/cilium
```
level=error msg="cannot read proc file" error="open /proc/net/tcp6: no such file or directory" file-path=/proc/net/tcp6 subsys=proxy
level=error msg="cannot read proc file" error="open /proc/net/udp6: no such file or directory" file-path=/proc/net/udp6 subsys=proxy
level=error msg="cannot read proc file" error="open /proc/net/tcp6: no such file or directory" file-path=/proc/net/tcp6 subsys=proxy
level=error msg="cannot read proc file" error="open /proc/net/udp6: no such file or directory" file-path=/proc/net/udp6 subsys=proxy
```

Then there are some suggestions
1. Increase the ipv6_compat parameter to facilitate users to enable or disable ipv6
2. Can the CEC document write a few more usage scenarios, or a youtube video is best
