### ISSUE TITLE
bgp-control-plane failed to retrieve labels for Node

### ISSUE THREAD

**Issue by wenqiang0527** [cilium/cilium#20959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

level=error msg="Encountered error during reconciliation" component=Controller.Run error="failed to retrieve labels for Node: failed to get node test20220809111450a0a8.master.node.com: node \"test20220809111450a0a8.master.node.com\" not found" subsys=bgp-control-plane

### Cilium Version

v1.12.0

### Kernel Version

4.18.0-348.el8.x86_64

### Kubernetes Version

1.24.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ldelossa** [comment]
Hello @wenqiang0527 can you provide me a sysdump of your cluster. You can do this with the following instructions: https://docs.cilium.io/en/v1.12/operations/troubleshooting/#automatic-log-state-collection

**Comment by wenqiang0527** [comment]
bgp-control-plane  will announce  podCIDR ? 

CiliumBGPPeeringPolicy:
spec:
  nodeSelector:
    matchLabels:
      bgp-policy: a
  virtualRouters:
  - exportPodCIDR: true
    localASN: 64512
    neighbors:
    - peerASN: 65199
      peerAddress: 10.125.1.8/32

cilium install  --config=k8s-api-server=https://10.182.5.40:6443,kube-proxy-replacement=strict,tunnel=disabled,cluster-pool-ipv4-cidr=10.142.48.0/24,cluster-pool-ipv4-mask-size=28,ipam=cluster-pool-v2beta,enable-bgp-control-plane=true,ipv4-native-routing-cidr=10.142.48.0/24,debug=true

cilium agent  some logs:
level=debug msg="failed to connect" Error="dial tcp 0.0.0.0:0->10.125.1.8:179: connect: no route to host" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=info msg="Reconciling peers for virtual router with local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=info msg="Adding peer 10.125.1.8/32 65199 to local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=info msg="Done reconciling peers for virtual router with local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=info msg="type:STATE  peer:{conf:{local_asn:64512  neighbor_address:\"10.125.1.8\"  peer_asn:65199}  state:{local_asn:64512  neighbor_address:\"10.125.1.8\"  peer_asn:65199  session_state:IDLE  router_id:\"<nil>\"}  transport:{local_address:\"<nil>\"}}"
level=info msg="type:STATE  peer:{conf:{local_asn:64512  neighbor_address:\"10.125.1.8\"  peer_asn:65199}  state:{local_asn:64512  neighbor_address:\"10.125.1.8\"  peer_asn:65199  session_state:ACTIVE  router_id:\"<nil>\"}  transport:{local_address:\"<nil>\"}}"

Am I miss some configuration?

**Comment by ldelossa** [comment]
@wenqiang0527 the latest logs are not the issue you first referenced when creating this ticket. 

Can you please provide either the sysdump or the full agent log, and a definition of the issue you are facing and want to troubleshoot.

**Comment by wenqiang0527** [comment]
here is sysdump

agent some logs:
level=info msg="  --local-router-ipv4=''" subsys=daemon
level=info msg="  --local-router-ipv6=''" subsys=daemon
level=info msg="Restored router address from node_config" file=/var/run/cilium/state/globals/node_config.h ipv4=10.142.48.39 ipv6="<nil>" subsys=node
level=debug msg="Allocated specific IP" ip=10.142.48.39 owner=router subsys=ipam
level=debug msg="Preflight for virtual router with ASN 64512 not necessary, first instantiation of this BgpServer." component=gobgp.preflightReconciler subsys=bgp-control-plane
level=debug msg="Begin reconciling peers for virtual router with local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=info msg="Reconciling peers for virtual router with local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=info msg="Done reconciling peers for virtual router with local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=debug msg="Begin reconciling pod CIDR advertisements for virtual router with local ASN 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=info msg="type:STATE peer:{conf:{local_asn:64512 neighbor_address:\"10.125.1.8\" peer_asn:65199} state:{local_asn:64512 neighbor_address:\"10.125.1.8\" peer_asn:65199 session_state:IDLE router_id:\"<nil>\"} transport:{local_address:\"<nil>\"}}"
level=info msg="type:STATE peer:{conf:{local_asn:64512 neighbor_address:\"10.125.1.8\" peer_asn:65199} state:{local_asn:64512 neighbor_address:\"10.125.1.8\" peer_asn:65199 session_state:ACTIVE router_id:\"<nil>\"} transport:{local_address:\"<nil>\"}}"


level=debug msg="Successfully listed CiliumBGPPeeringPolicies" component=Controller.Reconcile count=1 subsys=bgp-control-plane
level=debug msg="Comparing BGP policy node selector with node's labels" component=PolicySelection nodeLabels="beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,bgp-policy=a,kubernetes.io/arch=amd64,kubernetes.io/hostname=nvm20220809111450a0a8.master.sinanode.com,kubernetes.io/os=linux" policyNodeSelector="bgp-policy=a" subsys=bgp-control-plane
level=debug msg="Asking configured BGPRouterManager to configure peering" component=Controller.Reconcile subsys=bgp-control-plane
level=debug msg="Reconciling new CiliumBGPPeeringPolicy" component=gobgp.RouterManager.ConfigurePeers diff="Registering: [64512] Withdrawing: [] Reconciling: []" subsys=bgp-control-plane
level=info msg="Registering GoBGP servers for policy with local ASN 64512" component=gobgp.RouterManager.registerBGPServer subsys=bgp-control-plane
level=debug msg="Preflight for virtual router with ASN 64512 not necessary, first instantiation of this BgpServer." component=gobgp.preflightReconciler subsys=bgp-control-plane
level=debug msg="Begin reconciling peers for virtual router with local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=info msg="Reconciling peers for virtual router with local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=info msg="Adding peer 10.125.1.8/32 65199 to local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=info msg="Add a peer configuration" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=info msg="Done reconciling peers for virtual router with local ASN 64512" component=gobgp.neighborReconciler subsys=bgp-control-plane
level=debug msg="Begin reconciling pod CIDR advertisements for virtual router with local ASN 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="Advertising pod CIDR 10.142.48.32/28 for policy with local ASN: 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="create Destination" Nlri=10.142.48.32/28 Topic=Table asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="Advertising pod CIDR 10.142.48.48/28 for policy with local ASN: 64512" component=gobgp.exportPodCIDRReconciler subsys=bgp-control-plane
level=debug msg="create Destination" Nlri=10.142.48.48/28 Topic=Table asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=info msg="Successfully registered GoBGP servers for policy with local ASN 64512" component=gobgp.RouterManager.registerBGPServer subsys=bgp-control-plane
level=debug msg="Successfully completed reconciliation" component=Controller.Run subsys=bgp-control-plane
level=debug msg="IdleHoldTimer expired" Duration=0 Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="state changed" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance new=BGP_FSM_ACTIVE old=BGP_FSM_IDLE reason=idle-hold-timer-expired subsys=bgp-control-plane
level=debug msg="try to connect" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="failed to connect" Error="dial tcp 0.0.0.0:0->10.125.1.8:179: connect: no route to host" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="try to connect" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="failed to connect" Error="dial tcp 0.0.0.0:0->10.125.1.8:179: connect: no route to host" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="Endpoint identity has changed, aborting resolution routine in favour of new one" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1147 identity=1 identityLabels="k8s:bgp-policy=a,k8s:cilium.io/ciliumnode=k8s1,reserved:host" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="try to connect" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="failed to connect" Error="dial tcp 0.0.0.0:0->10.125.1.8:179: connect: no route to host" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="try to connect" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="failed to connect" Error="dial tcp 0.0.0.0:0->10.125.1.8:179: connect: no route to host" Key=10.125.1.8 Topic=Peer asn=64512 component=gobgp.BgpServerInstance subsys=bgp-control-plane
level=debug msg="Endpoint identity has changed, aborting resolution routine in favour of new one" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1147 identity=1 identityLabels="k8s:bgp-policy=a,k8s:cilium.io/ciliumnode=k8s1,reserved:host" ipv4= ipv6= k8sPodName=/ subsys=endpoint




[cilium-sysdump-20220930-162001.zip](https://github.com/cilium/cilium/files/9682183/cilium-sysdump-20220930-162001.zip)
