### ISSUE TITLE
K8s: Add way of reporting errors when importing policy

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2095]
Currently, we have no way of notifying users that import Kubernetes NetworkPolicy objects that the policies were unable to be imported by Cilium. For example, when a user imports a NetworkPolicy object with EgressRules that are label-based, which Cilium currently cannot do at this time, no error is returned to the user. Figure out a way of notifying the user about malformed / disallowed policies.

**Comment by ianvernon** [comment]
@aanm is there a way we can hook into this like we have done with our CRD validation?

**Comment by aanm** [comment]
>@aanm is there a way we can hook into this like we have done with our CRD validation?

No, this is a different subject. What needs to be addressed it what plugins are capable off doing. Kubernetes itself should inform the users if that spec is correct for the given plugins currently installed.
