### ISSUE TITLE
Cilium NAT issue some entries will not be deleted and new entries will not be added

### ISSUE THREAD

**Issue by lzj47010** [cilium/cilium#20982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

cilium bpf nat list |wc -l 
![image](https://user-images.githubusercontent.com/50096566/185528654-6b93cb56-1b5d-4867-a4b6-089f21c643f8.png)

The number of nat entries remains unchanged!

Cluster Node cannot access pod service !
Endpoint

# kubectl get ep -n kube-system -owide|grep gate
gateway                               10.2.0.148:80,10.2.0.148:443 

Service
# kubectl get svc -n kube-system -owide|grep gate
gateway                               NodePort    10.3.211.56    <none>        80:80/TCP,443:443/TCP 

Cluster Node Access
# curl  -I http://10.2.0.148  --connect-timeout 5
curl: (28) Connection timed out after 5001 milliseconds

### Cilium Version

1.9.6 && 1.9.18

### Kernel Version

 5.10.5-051005-generic  x86_64 x86_64 x86_64 GNU/Linux

&&

5.19.1-1.el7.elrepo.x86_64 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.18+
&&
v1.20.9

### Sysdump

[cilium-sysdump-20220819-095953.zip](https://github.com/cilium/cilium/files/9378781/cilium-sysdump-20220819-095953.zip)

### Anything else?

# cilium bpf ct list  global |head -10 
TCP OUT 10.11.81.43:443 -> 10.208.138.0:34858 service expires=189535 RxPackets=0 RxBytes=23 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x16 LastTxReport=167935 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=25 SourceSecurityID=0 IfIndex=0 
TCP OUT 10.208.138.0:6417 -> 10.2.0.148:80 expires=189383 RxPackets=1 RxBytes=74 RxFlagsSeen=0x12 LastRxReport=167783 TxPackets=3 TxBytes=206 TxFlagsSeen=0x16 LastTxReport=167783 Flags=0x0032 [ TxClosing SeenNonSyn NodePort ] RevNAT=23 SourceSecurityID=1 IfIndex=2 
TCP OUT 10.208.138.128:44809 -> 10.2.0.148:443 expires=189284 RxPackets=1 RxBytes=74 RxFlagsSeen=0x12 LastRxReport=167684 TxPackets=3 TxBytes=206 TxFlagsSeen=0x16 LastTxReport=167684 Flags=0x0032 [ TxClosing SeenNonSyn NodePort ] RevNAT=25 SourceSecurityID=1 IfIndex=2 
TCP OUT 10.208.138.0:40092 -> 10.2.0.148:443 expires=189765 RxPackets=1 RxBytes=74 RxFlagsSeen=0x12 LastRxReport=168165 TxPackets=3 TxBytes=206 TxFlagsSeen=0x16 LastTxReport=168165 Flags=0x0032 [ TxClosing SeenNonSyn NodePort ] RevNAT=25 SourceSecurityID=1 IfIndex=2 
TCP OUT 10.11.81.43:443 -> 10.208.138.128:43664 service expires=189607 RxPackets=0 RxBytes=23 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x16 LastTxReport=168007 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=25 SourceSecurityID=0 IfIndex=0 

These entries will not be deleted!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lzj47010** [comment]
The problematic entries are all RevNAT!=0.
# cilium bpf nat list |grep -v "RevNAT=0"|wc -l
Unable to open /sys/fs/bpf/tc/globals/cilium_snat_v6_external: Unable to get object /sys/fs/bpf/tc/globals/cilium_snat_v6_external: no such file or directory. Skipping.
2140

**Comment by aanm** [comment]
@lzj47010 v1.9 is end of life, can you try out a more recent version? Thank you.

**Comment by lzj47010** [comment]
@aanm Cilium v1.10.14 can work normally.Thanks.
