### ISSUE TITLE
How to used Cluster Mesh

### ISSUE THREAD

**Issue by mongoliaredmountain** [cilium/cilium#21010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[A bug happened!](https://docs.cilium.io/en/stable/gettingstarted/clustermesh/clustermesh/#clustermesh)

Hello everyone,how to used cilium Cluster Mesh? This web don't know to read, Who can give me a detailed operation procedure. 

### Cilium Version

1.12.0

### Kernel Version

4.8

### Kubernetes Version

1.23.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
:wave: 

Not sure if you have checked the below pages, please feel free to reach out to Cilium slack OSS for further questions/concern as github issue is normally not best medium for lightweight conversation, not to mention about higher response delay.

Getting started guide: https://docs.cilium.io/en/latest/installation/#cluster-mesh
Troubleshooting guide: https://docs.cilium.io/en/latest/operations/troubleshooting/
