### ISSUE TITLE
Health port 9879 conflict with kasperksy

### ISSUE THREAD

**Issue by kulisse** [cilium/cilium#21063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are setting up a server with cilium and for some reason it wouldn't work at all.

After a bit of investigating we saw that kaspersky antivirus is also using the port 9879.
The server is hosted on our IT infrastructure and every servers are required to have kaspersky installed on them without the possibility of uninstalling it.

The process using the port is kesl and I contacted IT about it but there is apparently no way to change the port used.

### Cilium Version

1.12.0

### Kernel Version

5.4.0-124-generic

### Kubernetes Version

1.24.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Have you checked and try the below helm attribute ?

https://docs.cilium.io/en/latest/helm-reference/#id1


> healthPort | TCP port for the agent health API. This is not the port for cilium-health. | int | 9879
