### ISSUE TITLE
Installation with external etcd - authentication handshake failed: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by JCzz** [cilium/cilium#21074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have k8s and etcd's running and verified:

```
    kubectl version --short
    K8S_VERSION=v1.24.3
    kubeadm config images list --kubernetes-version ${K8S_VERSION}
    ETCD_TAG=3.5.3-0

  HOST=192.168.64.2

  sudo docker run --rm -it \
  --net host \
  -v /etc/kubernetes:/etc/kubernetes k8s.gcr.io/etcd:${ETCD_TAG} etcdctl \
  --cert /etc/kubernetes/pki/etcd/peer.crt \
  --key /etc/kubernetes/pki/etcd/peer.key \
  --cacert /etc/kubernetes/pki/etcd/ca.crt \
  --endpoints https://"$HOST":2379 endpoint health --cluster
```

installing Cilium using helm as described [here](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-external-etcd/#configure-cilium) and added cert secrets also as described.

```
helm install cilium cilium/cilium --version 1.12.1 \
    --namespace kube-system \
    --set etcd.enabled=true \
    --set "etcd.endpoints[0]=192.168.64.2:2379" \
    --set "etcd.endpoints[1]=192.168.64.3:2379" \
    --set "etcd.endpoints[2]=192.168.64.4:2379"
```

I have compared each certificate from etcd and master node/control-plane and they are the same:

```
kubectl create secret generic -n kube-system cilium-etcd-secrets \
      --from-file=etcd-client-ca.crt=/etc/kubernetes/pki/etcd/ca.crt \
      --from-file=etcd-client.key=/etc/kubernetes/pki/apiserver-etcd-client.key \
      --from-file=etcd-client.crt=/etc/kubernetes/pki/apiserver-etcd-client.crt
```

I end up getting this in the logs from the "cilium-operator-" and ongoing restarts:

```
level=info msg="Initialization complete" subsys=cilium-operator-generic
{"level":"warn","ts":"2022-08-24T14:07:17.889Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x40006d5c00/192.168.64.3:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate signed by unknown authority\""}
```

I used kubeadm init phase certs etcd-serve to create the certs as described here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

### Cilium Version

1.12.1

### Kernel Version

Linux master01 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:27:01 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

 kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/arm64"}

### Sysdump

[cilium-sysdump-20220824-162313.zip](https://github.com/cilium/cilium/files/9416898/cilium-sysdump-20220824-162313.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@JCzz are you still facing any issues? I would suggest to double check the certificates that were generated.

**Comment by JCzz** [comment]
Thanks @aanm

Good suggestion, I moved on to not have external etcd and used stacked - it works. I will at some later point try again using external etcd.

**Comment by aanm** [comment]
@JCzz great, feel free to close the issue if you are no longer facing problems

**Comment by JCzz** [comment]
Just a note; this is still an issue if you are using external etcd.
