### ISSUE TITLE
Hubble observe some pods as 'world' entity

### ISSUE THREAD

**Issue by MadMax240484** [cilium/cilium#21083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After some pods recreated, they look like 'world' entity in hubble UI. 
![image](https://user-images.githubusercontent.com/49609951/186645116-db151dcb-1e1e-4caf-abbc-3230db005c47.png)
![image](https://user-images.githubusercontent.com/49609951/186646005-53069044-71b3-4f38-a3a7-95a0673c7053.png)
During troublshooting i found that **all of them** have no "CiliumEndpoint". I use this script (https://github.com/cilium/cilium/blob/master/contrib/k8s/k8s-unmanaged.sh)
This problem occours only with statefulset during relocation pods from one worker1 to worker2.
In case of high k8s API utilization when cilium-agent makes ciliumendpoint deletion request which timed out.  At this time new endpoint is created by clilium-agent with new pod location(worker node2) and only after that old endpoint deleted by cilium-agent on previous location(worker node1).

### Cilium Version

1.10.7

### Kernel Version

4.18.0-305

### Kubernetes Version

1.20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@MadMax240484 This might be another bug caused by https://github.com/cilium/cilium/issues/19931
