### ISSUE TITLE
Helm does not create external workload secrets

### ISSUE THREAD

**Issue by carnerito** [cilium/cilium#21137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After installing Cilium and configuring Cilium clustermesh using Helm `cilium clustermesh vm` commands are failing with an error message:
```Error: Unable to determine status: unable to get secret "clustermesh-apiserver-client-certs" to access clustermesh service: secrets "clustermesh-apiserver-external-workload-certs" not found```

This happens because Cilium Helm chart does not create external workload secrets. I've tested `cronJob` and `helm` certificate provisioning methods.

### Cilium Version

1.12.1

### Kernel Version

5.4.0-81-generic

### Kubernetes Version

1.24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Currently, helm chart didn't support external workload VM, hence it's probably why the mentioned secret is missing.

I am not sure how difficult it is to port logic from cilium-cli to helm chart to support ExternalWorkload VM though.
