### ISSUE TITLE
Integrate k8s prow into cilium/cilium

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#21163]
Goals:
- Automate the label assignments for PRs with the help of comments. Similarly to how it is done in Kubernetes pull requests. Example: https://github.com/kubernetes/kubernetes/pull/112056#issuecomment-1228276122

Non-goals:
- Report the CI test runs with prow

More info:
https://www.youtube.com/watch?v=DBrkSC6nS8A
https://github.com/kubernetes/test-infra/tree/master/prow

**Comment by NikhilSharmaWe** [comment]
Great
Looking forward to working on adding this functionality. I will be looking at the shared resources thoroughly.
