### ISSUE TITLE
v1.12.0 subnetIDsFilter (subnet-ids-filter) cannot be parsed properly on Helm Chart values.

### ISSUE THREAD

**Issue by davidh83110** [cilium/cilium#21179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My Helm Chart values:

```yaml
eni:
  enabled: true
  subnetIDsFilter: "subnet-1234a, subnet-1234b, subnet-1234c"
  updateEC2AdapterLimitViaAPI: true 
  awsReleaseExcessIPs: true 
```

Then I found out only `subnet-1234c` would be parsed in the logs of `cilium-operator` (see below).

```
level=info msg="  --subnet-ids-filter='subnet-1234a,,subnet-1234b,,subnet-1234c'" subsys=cilium-operator-aws

(...ignore)

level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-123xfff name=ip-10-10-205-106.ap-northeast-1.compute.internal subsys=ipam
level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-123xxx name=ip-10-10-217-40.ap-northeast-1.compute.internal subsys=ipam
(...etc)
```

Yes, have you noticed? There are double commas `,` in the end of every subnet IDs, so I tried to following config -- (removed the commas and replaced to spaces.

```yaml
subnetIDsFilter: "subnet-1234a subnet-1234b subnet-1234c"
```

And it worked as expected. 

I think this is a bug that the `cilium-operator` mis-parserd the subnet IDs, please help to verify it, thanks.

### Cilium Version

v1.12.0

### Kernel Version

Linux ip-10-218-232-237.ap-northeast-1.compute.internal 5.4.129-62.227.amzn2.x86_64 #1 SMP Wed Jul 7 00:08:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.20 AWS EKS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
Yes, the ConfigMap format is expecting a space-separated string. That is a limitation of the way we parse it. 

Therefore we should either document this in the Helm values docs, or change the Helm value type to take a list of stings (instead of a single string) and do the conversion to space-separated strings ourselves. PRs welcome.

**Comment by slayer321** [comment]
Hey @gandro , I did like to work on this issue.

**Comment by slayer321** [comment]
Hey @gandro , as you mention that we have two options.. either documenting that we required spaces for that fields or we can make them list of string .. so which one are we looking to go with ?

**Comment by gandro** [comment]
> Hey @gandro , as you mention that we have two options.. either documenting that we required spaces for that fields or we can make them list of string .. so which one are we looking to go with ?

I prefer the latter. It seems using a `join` in Sprig will be sufficient here to maintain backwards compatibility, as it seems to work with plain strings too.
