### ISSUE TITLE
Nightly tests: create small container image for connectivity tests

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2118]
To do tests with large numbers of endpoints, we want to have a small container image which only contains static binaries. It should have:

* statically linked `curl`
* small HTTP server for L7 testing

**Comment by ianvernon** [comment]
this looks promising: https://github.com/PierreZ/goStatic

**Comment by ianvernon** [comment]
@tgraf:

creating a small curl container was fairly simple:

```
$ docker images | grep curl
cilium                                curl                496c635f56a3        About an hour ago   6.72MB
```

However, I am unsure what the requirements of the http server we need are. Can you please elaborate?

**Comment by aanm** [comment]
@ianvernon 
https://github.com/eexit/mirror-http-server
https://hub.docker.com/r/eexit/mirror-http-server/

**Comment by tgraf** [comment]
> However, I am unsure what the requirements of the http server we need are. Can you please elaborate?

Very simple, it needs to respond on either all paths or on a defined list of paths with either `200` or a configurable reply code.

**Comment by ianvernon** [comment]
I've created this container in a separate cilium repository [here](https://github.com/cilium/connectivity-container).
But, I'm hitting #2227 when trying to test it locally, and I want to be sure the container image works in the tests before I close this ticket.
