### ISSUE TITLE
CFP: Support for ingress rules from Kuberentes services -- `fromServices`

### ISSUE THREAD

**Issue by dbanetto** [cilium/cilium#21186]
# Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

## Related to a problem

The problem that has sparked this is:

In a Cilium cluster with default policy enforcement enabled. A pod (e.g. `pod/caller`) is calling a kubernetes service endpoint (`service/foo`) and the pods (`pod/foo-1`) behind that service do complete the TCP handshake. This results in the following event being observed:

```
default/foo:443 <> default/foo-1:56398 Policy denied DROPPED (TCP Flags: SYN, ACK)
```

The workaround currently is to use an `ingress[].fromCIDR: <ip of service/foo>/32` rule as the policy evaluation event shows the entity is `world` so no other matching will work. This is very undesirable as it requires configuration that is cluster dependent and requires finding the service IP address.

The best solution is making use of data that Cilium already has, the `source_service` already exists.

## Related
* similar issue: https://github.com/cilium/cilium/issues/6390
* documentation for egress rules for kuberentes services: https://docs.cilium.io/en/v1.11/policy/language/#services-based

<details>
  <summary>Hubble event in <code>jsonpb</code> format</summary>

  ```json
{
  "flow": {
    "time": "2022-09-02T03:36:27.433015658Z",
    "verdict": "DROPPED",
    "drop_reason": 133,
    "ethernet": {
      "source": "da:a5:77:7c:eb:9f",
      "destination": "de:34:03:d6:27:56"
    },
    "IP": {
      "source": "172.21.199.191",
      "destination": "10.3.129.84",
      "ipVersion": "IPv4"
    },
    "l4": {
      "TCP": {
        "source_port": 443,
        "destination_port": 46252,
        "flags": {
          "SYN": true,
          "ACK": true
        }
      }
    },
    "source": {
      "identity": 2,
      "labels": [
        "reserved:world"
      ]
    },
    "destination": {
      "ID": 275,
      "identity": 815,
      "namespace": "default",
      "labels": [
        "k8s:app.kubernetes.io/name=foo",
        "k8s:component=server",
        "k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default",
        "k8s:io.cilium.k8s.namespace.labels.name=default",
        "k8s:io.cilium.k8s.policy.cluster=default",
        "k8s:io.cilium.k8s.policy.serviceaccount=foo-sa",
        "k8s:io.kubernetes.pod.namespace=default",
        "k8s:statefulset.kubernetes.io/pod-name=foo-1",
      ],
      "pod_name": "foo-1",
      "workloads": [
        {
          "name": "foo",
          "kind": "StatefulSet"
        }
      ]
    },
    "Type": "L3_L4",
    "node_name": "host",
    "event_type": {
      "type": 1,
      "sub_type": 133
    },
    "source_service": {
      "name": "platform-vault-active",
      "namespace": "app"
    },
    "traffic_direction": "INGRESS",
    "drop_reason_desc": "POLICY_DENIED",
    "Summary": "TCP Flags: SYN, ACK"
  },
  "node_name": "host",
  "time": "2022-09-02T03:36:27.433015658Z"
}
  ```
</details>

## Description of the feature

The core feature I would like is:
 * Able to specify an ingress rule that is from a kubernetes service

Extras that would be nice:
 * The ability to further add Layer 4 rules to restrict the inbound port
 * The ability to restrict the Layer 4 to ephemeral port range

## Description of a proposed path to a solution

While using `hubble observe -o jsonpb` the data required to make these decisions seem to be there

```
   ...
    "source_service": {
      "name": "myservice",
      "namespace": "default"
    },
   ...
```

An example policy manifest could be:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "bi-directional-service-rule"
spec:
  endpointSelector:
    matchLabels:
      id: app2
  egress:
  - toServices:
    - k8sService:
        serviceName: myservice
        namespace: default
  ingress:
  - fromServices:
    - k8sService:
        serviceName: myservice
        namespace: default
```

**Comment by dbanetto** [comment]
Bump?

**Comment by aanm** [comment]
> The workaround currently is to use an `ingress[].fromCIDR: <ip of service/foo>/32` rule as the policy evaluation event shows the entity is `world` so no other matching will work.

@dbanetto can you show a hubble output of a cluster running with a policy like that?
