### ISSUE TITLE
Cilium ignores packets received on interface without default route set.

### ISSUE THREAD

**Issue by kvaps** [cilium/cilium#21192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium ignores packets received on interface without default route set.

We have configuration with MetalLB in L2 mode and cilium in kube-proxy free mode.
External packets are coming into vlan interface with no IP assigned (metallb is used to announce arp from this interface)

The graphical scheme:
![image](https://user-images.githubusercontent.com/7556217/188150749-bd66de5a-7590-4be7-ba4b-1b6a89cf1133.png)

It is exactly **case 3** described in my **[Configuring routing for MetalLB in L2 mode](https://itnext.io/configuring-routing-for-metallb-in-l2-mode-7ea26e19219e)** article.

Problem is that cilium only routes external packets received on 192.168.1.0/24 network.
External packets for 1.2.3.4 are ignored for some reason.

Node setup:
```
ip link add link eth0 name eth0.100 type vlan id 100
ip link set eth0.100 up
ip route add 1.2.3.0/24 dev eth0.100 table 100
ip route add default via 1.2.3.1 table 100
ip rule add from 1.2.3.0/24 lookup 100
```

### Cilium Version

v1.12.1

### Kernel Version

5.4.0-86-generic

### Kubernetes Version

v1.22.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kvaps** [comment]
cc @krakazyabra

**Comment by pchaigno** [comment]
Is it packets going to 1.2.3.4 or coming from 1.2.3.4 which are dropped?

You mentioned KPR is enabled. Which devices did you let Cilium manage (`--devices`)?

**Comment by kvaps** [comment]
I guess this is related to https://github.com/cilium/cilium/issues/24252
