### ISSUE TITLE
Ginkgo CI: coalesce tests to only start and remove same containers once

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2119]
See if we can improve the throughput of some the Ginkgo tests by reducing the number of times we start up and bring down containers, especially in the following tests:

* `test/runtime/connectivity.go`
* `test/runtime/Policies.go`

**Comment by eloycoto** [comment]
The problem with that, there is no Teardown hook, it won't be easy :-(
https://github.com/onsi/ginkgo/issues/70

**Comment by eloycoto** [comment]
Some work related with this task: 

PR: https://github.com/cilium/cilium/pull/3059
New issue: https://github.com/cilium/cilium/issues/3109
