### ISSUE TITLE
Upgrade k8s versions in controlplane tests

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#21204]
Kind v0.15.0 was released and some of the k8s images were upgraded as well.

https://github.com/kubernetes-sigs/kind/releases/tag/v0.15.0

Instructions in https://github.com/cilium/cilium/tree/master/test/controlplane#updating-k8s-versions

**Comment by squeed** [comment]
Working on this. Running in to some weird issues in re-generating, probably just something silly with my laptop.

**Comment by squeed** [comment]
heh, turns out having your cable modem randomly sending RSTs will cause weird things to fail.
PR coming shortly.

**Comment by squeed** [comment]
Unfortunately, updating is not so simple; some of the tests have nondetermininism in that they embed pod IPs in the "golden" files. So I'm removing the non-determininism where possible, but some of the files will have to be manually updated.
