### ISSUE TITLE
Remove `bpf.GetMapType()`

### ISSUE THREAD

**Issue by ti-mo** [cilium/cilium#21214]
`MapTypeLRUHash on 4.9 kernel: no prealloc to no prealloc upgrade` in [pkg/bpf/map_linux_test.go](https://github.com/cilium/cilium/blob/1108684e354d2b6ecf66cbaf1cd82de5fa88b70f/pkg/bpf/map_linux_test.go#L591) uses `setMapTypesFromProber()` to force a particular probe result during a map upgrade scenario. Specifically, the probe output is consulted in the call to `GetMapType()` in `bpf.Map.openOrCreate()`.

There are a few problems with this approach:
- A package-level global is used to override the probe result for all map creations globally, inviting bugs and flakes. (and the override is not reverted after the test?)
- This override mechanism is introduced for just this one test.
- This is currently blocking the removal of one `bpftool` shellout in ProbeManager.
- From a distance, it looks like the test might be exercising more than it should. Perhaps it can be removed since it's 4.9-specific?

If this test cannot yet be removed or narrowed down, one option might be to add a method to `bpf.Map` to override the map type it will assign to `mapType` in `Map.openOrCreate()`.

cc @christarazi

**Comment by joestringer** [comment]
For what it's worth, this test is intended to prevent regressions like https://github.com/cilium/cilium/commit/7e5a97f5dddb59394484d401c230cbaba4e6a686. I think that the key question in replacing / rewriting / removing the test will be to understand how to avoid that type of bug in future.

Also worth noting, we plan to discuss kernel version support this Wednesday during the weekly community meeting which will likely impact any decisions around code that supports Linux 4.9.x.
