### ISSUE TITLE
bpf: optimize away dead code in verifier

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#2122]
LLVM doesn't do througout analysis to detect dead code, and there are also potential cases where it's not really possible. Right now the fix for the verifier will only mark with nops and for net + stable kernels it's too much complexity to have a bpf_patch_insn_single() for negative length. Add this into net-next as optimization. Related: http://patchwork.ozlabs.org/patch/840512/

**Comment by jrfastab** [comment]
Just to be sure I read this correctly, you want to do a dead-code detection
pass in the verifier and prune those paths instead of fail outright?

**Comment by borkmann** [comment]
We cannot fail outright as that would break existing programs unfortunately. [1] rewrites them to nops as a fix, but for bpf-next idea would be to optimize it away instead. The changes required to bpf_patch_insn_single() et al are too complex for -stable, though, but we should do that for bpf-next to reduce insn image.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf.git/commit/?id=c131187db2d3fa2f8bf32fdf4e9a4ef805168467

**Comment by borkmann** [comment]
not relevant anymore; will be solved differently.
