### ISSUE TITLE
AWS CNI config not generated upgrading from 1.11.8 to 1.12.1 

### ISSUE THREAD

**Issue by ulagian** [cilium/cilium#21243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello!

I've got an unexpected issue trying to update cilium in an EKS cluster.
It is an EKS cluster updated to Kubernetes 1.23, latest in AWS.
Using cilium 1.11.8 it works fine, using the helm template command with some flags enabled:

But after upgrading to 1.12.1 with the same helm template, the pod is not initialized.

This is the helm export with 1.11.8 that works:

`helm template cilium cilium/cilium --version 1.11.8 \
  --namespace kube-system \
  --set cni.chainingMode=aws-cni \
  --set enableIPv4Masquerade=false \
  --set tunnel=disabled \
  --set kubeProxyReplacement=strict \
  --set k8sServiceHost=xxxxxxxxxxxxxx.yl4.xxxxxxxxxxxxx.eks.amazonaws.com \
  --set k8sServicePort=443 \
  --set bpf.preallocateMaps=true \
  --set ipv6.enabled=false \
  --set nodeinit.enabled=true > cilium-base_1.11.8.yaml`

The helm template that it not works is the next:

`helm template cilium cilium/cilium --version 1.12.1 \
  --namespace kube-system \
  --set cni.chainingMode=aws-cni \
  --set enableIPv4Masquerade=false \
  --set tunnel=disabled \
  --set kubeProxyReplacement=strict \
  --set k8sServiceHost=xxxxxxxxxxxxxx.yl4.xxxxxxxxxxxxx.eks.amazonaws.com \
  --set k8sServicePort=443 \
  --set bpf.preallocateMaps=true \
  --set ipv6.enabled=false \
  --set nodeinit.enabled=true > cilium-base_1.12.1.yaml`

After deploying the manifest, and the pod is not initialized, I can check that the node where the pod is created, has the directory **/etc/cni/net.d** empty and is not creating the needed **/etc/cni/net.d/10-aws.conflist** file.

### Cilium Version

Client: 1.12.1 4c9a630 2022-08-15T16:29:39-07:00 go version go1.18.5 linux/amd64
Daemon: 1.12.1 4c9a630 2022-08-15T16:29:39-07:00 go version go1.18.5 linux/amd64

### Kernel Version

Linux ip-xx-xx-xx-xx.eu-west-1.compute.internal 5.4.209-116.363.amzn2.x86_64 #1 SMP Wed Aug 10 21:19:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.7-eks-4721010", GitCommit:"b77d9473a02fbfa834afa67d677fd12d690b195f", GitTreeState:"clean", BuildDate:"2022-06-27T22:19:07Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20220908-112305.zip](https://github.com/cilium/cilium/files/9526658/cilium-sysdump-20220908-112305.zip)

### Relevant log output

```shell
Exec lifecycle hook ([/cni-install.sh --enable-debug=false --cni-exclusive=true --log-file=/var/run/cilium/cilium-cni.log]) for Container "cilium-agent" in Pod "cilium-xxxx_kube-system(xxxxxxx-xxxx-xxxx-xxxxxx-xxxxxxxxxx)" failed - error: command '/cni-install.sh --enable-debug=false --cni-exclusive=true --log-file=/var/run/cilium/cilium-cni.log' exited with 1: , message: "Installing cilium-cni to /host/opt/cni/bin/ ...\nRemoving active Cilium CNI configurations from /host/etc/cni/net.d})...\nExisting CNI config is required for chaining but does not exist yet, exiting...\n"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
FYI, the Cilium sysdump seems to be missing most information because of a permission issue (see `cilium-sysdump.log`).

**Comment by aanm** [comment]
@mKeRix This seems to be a regression introduced by https://github.com/cilium/cilium/pull/18522/commits/a4083d8a16658288ac338e51b756f7ff99409390. It looks that we didn't take into account that same file installs the CNI configuration later on in https://github.com/cilium/cilium/blob/aed5b1816cb2937b00418e272d2946d2cf86992e/plugins/cilium-cni/cni-install.sh#L193-L227

Can we move the check introduced in https://github.com/cilium/cilium/pull/18522/commits/a4083d8a16658288ac338e51b756f7ff99409390 after installing the AWS or even remove it?

/cc @squeed

**Comment by squeed** [comment]
Taking a look. The script seems to do the right thing on a fresh cluster; now I'm exploring the upgrade case.

**Comment by squeed** [comment]
@ulagian, does your cluster have the `aws-node` DaemonSet?

**Comment by ulagian** [comment]
Hi @squeed,
Yes, exactly!

the cluster has the aws-node DaemonSet running. As I commented with the 11.8 version it worked without issues.

But with this last version, looks like the CNI config file is not created in the cilium nodes.

**Comment by squeed** [comment]
So cilium v1.12 waits for the aws-node daemonset to drop the `10-aws.conflist` CNI configuration file. Now, the configuration space for the VPC CNI is... [large](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html). Do you know why `aws-node` isn't creating that file?

**Comment by mKeRix** [comment]
For the original intention of the script to work it actually needs to be ahead of the file creation further down below, otherwise there is a good chance you will end up with different CNI configs per node (race condition between Cilium and aws-cni). We could replace the wait in that script with an (optional?) init Container in the Helm chart that does the same thing, we’ve actually started doing that to avoid some other issues in our org. I don’t think this would resolve the root cause of this issue though, it could just make the problematic code optional.

We did have it running like this for a while and also ran upgrades fine, however our initial installation already had this code so we might not have hit the problem scenario.

**Comment by squeed** [comment]
Right, the issue is that 1.12 waits for the CNI config to be written by aws-node first, whereas 1.11 didn’t wait.

However, the behavior for 1.12 is correct, since, the CNI config is not something we should be hard-coding.

So, I have a proposed fix (we use the existing Cilium config if it exists), but before it goes in, I’d really like to learn why AWS isn’t writing the CNI config in the cluster in question.

**Comment by squeed** [comment]
Nevermind, I'm wrong -- my fix won't work.

1. we delete the existing file on shutdown
2. if the existing file were there, we'd use it already.

Back to square 1: we need to be able to tell the difference between two cases:

1. aws-node hasn't written 10-aws.conflist to disk _yet_
2. aws-node will never do it for some reason.

**Comment by ulagian** [comment]
Hi @squeed,

I have installed the vpc-cni plugin installed.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/75275924/191773283-b2d52784-9242-43f2-9686-860b543e402b.png">

Respect, to the conflist file, I don't know why, but it looks like Cilium fails and aws-node is not written the file yet.

**Comment by ulagian** [comment]
In addition, I applied again the 1.12.1 version on my cluster and I recreated the nodes, and the result looks like this.

`[garmas@garmas]$ kubectl get pods --all-namespaces
NAMESPACE                        NAME                                            READY   STATUS              RESTARTS      AGE
garmas-testing-prod              garmas-testing-6fc5c45866-khng8                 0/2     Pending             0             19m
garmas-testing-staging           garmas-testing-8547795988-c2jrg                 0/2     Pending             0             18m
kube-system                      aws-load-balancer-controller-66dc598dc6-9h7ln   0/1     Pending             0             20m
kube-system                      aws-load-balancer-controller-66dc598dc6-zr8vt   0/1     Pending             0             20m
kube-system                      aws-node-4gswz                                  0/1     Running             2 (60s ago)   4m25s
kube-system                      aws-node-hfsj5                                  0/1     Running             2 (70s ago)   4m36s
kube-system                      aws-node-hg2td                                  0/1     Running             2 (70s ago)   4m26s
kube-system                      aws-node-r7t6g                                  0/1     Running             2 (70s ago)   4m36s
kube-system                      aws-node-xnzx8                                  0/1     Running             2 (60s ago)   4m26s
kube-system                      aws-node-zsb2f                                  0/1     Running             2 (70s ago)   4m26s
kube-system                      cilium-454ng                                    0/1     CrashLoopBackOff    4 (54s ago)   2m44s
kube-system                      cilium-4szmj                                    0/1     CrashLoopBackOff    4 (48s ago)   2m44s
kube-system                      cilium-4w97t                                    0/1     CrashLoopBackOff    4 (59s ago)   2m44s
kube-system                      cilium-kzk27                                    0/1     CrashLoopBackOff    4 (55s ago)   2m44s
kube-system                      cilium-node-init-jm9mg                          1/1     Running             0             2m44s
kube-system                      cilium-node-init-m4gzj                          1/1     Running             0             2m44s
kube-system                      cilium-node-init-n6qbg                          1/1     Running             0             2m44s
kube-system                      cilium-node-init-q54tr                          1/1     Running             0             2m44s
kube-system                      cilium-node-init-qcz5m                          1/1     Running             0             2m44s
kube-system                      cilium-node-init-v7967                          1/1     Running             0             2m44s
kube-system                      cilium-operator-7744759776-g5jnt                1/1     Running             0             2m44s
kube-system                      cilium-operator-7744759776-grr79                1/1     Running             0             2m44s
kube-system                      cilium-sb8x9                                    0/1     CrashLoopBackOff    4 (56s ago)   2m44s
kube-system                      cilium-xqnjt                                    0/1     CrashLoopBackOff    4 (56s ago)   2m44s
kube-system                      cluster-autoscaler-f9867fcb7-qfmr8              0/1     Pending             0             20m
kube-system                      coredns-8795444d9-9w9f6                         0/1     Pending             0             20m
kube-system                      coredns-8795444d9-xl552                         0/1     Pending             0             20m
kube-system                      k8dash-5c6c8fcff5-5dq6p                         0/1     Pending             0             20m
kube-system                      metrics-server-767585c6cc-q46n7                 0/1     Pending             0             20m
logging                          fluent-bit-h5nbv                                0/1     ContainerCreating   0             19m
logging                          fluent-bit-j54kl                                0/1     ContainerCreating   0             19m
logging                          fluent-bit-m5g8x                                0/1     ContainerCreating   0             18m
logging                          fluent-bit-nq957                                0/1     ContainerCreating   0             18m
logging                          fluent-bit-tbkh4                                0/1     ContainerCreating   0             19m
logging                          fluent-bit-z5gr2                                0/1     ContainerCreating   0             19m`

If I do a describe into an **aws-node** pod I've got readiness issues.
`  Warning  Unhealthy  34s   kubelet, ip-xx-xx-xx-xxx.eu-west-1.compute.internal  Readiness probe failed: {"level":"info","ts":"2022-09-22T15:47:55.246Z","caller":"/usr/local/go/src/runtime/proc.go:250","msg":"timeout: failed to connect service \":50051\" within 5s"}`

And if I go into the node and I do a `tail -f /var/log/aws-routed-eni/ipamd.log | grep error`:
`"Unable to reach API Server, Get \"https://172.20.0.1:443/version?timeout=5s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Then I applied again the 1.11.8 version and recreating the nodes and everything goes fine again:
`[garmas@garmas]$ kubectl get pods --all-namespaces
NAMESPACE                        NAME                                            READY   STATUS             RESTARTS        AGE
garmas-testing-prod              garmas-testing-6fc5c45866-khng8                 2/2     Running            0               24m
garmas-testing-staging           garmas-testing-8547795988-c2jrg                 2/2     Running            0               23m
kube-system                      aws-load-balancer-controller-66dc598dc6-9h7ln   1/1     Running            0               25m
kube-system                      aws-load-balancer-controller-66dc598dc6-xrnsg   1/1     Running            0               11s
kube-system                      aws-node-4gswz                                  1/1     Running            4 (2m45s ago)   9m30s
kube-system                      aws-node-hfsj5                                  1/1     Running            4 (2m53s ago)   9m41s
kube-system                      aws-node-hg2td                                  1/1     Running            4 (2m55s ago)   9m31s
kube-system                      aws-node-r7t6g                                  1/1     Running            4 (2m53s ago)   9m41s
kube-system                      aws-node-xnzx8                                  1/1     Running            3 (4m25s ago)   9m31s
kube-system                      aws-node-zsb2f                                  1/1     Running            4 (2m53s ago)   9m31s
kube-system                      cilium-4885f                                    1/1     Running            0               3m20s
kube-system                      cilium-6t4pl                                    1/1     Running            0               3m20s
kube-system                      cilium-9fwmc                                    1/1     Running            0               3m19s
kube-system                      cilium-gzl74                                    1/1     Running            0               3m19s
kube-system                      cilium-hshbt                                    1/1     Running            0               3m19s
kube-system                      cilium-node-init-7hs24                          1/1     Running            0               2m52s
kube-system                      cilium-node-init-8j7b9                          1/1     Running            0               3m19s
kube-system                      cilium-node-init-j6wj7                          1/1     Running            0               3m13s
kube-system                      cilium-node-init-pjmsl                          1/1     Running            0               3m8s
kube-system                      cilium-node-init-rtttt                          1/1     Running            0               3m3s
kube-system                      cilium-node-init-xbl2h                          1/1     Running            0               2m57s
kube-system                      cilium-operator-86c5f8b797-k2jdl                1/1     Running            0               3m20s
kube-system                      cilium-operator-86c5f8b797-qfxfg                1/1     Running            0               3m20s
kube-system                      cilium-znqfn                                    1/1     Running            0               3m20s
kube-system                      cluster-autoscaler-f9867fcb7-qfmr8              1/1     Running            0               25m
kube-system                      coredns-8795444d9-9w9f6                         1/1     Running            0               25m
kube-system                      coredns-8795444d9-xl552                         1/1     Running            0               25m
kube-system                      k8dash-5c6c8fcff5-5dq6p                         1/1     Running            0               25m
kube-system                      metrics-server-767585c6cc-q46n7                 1/1     Running            0               25m
logging                          fluent-bit-h5nbv                                1/1     Running            0               25m
logging                          fluent-bit-j54kl                                1/1     Running            0               25m
logging                          fluent-bit-m5g8x                                1/1     Running            0               23m
logging                          fluent-bit-nq957                                1/1     Running            0               24m
logging                          fluent-bit-tbkh4                                1/1     Running            0               24m
logging                          fluent-bit-z5gr2                                1/1     Running            0               24m
network                          eks-nginx-ingress-controller-5776754d85-fp9qg   1/1     Running            0               106s
network                          eks-nginx-ingress-controller-5776754d85-n8486   1/1     Running            0               106s`

Looks like Cilium is not allowing the aws-node to write the conflist files or something like this. Because when you go inside the aws-node node, you can see that any conflist file is existing in the /etc/cni/net.d/ directory.

**Comment by squeed** [comment]
Aha, I see the issue: `aws-node` is trying to talk to the k8s apiserver over the service IP, but the service network isn't up yet (because the failing postStart hook is causing it to restart).

The fix is for the postStart hook to wait, rather than fail. I'll have a fix on Monday.
