### ISSUE TITLE
Helm chart looks for `cilium-operator-{generic,aws,azure,alibabacloud}` which are not in the PATH

### ISSUE THREAD

**Issue by stormmore** [cilium/cilium#21268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When trying to deploy Cilium Operator using the Helm into our EKS clusters, we found that it was looking for `cilium-operator-generic` as the command in the Deployment manifest. However that command does not appear in the PATH for the operator container!

We looked more closely, both a the chart and the container and found that cilium-operator-{aws,azure,alibabacloud} also did not appear in the PATH. Along with checking the latest 1.12 version

### Cilium Version

1.12.0 (but 1.12.1 also would fail for the same issue)

### Kernel Version

$ uname -r
5.10.118

### Kubernetes Version

1.21

### Sysdump

[cilium-sysdump-20220909-123329.zip](https://github.com/cilium/cilium/files/9538229/cilium-sysdump-20220909-123329.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@stormmore can you provide the helm values that you are using? Thank you
