### ISSUE TITLE
CFP:  Forward to endpoints ICMP Errors for service NodePort

### ISSUE THREAD

**Issue by sahid** [cilium/cilium#21262]
Certain issues regarding how packets can be handled may happen when dealing with networks, In the case of fragmentation, a networking equipment in the path may accept a smaller packet size than the interface from where the packet is coming from.

Usually that networking equipment will reply using ICMP Error message to inform the sender (in the case of fragmentation) what maximum MTU can be accepted since fragmentation is denied by the DF bit on the ethernet frame.

ICMP Error type 3 is specified by the RFC 792 as follow:

```
Destination Unreachable Message

    0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     Type      |     Code      |          Checksum             |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                             unused                            |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |      Internet Header + 64 bits of Original Data Datagram      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

### Problem Description

Given an endpoint running an http server exposed to the world using a service type NodePort. A client from the world trying to connect to download content from it.

Assuming that, After the TCP connection gets initiated, data gets transferred from the endpoint to the client. Endpoint is sending  packets with maximum size configured by its device. In the path a networking equipment is configured to use a smaller MTU. That networking equipment will reply with an ICMP error type 3 code 4 (fragmentation needed and DF set).

### Proposed Change

After this change, the service NodePort receiving a ICMP Error message need-to-fragment will maintain the route and requested MTU. During egress, It will be able to determine by looking into that list whether packets need to be fragmented. If that is the case, the service NodePort will fragment packets prior to redirecting it to the device.

```
Pod-X      : 172.10.0.10
NodePort-X : 192.168.39.23
Router-X   : 192.168.39.1
Client-X   : 10.1.0.100


                                  +------------+
                                  | Pod-X      |
                                  +------+-----+
   Cilium Host-Y                         |
            ------+-------------+--------+-------------------
                  ||
                  || VxLan
                  ||
                  ||               +------------+
                  ||               | NodePort-X |  192.168.39.0/24 dev eth0
                  ||               +------+-----+
   Cilium Host-X  ||                      |
            ------++------------+---------+-------------------
                                |
   World                        |
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   |  ^
                   |  | ICMP Error Router-Y to NodePort
                   |  |   192.168.39.1/192.168.39.23
                   |  |      with in Payload 192.168.39.23/10.1.0.100
            +-------------+
            | Router-X    |
            +-------------+
                   |
   ----------------+-------+--------
                           |
                         Client-X


Routes
------
10.1.0.100 via 192.168.39.1 MTU 800
```

### Alternative

It has been considered to forward the ICMP Error need-to-fragment to the endpoint that has initiated the error. But this can't work since the endpoint is receiving a SNATed packet. It does not have any idea of the world outside the cluster.

### Implementation

The implementation will consist of building a storage that records routes/MTUs/TTL as-well as implementing a mechanism in nodeport that is fragmenting packets.

```
| Dest       | Via          | MTU | TTL
+------------+--------------+-----+----
| 10.1.0.100 | 192.168.39.1	| 800 | 300
...
```

### Links

https://github.com/cilium/cilium/issues/19720

**Comment by sahid** [comment]
It looks like forwarding the ICMP Error packet to the endpoint is not an option as Cilium’s eBPF NodePort implementation operates in SNAT mode.

Two cases are supportable:

- Using DSR mode, adding the support of forwarding the ICMP Error packet when Cilium is configured to use `loadbalancer.mode=dsr`. As in this DSR mode the backend replies directly to the external client.
_The TCP SYN will be joining the endpoint on the remote backend from the node-external using SNAT, then next packets will be using direct access from backend to the external client. It is expected that the packet which exceeds the MTU will happen during payload transfert._
- Having node-external handling ICMP Error. Using the node-external where the traffic arrives could handle the ICMP Error. For the case of a need to fragment, the route table of the node may be updated and fragment the packet to the external client.

It seems that both of the cases are valuables but I would appreciate any advice as there may exist blockers, work in-progress or better solutions.

**Comment by pchaigno** [comment]
> It looks like forwarding the ICMP Error packet to the endpoint is not an option as Cilium’s eBPF NodePort implementation operates in SNAT mode.

Could you explain a bit why SNATing is an issue here?

> The TCP SYN will be joining the endpoint on the remote backend from the node-external using SNAT, then next packets will be using direct access from backend to the external client.

Is that part of your first proposed approach? So in DSR mode we would still SNAT some packets? I don't think that's an acceptable solution for users given SNAT mode is often used to preserve the source IP.

**Comment by sahid** [comment]
> > It looks like forwarding the ICMP Error packet to the endpoint is not an option as Cilium’s eBPF NodePort implementation operates in SNAT mode.
> 
> Could you explain a bit why SNATing is an issue here?

For a given packet initiated by a external client arriving to a service nodeport, it will be SNATed to the remote backend that handles the targeted endpoint.

The source addr of the packet arriving to endpoint will be the addr of the node. If we let endpoint handling the ICMP Error it will consider it for the path `node -> endpoint` in opposite to `client -> endpoint`.

If we consider a need to fragment error reported, the MTU will be reduced for all the traffic that is passing through this path.

```
  client:         10.1.0.100
  router:         192.168.63.1
  nodeport:       192.168.63.100
  node:           10.0.128.10
  remote backend: 10.0.128.20
  endpoint:       10.0.90.12

  The client (10.1.0.100) is initiating a 3-way handshake going
  through service NodePort (192.168.63.100), then data are sent from
  endpoint to client but a networking equipement (192.168.63.1) in the
  networking path is repporting an ICMP Error need to frag.

  The networking equipment (192.168.63.1) is responding with an ICMP
  Error need to frag for a packet trying to join client at
  (10.1.0.100)

  192.168.63.1 -> 192.168.63.100        a)
       10.0.128.10 -> 10.0.128.20       b)
            10.0.128.10 -> 10.0.90.12   c)

 a) Networking equipement (192.168.63.1) reply an ICMP Error to 192.168.63.100
 b) Node (10.0.128.10) SNAT and DNAT the packet to join remote backend (10.0.128.20)
 c) Remote backend (10.0.128.20) route the packet to endpoint (10.0.90.12)
```

The ICMP Error received for a reply to client 10.1.0.100 by endpoint will be for 10.0.128.10 in opposite to 192.168.63.1.

**Comment by sahid** [comment]
The aim would be for SNAT mode to remove the (b) step by having the node handling the ICMP Error by itself. For DSR mode, adding support of xlateing the ICMP Error to endpoint.

**Comment by pchaigno** [comment]
> in DSR mode we only SNAT the SYN packet from node to remote backend

In DSR mode, we don't SNAT anything AFAIK. The SYN packet can be a bit different because [it carries the service IP & port in the IP options](https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/#dsr-mode) but it is not SNATed.

**Comment by sahid** [comment]
Right my mistake, not sure why I had stick this in my head. The point is to have the remote backend replying and the ICMP error directed to it when generated from the networking equipment.

**Comment by sahid** [comment]
Thinking out loud, for the native SNAT mode (opposite to any DSR mode), we could certainly just skip SNATing the ICMP Error packet arriving as no reply is expected, that would certainly be better than the original proposal to make the node itself handling it.
