### ISSUE TITLE
Deny egress to a specific external hostname except from certain Pods

### ISSUE THREAD

**Issue by seanuleh** [cilium/cilium#21272]
I am trying to write a policy that denies network traffic to an endpoint that lives outside of the cluster, except from a specific pod within the cluster. All other egress traffic should be allowed.

To be clear, say the external endpoint is restricted.com;
- Only a specific pod that I would like to select by labels should be able to access restricted.com
- All other egress on that specific pod should be allowed
- All other egress on other pods should be allowed

The external service uses static IP's so using IP's in the policy would be okay. Is this possible with Cilium Network Policies?

**Comment by aanm** [comment]
@seanuleh Yesm see https://docs.cilium.io/en/v1.12/policy/language/#deny-policies
