### ISSUE TITLE
egress ip = 0.0.0.0 Except for the elected node

### ISSUE THREAD

**Issue by osaffer** [cilium/cilium#21289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

I try to use egress functionality. 

It is been enabled : 

helm upgrade cilium cilium/cilium \
   --namespace kube-system \
   --reuse-values \
   --set egressGateway.enabled=true \
   --set bpf.masquerade=true \
   --set kubeProxyReplacement=strict \
   --set l7Proxy=false

kubectl rollout restart ds cilium -n kube-system
kubectl rollout restart deploy cilium-operator -n kube-system

I am doing the simple test described in the documentation.

- Problem is that any pods can access the external site
- All nodes excepted the elected node dont receive  egressip 
- Cannot verify if egress is really used
Thank you

### Cilium Version

cilium version
Client: 1.12.1 4c9a630 2022-08-15T16:29:39-07:00 go version go1.18.5 linux/amd64
Daemon: 1.12.1 4c9a630 2022-08-15T16:29:39-07:00 go version go1.18.5 linux/amd64

### Kernel Version

5.4.0-124-generic #140-Ubuntu SMP 

### Kubernetes Version

kubectl version --short
Client Version: v1.23.10
Server Version: v1.23.10

### Relevant log output

```shell
log pod cilium on ALL nodes except NODE4

level=info msg="Added CiliumEgressNATPolicy" ciliumEgressNATPolicyName=egress-sample subsys=egressgateway
level=info msg="Egress gateway policy applied" destinationCIDR=IP_DESTINATION/32 egressIP=0.0.0.0 gatewayIP=IPNODE4 sourceIP=10.0.1.143 subsys=egressgateway

And : 
log pod cilium on NODE4

level=info msg="Added CiliumEgressNATPolicy" ciliumEgressNATPolicyName=egress-sample subsys=egressgateway
level=info msg="Egress gateway policy applied" destinationCIDR=IP_DESTINATION/32 egressIP=IPNODE4 gatewayIP=IPNODE4 sourceIP=10.0.1.143 subsys=egressgateway


----

for i in $ciliums; do echo "==== $i ====";kubectl exec $i -c cilium-agent -n kube-system -- cilium bpf egress list; done
==== cilium-425q5 ====
Source IP    Destination CIDR     Egress IP   Gateway IP
10.0.1.143   IP_DESTINATION/32   0.0.0.0     IPNODE4 
==== cilium-cqjrb ====
Source IP    Destination CIDR     Egress IP   Gateway IP
10.0.1.143   IP_DESTINATION/32   0.0.0.0     IPNODE4 
==== cilium-dz99z ====
Source IP    Destination CIDR     Egress IP   Gateway IP
10.0.1.143   IP_DESTINATION/32   0.0.0.0     IPNODE4 
==== cilium-gjpdb ====
Source IP    Destination CIDR     Egress IP      Gateway IP
10.0.1.143   IP_DESTINATION/32   10.224.139.4   IPNODE4 

---
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Could you share a sysdump or at least the egress NAT policy you've used? 

> * Problem is that any pods can access the external site

Why is that a problem?

> * All nodes excepted the elected node dont receive  egressip

By elected node, do you mean the egress gateway node? So all nodes except the egress gateway node are assigned an egress IP? How did you assign the egress IP?

> * Cannot verify if egress is really used

Do you mean you can't verify if packets egress through the egress gateway or do you mean you can't verify if they egress with the appropriate egress IP?

**Comment by osaffer** [comment]
Hello

Thanks for your reply.

Yesterday I have installed the new release 1.12.2.
helm list -n kube-system
NAME  	NAMESPACE  	REVISION	UPDATED                                 	STATUS  	CHART        APP VERSION
cilium	kube-system	3       	2022-09-20 10:06:32.582777103 +0200 CEST	deployed	cilium-1.12.21.12.2     



helm install cilium cilium/cilium -n kube-system --set securityContext.privileged=true 
helm upgrade cilium cilium/cilium    --namespace kube-system    --reuse-values    --set egressGateway.enabled=false    --set bpf.masquerade=false    --set kubeProxyReplacement=strict    --set l7Proxy=false

This is the egress file: 
cat cilium-egress2.yaml
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-external-service
spec:
  # Specify which pods should be subject to the current policy.
  # Multiple pod selectors can be specified.
  selectors:
  - podSelector:
      matchLabels:
        org: empire
        class: mediabot
        # The following label selects default namespace
        io.kubernetes.pod.namespace: default

  # Specify which destination CIDR(s) this policy applies to.
  # Multiple CIDRs can be specified.
  destinationCIDRs:
  - "IP_EXTERNAL_SERVICE/32"

  # Configure the gateway node.
  egressGateway:
    # Specify which node should act as gateway for this policy.
    nodeSelector:
      matchLabels:
        egress-node: NODE_NAME

    # Specify the IP address used to SNAT traffic matched by the policy.
    # It must exist as an IP associated with a network interface on the instance.
    egressIP: IP_NODE

Now the situation is even worst, in the log I only see:

level=warning msg="CiliumEgressNATPolicy is deprecated and will be removed in version 1.13. Use CiliumEgressGatewayPolicy instead." subsys=klog

Quite strange warning as I use well CiliumEgressGatewayPolicy, and I dont see anymore the configuration loaded:

 cilium bpf egress list
No entries found.

kubectl get ciliumegressgatewaypolicies.cilium.io
NAME         AGE
egress-external-service   107s

Cilium configuration : 

kubectl get cm cilium-config -n kube-system -o yaml
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-sock: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: default
  cluster-pool-ipv4-cidr: 10.0.0.0/8
  cluster-pool-ipv4-mask-size: "24"
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-egress-gateway: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "false"
  enable-local-redirect-policy: "false"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: cluster-pool
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: vxlan
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2022-09-20T08:06:33Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cilium-config
  namespace: kube-system
  resourceVersion: "718404423"
  uid: 06e0b65f-6cf6-46c6-a956-5cf8f7b27e96

**Comment by pchaigno** [comment]
> Quite strange warning as I use well CiliumEgressGatewayPolicy, and I dont see anymore the configuration loaded:

Hm, weird :thinking: Could you share a sysdump of the cluster?

**Comment by osaffer** [comment]
I would not prefer to share a sysdump. Is it possible to investigate differently ?

**Comment by pchaigno** [comment]
Short of me asking for every single egress-gateway-related state one by one, I don't think so, no. You can also contact [one of the companies providing paid support](https://cilium.io/enterprise/) if it's a matter of getting reassurances on how the private data will be handled.

**Comment by osaffer** [comment]
I also noticed when I did a helm upgrade with new paramter, the configmap was not updated. So I needed to delete it, and reperform the upgrade.

Otherwise in my last test: 

I have installed with the full command: 

helm install cilium cilium/cilium -n kube-system --set securityContext.privileged=true  --set ipam.mode=cluster-pool --set ipam.operator.clusterPoolIPv4PodCIDRList=172.20.0.0/12 --set ipam.operator.clusterPoolIPv4MaskSize=12 --set egressGateway.enabled=true --set bpf.masquerade=true --set kubeProxyReplacement=strict --set l7Proxy=false --set hubble.relay.enabled=true    --set hubble.ui.enabled=true

**Comment by osaffer** [comment]
I would like to configure an EgressGroup as it is possible with EgressNatPolicy.

I am quite confused, because I do not see in the documentation such as possibility with EgressGatewayPolicy.
Can you clarify if it is possible ? 

apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-gw-nat-policy
spec:
  destinationCIDRs:
    - 10.2.0.0/16
  egress:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: egress-gw-monitor
          io.kubernetes.pod.namespace: cilium-egress-gateway
  egressGroups:
    - egressIP: 10.2.200.10
      nodeSelector:
        matchLabels:
          io.cilium/egress-gateway: 'true'
          topology.kubernetes.io/zone: us-west-2a
    - egressIP: 10.2.201.10
      nodeSelector:
        matchLabels:
          io.cilium/egress-gateway: 'true'
          topology.kubernetes.io/zone: us-west-2b
    - egressIP: 10.2.202.10
      nodeSelector:
        matchLabels:
          io.cilium/egress-gateway: 'true'
          topology.kubernetes.io/zone: us-west-2c
    - egressIP: 10.2.203.10
      nodeSelector:
        matchLabels:
          io.cilium/egress-gateway: 'true'
          topology.kubernetes.io/zone: us-west-2d

**Comment by pchaigno** [comment]
It is not.
