### ISSUE TITLE
CFP: Improve Cilium Metrics Documentation 

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#21343]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

The Cilium metrics documentation is not up to date with the state of Cilium source code (both for master and release branches).
Many metrics are documented but have incomplete descriptions and are missing label documentation (see: `proxy_upstream_reply_seconds`). 

Some default metrics have their documentation missing completely (see: [policy_update_call_duration](https://github.com/cilium/cilium/blob/master/pkg/metrics/metrics.go#L1313)).

Currently it is up to the developers/code-reviewers to ensure that changes to metrics are correctly documented. There is no automated check to ensure that documentation is kept up to date (for example, here is a [PR I merged that made changes to metrics declarations without documentation changes](https://github.com/cilium/cilium/pull/19991)).
The result is that it is easy have the documentation become out of date over time.

**Describe the feature you'd like**

I would like to be able to have metrics documentation be generated automatically so that it is always up to date. Ideally, I would like it if the [documentation](https://github.com/cilium/cilium/blob/master/Documentation/observability/metrics.rst) was generated from source code and checked via CI to ensure that it is up to date (i.e. something like `make generate-metrics-docs`)

Changes to metrics instantiation should be diffed against existing documentation to ensure that it is up to date. Ensuring that documentation is up to date should be a requirement for merging a pull request.

**(Optional) Describe your proposed solution**

Proposal: We refactor pkg/metrics.go such that we have a wrapper function for initializing each metric type, for example (just a rough idea for now, this may change, suggestions are welcome):

**NOTE:** This is just a prototype of what this might look like, this may change to suite our needs.
```go
EndpointRegenerationTimeStats = metrics.NewCounterVec(
	prometheus.CounterOpts{ // counter options
		Namespace: Namespace,
		Name:      "endpoint_regenerations_total",
		Help:      "Count of all endpoint regenerations that have completed, tagged by outcome",
	},
	Labels{
		{
			Name: "outcome",
			Description: "Outcome result of the endpoint generation",

			// note: just an example, this particular one requires more.
			// Known possible label values.
			// *Optional: May be difficult to do for dynamic labels (i.e. API endpoint label for API metrics).
			KnownValues: []string{models.EndpointStateReady, models.EndpointStateWaitingToRegenerate},
		},
		// etc...
	},
	CiliumMetricMetadata{
               // Type for different known types of metric classifications (i.e. the sections you see in metrics.rst docs)
               // For example: Endpoint, Clustermesh, BPF.
               // Can also contain metadata if necessary
               MetricType: metrics.Endpoint,

		// EnabledByDefault sets whether to enable this without a flag parameter, useful also for generating documentation.
		//
		// TODO: Figure out how to reconcile this against the runtime metric flags which can enable/disable metrics via CLI flags.
               EnabledByDefault: true,

		// Long form description used for generating documentation.
               Description: "Count of all endpoint regenerations that have been completed, tagged by the outcome. Useful when determining if endpoints are being regenerated correctly. Results with labels that are not " + models.EndpointStateReady + " may indicate a problem with the datapath",
	}
)
```

This refactoring would allow us to register metrics in the Prometheus collectors, as well as register metadata about the metric during init.
Furthermore, we would make the metrics package modular (i.e. no dependencies on Cilium runtime), which would allow it to be consumed as a versioned library by a special Go application that imports `github.com/cilium/cilium/pkg/metrics` and used to template out either some intermediary document (i.e. a JSON file) which is used to template the reStructuredText metrics documentation. Or we could just template the documentation rst files directly (i.e. metrics.rst).

Existing Cilium metric flags would still allow enabling disabled by default flags.

Finally, would have a make target (i.e. something like `make generate-metrics-docs`) that performs this templating. Changes to metrics declarations would be accompanied by a commit containing regenerated metrics documentation.
Pull requests would run a CI check that would generate the documentation and perform a diff to see if the doc generation had been committed.

**Comment by lambdanis** [comment]
As an inspiration/datapoint: we recently introduced autogenerated metrics documentation for Tetragon.
PR: https://github.com/cilium/tetragon/pull/2164
docs: https://tetragon.io/docs/reference/metrics/

It's using this little tool: https://github.com/isovalent/metricstool. It iterates over the Prometheus registry - so to generate the metrics docs we don't have to start the agent but we have to register all metrics and initialize them with all label values. Using it in Cilium would require #27834, I'm not sure what's the current status. Also, documenting metrics with unknown label values (e.g. all Hubble metrics) requires a different approach. In Tetragon, we currently initialize them separately when generating docs, with example label values - see also https://github.com/isovalent/metricstool/issues/8.
