### ISSUE TITLE
Ephemeral ports of an egress ip may be exhausted in NAT mapping table

### ISSUE THREAD

**Issue by skyblueted** [cilium/cilium#21346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We observed drop SYN packet in cilium pod of **egress gateway**, and reason was "**No mapping for NAT masquerade**".
After received the error message, we show the **nat mapping** table by filtering a egress ip, specific target and target port.

>Cilium nat table information likes below
> cilium bpf nat list | grep '[target ip]:[target port]' | grep 'XLATE_SRC' | sort -k7
> TCP OUT xxx.xxxx.xxx.xxx:32768 -> [target ip]:[target port] XLATE_SRC [egress ip]:**32768** Created=2719514sec HostLocal=0
>.
>.
>.
>TCP OUT xxx.xxxx.xxx.xxx:32768 -> [target ip]:[target port] XLATE_SRC [egress ip]:**60999** Created=2719514sec HostLocal=0

Thus, we guess the ephemeral ports of a specific egress ip are exhausted, and source ports of egress ip would not be recycled/deleted in nat mapping table after a period of time.
Is there maybe a bug or garbage collect is not working?

### Cilium Version

1.11.8

### Kernel Version

5.13.0-40-generic

### Kubernetes Version

v1.21.14

### Anything else?

Scenario:
![image](https://user-images.githubusercontent.com/79855132/190838445-0aa56ce4-e07b-4204-81ad-092d604eb42a.png)

**How to reproduce?**

1. Create a web service in cluster outside.
2. Deploy a pod which can use curl command and apply CiliumEgressNATPolicy through egress ip to web service.
3. Execute bash command in the pod.
    Repeat curl web service until total of running times exceed **_28231_**.
   (Hint: ephemeral port range: net.ipv4.ip_local_port_range = 32768    60999)
   `for i in {1..5000}; do [[ $(( $i % 1000 )) -eq 0 ]] && echo $i; curl -sI target ip]:[target port] > /dev/null; done &`

4. In cilium pod of egress gateway, you can observe nat mapping variation.
>cilium bpf nat list | grep '[target ip]:[target port]' | grep 'XLATE_SRC' | sort -k7
>TCP OUT xxx.xxxx.xxx.xxx:32768 -> [target ip]:[target port] XLATE_SRC [egress ip]:32768 Created=2719514sec HostLocal=0
>.
>.
>.
>TCP OUT xxx.xxxx.xxx.xxx:32768 -> [target ip]:[target port] XLATE_SRC [egress ip]:60999 Created=2719514sec HostLocal=0`

5. Create another pod and also curl same target and destination port,
We would receive error msg: "reason No mapping for NAT masquerade" from cilium pod of egress gateway node.
(e.g. cilium monitor -t drop -vv)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skyblueted** [comment]
Hi @jibi 👋
 In our environment, we have enabled **hybrid** mode in "--bpf-lb-mode"
Our configmap file is below attachment:
[cilium_cm.txt](https://github.com/cilium/cilium/files/9626108/cilium_cm.txt)

Recently, we found a way to easily reproduce.
1. Create two nginx pods in the same namespace.
2. Execute bash command in the one of pod (Successfull rate: 100%)
    `for i in {32768..65535}; do [[ $(( $i % 10 )) -eq 0 ]] && echo $i; curl -s -m1 [target ip]:[target port] --local-port $i  > /dev/null; done`
3. After step2 is finished, enter to cilium pod of egress gateway, you can observe 32768 entries are created in nat mapping.
 `cilium bpf nat list | grep '[target ip]:[target port]' | grep 'XLATE_SRC' | sort -k7 | wc -l  => 32768`
4. Now, go to another nginx pod, and just curl same [target]:[target port]
We could receive error msg: "reason No mapping for NAT masquerade" from cilium pod of egress gateway node.

We also saw **nat_fill_up** counter is increasing in cilium metrics, but value of **cilium_datapath_conntrack_gc_entries is zero**
```
root@/home/cilium#cilium metrics list | grep signal
cilium_datapath_signals_handled_total                 data="ipv4" signal="nat_fill_up" status="received"    2963.000000
root@/home/cilium# cilium metrics list | grep gc
cilium_datapath_conntrack_gc_duration_seconds         protocol="TCP" status="completed" family="ipv4"        357.261969
cilium_datapath_conntrack_gc_duration_seconds         family="ipv4" protocol="non-TCP" status="completed"    107.921936
cilium_datapath_conntrack_gc_entries                  status="alive" family="ipv4" protocol="TCP"            37635.000000
cilium_datapath_conntrack_gc_entries                  family="ipv4" protocol="TCP" status="deleted"          0.000000
cilium_datapath_conntrack_gc_entries                  family="ipv4" protocol="non-TCP" status="alive"        8604.000000
cilium_datapath_conntrack_gc_entries                  protocol="non-TCP" status="deleted" family="ipv4"      0.000000
cilium_datapath_conntrack_gc_key_fallbacks_total      family="ipv4" protocol="TCP"                           0.000000
cilium_datapath_conntrack_gc_key_fallbacks_total      family="ipv4" protocol="non-TCP"                       0.000000
cilium_datapath_conntrack_gc_runs_total               status="completed" family="ipv4" protocol="TCP"        3143.000000
cilium_datapath_conntrack_gc_runs_total               family="ipv4" protocol="non-TCP" status="completed"    3143.000000
```

Finally, we suspect  root cause of garbage collect is failure due to these range of codes
https://github.com/cilium/cilium/blob/ff1ed9337d62bc3d4d5f7afd0fdc58b25f2eec13/pkg/maps/ctmap/ctmap.go#L559-L588

**Comment by jibi** [comment]
Thanks for the detailed repro @skyblueted!
I'll take a look at the CT logic to see how we can fix it

**Comment by jibi** [comment]
After taking another look, `--bpf-lb-mode=hybrid` only explains half of the story (GC not deleting those orphaned NAT entries), but those NAT entries should normally get deleted when the related CT entry is deleted (which is what I'm observing as well in my reproduction environment)

**Comment by brb** [comment]
@skyblueted Could you check whether all `cilium bpf nat list` entries have corresponding `cilium bpf ct list global` entries?

**Comment by skyblueted** [comment]
Hello @brb @jibi  ,
I only saved some partial logs like these.
`root@bastion:~# k1c exec -ti cilium-9jt68 -- cilium bpf nat list | grep 192.168.1.11 | grep OUT | sort -k7 | wc -l
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)`
**28106**

**In a couple of days**, we still saw 28106 entries are existed in NAT table
`root@:/home/cilium# cilium bpf ct list global | grep 192.168.1.11`    // get empty result from CT
`root@:/home/cilium# cilium bpf nat list | grep 192.168.1.11:8080 | grep OUT | wc -l`
**28106**

_// Flush NAT table_
`root@:/home/cilium# cilium bpf nat flush
Flushed 72684 entries from /sys/fs/bpf/tc/globals/cilium_snat_v4_external`

_//  We restart to  simulation again after flushing NAT table._
`root@:/home/cilium# cilium bpf nat list | grep 192.168.1.11:8080 | grep OUT | sort -k7 | head
TCP OUT 172.20.13.168:32774 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32774 Created=1397326sec HostLocal=0
TCP OUT 172.20.13.168:32780 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32780 Created=1397326sec HostLocal=0
TCP OUT 172.20.13.168:32786 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32786 Created=1397326sec HostLocal=0
TCP OUT 172.20.13.168:32790 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32790 Created=1397326sec HostLocal=0
TCP OUT 172.20.13.168:32794 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32794 Created=1397326sec HostLocal=0
TCP OUT 172.20.13.168:32798 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32798 Created=1397326sec HostLocal=0
TCP OUT 172.20.13.168:32802 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32802 Created=1397326sec HostLocal=0
TCP OUT 172.20.13.168:32806 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32806 Created=1397326sec HostLocal=0
TCP OUT 172.20.13.168:32812 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32812 Created=1397326sec HostLocal=0
TCP OUT 172.20.13.168:32816 -> 192.168.1.11:8080 XLATE_SRC 10.2.2.1:32816 Created=1397326sec HostLocal=0`

`root@:/home/cilium# cilium bpf nat list | grep 192.168.1.11:8080 | grep OUT | sort -k7 | wc -l`
**9114**

`root@:/home/cilium# cilium bpf nat list | grep 192.168.1.11:8080 | grep OUT | sort -k7 | wc -l`
**9779**

`root@:/home/cilium# cilium bpf ct list global | grep 192.168.1.11`   // get empty result from CT
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
We hope these information can inspire you.
our initial log of cilium agent([cilium_init.log](https://github.com/cilium/cilium/files/9635265/cilium_init.log))

BTW, we got an interesting result in another scenario today.
If we just communicate to outside would by native routing **without egress ip**, we would see CT & NAT entries are increasing.
It means two pods are existed in the same worker node, and translate pod ip to node ip before communicating to outside.
Select one pod to deplete all source ports from 32768 to 65535, and switch over to another pod for test connectivity 
Command:
`for i in {32768..65535}; do [[ $(( $i % 10 )) -eq 0 ]] && echo $i; curl -s -m1 [target ip]:[target port] --local-port $i > /dev/null; done`
Finally, we observed the **entries were deleted** in NAT table, even if one of pod had preempt 32768~65535 ports once.

We are not sure whether exceptional behavior is related to outgoing traffic through egress ip or not.

**Comment by jibi** [comment]
Reproduced :white_check_mark: 
```
vagrant@k8s1:~$ cilium metrics list -p signals
Metric                                  Labels                                               Value
cilium_datapath_signals_handled_total   data="ipv4" signal="nat_fill_up" status="received"   710.000000
```

I'll look into fixing `ctmap.PurgeOrphanNATEntries()` now

**Comment by skyblueted** [comment]
That's awesome! Many thanks for the prompt reply.
