### ISSUE TITLE
Pod interface missing bpf_lxc to-container program resulting in dropped packets

### ISSUE THREAD

**Issue by hemanthmalla** [cilium/cilium#21345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We noticed that some of our pods are missing the `to-container` bpf_lxc program, which can cause weird connectivity issues. We ran `execsnoop` and `exitsnoop` on the node and noticed that cilium was actually executing `tc filter replace` commands. According to exitsnoop all `tc` commands had `0` return code, but the interface does not have the program attached.

```
root@<>:/home/<># execsnoop.bt | grep 'tc filter'
68573      850550 tc filter replace dev lxcb187183beddd ingress prio 1 handle 1 bpf da obj 57_next/bpf_lxc.o sec from-container
68646      850554 tc filter replace dev lxcb187183beddd egress prio 1 handle 1 bpf da obj 57_next/bpf_lxc.o sec to-container
```

```
root@<>:/home/cilium# tc filter show dev lxcb187183beddd egress
root@<>:/home/cilium# tc filter show dev lxcb187183beddd ingress
filter protocol all pref 1 bpf chain 0
filter protocol all pref 1 bpf chain 0 handle 0x2 classifier_ingress_security380_4026531992_2115 direct-action not_in_hw id 4491 tag 59904229c5a1f55d jited
filter protocol all pref 1 bpf chain 0 handle 0x1 bpf_lxc.o:[from-container] direct-action not_in_hw id 4481 tag 18a10b547e2fa35f jited
```

```
root@<>:/home/cilium# bpftool net list | grep lxcb187183beddd
lxcb187183beddd(380) clsact/ingress classifier_ingress_security380_4026531992_2115 id 4491
lxcb187183beddd(380) clsact/ingress bpf_lxc.o:[from-container] id 4481
```

```
# On Host
root@<>:/home/<># tc -V
tc utility, iproute2-ss200127

root@<>:/home/cilium# tc -V
tc utility, iproute2-ss190107
```

Here's the log line to confirm that this endpoint needed egress prog.
```
level=info msg="Create endpoint request" addressing="&{<> 1e0ae141-361b-11ed-8bc1-069f563a36f6  }" containerID=9596f370d8628353c7ffff63283bd06001755843442f61364f24069cb6c68b60 datapathConfiguration="&{false true false true 0xc00a1f8010}" interface=lxcb187183beddd k8sPodName=<> labels="[]" subsys=daemon sync-build=true
```

Could there be any weirdness between the tc and kernel versions that can cause the program attachment to silently fail ? Manually re-running the same `tc filter replace` command attaches the program and connectivity issues are resolved though.

### Cilium Version

Client: 1.8.7 95b99123a4 2022-09-16T16:33:52-04:00 go version go1.16.3 linux/amd64
Daemon: 1.8.7 95b99123a4 2022-09-16T16:33:52-04:00 go version go1.16.3 linux/amd64

### Kernel Version

Linux <> 5.13.0-1017-aws #19~20.04.1-Ubuntu SMP Mon Mar 7 12:53:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.9-dd.1", GitCommit:"f71f8bd315fe5d6d7d44b619bd9364362fb8d9a8", GitTreeState:"clean", BuildDate:"2021-08-06T21:03:07Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Did you check if the latest and/or stable Cilium versions are affected as well? We've changed the way we load programs for v1.13 so maybe v1.12 is affected but master isn't?

**Comment by pchaigno** [comment]
Given the presence of `classifier_ingress_security380_4026531992_2115` on the same device, this could be very likely related to the bug Daniel presented at LPC last week: https://lpc.events/event/16/contributions/1353/.

**Comment by borkmann** [comment]
I think you might need to set it the other way round.. configure Cilium with handle 0x2 (there's a hidden agent config: https://github.com/cilium/cilium/pull/18896) and the datadog agent as handle 0x1 where it must return TC_ACT_UNSPEC in their program, so that Cilium isn't bypassed.
```
filter protocol all pref 1 bpf chain 0 handle 0x2 classifier_ingress_security380_4026531992_2115 direct-action not_in_hw id 4491 tag 59904229c5a1f55d jited
filter protocol all pref 1 bpf chain 0 handle 0x1 bpf_lxc.o:[from-container] direct-action not_in_hw id 4481 tag 18a10b547e2fa35f jited
```
We ran into something similar recently (see Paul's pointer to the LPC talk).
