### ISSUE TITLE
CI: ConformanceGKE: timeout waiting for flow listener

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#21351]
ConformanceGKE is very often failing with:
```
🟥 Timeout waiting for flow listener to become ready
```
It happens in different parts of the connectivity tests such as `no-policies` or `to-fqdns`.

Examples:
https://github.com/cilium/cilium/actions/runs/3080816315/jobs/4978620184
https://github.com/cilium/cilium/actions/runs/3004747311/jobs/4824317010
https://github.com/cilium/cilium/actions/runs/3000791720/jobs/4816065201
https://github.com/cilium/cilium/actions/runs/3003020094/jobs/4820866453

Sysdump: 
[cilium-sysdump-out.zip.zip](https://github.com/cilium/cilium/files/9597548/cilium-sysdump-out.zip.zip)

**Comment by joestringer** [comment]
Possibly also related: https://github.com/cilium/cilium/issues/20904.

I also hit this error in a recent flake on aws-cni job, `no-policies/pod-to-local-nodeport/curl-0`. Rerunning the job made the test pass. The PR was https://github.com/cilium/cilium/pull/21414:

https://github.com/cilium/cilium/actions/runs/3109088749/jobs/5038981805

```
[=] Test [no-policies]
.
  [-] Scenario [no-policies/pod-to-local-nodeport]
  [.] Action [no-policies/pod-to-local-nodeport/curl-0: cilium-test/client-7bdbddd7b-dpflr (192.168.137.145) -> cilium-test/echo-other-node (echo-other-node:8080)]
  🟥 Timeout waiting for flow listener to become ready
```

**Comment by pchaigno** [comment]
Closing in favor of https://github.com/cilium/cilium-cli/issues/1204. Sebastian also sent a PR to temporarily disable Hubble in workflows: https://github.com/cilium/cilium/pull/22068.
