### ISSUE TITLE
Wrong SRC IP in SNAT at kube-proxy-replacement (in L3 network)

### ISSUE THREAD

**Issue by alex-bazhan** [cilium/cilium#21373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello! 

We are trying to run kubernetes with cilium in kube-proxy-free mode. We use BGP (L3 connectivity) between nodes, so we have this interfaces on each node:
mgmt0 (L2)
underlay1 (L3)
underlay2 (L3)
underlay_lpbk (loopback)

Our IP routing table looks like this:
```
default via 10.19.0.1 dev mgmt0 proto static 
10.19.0.0/24 dev mgmt0 proto kernel scope link src 10.19.0.101 
10.85.0.0/16 dev cni0 proto kernel scope link src 10.85.0.1 linkdown 
172.16.0.0/12 nhid 441 proto bgp src 172.19.0.101 metric 20 
        nexthop via inet6 fe80::21c:73ff:fecc:6279 dev underlay1 weight 1 
        nexthop via inet6 fe80::21c:73ff:fecc:6279 dev underlay2 weight 1
192.168.0.0/24 via 192.168.1.100 dev cilium_host src 192.168.1.100 mtu 1450 
192.168.0.0/20 dev docker0 proto kernel scope link src 192.168.0.1 linkdown 
192.168.1.0/24 via 192.168.1.100 dev cilium_host src 192.168.1.100 
192.168.1.100 dev cilium_host scope link 
192.168.2.0/24 via 192.168.1.100 dev cilium_host src 192.168.1.100 mtu 1450 
blackhole 192.168.152.0/26 proto bird 
192.168.160.192/26 via 172.19.0.103 dev tunl0 proto bird onlink 
192.168.168.64/26 via 172.19.0.102 dev tunl0 proto bird onlink 
```
When some pod in pod network trying to connect to Cluster API (10.96.0.1) it get wrong SRC IP in SNAT:
```
18:17:15.894385 lxc29b68dc3b423 In  IP 192.168.0.140.42916 > 172.19.0.101.6443: Flags [S], seq 3638727182, win 64860, options [mss 1410,sackOK,TS val 190796148 ecr 0,nop,wscale 7], length 0
18:17:15.894475 underlay1 Out IP 10.19.0.102.42916 > 172.19.0.101.6443: Flags [S], seq 3638727182, win 64860, options [mss 1410,sackOK,TS val 190796148 ecr 0,nop,wscale 7], length 0
```
We have IP **10.19.0.102** as SRC, but it must be **172.19.0.102**.

### Cilium Version

1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64

### Kernel Version

Linux control001.tst1 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.5", GitCommit:"e979822c185a14537054f15808a118d7fcce1d6e", GitTreeState:"clean", BuildDate:"2022-09-14T16:35:41Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[Uploading cilium-sysdump-20220920-184239-.zip…]()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmcdonagh** [comment]
Ran into this earlier today through a postgres NodePort service. Most of the time when I connect it comes up as a pod network IP. but I noticed a few times I got denied access and thought it was very strange because it showed the actual IP I was connecting from instead of a pod network IP. I had so much going on at the time after a big maintenance window that I didn't dive into it much.

**Comment by pchaigno** [comment]
> Uploading cilium-sysdump-20220920-184239-.zip…

I think you didn't wait for the sysdump to finish uploading before submitting the issue maybe?

> We have IP **10.19.0.102** as SRC, but it must be **172.19.0.102**.

From the IP routes, I would have expected 172.19.0.101 as the source IP if it was Linux/netfilter doing the masquerading.

Anyway, I'm guessing Cilium is in charge of the masquerading here (via BPF?) so we'll need the sysdump to see where it picked that source IP address.

**Comment by CiraciNicolo** [comment]
Same issue, with a different environment. We have a k3s cluster with 2 nodes (1 server and 1 agent), each node has its "local" iface and then 2x tunnel interface + loopback has an ip. 

With NodePort services, source client IP is NOT kept. I've already tried to use DSR or Hybrid mode with no luck. Any advice?
