### ISSUE TITLE
Updating k8s service selector twice causes cilium to misroute requests intermittently

### ISSUE THREAD

**Issue by sblitzken** [cilium/cilium#21371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This happens to me virtually every time I do a maintenance window, so about twice quarterly and I'm sure would be happening more often if I did this operation more often. There are a couple similar problems in the "Issues" on GH but they look slightly different and usually people say it's not easily reproducible in the issues I looked at. This is pretty easily reproducible for me but wreaks absolute havoc on production so I really can't just let it be and do some deep investigation. I haven't filed a bug yet just cause I've got tons of things on my plate and usually restarting cilium fixes it immediately but today it's been pretty stubborn and I've had to roll cilium like 3 or 4 times across two clusters.

I would say this has been happening for a couple years or so now, probably back to our usage of k8s versions 1.21 or .22 k8s via kops. I can look up the cilium versions that correspond if you need. There's also been several cluster rebuilds in that timeframe so I doubt it's an upgrade artifact. Here's what happens.

I have a k8s deployment that runs in multiple NS called "maintenance." It's essentially a very stripped down Apache that only serves a page that says "Sorry this service is down for scheduled maintenance" or whatever message I configure. The maintenance pods end up tagged with "app=obe,svc=maintenance." I'm not sure if the multiple tags may come into play here or not.

So, anytime I want to put a service into maintenance, I edit the service selector on the target service to select the maintenance pods instead of the actual pods. This first edit works without a hitch. No misrouting, nothing weird. Note that most of the time the services I edit the selector on are also tagged "app=obe,svc=${servicename}." So I'm usually just editing the "svc" tag in most cases to say "maintenance."

Now, our ingress is an ALB that points to a deployment of apache reverse proxy containers rather than an actual Ingress object. This deployment's pods are tagged "app=obe,svc=wormhole." So, naturally if I want to put a whole cluster's services into maintenance, I edit the wormhole service object's selector so the svc tag to look for is "maintenance." Works like a charm.

But when I edit that selector when the maintenance is done to go back to what it was before, intermittent requests are mis-routed. The reason I know it's cilium and not an Apache issue, besides the fact that restarting cilium fixes it (at least momentarily but usually permanently), is because the wormhole pods insert a response header so that I can tell which cluster served a request. On the misrouted requests, things are not even hitting the wormhole pods because that header is not even there.

It seems random. One service that receives misrouted requests has the svc tag "catalog." Another has a different app tag as well as a different svc tag. I can't see any rhyme or reason and when it's happening it's usually very urgent to just get things back to normal.

It's probably worth noting that we use the cluster-autoscaler with spots for extra capacity beyond our base needs. I can't tell if the issue coincides directly with a spot termination, but we have good logging around those events so I could tie it together if I had more evidence pointing towards that.

Please advise, this issue is killin me!

### Cilium Version

```
⮕  cilium version
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
Client: 1.10.5 b0836e8 2021-10-13T16:20:49-07:00 go version go1.16.9 linux/amd64
Daemon: 1.10.5 b0836e8 2021-10-13T16:20:49-07:00 go version go1.16.9 linux/amd64
```

Note that this has been happening for a minute now so probably 1.9 too but I can't say exactly.

### Kernel Version

```
Linux ip-172-21-33-72 5.13.0-1022-aws #24~20.04.1-Ubuntu SMP Thu Apr 7 22:10:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Same note about versions going back a couple of kops iterations of their default images.

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.11", GitCommit:"dc2898b20c6bd9602ae1c3b51333e2e4640ed249", GitTreeState:"clean", BuildDate:"2022-09-15T02:29:45Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```

I estimate this goes back to 1.21 at least though.

### Sysdump

I have the file but it's 111 MB. Not sure what the protocol is here? Please advise. 

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
> But when I edit that selector when the maintenance is done to go back to what it was before, intermittent requests are mis-routed.

So no misrouting the first time around but some when reverting the label change? That seems weird as nothing should be different between the two label changes.

Could the misrouted requests belong to an existing connection and thus end up routed per previous policy?

> This is pretty easily reproducible for me but wreaks absolute havoc on production so I really can't just let it be and do some deep investigation.

Are you able to reproduce in your staging environment to dig?

Best way to solve this would likely be to pinpoint the issue to a specific connection and check related state.

> I have the file but it's 111 MB. Not sure what the protocol is here? Please advise.

You can limit which nodes are collected to reduce the size. Otherwise, you can host it somewhere and link here, though not ideal. It's also possible to reduce the size a lot by recompressing. (For reference, GH's limit is at 25MB.)

**Comment by jmcdonagh** [comment]
I can try to replicate on the dev cluster for sure. I usually don't bother putting up a maintenance page when I update that one after the devs are gone so I haven't noticed it there. I will see what I can do and get back to you.

**Comment by jmcdonagh** [comment]
Gonna have to wait til people are gone though. Is there any sensitive info in the in the sysdump?

**Comment by pchaigno** [comment]
> Gonna have to wait til people are gone though. Is there any sensitive info in the in the sysdump?

No, there shouldn't be any. The most sensitive I could think of is connection tracking state which includes IP addresses of clients for established connections potentially.
