### ISSUE TITLE
CI: ConformanceAKS: Timeout waiting for flow listener to become ready

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#21382]
AKS connectivity tests often (though not always) fail in CI with:
```
   🟥 Timeout waiting for flow listener to become ready
   🟥 Receiving flows from Hubble Relay: hubble server status failure: context canceled
```
It usually happens in many different test cases at the same time.

Some examples:
https://github.com/cilium/cilium/actions/runs/3082276011/jobs/4983716731
https://github.com/cilium/cilium/actions/runs/3084600846/jobs/4986940018
https://github.com/cilium/cilium/actions/runs/3094379072/jobs/5007693355
https://github.com/cilium/cilium/actions/runs/3095653024/jobs/5010293945

Couple sysdumps:
[cilium-sysdump-out.zip(2).zip](https://github.com/cilium/cilium/files/9615357/cilium-sysdump-out.zip.2.zip)
[cilium-sysdump-out.zip(3).zip](https://github.com/cilium/cilium/files/9615358/cilium-sysdump-out.zip.3.zip)

**Comment by tommyp1ckles** [comment]
@aanm @pchaigno I think the last failure is unrelated:

```  
❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.0.0.247:8080/private" succeeded while it should have failed: 
```

**Comment by pchaigno** [comment]
Yep, that last CI run seems to have another flake in addition to the flow listener one.

**Comment by pchaigno** [comment]
Closing in favor of https://github.com/cilium/cilium-cli/issues/1204. Sebastian also sent a PR to temporarily disable Hubble in workflows: https://github.com/cilium/cilium/pull/22068.
