### ISSUE TITLE
cilium identity leak

### ISSUE THREAD

**Issue by nejisama** [cilium/cilium#21404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

update a pod label, the identity updated, but the old identity still exists in api server,  no ways to delete it
delete a pod, but the identity for the pod still exists in api server,  no ways to delete it

### Cilium Version

1.12.0

### Kernel Version

linux 4.19

### Kubernetes Version

1.24.0

### Relevant log output

```shell
kubectl get ciliumendpoints.cilium.io -n test
NAME        ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4            IPV6
test1   1831          42833                                                                        ready            11.124.27.178   
  
kubectl get ciliumidentities.cilium.io
NAME    NAMESPACE        AGE
42833   test       3h57m        // this is the new identity
46156   test   3h55m            // this is the old one, still exists
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nejisama** [comment]
I check the code, and i found  the pkg/k8s/identitybackend/identity.go:Release says "No action is needed to release the reference here." ? may be we needs to call  CiliumIdentities().Delete here?

**Comment by aanm** [comment]
Hello, thanks for opening the GH issue, please provide steps to reproduce the issue and a cilium sysdump otherwise the issue can't be fixed. Thank you.

**Comment by nejisama** [comment]
1. install a k8s cluster with cilium,  `minikube start --cni=cilium`
2. create a pod , for example, a simple nginx pod `kubectl apply -f nginx.yaml`
3. check the cilium endpoints & identity `kubectl get ciliumendpoints.cilium.io` ` kubectl get ciliumidentities.cilium.io`.

`
// endpoints 
NAME                       ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4           IPV6
my-nginx-df7bbf6f5-wghhb   633           6016    
// identity
NAME   AGE
6016   12s.   // this is the endpoint 633's identity id
8685   2m27s
`

4. update pod label ` kubectl label pods my-nginx-df7bbf6f5-wghhb app=test`
5. check the cilium endpoints & identity `kubectl get ciliumendpoints.cilium.io` ` kubectl get ciliumidentities.cilium.io`.  The endpoint is updated to new identity, but the old identity still exists.

`

NAME                       ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4           IPV6
my-nginx-df7bbf6f5-wghhb   633           58707   

NAME    AGE
58707   18s. // this is the new identity for endpoint 633 
6016    3m49s // this is the old idetity for endpoint 633, leaks.
8685    6m4s
`

6. delete pod `kubectl delete -f nginx.yaml`
7. check the cilium endpoints & identity `kubectl get ciliumendpoints.cilium.io` ` kubectl get ciliumidentities.cilium.io`.  The endpoint is deleted, nut the identity still exists, but no one use it, identity leaks.

`
// no endpoints any more.
kubectl get ciliumendpoints.cilium.io
No resources found in default namespace.

// identity still exists (58707 & 6016) , leaks.
NAME    AGE
58707   97s
6016    5m8s
8685    7m23s
`


`nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
`

**Comment by nejisama** [comment]
i think the identity should also be deleted when endpoint is deleted or updated,

**Comment by nejisama** [comment]
maybe add a identity delete here instead of no action?

``` pkg/k8s/identitybackend/identity.go
// Release dissociates this node from using the identity bound to the given ID.
// When an identity has no references it may be garbage collected.
func (c *crdBackend) Release(ctx context.Context, id idpool.ID, key allocator.AllocatorKey) (err error) {
	// For CiliumIdentity-based allocation, the reference counting is
	// handled via CiliumEndpoint. Any CiliumEndpoint referring to a
	// CiliumIdentity will keep the CiliumIdentity alive. No action is
	// needed to release the reference here.

       // Add a identity delete here?
      c.Client.CiliumV2().CiliumIdentities().Delete() 
	return nil
}
```

**Comment by aanm** [comment]
The identities are garbage collected by cilium-operator every 15 minutes [here](https://github.com/cilium/cilium/blob/2adf5f4313d42ae055528b09eb8dff4c19e74a98/operator/k8s_identity.go#L164-L179)

**Comment by nejisama** [comment]
> The identities are garbage collected by cilium-operator every 15 minutes

thanks

**Comment by nejisama** [comment]
> The identities are garbage collected by cilium-operator every 15 minutes [here](https://github.com/cilium/cilium/blob/2adf5f4313d42ae055528b09eb8dff4c19e74a98/operator/k8s_identity.go#L164-L179)

I tried update pod label, and wait more than 15 minutes, the identity still exists ?

```
kubectl get ciliumendpoints.cilium.io
NAME                       ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4          IPV6
my-nginx-df7bbf6f5-xgpnj   630           41689     

kubectl label pods my-nginx-df7bbf6f5-xgpnj app=test
pod/my-nginx-df7bbf6f5-xgpnj labeled

 kubectl get ciliumendpoints.cilium.io
NAME                       ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4          IPV6
my-nginx-df7bbf6f5-xgpnj   630      

kubectl get ciliumidentities.cilium.io
NAME    AGE
28840   4m54s
29735   14s
41689   47s

kubectl get ciliumidentities.cilium.io
NAME    AGE
28840   29m
29735   24m
41689   25m // after 25 minutes, the identities still exists


```

**Comment by nejisama** [comment]
I delete the pod， the identity gc will be triggered. but label update will not ?

**Comment by nejisama** [comment]
Thanks. The operator check identity every 15m, but the Identity timeout is 30m,  so i need to wait 30m
