### ISSUE TITLE
cilium service endpoints not update

### ISSUE THREAD

**Issue by fangzhexu** [cilium/cilium#21418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

（1）The Kubernetes Node simulates Crash
（2）When the Kubernetes Node status changes to Notready, the Pod state Terminating IP address in the Cilium Service is removed
（3）Kubernetes Node is faulty for more than 5 minutes, After rescheduling, the Pod status is ImagePullBackOff, and the IP address of Pod state Terminating appears in Cilium Servcie.

Result：Some requests to access the service failed.

· Kubernetes Node status changes to Notready
```
[root@k8s-yjy-master01 ~]# date
Fri Sep 23 14:28:00 CST 2022
[root@k8s-yjy-master01 ~]# kubectl get nodes
NAME          STATUS                     ROLES    AGE   VERSION
172.0.16.11   Ready,SchedulingDisabled   master   55d   v1.23.6
172.0.16.14   Ready,SchedulingDisabled   master   55d   v1.23.6
172.0.16.17   Ready,SchedulingDisabled   master   55d   v1.23.6
172.0.16.19   Ready                      node     55d   v1.23.6
172.0.16.22   NotReady                   node     55d   v1.23.6
172.0.16.8    Ready                      node     55d   v1.23.6
172.0.16.95   Ready,SchedulingDisabled   node     30d   v1.23.6
172.0.16.96   Ready,SchedulingDisabled   node     30d   v1.23.6
[root@k8s-yjy-master01 ~]# kubectl exec -it -n kube-system cilium-fck6g -- cilium service list|grep -i 10.211.45.143 -A 3
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
32    10.211.45.143:9999     ClusterIP      1 => 10.212.3.80:9999 (active)     
                                            2 => 10.212.4.106:9999 (active)    
33    10.211.159.1:80        ClusterIP      1 => 10.212.3.240:80 (active)      
                                            2 => 10.212.4.70:80 (active)       
[root@k8s-yjy-master01 ~]# kubectl describe svc -n call call-gateway  
Name:                     call-gateway
Namespace:                call
Labels:                   <none>
Annotations:              field.cattle.io/publicEndpoints: [{"port":34444,"protocol":"TCP","serviceName":"call:call-gateway","allNodes":true}]
Selector:                 app=call-gateway
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.211.45.143
IPs:                      10.211.45.143
Port:                     <unset>  9999/TCP
TargetPort:               9999/TCP
NodePort:                 <unset>  34444/TCP
Endpoints:                10.212.3.80:9999,10.212.4.106:9999
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
[root@k8s-yjy-master01 ~]# kubectl get pod -n call -o wide|grep gateway
call-gateway-6c877bc6f7-6jbxs               1/1     Running   0             158m    10.212.4.106   172.0.16.8    <none>           <none>
call-gateway-6c877bc6f7-75ttw               1/1     Running   0             4h53m   10.212.3.80    172.0.16.19   <none>           <none>
call-gateway-6c877bc6f7-dh6v2               1/1     Running   0             6m58s   10.212.5.92    172.0.16.22   <none>           <none>
```

· Kubernetes Node is faulty for more than 5 minutes, After rescheduling
```
[root@k8s-yjy-master01 ~]# date
Fri Sep 23 14:32:37 CST 2022
[root@k8s-yjy-master01 ~]# kubectl get nodes
NAME          STATUS                     ROLES    AGE   VERSION
172.0.16.11   Ready,SchedulingDisabled   master   55d   v1.23.6
172.0.16.14   Ready,SchedulingDisabled   master   55d   v1.23.6
172.0.16.17   Ready,SchedulingDisabled   master   55d   v1.23.6
172.0.16.19   Ready                      node     55d   v1.23.6
172.0.16.22   NotReady                   node     55d   v1.23.6
172.0.16.8    Ready                      node     55d   v1.23.6
172.0.16.95   Ready,SchedulingDisabled   node     30d   v1.23.6
172.0.16.96   Ready,SchedulingDisabled   node     30d   v1.23.6
[root@k8s-yjy-master01 ~]# kubectl exec -it -n kube-system cilium-fck6g -- cilium service list|grep -i 10.211.45.143 -A 3
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
32    10.211.45.143:9999     ClusterIP      1 => 10.212.3.80:9999 (active)        
                                            2 => 10.212.4.106:9999 (active)       
                                            3 => 10.212.5.92:9999 (active)        
33    10.211.159.1:80        ClusterIP      1 => 10.212.3.240:80 (active)         
[root@k8s-yjy-master01 ~]# kubectl describe svc -n call call-gateway   
Name:                     call-gateway
Namespace:                call
Labels:                   <none>
Annotations:              field.cattle.io/publicEndpoints: [{"port":34444,"protocol":"TCP","serviceName":"call:call-gateway","allNodes":true}]
Selector:                 app=call-gateway
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.211.45.143
IPs:                      10.211.45.143
Port:                     <unset>  9999/TCP
TargetPort:               9999/TCP
NodePort:                 <unset>  34444/TCP
Endpoints:                10.212.3.80:9999,10.212.4.106:9999
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
[root@k8s-yjy-master01 ~]# kubectl get pod -n call -o wide|grep gateway
call-gateway-6c877bc6f7-4r65v               0/1     ErrImagePull   0             36s     10.212.4.105   172.0.16.8    <none>           <none>
call-gateway-6c877bc6f7-6jbxs               1/1     Running        0             161m    10.212.4.106   172.0.16.8    <none>           <none>
call-gateway-6c877bc6f7-75ttw               1/1     Running        0             4h56m   10.212.3.80    172.0.16.19   <none>           <none>
call-gateway-6c877bc6f7-dh6v2               1/1     Terminating    0             9m40s   10.212.5.92    172.0.16.22   <none>           <none>
[root@k8s-yjy-master01 ~]# 
```

### Cilium Version
```
[root@k8s-yjy-master01 ~]# cilium version
cilium-cli: v0.12.0 compiled with go1.18.4 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.12.2
cilium image (running): v1.12.0
```
### Kernel Version
```
[root@k8s-yjy-master01 ~]# uname -r
5.4.205-1.el7.elrepo.x86_64
```
### Kubernetes Version
```
[root@k8s-yjy-master01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```
### Sysdump

[cilium-sysdump-20220927-180322.zip](https://github.com/cilium/cilium/files/9660577/cilium-sysdump-20220927-180322.zip)

### Anything else?

Cilium installation method: 
```
helm repo add cilium https://helm.cilium.io/

helm install cilium cilium/cilium --version 1.12.0 --namespace kube-system \
  --set cluster.id=1 --set cluster.name=cluster-yjy1 \
  --set k8sServiceHost=172.0.16.88 --set k8sServicePort=16443

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Hi! Can you upload a sysdump from your cluster while the issue you reported is occurring?
Can you highlight the IP addresses of the pods that you think are in the terminating state?

>The Kubernetes Node simulates Crash

How did you simulate this on your cluster?

**Comment by fangzhexu** [comment]
> 
(1) Do I upload cilium sysdump?
(2) The POD IP address in the Terminating state: ```10.212.5.92```
(3) Node exec  shell command: ```poweroff -nf```

**Comment by fangzhexu** [comment]
> Hi! Can you upload a sysdump from your cluster while the issue you reported is occurring? Can you highlight the IP addresses of the pods that you think are in the terminating state?
> 
> > The Kubernetes Node simulates Crash
> 
> How did you simulate this on your cluster?

(1) Do I upload cilium sysdump?
(2) The POD IP address in the Terminating state: 10.212.5.92
(3) Node exec shell command: poweroff -nf

**Comment by fangzhexu** [comment]
> Hi! Can you upload a sysdump from your cluster while the issue you reported is occurring? Can you highlight the IP addresses of the pods that you think are in the terminating state?
> 
> > The Kubernetes Node simulates Crash
> 
> How did you simulate this on your cluster?

Cilium sysdump exceeds the 25MB size limit, What should I do better?

**Comment by fangzhexu** [comment]
After more tests, it is found that the IP address of the ```Terminating``` state Pod on the faulty node always exists in ```cilium service``` from the start of rescheduling by default 5 minutes after the failure to the time when the newly scheduled Pod is ready.

**Comment by aditighag** [comment]
If the faulty node (or the cilium agent running on that node) isn't able to communicate to the kube-api server, then the agent won't receive terminating endpoint updates, and so the terminating endpoint IP will continue to be present in the service list.

After you forcefully reboot a node, you can monitor the `k8s_terminating_endpoints_events_total` metrics, and see when it gets updated.

In general, Kubernetes recommends gracefully shutting down nodes, which can include cordoning of a node. In your case, you seem to be forcefully shutting down a node.

**Comment by fangzhexu** [comment]
> If the faulty node (or the cilium agent running on that node) isn't able to communicate to the kube-api server, then the agent won't receive terminating endpoint updates, and so the terminating endpoint IP will continue to be present in the service list.
> 
> After you forcefully reboot a node, you can monitor the `k8s_terminating_endpoints_events_total` metrics, and see when it gets updated.
> 
> In general, Kubernetes recommends gracefully shutting down nodes, which can include cordoning of a node. In your case, you seem to be forcefully shutting down a node.

Sorry, I didn't describe the problem clearly

1. The cause of the problem is that we want to simulate node failure to test the impact on business. The problems found during the test are roughly like this: At the very beginning, Kubernetes Node enters the state of Notready. There are only two IP addresses in the running state in the Cilium Service. But the terminating endpoints appear in the ``ciliumc service`` and are ```active``` past the ```pod-eviction-timeout``` default (5 minutes), causing some of our requests to timeout, The terminating endpoints disappear from the ```clilium``` service only when the rescheduled new pods are fully ready.

2. During the simulation failure, the ```Cilium-agent``` on the corresponding Node is no longer accessible. The ```cilium service``` information I provided is obtained from the ```Cilium-agent``` on the ready Node.

**Comment by aanm** [comment]
@fangzhexu can you provide a sysdump where you have a NotReady node and the issue is happening? Thank you

**Comment by fangzhexu** [comment]
> 
sysdump has been uploaded, at the beginning of issue

cilium-sysdump-20220927-180322.zip

**Comment by fangzhexu** [comment]
> @fangzhexu can you provide a sysdump where you have a NotReady node and the issue is happening? Thank you

sysdump has been uploaded, at the beginning of issue

cilium-sysdump-20220927-180322.zip

**Comment by fangzhexu** [comment]
> @fangzhexu can you provide a sysdump where you have a NotReady node and the issue is happening? Thank you

@aanm  sysdump has been uploaded, at the beginning of issue
cilium-sysdump-20220927-180322.zip

**Comment by aanm** [comment]
@fangzhexu that sysdump doesn't contain the issue.
