### ISSUE TITLE
Egress Load Balancing with ciliumegressgatewaypolicy 

### ISSUE THREAD

**Issue by osaffer** [cilium/cilium#21420]
Hi,

I am trying to configure the loadbalancing with ciliumEgressGatewayPolicy , I have not seen documentation as for the use of EgressGroup for ciliumEgressNatPolicy

So I tried the following:  apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-lb
spec:
  selectors:
  - podSelector:
      matchLabels:
        org: empire
        class: mediabot
        io.kubernetes.pod.namespace: default

  destinationCIDRs:
  - "IP_Destination/32"

  egressGateway:
    nodeSelector:
      matchLabels:
        egress-lb: egress-lb 

    interface: eth0

After applying I can see : 

==== cilium-8plmb ====
Source IP   Destination CIDR     Egress IP      Gateway IP
10.0.2.32  IP_Destination/32   IP_NODE2   IP_NODE1
==== cilium-8sc4l ====
Source IP   Destination CIDR     Egress IP   Gateway IP
10.0.2.32   IP_Destination/32   0.0.0.0    IP_NODE1
==== cilium-9hclp ====
Source IP   Destination CIDR     Egress IP   Gateway IP
10.0.2.32   IP_Destination/32   0.0.0.0     IP_NODE1
==== cilium-df2tj ====
Source IP   Destination CIDR     Egress IP   Gateway IP
10.0.2.32   IP_Destination/32   0.0.0.0     IP_NODE1
==== cilium-dxxwx ====
Source IP   Destination CIDR     Egress IP   Gateway IP
10.0.2.32   IP_Destination/32   0.0.0.0     IP_NODE1
==== cilium-fpscq ====
Source IP   Destination CIDR     Egress IP   Gateway IP
10.0.2.32   IP_Destination/32   0.0.0.0     IP_NODE1
==== cilium-gjtzx ====
Source IP   Destination CIDR     Egress IP   Gateway IP
10.0.2.32   IP_Destination/32   0.0.0.0     IP_NODE1
==== cilium-h8kgq ====
Source IP   Destination CIDR     Egress IP      Gateway IP
10.0.2.32   148.110.139.159/32   IP_NODE1   IP_NODE1

So of course it will cause a problem when I will drain node 1.

Can you clarify if we can configure the load balancing with ciliumegressgatewaypolicy ?

Thank you

**Comment by julianwiedmann** [comment]
`EgressGroups` (ie. load-balancing for EgressGW) is not part of upstream Cilium, it's a vendor add-on. Please contact that vendor if you need further help.

**Comment by osaffer** [comment]
What is your solution if we drain one node ?

**Comment by julianwiedmann** [comment]
> What is your solution if we drain one node ?

It's been discussed [previously](https://github.com/cilium/cilium/issues/18230). But I'm not aware that anyone has started working on it.

**Comment by osaffer** [comment]
What a pity anyway, cilium could be a good solution, but skip a basic HA feature is quite a non sense. Unfortunately we will need to find an other solution.
