### ISSUE TITLE
CI: ConformanceAKS: command curl ... succeeded while it should have failed

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#21430]
## CI failure

AKS-connectivity test fails occasionally with error:

```
❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.0.0.114:8080/public" succeeded while it should have failed: 
```

Examples:
* https://github.com/cilium/cilium/actions/runs/3109675806/jobs/5040114497#step:16:91
* https://github.com/cilium/cilium/actions/runs/3095653024/jobs/5010293945#step:16:81

This seems distinct for other existing test flake: https://github.com/cilium/cilium/issues/21382

Sysdump:

https://github.com/cilium/cilium/suites/8429676044/artifacts/373302495

**Comment by pchaigno** [comment]
cc @jibi we may already have an issue for this.

**Comment by pchaigno** [comment]
This was opened before but https://github.com/cilium/cilium/issues/22162 has more info now so closing in favor of https://github.com/cilium/cilium/issues/22162.
