### ISSUE TITLE
CFP: Support PROXY Protocol from external LoadBalancers

### ISSUE THREAD

**Issue by Preisschild** [cilium/cilium#21438]
## Cilium Feature Proposal

**Is your feature request related to a problem?**
Some Load Balancing solutions, such as Hetzner's LoadBalancer and AWS' Classic Load Balancer are using the [HAProxy Proxy Protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) to pass source IP information along. If you use those Load Balancers with a Cilium-enabled Kubernetes Cluster you currently can not whitelist certain IP ranges, because cilium only sees all connections coming from the Load Balancer. 

**Describe the feature you'd like**
Cilium parses the HAProxy Headers and replace original source IP information with those in the header.

**(Optional) Describe your proposed solution**

1. Add global options to:
    - Enable PROXY Protocol support
    - Set LoadBalancer Trusted IP range
2. Check if PROXY support is enabled and the original source IP comes from the trusted proxy IP range.
    - If not -> use original IP, do not parse anything
    - If both true > Try to parse the PROXY header, replace original source ip with parsed source ip. Fallback to original IP if parsing fails.

**More Information**
- https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
- https://developers.cloudflare.com/spectrum/how-to/enable-proxy-protocol/#the-proxy-protocol-v2-header
- https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto

**Comment by Preisschild** [comment]
Related: https://github.com/cilium/cilium/issues/7531

**Comment by Preisschild** [comment]
There seems to be interested in this feature, can we keep this open please?

**Comment by zetaab** [comment]
There seems to be interested in this feature, can we keep this open please?

**Comment by Buffer0x7cd** [comment]
We are also interested in this feature because of it's use-case in per host proxy deployment model.

**Comment by albundy83** [comment]
Hello,
until the support is added (if possible of course), is there a way to receive real IP addresses inside Kube ?

**Comment by albundy83** [comment]
Thanks for your answer, I was hoping that it was possible now with some configurations tricks :)

**Comment by w7team** [comment]
https://github.com/cilium/cilium/issues/26530

**Comment by xiaods** [comment]
if you use ingress service, it also support ProxyProtocol,  see this commit: https://github.com/chaunceyjiang/cilium/commit/24911b03cf4c3f06481394b12e1a06762dce5d2a

**Comment by gadiener** [comment]
I also have a similar use case and would be interested in such functionality 👍🏻

**Comment by zetaab** [comment]
@gadiener there is PR open its just waiting for merge

**Comment by gadiener** [comment]
Thanks @zetaab I saw the PR, great work!

Does it cover the use case presented in my comment?

> It'd be great to receive the original source IP information to the destination pod as well. I could't find a way to do that with Cilium for TCP traffic. With Istio, for example, I can resolve the PROXY Protocol header on the sidecar and pass down the information using the transparent proxy feature.

**Comment by zetaab** [comment]
@gadiener you just need to have somekind of component in kubernetes cluster that understands proxy protocol. For instance it can be achieved using nginx-ingress (proxy protocol mode). Nginx can inject the real source ip to x-forwarded-for header as visible to pod itself
