### ISSUE TITLE
Check netpol rules on the host

### ISSUE THREAD

**Issue by anupamdialpad** [cilium/cilium#21440]
Hi,

We were previously using [Kube-router](https://github.com/cloudnativelabs/kube-router) in our cluster with bridge + ipam as the plugin but we are planning to move to Cilium. In kube-router we could run the iptables command to check if all the netpol rules are created successfully or not. Since Cilium uses bpf internally to route the packets I think we cannot use iptables to check the rules on the host. 

I want to know how bpf is used internally to create the rules from netpol and is there a way to check those rules on the host machine similar to iptables where we could check the forward chain for network policies and the nat table to know how a packet is routed for the pod ip.

**Comment by aanm** [comment]
Have you looked at https://docs.cilium.io/en/v1.12/operations/troubleshooting/#troubleshooting which provides a lot of details on how to debug Cilium?
