### ISSUE TITLE
Packet will leave node if destination is a service without backends

### ISSUE THREAD

**Issue by anfernee** [cilium/cilium#21453]
I see this behavior in 1.11, but from the source code: 

https://github.com/cilium/cilium/blob/58e4081c3c2a6e052d7c5e3443be33dd6ae5024b/bpf/bpf_lxc.c#L1253-L1275 

It looks like the behavior is still the same where `DROP_NO_SERVICE` is returned for the cases either service is not found or backend is not found in here: https://github.com/cilium/cilium/blob/master/bpf/lib/lb.h#L1505 

I am wondering if this is the correct behavior. Should we drop the packet if we know it belongs to a service without backend, as opposed to allowing it to exit the node.

**Comment by brb** [comment]
@anfernee Thanks for the issue. Are you saying the following does not result in a packet drop even if the `DROP_NO_SERVICE` is returned by the `lb4_local()`?
```
if (IS_ERR(ret)) 
    return ret; 
```

**Comment by anfernee** [comment]
I don't exactly know which line is causing the problem. If it's not expected behavior, I can dig more into this one. Looks like it's not, right?

**Comment by julianwiedmann** [comment]
> @anfernee Thanks for the issue. Are you saying the following does not result in a packet drop even if the `DROP_NO_SERVICE` is returned by the `lb4_local()`?
> 
> ```
> if (IS_ERR(ret)) 
>     return ret; 
> ```

As @michaelasp noticed in https://github.com/cilium/cilium/pull/21539, we don't even get to this point. `lb4_lookup_service()` returns NULL for a SVC with 0 backends, so we skip all subsequent service processing.

**Comment by pchaigno** [comment]
Reopening given the fix was reverted due to a BPF complexity regression.
