### ISSUE TITLE
egress gateway traffic appears to always be routed through the primary network interface

### ISSUE THREAD

**Issue by doy-materialize** [cilium/cilium#21452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i am trying to use the egress gateway feature to route traffic out one of many eips attached to a single eks node. from that node itself, i am able to configure routing such that i can successfully make external requests from each of the attached eips, but if i try to make cilium route egress out those ip addresses from other pods, only the eips attached to the primary network interface work correctly. trying to route traffic out an eip attached to a secondary eni causes the traffic to just hang. looking at tcpdump output, the gateway node is receiving the packets from the pod and sending them back out with a modified source ip address, but it seems to be always sending those packets out through the primary eni, regardless of what the routing rules say. am i configuring something wrong, or is this not currently supported?

### Cilium Version

i have encountered this behavior on both 1.11 and 1.12.

### Kernel Version

`Linux ip-10-2-41-104.ec2.internal 5.4.209-116.367.amzn2.x86_64 #1 SMP Wed Aug 31 00:09:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Difficult to say without seeing your config, but sounds like you might be missing the `egressGateway.installRoutes=true` [option](https://docs.cilium.io/en/v1.12/gettingstarted/egress-gateway/#compatibility-with-cloud-environments) that was introduced in Cilium `v1.12`.
