### ISSUE TITLE
cilium-operator with IPAM cluster-pool handing out duplicate CIDRs

### ISSUE THREAD

**Issue by gottwald** [cilium/cilium#21482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I noticed in newly provisioned k8s clusters with cilium we run into network issues where packets are routed to the wrong nodes which resulted in pod crashes and connectivity issues.

Digging further into this I found that cilium had handed out the same pod CIDRs for different machines.

**A rough timeline of how these things happen:**

It's easiest to reproduce when we bootstrap new HA clusters.

- k8s-master-1 node comes up
- cilium-operator (run 1): comes up
- cilium-operator (run 1): acquires lease `kube-system/cilium-operator-resource-lock`
- ciliumnode for the 1st master node is created
- worker-node-1 comes up
- k8s-master-2 comes up
- cilium-operator (run 1): cannot get to master due to leader change, loses leader status and stops itself
- cilium-operator gets restarted by k8s
- cilium-operator (run 2): starts normal and acquires new lease. Is now the leader
- cilium-operator (run 2): starts cluster pool ip allocator
- assigns the pod cidr from k8s-master-1 also to worker-node-1

I did some digging through the code and unless I missed anything it looks like the following happens:

- cilium-operator (run 1): hands out 192.168.0.0/25
- the restart happens
- cilium-operator (run 2): waits for k8s informer caches to be synced
- starts working on the ciliumnode work queue where it initially receives all existing ciliumnodes one by one
- for nodes that have a recorded cidr in the spec it tries to reuse it and learns it
- but nodes that don't have it get a new cidr assigned

It looks to me that this makes it possible that new cidrs are handed out before the mechanism went through all existing nodes. (not 100% sure I was following the path correctly)
If this holds true, then there should probably an initialization phase that first learns about all the cidrs in the cluster before it's allowed to hand out new ones.

This issue is a bit hard to reproduce at first but it can definitely happen to any cluster that uses cluster-pool IPAM and launches a new node while cilium-operator was restarted.

### Cilium Version

Daemon: 1.11.9 4409e95 2022-09-14T15:13:58+02:00 go version go1.17.13 linux/amd64

### Kernel Version

5.10.0-0.bpo.15-amd64 #1 SMP Debian 5.10.120-1~bpo10+1 (2022-06-13) x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.22.12

### Sysdump

Cannot fully disclose 

### Relevant log output

```shell
see attached files
```

### Anything else?

[cilium-operator-run-1.log](https://github.com/cilium/cilium/files/9666214/cilium-operator-run-1.log)
[cilium-operator-run-2.log](https://github.com/cilium/cilium/files/9666215/cilium-operator-run-2.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
> It looks to me that this makes it possible that new cidrs are handed out before the mechanism went through all existing nodes. (not 100% sure I was following the path correctly)

This logic _should_ be there, but for some reason it seems to fall short in your case.

https://github.com/cilium/cilium/blob/b5fbb603de5cb4643b77f9ae0e4c5eb08d5f8a40/operator/cmd/root.go#L517-L532

**Comment by gandro** [comment]
>  If this holds true, then there should probably an initialization phase that first learns about all the cidrs in the cluster before it's allowed to hand out new ones.

This mechanism _should_ be there, but for some reason it seems to fall short in your case:

https://github.com/cilium/cilium/blob/b5fbb603de5cb4643b77f9ae0e4c5eb08d5f8a40/operator/cmd/root.go#L517-L532

**Comment by dylandreimerink** [comment]
Running into this as well.

>This mechanism should be there

It appears that way, but what this does it wait until the cache is synced. The PodCIDR allocater doesn't do an initial sync on startup and goes straight into the control loop.
All existing nodes are queued as Update events, the allocator then marks all assigned PodCIDRs as allocated.
However, the order of these events isn't guaranteed. So if the order happens to be:
* Node 1 (no pod CIDR)
* Node 2 (10.0.10.0/24)

Then the allocator will assign Node 1 an address when it sees it, even the already used 10.0.10.0/24 since it hasn't processed the update event of node 2 yet. 

So, we need to queue all nodes without a PodCIDR and only attempt to allocate after we have marked all existing PodCIDRs as allocated.

**Comment by gandro** [comment]
> Then the allocator will assign Node 1 an address when it sees it, even the already used 10.0.10.0/24 since it hasn't processed the update event of node 2 yet.

Unless I'm missing something, this is not supposed to happen. The code that should prevent this is here:
https://github.com/cilium/cilium/blob/3046c1fc93d9dcf599e48266306adad3d399c707/pkg/ipam/allocator/podcidr/podcidr.go#L483-L489

`canAllocatePodCIDRs` is only set to true once the K8s caches are synced, which should imply that the operator has seen all Cilium nodes.

**Comment by dylandreimerink** [comment]
This podcidr code is triggered when the `Update()` or `Create()` function on the Allocator is called. The allocator doesn't consume an informer directly, rather the [operator does](https://github.com/cilium/cilium/blob/3046c1fc93d9dcf599e48266306adad3d399c707/operator/cmd/cilium_node.go#L148) and then calls into the Allocator.

However the informer callbacks don't call directly into the Allocator, the [events get queued.](https://github.com/cilium/cilium/blob/3046c1fc93d9dcf599e48266306adad3d399c707/operator/cmd/cilium_node.go#L174)

We close the `k8sCiliumNodesCacheSynced` channel [here](https://github.com/cilium/cilium/blob/3046c1fc93d9dcf599e48266306adad3d399c707/operator/cmd/cilium_node.go#L220). Which causes the main goroutine to [call](https://github.com/cilium/cilium/blob/3046c1fc93d9dcf599e48266306adad3d399c707/operator/cmd/root.go#L528) the `Resync`. Which sets `canAllocatePodCIDRs`.

At the same time(or after) the `Resync` the queued events [start coming in](https://github.com/cilium/cilium/blob/3046c1fc93d9dcf599e48266306adad3d399c707/operator/cmd/cilium_node.go#L227).

**Comment by timoreimann** [comment]
@dylandreimerink I saw you assigned yourself to the ticket. Is this bug something you plan to address?

Let us know if you need help, e.g., testing the fix or anything else.

**Comment by dylandreimerink** [comment]
@timoreimann I just submitted a PR with the fix. Would be great if you can verify that this fixes the bug, if you have an environment where you are encountering it. I welcome independent review.

I could reliably reproduce the bug by corrupting the ConfigMap and restarting the operators to cause a crash loop. Then adding additional nodes to the cluster and fixing the ConfigMap again.

**Comment by timoreimann** [comment]
@dylandreimerink thanks for the quick PR! We can certainly try it out in our infra next week and report back.

**Comment by timoreimann** [comment]
@dylandreimerink I see you removed the v1.10 flag. Is that because the issue only affects v1.11+, or rather that v1.10 is affected but won't be addressed?

**Comment by dylandreimerink** [comment]
@timoreimann v1.10 isn't effected. It turns out that in v1.11 a queue was added which causes the bug.

**Comment by gottwald** [comment]
I just ran a build of your PR in our test environment and I can no longer reproduce the issue. So from our side the fix looks good.

**Comment by timoreimann** [comment]
Thanks for getting the fixed merged. 🎉

Is there an ETA when we can expect it to be released? Eagerly awaiting it since the bug affects large parts of our fleet at DigitalOcean and keeps us from upgrading to Cilium 1.11.

**Comment by pchaigno** [comment]
@timoreimann The next set of patch releases is planned for around mid-November.

**Comment by timoreimann** [comment]
@pchaigno thanks for the info. We had somewhat hoped that such a critical bug could perhaps expedite shipping a small patch release, but understand if that's not possible.

**Comment by pchaigno** [comment]
IIRC, the bug only happens if Kubernetes nodes are being added while the operator is starting, which is probably why we didn't get more reports from users. In any case, it's always possible to manually backport the fix to the latest v1.11 patch release and use that yourself.
