### ISSUE TITLE
Cilium v1.12 docker image is not available yet for eks-a

### ISSUE THREAD

**Issue by mazzy89** [cilium/cilium#21486]
From my understanding the public ECR gallery repo available here https://gallery.ecr.aws/isovalent/cilium is mantained by you. I hope I’m not mistaken.

The latest image is for Cilium 1.11.x. Are you going to provide 1.12 for eks-a. Any there any blockers that have preventend to not have one created?

Thank you

**Comment by vincentmli** [comment]
good point to raise this issue since eks-a is partner with F5 and one of the motivation that I contributed VTEP to cilium is to allow eks-a with cilium work with BIG-IP :).  maybe @aanm @joestringer  knows about it

**Comment by aanm** [comment]
Closing this issue since this is a distribution maintained by a vendor.
