### ISSUE TITLE
Add developer docs to use vscode for debugging

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#21492]
This PR added support for easily building cilium images and deploying them to debug Cilium live in a kind environment:

https://github.com/cilium/cilium/pull/21108

We should extend the [contributor guide](https://docs.cilium.io/en/latest/contributing/development/) to include these examples and how to develop Cilium using this tooling.

**Comment by ti-mo** [comment]
Neat! I'd like to use this, will give this a spin and document it.
