### ISSUE TITLE
Build artifacts not collected for runtime tests with Envoy.

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#2150]
Jenkinsfile needs some work to gather logs etc. from the build VM of the runtime tests with Envoy. Also, it seems wrong that we do "vagrant destroy -f" within the parallel steps.

**Comment by aalemayhu** [comment]
:+1:  Also experienced an issue where envoy test failed. Would be extremely useful to get the logs.

**Comment by ianvernon** [comment]
@jrajahalme  is taking care of this as part of #2483.
