### ISSUE TITLE
cilium agent crashes on IPv6 only hosts (nodes)

### ISSUE THREAD

**Issue by telmich** [cilium/cilium#21538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

cilium agent crashes with the following error:

```
level=info msg="Validating configured node address ranges" subsys=daemon
level=fatal msg="postinit failed" error="external IPv4 node address could not be derived, please configure via --ipv4-node" subsys=daemon
level=info msg="Starting IP identity watcher" subsys=ipcache
```

### Cilium Version

v1.12.2

### Kernel Version

5.15.71-0-lts

### Kubernetes Version

1.25.0

### Sysdump

Not related

### Relevant log output

```shell
level=fatal msg="postinit failed" error="external IPv4 node address could not be derived, please configure via --ipv4-node" subsys=daemon
```
```


### Anything else?

The purpose ot this cilium installation is two fold:

* (a) Running k8s in an environment that is IPv6 only (i.e. hosts are IPv6 only)
* (b) Running k8s as ipv6 only pods / workload

The describe issue refers to (a), the error is, afaics, not related trying to run cilium *inside* also ipv6 only.

Cilium was installed using:

```
version=1.12.2

helm upgrade --install cilium cilium/cilium --version $version \
  --namespace kube-system \
  --set ipv4.enabled=false \
  --set ipv6.enabled=true \
  --set enableIPv6Masquerade=false \
  --set bgpControlPlane.enabled=true
```

The addresses of a sample host where cilium agent crashes is:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether a8:a1:59:a2:4a:19 brd ff:ff:ff:ff:ff:ff
    inet6 2a0a:e5c0:13:0:aaa1:59ff:fea2:4a19/64 scope global dynamic mngtmpaddr 
       valid_lft 86398sec preferred_lft 14398sec
    inet6 fe80::aaa1:59ff:fea2:4a19/64 scope link 
       valid_lft forever preferred_lft forever
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by samip5** [comment]
You need to disable tunnel too as vxlan will not work without IPv4.

**Comment by joestringer** [comment]
This test is run regularly against the Cilium codebase to implement IPv6-only mode:

https://github.com/cilium/cilium/blob/master/.github/workflows/tests-smoke-ipv6.yaml#L108

Maybe there are some additional options that are required like disabling tunneling mode as Skyler mentioned above.

**Comment by telmich** [comment]
@samip5 Why would vxlan not work without IPv4? We are using VXLAN in other projects on IPv6 only networks.

**Comment by samip5** [comment]
> @samip5 Why would vxlan not work without IPv4? We are using VXLAN in other projects on IPv6 only networks.

Because Cilium tries to do it over V4, in all cases.

**Comment by aanm** [comment]
@telmich disabling tunneling fix your issue?

**Comment by telmich** [comment]
Is there anything I can do for this issue to progress, @aanm ?

**Comment by aanm** [comment]
@telmich You need to disable tunneling which is enabled by default.

**Comment by samip5** [comment]
> @telmich You need to disable tunneling which is enabled by default.

Shouldn't it try to use IPv6 for the tunnel if IPv4 is disabled? I think that would be a safe assumption?

**Comment by samip5** [comment]
> I can confirm this also happens to me
> 
> 
> 
> git: a09e05e6b63d82dbc3a1b0de1721a3407c340e7c
> 
> 
> 
> cilium-config:
> 
> ```
> 
> apiVersion: v1
> 
> data:
> 
>   agent-not-ready-taint-key: node.cilium.io/agent-not-ready
> 
>   arping-refresh-period: 30s
> 
>   auto-direct-node-routes: "false"
> 
>   bpf-lb-acceleration: disabled
> 
>   bpf-lb-external-clusterip: "false"
> 
>   bpf-lb-map-max: "65536"
> 
>   bpf-lb-sock: "false"
> 
>   bpf-map-dynamic-size-ratio: "0.0025"
> 
>   bpf-policy-map-max: "16384"
> 
>   bpf-root: /sys/fs/bpf
> 
>   cgroup-root: /run/cilium/cgroupv2
> 
>   cilium-endpoint-gc-interval: 5m0s
> 
>   cluster-id: "0"
> 
>   cluster-name: default
> 
>   cni-exclusive: "true"
> 
>   cni-log-file: /var/run/cilium/cilium-cni.log
> 
>   custom-cni-conf: "false"
> 
>   debug: "false"
> 
>   dnsproxy-enable-transparent-mode: "true"
> 
>   egress-gateway-reconciliation-trigger-interval: 1s
> 
>   enable-auto-protect-node-port-range: "true"
> 
>   enable-bgp-control-plane: "false"
> 
>   enable-bpf-clock-probe: "false"
> 
>   enable-endpoint-health-checking: "true"
> 
>   enable-envoy-config: "true"
> 
>   enable-health-check-loadbalancer-ip: "false"
> 
>   enable-health-check-nodeport: "true"
> 
>   enable-health-checking: "true"
> 
>   enable-hubble: "true"
> 
>   enable-ipv4: "false"
> 
>   enable-ipv4-big-tcp: "false"
> 
>   enable-ipv4-masquerade: "true"
> 
>   enable-ipv6: "true"
> 
>   enable-ipv6-big-tcp: "false"
> 
>   enable-ipv6-masquerade: "true"
> 
>   enable-k8s-networkpolicy: "true"
> 
>   enable-k8s-terminating-endpoint: "true"
> 
>   enable-l2-neigh-discovery: "true"
> 
>   enable-l7-proxy: "true"
> 
>   enable-local-redirect-policy: "false"
> 
>   enable-masquerade-to-route-source: "false"
> 
>   enable-metrics: "true"
> 
>   enable-policy: default
> 
>   enable-remote-node-identity: "true"
> 
>   enable-sctp: "false"
> 
>   enable-svc-source-range-check: "true"
> 
>   enable-vtep: "false"
> 
>   enable-well-known-identities: "false"
> 
>   enable-xt-socket-fallback: "true"
> 
>   envoy-secrets-namespace: cilium-secrets
> 
>   external-envoy-proxy: "true"
> 
>   hubble-disable-tls: "false"
> 
>   hubble-export-file-max-backups: "5"
> 
>   hubble-export-file-max-size-mb: "10"
> 
>   hubble-listen-address: :4244
> 
>   hubble-socket-path: /var/run/cilium/hubble.sock
> 
>   hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
> 
>   hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
> 
>   hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
> 
>   identity-allocation-mode: crd
> 
>   identity-gc-interval: 15m0s
> 
>   identity-heartbeat-timeout: 30m0s
> 
>   install-no-conntrack-iptables-rules: "false"
> 
>   ipam: kubernetes
> 
>   ipam-cilium-node-update-rate: 15s
> 
>   k8s-client-burst: "20"
> 
>   k8s-client-qps: "10"
> 
>   k8s-kubeconfig-path: /home/ubuntu/.kube/local
> 
>   k8s-require-ipv6-pod-cidr: "true"
> 
>   kube-proxy-replacement: "true"
> 
>   kube-proxy-replacement-healthz-bind-address: ""
> 
>   max-connected-clusters: "255"
> 
>   mesh-auth-enabled: "true"
> 
>   mesh-auth-gc-interval: 5m0s
> 
>   mesh-auth-queue-size: "1024"
> 
>   mesh-auth-rotated-identities-queue-size: "1024"
> 
>   monitor-aggregation: medium
> 
>   monitor-aggregation-flags: all
> 
>   monitor-aggregation-interval: 5s
> 
>   node-port-bind-protection: "true"
> 
>   nodes-gc-interval: 5m0s
> 
>   operator-api-serve-addr: '[::1]:9234'
> 
>   operator-prometheus-serve-addr: :9963
> 
>   preallocate-bpf-maps: "false"
> 
>   procfs: /host/proc
> 
>   proxy-connect-timeout: "2"
> 
>   proxy-idle-timeout-seconds: "60"
> 
>   proxy-max-connection-duration-seconds: "0"
> 
>   proxy-max-requests-per-connection: "0"
> 
>   proxy-xff-num-trusted-hops-egress: "0"
> 
>   proxy-xff-num-trusted-hops-ingress: "0"
> 
>   remove-cilium-node-taints: "true"
> 
>   routing-mode: tunnel
> 
>   service-no-backend-response: reject
> 
>   set-cilium-is-up-condition: "true"
> 
>   set-cilium-node-taints: "true"
> 
>   sidecar-istio-proxy-image: cilium/istio_proxy
> 
>   skip-cnp-status-startup-clean: "false"
> 
>   synchronize-k8s-nodes: "true"
> 
>   tofqdns-dns-reject-response-code: refused
> 
>   tofqdns-enable-dns-compression: "true"
> 
>   tofqdns-endpoint-max-ip-per-hostname: "50"
> 
>   tofqdns-idle-connection-grace-period: 0s
> 
>   tofqdns-max-deferred-connection-deletes: "10000"
> 
>   tofqdns-proxy-response-max-delay: 100ms
> 
>   tunnel-protocol: vxlan
> 
>   unmanaged-pod-watcher-interval: "15"
> 
>   vtep-cidr: ""
> 
>   vtep-endpoint: ""
> 
>   vtep-mac: ""
> 
>   vtep-mask: ""
> 
>   write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conflist
> 
> kind: ConfigMap
> 
> metadata:
> 
>   annotations:
> 
>     meta.helm.sh/release-name: cilium
> 
>     meta.helm.sh/release-namespace: kube-system
> 
>   creationTimestamp: "2024-06-19T14:43:49Z"
> 
>   labels:
> 
>     app.kubernetes.io/managed-by: Helm
> 
>   name: cilium-config
> 
>   namespace: kube-system
> 
>   resourceVersion: "28346"
> 
>   uid: 9105f71f-e6d6-44fb-ac9a-e2c2c13b4f2d
> 
> ```
> 
> 
> 
> ciliumNode
> 
> ```
> 
> apiVersion: v1
> 
> items:
> 
> - apiVersion: cilium.io/v2
> 
>   kind: CiliumNode
> 
>   metadata:
> 
>     creationTimestamp: "2024-06-19T14:44:00Z"
> 
>     generation: 7
> 
>     labels:
> 
>       beta.kubernetes.io/arch: amd64
> 
>       beta.kubernetes.io/os: linux
> 
>       kubernetes.io/arch: amd64
> 
>       kubernetes.io/hostname: cloudvm
> 
>       kubernetes.io/os: linux
> 
>       node-role.kubernetes.io/control-plane: ""
> 
>       node.kubernetes.io/exclude-from-external-load-balancers: ""
> 
>     name: cloudvm
> 
>     ownerReferences:
> 
>     - apiVersion: v1
> 
>       kind: Node
> 
>       name: cloudvm
> 
>       uid: afdd3b48-ef12-413b-a330-68403c526317
> 
>     resourceVersion: "29245"
> 
>     uid: b6f2b66e-0540-4c1a-8f58-95634fd9b8c5
> 
>   spec:
> 
>     addresses:
> 
>     - ip: something::1
> 
>       type: InternalIP
> 
>     - ip: fd00:10:244::e8e9
> 
>       type: CiliumInternalIP
> 
>     alibaba-cloud: {}
> 
>     azure: {}
> 
>     bootid: 458933fb-bf2f-4679-8d37-e0665926991e
> 
>     encryption: {}
> 
>     eni: {}
> 
>     health:
> 
>       ipv6: fd00:10:244::335e
> 
>     ingress:
> 
>       ipv6: fd00:10:244::1939
> 
>     ipam:
> 
>       podCIDRs:
> 
>       - fd00:10:244::/64
> 
>       pools: {}
> 
> kind: List
> 
> metadata:
> 
>   resourceVersion: ""
> 
> (env)
> 
> ```
> 
> 
> 
> Forcing 
> 
> ```
> 
> enable-ipv4-masquerade: "false"
> 
> ```
> 
> and redeploying does not seem to fix it either

It would seem that you haven't disabled tunneling? Tunneling over v6 is currently NOT supported thus IPv6-only can work only in native routing mode.

**Comment by dioguerra** [comment]
This as nothing to do with tunneling, as it is disable by default.
It seems that the routingMode (in my case) needs to be set to native. after that error changes.

Have a look into the options tested by IPv6 only configurations in the project git workflows available here: https://github.com/cilium/cilium/blob/fb7e01b4875cbb47b9c8cec8c4da3dfd96ba6490/.github/workflows/tests-smoke-ipv6.yaml#L122

And fix it to your deployment. This made mine work (at least it does not error anymore) and coredns comes up

**Comment by samip5** [comment]
> This has nothing to do with tunneling, as it is disable by default.

It's NOT disabled by default, when this issue was created at least.

**Comment by joestringer** [comment]
Reading through from the early posts and recent posts, I think that the summary of this issue is: Cilium doesn't support tunneling over IPv6, and if configured to attempt this, then it will fail out with the error listed in the description. The solution is to change the routingMode to `native` to avoid attempting to tunnel over the IPv6 network.

I think it would be reasonable to improve the cilium-agent startup logic to detect the case where routingMode is tunnel and IPv4 is disabled, and report a clearer fatal error that this is an unsupported configuration. Feel free to submit a PR for this and refer to this issue for context.

If you would like support for tunneling over IPv6, please :+1: over at https://github.com/cilium/cilium/issues/17240 or coordinate with other contributors to develop the solution there.

If you're experiencing another issue on an IPv6-only environment, feel free to either share your experiences and how you solved the error in this issue, or alternatively please file a new issue describing exactly the configuration and symptoms you are experiencing.
