### ISSUE TITLE
Cilium timeout error for Arm64 on CircleCI

### ISSUE THREAD

**Issue by odidev** [cilium/cilium#21549]
**@André Martins**,  

I tried running the smoketest.yaml with CircleCi, and I am getting the below time out error for deployment pods. 

```
timed out waiting for the condition on deployments/pod-to-a-denied-cnp 
timed out waiting for the condition on deployments/pod-to-b-multi-node-nodeport 
```

**Logs of Circleci for reference**: https://app.circleci.com/pipelines/github/odidev/cilium/1/workflows/64e57aaa-d0ae-4570-8477-6a23485378e3/jobs/1 

**Config.yml file for reference**: https://github.com/odidev/cilium/blob/master/.circleci/config.yml 

It would be helpful if you could share some points for the above issue.

**Comment by odidev** [comment]
@tgraf ,could you please look into the above issue?

**Comment by aanm** [comment]
@odidev have you tried deploy cilium with [cilium-cli](https://github.com/cilium/cilium-cli)?

**Comment by odidev** [comment]
@ [aanm,](https://github.com/aanm) I have tried to deploy cilium in cilium-cli by using the make install command, which is present in the Readme.md file. I have verified where those cilium binaries are present. They are present in the /usr/local/bin/ directory. 

I have tried to run the Kind.yaml using GitHub actions for amd64 and arm64. For amd64, the connectivity test fails. For arm64 architecture, by using the GitHub runner it is failing to build and install cilium CLI binary. Please have a look at the logs: 

**Logs of Amd64 architecture**: https://github.com/anilreddypuresoftware/cilium-cli/actions/runs/3435021657/jobs/5726905326 

**Logs of Arm64 architecture**: https://github.com/anilreddypuresoftware/cilium-cli/actions/runs/3436250524/jobs/5729557404 

Also, in cilium package I was facing timeout error in the smoketest.yaml file. Due to this time out error some pods are not running. It would be helpful if you could share some pointers for the test issue. 

**Logs of Circleci for reference**: https://app.circleci.com/pipelines/github/odidev/cilium/1/workflows/64e57aaa-d0ae-4570-8477-6a23485378e3/jobs/1 

**Config.yml file for reference**: https://github.com/odidev/cilium/blob/master/.circleci/config.yml

**Comment by aanm** [comment]
Traffic is dropped with the following logs:
```
  ❓ [79] Nov 10 08:25:07.018: test-namespace/client2-f6bf998db-wtts5:58976 -> one.one.one.one:80 from-endpoint FORWARDED TRAFFIC_DIRECTION_UNKNOWN DROP_REASON_UNKNOWN (TCP Flags: ACK)
  ❓ [80] Nov 10 08:25:07.018: test-namespace/client2-f6bf998db-wtts5:58976 -> one.one.one.one:80 to-proxy FORWARDED EGRESS DROP_REASON_UNKNOWN (TCP Flags: ACK)
  ❓ [81] Nov 10 08:25:07.018: test-namespace/client2-f6bf998db-wtts5:58976 -> one.one.one.one:80 from-endpoint FORWARDED TRAFFIC_DIRECTION_UNKNOWN DROP_REASON_UNKNOWN (TCP Flags: ACK, FIN)
  ❓ [82] Nov 10 08:25:07.018: test-namespace/client2-f6bf998db-wtts5:58976 -> one.one.one.one:80 to-proxy FORWARDED EGRESS DROP_REASON_UNKNOWN (TCP Flags: ACK, FIN)
  ❓ [83] Nov 10 08:25:07.019: one.one.one.one:80 -> test-namespace/client2-f6bf998db-wtts5:58976 from-proxy FORWARDED TRAFFIC_DIRECTION_UNKNOWN DROP_REASON_UNKNOWN (TCP Flags: ACK, FIN)
  ❓ [84] Nov 10 08:25:07.019: one.one.one.one:80 -> test-namespace/client2-f6bf998db-wtts5:58976 to-endpoint FORWARDED EGRESS DROP_REASON_UNKNOWN (TCP Flags: ACK, FIN)
  ❓ [85] Nov 10 08:25:07.019: test-namespace/client2-f6bf998db-wtts5:58976 -> one.one.one.one:80 from-endpoint FORWARDED TRAFFIC_DIRECTION_UNKNOWN DROP_REASON_UNKNOWN (TCP Flags: ACK)
  ❓ [86] Nov 10 08:25:07.019: test-namespace/client2-f6bf998db-wtts5:58976 -> one.one.one.one:80 to-proxy FORWARDED EGRESS DROP_REASON_UNKNOWN (TCP Flags: ACK)
```

**Comment by odidev** [comment]
@ [aanm,](https://github.com/aanm) I have tried to deploy cilium in cilium-cli by using the make install command as per Readme.md file. I have verified that cilium binaries installation. It is present in the /usr/local/bin/ directory. 

I also tried to run the Kind.yaml using GitHub actions for amd64 and arm64(using self-hosted agent). For both architectures it is deployed successfully. 

For arm64 architecture, I have used self-hosted runner to deploy in GHA. 

I have added self-hosted runner by using this link: https://github.com/odidev/cilium-cli/settings/actions/runners/new?arch=arm64&os=linux 

Please have a look at the logs: 

**Workflow file of self-hosted runner**: https://github.com/odidev/cilium-cli/actions/runs/3477322438/workflow  

**Logs of Amd64 architecture**: https://github.com/odidev/cilium-cli/actions/runs/3477539409/jobs/5813819478 

**Logs of Arm64 architecture**: https://github.com/odidev/cilium-cli/actions/runs/3477322438/jobs/5813364222

**Comment by odidev** [comment]
@aanm, Could you please share your feedback regarding the above issue.
