### ISSUE TITLE
CFP: Push Cilium images to GitHub container registry

### ISSUE THREAD

**Issue by sandipanpanda** [cilium/cilium#21543]
## Cilium Feature Proposal
        

**Is your feature request related to a problem?**
Yes

If so, please describe the problem

Work is being done to generate Software Bill of Materials (SBOM) from Cilium release images and attach the generated SBOM to the images in Quay in an effort to improve the security posture of the Cilium family’s open source projects . While testing SBOM generation in https://github.com/cilium/cilium/pull/21435, it was found that Quay [doesn’t support](https://github.com/cilium/cilium/actions/runs/3115811565/jobs/5053074638#step:20:13) 'text/spdx' manifest. So, the generated SBOM can’t be pushed to Quay. This is a known issue, ko generates and uploads an SBOM for every image it produces by default and face similar issue: https://github.com/ko-build/ko/issues/532.

**Describe the feature you'd like**
The generated images can be pushed to GitHub container registry in addition to Quay. Then the generated SBOM can be attached to images in GitHub container registry.

**Comment by joestringer** [comment]
Makes sense, I think we can just look for places where we push tags to DockerHub today and also push to ghcr. From a quick glance, I don't think that any specific features need to be enabled on the repository.

**Comment by dmesser** [comment]
Quay.io product manager here. What specific MIME types outside of `text/spdx` are expected by Cilium? Quay.io is configured to only accept a fixed set of OCI types and that's why this currently fails.

**Comment by joestringer** [comment]
Perhaps @sandipanpanda could speak more to this, but I believe we are planning to use [k8s bom](https://github.com/kubernetes-sigs/bom) and sigstore (related: https://docs.sigstore.dev/cosign/sign#signature-location-and-management) so I think it's mostly around what those tools push as OCI artifacts. I don't think we have any particular Cilium-specific constraints around this so it's mostly about what those projects are planning to generate.

**Comment by sandipanpanda** [comment]
Hi there, there has been some progress on this issue recently. Our initial approach was to attach the SBOM using
`cosign attach sbom --sbom sbom.spdx quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.name }}:${{ steps.tag.outputs.tag }}` and then signing the container image. But attaching SBOMs this way does not sign them. While trying to attach SBOM this way, we found that Quay doesn’t support 'text/spdx' manifest as seen in https://github.com/cilium/cilium/actions/runs/3100873683/jobs/5021632419.

I have noticed that in cosign docs that we can include the SBOM in an [in-toto](https://in-toto.io/) attestation; see https://docs.sigstore.dev/cosign/other_types#sboms-software-bill-of-materials. So I changed my approach to signing the SBOM attestation while attaching to the image using `cosign attest --type spdx --predicate sbom.spdx quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/${{ matrix.name }}:${{ steps.tag.outputs.tag }}` and attaching the SBOM to Quay using this method worked as you can see in the `Image CI Build - Test / build-and-push-prs` [workflows](https://github.com/cilium/cilium/actions/runs/3199021062) run in https://github.com/cilium/cilium/pull/21435. :tada: For example, https://github.com/cilium/cilium/actions/runs/3199021062/jobs/5224299458#step:20:1

The SBOM attestation can be verified using
`cosign verify-attestation --type spdx quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/${{ matrix.name }}:${{ steps.tag.outputs.tag }}`

I think we should continue using this approach, as in this way the SBOM is signed while attaching it to the container image. So we are unaffected by whether Quay starts supporting 'text/spdx' manifest as of now. Moreover, other projects can start using this approach to attach SBOM to Quay images until Quay starts supporting them by default. Or, there is a workaround to support 'type/spdx' media types in Quay by [Adding other OCI media types to Quay](https://docs.projectquay.io/config_quay.html#other-oci-artifacts-with-quay).

**Comment by sandipanpanda** [comment]
Closing this as the issue has been resolved and this feature is no longer needed.

**Comment by dmesser** [comment]
FYI quay.io does support those OCI types now: https://twitter.com/quayio/status/1580121221080891392
