### ISSUE TITLE
NATted traffic from the pods does not reach the services

### ISSUE THREAD

**Issue by msarti** [cilium/cilium#21545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have deployed a VPN (tried both OpenVPN and Wireguard) as a pod, exposed as HostPort. Traffic from the VPN reaches both pod addresses and host addresses, but does not reach the service network. From inside the pod I don't see the problem, so I guess the natted traffic is somehow blocked.
Cilium is installed with kube-proxy replacement and Wireguard encryption.
For example, trying to query the dns from the service I get no answer:

`dig @10.106.0.10 kubernetes.default.svc.cluster.local`

While if I directly query a CoreDNS pod I get the correct result:

```
dig @10.6.4.102 kubernetes.default.svc.cluster.local

; <<>> DiG 9.18.1-1ubuntu1.2-Ubuntu <<>> @10.6.4.102 kubernetes.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42534
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 63b72753ea42101f (echoed)
;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN	A

;; ANSWER SECTION:
kubernetes.default.svc.cluster.local. 30 IN A	10.106.0.1

;; Query time: 112 msec
;; SERVER: 10.6.4.102#53(10.6.4.102) (UDP)
;; WHEN: Sun Oct 02 16:58:32 CEST 2022
;; MSG SIZE  rcvd: 123

```

Analyzing with tcpdump I see that the packets come out with the right address from the virtual interface:

```
tcpdump -i lxcdd0d26555ae7 -nn -s0 -v dst port 53 or src port 53
tcpdump: listening on lxcdd0d26555ae7, link-type EN10MB (Ethernet), snapshot length 262144 bytes
15:03:51.746181 IP (tos 0x0, ttl 63, id 33746, offset 0, flags [none], proto UDP (17), length 102)
    10.6.3.34.43986 > 10.106.0.10.53: 19465+ [1au] A? kubernetes.default.svc.cluster.local. (74)
```
This instead is the tcpdump of the request made directly to the pod, as you can see there is the answer:

```
tcpdump -i lxcdd0d26555ae7 -nn -s0 -v dst port 53 or src port 53
tcpdump: listening on lxcdd0d26555ae7, link-type EN10MB (Ethernet), snapshot length 262144 bytes
15:08:24.709271 IP (tos 0x0, ttl 63, id 13383, offset 0, flags [none], proto UDP (17), length 102)
    10.6.3.34.45473 > 10.6.4.102.53: 45179+ [1au] A? kubernetes.default.svc.cluster.local. (74)
15:08:24.710534 IP (tos 0x0, ttl 60, id 43233, offset 0, flags [DF], proto UDP (17), length 151)
    10.6.4.102.53 > 10.6.3.34.45473: 45179*- 1/0/1 kubernetes.default.svc.cluster.local. A 10.106.0.1 (123)
```

### Cilium Version

Client: 1.11.6 fee2d77 2022-06-13T16:02:58-07:00 go version go1.17.11 linux/amd64
Daemon: 1.11.6 fee2d77 2022-06-13T16:02:58-07:00 go version go1.17.11 linux/amd64

### Kernel Version

Linux vin-1 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msarti** [comment]
I add that the issue is not limited to the DNS service but to all the services.
Let me know if you need more info.

**Comment by aanm** [comment]
@msarti feel free to submit a PR that adds documentation with your findings. Thank you
