### ISSUE TITLE
Relicense or replace `ghash.h`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#21546]
File [`bpf/lib/ghash.h`](https://github.com/cilium/cilium/blob/61d7ff0083f40cc620990d96e1bf50c3e074d5c1/bpf/lib/ghash.h) is under a GPLv2 license but the CNCF "requires" us dual-license code under one of their approved licenses (cf. https://github.com/cilium/cilium/issues/18823). The rest of the BPF codebase is dual licensed under GPLv2 and 2-Clause BSD.

We should therefore either:
- Relicense if this hash implementation ended up in the public domain (unlikely?).
- Replace it with some other hash algorithm otherwise.

This hash implementation is [used for RSS steering](https://github.com/cilium/cilium/blob/b4ed8cdc696cf87bcf15ce12d6bbace6c4f08c04/bpf/lib/nodeport.h#L225) to backends in the case of [the standalone load balancer](https://cilium.io/blog/2021/05/20/cilium-110/#standalonelb) with IPIP (outer source IP prefix is hash of inner headers).

**Comment by qmonnet** [comment]
> Relicense if this hash implementation ended up in the public domain (unlikely?).

Not that I'm aware of. Looks like there was a discussion three years ago [clarifying its license as GPL-2.0](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919356).

**Comment by pchaigno** [comment]
@borkmann Any preferences on the above solutions? :point_up:

**Comment by borkmann** [comment]
> @borkmann Any preferences on the above solutions? ☝️

Thanks for the investigation, going with option 2 sounds good to me!
