### ISSUE TITLE
CFP: Support bpf-ct-timeout-* options for cilium-agent on helm chart values

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#21569]
## Cilium Feature Proposal
        
Support the following options on helm chart values.

- bpf-ct-timeout-regular-any
- bpf-ct-timeout-regular-tcp
- bpf-ct-timeout-regular-tcp-fin
- bpf-ct-timeout-regular-tcp-syn
- bpf-ct-timeout-service-any
- bpf-ct-timeout-service-tcp
- bpf-ct-timeout-service-tcp-grace

**Is your feature request related to a problem?**

Currently the helm chart doesn't support bpf-ct-timeout-* options, so we needed to patch the cilium-config cm generated with `helm template`. However it doesn't change `cilium.io/cilium-configmap-checksum`, so we need to restart cilium-agent manually.
https://github.com/cybozu-go/neco/pull/2108

I know we can modify those options with cilium cli, but we manage configuration files in our repository following the git-ops manner, and don't normally modify configuration manually.

**Describe the feature you'd like**

Support bpf-ct-timeout-* options for cilium-agent on helm chart values.

**Comment by ysksuzuki** [comment]
I think I can configure bpf-ct-timeout-* using extraConfig. I didn't know that.
https://github.com/cilium/cilium/blob/61d7ff0083f40cc620990d96e1bf50c3e074d5c1/install/kubernetes/cilium/README.md

**Comment by aanm** [comment]
Yes, you can use them using extraConfig. Does that work for you?

**Comment by ysksuzuki** [comment]
Yes, that works for me.

**Comment by ysksuzuki** [comment]
I'm planning to send a PR for it.
