### ISSUE TITLE
Agent metrics reporting failing controllers

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#21597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`cilium_controllers_failing` is >0 but there are no errors in the log and `cilium status` reports 100% healthy controllers

### Cilium Version

`1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64`

### Kernel Version

`Linux ip-10-199-29-110 5.15.0-1017-aws #21~20.04.1-Ubuntu SMP Fri Aug 5 11:44:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512", GitCommit:"94138dfbea757d7aaf3b205419578ef186dd5efb", GitTreeState:"clean", BuildDate:"2022-08-31T19:15:48Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
I suspect that `ipcache-inject-labels` controller might fail at startup and then fix itself after some time, and I wonder if that causes the metric to increment, but is never decremented.
