### ISSUE TITLE
Unmanaged pods with preemptible nodes on GKE

### ISSUE THREAD

**Issue by williamclot** [cilium/cilium#21594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Our organisation is using GKE with [preemptible](https://cloud.google.com/compute/docs/instances/preemptible) node pools. The preemptible VMs used in those node pools aren't _always available_ so we see some VMs being stopped and recreated from time to time. We use these VMs to reduce cost and with proper taints, tolerations & node affinity configuration we're able to run non-sensitive workloads on these node pools while running other more sensitive workloads on proper VMs. 

When using Cilium with preemptible VMs in GKE, we've noticed that when a preemptible VM linked to a node is deleted, the underlying compute instance in GCP gets recreated but the k8s node _remains the same_. Because the k8s node isn’t recreated the node pool taint doesn’t get reapplied and we end up in situations where pods are potentially unmanaged if cilium isn't up and ready when other pods get created. Ultimately in these situations we then see legitimate traffic being blocked.

I wonder if somehow the `cilium-operator` could help in this situation: from what I can see the operator is already responsible for watching cilium-agent pods and removing the node taint once cilium is ready. Would it somehow be possible to taint back a node when the operator sees the cilium-agent not running/modified or deleted on a node?

### Cilium Version

Cilium v1.12.0

### Kernel Version

COS-5.10.133

### Kubernetes Version

v1.22.12-gke.1200

### Anything else?

I did pop a message in the Cilium kubernetes slack channel too: https://cilium.slack.com/archives/C53TG4J4R/p1664808717519899  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@williamclot thank you for opening the GH issue.
> Would it somehow be possible to taint back a node when the operator sees the cilium-agent not running/modified or deleted on a node?

It would be possible but the race condition would still happen since the node would start and it would immediately create unmanaged pods while Cilium Operator didn't add the taint on the node. What if Cilium Operator deleted the pods that are not unmanaged by Cilium, would that be acceptable?

**Comment by williamclot** [comment]
Hi @aanm, thanks for your answer and for looking into this issue.

I think the deletion of unmanaged pods by cilium would work, generally speaking workloads running on these preemptible nodes should be fairly tolerant to deletion/restarts.

Does the Cilium operator support this pod deletion feature or is this something that would require development?

**Comment by aanm** [comment]
@williamclot There is existing code [here](https://github.com/cilium/cilium/blob/af61d36f5f20a7f3b07b8430a400073eb20c411c/operator/cmd/k8s_pod_controller.go#L32) that does this but only for kube-dns pods. I think it does make sense to enable it for all pods and not only kube-dns. Would you like to submit a PR that implements this?

**Comment by philpearl** [comment]
I'm also trying to pursue this with GKE: https://github.com/kubernetes/cloud-provider-gcp/issues/404. Would appreciate it if a Cilium expert could check if I'm making any sense!

Do you think it's safe to restart absolutely any unmanaged pod, or would it be better to have an annotation or label to look for? Or is there something there already that's means you'd only be looking at pods that rely on cilium networking?

**Comment by aanm** [comment]
@philpearl have you checked https://github.com/cilium/cilium/pull/22257?
