### ISSUE TITLE
RE: Cilium v1.12.2  API issues [Errors encountered while deleting endpoint], [unable to create endpoint, putEndpointIdTooManyRequests]

### ISSUE THREAD

**Issue by ajaykumarmandapati** [cilium/cilium#21604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

From time to time we see API issues with cilium `v1.12.2` on EKS `v1.23`, cilium agent is unresponsive on a particular node which then disrupts all networking on this node. 
Seems to be related to a closed issue - https://github.com/cilium/cilium/issues/19440

**Our only way to fix it at the moment is to cordon off and delete such a node.** 

**NOTE:** we were already experiencing this issue on v1.12.1 and tried to upgrade to see if it fixes but that did not help us.

### Cilium Version

`v1.12.1 and v1.12.2`

### Kernel Version

`Linux ip-10-32-117-219.eu-central-1.compute.internal 5.10.130 #1 SMP Tue Aug 30 01:05:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.23.7-eks-7709a84`

`Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.10-eks-15b7512", GitCommit:"cd6399691d9b1fed9ec20c9c5e82f5993c3f42cb", GitTreeState:"clean", BuildDate:"2022-08-31T19:17:01Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}`

### Relevant log output

```shell
2022-10-06 05:03:29.445,"level=warning msg=""Errors encountered while deleting endpoint"" error=""Cilium API client timeout exceeded"" eventUUID=5034197b-71e3-47c1-9d1b-66441852b46f subsys=cilium-cni"
2022-10-06 05:01:59.327,"level=warning msg=""Errors encountered while deleting endpoint"" error=""Cilium API client timeout exceeded"" eventUUID=892050ad-1e3f-4660-9304-1363d3d9e2e9 subsys=cilium-cni"
2022-10-06 04:59:54.405,"level=warning msg=""Errors encountered while deleting endpoint"" error=""Cilium API client timeout exceeded"" eventUUID=cb08d65f-233b-4ea5-a2ea-ea4ef8f7bc6c subsys=cilium-cni"
2022-10-05 19:37:26.702,"level=warning msg=""Errors encountered while deleting endpoint"" error=""[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound "" eventUUID=c1e23610-7e55-4142-92f2-bac6802a8333 subsys=cilium-cni"
2022-10-05 19:37:26.621,"level=warning msg=""Errors encountered while deleting endpoint"" error=""[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound "" eventUUID=377ddd9f-5ac3-4caa-ae13-b7bc52237f68 subsys=cilium-cni"
2022-10-05 19:30:26.494,"level=warning msg=""Errors encountered while deleting endpoint"" error=""[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound "" eventUUID=fface7af-13ed-44f1-9b78-12da9709e878 subsys=cilium-cni"
2022-10-05 19:30:26.414,"level=warning msg=""Errors encountered while deleting endpoint"" error=""[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound "" eventUUID=0395ae19-4fdd-4dd9-8240-52884251e208 subsys=cilium-cni"
2022-10-05 19:07:26.202,"level=warning msg=""Errors encountered while deleting endpoint"" error=""[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound "" eventUUID=220ceb10-b62b-4d47-bdba-627775b252a6 subsys=cilium-cni"
2022-10-05 19:07:26.138,"level=warning msg=""Errors encountered while deleting endpoint"" error=""[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound "" eventUUID=70b8453b-fd74-4f9f-a9ef-1d04cb2c312c subsys=cilium-cni"
2022-10-05 18:56:25.982,"level=warning msg=""Errors encountered while deleting endpoint"" error=""[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound "" eventUUID=046818cb-220e-4795-802a-13e03dcc7069 subsys=cilium-cni"
2022-10-05 18:56:25.916,"level=warning msg=""Errors encountered while deleting endpoint"" error=""[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound "" eventUUID=641a8561-f066-4e99-9bee-9002dcdb6f28 subsys=cilium-cni"
2022-10-05 18:54:25.833,"level=warning msg=""Errors encountered while deleting endpoint"" error=""[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound "" eventUUID=f33b93fe-3373-4f70-89a2-655f66979ab0 subsys=cilium-cni"

Warning  FailedCreatePodSandBox  83s (x147 over 3h40m)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "24467e4fb58266c69f42cb4a9bc0cb8232a25c463b319dbd2a70202ac1b6dc6f": plugin type="cilium-cni" name="cilium" failed (add): unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests
```

### Anything else?

Our EKS nodes run on `bottle-rocket` AMI's

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ajaykumarmandapati** [comment]
![image](https://user-images.githubusercontent.com/47316512/194513676-e6b3b6aa-b3dc-4b4c-bfbd-52c562761405.png)
We also see from cilium-cli, there is a broken pod and simply deleting this solves our issue from time to time.

**Comment by ajaykumarmandapati** [comment]
Any movement or acknowledgment of this? :)

**Comment by aanm** [comment]
@ajaykumarmandapati this looks similar to https://github.com/cilium/cilium/issues/20915

**Comment by ajaykumarmandapati** [comment]
Yup looks like any increased activity on the cluster causes this network outage 😞  @aanm

**Comment by therapy-lf** [comment]
Any way around it except downgrading cilium?

**Comment by ajaykumarmandapati** [comment]
we got around this by increasing API limits for cilium via [extraConfig](https://artifacthub.io/packages/helm/cilium/cilium/1.12.2?modal=values&path=extraConfig)
e.g. 
`extraConfig = {
        "api-rate-limit" : "{\"endpoint-create\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\", \"endpoint-delete\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\", \"endpoint-get\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\", \"endpoint-list\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\", \"endpoint-patch\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\"}"
      }`

**Comment by ikarlashov** [comment]
Follow-up. This could probably save some time for ppl who need it in yaml format:
`extraConfig:
      "api-rate-limit": "{\"endpoint-create\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\", \"endpoint-delete\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\", \"endpoint-get\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\", \"endpoint-list\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\", \"endpoint-patch\": \"rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true\"}"`

**Comment by christarazi** [comment]
@ajaykumarmandapati @ikarlashov It's worth mentioning that increasing limits on endpoint-delete probably works, however for endpoint-create, I'd very much doubt that the underlying kernel can handle this many endpoint creations at once. 

This is because loading BPF programs into the kernel is serialized, i.e. cannot be done in parallel, so if there are a burst of pods, loading their BPF programs into the kernel will immediately serialize their creation from the Cilium point of view. To be clear, Cilium can handle parallel pod creations, but when it reaches the BPF program loading stage of the creation, it will be serialized.

This rate-limiting was put in place to actually reduce the pressure of Cilium on the kernel and return that pressure back to the API calls to create pods. Without this, the system can get overwhelmed and cause undesirable behavior as it's overloaded. Just an FYI.

**Comment by christarazi** [comment]
@ajaykumarmandapati Did increasing the endpoint-delete limit resolve the symptoms? If so, do you consider this issue closed?

**Comment by ajaykumarmandapati** [comment]
> @ajaykumarmandapati Did increasing the endpoint-delete limit resolve the symptoms? If so, do you consider this issue closed?

Yup, it seems to have fixed it for us. 👍🏾

**Comment by m-yosefpor** [comment]
Same issue here with cilium `v1.12.2`. Increasing the ratelimit numbers stopped the putEndpointIdTooManyRequests events, but now it the issue turned to sth else:

> snapp-ode-018                                9h          Warning   FailedKillPod                                pod/money-4-b6b5g                                                         error killing pod: failed to "KillPodSandbox" for "45777b55-18c5-413c-af99-3dd32bc2d164" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for pod sandbox k8s_money-4-b6b5g_snapp-ode-018_45777b55-18c5-413c-af99-3dd32bc2d164_0(dc8d3cc8b6df32d192e1fb33035c4ed96aa25f36c1d7916a0971bf2356b4a38d): error removing pod snapp-ode-018_money-4-b6b5g from CNI network \"multus-cni-network\": plugin type=\"multus\" name=\"multus-cni-network\" failed (delete): netplugin failed: \"2023-03-02T07:40:35Z [error] SetNetworkStatus: failed to query the pod money-4-b6b5g in out of cluster comm: pods \\\"money-4-b6b5g\\\" not found\\n2023-03-02T07:40:35Z [error] Multus: error unsetting the networks status: SetNetworkStatus: failed to query the pod money-4-b6b5g in out of cluster comm: pods \\\"money-4-b6b5g\\\" not found\\n2023-03-02T07:40:35Z [verbose] Del: snapp-ode-018:money-4-b6b5g:unknownUID:cilium:eth0 {\\\"cniVersion\\\":\\\"0.3.1\\\",\\\"enable-debug\\\":false,\\\"log-file\\\":\\\"/var/run/cilium/cilium-cni.log\\\",\\\"name\\\":\\\"cilium\\\",\\\"type\\\":\\\"cilium-cni\\\"}\\n\""



When checking cliliium logs on the nodes:
> level=warning msg="Errors encountered while deleting endpoint" error="Cilium API client timeout exceeded" subsys=cilium-cni

**Comment by christarazi** [comment]
I would suggest upgrading to the latest v1.12 version. There have been deadlock fixes in recent releases and the symptoms you described sound like deadlocks.

**Comment by ajaykumarmandapati** [comment]
> I would suggest upgrading to the latest v1.12 version. There have been deadlock fixes in recent releases and the symptoms you described sound like deadlocks.

Do you mean `1.13.x` ?

**Comment by satishh1988** [comment]
Hi All,

seeing the similar error on the CNI logs  " level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni "

@ajaykumarmandapati  can you please share the details on where we have to apply the work around that you mentioned to increase api-rate-limit

version details:

**cilium version**
cilium-cli: v0.15.0 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.4
cilium image (stable): v1.13.4
cilium image (running): 1.13.4

**kernel version:**
5.15.0-76-generic

**cni logs :**

level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to enter namespace \"\", will not delete interface" error="failed to Statfs \"\": no such file or directory" subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to enter namespace \"\", will not delete interface" error="failed to Statfs \"\": no such file or directory" subsys=cilium-cni

**Comment by ajaykumarmandapati** [comment]
> Hi All,
> 
> seeing the similar error on the CNI logs " level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni "
> 
> @ajaykumarmandapati can you please share the details on where we have to apply the work around that you mentioned to increase api-rate-limit
> 
> version details:
> 
> **cilium version** cilium-cli: v0.15.0 compiled with go1.20.4 on linux/amd64 cilium image (default): v1.13.4 cilium image (stable): v1.13.4 cilium image (running): 1.13.4
> 
> **kernel version:** 5.15.0-76-generic
> 
> **Kubernetes version 1.24.0**
> 
> **cni logs :**
> 
> level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni level=warning msg="Unable to enter namespace "", will not delete interface" error="failed to Statfs "": no such file or directory" subsys=cilium-cni level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni level=warning msg="Unable to enter namespace "", will not delete interface" error="failed to Statfs "": no such file or directory" subsys=cilium-cni

We do it like this as mentioned in my comment above - https://github.com/cilium/cilium/issues/21604#issuecomment-1311676637

**Comment by satishh1988** [comment]
@ajaykumarmandapati  am not sure on where to add the extraConfig. can you help. deployment was done using the cilium install after downloading the package. i dont have any yaml with me.

**Comment by ajaykumarmandapati** [comment]
How are you installing cilium? via Helm or any other way.

> @ajaykumarmandapati am not sure on where to add the extraConfig. can you help. deployment was done using the cilium install after downloading the package. i dont have any yaml with me.

**Comment by satishh1988** [comment]
following the cilium doc https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/ 

CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
CLI_ARCH=amd64
if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}

cilium install

**Comment by ajaykumarmandapati** [comment]
I'm not quite knowledgeable on how to pass config values when you use the `cilium-cli` to install cilium, we use `helm` based installation where we can pass them via `values.yaml`

Maybe this is a good direction to research - https://github.com/cilium/cilium-cli#install-examples

**Comment by satishh1988** [comment]
Thanks for sharing. i can uninstall the current installation and redeploy again using the helm. can you share the step where you use the value.yaml for installation.

i see the below command to deploy cilium via helm post adding the cilium repo.

helm install cilium cilium/cilium --version 1.13.4 \
  --namespace kube-system

**Comment by ajaykumarmandapati** [comment]
Like I had shared earlier - https://artifacthub.io/packages/helm/cilium/cilium/1.12.2?modal=values&path=extraConfig
