### ISSUE TITLE
No valid cgroup base path found: socket load-balancing tracing feature will not work

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#21609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium agent build from master logs

level=warning msg="No valid cgroup base path found: socket load-balancing tracing feature will not work. File a GitHub issuewith an example cgroup path for a pod by running command on Kubernetes node: sudo crictl inspectp -o=json $POD_ID | grep cgroupsPath" subsys=cgroup-manager

I don't have crictl command installed, any other alternative command to inspect the pod cgroupPath?

### Cilium Version

Cilium 1.12.90 b33adeb6f8 2022-09-29T11:12:42+02:00 go version go1.19.1 linux/amd64

### Kernel Version

Linux cilium-dev 5.18.0+

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20221006-120333.zip](https://github.com/cilium/cilium/files/9726605/cilium-sysdump-20221006-120333.zip)

### Relevant log output

```shell
level=warning msg="No valid cgroup base path found: socket load-balancing tracing feature will not work. File a GitHub issuewith an example cgroup path for a pod by running command on Kubernetes node: sudo crictl inspectp -o=json $POD_ID | grep cgroupsPath" subsys=cgroup-manager
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
If you don't have the crictl tool installed on k8s nodes in your cluster, then you can inspect the base cgroup path (the cilium default is `/var/run/cilium/cgroupv2)` for one of the pod IDs on a node. Usually, it's something like this `/var/run/cilium/cgroupv2/kubepods/burstable/pod782195ba-e3a3-4858-9db4-ff744ed37c58/.

**Comment by vincentmli** [comment]
I don't have kubepods under /var/run/cilium/cgroupv2

```
[root@cilium-dev home]# tree /var/run/cilium/cgroupv2
/var/run/cilium/cgroupv2
├── cgroup.controllers
├── cgroup.max.depth
├── cgroup.max.descendants
├── cgroup.procs
├── cgroup.stat
├── cgroup.subtree_control
├── cgroup.threads
└── cpu.stat
```

**Comment by aditighag** [comment]
Are there any pods running on the cluster at all when you ran the above command? Is this the cilium dev VM?

**Comment by vincentmli** [comment]
yes, there are pods running, it is my  k8s cluster test lab with cilium image built from master branch and deployed, it is not cilium dev VM, sorry the node hostname might get you confused :), I also attached sysdump
```
[root@cilium-dev ~]# kubectl get po -o wide 
NAME                             READY   STATUS    RESTARTS   AGE   IP              NODE                     NOMINATED NODE   READINESS GATES
busybox-master-f97ff47c5-bts97   1/1     Running   16         16h   10.42.0.156     cilium-dev               <none>           <none>
deathstar-6f87496b94-99vwl       1/1     Running   0          16h   10.42.0.228     cilium-dev               <none>           <none>
deathstar-6f87496b94-gblpw       1/1     Running   0          16h   10.42.1.89      centos-dev.localdomain   <none>           <none>
f5-hello-world-7bb546899-xjsh6   1/1     Running   0          16h   10.42.1.14      centos-dev.localdomain   <none>           <none>
netshoot-ecap                    1/1     Running   1167       49d   10.169.72.239   cilium-dev               <none>     
```

**Comment by aditighag** [comment]
What's the output of `$ find /sys/fs/cgroup/ -name pod*` and `$ find /run/cilium/cgroupv2 -name pod*`?

**Comment by vincentmli** [comment]
> What's the output of `$ find /sys/fs/cgroup/ -name pod*` and `$ find /run/cilium/cgroupv2 -name pod*`?

nothing found, are you trying to find out the cgroup info for a pod? I am running k8s with docker, would docker inspect help find the info? there is busybox-master pod running in my node, here is cgroup info I could find from docker inspect

```
docker inspect 39749030df51 | grep -i 'cgroup'
            "CgroupnsMode": "host",
            "Cgroup": "",
            "CgroupParent": "kubepods-besteffort-pod8667b397_4131_4a8d_a4d5_d84cebd202bd.slice",
            "DeviceCgroupRules": null,
```

**Comment by vincentmli** [comment]
maybe this is what you are looking for? it looks you are looking for cgroup v2 info, but it appears my pod is on cgroup v1? 

```

[root@cilium-dev docker]# tree -L 1 /sys/fs/cgroup
/sys/fs/cgroup
├── blkio
├── cpu -> cpu,cpuacct
├── cpuacct -> cpu,cpuacct
├── cpu,cpuacct
├── cpuset
├── devices
├── freezer
├── hugetlb
├── memory
├── net_cls -> net_cls,net_prio
├── net_cls,net_prio
├── net_prio -> net_cls,net_prio
├── perf_event
├── pids
├── rdma
└── systemd

[root@cilium-dev docker]# tree -L 1 /sys/fs/cgroup/pids
/sys/fs/cgroup/pids
├── cgroup.clone_children
├── cgroup.procs
├── cgroup.sane_behavior
├── init.scope
├── kubepods.slice
├── notify_on_release
├── release_agent
├── system.slice
├── tasks
└── user.slice

[root@cilium-dev docker]# tree -L 2 /sys/fs/cgroup/pids
/sys/fs/cgroup/pids
├── cgroup.clone_children
├── cgroup.procs
├── cgroup.sane_behavior
├── init.scope
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── notify_on_release
│   ├── pids.current
│   ├── pids.events
│   ├── pids.max
│   └── tasks
├── kubepods.slice
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── kubepods-besteffort.slice
│   ├── kubepods-burstable.slice
│   ├── notify_on_release
│   ├── pids.current
│   ├── pids.events
│   ├── pids.max
│   └── tasks
```

**Comment by vincentmli** [comment]
more info after reading https://docs.docker.com/config/containers/runmetrics/, it looks my docker daemon /etc/docker/daemon.json `native.cgroupdriver=systemd` which says docker support cgroup v2, right?

```
{
  "exec-opts": ["native.cgroupdriver=systemd"], <====
  "log-driver": "json-file",
  "log-level": "",
  "log-opts": {
    "env": "os,customer",
    "labels": "somelabel",
    "max-file": "5",
    "max-size": "10m"
  }
}
```

to enable kernel with cgroup v2,  `systemd.unified_cgroup_hierarchy=1` can be added to kernel, but I don't have that added, meaning my kernel is running on cgroup v1, right? by the way, my kernel is custom build from bpf-next tree with version `5.18.0+`. 

does socket load-balancing tracing feature require kernel with cgroup v2?

**Comment by aditighag** [comment]
>systemd.unified_cgroup_hierarchy=1 can be added to kernel, but I don't have that added, meaning my kernel is running on cgroup v1, right?

Yes, that's right, you are on cgroups v1 controllers. Cgroups v2 controllers are needed only for kind like nested environments where kubernetes nodes are deployed as containers. If that's not the case with your environment, then you don't need to make any changes with respect to switching to cgroups v2 controllers. 

>does socket load-balancing tracing feature require kernel with cgroup v2?

Socket-lb feature requires cgroup v2. Most of the kernel versions (starting 4.9 I think?) supports both cgroup v1 and cgroup v2. I checked the sysdump, and cilium mounted cgroup v2 filesystem required for attaching BPF cgroup programs.

**Comment by aditighag** [comment]
> docker inspect 39749030df51 | grep -i 'cgroup'
>             "CgroupnsMode": "host",
>             "Cgroup": "",
>             "CgroupParent": "kubepods-besteffort-pod8667b397_4131_4a8d_a4d5_d84cebd202bd.slice",
>             "DeviceCgroupRules": null,
> ```

What's the full cgroup path for this pod? Based on your [comment](https://github.com/cilium/cilium/issues/21609#issuecomment-1275117922), try to locate it under `/run/cilium/cgroupv2/...kubepods.slice/kubepods-besteffort.slice/...`


Also, you are using systemd as the cgroup driver which isn't currently supported. It's listed in the follow-up issue - https://github.com/cilium/cilium/issues/21510.

**Comment by borkmann** [comment]
@aditighag looks like @aspsk hit this as well recently

**Comment by pchaigno** [comment]
We are also hitting this in the IPv6 Smoke Test. For example: https://github.com/cilium/cilium/actions/runs/3638261746
Sysdump: 
[cilium-sysdump-out.zip.zip](https://github.com/cilium/cilium/files/10175914/cilium-sysdump-out.zip.zip)

**Comment by joestringer** [comment]
Heads up that there was another fix in this area which addresses a race condition where the same error might occur: https://github.com/cilium/cilium/pull/27561 . I've lined it up for Cilium 1.14.2.
