### ISSUE TITLE
Kube-proxy replacement not working when running without privileges

### ISSUE THREAD

**Issue by jonkerj** [cilium/cilium#21603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm running this setup:
- Single node Kubernetes cluster based on Talos Linux (Talos Linux 1.2.3 with Kubernetes 1.25.0, installed without kube-proxy and without CNI)

Install Cilium using helm (this needs to be this complex as `SYS_MODULE` is not available on Talos Linux):

```
$ cat <<PR > postrend.sh
#!/bin/sh

set -e

$ cat <&0 > base.yaml
kubectl kustomize .
PR

$ cat <<PATCH > caps-patch.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: cilium-agent
          securityContext:
            capabilities:
              add:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_RESOURCE
                - PERFMON
                - BPF
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
                - SYS_ADMIN
      initContainers:
        - name: clean-cilium-state
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_RESOURCE
                - PERFMON
                - BPF
PATCH

$ cat <<KUST > kustomization.yaml
resources:
- base.yaml
patchesStrategicMerge:
- caps-patch.yaml
KUST

$ cat <VALUES > values.yaml
k8sServiceHost: <your loadbalancer IP>
k8sServicePort: 6443
kubeProxyReplacement: strict
operator:
  replicas: 1
securityContext:
  extraCapabilities:
  - PERFMON
  - BPF
  privileged: false
VALUES

$ helm upgrade --install -n kube-system --version 1.12.2 -f values.yaml --post-renderer ./postrend.sh cilium cilium/cilium
```

In my case, `coredns` is reliably crashlooping or otherwise unhappy about not being able to reach the kubernetes API. This can further be debugged by launching a pod that does something like `curl https://10.96.0.1:443/` (the `ClusterIP` Service `default/kubernetes`).

Funny thing is that when I change `securityContext.privileged` to `true` and upgrade the chart, the problem vanishes.

Inter-Pod communication works in both situations, even between nodes, as long as you connect to Pod IP and not through a service.

### Cilium Version

v1.12.2

### Kernel Version

5.15.68-talos

### Kubernetes Version

v1.25.0

### Sysdump

[cilium-sysdump-20221006-140816.zip](https://github.com/cilium/cilium/files/9724669/cilium-sysdump-20221006-140816.zip)

### Anything else?

I've upgraded to 1.13.0-rc1 without effect.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xiaods** [comment]
I use cilium ctl to install cilium 1.12.2
```
cilium install --helm-set-string=kubeProxyReplacement=strict,k8sServiceHost=<your loadbalancer IP>,k8sServicePort=6443
```
have a try on your os Talos Linux 1.2.3.

I think this is dependency  on os

**Comment by jonkerj** [comment]
This effectively deploys the helm chart (like I did), with the following values:

```
kubeProxyReplacement=strict
k8sServiceHost=<your loadbalancer IP>
k8sServicePort=6443
```

But it will also include the `SYS_MODULE` capability, which does not exist on Talos, so this install will fail.

I appreciate the help, but I think it's more useful to focus on debugging the kube proxy replacement while running unprivileged.

**Comment by jonkerj** [comment]
In the meanwhile, I've discovered there are two scenario's to get it working:

1. run privileged
2. deploy the `kube-proxy` DaemonSet

I think both are not really acceptable, IMO

**Comment by aanm** [comment]
It seems that it's a distribution issue since, as you said, the distribution doesn't provide `SYS_MODULE`?

**Comment by DWSR** [comment]
@aanm That's certainly one way to look at it.

The other way would be "Is it possible to do strict KPR without `SYS_MODULE`?"

**Comment by aanm** [comment]
@DWSR can you get `capsh --print` while running Cilium in privileged mode? Thanks

**Comment by DWSR** [comment]
> @DWSR can you get `capsh --print` while running Cilium in privileged mode? Thanks

```text
root@talos-v7n-kwk:/home/cilium# capsh --print
WARNING: libcap needs an update (cap=40 should have a name).
Current: =ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,38,39,40
Ambient set =
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root) euid=0(root)
gid=0(root)
groups=
Guessed mode: UNCERTAIN (0)
```

**Comment by jonkerj** [comment]
> It seems that it's a distribution issue since, as you said, the distribution doesn't provide `SYS_MODULE`?

I don't believe so, as required modules are compiled in, so one does not need to load modules. Also, when running privileged, everything works, so the kernel functionality seems there.

**Comment by jonkerj** [comment]
> @jonkerj @DWSR what is the error that you get when installing Cilium without being privileged and with the `SYS_MODULE` capability?

On a moduleless-kernel, there is no `SYS_MODULE` capability (see #21506 for more info on that), so I can't tell. Other than that, there is no error message at all, it is simply not possible to reach services, it quietly fails.

**Comment by aanm** [comment]
@jonkerj can you get the output of `capsh --print` when running with privileged and unprivileged w/ sys_module and without sys_module deployed via helm chart?

**Comment by jonkerj** [comment]
> @jonkerj can you get the output of `capsh --print` when running with privileged and unprivileged w/ sys_module and without sys_module deployed via helm chart?

I cannot test it with `SYS_MODULE`, as this capability does not exist. Trying to include it yields an error from the container runtime:

```
error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply caps: operation not permitted: unknown
```

So the container is not getting created and therefore there is no `capsh`-ing possible. If it would start, it would probably show the same as below, but with `sys_module` included.

### Privileged (without `SYS_MODULE`):
```
WARNING: libcap needs an update (cap=40 should have a name).
Current: =ep cap_sys_module,cap_sys_boot-ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,38,39,40
Ambient set =
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root) euid=0(root)
gid=0(root)
groups=
Guessed mode: UNCERTAIN (0)
```

### Unprivileged (without `SYS_MODULE`):
```
WARNING: libcap needs an update (cap=40 should have a name).
Current: = cap_chown,cap_dac_override,cap_fowner,cap_kill,cap_setgid,cap_setuid,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin,cap_sys_resource,38,39+ep
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_kill,cap_setgid,cap_setuid,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_admin,cap_sys_resource,38,39
Ambient set =
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root) euid=0(root)
gid=0(root)
groups=
Guessed mode: UNCERTAIN (0)
```

By the way: 38,39 and 40 are `permon`, `bpf` and `checkpoint_restore` according to [kernel source](https://github.com/torvalds/linux/blob/v5.15/include/uapi/linux/capability.h#L380-L418).

**Comment by aanm** [comment]
@frezbo it looks that Cilium is unable to function properly with Talos even if users deploy Cilium without SYS_MODULE. Is Talos loading these modules by default? https://docs.cilium.io/en/stable/operations/system_requirements/#requirements-for-l7-and-fqdn-policies

**Comment by jonkerj** [comment]
> @frezbo it looks that Cilium is unable to function properly with Talos even if users deploy Cilium without SYS_MODULE. Is Talos loading these modules by default? https://docs.cilium.io/en/stable/operations/system_requirements/#requirements-for-l7-and-fqdn-policies

All of those are `=Y` (see [source](https://github.com/siderolabs/pkgs/blob/v1.2.0/kernel/build/config-amd64#L1169-L1256)). Also, I wonder: if they were not there, how could it work privileged? Running privileged or not should not influence kernel config.

**Comment by DWSR** [comment]
@jonkerj Given [this comment](https://github.com/cilium/cilium/pull/21506#issuecomment-1265319556) you made on another issue, would making a note in Cilium's KPR documentation be sufficient to close this issue out?

**Comment by frezbo** [comment]
apologies, I was on PTO, still catching up, will take a look into this next week

**Comment by jonkerj** [comment]
> @jonkerj Given [this comment](https://github.com/cilium/cilium/pull/21506#issuecomment-1265319556) you made on another issue, would making a note in Cilium's KPR documentation be sufficient to close this issue out?

I would rather understand (or better: fix) the underlying problem, rather than documenting that it does not work.

**Comment by frezbo** [comment]
apologies, I was on PTO, still catching up, will take a look into this next week

**Comment by DWSR** [comment]
> I would rather understand (or better: fix) the underlying problem, rather than documenting that it does not work.

The linked comment appears to indicate that you have Cilium with KPR working correctly on Talos by passing a custom list of capabilities to the Helm chart. Is that not the case?

**Comment by jonkerj** [comment]
> > I would rather understand (or better: fix) the underlying problem, rather than documenting that it does not work.
> 
> 
> 
> The linked comment appears to indicate that you have Cilium with KPR working correctly on Talos by passing a custom list of capabilities to the Helm chart. Is that not the case?

Aaah now I understand. No, it was not the case unfortunately. In that issue I got Cilium running unprivileged, but did not know yet it was actually (silently) misbehaving KPR wise.

**Comment by DWSR** [comment]
Ah, OK.

**Comment by frezbo** [comment]
> @frezbo it looks that Cilium is unable to function properly with Talos even if users deploy Cilium without SYS_MODULE. Is Talos loading these modules by default? https://docs.cilium.io/en/stable/operations/system_requirements/#requirements-for-l7-and-fqdn-policies

Quick update: So I've built a custom Talos image to debug which allows `SYS_MODULE` capability and this is the output of `capsh --print` from the cilium agent pod (manually installed `libcap2-bin`) from privileged and non-privilged pod:

#### privileged

```bash
root@talos-default-worker-1:/home/cilium# capsh --print
WARNING: libcap needs an update (cap=40 should have a name).
Current: =ep cap_sys_boot-ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,38,39,40
Ambient set =
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root) euid=0(root)
gid=0(root)
groups=
Guessed mode: UNCERTAIN (0)
```

#### non-privileged

```bash
root@talos-default-worker-1:/home/cilium# capsh --print
WARNING: libcap needs an update (cap=40 should have a name).
Current: = cap_chown,cap_dac_override,cap_fowner,cap_kill,cap_setgid,cap_setuid,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_module,cap_sys_admin,cap_sys_resource+ep
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_kill,cap_setgid,cap_setuid,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_sys_module,cap_sys_admin,cap_sys_resource
Ambient set =
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root) euid=0(root)
gid=0(root)
groups=
Guessed mode: UNCERTAIN (0)
```

Also the output of checking the compiled in Kernel modules required as mentioned in Cilium Docs:

```bash
❯ talosctl -n 10.5.0.2 read /proc/config.gz | zgrep \
      -e "CONFIG_BPF" \
      -e "CONFIG_BPF_SYSCALL" \
      -e "CONFIG_NET_CLS_BPF" \
      -e "CONFIG_BPF_JIT" \
      -e "CONFIG_NET_CLS_ACT" \
      -e "CONFIG_NET_SCH_INGRESS" \
      -e "CONFIG_CRYPTO_SHA1" \
      -e "CONFIG_CRYPTO_USER_API_HASH" \
      -e "CONFIG_CGROUPS" \
      -e "CONFIG_CGROUP_BPF" \
      -e "CONFIG_NETFILTER_XT_SET" \
      -e "CONFIG_IP_SET" \
      -e "CONFIG_IP_SET_HASH_IP" \
      -e "CONFIG_NETFILTER_XT_TARGET_TPROXY" \
      -e "CONFIG_NETFILTER_XT_TARGET_CT" \
      -e "CONFIG_NETFILTER_XT_MATCH_MARK" \
      -e "CONFIG_NETFILTER_XT_MATCH_SOCKET"
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_JIT_DEFAULT_ON=y
# CONFIG_BPF_UNPRIV_DEFAULT_OFF is not set
# CONFIG_BPF_PRELOAD is not set
# CONFIG_BPF_LSM is not set
CONFIG_CGROUPS=y
CONFIG_CGROUP_BPF=y
CONFIG_NETFILTER_XT_SET=y
CONFIG_NETFILTER_XT_TARGET_CT=y
CONFIG_NETFILTER_XT_TARGET_TPROXY=y
CONFIG_NETFILTER_XT_MATCH_MARK=y
CONFIG_NETFILTER_XT_MATCH_SOCKET=y
CONFIG_IP_SET=y
CONFIG_IP_SET_MAX=256
CONFIG_IP_SET_BITMAP_IP=y
CONFIG_IP_SET_BITMAP_IPMAC=y
CONFIG_IP_SET_BITMAP_PORT=y
CONFIG_IP_SET_HASH_IP=y
CONFIG_IP_SET_HASH_IPMARK=y
CONFIG_IP_SET_HASH_IPPORT=y
CONFIG_IP_SET_HASH_IPPORTIP=y
CONFIG_IP_SET_HASH_IPPORTNET=y
CONFIG_IP_SET_HASH_IPMAC=y
CONFIG_IP_SET_HASH_MAC=y
CONFIG_IP_SET_HASH_NETPORTNET=y
CONFIG_IP_SET_HASH_NET=y
CONFIG_IP_SET_HASH_NETNET=y
CONFIG_IP_SET_HASH_NETPORT=y
CONFIG_IP_SET_HASH_NETIFACE=y
CONFIG_IP_SET_LIST_SET=y
# CONFIG_BPFILTER is not set
CONFIG_NET_SCH_INGRESS=y
CONFIG_NET_CLS_BPF=y
CONFIG_NET_CLS_ACT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_CRYPTO_SHA1=y
# CONFIG_CRYPTO_SHA1_SSSE3 is not set
CONFIG_CRYPTO_USER_API_HASH=y
CONFIG_BPF_EVENTS=y
# CONFIG_BPF_KPROBE_OVERRIDE is not set
```


So the issue seems to be not related to the `SYS_MODULE` capability. In both cases `cilium service list` shows the default kubernetes ClusterIP service to be active:

```bash
root@talos-default-worker-1:/home/cilium# cilium service list
ID   Frontend           Service Type   Backend                          
1    10.96.0.1:443      ClusterIP      1 => 10.5.0.2:6443 (active) 
```

Anything else I can look into to debug?

**Comment by frezbo** [comment]
Attaching the cilium agent logs in both privileged and unprivileged modes and also the output of `cilium debuginfo`

[cilium-agent-privileged.log](https://github.com/cilium/cilium/files/10238007/cilium-agent-privileged.log)
[cilium-agent-privileged-debuginfo.log](https://github.com/cilium/cilium/files/10238009/cilium-agent-privileged-debuginfo.log)
[cilium-agent-unprivileged.log](https://github.com/cilium/cilium/files/10238010/cilium-agent-unprivileged.log)
[cilium-agent-unprivileged-debuginfo.log](https://github.com/cilium/cilium/files/10238011/cilium-agent-unprivileged-debuginfo.log)

**Comment by frezbo** [comment]
@aanm does the logs provided above provide any hint? Is there any other information needed?

**Comment by dimatha** [comment]
Hello Everyone! 
I'm new to Cilium and wanted to give it a shot by running on RPi4 & Talos OS.
Just to mention that I'm experiencing the same problem running Talos 1.3.2 and Cilium 1.12.5 (kubeProxyReplacement=strict ). E.g.: pod2pod comms are working but service IPs are not reachable. I was following the official guidance from Talos documentation - https://www.talos.dev/v1.3/kubernetes-guides/network/deploying-cilium 

I wonder if it was ever working in this mode?

I've also noticed some errors from the Cilium apply-sysctl-overwrites init container:
> can't stat sysctl.d dir '/etc/sysctl.d/': stat /etc/sysctl.d/: no such file or directory

Which might be correct with Talos but not sure if this can cause some troubles?

**Comment by DWSR** [comment]
@dimatha `kubeProxyReplacement: strict` works correctly on Talos, but only when `securityContext.privileged` is `true`.

**Comment by dimatha** [comment]
@DWSR Thanks! Confirmed.

**Comment by rio** [comment]
Strict mode fails for me on that setup (rpi4, talos 1.3.2) but with cilium 1.13.0-rc4 and ipv6 enabled. The agent fails with
```
could not load module ip_tables: exit status 1
```
Disabling ipv6 makes it work again.

**Comment by TheAifam5** [comment]
> Strict mode fails for me on that setup (rpi4, talos 1.3.2) but with cilium 1.13.0-rc4 and ipv6 enabled. The agent fails with
> 
> ```
> 
> could not load module ip_tables: exit status 1
> 
> ```
> 
> Disabling ipv6 makes it work again.
> 
> 
> 
> Edit: agent is running in privileged mode.

This will be fixed by https://github.com/cilium/cilium/pull/23953

**Comment by jonkerj** [comment]
Excellent. But that still does not solve the issue that Cilium is not working in unprivileged mode under Talos, without giving any error or whatsoever.

**Comment by frezbo** [comment]
@jonkerj this seems to have fixed it, could you try with these:

```yaml
ipam:
  mode: kubernetes
hostServices:
  hostNamespaceOnly: true
socketLB:
  hostNamespaceOnly: true
```

and doing a `cilium install --helm-values values.yaml`

**Comment by jonkerj** [comment]
> @jonkerj this seems to have fixed it, could you try with these:

Sure, I will. It will take be a while, as my test cluster needs to be revived

**Comment by frezbo** [comment]
okay, I've drilled this down to specifying the existing cgroup mount that talos uses, helm/cli values file used:

```yaml
ipam:
  mode: kubernetes
kubeProxyReplacement: strict
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: 10.5.0.1
k8sServicePort: 6443
```

The `k8sServiceHost` and `k8sServicePort` needs to be updated

**Comment by DWSR** [comment]
> okay, I've drilled this down to specifying the existing cgroup mount that talos uses, helm/cli values file used:
> 
> ```yaml
> ipam:
>   mode: kubernetes
> kubeProxyReplacement: strict
> securityContext:
>   capabilities:
>     ciliumAgent:
>       - CHOWN
>       - KILL
>       - NET_ADMIN
>       - NET_RAW
>       - IPC_LOCK
>       - SYS_ADMIN
>       - SYS_RESOURCE
>       - DAC_OVERRIDE
>       - FOWNER
>       - SETGID
>       - SETUID
>     cleanCiliumState:
>       - NET_ADMIN
>       - SYS_ADMIN
>       - SYS_RESOURCE
> cgroup:
>   autoMount:
>     enabled: false
>   hostRoot: /sys/fs/cgroup
> k8sServiceHost: 10.5.0.1
> k8sServicePort: 6443
> ```

My initial impression is that this works correctly on Talos. Thanks @frezbo

**Comment by frezbo** [comment]
> Scratch that, traffic using in-cluster service IPs are broken when using this, but external services are fine.

that's weird, all `cilium connectivity test` passes, and coredns comes up fine, this was tested on talos main (1.4.0.alpha)

**Comment by jonkerj** [comment]
Using @frezbo's values, I can confirm my symptom has been resolved:

```
some@testpod:$ wget -qO/dev/null https://10.96.0.1:443/
wget: note: TLS certificate validation not implemented
wget: server returned error: HTTP/1.1 401 Unauthorized
```

This shows a test pod at non-CP node is able to reach the API server at it's `ClusterIP` service. Also, CoreDNS is working again:

```
some@testpod:$ nslookup kubernetes.default.svc.cluster.local
[..]
Name:   kubernetes.default.svc.cluster.local
Address: 10.96.0.1
```

So, inter-node traffic works, `ClusterIP` also works. LGTM, basically.
