### ISSUE TITLE
Communication across nodes timeouts unless BGP announces podCIDRs

### ISSUE THREAD

**Issue by miminar** [cilium/cilium#21619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we disable podCIDR announcements with MetalLB, pods cannot talk to services anymore and start to crash.

Helm values (with some obfuscation):

    ---
    k8sServiceHost: 10.205.160.17
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    ipv4NativeRoutingCIDR: 10.205.240.0/20
    tunnel: disabled
    autoDirectNodeRoutes: false
    ipv6:
      enabled: false
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - icmp
          - http
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-staging
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.middlewares: >-
              traefik-ethz-ldap-auth@kubernetescrd
          className: traefik
          enabled: true
          hosts:
            - hubble.foo.bar.example.com
          tls:
            - secretName: hubble-foo-bar-example.com-tls
              hosts:
                - hubble.foo.bar.example.com
    cluster:
      id: 29
      name: foo
    upgradeCompatibility: "1.12"
    extraEnv:
    - name: http_proxy
      value: http://proxy.example.com:3128
    - name: https_proxy
      value: http://proxy.example.com:3128
    - name: no_proxy
      value: localhost,127.0.0.1,10.206.0.0/16,10.205.0.0/16,.svc,.cluster.local,.local,.cilium,123.123.123.123,123.123.123.123/27,.foo.bar.example.com
    ipam:
      mode: kubernetes
    bgpControlPlane:
      enabled: false
    bgp:
      enabled: true
      announce:
        loadbalancerIP: true
        podCIDR: false
    ingressController:
      enabled: false
    monitor:
      enabled: true
    debug:
      enabled: false
    externalIPs:
      enabled: true
    nodePort:
      enabled: true
    hostPort:
      enabled: true
    prometheus:
      enabled: true
    operator:
      prometheus:
        enabled: true

Cilium's config:

    ---
    apiVersion: v1
    data:
      agent-not-ready-taint-key: node.cilium.io/agent-not-ready
      arping-refresh-period: 30s
      auto-direct-node-routes: "false"
      bgp-announce-lb-ip: "true"
      bpf-lb-external-clusterip: "false"
      bpf-lb-map-max: "65536"
      bpf-lb-sock: "false"
      bpf-map-dynamic-size-ratio: "0.0025"
      bpf-policy-map-max: "16384"
      bpf-root: /sys/fs/bpf
      cgroup-root: /run/cilium/cgroupv2
      cilium-endpoint-gc-interval: 5m0s
      cluster-id: "29"
      cluster-name: foo
      custom-cni-conf: "false"
      debug: "false"
      disable-cnp-status-updates: "true"
      disable-endpoint-crd: "false"
      enable-auto-protect-node-port-range: "true"
      enable-bgp-control-plane: "false"
      enable-bpf-clock-probe: "true"
      enable-endpoint-health-checking: "true"
      enable-external-ips: "true"
      enable-health-check-nodeport: "true"
      enable-health-checking: "true"
      enable-hubble: "true"
      enable-ipv4: "true"
      enable-ipv4-masquerade: "true"
      enable-ipv6: "false"
      enable-ipv6-masquerade: "true"
      enable-k8s-terminating-endpoint: "true"
      enable-l2-neigh-discovery: "true"
      enable-l7-proxy: "true"
      enable-local-redirect-policy: "false"
      enable-metrics: "true"
      enable-node-port: "true"
      enable-policy: default
      enable-remote-node-identity: "true"
      enable-svc-source-range-check: "true"
      enable-vtep: "false"
      enable-well-known-identities: "false"
      enable-xt-socket-fallback: "true"
      hubble-disable-tls: "false"
      hubble-listen-address: :4244
      hubble-metrics: dns drop tcp flow icmp http
      hubble-metrics-server: :9965
      hubble-socket-path: /var/run/cilium/hubble.sock
      hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
      hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
      hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
      identity-allocation-mode: crd
      install-iptables-rules: "true"
      install-no-conntrack-iptables-rules: "false"
      ipam: kubernetes
      ipv4-native-routing-cidr: 10.205.240.0/20
      ipv4-service-range: 10.205.209.0/24
      kube-proxy-replacement: strict
      kube-proxy-replacement-healthz-bind-address: ""
      monitor-aggregation: medium
      monitor-aggregation-flags: all
      monitor-aggregation-interval: 5s
      node-port-bind-protection: "true"
      nodes-gc-interval: 5m0s
      operator-api-serve-addr: 127.0.0.1:9234
      operator-prometheus-serve-addr: :9963
      preallocate-bpf-maps: "false"
      procfs: /host/proc
      prometheus-serve-addr: :9962
      proxy-prometheus-port: "9964"
      remove-cilium-node-taints: "true"
      set-cilium-is-up-condition: "true"
      sidecar-istio-proxy-image: cilium/istio_proxy
      synchronize-k8s-nodes: "true"
      tofqdns-dns-reject-response-code: refused
      tofqdns-enable-dns-compression: "true"
      tofqdns-endpoint-max-ip-per-hostname: "50"
      tofqdns-idle-connection-grace-period: 0s
      tofqdns-max-deferred-connection-deletes: "10000"
      tofqdns-min-ttl: "3600"
      tofqdns-proxy-response-max-delay: 100ms
      tunnel: disabled
      unmanaged-pod-watcher-interval: "15"
      vtep-cidr: ""
      vtep-endpoint: ""
      vtep-mac: ""
      vtep-mask: ""
    kind: ConfigMap
    metadata:
      annotations:
        meta.helm.sh/release-name: cilium
        meta.helm.sh/release-namespace: cilium
      creationTimestamp: "2022-08-31T10:36:03Z"
      labels:
        app.kubernetes.io/managed-by: Helm
      name: cilium-config
      namespace: cilium

BGP config with some obfuscation:

    ---
    apiVersion: v1
    data:
      config.yaml: |
        peers:
          - peer-address: 10.206.128.9
            peer-asn: 1234566
            my-asn: 1235629
          - peer-address: 10.206.128.10
            peer-asn: 1234566
            my-asn: 1235629
        address-pools:
          - name: default
            protocol: bgp
            addresses:
              - 10.205.210.0/24
              - 123.123.123.123/32
    kind: ConfigMap
    metadata:
      annotations: {}
      creationTimestamp: "2022-09-16T14:08:43Z"
      name: bgp-config
      namespace: cilium

After setting `bgp.announce.podCIDR` to `false`, things start to break up. This is for example prometheus log:

	v1.Pod: failed to list *v1.Pod: Get \"https://10.205.209.1:443/api/v1/namespaces/default/pods?resourceVersion=14886042\": dial tcp 10.205.209.1:443: i/o timeout"
	ts=2022-10-07T12:11:51.518Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get \"https://10.205.209.1:443/api/v1/namespaces/default/endpoints?resourceVersion=14885330\": dial tcp 10.205.209.1:443: i/o timeout"
	ts=2022-10-07T12:11:51.597Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: Get \"https://10.205.209.1:443/api/v1/namespaces/trident/services?resourceVersion=14886359\": dial tcp 10.205.209.1:443: i/o timeout"
	...
	ts=2022-10-07T12:18:13.806Z caller=notifier.go:526 level=error component=notifier alertmanager=http://10.205.243.230:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://10.205.243.230:9093/api/v2/alerts\": context deadline exceeded"

Pod to pod communication is working for pods on the same node but not across nodes.  
Pod to host communication is again working only for the pods on the same host.

We don't have such issues with `bgp.announce.podCIDR=true`. But we would prefer not to announce podCIDRs. I'll be happy to provide more information.

### Cilium Version

cilium-cli: 0.12.3 compiled with go1.18.5 on linux/amd64
cilium image (default): v1.12.1
cilium image (stable): v1.12.2
cilium image (running): v1.12.2

### Kernel Version

Linux eu-k8s-dev-06 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.22.13

### Sysdump

Cannot disclose publicly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xiaods** [comment]
this is design?

**Comment by miminar** [comment]
> this is design?

If that were the case, why making `podCIDR=false` an option at all?

For us, `podCIDR=true` is a potential security risk as the unexposed pods can be routable from outside of k8s cluster.

On the same cluster we successfully ran kube-router configured with `--advertise-pod-cidr=false` alongside cilium. It worked as expected. And that's what we'd like to use with pure cilium as well.

**Comment by xiaods** [comment]
> > this is design?
> 
> If that were the case, why making `podCIDR=false` an option at all?
> 
> For us, `podCIDR=true` is a potential security risk as the unexposed pods can be routable from outside of k8s cluster.
> 
> On the same cluster we successfully ran kube-router configured with `--advertise-pod-cidr=false` alongside cilium. It worked as expected. And that's what we'd like to use with pure cilium as well.

this is proposal feature. I also like it.
