### ISSUE TITLE
Ginkgo K8s tests don't refresh cilium pods after first run 

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2161]
After running a k8s test once in the ginkgo framework, subsequent test runs do not update the cilium pods running in the VMs. The underlying reason is that each test performs a `kubectl.Apply(...)` for the `cilium_ds.yaml`, which does nothing if there is already a cilium daemonset running.

Perhaps deployment of the `cilium_ds.yaml` in k8s case could be shifted into `before_suite()`, and use `kubectl replace --force -f ...` instead?

**Comment by joestringer** [comment]
+@eloycoto I guess this is one side effect from the change we made to allow the VMs to continue running in local environments.

**Comment by eloycoto** [comment]
@joestringer Yes, it is.
