### ISSUE TITLE
Pods stuck in ContainerCreating / endpoints waiting-for-identity

### ISSUE THREAD

**Issue by rpn0709** [cilium/cilium#21628]
Kubernetes version: 1.24.3
Containerd: 1.6.6
Cilium version v1.12.1
100 Node cluster / 3k pods / 100 cronjobs

Problem: Pods get stuck in ContainerCreating on all nodes. Node reboots and service restarts do not fix the issue. Existing pods that are running are unaffected.

 "cilium endpoint" list shows pod stuck in "waiting-for-identity"

No new deployments work. You can delete running deployments or pods and they will recreate fine and start Running but net new objects will not. 

Reproduce: Create cronjobs to spin up/down pods and after some time the cluster locks. 

Looking in etcd cilium identities hit a max 65k keys and won't allow anymore writes. Cilium API starts timing out due to being unable to write to etcd, updates still work however.

It appears that identities created from kubernetes jobs do not get cleaned up properly, even though they are deleted out of kubernetes.

The only way you can recover is by manually deleting the orphaned identities from etcd.

Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
level=debug msg="Greeting successful" host="http://redacted:4240" ipAddr=redacted nodeName=redacted path="Via L3" rtt=1.739402ms subsys=health-server
level=debug msg="Starting new controller" name=endpoint-3940-regeneration-recovery subsys=controller uuid=9171b188-b365-49e3-9153-59db3b69da7c
level=debug msg="creating new EventQueue" name=endpoint-3940 numBufferedEvents=25 subsys=eventqueue
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Starting new controller" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="58.22µs" eventEnqueueWaitTime=382ns eventHandlingDuration="35.827µs" eventType="*endpoint.EndpointPolicyVisibilityEvent" name=endpoint-3940 subsys=eventqueue
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime=498ns eventEnqueueWaitTime=286ns eventHandlingDuration="28.248µs" eventType="*endpoint.EndpointPolicyBandwidthEvent" name=endpoint-3940 subsys=eventqueue
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime=472ns eventEnqueueWaitTime=239ns eventHandlingDuration="7.868µs" eventType="*endpoint.EndpointNoTrackEvent" name=endpoint-3940 subsys=eventqueue
level=debug msg="Refreshing labels of endpoint" containerID=6e64667788 endpointID=3940 identityLabels="k8s:app=grafana-ds,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=k8s:io.cilium.k8s.policy.cluster=k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=k8s:maintainer=" infoLabels="k8s:pod-template-hash=8666fd778" subsys=endpoint
level=debug msg="Assigning information label" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ obj="{Key:pod-template-hash Value:8666fd778 Source:k8s}" subsys=endpoint
level=debug msg="Assigning security relevant label" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ obj="{Key:io.cilium.k8s.policy.cluster Value:natl Source:k8s}" subsys=endpoint
level=debug msg="Assigning security relevant label" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ obj="{Key:app Value:grafana-ds Source:k8s}" subsys=endpoint
level=debug msg="Assigning security relevant label" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ obj="{Key:maintainer Value:EOS Source:k8s}" subsys=endpoint
level=debug msg="Assigning security relevant label" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ obj="{Key:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name Value:eos Source:k8s}" subsys=endpoint
level=debug msg="Assigning security relevant label" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ obj="{Key:io.kubernetes.pod.namespace Value:eos Source:k8s}" subsys=endpoint
level=debug msg="Assigning security relevant label" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ obj="{Key:io.cilium.k8s.policy.serviceaccount Value:default Source:k8s}" subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 identityLabels="k8s:app=grafana-ds,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=eos,k8s:io.cilium.k8s.policy.cluster=k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=eos,k8s:maintainer=" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Resolving identity for labels" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 identityLabels="k8s:app=grafana-ds,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=k8s:io.cilium.k8s.policy.cluster=k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=k8s:maintainer=EOS" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 36.059µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 112.326µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="GET /endpoint/{id}/log request" endpointID=3940 subsys=daemon
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 52.974µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 140.203µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 50.796µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 44.283µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 87.374µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 55.513µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Greeting successful" host="http://xxx.xxx.xxx.xxx:4240" ipAddr=xxx.xxx.xxx.xxx nodeName=redacted path="Via L3" rtt=1.539406ms subsys=health-server
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 52.469µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Skipping CiliumEndpoint update because security identity is not yet available" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 36.689µs" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="unable to resolve identity: exponential backoff cancelled via context: context canceled (will retry)" code=Warning containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 endpointState=waiting-for-identity ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
level=warning msg="Error changing endpoint identity" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 error="unable to resolve identity: exponential backoff cancelled via context: context canceled" identityLabels="k8s:app=grafana-ds,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=k8s:io.cilium.k8s.policy.cluster=k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=eos,k8s:maintainer=EOS" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Starting new controller" name=resolve-identity-3940 subsys=controller uuid=3ca0e76c-dbca-4f19-b050-322f393d5b91
level=debug msg="stopping EventQueue" name=endpoint-3940 subsys=eventqueue
level=debug msg="exiting retrying regeneration goroutine due to endpoint being deleted" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Controller func execution time: 1m30.058562794s" name=endpoint-3940-regeneration-recovery subsys=controller uuid=9171b188-b365-49e3-9153-59db3b69da7c
level=debug msg="Controller run succeeded; waiting for next controller update or stop" name=endpoint-3940-regeneration-recovery subsys=controller uuid=9171b188-b365-49e3-9153-59db3b69da7c
level=debug msg="Resolving identity for labels" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 identityLabels="k8s:app=grafana-ds,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=,k8s:io.cilium.k8s.policy.cluster=k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=k8s:maintainer=EOS" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="unable to resolve identity: identity sync was cancelled: context canceled (will retry)" code=Warning containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 endpointState=waiting-for-identity ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
level=debug msg="Controller func execution time: 109.63µs" name=resolve-identity-3940 subsys=controller uuid=3ca0e76c-dbca-4f19-b050-322f393d5b91
level=debug msg="Controller run failed" consecutiveErrors=1 error="unable to resolve identity: identity sync was cancelled: context canceled" name=resolve-identity-3940 subsys=controller uuid=3ca0e76c-dbca-4f19-b050-322f393d5b91
level=debug msg="Deleting endpoint" code=OK containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 endpointState=disconnecting ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
level=debug msg="removing directory" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 directory=3940 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="removing directory" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 directory=3940_next_fail endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="removing directory" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 directory=3940_next endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="removing directory" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 directory=3940_stale endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Removed controller" name=endpoint-3940-regeneration-recovery subsys=controller uuid=9171b188-b365-49e3-9153-59db3b69da7c
level=debug msg="Removed controller" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Removed controller" name=resolve-identity-3940 subsys=controller uuid=3ca0e76c-dbca-4f19-b050-322f393d5b91
level=debug msg="Shutting down controller" name="sync-to-k8s-ciliumendpoint (3940)" subsys=controller uuid=476904e5-4295-4775-a1ae-595ba1bfe6fa
level=debug msg="Shutting down controller" name=resolve-identity-3940 subsys=controller uuid=3ca0e76c-dbca-4f19-b050-322f393d5b91
level=debug msg="Shutting down controller" name=endpoint-3940-regeneration-recovery subsys=controller uuid=9171b188-b365-49e3-9153-59db3b69da7c
level=debug msg="Endpoint removed" code=OK containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 endpointState=disconnected ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
level=info msg="Removed endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Waiting for proxy updates to complete..." containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Wait time for proxy updates: 7.532µs" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=debug msg="Skipping CiliumEndpoint deletion because it has no UID" containerID= controller="sync-to-k8s-ciliumendpoint (3940)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=warning msg="Creation of endpoint failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 error="request cancelled while resolving identity" ipv4= ipv6= k8sPodName=/ subsys=daemon
level=debug msg="End of create request" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3940 ipv4= ipv6= k8sPodName=/ subsys=daemon
level=debug msg="Probe successful" ipAddr=xxx.xxx.xxx.xxx nodeName=redacted rtt=11.939405ms subsys=health-server
level=debug msg="Greeting successful" host="http://xxx.xxx.xxx.xxx:4240" ipAddr=xxx.xxx.xxx.xxx nodeName=redacted path="Via L3" rtt=1.394008ms subsys=health-server

level=warning msg="Unable to create endpoint" containerID=4fd2175605c4bd7b03251f167310ea54a47c54c1895515b44eaad874d5a05e51 error="Cilium API client timeout exceeded" eventUUID=643d9fd9-37f3-4c63-a4c1-0ab2ebd4e53c subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=158adc0a7934e9e194b5359bf3fef375f8a148e04521eb21a5daf917551664a6 error="Cilium API client timeout exceeded" eventUUID=5221a8f2-45bc-415e-9371-6184623a7e9b subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=5391ab29a866ab6122538918f2f5bd21833d7c3c0472001271ad5ef83432255d error="Cilium API client timeout exceeded" eventUUID=fdd8ef74-6bad-4f15-b045-ed0f660bc8e8 subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=22354b1b000b1bb983082a3ebf7f004879fcb01d4a288776bb71e1a0f857bd38 error="Cilium API client timeout exceeded" eventUUID=97735c8a-00cc-4e32-88cb-90640a28e67e subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=8d9432cde91d985a950362d64d874bab24eba976a75a324adfc3854097a753b9 error="Cilium API client timeout exceeded" eventUUID=eed546ad-fd3f-4bcc-a04a-1b24a82df206 subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=368cb544ef551e0680a8a060552586da0be56d2fec51fcf1eb1e7ef843d1eff5 error="Cilium API client timeout exceeded" eventUUID=8e9b0592-bdd5-4ab0-88ed-a6fdd155d3ae subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=d687c5bf731ed609b95f36cafa660da026f772e0d11ba15ba829baaf2d669f24 error="Cilium API client timeout exceeded" eventUUID=7162d65a-aa2d-49d1-b8a8-2a727010ddd8 subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=669368e7bc47f258bf51efaa981719130f73c8a57d79757ec59704c242f128f1 error="Cilium API client timeout exceeded" eventUUID=2aeaade0-24b0-4327-b151-348e7baf47d7 subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=39b1c4f0b865c740ae666649855c37d45102e637b7725d15b8595d3c185f7384 error="Cilium API client timeout exceeded" eventUUID=d5d68d1d-a527-46bf-993b-2894f580f5f3 subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=1c1a816f9c8da2ea184a1c1f07403e1ae1eaa61580d5c2c3c315122ad6e1d50d error="Cilium API client timeout exceeded" eventUUID=96059c90-ce69-45e0-b8e8-5d7968bf9901 subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=5ac447bb2ae87135746ed484cd8c93f468e8d8b8682db3139053e1f95a00ce23 error="Cilium API client timeout exceeded" eventUUID=33d166c8-8694-405a-bece-ad0b3abc1275 subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=75777b340d5f5817174ec68e458032178476829c8407bf96705e997f96e12704 error="Cilium API client timeout exceeded" eventUUID=fd77aa81-7ef9-44b1-b11c-9cf7725b4f1a subsys=cilium-cni
level=warning msg="Errors encountered while deleting endpoint" error="[DELETE /endpoint/{id}][404] deleteEndpointIdNotFound " subsys=cilium-cni
level=warning msg="Unable to create endpoint" containerID=5e32244b44df0c7805428bc487ae0e83083b629a944b25149b998e036bc0c57d error="Put \"http:///var/run/cilium/cilium.sock/v1/endpoint/cilium-local:0\": EOF" eventUUID=7eda6f63-f3d0-4dad-9999-01577c1a2297 subs
ys=cilium-cni
level=warning msg="Unable to release IP" error="Delete \"http:///var/run/cilium/cilium.sock/v1/ipam/xxx.xxx.xxx.xxx\": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory\nIs the agent running?" ipAddr=xxx.xxx.xxx.xxx subsys=cilium-cni

**Comment by xiaods** [comment]
@sayboras I know the reason. please reset cilium cni and with follow parameter:
```
cilium install --helm-set-string=ipam.operator.clusterPoolIPv4PodCIDR="10.42.0.0/16",kubeProxyReplacement=strict,k8sServiceHost=<api server ip>,k8sServicePort=6443
```
it works like a charm on my environment.

**Comment by christarazi** [comment]
@rpn0709 Are you still facing this issue? Have you tried with the latest version of Cilium?
