### ISSUE TITLE
CFP: enable IP forwarding for each NIC

### ISSUE THREAD

**Issue by Jiang1155** [cilium/cilium#21674]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

Yes. One issue while using cilium is that we sometimes got a fib lookup error as the following:

xx drop (FIB lookup failed) flow 0x5fcbfa3a to endpoint 0, , identity unknown->unknown:  xxx-> xxxx etc

After spent some time debugging, we found the issue is that there are two places in Linux to turn on ip forwarding. One is a global one in already set by cilium , which is /proc/sys/net/ip4/ip_forward

But there is another setting in /proc/sys/net/ipv4/conf/eth0/forwarding, which also need to be set by cilium. Otherwise, packets will be dropped.

**Describe the feature you'd like**

When cilium starts up, also set /proc/sys/net/ipv4/conf/eth0/forwarding to 1. Or for whatever interfaces configured in cilium

**Comment by pchaigno** [comment]
Sorry, seems this fell through the cracks.

Could you share reproduction steps? Given your current description of the issue, I'm a bit surprised that we don't always hit it 🤔
