### ISSUE TITLE
what‘s the difference of the two tags？

### ISSUE THREAD

**Issue by smwyzi** [cilium/cilium#21679]
Each Cilium release tag，saying 1.12.0，the repo has two tags（1.12.0，v1.12.0），what‘s the difference of the two tags？

**Comment by sayboras** [comment]
It's exactly the same, as they are pointing the same commit hash. For example, both 1.12.0 and v1.12.0 are pointing to 9447cd1bfab4424ccb59b5ea9ca41f89590261d4.

Might I know why you are asking this question.

**Comment by smwyzi** [comment]
> It's exactly the same, as they are pointing the same commit hash. For example, both 1.12.0 and v1.12.0 are pointing to [9447cd1](https://github.com/cilium/cilium/commit/9447cd1bfab4424ccb59b5ea9ca41f89590261d4).
> 
> Might I know why you are asking this question.

Just confused，why having two tags pointing the same commit hash

**Comment by aanm** [comment]
IIRC @smwyzi the reason we have two tags is because https://readthedocs.org, the platform where we host our docs, uses X.Y.Z (or vX.Y.Z) and the image build process on docker hub uses the other variant.

**Comment by smwyzi** [comment]
> IIRC @smwyzi the reason we have two tags is because https://readthedocs.org, the platform where we host our docs, uses X.Y.Z (or vX.Y.Z) and the image build process on docker hub uses the other variant.

got it，thanks~
