### ISSUE TITLE
Kubernetes 1.25.1 with Cilium - external DNS requests fail

### ISSUE THREAD

**Issue by Zveroloff** [cilium/cilium#21680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Kubernetes with Cilium CNI is installed inside corporate network without direct internet access. 

Cilium connectivity test partially fails.
Sonobuoy tests fail with external (outside of cluster) dns requests.
Kubernetes DNS subsystem works correctly, `nslookup kubernetes.default` is being resolved correctly. Requests to corporate DNS fail with i/o timeout.

### Cilium Version

1.13.0-rc1

### Kernel Version

4.18.0-372.26.1.el8_6.x86_64

### Kubernetes Version

1.25.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xiaods** [comment]
this is coredns config scope. cilium is not the root cause.

**Comment by Zveroloff** [comment]
> this is coredns config scope. cilium is not the root cause.

It could be true, but as I see, external requests a correctly addressed to corporate DNS. They fail with network-related issues 'no route to host' and 'i/o timeout'

**Comment by xiaods** [comment]
> no route to host

1.13.0-rc1 default is already remove kubeproxy and iptables dependencies. but you can also have a try for below iptables test.


```
systemctl stop kubelet
systemctl stop docker
iptables --flush
iptables -tnat --flush
systemctl start kubelet
systemctl start docker

The route problem can be solved by flush iptables.
```

**Comment by oivindoh** [comment]
@Zveroloff

Are you sure this is 1.25 and not cilium post 1.12.2? I’m seeing and trying to track down the source similar timeouts to external addresses (though to external addresses hosted in the same cluster via manually deployed metallb) on 1.12.3 currently, but not on 1.12.2. On k8s 1.24
