### ISSUE TITLE
doc: repeated attention segments in k8s-install-default

### ISSUE THREAD

**Issue by 117503445** [cilium/cilium#21702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Repeated attention segments in <https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#:~:text=Video-,To%20learn%20more%20about%20the%20Cilium%20CLI%2C%20check%20out%20eCHO%20episode%208%3A%20Exploring%20the%20Cilium%20CLI.,-Video>.

![Snipaste_2022-10-12_22-35-30](https://user-images.githubusercontent.com/21152034/195371948-a7ccaf87-61fb-4eee-8c92-6d1f666e76c7.png)

The rst file is <https://github.com/cilium/cilium/blob/master/Documentation/gettingstarted/k8s-install-default.rst>.

However, I didn't figure out why there was a duplicate paragraph, since there was no duplicate in the rst file.

### Cilium Version

/

### Kernel Version

/

### Kubernetes Version

/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qmonnet** [comment]
Fixed with https://github.com/cilium/cilium/pull/21587.

Thanks for the report!
