### ISSUE TITLE
bgp-control-plane ebgp-multihop config

### ISSUE THREAD

**Issue by wenqiang0527** [cilium/cilium#21716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

how to set bgp-control-plane  ebgp config?
bgp-control-plane use gobgp, how to set more config 

like gobgp this config:
  [neighbors.ebgp-multihop.config]
    enabled = true
    multihop-ttl = 255

### Cilium Version

1.12.0

### Kernel Version

4.19

### Kubernetes Version

1.25.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qmonnet** [comment]
Hi, I'm not sure I understand the question. Can you please elaborate on what you are trying to achieve?

**Comment by wenqiang0527** [comment]
Is bgp-control-plane supports  ebgp multihop？

**Comment by dylandreimerink** [comment]
Lets close this issue in favor of #21753
