### ISSUE TITLE
[Questions] Is there any documentation about datapath-mode ?

### ISSUE THREAD

**Issue by nejisama** [cilium/cilium#21720]
I have some doubts about datapath-mode, and i cannot find any documents or blogs for this parameter.
If I configure datapath-mode=lb-only, what abilities are available and what abilities are missing,  or what abilities are different?

**Comment by qmonnet** [comment]
Hi, the description for the commit that introduced the mode is probably the best description we have at the moment: https://github.com/cilium/cilium/commit/6a18ef2e4aa5b163beaafae8ec120d9035045439

Related: https://github.com/cilium/cilium/issues/17485

**Comment by nejisama** [comment]
thanks. wish there was more documentation describing

**Comment by xiaods** [comment]
the docs is WIP.

**Comment by aanm** [comment]
@xiaods are you working on the docs?

**Comment by xiaods** [comment]
> @xiaods are you working on the docs?

no
