### ISSUE TITLE
Reconcile Kubernetes resources state after agent restart

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#21725]
Currently, we don't consistently reconcile state realized via Kubernetes watcher events for various resources including Kubernetes native as well custom resources. The agent only receives the latest state from the k8s api server. This can lead to stale entries, and out-of-sync realized state. As an example, when an event like node delete occurs while the agent is down, the agent doesn't actively clean up old node entries. As a result, all the consumers of node events like ipcache datapath state can go out of sync. While we have periodically running controllers that try to sync realized state with the desired state, this may not account for entries that went out-of-sync while the agent was down, and weren't updated when the agent came back up.

To give some data points, we do have some restore and sync logic for some of the resources. For example, this is the logic for service entries [1]: when the agent starts, the logic restores all the entries from BPF maps, and marks them with a flag. During the k8s sync, we flip the flag for the service entries that are still active. Once the k8s sync is complete, we then remove the stale entries. 

Approaches to tackle this problem:
- Restore from datapath and remove stale entries (similar to service)
- Persist k8s resources to disk and take a diff with the latest state once agent is back up
- Recreate state (e.g., BPF maps) from the latest state 
- Take a snapshot of the informer caches while the agent is going down (graceful shutdown) and take a diff upon restart 

List of such resources and their respective consumers that populate datapath state:

Cilium Node 
Consumers: IPCache, Policy, BGP*
Cilium Endpoint
Consumers: IPCache, Policy
Endpoint
Consumers: Service, BGP*
Pod
Consumers: Service, IPCache, LRP
Cilium (clusterwide) network policy
Consumers: Policy
Service
Consumers: Service/LB, LRP
Cilium Endpoint Slice
Consumers: IPCache, Egress Gateway

Other resources that have persisted state in kvstore/etcd, and whether they have reconciliation logic:

- [ ] Cilium Identity

Reconciliation logic is in place:

- [ ] IPCache
- [x] Service
- [x] Policy
- [x] LRP
- [ ] BGP manager*

[1] https://github.com/cilium/cilium/blob/master/pkg/service/service.go#L875. 
*BGP: I'm not sure if/which BPF map(s) are updated

Edit: I've updated some of the components that already have reconciliation logic. As discussed, need inputs from individual owners for the rest of them.

**Comment by ldelossa** [comment]
BGP Manager does not use any eBPF maps and it also isn't directly wired into the watcher code. It receives a "signal" which can occur internal or external to the manager, and then reconciles based on the current state of k8s.
