### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by eddie-knight** [cilium/cilium#21760]
As Cilium is signed up for the Security Slam, this issue is to track the efforts necessary to bring this repo's [CLOMonitor](https://clomonitor.io/projects/cncf/cilium) score to 100%.

### Summary

**Repository**: cilium
**URL**: https://github.com/cilium/cilium
**Checks sets**:  `COMMUNITY` + `CODE`
**Score**: 86

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  100%  |
|  License  |  75%  |
|  Best Practices  |  95%  |
|  Security  |  65%  |
|  Legal  |  100%  |

### Documentation [100%]

  - [x] [Adopters](https://github.com/cilium/cilium/blob/master/USERS.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#adopters))
  - [x] Changelog ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Code of conduct](https://github.com/cilium/cilium/blob/master/CODE_OF_CONDUCT.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#code_of_conduct))
  - [x] [Contributing](https://github.com/cilium/cilium/blob/master/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] Governance ([_docs_](https://clomonitor.io/docs/topics/checks/#governance))
  - [x] [Maintainers](https://github.com/cilium/cilium/blob/master/MAINTAINERS.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/cilium/cilium/blob/master/README.rst) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  - [x] Roadmap ([_docs_](https://clomonitor.io/docs/topics/checks/#roadmap))
  - [x] [Website](https://cilium.io) ([_docs_](https://clomonitor.io/docs/topics/checks/#website))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [x] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [95%]

  - [x] Analytics ([_docs_](https://clomonitor.io/docs/topics/checks/#analytics))
  - [x] [Artifact Hub badge](https://artifacthub.io/packages/helm/cilium/cilium
) ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [x] Community meeting ([_docs_](https://clomonitor.io/docs/topics/checks/#community_meeting))
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [x] Github discussions ([_docs_](https://clomonitor.io/docs/topics/checks/#github_discussions)) `EXEMPT`
  - [x] [OpenSSF badge](https://bestpractices.coreinfrastructure.org/projects/1269) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/cilium/cilium/releases/tag/v1.13.0-rc1) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  - [x] Slack precense ([_docs_](https://clomonitor.io/docs/topics/checks/#slack_presence)) `EXEMPT`
  
### Security [65%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [x] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/cilium/cilium/blob/master/SECURITY.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [x] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [x] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
### Legal [100%]

  - [x] Trademark disclaimer ([_docs_](https://clomonitor.io/docs/topics/checks/#trademark_disclaimer))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by eddie-knight** [comment]
This issue relates to the LF mentorship effort [here](https://mentorship.lfx.linuxfoundation.org/project/680e32e5-d056-46fa-a94d-4af453d4e81d)

**Comment by xmulligan** [comment]
the last three are being worked on in #21435 #22220 and #20776

**Comment by xmulligan** [comment]
license scanning is in #22737

**Comment by xmulligan** [comment]
Analytics completed in #22220

**Comment by xmulligan** [comment]
SBOM completed in #22191 so we are finished now 🎊
