### ISSUE TITLE
lb-ipam: IP sharing between services

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#21776]
PR #21764 introduces the initial version of the LB-IPAM feature. This version contains the basics but is by no means feature complete.
This issue tracks the proposal to add a feature similar[ MetalLB's IP sharing feature](https://metallb.universe.tf/usage/#ip-address-sharing).

MetalLB allows users to add the `metallb.universe.tf/allow-shared-ip` annotation to services. MetalLB will attempt to assign the same IP to all services with the same "sharing key" which is the value of the annotation. MetalLB doesn't guarantee this and will only assign the same IP if a few conditions are met:
* They both have the same sharing key.
* They request the use of different ports (e.g. tcp/80 for one and tcp/443 for the other).
  *  As long as #9207 is unresolved we should not allow the merging of services with overlapping ports regardless of protocol
* They both use the Cluster external traffic policy, or they both point to the exact same set of pods (i.e. the pod selectors are identical).

The stated use case is as follows:
> There are two main reasons to colocate services in this fashion: to work around a Kubernetes limitation, and to work with limited IP addresses.

The mentioned Kubernetes limitation is the [inability to have mixed protocol services](https://github.com/kubernetes/kubernetes/issues/23880). But this seems to have been addressed in recent versions.

**Comment by yellowhat** [comment]
Hi, are there any update on this?

Thanks

**Comment by frittenlab** [comment]
This feature would be awesome. I need the shared IP functionality to be able to have UDP and TCP services with the same IP address. This would allow me to get rid of Metallb in favor of Cilium. At the moment I need Metallb and Cilium.

**Comment by mrsrvman** [comment]
+1

**Comment by kenlasko** [comment]
We are very close to MetalLB parity with the inclusion of #26488 in 1.15. Adding IP sharing would allow me and many others to finally ditch MetalLB in favour of Cilium. Any thoughts as to how we can raise the visibility of this issue to the community so it can be worked on?

**Comment by dylandreimerink** [comment]
Added the `help-wanted` label, that should help for people filtering on that one. I will see if I can get the merging of #26488 on the community meeting agenda to draw a bit of attention to the subject. And lastly, we can make a post in the development channel on slack. With a bit of luck we can find someone who has time to work on this, and otherwise it will have to wait until I have the cycles.

**Comment by kenlasko** [comment]
Awesome! Thanks @dylandreimerink. I'd offer to look at it, but I'm an amateur 'developer' at best.

**Comment by kenlasko** [comment]
I was looking through the history on this topic, and I noticed taht @dylandreimerink mentioned that it looked like multi-protocol support through [MixedProtocolLBService ](https://github.com/kubernetes/kubernetes/issues/23880)has been listed as Stable since 1.26. I just tested this in my lab and it works without the need for `metallb.universe.tf/allow-shared-ip`  This means that Cilium doesn't need to have that workaround (nor does MetalLB for that matter). 

Now I just have to wait for 1.15 to be stable and my main production cluster can be moved to Cilium!

**Comment by dylandreimerink** [comment]
@kenlasko not sure we are talking about the same thing here. As far as I understand it this mixed protocol LB service refers to the fact that 1 service and now have a UDP and TCP ports at the same time whereas before all ports had to be the same protocol.

But what this feature is about is to allow 2 or more service to share the same IP address with the goal of minimizing IP usage.

**Comment by kenlasko** [comment]
Of course, you're right. I was only thinking about my own particular scenario where I am able to replace two separate TCP/UDP services with a single service that takes care of both. This won't help people who need to share a single IP across multiple distinct services.

**Comment by jbalonso** [comment]
I'd like to flag that the use case for IP sharing between services is architecturally related (or should be) to Gateway API `TCPRoute` and `UDPRoute `support (see #21929). I grant that there is a lot more configuration overhead implementing "IP sharing between services" using Gateway API compared to Metallb's `metallb.universe.tf/allow-shared-ip` annotation, but Gateway API offers a portable way to express the same intentions.

Moreover: noting the relatively low priority given to this feature request both organizationally and personally (my interpretation of @dylandreimerink's remark in https://github.com/cilium/cilium/issues/21776#issuecomment-1466113736), I suspect directing our energies toward #21929 would be more efficient.

Having typed all this, I just *now* noticed #28806 (which seems to be reaching conclusion), so my opinion is clearly late.

**Comment by dylandreimerink** [comment]
> I'd like to flag that the use case for IP sharing between services is architecturally related (or should be) to Gateway API TCPRoute and UDPRoute support (see https://github.com/cilium/cilium/issues/21929).
>
> I grant that there is a lot more configuration overhead implementing "IP sharing between services" using Gateway API compared to Metallb's metallb.universe.tf/allow-shared-ip annotation, but Gateway API offers a portable way to express the same intentions.

These two features indeed work great together. Currently our Gateway API implementation translates to old school services and LB-IPAM only works with old school services. There are a few reasons for this, the main reasons that come to mind are the lack of Gateway API -> datapath configuration and the lack of support on most cloud platforms. So its likely that IP sharing in Gateway API will be in terms of this feature, at least at first until it becomes a first class citizen. This also seems to be the approach for related IP allocation features https://github.com/cilium/cilium/issues/21926

When we do add IP allocation for Gateways directly to LB-IPAM instead of going via an intermediate service object we would indeed need to look at the routes associated with the gateways to determine if they can share an IP or not. I have not found any specific configuration options in the spec for IP sharing, if there is that would be great to know. The only semantic I could come up with which would be implementation specific would be to declare a custom address type for shared IPs in place of having a sharing key in an annotation https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.AddressType (though perhaps this is going a bit off-topic)

> Moreover: noting the relatively low priority given to this feature request both organizationally and personally (my interpretation of @dylandreimerink's remark in https://github.com/cilium/cilium/issues/21776#issuecomment-1466113736)

I personally did not have time this release cycle, I put quite some time into https://github.com/cilium/cilium/pull/26488 and I have some other PRs that need some love so they can make it into v1.15. But I feel like there are quite a few people that are eager for this one, lucky we have found other community members who do have cycles to work on this :pray: .

> I suspect directing our energies toward https://github.com/cilium/cilium/issues/21929 would be more efficient.

I don't believe that issue includes IPAM of any sort, that is left up to the GatewayClass / Infrasturcture provider or in the case of a on prem deployment LB-IPAM. Plus, we will want to support regular services for quite some time to come.
