### ISSUE TITLE
CFP:  Enable dsr_reply_icmp4 and dsr_reply_icmp6 functionality unconditionally

### ISSUE THREAD

**Issue by nnbu** [cilium/cilium#21795]
## Cilium Feature Proposal

**Is your feature request related to a problem?**
yes

If so, please describe the problem
Currently `dsr_reply_icmp4` and `dsr_reply_icmp6` functions are protected by `ENABLE_DSR_ICMP_ERRORS`. `ENABLE_DSR_ICMP_ERRORS` is enabled only when `LoadBalancerPMTUDiscovery` is true. And `LoadBalancerPMTUDiscovery` is true only when cilium is enabled in `LBOnly` mode (`DatapathModeLBOnly`) and `NodePortAcceleration`  is true.

**Describe the feature you'd like**

I propose to enable `dsr_reply_icmp4` and `dsr_reply_icmp6` whenever DSR is enabled. `dsr_reply_icmp4/6` notify the client if the packet size is more than MTU using ICMP error replies. So, in my opinion, it is better to notify the clients always, rather than silently dropping the packets as it is done today when `ENABLE_DSR_ICMP_ERRORS` is NOT enabled.

Alternatively, If there is a specific requirement where some client may not want to receive such replies, then we need to provide a new cilium option to enable `ENABLE_DSR_ICMP_ERRORS`.

**Comment by nnbu** [comment]
@sahid @YutaroHayakawa Please provide suggestions

**Comment by YutaroHayakawa** [comment]
I don't have any objection to enabling this by default. @borkmann, what was your intention in disabling this by default for CNI mode?

**Comment by sahid** [comment]
Yes this makes sens, I would have considered the case as bug fix since we don't provide any way to set `LoadBalancerPMTUDiscovery = true` when `NodePortAcceleration = disabled`.

I guess the intention here was to auto-enable it only for `native` but let users ability to enable it if needed for `disabled`.

**Comment by nnbu** [comment]
we could delete `LoadBalancerPMTUDiscovery` altogether. And define `ENABLE_DSR_ICMP_ERRORS` when DSR is enabled.

**Comment by sahid** [comment]
I would have kept it enabled by default and removed it from [0]

https://github.com/cilium/cilium/blob/master/daemon/cmd/daemon_main.go#L1288
