### ISSUE TITLE
Unclear behavior of a cilium policy with blocked internet egress

### ISSUE THREAD

**Issue by MTRNord** [cilium/cilium#21816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a cilium policy created using https://editor.cilium.io/ which generated this policy:

[matrix.yaml](https://github.com/cilium/cilium/files/9824927/matrix_buggy.txt)

In the editor, the representation shows this:

![image](https://user-images.githubusercontent.com/1374914/196821598-f1b235d6-5c69-44d5-be87-7f5613f6e7e6.png)
![image](https://user-images.githubusercontent.com/1374914/196821590-ff295add-7e98-46e2-92c3-1f827d2c6d29.png)

The 2 notable points here are that the outgoing traffic to the outside of the cluster is denied, but to certain ports within anywhere the namespace the traffic is allowed. Notable about this is that the ports within the namespace are _not_ restricted to certain labels.

Upon actually running this, it turns out that the policy of denying to the outside of the cluster is affected by the allowed ports for the namespace, in the way that any port allowed inside the namespace seems to also be allowed for egress outside the cluster.

A hubble flow is here:
[matrix-flows.txt](https://github.com/cilium/cilium/files/9824939/matrix-flows.txt)

Notable here is that the following opened connections are forwarded, while the expected behavior based upon the web editor is to drop them. This seemingly might be because the port used was allowed within the namespace itself.

```
Oct 19 22:40:07.276: matrix/matrix-synapse-federation-sender-1-654f646674-9m2zx:44822 -> gluten.space:8448 L4-Only FORWARDED (TCP Flags: SYN)
Oct 19 22:40:07.276: matrix/matrix-synapse-federation-sender-1-654f646674-9m2zx:44822 -> gluten.space:8448 to-stack FORWARDED (TCP Flags: SYN)
```

In comparison, the requests to the outside to port 8080 are getting as expected dropped.

In slack the assumption was made that this unlabeled form may be causing this:

```
- toEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "443"
        - ports:
            - port: "8008"
....
```

However, it is unclear what the expected behavior for this kind of policy would be due to the missing labeling.

### Cilium Version

```
cilium-cli: v0.12.0 compiled with go1.18.4 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.12.3
cilium image (running): v1.12.3
```

### Kernel Version

`Linux nordgedanken.dev 5.18.18-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC Wed Sep 21 22:51:34 EEST 2022 x86_64 AMD Ryzen 5 3600 6-Core Processor AuthenticAMD GNU/Linux`

### Kubernetes Version

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"archive", BuildDate:"2022-10-16T21:06:41Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:42:30Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

I am unsure how to actually upload this as the sysdump is ~190MB and the maximum filesize for github is 25MB

### Relevant log output

```shell
There doesnt seem to be any major-related log output in the agent for this.
```

### Anything else?

This was initially reported in the slack at https://cilium.slack.com/archives/C01JALNQAR1/p1666208798569529

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
@MTRNord Can you share the full policy spec in question?

>I am unsure how to actually upload this as the sysdump is ~190MB and the maximum filesize for github is 25MB

You can try to upload a sysdump from one of the nodes where you think the policy behavior is unexpected.

**Comment by MTRNord** [comment]
> @MTRNord Can you share the full policy spec in question?

Thats the one in the [matrix.yaml](https://github.com/cilium/cilium/files/9824927/matrix_buggy.txt) file, which is also linked above.


> > I am unsure how to actually upload this as the sysdump is ~190MB and the maximum filesize for github is 25MB
> 
> You can try to upload a sysdump from one of the nodes where you think the policy behavior is unexpected.

That dump size is a single node (my cluster is a single node setup.). I can host it, probably on my nextcloud though

**Comment by aanm** [comment]
@MTRNord If I understood the problem correctly, my answer is that this is the expected behavior since traffic not allowed by a policy is immediately dropped once a policy selects a pod.
