### ISSUE TITLE
2 clusters + clustermesh + Istio = no healthy endpoints

### ISSUE THREAD

**Issue by gawsoftpl** [cilium/cilium#21815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My environment has 2 clusters connected with cilium clustermesh.

1. Cluster 1 + istio 
2. Cluster 2 + Istio

I added svc in both clusters. Problem is that when I run pod with istio sidecar in cluster 2 and I try to send a request to service in cluster 1 I received an error with: **no healthy endpoints.** 

Without istio sidecar everything works fine. 

Problem is that istio sidecar first checks the endpoints list for service on Cluster 2. I added ServiceEntry for istio, but this only works when I set static ip:

```sh
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-mongocluster
spec:
  hosts:
  - mymongodb.somedomain # not used
  addresses:
  - 192.192.192.192/24 # VIPs
  ports:
  - number: 27018
    name: mongodb
    protocol: MONGO
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
  - address: 2.2.2.2
  - address: 3.3.3.3
  ```

Is there a configuration for setup clustermesh with istio ? Or maybe Istio is old technology and should be abandoned?

### Cilium Version

cilium-cli: v0.12.4 compiled with go1.19.1 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.3

### Kernel Version

5.15.0-50

### Kubernetes Version

1.25

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darkstarmv** [comment]
Cilium sets endpoints in network layer where Istio configures endpoints from K8s and these two are not aware of each other.
