### ISSUE TITLE
Add date of last page edit to Cilium's documentation

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#21847]
The documentation at https://docs.cilium.io/ have a commit reference in its footer, which tells from what Cilium commit the documentation was generated. However, it is global to the whole documentation, and does not really speak for the date of the last change on the document.

It would be nice to find a way to add this date, to reflect whether the page has been updated recently or whether it has remained untouched for a long time. Although this is not a perfect indicator on the freshness of the information, it can tell if a page has a high risk of being outdated.

Technically, I suppose it shouldn't be too hard to retrieve the commit id of the last change for a document, and to pass it for printing to the theme that we use for the docs. However, there are two things to keep in mind:

- It should be easy to retrieve the commit for the last update of a documentation source file, but it will likely be harder to reflect all changes for the resulting HTML page when this RST file includes another file as a fragment. I don't know if Sphinx provides an API to easily iterate on included files.
- Many pages would likely be dated from the recent reorganisation of the documentation files, given that source files were moved around, even though the actual text contents was unmodified. But there's probably not much to do here.

**Comment by kaiwalyakoparkar** [comment]
Hey @qmonnet I would like to work on this issue. I would appreciate if you can help me know the files likely to be updated and procedures as I am new to this project :)

**Comment by qmonnet** [comment]
Hi, and thanks!

I'm sorry, I'm currently on leave and won't be able to help you much during the coming days/weeks. I'd suggest joining the [#sig-docs](https://cilium.slack.com/archives/C9J6SC295) channel on Slack to get some advice/guidance.

Here are a few pointers anyway:

- [How to contribute](https://docs.cilium.io/en/latest/contributing/development/contributing_guide/) (with regards to submitting the PR, etc.)
- [The branch for the theme we use for the docs](https://github.com/cilium/sphinx_rtd_theme/tree/v1.0). This is where we'll need to edit the HTML/CSS to add the date in the footer. There's already the Git revision for the doc in the footer, we can probably look for its origin and grab the date in addition to the SHA. I haven't investigated to find how the SHA is retrieved, so you'll have to look into that.
- [Documentation/conf.py](https://github.com/cilium/cilium/blob/master/Documentation/conf.py): This is where we configure Sphinx for building the docs. Not sure if you'll need to touch this to get the date, but maybe.

**Comment by kaiwalyakoparkar** [comment]
Thank you, I will start working on it shortly

**Comment by christarazi** [comment]
@kaiwalyakoparkar Do you plan to continue working on this issue?

**Comment by christarazi** [comment]
@kaiwalyakoparkar Sorry for the issues you're running into. I've not seen these before and I don't think we have any specific guidance for your issue. We have developers on Mac OS that haven't had issues. 

If you don't mind, I will unassign from the issue, but feel free to continue working on it :slightly_smiling_face: . Please reach out if you are able to make progress and if we can help on the next step. For now, I think trying to figure out why your machine is having trouble is the only way forward.

**Comment by kaiwalyakoparkar** [comment]
Sounds good @christarazi
