### ISSUE TITLE
Remove deprecated `spec.eni.{min-allocate,pre-allocate,max-above-watermark}` parameters

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#21858]
When we added Azure IPAM support in Cilum 1.7, we moved certain IPAM knobs (e.g. `spec.eni.pre-allocate/`) from `spec.eni` to `spec.ipam`. https://github.com/cilium/cilium/pull/10089/commits/cd24805873ad1baa1c23d26d96c8dbb4262be629

The following knobs have been deprecated since Cilium v1.7 and should be removed:

```
spec.eni.min-allocate
spec.eni.pre-allocate
spec.eni.max-above-watermark
```

**Comment by obaranov1** [comment]
@gandro Do you mean they should be removed everywhere in the project?
