### ISSUE TITLE
Expose SRv6 Status in `cilium status --verbose`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#21872]
We can probably follow the implementation for the host firewall (cf. https://github.com/cilium/cilium/pull/17165) and do the same for SRv6. The goal is to have a quick way to check that SRv6 is actually enabled and on what devices it runs.

The status should also state which encapsulation mode is being used (SRH vs. reduced).

**Comment by pchaigno** [comment]
@Vishal-Chdhry Pretty much the same changes as in #17165 are needed but for `option.Config.EnableSRv6` instead of `option.Config.EnableHostFirewall`.

**Comment by Vishal-Chdhry** [comment]
\assign

**Comment by ti-mo** [comment]
@Vishal-Chdhry are you still planning to work on this? I see the PR was closed due to inactivity.

**Comment by husnialhamdani** [comment]
\assign

**Comment by YutaroHayakawa** [comment]
@husnialhamdani I assigned you. Thanks!
