### ISSUE TITLE
Cilium pods fails to start

### ISSUE THREAD

**Issue by devopslyf** [cilium/cilium#21887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium pods fails to start

### Cilium Version

1.11.7

### Kernel Version

Linux kubeadm-master-01 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10", GitCommit:"eae22ba6238096f5dec1ceb62766e97783f0ba2f", GitTreeState:"clean", BuildDate:"2022-05-24T12:50:52Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: failed to install iptables rules: unable to run 'ip6tables -t nat -S' iptables command: ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n (exit status 3)" subsys=daemon
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Can you try upgrading to a more recent Cilium version? Some iptables bugs have been fixed in recent Cilium versions. /cc @jibi

**Comment by abuxliu** [comment]
@aanm I tried v1.12.2 version, also has this error. @devopslyf  Are you solved this?
