### ISSUE TITLE
Remove non services v2 bpfmaps from bugtool

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#21905]
Bugtool currently attempts to dump legacy maps lb4_services which haven't existed in several versions. Its probably pretty safe to remove those now.

**Comment by Vishal-Chdhry** [comment]
Hi! @tommyp1ckles I would love to work on this issue, can You please guide me a little on what I have to do?

**Comment by tommyp1ckles** [comment]
Hi @Vishal-Chdhry, great, no problem.

[Bugtool](https://docs.cilium.io/en/v1.12/cmdref/cilium-bugtool/) is a utility we package with Cilium to help dump debug info.

It basically runs a bunch of various other cilium [commands](https://github.com/cilium/cilium/blob/master/bugtool/cmd/configuration.go) and other system tools and collects the output. One of the things that we do is dump bpf maps using bpftool. Some of the maps that we're dumping where at one point considered legacy but haven't been in use in quite some time (I believe they where last used in Cilium v1.8). So at this point its probably pretty safe to remove them from the dumps:

Namely, 
* lb_services
* lb_backends

Note: for each of these types, there's two maps, one for ipv4 and one for ipv6.
