### ISSUE TITLE
sysctlfix doesn't properly flush/close the overrides file before restarting systemd-sysctl unit

### ISSUE THREAD

**Issue by jdef** [cilium/cilium#21916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

problem code:
https://github.com/cilium/cilium/blob/master/tools/sysctlfix/main.go

we noticed flakey behavior on some hosts, where the `net.ipv4.conf.all.rp_filter` setting was not properly set to `0` even after the cilium agent init-containers ran. the generated override file seemed to be in place, but the live value for the aforementioned sysctl was still set to `1` and so the cilium health endpoint was timing out. manually setting the live value of the sysctl to `0` resolved the health endpoint issue.

strongly suspect that because the sysctl.d/ override file is not being properly flushed/closed *before* the restart of the `systemd-sysctl` unit, that the new sysctls aren't always being eval'd as intended.

### Cilium Version

1.11.10

### Kernel Version

5.10.32

### Kubernetes Version

1.23.13

### Sysdump

sorry, airgapped system

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jdef** [comment]
maybe related to #20437

**Comment by aanm** [comment]
Very nice finding indeed. @dylandreimerink it looks that https://github.com/cilium/cilium/blob/master/tools/sysctlfix/main.go#L75 should have been done before https://github.com/cilium/cilium/blob/master/tools/sysctlfix/main.go#L132. @jdef feel free to submit a PR :-)

**Comment by jdef** [comment]
i've been waiting 2.5y for my company to approve a process by which I can push PRs. wish it was easier...

**Comment by Tyrael** [comment]
@aanm @dylandreimerink  any update on this?
it looks there was no commits related this issue and I don't expect @jdef to create an MR if he hasn't done so yet.
