### ISSUE TITLE
Ginkgo CI: Only run tests that are prefixed with specific suite strings

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2191]
The nightly Cilium tests are actually ran alongside the K8s tests because the test descriptor contains the string "K8s". Fix the logic for which tests we run by only running tests that start with a specific string (i.e., K8s* would be ran, not \*K8s\*)

**Comment by ianvernon** [comment]
This is strange. The documentation for `--focus` is the following:

>   -focus string
>    	If set, ginkgo will only run specs that match this regular expression.

The command I used to run this locally:
```
K8S_VERSION=1.6 ginkgo --focus="K8s*" -v -noColor
```

This is directly taken from `ginkgo.Jenkinsfile`. Yet, in `test/k8sT/Nightly.go`, the `Describe` for the test is:
```
var _ = Describe("NightlyK8sEpsMeasurement", func() {
```

**Comment by eloycoto** [comment]
@ianvernon 

I made some research here; we have two options: 

- Using the focus string with the test suite name. In this case `ginkgoext.GetScopeWithVersion()`
- Or using a space just before "K8S*", like this: 
```
ginkgo --focus " K8S*" -v  
```

Match name is the complete name and not only the describe name, so it matches all. 

https://github.com/onsi/ginkgo/blob/master/internal/spec/specs.go#L85

Here two examples of the test name to match: 
```
'Foo Suite [Top Level] K8Spolicies K8Spolicies'
'Foo Suite [Top Level] NightlyK8STest NightlyK8STest'
```
