### ISSUE TITLE
Images in RC Helm Charts are unpinned  

### ISSUE THREAD

**Issue by austince** [cilium/cilium#21914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Unlike other releases, the Helm charts for RC releases do not have pinned images but rather use `latest` for all cilium repos with a pull policy of `Always` (see [1.13.0-rc1](https://artifacthub.io/packages/helm/cilium/cilium/1.13.0-rc1?modal=values)). This essentially makes it impractical to use these charts even in testing environments, as they will pull the latest `master` whenever a cilium container is created.

This is not the case with other releases (see [1.12.3](https://artifacthub.io/packages/helm/cilium/cilium/1.12.3?modal=values)), which pin both the tag and the sha. 

### Cilium Version

1.13.0-rc1

### Kernel Version

n/a

### Kubernetes Version

n/a

### Sysdump

n/a

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@austince thank you for filling this issue. The charts are fixed and they are pointing to the correct images. /cc @autophagy @Efrat19
