### ISSUE TITLE
CFP: Support UDPRoute in Cilium Gateway API

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#21930]
## Cilium Feature Proposal
        
The first cut for Gateway API was done in https://github.com/cilium/cilium/pull/21749, however, we have a couple of follow-up tasks to support more features from Gateway API upstream.

This is to track the work to support [UDPRoute](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.UDPRoute)

## Goals

TBD

## Proposed Solution

TBD

## Tasks

TBD

**Comment by youngnick** [comment]
The work to implement TCPRoute and UDPRoute has so much in common that it's better to track it with one issue. Closing as duplicate, moving to #21929.
