### ISSUE TITLE
runtime: program exceeds 10000-thread limit

### ISSUE THREAD

**Issue by mantoine96** [cilium/cilium#21948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In a newly deployed cluster, running v1.12.3, I see some Cilium-agents pods regularly restarting due to thread exhaustion. This is causing disruption since we are leveraging L7 policies / DNS Proxy.

### Cilium Version

v1.12.3

### Kernel Version

5.4.209-116.367.amzn2.x86_64

### Kubernetes Version

v1.23.10-eks-15b7512

### Sysdump

https://drive.google.com/file/d/14X5_fKVs3jjWlpeXujAgjWIPz13dLWYR/view?usp=share_link

### Relevant log output

```shell
runtime: program exceeds 10000-thread limit
runtime stack:
/usr/local/go/src/runtime/panic.go:992 +0x71
/usr/local/go/src/runtime/proc.go:763 +0x8c
/usr/local/go/src/runtime/proc.go:779 +0x36
/usr/local/go/src/runtime/proc.go:2297 +0x90
/usr/local/go/src/runtime/proc.go:2404 +0x5a
/usr/local/go/src/runtime/proc.go:3036 +0x45
/usr/local/go/src/runtime/proc.go:3194 +0x25e
/usr/local/go/src/runtime/proc.go:3336 +0x14d
/usr/local/go/src/runtime/asm_amd64.s:425 +0x43
/usr/local/go/src/runtime/sigqueue.go:151 +0x2f
/usr/local/go/src/runtime/netpoll.go:302 +0x89
/usr/local/go/src/runtime/netpoll.go:302 +0x89
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/netpoll.go:302 +0x89
/usr/local/go/src/runtime/netpoll.go:302 +0x89
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/netpoll.go:302 +0x89
/usr/local/go/src/runtime/netpoll.go:302 +0x89
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/sema.go:513 +0x13d
/usr/local/go/src/runtime/sema.go:513 +0x13d
github.com/go-openapi/runtime/client.(*Runtime).Submit(0xc001857ad0, 0xc02a0372c0)
/vendor/github.com/go-openapi/runtime/client/runtime.go:468 +0x445
```

### Anything else?

I don't think it is related, but when we deployed v1.12.3 on our main clusters we noticed some issues around identities.

For example, one of our deployments' identity would not propagate and would therefore get denied access to resources:
![image](https://user-images.githubusercontent.com/1666462/199204702-981af007-a240-4c4e-b2f1-b7362aacc769.png)
![image](https://user-images.githubusercontent.com/1666462/199204755-2fc8f39d-2ec5-47da-8b58-9e17f11a5ff8.png)

```
root@ip-10-210-129-85:/home/cilium# cilium identity get 22027
Error: Cannot get identity for given ID 22027: [GET /identity/{id}][404] getIdentityIdNotFound
```

Worth noting though that I have not been able to reproduce this on our testing cluster, and looking at the stacktrace for the thread exhaustion, it seems mainly related to the fqdn/dnsproxy subsystem.

[Example pod logs](https://github.com/cilium/cilium/files/9911188/logs.json.tar.gz)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
The provided sysdump seems to belong to Cilium version `quay.io/cilium/cilium:v1.10.9` and not the version mentioned in the issue description.

**Comment by mantoine96** [comment]
Oh sorry @aanm I messed up and uploaded the wrong sysdump. I added a link with the correct sysdump (I couldn't upload it directly on GitHub as it is around 35MB)

**Comment by aanm** [comment]
Can you provide all of the cilium logs from the previous container?

**Comment by mantoine96** [comment]
Sure @aanm , just added [the logs](https://github.com/cilium/cilium/files/9911188/logs.json.tar.gz) to the issue.

**Comment by aanm** [comment]
Can you check what is your max DNS requests in flight? Once you have that number can you set it as a value for the flag `dnsproxy-concurrency-limit` in the cilium-agent? I would also suggest to check why the upstream DNS is taking so much time to reply for DNS requests.

If it happens again it would be good to have a pprof CPU trace.

**Comment by mantoine96** [comment]
Hey @aanm 

I haven't been able to reproduce this issue in the newer versions of Cilium 1.12, so I'll close this issue. Thanks for your assistance!
