### ISSUE TITLE
Add --flow-debug field to protect per flow debug log messages

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2195]
Per flow debug messages can fill up the log quickly, add a `--flow-debug` or `--debug-level` or similar flag to require opt-in to this granularity of log messages.

**Comment by joestringer** [comment]
Can we set up per-module / per-file rate limiters that wrap the log.Foo() calls and restrict how much output we get to the logs?

I'm thinking that each file can specify, for instance, `log = common.DefaultLogger.WithRatelimit(5, time.Minute)`. The only thing is that if we have a ratelimiter on logs, then we likely want a method to also disable it when we really need all of those logs.

**Comment by tgraf** [comment]
@joestringer I like the proposal overall but I think for per flow debug messages, we should require opt-in anyway as it will get extremely verbose and even a rate limited logger will slow everything down considerably
