### ISSUE TITLE
SRv6: Set the outer IPv6 flowlabel hash

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#21961]
The IPv6 flowlabel field can be used by NICs for RSS. In SRv6 encapsulation, this is crucial as most NICs likely will only be able to use the outer IPv6 header to pick the queue, so without a flowlabel, all packets with the same outer IP addresses will end up on the same queue.

From @YutaroHayakawa:

> The `H.Encaps` section of [RFC8986](https://datatracker.ietf.org/doc/html/rfc8986) says it should follow the way specified in [RFC6437](https://datatracker.ietf.org/doc/html/rfc6437), but its :exploding_head:
I think we can follow the way of kernel implementation.
https://github.com/torvalds/linux/commit/b5facfdba14ccb440bd1eac20870a8f23afa17f3#diff-4da369b586ba9233e8a230875d06c5daa731175a8c483e3fcc0691aab9cd9817R103-R105

Following the kernel implementation is probably a better idea indeed. We could more specifically follow the `seg6_flowlabel=1` implementation. Not sure if we have an easy way to retrieve the skb hash though (i.e., not sure skb->hash is always set at the time of encap.).

**Comment by slayer321** [comment]
Hey @pchaigno , I did like to work on this issue.

**Comment by pchaigno** [comment]
@slayer321 Go ahead. Please keep in mind though that the main item of work here is to confirm that `skb->hash` is set when we perform the SRv6 encapsulation in the datapath. That will require running Cilium with IPv6 enabled and adding BPF debug logs.
