### ISSUE TITLE
CI: [Travis] pkg/alibabacloud/eni unit test is flaky

### ISSUE THREAD

**Issue by joamaki** [cilium/cilium#21964]
Observed in: https://app.travis-ci.com/github/cilium/cilium/jobs/587322013.

```
----------------------------------------------------------------------
FAIL: node_test.go:135: ENISuite.TestPrepareIPAllocation
node_test.go:159:
    c.Assert(a.EmptyInterfaceSlots, check.Equals, 1)
... obtained int = 0
... expected int = 1
OOPS: 4 passed, 1 FAILED
```

Reproducible locally with:

`go test ./pkg/alibabacloud/eni -test.v -test.count 100 -race 2>&1 | tee /tmp/eni-test.log`

Judging from logs, it appears there to be a background goroutine doing work after the test has finished 
(likely the "ipam-node-manager-resync" trigger from ipam.NewNodeManager):

```
level=info msg="Attached ENI to instance" eniID=46bccefc-d645-4647-bdb2-0802b04668dc securityGroupIDs="[sg-1]" subsys=eni toAllocate=10 vSwitchID=vsw-1
OK: 5 passed
level=warning msg="Unable to compute pending pods, will not surge-allocate" error="pod store uninitialized" instanceID=i-1 name=node1 subsys=ipam
--- PASS: Test (0.01s)
PASS
```

Unfortunately ipam.NodeManager does not expose a way to clean up & wait for the trigger 
and the controller to be removed. Preferably we'd refactor NodeManager to include a `Stop`
method to gracefully clean it up. This would also need a blocking `Trigger.Shutdown()` to make
sure that the function really does not get executed after it.

The test failure might be unrelated to having a trigger or controller executing in the background since
each test case should have their own instances. Potentially this flake is due to race with `mngr.Update()` 
and subsequent `Get().Ops().PrepareIPAllocation()` call?

**Comment by joamaki** [comment]
Ping @jaffcheng. You've recently fixed a bug related to this. Would you have an idea what's going on?

**Comment by jaffcheng** [comment]
I'll look into this later this week.

**Comment by ti-mo** [comment]
This was hit by https://github.com/cilium/cilium/pull/21833.

**Comment by jaffcheng** [comment]
@joamaki  Thanks for the investigation! I've sent a PR to fix this, please take a look.
