### ISSUE TITLE
Policy to access localhost doesn't work

### ISSUE THREAD

**Issue by MrFreezeex** [cilium/cilium#21965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have been testing cilium network policy lately and stumbled upon both the echo live on this subject (https://hackmd.io/@Echo-Live/040) and a blog post https://medium.com/@charled.breteche/kubernetes-security-explore-cilium-host-firewall-and-host-policies-de93ea9da38c also referenced in echo.

Both of these take the approach of applying policy to localhost connections (`allow-localhost: "policy"`). However I initially didn't wanted to bother with that (also my goal was to apply host firewall first and not everywhere).

So I tried to allow all localhost connections with `allow-localhost: "always"` (IIUC default should be also the same but just to be sure...) and well it didn't really worked out. While in audit mode I can see this for the coredns probe traffic (triggered by kubelet doing the probe but can also be triggered by running a curl on the local node):
```
Policy verdict log: flow 0xa4f7a163 local EP ID 2823, remote ID 10286, proto 6, egress, action audit, match none, 10.233.64.72:57110 -> 10.233.64.209:8080 tcp SYN
```

I also tried what is described here https://docs.cilium.io/en/latest/security/policy/language/#access-to-from-local-host but with the localhost policy mode and the ccnp matching all the nodes + allowing the node entity on egress and with that I now also see the ingress part:
```
Policy verdict log: flow 0xa4f7a163 local EP ID 2823, remote ID 10286, proto 6, egress, action audit, match none, 10.233.64.72:57110 -> 10.233.64.209:8080 tcp SYN
Policy verdict log: flow 0xa4f7a163 local EP ID 3980, remote ID host, proto 6, ingress, action audit, match none, 10.233.64.72:57110 -> 10.233.64.209:8080 tcp SYN
```

So even there the coredns is somehow not recognized as being inside the node entity.

Here is my endpoints on this node:
```
ENDPOINT   POLICY (ingress)   POLICY (egress)    IDENTITY   LABELS (source:key[=value])                                                  IPv6   IPv4            STATUS
           ENFORCEMENT        ENFORCEMENT
2823       Disabled (Audit)   Disabled (Audit)   1          k8s:node-role.kubernetes.io/control-plane                                                           ready
                                                            k8s:node.kubernetes.io/exclude-from-external-load-balancers
                                                            reserved:host
3630       Disabled (Audit)   Disabled (Audit)   4          reserved:health                                                                     10.233.64.199   ready
3980       Disabled (Audit)   Disabled (Audit)   10286      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system          10.233.64.209   ready
                                                            k8s:io.cilium.k8s.policy.cluster=default
                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns
                                                            k8s:io.kubernetes.pod.namespace=kube-system
                                                            k8s:k8s-app=kube-dns
```

The documentation does mention that the `node` entity should also represent all the pods in the local node so to me this should theoretically be working fine however for some reasons it doesn't.

While checking how the "node" entity is implemented, I noticed that the `reserved:host` label is not on the coredns pod so I think that would explain why it's not really part of this entity. But that being said I have very limited experience with how cilium works regarding policy and label so it might not be the correct explanation...

### Cilium Version

1.12.3

### Kernel Version

4.18.0-372.9.1.el8.x86_64 (rocky 8.6)

### Kubernetes Version

v1.24.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Thank you for the GH issue. It is not clear to me what you are trying to achieve. The `allow-localhost` would refer to traffic originated from the host's network namespace and not from the pods not running in the host network namespace.

**Comment by MrFreezeex** [comment]
> Thank you for the GH issue. It is not clear to me what you are trying to achieve. The `allow-localhost` would refer to traffic originated from the host's network namespace and not from the pods not running in the host network namespace.

My original intention was to allow probing pod health endpoints (rewadyness and health probes) from the local host. So at the very least from the kubelet (so host namespace to a pod a in the same host). So it seems to me that theorically the `allow-localhost` should allow this kind of traffic but apparently not 🤔.

**Comment by aanm** [comment]
With the `allow-localhost: auto` it has the behavior that you are expecting.

**Comment by MrFreezeex** [comment]
> With the `allow-localhost: auto` it has the behavior that you are expecting.

Either `allow-localhost: auto` or ``allow-localhost: always` doesn't seems to work for this... If I have the host firewall mode enabled I need to explicitly add a cilium network policy to allow access to pod health endpoint or else it is blocked :(. I have a bit more explanation on my first message. There is an example of a flow that is audited on my first message if you want to check and an hypothesis about the issue...

But basically these settings:
```
enable-host-firewall: "true"
enable-policy: always
policy-audit-mode: "true"
```

Should be sufficient to reproduce, you would be able to see that any kubelet probes to pod (for instance coredns) are audited (and even blocked if you remove the policy mode ofc).

**Comment by aanm** [comment]
To get this right you tried out:
```
enable-host-firewall: "true"
enable-policy: always
policy-audit-mode: "true"
allow-localhost: auto
```
and
```
enable-host-firewall: "true"
enable-policy: always
policy-audit-mode: "true"
allow-localhost: always
```

and neither of these set of options worked?

**Comment by MrFreezeex** [comment]
Yes I just double checked, both indeed doesn't work.

Here is an example with coredns that probe on the 8080 port.

I got the same kind of output with both configs:
```
$ kubectl exec -it -n kube-system cilium-cfs7s -- cilium monitor -t policy-verdict | grep -i audit | grep 8080
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), clean-cilium-state (init)
Policy verdict log: flow 0x7526f850 local EP ID 2526, remote ID 846, proto 6, egress, action audit, match none, 10.233.65.196:43516 -> 10.233.65.36:8080 tcp SYN
Policy verdict log: flow 0x517ce88f local EP ID 2526, remote ID 846, proto 6, egress, action audit, match none, 10.233.65.196:43600 -> 10.233.65.36:8080 tcp SYN
$ kubectl exec -it -n kube-system cilium-cfs7s -- cilium endpoint ls
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), clean-cilium-state (init)
ENDPOINT   POLICY (ingress)   POLICY (egress)    IDENTITY   LABELS (source:key[=value])                                                  IPv6   IPv4            STATUS
           ENFORCEMENT        ENFORCEMENT
430        Disabled (Audit)   Disabled (Audit)   4          reserved:health                                                                     10.233.65.192   ready
929        Disabled (Audit)   Disabled (Audit)   846        k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system          10.233.65.36    ready
                                                            k8s:io.cilium.k8s.policy.cluster=default
                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns
                                                            k8s:io.kubernetes.pod.namespace=kube-system
                                                            k8s:k8s-app=kube-dns
2526       Disabled (Audit)   Disabled (Audit)   1          k8s:node-role.kubernetes.io/control-plane                                                           ready
                                                            k8s:node.kubernetes.io/exclude-from-external-load-balancers
                                                            reserved:host
```

**Comment by riuvshyn** [comment]
it seems I am having exactly same issues... 
I know it's been a while but still @MrFreezeex did you manage to solve this issue?

**Comment by MrFreezeex** [comment]
I didn't recall this being fixed in my old tests and I forgot the workaround I was doing sorry :/

**Comment by riuvshyn** [comment]
No worries, thanks for the response anyway! do you still have cilium helm chart inputs by any chance?

**Comment by guoard** [comment]
> The problem is the egress traffic. If you have the host firewall enabled and specified egress rules, the host is not able to reach the pod.

I encountered the same issue. Enabling egress traffic for all nodes resolved it. For example:

```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-node-egress
spec:
  nodeSelector:
    matchLabels: {}
  egress:
    - toEntities:
        - all
```
