### ISSUE TITLE
Issue on GKE with calico

### ISSUE THREAD

**Issue by jxdn** [cilium/cilium#21984]
Hi I have A kubernetes cluster (GKE) running with calico in GCP.

Iam following the guides on <https://docs.cilium.io/en/v1.12/gettingstarted/cni-chaining-calico/> , and iam deploying the cilium with
`helm install cilium cilium/cilium --version 1.12.3   --namespace=kube-system   --set cni.chainingMode=generic-veth   --set cni.customConf=true   --set cni.configMap=cni-configuration   --set tunnel=disabled   --set enableIPv4Masquerade=false   --set enableIdentityMark=false --set cni.binPath=/home/kubernetes/bin  --set ipam.mode=kubernetes   --set ipv4NativeRoutingCIDR=$NATIVE_CIDR`

but i face this error:

any idea why ?

[Slack Message](https://cilium.slack.com/archives/C1MATJ5U5/p1667440980373239)

**Comment by jxdn** [comment]
![image](https://user-images.githubusercontent.com/36805254/199635230-f12fe658-0b7c-4058-b09b-e0d2bbb6bcc9.png)

**Comment by joestringer** [comment]
Cilium does not have any error like `cannot find a qualified ippool`:

```
cilium $ git grep "cannot find a qualified ippool"
cilium $
```

It looks like maybe Calico is returning this error, so you would need to follow up with the Calico folks.
