### ISSUE TITLE
[docs] Document enabling ping with host firewall

### ISSUE THREAD

**Issue by withinboredom** [cilium/cilium#21986]
## Cilium Feature Proposal

Currently, the docs [show how to allow a port](https://docs.cilium.io/en/stable/gettingstarted/host-firewall/#apply-a-host-network-policy), but once that is applied, ICMP packets are also dropped. This may not always be desirable, and locating how to enable ICMP packets is [is quite the adventure](https://docs.cilium.io/en/stable/policy/language/#example-icmp-icmpv6).

**Describe the feature you'd like**

1. Update the docs to point out that applying the policy will drop all other traffic, including ICMP. While this may seem somewhat obvious, the example makes it appear as though we're only applying TCP/UDP rules (and kubernetes usually doesn't concern itself with ICMP).
2. Include an example of properly enabling ICMP packets to the host.

**Comment by pchaigno** [comment]
Good suggestion! We forgot to update the host firewall docs after we added support for ICMP policies. Could you send a pull request to update the documentation as you suggested?

> locating how to enable ICMP packets is [is quite the adventure](https://docs.cilium.io/en/stable/policy/language/#example-icmp-icmpv6).

Do you mean it was hard to find in the documentation? What could we do to improve that?

**Comment by withinboredom** [comment]
> Could you send a pull request to update the documentation as you suggested?

@pchaigno, if you could point me in the direction on how to do so, I'd be more than happy to help.

> Do you mean it was hard to find in the documentation? What could we do to improve that?

Yeah, it was quite difficult to find because you'd have to know what to search for. I initially used "ping" as part of my query, which gave no results. It was only through digging through the CRD spec that I was able to discover it was called ICMP (at which point I face-palmed). Then I had to guess how to implement it in a host firewall correctly, look up what "type 128" and "type 32" meant, and hope I didn't mess something up along the way.

I venture the spec on ICMP types hasn't nor will change very much, but it would be nice to put a table of the types you support and their human meaning; in case they diverge at some distant point in the future. Also, it saves everyone a bit of googling -- especially when using ipv6 and requiring ICMP6 router announcements, and other important messages to get through the firewall.

**Comment by pchaigno** [comment]
> > Could you send a pull request to update the documentation as you suggested?
> 
> @pchaigno, if you could point me in the direction on how to do so, I'd be more than happy to help.

Arf, sorry, I started testing an updated policy when I saw the stalebot message. I would appreciate a review on the updated policy though: https://github.com/cilium/cilium/pull/22999.

> I venture the spec on ICMP types hasn't nor will change very much, but it would be nice to put a table of the types you support and their human meaning; in case they diverge at some distant point in the future.

ICMP and ICMPv6 types are assigned by the IANA so I don't think they will change any time soon :slightly_smiling_face: 

> Yeah, it was quite difficult to find because you'd have to know what to search for. I initially used "ping" as part of my query, which gave no results. It was only through digging through the CRD spec that I was able to discover it was called ICMP (at which point I face-palmed). Then I had to guess how to implement it in a host firewall correctly, look up what "type 128" and "type 8" meant, and hope I didn't mess something up along the way.

Thanks! Lots of good actionable comments here I think. Let's keep this issue to track the documentation changes. I've created a new issue for the longer-term feature change (3rd item).

- [ ] Mention "ping" in the documentation to ease search.
- [ ] Link to the IANA pages for [ICMP](https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml) and [ICMPv6](https://www.iana.org/assignments/icmpv6-parameters/icmpv6-parameters.xhtml) from the ICMP policy docs.
- [ ] Support names for the ICMP and ICMPv6 types: https://github.com/cilium/cilium/issues/23000.

**Comment by dipankardas011** [comment]
> > > Could you send a pull request to update the documentation as you suggested?
> > 
> > 
> > @pchaigno, if you could point me in the direction on how to do so, I'd be more than happy to help.
> 
> Arf, sorry, I started testing an updated policy when I saw the stalebot message. I would appreciate a review on the updated policy though: #22999.
> 
> > I venture the spec on ICMP types hasn't nor will change very much, but it would be nice to put a table of the types you support and their human meaning; in case they diverge at some distant point in the future.
> 
> ICMP and ICMPv6 types are assigned by the IANA so I don't think they will change any time soon slightly_smiling_face
> 
> > Yeah, it was quite difficult to find because you'd have to know what to search for. I initially used "ping" as part of my query, which gave no results. It was only through digging through the CRD spec that I was able to discover it was called ICMP (at which point I face-palmed). Then I had to guess how to implement it in a host firewall correctly, look up what "type 128" and "type 8" meant, and hope I didn't mess something up along the way.
> 
> Thanks! Lots of good actionable comments here I think. Let's keep this issue to track the documentation changes. I've created a new issue for the longer-term feature change (3rd item).
> 
> * [ ]  Mention "ping" in the documentation to ease search.
> * [ ]  Link to the IANA pages for [ICMP](https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml) and [ICMPv6](https://www.iana.org/assignments/icmpv6-parameters/icmpv6-parameters.xhtml) from the ICMP policy docs.
> * [ ]  Support names for the ICMP and ICMPv6 types: [Support names for the ICMP and ICMPv6 types #23000](https://github.com/cilium/cilium/issues/23000).

I think this Issue is completed
