### ISSUE TITLE
bgp: BGP Control Plane status in agent cli

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#22009]
Currently the BGP control plane is a one way street, we can make configuration but there is no user friendly way to get meaningful feedback as to the status of the control plane. The only options at this time is to inspect the agent logs and to check connections from the other side of a BGP connection.

It would be really nice to add a few features to the agent CLI:
* Add a line in `cilium status` if the BGP Control plane is enabled, something like `BGP Control plane: OK 2/2 sessions established` or of course showing that something is wrong with one or more connections.
* Add a `cilium bgp` command to the agent to go into more depth. This command should show details about the BGP speakers/vRouters and their peers (Connection status, uptime, settings (timings, has password yes/no), amounts of sent/received routes).
* Add a `cilium bgp routes` command which lists all routes that we are currently announcing, why we are announcing them (PodCIDR, LB SVC, Egress GW, Additional routes). Having the ability to filter/query with flags or some sort of query language would be nice since this list might get substantial.

Additional thoughts:
* Should also be added to sysdump as soon as the command exists to aid in debugging BGP related issues
* Outputs should support JSON format to be easily processed by machines.

**Comment by YutaroHayakawa** [comment]
Some thought around this. When implementing the above commands, ideally, we shouldn't `kubectl exec` into every node and aggregate results. We should instead implement an API server to collect and aggregate status (like we do for Cilium monitor => Hubble relay). And the CLI commands should be a wrapper of the API client.

This is because if we implement such logic into the CLI, it's hard for users to collect status programmatically. They need to build cilium-cli into their execution environment, or they need to reimplement the logic by themselves if they are not happy about that. This makes Cilium BGP automation friendly and hopefully makes easy to collaborate with SDN or Network Observability vendor solutions.

**Comment by MikeZappa87** [comment]
Something I have always found useful is BMP (openBMP is worth a look).

**Comment by erdeerdeerde** [comment]
I would love to have this too..

**Comment by danehans** [comment]
xref https://github.com/cilium/cilium/pull/28175 (author: @harsimran-pabla) that includes surfacing status in the new BGP CP CRDs. Is CLI status still required after the new CRDs are implemented?

Additionally, the `cilium bgp peers` command appears to resolve the first 2 bullets in this issue:
```
$ cilium bgp peers
Node                              Local AS   Peer AS   Peer Address   Session State   Uptime   Family         Received   Advertised
bgp-cplane-dev-v4-control-plane   65001      65000     10.0.1.1       established     3m20s    ipv4/unicast   0          0
                                                                                               ipv6/unicast   0          0
bgp-cplane-dev-v4-worker          65002      65000     10.0.2.1       established     3m17s    ipv4/unicast   0          0
                                                                                               ipv6/unicast   0          0
```

https://github.com/cilium/cilium/pull/27182 resolves the 3rd bullet in the agent CLI and https://github.com/cilium/cilium/issues/27420 tracks similar support for cilium-cli.

**Comment by harsimran-pabla** [comment]
> xref #28175 (author: @harsimran-pabla) that includes surfacing status in the new BGP CP CRDs. Is CLI status still required after the new CRDs are implemented?

I think CLI will still be required. CRD state can be used by automation tools, whereas CLI is more of a debugging tool. We also expose other BGP states like routes or policy configuration via CLI, which will not be exposed via k8s. Having the peering state also exposed via CLI makes it easier for users during debugging sessions to avoid going back and forth between CLI and kubectl to inspect BGP state.

**Comment by AnishShah** [comment]
Based on https://github.com/cilium/cilium/issues/22009#issuecomment-1751438442, it looks like we have addressed all the items mentioned in the issue. Is there anything left?

**Comment by dylandreimerink** [comment]
I think so, closing the issue
