### ISSUE TITLE
Fatal on DSR + tunneling

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#22003]
We should fatal on DSR + tunneling as it is not supported today.

Reported-by: @bmcustodio

**Comment by Shunpoco** [comment]
Hi @pchaigno, can I work on this issue?

I think we should modify [this part](https://github.com/cilium/cilium/blob/master/daemon/cmd/kube_proxy_replacement.go#L219-L225).

**Comment by pchaigno** [comment]
@Shunpoco Yes, that's correct. Feel free to send a PR.
