### ISSUE TITLE
Helm install may conflict when enable ingress controller and hubble ui ingress.

### ISSUE THREAD

**Issue by fly3366** [cilium/cilium#22018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

svclb-* will always pendding. because svclb-hubble-ui nad svclb will use same port!

### Cilium Version

master

### Kernel Version

4.19

### Kubernetes Version

1.25 k3s

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@fly3366 can you provide more information? Like a sysdump or the steps that you used to install Cilium? Otherwise it will be difficult to help you. Thank you

**Comment by tnorlin** [comment]
@fly3366 just to elaborate - svclb, does it mean LoadBalancer type Service? IF so, then the IP will be in state Pending until there is a service (metalLB, for instance) that provides address.

And the Service/Ingress shares IP/Port in presentation, as for instance:
```
kubectl get svc,ingress,ep -n jaeger |grep ingress
service/cilium-ingress-jaeger-ingress       LoadBalancer   10.100.201.66   172.16.25.2   80:31363/TCP,443:31644/TCP               30h
ingress.networking.k8s.io/jaeger-ingress   cilium   jaeger.demo.mylocal   172.16.25.2   80, 443   30h
endpoints/cilium-ingress-jaeger-ingress       192.192.192.192:9999                                         30h
```
