### ISSUE TITLE
New pods are not managed by Cilium on AKS

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#22013]
I've bisected this bug to commit https://github.com/cilium/cilium/commit/0d6346dbe5bada046eb72ab2f797fa4c0f86d07e. With that commit, on AKS, new pods are not managed by Cilium. In the connectivity tests, this is surfaced by the check for CiliumEndpoints failing.

### Reproduction Steps
```
az group create --subscription "${SUBSCRIPTION}" --name "${NAME}" --location "${LOCATION}" --tags "${TAGS[@]}" && az aks create --subscription "${SUBSCRIPTION}" --resource-group "${NAME}" --name "${NAME}" --network-plugin azure --node-count 3 "${COST_REDUCTION[@]}"
az aks get-credentials --subscription "${SUBSCRIPTION}" --resource-group "${NAME}" --name "${NAME}"
./cilium install --agent-image=docker.io/pchaigno/cilium-dev:0d6346dbe5bada046eb72ab2f797fa4c0f86d07e --operator-image=docker.io/pchaigno/operator-azure:0d6346dbe5bada046eb72ab2f797fa4c0f86d07e --config debug=true --azure-subscription "${SUBSCRIPTION}" --azure-resource-group "${NAME}"
kubectl get cep -A
```

The last step should return an empty result, even though the CLI deleted all umanaged pods as part of the installation. A run of `cilium connectivity test` will also fail.

### Sysdump

[cilium-sysdump-20221104-223346.zip](https://github.com/cilium/cilium/files/9942112/cilium-sysdump-20221104-223346.zip)

cc @squeed

**Comment by squeed** [comment]
I'm pretty sure this was caused by using v1.12 charts with an image from tip. In other words, I don't *think* there was a bug here.
