### ISSUE TITLE
Cilium kube-proxy replacement breaks on EKS due to dynamic k8sServiceHost endpoint IP

### ISSUE THREAD

**Issue by munjalpatel** [cilium/cilium#22039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium would work on newly added nodes (by cluster auto-scaler) just as its working on the nodes it was originally installed on.

### Cilium Version

```
cilium-cli: v0.12.6 compiled with go1.19.1 on darwin/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.3
cilium image (running): v1.12.3
```

### Kernel Version

```
Linux ip-10-0-76-118.us-west-2.compute.internal 5.10.135 #1 SMP Tue Oct 18 01:58:53 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20221107-153111.zip](https://github.com/cilium/cilium/files/9956327/cilium-sysdump-20221107-153111.zip)

### Relevant log output

```shell
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.47.0.0/16
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://10.1.0.1:443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://10.1.0.1:443" subsys=k8s
level=error msg="Unable to contact k8s api-server" error="Get \"https://10.1.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.1.0.1:443: i/o timeout" ipAddr="https://10.1.0.1:443" subsys=k8s
level=fatal msg="Unable to initialize Kubernetes subsystem" error="unable to create k8s client: unable to create k8s client: Get \"https://10.1.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.1.0.1:443: i/o timeout" subsys=daemon
```

**Logs from existing node where Cilium is working fine**
```shell
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.118.0.0/16
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://10.1.0.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Trying to auto-enable \"enable-node-port\", \"enable-external-ips\", \"bpf-lb-sock\", \"enable-host-port\", \"enable-session-affinity\" features" subsys=daemon
level=info msg="Inheriting MTU from external network interface" device=eth0 ipAddr=10.0.76.118 mtu=9001 subsys=mtu
```

### Helm config values
```js
{
  rollOutCiliumPods: true,
  autoDirectNodeRoutes: true,
  egressMasqueradeInterfaces: 'eth0',
  tunnel: 'disabled',
  kubeProxyReplacement: 'strict',
  k8sServiceHost: '10.1.0.1.',
  k8sServicePort: '443',
  loadBalancer: {
    algorithm: 'maglev',
    serviceTopology: true,
  },
  maglev: {
    hashSeed,
  },
  eni: {
    enabled: true,
    awsReleaseExcessIPs: true,
  },
  ipam: {
    mode: 'eni',
  },
  socketLB: {
    hostNamespaceOnly: true,
  },
  hubble: {
    enabled: true,
    relay: {
      enabled: true,
    },
    ui: {
      enabled: true,
    },
    metrics: {
      enabled: ['dns:query;ignoreAAAA', 'drop', 'tcp', 'flow', 'icmp', 'http'],
    },
    tls: {
      auto: {
        method: 'cronJob',
      },
    },
  },
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@munjalpatel Thank you for opening the GH issue. When running with kube-proxy replacement, you need to specify the real IP address of the kube-apiserver and not the service IP. This is important if you are not running with kube-proxy to perform the service translation between the service IP and the real IP address.

**Comment by munjalpatel** [comment]
Thanks, @aanm for the response. How do I get the real IP in EKS?

**Comment by aanm** [comment]
It's one of the IP addresses available in `kubectl get endpoints kubernetes`

**Comment by munjalpatel** [comment]
@aanm that was the first thing I did before switching to `10.1.0.1`

The problem there was that in EKS, the `endpoint` IP changed after ~12 hours and broke every Cilium daemonset and essentially, everything stopped working.

**Comment by aanm** [comment]
If you are running with kube-proxy, then using 10.1.0.1 will be safe because kube-proxy is responsible for translating that IP address into the real IP address of kube-apiserver.

**Comment by munjalpatel** [comment]
@aanm, we are not running with `kube-proxy` we are going for the `strict` mode to completely get rid of `kube-proxy`

**Comment by aanm** [comment]
I understand but kube-proxy also needs the "real" IP address of kube-apiserver so the problems you are having with Cilium because the IP is always changing, you would also face the same with kube-proxy.

**Comment by munjalpatel** [comment]
I think it must be how we configured EKS with Pulumi, it might have taken an old EKS cluster's endpoint IP. I'll revert to the correct endpoint IP and monitor for the next few hours. Thanks for the help though :)

**Comment by munjalpatel** [comment]
@aanm, EKS changed the endpoint IP again. Now it's `10.0.111.131`, and Cilium is broken once again.
This makes Cilium completely unusable with EKS; no one else on EKS is facing this issue?

**Comment by aanm** [comment]
@munjalpatel it all depends how you are configure kube-proxy. Can you set up a cluster with kube-proxy and see how kube-proxy is configured? The IP address that kube-proxy is using should be the same one that you need to pass to Cilium when you are running with kube-proxy replacement.

**Comment by munjalpatel** [comment]
@aanm we fixed this issue by using the `hostname` of EKS cluster.
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.yl4.us-west-2.eks.amazonaws.com
```

This should be really documented. It will save the next person hours of hair-pulling!

**Comment by munjalpatel** [comment]
@aanm PR submitted: https://github.com/cilium/cilium/pull/22057
