### ISSUE TITLE
Disrupted connections to clustermesh etcd leads to thundering herd

### ISSUE THREAD

**Issue by Sinjo** [cilium/cilium#22037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# Symptoms

After a [short networking disruption in AWS](https://www.availabl.co/aws/eu-west-1?start=1667392140000&end=1667392920000), instances of `cilium-agent` that were running outside of that region and configured to connect to clustermesh etcd instances inside that region all tried to reconnect at once.

This immediately overwhelmed the etcd instance, to the point where it consumed as much CPU as it could, but ultimately couldn't serve all those clients attempting to reconnect.

In the agent logs, there were a couple of errors that were happening frequently and looked relevant:

```
{
  "level": "warn",
  "ts": "2022-11-02T15:32:02.613Z",
  "logger": "etcd-client",
  "caller": "v3/retry_interceptor.go:62",
  "msg": "retrying of unary invoker failed",
  "target": "etcd-endpoints://[redacted]",
  "attempt": 0,
  "error": "rpc error: code = Unknown desc = etcdserver: too many requests"
}
```

and

```
level=warning msg="Unable to establish etcd connection to remote cluster" clusterName=[redacted] config=/var/lib/cilium/clustermesh/[redacted] error="etcdserver: too many requests" kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
```

The way we initially found out about it was via alerting on the `cilium_controllers_failing` metric.

# Recovery

Everything was able to very gradually return to a steady state, as `cilium-agent` instances successfully made a connection to the clustermesh etcd instances in the affected region. This graph of `cilium_controllers_failing` shows that happening over a period of a few hours:

![Screenshot from 2022-11-07 20-41-44_redacted](https://user-images.githubusercontent.com/237226/200412310-9ec158b1-27df-4a58-9502-49b230cef1d0.png)

# Code exploration and potential solutions

**Caveat**: This is my first time looking through the Cilium, etcd, and gRPC codebases, and I might have drawn some wrong conclusions.

I spent some time after the incident having a look through the Cilium codebase to try and figure out why this happened. The conclusion I reached is that there are two layers at which retry can happen: the etcd client itself, and the controller loop when `DoFunc` returns an error. I'm going to tackle them separately.

## etcd client

As far as I can tell, the etcd client used by the clustermesh [doesn't set any custom connection options for retries](https://github.com/cilium/cilium/blob/2e4df97693eb3e7d2aa57c8df4b03d8052c59882/pkg/clustermesh/remote_cluster.go#L165-L169). It passes through an etcd client config file which gets parsed into [this struct](https://github.com/etcd-io/etcd/blob/f64bed603314ce81450ff2f1723eab37df16f8c6/client/v3/yaml/config.go#L29-L41) with [these embedded fields](https://github.com/etcd-io/etcd/blob/f64bed603314ce81450ff2f1723eab37df16f8c6/client/v3/config.go#L28-L94).

The fields which can be specified via YAML don't let you control retry behaviour. To do that, you'd need to pass a custom `DialOptions` from code. Eventually, that config makes its way into a call to [etcd's `client.New`](https://github.com/cilium/cilium/blob/2e4df97693eb3e7d2aa57c8df4b03d8052c59882/pkg/kvstore/etcd.go#L679).

After stepping down a few function calls in the etcd client code, specifically:

  - [`newClient`](https://github.com/etcd-io/etcd/blob/f64bed603314ce81450ff2f1723eab37df16f8c6/client/v3/client.go#L83)
  - [`dialWithBalancer`](https://github.com/etcd-io/etcd/blob/f64bed603314ce81450ff2f1723eab37df16f8c6/client/v3/client.go#L419)
  - [`dial`](https://github.com/etcd-io/etcd/blob/f64bed603314ce81450ff2f1723eab37df16f8c6/client/v3/client.go#L284)
  - [`dialSetupOpts`](https://github.com/etcd-io/etcd/blob/f64bed603314ce81450ff2f1723eab37df16f8c6/client/v3/client.go#L289)

we get to the last part of that `dialSetupOpts` call that we [get a default retry policy set up](https://github.com/etcd-io/etcd/blob/f64bed603314ce81450ff2f1723eab37df16f8c6/client/v3/client.go#L237-L246). From what I can see, it doesn't look great. `defaultBackoffWaitBetween` is set to [25 milliseconds](https://github.com/etcd-io/etcd/blob/f64bed603314ce81450ff2f1723eab37df16f8c6/client/v3/options.go#L52-L53), which, if my understanding is right and this is the timeout we end up with, is pretty aggressive.

Assuming I've not made a crucial mistake in my reading of the code (which is very possible), I'm thinking it might be worth setting up a less aggressive retry policy on the etcd client via a `DialOption` - potentially user configurable, but maybe there's a reasonable one that would cover most/all uses.

## Controller retries

The fact that we saw that second log line, with the message `Unable to establish etcd connection to remote cluster`, indicates that we're eventually getting an error back from the etcd client and hitting [this conditional](https://github.com/cilium/cilium/blob/2e4df97693eb3e7d2aa57c8df4b03d8052c59882/pkg/clustermesh/remote_cluster.go#L176-L182).

When that happens, we hit [this conditional](https://github.com/cilium/cilium/blob/2e4df97693eb3e7d2aa57c8df4b03d8052c59882/pkg/controller/controller.go#L232-L240) and retry with an ever increasing delay (1s additional delay per consecutive failure, rather than exponential backoff, and no jitter).

I'm not sure how relevant these retries are compared to the etcd client ones. If I've understood both parts of the code right, the etcd client ones are way more aggressive, and therefore way more problematic in these conditions. That would definitely match up with the fact that I saw way more instances of the first log line from above than the second.

---

Sorry for the wall of text. Hopefully everything in there makes sense. If not, I'm happy to clarify anything I've said, and to provide additional details.

Thanks in advance for your help!

### Cilium Version

`1.12.3`

### Kernel Version

`Linux ip-[redacted] 5.15.0-1021-aws #25~20.04.1-Ubuntu SMP Thu Sep 22 13:59:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

v1.22.15-eks-fb459a0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dctrwatson** [comment]
Not unexpectedly, this is still happening in v1.12.4

**Comment by giorio94** [comment]
Thank @Sinjo for reporting this issue, and for the thorough investigation. 

I've started deepening into this, and I could reproduce the problem using a mock etcd server which always responds to Range requests with the `"etcdserver: too many requests"` error. 

In that specific situation, the aggressive retry does not appear to come from the UnaryClientInterceptor configured by the etcd client (i.e., the one mentioned above, and characterized by  `defaultBackoffWaitBetween`=25ms), since with most  errors (including ResourceExhausted) the retry loop is interrupted [here](https://github.com/cilium/cilium/blob/5c811513eae2bfe2bf745277f5c7b71b9290ca14/vendor/go.etcd.io/etcd/client/v3/retry_interceptor.go#L88-L90) after the first attempt (this can also be observed since the `attempt` number in the error message is always 0). 

Differently, the aggressive behavior traces to the implementation of the [Watch](https://github.com/cilium/cilium/blob/5c811513eae2bfe2bf745277f5c7b71b9290ca14/pkg/kvstore/etcd.go#L918) function, and in particular to the initial [Get](https://github.com/cilium/cilium/blob/5c811513eae2bfe2bf745277f5c7b71b9290ca14/pkg/kvstore/etcd.go#L945-L946) request, which in case of errors is re-attempted in an infinite loop, paced by a rate limiter configured with [20 QPS](https://github.com/cilium/cilium/blob/5c811513eae2bfe2bf745277f5c7b71b9290ca14/pkg/defaults/defaults.go#L298-L299). I've opened #23467 adding an exponential backoff to prevent such tight loop to occur if the Get operation fails.

**Comment by squeed** [comment]
Here's a wild idea: What if only the cilium-operator was responsible for connecting to remote clustermesh peers? It could then gossip identities to the local cluster, probably via [memberlist](https://github.com/hashicorp/memberlist)? That would reduce etcd connections by an order of magnitude.

**Comment by Sinjo** [comment]
Thanks for taking the time to look into this @giorio94. Really appreciate you pointing me at where the problem actually ended up being too.

@squeed Something like that definitely sounds appealing. One of my background worries has been how large the mesh could become before there were too many connections to etcd even under normal circumstances, but I'm not sure where that tipping point is.

**Comment by giorio94** [comment]
> Here's a wild idea: What if only the cilium-operator was responsible for connecting to remote clustermesh peers? It could then gossip identities to the local cluster, probably via [memberlist](https://github.com/hashicorp/memberlist)? That would reduce etcd connections by an order of magnitude.

I personally agree that having a single per-cluster component responsible for connecting to the remote etcd cluster, and then distributing the information to the agents, could definitely help with the scalability in case of large setups.
