### ISSUE TITLE
DSR Not working on my virtual machine

### ISSUE THREAD

**Issue by pengbinbin1** [cilium/cilium#22064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. I have installed cilium on my k8s cluster.I have set the DSR on the configmap. I  had noticed that the node port services are only working through local nodes (Local nodes are those nodes where the actual backend node is running)  ,but it will not work if the backend is on a remote node. I had checked whether the XDP acceleration is installed use command `cilium status`,there is no information for XDP.I have 2 questoins: 1. Why the DSR can not work on my VM ?  2. Dose DSR can only work well with XDP acceleration?  If not , where is the ebpf hooked to sovle the DSR scenario?

### Cilium Version

1.11

### Kernel Version

4.18 

### Kubernetes Version

1.20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
> Why the DSR can not work on my VM ?

Could you share exact reproduction steps or a sysdump, or ideally both?

> 2. Dose DSR can only work well with XDP acceleration?

No.

> If not , where is the ebpf hooked to sovle the DSR scenario?

The eBPF logic to implement DSR is at the tc-bpf program for the native device (as well as the tc-bpf hook of veth pairs for the backends).

**Comment by pengbinbin1** [comment]
> > Why the DSR can not work on my VM ?
> 
> Could you share exact reproduction steps or a sysdump, or ideally both?
> 
It is a security policy on my envirenment,i have resiolved it.
> > 2. Dose DSR can only work well with XDP acceleration?
> 
> No.
> 
> > If not , where is the ebpf hooked to sovle the DSR scenario?
> 
> The eBPF logic to implement DSR is at the tc-bpf program for the native device (as well as the tc-bpf hook of veth pairs for the backends).
And which module process the response about DSR, in my opinion it will do SNAT when response to the DSR request. Thank you.
