### ISSUE TITLE
CNI plugin should tolerate a down agent.

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#22067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While uninstalling Cilium, deletion of existing pods fails since the agent is down. It fails with the message

` failed to destroy network for sandbox \"\": plugin type=\"cilium-cni\" failed (delete): unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get \"http:///var/run/cilium/cilium.sock/v1/config\": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory\nIs the agent running?" `

The CNI specification says that, on delete, CNI plugins should be as error-tolerant as possible. So, if at all possible, the CNI binary should be able to handle a deletion without the agent running.

### Cilium Version

v1.13.0-rc2

### Kernel Version

n/a

### Kubernetes Version

n/a

### Anything else?

Related: https://github.com/cilium/cilium/issues/20723

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Now, this isn't so easy, since the cilium-cni plugin talks to the agent to delete endpoints.

@tommyp1ckles, maybe we can just ignore failed deletion requests on the CNI side and let the restoration logic clean them up?

Alternatively, we could write endpoints-to-delete to disk (perhaps just as filenames) and have the agent process these on startup?

**Comment by tommyp1ckles** [comment]
@squeed Makes sense that in the absence of Agent we should just clean up startup.

I'm not 100% sure that everything would get cleaned up correctly. #20350 should ensure that CEPs get cleaned up provided that all the necessary Endpoint cleanup happens correctly.

I'll take a look to see what this might look like.

**Comment by squeed** [comment]
This just bit an end-user.

They had nodes running at capacity, then they kicked off a Cilium upgrade. This caused the agent pod to be deleted, then another pod swooped in and was scheduled. Then, they couldn't recover the node: because couldn't delete any pods without a CNI configuration file.

The CNI spec, and kubelet's expectations, are that delete basically never fails. So, yes, I think we need this, but I need to understand what happens when the agent comes back up. How does it synchronize with existing state on the node?

**Comment by tommyp1ckles** [comment]
From the previous comment:

> Alternatively, we could write endpoints-to-delete to disk (perhaps just as filenames) and have the agent process these on startup?

Would this be sufficient in all cases, such as the one you described, where you need a delete due to capacity issues?

**Comment by tommyp1ckles** [comment]
Just trying to get my mind fully around this now..

> couldn't delete any pods without a CNI configuration file.

Why would the cni conf be deleted between an upgrade? I'd expect it to just be possibly rewritten at some point?

**Comment by squeed** [comment]
> Why would the cni conf be deleted between an upgrade, I'd expect it to just be possibly rewritten at some point?

Yeah, we delete the CNI configuration file as part of a `preStop` hook. We really need to stop doing this, but doing so at least prevents the cni plugin from getting a CNI DEL it can't handle.

**Comment by squeed** [comment]
> > Alternatively, we could write endpoints-to-delete to disk (perhaps just as filenames) and have the agent process these on startup?
> 
> Would this be sufficient in all cases, such as the one you described, where you need a delete due to capacity issues?

It should work! We need CNI DELs to succeed so that we can get cilium back on the node.

**Comment by squeed** [comment]
First idea: Write pending Endpoint deletion requests to a directory. The basic workflow would be:

1. cni plugin tries to connect to `/run/cilium/cilium.sock`. If that fails:
2. Touch `/run/cilium/deletionQueue/<CONTAINERID>`

Then, on plugin startup, drain the directory before starting up the API. Simple, right? No, because we have to worry about race conditions / TOCTOU.

So, we need to add some [file locking](http://0pointer.de/blog/projects/locking.html). Now, the steps are:

**Agent**
1. Try and connect to socket. On failure:
2. Take a shared lock on `/run/cilium/deletionQueue/lockfile`
3. Check to see if the socket now exists. If so, back to step 1.
4. Touch `/run/cilium/deletionQueue/<CONTAINERID>`
5. Release the lock

**Daemon**
1. Take an exclusive lock on `/run/cilium/deletionQueue/lockfile`. Do not unlock until the process exits
2. Process all pending deletion requests, deleting them while finished
3. Start the API server
4. Drop the lock

**Comment by tommyp1ckles** [comment]
Makes sense to me, Agent would probably need to take hold of the lock prior to starting the API socket, and we could cleanup after k8s store sync similar to the stale CEP cleanup.

Is there any reason to consider having some of the Agents endpoint restore logic be built into CNI - then just let the CEP be cleaned up on Agent start?
