### ISSUE TITLE
Agent Should Not Hard Fail on Config Values Above Max

### ISSUE THREAD

**Issue by isugimpy** [cilium/cilium#22070]
https://github.com/cilium/cilium/blob/dd08c3f2c2383948d7b21a65be90de8eaed86f14/pkg/option/config.go#L3422-L3425

Just got bitten by this in production.
`level=fatal msg="Error while creating daemon" error="invalid daemon configuration: specified PolicyMap max entries 131072 must not exceed maximum 65536" subsys=daemon`
While I do believe that 131072 is an excessive amount for the PolicyMap max entries, a hard exit with code 1 seems inappropriate.  Could this (and other bounded startup options) instead be changed to throw a warning and enforce the hard maximum value?

**Comment by pchaigno** [comment]
Sounds like a good improvement to me! We'd welcome a pull request implementing this.
