### ISSUE TITLE
CI: re-enable coverage reporting in `.github/workflows/lint-bpf-checks.yaml`

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#22088]
See #22078 and https://github.com/cilium/cilium/pull/22043#issuecomment-1307887505 for context.

/cc @ti-mo

**Comment by ti-mo** [comment]
Some progress, coverbee was updated to correctly handle instruction metadata in 0.3.0, but enabling it on https://github.com/cilium/cilium/pull/23281 causes some sort of panic. Another patch may be needed.

**Comment by StLeoX** [comment]
So is there any coverage data I can see?
