### ISSUE TITLE
Bump minimal kernel version to 4.19 / 4.18 RHEL

### ISSUE THREAD

**Issue by brb** [cilium/cilium#22116]
As discussed offline, we have decided to bump the minimal supported kernel vsn to 4.18 on RHEL / 4.19 other distros in v1.13.

This is a placeholder issue to track the required work.

- [x] #22586
- [x] Remove 4.9 CI job https://github.com/cilium/cilium/pull/23343
- [x] Move kube-proxy only to 4.19. The mixed mode (KPR=strict && kube-proxy) can be moved to the conformance DP job. https://github.com/cilium/cilium/pull/22062
- [ ] Identify datapath / agent parts which can be removed (most likely only hacks for IPCache's LPM)
  - [x] PrefixLengthCounter in Daemon: https://github.com/cilium/cilium/pull/25153
  - [x] Trigger to regenerate datapath in daemon policy handling
  - [x] Prefix length tracking and delete feature support checks in pkg/maps/ipcache
  - [x] bpf code LPM from hashmaps in bpf/lib/eps.h, related macros
  - [ ] CLI hint code when LPM map dumps don't list anything
- [ ] Bump minimum kernel version in [`pkg/datapath/linux/requirements.go`](https://github.com/cilium/cilium/blob/d6503fa75b48504e8bee9a0aa3cdc427c4fec623/pkg/datapath/linux/requirements.go#L27-L32)
- [ ] Make 4.19 the default development VM.

**Comment by pchaigno** [comment]
I've added an item to remember to also bump the default development VM version to the 4.19's given that the new minimum version we support.

**Comment by julianwiedmann** [comment]
Checking in - are we ok with merging changes that intentionally break 4.9 (ie. https://github.com/cilium/cilium/pull/23634#issuecomment-1425921626) while the 4.9 pipeline is still running (https://github.com/cilium/cilium/pull/23343) ?

I would feel more comfortable if we at least mark the 4.9 Jenkins job as `not-required`.

(cc @rgo3 @nbusseneau )

**Comment by julianwiedmann** [comment]
@brb :wave: checking if we can maybe close this.

>CLI hint code when LPM map dumps don't list anything

mind pointing at an example?

>Bump minimum kernel version in [pkg/datapath/linux/requirements.go](https://github.com/cilium/cilium/blob/d6503fa75b48504e8bee9a0aa3cdc427c4fec623/pkg/datapath/linux/requirements.go#L27-L32)

This doesn't exist in main, was removed with 755a6b93a1c0.

> Make 4.19 the default development VM.

Is this about vagrant? :zombie:

**Comment by brb** [comment]
> mind pointing at an example?

IIRC it was `cilium bpf ipcache list`. On some old kernels (definitely pre-4.19) it was not possible to get next bpf elem in an LPM map (https://github.com/cilium/cilium/issues/1673 hints that). Thus, cilium-agent used to bookkeep entries in user-space of such maps.

> Is this about vagrant? 🧟

Yep :skull: 

Thanks for bringing up this issue. We can close it :tada:
