### ISSUE TITLE
CFP: Pod MAC Address Specification

### ISSUE THREAD

**Issue by dsxsh** [cilium/cilium#22119]
**Is your feature request related to a problem?**

Lots of software requires licensing that's tied to a MAC address. Often the solutions for this are insanely convoluted and require things like Docker in Docker inside the cluster. 

**Describe the feature you'd like**

A pod is able to request a dedicated, pre-defined MAC address, and it succeeds in that request. 

**(Optional) Describe your proposed solution**

Calico seemingly supports this: [here](https://projectcalico.docs.tigera.io/networking/pod-mac-address)
However, not sure of the technical complexity and/or proposed solution.

**Comment by joestringer** [comment]
This seems like a reasonable suggestion. The code that creates the veth pair would need to be made aware of this new MAC address. From recollection this is part of the CNI plugin, so perhaps when the CNI plugin does an EndpointCreate request to cilium-agent, cilium-agent could fetch the MAC annotation from the corresponding Pod and return the desired MAC address in its API response. Then the CNI could implement the MAC address change.

**Comment by Inigo4562** [comment]
Are there any updates on this feature?

**Comment by youngnick** [comment]
It sounds like this feature is ready for someone to pick it up and begin design work. I think @joestringer's comments capture a likely way to make this happen, so I'll tag this as help-wanted.

If you're interested in working on this, please comment here and it can be assigned to you.

**Comment by Inigo4562** [comment]
I have never looked into this repo so it might be a good excuse to do so. I can try at least

**Comment by youngnick** [comment]
Okay @Inigo4562, it's all yours, please ask for help here if you need it.

**Comment by chaunceyjiang** [comment]
> so perhaps when the CNI plugin does an EndpointCreate request to cilium-agent, cilium-agent could fetch the MAC annotation from the corresponding Pod and return the desired MAC address in its API response. 


Hi @youngnick @joestringer I want to contribute this feature, but currently I have a problem, which is how CNI obtains MAC information.
Now I can get the MAC information on the server-side, but I don't know how to return it to CNI. You mentioned using the response value of `EndpointCreate` to return information, but I found that `EndpointCreate` only returns an error type.

Refer to: 
[EndpointCreate
](https://github.com/cilium/cilium/blob/main/pkg/client/endpoint.go#L44-L49)

**Comment by michi-covalent** [comment]
hi @Inigo4562 just checking in are you still interested in working on this? if not i'll assign it to @chaunceyjiang .

**Comment by Inigo4562** [comment]
Hello @michi-covalent, I haven't put enough time to work on this issue so please assign to @chaunceyjiang
