### ISSUE TITLE
CI: ConformanceAKS: curl succeeded while it should have failed due to incorrect exit code

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#22162]
Several curl tests are failing because the commands succeed when we expected them to fail. For example:
```
[=] Test [all-ingress-deny]
..
  ℹ️  📜 Applying CiliumNetworkPolicy 'all-ingress-deny' to namespace 'cilium-test'..
  [-] Scenario [all-ingress-deny/pod-to-pod]
  [.] Action [all-ingress-deny/pod-to-pod/curl-0: cilium-test/client2-bb57d9bb4-b5pbz (10.0.1.204) -> cilium-test/echo-other-node-694dd79b46-qzslj (10.0.0.220:8080)]
  [.] Action [all-ingress-deny/pod-to-pod/curl-1: cilium-test/client2-bb57d9bb4-b5pbz (10.0.1.204) -> cilium-test/echo-same-node-865dcc9b58-nz2tf (10.0.1.86:8080)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.0.1.86:8080/" succeeded while it should have failed: 
  ℹ️  curl output:
```

Examples:
https://github.com/cilium/cilium/actions/runs/3461307458/jobs/5779401491
https://github.com/cilium/cilium/actions/runs/3457550315/jobs/5771080426
https://github.com/cilium/cilium/actions/runs/3456343637/jobs/5769011681

Sysdumps for the first two examples above:
[cilium-sysdump-out.zip.zip](https://github.com/cilium/cilium/files/10007663/cilium-sysdump-out.zip.zip)
[cilium-sysdump-out.zip(1).zip](https://github.com/cilium/cilium/files/10007664/cilium-sysdump-out.zip.1.zip)

**Comment by margamanterola** [comment]
BTW, looking at the failed results, we see that not always the same individual tests are failing. For example, in [this one](https://github.com/cilium/cilium/actions/runs/3457550315/jobs/5771080426) the first failure is echo-ingress-l7 whereas in [this one](https://github.com/cilium/cilium/actions/runs/3456343637/jobs/5769011681) the first failure is all-egress-deny.

Anyway, yes, this very much looks like a race. The question is why does our code think the policy should be in place when it's not fully there.

**Comment by jibi** [comment]
Just pushed a change to the CLI to capture sysdumps right after a test fails: https://github.com/cilium/cilium-cli/pull/1228, hopefully that will give us some better visibility into what's going on :crossed_fingers:

**Comment by pchaigno** [comment]
Latest discovery from Jibi on this is that it seems to be a similar issue to https://github.com/cilium/cilium/issues/15724 where `kubectl ... curl ...` returns a 0 exit code even though the curl clearly timed out. The test then fails because it thinks the request succeeded when it shouldn't have.

**Comment by pchaigno** [comment]
[Added some more debug output](https://github.com/cilium/cilium/pull/22526) to curl and reran a bunch of times (in parallel because I don't have forever :p).

[The expected output](https://github.com/cilium/cilium/actions/runs/3609902939/jobs/6083378949) in case of a timeout looks like:
```
[2022-12-03T19:55:10Z]   ❌ command "curl -vvv -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.0.0.172:8080/" failed: command terminated with exit code 28
[2022-12-03T19:55:10Z]   ℹ️  curl output:
[2022-12-03T19:55:10Z]   *   Trying 10.0.0.172:8080...
* After 5000ms connect time, move on!
* connect to 10.0.0.172 port 8080 failed: Operation timed out
* Connection timeout after 5000 ms
* Closing connection 0
curl: (28) Connection timeout after 5000 ms
:0 -> :0 = 000
```
[The output we get](https://github.com/cilium/cilium/actions/runs/3609902920/jobs/6083378944) in our case is:
```
[2022-12-03T20:03:20Z]   ❌ command "curl -vvv -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.0.1.186:8080/" succeeded while it should have failed: *   Trying 10.0.1.186:8080...

[2022-12-03T20:03:20Z]   ℹ️  curl output:
[2022-12-03T20:03:20Z]   *   Trying 10.0.1.186:8080...
[2022-12-03T20:03:20Z]
```

It's as if the curl command had been interrupted before we reached the timeout (despite what the timestamps suggests).

For that reason, I'm starting to suspect it's a bug in the way we run curl rather than a bug in curl. Taking all this into account, it would be good to get agent/k8s/Golang eyes on https://github.com/cilium/cilium-cli/blob/1a823dc0a6afca645de32fbd057fff323a329f01/k8s/exec.go#L32 to see if something could explain the above.

**Comment by chancez** [comment]
Depending on api version and kubectl version, exit codes from kubectl exec may not be forwarded. That being said, the functionality for forwarding exit codes isn’t very new, I forget what version that was added. Maybe we can get verbose kubectl output (-v=10), it should have json output with the exec response code.

**Comment by tklauser** [comment]
> [Added some more debug output](https://github.com/cilium/cilium/pull/22526) to curl and reran a bunch of times (in parallel because I don't have forever :p).
> 
> [The expected output](https://github.com/cilium/cilium/actions/runs/3609902939/jobs/6083378949) in case of a timeout looks like:
> 
> ```
> [2022-12-03T19:55:10Z]   ❌ command "curl -vvv -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.0.0.172:8080/" failed: command terminated with exit code 28
> [2022-12-03T19:55:10Z]   ℹ️  curl output:
> [2022-12-03T19:55:10Z]   *   Trying 10.0.0.172:8080...
> * After 5000ms connect time, move on!
> * connect to 10.0.0.172 port 8080 failed: Operation timed out
> * Connection timeout after 5000 ms
> * Closing connection 0
> curl: (28) Connection timeout after 5000 ms
> :0 -> :0 = 000
> ```
> 
> [The output we get](https://github.com/cilium/cilium/actions/runs/3609902920/jobs/6083378944) in our case is:
> 
> ```
> [2022-12-03T20:03:20Z]   ❌ command "curl -vvv -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.0.1.186:8080/" succeeded while it should have failed: *   Trying 10.0.1.186:8080...
> 
> [2022-12-03T20:03:20Z]   ℹ️  curl output:
> [2022-12-03T20:03:20Z]   *   Trying 10.0.1.186:8080...
> [2022-12-03T20:03:20Z]
> ```
> 
> It's as if the curl command had been interrupted before we reached the timeout (despite what the timestamps suggest).

Not really relevant to the issue, but the timestamps stem from [logging in cilium-cli](https://github.com/cilium/cilium-cli/blob/1a823dc0a6afca645de32fbd057fff323a329f01/connectivity/check/action.go#L229-L232), not from when curl was executed. I think for that we'd need to add [`--trace-time`](https://everything.curl.dev/usingcurl/verbose/trace#trace-time) to the `curl` command.

**Comment by jibi** [comment]
> It's as if the curl command had been interrupted before we reached the timeout (despite what the timestamps suggest).

There's been a [similar report](https://discuss.kubernetes.io/t/go-client-exec-ing-a-shel-command-in-pod/5354) for the exact same logic we have in `k8s/exec.go`, where they suggested to use `stdin: false`.

For our case we can't just go for that as we need a way to interrupt the execution of the command after it times out, so I'm giving it a try to this new [StreamWithContext method](https://github.com/kubernetes/kubernetes/pull/103177/files) (needs to be backported to our own `client-go` fork)

**Comment by tklauser** [comment]
> > It's as if the curl command had been interrupted before we reached the timeout (despite what the timestamps suggest).
> 
> There's been a [similar report](https://discuss.kubernetes.io/t/go-client-exec-ing-a-shel-command-in-pod/5354) for the exact same logic we have in `k8s/exec.go`, where they suggested to use `stdin: false`.
> 
> For our case we can't just go for that as we need a way to interrupt the execution of the command after it times out, so I'm giving it a try to this new [StreamWithContext method](https://github.com/kubernetes/kubernetes/pull/103177/files) (needs to be backported to our own `client-go` fork)

Hopefully, our own fork shouldn't be needed anymore: https://github.com/cilium/cilium/pull/22547

Once that's merged in cilium/cilium we'd only need to update the vendored copy to a more recent client-go version providing `StreamWithContext`.

**Comment by pchaigno** [comment]
It is not as if someone else had already checked...

**Comment by jibi** [comment]
I did a few more tests by trying to set `tty: false` and adding printfs in the logic responsible for getting the data from the apiserver https://github.com/kubernetes/client-go/blob/6cbd19f22fe1f612bfc27a30a05a30613943d9bd/tools/remotecommand/v4.go#L54-L76 and:

* `p.Stdout` is not getting populated with the actual stdout but
* despite that, `wg.Wait()` https://github.com/kubernetes/client-go/blob/6cbd19f22fe1f612bfc27a30a05a30613943d9bd/tools/remotecommand/v4.go#L72 actually waits for the command to finish

My current theory is that something is going on in the apiserver (some of the streams in the spdy connections get closed/reset?) and that could explain also a different class of flakes that we've seen a few times like:

```
2022-12-07T17:32:12.2445705Z [2022-12-07T17:32:06Z]   🟥 Running test to-fqdns: setting up test: applying network policies: policies were not applied on all Cilium nodes in time: error dialing backend: write unix @->/tunnel-uds/proxysocket: write: broken pipe
2022-12-07T17:32:12.2445727Z 

```

**Comment by pchaigno** [comment]
> My current theory is that something is going on in the apiserver (some of the streams in the spdy connections get closed/reset?) and that could explain also a different class of flakes that we've seen a few times like:

Same theory here, but it's hard to confirm unfortunately. I've tried to reproduce this effect locally by cutting established connections to kube-apiserver but I haven't got a 0 exit code yet :-/

**Comment by pchaigno** [comment]
How did you retrieve the kubelet logs?

> ```
> kubelet-1.log:13:28:03.901767    3962 log.go:184] http: TLS handshake error from 10.224.0.5:47404: EOF
> ```
If we could figure what is behind 10.224.0.5:47404, we may be able to confirm or disprove the hypothesis that it's related to the kubectl error. That information should be in the bugtool report for the 10.224.0.5 node, but unfortunately there was an issue while collecting the bugtool reports in the sysdump after the error. The final sysdump doesn't have any reference to that port anymore.

**Comment by jibi** [comment]
> How did you retrieve the kubelet logs?

Just added a `for n in $(kubectl get nodes --no-headers | awk '{print $1}'); do ./test/nsenter.sh $n; done` to the `Post-test information gathering` job in order to run `/bin/journalctl --no-pager -au kubelet`, see the usual https://github.com/cilium/cilium/pull/22450 PR

> If we could figure what is behind 10.224.0.5:47404, we may be able to confirm or disprove the hypothesis that it's related to the kubectl error. That information should be in the bugtool report for the 10.224.0.5 node, but unfortunately there was an issue while collecting the bugtool reports in the sysdump after the error. The final sysdump doesn't have any reference to that port anymore.

Let me try run it again then

**Comment by jibi** [comment]
Similar? https://github.com/cilium/cilium/actions/runs/3674287408/jobs/6218240400

```
Mon, 12 Dec 2022 15:22:05 GMT   [.] Action [echo-ingress-l7/pod-to-pod-with-endpoints/curl-3-private: cilium-test/client2-7d8ccf8d-594q9 (10.0.1.238) -> curl-3-private (10.0.0.4:8080)]
Mon, 12 Dec 2022 15:22:05 GMT   ℹ️  unable to extract exit code from error: Timeout occurred
Mon, 12 Dec 2022 15:22:05 GMT   ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.0.0.4:8080/private" failed with unexpected exit code: Timeout occurred (expected 22, found -2)
Mon, 12 Dec 2022 15:22:05 GMT   📄 No flows recorded during action curl-3-private
Mon, 12 Dec 2022 15:22:05 GMT   📄 No flows recorded during action curl-3-private
```

there's a sysdump with the bugtool report, but I don't see any TLS error in the kubelet logs

**Comment by christarazi** [comment]
Are you still looking at this @jibi?

**Comment by jibi** [comment]
> Are you still looking at this @jibi?

This is on pause for now from my side as I don't have cycles :disappointed:

**Comment by pchaigno** [comment]
Got a recent occurrence at https://github.com/cilium/cilium/actions/runs/4799243965.
Sysdumps: [cilium-sysdumps.7z.zip](https://github.com/cilium/cilium/files/11332145/cilium-sysdumps.7z.zip) and [cilium-sysdump-final.zip](https://github.com/cilium/cilium/files/11332147/cilium-sysdump-final.zip)
Logs: [logs_1387297.zip](https://github.com/cilium/cilium/files/11332080/logs_1387297.zip)

**Comment by pchaigno** [comment]
The example above actually had a different root cause, explained at https://github.com/cilium/cilium-cli/issues/1260. I've sent https://github.com/cilium/cilium-cli/pull/1541 to try and fix that.

Let's take another occurrence that looks like the present issue: https://github.com/cilium/cilium/actions/runs/4806075784
Sysdump: [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/11333598/cilium-sysdumps.zip)
Logs: [logs_1390081.zip](https://github.com/cilium/cilium/files/11333607/logs_1390081.zip)

**Comment by pchaigno** [comment]
The workaround for this (cf. https://github.com/cilium/cilium-cli/pull/1543) is used in Cilium's CI so, if anyone hits this flake again, it would be good to know.

**Comment by amitmavgupta** [comment]
Hit this issue with AKS for Isovalent Enterprise for Cilium in Azure Marketplace. Let me know if I need to open a different issue for this, have the sysdump handy as well.

❌ 1/41 tests failed (1/282 actions), 14 tests skipped, 0 scenarios skipped:
Test [client-ingress-from-other-client-icmp-deny]:
  ❌ client-ingress-from-other-client-icmp-deny/client-to-client/ping-ipv4-1: cilium-test/client2-78f748dd67-dklg5 (192.168.1.206) -> cilium-test/client-7b78db77d5-ltl4q (192.168.1.161:0)
connectivity test failed: 1 tests failed

**Comment by pchaigno** [comment]
@amitmavgupta Did you have the error message `succeeded while it should have failed`? What version of the CLI were you using to run the connectivity tests?

**Comment by amitmavgupta** [comment]
@pchaigno Hi Paul- The test should have failed.

CLI version- 
cilium-cli: v0.14.5 compiled with go1.20.4 on darwin/arm64

**Comment by gandro** [comment]
I think I also hit this here:

```
  ℹ️  📜 Applying CiliumNetworkPolicy 'client-ingress-from-client2' to namespace 'cilium-test'..
  [-] Scenario [client-ingress/client-to-client]
  [.] Action [client-ingress/client-to-client/ping-ipv4-0: cilium-test/client-6f6788d7cc-jzxfm (10.0.0.38) -> cilium-test/client2-bc59f56d5-ds4jp (10.0.0.83:0)]
  ❌ command "ping -c 1 -W 2 -w 10 10.0.0.83" succeeded while it should have failed: PING 10.0.0.83 (10.0.0.83) 56(84) bytes of data.

  ℹ️  ping output:
  PING 10.0.0.83 (10.0.0.83) 56(84) bytes of data.
```

ping output is empty, meaning it likely didn't succeed. PR https://github.com/cilium/cilium/pull/26662 against `main`: https://github.com/cilium/cilium/actions/runs/5474746995/jobs/9969923321

**Comment by pchaigno** [comment]
Ah, [my "fix"](https://github.com/cilium/cilium-cli/blob/1b29d0a96f895c731927da2561b52240c17c63ce/connectivity/check/action.go#L291) doesn't work for ping because there is some output at the beginning even when it hangs. Maybe we can change the ping command we use to remove that first line:
```
PING 10.0.0.83 (10.0.0.83) 56(84) bytes of data.
```
