### ISSUE TITLE
NFS mount stuck after some time of working well  

### ISSUE THREAD

**Issue by edivita** [cilium/cilium#22185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a kubernetes single node installation which acts as both control plane and worker. This node was created initially with calico and after some months it was moved from calico to cilium v12.2 with kube-proxy replacement mode enabled and then the problem started: when the kubernetes node start everything works fine: all the ganesha pods exports the shares (via metalLoadBalancer) and those share are mountable as expected. After some time (1 or 2 weeks), without changing nothing - or at least nothing that I'm aware of - the NFS shares stop working for no reason and when I try to mount again the shares my client receive a timeout error. 

I've done a lot of testing and to my eyes it looks like there is something strange happening at network/cilium level: tshark reports that the TCP packets arrive to the server and the server reply, but I also see that the NFS packages (like the NFS Call) arrive to servre but the server never reply. 
I also enabled the full debug log in ganesha, in order to monitor what happen when I mount a share from a remote client and the logs doesn't report anything. So I decided to try to mount my share directly from the ganesha pod itself, in order to exclude all the the other network things which may be involved in the communication, and mounting 127.0.0.1 gives me the same result: timeout during the mount and no ganesha logs reported. 

To also exclude a problem in the ganesha pod I scaled down the replicas of the ganehsa pod to 0 and then back to 1 to force a pod recreation, but no luck at all. 

I restarted cilium pod and cilium operator pod, but also this wasn't helpful. The only thing which help is a node reboot, but this cannot be a solution. 

Cilium monitoring --type drop doesn't report any blocked packet, the node firewall is actually disabled (at least until I will find a solution to this problem), the kernel logs doesn't report something which looks important to my eyes (but you will understand better than me, of course). 

### Cilium Version

v1.12.2 

### Kernel Version

5.4.0-131-generic

### Kubernetes Version

v1.20.0

### Sysdump

[cilium-sysdump-20221115-133939.zip](https://github.com/cilium/cilium/files/10014697/cilium-sysdump-20221115-133939.zip)

### Anything else?

the host OS is Ubuntu 20.04.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rid** [comment]
It looks like it could be similar to https://github.com/cilium/cilium/issues/21541
