### ISSUE TITLE
CFP:  Whether Cilium plans to design out of tree IPAM plug-ins in the future？

### ISSUE THREAD

**Issue by weiwei02** [cilium/cilium#22222]
## Support the extension of IPAM  support to different cloud vendors outside the tree

Similar to the design and implementation of kubernetes CSI, it makes a high-level abstraction of ipam support to different cloud vendors. Leave the general functions in the core repository base of Cilium, and move the customized content of each cloud manufacturer to their own repository.
  If Cilium has such a set of general abstract interfaces, it is convenient to expand and develop Cilium in different IaaS environments.

**Is your feature request related to a problem?**

Designing a new set of IPAM interface protocols and moving the cloud manufacturer's code out of the tree has the following advantages:
1. Developers of cloud manufacturers do not need to submit code to the cilium code base, so that the maintenance cycles of IPAM and cilium are decoupled. If a cloud vendor has a bug in the connection with the cilium, it can be upgraded without the release of cilium.
2. In addition, if there is a set of abstract interfaces, it will be more helpful for testing. When cilium releases a new version, it does not need to test the environment of each cloud manufacturer.
If so, please describe the problem
3. In addition to the existing AWS, Azure, Alibaba, and GKE, there are many other cloud vendors that have supported or plan to support cilium. If their code is submitted to Cilium core repository. In the future, there will be many codes from various manufacturers in the cilium repository. Flags and configuration will be complex to a terrible amount.

**Describe the feature you'd like**
1. CRD data structure: remove CiliumNode and other data structure definitions related to cloud manufacturers, and convert them to a reference structure similar to 'OwnerReference' declared in CiliumNode. To describe the dependency on custom data structures.
2. Cilium operator: remove the cloud manufacturer's implementation of IPAM. Convert to code outside the tree for independent deployment.
3. Cilium agent: The agent configures different IPAM modes. NodeDiscovery registration, IPAM parameter filling and other cloud vendor related codes are moved out of the tree.
4. Cilium cni: After the IP application is completed, can you transfer more set features to other processes for processing instead of directly mixing the processing logic of cloud manufacturers in the code of Cilium cni.

Include any specific requirements you need

**(Optional) Describe your proposed solution**

The abstraction of CSI and CNI is a good example of out of tree extension. However, I have no good plan for the design of Cilium out of tree IPAM. At present, this is just an idea, but its benefits are obvious.
You can discuss whether Cilium will evolve in this direction in the future.

**Comment by wedaly** [comment]
At AKS, we integrated our IPAM implementation with Cilium using [delegated IPAM](https://github.com/cilium/cilium/pull/19219). This has the advantage of being part of the [CNI spec](https://www.cni.dev/docs/spec/#section-4-plugin-delegation), so the IPAM plugin doesn't need to depend on Cilium. It also requires no code changes in Cilium itself. We're using this today in AKS for [Azure CNI powered by Cilium](https://techcommunity.microsoft.com/t5/azure-networking-blog/azure-cni-powered-by-cilium-for-azure-kubernetes-service-aks/ba-p/3662341).

I'm not sure if this approach would work for everyone, but want to mention it as another way of drawing a boundary between Cilium and cloud-specific IPAM code.

**Comment by KaneVV1** [comment]
> At AKS, we integrated our IPAM implementation with Cilium using [delegated IPAM](https://github.com/cilium/cilium/pull/19219). This has the advantage of being part of the [CNI spec](https://www.cni.dev/docs/spec/#section-4-plugin-delegation), so the IPAM plugin doesn't need to depend on Cilium. It also requires no code changes in Cilium itself. We're using this today in AKS for [Azure CNI powered by Cilium](https://techcommunity.microsoft.com/t5/azure-networking-blog/azure-cni-powered-by-cilium-for-azure-kubernetes-service-aks/ba-p/3662341).
> 
> I'm not sure if this approach would work for everyone, but want to mention it as another way of drawing a boundary between Cilium and cloud-specific IPAM code.

We found that it needs local-router-ipv4, so enable-endpoint-routes needs to be turned on. However, BPF host routing is currently not supported with it. Does it mean that Delegated IPAM plugin does not support BPF host routing currently?
