### ISSUE TITLE
cluster not working against Ubuntu 22.04

### ISSUE THREAD

**Issue by sandeepksingla123** [cilium/cilium#22234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Ubuntu 18.04 works but Cluster 1.25 with Ubuntu 22.04 using Cilium CNI is not working.

It looks like CoreDNS returns DNS lookup failing with below error

[ERROR] plugin/errors: 2 1719163443584647392.8487499795824529487. HINFO: read udp 10.0.0.58:33144->168.63.129.16:53: i/o timeout
[ERROR] plugin/errors: 2 1719163443584647392.8487499795824529487. HINFO: read udp 10.0.0.58:37725->168.63.129.16:53: i/o timeout
[ERROR] plugin/errors: 2 1719163443584647392.8487499795824529487. HINFO: read udp 10.0.0.58:50031->168.63.129.16:53: i/o timeout
[ERROR] plugin/errors: 2 1719163443584647392.8487499795824529487. HINFO: read udp 10.0.0.58:47378->168.63.129.16:53: i/o timeout

Cilium Status

KVStore: Ok Disabled
Kubernetes: Ok 1.25 (v1.25.2) [linux/amd64]
Kubernetes APIs: ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumEndpointSlice", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement: Strict
Host firewall: Disabled
CNI Chaining: none
Cilium: Ok 1.12.2 (v1.12.2-c7516b9)
NodeMonitor: Disabled
Cilium health daemon: Ok
IPAM: IPv4: 7/254 allocated from 10.0.0.0/24,
BandwidthManager: EDT with BPF [CUBIC] [eth0]
Host Routing: BPF
Masquerading: BPF [eth0] 10.0.0.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status: 38/39 healthy
Name Last success Last error Count Message
cilium-health-ep 22h55m9s ago 4m10s ago 376 Get "http://10.0.0.56:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Proxy Status: OK, ip 10.0.0.203, 0 redirects active on ports 10000-20000
Global Identity Range: min 256, max 65535
Hubble: Disabled
Encryption: Disabled
Cluster health: 1/1 reachable (2022-11-15T11:51:59Z)

### Cilium Version

1.12.2

### Kernel Version

5.15.0-1022-azure

### Kubernetes Version

1.25.2

### Anything else?

Issue seems to be similar to https://github.com/cilium/cilium/issues/20125

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Can you provide installation steps as well as a sysdump?

**Comment by sandeepksingla123** [comment]
> Can you provide installation steps as well as a sysdump?

@aanm  attached sysdump

**Installation Steps:**
- Created new AKS cluster 1.25 version.
- Cilium 1.12 installed via helm chart
- cilium operator and deamon started
- core-dns pods failing with below error:
           [ERROR] plugin/errors: 2 1719163443584647392.8487499795824529487. HINFO: read udp 10.0.0.58:33144->168.63.129.16:53: i/o timeout
[ERROR] plugin/errors: 2 1719163443584647392.8487499795824529487. HINFO: read udp 10.0.0.58:37725->168.63.129.16:53: i/o timeout

-   Cilium status show error "cilium-health-ep 22h55m9s ago 4m10s ago 376 Get "http://10.0.0.56:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

[cilium-sysdump-20221119-184142.zip](https://github.com/cilium/cilium/files/10047750/cilium-sysdump-20221119-184142.zip)

**Comment by aanm** [comment]
Please provide more precise installation steps.

**Comment by sandeepksingla123** [comment]
Please refer below steps
1)  Create AKS cluster version 1.25.2 with bring your own cni
https://learn.microsoft.com/en-us/azure/aks/use-byo-cni?tabs=azure-cli#deploy-a-cluster

AKS host runs
OS-IMAGE :  Ubuntu 22.04.1 LTS
KERNEL-VERSION: 5.4.0-1094-azure

2) Install cilium CNI
helm repo add cilium https://helm.cilium.io/ -n cilium
helm install cilium cilium/cilium --namespace=cilium-f cilium_values_file.yml

Refer below cilium values file
[cilium_values_file.txt](https://github.com/cilium/cilium/files/10119449/cilium_values_file.txt)

3) Cilium operator & cilium deamon pods start successfully
4) core dns pods in  kube-system namespace failed with below error
"[ERROR] plugin/errors: 2 1719163443584647392.8487499795824529487. HINFO: read udp 10.0.0.58:33144->168.63.129.16:53: i/o timeout"
5) Cilium Status

KVStore:                Ok   Disabled
Kubernetes:             Ok   1.25 (v1.25.2) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumEndpointSlice", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [eth0 172.20.0.4]
Host firewall:          Disabled
CNI Chaining:           none
Cilium:                 Ok   1.12.2 (v1.12.2-c7516b9734)
NodeMonitor:            Disabled
Cilium health daemon:   Ok   
IPAM:                   IPv4: 7/254 allocated from 10.0.0.0/24, 
BandwidthManager:       EDT with BPF [CUBIC] [eth0]
Host Routing:           BPF
Masquerading:           BPF   [eth0]   10.0.0.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:      38/39 healthy
  Name               Last success    Last error   Count   Message
  **cilium-health-ep   44h43m43s ago   5m40s ago    537     Get "http://10.0.0.37:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)**   
Global Identity Range:   min 256, max 65535
Hubble:                  Disabled
Encryption:              Disabled
Cluster health:          1/1 reachable   (2022-11-30T04:29:45Z)

**Comment by msguit** [comment]
I have the same on my 3 node vagrant cluster.
OS nodes: Ubuntu 22.04.1 LTS
K8s ver: 1.25.5
Cilium ver: 1.10.5
Standard install and also my coredns pods are not running since.
Coredns log:
ERROR] plugin/errors: 2 987288461057245534.6110266123704021414. HINFO: read udp 10.0.0.190:59210->10.0.2.3:53: i/o timeout
Cilium status:
controller cilium-health-ep is failing since 27s (18x): Get "http://10.0.1.133:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers.
For the rest of the kube-system pods, all are running fine, except the coredns pods.
There is nothing special about the cluster, just default vagrant configuration and install. I tested the same setup on a Kind cluster and there it works.
I've been struggling for months about this and it gives me headaches ;).

**Comment by jspaleta** [comment]
I'm not able to reproduce the problem using aks kubernetes version 1.25.5 with the "azure" network plugin as required for AzureCNI (legacy mode) as described in the cilium.io docs.

I'm suspicious that the aks clusters observing the problem are using "kublet" aks network plugin (which may be the default network plugin that aks uses for k8s 1.25.5 now). The "kublet" network plugin is not documented as a supported configuration in the cilium documentation at this time for AzureCNI (legacy mode). 


A note for cilium developer, we may need to provide some breadcrumbs in the cilium.io docs to help people determine which aks network plugin they are using as a prereq.  Or if possible extend the cilium cli tool's aks discovery logic to abort install if kublet network plugin is found with a helpful note about supported plugin options.

Unfortunately the network plugin is an aks creation time only tunable, and I don't think you can change it with aks update. Clusters using the kublet network plugin will need to recreated using either network plugin "none" or "azure".

Here are my full install steps, that resulted in _no errors_.  Please, if you're impacted by this connectivity issue, please provide feedback on the specific aks creation differences for your impacted cluster.  This is most likely a subtle corner-case in aks configuration that we might be able to provide some documented guidance about.

1. Create aks cluster setting the k8s version and network plugin explicitly

```
$ az aks create --resource-group "${AZURE_RESOURCE_GROUP}" --name "${NAME}" --node-count 2 --node-vm-size Standard_B2s --node-osdisk-size 30 -k "1.25.5" --network-plugin="azure"
```

2. confirm the networkplugin is set to "azure"
```
$ az aks list -g ${AZURE_RESOURCE_GROUP} -o json |grep networkPlugin
      "networkPlugin": "azure",
      "networkPluginMode": null,
```
3. Confirm nodes are running Ubuntu 22.04
```
$ kubectl describe node aks-nodepool1-21255632-vmss000000
...
System Info:
  Machine ID:                 6a25f65b0b9e4faea3c1e45c8c4a7922
  System UUID:                06ca4eaf-2fee-4dd4-bcd0-fa5e4809758a
  Boot ID:                    a24e6e7c-421b-4412-bd75-e660a9ab3db7
  Kernel Version:             5.15.0-1033-azure
  OS Image:                   Ubuntu 22.04.1 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.6.15+azure-1
  Kubelet Version:            v1.25.5
  Kube-Proxy Version:         v1.25.5

```
3. install cilium using the cilium cli tool
```
$ cilium install --azure-resource-group ${AZURE_RESOURCE_GROUP}
🔮 Auto-detected Kubernetes kind: AKS
✨ Running "AKS" validation checks
✅ Detected az binary
ℹ️  Using Cilium version 1.12.5
🔮 Auto-detected cluster name: XXX
✅ Derived Azure subscription ID XXX
✅ Derived Azure AKS node resource group XXX
🔮 Auto-detected datapath mode: azure
🔮 Auto-detected kube-proxy has been installed
🚀 Creating Azure Service Principal for Cilium Azure operator...
✅ Created Azure Service Principal for Cilium Azure operator with App ID XXX
ℹ️  Its RBAC privileges are restricted to the AKS node resource group XXX
ℹ️  helm template --namespace kube-system cilium cilium/cilium --version 1.12.5 --set azure.clientID=XXX,azure.clientSecret=XXX,azure.enabled=true,azure.resourceGroup=XXX,azure.subscriptionID=XXX,azure.tenantID=XXX,bpf.masquerade=false,cluster.id=0,cluster.name=XXX,enableIPv4Masquerade=false,enableIPv6Masquerade=false,encryption.nodeEncryption=false,ipam.mode=azure,kubeProxyReplacement=disabled,nodeinit.enabled=true,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=disabled
ℹ️  Storing helm values file in kube-system/cilium-cli-helm-values Secret
🔑 Generated AKS secret cilium-azure
🔑 Created CA in secret cilium-ca
🔑 Generating certificates for Hubble...
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap for Cilium version 1.12.5...
🚀 Creating AKS Node Init DaemonSet...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed and ready...
♻️  Restarting unmanaged pods...
♻️  Restarted unmanaged pod kube-system/coredns-77f75ff65d-thr5l
♻️  Restarted unmanaged pod kube-system/coredns-autoscaler-58bfcf6b5-npz4h
♻️  Restarted unmanaged pod kube-system/konnectivity-agent-9c68df7cb-cmnjm
♻️  Restarted unmanaged pod kube-system/konnectivity-agent-9c68df7cb-xrbpn
♻️  Restarted unmanaged pod kube-system/metrics-server-56c547ff47-jlkvj
♻️  Restarted unmanaged pod kube-system/metrics-server-56c547ff47-twcs9
✅ Cilium was successfully installed! Run 'cilium status' to view installation health

```
4. run connectivity tests
```
$ cilium connectivity test
ℹ️  Monitor aggregation detected, will skip some flow validation steps
...
ℹ️  Cilium version: 1.12.5
🏃 Running tests...
[=] Test [no-policies]
................................
[=] Test [allow-all-except-world]
..............
[=] Test [client-ingress]
..
[=] Test [all-ingress-deny]
........
[=] Test [all-egress-deny]
................
[=] Test [all-entities-deny]
........
[=] Test [cluster-entity]
..
[=] Test [host-entity]
....
[=] Test [echo-ingress]
....
[=] Test [client-ingress-icmp]
..
[=] Test [client-egress]
....
[=] Test [client-egress-expression]
....
[=] Test [client-egress-to-echo-service-account]
....
[=] Test [to-entities-world]
......
[=] Test [to-cidr-1111]
....
[=] Test [echo-ingress-from-other-client-deny]
......
[=] Test [client-ingress-from-other-client-icmp-deny]
......
[=] Test [client-egress-to-echo-deny]
......
[=] Test [client-ingress-to-echo-named-port-deny]
....
[=] Test [client-egress-to-echo-expression-deny]
....
[=] Test [client-egress-to-echo-service-account-deny]
....
[=] Test [client-egress-to-cidr-deny]
....
[=] Test [client-egress-to-cidr-deny-default]
....
[=] Test [health]
..
[=] Test [echo-ingress-l7]
............
[=] Test [echo-ingress-l7-named-port]
............
[=] Test [client-egress-l7-method]
............
[=] Test [client-egress-l7]
..........
[=] Test [client-egress-l7-named-port]
..........
[=] Test [dns-only]
..........
[=] Test [to-fqdns]
........

✅ All 31 tests (228 actions) successful, 0 tests skipped, 1 scenarios skipped.

```

5. run external curl operations from deployments
```
$ kubectl create deployment hello-node --image=registry.k8s.io/e2e-test-images/agnhost:2.39 -- /agnhost netexec --http-port=8080
$ kubectl exec -ti hello-node-67949d9db-vh9dr -- curl -I http://www.example.com

HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 405972
Cache-Control: max-age=604800
Content-Type: text/html; charset=UTF-8
Date: Tue, 07 Mar 2023 20:48:11 GMT
Etag: "3147526947"
Expires: Tue, 14 Mar 2023 20:48:11 GMT
Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
Server: ECS (sab/56BC)
X-Cache: HIT
Content-Length: 1256

```

6. Check for errors in CoreDNS logs
```
$ kubectl logs coredns-77f75ff65d-2tw45 -n kube-system --all-containers=true |grep ERROR
(no output)

$ kubectl logs coredns-77f75ff65d-w7h2h -n kube-system --all-containers=true |grep ERROR
(no output)
```

7. Uninstall cilium 1.12.5 and install cilium 1.13.0 and repeat steps 4 - 6, with same result

**Comment by splattner** [comment]
Our cluster is set to `azure` networkPlugin and not `kubernet`.
One cluster with k8s 1.24.3 and OS AKSUbuntu-1804gen2containerd-2022.09.22 with Cilium 1.12.5 which works
The other k8s 1.25.5 with OS AKSUbuntu-2204gen2containerd-2023.02.09 with Cilium 1.12.5 where it doesn't work. 
Setup is the same for both, automated with terraform

**Comment by splattner** [comment]
there is a `konnectivity-agent` Kubernetes Network Policy in the `kube-system` which blocked the traffic. But the strange this is, on our cluster with the older version, we have the name Network Policy in place and no problem there.....

**Comment by splattner** [comment]
and networkpolicy from azure was also enabled.. which gave some strange behaviour. Recreated the cluster, with azurecni network plugin, network policy to none and then cilium on top. This works now for me

**Comment by gioppoluca** [comment]
We have a similar DNS problem in a VMWare on premise cluster with UBUNTI 22.04 using rancher.
Core DNS and in general connectivity between endpoints is not working the cilium status read "endpoints unreachable".
Seems specific from ubuntu 22.04 from also slack posts

**Comment by youngnick** [comment]
I'd encourage anyone seeing something similar to these symptoms to gather a sysdump and post it in here. Instructions are at https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection.

It does seem like there's at least something we may need to make more clear in the documentation for Ubuntu 22.04.

Marking this for the attention of sig/agent for now.

**Comment by gioppoluca** [comment]
Here is the dump of our env as for @youngnick  advice
[cilium-sysdump-20230522-103404.zip](https://github.com/cilium/cilium/files/11530505/cilium-sysdump-20230522-103404.zip)

**Comment by gioppoluca** [comment]
The same configuration used in 20.04 works with no problem.

**Comment by wzrdtales** [comment]
we reevaluate our no cilium policy, but unfortunately hit on this as well.

Environment:
VM with ubuntu 22.04
cluster via rancher rke2
no pods can make connections to any pod

cilium status

```
ilium status
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.23 (v1.23.7+rke2r2) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled   
Host firewall:          Disabled
Cilium:                 Ok   1.11.5 (v1.11.5-b0d3140)
NodeMonitor:            Disabled
Cilium health daemon:   Ok   
IPAM:                   IPv4: 3/254 allocated from 10.42.7.0/24, 
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      22/23 healthy
  Name               Last success   Last error   Count   Message
  cilium-health-ep   12m58s ago     5s ago       18      Get "http://10.42.7.228:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)   
Proxy Status:     OK, ip 10.42.7.35, 0 redirects active on ports 10000-20000
Hubble:           Disabled
Encryption:       Disabled
Cluster health:   8/8 reachable   (2023-07-10T11:11:26Z)
```


It says 10.42.7.228 can't be reached, which would be on the same host. So not even traffic on the same host passes to other machines. Installing a VM on ubuntu 20.04 same cluster works.

**Comment by wzrdtales** [comment]
pretty much same situation as @gioppoluca , with this cilium remains in the unsafe state and is banned for all our customers unfortunately.

**Comment by gioppoluca** [comment]
@wzrdtales are you on VMware?

**Comment by wzrdtales** [comment]
no, its a kvm virtualization

**Comment by wzrdtales** [comment]
ironically, the node can ping services on the other nodes which run ubuntu 20.04, but it can't ping any of its own and also all others can't reach any on the ubuntu 22.04 nodes

**Comment by tzssangglass** [comment]
for Ubuntu 22.04, maybe useful to fix this: [systemd-based-distributions](https://docs.cilium.io/en/stable/operations/system_requirements/#systemd-based-distributions)

**Comment by wzrdtales** [comment]
@tzssangglass we tried not helping at all unfortunately, whatever is already suggested was tested

**Comment by tzssangglass** [comment]
> @tzssangglass we tried not helping at all unfortunately, whatever is already suggested was tested

I am also troubled by this issue 😅

**Comment by tzssangglass** [comment]
I know how to reproduce this issue using the vagrant box provided by Cilium:

```bash
# download box
cd /tmp
wget https://app.vagrantup.com/cilium/boxes/ubuntu-5-4/versions/138/providers/virtualbox.box

# add box
vagrant box add cilium/ubuntu-5-4 /tmp/virtualbox.box

# run box
SERVER_BOX=cilium/ubuntu-5-4 SERVER_VERSION=0 IPV4=1 VM_MEMORY=8192 VM_CPUS=4 NO_BUILD=1 contrib/vagrant/start.sh
```

**Comment by wzrdtales** [comment]
bot no

**Comment by brainplot** [comment]
Is there any update on this? We can't move our Kubernetes clusters from 20.04 to Ubuntu 22.04 (or even 24.04) because we're blocked by this.
