### ISSUE TITLE
toEntities/fromEntities CRD description missing some options

### ISSUE THREAD

**Issue by chancez** [cilium/cilium#22235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

CRDs are missing all the possible options listed in the docs: https://docs.cilium.io/en/stable/policy/language/#entities-based
```
(⎈|kind-kind:default) ~/p/w/hubble-timescape ❯❯❯ k explain ciliumnetworkpolicy.spec.egress.toEntities                                                                               pr/chancez/network_policies ✭ ✚ ✱
KIND:     CiliumNetworkPolicy
VERSION:  cilium.io/v2

FIELD:    toEntities <[]string>

DESCRIPTION:
     ToEntities is a list of special entities to which the endpoint subject to
     the rule is allowed to initiate connections. Supported entities are
     `world`, `cluster` and `host`

     Entity specifies the class of receiver/sender endpoints that do not have
     individual identities. Entities are used to describe "outside of cluster",
     "host", etc.

(⎈|kind-kind:default) ~/p/w/hubble-timescape ❯❯❯ k explain ciliumnetworkpolicy.spec.ingress.fromEntities                                                                      ✘ 130 pr/chancez/network_policies ✭ ✚ ✱
KIND:     CiliumNetworkPolicy
VERSION:  cilium.io/v2

FIELD:    fromEntities <[]string>

DESCRIPTION:
     FromEntities is a list of special entities which the endpoint subject to
     the rule is allowed to receive connections from. Supported entities are
     `world`, `cluster` and `host`

     Entity specifies the class of receiver/sender endpoints that do not have
     individual identities. Entities are used to describe "outside of cluster",
     "host", etc.
```

### Cilium Version

v1.12.2

### Kernel Version

Linux lima-docker 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 12:56:31 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:38:29Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by slayer321** [comment]
@pchaigno  can you assign this issue to me
