### ISSUE TITLE
Avoid serializing ELFs to the filesystem as part of BPF load

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#22245]
Currently, the compilation process for eBPF programs for endpoints is to first invoke the compiler to create an ELF representing the datapath code onto the filesystem, then use pkg/elf to create a templated copy with the individual endpoint's data inside, then load this ELF into the kernel.

Now that we are moving more and more code over to cilium/ebpf for loading the datapath, we could avoid creating the ELFs on the filesystem altogether.

**Comment by ti-mo** [comment]
Finalized in https://github.com/cilium/cilium/pull/32962.
