### ISSUE TITLE
Deprecate MetalLB support

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#22246]
Recent BGP development in Cilium has focused around the new native BGP control plane support (https://github.com/cilium/cilium/pull/18860). When this approaches feature parity with Metal LB, we should mark the MetalLB support as deprecated. We can remove the functionality in the following release.

**Comment by joestringer** [comment]
I suggest that since we're planning on this path, we should deprecate this in 1.13 even if we don't plan on immediately removing it in 1.14. Ideally there should be a big warning message on startup if the user is using MetalLB, which points the users to the issues pages here so that they can share which MetalLB features they're using. This way we can try to avoid removing features that users are relying on, and instead provide a cleaner transition.

It'll probably help to have a list of which features we're aware of somewhere, (a) features that have parity with the native control plane, (b) features we plan to address (+ links to those issues), (c) features we know we don't support. Then users of the in-built MetalLB features can post on that page to track all of the capabilities.

**Comment by sathieu** [comment]
@joestringer Does the current implemtation works with ARP too? Or should I use upstream MetalLB for this?

**Comment by AidanGG** [comment]
I think advertising the loadbalancer IP over BGP (necessary: https://github.com/cilium/cilium/pull/21764) and annotating services to request specific IPs (https://github.com/cilium/cilium/issues/21776) are MetalLB features that are missing from the current control plane implementation.

**Comment by joestringer** [comment]
@cilium/sig-datapath can you look into the question from @sathieu above?

**Comment by dylandreimerink** [comment]
@AidanGG #21776 is about multiple services sharing the same IP. Requesting specific IPs will be possible with #21764. I would venture a guess that the amount of users that actually have a need to share service IPs is low. So I would say to deprecate the MetalLB integration even without this feature in place. Please correct me if I am wrong.

**Comment by dylandreimerink** [comment]
> Does the current implemtation works with ARP too? Or should I use upstream MetalLB for this?

@sathieu MetalLB is exclusively used for BGP announcements and the BGP Control Plane which succeeds it also doesn't use ARP. So at the moment the only option is to deploy MetalLB alongside Cillium.

**Comment by sathieu** [comment]
Thanks for the info @dylandreimerink.

**Comment by AidanGG** [comment]
Without MetalLB's FRR, I believe we don't have support from GoBGP (https://github.com/osrg/gobgp/issues/2563) to enable BFD with the control plane implementation.

**Comment by dylandreimerink** [comment]
> Without MetalLB's FRR, I believe we don't have support from GoBGP ([osrg/gobgp#2563](https://github.com/osrg/gobgp/issues/2563)) to enable BFD with the control plane implementation.

No, the new control plane will not have BFD support. But our current BGP (beta) feature also doesn't offer this since the MetalLB integration doesn't run in FRR mode.

I would encourage you to make a feature request for BFD support in BGP Control Plane. Perhaps someone in the community can contribute it to GoBGP so Cilium can start using it as well.

**Comment by AidanGG** [comment]
Right, I had a mental slip since I was thinking about bringing cilium to feature parity with upstream MetalLB rather than the MetalLB integration.

**Comment by mazzy89** [comment]
I have a question related to the topic. I've deployed cilium 1.12.4 with load balancer enabled and BGP publish of load balancer IP. The Service, automatically created by Cilium, get correctly the IP address and it's advertised properly. The Ingress does not report any IP in the status and I do not have any connectivity at the level of the Ingress. Now reading this diecussion seems that what I'm trying to achieve is not supported yet. Did I get it correctly?

**Comment by dylandreimerink** [comment]
@AidanGG I looked into BFD some more (your comment sparked interest), I created an [issue](https://github.com/cilium/cilium/issues/22394) to add support for it to Cilium (separate from MetalLB deprecation). In case you have any thoughts on the subject.

**Comment by Jean-Daniel** [comment]
I can't find If GoBGP support MPBGP. Would Cilium be able to advertise Dual Stack service using a single BGP session and MPBGP ?

**Comment by karelvanhecke** [comment]
As far as I can tell #22397 doesn't include support for externaltrafficpolicy. This should also be considered before deprecating metallb.

A bonus would be out of the box support for the following label:  https://kubernetes.io/docs/reference/labels-annotations-taints/#node-kubernetes-io-exclude-from-external-load-balancer
This would exclude control plane nodes from advertising load balancer IP's by default. Though this behaviour can be achieved using the nodeSelector field in CiliumBgpPeeringPolicies.

**Comment by dylandreimerink** [comment]
> As far as I can tell https://github.com/cilium/cilium/pull/22397 doesn't include support for externaltrafficpolicy. This should also be considered before deprecating metallb.

`ExternalTrafficPolicy: Local` support is definitely something we should add. I am not sure if missing the feature should block us from deprecating MetalLB at this point, given that deprecation is nothing more than an official announcement, requesting users to not use MetalLB and start switching. Users whom rely on `ExternalTrafficPolicy: Local` support have to wait for a bit. I feel that the earlier we get this processes started the better.

I believe the actual removal of MetalLB as is can easily be postponed until full feature parity has been reached. But it should also be clear that we will not be allocating resources towards upgrading of the MetalLB implementation (bugs and security issues will of course still receive support).

> A bonus would be out of the box support for the following label: https://kubernetes.io/docs/reference/labels-annotations-taints/#node-kubernetes-io-exclude-from-external-load-balancer
This would exclude control plane nodes from advertising load balancer IP's by default. Though this behaviour can be achieved using the nodeSelector field in CiliumBgpPeeringPolicies.

I think this is an interesting request which deserves its own issue. I think it might require some discussion on what the effect of such a label should be given that BGP + Service load balancing doesn't fit the usual external load balancer model exactly.

**Comment by camrossi** [comment]
@dylandreimerink is there a plan to open an issue for `ExternalTrafficPolicy: Local` support? I would like to know once this comes in. Putting together a design guide for Cilium integration with Cisco ACI (SDN Fabric) and would like to know once this is implemented so I can update the document. Otherwise I know I will forget 😅

**Comment by dylandreimerink** [comment]
@camrossi I have just created an issue to properly track this #23035

**Comment by joestringer** [comment]
I see an update from the [January 4th community meeting](https://docs.google.com/document/d/1Y_4chDk4rznD6UgXPlPvn3Dc7l-ZutGajUv1eF0VDwQ/edit#bookmark=id.5aise1agwer0) where the consensus appeared to be that when users use MetalLB in v1.13, we should let them know that the new BGP method is available but not yet mark as deprecated. Then we would hope to deprecate in v1.14 and remove MetalLB support in v1.15. That seems like a reasonable proposal moving forward.
