### ISSUE TITLE
Cilium should remove stale CNP node statuses from CNP resources if `--disable-cnp-status-updates` is true

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#22277]
It's possible for a user to have _disabled_ `--disable-cnp-status-updates` (meaning they _enabled_ the CNP node status) and then later _enabled_ it (meaning _disabled_ the CNP node status). This results in stale CNP node statuses inside CNP resources which could waste resources / bandwidth transmitting the status subresource to K8s, as the CNP resources are updated over time. This is not a crucial bug, but rather a minor enhancement. 

CNP node statuses are not used for any funtional purposes, but rather for providing information to the user.

One approach would be to kick off a one-time controller in the Operator to go through all the CNP resources once the K8s watcher for CNPs has fully synced and remove the node statuses entirely when `--disable-cnp-status-updates` is true.

**Comment by aanm** [comment]
Duplicate of https://github.com/cilium/cilium/issues/20231
