### ISSUE TITLE
Help: DSR with kube-vip and BGP doesnt route across nodes

### ISSUE THREAD

**Issue by kuja53** [cilium/cilium#22323]
Hello,

I have very weird issue which is little bit unique:

We are using cillium v1.12.2 with kube-proxy replacement in strict mode, we enable DSR and BPF masquerading. And our goal is to preserve `sourceIP` which, based on documentation, should work out-of-the box in this kind of configuration. But unfortunately, when I keep `externalTrafficPolicy` in `Cluster` mode it doesnt preserve `sourceIP` but keep ip of worker node which handle the request. It makes sense from my understanding the network layer but its completely against your documentation. When I configure `externalTrafficPolicy` to `Local` I could preserver `sourceIP` but when the request goes to node which doesnt has ingress-controler pod. It got `Connection refused`. This is caused due to BGP IP announcement via kube-vip. But I could assume that cilium virtual interface could forward this request to the right node via BPF layer. Same as I saw when I use IPVS in the past days when I used MetalLB in BGP mode. I also try integrated MetalLB for handling BGP and it also not work as is define in documentation. To be honest I try everything what comes to my mind.

Kubernetes version: v1.22.12 vanilla - provisioned by ClusterAPI
OS version: Ubuntu 20.04.5 with kernel 5.15.x
Cilium version: v1.12.2
nginx-ingress version: v1.2.1
kube-vip version: v0.5.0

cilium-config:
````
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: "true"
  bpf-lb-external-clusterip: "true"
  bpf-lb-map-max: "65536"
  bpf-lb-mode: dsr
  bpf-lb-sock: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: default
  cluster-pool-ipv4-cidr: 10.0.0.0/8
  cluster-pool-ipv4-mask-size: "24"
  custom-cni-conf: "false"
  debug: "false"
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-bpf-tproxy: "false"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-legacy-routing: "false"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "false"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "true"
  hubble-listen-address: :4244
  hubble-metrics: dns drop tcp flow icmp http
  hubble-metrics-server: :9965
  hubble-socket-path: /var/run/cilium/hubble.sock
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: cluster-pool
  ipv4-native-routing-cidr: 172.171.170.0/24
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: 0.0.0.0:10256
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  prometheus-serve-addr: :9962
  proxy-prometheus-port: "9964"
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: disabled
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
````

**Comment by julianwiedmann** [comment]
> But unfortunately, when I keep `externalTrafficPolicy` in `Cluster` mode it doesnt preserve `sourceIP` but keep ip of worker node which handle the request.

Just to clarify - at the client, you're seeing **replies** from a remote Service backend that have `.daddr = ClientIP` and `.saddr = backendIP` (rather than `.saddr = SvcIP`) ?

**Comment by kuja53** [comment]
At the client side I see on both ways externalIP of worker node which has current master of ingress-controler. I see the ClusterIP only on cilium veth. Which is kinda weird.

**Comment by kuja53** [comment]
So this issue - in my case - was connected to enable leader election on SVC-only LB in kube-vip configuratio and to use their latest release with iptables integrated to kube-vip image to better handle egress traffic.
