### ISSUE TITLE
Combining Hubble and Policy Editor In One Application

### ISSUE THREAD

**Issue by Daxcor69** [cilium/cilium#22338]
## Cilium Feature Proposal
  
**Is your feature request related to a problem?**

Figuring out what is being blocked/allowed by network policy in real time when you make changes is really hard to see.

**Describe the feature you'd like**

Drag and drop network policy editor/creator based and  REAL cluster objects as found by hubble in the live cluster.

**(Optional) Describe your proposed solution** 

- Take your policy editor and have it apart of the hubble application so it resides on the cluster itself.  
- have the editor discover all your pods in the cluster in all the name spaces.
- have the discovered objects so that you can drag and drop them into place, like on the ingress or egress side.
- have it also look at the services for port numbers and have them available as options on that particular pod.  This would further tighten the rules for that pod.
- when a policy is changed make sure that all flows are broken so that the changes are immediately applied
- show in the editor view the flows that are being acted upon by a particular rule. Have the flow list attached to the policy.
- have default policies that can easily be applied to a name spaces
- have a default policy that represents the Internet that can be dragged in as needed.
```
      - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 192.168.0.0/16
```

**Comment by Daxcor69** [comment]
Another Feature for this app:

- have flows showing in real time entering and leaving the namespace context.  A graphical representation of the Hubble text data that streams by on the lower portion of the screen.
- be able to right click on a flow and immediately apply a block.. think of an instant deny on a suspicious flow.
-

**Comment by kaworu** [comment]
Hi @Daxcor69 and thank you for opening this issue.

The Network Policy Editor at https://app.networkpolicy.io is not OSS for now and thus not integrated into the OSS version of Hubble UI. There is a version of Hubble UI with Network Policy integrated in the [Isovalent Cilium Enterprise offering](https://isovalent.com/product/).
