### ISSUE TITLE
CI: client-egress-to-echo-expression-deny (ConformanceAKS)

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#22367]
## CI failure: client-egress-to-echo-expression-deny (ConformanceAKS)

Link: https://github.com/cilium/cilium/actions/runs/3548488854/jobs/5959757792#step:16:2355

The full log didn't fit in the issue, it is attached as a TXT: [full-log.txt](https://github.com/cilium/cilium/files/10094154/full-log.txt)

I thin the final line is the most significant:
```
[2022-11-25T14:07:49Z]   🟥 Running test client-egress-to-echo-expression-deny: setting up test: applying network policies: policies were not applied on all Cilium nodes in time: error dialing backend: read unix @->/tunnel-uds/proxysocket: read: connection reset by peer
```

There doesn't seem to be a sysdump available:
```
Warning: No files were found with the provided path: cilium-sysdump-*.zip. No artifacts will be uploaded.
```

**Comment by pchaigno** [comment]
cc @jibi regarding the missing sysdump error.

**Comment by jibi** [comment]
> setting up test: applying network policies: policies were not applied on all Cilium nodes in time: error dialing backend: read unix @->/tunnel-uds/proxysocket: read: connection reset by peer

I think it's kind of expected as this wasn't the test failing but rather the setup of the test itself.
We probably just need to add the sysdump collection logic also [here](https://github.com/cilium/cilium-cli/blob/master/connectivity/check/context.go#L306), I'll have a look

**Comment by jibi** [comment]
This handle the case https://github.com/cilium/cilium-cli/pull/1233/files
