### ISSUE TITLE
How does node-local-dns work in dual-stack ipv4 and ipv6 mode?

### ISSUE THREAD

**Issue by mpv945** [cilium/cilium#22378]
Want to enable ipv6 dual stack to speed up dns resolution, how to correctly configure ipv6 local dns resolution?

**Comment by christarazi** [comment]
Hello. Consider asking for help on Cilium Slack at cilium.slack.com.

**Comment by joestringer** [comment]
One thing at least we can highlight is that turning IPv6 support on in Cilium should be as simple as setting `ipv6.enabled` to true in your helm settings. the `ipv6NativeRoutingCIDR` option may also be relevant if not using tunneling in that environment. See https://github.com/cilium/cilium/tree/master/install/kubernetes/cilium for more details.

Regarding IPv6 local DNS resolution, there is probably some overlap with https://docs.cilium.io/en/v1.12/gettingstarted/local-redirect-policy/#node-local-dns-cache . I do not know if there are any specific IPv6 steps that you need, but if you find some out then please consider posting your findings in this issue, and/or submit a PR to extend those docs (https://github.com/cilium/cilium/blob/master/Documentation/network/kubernetes/local-redirect-policy.rst).

**Comment by aditighag** [comment]
>Regarding IPv6 local DNS resolution, there is probably some overlap with https://docs.cilium.io/en/v1.12/gettingstarted/local-redirect-policy/#node-local-dns-cache .

The same instructions should work for IPv6 as well. Let us know if there are any gaps. You can also post on the Cilium public slack channel #kubernetes.
