### ISSUE TITLE
Enable cilium_bpf_map_pressure metric by default

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#22401]
Several users have reported that bpf_map_pressure is not exported by default in the metrics, but it would be very useful to be able to debug issues in their cluster.

**Comment by Vishal-Chdhry** [comment]
what I can understand that I have to 
1. Add `Namespace + "_" + SubsystemBPF + "_map_pressure"` in https://github.com/cilium/cilium/blob/a75e24b558703a4f66337ad28849c6a79240166f/pkg/metrics/metrics.go#L605
2. Impliment this https://github.com/cilium/cilium/blob/a75e24b558703a4f66337ad28849c6a79240166f/pkg/metrics/metrics.go#L1287

**Comment by joestringer** [comment]
:+1: I think it's just (1) + any potential documentation updates to the metrics page. (2) is defining the metric, which should already be correct.

**Comment by Vishal-Chdhry** [comment]
\assign
