### ISSUE TITLE
Add Cluster Debug tool intro & instructions to the Troubleshooting Guide

### ISSUE THREAD

**Issue by techcet** [cilium/cilium#2242]
### Title

Add Cluster Debug Tool Intro & Instructions to the Troubleshooting Guide

### Description of requested functionality

End-User Cluster debugging tool exists for easier troubleshooting. Introduce in the Troubleshooting Guide.

**Comment by aanm** [comment]
Done

**Comment by Kikiodazie** [comment]
> Done

Hey @aanm, 

Just checking on all the old issues that can be closed. 

Seeing you said "Done", can this be closed?

I hope this meets you well. Cheers

**Comment by aanm** [comment]
oh yeah this should have been closed. Thanks for checking!
