### ISSUE TITLE
CFP: Support per-interface NodePort SNAT IP

### ISSUE THREAD

**Issue by akhilles** [cilium/cilium#22429]
**Is your feature request related to a problem?**

The same IP (`IPV4_DIRECT_ROUTING`) is used for SNAT-ing NodePort traffic to remote backends on all host interfaces. This is problematic because the IP may not be assigned to the interface that the packet leaves. https://github.com/cilium/cilium/pull/18585 added multihoming support, but still requires all interfaces that forward service traffic to share the same IP.

**Describe the feature you'd like**

Allow for a different NodePort SNAT IP to be defined for each host interface, similar to `IPV4_MASQUERADE`.

**(Optional) Describe your proposed solution**

Generate a `NODEPORT_SNAT_IPV4_BY_IFINDEX(ifindex)` macro which chooses an IP address that's assigned to each interface (overriden by `--direct-routing-device`). In `tail_nodeport_nat_ipv4`, choose the SNAT IP using this macro + `ifindex` returned from `fib_lookup`.

Eventually, maybe `fib_lookup` would return the source IP (https://github.com/cilium/cilium/issues/17158), but this seems like an improvement over the current situation.

**Comment by brb** [comment]
@akhilles Thanks for the issue. #17158 should completely resolve it, but it will take awhile until it lands into mainstream kernels. 

> Allow for a different NodePort SNAT IP to be defined for each host interface, similar to IPV4_MASQUERADE.

I think this approach won't work. https://github.com/cilium/cilium/pull/18585 changed the FIB lookup direction from egress to ingress. This means that the NodePort SNAT IP would be of a device which received a request, but not of a device which will forward it. The following approach would work though:

> Generate a NODEPORT_SNAT_IPV4_BY_IFINDEX(ifindex)

Just keep in mind, that the macro would need to be regenerated (and all bpf_host instances reloaded) each time we add a new device during the runtime.

**Comment by akhilles** [comment]
> Just keep in mind, that the macro would need to be regenerated (and all bpf_host instances reloaded) each time we add a new device during the runtime.

Could this be delegated to the runtime device detection experimental feature? I believe it's already doing this for the `IS_L3_DEV(ifindex)` and `NATIVE_DEV_MAC_BY_IFINDEX(ifindex)` macros which are used in bpf_host.

I can submit a PR with this approach, I have it working locally. 

On a related note: I'm wondering if a BPF map would make sense here, instead of these macros. Maybe an array map with ifindex as key and {mac, is_l3, nodeport_ip, masq_ip} as value. Is the motivation for using macros just performance-related or something else?
