### ISSUE TITLE
Improve visibility into conntrack garbage collection

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#22434]
It is currently difficult to understand when, and how often, conntrack garbage collection occurs. This issue tracks improving metrics / logging / observability into these events.

One proposal would be to refactor the code into a `pkg/controller` instead of an open-coded goroutine, so that the `cilium status` output reveals the last time it ran + success. I think that the primary blocker from this until now is that the conntrack garbage collection interval is dynamically recalculated, but `pkg/controller` by default is quite opinionated about run intervals. If we solve this problem with `pkg/controller`, we probably just need to figure out a good way to make this controller retain the current dynamic interval behaviour implemented in the CT GC code today.

**Comment by aanm** [comment]
@joestringer are you aware of https://github.com/cilium/cilium/pull/21235? Could help a little bit

**Comment by joestringer** [comment]
@aanm I wasn't, thanks for sharing! However it looks like that PR doesn't cover conntrack maps today.
