### ISSUE TITLE
Proposal: limit resources when building Docker image in dev VMs

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2244]
I've kept encountering kernel panics / freezes locally on my Mac when trying to run the Kubernetes tests locally. Most often the failures occur when building the Docker image for use during the tests. I wonder if this is because we are hammering the resources (CPU, memory, etc.) in the VMs which is putting too much load on VirtualBox, and thus causing crashes. One thing we can do is to limit the amount of resources the build can consume, which is possible via the documentation for `docker build` : https://docs.docker.com/engine/reference/commandline/build/#options . Specifically:

* `--memory`
* one of the CPU-related flags (not entirely sure myself what these mean)

I can try testing this locally to see if it improves the stability of my setup, because I can't run the tests locally without crashing my computer more than 50 % of the time.

**Comment by eloycoto** [comment]
@ianvernon did you test something related with this? Yesterday @aanm and myself had a similar problem

**Comment by ianvernon** [comment]
i had a branch a while back, but never got around to doing anything with it. This is the only diff in the branch:

```
Ians-MacBook-Pro:test ianvernon$ git diff b1e851af0099c26569d1bbd3c47088d25424641c^ b1e851af0099c26569d1bbd3c47088d25424641c
diff --git a/contrib/packaging/docker/Makefile b/contrib/packaging/docker/Makefile
index 55f58a994..6b859bd61 100644
--- a/contrib/packaging/docker/Makefile
+++ b/contrib/packaging/docker/Makefile
@@ -14,7 +14,7 @@ docker-image-dev: clean
        @$(CURDIR)/../cp-dirs.sh $(BUILDDIR)
        cp -v ../../../Dockerfile.dev $(BUILDDIR)/Dockerfile
        find $(BUILDDIR) -name ".*" -prune ! -name ".git" -exec $(RM) -rf {} \;
-       docker build -q -t "cilium:$(DOCKER_IMAGE_TAG)" $(BUILDDIR)
+       docker build -q --memory=1GB -c 2 -t "cilium:$(DOCKER_IMAGE_TAG)" $(BUILDDIR)
 
 docker-image-dependencies: clean
        mkdir -p $(BUILDDIR)
```

I think that the Dockerfiles in my branch are gone as a result of the multistage build being in place, but you could try building with `--memory=<X GB>` and `-c <Y>` where X is the number of GB of RAM and Y is the # of CPUs.

**Comment by eloycoto** [comment]
I think that this can be closed now, we're not using bazel that was the main pain point here and this issue is no longer relevant.
