### ISSUE TITLE
cilium-etcd-operator -  Docker images with manifest v2 schema 1 to this repository is blocked.

### ISSUE THREAD

**Issue by darkstarmv** [cilium/cilium#22493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I try to pull cilium-etcd-operator via our company internal quay artifactory mirror, I'm getting this error:
``` 
docker pull quay-mirror.company.com/cilium/cilium-etcd-operator:v2.0.7@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc
Error response from daemon: unauthorized: Pulling Docker images with manifest v2 schema 1 to this repository is blocked. For more information visit https://www.jfrog.com/confluence/display/RTF/Advanced+Topics#AdvancedTopics-DockerManifestV2Schema1Deprecation
```

According to docker documentation https://docs.docker.com/registry/spec/deprecated-schema-v1/  schema 1 has been deprecated and has to be updated to schema 2:

>With the release of image manifest version 2, schema 2, image manifest version 2, schema 1 has been deprecated. This could lead to compatibility and vulnerability issues in images that haven’t been updated to image manifest version 2, schema 2.
 

### Cilium Version

v1.12.4

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
cc @aanm

**Comment by aanm** [comment]
@darkstarmv cilium-etcd-operator is deprecated and no longer maintained.

**Comment by darkstarmv** [comment]
Thank you @aanm - may be having a deprecation note in the helm values file or README or anywhere in documentation  would help to avoid confusion.
