### ISSUE TITLE
Failed to watch *v2alpha1.CiliumLoadBalancerIPPool: failed to list *v2alpha1.CiliumLoadBalancerIPPool

### ISSUE THREAD

**Issue by ichasco-heytrade** [cilium/cilium#22516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am having error when deploying cilium-operator
```
level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/resource/resource.go:183: Failed to watch *v2alpha1.CiliumLoadBalancerIPPool: failed to list *v2alpha1.CiliumLoadBalancerIPPool: ciliumloadbalancerippools.cilium.io is forbidden: User \"system:serviceaccount:cilium:cilium-operator\" cannot list resource \"ciliumloadbalancerippools\" in API group \"cilium.io\" at the cluster scope" subsys=k8s
```

### Cilium Version

v1.12.4

### Kernel Version

5.15.59

### Kubernetes Version

v1.24.7-eks-fb459a0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hello @ichasco-heytrade, *v2alpha1.CiliumLoadBalancerIPPool is only available in Cilium >= 1.13.0-rc3. That's why it fails in 1.12.4

**Comment by ichasco-heytrade** [comment]
The problem is that in the chart is defined `latest` version. And if I comment it adds `v1.12.4` that fails because the correct tag need to be `v1.12` beacause in qualys doesn't exist the other one:

```
Failed to pull image "quay.io/cilium/operator-generic-ci:v1.12.4": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/cilium/operator-generic-ci:v1.12.4": failed to resolve reference "quay.io/cilium/operator-generic-ci:v1.12.4": quay.io/cilium/operator-generic-ci:v1.12.4: not found
```

Is there any way to not hardcode the tag version in the Chart?

Thanks!

**Comment by ichasco-heytrade** [comment]
I have fixed using the dockerhub images instead of the qualys. Thanks!

**Comment by ichasco-heytrade** [comment]
I am installing it with HELM
```
dependencies:
  - name: cilium
    version: 1.12.4
    repository: https://helm.cilium.io/
```
