### ISSUE TITLE
cleanup workaround in CI for reinstall

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#22517]
PR #22163 breaks reinstall, and temporarily works around the issue in CI. But the real fix is in cilium-cli.

So, once https://github.com/cilium/cilium-cli/issues/1257 is fixed, we should remove the CI workaround.

**Comment by joestringer** [comment]
@squeed This is marked as a release-blocker. Is there further work to achieve this issue?

**Comment by squeed** [comment]
Ehh, I was being overly strict. Not a release-blocker, but I'll get this fix in soon.
