### ISSUE TITLE
Recent macOS versions do not support host-only adapters.

### ISSUE THREAD

**Issue by markarranz** [cilium/cilium#22511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When following the Development Setup guide, I ran into an issue attempting to follow [Option 1 - Using the Provided Vagrantfiles (Recommended)](https://docs.cilium.io/en/stable/contributing/development/dev_setup/#option-1-using-the-provided-vagrantfiles-recommended).

When I ran:
```bash
contrib/vagrant/start.sh
```
 I was prompted to create a VBox host-only network interface, which I accepted.

Instead of installing the VBox host-only network interface, I received an error stating that VBoxManage failed to create the host-only adapter.

### Cilium Version

cilium-cli: v0.12.11 compiled with go1.19.3 on darwin/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.4
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"

### Kernel Version

Darwin MarkBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
WARN: VirtualBox interface with "FD00::" not found
Create a new VBox hostonly network interface? [y/N] y
Creating VBox hostonly network...
0%...NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 105 of file VBoxManageHostonly.cpp
Unable create VBox hostonly interface:
```

### Anything else?

I was able to find [documentation on VirtualBox's website](https://www.virtualbox.org/manual/ch06.html#network_hostonly) stating, "Hosts running recent macOS versions do not support host-only adapters" and that macOS hosts should use the **Host-Only Networks**.

Does it make sense to add an if-else statement to check if the user is running macOS in the `contrib/vagrant/start.sh` script and adjust configuration accordingly?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by middaywords** [comment]
I downgraded the virtual box to version 6.x and this error is gone then.
