### ISSUE TITLE
bpf_lxc's CT programs are missing drop notifications

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#22527]
The BPF programs used for the CT lookups in bpf_lxc (e.g., :point_down:) shouldn't directly return error codes, they should notify the agent via `send_drop_notify` as we do in other bpf_lxc programs.
https://github.com/cilium/cilium/blob/8f4c7e10e026ebba05d8d2fb9910b8e5c75ed5b5/bpf/bpf_lxc.c#L92

**Comment by Jack-R-lantern** [comment]
\assign
