### ISSUE TITLE
Missing `TRACE_TO_PROXY` notification for return traffic to ingress proxy

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#22528]
Before this redirect to the proxy, we are missing a `TRACE_TO_PROXY` notification:
https://github.com/cilium/cilium/blob/8f4c7e10e026ebba05d8d2fb9910b8e5c75ed5b5/bpf/bpf_lxc.c#L830-L833

Same issue on the IPv6 path.

**Comment by christarazi** [comment]
I've tried hacking on this with the following diff:

```diff
diff --git a/bpf/bpf_lxc.c b/bpf/bpf_lxc.c
index 2c98bc90b1..51415bd2ab 100644
--- a/bpf/bpf_lxc.c
+++ b/bpf/bpf_lxc.c
@@ -309,6 +309,9 @@ static __always_inline int handle_ipv6_from_lxc(struct __ctx_buff *ctx, __u32 *d
 	if ((ct_status == CT_REPLY || ct_status == CT_RELATED) &&
 	    ct_state->proxy_redirect) {
 		/* Stack will do a socket match and deliver locally. */
+		send_trace_notify(ctx, TRACE_TO_PROXY, SECLABEL, 0,
+				  bpf_ntohs(proxy_port), 0, trace.reason,
+				  trace.monitor);
 		return ctx_redirect_to_proxy6(ctx, tuple, 0, false);
 	}
 
@@ -828,8 +831,13 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx, __u32 *d
 #endif /* ENABLE_L7_LB */
 
 	/* Check it this is return traffic to an ingress proxy. */
+	printk("before sending trace notification\n");
 	if ((ct_status == CT_REPLY || ct_status == CT_RELATED) && ct_state->proxy_redirect) {
 		/* Stack will do a socket match and deliver locally. */
+		send_trace_notify(ctx, TRACE_TO_PROXY, SECLABEL, 0,
+				  bpf_ntohs(proxy_port), 0, trace.reason,
+				  trace.monitor);
+		printk("should have sent trace notification\n");
 		return ctx_redirect_to_proxy4(ctx, tuple, 0, false);
 	}
 ```

however, I'm not seeing the missing trace point in monitor output. Additionally, I added the `printk()` statements to check if we are even reaching this code and I'm only seeing the first one `printk()` msg, which suggests that we are not reaching the condition where we would expect the `TRACE_TO_PROXY` event.

The workload is just doing a `dig google.com` with a policy that allows `matchPattern: '*'`.

Am I missing something?

**Comment by pchaigno** [comment]
That seems weird. How are you checking for the `printk` outputs?

> The workload is just doing a `dig google.com` with a policy that allows `matchPattern: '*'`.

The L7 policy needs to be enforced on ingress and you need to check the reply traffic (e.g., SYN+ACK) on the node where the policy is enforced.

**Comment by christarazi** [comment]
> That seems weird. How are you checking for the printk outputs?

`bpftool prog tracelog`

> The L7 policy needs to be enforced on ingress and you need to check the reply traffic (e.g., SYN+ACK) on the node where the policy is enforced.

Ah, so this could only be triggerable on DNS rules applied on ingress? I don't think we even support that: https://github.com/cilium/cilium/blob/master/pkg/policy/api/rule_validation.go#L113

---

This is what I see when I apply:

```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: tofqdn-dns-visibility
specs:
- endpointSelector: {}
  ingress:
  - fromEndpoints:
    - {}
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'

```

logs:

```
level=warning msg="Unable to add CiliumNetworkPolicy" ciliumNetworkPolicyName=tofqdn-dns-visibility error="Invalid CiliumClusterwideNetworkPolicy specs: L7 protocol DNS is not supported on ingress yet" k8sApiVersion= k8sNamespace= subsys=k8s-watcher
```

**Comment by christarazi** [comment]
Hm, this time I applied the [example HTTP L7 policy](https://docs.cilium.io/en/v1.12/gettingstarted/http/#apply-and-test-http-aware-l7-policy) and still only seeing `before sending trace notification` in `bpftool prog tracelog`.

**Comment by pchaigno** [comment]
Weird. Do you see the from-container trace?

Happy to debug that in a thread by the way, if it's easier.
