### ISSUE TITLE
Ingress Controller fails silently if l7proxy is disabled

### ISSUE THREAD

**Issue by gary-RR** [cilium/cilium#22535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When cilium is installed with wireguard:
helm install cilium cilium/cilium --version 1.12.3  --namespace kube-system --set kubeProxyReplacement=strict \
--set k8sServiceHost=192.168.0.64 --set k8sServicePort=6443 --set l7Proxy=false --set encryption.enabled=true \
--set encryption.type=wireguard --set hubble.enabled=false

And then L7 ingress is configured 
helm upgrade cilium cilium/cilium \
     --namespace kube-system \
     --reuse-values \
     --set ingressController.enabled=true \
     --set ingressController.loadbalancerMode=dedicated

kubectl -n kube-system rollout restart deployment/cilium-operator
kubectl -n kube-system rollout restart ds/cilium

If we try to leverage the ingress with the sample app from cilium docs, it waits a long time (seems to time out) and no result is returned:

kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.11/samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes/servicemesh/basic-ingress.yaml

HTTP_INGRESS=$(kubectl get ingress basic-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
If we call the service It just waits and eventually times out
curl --fail -s http://"$HTTP_INGRESS"/details/1 | jq

The expected result is a JSON payload like:
{
  "id": 1,
  "author": "William Shakespeare",
  "year": 1595,
  "type": "paperback",
  "pages": 200,
  "publisher": "PublisherA",
  "language": "English",
  "ISBN-10": "1234567890",
  "ISBN-13": "123-1234567890"
}
 
If cilium is installed without the wairegurd then everything works as expected. One odd thing is why the L7 proxy needs to be disabled ("--set l7Proxy=false")? wireguard is a L3/4 encryption so why it requires the L7 proxy be disabled? Doesn't make much sense. If we try to set "--set l7Proxy=true", wiregurd installation will fail.

### Cilium Version

cilium image (default): v1.12.2
cilium image (stable): v1.12.4
cilium image (running): v1.12.3

### Kernel Version

Linux kube-master 5.8.0-28-generic #30~20.04.1-Ubuntu SMP Thu Nov 5 20:57:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
Yes, `ingressController` requires `l7Proxy=true`, but WireGuard does not support `l7Proxy`. So unfortunately it is not possible to use WireGuard with the Ingress Controller (or any service mesh feature) at the moment.

We should document this in the ingress controller guide (cc @sayboras @jrajahalme ), or even better, error out if the user enables ingress controller while disabling the l7 proxy.

**Comment by gary-RR** [comment]
@gandro, thanks for the explanation!

**Comment by youngnick** [comment]
This issue has been resolved by the fix in #25215 - it's now not possible to disable the L7 proxy and enable Ingress or Gateway API support. For anyone else finding this one, if you're using a version that doesn't have this Helm check, note that L7 proxy _must_ be enabled for Ingress or Gateway API to work. 

Also important to note that as of 1.13, Wireguard _does_ now work with l7 proxy, so you don't need to disable the proxy when using Wireguard once you're on that version.
