### ISSUE TITLE
Can't connect to remote NodePort backend in hostNetwork (with tunnel enabled)

### ISSUE THREAD

**Issue by michaelasp** [cilium/cilium#22557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In cilium v1.12 with tunneling enabled, it is not possible to send traffic to nodeport services with hostnetwork pods being enabled. I believe the issue stems from this pr #18815. The function `DirectRoutingDeviceRequired` returns false in this case and never sets the macro `IPV4_DIRECT_ROUTING` which is required by nodeport for the SNAT IP for pods which aren't tunneled(i.e host network pods). Thanks for looking at this issue, it took us a bit to trace down but hopefully it's detailed enough. I think the macro still needs to be set in this case for traffic that is not tunneled. 

The datapath code that uses this is here, https://github.com/cilium/cilium/blob/07592906e958f12090830dc8d554774f57e6be32/bpf/lib/nat.h#L599-L613 
I believe that HostNetwork traffic falls into the second part of the conditional which breaks traffic flow. 

### Cilium Version

v1.12.4

### Kernel Version

5.4.0-42-generic

### Kubernetes Version

1.25

### Sysdump

N/A

### Anything else?

TCP Dump:
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vxlan0, link-type EN10MB (Ethernet), capture size 262144 bytes
22:22:09.271839 IP 10.200.0.2.47792 > 10.200.0.52.29442: Flags [S], seq 2615184186, win 64390, options [mss 1370,sackOK,TS val 2929822314 ecr 0,nop,wscale 7], length 0
22:22:09.271923 IP 0.0.0.0.47792 > 10.200.0.5.29442: Flags [S], seq 2615184186, win 64390, options [mss 1370,sackOK,TS val 2929822314 ecr 0,nop,wscale 7], length 0

SNAT IP is replaced by 0.0.0.0 since `IPV4_DIRECT_ROUTING` is not set.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Thanks for debugging & reporting, @michaelasp! Stumbled into the same issue while testing a fix for https://github.com/cilium/cilium/issues/22659 :sweat_smile:.

**Comment by julianwiedmann** [comment]
When forwarding the request to the backend, the Nodeport code SNATs with 0.0.0.0 (as `IPV4_DIRECT_ROUTING` is undefined, well spotted @michaelasp :+1:) here:
https://github.com/cilium/cilium/blob/ed94b2405e0bf6e319270a825390e4c2f344d7e9/bpf/lib/nodeport.h#L1683-L1698

We're forwarding host-to-host, so the packet doesn't go into the tunnel.

The following (+ test adjustments) should be enough. We might be able to exclude the case where the tunnel only exists for EgressGW.
```
--- a/pkg/option/config.go
+++ b/pkg/option/config.go
@@ -2591,7 +2591,7 @@ func (c *DaemonConfig) DirectRoutingDeviceRequired() bool {
        // BPF NodePort and BPF Host Routing are using the direct routing device now.
        // When tunneling is enabled, node-to-node redirection will be done by tunneling.
        BPFHostRoutingEnabled := !c.EnableHostLegacyRouting
-       return (c.EnableNodePort || BPFHostRoutingEnabled) && !c.TunnelingEnabled()
+       return (c.EnableNodePort || BPFHostRoutingEnabled)
```

**Comment by michaelasp** [comment]
Awesome! Thanks for the fix in progress @julianwiedmann 😄.

**Comment by brb** [comment]
@michaelasp Do you have the Socket LB enabled (`cilium status --verbose`)?

**Comment by michaelasp** [comment]
Hi @brb, sorry for the late response, I didn't get the notification. Any update on this issue? It seems to still be affecting us. For reference we are not using socket LB since it doesn't work with service mesh.

**Comment by pchaigno** [comment]
> we are not using socket LB since it doesn't work with service mesh

Do you have a reference for this? My impression was that socket LB is *required* for Cilium's service mesh.

**Comment by michaelasp** [comment]
Hey @pchaigno, I was referring to external service meshes, such as istio. From my understanding, socket LB prevents E/W traffic from being inspected by sidecar containers in those.
