### ISSUE TITLE
Lack of monitor aggregation for packets on path hostns -> overlay

### ISSUE THREAD

**Issue by AwesomePatrol** [cilium/cilium#22575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Steps to reproduce:
1. Create a cluster with at least 3 nodes
  a. Set `tunnel: geneve`
2. Create 2 pods with `iperf` on `node-1` and `node-3`
3. Create a `NodePort` `Service`
4. Run `hubble observe` on `node-2`
5. Connect `my-shell-1` to port on `node-2` (that will forward to pod on `node-3`)
6. Expect a monitor event generated approximately every `monitor-aggregation-interval` (default: 5s), instead get greeted with `205881` events in the span of 30 seconds

Results of `hubble observe` on `node-2`:
```
Dec  6 13:50:26.083: 10.108.1.202:40290 (world) <> default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK)
Dec  6 13:50:26.083: 10.108.1.202:40290 (world) <> default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK, PSH)
Dec  6 13:50:26.083: 10.108.1.202:40290 (world) <> default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK)
Dec  6 13:50:26.083: 10.108.1.202:40290 (world) <> default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK, PSH)
Dec  6 13:50:26.083: 10.108.1.202:40290 (world) <> default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK)
Dec  6 13:50:26.083: 10.108.1.202:40290 (world) <> default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK, PSH)
[...]
```

Expected (what is on node with `my-shell-1` or `my-shell-2`):
```
Dec  6 13:41:25.188: default/my-shell-1:42844 (ID:6621434) <- default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: SYN, ACK)
Dec  6 13:41:25.190: default/my-shell-1:42844 (ID:6621434) <- default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK, PSH)
Dec  6 13:41:30.912: default/my-shell-1:42844 (ID:6621434) <- default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK)
Dec  6 13:41:36.914: default/my-shell-1:42844 (ID:6621434) <- default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK)
Dec  6 13:41:42.913: default/my-shell-1:42844 (ID:6621434) <- default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK)
Dec  6 13:41:48.912: default/my-shell-1:42844 (ID:6621434) <- default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK)
Dec  6 13:41:54.912: default/my-shell-1:42844 (ID:6621434) <- default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK)
Dec  6 13:41:55.208: default/my-shell-1:42844 (ID:6621434) <- default/my-shell-2:5001 (ID:6650522) to-overlay FORWARDED (TCP Flags: ACK, FIN)
```

### Cilium Version

`78950e2b6e4ab3f31f4fd3d94c5effad4febc83d` (`master` from yesterday)

### Kernel Version

5.10.133+

### Kubernetes Version

v1.23.12-gke.100

### Anything else?

Initially reported as https://github.com/cilium/cilium/pull/22467

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
So from the title, I infer that those packets are requests from node-1 going to a backend on node-3 for the NodePort service you defined? And you only get this issue with the forward packets, not the replies (or maybe you are using DSR)?

**Comment by AwesomePatrol** [comment]
Sorry I missed two important things: `tunnel: geneve` and connecting to port on `node-2` (so that packets will need to be forwarded to pod on `node-3`. I updated the original description. Today I will work on providing some manifests to make it easier to reproduce

**Comment by AwesomePatrol** [comment]
This mitigates the issue, but it also completely disables reporting.
```patch
--- a/bpf/bpf_host.c
+++ b/bpf/bpf_host.c
@@ -458,7 +458,7 @@ handle_ipv4(struct __ctx_buff *ctx, __u32 secctx,
 {
        struct trace_ctx __maybe_unused trace = {
                .reason = TRACE_REASON_UNKNOWN,
-               .monitor = TRACE_PAYLOAD_LEN,
+               .monitor = 0,
        };
        struct remote_endpoint_info *info = NULL;
        __u32 __maybe_unused remote_id = 0;
```

**Comment by pchaigno** [comment]
I'm guessing that if you enable host firewall, the issue disappears?

**Comment by AwesomePatrol** [comment]
Yes, it works as it should (i.e. flows are aggregated):
```
Dec  8 11:34:29.730: 10.128.0.29:43270 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: SYN)
Dec  8 11:34:29.731: 10.128.0.29:43270 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK)
Dec  8 11:34:29.731: 10.128.0.29:43270 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Dec  8 11:34:29.742: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: SYN)
Dec  8 11:34:29.743: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK)
Dec  8 11:34:29.743: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Dec  8 11:34:35.460: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK)
Dec  8 11:34:39.756: 10.128.0.29:43270 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Dec  8 11:34:39.758: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK)
Dec  8 11:34:39.758: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Dec  8 11:34:39.758: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK)
Dec  8 11:34:39.758: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Dec  8 11:34:39.758: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Dec  8 11:34:39.758: 10.128.0.29:15735 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Dec  8 11:34:39.767: 10.128.0.29:43270 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Dec  8 11:34:39.768: 10.128.0.29:43270 (world) -> default/iperf-server:5201 (ID:6742010) to-endpoint FORWARDED (TCP Flags: ACK)
```

What is more interesting is that it is also enabled in the environment where I originally observed this issue. 🤔

**Comment by pchaigno** [comment]
> What is more interesting is that it is also enabled in the environment where I originally observed this issue. thinking

I'm guessing that environment is a bit behind on Cilium versions and didn't include https://github.com/cilium/cilium/commit/b08b12943fbcb4e15f20f82c5ea93174d4914b73?

**Comment by AwesomePatrol** [comment]
Yes you are right. I will patch it and verify.

As a side note, I made the same mistake again in the previous comment as I did in PR. I observed `to-endpoint` instead of `to-overlay`. If I change the node, I get `to-network`. I can't get `to-overlay` again no matter what node I use.

**Comment by AwesomePatrol** [comment]
> I'm guessing that environment is a bit behind on Cilium versions and didn't include [b08b129](https://github.com/cilium/cilium/commit/b08b12943fbcb4e15f20f82c5ea93174d4914b73)?

Unfortunately cherry-picking isn't enough, but hopefully simply upgrading to 1.12.0 will solve the problem. Thank you
