### ISSUE TITLE
cilium connectivity test failing in documented quick start procedure using kind running on Fedora

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium#22585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

cilium connectivity test timedout due to errors in echo-other-node pod when running through the docummented install process using kind managed k8s cluster running on Fedora (bare metal and pod machine VM on MacOS).

error details:
```
Error: EMFILE: too many open files, watch '/'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2303:34)
    at /usr/local/lib/node_modules/json-server/lib/cli/run.js:179:10 {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/',
  filename: '/'
}
```

Quick fix for kind documented here:
https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files

Suggested Change:
Enhance install documentation that notes recommended sysctl inotify related settings for kind to avoid too many open files error.

### Cilium Version

v1.12.4 and v1.12.2

### Kernel Version

Linux carbon 6.0.10-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 26 16:55:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
Do you mind opening a PR to update the docs for kind about this?

**Comment by afzal442** [comment]
Hi, any idea where to eye out? 😉

**Comment by LarsBingBong** [comment]
We're seeing this on a `Kubernetes` cluster with the following info:

- `Kubernetes` distribution: `K3s`
- `Kubernetes`: Version 1.24.8+k3s1
- OS: `Ubuntu 22.04 Jammy LTS`
- `Linux kernel`: v5.15.0-56

---

**Cilium**:

- CLI version: `v0.12.11 compiled with go1.19.3 on linux/amd64`
- Cilium on the Kubernetes cluster: 1.12.4

---

Following: https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files too raise the `instances` and `watches` values helps and the `cilium connectivity test` goes through.

---

I'm a little confused here though. Using e.g. > https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers to view the `inotify` values for `fs.inotify.max_user_watches` and `fs.inotify.max_user_instances` fixes it as I state above. However, this have never been an issue before.

So I looked further and:

Apparently the default `fs.inotify.max_user_watches` on `Ubuntu 20.04` is higher.

```text
# sysctl fs.inotify.max_user_instances fs.inotify.max_user_watches
  fs.inotify.max_user_instances = 128
  fs.inotify.max_user_watches = 131596

# lsb_release -a
  No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 20.04.4 LTS
  Release:        20.04
  Codename:       focal
```

Whereas on `Ubuntu 22.04.1` is:

```text
# sysctl fs.inotify.max_user_instances fs.inotify.max_user_watches
  fs.inotify.max_user_instances = 128
  fs.inotify.max_user_watches = 92513

# lsb_release -a
   No LSB modules are available.
   Distributor ID: Ubuntu
   Description:    Ubuntu 22.04.1 LTS
   Release:        22.04
   Codename:       jammy
```

---

So I'm writing the above to know if anyone else has experienced this on Ubuntu Kubernetes nodes and what people have done to potentially solve this.

Thank you

**Comment by ti-mo** [comment]
@jspaleta Where can the error you pasted be observed? How exactly does this cause the connectivity tests to fail?

We've seen random flakes connecting to echo-other-node in CI, so I'm wondering if this is failing silently behind the curtains somewhere bugtool/sysdump can't see it. Is this in kubelet logs, by any chance?

Maybe we need to investigate ways of grabbing kubelet logs in CI?

cc @brb as resident kind expert

**Comment by ysksuzuki** [comment]
I encountered this problem when I run the connectivity test locally, and I needed to increased the fs.inotify limits.
https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files

```
# Run connectivity test locally due to the too  many open files error
$ cilium connectivity test --include-unsafe-tests --collect-sysdump-on-failure \
  --sysdump-hubble-flows-count=1000000 --sysdump-hubble-flows-timeout=5m

# Some pods in cilium-test ns are failing
$ kubectl -n cilium-test get po
NAME                                  READY   STATUS             RESTARTS       AGE
client-6b4b857d98-5ksg2               1/1     Running            0              4m47s
client2-646b88fb9b-pb8hn              1/1     Running            0              4m46s
echo-external-node-545d98c9b4-ntb76   0/1     CrashLoopBackOff   5 (104s ago)   4m46s
echo-other-node-66bdd89578-4r9wl      1/2     CrashLoopBackOff   5 (98s ago)    4m46s
echo-same-node-55db76dd44-smblz       1/2     CrashLoopBackOff   5 (81s ago)    4m47s
host-netns-9gk5m                      1/1     Running            0              4m46s
host-netns-dmpfn                      1/1     Running            0              4m46s
host-netns-non-cilium-zwrpj           1/1     Running            0              4m46s
host-netns-rzz2j                      1/1     Running            0              4m46s

$ kubectl -n cilium-test logs echo-other-node-66bdd89578-4r9wl
Defaulted container "echo-other-node" out of: echo-other-node, dns-test-server

  \{^_^}/ hi!

  Loading /default.json
  Loading /middleware.js
  Done

  Resources
  http://:8080/private
  http://:8080/public
  http://:8080/auth-header-required

  Home
  http://:8080

  Type s + enter at any time to create a snapshot of the database
  Watching...

Error: EMFILE: too many open files, watch '/'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2350:36)
    at /usr/local/lib/node_modules/json-server/lib/cli/run.js:181:10 {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/',
  filename: '/'
}
```

**Comment by ti-mo** [comment]
Any takes for adding this to docs and making sure we get this right in our CI setup(s)?

**Comment by brb** [comment]
Can we replace the json-server with e.g., https://github.com/chanioxaris/json-server?

**Comment by tanguynicolas** [comment]
Documentation about this issue seems to be absent from [this page](https://docs.cilium.io/en/stable/installation/kind/).  
I just had the problem, and that's what got me here.
