### ISSUE TITLE
Visibility policy is disabled

### ISSUE THREAD

**Issue by ShaPoHun** [cilium/cilium#22615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Visibility policy is disabled
I'm learning about the l7 visibility strategy [(Layer 7 Protocol Visibility)](https://docs.cilium.io/en/v1.11/policy/visibility/#layer-7-protocol-visibility) . But it doesn't work

## result
![图片](https://user-images.githubusercontent.com/18458406/206395664-27a10263-3ded-43f6-a2eb-6912cf5e149a.png)

### Cilium Version

1.11.6

### Kernel Version

Linux qa-shanghai-master-1 5.4.206-1.el8.elrepo.x86_64 #1 SMP Fri Jul 15 06:38:32 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20221208-080705.zip](https://github.com/cilium/cilium/files/10183361/cilium-sysdump-20221208-080705.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Those fields will remain empty unless you set `endpoint-status=policy`. We have made this a bit clearer in the latest stable version of Cilium.

We should probably update the guide to clarify that.
