### ISSUE TITLE
ICMP fragments dropped when using BPF masquerading

### ISSUE THREAD

**Issue by mike4500** [cilium/cilium#22624]
HostA is a non-K8s system.
HostB is a K8S node running the Cilium agent

On HostA  a ping to Host B > 1472 bytes will fail. The following is seen by a tcpdump running on HostB:

- HostA: ping -c 1 -s 1448 HostB (this succeeds)
	HostA > HostB: ICMP echo request, id 75, seq 1, length 1456
	HOSTB > HostA: ICMP echo reply, id 75, seq 1, length 1456

- HostA: ping -c 1 -s 1472 HostB (this succeeds)
	HostA > HostB: ICMP echo request, id 76, seq 1, length 1456
	HostA > HostB: icmp
	HOSTB > HostA: ICMP echo reply, id 76, seq 1, length 1480

- HostA: ping -c 1 -s 1474 HostB (this fails)
	HostA > HostB: ICMP echo request, id 77, seq 1, length 1456
	HostA > HostB: icmp
	HostA > HostB: icmp
	HOSTB > HostA: ICMP echo reply, id 77, seq 1, length 1480
   30 sec. later
	HostA > HostB: ICMP reassembly time exceeded, length 556

Cilium version is v1.12.4 and the kernel version is 5.11.16-1. Also occurs on a K3S node with Cilium v1.12.1 and kernel 5.17.5-1. 
Cluster nodes have both a public interface and a private interface and the issue is seen on both interfaces.

Cilium installed via a manifest generated by:
helm template -n kube-system cilium drycc-canary/cilium --set hubble.enabled=true, --set hubble.relay.enables=true \
	--set hubble.ui.enabled=true, --set tunnel=geneve, --set cluster.name=cluster1,cluster.id=200 \
	--set ipam.operator.clusterPoolIPv4PodCIDR=10.200.0.0/18 --set bpf.masquerade=true, devices=(eno6np2, en05np0)

cilium monitor -t drop (on the target node cilium agent pod)

ping -c 1 -s 1474 HostB

xx drop (Invalid packet) flow 0x0 to endpoint 0, file bpf_host.c line 1983, , identity unknown: HostB_IP -> HostA_IP

ping -c 1 -s 1480 HostB

xx drop (Unsupported protocol for NAT masquerede) flow 0x0 to endpoint 0, file bpf_host.c line 1983, , identity unknown: HostB_IP -> HostA_IP

**Comment by pchaigno** [comment]
I'm guessing the bug goes away if you disable BPF masquerading. Can you confirm?

Could you also upload a sysdump of the cluster after running the failing request?

**Comment by mike4500** [comment]
Yes. The bug goes away with enable-bpf-masquerade: "false".

The cluster is on an air-gapped network and transfer may not be possible. Is there something specific I can pull out to reduce the latency?

**Comment by haribhusal1** [comment]
this issue still exists as of v1.13.3

**Comment by haribhusal1** [comment]
Steps to reproduce this issue: 

1. Have a k8s cluster 
2. instal Cilium Preferably >= v1.13.3
3. Initially have below value in cilium-config
 ```
enable-bpf-masquerade            false
 enable-host-legacy-routing       true
```
4. Rollout Restart ds/cilium and deployment/cilium-operator and once cilium ds are ready:

5. from one of the cluster node, try to ping another cluster node:
`ping -s 2500 192.168.x.x`
Your ping should be successful. 

6. Now change cilium config value to:
```
enable-bpf-masquerade            true
 enable-host-legacy-routing       false
```
from one of the cluster node, try to ping another cluster node:
`ping -s 2500 192.168.x.x`
Your ping should be UNSUCCESSFUL. Error can be like below.

```
ping -s 2500 192.168.122.150
PING 192.168.122.150 (192.168.122.150) 2500(2528) bytes of data.
ping: sendmsg: No buffer space available
ping: sendmsg: No buffer space available
ping: sendmsg: No buffer space available

```

7. Monitoring from hubble, should show error msg:

```
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, ifindex 7, file 105:2331, , identity unknown->unknown: 172.31.0.60 -> 172.31.0.21 TimeExceeded(TTLExceeded)
xx drop (Invalid packet) flow 0x0 to endpoint 0, ifindex 179, file 2:1167, , identity 1112->16777220: 10.0.36.28:33508 -> 169.254.25.10:53 udp
xx drop (Invalid packet) flow 0x0 to endpoint 0, ifindex 179, file 2:1167, , identity 1112->16777220: 10.0.36.28:33508 -> 169.254.25.10:53 udp
xx drop (Inval…
```

**Comment by atsai1220** [comment]
We were able to keep bpf masquerade by setting manually `mtu` to 1500 in the cilium configmap.

**Comment by pengfeiopen** [comment]
General Information
Cilium version 1.13.10
Kernel version 5.4.263
Operating System Rocky Linux release 8.9

Prerequisites
 1.System firewall enabled
 2.enable-bpf-masquerade=true
 3.Dual network card eth0 internal network eth1 external network

Monitoring from hubble,cilium
```
kubectl exec -it  cilium-56cjz   -n kube-system -- hubble observe --verdict DROPPED
 
Dec 14 08:56:21.707: 192.xxx.xxx.xxx (host) <> 77.90.185.208 (world) Unsupported protocol for NAT masquerade DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
Dec 14 08:56:22.656: 192.xxx.xxx.xxx (host) <> 77.90.185.195 (world) Unsupported protocol for NAT masquerade DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
Dec 14 08:56:23.549: 192.xxx.xxx.xxx (host) <> 108.181.56.102 (world) Unsupported protocol for NAT masquerade DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
Dec 14 08:56:26.512: 192.xxx.xxx.xxx (host) <> 77.90.185.188 (world) Unsupported protocol for NAT masquerade DROPPED (ICMPv4 DestinationUnreachable(CommAdminProhibited))
```
