### ISSUE TITLE
Allow libvirt to replace Virtualbox as vagrant provider

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2264]
Consistent host crashes from Virtualbox are causing development friction. Allowing developers to run the VMs under kvm (via libvirt plugin) may alleviate this issue.

Below is a (not comprehensive) list of things to fix to use libvirt to run the development VMs instead of Virtualbox:
* [ ] Sometimes the libvirt-backed boxes don't get IP connectivity automatically.
  * Possibly caused by vagrant-libvirt assuming eth\* named interfaces rather than the new ens\*p\*
  * Maybe this is already configured correctly, it's just that libvirt dhcp server takes longer to make connection and the VM image doesn't have a big enough timeout in its dhclient settings?
  * Related: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/609
* [x] ~~Even if local manual workarounds fix the above issue, NFS doesn't immediately work~~

**Comment by vadorovsky** [comment]
>NFS doesn't immediately work

What kind of issue do you have at this point? Usually, the problem with NFS mounts in vagrant-libvirt is related to firewall configuration in the most of distros. Hopefully we will just need to document how to configure firewalld / yast firewall / ufw properly.

Also, we are currently using rsync by default, so maybe we can use it for libvirt too (at least at the beginning)?

**Comment by joestringer** [comment]
> What kind of issue do you have at this point? Usually, the problem with NFS mounts in vagrant-libvirt is related to firewall configuration in the most of distros. Hopefully we will just need to document how to configure firewalld / yast firewall / ufw properly.

If I knew, I would probably be using libvirt already ;) It could be a firewall configuration issue, or it could be something like the IP connectivity issue meaning that NFS can't connect on bootup and it gives up, so if the first issue is resolved then NFS will work too.

> Also, we are currently using rsync by default, so maybe we can use it for libvirt too (at least at the beginning)?

rsync should work already.

**Comment by joestringer** [comment]
I spent some time on this recently, and was able to switch to libvirt/kvm, however I still observed my host kernel crash when booting the k8s VMs in `test/`. For reference I'll include my changes below but I think that this means we should pursue an alternative option to try to address these crashes.

First, you need vagrant-libvirt and vagrant-mutate. Fetch the vagrant virtualbox image and run `vagrant mutate ...` to mutate the virtualbox image into a libvirt image.

The below instructions need to be applied to the VM (ideally in the cilium-packer repo):

Add these lines to `/etc/network/interfaces`:
```
auto eth0
iface eth0 inet dhcp
```

Add these to the `/etc/grub/default` kernel commandline:
```
net.ifnames=0 biosdevnames=0
```

These ensure that devices are named like `eth0`, `eth1`, ... because the vagrant-libvirt plugin doesn't support the newer method for naming devices.. and also ensure that the first device autoconnects to the network so that vagrant can contact the VM and provision it.

Then, the test scripts must be taught about the `ethX` style of naming devices, and some libvirt-specific options:
```
diff --git a/test/Vagrantfile b/test/Vagrantfile
index dc8ad1f431fb..b5a1d881668a 100644
--- a/test/Vagrantfile
+++ b/test/Vagrantfile
@@ -14,7 +14,6 @@ $SERVER_VERSION="69"
 $MEMORY = (ENV['MEMORY'] || "4096").to_i
 $CPU = (ENV['CPU'] || "2").to_i
 
-ENV["VAGRANT_DEFAULT_PROVIDER"] = "virtualbox"
 Vagrant.configure("2") do |config|
 
     config.vm.define "runtime" do |server|
@@ -24,13 +23,18 @@ Vagrant.configure("2") do |config|
             vb.memory= $MEMORY
             vb.linked_clone = true
         end
+        server.vm.provider :libvirt do |libvirt|
+            libvirt.memory = $CPU
+            libvirt.cpus = $MEMORY
+        end
 
         server.vm.box =  "#{$SERVER_BOX}"
         server.vm.box_version = $SERVER_VERSION
         server.vm.hostname = "runtime"
 
         # This network is only used by NFS
-        server.vm.network "private_network", type: "dhcp"
+        server.vm.network "private_network", type: "dhcp",
+                :libvirt__forward_mode => "none"
         server.vm.synced_folder "../", "/home/vagrant/go/src/github.com/cilium/cilium",
             nfs: $NFS
 
@@ -52,16 +56,24 @@ Vagrant.configure("2") do |config|
                 vb.memory= $MEMORY
                 vb.linked_clone = true
             end
+            server.vm.provider "libvirt" do |libvirt|
+                libvirt.cpus = $CPU
+                libvirt.memory= $MEMORY
+            end
 
             server.vm.box =  "#{$SERVER_BOX}"
             server.vm.box_version = $SERVER_VERSION
             server.vm.hostname = "k8s#{i}"
             server.vm.network "private_network",
                 ip: "192.168.36.1#{i}",
-                virtualbox__intnet: "cilium-k8s#{$BUILD_NUMBER}-#{$JOB_NAME}-#{$K8S_VERSION}"
+                virtualbox__intnet: "cilium-k8s#{$BUILD_NUMBER}-#{$JOB_NAME}-#{$K8S_VERSION}",
+                :libvirt__forward_mode => "route",
+                :libvirt__guest_ipv6 => 'yes',
+                :libvirt__dhcp_enabled => false
 
             # This network is only used by NFS
-            server.vm.network "private_network", type: "dhcp"
+            server.vm.network "private_network", type: "dhcp",
+                :libvirt__forward_mode => "none"
             server.vm.synced_folder "../", "/home/vagrant/go/src/github.com/cilium/cilium",
                 nfs: $NFS
             # Provision section
diff --git a/test/provision/k8s_install.sh b/test/provision/k8s_install.sh
index 13a92e8dae03..2352e1090a88 100755
--- a/test/provision/k8s_install.sh
+++ b/test/provision/k8s_install.sh
@@ -9,6 +9,8 @@ SRC_FOLDER="/home/vagrant/go/src/github.com/cilium/cilium"
 SYSTEMD_SERVICES="$SRC_FOLDER/contrib/systemd"
 MOUNT_SYSTEMD="sys-fs-bpf.mount"
 
+MASTER_IP="192.168.36.11"
+CLUSTER_DEV="eth1"
 NODE=$1
 IP=$2
 K8S_VERSION=$3
@@ -104,7 +106,7 @@ sudo iptables --policy FORWARD ACCEPT
 #check hostname to know if is kubernetes or runtime test
 if [[ "${HOST}" == "k8s1" ]]; then
     sudo kubeadm init --token=$TOKEN \
-        --apiserver-advertise-address="192.168.36.11" \
+        --apiserver-advertise-address="${MASTER_IP}" \
         --pod-network-cidr=10.10.0.0/16 \
         ${KUBEADM_OPTIONS}
 
@@ -126,7 +128,7 @@ if [[ "${HOST}" == "k8s1" ]]; then
 
     $PROVISIONSRC/compile.sh
 else
-    kubeadm join --token=$TOKEN 192.168.36.11:6443 \
+    kubeadm join --token=$TOKEN ${MASTER_IP}:6443 \
         ${KUBEADM_SLAVE_OPTIONS}
     sudo systemctl stop etcd
     docker pull k8s1:5000/cilium/cilium-dev:latest
@@ -137,7 +139,7 @@ else
     # though the service IP should be routed to a different interface.
     # This particular workaround is only needed for cilium, running on a pod on host
     # network namespace, to reach out kube-api-server.
-    sudo iptables -t nat -A POSTROUTING -o enp0s8 ! -s 192.168.36.12 -j MASQUERADE
+    sudo iptables -t nat -A POSTROUTING -o ${CLUSTER_DEV} ! -s ${IP} -j MASQUERADE
 fi
 
 sudo touch /etc/provision_finished
```

For the developer VM, there's similar but separate changes required in the following files:
* `contrib/vagrant/start.sh` (update device names, always statically configure IPv4 addresses, fix the check to ensure that `vboxnet_addr_finder` isn't run, ensure the link is set up inside the VM so it can pass traffic)
* `Vagrantfile` ( update device names, define cpus/memory for libvirt, run the NFS logic even if the provider isn't virtualbox)

**Comment by joestringer** [comment]
This has been evaluated above, the instructions should still work but it didn't address the core problem. Closing.
