### ISSUE TITLE
Ingress Controller fails silently with basic configuration as documented

### ISSUE THREAD

**Issue by mahmoudajawad** [cilium/cilium#22645]
Hello.

I'm trying to get cilium up and running with minimal configuration for testing purposes. In the lab associated with this topic, it is only mentioned that installation of cilium requires two additional parameters to get ingress support using cilium without any additional component.
The documentation as well explains the same in the page: https://docs.cilium.io/en/stable/gettingstarted/servicemesh/ingress/ however, after deploying the sample application from https://docs.cilium.io/en/stable/gettingstarted/servicemesh/http/ curl only replies with (52) Empty reply from server. Cilium status is all green.

I also came across #22139 which explained how cni-chaining-portmap needs to be enabled if cilium config reports kube-proxy-replacement as disabled, which I also did, but still received the same results. So, I re-deployed cilium with kube-proxy-replacement set to strict, and again the same results.

Finally, I came across #22535 which explained that l7-proxy has to be enabled for ingress controller to work, and by looking at my config it seems to be already enabled.

I'm on LKE (Linode), using cilium version 1.12.4, deployed using helm.

cilium config:
```
agent-not-ready-taint-key                      node.cilium.io/agent-not-ready
arping-refresh-period                          30s
auto-direct-node-routes                        false
bpf-lb-external-clusterip                      false
bpf-lb-map-max                                 65536
bpf-lb-sock                                    false
bpf-map-dynamic-size-ratio                     0.0025
bpf-policy-map-max                             16384
bpf-root                                       /sys/fs/bpf
cgroup-root                                    /run/cilium/cgroupv2
cilium-endpoint-gc-interval                    5m0s
cluster-id                                     0
cluster-name                                   default
cluster-pool-ipv4-cidr                         10.0.0.0/8
cluster-pool-ipv4-mask-size                    24
cni-chaining-mode                              portmap
custom-cni-conf                                false
debug                                          false
disable-cnp-status-updates                     true
disable-endpoint-crd                           false
enable-auto-protect-node-port-range            true
enable-bgp-control-plane                       false
enable-bpf-clock-probe                         true
enable-endpoint-health-checking                true
enable-envoy-config                            true
enable-health-check-nodeport                   true
enable-health-checking                         true
enable-hubble                                  true
enable-ingress-controller                      true
enable-ingress-secrets-sync                    true
enable-ipv4                                    true
enable-ipv4-masquerade                         true
enable-ipv6                                    false
enable-ipv6-masquerade                         true
enable-k8s-terminating-endpoint                true
enable-l2-neigh-discovery                      true
enable-l7-proxy                                true
enable-local-redirect-policy                   false
enable-policy                                  default
enable-remote-node-identity                    true
enable-svc-source-range-check                  true
enable-vtep                                    false
enable-well-known-identities                   false                                                                                                  [0/1937]
enable-xt-socket-fallback                      true
enforce-ingress-https                          true
hubble-disable-tls                             false
hubble-listen-address                          :4244
hubble-socket-path                             /var/run/cilium/hubble.sock
hubble-tls-cert-file                           /var/lib/cilium/tls/hubble/server.crt
hubble-tls-client-ca-files                     /var/lib/cilium/tls/hubble/client-ca.crt
hubble-tls-key-file                            /var/lib/cilium/tls/hubble/server.key
identity-allocation-mode                       crd
ingress-lb-annotation-prefixes                 service.beta.kubernetes.io service.kubernetes.io cloud.google.com
ingress-secrets-namespace                      cilium-secrets
install-iptables-rules                         true
install-no-conntrack-iptables-rules            false
ipam                                           cluster-pool
kube-proxy-replacement                         strict
kube-proxy-replacement-healthz-bind-address
monitor-aggregation                            medium
monitor-aggregation-flags                      all
monitor-aggregation-interval                   5s
node-port-bind-protection                      true
nodes-gc-interval                              5m0s
operator-api-serve-addr                        127.0.0.1:9234
preallocate-bpf-maps                           false
procfs                                         /host/proc
remove-cilium-node-taints                      true
set-cilium-is-up-condition                     true
sidecar-istio-proxy-image                      cilium/istio_proxy
synchronize-k8s-nodes                          true
tofqdns-dns-reject-response-code               refused
tofqdns-enable-dns-compression                 true
tofqdns-endpoint-max-ip-per-hostname           50
tofqdns-idle-connection-grace-period           0s
tofqdns-max-deferred-connection-deletes        10000
tofqdns-min-ttl                                3600
tofqdns-proxy-response-max-delay               100ms
tunnel                                         vxlan
unmanaged-pod-watcher-interval                 15
vtep-cidr
vtep-endpoint
vtep-mac
vtep-mask
```

**Comment by youngnick** [comment]
Thanks for logging this @mahmoudajawad. Would you be able to collect a sysdump for us as per https://docs.cilium.io/en/stable/operations/troubleshooting/#reporting-a-problem ? That way we can try and get to the bottom of what's not working.

**Comment by mahmoudajawad** [comment]
Hello, @youngnick. Thanks for replying. Here's the dump.
Please, note that I took the step to manually delete `ds/kube-proxy` as a member of the Slack space suggested it shouldn't exist if I want to have ingress controller of cilium in action. However, even after removing `kube-proxy`, and restarting all pods, I'm still getting the empty response error.

[cilium-sysdump-20221213-064317.zip](https://github.com/cilium/cilium/files/10215175/cilium-sysdump-20221213-064317.zip)

**Comment by youngnick** [comment]
Thanks @mahmoudajawad, that's great. I can see that #22698 isn't affecting you, which is also great.

However, I can't see any Ingress objects that have an ingressClass of `cilium` present. Do you have at least one Ingress resource in the cluster? If so, could you post the YAML in here? Thanks.

**Comment by mahmoudajawad** [comment]
Oops! I was making some more tests before replying and ended-up removing the ingress before creating the dump archive. I redeployed the sample Ingress from documentations and here's the new dump:
[cilium-sysdump-20221213-071929.zip](https://github.com/cilium/cilium/files/10215455/cilium-sysdump-20221213-071929.zip)

**Comment by mahmoudajawad** [comment]
@youngnick, I can spare sometime to have a session with you to look into the issue should you find it practical. I can prepare a new cluster ahead of time and then go through all the steps to installing cilium and enabling Ingress Controller in it with you so that we debug the cluster config with every step.

**Comment by youngnick** [comment]
Hi @mahmoudajawad, sorry for the big delay here. I just came back to this one, and I still can't see any issues with the sysdump, looks like the Ingress should be working. If you're still interested, we can follow up here.

**Comment by mahmoudajawad** [comment]
@youngnick, thanks for coming back to this. I took little time to reply as I wanted to again give this a shot on LKE (Akami Cloud) with v1.26. However, I ended-up with the exact results.

It is worth noting that I was able to get it working on EKS (AWS) without any hassle, so I'm now leaning towards this being a LKE-specific issue, yet I would like to see it resolved as I use multiple cloud providers and would love to use cilium everywhere. Where should we go forward with this?

**Comment by youngnick** [comment]
Hmm, it looks like LKE might need some extra annotations, see #25357 for the annotations, although it seems that we'll need to build some things to actually support it.

**Comment by youngnick** [comment]
Hi @mahmoudajawad, have you checked to see if LKE does need extra annotations? #25357 shows some, and if it does you use the annotation copying documented in our Ingress documentation to copy the annotation from the Ingress to the generated Service. (#25357 uses the `service.beta.kubernetes.io/linode-loadbalancer-hostname-only-ingress: "true"` annotation, but they were using Gateway API, so we had to build some other functionality to support managing annotations there).

**Comment by youngnick** [comment]
This one has gone quite a while with no update, so I'm going to close it out. @mahmoudajawad, please comment if you need it reopened.
