### ISSUE TITLE
LB Source Range Check  is dropping packets in some of the cilium-agent pods.  

### ISSUE THREAD

**Issue by sugangli** [cilium/cilium#22658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have a cluster running with cilium 1.11.8. We deployed an L4 NetLB service with 105 sourceRanges.  When we curled the VIP from a client within these sourceRanges,  packets  were dropped by one of the cilium agent because of the source range checks[1], where W.X.Y.Z is the source range we defined and A.B.C.D is the VIP of the LB.  We restarted the node of the faulty pod,  and the problem seemed to go away for that particular test IP.  However, `cilium map get cilium_lb4_source_range` only gave me 46 entries on this pod. And `bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_source_range` shows different numbers of entries (600+ entries) on different pods. 

### Cilium Version

1.11.8

### Kernel Version

5.10.133

### Kubernetes Version

1.24

### Relevant log output

```shell
[1]Listening for events on 8 CPUs with 64x4096 of shared memory Press Ctrl-C to quit level=info msg="Initializing dissection cache..." subsys=monitor xx drop (Denied by LB src range check) flow 0x0 to endpoint 0, , identity world->unknown: W.X.Y.Z:10401 -> A.B.C.D:443 tcp SYN xx drop (Denied by LB src range check) flow 0x0 to endpoint 0, , identity world->unknown: W.X.Y.Z:10500 -> A.B.C.D:443 tcp SYN xx drop (Denied by LB src range check) flow 0x0 to endpoint 0, , identity world->unknown: W.X.Y.Z:10501 -> A.B.C.D:443 tcp SYN xx drop (Denied by LB src range check) flow 0x0 to endpoint 0, , identity world->unknown: W.X.Y.Z:10502 -> A.B.C.D:443 tcp SYN xx drop (Denied by LB src range check) flow 0x0 to endpoint 0, , identity world->unknown: W.X.Y.Z:10404 -> A.B.C.D:443 tcp SYN xx drop (Denied by LB src range check) flow 0x0 to endpoint 0, , identity world->unknown: W.X.Y.Z:10714 -> A.B.C.D:443 tcp SYN xx drop (Denied by LB src range check) flow 0x0 to endpoint 0, , identity world->unknown: W.X.Y.Z:10608 -> A.B.C.D:443 tcp SYN xx drop (Denied by LB src range check) flow 0x0 to endpoint 0, , identity world->unknown: W.X.Y.Z:10917 -> A.B.C.D:443 tcp SYN

Pod1:
######
bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_source_range | wc -l             
685
cilium map get cilium_lb4_source_range | wc -l
9
#####

Pod2:
######
bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_source_range | wc -l
668
cilium map get cilium_lb4_source_range | wc -l
75
######

Pod3:
######
bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_source_range | wc -l 
680
cilium map get cilium_lb4_source_range | wc -l
73
######
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sugangli** [comment]
> 

Sorry, updated the footnote in the log output.  We couldn't repro this error but it was seen on our customer's clusters.  We also found  a cilium map tool bug related to this issue. Will file another bug for that.

**Comment by brb** [comment]
Thanks for the issue.

Please use `cilium bpf lb list --source-ranges` instead. `cilium map get` is not meant to dump map contents for users.

**Comment by sugangli** [comment]
> Thanks for the issue.
> 
> Please use `cilium bpf lb list --source-ranges` instead. `cilium map get` is not meant to dump map contents for users.

Hi, thank you for the suggestion. We are on 1.11.8. and we don't have this option.

**Comment by sugangli** [comment]
Just to add another data point. We dumped and filtered the cilium_lb4_source_range map and the cilium_lb4_services_v2 map, and identified two source ranges has less reverse nat IDs than the expected number (4).  This happened on one of the cilium agents, the other cilium agent looked OK.

**Comment by shikha-khandelwa** [comment]
Hi Cilium team, checking in to see if we have any updates on this bug or if you have questions? Thanks!

**Comment by pchaigno** [comment]
> I am working with Sugang to track the resolution of this bug.

Do you mean you are working on fixing it? I'm not aware of anyone (else) who is looking into it.

**Comment by shikha-khandelwa** [comment]
I am working directly with the customer that this bug is affecting. I am not working on fixing it; only tracking resolution. Sorry for the confusion.

**Comment by brb** [comment]
Without a sysdump or knowing which LB src ranges were configured it's difficult to say what went wrong. I suggest to add logging for the LB src range modifications in the agent code, and check the BPF map content.

**Comment by anfernee** [comment]
From the control plane logic, I think there could be an issue. The `LBBPFMap.UpdateSourceRanges` basically deletes all previous source ranges, and add current source ranges. Any error happens during the update, it exits, which leaves the map in an inconsistent state: 

https://github.com/cilium/cilium/blob/fcf2b7ad1c47cc7309e752eb087ecfbda7ff8a6e/pkg/maps/lbmap/lbmap.go#L391-L421

If the map state becomes inconsistent, it will probably never be consistent again, because the previous source range is not really what's in the map, but from the user space cache. Some entries might be left behind and never got a chance to be cleaned up. 

https://github.com/cilium/cilium/blob/fcf2b7ad1c47cc7309e752eb087ecfbda7ff8a6e/pkg/service/service.go#L688-L693

**Comment by brb** [comment]
> Any error happens during the update

@anfernee Have you seen any error in your case?

**Comment by anfernee** [comment]
@sugangli has been dealing with a case where they have different ebpf map entries on different nodes (in the original comment). Unfortunately we don't have a sysdump to prove this is the root cause. Do you think it's worthwhile to have some house keeping controller to scan and reconcile the source range map?

**Comment by brb** [comment]
> Do you think it's worthwhile to have some house keeping controller to scan and reconcile the source range map?

I think it's better to figure out what is a root cause. The controller would just hide symptoms, but not the underlying issue.

**Comment by sugangli** [comment]
Is the cilium-bugtool sufficient to generate all the information we need?

**Comment by brb** [comment]
> Is the cilium-bugtool sufficient to generate all the information we need?

AFAIK cilium-bugtool does not include cilium-agent logs, while cilium-sysdump does.

**Comment by brb** [comment]
@sugangli Bump.

**Comment by sugangli** [comment]
Hi, if we added Ipv6 addresses into the source ranges, and then removed them. Will it cause this problem? The Ipv6 addresses may corrupt the Ipv4 entries, and they will never be recovered, right?

**Comment by sugangli** [comment]
@brb Bump. We have seen this on our test grid repeatedly. After we removed the adding Ipv6 addresses bit, the issue was gone.

**Comment by brb** [comment]
@sugangli Thanks for the update. There should be a src range map per IP family. I'm still struggling to understand how a IPv6 addr can influence the IPv4 map content.

**Comment by sugangli** [comment]
@brb Hi,  if I read the code correctly, the selection of the src range map is determined by the type of the front end IP, which is the service IP. If the service IP is v4,  and we accidentally add v6 addresses to the src range in the LB, then we may hit this issue.

**Comment by brb** [comment]
Aha! Doesn't kube-apiserver disallow such IP family mismatches?

**Comment by sugangli** [comment]
Hmm.. from our practices, they just went through.

**Comment by brb** [comment]
@sugangli I think we can check that on the cilium-agent side. Mind sending a PR?

**Comment by sugangli** [comment]
I can do it sometime next week. And the expected behavior will be logging the error on the cilium-agent?

**Comment by anfernee** [comment]
This seems to be a overlook in [dualstack KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/563-dual-stack) from k8s API side. when the service family is single stack, we don't verify source range to be the same ip family? cc @thockin

**Comment by thockin** [comment]
There was an issue (I know there were more, but here are a few:
https://github.com/kubernetes/kubernetes/issues/64841#issuecomment-524010965,
https://github.com/kubernetes/kubernetes/issues/105182,
https://github.com/kubernetes/kubernetes/issues/109575) to tighten the
meaning of the field.  On discussion, it turns out providers do
interesting things here, and we really CAN'T tighten it.

The cilium agent needs to catch it.

https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/service.go#L191-L201

**Comment by brb** [comment]
> I can do it sometime next week. And the expected behavior will be logging the error on the cilium-agent?

@sugangli Yep
