### ISSUE TITLE
L7 proxy access log file rotation isn't working

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#2267]
- Cilium version (run `cilium version`)
```cilium version
Cilium 1.0.0-rc2 40557c1 Sun, 3 Dec 2017 22:10:46 +0100 go version go1.9 linux/amd64
root@ip-172-0-36-124:/var/run/cilium#
```

- Kernel version (run `uname -a`)
```
uname -a
Linux ip-172-0-36-124.us-west-2.compute.internal 4.11.9-coreos #1 SMP Thu Jul 6 00:54:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
kubectl

### How to reproduce the issue
* Add an L7 enforcement policy
* Generate some L7 traffic and confirm that there are at least some logs in access.log file
* Execute the following command:
```
data=`cat access.log`
cat $data >> access.log
```
This increases the size of the access.log by a factor of 2 every time it is run.
* Repeat the previous step until the size exceeds 100Mb, which is the default limit configured with lumberjack library by the cilium agent.
* Generate some traffic again so that a few more logs are written to the access.log file. According to the documentation of lumberjack, each write should first check whether the size exceeds the limit, and then rotate the file, if needed.
* However, I was able to exceed the size limit, and the log file rotation did not happen:
```
root@ip-172-0-36-124:/var/run/cilium# ls -ltrh
total 232M
-rw-r--r--. 1 root root      1 Dec  5 23:14 cilium.pid
srw-rw----. 1 root cilium    0 Dec  5 23:15 monitor.sock
srw-rw----. 1 root cilium    0 Dec  5 23:15 cilium.sock
srw-rw----. 1 root cilium    0 Dec  5 23:15 health.sock
drwxr-x---. 8 root root    260 Dec  5 23:25 state
-rw-r--r--. 1 root root   232M Dec  5 23:54 access.log
```

**Note**: The lumberjack documentation states that it does not work well if there are multiple writers to the file, which is the case here. However, I expected the log rotation to happen correctly when a new log was written to the file by the proxy and the size was already > 100Mb. Please mark the Bug as invalid if the expectation is incorrect.

**Comment by manalibhutiyani** [comment]
The log will not be exactly rotated at 100MB all the time. This is mainly because of the way the kernel flushes file writes (The current file size on disk might be <100MB and the writes in flight i.e not on disk yet may not have amounted to > 100Mb). If you tail and check the file size, it will eventually rotate a bit later afterwards. You can check this behavior. I have tested this.

**Comment by ashwinp** [comment]
@manalibhutiyani how long do you recommend waiting? The file has size > 100Mb since the last 20 minutes now, and new writes (initiated by the proxy, not by my script) are continuously happening.

**Comment by manalibhutiyani** [comment]
Hmm.. that shouldn't happen.. I meant a couple of seconds more... Let me take a look.

**Comment by tgraf** [comment]
@ashwinp Is this still a bug?

**Comment by manalibhutiyani** [comment]
Closing since this access log will be deprecating soon in favor of monitor only logs
