### ISSUE TITLE
Cilium map get cilium_lb4_source_range return wrong entries if there are overlapped source ranges in the LB

### ISSUE THREAD

**Issue by sugangli** [cilium/cilium#22697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`cilium map get cilium_lb4_source_range` returns no entry for it if I put 185.185.10.46/32 twice in the LB.  Similarly, If I put 185.185.10.46/24 and 185.185.10.46/32, it returns only 185.185.10.0. Lastly even I removed 185.185.10.46/24, 185.185.10.146 won’t come back. `bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_source_range` gives the consistent results every time.

### Cilium Version

1.11.8

### Kernel Version

5.10.133

### Kubernetes Version

1.24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
cc @brb

**Comment by brb** [comment]
As mentioned in the previous issue, `cilium map get cilium_lb4_source_range` is not meant to be used to dump the LB src ranges from the BPF maps. Could you upgrade to v1.12 and check whether `cilium bpf lb list --source-ranges` has the same issue?
