### ISSUE TITLE
Clarify documentation and prevent activating Ingress and Gateway controllers if l7 proxy is disabled

### ISSUE THREAD

**Issue by youngnick** [cilium/cilium#22698]
This issue is effectively an epic covering work to handle what happens when Ingress or Gateway API support is enabled when L7 proxy support has already been explicitly disabled (which is required for Wireguard support, but could also be done for other reasons).

When this happens, a few problems can arise:
* #22535 
* #22667 

The fact that the last one has all Cilium pods panic and crash seems pretty bad.

Actions to take here are _at least_:
* [x] #22788
* [x] #22789
* [x] #22790
* [x] #21354 insead of the above issue.
* [x] ~Ensure that Kubernetes watchers don't use uninitialized l7 proxy config (which is the source of #22667) ~ - This is a very large refactor that will also cross over into efforts to move code more towards the Hive style, so it's pulled out of this issue.

**Comment by pchaigno** [comment]
Should we split this up into the 4 above tasks and mark good-first-issues? You should find people to work on this in the community if we do that IMO.

**Comment by afzal442** [comment]
Hey there, would like to look into it.

cc @pchaigno

**Comment by youngnick** [comment]
Thanks @pchaigno, good call. I've split out three of the tasks, and marked them good-first-issue. @afzal442, please feel free to pick up any of those sub-tasks!

**Comment by amolkavitkar** [comment]
https://github.com/cilium/cilium/blob/13ee10a1424e9e2ae15615937e7d9b03587388c5/daemon/cmd/daemon_main.go#L1490
isn't this is suppose to log a error if wireguard is enabled with L7proxy

**Comment by pchaigno** [comment]
@amolkavitkar That's correct and this logic works, but the present issue is about the Ingress and Gateway controllers when the L7 proxy is disabled, not about WireGuard. WireGuard is just one of the reasons why the L7 proxy might be disabled.

**Comment by youngnick** [comment]
#18773 is another example of a similar behavior.

**Comment by youngnick** [comment]
With #25215 merged, this one is resolved. As of 1.13, it's not possible to disable l7 proxy and enable Ingress or Gateway API, it will be rejected by Helm.

**Comment by jibi** [comment]
> With #25215 merged, this one is resolved. As of 1.13, it's not possible to disable l7 proxy and enable Ingress or Gateway API, it will be rejected by Helm.

reopening this as I think there's a typo in https://github.com/cilium/cilium/pull/25215/files: `l7proxy` should be `l7Proxy` (we dropped that PR from v1.12 https://github.com/cilium/cilium/pull/25452 and v1.13 https://github.com/cilium/cilium/pull/25346 backports but probably the notification from the PR description got lost)

**Comment by youngnick** [comment]
@sayboras closed this one in #25570.
