### ISSUE TITLE
Document need to rotate keys regularly with IPsec to avoid sequence number overflow

### ISSUE THREAD

**Issue by pecigonzalo** [cilium/cilium#22747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Loss of network connectivity between pods with ipsec enabled and ip xfrm state anti-replay oseq maxed out at 0xffffffff.

This is related to the issue described in https://github.com/cilium/cilium/issues/12447, but I thought opening a new issue was the way to go instead of resurrecting that old one.

### Cilium Version

Client: 1.12.1 4c9a630 2022-08-15T16:29:39-07:00 go version go1.18.5 linux/amd64
Daemon: 1.12.1 4c9a630 2022-08-15T16:29:39-07:00 go version go1.18.5 linux/amd64

### Kernel Version

5.4.209-116.367.amzn2.x86_64

### Kubernetes Version

Kubernetes v1.22.12-eks-ba74326

### Anything else?

This issue was closed as fixed by https://github.com/cilium/cilium/pull/15039, which was later reverted in https://github.com/cilium/cilium/commit/bb086ecefd92655ff53f693d7c668752c9a41a3d suggesting this to be fixed in the Cilium CLI and providing key rotation.

The task which I believe was meant to provide this was closed as stale https://github.com/cilium/cilium/issues/7304

I believe this has not been provided, and it has not been documented as required, but I understand from this chain of issues that there is a still relevant issue that at least requires the docs to explicitly mention key rotation has to be implemented.

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pecigonzalo** [comment]
I can confirm that, its required and creating a rotating job created by my colleague @cbeneke fixed the issue for us. I believe this should be in the docs.

**Comment by brb** [comment]
cc @NikAleksandrov @pchaigno

**Comment by pchaigno** [comment]
Yep, we should document that IPsec keys need to be regularly rotated to avoid running into the sequence number overflow. It may be enough to mention this in https://docs.cilium.io/en/latest/security/network/encryption-ipsec/#key-rotation with an `Attention!` block as done above.

**Comment by cbeneke** [comment]
Hello together,

if the fix will be limited to documenting the finding I would suggest to also include indicators that your service is running into these issues (e.g. the metric `cilium_ipsec_xfrm_error{error="state_sequence"}` increases / the XFRM state sequence number is `0xffffffff` for example on `ip xfrm state`).

**Comment by pchaigno** [comment]
@cbeneke That's a good point. We already have [a Prometheus metric to report IPsec errors](https://docs.cilium.io/en/stable/operations/metrics/#ipsec). IIRC, this particular error will be reported with type `XfrmOutStateSeqError`. 

When that metric increases, the issue is already happening however. In `cilium encrypt status`, we also report the maximum output sequence number across all states on the node as a way to see if this issue is close from happening. We could probably do the same with a new Prometheus metric. I've opened https://github.com/cilium/cilium/issues/22924 for this.

**Comment by pecigonzalo** [comment]
@pchaigno that would be great. I think still in the docs we can add more info, as @cbeneke suggested, on to what are the indicators of this issue.

**Comment by julianwiedmann** [comment]
I believe this is now superseded by the ESN support added with https://github.com/cilium/cilium/commit/7a2a18d873094be30d80e7ff3381fc986bf6cf3e.

**Comment by pchaigno** [comment]
That's correct. Sequence number overflow shouldn't happen anymore.
