### ISSUE TITLE
CI: K8sAgentPolicyTest Multi-node policy test with L7 policy using connectivity-check to check datapath

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#22749]
### Test Name

```shell
K8sAgentPolicyTest Multi-node policy test with L7 policy using connectivity-check to check datapath
```

### Failure Output

```shell
-
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-K8s-1.16-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
connectivity-check pods are not ready after timeout
Expected
    <*errors.errorString | 0xc001798de0>: {
        s: "timed out waiting for pods with filter  to be ready: 4m0s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.16-kernel-4.9/src/github.com/cilium/cilium/test/k8s/net_policies.go:894
```

### Standard Output

```shell
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 4
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 3 errors/warnings:
[cilium.bpf_metadata: map type mismatch on /sys/fs/bpf/tc/globals/cilium_ipcache: got 1, wanted 11
Policy map sync fixed errors, consider running with debug verbose = policy to get detailed dumps
Key allocation attempt failed
Cilium pods: [cilium-44rsb cilium-55qxs]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::echo-c default::pod-to-a-intra-node-proxy-egress-policy default::pod-to-a-multi-node-proxy-egress-policy default::pod-to-c-intra-node-proxy-to-proxy-policy default::pod-to-c-multi-node-proxy-to-proxy-policy 
Endpoint Policy Enforcement:
Pod                                                          Ingress   Egress
pod-to-a-intra-node-proxy-egress-policy-96b98dbb5-z44z7      false     false
pod-to-c-intra-node-proxy-ingress-policy-99978465c-wvm4m     false     false
testclient-n292v                                             false     false
pod-to-c-multi-node-proxy-to-proxy-policy-9d9cbd695-97482    false     false
echo-c-799d46bc9f-29mfq                                      false     false
testclient-crcnt                                             false     false
testds-k48h6                                                 false     false
coredns-8cfc78c54-hj947                                      false     false
echo-a-77c976f59b-xbttt                                      false     false
echo-b-5f88747484-8xp9s                                      false     false
pod-to-a-multi-node-proxy-egress-policy-599fd76758-8hslb     false     false
pod-to-c-intra-node-proxy-to-proxy-policy-8656bf7f9b-828bc   false     false
pod-to-c-multi-node-proxy-ingress-policy-7dbccb8d4b-f6v2q    false     false
test-k8s2-5b756fd6c5-qvkdz                                   false     false
testds-qwl45                                                 false     false
Cilium agent 'cilium-44rsb': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 69 Failed 0
Cilium agent 'cilium-55qxs': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 47 Failed 0
```

### Standard Error

```shell
12:16:55 STEP: Running BeforeAll block for EntireTestsuite K8sAgentPolicyTest Multi-node policy test with L7 policy
12:16:55 STEP: WaitforPods(namespace="default", filter="")
12:20:55 STEP: WaitforPods(namespace="default", filter="") => timed out waiting for pods with filter  to be ready: 4m0s timeout expired
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/3451/
- ZIP file(s): https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/3451/artifact/test_results_Cilium-PR-K8s-1.16-kernel-4.9_3451_BDD-Test-PR.zip (too big to upload)

### Anything else?

Seen on https://github.com/cilium/cilium/pull/22721

**Comment by christarazi** [comment]
```
cilium.bpf_metadata: map type mismatch on /sys/fs/bpf/tc/globals/cilium_ipcache: got 1, wanted 11
```
seems to be coming from the proxy (Envoy) and 

```
Policy map sync fixed errors, consider running with debug verbose = policy to get detailed dumps
```
indicates that the Agent's controllers for ensuring policymap state is synced, is reporting that it found missing entries.


Could there be some regression with the Envoy code recently?

cc @jrajahalme

**Comment by pchaigno** [comment]
Pretty sure this is caused by an already allocated port for one of the hostNetwork pods.

For example, https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.9/1525/testReport/Suite-k8s-1/20/K8sAgentPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/
Sysdump: 
[cilium-sysdump.7z.zip](https://github.com/cilium/cilium/files/10488471/cilium-sysdump.7z.zip)

The echo-b-host pod is failing with:
```
2023-01-22T14:05:17.348637801Z Some error occurred Error: listen EADDRINUSE: address already in use :::31000
2023-01-22T14:05:17.348646003Z     at Server.setupListenHandle [as _listen2] (node:net:1380:16)
2023-01-22T14:05:17.348648209Z     at listenInCluster (node:net:1428:12)
2023-01-22T14:05:17.348649891Z     at Server.listen (node:net:1516:7)
2023-01-22T14:05:17.348659478Z     at Function.listen (/usr/local/lib/node_modules/json-server/node_modules/express/lib/application.js:635:24)
2023-01-22T14:05:17.348663739Z     at /usr/local/lib/node_modules/json-server/lib/cli/run.js:135:20 {
2023-01-22T14:05:17.348665480Z   code: 'EADDRINUSE',
2023-01-22T14:05:17.348667302Z   errno: -98,
2023-01-22T14:05:17.348668897Z   syscall: 'listen',
2023-01-22T14:05:17.348670460Z   address: '::',
2023-01-22T14:05:17.348672048Z   port: 31000
2023-01-22T14:05:17.348673630Z }
```

**Comment by qmonnet** [comment]
[Hit](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-4.19/605/consoleFull) on https://github.com/cilium/cilium/pull/25910.

**Comment by margamanterola** [comment]
[Hit](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-4.19/93/testReport/junit/Suite-k8s-1/24/K8sAgentPolicyTest_Multi_node_policy_test_with_L7_policy_using_connectivity_check_to_check_datapath/) on https://github.com/cilium/cilium/pull/27034

**Comment by margamanterola** [comment]
As Paul mentioned, this means that there is another nodePort service that was allocated to that port. Interestingly, though, the service is not listed in the output of `cilium service list`. Does this mean that Kubernetes knows about the service, but Cilium doesn't? 

Or could it be a replication race of the echo-b service getting applied to the cluster?

**Comment by pchaigno** [comment]
> As Paul mentioned, this means that there is another nodePort service that was allocated to that port.

My comment wasn't very clear. I only meant that this test is failing because one of our hostNetwork pods is failing to allocate a port in hostns.

I don't think that already-allocated port was allocated by a service. I suspect (based on past similar flakes) that it's allocated by Cilium's proxy or one of our other components that allocate ports. It's a bit hard to say for sure because the allocated port doesn't appear in the `ss` output :confused:

**Comment by joestringer** [comment]
Hit in https://github.com/cilium/cilium/pull/28603, Conformance Ginkgo [E2E Test (1.19, f04-agent-policy-multi-node-1)](https://github.com/cilium/cilium/actions/runs/6531628408/job/17733250003#logs)

**Comment by gandro** [comment]
Also hit this in https://github.com/cilium/cilium/pull/29443 in multiple tests: https://github.com/cilium/cilium/actions/runs/7021502960/job/19103847216

**Comment by thorn3r** [comment]
Hit in https://github.com/cilium/cilium/pull/29910 on [Conformance Ginkgo E2E Test (1.27, f04-agent-policy-multi-node-1)](https://github.com/cilium/cilium/actions/runs/7478524616/job/20353699343)
