### ISSUE TITLE
Evaluate Cilium SLSA compliance

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#22740]
[SLSA](https://github.com/slsa-framework/slsa) is a framework for validating the supply chains of projects. This issue tracks evaluating and improving SLSA compliance in the Cilium tree.

**Comment by sandipanpanda** [comment]
@joestringer @aanm I can help implement https://github.com/kubernetes-sigs/tejolote, a highly configurable build executor and observer designed to generate signed [SLSA](https://slsa.dev/) provenance attestations about build runs, if you still consider this an issue.
