### ISSUE TITLE
Docs: include Transparent Encryption under Security heading

### ISSUE THREAD

**Issue by lizrice** [cilium/cilium#22751]
In the [latest version of the docs](https://docs.cilium.io/en/latest/), as part of the restructuring, the left-hand navigation includes a top-level heading of Security. Let's include Transparent Encryption as a section under this heading.  
<img width="275" alt="Screenshot 2022-12-15 at 10 33 47" src="https://user-images.githubusercontent.com/458616/207837346-5679537d-c578-4b34-99a7-6cf03410ea4f.png">

Even better, let's look at removing the Network Security page which is currently just a set of headings, and moving those headings to the left-hand navigation. 

<img width="376" alt="Screenshot 2022-12-15 at 10 34 04" src="https://user-images.githubusercontent.com/458616/207837380-98854557-f8e0-4d2c-8775-be018dcb8f85.png">

**Comment by mohit-marathe** [comment]
>Let's include Transparent Encryption as a section under this heading.

Currently the left-hand navigation is bit different from the first screenshot provided in the issue description. So I want to confirm if this is still needed.

**Comment by mohit-marathe** [comment]
>Even better, let's look at removing the Network Security page which is currently just a set of headings, and moving those headings to the left-hand navigation.

There are other pages that also contains just some headings. Do you suggest removing those as well?

**Comment by mohit-marathe** [comment]
>Let's include Transparent Encryption as a section under this heading.

Also, currently the left-hand navigation is a bit different from the screenshot provided. So I just want to confirm if this change is still needed?

**Comment by gailsuccess** [comment]
May I take this issue ?

**Comment by janvi01** [comment]
Hey @lizrice Does this issue still need to be done?

**Comment by lizrice** [comment]
The nav has changed enough that my original concern has gone away, I think we can just close this now
