### ISSUE TITLE
cilium endpoint cidr conflict

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#22770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Two node's cilium endpoint cidr same.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/6076617/208025675-226f292f-d96c-4073-be66-179d127f492c.png">

cilium config:
ipam: cluster-pool

### Cilium Version

cilium version
Client: 1.12.0 9447cd1 2022-07-19T12:22:00+02:00 go version go1.18.4 linux/amd64
Daemon: 1.12.0 9447cd1 2022-07-19T12:22:00+02:00 go version go1.18.4 linux/amd64

### Kernel Version

uname -a
Linux 10-10-66-25 4.19.113-300.el7.x86_64 #1 SMP Mon Mar 30 21:50:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

Error: unknown command "sysdump" for "cilium"

### Relevant log output

```shell
None
```

### Anything else?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
Can you try with the latest v1.12.5?

**Comment by llhhbc** [comment]
@christarazi Is this buf fixed?

**Comment by christarazi** [comment]
Typically, a .0 release is not generally stable and we recommend users to move to more stable patch releases when possible. As for this bug, I'm not sure if there's a fix for it. It's possible that there is.

What is the pod CIDR of the K8s Node and CiliumNode that has the incorrect endoint CIDR in your screenshot?

**Comment by llhhbc** [comment]
@christarazi   The problem I want to say is that the cidr allocated by node 10-10-66-25 and 10-10-66-26 are duplicated, which will cause pod network exceptions

**Comment by christarazi** [comment]
Can you share the resources mentioned in https://github.com/cilium/cilium/issues/22770#issuecomment-1371254917?
