### ISSUE TITLE
Helm Chart: certmanager requires user specify .Values.clustermesh.apiserver.tls.auto.certManagerIssuerRef

### ISSUE THREAD

**Issue by wigust** [cilium/cilium#22784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Helm Chart validation for clustermesh.apiserver.tls.auto.certManagerIssuerRef is broken.

Running `helm template --values val.yaml ./.` fails on `1.12.4` and `origin/master` (d8c7d93ff72d7737d626f3940b01acab49161c5a) because of validation in install/kubernetes/cilium/templates/validate.yaml:

``` 
{{- if and (or .Values.externalWorkloads.enabled .Values.clustermesh.useAPIServer) .Values.clustermesh.apiserver.tls.auto.enabled (eq .Values.clustermesh.apiserver.tls.auto.method "certmanager") }}
  {{- if not .Values.clustermesh.apiserver.tls.auto.certManagerIssuerRef }}
    {{ fail "ClusterMesh TLS certgen method=certmanager requires user specify .Values.clustermesh.apiserver.tls.auto.certManagerIssuerRef" }}
  {{- end }}  
{{- end }}
```

val.yaml:
```
rollOutCiliumPods: true

cni:
  exclusive: false
  debug:
    enabled: true

prometheus:
  enabled: true

operator:
  rollOutPods: true
  prometheus:
    enabled: true

kubeProxyReplacement: "strict"

k8sServiceHost: "172.16.102.137"
k8sServicePort: "6443"

bpf:
  masquerade: true

bgp:
  enabled: false
  announce:
    loadbalancerIP: true

ipam:
  mode: "kubernetes"

bgpControlPlane:
  enabled: true

ingressController:
  enabled: true

hubble:
  relay:
    rollOutPods: true
    enabled: true
  ui:
    rollOutPods: true
    enabled: true

bandwidthManager:
  enabled: true

cluster:
  name: "cluster2"
  id: 2

clustermesh:
  name: "cluster2"
  config:
    enable: true
  clusters: ["cluster1", "cluster2"]
  useAPIServer: true
  apiserver:
    tls:
      auto:
        method: "certmanager"
```

### Cilium Version

1.12.4

### Kernel Version

5.15.78

### Kubernetes Version

1.25.4

### Relevant log output

```shell
helm template --values val.yaml ./.

ClusterMesh TLS certgen method=certmanager requires user specify .Values.clustermesh.apiserver.tls.auto.certManagerIssuerRef
```

### Anything else?

According to the default `values.yaml` documentation string the user does not need to provide clustermesh.apiserver.tls.auto.certManagerIssuerRef in which case it will be generated.

https://github.com/cilium/cilium/blob/d8c7d93ff72d7737d626f3940b01acab49161c5a/install/kubernetes/cilium/values.yaml#L929-L936

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shunpoco** [comment]
I caught the same issue, so I made a PR to fix this problem.
@wigust thank you for your issuing!
