### ISSUE TITLE
Update Ingress and Gateway API docs to indicate that you must have the l7 proxy enabled

### ISSUE THREAD

**Issue by youngnick** [cilium/cilium#22788]
Both Ingress and Gateway API support require the layer 7 proxy to be enabled for them to work, but there are currently some installs that require explicitly disabling the layer 7 proxy.

This issue covers putting some disclaimers on the Ingress and Gateway API docs that make it clear that the l7 proxy must be enabled for the feature to work.

Split out from #22698.

**Comment by kayceeDev** [comment]
@youngnick I will like to pick up this issue. Please assign me.
