### ISSUE TITLE
pmtu can be problematic in Kubernetes hostport mode

### ISSUE THREAD

**Issue by lipangeng** [cilium/cilium#22783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

cilium set enable-pmtu-discovery is true,kubeProxyReplacement: "strict",

network: 10.5.32.67(curl) -> 10.5.241.52 (wireguard)-> Internet -> ax86u -> 10.10.1.51(Server)(Kubernetes hostport 443/80)

1.TCP channels can be established, but HTTPS cannot be established. After Client hello is sent, no response is received. But the http protocol is completely normal.
2.Using tcpdump monitoring, we know that interface eth0 of 10.10.1.51 and interface br0 of ax86u can receive the returned content. Interface eth0 of 10.5.241.52 is not received.
3.If the pod ip address is used, https can be accessed normally.
4.There is some Code: 4 (Fragmentation needed)
[tcpdump_caps.zip](https://github.com/cilium/cilium/files/10253371/tcpdump_caps.zip)

Pictures-----

HTTPS 10.10.1.51:443:
![图片](https://user-images.githubusercontent.com/7782635/208286938-6d179ecc-25c8-4920-86d2-de1593a3767d.png)

HTTPS 10.1.0.144:443(pod ip):
<img width="897" alt="图片" src="https://user-images.githubusercontent.com/7782635/208286977-d462718c-09bd-4ac5-9f1e-573113115294.png">

HTTP: 10.10.1.51:80

![图片](https://user-images.githubusercontent.com/7782635/208287004-7c337ede-20f2-4521-a3bb-dbbbec838714.png)

ICMP:
<img width="1285" alt="图片" src="https://user-images.githubusercontent.com/7782635/208287090-f22c9176-b55e-4883-b208-baf29f722ef5.png">

### Cilium Version

v1.13.0-rc3

### Kernel Version

5.10.0-19-amd64

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

https://ilemontech-cache.oss-cn-beijing.aliyuncs.com/temporary/cilium-sysdump-20221218-150119.zip

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
This feature was contributed by @nnbu in https://github.com/cilium/cilium/pull/21825. Maybe they can help here?
