### ISSUE TITLE
Add something to installs to try to prevent enabling Ingress if l7 proxy is disabled

### ISSUE THREAD

**Issue by youngnick** [cilium/cilium#22789]
Both Ingress and Gateway API support require the layer 7 proxy to be enabled for them to work, but there are currently some installs that require explicitly disabling the layer 7 proxy.

This issue covers adding logic to `cilium install` and the Helm chart that will not allow both l7 proxy to be disabled and Ingress support to be enabled, so that the install will fail.

Split out from #22698.

**Comment by aanm** [comment]
@Vishal-Chdhry any update on it?

**Comment by Vishal-Chdhry** [comment]
No sir, I am sorry I got a little busy in something else, I am unassigning myself
