### ISSUE TITLE
CI: Investigate GKE + IPsec failure with 1.24.7-gke and remove workaround

### ISSUE THREAD

**Issue by joamaki** [cilium/cilium#22808]
With GKE cluster version 1.24.7-gke the encryption connectivity test started failing (https://github.com/cilium/cilium/actions/runs/3738583649). Downgrading to 1.24.5-gke seems to solve the issue (https://github.com/cilium/cilium/pull/22798). 

Investigate why the new version causes reliable test failure, fix the issue and remove the pin.

**Comment by pchaigno** [comment]
Failures seem to always happen in the IPsec section, so it's either related to IPsec or caused by the uninstall/reinstall we perform in between the two sections.

Also note the k8s change may come with COS and kernel changes so it may not be specific to k8s v1.24.7.

**Comment by pchaigno** [comment]
@brlbil Do we need to update this issue to actually mention the IPsec aspect, and unassign @nbusseneau?
