### ISSUE TITLE
CFP: Cilium support over multiple interfaces 

### ISSUE THREAD

**Issue by VP-Samespace** [cilium/cilium#22809]
## Cilium Feature Proposal

Cilium Version : 1.12.2

**Is your feature request related to a problem?**

We have two routers connected with one host on two separate physical interfaces. Between the router & host we are using bgp unnumbered for routing.
On the host we have configured ip address on loopback interface and have not assigned IPs to the two physical interfaces as they use BGP unnumbered for peering.
We observe that Cilium binds to only one physical interface due to which we can't use the other one for failover/load balancing. 

**Describe the feature you'd like**

We observe that Cilium binds to only one physical interface due to which we can't use the other one for failover/load balancing. Do we have any plans to support this setup in the future?

**Describe your proposed solution**

This is similar to the feature request: https://github.com/cilium/cilium/issues/22132

**Comment by brb** [comment]
> We observe that Cilium binds to only one physical interface

@VP-Samespace Thanks for the issue. Are you saying that Cilium binds a BPF program to only one physical iface? If yes, have you tried specifying `--devices`?

**Comment by VP-Samespace** [comment]
@brb I appreciate your suggestion. We have tried configuring multiple devices based on your recommendations, and it was successful.
