### ISSUE TITLE
CFP: Cilium Helm Chart depend on `prometheus-operator-crds` if `serviceMonitors` are enabled

### ISSUE THREAD

**Issue by jcpunk** [cilium/cilium#22816]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

When installing Cilium via helm with the serviceMonitors enabled, kubernetes correctly notes the missing CRD resources.

**Describe the feature you'd like**

Helm's dependency resolution can be used to make this transparent.

**(Optional) Describe your proposed solution**

With the merge of https://github.com/prometheus-community/helm-charts/pull/2697 the prometheus folks are providing a chart that only contains the CRDs.  Adding this as an optional dependency to the Cilium Helm chart when serviceMonitors are requested would be a clean way to get these loaded.

**Comment by Jean-Daniel** [comment]
When installing Cilium (or any other component), I don't expect it to install CRDs that it does not own, especially in a transparent way.

The current state where helm failed if the monitoring CRDs are not installed should remain the default IMHO.

**Comment by jcpunk** [comment]
That is a workable response.  Perhaps adding a link in the documentation to point to the CRD chart would be sufficient?

**Comment by gandro** [comment]
I agree that Cilium should not install CRDs it does not own. But the documentation can surely be improved.

I think the following is currently documentation we have `serviceMonitors`, and it does mention that the CRDs need to be installed first:

https://github.com/cilium/cilium/blob/19f2ed152a721520a286bac1ea5f62751f6b513a/install/kubernetes/cilium/values.yaml#L846-L848

I do wonder however if we could somehow detect that in Helm (e.g. in `install/kubernetes/cilium/values.yaml`) and print a more human-readable message? In addition, we could also consider adding a paragraph in the actual `docs.cilium.io` as well (e.g. under Monitoring & Metrics).
