### ISSUE TITLE
Makefile: add a target for automating the release process

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#2282]
- [ ] Update the Dockerfiles and ask user to commit
- [x] Cherry picking commits for backports
- [ ] Check common mistakes using the (00-* tests)

**Comment by aalemayhu** [comment]
@tgraf since you have done the release so often please share some of the steps that might fit here. Thanks.

**Comment by borkmann** [comment]
With backporting-hat on this week, I did some semi-automation for backporting in #2283.

**Comment by tgraf** [comment]
Process has been documented and automated to a large extend:
http://docs.cilium.io/en/v1.1/contributing/#release-management
