### ISSUE TITLE
CFP: validate Helm chart values with JSON schemas

### ISSUE THREAD

**Issue by nbusseneau** [cilium/cilium#22831]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

Problem: it is possible to provide invalid / incoherent values to the Helm chart, because there is no input validation.

**Describe the feature you'd like**

It would be ideal if the Helm values could be validated against the Helm chart such that no invalid / incoherent values are provided.

In a first step, the validation would need to be configured such that only allowed values may be set on fields with constraints on acceptable values.

In a second step, the validation could be improved such that only coherent sets of values are allowed (i.e. when setting one value for a field imposes further constraints on the acceptable values for another field).

**(Optional) Describe your proposed solution**

Helm v3 supports providing JSON schemas to validate Helm values:

- https://helm.sh/docs/topics/charts/#schema-files
- https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/

I think we could leverage this to do the above.

**Comment by nbusseneau** [comment]
Naive first idea: auto-generate a full schema via CI tooling on every change (kinda like we do with documentation changes), and then find a way to mix in targeted constraints (e.g. using something like CUE) in order to impose constraints on acceptable values.

**Comment by nbusseneau** [comment]
Bad bot.

**Comment by ubergesundheit** [comment]
A good (although unmaintained) candidate for helm schema generation is https://github.com/karuppiah7890/helm-schema-gen

To get a feeling for the quality of the helm schema I generated a schema using the helm plugin mentioned above.

The generated schema contains `"type": null` for any value set to `null` or `~` in the `values.yaml` file. IMO these need fixing before a values schema can be introduced to make maintenance of the schema bearable.

If you want, I could start working on this
