### ISSUE TITLE
Fail to compile with clang 14.x

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#22834]
## Description

In master branch at the time of writing, the compilation is failed due to below error if clang version is 14.0. As highlighted by Yutaro, there is no issue with clang 10.x.

Mostly, it's due to the recent commit https://github.com/cilium/cilium/commit/a246aa0ce4f5879219069eb6055ce022f346d280 (thanks to Julian)

This issue is for tracking purpose of long term resolution, which could be:

- Fix issue with clang 10+, or
- Pin the clang version (mainly in docs) to only 10.x.x

```bash
$ clang --version          
clang version 14.0.5 (Fedora 14.0.5-2.fc36)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ make -j $(nproc) build
...
error: lib/drop.h:114:3: in function tail_ipv6_policy i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:114:3: in function tail_ipv6_to_endpoint i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:114:3: in function tail_ipv4_policy i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:114:3: in function tail_ipv4_to_endpoint i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:114:3: in function handle_policy i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:114:3: in function cil_to_container i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.
```

**Comment by julianwiedmann** [comment]
@jrajahalme do you think we missed an aspect in the [new build check](https://github.com/cilium/cilium/blob/19f2ed152a721520a286bac1ea5f62751f6b513a/bpf/lib/drop.h#L111)? My guess is that new clang stumbles over the `LXC_ID` templating ...

Is this sanity check important, or should we consider backing it out?

**Comment by anfernee** [comment]
I have the same issue. `clang-13` also works. It happens in `clang-14+`.

**Comment by sayboras** [comment]
Downgrading clang version in some distros (e.g. fedora 36+) might not be easy task. So for the time being, I have added the below PR to provide alternative option for local development.

https://github.com/cilium/cilium/pull/22856

**Comment by jspaleta** [comment]
oof, just chiming in. Definitely hitting this on Fedora 37 bare-metal dev environment using clang 15.0.6. Rolling back to v1.12.5 cilium release tag and compiling works as expected.

**Comment by optimistyzy** [comment]
> ```shell
> 
> Thread model: posix
> ```

Have the same problem with Clang-14 in ubuntu:

clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by sayboras** [comment]
The validation check is relaxed for clang 14+, so the master branch should work for clang 10+ now. 

There is one pending item to check why it didn't work for clang 14+, so we can keep this issue open.

**Comment by dylandreimerink** [comment]
Adding another data point, hitting the same issue with Clang 13 at the current master which includes the above mentioned commits. 

```
clang version 13.0.0 (Fedora 13.0.0-3.fc35)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
error: lib/drop.h:113:3: in function tail_ipv6_policy i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:113:3: in function tail_ipv6_to_endpoint i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:113:3: in function tail_ipv4_policy i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:113:3: in function tail_ipv4_to_endpoint i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:113:3: in function handle_policy i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

error: lib/drop.h:113:3: in function cil_to_container i32 (%struct.__sk_buff*): A call to built-in function 'abort' is not supported.

make[2]: *** [Makefile:302: bpf_lxc.o] Error 1
make[2]: Leaving directory '/home/dylan/go/src/github.com/cilium/cilium/bpf'
make[1]: *** [Makefile:121: bpf] Error 2
make[1]: Leaving directory '/home/dylan/go/src/github.com/cilium/cilium'
make: *** [Makefile:37: cilium-build] Error 2
```

**Comment by aanm** [comment]
once it's fixed revert https://github.com/cilium/cilium/pull/27829

**Comment by sayboras** [comment]
This should be fixed now, closing the issue.

```bash
$ clang --version  
clang version 16.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ make -j $(nproc) build
...
```
