### ISSUE TITLE
CFP: Improve `firstGlobalAddr` IP selection

### ISSUE THREAD

**Issue by akhilles** [cilium/cilium#22853]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

Floating IP is being chosen as NodePort IP instead of primary IP on additional host interfaces.
Related to https://github.com/cilium/cilium/issues/15332, https://github.com/cilium/cilium/pull/15333. 

**(Optional) Describe your proposed solution**

Would like to implement @pchaigno's proposal in https://github.com/cilium/cilium/pull/15333#issuecomment-804840937:

- [ ] Fix `netlink.AddrList` [upstream](https://github.com/vishvananda/netlink/blob/c21bda41e995cbc0b91d34bec008a48f05f14d8b/addr_linux.go#L177) to sort by interface indexes (or create a new function).
- [ ] Remove the sort on addresses in our `firstGlobalAddr` function.
- [ ] Extend `firstGlobalAddr` match [the kernel's selection](https://elixir.bootlin.com/linux/v5.11.8/source/net/ipv4/devinet.c#L1318) and skip secondary addresses.

**Comment by akhilles** [comment]
With `Addr.LinkIndex` (https://github.com/vishvananda/netlink/pull/543) now being available, I don't think upstream behavior of `netlink.AddrList` needs to be changed, we can just stable sort the results by `LinkIndex`.

**Comment by pchaigno** [comment]
> Floating IP is being chosen as NodePort IP instead of primary IP on additional host interfaces.

And this "floating IP" is a secondary IP?
