### ISSUE TITLE
Fedora CoreOS 37.20221127.3.0, Failed to upgrade cilium to v1.12.5

### ISSUE THREAD

**Issue by DebakelOrakel** [cilium/cilium#22868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I was unable to upgrade from v1.12.2 to v1.12.5 due to an issue with iptables.  
Reverting to v1.12.2 was also not possible, due to the same issue.  

In the end I was able to revert to v1.11.5 to get networking up again.

### Cilium Version

```
v1.12.x

```
### Kernel Version

```
OS-IMAGE: Fedora CoreOS 37.20221127.3.0
KERNEL-VERSION: 6.0.9-300.fc37.x86_64
```

### Kubernetes Version

```
VERSION: v1.25.4+k3s1
CONTAINER-RUNTIME: containerd://1.6.8-k3s1
```

### Relevant log output

```shell
level=warning msg="Failed to install iptables rules" error="unable to run 'iptables -t filter -S' iptables command: exit status 1 stderr=\"iptables v1.8.4 (nf_tables): table `filter' is incompatible, use 'nft' tool.\\n\\n\"" subsys=iptables
level=warning msg="Failed to install iptables rules" error="unable to run 'iptables -t filter -S' iptables command: exit status 1 stderr=\"iptables v1.8.4 (nf_tables): table `filter' is incompatible, use 'nft' tool.\\n\\n\"" subsys=iptables
```

### Anything else?

iptables version:
```
# iptables --version
iptables v1.8.8 (nf_tables)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jibi** [comment]
Hey @DebakelOrakel :wave: thanks for the report!

Could you share some more information (perhaps a sysdump) on the environment that you are running Cilium on please?

**Comment by DebakelOrakel** [comment]
Sure, the sysdump is with cilium v1.11.5.
If you need one with v1.12.x I can do that later this week.
https://drive.google.com/file/d/1WstOm4JM3Rq05CmXW18Y98zTcF7bVTj1/view?usp=share_link

**Comment by jibi** [comment]
>If you need one with v1.12.x I can do that later this week.

Yes please, I think a sysdump based on v1.12.x could give us some more info on what's going on :+1:

**Comment by pchaigno** [comment]
Could you also share the kernel config on this node?

**Comment by sfxworks** [comment]
In my case it was some nftable rules I had. They were conflicting with whatever cilium was trying. I didn't notice it until the node restarted and the rules were applied before cilium restarted. 

```config
# Create the nat table
table nat {
        # Create the postrouting chain
        chain postrouting {
                # Set the type and hook for the chain
                type nat hook postrouting priority 100;

                # Add a rule to the chain
                ip saddr 192.168.8.0/23 oif eno1 snat to public-ip
        }
}
```

**Comment by DebakelOrakel** [comment]
The nodes I use where freshly installed with this ignition config:
```
{
  "ignition": {
    "version": "3.3.0"
  },
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "just a public key signature"
        ]
      }
    ]
  },
  "storage": {
    "files": [
      {
        "overwrite": true,
        "path": "/etc/selinux/config",
        "contents": {
          "compression": "",
          "source": "data:,SELINUX%3Dpermissive%0ASELINUXTYPE%3Dtargeted%0A"
        }
      },
      {
        "path": "/etc/sysctl.d/90-kubelet.conf",
        "contents": {
          "compression": "",
          "source": "data:,vm.panic_on_oom%3D0%0Avm.overcommit_memory%3D1%0Akernel.panic%3D10%0Akernel.panic_on_oops%3D1%0Akernel.keys.root_maxbytes%3D25000000%0A"
        }
      },
      {
        "path": "/etc/zincati/config.d/55-updates-strategy.toml",
        "contents": {
          "compression": "",
          "source": "data:;base64,W3VwZGF0ZXNdCnN0cmF0ZWd5ID0gImZsZWV0X2xvY2siClt1cGRhdGVzLmZsZWV0X2xvY2tdCmJhc2VfdXJsID0gImh0dHA6Ly8xMC40My4wLjExLyIK"
        }
      }
    ],
    "filesystems": [
      {
        "device": "/dev/mapper/root",
        "format": "xfs",
        "label": "root",
        "wipeFilesystem": true
      }
    ],
    "luks": [
      {
        "clevis": {
          "tpm2": true
        },
        "device": "/dev/disk/by-partlabel/root",
        "label": "luks-root",
        "name": "root",
        "wipeVolume": true
      }
    ]
  }
}
```

I cant say definetly what image I installed originally, it auto updates using zincati service.
It probably was a fcos 36.x version from Oct/2, thats when I installed the thing.

Also originally I installed cilium v1.12.2, without any problems.

@pchaigno How would I get to the kernel config?

**Comment by pchaigno** [comment]
> Also originally I installed cilium v1.12.2, without any problems.

If you are able to bisect the specific patch release that introduced the regression, it could probably help guess which commit is to blame.

> How would I get to the kernel config?

I'd expect it to be in `/proc/config.gz`.

**Comment by DebakelOrakel** [comment]
OK, I updated again to v1.12.5:
```
❯ k -n kube-system get po -owide
NAME                               READY   STATUS    RESTARTS     AGE   IP             NODE         NOMINATED NODE   READINESS GATES
cilium-2j7th                       0/1     Running   0            36s   10.10.10.102   node-spock   <none>           <none>
cilium-nklzd                       0/1     Running   0            37s   10.10.10.103   node-mccoy   <none>           <none>
cilium-operator-7d64b5b85d-dpqpz   1/1     Running   0            37s   10.10.10.103   node-mccoy   <none>           <none>
cilium-v72lb                       1/1     Running   1 (8d ago)   12d   10.10.10.101   node-kirk    <none>           <none>
```
The os updated since my last atempt, it is now:
```
OS-IMAGE: Fedora CoreOS 37.20221211.3.0
KERNEL-VERSION: 6.0.12-300.fc37.x86_64
```
```
$ iptables --version
iptables v1.8.8 (nf_tables)
```
Sysdump: https://drive.google.com/file/d/1QaBDel20V7xrCzgoYBM2DcIw6ntHbQIC/view?usp=share_link  
(This is from admits update, 2 cilium agents and the operator have been updated, it got rolled back as the agents failed to report ready)

Sadly no `/proc/config.gz` or the like exists.

**Comment by jibi** [comment]
This message:
```
level=warning msg="Failed to install iptables rules" error="unable to run 'iptables -t filter -S' iptables command: exit status 1 stderr=\"iptables v1.8.4 (nf_tables): table `filter' is incompatible, use 'nft' tool.\\n\\n\"" subsys=iptables
```

might just be telling us that the legacy iptables tables are not there anymore, which would be in line with their release note:
https://docs.fedoraproject.org/en-US/fedora-coreos/major-changes/#_moving_to_iptables_nft

I'm downloading a coreos virtualbox image to run some more tests
