### ISSUE TITLE
[Questions] How to enable conntrack local?

### ISSUE THREAD

**Issue by nejisama** [cilium/cilium#22876]
How to enable conntrack local in cilium? 
I am cannot find the config for it, and I found a code in daemon/cmd/daemon_main.go, always set the conntrack local to false.
```
option.Config.Opts.SetBool(option.ConntrackLocal, false)
```
so the conntrack local cannot be enabled except I modify the code?

**Comment by pchaigno** [comment]
I believe you can enable this feature by running `cilium config ConntrackLocal=$state` inside the Cilium agent pods. Note however that this feature hasn't been maintained in a while (hence the lack of documentation) so it's know to have bugs. Where did you read about it?
