### ISSUE TITLE
[Question] How to check complexity issue continuously

### ISSUE THREAD

**Issue by Jaeyo** [cilium/cilium#22885]
i'm not familar with eBPF.
recently, i found out that there's an instruction limit in eBPF, which often causes complexity issues in Cilium.
if what i understand is correct, the number of instructions of cilum may vary depending on the flag of Cilium and kernel version.
therefore, event the most recent version of Cilium that worked properly in recent version of kernel can cause complexity issue when a new version of the kernel comes out.
if what i understand is correct, is there a way to check if the latest version of Cilium can run safely when the kernel is upgraded?
or is there any automated test being carried out for this?

**Comment by anfernee** [comment]
There is a verifier test defined here: 

https://github.com/cilium/cilium/blob/fcf2b7ad1c47cc7309e752eb087ecfbda7ff8a6e/test/k8s/verifier.go#L64-L74

AFAIK, it doesn't all the kernels in CI/CD, but in theory you can run this test on the kernel you want to test.

**Comment by Jaeyo** [comment]
thanks for response!
