### ISSUE TITLE
CiliumNetworkPolicy FQDN egress not working

### ISSUE THREAD

**Issue by rewanthtammana** [cilium/cilium#22889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I was trying to implement the FQDN feature of `CiliumNetworkPolicy` but it's not working for some reason. I tried many things but for the sake of reproduction, let's use the [blog from cilium](https://cilium.io/blog/2018/09/19/kubernetes-network-policies/) team directly.

### Reproduction steps

1. Create a kind cluster
    ```bash
    curl -LO https://raw.githubusercontent.com/cilium/cilium/1.12.5/Documentation/gettingstarted/kind-config.yaml
    kind create cluster --config=kind-config.yaml
    ```
2. Create deployments & services
    ```bash
    kubectl create ns empire
    kubectl apply -n empire -f https://raw.githubusercontent.com/cilium/cilium/v1.2.2/examples/minikube/http-sw-app.yaml
    ```
3. Apply cilium network policy allowing dns resolution
    ```bash
    cat <<EOF | kubectl apply -n empire -f -
    apiVersion: "cilium.io/v2"
    kind: CiliumNetworkPolicy
    metadata:
      name: "allow-within-namespace"
    specs:
      - endpointSelector:
          matchLabels: {}
        egress:
        - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": empire
        ingress:
        - fromEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": empire
      - endpointSelector:
          matchLabels: {}
        egress:
        - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": kube-system
              "k8s:k8s-app": kube-dns
    EOF
    ```
4. Test for dns connectivity & it's successful
    ```bash
    kubectl exec -it tiefighter -- curl deathstar.empire.svc.cluster.local/v1
    ```
5. Add an additional rule for outbound traffic to cilium.io
    ```bash
    cat <<EOF | kubectl apply -n empire -f -
    apiVersion: "cilium.io/v2"
    kind: CiliumNetworkPolicy
    metadata:
      name: "allow-within-namespace"
    specs:
      - endpointSelector:
          matchLabels: {}
        egress:
        - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": empire
        ingress:
        - fromEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": empire
      - endpointSelector:
          matchLabels: {}
        egress:
        - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": kube-system
              "k8s:k8s-app": kube-dns
      - endpointSelector:
          matchLabels: {}
        egress:
        - toFQDNs:
            - matchName: "cilium.io"
    EOF
    ```
6. Test for connectivity
    6.1 Test for internal DNS resolution - works
        ```
        kubectl exec -it tiefighter -- curl deathstar.empire.svc.cluster.local/v1
        ```
    6.2 Test for external DNS resolution - works
        ```
        kubectl exec -it tiefighter -- nslookup cilium.io 8.8.8.8
        ```
    6.3 Test to curl the endpoint - doesn't work
        ```
        kubectl exec -it tiefighter -- curl cilium.io
        ```
7. For some reason, cilium fqdn list is empty. Not sure if that's something related to this issue but nevertheless, I tried it.
    ```bash
    POD_NAME=$(kubectl get po -n kube-system -l k8s-app=cilium -ojsonpath='{@.items[0].metadata.name}')
    kubectl exec -n kube-system -it $POD_NAME -- cilium fqdn names
    ```

Tried debugging a with `cilium observe`, `cilium endpoint list`, etc but no information.

### Cilium Version

1.12.2

### Kernel Version

Darwin laptop 21.6.0 Darwin Kernel Version 21.6.0: root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64

### Kubernetes Version

1.25

### Sysdump

[cilium-sysdump-20221229-094847.zip](https://github.com/cilium/cilium/files/10317792/cilium-sysdump-20221229-094847.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kahirokunn** [comment]
I have the same issue.

**Comment by rewanthtammana** [comment]
@squeed @gandro @tommyp1ckles

**Comment by pchaigno** [comment]
@rewanthtammana Please don't ping arbitrary people to get attention. You've opened this issue in between Christmas and New Year so a bit of delay is only expected.

> I tried many things but for the sake of reproduction, let's use the [blog from cilium](https://cilium.io/blog/2018/09/19/kubernetes-network-policies/) team directly.

Whoah, that blog post is 4+ years old. Cilium was a baby back then :smile_cat: 

Have you tried following [the official guide for FQDN policies](https://docs.cilium.io/en/stable/gettingstarted/dns/)? In particular, the policy you cited is missing the `dns` rule (which I'm guessing wasn't required back then) so that won't work.

**Comment by rewanthtammana** [comment]
I also tried the official guide for FQDN policies but still it doesn't work! Attaching screenshot for reference

![image](https://user-images.githubusercontent.com/22347290/210704439-43e378a3-a3b0-4747-8126-d36b1da51b3d.png)

**Comment by pchaigno** [comment]
Could you share a sysdump with that last policy loaded? 🙏

**Comment by rewanthtammana** [comment]
PFA sysdump 
[cilium-sysdump-20230106-121312.zip](https://github.com/cilium/cilium/files/10358603/cilium-sysdump-20230106-121312.zip)

**Comment by rewanthtammana** [comment]
Nothing I can think of

**Comment by pchaigno** [comment]
Are you able to establish a connection over 8472/udp between two nodes in the cluster with e.g. netcat?

**Comment by rewanthtammana** [comment]
Yes, it's working.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/22347290/211000510-b9f9f81b-f55e-4c8b-b040-438a4c1bdcbc.png">

**Comment by pchaigno** [comment]
How did you install Cilium?

Is connectivity working for any pod-to-pod across nodes? Maybe it's just the health checks that are failing :thinking:

**Comment by rewanthtammana** [comment]
It's been a while, so I don't remember exactly but I'm presuming I installed cilium with helm charts.

I created a new pod with labels different from the ciliumnetworkpolicy selectors & the connection seem to be working.

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/22347290/211024083-b9717586-8d23-43ba-aab5-bc6036a65a58.png">

**Comment by rewanthtammana** [comment]
> Are the two pods on different nodes? If you try to resolve domain names from that client pod multiple times, does it always work?

Yes, they are on different nodes. The `nginx` pod I created is on `kubernetes1.25-worker`. The debug container I created for testing is on `kubernetes1.25-worker3`. The `mediabot` with ciliumnetworkpolicy is on `kubernetes1.25-worker2`.

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/22347290/211043269-acdc036a-eed3-4a43-b20c-99e4b0eabdc0.png">

> `cilium-health` status in the Cilium agent pods

I exec into one of the cilium pods in kube-system namespace & I see some endpoint connectivity errors here for control plane & two worker nodes. For third worker node, it's okay. 

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/22347290/211043728-10d1c63d-b0e3-4bc8-b9ff-2411a53d0abe.png">

**Comment by pchaigno** [comment]
Sorry, missed your answer here. Looking at the health checks here, it looks like all pod-to-pod connectivity across nodes is affected. So this is likely not specific to the FQDN policies. I would check that there are no firewall rules blocking VXLAN. The required ports are documented at https://docs.cilium.io/en/stable/operations/system_requirements/.

**Comment by jithunarayanan** [comment]
You must enable DNS proxy in the rule. Without the DNS section, it will not work. Refer to the sample manifest below.

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
name: rule10
spec:
endpointSelector:
matchLabels:
org: alliance
class: xwing
egress:
- toEndpoints:
- matchLabels:
io.kubernetes.pod.namespace: kube-system
k8s-app: kube-dns
toPorts:
- ports:
- port: "53"
protocol: UDP
rules:
dns:
- matchPattern: ""
- toFQDNs:
- matchPattern: ".amazon.com"

Please ensure the indentation is correct as well.
