### ISSUE TITLE
CFP: Transparent encryption for KPR traffic

### ISSUE THREAD

**Issue by sathieu** [cilium/cilium#22897]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

no.

**Describe the feature you'd like**

In current [limitations](https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/#limitations):

> Cilium’s eBPF kube-proxy replacement currently cannot be used with [Transparent Encryption](https://docs.cilium.io/en/stable/gettingstarted/encryption/#gsg-encryption).

We need to use kube-proxy replacement with Transparent Encryption.

**Comment by brb** [comment]
@sathieu Thanks for the issue. Is your feature request about encrypting KPR traffic, or running KPR with pod-to-pod encryption? The former for WireGuard is going to be addressed by https://github.com/cilium/cilium/pull/19401. While the latter is possible today with WireGuard, just that that doc section is misleading (it should be addressed by https://github.com/cilium/cilium/pull/22775). Unfortunately, neither applies to IPSec.

**Comment by sathieu** [comment]
Thanks @brb. We can close #22897, once https://github.com/cilium/cilium/pull/19401 is merged.
