### ISSUE TITLE
Inconsistency between API documentation and `pkg/endpoint/id.go`

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2289]
https://github.com/cilium/cilium/blob/e0ac001cca363df7bb420e067ed5f2f5ae9abaa3/api/v1/openapi.yaml#L670

https://github.com/cilium/cilium/blob/e0ac001cca363df7bb420e067ed5f2f5ae9abaa3/pkg/endpoint/id.go#L31

Doesn't look like docker endpoint prefixes are properly documented.

**Comment by tgraf** [comment]
This is a bug in the API spec and needs to be fixed

**Comment by joestringer** [comment]
I'll self-assign so it doesn't get lost.
