### ISSUE TITLE
Cannot mount a NFS when running a CI VM instance locally

### ISSUE THREAD

**Issue by Shunpoco** [cilium/cilium#22901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to create a vagrant instance using these commands:
```console
$ cd test
$ K8S_VERSION="1.25" ./vagrant-local-start-runtime.sh
```
But I caught the error during the creation:
```console
==> k8s1-1.25: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -o vers=3,nolock 192.168.58.1:/home/shunpoco/Documents/oss/cilium /home/vagrant/go/src/github.com/cilium/cilium
Stdout from the command:
Stderr from the command:
mount.nfs: Connection timed out
```

I found that the error was caused because I hadn't set my iptables properly.
By default, this vagrant up tries to mount NFS using `192.168.58.1#{i}` (please see [here](https://github.com/cilium/cilium/blob/master/test/Vagrantfile#L149-L152)), so I had to allow Vagrant to use these IP addresses.
When I set the new record on my iptables using the following command, the creation finished successfully.
```console
sudo iptables -I INPUT -s 192.168.58.0/24 -j ACCEPT
```

### My proposal
I think that we should add a warning in the shell script like [./contrib/vagrant/start.sh's warning](https://github.com/cilium/cilium/blob/master/contrib/vagrant/start.sh#L448-L450):
```console
    echo "# NFS enabled. don't forget to enable these ports on your host"
    echo "# before starting the VMs in order to have nfs working"
    echo "# iptables -I INPUT -s 192.168.56.0/24 -j ACCEPT"
```
Or, at least, we should add a such warning to [our document](https://docs.cilium.io/en/v1.12/contributing/development/dev_setup/#launch-ci-vms).

### Cilium Version

master branch

### Kernel Version

5.10.32-051032-generic

### Kubernetes Version

1.25

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shunpoco** [comment]
If the proposal is reasonable for you, I'd like to make a PR.

**Comment by pchaigno** [comment]
> I think that we should add a warning in the shell script like [./contrib/vagrant/start.sh's warning](https://github.com/cilium/cilium/blob/master/contrib/vagrant/start.sh#L448-L450):

That makes sense to me.
