### ISSUE TITLE
CIDRSet not working in policy for pod-to-pod traffic

### ISSUE THREAD

**Issue by arrowfeng** [cilium/cilium#22916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have two pods, one client with label app=client, other server with label app=server. 
![image](https://user-images.githubusercontent.com/20623365/210390524-f6bcff38-3a30-422b-b189-5d3288beaddb.png)

I have configured the following policy, but I can't ping the server (10.0.0.145).
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "cidr-rule"
spec:
  endpointSelector:
    matchLabels:
      app: client
  egress:
  - toCIDRSet:
    - cidr: 10.0.0.145/32
```
cilium config 
![image](https://user-images.githubusercontent.com/20623365/210390216-48304c88-e11d-400b-b204-e9a745edddc4.png)

cilium monitor
![image](https://user-images.githubusercontent.com/20623365/210391414-f450fd82-617c-41ad-9c69-e043c5690562.png)

cilium endpoints ls
![image](https://user-images.githubusercontent.com/20623365/210391483-df3d91cb-ecca-4454-93e5-1e1b2b72de7c.png)

cilium identity
![image](https://user-images.githubusercontent.com/20623365/210391600-5d0b63df-4495-42b9-bdd3-26e2a782dc07.png)

cilium policy trace --debug --src-identity 12152  --dst-identity 16777270   --dport 80/TCP  looks like good.
![image](https://user-images.githubusercontent.com/20623365/210392092-964054ce-5fe0-459e-ab1f-62b8d80ba221.png)

**How should I configure it so that L4 has connectivity or can ping the server？**

### Cilium Version

cilium-cli: v0.12.11 compiled with go1.19.3 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.5
cilium image (running): v1.12.2

### Kernel Version

4.18.0-348.2.1.el8_5.x86_64

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
You can use [label-based network policies](https://docs.cilium.io/en/stable/policy/language/#labels-based) instead to implement access control between Cilium-managed pods.

**Comment by arrowfeng** [comment]
> You can use [label-based network policies](https://docs.cilium.io/en/stable/policy/language/#labels-based) instead to implement access control between Cilium-managed pods.

Thank you, I try it.
