### ISSUE TITLE
Regression in latest cilium as it doesn't support IPAddress with CIDR notation from delegated ipam

### ISSUE THREAD

**Issue by rjdenney** [cilium/cilium#22917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using Cilium 1.13 with azure-ipam and CNS I ran into an issue with the ip addresses passed from the azure-ipam. The issue was originally tested on a dualstack cluster producing this error:

`Output when trying to run a dual stack AKS cluster
to setup network for sandbox "bba8210c502144b0ce2983a5ebedc7c18f63f3cceaaca5308b98b6b0715704f1": plugin type="cilium-cni" failed (add): unable to prepare IP addressing for 'fd12:1234::1f7/112': ParseAddr("fd12:1234::1f7/112"): unexpected character, want colon (at "/112")`

when tested and found on a single stack v4 cluster with the following error:

`Output when trying to run a dual stack AKS cluster
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5604fb6b5175dd7135a21d3a8c2b8e9299f9f0b247a8eb6635103cd12d6f5e5d": plugin type="cilium-cni" failed (add): unable to prepare IP addressing for '192.168.3.31/16': ParseAddr("192.168.3.31/16"): unexpected character (at "/16")`

This issue is related to the addition of netip into Cilium and this specific issue is appearing from line 293 of plugins/cilium-cni/main.go in the following commit: https://github.com/cilium/cilium/commit/5755c583526a1d7364ce2921e281a0b8fb08ec4c#diff-87793c7d9c6d6a10f34d6a3efefed53dac8abd700cb05cfb2a77844ec990b744R293

### Cilium Version

1.13.90

### Kernel Version

5.4.0-1094-azure

### Kubernetes Version

1.25.2

### Relevant log output

```shell
Output when trying to run a dual stack AKS cluster
to setup network for sandbox "bba8210c502144b0ce2983a5ebedc7c18f63f3cceaaca5308b98b6b0715704f1": plugin type="cilium-cni" failed (add): unable to prepare IP addressing for 'fd12:1234::1f7/112': ParseAddr("fd12:1234::1f7/112"): unexpected character, want colon (at "/112")

Output when trying to run a dual stack AKS cluster
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5604fb6b5175dd7135a21d3a8c2b8e9299f9f0b247a8eb6635103cd12d6f5e5d": plugin type="cilium-cni" failed (add): unable to prepare IP addressing for '192.168.3.31/16': ParseAddr("192.168.3.31/16"): unexpected character (at "/16")
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rjdenney** [comment]
@pchaigno yes, I am referring to the latest master. 

To reproduce:
1. Create an AKS cluster using Cilium CNI
2. Clone the latest master cilium repo
3. Build the cilium-cni binary
4. Run kubectl node-shell on the node of the AKS cluster created earlier
5. Run kubectl get pods -o wide to find a pod called "nsenter-xxx"
6. Copy the cilium-cni binary to the AKS cluster using kubectl cp cilium-cni nsenter-xxx:/opt/cni/bin
7. Create a new pod on the cluster using kubectl run test --image=nginx

When updated with the current cilium master the pod should get stuck in the "ContainerCreating" state and if you run kubectl describe pod you should see that the reason it is stuck creating is because of the error mentioned above.

**Comment by pchaigno** [comment]
I'm not sure that setup, with just the CNI binary, is supported. Any reason you are not following the getting started guide for AKS?

**Comment by rjdenney** [comment]
> EDIT: I got pinged by a colleague with more context who explained that you're likely working on this new setup for the Azure/Cilium integration 🙂 🚀

Yes, that is what I am currently working on 😄
