### ISSUE TITLE
Prometheus metric for highest IPsec output sequence number

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#22924]
As discussed in https://github.com/cilium/cilium/issues/22747, if the IPsec keys are not rotated often enough, some XFRM states may reach the maximum value for the output sequence number and packets will then be dropped. This is currently reported as a `XfrmOutStateSeqError` error (with the [corresponding IPsec Prometheus error counter](https://docs.cilium.io/en/stable/operations/metrics/#ipsec)) but we don't expose a Prometheus metric to watch the sequence number before it reaches its limit.

The suggestion here would be to implement something similar to [`cilium encrypt status`'s `Max Seq. Number`](https://github.com/cilium/cilium/blob/fd50b8d3b9684e0e88139e5776bd68ef15a344d0/cilium/cmd/encrypt_status.go#L92) but as a Prometheus metric. That is, we would report the maximum sequence number seen on the node as a Prometheus metric. Users would then be able to setup alerting if the value gets too close to the limit.

Suggested-by: Christian Beneke <c.beneke@wirelab.org>

**Comment by tanberBro** [comment]
Hi @pchaigno  , I'm new to cilium, can I try this ? I'd take this one.

**Comment by pchaigno** [comment]
@tanberBro Sure, go ahead. Don't hesitate to ask questions here or in the Slack #development channel if you need help.

**Comment by pchaigno** [comment]
Closing given https://github.com/cilium/cilium/pull/23084#pullrequestreview-1260998964.
