### ISSUE TITLE
unable to retrieve cilium status: no preferred addresses found; known addresses: []

### ISSUE THREAD

**Issue by orihomie** [cilium/cilium#22926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have arm VM with k8s installed by kubeadm command. 
After I've setup cluster (`kubeadm init`) I'm trying to run `cilium install`, which fails after long delay with error:
> unable to retrieve cilium status: no preferred addresses found; known addresses: []

root@k8-master# ➜  ~ cilium install
ℹ️  Using Cilium version 1.12.2
🔮 Auto-detected cluster name: kubernetes
🔮 Auto-detected datapath mode: tunnel
🔮 Auto-detected kube-proxy has been installed
ℹ️  helm template --namespace kube-system cilium cilium/cilium --version 1.12.2 --set cluster.id=0,cluster.name=kubernetes,encryption.nodeEncryption=false,kubeProxyReplacement=disabled,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=vxlan
ℹ️  Storing helm values file in kube-system/cilium-cli-helm-values Secret
🔑 Created CA in secret cilium-ca
🔑 Generating certificates for Hubble...
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap for Cilium version 1.12.2...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed and ready...
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         1 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 1, Ready: 1/1, Available: 1/1
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 1
                  cilium-operator    Running: 1
Cluster Pods:     2/2 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.12.2@sha256:986f8b04cfdb35cf714701e58e35da0ee63da2b8a048ab596ccb49de58d5ba36: 1
                  cilium-operator    quay.io/cilium/operator-generic:v1.12.2@sha256:00508f78dae5412161fa40ee30069c2802aef20f7bdd20e91423103ba8c0df6e: 1
Errors:           cilium             cilium-wt9mf    unable to retrieve cilium status: no preferred addresses found; known addresses: []
↩️ Rolling back installation...

Error: Unable to install Cilium: timeout while waiting for status to become successful: context deadline exceeded

### Cilium Version

1.12.2

### Kernel Version

Linux k8-master 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:56:13 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:09Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/arm64"}

### Sysdump
[cilium-sysdump-20230104-163833.zip](https://github.com/cilium/cilium/files/10349347/cilium-sysdump-20230104-163833.zip)

### Relevant log output

```shell
🔍 Collecting sysdump with cilium-cli version: v0.12.11, args: [sysdump]
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Cilium network policies
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium identities
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium nodes
🔍 Collecting Ingresses
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting Cilium etcd secret
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the Cilium operator deployment
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting the Hubble UI deployment
🔍 Collecting the CNI configmap
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting gops stats from Cilium pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
🔍 Collecting bugtool output from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting platform-specific data
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting kvstore data
🔍 Collecting Hubble flows from Cilium pods
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [12] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource (get ciliumegressnatpolicies.cilium.io)
⚠️ [13] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [14] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [19] Collecting CiliumClusterwideEnvoyConfigs: failed to collect CiliumClusterwideEnvoyConfigs: the server could not find the requested resource (get ciliumclusterwideenvoyconfigs.cilium.io)
⚠️ [20] Collecting CiliumEnvoyConfigs: failed to collect CiliumEnvoyConfigs: the server could not find the requested resource (get ciliumenvoyconfigs.cilium.io)
⚠️ [21] Collecting Cilium etcd secret: failed to collect Cilium etcd secret: an empty namespace may not be set when a resource name is provided
⚠️ [22] Collecting the Cilium configuration: failed to collect the Cilium configuration: an empty namespace may not be set when a resource name is provided
⚠️ [24] Collecting the Hubble daemonset: failed to collect the Hubble daemonset: an empty namespace may not be set when a resource name is provided
⚠️ [25] Collecting the Hubble Relay configuration: failed to collect the Hubble Relay configuration: an empty namespace may not be set when a resource name is provided
⚠️ [26] Collecting the Hubble Relay deployment: failed to collect the Hubble Relay deployment: an empty namespace may not be set when a resource name is provided
⚠️ [27] Collecting the Hubble UI deployment: failed to collect the Hubble UI deployment: an empty namespace may not be set when a resource name is provided
⚠️ [28] Collecting the Cilium operator deployment: failed to collect the Cilium operator deployment: an empty namespace may not be set when a resource name is provided
⚠️ [29] Collecting the 'clustermesh-apiserver' deployment: failed to collect the 'clustermesh-apiserver' deployment: an empty namespace may not be set when a resource name is provided
⚠️ [31] Collecting the CNI configmap: failed to collect the CNI configuration configmap: an empty namespace may not be set when a resource name is provided
⚠️ [44] Collecting kvstore data: failed to get cilium-config ConfigMap: an empty namespace may not be set when a resource name is provided
⚠️ cniconflist-cilium-kfnzm: no preferred addresses found; known addresses: []
⚠️ gops-cilium-kfnzm-memstats: failed to list processes "cilium-kfnzm" ("cilium-agent") in namespace "kube-system": no preferred addresses found; known addresses: []
⚠️ gops-cilium-kfnzm-stack: failed to list processes "cilium-kfnzm" ("cilium-agent") in namespace "kube-system": no preferred addresses found; known addresses: []
⚠️ gops-cilium-kfnzm-stats: failed to list processes "cilium-kfnzm" ("cilium-agent") in namespace "kube-system": no preferred addresses found; known addresses: []
⚠️ cilium-bugtool-cilium-kfnzm: failed to collect 'cilium-bugtool' output for "cilium-kfnzm" in namespace "kube-system": no preferred addresses found; known addresses: []: 
⚠️ logs-cilium-kfnzm-cilium-agent: failed to collect logs for "cilium-kfnzm" ("cilium-agent") in namespace "kube-system": no preferred addresses found; known addresses: []
⚠️ logs-cilium-kfnzm-mount-cgroup: failed to collect logs for "cilium-kfnzm" ("mount-cgroup") in namespace "kube-system": no preferred addresses found; known addresses: []
⚠️ logs-cilium-kfnzm-apply-sysctl-overwrites: failed to collect logs for "cilium-kfnzm" ("apply-sysctl-overwrites") in namespace "kube-system": no preferred addresses found; known addresses: []
⚠️ logs-cilium-operator-5b4f4cf5f8-zmc4m-cilium-operator: failed to collect logs for "cilium-operator-5b4f4cf5f8-zmc4m" ("cilium-operator") in namespace "kube-system": no preferred addresses found; known addresses: []
⚠️ logs-cilium-kfnzm-mount-bpf-fs: failed to collect logs for "cilium-kfnzm" ("mount-bpf-fs") in namespace "kube-system": no preferred addresses found; known addresses: []
⚠️ logs-cilium-kfnzm-clean-cilium-state: failed to collect logs for "cilium-kfnzm" ("clean-cilium-state") in namespace "kube-system": no cilium-sysdump-20230104-163833preferred addresses found; known addresses: []
⚠️ hubble-flows-cilium-kfnzm: failed to collect hubble flows for "cilium-kfnzm" in namespace "kube-system": no preferred addresses found; known addresses: []: 
⚠️ Please note that depending on your Cilium version and installation options, this may be expected
```

### Anything else?

**UPD** VM's ip configured via /etc/systemd/network/10-interface-name.network to make it static

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Note the uploading of the Cilium sysdump failed. It may be because you submitted the issue before GitHub had finished uploading.

**Comment by orihomie** [comment]
> Note the uploading of the Cilium sysdump failed. It may be because you submitted the issue before GitHub had finished uploading.

Fixed, thanks!

**Comment by pchaigno** [comment]
> Errors: cilium cilium-wt9mf unable to retrieve cilium status: no preferred addresses found; known addresses: []

This Cilium pod doesn't seem to exist in the sysdump. Is that because the error message is from a different install than the sysdump's?

**Comment by orihomie** [comment]
> > Errors: cilium cilium-wt9mf unable to retrieve cilium status: no preferred addresses found; known addresses: []
> 
> This Cilium pod doesn't seem to exist in the sysdump. Is that because the error message is from a different install than the sysdump's?

I was installing cilium on control plane node and collected sysdump on that node. 
I can reproduce it again it its needed.

**Comment by pchaigno** [comment]
What I'm saying is that the Cilium agent with the error message is nowhere to be seen in the cluster. Are you having any other issue besides that error message?

**Comment by orihomie** [comment]
No, it's only this issue with installing cilium. 
I've also reinited few (many) times kube and uninstalled & reinstalled cilium to get things work, so I apologize if my issue's description is incorrect.

**Comment by pchaigno** [comment]
Unless the issue still appears when running `cilium status`, I would ignore it. It's probably a transient error.
