### ISSUE TITLE
cilium mesh bpf tunnel list not updated

### ISSUE THREAD

**Issue by mlkmhd** [cilium/cilium#22923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I connected two clusters to each other successfully but after some days they disconnected from each other!

```
$ cilium --context=cluster-1 clustermesh status
⚠️  Service type NodePort detected! Service may fail when nodes are removed from the cluster!
✅ Cluster access information is available:
  - 192.168.7.136:31140
✅ Service "clustermesh-apiserver" of type "NodePort" found
✅ All 4 nodes are connected to all clusters [min:1 / avg:1.0 / max:1]
🔌 Cluster Connections:
- cluster-2: 4/4 configured, 4/4 connected
🔀 Global services: [ min:91 / avg:91.0 / max:91 ]
```

```
$ cilium --context=cluster-2 clustermesh status
⚠️  Service type NodePort detected! Service may fail when nodes are removed from the cluster!
✅ Cluster access information is available:
  - 192.168.7.68:31140
✅ Service "clustermesh-apiserver" of type "NodePort" found
✅ All 4 nodes are connected to all clusters [min:1 / avg:1.0 / max:1]
🔌 Cluster Connections:
- cluster-1: 4/4 configured, 4/4 connected
🔀 Global services: [ min:0 / avg:67.5 / max:90 ]
```
in the cluster1 the tunnel list is like this:
```
# cilium bpf tunnel list 
TUNNEL         VALUE
10.42.17.0:0   192.168.7.69:0    
10.42.19.0:0   192.168.7.71:0    
10.42.3.0:0    192.168.7.184:0   
10.42.16.0:0   192.168.7.70:0    
10.42.18.0:0   192.168.7.68:0    
10.42.2.0:0    192.168.7.185:0   
10.42.0.0:0    192.168.7.65:0    
```

but in the cluster2 the tunnel list is like this:
```
# cilium bpf tunnel list 
TUNNEL         VALUE
10.42.17.0:0   192.168.7.69:0   
10.42.18.0:0   192.168.7.68:0   
10.42.16.0:0   192.168.7.70:0
```

the cluster2 cilium agents connected to `clustermesh-apiserver` cluster1 successfully :
```
level=info msg="Got lease ID 7c0285270b1459e6 and the session TTL is 15m0s" subsys=kvstore
level=info msg="Got lock lease ID 7c0285270b1459e8" subsys=kvstore
level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/cluster-1 endpoints="[https://cluster-1.mesh.cilium.io:31140]" subsys=kvstore
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/cluster-1 endpoints="[https://cluster-1.mesh.cilium.io:31140]" etcdEndpoint="https://cluster-1.mesh.cilium.io:31140" subsys=kvstore version=3.4.13
level=info msg="Connection to remote cluster established" clusterName=cluster-1 config=/var/lib/cilium/clustermesh/cluster-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
level=info msg="Established connection to remote etcd" clusterName=cluster-1 config=/var/lib/cilium/clustermesh/cluster-1 kvstoreErr="<nil>" kvstoreStatus="Waiting for initial connection to be established" subsys=clustermesh
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
```

but all of my pods inside cluster2 cannot connect to cluster1 pods. where is my problem?

### Cilium Version

Client: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64

### Kernel Version

5.3.18-59.37-preempt

### Kubernetes Version

1.23

### Sysdump

[Uploading cilium-sysdump-20230104-143950.zip…]()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
> I connected two clusters to each other successfully but after some days they disconnected from each other!

So it worked at the beginning and over time, the problem occurred? 

I would suggest digging into what changed in the cluster at the time. What is the current status of the mesh?

**Comment by mlkmhd** [comment]
@pchaigno sorry for the broken dump file. I attached it again:
[cilium-sysdump-20230104-143950.zip](https://github.com/cilium/cilium/files/10365619/cilium-sysdump-20230104-143950.zip)

@christarazi Yes it worked at the beginning but I'm not sure what changed after installation. I'm the administrator of these two clusters and guess nothing change, but I like to know which parameters can break connection between clusters...

**Comment by christarazi** [comment]
From a brief look at the logs, it seems the connectivity to the etcd is having trouble. Have you looked into that?

**Comment by mlkmhd** [comment]
@christarazi 
Yes we may have some network disruption between our clusters but It is not continual. maybe for some minutes they disconnected from each other. is cilium agent retry to other cluster to collect list? 
I was thinking that garbage node collector deleted our nodes in opposite cluster and disabling garbage node collector maybe resolve this issue temporary 🤔
