### ISSUE TITLE
BPF host routing can't be enabled if the devices include the wildcard option

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#22925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium checks if all given network interfaces have L2 addr here if option.Config.EnableHostLegacyRouting is false, but the devices haven't been expanded at this point, and the check fails.
https://github.com/cilium/cilium/blob/v1.13.0-rc4/daemon/cmd/kube_proxy_replacement.go#L354

The devices are expanded here after initKubeProxyReplacementOptions that checks the interfaces' L2 addr is called
https://github.com/cilium/cilium/blob/v1.13.0-rc4/daemon/cmd/daemon.go#L954

initKubeProxyReplacementOptions is called here. DeviceManager.Detect hasn't been called yet.
https://github.com/cilium/cilium/blob/v1.13.0-rc4/daemon/cmd/daemon.go#L457

### Cilium Version

v1.13.0-rc4

### Kernel Version

$ uname -a
Linux rack2-cs4 5.15.77-flatcar

### Kubernetes Version

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:26:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"archive", BuildDate:"2022-08-02T02:58:28Z", GoVersion:"go1.17.12", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
$ cilium config set enable-host-legacy-routing false
✨ Patching ConfigMap cilium-config with enable-host-legacy-routing=false...
♻️  Restarted Cilium pods

level=info msg="BPF host routing is currently not supported with devices without L2 addr. Falling back to legacy host routing (enable-host-legacy-routing=true)." subsys=daemon

$ cilium config view | grep device
devices                                        eth+ eno1+ eno2+
direct-routing-device                          eth+

$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 xdp qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:73:c0:35 brd ff:ff:ff:ff:ff:ff
    prog/xdp id 8654
    altname enp0s3
    altname ens3
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 xdp qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:8b:21:90 brd ff:ff:ff:ff:ff:ff
    prog/xdp id 8665
    altname enp0s4
    altname ens4
4: node0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether f6:78:90:df:82:dc brd ff:ff:ff:ff:ff:ff
5: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 62:2f:b9:35:c2:0c brd ff:ff:ff:ff:ff:ff
6: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 1e:91:cf:58:2e:3b brd ff:ff:ff:ff:ff:ff
7: vetha592be56cda@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 12:7e:12:8f:fb:0e brd ff:ff:ff:ff:ff:ff link-netns cni-d7cafb86-3f39-4d45-a5d0-ff7255007fcf
    alias COIL:default:73cd4e34a2500232eaeb8b252dd13cbd117bc799add3a8ea1747a03e0362fd7a:eth0
10: cilium_geneve: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether b6:d4:6f:1b:ac:72 brd ff:ff:ff:ff:ff:ff
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Nice find @ysksuzuki! Are you planning to submit a fix for it?

**Comment by ysksuzuki** [comment]
Absolutely, I will get it done.
