### ISSUE TITLE
Cilium did not create the cr CiliumEndpoint corresponding to the pod

### ISSUE THREAD

**Issue by sunnoy** [cilium/cilium#22938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

pod list

```bash
kubectl get pod --label-columns app=test
NAME         READY   STATUS    RESTARTS   AGE   APP=TEST
static-web   1/1     Running   0          12m   
```

cilium endpoint

```bash
cilium endpoint list 
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                  IPv6   IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                   
678        Disabled           Disabled          9290       k8s:app=test                                                                        10.0.0.96    ready   
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                   
                                                           k8s:io.cilium.k8s.policy.cluster=default                                                                 
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                          
                                                           k8s:io.kubernetes.pod.namespace=default                                                                  
```

but cr CiliumEndpoint list no app=test CiliumEndpoint

```bash
kubectl get CiliumEndpoint -A
NAMESPACE     NAME                       ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4         IPV6
kube-system   coredns-5c6b6c5476-jtwxw   1338          22569         <status disabled>     <status disabled>    <status disabled>   ready            10.0.0.138   
```

### Cilium Version

cilium version 
Client: 1.12.5 701acde 2022-12-15T16:03:30-08:00 go version go1.18.9 linux/amd64
Daemon: 1.12.5 701acde 2022-12-15T16:03:30-08:00 go version go1.18.9 linux/amd64

### Kernel Version

uname -r
4.19.91-26.an8.x86_64

### Kubernetes Version

kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0+k3s1", GitCommit:"fae8817655a8ad1250d40e5b4f9a938cbb9c960a", GitTreeState:"clean", BuildDate:"2022-12-21T00:22:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

kubectl get node             
NAME           STATUS   ROLES                       AGE   VERSION
test01   Ready    control-plane,etcd,master   58m   v1.26.0+k3s1
test02   Ready    <none>                      57m   v1.26.0+k3s1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Hey! Can you upload a sysdump from the affect node?

**Comment by sunnoy** [comment]
CiliumEndpoint has been created when I checked today 。。。

```bash
kubectl get CiliumEndpoint -A
NAMESPACE     NAME                       ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4        IPV6
default       static-web                 2029          9290          <status disabled>     <status disabled>    <status disabled>   ready            10.0.0.82   
kube-system   coredns-5c6b6c5476-jtwxw   3779          22569         <status disabled>     <status disabled>    <status disabled>   ready            10.0.0.83   
```
