### ISSUE TITLE
CI: `docker.io/cilium/echoserver-udp` pod deployment fails because of rate limit 

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#22937]
```
	   Warning  Failed     3m12s (x3 over 3m50s)  kubelet            Failed to pull image "docker.io/cilium/echoserver-udp:v2020.01.30": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/cilium/echoserver-udp:v2020.01.30": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/cilium/echoserver-udp/manifests/sha256:66680075424a25cae98c4a437fec2b7e33b91fbe94e53defeea0305aee3866dd: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
Seen at https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/335/testReport/junit/Suite-k8s-1/26/K8sDatapathServicesTest_Checks_E_W_loadbalancing__ClusterIP__NodePort_from_inside_cluster__etc__Checks_service_on_same_node/

We should move that image over to quay.io.

**Comment by pchaigno** [comment]
I've asked one of the Quay admins to create the new Quay repository and push `docker.io/cilium/echoserver-udp:v2020.01.30` there. Are there any other tags for that image that we should push?

**Comment by pchaigno** [comment]
@obaranov1 quay.io/cilium/echoserver-udp:v2020.01.30 is now ready.

**Comment by obaranov1** [comment]
@pchaigno I have noticed there is a "docker.io/cilium/echoserver:1.10.1" image as well. Do we need to pass this one over to quay.io?

**Comment by pchaigno** [comment]
> @pchaigno I have noticed there is a "docker.io/cilium/echoserver:1.10.1" image as well. Do we need to pass this one over to quay.io?

Yep, good point. We've moved that one to Quay as well.

**Comment by obaranov1** [comment]
"docker.io/cilium/demo-client:1.0" this one too?

**Comment by pchaigno** [comment]
> "docker.io/cilium/demo-client:1.0" this one too?

That one has just been moved as well :slightly_smiling_face:
