### ISSUE TITLE
Proposal: Autodetect default ports for L7 policy rules

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#2293]
Hi, 

This is a proposal. Last week I was testing policies, and I figure it out that if you have an L7 policy, you always need to specified port if not, it is not going to work. 

I think that the L7 Policies should inherit the default port if it's not defined, this allows to end users a more straightforward way to create network policies. 

The idea is: 
```json
{
  "Ingress": [
    {
      "FromEndpoints": [
        {}
      ],
      "ToPorts": [
        {
          "Ports": [
            {
              "port": "8080",
              "protocol": "TCP"
            }
          ],
          "Rules": {
            "http": [
              {
                "method": "GET",
                "path": "/private"
              }
            ]
          }
        }
      ]
    }
  ]
}
```

This should allow only /private/ and destination port 8080. 

If you defined like this: 
```json
{
  "Ingress": [
    {
      "FromEndpoints": [
        {}
      ],
      "ToPorts": [
        {
          "Rules": {
            "http": [
              {
                "method": "GET",
                "path": "/private"
              }
            ]
          }
        }
      ]
    }
  ]
}
```

This should inherit port 80 and 443, so policy will be easy to read/write (same for Kafka or others L7 rules). 

Regards

**Comment by joestringer** [comment]
One brief comment: The latter example specifies "http", not "https" so should it really open 443 as well?

**Comment by eloycoto** [comment]
@joestringer good point, I'm not sure TBH.
