### ISSUE TITLE
cilium unstable, crashing every few minutes/hours

### ISSUE THREAD

**Issue by nikhiljha** [cilium/cilium#22949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Every few minutes/hours, Cilium will crash and restart. It works briefly (connectivity test passes, no visible issues with cluster networking) and then crashes again.

### Cilium Version

```
cilium-cli: 0.12.11 compiled with go1.19.3 on darwin/arm64
cilium image (default): v1.12.2
cilium image (stable): v1.12.5
cilium image (running): v1.13.0-rc2
```

### Kernel Version

Linux adenine 6.0.10 #1-NixOS SMP PREEMPT_DYNAMIC Sat Nov 26 08:27:56 UTC 2022 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

File size too large for GitHub, uploaded to https://ocf.berkeley.edu/~njha/tmp/cilium-sysdump-20230105-114355.zip

### Relevant log output

```shell
panic: addr is not a valid IP address

goroutine 1688 [running]:
github.com/cilium/cilium/pkg/ip.MustAddrFromIP(...)
	/go/src/github.com/cilium/cilium/pkg/ip/ip.go:971
github.com/cilium/cilium/pkg/fqdn.(*DNSCache).LookupIP(0xc000db3920, {0x0?, 0x50?, 0x8?})
	/go/src/github.com/cilium/cilium/pkg/fqdn/cache.go:450 +0x154
github.com/cilium/cilium/daemon/cmd.(*Daemon).GetNamesOf(0x0?, 0x1b2d2de?, {0x0, 0x0, 0x0})
	/go/src/github.com/cilium/cilium/daemon/cmd/hubble.go:343 +0x69
github.com/cilium/cilium/pkg/hubble/parser/seven.(*Parser).Decode(0xc0016b41e0, 0xc0014236b0, 0xc0033ac480)
	/go/src/github.com/cilium/cilium/pkg/hubble/parser/seven/parser.go:98 +0x310
github.com/cilium/cilium/pkg/hubble/parser.(*Parser).Decode(0xc001252600, 0xc0022c9580)
	/go/src/github.com/cilium/cilium/pkg/hubble/parser/parser.go:128 +0x2fd
github.com/cilium/cilium/pkg/hubble/observer.(*LocalObserverServer).Start(0xc004240a20)
	/go/src/github.com/cilium/cilium/pkg/hubble/observer/local_observer.go:128 +0xf4
created by github.com/cilium/cilium/daemon/cmd.(*Daemon).launchHubble
	/go/src/github.com/cilium/cilium/daemon/cmd/hubble.go:173 +0x129c
```

### Anything else?

I suspect something like a workload in the cluster poisoning the cache or something, because at first this was only happening on one node, and now it has slowly spread to three nodes.

Looks like it has something to do with Hubble-- I'll try turning off Hubble and seeing if that works for now.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
Hm, this definitely seems like a regression with the v1.13 version of the code. It seems that some conversion of an IP address is causing a panic. The code path suggests the IP is coming from the Hubble flows, so are you able to capture Hubble output (via `hubble observe`) as the issue occurs and provide it here?

It's possible that it might be some case of IPv4-in-IPv6 or vice versa formatted IP that causing an issue.

**Comment by christarazi** [comment]
Could you filter out the connection for streaming the Hubble logs via `grep -v` or using Hubble's filtering logic? Also, please avoid passing `-4` or `-6` so that we don't filter out potentially useful output.

**Comment by nikhiljha** [comment]
Okay, here we go: [log2.log](https://github.com/cilium/cilium/files/10367579/log2.log) -- output of `hubble observe -n cilium`

crash happened at...
```
Jan  8 02:20:53.678 [hubble-relay-d5bffcc85-cmpxt]: Error "rpc error: code = Unavailable desc = error reading from server: EOF" on 1 nodes: adenine
```

There doesn't look to be anything relevant in that log 🤔

**Comment by gandro** [comment]
Yeah, I think we won't see the offending IP in the Hubble logs, because Hubble is crashing before it stores the offending flow in the ring buffer. 

What might help getting the offending event identified is disabling Hubble and running `cilium monitor` (which doesn't do much flow post-processing) in the affected pod. 

But regardless of actual IP, we probably should not use `MustAddrFromIP` in `DNSCache.LookupIP` and error out gracefully instead.

**Comment by gandro** [comment]
I've opened a potential fix here: https://github.com/cilium/cilium/pull/22994

I see two reasons why `MustAddrFromIP` can panic: Some IPv4-in-IPv6 issues, or the IP was nil (which can happen if `net.ParseIP` cannot parse the IP).

The latter case would occur here:
https://github.com/cilium/cilium/blob/ba1fd7dc9325286b8ce9fefe998d4b810e1647be/pkg/hubble/parser/seven/parser.go#L93

It seems, the previous code was fine with dealing with nil IPs. Thus, my PR restores the old behavior where `GetNamesOf` gracefully deals with nil values. It remains to be determined however, why we cannot parse the IP address in the first pace, and secondly, if Hubble should avoid calling into other functions with a `nil` IP.

**Comment by christarazi** [comment]
@nikhiljha Would you be able to follow @gandro's suggestion here to disable Hubble and fetch the `cilium monitor -t l7` output on any node that was previously affected by the panic?

**Comment by nikhiljha** [comment]
I've been running `cilium monitor -t l7` on two nodes for a while but it doesn't have any log output. This is running on #22994. I'll try again on -rc3 with hubble disabled tomorrow.
