### ISSUE TITLE
clustermesh-api server failing to init in IPv6 single stack cluster

### ISSUE THREAD

**Issue by abasitt** [cilium/cilium#22952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am creating a cluster mesh of two clusters, both clusters are IPv6 single stack. 
The cluster mesh enabled as shown below.

> cilium clustermesh enable --service-type LoadBalancer
> 🔑 Found CA in secret cilium-ca
> 🔑 Generating certificates for ClusterMesh...
> ✨ Deploying clustermesh-apiserver from quay.io/cilium/clustermesh-apiserver:v1.12.5...
> ✅ ClusterMesh enabled!
> 

but the clustermesh-api server pod is not coming up.

> k get pods -n kube-system
> NAME                                     READY   STATUS             RESTARTS       AGE
> cilium-lrgvf                             1/1     Running            0              120m
> cilium-operator-7dd996567-q4wf8          1/1     Running            0              121m
> cilium-wkqr2                             1/1     Running            0              22h
> clustermesh-apiserver-7667fdb9b6-jj2xb   0/2     CrashLoopBackOff   34 (26s ago)   84m

Below are the logs on the clustermesh-api server.

> k logclustermesh-apiserver-7667fdb9b6-jj2xb -n kube-system
> Defaulted container "etcd" out of: etcd, apiserver, etcd-init (init)
> invalid value "https://127.0.0.1:2379,https://x:x:x:65:1:0:1:de5e:2379" for flag -listen-client-urls: URL address does not have the form "host:port": https://x:x:x:65:1:0:1:de5e:2379

Seems like its not starting because of not detecting the brackets for IPv6 address. I have found a similar old issue for kubeadm, this may be helpful to fix this issue. https://github.com/kubernetes/kubernetes/pull/70633

### Cilium Version

cilium-cli: v0.12.7 compiled with go1.19.3 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.5
cilium image (running): v1.12.5

### Kernel Version

Linux kube65cm1 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.24.8
Kustomize Version: v4.5.4
Server Version: v1.24.8

### Relevant log output

```shell
k logclustermesh-apiserver-7667fdb9b6-jj2xb -n kube-system
Defaulted container "etcd" out of: etcd, apiserver, etcd-init (init)
invalid value "https://127.0.0.1:2379,https://x:x:x:65:1:0:1:de5e:2379" for flag -listen-client-urls: URL address does not have the form "host:port": https://x:x:x:65:1:0:1:de5e:2379
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YutaroHayakawa** [comment]
Hi, thanks for your report!

At first glance, it seems like the value comes from the k8s `fieldRef`. So, I guess it is substituted in some weird way.

https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/clustermesh-apiserver/deployment.yaml#L92-L102

**Comment by abasitt** [comment]
Thank you for the quick response. Below did the trick by modifying the running deployment. The api server is running now.

        - --listen-client-urls=https://127.0.0.1:2379,https://[$(HOSTNAME_IP)]:2379
        - --advertise-client-urls=https://[$(HOSTNAME_IP)]:2379

I believe it will most likely fail for IPv4 clusters.

**Comment by YutaroHayakawa** [comment]
I think we can do like this.

```
        {{- if .Values.ipv4.enabled }}
         - --listen-client-urls=https://127.0.0.1:2379,https://$(HOSTNAME_IP):2379
         - --advertise-client-urls=https://$(HOSTNAME_IP):2379
        {{- else }}
        - --listen-client-urls=https://127.0.0.1:2379,https://[$(HOSTNAME_IP)]:2379
        - --advertise-client-urls=https://[$(HOSTNAME_IP)]:2379
        {{- end }}
```

**Comment by YutaroHayakawa** [comment]
@abasitt JFYI, I made a PR for fixing this bug, and now it's ready to merge. Once it is merged, this issue will be closed automatically. Thanks for your report!

**Comment by abasitt** [comment]
Thank you so much for the quick fix :)
