### ISSUE TITLE
High Latency for egress ip activation

### ISSUE THREAD

**Issue by skyblueted** [cilium/cilium#22969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Consider security and firewall constraint, we need to use egress ip to connect external service for fixed outgoing requirement by namespace.
Recently, we encountered the **several minutes** until egress ip was applied.
1.The delay time from "pod starts" to "egress ip available" is expected as instant
2. We also observed that enlarged # of cronjobs and # of destination CIDR in egress policy, they could increase waiting time.

### Cilium Version

1.12.4

### Kernel Version

5.15.0-48-generic

### Kubernetes Version

v1.22.15

### Relevant log output

```shell
[Configmap]
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-lb-acceleration: disabled
  bpf-lb-algorithm: maglev
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-mode: hybrid
  bpf-lb-sock: "true"
  bpf-lb-sock-hostns-only: "true"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "1"
  cluster-name: cluster1
  custom-cni-conf: "false"
  debug: "false"
  devices: ' eno5  ens3f0  '
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-ip-masq-agent: "true"
  enable-ipv4: "true"
  enable-ipv4-egress-gateway: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"

[Egress policy sample]
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  labels:
    app.kubernetes.io/instance: egress-policy
  name: egress-test
spec:
  destinationCIDRs:
  - 10.0.0.0/8
  egress:
  - namespaceSelector:
      matchLabels:
        name: test
  egressSourceIP: 10.100.10.1
```

### Anything else?

**How to reproduce?**
Topology:
![image](https://user-images.githubusercontent.com/79855132/211157128-37813f36-2890-4ab8-9b76-c974ccaf0a34.png)

- Deploy 1 egress policy to a namespace, generated _511_ rows of garbage destination CIDRs and one default dest for connect external service
- Set up an external web service (e.g. nginx) to response **$remote_addr** to verify that egress ip will be applied to new pod
- Insert bash script which accesses external web periodically until response includes egress ip to all nginx cronjobs in the first place, and create _30_ cronjobs in a namespace, each cronjob triggers a job per 1 minute

[Pseudo code]
```
- /bin/bash
- -c
- |
declare -i sec=0
isSet="False"
until [ $isSet == "True" ] || [ $sec -eq 360 ]
do
   echo "$(date) waiting AP start ... $sec seconds"
   echo "==============Verify egress ip============="
   resp=$(curl -s <web_service to get source ip>)
   echo $egress
   if [[ $resp == "<egress ip>"* ]]
   then
     isSet="True"
   else
     isSet="False"
   fi
   echo "===================================="
   sleep 1
   sec=`expr $sec + 1`
```

**Root cause:**
We found cilium implement **reconcile** code for egress map updated/deleted in general case.
Include **removeUnusedEgressRules** and **addMissingEgressRules** two function, they selected **_brute-force_** strategy.
They may take long time under new job is created or completed. 
https://github.com/cilium/cilium/blob/d95b0a0b70805e8de41c27c7d5b8fbac57d913e9/pkg/egressgateway/manager.go#L368-#L385
https://github.com/cilium/cilium/blob/d95b0a0b70805e8de41c27c7d5b8fbac57d913e9/pkg/egressgateway/manager.go#L332-#L362

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by benesch** [comment]
We're running into this too at @MaterializeInc.

**Comment by truffles** [comment]
We're experiencing the same issue.

In the `manager.removeUnusedEgressRules()` function, the current approach of looping through all egress policies to determine if any of them need to be removed seems inefficient.
Instead, we propose a more efficient solution:
1. Loop through `policyConfigs` to identify any egress policies that match, and remove them from the `egressPolicies` map.
   After this step, the remaining entries in the `egressPolicies` map are stale.
2. Remove the stale egress policies based on the `egressPolicies` map.

We recently implemented this approach in our production environment, and we haven't encountered any problems so far.
If this seems reasonable, I would be happy to submit a PR.

**Comment by jibi** [comment]
>  I discovered that the logic in the latest master branch has been optimized recently, which I had missed.

correct, the following improvements landed in master in the past couple of months:
* https://github.com/cilium/cilium/pull/23529
* https://github.com/cilium/cilium/pull/23967
* https://github.com/cilium/cilium/pull/24034
* https://github.com/cilium/cilium/pull/24042

**Comment by jibi** [comment]
Closing this as all the improvements are already in master, but feel free to reopen it if you are still experiencing the high latency.

There's a 1.14.0-snapshot.1 pre-release (https://github.com/cilium/cilium/releases/tag/v1.14.0-snapshot.1) that can be used to test these changes.
