### ISSUE TITLE
XDP: Failing to attach XDP program to team Interface with VLAN

### ISSUE THREAD

**Issue by log1cb0mb** [cilium/cilium#22970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Issue when enabling XDP/LB acceleration: Native

Cilium agent not coming up as its failing with following:

```
level=fatal msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface team0.216: operation not supported" subsys=datapath-loader
```

There is supposed to be XDP support for bonding interface however I am not sure if its different when interface aggregation type is Team and also interface in question is VLAN interface

### Cilium Version

1.12.5/1.13.0-rc4

### Kernel Version

Linux node 6.1.3-1.el8.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jan  3 09:56:26 EST 2023 x86_64 x86_64 x86_64 GNU/Linux

Same issue also with: 5.14.0-162.6.1.el9_1.x86_64

### Kubernetes Version

v1.24.8

### Relevant log output

```shell
level=debug msg="Launching compiler" args="[-emit-llvm -g -O2 -target bpf -std=gnu89 -nostdinc -D__NR_CPUS__=176 -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -Wimplicit-int-conversion -Wenum-conversion -DSECLABEL=2 -DNODE_MAC={.addr={0x8,0xc0,0xeb,0x32,0x4a,0x92}} -DCALLS_MAP=cilium_calls_xdp -Dcapture_enabled=0 -DTHIS_MTU=9000 -DNATIVE_DEV_IFINDEX=11 -DDISABLE_LOOPBACK_LB -I/var/run/cilium/state/globals -I/var/run/cilium/state -I/var/lib/cilium/bpf -I/var/lib/cilium/bpf/include -c /var/lib/cilium/bpf/bpf_xdp.c -o -]" subsys=datapath-loader target=clang
level=debug msg="Loading CollectionSpec from ELF" device=team0.216 ifindex=11 objPath=/var/run/cilium/state/bpf_xdp.o subsys=datapath-loader
level=debug msg="Loading Collection into kernel" device=team0.216 ifindex=11 objPath=/var/run/cilium/state/bpf_xdp.o subsys=datapath-loader
level=debug msg="Attaching program to interface" device=team0.216 direction= ifindex=11 objPath=/var/run/cilium/state/bpf_xdp.o progName=cil_xdp_entry subsys=datapath-loader
level=debug msg="Reverting bpffs map migration" device=team0.216 ifindex=11 objPath=/var/run/cilium/state/bpf_xdp.o subsys=datapath-loader
level=fatal msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface team0.216: operation not supported" subsys=datapath-loader
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by log1cb0mb** [comment]
@joamaki Anything regarding this?

**Comment by joamaki** [comment]
The team driver currently does not have native XDP support . Would it be feasible for you to use the bonding driver instead? You'll need 5.15 or newer kernel.

**Comment by log1cb0mb** [comment]
Thanks for the confirmation. I have to admit that I am not too familiar with the bpf programs requirements that you mentioned but sounds like supporting team driver would take lot of effort and currently not much user demand for it?

It will not be easy pushing for bonding driver in my environment but I can try, I may need to collect enough info or proper reasoning to justify it.

One general question: seems that there are limitation or not-supported funtionalities when using cilium and going BPF all the way (other bpf related features than native XDP) with team driver so in that scenario, would you recommend using bond instead? And yes, main driving factor for my environment is performance (_full disclosure: evaluating performance in my environment between calico and cilum_).
