### ISSUE TITLE
Does cilium provides multi CNI capabilities like Multus.

### ISSUE THREAD

**Issue by samar08** [cilium/cilium#22993]
Can anyone please tell me whether cilium provides multi-CNI capabilities like Multus? If yes, please provide the reference links of the documentation and the steps to enable it.

**Comment by xmulligan** [comment]
The closest Cilium gets to that is CNI Chaining https://docs.cilium.io/en/stable/gettingstarted/cni-chaining/#id1

**Comment by samar08** [comment]
So you mean only with cilium as the base and the only CNI we cannot enable multi-CNI capabilities without adding any additional CNIs to it.

**Comment by xmulligan** [comment]
Nope, that is not the focus of Cilium. Multus or CNI-Genie are better for that

**Comment by brb** [comment]
@samar08 Please check https://github.com/cilium/cilium/issues/20129 (WIP).

**Comment by w7team** [comment]
+1
