### ISSUE TITLE
is cilium suport allocate a static ip address for pod?

### ISSUE THREAD

**Issue by wanghonglei5181** [cilium/cilium#23005]
## Cilium Feature Proposal
**the feather what i want?**        
is cilium suport allocate a static ip address for pod?

**Is your feature request related to a problem?**

my pod needs a static ip, when pod destroyed and recreated,the ip adress can not be changed.

**Describe the feature you'd like**

the feather i want that is like calico annatation cni.projectcalico.io/ipaddrs:["xxxxx","xxxx"]
i am using calico now.
we want use cilium replace calico。

**(Optional) Describe your proposed solution**
the doc of calico that how specific a ip to a pod
https://projectcalico.docs.tigera.io/networking/use-specific-ip

in some situation,some service have a white list,such as database ,ldap serivce,security service and so on.

**Comment by christarazi** [comment]
Dup of https://github.com/cilium/cilium/issues/17026
