### ISSUE TITLE
Document how to debug memory leaks

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#23004]
* Sysdump includes gops output; provide commands for reading them
* Provide gops command to capture a profile without sysdump
* Briefly explain the different pprof profiles and which are useful when

**Comment by measutosh** [comment]
Hello @christarazi 

I would like to pick this up
Could you please lead me to the file where the changes need to be implemented or any other resources to get me started

**Comment by deepeshaburse** [comment]
Hi @christarazi @xmulligan, can I work on this?

**Comment by xmulligan** [comment]
Sure @deepeshaburse please start working on it

**Comment by deepeshaburse** [comment]
@xmulligan Could you please tell me where I need to add these changes?

**Comment by xmulligan** [comment]
@deepeshaburse Sorry, I don't code. You will need to figure it out

**Comment by deepeshaburse** [comment]
> @deepeshaburse Sorry, I don't code. You will need to figure it out

Oh no problem, I'll figure it out, thanks 😊

**Comment by christarazi** [comment]
For the second item, the set of command to capture the pprof is

```
kubectl exec -ti -n kube-system <cilium-pod> -- cilium-bugtool --get-pprof 
kubectl cp -n kube-system <cilium-pod-name>:/tmp/cilium-bugtool-<time-generated-name>.tar.gz ./cilium-pprof.tar.gz
```

Julia Evans has a great explainer for the 3rd bullet point, https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/.

**Comment by deepeshaburse** [comment]
> @deepeshaburse 
> 
> 
> 
> For the second item, the set of command to capture the pprof is
> 
> 
> 
> ```
> 
> kubectl exec -ti -n kube-system <cilium-pod> -- cilium-bugtool --get-pprof 
> 
> kubectl cp -n kube-system <cilium-pod-name>:/tmp/cilium-bugtool-<time-generated-name>.tar.gz ./cilium-pprof.tar.gz
> 
> ```
> 
> 
> 
> Julia Evans has a great explainer for the 3rd bullet point, https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/.

Thank you for the pointers! 😄

**Comment by deepeshaburse** [comment]
@christarazi I just had one more question, which page do I need to add this content to? Thanks!

**Comment by marseel** [comment]
> Sysdump includes gops output; provide commands for reading them

AFAIK current gops output contains only text output, which you can easily read.

> For the second item, the set of command to capture the pprof is
> 
> ```
> kubectl exec -ti -n kube-system <cilium-pod> -- cilium-bugtool --get-pprof 
> kubectl cp -n kube-system <cilium-pod-name>:/tmp/cilium-bugtool-<time-generated-name>.tar.gz ./cilium-pprof.tar.gz
> ```

Correct me if I'm wrong, but cilium-bugtool currently uses regular pprof and not gops. Also, this command will not work unless you add --pprof flag to cilium-agent for example.

To use gops you need to do something like this:
```
kubectl exec -ti -n kube-system <cilium-pod> -- gops pprof-cpu 1
```

I think it would make sense to add "--collect-pprofs" or something similar to cilium-cli that would get all profiles using gops when collecting sysdump. Let me follow up on this.

**Comment by christarazi** [comment]
@marseel Any updates?

**Comment by marseel** [comment]
cilium-cli currently already contains heap/cpu profiles by default: https://github.com/cilium/cilium-cli/pull/1424

So I think the only item left is documenting how to read them.
