### ISSUE TITLE
datapath: Introduce helpers for __ctx_is checks

### ISSUE THREAD

**Issue by brb** [cilium/cilium#23008]
In the datapath we have a few `__ctx_is` checks:

```
> git grep '__ctx_is =='
bpf/include/bpf/ctx/common.h:    return __ctx_is == __ctx_xdp;
bpf/include/bpf/helpers.h:#if __ctx_is == __ctx_skb
bpf/lib/edt.h:#if defined(ENABLE_BANDWIDTH_MANAGER) && __ctx_is == __ctx_skb
bpf/lib/identity.h:#if __ctx_is == __ctx_skb
bpf/lib/identity.h:#endif /* __ctx_is == __ctx_skb */
bpf/lib/nodeport.h:#if __ctx_is == __ctx_skb
bpf/lib/overloadable.h:#if __ctx_is == __ctx_skb
bpf/lib/pcap.h:# define capture_enabled (__ctx_is == __ctx_xdp)
bpf/lib/proxy.h:#if !(__ctx_is == __ctx_skb)
bpf/lib/qm.h:#if defined(RESET_QUEUES) && __ctx_is == __ctx_skb
```

For the sake of readability, we should introduce `ctx_is_{skb,xdp}()` helpers, and replace the `ifdef`'s with the if statements.

**Comment by brb** [comment]
@SamrathPalSingh Are you still interested in working on this issue?

**Comment by spacewander** [comment]
Hi @brb, I am interested in it.

> For the sake of readability, we should introduce ctx_is_{skb,xdp}() helpers, and replace the ifdef's with the if statements.

Do you mean ctx_is_skb macro? There is a guard macro in 
https://github.com/cilium/cilium/blob/ac326f8507f97ff9ed079fb1f72a3924a91c8348/bpf/include/bpf/helpers.h#L27-L31

A runtime `if` with function call may not support including different files.

**Comment by brb** [comment]
Hi @spacewander . I meant the following:
```
bool ctx_is_skb() {
    return __ctx_is == __ctx_skb
}
```
And then replace `#if __ctx_is == __ctx_skb` with `if ctx_is_skb() { ...`. Same goes for the XDP.

**Comment by spacewander** [comment]
Yes. But this doesn't allow selecting `#include <file>` dynamically, as shown in https://github.com/cilium/cilium/issues/23008#issuecomment-1427040261.
Do we need to keep that pattern unchanged?

**Comment by brb** [comment]
>  Do we need to keep that pattern unchanged?

Ah, I see. Yep, let's keep it unchanged.
