### ISSUE TITLE
Replace deprecated `set-output` commands in GitHub workflows

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#23015]
Several of our workflows have the following warning:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

We should fix it before it breaks CI.

**Comment by sayboras** [comment]
should be fixed in https://github.com/cilium/cilium/pull/22890

**Comment by sayboras** [comment]
as https://github.com/cilium/cilium/pull/22890 is merged, we can close this issue.
