### ISSUE TITLE
CFP:  Enhance toplevel makefiles to work with podman buildx

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium#23026]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**
Looking to use a bare metal linux build environment with podman installed. Build process is throwing errors associated with `docker buildx ls` from the top level Makefile.docker 

The error messages appear to be non-critical

**Describe the feature you'd like**
I'd like the Makefile to detect if podman is in use, so the docker buildx specific setup up is skipped and the `docker buildx ls` error messages aren't created 

**(Optional) Describe your proposed solution**

Should be able to detect if the docker command is really just podman underneath. If so don't attempt to setup the docker buildx.

**Comment by chancez** [comment]
The way I've tried to do something similar to this for nerdctl was to make anything running `docker ...` use a variable `DOCKER` in the makefile which could be overridden, and then added a bool to bypass the setup of the buildx builder. This worked well, but I eventually went back to `docker`, so I never created a PR for it.
