### ISSUE TITLE
CFP: Service backend health check.

### ISSUE THREAD

**Issue by jmjoy** [cilium/cilium#23033]
## Cilium Feature Proposal

**Describe the feature you'd like**

I want to use cilium as standalone L4 load balancer, like explained here: <https://cilium.io/blog/2022/04/12/cilium-standalone-L4LB-XDP/>.

However, I found that in the case of multiple backends, one of the backends fails, and the load balancing will also request this backend, resulting in the overall probability of problems.

So is there a mechanism to perform health detection on backend. When the health detection fails, kick out the problematic node?

**Comment by jmjoy** [comment]
I see that there is the API to quarantine the backend. https://isovalent.com/blog/post/cilium-release-112/#quarantining

How about built-in connectivity detection of backend services? I can contribute pr.

**Comment by aditighag** [comment]
Hi @jmjoy Thanks for the CFP request. Yes, the API to quarantine service backends can be used to take out unhealthy backends. 

>So is there a mechanism to perform health detection on backend. When the health detection fails, kick out the problematic node?

Did you mean "kick out the problematic backend"?

>How about built-in connectivity detection of backend services? I can contribute pr.

Sounds great! It'll be great if you could share a CFP with the details of your proposed approach. We can discuss it in the community meeting, or in the Cilium Slack #development channel.

**Comment by jmjoy** [comment]
Maybe can add option `-tcp-check-connect-timeout` in `cilium service update`, like:
```shell
cilium service update --id 1 --frontend "10.1.0.1:8080" --backends "10.1.0.100:8080" --tcp-check-connect-timeout 3s
```
I wonder how to configure TCP or UDP forwarding.

**Comment by jmjoy** [comment]
For example, lvs managed by keepalived has the function of connectivity detection for real servers.

https://keepalived.readthedocs.io/en/latest/configuration_synopsis.html#virtual-server-definitions-synopsis

See the `TCP_CHECK` configuration.

**Comment by bzed** [comment]
@jmjoy @aditighag any news on that? no response and autoclose is not nice :(
