### ISSUE TITLE
K8s testsuite log collection on failure reports invalid arguments

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2305]
This PR failed a run on jenkins:
https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-2302/1/execution/node/35/log/

When attempting to gather logs in the k8s tests, I see this:
```
21:40:48                             Cilium logs (last 200 lines)
21:40:48 docker: "logs" requires 1 argument.
21:40:48 See 'docker logs --help'.
21:40:48 
21:40:48 Usage:	docker logs [OPTIONS] CONTAINER
```

Seems like there's some assumption being violated here - perhaps the docker ID is unexpectedly empty?

The test itself is a pure documentation change, so should not have any relationship to the issue (though it appears to be a flake that may affect master occasionally)

**Comment by ianvernon** [comment]
The logic for this in the K8s tests is the following:

```
cilium_id=$(docker ps -aql --filter=name=cilium-agent)
echo "------------------------------------------------------------------------"
echo "                            Cilium logs (last 200 lines)"
docker logs ${cilium_id} --tail 200
echo ""
echo "------------------------------------------------------------------------"
```

I suspect `cilium_id` was empty for whatever reason. This ticket can track adding more output to console to see what containers are currently running, and not gather logs if `cilium_id` is empty? Also maybe it should output a warning in the case that `cilium_id` is empty, as that indicates Cilium isn't running :(

**Comment by eloycoto** [comment]
@joestringer this is for the old bash test. I'll close this one due is not longer used.
