### ISSUE TITLE
bugtool: make archive output configurable

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#2306]
Hi, this is a minor enhancement request. The output of the bugtool command can get pretty big. It would be nice if outputs to tar.gz by default.

**Comment by aalemayhu** [comment]
@michi-covalent mind if I retitle this to `bugtool: make archive output configurable`?

**Comment by ianvernon** [comment]
@michi-covalent by this do you mean the type of archive? E.g., instead of `tar`, `tar.gz`?
