### ISSUE TITLE
Migrate Azure APIs prior to Sep 30 2023

### ISSUE THREAD

**Issue by bchess** [cilium/cilium#23083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[Azure announced](https://azure.microsoft.com/en-us/updates/api-versions-being-retired-for-azure-api-management/) API versions older than 2021-08-01 will fail after 2023-09-30.

Cilium is currently using [Network API 2020-11-01](https://github.com/cilium/cilium/blob/13cdd07a70ffd21df3cc043a7c24334985c11286/pkg/azure/api/api.go#L14) and [Compute API 2021-03-01](https://github.com/cilium/cilium/blob/13cdd07a70ffd21df3cc043a7c24334985c11286/pkg/azure/api/api.go#LL13C59-L13C69), both of which will be affected. These will need to be upgraded prior to Sep 30.

### Cilium Version

n/a

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hey @bchess would you like to submit a PR? Thank you

**Comment by goverdhan07** [comment]
Hey @aanm, I would like to submit a PR

**Comment by harshitasao** [comment]
I would like to work on this.

/assign

**Comment by harshitasao** [comment]
Hey @aanm  I'm new to this project and wanted to work on this issue. From what I understand, I need to follow this [migration guide](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md) and do the upgrade. Please point me in the right direction if I'm wrong.

**Comment by aanm** [comment]
@harshitasao that is correct
