### ISSUE TITLE
CFP: add option for static/persistent HW network address of a pod

### ISSUE THREAD

**Issue by xhejtman** [cilium/cilium#23080]
## Cilium Feature Proposal
        
Calico CNI provides an annotation `cni.projectcalico.org/hwAdddress` in Pod that can be used if a Pod needs some persistent network interface MAC address.

It would be useful, if some similar option is provided also in Cilium CNI.

This feature is meant for e.g., licencing servers like flexlm that register MAC address on upstream registration services. This MAC address needs to remain the same even after redeployment or moving the pod to a different node.

The address needs to be persistent in Pod only, it does not matter how it looks in cluster.

**Comment by joestringer** [comment]
Thanks for the suggestion! It looks like there is already an issue to track this feature: https://github.com/cilium/cilium/issues/22119 . I will close this one as "duplicate", we can follow up on the other issue.

**Comment by youngnick** [comment]
Oh, looks like this one should be closed as duplicate, closing now, please see #22119 for further work on this feature request.
