### ISSUE TITLE
Lower severity of log message

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2310]
```
time="2017-12-12T02:20:11Z" level=error msg="Unable to add k8s service" error="Not all endpoints IPs are IPv6. Ignoring IPv6 service
```

This is very verbose and repeats often. This should be a warning at most.

**Comment by manalibhutiyani** [comment]
@raybejjani Could you please take a look.

**Comment by raybejjani** [comment]
Thanks to help from @aanm, this turned out to be a real bug. I won't lower the severity unless the consensus is that not handling services is a normal thing. See https://github.com/cilium/cilium/pull/2502
