### ISSUE TITLE
Rename git primary branch to "main"

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#23110]
It's 2023.

Steps (feel free to add ones I missed):

**pre-cut-over**
- [x] Declare cutover day. Ideally not close to any deadlines :-) 
  - April 18th, 2023
- [x] Prepare a PR that updates all relevant workflows in `.github`, `.travis.yml`, `.jenkinsfiles`
- [x] Fix up any scripts in `contrib`

**cut-over day**
- [x] Change the settings in github
- [x] Merge https://github.com/isovalent/cilium/issues/896
- [x] Fix any broken CI jobs :-)
- [x] Mirror `main` to `master` with https://github.com/google/mirror-branch-action (https://github.com/cilium/cilium/pull/24941)

**followup**
- [x] clean up references in docs

**Comment by xmulligan** [comment]
I might also add remove references to master from the docs

**Comment by xmulligan** [comment]
cc: @margamanterola

**Comment by joestringer** [comment]
I'm wondering about the step `Mirror main to master with https://github.com/google/mirror-branch-action`, github will redirect web requests or return error 301 for master branch so do we need to mirror it? cf. https://github.com/github/renaming#renaming-existing-branches

**Comment by squeed** [comment]
We only need to mirror `main` to `master` if there is tooling out there that expects a git branch named `master` (that we don't feel like tracking down). Accesses to individual files via the github web UI will be redirected, but anything that uses git will not.
