### ISSUE TITLE
SYN/ACK is not SNATed for host with high connection churn

### ISSUE THREAD

**Issue by egsysoev** [cilium/cilium#23126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have many k8s clusters with the following configuration:

1. Cillium running without kube-proxy in native routing mode with DSR enabled.
2. K8s service with externalIP type announced to clients by BGP protocol. Endpoints of this service are Istio gateways.
3. Cilium Load Balancers as an entrypoint for clients.
4. Clients connect to applications running behind Istio using service external IP address (let's call it VIP).
5. Traffic flow is: 
- Client sends SYN to VIP (ipSrc = ClientIP, ipDst = VIP).
- SYN arrives to LB node. Cilium sends SYN to service endpoints - istio pods (ipSrc = ClientIP, ipDst = IstioPodIP).
- SYN arrives to Istio pod. Istio responds with SYN/ACK directly to client and Cilium replaces Istio Pod IP with VIP because of DSR mode. (**ipSRC = VIP**, ipDst = ClientIP).
- Client gets SYN/ACK and then connection is established.

![scheme](https://user-images.githubusercontent.com/23383527/212805724-a1a37d09-36b5-48e8-ba84-8c7c6caa596e.png)

Problem happens with clients with high connection churn rate: they get `connection timeout` error when they connect to the application in cluster. We got tcpdump on Istio nodes and noticed that in some cases there was an incorrect behaviour:
- Client sends SYN to VIP (ipSrc = ClientIP, ipDst = VIP).
- SYN arrives to LB node. Cilium sends SYN to service endpoints - istio pods (ipSrc = ClientIP, ipDst = IstioPodIP).
- SYN arrives to Istio pod. Istio responds with SYN/ACK directly to client BUT this time source IP address _is not replaced_ with VIP (**ipSRC = IstioPodIP**, ipDst = ClientIP).
- Client doesn't get SYN/ACK because it's dropped somewhere in the network path because of invalid source ip.
When this issue happens we see the same source port(ports) for such failed connection attempts. If we restart Istio pod the problem is gone for some time, but then appears again with new "invalid" source port.
- We checked CT and NAT on cilium on node with Istio pod and noticed that there is no problem ipSrc:portSrc in NAT table. 
```
# cilium bpf ct list global | grep 10.212.195.45 | grep 56772
TCP IN 10.212.195.45:56772 -> 10.80.178.120:8443 expires=3732265 RxPackets=140003 RxBytes=11480246 RxFlagsSeen=0x02 LastRxReport=3710665 TxPackets=240318 TxBytes=17265052 TxFlagsSeen=0x12 LastTxReport=3710665 Flags=0x0090 [ SeenNonSyn DSR ] RevNAT=0 SourceSecurityID=16778508 IfIndex=0

# cilium bpf nat list  | grep '10.212.195.45:56772'

```
ClientIP=10.212.195.45, ClientSrcPort=56772.
IstioPodIP=10.80.178.120, IstioDstPort=8443.

As a result all connections attempts from 10.212.195.45 with source port 56722 are failed because they never get to the NAT table. This is just an example - we have any "SrcIP:SrcPorts" which do not have entries in NAT table.

### Cilium Version

1.11.4

### Kernel Version

5.4.0-100-generic

### Kubernetes Version

1.21.14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by egsysoev** [comment]
Cilium sysdump is 120MB so I have upload it in parts.
Please run the following command before extracting archive (I had to add `.zip` extension in order to upload if to github):
```
mv  cilium-sysdump-20230113-185259-parted.z01.zip cilium-sysdump-20230113-185259-parted.z01
mv  cilium-sysdump-20230113-185259-parted.z02.zip cilium-sysdump-20230113-185259-parted.z02
mv  cilium-sysdump-20230113-185259-parted.z03.zip cilium-sysdump-20230113-185259-parted.z03
mv  cilium-sysdump-20230113-185259-parted.z04.zip cilium-sysdump-20230113-185259-parted.z04
mv  cilium-sysdump-20230113-185259-parted.z05.zip cilium-sysdump-20230113-185259-parted.z05
mv  cilium-sysdump-20230113-185259-parted.z06.zip cilium-sysdump-20230113-185259-parted.z06
```

[cilium-sysdump-20230113-185259-parted.zip](https://github.com/cilium/cilium/files/10431628/cilium-sysdump-20230113-185259-parted.zip)
[cilium-sysdump-20230113-185259-parted.z01.zip](https://github.com/cilium/cilium/files/10431675/cilium-sysdump-20230113-185259-parted.z01.zip)
[cilium-sysdump-20230113-185259-parted.z02.zip](https://github.com/cilium/cilium/files/10431679/cilium-sysdump-20230113-185259-parted.z02.zip)
[cilium-sysdump-20230113-185259-parted.z03.zip](https://github.com/cilium/cilium/files/10431680/cilium-sysdump-20230113-185259-parted.z03.zip)
[cilium-sysdump-20230113-185259-parted.z04.zip](https://github.com/cilium/cilium/files/10431681/cilium-sysdump-20230113-185259-parted.z04.zip)
[cilium-sysdump-20230113-185259-parted.z05.zip](https://github.com/cilium/cilium/files/10431683/cilium-sysdump-20230113-185259-parted.z05.zip)
[cilium-sysdump-20230113-185259-parted.z06.zip](https://github.com/cilium/cilium/files/10431684/cilium-sysdump-20230113-185259-parted.z06.zip)

**Comment by ysksuzuki** [comment]
This issue might be related to this. We hit a similar issue with v1.11.
https://github.com/cilium/cilium/pull/20006/commits

Now we upgraded to v1.12, and the issue was gone since the CT handling has improved, thanks to https://github.com/cilium/cilium/pull/18454.

**Comment by egsysoev** [comment]
@ysksuzuki Thanks for the reply.
The issue is similar but we do not use NodePort.

**Comment by brb** [comment]
>  The issue is similar but we do not use NodePort.

@egsysoev The LoadBalancer BPF implementation is using the NodePort BPF code. Indeed, from your symptoms it's very similar to what @ysksuzuki linked. Try upgrading Cilium.

**Comment by egsysoev** [comment]
OK, we will try to upgrade. 
Thank you @brb and @ysksuzuki.

**Comment by brb** [comment]
@egsysoev Any update?

**Comment by jonaz** [comment]
@egsysoev did the upgrade help? We are running into simliar problems which we yet dont know are related to this issue and we are running 1.12.4.
