### ISSUE TITLE
Bug: Docs: Flag --ipv4-native-routing-cidr has been deprecated in cli tool

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium#23144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Deprecation warning following the docs for Native-routed Datapath Modes using cilium CLI.
Doc Reference:
https://docs.cilium.io/en/v1.13.0-rc4/network/clustermesh/clustermesh/

Deprecated command:
```
cilium install --ipv4-native-routing-cidr=10.0.0.0/9
```
results in output:
```
Flag --ipv4-native-routing-cidr has been deprecated, This can now be overridden via `helm-set` (Helm value: `ipv4NativeRoutingCIDR`).

```

Instructions should be replaced with
```
cilium install --helm-set "ipv4NativeRoutingCIDR=10.0.0.0/9"
```

### Cilium Version

cilium version
cilium-cli: v0.12.12 compiled with go1.19.4 on linux/amd64
cilium image (default): v1.12.5
cilium image (stable): v1.12.5
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"

### Kernel Version

N/A - Documentation bug only.

### Kubernetes Version

AKS - but not relevant. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by measutosh** [comment]
Hello @jspaleta , @christarazi 

I would like to pick this up
Could you please lead me to the file where the changes need to be implemented or any other resources to get me started

**Comment by deepeshaburse** [comment]
Hi @jspaleta and @christarazi, I don't see a PR for this issue. Can I work on it?
