### ISSUE TITLE
Migrate contents of `contrib/vagrant/start.sh` to Vagrantfile itself

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2316]
Moving the contents of this script to the Vagrantfile itself would make it easier to run different lifecycle commands for Vagrant VMs (up, provision, reload, etc.).

**Comment by eloycoto** [comment]
Duplicated by https://github.com/cilium/cilium/issues/2316

**Comment by ianvernon** [comment]
@eloycoto you referenced this ticket as duplicating itself, which is not possible. Did you mean to reference another ticket?

**Comment by eloycoto** [comment]
Duplicated by https://github.com/cilium/cilium/issues/2900
