### ISSUE TITLE
Policy drops at L3, L4 or CIDR are all logged as "Policy denied (L3)"

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2317]
Any policy denial as per this function:

https://github.com/cilium/cilium/blob/67ea898d859c8d7011562acb0bee7a660c04e398/bpf/lib/policy.h#L26-L77

Can be passed up through a call to `send_drop_notify()`
https://github.com/cilium/cilium/blob/67ea898d859c8d7011562acb0bee7a660c04e398/bpf/bpf_netdev.c#L476-L478

And end up being interpreted in `cilium monitor` as an L3 drop:
https://github.com/cilium/cilium/blob/67ea898d859c8d7011562acb0bee7a660c04e398/pkg/bpfdebug/drop.go#L47

This can confuse people debugging datapath or policy issues, potentially misleading them.

* [ ] Change the error description for `Policy Denied (L3)` to `Policy Denied`
* [ ] Remove `DROP_POLICY_L4` from datapath (Done by #6921)
* [x] Remove `DROP_POLICY_CIDR` from datapath

**Comment by manalibhutiyani** [comment]
I can try this if I get some cycles

**Comment by joestringer** [comment]
In a whitelist model it's difficult to truly differentiate reasons for packet drop at L3/L4/CIDR, as it's only if there is no allow policy at any of these layers that we drop the packet, so at that point it's unclear whether the drop should be associated with any particular layer.

Probably the "Policy Denied (L3)" text could just be replaced with "Policy Denied" and the other two drop reasons can be retired.
