### ISSUE TITLE
CFP: Support default Ingress Class mode

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#23181]
## Cilium Feature Proposal
        
**Describe the feature you'd like**

Currently, Cilium Ingress Controller only watches and manages any Ingress object having `spec.ingressClassName` as Cilium. There is no way to configure Cilium as the default Ingress Controller i.e. no value spec.ingressClassName.

**(Optional) Describe your proposed solution**

This could be achieved by having a flag e.g. --include-empty-ingress-class or something similar). If enabled, the Cilium operator will manage Ingress having `spec.ingressClassName` as empty as well.

**Comment by youngnick** [comment]
We should probably also do IngressClass object support, and allow for setting a default IngressClass object too - as per https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class.
