### ISSUE TITLE
Errors and warnings about identity release

### ISSUE THREAD

**Issue by joaoubaldo** [cilium/cilium#23192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are experiencing some identity release related errors and warnings ever since we've upgraded Cilium 1.12.2 to 1.12.4 (we are running 1.12.5 at the moment and the errors persist) which are causing our log volume to snowball. 
The logs are:

```level=error msg="Unable to find identity of previously used CIDR" cidr=10.212.176.195/32 subsys=ipcache```

```level=warning msg="Unexpected release of non-CIDR identity, will leak this identity. Please report this issue to the developers." identity=remote-node labels="reserved:remote-node" subsys=ipcache```

Things checked:

When all Cilium agents are restarted these errors go away but after a while they come back and keep increasing over time:
![image](https://user-images.githubusercontent.com/3534309/213456683-3e9c3272-3749-4a71-a46b-37b6b984ae94.png)

Further looking for more information about the IPs present in the error message, we see that these IPs were always used in the past by Kubernetes nodes. Example:
```
level=error msg="Unable to find identity of previously used CIDR" cidr=10.212.176.195/32 subsys=ipcache
```

The associated identity:
```
$ k8s-cilium-exec.sh cilium bpf ipcache list | grep 10.212.176.195
10.212.176.195/32                           identity=16787104 encryptkey=0 tunnelendpoint=0.0.0.0
```

Identity labels (notice the `reserved:remote-node` label in one of the agents):
```
$ k8s-cilium-exec.sh cilium identity get 16787104
...
==== detail from pod cilium-4fmbb , on node ip-10-212-156-19.eu-west-1.compute.internal
ID         LABELS
16787104   cidr:52.218.118.16/32
           reserved:world
==== detail from pod cilium-mthdb , on node ip-10-212-146-165.eu-west-1.compute.internal
ID         LABELS
16787104   cidr:10.212.176.195/32
           reserved:remote-node
           reserved:world
...
```

There also seems to be a correlation with failed `endpoint-delete` API calls as shown:
![image](https://user-images.githubusercontent.com/3534309/213463131-fd9e1413-7fbe-41df-ad40-bd811f4f3965.png)
However we couldn't find much information about the reason for these failed calls.

All of this is suggesting that there can be a relationship between these errors logs and IPs that were assigned to nodes in the past but later reused by Pods. It's also worth mentioning that we autoscale nodes and services, as such, IPs are often recycled - here are some metrics for better context:
![image](https://user-images.githubusercontent.com/3534309/213466641-26086175-b55e-4163-8ffe-2a5efeb41d87.png)

Unfortunately we couldn't replicate this in a test environment.

Happy to share more details if needed.

### Cilium Version

1.12.5

### Kernel Version

Linux ip-10-211-126-220.eu-west-1.compute.internal 5.4.226-129.415.amzn2.x86_64 #1 SMP Fri Dec 9 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

Cannot share due to sensitive information

### Anything else?

FWIW, it seems that there were some recent changes to the identity releasing logic that can be related, namely in commits https://github.com/cilium/cilium/commit/5f20d7de700e859abe32f0bcfaf4a237498e7e80 https://github.com/cilium/cilium/commit/adbde6763580c3587648ad3cf39d980049dc88f5.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
Is this still the case with the latest v1.12.8?

**Comment by aanm** [comment]
@picadoh-jumo, @adzeeman, @danielatjumo, @matosf, @ribeirux, @benmichael, @brunopalos, @HeinrichFilter, @mantoine96 @joaoubaldo can you report back to see if v1.12.9 still has this issue? Thank you

**Comment by mantoine96** [comment]
Will build our new image on 1.12.9 and let you know ASAP! Thanks!

**Comment by jerryguowei** [comment]
I are working to migrate from calico to cilium on our EKS cluster and got the similar errors. 
`level=error msg="Unable to find identity of previously used CIDR 10.0.72.144/32" subsys=ipcache`
This error caused we are not able to access the k8s api server, which is in `10.0.72.144/32`. We have to restart all cilium pods to resolve the issue.
we are running in the latest stable version 1.13.2

**Comment by joaoubaldo** [comment]
@aanm this is still happening with 1.12.9.
