### ISSUE TITLE
Add support for docker buildx v0.10 in build process

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#23223]
We have recently hit a spate of issues in CI due to the upstream GitHub worker version bump of docker buildx from v0.9 to v0.10. In order to mitigate, we have pinned the buildx version to v0.9 for now.

We should investigate what steps are necessary to support v0.10 in our CI. This includes:
* [ ] Ensure SBOM generation works with v0.10.
* [ ] Ensure that when v0.10 images are built (MediaType OCI v1), other CI actions can successfully detect these new images and pull them.
* [ ] Ensure that these images can be copied to popular cloud container registries (skopeo).
* [ ] Ensure that common container runtimes (containerd etc.) can pull these images.

Related: https://github.com/cilium/cilium/pull/23220

**Comment by joestringer** [comment]
Issues we previously hit with this:

- Image signing as part of the image build workflows for image signing would fail with this:
    ```
    level=fatal msg="generating doc: creating SPDX document: generating
    SPDX package from image ref quay.io/cilium/docker-plugin-ci:XXX:
    generating image package"
    ```
- Image builds might pass, but then the "wait for images to be ready" step would fail because `docker manifest ...` would never successfully identify that the target image was available

**Comment by aanm** [comment]
Fixed with https://github.com/cilium/cilium/pull/23431
