### ISSUE TITLE
Document that `install-egress-gateway-routes` is specific to EKS

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#23256]
The `install-egress-gateway-routes` flag, aka the `egressGateway.installRoutes` Helm value, is needed on EKS's ENI mode to steer traffic through the proper interfaces.

It is [documented in the egress gateway guide](https://docs.cilium.io/en/stable/gettingstarted/egress-gateway/#compatibility-with-cloud-environments), but we never mention that it's only meant for ENI mode. We should fix that as it can break things on other setups (e.g., known to cause issues on GKE).

**Comment by deepeshaburse** [comment]
@pchaigno Can I take this up?

**Comment by pchaigno** [comment]
@deepeshaburse Sure, go ahead. Don't hesitate to ask in Slack #development if you need help.
