### ISSUE TITLE
AKS Cluster Mesh Documented Instructons result in connectivity test failures.

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium#23266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running through BYOCNI AKS cluster mesh quick start guide documentation resulted in connectivity test errors.
https://docs.cilium.io/en/v1.13.0-rc4/network/clustermesh/aks-clustermesh-prep/#gs-clustermesh-aks-prep

I'm not sure if this is a bug in cilium-cli install, setting up for AKS incorrectly, or if its a bug in the documentation for preparing Azure resources.

Tested with cilium v1.12.5 and v1.13.0-rc4, same connectivity test failures occur

### Cilium Version

v1.12.5 and v1.13.0-rc4

### Kernel Version

kubectl -n kube-system exec -it ds/cilium -- uname -a
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init)
Linux aks-nodepool1-16441422-vmss000000 5.4.0-1098-azure #104~18.04.2-Ubuntu SMP Tue Nov 29 12:13:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"c86d003ea699ec4bcffee10ad563a26b63561c0e", GitTreeState:"clean", BuildDate:"2022-12-17T10:31:53Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230123-123225.zip](https://github.com/cilium/cilium/files/10484296/cilium-sysdump-20230123-123225.zip)

### Relevant log output

```shell
$ cilium connectivity test --context $CLUSTER1 --multi-cluster $CLUSTER2 --test "no-policies" --verbose

Test Report
❌ 1/1 tests failed (18/48 actions), 31 tests skipped, 1 scenarios skipped:
Test [no-policies]:
  ❌ no-policies/pod-to-remote-nodeport/curl-0: cilium-test/client-755fb678bd-gnb2z (10.10.2.161) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-1: cilium-test/client-755fb678bd-gnb2z (10.10.2.161) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-2: cilium-test/client-755fb678bd-gnb2z (10.10.2.161) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-3: cilium-test/client-755fb678bd-gnb2z (10.10.2.161) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-4: cilium-test/client-755fb678bd-gnb2z (10.10.2.161) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-7: cilium-test/client-755fb678bd-gnb2z (10.10.2.161) -> cilium-test/echo-same-node (echo-same-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-8: cilium-test/client-755fb678bd-gnb2z (10.10.2.161) -> cilium-test/echo-same-node (echo-same-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-9: cilium-test/client-755fb678bd-gnb2z (10.10.2.161) -> cilium-test/echo-same-node (echo-same-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-12: cilium-test/client2-5b97d7bc66-k9mmt (10.10.2.54) -> cilium-test/echo-same-node (echo-same-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-13: cilium-test/client2-5b97d7bc66-k9mmt (10.10.2.54) -> cilium-test/echo-same-node (echo-same-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-14: cilium-test/client2-5b97d7bc66-k9mmt (10.10.2.54) -> cilium-test/echo-same-node (echo-same-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-15: cilium-test/client2-5b97d7bc66-k9mmt (10.10.2.54) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-16: cilium-test/client2-5b97d7bc66-k9mmt (10.10.2.54) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-17: cilium-test/client2-5b97d7bc66-k9mmt (10.10.2.54) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-18: cilium-test/client2-5b97d7bc66-k9mmt (10.10.2.54) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-remote-nodeport/curl-19: cilium-test/client2-5b97d7bc66-k9mmt (10.10.2.54) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-local-nodeport/curl-1: cilium-test/client-755fb678bd-gnb2z (10.10.2.161) -> cilium-test/echo-other-node (echo-other-node:8080)
  ❌ no-policies/pod-to-local-nodeport/curl-2: cilium-test/client2-5b97d7bc66-k9mmt (10.10.2.54) -> cilium-test/echo-other-node (echo-other-node:8080)
```

### Anything else?

I was able to fix the pod-to-local-nodeport errors with a modified call to 
`az network vnet peering create` including the `--allow-gateway-transit` option.
But I can't find a way to fix the `no-policies/pod-to-local-nodeport` test errors

Vnet based network peering appears to be working as expected. pod-to-pod tests pass and the cilium-health command reports back agent-to-agent connectivity across both clusters.

```
$ kubectl -n kube-system exec -it ds/cilium -- cilium-health status
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init)
Probe time:   2023-01-23T23:06:26Z
Nodes:
  jspaleta-26504/aks-nodepool1-16441422-vmss000000 (localhost):
    Host connectivity to 192.168.20.4:
      ICMP to stack:   OK, RTT=269.602µs
      HTTP to agent:   OK, RTT=285.201µs
    Endpoint connectivity to 10.20.1.252:
      ICMP to stack:   OK, RTT=275.902µs
      HTTP to agent:   OK, RTT=187.301µs
  jspaleta-22766/aks-nodepool1-31783417-vmss000000:
    Host connectivity to 192.168.10.4:
      ICMP to stack:   OK, RTT=74.180935ms
      HTTP to agent:   OK, RTT=73.07483ms
    Endpoint connectivity to 10.10.0.84:
      ICMP to stack:   OK, RTT=72.94613ms
      HTTP to agent:   OK, RTT=73.462932ms
  jspaleta-22766/aks-nodepool1-31783417-vmss000001:
    Host connectivity to 192.168.10.5:
      ICMP to stack:   OK, RTT=68.017907ms
      HTTP to agent:   OK, RTT=67.772806ms
    Endpoint connectivity to 10.10.1.121:
      ICMP to stack:   OK, RTT=67.700006ms
      HTTP to agent:   OK, RTT=68.096407ms
  jspaleta-22766/aks-nodepool1-31783417-vmss000002:
    Host connectivity to 192.168.10.6:
      ICMP to stack:   OK, RTT=65.308795ms
      HTTP to agent:   OK, RTT=64.989194ms
    Endpoint connectivity to 10.10.2.195:
      ICMP to stack:   OK, RTT=65.039694ms
      HTTP to agent:   OK, RTT=65.229995ms
  jspaleta-26504/aks-nodepool1-16441422-vmss000001:
    Host connectivity to 192.168.20.5:
      ICMP to stack:   OK, RTT=714.703µs
      HTTP to agent:   OK, RTT=225.801µs
    Endpoint connectivity to 10.20.0.70:
      ICMP to stack:   OK, RTT=667.003µs
      HTTP to agent:   OK, RTT=656.403µs
  jspaleta-26504/aks-nodepool1-16441422-vmss000002:
    Host connectivity to 192.168.20.6:
      ICMP to stack:   OK, RTT=869.604µs
      HTTP to agent:   OK, RTT=198.601µs
    Endpoint connectivity to 10.20.2.192:
      ICMP to stack:   OK, RTT=469.002µs
      HTTP to agent:   OK, RTT=525.302µs
```

It seems like its something specific to how Kubernetes services are being handled.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jspaleta** [comment]
This is really starting to feel like either a kube-proxy or AKS service load balancer hiccup. 
As its just impacting nodeport. I'm just not familiar enough with what AKS is doing here with regard to NodePort.

I think I can have AKS disable kube-proxy entirely and I'm going to try to replace with cilium.

**Comment by jspaleta** [comment]
Okay... disabling kube-proxy as part of aks creation  and letting cilium install autodetect to replace it seems to solve the failing tests for me.  
I should be able to put a documentation PR up for the AKS specific docs tomorrow.

**Comment by jspaleta** [comment]
So real quick here are my workaround changes.

Prior to installing cilium, either at aks creation time or as an aks update need to disable kube-proxy following: 
https://learn.microsoft.com/en-us/azure/aks/configure-kube-proxy#utilize-kube-proxy-configuration-in-a-new-or-existing-aks-cluster-using-azure-cli

But its a multi step process to get your az cli tool setup with the kube-proxy extension.  
We could document it as a workaround, but I think I'd rather try to figure out why have kube-proxy installed is failing connectivity tests.

**Comment by YutaroHayakawa** [comment]
I think this is an expected behavior. To do Global NodePort work, we need to turn on KPR since the KubeProxy doesn’t know about global service annotation. Yep, we need to document it.

**Comment by jspaleta** [comment]
So probably need to update these:
https://docs.cilium.io/en/v1.13.0-rc4/network/clustermesh/clustermesh/#gs-clustermesh to add a note about kpr related cluster mesh features (at a minimum global service limitations)

https://docs.cilium.io/en/v1.13.0-rc4/network/clustermesh/aks-clustermesh-prep/#gs-clustermesh-aks-prep to provide kpr "happy path" instructions

https://docs.cilium.io/en/v1.13.0-rc4/network/clustermesh/affinity/ to add a note about kpr impact on global NodePort services
