### ISSUE TITLE
Add support for actions/checkout v3.2.0 or later

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#23268]
It seems that when dependabot suggests to bump the `actions/checkout` action to v3.2.0 or later, the `build-commits` workflow fails with:

```
llc -march=bpf -mattr=dwarfris -mcpu=v2 -filetype=obj -o bpf_sockops.o bpf_sockops.ll
/bin/bash: line 1: llc: command not found
```

https://github.com/cilium/cilium/pull/22708#pullrequestreview-1215903722

This issue tracks progress on resolving this so that we can bump this dependency.

**Comment by aanm** [comment]
@brlbil @nbusseneau can you take a look at this one?
