### ISSUE TITLE
docs: incorporate the OpenSSF Scorecard into the README

### ISSUE THREAD

**Issue by lizrice** [cilium/cilium#23287]
A recommendation from the Cilium security audit is to incorporate the [OpenSSF Scorecard](https://securityscorecards.dev/) badge into the project README

**Comment by xmulligan** [comment]
A lot of this already overlaps with the CLOmonitor https://clomonitor.io/projects/cncf/cilium#cilium_security which we already added in https://github.com/cilium/cilium/pull/19105
