### ISSUE TITLE
CI: K8sDatapathServicesTest Checks N/S loadbalancing Tests with direct routing and DSR

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#23309]
```
Stacktrace

/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
Can not connect to service "tftp://[fd04::11]:31852/hello" from outside cluster (6/10)
Expected command: kubectl exec -n kube-system log-gatherer-wbhjl -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://[fd04::11]:31852/hello -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" | grep client_address= 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 command terminated with exit code 71
```

Jenkins: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/514/testReport/Suite-k8s-1/26/K8sDatapathServicesTest_Checks_N_S_loadbalancing_Tests_with_direct_routing_and_DSR/
Sysdump: 
[cilium-sysdump.7z.zip](https://github.com/cilium/cilium/files/10492991/cilium-sysdump.7z.zip)

**Comment by tklauser** [comment]
Seen on #28972 (against `v1.13` branch): https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1032/

[cilium-sysdump.zip](https://github.com/cilium/cilium/files/13279768/cilium-sysdump.zip)
