### ISSUE TITLE
CI: TestGetIdentity/Duplicated_identity failure

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#23314]
### Description

Failure link https://app.travis-ci.com/github/cilium/cilium/jobs/594047847, this issue is replicated locally as well.

```
=== RUN   TestGetIdentity/Duplicated_identity
    identity_test.go:218: Expected key 10, got 11
    identity_test.go:218: Expected key 10, got 11
    --- FAIL: TestGetIdentity/Duplicated_identity (0.03s)
```

From the first look, the test expectation is to get key 10, however, the underlying `get` method didn't guarantee any particular order while retrieving element from map.

https://github.com/cilium/cilium/blob/master/pkg/k8s/identitybackend/identity.go#L219-L242

**Comment by joestringer** [comment]
#23229 traces the cause of this to https://github.com/cilium/cilium/pull/23064 which was not marked for backport to 1.13, so it looks like this does not affect 1.13 at this time.

**Comment by sayboras** [comment]
> it looks like this does not affect 1.13 at this time.

thanks, I overlooked on this :+1:
