### ISSUE TITLE
CI: TestGetIdentity/Duplicated_identity: `identity_test.go:218: Expected key 10, got 11`

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#23311]
## CI failure

```
--- FAIL: TestGetIdentity (0.61s)
    --- FAIL: TestGetIdentity/Duplicated_identity (0.03s)   
    identity_test.go:218: Expected key 10, got 11
```

Travis: https://app.travis-ci.com/github/cilium/cilium/jobs/594073675

**Comment by joestringer** [comment]
Looks like https://github.com/cilium/cilium/issues/23314 was posted after this but has more pointers / links. Closing duplicate.
