### ISSUE TITLE
Enhancement: Kind-based testing and better test coverage for Cluster Mesh

### ISSUE THREAD

**Issue by YutaroHayakawa** [cilium/cilium#23322]
This issue tracks the series of test enhancements of Cluster Mesh. This can be divided into several tasks.

**Migrate the current GCP-based testing infrastructure to a Kind-based infrastructure for better speed and flakiness**
At this point, we don't need to add any test cases. Only Kind migration should be done.

**Make a feature matrix and test scenarios for them (like a [datapath test](https://github.com/cilium/cilium/blob/master/.github/workflows/conformance-datapath.yaml#L123-L185))**
From Cluster Mesh's perspective, inter-cluster communication is the same as inter-node communication, so the datapath test covers most basic connectivity functionalities. So, we should focus on testing the Global / Shared service under some conditions. My suggestion would be like this.
  - encryption: "none" | "ipsec" | "wireguard"
  - tunnel: "disabled" | "vxlan"
  - ipFamily: "ipv4-only" | "dual-stack" | "ipv6-only"
  
Here are some issues that led me to create this issue.
- We couldn’t notice that Cluster Mesh was not working at all in IPv6 single stack environment (https://github.com/cilium/cilium/pull/22962)
- Wireguard test is somehow very flaky in GCP (It's not the matter of WireGuard test I think. I could complete the test in my local with Kind. Ref: https://github.com/cilium/cilium/pull/23045)

I have [partially done the Kind migration](https://github.com/cilium/cilium/compare/master...YutaroHayakawa:cilium:yutaro/oss/clustermesh-tests
). Please use this as an example. I currently use nektos/act for local testing, but it may not be accepted on upstream given the context in https://github.com/cilium/cilium/pull/20118. If it is still the case, let's remove act part on the actual PR (it is still useful for local testing, I think).

This issue can be closed once all the above tasks are achieved.

**Comment by giorio94** [comment]
Assigning to myself
