### ISSUE TITLE
contrib: Set custom DNS resolver for Kind nodes

### ISSUE THREAD

**Issue by brb** [cilium/cilium#23330]
We are using our [Kind provisioning script](https://github.com/cilium/cilium/blob/master/contrib/scripts/kind.sh) to create K8s clusters when testing in the CI (e.g., https://github.com/cilium/cilium/blob/master/.github/workflows/conformance-datapath.yaml).

Recently, we discovered that on some kernels a default DNS resolver, which is `dockerd`, is troublesome for the BPF host routing, which we want to test in the CI (https://github.com/cilium/cilium/issues/23283).

This issue is about extending the provisioning script to allow us to set a custom upstream DNS resolver (e.g., `1.1.1.1` or `8.8.8.8`) to Kind nodes.

A few ideas how to do that:
- Pass a custom `/etc/resolv.conf` to kubelet via `--resolv-conf` in the Kind / kubeadm config.
- Override `/etc/resolv.conf` of Kind nodes after creating a cluster (no race condition, as CoreDNS pods won't be started, as a CNI is not ready).
- Patch `kube-system/coredns` ConfigMap.
- Patch Kind to allow users to specify custom DNS entries (i.e., `docker run --dns="1.1.1.1,8.8.8.8"`).

**Comment by ChinmayaSharma-hue** [comment]
What would be the preferred method for specifying custom DNS resolvers in the provisioning script, by passing the path to a custom resolv.conf file or directly providing the DNS entries in the command line?

**Comment by brb** [comment]
@ChinmayaSharma-hue Ideally the second approach ("directly providing the DNS entries in the command line"). Just that it can be done in a Kind configuration file.

**Comment by yasintahaerol** [comment]
Hi 👋  I am interested in this issue. Could you assign me ?

**Comment by brb** [comment]
Hey @yasintahaerol , sure!

**Comment by lmb** [comment]
This might be relevant: https://github.com/kubernetes-sigs/kind/blob/77675009ce7862102f2d4a6c6b61b8094f964ebb/images/base/files/usr/local/bin/entrypoint#L396-L433

Set via https://github.com/kubernetes-sigs/kind/blob/6b58c9dfcbdb1b3a0d48754d043d59ca7073589b/pkg/cluster/internal/providers/docker/provision.go#L203-L205

I don't think this allows specifying the nameserver directly, but it might give a clue

- how to influence KIND to choose a different nameserver?
- how to add KIND_DNS_NAMESERVER or similar to upstream

**Comment by brb** [comment]
@yasintahaerol Hey, do you need help with this issue?
