### ISSUE TITLE
Problem with company security basic implementation was easy.

### ISSUE THREAD

**Issue by killgapwalker** [cilium/cilium#23350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to implement basic iptable construction in prebuild mode but havent got file type drop in iptable extension !? Maybe some people can text her some basic example for file type drop in u32 ?/iptables u32 Hex logic (obfuscation,virus) construction drop?!( I have donation money )

### Cilium Version

Polycube iptable.

### Kernel Version

Some kernel headers.

### Kubernetes Version

Polycube version looking  as new.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hi, can you describe what issue you are having? Thank you

**Comment by killgapwalker** [comment]
> Hi, can you describe what issue you are having? Thank you

Probably it is iptables u32 file type drop knowledge ,they are missing ! Actualy need help with iptables file type drop or even hex virus logic drop example.

**Comment by pchaigno** [comment]
The polycube project is not maintained by the Cilium community. Please open an issue on the Polycube repository if you are having issues with that software.
