### ISSUE TITLE
Cilium agent opens ports in all interfaces (maybe unnecessarily?)

### ISSUE THREAD

**Issue by cortopy** [cilium/cilium#23353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've noticed that cilium agent opens several ports on all interfaces, while some ports only listen on localhost.

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:9879          0.0.0.0:*               LISTEN      1345831/cilium-agen 
tcp        0      0 127.0.0.1:9890          0.0.0.0:*               LISTEN      1345831/cilium-agen 
tcp6       0      0 :::4244                 :::*                    LISTEN      1345831/cilium-agen 
tcp6       0      0 :::4240                 :::*                    LISTEN      1345831/cilium-agen 
tcp6       0      0 :::36195                :::*                    LISTEN      1345831/cilium-agen 
tcp6       0      0 :::9962                 :::*                    LISTEN      1345831/cilium-agen 
udp6       0      0 :::36195                :::*                                1345831/cilium-agen
````

I'm trying to secure a cluster where all traffic between nodes goes through a private network, but then Cilium agent is listening on all interfaces. It seems to me that this makes security more difficult to implement. I wasn't able to find documentation about what those ports do, but I would expect them to listen on the interface of the node's InternalIP.

I found that a similar question was asked in [Slack](https://cilium.slack.com/archives/C1MATJ5U5/p1670496809639599), and it was suggested that a new issue should be opened if using a recent version of cilium.

### Cilium Version

cilium-cli: v0.12.11 compiled with go1.19.3 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.5
cilium image (running): v1.12.3

### Kernel Version

Linux node1 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.23

### Anything else?

I've tried using firewall, but setting up an external firewall with cilium is breaking connectivity. It feels like this solution is bound to create many issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ydp** [comment]
I have a similar question, does cilium support configure interface or node CIDR to use for pod to pod traffic? Like what Antrea did in this issue https://github.com/antrea-io/antrea/pull/2704

**Comment by meyskens** [comment]
Unassigned myself as #24011 is merged which handles the case for all Envoy proxy ports being bound to all interfaces.
There are still services left on the above mentioned ports which should be looked into but I am probably not the best person to investigate those :)

**Comment by mhofstetter** [comment]
These are the ports which are still bound to all interfaces. Except the dynamically assigned DNS proxy redirect port - all of them are documented as mentioned by @rolinh 

`4240` -> Agent Health
`4244` -> Hubble Server
`9962` -> Agent Prometheus Metrics
`36195` -> DNS Proxy redirect port (dynamically assigned - can be double-checked by executing `cilium status --all-redirects` and checking `Proxy Status` output from within the Cilium Agent Pod)

**Comment by aanm** [comment]
@mhofstetter can we open the DNS proxy ones on the local interfaces?

**Comment by aanm** [comment]
We have addressed the overall concern in this issue and the remaining open ports are

* `4240` -> Agent Health
* `4244` -> Hubble Server (uses TLS)
* `9962` -> Agent Prometheus Metrics

Both `Agent Health` and `Agent Prometheus Metrics` are necessary to receive connections from outside of the node so we can't simply open them in the localhost. Pinning them to the node's InternalIP, as proposed in the issue description, is good solution and so, if you want, feel free to open a PR with that solution implemented.

Thank you!

**Comment by tamilmani1989** [comment]
@aanm I like to pick this up if not by anyone else

**Comment by aanm** [comment]
@tamilmani1989 sure, what do you have in mind?

**Comment by tamilmani1989** [comment]
@aanm as you mentioned in above comment, I'm considering to make `Agent Health` and `Agent Prometheus Metrics` to listen on `nodeip` instead of listening on all interfaces

**Comment by tamilmani1989** [comment]
looked at the code.. can update for agent health but little complicated for Prometheus. Prometheus address and port coming via cilium config and default config is set to `:9962`. 
https://github.com/cilium/cilium/blob/bbdad5d38364ce9d715f57986fa2f11361a326d9/pkg/metrics/registry.go#L38C43-L38C62 

I'm not sure if we can override config and change that internally. Let me know if you have any suggestions here.

**Comment by rolinh** [comment]
> Does hubble server (4244) requires receiving connections from outside?

Yes.

**Comment by tamilmani1989** [comment]
For prometheus, I tried to update to listen on nodeip here https://github.com/cilium/cilium/blob/d5ee4e70cfa5ea6941633d1cce545a541875b964/pkg/metrics/registry.go#L27C1-L27C1 to

```
var defaultRegistryConfig = RegistryConfig{
	PrometheusServeAddr: fmt.Sprintf("%s:9962", node.GetCiliumEndpointNodeIP()),
}
```
and importing node package resulted in cyclic dependency error. any suggesions here?
