### ISSUE TITLE
bugtool: Provide a wrapper script for executing from k8s master node

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#2338]
It would be nice if there is a wrapper script for bugtool that:

- calls `cilium bugtool` on all the cilium pods.
- captures logs from cilium pods. It might also be useful to get `kubectl logs --previous` in case cilium crashed.
- bundles all the output files into a single tgz file.

**Comment by manalibhutiyani** [comment]
@scanf : Please feel free re-assign if you don't have enough cycles.

**Comment by tgraf** [comment]
Duplicate of #2256
