### ISSUE TITLE
AWS EKS - unable to find ifindex for interface MAC

### ISSUE THREAD

**Issue by li3** [cilium/cilium#23423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On EKS 1.23, with Cilium 1.12.6.

Once in awhile pods will get stuck in ContainerCreating with errors like:

> Warning  FailedCreatePodSandBox  5m22s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "88b9759456ee02b38d26cc1d9d094c1dbb8ea52cb5eaee4a0c515c24589065bd": plugin type="cilium-cni" name="cilium" failed (add): unable to setup interface datapath: unable to install ip rules and routes: unable to find ifindex for interface MAC: interface with MAC 06:c1:5a:44:3c:26 not found

We are using Karpenter for autoscaling. Error seems to happen on new and old nodes at random. Replacing the node does not always fix the issue. We have set max-pod values on our nodes to a value roughly 90% of the [max pods text file](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt). The issue has happened on nodes with almost no pods, and on nodes running 100+.

Sometimes the pod seems to get stuck forever, and other times it will resolve itself after approximately 10 minutes.

Restarting the cilium pod on the node and affected pods scheduled on the node seems to have no impact.

Unsure if its relevant, but this seems to only happen on our clusters in eu-central-1. The issue has not been reported on our us-east-1 clusters, but they have different usage patterns.

### Cilium Version

cilium image (stable): v1.12.6
cilium image (running): v1.12.6

### Kernel Version

Linux ip-10-192-4-239.ec2.internal 5.4.226-129.415.amzn2.x86_64 #1 SMP Fri Dec 9 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.14-eks-ffeb93d", GitCommit:"96e7d52c98a32f2b296ca7f19dc9346cf79915ba", GitTreeState:"clean", BuildDate:"2022-11-29T18:43:31Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

Generated sysdump is 180mb and will not upload...

### Relevant log output

```shell
Warning  FailedCreatePodSandBox  5m22s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "88b9759456ee02b38d26cc1d9d094c1dbb8ea52cb5eaee4a0c515c24589065bd": plugin type="cilium-cni" name="cilium" failed (add): unable to setup interface datapath: unable to install ip rules and routes: unable to find ifindex for interface MAC: interface with MAC 06:c1:5a:44:3c:26 not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Note you can limit the sysdump collecting to only a node having this issue, with `--node-list`. See https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection for details.
