### ISSUE TITLE
Cilium Monitor Not Working

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#2342]
current cilium stable, minikube version: v0.22.3

```
root@minikube:/# cilium version
Cilium 1.0.0-rc2 2f33f7a Wed, 6 Dec 2017 15:22:37 -0800 go version go1.9 linux/amd64
```

Cilium status is fine: 

```
root@minikube:/# cilium status
KVStore:                Ok   Etcd: http://127.0.0.1:2379 - (Leader) 3.1.5
ContainerRuntime:       Ok   
Kubernetes:             Ok   OK
Kubernetes APIs:        ["core/v1::Node", "CustomResourceDefinition", "cilium/v2::CiliumNetworkPolicy", "extensions/v1beta1::NetworkPolicy", "networking.k8s.io/v1::NetworkPolicy", "core/v1::Service", "core/v1::Endpoint", "extensions/v1beta1::Ingress"]
Cilium:                 Ok   OK
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
Known cluster nodes:
 minikube (localhost):
  Primary Address:   192.168.99.100
   Type:             InternalIP
  AllocRange:        10.15.0.0/16
```

```
root@minikube:/# cilium monitor
Listening for events on 2 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
Error: unable to connect to monitor dial unix /var/run/cilium/monitor.sock: connect: connection refused
```

There is not gops output: 

```
root@minikube:/# gops    
1006 701 gops                 go1.9 /usr/local/bin/gops
255  1   cilium-node-monitor  go1.9 /usr/bin/cilium-node-monitor
262  1   cilium-health      * go1.9 /usr/bin/cilium-health
1    0   cilium-agent       * go1.9 /usr/bin/cilium-agent
root@minikube:/# gops stack 255
couldn't get port by PID: dial tcp 127.0.0.1:0: getsockopt: connection refused
```

I was told there are no logs for cilium-node-monitor, but I did confirm via "ps" that it was running: 

```
root@minikube:/# ps -Af | grep cilium
root         1     0  0 01:26 ?        00:00:02 cilium-agent --debug=false -t vxlan --kvstore etcd --kvstore-opt etcd.config=/var/lib/etcd-config/etcd.config --disable-ipv4=false
root       255     1  0 01:27 ?        00:00:00 cilium-node-monitor
root       262     1  0 01:27 ?        00:00:01 cilium-health -d
root       908   701  0 01:33 ?        00:00:00 grep cilium
```

**Comment by rlenglet** [comment]
gops is not enabled in this daemon. It would be extremely helpful to debug an issue like this. It's a matter of adding those 4 lines, cf. https://github.com/cilium/cilium/blob/master/daemon/main.go#L128:
```
	if err := gops.Listen(gops.Options{}); err != nil {
		errorString := fmt.Sprintf("unable to start gops: %s", err)
		fmt.Println(errorString)
		os.Exit(-1)
	}
```

**Comment by aalemayhu** [comment]
Some steps to reproduce would be nice. I tried seeing if there were any issues via minikube, not that it matters but using v0.23.0. Monitor is showing output here. Do you see the same issue with the master branch? I can carefully go through the launcher refactoring Joe did in c7a63484d9cc (pkg: Refactor monitor launcher common code, 2017-11-27) and see if there is some regression.

**Comment by danwent** [comment]
On a clean minikube, this works for me.  I think the above happened after minikube was running for a while, but I do not have steps to reproduce.  

I'd suggest that we at least figure out what debugging features we would need to root cause such an issue in the future and file items to add them.   Right now it doesn't seem like there were logs or the ability to do gops dumps.   

I don't know enough about the internals of cilium-node-monitor to have a hypothesis of the underlying issue (e.g., deadlock?) or to comment on whether a manual audit of the code would be a good use of time, so I'll defer to you all on that.

**Comment by aalemayhu** [comment]
OK, let's leave this open for now. I can try to do longer test runs this weekend with minikube.
Thanks.

**Comment by aalemayhu** [comment]
Can reproduce this now. It seems to take a couple of days before the process becomes defunct. I will add some more logging and use a prefix so it's easier to distinguish between the regular agent. Not sure exactly what is going wrong but will debug before working on a fix.

**Comment by aalemayhu** [comment]
Just to avoid any confusion I was testing with `cilium:stable` earlier. Will also check latest later.

**Comment by aalemayhu** [comment]
While attempting to reproduce with the latest image, experienced that `kubectl` stopped working. Attaching the logs from `minikube logs`, maybe this is caused by a OOM? 

[minikube_logs.txt](https://github.com/cilium/cilium/files/1593169/minikube_logs.txt)

**Comment by rlenglet** [comment]
Seems like kube-apiserver got killed. Happens every few days for me. Just `minikube ssh` then restart the `localkube` service.

**Comment by aalemayhu** [comment]
I am trying to reproduce this with the latest image + extra logs but just keep hitting `minikube` issues after running for a while... Tried using ssh as suggested above but it does not work. Will try reproducing this in a Docker deployment. @raybejjani have you seen this monitor issue before? 

```
a@alemayhu:~$ minikube ssh
E0110 13:53:51.010515   22039 ssh.go:53] Error attempting to ssh/run-ssh-command: ssh: handshake failed: read tcp 127.0.0.1:59652->127.0.0.1:34030: read: connection reset by peer
```

```
a@alemayhu:~$ minikube status
E0110 13:56:37.979637   22141 status.go:80] Error getting cluster bootstrapper: getting localkube bootstrapper: getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: read tcp 127.0.0.1:59692->127.0.0.1:34030: read: connection reset by peer
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
Y
```

**Comment by raybejjani** [comment]
No, I haven't. I recall having to configure a port somewhere to allow minikube ssh (probably in virtualbox). If the errors are instant then it's more likely something like a non-open port.
Does kubectl work? minikube sets up the host-side kubectl to work with minikube. If it works then it's specific to ssh, if not then it might be outside minikube.

**Comment by aalemayhu** [comment]
I have been running the monitor for days and weeks on some deployments and have not seen this issue there. The monitor is running fine in actual deployments, so I suspect this is a minikube only problem. I don't think I can justify spending much more time on it. So closing, please reopen if you disagree and would like to reassign.

**Comment by tgraf** [comment]
Adding to @scanf: gops support has been added to allow debugging this issue should it occur again next time.
