### ISSUE TITLE
After setting cilium ds resources such as request and limit - its failing on new nodes

### ISSUE THREAD

**Issue by Vishwavijet** [cilium/cilium#23436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm trying to set requests and limits for cilium ds in eks cluster.
Once the resources are set, pods are working fine.

But when the scaling of nodes is happening and on the new nodes we are facing below error from cilium
```
level=error msg=“error while opening/creating BPF maps” error=“Unable to create map /sys/fs/bpf/tc/globals/cilium_nodeport_neigh4: cannot allocate memory” subsys=daemon
level=fatal msg=“Error while creating daemon” error=“error while opening/creating BPF maps: Unable to create map /sys/fs/bpf/tc/globals/cilium_nodeport_neigh4: cannot allocate memory” subsys=daemon
```

### Cilium Version

1.12.1

### Kernel Version

5.15.0-1019-aws

### Kubernetes Version

1.22.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
What are the limits you are setting? Have you considered bumping them? I'd expect to see that error when the limits are set too low.

**Comment by Vishwavijet** [comment]
The resources such as requests and limits were set as below
"resources.requests.cpu" = "300m"
"resources.requests.memory" = "600Mi"
"resources.limits.cpu" = "600m"
"resources.limits.memory" = "1G"

We increased the limit 50% more than this, even though the avg utlization was far below this threshold and yet we faced the errors.

**Comment by christarazi** [comment]
We don't recommend setting CPU or memory limits at all. See https://twitter.com/thockin/status/1134193838841401345.

Requests are recommended and we don't recommend CPU request below 1 core and below 1G of memory.

---

As far as I can tell, this is not a bug in Cilium as the errors you're facing are directly resulting from the resource configuration you are applying.
