### ISSUE TITLE
linux-datapath trying to index with <nil>

### ISSUE THREAD

**Issue by nikhiljha** [cilium/cilium#23440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

> level=warning msg="Unable to install direct node route {Ifindex: 0 Dst: 2607:f140:8801:1::100/120 Src: <nil> Gw: <nil> Flags: [] Table: 0 Realm: 0}" error="unable to lookup route for node <nil>: numerical result out of range" subsys=linux-datapath

### Cilium Version

```
cilium image (default): v1.12.5
cilium image (stable): v1.12.6
cilium image (running): v1.12.5
```

### Kernel Version

Linux ... 6.0.10 #1-NixOS SMP PREEMPT_DYNAMIC Sat Nov 26 08:27:56 UTC 2022 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

https://ocf.berkeley.edu/~njha/tmp/cilium-sysdump-20230129-185915.zip

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nikhiljha** [comment]
possibly related to https://github.com/cilium/cilium/issues/8084

**Comment by pchaigno** [comment]
Do you have reproduction steps for this? How does the Cilium configuration differ from the default configuration?

**Comment by nikhiljha** [comment]
I believe this happens when DSR is enabled but the node CIDR size is improperly configured. This was the Cilium configuration when we were having this issue: https://github.com/ocf/kubernetes/blob/7d887d90430792df1c043f3547be034154f2c56a/apps/cilium.py

I switched to Kubernetes IPAM and properly set the node CIDR and cluster CIDR size in kube-controller-manager, and the issue no longer persists.
