### ISSUE TITLE
daemon: Extend auto-device detection to detect direct routing device

### ISSUE THREAD

**Issue by brb** [cilium/cilium#23444]
Cilium attaches `bpf_host.c` program to either use specified devices (via `--devices` and `--direct-routing-device`), or does the auto-device detection if the former is not specified. The auto-detection is based on two things:

 *  IP routes (https://github.com/cilium/cilium/blob/v1.13.0-rc5/pkg/datapath/linux/devices.go#L106).
 *  K8s Node IP addr (https://github.com/cilium/cilium/blob/v1.13.0-rc5/pkg/datapath/linux/devices.go#L131).

Usually, the second one is used for communication among nodes. In most cases, the first one should detect the second device, but there are some exclusions (see https://github.com/cilium/cilium/blob/v1.13.0-rc5/pkg/datapath/linux/devices.go#L261). Considering that lot's of critical functionality is implemented in `bpf_host.c` (e.g., the host firewall or the WireGuard-based encryption), we want to be extra defensive, thus we enable the direct routing device detection for some of them.

This issue is about extending the first one to detect the "direct routing device", and then dropping the https://github.com/cilium/cilium/blob/v1.13.0-rc5/pkg/option/config.go#L2602.

**Comment by AllMight2099** [comment]
Hi there!
Can I try working on this issue?

**Comment by pchaigno** [comment]
Sure, go ahead! Don't hesitate to reach out on Slack #development if you need any help.

**Comment by brb** [comment]
@AllMight2099 Hi, are you still on the issue?

**Comment by AllMight2099** [comment]
Hi!
Yup. I put up a [message](https://cilium.slack.com/archives/C2B917YHE/p1678397527723669) on #development a few days back with a doubt that I had. Sorry about the delay

**Comment by Jack-R-lantern** [comment]
That part seems to have changed due to the [device controller migration](https://github.com/cilium/cilium/blob/main/pkg/datapath/linux/devices_controller.go), can you check if the issue is still valid?
