### ISSUE TITLE
CFP: Cilium - learn BGP routes and apply them to routing table

### ISSUE THREAD

**Issue by cjabrantes** [cilium/cilium#23464]
Hi all,

I was exploring cilium with BGP in a setup with multiple MAC Domain and after some slack discussion was suggested to open this issue.

From https://docs.cilium.io/en/stable/concepts/networking/routing/#id3

> The Linux kernel on the node must be aware on how to forward packets of pods or other workloads of all nodes running Cilium. This can be achieved in two ways:
> 
> The node itself does not know how to route all pod IPs but a router exists on the network that knows how to reach all other pods. In this scenario, the Linux node is configured to contain a default route to point to such a router. This model is used for cloud provider network integration. See [Google Cloud](https://docs.cilium.io/en/stable/concepts/networking/routing/#gke-datapath), [AWS ENI](https://docs.cilium.io/en/stable/concepts/networking/routing/#aws-eni-datapath), and [Azure IPAM](https://docs.cilium.io/en/stable/concepts/networking/ipam/azure/#ipam-azure) for more details.
> 
> Each individual node is made aware of all pod IPs of all other nodes and routes are inserted into the Linux kernel routing table to represent this. If all nodes share a single L2 network, then this can be taken care of by enabling the option auto-direct-node-routes: true. Otherwise, an additional system component such as a BGP daemon must be run to distribute the routes. See the guide [Using kube-router to run BGP](https://docs.cilium.io/en/stable/gettingstarted/kube-router/#kube-router) on how to achieve this using the kube-router project.

My understanding is that we can have cilium announcing the pod CIDR (exportPodCidr and CiliumBGPPeeringPolicy) to the router, they will learn it and know how to route the traffic from each node of the cluster.
We can have the cluster nodes with a default route to the router or a static route with the POD CIDR range (maybe also the Service CIDR) to the router and that will work.

But if we want to avoid static routing and if default route needs to be in another interface (second option of the documentation transcribed above) we need to have a 3º party component applying the routes that are announced by the router to the routing table, m i correct?

Assuming so, the feature request would be that cilium would be able to apply those routes without the need of 3º party software.

Thanks

**Comment by YutaroHayakawa** [comment]
@log1cb0mb Feel free to file another issue :)

**Comment by log1cb0mb** [comment]
I could but then it will most likely just be a duplicate of this. As titled, BGP control plane's ability to learn BGP routes and update kernel routing table accordingly is what we are after. Now, that can be ANY BGP learned route.

Been checking out documentation and the current implementation, it turns out that such functionality was just not scoped yet.

All we need is turn those arrows here: https://github.com/cilium/cilium/tree/master/pkg/bgpv1 bidirectional. :)

**Comment by log1cb0mb** [comment]
I suppose what we need is cilium's implementation of this: https://github.com/osrg/gobgp/blob/master/docs/sources/zebra.md

**Comment by stelucz** [comment]
+1
Would be great to have it in Cilium. Currently, one needs to run additional component (e.g. bird) to populate RT at nodes.

**Comment by dswaffordcw** [comment]
@cjabrantes, @og1cb0mb, and @stelucz 

I filed a fresh request for this under https://github.com/cilium/cilium/issues/34841 and a formal proposal under https://github.com/cilium/design-cfps/pull/58.  Wish me luck 😁 !

**Comment by log1cb0mb** [comment]
> I filed a fresh request for this under #34841 and a formal proposal under [cilium/design-cfps#58](https://github.com/cilium/design-cfps/pull/58). Wish me luck 😁 !
> 
> For your use-cases are you running Cilium in [Encapsulation](https://docs.cilium.io/en/stable/network/concepts/routing/#encapsulation) or [Native](https://docs.cilium.io/en/stable/network/concepts/routing/#native-routing) routing mode?

Good stuff! This would be amazing to have. 

I am running Native. I now even have another use case where it would be really handy where one doesnt have to rely on upstream network device or even Bird/FRR but instead just cilium just learning routes from other cilium speakers within a cluster.
