### ISSUE TITLE
Bug: Endpoint sync cannot take ownership of CEP that is not local ("10.92.0.4")

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#23487]
This seems to have been introduced by a1c33d8c4e752c78c4a64da03b29de69255c7011 so we should understand why it can cause CI flakes.
```
                  cilium             cilium-mzvpr                        controller sync-to-k8s-ciliumendpoint (2043) is failing since 14s (15x): endpoint sync cannot take ownership of CEP that is not local ("10.92.0.4")
                  cilium             cilium-mzvpr                        controller sync-to-k8s-ciliumendpoint (211) is failing since 7s (18x): endpoint sync cannot take ownership of CEP that is not local ("10.92.0.4")
                  cilium             cilium-mzvpr                        controller sync-to-k8s-ciliumendpoint (237) is failing since 7s (18x): endpoint sync cannot take ownership of CEP that is not local ("10.92.0.4")
                  cilium             cilium-mzvpr                        controller sync-to-k8s-ciliumendpoint (673) is failing since 7s (18x): endpoint sync cannot take ownership of CEP that is not local ("10.92.0.4")
                  cilium             cilium-mzvpr                        controller sync-to-k8s-ciliumendpoint (3933) is failing since 8s (18x): endpoint sync cannot take ownership of CEP that is not local ("10.92.0.4")
                  cilium             cilium-mzvpr                        controller sync-to-k8s-ciliumendpoint (3675) is failing since 8s (18x): endpoint sync cannot take ownership of CEP that is not local ("10.92.0.4")
```
Seen in https://github.com/cilium/cilium/actions/runs/4037128898/jobs/6940212752

**Comment by matholleville** [comment]
I have exactly the same problem with preemptible nodes. Is it related?

**Comment by tommyp1ckles** [comment]
@matholleville 

> I have exactly the same problem with preemptible nodes. Is it related?

Do these nodes experience reboots or IP reassignments?

**Comment by raghvenders** [comment]
@tommyp1ckles @aanm - I have experienced the same issue in my local Single node - Linux(Ubuntu) - k3s version v1.25.6+k3s1 (9176e03c) go version go1.19.5 - Cilium 1.12.6.

I may have encountered this after reboot but my machine or node IP have not changed.

After restart node, pods are restarted, i again see same kind of error. Restarting cilium pod alone is not helping too.
Below is the error i obtained from  > cilium debuginfo

**endpoint sync cannot take ownership of CEP that is not local (\"10.0.0.199\")"**

Actually no pod exists with that ip. I can attach full cilium debug info if secure to be shared..

**Comment by raghvenders** [comment]
@tommyp1ckles @aanm - my bad, IP has got changed too. However my ip has got changed back to 10.0.0.199 and it now complains of the yesterdays ip - 10.0.0.97. 

Note : I will create a static IP however.

One more issue, I encountered around 12 cilium connectivity tests got failed yesterday.
However I got one of them succeeded as the IP got changed back to 10.0.0.199.

One example test - [=] Test [to-entities-world] , though technically curl command worked from that pod, i manually tried yesterday.

I am wondering if they are related.

**Comment by aanm** [comment]
@raghvenders this will likely be fixed in v1.12.8. Please report back if it won't solve it. Thank you

**Comment by fuog** [comment]
> @matholleville
> 
> > I have exactly the same problem with preemptible nodes. Is it related?
> 
> Do these nodes experience reboots or IP reassignments?

=>  i'm on `1.13.0 (v1.13.0-c9723a8d)`

i have the same situation as @matholleville, a preemptible node got evicted. I can say for sure that the IP changed from `10.234.0.47` to `10.234.0.49` . Normally yes, a shutdown/reboot is part of the process. I'm not sure if the node did actually remain the same in kubernetes.
But it is strange to see, that `k get nodes`, ore `k get ciliumnode` give me the new node-ip `10.234.0.49` but  `kubectl -n cni-cilium exec -ti cilium-46wpz -- cilium status` (of that node) is still running in to the error:
```
Controller Status:      156/160 healthy
  Name                                Last success   Last error   Count   Message
  sync-to-k8s-ciliumendpoint (2515)   never          47s ago      54      endpoint sync cannot take ownership of CEP that is not local ("10.234.0.47")   
  sync-to-k8s-ciliumendpoint (318)    never          46s ago      54      endpoint sync cannot take ownership of CEP that is not local ("10.234.0.47")   
```

**Comment by williamclot** [comment]
@tommyp1ckles is it worth reopening an issue for this?

**Comment by raghvenders** [comment]
@williamclot - Are cilium connectivity tests all running?

**Comment by wondertalik** [comment]
v1.13.2 the same. after rebooting servers have this error. before reboot was everythig ok.

**Comment by gberche-orange** [comment]
Also experienced with v1.14.3

**Comment by tommyp1ckles** [comment]
@haribhusal2025 Thanks for the report.

Could you open another issue (and if possible, attaching a cilium sysdump), this particular issue was fixed a while back and there have been a few changes to this code since then so we probably want to treat this as a separate issue. 

I can investigate it further from there.
