### ISSUE TITLE
devVM: set IPv6 podIP for hostNetwork pods

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#23503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When deploying a pod with `hostNetwork: true` on a dual-stack devVM, the pod status doesn't show an IPv6 address. Expectation is that it shows the node's IPv4 **and** IPv6 address.

Per https://kubernetes.io/docs/concepts/services-networking/dual-stack/#configure-ipv4-ipv6-dual-stack, this might just be a missing `--node-ip` parameter for `kubelet` when setting up the devVM. Probably best to also audit if we set up all the other parameters properly.

### Cilium Version

-

### Kernel Version

-

### Kubernetes Version

-

### Sysdump

-

### Relevant log output

```shell
kubectl get pod testds-gdpl6
...
        "hostIP": "192.168.60.12",
        "phase": "Running",
        "podIP": "192.168.60.12",
        "podIPs": [
            {
                "ip": "192.168.60.12"
            }
        ],


with a trivial manifest:

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: testds
spec:
  selector:
    matchLabels:
      zgroup: nodeport-backend-hostns
  template:
    metadata:
      labels:
        zgroup: nodeport-backend-hostns
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: k8s1
      containers:
      - name: web
        image: quay.io/cilium/echoserver:1.10.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jschwinger233** [comment]
> this might just be a missing --node-ip parameter for kubelet when setting up the devVM

This is exactly the root cause of the issue. After fixing the kubelet flag, the Node object and Pod object show the ipv6 in their addresses.

Then I'll audit other flags and open a PR to fix it.

Thank you @julianwiedmann
