### ISSUE TITLE
Investigate `bpf_fib_lookup` + `bpf_redirect` to replace egress gateway IP rules/routes

### ISSUE THREAD

**Issue by jibi** [cilium/cilium#23504]
When the egress IP is assigned to a different interface than the one with the default route, we'll have to install additional IP rules and routes to steer the traffic to the correct interface.

That's because the network stack routes packets before the TC egress hook (i.e. where bpf SNAT happens), which means can't match traffic on the egress IP. We instead need to explicitly match each combination of source (endpoints) IPs and destination CIDRs.

@pchaigno suggested we might want to look into switching to `bpf_fib_lookup` + `bpf_redirect` after the packet has been SNATed with the egress IP as that would allow to match the source/egress IP without the need for all the special IP rules/routes.

**Comment by pchaigno** [comment]
Another option is to perform the FIB lookup in bpf_overlay, before SNAT, and redirect directly to the proper interface. If we do that, we should be careful about path asymmetries (make sure the reply also bypasses the stack).

Yet another option (suggested by Julian) would be to encode the interface number in the BPF map, to avoid needing the FIB lookup.

**Comment by brb** [comment]
I think any `bpf_fib_lookup`-based solution requires an Egress GW IP addr set to a netdev. Is it always the case?

**Comment by jibi** [comment]
I'll start taking a look at this given that I have some cycles

> I think any bpf_fib_lookup-based solution requires an Egress GW IP addr set to a netdev. Is it always the case?

@brb I think it's reasonable to assume the egress IPs are assigned to a netdev. I'm aware of at least one setup where these are assigned to dummy devices instead of real netdev, not clear yet if that could be an issue here

**Comment by jibi** [comment]
> Another option is to perform the FIB lookup in bpf_overlay, before SNAT, and redirect directly to the proper interface

that presumes bpf_host is installed on all interfaces, which might not always be the case :thinking:

> Yet another option (suggested by Julian) would be to encode the interface number in the BPF map, to avoid needing the FIB lookup.

that could work, but requires changing the map layout plus some extra logic in userspace. Worth keeping in mind depending on which side we want to take the tradeoff (more instructions in the datapath vs some extra complexity in userspace)
