### ISSUE TITLE
Cilium - Problems using recorder feature

### ISSUE THREAD

**Issue by cjabrantes** [cilium/cilium#23517]
Hi all,

First of all, not quite sure if its a bug or maybe lack of documentation or my fault (tried first slack without success).
I was searching a way to make a pcap and what cilium had to offer, i found:
`https://docs.cilium.io/en/stable/cmdref/cilium_bpf_recorder/`
But i from what i was able to understand that only applies with we use XDP.

Then i found:
`https://docs.cilium.io/en/stable/cmdref/cilium_recorder_update/`

After i enable '--enable-recorder' i saw:
```

root@node1:~# kci exec -ti cilium-xtmv6  exec --  cilium recorder update --id 1 --filters '0.0.0.0/0 0 10.60.148.254/32 80 TCP' --caplen 0
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
Creating new recorder with id '1'
Added recorder with 1 filter


root@node1:~# kci exec -ti cilium-xtmv6  exec --  cilium recorder list
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
ID   Capture Length   Wildcard Filters
1    full             0.0.0.0/0:0        ->   10.60.148.254/32:80   TCP

Users   Priority      Wildcard Masks
1       56            00000000:0       ->   ffffffff:ffff   ff

```

But i can't find the pcap anywhere, from cilium logs i can see:
`level=info msg="  --hubble-recorder-storage-path='/var/run/cilium/pcaps'" subsys=daemon`

But i dont see it in the host or pod, is there any documentation or how this should work?

Is it possible to do a cluster wide pcap? or is always cilium agent per cilium agent, so node by node?

Thanks,

**Comment by borkmann** [comment]
Hello, the Cilium agent args need to be:   `--enable-recorder=true --enable-hubble=true --enable-hubble-recorder-api=true`, and then you should be able to use Hubble `hubble record "0.0.0.0/0 0 0.0.0.0/0 0 TCP" --time-limit 1s` which produces a pcap.

**Comment by cjabrantes** [comment]
Hi,

I have:
`cilium-agent --config-dir=/tmp/cilium/config-map --enable-recorder --enable-hubble-recorder-api
`
And in cilium configmap:

```
enable-hubble:
----
true
```

When i try o use it via hubble i get:
```
root@node1:/opt/manifest/helm_charts# hubble record "0.0.0.0/0 0 10.60.148.254/32 80 TCP"
Started recording. Press CTRL+C to stop.
rpc error: code = Unimplemented desc = unknown service recorder.Recorder
```
```
hubble --version
hubble v0.11.1
```

Thanks,

**Comment by borkmann** [comment]
Are you running with XDP? See example here: https://github.com/cilium/cilium/pull/18592

**Comment by gandro** [comment]
Also, the Hubble Recorder API is only available when connecting to the local unix domain socket (hubble record --server unix:///var/run/cilium/hubble.sock`) . Notably, it's not available via Hubble Relay.

**Comment by cjabrantes** [comment]
no XDP:

  `XDP Acceleration:       Disabled`

**Comment by cjabrantes** [comment]
> A potential cause could be that the Hubble Recorder API is only available when connecting to the local unix domain socket (`hubble record --server unix:///var/run/cilium/hubble.sock`) . Notably, it's not available via Hubble Relay.

That may be what is missing:

```
root@node1:/opt/manifest/helm_charts# hubble record "0.0.0.0/0 0 10.60.148.254/32 80 TCP" --server unix:///var/run/cilium/hubble.sock
Started recording. Press CTRL+C to stop.
2023-02-01T18:15:35Z Status: 0 packets (0 bytes) written
^CStopping recording...

2023-02-01T18:16:30Z Result: 0 packets (0 bytes) written
2023-02-01T18:16:30Z Output: /var/run/cilium/pcaps/hubble_1675275335_1045676380_k3s-cluster_node1.pcap

root@node1:/opt/manifest/helm_charts# ls -ltr /var/run/cilium/pcaps/hubble_1675275335_1045676380_k3s-cluster_node1.pcap
-rw------- 1 root root 24 Feb  1 18:15 /var/run/cilium/pcaps/hubble_1675275335_1045676380_k3s-cluster_node1.pcap
```

What is the expect result when we run this record via hubble, where the "sniffing" will be running? Only in the local node? or cluster? 
For example in this example "0.0.0.0/0 0 10.60.148.254/32 80 TCP", the expected is to have a pcap from node1 only or from all nodes?

Thanks,

**Comment by gandro** [comment]
The recorder currently only supports capturing on a single node. Cluster-wide capture via Relay has been discussed, but we don't have a good API design yet, since recording creates (potentially expensive) state on each node that needs to be properly managed. In addition, if I recall correctly, there are also limitations what kind of concurrent capture masks are supported, which limits the usability for concurrent captures and also needs a bit more API design to workaround.

**Comment by cjabrantes** [comment]
Hi,
Seems that something is still missing, i m able to see the pcap running, file is created but is empty.
I m running the recorder in the client node. I even tried to set the dst to any IP and any port, but still does not work, i always get empty file.

```
root@node1:~# kn get services
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
nginx-service            ClusterIP   10.60.148.254   <none>        80/TCP         18d
```

```
root@node1:~# kn get pods -o wide
NAME                                  READY   STATUS    RESTARTS        AGE     IP            NODE    NOMINATED NODE   READINESS GATES
client-deployment-bfbb8b74f-ngb5z     1/1     Running   2 (5d17h ago)   5d22h   10.50.3.32    node2   <none>           <none>
client-deployment-bfbb8b74f-nmdgk     1/1     Running   1 (5d18h ago)   5d22h   10.50.0.203   node1   <none>           <none>
client2-deployment-795b6b6995-79x5k   1/1     Running   45 (35m ago)    17d     10.50.0.167   node1   <none>           <none>
client2-deployment-795b6b6995-hsf7m   1/1     Running   2 (5d17h ago)   5d22h   10.50.3.86    node2   <none>           <none>
nginx-deployment-5bc5c8896f-6v6fr     1/1     Running   4 (5d20h ago)   7d20h   10.50.3.6     node2   <none>           <none>
nginx-deployment-5bc5c8896f-dxlzx     1/1     Running   0               4d12h   10.50.1.192   node3   <none>           <none>
```


```
root@node2:~# hubble record "0.0.0.0/0 0 10.50.1.192/32 80 TCP" --server unix:///var/run/cilium/hubble.sock
Started recording. Press CTRL+C to stop.
2023-02-02T23:41:59Z Status: 0 packets (0 bytes) written
```


```
kn exec -ti client-deployment-bfbb8b74f-ngb5z -- curl 10.60.148.254
<html>
<h1>Welcome</h1>
</br>
<h1>Hi! I was able to reach you  </h1>
</html
root@node1:~#
```

```
root@node2:~# ls -ltr /var/run/cilium/pcaps/hubble_1675381475_3614373319_k3s-cluster_node2.pcap
-rw------- 1 root root 24 Feb  2 23:44 /var/run/cilium/pcaps/hubble_1675381475_3614373319_k3s-cluster_node2.pcap
```

Any ideas?

**Comment by NiklasBeierl** [comment]
Can we please reopen this? 

I am experiencing the same issue as described by @cjabrantes. 

I got my agent to run with:
```
      --config-dir=/tmp/cilium/config-map
      --enable-recorder=true
      --enable-hubble=true
      --enable-hubble-recorder-api=true
```
By passing this value to `cilium install -f`:
```
extraArgs:
  - --enable-recorder=true
  - --enable-hubble=true
  - --enable-hubble-recorder-api=true
```

I have access to the hubble UI and can see traffic there, as well as with `hubble observe`, but hubble record always results in an empty pcap.
```
root@cilium-recorder-test-node:~# hubble record  --server unix:///var/run/cilium/hubble.sock "0.0.0.0/0 0 0.0.0.0/0 0 ANY" --packet-limit 100 --time-limit 10s --bytes-limit 10000
Started recording. Press CTRL+C to stop.
2025-04-12T22:48:25Z Status: 0 packets (0 bytes) written
2025-04-12T22:48:35Z Result: 0 packets (0 bytes) written
2025-04-12T22:48:35Z Output: /var/run/cilium/pcaps/hubble_1744498105_3266660343_cilium-recorder-test-node.pcap
root@cilium-recorder-test-node:~# file /var/run/cilium/pcaps/hubble_1744498105_3266660343_cilium-recorder-test-node.pcap
/var/run/cilium/pcaps/hubble_1744498105_3266660343_cilium-recorder-test-node.pcap: pcap capture file, microsecond ts (little-endian) - version 2.4 (Ethernet, capture length 65535)
```

When I have record commands running they are listed by `cilium recorder list`. 

<details><summary>Cilium status</summary>
<pre>
KVStore:                Disabled   
Kubernetes:             Ok         1.32 (v1.32.3+k3s1) [linux/amd64]
Kubernetes APIs:        ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   False   
Host firewall:          Disabled
SRv6:                   Disabled
CNI Chaining:           none
CNI Config file:        successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                 Ok   1.17.2 (v1.17.2-fb3ab54f)
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 6/254 allocated from 10.0.0.0/24, 
Allocated addresses:
  10.0.0.153 (kube-system/hubble-ui-76d4965bb6-r46bw)
  10.0.0.241 (default/whoamiv1-86ccc88fc-w5nbg)
  10.0.0.35 (kube-system/coredns-ff8999cc5-bv2h8 [restored])
  10.0.0.46 (health)
  10.0.0.54 (kube-system/hubble-relay-59cc4d545b-bbkdk)
  10.0.0.62 (router)
IPv4 BIG TCP:           Disabled
IPv6 BIG TCP:           Disabled
BandwidthManager:       Disabled
Routing:                Network: Tunnel [vxlan]   Host: Legacy
Attach Mode:            Legacy TC
Device Mode:            veth
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Clock Source for BPF:   ktime
Controller Status:      43/43 healthy
  Name                                                       Last success   Last error   Count   Message
  cilium-health-ep                                           1m2s ago       never        0       no error   
  ct-map-pressure                                            33s ago        never        0       no error   
  daemon-validate-config                                     20s ago        never        0       no error   
  dns-garbage-collector-job                                  5s ago         never        0       no error   
  endpoint-1574-regeneration-recovery                        never          never        0       no error   
  endpoint-2008-regeneration-recovery                        never          never        0       no error   
  endpoint-2360-regeneration-recovery                        never          never        0       no error   
  endpoint-2862-regeneration-recovery                        never          never        0       no error   
  endpoint-3129-regeneration-recovery                        never          never        0       no error   
  endpoint-3998-regeneration-recovery                        never          never        0       no error   
  endpoint-gc                                                4m5s ago       never        0       no error   
  endpoint-periodic-regeneration                             5s ago         never        0       no error   
  ep-bpf-prog-watchdog                                       3s ago         never        0       no error   
  ipcache-inject-labels                                      4s ago         never        0       no error   
  k8s-heartbeat                                              5s ago         never        0       no error   
  link-cache                                                 5s ago         never        0       no error   
  node-neighbor-link-updater                                 3s ago         never        0       no error   
  proxy-ports-checkpoint                                     44m4s ago      never        0       no error   
  resolve-identity-1574                                      4m2s ago       never        0       no error   
  resolve-identity-2360                                      4m5s ago       never        0       no error   
  resolve-identity-2862                                      1m21s ago      never        0       no error   
  resolve-identity-3998                                      1m8s ago       never        0       no error   
  resolve-labels-/                                           44m3s ago      never        0       no error   
  resolve-labels-default/whoamiv1-86ccc88fc-w5nbg            36m21s ago     never        0       no error   
  resolve-labels-kube-system/coredns-ff8999cc5-bv2h8         44m0s ago      never        0       no error   
  resolve-labels-kube-system/hubble-relay-59cc4d545b-bbkdk   39m5s ago      never        0       no error   
  resolve-labels-kube-system/hubble-ui-76d4965bb6-r46bw      26m8s ago      never        0       no error   
  restoring-ep-identity (2008)                               44m3s ago      never        0       no error   
  restoring-ep-identity (3129)                               44m3s ago      never        0       no error   
  sync-lb-maps-with-k8s-services                             44m3s ago      never        0       no error   
  sync-policymap-1574                                        14m0s ago      never        0       no error   
  sync-policymap-2008                                        14m0s ago      never        0       no error   
  sync-policymap-2360                                        9m5s ago       never        0       no error   
  sync-policymap-2862                                        6m21s ago      never        0       no error   
  sync-policymap-3129                                        14m2s ago      never        0       no error   
  sync-policymap-3998                                        11m8s ago      never        0       no error   
  sync-to-k8s-ciliumendpoint (2008)                          3s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (2360)                          5s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (2862)                          11s ago        never        0       no error   
  sync-to-k8s-ciliumendpoint (3998)                          8s ago         never        0       no error   
  sync-utime                                                 3s ago         never        0       no error   
  waiting-initial-global-identities-ep (2008)                44m3s ago      never        0       no error   
  write-cni-file                                             44m5s ago      never        0       no error   
Proxy Status:            OK, ip 10.0.0.62, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 9.52   Metrics: Disabled
KubeProxyReplacement Details:
  Status:                 False
  Socket LB:              Disabled
  Socket LB Tracing:      Disabled
  Socket LB Coverage:     Full
  Session Affinity:       Disabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Disabled 
  - LoadBalancer:   Disabled 
  - externalIPs:    Disabled 
  - HostPort:       Disabled
  Annotations:
  - service.cilium.io/node
  - service.cilium.io/type
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Auth                          524288
  Non-TCP connection tracking   65536
  TCP connection tracking       131072
  Endpoint policy               65535
  IP cache                      512000
  IPv4 masquerading agent       16384
  IPv6 masquerading agent       16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  Ratelimit metrics             64
  NAT                           131072
  Neighbor table                131072
  Global policy                 16384
  Session affinity              65536
  Sock reverse NAT              65536
  Tunnel                        65536
Encryption:       Disabled        
Cluster health:   1/1 reachable   (2025-04-12T22:56:06Z)
Name              IP              Node   Endpoints
  cilium-recorder-test-node (localhost):
    Host connectivity to 65.21.183.246:
      ICMP to stack:   OK, RTT=223.932µs
      HTTP to agent:   OK, RTT=322.307µs
    Endpoint connectivity to 10.0.0.46:
      ICMP to stack:   OK, RTT=514.017µs
      HTTP to agent:   OK, RTT=316.169µs
Modules Health:
      agent
      ├── controlplane
      │   ├── auth
      │   │   ├── observer-job-auth-gc-identity-events            [OK] OK (7.429µs) [5] (26m, x1)
      │   │   ├── observer-job-auth-request-authentication        [OK] Primed (44m, x1)
      │   │   └── timer-job-auth-gc-cleanup                       [OK] OK (38.055µs) (4m5s, x1)
      │   ├── bgp-control-plane
      │   │   └── job-diffstore-events                            [OK] Running (44m, x2)
      │   ├── ciliumenvoyconfig
      │   │   └── experimental
      │   │       ├── job-reconcile                               [OK] OK, 0 object(s) (44m, x2)
      │   │       └── job-refresh                                 [OK] Next refresh in 30m0s (14m, x2)
      │   ├── daemon
      │   │   ├──                                                 [OK] daemon-validate-config (20s, x44)
      │   │   ├── ep-bpf-prog-watchdog
      │   │   │   └── ep-bpf-prog-watchdog                        [OK] ep-bpf-prog-watchdog (3s, x89)
      │   │   └── job-sync-hostips                                [OK] Synchronized (4s, x45)
      │   ├── dynamic-lifecycle-manager
      │   │   ├── job-reconcile                                   [OK] OK, 0 object(s) (44m, x2)
      │   │   └── job-refresh                                     [OK] Next refresh in 30m0s (14m, x2)
      │   ├── enabled-features
      │   │   └── job-update-config-metric                        [OK] Waiting for agent config (44m, x1)
      │   ├── endpoint-manager
      │   │   ├── cilium-endpoint-1574 (/)
      │   │   │   ├── datapath-regenerate                         [OK] Endpoint regeneration successful (5s, x23)
      │   │   │   └── policymap-sync                              [OK] sync-policymap-1574 (14m, x3)
      │   │   ├── cilium-endpoint-2008 (kube-system/coredns-ff8999cc5-bv2h8)
      │   │   │   ├── cep-k8s-sync                                [OK] sync-to-k8s-ciliumendpoint (2008) (3s, x265)
      │   │   │   ├── datapath-regenerate                         [OK] Endpoint regeneration successful (5s, x24)
      │   │   │   └── policymap-sync                              [OK] sync-policymap-2008 (14m, x3)
      │   │   ├── cilium-endpoint-2360 (kube-system/hubble-relay-59cc4d545b-bbkdk)
      │   │   │   ├── cep-k8s-sync                                [OK] sync-to-k8s-ciliumendpoint (2360) (5s, x236)
      │   │   │   ├── datapath-regenerate                         [OK] Endpoint regeneration successful (5s, x21)
      │   │   │   └── policymap-sync                              [OK] sync-policymap-2360 (9m5s, x3)
      │   │   ├── cilium-endpoint-257 (kube-system/hubble-relay-59cc4d545b-48stx)
      │   │   │   └── datapath-regenerate                         [OK] Endpoint regeneration successful (44m, x1)
      │   │   ├── cilium-endpoint-2862 (default/whoamiv1-86ccc88fc-w5nbg)
      │   │   │   ├── cep-k8s-sync                                [OK] sync-to-k8s-ciliumendpoint (2862) (1s, x220)
      │   │   │   ├── datapath-regenerate                         [OK] Endpoint regeneration successful (5s, x20)
      │   │   │   └── policymap-sync                              [OK] sync-policymap-2862 (6m21s, x3)
      │   │   ├── cilium-endpoint-3129 (/)
      │   │   │   ├── datapath-regenerate                         [OK] Endpoint regeneration successful (5s, x24)
      │   │   │   └── policymap-sync                              [OK] sync-policymap-3129 (14m, x3)
      │   │   ├── cilium-endpoint-3998 (kube-system/hubble-ui-76d4965bb6-r46bw)
      │   │   │   ├── cep-k8s-sync                                [OK] sync-to-k8s-ciliumendpoint (3998) (8s, x158)
      │   │   │   ├── datapath-regenerate                         [OK] Endpoint regeneration successful (5s, x15)
      │   │   │   └── policymap-sync                              [OK] sync-policymap-3998 (11m, x2)
      │   │   └── endpoint-gc                                     [OK] endpoint-gc (4m5s, x9)
      │   ├── envoy-proxy
      │   │   ├── observer-job-k8s-secrets-resource-events-cilium-secrets    [OK] Primed (44m, x1)
      │   │   └── timer-job-version-check                         [OK] OK (4.190076ms) (4m4s, x1)
      │   ├── hubble
      │   │   └── job-hubble                                      [OK] Running (44m, x1)
      │   ├── identity
      │   │   └── timer-job-id-alloc-update-policy-maps           [OK] OK (166.721µs) (26m, x1)
      │   ├── l2-announcer
      │   │   └── job-l2-announcer-lease-gc                       [OK] Running (44m, x1)
      │   ├── node-manager
      │   │   ├── background-sync                                 [OK] Node validation successful (6s, x63)
      │   │   ├── node-checkpoint-writer                          [OK] node checkpoint written (43m, x2)
      │   │   ├── nodes-add                                       [OK] Node adds successful (44m, x1)
      │   │   └── nodes-delete                                    [OK] Node deletions successful (44m, x1)
      │   ├── policy
      │   │   └── observer-job-policy-importer                    [OK] Primed (44m, x1)
      │   ├── service-manager
      │   │   ├── job-health-check-event-watcher                  [OK] Waiting for health check events (44m, x1)
      │   │   └── job-service-reconciler                          [OK] 2 NodePort frontend addresses (44m, x1)
      │   ├── service-resolver
      │   │   └── job-service-reloader-initializer                [OK] Running (44m, x1)
      │   └── stale-endpoint-cleanup
      │       └── job-endpoint-cleanup                            [OK] Running (44m, x1)
      ├── datapath
      │   ├── agent-liveness-updater
      │   │   └── timer-job-agent-liveness-updater                [OK] OK (63.042µs) (0s, x1)
      │   ├── iptables
      │   │   ├── ipset
      │   │   │   ├── job-ipset-init-finalizer                    [OK] Running (44m, x1)
      │   │   │   ├── job-reconcile                               [OK] OK, 0 object(s) (44m, x2)
      │   │   │   └── job-refresh                                 [OK] Next refresh in 30m0s (14m, x2)
      │   │   └── job-iptables-reconciliation-loop                [OK] iptables rules full reconciliation completed (14m, x1)
      │   ├── l2-responder
      │   │   └── job-l2-responder-reconciler                     [OK] Running (44m, x1)
      │   ├── maps
      │   │   └── bwmap
      │   │       └── timer-job-pressure-metric-throttle          [OK] OK (2.471µs) (4s, x1)
      │   ├── mtu
      │   │   ├── job-endpoint-mtu-updater                        [OK] Endpoint MTU updated (44m, x1)
      │   │   └── job-mtu-updater                                 [OK] MTU updated (1500) (44m, x1)
      │   ├── node-address
      │   │   └── job-node-address-update                         [OK] Running (44m, x1)
      │   ├── orchestrator
      │   │   └── job-reinitialize                                [OK] OK (44m, x1)
      │   └── sysctl
      │       ├── job-reconcile                                   [OK] OK, 20 object(s) (4m3s, x60)
      │       └── job-refresh                                     [OK] Next refresh in 9m58.451308653s (4m3s, x1)
      └── infra
          ├── k8s-synced-crdsync
          │   └── job-sync-crds                                   [OK] Running (44m, x1)
          ├── metrics
          │   ├── job-collect                                     [OK] Sampled 24 metrics in 2.705892ms, next collection at 2025-04-12 22:58:04.322653432 +0000 UTC m=+2701.948955658 (4m4s, x1)
          │   └── timer-job-cleanup                               [OK] Primed (44m, x1)
          └── shell
              └── job-listener                                    [OK] Listening on /var/run/cilium/shell.sock (44m, x1)
</pre>
</details>
