### ISSUE TITLE
The handling of local_port in the sockmap's code is strange

### ISSUE THREAD

**Issue by spacewander** [cilium/cilium#23536]
The local_port in both sk_msg_md and bpf_sock_ops are in host byte order:
https://github.com/cilium/cilium/blob/b8786b36e93daf3c779216b6f23327ff19f8cc66/bpf/include/linux/bpf.h#L5784-L5794
https://github.com/cilium/cilium/blob/b8786b36e93daf3c779216b6f23327ff19f8cc66/bpf/include/linux/bpf.h#L5979-L5992

However, they are treated as network byte order in sockmap's code:
https://github.com/cilium/cilium/blob/b8786b36e93daf3c779216b6f23327ff19f8cc66/bpf/sockops/bpf_redir.c#L32
https://github.com/cilium/cilium/blob/b8786b36e93daf3c779216b6f23327ff19f8cc66/bpf/sockops/bpf_sockops.c#L33

The generated keys in the read/write side both use the port processed by bpf_ntohl so this conversion doesn't affect the match in sockmap.

BTW, it seems we can get rid of `>> 16` as they are in host byte order and can be accessed via `(__u16)xxx` cast directly.

**Comment by pchaigno** [comment]
Note this feature will be deprecated in v1.13 and removed in v1.14. It hasn't received enough attention in recent years.

**Comment by spacewander** [comment]
Is there any context about the deprecation? What's the alternative for it?

**Comment by pchaigno** [comment]
We are deprecating because nobody stepped up to maintain it.
