### ISSUE TITLE
CFP: config nat port range to SNAT iptables rules

### ISSUE THREAD

**Issue by w313062006** [cilium/cilium#23539]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

no matter random-fully config or not，pod egress connections might infrequently chose one of the NodePorts that cilium lb is defined, this may cause packet error.

**Describe the feature you'd like**

we can config --to-ports options to iptables rules to avoid port conflict if temporary ports equals nodeport defined.
just like NATPortRange in calico config
https://github.com/projectcalico/calico/blob/master/api/pkg/apis/projectcalico/v3/felixconfig.go#L312

**(Optional) Describe your proposed solution**

1, add a config value like IPTablesNatPortRange = "iptables-port-range"
2, add validate func for this config value
3, add --to-ports option to iptables rules according config value

**Comment by pchaigno** [comment]
I don't think that's expected. From [the KPR documentation](https://docs.cilium.io/en/stable/gettingstarted/#advanced-networking):
> If the NodePort port range overlaps with the ephemeral port range (net.ipv4.ip_local_port_range), Cilium will append the NodePort range to the reserved ports (net.ipv4.ip_local_reserved_ports). This is needed to prevent a NodePort service from hijacking traffic of a host local application which source port matches the service port. To disable the modification of the reserved ports, set nodePort.autoProtectPortRanges to false.
