### ISSUE TITLE
hubble: deprecation cleanup

### ISSUE THREAD

**Issue by kaworu** [cilium/cilium#23541]
- [x] [Helm's `.Values.hubble.metrics.tls.ca` section](https://github.com/cilium/cilium/blob/4095784e172094e21fcff8cfe6cf69b9a7938c63/install/kubernetes/cilium/values.yaml#L972-L981) was deprecated by https://github.com/cilium/cilium/pull/18607 and planned to be removed in v1.13
- [x] [Helm's `.Values.hubble.peerService.enabled` flag](https://github.com/cilium/cilium/blob/4095784e172094e21fcff8cfe6cf69b9a7938c63/install/kubernetes/cilium/values.yaml#L916-L920) was deprecated by https://github.com/cilium/cilium/pull/23407 and planned to be removed in v1.14, related code (i.e. local UNIX domain socket for the Peer Service in Hubble Relay) should be removed on the way. https://github.com/cilium/cilium/pull/24214

**Comment by mohit-marathe** [comment]
Hello @kaworu , can you please assign this issue to me?

**Comment by rolinh** [comment]
Thanks for volunteering @mohit-marathe :pray:

**Comment by azepecki** [comment]
Can I ask that this is assigned to me as well if these changes still need to be made? Thank you!

**Comment by mohit-marathe** [comment]
@rolinh yes I want to work on it. Do you suggest I make a separate PR for the remaining changes?

**Comment by mohit-marathe** [comment]
Since @azepecki has already made a PR for this, I'm unassigning myself. However I'll happy to help him by reviewing his PR. :v:

**Comment by dipankardas011** [comment]
@rolinh @mohit-marathe is this issue fixed by #24214?

**Comment by rolinh** [comment]
Indeed, it looks like it's been done.
