### ISSUE TITLE
Add support for CRI grpc interface

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2354]
The workloads layer is still using the docker client to retrieve the list of containers and watch for events.

- [ ] rename the misnamed containerd plugin to docker
- [ ] add support for the CRI grpc interface. There are several options here.

**Comment by nickray** [comment]
I am very interested in support for the CRI. For one, I was following along Kelsey Hightower's "the hard way" tutorial, which has switched to cri-containerd. But also I would like to test Clear Containers and drive them via CRI-O.

**Comment by joestringer** [comment]
As far as I can tell, labels appear to be fully mutable in CRI. We should make sure we don't end up being able to configure reserved labels on endpoints via CRI (See #2595)

**Comment by voidengineer** [comment]
This is the most important missing feature for me, because at my company we are making the switch to cri-containerd and the k8s-nodes will not even have docker installed any longer.

**Comment by tgraf** [comment]
> This is the most important missing feature for me, because at my company we are making the switch to cri-containerd and the k8s-nodes will not even have docker installed any longer.

Thanks, this is great feedback. We are bumping this up.

**Comment by voidengineer** [comment]
Just to be sure: I think the new title regarding `CRI-O` is not corrent. We are going to use `containerd` with `CRI`.
The corresponding Kubernetes (kubelet) flags are `--container-runtime=remote --container-runtime-endpoint=<path-to-cri-containerd-socket>`.

`CRI-O` is another implementation of `CRI`.

**Comment by tgraf** [comment]
> Just to be sure: I think the new title regarding CRI-O is not corrent. We are going to use containerd with CRI.

You are right, we have been tracking two different tasks with this issue. The addition of CRI interface support as well as testing with CRI-O which has been requested as well.

**Comment by voidengineer** [comment]
The implementation of CRI for containerd has been moved into the containerd-project as a plugin:
https://github.com/containerd/cri/releases/tag/v1.0.0-rc.0

This implements CRI v1alpha2 (Kubernetes 1.10). Is this important for you?

**Comment by mskarbek** [comment]
Is this will be available in 1.1 or we we can expect delay? According to #3585 feature freeze is in two days.

**Comment by tgraf** [comment]
> Is this will be available in 1.1 or we we can expect delay? According to #3585 feature freeze is in two days.

It looks like CRI/containerd support will make 1.1.

**Comment by mskarbek** [comment]
You have explicitly mentioned containerd, is there any reason? Will this implementation work for [cri-o](http://cri-o.io/)? We got rid of docker-related parts.

**Comment by aanm** [comment]
@ChiefAlexander @voidengineer @lorenz @AshleyByeUK @mskarbek @runiq @robodendron @sidcarter @martinbaillie @aaglenn @maximusfloydus
 
containerD and CRI-O support are merged and available in `v1.1.0-rc2` feel free to try it!

Thank you for your feedback over this feature!
