### ISSUE TITLE
Improve Hubble Relay Kubernetes Readiness/Liveness check

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#23542]
At the moment, Hubble Relay's Kubernetes readiness and liveness check are simply checking if the TCP port is open:

https://github.com/cilium/cilium/blob/f62b617059407f437757458fc4318064076c32e7/install/kubernetes/cilium/templates/hubble-relay/deployment.yaml#L66-L71

This kind of check is not particularly useful in determining if Hubble is ready. Instead, the user is required to manually inspect Relay's logs for common errors, such as: No access to peer service, mTLS authentication failures, pod2host connectivity broken and no connection to Hubble Observers.

We should introduce a more meaningful health-check which performs some basic checks, for example:

  - Have we received cluster information from the peer service?
  - Are we connected to a Hubble Observer on at least one node?
  - (Bonus): Do the connected Hubble Observers contain any flows in their ring buffer?

@kaworu mentioned that this health check could be exposed via the gRPC endpoint, which an upcoming Kubernetes version seems to support. This means we do not have to create a custom HTTP server just for this. @kaworu feel free to provide more details.

For older versions of Kubernetes, we could provide a `hubble-relay healthz` sub-command and use a [`command`](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command) based readiness/liveness probe.

**Comment by kaworu** [comment]
Hubble Relay [already register a gRPC health server](https://github.com/cilium/cilium/blob/bc2af2a48d94f628dc59395f8c9afb8705ebb086/pkg/hubble/relay/server/server.go#L132), but it doesn't provide any useful signal as we [constantly set the health to `HealthCheckResponse_SERVING`](https://github.com/cilium/cilium/blob/bc2af2a48d94f628dc59395f8c9afb8705ebb086/pkg/hubble/relay/server/server.go#L180). To the best of my knowledge there are no consumer of this endpoint (it is not used by k8s probe as pointed out by the issue description).

My proposition is that once the checks are implemented, we should update the gRPC health state accordingly (e.g. set the serving status to `HealthCheckResponse_NOT_SERVING` when the peer service is unavailable). Then, the k8s probes could make use of the gRPC health endpoint.

[Kubernetes v1.24 introduced built-in gRPC probe (in beta)](https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/). There are two relevant limitations with this probe:
1. it's only k8s v1.24+ and we aim to support older versions, so we would need a fallback solution
2. No TLS support (see [the documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe)) but Hubble Relay can be configured to serve over TLS

Thus, I would consider using [`grpc_health_probe(1)`](https://github.com/grpc-ecosystem/grpc-health-probe/) instead for the time being (original article [here](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/)), which is the project the k8s built-in probe aim to supersede. When/if the built-in probe support TLS and is available in the oldest k8s version we aim to support, then we could migrate over.

**Comment by cdenneen** [comment]
Seems like this might benefit from an `intialDelaySeconds` to help with the `Warning events`?

```
Failed to update endpoint kube-system/hubble-peer: Operation cannot be fulfilled on endpoints "hubble-peer": the object has been modified; please apply your changes to the latest version and try again

Error updating Endpoint Slices for Service kube-system/hubble-peer: skipping Pod cilium-m6wv7 for Service kube-system/hubble-peer: Node ip-10-208-63-176.ec2.internal Not Found
```

These are transient but I believe can be avoided with improving these probes.
