### ISSUE TITLE
Remove `TestDummyProg()`

### ISSUE THREAD

**Issue by rgo3** [cilium/cilium#23558]
As a follow up to #23557 we shouldremove `TestDummyProg()`. Like @ti-mo mentioned in https://github.com/cilium/cilium/issues/20739#issuecomment-1331855419_ feature probing prog/attachtype combinations looses value if the new implementation uses `bpf_link`.

Instead of probing for a succeeding `PROG_ATTACH` we should just ask for forgiveness with the new logic in `pkg/socketlb` and bail out or flip flags in cases of failure.

**Comment by rgo3** [comment]
cc @ti-mo

**Comment by ti-mo** [comment]
Proposal for this in https://github.com/cilium/cilium/pull/25355.
