### ISSUE TITLE
Remove sockops-enable and friends

### ISSUE THREAD

**Issue by brb** [cilium/cilium#23556]
We have deprecated `--sockops-enable` in v1.13, and we can remove the feature in v1.14 (it's not being maintained). `pkg/sockops`, `bpf/sockops`, `pkg/map/sockmap`, etc can be removed, and some of the issues https://github.com/cilium/cilium/issues?q=is%3Aissue+is%3Aopen+sockops can be closed.

**Comment by mohit-marathe** [comment]
Hello @brb, can you assign this to me?

**Comment by brb** [comment]
@mohit-marathe Sure!

**Comment by qmonnet** [comment]
Reopening the issue, just so we don't forget to clean up (other) sockops-related issues. :broom:

**Comment by qmonnet** [comment]
We can also probably remove the label `area/sockops` after that.

**Comment by brb** [comment]
@qmonnet Can we close this issue and related ones?

**Comment by brb** [comment]
Resolved by @mohit-marathe. Thanks! Closing the issue.
