### ISSUE TITLE
cilium loadbalance endpoint on some machine may not workong

### ISSUE THREAD

**Issue by konghui** [cilium/cilium#23586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. When I created a Loadbalance the node in  cluster. All the node through command `cilium service list` can got the right backend info :
```
644    10.254.192.4:9200      LoadBalancer    1 => 10.254.4.95:9200      
                                              2 => 10.254.0.181:9200     
                                              3 => 10.254.1.224:9200
```
the route of LoadBalancer contains many next hops. many of them were working correct.  But there were two node's behave were abnormal.
10.8.192.19:
`curl: (7) Failed connect to 10.254.192.4:9200; Connection timed out`
10.8.192.23:
`curl: (7) Failed connect to 10.254.192.4:9200; No route to host`

output of `cilium bpf list|grep 10.254.192.4:9200 -A 4`:
```
10.254.192.4:9200      10.254.1.224:9200 (840)                           
                       0.0.0.0:0 (840) [LoadBalancer]                    
                       10.254.4.95:9200 (840)                            
                       10.254.0.181:9200 (840)  
```

use `cilium monitor|grep 10.8.192.57` didn't find any request, but on others node can find the requests.  

2. cilium-config were:
```
  auto-direct-node-routes: "true"
  bpf-lb-map-max: "65536"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-name: sg-zl-1
  custom-cni-conf: "false"
  debug: "false"
  devices: lan0
  direct-routing-device: lan0
  disable-cnp-status-updates: "true"
  egress-masquerade-interfaces: wan0
  enable-auto-protect-node-port-range: "true"
  enable-bandwidth-manager: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-reachable-services: "true"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "false"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "true"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  endpoint-status: policy
  etcd-config: |-
    ---
    endpoints:
      - https://x.x.x.x:2379
      - https://x.x.x.x:2379
      - https://x.x.x.x:2379
    trusted-ca-file: '/var/lib/etcd-secrets/etcd-client-ca.crt'
    key-file: '/var/lib/etcd-secrets/etcd-client.key'
    cert-file: '/var/lib/etcd-secrets/etcd-client.crt'
  hubble-disable-tls: "true"
  hubble-listen-address: :4244
  hubble-metrics: dns drop tcp flow port-distribution icmp http
  hubble-metrics-server: :9091
  hubble-socket-path: /var/run/cilium/hubble.sock
  identity-allocation-mode: kvstore
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  ipam: kubernetes
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  kvstore: etcd
  kvstore-opt: '{"etcd.config": "/var/lib/etcd-config/etcd.config"}'
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  native-routing-cidr: 10.0.0.0/8
  node-port-bind-protection: "true"
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :6942
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9092
  sidecar-istio-proxy-image: cilium/istio_proxy
  tunnel: disabled
  wait-bpf-mount: "true"
```
3. create a new  new loadbalancer resource

4. **when I delete cilium-agent on the target two nodes and let it recreated new one. The problem was fixed**

### Cilium Version

Client: 1.10.2 319d2ac 2021-07-02T03:00:06+02:00 go version go1.16.5 linux/amd64
Daemon: 1.10.2 319d2ac 2021-07-02T03:00:06+02:00 go version go1.16.5 linux/amd64

### Kernel Version

Linux xxxxx 5.9.11-1.el7.elrepo.x86_64 #1 SMP Tue Nov 24 09:45:34 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.19.4

### Sysdump

Error: unknown command "sysdump" for "cilium"
Run 'cilium --help' for usage.
unknown command "sysdump" for "cilium"

### Anything else?

seems create cilium agent can fix this problem

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
I'm not sure I understand, so let me try to reformulate:
You've created a Kubernetes service of type LoadBalancer with three backends. Requests from all nodes work except for nodes 10.8.192.19 and 10.8.192.23 where the requests fail with different error messages. Is that correct?

> use cilium monitor|grep 10.8.192.57 didn't find any request, but on others node can find the requests.

What is 10.8.192.57 here?

Did you try tracing the connection that times out to see where packets are dropped? Note you may have more success if you first disable monitor aggregation (`monitor-aggregation: none`) in Cilium.

**Comment by konghui** [comment]
> I'm not sure I understand, so let me try to reformulate: You've created a Kubernetes service of type LoadBalancer with three backends. Requests from all nodes work except for nodes 10.8.192.19 and 10.8.192.23 where the requests fail with different error messages. Is that correct?
> 
> > use cilium monitor|grep 10.8.192.57 didn't find any request, but on others node can find the requests.
> 
> What is 10.8.192.57 here?
> 
> Did you try tracing the connection that times out to see where packets are dropped? Note you may have more success if you first disable monitor aggregation (`monitor-aggregation: none`) in Cilium.

10.8.192.57 was the source of the request server's address. I could find the request on the working node. 
The package was not dropped, because I didn't find the drop message on the cilium monitor output.
