### ISSUE TITLE
Complete drop notification to correct destination ID for reserved identities

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#2368]
Similar to GH issue #2114, we need to make the data path understand the reserved identities correctly and fill in the correct destination security identity.

**Comment by tgraf** [comment]
I've looked into this. The cost of this is non-trivial as we have to move several map lookups to earlier in the processing path. This imposes datapath cost for work that is only required if the packet is actually dropped. All of the information is retrieved based on addressing information that is made available to the agent in the drop notification. I suggest to do this work in the monitor.

**Comment by tgraf** [comment]
This has not come up recently. Closing.
