### ISSUE TITLE
BPF : Reply packets seem to always come from Host, even if we might be sending requests to cluster/world

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#2369]
While fixing GH issue #2114, we needed to make the data path understand the reserved identities correctly and fill in the correct destination security identity.

It was observed that the corresponding reply to a request always comes from HOST and never from world / cluster. We need to see if we can make this code more intelligent 

<- endpoint 29381, identity 259: 10.11.193.100:35174 -> 172.217.5.78:80 tcp ACK, FIN
-> forward (Established connection), at To stack, to endpoint 0, identity 259->2: 10.11.193.100:35174 -> 172.217.5.78:80 tcp ACK, FIN
<- netdev 2: 172.217.5.78:80 -> 10.11.193.100:35174 tcp ACK
-> forward (Reply connection), at To endpoint, to endpoint 29381, identity 1->259: 172.217.5.78:80 -> 10.11.193.100:35174 tcp ACK
<- netdev 2: 172.217.5.78:80 -> 10.11.193.100:35174 tcp ACK, FIN

**Comment by tgraf** [comment]
This is due to SNAT on the outgoing connection by kube-proxy, the reply packet will go to the IP of the node itself, gets reverse NATed and then sent to the Cilium endpoint.
