### ISSUE TITLE
Deadlock in Cilium Agent

### ISSUE THREAD

**Issue by mantoine96** [cilium/cilium#23707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After a while running (typically for us, several days), a Cilium agent will start to become unresponsive, failing its liveness checks which causes it to be restarted by Kubernetes. Since we leverage FQDN rules a lot, this ends up causing network disruption on the given host.
  

### Cilium Version

1.12.5 820a3086ad 2022-12-22T16:16:56+00:00 go version go1.18.9 linux/amd64

This is essentially the released 1.12.5 + this PR backported: https://github.com/cilium/cilium/pull/22252

### Kernel Version

5.4.228-131.415.amzn2.x86_64 

### Kubernetes Version

v1.23.14-eks-ffeb93d

### Anything else?

The entire threaddump can be found here: [cilium-wh7xn.log](https://github.com/cilium/cilium/files/10721535/cilium-wh7xn.log)

This was captured by setting a preStop lifecycle hook to run `kill -s ABRT 1`. 

This issue started occurring with v1.12.2 for us.

cc @joaoubaldo @carloscastrojumo 

From our dashboards, this is what we can observe:
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/1666462/218443636-3b09ff18-4830-42e2-989d-b09378df7d65.png">
The restart of the agent/agent going unhealthy happens shortly after a large amount of endpoints not ready.

We have other metrics and logs if needed so let us know if you need more information for troubleshooting.

Would you recommend running an image compiled with [the deadlock detection](https://docs.cilium.io/en/stable/contributing/development/debugging/#deadlock-detection) flag in production? We unfortunately cannot replicate this issue in a testing cluster.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
> Would you recommend running an image compiled with [the deadlock detection](https://docs.cilium.io/en/stable/contributing/development/debugging/#deadlock-detection) flag in production? We unfortunately cannot replicate this issue in a testing cluster.

I checked back with my colleagues and unfortunately, we do not recommend running `lockdebug` in production. Fetching a threadump as you did is probably the better approach.

**Comment by gandro** [comment]
I've opened a PR to fix the `fatal error: concurrent map read and map write`  issue here: https://github.com/cilium/cilium/pull/23713

It's still possible however that you also observed a deadlock. Thus, if you have additional threadumps from other runs that would be helpful to confirm that there are indeed no other unknown problems.

**Comment by gandro** [comment]
> Could the error you pointed out in #23713 have resulted in a deadlock / agent becoming unresponsive / healthcheck failing?

Yes, at least in theory. The panic stack dump you provided above has it's root in `created by github.com/cilium/cilium/pkg/status.(*Collector).runProbe`. That probe is used to determine the status of each cilium subsystem (such as IPAM in case of the failing probe).

If the probe never return a status (such as in case it panics), `probeReturned` is never triggered and thus the probe is marked as stale after 60 seconds:
https://github.com/cilium/cilium/blob/314ca7baeff4f568ffc0bad95124e40665b1f88c/pkg/status/status.go#L221

If there are any stale probes, then Cilium as a whole will not be marked as "ready"/"live":

https://github.com/cilium/cilium/blob/428c6d2076f4074d51560248fc0af72366c0fed6/daemon/cmd/status.go#L652-L657

The only issue with that theory is that we should see a the following warning emitted 15 seconds after the panic (which I do not see in the logs):
https://github.com/cilium/cilium/blob/314ca7baeff4f568ffc0bad95124e40665b1f88c/pkg/status/status.go#L198

**Comment by christarazi** [comment]
Are you still experiencing this in v1.12.x?

**Comment by mantoine96** [comment]
Hello @christarazi 

We did have one more crash occurrence with the patches you mentioned (we had backported them to our image). 

@gandro Great I'll test it out then! 

To be fair this is really rare, we last encountered the issue 20 days ago. Hopefully this issue is the right one! :) 

Thanks again!

**Comment by lukaselmer** [comment]
> Hopefully this issue is the right one! :)

Hi @mantoine96,

It seems we are facing the same issue (however, we only observe the issue in one AWS Zurich region, and not in the Frankfurt region).

Did you upgrade to the latest version of Cilium? Did it resolve the issue?

Thx!

**Comment by gandro** [comment]
Note that we fixed another related issue https://github.com/cilium/cilium/pull/26242 which however is still in the process of getting backported to v1.13

**Comment by mantoine96** [comment]
Hello @gandro 

Just confirming that in the last ~74 days, we have not had a single occurrence of the crash using our custom image based on v1.12.9.

#26242 also looks similar. We are in the process of upgrading to v1.13 so I will look out for it! 

@lukaselmer I would therefore recommend you try out 1.12.9 if you're experiencing similar issues. Like I mentioned, we haven't had an issue in > 74 days, which is pretty good going.
