### ISSUE TITLE
kops integration & guide

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2372]

**Comment by nebril** [comment]
Was blocked by https://github.com/kubernetes/kops/issues/2901 , but it seems like kops has 4.12 kernel now. Investigating.

**Comment by nebril** [comment]
https://github.com/kubernetes/kops/pull/4224 works, but until it's merged you need to build it yourself and push kops binaries to your s3 bucket. To do so:

- clone my kops fork: https://github.com/nebril/kops
- checkout cilium-support branch
- follow https://github.com/kubernetes/kops/blob/master/docs/development/adding_a_feature.md#testing to build and push kops binaries to your s3 bucket
- follow https://github.com/kubernetes/kops/blob/master/docs/aws.md to create a cluster, but use kops binary built by you. it should be in `.build/upload/kops/dev/linux/amd64/kops`

**Comment by tgraf** [comment]
This has been completed
