### ISSUE TITLE
CI: Premature GitHub status report in case of matrix jobs

### ISSUE THREAD

**Issue by mhofstetter** [cilium/cilium#23729]
Some GitHub Actions jobs which use the matrix feature are reporting their status prematurely.

The first matrix job which finishes successfully is going to report "success" to the PR status - which might be too early due to potentially failing parallel jobs within the same matrix. (failure will be reported correctly afterwards, but in the meantime the status shouldn't be succeeded)

status reporting should "never" be reported within the matrix itself and moved to the end into a separate job - whether pending at the beginning or the actual result at the end (but especially success)

examples:
* https://github.com/cilium/cilium/blob/master/.github/workflows/tests-datapath-verifier.yaml
* https://github.com/cilium/cilium/blob/master/.github/workflows/conformance-datapath.yaml

**Comment by spacewander** [comment]
Assign to me?

**Comment by pchaigno** [comment]
@spacewander Feel free to send a pull request for it. And don't hesitate to ask for help in Slack #development if needed.
