### ISSUE TITLE
Datapath BPF Complexity (ci-verifier) Expected — Waiting for status to be reported 

### ISSUE THREAD

**Issue by kaworu** [cilium/cilium#23727]
Seen in multiple PRs so opening a [ci/flake](https://github.com/cilium/cilium/pull/23709#issuecomment-1429307305) issue.

* https://github.com/cilium/cilium/pull/23709#issuecomment-1429307305
* https://github.com/cilium/cilium/pull/23636#issuecomment-1425537823

**Comment by pchaigno** [comment]
I believe that's expected and it happens because that CI job only runs if there are BPF changes. `/ci-verifier` forces its execution: https://github.com/cilium/cilium/blob/bff4ef92ae0bbba945b9cf8fe8f5399fd8523a21/.github/workflows/tests-datapath-verifier.yaml#L115-L116
