### ISSUE TITLE
Modularization: NetConf

### ISSUE THREAD

**Issue by joamaki** [cilium/cilium#23730]
The /etc/cni/net.d directory contains a "netconf" file that registers a CNI to Kubernetes.
Cilium agent writes this file after it has finished starting up and is ready to process CNI requests
(e.g. the API server is up and initialization is complete). This is implemented in daemon/cmd/cni.go
with startCNIConfWriter. The file is also read by the cilium-cni program that kubelet invokes to set up
networking for a new pod. 

As we're refactoring components into cells the end of the old daemon initialization is soon going to be the wrong
place from which to write the netconf file. In order to prepare for this, pull the netconf reading and writing into its
own cell along with relevant configuration options from option.Config. We'll likely want to expose a separate public
function for reading for cilium-cni.

The netconf cell should have a start hook that reads the netconf (if "ReadCNIConfiguration" is non-empty), and
a separate start hook that is executed as the last hook to write the netconf file (cell.Invoke to register the hook and making sure netconf cell is the last agent cell). Alternatively we could have "PostStart" hooks in Hive, but that's perhaps a bit too heavyweight for this one use case.

runDaemon from which we're currently calling startCNIConfWriter is running in a background goroutine forked
from OnStart hook. This should be changed to not fork from OnStart so that we also wait for runDaemon initialization to finish. Only change needed should be to instead fork the `srv.Serve()` call instead.

Sketch of the cell:
```
package netconf

type Config struct {
  ReadCNIConfiguration string
  ...
}
func (def Config) Flags(flags *pflag.FlagSet) {
  flags.String("read-cni-configuration", def.ReadCNIConfiguration, "If set reads the CNI configuration file ...")
}
var defaultConfig = Config{...}

var Cell = cell.Module(
  "netconf",
  "Reading and writing of CNI netconf files",
  cell.Config(defaultConfig),
  cell.Provide(New),
  cell.Invoke(registerWriter),
)

func New(lc hive.Lifecycle, cfg Config) *NetConf {
  n := &NetConf{}
  // Reading must happen only when we start (otherwise can't inspect hive)
  // We might want to expose an interface for accessing `*NetConf` instead, or
  // Promise[*NetConf]...
  lc.Append(hive.Hook{
    OnStart: readNetConf(n),
  })
}
func registerWriter(lc hive.Lifecycle, cfg Config) {
  lc.Append(hive.Hook{
    OnStart: startNetConfWriter,
    OnStop: removeCNIConfFile,
  })
}
```

Related: #23425

**Comment by joamaki** [comment]
@squeed you worked recently on the writing of the netconf file. Would you be interested in taking a look at this?

**Comment by squeed** [comment]
Definitely.
