### ISSUE TITLE
Remove PolicyImportErrorsTotal agent metric in Cilium 1.15

### ISSUE THREAD

**Issue by dlapcevic** [cilium/cilium#23747]
It is deprecated in Cilium 1.14, and should be removed in Cilium 1.15.
Context: https://github.com/cilium/cilium/pull/23349

/kind cleanup
/area metrics

**Comment by swastik959** [comment]
@dlapcevic hi I have created a pr please review it

**Comment by lavishpal** [comment]
Is this issue still open?
