### ISSUE TITLE
Migrate TLS policy tests from Ginkgo to cilium-cli connectivity test

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#23784]
Migrate the TLS policy tests currently in https://github.com/cilium/cilium/blob/master/test/k8s/net_policies.go to Cilium CLI connectivity test framework (https://github.com/cilium/cilium-cli/tree/master/connectivity).

- [x] Implement `WithSecrets()` that can be used before `WithPolicy()` to create the k8s secrets needed for the policy to be used https://github.com/cilium/cilium-cli/pull/1406
- [x] Create the needed certs on the fly so that they are never expired when the test is run (reuse code we already have for creating TLS secrets) https://github.com/cilium/cilium-cli/pull/1406
- [x] Re-use one of the existing test scenarios, if possible https://github.com/cilium/cilium-cli/pull/1406
- [x] Figure how the internal CA is configured on the client pods. It would be acceptable to have the required pods always run with the CA injected, so that those pods would not need to be restarted for specific tests.
- [x] replicate the test coverage in the Ginkgo test and when done, remove the test from Ginkgo https://github.com/cilium/cilium/pull/24414
- [ ] Use an internal HTTPS service instead an external one for the tests so that we avoid flaking due to any external issues
- [ ] Add new coverage for SNI enforcement
- [ ] Ensure that at least one of the tests fail if the egress proxy fails to forward the incoming SNI to the final destination
- [ ] Close open issues as they are fixed (see below)

Fixes: #22404, #22849

**Comment by meyskens** [comment]
I picked up the issue and was able to migrate the existing test over to cilium-cli (https://github.com/cilium/cilium-cli/pull/1406). 
Doing this I ported over a test to an external service only (same endpoint settings as tests already depended on to lower flakes) using certificate automation. 

However on the points for internal testing I did not continue on as they get quite far from the original re-use of what was already there intent.
The cilium connectivity tests use an "echo" server which is based on https://github.com/cilium/json-mock which runs a node.js based json-server. That tool itself has no built in TLS support and adding it would require a suite of dependencies (I would argue to replace it but do not know why it was chosen in the first place). Meaning testing pod-to-pod TLS would require a whole new pod being added or the echo server to be reworked (which also includes handling its certificates). This is probably work that needs to be scoped and discussed before adding it in a migrate-a-testcase PR.

**Comment by meyskens** [comment]
When https://github.com/cilium/cilium/pull/24414 is merged we moved the same test coverage over to cilium-cli.
@jrajahalme do we want to keep the other work items in this ticket or move them out to an improvement ticket? Among with a small discussion on how to improve the echo server for testing?

**Comment by jrajahalme** [comment]
@meyskens IMO it is best to open a new ticket for the remaining improvement steps and close this issue once the TLS tests have been deleted from the Ginkgo test.
