### ISSUE TITLE
Cilium health probes are sent in plain-text when IPSec is enabled

### ISSUE THREAD

**Issue by lukenjmcd** [cilium/cilium#23793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've setup cilium 1.13.0 with IPSec security on a Kind cluster, following the [Isovalent demo](https://isovalent.com/resources/video-cilium-transparent-encryption-with-ipsec-and-wireguard/).  The cluster has 2 worker nodes and one control plane nod.

I used Wireshark to capture the traffic on the Kind bridge network.  Most of the traffic appears to be properly tunnelled, but the HTTP health probes exchanges between cilium agents are in plain-text.

Here are the cilium pods, their IP addresses and the nodes on which they are running:

![image](https://user-images.githubusercontent.com/14074619/219152219-1945032c-b0e2-47b2-94d2-4a17eab4b6b3.png)

And here is wireshark output showing plain-text HTTP request between these IP addresses:

![image](https://user-images.githubusercontent.com/14074619/219152729-a78ca2b2-c7a6-491c-86f2-112c0b5b011b.png)

And another wireshark screenshot showing the plain-text HTTP requests interleaved with the IPSec UDP traffic:

![image](https://user-images.githubusercontent.com/14074619/219153349-96b4a6eb-5c72-4b1a-8a61-e03dc6ad816e.png)

### Cilium Version

v1.13.0

### Kernel Version

Linux cilium-ipsec-worker 5.15.0-1027-oracle #33-Ubuntu SMP Fri Jan 6 16:30:21 UTC 2023 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230215-153737.zip](https://github.com/cilium/cilium/files/10747367/cilium-sysdump-20230215-153737.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
That looks expected. Cilium agent pods are running in the host-network namespace. With IPsec, only traffic between Cilium-managed pods (i.e., pods running in their own network namespaces) is encrypted.

**Comment by lukenjmcd** [comment]
I am trying to ensure all traffic between kubernetes nodes is encrypted.  Is there a way to encrypt the cilium agent heartbeats?  At this point it appears to be the only plain-text traffic in my cluster.

**Comment by pchaigno** [comment]
No, with IPsec only pod-to-pod traffic is encrypted. In v1.14, WireGuard will support node encryption in addition to the usual pod-to-pod encryption.
