### ISSUE TITLE
docs: link to security audits from docs

### ISSUE THREAD

**Issue by lizrice** [cilium/cilium#23791]
The 2022 Security Audits for Cilium were recently published [here](https://github.com/cilium/cilium.io/blob/main/Security-Reports/CiliumSecurityAudit2022.pdf) and [here](https://github.com/cilium/cilium.io/blob/main/Security-Reports/CiliumFuzzingAudit2022.pdf). We should add links to them from the Cilium documentation. 

I'm not sure where the best location for this would be, but there might be an obviously good place once https://github.com/cilium/cilium/pull/23599 is finalized (wdyt @zacharysarah?)

**Comment by zacharysarah** [comment]
I think that's easily done, probably on what will soon be renamed as `security/index`.

**Comment by adityakode** [comment]
Hi , I would be intrested in contributing, can you assign me?

**Comment by zacharysarah** [comment]
@adityakode 👋🏻 Please feel free to open a pull request that references this issue.

**Comment by zacharysarah** [comment]
Just now coming back to this. It looks like the reports aren't searchable or pathable on https://cilium.io, so I'm going to copy them to cilium/cilium.
