### ISSUE TITLE
failed to install iptables rules

### ISSUE THREAD

**Issue by Antiarchitect** [cilium/cilium#23796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Just rebooted my control-plane nodes and one of them cannot came up.
Cilium Agent has fatal in it's log:
```
cilium-agent level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: failed to install iptables rules: unable to run 'iptables -t mangle -D OLD_CILIUM_PRE_mangle -m socket [unsupported revision] -m comment --comment cilium: any->pod redirect proxied traffic to host proxy -j MARK --set-xmark 0x200/0xffffffff' iptables command: exit status 2 stderr=\"Bad argument `[unsupported'\\nTry `iptables -h' or 'iptables --help' for more information.\\n\"" subsys=daemon
```

I think `[unsupported revision]` do this. Just looked at the code and I cannot imagine how this could ever happen (must be in `inboundProxyRedirectRule` function in iptables.go)

AHA! Found this: https://github.com/kubernetes/kubernetes/issues/95409#issuecomment-706191997

Is there a minimal iptables version cilium operates?
My current is iptables `v1.4.21`

P.S. Running 

```
iptables -t mangle -D OLD_CILIUM_PRE_mangle -m socket --transparent -m comment --comment "cilium: any->pod redirect proxied traffic to host proxy" -j MARK --set-xmark 0x200/0xffffffff
```

by hand did the trick bu the bug is still actual because rebooting the node causes the same CrashLoop with the same bug
### Cilium Version

cilium version
Client: 1.12.7 6719063 2023-02-13T09:31:05+01:00 go version go1.18.10 linux/amd64
Daemon: 1.12.7 6719063 2023-02-13T09:31:05+01:00 go version go1.18.10 linux/amd64

### Kernel Version

6.1.10-1.el7.elrepo.x86_64

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:22:09Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:26Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
Cilium v1.12.7 runs iptables v1.8.7:
```
$ docker run quay.io/cilium/cilium:v1.12.7 iptables --version
iptables v1.8.8 (nf_tables)
```

When you manually ran the command, did you do that inside one of the Cilium agent pods or directly on the host? I'm trying to understand what iptables binary was used when you did that.

Can you also share the kernel config for that node? Another suspicion is that the kernel module for `-m socket` may have been missing.

**Comment by pchaigno** [comment]
If I'm reading the above correctly, the `[unsupported revision]` only appears if you add a rule with the host iptables binary and then attempt to read it with Cilium's iptables binary. The error message appears because different iptables binaries are used to write and read the rule.

It doesn't explain why Cilium hit this in the logs when the rule should have been added and read by Cilium's iptables binary :thinking:

**Comment by liveder** [comment]
@pchaigno 
Seems related to this bug:
https://bugzilla.netfilter.org/show_bug.cgi?id=1632

**Comment by Antiarchitect** [comment]
> It doesn't explain why Cilium hit this in the logs when the rule should have been added and read by Cilium's iptables binary thinking

According to the logs cilium tries to delete "-D" the existing rule originally

**Comment by Antiarchitect** [comment]
Decided to rollback to 1.12.6 (before iptables update) as temprary solution - went smooth

**Comment by pchaigno** [comment]
> > It doesn't explain why Cilium hit this in the logs when the rule should have been added and read by Cilium's iptables binary thinking
> 
> According to the logs cilium tries to delete "-D" the existing rule originally

But if the node just rebooted, why was there an existing rule?

**Comment by Antiarchitect** [comment]
The rule could be preserved in /etc/sysconfig/iptables as before the investigation steps we deleted it manually

**Comment by pchaigno** [comment]
Ah, I see. And did you recently upgrade Cilium version? We've made some changes recently to the iptables version we use.

**Comment by Antiarchitect** [comment]
Yes. It was during the upgrade 1.12.5 -> 1.12.7. Then I read the changelog and rolled back to 1.12.6

**Comment by pchaigno** [comment]
OK. So this could be a regression introduced by https://github.com/cilium/cilium/pull/23163. cc @jibi
