### ISSUE TITLE
Question: Are you planning on doing releases using tags? 

### ISSUE THREAD

**Issue by rlewkowicz** [cilium/cilium#238]
I ask because I need some sort of package support. So like an `apt install cilium`. So when I boot strap swarm nodes I'm not compiling from source every time. I can set up a jenkins builder to build a repo and maintain releases. I just need to know If I should poll on changes periodically and build master or if we'll be seeing official releases?

**Comment by tgraf** [comment]
Yes, we're targeting official releases in the next couple of weeks.

We are already maintaining Docker images `cilium/cilium` with the latest and greatest builds but they are not flawless to run yet, we are ironing out the last couple of issues with regard to having the BPF filesystem mounted properly.
