### ISSUE TITLE
Implement auth communication API in Cilium Agent

### ISSUE THREAD

**Issue by youngnick** [cilium/cilium#23805]
This issue covers work to implement the communication API between the datapath and userspace for authenticating flows.

It should allow at least for:
- the datapath to say "this flow needs auth please"
- the agent to respond (probably by updating a table) with "A is authenticated to B until x time)" (this relies on #23801)

In order to ensure that we minimize drops on startup (#23808) and reauthenticate before the datapath entries expire, this will need to be able to be called from userspace as well as in response to an event from the datapath.

**Comment by mhofstetter** [comment]
adressed and fixed some issues while getting familiar with the datapath auth implementation (https://github.com/cilium/cilium/pull/21822)

- https://github.com/cilium/cilium/pull/23780
- https://github.com/cilium/cilium/pull/23839
- https://github.com/cilium/cilium/pull/23846

**Comment by mhofstetter** [comment]
initial adoption of modularization with hive cells in the auth manager
* https://github.com/cilium/cilium/pull/24041
* https://github.com/cilium/cilium/pull/24074

**Comment by mhofstetter** [comment]
Provide auth handlers with relevant data
* https://github.com/cilium/cilium/pull/24159

**Comment by mhofstetter** [comment]
Implementing new BPF map `auth` which should become the new way of keeping track of authentication state between security identities.
* https://github.com/cilium/cilium/pull/24218

**Comment by youngnick** [comment]
I think that #24410 is related here?
