### ISSUE TITLE
Cilium Nodes resources for Cilium external workload become stale when agent configs change to enable encryption.

### ISSUE THREAD

**Issue by jspaleta** [cilium/cilium#23827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Enabling wireguard encryption for external workloads is possible but can be tricky due to existing cilium node resources failing to update to include the external endpoint public key.

It would be great if the CiliumNode would automatically update to include the public key when an existing cilium cluster is updated to enable encryption and the external agent is restarted.

Currently, the existing CiliumNode resource corresponding to the external workload agent has to be manually deleted prior to agent restart.

### Cilium Version

```
$ cilium version
cilium-cli: v0.12.12 compiled with go1.19.4 on linux/amd64
cilium image (default): v1.12.5
cilium image (stable): v1.13.0
cilium image (running): v1.12.5
```

### Kernel Version

External workload vm
```
$uname -a
Linux external-workload 5.15.0-1033-azure #40~20.04.1-Ubuntu SMP Tue Jan 24 16:06:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-13T08:17:45Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

Order of operations to reproduce
1. create cilium managed k8s cluster without wireguard encryption
2. enable clustermesh on cluster
3. install the death star demo app
4. create external workload using `cilium clustermesh vm create`
5. generate install script using `cilium clustermesh vm install` and use script to start up cilium agent on external vm
6. confirm DNS on external workload resolves deathstar service
7. confirm pod connectivity from vm to cluster pod using curl to deathstar service
8. re-install cilium on cluster with wireguard encryption enabled
9. restart external workload agent with wireguard encryption enabled (and l7 proxy disabled)
10. use `sudo cilium status` on external vm to confirm encryption is enabled.
11. confirm DNS on external workload resolves deathstar service
12. fail to reconfirm pod connectivity from vm to cluster pod using curl to deathstar service 
13. Inspect CiliumNode resource for external workload confirming missing wireguard public key.
`kubectl get CiliumNode external-workload -o jsonpath='{.metadata.annotations.io\.cilium\.network\.wg-pub-key}'`
13. delete CiliumNode resource corresponding to external workload
14. restart cilium agent on external workload
15. Inspect CiliumNode resource for external workload confirming existence wireguard public key.
16. confirm pod connectivity from vm to cluster pod using curl to deathstar service
17. confirm use of cilium_wg0 on external vm using tcpdump

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
@jspaleta Thanks for the issue.

> Inspect CiliumNode resource for external workload confirming missing wireguard public key.

I'd expect that cilium-agent on the external workload VM should add the pub key to the corresponding CiliumNode. Did yo use any warnings/errors in the cilium-agent logs?

Another thing, recently we completely reworked the WireGuard integration. Could you try installing Cilium from the master branch (unreleased)?
