### ISSUE TITLE
Helm Chart Renders Duplicate ConfigMap Keys When Ingress Controller, GatewayAPI, and/or L7LB Are Enabled

### ISSUE THREAD

**Issue by DWSR** [cilium/cilium#23859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are three Helm Values that will result in the `enable-envoy-config` key being added to Cilium's ConfigMap:

https://github.com/cilium/cilium/blob/66e5ec75ed8bbb96c4129634a75f01662cc439b3/install/kubernetes/cilium/templates/cilium-configmap.yaml#L217
https://github.com/cilium/cilium/blob/66e5ec75ed8bbb96c4129634a75f01662cc439b3/install/kubernetes/cilium/templates/cilium-configmap.yaml#L225
https://github.com/cilium/cilium/blob/66e5ec75ed8bbb96c4129634a75f01662cc439b3/install/kubernetes/cilium/templates/cilium-configmap.yaml#L206

If any two of these values are enabled simultaneously (such as Ingress Controller and GatewayAPI support), it results in a ConfigMap with duplicate keys. Helm itself does not care about duplicate keys, but other tools, such as Kustomize, do.

This could be rewritten something like this:

```sprig
{{- if or .Values.gatewayAPI.enabled .Values.ingressController.enabled .Values.loadBalancer.l7.backend }}
enable-envoy-config: "true"
{{- end }}
```

### Cilium Version

1.13.0

### Kernel Version

N/A

### Kubernetes Version

N/A

### Sysdump

N/A

### Relevant log output

```shell
N/A
```

### Anything else?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Thanks for reporting the issue, would you plan to send the patch as well ? The above snippet looks good too me :)

**Comment by DWSR** [comment]
Maintaining Helm Charts is against my religion. 😜 

I should be able to manage. I'll hopefully have a PR up shortly.
