### ISSUE TITLE
MountVolume.SetUp failed for volume "bgp-config-path" : configmap "bgp-config" not found

### ISSUE THREAD

**Issue by 13567436138** [cilium/cilium#23868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

mp host-proc-sys-net]: timed out waiting for the condition
  Warning  FailedMount       35m (x12 over 43m)    kubelet            MountVolume.SetUp failed for volume "bgp-config-path" : configmap "bgp-config" not found
  Warning  FailedMount       34m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[bgp-config-path], unattached volumes=[etc-cni-netd host-proc-sys-net hostproc host-proc-sys-kernel clustermesh-secrets xtables-lock cilium-bootstrap-file-dir lib-modules kube-api-access-jd48v cilium-run cilium-cgroup bgp-config-path cni-path tmp bpf-maps]: timed out waiting for the condition
  Warning  FailedMount       25m (x8 over 26m)     kubelet            MountVolume.SetUp failed for volume "bgp-config-path" : configmap "bgp-config" not found
  Warning  FailedMount       2m43s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[bgp-config-path], unattached volumes=[tmp host-proc-sys-kernel clustermesh-secrets cni-path bgp-config-path host-proc-sys-net bpf-maps lib-modules xtables-lock etc-cni-netd cilium-bootstrap-file-dir cilium-cgroup cilium-run kube-api-access-jd48v hostproc]: timed out waiting for the condition
  Warning  FailedMount       33s (x10 over 4m44s)  kubelet            MountVolume.SetUp failed for volume "bgp-config-path" : configmap "bgp-config" not found
  Warning  FailedMount       27s                   kubelet            Unable to attach or mount volumes: unmounted volumes=[bgp-config-path], unattached volumes=[host-proc-sys-kernel hostproc clustermesh-secrets cni-path tmp host-proc-sys-net bgp-config-path bpf-maps cilium-bootstrap-file-dir cilium-run cilium-cgroup kube-api-access-jd48v etc-cni-netd xtables-lock lib-modules]: timed out waiting for the condition

### Cilium Version

v1.13.0

### Kernel Version

5.15

### Kubernetes Version

v1.26.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
As mentioned in https://docs.cilium.io/en/v1.13/network/bgp/, it seems like the configmap must be created before enabling bpg.

> BGP support is enabled by providing the BGP configuration via a ConfigMap and by setting a few Helm values. Otherwise, BGP is disabled by default.

**Comment by Apocrathia** [comment]
Heads up that this is happening again, and the 1.14 documentation does not mention the ConfigMap. https://docs.cilium.io/en/v1.14/network/bgp-control-plane/

**Comment by YutaroHayakawa** [comment]
@Apocrathia Thanks for the reporting, but the document you mentioned is not the equivalent of the one in the original issue. The same sentence @sayboras mentioned still exists on the v1.14 as well.

https://docs.cilium.io/en/v1.14/network/bgp/
