### ISSUE TITLE
Cilium doesn't recognize built-in kernel modules, causing IPv6 to fail on Talos Linux

### ISSUE THREAD

**Issue by nmdanny** [cilium/cilium#23863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've encountered this in Talos Linux which does not have any loadable kernel modules, rather, most modules are linked statically
When trying to enable IPv6 support:

```yaml
ipv6:
  enabled: true

securityContext:
  privileged: true

ipam:
  mode: kubernetes

kubeProxyReplacement: "strict"
k8sServiceHost: "192.168.13.37"
k8sServicePort: "6443"

```

(this also happens with kube-proxy enabled)

Then the agent fails (see below for logs)

The issue seems to be with https://github.com/cilium/cilium/blob/66e5ec75ed8bbb96c4129634a75f01662cc439b3/pkg/modules/modules_linux.go 

It tries to read `/proc/modules` which is empty, so it then tries to dynamically load the modules, e.g by doing
`modprobe ip6_tables` which fails on Talos Linux:

```shell
root@cwwk-box:/home/cilium# modprobe ip6_tables -n
modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/6.1.7-talos
```

I think a better solution would be to check the built in modules first:

```shell
root@cwwk-box:/home/cilium# cat /lib/modules/6.1.7-talos/modules.builtin | grep -E '(ip6table|ip_tables|xt_socket)'
kernel/net/netfilter/xt_socket.ko
kernel/net/ipv4/netfilter/ip_tables.ko
kernel/net/ipv6/netfilter/ip6table_filter.ko
kernel/net/ipv6/netfilter/ip6table_mangle.ko
kernel/net/ipv6/netfilter/ip6table_raw.ko
kernel/net/ipv6/netfilter/ip6table_security.ko
kernel/net/ipv6/netfilter/ip6table_nat.ko
```

When I patched cilium to skip the module check, it seems to work fine 

### Cilium Version

v1.13.0

### Kernel Version

`6.1.7-talos`

also encountered on talos `v1.3.4` which uses `5.15`

### Kubernetes Version

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.26.1

### Relevant log output

```shell
cilium-agent level=fatal msg="IPv6 is enabled and ip6tables modules could not be initialized (try disabling IPv6 in Cilium or loading ip6_tables, ip6table_mangle, ip6table_raw and ip6table_filter kernel modules)" error="could not load module ip6_tables: exit status 1" subsys=iptables
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrewrynhard** [comment]
It seems that Cilium has issues running on Talos every release. I would love to figure out some way to prevent this from the future. The Talos and Cilium pairing is popular in our community and others. Would the maintainers be open to discussions about this?

**Comment by TheAifam5** [comment]
Loaded dynamic modules are placed under `/proc/modules` but there is also a better place to get builtin and dynamic from `/sys/module`.

**Comment by pchaigno** [comment]
@nmdanny From the `/lib/modules/6.1.7-talos/modules.builtin` output you showed, it doesn't look like you have module `ip6_tables`. If skipping the module checks allowed Cilium to proceed, then that suggests this module isn't actually needed by Cilium, right? A sysdump would help here, to understand the general state of the cluster when the module checks are skipped.

Were you able to verify if the issue you hit is only for `ip6_tables`? Does it also happen for example with `ip6table_filter`?

<br>

> It seems that Cilium has issues running on Talos every release. I would love to figure out some way to prevent this from the future. The Talos and Cilium pairing is popular in our community and others. Would the maintainers be open to discussions about this?

@andrewrynhard I believe we would all very much be opened to that. The most obvious way to fix this would be to cover Talos in Cilium's CI. The weekly community meeting may be a good place to discuss that. You can ask in Slack's #development to add an open discussion item to that meeting's agenda.

Note the difficulty here is likely to find a group of folks ready to invest time and resources to maintain and host such a CI job for Talos.

**Comment by TheAifam5** [comment]
I managed to install cilium with IPv6 :) Would anyone be willing to review the patch?

**Comment by nmdanny** [comment]
> @nmdanny From the `/lib/modules/6.1.7-talos/modules.builtin` output you showed, it doesn't look like you have module `ip6_tables`. If skipping the module checks allowed Cilium to proceed, then that suggests this module isn't actually needed by Cilium, right? A sysdump would help here, to understand the general state of the cluster when the module checks are skipped.
> 
> Were you able to verify if the issue you hit is only for `ip6_tables`? Does it also happen for example with `ip6table_filter`?
> 

I trimmed down the output of `modules.buitlin` with a regex- I think I missed `ip6_tables` in the regex `ip6table|ip_tables|xt_socket` - I believe it's there but I'll verify when I'm home

**Comment by pchaigno** [comment]
> I managed to install cilium with IPv6 :) Would anyone be willing to review the patch?

@TheAifam5 If you have a patch for a bug in Cilium, we'd be happy to review it as a pull request :-)

**Comment by TheAifam5** [comment]
@pchaigno Done. I want to say that it is my first contribution so I tried to follow as closely to the guidelines but I am unable to start all the tests on my current machine.

If anyone is interested, it can pushed the image to my docker.io repository under: https://hub.docker.com/u/theaifam5

**Comment by TheAifam5** [comment]
@ajaykumarmandapati right now, it is not up to me. I made a PR which solves the problem on Talos Linux and should be also applicable to other distributions. I made a PR here: https://github.com/cilium/cilium/pull/23953 but someone needs to review it and accept and maybe there will be some comments I will need to fix... it will take time, the PR already is 2 weeks old.

If you really trust random guy from the internet, you might also just use https://hub.docker.com/r/theaifam5/cilium :upside_down_face: but it's up to you. I do not know if the operator is needed, but the generic one you can find also here: https://hub.docker.com/r/theaifam5/operator-generic

Other way, just build yourself, follow those steps:
- Download 1.13.0 source code
- Download the patch from PR and apply to extracted source
  **Go to the PR and append .patch to the URL - you will get a patch file from the PR**
  **Example: https://github.com/cilium/cilium/pull/23953.patch**
- Make sure you have Docker and buildx  installed
- Execute `make docker-cilium-image docker-operator-generic-image DOCKER_REGISTRY=<registry_url> DOCKER_DEV_ACCOUNT=<username> DOCKER_FLAGS=--push DOCKER_IMAGE_TAG=v1.13.0`
  **Replace <..> with a proper values**

If you have a Docker and Buildx then the whole process will take few minutes. Of course don't forget to login into your registry.

**Comment by ajaykumarmandapati** [comment]
@TheAifam5 Thanks for your quick response! 👍🏾 
I did check and found them in place, see the output below. I will check if your [patched](https://github.com/cilium/cilium/pull/23953) Cilium would work for us and let you know.

`[root@admin]# cat /lib/modules/5.15.79/modules.builtin | grep ipv6`
`kernel/net/ipv6/ipv6.ko`
`kernel/net/ipv6/netfilter/ip6_tables.ko`

**Comment by ajaykumarmandapati** [comment]
For some reason, I was unable to reuse your image and got a weird error the config `container` which is part of cilium has this error - `exec /usr/bin/cilium: exec format error`

However, now I try to build the image based on your patch and that fails with cilium showing this log output -
`info layer=debugger launching process with args: [/usr/bin/cilium-agent-bin --config-dir=/tmp/cilium/config-map]
could not launch process: could not open debug info - debuggee must not be built with 'go run' or -ldflags='-s -w', which strip debug info`

M1 mac , running docker desktop and the command I used to build the image was 
`docker buildx build --no-cache . -f ./images/cilium/Dockerfile --platform linux/amd64,linux/arm64`

**Comment by TheAifam5** [comment]
@ajaykumarmandapati Try with:
```
make docker-cilium-image DOCKER_REGISTRY=<registry_url> DOCKER_DEV_ACCOUNT=<username> DOCKER_FLAGS=--push DOCKER_IMAGE_TAG=v1.13.0
```

but you need a registry for that.

**Comment by sdomme** [comment]
@TheAifam5 Hi. I took over from @ajaykumarmandapati and was able to build the images with your patch and test it on our system. Bottlerocket OS on EKS 1.24 
It does work. It seems to fix the issue mentioned by @ajaykumarmandapati
