### ISSUE TITLE
I set ipam.operator.clusterPoolIPv4PodCIDR=10.1.0.0/16 why the pod ip allocated is still 10.0

### ISSUE THREAD

**Issue by 13567436138** [cilium/cilium#23872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

install cilium with:
helm install --kubeconfig ~/.kube/147config --kube-context cluster2 cilium . -n kube-system  \
  --set cluster.id=2 \
  --set cluster.name=cluster2 \
  --set ipam.operator.clusterPoolIPv4PodCIDR=10.1.0.0/16

thie ip allocated is not wright.

```
root@cluster2-147:~# kubectl get pod -A -owide
NAMESPACE        NAME                                    READY   STATUS    RESTARTS        AGE     IP                NODE        NOMINATED NODE   READINESS GATES
kube-system      cilium-gwh58                            1/1     Running   0               6m11s   192.168.229.147   worker-01   <none>           <none>
kube-system      cilium-hssc7                            1/1     Running   0               6m10s   192.168.229.149   worker-02   <none>           <none>
kube-system      cilium-l5tr4                            1/1     Running   0               6m10s   192.168.229.150   worker-03   <none>           <none>
kube-system      cilium-node-init-hvbgp                  1/1     Running   0               6m11s   192.168.229.147   worker-01   <none>           <none>
kube-system      cilium-node-init-r2dvr                  1/1     Running   0               6m11s   192.168.229.150   worker-03   <none>           <none>
kube-system      cilium-node-init-r7zm6                  1/1     Running   0               6m11s   192.168.229.149   worker-02   <none>           <none>
kube-system      cilium-operator-6cd654bd49-ptfb6        1/1     Running   0               6m10s   192.168.229.147   worker-01   <none>           <none>
kube-system      cilium-operator-6cd654bd49-zk6qs        1/1     Running   0               6m10s   192.168.229.149   worker-02   <none>           <none>
kube-system      clustermesh-apiserver-68468fb76-g79ml   2/2     Running   0               3m41s   10.0.1.79         worker-03   <none>           <none>

```

### Cilium Version

root@cluster1-144:~/cilium# cilium version
cilium-cli: v0.12.13 compiled with go1.20 on linux/amd64
cilium image (default): v1.12.6
cilium image (stable): unknown
cilium image (running): v1.13.0

### Kernel Version

root@cluster1-144:~/cilium# uname -a
Linux cluster1-144 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

root@cluster1-144:~/cilium# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
That doesn't seem expected. Could you share a Cilium sysdump of the cluster?

**Comment by hainamtvvt** [comment]
Must set ipam.mode=cluster-pool

**Comment by pchaigno** [comment]
@hainamtvvt `cluster-pool` is the default value for `ipam.mode`.

**Comment by hainamtvvt** [comment]
Maybe already set value PodCIDR when install K8s Cluster

**Comment by 13567436138** [comment]
my k8s cluster podcidr is 172.21.0.0/16

**Comment by 13567436138** [comment]
[cilium-sysdump-20230222-151319.zip](https://github.com/cilium/cilium/files/10801003/cilium-sysdump-20230222-151319.zip)

**Comment by 13567436138** [comment]
why

**Comment by 13567436138** [comment]
I solved it by setting podcidr the same as cilium，when install k8s

**Comment by gandro** [comment]
Looking at the sysdump, I see the following error in the CiliumNode status: `error: allocator not configured for the requested CIDR 10.0.0.0/24`. This indicates that the cluster was created with the default clusterPoolIPv4PodCIDR (which is `10.0.0.0/8`), and it was only later changed to `10.1.0.0./16`.

Changing the `clusterPoolIPv4PodCIDR` in a running cluster is not really supported, it can only be set at installation time. To change it, one has to remove all nodes from the cluster first, remove all CiliumNode objects (or remove their old pod CIDR) and then add the nodes back in, so the cilium agents can allocate new pod CIDRs from the new clusterPoolIPv4PodCIDR. 

The operator will never remove existing podCIDRs from nodes, even if they don't belong to the new clusterPoolIPv4PodCIDR. Instead, it will populate `status.ipam.operator-status` with the above message.

**Comment by jgomezve** [comment]
Hi

How does it relate when installing Cilium on AWS or GCP? I can't get rid off the default podCIDR

This is the command I use
```
cilium install   --datapath-mode tunnel   --set cluster.id=1   --set cluster.name=eks   --set eni.enabled=false   --set tunnel=vxlan   --set ipam.mode=cluster-pool   --set ipam.operator.clusterPoolIPv4PodCIDRList=10.111.0.0/16
```
