### ISSUE TITLE
Docs: Update Contribution Guide with Instructions for Running Cilium Docs Locally

### ISSUE THREAD

**Issue by kayceeDev** [cilium/cilium#23879]
Currently, the documentation lacks detailed information on how to set up and run it locally.

I believe that an update to the guide with instructions on how to run the documentation locally would make it easier for new contributors to make changes and preview their work.

Things to consider:
- System requirements for running the documentation
- Step-by-step instructions for installing and setting up the documentation locally
- How to view the documentation in a web browser
- How to make changes and preview them locally.

Then include the link to this new section in the `CONTRIBUTING.md`

**Comment by pchaigno** [comment]
In case you haven't already seen it, we have https://docs.cilium.io/en/latest/contributing/docs/docstest/#testing-documentation.

**Comment by kayceeDev** [comment]
> In case you haven't already seen it, we have https://docs.cilium.io/en/latest/contributing/docs/docstest/#testing-documentation.

I have. There was some improvement suggested. That's what I want to work on.

**Comment by zacharysarah** [comment]
@kayceeDev The description looks reasonably well scoped to me. Go for it! Please feel free to assign me for review when you open a PR.

**Comment by kayceeDev** [comment]
> @kayceeDev The description looks reasonably well scoped to me. Go for it! Please feel free to assign me for review when you open a PR.

Definitely 😊
