### ISSUE TITLE
plugin type="cilium-cni" name="cilium" failed (add): failed to find plugin "cilium-cni" in path [/opt/kube/bin]

### ISSUE THREAD

**Issue by 13567436138** [cilium/cilium#23870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened! Warning  FailedCreatePodSandBox  33s               kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4e4719cbaa7e05ccee9b41be37f362c67df85c6eb9d0c2c4e20a5ed3321382aa": plugin type="cilium-cni" name="cilium" failed (add): failed to find plugin "cilium-cni" in path [/opt/kube/bin]

where can i find binary of cilium-cni？

### Cilium Version

v1.13.0

### Kernel Version

5.15

### Kubernetes Version

v1.26.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pavankumar-go** [comment]
@13567436138 did you find the solution to this ?

**Comment by DesireWithin** [comment]
Facing same error.
I go inside the cilium agent pod. I see there is a path `/host/opt/cni/bin`, which is mount as `/opt/cni/bin` of the worker,
And there is a path `/opt/cni/bin` in the pod, there is a `cilium-cni` in it indeed.
