### ISSUE TITLE
Docs: Update documentation for a K3S cluster implementation with Netmaker + Wireguard for an Edge Cluster

### ISSUE THREAD

**Issue by benpsnyder** [cilium/cilium#23883]
I invested a good deal of time into getting this working, and wanted to share for others to benefit. See  [gravitl/netmaker - Building a cross-cloud wide edge network with K3S + Cilium CNI + Istio](https://github.com/gravitl/netmaker/issues/2054) (gravitl/netmaker#2054)

More information will drop in the coming weeks when we go through the Istio implementaiton, and a sample multi-cluster setup using Cilium's clustermesh. Would love some help from the Cilium community if anyone is interested in this.

**Comment by pchaigno** [comment]
@xmulligan may be interested.
