### ISSUE TITLE
datapath: Per endpoint routes broken for IPv6 traffic between (remote) node to pod when netpol is applied

### ISSUE THREAD

**Issue by brb** [cilium/cilium#23910]
The ICMPv6 neighbor resolution is striking us again (#23852). When sending a request from a remote node / a local node to the `echo` pod, the ICMPv6 NS is using the `echo`'s pod veth iface in the host netns IPv6 addr:
```
7: lxc75bc3f9009e7    inet6 fe80::ec8b:fdff:fe18:6632/64 scope link
```

And of course, it's not recognized by the `to-container` @ `lxc75bc3f9009e7`:

```
CPU 07: MARK 0x0 FROM 1192 DEBUG: Inheriting identity=1 from stack
<- stack flow 0x0 , identity host->unknown state unknown ifindex 0 orig-ip 0.0.0.0: fe80::ec8b:fdff:fe18:6632 -> ff02::1:ff00:3816 NeighborSolicitation
CPU 07: MARK 0x0 FROM 1192 DEBUG: Conntrack lookup 1/2: src=[::fe18:6632]:0 dst=[::ff00:3816]:0
CPU 07: MARK 0x0 FROM 1192 DEBUG: Conntrack lookup 2/2: nexthdr=58 flags=0
CPU 07: MARK 0x0 FROM 1192 DEBUG: CT verdict: New, revnat=0
CPU 07: MARK 0x0 FROM 1192 DEBUG: Successfully mapped addr.p4=[::fe18:6632] to identity=2
CPU 07: MARK 0x0 FROM 1192 DEBUG: Attempting local delivery for container id 1192 from seclabel 44107
CPU 07: MARK 0x0 FROM 1192 DEBUG: Policy evaluation would deny packet from 2 to 44107
Policy verdict log: flow 0x0 local EP ID 1192, remote ID world, proto 58, ingress, action deny, match none, fe80::ec8b:fdff:fe18:6632 -> ff02::1:ff00:3816 NeighborSolicitation
xx drop (Policy denied) flow 0x0 to endpoint 1192, ifindex 7, file 2:1604, , identity world->44107: fe80::ec8b:fdff:fe18:6632 -> ff02::1:ff00:3816 NeighborSolicitation
```

A few possible fixes:
- Add the IPv6 local scope addr of a pod into the IPCache, so that the non-world sec ID is used.
- Respect the `HOST_ID` skb mark in the `to-container` section.

**Comment by jschwinger233** [comment]
@brb , do you think we can do the same for ICMP6 NS/ND as ARP?

In `from-container`, we either tail_call `CILIUM_CALL_ARP`, or pass the skb to stack:

https://github.com/cilium/cilium/blob/62f72cd3b1251c85fa19375c222a5f58de8747a5/bpf/bpf_lxc.c#L1354-L1360

In `to-container`, we pass the ARP skb to stack anyhow:

https://github.com/cilium/cilium/blob/62f72cd3b1251c85fa19375c222a5f58de8747a5/bpf/bpf_lxc.c#L2163-L2165

For both direction, our bpf program on lxc doesn't perform policy check for ARP, and I was wondering if it's reasonable to follow this rule and skip policy check for IPv6 NDP at all? If it's acceptable, we won't be bothered by these issues at all.

**Comment by aspsk** [comment]
I had a similar problem in https://github.com/cilium/cilium/pull/22006 Namely, it appeared that when endpoint routes are enabled, we send NS requests using link-local addresses of `lxc*`, and thus pods reply to link-local addresses and they are recognized as `world` and dropped by `fib_redirect` as non-routable. I was able to fix this by installing neighbour entries manually. See the https://github.com/cilium/cilium/commit/47769617a3f2a30a6283b720dbcb10d7d312416a commit (in the https://github.com/aspsk/cilium/tree/aspsk/pr/endpoint-routes-with-bpf-redirection-ipv6 branch).

**Comment by brb** [comment]
Once fixed, let's remove https://github.com/cilium/cilium-cli/blob/v0.14.1/connectivity/check/test.go#L563.
