### ISSUE TITLE
CFP: FIPS build of Cilium

### ISSUE THREAD

**Issue by john-nunes** [cilium/cilium#23919]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

Yes.

If so, please describe the problem

We are looking to deploy Rancher within a FedRamp environment and Rancher RKE2 only has a FIPS compliant Canal build. We are looking at Cilium as a possible alternative. With the inclusion of boringcrypto in the Go compiler, this should be possible?

**Describe the feature you'd like**

A FIPS build of Cilium.

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by joestringer** [comment]
Thanks for the feature proposal. I think it would make sense to accept any patches that make it easier to produce FIPS-compliant builds of Cilium.
