### ISSUE TITLE
CFP: Move away from early-cycle RCs in favor of snapshot releases

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#23926]
During recent release cycles, Cilium has gone through a process of releasing monthly snapshots of the tree as vX.Y.0-rcN. These snapshots have been useful as regular targets for developers to focus on in order to ship features, but at the same time they have also raised some questions in the community:

1. Given that the format is vX.Y.0-rcN, this format does not follow [SemVer v2](https://semver.org/spec/v2.0.0.html). Some tooling expects the form `vX.Y.Z-rc.N` instead, and can better handle the number ordering if we follow SemVer v2.
2. Most related projects do not consider any monthly snapshot of the main branch as a "release candidate", so it can be confusing for users to understand how close the release is when each month brings a new release candidate with various brand new features.

I'd like to propose moving to a scheme like `vX.Y.0-snapshot.N` for each monthly release, then once we reach close to feature freeze, we can begin tagging release candidates. We can continue to encourage users to download and try out snapshot releases in order to provide early feedback on new features.

The primary blocker for this effort is to update the `contrib/` release scripting to support the new version format. I can take on that effort as part of preparing the February snapshot release.

**Comment by rolinh** [comment]
Thanks for writing this down, I'm all in favor of moving to SemVer v2 as this will alleviate the problem, notably with Go, that `v1.0.0-beta1 < v1.0.0-beta10 < v1.0.0-beta2` as opposed to `v1.0.0-beta.1 < v1.0.0-beta.2 < v1.0.0-beta.10` :tada: 

Something to consider however: the `vX.Y.0-rc.N` scheme is technically not SemVer v2 compatible in the sense the that the `v` prefix should be omitted (see [here](https://semver.org/spec/v2.0.0.html#is-v123-a-semantic-version)). However, Go modules expect versions with a `v` prefix (see [here](https://go.dev/doc/modules/version-numbers)).

> I'd like to propose moving to a scheme like vX.Y.0-snapshot.N for each monthly release, then once we reach close to feature freeze, we can begin tagging release candidates.

Is there a particular reason to use the term `snapshot` instead of the more standardized `alpha < beta < rc` for pre-release versions?

**Comment by joestringer** [comment]
> Something to consider however: the vX.Y.0-rc.N scheme is technically not SemVer v2 compatible in the sense the that the v prefix should be omitted (see [here](https://semver.org/spec/v2.0.0.html#is-v123-a-semantic-version)). However, Go modules expect versions with a v prefix (see [here](https://go.dev/doc/modules/version-numbers)).

As it turns out we are already tagging every release with two tags: One with the `v` prefix and one without. The official version from `VERSION` file at the top of the repo already omits the prefix so that version should follow Semver v2. If you find any other places where we need to include or omit the prefix, then please raise them or file a PR to improve the way these versions interact with other tooling.

> Is there a particular reason to use the term snapshot instead of the more standardized alpha < beta < rc for pre-release versions?

So far we've followed a model where the main branch is always releasable, hence our prior approach to labeling RCs at arbitrary points during development. For specific features we may determine the stability and document those features as beta / stable / etc, but we don't make any such classification for the overall release. Discussing with some folks, I heard opinions that labeling the snapshots as a "beta" implies in some way that the core functionality is somehow less stable than the RCs or full releases, but that's not really the case. The idea with the `-snapshot` naming is to avoid some of those preconceptions.

**Comment by joestringer** [comment]
We've moved towards snapshots and successfully published them for the first two months of v1.14 development. Closing this issue.
