### ISSUE TITLE
Any egress ICMP other than echos are dropped from node

### ISSUE THREAD

**Issue by liuyuan10** [cilium/cilium#23955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is on GKE but I think in general it applies to any direct routing cluster.

I noticed ICMP packets are being dropped by bpf_host:

```
xx drop (Unsupported protocol for NAT masquerade) flow 0x0 to endpoint 0, file bpf_host.c line 2285, , identity unknown->unknown: 10.128.0.62 -> 34.27.115.13 DestinationUnreachable
```

It was dropped because all ICMPs except echos are not supported by SNAT  [here](https://github.com/cilium/cilium/blob/master/bpf/lib/nat.h#L788)

What surprises me is that it's dropped even when bpf-masquerade is off. It turns out that any traffic using the node IP as source has to be  SNATTed to avoid conflict with nodeport [code](https://github.com/cilium/cilium/blob/master/bpf/lib/nat.h#L620)

In GKE, any pod to external traffic is masqueraded by iptables to node IP, so the ICMP drop applies to pod ICMP too.

Therefore, any non-echo ICMPs from GKE cluster node and pods are being dropped.

#18414 add support for ingress ICMPs for a specific ICMP type. This issue is for egress.

My cilium configmap:
[configmap.txt](https://github.com/cilium/cilium/files/10809665/configmap.txt)

### Cilium Version

I'm testing on v1.12 but should apply to any version

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
Related: https://github.com/cilium/cilium/issues/15890

**Comment by julianwiedmann** [comment]
> What surprises me is that it's dropped even when bpf-masquerade is off. It turns out that any traffic using the node IP as source has to be SNATTed to avoid conflict with nodeport [code](https://github.com/cilium/cilium/blob/master/bpf/lib/nat.h#L620)

FYI, I *think* this should be resolved on latest `main`: https://github.com/cilium/cilium/blob/ebdfb375c9c6a4b68b234077a8983a749aad3952/bpf/lib/nodeport.h#L1607
