### ISSUE TITLE
Garbage-Collection for identities not working

### ISSUE THREAD

**Issue by dbaumgarten** [cilium/cilium#23970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have a Kubernetes-Cluster with cilium that regularly starts lots of short-lived pods (with unique labels). Up to 10000 a day.
A few days ago we updated from cilium v1.10.9 to v1.10.19.
Today we experienced issues that no new pods could be started anymore with the error ```Key allocation attempt failed attempt=0 error="no more available IDs in configured space" ```.

Upon investigating we found that ```kubectl get ciliumid``` returns about 65000 entries. None of them older then from the time where we updated to v1.10.19. And most of these identities were for pods that did not exist anymore.

After manually deleting the old ciliumids with kubectl, the cluster started to work normally.

The question that remains is: Why did cilium not clean up the unused identities on its own?
I thought that there is a gc for this? Is it not enabled by default?

The timing makes it seem like it has something to do with the update to v1.10.19, but it could be just a coincidence.

### Cilium Version

v1.10.19 and v1.10.9 before that.

### Kernel Version

5.4.0-137-generic

### Kubernetes Version

v1.23.0

### Anything else?

Cilium-config:
```
  identity-allocation-mode: crd
  cilium-endpoint-gc-interval: "5m0s"
  debug: "false"
  enable-policy: "default"
  enable-ipv4: "true"
  enable-ipv6: "false"
  custom-cni-conf: "false"
  enable-bpf-clock-probe: "true"
  monitor-aggregation: medium
  monitor-aggregation-interval: 5s
  monitor-aggregation-flags: all
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-lb-map-max: "65536"
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: "cilium/istio_proxy"
  cluster-name: default
  cluster-id: ""
  tunnel: vxlan
  enable-l7-proxy: "true"
  wait-bpf-mount: "false"
  masquerade: "true"
  enable-bpf-masquerade: "true"
  enable-xt-socket-fallback: "true"
  install-iptables-rules: "true"
  auto-direct-node-routes: "false"
  enable-bandwidth-manager: "false"
  enable-local-redirect-policy: "false"
  kube-proxy-replacement:  "partial"
  kube-proxy-replacement-healthz-bind-address: ""
  enable-health-check-nodeport: "false"
  enable-host-reachable-services: "true"
  node-port-bind-protection: "true"
  enable-auto-protect-node-port-range: "true"
  enable-session-affinity: "true"
  enable-endpoint-health-checking: "true"
  enable-health-checking: "true"
  enable-well-known-identities: "false"
  enable-remote-node-identity: "true"
  operator-api-serve-addr: "127.0.0.1:9234"
  enable-hubble: "true"
  hubble-socket-path:  "/var/run/cilium/hubble.sock"
  hubble-listen-address: ":4244"
  hubble-disable-tls: "false"
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  ipam: "kubernetes"
  disable-cnp-status-updates: "true"
  enable-ipsec: "true"
  ipsec-key-file: /etc/ipsec/keys
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hello, thanks for opening the GH issue, please provide steps to reproduce the issue and a cilium sysdump otherwise the issue can't be fixed. Thank you.

**Comment by dbaumgarten** [comment]
Here is the sysdump: [cilium-sysdump-20230223-132640.zip](https://github.com/cilium/cilium/files/10813933/cilium-sysdump-20230223-132640.zip)  (limited to two affected nodes to keep it small enough to upload here).

Steps to reproduce:
1. Have a Kubernetes-Cluster with cilium v1.10.19 
2. Create thousands of short-lived pods with different labels (which causes cilium to create thousands of ciliumids)
3. After a while (depending on the pod spawn-rate) you reach >65000 ciliumids and the cluster is no longer able to spawn new pods)
4. You will see lots of unneeded ciliumids in the cluster. After deleting them manually, the cluster resumes normal operations (until the ciliumids reach 65k again)

**Comment by dbaumgarten** [comment]
Issue solved....
The ClusterRole for the operator was missing some permissions, so the controller did not start up properly and no GC ever happened.
After fixing ther permissions, everything seems to be working as intended.
