### ISSUE TITLE
CI: TestConformance/HTTPRouteHeaderMatching

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#23999]
## CI failure

```
    --- FAIL: TestConformance/HTTPRouteHeaderMatching (0.03s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/10_request_to_'/'_with_headers_should_receive_a_404 (0.01s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/0_request_to_'/'_with_headers_should_go_to_infra-backend-v1 (1.01s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/9_request_to_'/'_with_headers_should_go_to_infra-backend-v2 (1.01s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/7_request_to_'/'_with_headers_should_go_to_infra-backend-v1 (0.00s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/6_request_to_'/'_with_headers_should_go_to_infra-backend-v1 (0.00s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/5_request_to_'/'_with_headers_should_receive_a_404 (0.00s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/4_request_to_'/'_with_headers_should_receive_a_404 (0.00s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/8_request_to_'/'_with_headers_should_go_to_infra-backend-v2 (0.02s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/2_request_to_'/'_with_headers_should_go_to_infra-backend-v1 (0.00s)
        --- PASS: TestConformance/HTTPRouteHeaderMatching/1_request_to_'/'_with_headers_should_go_to_infra-backend-v2 (0.00s)
        --- FAIL: TestConformance/HTTPRouteHeaderMatching/3_request_to_'/'_with_headers_should_go_to_infra-backend-v2 (30.00s)
```

https://github.com/cilium/cilium/actions/runs/4260396740/jobs/7413516586

[logs_1181774.zip](https://github.com/cilium/cilium/files/10822128/logs_1181774.zip)

**Comment by sayboras** [comment]
This is relatd to PR https://github.com/cilium/cilium/pull/22680, I think it's better to roll forward and fix the issue, as this PR is part of 1.14 development cycle.

**Comment by lmb** [comment]
Another flake: https://github.com/cilium/cilium/actions/runs/4281046005/jobs/7453567927

**Comment by ysksuzuki** [comment]
Hello, is this failure related to the flake reported here?

https://github.com/cilium/cilium/actions/runs/4311719756/jobs/7521409184

```
--- FAIL: TestConformance/HTTPRouteHostnameIntersection (63.43s)
        --- FAIL: TestConformance/HTTPRouteHostnameIntersection/HTTPRoutes_that_do_intersect_with_listener_hostnames (63.02s)
```

**Comment by sayboras** [comment]
thanks, we can collate the details here :100:

**Comment by aspsk** [comment]
Have same here: https://github.com/cilium/cilium/actions/runs/4305879207/jobs/7522422026#step:13:1040

**Comment by gandro** [comment]
Can we disable the test for now? It seems to occur pretty frequently, about every third run, judging from https://github.com/cilium/cilium/actions/workflows/conformance-gateway-api.yaml

**Comment by sayboras** [comment]
Done, I might enable it back once I start working on the fix, so expect some failure during that window.

**Comment by gandro** [comment]
> Done, I might enable it back once I start working on the fix, so expect some failure during that window.

Ah, I would have suggested to only disable the HTTPRouteHeaderMatching test using `go test -skip`, instead of disabling the whole workflow
