### ISSUE TITLE
Sync TLS interception secrets to Envoy via SDS

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#24020]
Now that support for syncing k8s secrets to Envoy via SDS exists, we should use that also for TLS interception secret sync.

References:
- [PR 9486: Envoy TLS support with header imposition](https://github.com/cilium/cilium/pull/9486)
- [PR 18894: Add support for CiliumEnvoyConfig CRD](https://github.com/cilium/cilium/pull/18894)

**Comment by meyskens** [comment]
Update: changes on Cilium side are close to ready however cilium/proxy is not receiving the tls discovery keys correctly. @jrajahalme is looking into it

**Comment by meyskens** [comment]
Update: on the agent side the code is ready and functional. Tests are passing but flaky due to a potential issue where envoy goes into a sync lock while waiting on a secret to be available. We are working to resolve this in the proxy code before continuing this work.
