### ISSUE TITLE
Ingress still allowed after deleting policy that allowed it

### ISSUE THREAD

**Issue by ntaylor1781** [cilium/cilium#2408]
### Ingress still allowed after deleting policy that allowed it

When having multiple policies to allow ingress, if you delete a policy that had allowed ingress from pod A to pod B, pod A can still communicate with pod B. 

### General Information

- Cilium version: Cilium 0.13.90 56906ce Thu, 21 Dec 2017 21:51:13 +0100 go version go1.9 linux/amd64
- Kernel version: 4.11.11-coreos
- Orchestration system version:
`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}`

### How to reproduce the issue

1. Set policy enforcement ingress to always
2. Create two pods with different app names
3. Verify that pod A can't communicate with pod B
4. Create a policy that allows ingress to pod B from pod A
5. Test communication to verify it works. 
6. Delete the policy that allows ingress. 
7. Try communication from pod A to pod B. Communication works and continues to work when it shouldn't.

If you create a new pod from either one, and attempt communication, it will not work. It is only the two pods, where communication occurred before, that will work.

**Comment by manalibhutiyani** [comment]
Looks like a conn tracking issue. Assigning to Andre, to take a look.

**Comment by manalibhutiyani** [comment]
How is the communication taking place? Are you running a new curl command every time after deleting/enforcing the policy? or something else? Could you give a bit more information on whether the communication is a persistent tcp connection or a new connection? This could be related to the persistent tcp connections issue which we saw recently on Kafka.  Issue #2471

**Comment by ntaylor1781** [comment]
I tried it with a new curl, telnet, and ping. On each test I also let it sit for a while in case there was some sort of cache, before trying again. Each time I would also verify there was not an open connection before continuing with my test.

**Comment by manalibhutiyani** [comment]
@ntaylor1781 Could you please provide the cilium logs along with the `cilium monitor` output while running the traffic. This will give some idea where the packets are going. Also could you provide the output of  `cilium endpoint list` and `cilium policy get`

**Comment by aanm** [comment]
@ntaylor1781 I'm able to replicate this issue, I'll work on a fix for this.
