### ISSUE TITLE
Start hook failed

### ISSUE THREAD

**Issue by thanhlong9x** [cilium/cilium#24090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened when I install cilium on k8s version 1.26.1
![error cilium ebpf](https://user-images.githubusercontent.com/29721257/222035059-eaa8e67a-271e-4677-9512-d4121ed278b3.PNG)

### Cilium Version

1.13.0

### Kernel Version

5.8.0-63-generic (OS ubuntu 20.10)

### Kubernetes Version

1.26.1

### Anything else?

This is my config
![image (1)](https://user-images.githubusercontent.com/29721257/222035856-7a6c914b-23f4-4976-a8d5-4c141d9a22ca.png)
![image (2)](https://user-images.githubusercontent.com/29721257/222035820-89ac0253-5675-4106-9fa7-b99a401f4471.png)
![image (3)](https://user-images.githubusercontent.com/29721257/222035851-14d5e341-5f7b-4ff3-a268-d22452eb8495.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joamaki** [comment]
Ping @jibi. Could you take a look as this looks egress gateway related: it looks like we `#define HAVE_ENCAP` when either `ENCAP_IFINDEX` or `ENABLE_EGRESS_GATEWAY` is set (lib/common.h:50). Does this imply that egress gateway requires tunnel mode to function or this is accidental?

**Comment by jibi** [comment]
Egress gateway requires tunneling to forward packets to the gateway nodes, so if the feature is enabled but tunneling is not, we explicitly enable it:

https://github.com/cilium/cilium/blob/170284219ff62bf5dc1aac6203fb705310fdf38b/pkg/datapath/loader/base.go#L345-L349

Then, when the `TUNNEL_MODE` arg is passed to `bpf/init.sh` we end up defining `ENCAP_IFINDEX` in the datapath:

https://github.com/cilium/cilium/blob/170284219ff62bf5dc1aac6203fb705310fdf38b/bpf/init.sh#L430-L447

**Comment by jibi** [comment]
@thanhlong9x could you share the `helm` or `cilium` command you are using to deploy Cilium, together with some more info on the environment you are running it on?

**Comment by thanhlong9x** [comment]
Hi @jibi, As I said above, I am testing cilium cni version 1.13.0 on Kubernetes version 1.26.1 and OS is ubuntu 20.10 (kernel 5.8.0-63-generic). Since my test environment is private, I use "helm template" to generate yaml file before installation. Here is the command I use: 
helm template cilium cilium/cilium --version 1.13.0 \
--namespace kube-system \
--set operator.replicas=1 \
--set nodeinit.enabled=true \
--set nodeinit.restartPods=true \
--set externalIPs.enabled=true \
--set nodePort.enabled=true \
--set hostPort.enabled=true \
--set tunnel=disabled \
--set bpf.masquerade=true \
--set bpf.clockProbe=true \
--set bpf.waitForMount=true \
--set bpf.preallocateMaps=true \
--set bpf.tproxy=true \
--set bpf.hostRouting=true \
--set autoDirectNodeRoutes=true \
--set localRedirectPolicy=true \
--set enableCiliumEndpointSlice=true \
--set enableK8sEventHandover=true \
--set enableK8sEndpointSlice=true \
--set wellKnownIdentities.enabled=true \
--set sockops.enabled=true \
--set ipam.operator.clusterPoolIPv4PodCIDRList=10.244.0.0/16 \
--set ipv4NativeRoutingCIDR=10.244.0.0/16 \
--set nodePort.directRoutingDevice=eth0 \
--set devices=eth0 \
--set bandwidthManager.enable=true \
--set bandwidthManager.bbr=true \
--set hubble.enabled=true \
--set hubble.relay.enabled=true \
--set hubble.ui.enabled=true \
--set installNoConntrackIptablesRules=true \
--set egressGateway.enabled=true \
--set endpointRoutes.enabled=true \
--set pullPolicy=IfNotPresent \
--set kubeProxyReplacement=strict \
--set loadBalancer.algorithm=maglev \
--set loadBalancer.mode=dsr \
--set hostServices.enabled=true \
--set k8sServiceHost=172.20.2.111 \
--set k8sServicePort=6443

**Comment by jibi** [comment]
Seems like the culprit is enabling `--enable-ipv4-egress-gateway` together with `--sockops-enable`:
```
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=error msg="Failed to compile bpf_sockops.o: exit status 1" compiler-pid=64501 linker-pid=64502 subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="In file included from /var/lib/cilium/bpf/sockops/bpf_sockops.c:16:" subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="In file included from /var/lib/cilium/bpf/sockops/../lib/common.h:1095:" subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="In file included from /var/lib/cilium/bpf/lib/overloadable.h:11:" subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="/var/lib/cilium/bpf/lib/overloadable_skb.h:201:13: error: use of undeclared identifier 'ENCAP_IFINDEX'; did you mean 'CB_IFINDEX'?" subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="        *ifindex = ENCAP_IFINDEX;" subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="                   ^~~~~~~~~~~~~" subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="                   CB_IFINDEX" subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="/var/lib/cilium/bpf/sockops/../lib/common.h:696:2: note: 'CB_IFINDEX' declared here" subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="        CB_IFINDEX," subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="        ^" subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=warning msg="1 error generated." subsys=datapath-loader
Mar 02 11:33:39 k8s1 cilium-agent[64462]: level=error msg="Start hook failed" error="daemon creation failed: error while initializing daemon: failed to enable Sockmap: failed compile sockops/bpf_sockops.c: Failed to compile bpf_sockops.o: exit status 1" function="cmd.newDaemonPromise.func1 (daemon_main.go:1676)" subsys=hive
```

**Comment by joestringer** [comment]
I would suggest disabling sockops. We've deprecated that feature, and if we want it to work properly then developers in the Cilium community need to come together and make it work with the various other features.
