### ISSUE TITLE
Cilium as sdn for qemu/kvm machines

### ISSUE THREAD

**Issue by vtolstov** [cilium/cilium#24129]
does it possible to use Cilium to provide virtual network between qemu vm?
I know about kubernetes cni driver, but as i understand if i'm use Cilium on baremetal linux host with qemu all features the same.
Where i can find relevant info or some suggestions?

**Comment by YutaroHayakawa** [comment]
Cilium is very kubernetes-centric software at this point, but for example, with [kube-virt](https://docs.cilium.io/en/v1.13/network/kubernetes/kubeproxy-free/#socket-loadbalancer-bypass-in-pod-namespace), you may be able to run Cilium on top of it. There is [a small tip like this](https://docs.cilium.io/en/v1.13/network/kubernetes/kubeproxy-free/#socket-loadbalancer-bypass-in-pod-namespace) to run Cilium with VM isolation and it mentions kube-virt.

**Comment by vtolstov** [comment]
@YutaroHayakawa thank you, i think that cilium can work without kubernetes and fully controlled by rest api (and policy rules)
