### ISSUE TITLE
does cilium has default ratelimit ，containerd image pull speed from 1.7m/s slow down to 30k/s,continually

### ISSUE THREAD

**Issue by 13567436138** [cilium/cilium#24130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!does cilium has default ratelimit ，containerd image pull speed from 1.7m/s slow down to 30k/s,continually
![22384ded46b4dd9ca30ea274fc21676](https://user-images.githubusercontent.com/31508490/222342252-e2177438-4517-4bb9-8e7a-8675d414325c.png)

### Cilium Version

1.13

### Kernel Version

1.19

### Kubernetes Version

1.26.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YutaroHayakawa** [comment]
What made you think that's an issue of the Cilium? Could you elaborate more?

**Comment by 13567436138** [comment]
guess
