### ISSUE TITLE
Expose `bpf-lb-sock-hostns-only` in cilium status

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#24160]
Here is the description for the flag - `Skip socket LB for services when inside a pod namespace, in favor of service LB at the pod interface. Socket LB is still used when in the host namespace. Required by service mesh (e.g., Istio, Linkerd)`. 

This needs to be exposed as part of the `KubeProxyReplacement` section in `cilium status --verbose`:

```
KubeProxyReplacement Details:
  Status:                 Disabled
  Socket LB:              Disabled
  Socket LB Tracing:      Disabled
  Session Affinity:       Disabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Disabled
  - LoadBalancer:   Disabled
  - externalIPs:    Disabled
  - HostPort:       Disabled
```

Here is the link to the related code - https://github.com/cilium/cilium/blob/master/pkg/client/client.go#L631.

**Comment by romanspb80** [comment]
Can I kindly ask to assign this task to me?
