### ISSUE TITLE
Modularization: ipcache

### ISSUE THREAD

**Issue by joamaki** [cilium/cilium#24178]
Refactor ipcache into a control-plane and datapath cells. This is currently a collection of thoughts on how to go about it.

### Handle-pattern instead of K8sCachesSynced

IPcache depends on knowing when the k8s stores have finished with synchronization with api server (initial listing). This is done for a couple of reasons:
- Trigger reconciliation/garbage collection of the BPF maps which may contain old stale state.
- Generate full output ipcache entries based on a combination of incoming state from different Resources.

Since we may also get identities via kvstore, this abstraction doesn't actually work. Instead, consider a "handle"-based pattern:

```
type IPCache interface {
  NewHandle(source string) Handle
}

type Handle interface {
  Close()
  Synchronized()
  UpsertMetadata(prefix netip.Prefix, src source.Source, resource ipcacheTypes.ResourceID, aux ...IPMetadata)
  RemoveMetadata(prefix netip.Prefix, resource ipcacheTypes.ResourceID, aux ...IPMetadata)
  // ...
}
```

Here each cell that wants to manage ipcache entries will ask for a handle and mark it as synchronized once its initial Upsert() calls have finished. When all handles have marked themselves as Synchronized() IPcache can start reconciling.

### stream.Observable[IPCacheEvent]

Instead of hand-written support for listeners, expose a stream of IPCache events with the `Observable` type and implement it using `stream.Multicast()`.

### IPCache datapath

The datapath-side of IPCache is roughly implemented in `pkg/datapath/ipcache`, `daemon/cmd/datapath.go` and `pkg/maps/ipcache`. These should be unified into one cell that would on start initialize the ipcachemap and would handle the events from control-plane.

To keep dependency direction one-way, control-plane should do the `ipcache.Observe()` to register the datapath handlers.
`DumpToListener` (and the public mutex!) should be removed and instead `Observe()` should be called prior to start to guarantee that no events are missed.

### API handlers

Once https://github.com/cilium/cilium/pull/24016 has been merged, implement the "GetIPHandler" in `pkg/ipcache`. This removes the other need for `DumpToListener`.

### Testing

Integration tests for each handler (k8s, kvstore, ...) + ipcache (control-plane).
Test for GetIPHandler.
Privileged integration test for ipcache (control-plane) + ipcache (datapath).

Related: #23425

**Comment by joamaki** [comment]
cc: @joestringer

**Comment by joestringer** [comment]
I briefly looked into the "datapath" side of this and I identified a few different 'listeners' to userspace IPCache state that would all make sense as event handlers for events from the control-plane:
1. BPF Datapath (including `pkg/datapath/ipcache`, `daemon/cmd/datapath.go` and `pkg/maps/ipcache`)
2. Proxy / Envoy (including `pkg/proxy/epinfo.go` and maybe some references in `pkg/envoy/resources.go`).
3. WireGuard - `pkg/wireguard/agent/agent.go`
