### ISSUE TITLE
Support arm64 cilium/json-mock

### ISSUE THREAD

**Issue by kahirokunn** [cilium/cilium#24170]
## Cilium Feature Proposal
        
Because cilium/json-mock does not support arm64, I get an error with the following yaml in my environment.

`exec /bin/bash: exec format error`

What about changing the cilium/json-mock image to a multi-arch image?

**Comment by sayboras** [comment]
can you use the latest tag (e.g. v1.3.3) instead ? From v1.3.0, arm build is supported.

**Comment by kahirokunn** [comment]
Thx!
