### ISSUE TITLE
L7 LB: use ifindex of originating pod for FIB lookup

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#24196]
Discussed with @jrajahalme that as follow-on improvement to https://github.com/cilium/cilium/pull/24182, we should use the pod's ifindex (and not `cilium_host`'s ifindex) for the FIB lookup.

**Comment by brb** [comment]
Any TL;DR why pod's ifindex instead?

**Comment by julianwiedmann** [comment]
Essentially "we want this to look as if it's originating from the pod, the L7 LB aspect should be transparent". The initial behaviour was just an accident / unawareness of `skb->ifindex` having an impact on the datapath.

Let's hope we don't find any/too many other skb fields that need to be reflected ...
