### ISSUE TITLE
Expand k8s-upstream-tests to validate KPR

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#24199]
The following test script runs the kubernetes upstream tests against Cilium:

https://github.com/cilium/cilium/blob/master/test/kubernetes-test.sh#L11

These tests can be initiated with a `/test-upstream-k8s` command as a comment against a PR. Currently this appears to rely on an existing kube-proxy deployment and runs Cilium on top. This allows us to validate whether there is a mode where Cilium satisfies the upstream conformance tests (with upstream kube-proxy), but we do not get feedback about the conformance status with Cilium without kube-proxy.

This issue tracks adding CI support for Cilium with KPR.

**Comment by brb** [comment]
Thanks for the issue. Is it just KPR=on|off, or you want to test other Cilium configurations?

**Comment by joestringer** [comment]
@brb A large chunk of the upstream k8s tests validate Service functionality, and our users use a mix of kube-proxy or kube-proxy replacement. The idea behind this request is to help to identify regressions in conformance over time as we make changes to either of these modes. So KPR=on|off is probably enough. I would also settle for periodic (1/day? 1/week?) runs for one of the combinations as long as we have people watching the results.
