### ISSUE TITLE
CFP: QoS for network

### ISSUE THREAD

**Issue by ernado** [cilium/cilium#24194]
## Cilium Feature Proposal

**Describe the feature you'd like**

Support annotations like `network.cilium.io/qos` with values `top`, `low` that will specify network priority for
annotated pod, that will determine how much NIC queues will be allocated for this kind of network workload.

For example, NIC has N queues, workload with top priority will be scheduled on M of them, and workload with low priority
will use K queues, where M+K=N, and M:K=k.

E.g. N=100, M=80, K=20, M:K=8:2.

**(Optional) Describe your proposed solution**

### Mark packets with `skb->priority`

Set up a BPF endpoint->priority map by using provided labels.

Aggregate egress packets in the `bpf_host` program by endpoint and set the `skb->priority` field.

```c
	info = map_lookup_elem(&PRIORITY_MAP, &aggregate);
	if (!info)
		return CTX_ACT_OK;

	ctx->priority = info.priority;
	return CTX_ACT_OK;
```

### Setup queues

The proposed solution is to map priority to corresponding traffic class by using `mqprio` queueing discipline.

```mermaid
flowchart LR
    C1[Container 1, top priority]:::topclass --> bpf_lxc1 --> |Set aggregate id|marktop
    C2[Container 2, top priority]:::topclass --> bpf_lxc2 --> |Set aggregate id|marktop
    C3[Container 3, low priority]:::lowclass --> bpf_lxc3 --> |Set aggregate id|marklow
    C4[Container 4, low priority]:::lowclass --> bpf_lxc4 --> |Set aggregate id|marklow
    C5[Container 5, low priority]:::lowclass --> bpf_lxc5 --> |Set aggregate id|marklow
    C6[Container 6, low priority]:::lowclass --> bpf_lxc6 --> |Set aggregate id|marklow

    subgraph bpf_lxc
        bpf_lxc1
        bpf_lxc2
        bpf_lxc3
        bpf_lxc4
        bpf_lxc5
        bpf_lxc6
    end

    subgraph bpf_host
        marktop[Set priority to TC_PRIO_MAX = 15]
        marklow[Set priority to TC_PRIO_INTERACTIVE = 6]
    end

    marktop --> TCTop
    marklow --> TCLow

    subgraph mqprio
        TCTop[`Top` traffic class]
        TCLow[`Low` traffic class]
        TCTop --> Queue0:::topclass
        TCTop --> Queue1:::topclass
        TCTop --> Queue2:::topclass
        TCTop --> Queue3:::topclass
        TCTop --> Queue4:::topclass
        TCTop --> Queue5:::topclass
        TCTop --> Queue6:::topclass
        TCTop --> Queue7:::topclass
        TCLow --> Queue8:::lowclass
        TCLow --> Queue9:::lowclass
    end

    Queue0 --> TxQueue0
    Queue1 --> TxQueue1
    Queue2 --> TxQueue2
    Queue3 --> TxQueue3
    Queue4 --> TxQueue4
    Queue5 --> TxQueue5
    Queue6 --> TxQueue6
    Queue7 --> TxQueue7
    Queue8 --> TxQueue8
    Queue9 --> TxQueue9

    subgraph tx queue
        TxQueue0:::txtopclass
        TxQueue1:::txtopclass
        TxQueue2:::txtopclass
        TxQueue3:::txtopclass
        TxQueue4:::txtopclass
        TxQueue5:::txtopclass
        TxQueue6:::txtopclass
        TxQueue7:::txtopclass
        TxQueue8:::txlowclass
        TxQueue9:::txlowclass
    end
    
    classDef topclass fill:green
    classDef txtopclass fill:green
    classDef lowclass fill:red
    classDef txlowclass fill:red
```

#### Notes

Cilium uses [vishvananda/netlink](https://github.com/vishvananda/netlink) for queue setup, that can't setup `mqprio` (
needed for priority packets) nor `dsmark` (needed for QoS (DSCP) in IP header).

Probably this functionality should be added to this package.

**Comment by ernado** [comment]
CC: @tdakkota

**Comment by ernado** [comment]
This is still relevant.

**Comment by borkmann** [comment]
> This is still relevant.

Agree, currently looking into this for adding support. Once I have a non-draft PR, would you be open to test?

**Comment by ernado** [comment]
@borkmann great, of course!

**Comment by shengslin** [comment]
This feature is useful for the mixed deployment of online business and offline business, and I hope it can be integrated as soon as possible

**Comment by borkmann** [comment]
> This feature is useful for the mixed deployment of online business and offline business, and I hope it can be integrated as soon as possible

Agree, this is still the plan, just that 1.14 feature freeze is this week where it's unlikely to ship till then.

**Comment by shengslin** [comment]
@borkmann 
I've been looking at this feature, but it seems like there's been no progress. why?

**Comment by ernado** [comment]
I think that primary reason is preparing 1.14 release.

This feature did not land to 1.14, so it is reasonable to wait until new development cycle.
Will be awesome to see this feature in 1.15, we are still interested and test it as soon as pull request is available.

**Comment by koalo** [comment]
This is very similar to what I am looking for to restrict the access of containers to certain TAPRIO timeslots. However, in my scenario it would be good to also allow a single container to send packets with a certain set of priorities.

So for example:
Container 1 and 2: Send everything with priority 6 (overwrite priority of the packet/socket as in the current pull request)
Container 3 and 4: Allowed to send with priority 3 or 6 (depending on priority of the packet/socket), but block all other traffic

This might or might not be feasible to implement already in the first step, but I would be good to at least take this scenario into account for the configuration to avoid making it more difficult to implement in the future.

I am happy to support with testing and/or implementation!

**Comment by koalo** [comment]
Also very helpful would be to assign the priority based on the contents of the packet header.

For example:
For container 5 and destination address 10.0.0.3 use priority 3.
For container 5 and destination address 10.0.0.4 use priority 2.
For container 3 always use priority 1.

**Comment by ernado** [comment]
This is still relevant :)

**Comment by timbuchwaldt** [comment]
Very relevant for us as well. We would look into adding the featureset we care about if wanted. Basically this would include a mapping of pod-labels to DSCP headers in the IP packets originating from the pod. We care about that for hardware-level QoS in an on-prem scenario. 

An even more optimal implementation could include a way of selecting traffic via CNPs to make matching more granular than on a per-port level (e.g. to differentiate monitoring-traffic from application-traffic)
