### ISSUE TITLE
Deprecate custom Cilium Istioctl

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#24204]
Some time ago, the Cilium community created a fork of `istioctl` at https://github.com/cilium/istio , which simplified the installation experience in order to configure Istio + Cilium in order to implement a combination of features from both. Specifically, Cilium brought [API-Aware Network Policy](https://docs.cilium.io/en/v1.13/gettingstarted/demo/#apply-and-test-http-aware-l7-policy) at L7 to the Istio Service Mesh functionality.

For some time, it has been difficult to keep this up to date, and not many users have shown interest in using this tooling. In the mean time, [more and more Service Mesh functionality has been added to Cilium itself](https://www.cncf.io/blog/2022/07/20/cilium-1-12-ga-cilium-service-mesh-and-other-major-new-features-for-enterprise-kubernetes/), which should unlock similar use cases without needing to deploy Istio in addition to Cilium for such functionality.

This issue proposes to deprecate and remove the istioctl fork. This would also likely need some reworking of the docs around how to combine Cilium with Istio, since the L7 filtering functionality would no longer be supported. It may also allow us to re-evaluate some of the complicated Istio integration tests that we have in the tree and simplify them to increase reliability of those tests.

**Comment by nathandorsey** [comment]
How does one migrate from this process? I installed Istio using Cilium's fork of `istioctl`. I am sitting on version `1.10.6` of Istio. The only notes I could find state the change dealt with switching to Cilium's images for proxy and pilot.
https://github.com/isovalent/istio/releases/tag/1.9.6
