### ISSUE TITLE
InstallNoTrackRules creates asymmetric iptables rules in CILIUM_PRE_raw

### ISSUE THREAD

**Issue by akhilles** [cilium/cilium#24229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a pod with the "policy.cilium.io/no-track-port" annotation is created, the following iptables rules are created:

```
-A CILIUM_PRE_raw -d <pod ip>/32 -p tcp -m tcp --dport <port> -j CT --notrack
-A CILIUM_PRE_raw -d <pod ip>/32 -p udp -m udp --dport <port> -j CT --notrack
```

This only skips connection tracking for ingress traffic. Egress traffic is subject to connection tracking and results in entries with `[UNREPLIED]` flat set. This was verified using `conntrack -L`.

The following rules are also expected to be created so that connection tracking is bypassed correctly:

```
-A CILIUM_PRE_raw -s <pod ip>/32 -p tcp -m tcp --sport <port> -j CT --notrack
-A CILIUM_PRE_raw -s <pod ip>/32 -p udp -m udp --sport <port> -j CT --notrack
```

### Cilium Version

1.12.7

### Kernel Version

5.15.65

### Kubernetes Version

1.25

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Weil0ng** [comment]
This doesn't break the connection but leaving some trash entries in the kernel conntrack table.

It is causing problems if kernel conntrack is under pressure, working on a fix.

**Comment by akhilles** [comment]
@aditighag would https://github.com/cilium/cilium/pull/24230 be a candidate for backporting to 1.13? The main symptom is conntrack filling up with `[UNREPLIED]` entries which can be problematic under load.
