### ISSUE TITLE
Add `encrypt-node` status to `cilium status`

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#24239]
PR https://github.com/cilium/cilium/pull/19401 added support for node encryption to WireGuard transparent encryption. There is currently no command to quickly validate if node encryption has been enabled or not. Therefore, this issue proposes to add the value of the `EncryptNode` config field to the `cilium status` output.

Current output:
```console
$ cilium status 
[...]
Encryption:   Wireguard [cilium_wg0 (Pubkey: UzRSJUmRqsxl82xvFG0joBheaiqOnM3BCgpByYjVtCE=, Port: 51871, Peers: 3)]
```

Proposed output:
```console
$ cilium status 
[...]
Encryption:   Wireguard [NodeEncryption: Enabled, cilium_wg0 (Pubkey: UzRSJUmRqsxl82xvFG0joBheaiqOnM3BCgpByYjVtCE=, Port: 51871, Peers: 3)]
```

Where as the possible values for `NodeEncryption` would be `Enabled`, `Disabled` and `OptedOut` (based on `node.GetOptOutNodeEncryption()`.

To implement this, I'd recommend to extend the `WireguardStatus model here: https://github.com/cilium/cilium/blob/02ef3417903e5acbd0d8cddd7ef3248bc366569e/api/v1/openapi.yaml#L3380-L3385

**Comment by romanspb80** [comment]
Can I kindly ask to assign this task to me?

**Comment by gandro** [comment]
> Can I kindly ask to assign this task to me?

Done!
