### ISSUE TITLE
cilium agent uses 13+ cores for single traffic flow 

### ISSUE THREAD

**Issue by koolipaasha** [cilium/cilium#24243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

using wrk(https://github.com/wg/wrk) to send 10k HTTP requests to a target webserver pod.But the CPU usage of cilium agent is crossing 13 cores+ for certian traffic pattern. 

CPU usage of cilium-agent is crossing 13+ cores when the source of traffic is worker node(**cilium_host**) .For the same traffic between the pods its less than 1 core.

**Environment:**
Two worker nodes ,k8s 1.26,Cilium 1.12.6,no kube-proxy

**Traffic Pattern:**
Worker node1- Hosting "wrk" as a pod and also has  "wrk" as  a binary file.
Worker node2- Hosting target HTTP pod

 **command used**
Same command for generating traffic from both pod and worker:  
`wrk -t4 -c10000 -d18s http://10.0.1.12 [pod ip]`

CPU usage when traffic is send from pod(worker1-wrk) to pod(worker2):
**~1 core**

CPU usage when traffic is send from worker1(using wrk binary file using cilium_host interface ) to pod (worker2) :
**~13 cores**

from worker1:

```
 ip route get 10.0.1.12
10.0.1.12 dev cilium_host src 10.0.0.54 uid 0
    cache mtu 1450
[cpu_profile1035268235.zip](https://github.com/cilium/cilium/files/11032720/cpu_profile1035268235.zip)



```
```
Tasks: 1271 total,   1 running, 1270 sleeping,   0 stopped,   0 zombie
%Cpu(s): 10.3 us,  2.1 sy,  0.0 ni, 85.4 id,  0.0 wa,  0.0 hi,  2.1 si,  0.0 st
MiB Mem : 1029692.+total, 392188.5 free, 625446.1 used,  12058.1 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used. 398187.7 avail Mem
 PID       USER      PR  NI    VIRT        RES       SHR     S     %CPU  %MEM     TIME+ COMMAND
 641129   root      20   0    914016   163452   81088 S            1351   0.0      53:53.77 cilium-agent
```

### Cilium Version

1.12.6

### Kernel Version

 5.15.0-33-generic 

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230308-124037.zip](https://github.com/cilium/cilium/files/10920847/cilium-sysdump-20230308-124037.zip)

### Anything else?

[cilium-bugtool-20230308-123849.225+0000-UTC-2575061365.zip](https://github.com/cilium/cilium/files/10920879/cilium-bugtool-20230308-123849.225%2B0000-UTC-2575061365.zip)

[perf.data.tar.gz](https://github.com/cilium/cilium/files/11032671/perf.data.tar.gz)

[cpu_profile1035268235.zip](https://github.com/cilium/cilium/files/11032737/cpu_profile1035268235.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jtaleric** [comment]
Do you have / or could you get a `perf record -ag -F 99 -- sleep 30` during the workload on the system the agent is experiencing this? a pprof also might be helpful of the cilium agent.

**Comment by koolipaasha** [comment]
Thanks @jtaleric for your reply.I have attached the files.This time CPU usage was between 8 and 11 cores.

Worker1:
perf record -ag -F 99 -- sleep 30 --- > perf.data.tar.gz

worker 1(cilium-agent)
 gops pprof-cpu 1 ---> cpu_profile1035268235.zip

**Comment by marseel** [comment]
It seems like it's related to hubble events - could you try to run test again with hubble disabled to confirm it?

There is a bunch of logs:
```
level=info msg="hubble events queue is processing messages again: 2 messages were lost" subsys=hubble
```
Also, it's visible in pprof I think under `observer.(*LocalObserverServer).Start`

**Comment by learnitall** [comment]
Additionally, the profile from gops lists 74% of the samples as `runtime.gcBgMarkWorker`, which is pretty high. Looks like go is doing a ton of garbage collection and that we have an issue with excess memory allocations. If possible, it would also be really helpful to have a `gops pprof-heap` run.

**Comment by koolipaasha** [comment]
@marseel @learnitall Thanks for your comments.I no longer see the issue on 6.1.8 kernel,i can still collect the metrics? i can see that on 5.4 kernel,CPU  utilization is 4 CPUs and on 6.1.x its 0.2 cpu for the same traffic.
