### ISSUE TITLE
CFP:  support bgp peer graceful restart feature in control-plane

### ISSUE THREAD

**Issue by yanhongchang** [cilium/cilium#24256]
## Cilium Feature Proposal
        
env：
k8s version: 1.24.11
cilium version: 1.13.0
kernel: 5.10 

install with --enable-bgp-control-plane=true

**Is your feature request related to a problem?**
Yes

If so, please describe the problem

the bgp peer will reconnection when cilium-agent restart or rebuild，and this will make the ping down for about 10s+.this is Unacceptable in online.

![image](https://user-images.githubusercontent.com/10663031/223899342-9b3c12c1-8b0c-404a-bd6b-bd8170208f17.png)

I known the bird support graceful restart feature，this may very friendly for this case

**Describe the feature you'd like**

control-plane can support graceful restart，it will not ping down when restart or re-create cilium-agent.

**Comment by YutaroHayakawa** [comment]
This should be resolved in https://github.com/cilium/cilium/pull/25660
