### ISSUE TITLE
Cilium not respecting routes in different routing tables

### ISSUE THREAD

**Issue by kvaps** [cilium/cilium#24252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Pod-to-pod communication is not working in case when routes are located in different routing tables

working case:
```
ip route add 10.10.10.1/32 via 192.168.100.1 dev enp1s0
```

non-working case:
```
ip rule add to 10.10.10.0/24 lookup 1490
ip route add 10.10.10.1/32 via 192.168.100.1 dev enp1s0 table 1490
```

### Cilium Version

1.11.14

### Kernel Version

5.15.0-25-generic

### Kubernetes Version

v1.23.15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kvaps** [comment]
I found out that bpf_redirect not respecting other routing tables. If I set`enable-host-legacy-routing: true` everything is start working as it should.

**Comment by kvaps** [comment]
Somthing is going wrong here, if I remove these lines, everything is start to work
https://github.com/cilium/cilium/blob/85615c16eea57e2004e0593d42cf5e39bfd107d1/bpf/bpf_lxc.c#L406-L407

I also tried to undefine `ENABLE_SKIP_FIB`, unfortunately without any effect

@borkmann could you please comment on this?

**Comment by borkmann** [comment]
@kvaps could you test with PR https://github.com/cilium/cilium/pull/24271 ? Thanks Andrei!
