### ISSUE TITLE
Update OpenShift documentation

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#24270]
clarify that cilium organization does not maintain cilium-olm repository (ref https://github.com/cilium/cilium-olm/pull/107). vendors that do maintain OLM for cilium can add their specific instructions in this page:

https://docs.cilium.io/en/v1.13/installation/k8s-install-openshift-okd/

**Comment by learnitall** [comment]
I talked with @joestringer, @xmulligan and @saintdle last week about this a little bit and we were thinking of modifying the OpenShift documentation to point to the RedHat OLM marketplace, where vendors can publish the OLM images they maintain for installing Cilium and provide installation instructions.

I think it would make sense to also move the installation instructions for the deprecated [cilium/cilium-olm](github.com/cilium/cilium-olm) repo that's currently in the docs to the [isovalent/olm-for-cilium](github.com/isovalent/olm-for-cilium) repository.

cc @jtaleric @egrosdou01

**Comment by learnitall** [comment]
Alright I've created two PRs:

* https://github.com/isovalent/olm-for-cilium/pull/48
* https://github.com/cilium/cilium/pull/29300

Feedback is much appreciated, thanks!

**Comment by fgiloux** [comment]
I think that there is value for the community to maintain an installation of Cilium on OpenShift and publish it to the [Red Hat community catalogue](https://github.com/redhat-openshift-ecosystem/community-operators-prod). I am not following the rational for moving cilium/cilium-olm to isovalent/olm-for-cilium

**Comment by egrosdou01** [comment]
+1 @fgiloux It will be easier for engineers who work with the exact setup.

**Comment by joestringer** [comment]
I merged the PR earlier based on the understanding that the existing instructions were broken and outdated and hence that PR is better than leaving the instructions, but I did not intend that to be any sort of statement about the path forward. I'd welcome any suggestions on how we can better manage our relationship with the downstream OpenShift project and ensure widespread availability of Cilium on common platforms.
