### ISSUE TITLE
CI: automatically report ci-datapath configuration

### ISSUE THREAD

**Issue by brb** [cilium/cilium#24298]
Currently, the `conformance-e2e.yaml` and `conformance-ipsec-e2e.yaml` Github Action configuration matrices are manually constructed - https://github.com/cilium/cilium/issues/20606.

To prevent the table from becoming stale or false, we could automatically derive the configuration table after each run. The idea is to store a result of `cilium status` - https://github.com/cilium/cilium/blob/4ff7c8934c485b810fbe50acce2b8d0f7e7b5eac/.github/workflows/conformance-datapath.yaml#L386 for each job, and then parse it the end once all jobs have completed.

**Comment by Kanika637** [comment]
I want to work on this issue, can you guide me a little @brb ?

**Comment by brb** [comment]
@Kanika637 Thanks, sure!

**Comment by Kanika637** [comment]
Actually I am in a middle of something, will surely get back to this issue
ASAP.

**Comment by Saimurugeshwari** [comment]
can i work on this issue

**Comment by brb** [comment]
@Kanika637 Are you still on the issue?

**Comment by Kanika637** [comment]
No, I will make it unassigned to me.

**Comment by brb** [comment]
@Saimurugeshwari Are you still interested in working on this issue?

**Comment by SD-13** [comment]
Hey @brb I am trying to understand this issue. I took a quick look and didn't find any yaml file called `conformance-datapath.yaml` in workflows. Am I missing something?

**Comment by brb** [comment]
Hi @SD-13, the file got split and renamed to conformance-e2e.yaml and conformance-ipsec-e2e.yaml.
