### ISSUE TITLE
Sudden Increase In Dropped Egress Packets

### ISSUE THREAD

**Issue by arjunsalyan** [cilium/cilium#24305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We run multiple EKS clusters in the same VPC. Our cilium status looks like:

```
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.22+ (v1.22.16-eks-ffeb93d) [linux/amd64]
Kubernetes APIs:         ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [ens5 <NODE_IP> (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.12.7 (v1.12.7-6719063)
NodeMonitor:             Listening for events on 16 CPUs with 64x4096 of shared memory
IPAM:                    IPv4: 8/16 allocated, 
ClusterMesh:             1/1 clusters ready, 66 global-services
BandwidthManager:        EDT with BPF [CUBIC] [ens5]
Host Routing:            Legacy
Masquerading:            BPF   [ens5]   172.31.0.0/16 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       55/55 healthy
Proxy Status:            OK, ip 100.64.92.50, 0 redirects active on ports 10000-20000
Global Identity Range:   min 256, max 65535
Hubble:                  Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 575.16   Metrics: Ok
```

We run a NodePort services and mount them as Targets to ALB. The system had been running fine many months now, but then suddenly we started seeing target connection errors in the ALB. After some debugging we realised that our NodePort service is intermittently not giving a response and times out. And looking at the cilium metrics we could seen an increase in the dropped packets due to `FIB lookup failed`.

Restarting cilium fixes the issues for a few hours but then the issue resurfaces. We then ran `cilium monitor --type drop` on one of the nodes which was timing out when the nodeport service on it was being called (the pods have listen on port 8080)

```
xx drop (FIB lookup failed, 7) flow 0xa7eb68ef to endpoint 0, file bpf_host.c line 1604, , identity unknown->unknown: 100.64.50.240:35713 -> 100.64.52.236:8080 tcp SYN
xx drop (Service backend not found) flow 0x81a2fdfd to endpoint 0, file bpf_host.c line 665, , identity world->unknown: 172.31.57.118:34752 -> 100.64.50.240:30680 tcp SYN
xx drop (Service backend not found) flow 0x81a2fdfd to endpoint 0, file bpf_host.c line 665, , identity world->unknown: 172.31.57.118:34752 -> 100.64.50.240:30680 tcp SYN
xx drop (FIB lookup failed, 7) flow 0x3e4322cc to endpoint 0, file bpf_host.c line 1604, , identity unknown->unknown: 100.64.50.240:58091 -> 100.64.52.247:8080 tcp SYN
xx drop (FIB lookup failed, 7) flow 0x24953975 to endpoint 0, file bpf_host.c line 1604, , identity unknown->unknown: 100.64.50.240:51604 -> 100.64.52.236:8080 tcp SYN
xx drop (FIB lookup failed, 7) flow 0xf9c50c87 to endpoint 0, file bpf_host.c line 1604, , identity unknown->unknown: 100.64.50.240:34968 -> 100.64.52.247:8080 tcp SYN
xx drop (FIB lookup failed, 7) flow 0xf9c50c87 to endpoint 0, file bpf_host.c line 1604, , identity unknown->unknown: 100.64.50.240:34968 -> 100.64.52.247:8080 tcp SYN
```

We then looked at https://github.com/cilium/cilium/issues/15200 and we can confirm that node (`100.64.50.240`) and the three pods (100.64.52.236,100.64.50.240,100.64.52.247) for which the lookup is failing are in the same AZ. Then we ran `ip route get POD_IP` in the same node

```
$ ip route get 100.64.52.247
100.64.52.247 dev ens5 src 100.64.50.240 uid 0
    cache
$ ip route get 100.64.52.236
100.64.52.236 dev ens5 src 100.64.50.240 uid 0
    cache
```

As mentioned here pinging the POD_IP from the node fixes the issue momentarily in less than a minute, the issues appear again. But there are few pods in the same AZ which are not appearing in the `FIB lookup failed` error and for which the output of `FIB lookup failed` is like this

```
$ ip route get 100.64.92.31
100.64.92.31 via 100.64.48.1 dev ens5 src 100.64.50.240 uid 0
    cache
```

I did not reopen the same issue because I feel this error is different in a few ways:
- It appeared suddenly on a very stable system and there have been no upgrades/changes across the entire AWS account
- Not all pods of the same AZ are failing the lookup
- This timing out is intermittent and not all requests to the nodeport service fail even on the same pod

### Cilium Version

1.12.7 (we updated from 1.12.1 in an attempt to fix the issue, but it did not help)

### Kernel Version

5.15.0-1019-aws

### Kubernetes Version

v1.22.16-eks-ffeb93d

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
@arjunsalyan interesting, thank you for the report. Can you capture a sysdump on a node experiencing the issue?
