### ISSUE TITLE
Tunnel mode lowers throughput by a large amount

### ISSUE THREAD

**Issue by michaelasp** [cilium/cilium#24306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using cilium with tunnel mode enabled, throughput drops by a significant amount(30-50%). This was seen in #22898 with the attached logs. This bug is an extension of that to discuss matters related specifically to that.

### Cilium Version

1.12.3

### Kernel Version

5.4.0-42-generic

### Kubernetes Version

1.26

### Sysdump

Couldn't get it

### Anything else?

From other issue

1) tunnel: disabled, mtu: 1450  [logs](https://gist.github.com/michaelasp/3883c8fdfd298ad192a80f6a1db13262) ~8.24gb/s
2) tunnel: vxlan [logs](https://gist.github.com/michaelasp/1081274981900abfbfefdcccd6f52a68) ~5.8 Gb/s, 30% drop
3) tunnel: geneve [logs](https://gist.github.com/michaelasp/542ba5bfb0e325be2bb16585167e7314)   ~5.2 Gb/s 37% drop

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
As mentioned in the original issue, this may be caused by a kernel bug fixed by https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=89e5c58fc1e2857ccdaae506fb8bc5fed57ee063. IIRC, that fix was backported to LTS releases, so it would be good to know if your kernel includes it.

**Comment by michaelasp** [comment]
Hi @pchaigno, just took a look at the kernel source for Ubuntu here https://wiki.ubuntu.com/Kernel/SourceCode and it doesn't seem like that patch was added until 5.13 for Ubuntu LTS which was the OS I was using for my cluster.

**Comment by pchaigno** [comment]
That's correct. Your specific patch release doesn't have it because it's too old. I would suggest to upgrade to 5.4.0-145-generic, which does have the fix. Any kernel after and including 5.4.0-73 has it.
```
$ git checkout Ubuntu-5.4.0-145.162 
Updating files: 100% (7104/7104), done.
Previous HEAD position was 7cb08860ffd3 UBUNTU: Ubuntu-5.4.0-72.80
HEAD is now at f6af0157ac99 UBUNTU: Ubuntu-5.4.0-145.162
$ git log | grep "net: Fix gro aggregation for udp encaps with zero csum"
    net: Fix gro aggregation for udp encaps with zero csum
```

**Comment by jingai-db** [comment]
> As mentioned in the original issue, this may be caused by a kernel bug fixed by https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=89e5c58fc1e2857ccdaae506fb8bc5fed57ee063. IIRC, that fix was backported to LTS releases, so it would be good to know if your kernel includes it.

https://launchpad.net/ubuntu/+source/linux-aws/4.4.0-1125.139

Does the above patch already ship with `4.4.0`? We use `4.15` kernel and observed the throughput dip due to VxLAN.

**Comment by pchaigno** [comment]
You would need to check yourself. I don't know the answer for those kernel versions.
