### ISSUE TITLE
CFP: Supports Gateway API with ALB as an entry point

### ISSUE THREAD

**Issue by kahirokunn** [cilium/cilium#24313]
## Cilium Feature Proposal
        
I created a Gateway with Cilium in EKS.

Then the following LoadBalancer Service was created.

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-12T00:53:08Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    io.cilium.gateway/owning-gateway: argocd-server
  name: cilium-gateway-argocd-server
  namespace: argocd
  ownerReferences:
  - apiVersion: gateway.networking.k8s.io/v1beta1
    kind: Gateway
    name: argocd-server
    uid: 3f86d86f-cbaa-4f7c-a849-dffb280ae120
  resourceVersion: "1698290"
  uid: 1c3a8f40-8bdf-4556-9abf-fcd24ded06df
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: xxxxxx
  clusterIPs:
  - xxxxxx
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-80
    nodePort: 30460
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxxxxx.ap-northeast-1.elb.amazonaws.com
```

However, this does not allow the following configuration.

In many AWS environments, we want to use the Gateway API with ALB + WAF.

To do so, I need to configure Ingress (ALB) -> NodePort -> cilium.

**Is your feature request related to a problem?**

If so, please describe the problem

**Describe the feature you'd like**

Include any specific requirements you need

1. Once the Gateway is created, we want the cilium operator to create an Ingress and NodePort with the specified annotations, etc.
2. In terms of integration with ecosystems such as External DNS, we would like to create Ingress and have the `.status.addresses[].value` of the Gateway resource refer to the Ingress status and be filled in automatically.

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by kahirokunn** [comment]
I close it because there is a possibility that we can realize it here.
https://github.com/cilium/cilium/issues/21923
https://cilium.slack.com/archives/C53TG4J4R/p1679293555186809?thread_ts=1679289508.318579&cid=C53TG4J4R

**Comment by spesalvi** [comment]
@kahirokunn - I'm also looking for a way to use ALB with Gateway API.

Can you please suggest how this change be implemented.

I'm not able to open the slack link mentioned in the last comment.

Thanks,
Robert

**Comment by jgalliers** [comment]
@kahirokunn Yes, please include any workable solution here so others may benefit - not many have access to Cilium slack.

**Comment by giogujabidze** [comment]
Hi,

This is very important feature, because not all the cases could be covered with NLB. Like it was already mentioned the WAF rules, which could not be attached to the NLB. The Slack channel is very old and it asks for the Pro license to open old message. Could you please describe the best way to be able to create ALB via Cilium Gateway API? I was looking for it in the documentations, but was unable to find.
