### ISSUE TITLE
Socket-lb: LRP keeps redirecting to terminated backends

### ISSUE THREAD

**Issue by storpipfugl** [cilium/cilium#24327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

During upgrade of k8s control-plane a restart of the nodelocal-dns daemonset was triggered after which DNS service was not working in the cluster. Logs indicate that after nodelocal-dns pods are rolled Cilium LRP keeps redirecting to the now terminated nodelocal-dns pods. The effect is basically a total outage of the affected apps. The situation can be normalized by doing a rollout restart of the affected apps deployment where the removal and addition of endpoints in Cilium seems to trigger some kind of cleanup that gets things rolling again.

### Cilium Version

1.12.2

### Kernel Version

5.4.0-126-generic (Ubuntu kernel)

### Kubernetes Version

1.24.10

### Relevant log output

```shell
Most interesting log errors from a worker during the incident:
"level=error msg=""Error while inserting service in LB map"" error=""local-redirect service exists for frontend {{10.245.0.10 {UDP 53} 0} 0}, skip update for svc kube-dns"" k8sNamespace=kube-system k8sSvcName=kube-dns subsys=k8s-watcher"
---
"level=error msg=""Timed out waiting for datapath updates of FQDN IP information; returning response"" subsys=daemon"
---
error=""read udp 10.217.11.80:56374->10.217.11.171:53: read: connection refused"" ipAddr=""10.217.11.177:50824"" subsys=fqdn/dnsproxy","level=error msg=""Cannot forward proxied DNS lookup""
---
"level=error msg=""Local redirect service for policy (kube-system/nodelocaldns) with frontend (10.245.0.10:53) not deleted
```

### Anything else?

Refer to Slack discussion of issue for full log dump: https://files.slack.com/files-pri/T1MATJ4SZ-F04RFEEGGGL/download/cilium_all_v2.tar.gz?origin_team=T1MATJ4SZ

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
>Logs indicate that after nodelocal-dns pods are rolled Cilium LRP keeps redirecting to the now terminated nodelocal-dns pods. 

Hey @storpipfugl It sounds like you might be hitting the existing limitation of socket-lb - https://github.com/cilium/cilium/issues/12859. Without a sysdump, I can't check your kube-proxy replacement settings. I'm working on a fix for 12859, so you can monitor the issue for updates. In the meantime, you can disable socket-lb, or set kube-proxy replacement to partial or disabled. Node-local dns with LRP works with kpr=disabled. If you want to give it a try, we can leave this issue open for now.

**Comment by storpipfugl** [comment]
Thanks for looking into this @aditighag. It does sound like the issue we are hitting but I'm a bit surprised that we have socket-lb enabled. Cilium status says so if I understand it correctly:
`kubectl -n kube-system exec -ti cilium-27w7d -- cilium status --verbose
...
KubeProxyReplacement Details:
  Status:                 Strict
  Socket LB:              Enabled
  Socket LB Protocols:    TCP, UDP
...
`
but we it set as false in the configmap
` kubectl -n kube-system get cm cilium-config -o yaml | grep bpf-lb-sock
  bpf-lb-sock: "false"
`
and the daemonset pods are also logs
`level=info msg="  --bpf-lb-sock='false'" subsys=daemon`

what am I missing here?
