### ISSUE TITLE
go list errors when importing cilium package to the go project

### ISSUE THREAD

**Issue by astanevich** [cilium/cilium#24348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

go throws `go: github.com/optiopay/kafka@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000` error importing cilium package to the go project. Everything works fine with cilium `v1.10.*`, but doesn't work with newer versions (`v.1.11.*`, `v.1.12.*`, `v.1.13.*`)

When using [GoLand by JetBrains](https://www.jetbrains.com/go/), it runs `go list -modfile=go.mod -m -json -mod=mod all` setting up a new project. This command fails importing cilium package and IDE stops until all errors resolved. So there is no way to use Goland and cilium pkg newer than `1.10.*`

**How to reproduce:**

➜  go mod init goapp
go: creating new go.mod: module goapp
➜  go get github.com/cilium/cilium@v1.12.4
go: added github.com/cilium/cilium v1.12.4
➜  go list -modfile=go.mod -m -json -mod=mod all
go: github.com/optiopay/kafka@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

### Cilium Version

v1.12.4

### Kernel Version

Darwin 22.3.0, Darwin Kernel Version 22.3.0

### Kubernetes Version

n/a

### Relevant log output

```shell
go list -modfile=go.mod -m -json -mod=mod all
go: github.com/optiopay/kafka@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tklauser** [comment]
Cilium's `go.mod` currently uses `replace` directives:

https://github.com/cilium/cilium/blob/685352fc59a62c862177038b2aea9b6a3628ac63/go.mod#L251-L259

Per Go's module dependency rules (https://go.dev/ref/mod#go-mod-file-replace), these only apply to the main module i.e. not to modules importing it like your example `goapp`.

The way to work around that is to replicate Cilium's `replace` directives in your projects `go.mod`. This is e.g. done in the cilium-cli and hubble projects, see https://github.com/cilium/cilium-cli/blob/6a22b8cd97027f8b03ae6217602a1638fba53432/go.mod#L5-L11 and https://github.com/cilium/hubble/blob/4412b202b23f549102e8fc1a421514cca361955b/go.mod#L97-L102

Make sure to use the same module versions the respective Cilium version you're importing is using.

Regarding the `github.com/optiopay/kafka` dependency: this one was already replaced in #22689 for Cilium v1.14. So if you `go get github.com/cilium/cilium@v1.14.0-snapshot.0` instead you should no longer see the error.

We're also working on removing the remaining `replace` directives to make it easier to use Cilium's packages in 3rd party projects.
