### ISSUE TITLE
dnsproxy stops responding when the k8s apiserver restarts

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#24353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upgraded the k8s apiserver which caused every cilium agent's dnsproxy stop responding to DNS and eventually restart when liveness probe failed. After the restart, dnsproxy worked fine again.

### Cilium Version

`Daemon: 1.12.7 6719063 2023-02-13T09:31:05+01:00 go version go1.18.10 linux/amd64`

### Kernel Version

`Linux ip-10-254-149-219 5.13.0-1021-aws #23~20.04.2-Ubuntu SMP Thu Mar 31 11:36:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.16-eks-48e63af", GitCommit:"e6332a8a3feb9e0fe3db851878f88cb73d49dd7a", GitTreeState:"clean", BuildDate:"2023-01-24T19:18:15Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}`

### Relevant log output

```shell
level=warning msg="No response from probe within 15 seconds" probe=l7-proxy subsys=status
level=warning msg="Timeout while waiting probe" probe=l7-proxy startTime="2023-03-13 19:51:22.150136323 +0000 UTC m=+425149.435771013" subsys=status
level=error msg="Failed to start the tcp DNS proxy on [::]:41717" error="accept tcp [::]:41717: use of closed network connection" subsys=fqdn/dnsproxy
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
This is very likely the issue fixed in #24672

**Comment by aanm** [comment]
@dctrwatson please test it out with v1.12.9. Thank you

**Comment by dctrwatson** [comment]
> @dctrwatson please test it out with v1.12.9. Thank you

Will do later today. I have 2 test clusters left I can try it on.

**Comment by dctrwatson** [comment]
The remaining clusters upgraded okay. I can't be as sure this is solved because the remaining clusters don't use k8s DNS in their hot paths.

The error message was logged by every agent at startup still though. Don't see any l7-proxy warnings though.

**Comment by christarazi** [comment]
Is this still an issue?

**Comment by dctrwatson** [comment]
> Is this still an issue?

Mostly sure it's not an issue. We will be upgrading the cluster that this affected soon. But it hasn't happened in a long while.

I'll re-open if it does though.
