### ISSUE TITLE
CFP: In the case of DSR+UDP, there is no need for "advertising a lower MTU".

### ISSUE THREAD

**Issue by jasongwq** [cilium/cilium#24359]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

No

**Describe the feature you'd like**

In the case of DSR+UDP, there is no need for "advertising a lower MTU". （It is difficult for us to control devices outside the cluster.）

> https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#dsr-mode
Therefore, Cilium encodes this information in a Cilium-specific IPv4 option or IPv6 Destination Option extension header at the cost of advertising a lower MTU. For TCP services, Cilium only encodes the service IP/port for the SYN packet, but not subsequent ones.

> https://github.com/cilium/cilium/pull/9473
 The current approach has a shortcoming that if the request size is > (MTU - 8bytes), the request will be dropped after we append the IPv4 option.
 To partially solve this, in the case of TCP we set the option only for SYN packets which should have an empty payload. However, the problem still exists for TCP with SYN cookies and UDP packets. For those cases, a client needs to decrease its MTU by 8bytes.

**(Optional) Describe your proposed solution**
1. Increase the MTU of a node
2. The backends receives the IPv4 option, deletes it, and passes it to the pod.
3. Similar to TCP, when UDP has multiple IPv4 fragments, the IPv4 option extension header is only added to the first fragment.

**Comment by Jiang1155** [comment]
I assume you are talking about L2 MTUs.  The L2 MTU normally should be the same for the connected network devices. 
You mentioned that "it is difficult for us to control devices outside the cluster". Then even if you increase the node MTU, it will not work. The other devices still have a smaller MTU and will likely drop the packets which are larger than their MTU.

**Comment by divfor** [comment]
L2 switches can easily use a default 9200 MTU, so only k8s nodes need to increase L2 MTU.  actually large MTU (9000+ bytes) within local networks is more and more normal. This is helpful option to use DSR.
