### ISSUE TITLE
Update upgrade notes for 1.12.x, 1.13.y dataplane impact

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#24356]
The following page hasn't been updated to include entries in the table for 1.12 / 1.13:
https://docs.cilium.io/en/stable/operations/upgrade/#version-specific-notes

It should be updated. The impact should be the same as for earlier release series.

**Comment by mohit-marathe** [comment]
@joestringer , I think this issue is resolved

**Comment by joestringer** [comment]
Thanks, looks good!
