### ISSUE TITLE
CI: flakes due to putEndpointIdTooManyRequests

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#24361]
## CI failure

I saw a [ci failure](https://github.com/cilium/cilium/actions/runs/4406427789/jobs/7737432405) where some server pods failed to come up. The error message as returned by the CNI plugin was

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "64d0ede7d7465a1f77351e8f1eb3b724ab1ea35488e2a02a53cbf4f7fbb50bdd": plugin type="cilium-cni" name="cilium" failed (add): Unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests
```

Now, this is interesting because the CNI ADD should have been retried, but given that this node didn't have very many pods running on it. Nevertheless, we should consider raising the rate limit, and maybe just add a backoff + retry internal to the client. That way we can avoid surfacing these sorts of errors to the end-user.

**Comment by joestringer** [comment]
The rate limit is dynamic, so it's quite interesting if Cilium is returning this. Was this primarily caused by the deadlock that is referenced in the GitHub breadcrumbs above my response here, or was that unrelated? Potential consquences could be either, the ratelimiting heuristic is not well tuned, or we have some sort of real issue that is restricting the rate of endpoint creations that Cilium can handle.

Backoff+retry in the client could be an interesting avenue to explore, but IIRC we were trying to avoid being preempted by kubelet which could prematurely terminate Endpoint Create API calls, which the agent might not handle particularly gracefully. Definitely open to improvements in this area.

**Comment by squeed** [comment]
@joestringer in this case, the deadlock referenced in the breadcrumb is unrelated (it was a deadlock in the operator, unrelated to PodSandbox creation).

I've seen this error message a few times in CI; in all cases, there is a Deployment spinning up 5 pods in rapid sequence. The default burst in this case is 4, so one of them gets rate-limited.

I agree that we don't want to risk having endpoint creation terminated by the kubelet. However, I'm fairly certain we can retry a few times before that becomes a factor:

- kubelet PodSandbox creation deadline is, by default, 4 minutes. Containerd does not have any stricter deadlines for CNI ADD, nor do I believe cri-o does either. Given that PodSandbox creation usually takes ~1-2 seconds outside of CNI, I don't think we're at real risk of actually hitting that deadline
- Timing out means the CNI plugin process is killed, but all that means is that the APUI request's context is cancelled. We check for a done context a few places within `createEndpoint`, but at a first glance, we handle context closure gracefully.

All in all, I think it's safe for us to wait a second or two and retry. All of this is better than returning a failure to the kubelet and forcing the PodSandbox to be torn down and recreated.

**Comment by joestringer** [comment]
> At a first glance, we handle context closure gracefully.

You're more confident than me :joy: . From recollection, we got to a point where Cilium had an internal ~55s timer that would cancel the operation so that the Cilium's API handler could return back to Cilium-CNI within ideally 60s even if internally Cilium is taking too long to implement the request.. I was under the impression this case is graceful in Cilium, though I couldn't convincingly explain "why" without a much deeper dive.

I was under the impression we actually had 1m30s to handle it and we were being paranoid with the 1m SLA, so it's interesting to me that you're reporting we have 4m. I'm not sure where these numbers are coming from. Maybe Cilium client library API timers are also playing a role.

Beyond that, I'm not sure whether an API client cancellation is propagated correctly through the same mechanism to properly cancel the operation internally in Cilium, but I guess if that's missing then presumably we should just propagate that same context to the current part that we expect to work above. Not sure if that's the case you investigated above.

Then there's the question of testing, which I strongly suspect we have no testing that validates that such a case would leave things in a sane state.

Could there be this scenario?
1. Cilium CNI attempts to create the endpoint
1. Through 429s and retries etc. it delays the creation
1. Eventually Cilium can create the endpoint, this part succeeds
1. Cilium CNI is still wrapping things up, handling the successful return code
1. Kubelet kills Cilium-CNI
1. Kubelet doesn't execute a delete because the create was unsuccessful
1. Now we leaked an endpoint

Some of the oddities from a Cilium API perspective is that IIRC EndpointCreate is a blocking API, it's not "create" + separate query to check whether the create was successful. So the concern is that if somehow step (3)/(4) above crosses some timeout boundary at all (potentially because of the retries in step (2)), then maybe we end up leaving some state around.

**Comment by squeed** [comment]
> Could there be this scenario?
> 
>     1. Cilium CNI attempts to create the endpoint
> 
>     2. Through 429s and retries etc. it delays the creation
> 
>     3. Eventually Cilium can create the endpoint, this part succeeds
> 
>     4. Cilium CNI is still wrapping things up, handling the successful return code
> 
>     5. Kubelet kills Cilium-CNI
> 
>     6. Kubelet doesn't execute a delete because the create was unsuccessful
> 
>     7. Now we leaked an endpoint

According to the CNI spec, runtimes are supposed to issue a DEL after every unsuccessful ADD. Whether or not they handle this in the timeout case is not certain, but seems likely. In fact, containerd looks [pretty good at first glance](https://github.com/containerd/containerd/blob/main/pkg/cri/server/sandbox_run.go#L316). If CRI-O doesn't handle this, I'll file an issue on their side as well.

As for timeouts, I can't find any specific timeouts in the containerd code. In kubelet itself, the timeout is [2 minutes](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/v1beta1/defaults.go#L171) but this is [doubled for CreatePodSandbox](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cri/remote/remote_runtime.go#L163)

All in all, I think that a few seconds of retries aren't going to make the situation noticeably *worse*. If we spend, say, a maximum 15 seconds backing off and retrying, I would argue we improve the UX without significantly increasing the risk of bugs.

**Comment by davem-git** [comment]
I ran into this issue earlier today too. it looks like it retries every 30 seconds. an took 3 tries to start. I was restarting 1 workload with 3 pods, doesn't seem like i should have had too much going on

```sh
  Warning  FailedCreatePodSandBox  6m45s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "6d60d84387fbce1db0d5998616e57fd1aad7e44de0c9a6761ba1cda24b8f49c3": plugin type="cilium-cni" name="cilium" failed (add): unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests
  Warning  FailedCreatePodSandBox  6m15s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f96cf9dfbef921d51b10bc700d54635a712c69fdde8a8675480e32db2c6c1f41": plugin type="cilium-cni" name="cilium" failed (add): unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests
  Warning  FailedCreatePodSandBox  5m50s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "7a9d379de6f2002effd59afc2d59938ccefec7063ee89d046da697b36dc3d233": plugin type="cilium-cni" name="cilium" failed (add): unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests

**Comment by pchaigno** [comment]
@squeed Did you end up sending a PR for this?

**Comment by squeed** [comment]
I did not; it turns out the rate-limiting code is more sophisticated than I appreciated; it maintains a queue of waiting requests.

Nevertheless, container creation may fail now and then when performing large scaleups. If tests don't anticipate this, they need to be updated.

**Comment by aojea** [comment]
Do I understand this correctly and the CNI ADD depends on the API request to succeed?
@squeed do you have a link to the code?

**Comment by squeed** [comment]
If by API, you mean the cilium API exposed at `/run/cilium/cilium.sock`, then yes. The CNI plugin sets up the interface, then requests that the agent create an Endpoint. This is synchronous, and if the API is down or fails it will return failure to the runtime.

If you are having issues at scale, there are options to fix it. Firstly, we should make sure that the rate limiting is working as expected. It is supposed to be adaptive, allowing more in-flight requests if performance is good. We should probably check that it is working as intended (it seems okay, from a first read-through).

We should also give pod creation a quick profile and do a bit of spot optimization.

**Comment by aojea** [comment]
> If by API, you mean the cilium API exposed

apiserver, I remember some of the problems we had in ovn-kubernetes was because the CNI ADD required an API call to the apiserver to get the PodIP from the Pod object, and if there were any latency or connectivity problems trying to get the Pod object, the CNI ADD timed out

**Comment by squeed** [comment]
Fortunately that's not a problem we have here; ovn-kubernetes had a centralized control plane that was often very far behind the pod changestream. In this case, the "api" we're speaking about is the socket that the cni plugin uses to talk to the daemon.

Endpoint creation in Cilium is non-trivial -- to prevent pod creation from using all CPU, we intentionally rate limit endpoint creation and thus CNI ADD. The rate-limit is adaptive: depending on EndpointCreate request duration, the max-in-flight is adjusted so that wall-clock time remains within a certain window. However, just like TCP sliding window, it's not perfect and can lead to requests occasionally getting 429'd, as it were.

That said, there is room for improvement here. I suspect we just want to have a longer queue of pending EndpointCreate requests, especially if we don't have a lot of confidence for how long the queue can be. Or transition to a more sophisticated queuing discipline - something in the style of CoDel would be nice.

**Comment by aojea** [comment]
@squeed does this not need to create a CRD ?

where can I read more, can you give me some links to the code to get an starting point?

**Comment by philpearl** [comment]
This is just an FYI - not expecting any help or investigation. I think I've seen this against Google's dataplane V2. The scenario is an integration test where we start ~170 pods and there's not enough capacity in the cluster. The cluster scales up and adds a new node. Then we hit the rate limit issue across a large number of pods. 38 minutes later some pods are still stuck in an error state. Note that killing the pod failed!


```
Events:
  Type     Reason                  Age                 From               Message
  ----     ------                  ----                ----               -------
  Warning  FailedScheduling        38m                 default-scheduler  0/16 nodes are available: 1 node(s) had untolerated taint {workload-identity: enabled}, 6 Insufficient cpu, 9 Too many pods. preemption: 0/16 nodes are available: 1 Preemption is not helpful for scheduling, 15 No preemption victims found for incoming pod.
  Normal   Scheduled               36m                 default-scheduler  Successfully assigned accrds-883ef4403093ab7074feba779a9da52e7f409084/supplier-evidence-78849b757-fvpt8 to gke-dev-spot-9902a134-cc5f
  Warning  FailedCreatePodSandBox  36m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2aceb366d2544bd036e1e1bc1a81e400c2bfcf2ed9c6dec6c6c0eaebb08eb24b": plugin type="cilium-cni" failed (add): unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests
  Warning  FailedCreatePodSandBox  35m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4eb43d8b4005fc38cb869f874b028cf9e0b2d11e5b09de7b7c4a58bcdecfe917": plugin type="cilium-cni" failed (add): unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests
  Normal   Pulling                 34m                 kubelet            Pulling image "eu.gcr.io/ravelin-builds/supplier-evidence-service:latest--master"
  Normal   Pulled                  34m                 kubelet            Successfully pulled image "eu.gcr.io/ravelin-builds/supplier-evidence-service:latest--master" in 11.303560809s
  Normal   Created                 34m                 kubelet            Created container supplier-evidence
  Normal   Started                 34m                 kubelet            Started container supplier-evidence
  Normal   Killing                 27m                 kubelet            Stopping container supplier-evidence
  Warning  FailedKillPod           27m                 kubelet            error killing pod: failed to "KillPodSandbox" for "3f9f74d3-b944-477c-a344-a30381c77e3b" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"f634d70dbdf6b65d7d77d58899d4c3426da549832c428473a7171621cdcf41ee\": plugin type=\"cilium-cni\" failed (delete): failed to find plugin \"cilium-cni\" in path [/home/kubernetes/bin]"
  Warning  NetworkNotReady         26m (x2 over 26m)   kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
  Warning  FailedMount             26m (x3 over 26m)   kubelet            MountVolume.SetUp failed for volume "ravelin-config" : object "accrds-883ef4403093ab7074feba779a9da52e7f409084"/"ravelin-config" not registered
  Warning  FailedMount             23m (x6 over 24m)   kubelet            MountVolume.SetUp failed for volume "ravelin-config" : object "accrds-883ef4403093ab7074feba779a9da52e7f409084"/"ravelin-config" not registered
  Warning  FailedMount             23m (x6 over 24m)   kubelet            MountVolume.SetUp failed for volume "kube-api-access-ttlvr" : object "accrds-883ef4403093ab7074feba779a9da52e7f409084"/"kube-root-ca.crt" not registered
  Warning  NetworkNotReady         23m (x13 over 24m)  kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
  Normal   Killing                 2m2s                kubelet            Stopping container supplier-evidence
  Warning  FailedKillPod           104s                kubelet            error killing pod: failed to "KillPodSandbox" for "3f9f74d3-b944-477c-a344-a30381c77e3b" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"28ed42394a7e0abd28b6b5754c783530a01f691dad9a057fe09de3feba6628e2\": plugin type=\"cilium-cni\" failed (delete): failed to find plugin \"cilium-cni\" in path [/home/kubernetes/bin]"
  Warning  NetworkNotReady         14s                 kubelet            network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
  Warning  FailedMount             14s                 kubelet            MountVolume.SetUp failed for volume "ravelin-config" : object "accrds-883ef4403093ab7074feba779a9da52e7f409084"/"ravelin-config" not registered
```

**Comment by aojea** [comment]
@philpearl have you open a support case?

**Comment by davem-git** [comment]
i added this to the configmap

```yaml  api-rate-limit: |
    endpoint-create=auto-adjust:true,mean-over:15
```
it seemed to help on a lot of my clusters. I still have some errors though not perfect

**Comment by christarazi** [comment]
@davem-git I'm curious to know if Casey's PR could improve things for you: https://github.com/cilium/cilium/pull/25805

**Comment by marandalucas** [comment]
@davem-git

How can I set up api-rate-limit: in Dataplane V2?

Thanks

**Comment by yifeng-cerebras** [comment]
Can I ask what's the relation with the of this api rate limit vs k8s-client-qps? 
The doc doesn't seem to clarify.

**Comment by yifeng-cerebras** [comment]
@christarazi Thanks for clarifying. I'm trying to tune these configs for a large cluster.
IIUC, actions like create endpoint will eventually also need to call k8s client to create corresponding endpoint crd object and update pod.
So just to confirm, the internal rate limit will apply first before the k8s client side qps/rate limit but either of the these two qps config can be a bottleneck in case of a large number of pods creation?

**Comment by radhupr** [comment]
We're on Cilium 1.14.4 version. Due to some breaking changes , we are holding the upgrade till we move to new cluster. Is there any solution to this other than increasing `api-rate-limit` which is not available in the version we are using.

**Comment by davem-git** [comment]
> @davem-git
> 
> How can I set up api-rate-limit: in Dataplane V2?
> 
> Thanks

Sorry i missed this. Dataplan V2 is a gcp controlled cilium right? I'm not sure how that would be set. Can you pass a configmap for it?

**Comment by lodotek** [comment]
Did anyone figure out a solution for this for GKE dataplanev2 users operating at scale? (~10K+ pods and hundreds of nodes)
