### ISSUE TITLE
CFP: Create a cilium-multicall executable binary (or multiple binaries)

### ISSUE THREAD

**Issue by jingyuanliang** [cilium/cilium#24371]
## Cilium Feature Proposal

Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

A typical Cilium setup consists of multiple Cilium-related binaries. Some pkgs are shared by many or all of those binaries, and due to the static linking nature of Golang, the shared pkgs are stored as multiple copies in those binaries. This inflates the total space occupancy for a complete Cilium installation.

**Describe the feature you'd like**

Reduce the space footprint of Cilium installation, especially for the use case when Cilium is being packaged as a container and needs to be downloaded at runtime.

**(Optional) Describe your proposed solution**

Create a cilium-multicall executable that looks like:
```
import (
	bugtoolcmd "github.com/cilium/cilium/bugtool/cmd"
	healthcmd "github.com/cilium/cilium/cilium-health/cmd"
	ciliumcmd "github.com/cilium/cilium/cilium/cmd"
	daemoncmd "github.com/cilium/cilium/daemon/cmd"
)

func main() {
	switch name := path.Base(os.Args[0]); name {
	case "cilium":
		ciliumcmd.Execute()
	case "cilium-agent":
		daemoncmd.Execute()
	case "cilium-health":
		healthcmd.Execute()
	case "cilium-bugtool":
		if err := bugtoolcmd.BugtoolRootCmd.Execute(); err != nil {
			fmt.Println(err)
			os.Exit(1)
		}
	case "cilium-cni":
		cniMain()
	default:
		fmt.Printf("Unknown command: %s\n", name)
		os.Exit(1)
	}
}
```
then use the executable in place of separate cilium / cilium-agent / cilium-health / cilium-bugtool / cilium-cni by having them symlinked to the multicall executable. An experimental setup cuts off 40MB from the container image built by combining cilium / cilium-agent / cilium-health / cilium-bugtool / cilium-cni. We might be able to go further and combine envoy / hubble etc. too (I haven't identified how much code duplication there is between envoy / hubble and the main cilium codebase), or create multiple variations based on the list of cmds included (e.g. whether hubble is bundled).

@varunmar @MrHohn

**Comment by joestringer** [comment]
Hi @jingyuanliang , thanks for the suggestion!

Broadly this CFP starts with the assumption that most of the container image size comes from the binaries. Do you have data to break down the Cilium container usage to help us reason about this?

I believe we have explored this specific suggestion in the past and then reverted it for some reason, so it may be worth digging through the PR / git history to track down the rationale there. I'm open to this idea in general as long as we're taking into account any previous pain points.

Sharing code with the `cilium` binary seems like the most promising case from the ones you mentioned. I wouldn't expect much code to be shared with `cilium-health`, which should be a very simple HTTP agent. `cilium-bugtool` should be just running a bunch of commands + maybe some API requests (maybe there's sharing there, but I don't know how much). I don't think that `cilium-cni` should be shared, as it is a very simple binary that runs outside the container and the rest of the Cilium functionality should not be necessary there. Hubble CLI comes from https://github.com/cilium/hubble, merging that is likely to be a much bigger job. I'm a bit skeptical whether it's worthwhile. Envoy doesn't make sense to me at all, there is zero code sharing, they're written in different languages.

**Comment by jingyuanliang** [comment]
I'm only talking about the main cilium/cilium image. I'm looking at the tree at 8b2070337ded0af2ff3909b9908e907849908915. The image is built at gcr.io/gke-networking-test-images/cilium/cilium@sha256:7c0c7a9fe5ffa7b68e8e15eb874163022023378e4f2e1cfaf19c26e6a9f06d2b - should be public.

Layers annotated with Dockerfile command:
```
[
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 82576645, FROM ${CILIUM_RUNTIME_IMAGE} as release
         "digest": "sha256:25fcb78b84bce7d0139e52eff2afdfcd24fe142e7127edd5fd734cb51577496e"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1228, RUN echo ". /etc/profile.d/bash_completion.sh" >> /etc/bash.bashrc
         "digest": "sha256:e9ebbcff3bf986bbb3eb9b3a82eb44d02d0dc93788247200bf3ab93fbb7d47ed"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 11462594, COPY --from=cilium-envoy / /
         "digest": "sha256:2d5963d73a9cb7d205c803c738c026d797afb2c4fa79992669c8e73857758127"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 7815862, COPY --from=hubble /out/${TARGETOS}/${TARGETARCH}/bin/hubble /usr/bin/hubble
         "digest": "sha256:97d615d6782435e559f5c0226db1e3d1d69aa3e98e0953319040b6ce741c7b2a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 3627, COPY --from=hubble /out/linux/bash_completion /etc/bash_completion.d/hubble
         "digest": "sha256:3572155bb911e27e25870b0ee901aa2476c9972e3ace911376755ac220ed692b"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 74783372, COPY --from=builder /tmp/install/${TARGETOS}/${TARGETARCH} /
         "digest": "sha256:8282a37a5cc0f7e19ec09d7cad57846f1e61772e2fb6a1b39859542486727166"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 116,
         "digest": "sha256:bbc248eeb74b02beec5c37172374cd249190a55c9ae2df0aaf9318726734b72d"
      }
   ]
```

CILIUM_RUNTIME_IMAGE is the top consumer and clang is a big chunk of it. https://github.com/cilium/cilium/issues/9361 / https://github.com/cilium/cilium/issues/9515 track the removal of clang. Other than that, it's the main binaries and it's almost comparable to the binaries. Extracting the image, we see this. cilium-cni is smaller, but it's still 2x the size since I saw it a few months ago.

```
$ ls -l usr/bin/cilium*
-rwxr-x--- 1 jingyuanliang primarygroup 66904064 Mar 16 23:35 usr/bin/cilium
-rwxr-x--- 1 jingyuanliang primarygroup 85745664 Mar 16 23:35 usr/bin/cilium-agent
-rwxr-x--- 1 jingyuanliang primarygroup  7749632 Mar 16 23:35 usr/bin/cilium-bugtool
-rwxr-x--- 1 jingyuanliang primarygroup 30856384 Mar  2 14:07 usr/bin/cilium-envoy
-rwxr-x--- 1 jingyuanliang primarygroup 15073280 Mar 16 23:35 usr/bin/cilium-health
-rwxr-x--- 1 jingyuanliang primarygroup  4710400 Mar 16 23:35 usr/bin/cilium-health-responder
-rwxr-x--- 1 jingyuanliang primarygroup  1638400 Mar 16 23:35 usr/bin/cilium-mount
-rwxr-x--- 1 jingyuanliang primarygroup  2461696 Mar 16 23:35 usr/bin/cilium-sysctlfix
$ ls -l opt/cni/bin/cilium*
-rwxr-x--- 1 jingyuanliang primarygroup 28778496 Mar 16 23:35 opt/cni/bin/cilium-cni
```

I've mocked up the easiest change: https://github.com/jingyuanliang/cilium/compare/master...jingyuanliang:cilium:ln - I'm saying it's the "easiest" because I'm hijacking cilium-cni's binary. It's built to gcr.io/gke-networking-test-images/cilium/cilium@sha256:81866c80c329ae75d02a51bfa9922314c979af4006c04017765d36cbf178371e and layer containing the binaries dropped from 74783372 to 37290956, approximately cut in half. Inside the image, the sum of sizes of all binaries is just a few megabytes higher than the size of the previously largest binary (cilium-agent). This is before compression during `docker build`.

```
$ ls -l usr/bin/cilium*
lrwxrwxrwx 1 jingyuanliang primarygroup       23 Mar 16 23:54 usr/bin/cilium -> /opt/cni/bin/cilium-cni
lrwxrwxrwx 1 jingyuanliang primarygroup       23 Mar 16 23:54 usr/bin/cilium-agent -> /opt/cni/bin/cilium-cni
lrwxrwxrwx 1 jingyuanliang primarygroup       23 Mar 16 23:54 usr/bin/cilium-bugtool -> /opt/cni/bin/cilium-cni
-rwxr-x--- 1 jingyuanliang primarygroup 30856384 Mar  2 14:07 usr/bin/cilium-envoy
lrwxrwxrwx 1 jingyuanliang primarygroup       23 Mar 16 23:54 usr/bin/cilium-health -> /opt/cni/bin/cilium-cni
-rwxr-x--- 1 jingyuanliang primarygroup  4710400 Mar 16 23:53 usr/bin/cilium-health-responder
-rwxr-x--- 1 jingyuanliang primarygroup  1638400 Mar 16 23:53 usr/bin/cilium-mount
-rwxr-x--- 1 jingyuanliang primarygroup  2461696 Mar 16 23:53 usr/bin/cilium-sysctlfix
$ ls -l opt/cni/bin/cilium*
-rwxr-x--- 1 jingyuanliang primarygroup 89776128 Mar 16 23:53 opt/cni/bin/cilium-cni
```

As for functionality, I didn't run a full test set, but I quickly applied the same change to GKE's Cilium fork, and replaced the image into a cluster, and that cluster appears working well. I didn't run a full test set there either though.
