### ISSUE TITLE
Installing cilium breaks connection with internal load balancer

### ISSUE THREAD

**Issue by jorgnyg** [cilium/cilium#24372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

k3s worker nodes were able to communicate with master through internal load balancer before installing cilium.
After installing cilium the master node "breaks" connection with lb. 

Don't have full overview of what installation does, so not sure what kind of restrictions/changes are being made when installing. Might need to set some other options to make this work, but not sure about what. Might have completely overlooked something here..

### Cilium Version

1.13.0

### Kernel Version

5.15.0

### Kubernetes Version

Client Version: v1.25.7+k3s1
Kustomize Version: v4.5.7
Server Version: v1.25.7+k3s1

### Sysdump

🔍 Collecting sysdump with cilium-cli version: v0.13.1, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
🔮 Detected Cilium operator in namespace "kube-system"
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collecting Cilium nodes
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Cilium network policies
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium identities
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium Node Configs
🔍 Collecting Ingresses
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting Cilium BGP Peering Policies
🔍 Collecting Cilium LoadBalancer IP Pools
🔍 Collecting Cilium etcd secret
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
E0314 21:27:15.702742   16149 memcache.go:255] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
🔍 Collecting gops stats from Cilium pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
🔍 Collecting bugtool output from Cilium pods
⚠️ Deployment "hubble-relay" not found in namespace "kube-system" - this is expected if Hubble is not enabled
⚠️ Deployment "hubble-ui" not found in namespace "kube-system" - this is expected if Hubble UI is not enabled
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting profiling data from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting platform-specific data
🔍 Collecting kvstore data
E0314 21:27:15.874963   16149 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0314 21:27:15.879321   16149 memcache.go:106] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
🔍 Collecting Hubble flows from Cilium pods
I0314 21:27:16.905136   16149 request.go:682] Waited for 1.123039024s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:6443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dcilium
⚠️ Container "cilium-agent" for pod "cilium-djm58" in namespace "kube-system" is not running. Trying EphemeralContainer or separate Pod instead...
⚠️ EphemeralContainer "sysdump-1678829236" on pod "cilium-djm58" in namespace "kube-system" never reached Running status (falling back to separate Pod)
⚠️ Container "cilium-agent" on pod "cilium-djm58" in namespace "kube-system" is not running. Creating exec Pod.
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [12] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource
⚠️ [13] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [14] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [20] Collecting CiliumClusterwideEnvoyConfigs: failed to collect CiliumClusterwideEnvoyConfigs: the server could not find the requested resource (get ciliumclusterwideenvoyconfigs.cilium.io)
⚠️ [21] Collecting CiliumEnvoyConfigs: failed to collect CiliumEnvoyConfigs: the server could not find the requested resource (get ciliumenvoyconfigs.cilium.io)
⚠️ [22] Collecting Cilium BGP Peering Policies: failed to collect Cilium BGP Peering policies: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [23] Collecting Cilium LoadBalancer IP Pools: failed to collect Cilium LoadBalancer IP Pools: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [28] Collecting the Hubble Relay configuration: failed to collect the Hubble Relay configuration: configmaps "hubble-relay-config" not found
⚠️ cniconflist-cilium-6p2q8: error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ cniconflist-cilium-djm58: unable to upgrade connection: container not found ("cilium-agent")
⚠️ cniconflist-cilium-tp46k: error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ cniconflist-cilium-z6rsf: error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-6p2q8-memstats: failed to list processes "cilium-6p2q8" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-6p2q8-stack: failed to list processes "cilium-6p2q8" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-6p2q8-stats: failed to list processes "cilium-6p2q8" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-djm58-memstats: failed to list processes "cilium-djm58" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-djm58-stack: failed to list processes "cilium-djm58" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-djm58-stats: failed to list processes "cilium-djm58" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-tp46k-memstats: failed to list processes "cilium-tp46k" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-tp46k-stack: failed to list processes "cilium-tp46k" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-tp46k-stats: failed to list processes "cilium-tp46k" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-z6rsf-memstats: failed to list processes "cilium-z6rsf" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-z6rsf-stack: failed to list processes "cilium-z6rsf" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-z6rsf-stats: failed to list processes "cilium-z6rsf" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ cilium-bugtool-cilium-6p2q8: failed to collect 'cilium-bugtool' output for "cilium-6p2q8" in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable: 
⚠️ cilium-bugtool-cilium-tp46k: failed to collect 'cilium-bugtool' output for "cilium-tp46k" in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable: 
⚠️ cilium-bugtool-cilium-z6rsf: failed to collect 'cilium-bugtool' output for "cilium-z6rsf" in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable: 
⚠️ gops-cilium-6p2q8-pprof-heap: failed to list processes "cilium-6p2q8" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-6p2q8-pprof-cpu: failed to list processes "cilium-6p2q8" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-djm58-pprof-heap: failed to list processes "cilium-djm58" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-djm58-pprof-cpu: failed to list processes "cilium-djm58" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-tp46k-pprof-heap: failed to list processes "cilium-tp46k" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-tp46k-pprof-cpu: failed to list processes "cilium-tp46k" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-z6rsf-pprof-heap: failed to list processes "cilium-z6rsf" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ gops-cilium-z6rsf-pprof-cpu: failed to list processes "cilium-z6rsf" ("cilium-agent") in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-6p2q8-cilium-agent: failed to collect logs for "cilium-6p2q8" ("cilium-agent") in namespace "kube-system": Get "https://10.0.0.253:10250/containerLogs/kube-system/cilium-6p2q8/cilium-agent?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-6p2q8-config: failed to collect logs for "cilium-6p2q8" ("config") in namespace "kube-system": Get "https://10.0.0.253:10250/containerLogs/kube-system/cilium-6p2q8/config?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-6p2q8-mount-cgroup: failed to collect logs for "cilium-6p2q8" ("mount-cgroup") in namespace "kube-system": Get "https://10.0.0.253:10250/containerLogs/kube-system/cilium-6p2q8/mount-cgroup?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-6p2q8-apply-sysctl-overwrites: failed to collect logs for "cilium-6p2q8" ("apply-sysctl-overwrites") in namespace "kube-system": Get "https://10.0.0.253:10250/containerLogs/kube-system/cilium-6p2q8/apply-sysctl-overwrites?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-6p2q8-mount-bpf-fs: failed to collect logs for "cilium-6p2q8" ("mount-bpf-fs") in namespace "kube-system": Get "https://10.0.0.253:10250/containerLogs/kube-system/cilium-6p2q8/mount-bpf-fs?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-6p2q8-clean-cilium-state: failed to collect logs for "cilium-6p2q8" ("clean-cilium-state") in namespace "kube-system": Get "https://10.0.0.253:10250/containerLogs/kube-system/cilium-6p2q8/clean-cilium-state?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-operator-745755bb84-6bqsm-cilium-operator: failed to collect logs for "cilium-operator-745755bb84-6bqsm" ("cilium-operator") in namespace "kube-system": Get "https://10.0.0.37:10250/containerLogs/kube-system/cilium-operator-745755bb84-6bqsm/cilium-operator?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-tp46k-cilium-agent: failed to collect logs for "cilium-tp46k" ("cilium-agent") in namespace "kube-system": Get "https://10.0.0.37:10250/containerLogs/kube-system/cilium-tp46k/cilium-agent?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-tp46k-config: failed to collect logs for "cilium-tp46k" ("config") in namespace "kube-system": Get "https://10.0.0.37:10250/containerLogs/kube-system/cilium-tp46k/config?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-tp46k-mount-cgroup: failed to collect logs for "cilium-tp46k" ("mount-cgroup") in namespace "kube-system": Get "https://10.0.0.37:10250/containerLogs/kube-system/cilium-tp46k/mount-cgroup?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ hubble-flows-cilium-6p2q8: failed to collect hubble flows for "cilium-6p2q8" in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.253:10250, code 503: 503 Service Unavailable: 
⚠️ logs-cilium-tp46k-apply-sysctl-overwrites: failed to collect logs for "cilium-tp46k" ("apply-sysctl-overwrites") in namespace "kube-system": Get "https://10.0.0.37:10250/containerLogs/kube-system/cilium-tp46k/apply-sysctl-overwrites?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ hubble-flows-cilium-djm58: failed to collect hubble flows for "cilium-djm58" in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent"): 
⚠️ logs-cilium-tp46k-mount-bpf-fs: failed to collect logs for "cilium-tp46k" ("mount-bpf-fs") in namespace "kube-system": Get "https://10.0.0.37:10250/containerLogs/kube-system/cilium-tp46k/mount-bpf-fs?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ hubble-flows-cilium-tp46k: failed to collect hubble flows for "cilium-tp46k" in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable: 
⚠️ logs-cilium-tp46k-clean-cilium-state: failed to collect logs for "cilium-tp46k" ("clean-cilium-state") in namespace "kube-system": Get "https://10.0.0.37:10250/containerLogs/kube-system/cilium-tp46k/clean-cilium-state?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.37:10250, code 503: 503 Service Unavailable
⚠️ hubble-flows-cilium-z6rsf: failed to collect hubble flows for "cilium-z6rsf" in namespace "kube-system": error dialing backend: proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable: 
⚠️ logs-cilium-z6rsf-cilium-agent: failed to collect logs for "cilium-z6rsf" ("cilium-agent") in namespace "kube-system": Get "https://10.0.0.29:10250/containerLogs/kube-system/cilium-z6rsf/cilium-agent?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-z6rsf-config: failed to collect logs for "cilium-z6rsf" ("config") in namespace "kube-system": Get "https://10.0.0.29:10250/containerLogs/kube-system/cilium-z6rsf/config?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-z6rsf-mount-cgroup: failed to collect logs for "cilium-z6rsf" ("mount-cgroup") in namespace "kube-system": Get "https://10.0.0.29:10250/containerLogs/kube-system/cilium-z6rsf/mount-cgroup?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-z6rsf-apply-sysctl-overwrites: failed to collect logs for "cilium-z6rsf" ("apply-sysctl-overwrites") in namespace "kube-system": Get "https://10.0.0.29:10250/containerLogs/kube-system/cilium-z6rsf/apply-sysctl-overwrites?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-z6rsf-mount-bpf-fs: failed to collect logs for "cilium-z6rsf" ("mount-bpf-fs") in namespace "kube-system": Get "https://10.0.0.29:10250/containerLogs/kube-system/cilium-z6rsf/mount-bpf-fs?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ logs-cilium-z6rsf-clean-cilium-state: failed to collect logs for "cilium-z6rsf" ("clean-cilium-state") in namespace "kube-system": Get "https://10.0.0.29:10250/containerLogs/kube-system/cilium-z6rsf/clean-cilium-state?limitBytes=1073741824&sinceTime=2022-03-14T21%3A27%3A17Z&timestamps=true": proxy error from 127.0.0.1:6443 while dialing 10.0.0.29:10250, code 503: 503 Service Unavailable
⚠️ Please note that depending on your Cilium version and installation options, this may be expected
🗳 Compiling sysdump

### Anything else?

**Joining master node**
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--flannel-backend=none --disable-kube-proxy --disable-network-policy --node-taint node.cilium.io/agent-not-ready=true:NoSchedule' K3S_TOKEN=[token] sh -s - --cluster-init`

**Joining worker node**
`curl -sfL https://get.k3s.io | NSTALL_K3S_EXEC='--node-taint node.cilium.io/agent-not-ready=true:NoSchedule' K3S_URL=https://[internal-lb-ip]:6443 K3S_TOKEN=[token] sh -`

**Installing cilium on master node**
```
helm template cilium cilium/cilium \
		--version 1.13.0 \
    --namespace kube-system \
		--set operator.replicas=1 \
    --set k8sServiceHost=<internal-lb-ip> \
    --set k8sServicePort=6443 \
  > cilium.yaml
```
then apply

Backend set with master node on port 6443 is working fine before installing cilium. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jorgnyg** [comment]
Solved by disabling flannel _after_ installing cilium.

**Comment by nitays** [comment]
> Solved by disabling flannel _after_ installing cilium.

How did you do that, on an already-provisioned cluster?
