### ISSUE TITLE
cilium-agent metrics retrieve return 500 

### ISSUE THREAD

**Issue by yanhongchang** [cilium/cilium#24381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

by curl to retrieve metrics , such as : curl 10.20.x.x:9095/metrics, and get error:

An error has occurred while serving metrics:

collected metric "cilium_agent_api_process_time_seconds" { label:<name:"method" value:"0\231\224" > label:<name:"path" value:"0\231\224\nendpoint" > label:<name:"return_code" value:"201" > histogram:<sample_count:6330114 sample_sum:2.0773538182114024e+07 bucket:<cumulative_count:0 upper_bound:0.005 > bucket:<cumulative_count:0 upper_bound:0.01 > bucket:<cumulative_count:0 upper_bound:0.025 > bucket:<cumulative_count:0 upper_bound:0.05 > bucket:<cumulative_count:0 upper_bound:0.1 > bucket:<cumulative_count:156618 upper_bound:0.25 > bucket:<cumulative_count:1454767 upper_bound:0.5 > bucket:<cumulative_count:3740186 upper_bound:1 > bucket:<cumulative_count:4634844 upper_bound:2.5 > bucket:<cumulative_count:5051815 upper_bound:5 > bucket:<cumulative_count:5472476 upper_bound:10 > > } has a label named "method" whose value is not utf8: "0\x99\x94"

### Cilium Version

1.10.4

### Kernel Version

5.10

### Kubernetes Version

1.20.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
@yanhongchang thanks for the report. It looks like the metrics got mixed up on rendering a "method" which seems likely to be referring to an HTTP method. Do you know if this is reproducible by sending unusual HTTP traffic through Cilium with strange `METHOD` fields?

I think that the solution here should be that Cilium should sanitize such metric labels before storing them, and discard (or log) any metrics that cannot be rendered as utf8.

**Comment by yanhongchang** [comment]
> @yanhongchang thanks for the report. It looks like the metrics got mixed up on rendering a "method" which seems likely to be referring to an HTTP method. Do you know if this is reproducible by sending unusual HTTP traffic through Cilium with strange `METHOD` fields?
> 
> I think that the solution here should be that Cilium should sanitize such metric labels before storing them, and discard (or log) any metrics that cannot be rendered as utf8.

Sorry，I don't know how to repor it，when I found the problem, I rebuild the cilium-agent pod, and the metrics recover normal.
