### ISSUE TITLE
Cilium 1.13 complains about "UpdateIdentities: Updating an existing identity"

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#24401]
Seen in https://github.com/cilium/cilium/actions/runs/4431168886, check Cilium logs:

[cilium-sysdump-out.zip (32).zip](https://github.com/cilium/cilium/files/10985191/cilium-sysdump-out.zip.32.zip)

```
2023-03-15T21:47:56.617523931Z level=warning msg="UpdateIdentities: Updating an existing identity" identity=16777217 labels="[reserved:kube-apiserver]" labels(new)="[cidr:0.0.0.0/0 cidr:128.0.0.0/1 cidr:192.0.0.0/2 cidr:192.0.0.0/3 cidr:192.0.0.0/4 cidr:192.0.0.0/5 cidr:192.0.0.0/6 cidr:192.0.0.0/7 cidr:192.0.0.0/8 cidr:192.128.0.0/10 cidr:192.128.0.0/9 cidr:192.160.0.0/11 cidr:192.160.0.0/12 cidr:192.168.0.0/13 cidr:192.168.0.0/14 cidr:192.168.0.0/15 cidr:192.168.0.0/16 cidr:192.168.0.0/17 cidr:192.168.0.0/18 cidr:192.168.32.0/19 cidr:192.168.48.0/20 cidr:192.168.48.0/21 cidr:192.168.48.0/22 cidr:192.168.48.0/23 cidr:192.168.49.0/24 cidr:192.168.49.0/25 cidr:192.168.49.0/26 cidr:192.168.49.0/27 cidr:192.168.49.0/28 cidr:192.168.49.0/29 cidr:192.168.49.0/30 cidr:192.168.49.2/31 cidr:192.168.49.2/32 reserved:kube-apiserver reserved:world]" subsys=policy
```

It looks like Cilium is attempting to add `reserved:kube-apiserver` labels to an identity that already has that label, then complaining that it can't do it. Neither of these things are problems, so Cilium shouldn't warn about them.

**Comment by squeed** [comment]
Agreed, these error messages are not interesting.

https://github.com/cilium/cilium/blob/master/pkg/policy/selectorcache.go#L1030 is the line in question; the assumption that identities cannot change their labels is, due to the current metadata implementation, not correct.

**Comment by slayer321** [comment]
Hey @squeed , I did like to work on this issue.

**Comment by joestringer** [comment]
@slayer321 assigned to you, feel free to ask questions here or join Slack #development if you want to discuss an approach.

**Comment by giorio94** [comment]
Heads up that this log warning might not be that innocent. I've observed a few cases in which the above reported old and new labels were swapped (i.e., the new ones only included `reserved:kube-apiserver`), and since the old ones are then [blindly overwritten ](https://github.com/cilium/cilium/blob/5170939c5b76b50225bec1e400a86f06b1f95fbf/pkg/policy/selectorcache.go#L1045) it caused issues as the affected identities were not included in matching `cidr` selectors. I've still to fully understand what caused that though, and which cilium versions are affected.

```
level=warning msg="UpdateIdentities: Updating an existing identity" identity=16777218 labels="[cidr:0.0.0.0/0 cidr:0.0.0.0/1 cidr:0.0.0.0/2 cidr:0.0.0.0/3 cidr:0.0.0.0/4 cidr:10.0.0.0/10 cidr:10.0.0.0/11 cidr:10.0.0.0/12 cidr:10.0.0.0/13 cidr:10.0.0.0/14 cidr:10.0.0.0/7 cidr:10.0.0.0/8 cidr:10.0.0.0/9 cidr:10.2.0.0/15 cidr:10.2.0.0/16 cidr:10.2.0.0/17 cidr:10.2.0.0/18 cidr:10.2.0.0/19 cidr:10.2.0.0/20 cidr:10.2.0.0/21 cidr:10.2.0.0/22 cidr:10.2.0.0/23 cidr:10.2.0.0/24 cidr:10.2.0.0/25 cidr:10.2.0.0/26 cidr:10.2.0.0/27 cidr:10.2.0.0/28 cidr:10.2.0.0/29 cidr:10.2.0.4/30 cidr:10.2.0.6/31 cidr:10.2.0.6/32 cidr:8.0.0.0/5 cidr:8.0.0.0/6 reserved:kube-apiserver reserved:world]" labels(new)="[reserved:kube-apiserver]" subsys=policy`) 

$ cilium identity list
...
16777217   cidr:10.2.0.0/16
           reserved:world
16777218   cidr:10.2.0.6/32
           reserved:kube-apiserver
           reserved:world
16777219   cidr:10.2.1.121/32
           reserved:kube-apiserver
           reserved:world
16777223   cidr:10.2.2.213/32
           reserved:world
...

$ cilium policy selectors
...
{
"identities": [
    16777217,
    16777223
],
"selector": "LabelSelector{MatchLabels:map[string]string{cidr.10.2.0.0/16: ,},MatchExpressions:[]LabelSelectorRequirement{},}",
"users": 6
},
...
```

**Comment by christarazi** [comment]
@slayer321 It looks like https://github.com/cilium/cilium/pull/25241 will actually resolve this issue.

**Comment by giorio94** [comment]
I'm closing this issue, because #25241 got merged yesterday (it was not closed automatically as the target branch was a stable one).
