### ISSUE TITLE
Problem with hostNetwork sockets

### ISSUE THREAD

**Issue by RomanenkoDenys** [cilium/cilium#24417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Pod ingress-nginx working in hostNetwork has opened sockets to kube-dns.
```
netstat: can't scan /proc - are you root?
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 10.111.0.178:35765      10.111.0.247:5353       ESTABLISHED -
```
```
root@dev-master-0:~# kubectl -n kube-system get pods -o wide | grep kube-dns
d8-kube-dns-5f75bbc6d6-9sdqk                           2/2     Running   0              7m9s   10.111.0.173      dev-master-0                      <none>           <none>
d8-kube-dns-5f75bbc6d6-zjsn6                           2/2     Running   0              7m9s   10.111.0.247      dev-master-0                      <none>           <none>
```
If we restart kube-dns pods ip addresses of pods changes:
```
root@dev-master-0:~# kubectl -n kube-system delete pod d8-kube-dns-5f75bbc6d6-9sdqk d8-kube-dns-5f75bbc6d6-zjsn6
pod "d8-kube-dns-5f75bbc6d6-9sdqk" deleted
pod "d8-kube-dns-5f75bbc6d6-zjsn6" deleted
root@dev-master-0:~# kubectl -n kube-system get pods -o wide | grep kube-dns
d8-kube-dns-5f75bbc6d6-7gh8t                           2/2     Running   0              10s    10.111.1.250      dev-worker-6ce11b60-76fb8-29zwq   <none>           <none>
d8-kube-dns-5f75bbc6d6-vvphs                           2/2     Running   0              10s    10.111.4.28       dev-worker-6ce11b60-76fb8-q88fp   <none>           <none>
```

But socket in ingress-nginx pod does not change:
```
/ $ netstat -upn
netstat: can't scan /proc - are you root?
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 10.111.0.178:35765      10.111.0.247:5353       ESTABLISHED -
```
And nginx fails to resolve dns names.

When we use flannel as cni in the same cluster configuration, we do not have any issues and dns resolve works as expected.
Please give me some advice what to do in this case.

### Cilium Version

1.11.14 / 1.12.7

### Kernel Version

5.15.0-58-generic

### Kubernetes Version

1.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RomanenkoDenys** [comment]
Hey ! Yes, i will collect sysdump. We use kube-proxy-replacement. 
`10.111.0.247` is pod address.
Service address is `10.222.0.10`.
i think problem is connected to service resolve in cilium.
When we use flannel i see 10.222.0.10 in socket `Foreign Address`.

**Comment by RomanenkoDenys** [comment]
[cilium-sysdump-20230316-193832.zip](https://github.com/cilium/cilium/files/10995225/cilium-sysdump-20230316-193832.zip)

**Comment by aditighag** [comment]
The sysdump is incomplete. There are no cilium logs nor bugtool output.

**Comment by RomanenkoDenys** [comment]
@aditighag Hi
> The sysdump is incomplete. There are no cilium logs nor bugtool output.

Sorry, i collected new sysdump. https://drive.google.com/file/d/1Cb4TO2vi7ywIn64TEqwpO-fEYxWufRRD/view?usp=share_link (file is too big for github).

**Comment by RomanenkoDenys** [comment]
@aditighag Hi, did you have time to watch ?

**Comment by aditighag** [comment]
Based on the sysdump data, you are running into the limitation of socket-lb - https://github.com/cilium/cilium/issues/12859.

**Comment by RomanenkoDenys** [comment]
@aditighag thanks, i know this issue, but is there a plan to solve this problem ? https://github.com/cilium/cilium/issues/12859 was created almost 3 years ago and has no progress.

**Comment by aditighag** [comment]
You can monitor the issue for 1.14 updates.
