### ISSUE TITLE
Found two node IDs for the same node errors

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#24442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. restarted cilium-agent daemonsets in multiple clusters
2. agents in multiple clusters all complain about `Found two node IDs` for various `nodeName` but different node IDs

Seems it may just be nodes being deleted from clusters, not just agents restarting.

### Cilium Version

`Daemon: 1.12.8 87d8561 2023-03-15T19:28:16+01:00 go version go1.18.10 linux/amd64`

### Kernel Version

`Linux ip-10-206-123-81 5.15.0-1030-aws #34~20.04.1-Ubuntu SMP Tue Jan 24 15:16:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

### Relevant log output

```shell
`level=error msg="Found two node IDs (0 and 4176) for the same node" ipAddr=10.199.160.233 nodeName=ip-10-199-150-180.ec2.internal subsys=linux-datapath`
```

### Anything else?

Spot checking, it seems the nodeName being logged are for non-existent nodes so far

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
> Spot checking, it seems the nodeName being logged are for non-existent nodes so far

That makes sense because this error is printed while trying to deallocate a node ID, typically when a remote Kubernetes node was deleted.

A sysdump would help to figure this out. It would also be great if you had the Kubernetes Node object for a node for which this happened once deleted. So maybe taking two sysdumps: one before and one after a node deletion?

**Comment by pchaigno** [comment]
This may have been fixed by https://github.com/cilium/cilium/pull/25222, which will be released in the upcoming v1.12.10.

**Comment by pchaigno** [comment]
@dctrwatson Would you be able to share a sysdump?

**Comment by dctrwatson** [comment]
> @dctrwatson Would you be able to share a sysdump?

Unfortunately, I cannot share a full sysdump easily. If you tell me what parts you would like to see, I can share those though.

**Comment by pchaigno** [comment]
It's hard for me to describe what I want to see without digging through the sysdump and I'm not going to ask you for every file one by one. I think we'll leave it at that; maybe someone else from the community will be able to debug.

**Comment by mkilchhofer** [comment]
We also see this error message on mostly all our AWS EKS clusters with real workload on it:
![image](https://github.com/cilium/cilium/assets/7290987/6fca7d5f-f340-4ef5-800b-3d94af0f9c02)

On AWS EKS we use CNI chaining with [amazon-vpc-cni-k8s](https://github.com/aws/amazon-vpc-cni-k8s).

The same error message **does not appear on Azure AKS** where we use the bring-your-own CNI approach to ship Cilium.

The Policy Enforcement Mode we use on both AWS and Azure is `always`.

**Comment by rastislavs** [comment]
Looks like I hit this in CI: https://github.com/cilium/cilium/issues/26224

**Comment by alex-berger** [comment]
Same here with Cilium version 1.13.4.

**Comment by brb** [comment]
@alex-berger Could you provide a sysdump?

**Comment by alex-berger** [comment]
@brb I will try to get a sysdump. But, doing so I realized that, while I get quite some of those error messages per day, none of the affected nodes does still exist. So, I checked the Kubernetes audit logs and it looks like those errors appear whenever a node is deleted (removed from the cluster).

**Comment by kahirokunn** [comment]
I have the same error.

**Comment by brb** [comment]
It's very likely that the issue has been resolved by https://github.com/cilium/cilium/pull/27029. Please wait until next releases, and please report whether it is indeed the case.
