### ISSUE TITLE
Slack is not accessible.

### ISSUE THREAD

**Issue by Ji993** [cilium/cilium#24447]
Is it possible for the general public to join Cilium Slack channels or are they private ?

On your "Get Involved" page it says "For live conversation and quick questions, join the Cilium Slack workspace.", but the link doesn't work.

I have tried both of these links, but I am unable to access your Slack:
- https://cilium.herokuapp.com/
  Here I am getting an error from Heroku - An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details..."

- https://cilium.slack.com/
  This one seems to be invite-only or maybe I am wrong.

**Comment by youngnick** [comment]
There is an issue with `cilium.slack.com`, some Isovalent folks are working on it.

**Comment by xmulligan** [comment]
Thanks for reporting! It should be working again now. Let us know if you run into any more problems

**Comment by Ji993** [comment]
All good, got my invite via https://cilium.herokuapp.com. Thanks

**Comment by owais** [comment]
Looks like this might be broken again. Trying to get an invite since yesterday with multiple emails and haven't received one yet.

**Comment by fujitatomoya** [comment]
Hi, i have been having the similar error with https://cilium.slack.com/signup#/domain-signup? 

> The email address must match one of the domains listed below. Please try another email.

above comes up, even with my gmail.com... any thoughts?

**Comment by xmulligan** [comment]
@thebsdbox looks like it needs to be refreshed again 😅

**Comment by ozhankaraman** [comment]
yes, this is still not working atm

**Comment by NPastorale** [comment]
As of now, it is still returning this error:
> The email address must match one of the domains listed below. Please try another email.

When trying to join with an `@gmail.com` account.

**Comment by ozhankaraman** [comment]
Hi @NPastorale, I used the workaround described in this issue https://github.com/cilium/cilium/issues/29103 and it worked

**Comment by NPastorale** [comment]
Hi @ozhankaraman , unfortunately it is returning the same error
