### ISSUE TITLE
Visit pod no response

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#24454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. vip on node2
2. pod on node1
3. visit  vip:port on client， no response.
4. tcpdump on pod, src ip is 0.0.0.0?  Is this the bug reason?
![企业微信截图_16792815339625](https://user-images.githubusercontent.com/6076617/226274249-e6a0d64e-aacb-4555-a99f-c0ff8d4e8b6e.png)

### Cilium Version

cilium version
Client: 1.12.7 6719063 2023-02-13T09:31:05+01:00 go version go1.18.10 linux/amd64
Daemon: 1.12.7 6719063 2023-02-13T09:31:05+01:00 go version go1.18.10 linux/amd64

### Kernel Version

uname -a
Linux qfusion-node1 4.18.0-348.el8.x86_64 #1 SMP Tue Oct 19 15:14:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

no this command

### Anything else?

There is no error on harbor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by llhhbc** [comment]
cilium endpoint config 850
ConntrackAccounting               : Enabled
ConntrackLocal                    : Disabled
Debug                             : Enabled
DebugLB                           : Disabled
DebugPolicy                       : Enabled
DropNotification                  : Enabled
MonitorAggregationLevel           : None
PolicyAuditMode                   : Disabled
PolicyVerdictNotification         : Enabled
TraceNotification                 : Enabled

**Comment by youngnick** [comment]
Thanks for logging this issue @llhhbc.

Could you please gather a sysdump using https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection and add it to this issue?

Also, when you say "vip is on node2", how did you provision that vip?

**Comment by llhhbc** [comment]
I am use metallb to provision vip.  Our cilium version don't has sysdump command.

**Comment by llhhbc** [comment]
<img width="1835" alt="image" src="https://github.com/cilium/cilium/assets/6076617/102c377d-acc2-4be4-a8f8-ef3a09996b9d">
@youngnick

**Comment by youngnick** [comment]
Thanks @llhhbc, I can see what you're saying, and that _might_ be the answer, but we won't be able to tell without more information from the cluster. That's what the sysdump is for. The Cilium CLI is what has the sysdump command, so following the instructions on https://docs.cilium.io/en/stable/operations/troubleshooting/#reporting-a-problem should help you get one.

**Comment by llhhbc** [comment]
ok. I will upload dump info later.

**Comment by youngnick** [comment]
There should not be, no, aside from IP addresses.

**Comment by llhhbc** [comment]
OK

**Comment by llhhbc** [comment]
I found that sysdump will only export the information under kube-system. Our business pod is in another namespace. Do we need to add relevant parameters?

**Comment by llhhbc** [comment]
It occurs occasionally. After the last repair, it has not reappeared for the time being. You need to wait for the next time it reappears to dump
