### ISSUE TITLE
bpf.lbExternalClusterIP=true

### ISSUE THREAD

**Issue by kinbod** [cilium/cilium#24461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

bpf.lbExternalClusterIP=true doesn't work with kenel 4.18.0，rhel8.6  
It works in cluster internel, but when I add an ip route to out cluster then it can not get result with curl.

### Cilium Version

1.13.0

### Kernel Version

4.18.0

### Kubernetes Version

1.25.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
Please attach the sysdump.
