### ISSUE TITLE
Network Policy cannot work properly with ClusterIP CIDR

### ISSUE THREAD

**Issue by HeyZackWang** [cilium/cilium#24485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A deployment set Network policy Egress with ClusterIP CIDR 192.168.144.0/24 can not be connected using "ping"
"ping 192.168.144.106 stuck"
but when restarted Cilium Pod, it works expected

It's a 3 nodes cluster
SVC 192.168.144.106:
![image](https://user-images.githubusercontent.com/11372882/226511829-8facba81-af0b-46b2-ab5e-3c9edae1fe4d.png)
Pod:
![image](https://user-images.githubusercontent.com/11372882/226512264-b416ecda-d3b6-4b8d-bf83-122634aa976c.png)

NetworkPolicy 192.168.144.0/24:
![image](https://user-images.githubusercontent.com/11372882/226511953-be710afe-4045-4cc2-a976-10dd1ca924c9.png)
![image](https://user-images.githubusercontent.com/11372882/226512947-c4ae210c-c6b3-42b5-9c44-47cb6d6e53d2.png)

Ping Stuck:
![image](https://user-images.githubusercontent.com/11372882/226512073-5e1999e9-8fe6-4976-a3d2-d62c4cdf88bb.png)

Now, Restart Cilium Pod, Ping works fine.
![image](https://user-images.githubusercontent.com/11372882/226512511-137d94e3-1530-4a3a-9f37-29bd14444c33.png)
![image](https://user-images.githubusercontent.com/11372882/226514077-ed82d4e6-6e71-4ad0-84ec-96b2d913a5de.png)
See, worked:
![image](https://user-images.githubusercontent.com/11372882/226512559-c218b4b3-3a30-4fc4-ba8f-b7601e389d31.png)

### Cilium Version

Cilium Version: v1.12.3
![image](https://user-images.githubusercontent.com/11372882/226513048-8548079a-08d9-436f-8bb1-5c058783962c.png)

### Kernel Version

uname -r: 4.19.91

### Kubernetes Version

Kubernetes:              Ok   1.19 (v1.19.7) [linux/amd64]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xujunjie-cover** [comment]
Ipvs in your cluster?

**Comment by wangze83** [comment]
Yes.

IP Virtual Server version 1.2.1

 

From: ***@***.***> on behalf of xujunjie-cover ***@***.***>
Reply-To: cilium/cilium ***@***.***>
Date: Friday, March 24, 2023 at 01:37
To: cilium/cilium ***@***.***>
Cc: Wzzzz ***@***.***>, Author ***@***.***>
Subject: Re: [cilium/cilium] Network Policy cannot work properly with ClusterIP CIDR (Issue #24485)

 

Ipvs in your cluster?

**Comment by wangze83** [comment]
Used Ipvs in the cluster
IP Virtual Server version 1.2.1

**Comment by xujunjie-cover** [comment]
please have a test, try to  reping the vip；I guess after restart, socket has beed est between pod and ipvs.

**Comment by wangze83** [comment]
> please have a test, try to reping the vip；I guess after restart, socket has beed est between pod and ipvs.

Yes, exactly
“Restart Cilium Pod, Ping works fine.”
Let me do the test again:

kubectl get NetworkPolicy -n gjf-qa2 -o yaml networkpolicy-gjf-app-gjf-test-x
![image](https://user-images.githubusercontent.com/11372882/230289488-724047e5-4acb-4923-9e14-0ef2c3a434ff.png)

kubectl get pod -n gjf-qa2 -l app=gjf-app-gjf-test,nonce=x,stark-app=gjf-app,stark-ns=gjf-qa2
![image](https://user-images.githubusercontent.com/11372882/230289800-d1c937a9-7bb7-4a37-ac7a-1f59850b293b.png)

kubectl get svc -n gjf-qa2 gjf-app-abc
![image](https://user-images.githubusercontent.com/11372882/230290150-84899dc6-1c5e-47ff-92b7-10727311f0ad.png)


Enter Pod and 'ping' stuck:
![image](https://user-images.githubusercontent.com/11372882/230290240-1df06724-2b18-4940-950c-c4984369032f.png)

Look at the bpf policy Now:
![image](https://user-images.githubusercontent.com/11372882/230290322-632944ca-1fcf-4d22-96a3-9b7973559656.png)

Now, Restart Cilium Pod:
![image](https://user-images.githubusercontent.com/11372882/230290983-35652e93-8387-4554-8744-40b006122441.png)

ping worked:
![image](https://user-images.githubusercontent.com/11372882/230291075-5fe00e32-d46e-4d5d-a785-492a23337ad5.png)

Look at the bpf policy now:
![image](https://user-images.githubusercontent.com/11372882/230291438-96d0a5f1-fbd7-4ac0-b253-99ab2465c051.png)

**Comment by joestringer** [comment]
Cilium performs Service translation before applying network policy. As such, any network policy must consider the backends. For backends that are pods, using K8s netpol `podSelector` statements or Cilium NetworkPolicy endpointSelectors is the recommended path. For peers that are not k8s pods, the recommended path is to use the backend IP addresses rather than the service addresses.

**Comment by christarazi** [comment]
If the above has resolved your issue with policies, please close the issue.
