### ISSUE TITLE
CFP: I would like to have an option to transfer only the specified weight to remote in global service.

### ISSUE THREAD

**Issue by kahirokunn** [cilium/cilium#24494]
## Cilium Feature Proposal

Currently, if you want to forward a specified percentage of traffic to remote, you have to devise a way to do so by placing envoy in front of global service.
I would like to have an option to transfer only the specified weight to remote in global service.

**Is your feature request related to a problem?**

Many OSS and Cilium's Global Service are incompatible.
Cilium's Global Service does not create an Endpoint object for the Remote pod, so it will not work with many OSS Proxies that require an Endpoint object.

**Describe the feature you'd like**

I want to forward a specified percentage of traffic to the REMOTE cluster via Global Service.

**(Optional) Describe your proposed solution**

I would like to have an option to transfer only the specified weight to remote in global service.

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
Keep

**Comment by giorio94** [comment]
Hi @kahirokunn 

> Cilium's Global Service does not create an Endpoint object for the Remote pod, so it will not work with many OSS Proxies that require an Endpoint object.

Just a note that, starting from Cilium v1.16, it is possible to enable endpointslice synchronization for global services: https://docs.cilium.io/en/latest/network/clustermesh/services/#synchronizing-kubernetes-endpointslice-beta. 

Is that enough for your use-case?

**Comment by kahirokunn** [comment]
@giorio94 
Yes, that is more than sufficient! This is absolutely fantastic! Thank you so much!
