### ISSUE TITLE
CI: IntegrationTests: ClusterMeshTestSuite.TestWatchConfigDirectory: timeout while waiting for changed event

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#24491]
Observed in https://github.com/cilium/cilium/actions/runs/4471325368/jobs/7856059453?pr=24477

```
----------------------------------------------------------------------
FAIL: config_test.go:69: ClusterMeshTestSuite.TestWatchConfigDirectory

config_test.go:178:
    expectChange(c, cm, "cluster2")
config_test.go:46:
    c.Fatal("timeout while waiting for changed event")
... Error: timeout while waiting for changed event
```

[logs_1265704.zip](https://github.com/cilium/cilium/files/11026575/logs_1265704.zip)

**Comment by sayboras** [comment]
one more here https://github.com/cilium/cilium/actions/runs/4574123785/jobs/8075367376?pr=24649

**Comment by pchaigno** [comment]
@giorio94 Are you looking into this?

**Comment by giorio94** [comment]
> @giorio94 Are you looking into this?

Yes, and I've a fix almost ready. I'll open a PR shortly.

**Comment by giorio94** [comment]
The PR with the fix is open: https://github.com/cilium/cilium/pull/24993
