### ISSUE TITLE
Create CI test for node-local-dns with LRP

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#24508]
This is a follow up item from #24230 , we need to add a CI test to cover node-local-dns use case, need to check:
- DNS traffic correctly hits node-cache (incrementing its counter) and getting resolved
- Traffic between client pod and node-cache is NOT tracked in kernel conntrack table

**Comment by aditighag** [comment]
Slack messages roll over, so copy pasting the messages here - 

We can add a new test to the suite in cilium-cli - https://github.com/cilium/cilium-cli/tree/main/connectivity/tests. We could use the same test pods deployed in the [guide](https://docs.cilium.io/en/v1.13/network/kubernetes/local-redirect-policy/#node-local-dns-cache). We would have to add the lrp feature flag detection - https://github.com/cilium/cilium-cli/blob/main/connectivity/check/features.go.

@Weil0ng We discussed having a plan of action on the original linked PR - https://github.com/cilium/cilium/pull/24230#issuecomment-1470724579. Given the PR was merged with the expectation that we'll add CI coverage in 1.14. Feel free to follow-up on the Slack thread or here in case you have any questions regarding the test framework before getting started.

**Comment by aditighag** [comment]
Closing in lieu of - https://github.com/cilium/cilium/issues/33415.
