### ISSUE TITLE
Deprecate CNPStatusUpdates and K8sEventHandover

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#24503]
The logic for CNPStatusUpdates/K8sEventHandover is spread all over the Cilium repository:
- operator has GC for node status updates
- agent needs to update statuses
- logic for migrating events from CRD to kvstore
- additional logic when policies are created/updated

Taking into account that:
- This feature puts significant performance/scalability limitations and should not even be used for debugging purposes.
- Is disabled by default since Cilium 1.8

I propose we deprecate it and remove it in 1,15 Cilium.

**Comment by aanm** [comment]
K8s introduced KubernetesNetworkPolicy Status, maybe we shouldn't deprecate CNPStatusUpdates but give the same usage has we should have with KNPStatus?

**Comment by marseel** [comment]
> K8s introduced KubernetesNetworkPolicy Status, maybe we shouldn't deprecate CNPStatusUpdates but give the same usage has we should have with KNPStatus?

I am ok with better implementation for statuses for CNPs, but taking into account the current implementation - I think it makes sense to deprecate the current implementation, remove it and then implement new status that can be enabled by default. 

So what is left for this ticket is to remove the old implementation in 1.15.

**Comment by marseel** [comment]
I will close this issue as these two options have been deprecated.
I've created an issue with follow-ups for 1.16 with further cleanups: https://github.com/cilium/cilium/issues/29590
