### ISSUE TITLE
CFP: Fix Ingress traffic interactions with other Policy enforcement

### ISSUE THREAD

**Issue by youngnick** [cilium/cilium#24536]
## Background

Currently, Cilium's Ingress support has implications when interacting with other Policies that are a bit surprising and aren't well explained.

When traffic arrives at the per-node Envoy from _outside_ the cluster (in Cilium identity speak, it has a _world_ identity) to a listener created by Cilium's Ingress (or Gateway API) support, it picks up the special _ingress_ identity during its routing through Envoy. This identity can then interact with Network Policy (whether they are CiliumNetworkPolicy or ClusterWideCiliumNetworkPolicy) by being used in an ingress or egress policy.

> **Note**
> Yes, the fact that traffic coming into the cluster is called ingress, as well as traffic going _to_ an identity is confusing. This term overloading has come from two different directions and is tricky to fix. In this issue, `Ingress` means the Kubernetes resource `Ingress`, and other uses will be disambiguated with a modifier like "ingress identity", "ingress policy", or "ingress traffic".

However, when traffic arrives at the per-node Envoy from _inside_ the cluster, _and_ is bound for an ingress listener, the original security identity is maintained. This is because Cilium's Ingress support is built on our Layer 7 Policy support, and uses the same Envoys. This means that if users wish to have _in-cluster_ workloads talk to the "outside" of their Ingress or Gateway API listeners _and_ have Network Policy that restricts traffic between workloads, they may need to allow an unintendedly large amount of traffic in a Network Policy.

This has been the cause of some confusion and outages with a number of Cilium users, and the number will only grow as more people use Cilium's Ingress and Gateway API support.

In an old-school, physical network, that had a dedicated firewall device listening on certain open ports on an internet connection, this type of connection was called "hairpinning" (like a hairpin turn on a racetrack), and had a series of special options.

In Cilium's case, fully supporting Ingress hairpinning could safely have internal traffic pick up the _ingress_ identity, because the Ingress and Gateway API listeners are effectively performing some Policy enforcement themselves. This is because both Ingress and Gateway API will only route _requested_ traffic to their defined backends - they are effectively an allowlist for very specific Layer 7 traffic when passing through the per-node Envoys.

## Proposed changes

This CFP proposes two changes:
- [ ] Firstly, _all_ traffic passing through an Ingress or Gateway API listener should assume the _ingress_ identity. This includes traffic originating inside the cluster, and will mean that traffic from inside will _lose_ its internal identity. This is hairpinning for internal traffic.
- [ ] Secondly, the documentation will be updated to call out this interaction, and make it clear that by having traffic originating from inside the cluster go to an Ingress listener, it's _logically_ "leaving" the cluster and becoming _ingress_ identity traffic instead.

**Comment by sayboras** [comment]
One of the acceptance criteria is to add the connectivity test with and without reserved:ingress identity. 

https://github.com/cilium/cilium/issues/24536
> Add Ingress test with reserved:ingress policy to cilium/cilium-cli connectivity test suite

**Comment by sayboras** [comment]
The connectivity tests are done as part of https://github.com/cilium/cilium-cli/pull/1533
