### ISSUE TITLE
Report BPF helper return code for CT map insertion failure

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#24530]
We should report the exact kernel-side error when we fail to update the CT map (`CT: Map insertion failed`). We can do that via the `ext_err` field.

We however need to wait for https://github.com/cilium/cilium/pull/24410 to be merged, to be able to use that field. Without that PR, the field is used to pass the auth_type in some cases (policy_can_access).

**Comment by margamanterola** [comment]
This was already fix in https://github.com/cilium/cilium/pull/24716 🎉
