### ISSUE TITLE
NodePort NAT egress doesn't use the full available local port rage for source ports.

### ISSUE THREAD

**Issue by tsukada-ascade** [cilium/cilium#24555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi experts,
I'm trying to benchmark emqx broker concurrent connections. The emqx broker has replicas of 1 and NodePort 31883 to make the service accessible outside of k8s.

When I run 60,000 Connect Benchmark using [emqtt-bench](https://github.com/emqx/emqtt-bench), an error occurs around 32,767 connections.

```
$ ./emqtt_bench conn -c 60000 -i 1 -h 192.168.100.12 -p 31883
Start with 4 workers, addrs pool size: 1 and req interval: 4 ms

1s connect_succ total=791 rate=783.94/sec
2s connect_succ total=1587 rate=796.00/sec
3s connect_succ total=2383 rate=796.00/sec
[...]
49s connect_succ total=32759 rate=16.05/sec
50s connect_succ total=32765 rate=5.98/sec
51s connect_succ total=32767 rate=1.99/sec
client(10784): connect error - timeout
client(10784): EXIT for {shutdown,timeout}
```

The ip_local_port_range of the node running benchmark has already expanded.
```
$ cat /proc/sys/net/ipv4/ip_local_port_range
1025    65534
```

Looking at strace, it seemed that connect(2) on the mqtt client side had an error with EINPROGRESS.
```
1392467 16:15:48.306996 connect(18, {sa_family=AF_INET, sin_port=htons(31883), sin_addr=inet_addr("192.168.100.12")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

Observing with `hubble observe -t drop` on the node(192.168.100.12) specified in NodePort, it is dropped as `No mapping for NAT masquerade`.
```
root@adams-master-1:/home/cilium# hubble observe -t drop -f
Mar  6 04:09:38.704: 192.168.100.26:30478 (world) <> tmc-iot/emqx-0:1883 (ID:66669) No mapping for NAT masquerade DROPPED (TCP Flags: SYN)
Mar  6 04:09:39.756: 192.168.100.26:30478 (world) <> tmc-iot/emqx-0:1883 (ID:66669) No mapping for NAT masquerade DROPPED (TCP Flags: SYN)
Mar  6 04:09:41.804: 192.168.100.26:30478 (world) <> tmc-iot/emqx-0:1883 (ID:66669) No mapping for NAT masquerade DROPPED (TCP Flags: SYN)
Mar  6 04:09:45.836: 192.168.100.26:30478 (world) <> tmc-iot/emqx-0:1883 (ID:66669) No mapping for NAT masquerade DROPPED (TCP Flags: SYN)
```

When I ran the same 60,000 benchmark with CNI changed from cilium to flannel, I was able to exceed 32,767. However, a similar error occurred around 64,500 cons. I'm assuming this is a NAT limit on the number of concurrent sessions.

I would like to know why 32,767 is the upper limit in the case of cilium.

### Cilium Version

```
Client: 1.13.0 c9723a8d 2023-02-15T14:18:31+01:00 go version go1.19.6 linux/amd64
Daemon: 1.13.0 c9723a8d 2023-02-15T14:18:31+01:00 go version go1.19.6 linux/amd64
```

### Kernel Version

```
Linux adams-master-1 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

v1.26.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
It looks like it uses the [NodePort range](https://github.com/cilium/cilium/blob/6f48ae80838a1dedf8026868e97bb2e33f7ea49f/bpf/lib/nodeport.h#L1713) as a source port range, instead of ip_local_port_range.
