### ISSUE TITLE
kubectl delete cilium agent hangs all the network

### ISSUE THREAD

**Issue by jpm38** [cilium/cilium#24563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've deployed cilium on a kubernetes cluster of 3 masters and 4 workers using helm chart
When I try to uninstall cilium using "helm uninstall" the command des not return and all the network is stuck.
I must reboot all the  nodes to recover a normal behavior.

So, I've tried to delete only on pod agent and got the same result, lost my connection and no more access to my cluster nodes.

The expected behavior, in my opinion is that the pod is restarted.

Issue also with the rollout restart:
[root@apoc1 (APOC) ~]# kubectl rollout status ds cilium -n kube-system
Waiting for daemon set "cilium" rollout to finish: 0 out of 7 new pods have been updated...

**Logs of a cilium-agent pod being deleted:**

level=error msg="Interrupt received" subsys=hive
level=info msg="Shutting down... " subsys=daemon
level=info msg="Stopping fswatcher" config=tls-server subsys=hubble
level=info msg="Stopped serving cilium API at unix:///var/run/cilium/cilium.sock" subsys=daemon
level=info msg="Shutting down... " subsys=health-server
level=info msg="Waiting for all endpoints' go routines to be stopped." subsys=daemon
level=error msg="Failed to start the tcp DNS proxy on [::]:42775" error="accept tcp [::]:42775: use of closed network connection" subsys=fqdn/dnsproxy
level=info msg="Stopped serving cilium health API at unix:///var/run/cilium/health.sock" subsys=health-server
level=error msg="Failed to start the udp DNS proxy on [::]:42775" error="read udp [::]:42775: use of closed network connection" subsys=fqdn/dnsproxy
level=info msg="All endpoints' goroutines stopped." subsys=daemon
level=info msg="Stop hook executed" duration=20.383377ms function="cmd.newDaemonPromise.func2 (daemon_main.go:1701)" subsys=hive
level=info msg="Stop hook executed" duration="12.828µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumNode].Stop" subsys=hive
level=info msg="Stop hook executed" duration="6.543µs" function="*resource.resource[*k8s.io/api/core/v1.Node].Stop" subsys=hive
level=info msg="Stop hook executed" duration="34.609µs" function="client.(*compositeClientset).onStop" subsys=hive
level=info msg="Stopped gops server" address="127.0.0.1:9890" subsys=gops
level=info msg="Stop hook executed" duration="10.807µs" function="gops.registerGopsHooks.func2 (cell.go:51)" subsys=hive

### Cilium Version

v1.13.0

### Kernel Version
RHEL 8.7
4.18.0-425.13.1.el8_7.x86_64

### Kubernetes Version

1.24.10

### Sysdump

not applicable

### Anything else?

[cilium.txt](https://github.com/cilium/cilium/files/11065934/cilium.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jpm38** [comment]
I've tested with cilium 1.13.1 and it works fine.
So seems to be a bug that has been solved in 1.13.1 release.
closing the issue.

**Comment by danielmorlock** [comment]
We are experiencing the same issue with 1.13.1: Whenever Cilium is restarted, the network on the node gets stuck. We even't can't ping any host from any network != 127.0.0.1. 
 At the moment, restarting the Node is the only way to get the network back working.

**Comment by rabbagliettiandrea** [comment]
+1

**Comment by rabbagliettiandrea** [comment]
> I've tested with cilium 1.13.1 and it works fine. So seems to be a bug that has been solved in 1.13.1 release. closing the issue.

@jpm38 could please re-open?

**Comment by rabbagliettiandrea** [comment]
@danielmorlock if you're using K3s, this should fix: https://github.com/k3s-io/k3s/compare/master...rabbagliettiandrea:k3s:patch-1 please let me know if helps :)
