### ISSUE TITLE
Cilium Operator doesn't fully reconcile CiliumEndpointSlices on startup

### ISSUE THREAD

**Issue by alan-kut** [cilium/cilium#24581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cluster with Cilium Endpoint Slices enabled with identity based batching.
Label on namespace was changed. It led to change of identities for Cilium Endpoints in this namespace - Cilium Endpoints were updated with new identity.
Operator moved the endpoints from one slice to another.

First operator queued the insert of the cep to the new ces.
Then, delayed, operator queued the removed of the old cep from the old ces.
Operator crashed after inserting, before removing.

The old cep was never removed from the old ces.

In general there is no reconciliation of Cilium Endpoint Slices. If for some reason the state becomes bad it stays that way. In this particular case it should be enough to have full reconciliation during startup. 

### Cilium Version

all

### Kernel Version

all

### Kubernetes Version

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alan-kut** [comment]
I think it should be sig/operator

**Comment by christarazi** [comment]
Are you working on this @alan-kut? If so, please assign yourself.

**Comment by alan-kut** [comment]
I'm working on it. Draft PR is ready: https://github.com/cilium/cilium/pull/26836

**Comment by alan-kut** [comment]
\assign @alan-kut
