### ISSUE TITLE
cilium 1.13.x in conjunction with metallb doesn't deploy

### ISSUE THREAD

**Issue by xinity** [cilium/cilium#24593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

cilium release 1.13.x doesn't go well (meaning doesn't work at all) when used in conjunction with metallb (tested with 0.13.7 and 0.13.9)

In a nutshell, cilium starts and after several minutes, cilium gets deleted and metallb starts.
The setup cilium with metallb was perfectly working with cilium version 1.12.X whatever the version of metallb used (0.13.7 or 0.13.9)

### Cilium Version

1.13.0 
1.13.1

### Kernel Version

5.15.0-1025-raspi

### Kubernetes Version

v1.26.2+k0s

### Sysdump

[N/A]

### Anything else?

i've recored an asciinema video where we can observe what's really happening): https://asciinema.org/a/UhKGA26t2WgaBfGQJDQX2nlLA

the cilium values used can be found here: https://gist.github.com/xinity/cb80dae4e735b7b4ab0e1826f7e2213a

the full k0s cluster config can be found here: https://gist.github.com/xinity/c800f2186d5e81dfaad7f47f31b422a3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xinity** [comment]
**update**: tested with kubevip instead of metallb and everything works fine !
so i can confirm there is an issue between cilium and metallb :(

**Comment by julianwiedmann** [comment]
Hi, thanks for reporting this issue!

For initial triage, can you please elaborate on "doesn't work at all" - what symptoms are you seeing, which functionality isn't behaving as expected etc. Was the same setup working previously, and if so which on which Cilium release?

**Comment by xinity** [comment]
@julianwiedmann i’ve updated the issue feel free to look at the asciinema recording shared :)

**Comment by dylandreimerink** [comment]
From what I can tell looking at the asciinema is that Cilium initially appears to run fine, and then something causes the pods to terminate, as if the helm chart was removed. I do not understand how something like that could be caused by Cilium itself. I am not familiar with k0s, so I do not know how this is supposed to work, but I seems more likely to me that the orchestration is to blame here for whatever reason.
