### ISSUE TITLE
Make authed-flows visible in Hubble

### ISSUE THREAD

**Issue by meyskens** [cilium/cilium#24598]
Part of https://github.com/cilium/cilium/issues/22215 

A way should be added to signal to Hubble if a packet flow was authorized by an auth type to make it visible to both our test suite and the user in Hubble that a packet was authorized by something like mutual auth. 

Ideally there should be some way to indicate that a flow is encrypted as well.

**Comment by meyskens** [comment]
Changes to do this:

CLI: https://github.com/cilium/hubble/pull/1099
UI: https://github.com/cilium/hubble-ui/pull/568

**Comment by youngnick** [comment]
This is now complete, and available. Nice work @meyskens!
