### ISSUE TITLE
Cilium ingress updating CiliumEnvoyConfig failed

### ISSUE THREAD

**Issue by jonasz-lasut** [cilium/cilium#24595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium fails to update CiliumEnvoyConfig object when kubernetes objects are deleted by ArgoCD, which leads to not working ingress.

### Cilium Version

cilium-cli: v0.13.0 compiled with go1.20 on linux/amd64
cilium image (default): v1.13.0
cilium image (stable): v1.13.1
cilium image (running): v1.13.1

### Kernel Version

Linux <HOST> 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Fri Sep 2 16:07:40 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.7+k3s1", GitCommit:"f7c20e237d0ad0eae83c1ce60d490da70dbddc0e", GitTreeState:"clean", BuildDate:"2023-03-10T22:16:07Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump
Added link to google drive, file over 30MB
https://drive.google.com/file/d/1kC2UAqhXF6ibe2JWLEZSz2_AsZgtLweP/view?usp=sharing

### Relevant log output

```shell
level=info msg="LB-IPAM initializing" subsys=lbipam
level=info msg="Notify ingress controller for service ingress" subsys=ingress-controller
level=info msg="LB-IPAM done initializing" subsys=lbipam
level=error msg="Failed to process Ingress event, skipping: {ingress:0xc00129cf00}" subsys=ingress-controller
level=error msg="Failed to process Ingress event, skipping: {oldIngress:0xc00129cf00 newIngress:0xc001146b00}" subsys=ingress-controller
level=error msg="Failed to process Ingress event, skipping: {ingress:0xc0011e5000}" subsys=ingress-controller
level=error msg="Failed to process Ingress event, skipping: {oldIngress:0xc0011e5000 newIngress:0xc000ab3700}" subsys=ingress-controller
level=error msg="Failed to update CiliumEnvoyConfig for ingress" error="Operation cannot be fulfilled on ciliumenvoyconfigs.cilium.io \"cilium-ingress\": the object has been modified; please apply your changes to the latest version and try again" subsys=ingress-controller
level=warning msg="Failed to create CiliumEnvoyConfig" error="Operation cannot be fulfilled on ciliumenvoyconfigs.cilium.io \"cilium-ingress\": the object has been modified; please apply your changes to the latest version and try again" subsys=ingress-controller
level=error msg="Failed to process Ingress event, skipping: {ingress:0xc000a83f00}" subsys=ingress-controller
level=error msg="Failed to process Ingress event, skipping: {oldIngress:0xc00129c000 newIngress:0xc00129d800}" subsys=ingress-controller
level=error msg="Failed to process Ingress event, skipping: {ingress:0xc00129c000}" subsys=ingress-controller
level=error msg="Failed to process Ingress event, skipping: {oldIngress:0xc000a83f00 newIngress:0xc0012ad400}" subsys=ingress-controller
level=error msg="Failed to update CiliumEnvoyConfig for ingress" error="Operation cannot be fulfilled on ciliumenvoyconfigs.cilium.io \"cilium-ingress\": the object has been modified; please apply your changes to the latest version and try again" subsys=ingress-controller
level=warning msg="Failed to create CiliumEnvoyConfig" error="Operation cannot be fulfilled on ciliumenvoyconfigs.cilium.io \"cilium-ingress\": the object has been modified; please apply your changes to the latest version and try again" subsys=ingress-controller
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@jonasz-lasut have you looked at https://github.com/cilium/cilium/issues/17349 to see if it helps? Thank you
