### ISSUE TITLE
Running cilium on a different network segment fails

### ISSUE THREAD

**Issue by squidward05** [cilium/cilium#24618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to run cilium on a different network segment but it failed. I have a running network segment of 192.168.110.0, and a new node is added to a network segment of 192.168.120.0, and cilium has the following error,
I used the following helm values

```
    kubeProxyReplacement: strict
    k8sServiceHost: 192.168.110.140
    k8sServicePort: 6443
    nativeRoutingCIDR: 10.42.0.0/16
    autoDirectNodeRoutes: true
    tunnel: disabled
    bpf:
      masquerade: true
      preallocateMaps: true
```

### Cilium Version

Client: 1.11.5 b0d3140 2022-05-10T02:47:42+02:00 go version go1.17.9 linux/amd64
Daemon: 1.11.5 b0d3140 2022-05-10T02:47:42+02:00 go version go1.17.9 linux/amd64

### Kernel Version

Linux IU76-uat-worker3 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2+rke2r1", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-17T16:04:41Z", GoVersion:"go1.18.3b7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2+rke2r1", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-17T16:04:41Z", GoVersion:"go1.18.3b7", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230329-121806.zip](https://github.com/cilium/cilium/files/11096569/cilium-sysdump-20230329-121806.zip)

### Relevant log output

```shell
level=info msg="Processing API request with rate limiter" name=endpoint-delete parallelRequests=85 subsys=rate uuid=43078c91-3c4b-4537-8fba-564307b84861
level=info msg="API request released by rate limiter" name=endpoint-delete parallelRequests=85 subsys=rate uuid=43078c91-3c4b-4537-8fba-564307b84861 waitDurationTotal="59.795µs"
level=info msg="API call has been processed" error="endpoint not found" name=endpoint-delete processingDuration="2.896µs" subsys=rate totalDuration="73.514µs" uuid=43078c91-3c4b-4537-8fba-564307b84861 waitDurationTotal="59.795µs"
level=info msg="Processing API request with rate limiter" name=endpoint-delete parallelRequests=85 subsys=rate uuid=3baf3978-27d7-4caa-a1da-b9e6c2b35a17
level=info msg="API request released by rate limiter" name=endpoint-delete parallelRequests=85 subsys=rate uuid=3baf3978-27d7-4caa-a1da-b9e6c2b35a17 waitDurationTotal="44.344µs"
level=info msg="API call has been processed" error="endpoint not found" name=endpoint-delete processingDuration="2.746µs" subsys=rate totalDuration="60.382µs" uuid=3baf3978-27d7-4caa-a1da-b9e6c2b35a17 waitDurationTotal="44.344µs"
level=warning msg=" Unable to install direct node route {Ifindex: 0 Dst: 10.42.1.0/24 Src: <nil> Gw: 192.168.110.137 Flags: [] Table: 0 Realm: 0}" error="route to destination 192.168.110.137 contains gateway 192.168.120.254, must be directly reachable" subsys=linux-datapath
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Hi! Have you looked at https://docs.cilium.io/en/v1.13/network/concepts/routing/#id3 already?

> If all nodes share a single L2 network, then this can be taken care of by enabling the option auto-direct-node-routes: true. Otherwise, an additional system component such as a BGP daemon must be run to distribute the routes.

**Comment by hyt05** [comment]
> 你好！你看过https://docs.cilium.io/en/v1.13/network/concepts/routing/#id3了吗？
> 
> > 如果所有节点共享一个 L2 网络，那么可以通过启用选项 auto-direct-node-routes: true 来解决这个问题。否则，必须运行额外的系统组件（例如 BGP 守护程序）来分发路由。

sorry for my oversight
