### ISSUE TITLE
Cilium v1.13.1 suspected memory leak 

### ISSUE THREAD

**Issue by joakimstrandberg** [cilium/cilium#24634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We upgraded cilium from 1.13.0 to 1.13.1 using the helm chart and noticed that some of the cilium agents started to consume a lot of memory. We are running cilium in AKS with following configuration: BYOCNI, Encapsulation, Cluster Pool, Kubernetes CRD

Plotting the prometheus query 
```
sum by (pod) (cilium_process_resident_memory_bytes)/1024/1024
```
shows this increasing memory consumption for some of the agent pods.

![Screenshot 2023-03-28 at 15 13 59](https://user-images.githubusercontent.com/43732262/228249218-71c8cae7-45c4-4e66-85ae-20ed32847f98.png)

We also noticed that cilium agents experienced a high number of restarts after the upgrade, as shown with
```
sum by (pod) ((kube_pod_container_status_restarts_total{container="cilium-agent"}))
```

![Screenshot 2023-03-28 at 15 37 16](https://user-images.githubusercontent.com/43732262/228255345-1de90962-bd06-49fa-a314-29c887447386.png)

and we were prompted this error when trying to restart other pods (non-cilium-agent pods):
```
Warning  FailedCreatePodSandBox  7s (x3 over 60s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "89b0f6e4ffb605c6378647d6e15003c7b2906ec5e2f03ed45614f1f000e581de": plugin type="cilium-cni" name="cilium" failed (add): Unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests
```

When plotting 
```
sum by(method, path, return_code) (rate(cilium_agent_api_process_time_seconds_sum{method="PUT"}[1m]))
/
sum by(method, path, return_code) (rate(cilium_agent_api_process_time_seconds_count{method="PUT"}[1m]))
```

we could also see `PUT /v1/endpoint` timing out at 15s with return code 429.

![Screenshot 2023-03-28 at 16 00 45](https://user-images.githubusercontent.com/43732262/228262842-ec254773-db01-453d-8d48-8ab216c8cb0d.png)

### Cilium Version

1.13.1

### Kernel Version

5.4.0-1104-azure

### Kubernetes Version

v1.23.15

### Anything else?

Only experienced issues for cilium agents running on nodes where `CiliumNetworkPolicies` were applied. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@joakimstrandberg can you provide a sysdump? Thank you

**Comment by joakimstrandberg** [comment]
@aanm unfortunately I can not, since it contains sensitive data. Can you pin point which parts you are interested in so that I can remove any data if necessary?

**Comment by aanm** [comment]
@joakimstrandberg I'm interested in the gops mem heap file for the agents consuming a lot of memory.

**Comment by joakimstrandberg** [comment]
[gops-files-rr4bp.zip](https://github.com/cilium/cilium/files/11136526/gops-files-rr4bp.zip)

Attached files are for this agent:
<img width="1329" alt="Screenshot 2023-04-03 at 10 49 36" src="https://user-images.githubusercontent.com/43732262/229468660-e40c2b69-d6c2-4bad-b2bf-d318c86688ce.png">
Graph showing `cilium_process_resident_memory_bytes` in MB

**Comment by aanm** [comment]
@joakimstrandberg sorry I should have been more clear. I need the pprof-heap that is inside the sysdump. Thank you

**Comment by aanm** [comment]
> @aanm I am not too familiar with this file and do not want to share any sensitive data. Are there any commands I can use to extract specific information you would be interested in from the file and post here?

@joakimstrandberg that file contains the memory usage of a cilium agent which would be necessary to debug the memory leak.

**Comment by aanm** [comment]
@joakimstrandberg can you send me the pprof-heap file? Thank you

**Comment by aanm** [comment]
@joakimstrandberg thank you for that graph, as you can see, that graph only shows "322.89MB of memory used". Do you have an agent with more memory being used?

**Comment by joakimstrandberg** [comment]
@aanm Unfortunately I dont't have any agent using more memory at the time the sysdump was done. But when comparing it with agent that had no problems, there is some difference:
![cmtzr-heap](https://user-images.githubusercontent.com/43732262/234498491-c0937ca6-c11c-4b09-b1f2-1b3fee7946e4.svg)
