### ISSUE TITLE
Cilium - Problem to getting sctp traffic by hubble - sctp communication between pods doesn't work

### ISSUE THREAD

**Issue by kouamdo** [cilium/cilium#24642]
Hi all,

First of all, not quite sure if its a bug or maybe lack of documentation or my fault (tried first slack without success).
I'm trying to see communication between 2 pods by sctp, and see it with hubble , but nothing was fine.

after enable sctp on cilium by : `cilium config set enable-sctp true`
i was trying to capture sctp inside pod , but nothing : there is the pcap 
![image](https://user-images.githubusercontent.com/39982727/228740375-28b680ab-d761-4f6b-b6cd-b488968b7f25.png)

and use hubble to observ : ` hubble observe --protocol sctp --follow` but there was nothing in output

Knowing that cilium support sctp , is there someconfig that i should made ? How can i fix it ? where should i make some verification ?

**Comment by rolinh** [comment]
Hi, could you please report the Cilium version and Hubble CLI version that you are using?

**Comment by kouamdo** [comment]
> Hi, could you please report the Cilium version and Hubble CLI version that you are using?

i'm using cilium:v1.13 and hubble 0.11.3 compiled with go1.19.7 on linux/amd64

**Comment by kouamdo** [comment]
@nvibert
