### ISSUE TITLE
Installation on k3s fails using cilium-cli

### ISSUE THREAD

**Issue by itsironis** [cilium/cilium#24650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to install cilium on k3s but the daemonset is failing to start. I tried with the --flannel-backend=none --disable-network-policy flags and with flannel enabled.

### Cilium Version

cilium-cli: v0.13.2 compiled with go1.20.2 on linux/amd64
cilium image (default): v1.13.1
cilium image (stable): v1.13.1
cilium image (running): v1.13.1

### Kernel Version

Linux ip-10-0-4-61.eu-central-1.compute.internal 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux 

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17+k3s1", GitCommit:"abb8d7d44e4370f2a4ed2378debbc37907090295", GitTreeState:"clean", BuildDate:"2023-03-10T21:33:46Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17+k3s1", GitCommit:"abb8d7d44e4370f2a4ed2378debbc37907090295", GitTreeState:"clean", BuildDate:"2023-03-10T21:33:46Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

🔍 Collecting sysdump with cilium-cli version: v0.13.2, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
🔮 Detected Cilium operator in namespace "kube-system"
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Cilium network policies
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium identities
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium nodes
🔍 Collecting Cilium LoadBalancer IP Pools
🔍 Collecting Cilium Node Configs
🔍 Collecting Ingresses
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting Cilium BGP Peering Policies
🔍 Collecting Cilium etcd secret
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
🔍 Collecting the CNI configmap
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Cilium pods
🔍 Collecting bugtool output from Cilium pods
🔍 Collecting gops stats from Hubble Relay pods
🔍 Collecting profiling data from Cilium pods
🔍 Collecting logs from Cilium pods
⚠️ Deployment "hubble-relay" not found in namespace "kube-system" - this is expected if Hubble is not enabled
🔍 Collecting logs from Cilium operator pods
⚠️ Deployment "hubble-ui" not found in namespace "kube-system" - this is expected if Hubble UI is not enabled
🔍 Collecting logs from Hubble Relay pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting logs from Hubble UI pods
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting platform-specific data
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
🔍 Collecting kvstore data
🔍 Collecting Hubble flows from Cilium pods
I0330 15:38:19.410567   12302 request.go:690] Waited for 1.095313357s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:6443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dcilium
⚠️ Container "cilium-agent" for pod "cilium-nbvmm" in namespace "kube-system" is not running. Trying EphemeralContainer or separate Pod instead...
⚠️ EphemeralContainer "sysdump-1680190699" on pod "cilium-nbvmm" in namespace "kube-system" never reached Running status (falling back to separate Pod)
⚠️ Container "cilium-agent" on pod "cilium-nbvmm" in namespace "kube-system" is not running. Creating exec Pod.
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [12] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource
⚠️ [13] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [14] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [20] Collecting CiliumClusterwideEnvoyConfigs: failed to collect CiliumClusterwideEnvoyConfigs: the server could not find the requested resource (get ciliumclusterwideenvoyconfigs.cilium.io)
⚠️ [21] Collecting CiliumEnvoyConfigs: failed to collect CiliumEnvoyConfigs: the server could not find the requested resource (get ciliumenvoyconfigs.cilium.io)
⚠️ [22] Collecting Cilium BGP Peering Policies: failed to collect Cilium BGP Peering policies: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [23] Collecting Cilium LoadBalancer IP Pools: failed to collect Cilium LoadBalancer IP Pools: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [28] Collecting the Hubble Relay configuration: failed to collect the Hubble Relay configuration: configmaps "hubble-relay-config" not found
⚠️ cniconflist-cilium-nbvmm: unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-nbvmm-memstats: failed to list processes "cilium-nbvmm" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-nbvmm-stack: failed to list processes "cilium-nbvmm" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-nbvmm-stats: failed to list processes "cilium-nbvmm" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-nbvmm-pprof-heap: failed to list processes "cilium-nbvmm" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ gops-cilium-nbvmm-pprof-cpu: failed to list processes "cilium-nbvmm" ("cilium-agent") in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent")
⚠️ logs-cilium-nbvmm-cilium-agent: failed to collect logs for "cilium-nbvmm" ("cilium-agent") in namespace "kube-system": container "cilium-agent" in pod "cilium-nbvmm" is waiting to start: PodInitializing
⚠️ logs-cilium-nbvmm-apply-sysctl-overwrites: failed to collect logs for "cilium-nbvmm" ("apply-sysctl-overwrites") in namespace "kube-system": container "apply-sysctl-overwrites" in pod "cilium-nbvmm" is waiting to start: PodInitializing
⚠️ logs-cilium-nbvmm-mount-bpf-fs: failed to collect logs for "cilium-nbvmm" ("mount-bpf-fs") in namespace "kube-system": container "mount-bpf-fs" in pod "cilium-nbvmm" is waiting to start: PodInitializing
⚠️ logs-cilium-nbvmm-clean-cilium-state: failed to collect logs for "cilium-nbvmm" ("clean-cilium-state") in namespace "kube-system": container "clean-cilium-state" in pod "cilium-nbvmm" is waiting to start: PodInitializing
⚠️ logs-cilium-nbvmm-install-cni-binaries: failed to collect logs for "cilium-nbvmm" ("install-cni-binaries") in namespace "kube-system": container "install-cni-binaries" in pod "cilium-nbvmm" is waiting to start: PodInitializing
⚠️ hubble-flows-cilium-nbvmm: failed to collect hubble flows for "cilium-nbvmm" in namespace "kube-system": unable to upgrade connection: container not found ("cilium-agent"):
⚠️ Please note that depending on your Cilium version and installation options, this may be expected

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by casperakos** [comment]
Ok I think the issue has to do with my kernel version that runs in red hat 7.9. Is there any way to support red hat 7.9?

**Comment by julianwiedmann** [comment]
> Ok I think the issue has to do with my kernel version that runs in red hat 7.9. Is there any way to support red hat 7.9?

Hi! No sorry, if you're trying to install Cilium `v1.13.1` then the minimum kernel is 4.19 (or a BPF-equivalent kernel, eg. RHEL 8's 4.18).
