### ISSUE TITLE
Update fork of controller-tools

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#24657]
It's [falling behind](https://github.com/kubernetes-sigs/controller-tools/releases) and we should keep up with the latest tooling. 

https://github.com/cilium/controller-tools

**Comment by danehans** [comment]
@christarazi why is https://github.com/cilium/controller-tools forked from your repo instead of directly from upstream?

**Comment by christarazi** [comment]
@danehans Apologies for the late reply, see https://github.com/cilium/cilium/commit/ad007ee307a33bc6d45aafd383463c6dafd6e746 for more information as to why.

**Comment by soggiest** [comment]
Anything I can do to help refresh controller-tools? XValidation would be valuable to add to Cilium CRDs

**Comment by rastislavs** [comment]
PR with controller-tools version bump which adds support for XValidation: https://github.com/cilium/cilium/pull/30362

**Comment by christarazi** [comment]
FYI, updated to the latest of controller-tools finally (:tada:)
