### ISSUE TITLE
CFP: Unmanaged Pod Watcher should delete pods only on nodes managed by Cilium

### ISSUE THREAD

**Issue by owais** [cilium/cilium#24689]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

Yes, operator's unmanagedPodWatcher feature deletes pods on nodes that are not managed by cilium (do not have cilium deployed). This results in pods going into a enforced restart loop resulting in the pods (and nodes) becoming unavailable.

**Describe the feature you'd like**

I think it'd make sense for the operator to only delete unmanaged pods IF there is a cilium daemonset pod running on the pod's node or perhaps use another/better way to figure out if the pod's node is managed by cilium or not.

This is important for us as we want to gradually introduce cilium to production clusters one node pool at a time. We might even decide to not run cilium on some nodes ever depending on the workloads running on the node.

**Comment by taharah** [comment]
This would also be nice to have for use cases like Fargate in AWS.

**Comment by EronWright** [comment]
Is there a reasonable workaround for this issue?

**Comment by owais** [comment]
This is a feature request and there is nothing more to add to this so it shouldn't be marked as stale and closed unless the request is explicitly rejected.
