### ISSUE TITLE
test: k8sT/manifests/l3_l4_policy.yaml duplicates examples/minikube/l3_l4_policy.yaml

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2472]
Depcreated / other files are also duplicated accordingly. This is not causing test failures, but if we change the files in the `test/k8sT/manifests` but do update the examples or vice-versa, we risk breakage. As part of the provisioning steps, would be nice to create a symlink in the VM to the files in the examples directly instead of copying them directly to avoid code duplication.

**Comment by vadorovsky** [comment]
I would like to work on that issue
