### ISSUE TITLE
docs: Update diagram to remove mention of sockops

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#24735]
Sockops and friends have been removed in https://github.com/cilium/cilium/pull/23606. Anton reported that they're still referenced in a picture in the docs. We want to update that picture to remove these outdated references.

    Pictures (`cilium/Documentation/network/ebpf/_static/cilium_bpf_*.svg`) will still refer to sockmap et al.

_Originally posted by @aspsk in https://github.com/cilium/cilium/pull/23606#discussion_r1155745372_

**Comment by joestringer** [comment]
We might consider switching these to something like mermaid instead, to make them easier to update over time.

**Comment by zacharysarah** [comment]
@joestringer 👋🏻 
> We might consider switching these to something like mermaid instead, to make them easier to update over time.

I'd love to implement Mermaid, if not in this stack then in a future iteration.

As it is, the first I had to take in #24824 was to prettify the SVG enough to be human readable.

**Comment by qmonnet** [comment]
For the record, the Sphinx version we use is recent enough to support Mermaid. We haven't enabled the add-on because nobody has really needed it so far, as far as I know.

Someone reported two months ago that there was the matter of non-HTML formats to address (but does anyone use something else than the plain text files and the HTML version?), and possibly some subtleties to troubleshoot:

> For the html docs, adding the mermaid entry to certain pages worked, while on others not (I honestly failed to spot the difference in the source, but I didn't spend much time on that). On those not working, the mermaid js was not loaded at all. When adding the line below in conf.py to load the js file, it worked on all pages, but still it is not that small as a file (~1MB):
>
> ```python
> html_js_files = ["https://cdnjs.cloudflare.com/ajax/libs/mermaid/9.3.0/mermaid.min.js"] 
> ```
