### ISSUE TITLE
clustermesh: deletion events can be missed when restarting the connection to remote etcd

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#24740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the connection to remote etcd clusters is restarted (https://github.com/cilium/cilium/blob/mio%2Fmake-kind-clustermesh-fix/pkg/clustermesh/remote_cluster.go#L161), either due to config changes or by the watchdog, the old watchers are terminated, and new ones are established. This leaves a time window in which certain events are possibly missed, and never recovered once the new watchers are started. Indeed, while "add/update" events are observed while doing the initial relist operation, deletion ones are missed, possibly causing inconsistencies in the agent local state. 

This applies to nodes and services (which leverage the `Store` abstraction to trigger the respective callbacks, since a deletion event is not emitted for all keys when the store gets closed), and the IPcache watcher, which also does not remove the known elements when it is stopped. The identity cache appears also to be affected (although I have to double-check that).

Edit: I double-checked, and the identity cache is also affected, in two different ways:
* When a connection is re-established, a new allocator for the remote cluster is started (i.e., starting the corresponding watch), and then [stored in the remoteCaches map](https://github.com/cilium/cilium/blob/8f9daa8c4e9ccf17c4badaa28aa6c1b0b51924a8/pkg/allocator/allocator.go#L900) with the cluster name as key. Hence, overriding the old allocator which was previously present. This possibly leaves a time window in which the new allocator has been configured, but is not yet synchronized (i.e., list has not yet completed).
* For every event received from the kvstore, a new event is emitted through [`sendEvent`](https://github.com/cilium/cilium/blob/8f9daa8c4e9ccf17c4badaa28aa6c1b0b51924a8/pkg/allocator/cache.go#L92-L96), which uses a [channel from the main allocator](https://github.com/cilium/cilium/blob/8f9daa8c4e9ccf17c4badaa28aa6c1b0b51924a8/pkg/identity/cache/allocator.go#L454). Deletion events between restarts would be missed also here.

It is possible to reproduce this issue with the following:
* Create the environment: `make kind-clustermesh && make kind-clustermesh-images && make kind-install-cilium-clustermesh`
* Create a test deployment with multiple replicas in the first cluster, and a global service
* Observe with `cilium services get` and `cilium ip list` that these pieces of information have been propagated to the second cluster.
* Scale to zero the clustermesh-apiserver deployment in the first cluster, and wait for a few minutes until the connection is restarted.
* In the meanwhile, delete the test deployment and the service in the first cluster.
* Scale again the clustermesh-apiserver deployment to one replica.
* Observe that even after that the cilium agents reconnected to etcd, `cilium services get` and `cilium ip list` still report the stale entries.

Note: restarting the clustermesh-apiserver pod is enough to reproduce the issue. Scaling it to zero and then one just makes the whole steps more clear.

### Cilium Version

Latest on master as of today

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Good catch! We even do a list+watch when reconnecting, so this sort of bug is doubly frustrating.

FYI @oblazek

**Comment by giorio94** [comment]
Another issue which relates to the above is that the status is not properly cleaned up when one cluster is removed from the clustermesh configuration, until the agents are restarted. For instance, global service backends are not removed, nor remote nodes.

**Comment by giorio94** [comment]
All PRs addressing this issue have been merged: https://github.com/cilium/cilium/pull/25499, https://github.com/cilium/cilium/pull/25675, https://github.com/cilium/cilium/pull/25677. Upgrade notes PR is open: https://github.com/cilium/cilium/pull/26067

**Comment by giorio94** [comment]
Closing this issue, as the upgrade notes have also been merged.
