### ISSUE TITLE
Inconsistent behavior for hostport for CRIs

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#24741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Recently I switched from CRI-O to containerd. I followed the k8s docs for switching the CRI, which says in short cordon the node, drain it, stop kubelet, remove remaining ds pods, stop the CRI, change the endpoint to the new CRI, restart kubelet and uncordon the node.

This procedure worked at first, all containers came up again. But the services were only reachable from the host on the ClusterIP. The hostports were neither from the host nor from outside reachable.

Reverting the procedure the same way as described above lead to the fact that the containers were reachable again.

After that I switched again back to containerd to test why it was not working.
After uninstalling and installing cilium again with the flag cni.chainingMode=portmap connectivity was also possible for containerd.

What I understand from the celium docs is that if the kube proxy replacement is disabled this flag have to be set for hostport to work.

But I don't understand why CRI-O is working without this flag. In my opinion they should behave the same way. Especially because these too are the defacto CRIs for k8s.

As hostport mapping is a somehow standard procedure e.g. when deploying an ingress gateway on prem, it should be documented in the installation guide.

### Cilium Version

1.13.1

### Kernel Version

6.0.0-5

### Kubernetes Version

1.26.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Cilium indeed relies on portmap plugin for this functionality if KPR is disabled.

Is it possible that CRI-O is automatically setting up some portmap functionality by default?

I'm not sure that you are going to get a deep answer from the Cilium community in this case, since Cilium is presumably doing the exact same thing in both cases. This seems like it's more in the domain of the upstream CRIs to provide more background.

**Comment by squeed** [comment]
Indeed, CRI-O [manages hostport forwarding directly](https://github.com/cri-o/cri-o/tree/main/internal/hostport) whereas ContainerD does not.

**Comment by squeed** [comment]
Honestly, we should probably move hostport forwarding directly in to cilium in all cases. The CNI portmap plugin is intentionally very bare-bones (I should know, I wrote it).

**Comment by iFrozenPhoenix** [comment]
@squeed Thank you for the quick clarification.
