### ISSUE TITLE
XDP: Failing to attach XDP program to a tagged VLAN interface

### ISSUE THREAD

**Issue by JunPark** [cilium/cilium#24768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With Cilium 1.13.0, we could successfully enable XDP when a node has a single native VLAN. However, after we added a tagged VLAN (namely, vlan3 with the vlan id 3) on the same node along with the native VLAN, and then restarted its cilium agent, we got the following error.
```
Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface vlan3: operation not supported" subsys=datapath-loader
```
Here is our installation parameter set. Basically we use BPG to advertise both POD CIRD and Service CIDR with xvlan tunneling for Pod-to-pod communication.
```
helm upgrade --namespace kube-system cilium cilium/cilium --version 1.13.0 --set bgpControlPlane.enabled=true,bpf.masquerade=true,cluster.id=0,cluster.name=k8s-cluster-01,encryption.nodeEncryption=false,ipMasqAgent.enabled=true,ipam.mode=kubernetes,ipam.operator.clusterPoolIPv4MaskSize=26,ipam.operator.clusterPoolIPv4PodCIDR=172.16.0.0/12,kubeProxyReplacement=strict,loadBalancer.acceleration=native,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=vxlan
Release "cilium" has been upgraded. Happy Helming!
NAME: cilium
LAST DEPLOYED: Tue Apr  4 15:47:21 2023
NAMESPACE: kube-system
STATUS: deployed
REVISION: 9
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.13.0.
```
Just in case, here is an example of the success case when there is only a single VLAN as a good reference. I think such a result can prove our Mellanox driver supports XDP.
But unfortunately I could not see such a good result after adding a tagged VLAN on the native VLAN interface.
```
# bpftool net
xdp:
ens785np0(2) driver id 1641

tc:
ens785np0(2) clsact/ingress cilium-ens785np0 id 1754
ens785np0(2) clsact/egress cilium-ens785np0 id 1756
cilium_net(4) clsact/ingress cilium-cilium_net id 1737
cilium_host(5) clsact/ingress cilium-cilium_host id 1718
cilium_host(5) clsact/egress cilium-cilium_host id 1724
cilium_vxlan(6) clsact/ingress bpf_overlay.o:[from-overlay] id 1576
cilium_vxlan(6) clsact/egress bpf_overlay.o:[to-overlay] id 1587
lxc_health(11) clsact/ingress cilium-lxc_health id 1674
```

### Cilium Version

1.13.0

### Kernel Version

Linux worknode-1 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.10+rke2r1

### Sysdump

Somehow my sysdump file is too big (189MB), I cannot upload it here because its size exceeds 25 MB.

### Relevant log output

```shell
$ cilium status
...
...
Errors:           cilium             cilium-jmgtm    unable to retrieve cilium status: container cilium-agent is in CrashLoopBackOff, exited with code 1: level=fatal msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface vlan3: operation not supported" subsys=datapath-loader
...
```

### Anything else?

# lspci | grep -i ether
01:00.0 Ethernet controller: Intel Corporation Ethernet Controller 10G X550T (rev 01)
65:00.0 Ethernet controller: Mellanox Technologies MT28908 Family [ConnectX-6]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shuaizi** [comment]
looks like the driver for vlan3 not support xdp,
you can check from here: [https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#xdp](url)

**Comment by JunPark** [comment]
Hi @shuaizi, 
Thanks for the comment.
Jun> here is an example of the success case only with a single VLAN. 
Well, as I shared, I could enable XDP when a node has a single native VLAN with the current driver. So it was clear there is xdp support on the Mellanox driver.

**Comment by JunPark** [comment]
I think there is a similar bug report before: https://github.com/cilium/cilium/issues/22970 which was closed because, in the report, Linux kernel 5.14 was used and it was suggested to use 5.15 or higher. But, even with Linux 5.15 (like in our case here), there is still an issue in enabling XDP when there are multiple VLAN interfaces.

**Comment by JunPark** [comment]
I got a quick question. CC @ti-mo
Here, in this loop, https://github.com/cilium/cilium/blob/v1.13.0/pkg/datapath/loader/loader.go#L254-L273
it seems that all the found interfaces are looped through in order to replace ebpf or xdp program. 
In our server, we have a native VLAN (ens785np0) as well as a tagged VLAN (vlan3) which is generated from the original native VLAN. Now here is my question. 
Do we have to replace XDP (i.e., calling the function of "replaceDatapath(ctx, interfaceName, objPaths[i], progs, "")") even on the tagged VLAN interface although XDP could be already loaded on the native VLAN?

**Comment by ti-mo** [comment]
@JunPark Do you intend to forward traffic over any of these vlan devices? If not, you can manually specify the physical devices Cilium attaches to using the [`devices` setting](https://github.com/cilium/cilium/blob/e903eb692c40adc75673487f25759ba2bb9d4dcb/install/kubernetes/cilium/values.yaml#L595). Looks like this isn't so widely-documented, but you can see an example of this in [Host Firewall](https://docs.cilium.io/en/v1.13/security/host-firewall/#enable-the-host-firewall-in-cilium).

I think this recently gained support for wildcards, so if memory serves me well, you can specify e.g. `--set devices='ens*'` and those .1q devs will be ignored. There's no way I know of to selectively attach using XDP or TC to specific interfaces if they lack driver support.

**Comment by JunPark** [comment]
@ti-mo, thanks for chiming in here.
Yeah, in fact, we need such a tagged VLAN to implement a separate public-facing LB-type service while the native VLAN is being used for internal LB-type service. All these are based on the Cilium BGP peering from worker nodes to their top-of-rack (ToR) switch. Basically, we have two separate VRFs on ToR to deal with two separate IP Pools for LB.
Anyhow, we found this doc, https://docs.cilium.io/en/v1.13/configuration/vlan-802.1q/, it might be possible to use it if I rename vlan3 to ens785np0.3? Or wouldn't matter much? I will test it soon though, it'd be much appreciated if you can give me some insight on it.

**Comment by JunPark** [comment]
Here is an update regarding testing a tagged vlan name based on the native vlan interface name (like, `ens785np0.3` rather than `vlan3`).
```
# bpftool net
xdp:
ens785np0(2) driver id 4744

tc:
ens785np0(2) clsact/ingress cilium-ens785np0 id 785
ens785np0(2) clsact/egress cilium-ens785np0 id 798
ens785np0.3(4) clsact/ingress cilium-ens785np0.3 id 809
ens785np0.3(4) clsact/egress cilium-ens785np0.3 id 820
cilium_net(5) clsact/ingress cilium-cilium_net id 771
cilium_host(6) clsact/ingress cilium-cilium_host id 716
cilium_host(6) clsact/egress cilium-cilium_host id 756
cilium_vxlan(7) clsact/ingress bpf_overlay.o:[from-overlay] id 5327
cilium_vxlan(7) clsact/egress bpf_overlay.o:[to-overlay] id 5338

flow_dissector:
```
So I got noticed several interesting things here.
1. `tc` is successfully enabled on `ens785np0.3`.
2. `xdp` still fails to be enabled on `ens785np0.3` with the same error message before: `msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface ens785np0.3: operation not supported" subsys=datapath-loader`. But `xdp` is successfully enabled on the native interface `ens785np0`.
3. The cilium agent unnecessarily (?) exited out after failing enabling XDP on `ens785np0.3`.
So my question would be, regardless of why `xdp` is not enabled on `ens785np0.3`...
Would it be nice to selectively enable `xdp` on such available network interfaces and not simply exit out due to non-available network interfaces? Is there any compelling reasons not to selectively enable `xdp`?

**Comment by borkmann** [comment]
> xdp still fails to be enabled on ens785np0.3

The kernel doesn't support attaching XDP to vlan dev. It can only attach to phys device natively.

**Comment by poblahblahblah** [comment]
> The kernel doesn't support attaching XDP to vlan dev. It can only attach to phys device natively.

@borkmann It doesn't look like there is a documented way to _ignore_ a device for XDP, and looking at the code I don't see a way to do this, either.

Would would be the recommended path for addressing this issue? Would Cilium be willing to accept a patch that adds the ability to ignore devices by name or driver?

**Comment by borkmann** [comment]
> > The kernel doesn't support attaching XDP to vlan dev. It can only attach to phys device natively.
> 
> @borkmann It doesn't look like there is a documented way to _ignore_ a device for XDP, and looking at the code I don't see a way to do this, either.
> 
> Would would be the recommended path for addressing this issue? Would Cilium be willing to accept a patch that adds the ability to ignore devices by name or driver?

Could be an option, either name or based on type could work.

**Comment by pubyun** [comment]
the following patch was not merged:


Allow users to ignore links when enabling XDP

**Comment by qmonnet** [comment]
@pubyun No, that patch was [dropped](https://github.com/cilium/cilium/pull/25870#issuecomment-1815412655) in favour of #28666.
