### ISSUE TITLE
Service with L7 enabled, Envoy leaks client connections

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#24771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- Enable L7 Proxy LB for service
- Make requests from client
- Connections from Envoy stay alive after request is finished (and are not re-used for new requests)

### Cilium Version

v1.13.1

### Kernel Version

`5.15.0-1033-aws`

### Kubernetes Version

v1.23.16

### Relevant log output

Every request leaves behind a connection that periodically sends a keep-alive:
```shell
-> stack flow 0xdd6aa003 , identity 92527->84969 state reply ifindex 0 orig-ip 0.0.0.0: 10.254.54.65:8080 -> 10.254.190.159:51430 tcp ACK
-> endpoint 1384 flow 0x86d486d4 , identity 84969->92527 state established ifindex 0 orig-ip 10.254.190.159: 10.254.190.159:51430 -> 10.254.54.65:8080 tcp ACK
-> stack flow 0xef0f52bf , identity 92527->84969 state reply ifindex 0 orig-ip 0.0.0.0: 10.254.54.65:8080 -> 10.254.190.159:43186 tcp ACK
-> endpoint 1384 flow 0x1cec1cec , identity 84969->92527 state established ifindex 0 orig-ip 10.254.190.159: 10.254.190.159:43186 -> 10.254.54.65:8080 tcp ACK
```

### Anything else?

Adding `idle_timeout: 5s` to the service cluster cleans them up (I assume the default 1h applies normally)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Thanks for your issue, just curious if you are using Ingress controller or Gateway API or just L7 network policy :thinking:

**Comment by dctrwatson** [comment]
Just used the annotation on the service: `kubectl annotate service echo-service service.cilium.io/lb-l7=enabled`

**Comment by sayboras** [comment]
Out of curiosity, have you tried to set idle timeout policy manually in CEC, and check if the issue is still happening?

**Comment by dctrwatson** [comment]
> Out of curiosity, have you tried to set idle timeout policy manually in CEC, and check if the issue is still happening? 
> 

Yes. That's how I was able to handle it for the test service.
