### ISSUE TITLE
"helm upgrade" does not restart cilium agents with the updated options

### ISSUE THREAD

**Issue by JunPark** [cilium/cilium#24772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After installing the default setting of Cilium without any custom options, I ran the following command to update some options.
It worked well to apply all the updated options and restarted all the cilium agents with the updated options. So I could see XDP is enabled as well.
```
helm upgrade --namespace kube-system cilium cilium/cilium --version 1.13.0 --set bgpControlPlane.enabled=true,bpf.masquerade=true,cluster.id=0,cluster.name=vae-ttd-kpop-01,encryption.nodeEncryption=false,ipMasqAgent.enabled=true,ipam.mode=kubernetes,ipam.operator.clusterPoolIPv4MaskSize=26,ipam.operator.clusterPoolIPv4PodCIDR=172.16.0.0/12,kubeProxyReplacement=strict,loadBalancer.acceleration=native,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=vxlan
```
```
# bpftool net
xdp:
ens785np0(2) driver id 1641
tc:
ens785np0(2) clsact/ingress cilium-ens785np0 id 1754
ens785np0(2) clsact/egress cilium-ens785np0 id 1756
...
```

And then, for some other testing, we had to drop the option of loadBalancer.acceleration=native, so I switched the loadBalancer.acceleration from `native` to `disabled` and then run the following command again.
```
$ helm upgrade --namespace kube-system cilium cilium/cilium --version 1.13.0 --set bgpControlPlane.enabled=true,bpf.masquerade=true,cluster.id=0,cluster.name=vae-ttd-kpop-01,encryption.nodeEncryption=false,ipMasqAgent.enabled=true,ipam.mode=kubernetes,ipam.operator.clusterPoolIPv4MaskSize=26,ipam.operator.clusterPoolIPv4PodCIDR=172.16.0.0/12,kubeProxyReplacement=strict,loadBalancer.acceleration=disabled,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=vxlan

Release "cilium" has been upgraded. Happy Helming!
NAME: cilium
LAST DEPLOYED: Tue Apr  4 16:06:41 2023
NAMESPACE: kube-system
STATUS: deployed
REVISION: 10
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.13.0.

For any further help, visit https://docs.cilium.io/en/v1.13/gettinghelp
```
Although the output apparently seems good and completed, it does not actually restart the cilium agents with the updated options at all. So the nodes still have XDP enabled.
As a temporary solution, I executed the following to restart all the agents and then XDP has been disabled.
```
kubectl rollout restart ds cilium -n kube-system
```
Is any other better way to apply the change of options?

### Cilium Version

1.13.0

### Kernel Version

Linux worknode-1 5.15.0-67-generic https://github.com/cilium/cilium/pull/74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.10+rke2r1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
This is expected as per current implementation, if you want to have auto rollout when configmap is updated, please enable the below helm attributes:
- rollOutCiliumPods
- hubble.relay.rollOutPods
- hubble.ui.rollOutPods
- operator.rollOutPods


https://docs.cilium.io/en/v1.13/helm-reference/
