### ISSUE TITLE
CFP: --auto-direct-node-routes should ignore specific gateways

### ISSUE THREAD

**Issue by Managarmrr** [cilium/cilium#24777]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

I'm using [Hetzner](https://www.hetzner.com/) to host my kubernetes clusters. Hetzner has private networking, but when combining cloud servers with bare metal servers a gateway is introduced. The gateway is also introduced for cloud servers themselves. (e.g.: `10.16.0.0/12 via 10.16.0.1 dev enp7s0`).
This makes cilium deployed with the `--auto-direct-node-routes` ineffective, as it refuses to add the routes due to a gateway being there, even with the `ipv4-native-routing-cidr` properly configured. My current workaround is to run [kube-router](https://www.kube-router.io/) for a full iBGP mesh.

**Describe the feature you'd like**

I would like for cilium to disregard specific gateways.

**Describe your proposed solution**

A new config option, specifying a list of CIDRs for which to disregard gateways for `--auto-direct-node-routes` could be added.
Maybe `ipv4-native-routing-cidr` could be used, but I'm not certain of the implications of this.

**Comment by MTRNord** [comment]
I am seeing the same issue on my setup, and it currently causes quite some headaches since it causes unclear network failures which are really hard to debug, leading me to believe this being my issue.

**Comment by Managarmrr** [comment]
> I am seeing the same issue on my setup, and it currently causes quite some headaches since it causes unclear network failures which are really hard to debug, leading me to believe this being my issue.

If you're running on Hetzner I might have an idea about your network issue: Did you manually adjust ciliums MTU to 1400 via helm, or however else you manage cilium? cilium uses the wrong device to autodetect MTU, which leads to intermittend network issues with packets that reach the MTU.

**Comment by MTRNord** [comment]
> > I am seeing the same issue on my setup, and it currently causes quite some headaches since it causes unclear network failures which are really hard to debug, leading me to believe this being my issue.
> 
> If you're running on Hetzner I might have an idea about your network issue: Did you manually adjust ciliums MTU to 1400 via helm, or however else you manage cilium? cilium uses the wrong device to autodetect MTU, which leads to intermittend network issues with packets that reach the MTU.

I am running a dedicated server at hetzner which has a (k8s) load balancer ipv6 which seems to not be properly going to the cluster if I am coming from a hetzner vm. It works from the outside of the cluster.

At least on the node where that external ip belongs to all the interfaces have a mtu of 1500. Which if I understand you correctly is fine?

**Comment by Managarmrr** [comment]
> I am running a dedicated server at hetzner which has a (k8s) load balancer ipv6 which seems to not be properly going to the cluster if I am coming from a hetzner vm. It works from the outside of the cluster.
> 
> At least on the node where that external ip belongs to all the interfaces have a mtu of 1500. Which if I understand you correctly is fine?
> 
> Edit to make it clearer:
> 
> I have Node A, B and C. I have an ipv6 that is announced on Node A via metallb. It is a loadbalancer external ip which handles my ingress. I can reach the IPv6 on Node A from my home internet. I cannot reach the same IP from Node B or C at the host.

How are the nodes interconnected? If you're using a vSwitch then you'll need to make sure cilium works with an MTU of 1400, otherwise it won't work. If you're using the public interface (not a vSwitch VLAN) then your MTU of 1500 is fine.

**Comment by MTRNord** [comment]
> > I am running a dedicated server at hetzner which has a (k8s) load balancer ipv6 which seems to not be properly going to the cluster if I am coming from a hetzner vm. It works from the outside of the cluster.
> > At least on the node where that external ip belongs to all the interfaces have a mtu of 1500. Which if I understand you correctly is fine?
> > Edit to make it clearer:
> > I have Node A, B and C. I have an ipv6 that is announced on Node A via metallb. It is a loadbalancer external ip which handles my ingress. I can reach the IPv6 on Node A from my home internet. I cannot reach the same IP from Node B or C at the host.
> 
> How are the nodes interconnected? If you're using a vSwitch then you'll need to make sure cilium works with an MTU of 1400, otherwise it won't work. If you're using the public interface (not a vSwitch VLAN) then your MTU of 1500 is fine.

It currently is using the public interface but I want to use the internal one eventually (Its blocked behind me having super old nfs pvcs. And the operator for those wrote the ip which conflicts on one node with the internal into a read only field :D So I cannot route via the internal network yet)

**Comment by joestringer** [comment]
`--auto-direct-node-routes` only works when all nodes are directly connected via the same Layer 2 domain. If there are gateways in between, then this constraint is violated, so I would presume that the only path is to disable this option and either manage the routes on your own (as you're doing with kube-router), or use a tunnel overlay in order to provide pod IP connectivity across the underlying fabric.

I'm not sure I understand how simply ignoring the gateway is going to make connectivity functional, given that then the gateway would still need to know about how to route all k8s Pod CIDR ranges.

**Comment by Managarmrr** [comment]
Some cloud providers - such as Hetzner - introduce gateways in their private cloud networks.
The only thing kube-router does in my setup is add a new route on the host in the format of:
`nodeBPodCIDR via nodeB` which is what cilium would do with the `--auto-direct-node-routes` feature.
Also certain clouds support adding additional routes within the private networks by use of a cloud-controller-manager, but even that functionality is broken on Hetzner in particular with cilium, as no routes may be added for vSwitches.

A configuration flag which would allow one to specify certain networks to ignore the gateway for would therefore fix these setup issues in certain, arguably broken, cloud provider environments.

**Comment by joestringer** [comment]
Is there any documentation from Hetzner that describes the L2 layout of the nodes in such clusters and provides a guarantee that they are all directly connected? Furthermore do they describe the role of the gateways in that topology? If yes, then that documentation could help to frame any discussion around how the proposed changes to the `--auto-direct-node-routes` flag may work in conjunction with that topology.
