### ISSUE TITLE
Upgrade from 1.13.1 is failing on GKE

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#24787]
### Reproduction Steps
```
./cilium install --version=1.13.1 --helm-set=debug.enabled=true
./cilium upgrade --agent-image quay.io/cilium/cilium-ci:latest --operator-image quay.io/cilium/operator-generic-ci:latest
```
Cilium agent pods then fail to start with:
```
  Warning  FailedPostStartHook  4m43s                  kubelet            Exec lifecycle hook ([/cni-install.sh --enable-debug=true --cni-exclusive=true --log-file=/var/run/cilium/cilium-cni.log]) for Container "cilium-agent" in Pod "cilium-ltpm7_kube-system(de7f459f-9dc0-4daf-9d89-c1a94543ba75)" failed - error: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "2674d334d0571e097d9bc5f57d1ad2a05d7d58838d532cec65cc606625865d14": OCI runtime exec failed: exec failed: unable to start container process: exec: "/cni-install.sh": stat /cni-install.sh: no such file or directory: unknown, message: ""
  Normal   Killing              4m43s                  kubelet            FailedPostStartHook
```

Cilium CLI version in case that matters:
```
$ ./cilium version
cilium-cli: v0.13.1-35-gdacac93a compiled with go1.20.1 on linux/amd64
cilium image (default): v1.13.1
cilium image (stable): v1.13.1
cilium image (running): -ci:latest
```

### Sysdumps
Sysdump captured after upgrade from 1.13.1: [cilium-sysdump-20230407-000236.zip](https://github.com/cilium/cilium/files/11174723/cilium-sysdump-20230407-000236.zip)
Sysdump captured after upgrade from 1.13.0: [cilium-sysdump-20230406-232340.zip](https://github.com/cilium/cilium/files/11174729/cilium-sysdump-20230406-232340.zip)

### Misc.
I've been testing this upgrade path frequently in the last few days, so the breakage in master is very recent, no more than a few days old.

**Comment by chancez** [comment]
I think that’s expected, you're using the old chart (1.13) with the new image (~1.14). The script is gone in master/1.14, and is  of the agent binary itself now as of https://github.com/cilium/cilium/pull/24389.

To properly upgrade, you need to use the new chart (from master) which doesn’t use the script anymore.

**Comment by pchaigno** [comment]
Thanks Chance for the quick answer! That seems likely to be the case indeed.

I'll close this. Unfortunately `cilium upgrade` doesn't directly support specifying the new chart, but that's a different issue.
