### ISSUE TITLE
Connection refused when visiting localhost(127.0.0.1) address service in kube-proxy replacement mode

### ISSUE THREAD

**Issue by JohnJAS** [cilium/cilium#24805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm testing the kube-proxy replacement mode, and I found it works except that I can't visit my registry with localhost address. It showed "connection refused" via the ipv4 address. But it works well in kube-proxy hybrid mode. I get the answer on the official slack channel that it should be supported to visit localhost address in kube-proxy replacement mode. So I think it should be a bug.

_**_kube-proxy hybrid mode:(Notice that i didn't enable ipv6 so that it failed to connect to the ipv6 address, but it can establish connection with ipv4 address. )_**_
```
[root@ip-10-164-35-236 ~]# curl -k https://localhost:5000/auth/token -v
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 5000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
```
**_kube-proxy free mode: (It showed that it failed to connect to 127.0.0.1:5000)_**
```
[root@ip-10-164-32-107 ~]# curl -k https://localhost:5000/auth/token -v
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 5000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 5000 failed: Connection refused
* Failed to connect to localhost port 5000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 5000: Connection refused
```
_**Visiting registry via cluster ip is normal**_
```
# curl -k https://172.17.125.251:5000 -v
* Rebuilt URL to: https://172.17.125.251:5000/
*   Trying 172.17.125.251...
* TCP_NODELAY set
* Connected to 172.17.125.251 (172.17.125.251) port 5000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
```

**_installation command:_**
```
helm install cilium cilium-1.13.1.tgz -n kube-system \
  --set cni.binPath=/opt/cdf/cni \
  --set cni.confPath=/opt/cdf/cni/conf \
  --set cluster.name=cdf-kubernetes \
  --set ipam.mode=kubernetes \
  --set kubeProxyReplacement=strict \
  --set k8sServiceHost=${API_SERVER_IP} \
  --set k8sServicePort=${API_SERVER_PORT}
```

### Cilium Version

cilium-cli: v0.13.2 compiled with go1.20.2 on linux/amd64
cilium image (default): v1.13.1
cilium image (stable): v1.13.1
cilium image (running): v1.13.1

### Kernel Version

Linux ip-10-164-32-33.us-west-2.compute.internal 4.18.0-348.el8.x86_64 #1 SMP Mon Oct 4 12:17:22 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"db61bf1bb93524ed38d80018b6490f910358fb05", GitTreeState:"clean", BuildDate:"2023-03-15T03:13:46Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"db61bf1bb93524ed38d80018b6490f910358fb05", GitTreeState:"clean", BuildDate:"2023-03-15T03:10:15Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230411-085724.zip](https://github.com/cilium/cilium/files/11198759/cilium-sysdump-20230411-085724.zip)

### Anything else?

The kubernetes v1.26.1 is self-built via some security defects fixing. I think it should not be related to this issue, but still listed here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by j-be** [comment]
@JohnJAS I think I am hit by a similar if not the same issue. Have you found a solution yet?

If not: I tested with Cilium 1.13.3, 1.13.4 and v1.14.0-snapshot.4 on K3s without KubeProxy, nodes are Ubuntu 22.04. `cilium connectivity test` always gives me:

```
⚠️  Unable to contact Hubble Relay, disabling Hubble telescope and flow validation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4245: connect: connection refused"
ℹ️  Expose Relay locally with:
   cilium hubble enable
   cilium hubble port-forward&
ℹ️  Cilium version: 1.14.0
🏃 Running tests...
```
but `cilium hubble enable` gives me:
```
...
🔮 Auto-detected cilium version v1.14.0-snapshot.4
🔑 Found CA in secret cilium-ca
ℹ️  helm template --namespace kube-system cilium cilium/cilium --version 1.14.0-snapshot.4 --set hubble.enabled=true,hubble.relay.enabled=true,tls.ca.cert=...
✨ Patching ConfigMap cilium-config to enable Hubble...
🚀 Creating ConfigMap for Cilium version 1.14.0-snapshot.4...
♻️  Restarted Cilium pods
⌛ Waiting for Cilium to become ready before deploying other Hubble component(s)...
🚀 Creating Peer Service...

Error: Unable to enable Hubble: services "hubble-peer" already exists
```

Apart from that `cilium connectivity test` succeeds with  `✅ All 45 tests (322 actions) successful, 9 tests skipped, 0 scenarios skipped.` Also, `cilium hubble ui` works just fine.

Do you see the same on your side?

Cheers.
