### ISSUE TITLE
High latency when enable Cilium Annotation L7 Visibility

### ISSUE THREAD

**Issue by cuongquach** [cilium/cilium#24816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we enable annotation cilium L7 visibility for pod applications, we have detected some super slow response from our pod application via call directly kubernetes svc.

When i do curl command line to service deployment has Annotation L7, i can see return response header `x-envoy-upstream-service-time` from Cilium-Envoy miliseconds around over 3 minutues.

```
HTTP/1.1 200 OK
server: envoy
date: Tue, 11 Apr 2023 17:44:11 GMT
content-type: application/json
content-length: 46
access-control-allow-origin: *
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
strict-transport-security: max-age=2592000; includeSubDomains
x-envoy-upstream-service-time: 212182
```

- This issue is intermittent , we got some super slow response with high frequent occurs.
- This make our system un-stable when k8s also cannot healthcheck correctly with high response.
- I suspect something wrong or bottleneck somewhere at `cilium-envoy` , actually i am not very sure. 

### Cilium Version

cilium image (running): v1.13.1

### Kernel Version

5.10.162+

### Kubernetes Version

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.10-dispatcher-dirty", GitCommit:"c4dc593360fd87cf0fe27b27e36a4a19b62d90e9", GitTreeState:"dirty", BuildDate:"2023-01-24T19:42:00Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.12-gke.500", GitCommit:"fa2714567d7451b5e32541c10119d1246730c197", GitTreeState:"clean", BuildDate:"2023-03-23T11:35:05Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

Download from here: https://drive.google.com/file/d/12h_5ybQ23rLHbubmCc6s0_xN8Rs8oIa6/view?usp=share_link

It is over 25MB are allowed.

### Relevant log output

```shell
Log hubble when stuck in super slow response.


Apr 11 17:48:10.314: default/service-A-67b5cd8b9c-cll7c:44476 (ID:17490) -> default/service-B-8645564dcd-4thxh:5000 (ID:11027) to-stack FORWARDED (TCP Flags: SYN)
Apr 11 17:48:10.315: default/service-A-67b5cd8b9c-cll7c:44476 (ID:17490) -> default/service-B-8645564dcd-4thxh:5000 (ID:11027) to-proxy FORWARDED (TCP Flags: SYN)
Apr 11 17:48:10.315: default/service-A-67b5cd8b9c-cll7c:44476 (ID:17490) -> default/service-B-8645564dcd-4thxh:5000 (ID:11027) to-stack FORWARDED (TCP Flags: ACK)
Apr 11 17:48:10.315: default/service-A-67b5cd8b9c-cll7c:44476 (ID:17490) -> default/service-B-8645564dcd-4thxh:5000 (ID:11027) to-stack FORWARDED (TCP Flags: ACK, PSH)
Apr 11 17:48:10.316: default/service-A-67b5cd8b9c-cll7c:44476 (ID:17490) -> default/service-B-8645564dcd-4thxh:5000 (ID:11027) http-request FORWARDED (HTTP/1.1 GET http://service-B.default/api/call/cc4cb7c5cbfe/tree)
```

It wait for : TCP Flags: ACK, FIN and TCP Flags: ACK so long.
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vietwow** [comment]
any news for this bug?

**Comment by sgargan** [comment]
We have also seen issues with this annotation causing connection issues for requests > 60 seconds. This manifests as a `Broken Pipe` error, suggesting that the connection is closed as far as envoy is concerned. This is running against 1.16.5 version of Cilium.
