### ISSUE TITLE
Issue when changing PolicyEnforcement

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#2485]
This issue happens on Jenkins build (861)[https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/861/]

Error:
```
level=info msg="setting PolicyEnforcement=always"
cmd: "sudo cilium config | grep PolicyEnforcement | awk '{print $2}'" exitCode: 0
 never

cmd: "sudo cilium config PolicyEnforcement=always" exitCode: 1
 Error: Unable to change agent configuration: Patch http:///var/run/cilium/cilium.sock/v1beta/config: EOF
```

Trying the same order and it didn't happen, so must be a race condition in any
place.

**Comment by eloycoto** [comment]
I think that this issue is related to #2416

**Comment by ianvernon** [comment]
We haven't seen this issue in some time; I think we can close this.
