### ISSUE TITLE
cilium init container failed to copy cni onto hostpath due to permission denied

### ISSUE THREAD

**Issue by JohnJAS** [cilium/cilium#24889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Install cilium by setting the cni binaries path, the init contaienrd 'install-cni-binaries' will failed to copy cni plugins onto the host path due to permission denied error when the path is not root permission, like the following.

You can see the cni folder is owned by user 1999 with 700 permission. If not privileged, the init container can never copy the bins to the host path.
![image](https://user-images.githubusercontent.com/16176002/231976791-e3d13294-ef0c-4fc4-9657-9e08630dbffc.png)

```
[root@ip-10-164-32-33 charts]# kubectl logs -f cilium-gmq42 -n kube-system -c install-cni-binaries
Installing loopback driver...
cp: cannot stat '/host/opt/cni/bin/loopback': Permission denied
Installing cilium-cni to /host/opt/cni/bin/ ...
rm: cannot remove '/host/opt/cni/bin/cilium-cni.new': Permission denied
cp: failed to access '/host/opt/cni/bin/.cilium-cni.new': Permission denied
```

I've already set privilege as true, but it doesn't work. 
```
helm install cilium cilium-1.13.1.tgz -n kube-system \
    --set cni.binPath=/opt/cdf/cni \
    --set cni.confPath=/opt/cdf/cni/conf \
    --set cluster.name=cdf-kubernetes \
    --set ipam.mode=kubernetes \
    --set securityContext.privileged=true \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT}

```

After I check the yaml file, I found init container 'install-cni-binaries' didn't have securityContext.privileged settings inside the yaml like other init containers do. Refer to : 
https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L674-L680

I think this is a defect and I will create a PR for this later to fix this issue. 
Here is the PR: https://github.com/cilium/cilium/pull/24891

### Cilium Version

cilium-cli: v0.13.2 compiled with go1.20.2 on linux/amd64
cilium image (default): v1.13.1
cilium image (stable): v1.13.1
cilium image (running): v1.13.1

### Kernel Version

Linux ip-10-164-32-33.us-west-2.compute.internal 4.18.0-348.el8.x86_64 https://github.com/cilium/cilium/pull/1 SMP Mon Oct 4 12:17:22 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"db61bf1bb93524ed38d80018b6490f910358fb05", GitTreeState:"clean", BuildDate:"2023-03-15T03:13:46Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"db61bf1bb93524ed38d80018b6490f910358fb05", GitTreeState:"clean", BuildDate:"2023-03-15T03:10:15Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pengbinbin1** [comment]
I had the same problem

**Comment by JohnJAS** [comment]
@squeed Please have a review of this issue.

**Comment by JohnJAS** [comment]
@ldelossa I think no. Because cilium pods failed to start up if this issue happened. I've already created a [PR](https://github.com/cilium/cilium/pull/24891) for fixing anyway.
