### ISSUE TITLE
CNI live migration - Openshift

### ISSUE THREAD

**Issue by itmwiw** [cilium/cilium#24896]
Hello all,
First of all, thanks for the great work.
We have several production openshift clusters, some using OpenshiftSDN CNI and others using OpenshiftOVN CNI. We want to migrate all these clusters to cilium. 
In the documentation, I only found how to create an openshift cluster with Cilium from scratch. 
I found out this: https://cilium.io/blog/2020/10/06/skybet-cilium-migration/ for vanilla kubernetes clusters but nothing for openshift.
Can you help with this?
Thanks

**Comment by rickymulder** [comment]
I also have several OpenShift-SDN production clusters that I'd like to migrate to cilium.  This step-by-step would be incredibly helpful.

**Comment by coleenquadros** [comment]
any updates on this?

**Comment by saintdle** [comment]
Hi, it's a bit of a grey area, Red Hat doesn't really explain or provide guidance on moving your existing running clusters to a third party CNI, even if it's fully certified by themselves. 

I've jotted down the steps I had working in a lab, but this is at your own risk etc etc

https://veducate.co.uk/migrate-red-hat-openshiftsdn-ovn-kubernetes-cilium/
