### ISSUE TITLE
datapath: Ensure that "to-netdev" is invoked only once for the same packet

### ISSUE THREAD

**Issue by brb** [cilium/cilium#24916]
We have observed, that the same packet can be handled multiple times by the bpf_host's `to-netdev`. This can happen when the `to-netdev` is attached to a bridge and to an outgoing netdev which is attached to the bridge. This can result e.g., into multiple unnecessary SNATs for the same packet which can break the host-firewall (the host-firewall for a reply to such a packet is invoked after only the first rev-SNAT).

A potential fix could use a similar infrastructure as we do today with `nodeport_lb*()` for TC BPF bypass if a packet was handled by XDP.

**Comment by julianwiedmann** [comment]
To cover the SNAT aspect, we should just have the `nodeport_snat_fwd_ipv4()` path set `ctx_snat_done()` ...
