### ISSUE TITLE
CI: ConformanceDatapath: Incorrect status if jobs are skipped

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#24915]
The ConformanceDatapath workflow doesn't properly set its status on GitHub if the test is skipped. In such cases, the workflow remains indefinitely in Pending state. 

Example: https://github.com/cilium/cilium/actions/runs/4699458917
![image](https://user-images.githubusercontent.com/1764210/232313554-92a7a607-9223-4212-adfa-53e2175dc0e2.png)

**Comment by gandro** [comment]
Interesting. This likely also applies to other workflows (ci-verifier, ci-clustermesh) that use the same pattern as well. I guess we need to fix `Set commit status` to set the test as succeeded instead of as pending.
