### ISSUE TITLE
cilium1.10.3 tc replace bpf_lxc.o for lxc device cost too much cpu

### ISSUE THREAD

**Issue by z1006409356** [cilium/cilium#24913]
Cilium1.10.3, the size of the lxc. o file is 2.3M. When performing the "tc filter replace" operation to mount the ebpf file to the lxc device, kernel security verification takes up too much CPU, resulting in an average of 1.8 seconds for a single node to deploy 30 pods simultaneously; If you remove the operation of mouting bpf_lxc. o file to lxc devices, requires an average of only 200ms for one Pod

**Comment by sayboras** [comment]
Cilium 1.10.x is considered as EOL, do you observe the similar pattern in recent versions (e.g. 1.11.x, 1.12.x, and 1.13.x) ?

**Comment by z1006409356** [comment]
We initially used version 1.10.3 and developed many new features based on it. If we want to upgrade to version 1.13.0, the cost is very high.

We tested and found that version 1.12.0 no longer uses the tc filter instruction to mount the ebpf program. Creating 30 Pods simultaneously reduces the overall time consumption by 50% compared to version 1.10.3. We would like to know the specific modifications

**Comment by sayboras** [comment]
sorry for the late reply, I am not fully aware of such changes. Feel free to echo the same in #sig-datapath in cilium OSS.

I am closing this github issue.
