### ISSUE TITLE
Make use of the TransFunc introduced in k8s 1.27

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#24923]
Kubernetes has introduced in https://github.com/kubernetes/kubernetes/pull/116623, and backported to all branches, the TransFunc that allows to mutate certain resources in K8s Caches. This will allow us to remove our own TransFunc implementation functions in https://github.com/cilium/cilium/blob/264dd3f350022c7626438f2dab0401dcb41ec616/pkg/k8s/informer/informer.go#L101-L106 by using the DeltaFIFO directly from the library.

Depending how non-invasive the patch will be, we might consider backporting it to our stable branches as well.

cc @odinuge

**Comment by gandro** [comment]
This has the `needs/triage` label since it's unclear what the consequences are of not using TransFunc in our informers. It might be fine, it might not be.

**Comment by aanm** [comment]
This is likely handled by https://github.com/cilium/cilium/pull/24929 https://github.com/cilium/cilium/pull/24930 and https://github.com/cilium/cilium/pull/24931 for the stable branches. In terms of consistency we should be using the k8s client-go library by using the new `Transformer` as @odinuge suggested. @odinuge correct me if I'm wrong but I think with the above PRs we don't need to backport a potential PR that is using the `Transformer` option to all branches.

**Comment by christarazi** [comment]
Can we close this issue given the above?
