### ISSUE TITLE
Cilium pod fails to start due to CrashLoopBackOff error in config init-container

### ISSUE THREAD

**Issue by pasi-romo-idealo** [cilium/cilium#24949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium pod of the cilium daemonset fails occasionally to start due to CrashLoopBackOff-error in the config init-container on a newly created node. We have configured the node with following taint:
```
node.cilium.io/agent-not-ready=true:NoExecute
```
i.e. for kubernetes the node is Ready at this point, but it won't accept any actual workload. We are using karpenter for node scheduling, which is also affected by this problem because Karpenter sees the node as Ready even though it is not able schedule any new workloads on it and won't therefore spin up more nodes. This error occurs currently on one specific cluster several times a week.

### Cilium Version

We are using a custom build image based on cilium:v1.13.1, which has been patched with this fix for bottlerocket:
https://github.com/cilium/cilium/pull/23953

### Kernel Version

5.15.102

### Kubernetes Version

v1.24

### Sysdump

We have generated the sysdump, but it is too big to be attached here. If required we can provide it to you separately. Here is the output we got while collecting the sysdump:

![sysdump_screenshot](https://user-images.githubusercontent.com/79519247/232772453-54608445-dbdf-41cf-aeae-d5630f6e6a8d.png)

### Relevant log output

```shell
Here is the kubectl describe from the failing cilium-pod:


Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        DaemonSet/cilium
Init Containers:
  config:
    Container ID:  containerd://a7f91c4c1845ce5f053cd676518965793a32b6e9a916eb3a831318bb22d10ef9
    Image:         939049018659.dkr.ecr.eu-central-1.amazonaws.com/cilium:v1.13.1-idealobuild.1@sha256:d0b35d32667b0b9a19a0dd6e2038651d3a796f578646fe6d90cb2d5385b56a9e
    Image ID:      939049018659.dkr.ecr.eu-central-1.amazonaws.com/cilium@sha256:d0b35d32667b0b9a19a0dd6e2038651d3a796f578646fe6d90cb2d5385b56a9e
    Port:          <none>
    Host Port:     <none>
    Command:
      cilium
      build-config
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   -allow-config-keys strings        List of configuration keys that are allowed to be overridden (e.g. set from not the first source. Takes precedence over deny-config-keys
      --deny-config-keys strings         List of configuration keys that are not allowed to be overridden (e.g. set from not the first source. If allow-config-keys is set, this field is ignored
      --dest string                      Destination directory to write the fully-resolved configuration. (default "/tmp/cilium/config-map")
      --enable-k8s-api-discovery         Enable discovery of Kubernetes API groups and resources with the discovery API
  -h, --help                             help for build-config
      --k8s-api-server string            Kubernetes API server URL
      --k8s-client-burst int             Burst value allowed for the K8s client
      --k8s-client-qps float32           Queries per second limit for the K8s client
      --k8s-heartbeat-timeout duration   Configures the timeout for api-server heartbeat, set to 0 to disable (default 30s)
      --k8s-kubeconfig-path string       Absolute path of the kubernetes kubeconfig file
      --node-name string                 The name of the node on which we are running. Also set via K8S_NODE_NAME environment. (default "ip-10-32-226-151.eu-central-1.compute.internal")
      --source strings                   Ordered list of configuration sources. Supported values: config-map:<namespace>/name - a ConfigMap with <name>, optionally in namespace <namespace>. cilium-node-config:<NAMESPACE> - any CiliumNodeConfigs in namespace <NAMESPACE>.  node:<NODENAME> - Annotations on the node. Namespace and nodename are optional (default [config-map:cilium-config,cilium-node-config:kube-system])

Global Flags:
      Exit Code:    1
```

We see this log output on all the pods, which are running on the node with the affected cilium-pod:
```
Error from server: no preferred addresses found; known addresses: []
```
```


### Anything else?

The pods are running in AWS on EC2-instances:
```
System Info:
  Kernel Version:                 5.15.102
  OS Image:                       Bottlerocket OS 1.13.3 (aws-k8s-1.24)
  Operating System:               linux
  Architecture:                   amd64
  Kubelet Version:                v1.24.10-eks-08ad9cc
  Kube-Proxy Version:             v1.24.10-eks-08ad9cc
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ajaykumarmandapati** [comment]
@ldelossa 

1. It wouldn't be possible for us to use to the upstream version of cilium due to [this](https://github.com/cilium/cilium/pull/23953) bug, the network wouldn't come up at all.
2. We rely on Karpenter for the creation of Nodes and without it we cannot perform any tests, unfortunately.

Please find the cilium dump here - https://drive.google.com/file/d/1_QDBRVtsPerBHxwWZhbjYZXpjYxoIGqD/view?usp=sharing

**Comment by ajaykumarmandapati** [comment]
Hi ! Anything more that we can provide here?

**Comment by pasi-romo-idealo** [comment]
We have noticed that this problem occurs more frequently in those clusters, which are running lots of small workloads and use the consolidation-functionality of the karpenter. In this kind of cluster consolidation causes new nodes to be more frequently replaced (new nodes are being started, workloads moved over, old nodes removed) and we see this cilium error occurring more often. After disabling the consolidation we have noticed that this specific error can still occur but more seldom.

**Comment by pasi-romo-idealo** [comment]
In the end we were able to figure out that this issue is actually related to Bottlerocket (https://github.com/bottlerocket-os/bottlerocket/issues/3143). We are now using the latest release (Bottlerocket OS 1.14.2), which seems to have resolved this issue.
