### ISSUE TITLE
No connectivity between nodes with K8s 1.9

### ISSUE THREAD

**Issue by enzian** [cilium/cilium#2495]
When deploying cillium on a Kubernetes 1.9 Cluster, all packages between nodes are dropped.

**Comment by enzian** [comment]
@tgraf has more debugging information from my cluster

**Comment by tgraf** [comment]
```
time="2018-01-11T14:36:39Z" level=error msg="bpf: Unable to update in tunnel endpoint map" error="Unable to update element: invalid argument" ipAddr="f00d::acd:0:0:0/112"
```

**Comment by tgraf** [comment]
We have tracked this down to Kubernetes 1.9 installing a different set of iptables rules in the FORWARD chain which are not compatible with Cilium. Looking for a fix.

**Comment by enzian** [comment]
cool, thanks! In return I will write a tutorial for on how to set up a >1 Node cluster with cilium! (which I could not find yet!)

**Comment by enzian** [comment]
I did get Cilium running on a 1.8.7 cluster! :-)

**Comment by enzian** [comment]
hey, just wanted to check back in an thank you for addressing this :-)
