### ISSUE TITLE
Inconsistence between global and per-endpoint cilium options

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2496]
It seems there is some inconsistence between cilium daemon runtime options and endpoint options. The inconsistence should be fixed by following the rules:

- [ ] 1 - `cilium config` should print which options are mutable and not mutable at runtime. Plus it should print the values available for each options.

(RFC output)
```
$ cilium config
Options (Mutable)      | Enabled / Disabled
-------------------------------------------------
Conntrack              | Enabled
ConntrackAccounting    | Enabled
ConntrackLocal         | Disabled
Debug                  | Enabled
DropNotification       | Enabled
PolicyTracing          | Disabled
TraceNotification      | Enabled
-------------------------------------------------
Options (Mutable)      | Always / Default / Never
-------------------------------------------------
PolicyEnforcement        always
-------------------------------------------------
Options (Imutable)
-------------------------------------------------
k8s-configuration        /var/lib/cilium/cilium.kubeconfig
k8s-endpoint             
```

- [ ] 2 - `cilium endpoint config` should print witch options are mutable and not mutable at runtime. Plus it should print the values available for each options.

(RFC output)
```
$ cilium endpoint config 173
Options (Mutable)      | Enabled / Disabled
-------------------------------------------------
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Enabled
DropNotification         Enabled
NAT46                    Disabled
TraceNotification        Enabled
-------------------------------------------------
Options (Mutable)      | Always / Default / Never
-------------------------------------------------
EgressPolicy             Disabled
IngressPolicy            Disabled
```

- [ ] 3 - `cilium config` should **always** overwrite any endpoint's option

Example for the `Debug` option
```
$ cilium config
...
Debug     Enabled
...
$ cilium endpoint config 173
...
Debug     Disabled
...
$
$ cilium config Debug=Enabled
$ cilium config
...
Debug     Enabled
...
$ cilium endpoint config 173
...
Debug     Enabled
...
```

- [ ] 4 - `cilium endpoint config` should **always** take precedence over the same daemon's option **when changed**

Example for the `Debug` option
```
$ cilium config
...
Conntrack  Disabled
Debug      Disabled
...
$ cilium endpoint config 173
...
Conntrack  Enabled
Debug      Disabled
...
$
$ cilium endpoint config 173 Debug=Enabled
$ cilium config
...
Conntrack  Disabled
Debug      Disabled
...
$ cilium endpoint config 173
...
Conntrack  Enabled
Debug      Enabled
...
```
(Note that Conntrack endpoint's option remained unchanged to `Enabled` even the daemon's option was set as `Disabled`)
If later one, daemon would set up `cilium config Debug=false`, endpoint's option `Debug` would also be set to false.

**Comment by tgraf** [comment]
In the eyes of a user, all options are mutable. When we say non-mutable, we mean options which are only mutable at startup. They are still mutable with a restart of the agent.

I would split this into two high level sections:

```
Runtime options (mutable at runtime):
  Conntrack        Enabled        (Enabled/Disabled)

Startup options:
  IPv4             Enabled        (Enabled/Disabled)
```

We discussed a couple of times in the past whether a global config change should overwrite all endpoints. I'm fine either way but we should add a flag which allows to opt-out or opt-in. So either `--apply-to-endpoints` or `--preserve-endpoint-config`.

**Comment by ianvernon** [comment]
Seems related-to #1368.
