### ISSUE TITLE
Vagrant/CI: Add support for openSUSE distribution

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium#2497]
Currently, our Vagrantfile and packer box supports only Ubuntu as a distribution.

This issue is about allowing to use openSUSE distro in cilium's Vagrant environment. That will require providing some distribution-related abstraction in Vagrantfile and provisioning scripts, which will also open possibilities of supporting another distributions, if anyone will be interested.

TODO:
- [x] create a repository `cilium/packer-opensuse-tumbleweed` for maintaining a Vagrant box based on openSUSE
- [ ] modify the Vagrantfile
  - [ ] consume the `DISTRIBUTION` environment variable in Vagrantfile, which will determine which distro is used (the default value will be "ubuntu")
  - [ ] wrap the part of Vagrantfile, which derermines , in `case` or `if` clauses which will set the proper values of `config.vm.box` and `config.vm.box_version`, according to `DISTRIBUTION` env var and the Vagrant provider
- [ ] modify provisioning scripts
  - [ ] install different packages by different package manager on different distros
- [ ] modify `Jenkinsfile` and anything which contain information about CI jobs in cilium/bpf-ci-scripts/
  - [ ] change the `continuous-integration/jenkins/pr-head` job name to `continuous-integration/jenkins/ubuntu/pr-head`
  - [ ] introduce the new job `continuous-integration/jenkins/opensuse/pr-head` which will set up Vagrant with the proper `DISTRIBUTION` variable

Please let me know if I missed some point.

Other, related (but not required) ideas which could be helpful:

- ~using some configuration management system (salt, ansible etc.) for provisioning Vagrant VMs~
  - ~bash scripts which support multiple distributions may be unreadable~
  - ~at the same time, configuration management systems usually provide nice abstraction around distributions and hopefully we will need to just define the different lists of packets for each distro~
- we need to have all the needed packages in the boxes and provisioning scripts should work on every distribution

**Comment by tgraf** [comment]
Talk to @eloycoto as there is some work going on to simplify the `Vagrantfile` going forward.

**Comment by vadorovsky** [comment]
Yes, @eloycoto, I would appreciate your opinion. Feel free to ping me on Slack as well.

**Comment by vadorovsky** [comment]
Here is my packer configuration which I'm working on now:

https://github.com/mrostecki/cilium-packer-opensuse-tumbleweed

The work is still in progress. I will create some repo with Vagrantfile based soon - hopefully the only difference will be the box and getting rid of all `apt` commands which we have in the main repo.

/cc @eloycoto

**Comment by eloycoto** [comment]
Hi @mrostecki 

I was working in the update of the Ubuntu version, and I added envoy too. Here you have the changes if you want to copy

https://github.com/cilium/packer-ci-build/pull/7/files

Regards

**Comment by vadorovsky** [comment]
@eloycoto great, thank you, I will include those changes in my box soon.

Currently, I'm using the following minimalistic Vagrantfile for playing with my box https://github.com/mrostecki/cilium-vagrant-playground
I managed to build cilium and run tests in it. I think that I will keep playing with that separate repo until all the major changes in Vagrantfile you're currently planning will be merged. Then we can try to agree how we can include the openSUSE support upstream. WDYT?

**Comment by eloycoto** [comment]
Ok! works for me ;-)
