### ISSUE TITLE
Extremely slow agent startup

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#24987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Rolling upgrade to v1.12.9
2. each cilium agent pod is not ready for 2-3m

### Cilium Version

`1.12.9 e0bb30a 2023-04-17T23:54:19+02:00 go version go1.18.10 linux/amd64`

### Kernel Version

`Linux ip-10-200-14-243 5.15.0-1033-aws #37~20.04.1-Ubuntu SMP Fri Mar 17 11:39:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.22.17-eks-48e63af`

### Anything else?

When startup is slow, it correlates with cluster size (some clusters don't have this issue)

For the time until cilium starts, all I get is:
```
# cilium status
Get "http:///var/run/cilium/cilium.sock/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
```

I do see a bunch of `clang` and `tc` commands running in the background during this time.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Is this a regression? Do you have data on Cilium's startup performance on earlier versions?

**Comment by dctrwatson** [comment]
> Is this a regression? Do you have data on Cilium's startup performance on earlier versions?

It's been awhile since we did the v1.12.8 upgrade rollout, so I can't say with as much certainty.

I just restarted a handful of agents (that are still v1.12.8) in equally as large clusters, and they took only ~30s to startup.

**Comment by aanm** [comment]
Can you get a sysdump? Thank you

**Comment by dctrwatson** [comment]
> Can you get a sysdump? Thank you

Which part(s) are you specifically looking for? Unfortunately some of the data in the sysdump cannot be shared without some sanitization.

**Comment by dctrwatson** [comment]
For v1.12.9, looks like startup time is correlated with pod count (endpoints/identities/services) of a cluster

**Comment by aanm** [comment]
@dctrwatson the cilium logs would also be useful.

**Comment by aanm** [comment]
@dctrwatson also, do you have a pprof from the first ~90s of a v1.12.8 agent startup?

**Comment by dctrwatson** [comment]
> @dctrwatson the cilium logs would also be useful.

[cilium.log.zip](https://github.com/cilium/cilium/files/11278402/cilium.log.zip)

> FYI I can't open the pprof-trace on my side.

I just untar'd and zip'd the directory `cilium-bugtool --get-pprof` output (github won't let me upload `.tar.gz`)

> @dctrwatson also, do you have a pprof from the first ~90s of a v1.12.8 agent startup?

No, I would need to downgrade a cluster to get that. Also, v1.12.8 agents are Ready in only 20-30s

**Comment by dctrwatson** [comment]
I tried to get pprof of a v1.12.8, but so far I haven't figured out how to get it out of the pod without it getting cut off. So here's the largest tar I've been able to get out of a pod so far

[cilium-v1.12.8.zip](https://github.com/cilium/cilium/files/11278665/cilium-v1.12.8.zip)

**Comment by dctrwatson** [comment]
Just ended up using tried and true `exec -- cat | tar x`, lol

[cilium-v1.12.8.zip](https://github.com/cilium/cilium/files/11278739/cilium-v1.12.8.zip)

**Comment by dctrwatson** [comment]
Here's a new one from v1.12.9, hopefully you can open pprof-trace from this one:

[cilium-v1.12.9.zip](https://github.com/cilium/cilium/files/11278854/cilium-v1.12.9.zip)

**Comment by gandro** [comment]
@dctrwatson Could you give us an indication of the cluster size? How many pods do you have?

**Comment by dctrwatson** [comment]
> @dctrwatson Could you give us an indication of the cluster size? How many pods do you have?

The cluster where that pprof was taken has:
~9k endpoints
~7k identities
~2k network policies
~7k services
~10k pods
~200 nodes
