### ISSUE TITLE
Cilium connectivity test fails on clean install in k3s with "Error looking up localhost from pod"

### ISSUE THREAD

**Issue by oasisvali** [cilium/cilium#25015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After a clean install into a multi-node multi-cloud k3s cluster (with 2 nodes), `cilium connectivity test` fails with the following:

```
ℹ️  Monitor aggregation detected, will skip some flow validation steps
🐛 Validating Deployments...
⌛ [] Waiting for deployments [client client2 echo-same-node] to become ready...
⌛ [] Waiting for deployments [echo-other-node] to become ready...
⌛ [] Waiting for CiliumEndpoint for pod cilium-test/client-6f6788d7cc-g7jl2 to appear...
⌛ [] Waiting for CiliumEndpoint for pod cilium-test/client2-bc59f56d5-d77wq to appear...
⌛ [] Waiting for pod cilium-test/client-6f6788d7cc-g7jl2 to reach DNS server on cilium-test/echo-same-node-9f8754876-nbwlv pod...
⌛ [] Waiting for pod cilium-test/client2-bc59f56d5-d77wq to reach DNS server on cilium-test/echo-same-node-9f8754876-nbwlv pod...
⌛ [] Waiting for pod cilium-test/client-6f6788d7cc-g7jl2 to reach DNS server on cilium-test/echo-other-node-5c58b8cf8b-nt9vz pod...
🐛 Error looking up localhost from pod cilium-test/client-6f6788d7cc-g7jl2 to server on pod cilium-test/echo-other-node-5c58b8cf8b-nt9vz: command terminated with exit code 1:
🐛 Error looking up localhost from pod cilium-test/client-6f6788d7cc-g7jl2 to server on pod cilium-test/echo-other-node-5c58b8cf8b-nt9vz: context deadline exceeded:
connectivity test failed: timeout reached waiting lookup for localhost from pod cilium-test/client-6f6788d7cc-g7jl2 to server on pod cilium-test/echo-other-node-5c58b8cf8b-nt9vz to succeed (last error: context deadline exceeded)
```

The same connectivity test passes in single-node mode

### Cilium Version

cilium-cli: v0.13.2 compiled with go1.20.2 on darwin/amd64
cilium image (default): v1.13.1
cilium image (stable): v1.13.1
cilium image (running): v1.13.1

### Kernel Version

Linux ip-172-26-15-8 5.15.0-1030-aws #34-Ubuntu SMP Mon Jan 23 20:13:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.26.3 (k3s)

### Anything else?

Cilium was installed into the cluster using `cilium install --encryption wireguard --helm-set l7Proxy=false`
k3s cluster was created with the following server config:
```
node-external-ip: <>
flannel-backend: none
kube-apiserver-arg: 'service-node-port-range=80-32767'
disable-network-policy: true
```

Both nodes are not part of a subnet and can only reach each other via their public IPs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ldelossa** [comment]
Hello @oasisvali can you provide a sysdump for this issue?

**Comment by oasisvali** [comment]
@ldelossa here's the sysdump:
[cilium-sysdump-20230420-210047.zip](https://github.com/cilium/cilium/files/11291371/cilium-sysdump-20230420-210047.zip)

I did have cilium with encryption working on a multi-node k3s cluster recently, with the connectivity tests passing. The only difference I can think of with this setup where the tests are failing, is that in the previous cluster, the nodes were able to reach each other over Internal IP. With the current cluster, the nodes can only reach each other over their External IP.

Do you think that might be the root cause? If yes, is there a cilium configuration I can set to get it working in this case?

**Comment by oasisvali** [comment]
After a bit more digging around, I believe root cause of this issue is the fact that my cluster nodes are on seperate subnets. Creating the cluster with k3s, the private IPs of each node becomes its INTERNAL IP. When cilium gets installed, and the connectivity test is run, a pod on node 1 trying to reach a pod on node 2 gets routed to this INTERNAL IP (which doesn't work as both nodes are on seperate subnets).

I would have thought that installing cilium with wireguard encryption would automatically route all pod-to-pod packets over the wireguard interface, which I assume communicates via the node's EXTERNAL IP. Is there any way to get this configuration to work?

**Comment by oscgu** [comment]
I'm experiencing a similar issue. My master and worker nodes are running in different subnets, which makes the connectivity tests fail, when they try to reach each others dns server. Both subnets are connected through a vSwitch and servers can talk with eachother though outside of cilium

**Comment by oscgu** [comment]
Following this https://docs.cilium.io/en/v1.13/operations/system_requirements/ and removing the leftovers from previously installed cnis seems to have resolved my issue

**Comment by oasisvali** [comment]
I did manage to get my setup working without any connectivity between the 2 subnets by setting the nodes public IP as it's internal IP & external IP using the k3s config flags. This makes all the cilium connectivity tests pass as the nodes can now find each other at their public IPs. I've also enabled wireguard encryption but I'm not sure if setting the k3s node internal IP to the public IP is an anti-pattern
