### ISSUE TITLE
CIDRGroup references metric should count live references only and not count nonexistent CIDRGroups

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#25022]
The `cilium_cidrgroup_policies` metric counts all references of CIDRGroups inside a CNP even if the CIDRGroup doesn't exist (i.e. reference points to a nonexistent object).

**Comment by shawnh2** [comment]
hi, i'm willing to take this, assign please

**Comment by shawnh2** [comment]
hi, sorry to bother, I'm new to Cilium, need make some sure about this issue.

in this issue, I need do some works in here:

https://github.com/cilium/cilium/blob/191b672af20feda6e43f52fa1c429f1639cb50fd/pkg/k8s/watchers/cilium_network_policy.go#L257

to make sure that in this function, the empty `rule.CIDRGroupRef` needs to be skipped, 

https://github.com/cilium/cilium/blob/191b672af20feda6e43f52fa1c429f1639cb50fd/pkg/k8s/watchers/cilium_cidr_group.go#L187-L194

so the final implementation will be something like:

```go
		if len(rule.Cidr) == 0 {
			if len(rule.CIDRGroupRef) == 0 {
				cidrGroupRefs = append(cidrGroupRefs, string(rule.CIDRGroupRef))
			}
		}
```

**Comment by JonasKs** [comment]
I believe this can be closed?
