### ISSUE TITLE
CI: Move K8sUpdates to ci-e2e

### ISSUE THREAD

**Issue by brb** [cilium/cilium#25037]
The `K8sUpdate` tests the following:

* Cilium upgrade: $STABLE -> $LATEST -> $STABLE.
* No drops due to missed tail calls.
* Pod 2 pod connectivity with and without L7 netpol.
* No interruption in E/W LB long-lived connections.

We are going to move the upgrade test to a GHA. If we move to the `ci-e2e`, then we will increase a coverage for different configurations.

In addition, we should test N/S LB long-lived connections from non-Cilium host too (maybe other interruptions in connections too  to exercise more packet paths?).

The way I see the move is the following:
* At the end of `ci-datapath` connectivity tests destroy Kind cluster, and then create a new one.
* Install $STABLE cilium.
* Run `cilium-cli connectivity --test-upgrade --setup` (TBI) which will create necessary test pods and do sanity checks.
* Upgrade to $LATEST with `cilium-cli install`.
* Run `cilium-cli connectivity --test-upgrade` run the tests.
* Downgrade to $STABLE with `cilium-cli install`.
* Run `cilium-cli connectivity --test-upgrade` again.

**Comment by joestringer** [comment]
How do you propose `cilium-cli connectivity --test-upgrade` should work? I note that one of the key features of the existing test is to be asynchronously running connections through the datapath while the agent is upgraded / downgraded, then we count how many dropped flows etc. there are.

**Comment by brb** [comment]
> How do you propose cilium-cli connectivity --test-upgrade should work?

I'm suggesting to introduce a two-stage test case.

First (`--test-upgrade --setup`), it deploys necessary pods and services. The pods do all sorts of connections (same, as the `migrate-svc` does today). If any of the connection fails (unexpectedly), then that pod restarts. This bumps the restart counter.

Second, we do the Cilium upgrade.

Finally (`--test-upgrade`), it checks that no restarts happened after the upgrade.

**Comment by pchaigno** [comment]
FYI, Donia is adding some infra. to the CLI that would probably be useful here as well, to check counters after the upgrade and downgrade: https://github.com/cilium/cilium-cli/pull/1575.

**Comment by gandro** [comment]
I think the new pipelines causes CI flakes: https://github.com/cilium/cilium/issues/29476
