### ISSUE TITLE
Slack invite emails not received

### ISSUE THREAD

**Issue by thecubed** [cilium/cilium#25045]
Hello Cilium!

Using https://cilium.herokuapp.com/ to send a Slack invite, no invite emails are received. I have checked spam, and tried with multiple different email providers as well.

The API response from `POST /invite` seems to indicate a success though:
```
{
  "msg": "WOOT. Check your email!",
  "redirectUrl": "https://cilium.slack.com/"
}
```

This appears similar to #24447, however no error is received from the Slack invite app.

Thanks for looking into this!

**Comment by RomanKrasavtsev** [comment]
The same. Would love to join the community, but I haven't received an invitation so far.

**Comment by ti-mo** [comment]
Thanks for the reports, @thebsdbox is looking into this.

**Comment by thebsdbox** [comment]
At this point (from the debugging I've been able to do, the issue appears to be with Slack) we get a `200` back from their api endpoint and no errors. I'll keep testing, but we may need to raise an issue with them to troubleshoot.

**Comment by thebsdbox** [comment]
The URL https://slack.cilium.io/ should now allow you to sign up to slack again! (apologies for the down-time, we will need to keep an eye on this for a little while)

**Comment by ecerulm** [comment]
@thebsdbox , the  https://slack.cilium.io/  seems to require a @linuxfoundation.org or @meetingtomorrow.com email address. I've opened #34689

**Comment by xmulligan** [comment]
Should be fixed now, thanks for reporting
