### ISSUE TITLE
CI: ingress-conformance-test "An Ingress with a trailing slashes in a prefix path rule..."

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#25040]
## CI failure

The scenario "An Ingress with a trailing slashes in a prefix path rule should ignore the trailing slash and send traffic to the matching backend service" [flaked for no obvious reason](https://github.com/cilium/cilium/actions/runs/4752645068/jobs/8443248157). After discussing with servicemesh colleagues, they agreed it looked like a flake.

Relevant failure:
```
--- Failed steps:

  Scenario: An Ingress with a trailing slashes in a prefix path rule should ignore the trailing slash and send traffic to the matching backend service # features/path_rules.feature:181
    Then The Ingress status shows the IP address or FQDN where it is exposed # features/path_rules.feature:93
      Error: waiting for ingress status update: timed out waiting for the condition
```

CI logs:
[logs_1367515.zip](https://github.com/cilium/cilium/files/11295673/logs_1367515.zip)

Unfortunately, the artifacts were lost before I created this issue. Sorry!

**Comment by lmb** [comment]
Had [this one as well](https://github.com/cilium/cilium/actions/runs/5057424583/jobs/9076167700?pr=25484#step:17:294):

```
   Scenario Outline: An Ingress with no rules should send all requests to the default backend # features/default_backend.feature:21
    Then The Ingress status shows the IP address or FQDN where it is exposed # features/default_backend.feature:19
      Error: waiting for ingress status update: timed out waiting for the condition
```

[cilium-sysdump-out.zip.zip](https://github.com/cilium/cilium/files/11545134/cilium-sysdump-out.zip.zip)

**Comment by giorio94** [comment]
Another similar occurrence: https://github.com/cilium/cilium/actions/runs/5068113186/jobs/9100001126

```
  Scenario: An Ingress with prefix path rules should and send traffic to the matching backend service # features/path_rules.feature:154
    Then The Ingress status shows the IP address or FQDN where it is exposed # features/path_rules.feature:93
      Error: waiting for ingress status update: timed out waiting for the condition
```

[cilium-sysdump-out.zip](https://github.com/cilium/cilium/files/11554385/cilium-sysdump-out.zip)

**Comment by giorio94** [comment]
Another occurrence: https://github.com/cilium/cilium/actions/runs/5134217364/jobs/9237894893?pr=25499

```
   Scenario Outline: An Ingress with no rules should send all requests to the default backend # features/default_backend.feature:21
    Then The Ingress status shows the IP address or FQDN where it is exposed # features/default_backend.feature:19
      Error: waiting for ingress status update: timed out waiting for the condition
```

[cilium-sysdump-out.zip](https://github.com/cilium/cilium/files/11616362/cilium-sysdump-out.zip)

**Comment by giorio94** [comment]
Another similar one: https://github.com/cilium/cilium/actions/runs/5241198442/jobs/9462977273?pr=26070

```
   Scenario: An Ingress with prefix path rules should be case sensitive # features/path_rules.feature:134
    Then The Ingress status shows the IP address or FQDN where it is exposed # features/path_rules.feature:93
      Error: waiting for ingress status update: timed out waiting for the condition
```

[cilium-sysdump-out.zip](https://github.com/cilium/cilium/files/11722227/cilium-sysdump-out.zip)
