### ISSUE TITLE
bugtool: improve Documentation for Running cilium-bugtool is a K8s env

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#2510]
Many cilium users will be running cilium-bugtool in a k8s environment.  However, running bugtool in in the cilium pod using a command like (kubectl exec -it -n kube-system cilium-cnwxt -- cilium-bugtool) means that the resulting log archive is created inside the container, making it hard to upload to github, etc.   I had to run "kubectl cp kube-system/cilium-cnwxt:/tmp/cilium-bugtool-859913324.tar  cilium-bugtool-859913324.tar", but this was not documented anywhere.  

Also: 
- When I ran it, it hung on the "exec: cilium [debuginfo]" line for quite some time.  I almost gave up and killed it.  Showing some kind of progress here, or letting people know that it may take a while to run would be useful. 
- This generates a .tar file, but .tar files are not supported as attachments for github issues.   I had to zip my tar file.   Why not just generate a zip file?   Seems like it will be better for a user reporting issues both because it is a more standard file-type to open, and it will be smaller to transmit, especially if the logs collected are substantial.

**Comment by danwent** [comment]
Also, the docs are a little confusing, as they say "If kubectl is detected it will search for Cilium pods."   However, this seems to assume that users have a version of the cilium-debugtool binary on the host they are using for running kubectl.  At least that was not the case for me.  I only had it accessible in the cilium pod on my k8s deployment.

**Comment by aalemayhu** [comment]
If you look at the [troubleshooting][0] section this is mentioned there. Would those instructions have helped you if they were in `... --help`? Adding progress indicators is a good idea. Initially, the default format was tar but zip and back to tar. IIRC @tgraf suggested using tar. I guess the archive format can be configurable supporting tar, gzip, zip, etc.

Thanks.

[0]: http://docs.cilium.io/en/latest/troubleshooting/#single-node-bugtool

**Comment by danwent** [comment]
@scanf sorry, i must have just not read that section all the way to the bottom, as you're right, its right there.   Feel free to close this, or copy the other issues, which are more minor to another issue.

**Comment by aalemayhu** [comment]
No worries. You are feedback was valuable. I will address some of the items and close this later. 

Thanks.

**Comment by aalemayhu** [comment]
Archive format will be tracked in #2306 and the progress indicator in #2542. The follow up is in #2543.
