### ISSUE TITLE
Vagrant: Lack of certificates when setting up k8s environment

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium#2511]
Running `K8S=1 NWORKERS=1 ./contrib/vagrant/start.sh` command on the current master results in the following error:

```
==> cilium-k8s-node-2: ----- 03-install-kubernetes-worker.sh: main: Downloading kube-proxy... Done!
==> cilium-k8s-node-2: cp: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/examples/kubernetes-ingress/scripts/certs/ca-k8s.pem': No such file or directory
==> cilium-k8s-node-2: cp: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/examples/kubernetes-ingress/scripts/certs/ca-etcd.pem': No such file or directory
==> cilium-k8s-node-2: cp: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/examples/kubernetes-ingress/scripts/certs/etcd-cilium-key.pem': No such file or directory
==> cilium-k8s-node-2: cp: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/examples/kubernetes-ingress/scripts/certs/etcd-cilium.pem': No such file or directory
==> cilium-k8s-node-2: cp: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/examples/kubernetes-ingress/scripts/certs/k8s-cilium-key.pem': No such file or directory
==> cilium-k8s-node-2: cp: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/examples/kubernetes-ingress/scripts/certs/k8s-cilium.pem': No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by eloycoto** [comment]
@mrostecki that it has been fixed with the new vagrant box. 

https://github.com/cilium/packer-ci-build/blob/master/provision/install.sh#L128


cc @ianvernon

**Comment by aanm** [comment]
@mrostecki The certificates are generated inside the first VM (`cilium-k8s-master`) on the `/home/vagrant/go/src/github.com/cilium/cilium/examples/kubernetes-ingress/scripts/certs` directory.
The setup scripts for the 2nd VM (`cilium-k8s-node-2`) make the assumption the certificates will be available under `/home/vagrant/go/src/github.com/cilium/cilium/examples/kubernetes-ingress/scripts/certs`.

As a workaround can you start the VMs with `NFS=1`? This will run NFS on the guest VMs which will allow the generation of the certificates to be stored on the host and they will be read by `cilium-k8s-node-2` later on.

**Comment by vadorovsky** [comment]
@aanm That workaround works, thank you.

What should we do about that in general? Just update the box and close this issue? I assume that it will be done during the changes in Vagrantfile you plan to do in the nearest future?

**Comment by ianvernon** [comment]
@aanm does this mean we are required to start the VMs with `NFS=1`? If that is the case, we should get VirtualBox guest additions installed in the VM to avoid these sorts of issues. In the `packer-ubuntu-16.10` repository, there is an open issue to do this: https://github.com/cilium/packer-ubuntu-16.10/issues/20 . We could remove the NFS option after doing this from the Vagrant scripts since shared folders would be enabled by default in that case? The more simple the Vagrantfile is with fewer options, the better.

**Comment by ianvernon** [comment]
As lead triage master this week, assigning to both @eloycoto and @aanm .

**Comment by aanm** [comment]
@mrostecki Since we switched to virtualbox shared folders can this be closed?

**Comment by vadorovsky** [comment]
@aanm sure, let's close it
