### ISSUE TITLE
cilium-terraform-provider

### ISSUE THREAD

**Issue by rflorenc** [cilium/cilium#25113]
Is there any interest in a cilium-terraform-provider?

I've started this as a hobby project and thought I would ask wether someone would find it useful so it can be developed further: https://github.com/rflorenc/terraform-provider-cilium

Could maybe have a place in IAC use cases were clusters are entirely managed via terraform, without helm or cilium-agent binaries

It uses the cilium kubernetes client only for now, and does not use or access cilium.sock.

**Comment by ti-mo** [comment]
Hi @rflorenc, thanks for sharing! Are you looking for something in particular?

For reaching more potential users, feel free to advertise your project in Cilium Slack. We can always set you up with a Slack channel if that's something you'd be interested in. Maybe at some point you could propose adding a link to your project to the Cilium documentation if it sees enough uptake in the community.

**Comment by rflorenc** [comment]
Hi @ti-mo 

Was looking for some feedback in general since there are already different ways to interact with or install cilium. 

Not specifically related to the existing code since it is just a base, but more in terms of how useful this might be. Maybe from someone who uses terraform more actively even.

I'll try to hop on slack then, thanks!
