### ISSUE TITLE
Document CiliumCIDRGroup CRD

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#25123]
Add example use cases and examples for CiliumCIDRGroup CRD: https://github.com/cilium/cilium/pull/24638

**Comment by gailsuccess** [comment]
@christarazi , I would love to hack on this.

**Comment by JonasKs** [comment]
Hey @christarazi , I can start on this next week if you'd like.

**Comment by christarazi** [comment]
Awesome thanks, will assign you

**Comment by JonasKs** [comment]
Sorry for the delay, I'll get to this in the weekend.

**Comment by JonasKs** [comment]
I've created a draft PR, which will be ready for review tomorrow.
