### ISSUE TITLE
migrate main branch workflows to use cilium-cli with helm installation mode

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#25156]
we can start migrating main branch workflows to use cilium-cli with helm installation mode. these workflows need to be migrated:

- [x] workflows/conformance-aks.yaml https://github.com/cilium/cilium/pull/26382
- [x] workflows/conformance-aws-cni.yaml https://github.com/cilium/cilium/pull/25820
- [x] workflows/conformance-clustermesh.yaml https://github.com/cilium/cilium/pull/25834
- [x] workflows/conformance-eks.yaml https://github.com/cilium/cilium/pull/25820
- [x] workflows/conformance-externalworkloads.yaml https://github.com/cilium/cilium/pull/26382
- [x] workflows/conformance-gateway-api.yaml @sayboras https://github.com/cilium/cilium/pull/25608
- [x] workflows/conformance-gke.yaml https://github.com/cilium/cilium/pull/25820
- [x] workflows/conformance-ingress.yaml https://github.com/cilium/cilium/pull/25609
- [x] workflows/conformance-k8s-kind.yaml https://github.com/cilium/cilium/pull/25916
- [x] [workflows/conformance-k8s-network-policies.yaml](https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-k8s-network-policies.yaml) it uses `helm install` to install cilium, so nothing to update.
- [x] [workflows/conformance-k8s-kind-network-policies.yam](https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-k8s-kind-network-policies.yaml) https://github.com/cilium/cilium/pull/26692
- [x] workflows/conformance-kind-proxy-daemonset.yaml https://github.com/cilium/cilium/pull/25081
- [x] [workflows/tests-l4lb.yaml](https://github.com/cilium/cilium/blob/main/.github/workflows/tests-l4lb.yaml) it doesn't use cilium-cli to install cilium.
- [x] workflows/tests-smoke-ipv6.yaml: https://github.com/cilium/cilium/pull/25493
- [x] workflows/tests-smoke.yaml: https://github.com/cilium/cilium/pull/25493

helm installation mode should be largely compatible with the classic mode, but we have removed some obsolete flags, so we might need to make minor adjustments to these workflow files. 

ref: https://github.com/cilium/cilium-cli/releases/tag/v0.14.0

**Comment by tklauser** [comment]
Looks like all workflows were migrated. I've updated the issue description with links to all PRs. Closing as completed.
