### ISSUE TITLE
helm chart for hubble-ui deployment removed nodeSelector and tolerations on 1.11.15 release

### ISSUE THREAD

**Issue by BryanStenson-okta** [cilium/cilium#25181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[This PR](https://github.com/cilium/cilium/commit/ec8d4ff6042fa7f3cc7b33388ebbca43c468590b#r110939182) removed nodeSelector and toleration settings for the hubble-ui deployment.

The current 1.11 branch (1.11.16) `values.yaml` seems to suggest this was a mistake, as there are defaults listed: https://github.com/cilium/cilium/blob/v1.11.16/install/kubernetes/cilium/values.yaml#L939-L946

### Cilium Version

1.11.15

### Kernel Version

n/a

### Kubernetes Version

1.25

### Anything else?

Unless this was intentional, I can put a PR to revert.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rolinh** [comment]
This issue has been fixed by #25182.
