### ISSUE TITLE
Proposal: generate API code within Docker container

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2520]
The generation of API code is currently done using `make generate-api`, which requires external dependencies installed on the host on which the command is run (go-swagger). Given that go dependency management allows for anyone to install any version of a dependency, the build may fail due to an old / incompatible version of go-swagger being installed on the host. If this Make target triggers a build using a Docker container, we can put the go-swagger dependency into the container and not worry about this issue. We can then update the version of go-swagger in the Docker container as necessary, and the Make target can consume these changes with a simple change of the tag of the container containing go-swagger.

**Comment by aanm** [comment]
> Given that go dependency management allows for anyone to install any version of a dependency

With [golang dep](https://github.com/golang/dep) we will be able to pick which versions we want for generators.

**Comment by ianvernon** [comment]
dep seems intriguing, but my main reservation about it is that it is still experimental. I think a Docker image with a set version of go-swagger would be best as we know for sure that it will work. It also allows us to have more control the dependencies used as opposed to relying upon the users's host machine.

**Comment by ianvernon** [comment]
Fixed by adb32c654de93ffe0ee671007bd8a0dd76350fb5 .
