### ISSUE TITLE
Key-size mismatch warning on 1.14 upgrades/downgrades

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#25224]
https://github.com/cilium/cilium/pull/23885 introduced a warning on upgrades/downgrades to/from v1.14:
```
"Key-size mismatch for BPF map" file-path=/sys/fs/bpf/tc/globals/cilium_policy_00835 new=8 old=12 subsys=bpf
```
This warning can't be avoided by users today and it is expected/non-actionable.

We need to fix that before we release v1.14.
cc @jrajahalme

**Comment by joestringer** [comment]
I agree that this warning is superfluous for the policymap and should not be emitted. If this was for the CT map / LB map / etc then I would be worried about upgrade impact, but for policymap I don't believe that there is any upgrade impact.

@ti-mo do you have some next steps in mind to resolve this issue?

**Comment by nathanjsweet** [comment]
[Here is a PR](https://github.com/cilium/cilium/pull/26656) to address this issue.

**Comment by ti-mo** [comment]
> I agree that this warning is superfluous for the policymap and should not be emitted. If this was for the CT map / LB map / etc then I would be worried about upgrade impact, but for policymap I don't believe that there is any upgrade impact.
> 
> @ti-mo do you have some next steps in mind to resolve this issue?

@joestringer Replied in https://github.com/cilium/cilium/pull/26656#issuecomment-1628518404. There's now Map.Recreate(), this can already be used for the policy map.

**Comment by nathanjsweet** [comment]
We should close my PR and this issue.

When I tested this, I didn't get the key-size mismatch warning on upgrade. Instead, I got this "info" message:
```
level=info msg="Unpinning map with incompatible properties" file-path=/sys/fs/bpf/tc/globals/cilium_policy_02406 new="Type:LPMTrie KeySize:12 ValueSize:24 MaxEntries:16384 Flags:1" old="Type:Hash KeySize:8 ValueSize:24 MaxEntries:16384 Flags:1" subsys=bpf
```
On downgrade I did get the key-size mismatch log, but we're obviously not going to cut a downgrade release for a log message. I think we're safe to wait for @ti-mo's [more thorough solution](https://github.com/cilium/cilium/issues/26793).

**Comment by margamanterola** [comment]
Paul mentioned that this other issue is probably due to the same problem: https://github.com/cilium/cilium-cli/issues/1858

**Comment by ti-mo** [comment]
If someone picks this up next, let's simply change this to `.Info()` for now so it still shows up in the logs but doesn't trip up tests. To actually improve the safety of accidental map recreations, some structural work needs to be done that makes this decision explicit, see https://github.com/cilium/cilium/issues/28742.

**Comment by brb** [comment]
> still shows up in the logs but doesn't trip up tests

Created this to resolve the tests issue - https://github.com/cilium/cilium-cli/pull/2110

**Comment by brb** [comment]
@margamanterola We should keep the original assignments. My CLI PR made the error log check test case to ignore the warning. Meanwhile, this issue is about silencing those warnings for fine to migrate maps, so that users don't get puzzled. I know that Timo has plans to rework the migration which would fix this issue.
