### ISSUE TITLE
servicemesh: proxylib image for the separated cilium-envoy image

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#25226]
While #25081 allows `cilium-envoy` to run as a separate container, we still have to figure out how/if to pair a proxylib image (`libcilium.so`) with the external container. Proxylib uses a our stable Go extensions for Envoy API so that a Cilium agent build can add additional L7 parsers to Envoy without re-building the Envoy image. Cilium agent can then build control plane (e.g., policy) support for a given L7 protocol and ship an implementation of it as `libcilium.so` and configure Cilium Envoy filters to use it. These proxylib images are not useful by themselves, outside of them being used with Cilium. While we were shipping `cilium-envoy` within the Cilium agent image there was no problem with this, but now that we start supporting a separate cilium-envoy container image we need to figure out how to ship proxylib for it.

**Comment by mhofstetter** [comment]
Fixed with https://github.com/cilium/proxy/pull/232 & https://github.com/cilium/cilium/pull/26101
