### ISSUE TITLE
EKS Metadata hop limit for IMDSv2

### ISSUE THREAD

**Issue by savagete2860** [cilium/cilium#25232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am migrating a few EKS clusters away from another CNI (Weave) to use Cilium - both as an overlay network. The nodes on the cluster have IMDSv2 enforced with a hop limit of two. One hop for the node and one for a pod. Replacing the previous CNI with Cilium, the metadata service is unreachable with 2 hops and must be bumped to 3. I am curious why the additional hop is required and if this opens up and security concerns.

I am installing Cilium as follows:

```
helm install cilium cilium/cilium --version 1.12.9 \
  --namespace kube-system \
  --set operator.replicas=2
  --set ipam.operator.clusterPoolIPv4PodCIDRList=192.168.0.0/16
```

The underlying nodes running the Amazon EKS AMI.

To reproduce:
- EKS Cluster with IMDSv2 enforced with token hop limit of 2
- exec into a pod and run
```
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/
```
- notice the call hangs
- set token hop to 3 and re-run
- call will work

### Cilium Version

tested on 1.12.9, 1.13.1, and 1.13.2

### Kernel Version

1.23

### Kubernetes Version

1.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Do you have an example traceroute or similar that demonstrates the hops?

**Comment by savagete2860** [comment]
Adding `--set endpointRoutes.enabled=true` to the helm install fixes this issue. From the docs:

enable-endpoint-routes: "true" enables direct routing to the ENI veth pairs without requiring to route via the cilium_host interface.

I am not sure what the cilium host interface is, but if youre using cilium as an overlay network and do not use endpointRoutes with imdsv2, you need to have 3 hops set to hit the ec2 metadata service.

**Comment by alexinfoblox** [comment]
@savagete2860, when I set  `endpointRoutes.enabled=true` the network completely stopped working in the cluster?
I mean, I'm not able to aceess any services from outside the cluster. Even kubectl via Teleport stopped working. 
What might have been missed in the configuration?
