### ISSUE TITLE
Duplicate identities with large scale cluster

### ISSUE THREAD

**Issue by vipul-21** [cilium/cilium#25251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With AKS cluster of 1000 nodes, 1000 deployments each deployment having 2 unique labels and 60 replicas each. I am seeing duplicate identity for same set of labels.
For example, in the screenshot of `ciliumendpoints` you see the pods of same deployment each having same identity `25605` but one of them having `8785`
![image](https://user-images.githubusercontent.com/8600441/236018976-60cc601a-f06b-434c-8f7c-d7043ac659ad.png)
The cilium identity are as follows( you can see the labels are same.):
```
- apiVersion: cilium.io/v2
  kind: CiliumIdentity
  metadata:
    creationTimestamp: "2023-05-03T17:40:32Z"
    generation: 1
    labels:
      app: vipul-testing
      io.cilium.k8s.policy.cluster: default
      io.cilium.k8s.policy.serviceaccount: default
      io.kubernetes.pod.namespace: vipul-testing
      is-real: "true"
      real-dep-lab-00356-00001: val
      real-dep-lab-00356-00002: val
    name: "8785"
    resourceVersion: "10542470"
    uid: 3fe031d1-e527-4df4-b99b-86c438977451
  security-labels:
    k8s:app: vipul-testing
    k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: vipul-testing
    k8s:io.cilium.k8s.policy.cluster: default
    k8s:io.cilium.k8s.policy.serviceaccount: default
    k8s:io.kubernetes.pod.namespace: vipul-testing
    k8s:is-real: "true"
    k8s:real-dep-lab-00356-00001: val
    k8s:real-dep-lab-00356-00002: val
 ``````````````````````
 ```
- apiVersion: cilium.io/v2
  kind: CiliumIdentity
  metadata:
    creationTimestamp: "2023-05-03T17:40:03Z"
    generation: 1
    labels:
      app: vipul-testing
      io.cilium.k8s.policy.cluster: default
      io.cilium.k8s.policy.serviceaccount: default
      io.kubernetes.pod.namespace: vipul-testing
      is-real: "true"
      real-dep-lab-00356-00001: val
      real-dep-lab-00356-00002: val
    name: "25605"
    resourceVersion: "10526664"
    uid: 4863bc19-21ae-4364-ad41-b52c6a47fb82
  security-labels:
    k8s:app: vipul-testing
    k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: vipul-testing
    k8s:io.cilium.k8s.policy.cluster: default
    k8s:io.cilium.k8s.policy.serviceaccount: default
    k8s:io.kubernetes.pod.namespace: vipul-testing
    k8s:is-real: "true"
    k8s:real-dep-lab-00356-00001: val
    k8s:real-dep-lab-00356-00002: val
```

This is just one example, I am able to get more duplicate identities for same set of labels.

Added the cilium-bugtool for the cilium-bugtool for cilium agent for pod `real-dep-00356-5b46966c69-8mfr5`   with identity 8785

### Cilium Version

```
cilium-cli: v0.13.2 compiled with go1.20.2 on linux/amd64
cilium image (default): v1.13.1
cilium image (stable): v1.13.2
cilium image (running): 1.12.5.1
```

### Kernel Version

`Linux DESKTOP-IS3TR2T 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"dc2f9dc64421983f0f7839da8ab4ab6d4673daad", GitTreeState:"clean", BuildDate:"2023-04-08T13:29:19Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

Cilium bugtool - [cilium-agent-identity-8785.zip](https://github.com/cilium/cilium/files/11390470/cilium-agent-identity-8785.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
This is a known behaviour given that multiple nodes can be attempting to allocate identities for the same set of labels concurrently. Cilium tolerates this and correctly handles forwarding for the multiple identities. Are you osberving any connectivity issue or anything related to this behaviour?

**Comment by vipul-21** [comment]
Thanks @joestringer. Yeah the connectivity is not a problem. I didn't see anything related to this that impacted the connectivity.

**Comment by nandak522** [comment]
So @joestringer duplicate identity numbers is not a problem ?
