### ISSUE TITLE
IPsec connectivity issues after upgrading from 1.11 to 1.12.9

### ISSUE THREAD

**Issue by jasonaliyetti** [cilium/cilium#25292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We upgraded from 1.11.14 to 1.12.9.  We use ENI custom networking (seperate subnets for the host on eth0 and for pods on eth1+) with ipsec enabled.

Shortly after upgrading we started to get sporadic but disruptive connectivity issues.  Communication between healthy pods will fail at random with a connection timeout and connectivity is not restored for several minutes.  We turned ipsec off and the issue stopped.  When we re-enabled ipsec the issue returns albeit with lower frequency.  

### Cilium Version

1.12.9

### Kernel Version

5.15.106-64.140.amzn2.x86_64

### Kubernetes Version

EKS 1.24

### Relevant log output

```shell
This might be unrelated, but I do notice a new log message indicating "Unable to delete the IPsec route OUT from the host routing table" for a CIDR we don't use.  I think this is something being set on the CiliumNode's .spec.ipam.podCIDRs field as though we were using cluster-pool networking instead of ENI.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jasonaliyetti** [comment]
I forgot to mention that I do not see any drops in Hubble.

**Comment by joestringer** [comment]
This seems potentially related to the release note:
https://docs.cilium.io/en/v1.12/operations/upgrade/#upgrade-notes

cc @pchaigno

**Comment by jasonaliyetti** [comment]
Yeah, we saw that release note.  There was the expected behavior during the cutover, but after that we saw sporadic connectivity problems continue.  We also saw this happen with fresh nodes created after the upgrade as well as old ones from before the upgrade.  I can double check, but I do not think we saw any ipsec error counts increase.

**Comment by pchaigno** [comment]
As discussed on Slack, we will need a sysdump to be able to help debug this.

**Comment by jasonaliyetti** [comment]
[config.zip](https://github.com/cilium/cilium/files/11424436/config.zip)

Thus far this is what I am able to share -- it's just the configuration for our setup to give an idea of our networking.  We have had to rollback to 1.11.14 in the environments where this was occurring.  We are currently going to attempt to reproduce this issue in the next week or two.  If further information from the sysdump is needed I can work on getting that into a publicly shareable state after we are able to reproduce this.

I did confirm before we rolled back that we did not see a continued increase in xfrm errors for ipsec when the issue occurs.  We also see traffic reaching the destination pod with no drops indicated by Hubble or `cilium monitor` on either end of the connection.

**Comment by pchaigno** [comment]
Thanks! I checked the files; I'm not seeing anything obviously wrong.

**Comment by jasonaliyetti** [comment]
We are still working to reproduce this in a development cluster.  One of the challenges is that it only seems to occur with a sufficient number of nodes, usually around 30.  We can get the issue to occur, but by the time we sort out which nodes are impacted so that they can be targeted for the sysdump the issue has resolved (the sysdump issues a warning on a cluster of this size and indicates we need to target a subset) .  We're going to keep working on this, but it's taking some time.

**Comment by abbyglaubit** [comment]
We were unable to reproduce in a development cluster, so we tried to upgrade from 1.11.14 to 1.12.10, and saw the same sporadic but disruptive connectivity issues about 2 hours after upgrading. We took sysdumps of a few affected nodes and are in the process of redacting them so we can share them. There's a lot of sensitive information in the sysdumps, though, and it will take a bit to redact - is there any guidance you all can provide on what information from the sysdumps you need to debug?

**Comment by jasonaliyetti** [comment]
We also tried upgrading to 1.11.18 after seeing a lot of fixes around ENI + IPSEC.  The issue still occurs unfortunately.

**Comment by abbyglaubit** [comment]
@pchaigno Here is a sysdump of three nodes from when the issue was occurring. Sensitive information such as pod names, namespaces, and labels has been redacted.
[cilium-sysdump-redacted.zip](https://github.com/cilium/cilium/files/12080615/cilium-sysdump-redacted.zip)

**Comment by jasonaliyetti** [comment]
We attempted deploying v1.13.4 and still see connectivity issues with IPSec enabled.  This was on a fresh cluster that was created with v1.13.4 and no prior Cilium version was running.

**Comment by abbyglaubit** [comment]
Hi were you all able to take a look at the sysdump? We also saw connectivity issues after upgrading from 1.13.4 to 1.14.2

**Comment by pchaigno** [comment]
We were expecting v1.14.2 to fix all IPsec bugs except one around iptables-nft (so not affecting you according to the last sysdump you shared). Would you be able to collect a new sysdump after the upgrade attempt to v1.14.2?

**Comment by abbyglaubit** [comment]
We did and will follow up but we'll need a day or so to redact the sysdump! Also we were able to get 1.13.4 working on a fresh cluster (i.e. no upgrade)

**Comment by abbyglaubit** [comment]
here is a sysdump from the upgrade attempt to v1.14.2 
[cilium-sysdump-20231006-102352-redacted.zip](https://github.com/cilium/cilium/files/12898264/cilium-sysdump-20231006-102352-redacted.zip)

**Comment by pchaigno** [comment]
I don't see anything out of place except for the few `XfrmInError` and `XfrmFwdHdrError` errors. As per the docs, those can be expected but maybe we missed some impact they have.
```
Encryption: IPsec                     
Keys in use: 1                         
Max Seq. Number: 0xbeef0/0xffffffff
Errors: 61                        
	XfrmInError: 12                        
	XfrmFwdHdrError: 49                        
```
cc @jrfastab 

@abbyglaubit Regarding the connectivity issues after upgrading to v1.14.2, was it transient or did it never recover? Was all cross-node connectivity affected as far as you could see?

**Comment by abbyglaubit** [comment]
The cluster never recovered. The connectivity issues were sporadic (i.e. users reported seeing 504s about ~50% of the time). As far as I can all services/nodes in the cluster were affected.

**Comment by pchaigno** [comment]
> The connectivity issues were sporadic (i.e. users reported seeing 504s about ~50% of the time).

That sounds a bit weird. IPsec is all L3 so wouldn't cause 504s. Do you use L7 or DNS policies? Or maybe timeouts (from packet drops) in one service are causing these 504s in another, frontend service?
