### ISSUE TITLE
BPF Masquerading does not work with a bridge

### ISSUE THREAD

**Issue by volatilemolotov** [cilium/cilium#25303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium tests fail on the node that has a linux bridge configured and should be used as a masquerade interface. All pod-to-cidr and pod-to-world test fail.
For some reason cilium agent on that node reports:
 ```
 Masquerading:            BPF   []   10.0.7.0/24 [IPv4: Enabled, IPv6: Disabled]
```
note the missing interface name and in logs we can see:
```
level=debug msg="Ignoring bridge-like device" device=br0 subsys=linux-datapath
```

Not sure if its relevant but only this node causes issues and its the node that only has a bridge. 

### Cilium Version

1.13.1, 1.13.2

### Kernel Version

6.2.13-200.fc37.x86_64

### Kubernetes Version

Server Version: v1.24.8+k0s

### Sysdump

[cilium-sysdump-20230507-151821.zip](https://github.com/cilium/cilium/files/11415047/cilium-sysdump-20230507-151821.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Looks like that check was added in #17560, and you can override device detection with the `devices` Helm setting, which allows specifying which devices should be used by Cilium, it seems.

Tagging in sig/datapath though to check my work.

**Comment by volatilemolotov** [comment]
Problem is that all of the devices need to have the same name (or something with wildcard) in order for `devices` to work. 

I might try to manually change the names but that would bring my cluster down and not sure if i can do that now.
Ill try to create a lab on vms and test it that way. 

Looking at the PR it seems that bridge devices are unsupported?

**Comment by volatilemolotov** [comment]
I did not see a way to set devices per node, so probably the solution will be renaming the interfaces. 

i can solve that with udev rules. The question here is perhaps is this a good design?

**Comment by youngnick** [comment]
I checked with some other folks, and the udev rules way is currently the best available solution. Thanks @pchaigno!

**Comment by volatilemolotov** [comment]
Managed to change the names and now cilium status shows the correct interface for BPF Masquerade. 

The issue still remains. That node cannot reach anything outisde and i have no clue where to look further

**Comment by volatilemolotov** [comment]
Disregard the last comment. I had a another interface that i used to debug that had a lesser metric in the route table. 

All works now and using udev/systemd to change interface names helped. 

Thanks for guidance

**Comment by youngnick** [comment]
Okay, thanks @volatilemolotov for the issue and for keeping us up to date. I'll close this one out for now, feel free to comment if you need it reopened.
