### ISSUE TITLE
Request to backport dashboards helm chart from `main` to 1.13

### ISSUE THREAD

**Issue by jcpunk** [cilium/cilium#25360]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

I'd like to use the dashboard integration in cillium main with the 1.13 branch

**Describe the feature you'd like**

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Backport the commits from :
https://github.com/cilium/cilium/commit/f46499b50db8d4b3bea6f1a3df8d8e4800679ca4
https://github.com/cilium/cilium/commit/bdbb1294f251f2309845278920e087e2cb92167e

**Comment by squeed** [comment]
As a general rule, we don't backport new features. Given that this touches the helm charts pretty heavily, and doesn't fix any end-user issues, it qualifies as a feature.

**Comment by squeed** [comment]
I'm going to close this for now; feel free to re-open if you'd like to consider this further.

**Comment by jcpunk** [comment]
With 1.14 a ways off, having these dashboards natively in the helm chart would provide a nice quality of life improvement.

I'm not sure how to re-open this ticket...
