### ISSUE TITLE
Ginkgo CI: migrate image eloycoto/cilium_dependencies:latest to a Cilium-managed repository

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2536]
This is the image used to run the unit tests, and as such should be owned by cilium on DockerHub. Determine what is needed to make the unit tests work in the cilium-owned builder images.

**Comment by ianvernon** [comment]
@eloycoto do you have the Dockerfile that you used to build this perchance? We have had a lot of churn in our Dockerfiles since the Ginkgo framework was merged, and I'd like to get the work you did under the `cilium/` DockerHub Organization.

**Comment by eloycoto** [comment]
Hi @ianvernon 

Is this  one, should be ok with Cilium Dependencies image, I think that now has go-bindata.

https://github.com/eloycoto/cilium_dependencies
