### ISSUE TITLE
CFP: New metric to signal when IPSec sequence number overfow is imminent

### ISSUE THREAD

**Issue by owais** [cilium/cilium#25392]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

Cilium users are expected to re-key IPSec when the IPSec sequence number overflows. There is an open ticket to document this [here](https://github.com/cilium/cilium/issues/22747). Users can rotate the key periodically but that might not be good enough for some special cases with way too much traffic and/or unexpected traffic.

It was [proposed](https://github.com/cilium/cilium/issues/22924) to add a prometheus metric that exposes the sequence number directly but was [blocked due to security concerns](https://github.com/cilium/cilium/pull/23084#pullrequestreview-1260998964)

**Describe the feature you'd like**

A metric to hint that overflow is imminent and keys need to be rotated.

**(Optional) Describe your proposed solution**

Instead of exposing the sequence number directly as a metric, I propose cilium exports a boolean metric called `xfrm_sequence_number_threshold_reached` and set it to `1` once the sequence number passes the threshold. The threshold can be a user defined number. If even exposing this is not desirable for security reasons, cilium can add some leeway and randomness to emit the metric. For example, if the threshold is set to `500` and leeway set to `100`, then cilium MUST set the metric value to `1` any time after the sequence number reaches `400` and before it reaches `600`. Leeway value can be user provided or auto-generated by cilium. 

This would allow users to monitor sequence overflow & automate key rotation without exposing sensitive information via prometheus.

**Comment by eyenx** [comment]
We would also highly appreciate this :+1:

**Comment by owais** [comment]
This is a feature request and still quite valid. Don't think stuff like this should auto-close. It may not be prioritized right now but that doesn't mean it isn't desired at all.
