### ISSUE TITLE
Abnormal SNATed IP from cluster to external web service

### ISSUE THREAD

**Issue by skyblueted** [cilium/cilium#25437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are two machine types as worker nodes in our cluster. 
Recently, we found our traffics are blocked due to security policy of destination when we access to external web service
The web service just **allow** traffic from two network range (_**10.0.0.0/8 & 100.0.0.0/8**_), and **deny** private network _**172.16.0.0/12**_

We captured packets by tcpdump when we connect to outside service.
The result showed the **SNATed IP became cilium_host instead of node ip**.

The weird result we observed only occurred in one machine model
We are not sure cilium ebpf program could cause different SNATed logic according to machine type

**Expect result:**
The pod ip should be translated to node ip

**Actual result:**
The pod ip became cilium_host ip

### Cilium Version

1.12.8

### Kernel Version

5.15.0-48-generic

### Kubernetes Version

v1.22.15

### [cilium configmap]
```
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  annotate-k8s-node: "true"
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-lb-acceleration: disabled
  bpf-lb-algorithm: maglev
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-mode: hybrid
  bpf-lb-sock: "true"
  bpf-lb-sock-hostns-only: "true"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "41"
  cluster-name: cluster41
  cni-uninstall: "true"
  custom-cni-conf: "false"
  debug: "false"
  devices: ' eno5  ens3f0  '
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-ip-masq-agent: "true"
  enable-ipv4: "true"
  enable-ipv4-egress-gateway: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "true"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-session-affinity: "true"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "true"
  hubble-event-buffer-capacity: "16383"
  hubble-listen-address: :4244
  hubble-metrics: dns:query drop tcp flow icmp http
  hubble-metrics-server: :9965
  hubble-socket-path: /var/run/cilium/hubble.sock
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "true"
  ipam: kubernetes
  ipv4-native-routing-cidr: 172.18.0.0/15
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  prometheus-serve-addr: :9962
  proxy-prometheus-port: "9964"
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  skip-cnp-status-startup-clean: "false"
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: disabled
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
```

### =======   Abnormal node information  =======
**cilium nonmasquerade setting**
```
root@worker-1:/home/cilium# cat /etc/config/ip-masq-agent
nonMasqueradeCIDRs:
- [172.16.0.0/12](http://172.16.0.0/12)
- [100.111.0.0/16](http://100.111.0.0/16)
- [10.90.102.0/24](http://10.90.102.0/24)
masqLinkLocal: false
```
**cilium nat table**
_172.18.12.206 is cilium_host ip_
We accessed to outside service (100.110.97.3), it didn't hit nonMasqueradeCIDRs and native routing cidr
However, it finally was translated cilium_host ip
```
root@worker-1:/home/cilium# cilium bpf nat list | grep 100.110.97.3

TCP OUT 172.18.12.165:35058 -> 100.110.97.3:80 XLATE_SRC 172.18.12.206:35058 Created=1899296sec HostLocal=0
TCP IN 100.110.97.3:80 -> 172.18.12.206:39574 XLATE_DST 172.18.12.165:39574 Created=1899296sec HostLocal=0
TCP IN 100.110.97.3:80 -> 172.18.12.206:52616 XLATE_DST 172.18.12.190:52616 Created=1899296sec HostLocal=0
TCP IN 100.110.97.3:80 -> 172.18.12.206:39602 XLATE_DST 172.18.12.165:39602 Created=1899296sec HostLocal=0
TCP OUT 172.18.12.165:39554 -> 100.110.97.3:80 XLATE_SRC 172.18.12.206:39554 Created=1899296sec HostLocal=0
TCP IN 100.110.97.3:80 -> 172.18.12.206:52518 XLATE_DST 172.18.12.190:52518 Created=1899296sec HostLocal=0
TCP OUT 172.18.12.165:39594 -> 100.110.97.3:80 XLATE_SRC 172.18.12.206:39594 Created=1899296sec HostLocal=0
TCP OUT 172.18.12.165:50282 -> 100.110.97.3:80 XLATE_SRC 172.18.12.206:50282 Created=1899296sec HostLocal=0
TCP IN 100.110.97.3:80 -> 172.18.12.206:39672 XLATE_DST 172.18.12.165:39672 Created=1899296sec HostLocal=0
TCP OUT 172.18.12.165:50390 -> 100.110.97.3:80 XLATE_SRC 172.18.12.206:50390 Created=1899296sec HostLocal=0
TCP OUT 172.18.12.165:39650 -> 100.110.97.3:80 XLATE_SRC 172.18.12.206:39650 Created=1899296sec HostLocal=0
```
**node interface setting**
```
 root@worker-1:~# ip a show dummy0
10: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 46:41:32:6c:7d:bb brd ff:ff:ff:ff:ff:ff
    inet 100.111.11.213/32 scope global dummy0
       valid_lft forever preferred_lft forever
    inet6 fe80::4441:32ff:fe6c:7dbb/64 scope link
       valid_lft forever preferred_lft forever

root@worker-1:~# ip a show cilium_host
12: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether 96:ec:aa:03:5e:d6 brd ff:ff:ff:ff:ff:ff
    inet 172.18.12.206/32 scope global cilium_host
       valid_lft forever preferred_lft forever
    inet6 fe80::94ec:aaff:fe03:5ed6/64 scope link
       valid_lft forever preferred_lft forever
```

### =======   Normal node information (another model)  =======
**cilium nonmasquerade setting is same because it is from configmap**

**cilium nat table**
_100.111.13.207 is node ip_
```
root@worker-2:/home/cilium# cilium bpf nat list | grep 100.110.97.3

TCP OUT 172.18.8.93:48486 -> 100.110.97.3:80 XLATE_SRC 100.111.13.207:48486 Created=8032257sec HostLocal=0
TCP IN 100.110.97.3:80 -> 100.111.13.207:42164 XLATE_DST 172.18.8.93:42164 Created=8032257sec HostLocal=0
TCP IN 100.110.97.3:80 -> 100.111.13.207:36594 XLATE_DST 172.18.8.93:36594 Created=8032257sec HostLocal=0
TCP OUT 172.18.8.93:41580 -> 100.110.97.3:80 XLATE_SRC 100.111.13.207:41580 Created=8032257sec HostLocal=0
TCP OUT 172.18.8.93:35716 -> 100.110.97.3:80 XLATE_SRC 100.111.13.207:35716 Created=8032257sec HostLocal=0
TCP OUT 172.18.8.93:42178 -> 100.110.97.3:80 XLATE_SRC 100.111.13.207:42178 Created=8032257sec HostLocal=0
TCP IN 100.110.97.3:80 -> 100.111.13.207:55442 XLATE_DST 172.18.8.93:55442 Created=8032257sec HostLocal=0
```

**node interface setting**
```
root@worker-2:~# ip a show dummy0
10: dummy0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 66:29:f4:c0:06:3f brd ff:ff:ff:ff:ff:ff
    inet 100.111.13.207/32 scope global dummy0
       valid_lft forever preferred_lft forever
    inet6 fe80::6429:f4ff:fec0:63f/64 scope link
       valid_lft forever preferred_lft forever

root@worker-2:~# ip a show cilium_host
12: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
    link/ether 9e:89:6b:a7:50:c6 brd ff:ff:ff:ff:ff:ff
    inet 172.18.8.148/32 scope link cilium_host
       valid_lft forever preferred_lft forever
    inet6 fe80::9c89:6bff:fea7:50c6/64 scope link
       valid_lft forever preferred_lft forever
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
>There are two machine types as worker nodes in our cluster.
The weird result we observed only occurred in one machine model

What's different about the two worker nodes? Also, since you've enabled BPF masquerading, you can check the `devices` config on both the nodes. What's the output of `cilium status | grep -i masquerading` when run from cilium agent pods on both the nodes?

**Comment by skyblueted** [comment]
`What's different about the two worker nodes?`
=> You can consider their cpu, memory and disk specs (HDD/SSD) are different

`What's the output of cilium status | grep -i masquerading when run from cilium agent pods on both the nodes?`
=> In fact, we are set same network configuration to all worker nodes with GitOps

**Abnormal node**
```
k8c exec -ti cilium-s9d47 -- cilium status | grep -i Masquerading
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
Masquerading:            BPF (ip-masq-agent)   [dummy0, eno5, ens3f0]   172.18.0.0/13 [IPv4: Enabled, IPv6: Disabled]
```

**Normal node**
```
k8c exec -ti cilium-wlc8p -- cilium status | grep -i Masquerading
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init)
Masquerading:            BPF (ip-masq-agent)   [dummy0, eno5, ens3f0]   172.18.0.0/13 [IPv4: Enabled, IPv6: Disabled]
```

### Workaround
Today, we found some way to temporarily fix the issue
( Hint: Delete cilium pod is useless)

- Reboot
- **Delete cilium_host link, restart cilium pod, and redeploy application**

Unfortunately, the symptom is gone in our cluster after experiment 😥
May we collect other information if the issue come back next time?

**Comment by aditighag** [comment]
It's hard to debug this without a sysdump from the affected node. 
If the network devices configuration is similar across both the nodes, one possible explanation could be that masquerading was somehow performed by interfering iptable chains. 

>Unfortunately, the symptom is gone in our cluster after experiment 😥
May we collect other information if the issue come back next time?

Yes, please do. In the meantime, maybe we can close the issue?

**Comment by skyblueted** [comment]
`It's hard to debug this without a sysdump from the affected node.`
-> We have planned to prepare sysdump from the affected node in this week.

**Update**:
Recently, we found a way to easily reproduce the situation which occurred in **all** types worker nodes

We also buildup new cluster with cilium 1.12.8, its nodes have the same symptom
It caused severe impact, because dns lookup is failed when coredns forward dns query to external dns
(Reason: There are no private network routes in external dns)

**Reproduce Steps**:
1. kubectl drain <target node>
2. ssh <target node> "kubeadm reset"
3. kubectl delete no <target node>
4. ssh <target node> "reboot"
5. Join <target node> to cluster
6. Access to outside web service, and capture packets in the same time by tcpdump
7. Analyse tcpdump result, check snat ip is whether node ip or cilium_host ip

In cilium 1.12.8, we are easily reproduced the issue.
However, we didn't encountered the problem with the same reproduce steps after we rollback to cilium 1.12.4

**Comment by skyblueted** [comment]
Hi @aditighag ,
The sysdump file is from affected worker nodes of another cluster.
We hope that can help you to debug.
[cilium-bugtool-20230526-054424.tar.zip](https://github.com/cilium/cilium/files/11576321/cilium-bugtool-20230526-054424.tar.zip)

**Comment by skyblueted** [comment]
It still happening when we upgraded to cilium **1.13.3** from 1.12.4

We upgraded cilium yesterday, and select one worker node to do "Reproduce Steps".
After 1 day, the outing ip of pods in selected worker node is masqueraded as **cilium_host** instead of node ip when traffic  is from inside to outside

Wrong source nat ip will be blocked in the world because _cilium_host ip is in private network range_.

**Comment by rogerBridge** [comment]
Do you have any progress? We are having the same problem @skyblueted

**Comment by rogerBridge** [comment]
> Do you have any progress? We are having the same problem @skyblueted

but my snated address is not cilium_host, but pod's ip address

**Comment by rogerBridge** [comment]
> > Do you have any progress? We are having the same problem @skyblueted
> 
> No. We still didn’t know the root cause. Currently, the issue has not reoccurred within a month after we upgraded to 1.12.11
> 
> _BTW, there are some clusters need udp dsr mode to keep client ip in our environment. After we changed the configmap online and restarted cilium daemonset. We also observed the snat issue again. But the situation is different from 1.12.4 & 1.13.3_

could U tell me more info for your situation(udp dsr mode, with snat error), we also having the same problem(cilium version 1.13.3)

**Comment by skyblueted** [comment]
> > > Do you have any progress? We are having the same problem @skyblueted
> > 
> > 
> > No. We still didn’t know the root cause. Currently, the issue has not reoccurred within a month after we upgraded to 1.12.11
> > _BTW, there are some clusters need udp dsr mode to keep client ip in our environment. After we changed the configmap online and restarted cilium daemonset. We also observed the snat issue again. But the situation is different from 1.12.4 & 1.13.3_
> 
> could U tell me more info for your situation(udp dsr mode, with snat error), we also having the same problem(cilium version 1.13.3), I can't find its root cause : (

After we changed bpf-lb-mode from hybrid to dsr mode, the snated source address also became cilium_host ip instead of node ip.

You maybe can inspect your target address is included in **nonMasqueradeCIDRs** or **native routing** cidr.

If it is subnet in one of cidrs list, the result is reasonable.

**Comment by skyblueted** [comment]
Give a status update.
We also ran into same issue in **1.12.11**.
We found the root cause is related to the **_out of private network range we chose as pod cidr_**.
The result causes the node IP on the dummy interface and the Cilium host IP to be checked as public IPs for BPF masquerade.

It can refer to the code located below: 
[the link](https://github.com/cilium/cilium/blob/1.12.11/pkg/node/address.go#L210C1-L243C2).
Trace the firstGlobalV4Addr function, which uses the IsPublicAddr function. IsPublicAddr includes the privateIPBlocks array from initPrivatePrefixes in [the link](https://github.com/cilium/cilium/blob/1.12.11/pkg/ip/ip.go#L769C1-L797C2).

**Workaround**:
Define **DeriveMasqIPAddrFromDevice** in cilium configmap to restrict the BPF masquerade IP to a fixed device name
