### ISSUE TITLE
Add renovate bot as a GitHub action

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#25457]
Once we are able to run renovate as a GitHub action we should be able to specify any [postupgradecommands](https://docs.renovatebot.com/self-hosted-configuration/#allowedpostupgradecommands) that we wish. This will be helpful so that we can generate certain files after updates. For example `install/kubernetes/cilium/values.yaml` which is generated from the `install/kubernetes/cilium/values.yaml.tmpl` could make use of this. Another example is the `make -C images/ update-runtime-image` and `make -C images/ update-builder-image` scripts that are executed after upgrading.

Instructions are in https://github.com/renovatebot/github-action

**Comment by swastik959** [comment]
@aanm I have tired to create  a pr please review it

**Comment by swastik959** [comment]
As for the other update automation I think we can just add those in the renovate.json5 file
