### ISSUE TITLE
Enabling L7 ingress observability leads to "invalid packet" being dropped

### ISSUE THREAD

**Issue by demikl** [cilium/cilium#25455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When adding a L7 HTTP network policy or adding the annotation `policy.cilium.io/proxy-visibility="<Ingress/8080/TCP/HTTP>"` on a pod (in this example, `httpbin`), an incoming packet is sent to the envoy proxy but then is discarded with a log "invalid packet" as seen in hubble logs below.

### Cilium Version

1.14.0-snapshot.1

### Kernel Version

5.10.176-157.645.amzn2 from Amazon AMI amazon-eks-node-1.24-v20230411

### Kubernetes Version

AWS EKS 1.24 cluster running cilium (1.14.0-snapshot.1) as the only CNI, with kube-proxy replacement

### Relevant log output

```shell
May 3 13:58:49.960: contour/contour-envoy-94dccb664-9td4v:35838(ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080(ID:16530) to-stack FORWARDED (TCP Flags: SYN)
May 3 13:58:49.961: contour/contour-envoy-94dccb664-9td4v:35838(ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080(ID:16530) to-proxy FORWARDED (TCP Flags: SYN)
May 3 14:00:06.441: 100.89.175.191:60682(host) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080(ID:16530) to-proxy FORWARDED (TCP Flags: SYN)
May 3 14:00:06.442: 100.89.175.191:60682(world) <> httpbin/httpbin-9fd8f7b7b-ztdnm:8080(ID:16530) Invalid packet DROPPED (TCP Flags: SYN)
```

`100.89.175.191` is the IP address of the node on which the httpbin pod is running and might be related to the liveness probe of the pod coming from kubelet.

### Anything else?

The logs from above are from hubble, when sending an HTTP GET from my computer to a pod httpbin-9fd8f7b7b-ztdnm through an ingress managed by Contour/Envoy:

```shell
$ cilium hubble port-forward&
$ hubble observe -n httpbin -f
```

I think it's worth mentioning that egress observability works fine: if I put the annotation on the contour-envoy pod: `policy.cilium.io/proxy-visibility="<Egress/8080/TCP/HTTP>"`:
    
    May  3 14:10:29.720: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-proxy FORWARDED (TCP Flags: SYN)
    May  3 14:10:29.720: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) <- httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
    May  3 14:10:29.720: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-proxy FORWARDED (TCP Flags: ACK)
    May  3 14:10:29.720: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-proxy FORWARDED (TCP Flags: ACK, PSH)
    May  3 14:10:29.721: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-endpoint FORWARDED (TCP Flags: SYN)
    May  3 14:10:29.721: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) <- httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-stack FORWARDED (TCP Flags: SYN, ACK)
    May  3 14:10:29.722: 10.206.54.18 (ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) http-request FORWARDED (HTTP/1.1 GET http://httpbin-ouicloud-container-dev-paris.ouicloud-container-dev.aws.vsct.fr/get)
    May  3 14:10:29.723: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-endpoint FORWARDED (TCP Flags: ACK)
    May  3 14:10:29.723: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
    May  3 14:10:29.724: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) <- httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-stack FORWARDED (TCP Flags: ACK, PSH)
    May  3 14:10:29.725: 10.206.54.18 (ID:47439) <- httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) http-response FORWARDED (HTTP/1.1 200 4ms (GET http://httpbin-ouicloud-container-dev-paris.ouicloud-container-dev.aws.vsct.fr/get))
    May  3 14:10:29.725: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) <- httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
    May  3 14:10:31.725: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) <- httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-stack FORWARDED (TCP Flags: ACK, FIN)
    May  3 14:10:31.726: contour/contour-envoy-94dccb664-9td4v:52056 (ID:47439) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080 (ID:16530) to-endpoint FORWARDED (TCP Flags: ACK, FIN)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Can you attach the full sysdump collected from your cluster? 

>When adding a L7 HTTP network policy or adding the annotation policy.cilium.io/proxy-visibility="<Ingress/8080/TCP/HTTP>" on a pod (in this example, httpbin), an incoming packet is sent to the envoy proxy but then is discarded with a log "invalid packet" as seen in hubble logs below.

Can you clarify if there are no "invalid packet" drops in the absence of L7 visibility policies?

**Comment by demikl** [comment]
I can confirm that there is no "invalid packet" drops when L7 policies are not set.
Please find attached the sysdump as requested.
[cilium-sysdump-20230517-170615.zip](https://github.com/cilium/cilium/files/11499716/cilium-sysdump-20230517-170615.zip)

**Comment by aditighag** [comment]
I also noticed that the same node ip was assigned a different identity for the packet that was dropped - 

```
May 3 14:00:06.441: 100.89.175.191:60682(host) -> httpbin/httpbin-9fd8f7b7b-ztdnm:8080(ID:16530) to-proxy FORWARDED (TCP Flags: SYN)
May 3 14:00:06.442: 100.89.175.191:60682(world) <> httpbin/httpbin-9fd8f7b7b-ztdnm:8080(ID:16530) Invalid packet DROPPED (TCP Flags: SYN)
```

You might want to check if there are any interfering iptable rules on the node.

**Comment by demikl** [comment]
What should I check against those iptable rules ? Do you want me to dump them here, or is there a pattern I should look after ?

**Comment by LarsBingBong** [comment]
@demikl did you ever figure this out. Seeing something similar. Thank you.

**Comment by demikl** [comment]
Hi, nop, I don't know why this occured. I'm running cilium 1.14.3 now, and I've just run the same test, and it works now:

```
$ hubble observe -n httpbin -f  

Nov 17 08:28:38.782: contour/contour-envoy-fdbb9ff85-6kbw4:45502 (ID:14423285) -> httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-proxy FORWARDED (TCP Flags: SYN)
Nov 17 08:28:38.782: contour/contour-envoy-fdbb9ff85-6kbw4:45502 (ID:14423285) <- httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
Nov 17 08:28:38.782: contour/contour-envoy-fdbb9ff85-6kbw4:45502 (ID:14423285) -> httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-proxy FORWARDED (TCP Flags: ACK)
Nov 17 08:28:38.782: contour/contour-envoy-fdbb9ff85-6kbw4:45502 (ID:14423285) -> httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-proxy FORWARDED (TCP Flags: ACK, PSH)
Nov 17 08:28:38.782: 100.89.134.155:41918 (ID:14423285) -> httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-endpoint FORWARDED (TCP Flags: SYN)
Nov 17 08:28:38.782: 100.89.134.155:41918 (host) <- httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-stack FORWARDED (TCP Flags: SYN, ACK)
Nov 17 08:28:38.782: 100.89.134.155:41918 (ID:14423285) -> httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-endpoint FORWARDED (TCP Flags: ACK)
Nov 17 08:28:38.783: 100.89.134.155:41918 (ID:14423285) -> httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Nov 17 08:28:38.783: contour/contour-envoy-fdbb9ff85-6kbw4:45502 (ID:14423285) -> httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) http-request FORWARDED (HTTP/1.1 GET http://httpbin-XXXXX/get)
Nov 17 08:28:38.784: 100.89.134.155:41918 (host) <- httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-stack FORWARDED (TCP Flags: ACK, PSH)
Nov 17 08:28:38.784: contour/contour-envoy-fdbb9ff85-6kbw4:45502 (ID:14423285) <- httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Nov 17 08:28:38.784: contour/contour-envoy-fdbb9ff85-6kbw4:45502 (ID:14423285) <- httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) http-response FORWARDED (HTTP/1.1 200 2ms (GET http://httpbin-XXXXXXX/get))
Nov 17 08:28:40.786: 100.89.134.155:41918 (host) <- httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-stack FORWARDED (TCP Flags: ACK, FIN)
Nov 17 08:28:40.786: 100.89.134.155:41918 (ID:14423285) -> httpbin/httpbin-7599dbf7df-lvtvx:8080 (ID:14429560) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
```
