### ISSUE TITLE
cilium tries to attach XDP program on secondary interfaces when using ENI mode for CNI

### ISSUE THREAD

**Issue by demikl** [cilium/cilium#25453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium agent failed to restart on a node where it previously added a secondary interface (for provisioning additional pod IPs):

    level=fatal msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface eth1: invalid argument" subsys=datapath-loader

### Cilium Version

1.14.0-snapshot.1

### Kernel Version

5.10.176-157.645.amzn2 from Amazon AMI amazon-eks-node-1.24-v20230411

### Kubernetes Version

Amazon EKS v1.24

### Anything else?

I'm struggling with enabling XDP on an AWS EKS cluster. I'm using cilium for all network-related stuff, having removed aws-cni and kube-proxy. Cilium is thus responsible to attach additional ENI as required. At node bootstrap, I'm running these commands as [explained in your documentation](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#nodeport-xdp-on-aws):

    ip link set dev eth0 mtu 3498
    ethtool -L eth0 combined 2

This is working fine when a fresh node joins the cluster. However, when I restart the `cilium-xxxx` pod on that node, the `cilium-agent` container crash at startup with this message:

    level=fatal msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface eth1: invalid argument" subsys=datapath-loader

If I connect to the node and I run the same two commands as above but for `eth1` instead of `eth0`, the agent now runs fine. But that's not an option to manually connect to each instance when I need to restart the cilium daemonset :wink: .

The XDP program is not useful, as far as I understand, on any interface other than eth0, but I still need other bpf programs on eth1 and further. XDP, in my understanding, will only be used for routing NodePort trafic to a node that has a pod selected by the NodePort service, thus receiving trafic on its primary IP attached to `eth0`.

I've successfully used the following configuration (in the cilium configmap) to prevent cilium from crashing, but I'm not sure about the consequences of such a restriction (would Network Policies & observability still work ?):

    devices: eth0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
Hi @demikl, thanks for the report.

One question to make sure I understand your case 100%: what do you mean by `I still need other bpf programs on eth1 and further`? Are you attaching your own XDP progs to those interfaces? (I assume this is not the case)

What you're seeing make sense, AWS has a per-ENI address limit (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI), so those extra eth1,2,3.. interfaces need to be added in order for more IPs to be assigned to the node. I'm not sure if Cilium actually uses those interfaces to reply to ARP or if it routes any traffic over them. Have you done your own investigation? A packet capture would shed some light on this.

Good question regarding policy; I'll get some more eyes on this. If eth1+ remain unused, adding `devices: eth0` to the configmap example in [NodePort XDP on AWS](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#nodeport-xdp-on-aws) seems like a good idea. You could also deploy a udev rule on all nodes that keep eth1+ interfaces down when they're added to the node.

**Comment by borkmann** [comment]
> ip link set dev ethX mtu 3498
> ethtool -L ethX combined 2

Could you install this as udev rule on each of the nodes, so that whenever new device gets added this config is done automatically?

**Comment by borkmann** [comment]
> Either way, the user cannot be expected to react to interface additions with ethtool -L ethX combined 2, so if this kind of modification needs to be done at runtime, it should be done by Cilium.

It would be nice, although the problem is that the channel configuration might differ from device to device. You could have 2 different XDP NICs on your system and they each might require a different channel configuration. I'm not sure that Cilium would be the right place to somehow expose this somehow via crd or so to users as there is no one-size-fits-all. I think the best way would be to deploy this as udev rule on each of the nodes once, so that this setting on AWS is done automatically.

**Comment by demikl** [comment]
> One question to make sure I understand your case 100%: what do you mean by `I still need other bpf programs on eth1 and further`? Are you attaching your own XDP progs to those interfaces? (I assume this is not the case)

No, I don't. I was talking about programs that cilium might implement for network policies or whatever it is doing.

Pod trafic is outgoing from the eth interface where it's IP address is coming from, and also for incoming trafic to a pod. So, that might be eth1+.
