### ISSUE TITLE
Identity 8847360 missing from list

### ISSUE THREAD

**Issue by jimethn** [cilium/cilium#25460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am running cilium on EKS in CNI chaining mode. Every time a pod starts, cilium drops some ipv6 traffic from `8847360`.

```
$ cilium monitor --type drop
xx drop (Unsupported L3 protocol) flow 0x0 to endpoint 737, ifindex 203, file 2:2192, , identity 8847360->12727: fe80::12:54ff:fe0b:bfff -> ff02::16 143(0)
xx drop (Unsupported L3 protocol) flow 0x0 to endpoint 737, ifindex 203, file 2:2192, , identity 8847360->12727: fe80::12:54ff:fe0b:bfff -> ff02::16 143(0)
```

Verbose output shows this is ipv6 multicast neighbor solicitation.

```
Ethernet	{Contents=[..14..] Payload=[..82..] SrcMAC=f6:73:fc:ab:ab:b2 DstMAC=33:33:00:00:00:16 EthernetType=IPv6 Length=0}
IPv6	{Contents=[..40..] Payload=[..34..] Version=6 TrafficClass=0 FlowLabel=0 Length=36 NextHeader=IPv6HopByHop HopLimit=1 SrcIP=fe80::f473:fcff:feab:abb2 DstIP=ff02::16 HopByHop={ Contents=[..8..] Payload=[..34..] NextHeader=ICMPv6 HeaderLength=0 ActualLength=8 Options=[{OptionType=5 OptionLength=2 ActualLength=4 OptionData=[0, 0] OptionAlignment=[0 0]}, {OptionType=1 OptionLength=0 ActualLength=2 OptionData=[] OptionAlignment=[0 0]}]}}
ICMPv6	{Contents=[143, 0, 40, 217] Payload=[..30..] TypeCode=143(0) Checksum=10457 TypeBytes=[]}
  Packet has been truncated
  Failed to decode layer: No decoder for layer type MLDv2MulticastListenerReport
CPU 01: MARK 0x0 FROM 3861 DROP: 90 bytes, reason Unsupported L3 protocol, identity 8847360->22554, to endpoint 3861
```

I assume the source is some kube component, but what's strange is the unlisted identity `8847360` and not one of the special identities like `reserved:host` or `reserved:unmanaged`.

```
root@ip-10-20-214-85:/home/cilium# cilium identity list | grep 8847360 
root@ip-10-20-214-85:/home/cilium# 
```

I spun up a second EKS cluster, and installed cilium there, and I see the same behavior, from the same identity `8847360`, and again it does not appear in `cilium identity list`.

### Cilium Version

1.13.2

### Kernel Version

Linux ip-10-20-199-192.us-west-2.compute.internal 5.4.238-148.346.amzn2.x86_64 #1 SMP Tue Mar 28 23:37:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-ec5523e", GitCommit:"d9e9b09276855a532739ef8cb728194aa145430b", GitTreeState:"clean", BuildDate:"2023-03-20T18:46:36Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Can you attach a sysdump from the affected cluster?

**Comment by jimethn** [comment]
Sure I can provide it :)

[cilium-sysdump-20230518-101925.zip](https://github.com/cilium/cilium/files/11508532/cilium-sysdump-20230518-101925.zip)

**Comment by squeed** [comment]
I took a look at the sysdump and, oddly enough, ipv6 is also disabled for the AWS CNI plugin. I don't see any iptables rules that would set mark 0x870_000 for ipv6:

```
[0:0] -A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
[0:0] -A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
[0:0] -A KUBE-POSTROUTING -j MARK --set-xmark 0x4000/0x0
```

Likewise, ipv4 has somewhat more, but nothing too exciting.

I wonder if the identity is invalid because we're somehow parsing the packet wrong?
