### ISSUE TITLE
BPF jiffies never enabled due to missing `/proc/timer_list`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#25463]
https://github.com/cilium/cilium/pull/11434 introduced a new flag `enable-bpf-clock-probe` to use jiffies instead of `bpf_ktime_get_sec` which can be expensive. This feature however always fails to enable due to the missing `/proc/timer_list` file. I think that's because we don't mount that file in the agent container.

cc @borkmann

**Comment by pchaigno** [comment]
This probably doesn't have anything to do with missing mount because `/proc/schedstat` is available. As Timo mentioned, it's more likely due to the container runtime restricting access to `/proc/timer_list`.

**Comment by ti-mo** [comment]
Ah, I found a few GH issues related to my initial CONFIG_HZ probe replacement:
- `/proc/timer_list` is masked by both Moby and k8s as part of the default `securityContext.procMount` setting: https://github.com/kubernetes/kubernetes/issues/111962. This is still the case in `kubernetes/kubernetes` and `moby/moby` on master today. https://github.com/moby/moby/blob/1371aee3cc38134778e2e85f1a4122d1b31d344d/oci/defaults.go#L111.
- Similar bug report about the CONFIG_HZ side: https://github.com/cilium/cilium/issues/20981.
- Differences in container runtimes between various cloud providers might explain why this works on some platforms by not others. (or is it actually broken everywhere?)

A fix for this should be backported to 1.12 and 1.13 in any case.
