### ISSUE TITLE
Label-based egress support: KV store interaction

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2552]
Parent: #1488 

This ticket covers the agent-side changes to allow for label-based egress support. Synchronize information which uniquely identifies all cilium-managed endpoint IPs with the key-value store. All endpoints will watch on this specified prefix in the key-value store, and cache it locally for fast lookup. This will allow us to be able to determine which IPs correspond to sets of labels that are allowed for label-based egress policy.

**Comment by ianvernon** [comment]
Currently am working on determining the exact path and key/value for use in the key-value store, as well as during which parts of the endpoint lifecycle necessitate us updating the key-value store.

**Comment by ianvernon** [comment]
Per discussion, key-value store will contain the following mapping: 

Mapping of address space/ endpointIP (cluster1/10.1.1.1) → cluster/node/endpoint_id + labels (cluster1/node1/200 + labels).

What determines an updating of this information in the key-value store?
* Endpoint gets added
* Endpoint gets deleted
* Policy changes for endpoint
    * Addition / deletion of egress policy rules that apply to an endpoint
    * Addition / deletion of labels that apply to an endpoint

**Comment by ianvernon** [comment]
Open-ended question: how does this affect our L3-dependent L7?

**Comment by tgraf** [comment]
It will have severe scale limitations which is why we have not implemented it so far. The naive approach is to reconfigure the enforced policy on every update to the ip->label mapping.

**Comment by ianvernon** [comment]
TODO: define an interface (IPtoIDMapping) that has three functions:

* Update
* Delete
* Add
