### ISSUE TITLE
CFP: support full port mapping for a service

### ISSUE THREAD

**Issue by Jiang1155** [cilium/cilium#25572]
## Cilium Feature Proposal

**Is your feature request related to a problem?**
Yes

If so, please describe the problem

Basically, in some cases,  a pod may open lots of ports, and it is tedious ( and not scale ) to add a line for each port in k8s as a service. k8s has a endport support in newer releases. ([#16622 Port ranges in network policies](https://github.com/cilium/cilium/issues/16622)) But cilium does not support it yet. There was an effort but never got merged (https://github.com/cilium/cilium/issues/16622  and https://github.com/cilium/cilium/pull/17315 ). In addition, the previous plan is to just change the control plane to automatically add lots of ebpf maps for the port range, which may introduce ebpf map memory usage overhead depending on how many ports a user want to use.

**Describe the feature you'd like**
Add a full port mapping support for a service. For this kind of service, the data path ignores L4 checking and does not translate L4. As a result, the service can handle external traffic on all the ports. No need to modify k8s. 

1) Add a new service type ( FullPortMapping etc ) according to the control plane info ( such as CRD ). Pass it down to ebpf data plane. ( the control plane can be similar to LRP with CRDs )
2) The new type does not really use ports but uses a reserved port, such as 0, as a place holder ( to keep bpf map happy )
3) In lb4_lookup_service(), first do a normal lookup. If failed, then replace the dest port with the reserved port and search for FullPortMapping service. ( Assume normal service and FullPortMapping service do not share IPs )
4) In the lb4_local(), skip L4 translate if it is FullPortMapping service.
Other code path basically are the same.  

Include any specific requirements you need

Need to be able to backport to old 1.11 release

**(Optional) Describe your proposed solution**

see above.

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

======== following is the original post on slack =============================
link: https://cilium.slack.com/archives/C2B917YHE/p1684346187221869

Hi there, I am thinking add a new feature to cilium, but want to get some feedback about the feature and the design first.
The feature can be called as full port mapping support. One example request is from here: https://github.com/kubernetes/kubernetes/issues/23864  Basically, in some cases,  a pod may open lots of ports, and it is tedious ( and not scale ) to add a line for each port in k8s as a service.  To implement that, I plan to do something similar as local redirect policy. The following are detailed steps .
1) Add a new service type ( FullPortMapping etc ) according to the control plane info ( such as CRD ). Pass it down to ebpf data plane.
2) The new type does not really use ports but uses a reserved port, such as 0, as a place holder ( to keep bpf map happy )
3) In lb4_lookup_service(), first do a normal lookup. If failed, then replace the dest port with the reserved port and search for FullPortMapping service. ( Assume normal service and FullPortMapping service do not share IPs )
4) In the lb4_local(), skip L4 translate if it is FullPortMapping service.
Other code path basically are the same.  What do you guys think? Thanks.

**Comment by squeed** [comment]
https://github.com/cilium/cilium/pull/23016 should fix this - we have been working on endPort for some time :-)
