### ISSUE TITLE
Tag bpf entrypoints with new `__section_entry` macro

### ISSUE THREAD

**Issue by ti-mo** [cilium/cilium#25616]
Andrii submitted a patch a while ago to make the Cilium datapath fully conform to libbpf conventions: https://github.com/anakryiko/cilium/commit/e66bc11552ceee4045eac94741f99b9fbcf7989e.

This makes the datapath compile and pass veristat, but it cannot be merged as-is, since it converts tail call maps to BTF map defs that don't have the `id` field needed to hook up tail calls into their respective tail call maps. See https://github.com/cilium/cilium/issues/25005 for more info and ongoing work.

The other part of Andrii's proposed change makes it so entrypoints have section names that conform to libbpf conventions. `from-container`, `to-host` , etc. all need to become either `tc` or `xdp` depending on whether the datapath was built with `skb.h` or `xdp.h`.

I propose to add a new `__section_entry` macro (to go with the existing `__section_tail` and friends) that is declared as  `__section("tc")` by `skb.h` and `__section("xdp")` by `xdp.h`. This also acts as a clear definition of entrypoints vs. tail calls.

**Comment by Jack-R-lantern** [comment]
Can you assign this issue to me?

**Comment by ti-mo** [comment]
Sure!
