### ISSUE TITLE
Cilium is confused about source address if io.cilium.proxy-visibility observes http traffic

### ISSUE THREAD

**Issue by farcaller** [cilium/cilium#25630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Here's the setup:

I have two clusters A and B with cilium on both running in cluster mesh (native routing with kube-router doing the BGP only).

A pod `ingress` in cluster A receives http traffic and forwards it to a pod `workload` in cluster B. Workload is annotated with `io.cilium.proxy-visibility: '<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>,<Ingress/80/TCP/HTTP>'`.

(coincidentally, ingress is an envoy instance that's configured by istio. Istio service mesh isn't used and istio is pretty much a thin k8s CRD wrapper on top of envoy).

When the abovementioned annotation is present and I curl to `ingress`, the hubble reports that the traffic to `workload` on B originated from 'world' and shows the IP address of the machine with curl. That's seems to be wrong, because from the cluster perspective the traffic originated from the cluster A pod `ingress`. I suspect that cilium's envoy on B that gets enabled due to proxy-visibility trusts the `ingress`'es x-forwarded-for for whatever reason.

This makes it impossible to set up the reasonable CiliumNetowrkPolicies, because I want `workload` to receive traffic from `ingress` only, but the flows are reported from the out-of-cluster machines.

### Cilium Version

1.13.2

### Kernel Version

Linux web 6.1.27 #1-NixOS SMP PREEMPT_DYNAMIC Sun Apr 30 23:26:28 UTC 2023 x86_64 GNU/Linux

### Kubernetes Version

v1.26.4+k3s1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farcaller** [comment]
I did try, but the policy behaves really weird for me and doesn't apply at all (on the CEP side you don't see any endpoints allows on the ingress so it just blocks all the ingress). Trying to make an isolated use case but AWS doesn't do L2 so I'm working on a different setup.

Here's a couple new things I learned:
- the traffic from envoy in A flows to the _service IP_ in B. I have `bpf.lbExternalClusterIP = true`. With that, it's outside of the `ipv4NativeRoutingCIDR` so cilium supposedly does NAT.

**Comment by squeed** [comment]
Are you able to reproduce in a single cluster? That would be, obviously, much easier to dive in to.

**Comment by jrajahalme** [comment]
@farcaller Thanks for the report, indeed the hubble flow record from cluster B in your case picks up the source IP address from the `x-forwarded-for` header inserted by `ingress` in cluster A. This has no bearing on policy enforcement, however, as Cilium always resolves the source metadata for policy enforcement before HTTP headers are parsed.

So something else is going on w.r.t. policy enforcement not working in your case.

PR #25674 contains a fix for the incorrect Hubble flow record issue.

**Comment by squeed** [comment]
@farcaller can you open a separate issue for multicluster policy, ideally with as minimal a reproducer as possible? Thanks!
