### ISSUE TITLE
Service ID type mistmatch

### ISSUE THREAD

**Issue by vanyasvl** [cilium/cilium#25644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the API and Client package Service ID field has a type `int64`
but in pkg/service/id.go it has a type `uint32` (for example func GetID)
but then in pkg/loadbalancer/loadbalancer.go Serive ID has a type `uitn16`

How does issue look from the Client side:
Issue 1:
Trying to create new service with ID -11 (valid int64 regarding to API) via `PutServiceID`, all ok, PutServiceID returns `true`
Then trying to list services via `GetServces` and GetServices returns Service with ID `4294967294` (-2 casted to uint32)
Issue 2:
Creating a service with ID 100000 (lager than uint16). All ok, we see this ID in GerServicces output. Then trying to delete it via DeleteServiceID and got an error "Service Not Found". 

For Service with ID from 1 to 65535 (uint16) all works ok.

So you have to fix Service ID types in API, service and loadbalancer packages to match each other

### Cilium Version

1.13.2

### Kernel Version

5.15.0-71-generic

### Kubernetes Version

Cilium standalone L4 LB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Oops, that's confusing.

We might not be able to change the api types, but we should at least provide some meaningful comments and validation on the server side.
