### ISSUE TITLE
Shift `proxy_port` datapath handling from embedded `BPF_L4_MAP` into native `POLICY_MAP`

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2564]
Since commit 1481216929451b435501c6815515d602b24cd0b2, L3-dependent L4 policies (ie, policies requiring both a label and a port/protocol) are implemented in the bpf policymap. However, L4-only policies are still implemented as BPF code as per the below.

https://github.com/cilium/cilium/blob/6b7aa7671970073c3b160a21dbc3af860c95635b/pkg/endpoint/bpf.go#L95-L114

For consistency, should we attempt to unify these by shifting l4-only policies into the same map?

Subquestion: Do L3+L4 policies generate CFG_L4_INGRESS entries in the BPF here as well as the policymap entries, or just policymap entries?

**Comment by joestringer** [comment]
Since #2918 was merged, if L4-only policies are encoded in the map as {identity:0, dport: xxx} then the policy will be respected there. As at this point, proxy_port is still determined using this `BPF_L4_MAP` though.

Answering the subquestion:
Currently, Label-dependent L4 policies are mapped down to the `POLICY_MAP`, including if the label dependence is wildcarding all endpoints. ~~L4-only policies are not pushed down to this map~~ (#2992). For any label-dependent L4 policies with L7 filters, or L4-only policies with L7 filters, their proxy redirection is all implemented with the embedded `BPF_L4_MAP` (ie, the thing triggered by `CFG_L4_INGRESS`).

**Comment by ianvernon** [comment]
FYI @rlenglet this might overlap with the work you are doing right now.

**Comment by rlenglet** [comment]
Maybe. I think I'm nearly done with fixing https://github.com/cilium/cilium/issues/4711
That requires significant changes to `regenerateBPF`.

**Comment by ianvernon** [comment]
@rlenglet can this be closed given that #4711 was merged?

**Comment by rlenglet** [comment]
I would prefer to let @joestringer decide.

**Comment by joestringer** [comment]
Yep, looks like the `writeL4Policy` code was removed, and this was just open to track populating the policymap entries with redirect ports.

Closing, thanks!
