### ISSUE TITLE
Improve Hubble decoding performance

### ISSUE THREAD

**Issue by kaworu** [cilium/cilium#25657]
https://github.com/cilium/cilium/pull/24162 introduced specialized functions to decode `TraceNotify` events, replacing the generic but "slow" `binary.Read`. There are other event types that could benefit from the same optimization:
- [x] `DropNotify` https://github.com/cilium/cilium/blob/82a6396d59f5b52cbbb8a3787803cd2317ffdaf0/pkg/hubble/parser/threefour/parser.go#L112
- [x] `PolicyVerdictNotify` https://github.com/cilium/cilium/blob/82a6396d59f5b52cbbb8a3787803cd2317ffdaf0/pkg/hubble/parser/threefour/parser.go#L134
- [x] `DebugCapture` https://github.com/cilium/cilium/blob/82a6396d59f5b52cbbb8a3787803cd2317ffdaf0/pkg/hubble/parser/threefour/parser.go#L141
- [x] `DebugMsg` https://github.com/cilium/cilium/blob/82a6396d59f5b52cbbb8a3787803cd2317ffdaf0/pkg/hubble/parser/debug/parser.go#L50
- [x] `TraceSockNotify` https://github.com/cilium/cilium/blob/82a6396d59f5b52cbbb8a3787803cd2317ffdaf0/pkg/hubble/parser/sock/parser.go#L77

**Comment by Amshu-k** [comment]
@kaworu - I would like to work on this.

**Comment by Amshu-k** [comment]
@kaworu - I would like to work on this issue. Can you please assign this to me?
