### ISSUE TITLE
CFP: Have BGP CP use Port 179 by Default

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#25661]
## Cilium Feature Proposal
        
According to the [docs](https://docs.cilium.io/en/latest/network/bgp-control-plane/#local-listening-port), a user is required to configure the BGP listening port:
> By default the GoBGP BGPRouterManager will instantiate each virtual router without a listening port.

[TCP port 179](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) is the well-known port assigned to BGP by IANA. To simplify the configuration, the BGP CP should listen on this port by default.

**Is your feature request related to a problem?**

Unnecessary configuration is required when configuring BGP CP. Most configurations will use the default BGP port.

**Describe the feature you'd like**

Not require setting the `local-port` annotation when using the default BGP port of 179.

**(Optional) Describe your proposed solution**

Update `parseAnnotation()` to set the local port attribute to `179` by default. If the `local-port` annotation is set, the value will override the default.

**Comment by danehans** [comment]
Currently `-1` is used to signal the router to not listen for BGP requests. This does make sense in situations where you want to force the router to initiate the peering session. The question is, is this a more common use case than allowing two-way communication by default so a user does not need to specify the listening port annotation?

**Comment by YutaroHayakawa** [comment]
We're already aware of the use case that the BGP CPlane peers with the BGP speaker (e.g. FRR, Bird) that is already installed on the node. Changing the default may break the case that the BGP speaker is listening on the `179`. So, we should at least make this opt-in.

**Comment by danehans** [comment]
@rastislavs @harsimran-pabla thoughts on this issue?

**Comment by danehans** [comment]
> We're already aware of the use case that the BGP CPlane peers with the BGP speaker (e.g. FRR, Bird) that is already installed on the node.

@YutaroHayakawa now ^ comment is making sense to me due to https://github.com/cilium/cilium/issues/26146. Bird can be used for intra-cluster reachability and BGP CP for external reachability.

**Comment by danehans** [comment]
> Introduce localPort in the CiliumBGPVirtualRouter resource.

@harsimran-pabla I'm a +1 for using APIs over annotations to express intent.

> The default when not set value will be -1.

+1 on keeping the default (passive mode) for backward compatibility.

> If localPort in CiliumBGPVirtualRouter is set and local-port annotation on the node is set.
a. The virtual router will start with the local port defined in the annotation.
b. Annotation will take precedence since this is per node configuration vs CRD which can apply to multiple nodes.

This makes sense but may take a user by surprise. Has the community considered supporting the status subresource to surface this kind of information?

**Comment by harsimran-pabla** [comment]
It would make sense to expose BGP CP state information via status subresource. Feel free to open a [feature request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#cilium-feature-proposals) for it and if you have implementation ideas.

We will need a clear understanding of what information goes into the status subresource vs cilium CLI. Overall, I think it makes sense.

**Comment by danehans** [comment]
@harsimran-pabla thanks for the feedback. I created https://github.com/cilium/cilium/issues/26280 to track adding the status Subresource.

**Comment by danehans** [comment]
BGP CP cannot use port 179 by default without breaking backwards compatibility.
