### ISSUE TITLE
Make logrus configurable per package

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2567]
This way, we can simplify the log output for cilium-health daemon, whose stdout is redirected into cilium and printed to the same cilium log. (Currently it double-prints the RFC3339 timestamps).

**Comment by raybejjani** [comment]
While we already have per package loggers, we don't report which subsystem the logger is in (In most cases, some packages already do). If we finish that up, we would then be able to filter with grep. Would that work? or is the goal to select which subsystems emit debug to begin with?

**Comment by joestringer** [comment]
The primary issue that I've observed relating to this is that cilium-health logs end up with two timestamps at the start of the line because cilium-health logs to stdout, then that stdout is read in by a cilium goroutine and printed to the cilium log, and I'd like to be able to simplify that. Having subsystem support would also be excellent, because it would make it easier to tell which logs come from where.

**Comment by joestringer** [comment]
Fixed by #2566.
