### ISSUE TITLE
[DOC] fixing the word "span"

### ISSUE THREAD

**Issue by wasup-yash** [cilium/cilium#25688]
The issue is regarding readme, there is a word called `"span"` Isn't it supposed to be `"scan"`? if this issue needs to be corrected, please assign me this issue as I am new to the community and trying to get involved.

![cili](https://github.com/cilium/cilium/assets/112958086/d974143c-1f54-4e5c-8b55-bd0991a49b18)
 ?

**Comment by rolinh** [comment]
English is not my primary language but I think the word "span" is correct here. In this context, it means "cover" or "extend to".

**Comment by wasup-yash** [comment]
> English is not my primary language but I think the word "span" is correct here. In this context, it means "cover" or "extend to".

thank you for considering this, if that's not the problem as such so should I close the issue?
