### ISSUE TITLE
Connection tracking is cleared when policy is deleted when endpoint ends up in default allow

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2569]
When an endpoint is subject to policy and all policy of that endpoint is then cleared, the current behaviour removes all connections from the connection tracking tables. This is incorrect if the policy enforcement is set to default which will result the endpoint in turning into a "policy disabled" state and effectively all existing connections should have prevailed.

**Comment by manalibhutiyani** [comment]
This issue was seen in a persistent TCP connection case in a Kafka setup. GH #2471
