### ISSUE TITLE
SIG-Request: UBPF

### ISSUE THREAD

**Issue by hawkinsw** [cilium/cilium#25720]
Hello everyone and thank you for all that you doing for the ebpf technology and the community -- it's an contribution!

I was speaking with @Alan-Jowett about (and he was kind enough to allow me to help him with) ubpf and we were hoping that we could establish a `#ubpf` channel in the Cilium & eBPF Slack community. 

I spoke with @lizrice about such a request and she alerted me to the procedure at https://docs.cilium.io/en/v1.13/community/community/#how-to-create-a-sig 

I hope that I am following the proper procedures. 

Again, thank you for all the work that you are doing supporting the community!

Sincerely,
Will

**Comment by lizrice** [comment]
Great! I'd be happy to see a Slack channel for ubpf. This just needs an LGTM from one other committer (I am one) and we'll go ahead and create it

**Comment by hawkinsw** [comment]
Thank you, again!

**Comment by pchaigno** [comment]
Looks good to me as well!

**Comment by hawkinsw** [comment]
Thank you both!

**Comment by lizrice** [comment]
Channel is created, enjoy!
