### ISSUE TITLE
CFP: Add network policy names in hubble

### ISSUE THREAD

**Issue by Tim-herbie** [cilium/cilium#25752]
## Cilium Feature Proposal
        

**Is your feature request related to a problem?**

No, but it would simplify troubleshooting network connections within Kubernetes.

**Describe the feature you'd like**

When I started using Cilium, I have noticed that the name of the CiliumNetworkPolicy as well as the name of the CiliumClusterwideNetworkPolicy will not be shown in the cilium hubble ui as well as in hubble observe. For me, the observability would be increased when I could comprehend why the traffic was accepted or denied.

**(Optional) Describe your proposed solution**

Add the network policy name to the hubble ui and hubble observe as value.

**Comment by ti-mo** [comment]
@Tim-herbie Thanks for the suggestion! Might be more effective to create an issue in https://github.com/cilium/hubble/issues instead? I'll close this one for now.

**Comment by Tim-herbie** [comment]
https://github.com/cilium/hubble/issues/1100
