### ISSUE TITLE
CFP: hubble ui: add traffic direction as column

### ISSUE THREAD

**Issue by Tim-herbie** [cilium/cilium#25782]
## Cilium Feature Proposal
    
**Is your feature request related to a problem?**

No, but it simplify network troubleshooting within the Kubernetes Cluster

**Describe the feature you'd like**

Currently it is not possible to choose "traffic direction" as column in the hubble ui. When I click on one line, I can see the traffic direction, but troubleshooting would be faster when I could see this information without selecting a line.

**Comment by julianwiedmann** [comment]
:wave: would https://github.com/cilium/hubble-ui/issues be better suited for this?
