### ISSUE TITLE
strange behaviour for hostPort

### ISSUE THREAD

**Issue by louisportay** [cilium/cilium#25791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Linked to https://github.com/cilium/cilium/issues/24741

Steps to reproduce:

cilium-config ConfigMap
  kube-proxy-replacement: disabled
  enable-host-port: "true"

ingress-nginx/controller:v1.8.0 with this config
[...]
ports:
          - containerPort: 80
            hostPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            hostPort: 443
            name: https
            protocol: TCP
with its associated service (type ClusterIP)

I try to request the public IP from a node and the server replies with `connection refused`.

I modify the ConfigMap like this

cilium-config ConfigMap
  kube-proxy-replacement: disabled
  enable-host-port: "false"
  cni-chaining-mode: "portmap"
  
 I restart cilium on every node and the ingress controller,
 after this I'm able to reach the ingress controller from a node public IP.
 
Interesting thing, if I change again cilium config (and restart the components), my requests `time out` instead of my connection being refused.

I'm unable to tell what's the expected behaviour here.

### Cilium Version

1.13.3

### Kernel Version

5.15.0-69-generic

### Kubernetes Version

v1.26.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
@louisportay Have you managed to make some progress here? You've still provided relatively little information in this issue. I don't think we do much testing with KPR disabled, if any. Are you also running a similar setup to the issue you linked? If so, maybe chime in there?
