### ISSUE TITLE
CI: ClusterMesh (ci-multicluster)

### ISSUE THREAD

**Issue by pippolo84** [cilium/cilium#25816]
## CI failure

https://github.com/cilium/cilium/actions/runs/5141598573/jobs/9254287333

Step: Setup & Test (7, vxlan, ipv4, wireguard, iptables)

Output of test failure:

```
📋 Test Report
connectivity test failed: 2 tests failed
❌ 2/43 tests failed (2/277 actions), 13 tests skipped, 1 scenarios skipped:
Test [all-ingress-deny]:
  ❌ all-ingress-deny/pod-to-cidr/external-1111-0: cilium-test/client2-76f4d7c5bc-zp4w4 (10.242.1.75) -> external-1111 (1.1.1.1:443)
Test [to-cidr-external-knp]:
  ❌ to-cidr-external-knp/pod-to-cidr/external-1111-1: cilium-test/client2-76f4d7c5bc-zp4w4 (10.242.1.75) -> external-1111 (1.1.1.1:443)
Error: Process completed with exit code 1.
```

Sysdump: [cilium-sysdumps-7.zip](https://github.com/cilium/cilium/files/11623519/cilium-sysdumps-7.zip)

**Comment by learnitall** [comment]
Hey @giorio94, can you take a look?

**Comment by rastislavs** [comment]
Hit in similar ones in https://github.com/cilium/cilium/pull/26040:

Installation and Connectivity Test (7, vxlan, ipv4, wireguard, iptables):
```
❌ 1/43 tests failed (1/277 actions), 13 tests skipped, 1 scenarios skipped:
Test [all-ingress-deny-knp]:
  ❌ all-ingress-deny-knp/pod-to-cidr/external-1111-0: cilium-test/client-6965d549d5-ksdvq (10.242.1.177) -> external-1111 (1.1.1.1:443)
```

Installation and Connectivity Test (6, vxlan, ipv4, disabled, none):
```
❌ 1/43 tests failed (1/288 actions), 13 tests skipped, 0 scenarios skipped:
Test [all-ingress-deny]:
  ❌ all-ingress-deny/pod-to-cidr/external-1111-0: cilium-test/client-6965d549d5-bmcb4 (10.242.1.164) -> external-1111 (1.1.1.1:443)
```

Sysdumps:
- [cilium-sysdumps-7.zip](https://github.com/cilium/cilium/files/11745648/cilium-sysdumps-7.zip)
- [cilium-sysdumps-6.zip](https://github.com/cilium/cilium/files/11745651/cilium-sysdumps-6.zip)

**Comment by YutaroHayakawa** [comment]
Similar issue in `(2, disabled, ipv4, wireguard, none, false, migration, migration)`

```
❌ 1/44 tests failed (1/289 actions), 12 tests skipped, 0 scenarios skipped:
connectivity test failed: 1 tests failed
Test [all-ingress-deny]:
  ❌ all-ingress-deny/pod-to-cidr/external-1111-0: cilium-test/client-6965d549d5-74lkz (10.242.1.138) -> external-1111 (1.1.1.1:443)
```

https://github.com/cilium/cilium/actions/runs/5441859523/jobs/9896330941
