### ISSUE TITLE
packages drop by FIB lookup failed

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#25822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

packages drop by FIB lookup failed

this data is generate by `cilium monitor -j > cil_j.log`

{"cpu":"CPU 14:","type":"drop","mark":"0x2f75d213","reason":"FIB lookup failed","source":2771,"bytes":66,"srcLabel":0,"dstLabel":0,"dstID":0,"summary":{"ethernet":"Ethern
et\t{Contents=[..14..] Payload=[..54..] SrcMAC=b4:0c:25:e2:80:16 DstMAC=00:62:0b:91:af:10 EthernetType=IPv4 Length=0}","ipv4":"IPv4\t{Contents=[..20..] Payload=[..32..] V
ersion=4 IHL=5 TOS=0 Length=52 Id=4700 Flags=DF FragOffset=0 TTL=122 Protocol=TCP Checksum=63297 SrcIP=0.0.0.0 DstIP=245.0.2.38 Options=[] Padding=[]}","tcp":"TCP\t{Conte
nts=[..32..] Payload=[] SrcPort=56284 DstPort=3306(mysql) Seq=2889614829 Ack=0 DataOffset=8 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false
 NS=false Window=8192 Checksum=48644 Urgent=0 Options=[..6..] Padding=[]}","l2":{"src":"b4:0c:25:e2:80:16","dst":"00:62:0b:91:af:10"},"l3":{"src":"0.0.0.0","dst":"245.0.2
.38"},"l4":{"src":"56284","dst":"3306"}}}

```json
{"cpu":"CPU 31:","type":"debug","message":"Encapsulating to node 3232300837 (0xc0a8ff25) from seclabel 59087"}
{"cpu":"CPU 35:","type":"debug","message":"Successfully mapped addr=192.168.255.37 to identity=7"}
{"cpu":"CPU 41:","type":"debug","message":"Successfully mapped addr=192.168.255.37 to identity=7"}
{"cpu":"CPU 14:","type":"debug","message":"Successfully mapped addr=10.82.16.184 to identity=2"}
{"cpu":"CPU 14:","type":"debug","message":"Conntrack lookup 1/2: src=10.82.16.184:56284 dst=10.82.41.249:3306"}
{"cpu":"CPU 14:","type":"debug","message":"Conntrack lookup 2/2: nexthdr=6 flags=4"}
{"cpu":"CPU 14:","type":"debug","message":"CT verdict: New, revnat=0"}
{"cpu":"CPU 14:","type":"debug","message":"Conntrack create: proxy-port=0 revnat=124 src-identity=0 lb=0.0.0.0"}
{"cpu":"CPU 14:","type":"debug","message":"Conntrack lookup 1/2: src=10.82.16.184:56284 dst=245.0.2.38:3306"}
{"cpu":"CPU 14:","type":"debug","message":"Conntrack lookup 2/2: nexthdr=6 flags=1"}
{"cpu":"CPU 14:","type":"debug","message":"CT verdict: New, revnat=0"}
{"cpu":"CPU 14:","type":"debug","message":"Conntrack create: proxy-port=0 revnat=124 src-identity=2 lb=245.0.2.38"}
{"cpu":"CPU 14:","type":"drop","mark":"0x2f75d213","reason":"FIB lookup failed","source":2771,"bytes":66,"srcLabel":0,"dstLabel":0,"dstID":0,"summary":{"ethernet":"Ethern
et\t{Contents=[..14..] Payload=[..54..] SrcMAC=b4:0c:25:e2:80:16 DstMAC=00:62:0b:91:af:10 EthernetType=IPv4 Length=0}","ipv4":"IPv4\t{Contents=[..20..] Payload=[..32..] V
ersion=4 IHL=5 TOS=0 Length=52 Id=4700 Flags=DF FragOffset=0 TTL=122 Protocol=TCP Checksum=63297 SrcIP=0.0.0.0 DstIP=245.0.2.38 Options=[] Padding=[]}","tcp":"TCP\t{Conte
nts=[..32..] Payload=[] SrcPort=56284 DstPort=3306(mysql) Seq=2889614829 Ack=0 DataOffset=8 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false
 NS=false Window=8192 Checksum=48644 Urgent=0 Options=[..6..] Padding=[]}","l2":{"src":"b4:0c:25:e2:80:16","dst":"00:62:0b:91:af:10"},"l3":{"src":"0.0.0.0","dst":"245.0.2
.38"},"l4":{"src":"56284","dst":"3306"}}}
{"cpu":"CPU 04:","type":"debug","message":"Successfully mapped addr=10.82.51.229 to identity=2"}
{"cpu":"CPU 22:","type":"debug","message":"Successfully mapped addr=10.82.51.229 to identity=2"}
{"cpu":"CPU 52:","type":"debug","message":"Conntrack lookup 1/2: src=245.0.0.12:50186 dst=192.168.255.35:6443"}
{"cpu":"CPU 52:","type":"debug","message":"Conntrack lookup 2/2: nexthdr=6 flags=1"}
{"cpu":"CPU 52:","type":"debug","message":"CT entry found lifetime=3566377, revnat=0"}
{"cpu":"CPU 52:","type":"debug","message":"CT verdict: Established, revnat=0"}
{"cpu":"CPU 52:","type":"debug","message":"Successfully mapped addr=192.168.255.35 to identity=1"}
{"cpu":"CPU 52:","type":"capture","mark":"0xddc507eb","message":"Delivery to ifindex 0","prefix":"-\u003e 0","source":1149,"bytes":66,"summary":"245.0.0.12:50186 -\u003e
192.168.255.35:6443 tcp ACK"}
```

![image](https://github.com/cilium/cilium/assets/6076617/723aafa1-4035-4b5d-8df0-2b08130d6cfb)

### Cilium Version

1.12.7

### Kernel Version

Linux wcn-gdppd-qfusion1 6.2.11-1.el8.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 13 08:18:02 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

too big to upload

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
:wave: are you looking for help in diagnosing why the drop occurred? If so, describing your test scenario, the cilium config and/or providing a sysdump (you could upload somewhere else and link here) would be a great start.

**Comment by llhhbc** [comment]
Yes, at present, when we frequently delete pods with the same name, there will be a probability of such a drop. I don’t know why

Here is the cilium sysdump file
url: https://pan.baidu.com/s/1mO3mGKgl83_dTqT5nsoR4Q    Extraction code: abcd

**Comment by lmb** [comment]
From #28218:

> This bug appeared once before, but since it never recurred, sysdump was not performed, causing the problem to be shelved. It happened again recently and a sysdump was executed. Since it was time to recover at that time, after completing the sysdump, restart the pod to resume business first. The specific pod is: pod-name: qfusion-admin/mysql-6ccf1fd801-0. This problem occurs occasionally, but it occurs from time to time.

> cilium sysdump file:
https://drive.google.com/file/d/17aVXdvSpKmMTMQHnEdoBQruHciXU9HeO/view?usp=drive_link
