### ISSUE TITLE
CFP: Add more ebpf ICMP support or suppress tx errors caused by "unsupported protocol"

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#25848]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

For version 1.11.4  (maybe for the latest 1.11.17 as well), when enable ebpf-msquerade, ebpf program will drop all ICMP packets except `Echo request` and `Echo reply`. When ebpf drop the ICMP packets, the counter of eth0 tx errors will increase, and ethtool give no reasons for this. However, we can reproduce the situation by manually send ICMP timestamp or other type using `hping3`.

The coredns in kubernetes occassionally send `Destination unreachable` in our usage.

**Describe the feature you'd like**

1. When ebpf drop the unsupport ICMP, don't make the tx error increase since we want to monitor the state for exceptions. 
2. Or, support commonly used ICMP protocol, v1.13 seems to support `Destination unreachable` now.

**Comment by julianwiedmann** [comment]
:wave: hi! This sounds like a duplicate of https://github.com/cilium/cilium/issues/23955, right?

**Comment by nijich** [comment]
> 👋 hi! This sounds like a duplicate of #23955, right?

Hi, I think they are slightly different. For me, avoiding the side effect of tx errors is more useful, since there are many ICMP types, although currently we only suffer the unreachable one. Besides, I am also curious about why ebpf droping packets causing tx errors increasing. Thank you for your reply.

**Comment by julianwiedmann** [comment]
> > wave hi! This sounds like a duplicate of #23955, right?
> 
> Hi, I think they are slightly different. For me, avoiding the side effect of tx errors is more useful, since there are many ICMP types, although currently we only suffer the unreachable one.

Imho the end goal is to let all unsupported packets pass through the SNAT engine, without dropping them. Unless there's a strong reason why a **specific** type of (ICMP) packet must be prevented from leaking out.

> Besides, I am also curious about why ebpf droping packets causing tx errors increasing. Thank you for your reply.

In general, it would be helpful to show the actual `ethtool` statistics output (and the specific counter) you are referring to. This makes it much easier for others to match up their symptoms.

I would dare to say that incrementing error counters on a DROP from a BPF program is a good thing. Makes it much easier to trace down where your packets get lost :).

**Comment by nijich** [comment]
> Imho the end goal is to let all unsupported packets pass through the SNAT engine, without dropping them. Unless there's a strong reason why a **specific** type of (ICMP) packet must be prevented from leaking out.

Yes. But supporting all/many kinds of packets takes much longer times to achieve. 

> In general, it would be helpful to show the actual `ethtool` statistics output (and the specific counter) you are referring to. This allows others to match up their symptoms.

In our environment, the containers are run on hyper-v based vm. `ethtool -S eth0` gives no specific tx_xxx_errors result. We are not expert in linux kernel. I have tried to understand the kernel code but failed. The thing I don't understand, is ebpf programme runs at tc, and I think tx error statistic the device driver layer, which shouldn't be affected.

> I would dare to say that incrementing error counters on a DROP from a BPF program is a good thing. Makes it much easier to trace down where your packets get lost :).

I agree. This issue can be closed if you want. We will update our cilium when more protocols are supported. Thank you.
