### ISSUE TITLE
BGP CP: Document PeerPort

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#25869]
https://github.com/cilium/cilium/pull/25809 adds support for `PeerPort`, allowing a user to define the port used for creating a BGP peer. Update the BGP CP user docs to explain the details of using this field.

**Comment by hainamtvvt** [comment]
How to config PeerPort, can you share config example!!

**Comment by danehans** [comment]
The `peerPort` field is documented [here](https://docs.cilium.io/en/stable/network/bgp-control-plane/#fields). Did you set this field to the TCP port of the configured neighbor? __Note:__ If the neighbor is a Cilium BGP Control plane, the default local port of the neighbor is `0` which is passive mode. You can set the listening port through the `local-port` [annotation](https://docs.cilium.io/en/stable/network/bgp-control-plane/#local-listening-port). If you feel additional documentation is required, can you please create a new issue since the field is documented and this issue is closed?
