### ISSUE TITLE
TCP retransmissions & general networking issues on 1.14.0-snapshot.3

### ISSUE THREAD

**Issue by buroa** [cilium/cilium#25868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

TCP retransmissions on Cilium `1.14.0-snapshot.3` (not present on `1.14.0-snapshot.2`).

### Cilium Version

1.14.0-snapshot.3

### Kernel Version

6.1.30-talos

### Kubernetes Version

v1.27.2

### Sysdump

*The file size was too big to upload here.*

https://pub-877347772b464d078a73206e03fd113d.r2.dev/cilium-sysdump-20230602-092620.zip

### Anything else?

https://github.com/buroa/k8s-gitops/blob/master/kubernetes/apps/kube-system/cilium/app/helmrelease.yaml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by buroa** [comment]
@Bevisy https://pub-877347772b464d078a73206e03fd113d.r2.dev/cilium-darwin-arm64.tar.gz

**Comment by margamanterola** [comment]
Hi @buroa! Thanks a lot for your report. Could you please include a few more details with regards to what you are seeing? When do the retransmissions happen? Between which endpoints? And any other details that might help us pin down the problem better.

**Comment by buroa** [comment]
We can close this. The latest snapshot seemed to fix the issue.

**Comment by lmq1999** [comment]
![image](https://github.com/cilium/cilium/assets/41988000/0fa0c865-338b-464d-b61a-cdf7f5a4fcf3)
the issue still appear in version v1.14.5
