### ISSUE TITLE
frequent dnsproxy timeouts

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#25877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Periodically, for 10s of minutes, the dnsproxy will not respond to queries and have timeouts. As a dnsproxy handles more queries the likelihood of timeouts increases. So high traffic nodes it happens nearly immediately, while lower traffic nodes takes bit longer before they start exhibiting the same symptoms.

### Cilium Version

Client: 1.13.3 36cb0eed 2023-05-17T12:31:14-04:00 go version go1.19.8 linux/amd64
Daemon: 1.13.3 36cb0eed 2023-05-17T12:31:14-04:00 go version go1.19.8 linux/amd64

### Kernel Version

Linux ip-10-0-37-189 5.15.0-1036-aws #40~20.04.1-Ubuntu SMP Mon Apr 24 00:21:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.13-eks-0a21954

### Relevant log output

```shell
level=warning msg="Lock acquisition time took longer than expected. Potentially too many parallel DNS requests being processed, consider adjusting --dnsproxy-lock-count and/or `" dnsName=bar.default.svc.cluster.local. duration=6.444839747s expected=1s subsys=daemon
level=warning msg="Lock acquisition time took longer than expected. Potentially too many parallel DNS requests being processed, consider adjusting --dnsproxy-lock-count and/or --dnsproxy-lock-timeout" dnsName=foo.bar.svc.cluster.local. duration=2.08938462s expected=1s subsys=daemon
level=error msg="Failed to dial connection to the upstream DNS server, cannot service DNS request" DNSRequestID=49079 dnsName=foo.bar.svc.cluster.local. endpointID=1176 error="failed to dial connection to 10.192.166.90:53: dial udp 10.192.166.90:53: i/o timeout" identity=75543 ipAddr="10.192.11.175:50687" subsys=fqdn/dnsproxy
```

### Anything else?

Tried setting `--dnsproxy-lock-count=1024` and `--dnsproxy-lock-timeout=3s` but that doesn't prevent the issue

Highest traffic cluster's upstream coredns pods report a total of ~120 qps

The highest traffic dnsproxy reports 20qps

There's a correlation between pods that talk to s3 frequently and nodes that exhibit timeouts

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
@christarazi (@joestringer) Have a chance to take a look?

> Tried setting --dnsproxy-lock-count=1024 and --dnsproxy-lock-timeout=3s but that doesn't prevent the issue

@dctrwatson do you have any other config settings in place for the proxy? They did not change between the 1.12 (good version) -> 1.13 upgrade right?

**Comment by dctrwatson** [comment]
> @dctrwatson do you have any other config settings in place for the proxy? They did not change between the 1.12 (good version) -> 1.13 upgrade right?

Only change was disabling the ingress controller and whatever Helm changed when upgrading the chart:
```
+  identity-heartbeat-timeout: "30m0s"
+  identity-gc-interval: "15m0s"
+  loadbalancer-l7: "envoy"
+  loadbalancer-l7-ports: ""
+  loadbalancer-l7-algorithm: "round_robin"
+  monitor-aggregation-interval: "5s"
+  enable-ipv6-big-tcp: "false"
+  enable-sctp: "false"

-  enable-ingress-controller: "true"
-  enforce-ingress-https: "true"
-  enable-ingress-secrets-sync: "true"
-  ingress-secrets-namespace: "cilium-secrets"
-  ingress-lb-annotation-prefixes: "service.beta.kubernetes.io service.kubernetes.io cloud.google.com"
-  monitor-aggregation-interval: 5s
-  subnet-ids-filter: ""
-  instance-tags-filter: ""
-  install-iptables-rules: "true"
```

I made the dnsproxy config changes afterwards when trying to remedy the issue.

**Comment by christarazi** [comment]
Question:

Does `bar.default.svc.cluster.local` have backends that are in-cluster pods? If so, then Cilium is not actually performing any policy enforcement on these IPs because `toFQDN` rules are syntactic sugar for `toCIDR` rules, which utilize node-local identities that are not supported for IPs within the cluster. In other words, you should prefer `toEndpoints` rules as that will select the label-based identity of the pods. `toFQDN` rules should only be used for destinations whose IPs are outside of the cluster.

**Comment by dctrwatson** [comment]
> Does `bar.default.svc.cluster.local` have backends that are in-cluster pods?

Yes, they are.

> If so, then Cilium is not actually performing any policy enforcement on these IPs because `toFQDN` rules are syntactic sugar for `toCIDR` rules, which utilize node-local identities that are not supported for IPs within the cluster. In other words, you should prefer `toEndpoints` rules as that will select the label-based identity of the pods. `toFQDN` rules should only be used for destinations whose IPs are outside of the cluster.

Correct, we don't. We have a CCNP that adds dnsproxy with an allow-all (`*`) rule. This makes it easy to determine traffic that's bound for `world` so we can then create only the `toFQDN` rules for them.

**Comment by christarazi** [comment]
:+1: 

Once you've removed `*.svc.cluster.local` and the DNS proxy is handling only the traffic that it should, then we'd be interested to see if that resolves the issue here or if you see it happening again for domains with IPs outside of the cluster.

**Comment by dctrwatson** [comment]
> Once you've removed `*.svc.cluster.local` and the DNS proxy is handling only the traffic that it should

Is there a way to write the CCNP to dnsproxy all requests _except_ `.cluster.local` ?

> if you see it happening again for domains with IPs outside of the cluster

The nodes most affected are the ones that make frequent requests to S3

**Comment by dctrwatson** [comment]
> Once you've removed `*.svc.cluster.local` and the DNS proxy is handling only the traffic that it should

Was just spot checking and some of the `.cluster.local` dnsNames being queried are coming from the same pods that have `toFQDN` rules for external services anyway...

**Comment by dctrwatson** [comment]
Another data point, this seems to be a regression in v1.13.3. Just noticed that 1 of the clusters affected by this had been on v1.13.2 for awhile and did not exhibit this behavior.

**Comment by christarazi** [comment]
In regards to potential regression, I've identified https://github.com/cilium/cilium/pull/25147 as a possible candidate. If you're up for it, you can revert the commits from that PR and deploy Cilium with that change to see if you still observe the timeouts.

**Comment by dctrwatson** [comment]
Alrighty, I think I tracked it down. Seems many large TCP queries are the culprit. UDP queries don't seem to be affected.

As in, `(A + AAA) * len(search-domains)` size queries

![Screenshot_2023-06-06_20 12 32](https://github.com/cilium/cilium/assets/395054/f2de743d-fbf9-404c-a8cc-3a3e6c6c3faa)

Since that drop in TCP request size, there's been no more timeouts.

TCP QPS went from ~850/s to ~100/s as well. UDP QPS is still ~1400/s 

![Screenshot_2023-06-06_20 18 03](https://github.com/cilium/cilium/assets/395054/301a2107-f645-40ca-9367-76ac2a923dad)

These metrics are from CoreDNS for the cluster.

I'll slowly roll this out to our other clusters and if we see it in one of those, I'll try the revert.

**Comment by dctrwatson** [comment]
Alright, the number of timeouts is greatly reduced, but not gone.

On a nodes where dnsproxy is reporting ~0.3 QPS, per `rate(cilium_proxy_upstream_reply_seconds_count{k8s_app="cilium",scope="totalTime"}[1m])`, are still periodically hitting timeouts.

These are UDP FQDN queries and no search domains either.

The CoreDNS in this cluster is only seeing a cumulative 100 QPS (much less than my test cluster couple days ago)

I can't use v1.13.2 on these clusters (due to apiserver CNP bug), so I'll try to figure out how to build v1.13.3 with the revert.

**Comment by dctrwatson** [comment]
> In regards to potential regression, I've identified #25147 as a possible candidate. If you're up for it, you can revert the commits from that PR and deploy Cilium with that change to see if you still observe the timeouts.

I just noticed this was also backported to v1.12.10, which does not exhibit this issue.

I think it has to do with k8s excessive search domains. It seems once we get services to issue queries for FQDNs, the issue goes away. But this is super annoying to fix because then you start running into "bugs" with SNI.

**Comment by dctrwatson** [comment]
@christarazi what are some next steps we can take debug this further?

The pods issuing the internal DNS queries that timeout are the same pods that use dnsproxy for FQDN rules, so we can't have them not use dnsproxy unfortunately.

It doesn't seem to be load related because these dnsproxy shouldn't be getting more than 1 QPS.

The only correlation is how search domains, so the larger the query the more likely it's to timeout.

**Comment by christarazi** [comment]
I think the quickest action is to disallow `*.svc.cluster.local` DNS requests from going to the proxy. The policy `matchPattern` field supports regex so you should be able to express "everything but ...".

**Comment by dctrwatson** [comment]
> I think the quickest action is to disallow `*.svc.cluster.local` DNS requests from going to the proxy. The policy `matchPattern` field supports regex so you should be able to express "everything but ...".

Ah. I assumed they would be denied if not included in the capture rule.

I have a short week this week, so I will try this out next week. Thank you!

**Comment by christarazi** [comment]
Yeah, there are two rules when using DNS policies:

1. DNS L7 rule
2. FQDN allow rules

See https://docs.cilium.io/en/stable/security/policy/language/#dns-proxy for more details. It's admittedly subtle. :slightly_smiling_face:

**Comment by dctrwatson** [comment]
Seems not having `*.*.svc.cluster.local` in the DNS L7 rules means the dnsproxy just rejects any queries for local services

Looks like in the code, once an endpoint has any DNS L7 rules attached, all queries are routed through the dnsproxy, which then applies the L7 rules with a default-deny.

**Comment by christarazi** [comment]
Could you try to keep those queries as part of the first policy and but for the second? Meaning keep `matchPattern: '*'` for (1) and the "everything except ..." for (2). I'd be interested to know if that reduces the load enough. 

If that doesn't do it, then I'm afraid that a continuous profile of Cilium whenever the timeouts are occurring would be the only way to debug it further.

**Comment by dctrwatson** [comment]
> Could you try to keep those queries as part of the first policy and but for the second? Meaning keep `matchPattern: '*'` for (1) and the "everything except ..." for (2). I'd be interested to know if that reduces the load enough.

Oh, that's how our policies are setup now. We allow `cluster`, but anything to `world` needs `toFQDN` rules.

> If that doesn't do it, then I'm afraid that a continuous profile of Cilium whenever the timeouts are occurring would be the only way to debug it further.

I'm going to try to figure how to trigger this in a test cluster. Right now it happens immediately in our largest prod clusters, and after minutes to hours (depending on cluster size) for the rest of our prod clusters.

Once I can repro this easily, is it `gops` that I use to get the continuous profile you're looking for?

**Comment by christarazi** [comment]
Your comment made me file https://github.com/cilium/cilium/pull/26675 :wink: 

Please let me know if those int ructions work well for you.

**Comment by dctrwatson** [comment]
Unfortunately, I cannot repro this issue artificially.

Since it seems to be a function of cluster size (number identities, endpoints, etc), can you think of any reason why dnsproxy would have issues? Since it's timeouts though, not sure how datapath would affect it.

I'm asking since I was wondering if there we any knobs you can think of I can tweak to mitigate the issue? I'm going to have to repro in a prod cluster to get the profile.

> Your comment made me file #26675 😉
> 
> Please let me know if those int ructions work well for you.

Thanks! Will hopefully have profile for you later today.

**Comment by dctrwatson** [comment]
@christarazi here's 60s pprof that I was taking when there was there was 22 timeouts. Longest timeout was `duration=27.816236277s`

All but 1 of the timeouts were for lookups on pods for the same statefulset service: `pod-N.sts-service.default.svc.cluster.local.`
1 timeout was for an EC2 API FQDN.

[cilium-pprof.zip](https://github.com/cilium/cilium/files/12009161/cilium-pprof.zip)

**Comment by ombre9** [comment]
We are facing the same error, using Cilium 1.13.4. Only solution worked for us to downgrade to 1.13.1

**Comment by christarazi** [comment]
@ombre9 Did you try each version in between v1.13.4 and v1.13.1?

**Comment by christarazi** [comment]
@dctrwatson Thanks for the pprof. From a quick glance, it looks like endpoint regeneration taking longer than previous versions potentially is the culprit:

![image](https://github.com/cilium/cilium/assets/3885308/05608214-b5c2-4afb-99c4-f09137c7fd30)

**Comment by ombre9** [comment]
@christarazi  We were running 1.13.1, then upgraded to 1.13.3 where the problem started happening, but it wasn't that significant, then upgraded to 1.13.4 where it got way worse. After trying out a few things and analyzed the logs it was clear the best is to downgrade.

**Comment by egsysoev** [comment]
@ombre9 Did you manage to upgrade cilium higher that 1.13.2? We are facing the similar issue but in our case (~400 nodes, ~120 pods per node) DNS proxy stops responding periodically.

**Comment by ombre9** [comment]
@egsysoev Yes, we did, we are running v1.14.7.

**Comment by egsysoev** [comment]
@ombre9 Thank you for reply! 
How did you choose this version? Are there any specific changes that fix dns problem?

**Comment by ombre9** [comment]
@egsysoev we didn't go from 1.13.2 to 1.14.7. We had many upgrades in between. tbh I don't remember which version solved our problem because it was a combination of thigs. We are running it in azure, where MS identified an issue with their DNS + we observed cilium is constantly running with high cpu usage which was caused by SNAT port exhaustion.
