### ISSUE TITLE
BGP CP: Move Default API Values to Type Definitions

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#25871]
Currently, default values are defined in the agent pkg. Instead, move these values to `pkg/k8s/apis/cilium.io/v2alpha1/bgpp_types.go`. This allows the default value to be versioned with the API. This also provides consistency with the kubebuilder tag that defines the default value. If the value needs to be changed, it's updated in one place.

**Comment by rastislavs** [comment]
Thanks @danehans  for reporting this (and other k8s API conventions inconsistencies ;))
I am working on a refactor that would address all API inconsistencies for the BGP CP, will incorporate this one into that.

**Comment by danehans** [comment]
> Thanks @danehans for reporting this (and other k8s API conventions inconsistencies ;))

@rastislavs that's great to hear. Pls cc me on your PR so I can review it.
