### ISSUE TITLE
[cilium+metallb] When cilium and metallb (layer 2 mode) are used together, pod can't response large packets(bigger than a MTU)

### ISSUE THREAD

**Issue by rogerBridge** [cilium/cilium#25886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

environment:
metallb 0.13.7, use layer 2 mode
cilium 1.13.3, use DSR mode
network card MTU is 1508, cilium MTU is 1508
linux kernel version is 5.10
kubernetes version is 1.21.14

problem:
When the udp packet is sent from the outside to the pod in the kubernetes cluster (the outside is connect to the LoadBalancer service, and cilium use random loadbalancing algorithm to access one of the pods), if the pod and the metallb-speaker are on the same node, then when the pod replies with a udp message exceeding one MTU, the outside cannot receive it, but those pods that are not on the same node with the metallb-speaker master can reply to external udp messages that exceed one mtu (all pods use cilium egress, and egress network card use metallb-speaker master's info)

### Cilium Version

1.13.3

### Kernel Version

5.10.0

### Kubernetes Version

v1.21.14

### Anything else?

when the external udp requests the loadBalancer service, the requested packet size exceeds the mtu, and the service response packet also exceeds the mtu, at this time, the pod located on the same node as the main metallb cannot respond to the udp request, but other pod can

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
So if I understand correctly, in the diagram below, return traffic for pod1 does not work but for pod2 it does?

```mermaid
flowchart LR
    
    subgraph node2
        pod2
    end

    subgraph node1
        pod1 
        lb-svc
    end
    
    external-host

    external-host --> lb-svc 
    pod2 --> external-host
    pod1 --> external-host
    lb-svc --> pod1
    lb-svc --> pod2

```

It would be helpful if you could collect the routes present in both pod1 and pod2 since those will determine the MTU used by the pods for the different destionations.

**Comment by rogerBridge** [comment]
@dylandreimerink Yes!!! your understanding is correct

**Comment by rogerBridge** [comment]
@dylandreimerink 
thank u, bro, first, your data packet path is correct. Second, my description is inaccurate. It is not that the pod on the same node as the metallb master cannot reply, but that the reply message data is damaged. Taking the response of 2000 bytes as an example, I After the metallb master node captures the packet, it is found that cilium will modify the seventh and eighth bytes of the data part of the second message of the udp response message, so that the outside cannot assemble the message replied by the pod

**Comment by rogerBridge** [comment]
@dylandreimerink It should be that cilium regards the second data packet as a udp data packet, and wants to modify the udp header check value, but the second data packet is an ipv4 data packet, and modifying the data packet leads to data corruption

**Comment by jasongwq** [comment]
Could you provide the network packets when the issue occurs?
