### ISSUE TITLE
Auth: Support garbage collection for KVStore Identity Backend

### ISSUE THREAD

**Issue by mhofstetter** [cilium/cilium#25898]
Currenty, Auth Map garbage collection builds on top of K8s Resource of type CiliumIdentity to delete auth map entries whenever a identity gets deleted. This only works if the Identity Store is backed by CRDs and not KVStore.

This issue should track this limitation and implement support for KVStore.

**Comment by joestringer** [comment]
@mhofstetter  Is there a commandline guardrail in cilium-agent or cilium-operator that informs or prevents the user from deploying Cilium with this combination of settings? That check would be good to land in 1.14, then we can target kvstore backend support with auth mode in a subsequent release.

**Comment by mhofstetter** [comment]
> @mhofstetter Is there a commandline guardrail in cilium-agent or cilium-operator that informs or prevents the user from deploying Cilium with this combination of settings? That check would be good to land in 1.14, then we can target kvstore backend support with auth mode in a subsequent release.

@joestringer no - not yet.

But https://github.com/cilium/cilium/pull/26373 & https://github.com/cilium/cilium/pull/26375, which are planned to land in v1.14, should cover the issue with the duplicated CiliumIdentity K8s Watcher and add support for the KVStore Identity Backend.

**Comment by joestringer** [comment]
@mhofstetter thanks. What's the state of testing for the auth feature overall and in kvstore mode in particular? Do we need to mark some of this as beta?

**Comment by mhofstetter** [comment]
@joestringer In general, the feature is covered by the [Cilium CLI connectivity tests](https://github.com/cilium/cilium-cli/blob/main/connectivity/suite.go#L965-L982) which are executed in the [Cilium Conformance-E2E-Tests](https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-e2e.yaml#L347-L348).

As for the KVStore mode in particular, we might lack some coverage because AFAIK the Conformance-E2E tests don't test KVStore mode. But we only rely on KVStore only indirectly for Auth Map Garbage Collection, where we are interested in the deleted CiliumIdentities. By using the observable Identity Allocator that acts as an abstraction for the CRD & KVStore identity backends we should be fine (https://github.com/cilium/cilium/pull/26373 & https://github.com/cilium/cilium/pull/26375).

For the time being, we lack automated e2e-tests for the re-auth & auth map gc part. These parts are covered with Unit Tests only. Connectivity Tests might not be the ideal test for this use-case.

Overall i think we should discuss the state of the auth feature for v1.14 in general and not KVStore in particular (at least after having the mentioned PRs merged and this issue closed). Therefore i would recommend to discuss this on the [overall auth roadmap issue](https://github.com/cilium/cilium/issues/22215). WDYT? 

/cc @youngnick

**Comment by youngnick** [comment]
I think the mutual feature overall is in good shape, with pretty good test coverage, and meets most of the criteria for a Limited feature, with the exception of actual usage, but I'll put something on the overall auth roadmap issue.
