### ISSUE TITLE
[Feature Request] Controls the maximum number of external connections(through loadbalancer) to a pod

### ISSUE THREAD

**Issue by rogerBridge** [cilium/cilium#25890]
The usage scenario is as follows: External access to a group of pods through loadbalancer. Can you provide a method to control the maximum number of external connections that a pod can accept (external connections: connections to access pods through loadbalancer), for example, 20000. If it is full, loadbalancer forwarding to other pods, if the number of external connections of all pods in the loadbalancer is full, then stop forwarding to pods

**Comment by dylandreimerink** [comment]
Can you explain what the use-case for this feature is? Purposefully dropping connections above a certain threshold does not sound desirable. Even if it was, why make Cilium do that and not the process itself? 

>  If it is full, loadbalancer forwarding to other pods
I do see something in a least connections mode where a backend is picked based on the least amount of active connections.
