### ISSUE TITLE
Annotate endpoint in k8s only if endpoint is managed by k8s

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2593]
It seems we try to annotate endpoint even if that endpoint is not managed by kubernetes:

https://github.com/cilium/cilium/blob/e79cd67c8703369bc94b9eb6f41270f86242be98/pkg/endpoint/policy.go#L845

```
level=error msg="error getting pod for endpoint" endpointID=63264 error="resource name may not be empty" k8sIdentityAnnotation=cilium.io/identity k8sNamespace= k8sPodName=
level=error msg="error getting pod for endpoint" endpointID=34774 error="resource name may not be empty" k8sIdentityAnnotation=cilium.io/identity k8sNamespace= k8sPodName=
```

**Comment by tgraf** [comment]
We are also spawning two nested go subroutines instead of one

**Comment by tgraf** [comment]
There is another issue, on failure to annotate and when the update failed because of an outdated resources, we still sleep until retrying again, as the sleep time increases, it becomes more and more unlikely that we can get a successful update as the time between fetch & update increases

**Comment by tgraf** [comment]
Several other issues:
- The endpoint is no longer locked in the go subroutine
- Several go subroutines can overlap annotating the same pod and possibly overwriting with older values if previous updates failed
