### ISSUE TITLE
agent: Deprecate --kube-proxy-replacement=partial

### ISSUE THREAD

**Issue by brb** [cilium/cilium#25988]
And change the flag to `--kube-proxy-replacement=boolean`, where `false` allows a user to control each individual feature (e.g., `--enable-node-port=true` to enable the BPF NodePort).

The release blockers after https://github.com/cilium/cilium/pull/26036 has been merged:

- [ ] KPR GSG docs
- [ ] Upgrade guide (incl., the external-ips and host-port defaults change)
- [x] GH workflows update

**Comment by aojea** [comment]
does not this break the compatibility with previous tools that use this flags?

**Comment by brb** [comment]
> does not this break the compatibility with previous tools that use this flags?

Users will have enough time to update their tools. We will completely remove the options in v1.16.

**Comment by aojea** [comment]
+1 the less options the better , just curious about how the project handles this deprecations

**Comment by brb** [comment]
> just curious about how the project handles this deprecations

Deprecate an option and announce in the upgrade guide of v1.X.0 about deprecation, then remove the option in v1.X+1.0. Considering how widely the `--kube-proxy-replacement` is used, we will remove the `partial` in v1.X+2.0.
