### ISSUE TITLE
Verify and make Envoy the default option

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2601]

**Comment by jrajahalme** [comment]
@tgraf Do we have rc3 released, or should I test this on rc3 branch?

**Comment by tgraf** [comment]
> Do we have rc3 released, or should I test this on rc3 branch?

You can use `cilium/cilium:v1.0.0-rc3` or `cilium/cilium:stable`, both point to rc3.

**Comment by jrajahalme** [comment]
Verified with gRPC GSG. Envoy runs as intended on cilium/cilium:stable :-) Posted a clean-up PR on gRPC GSG to remove the cilium.yaml editing steps (#2622).

**Comment by tgraf** [comment]
Envoy is not being built when running `make` yet it seems.

**Comment by tgraf** [comment]
Envoy has been enabled by default in rc4
