### ISSUE TITLE
CI: Only allow one concurrent build per PR in Cilium-Ginkgo-Tests

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2604]
Via Slack: 

"it looks like if you launch two consecutive CI runs for the same PR on Cilium-Bash-Tests, the second one will interrupt the first. Doesn't look like the same rule applies to Cilium-Ginkgo-Tests though."

We should ensure that per-PR, only one build of each job can run at a time. This ensures that all jobs are treated equally with respect to build resources.

**Comment by joestringer** [comment]
I think this is actually working as intended now. I just pushed a couple of commits and the ginkgo test for the previous PR got interrupted/cancelled.

**Comment by ianvernon** [comment]
Ah, great! Thanks for confirming :D
