### ISSUE TITLE
CI: ConformanceAKS - Clean up Cilium

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#26075]
## CI failure

Hit on https://github.com/cilium/cilium/pull/25921: https://github.com/cilium/cilium/actions/runs/5220654175/jobs/9424008106

```
Run pkill -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay"
  pkill -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay"
  cilium uninstall --chart-directory=install/kubernetes/cilium --wait
  shell: /usr/bin/bash -e {0}
  env:
    name: cilium-cilium-5220654175
    location: westeurope
    cost_reduction: --node-vm-size Standard_B2s --node-osdisk-size 30
    cilium_cli_version: v0.14.5
    cilium_cli_ci_version: 
    check_url: https://github.com/cilium/cilium/actions/runs/5220654175
    job_name: Installation and Connectivity Test
    QUAY_ORGANIZATION: cilium
    QUAY_ORGANIZATION_DEV: cilium
    QUAY_CHARTS_ORGANIZATION_DEV: cilium-charts-dev
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 

Error: Process completed with exit code 1.
```

It seems that the background `cilium hubble port-forward` process terminated early for some reason, causing `pkill` to fail since no matching process was found (Exit code 1 means `No processes matched or none of them could be signalled` according to the man page).

Sysdump: [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/11706108/cilium-sysdumps.zip)

**Comment by aspsk** [comment]
Given the flakyness of the `kubectl port-forward`, we need to ignore the exit value `1` of `pkill` to prevent from this flake

**Comment by tklauser** [comment]
Hit in https://github.com/cilium/cilium/pull/26390: https://github.com/cilium/cilium/actions/runs/5332672234/jobs/9662173594
