### ISSUE TITLE
Ginkgo: Come up with a better way to test that monitor output is flushed

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2608]
Throughout the monitor tests, we sleep to wait for monitor output to have what we need:

https://github.com/cilium/cilium/blob/41b47f20a332d03e9ea076ca985ea52576f24fe8/test/runtime/monitor.go#L89

https://github.com/cilium/cilium/blob/41b47f20a332d03e9ea076ca985ea52576f24fe8/test/runtime/monitor.go#L121

https://github.com/cilium/cilium/blob/41b47f20a332d03e9ea076ca985ea52576f24fe8/test/runtime/monitor.go#L145

https://github.com/cilium/cilium/blob/41b47f20a332d03e9ea076ca985ea52576f24fe8/test/runtime/monitor.go#L177

https://github.com/cilium/cilium/blob/41b47f20a332d03e9ea076ca985ea52576f24fe8/test/runtime/monitor.go#L206

This already adds 1/3 minute per run, we should try to come up with ways to avoid long sleeps like this.

**Comment by eloycoto** [comment]
Comments added by @tgraf in cilium slack: 
```
tgraf [4:27 PM] The monitor tests need to be reworked, the enforcement of > 3 lines in the monitor is arbitrary and depends on timing
tgraf [4:29 PM] The tests should either expect certain output to validate if --to and --related-to match everything required or succeed on any output
[4:29 PM] and just block until output happens with a timeout
```

**Comment by eloycoto** [comment]
Hi @joestringer  this was fixed by: 

https://github.com/cilium/cilium/pull/3139

Regards
