### ISSUE TITLE
CFP: Native ARP Support or metalLB support for production environments without BGP capability

### ISSUE THREAD

**Issue by Syntax3rror404** [cilium/cilium#26098]
I am loving Cilium! I have been running a cluster in my home lab, integrating it with OPNsense and BGP, along with the kube-proxy replacement, and it's working wonderfully!

At work, we would like to build a larger cluster based on Cilium and kubeadm. However, the problem is that Cilium inherently supports only BGP as its load balancing solution, and currently, we don't have the ability to use BGP in our data center.

Therefore, I have the following questions regarding a production setup without BGP support:

1) MetalLB: MetalLB allows for load balancing and provisioning of external IPs based on ARP, eliminating the need for a BGP router. This solution seems viable. Is it possible to install Cilium as the CNI and kube-proxy replacement while also using MetalLB for handling external IPs? **I have come across some information suggesting that MetalLB may not integrate well with Cilium**. Could you provide guidance on this compatibility issue?

2) Cilium native solution: What are your recommendations in such scenarios? What is the best practice for using Cilium as a solution in environments without BGP capability? Or would the solution mentioned above be the one you would support?

Thank you in advance for your assistance and for providing such a great product!

**Comment by lostz** [comment]
sam as i

**Comment by dylandreimerink** [comment]
https://github.com/cilium/cilium/pull/25471 was recently merged, which provides native ARP support for services. Here are the corresponding docs: https://docs.cilium.io/en/latest/network/l2-announcements/

**Comment by Syntax3rror404** [comment]
> #25471 was recently merged, which provides native ARP support for services. Here are the corresponding docs: https://docs.cilium.io/en/latest/network/l2-announcements/

Thank you for your work!! This means, that we must wait for the next cilium release?

**Comment by dylandreimerink** [comment]
Yes, this feature will be part of the upcoming v1.14 release. It should already be available in the latest CI build https://github.com/cilium/cilium#development if you want to test the feature right now. 

It will also be available in snapshot 4 or RC1 which ever will be released first, again use these versions at your own risk until the official stable release.

**Comment by dylandreimerink** [comment]
https://github.com/cilium/cilium/releases/tag/v1.14.0-snapshot.4
