### ISSUE TITLE
CI: ConformanceEKS: failed to fetch cilium runtime config: error dialing backend: remote error: tls: internal error`

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#26112]
## CI failure

```
⚠️  Unable to detect Cilium version, assuming v1.13.2 for connectivity tests: unable to parse cilium version on pod "cilium-7pkkz": unable to fetch cilium version on pod "cilium-7pkkz": error dialing backend: remote error: tls: internal error
```

This indicates that cilium-cli is unable to talk to the K8s apiserver or kubelet on the node. It seems like the sysdump was able to succeed tough, so this might have been an ephemeral error.

https://github.com/cilium/cilium/actions/runs/5188573844/jobs/9352416199

[logs_1565015.zip](https://github.com/cilium/cilium/files/11721513/logs_1565015.zip)

Unfortunately the sysdump already expired.

**Comment by holgerson97** [comment]
For everybody passing by: I fixed it by disabling my Wireguard client.
