### ISSUE TITLE
CFP: Add workqueue metrics for cilium-agent

### ISSUE THREAD

**Issue by ysksuzuki** [cilium/cilium#26122]
## Cilium Feature Proposal
        
It would be helpful to add workqueue metrics such as the depth, current depth of a workqueue, and the latency, how long an item stays in a workqueue to monitor the agent's k8s watcher performance.
https://github.com/kubernetes/client-go/blob/5a019202120ab4dd7dfb3788e5cb87269f343ebe/util/workqueue/metrics.go#L73-L90

`Resource[T k8sRuntime.Object]` relies on workqueue(enqueue items on cache.ResourceEventHandler), and some watchers, such as the EndpointSlice watcher, are using it with the latest implementation.
https://github.com/cilium/cilium/blob/9dc8dae85b50415ce4483962e2b0efb9d170b39b/pkg/k8s/resource/resource.go#L339

**Is your feature request related to a problem?**

We sometimes see the agent's sync delay when a large number of Pods restart, and the following logs from client-go is appearing when delays occur.(v1.12) With the new `Resource[T k8sRuntime.Object]` implementation, we should monitor the workqueue instead of DeletaFIFO.

```
2023-04-17 19:09:48 level=info msg="Trace[1730758035]: \"DeltaFIFO Pop Process\" ID:app/moco-mysql-675dn,Depth:1026,Reason:slow event handlers blocking the queue (17-Apr-2023 10:09:48.471) (total time: 109ms):" subsys=klog
```

**Describe the feature you'd like**

Add workqueue metrics using [workqueue.SetProvidor](https://github.com/kubernetes/client-go/blob/5a019202120ab4dd7dfb3788e5cb87269f343ebe/util/workqueue/metrics.go#L264)

**(Optional) Describe your proposed solution**

Currently, there's a conflict with the controller-runtime metrics registration. So we need to fix it.

**Comment by joestringer** [comment]
Sounds like a good idea to me, cc @cilium/metrics

**Comment by chancez** [comment]
+1 to work queue metrics, they're arguably one of the most useful ones.

**Comment by clay-moss** [comment]
@joestringer @chancez Can this be done for the operator as well? I am seeing issues with IPAM initialization and this warning appears frequently:

```
2023-06-13T14:07:31.756702202Z level=info msg="Trace[1582166779]: \"DeltaFIFO Pop Process\" ID:kube-system/hubble-metrics-5cprm,Depth:2040,Reason:slow event handlers blocking the queue (13-Jun-2023 14:07:31.155) (total time: 600ms):" subsys=klog
```

**Comment by ysksuzuki** [comment]
> Currently, there's a conflict with the controller-runtime metrics registration. So we need to fix it.

controller-runtime calls workqueue.SetProvider in its init function, and we can't use it to register the workqueue metrics to our registry because it can be called only once, and subsequent calls will be ignored. 

controller-runtime registers the workqueue metrics to its registry using workqueue.SetProvidor in its init function here.
https://github.com/kubernetes-sigs/controller-runtime/blob/451530c09937350ff7f5ebf7a00d059b4334e8ee/pkg/metrics/workqueue.go#L99

`github.com/cilium/cilium/operator/metrics` imports `sigs.k8s.io/controller-runtime/pkg/metrics`
https://github.com/cilium/cilium/blob/be2cb2bcc5300c7c634d8d5596b7869f3e7799be/operator/metrics/metrics.go#L13

cilium-agent doesn't use controller-runtime, however, it has an indirect dependency on controller-runtime. For example, these are the dependency graphs below.

```
- github.com/cilium/cilium/daemon/cmd -> github.com/cilium/cilium/pkg/ipam -> github.com/cilium/cilium/pkg/ipam/metrics -> github.com/cilium/cilium/operator/metrics
- github.com/cilium/cilium/daemon/cmd -> github.com/cilium/cilium/pkg/ipam -> github.com/cilium/cilium/operator/watchers -> github.com/cilium/cilium/operator/pkg/ciliumendpointslice -> github.com/cilium/cilium/operator/metrics
```

I think that the root cause is that `github.com/cilium/cilium/pkg/ipam` depends on the operator's package.

**Comment by ysksuzuki** [comment]
The possible solutions:

1. Remove the dependency from `github.com/cilium/cilium/pkg/ipam` to `github.com/cilium/cilium/operator/metrics`
2. Add a feature to controller-runtime to opt out of automatic registration of metrics
3. Use controller-runtime metrics registry instead of Cilium metrics registry

**Comment by ysksuzuki** [comment]
Also, we need to create a rateLimitingQueue with a name like this to export workqueue metrics

```
workqueue.NewRateLimitingQueueWithConfig(rateLimiter, RateLimitingQueueConfig{Name: name})
```

**Comment by joestringer** [comment]
We discussed this during the APAC call on 2023-06-20. Regarding this solution:

> Remove the dependency from github.com/cilium/cilium/pkg/ipam to github.com/cilium/cilium/operator/metrics

It's surprising to us that daemon depends on operator packages. This should probably be cleaned up anyway, so it seems like a good target for the fix. If we dependency-inject the metrics, then the ipam package shouldn't need to depend on metrics.

**Comment by ysksuzuki** [comment]
I'm working on it
https://github.com/cilium/cilium/pull/27042
