### ISSUE TITLE
Kafka proxy allows traffic for unknown identities by default

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2612]
It seems whenever the identity is not found by the agent, line 137, we are simply logging that. This would later, on line 146, cause the kafka rules to be `nil` and returning `true` for an unknown identity, line 152.

https://github.com/cilium/cilium/blob/41b47f20a332d03e9ea076ca985ea52576f24fe8/pkg/proxy/kafka.go#L133-L152

These were the log messages I saw:
```
...
level=warning msg="Unable to resolve identity to labels" identity=746 req="apiKey=18,apiVersion=1,len=30: null"
level=debug msg="Allowing, no Kafka rules loaded" req="apiKey=18,apiVersion=1,len=30: null"
...
```

The easiest way to see this bug is to run 2 hosts, where one of the host is not aware of the other's hosts identities. For example on this case, the identity `746` was running on host-1, and these logs were taken on host-2.

**Comment by tgraf** [comment]
What policy do you have loaded? I would expect the default rules to apply in this case.
