### ISSUE TITLE
Worker node cannot reach CoreDNS service while master node is able to

### ISSUE THREAD

**Issue by nadecancode** [cilium/cilium#26141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have Cilium with kube-proxy-less installed on a master node. Yesterday, I tried adding one more node with a dedicated traefik ingress controller but it is not able to connect to the kube API route. I did a bit digging and it turns out that pod is not able to access the kube-dns service IP. The issue above only exists in worker node.

I have also made sure that the Cilium CIDR is not overlapping with the node CIDR (I changed it to one that is definitely not overlapping but the issue still persists)

### Cilium Version

cilium-cli: v0.14.2 compiled with go1.20.2 on linux/amd64
cilium image (default): v1.13.2
cilium image (stable): v1.13.3
cilium image (running): v1.13.2

### Kernel Version

Linux k8s 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - master node
Linux k8s-worker 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - worker node

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230613-004122.zip](https://github.com/cilium/cilium/files/11728591/cilium-sysdump-20230613-004122.zip)

### Relevant log output

```shell
root@k8s:~# cilium connectivity test
ℹ️  Monitor aggregation detected, will skip some flow validation steps
⌛ [kubernetes] Waiting for deployments [client client2 echo-same-node] to become ready...
⌛ [kubernetes] Waiting for deployments [echo-other-node] to become ready...
⌛ [kubernetes] Waiting for CiliumEndpoint for pod cilium-test/client-6965d549d5-rf9gr to appear...
⌛ [kubernetes] Waiting for CiliumEndpoint for pod cilium-test/client2-76f4d7c5bc-r2wnt to appear...
⌛ [kubernetes] Waiting for pod cilium-test/client2-76f4d7c5bc-r2wnt to reach DNS server on cilium-test/echo-same-node-577576cc5-gthfw pod...
⌛ [kubernetes] Waiting for pod cilium-test/client-6965d549d5-rf9gr to reach DNS server on cilium-test/echo-same-node-577576cc5-gthfw pod...
⌛ [kubernetes] Waiting for pod cilium-test/client-6965d549d5-rf9gr to reach DNS server on cilium-test/echo-other-node-7dd489897c-7j695 pod...
connectivity test failed: timeout reached waiting lookup for localhost from pod cilium-test/client-6965d549d5-rf9gr to server on pod cilium-test/echo-other-node-7dd489897c-7j695 to succeed (last error: context deadline exceeded)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NADESHIKON** [comment]
```
Cluster health:     1/2 reachable     (2023-06-13T04:35:42Z)                                                
  Name              IP                Node        Endpoints                                                 
  k8s (localhost)   redacted       reachable   reachable                                                 
  k8s worker           redacted   reachable   unreachable
```

It seems that worker node is reachable but the endpoint is not

**Comment by NADESHIKON** [comment]
Magically fixed itself after completely reinstalling cilium.
