### ISSUE TITLE
CI: Conformance E2E - egress-gateway

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#26158]
## CI failure

Hit on https://github.com/cilium/cilium/pull/26109: https://github.com/cilium/cilium/actions/runs/5252755259/jobs/9489217504
Matrix entry: (7, bpf-next-20230420.212204, none, strict, disabled, snat, true, testing-only)

```
[=] Test [egress-gateway]

ℹ️  📜 Applying CiliumEgressGatewayPolicy 'cegp-sample-echo-service' to namespace ''..
ℹ️  📜 Applying CiliumEgressGatewayPolicy 'cegp-sample' to namespace ''..
[-] Scenario [egress-gateway/egress-gateway]
🟥 Failed to ensure egress gateway policy map is properly populated: timeout while waiting for condition, last error: Could not find egress gateway policy entry matching {SourceIP:10.244.3.62 DestCIDR:0.0.0.0/0 EgressIP:0.0.0.0 GatewayIP:172.18.0.5}
ℹ️  📜 Deleting CiliumEgressGatewayPolicy 'cegp-sample' from namespace ''..
ℹ️  📜 Deleting CiliumEgressGatewayPolicy 'cegp-sample-echo-service' from namespace ''..

connectivity test failed: 1 tests failed
📋 Test Report
❌ 1/50 tests failed (0/539 actions), 10 tests skipped, 0 scenarios skipped:
Test [egress-gateway]:
```

Sysdump: [cilium-sysdump-7-final.zip](https://github.com/cilium/cilium/files/11732749/cilium-sysdump-7-final.zip)

Looking at the sysdump, this error message looks suspicious:

```
level=error msg="Failed to get identity labels for endpoint, skipping update to egress policy." error="identity 28814 not found" k8sEndpointName=echo-other-node-7bc75565b9-287c5 k8sNamespace=cilium-test subsys=egressgateway
```

**Comment by jibi** [comment]
We tried to reproduce this failure without much success, some more context in this thread https://isovalent.slack.com/archives/C02DXV6DQQL/p1685045292165899

**Comment by qmonnet** [comment]
[Hit also](https://github.com/cilium/cilium/actions/runs/5254364399/jobs/9508696175) in https://github.com/cilium/cilium/pull/23165.
