### ISSUE TITLE
DSR broken with VLANs on 1.13.3

### ISSUE THREAD

**Issue by kvaster** [cilium/cilium#26166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We use cilium on tagged VLAN. Main interface has static address and VLAN interface has dynamically assigned (keepalived)  external addresses.

The following commit breaks DSR on our setup: https://github.com/cilium/cilium/commit/78f93188ae0e4a74c3794b517047e33b9c3984c5

Before 1.13.3 packets were output as it should be - on tagged interface (`wan0.4000` in our case) and with 1.13.3 packets are outputed:
* through `wan0.4000` interface if source address (packet was received on) currently directly belongs to this server (this is correct)
* through `wan0` interface in other situation and this breaks connectivity

It seems that new code ignores ip rules.

For test in VM (full setup: https://github.com/kvaster/k8s-test-guide):
10.117.10.x/24 - static internet addresses assigned to `wan0`. This addresses are used to connect via ssh to servers and to connect to internet from inside kubernetes.
10.117.12.x/24 - static addresses assigned to tagged vlan `wan0.4000`. This addresses are internal static network - used by kubernetes nodes
10.117.11.x/24 - dynamic internet addresses assigned `wan0.4000` devices via keepalived. This addresses are used by clients to connect to kubernetes ingress from outside of the world.

Following additional routes applied:
```
10.117.11.0/24 dev wan0.4000
10.117.11.0/24 dev wan0.4000 table vswitch
10.117.12.0/24 dev wan0.4000 table vswitch
```

Following additional rules applied:
```
from all to 10.244.0.0/16 lookup main priority 200
from 10.117.11.0/24 table vswitch priority 201
from 10.117.12.100 lookup vswitch priority 202
from 10.117.12.0/24 lookup vswitch priority 202
```

### Cilium Version

1.13.3

### Kernel Version

6.3.4

### Kubernetes Version

1.26.4

### Sysdump

[cilium-sysdump-20230613-124152.zip](https://github.com/cilium/cilium/files/11733377/cilium-sysdump-20230613-124152.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report. Do you know the last version that worked successfully? This might help to narrow down where the regression was introduced (using `git log`).

**Comment by julianwiedmann** [comment]
:wave: thanks for the report!

> 10.117.11.x/24 - dynamic internet addresses assigned wan0.4000 devices via keepalived. This addresses are used by clients to connect to kubernetes ingress from outside of the world.

I assume what you're seeing is that such reply traffic (originating from these addresses) gets misrouted on egress now? That would make sense.

Essentially the same scenario as https://github.com/cilium/cilium/pull/26136, we need a FIB lookup after RevDNAT. Should be easy to add once those helpers are in.

**Comment by julianwiedmann** [comment]
I've started to hack up needed changes up, should have a PR soon. Tentatively marking as blocker for 1.14 so we don't lose track of it.

**Comment by julianwiedmann** [comment]
> I've started to hack up the needed changes, should have a PR soon. Tentatively marking as blocker for 1.14 so we don't lose track of it.

Don't think we will fully wrap this up before the release, and it's too big of a change to push in last minute. So we'll just backport when ready.

**Comment by kvaster** [comment]
From my point of view it looks like completely broken functionality for us :)

**Comment by julianwiedmann** [comment]
:wave: heya @kvaster - with https://github.com/cilium/cilium/pull/26638 merged into `main`, did you have a chance to test whether this issue is resolved?

FYI, https://github.com/cilium/cilium/pull/27381 has images for the pending v1.14 backport.

**Comment by kvaster** [comment]
Thanks! I'm planning to test today and will get back as soon as I will have results.

**Comment by kvaster** [comment]
Seems to work OK!
