### ISSUE TITLE
Service cache: populate OldEndpoints when merging information from remote clusters 

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#26176]
https://github.com/cilium/cilium/pull/25687 added an `OldEndpoints` field to the `ServiceEvent`, which is currently set to the same values as `Endpoints` when merging information from remote clusters. This followup issue proposes to compute and propagate the appropriate `OldEndpoints` value also in those cases, for consistency if it was needed to be relied upon. See https://github.com/cilium/cilium/pull/25687#discussion_r1223053368 for additional details.

**Comment by joestringer** [comment]
Should we just delete the field for now if it's not reliable?

**Comment by giorio94** [comment]
The field is currently populated and used when handling endpoint/endpointslice updates in the local cluster. This issue refers only to merging the information from remote clusters (AFAIU `OldEndpoints` is not used in that case, except maybe for external workloads if any service with endpoints outside of the cluster is present). Sorry if that wasn't clear from the original description.

**Comment by akstron** [comment]
Hi, I would like to work on this issue. Kindly assign it to me. Thanks

**Comment by swastik959** [comment]
@giorio94 hi I want to work on this issue can you please guide me through this

**Comment by giorio94** [comment]
Thanks to both! I've assigned this issue to @akstron, who asked first. If you have any questions, we are happy to help you on the #development channel on Cilium Slack.
