### ISSUE TITLE
clustermesh taking too long to start

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#26192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- clustermesh-apiserver pod is rescheduled
- 90 minutes before all pods in other clusters can talk to each other again 

### Cilium Version

Client: 1.12.10 628b520 2023-05-16T12:50:44-04:00 go version go1.18.10 linux/amd64
Daemon: 1.12.10 628b520 2023-05-16T12:50:44-04:00 go version go1.18.10 linux/amd64

### Kernel Version

Linux ip-10-193-51-181 5.15.0-1035-aws #39~20.04.1-Ubuntu SMP Wed Apr 19 15:34:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.13-eks-0a21954

### Anything else?

This is after raising QPS limit with `--kvstore-opt=etcd.qps=100`. etcd now uses 10-12 vCPUs during the initial sync, then falls back to ~1 vCPU.

We use CNPs in both clusters and they both contain egress and ingress rules that limit access by a shared label.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @dctrwatson , thanks for the report.

Are you able to track content of the etcd instance over this time?

I'm wondering about a couple of things related to clustermesh-apiserver operation:
- Can we gather a status of the amount of objects it intends to sync and progress?
- Do you think that etcd leases may be causing etcd state from prior to startup to be lost, and the newly restarted instance does not refresh the existing entries, hence potentially leading to a loss of entries during restart/upgrade?

> This is after raising QPS limit with --kvstore-opt=etcd.qps=100. etcd now uses 10-12 vCPUs during the initial sync, then falls back to ~1 vCPU.

Can you share a bit more about this, do you have dashboards or anything? When you say "initial sync", how long does that take? How does that compare to the 90 minutes you report?

**Comment by dctrwatson** [comment]
> Are you able to track content of the etcd instance over this time?

I don't think I've seen any metrics from clustermesh-apiserver. I just checked the helm chart and there's not a ServiceMonitor.
If etcd and/or clustermesh-apiserver expose a metrics endpoint that prometheus can scrape, I can get this.

Running `cilium status --all-clusters` on agents, I assume the nodes/identities/services are the content of the etcd instance.

> * Can we gather a status of the amount of objects it intends to sync and progress?
> Can you share a bit more about this, do you have dashboards or anything? When you say "initial sync", how long does that take? How does that compare to the 90 minutes you report?

The amount of time of the initial sync is proportional to the number of identities+services in the cluster. For example, the cluster that take 90 minutes for it initial sync has 7700 identities and 8000 services (though there's only like 16 global services, I reported that discrepenancy in https://github.com/cilium/cilium/issues/26049 ). Without the etcd

The CPU usage remains high until `cilium status` stops showing an increase in identities+services for that cluster. So that's why I assume it's an initial sync for the clustermesh-apiserver.

I'm watching the workload usage dashboard from the kube-prom community. So break-down of cpu usage by container for a pod.

> * Do you think that etcd leases may be causing etcd state from prior to startup to be lost, and the newly restarted instance does not refresh the existing entries, hence potentially leading to a loss of entries during restart/upgrade?

Per `cilium status`, it seems like clustermesh-apiserver come up with no state every time.
As for the agents' state, it's not a total loss. Only a couple remote endpoints lose their identity (and not usually the same ones) each time.

**Comment by giorio94** [comment]
Hi @dctrwatson, thanks for the report. You may also find https://github.com/cilium/cilium/issues/25562 relevant.

> I don't think I've seen any metrics from clustermesh-apiserver. I just checked the helm chart and there's not a ServiceMonitor.
> If etcd and/or clustermesh-apiserver expose a metrics endpoint that prometheus can scrape, I can get this.

Yes, the current stable versions of clustermesh-apiserver do not expose any metrics. They have been recently introduced and they are available in the latest v1.14 snapshot: https://docs.cilium.io/en/latest/observability/metrics/#cluster-mesh-api-server-metrics.

> The amount of time of the initial sync is proportional to the number of identities+services in the cluster. For example, the cluster that take 90 minutes for it initial sync has 7700 identities and 8000 services.

The time for synchronization completion is proportional to the total number of entries to be synchronized (nodes + identities + services + endpoints) and the rate limiting settings. At first sight, though, it should take much less than 90 minutes with the numbers you mentioned. There have been recently quite a few performance improvements in the clustermesh-apiserver area to reduce the time required to complete the synchronization (mainly https://github.com/cilium/cilium/pull/25260 and https://github.com/cilium/cilium/pull/25049). 

> though there's only like 16 global services, I reported that discrepenancy in https://github.com/cilium/cilium/issues/26049

I've posted a comment to https://github.com/cilium/cilium/issues/26049 with more details, but the TL;DR; is that it has been recently fixed. 

> Per cilium status, it seems like clustermesh-apiserver come up with no state every time.

Yes, this is correct, since etcd is part of the clustermesh-apiserver and the data is stored in an emptydir.

**Comment by dctrwatson** [comment]
> At first sight, though, it should take much less than 90 minutes with the numbers you mentioned.

Yeah, that's for our slowest clusters. Some clusters sync faster than others for some reason.

> There have been recently quite a few performance improvements in the clustermesh-apiserver area to reduce the time required to complete the synchronization (mainly #25260 and #25049).

Will these be backported to v1.12? (We can't upgrade to v1.13 yet due to other regressions)

**Comment by giorio94** [comment]
> > There have been recently quite a few performance improvements in the clustermesh-apiserver area to reduce the time required to complete the synchronization (mainly #25260 and #25049).
> 
> Will these be backported to v1.12? (We can't upgrade to v1.13 yet due to other regressions)

I'd personally say that they won't be backported. They practically rewrite most of the clustermesh-apiserver, and that would be a too drastic/risky change for a patch release; additionally, they also depend on other abstractions (mainly `Resource[T]`) which weren't present in v1.12 (some pieces are also missing in v1.13). 

But, theoretically speaking, there's nothing \[*\] which prevents the usage of a newer `clustermesh-apiserver` alongside an older cilium version. There have been no API changes, and it should just work as a drop in replacement (I've made a test and all connectivity checks passed).

\[*\]: there are actually two limitations that need to be considered:
* You may need to manually set additional clustermesh-apiserver CLI flags that were not present in previous versions (mainly to disable the synchronization of all services, or to enable the metrics exposition).
* There's currently an issue which prevents newer versions the clustermesh-apiserver to start when running against older versions of cilium: https://github.com/cilium/cilium/pull/26220

**Comment by dctrwatson** [comment]
> I'd personally say that they won't be backported. They practically rewrite most of the clustermesh-apiserver, and that would be a too drastic/risky change for a patch release; additionally, they also depend on other abstractions (mainly `Resource[T]`) which weren't present in v1.12 (some pieces are also missing in v1.13).
> 
> But, theoretically speaking, there's nothing [*] which prevents the usage of a newer `clustermesh-apiserver` alongside an older cilium version. There have been no API changes, and it should just work as a drop in replacement (I've made a test and all connectivity checks passed).

Ah, darn. I'm excited to try out all these improvements!

> * You may need to manually set additional clustermesh-apiserver CLI flags that were not present in previous versions (mainly to disable the synchronization of all services, or to enable the metrics exposition).

That's won't be an issue, we already materialize the helm template and do a bunch of patches via kustomize.

> * There's currently an issue which prevents newer versions the clustermesh-apiserver to start when running against older versions of cilium: [clustermesh-apiserver: don't wait for the presence of unused CRDs #26220](https://github.com/cilium/cilium/pull/26220)

Thank you! I will try out newer clustermesh-apiserver once there's a release including this patch.

**Comment by giorio94** [comment]
Great! FYI, the above patch has been merged today, and it will be included in the next release.

**Comment by giorio94** [comment]
I'm closing this issue, given that the refactored clustermesh-apiserver has landed in v1.14. 
@dctrwatson Feel free to reopen it if you continue to experience issues also with the updated version.
