### ISSUE TITLE
Cannot connect a Docker container to another Docker network

### ISSUE THREAD

**Issue by EtienneM** [cilium/cilium#26190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am in a situation where I would like to have a Docker container in two different networks: a Cilium network, and another one.

## Steps to Reproduce

1. Create the Cilium network: `docker network create --driver cilium --ipam-driver cilium cilium-net`
2. Create the other Docker network: `docker network create other-net`
3. Create an application on the other network: `docker run --rm --net other-net cilium/demo-httpd`
4. Connect the container to the Cilium network: `docker network connect cilium-net $container_id`

We face the following error:

```
Error response from daemon: failed to add static route 0.0.0.0/0: file exists
```

If we first create the application in the Cilium network, then connect it to the other network, the error message is different:

```
Error response from daemon: failed to set gateway while updating gateway: file exists
```

The following piece of code seems relevant to this issue:

https://github.com/cilium/cilium/blob/36cb0eed03c8bc6576f3fd33a94440c70ae18974/plugins/cilium-docker/driver/driver.go#L496-L505

https://github.com/cilium/cilium/blob/1.13.3/plugins/cilium-docker/driver/driver.go#L496-L505

### Cilium Version

```
vagrant@agent-1:~$ sudo cilium version
Client: 1.13.2 8cb94c70 2023-04-17T23:19:21+02:00 go version go1.19.8 linux/amd64
Daemon: 1.13.2 8cb94c70 2023-04-17T23:19:21+02:00 go version go1.19.8 linux/amd64
```

### Kernel Version

```
Linux agent-1 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

n/a

Running without Kubernetes

### Sysdump

```
vagrant@agent-1:~$ sudo cilium-cli sysdump
🔍 Collecting sysdump with cilium-cli version: v0.14.6, args: [sysdump]
failed to create sysdump collector: failed to detect Cilium namespace: Get "http://localhost:8080/api/v1/namespaces/kube-system": dial tcp 127.0.0.1:8080: connect: connection refused
```

which makes sense as we don't use Kubernetes.

### Relevant log output

```shell
cilium-agent          | level=info msg="Create endpoint request" addressing="&{10.15.1.94/32   }" containerID= datapathConfiguration="<nil>" interface=lxc0b8a340f050b k8sPodName=/ labels="[]" subsys=daemon sync-build=true
cilium-agent          | level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2294 ipv4= ipv6= k8sPodName=/ subsys=endpoint
cilium-agent          | level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2294 identityLabels="reserved:init" ipv4= ipv6= k8sPodName=/ subsys=endpoint
cilium-agent          | level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2294 identity=5 identityLabels="reserved:init" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
cilium-agent          | level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2294 identity=5 ipv4= ipv6= k8sPodName=/ subsys=endpoint
cilium-agent          | level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2294 identity=5 ipv4= ipv6= k8sPodName=/ subsys=endpoint
cilium-agent          | level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2294 identity=5 ipv4= ipv6= k8sPodName=/ subsys=daemon
cilium-agent          | level=info msg="Delete endpoint request" endpointID=2294 ipv4=10.15.1.94 ipv6= k8sNamespace= k8sPodName= subsys=daemon
cilium-agent          | level=info msg="Removed endpoint" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2294 identity=5 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

### Anything else?

I can see someone else faced the same issue a couple of years ago (#13161), with no real answer.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @EtienneM , thanks for the report.

Unfortunately, the cilium-docker plugin is no longer maintained by the Cilium project and is scheduled to be removed. You're welcome to pick up the code and tweak it to your own use based on the open source license, but it's decreasingly likely that any Cilium developers will be able to assist with this.

The cilium-cni plugin may provide a better alternative as it is still actively maintained, but be aware that the most common deployment platform for Cilium is on top of Kubernetes. Your mileage may vary when deploying Cilium on other platforms.

Closing "won't fix".

**Comment by EtienneM** [comment]
Thanks for your prompt answer which includes valuable information for us :)

We will have a look at the CNI plugin to replace the Docker one.
