### ISSUE TITLE
Binaries are installed even when cni.install is set to false

### ISSUE THREAD

**Issue by MaienM** [cilium/cilium#26198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I deployed the helm chart with `cni.install` set to false, but the `install-cni-binaries` container were still deployed and it still installed the binaries.

### Cilium Version

1.13.3

### Kernel Version

Linux host1 6.1.31 #1-NixOS SMP PREEMPT_DYNAMIC Tue May 30 13:03:33 UTC 2023 x86_64 GNU/Linux
Linux host2-7 6.1.21 #1-NixOS SMP Tue Jan  1 00:00:00 UTC 1980 aarch64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/arm64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @MaienM , thanks for the report.

Can you share the exact set of steps you used to reproduce this?

I tried this, and I don't see any CNI install being generated into the template:

```
$ helm template cilium cilium/cilium --version 1.13.3 --set cni.install=false | grep "cni.install"
$
```

**Comment by MaienM** [comment]
The container that's doing the installing is called `install-cni-binaries` (unless I'm misunderstanding what that does, but the log seems pretty unambiguous). Running the command you posted also gives me no results, but changing the name being `grep`ed gives me

```bash
$ helm template cilium cilium/cilium --version 1.13.3 --set cni.install=false | grep "install-cni-binaries"
      - name: install-cni-binaries
$
```

The output of the `install-cni-binaries` container:

```
Installing loopback driver...
cp: not writing through dangling symlink '/host/opt/cni/bin/loopback'
Installing cilium-cni to /host/opt/cni/bin/ ...
wrote /host/opt/cni/bin/cilium-cni
```

(The `loopback` symlink isn't actually dangling, it just appears to be because the container doesn't have the target mounted.)

**Comment by joestringer** [comment]
Thanks for the report! I've sent a fix for it. Do you think you'd be able to test it? Either way, it should end up in next month's patch releases.

**Comment by MaienM** [comment]
Just tried out the PR and yeah, works as expected (not that I really had any doubts looking at the PR).
