### ISSUE TITLE
CI: Cilium Runtime

### ISSUE THREAD

**Issue by pippolo84** [cilium/cilium#26233]
## CI failure

https://github.com/cilium/cilium/actions/runs/5253490286?pr=26159

Logs: [logs_1606536.zip](https://github.com/cilium/cilium/files/11747885/logs_1606536.zip)

**Comment by giorio94** [comment]
That error occurs when the cached Ginkgo binary got evicted by GH. In that case, you should rerun the full workflow rather than only the failed jobs.
