### ISSUE TITLE
init.sh: move tunnel device management to Go

### ISSUE THREAD

**Issue by rgo3** [cilium/cilium#26254]
The following code of init.sh deals with tunnel device creation and removal: https://github.com/cilium/cilium/blob/0b9824820db13e955a2713e106e2f488deb2d38e/bpf/init.sh#L241-L277 and should be moved to Go.

**Comment by cyclinder** [comment]
Hi @rgo3, I'm very interested in this, can I work on this?

**Comment by rgo3** [comment]
Absolutely @cyclinder!

I haven't really thought about this issue too much in terms where the new code should go but that's probably something we can figure out after we have a first draft.

Some quick pointers to things that will be relevant when working on this:
* [`Reinitialize()`](https://github.com/cilium/cilium/blob/390b4dc0d9ef63ae30f435e3ea2926069ef5a78b/pkg/datapath/loader/base.go#L288) is where `init.sh` is called from.
* There's also https://github.com/cilium/cilium/blob/main/pkg/datapath/loader/netlink.go, that file already has some functions to setup a device
* writing to `node_config.h` happens in [`WriteNodeConfig()`](https://github.com/cilium/cilium/blob/5a1770cd16c77fbd90469190c60c48ab44614b0d/pkg/datapath/linux/config/config.go#L84). We should try to accumulate any other writes to the file there as well, which in turn means that if you want to query the `ifindex` of the encap device in that function the device needs to be created before `WriteNodeConfig()` is called. The changes in https://github.com/cilium/cilium/pull/25380 should show equivalent code when calling `SetupBaseDevice()` and querying the respective `ifindex` values.

Once you have some code feel free to open a draft PR. Otherwise happy hacking!

**Comment by cyclinder** [comment]
thanks @rgo3 for the detail!

I'm new to this area, I'll spend time looking into this, and if there's code, I'll submit a PR, thanks again for your help!
