### ISSUE TITLE
CFP: More LoadBalancer algorithms

### ISSUE THREAD

**Issue by DanOfir** [cilium/cilium#26264]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

If so, please describe the problem

**Describe the feature you'd like**
I would like to have more Load Balancer algorithms.
currently, the default algorithm is random and there is an option to use also MAGLEV.

IPVS for example supports all  algorithms
Round Robin
Least connection
and more... 

I'm mostly interested in Least Connection in terms of priority.

i need the Service that load balance the traffic between all pods to work with Least Connections

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by joestringer** [comment]
Thanks for filing this feature request. I think it makes sense for Cilium to explore some of these more advanced load balancing modes. I've added labels to tag the relevant areas so that other interested members of the community can easily find this issue and discuss.

**Comment by klaymen47** [comment]
I'd like to express my interest in having a least connections LB available in Cilium as well. :)
