### ISSUE TITLE
healthCheckNodePort HTTP /healthz doesn't work with Proxy Protocol

### ISSUE THREAD

**Issue by gitanuj** [cilium/cilium#26274]
I am using Cilium as Kube Proxy replacement and NLB health checks are served by Cilium. However I need to use Proxy Protocol on NLBs to get extra information from AWS about VPC Endpoint ID and also use externalTrafficPolicy=Local so that the traffic is routed most efficiently (and never hops between nodes unnecessarily).

When externalTrafficPolicy=Local is used the nodePort is no longer served by health checks, instead healthCheckNodePort is served by all the cilium instances spread across all nodes. So the only option is to use HTTP health check and rely on 200 OK. The problem is that Cilium doesn't recognize Proxy Protocol (because it uses golang's net/http server) and HTTP health checks do not work at all.

Is there any other way to use Proxy Protocol on NLB and avoid unnecessary node hops with Cilium? If not, does it make sense to support Proxy Protocol in Cilium's kube proxy replacement health server?

**Comment by joestringer** [comment]
Hi @gitanuj , thanks for the report. How does this relate to the issue https://github.com/cilium/cilium/issues/21438 ? Is it the same or does this only apply to the health server provided for kube-proxy replacement?

**Comment by gitanuj** [comment]
This one specifically applies to only health server. The linked issue is asking for more where Cilium could parse PPv2 headers and use the source IP from there.

If only health server can just support accepting PPv2 TCP connections also (without even using any information from the headers) then cloud LBs with PPv2 can use HTTP health checks (which is needed for externalTrafficPolicy=True). Although I am not sure if kube-proxy supports such a scenario but this could be a nice addition.
