### ISSUE TITLE
Migrate to .readthedocs.yaml configuration file v2

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#26299]
We need to migrate to this configuration file at the risk that all our docs will stop being built https://blog.readthedocs.com/migrate-configuration-v2/

We will likely need to backport this to all branches that we support.

As we change the python version we will also need to update this file:
```patch
diff --git a/Documentation/Dockerfile b/Documentation/Dockerfile
index 30ae02186f..aca9a566a8 100644
--- a/Documentation/Dockerfile
+++ b/Documentation/Dockerfile
@@ -1,5 +1,5 @@
 # Python version should match the one in use in Read The Docs
-FROM docker.io/library/python:3.7.9-alpine3.13 AS docs-base
+FROM docker.io/library/python:3.11-alpine3.17 AS docs-base
 
 LABEL maintainer="maintainer@cilium.io"
 ```

which will unblock this PR https://github.com/cilium/cilium/pull/25689

**Comment by qmonnet** [comment]
> ## Deprecation timeline
>
> We understand this change will affect many of our users, so we have a timeline to communicate this deprecation to our users effectively.
>
> [...]
>
> - **Monday, August 14, 2023**: Do a second brownout (temporarily enforce this deprecation) for 24 hours: 00:01 PST to 23:59 PST (midnight)
>
> - **Monday, September 4, 2023**: Do a third and final brownout (temporarily enforce this deprecation) for 48 hours: 00:01 PST to 23:59 PST (midnight)
>
> - **Monday, September 25, 2023**: Fully remove support for building documentation without configuration file v2.

Would be nice to avoid the brownouts - next one in ten days from now. Donia, let me know if I can help on the `Documentation` side.

I expect backports to be straightforward, we're recently updated the doc framework to be nearly identical on all branches 1.12+.

**Comment by ti-mo** [comment]
Ping, this is approaching/ongoing.

**Comment by doniacld** [comment]
On it this week!
