### ISSUE TITLE
Cilium agent API rate limiting requests due to deadlock

### ISSUE THREAD

**Issue by bimmlerd** [cilium/cilium#26295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

From [Cilium Slack thread](https://cilium.slack.com/archives/C1MATJ5U5/p1683875356505479):

> We’re seeing a curious issue that’s just started to bite us with Cilium 1.13.2 in EKS clusters in vpc-eni mode. We’ve noticed that the Cilium agent API is rate limiting requests at different times. The interesting thing is that this is a really small cluster (6 nodes) and the only workload on it is a few Kuberhealthy pods firing up every couple of minutes. We see the endpoint-delete and endpoint-create calls time out. Also interesting is that similarly small clusters on the same version aren’t experiencing the issue, or certainly not anywhere near to the same extent. I’ve been through https://docs.cilium.io/en/v1.13/configuration/api-rate-limiting and can improve timeout rates by tweaking max-wait-duration, for example - but does anyone have any insight into why this might be happening to just this cluster?

With such a light workload, it's surprising that the API requests would time out/be rate limited. Resource availability was ruled out as the culprit. The user also reported that:

> Another effect of what I’m seeing is `cilium ip list` executed in a random agent pretty much always fail after a delay:

```
Error: Cannot get ipcache entries. err: Cilium API client timeout exceeded
command terminated with exit code 1
```

### Cilium Version

`1.13.3 36cb0eed 2023-05-17T12:31:14-04:00 go version go1.19.8 linux/amd64`

(also reported on 1.13.2)

### Kernel Version

`Linux ip-10-129-168-241.ec2.internal 5.10.179-168.710.amzn2.x86_64 #1 SMP Mon May 22 23:10:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.9-eks-0a21954", GitCommit:"eb82cd845d007ae98d215744675dcf7ff024a5a3", GitTreeState:"clean", BuildDate:"2023-04-15T00:37:59Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}`

### Sysdump

Sysdumps available, but too large to be attached. Attaching annotated, pruned and condensed stack trace instead
[condensed.txt](https://github.com/cilium/cilium/files/11767822/condensed.txt)

Specifically, we have the following go routine stack trace, which holds the endpoint lock and wants to acquire the IPCache lock. That is not allowed, c.f. https://github.com/cilium/cilium/pull/24582#issuecomment-1485365105.

```
1 occurences. Sample stack trace:
golang.org/x/sync/semaphore.(*Weighted).Acquire(0xc000efac30, {0x3897670, 0xc00007e030}, 0x40000000)
	./vendor/golang.org/x/sync/semaphore/semaphore.go:60 +0x345
github.com/cilium/cilium/pkg/lock.(*SemaphoredMutex).Lock(...)
	./pkg/lock/semaphored_mutex.go:30
github.com/cilium/cilium/pkg/ipcache.(*IPCache).Lock(...)
	./pkg/ipcache/ipcache.go:141
github.com/cilium/cilium/pkg/ipcache.(*IPCache).AllocateCIDRs(0xc000427b90, {0xc006aa4000, 0x2d, 0x18?}, {0x0, 0x0, 0x0?}, 0x0)
	./pkg/ipcache/cidr.go:56 +0x1b0
github.com/cilium/cilium/pkg/ipcache.(*IPCache).AllocateCIDRsForIPs(0x0?, {0xc006aa2000?, 0x8000101?, 0x0?}, 0xffffffffffffffff?)
	./pkg/ipcache/cidr.go:103 +0x51
github.com/cilium/cilium/daemon/cmd.cachingIdentityAllocator.AllocateCIDRsForIPs(...)
	./daemon/cmd/identity.go:114
github.com/cilium/cilium/pkg/policy.(*SelectorCache).allocateIdentityMappings(0xc00047dab0, {{0x0?, 0x0?}, {0xc000eeee00?, 0x19?}}, 0xa?)
	./pkg/policy/selectorcache.go:497 +0x295
github.com/cilium/cilium/pkg/policy.(*SelectorCache).AddFQDNSelector(0xc00047dab0, {0x385e680, 0xc0024c6630}, {{0x0, 0x0}, {0xc000eeee00, 0x19}})
	./pkg/policy/selectorcache.go:831 +0x2de
github.com/cilium/cilium/pkg/policy.(*L4Filter).cacheFQDNSelector(...)
	./pkg/policy/l4.go:628
github.com/cilium/cilium/pkg/policy.(*L4Filter).cacheFQDNSelectors(0xc0024c6630, {0xc000f63600?, 0x4, 0xc006339bd0?}, 0x9?)
	./pkg/policy/l4.go:623 +0x8d
github.com/cilium/cilium/pkg/policy.createL4Filter({0x38a2cb8, 0xc0003c2a00}, {0xc0003c3520?, 0x1, 0x1}, 0x0, {0x387a500, 0xc000d659f0}, {{0xc0007900cb, 0x3}, ...}, ...)
	./pkg/policy/l4.go:725 +0x3da
github.com/cilium/cilium/pkg/policy.createL4EgressFilter(...)
	./pkg/policy/l4.go:879
github.com/cilium/cilium/pkg/policy.mergeEgressPortProto({0x38a2cb8, 0xc0003c2a00}, 0x38a2cb8?, {0xc0003c3520?, 0x3?, 0xc002d9aa80?}, 0xc000790168?, {0x387a500?, 0xc000d659f0?}, {{0xc0007900cb, ...}, ...}, ...)
	./pkg/policy/rule.go:717 +0x10b
github.com/cilium/cilium/pkg/policy.mergeEgress.func1({0x387a500, 0xc000d659f0})
	./pkg/policy/rule.go:654 +0x405
github.com/cilium/cilium/pkg/policy/api.PortRules.Iterate({0xc000d659f0, 0x1, 0x3157640?}, 0xc00634fea0)
	./pkg/policy/api/l4.go:279 +0x65
github.com/cilium/cilium/pkg/policy.mergeEgress({0x38a2cb8, 0xc0003c2a00}, 0xc00634f570, {0xc0003c3520, 0x1, 0x1}, 0x0, {0x3881d28, 0xc006a8fce0}, {0x3881cd8, ...}, ...)
	./pkg/policy/rule.go:624 +0x4cf
github.com/cilium/cilium/pkg/policy.(*rule).resolveEgressPolicy(0xc001497450, {0x38a2cb8, 0xc0003c2a00}, 0xc00634f570, 0xc006a9bd80, 0xc0063614a0, {0x0, 0x0, 0x0}, {0x0, ...})
	./pkg/policy/rule.go:753 +0x85c
github.com/cilium/cilium/pkg/policy.ruleSlice.resolveL4EgressPolicy({0xc003518598, 0x1, 0x656e726562756b2e?}, {0x38a2cb8, 0xc0003c2a00}, 0xc00634f570)
	./pkg/policy/rules.go:103 +0x467
github.com/cilium/cilium/pkg/policy.(*Repository).resolvePolicyLocked(0xc00047db20, 0xc001334540)
	./pkg/policy/repository.go:718 +0x48a
github.com/cilium/cilium/pkg/policy.(*PolicyCache).updateSelectorPolicy(0xc000702c78, 0xc001334540)
	./pkg/policy/distillery.go:119 +0x14c
github.com/cilium/cilium/pkg/policy.(*PolicyCache).UpdatePolicy(...)
	./pkg/policy/distillery.go:153
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc0012f1180)
	./pkg/endpoint/policy.go:219 +0x245
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc0012f1180, 0xc003aa4800, 0xc0063608a0)
	./pkg/endpoint/bpf.go:845 +0x325
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc0012f1180, 0xc003aa4800)
	./pkg/endpoint/bpf.go:609 +0x1a5
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc0012f1180, 0xc003aa4800)
	./pkg/endpoint/policy.go:387 +0x7a6
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc0064573e0, 0x2d9bea0?)
	./pkg/endpoint/events.go:53 +0x325
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
	./pkg/eventqueue/eventqueue.go:245 +0x142
sync.(*Once).doSlow(0x7461656274726165?, 0x443f25?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0x6d69546e6f697461?)
	./pkg/eventqueue/eventqueue.go:233 +0x45
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
	./pkg/eventqueue/eventqueue.go:229 +0x76
```

### Relevant log output

The following log lines are not directly indicative of this specific issue, but are commong loglines we see when dealing with a deadlock involving the ipcache and/or an endpoint.

```shell
2023-06-13T08:05:23.500714779Z level=error msg="Timed out waiting for datapath updates of FQDN IP information; returning response" subsys=daemon
...
2023-06-14T02:52:27.830848410Z level=warning msg="Timeout waiting for response to forwarded proxied DNS lookup" DNSRequestID=1819 dnsName=kubernetes.default.svc.cluster.local. endpointID=3314 error="read udp 10.129.164.100:36045->10.129.161.165:53: i/o timeout" identity=23608 ipAddr="10.129.167.58:43160" subsys=fqdn/dnsproxy
...

sysdump collection:
⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-4nnvh": reading file in tar archive: /tmp/2547443837/cilium-sysdump-20230614-154352/cilium-bugtool-cilium-4nnvh-20230614-154352/cmd/state/413/template.o: writing file: unexpected EOF
⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-8h7lp": reading file in tar archive: /tmp/2547443837/cilium-sysdump-20230614-154352/cilium-bugtool-cilium-8h7lp-20230614-154352/cmd/state/511/template.o: writing file: unexpected EOF
⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-jb2fw": reading file in tar archive: /tmp/2547443837/cilium-sysdump-20230614-154352/cilium-bugtool-cilium-jb2fw-20230614-154352/cmd/cat--proc-kallsyms.md: writing file: unexpected EOF
⚠️ Failed to unarchive 'cilium-bugtool' output for "cilium-4pcqv": reading file in tar archive: /tmp/2547443837/cilium-sysdump-20230614-154352/cilium-bugtool-cilium-4pcqv-20230614-154352/cmd/state/2018/bpf_lxc.o: writing file: unexpected EOF
```

### Anything else?

The current hypothesis is that this can occur when there are overlapping `toFQDN` policies, i.e. `[matchPattern: foo.com]` and `[machPattern: foo.com, matchPattern: bar.com]`

The offending locking in IPCache appears to have been introduced to fix a race condition: https://github.com/cilium/cilium/commit/40e13ea2a5a944a45761fc433c4c971536957f4b is the commit in question, part of https://github.com/cilium/cilium/pull/20721.

Since that PR was backported, it's possible that 1.12 is also affected, though this is not yet confirmed.

A potential avenue for solving this is https://github.com/cilium/cilium/pull/26242, though it's unclear whether we can risk backporting those changes.

Co-investigated with @gandro.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
It looks like https://github.com/cilium/cilium/pull/26242 should solve this issue. I think the key question would just be around how we roll that patch out incrementally to gain confidence in it, particularly if we think that approach will be the way to resolve this issue on older releases. One other minor nit which is that it makes use of generic atomic pointers, so that might cause some backport headaches for older releases (I forget exactly when we introduced generics).

**Comment by spudlymurf** [comment]
@joestringer We're significantly affected by this and would be happy to do pretty much anything to get it to a resolution including running patches or whatever might be needed. We're at a point where we don't have much to lose in clusters that are affected.

**Comment by joestringer** [comment]
@spudlymurf thanks for the offer! I've just merged what I think is a reasonable solution to this problem in https://github.com/cilium/cilium/pull/26242 . If you're able to pull that and apply it on your release branch and provide feedback whether it addresses your issue or not, that could be helpful. So far we haven't (yet) evaluated backporting the PR to older releases.

**Comment by spudlymurf** [comment]
@joestringer Could we possibly get a dev build of that fix on v1.13.3?

**Comment by squeed** [comment]
@spudlymurf that's a good idea. I'll look in to building a test image. FQDN policies are the perfect stress-test case.

**Comment by squeed** [comment]
I provided a proposed backport of https://github.com/cilium/cilium/pull/26242# to v1.13 and the reporter indicated a [significant improvement](https://cilium.slack.com/archives/C1MATJ5U5/p1688962799888459?thread_ts=1683875356.505479&cid=C1MATJ5U5).

**Comment by joestringer** [comment]
Fixed via https://github.com/cilium/cilium/pull/26242 / https://github.com/cilium/cilium/pull/26735 , to be incluned in Cilium v1.13.6.
