### ISSUE TITLE
Remove UpdateSecLabels from Owner

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2629]
Feedback on #2315 was fairly strong about whether `UpdateSecLabels()` belongs as part of `Owner`.

https://github.com/cilium/cilium/blob/c9cc88db3b3c864d155e047def0f12e8640b5e6e/pkg/endpoint/owner.go#L90-L97

>      @raybejjani 
>I'm on the fence about this, mostly because UpdateSecLabels (and the various Daemon methods it calls) doesn't seem relevant to the owner of an endpoint. In particular, it seems like this function should be on the endpoint itself but that's a non-trivial refactor from what I can tell :/
>
>      @joestringer
>I agree, but also this PR was getting big enough as it is that I didn't really want to try to tackle this at this stage.
>
>      @aanm
>@joestringer Right, but I also don't understand why is this in the owner.go?
>
>      @joestringer
>@aanm Mostly just because Identity management is all in the daemon currently, and the caller isn't in the daemon package so it needs to deal with the abstract class "Owner" rather than knowing the internal details of the daemon. If we refactoring all of the daemon DeleteIdentity(), updateEndpointIdentity(), etc. stuff out of daemon, then it wouldn't need to be here. We can do that in a follow up PR.

This issue tracks the request to refactor this functionality out of `daemon/`.

**Comment by tgraf** [comment]
#2613 will do this already
