### ISSUE TITLE
The tcp packet was dropped because cksum incorrect

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#26300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/cilium/cilium/assets/6076617/6b49cfdc-7b8b-452b-8af3-b044caf13d36)

cilium  status err
<img width="725" alt="image" src="https://github.com/cilium/cilium/assets/6076617/f27e09d8-8fd9-47e3-be93-518103175b7c">

Compared with the cilium in the normal environment, it may be caused by tcp cksum incorrect

### Cilium Version

<img width="726" alt="image" src="https://github.com/cilium/cilium/assets/6076617/602e2006-9fc4-4b7f-80ee-320a4ac41f61">

### Kernel Version

4.19.113-300.el7.x86_64

### Kubernetes Version

1.18.17

### Sysdump

[Uploading cilium-sysdump-20230617-011948.zip…]()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
for this test, did you disable all the nic checksum offloading capabilities via ethtool?

**Comment by llhhbc** [comment]
It has nothing to do with the network card. The data packet has been received. The cilium monitor can capture the log of the received packet, but there is no reply packet. The packet is rejected by the kernel. It is guessed that it may be caused by the failure of the kernel chksum

**Comment by llhhbc** [comment]
@joestringer

**Comment by joestringer** [comment]
Kernel checksum handling is highly dependent on hardware checksum offload capabilities, which is why we're interested to understand whether adjusting those settings has an impact on this bug. It would help us to help you if we can establish whether that plays a role in this bug.

**Comment by llhhbc** [comment]
Ok, I will turn off the relevant checks on the network interface for testing

**Comment by YakovMyagkov** [comment]
I had a similar problem on the entire RHEL OS family, in vxlan mode.  When requesting cilium-health status, I saw that the agnet endpoint on the other node was not available and a timeout message.  When disconnected via ethtool -K eth0 rx off tx off, vxlan between nodes began to work fully

**Comment by YakovMyagkov** [comment]
I also tested in Ubuntu, but in Ubuntu by default, rx-checksum is disabled. I tried to turn on rx-checksum, but it did not affect the work of vxlan in any way. My suggestion is that RHEL-like OS have some kind of feature in the kernel configuration that leads to this problem.

**Comment by YakovMyagkov** [comment]
It may be worth adding an operating system check to the silium agent, and if it is RHEL-like OS, then you should disable rx-checksum on the network interface? 
Below in the screenshots:
1)Checksum verification is disabled
2)Checksum check is enabled
3)Composition of the test bench(RHEL 8.7)
![image](https://github.com/cilium/cilium/assets/90950462/980bd9d0-a58e-403d-9036-a2d887c06840)
![image](https://github.com/cilium/cilium/assets/90950462/3b5df657-9c72-4053-8b5d-c50ebb5d9f1b)
![tg_image_2817479838](https://github.com/cilium/cilium/assets/90950462/cd10aa73-6545-418a-a05f-c91f147f576a)

**Comment by joestringer** [comment]
This seems like an upstream bug in the kernel. I suggest filing a bug with your distribution regarding this issue.

**Comment by orientlu** [comment]
Does anyone know how to solve it?

**Comment by YakovMyagkov** [comment]
> Does anyone know how to solve it?

ethtool -K <name_your_interface> rx off tx off

**Comment by monotok** [comment]
I solved it by:

`ethtool --offload cilium_vxlan tx-checksum-ip-generic off`
