### ISSUE TITLE
CFP: add support for Nomad KV store

### ISSUE THREAD

**Issue by maxadamo** [cilium/cilium#26330]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

The main issue stems from the deprecation notice announced in this merge: https://github.com/cilium/cilium/pull/17993

Contrary to beliefs, Cilium is being utilized with Consul to execute the CNI on Nomad, and there is an ongoing project, Netreap, dedicated to making Cilium compatible with Nomad. You can find more information about it here: https://github.com/cosmonic/netreap 

Hence the idea is to enhance the support for Hashicorp products, specifically by integrating the Nomad key-value (KV) store.

**Describe the feature you'd like**

The developers of Netreap have plans to integrate the Nomad KV store, which operates similarly to the Consul KV store. Utilizing the Nomad KV store will be a natural choice, and it offers slightly better efficiency as it runs on the loopback address (whilst the Consul agent, will have to query the consul server)

**Describe your proposed solution**

Ultimately Consul is a very popular tool, and as of version 1.4 of Nomad, Hashicorp added KV store to Nomad: 
https://www.hashicorp.com/blog/nomad-1-4-adds-nomad-variables-and-updates-service-discovery

Ideally Cilium will support this KV store as well as Consul and Etcd

**Comment by joestringer** [comment]
Given that the Consul community have recently expressed interest in helping to maintain the Consul support, we have held back on removing that support in Cilium. I think that if we have community members who are interested in maintaining Consul support, Nomad support, etc. then there is a reasonable argument for including such support in Cilium and building out the internal abstractions to ensure that each of these kvstores retains a common featureset. That said, it's all subject to reviewing the actual details of any such proposal and whether the underlying kvstores have all of the same primitives that Cilium needs in order to be able to consistently propagate state.

**Comment by joestringer** [comment]
Latest status I'm aware of here:
- [Netreap](https://github.com/cosmonic/netreap) are developing in this space, primarily by creating an alternative to `cilium-operator` that removes k8s dependencies and adds Nomad-backed clusterwide operations. There may be some options to integrate some of that logic into Cilium, but I am not currently aware of any efforts to explore this direction.
- Hashicorp have [made licensing changes for some products](https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license) and I am not sure what the implications may be on this issue.

**Comment by maxadamo** [comment]
> * Hashicorp have [made licensing changes for some products](https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license) and I am not sure what the implications may be on this issue.

@joestringer I was fully aware. It's gonna be the same license used by MongoDB, Confluent, Redis Labs, as well as other products: https://opencoreventures.com/blog/2023-08-23-hashicorp-switching-bsl-shows-need-for-open-charter-companies/

I see that an Enterprise version of Cilium exists. Is NetReap or Cilium making a competitive offer using one of the Hashicorp tools, for instance, like as TerraGrunt, CloudBold, Camptocamp.... ?

**Comment by joestringer** [comment]
I have no specific knowledge of licensing impact other than that the CNCF is investigating the impact on projects under the foundation. For individual enterprise editions, those vendors are welcome to post an update here or otherwise you can reach out directly to the vendor.
