### ISSUE TITLE
The DSR section in kubeproxy-free.rst may need to be updated

### ISSUE THREAD

**Issue by spacewander** [cilium/cilium#26339]
Under the https://github.com/cilium/cilium/blob/main/Documentation/network/kubernetes/kubeproxy-free.rst#direct-server-return-dsr section, the doc claims that "DSR currently requires Cilium to be deployed in [:ref:`arch_direct_routing`](https://github.com/cilium/cilium/blob/main/Documentation/network/kubernetes/kubeproxy-free.rst#id7), i.e. it will not work in either tunneling mode."

However, [the section after it](https://github.com/cilium/cilium/blob/main/Documentation/network/kubernetes/kubeproxy-free.rst#direct-server-return-dsr-with-geneve) claims that the DSR mode can work with tunnel protocol geneve.

Look like we need to update the former one?

**Comment by borkmann** [comment]
Cc @julianwiedmann This indeed needs an update. Thanks for spotting!

**Comment by julianwiedmann** [comment]
Thank you @spacewander ! Please give https://github.com/cilium/cilium/pull/26582 a look.
