### ISSUE TITLE
No valid cgroup base path found

### ISSUE THREAD

**Issue by kkoppel** [cilium/cilium#26368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am deploying Cilium on a Talos Linux v1.4.4 based cluster in kube-proxy free mode as follows:
```
$ helm install cilium cilium/cilium \
  --version 1.13.4 \
  --namespace kube-system \
  --set ipam.mode=kubernetes \
  --set=kubeProxyReplacement=strict \
  --set=tunnel="disabled" \
  --set=ipv4NativeRoutingCIDR="10.0.0.0/16"
  --set=securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
  --set=securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
  --set=cgroup.autoMount.enabled=false \
  --set=cgroup.hostRoot=/sys/fs/cgroup \
  --set=k8sServiceHost="10.0.0.10" \
  --set=k8sServicePort="6443"
```

The cgroup related settings come from the Talos Linux docs (https://www.talos.dev/v1.4/kubernetes-guides/network/deploying-cilium/#method-1-helm-install) and are mentioned also here: https://github.com/cilium/cilium/issues/21603#issuecomment-1453753820

The Cilium agent on all cluster nodes logs this warning during startup:
```
No valid cgroup base path found: socket load-balancing tracing with Hubble will not work.See the kubeproxy-free guide for more details.
```

According to https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#observability this should not happen and should be reported.

I do not have the ability to run crictl, but here's what I can see inside one of the Cilium agent pods:
```
$ kubectl -n kube-system exec cilium-xcrpf -c cilium-agent -- find /sys/fs/cgroup/ -name pod*
/sys/fs/cgroup/kubepods/burstable/pod223e8377-dea2-4501-9eb2-224364fb45b7
/sys/fs/cgroup/kubepods/burstable/podeb41e277-d0b7-4b8d-a0d7-52c7afdff139
/sys/fs/cgroup/kubepods/burstable/pod4b5cbcf8-c8fe-4402-9c95-3b456078ecb2
/sys/fs/cgroup/kubepods/burstable/pod474a5505-f9eb-45be-af7c-b8f6afb78fa5
/sys/fs/cgroup/kubepods/besteffort/pod0ff1de47-b7e1-4693-adcd-3f0b48b297b6
/sys/fs/cgroup/podruntime
```

I would be happy to provide any additional information.

### Cilium Version

cilium-cli: v0.14.7 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.3
cilium image (stable): v1.13.4
cilium image (running): v1.13.4

### Kernel Version

v6.1.28

### Kubernetes Version

v1.27.1

### Sysdump

[cilium-sysdump-20230620-071311.zip](https://github.com/cilium/cilium/files/11797239/cilium-sysdump-20230620-071311.zip)

### Relevant log output

```shell
level=warning msg="No valid cgroup base path found: socket load-balancing tracing with Hubble will not work.See the kubeproxy-free guide for more details." subsys=cgroup-manager
```

### Anything else?

The same issue was present on Cilium v1.13.3.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
Cc @aditighag
