### ISSUE TITLE
how to check UnmanagedPodRestarter is on/working?

### ISSUE THREAD

**Issue by Guitarkalle** [cilium/cilium#26388]
Hi,

I installed Cilium CNI (1.13.4) chained with VPC-CNI on an EKS cluster using helm recently. This cluster is running pods already, so I need to restart all existing pods to have them managed by Cilium. When looking at the helm chart values it seems like there is a watcher in the operator that automatically can restart unmanaged pods. This however does not seem to work for me, I cannot find anything in the logs of the operator regarding this watcher and it didn't restart any pods.

Anyone have any ideas how to troubleshoot and get it working?

**Comment by ti-mo** [comment]
@Guitarkalle https://docs.cilium.io/en/stable/installation/k8s-install-helm/#restart-unmanaged-pods

As far as I understand, the operator won't start shooting down random unmanaged pods in your cluster, iirc this is only for kube-dns and potentially other Pods deployed along with Cilium's Helm chart.

**Comment by Guitarkalle** [comment]
Ah I see, thank you! I must have misunderstood

**Comment by Guitarkalle** [comment]
Although the name of the value in the helm chart is very misleading now that I look at it :) Is it just misleading naming?

https://docs.cilium.io/en/stable/helm-reference/
operator.unmanagedPodWatcher.restart
Restart any pod that are not managed by Cilium.

**Comment by ti-mo** [comment]
True, hadn't noticed this killing other pods before. Anyway, here's where it's implemented: https://github.com/cilium/cilium/blob/5da5882754569e118e713532b89dc4ca89ab76fd/operator/cmd/k8s_pod_controller.go#L46. Looking at the code, I don't see it filter based on pod name anywhere. Looks like Pods in the host netns don't get restarted though, same for Pods younger than 30s.

Make sure you haven't accidentally set `operator.unmanagedPodWatcher.intervalSeconds` to zero, or the watcher will be disabled.

Turning on debug logging for the operator should yield at least a bit of feedback.

**Comment by Guitarkalle** [comment]
here seems to be the answer:
https://github.com/cilium/cilium/blob/755eae8377fc4c353337af31be5d502c333b9f3c/operator/option/config.go#L336

So maybe a bit badly documented? Or maybe I missed it somewhere

**Comment by chancez** [comment]
Yeah you should be able to configure it via the helm options like this:
```
operator:
  extraArgs:
    - '--pod-restart-selector=foo=bar,fizz=buzz'
```
