### ISSUE TITLE
cilium monitor and hubble not reporting correctly IPv6 TCP traffic

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#26418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There seems to be a regression in main which causes both `cilium monitor` and `hubble observe` to not correctly report IPv6 TCP traffic. In particular, they only show the initial handshake, while everything works properly for IPv4. I managed to bisect it to the following commits (v1.13 is not affected):

Good: https://github.com/cilium/cilium/commit/b6c4e57af215d43013bb9201e25f6aa25a4d654f
```
$ hubble observe --pod <pod-name> -f --numeric

10.244.1.69:54934 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: SYN)
10.244.1.69:54934 (ID:14364) <- 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
10.244.1.69:54934 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK)
10.244.1.69:54934 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
10.244.1.69:54934 (ID:14364) <- 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
10.244.1.69:54934 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
10.244.1.69:54934 (ID:14364) <- 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
10.244.1.69:54934 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK)

[fd00:10:244:1::27b3]:38494 (ID:14364) -> [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: SYN)
[fd00:10:244:1::27b3]:38494 (ID:14364) <- [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
[fd00:10:244:1::27b3]:38494 (ID:14364) -> [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK)
[fd00:10:244:1::27b3]:38494 (ID:14364) -> [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
[fd00:10:244:1::27b3]:38494 (ID:14364) <- [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
[fd00:10:244:1::27b3]:38494 (ID:14364) -> [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
[fd00:10:244:1::27b3]:38494 (ID:14364) <- [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
[fd00:10:244:1::27b3]:38494 (ID:14364) -> [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK)
```

Bad: https://github.com/cilium/cilium/commit/eee902f44979f9c4336179ef061845453743842f

```
$ hubble observe --pod <pod-name> -f --numeric

10.244.1.69:33028 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: SYN)
10.244.1.69:33028 (ID:14364) <- 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
10.244.1.69:33028 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK)
10.244.1.69:33028 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
10.244.1.69:33028 (ID:14364) <- 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
10.244.1.69:33028 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
10.244.1.69:33028 (ID:14364) <- 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
10.244.1.69:33028 (ID:14364) -> 10.244.1.171:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK)

[fd00:10:244:1::27b3]:45126 (ID:14364) -> [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: SYN)
[fd00:10:244:1::27b3]:45126 (ID:14364) <- [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
[fd00:10:244:1::27b3]:45126 (ID:14364) -> [fd00:10:244:1::ae21]:9898 (ID:1606) to-endpoint FORWARDED (TCP Flags: ACK)
```

### Cilium Version

```
level=info msg="     _ _ _" subsys=daemon
level=info msg=" ___|_| |_|_ _ _____" subsys=daemon
level=info msg="|  _| | | | | |     |" subsys=daemon
level=info msg="|___|_|_|_|___|_|_|_|" subsys=daemon
level=info msg="Cilium 1.13.90 eee902f44979 2023-01-04T10:11:14+02:00 go version go1.19.5 linux/amd64" subsys=daemon
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
@giorio94 are you saying that the parent commit of https://github.com/cilium/cilium/commit/eee902f44979f9c4336179ef061845453743842f the monitor still works, or is it rather somewhere in https://github.com/cilium/cilium/pull/22936 where the bisection breaks?

**Comment by giorio94** [comment]
> @giorio94 are you saying that the parent commit of [eee902f](https://github.com/cilium/cilium/commit/eee902f44979f9c4336179ef061845453743842f) the monitor still works, or is it rather somewhere in #22936 where the bisection breaks?

Yes, the monitor works fine with the parent commit, while it breaks in https://github.com/cilium/cilium/commit/eee902f44979f9c4336179ef061845453743842f.

**Comment by borkmann** [comment]
(Also marking as blocker for 1.13 given https://github.com/cilium/cilium/pull/22936 was backported.)

**Comment by borkmann** [comment]
Do you happen to have BIG TCP for IPv6 in your config enabled where we'd insert an extension header locally? Iow, the pkts would look different header wise for control vs data packets? I looked at the commit, at least nothing obvious stands out. Cc @julianwiedmann

**Comment by giorio94** [comment]
> (Also marking as blocker for 1.13 given #22936 was backported.)

🤔, this is weird. Yesterday I couldn't reproduce the issue on the latest v1.13

**Comment by giorio94** [comment]
> Do you happen to have BIG TCP for IPv6 in your config enabled where we'd insert an extension header locally (cilium status)? Iow, the pkts would look different header wise for control vs data packets?

Sorry, I forgot to mention the config, which was a pretty basic one. The tests were executed on a two node cluster with dual IP family, and cilium installed with (images build from the respective commits and loaded on kind):

```
cilium install \
  --helm-set=ipv6.enabled=true \
  --chart-directory install/kubernetes/cilium \
  --helm-set image.override=localhost:5000/cilium/cilium-dev:local \
  --helm-set image.pullPolicy=Never --helm-set operator.image.pullPolicy=Never \
  --helm-set operator.image.override=localhost:5000/cilium/operator-generic:local
```

I also recreated the cluster between the two tests to prevent interference.

**Comment by julianwiedmann** [comment]
:facepalm: thanks for spotting Marco, fix inbound via https://github.com/cilium/cilium/pull/26476.
