### ISSUE TITLE
Gateway API Gateway create causes cilium pod  crashbackoff

### ISSUE THREAD

**Issue by ksully-execute** [cilium/cilium#26424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running Cilium V1.13.3 on ubuntu on-prem with metallb, openebs. 3 nodes (1 controller, 2 workers)
All stable, with hubble, gatewayapi, strict proxy all enabled, started with:
`cilium install  --kube-proxy-replacement=strict --encryption "wireguard" --node-encryption  --restart-unmanaged-pods --wait-duration  "5m" --helm-set gatewayAPI.enabled=true,operator.replicas=1,hubble.relay.enabled=true,hubble.metrics.enabled="{dns,drop:sourceContext=pod;destinationContext=pod,tcp,flow,port-distribution,httpV2}",hubble.ui.enabled=true,kubeProxyReplacement=strict,enable-l7-proxy=true
`
Following the http example: https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/http/

GatewayClass added, no issue.
The moment I create the gateway, the cilium pods crash (log file attached and sysdump)
If I remove the gateway, the pods don't recover (in CrashBackOff), but do start fine if I rollout restart them
Was asked to open this by Daniel Borkman via slack.

### Cilium Version

v1.13.3

### Kernel Version

5.19.0-45-generic #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230622-154653.zip](https://github.com/cilium/cilium/files/11839673/cilium-sysdump-20230622-154653.zip)

### Relevant log output

```shell
see attached log file
```

### Anything else?

[kube-system-cilium-4dbxq-1687462377760649229.log](https://github.com/cilium/cilium/files/11839693/kube-system-cilium-4dbxq-1687462377760649229.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ksully-execute** [comment]
note that if i start cilium with the minimal needed:
cilium install     --kube-proxy-replacement=strict     --helm-set gatewayAPI.enabled=true

everything works ok, so must be one of the other capabilities I enabled (see install command in description)

**Comment by borkmann** [comment]
@sayboras Hey Tam 👋 do you have a chance to take a look? Thanks!

**Comment by ksully-execute** [comment]
tried with less stuff
cilium install  --kube-proxy-replacement=strict  --wait-duration  "5m" --helm-set gatewayAPI.enabled=true,hubble.ui.enabled=true,hubble.relay.enabled=true,enable-l7-proxy=true

and it worked fine, so it must be related to the things left: 
 --encryption "wireguard" --node-encryption  --restart-unmanaged-pods --wait-duration  "5m" --helm-set operator.replicas=1

**Comment by sayboras** [comment]
:wave: 

As per attached sysdump, the flag `enable-l7-proxy` is set as false, so it will cause panic when Gateway API is enabled.

I also notice that in your installation command, the part `enable-l7-proxy=true` seems to be invalid, the correct option will be `l7Proxy=true` instead.

Just a note in v1.13.4, we have a helm validation to make sure that such discrepancy is highlighted earlier as part of the installation itself. https://github.com/cilium/cilium/pull/25570 

Agent log in sysdump.

```
...
2023-06-22T15:42:32.578782927-04:00 level=info msg="  --enable-l2-neigh-discovery='true'" subsys=daemon
2023-06-22T15:42:32.578788412-04:00 level=info msg="  --enable-l7-proxy='false'" subsys=daemon
...
```

**Comment by ksully-execute** [comment]
Excellent, thanks!

**Comment by ksully-execute** [comment]
When I fix the parameter for l7proxy, I get a conflict as shown below. Is this expected, that encryption with wireguard isn't supported with l7 proxy on?

```
 Using Cilium version 1.13.3
🔮 Auto-detected cluster name: kubernetes
ℹ️  L7 proxy disabled due to Wireguard encryption
⚠️️  Wireguard does not support node encryption yet
🔮
```

**Comment by sayboras** [comment]
I think it's expected for 1.13.x release, can you try with the recent snapshot release v1.14.x ?

**Comment by ksully-execute** [comment]
will do, but can't till early next week, so will close the case since the main topic is dealt with
