### ISSUE TITLE
update outdated installation docs

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#26430]
let's use this issue to track outdated documentation pages so that we can update them for v1.14 release ✨ 

- [x] cluster mesh: https://docs.cilium.io/en/latest/network/clustermesh/clustermesh/#gs-clustermesh let's document both helm-based and cilium-cli based instructions.
- [x] external workloads: https://docs.cilium.io/en/latest/network/external-workloads/#external-workloads document newly added helm values: https://github.com/cilium/cilium/pull/26607
- [x] cilium-cli: this is an open question, but i'd like to release cilium-cli v0.15 and update cilium v1.14 docs to consistently use Helm mode. otherwise we need to support the classic mode for another 6 monthds. cc @tklauser @asauber what do you think: https://github.com/cilium/cilium/pull/26606
- [x] openshift: https://docs.cilium.io/en/latest/installation/k8s-install-openshift-okd/#k8s-install-openshift-okd refers to https://github.com/cilium/cilium-olm, which has been deprecated: will clarify this in https://github.com/cilium/cilium/issues/26536

anything else?

### additional pages to check
- [x] Documentation/gettingstarted/hubble.rst
- [x] Documentation/gettingstarted/k8s-install-default.rst
- [x] Documentation/helm-values.rst
- [x] Documentation/installation/k3s.rst
- [x] Documentation/installation/k8s-install-migration.rst
- [x] Documentation/network/clustermesh/aks-clustermesh-prep.rst
- [x] Documentation/network/clustermesh/clustermesh.rst
- [x] Documentation/network/external-workloads.rst
- [x] Documentation/network/servicemesh/gateway-api/installation.rst
- [x] Documentation/network/servicemesh/installation.rst
- [x] Documentation/network/servicemesh/tls-default-certificate.rst
- [x] Documentation/operations/performance/tuning.rst
- [x] Documentation/security/network/encryption-ipsec.rst
- [x] Documentation/security/network/encryption-wireguard.rst

**Comment by asauber** [comment]
I'm 100% onboard with Helm mode being the default documented CLI mode for 1.14.

For clarification, we would need to support classic mode for an additional 6 months otherwise, because the Helm-mode changes would not be an appropriate intra-minor-version change for 1.14?

**Comment by asauber** [comment]
cilium-cli: I do think that 0.15 should be the release marked as "maintained" for the 1.14 release, and that it should have Helm mode as the default. I have [this issue](https://github.com/cilium/cilium-cli/issues/1624) assigned to myself track that. I'll add a task for the initial pass to update existing `cilium-cli` references. I should be able to complete that within the next week or so.

**Comment by tklauser** [comment]
I agree that 0.15 should default to helm mode and be the supported cilium-cli release for Cilium v1.14.

> otherwise we need to support the classic mode for another 6 months

I think worst case we'd even have to support it until 1.14 is EoL which is when v1.16 releases - so 18 months. All the more reason to default to helm mode now.

**Comment by danehans** [comment]
xref https://github.com/cilium/cilium/issues/26531 to update the k8s requirements doc.

**Comment by nvibert** [comment]
We're seeing some reported issues from folks using Cilium CLI to install with `--azure-resource-group` as this is no longer supported in the new Azure CLI mode.

**Comment by joestringer** [comment]
IMO flags like `--azure-resource-group` should be retained in cilium-CLI and mapped into the Helm value in the new helm mode.

**Comment by michi-covalent** [comment]
you mean retain them so that we can deprecate them first and remove them later, or retain them and support them in the long term?

if the latter, i'm open to discussion in terms of what installation flags cilium-cli should provide. i think we need clear guidelines in terms of what types of settings should have a dedicated CLI flag vs Helm values 🎏

**Comment by michi-covalent** [comment]
i'll open a separate cilium-cli issue for improving the overall UX friendliness 🎏🎏🎏. closing this issue as completed ✅
