### ISSUE TITLE
Support for AKS BYOCNI On Azure Linux-Mariner

### ISSUE THREAD

**Issue by amitmavgupta** [cilium/cilium#26471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

This is more of a **documentation request** for adding support for AKS BYOCNI on [Azure Linux-Mariner](https://learn.microsoft.com/en-us/azure/aks/use-azure-linux)

++++++++++++Bringing up an AKS cluser with Azure Linux aka Mariner++++++++++++++++++

- az group create --name AzureLinuxTest --location eastus

- az aks create --name cluster1 --resource-group AzureLinuxTest --os-sku AzureLinux --generate-ssh-keys --network-plugin none

- az aks get-credentials --resource-group AzureLinuxTest --name cluster1

- kubectl get pods --all-namespaces

- cilium install --azure-resource-group AzureLinuxTest 

- kubectl get pods --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork --no-headers=true | grep '<none>' | awk '{print "-n "$1" "$2}' | xargs -L 1 -r kubectl delete pod

++++++++++++++++++++++Installing Cilium with AKS BYOCNI+++++++++++++++++++++++

amit@Amits-MacBook-Air ~ % cilium install --azure-resource-group AzureLinuxTest
🔮 Auto-detected Kubernetes kind: AKS
ℹ️  Using Cilium version 1.13.2
🔮 Auto-detected cluster name: cluster1
✅ Derived Azure subscription ID 8dbd2563-77eb-41a1-917b-5a1344da9767 from subscription cilium-demo
✅ Detected Azure AKS cluster in BYOCNI mode (no CNI plugin pre-installed)
🔮 Auto-detected datapath mode: aks-byocni
🔮 Auto-detected kube-proxy has been installed
⚠️ Unable to list kubernetes api resources, try --api-versions if needed: failed to list api resources: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
ℹ️  helm template --namespace kube-system cilium cilium/cilium --version 1.13.2 --set aksbyocni.enabled=true,azure.resourceGroup=AzureLinuxTest,cluster.id=0,cluster.name=cluster1,encryption.nodeEncryption=false,kubeProxyReplacement=disabled,nodeinit.enabled=true,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator
ℹ️  Storing helm values file in kube-system/cilium-cli-helm-values Secret
🔑 Created CA in secret cilium-ca
🔑 Generating certificates for Hubble...
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap for Cilium version 1.13.2...
🚀 Creating AKS Node Init DaemonSet...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed and ready...
✅ Cilium was successfully installed! Run 'cilium status' to view installation health

++++++++++++++++++++++Cilium Connectivity Tests+++++++++++++++++++++++

amit@Amits-MacBook-Air ~ % cilium connectivity test
ℹ️  Monitor aggregation detected, will skip some flow validation steps
✨ [cluster1] Creating namespace cilium-test for connectivity check...
✨ [cluster1] Deploying echo-same-node service...
✨ [cluster1] Deploying DNS test server configmap...
✨ [cluster1] Deploying same-node deployment...
✨ [cluster1] Deploying client deployment...
✨ [cluster1] Deploying client2 deployment...
✨ [cluster1] Deploying echo-other-node service...
✨ [cluster1] Deploying other-node deployment...
✨ [host-netns] Deploying cluster1 daemonset...
✨ [host-netns-non-cilium] Deploying cluster1 daemonset...
✨ [cluster1] Deploying echo-external-node deployment...
⌛ [cluster1] Waiting for deployments [client client2 echo-same-node] to become ready...
⌛ [cluster1] Waiting for deployments [echo-other-node] to become ready...
⌛ [cluster1] Waiting for CiliumEndpoint for pod cilium-test/client-7b78db77d5-kztfz to appear...
⌛ [cluster1] Waiting for CiliumEndpoint for pod cilium-test/client2-78f748dd67-fqrh6 to appear...
⌛ [cluster1] Waiting for pod cilium-test/client-7b78db77d5-kztfz to reach DNS server on cilium-test/echo-same-node-56445df7f5-p4r7c pod...
⌛ [cluster1] Waiting for pod cilium-test/client2-78f748dd67-fqrh6 to reach DNS server on cilium-test/echo-same-node-56445df7f5-p4r7c pod...
⌛ [cluster1] Waiting for pod cilium-test/client-7b78db77d5-kztfz to reach DNS server on cilium-test/echo-other-node-5b4c56d689-nsk7g pod...
⌛ [cluster1] Waiting for pod cilium-test/client2-78f748dd67-fqrh6 to reach DNS server on cilium-test/echo-other-node-5b4c56d689-nsk7g pod...
⌛ [cluster1] Waiting for pod cilium-test/client-7b78db77d5-kztfz to reach default/kubernetes service...
⌛ [cluster1] Waiting for pod cilium-test/client2-78f748dd67-fqrh6 to reach default/kubernetes service...
⌛ [cluster1] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-5b4c56d689-nsk7g to appear...
⌛ [cluster1] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-56445df7f5-p4r7c to appear...
⌛ [cluster1] Waiting for Service cilium-test/echo-other-node to become ready...
⌛ [cluster1] Waiting for Service cilium-test/echo-same-node to become ready...
⌛ [cluster1] Waiting for NodePort 10.224.0.4:30552 (cilium-test/echo-other-node) to become ready...
⌛ [cluster1] Waiting for NodePort 10.224.0.4:30919 (cilium-test/echo-same-node) to become ready...
⌛ [cluster1] Waiting for NodePort 10.224.0.6:30552 (cilium-test/echo-other-node) to become ready...
⌛ [cluster1] Waiting for NodePort 10.224.0.6:30919 (cilium-test/echo-same-node) to become ready...
⌛ [cluster1] Waiting for NodePort 10.224.0.5:30552 (cilium-test/echo-other-node) to become ready...
⌛ [cluster1] Waiting for NodePort 10.224.0.5:30919 (cilium-test/echo-same-node) to become ready...
ℹ️  Skipping IPCache check
🔭 Enabling Hubble telescope...
⚠️  Unable to contact Hubble Relay, disabling Hubble telescope and flow validation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:4245: connect: connection refused"
ℹ️  Expose Relay locally with:
   cilium hubble enable
   cilium hubble port-forward&
ℹ️  Cilium version: 1.13.2
🏃 Running tests...
[=] Test [no-policies]
..........................
[=] Test [no-policies-extra]
............
[=] Test [allow-all-except-world]
................
[=] Test [client-ingress]
..
[=] Test [client-ingress-knp]
..
[=] Test [allow-all-with-metrics-check]
....
[=] Test [all-ingress-deny]
........
[=] Test [all-ingress-deny-knp]
........
[=] Test [all-egress-deny]
................
[=] Test [all-egress-deny-knp]
................
[=] Test [all-entities-deny]
........
[=] Test [cluster-entity]
..
[=] Test [host-entity]
......
[=] Test [echo-ingress]
....
[=] Test [echo-ingress-knp]
....
[=] Test [client-ingress-icmp]
..
[=] Test [client-egress]
....
[=] Test [client-egress-knp]
....
[=] Test [client-egress-expression]
....
[=] Test [client-egress-expression-knp]
....
[=] Test [client-with-service-account-egress-to-echo]
....
[=] Test [client-egress-to-echo-service-account]
....
[=] Test [to-entities-world]
......
[=] Test [to-cidr-external]
....
[=] Test [to-cidr-external-knp]
....
[=] Test [echo-ingress-from-other-client-deny]
......
[=] Test [client-ingress-from-other-client-icmp-deny]
......
[=] Test [client-egress-to-echo-deny]
......
[=] Test [client-ingress-to-echo-named-port-deny]
....
[=] Test [client-egress-to-echo-expression-deny]
....
[=] Test [client-with-service-account-egress-to-echo-deny]
....
[=] Test [client-egress-to-echo-service-account-deny]
..
[=] Test [client-egress-to-cidr-deny]
....
[=] Test [client-egress-to-cidr-deny-default]
....
[=] Test [health]
...

[=] Skipping Test [north-south-loadbalancing]

[=] Skipping Test [pod-to-pod-encryption]

[=] Skipping Test [node-to-node-encryption]

[=] Skipping Test [egress-gateway]

[=] Skipping Test [north-south-loadbalancing-with-l7-policy]
[=] Test [echo-ingress-l7]
............
[=] Test [echo-ingress-l7-named-port]
............
[=] Test [client-egress-l7-method]
............
[=] Test [client-egress-l7]
..........
[=] Test [client-egress-l7-named-port]
..........

[=] Skipping Test [client-egress-l7-tls-deny-without-headers]

[=] Skipping Test [client-egress-l7-tls-headers]

[=] Skipping Test [client-egress-l7-set-header]

[=] Skipping Test [echo-ingress-auth-always-fail]

[=] Skipping Test [echo-ingress-auth-mtls-spiffe]

[=] Skipping Test [pod-to-ingress-service]

[=] Skipping Test [pod-to-ingress-service-deny-all]

[=] Skipping Test [pod-to-ingress-service-allow-ingress-identity]
[=] Test [dns-only]
..........
[=] Test [to-fqdns]
........

✅ All 42 tests (291 actions) successful, 13 tests skipped, 1 scenarios skipped.

### Cilium Version

1.13.2

### Kernel Version

root@aks-nodepool1-35189466-vmss000000 [ / ]# uname -a
Linux aks-nodepool1-35189466-vmss000000 5.15.107.1-2.cm2 #1 SMP Wed Apr 26 19:36:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

root@aks-nodepool1-35189466-vmss000000 [ / ]# uname -r
5.15.107.1-2.cm2

root@aks-nodepool1-35189466-vmss000000 [ / ]# cat /etc/lsb-release
DISTRIB_ID="Mariner"
DISTRIB_RELEASE="2.0.20230426"
DISTRIB_CODENAME=Mariner
DISTRIB_DESCRIPTION="CBL-Mariner 2.0.20230426"

### Kubernetes Version

1.25.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Is there anything particularly unusual about this platform that may motivate documenting specifics?

If this is a matter of documenting how to use the `aks` CLI to specify the OS that AKS will install, I think it's not the responsibility of the Cilium documentation to document this. We can update the system requirements to report that Cilium works with Mariner, but I don't think we should be trying to document install to every single OS out there.

**Comment by joestringer** [comment]
@tommyp1ckles @mathpl are you folks working on this? I don't see any activity since assignment in July.

**Comment by tommyp1ckles** [comment]
@joestringer @mathpl  I haven't had the time to work on this.

**Comment by amitmavgupta** [comment]
@joestringer The reason I had opened this ticket is because Mariner or AKS Linux Host will become the default very soon. I have a meeting with the Azure team later this week and can add more to this. If we would like this to be moved to the CEE docs that's also fine or the team can cover it via a blog. Happy to do it either way.

**Comment by amitmavgupta** [comment]
Agree @joestringer we can close this out.
