### ISSUE TITLE
`cilium cleanup` command is not backward compatible

### ISSUE THREAD

**Issue by sofat1989** [cilium/cilium#26472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Cilium version 1.12 is deployed
2. Upgrade the cilium version to 1.13. Before upgrading, in the init container, we want to clean all the state.
```
 cilium cleanup --all-state

Warning: Destructive operation. You are about to remove:
- tc filters
cilium_geneve [{LinkIndex: 8, Handle: 0:1, Parent: ffff:fff2, Priority: 1, Protocol: 3} {LinkIndex: 8, Handle: 0:1, Parent: ffff:fff3, Priority: 1, Protocol: 3}]

- links
&{{6 1500 1000 cilium_net 12:94:66:bf:68:67 up|broadcast|multicast 69827 7 0 <nil>  0xc0005d4e40 0 0 1 0xc0002a0b10 ether <nil> up 0 -1 32 32 65536 65535 0 [] 0 <nil>}   <nil>}
&{{7 1500 1000 cilium_host 5a:5b:ee:4b:a6:47 up|broadcast|multicast 69827 6 0 <nil>  0xc0005d4fc0 0 0 1 0xc0002a0b58 ether <nil> up 0 -1 32 32 65536 65535 0 [] 0 <nil>}   <nil>}
&{{8 1500 1000 cilium_geneve e2:81:3a:54:73:f1 up|broadcast|multicast 69699 0 0 <nil>  0xc0005d5140 0 0 1 0xc0002a0be8 ether <nil> unknown 0 -1 1 1 65536 65535 0 [] 0 <nil>} 0 <nil> 0 0 6081 0 0 0 0 false}
*
removed map cilium_call_policy
*
```
The bpf programs are left on the eth0 and container interfaces.
```
# bpftool net list
xdp:

tc:
eth0(2) clsact/ingress cilium-eth0 id 1016
eth0(2) clsact/egress cilium-eth0 id 1027
califf708979b3d(10) clsact/ingress cilium-califf708979b3d id 1036
califf708979b3d(10) clsact/egress cilium-califf708979b3d id 1041

flow_dissector:
```

The root cause may be here.

1.13 clean the bpf filter whose name contains `cil_`, but the 1.12 the bpf filter name is prefix with `cilium_`.
```
eth0(2) clsact/ingress cilium-eth0 id 1016
```

```
# cilium/cmd/cleanup.go

func getTCFilters(link netlink.Link) ([]*netlink.BpfFilter, error) {
	allFilters := []*netlink.BpfFilter{}
	*
					// Filters created by the Go bpf loader contain the bpf function and
					// interface name, like cil_from_netdev-eth0.
					strings.Contains(bpfFilter.Name, "cil_") {
					allFilters = append(allFilters, bpfFilter)
				}
```
1.12
```
func getTCFilters(link netlink.Link) ([]*netlink.BpfFilter, error) {
	allFilters := []*netlink.BpfFilter{}
	*
					strings.Contains(bpfFilter.Name, "cilium") { {
					allFilters = append(allFilters, bpfFilter)
				}
```

### Cilium Version

1.12
1.13

### Kernel Version

none

### Kubernetes Version

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@sofat1989 thank you for opening the GH issue. Would you like to submit a PR with the fix?

**Comment by joestringer** [comment]
> Upgrade the cilium version to 1.13. Before upgrading, in the init container, we want to clean all the state.

For what it's worth, this is outside of the expected upgrade path and is likely to cause some combination of packet drops for existing applications and potential network policy security bypass. The official upgrade guide is here and does not include this step: https://docs.cilium.io/en/stable/operations/upgrade/#admin-upgrade .

In general `cilium cleanup` is only available for worst case scenarios where you need to clear out state from nodes, because they're completely messed up or you're uninstalling Cilium. I see no reason to ever use it as part of the upgrade process.
