### ISSUE TITLE
CFP: Add support for multiple ingress envoys

### ISSUE THREAD

**Issue by farcaller** [cilium/cilium#26487]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

Oftentimes there's a need to serve different services for different audiences based on the external (to k8s) networking policies, e.g. serve internal only resources to the clients of a specific subnet. That's commonly solved by having a public ingress and a private ingress, the traffic to which is routed by different means.

**Describe the feature you'd like**

Allow deploying several envoys (when using a dedicated DaemonSet). Each envoy should bind to the specific ingress/gateway class. This is consistent in how nginx ingress and istio operate.

**(Optional) Describe your proposed solution**

Envoy configuration becomes namespaced, following the gatewayclass's name. For the first iteration, the helkm chart can be extended to support `envoy.extraDeployments` array where each element is a copy of `envoy.{ ... }` hierarchy. An additional field `gatewayClassName` is required, defaulting to `cilium` for the default one (as it is right now).

For a full support, `CiliumEnvoyConfig` would have to become targeted, too, allowing to match to the individual envoy instances.

**Comment by farcaller** [comment]
Still relevant.

**Comment by zetaab** [comment]
yeah, we have exactly same use-case. We are currently using two ingress classes in our clusters, public and internal. With cilium its not possible to do the same. We have two different subnets in our clusters and with annotation in kubernetes service object, we can decide which subnet is used. See: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#service-annotations `loadbalancer.openstack.org/floating-subnet`

**Comment by zetaab** [comment]
seems that same applies to new gateway api, cilium supports only one gateway which is called `cilium`. Perhaps worth of revisit and support multiple gateways like public and internal?

**Comment by Exeteres** [comment]
Still relevant!
I also need to organize two different ingress/gateway api classes - `public` and `private`.
Right now I'm using two independent Traefik installations for this, but it would be really nice to abandon them in favor of the Cilium.

**Comment by zviratko** [comment]
> Still relevant! I also need to organize two different ingress/gateway api classes - `public` and `private`. Right now I'm using two independent Traefik installations for this, but it would be really nice to abandon them in favor of the Cilium.

This issue is about Ingress, what you are asking is already possible using Gateway API.

Why is it still relevant for Ingress? Well, most Helm charts etc. support Ingress provisioning and not many of them support Gateway, so it's still useful (also more battle tested).

**Comment by Exeteres** [comment]
> > Still relevant! I also need to organize two different ingress/gateway api classes - `public` and `private`. Right now I'm using two independent Traefik installations for this, but it would be really nice to abandon them in favor of the Cilium.
> 
> This issue is about Ingress, what you are asking is already possible using Gateway API.
> 
> Why is it still relevant for Ingress? Well, most Helm charts etc. support Ingress provisioning and not many of them support Gateway, so it's still useful (also more battle tested).

It seemed to me that the author's comment also mentions the Gateway API.

In any case, I don't think the Gateway API by itself can solve this problem.
Suppose in the gateway specification we can specify the ports on which the envoy will expect requests for certain routes, but we can't specify the visibility of the service itself.

In other words, I want the envoy instance for public routes to be accessible via a service like NodePort or LoadBalancer, and the instance for private routes to be accessible via ClusterIP, so I can route traffic to it from something like WireGuard.

**Comment by pschichtel** [comment]
There is already the shared and dedicated modes which can be overridden per ingress/gateway. If there was an annotation to specify the loadbalancer IP, then mode=shared could just share the loadbalancer for those with the same IP. mode=dedicated could use the annotation to assign the IP.
