### ISSUE TITLE
IP/CIDR network policies do not apply to endpoints related to NodePort Service

### ISSUE THREAD

**Issue by yantingqiu** [cilium/cilium#26498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

According to the Cilium documentation

> CIDR policies are used to define policies to and from endpoints which are not managed by Cilium and thus do not have labels associated with them. These are typically **### external services, VMs or metal machines running in particular subnets**. CIDR policy can also be used to limit access to external services, for example to limit external access to a particular IP range. CIDR policies can be applied at ingress or egress.

When I use NodePort to expose my application, I want to restrict the traffic from outside the cluster. However, CIDR-based or world entities do not work. How can I restrict access to NodePort services from external services?

### Cilium Version

v1.13.2

### Kernel Version

4.18.0-372.9.1.15.po1.x86_64

### Kubernetes Version

1.27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
See also `loadBalancerSourceRanges `: https://docs.cilium.io/en/latest/network/kubernetes/kubeproxy-free/#loadbalancer-source-ranges-checks
