### ISSUE TITLE
Test upgrade between cilium versions

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2651]
We should add a test case to test the upgrade between a stable cilium version against a PR.

I think this test will only need to create a couple of endpoints with a couple options each, then it should stop cilium and restart it with the new cilium version.

Currently the restore functionality is being tested for the same version and not between different versions.

**Comment by tgraf** [comment]
We can do this as part of the nightly test, upgrade from the previous version.

**Comment by eloycoto** [comment]
Hi, 

Issue fixed by PR https://github.com/cilium/cilium/pull/2899
