### ISSUE TITLE
Missing `services_events_total` metric

### ISSUE THREAD

**Issue by whites11** [cilium/cilium#26511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I deployed cilium 1.13.4 on kubernetes.
I am scraping both the operator and the agents with prometheus.
I deployed the default grafana dashboard.

I don't have data for one chart, turns out the `cilium_services_events_total` is not exposed by either components.

Looking at the code it looks like the metric should always be exposed

### Cilium Version

1.13.4

### Kernel Version

5.15.111-flatcar

### Kubernetes Version

v1.24.15

### Relevant log output

```shell
# curl -s localhost:9962/metrics|grep services_events_total
#
```

```
# curl -s localhost:9963/metrics|grep services_events_total
#
```
```


### Anything else?

it's not about the metric being without data, the description is not there in the exporter outputs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ldelossa** [comment]
@whites11 can you please provide a sysdump  when you're experiencing this issue.

**Comment by whites11** [comment]
unfortunately, sysdump is too big for github.
you can download it from here for https://drive.google.com/file/d/1dEnnqBT2zRzhXacYMzcpkwTdY04dk5mb/view?usp=sharing for 24h

**Comment by christarazi** [comment]
I tested latest Cilium v1.12 and v1.11. Both of them also are missing the metric. Seems like this has been a bug for a long time.
