### ISSUE TITLE
External endpoint cannot be accessed through NodePort

### ISSUE THREAD

**Issue by zghyy** [cilium/cilium#26519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I added an external Endpoint to a Service, and this endpoint is an external host. I can't access normally through NodePort。
First, I created two Nginx Pods and a Service in NodePort mode.
<img width="842" alt="image" src="https://github.com/cilium/cilium/assets/45261749/2b0a1c2a-66da-4df0-a651-4f52f2575066">
Next I created a new EndpointSlice and added an external host to this new resource
```yaml
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.120.16.3
 # conditions:
#    ready: true
#  nodeName: 10.10.101.164-master
#  targetRef:
#    kind: Pod
#    name: nginx-route-5cb78b69ff-vt8ds
#    namespace: default
#    resourceVersion: "1895730"
#    uid: 7daabd21-ea5c-42a3-a95f-b72ed6e26050
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-06-19T03:26:32Z"
  creationTimestamp: "2023-06-05T04:51:20Z"
  generateName: nginx-route-
  generation: 11
  labels:
 #   endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: nginx-route
  name: nginx-route-2abcd
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: nginx-route
    uid: ab4de192-3bb5-4f7d-b4c0-006964d5b348
ports:
- name: web
  port: 80
  protocol: TCP
```
I can normally see the endpointSlice resource I created through the query
<img width="586" alt="image" src="https://github.com/cilium/cilium/assets/45261749/933803c8-b4c9-4233-8daa-aa0db9734f3e">
Of course, I also saw my newly added endpoint information through the cilium bpf lb list
<img width="874" alt="image" src="https://github.com/cilium/cilium/assets/45261749/357c3446-4127-48df-a545-1ea0fdd1b25d">
But when I access through NodePort, the external Endpoint does not receive normal feedback. I queried the ct table of cilium and got the following information.
<img width="1651" alt="image" src="https://github.com/cilium/cilium/assets/45261749/a4e9285f-fdd2-4721-939c-f72b4c1826f9">
Finally, I got this information through the main network card capture packet.
<img width="1061" alt="image" src="https://github.com/cilium/cilium/assets/45261749/074708e8-709d-45e2-a31f-04524ebf88b9">
So why my source address becomes 0.0.0.0

### Cilium Version

```bash
[root@10 ~]# cilium version
cilium-cli: v0.14.7 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.3
cilium image (stable): unknown
cilium image (running): v1.13.4
```

### Kernel Version

```bash
[root@10 ~]# uname -a
Linux 10.10.101.164-master 5.10.180 #1 SMP Thu Jun 1 10:19:30 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```bash
[root@10 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-hc.1", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"archive", BuildDate:"2022-01-10T07:44:48Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20230628-125850.zip](https://github.com/cilium/cilium/files/11889604/cilium-sysdump-20230628-125850.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zghyy** [comment]
I spent a while looking through the code of cilium. I don’t know if it is related to the following part. I saw issue GH#17158 mentioned in it.
https://github.com/cilium/cilium/blob/4061cdfc83370200e3f9a0c5a782ca17a288ae71/bpf/lib/nodeport.h#L1975-L1982

**Comment by brb** [comment]
@zghyy Thanks for the detailed issue. Did you observe any drops with `cilium monitor` or Hubble?

**Comment by zghyy** [comment]
The picture below shows the information I got from `cilium monitor` when my request failed. I didn’t see any drops. I thought somewhere changed my source address to `0.0.0.0`, so I went to the code and found `target.addr = IPV4_DIRECT_ROUTING`. 
<img width="1402" alt="image" src="https://github.com/cilium/cilium/assets/45261749/1d0c66b2-292c-42ef-bc81-f9054e3f2f5a">

**Comment by brb** [comment]
>  thought somewhere changed my source address to 0.0.0.0

Did you see with the tcpdump that it's 0.0.0.0 indeed? According to https://github.com/cilium/cilium/blob/v1.13.4/pkg/option/config.go#L2628, when the tunneling is enabled, which is enabled in your case, the `IPV4_DIRECT_ROUTING` is not required.
