### ISSUE TITLE
LoadBalancer service unable to reach external Endpoint

### ISSUE THREAD

**Issue by PKizzle** [cilium/cilium#26515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I point a custom Endpoint to an external IP address and use a LoadBalancer service that is linked to this Endpoint. I expect to be able to reach the external service using the LoadBalancer IP address but am unable to connect. Strangely, I can connect to the external service using the LoadBalancer IP address from any node but not from outside the cluster.

### Cilium Version

Client: 1.14.0-snapshot.4 6c8db759 2023-06-16T12:17:20-07:00 go version go1.20.5 linux/arm64
Daemon: 1.14.0-snapshot.4 6c8db759 2023-06-16T12:17:20-07:00 go version go1.20.5 linux/arm64

### Kernel Version

6.1.21-v8+ aarch64 GNU/Linux

### Kubernetes Version

v1.27.2+k3s1

### Metallb Version

v0.13.10

### Sysdump

[cilium-sysdump-20230627-234741.tar.gz](https://github.com/cilium/cilium/files/11887634/cilium-sysdump-20230627-234741.tar.gz)

The sysdump file extension had to be modified in order to upload to GitHub. Change it back to `.tar.zst` before attempting to unpack.

### Relevant log output

```
msg="Kubernetes service definition changed" action=service-updated endpoints="${EXT_IPV4}:6690/TCP,${EXT_IPV6}:6690/TCP" k8sNamespace=network k8sSvcName=drive-server old-endpoints= old-service=nil service="frontends:[10.43.41.69 fd99::187]/ports=[drive-server]/selector=map[]" subsys=k8s-watcher
msg="Upserting service" backends="[${EXT_IPV4}:6690]" l7LBFrontendPorts="[]" l7LBProxyPort=0 loadBalancerSourceRanges="[]" serviceIP="{10.43.41.69 {TCP 6690} 0}" serviceName=drive-server serviceNamespace=network sessionAffinity=false sessionAffinityTimeout=0 subsys=service svcExtTrafficPolicy=Cluster svcHealthCheckNodePort=0 svcIntTrafficPolicy=Cluster svcType=ClusterIP
msg="Acquired service ID" backends="[${EXT_IPV4}:6690]" l7LBFrontendPorts="[]" l7LBProxyPort=0 loadBalancerSourceRanges="[]" serviceID=56 serviceIP="{10.43.41.69 {TCP 6690} 0}" serviceName=drive-server serviceNamespace=network sessionAffinity=false sessionAffinityTimeout=0 subsys=service svcExtTrafficPolicy=Cluster svcHealthCheckNodePort=0 svcIntTrafficPolicy=Cluster svcType=ClusterIP
```

### Anything else?

I have switched the CNI plugin from tigera/calico and over there the aforementioned configuration was working fine.

Follow these steps to re-create the issue:
1. Create a custom Endpoint pointing to an external IP address
2. Create a LoadBalancer service with the same name as the endpoint
3. Try to connect to external service using the LoadBalancer IP address

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PKizzle** [comment]
The same situation with version 1.14.0-rc.0

**Comment by brb** [comment]
> Strangely, I can connect to the external service using the LoadBalancer IP address from any node.

Thanks for the issue. Are you saying that you are able to connect to the service from outside the cluster, but *not* able from inside the cluster?

**Comment by PKizzle** [comment]
I am able to connect from within the cluster as well as from the host network of the Kubernetes node. However, not from any other external device.

**Comment by PKizzle** [comment]
Is there any further information I may provide?

**Comment by PKizzle** [comment]
I think I found the issue. As can be seen from the Wireshark capture above the external endpoint's traffic is directly routed to the `telnet` sender without changing it to the LoadBalancer's IP address.

**Comment by PKizzle** [comment]
Ok so this related to DSR. When using the SNAT mode everything works as expected.

**Comment by brb** [comment]
> Ok so this related to DSR. When using the SNAT mode everything works as expected

Aha, so I think the failure is expected. What happens is that the external IP owner (`custom Endpoint to an external IP address`) does not have any Cilium's BPF program which could handle the DSR reply. In particular, before sending the reply to the client, it needs to rev-DNAT it.

**Comment by PKizzle** [comment]
Would it be possible to add this special case to the hybrid mode and let the endpoint use SNAT?
