### ISSUE TITLE
Metrics node_connectivity_latency_seconds have a cardinality leak

### ISSUE THREAD

**Issue by joulaud** [cilium/cilium#26512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We observe a leak of cardinality on `cilium_node_connectivity_latency_seconds` with notable impact on our Prometheus stack.

![20230627T150639_manual_ZONE_Navigator-Firefox_WM_NAME_COMPOUND_TEXT-Thanos-Highly_available_Prometheus_setup-Mozilla_Firefox](https://github.com/cilium/cilium/assets/48206448/9dcafd45-c26f-47ec-b507-a55704b55b25)

It seems that Cilium exposes metrics for all endpoints it once probed even if those do not exist anymore. At least this would be consistent with the description of the metric which states "last observed latency between the current Cilium agent and other Cilium nodes".

### Cilium Version

Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
Client: 1.11.14 85615c1 2023-02-13T09:07:56+01:00 go version go1.17.13 linux/amd64
Daemon: 1.11.14 85615c1 2023-02-13T09:07:56+01:00 go version go1.17.13 linux/amd64

### Kernel Version

Linux ip-10-71-32-111 5.10.0-20-cloud-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marseel** [comment]
Option `endpointHealthChecking` / `enable-endpoint-health-checking` creates a virtual endpoint for health checking: https://github.com/cilium/cilium/blob/7361056c1544c48bb8919296fbdc4e1a4c698d9b/daemon/cmd/health.go#L35
but looking at the code again it seems like just disabling `healthChecking` already disables the virtual endpoint.

**Comment by tommyp1ckles** [comment]
This is linked to issue: https://github.com/isovalent/roadmap/issues/764 which I'm not sure is related?

**Comment by christarazi** [comment]
This is fixed by https://github.com/cilium/cilium/pull/28382. If I'm mistaken, please reopen.
