### ISSUE TITLE
CFP: Support PROXY Protocol from L2 Aware LB and CNI

### ISSUE THREAD

**Issue by w7team** [cilium/cilium#26530]
非常开心看到新版中新增了[L2 Aware LB](https://docs.cilium.io/en/latest/network/l2-announcements/)功能，让cilium可以原生支持LoadBalancers类型，想询问一下下一步有没有支持PROXY Protocol的计划，大多L7层的应用比如nginx、traefik已经支持了PROXY Protocol，但是**cni**转发时会把来源ip给弄丢，所以我认为PROXY Protocol还是很有必要的，希望能看到下一步的支持计划

I am very happy to see that the L2 Aware LB function has been added in the new version, so that cilium can natively support the LoadBalancers type. I would like to ask if there is any plan to support the PROXY protocol in the next step, mainly because L7 layer applications such as nginx and traefik already support the PROXY protocol. , but the source ip is lost when **cni** forwards, so I think PROXY Protocol is still necessary, and I hope to see the next support plan

**Comment by aanm** [comment]
cc @dylandreimerink FYI
