### ISSUE TITLE
Pods on a single node(s) periodically become unreachable (EKS, Clustermesh)

### ISSUE THREAD

**Issue by georgew5656** [cilium/cilium#26543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have two EKS clusters running clustermesh enabled through the helm chart.
This generally seems to work pretty well except for some deployment issues [helm: Add client-cert K8s Secret when clustermesh apiserver is enabled](https://github.com/cilium/cilium/pull/26537/commits/5f8fa45d8be02cb11ea2b5bcc5950ddc9ec258e0)

There is an issue that seems to randomly occur where many/all of the pods on a single node will no longer be able to do pod-to-pod communication (generally reaching out of the cluster seems to work okay, though a few requests get blocked).
The issue is superficially similar to: https://github.com/cilium/cilium/issues/25518, but I have checked the net.ipv4.conf.all.rp_filter config and it is set properly.

When the pods are rotated off of the node they seem to work fine. Eventually, it seems like the node is able to recover, but not immediately after all the pods are removed.

My initial suspicion was that this was our cloud provider throttling our nodes, but they reported seeing not packets dropped on the ENI of the node (the packets were dropped inside the node), and the fact that the issue does not seem to immediately resolve itself after removing our highest volume pods off the node seems to rule out straightforward throttling (the issue _could_ still be related to load but doesn't seem to be direct throttling).

The only strange thing that I was able to discover is a bunch of rejected connection errors on the etcd container in the cilium apiserver pod, on requests coming from cilium agent pods in the same cluster. This might just be because cilium agents pod in cluster 1 have credentials to hit etcd in cluster 2 but not in cluster 1, but are still trying to make requests to etcd in cluster 1 and are just getting permission denied, leading to those rejected connection errors.

### Cilium Version

1.13.0

### Kernel Version

Linux amzn2.aarch64 3 aarch64 aarch64 aarch64 GNU/Linux

(Amazon Linux)

### Kubernetes Version

1.24

### Anything else?

We're running in CRD mode and there's not too much else running in the way of NetworkPolicies, etc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
If you're running v.1.13.0, you don't have [this fix](https://github.com/cilium/cilium/pull/23532), which is in v1.13.1.

Can you upgrade to the latest v1.13 release and, if it happens again, capture a sysdump? It includes a decent amount of health checking information so it should aid in debugging. Thanks!

**Comment by georgew5656** [comment]
The issue was with counter exhaustion and IPSEC, solved this by rotating keys. (https://docs.cilium.io/en/latest/security/network/encryption-ipsec/)
