### ISSUE TITLE
vxlan mode + without kube-proxy:  pod can't to start due to "Cilium API client timeout exceeded"

### ISSUE THREAD

**Issue by cyclinder** [cilium/cilium#26554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I configured cilium to run in `vxlan` mode and set kube-proxy Replacement to strict. Also configured: `enable-host-legacy-routing: false`. 

All pods of cilium were Running state, But I can't start a nginx pod, and with an error message of "Cilium API client timeout exceeded".

And I edit `cilium-config` configMap and set `enable-host-legacy-routing: "true"`,  and then I restarted the cilium pod：

```
kubectl delete po -n kube-system -l k8s-app=cilium
```

The nginx pod ran successfully.

### Cilium Version

v1.13.2

### Kernel Version

```
Linux 10-20-1-230 5.19.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct 12 18:33:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:42Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

Maybe we should prevent this combination of configurations in the code, or document it.

```
tunnel: vxlan
enable-host-legacy-routing: "false"
kube-proxy-replacement: strict
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
So, that sort of error message meant that the CNI ADD request, which talks to the local Cilium agent over a GRPC socket, failed. There can be a few causes of this, but the _most likely one_ is a deadlock.

If you are able to reproduce this, can you please capture a sysdump and include it? That would make determining the issue, if any, much easier. Thanks!
