### ISSUE TITLE
CFP: Add an application runtime with no sidecar mode

### ISSUE THREAD

**Issue by JasonChen86899** [cilium/cilium#26585]
**Describe the feature you'd like**
Add an application runtime with no sidecar mode. 
As we known **Dapr** that is an perfect application runtime with side car mode
In cilium, we can do this same thing but can only with an easy way

**Describe your proposed solution**
1. add application runtime operator that handle config
2. make envoy do proxy for applications to operate components
3.  add runtime sdk for applications to use

**Comment by julianwiedmann** [comment]
:wave: hi @JasonChen86899. Right now the description feels very specific - are you planning to work on this? I don't think there is enough context here yet, so others could easily understand what is needed.

**Comment by JasonChen86899** [comment]
hi @julianwiedmann  following is the background
This is some thing about Dapr (https://github.com/dapr) which is a runtime for building distributed applications across the cloud and edge.
But in production development env, we not only need an application runtime like Dapr but also need a service mesh  like cilium mesh or istio
So we can expand cilium mesh and add an application runtime.That is my reason for this issue

**Comment by youngnick** [comment]
Hi @JasonChen86899, it sounds like you would like Cilium to grow support for interacting with Dapr and other similar application frameworks.

This would be a significant amount of engineering effort, so I encourage you to come to a community meeting and talk about what benefits you feel this would bring.

**Comment by JasonChen86899** [comment]
@ldelossa @youngnick  I will test Dapr with cilium first. IMO if this ok, this will be a good thing for developer using two sidecar in one pod (two sidecar: istio sider car and dapr sidecar)

**Comment by macmiranda** [comment]
I believe Dapr solves many of the same problems that Istio does. At least in our company, we didn't see any advantage in using both of them together.

It would be great though if **Cilium** and **Dapr** could interact with each other, especially when it comes to mTLS and Layer 7 policies, but I'd guess the same limitations as the Istio integration would apply:

> * mTLS mode STRICT or PERMISSIVE (default) are not compatible with Cilium HTTP network policy. To use an HTTP-based network policy (for example, [Layer 7 Examples](https://docs.cilium.io/en/latest/security/policy/language/#l7-policy)), you must configure mtls.mode=DISABLE under Istio’s PeerAuthentication.

**Comment by JasonChen86899** [comment]
@macmiranda  Thx for sharing the experience with istio and Cilium.

But I have different opinions on Dapr and istio. Dapr sidecar and istio sidecar do different things. Dapr is application runtime and istio is service mesh .this doc 
 explains it. https://docs.dapr.io/concepts/service-mesh/  The only same feature maybe  mTLS encryption and distributed tracing. There are some mesh capabilities provided by istio and Dapr does not provide these capabilities

So I want to integrate application runtime and service mesh. In this case, I test Dapr and Clilium mesh which replaces with istio. There will be only one sidecar in pod and network traffic router between pods will be provided by Cilium

**Comment by macmiranda** [comment]
I'd argue that the features you're attributing to Service Meshes are usually provided by CNIs too. That's why Cilium would be such a good replacement in this case. The overlap between Dapr and Cilium would be minimum. Sure Cillium (now) does Service Mesh but it's the CNI features that shine.

**Comment by JasonChen86899** [comment]
@macmiranda  ok, I understand what you mean. I have a question. 

Does Cillium mesh now work like istio or can totally replace istio. For example, I want to do traffic-management for services just like istio traffic-management. Does Cililum mesh has this feature or is it in the plan or on going?
