### ISSUE TITLE
Missing affinity in the preflight daemonset template 

### ISSUE THREAD

**Issue by DanniRiggin** [cilium/cilium#26604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We need to deploy different preflight daemonsets across different node types. To do this we would like to set affinity on the preflight daemonset. 

https://github.com/cilium/cilium/blob/d102dbc5f1056493f01efea9c9059771b9c63823/install/kubernetes/cilium/values.yaml#L2546 - provides a way to set affinity for cilium-preflight. 

But because: 
https://github.com/cilium/cilium/blob/d102dbc5f1056493f01efea9c9059771b9c63823/install/kubernetes/cilium/templates/cilium-preflight/daemonset.yaml is missing: 
```
{{- with .Values.preflight.affinity }}
affinity:
  {{- toYaml . | trim | nindent 8 }}
{{- end }}
```
The affinity is not respected. 

### Cilium Version

Copied the template using 1.12.10 and 1.12.7 as the versions, but I assume this is across versions. 

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Good catch!

**Comment by aanm** [comment]
@DanniRiggin thank you for the GH issue, would you like to submit a PR with a fix?
