### ISSUE TITLE
CFP: Unified Logging

### ISSUE THREAD

**Issue by dminninger-devk** [cilium/cilium#26616]
We're running cilium on an aws eks cluster and are ingesting the application logs with filebeat. Persisting the logs to elastic is quite a problem because the schema differs from where the log is output in the code. Elastic throws errors and some loglines are not persisted - no good.

# Some examples:

## Labels:
You're  writing labels as `map` here: https://github.com/cilium/cilium/blob/c068a443049b5dedb34608069df4b1721b1e4669/pkg/k8s/identitybackend/identity.go#L92C44-L92C44 .
But here you're writing an `array`: https://github.com/cilium/cilium/blob/main/pkg/k8s/network_policy.go#L35

## k8sNamespace
Usually you're logging `k8sNamespace` as `string` (`keyword` in elastic) but in some cases you're defining subfields which breaks the elastic schema.
Defining subfield `k8sNamespace.illegal`: https://github.com/cilium/cilium/blob/c068a443049b5dedb34608069df4b1721b1e4669/pkg/k8s/apis/cilium.io/utils/utils.go#L314C12-L314C12

Defining `k8sNamespace.old`: https://github.com/cilium/cilium/blob/c068a443049b5dedb34608069df4b1721b1e4669/pkg/k8s/watchers/cilium_network_policy.go#L420

# Request
Please define and use a logging schema throughout the project. It must not be [Elastic Common Schema](https://www.elastic.co/guide/en/ecs/current/index.html) but it would be nice if the schema could be inspired by ECS.

**Comment by aanm** [comment]
@dminninger-devk thanks for the proposal, would you like to submit a PR with the changes?
