### ISSUE TITLE
Issue while testing ESP using cilium 1.13.4

### ISSUE THREAD

**Issue by Muneer94** [cilium/cilium#26626]
I am testing esp on multiclustering environment but facing couple of issues:

1. When I enabled ipsec encryption pods from cluster 1 can't ping pods in cluster 2 but when I used wireguard encryption there are no issues with the communication. Not sure why ipsec encryption didn't work
2. I tried esp test in same node and also in different nodes both didn't work I've checked hubble in that flow of the pod that is sending esp message shows dropped event but no error message
 
**Infra Details:**

-  Kubernetes Version : v1.24.7
-  Cilium Version : 1.13.4
-  Dual Stack K8s cluster --> Cluster1(ipv4/ipv6) , Cluster2(ipv4/ipv6)

[cilium-sysdump-20230704-132432.zip](https://github.com/cilium/cilium/files/11949304/cilium-sysdump-20230704-132432.zip)

**Comment by squeed** [comment]
Just distilling some information from the sysdump:

```
$ cat cilium-encrypt-status.md
Encryption: IPsec                     
Keys in use: 1                         
Max Seq. Number: 0x1a1/0xffffffff
Errors: 2177                      
	XfrmInStateProtoError: 2177   
```

and seeing ipsec errors on the `cilium_host` interface:

```
src 0.0.0.0 dst 10.42.104.49
	proto esp spi 0x00000003(3) reqid 1(0x00000001) mode tunnel
	replay-window 0 seq 0x00000000 flag  (0x00000000)
	mark 0xd00/0xf00 output-mark 0xd00/0xf00
	aead rfc4106(gcm(aes)) [hash:4cae382d54681d4348f90ba315544d5978b5ff9d6c0886415088c5f17073d7a7] (160 bits) 128
	anti-replay context: seq 0x0, oseq 0x0, bitmap 0x00000000
	sel src 0.0.0.0/0 dst 0.0.0.0/0 uid 0
	lifetime config:
	  limit: soft (INF)(bytes), hard (INF)(bytes)
	  limit: soft (INF)(packets), hard (INF)(packets)
	  expire add: soft 0(sec), hard 0(sec)
	  expire use: soft 0(sec), hard 0(sec)
	lifetime current:
	  0(bytes), 0(packets)
	  add 2023-07-03 13:54:46 use 2023-07-03 13:55:59
	stats:
	  replay-window 0 replay 0 failed 1373
```

**Comment by Muneer94** [comment]
I have used the following helm custom values for deploying Cilium in 2 clusters. Is there something I am missing in configuring encryption correctly?

`kubectl create -n kube-system secret generic cilium-ipsec-keys --from-literal=keys="3 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64)) 128"`

```
debug:
  enabled: true

cluster:
  id: 1
  name: mc1

rollOutCiliumPods: true

ipam:
  mode: "kubernetes"

k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: true

encryption:
  enabled: true
  nodeEncryption: false
  type: ipsec
  ipsec:
    keyFile: keys
    mountPath: /etc/ipsec
    secretName: cilium-ipsec-keys

ipv4:
  enabled: true

ipv6:
  enabled: true

tunnel: "vxlan"

sctp:
  enabled: true
```

**Comment by squeed** [comment]
You do need to make sure that both clusters have the same key. AIUI this is not documented anywhere :-(.

**Comment by Muneer94** [comment]
@squeed Thanks for the suggestion. I have tried using the same key in both clusters now connectivity is working fine.
But still esp test is not working across different nodes and also in same node(both esp server and client in same node). I have attached sysdump of esp test (esp server in Cluster 1 and esp client in Cluster 2 )

[cilium-sysdump-20230707-185232.zip](https://github.com/cilium/cilium/files/11984268/cilium-sysdump-20230707-185232.zip)

**Comment by brb** [comment]
> still esp test

What is this test?

**Comment by Muneer94** [comment]
**Simple Pod with nc installed in it Deployed in Custer 1 (Acting as a Server):**

```
nc -l <server_ip> 12345
nc -l 10.42.1.150 12345
```

**Another Pod Deployed in Cluster2 (Acting as a Client):**

Now I send a message to the server IP by the following command
```
nc <server_ip> 12345 -p 12345
nc 10.42.1.150 12345 -p 12345
sample message
```

**Note:** When I deploy both server and client in the same node I can see the message as pods in the same node don't need encryption, but when I test it across different clusters I don't see the message in the server 

Sorry for not being clear in my previous comments @brb

**Comment by brb** [comment]
We do have IPsec tests for ClusterMesh - https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-clustermesh.yaml. Have you checked those?
