### ISSUE TITLE
review and document all the Helm values in values.yaml

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#26654]
some helm values are commented out. for example:

https://github.com/cilium/cilium/blob/c068a443049b5dedb34608069df4b1721b1e4669/install/kubernetes/cilium/values.yaml#L329-L335

these commented out values do not get included in the auto-generated [README.md](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/README.md), which makes it difficult to know all the available configuration options.

the goal of this issue is to review and document all of these commented out helm values 📝

**Comment by aanm** [comment]
@nbusseneau can you take a look?
