### ISSUE TITLE
Datapath: 1.14 Pre-Release Regression Testing

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#26651]
This issue is to track pre-1.14 regression testing for datapath throughput and latency. The goal is to perform a check to ensure that Cilium with a default install does not contain a regression between 1.12, 1.13, and 1.14-pre.

Goal: Compare throughput and latency on a default helm install of Cilium between 1.12, 1.13, and 1.14-pre.
Non-Goal: Gather independent, publishable numbers regarding throughput and latency performance.
Test Environment: Two-node GKE cluster.
Test Setup: Pod-to-pod netperf test for TCP stream, CRR, and RR with the same number of parallel connections as cores.

CC: @aanm, @marseel, @borkmann

**Comment by learnitall** [comment]
I got a first round of results today. I had trouble finishing the CRR tests due to an issue with the conntrack table filling up on each node. I haven't dug into the results yet, I'll do that next week and report the findings here.

Here are the results from each test. Note that the CRR and RR tests I ran only gave percentiles, so rather than averaging them, I'm taking the results from the netperf instance with the largest 99th percentile.

CRR Latencies (ms) by Version (lower is better)

|Version|50th|90th|99th|
|---|---|---|---|
|1.14.0-rc.0|848|2536|8380|
|1.13.4|864|2357|8073|
|1.12.10|762|2319|7080|

RR Latencies (ms) by Version (lower is better)

|Version|50th|90th|99th|
|---|---|---|---|
|1.14.0-rc.0|144|216|467|
|1.13.4|149|235|504|
|1.12.10|148|226|513|

Stream Average Throughput (10^6 bits/s) by Version (higher is better)

|Version|Throughput
|---|---|
|1.14.0-rc.0|992|
|1.13.4|987|
|1.12.10|991|

**Comment by joestringer** [comment]
This looks like it is within parameters for the v1.14.0 release. Thanks for testing @learnitall!
