### ISSUE TITLE
Policy Precedence testing

### ISSUE THREAD

**Issue by nathanjsweet** [cilium/cilium#26717]
- Make sure that [the permutation matrix](https://docs.google.com/spreadsheets/d/1WANIoZGB48nryylQjjOw6lKjI80eVgPShrdMTMalLEw/edit#gid=2109052536) for all different types of policies is complete.
- Make sure that various identity tests are also tested for CIDR corollaries (i.e. identities which are technically not equal, but overlap because their CIDRs overlap).
- Test complex CIDR policies (e.g. [the "Allow-ception" test](https://github.com/cilium/cilium/pull/26718))

**Comment by christarazi** [comment]
Redirect, deny, auth are the categories of precedence.

**Comment by joestringer** [comment]
@nathanjsweet @squeed is there something more to do for this? It was originally scheduled around the time of v1.14, but it seems like we don't plan to do anything for it.

**Comment by nathanjsweet** [comment]
@joestringer
- The permutation matrix is covered by [TestMapState_denyPreferredInsertWithSubnets](https://github.com/cilium/cilium/blob/main/pkg/policy/mapstate_test.go#L2755)
- CIDR corollaries are covered by [Test_EnsureDeniesPrecedeAllows](https://github.com/cilium/cilium/blob/main/pkg/policy/distillery_test.go#L1654)

Allow-ception still needs a test and is the last element of this issue. I will work to get that done this week to close this issue.
