### ISSUE TITLE
GCP healthchecks fail in KubeProxyReplacement mode

### ISSUE THREAD

**Issue by nberlee** [cilium/cilium#26727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Clusters hosted on GCP in kube-proxy-less mode, setting up a loadbalancer-service using `externalTrafficPolicy: Local` triggers failures in GCP healthchecks. This leads to ingress traffic being distributed among all Kubernetes nodes.

The [cloud-provider-gcp](https://github.com/kubernetes/cloud-provider-gcp) sets up these healthchecks based on the services' `spec.healthCheckNodePort`. This port is made accessible by Cilium on the nodeIP. However, GCP healthchecks have a destination IP towards the forwarding rule IP (equivalent to `spec.loadBalancerIP`). This results in the GCP LB randomly sends these packets to any nodes within the GCP instance group.

The problem emerges since Cilium's HealthServer binds to local IPs and no forwarding rules for the LBips, hence, it doesn't acknowledge the GCP LB healthcheck packets. It's noteworthy that Kube-Proxy has [forwarding rules](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1683) set up for such scenarios.

### Cilium Version

1.13.4

### Kernel Version

6.1.35

### Kubernetes Version

1.26.6

### Anything else?

See https://github.com/kubernetes/kubernetes/issues/117621#issuecomment-1531059530 for a packetcapture of this behaviour. And a more detailed discussion on what GCP healthchecks are doing.

I will create a PR to fix this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
@nberlee :wave:  Is the following still the case?

> However, GCP healthchecks have a destination IP towards the forwarding rule IP (equivalent to spec.loadBalancerIP). This results in the GCP LB randomly sends these packets to any nodes within the GCP instance group.

To me it is weird that they are sending HCs randomly by using `loadBalancerIP` instead of iterating over nodes list, and then deriving which nodes have endpoints.

**Comment by nberlee** [comment]
Sorry for the confion, this is bad wording from me.

the word `these` should not have been in here. `these` points to healtcheck traffic, where as I was trying to say that normal traffic now gets random split over all instances.

 I am talking about the consequence of not having any instance (node) that is up according to the healthcheck. This causes the loadbalancer to randomly send packets to any node withing the GCP instance group as a fallback (without any session affinity).
