### ISSUE TITLE
Custom IPAM section in CNI config is ignored

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#26731]
@joamaki stumbled upon the fact that NetConf isn't set anymore in the daemon: https://github.com/cilium/cilium/blob/main/daemon/cmd/daemon.go#L405. This is passed down to NodeDiscovery which then pulls some IPAM related things out of it.

This breaks the ability to configure IPAM parameters such as e.g. the ones used for ENI [documented here](https://docs.cilium.io/en/stable/network/concepts/ipam/eni/#custom-eni-configuration). Since this is a critical ability for many ENI users, this is a release-blocking bug that we need to address. The IPAM parameters need to be present in the CiliumNode CRD when it is created, otherwise the operator will take meaningful decisions (e.g. attaching network interface from the wrong subnet) based on absent configuration.

In addition, we should probably also add some CI testing around this, for example by using custom subnets in the CI-EKS workflow.

**Comment by squeed** [comment]
The fix has been filed to `main`.
