### ISSUE TITLE
Cilium TLS Ingress and Let's Encrypt DNS-01 challenged cert-manager: need rollout restart of cilium-operator

### ISSUE THREAD

**Issue by sbocahu** [cilium/cilium#26787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On a 1.27.3 kubernetes cluster running on Debian 12;
full bpf cilium config (bpf masquerading, kube-proxy strict);
using cilium for Loadbalancer type using layer2 announcement;
an Ingress of class Cilium, with TLS termination (letsencrypts provider managed from cert-manager)

1. deployed a web solution using helm; tried to access the HTTP service with curl: **connection reset by peer**
issued rollout restart deploy/cilium-operator => OK webservice available through the ingress

2. duplicate of #26586    ̶u̶p̶g̶r̶a̶d̶e̶d̶ ̶t̶h̶e̶ ̶s̶o̶l̶u̶t̶i̶o̶n̶ ̶w̶i̶t̶h̶ ̶h̶e̶l̶m̶;̶ ̶t̶r̶i̶e̶d̶ ̶t̶ ̶o̶a̶c̶c̶e̶s̶s̶ ̶t̶h̶e̶ ̶H̶T̶T̶P̶ ̶s̶e̶r̶v̶i̶c̶e̶ ̶w̶i̶t̶h̶ ̶c̶u̶r̶l̶:̶ ̶*̶*̶H̶T̶T̶P̶ ̶5̶0̶3̶ ̶s̶e̶r̶v̶i̶c̶e̶ ̶u̶n̶a̶v̶a̶i̶l̶a̶b̶l̶e̶*̶*̶
̶t̶r̶i̶e̶d̶ ̶c̶u̶r̶l̶ ̶o̶n̶ ̶t̶h̶e̶ ̶s̶e̶r̶v̶i̶c̶e̶ ̶i̶p̶/̶p̶o̶r̶t̶:̶ ̶O̶K̶ ̶w̶e̶b̶s̶e̶r̶v̶i̶c̶e̶ ̶a̶v̶a̶i̶l̶a̶b̶l̶e̶ ̶o̶n̶ ̶t̶h̶e̶ ̶C̶l̶u̶s̶t̶e̶r̶I̶p̶ ̶s̶e̶r̶v̶i̶c̶e̶
̶i̶s̶s̶u̶e̶d̶ ̶r̶o̶l̶l̶o̶u̶t̶ ̶r̶e̶s̶t̶a̶r̶t̶ ̶d̶e̶p̶l̶o̶y̶/̶c̶i̶l̶i̶u̶m̶-̶o̶p̶e̶r̶a̶t̶o̶r̶:̶ ̶n̶o̶ ̶c̶h̶a̶n̶g̶e̶
̶i̶s̶s̶u̶e̶d̶ ̶r̶o̶l̶l̶o̶u̶t̶ ̶r̶e̶s̶t̶a̶r̶t̶ ̶d̶a̶e̶m̶o̶n̶s̶e̶t̶s̶/̶c̶i̶l̶i̶u̶m̶:̶ ̶O̶K̶ ̶w̶e̶b̶s̶e̶r̶v̶i̶c̶e̶ ̶a̶v̶a̶i̶l̶a̶b̶l̶e̶ ̶t̶h̶r̶o̶u̶g̶h̶ ̶t̶h̶e̶ ̶i̶n̶g̶r̶e̶s̶s̶

### Cilium Version

1.14.0-rc.0

### Kernel Version

6.1.37 from Debian 12

### Kubernetes Version

1.27.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
If you updated cilium config(s), then it's expected that the operator/cilium DS needs to be restarted. Can you elaborate on what your expectations are?

**Comment by sbocahu** [comment]
I had not updated Cilium's config, only deployed a web solution that uses Cilium features:

1. setup k8s cluster, configure Cilium, check that it works as expected (example following Cilium quickstart/doc using a nginx deployment + expose it), setup external-dns & cert-manager, restart cilium ds/operator "in case of"
2. deploy a web solution; it should become available on https://something... - it may, however it may not and require a rolling restart of the operator and/or the daemonset (no other operation, no config change)

Moreover, I'm highly confident that I left a working setup yesterday evening; however I needed to issue a rolling restart of Cilium DS this morning to access to web solution.
Curl was stuck 'Trying IP:443...'

I'll do some more testing and take more notes but I usually don't open issues without a certain amount of confidence there is indeed something wrong.

**Comment by sbocahu** [comment]
New deployment => connection reset by peer | rollout restart of cilium-operator => OK

Last logs of cilium-operator leader, before rollout restart:

```
level=error msg="Failed to process Ingress event, skipping: {ingress:0xc0014d2a00}" subsys=ingress-controller                                                                                                                                  
level=error msg="Failed to process Ingress event, skipping: {oldIngress:0xc0014d2a00 newIngress:0xc000af6b00}" subsys=ingress-controller
```

grep of 'ingress' in operator leader after restart:

```
level=info msg="Notify ingress controller for service ingress" subsys=ingress-controller
level=info msg="Notify ingress controller for service ingress" subsys=ingress-controller
level=info msg="Notify ingress controller for service ingress" subsys=ingress-controller
level=info msg="Notify ingress controller for service ingress" subsys=ingress-controller
```

It takes time to get the certificate from LetsEncrypt using DNS-01 challenge, could it be the source of this issue ?

The logs about o,gress processing failure are not helpful, how can we get more info on what's going on ?

**Comment by sbocahu** [comment]
a few hours ago I left with 4 ingresses OK, I'm back and 2 of them or KO.

rollout restart of DS and all of them are OK.

**Comment by aanm** [comment]
Hello, thanks for opening the GH issue, please provide steps to reproduce the issue and a cilium sysdump otherwise the issue can't be fixed. Thank you.

**Comment by sbocahu** [comment]
Hi,

Reinstalled the cluster from scratch, with Cilium 1.14.0-rc.1 and kubernetes 1.27.4.



This is a sysdump after a first deployment

[cilium-sysdump-20230724-133414.zip](https://github.com/cilium/cilium/files/12146464/cilium-sysdump-20230724-133414.zip)

Debug logs show upserts for the endpoint but lacking for the certificate secret until the rollout restart of operator, issued minutes after the cert was issued (kubectl get cert: age 33m / kubectl get -n cilium-secrets ...cert: age 11m)

![image](https://github.com/cilium/cilium/assets/929169/c3205551-7815-4f6e-b25a-a3d95b16aff2)

**Comment by sbocahu** [comment]
Here is a sysdump *after* rollout restart of daemonsets. I forget to create it before, when experiencing issue with accessing the ingress from the outside of the cluster.

However I had read about the kubectl get lease command on some slack conversation and I had checked it:

when the problem occurs (can't access the ingress service from outside the cluster); 'kubectl get leases' shows only a hand of leases and none are related to the deployments I try to reach.
After rollout restart ds/cilium, a lot of more leases appear, notably the service and ingress that I am targeting.

Nothing in the logs rang a bell but I was probably looking for something too obvious

[cilium-sysdump-20230724-190436.zip](https://github.com/cilium/cilium/files/12149297/cilium-sysdump-20230724-190436.zip)

**Comment by sbocahu** [comment]
2/ issue seems to be identical to #26586. Although I had searched the existing issue at the time, I missed it because of misunderstanding/lack of troubleshooting at that time. Now hthat I read it again it rings a bell.

I'm testing with: --set l2announcements.leaseRenewDeadline=10s --set l2announcements.leaseDuration=30s --set l2announcements.leaseRetryPeriod=3s

**Comment by meyskens** [comment]
I have tried but failed to replicate this. Your sysdump seems to be done in the kube-network namespace thus is missing the logs. I would be very interested in reading the operator logs for before and after the restart of the deployment. Could you try to run this again and upload them for me to look into?
