### ISSUE TITLE
aws-eni datapath + helm chart + generated ConfigMap *never* allows for correct direct routing configs or BPF masquerade

### ISSUE THREAD

**Issue by armenr** [cilium/cilium#26785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There appear to be a number of bugs with the Cilium Helm Chart. 

1. `enable-endpoint-routes: false` is not respected if `eni` is enabled
2. `egress-masquerade-interfaces: eth0` appears in the generated ConfigMap, even when `egressMasqueradeInterfaces` is not set.

**The net effect is that Cilium:** 
1. Falls back to legacy host routing
2. Falls back to iptables-based masquerading.

See notes below for findings + how to reproduce

### Cilium Version

1.13.4

### Kernel Version

5.10.184-175.731.amzn2.x86_64

### Kubernetes Version

v1.27.3-eks-a5565ad

### Sysdump

[cilium-sysdump-20230712-140142.zip](https://github.com/cilium/cilium/files/12026558/cilium-sysdump-20230712-140142.zip)

### Relevant log output

```shell
kube-system/cilium-dn9mn[cilium-agent]: level=info msg="BPF host routing is currently not supported with enable-endpoint-routes. Falling back to legacy host routing (enable-host-legacy-routing=true)." subsys=daemon

kube-system/cilium-dn9mn[cilium-agent]: level=warning msg="Falling back to iptables-based masquerading." error="BPF masquerade does not allow to specify devices via --egress-masquerade-interfaces (use --devices instead)" subsys=daemon
```

### Anything else?

I believe the issues are with: 

#### Occurrence 1

The first occurrence for this in the template is found here:

https://github.com/cilium/cilium/blob/40a0fc3a49996c3317b7f873707f4f9c4bdfd5a8/install/kubernetes/cilium/templates/cilium-configmap.yaml#L463

^^ Even **if** you set `endpointRoutes.enabled: false` in Helm, this line appears to override that. 

It may be useful to pass an `or` condition rather than just the `if .Values.eni.enabled`

#### Occurrence 2

Later in the template, there is also this: 

https://github.com/cilium/cilium/blob/40a0fc3a49996c3317b7f873707f4f9c4bdfd5a8/install/kubernetes/cilium/templates/cilium-configmap.yaml#L767

So, it would appear that the templating at line `464` overrides the templating at line `767`

### Problem 2 `egress-masquerade-interfaces` VS `devices`

If I **do not include** the key `egressMasqueradeInterfaces` in my Values.yaml, I am **still seeing** the chart generate a ConfigMap with: `egress-masquerade-interfaces: eth0`

https://github.com/cilium/cilium/blob/40a0fc3a49996c3317b7f873707f4f9c4bdfd5a8/install/kubernetes/cilium/templates/cilium-configmap.yaml#L548

#### Additional context for this problem:

**Cilium info**

```
❯ cilium version
cilium-cli: v0.14.6 compiled with go1.20.4 on darwin/arm64
cilium image (default): v1.13.3
cilium image (stable): v1.13.4
```

**values.yaml**

```
---
bandwidthManager.enabled: true
bpf.masquerade: true
cluster.name: v3-uat-uhura
devices: eth+
enableIPv4Masquerade: true
encryption.nodeEncryption: false
endpointRoutes.enabled: false
eni.enabled: true
externalIPs.enabled: true
hostPort.enabled: true
ipam.mode: eni
ipv4NativeRoutingCIDR: "172.17.16.0/20"
k8sServicePort: 443
kubeProxyReplacement: strict
MTU: 9000
nodePort.enabled: true
operator.replicas: 1
routing-mode: native
socketLB.enabled: true
tunnel: disabled
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
```

**Commands**
```
export CILIUM_CLI_MODE=helm
cilium install --cluster-name v3-uat-uhura --helm-values values.yaml --dry-run
```

**Generated ConfigMap**

```
# Source: cilium/templates/cilium-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  identity-allocation-mode: crd
  identity-heartbeat-timeout: "30m0s"
  identity-gc-interval: "15m0s"
  cilium-endpoint-gc-interval: "5m0s"
  nodes-gc-interval: "5m0s"
  skip-cnp-status-startup-clean: "false"
  disable-endpoint-crd: "false"
  debug: "false"
  debug-verbose: ""
  enable-policy: "default"
  enable-ipv4: "true"
  enable-ipv6: "false"
  custom-cni-conf: "false"
  enable-bpf-clock-probe: "true"
  monitor-aggregation: medium
  monitor-aggregation-interval: "5s"
  monitor-aggregation-flags: all
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-lb-map-max: "65536"
  bpf-lb-external-clusterip: "false"
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: "cilium/istio_proxy"
  cluster-name: v3-uat-uhura
  cluster-id: "0"
  tunnel: "disabled"
  mtu: "9000"
  enable-endpoint-routes: "true"
  auto-create-cilium-node-resource: "true"
  ec2-api-endpoint: ""
  eni-tags: "{}"
  enable-l7-proxy: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6-big-tcp: "false"
  enable-ipv6-masquerade: "true"
  enable-bpf-masquerade: "true"
  egress-masquerade-interfaces: eth0
  enable-xt-socket-fallback: "true"
  install-no-conntrack-iptables-rules: "false"
  auto-direct-node-routes: "false"
  enable-bandwidth-manager: "true"
  enable-bbr: "false"
  enable-local-redirect-policy: "false"
  ipv4-native-routing-cidr: 172.17.16.0/20
  devices: "eth+"
  kube-proxy-replacement: "strict"
  kube-proxy-replacement-healthz-bind-address: ""
  bpf-lb-sock: "true"
  enable-health-check-nodeport: "true"
  node-port-bind-protection: "true"
  enable-auto-protect-node-port-range: "true"
  enable-svc-source-range-check: "true"
  enable-l2-neigh-discovery: "true"
  arping-refresh-period: "30s"
  cni-uninstall: "true"
  enable-endpoint-health-checking: "true"
  enable-health-checking: "true"
  enable-well-known-identities: "false"
  enable-remote-node-identity: "true"
  synchronize-k8s-nodes: "true"
  operator-api-serve-addr: "127.0.0.1:9234"
  enable-hubble: "true"
  hubble-socket-path: "/var/run/cilium/hubble.sock"
  hubble-listen-address: ":4244"
  hubble-disable-tls: "false"
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  ipam: "eni"
  disable-cnp-status-updates: "true"
  enable-vtep: "false"
  vtep-endpoint: ""
  vtep-cidr: ""
  vtep-mask: ""
  vtep-mac: ""
  enable-bgp-control-plane: "false"
  procfs: "/host/proc"
  bpf-root: "/sys/fs/bpf"
  cgroup-root: "/run/cilium/cgroupv2"
  enable-k8s-terminating-endpoint: "true"
  enable-sctp: "false"
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  unmanaged-pod-watcher-interval: "15"
  tofqdns-dns-reject-response-code: "refused"
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: "0s"
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: "100ms"
  agent-not-ready-taint-key: "node.cilium.io/agent-not-ready"
```

On `line 35` you'll notice: 
`  enable-endpoint-routes: "true"`

...which is contrary to what we want. -->  values.yaml: `endpointRoutes.enabled: false`

On `line 44` you'll notice:
`  egress-masquerade-interfaces: eth0`

...which technically shouldn't be there --> not present in the values.yaml I gave to helm, at all

On `line 52` you'll notice:
`  devices: "eth+"`

...which is expected/desired --> values.yaml: `devices: eth+`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
:wave: hi!

For the ENI vs endpoint-routes aspect, I would suggest that you open a PR with your proposed change and discuss why that's a good idea.

For the masquerading part, this is likely what's causing you troubles:

```
  enable-ipv4-masquerade: "true"
  ...
  enable-ipv6-masquerade: "true"
  enable-bpf-masquerade: "true"
```

`v1.13` doesn't have support for IPv6 BPF Masquerading yet, so we're falling back to iptables masquerading.

**Comment by michaelsaah** [comment]
this brings up something I've been wondering about, which is whether it's possible (in a technical sense) to run in "ENI mode" (i.e. pods get VPC-routable IPs) and also use BPF routing, as opposed to legacy.

the fact that `enable-endpoint-routes` gets set to `true` when enabling ENI mode suggests that it is not. however, if there are performance gains to be had by using BPF routing, then it would be advantageous for ENI mode users to have access to those gains.

**Comment by michaelsaah** [comment]
thanks for the detailed reply @armenr, good to hear you have it working with this configuration

**Comment by iuliancristea** [comment]
The fact that Cilium is meant to work with eBPF host routing in `eni` mode, but the Helm Chart templates out unexpected values seems to be a bug.

Is anyone looking at this at the moment or should I?

**Comment by joestringer** [comment]
I see two problems highlighted in the description:

1. enable-endpoint-routes: false is not respected if eni is enabled

ENI mode requires endpoint-routes mode to be enabled. Otherwise, forwarding between Pods and the underlying network may be incorrect, which in some cases may lead to packet loss due to the underlying Amazon network dropping the traffic. Note that this is not deterministic, the traffic may sometimes work and sometimes does not work. This behaviour is out of the control of Cilium if you somehow configure Cilium with endpoint-routes mode disabled.

2. egress-masquerade-interfaces: eth0 appears in the generated ConfigMap, even when egressMasqueradeInterfaces is not set.

I know that the devices configurations have undergone a few changes in recent versions of Cilium and IIRC there will be further changes in v1.16. I'm not sure exactly whether the problem reported in this issue is specifically a Helm configuration issue, in which case perhaps it's worth posting a proposal for how to improve the Helm handing, or whether it's a problem with the underlying device flags and interactions between the devices flag and masquerade interfaces flag. At least from the latest implementation in the `main` branch I don't see it generating the `eth0` setting by default:

```
$ helm template ./install/kubernetes/cilium/ | grep -i masq
  enable-ipv4-masquerade: "true"
  enable-ipv6-masquerade: "true"
  enable-masquerade-to-route-source: "false"
```

I don't see eth0 being added into the Helm configuration if I use the `values.yaml` from this issue description either.

Seems to me like this issue is now solved. If you are still experiencing an issue with the ENI Helm configurations and masquerade flags, please consider filing a new issue afresh to summarize what you are trying to do and the exact steps to reproduce the problem you observe.
