### ISSUE TITLE
CFP: Emulate Network Failures for Chaos Testing

### ISSUE THREAD

**Issue by hoozgomk** [cilium/cilium#26835]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

I work on a project where we test various interruptions on k8s services. I'm working on extending the supported protocols and I noticed that there is no tool available for emulating network failures on k8s clusters with the eBPF-based network. 

**Describe the feature you'd like**

Please provide documentation (if the actual feature already exists) or provide the functionality to emulate network-based fault emulation (chaos testing) when using Cilium for network packet management. 

Thank you 🙏 & kind regards!

**Comment by aditighag** [comment]
Hey, that's an interesting proposal. We currently don't have any such tool. Can you list a few scenarios for fault/error emulation that you would be interested in for your projects? 

Some scenarios that I can think of (not an exhaustive list) from Cilium pov: 
- Per Cilium endpoint BPF programs missing/delays in loading them
- Exhaustion of service/backend ids allocated for load-balancing
- Conntrack map contention
- K8s node goes down ungracefully
- Policy map full
- Leaked Cilium allocated identities
... and so on.

If you are interested in discussing your ideas, or your feature request in general, you are welcome to join our weekly community meeting - https://docs.cilium.io/en/latest/community/community/.

**Comment by hoozgomk** [comment]
Hello!
Thank you for the reply.

My main interest is to be able to emulate network problems like:
- network delay, 
- packet loss, 
- packet duplicating, 
- packet corrupt, 
- network partition, 
- reaching network bandwidth limit.

Till now, I worked with Linkerd to gather and monitor L7 traffic, Chaos Mesh worked well in this setup to emulate the scenarios mentioned above.
But based on my tests, I couldn't reproduce the same scenarios with Cilium - network injections didn't take effect.
The coverage of this topic across the Internet is somehow limited, thus my conclusions may be wrong. 
I thought that this might be caused by the fact of how Linkerd's proxies handle traffic, but Cilium's eBPF-based networking might have different behavior or requirements for emulating network delays.

Kind regards,
