### ISSUE TITLE
Cilium doesn't understand link-local IPv6 traffic as valid nor ula addresses as local

### ISSUE THREAD

**Issue by samip5** [cilium/cilium#26837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I was looking at the hubble observer logs, when I noticed a lot of dropped traffic for ICMPv6 due to invalid source IP, despite it not being invalid by IPv6 spec.

### Cilium Version

cilium-cli: v0.12.1 compiled with go1.18.5 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.13.4
cilium image (running): v1.14.0-rc.0

### Kernel Version

5.19.0-1022-raspi
5.19.0-46-generic
6.1.0-10-amd64
6.1.38-060138-generic

### Kubernetes Version
```
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.2",
    "gitCommit": "7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647",
    "gitTreeState": "archive",
    "buildDate": "2023-07-03T16:23:17Z",
    "goVersion": "go1.20.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1",
  "serverVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.3+k3s1",
    "gitCommit": "01ea3ff27be0b04f945179171cec5a8e11a14f7b",
    "gitTreeState": "clean",
    "buildDate": "2023-03-27T22:23:17Z",
    "goVersion": "go1.19.7",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

### Relevant log output

```shell
Jul 14 13:21:44.952: 2001:14ba:16fd:9610:307:aa4a:a67b:ffc7 (world) <> fddf:f7bc:9670:1::d037 (world) Stale or unroutable IP DROPPED (ICMPv6 EchoRequest)
Jul 14 13:30:02.627: fe80::988f:36ff:fe24:2756 (ID:49805) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:02.641: fe80::988f:36ff:fe24:2756 (ID:49805) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:02.722: fe80::3c70:5ff:fef0:1992 (ID:7535) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:02.737: fe80::3c70:5ff:fef0:1992 (ID:7535) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:02.925: fe80::3c70:5ff:fef0:1992 (ID:7535) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:03.073: fe80::4407:dff:fe08:433a (ID:36186) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:03.085: fe80::4407:dff:fe08:433a (ID:36186) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:03.141: fe80::3c70:5ff:fef0:1992 (ID:7535) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:03.361: fe80::4407:dff:fe08:433a (ID:36186) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:03.393: fe80::988f:36ff:fe24:2756 (ID:49805) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:03.557: fe80::988f:36ff:fe24:2756 (ID:49805) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
Jul 14 13:30:03.713: fe80::4407:dff:fe08:433a (ID:36186) <> ff02::16 (world) Invalid source ip DROPPED (ICMPv6 143(0))
```

### Anything else?

Seems somewhat related to #26816

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this @samip5, would you be able to collect a sysdump from the cluster please? (https://docs.cilium.io/en/stable/operations/troubleshooting/#reporting-a-problem if you need some instructions).

**Comment by samip5** [comment]
> Thanks for this @samip5, would you be able to collect a sysdump from the cluster please? (https://docs.cilium.io/en/stable/operations/troubleshooting/#reporting-a-problem if you need some instructions).

That contains a LOT of things, could you please tell me what you are most interested in seeing from that dump?

**Comment by youngnick** [comment]
To be honest, I'm not sure. I'm triaging this week, and we usually try to get a sysdump before sending an issue off to the related team.

I suspect that a bunch of the datapath details might be relevant, but I'm not exactly sure which, sorry.

**Comment by YutaroHayakawa** [comment]
It usually happens when your ICMPv6 packet uses an IPv6 address not assigned by Cilium as a source. Could you provide us with the address information of your source Pod?

Also, from network's stand point, link-local address is only usable within the same link (L2 domain). And in case of Cilium network, L2 domain is only within the veth between Pod and host. There's no L2 reachability between Pod to Pod or Pod to outside. In your case, seems like you are trying to reach to the external world with link-local address. Thus, it doesn't work.

**Comment by samip5** [comment]
> Also, from the network's standpoint, a link-local address is only usable within the same link (L2 domain). And in the case of the Cilium network, the L2 domain is only within the veth between Pod and host. There's no L2 reachability between Pod to Pod or Pod to outside. In your case, seems like you are trying to reach the external world with a link-local address. Thus, it doesn't work.


No, those link-local requests are NOT initialised by me (I'm not entirely sure what is doing those) The one on the top with a global address is which was also dropped.

**Comment by YutaroHayakawa** [comment]
> No, those link-local requests are NOT initialised by me (I'm not entirely sure what is doing those) The one on the top with a global address is which was also dropped.

Ok, got it. So, these link-local address is from outside of your cluster correct (BTW, it seems like it's a Multicast Listener Report message (type: 143))?

**Comment by samip5** [comment]
> Invalid source IP drop only happens when the packet comes out from the container and the source IP of the packet is not the one of that container. So, if the packet is coming from outside and you see the invalid source IP error, I guess what's happening here is the Pod is forwarding the packet or generating the packet with the spoofed IP address. In any case, IP <=> Pod mapping information helps. Could you provide that?


Modified dump, that only has CIlium named files.

[cilium-sysdump-modified-20230724-113922.zip](https://github.com/cilium/cilium/files/12143617/cilium-sysdump-modified-20230724-113922.zip)

**Comment by YutaroHayakawa** [comment]
Thanks for the sysdump. Ok, now I understand the problem. So, your Home Assistant Pod is trying to do multicast to `All MLDv2-capable routers (`ff02::16`)` or trying to perform `SSDP (`ff02::c`)`. These are [link-local scope multicast addresses](https://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xhtml). That's why your Pod uses a link-local address as a source.

Then, Cilium doesn't know about your Pod's link-local addresses, because it's automatically assigned by the Linux kernel and not by Cilium. So, Cilium cannot recognize it and thinks that's an invalid source IP address.

It is doing the right thing from the standard's perspective, but I guess your problem is the too noisy Hubble flow log right?

**Comment by samip5** [comment]
> Then, Cilium doesn't know about your Pod's link-local addresses, because it's automatically assigned by the Linux kernel and not by Cilium. So, Cilium cannot recognize it and thinks that's an invalid source IP address.

I think it should know about them, as if that traffic get's dropped, there's multiple issues that come from that.

Eg running vxlan over Cilium with DHCPv6 for pods doesn't really work if Cilium drops link-local packets.

**Comment by samip5** [comment]
One other thing in the log snippet:
```
Jul 14 13:21:44.952: 2001:14ba:16fd:9610:307:aa4a:a67b:ffc7 (world) <> fddf:f7bc:9670:1::d037 (world) Stale or unroutable IP DROPPED (ICMPv6 EchoRequest)
```

That security identity as world is incorrect for the `fd` starting address as that's a local cluster cidr.

**Comment by YutaroHayakawa** [comment]
> I think it should know about them, as if that traffic get's dropped, there's multiple issues that come from that.
> Eg running vxlan over Cilium with DHCPv6 for pods doesn't really work if Cilium drops link-local packets.

If it's a use case for running some link-local operation on Pod <=> Host link, then yeah agree.

So, the problem we can see here is

1. Cilium's source address checking doesn't recognize the link-local address assigned to the Pod
2. Even if 1. is solved, Cilium doesn't drop the link-local multicast packet

**Comment by samip5** [comment]
I think the problem is wider than just those.

Eg blackbox-exporter running as root, will not be able to ping things.

[cilium-sysdump-20230726-230133.zip](https://github.com/cilium/cilium/files/12176846/cilium-sysdump-20230726-230133.zip)

It seems that I need to downgrade or switch CNI as this is just not acceptable.

**Comment by samip5** [comment]
> It's hard to say your blackbox-exporter issue is relevant to this one from your sysdump. What do you mean by `will not be able to ping things`?

The whole pod was unable to either 1) send ICMPv6 or 2) receive the ICMPv6 packet back and a root shell, resulting in operation not permitted errors even with privileged.

**Comment by YutaroHayakawa** [comment]
What's your destination for that ICMPv6 ping? What I don't understand here is why the Pod picks link-local address as a source.

**Comment by samip5** [comment]
> What's your destination for that ICMPv6 ping? What I don't understand here is why the Pod picks link-local address as a source.

That would be any of the a.fi record's AAAA's aka global address and cluster cidr is an ULA prefix.

**Comment by YutaroHayakawa** [comment]
Could you show me your cilium-config ConfigMap? `kubectl -n kube-system get cm cilium-config -o yaml`.

**Comment by samip5** [comment]
> Could you show me your cilium-config ConfigMap? `kubectl -n kube-system get cm cilium-config -o yaml`.

Values are at: https://github.com/samip5/k8s-cluster/blob/88ec9dbae52af3c675a33119ad26032475e5b762/cluster/apps/system/cilium/app/helm-release.yaml

```yaml
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: "true"
  bpf-lb-algorithm: maglev
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-mode: dsr
  bpf-lb-sock: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "2"
  cluster-name: home-cluster
  cni-uninstall: "true"
  custom-cni-conf: "false"
  debug: "false"
  debug-verbose: ""
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "true"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-hubble-open-metrics: "false"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "true"
  enable-ipv6-big-tcp: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-sctp: "false"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-metrics: dns:query drop tcp flow port-distribution icmp http
  hubble-metrics-server: :9965
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  identity-gc-interval: 15m0s
  identity-heartbeat-timeout: 30m0s
  install-no-conntrack-iptables-rules: "false"
  ipam: kubernetes
  ipv4-native-routing-cidr: 10.244.0.0/16
  ipv6-native-routing-cidr: fddf:f7bc:9670::/48
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: 0.0.0.0:10256
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9962
  proxy-prometheus-port: "9964"
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  skip-cnp-status-startup-clean: "false"
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: disabled
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-07-26T20:47:14Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: cilium
    helm.toolkit.fluxcd.io/namespace: kube-system
  name: cilium-config
  namespace: kube-system
  resourceVersion: "343200350"
  uid: b1379046-3862-4bf0-83f5-6c722a14de21
  ```

**Comment by samip5** [comment]
@YutaroHayakawa Was this forgotten?

**Comment by samip5** [comment]
Pinging @YutaroHayakawa again as seems this was forgotten?

**Comment by YutaroHayakawa** [comment]
@samip5 Sorry, indeed it was forgotten. Let me recap the issue again. There are multiple issues raised in this thread. Let me recap them.


1. IPv6 link-local address assigned to the Pod is not recognized by Cilium source address check

You have `Home Assistant Pod` on your cluster and the pod talks to `ff02::16` or `ff02::c`. Since both of them are link-local multicast addresses, the Pod picks its link-local address as a source, and Cilium source address checking doesn't understand the link-local address assigned to the Pod, so it will generate a lot of Hubble flow logs.

I think the easiest solution would be just to silently drop the packet coming from link-local address. Cilium doesn't provide any routability for link-local traffic (Cilium only supports L3 forwarding, L2 is terminated on `lxcXXXXX` device). Thus it doesn't make sense to deal with link-local traffic.

2. `The whole pod was unable to either 1) send ICMPv6 or 2) receive the ICMPv6 packet back as even with a root shell (aka privileged), resulted in operation not permitted errors when I manually invoked ping6 on the pod shell.`

Is this still an issue after this issue fixed? https://github.com/cilium/cilium/issues/26816

**Comment by samip5** [comment]
> @samip5 Sorry, indeed it was forgotten. Let me recap the issue again. There are multiple issues raised in this thread. Let me recap them.
> 
> 1. IPv6 link-local address assigned to the Pod is not recognized by Cilium source address check
> 
> You have `Home Assistant Pod` on your cluster and the pod talks to `ff02::16` or `ff02::c`. Since both of them are link-local multicast addresses, the Pod picks its link-local address as a source, and Cilium source address checking doesn't understand the link-local address assigned to the Pod, so it will generate a lot of Hubble flow logs.
> 
> I think the easiest solution would be just to silently drop the packet coming from link-local address. Cilium doesn't provide any routability for link-local traffic (Cilium only supports L3 forwarding, L2 is terminated on `lxcXXXXX` device). Thus it doesn't make sense to deal with link-local traffic.
> 
> 2. `The whole pod was unable to either 1) send ICMPv6 or 2) receive the ICMPv6 packet back as even with a root shell (aka privileged), resulted in operation not permitted errors when I manually invoked ping6 on the pod shell.`
> 
> Is this still an issue after this issue fixed? #26816


Regarding number one: I don't think it should be silently dropped. I think it should instead work as DHCPv6 will not work either as how it's implemented. I have a gateway pod, that runs an DHCPv4 and DHCPv6 server and traffic is using VXLAN. If one adds IPv6 to that mix, static IPv6 addresses will be able to route traffic via that gateway pod, but DHCPv6 will not as the neighbour becomes unreachable very often via NDP. Related: https://github.com/angelnu/pod-gateway/pull/17

2) I haven't noticed it at least, so maybe not?

**Comment by YutaroHayakawa** [comment]
Where is that VXLAN terminated? In the "Gateway Pod" or in your host namespace?

**Comment by samip5** [comment]
> Where is that VXLAN terminated? In the "Gateway Pod" or in your host namespace?

In the gateway pod using Cilium's default route address.

**Comment by samip5** [comment]
@YutaroHayakawa Can we get some traction on this, yet again?

**Comment by YutaroHayakawa** [comment]
> Application pod -> gateway client sidecar (running dhcp client and overriding default route except for the gateway pod's address which is resolved via kube-dns) -> VXLAN to the gateway pod -> VPN client

How is DHCP involved in this case? The DHCP server runs on "Gateway Pod," and the DHCP client Pod access to the "Gateway Pod" using a VXLAN tunnel. Then why does DHCP traffic leak to the underlay (Cilium Network)? From Cilium's perspective, your Pod should only have VXLAN traffic, and the outer IP address of the VXLAN packet should be Pod IP assigned from Cilium right?

**Comment by samip5** [comment]
> > Application pod -> gateway client sidecar (running dhcp client and overriding default route except for the gateway pod's address which is resolved via kube-dns) -> VXLAN to the gateway pod -> VPN client
> 
> How is DHCP involved in this case? The DHCP server runs on "Gateway Pod," and the DHCP client Pod access to the "Gateway Pod" using a VXLAN tunnel. Then why does DHCP traffic leak to the underlay (Cilium Network)? From Cilium's perspective, your Pod should only have VXLAN traffic, and the outer IP address of the VXLAN packet should be Pod IP assigned from Cilium right?

Correct, but I'm not sure why link-local NDP (which is a requirement for DHCPv6), doesn't seem to work meaning IPv6 works via VXLAN only with static IPs, not via DHCPv6 and even if it does work for a while, it loses the neighbour discovery at some point, which results in loss of connectivity. I haven't been able to figure out why it loses it.

Cilium's shouldn't care at all about the inter-VXLAN traffic.

DHCPv4 does work over the VXLAN (only when the underlay is using IPv4, as it doesn't seem to work at all if underlay is IPv6), but that doesn't rely on IPv6 link-local.

**Comment by YutaroHayakawa** [comment]
> doesn't seem to work meaning IPv6 works via VXLAN only with static IPs, not via DHCPv6 and even if it does work for a while

In your case, you need to run NDP (RA) over your VXLAN. Cilium doesn't allow you to send RA with the Cilium network (in this case, underlay network) because Cilium doesn't provide any L2 reachability between Pods by design. Do you mean even over VXLAN doesn't work? Or are you trying to do NDP with underlay?

> DHCPv4 does work over the VXLAN (only when the underlay is using IPv4, as it doesn't seem to work at all if underlay is IPv6), but that doesn't rely on IPv6 link-local.

I'm not sure why this is the case. If everything is encapsulated with VXLAN, the underlying protocol shouldn't matter. If you have a packet capture of the DHCP packet leaving the Pod (it should be encapsulated), we may find out something.

**Comment by samip5** [comment]
Bot, it was just forgotten...

**Comment by samip5** [comment]
@joestringer Why does it have the more info needed label but I wasn't asked for more info?

**Comment by joestringer** [comment]
@samip5 Yutaro asked some questions above, so I interpreted that more information is needed:

> In your case, you need to run NDP (RA) over your VXLAN. Cilium doesn't allow you to send RA with the Cilium network (in this case, underlay network) because Cilium doesn't provide any L2 reachability between Pods by design. Do you mean even over VXLAN doesn't work? Or are you trying to do NDP with underlay?

**Comment by samip5** [comment]
> Do you mean even over VXLAN doesn't work? Or are you trying to do NDP with underlay?
I mean over VXLAN IPv6 Neighbor Discovery works for a moment, and then fails resulting in loss of IPv6 connectivity, but it does work for a few minutes. However if I'm NOT relying on RAs (eg static IPv6 addresses), it does work fine

It will take some time for me to gather TCP dumps again of the issue.
