### ISSUE TITLE
CFP: Switch SNAT and DSR based on LoadBalancer Endpoint type 

### ISSUE THREAD

**Issue by PKizzle** [cilium/cilium#26865]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

As determined in https://github.com/cilium/cilium/issues/26515#event-9834529800 DSR mode cannot handle a LoadBalancer service connected to an external endpoint.

**Describe the feature you'd like**

Additionally to documenting this limitation the hybrid mode shall be extended to automatically use SNAT mode if such configuration is detected. In detail this is a LoadBalancer service with a custom Endpoint (or EndpointSlice) that points to an IP address outside the cluster.

**Comment by youngnick** [comment]
Hi @PKizzle, it sounds like your feature request is actually two things:
- In the event that a LoadBalancer Service has a Endpoint that is not inside the cluster, traffic bound for that endpoint should SNAT so that it is coming from the Loadbalancer address?
- While that is being worked on, the fact that this doesn't work should be documented.

Does that sound right?

Would you be able to put some more description of the setup you're using in here as well please? It will make it easier for someone to pick this up.

**Comment by PKizzle** [comment]
Hi @youngnick, yes that is correct.

About my setup: The Kubernetes cluster is responsible for proxying all incoming traffic to other network devices that may reside outside the cluster. There are many services that require additional open ports in addition to the standard HTTP(S) ports that can be handled by Ingress resources. As the ingress solution I am using does not provide an internal proxying solution for these ports I rely on the combination of LoadBalancer services and external Endpoints to achieve the same goal.

**Comment by youngnick** [comment]
Thanks for that @PKizzle, I've added some labels here which should get this into the right queues and get someone looking at this for you.

**Comment by PKizzle** [comment]
I think this CFP is still valid as it ensures that the documentation includes problematic configurations that shall be avoided. Also, it provides a workaround should such a configuration be detected.

@youngnick Seems like nobody has looked into this issue so far. Could you maybe ping someone?

**Comment by PKizzle** [comment]
This is still something that should be at least documented so this kind of problematic configuration can be easily detected and fixed.

**Comment by PKizzle** [comment]
Still relevant and should therefore not be closed.

**Comment by PKizzle** [comment]
That would also be a very welcome solution to solve the issue  👍

**Comment by vasiliev-a-a** [comment]
Still relevant
