### ISSUE TITLE
CFP: Entity for all endpoints in ClusterMesh

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#26879]
## Cilium Feature Proposal

**Is your feature request related to a problem?**

Too many endpoints in clustermesh to insert into bpf map so using endpoint selector fails.
Cannot use CIDR rules for managed endpoints.

**Describe the feature you'd like**

A `clustermesh` entity that maps to any managed endpoint. Like `cluster` but not limited to the endpoints with the local cluster id.

**(Optional) Describe your proposed solution**

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by aditighag** [comment]
Hi, That's a reasonable feature request. Just to confirm, do you want the entity to only exclude traffic attributed with the `WORLD` or `CIDR` identity, right?

>A clustermesh entity that maps to any managed endpoint.

But note that the cluster entity applies to non-managed entities within a cluster as well - https://docs.cilium.io/en/latest/security/policy/language/#entities-based.

**Comment by dctrwatson** [comment]
> But note that the cluster entity applies to non-managed entities within a cluster as well

Oh, right. sorry for the incorrect language.

> Just to confirm, do you want the entity to only exclude traffic attributed with the `WORLD` or `CIDR` identity, right?

Right. I want to be able to have a policy that matches any endpoint and any traffic in the `ipv4-native-routing-cidr`. So I assume the selector would look something like:
```
egress:
- toEntities:
	-  clustermesh
- toCIDR:
	- 10.0.0.0/8 
```

**Comment by aditighag** [comment]
Does this following spec work for your use case? 

```
egress:
- toEntities:
	-  {}
- toCIDR:
	- 10.0.0.0/8
```

**Comment by dctrwatson** [comment]
What does `{}` translate to for entities?

**Comment by aditighag** [comment]
See this example in the guide - https://docs.cilium.io/en/latest/security/policy/language/#egress-allow-all-endpoints. It'll allow access to all endpoints in the CNP namespace, including the known entities in the local as well remote clusters.

**Comment by dctrwatson** [comment]
Oh, all endpoints. There's too many endpoints in the mesh to insert into the policy map.

**Comment by aditighag** [comment]
>There's too many endpoints in the mesh to insert into the policy map.

Adding a new `clustermesh` entity selector isn't going to change that, as is the case with the `cluster` selector.

**Comment by dctrwatson** [comment]
> Adding a new `clustermesh` entity selector isn't going to change that, as is the case with the `cluster` selector.

Oh, that's unfortunate. I had assumed entities were a way to map to a group of endpoints.

This request becomes much more daunting then... :(

**Comment by dctrwatson** [comment]
@aditighag should I start a new CFP? Or just edit this one?

To more accurately reflect my real feature request now that I have a better idea of what I'm asking for.
