### ISSUE TITLE
CI: Travis `ERROR: Could not find a version that satisfies the requirement PyYAML==6.0`

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#26873]
## CI failure

Travis is unable to fetch some of the docs tooling dependencies:

```
#7 8.190 Collecting PyYAML==6.0
#7 8.195   Downloading PyYAML-6.0.tar.gz (124 kB)
#7 8.405   Installing build dependencies: started
#7 12.07   Installing build dependencies: finished with status 'done'
#7 12.07   Getting requirements to build wheel: started
#7 12.39   Getting requirements to build wheel: finished with status 'error'
#7 12.39   ERROR: Command errored out with exit status 1:
...
#7 12.39 ERROR: Could not find a version that satisfies the requirement PyYAML==6.0
#7 12.39 ERROR: No matching distribution found for PyYAML==6.0
#7 12.41 WARNING: You are using pip version 21.0.1; however, version 23.2 is available.
#7 12.41 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
#7 ERROR: executor failed running [/bin/sh -c pip install -r /tmp/requirements.txt]: runc did not terminate sucessfully
```

- Observed on main here: https://app.travis-ci.com/github/cilium/cilium/builds/264564427 (PR https://github.com/cilium/cilium/pull/26869)
- And on v1.13 here: https://app.travis-ci.com/github/cilium/cilium/jobs/606180933 (PR https://github.com/cilium/cilium/pull/26861)

**Comment by markpash** [comment]
I'm receiving similar problems when running locally with `make test-docs`.

I found this issue that may be related. There's very recent comments that suggest this is affecting many projects currently.
https://github.com/yaml/pyyaml/issues/601

**Comment by michi-covalent** [comment]
https://github.com/cilium/cilium/pull/26874 should fix the issue. could you try rebasing
