### ISSUE TITLE
Change cilium vagrant image to 18.04 LTS

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2688]
We will switch to 17.10 which will be EOL around June 2018.

We need to switch the base images in April once 18.04 is release installed with the kernel 4.9 LTS to avoid getting bitten by the 17.10 EOL.

**Comment by ianvernon** [comment]
https://itsfoss.com/ubuntu-18-04-release-features/ shows that 18.04 LTS will be released on 26th April.

**Comment by aanm** [comment]
https://github.com/cilium/cilium/issues/4064#issuecomment-388506759

**Comment by joestringer** [comment]
We should prioritize this for Cilium 1.2-1.3 timeline.

**Comment by ianvernon** [comment]
I am blocked on this because there is no Docker package released for 18.04 LTS :( 

https://github.com/cilium/packer-ci-build/pull/57#issuecomment-394527063

**Comment by joestringer** [comment]
Hmm. We could either switch to an edge release temporarily, or hope that Docker releases its next stable (2018.06) before Ubuntu EOL Ubuntu 17.10, and switch then.

**Comment by eloycoto** [comment]
Docker will release the new version with Bionic APT support soon. I understand that will be this week with Dockercon, repos are "ready"
https://download.docker.com/linux/ubuntu/dists/bionic/stable/

**Comment by ianvernon** [comment]
Bionic APT support is merged. Once https://github.com/cilium/packer-ci-build/pull/57 is merged, will consume the changes in the Cilium Vagrantfiles.

**Comment by ianvernon** [comment]
Fixed by https://github.com/cilium/cilium/pull/4766

**Comment by ianvernon** [comment]
Removing backport label per @tgraf 's comment on the PR: https://github.com/cilium/cilium/pull/4766#issuecomment-403147790
