### ISSUE TITLE
question: how to verify mutual authentication

### ISSUE THREAD

**Issue by Guitarkalle** [cilium/cilium#26902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed cilium (tried 1.14.0-rc.1 and 1.15.0-dev) with helm into an EKS cluster running with aws-vpc CNI chaining.

`
$ helm install cilium ./cilium \
    --namespace kube-system \
    --set cni.chainingMode=aws-cni \
    --set cni.exclusive=false \
    --set enableIPv4Masquerade=false \
    --set routingMode=native \
    --set endpointRoutes.enabled=true
   --set encryption.enabled=true \
   --set encryption.type=wireguard \
    --set authentication.mutual.spire.enabled=true \
    --set authentication.mutual.spire.install.enabled=true
`

I installed via the example here: https://docs.cilium.io/en/latest/network/servicemesh/mutual-authentication/mutual-authentication/#examples

I then followed the example here: https://docs.cilium.io/en/latest/network/servicemesh/mutual-authentication/mutual-authentication-example/

but according to the last section I should get this output, but instead I get nothing from the cilium pod (I checked all of the cilium podsm and I ran the enable debug command)
`
$ kubectl -n kube-system -c cilium-agent logs cilium-9pshw --timestamps=true | grep "Policy is requiring authentication\|Validating Server SNI\|Validated certificate\|Successfully authenticated"
2023-07-04T17:58:28.795760597Z level=debug msg="Policy is requiring authentication" auth_type=spire local_identity=17947 remote_identity=39239 subsys=auth
2023-07-04T17:58:28.800509503Z level=debug msg="Validating Server SNI" SNI ID=39239 subsys=auth
2023-07-04T17:58:28.800525190Z level=debug msg="Validated certificate" subsys=auth uri-san="[spiffe://spiffe.cilium/identity/39239]"
2023-07-04T17:58:28.801441968Z level=debug msg="Successfully authenticated" auth_type=spire local_identity=17947 remote_identity=39239 remote_node_ip=10.0.1.175 subsys=auth
`

Any idea what I might have done wrong?

### Cilium Version

1.14.0-rc.1 and 1.15.0-dev

### Kernel Version

Linux 5.10.184-175.731.amzn2.x86_64

### Kubernetes Version

1.26

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Hi, Can you attach a sysdump from your cluster?

**Comment by Guitarkalle** [comment]
Hello @aditighag  can you advice how I do a sysdump?

when running this command I do see the services, so at least something indicating mtls is there

`kubectl exec -n cilium-spire spire-server-0 -c spire-server -- /opt/spire/bin/spire-server entry show -selector cilium:mutual-auth`

**Comment by Guitarkalle** [comment]
[cilium-sysdump-20230720-225526.zip](https://github.com/cilium/cilium/files/12113955/cilium-sysdump-20230720-225526.zip)
Here is a sysdump

**Comment by sayboras** [comment]
:wave: 

Just curious if you are checking the logs from cilium-ghvt8 pod instead? Kindly note that it is depending on the traffic flow (e.g. destination).

```
$ grep "Policy is requiring authentication\|Validating Server SNI\|Validated certificate\|Successfully authenticated" *
logs-cilium-ghvt8-cilium-agent-20230720-225526.log:2023-07-20T20:54:01.364505382Z level=debug msg="Policy is requiring authentication" key="localIdentity=49577, remoteIdentity=56596, remoteNodeID=0, authType=spire" subsys=auth
logs-cilium-ghvt8-cilium-agent-20230720-225526.log:2023-07-20T20:54:01.366663507Z level=debug msg="Validating Server SNI" SNI ID=56596 subsys=auth
logs-cilium-ghvt8-cilium-agent-20230720-225526.log:2023-07-20T20:54:01.366858197Z level=debug msg="Validated certificate" subsys=auth uri-san="[spiffe://spiffe.cilium/identity/56596]"
logs-cilium-ghvt8-cilium-agent-20230720-225526.log:2023-07-20T20:54:01.370287785Z level=debug msg="Successfully authenticated" key="localIdentity=49577, remoteIdentity=56596, remoteNodeID=0, authType=spire" remote_node_ip=192.168.62.143 subsys=auth
```

**Comment by Guitarkalle** [comment]
@sayboras Hey,

so it seems like it works sometimes. I cannot give the sysdump to my real cluster sadly. But I can 100% confirm that I do not see this log in this cluster.. Can I verify that it uses mtls some other way, especially without debug logging? In the log for my Identity to the pod it just says skipping updating due to not changed

When I look at the CEP it says: 
encryption.key: 255

policy.egress.enforcing: false
policy.ingress.enforcing: falsee

**Comment by Guitarkalle** [comment]
I am suspecting this is due to the timing of when you enable the cilium debug logs? It says to do it at the end of the example, but feels like I only see the logs if I enabled it from the start

**Comment by sayboras** [comment]
debug logs are just one of the ways to verify mutual auth, you can use Hubble (e.g. hubble cli or hubble ui). 

If you want, you can just enable debug log as part of the cilium installation.

**Comment by Guitarkalle** [comment]
That sounds super interesting with hubble. I have used the UI quite a bit but haven't noticed anything about mtls yet. How am I able to see it in the UI?

**Comment by sayboras** [comment]
In hubble cli, you might see the first flow with auth details. Meanwhile, for hubble UI, there will be padlock indicating the mutual auth is enabled between source and destination.
