### ISSUE TITLE
CFP: clustermesh-apiserver deployment support lifecycle and terminationGracePeriodSeconds

### ISSUE THREAD

**Issue by acgs771126** [cilium/cilium#26900]
## Cilium Feature Proposal

**Is your feature request related to a problem?**
Yes.
If you enable cilium clustermesh in AWS environment and also use NLB to expose apiserver,  you will encounter some connection issue when terminating clustermesh-apiserver pod. Because NLB will need some time to draining target(apiserver) but kubernetes already sent signal term to the apiserver pod to close process.

**Describe the feature you'd like**
Helm chart templates/clustermesh-apiserver/deployment.yaml support
[1] `lifecycle` in apiserver and etcd container
[2] clustermesh-apiserver pod support `terminationGracePeriodSeconds`

**(Optional) Describe your proposed solution**

In this scenario, we need to set lifecycle to the apiserver and etcd container and also need to increase clustermesh-apiserver pod's terminationGracePeriodSeconds for handle graceful shutdown.

**Comment by aditighag** [comment]
/cc  @cilium/sig-clustermesh 

Hi @acgs771126 I've tagged the clustermesh team. If you don't see any comments in a week, please reach out on the #development Cilium Slack channel with your proposal.

**Comment by giorio94** [comment]
Hi @acgs771126,

Could you please clarify more the issue you are facing? I mean, agents open persistent connections to the etcd container part of clustermesh-apiserver, and as such it doesn't help waiting some additional time before they terminate. Whenever you restart the clustermesh-apiserver pod, all agents will need to reconnect, and then synchronize the different pieces of information again from scratch. 

As a side note, PRs shall always opened against the main branch, and then subsequently backported to stable versions if necessary.

**Comment by acgs771126** [comment]
Hi @giorio94, thank for your apply.
Let me explain more detail, we are using AWS NLB in front of clustermesh-apiserver pods and also we using aws-loadbalancer-controller to handle pod register/deregister to AWS NLB.
When pod status into terminating, this moment will happend 2 thing as some time
[1] aws-loadbalancer-controller call AWS api to deregister pod in NLB backend(target group) and also target(pod) will into `draining` status to prevent NLB create new connection to deregistered pod.
[2] kubernetes send sigTerm to the pod.

But, NLB still posibble send some in-flight traffic to `draining` target(pod). if apiserver container has been closed at this moment, remote cluster's agent will get some error message like:

```
{"level":"warn","ts":"2023-07-03T11:19:16.146Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc002796000/$cluster_name.mesh.cilium.io:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
```

So we hope that set the preStop hook to sleep a while, the pod can be shut down after the NLB has completed the in-flight traffic.

If still need more explain please kindly let me know, thank you :)

Reference link:
[1] [aws NLB deregister in-flight explain](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#deregistration-delay)

[2] [AWS Blog, about using preStop hook to imprement graceful shutdown applications](https://aws.amazon.com/tw/blogs/containers/how-to-rapidly-scale-your-application-with-alb-on-eks-without-losing-traffic/)

**Comment by giorio94** [comment]
Thanks @acgs771126 for the clarification.

I see your point, but I'm not confifident that delaying the clustermesh-apiserver pod termination would help in this case. 

The fact is that when the clustermesh-apiserver pod is restarted, remote agents need to re-establish a new connection to the new instance, and synchronize again the full state (this is required because it is effectively a different etcd instance). If you delay the shutdown, you'll just delay the point in time in which the re-synchronization is performed, but you don't get rid of it. There will be always a time window in which all agents need to detect that the clustermesh-apiserver is no longer healthy (though an health check mechanism), and re-establish a new connection (during this period, you might see etcd warning messages about connection retries, but that's fine).

It is also worth mentioning that running multiple replicas of the clustermesh-apiserver in parallel is currently not officially supported, and can lead to possible subtle issues and unexpected connection re-establishments.

**Comment by acgs771126** [comment]
@giorio94 you are right, when I set lifecycle.preStop still got same warn log messge from agent.
But I still hope chart can support preStop hook settings, because when I set preStop hook can prevent this metrics `cilium_clustermesh_remote_cluster_readiness_status` from 1(good) to 0(bad) in my case.
I used this metrics to monitor our cluster mesh status.

---

I tested rollout restart deployment `clustermesh-apiserver` in my environment
timeline and result(good=1, bad=0):
[1] 19:15 (with preStop sleep) : good
[2] 19:28 (with preStop sleep) : good
[3] 19:37 (without preStop sleep) : bad 
[4] 19:40 (without preStop sleep) : good 
[5] 19:45 (without preStop sleep) : bad 
![image](https://github.com/cilium/cilium/assets/43164653/25fc2060-7fa8-4c89-9a57-dbaf21d93b41)

**Comment by giorio94** [comment]
Yeah, I personally think that the helm chart extensions you implemented are still valuable additions. I don't think they will be eligible for backporting according to the [backporting criteria](https://docs.cilium.io/en/stable/contributing/release/backports/#id1) though.

**Comment by acgs771126** [comment]
Thank you @giorio94 
It is a great honor to contribute to this project.
