### ISSUE TITLE
Fixes: Renamed the OpLabels field to Labels

### ISSUE THREAD

**Issue by dipankardas011** [cilium/cilium#26923]
https://github.com/cilium/cilium/blob/2390916e5a2e37902730c6de776d2b19d527bd2b/pkg/endpoint/endpoint.go#L155
https://github.com/cilium/cilium/blob/2390916e5a2e37902730c6de776d2b19d527bd2b/pkg/endpoint/restore.go#L429

**Comment by youngnick** [comment]
Thanks for logging this issue @dipankardas011, you raise a good point about some of the Cilium FIXMEs being a bit unclear. However, sorting out all the FIXMEs is probably a larger job, and not a good place to get started. That said, I'm going to ask about FIXMEs and TODOs at a community meeting soon and see if we can bring some of these older ones up to date.

I'd recommend checking out the `good-first-issue` label for things that are good to get started with. See https://github.com/cilium/cilium/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Agood-first-issue for all the available issues.

I'll close this out now though, please comment if you have further questions.

**Comment by dipankardas011** [comment]
sure
