### ISSUE TITLE
BGP CP: Add Support for Multi-Pool IPAM

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#26937]
Currently, BGP CP only supports `kubernetes` IPAM. Add support for running BGP CP with [Multi-Pool IPAM](https://docs.cilium.io/en/v1.14/network/kubernetes/ipam-multi-pool/). The following is an agent (1.14.0-rc.1) log message when trying to run BGP CP with Multi-Pool IPAM:

```sh
level=error msg="Invoke failed" ="cmd.glob..func4 (daemon_main.go:1592)" error="could not build arguments for function \"github.com/cilium/cilium/daemon/cmd\".glob..func4 (/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1592): failed to build promise.Promise[*github.com/cilium/cilium/daemon/cmd.Daemon]: could not build arguments for function \"github.com/cilium/cilium/daemon/cmd\".newDaemonPromise (/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1628): failed to build *agent.Controller: could not build arguments for function \"github.com/cilium/cilium/pkg/bgpv1/agent\".NewController (/go/src/github.com/cilium/cilium/pkg/bgpv1/agent/controller.go:170): failed to build agent.nodeSpecer: received non-nil error from function \"github.com/cilium/cilium/pkg/bgpv1/agent\".NewNodeSpecer (/go/src/github.com/cilium/cilium/pkg/bgpv1/agent/nodespecer.go:42): BGP Control Plane doesn't support current IPAM-mode: 'multi-pool'" subsys=hive
````

**Comment by danehans** [comment]
xref: https://github.com/cilium/cilium/pull/25767

> The only cluster-pool-v2beta feature that is lacking in multi-pool IPAM mode is BGP support. We intend to add BGP support to multi-pool IPAM in Cilium v1.15.

**Comment by YutaroHayakawa** [comment]
In our rough idea, the change should be something look like this.

```
virtualRouters:
- localASN: 65000
  podCIDRPoolSelector:
    foo: bar
```

Then it selectively advertises the route from the specified pool. The CiliumNode should contain the information that which prefix is coming from which pool.
