### ISSUE TITLE
During Cilium restart DualStack service might temporarily remove one IP family endpoints

### ISSUE THREAD

**Issue by brb** [cilium/cilium#26944]
Observed during the upgrade from `v1.13.4` to the `main`:
```
level=debug msg="Kubernetes service definition changed" action=service-updated endpoints="[fd00:10:244:1::3b68]:8000/TCP,[fd00:10:244:3::3153]:8000/TCP,[fd00:10:244::4fee]:8000/TCP" k8sNamespace=cilium-test k8sSvcName=test-conn-disrupt old-endpoints= old-service=nil service="frontends:[10.96.141.20 fd00:10:96::22c1]/ports=[http]/selector=map[app:test-conn-disrupt-server]" subsys=k8s-watcher
...
level=debug msg="Upserting service" backends="[]" l7LBFrontendPorts="[]" l7LBProxyPort=0 loadBalancerSourceRanges="[]" serviceIP="{10.96.141.20 {TCP 8000} 0}" serviceName=test-conn-disrupt serviceNamespace=cilium-test sessionAffinity=false sessionAffinityTimeout=0 subsys=service svcExtTrafficPolicy=Cluster svcHealthCheckNodePort=0 svcIntTrafficPolicy=Cluster svcType=ClusterIP
...
```

Eventually, the agent received an update for the service with IPv4 endpoints. Until then the IPv4 endpoints were removed which interrupted open IPv4 connections to that service.

The issue reproduced in https://github.com/cilium/cilium/pull/26398 when enabling `ipv6`.

I haven't checked whether other versions are impacted too.

**Comment by margamanterola** [comment]
Marking as a 1.14 release blocker for now. We should check whether the same behavior is present in 1.14 or not, but given that we only branched a few weeks ago, there's a high chance that it is.

**Comment by brb** [comment]
I saw the same behavior with v1.14.
