### ISSUE TITLE
documentation for configuring kube-proxy-replacement as part of Gateway API is not correct

### ISSUE THREAD

**Issue by Roguito** [cilium/cilium#26959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Following https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/

using the cilium CLI results in:
➜  ~ cilium install --kube-proxy-replacement=strict
 --helm-set gatewayAPI.enabled=true
unknown flag: --kube-proxy-replacement

Suggestion on slack CNCF's cilium # was to:
--helm-set kubeProxyReplacement=strict

which worked.

Not sure if this is a CLI, documentation or whatever issue so documenting it here.

Thank you Julian Wiedmann for the help. 

### Cilium Version

➜  ~ cilium version
cilium-cli: v0.15.0 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.4
cilium image (stable): v1.13.4
cilium image (running): 1.13.4
➜  ~ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        disabled

Deployment             cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
DaemonSet              cilium             Desired: 3, Ready: 3/3, Available: 3/3
Containers:            cilium             Running: 3
                       cilium-operator    Running: 2
Cluster Pods:          14/14 managed by Cilium
Helm chart version:    1.13.4
Image versions         cilium             quay.io/cilium/cilium:v1.13.4@sha256:bde8800d61aaad8b8451b10e247ac7bdeb7af187bb698f83d40ad75a38c1ee6b: 3
                       cilium-operator    quay.io/cilium/operator-generic:v1.13.4@sha256:09ab77d324ef4d31f7d341f97ec5a2a4860910076046d57a2d61494d426c6301: 2

### Kernel Version

rogue@k8s1:~$ uname -a
Linux k8s1 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

➜  ~ k get nodes
NAME   STATUS   ROLES           AGE     VERSION
k8s1   Ready    control-plane   4d22h   v1.27.3
k8s2   Ready    control-plane   4d20h   v1.27.3
k8s3   Ready    control-plane   4d20h   v1.27.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Hi, Thanks for filing the issue and the suggested fix in the documentation. Are you interested in sending a PR with the fix?

**Comment by Roguito** [comment]
@aditighag I'm not a developer and barely even know the kubernetes ecosystem, I just threw myself into the deep end to learn and thought I would point out some issues I am having along the way.

**Comment by youngnick** [comment]
Thanks again for this @Roguito, and good luck with your journey!

The remaining change here is to update the docs at https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/ to change
```
 --kube-proxy-replacement=strict
```
to
```
--helm-set kubeProxyReplacement=strict
```

In the Installation section using Cilium CLI.

This is a reasonably straightforward change, so I'm marking it as a good-first-issue for someone who wants to get their feet wet with updating documentation.

**Comment by sujoshua** [comment]
I checked the corresponding [documentation source file](https://github.com/cilium/cilium/blob/fa9aaa94b386d505ac00dd4635a7c07907ca51bd/Documentation/network/servicemesh/gateway-api/installation.rst?plain=1#L66) and found that it was correctly modified to
```
$ cilium install |CHART_VERSION| \
   --set kubeProxyReplacement=true \
   --set gatewayAPI.enabled=true
```
in commit a26e2f812094636c73ab45aeb85ff6991e3a04e0.

The document with [latest path](https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/gateway-api/) is the correct version as source code. However, the version with [stable path](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/) which is mentioned in this issue is stale.

So the current issue is that I don't know how to synchronize the correct version to the stable version.

**Comment by dipankardas011** [comment]
is --helm-set same as --set ?

**Comment by sujoshua** [comment]
> is --helm-set same as --set ?

yes，according to the source code

**Comment by youngnick** [comment]
Oh yes, I forgot that this changed in 1.14 as well, sorry.

The correct value is now as @sujoshua says.

**Comment by gailsuccess** [comment]
I think we should close this issue , drawing inspiration from [this comment ](https://github.com/cilium/cilium/issues/26959#issuecomment-1647910814) . 

Here is the [stable version](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/) 
![image](https://github.com/cilium/cilium/assets/157372272/9aafc90b-994c-4bc4-866d-889b564b4b6c)

This is the [latest version](https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/gateway-api/)

![image](https://github.com/cilium/cilium/assets/157372272/94e182b6-f209-4418-8364-6cf9075c810b)

**Both versions have been synchronized .**  We can close the issue.

**Comment by youngnick** [comment]
Thanks for following up @gailsuccess, I really appreciate it. 

And thanks to everyone for your contributions here.

Closing this issue.
