### ISSUE TITLE
TCP packets keep being routed to old IP after daemonset restart

### ISSUE THREAD

**Issue by jmichalek132** [cilium/cilium#26969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. We ran many k8s clusters (EKS)
2. We use traefik (version: `2.9.7`)
3. We use linkerd (version `2.13.3`)
4. We have tracing enabled in traefik
5. We send the traces to opentelmetry collector which is outside the service mesh (traefik is inside the service mesh), it runs as a deamonset so we get 1 pod per node. 
6. The traces are sent using jaeger go client library using thrift_http
7. We sent the traces to opentelemetry pod the node using hostPort
8. Tracing endpoint configuration for traefik
```
              env:
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: JAEGER_ENDPOINT
                  value: http://$(HOST_IP):14268/api/traces?format=jaeger.thrift
```
9. When a rolling update of the opentelemetry daemonset happens, we stop receiving these traces.

### Cilium Version

Client: 1.12.10 628b520 2023-05-16T12:50:44-04:00 go version go1.18.10 linux/amd64
Daemon: 1.12.10 628b520 2023-05-16T12:50:44-04:00 go version go1.18.10 linux/amd64

### Kernel Version

Linux ip-10-25-72-207.ec2.internal 5.15.108 #1 SMP Tue May 9 23:54:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Linux 5.15.108 x86_64

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.6-eks-a5565ad", GitCommit:"895ed80e0cdcca657e88e56c6ad64d4998118590", GitTreeState:"clean", BuildDate:"2023-06-16T17:34:03Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output
Logs from traefik after the rolling update of the opentelemetry daemonset:
```
2023-07-21 00:23:50.937 | time="2023-07-20T22:23:50Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
-- | -- | --
  |   | 2023-07-21 00:23:51.909 | time="2023-07-20T22:23:51Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:23:52.914 | time="2023-07-20T22:23:52Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:23:53.910 | time="2023-07-20T22:23:53Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:23:54.923 | time="2023-07-20T22:23:54Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:23:55.916 | time="2023-07-20T22:23:55Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:23:56.912 | time="2023-07-20T22:23:56Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:23:57.910 | time="2023-07-20T22:23:57Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:23:58.916 | time="2023-07-20T22:23:58Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:23:59.909 | time="2023-07-20T22:23:59Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:24:00.917 | time="2023-07-20T22:24:00Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:24:01.915 | time="2023-07-20T22:24:01Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:24:02.909 | time="2023-07-20T22:24:02Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger |  
  |   | 2023-07-21 00:24:03.909 | time="2023-07-20T22:24:03Z" level=error msg="Tracing jaeger error: failed to flush Jaeger spans to server: error from collector: 502" tracingProviderName=jaeger
```
Excerpt from cilium logs around the time of the rolling update:
```
2023-07-21 00:20:09.485 | level=info msg="Removed endpoint" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=3716 identity=499 ipv4= ipv6= k8sPodName=/ subsys=endpoint |  
-- | -- | --
  |   | 2023-07-21 00:20:09.758 | level=info msg="Removed endpoint" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=612 identity=56201 ipv4= ipv6= k8sPodName=/ subsys=endpoint |  
  |   | 2023-07-21 00:20:09.825 | level=info msg="Removed endpoint" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1193 identity=38855 ipv4= ipv6= k8sPodName=/ subsys=endpoint |  
  |   | 2023-07-21 00:20:22.504 | level=info msg="Synchronized ENI information" numInstances=5 numSecurityGroups=24 numSubnets=18 numVPCs=2 subsys=eni |  
  |   | 2023-07-21 00:21:22.746 | level=info msg="Synchronized ENI information" numInstances=5 numSecurityGroups=24 numSubnets=18 numVPCs=2 subsys=eni |  
  |   | 2023-07-21 00:22:23.255 | level=info msg="Synchronized ENI information" numInstances=5 numSecurityGroups=24 numSubnets=18 numVPCs=2 subsys=eni |  
  |   | 2023-07-21 00:23:05.366 | level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager |  
  |   | 2023-07-21 00:23:05.366 | level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager |  
  |   | 2023-07-21 00:23:05.366 | level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager |  
  |   | 2023-07-21 00:23:05.366 | level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager |  
  |   | 2023-07-21 00:23:05.366 | level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager |  
  |   | 2023-07-21 00:23:05.367 | level=info msg="Garbage collected identity" identity=7954 subsys=cilium-operator-aws |  
  |   | 2023-07-21 00:23:05.378 | level=info msg="Garbage collected identity" identity=21663 subsys=cilium-operator-aws |  
  |   | 2023-07-21 00:23:05.385 | level=info msg="Garbage collected identity" identity=20020 subsys=cilium-operator-aws
```

### Anything else?
After the rolling update, we can see in Hubble ui that there is a constant flow to an IP, trough metrics we figured out that this is the IP of the previous otel instance on the node that was there before the rolling update.
<img width="1700" alt="Screenshot 2023-07-21 at 00 38 57" src="https://github.com/cilium/cilium/assets/7171250/d763f73b-80f5-4199-abae-21496cc6a38e">

When we exec into the cilium pod on the node where this happened an run:
```
cilium endpoint list
cilium service list
```
We don't see the IP of the old otel pod in the output of either of those commands.

We do however find it in the ipcache:
```
# cilium bpf ipcache get 10.24.66.234
10.24.66.234 maps to identity identity=2 encryptkey=0 tunnelendpoint=0.0.0.0 nodeid=0
```
Which we think is the source of the problem.

* This is quite an edge case, this traffic is sent to a hostPort, and there is also a linkerd intercepting the outgoing requests from traefik, it's also routed to a single pod on the node, so before the new one is created during the rolling update there is no valid destination for the traffic.
* We seem to have found a workaround for this, basically sending the traces over udp and enabling `JAEGER_REPORTER_ATTEMPT_RECONNECTING_DISABLED`  which seems to cover this issue.
<img width="959" alt="Screenshot 2023-07-21 at 01 17 28" src="https://github.com/cilium/cilium/assets/7171250/1ec84bb9-d970-4559-9359-c10fca7dee19">

* After re-reading these two issues:
  * https://github.com/cilium/cilium/issues/12859
  * https://github.com/cilium/cilium/issues/24417

I think this could be a duplicate of them but I would appreciate confirmation that's the case. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by margamanterola** [comment]
Your report seems indeed to match #12859, the easiest way of verifying this is disabling socketlb. If all works fine with socketlb disabled, then it is indeed this issue.

**Comment by jmichalek132** [comment]
Hi @margamanterola sorry for the late reply I was on PTO, unfortunately, I am being told by on my side we can't just disable it without some extra work we are not planning on doing right now. We might do it later tough. In the mean since it seems like we are hitting the other issue and we have found a workaround you can close this as a duplicate. If we eventually try disabling that option and confirm it's indeed the case I will leave a comment.

**Comment by margamanterola** [comment]
Thanks Juraj, closing as a Duplicate then.
