### ISSUE TITLE
CT entries are removed/reset every 5 minutes

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2697]
Verify what will be the outcome in the CT by running #2684 while policies are re-fetched from k8s.

**Comment by joestringer** [comment]
Nothing is changing in the policy, this regeneration is being triggered by this periodic trigger so the CT table should not be affected.

Separately, we run garbage collection every 10 seconds. If a connection has not received traffic in the last 5 minutes, we will delete the connection. In this case, if the application sends another packet after this period, we will simply drop the packet. This results in a "stuck" connection. We don't currently attempt to reset the connection.

https://github.com/cilium/cilium/blob/1b0aa61c19fb4cae9f2aea4fbe2adc7b4d8a61a6/bpf/lib/conntrack.h#L31

To avoid connections getting stuck, we can either:
* Make the application send keepalives once every 5 minutes, or
* Send a reset in response to a packet that gets dropped and assume the application will reopen the socket, or
* Increase the timeout, or
* Pick up connections in the middle

**Comment by tgraf** [comment]
> Increase the timeout, or

Let's increase it to 2 hours.

> Send a reset in response to a packet that gets dropped and assume the application will reopen the socket, or

I think this will cause more problems than it solves

> Pick up connections in the middle

I'm open to this. We discussed this earlier. There is no point in protecting the TCP stack so we just replace the logic that currently requires a SYN for a conntrack create and also remove the logic that deletes on RST.

**Comment by tgraf** [comment]
I will give this a shot, this has been bothering me long enough ;-)
