### ISSUE TITLE
CFP: Add cluster filter for cilium dashboards

### ISSUE THREAD

**Issue by pixiono** [cilium/cilium#26982]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

We have several clusters with Cilium installations. We have a central Grafana and would like to use the dashboards to switch between the clusters.

**Describe the feature you'd like**

See above

**(Optional) Describe your proposed solution**

There is a [variable feature in Grafana](https://grafana.com/docs/grafana/latest/dashboards/variables/) which could be used to switch between datasources and clusters.

**Comment by youngnick** [comment]
Thanks for this @pixiono.

What would you like the Cilium Grafana dashboards to do differently? I agree it seems like the variable feature will probably be useful to do something like switch between clusters, but could you give some more detail on what you need?

**Comment by ti-mo** [comment]
Hi @pixiono, this doesn't feel like a topic that needs extensive discussion or planning. If you'd like to add this to the official Cilium Grafana dashboards, feel free to open a PR! This is a really minor change. Closing this out for now.
