### ISSUE TITLE
L2announcement not creating lease

### ISSUE THREAD

**Issue by davehs30** [cilium/cilium#26996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to use the new L2announcement on 1.14.0-rc1.  The 'lease' is not occurring also no 'status' is returned from describe l2announcement.   No arp occurring for the load balanced allocated IP address.  attached are the resource files used
[l2-policy-1.yaml.txt](https://github.com/cilium/cilium/files/12130241/l2-policy-1.yaml.txt)
[hello-world.yaml.txt](https://github.com/cilium/cilium/files/12130242/hello-world.yaml.txt)
[IP-Pool.yaml.txt](https://github.com/cilium/cilium/files/12130244/IP-Pool.yaml.txt)

### Cilium Version

 cilium version
cilium-cli: v0.15.0 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.4
cilium image (stable): v1.13.4
cilium image (running): 1.14.0-rc.1

### Kernel Version

5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

sys dump is to large

### Relevant log output

```shell
kubectl describe l2announcement
Name:         policy1
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  cilium.io/v2alpha1
Kind:         CiliumL2AnnouncementPolicy
Metadata:
  Creation Timestamp:  2023-07-19T15:30:01Z
  Generation:          9
  Resource Version:    4036052
  UID:                 f8d32830-df81-41a0-bb2f-e2d4d121cb8a
Spec:
  External I Ps:  true
  Interfaces:
    ^ens15
  Load Balancer I Ps:  true
  Node Selector:
    Match Labels:
      Role:  worker
  Service Selector:
    Match Labels:
      io.kubernetes.service.name:  hello-world
Events:                            <none>


 kubectl get leases -n kube-system
NAME                                   HOLDER                                                                      AGE
apiserver-e3su4tlnj5c2gybxwyy2uxzl3u   apiserver-e3su4tlnj5c2gybxwyy2uxzl3u_8bb736b9-28b3-4fd5-977a-7087d79f9cca   18d
apiserver-grmwtklhmp2qpbd6skynsk6cqa   apiserver-grmwtklhmp2qpbd6skynsk6cqa_7a4db58d-d8f0-466d-9300-677b3dd8e112   18d
apiserver-t7oqh2epnxkdslv4ib2kutibnm   apiserver-t7oqh2epnxkdslv4ib2kutibnm_0ba338f4-906d-492b-a55d-2dbe40fd1329   18d
cilium-operator-resource-lock          nj-r203-u37-38-k8.online-hosting.cloud-ucfKpCbwLf                           18d
kube-controller-manager                nj-k8-control-1.online-hosting.cloud_19481c7e-f38b-4381-be63-0447f954ec54   18d
kube-scheduler                         nj-k8-control-1.online-hosting.cloud_c787dbbf-c56c-4e55-aa30-e9978536c938   18d
```

### Anything else?

work with Dylan Reimerink via slack on troubleshooting,  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
```

**Comment by chaunceyjiang** [comment]
hi, I'm a beginner. Can i pick up this issue? i want  to learn cilium through this issue.

@aditighag @davehs30 @dylandreimerink

**Comment by youngnick** [comment]
Hi @chaunceyjiang, this one seems like it might take pretty detailed knowledge of Cilium's internals to get started on, I recommend picking up a "good-first-issue"-labelled issue first (see https://github.com/cilium/cilium/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Agood-first-issue  for the list.)

**Comment by youngnick** [comment]
@davehs30, could you create a sysdump using the instructions at https://docs.cilium.io/en/stable/operations/troubleshooting/#reporting-a-problem? Once that's done, I'll mark this for further sig-datapath attention.

**Comment by dylandreimerink** [comment]
> Can i pick up this issue? i want to learn cilium through this issue.

This seems to be a particularly difficult bug, the nature of which isn't yet clear to us, even after extensive attempts over OSS slack. So this one is better left to me as author of the feature.

> sys dump is to large

The sysdump is likely going to be critical for debugging this one, given we tried everything without it already via slack. If it is to large, perhaps you could utilize a service such as WeTransfer or TransferXL to work around the upload limit of github.

**Comment by davehs30** [comment]
[cilium-sysdump-07242023.zip](https://github.com/cilium/cilium/files/12145199/cilium-sysdump-07242023.zip)

reduced the node list to only one control plane node and one worker node.

**Comment by dylandreimerink** [comment]
I think I found the issue. The policy matches on the node label selector `role: worker` which is also present in the example: https://docs.cilium.io/en/latest/network/l2-announcements/#policies.

You would think this is correct because of the cli output:
```
kubectl get nodes -o wide
NAME                                     STATUS   ROLES           AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
nj-k8-control-1.online-hosting.cloud     Ready    control-plane   17d   v1.27.3   10.200.8.128   <none>        Ubuntu 22.04.2 LTS   5.15.0-76-generic   containerd://1.6.21
nj-k8-control-2.online-hosting.cloud     Ready    control-plane   17d   v1.27.3   10.200.8.129   <none>        Ubuntu 22.04.2 LTS   5.15.0-76-generic   containerd://1.6.21
nj-k8-control-3.online-hosting.cloud     Ready    control-plane   17d   v1.27.3   10.200.8.130   <none>        Ubuntu 22.04.2 LTS   5.15.0-76-generic   containerd://1.6.21
nj-r203-u33-34-k8.online-hosting.cloud   Ready    worker          10d   v1.27.3   10.200.8.131   <none>        Ubuntu 22.04.2 LTS   5.15.0-76-generic   containerd://1.6.21
nj-r203-u35-36-k8.online-hosting.cloud   Ready    worker          9d    v1.27.3   10.200.8.132   <none>        Ubuntu 22.04.2 LTS   5.15.0-76-generic   containerd://1.6.21
nj-r203-u37-38-k8.online-hosting.cloud   Ready    worker          9d    v1.27.3   10.200.8.133   <none>        Ubuntu 22.04.2 LTS   5.15.0-76-generic   containerd://1.6.21
```

But when we take a look at the actual node object:
```
- apiVersion: cilium.io/v2
  kind: CiliumNode
  metadata:
    creationTimestamp: "2023-07-10T20:07:12Z"
    generation: 24
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: nj-r203-u33-34-k8.online-hosting.cloud
      kubernetes.io/os: linux
      node-role.kubernetes.io/worker: worker
    name: nj-r203-u33-34-k8.online-hosting.cloud
 [...]
```

There is no `role` label, just the `node-role.kubernetes.io/worker`. For the control plane nodes there is the [`node-role.kubernetes.io/control-plane`](https://kubernetes.io/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-control-plane) label.

So the policy doesn't match any nodes, thus no leases. The fix would be to change the policy to have the following node selector:
```
 nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
``` 
or
```
 nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists
```

So lesson learned, never look at the pretty CLI output, its not the same as looking at the raw YAML :face_exhaling:.

I am also going to update the docs to avoid this confusion in the future. I believe the example in the docs was made this way due to confusion caused by kind configuration we regularly use during development https://kind.sigs.k8s.io/docs/user/configuration/#nodes. But the kind config obviously doesn't translate to the labels on the node.

Please confirm if this work for you.

**Comment by davehs30** [comment]
Confirmation,  this was the problem!  it is working now,  Thank you!
