### ISSUE TITLE
Helm chart: Agent Prometheus annotations set twice (daemonset and service)

### ISSUE THREAD

**Issue by mkilchhofer** [cilium/cilium#26991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

It seems that the Agents are scraped twice when enabling
```yaml
prometheus
  enabled: true
```

The annotations are set on
- `templates/cilium-agent/daemonset.yaml` :
https://github.com/cilium/cilium/blob/4061cdfc83370200e3f9a0c5a782ca17a288ae71/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L44-L45

- and also `templates/cilium-agent/service.yaml` :
https://github.com/cilium/cilium/blob/4061cdfc83370200e3f9a0c5a782ca17a288ae71/install/kubernetes/cilium/templates/cilium-agent/service.yaml#L37-L38

It seems that it is due to this values block here:
https://github.com/cilium/cilium/blob/4061cdfc83370200e3f9a0c5a782ca17a288ae71/install/kubernetes/cilium/values.yaml#L1655-L1659

Is there a reason why this flag is true, the comment abode `proxy:` seems likely that this YAML block is related to Istio.
Shall we file a PR for this and set it to `false`? Or is it perfectly fine from your side and we need to override this in our environment?

### Cilium Version

cilium image (running): v1.12.10

### Kernel Version

unrelated

### Kubernetes Version

unrelated

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
The proxy one might've been deprecated - https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml#L1839. /cc @mhofstetter

**Comment by youngnick** [comment]
@mkilchhofer, when Cilium has certain features turned on, it runs its own version of Envoy (that's the `proxy` config). It seems like the Values comments may not have been updated for a while though, sorry about that.

@mhofstetter, did you change these as part of the Envoy Daemonset efforts?

**Comment by mhofstetter** [comment]
@youngnick  @mkilchhofer 

There exist two Prometheus "configurations" for the agent - one for the agent itself (`.Values.prometheus.*`, default port `9962` & configured on the DaemonSet Pod templates via annotation directly), and one for the Envoy proxy (`:Values.proxy.prometheus.*`, default port `9964` & configured in a separate Service (via annotation) or ServiceMonitor) which runs as process within the same Pod. Envoy automatically gets started once L7 features are configured.

So there shouldn't be any duplicated scrapes on the same port.

With the effort of running Envoy in it's own DaemonSet, this separation should become more clear. Therefore also the rename to `.Values.envoy.prometheus.*` and the deprecation of `.Values.proxy.prometheus.*`. But the old config still exists to support the embedded mode too.

**Comment by mhofstetter** [comment]
> Aah, we don't use the L7 feature so far.
> 
> We see target `DOWN` in Prometheus as it seems not responding on the metrics endpoint in embedded mode when no L7 policy is in place?

yes, that's because the envoy process doesn't get started in the agent pods if no L7 functionality is configured. 

You can check this from within the agent pod (~ following output)

```
home/cilium# ps -x | grep cilium-envoy
    411 ?        Sl     0:00 cilium-envoy -l info -c /var/run/cilium/envoy/bootstrap.pb --base-id 0 --log-format %t|%l|%n|%v
```

In this case I'd recommend to disable proxy (envoy) scraping by setting `.Values.proxy.prometheus.enabled=false`

**Comment by mkilchhofer** [comment]
👍 thanks for your help. I now understand the background.

However I ask myself what is the best solution if partial L7 filtering/visibility is used on some nodes. If I want metrics about this, prometheus will still see some `target DOWNs` on the nodes without envoy embedded is running.

Is the dedicated DaemonSet option documented already?

**Comment by youngnick** [comment]
Yes, it's available at https://docs.cilium.io/en/stable/security/network/proxy/envoy/#enable-and-configure-envoy-daemonset as of Cilium 1.14.
