### ISSUE TITLE
Cilium connectivity Test echo-external-pod doesn't come up

### ISSUE THREAD

**Issue by amitmavgupta** [cilium/cilium#27009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While running cilium connectivity test on an EKS or AKS environment we see that the echo-external-node doesn't come up.

**Pod Failing**
Node-Selectors:              cilium.io/no-schedule=true
Tolerations:                 op=Exists
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  107s  default-scheduler  0/2 nodes are available: 2 node(s) didn't match Pod's node affinity/selector. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.

This is happening since the deployment is missing information about anti-affinity and there is no need for the nodeSelector here because as soon as anti-affinity is added and nodeSelector is removed the pod comes up fine.

**Add**
spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - client
            topologyKey: kubernetes.io/hostname

**Remove**
nodeSelector:
        cilium.io/no-schedule: "true"

**Pod Working fine after the fix**

Node-Selectors:              <none>
Tolerations:                 op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  32s   default-scheduler  Successfully assigned cilium-test/echo-external-node-6cc6759979-pwgjb to ip-192-168-138-131.ap-southeast-2.compute.internal
  Normal  Pulled     32s   kubelet            Container image "quay.io/cilium/json-mock:v1.3.5@sha256:d5dfd0044540cbe01ad6a1932cfb1913587f93cac4f145471ca04777f26342a4" already present on machine
  Normal  Created    32s   kubelet            Created container echo-external-node
  Normal  Started    32s   kubelet            Started container echo-external-node

kubectl get pods -A
NAMESPACE          NAME                                  READY   STATUS    RESTARTS   AGE
cilium-test        client-7b78db77d5-xs597               1/1     Running   0          4m15s
cilium-test        client2-78f748dd67-zq9c5              1/1     Running   0          4m15s
cilium-test        echo-external-node-6cc6759979-pwgjb   1/1     Running   0          69s
cilium-test        echo-other-node-56ddbd8694-j6tnw      2/2     Running   0          4m14s
cilium-test        echo-same-node-5cf949b488-gjwlm       2/2     Running   0          4m15s
cilium-test        host-netns-tg5mz                      1/1     Running   0          4m14s
cilium-test        host-netns-wm7vj                      1/1     Running   0          4m14s

### Cilium Version

1.13.4

### Kernel Version

Linux ip-192-168-114-198.ap-southeast-1.compute.internal 5.10.184-175.731.amzn2.x86_64 #1 SMP Tue Jun 27 21:48:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.25.6

### Relevant log output

[_No response_](https://github.com/cilium/cilium-cli/blob/fdff063b0dafc860105f8370ea98fb59673cff23/connectivity/check/deployment.go#L966-L984)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this issue @amitmavgupta, would you be able to upload a sysdump (using https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection) ? That will help someone be able to more easily help you troubleshoot.

**Comment by NesManrique** [comment]
I also hit this issue, in my case just removing the nodeSelector was enough to make it work. Not sure why that nodeSelector config is needed.

```
# Removed
nodeSelector:
   cilium.io/no-schedule: "true"
```

**Comment by amitmavgupta** [comment]
Hi @youngnick sure. It's attached herewith. Like @NesManrique  said in some cases it works by just editing out the nodeSelector whereas in some scenarios for AKS specifically you need to add the AntiAffinity spec.

The below sysdump is for EKS where the fix was just to remove the nodeSelector
[cilium-sysdump-20230801-101021.zip](https://github.com/cilium/cilium/files/12224707/cilium-sysdump-20230801-101021.zip)

**Comment by NesManrique** [comment]
Just for context I'm using EKS.

**Comment by Aym3nTN** [comment]
Any updates on this so far?

**Comment by joestringer** [comment]
This looks like a CLI bug to me. https://github.com/cilium/cilium-cli/commit/d541be5e7ce5e6336fa1990dd914d9fdc4dbc022 introduced the `echo-external-pod` deployment to run an application on nodes _not_ running Cilium. However, in a standard user environment there are no such nodes. The CLI should detect this and avoid scheduling the Pod or running these tests by default.
