### ISSUE TITLE
CI: K8sAgentPolicyTest Multi-node policy test validates ingress CIDR-dependent L4 connectivity works from the outside before any policies

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#27052]
## CI failure

```
• Failure in Spec Teardown (AfterEach) [270.789 seconds]
K8sAgentPolicyTest
/home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
  Multi-node policy test
  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
    validates ingress CIDR-dependent L4
    /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
      connectivity works from the outside before any policies [AfterEach]
      /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:515

      Found 1 k8s-app=cilium logs matching list of errors that must be investigated:
      2023-07-24T15:08:35.839935660Z level=error msg="Link not found" device=lxc818f597e2860 subsys=datapath-loader
```

[cilium-sysdumps.zip](https://github.com/cilium/cilium/files/12162227/cilium-sysdumps.zip)

https://github.com/cilium/cilium/actions/runs/5646458655/job/15294475107

Triggered from https://github.com/cilium/cilium/pull/25324

**Comment by gandro** [comment]
Seeing this in quote a few pipelines in https://github.com/cilium/cilium/pull/26894/ too:

https://github.com/cilium/cilium/actions/runs/5669512391/job/15362469906
https://github.com/cilium/cilium/actions/runs/5669512391/job/15362474938
https://github.com/cilium/cilium/actions/runs/5669512391/job/15362480059

**Comment by lmb** [comment]
Hit: https://github.com/cilium/cilium/actions/runs/5831523877/job/15815159729

**Comment by giorio94** [comment]
Hit on https://github.com/cilium/cilium/pull/27575: https://github.com/cilium/cilium/actions/runs/6028329882/job/16355456036
