### ISSUE TITLE
Ginkgo: Kafka test issues

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#2707]
I've seen the following error in the last days of testing.

```
    "status": [
      {
        "code": "Failure",
        "message": "Error regenerating endpoint: Unable to allocate ingress redirects: address already in use",
        "state": "ready",
        "timestamp": "2018-02-04T18:51:16Z"
      }
    ]
```
Cilium.log
```
Feb 04 18:51:16 runtime cilium-agent[26466]: level=debug msg="Setting packet marker of socket" fd=39 marker=4277797251
Feb 04 18:51:16 runtime cilium-agent[26466]: level=error msg="Unable to create kafka proxy" error="address already in use" id="47048:ingress:TCP:9092"
Feb 04 18:51:16 runtime cilium-agent[26466]: level=warning msg="Regeneration of endpoint program failed" containerID=95a7c04b49f50ae5016f5bf6a8c2e2b8897bfa23f9f3e4ff3f975914a3c575ca endpointID=47048 error="Unable to allocate ingress redirects: address already in use" policyRevision=88
```

https://github.com/cilium/cilium/blob/a1b540462ff16be31a7d2e22364174c6abe57d07/pkg/proxy/proxy.go#L365-L375

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/1252/

Attached ginkgo logs. 

[RuntimeKafkaKafkaPolicyIngress.zip](https://github.com/cilium/cilium/files/1694358/RuntimeKafkaKafkaPolicyIngress.zip)

**Comment by raybejjani** [comment]
I don't know much about the proxy stuff, but if we're seeing this only in CI I wonder if we accidentally bypass/don't wait for the kafka proxy releasing it's ports and then use the same one. In particular, 9092 is a default port for kafka, I think.

**Comment by tgraf** [comment]
The port in the log is the filter port, not the port the proxy will listen on. I think there are three different possible explanations:
 - The proxy of the given is still shutting down and the port is not available yet but we have already released it from the list of allocated pots
 - The kernel refuses to listen despite using `SO_REUSEPORT`. (Most likely scenario)
 - There is a bug and we allocate the same port twice.

We have plenty of ports. I suggest we spawn a go subroutine and wait for a minute before we remove the port from the list of allocated ports when removing a redirect.

**Comment by eloycoto** [comment]
hi!

finally i can reproduce the issue and i tried to fixed but i think that it's envoy internal.

workflow to reproduce:

```
docker run -dt --net=cilium-net --name zook -l id.zook digitalwonderland/zookeeper
docker policy import l7.json
```

l7.json
```
[{
    "labels": [{"key": "name", "value": "l7-rule"}],
    "endpointselector": {"matchlabels":{"id":"app1"}},
    "ingress": [{
        "fromendpoints": [
            {"matchlabels":{"id":"app2"}}
        ],
        "toports": [{
            "ports": [{"port": "80", "protocol": "tcp"}],
            "rules": {
                "http": [{
                    "method": "get",
                    "path": "/public"
                }]
            }
        }]
    }]
}]
```

when you apply the policy a new port is allocated, and you can see in the `ss -putan` output

```
root@runtime:/home/vagrant# ss -putan | grep 10000
tcp    listen     0      128       *:10000                 *:*                   users:(("cilium-envoy",pid=28927,fd=24))
root@runtime:/home/vagrant#
```

when you delete the policy `cilium policy delete --all` the
`proxy.allocatedports` are empty, and the signal to envoy is sent[0] i can see the call in the envoyproxy[1][2]

[0] https://github.com/cilium/cilium/blob/master/pkg/envoy/envoy.go#l312
[1] https://github.com/cilium/cilium/blob/master/pkg/envoy/grpc.go#l203
[2] https://github.com/cilium/cilium/blob/master/pkg/envoy/streamctrl.go#l236

but if i made an `ss` the port still listen.

so, i think that we do all correct in envoy, but the problem is in the following function:
https://github.com/envoyproxy/envoy/blob/master/source/server/lds_api.cc#l43

in the envoy log i saw that message, but the proxy keep listening:

```
2018-02-07 20:16:52.141][28927][info][upstream] external/envoy/source/server/lds_api.cc:58] lds: remove listener '56326:ingress:tcp:80'
```

The main problem is that cilium will try to allocate another proxy in port
10000, and when it try, it'll fail. this is causing all the test failures in
right now in master. 


Not sure what is the best way to fix this, any idea @jrajahalme @tgraf

**Comment by tgraf** [comment]
I'll let @jrajahalme comment first on Envoy behaviour. We can definitely avoid reusing ports for longer to avoid this problem but we need to understand the behaviour of Envoy. Part of the problem might be that Envoy is not using `SO_REUSEPORT`?

**Comment by jrajahalme** [comment]
@eloycoto It would be helpful to see the Errors in envoy log for the failed re-use of the port 10000. 

Anyway, Envoy does not immediately destroy the listener (and close the socket), see this comment in Envoy sources:
```
      // Once the drain time has completed via the drain manager's timer, we tell the workers to
      // remove the listener.
```

But on the other hand it should be able to pass sockets from draining listeners to new ones when they use the same address and port. I think this should also work across restarts, if we are not using the same Envoy instance in all the tests.

@tgraf is right in that Envoy does not set SO_REUSEPORT, but IMO it would not be safe to allow other programs to listen on the same port.

**Comment by eloycoto** [comment]
Hi, 

I'll post tomorrow, the main issue is when a Kafka proxy starts on that port, not envoy

Regards

**Comment by tgraf** [comment]
I've submitted https://github.com/cilium/cilium/pull/2747 to implement:
 * Delay port released
 * Random port number allocation

**Comment by eloycoto** [comment]
Hi @jrajahalme 

The logs from envoy: 

```
vagrant@runtime:~$ cat /var/run/cilium/cilium-envoy.log                        
[2018-02-08 17:52:34.671][7510][info][main] external/envoy/source/server/server.cc:157] initializing epoch 0 (hot restart version=9.200.16384.127)      
[2018-02-08 17:52:34.729][7510][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:131] cm init: all clusters initialized    
[2018-02-08 17:52:34.729][7510][info][config] external/envoy/source/server/configuration_impl.cc:54] loading 0 listener(s)                              
[2018-02-08 17:52:34.730][7510][info][config] external/envoy/source/server/configuration_impl.cc:92] loading tracing configuration                      
[2018-02-08 17:52:34.730][7510][info][config] external/envoy/source/server/configuration_impl.cc:118] loading stats sink configuration                  
[2018-02-08 17:52:34.731][7510][info][main] external/envoy/source/server/server.cc:330] all clusters initialized. initializing init manager             
[2018-02-08 17:52:34.733][7510][info][main] external/envoy/source/server/server.cc:346] starting main dispatch loop                                     
[2018-02-08 17:52:34.748][7510][info][upstream] external/envoy/source/server/lds_api.cc:50] lds: add/update listener '56326:ingress:TCP:80'             
[2018-02-08 17:52:34.750][7510][info][config] external/envoy/source/server/listener_manager_impl.cc:538] all dependencies initialized. starting workers 
[2018-02-08 17:53:51.201][7510][info][upstream] external/envoy/source/server/lds_api.cc:58] lds: remove listener '56326:ingress:TCP:80'                 
```

The policy was deleted at 17:53 and after a few min the port is still listening: 
```
root@runtime:/home/vagrant# date                                                                                                  
Thu Feb  8 18:03:01 UTC 2018                                                                                                      
root@runtime:/home/vagrant# ss -putan | grep envoy                                                                                
tcp    LISTEN     0      128    127.0.0.1:9901               0.0.0.0:*                   users:(("cilium-envoy",pid=7510,fd=9))   
tcp    LISTEN     0      128       *:18365                 *:*                   users:(("cilium-envoy",pid=7510,fd=24))          
root@runtime:/home/vagrant#                                                                                                       
```

**Comment by ianvernon** [comment]
@eloycoto can we close this since #2796 was resolved?

**Comment by eloycoto** [comment]
Hi @ianvernon 

I've just checked now, and the envoy proxy is still not closing the ports after a while(12 min in this case)

**Comment by eloycoto** [comment]
Close this one.
