### ISSUE TITLE
Hubble threefour parser is not recognizing workloads of remote pods

### ISSUE THREAD

**Issue by marqc** [cilium/cilium#27108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The hubble threefour parser does not recognize the workload metadata of remote pods.

For local pods it has a slim pod cache that is used to find workload metadata. For remote pods it is using ipcache that only has a pod name, namespace and labels. https://github.com/cilium/cilium/blob/main/pkg/hubble/parser/common/endpoint.go#L109

Because of missing workload data in the endpoint in the flow object, the hubble metrics cannot properly label source/destination when using "workload" label context. This is particularly important as pod-short is getting removed in 1.14.

### Cilium Version

all (I checked 1.12, 1.13 and current main)

### Kernel Version

n/a

### Kubernetes Version

1.26.5 but not really relevant

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this @marqc, I think I see what you're getting at, but just to be clear, by "remote pod" you mean "pod in another cluster in a Cluster Mesh"?

**Comment by marqc** [comment]
No. I mean pod in the same cluster running on another node than cilium-agent that observes the flow.

**Comment by michi-covalent** [comment]
is this the same issue as https://github.com/cilium/cilium/issues/25676?

**Comment by marqc** [comment]
> is this the same issue as #25676?

Yes, looks like a duplicate
