### ISSUE TITLE
Endpoint does not inherit CIDR policy automatically

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2711]
Observed in tests on PR: https://github.com/cilium/cilium/pull/2708

Likely caused by changed trigger when policy is being recalculated

**Comment by ianvernon** [comment]
Since the test runs are not kept for a long time, can you please provide the build output / link to logs / artifacts so that they are not lost?

**Comment by tgraf** [comment]
Removing the timeout from the ping, the ping automatically starts working after about 5 minutes. This matches the regular regeneration interval.

```
  }
]
Revision: 23
PING 192.168.254.254 (192.168.254.254) 56(84) bytes of data.
64 bytes from 192.168.254.254: icmp_seq=296 ttl=63 time=0.223 ms
64 bytes from 192.168.254.254: icmp_seq=297 ttl=63 time=0.251 ms
64 bytes from 192.168.254.254: icmp_seq=298 ttl=63 time=0.279 ms
64 bytes from 192.168.254.254: icmp_seq=299 ttl=63 time=0.153 ms
64 bytes from 192.168.254.254: icmp_seq=300 ttl=63 time=0.202 ms
```

**Comment by tgraf** [comment]
In the initial endpoint generation, the endpoint is not regenerated after the initial policy calculation.

**Comment by tgraf** [comment]
The header file is generated before the policy is calculated:
``` go
        if err = e.writeHeaderfile(epdir, owner); err != nil {
                e.Mutex.Unlock()
                return 0, fmt.Errorf("Unable to write header file: %s", err)
        }
```

[...]

``` go
                _, flushEndpointCT, consumersAdd, consumersToRm, err = e.regeneratePolicy(owner, nil)
                if err != nil {
```
