### ISSUE TITLE
Auto Device Detection Should Support Equal Cost Multipath (ECMP) Routing

### ISSUE THREAD

**Issue by nitendra-thakur** [cilium/cilium#27121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Auto device detection cannot detect interfaces when ECMP is used on host. `--devices` option is useful but when all k8s nodes are not using the same interface names; it becomes difficult to install cilium using the the helm chart.

This part of the code can be updated to achieve the desired result. https://github.com/cilium/cilium/blob/v1.13.4/pkg/datapath/linux/devices.go#L275-L277
to:
```
if len(route.MultiPath) == 0 {
			linkInfo := linkInfos[route.LinkIndex]
			linkInfo.hasDefaultRoute = linkInfo.hasDefaultRoute || route.Dst == nil
			linkInfos[route.LinkIndex] = linkInfo
		} else {
			for _, r := range route.MultiPath {
				linkInfo := linkInfos[r.LinkIndex]
				linkInfos[r.LinkIndex] = linkInfo
			}
		}
```
I was able to detect the interfaces correctly after the change. Happy to contribute a PR if that helps.

### Cilium Version

1.13.4

### Kernel Version

5.4.0-29

### Kubernetes Version

v1.24.2

### Anything else?

When ECMP is used, the routes are returned with multiple next hops. This can be tested on a host using `ip route show` command and would display the route with multiple next hops

```
default nhid 26 proto bgp src 10.10.10.10 metric 20
	nexthop via inet6 fc00::1 dev eth102 weight 1
	nexthop via inet6 fc00::1 dev eth101 weight 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this @nitendra-thakur, I'll route this towards the right folks to get some eyes across it.
