### ISSUE TITLE
cleanup: Don't run `sync-to-k8s-ciliumendpoint` for endpoints which don't need it

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#27128]
During a [PR review](https://github.com/cilium/cilium/pull/26894#discussion_r1277291164) we noticed that we are starting the `sync-to-k8s-ciliumendpoint` controller for host and health endpoints. Those endpoints don't have or need a CiliumEndpoint object, so the controllers are running in vain.

We should not start those controllers for endpoints where we know that they don't need a CEP.

**Comment by kwakubiney** [comment]
Can I pick this up?

**Comment by kwakubiney** [comment]
Quick question though, looks like there's a check for the `health` endpoint already & hence the controller does not run for it? Unless I am mistaken. 
See: 
```
// The health endpoint doesn't really exist in k8s and updates to it caused
	// arbitrary errors. Disable the controller for these endpoints.
	if isHealthEP := e.HasLabels(pkgLabels.LabelHealth); isHealthEP {
		scopedLog.Debug("Not starting unnecessary CEP controller for cilium-health endpoint")
		return
	}
```

**Comment by gandro** [comment]
> Quick question though, looks like there's a check for the `health` endpoint already & hence the controller does not run for it? So a similar check for other endpoints which don't have a k8s pod association?
> 
> See:
> 
> ```
> // The health endpoint doesn't really exist in k8s and updates to it caused
> 	// arbitrary errors. Disable the controller for these endpoints.
> 	if isHealthEP := e.HasLabels(pkgLabels.LabelHealth); isHealthEP {
> 		scopedLog.Debug("Not starting unnecessary CEP controller for cilium-health endpoint")
> 		return
> 	}
> ```

I noticed that check too, but I don't this log message being emitted in my local testing. Instead, I see the following log line, indicating that the controller was started for Cilium health nonetheless:

```
level=debug msg="Skipping CiliumEndpoint update because it has no k8s cep name" containerID= containerInterface= controller="sync-to-k8s-ciliumendpoint (3158)" datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=3158 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=debug msg="Controller func execution time: 76.855µs" name="sync-to-k8s-ciliumendpoint (3158)" subsys=controller uuid=0e568f1d-e28e-4dd0-b89f-2f2ae9a78e6b
```

Where endpoint 3158 is the local health endpoint:
```
$ cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                   IPv6   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                     
2068       Disabled           Disabled          1          k8s:node-role.kubernetes.io/control-plane                                          ready   
                                                           k8s:node.kubernetes.io/exclude-from-external-load-balancers                                
                                                           reserved:host                                                                              
3158       Disabled           Disabled          4          reserved:health                                                      10.10.2.172   ready   

```

**Comment by gandro** [comment]
Since we require the pod name (and thereby the cep name) of an endpoint to be available at creation time these days (at latest since https://github.com/cilium/cilium/pull/26242), I think we could probably just check if `e.GetK8sCEPName()` returns an empty string and not start the controller in that case.

**Comment by kwakubiney** [comment]
> Since we require the pod name (and thereby the cep name) of an endpoint to be available at creation time these days (at latest since #26242), I think we could probably just check if `e.GetK8sCEPName()` returns an empty string and not start the controller in that case.

I see the above mentioned approach in the `doFunc()` of the controller params. I am going to move it up so there's no need for `doFunc()` to run in the first place when that condition is true.
