### ISSUE TITLE
SPIRE server missing correct SELinux context and capabilities options

### ISSUE THREAD

**Issue by mjf** [cilium/cilium#27130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Fedora 38
2. deploy Cilium using Helm chart with SPIRE server enabled
3. SPIRE server won't bind socket within `/run` on host because SELinux context is not set properly

### Cilium Version

`1.41.0`

### Kernel Version

`6.4.4-200.fc38.x86_64`

### Kubernetes Version

`1.27.4`

### Sysdump

*N/A*

### Relevant log output

Relevant excerpt from `/var/log/audit/audit.log`:

```yaml
type=AVC msg=audit(1690532456.762:87318): avc:  denied  { write } for  pid=365463 comm="spire-server" name="sockets" dev="tmpfs" ino=43170 scontext=system_u:system_r:container_t:s0:c375,c775 tcontext=system_u:object_r:container_var_run_t:s0 tclass=dir permissive=0
```

### Anything else?

I tried to add the following context as quick fix to the Helm chart for the SPIRE server container:

```yaml
specs:
  containers:
  -
    securityContext:
      seLinuxOptions:
        level: s0
        type: spc_t
```

It effectively resolved the issue and SPIRE server binded the socket.

Also add relevant `securityContext.capabilities` for those enforcing strict policies, please. Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
Thank you for the report and the suggested fix, we are going to look into it.

**Comment by sayboras** [comment]
Thanks for reporting, just curious if you are planning to submit a patch as well.
