### ISSUE TITLE
GatewayAPI feature in helm chart doesn't include CRDs

### ISSUE THREAD

**Issue by jcpunk** [cilium/cilium#27139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I enable GatewayAPI via helm, I do not get the GatewayAPI CRDs that cillium supports.

### Cilium Version

1.14.0

### Kernel Version

Linux testify.fnal.gov 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 29 17:06:27 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Kuberenetes 1.27.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
👋 have you checked the below docs? It's a prerequisite to have related CRDs installed.

https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#prerequisites

**Comment by jcpunk** [comment]
Interesting, I'd expected the CRDs in the chart.  I'd say this can be closed out then.
