### ISSUE TITLE
CFP: Config option to customize the default IP Pool when using MultiPool

### ISSUE THREAD

**Issue by LAMRobinson** [cilium/cilium#27131]
## Cilium Feature Proposal
        
**Describe the feature you'd like**

With the new MultiPool IPAM mode, I want to be able to set the default IP Pools a node uses, so I can have nodes in different datacenters using IP ranges within the over-arching IP summary for that DC.

For example:
 - DC1 - 10.0.0.0/16
    - Node 1 - 10.0.0.0/24
    - Node 2 - 10.0.1.0/24
 - DC2 - 10.1.0.0/16
    - Node 3 - 10.1.0.0/24
    - Node 4 - 10.1.1.0/24

I'd need to be able to apply different default IP pools to different nodes based on Node label.

Pod / Namespace specified IPPools should naturally take priority.

**(Optional) Describe your proposed solution**

As per the [conversation in Slack](https://cilium.slack.com/archives/C1MATJ5U5/p1690535827793529), we already have a Const `PoolDefault` which is used [here](https://github.com/cilium/cilium/blob/d18cf579816ab8a68e341994fc036aa9efba7ac2/pkg/ipam/ipam.go#L233) as the fallback if the pod/namespace doesn't specify a specific pool.

The proposed solution is to change that `const` to a `var` and set it via a new `default-ip-pool (DefaultIPPool)` option in the Daemon Configuration, which would have a default value of `default` (to match current behaviour).

This can then be set at a cluster level, but more importantly for this issue, at a node level using `CiliumNodeConfig`. The above use case could be solved by creating a `CiliumNodeConfig` for each DC, use a label selector like `topology.kubernetes.io/zone == DCX`, and set the new `DefaultIPPool` option to the `IPPool` for `DCX`.

A future enhancement would be to allow the selection of a DefaultIPPool using a labelselector, to avoid hard coding in configs, but that would be a next step / in-addition.

I will log a PR with these changes once I get an initial go ahead here. Please do let me know what I should name this new flag.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by gandro** [comment]
Stale-triage: This feature request is still relevant. @LAMRobinson If you are still willing to contribute this, a PR would be still be welcome, so feel free to go ahead. I think the approach of using a `default-ip-pool`-like option is probably the easiest and simplest for now.

**Comment by chaunceyjiang** [comment]
@gandro Hi,

I'm very interested in this issue. Can I pick up this issue?

**Comment by LAMRobinson** [comment]
@chaunceyjiang happy for you to take this forward from my end, I rather lost track of this.

**Comment by gandro** [comment]
> @gandro Hi,
> 
> I'm very interested in this issue. Can I pick up this issue?

Yes, feel free! I'll assign you. If you have questions, please don't hesitate to reach out on Slack!
