### ISSUE TITLE
Ginkgo CI: remove KubectlPolicyNameLabel constant and use pkg/annotation 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2716]
#2072 adds a new package for annotations, but was not merged when #2648 was merged. Make the Ginkgo tests use the annotation from the package instead of the `KubectlPolicyNameLabel` constant added in the Ginkgo package.

**Comment by eloycoto** [comment]
Already in there: 
https://github.com/cilium/cilium/blob/fce115e3875eeb023c941530407de5cd8134ef72/test/helpers/cons.go#L156
