### ISSUE TITLE
Mutual Auth does not handle having auth table rules removed by non-agent actors

### ISSUE THREAD

**Issue by youngnick** [cilium/cilium#27183]
During some other work, @joestringer noted that, if an entry is deleted from the mutual auth table, then packets will be dropped with a "needs auth" signal to the agent, but because the agent has the authentication cached, it will not take any action.

The agent auth table code should be robust against auth table changes, and should be able to fix the situation.

**Comment by meyskens** [comment]
Fix in https://github.com/cilium/cilium/pull/27241
