### ISSUE TITLE
Network interfaces in external workloads created by Cilium are not persisted

### ISSUE THREAD

**Issue by ma-ble** [cilium/cilium#27186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We use the cluster mesh feature of Cilium and add external workloads. This works as desired via the script generated by the cilium-cli.

```
cilium clustermesh vm install install-external-workload.sh
```

The added external workloads can perform restarts / reboots etc. independently of the kubernetes cluster.

The problem is that after a reboot of the external workload, it can no longer register independently with the cluster mesh. The network interfaces created by the cilium agent when registering the external workload on the cluster mesh, such as "cilium_vxlan" or "cilium_net@cilium_host", no longer exist after a reboot. The cilium agent installed on the external workload does not verify the network interfaces itself after a reboot / restart, but immediately tries to connect to the etcd server via the config.

Could you configure the cilium agent to create the network interfaces (external workloads) in such a way that they survive a reboot?

### Cilium Version

1.14.0-rc.1

### Kernel Version

6.3.11-200.fc38.x86_64

### Kubernetes Version

k3s version v1.26.3+k3s1 (01ea3ff2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by areitz86** [comment]
Still interested in this. Or is this behaviour intended and users need to persist network configuration themselves?
