### ISSUE TITLE
Add service event processing delay metric

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#27198]
One of the [golden signals](https://sre.google/sre-book/monitoring-distributed-systems/) that we seem to be missing is the processing time for Cilium to handle Kubernetes Service and Endpoints events.

One way to implement this would be to wrap [`k8sServiceHandler`](https://github.com/cilium/cilium/blob/fded1abcf310160a9c518b6e25f1ac6059e08a97/pkg/k8s/watchers/watcher.go#L603) with a new metric to measure the time taken to handle an update and delete event.

**Comment by tommyp1ckles** [comment]
@asauber @christarazi Is this still relevant?

**Comment by christarazi** [comment]
Yep, I think so.

**Comment by asauber** [comment]
Unassigning myself as I've shifted to projects and don't want to block this.

**Comment by christarazi** [comment]
Fixed by https://github.com/cilium/cilium/pull/32055
