### ISSUE TITLE
CFP: CI scale testing

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#27196]
## Cilium Feature Proposal

This issue is for tracking a CFP for running scale tests in CI for Cilium. It is currently a WIP. It can be found in this Google Doc: [CFP-2023-07-21: Perf & Scale Testing CI](https://docs.google.com/document/d/12Tlj36UYq93KUJHWG-I5WXVmmHnD-59W79QE9aByMJE/edit?usp=sharing).

**Comment by xmulligan** [comment]
@marseel @learnitall would you mind adding the CFP to the design folder so we can reference in the future? https://github.com/cilium/design-cfps

**Comment by learnitall** [comment]
@xmulligan yep! Will add it in there this week.
