### ISSUE TITLE
CI: Cilium Conformance E2E: allow-all-with-metrics-check

### ISSUE THREAD

**Issue by pippolo84** [cilium/cilium#27194]
## CI failure

Setup & Test (1, 4.19-20230420.212204, iptables, false, vxlan)

📋 Test Report
❌ 1/51 tests failed (1/549 actions), 10 tests skipped, 1 scenarios skipped:
connectivity test failed: 1 tests failed
Test [allow-all-with-metrics-check]:
  ❌ allow-all-with-metrics-check/pod-to-pod/curl-ipv6-3: cilium-test/client2-f59f448f9-q4p22 (fd00:10:244:3::27ad) -> cilium-test/echo-other-node-87b8f7565-j9rjk (fd00:10:244:2::19aa:8080)
Error: Process completed with exit code 1.

https://github.com/cilium/cilium/actions/runs/5728300545/job/15522547810
[cilium-sysdumps.zip](https://github.com/cilium/cilium/files/12231502/cilium-sysdumps.zip)

**Comment by giorio94** [comment]
Hit a very similar one in https://github.com/cilium/cilium/pull/27430: https://github.com/cilium/cilium/actions/runs/5888260082/job/15969113288
Sysdump: [cilium-sysdump-12-20230817-080351.zip](https://github.com/cilium/cilium/files/12368217/cilium-sysdump-12-20230817-080351.zip)
Matrix entry: (12, bpf-next-20230810.091425, none, true, disabled, wireguard, true, snat, true)


```
[=] Test [allow-all-with-metrics-check]
...
  [-] Scenario [allow-all-with-metrics-check/pod-to-pod]
  [.] Action [allow-all-with-metrics-check/pod-to-pod/curl-ipv4-0: cilium-test/client-6b4b857d98-dvnf9 (10.244.2.129) -> cilium-test/echo-other-node-66bdd89578-r7bls (10.244.1.172:8080)]
  [.] Action [allow-all-with-metrics-check/pod-to-pod/curl-ipv6-0: cilium-test/client-6b4b857d98-dvnf9 (fd00:10:244:2::9017) -> cilium-test/echo-other-node-66bdd89578-r7bls (fd00:10:244:1::c9ad:8080)]
  [.] Action [allow-all-with-metrics-check/pod-to-pod/curl-ipv4-1: cilium-test/client-6b4b857d98-dvnf9 (10.244.2.129) -> cilium-test/echo-same-node-55db76dd44-lnbdc (10.244.2.60:8080)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://10.244.2.60:8080/" failed: command terminated with exit code 22

📋 Test Report
❌ 1/55 tests failed (1/583 actions), 6 tests skipped, 0 scenarios skipped:
connectivity test failed: 1 tests failed
Test [allow-all-with-metrics-check]:
  ❌ allow-all-with-metrics-check/pod-to-pod/curl-ipv4-1: cilium-test/client-6b4b857d98-dvnf9 (10.244.2.129) -> cilium-test/echo-same-node-55db76dd44-lnbdc (10.244.2.60:8080)
Error: Process completed with exit code 1.
```

**Comment by danehans** [comment]
Similar issue with https://github.com/cilium/cilium/actions/runs/5931698267/job/16084077285:

```
...
❌ 1/53 tests failed (1/575 actions), 8 tests skipped, 0 scenarios skipped:
Test [to-fqdns]:
  ❌ to-fqdns/pod-to-world/http-to-one.one.one.one-0: cilium-test/client-6b4b857d98-b2kzh (10.244.2.209) -> one.one.one.one-http (one.one.one.one:80)
connectivity test failed: 1 tests failed
Error: Process completed with exit code 1.
```

**Comment by doniacld** [comment]
Assigning myself on it to investigate as the author of the tests.
