### ISSUE TITLE
v1.14.0: "Option --routing-mode cannot be used in combination with --tunnel"

### ISSUE THREAD

**Issue by zadjadr** [cilium/cilium#27213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried adding [1.14.0 to Kubernetes/Kops](https://github.com/kubernetes/kops/pull/15705#issuecomment-1655849069), but received the following error on the cilium operator:

```log
cilium-operator level=fatal msg="Option --routing-mode cannot be used in combination with --tunnel" subsys=config
```

The cilium-config looks [like this](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/15705/pull-kops-e2e-cni-cilium-etcd/1684943371451240448/artifacts/cluster-info/kube-system/configmaps.yaml):

```log
  kind: ConfigMap
  metadata:
    creationTimestamp: "2023-07-28T15:19:55Z"
    labels:
      addon.kops.k8s.io/name: networking.cilium.io
      app.kubernetes.io/managed-by: kops
      role.kubernetes.io/networking: "1"
    name: cilium-config
    namespace: kube-system
  apiVersion: v1
  data:
    agent-health-port: "9879"
    auto-direct-node-routes: "false"
    bpf-ct-global-any-max: "262144"
    bpf-ct-global-tcp-max: "524288"
    bpf-lb-algorithm: random
    bpf-lb-maglev-table-size: "16381"
    bpf-lb-map-max: "65536"
    bpf-lb-sock-hostns-only: "false"
    bpf-nat-global-max: "524288"
    bpf-neigh-global-max: "524288"
    bpf-policy-map-max: "16384"
    cgroup-root: /run/cilium/cgroupv2
    cluster-name: default
    debug: "false"
    disable-cnp-status-updates: "true"
    disable-endpoint-crd: "false"
    enable-bpf-masquerade: "false"
    enable-endpoint-health-checking: "true"
    enable-ipv4: "true"
    enable-ipv4-masquerade: "true"
    enable-ipv6: "false"
    enable-ipv6-masquerade: "false"
    enable-k8s-event-handover: "true"
    enable-l7-proxy: "true"
    enable-node-port: "true"
    enable-remote-node-identity: "true"
    enable-service-topology: "false"
    enable-unreachable-routes: "false"
    etcd-config: |-
      ---
      endpoints:
        - https://api.internal.e2e-pr15705.pull-kops-e2e-cni-cilium-etcd.test-cncf-aws.k8s.io:4003

      trusted-ca-file: '/var/lib/etcd-secrets/etcd-ca.crt'
      key-file: '/var/lib/etcd-secrets/etcd-client-cilium.key'
      cert-file: '/var/lib/etcd-secrets/etcd-client-cilium.crt'
    identity-allocation-mode: crd
    identity-change-grace-period: 5s
    install-iptables-rules: "true"
    ipam: kubernetes
    kube-proxy-replacement: strict
    kvstore: etcd
    kvstore-opt: '{"etcd.config": "/var/lib/etcd-config/etcd.config"}'
    monitor-aggregation: medium
    nodes-gc-interval: 5m0s
    preallocate-bpf-maps: "false"
    sidecar-istio-proxy-image: cilium/istio_proxy
    tofqdns-dns-reject-response-code: refused
    tofqdns-enable-poller: "false"
    tunnel: vxlan
```

I don't see that a "routing-mode" is specified. But it looks like this is set per default somewhere in Cilium 1.14.0?

I have not seen anything in the [Upgrade Guide](https://docs.cilium.io/en/stable/operations/upgrade/#deprecated-options) that might indicate this. Would love some help on this.

### Cilium Version

v1.14.0

### Kernel Version

Linux control-plane-es1-3gpf53 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.27.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by log1cb0mb** [comment]
Its because of this default case:
https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-configmap.yaml#L447

**Comment by zadjadr** [comment]
@log1cb0mb Thank you, I was able to fix part of the problem. Now there is some issues with Openstack, but that should not be related to this issue.
