### ISSUE TITLE
CI: ConformanceAKS (ci-aks) - host-entity

### ISSUE THREAD

**Issue by rastislavs** [cilium/cilium#27236]
## CI failure

Job: https://github.com/cilium/cilium/actions/runs/5747555698/job/15578776141

```
  ❌ Error finalizing 'host-entity': timed out removing policies on Cilium agents: Timeout occurred
...
connectivity test failed: 1 tests failed

📋 Test Report
❌ 1/46 tests failed (0/289 actions), 9 tests skipped, 1 scenarios skipped:
Test [host-entity]:
```
Hit on PR: https://github.com/cilium/cilium/pull/27223

Artifacts:
- [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/12248448/cilium-sysdumps.zip)
- [cilium-junits.zip](https://github.com/cilium/cilium/files/12248450/cilium-junits.zip)

**Comment by giorio94** [comment]
Hit on https://github.com/cilium/cilium/pull/27575: https://github.com/cilium/cilium/actions/runs/6009696701/job/16299643726
