### ISSUE TITLE
Cilium pod can stuck on pending when daemonset is restarting

### ISSUE THREAD

**Issue by sergeyshevch** [cilium/cilium#27243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium pods stuck in a pending state and cannot start on the desired node with the following event

```
1 Insufficient memory. preemption: not eligible due to a terminating pod on the nominated node..
```

I restarted cilium ds and found that some Cilium pods cannot schedule. Cilium has the largest priority but cannot be scheduled because of the terminating pod. Pod cannot terminate because cilium not running on node

### Cilium Version

v1.13.4
v1.14.0 (in different clusters)

### Kernel Version

N/A

### Kubernetes Version

v1.26.6-eks-a5565ad

### Sysdump

N/A

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ldelossa** [comment]
Hey, can you provide a Cilium sysdump for this issue?

**Comment by sergeyshevch** [comment]
@ldelossa I tried to reproduce it again and it's hard to receive same conditions to get Cilium sysdump

I guess I also find some preconditions for easy reproduction of such an issue:
- Small cluster around 3-4 nodes
- Pods with long prestop hooks (30s+ in my case)
- Not enough memory to schedule another cilium pod
- cilium-agent image change
 
So daemonset should try to deploy a new version of the cilium pod when some pod is terminating in this node

**Comment by alex-berger** [comment]
From a recent Slack conversation at https://cilium.slack.com/archives/C53TG4J4R/p1690802884821699

> What is the recommended way to set memory and cpu resource requests and limits for the Cilium Agent Pod’s containers?
> - **(A)** not setting any resources requests and limits at all
> - **(B)** setting only resource requests but no limits
> - **(C)** setting both resource requests and limits
> 
> With (A) we rely on the [fact](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#node-out-of-memory-behavior) that the kubelet sets an oom_score_adj value of -997 for containers in Pods that have system-node-critical [Priority](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority), the same oom_score_adj as is used for Pods with [QoS of Guaranteed](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#guaranteed) (which can otherwise only be achieved by setting resource requests and limits for memory). So far so god. However, without any resource requests set for cpu and especially memory, we can also not guarantee anything and the cilium-agent container might crash (restart) anytime failing to allocate memory if there is high memory pressure on the node. In the worst case this might lead to a [CrashLoopBackOff](https://sysdig.com/blog/debug-kubernetes-crashloopbackoff/) (although, I have do admit I have not yet observed that in the wild on our systems).
> With (B) and (C) we run into problems during upgrades and configuration changes, which cause replacement (deletion/creation) of the Cilium Agent Pods. If the Cilium Agent Pod is replaced on an already existing Node, this might cause a deadlock if there are not enough resources (memory or cpu) available on that Node. In that case Kubernetes scheduler will try to [preempt (evict)](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/) Pods with lower [Priority](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority) to free resources for the Cilium Agent Pod on the corresponding Node, but as that Cilium Agent Pod is not (yet) running the evicted Pods will be stuck in Terminating state as they need a running CNI plugin to properly terminate. With the preempted Pods not terminating, resources are not freed, which prevents Cilium Agent Pod from being scheduled on that Node, … and we have a formidable deadlock.

In our case we opted for **(A)** (not setting any resources requests and limits on the `cilium-agent`) to break the deadlock.

A potential fix is proposed in https://github.com/cilium/cilium/pull/23486

**Comment by sergeyshevch** [comment]
@alex-berger Thanks for sharing! TBH I don't really like idea to run cilium without requests/limits. 
Also as i see https://github.com/cilium/cilium/pull/23486 already merged and exists in my cluster

**Comment by sergeyshevch** [comment]
@alex-berger @borkmann Can enabling setNodeTaints flag help in mitigating such issue?

**Comment by sergeyshevch** [comment]
Not stale

**Comment by lojies** [comment]
> @ldelossa I tried to reproduce it again and it's hard to receive same conditions to get Cilium sysdump
> 
> I guess I also find some preconditions for easy reproduction of such an issue:
> 
> * Small cluster around 3-4 nodes
> * Pods with long prestop hooks (30s+ in my case)
> * Not enough memory to schedule another cilium pod
> * cilium-agent image change
> 
> So daemonset should try to deploy a new version of the cilium pod when some pod is terminating in this node

you can see how to reproduct this in my issue.i think it is the same with calico.
