### ISSUE TITLE
CI: linuxPrivilegedIPv4AndIPv6TestSuite/TestNodeChurnXFRMLeaks

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#27268]
## CI failure

Hit on https://github.com/cilium/cilium/pull/27242: https://github.com/cilium/cilium/actions/runs/5752260375/job/15592941475

```
--- FAIL: Test (227.53s)
    --- FAIL: Test/linuxPrivilegedIPv4AndIPv6TestSuite (3.51s)
        --- FAIL: Test/linuxPrivilegedIPv4AndIPv6TestSuite/TestNodeChurnXFRMLeaks (1.06s)
            node_linux_test.go:809: 
                ... value *errors.joinError = &errors.joinError{errs:[]error{(*errors.joinError)(0xc0010e0180)}} ("failed to enable ipsec with out IPv6 using local IP ::/0, rem 2001:aaaa::/64, spi 0: unable to replace remote state: file exists")
```

**Comment by julianwiedmann** [comment]
@pchaigno @tommyp1ckles FYI - I reproduced locally, this fails when https://github.com/cilium/cilium/pull/27212 and https://github.com/cilium/cilium/pull/25994 are put together.

**Comment by brb** [comment]
Looks like https://github.com/cilium/cilium/pull/25994 helped to expose an error which previously was visible only in logs.

**Comment by brb** [comment]
The test tries to insert the following XFRM states:

1. `destinationIP="<nil>" sourceIP=1.1.1.1 spi=6` 
2. `destinationIP="<nil>" sourceIP="face::1" spi=6`

The second conflicts with the first one, thus the test failure.
