### ISSUE TITLE
cilium on ubuntu 22.04

### ISSUE THREAD

**Issue by nadeem414** [cilium/cilium#27279]
I am running cilium fine until I added a Ubuntu 22.04 node to the cluster. since then the node cilium pod is in crashloop state for that node only. I seen other issues but I dont see a clear resolution to those problems. my version are following.
cilium-cli: v0.15.0 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.4
cilium image (stable): v1.14.0
cilium image (running): 1.13.4

**Comment by nadeem414** [comment]
`cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             2 errors
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        disabled

Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet              cilium             Desired: 4, Ready: 3/4, Available: 3/4, Unavailable: 1/4
Containers:            cilium             Running: 4
                       cilium-operator    Running: 1
Cluster Pods:          20/20 managed by Cilium
Helm chart version:    1.13.4
Image versions         cilium             quay.io/cilium/cilium:v1.13.4@sha256:bde8800d61aaad8b8451b10e247ac7bdeb7af187bb698f83d40ad75a38c1ee6b: 4
                       cilium-operator    quay.io/cilium/operator-generic:v1.13.4@sha256:09ab77d324ef4d31f7d341f97ec5a2a4860910076046d57a2d61494d426c6301: 1
Errors:                cilium             cilium          1 pods of DaemonSet cilium are not ready
                       cilium             cilium-7gn2x    unable to retrieve cilium status: container cilium-agent is in CrashLoopBackOff, exited with code 2: level=info msg="Restored services from maps" f`

**Comment by dylandreimerink** [comment]
Thanks for this report, would you be able to grab a sysdump file and upload it please so we can better debug the issue? (Using https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection)

**Comment by nadeem414** [comment]
[cilium-sysdump-20230804-082431.zip](https://github.com/cilium/cilium/files/12262932/cilium-sysdump-20230804-082431.zip)
hi @dylandreimerink, here is the sysdump file.

**Comment by nadeem414** [comment]
I added the sysdump but no action so far. @dylandreimerink did had a chance to look at the sysdump files.
