### ISSUE TITLE
Spire helm chart - static busy box image

### ISSUE THREAD

**Issue by dvbthijsvnuland** [cilium/cilium#27282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Helm chart issue:
The busybox image in both the statefulset and daemonset templates in the spire-agent and spire-server are static (docker.io)
They should be represented in the values file so you can override them with (for instance) a private repository.

### Cilium Version

1.14

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dvb-simp** [comment]
@eegseth The PR only addresses the Statefulset, would you mind incorporating the same change to the daemonset image as well?

**Comment by dvb-simp** [comment]
@dylandreimerink  is there a way to move this change forward? :) this way we could use the helm chart as is, in stead of hacking into it.

**Comment by dylandreimerink** [comment]
The PR needs a rebase, that is the responsibility of the author. I re-requested a review since the comments have been resolved. Please understand that the review load can be quite high sometimes, so it might just take a few days for all reviewers to find time in their schedule.

**Comment by meyskens** [comment]
This was fixed in https://github.com/cilium/cilium/pull/27621 :)
