### ISSUE TITLE
CFP: Intrusion Detection

### ISSUE THREAD

**Issue by Jiawei0227** [cilium/cilium#27308]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

We are looking for a Kubernetes native IDPS solution and are currently integrating with Cilium. Just wondering if there are any thoughts on enhance cilium with some Intrusion detection/prevention support.

**Describe the feature you'd like**

A k8s native intrusion detection system integrated with cilium natively

**(Optional) Describe your proposed solution**

I do not have any ideas how this can be done but I am happy to do some research if there are folks interested and share some thoughts

**Comment by ldelossa** [comment]
Yes @Jiawei0227 please take a look at Tetragon and see if this fulfills your need. If it does you can close this CFP. If it does not please define why

**Comment by Jiawei0227** [comment]
@mhulscher @ldelossa Thanks for pointing me out to tetragon!
I think I am looking more like traditional signature based detection. For example, if we have some existing `snort` or `suricata` rulesets and I want to apply the same ruleset somewhere along the datapath.  Do you think this makes sense or not?
