### ISSUE TITLE
Helm Chart Incompatible with Server-Side Applies

### ISSUE THREAD

**Issue by jb-2020** [cilium/cilium#27325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The following error occurs when setting `routingMode` while installing the chart using server-side applies[1]:

```
Helm install failed: 
error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 103: mapping key "routing-mode" already defined at line 101
```

Root cause is this bit of logic: https://github.com/cilium/cilium/blob/fc9c8a99e2fc0d9b37e18362f2694b3e72d1cd97/install/kubernetes/cilium/templates/cilium-configmap.yaml#L445-L453

Setting `routingMode` explicitly results in:
```
  # Default case
  routing-mode: "tunnel"
  tunnel-protocol: "vxlan"
  routing-mode: "native"
```

This method of installation is less forgiving than the typical client-side install and duplicated keys are not tolerated (see error message above).  Server-side applies is a requirement when using Flux[2].

The helm chart should be updated to not include any duplicated keys regardless of configuration specified by the user.

[1] https://kubernetes.io/docs/reference/using-api/server-side-apply/
[2] https://github.com/fluxcd/flux2

### Cilium Version

v1.14.0

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by weikinhuang** [comment]
I am still encountering this issue as well. A quick validation with kubeconform might be good to add to the chart ci.

**Comment by jimethn** [comment]
Still needed
