### ISSUE TITLE
Working with two NIC and VRFs on nodes level

### ISSUE THREAD

**Issue by drustan** [cilium/cilium#27383]
Hi everyone,

Before considering the deployment of two distinct K8S cluster, I'm looking into trying to setting up a Kubernetes cluster handling two networks. I would like to have a strict network isolation, every Kubernetes node having two network interfaces, each in their own VRF. With the help of Kube-VIP, I would have two VIP, one for each network and each of these VIP would be linked to their own Ingress controller.

My question is, how would this work if each interface is in a different VRF? Would I need several Cilium instances? Like two Cilium processes by node, each bound to its own routing table (VRF). Is this even feasible?

I'm open to any suggestions you may have. Thanks in advance for your help!

**Comment by ti-mo** [comment]
Hi @drustan. It's not currently possible to run multiple Cilium agents per node. I feel like the core of this issue isn't necessarily Cilium-related, but more of a generic k8s networking question, so I'll close this issue for now (this is a Cilium issue/bug tracker).

I doubt you'll get a meaningful response here, maybe give the #kubernetes channel on Cilium Slack a try? Thanks.
