### ISSUE TITLE
Deadlock in 1.12 ipcache metadata

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#27382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Deadlock in ipcache was introduced by https://github.com/cilium/cilium/pull/26958
The version of Cilium with this change has not been released yet. 

My current understanding of it:
- PR introduced delete in metadata
- This delete needs to acquire metadata mutex
- Metadata delete operation is performed under IPCache lock https://github.com/meyskens/cilium/blob/9be3b287363bbb2c1ef3160aa5e4bb2c236574fa/pkg/ipcache/ipcache.go#L576
- This is in contradiction to comment https://github.com/cilium/cilium/blob/835531431df58070c70699ca4fad5ffc935153a8/pkg/ipcache/metadata.go#L44-L46

### Cilium Version

1.12 branch (unreleased)

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Fixed via https://github.com/cilium/cilium/pull/27406 .
