### ISSUE TITLE
GC interval auto calculation is wrong when woken up by the map full signals

### ISSUE THREAD

**Issue by Jiang1155** [cilium/cilium#27405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

During operation, we sometimes saw CT table is about full and not cleaned up for about an hour. Clients see some http errors.

After some investigation, I noticed that there are 15 "Conntrack garbage collector interval recalculated" messages printed out in within one minute. As a result, the newInterval became larger and larger. Starting from 2 min to 12h.  And then there was no GC messages for about an hour later. During that time, the system was in fact under a heavy load, and the GC should be invoked more frequently. 

I think one reason for this issue is because of this line:
`case <-ctTimer.After(ctmap.GetInterval(maxDeleteRatio)):`

https://github.com/cilium/cilium/blob/main/pkg/maps/ctmap/gc/gc.go#L137

When the gc is woken up by signal, the select will be done and then go to next for loop iteration. In the next iteration, the GetInterval will be called again even if it has not expired last time. As a result, the time interval will become longer and longer which contradicts the intention to run gc when in heavy load. The GetInterval() has a wrong assumption that it will be only called after timer expires.

To fix it, one idea is to pass an additional argument to GetInterval() to let it know if it is woken by signal or not. If yes, no need to calculate interval again ( or make interval even smaller?)

E.g
```
           select {
			case x := <-wakeup:
				triggeredBySignal = true
				ipv4 = false
				ipv6 = false
				if x == signal.SignalProtoV4 {
					ipv4 = true
				} else if x == signal.SignalProtoV6 {
					ipv6 = true
				}
				
				// Drain current queue since we just woke up anyway.
				for len(wakeup) > 0 {
					x := <-wakeup
					if x == signal.SignalProtoV4 {
						ipv4 = true
					} else if x == signal.SignalProtoV6 {
						ipv6 = true
					}
				}
+                               wakeupBySig = true
			case <-ctTimer.After(ctmap.GetInterval(mapType, maxDeleteRatio, wakeupBySig)):
				ipv4 = ipv4Orig
				ipv6 = ipv6Orig
			}
```

 

### Cilium Version

Found issue on 1.11, but same code exists in 1.13

### Kernel Version

5.10

### Kubernetes Version

1.21

### Relevant log output

```shell
2023-08-07T12:32:17.229979814Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.03000640869140625 newInterval=2m33s subsys=map-ct
2023-08-07T12:32:27.431066097Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.009735107421875 newInterval=3m50s subsys=map-ct
2023-08-07T12:32:37.363001371Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.009246826171875 newInterval=5m45s subsys=map-ct
2023-08-07T12:32:47.565375935Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.00983428955078125 newInterval=8m38s subsys=map-ct
2023-08-07T12:32:50.354593794Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.00250244140625 newInterval=12m57s subsys=map-ct
2023-08-07T12:32:54.902820713Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.00295257568359375 newInterval=19m26s subsys=map-ct
2023-08-07T12:32:56.351881255Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.00177001953125 newInterval=29m9s subsys=map-ct
2023-08-07T12:32:58.057273550Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.001628875732421875 newInterval=43m44s subsys=map-ct
2023-08-07T12:32:59.544525575Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.00225830078125 newInterval=1h5m36s subsys=map-ct
2023-08-07T12:33:07.821605228Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.007526397705078125 newInterval=1h38m24s subsys=map-ct
2023-08-07T12:33:09.770301588Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.00151824951171875 newInterval=2h27m36s subsys=map-ct
2023-08-07T12:33:10.997402343Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0007171630859375 newInterval=3h41m24s subsys=map-ct
2023-08-07T12:33:21.048709683Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.00943756103515625 newInterval=5h32m6s subsys=map-ct
2023-08-07T12:33:27.163267694Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.00713348388671875 newInterval=8h18m9s subsys=map-ct
2023-08-07T12:33:28.986784651Z level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.001415252685546875 newInterval=12h0m0s subsys=map-ct
```

### Anything else?

Tested the time.After() function behavior with this simple program, which can run from here: https://go.dev/tour/concurrency/5

```
package main

import "fmt"
import "github.com/cilium/cilium/pkg/inctimer"
import "time"

func cal() (inter time.Duration) {
	fmt.Println("in cal")
	inter = 5 * time.Second
	return 
}

func fibonacci(c, quit chan int) {
	x, y := 0, 1
	ctTimer, _ := inctimer.New()
	
	for {
		select {
		case c <- x:
			x, y = y, x+y
		case <-ctTimer.After(cal()):
			fmt.Println("after 5 sec")
		case <-quit:
			fmt.Println("quit")
			return
		}
	}
}

func main() {
	c := make(chan int)
	quit := make(chan int)
	
	go func() {
		for i := 0; i < 10; i++ {
			fmt.Println(<-c)
		}
		quit <- 0
	}()
	fibonacci(c, quit)
}
```

And the output is this:
```
1
2
in cal
in cal
3
5
in cal
in cal
8
13
in cal
in cal
21
34
in cal
quit
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
Thanks for the report!

cc'ing @cilium/sig-datapath to suggest approaches to resolve this.

**Comment by Jiang1155** [comment]
> Thanks for the detailed report!
> 
> While I'm working on an approach that will consider the actual time passed between GC runs to recalculate the interval, I'm bothered by the fact that GC is constantly triggered by a signal, but deleteRatio is really small every time, meaning that few items were actually cleared up. While the interval update logic is indeed wrong, fixing it will unlikely help in your use case, because the CT table will still be full.
> 
> Could you check which signal get emitted? It can be either ct_fill_up or nat_fill_up, and it's seen in the metrics. It can give a clue to what's going on.

I don't remember whether it is ct or nat fill up back in August, but I have a similar issue recently and it is NAT fill up. In the recent issue, I think something is wrong between CT and NAT. From my understanding, NAT is cleaned up when cleaning CT. If somehow CT entry was cleaned but not the corresponding NAT entry, then that NAT entry will stay there forever？ If you could share more details about how they should connect together, it will be great. I can open a new issue for that too. But I have some private patch in the cilium we are using and I am not sure if that is related or not yet.

**Comment by matveybrant** [comment]
I think I am seeing the same issue with 1.11.9 - same gc interval recalculated messages

I see 

`cilium_datapath_signals_handled_total                 data="ipv4" signal="nat_fill_up" status="received"                                                                                                                                                                                                                88.000000`



`level=info msg="Deleted orphan SNAT entries from map" ctMapIPVersion=0 egressDeleted=14 ingressAlive=92680 ingressDeleted=14 subsys=ct-gc
level=info msg="Deleted orphan SNAT entries from map" ctMapIPVersion=0 egressDeleted=2 ingressAlive=112734 ingressDeleted=2 subsys=ct-gc
level=info msg="Deleted orphan SNAT entries from map" ctMapIPVersion=0 egressDeleted=1 ingressAlive=98156 ingressDeleted=1 subsys=ct-gc
level=info msg="Deleted orphan SNAT entries from map" ctMapIPVersion=0 egressDeleted=1 ingressAlive=105242 ingressDeleted=1 subsys=ct-gc
level=info msg="Deleted orphan SNAT entries from map" ctMapIPVersion=0 egressDeleted=2 ingressAlive=92882 ingressDeleted=2 subsys=ct-gc
level=info msg="Deleted orphan SNAT entries from map" ctMapIPVersion=0 egressDeleted=2 ingressAlive=99795 ingressDeleted=2 subsys=ct-gc
level=info msg="Deleted orphan SNAT entries from map" ctMapIPVersion=0 egressDeleted=2 ingressAlive=112859 ingressDeleted=2 subsys=ct-gc
level=info msg="Deleted orphan SNAT entries from map" ctMapIPVersion=0 egressDeleted=1 ingressAlive=102816 ingressDeleted=1 subsys=ct-gc
level=info msg="Deleted orphan SNAT entries from map" ctMapIPVersion=0 egressDeleted=1 ingressAlive=110303 ingressDeleted=1 subsys=ct-gc`

`level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0268111 newInterval=7m30s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0383555 newInterval=11m15s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0458672 newInterval=16m53s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0314568 newInterval=25m20s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0495692 newInterval=38m0s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.004357 newInterval=57m0s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0017612 newInterval=1h25m30s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0001389 newInterval=2h8m15s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0144785 newInterval=3h12m23s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0220349 newInterval=4h48m35s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0184478 newInterval=7h12m53s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0038136 newInterval=10h49m20s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0205263 newInterval=12h0m0s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.3999241 newInterval=7h12m3s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0485068 newInterval=10h48m5s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.4330668 newInterval=6h7m25s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0429988 newInterval=9h11m8s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0150085 newInterval=12h0m0s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.3122205 newInterval=8h15m12s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0292101 newInterval=12h0m0s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.3578556 newInterval=7h42m21s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0482851 newInterval=11h33m32s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0132158 newInterval=12h0m0s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.2689871 newInterval=8h46m20s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0302574 newInterval=12h0m0s subsys=map-ct`

Could this cause any performance issues?  I am seeing one of the connection tracking tables running very close to full in some externally reachable pods often.

**Comment by Jiang1155** [comment]
> Could this cause any performance issues? I am seeing one of the connection tracking maps running very close to full in some externally reachable pods often.

I think the answer is yes at least in my case. One of the consequence is that the GC does not get clean up and becomes full after some time. Then it depends on how big you set the CT or NAT table size. If the table size is relatively big, then it cause endpoint creation or pod starting to be slow. But I did not figure the exact code path yet.

**Comment by Jiang1155** [comment]
> > If somehow CT entry was cleaned but not the corresponding NAT entry
> 
> We hit that kind of a bug recently, the bugfix was merged about a week ago: [0a080d3](https://github.com/cilium/cilium/commit/0a080d3f504d1d838be231e33622ff9222d0cb4a)
> 

Good to know. Thanks for sharing.

> Could you share what exact versions of Cilium you tested? I'm especially interested in the 1.11.x one to figure out if it contains the affected code.
> 

based on 1.11.1

> > then that NAT entry will stay there forever？
> 
> Not really, because [PurgeOrphanNATEntries](https://github.com/cilium/cilium/blob/f99f1289ce87f03d3a3b02d80b1a47831e3ca45a/pkg/maps/ctmap/gc/gc.go#L263) is supposed to GC it upon receiving the nat_fill_up signal (your case).
> 
> Do you have any `Deleted orphan SNAT entries from map` messages in the log?
> 

Probably not. I don't remember seeing those logs.

> > But I have some private patch in the cilium we are using and I am not sure if that is related or not yet.
> 
> Do you mean you applied some patch that might affect the GC logic? Is it possible that you share it (maybe privately)?

The code is here: https://github.com/Jiang1155/cilium/tree/dsr-ipip-v2  (btw, I try to push it to upstream, but got some comments and I did not get  a chance to fix them yet ).

I did not change GC logic, but I made some changes related to the nat table entry and wondering if that may cause issues. 

Also, I just found this patch https://github.com/cilium/cilium/commit/790465042b91cce78678b816f88387bdf5d95905https://github.com/cilium/cilium/commit/790465042b91cce78678b816f88387bdf5d95905
 which is missing in my code base and we are using  DSR (but with ipip ). I am thinking maybe I need that patch. 

But in my case, the orphan NAT entries are like this:
 
`TCP IN <IP:PORT> -> <IP:PORT> XLATE_DST <IP:PORT> Created=9400363sec HostLocal=0`

And I am not sure if that entry is created by my patch or not. I may try to dig more when I have some cycles.

**Comment by Jiang1155** [comment]
> Could this cause any performance issues? I am seeing one of the connection tracking maps running very close to full in some externally reachable pods often.

btw, if your only problem is that GC sometimes does not run for a long time (12h max by default ), you can also consider backing port this patch https://github.com/cilium/cilium/commit/3ea5e8c5e9c3e77b23eea30ed08200ade03e2d98 and set max interval to a smaller value.

**Comment by julianwiedmann** [comment]
Please test with a build that contains https://github.com/cilium/cilium/pull/28657 (it's queued up for 1.15 backports) :).

**Comment by Jiang1155** [comment]
> Sorry for the long response.
> 
> > > Could you share what exact versions of Cilium you tested? I'm especially interested in the 1.11.x one to figure out if it contains the affected code.
> > 
> > 
> > based on 1.11.1
> 
> It doesn't contain the affected code yet (it's older), but [Jiang1155@80e5857](https://github.com/Jiang1155/cilium/commit/80e58574f12d0d3094d63411d9b2f428238e4c3d) might indeed need a similar fix to the GC logic. So, basically:
> 
> > I did not change GC logic, but I made some changes related to the nat table entry and wondering if that may cause issues.
> 
> Yes, it might.
> 
> > btw, if your only problem is that GC sometimes does not run for a long time (12h max by default ), you can also consider backing port this patch [3ea5e8c](https://github.com/cilium/cilium/commit/3ea5e8c5e9c3e77b23eea30ed08200ade03e2d98) and set max interval to a smaller value.
> 
> Does it actually help any of you? As as I understand from the logs above, the GC runs aren't effective, even though frequent (before the interval rises). Would it help to cap the max interval to a smaller value and run the GC more often if it doesn't clean up what it should? I believe not.
> 
> By the way, regarding [Jiang1155@80e5857](https://github.com/Jiang1155/cilium/commit/80e58574f12d0d3094d63411d9b2f428238e4c3d), I'm curious, what is wrong with the standard IPIP mode, why do you need to change that: [Jiang1155@80e5857#diff-304969c111195cf4253b336fc67c9891f17b91d49738a0cc334333ac11e84b9eL1249-R1254](https://github.com/Jiang1155/cilium/commit/80e58574f12d0d3094d63411d9b2f428238e4c3d#diff-304969c111195cf4253b336fc67c9891f17b91d49738a0cc334333ac11e84b9eL1249-R1254)?
> 

About this question: what is wrong with the standard IPIP mode, why do you need to change that.

Current IPIP only support lb-only mode, it cannot be used for CNI usage.  At least need some code to decap.  Another reason to change IPIP is to support nodeport. But I may used a different way to support nodeport, like only external IP uses IPIP DSR, and nodeport still uses SNAT. 

> Also, 1.11.1 and 1.11.9 are very old versions of the 1.11 branch, which itself is no longer supported, and chasing bugs there is somewhat painful, especially with a custom patch that may affect the relevant behavior. May I ask you to try to reproduce the bug on the latest version, ideally on main or 1.14.5, or at least on 1.12.17? It's needed to make sure that all known bugfixes are backported. Is it possible to try that?


I will try to test on newer versions.

btw, I am not sure if this comment will close the issue or not. I did not test that #28657  yet.
