### ISSUE TITLE
Check for cilium.sock in /healthz endpoint

### ISSUE THREAD

**Issue by thorn3r** [cilium/cilium#27436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The cilium health-server relies on cilium.sock to query the cilium-agent daemon for status information to report health. If this file is deleted, the daemon's `/healthz` endpoint will still return 200, but tools making use of the health-server such as the agent's embedded cilium CLI will not be able to return any status information. The health-server will also be unable to check the health of other nodes in the cluster, and cilium-agent will produce warning logs as follows:

```
level=error msg="unable to get cluster nodes" error="unable to get nodes' cluster: Get \"http://localhost/v1/cluster/nodes\": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory" subsys=health-server
```

### Cilium Version

v1.14.0

### Kernel Version

5.15.0-1033-gke

### Kubernetes Version

v1.26.5-gke.1400

### Relevant log output

```shell
level=error msg="unable to get cluster nodes" error="unable to get nodes' cluster: Get \"http://localhost/v1/cluster/nodes\": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory" subsys=health-server
```

```
root@xxx:/home/cilium# cilium status
Get "http://localhost/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
```

**Comment by chaunceyjiang** [comment]
I‘m a beginner and I would like to try fixing this issue. Can it be assigned to me?

**Comment by aanm** [comment]
I've assigned it to you @chaunceyjiang
