### ISSUE TITLE
CFP:  Metrics for CT_SERVICE 

### ISSUE THREAD

**Issue by wenlxie** [cilium/cilium#27452]
## Feature request

We are using cilium xdp geneve dsr mode as L4 load balancer. The metrics like connections/pkts/bytes of the vip and vip's backends are very important to provide observation for the products.

If cilium can support this, it should a really helpful feature .

We used IPVS before, here are the example statistics that provided by IPVS:

Examples for ipvs:
http://www.austintek.com/LVS/LVS-HOWTO/HOWTO/LVS-HOWTO.monitoring_lvs.html

```
ipvsadm -L -t smtp:smtp --stats 
Prot LocalAddress:Port               Conns   InPkts  OutPkts  InBytes OutBytes   -> RemoteAddress:Port TCP  
smtp.uio.no:smtp              1508879 38457326        0   10461M        0   
-> mail-mx6.uio.no:smtp           374117  9490846        0    2664M        0   
-> mail-mx3.uio.no:smtp           377646  9961956        0    2543M        0   
-> mail-mx2.uio.no:smtp           378502  9288837        0    2707M        0   
-> mail-mx1.uio.no:smtp           378614  9715687        0    2546M        0 

# ipvsadm -L -t smtp:smtp --rate Prot LocalAddress:Port                 CPS    InPPS   OutPPS    InBPS   OutBPS   -> RemoteAddress:Port TCP  smtp.uio.no:smtp                    7       85        0    20480        0   
-> mail-mx6.uio.no:smtp                1       17        0     1126        0   
-> mail-mx3.uio.no:smtp                1       17        0     2023        0   
-> mail-mx2.uio.no:smtp                2       26        0     6681        0   
-> mail-mx1.uio.no:smtp                2       25        0    10650        0
```

**Comment by ti-mo** [comment]
@wenlxie Is there nothing along these lines in Cilium's exported Prometheus metrics?

If not, are you planning on driving this work?

**Comment by wenlxie** [comment]
@ti-mo  
In the conntrack, it only account metrics for the dir=CT_INGRESS and CT_EGRESS, but not for dir=CT_SERVICE. 

https://github.com/cilium/cilium/pull/7119

I am trying to enhance for this.  I am thinking about two approaches:
1.  
1) Change the ct_entry defination, rx_bytes and backend_id to be not in a union https://github.com/cilium/cilium/blob/main/bpf/lib/common.h#L904-L907C4
2) Count the rx_bytes/tx_bytes/rx_pkts/tx_pkts when look up for conntrack.
3) We can get the totoal connections for svc/backend by iterate the conntrack tables, total connections/active connections/inactive connections  for svc, total connections /active connections/inactive connections for svc's backend pod. 

2. 
1) Add a new map, this map's key is svcip:svcport, backend pod ip:backend pod port, the value for it includes the connections, rx/tx packets. 
2) We can get the metrics by iterate this new map. 
The benefit is we don't need to iterate conntrack table to get related metrics since it may have lots of items.  

@ti-mo  @brb  Could you help to check for 1 and 2?  Then I can start to implemented for it. 

I am not sure for why https://github.com/cilium/cilium/pull/7119 is introduced for CT_SERVICE, is there anything for why we didn't accounting  for CT_SERVICE?

**Comment by wenlxie** [comment]
PR: https://github.com/cilium/cilium/pull/27527

**Comment by wenlxie** [comment]
```
Change the ct_entry defination, rx_bytes and backend_id to be not in a union https://github.com/cilium/cilium/blob/main/bpf/lib/common.h#L904-L907C4
Count the rx_bytes/tx_bytes/rx_pkts/tx_pkts when look up for conntrack.
We can get the totoal connections for svc/backend by iterate the conntrack tables, total connections/active connections/inactive connections for svc, total connections /active connections/inactive connections for svc's backend pod.
```

This solution  need a go routine to iterate with the ct_map and generate the related metrics,
There is already a go routine to do gc of the conntrack entry, we can integrate the service /backend pod metrics generated together in this go routine, but the issue is gc go routine has its own gc-interval. This may block the metrics generated in time. 

So it is better to have another map which can store the connection/ rx/tx pkt and bytes info, we can iterate the map to generate the metrics like I mentioned in solution 2. 

@ti-mo  @brb  @julianwiedmann  @YutaroHayakawa  Any suggestions for this? Thanks

**Comment by wenlxie** [comment]
After check the code, the conntrack table dump in GC are still not have the improvement with BPF_MAP_LOOKUP_BATCH feature. This feature should help to improve the GC performance significantly.

**Comment by wenlxie** [comment]
For the IPVS statistics:  
Conns/InPkts/OutPkts/InBytes/OutBytes
1. They are counters  value from beginning till now.
2. Both of VIP and its backend ip have these statistics. 

So add the statistics for inbytes/inpkt for CT_SERVICE is not enough, 
With it, we just can get the statistics for the current connections, but will lose the statistics of cycled connections. 

It is need to have a new map to store these metrics.
