### ISSUE TITLE
CFP: Recreate CNP CRDs based on feature enablement

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#27459]
Currently, Cilium Operator installs all CNP CRD in the cluster upon initialization. Since this CRD is defined with kubemarkers, its configuration is hardcoded [here](https://github.com/cilium/cilium/blob/31fa619d8fea7ff8228c24779f726424fb1b08d5/pkg/k8s/apis/cilium.io/v2/types.go#L19-L31). This causes some issues as pointed out in https://github.com/cilium/cilium/issues/17880 and can be confusing for users.

To prevent these issues, we could perform some conditional checking while we are constructing the CRD in [here](https://github.com/cilium/cilium/blob/4076314941da6ef1ed3728d2b0328996a31d4d73/pkg/k8s/apis/cilium.io/client/register.go#L315-L338) and define the CEP column views based on the features that are enabled. For example, if IPv6 is not enabled then we shouldn't display the IPv6 column, or, if we start Cilium agent with `--endpoint-status=policy` then we should show the column for policy enforcement status otherwise it should be omitted.

**Comment by Iiqbal2000** [comment]
Hi @aanm, I'm interested in addressing this issue. Could you guide me on how to retrieve the enabled features? Is there a specific function available for this?

**Comment by aanm** [comment]
Hi @Iiqbal2000 , the enabled features can be checked by looking at the contents of the directory `/tmp/cilium/config-map` inside the cilium-operator. That directory contains a list of files where its name is the flag name and the content of the file is the value of the flag.
For example if `/tmp/cilium/config-map/endpoint-status` contains `policy` we know that we should install the CRD for the policy enforcement status.

**Comment by Iiqbal2000** [comment]
Hi @aanm, I am still wondering. Can the CEP column views be updated when runtime?

**Comment by aanm** [comment]
> Hi @aanm, I am still wondering. Can the CEP column views be updated when runtime?



@Iiqbal2000 I think the idea suggested by Joe is a good call. I think we should do the following:

> Alternatively could we just drop these columns by default and display them in the `-o wide` configuration? So rather than dynamically changing the output based on the enabled features, just set up a regular and `-o wide` version and those are the two columns configurations? Then rely on standard kubectl tooling for if users want to output in custom formats?

**Comment by Iiqbal2000** [comment]
> @Iiqbal2000 I think the idea suggested by Joe is a good call. I think we should do the following:
> 
> > Alternatively could we just drop these columns by default and display them in the `-o wide` configuration? So rather than dynamically changing the output based on the enabled features, just set up a regular and `-o wide` version and those are the two columns configurations? Then rely on standard kubectl tooling for if users want to output in custom formats?

To make this work, do we need to set a value for the priority property in the Kubebuilder definition?

**Comment by aanm** [comment]
@Iiqbal2000 I believe so, yes.

**Comment by Iiqbal2000** [comment]
Ok @aanm, I will create a PR

**Comment by Iiqbal2000** [comment]
Which columns should be visible by default @aanm @joestringer ?

**Comment by aanm** [comment]
@Iiqbal2000 these ones would be a good start
```
$ kubectl --all-namespaces get cep
NAMESPACE            NAME                                      ENDPOINT ID   IDENTITY ID   ENDPOINT STATE   IPV4           IPV6
kube-system          coredns-565d847f94-92jdz                  1778          50416         ready            10.244.1.201   fd00:10:244:1::5c3b
kube-system          coredns-565d847f94-kqxhq                  2676          50416         ready            10.244.1.119   fd00:10:244:1::5de
...
```

**Comment by Iiqbal2000** [comment]
@aanm can you check my pr?
