### ISSUE TITLE
enhancement/correction in documentation - https://docs.cilium.io/en/latest/installation/kind/

### ISSUE THREAD

**Issue by zohebk8s** [cilium/cilium#27473]
Hi Team,

The image latest doesn't exist and if users try to install kind by pasting the command provided in an official document, it will fail with the below error.

root@zoh-aks:~/cilium-main/install/kubernetes# docker pull quay.io/cilium/cilium:latest
Error response from daemon: manifest for quay.io/cilium/cilium:latest not found: manifest unknown: manifest unknown

root@zoh-aks:~/cilium-main/install/kubernetes# kind load docker-image quay.io/cilium/cilium:latest
ERROR: image: "quay.io/cilium/cilium:latest" not present locally

Please try to update the image in both the commands mentioned in the documentation.

<img width="668" alt="image" src="https://github.com/cilium/cilium/assets/128701612/22bd5b6a-7f61-4dcb-80c9-bc119c1363a1">

Instead, the users have to select the right image like v1.14.0. (As I believe v1.14.0 is the current stable version)

root@zoh-aks:~/cilium-main/install/kubernetes# docker pull quay.io/cilium/cilium:v1.14.0
v1.14.0: Pulling from cilium/cilium
Digest: sha256:5a94b561f4651fcfd85970a50bc78b201cfbd6e2ab1a03848eab25a82832653a
Status: Image is up to date for quay.io/cilium/cilium:v1.14.0
quay.io/cilium/cilium:v1.14.0

**Comment by ti-mo** [comment]
@zohebk8s Thanks for the report! Would you be willing to put together a PR to address this?

**Comment by zohebk8s** [comment]
@ti-mo It would be great, if you can fix it. If you are okay, just mention my name(Zoheb) in that.

**Comment by riteshsonawane1372** [comment]
Assign me.

**Comment by vipul-21** [comment]
@ti-mo can I pick this up ?

**Comment by vipul-21** [comment]
Checked the documentation: https://docs.cilium.io/en/stable/installation/kind/#kind-install-cilium. Seems like it uses the  image tag which is `v1.14.2`. So not sure how/where to replicate the issue ?
@zohebk8s Was it on local ?

**Comment by vipul-21** [comment]
Found the place we will need to change: https://github.com/cilium/cilium/blob/main/Documentation/conf.py#L91
Will raise a PR
