### ISSUE TITLE
CFP: Support cilium metrics allowlist

### ISSUE THREAD

**Issue by CatherineF-dev** [cilium/cilium#27471]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**
https://github.com/cilium/cilium/issues/20810

If so, please describe the problem
Some cilium metrics cardinality are very high. Current open-telemetry collector will read the whole metrics payload, which can cause open-telemetry collector OOM.

**Describe the feature you'd like**
Add a flag --metrics-allowlist to only expose certain cilium metrics

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

- https://github.com/cilium/cilium/blob/main/pkg/metrics/metrics.go#L1002

```[tasklist]
### Tasks
```

**Comment by ti-mo** [comment]
Hi @CatherineF-dev, thanks for the proposal! Could you elaborate on what exactly `--metrics-allowlist`'s effect would be? I'm not sure if an agent flag is useful for this beyond specifying 2-3 metrics, or this will grow huge. (there are limits on how long arguments can be)

Could you flesh this out a bit more?

**Comment by CatherineF-dev** [comment]
Explicitly list all exposed metrics in --metrics-allowlist. 

For example, cilium_k8s_client_api_latency_time_seconds_bucket causes some OOMs. After updating --metrics-allowlist, this metric will not be exposed. Not only this metric, found other cilium metrics cardinality is high as well.

**Comment by CatherineF-dev** [comment]
After PR https://github.com/prometheus/client_golang/pull/1327, cilium will be able to use metrics-allowlist.
