### ISSUE TITLE
Host Firewall blocks ipv6 traffic from outside even without ClusterWideNetworkPolicy and/or with policy-audit-mode='true'

### ISSUE THREAD

**Issue by cgrijs** [cilium/cilium#27484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed plain k8s cluster and cilium without ipv6 support. We need (link-local) ipv6 traffic to the nodes for BGP traffic. With enable-host-firewall='false' this works as desired.

Enabling the host firewall, even without a CWNP, and even in audit-mode, which I expect not to drop any traffic, will block incoming ipv6 traffic. No 'drops' or 'audit' log entries appear in the logging.

### Cilium Version

Client: 1.14.0 b5013e15 2023-07-26T10:28:38+02:00 go version go1.20.5 linux/amd64
Daemon: 1.14.0 b5013e15 2023-07-26T10:28:38+02:00 go version go1.20.5 linux/amd64

(but same behavior also seen in 1.13)

### Kernel Version

Linux 5.15.0-78-generic #85-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230814-094014.zip](https://github.com/cilium/cilium/files/12333493/cilium-sysdump-20230814-094014.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
> Enabling the host firewall, even without a CWNP, and even in audit-mode, which I expect not to drop any traffic, will block incoming ipv6 traffic.

I believe this is expected behaviour. Without IPv6 support in cilium we are not able to apply policy. So IPv6 traffic gets dropped.

> No 'drops' or 'audit' log entries appear in the logging.

This is unexpected. We should be raising a drop notification from the relevant code path.

**Comment by cgrijs** [comment]
> > Enabling the host firewall, even without a CWNP, and even in audit-mode, which I expect not to drop any traffic, will block incoming ipv6 traffic.
> 
> I believe this is expected behaviour. Without IPv6 support in cilium we are not able to apply policy. So IPv6 traffic gets dropped.

The packets are dropped even though there is no policy applied, and, IMHO, audit mode should not drop any packets.

**Comment by maartenvdezz** [comment]
I have the same issue. I've enabled IPv6, proxy-replacement and host firewall but it immediately blocks icmp6. In monitor policy-verdict I don't see the traffic at all.
