### ISSUE TITLE
[cilium wireguard enabled] server-client connection punch-hole timeout problem when clinet behind NAT

### ISSUE THREAD

**Issue by FengGaoCSC** [cilium/cilium#27482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Under k8s environment with a cloud node and edge node.  the following show the topology of network.
```
      Server node (APIserver)
            |
    NAT（router)
            |
       Client node
```
#### With wireguard enabled by:
```
cilium install --encryption wireguard --version v1.12.5
```

####  issues:
  - 1.  First pods on Server/APIServer node **could not** connection  pods on Client node .

  - 2. Pods on Client node **must initial** access to the pods on Server node.

  - 3. Then pods on Server node **could** connection pods on client node  since the cilium(wireguard) on Server side update the endpoint address of client node after client pod initial the connection on step 2 
  
  - 4. After a while, pods on Server/APIServer node **could not** connection  pods on client node **again**.

#### What I want:
 After the pods on client node communicate whit pods on Server node, Server node could always can communicate with pods on the client node.
  

### Cilium Version

v1.12.5

### Kernel Version

linux 5.15.0-67-generic

### Kubernetes Version

1.22.13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FengGaoCSC** [comment]
@ti-mo 

thanks very much for your quick reply

**Comment by FengGaoCSC** [comment]
@fujitatomoya 

As @ti-mo replied, this need client is going to have to enable keepalives to keep the connection open.

**Comment by fujitatomoya** [comment]
@ti-mo thanks for reply, it is more likely related to wireguard but cilium. we will look into those.

**Comment by FengGaoCSC** [comment]
@ti-mo 

> @FengGaoCSC This is likely not an issue with Cilium. If the `NAT (router)` node in your diagram is a typical ISP middlebox (performing firewalling and SNAT for the client), the client is going to have to enable keepalives to keep the connection open. See https://www.wireguard.com/quickstart/#nat-and-firewall-traversal-persistence.
> 
> Closing for now.

Can we set wireguard configuration feature of `keepalive`of wireguard via cilium command `cilium install --encryption wireguard`? I had check the command and source but didn't get such infomation.

thanks very much

CC: @fujitatomoya

**Comment by FengGaoCSC** [comment]
- two methods to set keepalive feature
  - 1. using wireguard tools could setting keepalive configuration
  ```
  ## wg set interface  peer ${base64_publickey} persistent-keepalive interval-seconds
  ## e.g
  wg set  cilium_wg0 peer lY2o6SXH8I9PCSTWsniUhfa7FAzHWiQ6Jr431J19XiU= persistent-keepalive 5
  ```
   - 2. create a configure file like following and then set the conf
   ```
   cat /etc/wireguard/wg0.conf
   [Interface]
   Address = 10.0.0.1/32, fd12:3456:789a::1/128
   ListenPort = 51820
   PrivateKey = <Private Key>
   SaveConfig = true

   [Peer]
   PublicKey = <Client public key>
   PresharedKey = <Pre-Shared Key>
   PersistentKeepalive = 25

   wg setconf cilium_wg0 /etc/wireguard/wg0.conf
   ```

**Comment by brb** [comment]
We could accept a contribution to add an option to Cilium to set the persistent keepalive for `cilium_wg0`. Could you create a CFP issue?

**Comment by FengGaoCSC** [comment]
> We could accept a contribution to add an option to Cilium to set the persistent keepalive for `cilium_wg0`. Could you create a CFP issue, or just send a PR?

Will create it
