### ISSUE TITLE
Expected Kube-Proxy replacement to enable healthz endpoint

### ISSUE THREAD

**Issue by JoelSpeed** [cilium/cilium#27502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When switching from kube-proxy to Cilium, and enabling the strict kube-proxy replacement mode, I expected all of kube-proxy functionality to be replicated by Cilium without further configuration.

Cloud controller managers rely on the kube-proxy healthz endpoint being exposed (by default in Kube-Proxy) on `0.0.0.0:10256`. In Cilium, even when in `strict` mode, this is off by default.

Is there any reason, that in `strict`, we shouldn't be exposing the healthz endpoint by default, to match the behaviour of Kube-Proxy?

### Cilium Version

Cilium 1.12.10 628b520 2023-05-16T12:50:44-04:00 go version go1.18.10 linux/amd64

### Kernel Version

Doesn't matter for this issue

### Kubernetes Version

Doesn't matter for this issue (1.27)

### Anything else?

This may well be closed as a case of, go configure it, the option is there. But it seemed like a surprising behaviour to me, so perhaps it needs to be more obvious in the docs for replacing kube-proxy if it is decided not to fix this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
You can enable it by setting `kubeProxyReplacementHealthzBindAddr`. We didn't enable it by default because of potential port conflicts when users run KPR with kube-proxy.

**Comment by brb** [comment]
> My understanding, with strict mode specifically, was that running KPR would conflict with kube-proxy on other things (specifically the routing elements), so you couldn't run KPR strict and have kube-proxy running? Is that incorrect?

Noup, you can run KPR=strict with kube-proxy today. There are no conflicts except for the healthz endpoint bind port.

**Comment by JoelSpeed** [comment]
So what does strict mode actually mean then? I thought strict mode was a replacement for kube-proxy and that the intention was that you shouldn't run kube-proxy when running strict mode, but your comments suggest that isn't the case

**Comment by brb** [comment]
I does fully replace kube-proxy. Just in the past we received quite a few bug reports about the port collision from folks who still had kube-proxy running.
