### ISSUE TITLE
spire-server-0 stuck in "pending" state.

### ISSUE THREAD

**Issue by gary-RR** [cilium/cilium#27508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Envronment: on-prem lab.
Linux version: Ubuntu 20.04.5 LTS
Kernel: Linux 5.8.0-28-generic
Kubernetes version: v1.25.12
Cilium CLI version: 1.15.0-de

##Helm install options:
helm install cilium ./cilium \
  --namespace=kube-system \
  --set authentication.mutual.spire.enabled=true \
  --set authentication.mutual.spire.install.enabled=true \
  --set authentication.mutual.spire.server.datastorage.enabled=false

Upon execution, cilium itself installs fine, and "cilium status" confirms it. However, spire pods fail to start:
$ kubectl get all -n cilium-spire
NAME                    READY   STATUS                  RESTARTS        AGE
pod/spire-agent-2dkdq   0/1     Init:CrashLoopBackOff   7 (3m49s ago)   23m
pod/spire-agent-brcz8   0/1     Init:CrashLoopBackOff   7 (3m49s ago)   22m
pod/spire-agent-mtd8r   0/1     Init:CrashLoopBackOff   8 (4m40s ago)   29m
pod/spire-server-0      0/2     Pending                 0               33m

NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/spire-server   ClusterIP   10.96.232.169   <none>        8081/TCP   33m

NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/spire-agent   3         3         0       3            0           <none>          33m

NAME                            READY   AGE
statefulset.apps/spire-server   0/1     33m

I've tried everything from reinstallation and multiple reboots but the issue persists, looks like a bug to me. 

### Cilium Version

cilium-cli: v0.15.5 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.14.0
cilium image (stable): v1.14.0
cilium image (running): 1.15.0-dev

### Kernel Version

Linux 5.8.0-28-generic

### Kubernetes Version

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.12

### Sysdump

[cilium-sysdump-20230815-122750.zip](https://github.com/cilium/cilium/files/12344170/cilium-sysdump-20230815-122750.zip)

### Relevant log output

```shell
$ kubectl get all -n cilium-spire
NAME                    READY   STATUS                  RESTARTS        AGE
pod/spire-agent-2dkdq   0/1     Init:CrashLoopBackOff   8 (3m45s ago)   29m
pod/spire-agent-brcz8   0/1     Init:CrashLoopBackOff   8 (3m43s ago)   28m
pod/spire-agent-mtd8r   0/1     Init:CrashLoopBackOff   9 (4m28s ago)   35m
pod/spire-server-0      0/2     Pending                 0               39m

NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/spire-server   ClusterIP   10.96.232.169   <none>        8081/TCP   39m

NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/spire-agent   3         3         0       3            0           <none>          39m

NAME                            READY   AGE
statefulset.apps/spire-server   0/1     39m
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
Can you paste the output of `kubectl describe pod <spire pod>`?
