### ISSUE TITLE
Cilium Connection Tracking Seems to Prevent Final Tear-Down of Connections from Proxy

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#2752]
I was about to use cilium monitor to debug an issue in a minikube environment that had been running a while with cilium latest.   But when I fired up cilium monitor with --related-to referring to the pod of interest, I saw there was already a flood of conntrack drops: 

````
xx drop (CT: Can't create entry from packet) flow 0x1a06805 to endpoint 20509, identity 314->314: 10.15.28.238:10002 -> 10.15.47.43:55336 tcp ACK, FIN
xx drop (CT: Can't create entry from packet) flow 0xc64292fe to endpoint 20509, identity 314->314: 10.15.28.238:10002 -> 10.15.47.43:36328 tcp ACK, FIN
xx drop (CT: Can't create entry from packet) flow 0xd3723931 to endpoint 20509, identity 314->314: 10.15.28.238:10002 -> 10.15.47.43:47274 tcp ACK, FIN
xx drop (CT: Can't create entry from packet) flow 0x2ccd1bb4 to endpoint 20509, identity 314->314: 10.15.28.238:10002 -> 10.15.47.43:50514 tcp ACK, FIN
xx drop (CT: Can't create entry from packet) flow 0x1a06805 to endpoint 20509, identity 314->314: 10.15.28.238:10002 -> 10.15.47.43:55336 tcp ACK, FIN
xx drop (CT: Can't create entry from packet) flow 0xb6b9de8c to endpoint 20509, identity 314->314: 10.15.28.238:10002 -> 10.15.47.43:49078 tcp ACK, FIN
xx drop (CT: Can't create entry from packet) flow 0xc64292fe to endpoint 20509, identity 314->314: 10.15.28.238:10002 -> 10.15.47.43:36328 tcp ACK, FIN
xx drop (CT: Can't create entry from packet) flow 0xd3723931 to endpoint 20509, identity 314->314: 10.15.28.238:10002 -> 10.15.47.43:47274 tcp ACK, FIN
xx drop (CT: Can't create entry from packet) flow 0x2ccd1bb4 to endpoint 20509, identity 314->314: 
````

(see attached log for full list) 

Interestingly, these all seem to be dropped FINs from the proxy (10.15.28.238) to ephemeral ports on the pod of interest (10.15.47.43, endpoint 20509, identity 314).   Oddly, both source and dest identity in the flows are listed as 314, potentially implying that this is a pod talking to itself?  

It seems like it is the proxy trying to tear down connections that were initiated from the pod of interest to the proxy, since the proxy port is constant, and the ports on the pod seem ephemeral.   I would think that traffic back from the proxy to the client would be rewritten to appear to come from the real destination, but perhaps the conntrack drop happens before that rewrite? 

[conntrack-drop-flood.log](https://github.com/cilium/cilium/files/1706182/conntrack-drop-flood.log)

**Comment by tgraf** [comment]
This is very likely resolved via #2700
