### ISSUE TITLE
CFP: cluster wide Layer 7 Protocol Visibility

### ISSUE THREAD

**Issue by liyihuang** [cilium/cilium#27540]
**Describe the feature you'd like**

Currently, if we would like to have the cluster wide l7 Protocol Visibility(let's say DNS queries for example), we have to configure the cluster wide network policy to match * so we can see the DNS queries events. It forces people to adopt a zero trust model or apply the allow all cluster network policy to allow the traffic. I think we can improve the user experience here

We already have this annotation(https://docs.cilium.io/en/stable/observability/visibility/#proxy-visibility) that can work with pods. I hope we can have some config to allow people to observe the l7 events easily for the entire cluster or the namespaces

**(Optional) Describe your proposed solution**

I think we can have a helm values where we pass that to cilium where we can define label selector and namespace to actively select endpoints where and how we want to observe the Layer 7 Protocol Visibility. I can think of 2 benefits if we do it

1. I think it's easy for us to select from whole cluster, namespace to endpoints how we want to observe the Layer 7 Protocol. then we don't have to rely on the pod annotation any more.
2. we have a central place to see how we want to see observe l7 protocol, where we don't rely some filters through kubectl to see how we did the annotation.

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by joestringer** [comment]
Thanks for the suggestion! I think this makes sense. I see that this was also previously suggested here: https://github.com/cilium/cilium/issues/9593 .

**Comment by vyas-n** [comment]
Hey @joestringer,

I'm not sure if this was already implemented, but I'd like to do the same to enable viewing all layer 7 traffic in my cluster without requiring security rules to deny any of the traffic.

Is there a sample `CiliumClusterwideNetworkPolicy` that can do this today?
