### ISSUE TITLE
Layer 7 Protocol Visibility not working for 1.12.x

### ISSUE THREAD

**Issue by liyihuang** [cilium/cilium#27544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to follow https://docs.cilium.io/en/latest/observability/visibility/ to observe the DNS events but I found I only see the UDP 53 but no DNS events and resolution with cilium 1.12.x. I tried the 1.12.7 and latest release 1.12.13. they are the same

I have tested in 1.13.6 and 1.14.1. there isn't any issue at all with the helm same config. I believe that's a bug for 1.12 branch but not sure why it only happens to 1.12. Is there some fix PR not cherry picked to 1.12 branch?

### Cilium Version

1.12.x I tried with 1.12.7 and 1.12.12

### Kernel Version

Linux minikube 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:29:30 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

v1.26.3

### Sysdump

I dont think this is needed since you can easily reproduce it with a minikube

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
I was able to easily reproduce this on v1.12.12 as well:

```
kubectl apply -f examples/minikube/http-sw-app.yaml
kubectl annotate pod xwing policy.cilium.io/proxy-visibility="<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>"
kubectl exec xwing -- curl -s -XPOST deathstar.default.svc.cluster.local/v1/request-landing
```

Launch a `hubble observe -t l7 -f` or `cilium monitor -t l7` on the container running the `xwing` Pod and repeat the last command. No L7 traces occur. I also tried simplifying the visibility annotation to only include the DNS section, no difference.
