### ISSUE TITLE
Add m7a AWS instance family to ENI 

### ISSUE THREAD

**Issue by svyatoslavmo** [cilium/cilium#27562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

AWS released m7a instance family. In order for ENI to work pkg/aws/eni/limits/limits.go needs to be updated. 

### Cilium Version

1.14.1

### Kernel Version

5.15

### Kubernetes Version

EKS 1.26

### Relevant log output

`level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-074938c93fb3eebec name=ip-10-1-27-6.ec2.internal subsys=ipam`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
SGTM, thanks for the PR!

**Comment by jeremych1000** [comment]
Heya - mind regenerating again please? There's also m7a, m7i, and r7a, and r7iz for example/
https://aws.amazon.com/ec2/instance-types/

**Comment by cspargo** [comment]
there's also c7* that could be included here

**Comment by AnishShah** [comment]
This was fixed in #28880
