### ISSUE TITLE
Cluster Mesh Pod to ClusterIP of service in other cluster is not working (pod-to-pod works fine)

### ISSUE THREAD

**Issue by belmeopmenieuwesim** [cilium/cilium#27578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I had anticipated that Cilium ClusterMesh would seamlessly bridge the internal network of ClusterA with that of ClusterB. However, I'm encountering an issue: I can't seem to connect to the ClusterIP of a service located in a different cluster. That said, pod-to-pod communication across clusters is functioning properly, indicating that ClusterMesh is operational to an extent.

My primary requirement is service connectivity, especially through ClusterIP, and I don't need DNS resolution for this. This is crucial because I must communicate with the DNS server in another cluster within the mesh.

I attempted to address this by enabling `bpf.lbExternalClusterIP=true`, but unfortunately, that didn't resolve the issue.

Could someone shed some light on this? How can I configure Cilium to expose the service CIDR range across all clusters in the mesh?

### Cilium Version

v1.14.1

### Kernel Version

5.15.0-79-generic

### Kubernetes Version

Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.7+rke2r1

### Sysdump

[cilium-sysdump-20230818-023811.zip](https://github.com/cilium/cilium/files/12374322/cilium-sysdump-20230818-023811.zip)

### Relevant log output

```shell
[INFO] 10.42.1.58:37185 - 1992 "A IN nginx.us-west.svc.cluster.local. udp 49 false 512" NOERROR qr,aa,rd 96 0.000111573s
[INFO] 10.42.1.58:37185 - 41670 "AAAA IN nginx.us-west.svc.cluster.local. udp 49 false 512" NOERROR qr,aa,rd 142 0.000293594s
[INFO] 10.42.1.4:37690 - 5686 "AAAA IN nginx.us-west.svc.cluster.local. udp 49 false 512" - - 0 6.001504238s
[ERROR] plugin/errors: 2 nginx.us-west.svc.cluster.local. AAAA: read udp 10.42.0.153:58513->10.52.1.39:53: i/o timeout
[INFO] 10.42.1.4:37690 - 54331 "A IN nginx.us-west.svc.cluster.local. udp 49 false 512" - - 0 6.001693736s
[ERROR] plugin/errors: 2 nginx.us-west.svc.cluster.local. A: read udp 10.42.0.153:39970->10.52.1.39:53: i/o timeout
[INFO] 10.42.1.4:37690 - 5686 "AAAA IN nginx.us-west.svc.cluster.local. udp 49 false 512" - - 0 6.002637023s
[INFO] 10.42.1.4:37690 - 54331 "A IN nginx.us-west.svc.cluster.local. udp 49 false 512" - - 0 6.002863163s
[ERROR] plugin/errors: 2 nginx.us-west.svc.cluster.local. A: read udp 10.42.0.153:59484->10.52.1.39:53: i/o timeout
[ERROR] plugin/errors: 2 nginx.us-west.svc.cluster.local. AAAA: read udp 10.42.0.153:43216->10.52.1.39:53: i/o timeout
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
Cc @giorio94

**Comment by giorio94** [comment]
I don't know the details about the CockroachDB deployment, but generally speaking I would say that you can use global services to LB the access to the DB from clients, and the CoreDNS changes you mentioned for the headless services so that replicas can talk with each other.

**Comment by azalio** [comment]
> I managed to at least get the DNS part of my issue working. By configuring CoreDNS itself using the `kubernetes` plugin:

@belmeopmenieuwesim Can you help me with my situation?
I want to create some deployments with same pods in two kubernetes clusters. 
Both of them will have headless service for example "serviceA".

Can I get IPs from both cluster through coredns in cluster one? 
In other words, maybe you know how to get IPs from two cluster from one CoreDNS instance?

**Comment by dboslee** [comment]
As an alternative solution, I ended up a creating a global service per statefulset replica. Where the service name is the `{hostname}-{region}`. Then I used the service label selectors to select based on `region={region},statefulset.kubernetes.io/pod-name={hostname}`. Unfortunately this only works for statefulsets where the pod names are predictable.
