### ISSUE TITLE
Mutual Auth: add renovate for up to date images

### ISSUE THREAD

**Issue by meyskens** [cilium/cilium#27608]
We ship SPIRE and busybox image references in our Helm chart for Mutual Auth. However as raised in https://github.com/cilium/cilium/pull/27606 we do not have Renovate rules to track updates for these.

This issue is to track the work on adding these to our codebase

**Comment by aanm** [comment]
depends on https://github.com/cilium/cilium/issues/25457

**Comment by meyskens** [comment]
Fixed in https://github.com/cilium/cilium/pull/27708
