### ISSUE TITLE
`k8s:io.cilium.k8s.namespace.labels.*` are not removed from CEP when the label is removed from NS

### ISSUE THREAD

**Issue by PhilipSchmid** [cilium/cilium#27626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

CiliumEndpoints get `k8s:io.cilium.k8s.namespace.labels.*` labels and values added, as soon as I add the label to the Pod's namespace - for example `kubectl label namespace podinfo metrics=true`. Namespace label value updates are also propagated to the CEP labels within a few seconds. However, if I remove the namespace label completely (`kubectl label namespace podinfo exposed-`), the `k8s:io.cilium.k8s.namespace.labels.*` stays on the Pod's CEP until I restart the pod.

Here is an example:
![image](https://github.com/cilium/cilium/assets/5549063/7a36db40-e98d-46ec-a43f-1e2d1866e1e2)

The attached sysdump is taken from the cluster state where I already removed the `exposed=true` label from the `podinfo` NS, but it's still on the CEP of the `frontend-podinfo-74f74865f5-9fmp6` Pod (ID: `2893`, Cilium agent: `cilium-qbhtl`, node `ip-10-1-0-45.eu-central-1.compute.internal`):
```
root@ip-10-1-0-45:/home/cilium# cilium endpoint list | grep 2893 -B 5 -A 10
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=goldpinger
                                                           k8s:io.cilium.k8s.namespace.labels.metrics=true
                                                           k8s:io.cilium.k8s.policy.cluster=philip-netpol-demo
                                                           k8s:io.cilium.k8s.policy.serviceaccount=goldpinger-serviceaccount
                                                           k8s:io.kubernetes.pod.namespace=goldpinger
2893       Enabled            Enabled           128746     k8s:app.kubernetes.io/name=frontend-podinfo                                         100.64.2.63    ready
                                                           k8s:io.cilium.k8s.namespace.labels.exposed=true
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=podinfo
                                                           k8s:io.cilium.k8s.namespace.labels.metrics=true
                                                           k8s:io.cilium.k8s.policy.cluster=philip-netpol-demo
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default
                                                           k8s:io.kubernetes.pod.namespace=podinfo
```

### Cilium Version

`1.14.1`

### Kernel Version

`5.14.0-284.11.1.el9_2.x86_64`

### Kubernetes Version

`v1.27.4` (kubeadm)

### Sysdump

[cilium-sysdump-20230822-150542.zip](https://github.com/cilium/cilium/files/12408917/cilium-sysdump-20230822-150542.zip)

### Anything else?

Isovalent internal Slack discussion: https://isovalent.slack.com/archives/C027LL0JKFB/p1692707524229729

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tklauser** [comment]
Proposed fix in https://github.com/cilium/cilium/pull/27831. Looks like this affects all currently supported stable versions (v1.11-v1.14).
