### ISSUE TITLE
Replace use of shirou/gopsutil/v3 with simpler dependency or native code

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#27635]
gopsutil is used to retrieve load/CPU/memory information for debugging purposes. This currently inherits a series of dependencies which is undesired.

* [ ] Implement `pkg/loadinfo` with a simpler dependency.

**Comment by danshank** [comment]
Hey folks, looks like there hasn't been much movement here. @tgraf or @swastik959, do you mind if I push a branch? I'm close to having a replacement for gopsutil load, mem, and process directly in the cilium repo.

**Comment by christarazi** [comment]
@danshank Please go ahead
