### ISSUE TITLE
Ginkgo CI: add check for deadlocks in AfterEach

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2765]
For the Bash script based tests, we have `tests/99-deadlock-check.sh`, and `tests/k8s/tests/999-deadlock-check.sh`. Add a similar check to the Ginkgo framework. I recommend we do this after each Ginkgo test in an `AfterEach`.

**Comment by eloycoto** [comment]
Fixed by https://github.com/cilium/cilium/pull/3027
