### ISSUE TITLE
High CPU Usage with Cilium 1.13.0 and Kernel 5.15.106

### ISSUE THREAD

**Issue by njuettner** [cilium/cilium#27661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We’re currently facing issues with high CPU usage using kernel 5.x (in our case 5.15.106) and Cilium 1.13.0.

We were trying to find the root cause in the last days and found some quirks.
Because we thought it’s an issue of hubble / hubble event queue size or a Cilium patch version (taking the latest release from last week 1.13.6) we started there.

We noticed some upstream issues saying it might be a Kernel flaw (https://github.com/cilium/cilium/issues/24243), so we also looked into Kernel options.

We tried a couple of scenarios:
- Maxing out the event queue size did not help
- Disabling hubble completely did not help
- Using Kernel 6.x with the current release Cilium 1.13.0 did not help
- Using Kernel 5.x with the latest patch release Cilium 1.13.6 did slightly decrease CPU consumption but not much
- Using Kernel 6.x with the latest patch release Cilium 1.13.6 decreased CPU consumption by a 80%

The first graph has a short spike with Cilium 1.13.6 and Kernel 6.x which we expect as normal because of endpoints and service ingestions from Cilium.

The second graph has a constant high CPU usage with Cilium 1.13.6 and Kernel 5.x when running tests.

Do you have any ideas how to avoid upgrading to Kernel 6.x (specifically 6.1.43) to decrease the CPU usage? Any settings we should consider? We’re currently use more or less the default settings from the upstream chart.

![image](https://github.com/cilium/cilium/assets/1936982/0adecdfc-bd26-4566-b836-ab14df1085b4)

![image](https://github.com/cilium/cilium/assets/1936982/b33f0e0c-5493-41bf-ac51-b9ca4c61003d)

### OS 

flatcar

### Cilium Version

1.13.0

### Kernel Version

5.15.106

### Kubernetes Version

v1.24.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @njuettner is this high CPU in general with v1.13.x, or are you running an earlier v1.12.x version with lower CPU and you think it's a regression?

**Comment by joestringer** [comment]
I think that a good next step would be gathering sysdump / logs / `gops` output from an agent that is actively using a lot of CPU so that we can narrow down which features are causing the issue in this environment.

**Comment by njuettner** [comment]
I collected some stuff: 

[pprof-cpu.zip](https://github.com/cilium/cilium/files/12439158/pprof-cpu.zip)
[gops-memstats-$(pidof-cilium-agent).md](https://github.com/cilium/cilium/files/12439160/gops-memstats-.pidof-cilium-agent.md)
[gops-stack-$(pidof-cilium-agent).md](https://github.com/cilium/cilium/files/12439161/gops-stack-.pidof-cilium-agent.md)
[gops-stats-$(pidof-cilium-agent).md](https://github.com/cilium/cilium/files/12439163/gops-stats-.pidof-cilium-agent.md)

**Comment by njuettner** [comment]
@joestringer We haven't upgraded to Cilium 1.13, we switched currently from AWS CNI to Cilium (1.13.0)

**Comment by joestringer** [comment]
Following the debugging steps further with the `pprof-cpu`, I can see that the vast majority of time is being spent in what appears to be Cilium monitor and Hubble logic:

![image](https://github.com/cilium/cilium/assets/1243336/fbad77b6-4022-4d95-8bac-b79abb9aa1ed)

It may be relevant to understand exactly which Hubble settings you're using / how exactly you configured/installed Cilium, particularly if there's anything non-default. Also a sense for the scale of load on the targeted node in terms of bitrate / connections per second etc.

**Comment by njuettner** [comment]
To also answer the first question 😅 

> Pod churn also may be playing a role here, are you able to share a sense of how frequently pods are being created/removed in the cluster or node?

No frequently creation / removal of pods in the cluster, long-term running deployments as usual, no frequent jobs or anything.

**Comment by marseel** [comment]
One thing you could try as short-term mitigation is to lower `monitor-aggregation: medium` to `low` or `none`.
AFAIK Disabling just hubble does not disable ring-buffer events, which seems to be causing high CPU usage in your case.

**Comment by joestringer** [comment]
@marseel monitor aggregation aggregates events so that fewer events are generated and hence less CPU should be used. Setting monitor aggregation to medium is the most CPU-efficient configuration of this option.

**Comment by marseel** [comment]
ah yea, I don't know why I thought in reverse about this flag :facepalm:

**Comment by learnitall** [comment]
Looking at the cpu profile, there is an extra Info log that seems to be eating up CPU time. It was reduced to a debug log and eventually removed in May. I've asked for this change to be backported.

@njuettner would you be able to collect a pprof when hubble is disabled? That would be really helpful in nailing down what is going on.
