### ISSUE TITLE
Remove check for permissive CCNPs

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#27689]
The following warning was added when changing `toEndpoints` / `fromEndpoints` behaviour in CiliumClusterwideNetworkPolicy long ago:

https://github.com/cilium/cilium/blob/d1b8613364cb04d170ceef0926919ce47dcfd65d/pkg/k8s/apis/cilium.io/v2/validator/validator.go#L108-L115

The warning is no longer applicable. Remove it and all related code.

**Comment by shawnh2** [comment]
hi, interested in solving this one
