### ISSUE TITLE
CFP:  check and generate the some warning for L2AnnouncementPolicy

### ISSUE THREAD

**Issue by liyihuang** [cilium/cilium#27707]
## Cilium Feature Proposal
        
When I use the `L2AnnouncementPolicy`, I made a typo for the CIDR block for `CiliumLoadBalancerIPPool`. I didn't notice it for hours and did a lot of troubleshooting.

For example, my layer 2 network is in 192.168.1.0/24, and I would like to use a 192.168.1.248/29 as the `CiliumLoadBalancerIPPool` for `L2AnnouncementPolicy`. If I have a typo like 192.168.11.248/29, cilium still generate the `LoadBalancer` type for 192.168.11.248/29 range but it will not reply the ARP.

since I also configured the `L2AnnouncementPolicy`, cilium should know that 192.168.11.248/29 is not in 192.168.1.0/24 and can generate some warning so users like me dont have to spend toooo much time on troubleshooting.

**Describe the feature you'd like**

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by joestringer** [comment]
How does Cilium know about your L2 network IP range? Did you configure it as the `ipv4-native-routing-cidr`?

**Comment by liyihuang** [comment]
If I understand the `L2AnnouncementPolicy` and use it with `L2AnnouncementPolicy` correctly, most of the time it will try to grab the IP and reply the ARP on the host's layer 2 network. From cilium, we already know the host's IP address and netmask, it's easy for us to compare the if the ARP is trying to reply is within the same network with host's network.

Hope I make it clear
