### ISSUE TITLE
Hubble pod metrics missing when using (Source|Destination)(Ingress|Egress)Context

### ISSUE THREAD

**Issue by matmerr** [cilium/cilium#27717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In a very basic scenario with (Source|Destination)(Egress|Ingress)Context hubble metrics on 1.14.1 I'm not seeing any unique metrics for flow:sourceEgressContext with pod option set, despite seeing metrics for flow:sourceContext. 

It's also possible the output below may be expected and my understanding/usage of (Source|Destination)(Egress|Ingress)Context is incorrect

**Scenario: Send traffic from pod a to pod b**
pod a (agnhost-a), node 0
pod b (agnhost-b), node 1

---
**hubble-metrics: flow:sourceContext=pod**

node 0
```
hubble_flows_processed_total{protocol="TCP",source="kube-system/agnhost-a",subtype="to-stack",type="Trace",verdict="FORWARDED"} 5
hubble_flows_processed_total{protocol="TCP",source="kube-system/agnhost-b",subtype="to-endpoint",type="Trace",verdict="FORWARDED"} 3
hubble_flows_processed_total{protocol="Unknown flow",source="kube-system/agnhost-b",subtype="7",type="Unknown",verdict="TRACED"} 1
```

node 1
```
hubble_flows_processed_total{protocol="TCP",source="kube-system/agnhost-a",subtype="to-endpoint",type="Trace",verdict="FORWARDED"} 5
hubble_flows_processed_total{protocol="TCP",source="kube-system/agnhost-b",subtype="to-stack",type="Trace",verdict="FORWARDED"} 3
hubble_flows_processed_total{protocol="Unknown flow",source="kube-system/agnhost-a",subtype="7",type="Unknown",verdict="TRACED"} 1
```
----
**hubble-metrics: flow:sourceEgressContext=pod**

node 0 (pod name not found, here's everything)
```
hubble_flows_processed_total{protocol="TCP",subtype="to-endpoint",type="Trace",verdict="FORWARDED"} 333
hubble_flows_processed_total{protocol="TCP",subtype="to-stack",type="Trace",verdict="FORWARDED"} 243
hubble_flows_processed_total{protocol="UDP",subtype="to-endpoint",type="Trace",verdict="FORWARDED"} 87
hubble_flows_processed_total{protocol="UDP",subtype="to-stack",type="Trace",verdict="FORWARDED"} 87
hubble_flows_processed_total{protocol="Unknown flow",subtype="7",type="Unknown",verdict="TRACED"} 319
hubble_flows_processed_total{protocol="Unknown flow",subtype="7",type="Unknown",verdict="TRANSLATED"} 20
```

node 1 (pod name not found, here's everything)
```
hubble_flows_processed_total{protocol="TCP",subtype="to-endpoint",type="Trace",verdict="FORWARDED"} 494
hubble_flows_processed_total{protocol="TCP",subtype="to-stack",type="Trace",verdict="FORWARDED"} 359
hubble_flows_processed_total{protocol="UDP",subtype="to-endpoint",type="Trace",verdict="FORWARDED"} 115
hubble_flows_processed_total{protocol="UDP",subtype="to-stack",type="Trace",verdict="FORWARDED"} 115
hubble_flows_processed_total{protocol="Unknown flow",subtype="7",type="Unknown",verdict="TRACED"} 454
hubble_flows_processed_total{protocol="Unknown flow",subtype="7",type="Unknown",verdict="TRANSLATED"} 20
```

### Cilium Version

cilium-cli: v0.14.8 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.3
cilium image (stable): v1.14.1
cilium image (running): v1.14.1

### Kernel Version

Linux aks-nodepool1-28118625-vmss000000 5.15.0-1042-azure

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-19T16:11:29Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chancez** [comment]
CC @marqc

**Comment by marqc** [comment]
@matmerr Can you repeat your test with additional metric options set (for debugging purposes)

```
hubble-metrics: flow:sourceEgressContext=pod;labelsContext=source_pod,traffic_direction
```

**Comment by marqc** [comment]
I found a bug in code that resulted in this wrong behavior.  Until fix is applied and released, you can use a workaround to also specify "sourceContext", eg.

```
hubble-metrics: flow:sourceEgressContext=pod;sourceContext=reserved-identity
```
