### ISSUE TITLE
Pod health checks fail due to "Missed tail call".

### ISSUE THREAD

**Issue by hmadison** [cilium/cilium#27720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The pods for my various services fail to start due to failing health checks caused by Cilium dropping traffic with the reason "Missed tail call". My expectation would be that, by default, Cilium wouldn't be dropping the health checks coming from the host to the pods.

### Cilium Version

cilium-cli: v0.15.5 compiled with go1.20.7 on darwin/arm64
cilium image (default): v1.14.0
cilium image (stable): v1.14.1
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"

### Kernel Version

Linux minikube 6.4.11-200.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Wed Aug 16 18:01:59 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

```
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4
```

via

```
minikube start --memory 8000 --cpus 4 --network-plugin=cni --driver=podman
minikube v1.31.2 on Darwin 13.4.1 (arm64)
```

### Sysdump

[cilium-sysdump-20230826-081252.zip](https://github.com/cilium/cilium/files/12445315/cilium-sysdump-20230826-081252.zip)

### Anything else?

This is a semi-frequent occurrence on my end. When I go and run [Flux](https://fluxcd.io/) and have it spin up a set of operators (such as cert-manager, the Flink operator and external secrets), the chance of this happening is (subjectively) around 75%. The best fix that I have is to tear down the Minikube VM and rebuild everything. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hmadison** [comment]
Here is another sysdump which was taken during a second instance of this issue occurring.

[cilium-sysdump-20230826-121711.zip](https://github.com/cilium/cilium/files/12446043/cilium-sysdump-20230826-121711.zip)

What's interesting is that I can delete and re-create the resource and the "Missed tail call" issues return for the given pod return.

**Comment by dylandreimerink** [comment]
Hi @hmadison, thanks for the report. 

I did a quick scan of the sysdump but I can't find any information that tells me which tail call is missing, which is important to continue the fault finding. Could you run following command `kubectl -n kube-system exec cilium-8db5q -- cilium monitor --type drop -v`? It should contain the drop notifications mentioning the missing tailcall with some additional fields. Could you collect a few lines and send them, that would hopefully help in identifying the cause.

**Comment by brb** [comment]
@hmadison Did the "Missed tail call" thing start to happen after you upgrade Cilium? Or was it after installation? Asking, as I see different versions:
> cilium image (default): v1.14.0
> cilium image (stable): v1.14.1

**Comment by hmadison** [comment]
Hi @brb,

Its after the installation into a fresh cluster.

Thanks,
Hunter

**Comment by ti-mo** [comment]
@hmadison I've marked https://github.com/cilium/cilium/pull/29307 as fixing this issue since it gets rid of the last case of missed tail calls we've been able to find. There's also been https://github.com/cilium/cilium/pull/28740 that made its way into 1.14.4, so please give that version a try and report back :pray:.
