### ISSUE TITLE
CFP: Cilium support for WireGuard encryption with Azure CNI Overlay

### ISSUE THREAD

**Issue by cloud-az** [cilium/cilium#27733]
Customize Cilium integrated with Azure CNI Overlay to allow WireGuard node-to-node encryption (Not **BYON**).
This is already supported by [Calico](https://docs.tigera.io/calico/latest/network-policy/encrypt-cluster-pod-traffic) free edition. Would it be something relevant for Cilium?

**Comment by youngnick** [comment]
Thanks for this issue @cloud-az.

I'm not sure I understand what you are asking for here, sorry.

Do you mean that, when running Cilium in chaining mode with the Azure CNI, you would like to be able to enable Wireguard node-to-node encryption?

Either way, would you be able to provide some more detail on what problem you're trying to solve, so we can ensure we understand the request properly?

**Comment by cloud-az** [comment]
"_Do you mean that, when running Cilium in chaining mode with the Azure CNI, you would like to be able to enable Wireguard node-to-node encryption?_" Yes. 
I need to enable node - to - node encryption, but I see you do not support it in the non-enterprise edition of the Cilium chained with Azure CNI Overlay. I am aware of SPIFFE for pod-to-pod, but then we need to either choose enterprise or BYON with Cilium CNI.

**Comment by youngnick** [comment]
Ah yes, that sounds correct to me as well. Is there anything else you need on this issue?

**Comment by cloud-az** [comment]
That's all from me, looking forward to see if this will supported.

**Comment by amitmavgupta** [comment]
@cloud-az I see that you have opened an issue on the [Azure GH repo](https://github.com/Azure/AKS/issues/3873) as well which is great.

[Azure- CNI powered by Cilium](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium) (Overlay or VNET mode) is governed by Microsoft and they take a call to add more features to it. We also have wireguard support available via [Isovalent Enterprise for Cilium from Azure Marketplace](https://isovalent.com/blog/post/tutorial-deploying-isovalent-using-azure-arm-templates/#h-6-encryption) if that helps.

Happy to support in the BYOCNI mode as well for the first part of your question.

Regards,
-Amit

**Comment by margamanterola** [comment]
As Amit says, Azure CNI powered by Cilium is controlled by Microsoft. Thus, there's nothing we can do here, sorry. Closing as not planned.
