### ISSUE TITLE
Bootstrap GHA for scale-testing

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#27749]
As part of https://github.com/cilium/cilium/issues/27196 we are going to implement GithubAction for scale-testing Cilium.

This issue is for the first step of implementation:
- Creating a new GithubAction
- Spinning small (2-3 nodes) cluster using kOps
- Tearing down cluster.

First, we want to ensure that our pipeline does not leak any resources and cleans up everything, before processing with larger clusters and actual scale-testing.

**Comment by learnitall** [comment]
I currently have a workflow that can successfully perform the actions mentioned above and additionally run a bare-bones CL2 configuration. Cluster cleanup will occur if the workflow fails or is canceled. Next week, I will create a PR with the workflow so we can get it running bi-weekly on main.

**Comment by learnitall** [comment]
Now that we have a bootstrapped workflow that is working, I'm going to close this one out. Merging the workflow can be tracked in #965
