### ISSUE TITLE
Service update skipped after LRP removed during restart

### ISSUE THREAD

**Issue by tangenti** [cilium/cilium#27754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If the LRP for a service is deleted during pod restart, Cilium would reconcile the service in the following order:

1. The service is restored from LB map, with the type of `SVCTypeLocalRedirect` in `restoreServicesLocked`.
2. Later service update would be skipped as the type is `SVCTypeLocalRedirect`.
3.`SyncWithK8sFinished` is called, the service still has `restoredFromDatapath` set to `true`, so it would be removed along with the backends.
4. Service update is triggered again on new event, and `upsertService` will succeed as the previous restored service is deleted. 

Impact: Any traffic sent to the service before step 4 fully finished will timeout. 

I'm not sure how Cilium handles resync in the watcher, but I observed ~30 minutes period of unavailability on my clusters due to this issue.

Related issue: #13274 

### Cilium Version

All versions with LRP

### Kernel Version

N/A

### Kubernetes Version

1.27.4-gke.900

### Relevant log output

```shell
ERROR 2023-08-28T10:55:52.478446103Z [resource.labels.containerName: cilium-agent] {"error":"local-redirect service exists for frontend {{10.100.128.10 {UDP 53} 0} 0}, skip update for svc kube-dns", "k8sNamespace":"kube-system", "k8sSvcName":"kube-dns", "level":"error", "msg":"Error while inserting service in LB map", "subsys":"k8s-watcher"}


WARNING 2023-08-28T10:56:11.489941852Z [resource.labels.containerName: cilium-agent] {"l3n4Addr":"{IP:10.100.128.10 L4Addr:{Protocol:NONE Port:53} Scope:0}", "level":"warning", "msg":"Deleting no longer present service", "serviceID":131, "subsys":"service"}
WARNING 2023-08-28T10:56:11.490440425Z [resource.labels.containerName: cilium-agent] {"l3n4Addr":"{IP:10.100.130.169 L4Addr:{Protocol:NONE Port:53} Scope:0}", "level":"warning", "msg":"Deleting no longer present service", "serviceID":108, "subsys":"service"}
INFO 2023-08-28T10:56:11.492063967Z [resource.labels.containerName: cilium-agent] {"level":"info", "msg":"Deleted orphan backends", "orphanBackends":3, "subsys":"service"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
Cc @aditighag

**Comment by aditighag** [comment]
Hi! Can you share the steps to reproduce the issue? What Cilium version are you using? Also, can you upload a sysdump from the affected cluster?

**Comment by aditighag** [comment]
Sorry, I missed some details in the original description. 

Thanks for the detailed report, this scenario wasn't handled in the PR - https://github.com/cilium/cilium/pull/13274. `EnsureService` needs to be called in the restore path as well. /cc @Weil0ng

**Comment by tangenti** [comment]
Hi @aditighag, thanks for confirming the issue. 

If we don't have anyone from the community to work on the issue, I could have a try to fix the problem, but I'm quite busy these days so it might take extra time.

**Comment by aditighag** [comment]
>If we don't have anyone from the community to work on the issue, I could have a try to fix the problem

Go for it. I've assigned you the issue. Feel free to ping me on the Cilium #development channel if you have any questions.

**Comment by aditighag** [comment]
Resolved by - https://github.com/cilium/cilium/pull/36036.
