### ISSUE TITLE
Create new metrics API endpoint for debug-specific metrics

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#27750]
There are some metrics that can be useful for debugging purposes, but because they have a high cardinality, they aren't exposed to the regular API metrics.

Exposing a new local-only API endpoint for debug-specific metrics would allow us to fetch its values and store them in the sysdumps. 

This would also allow us to enable all metrics that got disabled by default due high cardinality.

**Comment by aanm** [comment]
Potentially duplicate of https://github.com/cilium/cilium/issues/27659

**Comment by christarazi** [comment]
Dup of https://github.com/cilium/cilium/issues/27659
