### ISSUE TITLE
Cilium hard coded service map size

### ISSUE THREAD

**Issue by buggyhunter** [cilium/cilium#27763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium code base explicitly sets max service id as 65536 ( https://github.com/cilium/cilium/blob/main/pkg/service/const.go#L12 )

If cilium runs full mode ( kube-proxy replacement) then it creates couple of service entry in the map per kubernetes service. ( based on the number of machines, service type etc)

This limitation decreases total number of kubernetes service to around ~10-15k.. Even smaller if there are more machines.

This limit should be configurable as cilium should able to handle huge number of services.

### Cilium Version

1.11.x

### Kernel Version

4.9.0-14-amd64

### Kubernetes Version

1.25.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by buggyhunter** [comment]
@youngnick @julianwiedmann any estimation for this issue?

seems it should be easy to make it configurable.

**Comment by aditighag** [comment]
Hi @buggyhunter 

What's the max number of services you are looking to deploy in your cluster? Do you know the approximate proportion of service types (e.g., clusterIP, node port)?

The code you've linked is the max number of service ID allocator. Have you tries bumping up the lb map size - https://github.com/cilium/cilium/blob/main/daemon/cmd/daemon_main.go#L1021?

**Comment by buggyhunter** [comment]
@aditighag we want to have ~40-50K node port service count.

We need to extend [cilium_lb4_services_v2](https://github.com/cilium/cilium/blob/main/daemon/cmd/status.go#L365)

That map's size is fixed to [~65K ](https://github.com/cilium/cilium/blob/main/pkg/service/const.go#L12)which is not enough. Because for each nodeport, ~3-4 map entry is created so it ends up around ~10-15K node port size.

After limit we see following log in cilium: 

```
level=error msg="Error while inserting service in LB map"
 error="Unable to allocate service ID 0 for {{10.8.48.102 {TCP 32894} 0} 0}: no service ID available"...
```

We are using cilium in IPAM ENI mode.
When we  execute `cilium service list`:

```
                                              6 => 10.9.47.37:32261
23104   100.67.101.97:30568    ClusterIP      1 => 10.9.40.60:30568
                                              2 => 10.9.37.123:30568
                                              3 => 10.9.56.38:30568
                                              4 => 10.9.45.20:30568
                                              5 => 10.9.46.96:30568
                                              6 => 10.9.47.37:30568
23105   0.0.0.0:30568          NodePort       1 => 10.9.40.60:30568
                                              2 => 10.9.37.123:30568
                                              3 => 10.9.56.38:30568
                                              4 => 10.9.45.20:30568
                                              5 => 10.9.46.96:30568
                                              6 => 10.9.47.37:30568
23106   10.9.52.130:30568      NodePort       1 => 10.9.40.60:30568
```
as you see for each port there are 3-4 entries in map.

**Comment by aditighag** [comment]
>level=error msg="Error while inserting service in LB map"
 error="Unable to allocate service ID 0 for {{10.8.48.102 {TCP 32894} 0} 0}: no service ID available"...

You seem to be hitting the service ID allocation limit, it's a `uint16` field at the moment (65k max). If you want to extend that limit, you would have to make similar changes as previously done for backend ID - https://github.com/cilium/cilium/pull/17235.

**Comment by buggyhunter** [comment]
@aditighag Is changing [limit here](https://github.com/cilium/cilium/blob/main/pkg/maps/lbmap/lbmap.go#L28) enough?
or does it require more changes?
If it requires more changes then we very appreciate if cilium team prioritize this issue and bring this capability.

**Comment by danwent** [comment]
@buggyhunter , based on @aditighag comments, the change to increase the 65K limits is vastly more complex than just changing a few constants.  An example of a similar type of change is the change she linked here: https://github.com/cilium/cilium/pull/17235/files 

The other potential angle is to keep the service limit at 65K, but eliminate the multiple service-ids allocated per NodePort service.  There might be some quick-and-dirty changes that you could apply in a private branch to try and reduce the number of service-ids allocated (e.g., if you only care about NodePort connectivity and not clusterIP connectivity for that same service).   I think we're setting up a chat with your team, so we can talk more then.

**Comment by jhead-slg** [comment]
Like @buggyhunter, we are also wanting to have a large number of nodePorts. In our use-case each nodePort we add allocates 8 Cilium serviceIDs limiting the cluster to only supporting about 8k services.

@danwent Did anything materialize from the off issue chat?

```
65521   23.111.147.42:17724     NodePort        1 => 240.2.9.24:11418 (active)
                                                2 => 240.2.9.47:11418 (active)
65522   23.111.147.42:17724/i   NodePort        1 => 240.2.2.102:11418 (active)
                                                2 => 240.2.9.24:11418 (active)
                                                3 => 240.2.9.47:11418 (active)
65523   10.10.0.47:17724        NodePort        1 => 240.2.9.24:11418 (active)
                                                2 => 240.2.9.47:11418 (active)
65524   10.10.0.47:17724/i      NodePort        1 => 240.2.2.102:11418 (active)
                                                2 => 240.2.9.24:11418 (active)
                                                3 => 240.2.9.47:11418 (active)
65525   240.0.3.72:17724        NodePort        1 => 240.2.9.24:11418 (active)
                                                2 => 240.2.9.47:11418 (active)
65526   240.0.3.72:17724/i      NodePort        1 => 240.2.2.102:11418 (active)
                                                2 => 240.2.9.24:11418 (active)
                                                3 => 240.2.9.47:11418 (active)
65527   0.0.0.0:17724           NodePort        1 => 240.2.9.24:11418 (active)
                                                2 => 240.2.9.47:11418 (active)
65528   0.0.0.0:17724/i         NodePort        1 => 240.2.2.102:11418 (active)
                                                2 => 240.2.9.24:11418 (active)
                                                3 => 240.2.9.47:11418 (active)
```
