### ISSUE TITLE
CFP: Ensure dependent CNI plugins are ready before a pod is started.

### ISSUE THREAD

**Issue by howardjohn** [cilium/cilium#27760]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

Some applications add additional CNI plugins to configure the pod network. Most notably, service meshes like Istio and Linkerd generally do this. This is generally done by a DaemonSet that updates the CNI config.

This has a major major problem: pods depending on the CNI plugin can start before the CNI plugin is deployed. https://linkerd.io/2022/12/01/what-really-happens-at-startup-linkerd-init-containers-the-cni-and-more/#cni-plugin-ordering describes this more. The workarounds for this are terrible.

**Describe the feature you'd like**

I would like Cilium to provide a first class way to prevent this problem.

The obvious question is: why Cilium, and not Kubernetes. I would love to have this fixed in Kubernetes core, but it seems like an uphill battle; see https://github.com/kubernetes/kubernetes/issues/75890 which has been opened for 4 years, including some efforts on a KEP without success.

Cilium (and other CNIs) is uniquely situated to workaround this problem fairly well).

Option 1: add a custom stub plugin in the initial cilium config.

Strawman config: `--cni-chaining-mode=custom --custom-cni-chain-plugins=[some-plugin-i-need]`. We insert a `{"type":"some-plugin-i-need"}`. The cni plugin replaces this with the full config later

Cons:
* requires all nodes to have the plugin, even for pods that do not depend on it
* Error message is kind of opaque
* Pod schedules onto bad node

Option 2: Add a pod annotation like cni.io/required-plugins: [some-plugin-i-need]. The CNI will read this annotation and block until the plugin is ready

Pros:
* Better error message is possible
* Works fine with CNI plugin being only on some nodes
Cons:
* CNI needs to read the plugin config which is kind of awkward/a layer violation.
* Pod schedules onto bad node

**Comment by aditighag** [comment]
Hi @howardjohn Have you looked at the CNI chaining configuration guide - https://docs.cilium.io/en/v1.14/installation/cni-chaining/?

**Comment by howardjohn** [comment]
https://docs.cilium.io/en/v1.14/installation/cni-chaining/ seems to be about adding cilium as a plugin on top of an existing "base" CNI. This is about the opposite -- appending an additional CNI plugin(service mesh) on top of the base.

In theory we could do the same thing as the doc but add `[cilium, other-thing]` instead of `[other-thing, cilium]`, but I am worried that this will look awkward in practice for users. Our docs for installing the service mesh would first be "modify your cilium CNI configuration" which is a big ask (compared to option 2, which requires no config changes to cilium). Additionally, it would mean the user manually becomes in control over the Cilium CNI config (which may lose some functionality like log-file, integrating with other chaining types, etc)

**Comment by aditighag** [comment]
>Some applications add additional CNI plugins to configure the pod network. Most notably, service meshes like Istio and Linkerd generally do this. This is generally done by a DaemonSet that updates the CNI config.

It sort of depends on what networking functionalities are delegated to the other CNI plugin. Based on your comments, it seems like the basic network connectivity and IPAM would still be handled by cilium?

>Add a pod annotation like cni.io/required-plugins: [some-plugin-i-need]. The CNI will read this annotation and block until the plugin is ready

That seems rather unusual. AFAIK, the cilium-cni plugin (or CNI plugins in general) don't read pod annotations. Networking setup, in general, is decoupled from pod updates from the Kubernetes api server. Is there a precedence for reading such annotations in CNI plugins?

**Comment by squeed** [comment]
In general, it is expected that the CNI configuration file precisely expresses administrator intent. Of course, the reality is that plugins themselves rewrite the configuration as-necessary. Thus, the CNI configuration file is now a part of the "eventually consistent" story of Pod creation and management.

We're talking about how to fix this within the CNI project itself (it will likely include making CNI an explicit part of CRI, then the Kubelet is responsible for managing network configurations). However, the initial scope of work doesn't include any explicit versioning, so how configuration-changes are rolled out is very undefined.

To solve your specific problem, the [Pod Readiness feature](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate) might suit your use-case. (It was previously known as PodReady++). Basically, you could add additional readiness gates that prevent a pod from being marked as Ready until they are satisfied. Then, the desired network plugin should set those on the Pod.

It might make sense to tie this in with the CNI STATUS verb.

**Comment by howardjohn** [comment]
@squeed pod readiness does not help unfortunately. The application containers _must_ not start before the network is configured, else (1) we cannot actually program the network since CNI `ADD` is not called, (2) we could bypass security policies

**Comment by relu** [comment]
From my experience, Cilium's strategy of dealing with this involving node taints works reasonably well, see the [considerations noted in the documentation](https://docs.cilium.io/en/stable/installation/taints/). Other CNI plugins could employ a similar tactic, although a standardized and unified method of dealing with this problem imposed by CNI would probably be the best approach going forward.

**Comment by howardjohn** [comment]
> From my experience, Cilium's strategy of dealing with this involving node taints works reasonably well, see the [considerations noted in the documentation](https://docs.cilium.io/en/stable/installation/taints/). Other CNI plugins could employ a similar tactic, although a standardized and unified method of dealing with this problem imposed by CNI would probably be the best approach going forward.

The taints approach is not generally viable for our users, IMO. It requires step 1 of onboarding "Go reconfigure your cluster", which is a huge burden -- and different for every platform. And if they do it wrong (or add a new node pool and forget, etc), they have an outage and/or CVE.
