### ISSUE TITLE
CFP: Add an option to Cilium to set the persistent keepalive for cilium_wg0

### ISSUE THREAD

**Issue by FengGaoCSC** [cilium/cilium#27771]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**
Related with: https://github.com/cilium/cilium/issues/27482

**Describe the feature you'd like**
I would like to add an option to Cilium to set the wiregurd persisten keepalive for cilium_wg0 interface that  when edge node behind the NAT, cilium client still could communication with server.

**(Optional) Describe your proposed solution**
for example the following command: 
```
cilium install  --encryption wireguard  --pereistent-keepalive <interval-seconds>
```

**Comment by fujitatomoya** [comment]
@FengGaoCSC thanks for creating issue.

@chaunceyjiang thank you for taking care of this. there has been any discussion on this? we were not sure if this is acceptable extension for cilium-cli and cilium. we are happy to explain the background if there is an appropriate place to discuss on this.
anyway i will take a look at the PR.

cheers,
Tomoya

**Comment by fujitatomoya** [comment]
> `cilium install --encryption wireguard --pereistent-keepalive <interval-seconds>`

according to the current implementation and latest doc, it would be more like.

```bash
cilium install --set encryption.enabled=true --set encryption.type=wireguard --set encryption.wireguard.persistentKeepalive=<sec>
```

once https://github.com/cilium/cilium/pull/27932 and helm value for configmap flag are supported?

**Comment by fujitatomoya** [comment]
https://github.com/cilium/cilium/pull/28013 is follow-up to support Cilium Charts.
