### ISSUE TITLE
CI: Conformance IPsec E2E: no-policies/pod-to-world/https-to-one.one.one.one-index-0: Resolving timed out after 2000 milliseconds

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#27799]
## CI failure

[cilium-sysdump-conformance-ipsec-e2e-key-rotation-1-20230829-091905.zip](https://github.com/cilium/cilium/files/12463901/cilium-sysdump-conformance-ipsec-e2e-key-rotation-1-20230829-091905.zip)

Sympton: The DNS lookup fails as follows:

```
[.] Action [no-policies/pod-to-world/http-to-one.one.one.one-0: cilium-test/client2-646b88fb9b-n948t (10.244.2.191) -> one.one.one.one-http (one.one.one.one:80)]
Tue, 29 Aug 2023 09:16:46 GMT   [.] Action [no-policies/pod-to-world/https-to-one.one.one.one-0: cilium-test/client2-646b88fb9b-n948t (10.244.2.191) -> one.one.one.one-https (one.one.one.one:443)]
Tue, 29 Aug 2023 09:16:46 GMT   ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 --retry 3 --retry-all-errors --retry-delay 3 [https://one.one.one.one:443](https://one.one.one.one/)" failed: command failed: curl: (28) Resolving timed out after 2000 milliseconds
```

It is a bit suspicious that it's not the connection to 1.1.1.1 that fails, but the DNS lookup. In Hubble, I don't see any dropped UDP port 53 traffic.

Observed in: https://github.com/cilium/cilium/actions/runs/6010063414/job/16300738637
Also observed in scheduled run: https://github.com/cilium/cilium/actions/runs/6011389565/job/16304679395

**Comment by christarazi** [comment]
Seen also in `Conformance E2E (ci-e2e) `: https://github.com/cilium/cilium/actions/runs/6042609573/job/16398065580

**Comment by pchaigno** [comment]
All of the failures in IPsec E2E so far look like they may have different root causes:

1. The original report, https://github.com/cilium/cilium/actions/runs/6011389565/job/16304679395
    - DNS resolution fails.
    - The UDP communication between the client and DNS server look normal.
    - https://github.com/cilium/cilium/pull/27874 will add info from DNS server pods.
2. echo-ingress, https://github.com/cilium/cilium/actions/runs/6030941968/job/16363741360
    - The packet disappears into the proxy even though we don't have L7 policies.
    - Not visible in the packet traces because we're missing one (fixed at https://github.com/cilium/cilium/pull/27872), but I confirmed via CT data.
    - It's another case of https://github.com/cilium/cilium/issues/17459.
    - `--flush-ct` of the connectivity tests should fix this. PR at https://github.com/cilium/cilium/pull/27883.
3. local-nodeport, https://github.com/cilium/cilium/actions/runs/6040307174/job/16390886302
    - The same connection to local backend going through a remote node VIP succeeds multiple times before failing.
    - For some reason, the CiliumInternalIP is picked as the SNAT IP on the failing connection but not before.
    - That leads to a RST.

**Comment by jschwinger233** [comment]
Not sure all cases have the same cause, but it appears some are due to forward delay of coredns.

After creating a cilium cluster (IPsec + native-routing), run `dig +timeout=1 one.one.one.one` inside either CoreDNS pod, there is a certain probability you might see result like:

```
;; communications error to 127.0.0.53#53: timed out
;; communications error to 127.0.0.53#53: timed out
```

I ran `pwru --timestamp absolute --output-meta --output-tuple --filter-track-skb 'ip and udp and udp[21:4] = 0x6f6e6503'` to capture all DNS query with `one.`, the tracing log shows:

```
# The dig sent the DNS query at 19:19:14.924
19:19:14.924 0xffffa0bca1d92a00      3 [/usr/bin/dig(392458)]              ip_send_skb   22087278375650 netns=4026534589 mark=0x0 iface=0 proto=0x0000 mtu=0 len=84 127.0.0.1:52392->127.0.0.53:53(udp)

# The coredns received DNS query at 19:19:14.926 
19:19:14.926 0xffffa0bca1d92a00      2 [coredns(391972)]          skb_consume_udp   22087278451594 netns=0 mark=0x0 iface=0 proto=0x0800 mtu=0 len=56 127.0.0.1:52392->127.0.0.53:53(udp)

# However, coredns sent DNS query to upstream at 19:19:16.937, which is 2 seconds after reception
19:19:16.937 0xffffa0ba94fb7400      5 [coredns(391972)]              ip_send_skb   22089281394165 netns=4026534589 mark=0x0 iface=0 proto=0x0000 mtu=0 len=84 10.244.0.184:41455->172.20.0.1:53(udp)
```

This 2 seconds delay can also be seen at non-IPsec cilium cluster, so I presume it's a general coredns issue likely not relevant to IPsec.

The coredns I tested is:
```
[INFO] plugin/reload: Running configuration SHA512 = 591cf328cccc12bc490481273e738df59329c62c0b729d94e8b61db9961c2fa5f046dd37f1cf888b953814040d180f52594972691cd6ff41be96639138a43908
CoreDNS-1.10.1
linux/amd64, go1.20, 055b2c3
```

Haven't tried the latest version v1.11.1.

**Comment by thorn3r** [comment]
Hit in workflow: https://github.com/cilium/cilium/actions/runs/8574999134/job/23503086062 on https://github.com/cilium/cilium/pull/31677
Sysdump: [cilium-sysdump-1-final.zip](https://github.com/cilium/cilium/files/14890666/cilium-sysdump-1-final.zip)

```
❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 --retry 3 --retry-all-errors --retry-delay 3 [http://one.one.one.one:80](http://one.one.one.one/)" failed: command failed (pod=cilium-test/client2-ccd7b8bdf-zbz7h, container=client2): "curl: (28) Resolving timed out after 2000 milliseconds\n"
```
