### ISSUE TITLE
Add `cilium_dbg` statement to `ipv4_to_endpoint_is_hairpin_flow()`

### ISSUE THREAD

**Issue by ti-mo** [cilium/cilium#27826]
While working on https://github.com/cilium/cilium/pull/27798, we considered adding a `cilium_dbg()` call to `ipv4_to_endpoint_is_hairpin_flow()` (see https://github.com/cilium/cilium/pull/27798#discussion_r1308795697). In the process, I noticed the `DBG_L7_LB` not being part of `enum DebugEventType` in `flow.proto`.

This issue is for adding DBG_L7_LB to flow.proto, introducing a new DBG_SKIP_POLICY enum value, calling it at the end of `ipv4_to_endpoint_is_hairpin_flow()` if it's about to return `true` (so, when `entry->lb_loopback == 1`) and regenerating the protobuf.

**Comment by Jack-R-lantern** [comment]
Can you assign it to me?

**Comment by Jack-R-lantern** [comment]
@ti-mo i have a question, 
i want to add cilium_dbg() [here](https://github.com/cilium/cilium/blob/6a8155e68530b4fef158474c73d07ec19e60b989/bpf/bpf_lxc.c#L2102)
```c
cilium_dbg(ctx, DBG_SKIP_POLICY, ..., ....);
```
Can you explain what to put as the first and second arguments?

**Comment by qmonnet** [comment]
> Can you explain what to put as the first and second arguments?

When we talked about that last week Timo had proposed the `LXC_ID` and the `sec_identity`, and I think it's OK. There's no specific parameter we need to debug here anyway, the important thing is to be able to determine that we do skip the policy check on this endpoint for a packet. So probably something like:

```c
cilium_dbg(ctx, DBG_SKIP_POLICY, LXC_ID, sec_identity);
```

Thanks for taking care of this!

**Comment by Jack-R-lantern** [comment]
@qmonnet [scope of sec_identity](https://github.com/cilium/cilium/blob/6a8155e68530b4fef158474c73d07ec19e60b989/bpf/bpf_lxc.c#L2058A1-L2081E1)
I'm going to change sec_identity to src_sec_identity.
