### ISSUE TITLE
how to change svc loadbalance mode

### ISSUE THREAD

**Issue by tom20180101** [cilium/cilium#27847]
k8s cluster: 1.24.16
cilium: 1.14

In my cluster, cilium replace kube-proxy,i want change svc loadbalance mode (default RR) , but i don't konw how to change it ,and i can't find this in document, someone tell me change it in svc ,and add  "cilium.io/load-balancer-mode: source-ip" , but i test it  and not work

**Comment by aditighag** [comment]
Hi @tom20180101 Cilium supports two load-balancer modes - random (default) and maglev. See `--bpf-lb-algorithm` -https://docs.cilium.io/en/stable/cmdref/cilium-agent/.

**Comment by tom20180101** [comment]
@aditighag  i'm glad you replied,   i already config it in cm  and restart cilium cilium-operator
`bpf-lb-algorithm: maglev
bpf-lb-maglev-hash-seed: AKHYE28K1gPQgfHT
bpf-lb-maglev-table-size: "65521"
`
and i test it according svc nginx, the result is 
`[root@master ~]# for i in {1..10};do curl 10.96.48.165:8080 ;done
this is test web page1
this is test web page2
this is test web page2
this is test web page1
this is test web page2
this is test web page2
this is test web page1
this is test web page2
this is test web page1
this is test web page1
[root@master ~]# 
`
now how client  access same backend server , the maglev seems not  achieve that

**Comment by youngnick** [comment]
@tom20180101 Both Round Robin and Maglev randomly choose backends from the pool, maglev just uses a slightly different weighting algorithm for it.

It sounds like you're wanting some sort of sticky load balancing for LB Services instead? If so, that's a new feature.

**Comment by tom20180101** [comment]
@youngnick    i want achieve that the same client (same ip )according LB choose same backend server no matter how many request .  :)

**Comment by youngnick** [comment]
Thanks for that, that's what I meant as well, so that would be a new feature. I'll see if there are any other outstanding requests for that, if so we can close this one out and you can follow them.

**Comment by tom20180101** [comment]
thanks @youngnick

**Comment by BurlyLuo** [comment]
@youngnick glad to see your explantiation about the ticket. 
my question is how to test the func about the maglev that in cilium CNI. 
how to prove the feature is take effect? thanks:)
