### ISSUE TITLE
CFP: Increase PolicyMapMax Hard Limit

### ISSUE THREAD

**Issue by isugimpy** [cilium/cilium#27866]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

Yes.  Even after increasing bpf.policyMapMax to 65536, I'm managing to hit the maximum on a particularly strange cluster.  (> 20k services, 1-2 pods per service)

**Describe the feature you'd like**

Increase bpf.policyMapMax further than 16 bits.

**(Optional) Describe your proposed solution**

Simply put, I'd like to increase https://github.com/cilium/cilium/blame/710316a4cf64202e210ec29c97be08209f96c69a/pkg/option/config.go#L644 even further.  Practically speaking, I don't know what a theoretical hard maximum for this value is.  Would 24 bits be acceptable?  Realistically, it seems like there are inevitable practical limits to the maximums here, but allowing users to go higher if they choose to face the risks of those limits would be nice if it's mechanically possible to do so.  Happy to open the PR to increase this myself, if it'd be accepted.

**Comment by christarazi** [comment]
I think it's certainly possible to bump the maximum. I think it might be worth investigating whether the way your policies are written could be optimized such that the number of identities relevant in the policies is reduced. One very easy way to saturate the policymaps is with an overly permissive policy. Have you taken a look at https://docs.cilium.io/en/latest/operations/performance/scalability/identity-relevant-labels/#identity-relevant-labels?

**Comment by isugimpy** [comment]
I have!  I was tuning that a bit yesterday actually.  Unfortunately, I was in the middle of dealing with an incident triggered by a strange upgrade behavior and had to roll back, so I haven't had a great opportunity to explore what the impact of the change ended up being.  The key thing in my mind is that with the sheer number of unique services in the cluster (and that growing more over time), it's still likely to be hit.  This cluster provides per-engineer development environments, so there's a huge number of unique identities, unlike a more traditional cluster.

I'm not sure if there's a metric for the number of identities created, but I'll take a look at that when I get back to work on Tuesday and see how our changes impacted things.

**Comment by christarazi** [comment]
Yep, see the metrics reference [here](https://docs.cilium.io/en/stable/observability/metrics/#identity) for identity-relevant metrics.

**Comment by isugimpy** [comment]
Maybe I've got an X/Y problem here.  The log entry I'm seeing is 
```
Aug 31 17:02:00 cilium-r5k59 cilium-agent error level=error msg="Failed to add PolicyMap key" bpfMapKey="{46885 8080 6 0}" containerID= datapathPolicyRevision=9 desiredPolicyRevision=9 endpointID=1489 error="Unable to update element for cilium_policy_01489 map with file descriptor 299: the map is full, please consider resizing it. argument list too long" identity=31110 ipv4= ipv6= k8sPodName=/ port=0 subsys=endpoint
```
Looking at the metrics, at peak late this past week there were ~37000 identities on the cluster.  With some tuning of the identity-relevant labels, I managed to get that down to about ~31000 identities before we had to roll back our changes for other reasons, preventing me from doing further testing and tuning.  As deployed from the helm chart, my values for BPF settings look as follows:
```
  bpf:
    mapDynamicSizeRatio: 0.005
    masquerade: true
    policyMapMax: 65536
```
With the sheer number of unique things running in this cluster, I'm not honestly sure I could feasibly decrease the identity count much further.  We give each user a namespace where they can deploy as much of our service stack as they need for development, and each namespace should be able to run fully independently, so there's effectively no overlap between them, and very few pods which have multiple replicas.  Nearly everything that runs on the cluster is actually a unique identity, for all reasonable intents and purposes.

If there are further things that could be tuned, I'm absolutely open to trying that.  One thing that's worth noting is that, today, the only policies on the cluster are ones used by Cilium's own test harness.  This is intentional.  While we could turn off policy entirely because of that, we're intentionally using this cluster as a means to do worst-case scenario testing in our environment as we work toward certifying Cilium for use elsewhere in our stack.  Eventually, we do intend to be using policy on our other clusters (and perhaps this one in a meaningful way), so we're really trying to push the limits and understand where things break.

**Comment by christarazi** [comment]
Thanks for the context. 

Speaking of this subject, I've put up https://github.com/cilium/cilium/pull/27903 which should provide more pointers. I'm curious to see how these instructions fair with your situation, especially depending on the type of identities. If most of your identities are label-derived, then identity-relevant labels is the best that can be done there. However, if some identities come from another source, there could be some wiggle room there. Let me know how it goes.

Btw, it would be useful to see the `cilium_identities` metric in your environment and the breakdown based on type.

**Comment by isugimpy** [comment]
That linked PR is super helpful, I'll about checking that out tomorrow.

![image](https://github.com/cilium/cilium/assets/14954499/af8bab75-2fe2-4a26-9d45-faafb5e9a1ca)
Last 7 days of metrics.  That bit in the middle where everything goes weird is when we upgraded from 1.13 to 1.14, and then it levels back out after we downgraded.  That's also why there are only node_local identities during that window.  The graph being a mess there is almost certainly more to do with the cluster being in a weird/bad state than my changes, especially given that we rolled back everything (including the reduced set of labels) at 1940 UTC, where the node_local line disappears from the graph and the amount of identities doesn't actually go back to the pre-reduction state.

**Comment by isugimpy** [comment]
Looked through the doc.  I'll have to see about enabling that pressure metric, because it's not default enabled on 1.13.  Also tossed a comment in to correct the metric lookup.  I'm not sure how much this is going to end up helping, but I'll try the further investigation steps as well.

**Comment by isugimpy** [comment]
Apologies for the delay, I had some conflicts and couldn't get back to this until today.  We upgraded to 1.14 this weekend, so I now have the cilium_identities metric.

{type="cluster_local"} 37370
{type="reserved"} 3992

We are still hitting limits on the map size at this point.

**Comment by christarazi** [comment]
I wonder why there are nearly 4k reserved identities. That seems a bit surprising.

**Comment by isugimpy** [comment]
Well, I feel a bit silly. That's the result of me doing `sum by (type)`. I
had assumed that each row would have a value of 1. There are 8 reserved
identities per node.

**Comment by joestringer** [comment]
Policy map max size is effectively encoding the maximum of the set of explicitly denied tuples (peer identity + port) plus the maximum of the set of explicitly allowed tuples (peer identity + port). I can see some evaluation above regarding how many unique app policy postures there may be, and perhaps there's a fair argument for having 10Ks of unique identities in the cluster. I note that this is limited to a little less than 65K based on the bitpatterns used to encode numeric identities under the hood, though that's mostly for in-cluster destinations and it's possible to extend the total number of identities further with out-of-cluster destinations potentially by at least tens of thousands more peers.

If we wish to encode all of these into the policy map, then the policy posture seems like it's "allow all", which Cilium can effectively encode with a single entry if the policy is set to allow `toEntities: - All` or `fromEntities: - all`. In that case, you wouldn't need a policymap max size scaling based on the number of identities in the cluster because one entry is enough to allow all peers. If on the other hand there is a use case for being very permissive within the cluster but not allowing all peers, then maybe we should work on a better way to encode the policy into the policy map rather than simply bumping the limit. Simply bumping the limit further is always possible, but it comes at the cost of memory usage for the maps plus processing cost for calculating the policy posture for each possible peer, which is naturally inefficient for highly permissive policies in clusters with many identities.

**Comment by isugimpy** [comment]
I should specifically call out that we're not actively using policy on this cluster, but have it enabled in the interest of future use.  The reason I opened this issue is that we're getting continuous log messages indicating the inability to update Cilium policy maps.  Prior to 1.14, I can't recall the precise message (and the logs have long since been lost to time) but since upgrading we're getting ENOSPC back when attempting to update the map.  Perhaps this is misguided on my part and I'm proposing an X/Y problem here where my speculation is that the total map size is too small, and instead there's some other problem.

It's probably also a reasonable assumption to suggest we could just disable policy entirely for the cluster, but that's actually not desirable to us, just so it's said.  We've been trying to stress test Cilium to see where the cracks are, to prepare for a broader rollout to more clusters, and being able to see it in our most abusive cluster has been extremely enlightening for us.

Maybe there's some other possible solution to this which could be proposed?  Since I hadn't provided one before now, example log line below:
` level=error msg="Failed to add PolicyMap key" bpfMapKey="{64 51799 0 6 36895}" containerID=363108759a datapathPolicyRevision=0 desiredPolicyRevision=6 endpointID=2015 error="update map cilium_policy_02015: update: no space left on device" identity=7563 ipv4=10.97.39.43 ipv6= k8sPodName=flux-system/notification-controller-5dc5586b8b-mt9gj port=0 subsys=endpoint`

**Comment by christarazi** [comment]
ENOSPC is actually interesting because I was under the impression that you were seeing the more typical E2BIG when it comes to maps. Do you have a sense for when the former occurs over the latter?

**Comment by isugimpy** [comment]
Oh heck, I did give a log line above.  Thank you for pointing that out, this has been ongoing long enough that I completely forgot.  So, yes, I **had** been seeing E2BIG consistently for a while, interspersed with ENOSPC.  E2BIG completely stopped in our logs as of 9/27 for reasons that aren't obvious to me because we didn't make any relevant changes around then that I'm aware of.

**Comment by christarazi** [comment]
ENOSPC sounds like it occurs when the bpffs runs out of space presumably due to many maps consuming lots of memory due to many entries, but I've never experienced this before so I'm not sure exactly.

**Comment by joestringer** [comment]
> I should specifically call out that we're not actively using policy on this cluster, but have it enabled in the interest of future use.
...
> Perhaps this is misguided on my part and I'm proposing an X/Y problem here where my speculation is that the total map size is too small, and instead there's some other problem.
...
> Maybe there's some other possible solution to this which could be proposed?

Cilium's generation of policymap entries is highly dependent on the network policies you have in place. I think it would help to have a general overview of how permissive you wish the network policy to be and also to see how you're mapping that to netpol/cnp/ccnp resources to see whether there is a use case here that Cilium is poorly optimized for, or whether it's simply a matter of encoding the network policy more precisely for the traffic you expect to allow.

**Comment by isugimpy** [comment]
Today, precisely one policy exists on the entire cluster.  https://github.com/cilium/cilium/blob/79f07dff67cdf6b22a4cc770532bb6bd1800a88f/examples/policies/l7/dns/dns-visibility.yaml  I can delete it, but made the assumption that it may be providing some useful data in terms of metrics since it's theoretically exercising the system.

As far as how we actually want things to look, that's somewhat of a mutable state that we're still determining.  In an ideal world, each of the main developer namespaces would be isolated via CNP such that it can only talk to things inside that namespace, DNS, and the ingress controllers.  I think I'd place that somewhere in the moderately permissive camp, in that we wouldn't be isolating services from each other within the same namespace at all.

**Comment by joestringer** [comment]
Hmm, that's quite odd. I wouldn't expect this policy to generate many policymap entries. Are you sure there isn't another permissive policy created somewhere, such as Kubernetes NetworkPolicy?

**Comment by isugimpy** [comment]
Bad assumption on my part that the core NetworkPolicy wouldn't be a part of this.  In that case, there are 4 other network policies on the whole cluster:

```
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      app.kubernetes.io/instance: flux-system
      app.kubernetes.io/part-of: flux
      kustomize.toolkit.fluxcd.io/name: fluxcd
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: allow-egress
    namespace: flux-system
  spec:
    egress:
    - {}
    ingress:
    - from:
      - podSelector: {}
    podSelector: {}
    policyTypes:
    - Ingress
    - Egress
  status: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      app.kubernetes.io/instance: flux-system
      app.kubernetes.io/part-of: flux
      kustomize.toolkit.fluxcd.io/name: fluxcd
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: allow-scraping
    namespace: flux-system
  spec:
    ingress:
    - from:
      - namespaceSelector: {}
      ports:
      - port: 8080
        protocol: TCP
    podSelector: {}
    policyTypes:
    - Ingress
  status: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    labels:
      app.kubernetes.io/instance: flux-system
      app.kubernetes.io/part-of: flux
      kustomize.toolkit.fluxcd.io/name: fluxcd
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: allow-webhooks
    namespace: flux-system
  spec:
    ingress:
    - from:
      - namespaceSelector: {}
    podSelector:
      matchLabels:
        app: notification-controller
    policyTypes:
    - Ingress
  status: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: "2023-02-17T18:45:39Z"
    generation: 1
    labels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 9.5.3
      kustomize.toolkit.fluxcd.io/name: infra-grafana
      kustomize.toolkit.fluxcd.io/namespace: infra-grafana
    name: grafana
    namespace: infra-grafana
  spec:
    egress:
    - {}
    ingress:
    - {}
    podSelector:
      matchLabels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: kube-prometheus
    policyTypes:
    - Egress
    - Ingress
  status: {}
kind: List
metadata:
  resourceVersion: ""
```
Those probably could be removed as well, they're just the stock ones provided by the apps, but I wouldn't expect these to be problematic either unless there's something you see that I don't.

**Comment by joestringer** [comment]
The way that Cilium interprets these Kubernetes permissive network policies is by enumerating every identity within the cluster and populating the policymap with an allow for each.

If you converted these to CNP with `toEntities: - all` `fromEntities: - all` instead of the pod selectors, then this would (a) allow connections from both within and outside the cluster (assuming connectivity outside the cluster is physically possible), but also (b) would be far more efficient on the number of policymap entries. As long as (a) does not violate your intended policy, this would be the best path forward using current Cilium feature support.

If these policies need to express only an allow-all for every other Pod within the cluster, then CNP has the expressions `toEntities: - cluster` and `fromEntities: - cluster`, but this is not currently optimized to minimize the number of Identities. If that is an intended policy target, then maybe one further step is for Cilium to look at optimizing policy matches for traffic within the cluster so that they don't require encoding every peer inside the cluster into the policymap lookup. It's not exactly trivial but I think there's a reasonable way to integrate such a solution into the current implementation without super invasive changes.
