### ISSUE TITLE
CFP:   restart the cilium components with helm post-upgrade hook  

### ISSUE THREAD

**Issue by liyihuang** [cilium/cilium#27867]
## Cilium Feature Proposal
        
I personally have spent hours of troubleshooting after the cilium's upgrade. It turns out the root cause of the issue is I didn't restart the cilium after the helm upgrade. I have also seen other users ran into the this type of issue for long time.

When we use the helm to upgrade cilium, the cilium may or may not restart itself. I suggest that we should have a post upgrade job to restart all cilium components.

The argument could be a mandatory post upgrade restart could cause some unnecessary disruption. However, I think the  
 pros of restart outweigh the cons since people should expect there can be some disruption when upgrading their CNI.

**Describe the feature you'd like**

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by youngnick** [comment]
Thanks for opening this CFP @liyihuang. I can see how that is pretty frustrating.

However, this would be a _significant_ behavior change, so it will need a similar amount of work put into proving why it's a better option. This would require a full CFP, using the template in the [design-cfps](https://github.com/cilium/design-cfps) repo, explaining why changing things is a better idea than leaving them how they are, and how we should deal with the behavior change on upgrade (I expect we would need a way to revert the old behavior at a minimum, to lessen the impact). Anyone wanting to solve this in the way you suggest will need to do something like this, sadly.

If that's too much, we could also accept a PR to add a callout to the [Upgrade Guide](https://docs.cilium.io/en/stable/operations/upgrade/) to suggest manual restarts after upgrading if anything is not working.

**Comment by liyihuang** [comment]
thanks for pointing out the doc. This is my first CFP for cilium project. I will look into it how to do it properly. To be honest, I'm thinking we should do both(add the a callout and a change)

**Comment by aanm** [comment]
As suggested in the weekly meeting by Sebastian we currently have an existing option: `rollOutCiliumPods`/ `$component.rollOutPods` Helm value (disabled by default).

We shouldn't make this the default behavior since that's not the expectation that users have when using helm upgrade. For example, if the user modifies configmap value and all pods are restarted immediately, which might cause DoS in the entire cluster if that new value was not accepted by Cilium and then we would make all Cilium pods to be in crashloopbackoff.

I think a potential solution would be https://github.com/cilium/cilium/issues/27972

**Comment by liyihuang** [comment]
thanks. I didn't know we have the `rollOutCiliumPods ` option before. I was thinking we can have 
`post-upgrade` from  https://helm.sh/docs/topics/charts_hooks/#the-available-hooks to perform necessary restart after a `helm upgrade` and have a bool to control it. https://github.com/cilium/cilium/issues/27972 is a good solution from for people to notice or we can have some notes for helm upgrade to remind people to restart the pod

btw, I personally dont think hot reload is a good idea since we have lots of flags and people need to remember it or have a dictionary to look it up.

**Comment by youngnick** [comment]
I agree that #27972 is probably a better solution - does that mean we should close this one out @liyihuang?
