### ISSUE TITLE
Make endpoint.WaitForProxyCompletions aware of regenerateBPF processing time

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2788]
I've noticed when the system is with a heavy load, the regenerateBPF on line 769 can take more than 10 seconds to build. This causes `endpoint.WaitForProxyCompletions` to fail immediately, since its context has a timeout of 10 seconds, setting the endpoint to `not-ready` state until a new policy regeneration is triggered (which only happens after 5 minutes in a kubernetes cluster).

https://github.com/cilium/cilium/blob/4ec32af26003336bb516c22c33848d10fa3f2e04/pkg/endpoint/policy.go#L733-L740

https://github.com/cilium/cilium/blob/4ec32af26003336bb516c22c33848d10fa3f2e04/pkg/endpoint/policy.go#L769-L773

Proposed (non tested) workaround:

```golang
diff --git a/pkg/endpoint/endpoint.go b/pkg/endpoint/endpoint.go
index bc156abec..08999d32a 100644
--- a/pkg/endpoint/endpoint.go
+++ b/pkg/endpoint/endpoint.go
@@ -17,7 +17,6 @@ package endpoint
 import (
        "encoding/base64"
        "encoding/json"
-       "errors"
        "fmt"
        "os"
        "path/filepath"
@@ -350,7 +349,7 @@ func (e *Endpoint) WaitForProxyCompletions() error {
        e.getLogger().Debug("Waiting for proxy updates to complete...")
        err := e.ProxyWaitGroup.Wait()
        if err != nil {
-               return errors.New("proxy state changes failed")
+               return fmt.Errorf("proxy state changes failed: %s", err)
        }
        e.getLogger().Debug("Wait time for proxy updates: ", time.Since(start))
        return nil
diff --git a/pkg/endpoint/policy.go b/pkg/endpoint/policy.go
index ffad98627..bd09674a9 100644
--- a/pkg/endpoint/policy.go
+++ b/pkg/endpoint/policy.go
@@ -16,6 +16,7 @@ package endpoint
 
 import (
        "context"
+       "errors"
        "fmt"
        "net"
        "os"
@@ -731,7 +732,7 @@ func (e *Endpoint) regenerate(owner Owner, reason string) (retErr error) {
        }()
 
        e.BuildMutex.Lock()
-       completionCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
+       completionCtx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
        e.ProxyWaitGroup = completion.NewWaitGroup(completionCtx)
        defer func() {
                cancel()
@@ -768,8 +769,24 @@ func (e *Endpoint) regenerate(owner Owner, reason string) (retErr error) {
 
        revision, err := e.regenerateBPF(owner, tmpDir, reason)
        if err == nil {
+               waitForProxyCompletions := make(chan error)
+               go func() {
+                       err = e.WaitForProxyCompletions()
+                       select {
+                       case waitForProxyCompletions <- err:
+                       default:
+                               close(waitForProxyCompletions)
+                       }
+               }()
                // Wait for all asynchronous proxy updates to be finished.
-               err = e.WaitForProxyCompletions()
+               select {
+               case err1, ok := <-waitForProxyCompletions:
+                       if ok {
+                               err = err1
+                       }
+               case <-time.After(10 * time.Second):
+                       err = errors.New("Proxy setup was not completed")
+               }
        }
        if err != nil {
                os.RemoveAll(tmpDir)
```

**Comment by rlenglet** [comment]
The completion timeout duration is arbitrary. It only has to be set to some finite duration, just to make sure the agent doesn't get stuck forever in some corner cases (proxy unresponsive, etc.).
Let's just bump the timeout to 1 minute in the couple places where we create the WaitGroup. I think this can be a 2-liner.

**Comment by rlenglet** [comment]
@aanm Any concern with just bumping up the timeout?

**Comment by rlenglet** [comment]
Discussed with @aanm and @jrajahalme, and found a better fix, out for review in https://github.com/cilium/cilium/pull/2794.

The wait group `Daemon.deleteEndpoint` wait group was already OK with a 10-second timeout. Reverting it to 10 seconds.

The wait group used for regeneration can be made local to `Endpoint.regenerateBPF` and its timeout set back to 10 seconds. We also now wait for proxy completions before generating the BPF program. This allows correctly handling the case when the BPF program is inserted and starts redirecting traffic to a proxy port before the proxy is configured to listen on that port, which leads to traffic loss.
