### ISSUE TITLE
ClusterMesh uses an etcd image that's not multi-arch

### ISSUE THREAD

**Issue by samip5** [cilium/cilium#27899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. I enabled cluster mesh between two clusters, one of which is an single node k3s, and one is multi-node mixed-arch cluster.
2. Notice that the etcd-init on the clustermesh-apiserver pod fail to start due to it getting scheduled to an arm64 node and the image not being arm64 friendly.

### Cilium Version

cilium-cli: v0.12.1 compiled with go1.18.5 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.14.1
cilium image (running): v1.14.1

### Kernel Version

Linux w-amd-2 6.1.38-060138-generic #202307070815 SMP PREEMPT_DYNAMIC Sat Jul  8 00:45:13 UTC 2023 x86_64 GNU/Linux
Linux w2 5.19.0-1022-raspi #29-Ubuntu SMP PREEMPT Thu Jun 22 12:14:01 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.3",
    "gitCommit": "25b4e43193bcda6c7328a6d147b1fb73a33f1598",
    "gitTreeState": "archive",
    "buildDate": "2023-08-19T06:38:21Z",
    "goVersion": "go1.20.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1",
  "serverVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.4+k3s1",
    "gitCommit": "36645e7311e9bdbbf2adb79ecd8bd68556bc86f6",
    "gitTreeState": "clean",
    "buildDate": "2023-07-27T22:34:28Z",
    "goVersion": "go1.20.6",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

### Relevant log output

```shell
k logs -n kube-system clustermesh-apiserver-6b6f446b44-26s47 -c etcd-init
exec /bin/sh: exec format error
```

### Anything else?

The upstream etcd ('quay.io/coreos/etcd:v3.4.13') image cannot be used or at least it should have an nodeSelector that only schedules on amd64.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for logging this @samip5, I'll label it so that it goes into the agent queue.

**Comment by aanm** [comment]
blocked by https://github.com/cilium/cilium/issues/23770

**Comment by samip5** [comment]
This is also a blocker for using arm64-only clusters with the cluster mesh.

**Comment by samip5** [comment]
@youngnick This is not stale right?

**Comment by giorio94** [comment]
Hey @samip5, please notice that `'quay.io/coreos/etcd:v3.5.4` is a multi-arch image, and it is currently used in all stable versions of Cilium. Additionally, https://github.com/cilium/cilium/pull/29109 will further bump the etcd version on Cilium v1.15 to v3.5.10. 

It seems that you are using an old Cilium CLI version though, which still hardcoded an old etcd version (new CLI versions leverage helm to configure the clustermesh-apiserver). Could you please try again using the latest version of the Cilium CLI?
