### ISSUE TITLE
Make the migrate-svc app we use in ipsec tests more sensitive to drops

### ISSUE THREAD

**Issue by margamanterola** [cilium/cilium#27916]
### Problem description
Our IPSec tests use the migrate-svc app to detect whether or not there have been packet drops when doing upgrades or key rotations.  This app includes a [500ms sleep](https://github.com/cilium/test-connection-disruption/blob/9f8567dc62fa1bf7243eca59b502b397b40d14a2/cmd/client/main.go#L75), included to avoid saturating the system. The wait time was arbitrarily picked, no investigation was done as to how much to wait.

It would be worth reducing the time or even completely removing the sleep, because we currently miss catching some drops that are visible when using the more intensive httpperf instead.

### Implementation suggestion
Whoever is doing this work, should check that the system doesn't get overloaded. And to make this easier it would make sense to make the sleep amount a parameter to the migrate-svc app, and then iterate from the testing side.

**Comment by brb** [comment]
The source code of the ~migrate-svc~ app - https://github.com/cilium/test-connection-disruption.

> The wait time was arbitrarily picked, no investigation was done as to how much to wait.

To add historical context, the app was created to test the LB BPF maps migration in Cilium v1.5. The sleep time didn't matter for that migration path. Since then the app has been used to test flow interruptions during any Cilium upgrade.

**Comment by brb** [comment]
* https://github.com/cilium/test-connection-disruption/pull/7
* https://github.com/cilium/cilium-cli/pull/1955
* https://github.com/cilium/cilium/pull/27966

**Comment by pchaigno** [comment]
Reopening given https://github.com/cilium/cilium-cli/pull/1955#discussion_r1320041856. @brb I see it's still set to 10ms. Did you try 0ms?

**Comment by brb** [comment]
> I see it's still set to 10ms. Did you try 0ms?

Noup, I haven't. The interval is controlled by the CLI's `--conn-disrupt-dispatch-interval` param. So, it should be straightforward for anyone to try setting to 0ms.
