### ISSUE TITLE
CFP: mac spoofing protection

### ISSUE THREAD

**Issue by shen-cloud** [cilium/cilium#27955]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

In current implementation, there is no mac spoofing protection. A malicious pod in a Kubernetes cluster can use the ARP protocol to spoof the IP address of another pod on the same node. This causes other pods on the node to talk to the attacker's pod instead of the legitimate pod. With the proposal, any traffic that exits from the pod should match the source mac address and arp responses should match the assigned IP and mac address to protect from mac spoofing.

**Describe the feature you'd like**

1. source mac of traffic from the container should match pod-side veth mac
2. arp response from the container should match pod-side veth IP and mac

**(Optional) Describe your proposed solution**

1. add feature flag for mac spoof check 
2. expose pod-side veth mac to bpf code through macro like NODE_MAC
3. check source mac address for the traffic in from-container
4. check arp response in from-container

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by shen-cloud** [comment]
@aojea

**Comment by youngnick** [comment]
Thanks for logging this request @shen-cloud.

I don't think it will be actionable without some more information though - currently the justification section is not complete.

> In current implementation, there is no mac spoofing protection. It adds security concerns when ENABLE_ARP_PASSTHROUGH is present since ARP will be

If you could please update this with some more detail, including explaining more _why_ you feel that this creates security concerns, and how your proposed approach will manage those concerns, then we may be able to proceed.

**Comment by shen-cloud** [comment]
Updated the justification section. Please let me know if you need more clarifications.

**Comment by youngnick** [comment]
Thanks for that @shen-cloud, this seems reasonable. I'll mark this with the correct labels so that it can proceed. I recommend trying to make it to a community meeting to talk about this CFP if you would like to speed the process up.

**Comment by aojea** [comment]
> In current implementation, there is no mac spoofing protection. A malicious pod in a Kubernetes cluster can use the ARP protocol to spoof the IP address of another pod on the same node.

@shen-cloud AFAIK this can only happen when the veth interfaces are connected to a bridge, if the interfaces are connected to the host directly I think the mac spoofing attack is not possible

```
 ip route
default via 10.128.0.1 dev eth0 proto dhcp src 10.128.0.17 metric 1024
10.48.0.3 dev gke5704b41048c scope link
10.48.0.4 dev gkeb6e004a4593 scope link
10.48.0.5 dev gke6c0ff2ef011 scope link
10.48.0.6 dev gkeeb651ff9e59 scope link
10.48.0.7 dev gke56d91121867 scope link
10.48.0.8 dev gkec9033c7b339 scope link
10.48.0.9 dev gkeb2afbac543c scope link
10.48.0.10 dev gke59f0af01da9 scope link
10.48.0.11 dev gke7f1834ff0dd scope link
10.48.0.13 dev gke56ac0065a20 scope link
10.48.0.15 dev gke4b1eadb3301 scope link
10.48.0.17 dev gkee5340c752c5 scope link
10.48.0.18 dev gke080d905f1a3 scope link
10.48.0.19 dev gke4f04b641acc scope link
10.48.0.20 dev gke4d71cb5889d scope link
10.48.0.21 dev gke5e0b9a91f25 scope link
10.48.0.22 dev gkefdeae4002b6 scope link
10.48.0.24 dev gke1f6d7f4d677 scope link
10.48.0.25 dev gkecaf864712ac scope link
10.48.0.26 dev gkeedd6637cbaf scope link
10.48.0.28 dev gke8a4191b7cd9 scope link
10.48.0.29 dev gke748404942ab scope link
10.48.0.30 dev gke677c5c25764 scope link
```

**Comment by shen-cloud** [comment]
please keep this open as the commit is currently in review
