### ISSUE TITLE
remove 'ReverseRules' from Consumable

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2795]
Example:
If we want to allow identity B to have ingress traffic from identity A, then without connection tracking enabled, we have to allow ingress traffic to A from B as well so that A can receive replies from B - traffic must be allowed in both directions. As such, the structures within Cilium for policy have to know that identity B is allowed to receive traffic from identity A, and vice versa.

If ConnTrack is disabled for the endpoints, within the Consumables that apply to those endpoints, we have to find a way to specify which identities have been specified as being allowed to talk to each other. The current implementation in the Consumable structure is to have a map of security identities (ReverseRules) which specify which identities have specified that they want to receive traffic from that Consumable; the Consumable must know that it must allow traffic in the reverse direction so the connection can be maintained. However, this has a variety of issues associated with it:

* We enable ConnTrack for an endpoint dependent upon the policy:

`pkg/endpoint/policy.go:regeneratePolicy`:
```
// Apply possible option changes before regenerating maps, as map regeneration
	// depends on the conntrack options
	if c.L4Policy != nil {
		if c.L4Policy.RequiresConntrack() {
			opts[OptionConntrack] = optionEnabled
		}
	}
```

We thus change something that the user may have configured based on the policy. In my opinion, we should not be changing options that are configurable unless the user specifies them. 

* This does not work in a multinode setup 

The only way that the ReverseRules map is updated is based off of the `ConsumableCache`, which maps identities to Consumables on the local host. However, if the cache does not contain an entry for the identity for which the reverse rule is being added, as is the case when both identities are on separate nodes in the system, then no such reverse rule is added. This will always be the case when ConnTrack is disabled for two endpoints that are on separate nodes, as the ConsumableCache is only updated with identities local to the host on which the cilium-agent is running.

* This hasn't been working anyway upon changes in policy after the reverse rules have been updated: 

in `pkg/policy/consumer.go:BanConsumerLocked`, which is called when an identity is no longer allowed ingress access for a Consumable, there is the following logic:
```
if consumer.Reverse != nil {
	c.deleteReverseRule(id, c.ID)
}
```

However, the `Reverse` field for a Consumer is never populated anywhere in the code. Thus, in the case where endpoints are running on both nodes with ConnTrack disabled, the deletion of an identity from the `ReverseRules` of a Consumable wasn't happening when it should. 

I think this warrants us making this option immutable for an endpoint, or at least specifying clearly in our documentation in which cases this will work / not work (single node setup vs multinode setup). 

Feel free correct me if my assumptions are incorrect below :-)

**Comment by joestringer** [comment]
> We thus change something that the user may have configured based on the policy. In my opinion, we should not be changing options that are configurable unless the user specifies them.

That sounds like a pretty intuitive argument which I'm inclined to agree with. My guess would be that when this L4Policy check (and therefore L7 policy check) was introduced, the "disable CT" endpoint option was not considered. I believe that proxy_port is tightly coupled to CT in the datapath at the moment, so if we 'fixed' this to respect the user's wish to disable conntrack, it may end up breaking L7 policy application. In that case, which of the user's intentions should we respect? Disabling the CT option or implementing L7 policy?

**Comment by ianvernon** [comment]
After discussion with @tgraf, we can rip the ReverseRules out of the Consumable. I checked at what points in the ConsumableCache where identities are added to the Cache:


The only time the cache is added to is in this function: 
`pkg/policy/cache.go`:
```
func (c *ConsumableCache) GetOrCreate(id NumericIdentity, lbls *Identity) *Consumable {
	c.cacheMU.Lock()
	defer c.cacheMU.Unlock()
	if cons, ok := c.cache[id]; ok {
		return cons
	}

	c.cache[id] = NewConsumable(id, lbls, c)
	return c.cache[id]
}
```

And this function is only called twice in Cilium:
* `pkg/policy/cache.go:Init`, in which all reserved identities are added to the Cache.
* `pkg/endpoint/policy.go:SetIdentity`, which is only called upon an endpoint (that is, only for endpoints on the host)

Thus, the cache only contains identities of endpoints managed on the node itself, and thus this 'ReverseRules' model breaks down when running Cilium in a multinode setup. An alternative to fix this is to have all identities computed on every node and added to the ConsumableCache, but this is not scalable at all, as it requires synchronization with the key-value store, and because policy computation is quite costly. 

Thus, we should remove `ReverseRules` and add documentation specifying that users must add explicit policy rules to allow traffic in both directions in the case that ConnTrack is disabled for an endpoint.

**Comment by ianvernon** [comment]
Unfortunately, after trying to remove `ReverseRules`, we cannot do it so easily. When `ConnTrack` is disabled in an endpoint's configuration, despite adding rules that allow communication in both directions (from the host --> endpoint and endpoint --> host), connectivity doesn't work because adding a rule that applies to `reserved:host` doesn't work the same as applying a rule to an endpoint with label `id.server`, in that internally, the host is not really an endpoint; there is a `Consumable` with identity 1 in the `ConsumableCache`, though. The only way the Consumables representing the reserved identities to be updated is when the Consumable associated with endpoint(s) is updated to allow these reserved identities. This is done by updating the `ReverseRules` of the reserved identity `Consumables`. Thus, removing this will take some work, as we need to allow reserved-identity --> endpoint communication in the case ConnTrack is disabled for an endpoint.
