### ISSUE TITLE
[Gateway API] Cilium panic: runtime error

### ISSUE THREAD

**Issue by maxtacu** [cilium/cilium#27956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Creating an HttpRoute with missing port crashes the whole cilium-operator
```
- backendRefs:
  - name: <service-name>
    port: null
```
with the following error: 
```
panic: runtime error: invalid memory address or nil pointer dereference
```

### Cilium Version

v1.14.1

### Kernel Version

Bottlerocket OS 1.14.3
Kernel 5.15.117

### Kubernetes Version

v1.27.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maxtacu** [comment]
Currently to avoid cilium crash we have to implement kyverno policies that denies configurations with missing port number

**Comment by chaunceyjiang** [comment]
/assign @chaunceyjiang

I will try to fix this issue.

**Comment by chaunceyjiang** [comment]
Additional panic information:
![image](https://github.com/cilium/cilium/assets/17962021/e6b5932c-b027-47ef-abd6-f8362e4eb9fd)
