### ISSUE TITLE
ENI: calculateExcessIPs not consider minAllocate when usedIP+preAllocate less minAllocate and availableIPs greate than MinAllocate

### ISSUE THREAD

**Issue by wu0407** [cilium/cilium#27970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I found the operator released more ips than expected, and it needs to allocate ips in the next sync cycle.
It causes unnecessary calls to cloud APIs and the Instability of the IP resource pool.

In this situation need to Release ip:
```
availableIPs:      61,
usedIPs:           29,
preAllocate:       20,
minAllocate:       60,
maxAboveWatermark: 0,
```
release ip count is `availableIPs-usedIPs-preAllocate=61-29-20=12`. But According to the design it only excess 1 IP `availableIPs -minAllocate=61-60=1` 

Next resync cycle after 12 IP is released,  it is needed ip:
```
availableIPs:     49,
usedIPs:          29,
preAllocate:      20,
minAllocate:      60,
maxAllocate:      0,
```
need ip count is `minAllocate-availableIPs=60-49=11`

The test code for this situation is incorrect. But the comment `1 excess` is right. 
https://github.com/cilium/cilium/blob/3a23173e76cf5e379ff58d01cd74c5a2a57765ae/pkg/ipam/node_test.go#L42

### Cilium Version

master--all release version

### Kernel Version

no

### Kubernetes Version

no

### Anything else?

https://github.com/cilium/cilium/blob/3a23173e76cf5e379ff58d01cd74c5a2a57765ae/pkg/ipam/node.go#L327-L352

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
According to the documentation, `minAllocate` is only used in the beginning, and not during operations:

https://docs.cilium.io/en/stable/network/concepts/ipam/eni/#ipam-eni

> `spec.ipam.min-allocate`
>    The minimum number of IPs that must be allocated when the node is first bootstrapped. [..] After reaching this watermark, the PreAllocate and MaxAboveWatermark logic takes over to continue allocating IPs.

So I think the behavior is correct. If you want to avoid excess API calls, you can instead set `MaxAboveWatermark` maybe?

**Comment by wu0407** [comment]
Although the maxAboveWatermark setting can help reduce excess IPs, it does not solve the problem of excess API calls. Let's say you set the maxAboveWatermark to 5, and the result shows that there are 7 excess IPs (12-5=7).
Because maxAboveWatermark is a static setting, the stat of used IPs is dynamic, The aim is to prevent having an excessive number of IPs that exceed the actual need.

**Comment by gandro** [comment]
I'm not sure I understand - is the problem that `maxAboveWatermark` is an absolute value, not a percentage? Or is it that `maxAboveWatermark` is not respected when releasing excess IPs?

**Comment by wu0407** [comment]
maxAboveWatermark is a related value. I expect not to release IP and allocate IP when usedIPs+preAllocate not over` minAllocate + maxAboveWatermark` and `used IPs` less than `minAllocate + maxAboveWatermark`. It is difficult to achieve this goal by setting maxAboveWatermark.

In this case, we can set maxAboveWatermark to 11 to avoid releasing IP and allocate IP.  But when usedIPs is 28, it cannot meet this goal. It will release 2 IPs and allocate 1 IP.

```
availableIPs:      61,
usedIPs:           28,
preAllocate:       20,
minAllocate:       60,
maxAboveWatermark: 11,
```
The release IP count is `availableIPs-usedIPs-preAllocate-maxAboveWatermark`=61-28-20-11=2

After the release 2 IPs
```
availableIPs:      59,
usedIPs:           28,
preAllocate:       20,
minAllocate:       60,
maxAboveWatermark: 11,
```
The needed IP count is `minAllocate-availableIPs=60-59=1`

**Comment by gandro** [comment]
I see, thanks. According to the documentation, `minAllocate` should not be used to compute the needed count after the initial set of allocations. But I do see that this seems no longer the case now that we have IP release. It seems the `minAllocate` logic is indeed broken at the moment.

Thanks for explaining this to me, I now agree that this is a bug. We should however also update the documentation to document the new formula.
