### ISSUE TITLE
Cilium v1.14.2 with Kubernetes v1.28 is unstable

### ISSUE THREAD

**Issue by dghubble** [cilium/cilium#27982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Starting in Cilium v1.14.0 on Kubernetes v1.28.1, Cilium agents can lose connection to `kube-apisever` when using `kube-proxy` and the kubernetes service ClusterIP. This looks closely related to https://github.com/cilium/cilium/issues/27900

Cilium supports hybrid modes in which Cilium can coexist with `kube-proxy` while performing some or all of its responsibilities (e.g. there are reasons one might not wish to remove kube-proxy). Cilium v1.14 removed the `kube-proxy-replacement` `partial` mode and changed it to either `true` or `false`. But something else appears to have changed:

Consider a cluster with a `kube-proxy` daemonset. `kube-proxy` uses `ipvs` to load balance the default `kubernetes` service ClusterIP to a kube-apiserver endpoint.

```
kubectl get service
NAME              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
kubernetes        ClusterIP   10.3.0.1       <none>        443/TCP                      26h

kubectl get endpoints
NAME              ENDPOINTS                                         AGE
kubernetes      10.0.8.71:6443                                    26h
```

Cilium agent's respect the default `KUBERNETES_SERVICE_HOST` by default (10.3.0.1), which usually works fine. 

```
level=info msg="Establishing connection to apiserver" host="https://10.3.0.1:443" subsys=k8s-client
level=info msg="Establishing connection to apiserver" host="https://10.3.0.1:443" subsys=k8s-client
level=error msg="Unable to contact k8s api-server" error="Get \"https://10.3.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.3.0.1:443: connect: operation not permitted" ipAddr="https://10.3.0.1:443" subsys=k8s-client
```

But I've noticed there is a (yet unknown) sequence of events whereby connectivity to the kubernetes service Cluster IP breaks on certain nodes. **This can happen after days of otherwise running normally.** I think it's related to node restarts because I see it more on spot instances. The result is that the Cilium agent on those nodes crashloops, unable to reach the apiserver.

### Workaround

The workaround is updating Cilium agent to have an explicit kube-apiserver IP address or DNS record in a `KUBERNETES_SERVICE_HOST` environment variable, but this should not be neccessary and is undesired. Workloads (including Cilium agent) on clusters with `kube-proxy` should be able to use in-cluster service discovery

I suspect the wrinkle here is that Cilium itself can interact with Kubernetes Service mappings. That or something about Kubernetes v1.28 itself.

### Scope

I've observed in this with KubeProxyReplacement `false` (enabling the individual features) and KubeProxyReplacement enabled.

```
kube-proxy-replacement:  "false"
bpf-lb-sock: "true"
bpf-lb-external-clusterip: "true"
enable-node-port: "true"
enable-health-check-nodeport: "false"
enable-external-ips: "true"
enable-host-port: "true"
```

And with KubeProxyReplacement `true`

```
kube-proxy-replacement:  "true"
```

Neither mode is related to the fix.

### Cilium Version

Cilium v1.14.0, v1.14.1

### Kernel Version

Linux ip-10-0-11-132 6.4.7-200.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:22:11 UTC 2023 aarch64 GNU/Linux

### Kubernetes Version

Kubernetes v1.28.1

### Anything else?

The fallback here should be kube-proxy's IPVS, which does program the right LVS rules

```
ipvsadm -L -n
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.3.0.1:443 rr
  -> 10.0.8.71:6443               Masq    1      0          0
  ...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dghubble** [comment]
When this occurs on a node, the kubernetes Service cluster IP can't be used from the host, which aligns with what Pods see.

```
curl https://10.3.0.1
hangs
```

Once Cilium agents start (using the workaround above), the same curl command works from hosts. Seems like Cilium having run on the node in the past interferes with IPVS functionality.

**Comment by youngnick** [comment]
Thanks for this issue @dghubble, and especially for the great investigation.

Cilium 1.14 actually only supports up to Kubernetes 1.27 - the client upgrade has only been merged into `main` at this point. It is odd that there's much more compatibility issues than usual (see #27900 and #27965 for other examples), so we'll see if we can do something to resolve all of these. Feels like at the very least we should call out that there are known issues with Cilium 1.14.x and Kubernetes 1.28, but I'll talk to some other folks and see what the consensus is.

**Comment by jspaleta** [comment]
My reproducer is probably an entirely different issue than initially reported, same symptoms but high likelihood a different problem..maybe even a Kind specific problem.
Should I file a new issue to track that?

I'm going to retest now using my local k3s home lab and avoid the complication of cluster node as containers sharing a common kernel.

**Comment by Silvest89** [comment]
This actually happens after a node reboot. I am using a k3s cluster with kured to have automatic reboots after updates. It won't be able to access the kube-dns anymore so it cannot reach anything.

**Comment by youngnick** [comment]
It looks like there may be two issues in play here: An upstream issue (kubernetes/kubernetes#120247), and possibly #27848. The upstream issue fix is in and will be included in Kubernetes 1.28.2, due out soon, and the other investigation is ongoing at #27848.

**Comment by aanm** [comment]
@dghubble @Silvest89 would you be able to test it again with Kubernetes 1.28.2? Thank you

**Comment by zhurkin** [comment]
> @dghubble @Silvest89 would you be able to test it again with Kubernetes 1.28.2? Thank you
I don't know if the information will be useful .
`cicd-kub-control-01:/home/icce# cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             1 errors, 3 warnings
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 3, Unavailable: 3/3
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium             Pending: 3
                       cilium-operator    Running: 1
Cluster Pods:          0/2 managed by Cilium
Helm chart version:    1.15.0-pre.0
Image versions         cilium             quay.io/cilium/cilium:v1.15.0-pre.0: 3
                       cilium-operator    quay.io/cilium/operator-generic:v1.15.0-pre.0: 1
Errors:                cilium             cilium          3 pods of DaemonSet cilium are not ready
Warnings:              cilium             cilium-9ch5r    pod is pending
                       cilium             cilium-f8zgf    pod is pending
                       cilium             cilium-j6kql    pod is pending
cicd-kub-control-01:/home/icce# kubectl get nodes
NAME                  STATUS   ROLES           AGE     VERSION
cicd-kub-control-01   Ready    control-plane   3d1h    v1.28.2
cicd-kub-control-02   Ready    control-plane   2d23h   v1.28.2
cicd-kub-control-03   Ready    control-plane   2d22h   v1.28.2
cicd-kub-control-01:/home/icce# kubectl get po -A | grep -e cilium -e core
kube-system   cilium-9ch5r                                  0/1     Init:CreateContainerError   0          98s
kube-system   cilium-f8zgf                                  0/1     Init:CreateContainerError   0          98s
kube-system   cilium-j6kql                                  0/1     Init:CreateContainerError   0          98s
kube-system   cilium-operator-756dfd6d4d-nfxk5              1/1     Running                     0          98s
kube-system   coredns-5dd5756b68-brfj8                      0/1     Pending                     0          2d16h
kube-system   coredns-5dd5756b68-ql7mw                      0/1     Pending                     0          2d16h
cicd-kub-control-01:/home/icce# kubectl -n kube-system logs cilium-9ch5r
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Error from server (BadRequest): container "cilium-agent" in pod "cilium-9ch5r" is waiting to start: PodInitializing`

**Comment by dghubble** [comment]
Preliminarily, on a [Kubernetes v1.28.2](https://github.com/poseidon/typhoon/pull/1380) cluster, I've not been able to reproduce the issue. Restarting nodes, Cilium can reach the apiserver just fine, which I suspected was the trigger before. I observed the original issue in real production clusters though, after several days of use, so I'll have more confidence in a few days.

**Comment by julianwiedmann** [comment]
> Preliminarily, on a [Kubernetes v1.28.2](https://github.com/poseidon/typhoon/pull/1380) cluster, I've not been able to reproduce the issue. Restarting nodes, Cilium can reach the apiserver just fine, which I suspected was the trigger before. I observed the original issue in real production clusters though, after several days of use, so I'll have more confidence in a few days.

Thank you for the feedback! Let's leave it in `need-more-info` then until you have full confidence.

**Comment by aojea** [comment]
This seems a duplicate of https://github.com/cilium/cilium/issues/27900, should we close it @aanm @julianwiedmann ?

**Comment by dghubble** [comment]
I've seen this occur once on a new cluster with Kubernetes v1.28.2 and Cilium v1.14.2. Most clusters have been fine since those upgrades.

Is there anything specific I should be collecting? To confirm it's the same issue. Unfortunately, I usually have to apply mitigations asap and can't afford to leave clusters in this broken state for long.

**Comment by Silvest89** [comment]
@aanm @dghubble 
Upgraded my cluster from 1.27.6 to 1.28.2. Everything seems to be working smooth =]

**Comment by dghubble** [comment]
This issue can still happen. I've had to explicitly set a `KUBERNETES_SERVICE_HOST` to an external DNS record so that Cilium can reliably find the apiserver. This should not be required, in-cluster kube-proxy should be sufficient.

```
level=info msg="Establishing connection to apiserver" host="https://10.3.0.1:443" subsys=k8s-client
level=error msg="Unable to contact k8s api-server" error="Get \"https://10.3.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.3.0.1:443: connect: operation not permitted" ipAddr="https://10.3.0.1:443" subsys=k8s-client
level=error msg="Start hook failed" error="Get \"https://10.3.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.3.0.1:443: connect: operation not permitted" function="client.(*compositeClientset).onStart" subsys=hive
```

**Comment by aanm** [comment]
@dghubble that could be related with an issue with kube-proxy and not Cilium itself as you have pointed it out that connecting to connecting directly to an external DNS record it works but not with a cluster IP, for which kube-proxy does the service translation.

**Comment by dghubble** [comment]
That was my initial suspicion as well, but kube-proxy creates the usual IPVS/LVS rules doesn't change much btw Kubernetes releases. 

The service routing responsibility boundaries seem unclear and this is a place that having all these rules handled in the kernel / ebpf bites, it's not clear what's going on.

* Initially there is only `kube-proxy` and Kubernetes Service traffic is routed correctly
* Cilium can start and connect to the `kubernetes` Kubernetes Service (i.e. in-cluster, `kubernetes`, 10.3.0.1)
* Cilium itself is now also responsible for Kubernetes Service routing with kube proxy replacement features turned on. Presumably Cilium writes some eBPF rules related to 
* Some time later, Cilium restarts and now 10.3.0.1 does not route to the apiserver anymore. Neither IPVS rules nor any eBPF rules left behind handle this, connections hang.

I'm suspecting this is some sort of stale state issue and rebooting the host would clear out any old eBPF rules or whatever is causing a conflict here.

You'll probably not see many reports of this because Helm chart users as led to provide a hardcoded apiserver IP (still the workaround we use), which of course avoids needingusing Kubernetes Service routing to reach the apiserver (at the expense of hardcoding). But this all used to work fine and ought to work fine.

Next time we provision v1.28.2+ clusters, I can cross reference by using flannel/Calico to verify this is not a kube-proxy issue. And revert to Cilium 1.13 to check it's not related to Kubernetes 1.28 (although I imagine Cilium doesn't officially support that combination either).

**Comment by squeed** [comment]
hey there, @dghubble :wave:. Long time, no see.

Anyways.

The fiddly details of BPF, conntrack, and other kernel state isn't my wheelhouse. Like you said, it's likely there's bad kernel state somewhere that is breaking load balancing / service IPs from the host to the apiserver. Not good. I agree that nodes in this state can't be left around for too long.

You can get a pretty quick (~5 second) dump of the node's state by executing `cilium-bugtool` directly. This is a lot faster than a full sysdump. It includes bpf map state, conntrack, and other important details. The next time you find a node in this state, can you run 

```
$ kubectl -n kube-system exec $CILIUM_POD -- cilium-bugtool --archive -o gz -t - > bugtool.tgz
```

and either attach that to the issue, or reach out privately? Thanks!

**Comment by Silvest89** [comment]
@squeed 
I myself have been running stable so far. Should one of my nodes reach that state I will keep in mind to do that!

**Comment by squeed** [comment]
I was thinking about this some more, and I realized there's a bit of a configuration issue. With `bpf-lb-sock` enabled, Cilium will be load-balancing it's own connections to the apiserver on the `connect()` syscall, rather than relying on kube-proxy to set up ipvs rules. That works as long as kube-proxy is there to "bootstrap" the service IP, but now we have a chicken-egg problem. If the set of apiservers ever rotates out, Cilium will be forever stuck with a stale backend map, and it can't connect to the apiserver to get a fresh one.

This is why we require connecting to the "real" apiserver address when kube-proxy is removed. Perhaps we need to exclude the agent process from socket-lb.

**Comment by tedli** [comment]
Hi,

**Comment by tedli** [comment]
Hi,

My setup of kubernetes 1.28.2 with cilium 1.14.2 works well (kube-proxy replacement strict), except for that in-cluster `apiserver` service, can't be accessed in pods at different nodes.

1. The cluster was set up by `kubadm` with skip addon kube-proxy.
2. The cluster had 2 nodes, one for control-plane, apiserver listened on node default ip, the other joined as worker.
3. The cilium CNI was installed with explicit specifing `k8sServiceHost: 10.123.45.67, k8sServicePort: 6443`.
4. The apiserver clueter ip can be accessed at nodes, on both control-plane node, worker node, `curl -kv https://100.64.0.1` returns.
5. In pods scheduled to the control-plane node, `curl -kv https://100.64.0.1` returns.
6. In pods scheduled to the worker node, `curl -kv https://100.64.0.1`, got `OpenSSL SSL_connect: Connection reset by peer`.
7. Deploy pods on both nodes, expose by serivce, curl this service on both nodes, pods on both nodes, returns as expect.

```
[root@chief-01 ~]# kubectl get no -o wide
NAME                           STATUS   ROLES           AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE        KERNEL-VERSION             CONTAINER-RUNTIME
chief-01.cluster-01.k8s.dev    Ready    control-plane   6h39m   v1.28.2   10.123.45.67   <none>        Anolis OS 8.8   5.10.134-15.2.an8.x86_64   containerd://1.7.6
worker-01.cluster-01.k8s.dev   Ready    <none>          6h37m   v1.28.2   10.123.45.68   <none>        Anolis OS 8.8   5.10.134-15.2.an8.x86_64   containerd://1.7.6
[root@chief-01 ~]# kubectl get svc -o wide
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE     SELECTOR
kubernetes   ClusterIP   100.64.0.1   <none>        443/TCP   6h39m   <none>
[root@chief-01 ~]# kubectl get ep -o wide
NAME         ENDPOINTS           AGE
kubernetes   10.123.45.67:6443   6h39m
```

[bugtool.chief-01.tar.gz](https://github.com/cilium/cilium/files/12912955/bugtool.chief-01.tar.gz)
[bugtool.worker-01.tar.gz](https://github.com/cilium/cilium/files/12912957/bugtool.worker-01.tar.gz)

**Comment by dghubble** [comment]
@squeed 👋🏻 long time! Yeah, my suspicion is that it's related to this overlapping responsibility kube-proxy and Cilium have for managing the apiserver's own Kubernetes Service traffic. Having `socket-lb` optionally exclude the apiserver itself could be helpful. Odd part is this was never an issue before, I'm not sure if something changed here with the shifting kube-proxy modes. Next Kubernetes patch release, I should have an opportunity to test this again and capture logs (or if I find time sooner).

@tedli The workaround to this issue is giving Cilium explicit IP addresses for the apiserver (undesired). If you're seeing issues in that case, you're probably describing a separate issue.

**Comment by dghubble** [comment]
I saw it recur on one node today! A Cilium agent pod was unable to reach kube-apiserver. My usual workaround is to modify the Cilium DaemonSet to explicitly set a `KUBERNETES_SERVICE_HOST`, but this time I tried rebooting the host, which does mitigate the issue. This seems to support the theory that old BPF rules are lying around preventing the new Cilium Pod from reaching kube-apiserver via kube-proxy, as it normally can.

Bugtool: https://storage.googleapis.com/dghubble/bugtool.tar.gz (too big for GitHub)

**Comment by squeed** [comment]
So, looking at the bugtool, I see the following set of backends for the apiserver service:

```
10.3.0.11:443        0.0.0.0:0 (16) (0) [ClusterIP]   (ignore this bit)
                     10.2.1.160:443 (16) (2)          
                     10.2.2.35:443 (16) (1)
```

As of the time of the bugtool, are those correct? My theory is that cilium is missing changes to the `default/kubernetes` service, and once that happens it can't recover. (This is why you should not use the apiserver ClusterIP with socket-lb).

Separately, #25169 may also be relevant to this.

**Comment by dghubble** [comment]
Yeah, this looks ood. Those two backend IPs are from the Pod CIDR range (`10.2.0.0/16`). But the apiserver runs on controller/master node(s) with host network (`10.0.4.0/22` in this case). Kubernetes and kube-proxy see this as I'd expect, just one apiserver/master in this cluster:

```
kubectl get endpoints kubernetes
NAME         ENDPOINTS        AGE
kubernetes   10.0.4.26:6443   29d
```

```
kubectl get pods -n kube-system -o wide
NAME                                                    READY   STATUS    RESTARTS      AGE   IP           NODE                            NOMINATED NODE     
kube-apiserver-magnesium.region.dghubble.io            1/1     Running   3 (33h ago)   29d   10.0.4.26    magnesium.region.dghubble.io   <none>           <none>
```

I'm not sure what the Pod IPs Cilium was seeing correspond to anymore. Cilium now shows the right backend.

```
ID   Frontend             Service Type   Backend                          
...
2    10.3.0.1:443         ClusterIP      1 => 10.0.4.26:6443 (active)
```

**Comment by dghubble** [comment]
Btw, I've preferred Cilium using in-cluster discovery (i.e. `10.3.0.1` via kube-proxy) in a Kubernetes distro because it's platform agnostic. Giving Cilium an IP hardcodes a value (and to support multi-master I'd need to create VIPs in a platform agnostic way on behalf of users) and giving Cilium a DNS record pointing to the apiserver is hard to do in a platform agnostic way (e.g. public vs private clusters use different FQDNs depending on AWS private Endpoints Azure PrivateLink, etc). Though that may be the way we go. The Cilium docs just say give us the real apiserver address _somehow_.

In theory, Cilium could just read the `kubernetes` endpoints directly and do it's own load balancing (since `client-go` doesn't load balance multiple IPs) similar to what `kube-proxy` is providing. Distros wouldn't have to decide how to give Cilium a "real" apiserver address.


If you give it an IP

**Comment by dghubble** [comment]
I suspect that would fix this situation. Did Cilium 1.13 with partial kube-proxy previously work this way? It's odd this became a problem so recently.

**Comment by squeed** [comment]
I believe 1.14 brings changes to the socket-lb, but that’s not my area of expertise. @aditighag, any pointers?

**Comment by n-able-consulting** [comment]
I was fixated on this issue for a day before I found this threat. 
I am using cilium 1.14.4, with my own programmed provisioning. Suddenly it breaks when enabling OIDC...
I run on bare metal. I have multiple interfaces to different VLANs, so I can use the 'internal' interface in my configuration. Technically, it's no big deal. 

I have problems with what it means when I do a high-available setup because I then have to address the 'outside' load balancer for 'in cluster traffic'. I do not like it. Also, I can not imagine this is the way it is meant to be.

We built in PKI and overlay to secure all communication, then we break it open to talk over the 'outside' infrastructure network. Instead of using the build in overlay Kubernetes service. I can not believe this?

**Comment by n-able-consulting** [comment]
Issue is older. Also 1.13.9 breaks when configuring OIDC on api-server...

**Comment by n-able-consulting** [comment]
I can concure it is a 1.28 issue. Provisioning k8s 1.27 Cilium does not break, after configuring OIDC. With breaking I refer to the familiar issue: Unable to contact k8s api-server / Forbidden 10.2.0.1;6443. 
It works when setting k8sServiceHost in 1.28, which, as I stated above, in my opinion, is digging a whole out of the k8s security plane... And as such no solution. 
If not clear yet, I do not like this Cilium feature.

**Comment by dghubble** [comment]
I ultimately had to adapt our Kubernetes distro to tell Cilium the DNS name resolving to any of the apiservers. The approach and resolver varies based on the cloud provider.

It's a shame, Cilium used to support the in-cluster kubernetes ClusterIP, but now effectively relies on an external resolver.
