### ISSUE TITLE
Cilium allow for seamless datapath map live updates

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#2799]
Commits like 444aa65b47bb2b3 are a bit problematic with regards to live updates of Cilium in that the map properties change and thus the loader will try to retrieve already pinned maps first and find that they don't match the properties from the object file. With regards to calls, it's still fairly straight forward in that the daemon could temporarily rename those pinned maps, reload its programs and then remove them. It gets more complicated when we change maps that hold data entries in them; potentially once CTF (C type format) for BPF gets merged, we could use this to find the diff in the map key/val structures and set it to some same default in the migration phase. Other, approach without data migration could also be that Cilium daemon just uses it's own BPF fs mount instance (different location that the default /sys/fs/bpf/), moves the mount instance to a different location if present from prior Cilium run, mounts the new instance to that original location, and after all has been set up, it un-mounts the old instance which then drops all the old maps. cc @danwent

**Comment by tgraf** [comment]
We have already declared several maps non-persistent which causes such maps to be deleted before they get recreated. We already do this for the proxymap.

Do we even need to pin the non-policy calls map?

``` c
/* Private per EP map for internal tail calls */
struct bpf_elf_map __section_maps CALLS_MAP = {
        .type           = BPF_MAP_TYPE_PROG_ARRAY,
        .id             = CILIUM_MAP_CALLS,
        .size_key       = sizeof(__u32),
        .size_value     = sizeof(__u32),
        .pinning        = PIN_GLOBAL_NS,
        .max_elem       = CILIUM_CALL_SIZE,
};
```

**Comment by borkmann** [comment]
Yes, we need to pin all kind of call maps as otherwise they would flush their programs (urefs dropping to zero if there are no user space reference points anymore - needed to break up circular dependencies between prog/tail call maps).

**Comment by tgraf** [comment]
This hasn't been updated in a long time. Closing.
