### ISSUE TITLE
Gateway API HttpRoute cannot strip path prefix

### ISSUE THREAD

**Issue by nxy7** [cilium/cilium#27994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium HttpRoute URLRewrite implementation doesn't conform to Kubernetes [guidlines](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPPathModifier) in 2 aspects.
First - it doesn't accept empty 'replace prefix'
Second - given `PathPrefix: /echo`, `replacePrefixMatch: /` and request to `{someAddrs}/echo/test` leaves you with `{someAddrs}//test`, so double slash.

I think the first one is Cilium's problem
https://github.com/cilium/cilium/blob/762d8c9ed13d4d2bced71d4b04c1a30de149bf93/operator/pkg/model/translation/envoy_virtual_host.go#L273-L275
If PathPrefix is empty it doesn't apply the rewrite. According to [Kubernetes guidlines](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPPathModifier) empty prefix should be allowed.

Second issue is probably out of Cilium hands and is envoy issue. If I'm not mistaken it's envoy that actually does url manipulation and doesn't make sure that output url is valid. Still if Cilium accepted empty prefixes I think you could avoid double '/' by making  `replacePrefixMatch: ""` in URLRewrite.

### Cilium Version

1.15.0-pre.0

### Kernel Version

Linux 6.5

### Kubernetes Version

1.27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nxy7** [comment]
Looking at your PR am I correct to assume that you want to conform to Kubernetes API, but this PR will not fix the issue with double '/'? Should I maybe open issue on envoy side?

**Comment by chaunceyjiang** [comment]
> you want to conform to Kubernetes API,

Yes.

>  but this PR will not fix the issue with double '/'? 

I haven't found the reason for the appearance of double '/' yet, I'm still researching it.

> Should I maybe open issue on envoy side?

I cannot answer at the moment. It may take me some time to see if I can find the root cause of this problem.

**Comment by nxy7** [comment]
I don't mind waiting, just wanted to know what's current status after this PR. Thanks for answering so quickly ;-)
