### ISSUE TITLE
Traffic_direction label of hubble_flow/tcp metrics is inverse

### ISSUE THREAD

**Issue by anubhabMajumdar** [cilium/cilium#28006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# Cilium Image

```
image: quay.io/cilium/cilium:v1.14.1@sha256:edc1d05ea1365c4a8f6ac6982247d5c145181704894bb698619c3827b6963a72
```

# Cilium configuration

```
hubble-metrics: tcp:sourceContext=pod;destinationContext=pod;labelsContext=traffic_direction,source_pod,destination_pod
    flow:sourceContext=pod;destinationContext=pod;labelsContext=traffic_direction,source_pod,destination_pod
```

# Environment

```
$ kgno -owide
NAME                                STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-nodepool1-27817402-vmss000000   Ready    agent   24h   v1.26.6   10.224.0.5    <none>        Ubuntu 22.04.3 LTS   5.15.0-1041-azure   containerd://1.7.1+azure-1
aks-nodepool1-27817402-vmss000001   Ready    agent   24h   v1.26.6   10.224.0.4    <none>        Ubuntu 22.04.3 LTS   5.15.0-1041-azure   containerd://1.7.1+azure-1

$ kgpo -l k8s-app=cilium -owide        
NAME           READY   STATUS    RESTARTS   AGE     IP           NODE                                NOMINATED NODE   READINESS GATES
cilium-8jdtg   1/1     Running   0          9m12s   10.224.0.6   aks-nodepool1-27817402-vmss000002   <none>           <none>
cilium-9gtms   1/1     Running   0          9m12s   10.224.0.5   aks-nodepool1-27817402-vmss000000   <none>           <none>

$ kgpo -l app=agnhost -owide         
NAME        READY   STATUS    RESTARTS   AGE    IP           NODE                                NOMINATED NODE   READINESS GATES
agnhost-a   1/1     Running   0          100m   10.0.0.227   aks-nodepool1-27817402-vmss000000   <none>           <none>
agnhost-b   1/1     Running   0          100m   10.0.1.225   aks-nodepool1-27817402-vmss000001   <none>           <none>
```

# Generate traffic

```
$ k exec -it agnhost-a curl 10.0.1.225
agnhost-b
```

# Check hubble metrics

### Node aks-nodepool1-27817402-vmss000000

```
root@aks-nodepool1-27817402-vmss000000:/# curl -s localhost:9965/metrics | grep hubble_flow | grep agnhost
hubble_flows_processed_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",protocol="TCP",source="kube-system/agnhost-b",source_pod="agnhost-b",subtype="to-endpoint",traffic_direction="egress",type="Trace",verdict="FORWARDED"} 3
hubble_flows_processed_total{destination="kube-system/agnhost-b",destination_pod="agnhost-b",protocol="TCP",source="kube-system/agnhost-a",source_pod="agnhost-a",subtype="to-overlay",traffic_direction="egress",type="Trace",verdict="FORWARDED"} 5
root@aks-nodepool1-27817402-vmss000000:/#
root@aks-nodepool1-27817402-vmss000000:/#
root@aks-nodepool1-27817402-vmss000000:/# curl -s localhost:9965/metrics | grep hubble_tcp | grep agnhost
hubble_tcp_flags_total{destination="kube-system/agnhost-a",destination_pod="agnhos -a",family="IPv4",flag="FIN",source="kube-system/agnhost-b",source_pod="agnhost-b",traffic_direction="egress"} 1
hubble_tcp_flags_total{destination="kube-system/agnhost-a",destination_pod="agnhos -a",family="IPv4",flag="SYN-ACK",source="kube-system/agnhost-b",source_pod="agnhos -b",traffic_direction="egress"} 1
hubble_tcp_flags_total{destination="kube-system/agnhost-b",destination_pod="agnhos -b",family="IPv4",flag="FIN",source="kube-system/agnhost-a",source_pod="agnhost-a",traffic_direction="egress"} 1
hubble_tcp_flags_total{destination="kube-system/agnhost-b",destination_pod="agnhos -b",family="IPv4",flag="SYN",source="kube-system/agnhost-a",source_pod="agnhost-a",traffic_direction="egress"} 1
```
### Node aks-nodepool1-27817402-vmss000001

```
root@aks-nodepool1-27817402-vmss000001:/# curl -s localhost:9965/metrics | grep hubble_flow | grep agnhost
hubble_flows_processed_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",protocol="TCP",source="kube-system/agnhost-b",source_pod="agnhost-b",subtype="to-overlay",traffic_direction="ingress",type="Trace",verdict="FORWARDED"} 3
hubble_flows_processed_total{destination="kube-system/agnhost-b",destination_pod="agnhost-b",protocol="TCP",source="kube-system/agnhost-a",source_pod="agnhost-a",subtype="to-endpoint",traffic_direction="ingress",type="Trace",verdict="FORWARDED"} 5
root@aks-nodepool1-27817402-vmss000001:/#
root@aks-nodepool1-27817402-vmss000001:/# curl -s localhost:9965/metrics | grep hubble_tcp | grep agnhost
hubble_tcp_flags_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",family="IPv4",flag="FIN",source="kube-system/agnhost-b",source_pod="agnhost-b",traffic_direction="ingress"} 1
hubble_tcp_flags_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",family="IPv4",flag="SYN-ACK",source="kube-system/agnhost-b",source_pod="agnhost-b",traffic_direction="ingress"} 1
hubble_tcp_flags_total{destination="kube-system/agnhost-b",destination_pod="agnhost-b",family="IPv4",flag="FIN",source="kube-system/agnhost-a",source_pod="agnhost-a",traffic_direction="ingress"} 1
hubble_tcp_flags_total{destination="kube-system/agnhost-b",destination_pod="agnhost-b",family="IPv4",flag="SYN",source="kube-system/agnhost-a",source_pod="agnhost-a",traffic_direction="ingress"} 1
```

# Issue

On node `aks-nodepool1-27817402-vmss000000`, we observe these metric (this node hosts agnhost-a):

```
hubble_flows_processed_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",protocol="TCP",source="kube-system/agnhost-b",source_pod="agnhost-b",subtype="to-endpoint",traffic_direction="egress",type="Trace",verdict="FORWARDED"} 3

hubble_tcp_flags_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",family="IPv4",flag="SYN-ACK",source="kube-system/agnhost-b",source_pod="agnhos -b",traffic_direction="egress"} 1
```

Question - if `source_pod=agnhost-b` and `destination_pod=agnhost-a`, how can `traffic_direction` be `egress` on this node? 

Same for node `aks-nodepool1-27817402-vmss000001`.

I think the `traffic_direction` label is inverse of what it's supposed to be.

### Cilium Version

`v1.14.1@sha256:edc1d05ea1365c4a8f6ac6982247d5c145181704894bb698619c3827b6963a72`

### Kernel Version

```
root@aks-nodepool1-27817402-vmss000001:/# uname -a
Linux aks-nodepool1-27817402-vmss000001 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-19T16:11:29Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20230907-131025.zip](https://github.com/cilium/cilium/files/12553062/cilium-sysdump-20230907-131025.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anubhabMajumdar** [comment]
I was experimenting with the code a little bit, and I edited the way we decode L3/4 traffic direction - https://github.com/anubhabMajumdar/cilium/blob/28dd609df422466647f5b0d6d6fdff4db73a16b0/pkg/hubble/parser/threefour/parser.go#L480 .

There may be some subtle bug in that piece of code? The way we are decoding the direction maybe wrong?

**Comment by anubhabMajumdar** [comment]
@julianwiedmann Can I help out with this bug? Would love to contribute to fix this issue.

**Comment by joestringer** [comment]
> On node aks-nodepool1-27817402-vmss000000, we observe these metric (this node hosts agnhost-a):
> 
> ```
> hubble_flows_processed_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",protocol="TCP",source="kube-system/agnhost-b",source_pod="agnhost-b",subtype="to-endpoint",traffic_direction="egress",type="Trace",verdict="FORWARDED"} 3
> 
> hubble_tcp_flags_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",family="IPv4",flag="SYN-ACK",source="kube-system/agnhost-b",source_pod="agnhos -b",traffic_direction="egress"} 1
> ```
> 
> Question - if source_pod=agnhost-b and destination_pod=agnhost-a, how can traffic_direction be egress on this node?
> 
> Same for node aks-nodepool1-27817402-vmss000001.
> 
> I think the traffic_direction label is inverse of what it's supposed to be.

I suspect that this is a question of "flow direction" vs. "packet direction". The field is called `traffic_direction`, which is a bit ambiguous. If we look at the packet in the second metric, we see that it is a SYN-ACK. This implies that the packet is a reply for an egress connection.

If you search for `traffic_direction` below this page, it defines the direction as the direction of the _flow_, not the packet: 

> *Identifies the traffic direction of the flow. Possible values are ingress, egress and unknown.*

https://docs.cilium.io/en/stable/observability/metrics/#context-options

**Comment by anubhabMajumdar** [comment]
> > On node aks-nodepool1-27817402-vmss000000, we observe these metric (this node hosts agnhost-a):
> > ```
> > hubble_flows_processed_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",protocol="TCP",source="kube-system/agnhost-b",source_pod="agnhost-b",subtype="to-endpoint",traffic_direction="egress",type="Trace",verdict="FORWARDED"} 3
> > 
> > hubble_tcp_flags_total{destination="kube-system/agnhost-a",destination_pod="agnhost-a",family="IPv4",flag="SYN-ACK",source="kube-system/agnhost-b",source_pod="agnhos -b",traffic_direction="egress"} 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Question - if source_pod=agnhost-b and destination_pod=agnhost-a, how can traffic_direction be egress on this node?
> > Same for node aks-nodepool1-27817402-vmss000001.
> > I think the traffic_direction label is inverse of what it's supposed to be.
> 
> I suspect that this is a question of "flow direction" vs. "packet direction". The field is called `traffic_direction`, which is a bit ambiguous. If we look at the packet in the second metric, we see that it is a SYN-ACK. This implies that the packet is a reply for an egress connection.
> 
> If you search for `traffic_direction` below this page, it defines the direction as the direction of the _flow_, not the packet:
> 
> > _Identifies the traffic direction of the flow. Possible values are ingress, egress and unknown._
> 
> https://docs.cilium.io/en/stable/observability/metrics/#context-options
> 
> From this, it seems like the metric is working as intended (if a bit confusing).

Thanks for the explanation. So, if I want to infer `packet_direction` (as in whether the packet is entering or leaving the node), should I use the `subtype` label for it? For ex: `to-endpoint` will always mean an ingress packet while `from-endpoint` will mean egress packet?

Also, would it be valuable to add `packet_direction` as a label in future?
