### ISSUE TITLE
Health unix socket takes a long time to create on large clustermesh

### ISSUE THREAD

**Issue by CallMeFoxie** [cilium/cilium#28017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sometimes - not always - when running a larger clustermesh (16 clusters in the test as of right now) the `health.sock` takes a long time to be brought up.
```
level=info msg="Launching Cilium health daemon" subsys=daemon
level=info msg="Launching Cilium health endpoint" subsys=daemon
```

HOWEVER it takes several hours - even days - to get this message:
```
level=info msg="Serving cilium health API at unix:///var/run/cilium/health.sock" subsys=health-server
```

which means that `cilium status` will output until then:
```
$ kubectl exec -ti -n cilium cilium-jhbst -- bash
croot@infra8-ng-2-2:/home/cilium# cilium status
KVStore:                 Ok   etcd: 3/3 connected, leases=1, lock lease-ID=54158a413243dc0f, has-quorum=true: <redacted 3 nodes> 3.2.26 (Leader)
Kubernetes:              Ok   1.27 (v1.27.1) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [enp3s0 <redacted> (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.0 (v1.14.0-a054768c85)
NodeMonitor:             Disabled
IPAM:                    IPv4: 11/62 allocated from <redacted>/26, 
ClusterMesh:             16/16 clusters ready, 0 global-services
...
Cluster health:                        Warning   cilium-health daemon unreachable
```

and `cluster-health status` will not work because it reads from the unix socket.

Indeed the unix socket node doesn't exist to begin with. However the port `4240` is fine.

This does not happen when there's no clustermesh.

```
xxx:/home/cilium# ls -la /var/run/cilium/
-rw-r-----  1 root root    2 Sep  7 12:36 cilium.pid
srw-rw----  1 root root    0 Sep  7 12:36 cilium.sock
srw-rw----  1 root root    0 Sep  7 13:51 health.sock
...
```

No errors reported anywhere (only some nodes from the clustermesh are not available). I wonder if it has to do with some nodes not being available (still working out the security groups)?

```
xxx:/home/cilium# cilium-health status | grep -i "to agent" | grep deadline | wc -l
157
xxx:/home/cilium# cilium-health status | grep -i "to agent" | grep -v deadline | wc -l
33
```

I tried searching in the source code but there's not many debug logging around the unix socket setup.

### Cilium Version

1.14.0

### Kernel Version

5.15.0-83-generic

### Kubernetes Version

1.27.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CallMeFoxie** [comment]
What's interesting from user's POV is this:

zajimavy
```
level=debug msg="Probe successful" ipAddr=aaa nodeName=XXX rtt=14.455898ms subsys=health-server
level=debug msg="Probe successful" ipAddr=bbb nodeName=YYY rtt=14.483362ms subsys=health-server
...
```
ale
```
nnn:/home/cilium# cilium-health status | grep ... -A 3 
  XXX:
    Host connectivity to 10.130.16.61:
      ICMP to stack:   OK, RTT=7.107339ms
      HTTP to agent:   Get "http://aaa:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
--
  YYY:
    Host connectivity to 10.130.16.110:
      ICMP to stack:   OK, RTT=10.621282ms
      HTTP to agent:   Get "http://bbb:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

It doesn't seem to be reported correctly in the cilium-health status?

**Comment by CallMeFoxie** [comment]
What's also interesting is this
```
ashley@foxtop:~/repos/cilium-szn$ kubectl logs --since=5m  --context infra8.ng -n cilium cilium-dtjxn 2>&1 | grep health-server | grep "Probe successful" | wc -l
950
ashley@foxtop:~/repos/cilium-szn$ kubectl logs --since=5m  --context infra8.ng -n cilium cilium-dtjxn 2>&1 | grep health-server | grep "Greeting failed" | wc -l
10
```

given that the "not working" are in majority as per the initial post (157 vs 33)

it's as if the timeout isn't working somewhere, which is not helping if the unix socket creation is waiting for initial pass or something.

**Comment by CallMeFoxie** [comment]
OK I fixed one of the remote server's ACLs so the port 4240 can be reached. It took roughly 75 minutes (so around the same time as to how long it took to create the unix socket from starting cilium) to update its status. Coincidence?

Also 75 minutes is 4500 seconds, divided by 30 seconds timeout gives me roughly 150 nodes to fail. Which is - again - very similar to the 141 currently "deadlined" nodes....

**Comment by CallMeFoxie** [comment]
The plot thickens :) Another node:
```
srw-rw----  1 root root    0 Sep  8 09:32 health.sock
srw-rw----  1 root root    0 Sep  8 08:13 hubble.sock
```
and now it is 10:12, yet all I see are "ICMP to stack" and no "HTTP to stack" just yet.

**Comment by CallMeFoxie** [comment]
Fixed all the endpoints and now it takes only 2 minutes -ish
```
srw-rw----  1 root root    0 Sep  8 10:45 health.sock
srw-rw----  1 root root    0 Sep  8 10:43 hubble.sock
```

**Comment by giorio94** [comment]
Hey @CallMeFoxie, thanks for the detailed report.

The reason for the delay in the creation of the socket is that we do a first synchronous probing of the status of all nodes \[1\] to retrieve the initial status before starting the health-server \[2\]. While the ICMP check is done in parallel for all nodes, \[3\] and configured with an overall timeout of 1 second \[4\] during the initial run, the HTTP check is done sequentially \[5\], with a timeout of 30s per request \[6\]. This exactly matches the numbers you were reporting.

In terms of possible solutions, I'd suggest dropping the initial synchronous probing, and just initialize all nodes to an unknown status. That way, the health-server initialization is no longer blocked for a long period of time if a subset of nodes is unreachable. Additionally, I guess it should be reasonable to lower the HTTP check timeout, as well as possibly increase the associated parallelism.

\[1\]: https://github.com/cilium/cilium/blob/9ab742b6ed2c483d75b49292d250258a771b3b31/pkg/health/server/server.go#L332-L333
\[2\]: https://github.com/cilium/cilium/blob/9ab742b6ed2c483d75b49292d250258a771b3b31/pkg/health/server/server.go#L353
\[3\]: https://github.com/cilium/cilium/blob/9ab742b6ed2c483d75b49292d250258a771b3b31/vendor/github.com/servak/go-fastping/fastping.go#L401-L481
\[4\]: https://github.com/cilium/cilium/blob/9ab742b6ed2c483d75b49292d250258a771b3b31/cilium-health/launch/launcher.go#L38
\[5\]: https://github.com/cilium/cilium/blob/9ab742b6ed2c483d75b49292d250258a771b3b31/pkg/health/server/prober.go#L291-L334
\[6\]: https://github.com/cilium/cilium/blob/9ab742b6ed2c483d75b49292d250258a771b3b31/pkg/health/probe/probe.go#L17

**Comment by CallMeFoxie** [comment]
stale or not, it is still happening :)
