### ISSUE TITLE
`make kind-install-cilium` fails with `cilium: command not found`

### ISSUE THREAD

**Issue by fujitatomoya** [cilium/cilium#28043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. start devcontainer with vscode.
2. issue `make kind-install-cilium`.
3. cilium install failed since `cilium-cli` command is not found.

```bash
root@f2c1bfa316b2:/go/src/github.com/cilium/cilium# make kind-install-cilium
  INSTALL cilium
# cilium-cli doesn't support idempotent installs, so we uninstall and
# reinstall here. https://github.com/cilium/cilium-cli/issues/205
cilium uninstall >/dev/null
bash: line 1: cilium: command not found
make: [Makefile:626: kind-install-cilium] Error 127 (ignored)
# cilium-cli's --wait flag doesn't work, so we just force it to run
# in the background instead and wait for the resources to be available.
# https://github.com/cilium/cilium-cli/issues/1070
cilium install \
        --chart-directory=/go/src/github.com/cilium/cilium/install/kubernetes/cilium \
        --helm-values=/go/src/github.com/cilium/cilium/contrib/testing/kind-common.yaml \
        --helm-values=/go/src/github.com/cilium/cilium/contrib/testing/kind-values.yaml \
        --version= \
        >/dev/null 2>&1 &
```

### Cilium Version

https://github.com/cilium/cilium/commit/5b0cf2cc3d6abcdf7b1a662691c9620237b31b51

### Kernel Version

Linux tomoyafujita 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

root@f2c1bfa316b2:/go/src/github.com/cilium/cilium# kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

### Anything else?

quay.io/cilium/cilium-builder:xxx container image should include `cilium-cli`?

work around is straight forward, we can just install the `cilium-cli` in the cilium-builder container with https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/

```bash
CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
CLI_ARCH=amd64
if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
It's also not part of the `make dev-doctor` output. So we should make it part of development requirements that `cilium-cli`, `kind` and `kubectl` are one of the requirements as well if people are planning to use `kind`.

**Comment by fujitatomoya** [comment]
I will go ahead to close this one in favor of https://github.com/cilium/cilium/pull/28269

CC: @aanm
