### ISSUE TITLE
The agent stops accessing the kube-apiserver until agent restarts

### ISSUE THREAD

**Issue by maximsnezhkov** [cilium/cilium#28089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello. At a random moment, a problem appeared in the cluster with the launch of new pods. Each new pod was stuck with a FailedCreatePodSandBox creation error.
`
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox ae9ae5c6be538784e6cfd2838e999020d22b6dbae6b8e963363bce402c67ff51: Unable to create endpoint: Cilium API client timeout exceeded
`
Restarting the cilium-agent resulted in a successful pod launch. As a result, the problem moved to new cluster nodes until I restarted all cilium-agent pods.

### Cilium Version

1.12.10

### Kernel Version

5.3.0
5.4.0

### Kubernetes Version

1.22.17

### Sysdump

[cilium-sysdump-20230824-130040.zip](https://github.com/cilium/cilium/files/12583501/cilium-sysdump-20230824-130040.zip)

### Relevant log output

```shell
There were no messages related to the problem in the cilium-agent log.
```

### Anything else?

I have not been able to figure out the reason. It looks like at some point the connectivity between cilium-agent and kube-apiserver was disrupted, after which the agent stopped performing successful connection attempts. 
The appearance of new problematic agents was tracked by the metric
`sum(cilium_endpoint_state{service="cilium-agent-metrics",env="prod", instance=~"$pod", endpoint_state="waiting-for-identity"}) by (instance)`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by haribhusal1** [comment]
I can confirm, this is happening in our clusters as well. This is causing unexpected outages. Any fix ?

**Comment by christarazi** [comment]
It sounds like the issue is a deadlock given the error msg. We've made improvements in the latest version of Cilium. At the very least, the latest v1.13 contains the deadlock improvements (https://github.com/cilium/cilium/pull/26242).
