### ISSUE TITLE
CFP:  Dynamically generate CRD validation logic

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#28080]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

If a user configures Cilium with `--enable-l7-proxy=false`, it may impact the ability for Cilium to enforce CiliumNetworkPolicies. If a user configures this flag and adds either L7 policies or even `ToFQDNs` policies (which are L3, but rely on L7 information) in this configuration, the policy will be ineffective. This may be surprising if the user does not realize that L7 functionality is disabled at the time of creating policies (for instance, because the cluster administrator is a different person than the person managing policies for a specific Kubernetes namespace).

**Describe the feature you'd like**

Detect and report this configuration to the user in a manner that is easy to identify and resolve.

**(Optional) Describe your proposed solution**

Extend the cilium-operator to detect the `--enable-l7-proxy=false` flag and dynamically reconfigure the CRD validation logic to reject policies that include L7 or ToFQDNs statements.

This would potentially interact with https://github.com/cilium/cilium/issues/27770, because the CRD validation may change depending on agent flags, even if the Cilium version does not change.

*For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.*

*Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.*

**Comment by christarazi** [comment]
The immediate challenge here is that CRD validation logic is done via `kubebuilder` annotations as Go code comments on the API type structs. The alternative could be [dynamic admission webhooks](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/), but those have their own can of worms.

**Comment by danehans** [comment]
This issue is very similar to https://github.com/cilium/cilium/issues/23152. @joestringer should this be closed as a dupe?

**Comment by joestringer** [comment]
We can continue the discussion on the other issue.
