### ISSUE TITLE
Add option to define path of cilium-envoy.log and add log rotation to the log file

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2810]
It's currently being placed under `{state-dir}/cilium-envoy.log`. We should be able to change this

**Comment by jrajahalme** [comment]
Right, with debug logging the volume hosting the state dir can fill up fast.

**Comment by manalibhutiyani** [comment]
log rotation has already been merged as part of Issue #3034

**Comment by manalibhutiyani** [comment]
This can be closed when @jrajahalme merges #2990
