### ISSUE TITLE
NodePort is not accessible on dsr mode

### ISSUE THREAD

**Issue by QQGoblin** [cilium/cilium#28149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My Kubernetes cluster has two nodes and I replaced kube-proxy with the functionality of cilium.

cilium works in DSR mode，cilium works in DSR mode, version 1.14.1。

kubernetes cluster deploys the following services. 
![image](https://github.com/cilium/cilium/assets/80881214/a083def5-a7e8-492c-a9ff-c25ebc25bc79)

I found that on `172.28.117.42` executing `curl http://172.28.117.98:37778` will fail, while executing `curl http://172.28.117.42:37777` on `172.28.117.98` will fail.

these curl commands should work correctly. This problem was discovered after upgrading from version 1.12.x to 1.14.1. I think it is a bug caused by the introduction of new features.

### Cilium Version

Client: 1.14.1 c191ef6f 2023-08-10T18:54:57+02:00 go version go1.20.7 linux/amd64
Daemon: 1.14.1 c191ef6f 2023-08-10T18:54:57+02:00 go version go1.20.7 linux/amd64

### Kernel Version

Linux 5b4c2dd3-ca11-5f1c-ba44-0034bc5ffca5 5.10.16-1.el7.bclinux.x86_64 #1 SMP Sun Feb 14 06:58:31 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"8206683d1b72be8592759ce3d595efa3c7a568ec", GitTreeState:"clean", BuildDate:"2023-05-24T06:04:26Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"8206683d1b72be8592759ce3d595efa3c7a568ec", GitTreeState:"clean", BuildDate:"2023-05-24T06:03:22Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20230914-195830.zip](https://github.com/cilium/cilium/files/12604549/cilium-sysdump-20230914-195830.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by QQGoblin** [comment]
[cilium-sysdump-20230914-195830.zip](https://github.com/cilium/cilium/files/12604546/cilium-sysdump-20230914-195830.zip)

**Comment by julianwiedmann** [comment]
> My Kubernetes cluster has two nodes and I replaced kube-proxy with the functionality of cilium.
> 
> cilium works in DSR mode，cilium works in DSR mode, version 1.14.1。

:wave: thank you for reporting this! Could you clarify the text above - I take it that on 1.14.1, DSR mode **doesn't** work for you? Have you started to debug what's causing the disruption? Using `hubble` or `cilium monitor` to check for unexpected packet drops or flows might be a good start here.

You probably also want to re-test when `v1.14.2` is released (bringing https://github.com/cilium/cilium/pull/27381).

**Comment by QQGoblin** [comment]
> > My Kubernetes cluster has two nodes and I replaced kube-proxy with the functionality of cilium.
> > 
> > cilium works in DSR mode，cilium works in DSR mode, version 1.14.1。
> 
> :wave: thank you for reporting this! Could you clarify the text above - I take it that on 1.14.1, DSR mode **doesn't** work for you? Have you started to debug what's causing the disruption? Using `hubble` or `cilium monitor` to check for unexpected packet drops or flows might be a good start here.
> 
> You probably also want to re-test when `v1.14.2` is released (bringing https://github.com/cilium/cilium/pull/27381).

My cluster has two nodes, A and B. I ran a pod in the cluster and created a nodeport type svc for it.
I found the following issues:
If the pod is on node A, I cannot access the container on node A using the 'NodeB_IP: Nodeport '

**Comment by QQGoblin** [comment]
What I observed through cilium monitor is as follows:
![image](https://github.com/cilium/cilium/assets/80881214/a6814041-4a4c-4a06-b1e6-f44ff2a3375b)

**Comment by QQGoblin** [comment]
I tested version 1.14.2 and the problem persists.
I tested multiple versions and found that versions after 1.13.2 have the same problem, and
1.12.x, 1.13.0~1.13.2 are all normal.

**Comment by QQGoblin** [comment]
> Ah that's curious. It looks like the backend selection only happens on the remote node. Even though you have the SocketLB enabled - so it should happen on the client node at `connect()` time.
> 
> Can you grab some [SocketLB logs](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#observability) while trying the test?

I'm not quite sure how to collect socket log.
I executed `hubble observe --pod sp-network-check-9c112653-00a3-5886-88a4-e1d5634e8ec7` on node A and got the following output:

![image](https://github.com/cilium/cilium/assets/80881214/523ab882-82e3-44c2-9160-7dc31bfa76ac)

I also tried executing `cilium monitor -v -t trace-sock` synchronously while testing, but from the output, there didn’t seem to be anything of value.
```
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25252, dst [127.0.0.1]:53176 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21360, dst [127.0.0.1]:8080 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21361, dst [172.28.117.42]:6443 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25253, dst [172.28.117.42]:44474 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25254, dst [172.28.117.42]:49416 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21362, dst [127.0.0.1]:45708 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21363, dst [127.0.0.1]:2379 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25255, dst [127.0.0.1]:2379 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17925, dst [127.0.0.1]:45716 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17926, dst [127.0.0.1]:53182 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21364, dst [127.0.0.1]:8080 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17927, dst [172.28.117.116]:48850 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21365, dst [172.28.117.42]:49430 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17928, dst [127.0.0.1]:53186 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21366, dst [127.0.0.1]:8080 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17929, dst [172.28.117.98]:39320 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 28871, dst [127.0.0.1]:47426 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 28872, dst [127.0.0.1]:8080 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 28873, dst [127.0.0.1]:9879 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17930, dst [127.0.0.1]:39404 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17931, dst [127.0.0.1]:39416 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21367, dst [127.0.0.1]:9879 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17932, dst [172.28.117.116]:2380 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21368, dst [127.0.0.1]:8080 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 28874, dst [127.0.0.1]:47432 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 28875, dst [127.0.0.1]:47440 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21369, dst [127.0.0.1]:8080 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21370, dst [172.28.117.116]:45236 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17933, dst [172.28.117.42]:42680 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21371, dst [172.28.117.42]:39182 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25256, dst [172.28.117.42]:6443 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25257, dst [127.0.0.1]:2379 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21372, dst [127.0.0.1]:34376 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17934, dst [127.0.0.1]:34380 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 28876, dst [127.0.0.1]:2379 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17935, dst [127.0.0.1]:8080 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 28877, dst [127.0.0.1]:47444 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21373, dst [172.31.254.36]:43718 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21374, dst [172.31.254.36]:43716 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 28878, dst [172.31.254.38]:10250 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25258, dst [172.31.254.38]:10250 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21375, dst [172.28.117.42]:39190 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25259, dst [127.0.0.1]:47452 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 28879, dst [127.0.0.1]:8080 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17936, dst [172.31.254.39]:8181 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25260, dst [172.31.254.60]:8080 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21376, dst [172.31.254.36]:44614 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21377, dst [172.31.254.36]:57902 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 25261, dst [172.31.254.39]:8080 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17937, dst [172.31.254.60]:8080 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17938, dst [172.31.254.36]:55396 tcp
CPU 02: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17939, dst [172.31.254.36]:55398 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21378, dst [172.28.117.116]:2380 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17940, dst [172.28.117.98]:56812 tcp
CPU 03: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17941, dst [127.0.0.1]:47460 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21379, dst [127.0.0.1]:8080 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21380, dst [127.0.0.1]:8080 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 17942, dst [127.0.0.1]:47472 tcp
CPU 01: [pre-xlate-rev] cgroup_id: 1 sock_cookie: 21381, dst [172.28.117.116]:45246 tcp
```
