### ISSUE TITLE
datapath: Interrupted flows during upgrade when using Geneve for pod-to-pod

### ISSUE THREAD

**Issue by brb** [cilium/cilium#28143]
Reliably caught in https://github.com/cilium/cilium/actions/runs/6168348871/job/16751021820 (https://github.com/cilium/cilium/pull/27322). TL;DR the upgrade v1.14 -> main breaks existing connections with the following configuration:
```
          - name: '8'
            # renovate: datasource=docker depName=quay.io/lvh-images/kind 
            kernel: 'bpf-next-20230810.091425'
            kube-proxy: 'iptables'
            kpr: 'false'
            tunnel: 'geneve'
            endpoint-routes: 'true'
```

Observed the same failure (with Geneve) when adding the IPsec upgrade tests.

**Comment by julianwiedmann** [comment]
Assigning to myself, I'd quickly want to check if this is still an issue on latest main.

**Comment by julianwiedmann** [comment]
@brb ok, I'm slightly confused. We *are* [running](https://github.com/cilium/cilium/blob/3c3ce625f8ee6b0896b16d90e6a5b38f0e2cf7e5/.github/workflows/tests-e2e-upgrade.yaml#L174) this exact config in CI now ... so did we intentionally fix this problem at some point? Or was it something that just resolved itself?

**Comment by brb** [comment]
Good news. I think the latter (got resolved unintentionally). We can close it.
