### ISSUE TITLE
Cilium v1.14.x - Deployment Failure of Helm Chart on fresh Cluster

### ISSUE THREAD

**Issue by seb-lafond** [cilium/cilium#28167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

Everyday we rebuild/redeploy one of our Kubernetes/Cilium clusters to check for any regressions.   We use kubeadm for Kubernetes stack and Helm chart for Cilium.  All of this is managed through Ansible.  

As we use the cronjob method to generate clustermeshapi certificates, _clustermesh-apiserver-generate-certs_ job is deployed. With the v1.13.x chart, the job is deployed and **not completed** but chart is **deployed.** This is because the pod don't have tolerations to run on the master node.  

Since v1.14.x, the _clustermesh-apiserver-generate-certs_ job is deployed and not completed as usual but the Helm deployment fails. We observed that Helm hooks _post-install,post-upgrade_ have been added to the job. [https://github.com/cilium/cilium/pull/23102](https://github.com/cilium/cilium/pull/23102)
Now, the job need to be completed for chart deployment to succeed.

### RECAP
**v1.13.x using Ansible:**
- kubeadm init on first master
- Helm install of Cilium chart
- _clustermesh-apiserver-generate-certs_ job is deployed but not completed.  Job pod can't run on master node, but the result is a success as there are no Helm hooks post-install/post-upgrade
- kubeadm join on secondary masters and so on for worker nodes

**v1.14.x using Ansible:**
- kubeadm init on first master
- Helm install of Cilium chart
- _clustermesh-apiserver-generate-certs_ job is deployed but not completed.  Job pod can't run on master node. Result is a failure cause Helm hooks post-install/post-upgrade are present.  The job needs to be completed to have chart deployed successfully
-  Ansible task **failed** ...

**Workarounds:**
Remove taints on master node, deploy chart, re-add taints on master node
or
Remove "helm.sh/hook": post-install,post-upgrade" annotation on job
or
Add tolerations on job template _install/kubernetes/cilium/templates/clustermesh-apiserver/tls-cronjob/_job-spec.tpl_ and in Helm values

No issue when upgrading from v1.13.x to v1.14.x as the job runs normally on one of the worker nodes

### Cilium Version

cilium-cli: v0.15.7 compiled with go1.21.0 on linux/amd64
cilium image (default): v1.14.1
cilium image (stable): v1.14.1
cilium image (running): 1.14.1

### Kernel Version

Linux ad11srvkumaa101 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Thank you for reporting this and the great description! Let's loop in @cilium/sig-clustermesh ...

**Comment by giorio94** [comment]
Thanks for the report @seb-lafond! One initial note is that this possibly applies also to the hubble certificates generation, so looping in @cilium/sig-hubble as well. One difference, though, is that in the clustermesh case it is currently not possible to configure the job tolerations. I've raised https://github.com/cilium/cilium/pull/28221 to fix this divergence.

@seb-lafond Would being able to configure the tolerations enough for you? I guess that would be the only proper solution (which does not involve changing your infrastructure setup) to make sure that the job can correctly complete when no worker node has yet joined the cluster.

**Comment by seb-lafond** [comment]
Hi @giorio94,

Thank you for your reply.

Tolerations on the job will do the trick [#28221 ](https://github.com/cilium/cilium/pull/28221). 

Additionaly, adding the possibility to use **affinity** section to the job template would allow prioritizing job deployment on worker nodes if they are available.

**Comment by giorio94** [comment]
> Tolerations on the job will do the trick https://github.com/cilium/cilium/pull/28221.

Great! https://github.com/cilium/cilium/pull/28221 has been merged and marked for backport to v1.14.

> Additionaly, adding the possibility to use affinity section to the job template would allow prioritizing job deployment on worker nodes if they are available.

Makes definitely sense to me. Feel free to propose a PR which introduces that configuration, as well as to ask on the slack #development channel if you need any help about that.

**Comment by aanm** [comment]
The main bug got fixed by https://github.com/cilium/cilium/pull/28221, the nice-to-have that was discussed can be addressed as a follow up.

**Comment by nickolaev** [comment]
@aanm can we close this one now?
