### ISSUE TITLE
Decrease L2 announcement RBAC log spamming

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#28165]
The L2 announcement module has a feature: if disabled, it will start a one-shot function that will list all leases and remove any l2 announcement relegated leases which are now no longer in use. Normally this works as expected because, when the feature was active the cilium agent got granted access to list the leases. However if someone never enabled the feature in the first place, the API server will reject the list leases request. So any time an agent restarts the API server will log a request denied which can be spam-y in clusters with a lot of node churn. It doesn't actually effect cilium since we explicitly catch this scenario and don't log it.

It would be nice if we could make the module query the API server what its grants are and only make the request if its confident it will be allowed. This should reduce/eliminate the blocked logs.

**Comment by aanm** [comment]
Perhaps we could do the one-off GC from the Cilium operator?

**Comment by dylandreimerink** [comment]
That is a good idea. That will reduce the work in any case, and the operator has grants for leases anyway

**Comment by dylandreimerink** [comment]
bump
