### ISSUE TITLE
Audit APIs for Selector Field Semantics

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#28177]
API types that contain label selector fields, i.e. [EndpointSelector](https://github.com/cilium/cilium/blob/v1.14.2/pkg/policy/api/rule.go#L48-L60), [ServiceSelector](https://github.com/cilium/cilium/blob/v1.14.2/pkg/k8s/apis/cilium.io/v2alpha1/bgpp_types.go#L182-L188), etc., have inconsistent behavior. Specifically, label selector fields should document semantics when the field is `nil` or `empty`. According to https://github.com/kubernetes/kubernetes/issues/25836, `nil` and `empty` should be treated the same.

Write (or solicit API owners to write/update) API docs as needed. Flag anything that tries to differentiate `nil` from `empty`. For legacy selectors (`map[string]string`), `nil` and `empty` should always mean the same thing, and consider any that try to violate this. For modern selectors (`metav1.LabelSelector`), it may be OK to distinguish `nil` from `empty` but **ONLY IF** the field is a pointer.

Write an API convention for documenting this. Ideally, a blob of text that can be used on all fields.

Bonus: write an API linter that checks that any metav1.LabelSelector field has this text in the comments.

**Comment by danehans** [comment]
xref https://github.com/cilium/cilium/pull/27100#discussion_r1321910619 for the discussion that prompted this issue.

**Comment by danehans** [comment]
I put together some ideas in [this doc](https://docs.google.com/document/d/1DoNEnCFKc1RBQORUYHnNeiZPT2jnMX-jVwN-9lJmK2w/edit?usp=sharing) for refactoring the [EndpointSelector](https://pkg.go.dev/github.com/cilium/cilium/pkg/policy/api#EndpointSelector) since the semantics differ for `nil` and `empty`.

**Comment by aanm** [comment]
cc @christarazi

**Comment by danehans** [comment]
@aojea would appreciate your input on this issue from a k8s sig-network perspective. From my understanding, CNP/CCNP selector fields are consistent with k8s NetworkPolicy semantics.

**Comment by aojea** [comment]
> According to https://github.com/kubernetes/kubernetes/issues/25836, nil and empty should be treated the same.

I don't think it means that, it means that if the label selector is not a pointer, emptu and nil must be the same, this is beca is how json serialization and golang defaults works, if you define a type like a map or a slice as a value then, after serializing it, there is no possible way to differentiate if the user has set an empty value or just didn't set it see an example

https://go.dev/play/p/42ODrripMXS
```go
import (
	"encoding/json"
	"fmt"
	"os"
)

func main() {
	type endpoint struct {
		Name     string            `json:"name,omitempty"`
		Selector map[string]string `json:"selector,omitempty"`
	}
	type endpointPointer struct {
		Name     string             `json:"name,omitempty"`
		Selector *map[string]string `json:"selector,omitempty"`
	}

	emptyMap := map[string]string{}
	ep1 := endpoint{
		Name: "test-nopointer",
	}
	ep2 := endpoint{
		Name:     "test-nopointer-emptymap",
		Selector: emptyMap,
	}
	ep3 := endpointPointer{
		Name:     "test-pointer-nil",
		Selector: nil,
	}
	ep4 := endpointPointer{
		Name:     "test-pointer-emptymap",
		Selector: &emptyMap,
	}
	fmt.Println("field is a map")

	b, err := json.Marshal(ep1)
	if err != nil {
		fmt.Println("error:", err)
	}
	os.Stdout.Write(b)
	fmt.Println()
	b, err = json.Marshal(ep2)
	if err != nil {
		fmt.Println("error:", err)
	}
	os.Stdout.Write(b)
	fmt.Println()
	fmt.Println("field is a pointer")
	b, err = json.Marshal(ep3)
	if err != nil {
		fmt.Println("error:", err)
	}
	os.Stdout.Write(b)
	fmt.Println()
	b, err = json.Marshal(ep4)
	if err != nil {
		fmt.Println("error:", err)
	}
	os.Stdout.Write(b)
}

...


```json
field is a map
{"name":"test-nopointer"}
{"name":"test-nopointer-emptymap"}
field is a pointer
{"name":"test-pointer-nil"}
{"name":"test-pointer-emptymap","selector":{}}
```

If you use a value you can not make assumptions between not set or set to empty, because the output is the same, however, if you use a pointer you can make those assumptions, the important here is that you clearly document this so consumers are aware of this behavior.
