### ISSUE TITLE
CFP: cilium helm install support airgap environment.

### ISSUE THREAD

**Issue by xiaods** [cilium/cilium#28178]
## Cilium Feature Proposal
   
**Is your proposed feature related to a problem?**
cilium install and helmMapOpts["image.useDigest"] = "false" . we can't install cilium with image tar files on airgap environments.

**Describe the feature you'd like**
need options to install cilium image without digest in airgap environments.

**Comment by lmb** [comment]
Can you explain how we can reproduce the environment you're trying to install cilium in? "airgap environments" could mean many things.

**Comment by xiaods** [comment]
> Can you explain how we can reproduce the environment you're trying to install cilium in? "airgap environments" could mean many things.

I discovered that when using `cilium-cli install`, the installation calls on Cilium Helm parameters to configure the Cilium cluster installation. For example, in the following scenario, I use my developed k8e engine to install the Cilium cluster.

```
curl -sfL https://getk8e.com/install.sh | K8E_TOKEN=ilovek8e INSTALL_K8E_EXEC="server --cluster-init --write-kubeconfig-mode 644" sh -
```

After the Cilium installation is completed, it is found that the Cilium image has been using digests signatures for the image. Moreover, I found that it is not possible to specify the use of tags to download the Cilium image. Because in offline environments, I usually use `docker save` to store the Cilium tar package, and in offline networks, use `docker load < cilium.tar` to load. Here is a problem: The Docker digested images will change their digests after being packaged and distributed to the offline host, which cannot ensure that they are consistent with the official repository. This is why I want to raise a request, whether it is possible to add a parameter in Helm to specify the Cilium tag.

**Comment by aanm** [comment]
You can already specify the image tags for all images, for example `image.tag` or `operator.image.tag`. Is there anything that is missing?

**Comment by xiaods** [comment]
> You can already specify the image tags for all images, for example `image.tag` or `operator.image.tag`. Is there anything that is missing?

thanks for your hints. let me check it

**Comment by aanm** [comment]
I see, in that case please add the `--set image.useDigest=false` as part of that command.

**Comment by xiaods** [comment]
https://github.com/cilium/cilium-cli/issues/1106

**Comment by xiaods** [comment]
> --set image.useDigest=false

Thanks this hints. it's works on cilium images.

**Comment by bbaassssiiee** [comment]
You'll need to do it for all images:

```sh
--set image.useDigest=false \
--set hubble.relay.image.useDigest=false \
--set hubble.ui.backend.image.useDigest=false \
--set hubble.ui.frontend.image.useDigest=false \
--set operator.image.useDigest=false \
--set certgen.image.useDigest=false \
--set envoy.image.useDigest=false
```
