### ISSUE TITLE
New cilium encrypt subcommands for managing keys

### ISSUE THREAD

**Issue by margamanterola** [cilium/cilium#28174]
In our IPSec documentation, we tell users that they should rotate their keys, and provide a [handy but ugly](https://docs.cilium.io/en/stable/security/network/encryption-ipsec/#ipsec-key-rotation) shell script to do that.

It would be better if we had a command like: `cilium encrypt rotate-keys` that took care of this for the user.

Additionally, although perhaps less important, it would also be good to have `cilium encrypt key-status` that would print the data of the keys in use rather than having to use commands like `kubectl get secret -n kube-system cilium-ipsec-keys -o go-template --template={{.data.keys}} | base64 -d`.

**Comment by chaunceyjiang** [comment]
Hi, Can i pick up this issue?

/assign @chaunceyjiang

**Comment by chaunceyjiang** [comment]
> This should actually have been in the cilium repo, as cilium encrypt is part of the in-agent cilium cli, rather than the external cilium cli. Sorry about the confusion.

Hi @aanm @margamanterola, I have a question. Why can't we add this command in external cilium cli? Instead, why do we need to add it in the in-agent cilium cli?

From the official documentation, it seems like this sub command is meant to be used external cilium cli .

https://docs.cilium.io/en/stable/security/network/encryption-ipsec/#key-rotation.

``` shell
KEYID=$(kubectl get secret -n kube-system cilium-ipsec-keys -o yaml | awk '/^\s*keys:/ {print $2}' | base64 -d | awk '{print $1}')
if [[ $KEYID -ge 15 ]]; then KEYID=0; fi
data=$(echo "{\"stringData\":{\"keys\":\"$((($KEYID+1))) "rfc4106\(gcm\(aes\)\)" $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null| xxd -p -c 64)) 128\"}}")
kubectl patch secret -n kube-system cilium-ipsec-keys -p="${data}" -v=1
```

**Comment by joestringer** [comment]
cc @cilium/sig-encryption

**Comment by pchaigno** [comment]
@chaunceyjiang A Cilium CLI command would be more appropriate in my opinion as well.

**Comment by jschwinger233** [comment]
@chaunceyjiang Because external cli relies on external binaries which may behave unexpectedly on different platforms. For example, macOS awk vs GNU/awk.

**Comment by margamanterola** [comment]
Sorry, I had drafted an answer to this last week, but forgot to hit send. Yes, a command in the external CLI would be nicer (that's why I had originally filed this issue there), but currently only the internal one has the `encrypt` subcommand.

I guess we could add a new `encrypt` subcommand to the external CLI. We probably also want an `encrypt status` subcommand there, that covers the status of the overall encryption feature (although that's a separate work item).

And Grey does have a point that we would need to figure out how to do the key rotation in a way that works regardless of the OS.

**Comment by chaunceyjiang** [comment]
> I guess we could add a new encrypt subcommand to the external CLI. We probably also want an encrypt status subcommand there, that covers the status of the overall encryption feature (although that's a separate work item).


+1 

> Yes, that's on the list of retrospective items from recent IPsec bugs. I'll probably get to it in the coming weeks if nobody does before.

I think we should open a new issue for this task, and I can attempt to complete it.

**Comment by viktor-kurchenko** [comment]
I've raised PR to address the issue: https://github.com/cilium/cilium-cli/pull/2266
CC: @margamanterola

**Comment by margamanterola** [comment]
Thanks for getting this done, Viktor! :tada:
