### ISSUE TITLE
Support reporting status of Hive Job in `cilium status`

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#28206]
Today, controllers in Cilium report their status in `cilium status --all-controllers` and is a useful way to get an idea of Cilium's operational status. There's also recently been the notion of a Job from the Hive framework. It seems to be a superset of controllers (`pkg/controller`), but is still missing this visibility aspect.

Once that's added, it seems like we could move controllers to Hive Jobs by aliasing the controller-related methods to use Hive Job in the backend.

**Comment by christarazi** [comment]
cc @pippolo84

**Comment by joamaki** [comment]
Once https://github.com/cilium/cilium/pull/27522/ is in this becomes pretty straightforward. We can then unify the `--all-controllers` to show both controllers and jobs.

**Comment by joamaki** [comment]
The hive jobs are reported as part of health (`--all-health`). Shall we close this?
