### ISSUE TITLE
unable to find controller ipcache-inject-labels" subsys=daemon

### ISSUE THREAD

**Issue by chaunceyjiang** [cilium/cilium#28223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!

![image](https://github.com/cilium/cilium/assets/17962021/6d883609-4d5d-4c76-b430-7eb7c74ed42d)

### Cilium Version

v1.14.0

### Kernel Version

Linux localhost 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.27.0

### Anything else?

https://docs.cilium.io/en/stable/security/network/encryption-ipsec/#encryption-ipsec

I followed this document step by step, but I always get this error.

```
cilium upgrade --version 1.14.0     --set kubeProxyReplacement=true     --set ingressController.enabled=true     --set ingressController.loadbalancerMode=dedicated --helm-set ipv6.enabled=false --set encryption.enabled=true    --set encryption.type=ipsec  --set gatewayAPI.enabled=true
```

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
Could it be that you are looking at the wrong error? In your screenshot it says "IPSec cannot be used with BPF NodePort". 

Please just copy and paste the error in the future instead of providing a screenshot. It makes it harder to find similar issues.
