### ISSUE TITLE
CFP:  Enable node to node (both behind NAT) communication in Kubernetes cluster after set the persistent keepalive for cilium_wg0

### ISSUE THREAD

**Issue by FengGaoCSC** [cilium/cilium#28232]
## Cilium Feature Proposal
**Is your proposed feature related to a problem?**

Continued with https://github.com/cilium/cilium/issues/27771

**Describe the feature you'd like**

When node join to k8s cluster but the node is behind the NAT, after https://github.com/cilium/cilium/issues/27771 and https://github.com/cilium/cilium/pull/28013 , the node could communicate with control panel bi-direction. but node to node communication(both behind the NAT) is still a problem since the node only can get the peer's local IP address for configuration. 

What I want is if we can enable the hub-spoke topology node-to-node communication in k8s cluster.

**(Optional) Describe your proposed solution**

my suggestion is:
1. add an options for example --enable-wireguard-hub-spoke when install cilium into kubernetes
2. this options will be configured into the configure map
3. the control-panel node when see this configure are enabled, maybe it need to enable the ip_forwarding for IPv4 and IPv6 both. e.g ` sysctl -w net.ipv4.ip_forward=1`
4. when node join the cluster, the node only need to configure the control-panel node as the peer but  it didn't need to configure other node's joined this cluster as peers as following
```console
root@nodebehindNAT1:/home/nodebehindNAT1# wg
# Settings for this local node
[Interface]
PrivateKey =<privateKey>
Address = <local IP address>
ListenPort = <port>

# remote settings for control panel node
[Peer]
PublicKey = <publicKey>
Endpoint = <control panel node IP:port>
AllowedIPs = <CNI kubernet IPAM range e.g. 10.0.0.0/16>
PersistentKeepalive = 25

```

**Comment by FengGaoCSC** [comment]
@brb

**Comment by brb** [comment]
@FengGaoCSC Thanks for the CFP. Mind describing how would you implement such a topology in Cilium?

**Comment by FengGaoCSC** [comment]
> @FengGaoCSC Thanks for the CFP. Mind describing how would you implement such a topology in Cilium?

thanks @brb.

I add the describing that what I think when implement such a topology in cilium with wireguard.

@fujitatomoya

**Comment by fujitatomoya** [comment]
@FengGaoCSC i think we need to come up with more feasible design and ideas that actually explains what needs to be done. I am not even really sure how cilium manages wireguard configuration, besides this idea brings the boundary that specific configuration needs to be applied to devices only behind the NAT. Let's consider internally for more details.
