### ISSUE TITLE
Gateway API HttpRoute cannot strip path prefix - double slash problem

### ISSUE THREAD

**Issue by nxy7** [cilium/cilium#28270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've previously created issue #27994 regarding this subject, but it was closed after PR that doesn't really address the issue so I thought I'd open new one to track double slash problem.
While using Gateway API i found out that given `PathPrefix: /echo`, `replacePrefixMatch: /` and request to `{someAddrs}/echo/test` leaves you with `{someAddrs}//test`, so double slash. That makes stripping prefix impossible, which is pretty handy feature (seems pretty fundamental for gateway).
This issue might be out of Cilium hands and could envoy issue. If I'm not mistaken it's envoy that actually does url manipulation and if that's the case, then it doesn't make sure that output url is valid. Still if Cilium accepted empty prefixes I think you could avoid double '/' by making  `replacePrefixMatch: ""` in URLRewrite.
I don't know cilium internals, so let me know if it's something that cilium can fix or should I create issue on envoy side.

### Cilium Version

1.15.0-pre.0

### Kernel Version

Linux 6.5

### Kubernetes Version

1.27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nxy7** [comment]
It seems that envoy has [merge_slashes option](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html), but I'm not entirely sure how to pass config to envoy if I'm using it via cilium.

**Comment by sayboras** [comment]
👋 

Just curious if you are keen to submit the PR for the same. Assume that we are going with your proposal, the patch will be something like below. Note that we need to update the existing tests, and make sure the conformance test in CI are still passing.

```diff
diff --git a/operator/pkg/model/translation/envoy_http_connection_manager.go b/operator/pkg/model/translation/envoy_http_connection_manager.go
index 0026da564a..5fd9609a02 100644
--- a/operator/pkg/model/translation/envoy_http_connection_manager.go
+++ b/operator/pkg/model/translation/envoy_http_connection_manager.go
@@ -37,6 +37,7 @@ func NewHTTPConnectionManager(name, routeName string, mutationFunc ...HttpConnec
 		UpgradeConfigs: []*httpConnectionManagerv3.HttpConnectionManager_UpgradeConfig{
 			{UpgradeType: "websocket"},
 		},
+		MergeSlashes: true,
 	}
 
 	// Apply mutation functions for customizing the connection manager.
```

**Comment by nxy7** [comment]
Sure, I'm not sure how cilium testing is set up so that might take some time, but I think I can send PR this week.

**Comment by sayboras** [comment]
Thanks for your help, feel free to hit me up in Cilium OSS if you have any questions/concerns.
