### ISSUE TITLE
Introduce backoff on cloud IPAM failures

### ISSUE THREAD

**Issue by jaffcheng** [cilium/cilium#28273]
In cloud IPAM modes, the operator attempts to allocate ENIs and IPs until the node's IP deficit is fulfilled. However, external cloud API requests may fail due to various reasons such as performance degradation or changes from providers. Since cloud API quotas are typically limited, to avoid API rate limit issues, it would be safer to implement a backoff mechanism for node IP pool maintenance failures instead of retrying indefinitely.

**Comment by aanm** [comment]
@jaffcheng would you like to submit a PR?

**Comment by jaffcheng** [comment]
> @jaffcheng would you like to submit a PR?

Yes, but I’m afraid not in a couple weeks, so feel free to take this.
