### ISSUE TITLE
Wrong source address on return traffic while trying to access services with endpoints being node (physical) addresses

### ISSUE THREAD

**Issue by lgyurci** [cilium/cilium#28288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Environment:** 
I have an RKE2 cluster (v1.26.7+rke2r1) with the kube-apiserver running on the hosts. There are 3 nodes, all connected via layer 2: 10.186.50.106, 10.186.50.107 and 10.186.50.108. Therefore, I am using direct routing with direct server return (DSR), with the following cilium configuration:
```autoDirectNodeRoutes: true
bandwidthManager:
  bbr: true
  enabled: true
bgpControlPlane:
  enabled: true
bpf:
  hostLegacyRouting: false
  lbExternalClusterIP: true
  masquerade: true
etcd:
  nodeSelector:
    kubernetes: {}
hubble:
  enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDR: 10.185.128.0/18
ipv4NativeRoutingCIDR: 10.185.128.0/17
k8sServiceHost: censored.example.com
k8sServicePort: 6443
kubeProxyReplacement: strict
loadBalancer:
  algorithm: maglev
  mode: dsr
routingMode: native
tunnel: disabled
```
Cilium status:
```
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.26 (v1.26.7+rke2r1) [linux/amd64]
Kubernetes APIs:         ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [bond0.650 10.186.50.106 (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            portmap
CNI Config file:         CNI configuration file management disabled
Cilium:                  Ok   1.13.2 (v1.13.2-8cb94c70)
NodeMonitor:             Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 18/254 allocated from 10.185.130.0/24, 
IPv6 BIG TCP:            Disabled
BandwidthManager:        EDT with BPF [BBR] [bond0.650]
Host Routing:            BPF
Masquerading:            BPF   [bond0.650]   10.185.128.0/17 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       98/98 healthy
Proxy Status:            OK, ip 10.185.130.84, 0 redirects active on ports 10000-20000
Global Identity Range:   min 256, max 65535
Hubble:                  Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 67.22   Metrics: Disabled
Encryption:              Disabled
Cluster health:          3/3 reachable   (2023-09-26T13:57:55Z)
```
**Problem:**
ClusterIP services having the node IPs as enpoints will have wrong source IP addresses on the returned packets, IF the request was processed on a different node than the original receiver of said request - for example, the kube-apiserver. This kills internal communication with the kube-apiserver, making certain controllers (like ingress-nginx) reach the kubernetes API 1/3rd of the time, and time out every other time.

To better illustrate the problem, I tried to reach the internal kube-apiserver address from an external computer (service IPs are routed to the nodes). The address of this external computer in this example is 192.168.0.1, for simplicity. The internal address of the kube-apiserver (ClusterIP) is 10.185.192.1. The api endpoint is running on the host network, binding to tcp port 6443. Therefore, the ClusterIP service has the port 443 forwarded to port 6443 with the enpoints being the nodes themselves (10.186.50.108 (node1),10.186.50.107 (node2),10.186.50.106 (node3))

**Working case (1/3rd of the time):**
- 192.168.0.1 sends packet to 10.185.192.1
- Packet gets routed to 10.186.50.108 (node1)
- 10.186.50.108 (node1) processes the request
- Sends reply back to 192.168.0.1 with the source IP 10.185.192.1
- Everyone is happy

**Not working case (2/3rd of the time):**
 - 192.168.0.1 send packet to 10.185.192.1
 - Packet gets routed to 10.186.50.108 (node1)
 - 10.186.50.108 (node1) decides, that because of load balancing reasons, the request should be processed by 10.186.50.107 (node2) instead
 - 10.186.50.108 (node1) swaps out dst address of the packet to 10.186.50.107, and the 443 dst port to 6443. Then, forwards the packet to 10.186.50.107 (node2) on layer 2. It also encodes in the IP options header the initial destination address (10.185.192.1).
 - 10.186.50.107 (node2) processes the request
 - 10.186.50.107 (node2) sends reply to 192.168.0.1 with the source address being 10.186.50.107
 - Some stateful firewall in between 192.168.0.1 and node2, or in the end, 192.168.0.1's kernel discards the packet, since it is an invalid connection

The setup works every other time (when the service endpoints are pods), and the correct source IP gets placed into the packets.

### Cilium Version

1.13.2

### Kernel Version

5.14.0-284.11.1.el9_2.x86_64

### Kubernetes Version

v1.26.7+rke2r1

### Sysdump

I'd rather not post it, or if it's really necessary, after the lengthy process of censoring information that could be used to identify our organization.

### Relevant log output

```shell
No relevant logs. I could post some nginx-ingress controllers timing out, trying to reach the kube api if you think it would help.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lgyurci** [comment]
The nginx ingress controllers not being able to access the kube API turned out to be a networkpolicy issue (my bad). The issue with the external access still exists, and I would consider it as a bug (since the access is inconsistent). I know that normally, this shouldn't be an issue, since it is very rare, that you'd like to access an internal service externally where the endpoints are node addresses and ports, but practically could happen.

**Comment by lmb** [comment]
Thaks for the detailed write up. Are you able to reproduce this on the latest 1.13 point release?

**Comment by lgyurci** [comment]
We cannot update cilium easily unfortunately (the cluster is deployed with rancher, and cilium is managed by that)

**Comment by julianwiedmann** [comment]
In short - accessing a remote backend in `hostNetwork` with DSR. Should be fixed with https://github.com/cilium/cilium/pull/24795 / `v1.13.3`.

**Comment by julianwiedmann** [comment]
(hence still `needs-more-info` on a current release)

**Comment by lgyurci** [comment]
Seems like it's working in 1.14.0. Thank you.
