### ISSUE TITLE
Makefile: "make tags" fails

### ISSUE THREAD

**Issue by LeiW000** [cilium/cilium#28319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

OS: Ubutun 22.04.03
It looks like "make tags" fails. I checked the code. The "-L" is used with ctags. But it does not seem that there is "-L" option in ctags.

```
~/ws/cilium/cilium$ make tags
ctags: invalid option -- 'L'
        Try 'ctags --help' for a complete list of options.
make: *** [Makefile:164: tags] Error 1
```

### Cilium Version

latest version

### Kernel Version

Linux icx06 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

I don't think it has anything to do with k8s version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
I think you have an old or incompatible version of ctags installed:

```
$ ctags --help | grep -A 1 -B 1 -- -L
  -R   Equivalent to --recurse.
  -L <file>
       A list of input file names is read from the specified <file>
$ ctags --version
Universal Ctags 6.0.0, Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Feb  1 2023, 00:00:00
  URL: https://ctags.io/
  Output version: 0.0
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc, +optscript
```

Please try updating your ctags.

**Comment by LeiW000** [comment]
@lmb , Thanks for the quick reply. You are right. After installing universal-ctags, "make tags" works now.
