### ISSUE TITLE
BGP CP: Document AdvertisedPathAttributes

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#28315]
https://github.com/cilium/cilium/pull/27705 added support for `AdvertisedPathAttributes` but needs to be documented.

**Comment by YutaroHayakawa** [comment]
CC: @rastislavs

**Comment by rastislavs** [comment]
Yeah I plan on adding docs for this feature, however I think we should do that after some follow-up PRs are merged:
 - I will be opening a follow-up on https://github.com/cilium/cilium/pull/27705 that adds extended community support shortly,
 - I would also wait for https://github.com/cilium/cilium/pull/28310

Anyways, will take care of this - assigning.

**Comment by danehans** [comment]
@rastislavs thanks for the heads-up!
