### ISSUE TITLE
CFP: Enhance L2 Announcement

### ISSUE THREAD

**Issue by kvaster** [cilium/cilium#28326]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

One of the problems with kubernetes is external load balancers used for services (ingress for example). Load balancers should care about both failover and throughput. One kind of setup is to have private L2 network for nodes. Each node have a static IP inside. Also there is one more L2 network (several IPs with a gateway) and they can be dynamically assigned to the nodes (currently we do it via keepalived). This is really looks like new beta feature 'L2 Announcement', but 'L2 Announcement' assigns all external ip's defined for service to juts only one node. For failover and performance (via dsr) we need to try to distribute evenly external ip's on different nodes and to reassign them as soon as node will be treated as 'down'.

i.e. if we have three ip's (74.6.143.2-4 for example) and three nodes and ingress service with load balancer, I would expect that:
node1: 74.6.143.2, node2: 74.6.143.3, node3: 74.6.143.4.

If node3 goes down it may be: node1: 74.6.143.2, node2: 74.6.143.3 and 74.6.143.4

**Describe the feature you'd like**

Try to always evenly distribute all external ip's defined for service on all allowed nodes. Try to reassign ip as soon as possible whenever any node goes down.

**Comment by kvaster** [comment]
Any chances to look into this ?

**Comment by ksa-real** [comment]
bump
