### ISSUE TITLE
IPv6 not working between nodes because of extra route

### ISSUE THREAD

**Issue by CallMeFoxie** [cilium/cilium#28327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With cilium 1.14 we are having troubles with IPv6 routing between nodes. Cilium adds this to the interface:
```
7: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 9a:aa:d1:1e:5c:dc brd ff:ff:ff:ff:ff:ff
    inet 10.11.22.33/32 scope global cilium_host
       valid_lft forever preferred_lft forever
    inet6 2a02:aa:bb:8a00::2080:2bd/64 scope global 
       valid_lft forever preferred_lft forever
```

which also - by default - adds a route
```
2a02:aa:bb:8a00::2080:2b8 dev lxc_health proto kernel metric 1024 pref medium
2a02:aa:bb:8a00::2080:200/120 dev cilium_host proto kernel src 2a02:aa:bb:8a00::2080:2bd metric 1024 pref medium
2a02:aa:bb:8a00::/64 dev cilium_host proto kernel metric 256 pref medium
```

which crosses with our ip pool:
```
2a02:aa:bb:8a00::2080:0/105
```

meaning all the pod-to-pod traffic gets improperly routed.

It seems to work fine with Cilium 1.13. I do not have any kubernetes cluster by hand to check, but our openstack cilium 1.13 cluster has assigned IPv6 with `/128` mask but also `--ipv6-node` flag set.

There's `noprefixroute` flag in netlink which seems to add the IP but not add the route on that interface, but I am struggling to build cilium outside of CI and it is Friday ( :upside_down_face: ) so cannot test it until Monday. My idea to try out is this patch:
```patch
diff --git a/pkg/datapath/loader/netlink.go b/pkg/datapath/loader/netlink.go
index bfecce37f0..9b1ce01ced 100644
--- a/pkg/datapath/loader/netlink.go
+++ b/pkg/datapath/loader/netlink.go
@@ -435,6 +435,7 @@ func addHostDeviceAddr(hostDev netlink.Link, ipv4, ipv6 net.IP) error {
                                IP:   ipv6,
                                Mask: net.CIDRMask(64, 128), // corresponds to /64
                        },
+                       Flags: unix.IFA_F_NOPREFIXROUTE,
                }
 
                if err := netlink.AddrReplace(hostDev, &addr); err != nil {
```

if this works I will be happy to sent a PR

### Cilium Version

1.14.1

### Kernel Version

5.15.0-69-generic

### Kubernetes Version

1.27.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CallMeFoxie** [comment]
Added the forementioned patch and managed to build it and it seems to have fixed the issue, I can now access pods across nodes and from external place successfully

```
7: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 9a:aa:d1:1e:5c:dc brd ff:ff:ff:ff:ff:ff
    inet 10.89.4.57/32 scope global cilium_host
       valid_lft forever preferred_lft forever
    inet6 2a02:aa:bb:8a00::2080:2bd/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
```

I will create the PR while I do more testing, as I am not sure if it broke something in return :-)

**Comment by rgo3** [comment]
Thanks for creating the issue (and subsequent PR)! 

I'm a bit hesitant to just add a netlink flag that solves a specific issue if we haven't confirmed that this flag missing is a regression from 1.13 to 1.14. AFAICT `noprefixroute` was not set either in the 1.13 code, looking at the iproute2 [code](https://github.com/iproute2/iproute2/blob/main/ip/ipaddress.c) it isn't set as the default when calling `ip -6 addr add ...`. 

The first thing we'll need to figure out is if the transition from the previous bash script ([`init.sh`](https://github.com/cilium/cilium/blob/v1.13.7/bpf/init.sh)) introduced a new bug. If yes, we need to make sure that the new go code exactly matches what we had in `init.sh` and hope that this solves the issue. If not there is most likely a different reason that causes this.

**Comment by CallMeFoxie** [comment]
I very much agree with that, which is why we need further testing :) The only other specimen I had to compare to was 1.13 but for some reason that had /128 on the iface instead. Will see if I can dig out some forgotten 1.13 cluster with IPv6 somewhere myself

**Comment by nikhiljha** [comment]
This seems maybe related to #27898 -- have you tested this commit (https://github.com/cilium/cilium/commit/b3a6b4e703200ffb5f066f08511f8bb7d6fee047) vs this one (https://github.com/cilium/cilium/commit/d10e8ebed3863849ea819aec63fcd8546b85b171)?

**Comment by jschwinger233** [comment]
Could you provide the cilium configuration for reproduction?

**Comment by CallMeFoxie** [comment]
OKay so we managed to test current 1.15.0 branch with the patch already included and it is still broken the same way.

I wonder if the /64 was added because most clouds/providers/places/... are used with tunnelling? We do not use any tunnel as we use eBGP against TOR. Removing the prefix route seems to fix our use case. Not sure I can test it in tunnelling mode though. And apparently we did not really test IPv6 on 1.13 either sadly.

**Comment by CallMeFoxie** [comment]
@ti-mo if the patch is included in current 1.15.0 branch then yes, it has been tested :)

I will ask colleague to build it with /128 instead. In theory it should have the exact same effect. However it would be nice to know why *originally* it was /64 in 1.13 with the shell script :)

**Comment by oblazek** [comment]
yeah it has been tested with #28417 included.. 

> I will ask colleague to build it with /128 instead.

I'm on it.

**Comment by ti-mo** [comment]
Nice, thanks for confirming Ondrej.

> However it would be nice to know why originally it was /64 in 1.13 with the shell script :)

`ip a add fe80::99 dev eth0` (with the prefix size omitted) should always result in `inet6 fe80::99/128 scope link`, not /64. This slipped through review and testing, and I'm not sure how this isn't causing more widespread issues.

**Comment by rgo3** [comment]
I think it is just a translation error by me when porting the script to Go. I'm still trying to figure out why I changed it to /64 but as Timo says, just running `ip -6 a add fe80::99 dev eth0` results in /128 and not /64. Using `net.CIDRMask(128, 128)` should be equivalent to the old behavior in `init.sh` and resolve this issue.

**Comment by CallMeFoxie** [comment]
Yes setting it to /128 works fine as well, let me update the PR then
