### ISSUE TITLE
Delayed identity cleanup on operator restart

### ISSUE THREAD

**Issue by skmatti** [cilium/cilium#28339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On operator start up, all identities are marked as alive irrespective of whether an identity has the delete annotation

https://github.com/cilium/cilium/blob/bb6decf7c7e2e31da91cc94e7d2c050a2d937048/operator/identitygc/crd_gc.go#L52

The delete annotation is added on an identity in https://github.com/cilium/cilium/blob/bb6decf7c7e2e31da91cc94e7d2c050a2d937048/operator/identitygc/crd_gc.go#L125 

As the default heartbeat timeout is 30 minutes, an identity that was marked for deletion with an annotation is marked alive on operator start up and delays the cleanup by 30 minutes.

I think an identity with the deletion annotation should not marked alive again. Is there an issue with this?.

### Cilium Version

1.12

### Kernel Version

not applicable

### Kubernetes Version

1.27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonohart** [comment]
The larger problem that this causes is every time the operator restarts, identity GC is delayed again by at least the ID timeout value (30 mins default). The operator will restart it loses leader election due to k8s api calls failing. If this happens often enough, say once per hour, then the operator GC logic keeps delaying the GC of identities further and further in the future which allows identities to accumulate until the policy maps fill up.

**Comment by skmatti** [comment]
@dlapcevic @aojea Is this addressed with https://github.com/cilium/cilium/issues/27752, if so can you open this and reassign to yourself. 

If this needs to be handled separately, can you open so others can take a look?. Thanks!

**Comment by dlapcevic** [comment]
Yes, this will be addressed with https://github.com/cilium/cilium/issues/27752.

The plan is to immediately clean up unused Cilium Identities. They will anyway be cleaned up when operator starts.

**Comment by skmatti** [comment]
@dlapcevic Is this issue addressed?. Can we mark it as fixed or reopen if there is pending work?

**Comment by dlapcevic** [comment]
https://github.com/cilium/cilium/issues/34740
