### ISSUE TITLE
Helm: cilium-envoy metrics endpoint not included in cilium-agent ServiceMonitor

### ISSUE THREAD

**Issue by PhilipSchmid** [cilium/cilium#28356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Let's imagine somebody wants to run the Cilium built-in Envoy proxy, is trying to expose the envoy metrics endpoint (`envoy_*`) and lets Prometheus scrape it. Unfortunately, that's currently not supported with our Helm chart. I doubt that's intentional. It actually looks more like a bug to me.

While the `cilium-agent` DS gets the regarding `envoy-metrics` port:

https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L245-L250

... and the `cilium-agent` Services exposes the `envoy-metrics` targetPort in case `.Values.prometheus.serviceMonitor.enabled` is set:

https://github.com/cilium/cilium/blob/v1.13.7/install/kubernetes/cilium/templates/cilium-agent/service.yaml#L22-L25

... it's **not** used in the `cilium-agent` ServiceMonitor:

https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-agent/servicemonitor.yaml#L30-L43

Hence, if somebody wants to scrape those metrics, they need to manually create a dedicated ServiceMonitor resource to scrape `9964/TCP` from the Cilium agent pods.

Honestly, I'm not 100% sure if we should even support this and if so, how. The main issue is that Envoy will only start if required (i.e. there is l7 policy/ingress/gateway/CEC enabled, etc.), so even if the Envoy metrics port is enabled, it might not be open at the installation time. This would then result in Prometheus seeing this target as unavailable.
Originally, I thought about an explicit flag to enforce the inclusion of the `envoy-metrics` port in the `cilium-agent` ServiceMonitor, but then I found [this](https://github.com/cilium/cilium/commit/e04fa7c2566aa7f3a9e72401824b68d67f9fcfd7) commit co-authored by @mhofstetter and @jrajahalme.

Currently, I see 4 possible solutions:
1. Introduce new Helm flags in the Cilium Agent "monitoring" section `.Values.prometheus.*`. E.g. `.Values.prometheus.envoy.enabled=false`, `.Values.prometheus.envoy.port=9964` and  `.Values.prometheus.serviceMonitor.envoyMetrics=false` (`=.*` = default values).
2. Leverage the existing `.Values.proxy.prometheus` section, which is, according to @sayboras, anyway handling Cilium Envoy stuff and not Istio proxy things like stated in the comment (`# -- Configure Istio proxy options.`). This would then also need a `.Values.proxy.prometheus.serviceMonitor` subsection like we have [for the agent](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml#L1847-L1869). However, this potential solution conflicts with the deprecation intention of the linked commit from above.
3. We could adjust the `cilium-agent` ServiceMonitor [logic](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-agent/servicemonitor.yaml#L30-L41) to also include [stuff from the `.Values.envoy.prometheus` section](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml#L2072-L2097), even though we don't run the standalone Envoy DS (`.Values.envoy.enabled=false`). This may cause confusion.
4. We don't do anything as we intend to go with the standalone Cilium Envoy DS in the future anyway. Until then, users simply need to continue to create their own `envoy-metrics` ServiceMonitor in case they want to scrape from the Cilium built-in Envoy metrics endpoint.

### Cilium Version

All of them

### Kernel Version

Doesn't matter

### Kubernetes Version

Doesn't matter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
After talking amongst the team, we're trying to move all config eventually into `.envoy.prometheus` and children, even though `.envoy.enabled=false` in this case.

I'm opening a PR now to cover this option.
