### ISSUE TITLE
Impossible to configure cilium via helm values

### ISSUE THREAD

**Issue by riuvshyn** [cilium/cilium#28381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

It impossible to configure some cilium options like set `enable-k8s-networkpolicy` to `false` in cilium helm chart
As per documentation `enable-k8s-networkpolicy` is `true` by default, so in case one wants to disable it, nothing happens because helm template allows only to enable it.
[This](https://github.com/cilium/cilium/blob/v1.14.1/install/kubernetes/cilium/templates/cilium-configmap.yaml#L766-L768) allows only setting to `true` (which is `true` by default). 
I am pretty sure it is not the only option which might have similar issue.

### Cilium Version

1.14.x, 1.15.x

### Kernel Version

N/A

### Kubernetes Version

N/A

### Sysdump

not relevant

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hello, thanks for opening the GH issue, please provide steps to reproduce the issue and a cilium sysdump otherwise the issue can't be fixed. Thank you.

**Comment by riuvshyn** [comment]
as a workaround I've used `extraConfig`

**Comment by riuvshyn** [comment]
@aanm Thanks for looking in to this, 
steps to reproduce are pretty simple:
1. install cilium using chart configured to disable native k8s netpolicies support.

expectations:
- ability to turn off k8s native net policies support via helm chart values, as there is already `k8sNetworkPolicy` option available.

reality:
- `k8sNetworkPolicy` can be used only to set `enable-k8s-networkpolicy` to `true` due to the way how templating is done, and this doesn't make any sense because `enable-k8s-networkpolicy` is `true` by default.


However I was able to workaround it by doing this:

```
    extraConfig:
      enable-k8s-networkpolicy: "false"
```

**Comment by gandro** [comment]
So the bug fix here would be correct up the linked entry:
https://github.com/cilium/cilium/blob/v1.14.1/install/kubernetes/cilium/templates/cilium-configmap.yaml#L766-L768

To use something like
```yaml
{{- if hasKey .Values.k8sNetworkPolicy "enabled" }}
  enable-k8s-networkpolicy: {{ .Values.k8sNetworkPolicy.enabled | quote }}
{{- end }}
```

That way, it can be set to false. I'll mark this as a `good-first-issue`

**Comment by aanm** [comment]
This seems to work for me.

```yaml
$ cat values.yaml
k8sNetworkPolicy:
    enabled: "false"
```
```bash
$ helm template cilium cilium/cilium -f values.yaml | grep 'enable-k8s-networkpolicy'
enable-k8s-networkpolicy: "false"
```

**Comment by riuvshyn** [comment]
ohh... maybe I was doing 
```
k8sNetworkPolicy:
    enabled: false
```

I might've missed quotes... which makes sense.

@aanm Feel free to close the issue.

**Comment by gandro** [comment]
> This seems to work for me.
> 
> ```yaml
> $ cat values.yaml
> k8sNetworkPolicy:
>     enabled: "false"
> ```
> 
> ```shell
> $ helm template cilium cilium/cilium -f values.yaml | grep 'enable-k8s-networkpolicy'
> enable-k8s-networkpolicy: "false"
> ```

In my opinion, requiring a "string" for something that is supposed to be a boolean value is a bug. It also yields a worse user experience, as `--set k8sNetworkPolicy.enabled="false"` will not work on the command-line (one has to use --set-string).  Let's not close this and instead fix our templates.

**Comment by hasan-alkama** [comment]
Hi, if this issue still there i want to work on this can you assign me?

**Comment by hasan-alkama** [comment]
It seems like this is working for me in the latest version( 1.16.0-dev.) of Cilium "
I cloned main branch.
`helm install cilium --set enable-k8s-networkpolicy=false`

**Comment by hasan-alkama** [comment]
@gandro ,There is one pr raised against this issue as mentioned. but is not yet merged and closed .do i need to raise another pr request for this issue to close ?
