### ISSUE TITLE
Thrashing retry when Map update fails

### ISSUE THREAD

**Issue by joshrosso** [cilium/cilium#28386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Likely related to us hitting map limits (see https://github.com/cilium/cilium/issues/27866), we've noticed when we're in this state, a log message will show such as:

```
level=error msg="Failed to add PolicyMap key" bpfMapKey="{64 61661 0 6 36895}" containerID=4937d57d18 datapathPolicyRevision=56 desiredPolicyRevision=56 endpointID=1846 error="update map cilium_policy_01846: update: no space left on device" identity=56259 ipv4=<removed> ipv6= k8sPodName=flux-system/notification-controller-5dc5586b8b-gv6rj port=0 subsys=endpoint
```

However, we've noticed this logic will retry (and emit the above log message) upwards of 20k messages per second. 

<img width="2590" alt="Screenshot 2023-10-03 at 9 18 40 AM" src="https://github.com/cilium/cilium/assets/6200057/e9026a78-e032-448e-91ff-ceeba1e31bb0">

> Note this graph represents our throttled logs, so is missing our base accepted amount, which is 5k.

I believe the code path that this triggers may be:

https://github.com/cilium/cilium/blob/93f401129bff6487933f2bc083a1c333ea356c7e/pkg/bpf/map_linux.go#L844-L852

This isn't an extremely problematic thing for us, but figured it might benefit to surface in case some amount of backoff would be warranted?

Thanks all!

### Cilium Version

`v1.14.2`

### Kernel Version

`Linux ip-10-10-47-183.ec2.internal 6.2.0-1012-aws #12~22.04.1-Ubuntu SMP Thu Sep  7 14:01:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`1.24.9`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
Thanks for the report, we're planning on reworking the dozens of BPF map reconcilers in the code base around a single mechanism. Backoff is an important part of that, and we should also log judiciously. We'll use this issue as a data point.

cc @joamaki

**Comment by joestringer** [comment]
@ti-mo I'm curious, how big of an effort is that? I think that approach sounds definitely like something we should work towards. At the same time, a very simple timer wrap + error check around this current log could potentially ratelimit the log & mitigate the logging issue with just a few lines of code. Could be another shorter term step on the way towards general better policymap entry population handling behaviour?

**Comment by christarazi** [comment]
In theory, if the BPF map was created with `WithCache`, then this creates a userspace copy of the BPF map which means we have the current count and we also know the max entries. That allows us to determine whether an insert into a map will fail, so we could catch this and prevent it, with say, a rate-limited log msg.

**Comment by joamaki** [comment]
I'm looking at improving the policy map reconciliation efficiency in https://github.com/cilium/cilium/pull/28472 and solving this issue as part of it could make sense. The approach there is to move the policy map reconciliation into the controller rather than doing the incremental processing directly. We would only need to configure the controller's retry backoff to make sure reconciliation isn't being done too aggressively when the map is full. Rate-limiting log messages would also make sense.
