### ISSUE TITLE
CI: AKS failures with "Bad Request"

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#28402]
## CI failure

Example failure:
https://github.com/cilium/cilium/actions/runs/6404410581/job/17384930283

```
ERROR: (BadRequest) Bad request
Code: BadRequest
Message: Bad request
```

**Comment by joestringer** [comment]
Jibi enabled `--debug --verbose` in a job here to investigate further, but there's not much additional info that I can see:

https://github.com/cilium/cilium/pull/28398
https://github.com/cilium/cilium/actions/runs/6406120366

**Comment by nbusseneau** [comment]
I am reproducing the issue using my personal account by copy/pasting the commands from the CI runs, so it's not account related.

**Comment by nbusseneau** [comment]
I can reproduce the issue consistently on the `cilium-pr` subscription (used for CI), it started happening 18 hours ago as per the subscription's activity logs. No issue at all on other subscriptions. Very weird 🤔

**Comment by wedaly** [comment]
AKS was throttling cluster create operations from the subscription used by Cilium CI. We've made an update to allow this subscription, and I see that [recent CI runs](https://github.com/cilium/cilium/actions/runs/6409533541/job/17400901514) are now able to create a cluster successfully.
