### ISSUE TITLE
Ginkgo CI: log shell commands that are ran on VMs without resultant output to separate file for each test

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2841]
Proposal: One of the advantages of the bash-based framework is that it was very easy to run the commands from the tests directly from the script itself. The Ginkgo framework however, obfuscates this. We currently create a file called 'logs' which logs information about the commands that are ran, including their output. However, it would be helpful to have a file that only contains the logs that are ran, so that someone could manually run the commands from the test on their host directly instead of through Ginkgo. 

This is merely a suggestion - I am open to feedback on this.

**Comment by eloycoto** [comment]
This proposal is not difficult, but I'm worried when we use templates to create files on the fly, that can't be in that file so it'll not cover 100% of the cases.

**Comment by ianvernon** [comment]
@eloycoto best-effort is fine for this.

**Comment by eloycoto** [comment]
Duplicated by https://github.com/cilium/cilium/issues/2843?
