### ISSUE TITLE
Cilium operator cannot allocate IP addresses when AWS launch new instance types

### ISSUE THREAD

**Issue by sergeyshevch** [cilium/cilium#28424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- The cilium operator relies on the ec2 instance limit in the process of IP allocation. This information fetched from AWS API on the Cilium operator startup here: https://github.com/cilium/cilium/blob/main/pkg/ipam/allocator/aws/aws.go#L102
- On 4 Oct 2023 AWS launched new instance types c7a ([blog post](https://aws.amazon.com/blogs/aws/new-amazon-ec2-c7a-instances-powered-by-4th-gen-amd-epyc-processors-for-compute-optimized-workloads/))
- The Cilium operator that was already running before that launch has no information about limits for c7a types
- We are using Karpenter for node provisioning. It periodically fetches information about new instance types and started provisioning c7a instances because it’s cheap  (because a low amount of AWS customers use new instance types right after launch)
- Karpenter provisions new nodes and Cilium cannot allocate IP addresses on it

Some cilium operator logs in the process of the incident

--update-ec2-adapter-limit-via-api already set to true and the issue was fixed after the ilium-operator reboot

I guess that cilium-operator should periodically fetch this API for new instance types to prevent such issues

### Cilium Version

Client: 1.14.2 a6748946 2023-09-09T20:59:33+00:00 go version go1.20.8 linux/amd64
Daemon: 1.14.2 a6748946 2023-09-09T20:59:33+00:00 go version go1.20.8 linux/amd64

### Kernel Version

Linux <NodeName> 5.15.128 #1 SMP Thu Sep 14 21:42:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

n/a

### Relevant log output

```shell
2023-10-04 17:57:17.292 
level=warning msg="Unable to find limits for instance type, consider setting --update-ec2-adapter-limit-via-api=true on the Operator" instance-type=c7a.large subsys=eni

2023-10-05 10:39:24.478 
level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-0b7fc3f275d818c7f name=ip-10-7-128-51.ec2.internal subsys=ipam
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Thanks for the bug report. I'm glad to see that a restart fixes the issue.

Most likely we should trigger a re-fetch if we don't find the instance type we expect (with some reasonable backoff to prevent pathological cases).

**Comment by sergeyshevch** [comment]
https://aws.amazon.com/ru/about-aws/whats-new/2023/10/amazon-ec2-r7i-instances/
Same issue with new r7i instances. 

@squeed Is this issue planned in any way?

**Comment by squeed** [comment]
@sergeyshevch yes, it should make it's way down the queue and be fixed in time. Feel free to jump on it if you have the cycles.

**Comment by sergeyshevch** [comment]
Not stale
