### ISSUE TITLE
Cilium BGP Control Plane: Wrong (Best) Path

### ISSUE THREAD

**Issue by siddjellali** [cilium/cilium#28426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have successfully set up the BGP Control Plane and IP pool for the load balancer. However, the BGP advertisements, which are being announced by Cilium from three Kubernetes nodes (k8s01, k8s02, k8s03), all have the same weight. This setup does not allow for precise identification of the load balancer service location. For example, the service 'portainer' is deployed on k8s02 (192.168.252.11), but the best path is being directed to k8s03 (192.168.252.12), rendering the service inaccessible from my user network.

```
[root@k8s01 ~]# kubectl get nodes -o wide
NAME    STATUS   ROLES           AGE   VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                      KERNEL-VERSION                 CONTAINER-RUNTIME
k8s01   Ready    control-plane   22h   v1.27.6   192.168.252.10   <none>        Rocky Linux 9.2 (Blue Onyx)   5.14.0-284.30.1.el9_2.x86_64   containerd://1.6.24
k8s02   Ready    worker          22h   v1.27.6   192.168.252.11   <none>        Rocky Linux 9.2 (Blue Onyx)   5.14.0-284.30.1.el9_2.x86_64   containerd://1.6.24
k8s03   Ready    worker          22h   v1.27.6   192.168.252.12   <none>        Rocky Linux 9.2 (Blue Onyx)   5.14.0-284.30.1.el9_2.x86_64   containerd://1.6.24

[root@k8s01 ~]# kubectl get pods -n portainer -o wide
NAME                         READY   STATUS    RESTARTS   AGE   IP           NODE    NOMINATED NODE   READINESS GATES
portainer-5888b58d44-8lfq6   1/1     Running   0          8h    10.0.0.152   k8s02   <none>           <none>

[root@k8s01 ~]# kubectl get svc -n portainer
NAME        TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                         AGE
portainer   LoadBalancer   10.102.21.130   10.200.0.139   9443:31341/TCP,8000:30892/TCP   8h
```

Thanks a lot for your support

### Cilium Version

```
cilium-cli: v0.15.8 compiled with go1.21.0 on linux/amd64
cilium image (default): v1.14.1
cilium image (stable): v1.14.2
cilium image (running): 1.14.2
```

### Kernel Version

```
Linux k8s01 5.14.0-284.30.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep 16 09:55:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

### Kubernetes Version

```
Client Version: v1.27.6
Kustomize Version: v5.0.1
Server Version: v1.27.6
```

### Sysdump

🔍 Collecting sysdump with cilium-cli version: v0.15.8, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
🔮 Detected Cilium operator in namespace "kube-system"
ℹ️ Failed to detect Cilium SPIRE installation - using Cilium namespace as Cilium SPIRE namespace: kube-system
🔍 Collecting Kubernetes nodes
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes network policies
🔍 Collecting Kubernetes metrics
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium network policies
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium CIDR Groups
🔍 Collecting Cilium endpoint slices
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium nodes
🔍 Collecting Cilium identities
🔍 Collecting Ingresses
🔍 Collecting Cilium Node Configs
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting IngressClasses
🔍 Collecting Cilium BGP Peering Policies
🔍 Collecting CiliumEnvoyConfigs
🔍 Collecting Cilium LoadBalancer IP Pools
🔍 Collecting Cilium Pod IP Pools
🔍 Checking if cilium-etcd-secrets exists in kube-system namespace
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Cilium configuration
🔍 Collecting the Cilium Node Init daemonset
🔍 Collecting the Cilium Envoy configuration
🔍 Collecting the Hubble daemonset
🔍 Collecting the Cilium Envoy daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
🔍 Collecting the Cilium operator metrics
🔍 Collecting the clustermesh metrics
⚠️ Daemonset "cilium-node-init" not found in namespace "kube-system" - this is expected if Node Init DaemonSet is not enabled
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting gops stats from Cilium pods
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
⚠️ Daemonset "cilium-envoy" not found in namespace "kube-system" - this is expected if Envoy DaemonSet is not enabled
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
⚠️ Deployment "hubble-ui" not found in namespace "kube-system" - this is expected if Hubble UI is not enabled
🔍 Collecting bugtool output from Cilium pods
🔍 Collecting profiling data from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium Envoy pods
🔍 Collecting logs from Cilium Node Init pods
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting logs from Cilium SPIRE server pods
🔍 Collecting logs from Cilium SPIRE agent pods
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting the Cilium SPIRE server statefulset
🔍 Collecting the Cilium SPIRE agent daemonset
⚠️ StatefulSet "spire-server" not found in namespace "kube-system" - this is expected if SPIRE installation is not enabled
🔍 Collecting the Cilium SPIRE agent configuration
Secret "cilium-etcd-secrets" not found in namespace "kube-system" - this is expected when using the CRD KVStore
🔍 Collecting the Cilium SPIRE server configuration
⚠️ Daemonset "spire-agent" not found in namespace "kube-system" - this is expected if SPIRE installation is not enabled
🔍 Collecting platform-specific data
🔍 Collecting kvstore data
🔍 Collecting Cilium external workloads
🔍 Collecting GatewayClass entries
🔍 Collecting Gateway entries
🔍 Collecting ReferenceGrant entries
🔍 Collecting HTTPRoute entries
🔍 Collecting TLSRoute entries
🔍 Collecting GRPCRoute entries
🔍 Collecting TCPRoute entries
🔍 Collecting UDPRoute entries
🔍 Collecting Hubble flows from Cilium pods
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting Tetragon tracing policies
🔍 Collecting Helm values from the release
⚠️ ConfigMap "spire-agent" not found in namespace "kube-system" - this is expected if SPIRE installation is not enabled
⚠️ ConfigMap "spire-server" not found in namespace "kube-system" - this is expected if SPIRE installation is not enabled
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [13] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource
⚠️ [14] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [16] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [18] Collecting Cilium endpoint slices: failed to collect Cilium endpoint slices: the server could not find the requested resource (get ciliumendpointslices.cilium.io)
⚠️ [24] Collecting CiliumClusterwideEnvoyConfigs: failed to collect CiliumClusterwideEnvoyConfigs: the server could not find the requested resource (get ciliumclusterwideenvoyconfigs.cilium.io)
⚠️ [25] Collecting CiliumEnvoyConfigs: failed to collect CiliumEnvoyConfigs: the server could not find the requested resource (get ciliumenvoyconfigs.cilium.io)
⚠️ [33] Collecting the Cilium Envoy configuration: failed to collect the Cilium Envoy configuration: configmaps "cilium-envoy-config" not found
⚠️ [67] Collecting GatewayClass entries: failed to collect GatewayClass entries: the server could not find the requested resource
⚠️ [68] Collecting Gateway entries: failed to collect Gateway entries: the server could not find the requested resource
⚠️ [69] Collecting ReferenceGrant entries: failed to collect ReferenceGrant entries: the server could not find the requested resource
⚠️ [70] Collecting HTTPRoute entries: failed to collect HTTPRoute entries: the server could not find the requested resource
⚠️ [71] Collecting TLSRoute entries: failed to collect TLSRoute entries: the server could not find the requested resource
⚠️ [72] Collecting GRPCRoute entries: failed to collect GRPCRoute entries: the server could not find the requested resource
⚠️ [73] Collecting TCPRoute entries: failed to collect TCPRoute entries: the server could not find the requested resource
⚠️ [74] Collecting UDPRoute entries: failed to collect UDPRoute entries: the server could not find the requested resource
⚠️ [77] Collecting Tetragon tracing policies: failed to collect Tetragon tracing policies: the server could not find the requested resource (get tracingpolicies.cilium.io)
⚠️ metrics-cilium-operator-68d46654c5-bs8db-cilium-operator-prometheus: failed to collect the Cilium clustermesh metrics: failed to find port prometheus in container cilium-operator in pod cilium-operator-68d46654c5-bs8db - this is expected if prometheus metrics are disabled
⚠️ metrics-cilium-operator-68d46654c5-g9s7n-cilium-operator-prometheus: failed to collect the Cilium clustermesh metrics: failed to find port prometheus in container cilium-operator in pod cilium-operator-68d46654c5-g9s7n - this is expected if prometheus metrics are disabled
⚠️ Please note that depending on your Cilium version and installation options, this may be expected
🗳 Compiling sysdump
✅ The sysdump has been saved to cilium-sysdump-20231005-190004.zip

[cilium-sysdump-20231005-190004.zip](https://github.com/cilium/cilium/files/12821177/cilium-sysdump-20231005-190004.zip)

### Anything else?

```
FortiGate #  get router info bgp network 10.200.0.139
VRF 0 BGP routing table entry for 10.200.0.139/32
Paths: (3 available, best #3, table Default-IP-Routing-Table)
  Advertised to non peer-group peers:
   192.168.252.10 192.168.252.11
  Original VRF 0
  64512
    192.168.252.10 from 192.168.252.10 (192.168.252.10)
      Origin IGP metric 0, localpref 100, valid, external
      Last update: Thu Oct  5 17:52:34 2023

  Original VRF 0
  64512
    192.168.252.11 from 192.168.252.11 (192.168.252.11)
      Origin IGP metric 0, localpref 100, valid, external
      Last update: Thu Oct  5 17:52:35 2023

  Original VRF 0
  64512
    192.168.252.12 from 192.168.252.12 (192.168.252.12)
      Origin IGP metric 0, localpref 100, valid, external, **best**
      Last update: Thu Oct  5 17:52:36 2023

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YutaroHayakawa** [comment]
The expected behavior here is your router (FortiGate) will load balance the traffic with ECMP. However, looks like only one route is selected as the best path. Please check if your router is capable of ECMP load balancing.

Also, your service `portainer` has `externalTrafficPolicy: Cluster`, so in the regular Kubernetes setup, all nodes can forward the packet to the node which runs the service backend pods. In your case, when `k8s03` receives the packet, it should redirect the packet to `k8s02`, but you said when your `k8s03` receives the traffic, the service becomes "unreachable". I guess something going wrong here.

**Comment by siddjellali** [comment]
Thanks for your quick reply :)
Solution is already documented here : https://docs.cilium.io/en/stable/network/bgp-control-plane/#semantics-of-the-externaltrafficpolicy-local

**Comment by siddjellali** [comment]
found the issue IPForwarding...

This command is not enough : `echo 1 > /proc/sys/net/ipv4/ip_forward`

>> Correct command: sysctl --write net.ipv4.ip_forward=1

Thanks @YutaroHayakawa
