### ISSUE TITLE
hello I would like to collaborate with your project serving as a translator to Spanish which is my native language

### ISSUE THREAD

**Issue by LuigiBaute** [cilium/cilium#2842]

**Comment by tgraf** [comment]
Hi @LuigiBaute, thanks for the offer! We haven't thought about translation yet but the only artefact that can benefit from translation is the documentation in `Documentation/`

**Comment by LuigiBaute** [comment]
Ok should How should I start posting them? by branches, commits. let me know...

**Comment by joestringer** [comment]
@LuigiBaute Looks like we lost track of your reply here, sorry about that. At the moment, the sphinx docs are not well set up for translations, but if you're still interested, I would suggest looking into the sphinx docs for how to set up for docs translation:

http://www.sphinx-doc.org/en/master/intl.html#quick-guide

I'd expect such an integration to start with a basic PR to put the translation infrastructure in place for allowing sphinx to generate the translated docs from some translation files, then you could tackle each document in a separate PR.
