### ISSUE TITLE
hello I would like to collaborate with your project serving as a translator to Spanish which is my native language

### ISSUE THREAD

**Issue by LuigiBaute** [cilium/cilium#2844]
**Important:** Join our [slack channel](http://cilium.io/slack) for immediate
support and an opportunity to ask questions. Please also have a look at our
[FAQ](https://goo.gl/qG2YmU) for frequently asked questions first.

If you open a GitHub issue, please follow these guidelines:

1. It must be a bug or a feature request.
2. The form below must be filled out.

--------------

### Title

Choose a descriptive title that summarizes the symptom of the bug

### General Information

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)

### How to reproduce the issue

1. instruction 1
2. instruction 2

### Title

Choose a descriptive title, e.g. "Support delivering pizzas"

### Description of requested functionality

Paragraph goes here

### Example use cases

Use case description goes here

### List of sub tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by tgraf** [comment]
Dup of #2842
