### ISSUE TITLE
After recent system update starwars demo suddenly stopped working

### ISSUE THREAD

**Issue by inliquid** [cilium/cilium#28454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm using these test pods on `kind` local cluster:

1. https://raw.githubusercontent.com/cilium/tetragon/main/testdata/specs/testpod.yaml
2. https://raw.githubusercontent.com/cilium/cilium/main/examples/minikube/http-sw-app.yaml

After recent system update (`apt update && apt upgrade`) both `test-pod` and `deathstar` pods do not work normally:
1. `test-pod` can't start:
    ```
    failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "sleep": executable file not found in $PATH: unknown
    ```
    
    It worked before that without any issue for quite a long period of time.
2. Can't connect to `deathstar` with `kubectl exec`:
    ```
    $ kubectl exec -it deathstar-7848d6c4d5-bv4wc --namespace default --container deathstar -- sh
    error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "d1c85145b5017031c6e6e02db0749b68cd2f861740b4c62b75033ea5198fe71d": OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown
    ```
    Same when I try `sh`, `bash`, `/bin/bash`.

    It also worked without any issue.

Note that "unknown" at the end of error message.

Please advice, we use these test pods in local testing and development and now this issue blocks it. =(

### Kernel Version

```
$ uname -a
Linux mint-vm 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hey @aanm I see that you released a v2.0 of the deathstar image a couple of weeks ago. Does the new image remove shells and common commands? Have we integrated that new version into CI yet?

**Comment by inliquid** [comment]
I can confirm that setting `docker.io/cilium/starwars:v1.0` (instead of `latest`) resolves above issues.

**Comment by lizrice** [comment]
The latest version was rebuilt to [work on ARM](https://github.com/cilium/starwars-docker/pull/3), and for simplicity and small size I built it on a scratch image. If we need other executables for test scripts etc then it would be easy enough to change it back to a Linux distro base image again

**Comment by inliquid** [comment]
Up

**Comment by inliquid** [comment]
Up

**Comment by inliquid** [comment]
Up

**Comment by ti-mo** [comment]
@joestringer Ping, looks like you were making some changes with https://github.com/cilium/cilium/pull/31146, but not sure if this issue has been fixed by now.

**Comment by joestringer** [comment]
@ti-mo Same status as https://github.com/cilium/cilium/issues/28454#issuecomment-1768098920. To reintroduce a shell, someone would need to submit the proposed changes into https://github.com/cilium/starwars-docker .

**Comment by joestringer** [comment]
(Removing agent classification - it's not really an agent bug, this was a side-effect of introducing multi-platform images in https://github.com/cilium/starwars-docker).

**Comment by inliquid** [comment]
Up

**Comment by joestringer** [comment]
Hi @inliquid , in practice these images were designed specifically for demo usage for the examples on https://docs.cilium.io so any usage beyond that is not top of mind for the maintainers of these images. This is why it broke when a new major version was released.

>  test-pod can't start: [...]

The latest tetragon YAML no longer uses that image.

> Can't connect to deathstar with kubectl exec: [...]

We've outlined the steps to make this work in the [comment above](https://github.com/cilium/cilium/issues/28454#issuecomment-2181382728). If you're using this for your own purposes, you could either create your own dockerfile using these images as a base and then add the tools that you want, or you could propose a PR to change https://github.com/cilium/starwars-docker to include a shell and other tools.

I'll close this as wont-fix, but if you wish to submit a change to support this use case then you are welcome to do so.
