### ISSUE TITLE
Cilium possibly leaking overlay network IP

### ISSUE THREAD

**Issue by deanmax** [cilium/cilium#28461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a standalone envoy ingress controller running in pod(daemonset) in AWS EKS environment. We're running Cilium as CNI in default mode(encapsulation, with egress masquerade interface set to `eth0`) in our cluster. I was troubleshooting an issue related to [AWS ENA conntrack table](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-network-performance-ena.html) getting full that causing all subsequent traffic getting dropped. During the investigation, I did a tcpdump(`tcpdump tcp -i eth0 -s96 -w dump.pcap`) on eth0 of the underlying EC2 instance where envoy pod was running and found sometimes the egressing traffic from envoy to client was using **k8s internal(pod) IP** as source
<img width="1484" alt="Screenshot 2023-09-15 at 15 14 03" src="https://github.com/cilium/cilium/assets/3320547/7d66f648-cf9d-4598-ba46-c89a85d768bb">
<img width="1441" alt="Screenshot 2023-09-16 at 23 25 05" src="https://github.com/cilium/cilium/assets/3320547/5bb70cf1-fb09-48dd-8dec-2e4c85db2e65">
### Notes
- In the first image, record list on the right is a dump of conntrack table records. It shows an incoming traffic from IP 60.10.150.32, while on the left window wireshark tcpdump shows a replying packet to the same remote address, however the source IP was an overlay network IP
- In the second image, the overlay network IP was confirmed to be pod IP of envoy ingress controller.
- Most of time, I'm only seeing traffic flow correctly using the underlying EC2 node's IP (10.235.87.40)
- For egress traffic with internal pod IP as source, seems like all of them are RST/FIN packets

We've just started to adopt Cilium for our cluster and still new to this technology, so not sure if this is something that we can adjust in cilium config. But this inconsistency of egress source IP pattern looks pretty concerning as a possible bug.

### Cilium Version

1.12.0

### Kernel Version

5.10.184-175.749.amzn2.x86_64

### Kubernetes Version

1.25

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Hi there, thanks for the bug report.

Two questions:
1. v1.12.0 is quite old; we're up to v1.12.14. If you're still running .0, please upgrade.
2. Could you attach a sysdump from an affected node to the issue?

It is possible that there is ICMP traffic that contains the original source IP, which may be displayed differently in `tcpdump`. I'm not sure if that's the case here, however. Either way, AWS does not generally allow nodes to originate traffic with a "wrong" source IP. Anything written on the wire with the wrong source is generally dropped at the VPC layer. So, if it seems like the packets in question are being received, it could be rather a tcpdump / wireshark quirk. 

Can you share your configuration, especially around masquerading?
