### ISSUE TITLE
Mutual Authentication does not take effect

### ISSUE THREAD

**Issue by 123liuziming** [cilium/cilium#28476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have deployed cilium in aliyun ack according to [doc](https://docs.cilium.io/en/stable/installation/k8s-install-helm/#k8s-install-helm). And I 've tried Mutual Authentication according to [Mutual Authentication(Beta)](https://docs.cilium.io/en/latest/network/servicemesh/mutual-authentication/mutual-authentication-example/) and [Mutual Authentication Example](https://docs.cilium.io/en/latest/network/servicemesh/mutual-authentication/mutual-authentication-example/). Everything goes well, but the last step was not as expected:

```
kubectl -n kube-system -c cilium-agent logs cilium-h4wvc --timestamps=true | grep "Policy is requiring authentication\|Validating Server SNI\|Validated certificate\|Successfully authenticated"
```

There is no such log about authentication or certificate

### Cilium Version

cilium-cli: v0.15.10 compiled with go1.21.2 on darwin/amd64
cilium image (default): v1.14.2

### Kernel Version

Alibaba Cloud Linux (Aliyun Linux) 2.1903 LTS (Hunting Beagle)
Kernel 4.19.91-27.4.a17.x86_64 on an x86_64

### Kubernetes Version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.3-aliyun.1", GitCommit:"937f53855a22139bea7b64c0cfbd04aef3c20717", GitTreeState:"clean", BuildDate:"2023-09-05T03:51:24Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.26) exceeds the supported minor version skew of +/-1

### Sysdump

[cilium-sysdump-20231010-143947.zip](https://github.com/cilium/cilium/files/12853649/cilium-sysdump-20231010-143947.zip)

### Relevant log output

```shell
Cilium daemonset full log:

https://static-demo-1.oss-cn-hangzhou.aliyuncs.com/cilium.log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
In the above log, I can see the below line, is it what you are expecting ? 

```
level=debug msg="Successfully authenticated" key="localIdentity=18399, remoteIdentity=57986, remoteNodeID=34363, authType=spire" remote_node_ip=10.0.0.57 subsys=auth
```

**Comment by 123liuziming** [comment]
Yeah, I can find these log in kubectl now. Thanks for your reply, I will close the issue first.
