### ISSUE TITLE
Enabling wireguard causes network failures

### ISSUE THREAD

**Issue by roarvroom** [cilium/cilium#28470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# Bug description:

Installing default Cilium Helm chart on EKS fails to work with Wireguard encryption enabled

# Steps to reproduce:

* vanilla EKS, K8S 1.27
* remove ds aws-node
* install cilium: helm upgrade --install cilium cilium/cilium --version 1.14.2   --namespace kube-system
* deploy 2 (ubuntu) pods, run iperf between them; works as expected
* remov cilium: helm uninstall cilium -n kube-system
* install cilium with wireguard: helm upgrade --install cilium cilium/cilium --version 1.14.2   --namespace kube-system --set encryption.enabled=true --set encryption.type=wireguard
* deploy 2 ubuntu pods
* iperf now failing like this
```
root@ubuntu-pod-2:/# iperf -c 10.0.0.13 -t 60
------------------------------------------------------------
Client connecting to 10.0.0.13, TCP port 5001
TCP window size:  325 KByte (default)
------------------------------------------------------------
[  3] local 10.0.2.92 port 42254 connected with 10.0.0.13 port 5001
write failed: Connection reset by peer
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0- 0.0 sec   322 KBytes   148 Mbits/sec
```

### Cilium Version

cilium-cli: v0.15.7 compiled with go1.21.0 on darwin/arm64
cilium image (default): v1.14.1
cilium image (stable): v1.14.2
cilium image (running): 1.14.2

### Kernel Version

Linux ip-100-64-250-99.eu-central-1.compute.internal 5.10.184-175.749.amzn2.x86_64 #1 SMP Wed Jul 12 18:40:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:21Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20231009-153435.zip](https://github.com/cilium/cilium/files/12846746/cilium-sysdump-20231009-153435.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Hi there,
Have you worked through the [wireguard troubleshooting steps](https://docs.cilium.io/en/v1.14/security/network/encryption-wireguard/#troubleshooting)? What happens if you download the cilium-cli and execute `cilium connectivity test`?
