### ISSUE TITLE
A Performance issue with calling __sync_fetch_and_add().

### ISSUE THREAD

**Issue by LeiW000** [cilium/cilium#28487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We call  __sync_fetch_and_add() for network traffic data in __ct_lookup() and __account_and_check(). But, It looks like it consumes lots of CPU time.

I run [kubenetbench](https://github.com/isovalent/kubenetbench) and the following is what I saw with perf. It took 2.13% CPU time on bpf_prog_*_handle_policy. I annotated it and found that most of CPU time was spent on  __sync_fetch_and_add() .
![image](https://github.com/cilium/cilium/assets/51774176/0f129f85-800c-4ce6-afdc-404f7aa57ce9)

![image](https://github.com/cilium/cilium/assets/51774176/fbcd799f-2cab-401a-a471-78519cc5f8a1)
![image](https://github.com/cilium/cilium/assets/51774176/d8f94a43-87f3-4777-be1a-1438fe4c8ee5)

I saw the comment below. Is it a known issue? If yes, is there any plan to fix it?
https://github.com/cilium/cilium/blob/9dcc5d15207bf9aa431805db19a7de02129a3f9e/bpf/lib/conntrack.h#L285

### Cilium Version

1.14.2

### Kernel Version

5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

 v1.28.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by learnitall** [comment]
Hey @LeiW000, thanks for bringing this up. There are two main places where `__sync_fetch_and_add` is used:

* Conntrack table metrics, to track the number of packets and bytes in a flow (which you linked to).
* Policymap metrics, to track the number of packets and bytes a policy has been applied to (see https://github.com/cilium/cilium/blob/main/bpf/lib/policy.h#L18).

There are two main solutions that can be used to help ease the performance impact of `__sync_fetch_and_add` in these cases:

1. Put these metrics behind a configuration option, which gives users the ability to either enable to disable them.
2. Calculate these metrics using a per-CPU map, to avoid the need for `__sync_fetch_and_add`.

Conntrack metrics are already able to be toggled, (see the macro usage at https://github.com/cilium/cilium/blob/main/bpf/lib/conntrack.h#L284), and
the PR https://github.com/cilium/cilium/pull/27527 will disable them by default.

As for the policymap, there are two suggestions for a PR:

1. Apply the same pattern used by conntrack to put policymap metrics behind an option and add a note in the [performance tuning guide](https://github.com/cilium/cilium/blob/main/Documentation/operations/performance/tuning.rst) describing how this option can be disabled to save on CPU. Unlike the conntrack metrics, this option would need to be enabled by default.
2. Migrate the policymap metrics to use a per-CPU map.

**Comment by LeiW000** [comment]
@learnitall, thanks for your comment. Just saw it. I don't know why I did not get the notification for your comment.

For the policymap, I will see if I can file a PR.

**Comment by Jack-R-lantern** [comment]
@LeiW000 @learnitall 
Can I work on this issue?

**Comment by LeiW000** [comment]
@Jack-R-lantern, Yes if you are interested. For the policymap. I agree with @learnitall. We need to implement Learnitall's suggestion both 1) and 2).

By the way, please let me know after you file the PR.

**Comment by learnitall** [comment]
Thank you @Jack-R-lantern! To clarify, we only need to start with either 1) or 2), unless I'm missing something @LeiW000, and then feel free to correct me. It would make sense to pick one out and start there, and then we can continue to work on this if needed afterward. The reasoning is that the first option allows users to opt out of the expensive operations as needed, while the second option removes the expensive operations altogether. In the context of this issue, it wouldn't be as useful for users to be able to opt out of inexpensive operations by implementing both solutions together.

Number two is definitely my preferred solution, but it would be more time-consuming and difficult compared to option one. Up to you on which solution you choose to go with @Jack-R-lantern  :)

**Comment by Jack-R-lantern** [comment]
@learnitall 
I checked the first option and there is no macro like CONTRACK_ACCOUNT, am I correct?
If that macro doesn't exist, we'll implement it in the second option.

**Comment by LeiW000** [comment]
It is OK to go ahead with 1) first. But, the 2) is very reasonable, too. From my perspective, it would be great if it could be implemented as well. 

By the way, @Jack-R-lantern , thank you for working on it.

**Comment by learnitall** [comment]
@Jack-R-lantern it's definitely okay to ask questions about implementation difficulties, please feel free! And you're correct, there currently isn't a macro like CONTRACK_ACCOUNT for policymap.

**Comment by Jack-R-lantern** [comment]
@learnitall 
Based on this [review](https://github.com/cilium/cilium/pull/28749#pullrequestreview-1702115610), I'm going to start with approach #1.

**Comment by learnitall** [comment]
Sounds good!

**Comment by cmergenthaler** [comment]
Are there any plans on improving the performance of CT or Policymap metrics? We'd be really interested in the CT metrics but want to avoid performance impact due to it.
