### ISSUE TITLE
CFP:  Support multiple XDP programs for cilium 

### ISSUE THREAD

**Issue by wenlxie** [cilium/cilium#28509]
## Cilium Feature Proposal
When runs cilium in XDP mode, there are some requirements that we want to run multiple XDP programs along with Cilium.
For example:
1) We may want to capture the pacekts by  Geneve VNI or IPIP innner IP,  but `hubble record` feature is not powerful enough, it only supports filter packets by 5 tuples. 
2) User want to have some customized metrics for packets ,  but not want to change the cilium codes since there are maintain effort
3)  DDoS protect xdp programs runs before cilium XDP

So  this proposal is for Cilium that can supported an easy way to integrate with other XDP programs.

**Comment by borkmann** [comment]
(For some more details, see https://netdev.bots.linux.dev/netconf/2023/index.html wrt 'bpf_mprog for XDP' in the slides and notes.)

**Comment by oblazek** [comment]
It's not the best, but we are doing our own tail calls, so slightly modifying cilium code base, but keeping our code outside of cilium.

**Comment by wenlxie** [comment]
> It's not the best, but we are doing our own tail calls, so slightly modifying cilium code base, but keeping our code outside of cilium.

@oblazek 
Could you share more? 
For my case, tailcall has some limitations. 
I need to add tailcall before return in all the xdp programs, so need to change many places of the cilium codes.

**Comment by oblazek** [comment]
> @oblazek Could you share more? For my case, tailcall has some limitations. I need to add tailcall before return in all the xdp programs, so need to change many places of the cilium codes.

Hmm there are not many bpf programs that cilium has imo. But we are doing our own logic on the ingress part, so doing a tail call for example here: https://github.com/cilium/cilium/blob/main/bpf/bpf_xdp.c#L205 if that fails to find it - the packet is not dropped and is handled by the next one `ep_tail_call(ctx, CILIUM_CALL_IPV4_FROM_NETDEV);`
