### ISSUE TITLE
CFP: Add missing Kubernetes liveness and readiness probes to `node-init` container of `cilium-node-init` DaemonSet

### ISSUE THREAD

**Issue by chirangaalwis** [cilium/cilium#28553]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

If so, please describe the problem

**Describe the feature you'd like**
$subject needs to be introduced to the cilium workload Helm chart based on the following violations
- [CKV_K8S_8](https://docs.bridgecrew.io/docs/bc_k8s_7)
- [CKV_K8S_9](https://docs.bridgecrew.io/docs/bc_k8s_8)

**Comment by squeed** [comment]
Liveness and readiness probes are not interesting for nodeinit; it is a "one-shot" container where the exit status is all that matters.
