### ISSUE TITLE
CI: resource package test triggers panic: channel full

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#28575]
Encountered on PR https://github.com/cilium/cilium/pull/28503 in privileged test run, seems unrelated:

https://github.com/cilium/cilium/actions/runs/6499290523/job/17652405533

```
panic: channel full

goroutine 65 [running]:
k8s.io/apimachinery/pkg/watch.(*RaceFreeFakeWatcher).Add(0xc00082a2c0?, {0x24569a8?, 0xc00082a580?})
	/host/vendor/k8s.io/apimachinery/pkg/watch/watch.go:218 +0x13e
k8s.io/client-go/testing.(*tracker).add(0xc000026370, {{0x0, 0x0}, {0x214df70, 0x2}, {0x214eee0, 0x5}}, {0x24569a8, 0xc00082a000}, {0x0, ...}, ...)
	/host/vendor/k8s.io/client-go/testing/fixture.go:431 +0xba5
k8s.io/client-go/testing.(*tracker).Create(0xc000687f30?, {{0x0, 0x0}, {0x214df70, 0x2}, {0x214eee0, 0x5}}, {0x24569a8?, 0xc00082a000?}, {0x0, ...})
	/host/vendor/k8s.io/client-go/testing/fixture.go:356 +0x7b
github.com/cilium/cilium/pkg/k8s/resource_test.TestResource_RepeatedDelete.func3()
	/host/pkg/k8s/resource/resource_test.go:301 +0x9f
created by github.com/cilium/cilium/pkg/k8s/resource_test.TestResource_RepeatedDelete in goroutine 25
	/host/pkg/k8s/resource/resource_test.go:297 +0x590
FAIL	github.com/cilium/cilium/pkg/k8s/resource	0.254s
```

**Comment by margamanterola** [comment]
@joamaki This seems to come from code that you recently added. 
https://github.com/cilium/cilium/blob/854353b1e827349163801d185a82678c12da8440/pkg/k8s/resource/resource_test.go#L295-L296

Could it be that the "unreliable" processing the events, is unreliable enough that it causes the channel to fill?

If I'm reading the code correctly, then the channel has space for up to 100 events:
https://github.com/cilium/cilium/blob/854353b1e827349163801d185a82678c12da8440/vendor/k8s.io/apimachinery/pkg/watch/watch.go#L52

And out of the 1000 inserts and 1000 deletes, 33% of deletes are supposed to fail and get retried. I don't completely follow how this leads to the channel getting filled only some of the runs, but it does sound like the randomness can sometimes cause this.

**Comment by joamaki** [comment]
Oh wow, didn’t realize the fake client had these sorts of sanity checks built in. I wrote this with the assumption that it would be fine pushing as much in via the fake client as I liked. 


Given this limitation I’ll restructure the test a bit to avoid filling the fake client’s watch channel. Or even just bypass the fake client entirely by using a hand-rolled ListerWatcher to have more control.

**Comment by joamaki** [comment]
Hand-rolled ListerWatcher seemed like the most straightforward way to have better control in the test: https://github.com/cilium/cilium/pull/28588.
