### ISSUE TITLE
CFP: `cilium config` clarifies the scope of influence of parameter modifications

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#28580]
In an already online environment, I want to dynamically modify the cilium config, but I want to know the scope of the modification. For example, will it affect the existing long connections and will there be flash interruptions? For example, I want to adjust the debug parameters, but I am not sure whether it will affect it?

Will executing `cilium config debug=true` affect the network of already running pods? Some businesses are in tcp long connection mode

**Comment by squeed** [comment]
Changing settings via `cilium config` should not cause any in-progress connections to be dropped. In fact, Cilium is designed such that restarting the agent should not affect pod networking - including existing and new connections during agent restart.
