### ISSUE TITLE
problem in clustermesh 

### ISSUE THREAD

**Issue by Jaideep1997** [cilium/cilium#28592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i have two AWS EKS cluster  in the same VPC and same SUBNET i wanted to create clustermesh between them but it is failing again and again why??here are my command which i am using cilium install --set cluster.id=1 --set cluster.name=kind-az1 --wait
cilium clustermesh enable --service-type LoadBalancer
sleep 10
CRT=$(kubectl get secret cilium-ca -n kube-system -o yaml | yq .data.\"ca.crt\" -r)sllep 10

KEY=$(kubectl get secret cilium-ca -n kube-system -o yaml | yq .data.\"ca.key\" -r)
cilium install --set cluster.id=2 --set cluster.name=kind-az2 --helm-set tls.ca.cert="$CRT" --helm-set tls.ca.key="$KEY" --wait
cilium clustermesh enable --service-type LoadBalancer
sllep 10
kubectl config use-context kind-az1
cilium clustermesh connect --context kind-az1 --destination-context kind-az2  but  it is giving me this erroe why
![Screenshot from 2023-10-13 18-50-41](https://github.com/cilium/cilium/assets/50451066/d6d1c945-bc70-4d77-8b8b-6e75b13a6fb0)
![Screenshot from 2023-10-13 19-36-38](https://github.com/cilium/cilium/assets/50451066/77298c53-c472-46a7-b72c-39029e524076)
![Screenshot from 2023-10-13 18-50-41](https://github.com/cilium/cilium/assets/50451066/53191453-c5a8-410a-9177-1f71dcc40ee9)

### Cilium Version

cilium version 1.14.2

### Kernel Version

Linux cbnits198-HP-Pavilion-Gaming-Laptop 5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Kustomize Version: v4.5.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jaideep1997** [comment]
please help

**Comment by joestringer** [comment]
Hi, are you sure that both clusters have properly enabled clustermesh? The [official guide](https://docs.cilium.io/en/stable/network/clustermesh/clustermesh/#clustermesh) provides commands to use `--context` with the `cilium clustermesh enable` command, but I don't see that in your output.
