### ISSUE TITLE
Replace gocheck with standard Go testing

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#28596]
Standard go testing framework is better understood by tooling and doesn't need special invocations in order to run the test logic. Should we try to switch all current usage of gocheck over to standard Go testing framework?

**Comment by joestringer** [comment]
According to commit 652e271b396116 we already decided to migrate away, we just didn't have an issue or plan for this.

**Comment by sayboras** [comment]
I was updating some of the tests as part of last year  quiet period,  probably it is good  for a first cut.

**Comment by sayboras** [comment]
All the linked PRs are merged, the current main branch no longer use gocheck or cilium/checkmate libraries, closing this issue.

**Comment by tklauser** [comment]
Awesome work @sayboras!
