### ISSUE TITLE
Helm chart: impossible to set tolerations for spire-agent

### ISSUE THREAD

**Issue by rauanmayemir** [cilium/cilium#28600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`spire-agent` daemonSet does not have a way to set `tolerations` which effectively breaks the cluster, because it _at least_ needs to set control plane tolerations, otherwise `cilium-agent` won't be able to start on master nodes.

### Cilium Version

1.14.2

### Kernel Version

-

### Kubernetes Version

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
:wave: 

I have added backport label for the below PR, it should be available in the next release.

https://github.com/cilium/cilium/pull/27229
