### ISSUE TITLE
CI: Conformance AWS-CNI: echo-ingress/pod-to-pod: failed with unexpected exit code: Timeout occurred (expected 28, found -2)

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#28628]
## CI failure

Hit on https://github.com/cilium/cilium/pull/28603: https://github.com/cilium/cilium/actions/runs/6531628118/job/17733222702#step:18:94

The unusual part with this failure is `failed with unexpected exit code: Timeout occurred (expected 28, found -2)`.

What is CLI doing to generate an error like this? How does the error `-2` get returned when curl typically returns positive error codes? Why `Timeout occurred`?

```
[=] Test [echo-ingress]
...
  ℹ️  📜 Applying CiliumNetworkPolicy 'echo-ingress-from-other-client' to namespace 'cilium-test'..
  [-] Scenario [echo-ingress/pod-to-pod]
  [.] Action [echo-ingress/pod-to-pod/curl-ipv4-0: cilium-test/client2-646b88fb9b-s4ghw (192.168.157.58) -> cilium-test/echo-other-node-6f988f[86](https://github.com/cilium/cilium/actions/runs/6531628118/job/17733222702#step:18:87)97-mmg44 (192.168.119.237:8080)]
  [.] Action [echo-ingress/pod-to-pod/curl-ipv4-1: cilium-test/client2-646b[88](https://github.com/cilium/cilium/actions/runs/6531628118/job/17733222702#step:18:89)fb9b-s4ghw (192.168.157.58) -> cilium-test/echo-same-node-695c975475-cm62k (192.168.134.114:8080)]
  [.] Action [echo-ingress/pod-to-pod/curl-ipv4-2: cilium-test/client-6b4b857d98-bsmzs (192.168.130.143) -> cilium-test/echo-other-node-6f988f8697-mmg44 (192.168.119.237:8080)]
  ℹ️  unable to extract exit code from error: Timeout occurred
93
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://1[92](https://github.com/cilium/cilium/actions/runs/6531628118/job/17733222702#step:18:93).168.119.237:8080" failed with unexpected exit code: Timeout occurred (expected 28, found -2)
  📄 No flows recorded for peer cilium-test/client-6b4b857d98-bsmzs during action curl-ipv4-2
  📄 No flows recorded for peer cilium-test/echo-other-node-6f988f8697-mmg44 during action curl-ipv4-2
```

**Comment by tommyp1ckles** [comment]
> What is CLI doing to generate an error like this? How does the error -2 get returned when curl typically returns positive error codes? Why Timeout occurred?

It seems like we return -2 by default when we fail to parse out the return code from the stdout of kubectl exec:

https://github.com/cilium/cilium-cli/blob/951eb9108277f4ffeb86d047bd492b6b96a52542/connectivity/check/action.go#L339

Timeout seems like what we're expecting in this case, question is why the exit status scrape fails...

**Comment by tommyp1ckles** [comment]
However ` Timeout occurred` doesn't seem like the timeout error message I'm used to seeing from curl

**Comment by tommyp1ckles** [comment]
I do see a Pod (not the one the failure is happening on) pending after 11 minutes: ```cilium-test   echo-external-node-545d98c9b4-jlqs4   0/1     Pending   0          11m   <none>            <none> ```

I'm thinking this might be related to slow Pod creation times?

**Comment by tommyp1ckles** [comment]
Other conn test issues such as:

https://github.com/cilium/cilium/issues/28625
https://github.com/cilium/cilium/issues/28627

Seem like they might be same underlying cause - only difference is this one produces a more confusing error because of the expected curl timeout (i.e. code 28).

**Comment by tommyp1ckles** [comment]
@joestringer Looks like the sysdumps got cleared out due to rerun, did you manage to save a copy of that?

**Comment by joestringer** [comment]
That's pretty neat though, it sounds like even if the failure is a timeout, the CLI checks the exit code to double-check that the failure is the same as what was expected. The idea that Pods are still pending and not getting bootstrapped could be a useful insight to keep an eye out for issues like this in future.

**Comment by glrf** [comment]
Just hit the same error in https://github.com/cilium/cilium/actions/runs/6826316333/job/18565993216 and saved the sysdump. There was a pending pod, but it seems like a red herring, as it wasn't the pod executing the test. 
[cilium-sysdumps.zip](https://github.com/cilium/cilium/files/13321294/cilium-sysdumps.zip)
