### ISSUE TITLE
Default IPv6 prefix allocated from reserved address space

### ISSUE THREAD

**Issue by azenk** [cilium/cilium#2862]
As far as I'm able to determine, the default IPv6 cluster prefix of f00d::/48 is part of a [reserved block of addresses](https://www.iana.org/assignments/ipv6-address-space/ipv6-address-space.xhtml).  Wouldn't a ula prefix be more appropriate as a default?  Perhaps either a fixed fdxx prefix or one generated at cluster build time?

**Comment by tgraf** [comment]
@azenk Agreed. We picked one that a user needs to change as everyone should really be using their own prefixes as addresses are free.
