### ISSUE TITLE
When I use Cilium Network，Use Minio to upload file often occure failed

### ISSUE THREAD

**Issue by albenfan** [cilium/cilium#28639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. my minio svc info like this：
![image](https://github.com/cilium/cilium/assets/53927188/2b09d81d-67a2-48bf-9e2e-e4ba928c3f31)
2.when i upload file use minio web server by  172.16.107.175:30027，the node which minio pod exists， it succeed
3.when i uplaod file use minio web server by  ${OtherNodeIp}:30027, it failed, like this
![image](https://github.com/cilium/cilium/assets/53927188/a41a432c-263a-4b91-b541-3c7a9c27a1bd)
4. can you tell me how to solve this problem
5. cilium netwotk status is like this
![image](https://github.com/cilium/cilium/assets/53927188/828fafd8-1a6b-46af-8a3d-53e813a91382)

### Cilium Version

![image](https://github.com/cilium/cilium/assets/53927188/668b4d18-acd4-4515-9aa3-42f996540ab1)

### Kernel Version

Linux master1 5.13.12-1.el7.elrepo.x86_64 #1 SMP Tue Aug 17 10:49:05 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:57:43Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi, I'm afraid there isn't enough information to pinpoint the problem. You'll need to dig a bit deeper. Some suggestions: [Install and use Hubble](https://docs.cilium.io/en/stable/overview/intro/#intro) to introspect what is happening to the traffic on the wire for the Pods that experience connectivity issues.

Cilium 1.11.x is also end of life for some time now, the latest is v1.14.3. It's quite possible that the bug has been resolved in a newer version, so I'd suggest attempting to upgrade before further investigation.
