### ISSUE TITLE
Kubernetes pods not getting IP assigned from podCIDR

### ISSUE THREAD

**Issue by d3bt3ch** [cilium/cilium#28650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are using cilium `ipam` mode `crd` on `kOps` cluster on `AWS`. After successful setup of the kubernetes some pods are getting IP assigned same to the `IP` of the host machine which is from the aws subnet ip pool and some pods are getting `IP` assigned based on the podCIDR mentioned in the `kOps` configuration. Need some configuration clarification on the same. 

### Cilium Version

1.13.5

### Kernel Version

6

### Kubernetes Version

1.28.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
That shouldn't happen. Is there a chance that pods are getting started with a different CNI plugin?

**Comment by squeed** [comment]
The easiest way to determine this is to see if there are pods without a CiliumEndpoint k8s resource. The `cilium status` command should tell you.

You can also see if there are multiple files in `/etc/cni/net.d` on the host.
