### ISSUE TITLE
[arm64] BGP Control Plane + Native Routing + LB-IPAM results in BPF program too large error (1.15-dev)

### ISSUE THREAD

**Issue by samip5** [cilium/cilium#28651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In this environment, Cilium decided that the BPF program is too large so it's rather unhappy as result.

### Cilium Version

cilium-cli: v0.12.1 compiled with go1.18.5 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.14.2
cilium image (running): -ci:0a28eb945e98a4729f5b580a28b5e346def975db

### Kernel Version

6.1.0-12-arm64
6.1.0-9-arm64

### Kubernetes Version
```json
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.6",
    "gitCommit": "741c8db18a52787d734cbe4795f0b4ad860906d6",
    "gitTreeState": "archive",
    "buildDate": "2023-10-03T16:31:42Z",
    "goVersion": "go1.21.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1",
  "serverVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.4+k3s1",
    "gitCommit": "36645e7311e9bdbbf2adb79ecd8bd68556bc86f6",
    "gitTreeState": "clean",
    "buildDate": "2023-07-28T09:46:05Z",
    "goVersion": "go1.20.6",
    "compiler": "gc",
    "platform": "linux/arm64"
  }
}
```

### Sysdump

The whole sysdump of my dev cluster (too large for GH): https://s3.skym.fi/public/cilium-sysdump-20231007-213830.zip

### Relevant log output

```shell
Verifier error: program tail_handle_snat_fwd_ipv6: load program: argument list too long: BPF program is too large. Processed 1000001 insn (2234 line(s) omitted)
```

### Anything else?

Current helm values are available here: https://github.com/samip5/k3s-dev-cluster/blob/fde716e03d35bb617b68843bd50ea11fdda7eb5f/kubernetes/apps/kube-system/cilium/app/helmrelease.yaml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hello, thanks for the report. Do you experience this behaviour with any stable versions of Cilium such as v1.14.3? Would you be willing to bisect the issue if not? It would help a lot to understand which changes may have introduced the issue.

**Comment by samip5** [comment]
> Hello, thanks for the report. Do you experience this behaviour with any stable versions of Cilium such as v1.14.3? Would you be willing to bisect the issue if not? It would help a lot to understand which changes may have introduced the issue.

The problems with IPv6 still keep me on 1.13.6. I have only seen it with the 1.15-dev version to my knowledge.
