### ISSUE TITLE
Docs: No Installation on AWS EKS page post 1.9

### ISSUE THREAD

**Issue by sudhakartag1** [cilium/cilium#28662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-eks/ says:
"Warning

You are not reading the most up to date version of this documentation. [v1.14](https://docs.cilium.io/en/v1.14/gettingstarted/k8s-install-eks/) is the newest version."

Navigating to https://docs.cilium.io/en/v1.14/gettingstarted/k8s-install-eks/ results in 
"404 Not Found
You are browsing the documentation of cilium. The documentation page you are looking for was not found.

Documentation changes over time and pages are moved around. You can try to navigate to [the index page](https://docs.cilium.io/) of the project and use its navigation, or search for a similar page."

### Cilium Version

1.14

### Kernel Version

n/a

### Kubernetes Version

1.24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report. Please see https://docs.cilium.io/en/v1.14/gettingstarted/k8s-install-default/ .
