### ISSUE TITLE
Cilium connectivity test failure

### ISSUE THREAD

**Issue by wisdomdevil** [cilium/cilium#28672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Good afternoon, I just installed a new cilium instance using:

    cilium install \
      --helm-set=ipam.mode=kubernetes.
      --helm-set=kubeProxyReplacement=strict.
      --helm-set=ipv4NativeRoutingCIDR=172.16.0.0/12 \
      --helm-set=k8sServiceHost=my-api-server.
      --helm-set=k8sServicePort=6443

After that, I ran

cillium connectivity test and I get error [=] Test [no-policies]
.
  [-] Scenario [no-policies/pod-to-external-workload].
  [-] Scenario [no-policies/pod-to-cidr].
  [.] Action [no-policies/pod-to-cidr/external-1111-0: cilium-test/client2-59b578d4bb-gm4sp (172.16.5.244) -> external-1111 (1.1.1.1.1:443)]
  ❌ The command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 --retry 3 --retry-all-errors --retry-delay 3 https://1.1.1.1:443" failed: command terminated with exit code 35

I get similar errors for all external requests. 

I noticed that inside the client and client2 test feeds dns-resolve is not working

This seems to be a problem with alpine musl :

If I ping one.one.one.one.one - I get a timeout
And if one.one.one.one.one. (added a dot), everything pings fine.

Inside the other pods I deploy, everything works as expected. 

Screenshots of trouble 

![image](https://github.com/cilium/cilium/assets/74432905/50e42085-5d49-4d4c-ba62-6d53a4c15135)

with added dot

![image](https://github.com/cilium/cilium/assets/74432905/c41788b0-d5df-47cd-b228-7c6e5483511a)

![image](https://github.com/cilium/cilium/assets/74432905/710faf74-cee1-4bf5-bc6c-bcc02baec2dc)

### Cilium Version

1.14.2

### Kernel Version

Linux master-1 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Oh, interesting. We totally should add that trailing dot; it doesn't hurt anything.

**Comment by chaunceyjiang** [comment]
Hi @squeed I don't understand where this issue should be fixed? It seems like it should be in the cilium-cli repository, right?

**Comment by squeed** [comment]
@chaunceyjiang exactly right, just the default "external target" argument.

A bit funny that alpine+musl doesn't add it :shrug:

**Comment by nickolaev** [comment]
Is it related to https://github.com/cilium/cilium-cli/issues/1243

**Comment by fgiloux** [comment]
I guess it has been addressed by [this commit](https://github.com/cilium/cilium/commit/047fa1d59f3d6d69354993363c5e783642650591).

**Comment by nickolaev** [comment]
@giorio94 as an author of the commit referred by @fgiloux do you feel it also closes this one?

**Comment by giorio94** [comment]
Yep, thanks for the ping. Closing.
