### ISSUE TITLE
L7 DNS policy does not work with IPv6 DNS server

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#28678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When creating a L7 DNS policy (i.e. `toPorts[].rules.dns`)), that policy allows traffic to IPv4 DNS servers, but not IPv6 DNS servers.

Reproduction steps:

Setup:
```console
$ helm upgrade --install cilium ./install/kubernetes/cilium 
   --namespace kube-system \
   --set debug.enabled=true \
   --set hubble.relay.enabled=true \
   --set ipv6.enabled=true \
   --set operator.replicas=1
$ cilium connectivity test
...
✅ All 42 tests (501 actions) successful, 14 tests skipped, 1 scenarios skipped.
$ kubectl -n cilium-test get cep
NAME                              ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4         IPV6
client-84bfddc76b-5sr8l           948           21399         <status disabled>     <status disabled>    <status disabled>   ready            10.0.1.48    fd00::1fc
client2-764b565764-s8b6q          672           20378         <status disabled>     <status disabled>    <status disabled>   ready            10.0.1.138   fd00::181
echo-other-node-bdf865497-pq7ch   1478          14746         <status disabled>     <status disabled>    <status disabled>   ready            10.0.2.109   fd00::222
echo-same-node-58bfcdb7f5-vpbt7   2777          27145         <status disabled>     <status disabled>    <status disabled>   ready            10.0.1.144   fd00::1e9
```

Note that the two `echo` pods set up by the Cilium CLI host a coredns server that allows us to look up `localhost`. Without any network policy, this works with both IPv4 and IPv6.

```console
$ kubectl -n cilium-test exec client-84bfddc76b-5sr8l -- nslookup localhost 10.0.2.109
Server:		10.0.2.109
Address:	10.0.2.109#53

Non-authoritative answer:
Name:	localhost.cilium-test.svc.cluster.local
Address: 127.0.0.1
Name:	localhost.cilium-test.svc.cluster.local
Address: ::1
$ kubectl -n cilium-testexec client-84bfddc76b-5sr8l -- nslookup localhost fd00::222 
Server:		fd00::222
Address:	fd00::222#53

Non-authoritative answer:
Name:	localhost.cilium-test.svc.cluster.local
Address: 127.0.0.1
Name:	localhost.cilium-test.svc.cluster.local
Address: ::1
```

However, as soon as I apply a L7 DNS policy on that pod, IPv6 lookups stop working (IPv4 is fine):
```console
$ kubectl -n cilium-test apply -f - <<EOF                                       
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: dns-via-proxy-for-client
spec:
  endpointSelector:
    matchLabels:
      kind: client
  egress:
    - toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
      toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: cilium-test
            kind: echo
EOF
$ kubectl -n cilium-test exec client-84bfddc76b-5sr8l -- nslookup localhost 10.0.2.109
Server:		10.0.2.109
Address:	10.0.2.109#53

Non-authoritative answer:
Name:	localhost.cilium-test.svc.cluster.local
Address: 127.0.0.1
Name:	localhost.cilium-test.svc.cluster.local
Address: ::1
$ kubectl -n cilium-test exec client-84bfddc76b-5sr8l -- nslookup localhost fd00::222
;; communications error to fd00::222#53: timed out
;; communications error to fd00::222#53: timed out
;; communications error to fd00::222#53: timed out
;; no servers could be reached

command terminated with exit code 1
```

Just using `toPorts` (without any DNS rule) behaves the same a no policy. It only stops working for IPv6 if I add the `dns` rule. 

### Cilium Version

Cilium 1.15.0-dev aa10d940 2023-10-17T23:18:44+07:00 go version go1.21.3 linux/amd64 (i.e. current `main`)

I've also been able to reproduce this with Cilium v1.13.7.

### Kernel Version

6.5.7-arch1-1

### Kubernetes Version

v1.25.3 (used our kind.sh script to set up a dual-stack cluster)

### Sysdump

[cilium-sysdump-20231018-150416.zip](https://github.com/cilium/cilium/files/13025363/cilium-sysdump-20231018-150416.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
Hubble does not show any drops (I used echo-same-node here to avoid issues with events being shown out of order), and the packet is forwarded to the proxy. It seems that the response is somehow not properly delivered:

```console
$ hubble observe -f --protocol udp
Oct 18 13:19:43.775: cilium-test/client-84bfddc76b-5sr8l:45346 (ID:21399) -> cilium-test/echo-same-node-58bfcdb7f5-vpbt7:53 (ID:27145) policy-verdict:L3-L4 EGRESS ALLOWED (UDP)
Oct 18 13:19:43.775: cilium-test/client-84bfddc76b-5sr8l:45346 (ID:21399) -> cilium-test/echo-same-node-58bfcdb7f5-vpbt7:53 (ID:27145) to-proxy FORWARDED (UDP)
Oct 18 13:19:43.775: cilium-test/client-84bfddc76b-5sr8l:45346 (ID:21399) -> :53 (ID:27145) dns-request proxy FORWARDED (DNS Query localhost.cilium-test.svc.cluster.local. A)
Oct 18 13:19:43.776: [fd00::123]:43803 (ID:21399) -> cilium-test/echo-same-node-58bfcdb7f5-vpbt7:53 (ID:27145) to-endpoint FORWARDED (UDP)
Oct 18 13:19:43.777: [fd00::123]:43803 (host) <- cilium-test/echo-same-node-58bfcdb7f5-vpbt7:53 (ID:27145) to-stack FORWARDED (UDP)
Oct 18 13:19:43.778: :45346 (ID:21399) <- :53 (ID:27145) dns-response proxy FORWARDED (DNS Answer "127.0.0.1" TTL: 604800 (Proxy localhost.cilium-test.svc.cluster.local. A))
Oct 18 13:19:43.779: cilium-test/client-84bfddc76b-5sr8l:45346 (ID:21399) <- cilium-test/echo-same-node-58bfcdb7f5-vpbt7:53 (ID:27145) to-endpoint FORWARDED (UDP)
```

**Comment by danehans** [comment]
The DNS proxy is not setting the checksum (defaults to `0`) in the UDP header when writing a response:

![Screenshot 2023-11-21 at 09 38 22](https://github.com/cilium/cilium/assets/1878195/c5f1700d-1015-4018-86fa-c6af644d6ae2)

This is causing IPv6 receivers to discard the response from the DNS proxy. Per [RFC 2460](https://www.ietf.org/rfc/rfc2460.txt), the checksum must be set when originating a UDP packet:
> Unlike IPv4, when UDP packets are originated by an IPv6 node,
    the UDP checksum is not optional.  That is, whenever
    originating a UDP packet, an IPv6 node must compute a UDP
    checksum over the packet and the pseudo-header, and, if that
    computation yields a result of zero, it must be changed to hex
    FFFF for placement in the UDP header.  IPv6 receivers must
    discard UDP packets containing a zero checksum, and should log
    the error.
