### ISSUE TITLE
Cilium not compatible with XDP SYNPROXY  K8S nodeport service protection

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#28681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sorry this issue is not a bug from what I understand, and not important enough to be a CFP I think. I had ported in kernel version of XDP SYNPROXY to xdp-projects bpf-examples repo to run XDP SYNPROXY as DaemonSet to protect each k8s node from SYN flood attack [xdp-synproxy ](https://github.com/vincentmli/bpf-examples/tree/vli-dev/xdp-synproxy), for example to protect k8s nodeport service from SYN flood attack, it works as intended to prevent SYN flood attack.  

the issue is the XDP SYNPROXY  breaks normal nodeport service connection,  when node received the SYN, XDP SYNPROXY responded with SYN+ACK, and client responded with ACK, node send RST to the final ACK because the SYN is not seen by node, tcpdump on the node interface shown below:

```
11:19:12.350335 IP 10.169.72.187.51014 > 10.169.72.239.32506: Flags [.], ack 3913777856, win 502, options [nop,nop,TS val 2837429801 ecr 1092523223], length 0
11:19:12.350538 IP 10.169.72.239.32506 > 10.169.72.187.51014: Flags [R], seq 3913777856, win 0, length 0
```
from what I understand, XDP hooks at driver layer, Cilium datapath mainly works at TC layer, the SYN packet processed by XDP SYNPROXY and Cilium datapath has never seen the SYN. XDP SYNPROXY also works with netfilter SYNPROXY module and netfilter connection tracking, but Cilium datapath mostly bypass netfilter and has its own connection tracking, so it appears to me this is expected result, I could be missing something. I wonder though if there is possibility let Cilium nodeport datapath accommodate this scenario? 

### Cilium Version

cilium-cli: v0.14.0 compiled with go1.20.2 on linux/amd64
cilium image (default): v1.13.2
cilium image (stable): v1.14.2
cilium image (running): v1.13.0

### Kernel Version

Linux cilium-dev 6.6.0-rc2+

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment]
by the way, XDP SYNPROXY works with k8s with flannel CNI fine with nodeport service

**Comment by ninja-** [comment]
that would be nice to have, currently it's hard/impossible to apply any DDoS protections to Cilium in form of iptables rules, with the workaround being using a non-Kubernetes node as a frontend

**Comment by vincentmli** [comment]
@ninja- SYNPROXY is stateful connection so it requires connection tracking, if you just want to rate limit tcp/udp request per IP, if you do not have Cilium XDP program attached to node, you can attach your own XDP program to rate limit request per IP, for example to rate limit DNS request per IP [DNS RRL ](https://github.com/NLnetLabs/XDPeriments/blob/master/RRL/Round3/xdp_rrl.c), and I have ported it here [ libbpf-bootstrap xdppacket](https://github.com/vincentmli/libbpf-bootstrap/blob/dnsrrl/examples/c/xdppacket.bpf.c)
