### ISSUE TITLE
CI: Conformance EKS: echo-ingress-l7-named-port: Timeout occurred

### ISSUE THREAD

**Issue by pippolo84** [cilium/cilium#28693]
## CI failure

Hit on https://github.com/cilium/cilium/pull/28647: https://github.com/cilium/cilium/actions/runs/6564558676/job/17831176427

```
[=] Test [echo-ingress-l7-named-port]

  ℹ️  📜 Applying CiliumNetworkPolicy 'echo-ingress-l7-http-named-port' to namespace 'cilium-test'..
  ℹ️  Cilium agent kube-system/cilium-sstn9 logs since 2023-10-18 18:04:48.207876181 +0000 UTC m=+641.693496947:
...
  ℹ️  📜 Deleting CiliumNetworkPolicy 'echo-ingress-l7-http-named-port' from namespace 'cilium-test'..
  🟥 Running test echo-ingress-l7-named-port: setting up test: applying network policies: policies were not applied on all Cilium nodes in time: Timeout occurred
...
📋 Test Report
❌ 1/45 tests failed (0/276 actions), 11 tests skipped, 1 scenarios skipped:
Test [echo-ingress-l7-named-port]:
Error: Process completed with exit code 1.
```

Logs: [logs_1867421.zip](https://github.com/cilium/cilium/files/13039942/logs_1867421.zip)
Sysdump: [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/13039967/cilium-sysdumps.zip)

**Comment by tommyp1ckles** [comment]
Hit this here: https://github.com/cilium/cilium/actions/runs/6774695309/job/18412385947

**Comment by brb** [comment]
I'm hitting like crazy this in https://github.com/cilium/cilium/pull/29073. Any findings?
