### ISSUE TITLE
[tunnel] add option to compute UDP csum for tunnel packets

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#28707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The udp vxlan package sent by cilium does not have cksum set, and my network equipment will have a NAT scenario. The network equipment cannot sense the cksum all-0 scenario, and will recalculate the cksum after NAT. The incremental calculation method is used, resulting in the calculated cksum. is wrong, and after receiving the packet, the server finds that the cksum is wrong and discards the data packet. Does cilium support calculating the cksum before sending the packet instead of using all zero？

### Cilium Version

1.12.7

### Kernel Version

Linux hcsoemin 5.10.0-60.18.0.50.r966_40.hce2.x86_64 #1 SMP Tue Aug 29 06:17:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.24

### Sysdump

    192.172.28.180.42528 > 172.226.130.13.8472: [no cksum] OTV, flags [I] (0x08), overlay 0, instance 41859
IP (tos 0x0, ttl 64, id 20486, offset 0, flags [DF], proto TCP (6), length 60)
    245.0.1.2.43332 > 245.0.0.13.6443: Flags [S], cksum 0x32d7 (correct), seq 193286423, win 64860, options [mss 1410,sackOK,TS val 2082967994 ecr 0,nop,wscale 7], length 0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
> The network equipment cannot sense the cksum all-0 scenario

:wave: wow :). Have you reported this bug to the HW vendor?

> Does cilium support calculating the cksum before sending the packet instead of using all zero?

No, that's not supported today. Sounds like you might want to adjust `BPF_F_ZERO_CSUM_TX` [here](https://github.com/cilium/cilium/blob/6db3b8f4032587329ccd3b1af3785c845be2cd22/bpf/lib/overloadable_skb.h#L212C50-L212C50), and build your own cilium until your network HW is fixed ?

**Comment by julianwiedmann** [comment]
FWIW, I don't think adding such an option for upstream cilium is a worthwhile enhancement. It would be just one more exotic config option that requires maintenance + test overhead, only to workaround bugs in other components.
