### ISSUE TITLE
Correct documentation about: "Using Kube-Router to Run BGP"

### ISSUE THREAD

**Issue by mapti89** [cilium/cilium#28706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When deploying kube-router for bgp following the documentation the container kube-router stay in crashloopbackoff

### Cilium Version

1.14.3

### Kernel Version

5.15.0-86

### Kubernetes Version

1.26.3

### Anything else?

Instead of pointing to this link "https://raw.githubusercontent.com/cloudnativelabs/kube-router/v1.2/daemonset/generic-kuberouter-only-advertise-routes.yaml" 
you should point to this new one:
"https://raw.githubusercontent.com/cloudnativelabs/kube-router/v2.0/daemonset/generic-kuberouter-only-advertise-routes.yaml" I guess there as been change on kube-router side.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mapti89** [comment]
I am referring to this documentation:
https://docs.cilium.io/en/stable/network/kube-router/
![Screenshot_20231020_005109](https://github.com/cilium/cilium/assets/124796367/8c74204e-ccca-42a6-8569-c24f040bf64f)

**Comment by squeed** [comment]
Good catch!
