### ISSUE TITLE
Generic Veth Chaining configuration suggested in documentation does not work.

### ISSUE THREAD

**Issue by veshij** [cilium/cilium#28714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm following https://docs.cilium.io/en/stable/installation/cni-chaining-generic-veth/ to deploy cilium on the on-prem kubernetes cluster running in-house veth-based CNI.
Suggested [configmap](https://docs.cilium.io/en/stable/installation/cni-chaining-generic-veth/#create-a-cni-configuration-to-define-your-chaining-configuration) adds a cilium cni section:
```
        {
          "type": "cilium-cni"
        }
```
Exactly the same config is rendered on kubelet nodes, and unfortunately  it does not work.
Plugin fails with:
```
...
plugin type="cilium-cni" failed (add): CNI PrevResult supplied, but not in chaining mode -- this is invalid, please set chaining-mode in CNI configuration
```

Based on the code correct cilium cni configuration should include `chaining-mode`:
```
        {
          "type": "cilium-cni",
          "chaining-mode": "generic-veth"
        }
```

There is a [codepath](https://github.com/cilium/cilium/blob/6db3b8f4032587329ccd3b1af3785c845be2cd22/daemon/cmd/cni/config.go#L307-L312) which should add missing sections in json, but it's not executed for multiple reasons:

- helm chart in the example does not set [CNIChainingTarget](https://github.com/cilium/cilium/blob/6db3b8f4032587329ccd3b1af3785c845be2cd22/daemon/cmd/cni/config.go#L307-L312)
- even is CNIChainingTarget is set - correct config will not be rendered since [ReadCNIConf](https://github.com/cilium/cilium/blob/6db3b8f4032587329ccd3b1af3785c845be2cd22/daemon/cmd/cni/config.go#L260-L273) is also set.

### Cilium Version

1.14.3

### Kernel Version

5.15.0-39-generic

### Kubernetes Version

1.27.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pratheeshm** [comment]
Faced the same issue. And worked only after adding `"chaining-mode": "generic-veth"` in cni config.

**Comment by squeed** [comment]
Good catch. I added those changes but didn't update the documentation. I'll get this fixed in the coming weeks.
