### ISSUE TITLE
Unable to update element for" cilium_lb4_backends_v2 map with file descriptor 17: the map is full, please consider resizing it. argument list too long" 

### ISSUE THREAD

**Issue by nowjean** [cilium/cilium#28726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium service list not working correctly.

I deployed 100 pods wtih ClusterIP type Serivce which expose 500 ports each pod. After that, i got unstable network connection and got some cilium pod error like below. (In Configure Azure CNI Powered by Cilium in Azure Kubernetes Service (AKS))

`level=error msg="Error while inserting service in LB map" error="failed to update backend cilium_lb4_backends_v2 map with file descriptor 17: the map is full, please consider resizing it. argument list too long" `

It seems related to this issue: https://github.com/cilium/cilium/issues/23551 
But my cilium version is 1.12.10. It can be also bug?

Plus, When i delete all of services and pods, there are still legacy service list in cilium ( command: cilium service list).

### Cilium Version

1.12.10

### Kernel Version

5.15.0-1041-azure

### Kubernetes Version

v1.25.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
Thanks for this report, would you be able to grab a sysdump file and upload it please so we can better debug the issue? (Using https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection)

**Comment by nowjean** [comment]
> Thanks for this report, would you be able to grab a sysdump file and upload it please so we can better debug the issue? (Using https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection)

Sorry, Because of company security problem, I can't upload dump file.

I have tested BYO v1.14.3 cilium in AKS and configured --bpf-lb-map-max to 15000, there were no errors. (Azure cilium can't change config values)

Also, I also have tested in Azure cilium with reducing ports from 500 to 200, there were no errors too.

I think it can resolve configure --bpf-lb-map-max but, I'm not sure that how calculate this value for k8s ports or services.

**Comment by dylandreimerink** [comment]
> I think it can resolve configure --bpf-lb-map-max but, I'm not sure that how calculate this value for k8s ports or services.

A backend describes a location where to send traffic next, so a service pointing to 3 pods will produce 3 backends. There are certain features that add more backends such as cluster-mesh, which adds the remote backends in other clusters as well.

You can checkout the results of `cilium bpf lb` and `cilium bpf lb --backends` within your agent container to get a feeling for how many backends you are using and for what.

**Comment by tamilmani1989** [comment]
looks this issue is fixed with this PR https://github.com/cilium/cilium/pull/26742. can you try cilium 1.14.2 or 1.15?
