### ISSUE TITLE
Add field to CNP Status to indicate whether policy is in datapath

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2873]
The policy status currently sets the `OK` field to true when the policy was *loaded* into the agent. We need a field which indicates `true` when the policy has been *implemented* in the datapath.

```
// CiliumNetworkPolicyNodeStatus is the status of a Cilium policy rule for a
// specific node
type CiliumNetworkPolicyNodeStatus struct {
        // OK is true when the policy has been installed successfully
        OK bool `json:"ok,omitempty"`

        // Error describes the error condition if OK is false
        Error string `json:"error,omitempty"`

        // LastUpdated contains the last time this status was updated
        LastUpdated Timestamp `json:"lastUpdated,omitempty"`
}
```

**Comment by aanm** [comment]
How can the logic be verified? The `CiliumNetworkPolicyNodeStatus` is per node, the policy is per endpoint. Does this means we should present the policy is implemented in the datapath in case there's one endpoint that is enforcing this given policy?

**Comment by tgraf** [comment]
> How can the logic be verified? The CiliumNetworkPolicyNodeStatus is per node, the policy is per endpoint. Does this means we should present the policy is implemented in the datapath in case there's one endpoint that is enforcing this given policy?

The policy is implemented when *all* endpoints on the node have implemented the relevant policy revision. I think it makes sense to add two fields:

`Revision` - policy revision which was return when the policy was added to the repository internall
`Enforcing` - true when all endpoints are  on `>= Revision`

**Comment by aanm** [comment]
>`Revision` - policy revision which was return when the policy was added to the repository internall
>
>`Enforcing` - true when all endpoints are on `>= Revision`

After they are on that revision number I'll need to check which endpoints have the policy installed. And for that I need this https://github.com/cilium/cilium/issues/1556

**Comment by tgraf** [comment]
> After they are on that revision number I'll need to check which endpoints have the policy installed. And for that I need this #1556

I don't follow. When we receive a CRD, we import it into the policy repository and we get back a policy revision. We can update the status with the revision right away. We should then run a controller which waits for all endpoints on the node to run this revision. Alternatively, we can encode this logic into `bumpPolicyRevision()` if we don't want to poll. Once all endpoints have been bumped, the `Enforcing` bit can be set.

**Comment by aanm** [comment]
ah that is easier then. I thought you wanted to mark the policy as `Enforced` only if there were endpoints that were being covered by the given policy.
