### ISSUE TITLE
Multi-Pool: `status.ipam.operator-status.error` is not cleared after a successful allocation

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#28758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

To reproduce, create Cilium installation without default pool, create default pool after one minute, and observe nodes successfully allocating pod CIDRs from default pool, but still reports `cannot allocate from non-existing pool: default error is not cleared`

### Cilium Version

Affects versions 1.14.0 up to current `main`

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FR-Solution** [comment]
+1

**Comment by pmseleznev** [comment]
+1

**Comment by dmkolbin** [comment]
+1

**Comment by commercetechsolutions** [comment]
+1

**Comment by gandro** [comment]
Please do not spam the issue with +1 posts. Use the :+1: button in the reaction in the original post

**Comment by gandro** [comment]
It is possible that it got fixed, I have not tried to reproduce it recently. On the other hand, there has been some up-voting on this issue as recent as September, so if those people could provide reproduction steps that would be helpful.

**Comment by FR-Solution** [comment]
Perhaps we didn't describe the task to ourselves very accurately at first: we thought we wanted to completely abandon the default pool and specify only those pools that we attach to namespaces. But if I understand correctly, part of the node addressing is taken from the default pool for routing, and it is essential for configuration, so we cannot do without it.

**Comment by gandro** [comment]
> Perhaps we didn't describe the task to ourselves very accurately at first: we thought we wanted to completely abandon the default pool and specify only those pools that we attach to namespaces. But if I understand correctly, part of the node addressing is taken from the default pool for routing, and it is essential for configuration, so we cannot do without it.

Yeah this sounds like a feature request unrelated to this issue here (which was a plain old bug). It should be possible now to set per-node default-pools via https://github.com/cilium/cilium/pull/28818 and `CiliumNodeConfig` https://docs.cilium.io/en/stable/configuration/per-node-config/

Since @jonasbadstuebner was not able to reproduce, I'll assume the bug (where the `status` field is not cleared after the error is fixed) has been patched and we can close this issue. If it resurfaces, feel free to leave a comment and we can re-open.

**Comment by FR-Solution** [comment]
@gandro Yes, they went approximately in this direction as a solution.
