### ISSUE TITLE
L2 announcements creates and maintains leases for services without announce-able IPs

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#28752]
Recently a bug/oversight in the L2 announcements logic surfaced. Currently L2 announcements just looks at policies, all services selected by a policy will get leases. It is only after a node becomes lease hold that we look at the IPs inside the service. This means that we also maintain leases for internal services with only ClusterIPs but no ExternalIP or LoadBalancerIP. This is extremely wasteful in terms of performance and reduces the max scalability of the feature.

The fix is simple, we should check, before "selecting" services if they have any useful IPs

**Comment by chaunceyjiang** [comment]
> The fix is simple, we should check, before "selecting" services if they have any useful IPs



Hi @dylandreimerink I'm very interested in this issue. Can I pick up this issue?

**Comment by f1ko** [comment]
Hi @chaunceyjiang , sorry but we assigned this Issue internally already.
Will add it here for visibility now as well.

**Comment by chaunceyjiang** [comment]
@f1ko ok, thanks for your reply .

**Comment by dylandreimerink** [comment]
Sorry, this went a bit clunky, @f1ko asked me via slack and I thought everyone could assign themselves, but only members of the Org can so it wasn't properly communicated here. Will assign @f1ko now.

**Comment by drawdy** [comment]
Will this fix take effect in the next version(1.14.5)?
