### ISSUE TITLE
CFP: multicast support

### ISSUE THREAD

**Issue by lliu0947** [cilium/cilium#28750]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

Our use case involves distributing  data feeds to multiple consumers running in the k8s cluster, This case requires multicast support. 

**Describe the feature you'd like**

multicast support in cilium

**(Optional) Describe your proposed solution**

The container network multicast transmission technology based on eBPF focuses on solving the problem of efficient multicast transmission in the container network and provides support for multiple multicast protocols. My idea is to use the eBPF map to maintain the pod list for multicast communication, complete the addition and deletion of multicast members in the cilium agent, and use the eBPF helper function to implement directional data transmission and network forwarding.

For detailed plans, see https://docs.google.com/document/d/14ekQd1MoKK9_NX0ru9rrhIHSfOyk_WkKQF7-aTLt3I0/edit?usp=sharing

**Comment by ldelossa** [comment]
@lliu0947 

Hey! your timing is pretty coincidental.

I've actually been working on the multicast feature internally for a bit now (started this before the CFP was submitted) and we are getting close to opening a OSS PR for the datapath bits. 

The design we have is rather close! 

When this PR is opened we invite you and other community members to review this PR and design. 
We expect this PR to be opened within the next several days.

**Comment by lliu0947** [comment]
> @lliu0947
> 
> Hey! your timing is pretty coincidental.
> 
> I've actually been working on the multicast feature internally for a bit now (started this before the CFP was submitted) and we are getting close to opening a OSS PR for the datapath bits.
> 
> The design we have is rather close!
> 
> When this PR is opened we invite you and other community members to review this PR and design. We expect this PR to be opened within the next several days.

When do you plan to open the pr? We are looking forward to supporting multicast in cilium

**Comment by ldelossa** [comment]
@lliu0947 

https://github.com/cilium/cilium/pull/29469 - Here is the initial PR for Multicast.

**Comment by VY5FR2NWJ9** [comment]
Is multicast already ready for use?

**Comment by hrishin** [comment]
@ldelossa thank you for getting the intial work done!

Q: Current PR seems to be supporting the sending side? (pod to pod same host, pop to pod remote host). 
Does this also support receiving side as well? (from external world to pods)

**Comment by fujitatomoya** [comment]
@ldelossa thanks for contributing the PR 👍 

I work on [Robot Operating System 2](https://docs.ros.org/en/rolling/) as a member of [Technical Steering Committee](https://docs.ros.org/en/rolling/The-ROS2-Project/Governance.html).

ROS 2 (Internally transport implementation is configurable) in default uses [Data Distribution Service](https://www.dds-foundation.org/what-is-dds-3/) and that relies on UDP multicast for participant discovery protocol in the application layer.

I just tried https://github.com/cilium/cilium/pull/29469, and since ROS 2 application cannot discover the participants, i believe it does not support pod to pod multicast communication just yet? no pressure and just checking the current status since i am not familiar with Cilium implementation.

thanks in advance,

**Comment by nakabonne** [comment]
Thanks for getting this https://github.com/cilium/cilium/pull/29469 done! Has this been released? I poked a bit around a few latest releases but can't find this commit.

**Comment by fujitatomoya** [comment]
> Thanks for getting this https://github.com/cilium/cilium/pull/29469 done! Has this been released? I poked a bit around a few latest releases but can't find this commit.

AFAIS, it's in main only, not merged into any release branches yet.

**Comment by nakabonne** [comment]
Thank you @fujitatomoya 
If that's the case, does anyone know if there is a milestone for the multicast support? CC: @ldelossa

**Comment by harsimran-pabla** [comment]
[PR](https://github.com/cilium/cilium/pull/31355) to add support for managing multicast BPF maps.

**Comment by xmulligan** [comment]
@lliang0947 I think we can close this now that https://github.com/cilium/cilium/pull/29469 is merged right?

**Comment by fujitatomoya** [comment]
@lliang0947 @xmulligan 
CC: @harsimran-pabla 

i already verified that multicast works with multicast group address and subscribers with Robot Operating System 2 and Data Distributing Service, see more details for https://github.com/fujitatomoya/ros_k8s/blob/master/docs/Setup_Kubernetes_Cluster.md#enable-multicast-wip.

btw, to close this issue, we would want to add some docs for user manual explains how to set this up? i did not see those docs so i was looking at the source code for https://github.com/cilium/cilium/pull/31355 to figure this out?

if that is good to go, i can work on the quick doc update.

**Comment by fujitatomoya** [comment]
@xmulligan i could use review for https://github.com/cilium/cilium/pull/32612

CC: @harsimran-pabla @ldelossa @joestringer
