### ISSUE TITLE
Reported cilium memory usage seems high

### ISSUE THREAD

**Issue by piec** [cilium/cilium#28772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,

I am surprised by the memory usage of cilium's daemonset pods reported by kubernetes metrics-server. In a cluster I'm using right now, newly started cilium pods are reported to use >330Mi. (All of my cilium pods use between 330Mi and 430Mi). It seems a bit high to me, correct?
```
$ kubectl -n kube-system top pods -l k8s-app=cilium
NAME           CPU(cores)   MEMORY(bytes)
cilium-5fj8p   6m           366Mi <-----
cilium-64vjc   12m          426Mi
cilium-77twq   5m           337Mi
...
```
---
Kubernetes metrics-server memory usage for a pod is based on cAdvisor's `container_memory_working_set_bytes`, itself is based on the pod's memory cgroup statistics.
In cgroupv1 it's calculated like this: `container_memory_working_set_bytes = memory.usage_in_bytes - memory.stat[total_inactive_file]`
[source](https://github.com/google/cadvisor/blob/bf2a7fee4170e418e7ac774af7679257fe26dc69/container/libcontainer/handler.go#L837-L845)
An easy way to get these values is to `kubectl exec` a shell in a cilium pod "cilium-agent" container and to look at `/sys/fs/cgroup/memory/memory.stat` and `/sys/fs/cgroup/memory/memory.usage_in_bytes`.
(it's also more accurate to open a shell in the node itself and find the pod's cgroup, because there is actually also the stopped initContainer that can still use some memory even if it's completed)

```
(pod cilium-5fj8p) # cat /sys/fs/cgroup/memory/memory.usage_in_bytes
                                     403435520

(pod cilium-5fj8p) # cat /sys/fs/cgroup/memory/memory.stat
cache                                 73277440
rss                                   71852032
rss_huge                                     0
shmem                                 31850496
mapped_file                           25665536
dirty                                        0
writeback                                    0
swap                                         0
pgpgin                                15544572
pgpgout                               15509140
pgfault                                2099552
pgmajfault                              432855
inactive_anon                         92012544
active_anon                           11620352
inactive_file                         19111936
active_file                           22315008
unevictable                                  0
hierarchical_memory_limit           4027047936
hierarchical_memsw_limit   9223372036854771712
total_cache                           73277440
total_rss                             71852032
total_rss_huge                               0
total_shmem                           31850496
total_mapped_file                     25665536
total_dirty                                  0
total_writeback                              0
total_swap                                   0
total_pgpgin                          15544572
total_pgpgout                         15509140
total_pgfault                          2099552
total_pgmajfault                        432855
total_inactive_anon                   92012544
total_active_anon                     11620352
total_inactive_file                   19111936
total_active_file                     22315008
total_unevictable                            0

(pod cilium-5fj8p) # cat /sys/fs/cgroup/memory/memory.kmem.usage_in_bytes
                                     258306048

(pod cilium-5fj8p) # ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.4  2.1 789072 84136 ?        Ssl  Sep22 233:43 cilium-agent --config-dir=/tmp/cilium/config-map
root         423  0.0  0.1 706916  4028 ?        Sl   Sep22   3:13 cilium-health-responder --listen 4240 --pidfile /var/run/cilium/state/health-endpoint.pid
```

If I do the calculation, WSS=`(403435520-19111936)/1024/1024 ~= 366.5 Mi`, the same as the kubernetes metric.
But why is `memory.usage_in_bytes` so high? According to the [kernel's documentation](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt) it should be more or less equal to RSS+CACHE(+SWAP) but is much higher. `memory.usage_in_bytes` does not seem to count kernel memory as I have read at other places.

What do you think?
Thanks

### Cilium Version

Client: 1.12.5 701acde 2022-12-15T16:03:30-08:00 go version go1.18.9 linux/arm64
Daemon: 1.12.5 701acde 2022-12-15T16:03:30-08:00 go version go1.18.9 linux/arm64

### Kernel Version

Linux 5.15.0-1031-aws #35~20.04.1-Ubuntu SMP Sat Feb 11 16:19:53 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Server Version: v1.26.3
kops cluster

### Sysdump

I have a sysdump but not like to share it publicly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
Memory usage of Cilium depends on the resources within the cluster. More policies, more pods, more nodes, etc, can lead to an increase in memory usage. Without information about the cluster, it's difficult to determine whether Cilium is using an expected amount of memory or if there's some sort of leak.

**Comment by piec** [comment]
I agree with that, and I'm ok with cilium using memory :) but what I don't understand is how memory usage is being reported. Why is the pod cgroup `memory.usage_in_bytes` so high (>300Mi) while rss + cache ~= 150Mi? Do you observe the same thing?

This example is from a "dev" cluster that is currently idle. It is not running any workload except running kube-prometheus-stack
```
$ kubectl get endpoints -A | wc -l
41
$ kubectl get ns | wc -l
21
$ kubectl get networkpolicies.networking.k8s.io -A | wc -l
No resources found
0
$ kubectl get nodes | wc -l
5
$ kubectl get pods -A | wc -l
77
$ kubectl get service -A | wc -l
41
$ kubectl -n kube-system top pods -l k8s-app=cilium
NAME           CPU(cores)   MEMORY(bytes)
cilium-chs8g   10m          504Mi
cilium-k7qxn   6m           351Mi
cilium-n47rm   6m           338Mi
cilium-v5bjx   5m           346Mi

$ kubectl -n kube-system exec -it cilium-chs8g -- ps aux
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  1.0  1.6 857244 132172 ?       Ssl  Sep23 491:04 cilium-agent
root         420  0.0  0.0 706660   5060 ?       Sl   Sep23   1:08 cilium-health

$ kubectl -n kube-system exec -it cilium-k7qxn -- ps aux
Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.6  1.5 788888 122456 ?       Ssl  Oct13 107:12 cilium-agent
root         420  0.0  0.0 706660   5324 ?       Sl   Oct13   0:24 cilium-health
```

**Comment by squeed** [comment]
Oh man, cgroup memory accounting is super interesting and never obvious. The cgroup attempts to account for certain blocks of kernel memory, especially TCP sockets. You're not the first person to notice that RSS is calculated differently than `usage_in_bytes`. For example, the cgroup can include `inactive_file`, which is *not* included in RSS. So that, alone, is probably the difference you're seeing.

**Comment by lmb** [comment]
Seems like there is a plausible explanation, do you mind if we close this issue @piec ?

**Comment by piec** [comment]
(Sorry for leaving this issue stale)

Hi @squeed, thanks for your answer

> You're not the first person to notice that RSS is calculated differently than usage_in_bytes

I'm not saying that :)

What I'm saying is in my example:
* according to k8s source code:
`k8s pod memory = cAdvisor wss = cgroup memory.usage_in_bytes - memory.stat[total_inactive_file] ~= 366 Mi` (corresponds to reported pod's memory)
* according to [kernel doc](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt):
`cgroup memory.usage_in_bytes ~= RSS+CACHE(+SWAP)` and does not account for kernel memory.
If I do the calculation for my pod it <100Mi
* So question: why is `memory.usage_in_bytes` so large?
Is the documentation outdated? I didn't find the time to check how the kernel does the accounting. Also it can be quite complex I suppose

**Comment by anjmao** [comment]
I was playing with hetzner k8s terraform module and installed it with cilium as default cni for my initial empty 2 nodes clusters with few small cheap 5$/nodes. It wasn't able to start due to cilium crashes and OOM kills. 
Later I saw this comment inside the module regarding cilium higher memory usage for empty clusters https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/kube.tf.example#L675

**Comment by aanm** [comment]
Cilium 1.12.5 is EOL, please upgrade to a more recent version and create a new issue if you are still facing this problem. Cilium 1.16.0, planned to be released at the end of this month has some memory optimizations which should decrease its memory usage.
