### ISSUE TITLE
New nodes cannot reach the API server

### ISSUE THREAD

**Issue by oarezki** [cilium/cilium#28807]
Hi,

I deployed EKS cluster with terraform, a node group of two worker nodes, working absolutely fine, with Cilium configured to be a replacement (**kubeProxyReplacement: "true"**) for Kube proxy, whose I deleted the ds. 

However, whenever I want to scale out the cluster (still with terraform), the new nodes' cilium agents (config init container) cannot reach the API server.

Security groups are common to all nodes.

After troubleshooting, I found out **that kube proxy is still needed to add new nodes**. I did set it up again, and it worked.

Is this a normal behavior ? Because per the documentation I ran into, kube proxy can be deleted if Cilium fully supplanted it.

**Comment by dylandreimerink** [comment]
I recommend you follow the instructions in https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kubeproxy-free. Particularly the warnings regarding the removal of kube proxy when replacing it with Cilium.

You do not need kube-proxy to bootstrap a cluster since the API server listens on the host network, if you are planning on running Cilium on a new cluster, its easier to not install kube-proxy in the first place, instructions for that are also in the link.

**Comment by oarezki** [comment]
I had to perform a migration from vpc cni to cilium, hence the presence of kube proxy which I deleted afterwards.

Is kube proxy required to scale out a cluster ?

**Comment by dylandreimerink** [comment]
> Is kube proxy required to scale out a cluster ?

No, it should not be. The kube api server pod listens on the host network, so no CNI should be required to reach it. So unless you are explicitly blocking traffic to the api server it should "just work".

**Comment by oarezki** [comment]
> so no CNI should be required to reach it

Thank you for your response, but I'm not sure I fully understand the connection with CNI in this context.

Also, as I stated in my very first comment, I'm using EKS whose master nodes are AWS managed, so I don't have access to those nodes for packet capture or troubleshooting.

I had to add kube proxy temporarily to my cluster, which fixed my issue of scaling out.

However, I'm not entirely sure why kube proxy was necessary in this case. Could you please provide more insights into why kube proxy might have been needed for this specific scenario in an EKS-managed environment?

**Comment by squeed** [comment]
You do need to configure Cilium to connect directly to the apiserver, rather than through the service IP as provided by kube-proxy.

You do this by setting the `k8sServiceHost` and `k8sServicePort` helm values, then re-installing.

**Comment by oarezki** [comment]
> You do need to configure Cilium to connect directly to the apiserver, rather than through the service IP as provided by kube-proxy.
> 
> You do this by setting the `k8sServiceHost` and `k8sServicePort` helm values, then re-installing.

They are already configured and as I stated before, it is already working with existing nodes, so it cannot be k8sServiceHost and k8sServicePort.

**Comment by lmb** [comment]
Hi @oarezki, if you think this is a bug please open a new issue following the Bug Report template and include all the relevant information. As it stands there isn't enough information here diagnose the issue.

If this is not a bug but a configuration issue you're best off asking in our slack.
