### ISSUE TITLE
Expose environment variable to helm chart value.

### ISSUE THREAD

**Issue by crazy-canux** [cilium/cilium#28826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when deploy hubble-ui stand along on GKE. it's not working.

### Cilium Version

cilium-cli: v0.13.2 compiled with go1.20.2 on linux/amd64
cilium image (default): v1.13.1
cilium image (stable): v1.14.3
cilium image (running): v1.12.10-gke.11

### Kernel Version

Linux a015717 5.15.0-86-generic #96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3-gke.100", GitCommit:"6466b51b762a5c49ae3fb6c2c7233ffe1c96e48c", GitTreeState:"clean", BuildDate:"2023-06-23T09:27:28Z", GoVersion:"go1.20.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

N/A

### Relevant log output

```shell
level=warning msg="Failed to create gRPC client" address="10.242.153.132:4244" error="connection error: desc = \"transport: error while dialing: dial tcp 10.242.153.132:4244: connect: connection refused\"" hubble-tls=true next-try-in=10s peer=gke-phoenix-dev-cluster1-arm64-group1-4266fa47-gkv6 subsys=hubble-relay
level=warning msg="Failed to create gRPC client" address="10.242.153.168:4244" error="connection error: desc = \"transport: error while dialing: dial tcp 10.242.153.168:4244: connect: connection refused\"" hubble-tls=true next-try-in=10s peer=gke-phoenix-dev-cluster1-arm64-group1-3b2f6dce-w3tk subsys=hubble-relay
```

### Anything else?

https://github.com/cilium/cilium/blob/898a632e3c3b64eaa0f23ebde5a069e87373c59b/install/kubernetes/cilium/templates/hubble-ui/deployment.yaml#L99

        - name: FLOWS_API_ADDR
          value: "hubble-relay:443"
        - name: TLS_TO_RELAY_ENABLED
          value: "true"
        - name: TLS_RELAY_SERVER_NAME
          value: ui.hubble-relay.cilium.io
          
for gke it should be:

         - name: FLOWS_API_ADDR
          value: "hubble-relay.kube-system.svc:443"
        - name: TLS_TO_RELAY_ENABLED
          value: "true"
        - name: TLS_RELAY_SERVER_NAME
          value: relay.kube-system.svc.cluster.local

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crazy-canux** [comment]
Oh, Sorry for paste the wrong logs.

If you check the GKE spec, you will understand.
https://cloud.google.com/kubernetes-engine/docs/how-to/configure-dpv2-observability#hubble-ui-standard

**Comment by dylandreimerink** [comment]
I believe this issue is a duplicate of https://github.com/cilium/cilium/issues/28708

**Comment by crazy-canux** [comment]
Thank you!  I will use 1.15 once it's released.
