### ISSUE TITLE
Disable socket-LB for connected UDP

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#28821]
Until we've fully resolved the socket-LB limitation, add an option to disable socket-LB only for connected UDP (this enables socket-LB for TCP). 

More context - https://github.com/cilium/cilium/issues/28820.

**Comment by chaunceyjiang** [comment]
I'm very interested in this issue. Can I pick up this issue? @aditighag

**Comment by aditighag** [comment]
@chaunceyjiang I've assigned you the issue. I would suggest reaching out on the #datapath Slack channel with a high level approach, or if you have any questions.

**Comment by chaunceyjiang** [comment]
@aditighag Thank you very much. To be honest, I'm not yet familiar with `datapath`, I can't guarantee that I will be able to complete this task, but I will do my utmost best.

**Comment by gaffneyd4** [comment]
We are using cilium in kube-proxy-replacement mode. When reviewing the [documentation](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kubernetes-without-kube-proxy) for it, I noticed this:
> Cilium’s kube-proxy replacement depends on the socket-LB feature
What would be the effect of `disable socket-LB only for connected UDP` for users like us running in `strict` kube-proxy-replacement mode? Would this change cause connected UDP to break? Would users have to run kube-proxy again? Is there a fall back method for routing connected UDP without using socketLB or running kube-proxy?

**Comment by aditighag** [comment]
>What would be the effect of disable socket-LB only for connected UDP for users like us running in strict kube-proxy-replacement mode?

The expectation would be that connected UDP traffic will be load-balanced in the Cilium's per-packet LB datapath. However, if you have pods/processes in the host netns that need service LB, you would have to install kube-proxy. Hope that answers your questions.

**Comment by borkmann** [comment]
Fixed via https://github.com/cilium/cilium/pull/33459
