### ISSUE TITLE
kafka: Create responses based on version of request

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2883]
The current code sends Kafka responses based on the latest version regardless of the version used in the request. Validate if any of the responses returned are incompatible based on the request version. The responses are very basic so it's unclear whether any version incompatibility exists.

**Comment by eloycoto** [comment]
I added `needs/e2e-test` to add a test case for this in Nightly tests.

**Comment by manalibhutiyani** [comment]
I have a query about this
We only send a response if there is a request deny. I am going through all the responses we create : 
```
// CreateResponse creates a response message based on the provided request
// message. The response will have the specified error code set in all topics
// and embedded partitions.
func (req *RequestMessage) CreateResponse(err error) (*ResponseMessage, error) {
	switch val := req.request.(type) {
	case *proto.ProduceReq:
		return createProduceResponse(val, err)
	case *proto.FetchReq:
		return createFetchResponse(val, err)
	case *proto.OffsetReq:
		return createOffsetResponse(val, err)
	case *proto.MetadataReq:
		return createMetadataResponse(val, err)
	case *proto.ConsumerMetadataReq:
		return createConsumerMetadataResponse(val, err)
	case *proto.OffsetCommitReq:
		return createOffsetCommitResponse(val, err)
	case *proto.OffsetFetchReq:
		return createOffsetFetchResponse(val, err)
	case nil:
		return nil, fmt.Errorf("unsupported request API key %d", req.kind)
	default:
		// The switch cases above must correspond exactly to the switch cases
		// in ReadRequest.
		log.Panic(fmt.Sprintf("Kafka API key not handled: %d", req.kind))
	}
	return nil, nil
```

I can see that we fill in the fields of the responses based on the value of `req.apiVersion`, specifically the `Bytes` interface of all of these methods checks for  `req.apiVersion` before choosing to fill in a field or skip it. So is this issue concerning checking if we are filling up all these fields based on `req.apiVersion` or latest version? From what I can tell, we already check this. Could you clarify a bit more what is needed in this issue?

**Comment by tgraf** [comment]
The intent of this issue is to verify whether we correctly support versioning of responses based on the requests, if we already do this, then this issue can be closed.
