### ISSUE TITLE
LRP with address matcher not working after removing the service

### ISSUE THREAD

**Issue by tangenti** [cilium/cilium#28841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Reproducing steps:

1. Apply an LRP with service matcher for a service.
2. Apply another LRP with address matcher for the same service, where the address is the cluster IP of the service. In the output of `cilium lrp list`, the latest applied LPR is not shown, which is expected as there's already an LRP for the front end.
3. Now, remove the service or add the label "service.kubernetes.io/headless" to the service, so Cilium would ignore the service.
4. Check the output of `cilium lrp list` again. The output would only include the first LRP applied, but matched nothing.

I consider this as a bug, since that after ignoring the service, the cluster IP exists while the matched service is deleted, so the second LRP should take effect (especially the CR still exists). 

### Cilium Version

cilium:v1.12.10-gke.25

### Kernel Version

N/A

### Kubernetes Version

1.27.4-gke.900

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tangenti** [comment]
Related issue: #27754

**Comment by dylandreimerink** [comment]
Thanks for this report, would you be able to grab a sysdump file and upload it please so we can better debug the issue? (Using https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection)

**Comment by aditighag** [comment]
>Apply another LRP with address matcher for the same service

What's the real use case here? The two types of LRPs serve different purposes.
