### ISSUE TITLE
Rename or remove cilium cleanup

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#28842]
Cilium cleanup sounds pretty innocent, many people like things to be clean.

Unfortunately the actual functionality of this is dangerous and invasive, and occasionally users stumble onto the option while trying to solve another problem. Rather than cleaning things up and helping to get Cilium into a better state, this leads the user into further problems.

https://github.com/cilium/cilium/blob/5ab0230bb9f0566bf36375e9640a6afa802b681b/cilium-dbg/cmd/cleanup.go#L30-L33

We should consider at least renaming the option to make it clearer that this is some sort of "force-destroy" of state (flush also works, but flush doesn't sound dangerous enough).

We may also consider dropping the feature, however maybe it's still useful for something like uninstall.

**Comment by shardulsrivastava** [comment]
@joestringer I can work on this issue, can you please assign it to me

**Comment by joestringer** [comment]
@shardulsrivastava sure, do you have a proposal or PR to discuss?

**Comment by littlejo** [comment]
@joestringer could assign it to me?

**Comment by qmonnet** [comment]
@hemanthmalla mentioned he's still using the command, so we probably want a renaming rather than a removal.
