### ISSUE TITLE
Node After Restart Can Not Communicate With Service IPs

### ISSUE THREAD

**Issue by yaskinny** [cilium/cilium#28864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a node gets restarted (manually/crashed/...), that node (and any pods on this node) can not communicate with the service IPs. For example

On a working node if i check connectivity to any service ip/port it works. here I check kubernetes service on default namespace:
```
nc -zv 10.96.0.1  443
Connection to 10.96.0.1 443 port [tcp/https] succeeded!
```

same command on a node which is restarted fails.

but failed node can communicate directly with pod IPs. so if a pod IP is 10.1.2.3 and it accepts connections on port 4444, I can validate node can connect to the pod IP with the same `nc` command.
```
nc -zv 10.1.2.3 4444
Connection to 10.1.2.3 4444 port [tcp/https] succeeded!
```

I can fix the failed node with:
- Drain node , delete node from the cluster, reboot the node , join node again to the cluster.
OR
- Change Cilium configuration: 
   - change routing mode to `native` and delete that node cilium pod.
   - then wait for that node cilium pod to become ready
   - after that change routing back to `tunnel` and delete cilium pod on the failed node
   -  after these steps, node becomes ready and can communicate with the services IPs

### Cilium Version

1.14.2

### Kernel Version

5.15.0-87-generic

### Kubernetes Version

1.28.1

### Anything else?

failed node which can not communicate with the service shows that service identity as `world` but other nodes shows its identity id in `cilium monitor`.
also failed node shows correct identity id for service in output of `cilium identity list`(it shows identity id 12304)

---
K8s cluster is on-prem and we are using kube-replacement mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yaskinny** [comment]
anyone on this issue?

**Comment by adamcooke** [comment]
I have also observed this issue recently when a node is shutdown in an unexpected manner. The resolution was to just delete the cilium pod on the host and service connectivity was restored once the new pod was initialized.

As with the OP, pod connectivity was fine, it was just services that were inaccessible.

**Comment by yaskinny** [comment]
hello @adamcooke, Thanks for response.

What kind of information do You need? tell me and I'll share them for You here.

**Comment by squeed** [comment]
@yaskinny that seems drastic! Would it be possible to capture a sysdump with a node in this state?

**Comment by yaskinny** [comment]
hey @squeed, I'll for sure provide a sysdump in couple of days. Right now I'm busy with other tasks. Thanks!

**Comment by yaskinny** [comment]
hello,
I  got a system dump from a failed node, the problem is sysdump has lots of information like our public ips in policies, application names, container names, ... . which disclosing tons of information.

I did a simple grep and they are mostly in these files:
```
cilium-debuginfo-20231127-135845.302+0000-UTC.md
cilium-debuginfo-20231127-135845.302+0000-UTC.json
cilium-map-events-cilium_ipcache--o-json.md
cilium-ip-list--n--o-json.md
cilium-map-list---verbose.md
cilium-service-list--o-json.md
cilium-policy-get.md
cilium-bpf-ipcache-list.md
cilium-identity-list.md
```
if they are not needed I can exclude them and send other files. if they are needed I have to almost change everything that disclosing information.

Also do you need sysdump from a healthy node or same node after recovering it?

please let me know.
@julianwiedmann @squeed @adamcooke

**Comment by youngnick** [comment]
Sending some information is better than none - if you could send whatever you can, it will really help with being able to investigate this issue. I'll mark this as need-more-info again while you come back with that.

A separate sysdump from a healthy node would also be useful, thanks.
