### ISSUE TITLE
CFP: Will cilium consider enhancing non-compatible upgrade capabilities?

### ISSUE THREAD

**Issue by MeninaChimp** [cilium/cilium#28894]
## Cilium Feature Proposal
        
Hello cilium team, thank you for your time.

**Is your proposed feature related to a problem?**

When there are changes in the BPF maps resource structure, length, size, field additions and deletions, etc., it will lead to incompatible upgrades.

For incompatible upgrades caused by BPF maps change, cilium achieves compatibility with the new structure by performing a one-time migration of existing data when the new version of the agent starts. However, during this upgrade process, upstream changes will be interrupted. The duration depends on the scale of the existing data. For online traffic with high-frequency changes, this delay appears to be too large. Regarding this issue, does Cilium have plans to enhance such capabilities, such as a hot upgrade solution for dual-process switching?

In addition, For the changes of the BPF maps maintained on the data plane, such as the ct map (although padding is currently reserved), the one-time migration solution does not seem to be applicable, so for this kind of scenario, does Cilium have plans to enhance it in the future? or Cilium’s planning does not consider such scenarios

**Describe the feature you'd like**

Maybe a hot upgrade solution for dual process switching

**Comment by joestringer** [comment]
Thanks for raising interest around this issue. In general only the CT map should be problematic in this regard based on current mechanisms. I believe it should be possible for Cilium to avoid any datapath impact during upgrades/restarts with changes to any other maps. At the same time, I recognize that there is a lot of nuance in the way that Cilium prepares the datapath upon restart/upgrade. As such, it is easy to reintroduce unintentional drops into the tree. We would welcome patches to improve the connectivity behaviour in Cilium across upgrades.

**Comment by MeninaChimp** [comment]
@joestringer Thank you for your reply, it is very clear and we understand it.
