### ISSUE TITLE
Forbid using ephemeral ports in Pod `spec.containers.ports[].hostPort`

### ISSUE THREAD

**Issue by jibi** [cilium/cilium#28924]
Currently nothing prevents from configuring a Pod to use a `hostPort` in the ephemeral range, but if BPF masquerading is enabled, this can conflict with masqueraded traffic, as the reply traffic will hit the service first and will then be rejected instead of being reverse translated.

We found this while looking at a CI flake, where the echo server was using a host port of 40000 https://github.com/cilium/cilium-cli/pull/2073.

Because of this, we should reject such configuration

**Comment by jignyasamishra** [comment]
@jibi can you help me understamd exactly we are trying to tackle here and give me some suggestiosn on how to get started on this. Thank you!
