### ISSUE TITLE
CFP: Have a shorter CT expiration when a connection is in half closing status. 

### ISSUE THREAD

**Issue by tongqg** [cilium/cilium#28939]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

In eBay, we have our SLB solution. It is implemented in DSR (Direct Server Return) mode.  User's connection request is going through the node but the response doesn't. When we deploy Cilium on the network nodes,  Cilium leaves a lot of CT entries left in RxClosing but not TxClosing status These CT entries can't reach to the final closed status. They are expired in 6 hours which is the default expiration time for active connection. It ends up with a big CT Map required for the network nodes. But most of them are not for active connections. 

**Describe the feature you'd like**

This proposal is to have a separate expiration time for half closing CT entries. The expiration timeout should be much shorter such as 60 seconds

**(Optional) Describe your proposed solution**

The implementation will be straightforward. If this feature makes sense, I can submit a PR for this.

**Comment by julianwiedmann** [comment]
:wave: that sounds interesting indeed! Your suggested improvement would specifically be about `CT_SERVICE` entries on the load-balancer node, correct?

Naively I would have expected that the relevant code already handles this (https://github.com/cilium/cilium/blob/fb996faa66d8ebc735b0143e4b75c2cfe64480eb/bpf/lib/conntrack.h#L313), so maybe we're just missing a condition there. Could you have a look at that code part, and check why it's not helping in your scenario?

(would definitely be interested in having a look at the PR, if you already have a draft change :+1: )

**Comment by julianwiedmann** [comment]
(note that in the case of `CT_SERVICE` entries, I believe this would be also relevant to non-DSR setups. `CT_SERVICE` entries don't track replies when they pass through the LB.)

**Comment by tongqg** [comment]
@julianwiedmann Thanks for checking this request. I refer to the CT entries other than `CT_SERVICE` such as `CT_INGRESS` or `CT_EGRESS`. I am raising the PR to show what exactly I was trying to propose. Since the number of connections (in DSR mode) are extremely large in the load-balancer node in eBay, this change will help to reduce the total number of CT entries in the BPF map.

**Comment by julianwiedmann** [comment]
> I refer to the CT entries other than `CT_SERVICE` such as `CT_INGRESS` or `CT_EGRESS`.

ok, that's curious. When using DSR, the LB node [avoids creating](https://github.com/cilium/cilium/blob/e40fd083a503b21dd3c88e8e21e83814356a3616/bpf/lib/nodeport.h#L2887) `CT_EGRESS` entries for LBed connections. And I see even less reason for creating `CT_INGRESS` entries on the LB node.

Are you up for debugging in a bit more detail what's going on? Let's understand whether this is a bug / mis-config, before we add config options to work-around unexplained behaviour.

For a start, can you share a (sanitized) sysdump? A snapshot of your cilium config? A dump of the CT map that shows these `CT_INGRESS` / `CT_EGRESS` entries? Is the LB node running in XDP mode?

**Comment by tongqg** [comment]
We are still using our own SLB solution (BGP + ipvs + ipip tunnel). We are not moving to Cilium XDP LB yet.

**Comment by julianwiedmann** [comment]
> We are still using our own SLB solution (BGP + ipvs + ipip tunnel). We are not moving to Cilium XDP LB yet. Also we haven't enabled KPR (Kube-proxy-replacement) feature either.
> 
> When we deploy `cilium-agent` on such a node, the CT map has all connections going through the node I believe. I've seen the map has both `CT_INGRESS` and `CT_EGRESS`.

Ah suddenly this makes a lot more sense :).

If you have your own DSR LB-logic in ipvs, then yes that should result in
```
CT_INGRESS: client -> vip
CT_EGRESS: client -> backend
``` 

and those entries never fully closing, as the LB is not observing the return traffic.

**Comment by tongqg** [comment]
Our SLB have a lot of connections which end up with too many (like millions) CT entries left in the BPF map. We need the enhancement to cleanup the half closed connection sooner.
