### ISSUE TITLE
cilium_agent_bootstrap_seconds metrics are missing due to race condition between daemon/cmd/root.go & pkg/metrics/metrics.go

### ISSUE THREAD

**Issue by Ramkumar-K** [cilium/cilium#28935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the 1.13 branch the cilium_agent_bootstrap_seconds metrics are not getting exported from the metrics port.

init() from daemon/cmd/root.go calls registerBootstrapMetrics and init() from pkg/metrics/metrics.go calls ResetMetrics just a bit later and hence the bootstrap metrics are not recorded.

Solutions could be:

1. Invoke registerBootstrapMetrics from RegisterDefaultMetrics in pkg/metrics/metrics.go
2. Invoke registerBootstrapMetrics in updateMetrics in daemon/cmd/metrics.go
3. Is there a way to specify dependency between the 2 libraries or can the registration code be moved out of the init functions?

### Cilium Version

1.13

### Kernel Version

Linux gke-metrics-test-default-pool-47945f99-qjk7 6.1.42+ #1 SMP PREEMPT_DYNAMIC Sun Oct  8 14:23:56 UTC 2023 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux

### Kubernetes Version

1.28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ramkumar-K** [comment]
@aojea @akhilles

**Comment by aojea** [comment]
cc: @aanm
