### ISSUE TITLE
Missing metrics if there are over 1000 nodes in a cluster

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#28934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Prometheus-operator only detects up to 1000 endpoints per ServiceMonitor. So if you have over 1000 nodes, you will be missing Cilium metrics for a subset of them.

### Cilium Version

all

### Kernel Version

n/a

### Kubernetes Version

n/a

### Anything else?

Upstream bug: https://github.com/prometheus-operator/prometheus-operator/issues/3862

A workaround is to use PodMonitor instead of ServiceMonitor, example: https://github.com/prometheus-community/helm-charts/pull/2866

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chancez** [comment]
So  a simple fix would be for us to add an option to create PodMonitors instead of ServiceMonitors. That seems fairly simple. @dctrwatson would you be interested in opening a PR for that?
