### ISSUE TITLE
Router IP restoration from Kubernetes is no longer working

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#29019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

During local testing, we've discovered that router IP restoration from Kubernetes no longer seems to work:

> - Does restoration from K8s even work? We fetch the [k8s `Node` object](https://github.com/cilium/cilium/blob/9638c9d41ab162b396b99ef0ede2089bd0021046/daemon/k8s/init.go#L55) (not `CiliumNode`) and it no longer seems to contain an annotation with the router IP? And even with clusterpool, we call `UpdateCiliumNodeResource` before `WaitForNodeInformation`, which [simply clears out the old router IP](https://github.com/cilium/cilium/blob/e30e46a5b43945900cace8e7a73fd571d0365db0/pkg/nodediscovery/nodediscovery.go#L438) (and [ignores](https://github.com/cilium/cilium/blob/e30e46a5b43945900cace8e7a73fd571d0365db0/pkg/nodediscovery/nodediscovery.go#L490) the router IP from the `Node` resource if it was present, but it anyway doesn't seem to be). At least with Kind, I have not been able to get it to work both before and after this PR

See discussion on the PR for some more investigation: https://github.com/cilium/cilium/pull/28781#issuecomment-1798105075

It seems that we no longer set annotations for the K8s node object. One question though is if we should actually restore the router IP from annotations, or if it would be better to use the CiliumNode object instead.

### Cilium Version

v1.15-pre, but this might have been a regression since 1.13

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
@gandro, @tommyp1ckles, we can close this as fixed by https://github.com/cilium/cilium/pull/29460 and https://github.com/cilium/cilium/pull/29964, right?

**Comment by gandro** [comment]
I believe this can be closed now, yes.
