### ISSUE TITLE
CI: Conformance E2E (ci-e2e) - [pod-to-pod-encryption] + [node-to-node-encryption]

### ISSUE THREAD

**Issue by rastislavs** [cilium/cilium#29029]
## CI failure

Job: https://github.com/cilium/cilium/actions/runs/6783164928/job/18436851695

```
📋 Test Report
❌ 2/55 tests failed (3/603 actions), 7 tests skipped, 0 scenarios skipped:
Test [pod-to-pod-encryption]:
  ❌ pod-to-pod-encryption/pod-to-pod-encryption/curl-ipv4: cilium-test/client-6b4b857d98-xbwvx (10.244.3.237) -> cilium-test/echo-other-node-78455455d5-6f52k (10.244.1.15:8080)
Test [node-to-node-encryption]:
  ❌ node-to-node-encryption/node-to-node-encryption/curl-ipv4: cilium-test/host-netns-znfts (172.18.0.3) -> cilium-test/echo-other-node-78455455d5-6f52k (10.244.1.15:8080)
  ❌ node-to-node-encryption/node-to-node-encryption/curl-ipv6: cilium-test/host-netns-znfts (fc00:c111::3) -> cilium-test/echo-other-node-78455455d5-6f52k (fd00:10:244:1::f7b6:8080)
```

Logs:
```
[=] Test [pod-to-pod-encryption]
.
  [-] Scenario [pod-to-pod-encryption/pod-to-pod-encryption]
  [.] Action [pod-to-pod-encryption/pod-to-pod-encryption/curl-ipv4: cilium-test/client-6b4b857d98-xbwvx (10.244.3.237) -> cilium-test/echo-other-node-78455455d5-6f52k (10.244.1.15:8080)]
  ❌ Captured unencrypted pkt (count=17 packets)
```

```
[=] Test [node-to-node-encryption]
..
  [-] Scenario [node-to-node-encryption/node-to-node-encryption]
  [.] Action [node-to-node-encryption/node-to-node-encryption/ping-ipv4: cilium-test/host-netns-znfts (172.18.0.3) -> cilium-test/host-netns-5xd65 (172.18.0.2:0)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/curl-ipv4: cilium-test/host-netns-znfts (172.18.0.3) -> cilium-test/echo-other-node-78455455d5-6f52k (10.244.1.15:8080)]
  ❌ Captured unencrypted pkt (count=11 packets)
```

Sysdumps: https://drive.google.com/file/d/1fx3jEq6mKVWzLoKcKf-oJKDTBunkBQrX/view?usp=sharing

**Comment by brb** [comment]
I wonder whether it's one-off, or does it is constantly failing? The recently merged https://github.com/cilium/cilium/pull/29000 might be to blame.

**Comment by rastislavs** [comment]
@brb I re-run the job and seems to be constant, here are the next attempts:
- https://github.com/cilium/cilium/actions/runs/6783164928/job/18438475665
- https://github.com/cilium/cilium/actions/runs/6783164928/job/18439466372

**Comment by brb** [comment]
Hmm, I've just tried running this https://github.com/cilium/cilium/pull/29031 (the latest `main` + a dummy commit), and the jobs passed - https://github.com/cilium/cilium/actions/runs/6784698892.

**Comment by rastislavs** [comment]
Hmm, I see this failing on this PR: https://github.com/cilium/cilium/pull/28973 - not sure how the change could be related to the failure.

Let me rebase it and retry again.

**Comment by rastislavs** [comment]
Yeah the test is passing now after the rebase. Maybe an issue with the intermediary commit I was based on? (It was failing while I was based on https://github.com/cilium/cilium/commit/18879b5975ad516727ae4e821d79d9b1edccea11)

**Comment by brb** [comment]
Thanks for validating this. :man_shrugging:

**Comment by brb** [comment]
Yeah, it could be that the GH action workflow file is taken the new one, while the code doesn't have necessary changes for that failing test to pass. I think we can close this issue.
