### ISSUE TITLE
When tcp requests syn, an incorrect ack is returned. When in the network quadruple, the source IP and port are the same, and the destination IP and port are different

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#29037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As shown in the figure below, two sessions: 10.82.36.11:40001 -> 10.82.107.128:3600 and 10.82.36.11:40001->10.82.107.120:3448. When the first one sends syn, the seq returned by the server is 1987538173 , when sending syn for the second session, the seq returned by the server is 1987538174, and cilium mistakenly treats the two sessions as one session.

<img width="1564" alt="企业微信截图_688b5251-7218-4197-b136-a264cc7f61e3" src="https://github.com/cilium/cilium/assets/6076617/07cb266c-4181-4437-8fe0-8861b8d2974e">

### Cilium Version

1.12.7

### Kernel Version

4.19.113-300.el7.x86_64

### Kubernetes Version

1.24.10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Where do you see the two sessions being combined? Are the conntrack maps indicating incorrect information?

**Comment by squeed** [comment]
Also, Cilium is now up to v1.12.15; please consider upgrading. Likewise, it's difficult to consider issues without a sysdump or other debugging information.

**Comment by llhhbc** [comment]
the picture is the sysdump info, you can look the response seq. within in green and blue box,they are two session.

**Comment by llhhbc** [comment]
@squeed

**Comment by julianwiedmann** [comment]
> the picture is the sysdump info, you can look the response seq. within in green and blue box,they are two session.

Please follow the steps in the [issue template](https://github.com/cilium/cilium/issues/new?assignees=&labels=kind%2Fcommunity-report%2Ckind%2Fbug%2Cneeds%2Ftriage&projects=&template=bug_report.yaml):

> **Sysdump**
> - [Install Cilium CLI](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-the-cilium-cli).
> - Run cilium sysdump command

Also please reproduce on the **latest** `v1.12` release (which is currently `v1.12.16`). Or preferably `v1.14`.

**Comment by llhhbc** [comment]
@julianwiedmann The results of the tcpdump packet capture clearly illustrate the problem. Is there no possible direction for the problem?
