### ISSUE TITLE
Simplify policy translation between control plane and data plane

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#2904]
This is a proposal to simplify the logical model of the policy translation between the control plane and the data plane

### 1) Generate the policy in the control plane in go using maps.

```golang
// endpointPolicy is the joined policy map that represents the sum of
// all policies that selects this endpoint
type EndpointPolicy map[NumericIdentity][L4Rule]L7Rule
```

this would be stored in the endpoint structure for Ingress and Egress.

For example, let's imagine that we have 5 ingress rules:

```
(FROM -> TO:DESTINATION PORT)
A -> B               // B allows traffic from A
A -> B:80            // B allows traffic from A to port 80
* -> B:83            // B allows traffic from any to port 83
C -> B:81            // B allows traffic from C to port 81
D -> B:81 "GET /foo" // B allows traffic from D to port 81 for http "GET /foo"
```

The ingress `endpointPolicy` map of endpoint B will be:

```golang
endpointPolicy := map[NumericIdentity][L4Rule]L7Rule{
  0: {
    "83/TCP": "Redirect to 0",
  },
  A: {
    "0": "Redirect to 0",
    "80/TCP": "Redirect to 0",
  },
  C: {
    "81/TCP": "Redirect to 0",
  },
  D: {
    "81/TCP": "Redirect to 10000",
  },
}
```

This logic map would be passed to BPF which would be in charge of setting up the policies by maps, #defines, programs, etc.

### 2) BPF datapath's implementation of the `endpointPolicy`:

We would need to change the policy's map logic to have support for a key with 2 elements plus a value of 3 elements

The translation of the previous endpointPolicy would be:

```
+-----------------------+----------------------------+
|         KEY           |            VALUE           |
+-IDENTITY-+-PORT/PROTO-+-REDIRECT-+-BYTES-+-PACKETS-+
|    0     |   83/TCP   |    0     |   0   |    0    |
|    A     |      0     |    0     |   0   |    0    |
|    A     |   80/TCP   |    0     |   0   |    0    |
|    C     |   81/TCP   |    0     |   0   |    0    |
|    D     |   81/TCP   |  10000   |   0   |    0    |
+----------+------------+----------+-------+---------+
```

For every packet received the lookup would be done in the following order:

```
0) Lookup for "IDENTITY-PORT/PROTO":
    IF exists
      IF VALUE.REDIRECT != 0
        do redirect to proxy
      ELSE
        continue bpf datapath
    ELSE
      go to 1)
1) Lookup for "IDENTITY-0" (to any port from identity):
    IF exists
      IF VALUE.REDIRECT != 0
        do redirect to proxy  (This is actually invalid. L7 requires a L4 port)
      ELSE
        continue bpf datapath
    ELSE
      go to 2)
2) Lookup for "0-PORT/PROTO" (to PORT/PROTO from any identity):
    IF exists
      IF VALUE.REDIRECT != 0
        do redirect to proxy
      ELSE
        continue bpf datapath
    ELSE
      go to 3)
3) Lookup for "0-0" (to any port from any identity):
    IF exists
      IF VALUE.REDIRECT != 0
        do redirect to proxy  (This is actually invalid. L7 requires a L4 port)
      ELSE
        continue bpf datapath
    ELSE
      go to 4)
4) DROP PACKET
```

Number of total lookups for each packet from:

```
+-----------+-------------+-------------+
| Packets   |   Lookups   |    Action   |
+-----------+-------------+-------------+
|  A->B:83  |      3      |    ACCEPT   |
|  A->B:80  |      1      |    ACCEPT   |
|  A->B:85  |      2      |    ACCEPT   |
|  C->B:81  |      1      |    ACCEPT   |
|  D->B:81  |      1      | L7 FORWARD  |
|  E->B:80  |      4      |     DROP    |
+-----------+-------------+-------------+
```

**Comment by joestringer** [comment]
```
3) Lookup for "0-0" (to any port from any identity):
    IF exists
      IF VALUE.REDIRECT != 0
        do redirect to proxy
      ELSE
        continue bpf datapath
    ELSE
      go to 4)
```

Is this the case where there's no policy enforced on this endpoint at all? There can't be a redirect in this case, because a redirect requires a destination port to be specified.

**Comment by aanm** [comment]
>because a redirect requires a destination port to be specified.

AFAIK Kafka doesn't need a destination port

**Comment by joestringer** [comment]
> > because a redirect requires a destination port to be specified.

> AFAIK Kafka doesn't need a destination port

According to the docs here, the L7 policy is embedded within an L4 policy, which requires at least the port to be specified:
http://docs.cilium.io/en/latest/policy/language/#layer-7-examples

**Comment by aanm** [comment]
Yeah, it was a misinterpretation on my side from a discussion yesterday on slack. That's correct: redirect requires a destination port to be specified.

**Comment by aanm** [comment]
@joestringer updated for steps `1)` and `3)`

**Comment by joestringer** [comment]
FWIW, `3)` is implemented today by `#undef`ing `POLICY_INGRESS`, and I believe that the L3/L4 level implementation of `2)` is handled as part of `0)`, but userspace generates every known identity + the L4 port and puts that entry into the map. It doesn't populate the proxy_port, though, which I think it should do. It would simplify the logic if the proxy_port was stored in this map instead of being done separately.

**Comment by ianvernon** [comment]
How does CIDR-based policy come into play here?

**Comment by jrajahalme** [comment]
Maybe, only if there is no source security identifier, lookup the source IP on an LPM trie to map it to a security identifier? The control plane could then assign security identifiers for the CIDRs in the policy, the rest of the engine would not need to know about CIDRs?

**Comment by tgraf** [comment]
Please do not call it endpointPolicy but use a more generic name and then embed it into endpoint. We will have L4 and L7 policy depend on CIDR and possibly other things in the future. We should properly abstract it away:

``` go
type PolicyPeer interface {
    [...]
}
```

The `PolicyPeer` can either be an identity, an entity or a CIDR for now, in the future it can also be a service unless we decide to represent services as identities as well. It can represent both the source or the destination, depending on whether it is at ingress or egress.

``` go
type Policy map[PolicyPeer][L4Rule]L7Rule
```

I'm absolutely in favour of decoupling the map updates from the policy generation and move the map updates into `pkg/datapath` and moves all the maps into `pkg/datapath/maps`. We should no longer have BPF specific logic in `pkg/policy` and `pkg/endpoint` in the future.

Update:
I've called out identity and entities separately as we may require different datapath behaviour depending on whether we allow or disallow traffic to/from world, cluster, and host. Having the flexibility of an interface will help.

**Comment by ianvernon** [comment]
Overall, I think this is a step in the right direction; it separates the datapath from the policy package, which is a big issue at this time. Other concerns I have regarding how we compute policy currently:

* Efficiency concerns (policy computation is quite costly)
* Need for in-memory caching in the agent of policy
* Gaps (no tracing for CIDR, no CIDR-dependent L4, tracing in general)
* Lack of a documented test matrix for policy; what are the test cases we currently have that test specific policy configurations that we say we support?
* Removal of Consumables :) 
* How we can develop a model which supports the above ^
