### ISSUE TITLE
CFP: Ability to specify Local IP for BGP Neighbor in CR

### ISSUE THREAD

**Issue by monoxane** [cilium/cilium#29066]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

We are trying to use CIlium with BGP in a completely L3 routed network where there are 2 interfaces per node, currently Cilium will initialise the BGP Neighbor session with a [wildcard address](https://github.com/cilium/cilium/blob/e40fd083a503b21dd3c88e8e21e83814356a3616/pkg/bgpv1/gobgp/server.go#L262), in our experience this is causing GoBGP to initialise this connection from the interface with the lowest metric, not the interface with the best route to that neighbor, causing our secondary interface's BGP session to traverse eth0 > tor1 > spine(s) > tor2 instead of going directly from eth1 > tor2.

**Describe the feature you'd like**

In my understanding all that is required to resolve this problem is the introduction of a nullable LocalAddress field on the `CiliumBGPNeighbor` CRD entity, and if set use the value as `peer.Transport.LocalAddress` in `GoBGPServer.getPeerConfig`, with fall back to the wildcard if null. I'm fairly sure this would instruct GoBGP to use a specified local address/interface for the session and resolve our problems.

**Comment by squeed** [comment]
This is a good observation -- source address selection can be awkward. Is GoBGP's source address selection somehow different than that of `ip route get <dest>`? If so, that is definitely awkward.

One problem with hard-coding source IP is that it generally needs to be per-node. So, ideally, we find a way to configure BGP source address selection in a reasonably generic way.

**Comment by monoxane** [comment]
I can't actually directly inspect the routing table because we use Talos Linux but I'm fairly sure the selection is the same as `ip route get <dest>` because both interfaces have a default route, a local scope route, and specific metrics (`eth0` 1024, `eth1` 2048).

From what I can tell GoBGP will accept _either_ an address or an iface name as LocalAddress, so the CRD field could have the expectation of either an interface name or interface IP which would resolve the need to have a separate PeeringPolicy for each node (we do use a separate policy due to network architecture but its only a handful of nodes and I absolutely understand that it's atypical).

I'm also happy to write code and test this I just haven't worked out where the CRDs and types come from yet... something to do with the OpenAPI specs I think.

**Comment by timbuchwaldt** [comment]
We have this exact issue, @YutaroHayakawa. 
We run bird on each node, then peer locally with MetalLB (legacy) and now Cilium. Our local birds are configured to only allow certain loopback IPs for each of the sessions. We can override this with a `CiliumBGPNodeConfigOverride` object for each node, but this feels very redundant as they all contain the same loopback IP. It would be amazing to support setting the localAddress right in the `CiliumBGPClusterConfig` so we don't have to write an operator to create the override for each node.
