### ISSUE TITLE
CI: Conformance E2E Setup & Test (9, 5.10-20231026.065108...)

### ISSUE THREAD

**Issue by thorn3r** [cilium/cilium#29061]
## CI failure
Hit on https://github.com/cilium/cilium/pull/27520 : https://github.com/cilium/cilium/actions/runs/6788118583/job/18465835688

Seeing a lot of other failures in the recent job history:
https://github.com/cilium/cilium/actions/runs/6797935163
https://github.com/cilium/cilium/actions/runs/6797514393
https://github.com/cilium/cilium/actions/runs/6797075058
https://github.com/cilium/cilium/actions/runs/6795855417
https://github.com/cilium/cilium/actions/runs/6794956035
https://github.com/cilium/cilium/actions/runs/6791851552
https://github.com/cilium/cilium/actions/runs/6790500828

Seems to have cropped up after the this was merged: https://github.com/cilium/cilium/pull/29000

```
[=] Test [node-to-node-encryption]
..
  [-] Scenario [node-to-node-encryption/node-to-node-encryption]
  [.] Action [node-to-node-encryption/node-to-node-encryption/ping-ipv4: cilium-test/host-netns-bdd4b (172.18.0.3) -> cilium-test/host-netns-ps78w (172.18.0.4:0)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/curl-ipv4: cilium-test/host-netns-bdd4b (172.18.0.3) -> cilium-test/echo-other-node-78455455d5-7vnrx (10.244.1.171:8080)]
  ❌ Captured unencrypted pkt (count=11 packets)
```
[cilium-sysdump-9-final.zip](https://github.com/cilium/cilium/files/13297640/cilium-sysdump-9-final.zip)

**Comment by brb** [comment]
See https://github.com/cilium/cilium/issues/29029

**Comment by thorn3r** [comment]
this is a dupe (didn't find the other in my search because it was already closed). rebasing allowed the test to pass, going to close this
