### ISSUE TITLE
Pre-Release Testing During Contribfest

### ISSUE THREAD

**Issue by farazoman** [cilium/cilium#29092]
### Test Category

Documentation

### Test Details

I tested up to the header of https://docs.cilium.io/en/v1.15.0-pre.2/gettingstarted/demo/#apply-and-test-http-aware-l7-policy on the starwars demo. I didn't end up completing the guide

I used https://docs.cilium.io/en/v1.15.0-pre.2/gettingstarted/k8s-install-default/#k8s-install-quick guide for the quick install on minikube (see version below)

```
farazoman@system76-pc:~/code$ minikube version
minikube version: v1.32.0
commit: 8220a6eb95f0a4d75f7f2d7b14cef975f050512d
```

### Time

It took ~30 minutes to test.

### Test Status

Incomplete: Ran out of time

### Cilium Version

farazoman@system76-pc:~/code$ cilium version
cilium-cli: v0.15.12 compiled with go1.21.3 on linux/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.3
cilium image (running): 1.15.0-pre.2

### Kernel Version

Linux system76-pc 6.5.4-76060504-generic #202309191142~1695998943~22.04~070916d~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
@jspaleta Ping, what's actionable here?
