### ISSUE TITLE
Slack New User Registration Not Working

### ISSUE THREAD

**Issue by ozhankaraman** [cilium/cilium#29103]
I try to register a new user to Cilium Slack to join Cilium Workspace even I try with my gmail account using SSO, it resonds like `The email address must match one of the domains listed below. Please try another email.`.  I also tried with Apple SSO sharing my gmail account but still got the same error.

**Comment by thebsdbox** [comment]
Apologies, the underlying token had expired again. This has been fixed and if you head to https://slack.cilium.io you should be able to join the Cilium & eBPF slack instance with a generic email address!

**Comment by ozhankaraman** [comment]
thanks for the link, I confirm that I could able to register to slack workspace via that link, closing issue
