### ISSUE TITLE
Config inconsistency when adding an additional cluster CIDR in native routing mode

### ISSUE THREAD

**Issue by gottwald** [cilium/cilium#29102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an inconsistency in available configuration options if a user wants to add an additional cluster CIDR in a certain deployment scenario.

Relevant config:
```
auto-direct-node-routes: "true"
ipam: cluster-pool
ipv4-native-routing-cidr: 10.244.0.0/16
routing-mode: native
```
The cilium-operator runs with an additional `--cluster-pool-ipv4-cidr=10.244.0.0/16`

In this scenario, if a user needs to expand the cluster IP network space, according to the docs one should not change/grow the value of an already set CIDR, but instead add an additional one.
This works on the IPAM side, since `cluster-pool-ipv4-cidr` is a string slice option, however the routing side `ipv4-native-routing-cidr` only takes a single CIDR as string which doesn't let the user add another CIDR if it's not directly adjacent to the existing one and/or cannot be expressed as one new CIDR.

### Cilium Version

v1.14.3 (including all available newer ones)

### Kernel Version

Linux pool-xcp3y 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.28.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timoreimann** [comment]
Still relevant.

**Comment by timoreimann** [comment]
Appreciate if this could be triaged.

**Comment by timoreimann** [comment]
Keep alive.
