### ISSUE TITLE
CI: Conformance Ginkgo (f19-update) - found error endpoint regeneration failed

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#29108]
## CI failure

Hit on https://github.com/cilium/cilium/pull/29051
Link: https://github.com/cilium/cilium/actions/runs/6825486460/job/18563485231
Sysdump: [test_results-E2E Test (1.19, f19-update).tar.gz](https://github.com/cilium/cilium/files/13320815/test_results-E2E.Test.1.19.f19-update.tar.gz)

Seen on scheduled runs as well: 
* https://github.com/cilium/cilium/actions/runs/6808498669/job/18513085412
* https://github.com/cilium/cilium/actions/runs/6806188619/job/18507111511
* https://github.com/cilium/cilium/actions/runs/6802855511/job/18496939129

```
• Failure in Spec Teardown (AfterEach) [573.044 seconds]
K8sUpdates
/home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
  Tests upgrade and downgrade from a Cilium stable image to master [AfterEach]
  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:515

  Found 1 k8s-app=cilium logs matching list of errors that must be investigated:
  2023-11-10T13:45:10.487646184Z level=error msg="endpoint regeneration failed" containerID=dc7fd23665 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1183 error="endpoint 1183 SecurityIdentity changed during policy regeneration" identity=6117 ipv4=10.0.1.80 ipv6= k8sPodName=default/app1-94b79fb5b-b27qq subsys=endpoint

  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:413
------------------------------

Summarizing 1 Failure:

[Fail] K8sUpdates [AfterEach] Tests upgrade and downgrade from a Cilium stable image to master 
/home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:413
```

**Comment by marseel** [comment]
I will take a look at that as it seems to be the most common reason for CI flakes recently. 
FYI k8s version does not matter as it happens on all k8s versions.

**Comment by marseel** [comment]
I took a look at https://github.com/cilium/cilium/actions/runs/6860299826 run

It seems that `endpoint regeneration failed` is not "fatal" error, it is expected to happen when security identity changes during policy regeneration. So probably we could filter this error and not fail the test, but I guess we do not expect identities to change during upgrades/downgrades.

So now the question becomes why SecurityIdentity changes:
```
before:
security-labels:
  k8s:app: grafana
  k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: cilium-monitoring
  k8s:io.cilium.k8s.policy.cluster: test-upgrade-downgrade
  k8s:io.cilium.k8s.policy.serviceaccount: default
  k8s:io.kubernetes.pod.namespace: cilium-monitoring
after:
  security-labels:
    k8s:app: grafana
    k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: cilium-monitoring
    k8s:io.cilium.k8s.policy.cluster: default
    k8s:io.cilium.k8s.policy.serviceaccount: default
    k8s:io.kubernetes.pod.namespace: cilium-monitoring
```
It seems like `k8s:io.cilium.k8s.policy.cluster` label changes even though `cluster-name` is correctly specified:
```
-cluster-name='test-upgrade-downgrade'" subsys=daemon
....
2023-11-14T07:18:41.187995264Z level=debug msg="UpdateIdentities: Adding a new identity" identity=38192 labels="[k8s:app=migrate-svc-client k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default 

---> k8s:io.cilium.k8s.policy.cluster=default <----


k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:zgroup=migrate-svc]" subsys=policy
```

**Comment by marseel** [comment]
I just double-checked. The wrong identity is created after upgrade to `1.15.0-dev`.
Identity timestamps with `policy.cluster=default`:
```
creationTimestamp: "2023-11-14T07:17:18Z"
```
which corresponds to this upgrade:
```
Tue, 14 Nov 2023 07:16:53 GMT
07:16:53 STEP: Upgrading Cilium to 1.15.0-dev
```

**Comment by brb** [comment]
Nice investigation!

We could set a cluster name the same way as we do for the ci-e2e based tests - https://github.com/cilium/cilium/blob/main/.github/actions/cilium-config/action.yml#L66. I remember I had to set it too, but AFAIK for other test failures during the Cilium upgrade.

**Comment by marseel** [comment]
> We could set a cluster name the same way as we do for the ci-e2e based tests

oh well, I don't think we can for this particular test :sob: 
Anyway, I opened PR which should fix it.
