### ISSUE TITLE
Kafka testing improvements

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2910]
- [ ] Test with multiple brokers
- [ ] Write Ginkgo tests to validate L7 record creation for test app with and without policy enforcement
- [ ] Find more realistic Kafka test applications
- [ ] Benchmark in Ginkgo nightly tests
  - [ ] Count parse errors and report via time series database

**Comment by manalibhutiyani** [comment]
Question about item 1 
`Write Ginkgo tests to validate L7 record creation for test app with and without policy enforcement`
Just want to confirm that this means testing creation of access log records with and without policy.
I think we do not have an api in place to know the access log location. Wondering does this need to be supported first, or go via the unix-socket way or something else in ginkgo?
