### ISSUE TITLE
kpr: show DSR-dispatch mode in cilium-dbg status

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#29132]
When running `cilium-dbg status --verbose` on a cluster with [KPR in DSR mode](https://docs.cilium.io/en/latest/network/kubernetes/kubeproxy-free/#direct-server-return-dsr), it would be great to also show the selected DSR dispatch mode (IP-option, Geneve, IPIP) in the output. See below for an example of the current output.

```
KubeProxyReplacement Details:
  Status:                 Strict
  Socket LB:              Enabled
  Socket LB Coverage:     Full
  Socket LB Protocols:    TCP, UDP
  Devices:                eth0 10.242.0.4 (Direct Routing)
  Mode:                   SNAT
  Backend Selection:      Random
  Session Affinity:       Enabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  XDP Acceleration:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767)
  - LoadBalancer:   Enabled
  - externalIPs:    Enabled
  - HostPort:       Enabled 
```

**Comment by chaunceyjiang** [comment]
I want to pick up this issue. please assign to me.

**Comment by julianwiedmann** [comment]
> I want to pick up this issue. please assign to me.

awesome! Assigned it to you - for a start, it's probably best to track down where the current output gets built. And then just add some more info into that.
