### ISSUE TITLE
Cilium changes source port in TCP SYN-ACK response when `enable-host-firewall: true` is set

### ISSUE THREAD

**Issue by Adrian-St** [cilium/cilium#29154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When setting `enable-host-firewall: true` in the Cilium configmap the Cilium eBPF program attached to the cluster internal network interface starts changing the source port on the SYN-ACK response to the the clients SYN packet and the TCP handshake can't be established. This happens for any traffic, Node to Node as well as Pod to Node traffic.
Removing the bpf program from the interface fixes the issue. Restarting the Cilium daemon does not fix the issue, but restarting the Cilium daemon with  `clean-cilium-bpf-state: "true"` does.

### Cilium Version

Daemon: 1.12.3 1c466d2 2022-10-12T11:33:37+01:00 go version go1.18.6 linux/amd64

### Kernel Version

5.15.0-1022-aws

### Kubernetes Version

v1.23.5

### Sysdump

cilium sysdump (only for the node where the TCP server is running):

[cilium-sysdump-20231114-024856.zip](https://github.com/cilium/cilium/files/13343976/cilium-sysdump-20231114-024856.zip)

### Steps to reproduce:
- Set `enable-host-firewall: true`
- Restart the Cilium daemon on the node where the TCP server is running
- Wait until the Cilium daemon logs show `Conntrack garbage collector interval recalculated`. Not 100% sure if this is necessary, but the issue didn't occur until the log line appeared, so it might be.
- Run a simple Netcat TCP server: `while :; do netcat -l -p 20000; done`
- Run a simple Netcat TCP client: `i=0; while :; do netcat -q 0 -v <server ip> 20000 <<< "$i"; (( i++ )); sleep 0.01; done`
- Run it for bit, sometimes it requires quite a few packets (1000-2000) until the issue starts happening
- At some point the client will get stuck and you will experience the issue described, where the TCP SYN-ACK packet from the server comes from the wrong port

### Example TCP flow:
```
tcpdump -i any -c50 -n -nn host 172.26.46.225 and 172.26.10.232:
02:29:07.202364 IP 172.26.10.232.44354 > 172.26.46.225.20000: Flags [S], seq 4281730853, win 62727, options [mss 8961,sackOK,TS val 683165225 ecr 0,nop,wscale 8], length 0
02:29:07.202401 IP 172.26.46.225.18700 > 172.26.10.232.44354: Flags [S.], seq 3860119699, ack 4281730854, win 62643, options [mss 8961,sackOK,TS val 4257739121 ecr 683165225,nop,wscale 8], length 0
02:29:07.203065 IP 172.26.10.232.44354 > 172.26.46.225.18700: Flags [R], seq 4281730854, win 0, length 0
```

### Cilium configmap:

```
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-create-cilium-node-resource: "true"
  auto-direct-node-routes: "false"
  aws-enable-prefix-delegation: "true"
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-sock: "false"
  bpf-lb-sock-hostns-only: "true"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  clean-cilium-bpf-state: "true"
  cluster-id: "0"
  cluster-name: default
  custom-cni-conf: "true"
  debug: "false"
  direct-routing-device: eth0
  disable-cnp-status-updates: "true"
  disable-endpoint-crd: "false"
  ec2-api-endpoint: ""
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "true"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "true"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-firewall: "true"
  enable-host-legacy-routing: "false"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-masquerade: "false"
  enable-ipv6: "false"
  enable-ipv6-masquerade: "false"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "true"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  eni-tags: '{}'
  hubble-disable-tls: "false"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  install-no-conntrack-iptables-rules: "false"
  instance-tags-filter: ""
  ipam: eni
  ipv4-native-routing-cidr: ""
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ""
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  node-port-range: 3000,5000
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  prometheus-serve-addr: :9962
  proxy-prometheus-port: "9964"
  read-cni-conf: /tmp/cni-configuration/cni-config
  remove-cilium-node-taints: "true"
  set-cilium-is-up-condition: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  subnet-ids-filter: ""
  subnet-tags-filter: ""
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-min-ttl: "3600"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel: disabled
  unmanaged-pod-watcher-interval: "15"
  update-ec2-adapter-limit-via-api: "true"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
  write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conflist
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-03-13T18:26:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cilium-config
  namespace: kube-system
  resourceVersion: "738661055"
  uid: b9a648bb-bd53-4929-9711-379e888001c7
  ```

### Additional info

The `cilium monitor -t drop` doesn't show anything, so I don't think this is expected behaviour. We don't actually need the host firewall, so we disabled it for now, but I'm mostly curious about where in the eBPF program it might do that as I couldn't find anything related to rewriting ports.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
>Daemon: 1.12.3 https://github.com/cilium/cilium/commit/1c466d26ff0edfb5021d024f755d4d00bc744792 2022-10-12T11:33:37+01:00 go version go1.18.6 linux/amd64

That's rather outdated :). Have you tried reproducing this behaviour on a current release?
