### ISSUE TITLE
CI: K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#29166]
## CI failure
Example test -  `E2E Test (1.26, f19-update)`
happens for all k8s versions
Example test runs:
- https://github.com/cilium/cilium/actions/runs/6840898155/job/18600654350
- https://github.com/cilium/cilium/actions/runs/6832792992/job/18583871965
- https://github.com/cilium/cilium/actions/runs/6802855511/job/18496925810
```
 Unexpected missed tail call
  Expected
      <int>: 65
  to be ==
      <int>: 0
```

**Comment by brb** [comment]
@marseel I believe this is the same issue - https://github.com/cilium/cilium/issues/26739. @ti-mo is currently on it.

**Comment by marseel** [comment]
ah yea, thanks. Must have missed this one.
