### ISSUE TITLE
Remote Cluster Status is not returning correct error when connection is not established

### ISSUE THREAD

**Issue by simonwu-sn** [cilium/cilium#29161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I try to establish clustermesh, one remote cluster has network issue and cannot be reached. `cilium clustermesh status` will return error `remote cluster configuration required but not found`, which is incorrect and misleading.

When check the code, I found in cilium repo, the Connected field is not very strict, when rc.backend exists and the status is failing, it will return Connected = true.
```
	status := &models.RemoteCluster{
		Name:        rc.name,
		Ready:       rc.isReadyLocked(),
		Connected:   rc.backend != nil,
		Status:      backendStatus,
		Config:      rc.config,
		NumFailures: int64(rc.failures),
		LastFailure: strfmt.DateTime(rc.lastFailure),
	}
```

And it will cause cilium cli to return incorrect status as the code below:
```
	case !status.Connected:
		return errors.New(status.Status)
	case status.Config == nil:
		return errors.New("remote cluster configuration retrieval status unknown")
	case status.Config.Required && !status.Config.Retrieved:
		return errors.New("remote cluster configuration required but not found")
```

The expect error will be something like `Fail to connect with remote cluster xxx`.

### Cilium Version

1.14.2

### Kernel Version

Linux i-089f351899cc4940f.ap-northeast-1.compute.internal 5.4.241-150.347.amzn2.x86_64 #1 SMP Mon Apr 24 23:27:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.15-eks-4f4795d

### Relevant log output

```shell
❌ 2 Errors:
  ❌ cilium-v4xfk is not connected to cluster xxx: remote cluster configuration required but not found
  ❌ cilium-z57kb is not connected to cluster xxx: remote cluster configuration required but not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Thanks for raising this! What you're saying makes sense - would you be comfortable in opening a PR to improve this behaviour?

**Comment by simonwu-sn** [comment]
I tried but failed. When we enable kvstoremesh along with cluster mesh.

```
			config, err := cmutils.GetClusterConfig(ctx, rc.name, backend)
			if err != nil {
				return err
			}

			if config == nil && requireConfig {
				return errors.New("cluster configuration expected to be present but not found")
			}
```

The logic here try to get cluster configuration from remote, but when if fails to retrieve cluster config, it will set cluster-config as nil instead of throwing an error. Then I got lost there.

**Comment by simonwu-sn** [comment]
It seems `st, err := e.determineEndpointStatus(ctx, ep)` in `func (e *etcdClient) statusChecker()` is not returning correct status when connection is failed.

**Comment by simonwu-sn** [comment]
```
   common-stg-0-prd-tokyo: not-ready, 0 nodes, 0 endpoints, 0 identities, 0 services, 0 failures (last: never)
   └  etcd: 1/1 connected, leases=0, lock leases=0, has-quorum=true: https://clustermesh-apiserver.kube-system.svc:2379 - 3.5.4 (Leader)
   └  remote configuration: expected=true, retrieved=false
   └  synchronization status: nodes=false, endpoints=false, identities=false, services=false
   common-stg-1-prd-tokyo: not-ready, 0 nodes, 0 endpoints, 0 identities, 0 services, 0 failures (last: never)
   └  etcd: 1/1 connected, leases=0, lock leases=0, has-quorum=true: https://clustermesh-apiserver.kube-system.svc:2379 - 3.5.4 (Leader)
   └  remote configuration: expected=true, retrieved=false
   └  synchronization status: nodes=false, endpoints=false, identities=false, services=false`
   common-stg-0-prd-tokyo: not-ready, 0 nodes, 0 endpoints, 0 identities, 0 services, 0 failures (last: never)
   └  etcd: 1/1 connected, leases=0, lock leases=0, has-quorum=true: https://clustermesh-apiserver.kube-system.svc:2379 - 3.5.4 (Leader)
   └  remote configuration: expected=true, retrieved=false
   └  synchronization status: nodes=false, endpoints=false, identities=false, services=false
   common-stg-1-prd-tokyo: not-ready, 0 nodes, 0 endpoints, 0 identities, 0 services, 0 failures (last: never)
   └  etcd: 1/1 connected, leases=0, lock leases=0, has-quorum=true: https://clustermesh-apiserver.kube-system.svc:2379 - 3.5.4 (Leader)
   └  remote configuration: expected=true, retrieved=false
   └  synchronization status: nodes=false, endpoints=false, identities=false, services=false
```

Even the connection fails, etcd should 1/1 connected

**Comment by giorio94** [comment]
Hey @simonwu-sn, please notice that, when using kvstoremesh, the Cilium agents connect to the local clustermesh-apiserver, while it is kvstoremesh that connects to the remote ones. This means that from the agents point of view the connection to etcd succeeds even in case kvstoremesh cannot connect to one of the remote clusters (which is why the CLI reports connected as status). But then they expect the config key to be present for each cluster, although it is not because kvstoremesh never connected to that one, hence the `remote cluster configuration required but not found` error.

One improvement could be to somehow propagate the information about whether kvstoremesh successfully connected to the remote cluster to the agents, and then display also that through the CLI. That introduces a possible chicken and egg problem though, because the agent needs the cilium config to know whether kvstoremesh is actually enabled or not.

**Comment by giorio94** [comment]
> Can we revise remote cluster configuration required but not found to not found or not valid. It's more verbose but less confusing.

I'm not sure that would be better, as the cluster configuration for the given cluster is actually not found in this case. It can also happen that it is not valid (because two clusters are using the same ClusterID), but that's a different situation (and error message).

**Comment by simonwu-sn** [comment]
Yeah, then propagating the error in kvmesh may suit the case.
