### ISSUE TITLE
Excessive CPU usage when utilizing dnsproxy

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#29175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upgraded to v1.14.4 and now some agents are utilizing all spare CPU cycles (overall average increase of 20x CPU usage)

### Cilium Version

Client: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64
Daemon: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64

### Kernel Version

5.15.0-1049-aws #54~20.04.1-Ubuntu SMP Fri Oct 6 22:04:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.17-eks-4f4795d", GitCommit:"af19e454a15b5eb16d9f29d4d2361b3050ac78a6", GitTreeState:"clean", BuildDate:"2023-10-20T23:22:36Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cpu_profile.zip](https://github.com/cilium/cilium/files/13359953/cpu_profile.zip)
[heap_profile.zip](https://github.com/cilium/cilium/files/13362713/heap_profile.zip)

### Anything else?
Upgrade started just after 19:00...
`rate(go_memstats_mallocs_total)`:
![Screenshot 2023-11-14 at 8 14 21 PM](https://github.com/cilium/cilium/assets/395054/19a0012c-c45d-4bf8-95d0-459c121852cd)

`rate(cilium_process_cpu_seconds_total)`:
![Screenshot 2023-11-14 at 8 14 40 PM](https://github.com/cilium/cilium/assets/395054/dc75bb90-7fe0-4572-a7ca-e375ae374519)

I believe it's related to https://github.com/cilium/cilium/pull/29086 per the cpu profiles

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dctrwatson** [comment]
Seems restarting helps for awhile. But then the agents start showing those step increases again.

**Comment by dctrwatson** [comment]
also seems like v1.13.9 may also be affected: https://cilium.slack.com/archives/C1MATJ5U5/p1700007641737079

**Comment by aanm** [comment]
Running the changes done on PR https://github.com/cilium/cilium/pull/29180 we were able to correlate the timeouts to the CPU usage
```
aanm err type is *net.OpError: read udp 10.254.98.163:51497->10.254.95.152:53: i/o timeout
```

**Comment by slenky** [comment]
I have upgraded from 1.13.3 to 1.14.4 and have the same situation. Is it possible to rollback safely to the previous version? Or is it possible to mitigate this issue without rollback? Thanks

**Comment by macmiranda** [comment]
We've upgraded to `quay.io/cilium/cilium:v1.14.4@sha256:4981767b787c69126e190e33aee93d5a076639083c21f0e7c29596a519c64a2e`

You can see the CPU consumption below up to the point we reverted to `v.1.14.3
