### ISSUE TITLE
Remove CIDR limit on older kernels

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2920]
On kernels lacking LPM maps, we generate code to simulate an LPM map. Due to the code generation aspect, we have to enforce an upper limit on number of matches. Some users have run into this limit. I suggest to fall back to a exact match hash table and generate all allowed IPs instead.

**Comment by jrajahalme** [comment]
Just brainstorming on the design:
- Have a single map for each IP version where the key is the prefix including the length.
- We don't really need the longest prefix match, but might still do the lookups on any given address for all prefix lengths from longest to shortest, masking the packet's address to the given length and doing the lookup.
- Looking up 128 times for IPv6 is very wasteful, so we probably should inline the prefix lengths that exist on the map to the program and only look up for those lengths. This implies that for an empty map we do no lookups.
- Should do the above for IPv4 as well.

**Comment by joestringer** [comment]
@jrajahalme thanks for the suggestions, I implemented the datapath side of this on a local tree. Seems like we can support up to about 90 prefixes with current code complexity and LLVM 7 code generation. Pretty straightforward patch on that side. I'm guessing that when we move to support CIDR-dependent L4 this number of prefixes will drop, probably in half.

Need to put together the userspace plumbing for this though:
* [x] Switch L3Policy via `CIDR{4,6}_{E,IN}GRESS_MAPPINGS` to use a CIDR map of type `BPF_MAP_TYPE_HASH` when LPM is not available
* [x] Track the prefixes in use and currently configured and define those in the BPF generation
* [x] Figure out how to signal warning to the user if the maximum supported number of prefixes is exceeded
