### ISSUE TITLE
CFP: Cilium Helm Chart - Add hubble-exporter flags

### ISSUE THREAD

**Issue by sumeet-zuora** [cilium/cilium#29203]
## Cilium Feature Proposal
        
Current helm chart, does not consider the https://docs.cilium.io/en/latest/observability/hubble-exporter/. which includes number of flags which need to be added
Some example are

```
hubble-export-file-path
hubble-export-allowlist

```

**Describe the feature you'd like**

Flags inside the vaules.yaml to set hubble exporter configurations

**Comment by lambdanis** [comment]
This is implemented in https://github.com/cilium/cilium/pull/28873 it seems

**Comment by chancez** [comment]
This has been implemented
