### ISSUE TITLE
Cilium connectivity test failure for `allow-all-with-metrics-check`

### ISSUE THREAD

**Issue by vipul-21** [cilium/cilium#29213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With the introduction of the commit: https://github.com/cilium/cilium/commit/f8e94721fcebe4f9e0d45d4d914949ffb7467ad1, the cilium metric for `forward_count_total`, `forward_bytes_total`, `drop_bytes_total`, `drop_count_total` all were changed to have a subsystem in their metric name i.e. `cilium_datapath_forward_count_total`. This broke the existing cilium cli connectiivty that was looking for the non subsystem metric name. i.e `cilium_forward_count_total`
Error: 
```
  🐛 failed to check metrics on node aks-nodepool1-10981532-vmss000000: metric cilium_forward_count_total has not been retrieved after action
``` 

There are 2 ways we can fix this:
1. we update the cilium-cli with the new metric name, and make sure different versions of cilium cli support the different version of cilium.
2. We change the metric name to include subsystem as `""` so that the metric name remain the same and can be backward compatible.

I would like to take up the fix for this, but wanted to know the correct way forward before I create a PR

### Cilium Version

1.15.0

### Kernel Version

Linux aks-nodepool1-10981532-vmss000000 5.15.0-1051-azure #59-Ubuntu SMP Wed Oct 11 18:49:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.27.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Thanks for the report!

@carnerito / @derailed could you advise here?

**Comment by carnerito** [comment]
This change was not intended, I think we should remove the subsystem information from metric names. I've opened [PR](https://github.com/cilium/cilium/pull/29226) that fixes this.
