### ISSUE TITLE
StringSlice no longer works for values splitted by spaces on hive cells

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#29210]
During the 1.15 development cycle it was discovered that flags that can accepted multiple values, more specifically registered with `StringSlice` in hive cells, can no longer recognize their values separated by spaces.

Historically, the values defined on the Cilium's ConfigMap are separated by values while the values defined on a CLI flag are separated by commas. We should keep this known behavior unless that we can guarantee that all values of the flags, no matter which format, can only be separated by commas.

Thus, for 1.15, Cilium should still be able to parse spaces for ConfigMap values and commas for CLI flags. Once we have transitioned all flags into hive cells then we can decide if we want to change this behavior and not allowing spaces.

**Comment by michi-covalent** [comment]
related:

- https://github.com/cilium/cilium/pull/29564
- https://github.com/cilium/cilium/pull/28922

**Comment by joestringer** [comment]
I've requested changes for all the PRs I could find related to this, because I think we're seeing one-by-one attempts to fix _some_ options that we notice have broken, and I'm concerned that we may miss some options or make them inconsistent between one another.

**Comment by joestringer** [comment]
@joamaki is this on your radar? Seems like it's assigned to you but I see no acknowledgement. I know that @michi-covalent , @tommyp1ckles and @mhofstetter have all also been looking at this problem. Do we have an opinion about how to apply the fix consistently for all affected configs?

**Comment by joamaki** [comment]
#29848 should address this. Reviews of the approach I took would be much appreciated.

**Comment by tommyp1ckles** [comment]
Can confirm that @joamaki 's changes fix the issue I was trying to address the issue I was trying to fix here: https://github.com/cilium/cilium/pull/29564/commits/95066a4b872d0cc065f8148cf52f2ed7d9e89303

Will close that one

**Comment by chancez** [comment]
Just hit this in https://github.com/cilium/cilium/pull/35206. Unfortunately the fix doesn't seem to work for our case where we're using `,` as a separator in our config values.
