### ISSUE TITLE
Add support for kube-aws

### ISSUE THREAD

**Issue by mmr** [cilium/cilium#2921]
### Add support for kube-aws

Genereate the required `ConfigMap` with the correct `etcdEndpoints` to make it easier to use `Cilium` with `kube-aws`

**Comment by mumoshu** [comment]
Hi! Just curious, but I guessed that #4314 would make it unnecessary to set etcdEndpoints that is special to kube-aws. Am I correct?

**Comment by tgraf** [comment]
> Hi! Just curious, but I guessed that #4314 would make it unnecessary to set etcdEndpoints special that is special to kube-aws. Am I correct?

Yes, we are still testing but that is the motivation behind #4314
