### ISSUE TITLE
Messages generated inside controllers are not logged

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#29215]
1. Install Cilium
2. Check `kubectl logs -n kube-system ds/cilium  | grep endpointsynchronizer` and the result is empty. The logs should contain at least one message similar to:
```
level=debug msg="Skipping CiliumEndpoint update because it has no k8s cep name" containerID= containerInterface= controller="sync-to-k8s-ciliumendpoint (3394)" datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=3394 identity=4 ipv4=10.244.0.118 ipv6= k8sPodName=/ subsys=endpointsynchronizer
```

Did a bisect which resulted on 52c06e1b3b05eeaf23a19c29975dbe2cad170db6 to be the first bad commit.

/cc @learnitall

**Comment by learnitall** [comment]
I tried doing a manual review of the changes in https://github.com/cilium/cilium/commit/52c06e1b3b05eeaf23a19c29975dbe2cad170db6 and adding some more debug logs to understand how this regression could have occurred... and came up empty. I see that for some reason the endpoint's logger has its level set incorrectly- at various points it's either set to `Info` or `Panic`, but not `Debug`. Tomorrow I'll try slowly rolling back changes from the bad commit to narrow down the culprit.

**Comment by learnitall** [comment]
It looks like the culprit change was 

```diff
diff --git a/pkg/endpoint/log.go b/pkg/endpoint/log.go
index fcde76edad..7e98202722 100644
--- a/pkg/endpoint/log.go
+++ b/pkg/endpoint/log.go
@@ -108,6 +108,10 @@ func (e *Endpoint) UpdateLogger(fields map[string]interface{}) {
        // If this endpoint is not set to debug, it will use the log level set by the user.
        if e.Options != nil && e.Options.IsEnabled(option.Debug) {
                baseLogger.SetLevel(logrus.DebugLevel)
-       } else {
-               // Debug mode takes priority; if not in debug, check what log level user
-               // has set and set the endpoint's log to log at that level.
-               baseLogger.SetLevel(logging.DefaultLogger.Level)
        }
 
        // When adding new fields, make sure they are abstracted by a setter
```

> https://github.com/cilium/cilium/commit/52c06e1b3b05eeaf23a19c29975dbe2cad170db6#diff-89ac7b0e901d12185e606751ca4b265614b4c582f706c0fa3d753b6afbf0aa5dL101-L104

I removed these lines in https://github.com/cilium/cilium/commit/52c06e1b3b05eeaf23a19c29975dbe2cad170db6 because the `baseLogger` variable is initialized with the return value of `logging.InitializeDefaultLogger`, and I assumed that the logger this function returns would always match the value of `logging.DefaultLogger`. This is not the case.

The body of `logging.InitializeDefaultLogger` looks like this:

```
