### ISSUE TITLE
Cilium 1.14.4: DNS problems after update from 1.14.3

### ISSUE THREAD

**Issue by opaetzel** [cilium/cilium#29238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We updated cilium from 1.14.3 to 1.14.4 on our Kubernetes cluster and DNS failed to work for some workflows. When we rolled back to 1.14.3 the issue disappeared.
We run cilium in CNI chaining mode with AWS CNI. Also, audit mode is currently turned on, so nothing should be blocked because of policies. We looked into the hubble flow verdict logs and there were no DROPPED or AUDIT flows to the DNS server.  
The behavior was that DNS queries would hang forever and eventually time out. For some workloads this was happening every time, others could sometimes complete the DNS queries and others couldn't.

I'm sorry I couldn't gather any more information, if you need any log output, I will try and get it for you. 

### Cilium Version

1.14.4

### Kernel Version

Linux 6.2.0-1015-aws #15~22.04.1-Ubuntu SMP Fri Oct  6 21:37:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.17

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@opaetzel thank you for the bug report, can you try out `quay.io/cilium/cilium-ci:d40c54bd2e6acf7a848746936a4194de4e5ffef0` built from https://github.com/cilium/cilium/pull/29240?

**Comment by opaetzel** [comment]
I will try it out this evening (CET)

**Comment by opaetzel** [comment]
I just tried `quay.io/cilium/cilium-ci:d40c54bd2e6acf7a848746936a4194de4e5ffef0` and unfortunately, it did not fix the issue. We are for example getting errors when using yarn:

**Comment by aanm** [comment]
@opaetzel Thank you, can you try out `quay.io/cilium/cilium-ci:49bce683b6d95ef3d92d38519ecbc8074e633474` built from https://github.com/cilium/cilium/pull/29180?

**Comment by jan-kantert** [comment]
Beside this issue we also see high CPU usage on some clusters with 1.14.4. Downgrading to 1.14.3 fixed that as well.

**Comment by aanm** [comment]
@jan-kantert thanks for the info, we are aware of the CPU usage and it will get fixed in 1.14.5.

**Comment by opaetzel** [comment]
Hi @aanm I just tried `quay.io/cilium/cilium-ci:49bce683b6d95ef3d92d38519ecbc8074e633474` and could not replicate the DNS issue, so it seems #29180 helps with this

**Comment by aanm** [comment]
@opaetzel can you test out `quay.io/cilium/cilium-ci:7ba68aaaa4964a64961b309baf32115aecb02d2e` built from https://github.com/cilium/cilium/pull/29240?

**Comment by opaetzel** [comment]
I just tested `quay.io/cilium/cilium-ci:7ba68aaaa4964a64961b309baf32115aecb02d2e` and got the same DNS issues as with 1.14.4

**Comment by jrajahalme** [comment]
Use the `7ba68aaaa4964a64961b309baf32115aecb02d2e` image with debug logs, thanks!

**Comment by opaetzel** [comment]
@jrajahalme 7ba68aaaa4964a64961b309baf32115aecb02d2e doesn't seem to exist any more. It looks like I was too slow. I have a log file from last week created with cilium 1.14.4, though. Maybe they are of help, too. The domain that could not be resolved was `registry.yarnpkg.com`. 
[cilium_logs_cleaned.txt](https://github.com/cilium/cilium/files/13562722/cilium_logs_cleaned.txt)

**Comment by opaetzel** [comment]
OK I was wrong and the image is still there. But now I am having trouble capturing all the logs in time. Maybe the 1.14.4 logs will help you already. Otherwise, I will try again of course.

**Comment by opaetzel** [comment]
Hi @jrajahalme do you have any news on this? Should it be fixed in cilium 1.14.6?

**Comment by opaetzel** [comment]
I tested with 1.14.6 and could not replicate the error
