### ISSUE TITLE
Update Installation on OpenShift OKD docu

### ISSUE THREAD

**Issue by egrosdou** [cilium/cilium#29242]
Documentation update: https://docs.cilium.io/en/v1.14/installation/k8s-install-openshift-okd/#k8s-install-openshift-okd

- cilium/cilium-olm points to an archived project
- The latest version 1.14.4 cannot be found under manifests. Version 1.14.3 is available instead.

**Comment by julianwiedmann** [comment]
Could you please open a PR to update the [project link](https://github.com/cilium/cilium-olm/commit/d595d9b949ee9eab66968cd5e32636bb79f2fe9d)?

The `1.14.4` release might still be cooking, Openshift sometimes lags behind a few days ...

**Comment by julianwiedmann** [comment]
> The `1.14.4` release might still be cooking, Openshift sometimes lags behind a few days ...

... and you can follow along here: https://github.com/isovalent/olm-for-cilium/pull/46 :)

**Comment by egrosdou01** [comment]
Thanks @julianwiedmann. PR was created. QQ: are you aware if the documentation needs a refresh? Looking at the screenshots, the example was created for Cilium v.1.12.2.

**Comment by julianwiedmann** [comment]
> Thanks @julianwiedmann. PR was created.

:pray: 

> QQ: are you aware if the documentation needs a refresh? Looking at the screenshots, the example was created for Cilium v.1.12.2.

No idea, sorry. But if any parts are out-dated, we would surely appreciate PRs that improve the docs again :). These sort of "integration" topics typically rely on the relevant user base to keep things in optimal shape.

**Comment by egrosdou01** [comment]
I will double-check on the Cilium Slack channel. Once done, I will update the needed documentation. Thanks for the help.
