### ISSUE TITLE
Nothing like `TraceContext`

### ISSUE THREAD

**Issue by StLeoX** [cilium/cilium#29258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Environment: 
cilium version
cilium image (default): v1.14.2

run:
```
grpcurl -plaintext -d '' 127.0.0.1:24377 observer.Observer.GetFlows
```

GET:
```
{
  "flow": {
    "time": "2023-11-19T12:16:04.150900943Z",
    "verdict": "FORWARDED",
    "ethernet": {
      "source": "ae:0a:bd:d8:62:a5",
      "destination": "12:87:62:04:89:ae"
    },
    "IP": {
      "source": "10.0.0.27",
      "destination": "10.0.0.194",
      "ipVersion": "IPv4"
    },
    "l4": {
      "TCP": {
        "sourcePort": 3000,
        "destinationPort": 55868,
        "flags": {
          "SYN": true,
          "ACK": true
        }
      }
    },
    "source": {
      "ID": 559,
      "identity": 61182,
      "namespace": "cilium-monitoring",
      "labels": [
        "k8s:app=grafana",
        "k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring",
        "k8s:io.cilium.k8s.policy.cluster=default",
        "k8s:io.cilium.k8s.policy.serviceaccount=default",
        "k8s:io.kubernetes.pod.namespace=cilium-monitoring"
      ],
      "podName": "grafana-84476dcf4b-nncj8",
      "workloads": [
        {
          "name": "grafana",
          "kind": "Deployment"
        }
      ]
    },
    "destination": {
      "identity": 1,
      "labels": [
        "reserved:host",
        "reserved:kube-apiserver"
      ]
    },
    "Type": "L3_L4",
    "nodeName": "master",
    "reply": true,
    "eventType": {
      "type": 4,
      "subType": 3
    },
    "trafficDirection": "INGRESS",
    "traceObservationPoint": "TO_STACK",
    "isReply": true,
    "uuid": "d0454598-a9e6-458c-bcbd-d82f0c2dd3f5",
    "Summary": "TCP Flags: SYN, ACK"
  },
  "nodeName": "master",
  "time": "2023-11-19T12:16:04.150900943Z"
}
...
```

In this flow instance, I get nothing like TraceContext, but TraceContext is described in 
 cilium/api/v1/flow/.

### Cilium Version

v1.14.2

### Kernel Version

Linux master 5.4.0-99-generic #112~18.04.1-Ubuntu SMP Thu Feb 3 14:09:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[aaa.txt](https://github.com/cilium/cilium/files/13403145/aaa.txt)

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rolinh** [comment]
```
In this flow instance, I get nothing like TraceContext, but TraceContext is described in
cilium/api/v1/flow/.
```
TraceContext is added to L7 (HTTP) flows when a trace context header is found. You need to enable L7 visibility to capture L7 flows and then, assuming your application uses HTTP and is instrumented, you should see them appear in Hubble flows.
