### ISSUE TITLE
ClusterIP services do not work on secondary interfaces

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#29299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If additional ENIs are attached to a node, all Pods that are assigned IPs for that ENI cannot use ClusterIP services until cilium is restarted

### Cilium Version

1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64

### Kernel Version

5.15.0-1049-aws #54~20.04.1-Ubuntu SMP Fri Oct 6 22:04:33 UTC 2023 x86_64

### Kubernetes Version

v1.24.17-eks-4f4795d

### Anything else?

Also required adding `--devices=ens+` to the agent (the default value seems to only detect the primary interface)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
Have you followed https://docs.cilium.io/en/stable/network/concepts/routing/#aws-eni specifically the configuration section?

**Comment by dctrwatson** [comment]
@lmb yes, these are clusters that have been running Cilium for years. I'm not exactly sure when we started using multiple ENIs after switching to Prefix Delegation (it's been an ongoing project to increase pod density of nodes), so I can't be sure when this issue started unfortunately.

**Comment by lmb** [comment]
Okay, thanks for confirming. You're saying this used to work but now it's broken, or it never worked and you noticed it just now?

**Comment by dctrwatson** [comment]
> You're saying this used to work but now it's broken, or it never worked and you noticed it just now?

It definitely used to work. But since we switched to prefix delegation, we stopped using secondary ENIs for a long while.

**Comment by dylandreimerink** [comment]
@dctrwatson did you explicitly enable the runtime device detection feature? Its not enabled by default since its still experimental, its gated behind the `enableRuntimeDeviceDetection` helm value / `--enable-runtime-device-detection` flag.

**Comment by dctrwatson** [comment]
> @dctrwatson did you explicitly enable the runtime device detection feature? Its not enabled by default since its still experimental, its gated behind the `enableRuntimeDeviceDetection` helm value / `--enable-runtime-device-detection` flag.

Wait... multiple devices isn't a supported feature anymore?

**Comment by dylandreimerink** [comment]
Multiple devices are still supported. But the feature to detect when a new device has been added while the agent is running is new. Not every part of Cilium can handle the signal which is why its behind a flag and disabled by default. To my knowledge initialization of ENI's is one of the functions that does handle this signal if the feature is enabled.

**Comment by dctrwatson** [comment]
Seems that `--enable-runtime-device-detection` does indeed fix the issue at least...

**Comment by dylandreimerink** [comment]
> I'm very curious how this used to work then.

Is it possible you were running in kube-proxy mode before? In non-KPR mode it does work out of the box

**Comment by dctrwatson** [comment]
> Is it possible you were running in kube-proxy mode before? In non-KPR mode it does work out of the box

We've been running in `strict` mode for at least couple years now. If it's related to KBR, could we finally caught up to a kernel version that enabled a new feature that we didn't have before?
