### ISSUE TITLE
GKE: Warning `Unable to get node resource`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#29330]
Observed on https://github.com/cilium/cilium/commit/7cfa82b1ddeb1fa2a690eeb52295791cfe1fc5b7:
```
level=warning msg="Unable to get node resource" error="ciliumnodes.cilium.io \"gke-paul-cluster-default-pool-7f08f208-7p4z\" not found" subsys=nodediscovery
```

[cilium-sysdump-20231122-153249.zip](https://github.com/cilium/cilium/files/13440888/cilium-sysdump-20231122-153249.zip)

### Reproduction steps
```
NATIVE_CIDR="$(gcloud container clusters describe "${NAME}" --zone "${ZONE}" --format 'value(clusterIpv4Cidr)')"
echo $NATIVE_CIDR
helm install cilium ./cilium \
        --namespace kube-system \
        --set image.repository=docker.io/pchaigno/cilium-dev \
        --set image.tag=test \
        --set image.useDigest=true \
        --set image.digest=sha256:8d96a9589fe195e9f2c0a95c7666bad34c58019e232ec833dc52a3da11c91585 \
        --set operator.image.repository=docker.io/pchaigno/operator \
        --set operator.image.suffix="" \
        --set operator.image.tag=test \
        --set operator.image.useDigest=true \
        --set operator.image.genericDigest=sha256:fe5f886d3e18d9e9ec5ae90756915bb2d1cdad86796e20d9b24e52b24db214fc \
        --set nodeinit.enabled=true \
        --set nodeinit.reconfigureKubelet=true \
        --set nodeinit.removeCbrBridge=true \
        --set cni.binPath=/home/kubernetes/bin \
        --set gke.enabled=true \
        --set ipam.mode=kubernetes \
        --set ipv4NativeRoutingCIDR=$NATIVE_CIDR \
        --set debug.enabled=true
```
Those two images correspond to https://github.com/cilium/cilium/commit/7cfa82b1ddeb1fa2a690eeb52295791cfe1fc5b7.

**Comment by giorio94** [comment]
At first sight the `"Unable to get node resource"` error looks benign, and triggered because we are not ignoring NotFound errors [here](https://github.com/cilium/cilium/blob/7cfa82b1ddeb1fa2a690eeb52295791cfe1fc5b7/pkg/nodediscovery/nodediscovery.go#L380-L382). My understanding is that the CiliumNode is not necessarily expected to be present at that point, except for some IPAM modes which create it on their own. It is also possible that the CiliumNode store is lagging behind, and it is not yet containing the given CiliumNode although already present in k8s.

**Comment by joestringer** [comment]
If we think this warning is benign, then can we detect the benign scenario and avoid emitting warnings? Or back off and retry to ensure that the warning/error is only reported after repeated attempts once we have the confidence to believe that there is a warning? This behaviour can confuse users and make them think something is going wrong.

Also worth noting that ideally warnings and errors should be actionable by the user. Reporting that a node resource cannot be found doesn't point out any consequences or what someone should do if this occurs.

**Comment by danehans** [comment]
@joestringer I'll assign myself this issue try reproducing using https://github.com/cilium/cilium/commit/7cfa82b1ddeb1fa2a690eeb52295791cfe1fc5b7 and the latest build. If the issue still exists, I'll fix the benign error.
