### ISSUE TITLE
[egressgw] run CI on 5.4 kernel

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#29346]
Per our current docs, EgressGW requires a `5.2+` kernel (code-wise this is actually `HAVE_LARGE_INSN_LIMIT`). It would be good to validate that it actually works on the limited BPF feature set that such an older kernel provides. In particular for scenarios where `HAVE_FIB_NEIGH` is not set.

**Comment by julianwiedmann** [comment]
@brb any chance that you still have context on the [matrix setup](https://github.com/cilium/cilium/blob/f3cfc638eb80a576d2064ee2952651eed6b53acb/.github/workflows/conformance-e2e.yaml#L86)? The 5.4 config is fairly low on features, is that sufficient to cover real-world usage? Or should we have an additional config with more advanced features?

**Comment by brb** [comment]
The thinking was to test on all LTS kernels. We could just add more configs, as they all run in parallel.
