### ISSUE TITLE
CI: K8sAgentPolicyTest Multi-node policy test validates fromEntities policies with remote-node identity disabled

### ISSUE THREAD

**Issue by lmb** [cilium/cilium#29362]
### Test Name

```shell
K8sAgentPolicyTest Multi-node policy test validates fromEntities policies with remote-node identity disabled Allows from all hosts with cnp fromEntities host policy
```

### Failure Output

```shell
Cilium validation failed: 4m0s timeout expired: Last polled error: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-rxm99': Exitcode: 1 \nErr: exit status 1\nStdout:\n \t \nStderr:\n \t Defaulted container \"cilium-agent\" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)\n\t Error: Cannot get status/probe: Put \"http://localhost/v1beta/status/probe\": context deadline exceeded\n\t \n\t command terminated with exit code 1\n\t \n
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:453
cilium pre-flight checks failed
Expected
    <*errors.errorString | 0xc00136e980>: {
        s: "Cilium validation failed: 4m0s timeout expired: Last polled error: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-rxm99': Exitcode: 1 \nErr: exit status 1\nStdout:\n \t \nStderr:\n \t Defaulted container \"cilium-agent\" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)\n\t Error: Cannot get status/probe: Put \"http://localhost/v1beta/status/probe\": context deadline exceeded\n\t \n\t command terminated with exit code 1\n\t \n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.19/src/github.com/cilium/cilium/test/k8s/assertion_helpers.go:157
```

### Standard Output

```shell
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
⚠️  Number of "context deadline exceeded" in logs: 18
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Cilium pods: [cilium-5rfmp cilium-bmj26]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                         Ingress   Egress
test-k8s2-794579c97-4kxgb   false     false
testclient-2dqwt            false     false
testclient-tddsl            false     false
testds-glrnv                false     false
testds-mh79r                false     false
coredns-85fbf8f7dd-wtzx8    false     false
Cilium agent 'cilium-5rfmp': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 39 Failed 0
Cilium agent 'cilium-bmj26': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 29 Failed 0
```

### Standard Error

```shell
Truncated
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.19/267/testReport/junit/Suite-k8s-1/21/K8sAgentPolicyTest_Multi_node_policy_test_validates_fromEntities_policies_with_remote_node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy/
- ZIP file(s): 
[319c881b_K8sAgentPolicyTest_Multi-node_policy_test_validates_fromEntities_policies_with_remote-node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy.zip](https://github.com/cilium/cilium/files/13458026/319c881b_K8sAgentPolicyTest_Multi-node_policy_test_validates_fromEntities_policies_with_remote-node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy.zip)

### Anything else?

Hit three times in rapid succession: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.19/256/testReport/junit/Suite-k8s-1/20/K8sAgentPolicyTest_Multi_node_policy_test_validates_fromEntities_policies_with_remote_node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy/ and https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/316/testReport/junit/Suite-k8s-1/22/K8sAgentPolicyTest_Multi_node_policy_test_validates_fromEntities_policies_with_remote_node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy/

**Comment by nbusseneau** [comment]
This was hit in #29640.

- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.19/273/testReport/junit/Suite-k8s-1/19/K8sAgentPolicyTest_Multi_node_policy_test_validates_fromEntities_policies_with_remote_node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy/
  - [4e192946_K8sAgentPolicyTest_Multi-node_policy_test_validates_fromEntities_policies_with_remote-node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy.zip](https://github.com/cilium/cilium/files/13587199/4e192946_K8sAgentPolicyTest_Multi-node_policy_test_validates_fromEntities_policies_with_remote-node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy.zip)
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.19/281/testReport/junit/Suite-k8s-1/21/K8sAgentPolicyTest_Multi_node_policy_test_validates_fromEntities_policies_with_remote_node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy/
  - [5c4452a3_K8sAgentPolicyTest_Multi-node_policy_test_validates_fromEntities_policies_with_remote-node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy.zip](https://github.com/cilium/cilium/files/13587201/5c4452a3_K8sAgentPolicyTest_Multi-node_policy_test_validates_fromEntities_policies_with_remote-node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy.zip)

**Comment by giorio94** [comment]
Hit in https://github.com/cilium/cilium/pull/29847 as well: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-4.19/304/testReport/junit/Suite-k8s-1/24/K8sAgentPolicyTest_Multi_node_policy_test_validates_fromEntities_policies_with_remote_node_identity_disabled_Allows_from_all_hosts_with_cnp_fromEntities_host_policy/
