### ISSUE TITLE
Cilium 1.14.4 - AWS EKS - Masquerade with overlay mode not working

### ISSUE THREAD

**Issue by pdrastil** [cilium/cilium#29363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,
I'm looking into swapping AWS VPC CNI with Cilium to get L7 policies working, however I'm running into issues with overlay setup with secondary ENIs on different subnets in 3 AZs. EKS cluster starts without any nodes and all provisioning is done dynamically with Karpenter which makes the issues reproducible every time I build a new cluster. Nodes are using latest Bottlerocket OS AMI.

Config section that doesn't change across modes:

```yaml
routingMode: native

cni:
  install: true
  customConf: true
  configMap: cni-configuration

eni:
  enabled: true
  updateEC2AdapterLimitViaAPI: true
  awsReleaseExcessIPs: true
  awsEnablePrefixDelegation: true

ipam:
  mode: eni

endpointRoutes:
  enabled: true

kubeProxyReplacement: true

nodePort:
  enabled: true

socketLB:
  enabled: false
  # -- Disable socket lb for non-root ns. This is used to enable Istio routing rules.
  hostNamespaceOnly: true
```

The value for `k8sServiceHost` is `replace(module.eks.cluster_endpoint, "https://", "")`

1) eBPF based masquerade

In this setup I'm running into problems with CoreDNS that doesn't start when Karpenter provisions first nodes. Cilium status shows everything as healthy but in CoreDNS logs I see errors in networking. I've did some experiments and problem resolve if I restart cilium deamonset / agent manually. Same behaviour was observed also on 1.15.0-pre.2 Helm chart.

```yaml
bpf:
   masquerade: true

ipMasqAgent:
  enabled: true
```

CoreDNS logs:

```
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:53243->10.0.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:45013->10.0.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:38592->10.0.0.2:53: i/o timeout
[INFO] plugin/ready: Still waiting on: "kubernetes"
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:59609->10.0.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:57288->10.0.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:44291->10.0.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:58881->10.0.0.2:53: i/o timeout
[INFO] plugin/ready: Still waiting on: "kubernetes"
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:60436->10.0.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:41234->10.0.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 465548514489782249.536620727934911967. HINFO: read udp 100.64.139.21:57608->10.0.0.2:53: i/o timeout
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[WARNING] plugin/kubernetes: Kubernetes API connection failure: Get "https://172.20.0.1:443/version": dial tcp 172.20.0.1:443: i/o timeout
```

2) iptables based masquerade

Configuration for this section is based on https://docs.cilium.io/en/stable/network/concepts/routing/#id5

In this mode Cilium and CoreDNS starts correctly, however when I look into Hubble I can see that egress traffic in secondary CIDR (100.64.0.0/16) is marked as world communication. I'm not 100% sure that this is a bug or I'm missing something somewhere but I would expect that pod to pod communication would resolve inside the cluster and traffic should happen inside the namespace.

```yaml
ipv4NativeRoutingCIDR: 100.64.0.0/16
egressMasqueradeInterfaces: eth0
```

I haven't seen any change in behaviour when following was set:
- Changed `ipv4NativeRoutingCIDR` to primary CIDR 10.0.0.0/16 or keeping it empty
- Disabled `endpointRoutes` to route via Cilium interface

3) No masquerade

I don't see any difference between this and iptables based masquerade. Again all traffic between pods is marked as world communication. Again not 100% sure if this is expected or I'm missing something to make pods aware about each other. 

```yaml
enableIPv4Masquerade: false
```

### Cilium Version

1.14.4

### Kernel Version

Linux 6.1.59 #1 SMP PREEMPT_DYNAMIC Thu Nov  9 07:59:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.28.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this issue @pdrastil. It would really help troubleshooting here if you could add a sysdump (collected using https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection ) to the issue, after scrubbing any confidential stuff if needed.

The sysdump captures the bpf state, so it's really helpful for being able to look into this sort of issue. Maybe start with the sysdump for the use case you want to use the most?

Thanks for your patience.

**Comment by pdrastil** [comment]
Hi @youngnick thanks for the reply. I would take a look on eBPF mode with ipMasqAgent. This looks like a bug where something is not going in correct order as Cilium starts working after manual DS restart. At that point CoreDNS stops crash looping and everything else starts properly. See attached sysdump from small test cluster that was created for this scenario.

[cilium-sysdump-20231128-222654.zip](https://github.com/cilium/cilium/files/13493602/cilium-sysdump-20231128-222654.zip)

**Comment by youngnick** [comment]
Okay, thanks for that, I've labelled the issue so it should show up in the correct queue now.

**Comment by paurosello** [comment]
We are facing the same issue in our clusters using EKS and also our setup with EC2 instances, after agent restart everything works perfectly fine, when a new node joins the cluster it boots broken.

**Comment by pdrastil** [comment]
Hi @youngnick I had time to test 1.14.5 and it seems that something fixed startup of nodes in the cluster. I will run this multiple times to be sure but so far newer version looks good.

**Comment by msolters** [comment]
> We are facing the same issue in our clusters using EKS and also our setup with EC2 instances, after agent restart everything works perfectly fine, when a new node joins the cluster it boots broken.

This sounds suspiciously like https://github.com/cilium/cilium/issues/28764
