### ISSUE TITLE
Phase out support for 4.19 kernel

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#29380]
The `4.19` kernel will go [end-of-life](https://www.kernel.org/category/releases.html) in December 2024. Time to start thinking about timeline & tasks for its deprecation.

**Comment by julianwiedmann** [comment]
For reference, here's what we did for the 4.9 kernel: https://github.com/cilium/cilium/issues/22116

**Comment by sushiMix** [comment]
REDHAT 8 is a kernel 4.18 do you mean you'll remove it's support ?

**Comment by lmb** [comment]
@sushiMix RHEL kernels share a version number with kernel.org releases but are basically a whole different beast due to backports.

**Comment by lmb** [comment]
Closing in favour of https://github.com/cilium/cilium/issues/29380.

**Comment by aanm** [comment]
@lmb that's the same GH issue
