### ISSUE TITLE
Docs: Add Webhook Limitations to EKS Install Doc

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#29454]
Currently, the EKS install [doc](https://docs.cilium.io/en/latest/installation/k8s-install-helm/) state the following limitations when using overlay mode:

>Cilium can alternatively run in EKS using an overlay mode that gives pods non-VPC-routable IPs. This allows running more pods per Kubernetes worker node than the ENI limit, but means that pod connectivity to resources outside the cluster (e.g., VMs in the VPC or AWS managed services) is masqueraded (i.e., SNAT) by Cilium to use the VPC IP address of the Kubernetes worker node.

Additionally, this mode does not support webhooks since the EKS control plane cannot directly access the pod. As a workaround, the webhook endpoint can be exposed using host networking. This workaround should be documented.

**Comment by danehans** [comment]
If others agree with this issue, feel free to assign me and I'll update the doc.

**Comment by danehans** [comment]
xref https://github.com/cilium/cilium/issues/21959

**Comment by youngnick** [comment]
Seems reasonable to me, thanks @danehans.
