### ISSUE TITLE
CI: Cilium E2E Upgrade (ci-e2e-upgrade) fails in no-missed-tail-calls

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#29476]
## CI failure

Occurred in https://github.com/cilium/cilium/pull/29443
Test: [Setup & Test (7, bpf-next-20231030.012704, none, true, {eth0,eth1}, true, disabled, snat, true, t..](https://github.com/cilium/cilium/actions/runs/7021503468/job/19103730011#logs)

```
 [=] Test [no-missed-tail-calls]

  [-] Scenario [no-missed-tail-calls/no-missed-tail-calls]
  🟥 Detected drops due to missed tail calls: 1
```

Sysdump: Too large to upload, but I can provide it upon request.

**Comment by pchaigno** [comment]
Another case at https://github.com/cilium/cilium/actions/runs/7180493466/job/19552892605, with the same config.

And then a similar one for the downgrade (still same Cilium config) at https://github.com/cilium/cilium/actions/runs/7190938554/job/19584876695.

**Comment by pchaigno** [comment]
Another case with a different configuration (14) but very similar to the configuration 7 referred to above: https://github.com/cilium/cilium/actions/runs/7180493466/job/19552894913.
