### ISSUE TITLE
Add a userspace bitwise LPM trie data structure

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#29519]
When building networking functionality, one of the quintessential properties of the dataplane is that the features must make decisions about to handle packet content based on bitpatterns in the packets. IP protocols define meaning for bitwise prefixes, which motivates the need for Longest Prefix Match (LPM) structures when handling the packets. We've had such structures in the datapath for a long time, and have used them for multiple purposes from identifying the identity of traffic (via ipcache) to identifying whether identity or port is relevant for making a policy decision (via policymap) to routing (in SRv6). We use this data structure when handling packets because of the efficiency of these lookups compared to alternatives like iterating through possible matches in hash tables or arrays.

Assuming that the dataplane has logic that operates on LPM map types, the local control plane also needs to be able to populate these maps efficiently. In many cases, userspace can do this by processing abstract (k8s) resources and internally representing these in hash tables, sometimes even as multi-layered hash tables. However, as the implementation becomes more powerful, the needs for populating the datapath LPM map types start to drive a need for userspace to have similar representations in order to make data efficiently indexable and comparable, particularly in the case of overlapping sets of keys.

This issue collects use cases for a userspace bitwise LPM data structure in userspace:
- Policy: When calculating the way that L4 port range policies impact one another, we need efficient ways to store and index potentially overlapping policy "Filters" that define the traffic behaviour for those port ranges. By encoding this with a bitwise LPM, we can ensure that the insertion/merging of new port range policies and evaluation of those port range policies to calculate datapath entries does not require linear iteration of all filters in the port range space.
- IPCache: We would like to be able to associate labels with CIDRGroups. When there are two CIDRGroups with distinct labels, such as `192.0.2.0/24` with `A` and `192.0.2.3/32` with `B`, the IPCache needs to calculate the full set of labels that applies to each subset entry in the IPCache. In this example, the IP `192.0.2.3/32` resides within the prefix `192.0.2.0/24`, so when calculating a local identity for this IP, the identity should include both labels `A` _and_ `B`. In order to implement this, when evaluating the identity for `192.0.2.3`, it would be helpful to be able to iterate up a tree of possible prefixes and locate entries that define additional labels for this prefix to have.

**Comment by nathanjsweet** [comment]
Great write up! [Port Range Mapping](https://github.com/cilium/cilium/pull/28881) needs this.
[Here is a pull request](https://github.com/cilium/cilium/pull/29717) to solve this need.
