### ISSUE TITLE
Randomly delayed IPv6 traffic on host network

### ISSUE THREAD

**Issue by Hayajiro** [cilium/cilium#29529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using Cilium 1.14, IPv6 traffic sent by the host itself is randomly delayed by ~4 seconds on average. This affects only individual packets, and affected packets are retransmitted several times until an ACK is received. This usually happens around 4 seconds later, according to tcpdump. After the initial ACK, all duplicate ACKs arrive within a few milliseconds.

The issue appears **roughly** every 30 minutes - sometimes a bit slower or faster, but generally in that ballpark. It also affects every node individually, so each node has its own window.

In our case, this mainly affects BGP KeepAlive messages (sent by bird). Whenever this occurs, we experience flapping BGP sessions on our Router due to tight hold times. This makes us believe that the issue is on the egress path and the ACK is actually unobstructed. Our specific issue with flapping BGP sessions was worked around by making the hold times less strict, but it doesn't solve the underlying problem.

### Cilium Version

```
Client: 1.14.4 c78702ce25 2023-10-26T12:24:12+02:00 go version go1.20.11 linux/amd64
Daemon: 1.14.4 c78702ce25 2023-10-26T12:24:12+02:00 go version go1.20.11 linux/amd64
```

We're actually using a custom image to fix #26886, but we experience the same problem even when backporting the official fix to the issue. However, as mentioned below, the issue got first introduced in `v1.14.0-snapshot.3`. `v1.14.0-snapshot.2`, which also contains the conntrack-bug, did not experience these delays with IPv6 traffic.

### Kernel Version

```
Linux m1 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.26.5
Kustomize Version: v4.5.7
Server Version: v1.26.5
```

### Sysdump

Available via Slack upon request

### Relevant log output

```shell
We can provide things like packet captures and kernel traces of delayed packets via Slack.
```

### Anything else?

I've also tried tracing the affected packets in the kernel, but the traces look exactly the same, with the only difference being whether we receiving a packet (`ipv6_gro_receive`) or start to retransmit the seemingly lost packet (`__skb_clone`):
![image](https://github.com/cilium/cilium/assets/4905319/7d79a880-d2cd-4fc9-931e-901541ac779b)
Left is the delayed packet, right the one that's been sent correctly.

We've already tried find the bug using `git bisect`, but during the time, there were a lot of other bugfixes that made IPv6 work somewhat reliably in our setup (e.g. the NDP issue). This made juggling the right patches for each step quite difficult and we weren't able to find a specific commit last time we tried. However, we already nailed it down to two specific releases: **The issue does not occur using `v1.14.0-snapshot.2` , but starts popping up using `v1.14.0-snapshot.3`.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
@Hayajiro Thanks for the report, could you share some more info abour your cluster? Ideally, we need some form of sysdump to look into this further. Any logs from the time of the event would be useful. Does this correspond to any other events in your environment? What's your cluster's Cilium config?

**Comment by Hayajiro** [comment]
Hi @ti-mo

sorry, I completely forgot to attach the Helm values in the initial issue, so here they are:

```
  ipam.mode=kubernetes
  hubble.relay.enabled=true
  hubble.ui.enabled=true
  l7Proxy=false
  encryption.enabled=true
  encryption.type=wireguard
  prometheus.enabled=true
  operator.prometheus.enabled=true
  hubble.metrics.enabled='{flow,tcp,icmp,port-distribution:labelsContext=source_pod\,source_ip\,source_namespace\,source_workload\,destination_ip\,destination_pod\,destination_namespace\,destination_workload\,traffic_direction,drop:labelsContext=source_pod\,source_ip\,source_namespace\,source_workload\,destination_ip\,destination_pod\,destination_namespace\,destination_workload\,traffic_direction;labelsContext=source_pod\,source_ip\,source_namespace\,source_workload\,destination_ip\,destination_pod\,destination_namespace\,destination_workload\,traffic_direction}'
  hostFirewall.enabled=true
  cni.chainingMode=portmap
  ipv6.enabled=true
  kubeProxyReplacement=disabled
  extraConfig.log-opt='format=json-ts'
```

There are no manual changes to the Cilium-Config.

> Ideally, we need some form of sysdump to look into this further

As mentioned above, I'd gladly provide this via Slack (otherwise I'd have to anonymize it first, which might take a while) and could potentially also grant access to a cluster affected by this issue.

> Any logs from the time of the event would be useful. Does this correspond to any other events in your environment?

We've already had a look, but there's nothing unusual about this. `hubble monitor` doesn't see the traffic, at all, and cilium-agent doesn't log anything unusual, either. It also doesn't relate to any other events from what we've seen.

**Comment by Hayajiro** [comment]
Still relevant, haven't checked with 1.15.0 just yet, but I suppose it affects that version, as well.
