### ISSUE TITLE
Unable to upgrade LVH images tests-datapath-verifier.yaml

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#29543]
We haven't been able to upgrade the LVH images since October for tests-datapath-verifier.yaml as they fail every time. The GH action with the test failure can be found [here](https://github.com/cilium/cilium/actions/runs/7058620998)

The PR that tried to upgrade the images is https://github.com/cilium/cilium/pull/29534/files#diff-8a97415e3b1ab63d0cbf682a195a63c178786ae792455f62f7dc523acf9f9b50, the changes were reverted in the meanwhile but the diff was the following:
```diff
diff --git a/.github/workflows/tests-datapath-verifier.yaml b/.github/workflows/tests-datapath-verifier.yaml
index f833b34d9e0..dc22e342eb9 100644
--- a/.github/workflows/tests-datapath-verifier.yaml
+++ b/.github/workflows/tests-datapath-verifier.yaml
@@ -73,22 +73,22 @@ jobs:
       matrix:
         include:
           # renovate: datasource=docker depName=quay.io/lvh-images/kind
-          - kernel: '4.19-20231026.065108'
+          - kernel: '4.19-20231124.100406'
             ci-kernel: '419'
           # renovate: datasource=docker depName=quay.io/lvh-images/kind
-          - kernel: '5.4-20231026.065108'
+          - kernel: '5.4-20231124.100406'
             ci-kernel: '54'
           # renovate: datasource=docker depName=quay.io/lvh-images/kind
-          - kernel: '5.10-20231026.065108'
+          - kernel: '5.10-20231124.100406'
             ci-kernel: '510'
           # renovate: datasource=docker depName=quay.io/lvh-images/kind
-          - kernel: '5.15-20231026.065108'
+          - kernel: '5.15-20231124.100406'
             ci-kernel: '510'
           # renovate: datasource=docker depName=quay.io/lvh-images/kind
-          - kernel: '6.1-20231026.065108'
+          - kernel: '6.1-20231124.100406'
             ci-kernel: '61'
           # renovate: datasource=docker depName=quay.io/lvh-images/kind
-          - kernel: 'bpf-next-20231123.012848'
+          - kernel: 'bpf-next-20231128.012937'
             ci-kernel: 'netnext'
     timeout-minutes: 60
     steps:

```

**Comment by mhofstetter** [comment]
**Analysis**

LVH PR https://github.com/cilium/little-vm-helper-images/pull/187 introduced `systemd-resolved` in the images.

The GH workflow `tests-datapath-verifier.yaml` fails because `systemd-resolved` isn't ready once the LVH GH action command [tries to download Go](https://github.com/cilium/cilium/blob/main/.github/workflows/tests-datapath-verifier.yaml#L117-L118) as first step.

Waiting for the service to become ready should do the trick

poor mans solution (added as first step in `cmd`:

```
for i in {1..5}; do curl "https://golang.org/" > /dev/null 2>&1 && break || sleep 5; echo "Waiting for systemd-resolved to be ready..."; done
```

**Comment by mhofstetter** [comment]
Blocked Renovate PR: https://github.com/cilium/cilium/pull/29556

**Comment by mhofstetter** [comment]
Related DNS changes in LVH images & action

Images: install `systemd-resolved`: https://github.com/cilium/little-vm-helper-images/pull/187
Action: remove dns-resolver property in action: https://github.com/cilium/little-vm-helper/pull/118
