### ISSUE TITLE
Hubble-UI error when trying to access via Gateway API in 1.15.0-pre.3

### ISSUE THREAD

**Issue by HummingMind** [cilium/cilium#29563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am getting the following error when accessing the UI:
Data stream has failed on the UI backend: Http response at 400 or 500 level, http status code: 400

![image](https://github.com/cilium/cilium/assets/87399963/a0e7cf0a-82cd-4d37-94fb-c27c879b87c5)

In the Browser's Dev Tools I can see:
POST https://myfqdn/api/ui.UI/GetControlStream 400 (Bad Request) (edited)

From what I am gathering, this has something to do with grpc/h2c/HTTP2. TLS is being terminated at the HTTPS listener. Do I need a grpc route? The response header states: "gRPC requires HTTP/2"

Is there a documentation example on how this is supposed to work in a k8s cluster, that is not running on a local machine, specifically with the v1 of Gateway API?

### Cilium Version

1.15.0-pre.3

### Kernel Version

5.10.102.2-microsoft-standard

### Kubernetes Version

1.28.3

### Anything else?

I found a somewhat similar issue here: https://github.com/cilium/hubble-ui/issues/452
But that is using the Contour ingress, as opposed to Cilium's Gateway API as ingress.

If this issue needs to be moved to the hubble-ui repository, please feel free to move it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HummingMind** [comment]
I found this in the Gateway API documentation:
https://gateway-api.sigs.k8s.io/geps/gep-1911/

But when I describe the hubble-ui service, I don't see this filed being populated. Am I on the right track? 😨

**Comment by HummingMind** [comment]
I got it to work via Contour and it's HTTPProxy resource.
Couldn't get it to work via the Gateway API in Cilium.

Would be nice if any of the devs commented on whether this is supposed to work with Gateway API or if it is not yet baked enough to support something like this.

Thank you!

**Comment by cornfeedhobo** [comment]
I'm getting this same error using the Ingress Controller feature. I think the underlying problem is a misconfiguration in the envoy configs.

**Comment by cornfeedhobo** [comment]
@ti-mo I think this is a valid bug and should be investigated, given that it's also happening when I'm not using the gateway.

**Comment by HummingMind** [comment]
It seems like h2c is required for the backend (/api route). Contour supports this with their HTTPProxy resource. Gateway API 1.0 spec says that it's up to each implementation to support h2c on HTTP listeners. I have not found any mention of h2c support in Cilium's documentation or GitHub issues.

**Comment by cornfeedhobo** [comment]
@HummingMind Could you test this with `1.14.x`?

**Comment by HummingMind** [comment]
I doubt it's going to work based on what I found.

Seems like there will be a fallback on HTTP short polling soon for this: https://github.com/cilium/hubble-ui/pull/493#issuecomment-1855876015

**Comment by HummingMind** [comment]
With Gateway API and Cilium specifically though:
From https://gateway-api.sigs.k8s.io/geps/gep-1911/ it states that:

![image](https://github.com/cilium/cilium/assets/87399963/63104a46-99df-4136-ac63-ddcedfda2617)

So if I create a serivice (to route to the hubble ui backend), and mark it with appProtocol: h2c, Cilium's implementation should be able to support this, but it doesn't seem to with 1.15.0-rc.0.

It works with Contour's HTTPPRoxy resource. Contour's Gateway API 1.0 support is not coming out until the end of January, so I can't test it there yet.

**Comment by cornfeedhobo** [comment]
I got it to work here with 1.14.5

**Comment by HummingMind** [comment]
How? Can you provide your yaml please for the Gateway, the Routes, and the Service?

Thank you!

**Comment by cornfeedhobo** [comment]
Yeah, here's a gist of the gateways https://gist.github.com/cornfeedhobo/ac71985d8eae173b3b256e0189e749b7

**Comment by HummingMind** [comment]
Thank you for the configs! 🍻 

So no separate route for /api and no separate service for the backend? Interesting. I will stand up a new cluster with 1.14.5 today and will test. Will let you know the results.

**Comment by HummingMind** [comment]
Well FML. It does work with v1.14.5 just fine. Without creasting a separate service for the backend (so no need for a separate ./API route). Thank you @cornfeedhobo for pointing out using the current stable version (v1.14.5).

This is definitely a bug with v1.15.x snapshots.
Not sure who to tag here from the devs. @ti-mo

**Comment by acelinkio** [comment]
Can confirm this is still an issue in 1.15.0-rc.0

**Comment by acelinkio** [comment]
This issue is still occurring in 1.15.0

**Comment by devodev** [comment]
After having the same problem, I followed the trail of PRs and found this: https://github.com/cilium/hubble-ui/pull/767
Specifically related to this issue:

> Eliminates using of grpc-web and introduces short polling over basic http/1

I confirm that the cilium release 1.15.1 updates the hubble-ui images to 0.10.3, which removes grpc-web and fixes the issue: https://github.com/cilium/hubble-ui/releases/tag/v0.13.0

**Comment by geakstr** [comment]
@devodev thank for verification!
