### ISSUE TITLE
CFP: show traffic metrics for pods 

### ISSUE THREAD

**Issue by minosniugang** [cilium/cilium#29586]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

yes.  Previously we get the traffic for a pod through pod eth0 interface, e.g.
/ # ifconfig eth0
eth0  	Link encap:Ethernet  HWaddr xxx
      	UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
      	RX packets:4622917635 errors:0 dropped:0 overruns:0 frame:0
      	TX packets:4114094521 errors:0 dropped:0 overruns:0 carrier:0
      	collisions:0 txqueuelen:1000
      	RX bytes:2395417236939 (2.1 TiB)  TX bytes:3085935590709 (2.8 TiB)

However after we enabled KPR, we are not able to get the metrics for RX. Since BPF host routing on receiver side redirect the packet to pod directly and bypass lxc interface, so we are not able to get the traffic from interface. 

I see there are metrics for traffic
HELP cilium_forward_bytes_total Total forwarded bytes, tagged by ingress/egress direction
TYPE cilium_forward_bytes_total counter
cilium_forward_bytes_total{direction="EGRESS"} 4.1795931765499e+13
cilium_forward_bytes_total{direction="INGRESS"} 2.6188509546973e+13

however there are some problems
1. these metrics add traffic for all pods in the node together, I am not able to get the traffic for individual pod
2. the data seems not correct in some cases.  e.g. traffic is counted twice, one in host and one in lxc

**Describe the feature you'd like**

we want to get the traffic metrics with specific pods,  one idea is to add an endpoint label in metrics, i.e.
cilium_forward_bytes_total{direction="EGRESS", endpointID="1234"} 32423424. // a pod 
cilium_forward_bytes_total{direction="EGRESS", endpointID="3341"} 242344. // another pod
cilium_forward_bytes_total{direction="EGRESS", endpointID="1"} 76867. // host
same for ingress

**(Optional) Describe your proposed solution**

**Comment by gberche-orange** [comment]
A possible workaround is to have a single pod in the namespace and use cadvisor https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md#prometheus-container-metrics `container_network_receive_packets_total`and `container_network_transmit_bytes_total`

**Comment by mostafabayat** [comment]
> A possible workaround is to have a single pod in the namespace and use cadvisor https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md#prometheus-container-metrics `container_network_receive_packets_total`and `container_network_transmit_bytes_total`

I didn't understand clearly, the point is that receive metrics are incorrect, and at the same time transmit packet are correct.
for example, in my case, `container_network_receive_packets_total` are incorrect and `container_network_transmit_packets_total` are correct.

**Comment by mostafabayat** [comment]
#30566
