### ISSUE TITLE
CFP: Exclude k8s check from health probe result

### ISSUE THREAD

**Issue by minosniugang** [cilium/cilium#29588]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

Our clusters are very big, i.e. 5k nodes, 100k pods. cilium agents introduce very heavy traffic to api server for listing service, endpoints, identities, etc.  Our API server has configured flow schema to restrict request from cilium agent.  

So sometimes the requests from cilium agent are blocked, most of the time it should not be a problem, the controller will retry.  However the health check will be blocked as well, and if the failed health check exceed the threshold, liveness probe will kill the container.  Then the cilium agent enter the much heavier initialization phase which need relist lots of resources,  and takes other cilium agent down.  Finally it triggers a cascade failure and majority of the cilium agents will down. 

**Describe the feature you'd like**

So we want to have the option to exclude the k8s check from liveness probe.  If k8s is not available, cilium can just keep retry and report failure in status, but don't kill itself. 

**(Optional) Describe your proposed solution**

1. add a new option ExcludeK8sFromHealthProbeResult, default false to keep the same behavior as before. 
2. when ExcludeK8sFromHealthProbeResult is set true and k8s health check fail,  cilium status will show k8s not available, but cilium status --brief still show OK so liveness probe will not kill the container.

**Comment by chaunceyjiang** [comment]
Hi, @minosniugang Can we solve the problem by adjusting parameters related to livenessProbe, such as `timeoutSeconds`?

**Comment by minosniugang** [comment]
this is the workaround we do today, but it will hide other problems which may be more critical

**Comment by aanm** [comment]
@minosniugang this seems a more specific use case of https://github.com/cilium/cilium/issues/25288, would you like to give a go for https://github.com/cilium/cilium/issues/25288?

**Comment by minosniugang** [comment]
[25288](https://github.com/cilium/cilium/issues/25288)  is asking improvement in kvstore health check, not related to this one. 
One idea you suggest there is to allow user customize the health check scope through url parameters.  So we need identify the list of sub-systems that user can use in include / exclude. The challenge is the sub-system list is dynamic and rely on configurations.  In status code today we only check the enabled sub-system, but if user can define the sub-system explicitly in health check monitor, how to handle the conflict with configuration gracefully? e.g. if user use kvstore, not k8s crd. Then the health check include k8s, what should we do?
