### ISSUE TITLE
Remove `skip-cnp-status-startup-clean` and CNP status 

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#29590]
Follow-ups from https://github.com/cilium/cilium/issues/24503 :
- Remove `skip-cnp-status-startup-clean`: https://github.com/cilium/cilium/blob/2835b063800f7e98696c38e451016e5e9a0ab47b/operator/option/config.go#L72
- Remove CNP Status: https://github.com/cilium/cilium/blob/e6a55a021627d41c0779631e8e01faed4e5f31a3/pkg/k8s/apis/cilium.io/v2/cnp_types.go#L77
- Remove hidden option `legacy-turn-off-k8s-event-handover` https://github.com/cilium/cilium/blob/5ef0f107d64e64a422a65741d804b01cd3995545/pkg/option/config.go#L828

**Comment by marseel** [comment]
I will reopen this issue - thanks @chaunceyjiang for fixing 1st and 3rd points. 
I think we are still missing 2nd point, is this something you would like to tackle?

**Comment by christarazi** [comment]
If the user can no longer configure it then it can't be used anymore AFAIU. Which means it's safe to remove from the CRD.

**Comment by christarazi** [comment]
@marseel Can we close this?

**Comment by marseel** [comment]
I've opened https://github.com/cilium/cilium/pull/32877
