### ISSUE TITLE
CFP: Improve security by explicit cluster name and cluster-id in clustermesh

### ISSUE THREAD

**Issue by CallMeFoxie** [cilium/cilium#29602]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

Sort of. We run a large clustermesh with tens of clusters. However right now there's no way to verify that nobody has messed with "their" cluster in the clustermesh. For all we know they could (provided they manage to access the etcd):
a) insert foreign cluster's endpoint number
b) insert fake labels on their actual endpoints and pretend they are a different cluster

**Describe the feature you'd like**

It would be nice to have the option to specify not just another cluster's kvstore (etcd), but also their cluster name (or derive it from the file name) AND their remote cluster ID.
- The cluster ID would be verified against the endpoints in that ETCD
- The name of their cluster would be fixed as a local label for endpoints from their cluster, something like `cilium.io:cluster-name: fubar`.

(Hope this is actual CFP and not a bug report?)

Cheers

Ashley

**Comment by giorio94** [comment]
Thanks @CallMeFoxie for raising this point. 

Let me try to answer inline:

> For all we know they could (provided they manage to access the etcd):
a) insert foreign cluster's endpoint number
b) insert fake labels on their actual endpoints and pretend they are a different cluster

This is indeed possible, and covered by the Cilium threat model under [Cilium Key-value Store Attacker](https://docs.cilium.io/en/stable/security/threat-model/#cilium-key-value-store-attacker) and [Kubernetes API Server Attacker](https://docs.cilium.io/en/stable/security/threat-model/#kubernetes-api-server-attacker), which can be extended to include the clustermesh case. Specifically, the first section focuses on tampering with the kvstore itself, while the latter covers CRDs (which are then reflected by the clustermesh-apiserver -- when Cilium is configured in CRD mode -- into the sidecar etcd instance). Overall, access to the kvstore shall be secured configuring mTLS, limiting at the same time the permissions associated with each user (e.g., remote clusters are granted read-only access only to the clustermesh-apiserver kvstore). Although additional consistency checks could be introduced in the agent (more on this later) to ensure matching ClusterID/ClusterName in all resources, an attacker with full kvstore access would still be able to tamper with the rest of the information, possibly disrupting connections, diverting traffic and so on. 

> It would be nice to have the option to specify not just another cluster's kvstore (etcd), but also their cluster name (or derive it from the file name) AND their remote cluster ID.
> * The cluster ID would be verified against the endpoints in that ETCD
> * The name of their cluster would be fixed as a local label for endpoints from their cluster, something like cilium.io:cluster-name: fubar.

Currently, the remote cluster name is specified as part of the configuration itself (it is the key of the secret entry, which then becomes the name of the file containing the configuration), while the remote cluster ID is retrieved by the agents from the remote kvstore when connecting to it (this was a design choice to avoid requiring users to explicitly specify it). [Cluster ID validation](https://github.com/cilium/cilium/blob/d1128cf948979de7433385b2101a98404d99c64f/pkg/clustermesh/remote_cluster.go#L72-L76) is implemented to block the connection in case two clusters report the same Cluster ID, as well as there are checks to ensure that the Cluster ID specified in the different resources is in the expected range. Besides that, it should be possible to extend the observers of the different resources (nodes/IPs/services/identities) to additionally validate that the reported cluster name/id match the global ones of the clusters. That's something I've also personally evaluated in the past but, as mentioned earlier, I'd consider that a consistency check, not something security oriented.

**Comment by oblazek** [comment]
Thanks a lot for the writeup @giorio94 ..
Seems to me that most secure thing to do here (if attacker gains access to the etcd) is to validate if the identity synced from etcd contains the cluster label. 

I.e. as the attacker cannot modify the clustername (e.g. `iptv-stable.ko`) on the side of the agent syncing the remote ID `the remote cluster name is specified as part of the configuration itself` 
```
cilium/state/identities/v1/id/4546510
k8s:app=service-user-notify;k8s:io.cilium.k8s.policy.cluster=iptv-stable.ko;k8s:io.kubernetes.pod.namespace=stream-stable;
```
we probably could validate that the identity contains the `io.cilium.k8s.policy.cluster=iptv-stable.ko`.
In case attacker tried to modify the identity values we would still know for sure if this ID comes from the `iptv-stable.ko` cluster. That's the least we can do I think.

**Comment by giorio94** [comment]
Yes, it is definitely possible to validate the cluster name there and reject entries with an invalid cluster name. The next step would also be validating the numeric identity, given that the first byte must match the Cluster ID. That said, the same attacker would also be able to tamper with all the other values which cannot be validated, which IMO limits the effectiveness of such approach from a pure security standpoint.

**Comment by giorio94** [comment]
Closing, as addressed by https://github.com/cilium/cilium/pull/32749, https://github.com/cilium/cilium/pull/32785 and https://github.com/cilium/cilium/pull/32996.

**Comment by oblazek** [comment]
aweseome!! Thanks a lot Marco ;)
