### ISSUE TITLE
What is the theoretical value of CPU consumption when enabling the Hubble ?

### ISSUE THREAD

**Issue by thfsir** [cilium/cilium#29617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Set -- set hub. enabled=true, collect metrics metrics, enable L7 proxy,  and how much CPU does the cilium agent need to consume? Is there any reference data for this?

### Cilium Version

1.13.6

### Kernel Version

5.18

### Kubernetes Version

1.20

### Sysdump

no

### Relevant log output

```shell
no
```

### Anything else?

no

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by glibsm** [comment]
The answer really depends on the environment and how much network traffic is flowing through the cluster. We'd encourage you to look at utilization _in your environment_ with and without it enabled to get a better understanding how it would affect _you_.

Feel free to reach out for more discussion on the topic in the OSS Slack #hubble channel, it's probably a better avenue to have this kind of a discussion.
