### ISSUE TITLE
CFP: Add support for mixed protocol L2LB ports

### ISSUE THREAD

**Issue by i404788** [cilium/cilium#29628]
## Cilium Feature Proposal

Currently there seems to be a limitation on mixed protocol L2 LoadBalancers; they can't use the same port for TCP/UDP even though some service require both to be on the same external port.

It also requires support for `MixedProtocolLBService` feature which I believe is already supported by not documented .

**Is your proposed feature related to a problem?**

This limitation is currently undocumented (there is no reference to UDP in general in the L2LB docs).

Current behaviour seems to indicate it might 'work' but the LBIPAM prevents UDP/TCP from being allocated on the same IP even on the same service. It might require changes in similar vein to https://github.com/cilium/cilium/pull/28806

**Describe the feature you'd like**

If it's already supported allow UDP/TCP to be allocated to the same LBIPAM address-port if it's on the same service (assuming `MixedProtocolLBService` is enabled).

**Comment by borkmann** [comment]
Hello :wave: TCP/UDP on the same port has a PR which is work in progress: https://github.com/cilium/cilium/pull/26399 . Could you help to test / review from your side? I presume this should address your concerns? Thanks!

**Comment by i404788** [comment]
Hey, didn't know this was being worked on I think that will resolve it I'll have to check if the IPAM logic is also correct, I'll follow up in the PR if I have time to test/review it.

**Comment by dylandreimerink** [comment]
The LB-IPAM logic has been purposefully made to match the current capabilities of the datapath. As soon as https://github.com/cilium/cilium/pull/26399 is merged, we can also remove the constraint from LB-IPAM
