### ISSUE TITLE
egressgw: add BPF complexity tests for XDP

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#29635]
`ENABLE_EGRESS_GATEWAY` introduces additional complexity to the nodeport RevSNAT / RevDNAT paths. Let's make sure this is reflected in the complexity tests, and populate the XDP configs with `-DENABLE_EGRESS_GATEWAY=1`.

See https://github.com/cilium/cilium/tree/main/bpf/complexity-tests/netnext/bpf_host for existing tests that cover EgressGW.

**Comment by AbhilashGade** [comment]
Can I work on this issue?
