### ISSUE TITLE
ClusterMesh Configuration not Found on Running Cilium Pods

### ISSUE THREAD

**Issue by lagumen** [cilium/cilium#29632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Setting up cilium clustermesh through service-type ClusterIP allowed two distinct clusters to connect but respective cilium pods are not able to to connect to remote cluster due to a remote cluster configuration is not detected/found on cilium pods declarative config => /var/lib/cilium/clustermesh. 

I expected  /var/lib/cilium/clustermesh would contain the necessary remote cluster configuration for these cilium pods to connect to remote cluster

The expected absolute path was discovered instead residing on these locations, but are empty directories:
/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1345/fs/var/lib/cilium/clustermesh
/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1345/fs/var/lib/cilium/clustermesh

Attached images:
<img width="1067" alt="Screenshot 2023-12-05 at 7 58 13 AM" src="https://github.com/cilium/cilium/assets/14792464/908cf876-327a-4fd8-a883-06bcbad278a5">

<img width="401" alt="Screenshot 2023-12-05 at 8 01 10 AM" src="https://github.com/cilium/cilium/assets/14792464/4094060a-be8b-426d-a758-157a99e2feef">

<img width="2380" alt="Screenshot 2023-12-05 at 8 02 03 AM" src="https://github.com/cilium/cilium/assets/14792464/7450df9d-3619-4acf-a28c-c0a26f62cf71">

<img width="2375" alt="Screenshot 2023-12-05 at 8 03 38 AM" src="https://github.com/cilium/cilium/assets/14792464/9dde6b3b-fe58-4e8b-9b42-95e132f3aff9">

### Cilium Version

[root@mac ~]# cilium version
cilium-cli: v0.15.16 compiled with go1.21.4 on linux/amd64
cilium image (default): v1.14.4
cilium image (stable): v1.14.4
cilium image (running): 1.14.4

### Kernel Version

[root@mac ~]# uname -r
5.14.0-284.11.1.el9_2.x86_64

### Kubernetes Version

[root@mac ~]# kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4

### Sysdump

[cilium-sysdump-20231205-081059.zip](https://github.com/cilium/cilium/files/13561209/cilium-sysdump-20231205-081059.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
> due to a remote cluster configuration is not detected/found on cilium pods declarative config => /var/lib/cilium/clustermesh.

This error message refers to the cluster configuration object not being present in the remote kvstore. This error can occur when kvstoremesh is enabled, if kvstoremesh itself cannot connect to the remote clustermesh-apiserver to relay the different information (including the cluster config object). Please refer to https://github.com/cilium/cilium/issues/29161 for additional details.

Checking the kvstoremesh logs from your sysdump, you can indeed see:

> 2023-12-05T05:58:01.516965983-06:00 level=warning msg="Unable to establish etcd connection to remote cluster" clusterName=cluster01 config=/var/lib/cilium/clustermesh/cluster01 error="timed out while waiting for etcd session. Ensure that etcd is running on [https://cluster01.mesh.cilium.io:2379]" kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
> 2023-12-05T05:58:01.517014656-06:00 {"level":"warn","ts":"2023-12-05T11:58:01.516785Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0005e5dc0/cluster01.mesh.cilium.io:2379","attempt":0,"error":"rpc error: code = Canceled desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 10.96.129.166:2379: i/o timeout\""}

Which means that the configured IP address is not reachable. It seems that you are exposing the clustermesh-apiserver through a ClusterIP service, which is rather strange. How do you ensure they are reachable from the other clusters? Typically, you would want to use either NodePort or LoadBalancer services.
