### ISSUE TITLE
Node labels updates rejected indefinitely by host endpoint if node watcher initializes before the host endpoint is created

### ISSUE THREAD

**Issue by skmatti** [cilium/cilium#29649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We ran into a race condition where the host endpoint's labels are outdated indefinitely. The issue is fixed if I restart the cilium agent.

The sequence of steps that resulted in the race condition are:

1. The endpoint manager's node label observer is initialized before the host endpoint is created. So, the first node label update is missed as we return early if the host endpoint is not found.

https://github.com/cilium/cilium/blob/d1128cf948979de7433385b2101a98404d99c64f/pkg/endpointmanager/host.go#L43-L48

2. All the subsequent node label updates are rejected by endpoint's `ModifyIdentityLabels` function

https://github.com/cilium/cilium/blob/d1128cf948979de7433385b2101a98404d99c64f/pkg/labels/oplabels.go#L157-L169

As the first node label update was missed, some labels on the oldNode object are not found on the endpoint's existing labels so the update request is rejected.

### Cilium Version

All versions

### Kernel Version

Linux bootstrapper 5.4.0-100-generic

### Kubernetes Version

1.27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bagga11** [comment]
Is there any ETA for this to be fixed?

**Comment by skmatti** [comment]
@pchaigno @aojea any insights on the fix for this issue? 

Maybe we should treat host endpoint separately and allow label updates even if the previous updates were missed?

**Comment by skmatti** [comment]
Can someone help remove the stale label?. Thanks

**Comment by skmatti** [comment]
@pchaigno @aojea @joestringer Any insights on how to prevent this race condition. We ran into this issue again.

**Comment by pchaigno** [comment]
> Maybe we should treat host endpoint separately and allow label updates even if the previous updates were missed?

That seems worth a try. Do you want to send a PR with that fix and the related test?

**Comment by skmatti** [comment]
@pchaigno I raised a PR. can you please help review it?. Thanks
