### ISSUE TITLE
CI: Runtime Test (privileged) TestSharingKey

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#29645]
## CI failure

- Copy-paste the output the test failure.

```
--- FAIL: TestSharingKey (1.11s)
    lbipam_test.go:669: Expected service status to be updated
```

- Upload the zip file generated from that test failure.

[cilium-junits.zip](https://github.com/cilium/cilium/files/13573921/cilium-junits.zip)

- Copy-paste the link of the CI build where that test failure has happen.

https://github.com/cilium/cilium/actions/runs/7107632741/attempts/1

**Comment by michi-covalent** [comment]
another similar failure:
```
--- FAIL: TestRequestIPs (1.11s)
    lbipam_test.go:1907: Expected service status update
```
https://github.com/cilium/cilium/actions/runs/7107632741
[cilium-junits.zip](https://github.com/cilium/cilium/files/13574174/cilium-junits.zip)

**Comment by brb** [comment]
> --- FAIL: TestRequestIPs (1.11s)
    lbipam_test.go:1907: Expected service status update

One more https://github.com/cilium/cilium/actions/runs/7114285658/job/19368045143
