### ISSUE TITLE
Local identity updates are double-processed (and all endpoints needlessly regenerated)

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#29681]
Happening in https://github.com/cilium/cilium/actions/runs/7115820553/job/19372953420
```
2023-12-06T14:30:57.396708838Z level=warning msg="UpdateIdentities: Skipping Delete of a non-existing identity" identity=16777217 subsys=policy
```

Happened in tests:
```
K8sAgentPolicyTest Multi-node policy test validates fromEntities policies with remote-node identity disabled
K8sAgentPolicyTest Multi-node policy test validates ingress CIDR-dependent L4 With host policy
```

Warning currently allowlisted at https://github.com/cilium/cilium/blob/5a82225cd713ed4480324a3ebfce449196cbbd3c/test/helpers/cons.go#L248C1-L248C41.

**Comment by squeed** [comment]
Aha, it looks like we are double-deleting identities. (This error message is from the SelectorCache), as well as pushing out a totally needless endpoint regeneration!

When the IP entry is stale, the ipcache releases it's reference, which causes the refcount to go to zero. The local allocator sends a delete on its event channel, which is picked up by `identityWatcher.Watch()`, which calls `identityAllocatorOwner.UpdateIdentities()`, which calls `SelectorCache.UpdateIdentities()` **and** regenerates all endpoints!

Separately, the ipcache notices that the identity was deleted, and **also** calls `SelectorCache.UpdateIdentities()`. This correctly generates an incremental policy update, which is no fun given that we've already queued a full regeneration of all endpoints.

We should **really** fix this. I don't yet understand the purpose of the event channel; that will take some understanding.
