### ISSUE TITLE
Unavoidable warning `Disabling socket-LB tracing as it requires kernel 5.7 or newer`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#29734]
The following warning pops up in our ginkgo CI:
```
Disabling socket-LB tracing as it requires kernel 5.7 or newer
```

It currently be avoided because, even if we disable the feature, it is printed:
https://github.com/cilium/cilium/blob/v1.14.4/daemon/cmd/kube_proxy_replacement.go#L354-L357

**Comment by rgo3** [comment]
Daniel actually did open a PR for this after all: #29730
