### ISSUE TITLE
Unavoidable LRP warning `Without socket lookup kernel functionality, BPF datapath cannot prevent potential loop caused by local-redirectservice translation`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#29735]
This warning pops up in our ginkgo CI:
```
level=warning msg="Without socket lookup kernel functionality, BPF datapath cannot prevent potential loop caused by local-redirectservice translation. Needs kernel version >= 5.1" subsys=redirectpolicy
```

There doesn't seem to be a way to avoid it if you're using Linux < v5.1 with LRP enabled.

Warning currently allowlisted at https://github.com/cilium/cilium/blob/5a82225cd713ed4480324a3ebfce449196cbbd3c/test/helpers/cons.go#L248C1-L248C41.

**Comment by borkmann** [comment]
Related fix: https://github.com/cilium/cilium/pull/26144

**Comment by aditighag** [comment]
What's the expectation here? We currently don't check for underlying kernel versions in the agent code, so should we change that behavior, and suppress such unavoidable warnings?

**Comment by aditighag** [comment]
The code probing for socket lookup helpers has been removed with the merge of  https://github.com/cilium/cilium/pull/26144.
