### ISSUE TITLE
Fix typos all around the project

### ISSUE THREAD

**Issue by szepeviktor** [cilium/cilium#29757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've found 200+ misspellings.
From https://github.com/cilium/cilium/pull/29753#issuecomment-1847954160

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

What is the the next step?

**Comment by kumarankit999** [comment]
Is there any remaining typos?

**Comment by szepeviktor** [comment]
No.

**Comment by kumarankit999** [comment]
I would like to work on it
/assign

**Comment by kumarankit999** [comment]
We can do one thing here, We can create a single PR for resolving 5-6 file typos.
We can easily achieve this goal!

**Comment by kumarankit999** [comment]
Let me know your views on this!
