### ISSUE TITLE
Endpoint transition from waiting-to-identity state to waiting-to-regenerate not supported

### ISSUE THREAD

**Issue by mougams** [cilium/cilium#29776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

For the the context, I have cilium agent running on a node independent from Kubernetes, connected to a dedicated etcd server.

While trying to create some custom endpoint using the API, with initial state as _models.EndpointStateWaitingDashForDashIdentity_, I get a state transition skipped error, causing the endpoint to be created:
 - in status _**waiting-for-identity**_ 
 - and the identity to stay forever as _no label id_

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY        LABELS (source:key[=value])                IPv6                 IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                    
3236       Unknown            Unknown           <no label id>   k8s:app=incubator-mynetns3                                      10.247.1.1   waiting-for-identity   
                                                                k8s:io.cilium.k8s.policy.cluster=default                                                            
                                                                k8s:io.kubernetes.pod.namespace=default 
```

From what I could see is that an endpoint could transition from waiting-to-identity state to waiting-to-regenerate, but it appears that [this case is not handled](https://github.com/cilium/cilium/blob/v1.4/pkg/endpoint/endpoint.go#L1688).

When I recompile cilium with the support of this transition as follow

```
diff --git a/pkg/endpoint/endpoint.go b/pkg/endpoint/endpoint.go
index ab689e8d54..674e68e82c 100644
--- a/pkg/endpoint/endpoint.go
+++ b/pkg/endpoint/endpoint.go
@@ -1364,7 +1364,7 @@ func (e *Endpoint) setState(toState State, reason string) bool {
                }
        case StateWaitingForIdentity:
                switch toState {
-               case StateReady, StateDisconnecting, StateInvalid:
+               case StateReady, StateDisconnecting, StateInvalid, StateWaitingToRegenerate:
                        goto OKState
                }
        case StateReady:
```
the endpoint creation gives following warning

`Endpoint lacks identity, skipping policy calculation`

and the endpoint becomes in
 - in status _**ready**_ 
 - and the identity stays forever as _no label id_

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY        LABELS (source:key[=value])                IPv6                 IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                    
331        Unknown            Unknown           <no label id>   k8s:app=incubator-mynetns3                                      10.247.1.1   ready   
                                                                k8s:io.cilium.k8s.policy.cluster=default                                             
                                                                k8s:io.kubernetes.pod.namespace=default                                              

```

```
2023-12-11T08:32:16.354860000Z level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4= ipv6= k8sPodName=/ subsys=daemon
2023-12-11T08:32:16.354917000Z level=warning msg="Endpoint lacks identity, skipping policy calculation" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2023-12-11T08:32:16.360608000Z level=warning msg="Endpoint lacks identity, skipping policy calculation" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2023-12-11T08:32:18.372274000Z level=info msg="Compiled new BPF template" BPFCompilationTime=2.004872253s file-path=/var/run/cilium/state/templates/364daf715b9c11c5d1ed671f9aefd56af5815691eb91baae26c525514a8fe5b5/bpf_lxc.o subsys=datapath-loader
2023-12-11T08:32:18.452824000Z level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```
Indeed, I could see the bpf program in the run directory

```
$ sudo tree /var/run/cilium/state/331
/var/run/cilium/state/331
├── bpf_lxc.o
├── ep_config.h
└── template.o -> /var/run/cilium/state/templates/364daf715b9c11c5d1ed671f9aefd56af5815691eb91baae26c525514a8fe5b5/bpf_lxc.o

0 directories, 3 files
```

After a restart of cilium-agent, the endpoint moves in restore state, and the endpoint is ready to be used, with identity created

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                IPv6                 IPv4         STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                               
331        Disabled           Disabled          21864      k8s:app=incubator-mynetns3                                      10.247.1.1   ready   
                                                           k8s:io.cilium.k8s.policy.cluster=default                                             
                                                           k8s:io.kubernetes.pod.namespace=default                                              

```

```
2023-12-11T08:41:54.231384000Z level=info msg="New endpoint" containerID=mynetns3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 ipv4=10.247.1.1 ipv6= k8sPodName=default/netsvc-incubator01-da1 subsys=endpoint
2023-12-11T08:41:54.231657000Z level=info msg="Successfully restored endpoint. Scheduling regeneration" endpointID=331 subsys=daemon
2023-12-11T08:41:54.233104000Z level=info msg="Reusing existing global key" key="k8s:app=netsvc-incubator01-da1-mynetns;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.kubernetes.pod.namespace=default;" subsys=allocator
2023-12-11T08:41:54.245346000Z level=info msg="Security identity for endpoint is different from the security identity restored for the endpoint" endpointID=331 identityLabels.new=21864 identityLabels.old=init subsys=endpoint
2023-12-11T08:41:59.243368000Z level=info msg="Identity of endpoint changed" containerID=mynetns3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=331 identity=21864 identityLabels="k8s:app=incubator-mynetns3,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.kubernetes.pod.namespace=default" ipv4=10.247.1.1 ipv6= k8sPodName=default/netsvc-incubator01-da1 oldIdentity=5 subsys=endpoint
2023-12-11T08:41:59.332702000Z level=info msg="Rewrote endpoint BPF program" containerID=mynetns3 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=331 identity=21864 ipv4=10.247.1.1 ipv6= k8sPodName=default/netsvc-incubator01-da1 subsys=endpoint
2023-12-11T08:41:59.333142000Z level=info msg="Restored endpoint" endpointID=331 ipAddr="[10.247.1.1 ]" subsys=endpoint
2023-12-11T08:41:59.333318000Z level=info msg="Finished regenerating restored endpoints" regenerated=4 subsys=daemon total=4
```

Once created, modulo the addition of the routes, the traffic is fully routable via cilium in the namespace, and policy are also enabled.

### Cilium Version

1.14

### Kernel Version

5.4.249

### Kubernetes Version

NA

### Relevant log output

```shell
Logs:
=====
	Invalid state transition skipped" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1473 endpointState.from=waiting-for-identity endpointState.to=waiting-to-regenerate


$ sudo cilium endpoint list
...
3236       Unknown            Unknown           <no label id>   k8s:app=incubator-mynetns3                                      10.247.1.1   waiting-for-identity   
                                                                k8s:io.cilium.k8s.policy.cluster=default                                                            
                                                                k8s:io.kubernetes.pod.namespace=default
```

### Anything else?

Initially raised in cilium slack https://cilium.slack.com/archives/C1MATJ5U5/p1702055222749189

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oblazek** [comment]
Hi, I believe the problem is because `NewEndpointFromChangeModel()` - https://github.com/cilium/cilium/blob/main/daemon/cmd/endpoint.go#L377 sets the endpoint labels from the base `EndpointChangeRequest`. 

But  https://github.com/cilium/cilium/blob/main/daemon/cmd/endpoint.go#L504 is expected to set the labels and bump the identity revision, but at this point there are no "new" labels, so it never returns true and the regen is skipped -> we are stuck in waiting-for-identity forever (until we update the labels or something)

**Comment by oblazek** [comment]
I think we should fix this, but will need some approval from one of the codeowners :)

**Comment by mougams** [comment]
I've tested with following patch on branch  1.14, and the endpoint is successfully created with the right status and identities without restarting cilium agent

```
diff --git a/pkg/endpoint/api.go b/pkg/endpoint/api.go
index 4ce1a242ff..df090446f7 100644
--- a/pkg/endpoint/api.go
+++ b/pkg/endpoint/api.go
@@ -18,7 +18,7 @@ import (
        identitymodel "github.com/cilium/cilium/pkg/identity/model"
        "github.com/cilium/cilium/pkg/labels"
        "github.com/cilium/cilium/pkg/labels/model"
-       "github.com/cilium/cilium/pkg/labelsfilter"
+       //"github.com/cilium/cilium/pkg/labelsfilter"
        "github.com/cilium/cilium/pkg/mac"
        "github.com/cilium/cilium/pkg/option"
        "github.com/cilium/cilium/pkg/policy"
@@ -129,12 +129,12 @@ func NewEndpointFromChangeModel(ctx context.Context, owner regeneration.Owner, p
                }
        }
 
-       if base.Labels != nil {
+       /*if base.Labels != nil {
                lbls := labels.NewLabelsFromModel(base.Labels)
                identityLabels, infoLabels := labelsfilter.Filter(lbls)
                ep.OpLabels.OrchestrationIdentity = identityLabels
                ep.OpLabels.OrchestrationInfo = infoLabels
-       }
+       }*/
 
        if base.State != nil {
                ep.setState(State(*base.State), "Endpoint creation")
diff --git a/pkg/endpoint/endpoint.go b/pkg/endpoint/endpoint.go
index ab689e8d54..674e68e82c 100644
--- a/pkg/endpoint/endpoint.go
+++ b/pkg/endpoint/endpoint.go
@@ -1364,7 +1364,7 @@ func (e *Endpoint) setState(toState State, reason string) bool {
                }
        case StateWaitingForIdentity:
                switch toState {
-               case StateReady, StateDisconnecting, StateInvalid:
+               case StateReady, StateDisconnecting, StateInvalid, StateWaitingToRegenerate:
                        goto OKState
                }
        case StateReady:

```

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                   IPv6   IPv4           STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                      
819        Disabled           Disabled          54719      k8s:app=incubator07                                  10.245.1.7     ready   
                                                           k8s:io.cilium.k8s.policy.cluster=default                                    
                                                           k8s:io.kubernetes.pod.namespace=default    
```

**Comment by christarazi** [comment]
I think the fact that you see

> From what I could see is that an endpoint could transition from waiting-to-identity state to waiting-to-regenerate, but it appears that [this case is not handled](https://github.com/cilium/cilium/blob/v1.4/pkg/endpoint/endpoint.go#L1688).

means something has gone wrong earlier in the endpoint creation process. It is valid not to handle this state transition because it's not supposed to be valid. This is a signal of something deeper is wrong.

The patch from @mougams above doesn't quite make sense to me because it's not obvious why removing the if condition is the correct root fix. This seems like a hacky stopgap to force the labels to be set. However, the labels of the endpoint can be nil upon creation and then the metadata resolver that is per endpoint should sync with k8s to fetch the labels of the pod. It seems like this is not happening. There should be a controller for this operation called `resolve-labels-<ns/podname>`. Is that running without errors in your cluster?

I see from your original report that 

> For the the context, I have cilium agent running on a node independent from Kubernetes, connected to a dedicated etcd server.

I assume this means the node still has k8s control plane access?

**Comment by oblazek** [comment]
@christarazi imagine you have all the information you need in `EndpointChangeRequest` (including the labels) and this is not a k8s environment -> you call `createEndpoint()` which later on calls `regenTriggered = ep.UpdateLabels(ctx, labels.LabelSourceAny, identityLbls, infoLabels, true)` , but as the labels are already set at this time you do not bump the identity revision and this code is never run:
```
if rev != 0 {
    return e.runIdentityResolver(ctx, rev, blocking)
}
``` 
which is exactly the reason why we should think about removing the above mentioned code:
```
if base.Labels != nil {
    lbls := labels.NewLabelsFromModel(base.Labels)
    identityLabels, infoLabels := labelsfilter.Filter(lbls)
    ep.OpLabels.OrchestrationIdentity = identityLabels
    ep.OpLabels.OrchestrationInfo = infoLabels
}
```

sidenote: if I actually remove the code unit tests run without any issues.

**Comment by mougams** [comment]
> I assume this means the node still has k8s control plane access?

I had the same issue when trying to run my code on an external workload.
Here, my cilium agent has only knowledge of the _etcd server,_ which it uses to fetch and populate all the information for the mesh connectivity.

**Comment by christarazi** [comment]
Ok, I'm following everything you've said above regarding labels and etcd. However, doesn't the following condition evaluate to `true` in your case, so it would be equivalent to removing the if condition like was proposed previously?

```
if base.Labels != nil {
```

**Comment by oblazek** [comment]
imho the problem is that we cannot `createEndpoint()` with labels in a single step.. if we don't remove that 
```
if base.Labels != nil {
```
then base.Labels is not nil, i.e. the condition is run and `ep.OpLabels.OrchestrationIdentity` are set and cannot be set in the following call to `UpdateLabels` -> the identityRegeneration is not triggered

**Comment by christarazi** [comment]
But if you remove the condition

> ```
> if base.Labels != nil {
> ```

then doesn't `ep.OpLabels.OrchestrationIdentity` get set, all the same, causing `UpdateLabels` to not trigger the identity regeneration?

**Comment by oblazek** [comment]
but that is exactly the problem, if we keep this condition (I suggest we remove it completely), then `ep.OpLabels.OrchestrationIdentity` gets set in the `NewEndpointFromChangeModel()` and https://github.com/cilium/cilium/blob/main/pkg/endpoint/endpoint.go#L1180 won't return true -> the revision won't be incremented -> which is the problem

**Comment by oblazek** [comment]
just did a few tests, seems to me it can be removed, but PatchEndpoint() needs it, so will require some additional changes.

**Comment by christarazi** [comment]
Thanks for spending effort on this, please file a PR when you have a set of changes ready to go.
