### ISSUE TITLE
CFP: Implement Egress IP feature

### ISSUE THREAD

**Issue by tuxtof** [cilium/cilium#29782]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

As a customer i need to be able to ensure that the traffic from one or more pods in one or more namespaces has a consistent source IP address for services outside the cluster network.
I need to be able to do that for plenty of different pods or namespaces assigning specific IP each time 

Egress GW don't allow to solve this issue

**Describe the feature you'd like**

An egress IP address is implemented as an additional IP address on the primary network interface of a node and must be in the same subnet as the primary IP address of the node. The additional IP address must not be assigned to any other node in the cluster.
It can be assigned to a namespace or a pods

similar feature are existing in other CNI like kube-ovn

**Comment by joestringer** [comment]
Hi @tuxtof , there is significant overlap between this proposal and the [Egress Gateway](https://docs.cilium.io/en/stable/network/egress-gateway/#id1) feature. Could you explain a bit more about how this proposal would be different and maybe why the existing feature doesn't cover that use case?

**Comment by tuxtof** [comment]
Hello @joestringer let me try to give more details

let's take the more simple example where we set egressGateway interface and we get dynamically the egress IP

some issues are:
- if we use dynamic k8s node pool where node IP change during pool upgrade, egress IP will change breaking your external firewall rules
- if you want to manage a big number of namespace/tenant each using their own egress IP, you need to have a lot of gateway (one for each tenant/ns)

we can also select a specific ip on the egressgateway but there is no way to set it dynamically and no failover mechanism

this is clearly the kind of problem we need to fix here with egress IP feature, or egressgateway improvement


hope this is more clear

**Comment by squeed** [comment]
> if we use dynamic k8s node pool where node IP change during pool upgrade, egress IP will change breaking your external firewall rules

That is not a good use case for egress gateway; if you rely on static IPs, you will need a way to provide static IPs to the egress gateways. A core set of non-dynamic nodes, with ENIs (or equivalent) would be a better architecture.

> if you want to manage a big number of namespace/tenant each using their own egress IP, you need to have a lot of gateway (one for each tenant/ns)

AIUI Egress Gateway is not namespace-specific the policies are non-namespaced. So you are free to mix and match namespaces.

What sort of failover are you envisioning?
