### ISSUE TITLE
Connection refused while accessing service from outside the cluster

### ISSUE THREAD

**Issue by madushanTHAMB** [cilium/cilium#29821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello guys ! It's very rare that i ask issues because i always found an existing issues but now i searched for 3 days and i can't find any solutions to my problem. I hope you have somes good advices for me cause i need you !
I have my K8S cluster and i want to expose my elasticsearch service from outside.
For my configuration, i'm using CIlium for security and also for ingress so i have a ingress controller activate.
I don't want to use the field external_IP, i want to use my LoadBalancer : 

cilium-ingress   LoadBalancer   10.X.X.X(internal)   10.X.X.X(external)   443:30277/TCP    3h21m
elasticsearch-service               ClusterIP      10.X.X.X      <none>           9200/TCP         177m

Here are my configurations:

My pod config yaml:

####################### POD CONFIG ##########################################
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: stack-es
  namespace: eck
spec:
  version: 8.9.1
  http:
    tls:
      certificate:
        secretName: elastic-certs
  nodeSets:
  - name: master
    count: 3
    config:
      node.roles: ["master"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: "30Gi"
              cpu: "6"
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        labels:
          node: master
      spec
        storageClassName: rook-ceph-block
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
  - name: data
    count: 3
    config:
      node.roles: ["data"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: "30Gi"
              cpu: "6"
          volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        labels:
          node: data
      spec:
        storageClassName: rook-ceph-block
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Ti
############################################################

Here my service file : 
############################################################
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: eck
spec:
  selector:
      elasticsearch.k8s.elastic.co/cluster-name: stack-es
  ports:
    - protocol: TCP
      port: 9200
##########################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-elasticsearch
  namespace: eck
  annotations:
    ingress.cilium.io/tls-passthrough: "enabled"
    io.cilium/proxy-protocol: "tcp"
spec:
  ingressClassName: cilium
  rules:
  - host: test-elasticsearch.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-service
            port:
              number: 9200
  tls:
  - hosts:
    - test-elasticsearch.com
    secretName: elastic-certs

############################################################

As you can see my prompt for the ingress : 

ingress-elasticsearch   cilium   test-elasticsearch.tech.private.sfr.com   10.X.X.X  80, 443   3h34m

And when i'm curling it : curl -k https://curl https://test-elasticsearch.tech.private.sfr.com -k
I'm getting this(im skipping the ssl) : 
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}

So it's working ! But when i'm doing this outside the cluster i got a connection refused ! 
So i try to put certificates etc ... But it's doesnt work.

Here my cilium configuration:
cluster:
  id: 0
  name: k02
encryption:
  nodeEncryption: false
kubeProxyReplacement: true
gatewayAPI:
  enabled: true
bpf:
  masquerade: true
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.10.0.0/16"
ipv4NativeRoutingCIDR: "10.10.0.0/16"
k8sServiceHost: "XXXXX"
k8sServicePort: "6443"
ingressController:
  enabled: true
  loadbalancerMode: "shared"
l2announcements:
  enabled: true
devices: "XX"
enableIPv4BIGTCP: true
externalIPs:
  enabled: true
hubble:
  peerService:
    clusterDomain: "X"
  relay:
    enabled: true
    podLabels: {site: X}
  ui:
    enabled: true
operator:
  replicas: 1
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
routingMode: native
autoDirectNodeRoutes: true

I hope someone can help me for that one ! 
Thanks for you help !

### Cilium Version

v1.14.4

### Kernel Version

Linux 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4

### Anything else?

I already checked logs etc, there is nothing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by firstdorsal** [comment]
how did you solve it?
