### ISSUE TITLE
internalLifecycle breaks `cilium-agent hive` output

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#29828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Commit 7f94c897a11bc0a9f13e1c965d8f2ae2b160360f added "internalLifecycle" to allow attaching of lifecycle hooks for cell internals.

This breaks the output of cilium-agent hive output, where the hooks added via lifecycle.Lifecycle now are showing the wrong function name and location:
```
hive.(*internalLifecycle).Append.func2 (pkg/hive/hive.go:185) 
```

### Cilium Version

main/v1.15

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joamaki** [comment]
Fixed in https://github.com/cilium/cilium/pull/30416
