### ISSUE TITLE
Cilium should reconcile missed node delete events

### ISSUE THREAD

**Issue by rgo3** [cilium/cilium#29822]
Cilium can miss `NodeDelete` events from Kubernetes, e.g when nodes get deleted during an upgrade while the cilium agent is down. This leads to leaking of resources (e.g. xfrm states/policies, node IDs) if a subsystem in cilium that subscribes to node events doesn't implement reconciliation/garbage collection. https://github.com/cilium/cilium/issues/26298#issuecomment-1832023965 offers a handful of steps to reproduce the bug.

Some subsystems already implement garbage collection to a certain degree for themselves, e.g. the [wireguard agent](https://github.com/cilium/cilium/blob/6ae935476e296986bd9e8ed7d3335748a3f3f727/pkg/wireguard/agent/agent.go#L293), however any feature depending on the `linuxNodeHandler` for cleanup suffers from the described issue.

This issue should track the design and development of a reconciler that ensures that the cilium agent knows about the same set of nodes that are currently in the Kubernetes cluster, triggering the cleanup of node-specific resources and unifying garbage collection functionality across all subsystems that subscribe to the `NodeManager`. 

An implementation approach could be based on the [Generic Reconciler](https://github.com/cilium/cilium/pull/29698) that was merged into the cilium code base for 1.16

**Comment by aanm** [comment]
@rgo3 can we edit the GH issue description to be more precise about what we want to accomplish? It's not clear enough which components within Cilium should reconcile missed node delete events.
