### ISSUE TITLE
Automate SPIRE image bumps via renovate

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#29839]
Currently the renovate SPIRE image bump automation to bump the version is being skipped (see [this comment](https://github.com/cilium/cilium/pull/29802#discussion_r1424925789) from @sayboras).

This issue tracks re-enabling the automation.

**Comment by joestringer** [comment]
Whenever we fix this on main, we'll want to add a stanza to apply the same renovate config for v1.15 (bounding the release to <1.9).

**Comment by kfox1111** [comment]
Not sure the right place to start the conversation, but this might be the right audience? The spire folks have a helm chart now located at https://github.com/spiffe/helm-charts-hardened thats getting close to 1.0 and has quite a few features in it now. Would it make sense to consider embeding that chart rather then maintaining your own objects?

**Comment by joestringer** [comment]
@meyskens @sayboras maybe you folks have some thoughts on the above from @kfox1111 ?

**Comment by meyskens** [comment]
@kfox1111 could you file a separate issue for that, it sounds interesting :) Would be nice to follow up on this and also get the people who maintain our helm chart involved to see how we best tackle this. 

The background on that is what when we started the closest we had to a Helm chart were a few example deployments and the starts of a chart we never made a proper work item to look back onto this.

**Comment by sayboras** [comment]
The upstream chart was developed almost at the same time when we added spire support in Cilium, but during that time it didn't have a couple of features we want (e.g. init step to configure custom admin identity). This might not be true now, we can continue the discussion in #30106.

Thanks again for bringing this up.

**Comment by sayboras** [comment]
This is done recently with the help of post upgrade task in renovate.
