### ISSUE TITLE
cilium gateway LodaBalancer Inaccessible 

### ISSUE THREAD

**Issue by 905839698** [cilium/cilium#29836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1；helm upgrade cilium cilium/cilium --version 1.15.0-pre.3     --namespace kube-system     --set operator.replicas=2     --set hubble.relay.enabled=true     --set hubble.ui.enabled=true     --set tunnel=disabled     --set kubeProxyReplacement=true     --set bpf.masquerade=true     --set loadBalancer.mode=dsr     --set bandwidthManager.enabled=true     --set ipam.mode=kubernetes     --set ipv4NativeRoutingCIDR=172.20.0.0/16      --set autoDirectNodeRoutes=true     --set k8sServiceHost=192.168.8.66     --set k8sServicePort=6443     --set gatewayAPI.enabled=true     --set prometheus.enabled=true     --set operator.prometheus.enabled=true        --set hubble.enabled=true        --set hubble.metrics.enableOpenMetrics=true        --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}"     --set lbExternalClusterIP=true     --set l2announcements.enabled=true           --set routingMode=native  --set hostFirewall.enabled=true --set HostPort.enabled=true --set socketLB.enabled=true   --set rollOutCiliumPods=true --set pmtuDiscovery.enabled=true --set  bpf.hostLegacyRouting=false --set bpf.tproxy=true
2、kubectl.exe get gateway
NAME                 CLASS    ADDRESS        PROGRAMMED   AGE
helloworld-gateway   cilium   192.168.8.99   True         42h
3、LoadBalancer is cilium L2 Announcements

### Cilium Version

1.15.0-pre.3

### Kernel Version

Linux master 5.14.0-362.8.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 8 17:36:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.28.1

### Sysdump

🔍 Collecting sysdump with cilium-cli version: v0.15.12, args: [sysdump]
🔮 Detected Cilium installation in namespace "kube-system"
🔮 Detected Cilium operator in namespace "kube-system"
ℹ️ Failed to detect Cilium SPIRE installation - using Cilium namespace as Cilium SPIRE namespace: kube-system
🔍 Collecting Kubernetes nodes
🔮 Detected Cilium features: map[cidr-match-nodes:Disabled cni-chaining:Disabled:none enable-envoy-config:Enabled enable-gateway-api:Enabled enable-ipv4-egress-gateway:Disabled endpoint-routes:Disabled ingress-controller:Disabled ipv4:Enabled ipv6:Disabled mutual-auth-spiffe:Disabled wireguard-encapsulate:Disabled]
🔍 Collect Kubernetes nodes
🔍 Collecting Kubernetes events
🔍 Collect Kubernetes version
🔍 Collecting Kubernetes namespaces
🔍 Collecting Kubernetes pods
🔍 Collecting Kubernetes services
🔍 Collecting Kubernetes pods summary
🔍 Collecting Kubernetes endpoints
🔍 Collecting Kubernetes network policies
🔍 Collecting Kubernetes metrics
🔍 Collecting Kubernetes leases
🔍 Collecting Cilium cluster-wide network policies
🔍 Collecting Cilium network policies
🔍 Collecting Cilium Egress Gateway policies
🔍 Collecting Cilium egress NAT policies
🔍 Collecting Cilium local redirect policies
🔍 Collecting Cilium CIDR Groups
🔍 Collecting Cilium endpoint slices
🔍 Collecting Cilium endpoints
🔍 Collecting Cilium nodes
🔍 Collecting Cilium identities
🔍 Collecting Ingresses
🔍 Collecting Cilium Node Configs
🔍 Collecting Cilium BGP Peering Policies
🔍 Collecting IngressClasses
🔍 Collecting Cilium LoadBalancer IP Pools
🔍 Collecting Cilium Pod IP Pools
🔍 Collecting the Cilium configuration
🔍 Checking if cilium-etcd-secrets exists in kube-system namespace
🔍 Collecting the Cilium daemonset(s)
🔍 Collecting the Cilium Node Init daemonset
🔍 Collecting the Cilium Envoy configuration
🔍 Collecting the Cilium Envoy daemonset
🔍 Collecting the Hubble daemonset
🔍 Collecting the Hubble Relay configuration
🔍 Collecting the Hubble Relay deployment
🔍 Collecting the Hubble UI deployment
🔍 Collecting the Cilium operator deployment
🔍 Collecting the Cilium operator metrics
🔍 Collecting the clustermesh metrics
🔍 Collecting the 'clustermesh-apiserver' deployment
🔍 Collecting the CNI configuration files from Cilium pods
🔍 Collecting the CNI configmap
🔍 Collecting gops stats from Cilium pods
🔍 Collecting gops stats from Hubble pods
🔍 Collecting gops stats from Hubble Relay pods
⚠️ Daemonset "cilium-node-init" not found in namespace "kube-system" - this is expected if Node Init DaemonSet is not enabled
🔍 Collecting bugtool output from Cilium pods
⚠️ Daemonset "cilium-envoy" not found in namespace "kube-system" - this is expected if Envoy DaemonSet is not enabled
⚠️ Deployment "clustermesh-apiserver" not found in namespace "kube-system" - this is expected if 'clustermesh-apiserver' isn't enabled
🔍 Collecting profiling data from Cilium pods
🔍 Collecting logs from Cilium pods
🔍 Collecting logs from Cilium Envoy pods
🔍 Collecting logs from Cilium Node Init pods
Secret "cilium-etcd-secrets" not found in namespace "kube-system" - this is expected when using the CRD KVStore
🔍 Collecting logs from Cilium operator pods
🔍 Collecting logs from 'clustermesh-apiserver' pods
I1213 09:32:19.367706   13440 request.go:697] Waited for 1.1080605s due to client-side throttling, not priority and fairness, request: GET:https://192.168.8.66:6443/api/v1/namespaces/kube-system/pods?labelSelector=io.cilium%2Fapp%3Doperator
🔍 Collecting logs from Hubble pods
🔍 Collecting logs from Hubble Relay pods
🔍 Collecting logs from Hubble UI pods
🔍 Collecting platform-specific data
🔍 Collecting kvstore data
🔍 Collecting Cilium external workloads
🔍 Collecting Hubble flows from Cilium pods
🔍 Collecting bugtool output from Tetragon pods
🔍 Collecting Tetragon PodInfo custom resources
🔍 Collecting Tetragon tracing policies
🔍 Collecting Helm values from the release
🔍 Collecting GatewayClass entries
🔍 Collecting Gateway entries
🔍 Collecting ReferenceGrant entries
🔍 Collecting HTTPRoute entries
🔍 Collecting TLSRoute entries
W1213 09:32:27.174242   13440 warnings.go:70] The v1alpha2 version of ReferenceGrant has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
🔍 Collecting GRPCRoute entries
🔍 Collecting TCPRoute entries
🔍 Collecting UDPRoute entries
🔍 Collecting CiliumClusterwideEnvoyConfigs
🔍 Collecting CiliumEnvoyConfigs
⚠️ The following tasks failed, the sysdump may be incomplete:
⚠️ [13] Collecting Cilium egress NAT policies: failed to collect Cilium egress NAT policies: the server could not find the requested resource
⚠️ [14] Collecting Cilium Egress Gateway policies: failed to collect Cilium Egress Gateway policies: the server could not find the requested resource (get ciliumegressgatewaypolicies.cilium.io)
⚠️ [16] Collecting Cilium local redirect policies: failed to collect Cilium local redirect policies: the server could not find the requested resource (get ciliumlocalredirectpolicies.cilium.io)
⚠️ [18] Collecting Cilium endpoint slices: failed to collect Cilium endpoint slices: the server could not find the requested resource (get ciliumendpointslices.cilium.io)
⚠️ [24] Collecting Cilium BGP Peering Policies: failed to collect Cilium BGP Peering policies: the server could not find the requested resource (get ciliumbgppeeringpolicies.cilium.io)
⚠️ [31] Collecting the Cilium Envoy configuration: failed to collect the Cilium Envoy configuration: configmaps "cilium-envoy-config" not found
⚠️ [61] Collecting Tetragon PodInfo custom resources: failed to collect Tetragon PodInfo: the server could not find the requested resource (get podinfo.cilium.io)
⚠️ [62] Collecting Tetragon tracing policies: failed to collect Tetragon tracing policies: the server could not find the requested resource (get tracingpolicies.cilium.io)
⚠️ Please note that depending on your Cilium version and installation options, this may be expected
🗳 Compiling sysdump

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 905839698** [comment]
help

**Comment by squeed** [comment]
@905839698 can you provide some more information?

What configuration did you create? Who is talking to whom? What is failing?

Have you tried the [troubleshooting document](https://docs.cilium.io/en/latest/operations/troubleshooting/)?
