### ISSUE TITLE
CI: ConformanceGKE: DNS resolution timeout

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#29843]
Timeout when trying to resolve the domain name.

Happened at https://github.com/cilium/cilium/actions/runs/7182557500/job/19559365438:
```
[=] Test [no-policies] [1/58]
...
  [-] Scenario [no-policies/pod-to-world]
  [.] Action [no-policies/pod-to-world/http-to-google.com-0: cilium-test/client-5597ff4fdf-4ctrh (10.0.0.165) -> google.com-http (google.com:80)]
  [.] Action [no-policies/pod-to-world/https-to-google.com-0: cilium-test/client-5597ff4fdf-4ctrh (10.0.0.165) -> google.com-https (google.com:443)]
  [.] Action [no-policies/pod-to-world/https-to-google.com-index-0: cilium-test/client-5597ff4fdf-4ctrh (10.0.0.165) -> google.com-https-index (google.com:443)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 --retry 3 --retry-all-errors --retry-delay 3 [https://google.com:443/index.html](https://google.com/index.html)" failed: command failed (pod=cilium-test/client-5597ff4fdf-4ctrh, container=client): "curl: (28) Resolving timed out after 2001 milliseconds\n"
```
Sysdumps: 
[cilium-sysdumps(1).zip](https://github.com/cilium/cilium/files/13658990/cilium-sysdumps.1.zip)

Seems similar to https://github.com/cilium/cilium/issues/27799.

**Comment by brlbil** [comment]
The latest occurrence of the same issue https://github.com/cilium/cilium/actions/runs/7525941420/job/20483164922

Sysdumps: [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/13937158/cilium-sysdumps.zip)

**Comment by thorn3r** [comment]
Hit on https://github.com/cilium/cilium/actions/runs/7631765730/job/20790500641 in https://github.com/cilium/cilium/pull/30361
Sysdump: [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/14029989/cilium-sysdumps.zip)
