### ISSUE TITLE
CI: Cilium IPsec Upgrade: `cannot open '/proc/pagetypeinfo' for reading`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#29851]
Whenever we have a failure in the IPsec upgrade test, we fail to upload the sysdump because the Fetch artifact step fails with:
```
==> /proc/buddyinfo <==
Node 0, zone      DMA      0      0      0      0      0      0      0      0      1      2      2 
Node 0, zone    DMA32    233    270    284    224    173    129     74     38     15     13      3 
Node 0, zone   Normal  14151  21993  14503   8331   4236   2030    735    271     88     36     62 
head: cannot open '/proc/pagetypeinfo' for reading: Permission denied
```
Example: https://github.com/cilium/cilium/actions/runs/7190939610/job/19584878094.

**Comment by pchaigno** [comment]
Maybe started failing with https://github.com/cilium/cilium/commit/cd93d3774959645dc3f12157c2544a3d9c16df57? cc @brb

**Comment by brb** [comment]
Good catch, true. Do we still need that `cat /proc/pagetypeinfo`?

**Comment by pchaigno** [comment]
IDK. You'd need to ask whoever added that. The original issue got closed only because the stale bot closed it.

**Comment by brb** [comment]
Let's drop it. Getting a sysdump is more important. In the worst case we can re-add it (either to bugtool, or ssh and then cat).

**Comment by pchaigno** [comment]
Are you taking care of it?
