### ISSUE TITLE
CI: Conformance E2E (ci-e2e)

### ISSUE THREAD

**Issue by pippolo84** [cilium/cilium#29857]
Setup & Test (12, bpf-next-20231211.012942, none, true, {eth0,eth1}, true, disabled, wireguard, t... https://github.com/cilium/cilium/actions/runs/7192965549/job/19590476147

```
[=] Test [pod-to-ingress-service] [57/64]
.
  [-] Scenario [pod-to-ingress-service/pod-to-ingress-service]
  [.] Action [pod-to-ingress-service/pod-to-ingress-service/curl-0: cilium-test/client-75bff5f5b9-qcpx2 (10.244.2.43) -> /cilium-ingress-ingress-service (cilium-ingress-ingress-service.:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 [http://cilium-ingress-ingress-service.:80](http://cilium-ingress-ingress-service./)" failed: error with exec request (pod=cilium-test/client-75bff5f5b9-qcpx2, container=client): command terminated with exit code 6
```

Full logs: [logs_1965652.zip](https://github.com/cilium/cilium/files/13660002/logs_1965652.zip)
Sysdump: too big :(

**Comment by learnitall** [comment]
Hit [here](https://github.com/cilium/cilium/actions/runs/7545131009/job/20540078469) for PR https://github.com/cilium/cilium/pull/29796

**Comment by thorn3r** [comment]
Hit on https://github.com/cilium/cilium/pull/30361 in https://github.com/cilium/cilium/actions/runs/8088292242/job/22102049585
Sysdump: 
[Uploading cilium-sysdump-20240228-232543.zip…]()

**Comment by thorn3r** [comment]
Sysdump didn't attach correctly:
[cilium-sysdump-20240228-232543.zip](https://github.com/cilium/cilium/files/14442909/cilium-sysdump-20240228-232543.zip)
