### ISSUE TITLE
CI: Jenkinsfile logic for master builds isn't working correctly

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2985]
A build of the master branch of Cilium using the Ginkgo CI  uses the `BDD-PR` section of the Jenkinsfile instead of the `BDD-Master` section. Luckily, there is no issue here as the two sections are functionally equivalent in terms of the tests that are ran at this point in time, but since there has been discussion to use different logic for when builds should fail for PRs vs in master, it behooves us to make sure this works correctly.

Note how BDD-Master is skipped and BDD-PR is used here: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/277/flowGraphTable/

Jenkinsfile logic:
```
  stage('BDD-Test-Master') {
            when {
                expression {
                    return env.GIT_BRANCH == 'origin/master';
                }
            }
...
 stage('BDD-Test-PR') {
            when {
                expression {
                    return env.GIT_BRANCH != 'origin/master';
                }
            }
...
```

I wonder if it is because the branch name is 'master' and not 'origin/master'? I wasn't able to find what the value of `GIT_BRANCH` in the environment was when triaging this issue.

https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/277/git/ shows that this may be the case.

**Comment by eloycoto** [comment]
Fixed by https://github.com/cilium/cilium/pull/3082
