### ISSUE TITLE
Optimize `make update-authors`

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#29882]
One of the steps during the release process is to ensure that the list of `AUTHORS` in the repo is up to date. We currently manage this by running `make update-authors`. This currently takes me about 3.5 minutes on my system to run. It'd be nice if this ran within a few seconds.

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by mohmaaya** [comment]
Hi, I am interested and would be glad to get to work on this.

**Comment by joestringer** [comment]
Hi folks, you're welcome to start working on it, and if you two are both interested then perhaps you could discuss together on Slack #development channel on how to tackle the problem and propose a solution?

I think the first step would be to start digging into what `make update-authors` does under the hood to extract the set of authors out of the git history, maybe profile where the time is spent with some userspace tooling, and then see whether there might be either a reliable faster method to extract the information from git, or perhaps to create some kind of cache for AUTHORS prior to a particular commit reference so that subsequent attempts do not need to iterate so far back into git history.

**Comment by mohmaaya** [comment]
Sound good to me and I am up for it. @20RitikSingh let me know if you are up for discussing.

**Comment by 20RitikSingh** [comment]
sure.

**Comment by 20RitikSingh** [comment]
so , there is this file of [AUTHORS](https://github.com/cilium/cilium/blob/main/AUTHORS) so we can just find the last release date and only query git for that duration by using "`--since`" flag in `git shortlog --summary ` .
@joestringer  should i go ahead with this approach?

**Comment by joestringer** [comment]
One tricky part here is that we will run `make update-authors` separately on each branch - for example `main`, `v1.15`, `v1.14`, and each currently-maintained older release branch. So if we detect since the last release by default, then that last release should probably be determined based on the local branch version. You can see the current version in the `VERSION` file in each branch, and I think there's some scripts under `contrib/` which also have some code to detect previous versions.

I think it would be good to also ensure that there is still a way to generate the full AUTHORS list since the beginning just in case we want to double-check that nothing was missed during the incremental updates since a recent release.

**Comment by joestringer** [comment]
IIRC the script also currently completely deletes the entire authors file and generates it from scratch. So if this only runs with `--since`, then you'd also need to stitch the new diff of authors into the existing file.

I'll also mention we currently implement this with a relatively simple shell scripts. If it's simple enough to implement in shell, you are welcome to implement that way. Alternatively, if shell becomes unwieldy to implement this, then you could alternatively consider writing a replacement for `contrib/scripts/extract_authors.sh` in Go with this new feature and add it to `tools/`.

**Comment by 20RitikSingh** [comment]
i tried using `git shortlog --email --summary --format="%aN%aE"|awk '{$1=" ";print $0}'|awk -F '[<>]' '{ printf "%-40s %s\n", substr($1,1,40), $2 }'` to replace logic of `contrib/scripts/extract_authors.sh` but due to non ascii characters its acting up in few places
[temp.txt](https://github.com/cilium/cilium/files/13689308/temp.txt)

**Comment by 20RitikSingh** [comment]
`git shortlog --email --summary --format="%<|(40)%aN%aE"|awk '{$1=" ";print $0}'|sort -u` this  also works if you are fine with this output
[temp.txt](https://github.com/cilium/cilium/files/13689382/temp.txt)

**Comment by joestringer** [comment]
As I understand, André has been working on improving this in the cilium/release tooling: https://github.com/cilium/release/pull/196 .

**Comment by joestringer** [comment]
@aanm is this faster now in the implementation in cilium/release ? Should we remove the update-authors make targets in the tree?

**Comment by aanm** [comment]
> @aanm is this faster now in the implementation in cilium/release ? Should we remove the update-authors make targets in the tree?

It depends, do we have intentions of updating authors outside of the release process? If yes then we just need to add a command line option to the release tool to update authors.

**Comment by joestringer** [comment]
I don't usually do that outside of release schedules, but sometimes during the release process I find that the authors file gets a bit messed up and I need to re-run it, particularly after editing `.mailmap`. I guess we can leave it for the moment. Either way I think we've effectively achieved the goal of this issue, and we can always remove the target later if we add a dedicated command in cilium/release.
