### ISSUE TITLE
DSR IP Option preserved in packet forwarded to backend

### ISSUE THREAD

**Issue by sypakine** [cilium/cilium#29900]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

When using IP option based DSR (`bpf-lb-mode: dsr` + `bpf-lb-dsr-dispatch: opt`), the packet forwarded to the backend endpoint preserves the IP option . We are using Windows KubeVirt VMs, which drop packets that contain IP options and are looking to remove or control the presence of the option when forwarding to the backend.

According to tests, this is intended behavior:

https://github.com/cilium/cilium/blob/0363a2ebbe500f484bbbae7853079b731dddb6de/bpf/tests/tc_nodeport_lb4_dsr_backend.c#L230-L237

I have a change which drops the DSR option from the packet and recalculates the checksum(s) before forwarding, but I am looking for input on whether there are legitimate circumstances where we would want to preserve the option. If so, this could be gated behind flag.

### Cilium Version

1.16.0-dev

### Kernel Version

N/A

### Kubernetes Version

 v1.27.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
>I have a change which drops the DSR option from the packet and recalculates the checksum(s) before forwarding, but I am looking for input on whether there are legitimate circumstances where we would want to preserve the option. If so, this could be gated behind flag.

Haven't given it too much thought, but I don't see any reason why the option would need to be preserved.

But I would suggest to still keep this behind a flag, so we can disable it for older kernels if necessary.

**Comment by julianwiedmann** [comment]
> We are using Windows KubeVirt VMs, which drop packets that contain IP options

just to confirm - this is *any* type of IP option, or just non-standard ones? Ideally we would only change the option type to `NOP`.

**Comment by sypakine** [comment]
> > We are using Windows KubeVirt VMs, which drop packets that contain IP options
> 
> just to confirm - this is _any_ type of IP option, or just non-standard ones? Ideally we would only change the option type to `NOP`.

This will only check for and remove the DSR IP Option:
https://sourcegraph.com/github.com/sypakine/cilium@ccec04ca682dbc4a590211837ca8138b85fe66a8/-/blob/bpf/lib/nodeport.h?L2097-2098

This approach is consistent with how we extract the IP option information:

https://github.com/cilium/cilium/blob/main/bpf/lib/nodeport.h#L2059-L2072

**Comment by julianwiedmann** [comment]
> > > We are using Windows KubeVirt VMs, which drop packets that contain IP options
> > 
> > 
> > just to confirm - this is _any_ type of IP option, or just non-standard ones? Ideally we would only change the option type to `NOP`.
> 
> This will only check for and remove the DSR IP Option: https://sourcegraph.com/github.com/sypakine/cilium@ccec04ca682dbc4a590211837ca8138b85fe66a8/-/blob/bpf/lib/nodeport.h?L2097-2098
> 
> This approach is consistent with how we extract the IP option information:
> 
> https://github.com/cilium/cilium/blob/main/bpf/lib/nodeport.h#L2059-L2072

I'm trying to understand whether it would be sufficient to memset with `IPOPT_NOP`, update the IPv4 header checksum and be done. But **not** call `ctx_adjust_hroom()` to actually remove the consumed space.

Would that work for Windows KubeVirt VMs, or do they reject **all types** of IP option?

**Comment by sypakine** [comment]
> Would that work for Windows KubeVirt VMs, or do they reject **all types** of IP option?

Let me test and confirm the behavior.

**Comment by sypakine** [comment]
When I set the option type as `NOP` and recalculate the IP checksum, the packet is silently dropped -- I don't even see it arrive at the Pod interface. My hypothesis is linux sees a `NOP` IP option with a length, which violates [RFC 791]:

> No Operation.  This option occupies only 1 octet; it has no length octet.

Given the above, we probably can't avoid resizing the option in either case. Would we prefer to change the option to `NOP` and resize, or drop the option all together and resize?

[RFC 791]: https://www.rfc-editor.org/rfc/rfc791.html

**Comment by julianwiedmann** [comment]
> When I set the option type as `NOP` and recalculate the IP checksum, the packet is silently dropped -- I don't even see it arrive at the Pod interface. My hypothesis is linux sees a `NOP` IP option with a length, which violates [RFC 791](https://www.rfc-editor.org/rfc/rfc791.html):
> 
> > No Operation.  This option occupies only 1 octet; it has no length octet.
> 
> Given the above, we probably can't avoid resizing the option in either case. Would we prefer to change the option to `NOP` and resize, or drop the option all together and resize?

How about `NOP` ing the full length? :)

**Comment by sypakine** [comment]
> > When I set the option type as `NOP` and recalculate the IP checksum, the packet is silently dropped -- I don't even see it arrive at the Pod interface. My hypothesis is linux sees a `NOP` IP option with a length, which violates [RFC 791](https://www.rfc-editor.org/rfc/rfc791.html):
> > > No Operation.  This option occupies only 1 octet; it has no length octet.
> > 
> > 
> > Given the above, we probably can't avoid resizing the option in either case. Would we prefer to change the option to `NOP` and resize, or drop the option all together and resize?
> 
> How about `NOP` ing the full length? :)

Attempted in https://github.com/sypakine/cilium/commit/1a0307069a31125f76564cf590b6a05501580a59, but the packet is being dropped silently (presumably by the kernel).

**Comment by sypakine** [comment]
> > > When I set the option type as `NOP` and recalculate the IP checksum, the packet is silently dropped -- I don't even see it arrive at the Pod interface. My hypothesis is linux sees a `NOP` IP option with a length, which violates [RFC 791](https://www.rfc-editor.org/rfc/rfc791.html):
> > > > No Operation.  This option occupies only 1 octet; it has no length octet.
> > > 
> > > 
> > > Given the above, we probably can't avoid resizing the option in either case. Would we prefer to change the option to `NOP` and resize, or drop the option all together and resize?
> > 
> > 
> > How about `NOP` ing the full length? :)
> 
> Attempted in [sypakine@1a03070](https://github.com/sypakine/cilium/commit/1a0307069a31125f76564cf590b6a05501580a59), but the packet is being dropped silently (presumably by the kernel).

The drops were due to L3 csum calculation. Resolved the issue.
