### ISSUE TITLE
set-string envoy.extraArgs can not use

### ISSUE THREAD

**Issue by bitcoffeeiux** [cilium/cilium#29949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I try to set the extra thread count parameter for envoy when I use cilium install, cilium does not install successfully.

command:
./cilium install --set-string envoy.enabled=true --set-string envoy.extraArgs=[{"concurrency":"2"}]

result:
Error: Unable to install Cilium: YAML parse error on cilium/templates/cilium-envoy/daemonset.yaml: error converting YAML to JSON: yaml: line 46: could not find expected ':'

### Cilium Version

1.14.4

### Kernel Version

5.10

### Kubernetes Version

1.20.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Can you try the below instead ? 

```
cilium install --set-string envoy.enabled=true --set-string envoy.extraArgs={"--concurrency 2"}
```
