### ISSUE TITLE
1.15.0 crashes when using prometheus targets

### ISSUE THREAD

**Issue by cornfeedhobo** [cilium/cilium#29975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am testing out the 1.15.0 images, using the 1.14.4 helm chart.

When setting `prometheus.enabled=true`, the cilium-envoy daemonset pods get stuck in a crashloop with the following error:

```plain
assert failure: get_capabilities(CAP_EFFECTIVE) == 0 && get_capabilities(CAP_PERMITTED) == 0. Details: cilium-envoy running with privileges, exiting
```

I have verified that all the other prometheus settings in the chart values do not cause this.

### Cilium Version

Every 1.15.0 pre-release is affected

### Kernel Version

6.6.6-1-default

### Kubernetes Version

v1.26.10+k3s2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by acelinkio** [comment]
You may want to try leveraging the pre-release helm charts for the pre-release images

chart: cilium
repoURL: https://helm.cilium.io/
targetRevision: 1.15.0-rc.0

When using helm cli, they can be found via
```
helm repo add cilium https://helm.cilium.io/
helm search repo cilium/cilium --versions --devel
```

**Comment by cornfeedhobo** [comment]
@acelinkio Thanks for the tip. I tried that yesterday, but that throws an unrelated error when trying to render any of the 1.15.0 charts and `serviceMonitor.enabled=true`:

```plain
cilium/templates/cilium-envoy/servicemonitor.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations
```

**Comment by cornfeedhobo** [comment]
@acelinkio You're right - the newer chart addresses this problem. Thanks.

Sadly, this led to uncovering a different bug in the charts related to ServiceMonitors :(
