### ISSUE TITLE
Hubble UI doesn't work with Cilium 1.14.x install, "Data stream has failed on the UI backend: EOF"

### ISSUE THREAD

**Issue by feimingc** [cilium/cilium#29977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/cilium/hubble-ui/issues/321

### Cilium Version

clium 1.14.x 

### Kernel Version

kernel 5.10

### Kubernetes Version

1.26.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
This isn't yet enough information to diagnose; can you please provide relevant pod logs, cluster status, etc.

**Comment by nijich** [comment]
I had this problem previously, and solved this by disabling the TLS verify.
