### ISSUE TITLE
CI: Cilium IPsec upgrade - unexpected packet drops on downgrade

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#29987]
## CI failure

Hit on https://github.com/cilium/cilium/pull/29896
Link: https://github.com/cilium/cilium/actions/runs/7258862919/job/19777306148
Sysdump: [cilium-sysdump-ipsec-downgrade-1-20231219-094253.zip](https://github.com/cilium/cilium/files/13716375/cilium-sysdump-ipsec-downgrade-1-20231219-094253.zip)

```
 [=] Test [no-unexpected-packet-drops] [3/71]

  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
  🟥 Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "Missed tail call"
  },
  "name": "cilium_drop_count_total",
  "value": 1
}
```

**Comment by ti-mo** [comment]
Related: https://github.com/cilium/cilium/issues/28088

**Comment by ti-mo** [comment]
@giorio94 Thanks for the report! As far as I can tell, the failed job downgraded to 1.14.5 (I'm assuming this is correct and it's not using unreleased v1.14 tip under the covers!) which doesn't have the latest round of fixes (the new 'Host datapath not ready' drop reason) yet. I remain hopeful that this will fix the issue once and for all. :smile:

**Comment by bimmlerd** [comment]
Hit in https://github.com/cilium/cilium/pull/31119 
Link: https://github.com/cilium/cilium/actions/runs/8140815226/job/22284010883#step:19:276
sysdump: [cilium-sysdump-ipsec-downgrade-1-20240305-085616.7z.zip](https://github.com/cilium/cilium/files/14496173/cilium-sysdump-ipsec-downgrade-1-20240305-085616.7z.zip) (sorry for the stupid format, but GH doesn't allow 7z files, and just zip was 30M :face_exhaling:)

**Comment by giorio94** [comment]
Hit on https://github.com/cilium/cilium/pull/31013
Link: https://github.com/cilium/cilium/actions/runs/8152624427/job/22282423609
Sysdump: [cilium-sysdump-ipsec-downgrade-1-20240305-080723.zip](https://github.com/cilium/cilium/files/14496951/cilium-sysdump-ipsec-downgrade-1-20240305-080723.zip)

**Comment by ti-mo** [comment]
Thanks for the reports, all.

@julianwiedmann FYI, we've found and fixed a few 'real' missed tail calls in the datapath revealed by static analysis on the bytecode: https://github.com/cilium/cilium/pull/30467/commits/672fccf5074094d989672728ce4dd7129dd6b9af.

Are these code paths that could potentially be triggered during up/downgrade tests, resulting in missed tail calls? I'm relatively confident the user space side is sound, even on release branches, so we may need to start looking into datapath itself. https://github.com/cilium/cilium/pull/30972 should provide more clarity on 1.16 but I've hit a small blocker and this still needs to be backported. Almost impossible to find the culprit until this lands.

**Comment by julianwiedmann** [comment]
> Thanks for the reports, all.
> 
> @julianwiedmann FYI, we've found and fixed a few 'real' missed tail calls in the datapath revealed by static analysis on the bytecode: [672fccf](https://github.com/cilium/cilium/commit/672fccf5074094d989672728ce4dd7129dd6b9af).
> 
> Are these code paths that could potentially be triggered during up/downgrade tests, resulting in missed tail calls?

Not for testing in combination with IPsec, unfortunately :/. So we're still chasing ...

> I'm relatively confident the user space side is sound, even on release branches, so we may need to start looking into datapath itself. #30972 should provide more clarity on 1.16 but I've hit a small blocker and this still needs to be backported. Almost impossible to find the culprit until this lands.

And there's no way to start debugging with a WIP branch, because we need actual builds for the up/downgrade? Hmpf.

**Comment by chancez** [comment]
> And there's no way to start debugging with a WIP branch, because we need actual builds for the up/downgrade? Hmpf.

**Comment by giorio94** [comment]
Hit on https://github.com/cilium/cilium/pull/31399 as well (on downgrade)
Link: https://github.com/cilium/cilium/actions/runs/8285336368/job/22707998046
Sysdump: [cilium-sysdump-ipsec-downgrade-1-20240315-141915.zip](https://github.com/cilium/cilium/files/14618311/cilium-sysdump-ipsec-downgrade-1-20240315-141915.zip)

**Comment by thorn3r** [comment]
Hit in https://github.com/cilium/cilium/actions/runs/8524886608/job/23350536331 on https://github.com/cilium/cilium/pull/31677
Sysdump: 
[cilium-sysdump-1-final.zip](https://github.com/cilium/cilium/files/14852805/cilium-sysdump-1-final.zip)

**Comment by thorn3r** [comment]
Hit again in https://github.com/cilium/cilium/actions/runs/8574999134/job/23504841663 on https://github.com/cilium/cilium/pull/31677

**Comment by giorio94** [comment]
One more: https://github.com/cilium/cilium/actions/runs/8630649349/job/23657371018
