### ISSUE TITLE
Node reachable but Endpoints unreachable

### ISSUE THREAD

**Issue by tengdagg** [cilium/cilium#29998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

My iptables and networkpolicies don't have any restriction, communication between nodes is also normal, what is the reason for this, now if pod is deployed to node02, I can only access the service using node02's IP:nodePort, and I can't access it from several other nodes! Please help me.

### Cilium Version

1.14.5

### Kernel Version

5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux

### Kubernetes Version

1.28.2

### Sysdump

[cilium-agent.log](https://github.com/cilium/cilium/files/13723913/cilium-agent.log)

### Relevant log output

```shell
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2875 identityLabels="reserved:health" ipv4=10.0.4.182 ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2875 identity=4 identityLabels="reserved:health" ipv4=10.0.4.182 ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
level=info msg="Compiled new BPF template" BPFCompilationTime=2.651617965s file-path=/var/run/cilium/state/templates/f6ba6d64bbd20634e5ca2ee342fdbea509201ce8dc3fa3516b2060876a11d615/bpf_lxc.o subsys=datapath-loader
level=info msg="Re-pinning map with ':pending' suffix" bpfMapName=cilium_calls_01500 bpfMapPath=/sys/fs/bpf/tc/globals/cilium_calls_01500 subsys=bpf
level=info msg="Re-pinning map with ':pending' suffix" bpfMapName=cilium_calls_01149 bpfMapPath=/sys/fs/bpf/tc/globals/cilium_calls_01149 subsys=bpf
level=info msg="Unpinning map after successful recreation" bpfMapName=cilium_calls_01500 bpfMapPath="/sys/fs/bpf/tc/globals/cilium_calls_01500:pending" subsys=bpf
level=info msg="Rewrote endpoint BPF program" containerID=417118907b datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=1500 identity=49090 ipv4=10.0.4.169 ipv6= k8sPodName=prometheus/prometheus-6ffd6bd4f8-vzb4x subsys=endpoint
level=info msg="Restored endpoint" endpointID=1500 ipAddr="[10.0.4.169 ]" subsys=endpoint
level=info msg="Unpinning map after successful recreation" bpfMapName=cilium_calls_01149 bpfMapPath="/sys/fs/bpf/tc/globals/cilium_calls_01149:pending" subsys=bpf
level=info msg="Rewrote endpoint BPF program" containerID=13f518f869 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=1149 identity=26617 ipv4=10.0.4.8 ipv6= k8sPodName=kmsserver/vlmcsd-7c64fd8d87-6lm7s subsys=endpoint
level=info msg="Restored endpoint" endpointID=1149 ipAddr="[10.0.4.8 ]" subsys=endpoint
level=info msg="Finished regenerating restored endpoints" regenerated=3 subsys=daemon total=3
level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_snat_v4_external subsys=daemon
level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_lb4_affinity subsys=daemon
level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_lb_affinity_match subsys=daemon
level=info msg="Removed stale bpf map" file-path=/sys/fs/bpf/tc/globals/cilium_lb4_source_range subsys=daemon
level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2875 identity=4 ipv4=10.0.4.182 ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Serving cilium health API at unix:///var/run/cilium/health.sock" subsys=health-server
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.00028450369346759197 newInterval=11m15s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0004911075661047719 newInterval=16m53s subsys=map-ct
level=info msg="Conntrack garbage collector interval recalculated" deleteRatio=0.0007485156697183074 newInterval=25m20s subsys=map-ct
```

### Anything else?

kubectl exec -n kube-system -t ds/cilium -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.28 (v1.28.0) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    False   [ens192  (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.5 (v1.14.5-85db28be)
NodeMonitor:             Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 2/254 allocated from 10.0.2.0/24,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:       22/22 healthy
Proxy Status:            OK, ip 10.0.2.184, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 1682/4095 (41.07%), Flows/s: 5.01   Metrics: Disabled
Encryption:              Disabled
Cluster health:          5/6 reachable   (2023-12-20T02:57:18Z)
  Name                   IP              Node        Endpoints
  k8sdevnode02           172.20.110.86   reachable   unreachable
  
  
  Checking the status of the cilium pod on node02 gives me this feedback
kubectl -n kube-system exec cilium-wm2vl -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.28 (v1.28.0) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    False   [ens192  (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.5 (v1.14.5-85db28be)
NodeMonitor:             Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 4/254 allocated from 10.0.4.0/24,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:       36/36 healthy
Proxy Status:            OK, ip 10.0.4.108, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 1024/4095 (25.01%), Flows/s: 1.60   Metrics: Disabled
Encryption:              Disabled
Cluster health:          1/6 reachable   (2023-12-20T03:01:50Z)
  Name                   IP              Node        Endpoints
  k8sdevmaster01         172.20.110.82   reachable   unreachable
  k8sdevmaster02         172.20.110.83   reachable   unreachable
  k8sdevmaster03         172.20.110.84   reachable   unreachable
  k8sdevnode01           172.20.110.85   reachable   unreachable
  k8sdevnode03           172.20.110.87   reachable   unreachable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AGou-ops** [comment]
same issue here.

**Comment by tengdagg** [comment]
@AGou-ops  I also rebooted but still the same problem, what version of K8S do you have?

**Comment by AGou-ops** [comment]
@tengdagg v1.25.12，and cilium 1.14.5.

Have you tried reinstalling Cilium and then rebooting the cluster?

**Comment by squeed** [comment]
Debugging this issue is highly installation-specific. You will need to ensure there is one of 
- Layer 2 connectivity between nodes, or
- use tunneling, such as vxlan or geneve

In general, `cilium install` should do the right thing. Likewise, `cilium connectivity test` may be of some use.
