### ISSUE TITLE
CFP: response substitution support in envoy

### ISSUE THREAD

**Issue by cornfeedhobo** [cilium/cilium#29992]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

Yes. If an application is not configured to support subpaths, it's common to rewrite
the response to include the subpath in any linked assets.

A common solution is to use nginx's `sub_filter` option.
This is how the Hubble UI pod works currently.

**Describe the feature you'd like**

I want to remove nginx when it's not needed and rely on envoy directly.

This isn't a requirement, but a nice-to-have.

**(Optional) Describe your proposed solution**

I wish I knew envoy enough to offer one. Good luck! :pray:

**Comment by squeed** [comment]
For the time being, it's likely we'll restrict support to the upstream [gateway api](https://gateway-api.sigs.k8s.io/guides/http-header-modifier/). So, a first step would be defining an API for that upstream :-).

I'm sure @youngnick would be happy to give a few pointers.

**Comment by youngnick** [comment]
So, from what I can see of the `sub_filter` options, it seems like this is a general search-and-replace across all content in the response? Envoy is generally not cool with modifying the response body, sadly. It's possible, but not easy.

If it's about rewriting paths in _requests_ or headers though, that we can do with existing Gateway API constructs.

**Comment by cornfeedhobo** [comment]
You are correct, it's a simple search and replace. If I recall correctly, envoy exposes some Lua scripting that may be of use towards this goal.
