### ISSUE TITLE
Logger used before being bootstrapped

### ISSUE THREAD

**Issue by antonipp** [cilium/cilium#30007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This issue is happening on agent / operator startup. The [`log` object in `pkg/option/config.go`](https://github.com/cilium/cilium/blob/1dc0bac5f048f66a5aab33ed677afc66f4c73a05/pkg/option/config.go#L46) is used before it is properly initialized. This results in logs not being properly formatted. 

For example if we start the agent with `--log-opt='format=json'`, the very first logs emitted by the agent are still formatted as k/v values:
```
$ kubectl logs cilium-agent-qgz98 | head
level=info msg="Memory available for map entries (0.003% of 66207707136B): 165519267B" subsys=config
level=info msg="option bpf-ct-global-any-max set by dynamic sizing to 290384" subsys=config
level=info msg="option bpf-neigh-global-max set by dynamic sizing to 524288" subsys=config
level=info msg="option bpf-sock-rev-map-max set by dynamic sizing to 290384" subsys=config
{"level":"info","msg":"  --agent-health-port='9879'","subsys":"daemon"}
{"level":"info","msg":"  --agent-labels=''","subsys":"daemon"}
{"level":"info","msg":"  --agent-not-ready-taint-key='node.cilium.io/agent-not-ready'","subsys":"daemon"}
```

This is due to the fact that the [`option.DaemonConfig.Populate()` method](https://github.com/cilium/cilium/blob/1dc0bac5f048f66a5aab33ed677afc66f4c73a05/pkg/option/config.go#L2867) is called before the logger is initialized and it is logging various things in there. 

It's happening in the Operator [here](https://github.com/cilium/cilium/blob/f7a29d380be02a3fef1819b2ee5d5cd959d890c9/operator/cmd/root.go#L187-L197) and in the Agent [here](https://github.com/cilium/cilium/blob/2c1cc4e9365c0cb90138a2f3cff6e6dd63930e4b/daemon/cmd/root.go#L63-L70).

It's kind of a chicken-and-egg problem because the `Populate` method is actually parsing the `LogOpt` values [here](https://github.com/cilium/cilium/blob/1dc0bac5f048f66a5aab33ed677afc66f4c73a05/pkg/option/config.go#L3240-L3244) so we can't really initialize the logger before the `LogOpt`s are parsed.

Not sure what would be the best fix here, maybe we can parse _only_ the `LogOpt`s right away, setup the loggers afterwards and only _then_ process all the other logic?  

### Cilium Version

`Daemon: 1.13.9 a65bfca8cc 2023-11-29T14:19:04-07:00 go version go1.20.11 linux/arm64`

### Kernel Version

`5.15.0-1050-aws`

### Kubernetes Version

`Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.6", GitCommit:"219d3257e999424d258e7e3bbd3afc1979bba8e4", GitTreeState:"clean", BuildDate:"2023-07-05T10:36:16Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/arm64"}`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Very good find :-). Thanks!

**Comment by jaredledvina** [comment]
Not stale!

**Comment by jaredledvina** [comment]
Still fresh!

**Comment by jaredledvina** [comment]
Still an issue on 1.14.13
