### ISSUE TITLE
Unable to access Application hosted on AKS on AGIC(application gateway ingress controller) when creating AKS with BYO CNI with Cilium. 

### ISSUE THREAD

**Issue by anilkumar1619** [cilium/cilium#30005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Unable to access Application hosted on AKS on AGIC(application gateway ingress controller) when creating AKS with BYO CNI with Cilium. 

Created AKS cluster with BYO CNI by following below document and installed Cilium using below documents. Receiving error 502 when accessing the application. 
AKS created by following https://learn.microsoft.com/en-us/azure/aks/use-byo-cni?tabs=azure-cli article
Cilium installed by following https://docs.cilium.io/en/v1.13/installation/k8s-install-helm/
AGIC configured by following https://learn.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new

Application yamls: https://learn.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new#deploy-a-sample-application-by-using-agic

Error: 
<img width="455" alt="image" src="https://github.com/cilium/cilium/assets/84578520/9a7b8527-a336-40d5-be02-164f34057169">
Couldn't find anything from any articles. 
Couple of articles says Cilium doesn't support L7. The same application is accessible if it is exposed on service type "load balancer"

### Cilium Version

1.13.10

### Kernel Version

Not sure installing with below command from https://docs.cilium.io/en/v1.13/installation/k8s-install-helm/ document. 
helm install cilium cilium/cilium --version 1.13.10 \
  --namespace kube-system \
  --set aksbyocni.enabled=true \
  --set nodeinit.enabled=true

### Kubernetes Version

1.27.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jaredthivener** [comment]
@anilkumar1619 - If you are using Azure CNI Overlay, it's not supported. https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay?tabs=kubectl#limitations-with-azure-cni-overlay
<img width="602" alt="Screenshot 2024-01-21 at 10 18 17 PM" src="https://github.com/cilium/cilium/assets/87688021/e32ac431-56d4-4f18-a63e-29d23cfc5240">

**Comment by squeed** [comment]
@jaredthivener thanks for the pointer :-). The Azure documents are mostly maintained by Microsoft, but if you can see any reasonable changes we can add to our docs, do feel free to submit a PR.

For now, I'll close this issue. Shout and I'll re-open it :-)
