### ISSUE TITLE
CFP: add a simple Service LoadBalancer node ipam

### ISSUE THREAD

**Issue by MrFreezeex** [cilium/cilium#30037]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**
In a context of  a Kubernetes cluster deployed on a "uncontrolled" network (i.e.: rented servers/vms where you don't have an equivalent to a "VPC" of some kinds) you could be in a context where you cannot use either  L2 or BGP Cilium features and thus you will not be able to use a Service of type LoadBalancer.

**Describe the feature you'd like**
This should work quite similarly to k3s ServiceLB (https://docs.k3s.io/networking#service-load-balancer) and fetch the selected pods and then get the Node addresses where the pods run at and "advertising" those into the service status. Using a Service of LoadBalancer type can be quite useful when using other controller that is using those, for instance ExternalDNS. 

**(Optional) Describe your proposed solution**
The proposal would be to add a new load balancer class called `io.cilium/node` to activate this feature. And also like k3s Service LB use `.spec.ipFamilies` to determine the type of addresses and then it would use preferably `ExternalIP` type addresses if any or `InternalIP` addresses otherwise. I don't plan to implement an equivalent to the labels `svccontroller.k3s.cattle.io/lbpool` and `svccontroller.k3s.cattle.io/enablelb` though.

**Comment by stevefan1999-personal** [comment]
> I don't plan to implement an equivalent to the labels svccontroller.k3s.cattle.io/lbpool and svccontroller.k3s.cattle.io/enablelb though.
But why?

**Comment by MrFreezeex** [comment]
> > I don't plan to implement an equivalent to the labels svccontroller.k3s.cattle.io/lbpool and svccontroller.k3s.cattle.io/enablelb though.
> 
> But why?

I don't have this use case and I believe most people who would use this feature too + not implementing it simplify the initial implementation and its review. But feel free to give it a shot an implement those features, I may do it in a few months but have other priorities atm.
