### ISSUE TITLE
Gateway API Source IP

### ISSUE THREAD

**Issue by nushkovg** [cilium/cilium#30042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current implementation of Gateway API through Envoy does not allow for getting the source IP of the requests done via the Gateway. I've seen that the Ingress Controller has support for enabling the proxy protocol in the latest version (`1.15.0-rc.0`), but the Gateway API still has no way to enable this.

For more context, I am running a self-hosted kubernetes cluster on a debian based server. The cluster is currently a single node one, and I have HAProxy running in front of the cluster as a reverse proxy. Enabling the proxy protocol on HAProxy side for the source IP to pass through will work only if the `Gateway` load balancer supports activating the proxy protocol on that side as well. Currently I am getting the public server IP as the source IP in the `x-forwarded-for` header, which is incorrect.

I will accept workarounds if they exist, so I am really open to discussion, since going back to Ingress just because of this feels...wrong.

### Cilium Version

cilium-cli: v0.15.19 compiled with go1.21.5 on linux/amd64
cilium image (default): v1.14.4
cilium image (stable): v1.14.5
cilium image (running): 1.14.5

### Kernel Version

Linux debian1 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
maybe @youngnick has an answer :-) ?

**Comment by chaunceyjiang** [comment]
> The current implementation of Gateway API through Envoy does not allow for getting the source IP of the requests done via the Gateway. I've seen that the Ingress Controller has support for enabling the proxy protocol in the latest version (1.15.0-rc.0), but the Gateway API still has no way to enable this.


Hi， @nushkovg  I've submitted a PR to implement this feature. Could you help me test whether this PR meets the requirements? You can directly use the image [here](https://github.com/cilium/cilium/actions/runs/7738494996/job/21099430270?pr=30567).

**Comment by youngnick** [comment]
Sorry for the delays everyone, and thanks for getting to this one @chaunceyjiang. Adding a mechanism to say "all Gateway API gateways will pass PROXY protocol", the same as the existing Ingress support seems like a reasonable step.

**Comment by youngnick** [comment]
I've recently merged some more documentation to the main Ingress and Gateway API (https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/gateway-api/#reference) and Ingress (https://docs.cilium.io/en/latest/network/servicemesh/ingress/#reference) docs with more information about how Client IP visibility works in Cilium, along with how Cilium's NetworkPolicy interacts with the `reserved:ingress` identity.

@mauricec73, please check that out and, if anything is unclear, open another issue and we'll see if we can update it  as needed.
