### ISSUE TITLE
CFP: Check if sysctl values need to be updated before write instead of blatant sysctl write to potentially read-only filesystem

### ISSUE THREAD

**Issue by jakeschurch** [cilium/cilium#30059]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

Ability to have hardened read-only proc filesystem is not allowed due to [enableIPForwarding](https://github.com/cilium/cilium/blob/2daca4c3935a43dac72044c7ca3e17ac57af2617/pkg/datapath/iptables/sysctl_linux.go#L10) always assuming that filesystem is readable / modifiable. When using read-only proc filesystem with load-balancing enabled ensures cilium-agent node crash, even if values have been set previously.

**Describe the feature you'd like**

Add work-around for read-only procfs or when sysctl writes are not allowed.

**(Optional) Describe your proposed solution**

Modify usage of [writeSysctl](https://github.com/cilium/cilium/blob/2daca4c3935a43dac72044c7ca3e17ac57af2617/pkg/sysctl/sysctl.go#L91) to read parameter path file if exists and checks if read value is set to `value` passed in writeSysctl fn.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by squeed** [comment]
Neat idea. I'd not heard of a read-only sysfs, but it's clearly not a bad idea.

What should happen if the desired sysctl is not set? Abort and exit?

**Comment by chaunceyjiang** [comment]
Hi, @jakeschurch I've submitted a PR based on your suggestion, could you help test it in your environment? Let's see if it meets your needs.
