### ISSUE TITLE
CFP: Pass cilium identity to called services

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cilium/cilium#30057]
## CFP: Pass Cilium identity to called services
        
**Is your proposed feature related to a problem?**

Cilium already offers strong identity authentication with mTLS and transport encryption with Wireguard/IPSec for service-to-service communication. Further, network policies can be used to granularly restrict the access between those services (i.e. with L7 policies access can be specified all the way down to the HTTP endpoint/verb level).

However, there are some scenarios where the called service would benefit if it could obtain the identity of the calling application. For example: A multi-tenant service serves multiple different client applications which have access to the same HTTP endpoint (i.e. `GET /events`) but the providing service should return specific events for the different calling application (for example consumer A receives events for tenant A, consumer B receives events for tenant B).

This is one example, but I am sure there are many where the application requires more finer-granular authorization logic than what L7 policies allow.

Some background:
- We come from a world with homegrown mTLS setup for service-to-service authentication where the called application usually used the CN of the client certificate to do further granular access control within the endpoints.
- It would be cool to retrieve the identity from Cilium, as Cilium has invested heavily to establish this identity (SPIFFE etc.). If we cannot reuse the identity from the Cilium layer, we basically have to manually establish identity on another layer (for example, by building yet another CA and doing mTLS on the app layer again, which would prevent us from using some Cilium features that rely on it being cleartext; or by using OAuth2 for service-to-service communication, which would mean we have to create an IDP, distribute client credentials etc.).

**Describe the feature you'd like**

It would be nice if Cilium could pass the identity information when doing service-to-service calls in the mesh.
We only require it for HTTP, but it could also be interesting for other L7 protocols.

Istio and Linkerd both support passing the client identity to HTTP services as headers:
- Istio (client certificate as HTTP header): https://stackoverflow.com/a/69767914
- Linkerd (identity as HTTP header): https://github.com/linkerd/linkerd2/issues/3756

(I'm fully aware that Cilium's sidecarless design probably makes this harder than a simple header injection done in a sidecar, but maybe there's a way to have custom `EnvoyConfig` which does this?)

**(Optional) Describe your proposed solution**

I could imagine that Cilium adds a HTTP header like `cilium-identity: <calling-application>`.

**Comment by EItanya** [comment]
This is an interesting idea, I do want to note one potential issue.

Cilium Identities are dynamic, meaning that the identity of a pod can change during its lifetime. Let's say for example the Namespace labels change for a pod, the identity would change, and therefore the passed header may no longer be accurate.

Usually when passing identity this way you are assured that the identity of the caller cannot change because it's cryptographically verified and cannot change.

SPIRE is able to issue JWTs quite easily as well as mTLS certs, maybe use that?

**Comment by Brightside56** [comment]
it could work at least using XFCC and its `by` field:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-client-cert

now we have to do terrible things to reinvent it, while Cilium could make it effortless
