### ISSUE TITLE
Slack rejecting new joiners again

### ISSUE THREAD

**Issue by NPastorale** [cilium/cilium#30069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While trying to join the Slack workspace, either via https://slack.cilium.io/ or https://cilium.slack.com/, the `The email address must match one of the domains listed below. Please try another email.` message is returned. This is when trying to join with an `@gmail.com` account.

The solution on #29103 does not work, and even though #24447 is closed, this is still happening

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xmulligan** [comment]
cc: @thebsdbox

**Comment by xmulligan** [comment]
Should be fixed now, can you confirm?

**Comment by NPastorale** [comment]
I was able to join via https://slack.cilium.io/

Thanks!

**Comment by camrossi** [comment]
@NPastorale I am having the same issue, do you want me to open a new Issue?

**Comment by xmulligan** [comment]
Yes, please open a new issue
