### ISSUE TITLE
Cilium fails to attach xdp to bonded interface

### ISSUE THREAD

**Issue by 0xAlcibiades** [cilium/cilium#30072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have 4 25 gbit mellanox NICs LACP bonded. Looks like the xdp program attempts to connect to the bond and fails.

`level=fatal msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface bond0: invalid argument" subsys=datapath-loader`

Looks similar to:

#25453 

### Cilium Version

v1.14.4

### Kernel Version

6.5.0-14-generic #14~22.04.1-Ubuntu

### Kubernetes Version

v1.29.0+rke2r1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xAlcibiades** [comment]
Checking in here, I have read a few other reports, wondering if it has something to do with the device cilium is attaching to natively, which is not something you can specify in the helm chart. That's just a hypothesis though.

**Comment by haribhusal2025** [comment]
I can confirm this. Cilium is not able to handle bond interface properly. When i included bond0 interface in "devices:" section of cilium-config. External Gitlab Webhooks were not able to reach services inside kubernetes cluster. I was getting "Error: Net::OpenTimeout". As a workaround, i removed bond0 interface from cilium config and just entered node-IP interface and webhooks are working fine.

**Comment by 0xAlcibiades** [comment]
So, I have reachability working just fine, but there seems to be an issue particularly with XDP, and supposedly this is supported in the bonding driver. May have to do with LACP vs active-active, etc after looking under the covers in the linux bonding driver. Would be great to get some input from @dylandreimerink or somebody else from the Cilium team here.

**Comment by julianwiedmann** [comment]
The kernel bonding driver only supports XDP for a limited set of bond modes:
https://elixir.bootlin.com/linux/v6.7.2/source/drivers/net/bonding/bond_main.c#L327
