### ISSUE TITLE
Cilium Envoy in standalone DaemonSet - ServiceMonitor has the wrong value for the endpoints.port

### ISSUE THREAD

**Issue by HummingMind** [cilium/cilium#30076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,
I am running Envoy as a standalone daemonSet.
I enabled the ServiceMonitor via the Helm chart. But my prometheus instance is not picking it up.

After some troubleshooting, I found that the ServiceMonitor has the endpoints.port specified as "metrics", but describing the cilium-envoy service shows that the port name is actually "envoy-metrics".

I made my own ServiceMonitor config to test it with the correct port name and it works just fine.

I am guessing this has something to do with inconsistent port naming for embedded vs standalone.

I can run with the manual ServiceMonitor for now, but this took me quite a bit of time to figure out. So I am sure it would help someone else to get this fixed.

Thank you!

### Cilium Version

1.14.5

### Kernel Version

Whatever Azure Linux hosts are running. Some flavor of Ubuntu 22.04.

### Kubernetes Version

1.28.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Argh! Good catch.

**Comment by aanm** [comment]
Closing since it was fixed by #27207 and it's available in 1.14.7. Feel free to open a new GH issue in case the issue persists. Thank you
