### ISSUE TITLE
can cilium resolve the ip of sts's pod using svc like below

### ISSUE THREAD

**Issue by 13567436138** [cilium/cilium#30074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!
![image](https://github.com/cilium/cilium/assets/31508490/1598af9f-59f1-4f33-8dbe-34a1618309df)

### Cilium Version

root@karmada-02-a:~# cilium version
cilium-cli: v0.13.0 compiled with go1.20 on linux/amd64
cilium image (default): v1.13.0
cilium image (stable): v1.14.5
cilium image (running): v1.14.4

### Kernel Version

root@karmada-02-a:~# uname -r
6.2.0-39-generic

### Kubernetes Version

1.28.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Have you taken a look at the [troubleshooting steps](https://docs.cilium.io/en/latest/operations/troubleshooting)? What were the results?
