### ISSUE TITLE
Build development setup quickly seems not work in 1.14.5

### ISSUE THREAD

**Issue by fuchencong** [cilium/cilium#30087]
Not sure if's it's bug or did I miss something? My cilium code version is 1.14.5.

[Slack Message](https://cilium.slack.com/archives/C2B917YHE/p1704252292170039?thread_ts=1704252292.170039&cid=C2B917YHE)

I tried to build a development setup in my host. Accroding to [Development Setup](https://docs.cilium.io/en/stable/contributing/development/dev_setup/). My steps are as follows

1. download cilium code
2. `make kind`: build kind cluster
3. install Cilium CLI
4. `make kind-install-cilium-fast`: install cilium to kind cluster
5. make some change to local code
6. `make kind-image-fas`t: build Cilium from local code, and install new binary target to kind cluster

But I found cilium-agent in Cilium Pod was not updated, Do I need to update it manually?

**new built cilium-agent**:
```bash
# docker exec -it kind-worker /bin/bash
root@kind-worker:/# md5sum cilium-binaries/cilium-agent
3a28c5dee3c307c0f579d3697d28c1d5  cilium-binaries/cilium-agent
```

**cilium-agent in Cilium pod not update**:

```bash
root@kind-worker:/# crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID              POD
09b6b11a6d8d1       a408285c55c0a       55 minutes ago      Running             cilium-agent        0                   ab58c8ef2f644       cilium-dvq9c
9358e02cf0d1c       9d5429f6d7697       3 hours ago         Running             kube-proxy          0                   82c6ec08eca37       kube-proxy-n227w
root@kind-worker:/# crictl exec -it 09b6b11a6d8d1 md5sum /usr/bin/cilium-agent
4891c042385142ac608faa9ea5bc2297  /usr/bin/cilium-agent
```

After some investigation and change, it seems work. Not sure if it's bug.

1. use `KIND_VALUES_FAST_FILES="--helm-values=contrib/testing/kind-fast.yaml" make kind-install-cilium-fast`  to install cilium
2. Add some code in `kind-image-fast` target

![image](https://github.com/cilium/cilium/assets/9530753/1c9a6160-1e33-419b-a316-b1be41032829)

**Comment by fuchencong** [comment]
Hi @joestringer 

I tried `main` branch, it works well.

**Comment by joestringer** [comment]
OK. In that case, you could work around by using the regular image targets instead of `-fast`, or develop on main. I doubt there is much interest in fixing this target in the v1.14 branch since we've already branched for the next stable release v1.15.x and all future development will be on main for v1.16.x.
