### ISSUE TITLE
cert-manager does not work with enforce-ingress-https=true

### ISSUE THREAD

**Issue by robkooper** [cilium/cilium#30094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- Running talos kubernetes v1.29.0 and cilium v1.50.0-rc1
- Deployed cilium with enforce-ingress-https=true and cert-manager
- Deploying a simple application with an ingress route that has the annotation `cert-manager.io/cluster-issuer: "letsencrypt-staging`

At this point as expected the cert-manager will create the ingress route. When trying to connect to the ingress route I get a 404:
```
> curl -v http://whoami.talos.ncsa.cloud/.well-known/acme-challenge/cdNC_t4sc60eWCYPxNpEarquMYtW8XZ1DlSS-YPy_kE
*   Trying XXXXXXX:80...
* Connected to whoami.XXXXX (XXXXXXX) port 80
> GET /.well-known/acme-challenge/cdNC_t4sc60eWCYPxNpEarquMYtW8XZ1DlSS-YPy_kE HTTP/1.1
> Host: XXXXXXX
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< date: Wed, 03 Jan 2024 23:31:07 GMT
< server: envoy
< content-length: 0
<
```

- disabling enforce-ingress-https `cilium config set enforce-ingress-https false` still results in a 404
- restarting the operator as well `kubectl -n kube-system rollout restart deployment cilium-operator` will result in a 200
- certificate is created

### Cilium Version

cilium:v1.15.0-rc.0

### Kernel Version

```
NAME                    VERSION   INTERNAL-IP     OS-IMAGE         KERNEL-VERSION   CONTAINER-RUNTIME
talos-controlplane-01   v1.29.0   192.168.3.25    Talos (v1.6.1)   6.1.69-talos     containerd://1.7.11
```

### Kubernetes Version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0

### Sysdump

[cilium-sysdump-20240103-173807.zip](https://github.com/cilium/cilium/files/13824390/cilium-sysdump-20240103-173807.zip)

### Anything else?

Using traefik as ingress controllers this works. Traefik is configured to rewrite the http to https connection, but a special annotation is added to the ingress route to not use the https port. I could not find a similar annotation in cilium, for example `ingress.cilium.io/enforce-ingress-https: false` This would be used by the ingress controller to prevent rewriting the route to be https

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
It seems there are two issues here.

First is that the docs say `enforceHttps` should return a 308 error code. From your bug, it seems that 404 is being returned, which is clearly incorrect.

Secondly, it seems like you'd like the ability to override https forcing. That comes with security implications; if the administrator has configured Cilium to force https, they may not want individual teams to be able to disable https. That will require a bit more of a careful design, as it is security-sensitive.

Thoughts?

**Comment by robkooper** [comment]
Looking closer at the lets-encrypt [docs](https://letsencrypt.org/docs/challenge-types/#http-01-challenge) it seems that it follows a redirect, in which case the 308 should do, and there is no need for allowing me to use HTTP.

**Comment by squeed** [comment]
Gotcha, so the bug, then, is that 308's are not being returned. Agreed?
