### ISSUE TITLE
Setting the ingress.cilium.io/websocket annotation on an ingress does nothing

### ISSUE THREAD

**Issue by judge-red** [cilium/cilium#30116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

According to the [docs](https://docs.cilium.io/en/stable/network/servicemesh/ingress/#supported-ingress-annotations), It's possible to set the `ingress.cilium.io/websocket: enabled` annotation on an ingress to, well, enable websockets over the ingress in question.

However, this setting seems to result in no actual change in the Envoy config and I can't get websockets to work.

### Cilium Version

1.14.5 (deployed through the Helm chart)

### Kernel Version

Linux <hostname> 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.27.9

### Anything else?

It appears that this annotation was introduced through this MR:
https://github.com/cilium/cilium/pull/20814

However, in `main` I can only find the `GetAnnotationWebsocketEnabled` function (in `operator/pkg/ingress/annotations/annotations.go`), but no code that is calling it (no idea what happened to the `operator/pkg/ingress/envoy_config.go` file either). So the annotation is ready but it doesn't seem to impact the Envoy config.

As you can see in the last comments in the MR, I'm not the only one who noticed that code went missing - but the contributor who raised this concern did not receive any reply so far and it's been a while.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
👋 

Thanks for your issue.

The websocket upgrade is enabled by default in recent versions, can you check if the related CEC config is still having the attribute `UpgradeType: "websocket"`.

**Comment by judge-red** [comment]
Thanks for your input, that's interesting to hear. Does that mean that the annotation is not necessary anymore?

But my `cilium-envoy-config` ConfigMap does neither include the string `UpgradeType` not the string `websocket`. I'll attach the ConfigMap, in case it's useful. 
[cm-cilium-envoy-config.yaml.txt](https://github.com/cilium/cilium/files/13857662/cm-cilium-envoy-config.yaml.txt)

I guess it goes without saying that I don't understand how this works exactly (I just noticed that my webapp can't open websockets over a Cilium-controlled ingress, while it works with ingress-nginx) and have no idea about Envoy really, so let me know if I look in the wrong place or if you suspect I forgot something really basic or something.

**Comment by sayboras** [comment]
> Does that mean that the annotation is not necessary anymore?

yes, the annotation is no longer required.

> But my cilium-envoy-config ConfigMap does neither include the string UpgradeType not the string websocket. I'll attach the ConfigMap, in case it's useful.

It's actually not in the configmap, but in CiliumEnvoyConfig resource. You can just dump the CiliumEnvoyConfig via kubectl command. Each Ingress will have its own CiliumEnvoyConfig.

```
$ kubectl get ciliumenvoyconfig -A
$ kubectl get ciliumenvoyconfig <name of the resource> -o yaml
```

**Comment by judge-red** [comment]
There's only a single `ciliumenvoyconfig` by the name `cilium-ingress` (in the `kube-system` namespace), but it does seem to include the config for all ingresses. And indeed, it does container the `upgradeType: websocket` so I guess the root cause of my problem with websockets is somewhere else entirely. My bad!

Should I cloud this issue?
