### ISSUE TITLE
GatewayClass not created on 1.15.0-rc.0

### ISSUE THREAD

**Issue by wibed** [cilium/cilium#30138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

hi i upgraded to 1.15.0-rc,0 and experienced the gatewayclass not beeing created as usual.
on 1.14.5 i do bind the gatewayclass crd to v1beta1 as seen here:
...
helmCharts:
  - name: cilium
    releaseName: cluster0
    includeCRDs: true
    version: 1.14.5
    apiVersions:
      - gateway.networking.k8s.io/v1beta1/GatewayClass
...

yet on version 1.15.0-rc.0 with or without the statement, the gatewayclass is not created.

what am i doing wrong?

### Cilium Version

1.15.0-rc.0

### Kernel Version

6.1.46-talos

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.4", GitCommit:"bae2c62678db2b5053817bc97181fcc2e8388103", GitTreeState:"clean", BuildDate:"2023-11-15T16:48:54Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Thanks for your issue.

Just curious if you have installed new Gateway API CRDs from v1.0.0 before performing the upgrade.

**Comment by youngnick** [comment]
Yes, in Cilium 1.15, we have upgraded to v1.0.0 of Gateway API, which _removes_ the `v1beta1` GatewayClass resource. For all the Standard support objects, you need to move to `v1` instead. (That's GatewayClass, Gateway, and HTTPRoute).

**Comment by wibed** [comment]
thanks for your input.

indeed after deleting existing crd's and binding to the v1/gateway class like this:
```yaml
...
    apiVersions:
      - gateway.networking.k8s.io/v1/GatewayClass
...
```

i manage to set it up correctly!
