### ISSUE TITLE
Cilium detaches still in use XDP programs on restart

### ISSUE THREAD

**Issue by rgo3** [cilium/cilium#30132]
As noticed and reported on slack by @oblazek, the [`maybeUnloadObsoleteXDPPrograms()`](https://github.com/cilium/cilium/blob/cbe30378f752eb0295426a0e6bae34b4c7292e67/pkg/datapath/loader/xdp.go#L42) function has a bug where it removes still necessary XDP programs from a netlink device. This can lead to temporary connectivity issues as these programs will not be replaced atomically as intended.

The issue is that the kernel returns different values when it is queried for the attach mode of a netlink device compared to the values used when configuring the attach mode: see https://elixir.bootlin.com/linux/v6.7/source/include/uapi/linux/if_link.h#L1333
E.g. when attaching with `XDPDriverMode` (evaluates to '4' in the input flags), querying it will return `XDP_ATTACHED_DRV` (evaluates to '1'). This means that the [check](https://github.com/cilium/cilium/blob/cbe30378f752eb0295426a0e6bae34b4c7292e67/pkg/datapath/loader/xdp.go#L62) for matching attach modes will fail, the respective device will not be marked as used and cilium proceeds to detach the xdp program from that device.

For a fix Cilium needs to know about the constant values returned for the attach mode by the kernel when querying devices and match those to the respective input parameters cilium used when attaching the programs

cc @ti-mo

**Comment by ti-mo** [comment]
@rgo3 Was this shipped in 1.14 or will it ship in 1.15?

**Comment by oblazek** [comment]
imo the same bug is relevant in all 1.13, 1.14 and 1.15

**Comment by rgo3** [comment]
Given we backported https://github.com/cilium/cilium/commit/5de211a883e07cf82644d0d180265a545c6c9414 until 1.13, a fix should be backported there as well.
