### ISSUE TITLE
Egress gateway not working on 1.15.0-rc.0 when using interface

### ISSUE THREAD

**Issue by JackMyers001** [cilium/cilium#30159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have described my networking setup + `CiliumEgressGatewayPolicy` in #30158.

I had previously been running v1.14.5 with the `egressGateway.installRoutes: true` Helm value, as I found that none of my pods that used the Egress gateway would be able to reach anything outside of the VPN VLAN subnet without this value being set. For example, I could reach `192.168.150.1`, `192.168.150.101`, `192.168.150.102`, `10.0.20.51` and `10.0.20.52`, but I could not reach `10.0.20.1`, nor any other subnet on my LAN. I could also not reach my WAN.

The `installRoutes` flag was removed in #26215, as an apparent fix for #23504. I have upgraded Cilium from v1.14.5 to v1.15.0-rc.0 and I removed that now non-existent Helm value. After the upgrade, I have found that I am in exactly the same situation as I was when I didn't have `installRoutes` on v1.14.5.

Please let me know what logs / tests I should run to diagnose the issue further.

### Cilium Version

Working on v1.14.5, broken in v1.15.0-rc.0

### Kernel Version

Linux 6.1.69-talos

### Kubernetes Version

v1.29.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JackMyers001** [comment]
This is still broken in `1.15.0-rc.1`.

I realized I forgot to upload a sysdump when creating the original issue. [Here is the output](https://github.com/cilium/cilium/files/13998367/cilium-sysdump-20240120-231125.zip) of `cilium-cli sysdump`, generated with:

```
cilium-cli:  compiled with go1.21.6 on linux/amd64
cilium image (default): v1.14.5
cilium image (stable): v1.14.5
cilium image (running): 1.15.0-rc.1
```

I have modified the logs slightly so as to mask my public IPv4 and IPv6 addresses.

**Comment by squeed** [comment]
@jibi would you mind taking a look? Has there been a regression from v1.14?

**Comment by julianwiedmann** [comment]
> I had previously been running v1.14.5 with the egressGateway.installRoutes: true Helm value, as I found that none of my pods that used the Egress gateway would be able to reach anything outside of the VPN VLAN subnet without this value being set.

Right, that's not what the flag was intended for :slightly_smiling_face:.

It sounds like the routing on your node isn't set up as needed. Going by https://github.com/cilium/cilium/issues/30158, can you check whether `EgressIP -> externalIP` traffic on your gateway node is routed via `enp4s0.150`?

**Comment by JackMyers001** [comment]
> Right, that's not what the flag was intended for 🙂.

I *was* rather surprised when setting that flag worked 😆.

> It sounds like the routing on your node isn't set up as needed. Going by #30158, can you check whether `EgressIP -> externalIP` traffic on your gateway node is routed via `enp4s0.150`?

In `v1.14.5`, if I open a shell on a pod that doesn't have any `EgressGateway` selector labels and I run `curl ifconfig.me`, I will see my home's IP address. If I add the `route-through-vpn` label and again run `curl ifconfig.me`, I will see the IP address of the VPN.

In `v1.15.0.rc.0` / `rc.1`, running the command on a pod without the label returns my home IP as expected. With the label applied, nothing ever happens. Curl never seems to time out, either. I can't ping any WAN address (again, no timeouts, just no responses). This is identical behavior to `v.1.4.5` if I *don't* have the `egressGateway.installRoutes` flag set to `true`.

Apologies if I misunderstood the question. I hope this is what you were after?

**Comment by julianwiedmann** [comment]
https://github.com/cilium/cilium/pull/30488 has a bit more details.

Your gateway node's routing needs to be set up so that ``ip route get <externalIP> from <egressIP>`` returns `enp4s0.150`.

**Comment by JackMyers001** [comment]
Sorry for the slow update. All testing below is running Cilium `v1.15.1`. Because I'm running Talos Linux, I don't have the ability to run `ip route` directly on the node, however if I create a pod on the egress gateway node with the `NET_ADMIN` and `NET_RAW` capabilities, I think that's effectively equivalent?

The output of `ip route get 1.1.1.1 from 192.168.150.100` is:

```
1.1.1.1 from 192.168.150.100 via 10.0.20.1 dev enp4s0 uid 0
```

The output of `ip route` is:

```
default via 10.0.20.1 dev enp4s0 src 10.0.20.51 metric 1024
default via 192.168.150.1 dev enp4s0.150 src 192.168.150.100 metric 4096
10.0.20.0/24 dev enp4s0 proto kernel scope link src 10.0.20.51
10.244.0.0/24 via 10.244.0.147 dev cilium_host proto kernel src 10.244.0.147
10.244.0.147 dev cilium_host proto kernel scope link
10.244.2.0/24 via 10.244.0.147 dev cilium_host proto kernel src 10.244.0.147 mtu 1450
10.244.3.0/24 via 10.244.0.147 dev cilium_host proto kernel src 10.244.0.147 mtu 1450
192.168.150.0/24 dev enp4s0.150 proto kernel scope link src 192.168.150.100
```

And the (trimmed) output of `ip addr` is:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 brd 127.255.255.255 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether e6:6e:08:5e:29:44 brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 1e:56:d0:c6:4d:c4 brd ff:ff:ff:ff:ff:ff
4: teql0: <NOARP> mtu 1500 qdisc noop state DOWN group default qlen 100
    link/void
5: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
6: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
7: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd :: permaddr e219:8a6f:e319::
8: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:e0:4c:f8:06:da brd ff:ff:ff:ff:ff:ff
    inet 10.0.20.51/24 brd 10.0.20.255 scope global enp4s0
       valid_lft forever preferred_lft forever
    inet6 <my-ipv6-adr>:20:2e0:4cff:fef8:6da/64 scope global dynamic mngtmpaddr
       valid_lft 86364sec preferred_lft 14364sec
    inet6 fe80::2e0:4cff:fef8:6da/64 scope link
       valid_lft forever preferred_lft forever
9: siderolink: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1280 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet6 fdae:41e4:649b:9303:29e4:1e8a:3d27:da3f/64 scope global
       valid_lft forever preferred_lft forever
10: enp4s0.150@enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:e0:4c:f8:06:da brd ff:ff:ff:ff:ff:ff
    inet 192.168.150.100/24 brd 192.168.150.255 scope global enp4s0.150
       valid_lft forever preferred_lft forever
    inet6 <my-ipv6-adr>:150:2e0:4cff:fef8:6da/64 scope global dynamic mngtmpaddr
       valid_lft 85898sec preferred_lft 13898sec
    inet6 fe80::2e0:4cff:fef8:6da/64 scope link
       valid_lft forever preferred_lft forever
```

If I do `traceroute 1.1.1.1 -i enp4s0.150` I _do_ see my traffic go through the VPN interface, so that part is working as expected.

Unless I am missing something obvious, I believe that it is currently not possible to use Egress Gateways to route **all** traffic from specific pods through a specific interface. This is in contrast to my expectation from the _original_ documentation (updated in commit e777df1b68a2e1763b33813b7f06a10765aeb442); I would have expected that if I'm providing an interface name / IP, Cilium would bind to that interface.

Would Cilium be willing to accept a PR to change the current behavior / add a new option to bind directly to the interface, rather than using the host's routing table? If not, this issue can be closed as "won't fix".

**Comment by julianwiedmann** [comment]
>Would Cilium be willing to accept a PR to change the current behavior / add a new option to bind directly to the interface, rather than using the host's routing table?

Sure, let's have a look :).

**Comment by Elegant996** [comment]
> Would Cilium be willing to accept a PR to change the current behavior / add a new option to bind directly to the interface, rather than using the host's routing table? If not, this issue can be closed as "won't fix".

@JackMyers001 Did you have any luck binding to the interface? Just reached an edge case where directing traffic to an interface (without an IP) would be desired. The interface is being used as a macvlan bridge in a container.

Although we can bind things like `curl` to an interface in the container, the default route is still that of cilium so NetworkPolicies are interfering.
