### ISSUE TITLE
CI: have CLI parameter to allow for output of all commands to console as well as to file

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3016]
It'd be quite helpful to see the output of commands on console in real time instead of having to correlate with the created `logs` file. This can be a CLI option provided to Ginkgo which is false by default.

**Comment by eloycoto** [comment]
@ianvernon  duplicated by https://github.com/cilium/cilium/issues/2843?

**Comment by eloycoto** [comment]
Closed, work done in 2843
