### ISSUE TITLE
Enabling proxy protocol in ingress controller results in errors

### ISSUE THREAD

**Issue by judge-red** [cilium/cilium#30180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I enabled the proxy protocol listener filter in the ingress controller, see:
https://github.com/cilium/cilium/blob/v1.15.0-rc.0/install/kubernetes/cilium/values.yaml#L729

Now I see this warning in all `cilium-envoy` pods and no traffic seems to flow through the ingress anymore:
```
cilium-envoy-hqqk6 cilium-envoy [2024-01-10 13:51:24.326][7][debug][config] [external/envoy/source/extensions/listener_managers/listener_manager/listener_manager_impl.cc:125]     name: envoy.filters.listener.proxy_protocol
cilium-envoy-hqqk6 cilium-envoy [2024-01-10 13:51:24.326][7][debug][config] [external/envoy/source/extensions/listener_managers/listener_manager/listener_manager_impl.cc:154]   config: {"@type":"type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol"}
cilium-envoy-hqqk6 cilium-envoy [2024-01-10 13:51:24.326][7][warning][config] [external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:128] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) kube-system/cilium-ingress/listener: Didn't find a registered implementation for 'envoy.filters.listener.proxy_protocol' with type URL: 'envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol'
cilium-envoy-hqqk6 cilium-envoy [2024-01-10 13:51:24.326][7][trace][config] [external/envoy/source/extensions/config_subscription/grpc/grpc_mux_impl.cc:124] Sending DiscoveryRequest for type.googleapis.com/envoy.config.listener.v3.Listener: version_info: "123" type_url: "type.googleapis.com/envoy.config.listener.v3.Listener" response_nonce: "124" error_detail { code: 13 message: "Error adding/updating listener(s) kube-system/cilium-ingress/listener: Didn\'t find a registered implementation for \'envoy.filters.listener.proxy_protocol\' with type URL: \'envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol\'\n" }
```

While it's labeled as a warning, it sounds like the filter isn't loaded, i.e. it's rather fatal for the functionality and I suspect this is why I can't access my workloads through the ingress anymore. But I have no prior experience with using proxy protocol with Cilium, as it's only been added very recently, so maybe my problem lies somewhere else.

### Cilium Version

$ cilium version
cilium-cli: v0.15.19 compiled with go1.21.5 on darwin/amd64
cilium image (default): v1.14.4
cilium image (stable): v1.14.5
cilium image (running): 1.15.0-rc.0

### Kernel Version

Linux 5.15.0-91-generic https://github.com/cilium/cilium/pull/101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.27.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judge-red** [comment]
Addendum: ingresses don't seem to work for me with 1.15.0-rc.0 in general, with or without proxy protocol. So maybe it's only a warning after all? Anyway, I had to go back to 1.14.5 to get working ingresses.

**Comment by sayboras** [comment]
Thanks for your issue, it seems to be a bug on either proxy build, or the client encoding/decoding part. 

Will check and get back to you on this.
