### ISSUE TITLE
envoy spams debug log

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3021]
Found `envoy-log` sitting around with 16G, all entry look the same:

```
[2018-03-04 22:59:51.822][388][warning][router] accesslog.cc:171] Cilium access log send failed: Resource temporarily unavailable
```

**Comment by jrajahalme** [comment]
Is there any time interval between the entries? I.e., would rate-limiting the logging help here?

**Comment by tgraf** [comment]
I saw several messages per second, it looked like an error retry that then spams the log.
