### ISSUE TITLE
CFP: xDS Adapter for ClusterIP Routing

### ISSUE THREAD

**Issue by robscott** [cilium/cilium#30235]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

There are some capabilities that the Kubernetes API Server is not well equipped to handle. This includes topology aware routing (or any form of routing that requires a feedback loop) and routing to endpoints outside of the cluster.

**Describe the feature you'd like**

A new xDS adapter in Cilium that could take advantage of some of the strengths of xDS, particularly the feedback loop via LRS and the overall potential for scalability improvements when adjustments to routing configurations don't need to round trip through the Kubernetes API Server. In most cases, I'd expect xDS only to be used on Services where it is particularly helpful, and for the Kubernetes API to remain the primary source of truth.

**(Optional) Describe your proposed solution**

I've provided more information in the [original proposal doc](https://docs.google.com/document/d/1U4pO_dTaHERKOtrneNA8njW19HSVbq3sBM3x8an4878/edit) and will work on a more detailed CFP as a follow up to this issue.

**Comment by linsun** [comment]
related: [#30283](https://github.com/cilium/cilium/issues/30283)

**Comment by robscott** [comment]
This CFP is intentionally targeted on a relatively small scope - the overlap of existing Cilium capabilities with existing xDS APIs. If you're interested in exploring anything beyond that, I recommend checking out the broader issue: #30283.

**Comment by robscott** [comment]
This is very much still going, will be discussing in more detail at the dev summit tomorrow.

**Comment by danehans** [comment]
@robscott any outcomes from the dev summit worth mentioning here?
