### ISSUE TITLE
CI:Conformance Cluster Mesh: DNS resolution timeout

### ISSUE THREAD

**Issue by brlbil** [cilium/cilium#30251]
Timeout on DNS resolution. 

The CI run IDs:
https://github.com/cilium/cilium/actions/runs/7528399133/job/20490533311
https://github.com/cilium/cilium/actions/runs/7526560489/job/20484978979
https://github.com/cilium/cilium/actions/runs/7512514388/job/20453295035

```
[.] Action [client-egress-l7/pod-to-world/https-to-google.com-0: cilium-test/client-69748f45d8-fkdfr (10.242.1.95) -> google.com-https (google.com:443)]
  [.] Action [client-egress-l7/pod-to-world/https-to-google.com-index-0: cilium-test/client-69748f45d8-fkdfr (10.242.1.95) -> google.com-https-index (google.com:443)]
  [.] Action [client-egress-l7/pod-to-world/http-to-google.com-1: cilium-test/client2-ccd7b8bdf-45jmn (10.242.1.140) -> google.com-http (google.com:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 --retry 3 --retry-all-errors --retry-delay 3 [http://google.com:80](http://google.com/)" failed: command failed (pod=cilium-test/client2-ccd7b8bdf-45jmn, container=client2): "curl: (28) Resolving timed out after 2001 milliseconds\n"
```

[cilium-sysdumps.zip](https://github.com/cilium/cilium/files/13939072/cilium-sysdumps.zip)

Similar to  #29843 and #27799

**Comment by thorn3r** [comment]
Hit in https://github.com/cilium/cilium/actions/runs/7658533255/job/20871684721 on https://github.com/cilium/cilium/pull/30361
Sysdump: [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/14056613/cilium-sysdumps.2.zip)

**Comment by thorn3r** [comment]
Hit in https://github.com/cilium/cilium/actions/runs/8524885540/job/23350530348 on https://github.com/cilium/cilium/pull/31677
