### ISSUE TITLE
CI: Ingress Conformance Test: An Ingress with mixed path rules should send traffic to the matching backend service where Exact is preferred

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#30281]
### Name

[Ingress Conformance Test (Without_XDP, true, false, disabled, dedicated, false)](https://github.com/cilium/cilium/actions/runs/7545131415/job/20540072188#logs): An Ingress with mixed path rules should send traffic to the matching backend service where Exact is preferred

### Logs

```
Scenario: An Ingress with mixed path rules should send traffic to the matching backend service where Exact is preferred # features/path_rules.feature:174
    When I send a "GET" request to "http://mixed-path-rules/foo"                                                          # feature.go:94 -> iSendARequestTo
    timeout while waiting after 6 attempts, 0/3 sucessess
    Then the response status-code must be 200                                                                             # feature.go:102 -> theResponseStatuscodeMustBe
    And the response must be served by the "foo-exact" service           
```

### Sysdump

[cilium-sysdump-out.zip](https://github.com/cilium/cilium/files/13953927/cilium-sysdump-out.zip)

### Link

* Action: https://github.com/cilium/cilium/actions/runs/7545131415/job/20540072188#logs
* PR: https://github.com/cilium/cilium/pull/29796

**Comment by thorn3r** [comment]
Hit a similar one in https://github.com/cilium/cilium/actions/runs/7631765783/job/20790487495 on  https://github.com/cilium/cilium/pull/30361
Sysdump: [cilium-sysdump-out.zip](https://github.com/cilium/cilium/files/14030019/cilium-sysdump-out.zip)

**Comment by giorio94** [comment]
Hit in https://github.com/cilium/cilium/pull/30743 as well

**Comment by giorio94** [comment]
Hit again: https://github.com/cilium/cilium/actions/runs/9267168012/job/25493004548

**Comment by aditighag** [comment]
Hit in - https://github.com/cilium/cilium/actions/runs/9320255252/job/25656650072.

**Comment by ovidiutirla** [comment]
Hit again: https://github.com/cilium/cilium/actions/runs/9330022689/job/25683138209
