### ISSUE TITLE
Why LB4_REVERSE_NAT_SK_MAP_SIZE is set to 262144?

### ISSUE THREAD

**Issue by tacslon** [cilium/cilium#30285]
The LB4_REVERSE_NAT_SK_MAP_SIZE is set to 262144, which is 4x of 65536, so is there any reason why it is set to 262144? Thanks.

**Comment by squeed** [comment]
Hi there, @tacslon. I'm not able to answer your question, but a GitHub issue may not be the best way to get an answer. Have you considered joining the [Cilium Slack](https://cilium.herokuapp.com/)?
