### ISSUE TITLE
CFP: Consider using xDS for state synchronization in Cilium

### ISSUE THREAD

**Issue by shashankram** [cilium/cilium#30283]
## Background

Cilium uses Kubernetes as its primary control plane, and as a means for state synchronization between Cilium agents running as a daemonset on each node. In the CRD based operational mode, this is realized by agents watching Kubernetes resources (Pods, Endpoints, Nodes, Cilium CRDs, etc.), and then propagating the state changes throughout the cluster by writing new/updated state information back to Kubernetes, using CRs such as CiliumIdentity, CiliumEndpoint, etc. For example, when a Pod is created, the agent is responsible for writing a CiliumEndpoint CR and potentially a CiliumIdentity CR representing the Pod’s security identity. This mechanism is able to reconcile state information globally in the cluster.

In the kvstore mode, Cilium agents can synchronize state by directly writing to a dedicated kvstore (etcd) and watching for state changes to reconcile state information across all agents. Using the kvstore can alleviate the stress exerted on the k8s API server in large clusters consisting of thousands of Nodes and tens of thousands of Pods. Reads/writes to the k8s API server are instead offloaded to the kvstore which serves as a centralized datastore for state information. The kvstore thus provides a good way to scale and reduce the stress on the k8s API server, which can provide significant performance benefits in large clusters.

You can think of this as a multi-tiered architecture, where Kubernetes is used as the central control plane, with agents implementing a local control plane on each node and synchronizing state via a backing datastore (either via k8s CRDs or a dedicated kvstore).

## Problems

In both the operation modes described above, since every Cilium agent instance is responsible for watching several k8s or kvstore resources and writing back state information to the cluster via CRDs or directly to the kvstore, there are a few problems that arise as the scale of a cluster grows in terms of nodes, pods, namespaces and network policies. Some of these are as follows:

- Increase in the amount of work each agent must perform in terms of translating user intent to lower level datapath configuration. This can lead to increased CPU and memory usage on each node.

- The read/write overhead on the k8s API server can be significant when the number of resources being read and written to is large. This can cause the k8s API server to become a bottleneck in large clusters, and sometimes even result in outages. This is especially true for operations that cause a large volume of churn in the cluster, such as on changing the namespace label thereby resulting in recomputing the identities of pods in that namespace.

- CiliumIdentity duplication due to a lack of centralized identity management can present reliability and scalability issues.

- Duplicative translations from user intent to lower level configuration across all agents. For example, consider network policies where all policies are translated to more fine grained derivatives (policy rules) within the Cilium agent and stored in memory before being realized by eBPF maps. There's also a lack of efficient distribution mechanism to selectively filter and distribute policies relevant to a particular node.

- A local control plane on each node that needs privileged write access to the backing store is vulnerable to a multi-node compromise that can arise from a single agent in the cluster being compromised, since all agents have the ability to alter global state information in the cluster.

- In the kvstore mode, there is increased operational complexity arising from needing to run and manage a dedicated datastore.

## How an xDS based control plane can be useful

In this model, a centralized control plane is used to synchronize state information across all agents in the cluster. This control plane is responsible for translating user intent to lower level configuration, and propagating this information to all agents in the cluster. Each agent is responsible for realizing this configuration locally on the node. This model is similar to the way Envoy works, where a centralized control plane is used to configure and synchronize state information across all Envoy proxies in the cluster using the xDS protocol.

- The control plane would shield the dataplane (agent and eBPF datapath) from higher level complexity pertaining to translating user intent and cluster state to a lower level representation that is easier to process and apply in the datapath, and reconcile state information across all nodes. This could significantly improve agent performance and resource utilization on the node. Additionally, it could reduce the agent complexity, for example, by enabling the control plane to ingest other sources of infrastructural state and make it available to agents without the agents needing to evolve.

- Reduced read/write strain on the k8s API server since the control plane would be responsible for reading and writing state information to the k8s API server when necessary, and the number of control plane replicas will be far fewer than the number of nodes in the cluster.

- Centralized management and distribution of identities to avoid duplication.

- As a dedicated privileged component in the cluster that can modify global state, it can be easier to apply and enforce security controls to the control plane to reduce the attack surface, including running it outside the cluster in a security hardened environment.

- Simplify operations without necessitating a kvstore for better performance. Since the overwhelming majority of the load is read, a cache will yield the same improvement for a fraction of the operational complexity arising from a dedicated datastore.

Overall, an xDS control plane architecture for state synchronization and distribution can provide a scalable solution similar to that with a dedicated kvstore, but with simplicity of using Kubernetes as the backing store, and without the operational complexity of running a dedicated datastore.
![Screenshot from 2024-01-16 09-54-59](https://github.com/cilium/cilium/assets/21697719/613ec51e-b76e-43cf-a0f1-739b4ea0272c)

## Conclusion

This is not a concrete proposal on the implementation details, but rather meant to start a discussion on how this can be beneficial to the Cilium project. If there is consensus that this is a good idea, I would like to augment this issue with a more concrete proposal on how this can be implemented in a phased manner without destabilizing the existing implementation and features.

**Comment by shashankram** [comment]
Worth noting that https://github.com/cilium/cilium/issues/30235 is a subset of the capability this proposal could implement. I want to start a discussion larger than the scope of https://github.com/cilium/cilium/issues/30235 as the motivations for both these issues are quite different. I don't view either of these issues as blockers for each other, though there is the possibility to collaborate on the design and implementation to realize the shared objectives described in the two issues.

**Comment by youngnick** [comment]
I think that using an xDS control plane as a caching proxy to streamline and scale getting the details of endpoints and endpoint groups (ie Services) from Kubernetes makes sense.

But I don't think that this will ever be a complete replacement for all Agent <-> Kubernetes traffic. The Agent will still need to watch and reconcile quite a few things itself.

Most importantly, I think that for this point:
> The control plane would shield the dataplane (agent and eBPF datapath) from higher level complexity pertaining to translating user intent and cluster state to a lower level representation that is easier to process and apply in the datapath, and reconcile state information across all nodes. This could significantly improve agent performance and resource utilization on the node. Additionally, it could reduce the agent complexity, for example, by enabling the control plane to ingest other sources of infrastructural state and make it available to agents without the agents needing to evolve.

There's only a limited extent to which this is true, because of policy computation and enforcement. Routing decisions and policy computation are not independent, they're more coupled than you might think, because, for example, if policy removes endpoints from consideration, the load calculations may be different. Moving this logic out of the dataplane and into xDS to realize this goal will require a lot more work, code, and logic than it may appear (given that this is still under active development and has been for Cilium's entire lifetime ).

I'm still processing this, so I will probably have more thoughts, but wanted to get my initial impressions out for discussion. Happy to talk more about this.

**Comment by shashankram** [comment]
> I think that using an xDS control plane as a caching proxy to streamline and scale getting the details of endpoints and endpoint groups (ie Services) from Kubernetes makes sense.
> 
:thumbsup:

> But I don't think that this will ever be a complete replacement for all Agent <-> Kubernetes traffic. The Agent will still need to watch and reconcile quite a few things itself.
> 
Could you share what some of these are? 

> Most importantly, I think that for this point:
> 
> > The control plane would shield the dataplane (agent and eBPF datapath) from higher level complexity pertaining to translating user intent and cluster state to a lower level representation that is easier to process and apply in the datapath, and reconcile state information across all nodes. This could significantly improve agent performance and resource utilization on the node. Additionally, it could reduce the agent complexity, for example, by enabling the control plane to ingest other sources of infrastructural state and make it available to agents without the agents needing to evolve.
> 
> There's only a limited extent to which this is true, because of policy computation and enforcement. Routing decisions and policy computation are not independent, they're more coupled than you might think, because, for example, if policy removes endpoints from consideration, the load calculations may be different. Moving this logic out of the dataplane and into xDS to realize this goal will require a lot more work, code, and logic than it may appear (given that this is still under active development and has been for Cilium's entire lifetime ).
> 
I understand that it would require a lot of work to realize this, but is there a technical reason why this may be unfeasible?

> I'm still processing this, so I will probably have more thoughts, but wanted to get my initial impressions out for discussion. Happy to talk more about this.
>
Thanks @youngnick for the initial feedback.

**Comment by youngnick** [comment]
> > But I don't think that this will ever be a complete replacement for all Agent <-> Kubernetes traffic. The Agent will still need to watch and reconcile quite a few things itself.
> 
> Could you share what some of these are?

Off the top of my head, things that are needed for features like BGP routing and other L2 annoucement features, Ingress, Gateway API, as well as basic concurrency primitives like Leases. All I'm trying to say here is that I don't think it's very plausible that we would end up with _zero_ connection between the agents and the apiserver.

> > Most importantly, I think that for this point:
> > > The control plane would shield the dataplane (agent and eBPF datapath) from higher level complexity pertaining to translating user intent and cluster state to a lower level representation that is easier to process and apply in the datapath, and reconcile state information across all nodes. This could significantly improve agent performance and resource utilization on the node. Additionally, it could reduce the agent complexity, for example, by enabling the control plane to ingest other sources of infrastructural state and make it available to agents without the agents needing to evolve.
> > 
> > 
> > There's only a limited extent to which this is true, because of policy computation and enforcement. Routing decisions and policy computation are not independent, they're more coupled than you might think, because, for example, if policy removes endpoints from consideration, the load calculations may be different. Moving this logic out of the dataplane and into xDS to realize this goal will require a lot more work, code, and logic than it may appear (given that this is still under active development and has been for Cilium's entire lifetime ).
> 
> I understand that it would require a lot of work to realize this, but is there a technical reason why this may be unfeasible?

I don't think I explained myself very well - perhaps a better way to explain is that policy enforcement and traffic routing are not orthogonal. Currently, Cilium does forwarding in something like this order:
- service expansion (turning Services into groups of endpoints)
- Policy computation and enforcement
- Routing decisions

Because the policy computation is important for routing decisions, I think that replacing the whole thing with xDS APIs will be tricky. From what I can see, we really have four options:
- Do service expansion in the xDS control plane, pass that information to the agent, then have the agent pass the decisions back so that the control plane can use LRS information to make a routing decision;
- Do service expansion and endpoint lookup (including maintaining LRS information) in the xDS control plane, then enrich the endpoint information that's sent down to the agents for policy and routing decisions with more information about desirability, probably with some form of priority or cost number
- Don't do LRS at all and just have the xDS control plane send only endpoints, clusters etc.
- Completely rebuild the policy engine in the xDS control plane, so that all decisions can be made there.

I've included the third and fourth options for completeness, but I don't think either of them are viable because, respectively:
- I agree that LRS and being able to take cluster-wide load into account during routing is very desirable
- Rebuilding the policy engine is basically cutting out one of the core parts of Cilium, that has great performance and reliability, and externalizing it away from eBPF.

To me, it seems like the second is the most achievable - having a centralized control plane keep a picture of the cluster's state and load, and then enriching the information sent to Cilium's policy and routing engine with additional information seems like it would  meet a few goals:
- allows the xDS control plane to inject additional endpoints - with the relevant metadata to reflect their priority for routing. This would help with the scaling concerns, I think.
- uses LRS for centralized collection and management of load information, so that information can be used in routing decisions.

As I said, still digesting and thinking about this though, so I'm definitely interested in talking more about it.

**Comment by shashankram** [comment]
> > > But I don't think that this will ever be a complete replacement for all Agent <-> Kubernetes traffic. The Agent will still need to watch and reconcile quite a few things itself.
> > 
> > 
> > Could you share what some of these are?
> 
> Off the top of my head, things that are needed for features like BGP routing and other L2 annoucement features, Ingress, Gateway API, as well as basic concurrency primitives like Leases. All I'm trying to say here is that I don't think it's very plausible that we would end up with _zero_ connection between the agents and the apiserver.
> 
Is there a reason this data cannot be proxied via the xDS control plane? I am not familiar with the usage of Leases in the agent, why would this be required with a centralized controller?

> > > Most importantly, I think that for this point:
> > > > The control plane would shield the dataplane (agent and eBPF datapath) from higher level complexity pertaining to translating user intent and cluster state to a lower level representation that is easier to process and apply in the datapath, and reconcile state information across all nodes. This could significantly improve agent performance and resource utilization on the node. Additionally, it could reduce the agent complexity, for example, by enabling the control plane to ingest other sources of infrastructural state and make it available to agents without the agents needing to evolve.
> > > 
> > > 
> > > There's only a limited extent to which this is true, because of policy computation and enforcement. Routing decisions and policy computation are not independent, they're more coupled than you might think, because, for example, if policy removes endpoints from consideration, the load calculations may be different. Moving this logic out of the dataplane and into xDS to realize this goal will require a lot more work, code, and logic than it may appear (given that this is still under active development and has been for Cilium's entire lifetime ).
> > 
> > 
> > I understand that it would require a lot of work to realize this, but is there a technical reason why this may be unfeasible?
> 
> I don't think I explained myself very well - perhaps a better way to explain is that policy enforcement and traffic routing are not orthogonal. Currently, Cilium does forwarding in something like this order:
> 
>     * service expansion (turning Services into groups of endpoints)
> 
>     * Policy computation and enforcement
> 
>     * Routing decisions
> 
> 
> Because the policy computation is important for routing decisions, I think that replacing the whole thing with xDS APIs will be tricky. From what I can see, we really have four options:
> 
>     * Do service expansion in the xDS control plane, pass that information to the agent, then have the agent pass the decisions back so that the control plane can use LRS information to make a routing decision;
> 
>     * Do service expansion and endpoint lookup (including maintaining LRS information) in the xDS control plane, then enrich the endpoint information that's sent down to the agents for policy and routing decisions with more information about desirability, probably with some form of priority or cost number
> 
I like this option.

>     * Don't do LRS at all and just have the xDS control plane send only endpoints, clusters etc.
> 
>     * Completely rebuild the policy engine in the xDS control plane, so that all decisions can be made there.
> 
> 
> I've included the third and fourth options for completeness, but I don't think either of them are viable because, respectively:
> 
>     * I agree that LRS and being able to take cluster-wide load into account during routing is very desirable
> 
>     * Rebuilding the policy engine is basically cutting out one of the core parts of Cilium, that has great performance and reliability, and externalizing it away from eBPF.
> 
> 
> To me, it seems like the second is the most achievable - having a centralized control plane keep a picture of the cluster's state and load, and then enriching the information sent to Cilium's policy and routing engine with additional information seems like it would meet a few goals:
> 
>     * allows the xDS control plane to inject additional endpoints - with the relevant metadata to reflect their priority for routing. This would help with the scaling concerns, I think.
> 
>     * uses LRS for centralized collection and management of load information, so that information can be used in routing decisions.
> 
> 
> As I said, still digesting and thinking about this though, so I'm definitely interested in talking more about it.

Thanks for the detailed insights on the possibilities to enable this. This is definitely still pretty raw to turn into a concrete proposal that is feasible without destabilizing the code-base.

**Comment by youngnick** [comment]
Perhaps we should try and catch up in-person about this at Kubecon?

**Comment by shashankram** [comment]
> Perhaps we should try and catch up in-person about this at Kubecon?

Unfortunately I won't be able to attend in-person, but would love to collaborate with you on this proposal. I'll try to find some time to chat with you about this.

**Comment by youngnick** [comment]
Please feel free to reach out to me on Slack about setting up a time.
