### ISSUE TITLE
unreachable endpoints in cluster mesh setup - k8s v1.26.12

### ISSUE THREAD

**Issue by esc-velocity** [cilium/cilium#30297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

All endpoints returned by ciliumnodes.cilium.io are correct and works, on both clusters. Unfortunately cilium status command shows that two of six nodes have unreachable endpoints and their endpoint IP are not updating in cilium-health status.

### Cilium Version

1.14.5

### Kernel Version

Linux kma-01-kat 6.1.9-060109-generic #202302010835 SMP PREEMPT_DYNAMIC Wed Feb  1 08:41:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.26.12

### Sysdump

[cilium-sysdump-20240117-115525.zip](https://github.com/cilium/cilium/files/13964068/cilium-sysdump-20240117-115525.zip)
[cilium-sysdump-20240117-115518.zip](https://github.com/cilium/cilium/files/13964073/cilium-sysdump-20240117-115518.zip)

### Relevant log output

```shell
kubectl get ciliumnodes.cilium.io
NAME         CILIUMINTERNALIP   INTERNALIP     AGE
kma-01-waw   10.111.0.66        172.18.33.23   21h
kma-02-waw   10.111.1.54        172.18.33.24   21h
kma-03-waw   10.111.2.1         172.18.33.25   21h
kno-01-waw   10.111.3.105       172.18.33.26   21h
kno-02-waw   10.111.4.200       172.18.33.27   21h
kno-03-waw   10.111.5.94        172.18.33.28   21h

kubectl get ciliumnodes.cilium.io
NAME         CILIUMINTERNALIP   INTERNALIP      AGE
kma-01-kat   10.222.0.137       172.16.37.108   23h
kma-02-kat   10.222.1.221       172.16.37.109   23h
kma-03-kat   10.222.2.115       172.16.37.110   23h
kno-01-kat   10.222.3.225       172.16.37.111   23h
kno-02-kat   10.222.4.15        172.16.37.112   23h
kno-03-kat   10.222.5.65        172.16.37.113   23h

Cluster health:                 10/12 reachable   (2024-01-17T13:29:35Z)
  Name                          IP                Node        Endpoints
  kato/kma-01-kat (localhost)   172.16.37.108     reachable   reachable
  kato/kma-02-kat               172.16.37.109     reachable   reachable
  kato/kma-03-kat               172.16.37.110     reachable   reachable
  kato/kno-01-kat               172.16.37.111     reachable   reachable
  kato/kno-02-kat               172.16.37.112     reachable   reachable
  kato/kno-03-kat               172.16.37.113     reachable   reachable
  waw/kma-01-waw                172.18.33.23      reachable   reachable
  waw/kma-02-waw                172.18.33.24      reachable   unreachable
  waw/kma-03-waw                172.18.33.25      reachable   reachable
  waw/kno-01-waw                172.18.33.26      reachable   unreachable
  waw/kno-02-waw                172.18.33.27      reachable   reachable
  waw/kno-03-waw                172.18.33.28      reachable   reachable

  waw/kma-01-waw (localhost)   172.18.33.23      reachable   reachable
  kato/kma-01-kat              172.16.37.108     reachable   reachable
  kato/kma-02-kat              172.16.37.109     reachable   reachable
  kato/kma-03-kat              172.16.37.110     reachable   reachable
  kato/kno-01-kat              172.16.37.111     reachable   reachable
  kato/kno-02-kat              172.16.37.112     reachable   reachable
  kato/kno-03-kat              172.16.37.113     reachable   reachable
  waw/kma-02-waw               172.18.33.24      reachable   reachable
  waw/kma-03-waw               172.18.33.25      reachable   reachable
  waw/kno-01-waw               172.18.33.26      reachable   reachable
  waw/kno-02-waw               172.18.33.27      reachable   reachable
  waw/kno-03-waw               172.18.33.28      reachable   reachable


  waw/kma-02-waw:
    Host connectivity to 172.18.33.24:
      ICMP to stack:   OK, RTT=7.630408ms
      HTTP to agent:   OK, RTT=7.382816ms
    Endpoint connectivity to 10.111.1.8:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.111.1.8:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  waw/kma-03-waw:
    Host connectivity to 172.18.33.25:
      ICMP to stack:   OK, RTT=8.938434ms
      HTTP to agent:   OK, RTT=15.988116ms
    Endpoint connectivity to 10.111.2.126:
      ICMP to stack:   OK, RTT=8.810335ms
      HTTP to agent:   OK, RTT=14.401816ms
  waw/kno-01-waw:
    Host connectivity to 172.18.33.26:
      ICMP to stack:   OK, RTT=9.043766ms
      HTTP to agent:   OK, RTT=14.109471ms
    Endpoint connectivity to 10.111.3.115:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.111.3.115:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
Hi @esc-velocity, thanks for your detailed issue.

I had a look at the sysdumps you posted, and I see that there are a bunch of system pods with non-zero restarts from few minutes prior to sysdump collections, including both Kubernetes and Cilium ones. My feeling is that the Cilium agents in the remote cluster had not yet fully reconnected after the restart of the clustermesh-apiserver, as the information about the health IP of the node (`kno-01-waw`) on which the agent also restarted seem to be out of date.

Did the situation converge automatically after a few more minutes? If not, could you please restart the Cilium agents in both clusters and see if the issue resolves?

**Comment by pbabilas** [comment]
Hi @giorio94 I can provide some answears because it's also our system ;]
The fault also persists after days (is not solved automatically), the only solution is to restart the cilium pods, but after some time (hours/days) the situation repeats itself.

**Comment by giorio94** [comment]
Sorry, I haven't yet had cycles to further troubleshoot this issue. I'll try to get back to it this week.

**Comment by giorio94** [comment]
I've checked the new sysdumps, and it appears that you hit the same bug mentioned in https://github.com/cilium/cilium/issues/24692. TL;DR; when KPR is enabled and a NodePort service configured with the same port exists in both meshed clusters, the traffic from a node towards that nodeport will always hit the local service, regardless of whether the target node is local or remote.

Specifically, this affects the clustermesh-apiserver service (which by default uses NodePort `32379`), causing the agents to mistakenly connect to the local one instead of the remote one (after a first successful connection), regardless of the configuration. 

Could you please [configure a different NodePort](https://github.com/cilium/cilium/blob/d678428a8697545c03fa1da76d7833090671c058/install/kubernetes/cilium/values.yaml#L2615-L2622) on each cluster as a workaround and verify if the issue gets fixed?

**Comment by giorio94** [comment]
Thanks for confirming, I'll close this issue then. Feel free to open a new one in case you experience another problem.
