### ISSUE TITLE
CI: v1.12: Conformance IPsec E2E: `Failed to update or lookup TC buffer`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#30293]
On v1.12, we're seeing packet drops of type `Failed to update or lookup TC buffer` after the key rotation in https://github.com/cilium/cilium/actions/runs/7549079052/job/20552425179.

We've previously seen such packet drops in the upgrade workflow, on agent restarts. Those were fixed by https://github.com/cilium/cilium/pull/28740, but not backported to v1.12. It's however unclear how it could explain such packet drops given the agents are not restarted in this workflow.

One possibility is that they are happening on the initial agent startup?

Sysdump: [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/13962728/cilium-sysdumps.zip)

cc @julianwiedmann @ti-mo

**Comment by pchaigno** [comment]
(I've seen it happen a couple times so unsure it's specific to that config.)

**Comment by ti-mo** [comment]
> It's however unclear how it could explain such packet drops given the agents are not restarted in this workflow.

The agent doesn't need to be restarted for endpoint progs to be reattached. If the endpoint regenerates for whatever reason, this kind of error can occur.

**Comment by pchaigno** [comment]
Only if the regeneration leads to a recompilation (or repatching of the ELF), right? I thought that didn't happen on newer kernels without policies :thinking:

**Comment by ti-mo** [comment]
> or repatching of the ELF

ELF patching happens on every ELF load to plumb IPs, ID, etc. into the bytecode, even if the ELF template was just recompiled due to an agent config change. Normally, this doesn't cause changes in complexity or different branches being taken (at least, for now).

**Comment by pchaigno** [comment]
> ELF patching happens on every ELF load to plumb IPs, ID, etc. into the bytecode, even if the ELF template was just recompiled due to an agent config change.

Yeah, but I can't think of anything that would cause such a change during the key rotation. We don't change the config, restart the agent, load CRDs, or anything like that. We load a new Kubernetes secret and update the XFRM configuration on the nodes.

**Comment by julianwiedmann** [comment]
https://github.com/cilium/cilium/pull/30352 hit it with https://github.com/cilium/cilium/actions/runs/7612288434/job/20729575793 as

```
🟥 Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "Failed to update or lookup TC buffer"
  },
  "name": "cilium_drop_count_total",
  "value": 1
}
```

**Comment by giorio94** [comment]
Hit in https://github.com/cilium/cilium/pull/30390 as well
Link: https://github.com/cilium/cilium/actions/runs/7638041299/job/20808110994
Sysdump: [cilium-sysdump-conformance-ipsec-e2e-key-rotation-3-20240124-094528.zip](https://github.com/cilium/cilium/files/14038917/cilium-sysdump-conformance-ipsec-e2e-key-rotation-3-20240124-094528.zip)

```
  🟥 Found unexpected packet drops:
{
  "labels": {
    "direction": "INGRESS",
    "reason": "Failed to update or lookup TC buffer"
  },
  "name": "cilium_drop_count_total",
  "value": 2
}
```

**Comment by julianwiedmann** [comment]
v1.12 is EOL, and afaik we haven't seen this particular error on newer releases. Closing without a solution to the mystery.
