### ISSUE TITLE
Identities and bpf-ipcache entries for IPs specific to evicted FQDN entries are not cleaned up causing policy map to be filled

### ISSUE THREAD

**Issue by vethastanley** [cilium/cilium#30296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are using Cilium CNI in our AWS EKS cluster as our primary CNI and to enforce network policies. By default, a namespace is restricted to have traffic only within itself. Further ingress and egress for specific hosts are permitted through L3-based FQDN policies.

Recently in our production environment, some of the network traffic dropped. On analyzing the cilium sysdump, we could see in the cilium agent **cilium-drzfl** there were many errors while trying to update a policy map stating the map is full.

`level=error msg="Failed to add PolicyMap key" bpfMapKey="{16899967 0 0 1}" containerID= datapathPolicyRevision=194 desiredPolicyRevision=194 endpointID=51 error="Unable to update element for cilium_policy_00051 map with file descriptor 111: the map is full, please consider resizing it. argument list too long" identity=15003 ipv4= ipv6= k8sPodName=/ port=0 subsys=endpoint`

Then we found the policy map already has `16384` entries. On further analysis we found most of the identities are pointing to an IP with label `reserved:world`. But these IPs are no more mapped to any FQDN hosts but they are available in the bpm ipcache and the identities are mapped to the policies. These IPs seems to be belonging to AWS services like S3, SQS and SMTP as they are mentioned as part of the FQDN policy. 

This looks like an identity leak as though the IPs specific to FQDN hosts are deleted from the FQDN cache its corresponding identities are not deleted.

**Note: I have a cilium sysdump but it is 45 MB in size and git is not letting me to upload it. Is there a way to upload it here?**

### Cilium Version

1.13.1

### Kernel Version

Linux amzn2.x86_64

### Kubernetes Version

1.27.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
This looks like it might be the issue as outlined in https://github.com/cilium/cilium/pull/27870. The fix has been backported to v1.13.8, but it does require setting an additional option.

S3, in particular, can cause policy map overflows, as the same name can resolve to many, many different IPs at once.

**Comment by vethastanley** [comment]
@squeed Thank you for the information. This helps a lot.

**Comment by vethastanley** [comment]
From the documentation, it is not very clear what is the unit of the value of the option `conntrackGCMaxInterval'. Is it "seconds"? Secondly, if I now mention the max interval as 1 hour does that mean the maximum interval allowed between any two consecutive GC is one hour?

Currently, we have left the cluster for more than 2 days now and I could still see the identities are not cleaned up. In this case, will this option to set the max interval for GC help?

**Comment by dctrwatson** [comment]
> This looks like it might be the issue as outlined in #27870. The fix has been backported to v1.13.8, but it does require setting an additional option.
> 
> S3, in particular, can cause policy map overflows, as the same name can resolve to many, many different IPs at once.

@squeed I don't suppose there's some metric being emitted that can validate that interval? I can't seem to find one

**Comment by christarazi** [comment]
@vethastanley It's a duration which means you can specify the unit, i.e. `s`, `ms`, etc. Did @squeed's suggestion work for you

**Comment by vethastanley** [comment]
@christarazi Thanks for the reply. I tried to compare with the other durations that are already present in the configuration and figured out its units. 

Yes I tried to apply the new configuration suggested by @squeed and the initial tests shows that things are better now. We are moving it to production now. I can say the issue is resolved with this property.
