### ISSUE TITLE
Pre-release testing 

### ISSUE THREAD

**Issue by mohang6770** [cilium/cilium#30301]
### Test Category

Other

### Test Details

tried to upgrade cilium from 1.14.5 to pre release version v1.15.0-rc.1 , the operator got updated
error:│ cilium-agent level=fatal msg="failed to start: daemon creation failed: unable to initialize kube-proxy replacement options: Node Port \"hybrid\" mode cannot be used with vxlan tunneling.\nfailed to stop: unable to find controller ipcache-inje │
│ ct-labels" subsys=daemon

### Time

It took 1 hour to attempt this test

### Test Status

Failure: Reproducible bug encountered/filed

### Cilium Version

v1.15.0-rc.1

### Kernel Version

4.18.0-513.9.1.el8_9.x86_64

### Kubernetes Version

1.27.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rari459** [comment]
How were you able to resolve this issue? Also seeing this after operator upgrade.
