### ISSUE TITLE
FQDN: consider not adding names to the DNSCache that don't have selectors

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#30314]
The FQDN policy system really has two separate components:

1: DNS proxy policy, which intercepts DNS requests and allows or denies _the DNS request_ based on the name
2: toFQDN policy, which dynamically configures L3 policy based on intercepted DNS requests. Endpoints with ToFQDN must, by definition, use DNS proxy as well

The toFQDN policy engine must maintain a cache (the "DNSCache") of names and their answers, so it can manage TTLs and garbage collection. This cache is not used for generating responses, just for computing IPs for L3 policy.

However, we currently insert *all* names intercepted as part of DNS policy in to the DNSCache, regardless of whether or not they are used for toFQDN policy. We should consider skipping this where possible.

One disadvantage of this would be when a toFQDN policy is added for a name that would have already existed in the DNSCache. I think, however, this is OK. By definition, toFQDN policy is dependent on endpoints making DNS requests. Any IP addresses discovered after the toFQDN policy is created would be allowed, which IMHO is acceptable.

**Comment by Shunpoco** [comment]
Hi @squeed, Can I take this issue?

In my understanding, `notifyOnDNSMsg` kicks updating (inserting) DNSCache [here](https://github.com/cilium/cilium/blob/main/daemon/cmd/fqdn.go#L429), so we can filter unnecessary DNS records in that process.

**Comment by aanm** [comment]
> Hi [@squeed](https://github.com/squeed), Can I take this issue?
> 
@Shunpoco go ahead

**Comment by squeed** [comment]
For sure!

**Comment by gandro** [comment]
> However, we currently insert all names intercepted as part of DNS policy in to the DNSCache, regardless of whether or not they are used for toFQDN policy. We should consider skipping this where possible.

There is actually one other user of this information: Hubble does a reverse lookup on the IP to annotate the IP with known fqdn names for the IP. If users just have a DNS observability rule without ToFQDNs they might still want Hubble to annotate all flows with the FQDN of the observed IP.

**Comment by squeed** [comment]
Aha, good point; I didn't realize that.

**Comment by Shunpoco** [comment]
@squeed, @gandro 
I'm sorry to leave this issue for months. Now I can make time, so will tackle this issue.
But 
> There is actually one other user of this information: Hubble ~

Did you mean that Hubble uses this DNSCache information not only DNS with toFQDN policy, but also which is not related with toFQDN policy?
In that case, should we leave the current implementation (and close this ticket), or should we prepare other DNS cache system for Hubble and separate it to FQDN code?

**Comment by gandro** [comment]
A second cache probably would not bring the performance benefits we expect from this work. I think we are unsure how to proceed here, given the fact that Hubble relies on this and the behavior changes outlined it the the last paragraph of the original post.

I'm currently leaning towards leaving the current implementation as is and close the ticket.

**Comment by gandro** [comment]
Closing as not planned for now. We can reopen if the assessment changes
