### ISSUE TITLE
Test flake: Unexpected connection between frontend and backend

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#3032]
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/k8sT/Policies.go:633
Unexpected connection between frontend and backend; wanted HTTP 403, got: HTTP 404
Expected
    <string>: 404
to equal
    <string>: 403
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/k8sT/Policies.go:692
```
```
Test Result (1 failure / -18)
k8s-1.9.K8sValidatedPolicyTestAcrossNamespaces Policies Across Namespaces
```
from
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/31/

zip file with test results
[test_results_Cilium-PR-Ginkgo-Tests-K8s_31.zip](https://github.com/cilium/cilium/files/1786464/test_results_Cilium-PR-Ginkgo-Tests-K8s_31.zip)

**Comment by ianvernon** [comment]
Unfortunately, this one slipped through the cracks. We have not seen such behavior in some time. @aanm can we close this in favor of triaging more recent failures?

**Comment by aanm** [comment]
@ianvernon the .zip doesn't contain any useful info?

**Comment by ianvernon** [comment]
> can we close this in favor of triaging more recent failures?

IMO, more recent failures necessitate higher priority in triaging. Given how much code has changed in the past month, and that we haven't seen this specific issue occur for some time, I don't see debugging this as a particularly useful exercise. It's up to those who triage Jenkins (and when this was filed, I was the Jenkins Backup, so I take responsibility for letting this fall through the cracks) to triage things in a timely manner.

**Comment by tgraf** [comment]
Never seen again. Closing.
