### ISSUE TITLE
toService in clusterwidenetworkpolicy is not taken into effect

### ISSUE THREAD

**Issue by eegseth** [cilium/cilium#30350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When creating a ciliumClusterwideNetworkpolicy, the field spec.egress.toService is no taken into effect. (And perhaps ingress also, not tested).

Applying the policy with `kubectl apply -f .\clusterwidepolicy.yaml`  all looks ok, the object is created. Doing an inspection with  `kubectl get ciliumclusterwidenetworkpolicy -o yaml`  , the policy looks as it should.

But when you do a `cilium policy get`, the clusterwide policy is not listed, and the traffic allowed in the policy is dropped.

E.g.
`
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: test
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - toServices:
        - k8sService:
            serviceName: some-service
            namespace: some-namespace
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
`

Looks ok:
![image](https://github.com/cilium/cilium/assets/23167027/bef40601-01e0-444a-a4d7-c4649cca9d2b)

But nothing in output from cilium policy get:
![image](https://github.com/cilium/cilium/assets/23167027/ce188d87-3e89-4432-a572-daaa9286e334)

### Cilium Version

1.15.0-pre.3

### Kernel Version

5.15.0-1049-azure / AKSUbuntu-2204gen2containerd-202307.27.0

### Kubernetes Version

1.27.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by odinuge** [comment]
Hi!

If you look at https://docs.cilium.io/en/stable/security/policy/language/#limitations it describes that using `.ToServices` and `.ToPorts` in the same rule is not supported. If you check the logs of your cilium agents, you will probably see something like this; 

```
level=warning msg="Unable to add CiliumNetworkPolicy" ciliumNetworkPolicyName=test error="Invalid CiliumClusterwideNetworkPolicy spec: Combining ToServices and ToPorts is not supported yet" k8sApiVersion= k8sNamespace= subsys=k8s-watcher
```
