### ISSUE TITLE
Docs: Document IPv6 Tunneling Limitation

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#30360]
I recently tried running an IPv6-only cluster and ran into #17240. Since this issue has been open for a while and is currently unassigned, I think it's a good idea to document this caveat.

**Comment by alephpt** [comment]
I saw that 17240 is closed. Does this mean that standalone ipv6 tunneling is not going to be implemented in cilium?

**Comment by danehans** [comment]
Issue https://github.com/cilium/cilium/issues/17240 is still open.
