### ISSUE TITLE
Update upload-artifacts GitHub action to v4

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#30396]
It seems there is a breaking change on this GH action at that makes all actions to fail as seen in PR #30048, for example [here](https://github.com/cilium/cilium/actions/runs/7619007011)

The breaking change is documented in [here](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes). There's also a GH issue with more information [here](https://github.com/actions/upload-artifact/issues/478)

**Comment by mtardy** [comment]
[Migration help here](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) for this issue.
