### ISSUE TITLE
Cilium-agent incorrectly handles rollouts of statefulsets

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#30409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are multiple issues with how we handle the recreation of statefulset pods **on the same node**. This is specific to statefulsets as after the rolling upgrade of them, they have the same namespace and name.

1. Informer lagging case

In case of informer lagging, it might contain an old pod object in store, which we use for assigning ownerReference.
Here we get pod information for ownerReference: https://github.com/cilium/cilium/blob/bacf2e8718e603b6b74bd599711d73f3f7bfcddb/pkg/endpointmanager/endpointsynchronizer.go#L172
which comes from `fetchK8sMetadataForEndpoint`: https://github.com/cilium/cilium/blob/63e2676ccbe992af3243253725dab2bfc7981a9d/daemon/cmd/endpoint.go#L443
and only in HighScaleIPCache case it's fetched from k8s control plane, in most of the cases it's fetched from local store: 
https://github.com/cilium/cilium/blob/e43b759bab69c9f978fd893a75ae7c3f03d184b0/daemon/cmd/state.go#L193-L199

This can be easily reproduced by adding artificial `time.Sleep` in Add/Update/Delete handlers in the pod informer. When ownerReference is set to the old pod then kube-controller-manager GCes CiliumEndpoint and `sync-to-k8s-ciliumendpoint` controller never recreates CiliumEndpoint as it stores local copy and doesn't react to this delete event thinking that there is correct CEP: https://github.com/cilium/cilium/blob/bacf2e8718e603b6b74bd599711d73f3f7bfcddb/pkg/endpointmanager/endpointsynchronizer.go#L138

Potential solutions:
- During CNI Add verify that UID of the pod is the same as the pod in informer's store
- Make sync-to-k8s-ciliumendpoint controller react to changes to CiliumEndpoint.

This is more likely to occur in 1.13 as we don't use Resource[T] for informer updates, but still can happen in 1.14/1.15 under high pod churn on the node.

2. Delayed Delete pod event

CNI ADD/CNI DEL are independent from pod informer updates. In case statefulset pod is recreated on the same node, we might trigger a Delete event after recreating statefulset pod. As it has the same namespace/name it can cause some issues, for example, LocalRedirectPolicy depends only on namespace/name of the pod:
- trigger of deletion - https://github.com/cilium/cilium/blob/fbebd4062d96e330d82f0e976145af4711f0f4f2/pkg/k8s/watchers/pod.go#L542-L544
- id of policy entries consists only of namespace/name: https://github.com/cilium/cilium/blob/825b91d17489b8e7f4d82ce92b402a2b2581e97d/pkg/redirectpolicy/manager.go#L316-L319

Potential solution:
We should definitely review this case and also take into account UID of pod when receiving delete event (I only did initial review where I found issue with LocalRedirectPolicy).

3. Missed Delete/Add event

In some very rare cases, informer may skip the Delete/Add event and trigger the Update event instead with references to a new and old pod (because they have the same namespace/name). For example, this can happen when watch requests to k8s control plane gets terminated and the informer performs a relist. 

Update trigger: https://github.com/cilium/cilium/blob/fbebd4062d96e330d82f0e976145af4711f0f4f2/pkg/k8s/watchers/pod.go#L140-L149

This can potentially cause for example not detecting pod label's change. Scenario:
- Pod A with label X=Y
- Pod A gets deleted and recreated as Pod A' on the same node but without label X=Y (Pod A' has the same namespace/name)
- Pod A' gets patched with label X=Y
If the informer skips Delete/Add/Update events and triggers an update between Pod A with labels -> Pod A' with labels, we might fail to detect a patch of labels in the last step as we would be comparing Pod A and Pod A': https://github.com/cilium/cilium/blob/fbebd4062d96e330d82f0e976145af4711f0f4f2/pkg/k8s/watchers/pod.go#L361

Potential solution:
- Take into account UID of the pod when handling an update event. 

### Cilium Version

1.13-1.15 affected

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaunceyjiang** [comment]
> In case of informer lagging, it might contain an old pod object in store, which we use for assigning ownerReference.
Here we get pod information for ownerReference:

> This can be easily reproduced by adding artificial time.Sleep in Add/Update/Delete handlers in the pod informer. When ownerReference is set to the old pod then kube-controller-manager GCes CiliumEndpoint and sync-to-k8s-ciliumendpoint controller never recreates CiliumEndpoint as it stores local copy and doesn't react to this delete event thinking that there is correct CEP:

 

It seems in the screenshot provided in this https://github.com/cilium/cilium/issues/29967 issue there is a similar error.

**Comment by aanm** [comment]
This GH issue will likely fix https://github.com/cilium/cilium/issues/30820 and https://github.com/cilium/cilium/issues/27123

**Comment by fanux** [comment]
We have also encountered similar problems.
