### ISSUE TITLE
Helm value hubble.export.static.enabled=false - doesn't disable the hubble exporter static config

### ISSUE THREAD

**Issue by saintdle** [cilium/cilium#30425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the hubble exporter - static config is in place, it is expected that using the helm value `hubble.export.static.enabled=false` should disable this configuration

### Cilium Version

1.15.0-rc.1

### Kernel Version

Linux server 6.2.0-1019-gcp #21~22.04.1-Ubuntu SMP Thu Nov 16 18:18:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
thank you for debugging this, looks like we just need to get your PR merged! :)
