### ISSUE TITLE
cilium-agent cannot running

### ISSUE THREAD

**Issue by pengbinbin1** [cilium/cilium#30437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I deployed cilium(v1.14.6) on my cluster,but the cilium-daemon can not work will with error log "initializing conntrack map cilium_ct_any4_global  cannot allocate memory (without BTF k/v)",what is wrong?thank you.

### Cilium Version

v1.14.6

### Kernel Version

4.19

### Kubernetes Version

1.26

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pengbinbin1** [comment]
![微信图片_20240125160512](https://github.com/cilium/cilium/assets/28950491/b68c0f67-591b-4e2e-b3c3-78b5a78489bf)

**Comment by chaunceyjiang** [comment]
Could you please copy and paste the log information from the screenshot into plain text? It would make it much easier for developers to help you.

**Comment by pengbinbin1** [comment]
> Could you please copy and paste the log information from the screenshot into plain text? It would make it much easier for developers to help you.
level=info msg="Spire Delegate API Client is disabled as no socket path is configured" subsys=spire-delegate
level=info msg="Mutual authentication handler is disabled as no port is configured" subsys=auth
level=info msg=Invoked duration=62.284453ms function="cmd.glob..func4 (daemon_main.go:1607)" subsys=hive
level=info msg=Invoked duration="9.821µs" function="gc.registerSignalHandler (cell.go:47)" subsys=hive
level=info msg=Invoked duration="9.909µs" function="utime.initUtimeSync (cell.go:30)" subsys=hive
level=info msg=Invoked duration="39.992µs" function="agentliveness.newAgentLivenessUpdater (agent_liveness.go:44)" subsys=hive
level=info msg=Invoked duration="41.416µs" function="l2responder.NewL2ResponderReconciler (l2responder.go:64)" subsys=hive
level=info msg=Invoked duration="54.074µs" function="garp.newGARPProcessor (processor.go:27)" subsys=hive
level=info msg=Starting subsys=hive
level=info msg="Started gops server" address="127.0.0.1:9890" subsys=gops
level=info msg="Start hook executed" duration="244.999µs" function="gops.registerGopsHooks.func1 (cell.go:44)" subsys=hive
level=info msg="Start hook executed" duration="1.79µs" function="metrics.NewRegistry.func1 (registry.go:86)" subsys=hive
level=info msg="Establishing connection to apiserver" host="https://100.2.231.111:6443" subsys=k8s-client
level=info msg="Serving prometheus metrics on :9962" subsys=metrics
level=info msg="Connected to apiserver" subsys=k8s-client
level=info msg="Start hook executed" duration=7.419591ms function="client.(*compositeClientset).onStart" subsys=hive
level=info msg="Start hook executed" duration="4.814µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Node].Start" subsys=hive
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.113.0.0/16
level=info msg="Start hook executed" duration=2.510111ms function="node.NewLocalNodeStore.func1 (local_node_store.go:77)" subsys=hive
level=info msg="Start hook executed" duration="24.569µs" function="authmap.newAuthMap.func1 (cell.go:28)" subsys=hive
level=info msg="Start hook executed" duration="10.568µs" function="configmap.newMap.func1 (cell.go:24)" subsys=hive
level=info msg="Start hook executed" duration="13.841µs" function="signalmap.newMap.func1 (cell.go:45)" subsys=hive
level=info msg="Start hook executed" duration="7.523µs" function="nodemap.newNodeMap.func1 (cell.go:24)" subsys=hive
level=info msg="Start hook executed" duration="40.561µs" function="eventsmap.newEventsMap.func1 (cell.go:36)" subsys=hive
level=info msg="Start hook executed" duration=1.913773ms function="datapath.newDatapath.func1 (cells.go:114)" subsys=hive
level=info msg="Restored 0 node IDs from the BPF map" subsys=linux-datapath
level=info msg="Start hook executed" duration="66.635µs" function="datapath.newDatapath.func2 (cells.go:127)" subsys=hive
level=info msg="Start hook executed" duration="3.424µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Start" subsys=hive
level=info msg="Start hook executed" duration=100.805736ms function="*manager.diffStore[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Start" subsys=hive
level=info msg="Start hook executed" duration=796ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s.Endpoints].Start" subsys=hive
level=info msg="Using discoveryv1.EndpointSlice" subsys=k8s
level=info msg="Start hook executed" duration=103.201729ms function="*manager.diffStore[*github.com/cilium/cilium/pkg/k8s.Endpoints].Start" subsys=hive
level=info msg="Start hook executed" duration="1.641µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumNode].Start" subsys=hive
level=info msg="Start hook executed" duration=684ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Pod].Start" subsys=hive
level=info msg="Start hook executed" duration=807ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Namespace].Start" subsys=hive
level=info msg="Start hook executed" duration="1.078µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumNetworkPolicy].Start" subsys=hive
level=info msg="Start hook executed" duration=915ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumClusterwideNetworkPolicy].Start" subsys=hive
level=info msg="Start hook executed" duration=851ns function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumCIDRGroup].Start" subsys=hive
level=info msg="Start hook executed" duration="16.015µs" function="endpointmanager.newDefaultEndpointManager.func1 (cell.go:204)" subsys=hive
level=info msg="Start hook executed" duration="8.053µs" function="cmd.newPolicyTrifecta.func1 (policy.go:130)" subsys=hive
level=info msg="Start hook executed" duration="16.509µs" function="*manager.manager.Start" subsys=hive
level=info msg="Start hook executed" duration=758ns function="*cni.cniConfigManager.Start" subsys=hive
level=info msg="Serving cilium node monitor v1.2 API at unix:///var/run/cilium/monitor1_2.sock" subsys=monitor-agent
level=info msg="Start hook executed" duration="96.676µs" function="agent.newMonitorAgent.func1 (cell.go:62)" subsys=hive
level=info msg="Start hook executed" duration="1.043µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumL2AnnouncementPolicy].Start" subsys=hive
level=info msg="Start hook executed" duration="4.117µs" function="*job.group.Start" subsys=hive
level=info msg="Start hook executed" duration=16.646909ms function="signal.provideSignalManager.func1 (cell.go:26)" subsys=hive
level=info msg="Datapath signal listener running" subsys=signal
level=info msg="Start hook executed" duration=1.167979ms function="auth.registerAuthManager.func1 (cell.go:110)" subsys=hive
level=info msg="Start hook executed" duration="1.892µs" function="auth.registerGCJobs.func1 (cell.go:159)" subsys=hive
level=info msg="Start hook executed" duration="8.504µs" function="*job.group.Start" subsys=hive
level=warning msg="Deprecated value for --kube-proxy-replacement: strict (use either \"true\", or \"false\")" subsys=daemon
level=info msg="Auto-enabling \"enable-node-port\", \"enable-external-ips\", \"bpf-lb-sock\", \"enable-host-port\", \"enable-session-affinity\" features" subsys=daemon
level=info msg="Inheriting MTU from external network interface" device=ens9f0 ipAddr=100.2.231.113 mtu=1500 subsys=mtu
level=warning msg="No valid cgroup base path found: socket load-balancing tracing with Hubble will not work.See the kubeproxy-free guide for more details." subsys=cgroup-manager
level=info msg="Removed map pin at /sys/fs/bpf/tc/globals/cilium_ipcache, recreating and re-pinning map cilium_ipcache" file-path=/sys/fs/bpf/tc/globals/cilium_ipcache name=cilium_ipcache subsys=bpf
level=error msg="error while opening/creating BPF maps" error="initializing conntrack map cilium_ct_any4_global: creating map: map create: cannot allocate memory (without BTF k/v)" subsys=daemon
level=error msg="Start hook failed" error="daemon creation failed: error while opening/creating BPF maps: initializing conntrack map cilium_ct_any4_global: creating map: map create: cannot allocate memory (without BTF k/v)" function="cmd.newDaemonPromise.func1 (daemon_main.go:1663)" subsys=hive
level=info msg=Stopping subsys=hive
level=error msg="Observer job stopped with an error" error="context canceled" func="auth.(*AuthManager).handleAuthRequest" name="auth request-authentication" subsys=auth
level=error msg="Observer job stopped with an error" error="context canceled" func="auth.(*authMapGarbageCollector).handleIdentityChange" name="auth gc-identity-events" subsys=auth
level=info msg="Stop hook executed" duration="76.483µs" function="*job.group.Stop" subsys=hive
level=info msg="Stop hook executed" duration="2.114µs" function="auth.registerGCJobs.func2 (cell.go:163)" subsys=hive
level=info msg="Datapath signal listener exiting" subsys=signal
level=info msg="Datapath signal listener done" subsys=signal
level=info msg="Stop hook executed" duration="377.646µs" function="signal.provideSignalManager.func2 (cell.go:29)" subsys=hive
level=info msg="Stop hook executed" duration="7.363µs" function="*job.group.Stop" subsys=hive
level=info msg="Stop hook executed" duration="5.738µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumL2AnnouncementPolicy].Stop" subsys=hive
level=info msg="Stop hook executed" duration="2.459µs" function="agent.newMonitorAgent.func2 (cell.go:92)" subsys=hive
level=info msg="Stop hook executed" duration="1.375µs" function="*cni.cniConfigManager.Stop" subsys=hive
level=info msg="Stop hook executed" duration="11.078µs" function="*manager.manager.Stop" subsys=hive
level=error msg="Close() called without calling InitIdentityAllocator() first" subsys=identity-cache
level=error msg="Stop hook failed" error="unable to find controller ipcache-inject-labels" function="cmd.newPolicyTrifecta.func2 (policy.go:134)" subsys=hive
level=info msg="Stop hook executed" duration="10.018µs" function="endpointmanager.newDefaultEndpointManager.func2 (cell.go:208)" subsys=hive
level=info msg="Stop hook executed" duration="8.206µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1.CiliumCIDRGroup].Stop" subsys=hive
level=info msg="Stop hook executed" duration="3.645µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumClusterwideNetworkPolicy].Stop" subsys=hive
level=info msg="Stop hook executed" duration="1.891µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumNetworkPolicy].Stop" subsys=hive
level=info msg="Stop hook executed" duration="2.21µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Namespace].Stop" subsys=hive
level=info msg="Stop hook executed" duration="1.701µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Pod].Stop" subsys=hive
level=info msg="Stop hook executed" duration="1.643µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.CiliumNode].Stop" subsys=hive
level=info msg="Stop hook executed" duration="10.735µs" function="*manager.diffStore[*github.com/cilium/cilium/pkg/k8s.Endpoints].Stop" subsys=hive
level=info msg="Stop hook executed" duration="66.036µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s.Endpoints].Stop" subsys=hive
level=info msg="Stop hook executed" duration="10.872µs" function="*manager.diffStore[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Stop" subsys=hive
level=info msg="Stop hook executed" duration="24.271µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Stop" subsys=hive
level=info msg="Stop hook executed" duration=317ns function="eventsmap.newEventsMap.func2 (cell.go:46)" subsys=hive
level=info msg="Stop hook executed" duration="6.777µs" function="nodemap.newNodeMap.func2 (cell.go:27)" subsys=hive
level=info msg="Stop hook executed" duration="20.745µs" function="signalmap.newMap.func2 (cell.go:48)" subsys=hive
level=info msg="Stop hook executed" duration="4.231µs" function="configmap.newMap.func2 (cell.go:27)" subsys=hive
level=info msg="Stop hook executed" duration="2.061µs" function="authmap.newAuthMap.func2 (cell.go:31)" subsys=hive
level=info msg="Stop hook executed" duration="1.055µs" function="node.NewLocalNodeStore.func2 (local_node_store.go:96)" subsys=hive
level=info msg="Stop hook executed" duration="15.859µs" function="*resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Node].Stop" subsys=hive
level=info msg="Stop hook executed" duration="3.804µs" function="client.(*compositeClientset).onStop" subsys=hive
level=info msg="Stop hook executed" duration="24.379µs" function="metrics.NewRegistry.func2 (registry.go:96)" subsys=hive
level=info msg="Stopped gops server" address="127.0.0.1:9890" subsys=gops
level=info msg="Stop hook executed" duration=21.265468ms function="gops.registerGopsHooks.func2 (cell.go:51)" subsys=hive
level=fatal msg="failed to start: daemon creation failed: error while opening/creating BPF maps: initializing conntrack map cilium_ct_any4_global: creating map: map create: cannot allocate memory (without BTF k/v); failed to stop: unable to find controller ipcache-inject-labels" subsys=daemon

**Comment by pengbinbin1** [comment]
> Could you please copy and paste the log information from the screenshot into plain text? It would make it much easier for developers to help you.
[cilium-err.log](https://github.com/cilium/cilium/files/14059348/cilium-err.log)

**Comment by lmb** [comment]
The reason is most likely that you don't have enough RAM for the number of conntrack entries you are tring to support. Try reducing that number.
