### ISSUE TITLE
CI: add tests which check that `cilium endpoint regenerate` works as intended

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3044]
https://github.com/cilium/cilium/pull/3040 fixed an issue that caused `cilium endpoint regenerate` to be broken. Add a basic test which ensures that this CLI command works correctly in the Ginkgo tests.

**Comment by joestringer** [comment]
The part that's unclear to me on this is how we validate that the command 'works correctly'. The CLI should kick the datapath and cause full recompilation for an endpoint, but how do we measure this?

Furthermore this functionality is typically used by developers and is rarely necessary in any real environment.

**Comment by ianvernon** [comment]
I think the command failed every time (i.e., internal server error) in #3040 - so if there's a test that at the minimum asserts that the API returns without error, that'd be a good start.
