### ISSUE TITLE
Incomplete requests from Pod to Service with backend on same Node with DSR Enabled

### ISSUE THREAD

**Issue by burulevanton** [cilium/cilium#30451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are currently experiencing an issue in our Kubernetes (k8s) cluster that employs Istio, specifically related to the configuration of Cilium with the `bpf-lb-mode=dsr` parameter. Our setup includes Istio inside the k8s cluster, and we have a Istio Service published via ClusterIP with an ExternalIP. This ExternalIP is an Anycast IP that is announced via exaBGP on separate LB(not part of Istio) nodes.

When using the Cilium configuration parameter `bpf-lb-mode=dsr`, requests from a pod inside the Istio node to Istio Service are not being completed. The cilium monitor logs display something similar to the following:
```
<- endpoint 936 flow 0xd304afd9 , identity 3352->unknown state unknown ifindex 0 orig-ip 0.0.0.0: <test-pod-ip>:33920 -> <anycast-ip>:443 tcp SYN
Policy verdict log: flow 0xd304afd9 local EP ID 936, remote ID 16777290, proto 6, egress, action allow, match L3-L4, <test-pod-ip>:33920 -> <anycast-ip>:443 tcp SYN
-> stack flow 0xd304afd9 , identity 3352->16777290 state new ifindex 0 orig-ip 0.0.0.0: <test-pod-ip>:33920 -> <anycast-ip>:443 tcp SYN
-> network flow 0xd304afd9 , identity unknown->unknown state unknown ifindex 0 orig-ip 0.0.0.0: <istio-node-ip>:33920 -> <anycast-ip>:443 tcp SYN
<- network flow 0xcee3c99d , identity unknown->unknown state unknown ifindex eth0 orig-ip 0.0.0.0: <istio-node-ip>:33920 -> <istio-pod-ip>:8443 tcp SYN
```
However, when we switch to the configuration parameter `bpf-lb-mode=snat`, everything works as expected. 

After attempting to upgrade to v1.13.5, the problem persists.

Example of our cluster schema looks something like this:
![cilium dsr](https://github.com/cilium/cilium/assets/18692512/bf3f1c95-c81b-430b-aa45-07eb63ac17ff)

The question at hand is whether this behavior is a bug or if the DSR functionality is working as intended.

### Cilium Version

1.12.10

### Kernel Version

5.15.0-73-generic

### Kubernetes Version

1.22.17

### Sysdump

[cilium-sysdump-20240125-180404.z01.zip](https://github.com/cilium/cilium/files/14060660/cilium-sysdump-20240125-180404.z01.zip)
[cilium-sysdump-20240125-180404.z02.zip](https://github.com/cilium/cilium/files/14060661/cilium-sysdump-20240125-180404.z02.zip)
[cilium-sysdump-20240125-180404.zip](https://github.com/cilium/cilium/files/14060665/cilium-sysdump-20240125-180404.zip)

To extract the archive please run
```bash
mv cilium-sysdump-20240125-180404.z01.zip cilium-sysdump-20240125-180404.z01
mv cilium-sysdump-20240125-180404.z02.zip cilium-sysdump-20240125-180404.z02
zip -F cilium-sysdump-20240125-180404.zip --out cilium-sysdump.zip
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
hi! Just to note that Cilium `1.12.10` is fairly old (in fact, it's end-of-life as we just released `v1.15`). Are you able to reproduce this with the latest version of Cilium?
