### ISSUE TITLE
Can Cilium work with underlay CNI like sriov or macvaln on the chaining mode？

### ISSUE THREAD

**Issue by pengbinbin1** [cilium/cilium#30490]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

If so, please describe the problem

**Describe the feature you'd like**
Our cluster uses underlay CNI as the primary CNI, and we want to use cilium replace of kube-proxy to implement the k8s service function，How should I write the CNI configuration file of cilium?

**Comment by lmb** [comment]
Hi @pengbinbin1, please use the slack channel as mentioned in the CFP template.
