### ISSUE TITLE
Slack rejecting new joiners

### ISSUE THREAD

**Issue by camrossi** [cilium/cilium#30538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Trying to join Slack using my gmail address and I get this error:
`The email address must match one of the domains listed below. Please try another email.`

This seems to be a reoccurring issue (https://github.com/cilium/cilium/issues/30069) but I was told to open another Issue

**Comment by aanm** [comment]
cc @thebsdbox

**Comment by lizrice** [comment]
I refreshed the token and I think this should be fixed again

**Comment by camrossi** [comment]
I was about to join just now, thank you @lizrice !

**Comment by astrosmash** [comment]
Hi @lizrice / @xmulligan , looks like it's rejecting new registrations again. Can you please check the token again? Thank you

**Comment by hacktivist123** [comment]
Sorted now @astrosmash please try again!
