### ISSUE TITLE
Local Redirect Policy results in loopback when socket-LB is disabled

### ISSUE THREAD

**Issue by pravk03** [cilium/cilium#30558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[PR#13287 ](https://github.com/cilium/cilium/pull/13287/) was added to prevent the local-redirect service from looping back packets from the service's node-local backend to itself. However, this solution works only when socket load balancing mode is fully enabled (`ENABLE_SOCKET_LB_FULL`) or when the node local backend uses host network (`ENABLE_SOCKET_LB_HOST_ONLY`). We would run into the same loopback issue when the local-redirect service uses pod network and we probably need to have a loop prevention logic added in the lxc ebpf code.

cc: @sugangli ,  @liuyuan10 , @aojea 

### Cilium Version

Client: 1.13.10
Daemon: 1.13.10

### Kernel Version

Linux default-byac 6.1.58+ #1 SMP PREEMPT_DYNAMIC Sat Nov  4 14:14:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-gke.1203001

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pravk03** [comment]
cc @aditighag

**Comment by aditighag** [comment]
>We would run into the same loopback issue when the local-redirect service uses pod network

Hi! Could you describe your use case: when would you want packets not to be looped back in case of LRP?

**Comment by sugangli** [comment]
Hi @aditighag , we want to use LRP to redirect traffic to Nodelocal DNS on  pod network and be able to send DNS to other DNS service when there is cache miss.  However, we cannot enable socket LB because we want to be compatible with Istio (see this [doc](https://docs.google.com/document/d/13OEKHLQ87WG6bnYrTA_4zJVqMUbK5S0qnYACZPGaCjE/edit?tab=t.0#heading=h.7vszqtr360id) we shared with the OSS for more context).  Is there a better way to do it with bpf_lxc only?

**Comment by aditighag** [comment]
>we want to use LRP to redirect traffic to Nodelocal DNS on pod network and be able to send DNS to other DNS service when there is cache miss. 

Did you follow the [guide](https://docs.cilium.io/en/stable/network/kubernetes/local-redirect-policy/#node-local-dns-cache) to set up LRP for the node-local dns use case?
Per the official k8s [documentation](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/), when there is a cache miss, the node-local dns pods would send DNS requests to the upstream (cluster) DNS pods. When do you see packets getting looped? 

>However, we cannot enable socket LB because we want to be compatible with Istio (see this [doc](https://docs.google.com/document/d/13OEKHLQ87WG6bnYrTA_4zJVqMUbK5S0qnYACZPGaCjE/edit?tab=t.0#heading=h.7vszqtr360id) we shared with the OSS for more context). Is there a better way to do it with bpf_lxc only?

The datapath code that prevents loop in the socket-lb case has some drawbacks, and we are planning to replace that logic (see [issue](https://github.com/cilium/cilium/issues/15195)).

**Comment by pravk03** [comment]
cc @Weil0ng

**Comment by pravk03** [comment]
> when there is a cache miss, the node-local dns pods would send DNS requests to the upstream (cluster) DNS pods. When do you see packets getting looped?

The bpf program on the lxc interface translates the request from node-local DNS pod to cluster DNS back to itself [here](https://github.com/cilium/cilium/blob/03b0d866ea25a9da924464944b53f045a87ed203/bpf/bpf_lxc.c#L1363). We probably need a loop back check here before translation.

**Comment by pravk03** [comment]
Here is a repro: 

* Followed the [dev setup gide](https://docs.cilium.io/en/stable/contributing/development/dev_setup/) to set up a kind cluster with cilium 1.14
```
  cilium version
  cilium-cli: v0.15.20 compiled with go1.21.6 on linux/amd64
  cilium image (default): v1.14.5
  cilium image (stable): v1.14.6
  cilium image (running): 1.14.6
```

* Set up node local DNS from [here](https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/#node-local-dns-cache). The node local DNS would use cluster metadata server as the upstream DNS server (192.168.11.1  as a proxy for cluster metadata server).

* Created a simple pod and updated the DNS server to forward the queries to the cluster metadata server (192.168.11.1). 

```
cat <<EOF | kubectl apply -f - 
apiVersion: v1
kind: Pod
metadata:
  name: pk-pod
spec:
  containers:
    - name: pk-pod
      image: busybox
      command: ["/bin/sh", "-c", "echo 'nameserver 192.168.11.1' > /etc/resolv.conf && sleep 10000"]
EOF
```

* Added a LRP  to steer the reqests to node-local-dns pods

```
  apiVersion: cilium.io/v2
  kind: CiliumLocalRedirectPolicy
  metadata:
    annotations:
    name: nodelocaldns
    namespace: kube-system
  spec:
    redirectFrontend:
      addressMatcher:
        ip: 192.168.11.1
        toPorts:
        - name: dns
          port: "53"
          protocol: UDP
        - name: dns-tcp
          port: "53"
          protocol: TCP
    redirectBackend:
      localEndpointSelector:
        matchLabels:
          k8s-app: node-local-dns
      toPorts:
      - name: dns
        port: "53"
        protocol: UDP
      - name: dns-tcp
        port: "53"
        protocol: TCP
```

* Trigger a ping command and it works as expected. 
```
kubectl exec pk-pod -- ping -v -c 1 www.google.com
PING www.google.com (142.251.2.99): 56 data bytes
64 bytes from 142.251.2.99: seq=0 ttl=112 time=1.432 ms

--- www.google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.432/1.432/1.432 ms


From hubble logs:
hubble observe --pod pk-pod -f
Feb  3 01:54:09.224: default/pk-pod (ID:3296) <> kube-system/nodelocaldns-local-redirect:53 (world) pre-xlate-fwd TRACED (UDP)
Feb  3 01:54:09.224: default/pk-pod (ID:3296) <> kube-system/node-local-dns-24dnm:53 (ID:32364) post-xlate-fwd TRANSLATED (UDP)
Feb  3 01:54:09.224: default/pk-pod:45520 (ID:3296) -> kube-system/node-local-dns-24dnm:53 (ID:32364) to-endpoint FORWARDED (UDP)
Feb  3 01:54:09.224: default/pk-pod:45520 (ID:3296) <> kube-system/node-local-dns-24dnm (ID:32364) pre-xlate-rev TRACED (UDP)
Feb  3 01:54:09.224: default/pk-pod:45520 (ID:3296) <> kube-system/node-local-dns-24dnm (ID:32364) pre-xlate-rev TRACED (UDP)
Feb  3 01:54:09.226: default/pk-pod:45520 (ID:3296) <- kube-system/node-local-dns-24dnm:53 (ID:32364) to-endpoint FORWARDED (UDP)
Feb  3 01:54:09.226: kube-system/node-local-dns-24dnm:53 (ID:32364) <> default/pk-pod (ID:3296) pre-xlate-rev TRACED (UDP)
Feb  3 01:54:09.226: kube-system/nodelocaldns-local-redirect:53 (world) <> default/pk-pod (ID:3296) post-xlate-rev TRANSLATED (UDP)
Feb  3 01:54:09.226: kube-system/node-local-dns-24dnm:53 (ID:32364) <> default/pk-pod (ID:3296) pre-xlate-rev TRACED (UDP)
Feb  3 01:54:09.226: kube-system/nodelocaldns-local-redirect:53 (world) <> default/pk-pod (ID:3296) post-xlate-rev TRANSLATED (UDP)
Feb  3 01:54:09.226: default/pk-pod (ID:3296) -> 142.251.2.99 (world) to-stack FORWARDED (ICMPv4 EchoRequest)
Feb  3 01:54:09.228: default/pk-pod (ID:3296) <- 142.251.2.99 (world) to-endpoint FORWARDED (ICMPv4 EchoReply)
```

* Edit `cilium-config` configmap to enable socket LB in host only mode (`bpf-lb-sock-hostns-only: "true"`) and restart the cilium-agent pods. 

* Trigger a ping command, but now it fails as DNS resolution fails. 
```
kubectl exec pk-pod -- ping -v -c 1 www.google.com
ping: bad address 'www.google.com'
command terminated with exit code 1

From hubble logs:
root@kind-worker:/home/cilium# hubble observe --pod pk-pod -f
Feb  3 01:56:31.292: default/pk-pod:53548 (ID:3296) -> kube-system/node-local-dns-24dnm:53 (ID:32364) to-endpoint FORWARDED (UDP)
Feb  3 01:56:36.777: default/pk-pod:53548 (ID:3296) <- kube-system/node-local-dns-24dnm:53 (ID:32364) to-endpoint FORWARDED (UDP)
Feb  3 01:56:38.855: default/pk-pod (ID:3296) -> 192.168.11.1 (world) to-stack FORWARDED (ICMPv4 DestinationUnreachable(Port))
```

* Adding some logs in the bpf_lxc.c i confirmed that the requests from node local dns were getting looped back during [service lookup](https://github.com/cilium/cilium/blob/dc49625f1ca83984e43328f9330286b04995a332/bpf/bpf_lxc.c#L110C9-L110C18).

**Comment by aditighag** [comment]
>The node local DNS would use cluster metadata server as the upstream DNS server (192.168.11.1 as a proxy for cluster metadata server).

I don't follow this. What's "cluster metadata server"? In a standard node-local-dns deployment there is a cluster DNS service and upstream DNS service.

Also, I just noticed that the LRP you've mentioned is incorrect for the node-local dns use case. Please follow this guide to deploy node-local dns and LRP - https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/#node-local-dns-cache.

**Comment by pravk03** [comment]
> I don't follow this. What's "cluster metadata server"

Sorry for not big clear with my earlier comment (edited it now).  "cluster metadata server" is a cluster external DNS server. 

> I just noticed that the LRP you've mentioned is incorrect for the node-local dns use case. Please follow this guide to deploy node-local dns and LRP -  - https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/#node-local-dns-cache

We cannot exactly use the same config because in our setup, pod DNS queries for external URLs (URLs that don't refer to cluster resources) are forwarded directly to the cluster external DNS server bypassing kube-dns.

**Comment by aditighag** [comment]
> > I just noticed that the LRP you've mentioned is incorrect for the node-local dns use case. Please follow this guide to deploy node-local dns and LRP -  - https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/#node-local-dns-cache
> 
> We cannot exactly use the same config because in our setup, pod DNS queries for external URLs (URLs that don't refer to cluster resources) are forwarded directly to the cluster external DNS server bypassing kube-dns.

Ok, this context was missing in the original report. There are still some gaps in your last comment though.

Can you clearly describe the expected connectivity flow? Application pods connect to `192.168.1.1` which is a cluster external DNS server. This traffic is redirected to node-local DNS cache pods using the deployed LRP. What happens when the node-local DNS cache can't resolve a DNS request? Does it reach out to upstream kube-dns service?

The hubble flows you've added with and without socket-lb needs some more comments, and I'm not seeing "loopback" packets in the flows.  
>Adding some logs in the bpf_lxc.c i confirmed that the requests from node local dns were getting looped back during [service lookup](https://github.com/cilium/cilium/blob/dc49625f1ca83984e43328f9330286b04995a332/bpf/bpf_lxc.c#L110C9-L110C18).

What was the IP address the node-local dns was trying to reach?

**Comment by pravk03** [comment]
> What was the IP address the node-local dns was trying to reach?

We want to bypass kube-dns and route external URLs to cluster external DNS server. This is for both normal pods and node local DNS pods.

Below is the sequence: 

* User pod sends a DNS request for an external URL, and the request is resolved by an cluster external DNS server.
* LRP redirects the traffic directed to cluster external DNS server to node-local DNS pod
* When node-local DNS pod can't resolve a DNS request, it makes a request to cluster external DNS server
* LRP again redirects the traffic back to itself

> The hubble flows you've added with and without socket-lb needs some more comments, and I'm not seeing "loopback" packets in the flows.

Including the hubble flow logs for the node-local DNS pod with the setup in https://github.com/cilium/cilium/issues/30558#issuecomment-1925020478. The loopback packets originate from the default address for service loopback `169.254.42.1`  .

```

kubectl exec pk-pod -- ping -c 1 www.google.com
ping: bad address 'www.google.com'
command terminated with exit code 1

hubble observe -f --pod kube-system/node-local-dns-jpxh5 
Feb  9 22:44:49.847: 169.254.42.1:34755 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.847: 169.254.42.1:49049 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.847: 169.254.42.1:32944 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.847: 169.254.42.1:52390 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.847: 169.254.42.1:42290 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.847: 169.254.42.1:38228 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.847: 169.254.42.1:35429 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.847: 169.254.42.1:33449 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.847: 169.254.42.1:41205 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.847: 169.254.42.1:40057 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:58018 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:53857 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:37298 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:34583 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:57067 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:37750 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:51369 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:38577 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:42392 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:54031 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:41034 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:60081 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:49210 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:40176 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:47465 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:53171 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.848: 169.254.42.1:51823 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.849: 169.254.42.1:43854 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.849: 169.254.42.1:43709 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.849: 169.254.42.1:37854 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.849: 169.254.42.1:55706 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.849: 169.254.42.1:52043 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.849: 169.254.42.1:33113 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.850: 169.254.42.1:58154 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.850: 169.254.42.1:48747 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.850: 169.254.42.1:34080 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.850: 169.254.42.1:58907 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:59788 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:32898 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:55613 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:34498 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:42829 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:41303 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:33720 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:36272 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:50874 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:51058 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:54992 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:54247 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:38798 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:60185 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:59962 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:39159 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
Feb  9 22:44:49.851: 169.254.42.1:44398 (ID:51577) -> kube-system/node-local-dns-jpxh5:53 (ID:51577) to-endpoint FORWARDED (UDP)
... 
...
```

**Comment by aditighag** [comment]
Hi @pravk03 Thanks! Based on the additional context you provided, yes, it does look like a case of loopback traffic for LRP backends.

Note that, the loop prevention logic for LRP backends with socket-lb enabled that you've mentioned in the original report has some corner cases, so I'm planning to replace it. The loop prevention logic also needs to be exposed to the end user through the LRP spec, so that users can only enable it in certain LRPs (e.g., kiam, or the use case you have mentioned in this issue). Here is the PR - https://github.com/cilium/cilium/pull/26144. While the PR only addresses this for socket-lb, it can be extended for the per-packet LB case as well.

**Comment by pravk03** [comment]
Thanks @aditighag. Is there a plan to merge https://github.com/cilium/cilium/pull/26144 soon ?

**Comment by aditighag** [comment]
@pravk03 Yes... I'll be sending out a couple of dependent PRs, you can follow the PR for updates.

**Comment by pravk03** [comment]
Since we are currently blocked and want this addressed soon, wondering if there are any potential issues with adding a backend IP address check before doing service translation in the lxc interface ([commit](https://github.com/cilium/cilium/pull/30879/commits/26a00ef2479d48d17dd580558fd84f36771edf8e)).

**Comment by liuyuan10** [comment]
@aditighag As PR #30879 shows, it seems very easy to achieve the same loopback prevention for LRP in non socket LB mode. I assume it can't be done the same way in socket LB because source address of packets are not available in that context (pls correct me if wrong). Does that PR make sense and worth merging so that we can get feature parity for LRP in both socket LB and non-socket LB mode.

**Comment by aditighag** [comment]
@liuyuan10 We don't want to enforce this behavior for all LRPs, which is why 26144 exposes this as part of the API.

**Comment by liuyuan10** [comment]
@aditighag I understand you want to control it by a flag in the API. Your PR only covers socket-lb. For per packet LB, can I ask for you opinion on the approach taken in PR #30879  though I know we need to protect it behind a config flag. If it's the right path, we can talk about how to rebase it on top of you PR #26144

**Comment by aditighag** [comment]
>For per packet LB, can I ask for you opinion on the approach taken in PR https://github.com/cilium/cilium/pull/30879 though I know we need to protect it behind a config flag. If it's the right path, we can talk about how to rebase it on top of you PR https://github.com/cilium/cilium/pull/26144

It's not just about protecting it behind a flag. We need to check in the datapath which LRP services + pods we need to skip service translation. I can give pointers for the per-packet LB changes once 26144 is ready for review, and you can rebase on top.

**Comment by liuyuan10** [comment]
> We need to check in the datapath which LRP services + pods we need to skip service translation

Yes. that's about how to decide if enable loop prevention following your PR #26144 . Other than that, do you think the way we detect the loop makes sense for per packet LB?

**Comment by aditighag** [comment]
@pravk03 / @liuyuan10 Are you planning to pick [the PR](https://github.com/cilium/cilium/pull/30879) back up now that https://github.com/cilium/cilium/pull/26144 is merged?

**Comment by pravk03** [comment]
Thanks. With your changes, we can set `skipRedirectFromBackend` to true and wouldn't need [#30879](https://github.com/cilium/cilium/pull/30879) ?

**Comment by aditighag** [comment]
> Thanks. With your changes, we can set `skipRedirectFromBackend` to true and wouldn't need [#30879](https://github.com/cilium/cilium/pull/30879) ?

#30879 revised the socket-lookup based loopback logic in the socket-LB datapath. But IIUC, you opened #30879 for per-packet LB, right?

**Comment by pravk03** [comment]
Got it. Let me update https://github.com/cilium/cilium/pull/30879.

**Comment by aditighag** [comment]
Hi @pravk03 I looked into the BPF source code, and yes, `bpf_get_netns_cookie` helper is not exposed to BPF TC programs. So we won't be able to invoke it from cilium tc programs. It'll be great, however, if we can use the same `skip_lb{4,6}_map`s infrastructure across per-packet LB and socket-LB. 

There are a couple of options - 

(1) Write per `EP_NETNS_COOKIE` to cilium TC hooks via ELF variable substitutions. We already write per ep fields like `LXC_ID`, IP, MAC, etc, you can take a look at the code here - https://github.com/cilium/cilium/blob/master/pkg/datapath/loader/template.go#L214. The [per ep netns cookie](https://github.com/cilium/cilium/blob/main/pkg/endpoint/endpoint.go#L425-L425) then can be retrieved in the tc egress programs without having to call `bpf_get_netns_cookie`. 

(2) Maintain a mapping of endpoint IP to netns cookie, and use that to get netns cookie.

(3) Modify skip_lb_map key to have a union of netns_cookie (socket-LB) or ep IP fields (per-packet LB). 

Option (1) looks the cleanest, and I would suggest looking into it to unblock PR #30879.
