### ISSUE TITLE
CFP: Cross-plat build support

### ISSUE THREAD

**Issue by Alan-Jowett** [cilium/cilium#30562]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

The current builds system is dependent on a Linux only tool (gnumake) that isn't available on other platforms.

**Describe the feature you'd like**

A cross-platform builds system (either cmake or go build).

**(Optional) Describe your proposed solution**

Replace the current Makefile based build system (that only works with gnumake) with either a Go build or a CMake based build system that would permit building the Cilium user mode agent on other non-Linux platforms.

**Comment by sayboras** [comment]
I don't have enough knowledge to confirm how much effort is required to replace the current Makefile. But in my opinion, it could be a lot of effort and prone to error, while the value proposition is not that clear.

Just wanna highlight that Cilium codebase provides the devcontainer configuration to reduce such friction.

**Comment by Alan-Jowett** [comment]
The goal here is to build a version of the user mode agent that will run on Windows, rather than merely building a Linux version on Windows.

With [eBPF-for-Windows](https://github.com/microsoft/ebpf-for-windows) approaching the point where it can now run Cilium BPF programs, the next step is to permit the Cilium CNF to run on Windows.

While it would be possible to build a parallel build system for producing Windows Cilium CNF, that isn't a good long term strategy as it would require developers to maintain 2 build systems and keep them in synch.

**Comment by lmb** [comment]
@Alan-Jowett this might benefit from discussion at the community meeting if you can join that.
