### ISSUE TITLE
counter of container /sys/class/net/eth0/statistics/rx_packets not increase 

### ISSUE THREAD

**Issue by P0lskay** [cilium/cilium#30566]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

We are faced with the following problem. The problem is reproduced as follows:

- deploy any pod
- ping the pod address 10 times per second
- the counter /sys/class/net/eth0/statistics/tx_packets is growing correctly - ~ 10 per second
- counter /sys/class/net/eth0/statistics/rx_packets - not growing

![image](https://github.com/cilium/cilium/assets/49369886/ab9712c2-749f-4d51-9bcf-5fd94d9d5e95)

Has anyone encountered such a problem? (The problem is not related to the node, because if the pod uses the hostNetwork parameter, the counter will work correctly)

### Cilium Version

1.13.2

### Kernel Version

5.14.0-168.el9.x86_64

### Kubernetes Version

1.27.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by P0lskay** [comment]
The problem is that we use cAdvisor to collect network statistics on containers. cAdvisor focuses on counters inside the /sys/class/net/eth0/statistics/ folder. Because of this, we do not get correct network statistics on containers at the network level.
![image](https://github.com/cilium/cilium/assets/49369886/e80fcffa-efe4-4b67-a895-8815eef798f3)

**Comment by mostafabayat** [comment]
> Okay, this is unlikely to change I think. You can try disabling features which bypass the host network stack, at the cost of lower throughput. The other option would be to see whether our metrics can help: https://docs.cilium.io/en/stable/observability/metrics/
> 
> Otherwise it might be nice to document this fact so that others with the same question can benefit.

Can you provide guidance on disabling the features that are causing this issue? Is it still possible to use BPF and have these metrics be correct?

**Comment by borkmann** [comment]
This has been fixed in the kernel via https://lore.kernel.org/all/20231114004220.6495-1-daniel@iogearbox.net/

(this one specifically https://lore.kernel.org/all/20231114004220.6495-6-daniel@iogearbox.net/ )

**Comment by ti-mo** [comment]
@borkmann Thanks! Closing this.

**Comment by borkmann** [comment]
I recently backported this into 6.1 stable kernel.

**Comment by borkmann** [comment]
> @borkmann Great! Thanks, and it seems to been fixed at 6.1.120, am I right?

Yes, that is correct.
