### ISSUE TITLE
cilium installation with helm not working

### ISSUE THREAD

**Issue by gailsuccess** [cilium/cilium#30585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/cilium/cilium/assets/157372272/5a98bcbf-b342-4893-9be8-c4a6eb2a44c4)

Hello , I am following the instructions on the docs [https://docs.cilium.io/en/stable/installation/k8s-install-helm/](https://docs.cilium.io/en/stable/installation/k8s-install-helm/)

When I type in the command `helm repo add cilium https://helm.cilium.io/` . 
I get this error message
```sh
Error: looks like "https://helm.cilium.io/" is not a valid chart repository or cannot be reached: Get "https://helm.cilium.io/index.yaml": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

```
I can't seem to access [https://helm.cilium.io/](https://helm.cilium.io/) on my browser.

![image](https://github.com/cilium/cilium/assets/157372272/7eecad0c-85a7-44fd-8f83-19d4e668e5b3)

### Cilium Version

v0.15.21

### Kernel Version

lenovo 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.29

### Relevant log output

```shell
helm repo add cilium https://helm.cilium.io/
Error: looks like "https://helm.cilium.io/" is not a valid chart repository or cannot be reached: Get "https://helm.cilium.io/index.yaml": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Anything else?

![image](https://github.com/cilium/cilium/assets/157372272/40089555-552b-44c3-a3f0-7a798b90da23)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
I am just curious if the issue is temporary, it seems to work for me now

```
$ curl https://helm.cilium.io/
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
...
```

**Comment by gailsuccess** [comment]
Thank you @sayboras , I switched to a different internet service provider.
![image](https://github.com/cilium/cilium/assets/157372272/c0fd7538-043c-40d0-8a6e-5f3cec66e55e)
