### ISSUE TITLE
Cilium is dropping IPv4 multicast traffic, with no clear drop reason

### ISSUE THREAD

**Issue by samip5** [cilium/cilium#30586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Traffic to IPs to `224.0.0.22` & `239.255.255.250` as examples get dropped with no reason.

### Cilium Version

cilium-cli: v0.15.18 compiled with go1.21.5 on darwin/arm64
cilium image (default): v1.14.4
cilium image (stable): v1.14.6
cilium image (running): 1.14.6

### Kernel Version

6.1.0-15-amd64

### Kubernetes Version

v1.29.0+k3s1

### Anything else?

I think this is not duplicate as I'm not asking for support, I'm asking for the reason to be listed while it's dropped.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Can you please provide more details about the scenario - who is sending the traffic, where do you see it being dropped (hubble?), what's an example of such a drop indication etc

**Comment by samip5** [comment]
> Can you please provide more details about the scenario - who is sending the traffic, where do you see it being dropped (hubble?), what's an example of such a drop indication etc

Synching is sending the traffic, I see it in Hubble being dropped with no drop reason. It simply lists it as dropped.

**Comment by samip5** [comment]
This should be looked at. @julianwiedmann Was this forgotten?

**Comment by marcocaronna** [comment]
@julianwiedmann I have the same issue
Hubble shows that the UDP packets to 239.255.255.250 are dropped, but the drop reason is empty.

**Cilium Version**
cilium-cli: v0.16.4 compiled with go1.22.1 on linux/amd64
cilium image (default): v1.15.3
cilium image (stable): v1.15.3
cilium image (running): 1.16.0-pre.1 (same issue with 1.15.3 running)

**Kernel Version**
6.1.0-18-amd64

**Kubernetes Version**
v1.29.3

These are the details in Hubble:
**Flow Details**
Timestamp
2024-04-19T12:34:46.659Z

Verdict
dropped

Drop reason

Traffic direction
egress

Source pod
plex-54698d66f7-jb8v5

Source identity
35607

Source labels
app=plex
io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=plex-server
io.cilium.k8s.namespace.labels.name=plex-server
io.cilium.k8s.policy.cluster=kubernetes
io.cilium.k8s.policy.serviceaccount=default
namespace=plex-server

Source IP
10.0.0.214

Destination identity
2

Destination labels
reserved:world

Destination IP
239.255.255.250

Destination port • protocol
1900 • UDP

**Comment by julianwiedmann** [comment]
Ah that's curious. @cilium/sig-hubble does that ring any bells - what would cause us to not report the `Drop reason`?

```
Verdict
dropped

Drop reason

Traffic direction
egress
```

**Comment by gandro** [comment]
Are you able to share a raw JSON object for the Hubble drop? They should contain the numeric reason.

I think the only cases where Hubble would not display a drop reason is because the Hubble client does not know the drop reason and protobuf thus will omit it.

**Comment by marcocaronna** [comment]
I used the Hubble CLI to check the connection and found this line:
`Apr 24 12:45:20.468: plex-server/plex-54698d66f7-jb8v5:47249 (ID:4518) <> 239.255.255.250:1900 (world) TTL exceeded DROPPED (UDP)`
Wild guess: either the switch or the router that the k8s node is connected to doesn't forward the multicast packets properly?

**Comment by networkhermit** [comment]
Got a similar problem originated from tailscale proxy pod, but I have no idea why tailscale pod needs the multicast traffic.

```text
Ethernet        {Contents=[..14..] Payload=[..114..] SrcMAC=00:00:00:00:00:00 DstMAC=01:00:5e:7f:ff:fa EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..94..] Version=4 IHL=5 TOS=0 Length=122 Id=60808 Flags=DF FragOffset=0 TTL=1 Protocol=UDP Checksum=37022 SrcIP=10.42.1.40 DstIP=239.255.255.250 Options=[] Padding=[]}
UDP     {Contents=[..8..] Payload=[..86..] SrcPort=40788 DstPort=1900(ssdp) Length=102 Checksum=64451}
  Packet has been truncated
  Failed to decode layer: No decoder for layer type Payload
CPU 06: MARK 0x0 FROM 184 DROP: 136 bytes, reason TTL exceeded, identity 20773->world-ipv4
------------------------------------------------------------------------------
Ethernet        {Contents=[..14..] Payload=[..114..] SrcMAC=00:00:00:00:00:00 DstMAC=01:00:5e:7f:ff:fa EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..94..] Version=4 IHL=5 TOS=0 Length=165 Id=60809 Flags=DF FragOffset=0 TTL=1 Protocol=UDP Checksum=36978 SrcIP=10.42.1.40 DstIP=239.255.255.250 Options=[] Padding=[]}
UDP     {Contents=[..8..] Payload=[..86..] SrcPort=40788 DstPort=1900(ssdp) Length=145 Checksum=64494}
  Packet has been truncated
  Failed to decode layer: No decoder for layer type Payload
CPU 06: MARK 0x0 FROM 184 DROP: 179 bytes, reason TTL exceeded, identity 20773->world-ipv4

```
