### ISSUE TITLE
FQDN Policies ignore CNAMEs returned during lookup

### ISSUE THREAD

**Issue by foyerunix** [cilium/cilium#30588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello,
 
We successfully deployed Cilium network policies using FQDNs in our environment.
We know the DNS proxy work without issue.
 
Meanwhile we encounter an issue in a specific use case of Cilium FQDN policies.
We want the CiliumNetworkPolicy FQDN entry to reference an A record, while the pod will resolve a CNAME to this DNS entry.
 
Example:
 
FQDN in policy: host.example.com
Pod is resolving: database.example.com
 
Nslookup result:
 
```
nslookup database.example.com
Server:         10.0.0.1
Address:        10.0.0.1#53
 
database.example.com   canonical name = host.example.com.
Name:   host.example.com
Address: 10.10.10.1
```
 
It seem that Cilium is unable to check that:
- The pod actually resolved a CNAME
- The CNAME resolved is present in one CiliumNetworkPolicy as a FQDN
- Therefore the IP resolved by the A record resolved by the CNAME should be allowed
 
If we look there: https://github.com/cilium/cilium/blob/6cc25be48e53136f2d8d6f8b2bdaa1d964f4df92/daemon/cmd/fqdn.go#L336
We can see that the CNAMEs are correctly returned from ExtractMsgDetails
 
But they seem to be only reused for logging purpose: https://github.com/cilium/cilium/blob/6cc25be48e53136f2d8d6f8b2bdaa1d964f4df92/daemon/cmd/fqdn.go#L471
 
Therefore a Cilium FQDN policy is unable to work if it reference an A record that the pod resolve thought a CNAME.
 
Thanks,
Best Regards.

### Cilium Version

v1.14.3

### Kernel Version

5.14.0-362.13.1.el9_3.x86_64

### Kubernetes Version

v1.27.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Thanks for the well-written issue! On first glance this looks on the edge between bug and enhancement. Maybe @cilium/fqdn can advise whether we have the right test infrastructure to build an easy reproducer, and drive a code change from that.

**Comment by christarazi** [comment]
Similar, possibly dup of https://github.com/cilium/cilium/issues/20191
