### ISSUE TITLE
CiliumCIDRGroup not work for egress rules

### ISSUE THREAD

**Issue by minosniugang** [cilium/cilium#30597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am using CiliumCIDRGroup to optimize my cnp, however I found it only work for ingress rule, but not for egress rule.

Here is my spec

apiVersion: cilium.io/v2alpha1
kind: CiliumCIDRGroup
metadata:
  name: myipset
spec:
  externalCIDRs: 
  - 10.118.0.0/16
  - 10.119.0.0/16

apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: mycnp
  namespace: myns
spec:
  endpointSelector:
    matchLabels:
      app: test
  egress:
  - toCIDRSet:
    - cidrGroupRef: myipset

I see in the code CiliumCIDRGroup is only supported in ingress rule, but not egress rule, is there any specific consideration?
Also the doc doesn't mention this limitation.  If it can work for ingress, it is nature to assume it should also work for egress 

### Cilium Version

1.14

### Kernel Version

5.15

### Kubernetes Version

1.23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
> however I found it only work for ingress rule, but not for egress rule.

hi! Can you say in a bit more detail **what** doesn't work - is the CNP resource not accepted, or is it not taking effect, or ...?

@pippolo84 fyi, but https://github.com/cilium/cilium/pull/24638 sounds pretty clear that it's only adding support for Ingress rules.

**Comment by pippolo84** [comment]
> I see in the code CiliumCIDRGroup is only supported in ingress rule, but not egress rule, is there any specific consideration?

Not really. I see that from an older related [proposal](https://github.com/cilium/cilium/issues/10349), the Egress part was mentioned too, but as @julianwiedmann correctly pointed out, the current implementation only supports Ingress.
Is your use case similar to the one depicted in https://github.com/cilium/cilium/issues/10349?

Looking at the code, I'd say it should be doable to add support for Egress as well. Would you be up to contribute a PR?

**Comment by chaunceyjiang** [comment]
> Looking at the code, I'd say it should be doable to add support for Egress as well.

Hi, @pippolo84 I'm very interested in this, I want to try implementing this feature.
