### ISSUE TITLE
Drop kubernetes ThirdPartyResources support?

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#3060]
Kubernetes 1.10 libraries no longer provide any `ThirdPartyResources` used here.

https://github.com/cilium/cilium/blob/c7ba09632af954b3f386589b527ad0e90554c97d/pkg/k8s/apis/cilium.io/v1/register.go#L95

#### Why update to k8s 1.10?

New features introduced in k8s 1.10:

- Categories in CRD which allow cilium network policies to show up under `kubectl get all`
```
	// Categories is a list of grouped resources custom resources belong to (e.g. 'all')
	// +optional
	Categories []string `json:"categories,omitempty" protobuf:"bytes,6,rep,name=categories"`
```
- Subresources in CRD which allows cilium to use `UpdateStatus` instead of `Update` to update the CNP status. This is in **alpha** state, the user needs to enable this in kube-apiserver. In k8s 1.11 it will be enabled by default. If the user is running k8s 1.10 with this feature enable it won't be able to run cilium unless https://github.com/cilium/cilium/pull/2966 is merged before 1.10 is released, this PR doesn't require to update k8s libs.
```
	// Subresources describes the subresources for CustomResources
	// This field is alpha-level and should only be sent to servers that enable
	// subresources via the CustomResourceSubresources feature gate.
	// +optional
	Subresources *CustomResourceSubresources `json:"subresources,omitempty" protobuf:"bytes,6,opt,name=subresources"`
```

### Solutions proposed:

1) Do not upgrade kubernetes libraries to 1.10. Only update them in 1.11
2) Upgrade kubernetes libraries and drop support for k8s 1.6
3) Clone the last kubernetes libraries that contains `ThirdPartyResources` to `cilium/kubernetes` and use that clone for `ThirdPartyResources` usage only.

**Comment by tgraf** [comment]
> Upgrade kubernetes libraries and drop support for k8s 1.6

+1

I see very limited value in running k8s 1.6. k8s is still advancing fast and there is little value to keeping complexity around for minor edge use cases. I'd rather drop TPR support pre 1.0.

**Comment by ianvernon** [comment]
I'm all for this. Which libraries will have to be updated?

**Comment by aanm** [comment]
From what I've tried.
```
k8s.io/apiextensions-apiserver kubernetes-1.8.2
k8s.io/apimachinery kubernetes-1.8.2
k8s.io/api kubernetes-1.8.2
k8s.io/client-go kubernetes-1.8.2
```

This one doesn't need to be update. I've checked and we only use this for the ip-allocator.
```
k8s.io/kubernetes v1.5.1
```

**Comment by tgraf** [comment]
> This one doesn't need to be update. I've checked and we only use this for the ip-allocator.

If we update, we have to configure the ip allocator to continue handing out sequential IPs or fix the agent logic to use well known IPs for the gateway IPs.

**Comment by ianvernon** [comment]
@aanm IIRC this has been done, so can this be closed?
