### ISSUE TITLE
Cilium Identity entry to external IP gets removed by mistake

### ISSUE THREAD

**Issue by revog** [cilium/cilium#30627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We observed a behaviour in one of our Kubernetes cluster running with Cilium v1.14.4. 
Suddenly an external IP (outside of Kubernetes) could no more be reached from inside the Kubernetes cluster. 
* DNS Name resolution was still working and resolving the correct url
* Ping from within a Pod to the resolved IP did not work
* Ping from the node itself to the resolved IP was always working

We did some further investigations and found out, that the Cilium Identity was no more existing. We were able to get the Identity ID by Cilium's BPF IP Cache:

```
root@k8s-node:/home/cilium# cilium bpf ipcache get 10.150.85.3
10.150.85.3 maps to identity identity=16777287 encryptkey=0 tunnelendpoint=0.0.0.0

root@k8s-node:/home/cilium# cilium identity get 16777287
Error: Cannot get identity for given ID 16777287: [GET /identity/{id}][404] getIdentityIdNotFound
```

After deleting the Cilium Pod on the affected Nodes, the Pod got recreated and the identity was known again:
```
root@k8s-node:/home/cilium# cilium bpf ipcache get 10.150.85.3
10.150.85.3 maps to identity identity=16777287 encryptkey=0 tunnelendpoint=0.0.0.0

root@k8s-node:/home/cilium# cilium identity get 16777287
ID         LABELS
16777287   cidr:10.150.85.3/32
           reserved:world
```

This issue was only present on some of the cluster nodes (about 4 from 23 were affected). 

What could be the reason for this behaviour?

### Cilium Version

```
root@k8s-node:/home/cilium# cilium version
Client: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64
Daemon: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64

```

### Kernel Version

`Linux k8s-node 5.14.21-150500.55.44-default #1 SMP PREEMPT_DYNAMIC Mon Jan 15 10:03:40 UTC 2024 (cc7d8b6) x86_64 x86_64 x86_64 GNU/Linux
`

### Kubernetes Version

`Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.5+rke2r1", GitCommit:"506050d61cf291218dfbd41ac93913945c9aa0da", GitTreeState:"clean", BuildDate:"2023-12-20T17:22:09Z", GoVersion:"go1.20.12 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}`

### Sysdump

Cannot upload 300MB+ file ... any alternative?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timbuchwaldt** [comment]
We see this exact behavior with incoming traffic as well. Cilium v1.14.6, randomly nodes start loosing identities like this.

**Comment by lmb** [comment]
Can you please include the config you are using? Feel free to put the sysdump on Drive or similar, as long as it's publicly accessible.

@revog do you see this on 1.14.6 as well?

**Comment by revog** [comment]
> Can you please include the config you are using? Feel free to put the sysdump on Drive or similar, as long as it's publicly accessible.
> 
> @revog do you see this on 1.14.6 as well?

Great, uploaded it to my Dropbox. Here's the direct link
https://www.dropbox.com/scl/fi/nxgu3wxs0v2t7fm36sadh/cilium-sysdump-20240205-091123.zip?rlkey=tzezmugldp3xb2cin3s8atksm&dl=0

Never tried version 1.14.6 (we use the packaged one coming with the Rancher RKE2 release).
