### ISSUE TITLE
Cilium perpetually out of sync in Argo CD due to missing `divisor` spec for `GOMEMLIMIT`

### ISSUE THREAD

**Issue by jdmcmahan** [cilium/cilium#30634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Cilium daemonset does not specify a `divisor` value for [the new `GOMEMLIMIT` environment variable](https://github.com/cilium/cilium/blob/7694bbafb4cdeaf3507506e405386d08b24dcdab/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L195-L198). Kubernetes appears to be setting one on apply by default (`divisor: '0'`) which is flagged as a difference by Argo CD. This results in the Cilium application being perpetually out of sync.

<img width="1546" alt="image" src="https://github.com/cilium/cilium/assets/15273409/f5889d8d-4c53-4f2f-9730-a449bc26e7d0">

### Cilium Version

1.15.0

### Kernel Version

6.1.74

### Kubernetes Version

1.29.1

### Sysdump

[cilium-sysdump.zip](https://github.com/cilium/cilium/files/14172391/cilium-sysdump.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
That's annoying! ArgoCD should fix its defaulting. But the fix here is easy enough :-/
