### ISSUE TITLE
Cilium doesn't handle 2 digit kernel versions

### ISSUE THREAD

**Issue by optix2000** [cilium/cilium#30630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium expects the kernel version to always have 3 digits.

However, the kernel is perfectly allowed to have only 2 or even only 1 digit for the version number.
https://github.com/torvalds/linux/blob/35a4474b5c3dd4315f72bd53e87b97f128d9bb3d/Makefile#L367

### Cilium Version

Cilium 1.14.5 85db28be

### Kernel Version

Linux 6.7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.7.1-1~exp1 (2024-01-22) x86_64 GNU/Linux

### Kubernetes Version

v1.28.4

### Relevant log output

```shell
level=info msg="Cilium 1.14.5 85db28be 2023-12-11T14:30:29+01:00 go version go1.20.12 linux/amd64" subsys=daemon
level=fatal msg="kernel version: NOT OK" error="Invalid character(s) found in minor number \"7-amd64\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\"" subsys=linux-datapath
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
The problem is here: https://github.com/cilium/cilium/blob/4fd12d731e78d5121ec3793b81df026f79bd7c6a/pkg/version/version_unix.go#L19-L39

cc @tklauser

**Comment by tklauser** [comment]
It looks like that function doesn't account for 2 digit kernel versions. Fixing it should be fairly straight-forward. A possible solution would be to use something like Go uses in its `internal/syscall/unix` package: https://github.com/golang/go/blob/master/src/internal/syscall/unix/kernel_version_linux.go

**Comment by MeherRushi** [comment]
@lmb @tklauser I have PR regarding this. Please do let me know if there are any changes to be made
