### ISSUE TITLE
Cilium on GKE: scaling issues and pods unschedulable

### ISSUE THREAD

**Issue by kaliloved** [cilium/cilium#30644]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Hi all,

I'm trying to install Cilium on a GKE cluster with the autoscaling enabled. The cluster has a single regional nodepool that can scale from 1 to 3 nodes per zone. 
As suggested on the Cilium doc (https://docs.cilium.io/en/stable/installation/taints/) I have added some taint to the cluster to ensure Cilium is the selected CNI. I've tried with this taint:
` taint {
      key = "node.cilium.io/agent-not-ready"
      value = "true"
      effect = "NO_EXECUTE"}`
Than with this one:
`taint {
      key = "ignore-taint.cluster-autoscaler.kubernetes.io/agent-not-ready-taint-key"
      value = "true"
      effect = "NO_EXECUTE"}`
And finally with a combination of the two. But after the cluster is initialized and Cilium installed (always following the doc: https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/) I get the following error:
![image](https://github.com/cilium/cilium/assets/67737233/31005fb7-ff17-448c-a0a3-a9595be68ac9)
![image](https://github.com/cilium/cilium/assets/67737233/f2ee237e-f6ce-48c2-bb88-4af49e301e6d)
If I run Cilium status everything is ok, the operator, the agent... are up and running, but the cluster isn't able to scale. Looking at the GKE logs everything seems to point at the taint. Am I using the wrong taints?

### Cilium Version

version 1.15.0

### Kernel Version

5.10.102.1

### Kubernetes Version

1.27.8-gke.1067004

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
@kaliloved have you tried asking on the Slack channel? You might get a quicker answer there.

**Comment by kaliloved** [comment]
Hi @lmb, I've asked on slack and they suggest to open an issue. Do you suggest to add additional info, like entire logs?

**Comment by ti-mo** [comment]
Normally, cilium-operator is responsible for removing these taints once the agent has successfully landed for the first time. I haven't interacted with this system for a while so not sure how it's evolved. Anything interesting in the operator logs? Can it communicate with the k8s api?

**Comment by kaliloved** [comment]
Hi all,
the issue is solved, there was an error in the way I was creating the cluster. Before I was using this configuration:
![image](https://github.com/cilium/cilium/assets/67737233/58025190-7f3d-4d26-b4d5-7bc89a736b9c)
in which the required taint is in "google_container_node_pool"  terraform resource. But using the taint in the "google_container_cluster" tf resource everything works fine, the scheduler works and the taint is removed after Cilium is installed.

**Comment by lmb** [comment]
Thanks for your update. Please copy and paste text instead of adding a screenshot is possible. Then others can search and copy and paste your code.
