### ISSUE TITLE
CFP: Expand Helm to support exposing the Envoy Admin API over a port (vs the current unix socket)

### ISSUE THREAD

**Issue by bdecoste** [cilium/cilium#30647]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

Difficult to gain access to the Envoy Admin API for debugging via a unix socket, especially when Envoy is run as a separate daemonset where installing curl via apt is not possible. 

**Describe the feature you'd like**

Add an option (envoy.debug?) to the Helm charts to enable exposing the Envoy Admin API over a port instead of a unix socket.

**(Optional) Describe your proposed solution**

Proposed change to the Envoy bootstrap configmap attached when this feature is enabled (e.g. envoy.debug in Helm values).

[cilium-envoy-config.yaml.gz](https://github.com/cilium/cilium/files/14182545/cilium-envoy-config.yaml.gz)

**Comment by sayboras** [comment]
This looks reasonable to me.

What do you think about having helm flags envoy.admin.{enabled,port} ?

**Comment by mhofstetter** [comment]
Good proposal.

But we have to ensure that we keep exposing the Admin API via the socket too - because the Cilium Agent is communicating with Envoy through this way (Adjusting log level etc). So it should be "in addition to" and not "instead of".
