### ISSUE TITLE
Filter HTTP in Istio sidecar proxy

### ISSUE THREAD

**Issue by rlenglet** [cilium/cilium#3065]
Implement Cilium L7 HTTP filtering in Istio's sidecar proxy container.

**Envoy**

- [x] Implement a `transparent` per-listener flag in Envoy to support iptables TPROXY instead of REDIRECT, in order to preserve the sockets' source IP addresses. (https://github.com/envoyproxy/data-plane-api/pull/522, https://github.com/envoyproxy/data-plane-api/pull/558, https://github.com/envoyproxy/envoy/pull/2734, https://github.com/envoyproxy/envoy/pull/2719)
- [x] Implement a listener filter that maps the remote IP address of every ingress connection a to security identity using the IP-to-ID mapping published via NPHDS. (https://github.com/cilium/cilium/pull/3407)

**Istio**

- [x] Upstream the Istio sidecar changes from https://github.com/cilium/cilium/pull/3035.
- [x] Extend Istio's Pilot service to set the `transparent` flag on every listener in LDS.
- [x] Configure the Cilium filters in every listener in LDS.
  - [x] Short-term, fork Istio's Pilot service to configure the Cilium filters in every listener in LDS.
  - [x] Long-term, implement an Istio Pilot Webhook to rewrite the listeners in LDS to configure the Cilium filters.

**Cilium**

- [x] Implement hidden `--sidecar-http-proxy` command-line option to disable redirects for HTTP only, since traffic is redirected into Envoy by the Istio sidecar proxy container. (https://github.com/cilium/cilium/pull/3126)
- [x] Handle NPDS and NPHDS ACKs from Envoy, to report the correct policy revision implemented for an endpoint. (https://github.com/cilium/cilium/pull/3151)
- [x] Start the xDS and access log servers independently from the local-node Envoy proxy. (https://github.com/cilium/cilium/pull/3131)
- [x] Fix access logging from Envoy and proxy redirect stats.
  - [x] Support access from non-root Envoy processes. (https://github.com/cilium/cilium/pull/3131)
  - [x] Support multiple concurrent access log connections. (https://github.com/cilium/cilium/pull/3131)
  - [x] Support access logging from Envoy processes non managed by Cilium. (https://github.com/cilium/cilium/pull/3278, https://github.com/cilium/cilium/pull/3600)
  - [x] Report proxy redirect stats per-endpoint instead of per-listener. (https://github.com/cilium/cilium/pull/3278)
- [x] Generate one policy per endpoint, instead of one per identity, based on the endpoint's enforcement mode. Identify each policy by endpoint node IP address. (https://github.com/cilium/cilium/pull/3151, https://github.com/cilium/cilium/pull/3342)
- [x] Generate allow-all policy in case of "never" mode of "default" mode + no rule. (https://github.com/cilium/cilium/pull/3326)
- [x] Build `proxy` and `proxy_init` Docker images. (https://github.com/cilium/cilium/pull/3035)
  - [x] Build an Envoy binary with `transparent` support, Cilium's filters, and Istio's filters.
  - [x] Build a `proxy` image.
    - [x] Add the Envoy binary.
    - [x] Add the pilot-agent binary.
    - [x] Run the Envoy binary with setuid bit set, in order for Envoy to have the CAP_NET_ADMIN capability.
    - [x] Mount 2 named sockets into the container, for xDS and access log.
  - [x] Build a `proxy_init` image that uses TPROXY instead of REDIRECT in PREROUTING in its `prepare-proxy.sh` script.
- [x] Update the Istio GSG doc to upgrade to 0.7.0. (https://github.com/cilium/cilium/pull/3070, https://github.com/cilium/cilium/pull/3530, https://github.com/cilium/cilium/pull/3702)
- [x] Add a section into the Istio GSG to explain the purpose of the GSG.
- [x] Polish the Istio GSG doc. (Optional)
  - [x] Upgrade the Kafka-enhanced demo changes to 0.6.0 (if there were any).
  - [x] Configure the Istio injector to use Cilium's `proxy` and `proxy_init` images.

**Comment by rlenglet** [comment]
test-me-please

**Comment by tgraf** [comment]
@rlenglet What work is left on the Cilium side?

**Comment by rlenglet** [comment]
@tgraf We should be good for 1.0.

There's one more thing we'll need to do at some point: sending the L3-L4-only policies to the sidecar proxies. Right now, in case there are no L7 rules, traffic would be blocked by the sidecar proxies because traffic is always redirected to the proxies. I don't consider that's a blocker since the Istio GSG only uses policies with L7 rules.

And I'll need to update the Istio GSG to update to Istio 0.7.0+ etc.

**Comment by tgraf** [comment]
@rlenglet Thanks! Removing 1.0-blocker
