### ISSUE TITLE
Pods from some (only some) nodes in EKS(1.24) doesn't resolve DNS

### ISSUE THREAD

**Issue by tsanchezlara** [cilium/cilium#30654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi all! I will raise this ticket because honestly I don't know what can I check any more.
I'll describe the issue just in case someone faced the same issue and know WTF is going on here.

We have some EKS clusters in 1.24 version with cilium chart installed (initially version 1.10.19).
Some months ago, we noticed some pods start failing and we identified a DNS issue. The pods couldn't resolve DNS.
After some research we saw:

* This issue happens just in some nodes, the other nodes works properly
* The pod's in the affected node, can't resolve DNS (using coredns) but they can reach the service (tested with netcat)
* The host (EC2) have the same problem, can't resolve using coredns service IP.
* We don't see any drops /filter on iptables or using tcpdump
* Coredns doesn't receive the "crashed" pods DNS queries
* At same time the issue is there, new nodes are created without problems
* The affected node can reach coredns service
  # nc -zuv 172.20.0.10 53
  Ncat: Version 7.50 ( https://nmap.org/ncat )
  Ncat: Connected to 172.20.0.10:53.
  Ncat: UDP packet sent successfully
  Ncat: 1 bytes sent, 0 bytes received in 2.01 seconds.
* The affected nod CAN'T resolve names through coredns service:
  # dig www.google.es @172.20.0.10
  ; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.13.5 <<>> www.google.es @172.20.0.10
  ;; global options: +cmd
  ;; connection timed out; no servers could be reached
* Tested with TCP works properly:
  # dig +tcp crmartinez.com @172.20.0.10
  ;; global options: +cmd
  ;; Got answer:
  ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61059
  ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
  
  ;; OPT PSEUDOSECTION:
  ; EDNS: version: 0, flags:; udp: 4096
  ;; QUESTION SECTION:
  ;www.google.es.			IN	A
  
  ;; ANSWER SECTION:
  www.google.es.		30	IN	A	142.251.111.94
  
  ;; Query time: 10 msec
  ;; SERVER: 172.20.0.10#53(172.20.0.10)
  ;; WHEN: mié feb 07 07:52:40 UTC 2024
  ;; MSG SIZE  rcvd: 71
 * We upgraded to cilium chart version 1.12.18 but the problem persists
 
SOFTWARE VERSIONS:
Cilium chart: 1.12.18
Coredns: 1.9.3.11
EKS: 1.24

Hope someone can bring me some light on these.. I am going mad...

Thank you in advance btw!

### Cilium Version

Client: 1.12.18 04ea6202 2024-01-17T20:26:48+02:00 go version go1.20.12 linux/amd64
Daemon: 1.12.18 04ea6202 2024-01-17T20:26:48+02:00 go version go1.20.12 linux/amd64

### Kernel Version

Linux _node-ip-XX-XX-XX-XX 5.10.205-195.807.amzn2.x86_64 #1 SMP Tue Jan 16 18:28:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.17-eks-5e0fdde", GitCommit:"221f136737816ce068aa975f082cd0bf81c7ad5f", GitTreeState:"clean", BuildDate:"2024-01-02T20:35:57Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

Our installed version doesn't have sysdump

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
@tsanchezlara Are you keeping an eye on your clusters' metrics? if the bpf datapath drops packets, you should see sporadic increases in drop metrics. Also, if it's actually the bpf datapath dropping packets, you can use Hubble to observe that. tcpdump isn't going to tell you about packets it doesn't see. :)

Does this happen on newer Cilium versions as well?

**Comment by tsanchezlara** [comment]
Hi, first thank you @ti-mo for your help!! highly appreciated!
Checking the metrics yes, we can see `missing DNS responses` when a node/s is not working as expected.
With hubble I wasn't be able to see any drop (on the UI).
For me is hard to understand what can provoke this issue. This start happening on cilium version `1.10.19` and upgrading to `10.12.18` didn't fix the issue.
This issue doesn't appair always, jus some days... and most of the nodes (the new created also) works fine...

**Comment by tsanchezlara** [comment]
Hi all, anyone had the chance to check it?

**Comment by tsanchezlara** [comment]
Hi again, has someone checked this ticket? we are still facing this issue and is annoying...

**Comment by ti-mo** [comment]
@tsanchezlara Keep in mind this is not a support channel. We use GH issues as a public bug tracker, where people facing similar issues can interact and exchange troubleshooting ideas. The extra info you've provided is still rather vague. The version you've upgraded to (presumably 1.12) is also aging, have you tried newer?
