### ISSUE TITLE
Use `cosign attest` instead of `cosign attach` for Cilium SBOMs

### ISSUE THREAD

**Issue by sandipanpanda** [cilium/cilium#30664]
Currently, Cilium attaches SBOMs to images using `cosign attach sbom --sbom sbom.spdx quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.name }}@${{ steps.docker_build_release.outputs.digest }}` during build images workflows.

This raises the following warning:
> WARNING: SBOM attachments are deprecated and support will be removed in a Cosign release soon after 2024-02-22 (see https://github.com/sigstore/cosign/issues/2755). Instead, please use SBOM attestations.

Cilium build image workflows need to migrate to using [cosign attest](https://github.com/sigstore/cosign/blob/main/doc/cosign_attest.md)

**Comment by sayboras** [comment]
Thanks for your issue, just curious if you are planning to send PR as well.

**Comment by aanm** [comment]
I'm re-opening this since https://github.com/cilium/cilium/pull/30823 had to be reverted.

**Comment by kumarankit999** [comment]
Looks Interesting, I would like to work on this issue or do collab!

**Comment by sandipanpanda** [comment]
I am working on this!
