### ISSUE TITLE
dnsproxy fails with "cannot assigned requested address" under load

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#30669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With enough dns traffic, cilium starts erroring with `cannot assigned requested address`

### Cilium Version

1.14.6 4a4fa058 2024-01-17T20:45:58+02:00 go version go1.20.12 linux/amd64

### Kernel Version

5.15.0-1052-aws #57~20.04.1-Ubuntu SMP Mon Jan 15 17:04:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.25.16-eks-5e0fdde

### Anything else?

This is related to https://github.com/cilium/cilium/issues/29175
Specifically this change: https://github.com/cilium/cilium/pull/29239

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
How much is "enough" traffic? Do you know of a way to reproduce this in a test setup?

**Comment by dctrwatson** [comment]
> How much is "enough" traffic? Do you know of a way to reproduce this in a test setup?

In the previous incarnations, I wasn't able to synthetically reproduce it easily. But we have a couple clusters were it reliable happens.

> P.S. Was this OK on previous versions of Cilium?
v1.14.3 + v1.14.5 are fine
v1.14.4 + v1.14.6 have issues

**Comment by margamanterola** [comment]
Given that you are calling out the new transparent proxy functionality as a likely reason for the problem, have you tried changing the value of the flag with `--dnsproxy-enable-transparent-mode` (or `dnsProxy.enableTransparentMode` in Helm values)?

**Comment by dctrwatson** [comment]
> Given that you are calling out the new transparent proxy functionality as a likely reason for the problem, have you tried changing the value of the flag with `--dnsproxy-enable-transparent-mode` (or `dnsProxy.enableTransparentMode` in Helm values)?

Sorry, I missed that this was behind a flag now. Let me disable TPROXY mode when rolling forward again.

**Comment by dctrwatson** [comment]
Disabling transparent mode has fixed the errors.

**Comment by christarazi** [comment]
Should the issue be closed?

**Comment by dctrwatson** [comment]
> Should the issue be closed?

Sorry. Yes, this should be closed.
