### ISSUE TITLE
Helm issue when setting kubeProxyReplacement=true - incompatible types for comparison

### ISSUE THREAD

**Issue by heckelmann** [cilium/cilium#30661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm trying to follow the guide to use cilium as a kube-proxy replacement (https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kubeproxy-free)

Running the `helm` upgrade command produces an error. 
```
helm upgrade -i cilium cilium/cilium --version 1.15.0 \
    --namespace kube-system \
    --reuse-values
    --set kubeProxyReplacement=true \
    --set k8sServiceHost=${API_SERVER_IP} \
    --set k8sServicePort=${API_SERVER_PORT}
    
Error: UPGRADE FAILED: template: cilium/templates/cilium-agent/daemonset.yaml:678:48: executing "cilium/templates/cilium-agent/daemonset.yaml" at <ne $kubeProxyReplacement "strict">: error calling ne: incompatible types for comparison
```

### Cilium Version

cilium-cli: v0.15.22 compiled with go1.21.6 on linux/amd64
cilium image (default): v1.15.0
cilium image (stable): v1.14.6
cilium image (running): 1.15.0

### Kernel Version

6.1.74

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.1", GitCommit:"bc401b91f2782410b3fb3f9acf43a995c4de90d2", GitTreeState:"clean", BuildDate:"2024-01-17T15:41:12Z", GoVersion:"go1.21.6", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sayboras** [comment]
Which helm version you are using ? Helm v3.13 is recommended for cilium.

Alternatively, you can try with --set-string instead of set, or --set kubeProxyReplacement='true'.

**Comment by heckelmann** [comment]
Thank you for your reply. Indeed, it was the helm version. I used 3.8 locally... 
After upgrading, it was working.
