### ISSUE TITLE
Docker getting started guide is broken: unable to run `cilium status`

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3068]
Reproducing steps:

`cd ./examples/gettingstarted`
`vagrant up`
`vagrant ssh`

```
vagrant@vagrant:~/cilium$ cilium status
/usr/local/bin/cilium: line 1: syntax error near unexpected token `newline'
/usr/local/bin/cilium: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
```

I followed the instructions from here: http://docs.cilium.io/en/v1.0.0-rc6/gettingstarted/docker/

**Comment by tgraf** [comment]
Are you sure that you followed rc6 and not rc7?

**Comment by ianvernon** [comment]
http://docs.cilium.io redirects to http://docs.cilium.io/en/v1.0.0-rc6/ . I am unable to access http://docs.cilium.io/en/v1.0.0-rc7/. I'm running this against latest master ( 1f78eb3042abd49f29fb3e2fc34053010262c3d1 )

**Comment by tgraf** [comment]
Based on the error message, it means that it couldn't find the binary in the S3 bucket.

**Comment by ianvernon** [comment]
Ah, yeah. releases.cilium.io doesn't have rc7 up yet. The Vagrantfile should check the return code of `curl -sS -L "http://releases.cilium.io/#{cilium_version}/cilium-x86_64" -o /usr/local/bin/cilium` and exit out if it cannot be found to make the error more obvious. We can suggest in the error message to use a more recent version?

**Comment by tgraf** [comment]
Will adjust the release process to upload the binaries right after tagging. The binaries can be made available before the announcement occurs.
