### ISSUE TITLE
CI: Conformance E2E: node-to-node-encryption

### ISSUE THREAD

**Issue by thorn3r** [cilium/cilium#30745]
## CI failure

Output:
```
[=] Test [node-to-node-encryption] [44/70]
....
  [-] Scenario [node-to-node-encryption/node-to-node-encryption]
  [.] Action [node-to-node-encryption/node-to-node-encryption/ping-ipv4: cilium-test/client-56f8968958-f9kb4 (10.244.1.47) -> cilium-test/host-netns-qvxsk (172.18.0.2:0)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/ping-ipv4: cilium-test/host-netns-vz7df (172.18.0.4) -> cilium-test/host-netns-qvxsk (172.18.0.2:0)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/curl-ipv4: cilium-test/host-netns-vz7df (172.18.0.4) -> cilium-test/echo-other-node-7b55b68c-pgs2n (10.244.3.253:8080)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/ping-ipv6: cilium-test/client-56f8968958-f9kb4 (fd00:10:244:1::310f) -> cilium-test/host-netns-qvxsk (fc00:c111::2:0)]
  🟥 Failed to execute tcpdump: %!w(<nil>)
🔍 Collecting sysdump with cilium-cli version: v0.15.21, args: [connectivity test --include-unsafe-tests --collect-sysdump-on-failure --sysdump-hubble-flows-count=1000000 --sysdump-hubble-flows-timeout=5m --sysdump-output-filename cilium-sysdump-2-<ts> --junit-file cilium-junits/Setup & Test (2).xml --junit-property github_job_step=Run tests (2) --request-timeout 30s]
```

Hit in workflow run: https://github.com/cilium/cilium/actions/runs/7890849143/job/21533940004
On PR: https://github.com/cilium/cilium/pull/30361

Sysdump: 
[cilium-sysdumps.zip](https://github.com/cilium/cilium/files/14271090/cilium-sysdumps.4.zip)

**Comment by bimmlerd** [comment]
fixed in https://github.com/cilium/cilium-cli/pull/2321 by Marco

**Comment by joestringer** [comment]
I believe we're waiting on these PRs to get this properly fixed across various branches in this repository:

main: https://github.com/cilium/cilium/pull/31171
v1.15: https://github.com/cilium/cilium/pull/31172
v1.14: https://github.com/cilium/cilium/pull/31173

**Comment by bimmlerd** [comment]
> I believe we're waiting on these PRs to get this properly fixed across various branches in this repository:
> 
> main: #31171 v1.15: #31172 v1.14: #31173

All of the PRs are merged, closing.
