### ISSUE TITLE
arm64 on azure arm64 nodes 

### ISSUE THREAD

**Issue by stgleb** [cilium/cilium#30760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I can't run json-mock workload of version v1.3.4 on azure `Standard_D2ps_v5` linux machine. In the same time it works fine for `Standard_DS2_v2`. Can it be an issue of multi-arch build?

### Cilium Version

v1.3.4

### Kernel Version

v1.3.4

### Kubernetes Version

1.27

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
This does not look like an issue with Cilium. @stgleb are you sure you logged this in the right repo?

**Comment by joestringer** [comment]
@youngnick looks like issues are disabled on json-mock: https://github.com/cilium/json-mock . v1.3.4 [does appear to have arm64 builds](https://quay.io/repository/cilium/json-mock?tab=tags) but I don't know if there is any CI validating the behaviour.

@stgleb I think it would help to understand more specifically what you experience when you say you "can't run json-mock workload". How do you deploy the workload? Are there kubectl events, logs, Pod descriptions, etc which provide some error message?
