### ISSUE TITLE
Targets went unhealthy /blocked by iptables

### ISSUE THREAD

**Issue by nike21oct** [cilium/cilium#30791]
hi ,i have a EKS cluster which is using bottlerocket AMI and cilium as a CNI and nginx as a ingress controller and when i implemented these IP tables rules by bootstrap-container my application stop open from outside the cluster , my target in target group shows unhealthy , we are having network load balancer in aws which is using Protocol : Port is TLS: 32443 and health check is using protocol http and port is 32002, so what should i need to do?
I also observe that when i did the policy to drop for input chain and when I run cilium status for cilium pod it is showing unreachable for node and endpoints.

please help me here , what could be the issue , do I need to add any specific rule here?

#!/usr/bin/env bash

Flush iptables rules
iptables -F

3.4.1.1 Ensure IPv4 default deny firewall policy (Automated)
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

Allow inbound traffic for kubelet (so kubectl logs/exec works)
iptables -I INPUT -p tcp -m tcp --dport 10250 -j ACCEPT

3.4.1.2 Ensure IPv4 loopback traffic is configured (Automated)
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A INPUT -s 127.0.0.0/8 -j DROP

3.4.1.3 Ensure IPv4 outbound and established connections are configured (Manual)
iptables -A OUTPUT -p tcp -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p udp -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p icmp -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -p udp -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -p icmp -m state --state ESTABLISHED -j ACCEPT

Flush ip6tables rules
ip6tables -F

3.4.2.1 Ensure IPv6 default deny firewall policy (Automated)
ip6tables -P INPUT DROP
ip6tables -P OUTPUT DROP
ip6tables -P FORWARD DROP

Allow inbound traffic for kubelet on ipv6 if needed (so kubectl logs/exec works)
ip6tables -A INPUT -p tcp --destination-port 10250 -j ACCEPT

3.4.2.2 Ensure IPv6 loopback traffic is configured (Automated)
ip6tables -A INPUT -i lo -j ACCEPT
ip6tables -A OUTPUT -o lo -j ACCEPT
ip6tables -A INPUT -s ::1 -j DROP

3.4.2.3 Ensure IPv6 outbound and established connections are configured (Manual)
ip6tables -A OUTPUT -p tcp -m state --state NEW,ESTABLISHED -j ACCEPT
ip6tables -A OUTPUT -p udp -m state --state NEW,ESTABLISHED -j ACCEPT
ip6tables -A OUTPUT -p icmp -m state --state NEW,ESTABLISHED -j ACCEPT
ip6tables -A INPUT -p tcp -m state --state ESTABLISHED -j ACCEPT
ip6tables -A INPUT -p udp -m state --state ESTABLISHED -j ACCEPT
ip6tables -A INPUT -p icmp -m state --state ESTABLISHED -j ACCEPT

please help me into this

https://aws.amazon.com/blogs/containers/validating-amazon-eks-optimized-bottlerocket-ami-against-the-cis-benchmark/
I am following above documentation for doing the benchmarking of my EKS cluster

**Comment by youngnick** [comment]
Hmm, I'm not sure what you're trying to achieve with this and Cilium.

For someone to be able to help, you'll need to:
- provide some more information about your setup. Why use iptables and not CiliumNetworkPolicy?
- I suggest running through the page at https://docs.cilium.io/en/stable/operations/troubleshooting
- Also, upload a sysdump as per https://docs.cilium.io/en/stable/operations/troubleshooting/#reporting-a-problem.

**Comment by nike21oct** [comment]
hi @youngnick , we are using CILIUM as a CNI in our EKS cluster. We have a requirement from security team that we need to do the hardening of our EKS AMI that is bottlerocket and in doing this there are the set of iptables rules which we need to implement. So when I implement "iptables -P INPUT DROP" which is the part of iptables rule after implementing this the health check of targets which is worker node gets failed and also the endpoints and node showing unreachable in cilium status of cilium agent pod.

![Uploading Screenshot 2024-02-13 at 5.40.34 PM.png…]()

**Comment by nike21oct** [comment]
hi @youngnick , Any idea how we can solve this issue?

**Comment by joestringer** [comment]
If you're trying to protect the host, I would suggest looking into Cilium's [Host Firewall](https://docs.cilium.io/en/stable/security/host-firewall/#id1) feature. Otherwise, I doubt that someone is going to be able to steer you on the right way to write your iptables rules to integrate with Cilium. Implementing a solution like that gets complicated very quickly as there are many nuances between the rules installed by Cilium vs. the rules you would like to install, and there's a high likelihood that the newly written rules cause unintended packet drops on specific paths through the network stack.
