### ISSUE TITLE
KPR with DSR and Geneve dispatch, but can not work with native routing mode

### ISSUE THREAD

**Issue by BurlyLuo** [cilium/cilium#30845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
level=fatal msg="failed to start: daemon creation failed: unable to initialize kube-proxy replacement options: Node Port \"dsr\" mode with geneve dispatch requires geneve tunnel protocol.\nfailed to stop: unable to find controller ipcache-inject-labels" subsys=daemon

The Helm example configuration in a kube-proxy-free environment with DSR and Geneve dispatch enabled would look as follows:
```
# 1.0: Direct Server Return (DSR) with Geneve[--set loadBalancer.mode=dsr --set loadBalancer.dsrDispatch=geneve]
# https://docs.cilium.io/en/v1.15/network/kubernetes/kubeproxy-free/#direct-server-return-dsr
helm install cilium cilium/cilium --set k8sServiceHost=$controller_node_ip --set k8sServicePort=6443 --version 1.15.0-rc.1 --namespace kube-system --set image.pullPolicy=IfNotPresent --set debug.enabled=true --set debug.verbose="datapath flow kvstore envoy policy" --set bpf.monitorAggregation=none --set monitor.enabled=true --set ipam.mode=cluster-pool --set cluster.name=cilium-lb-dsr-dispatch --set kubeProxyReplacement=true --set routingMode=native --set autoDirectNodeRoutes=true --set ipv4NativeRoutingCIDR="10.0.0.0/8" --set loadBalancer.mode=dsr --set loadBalancer.dsrDispatch=geneve
```

### Cilium Version

cilium image (running): 1.15.0-rc.1

### Kernel Version

[root@wluo cilium-lb-dsr-dsrDispatch]$ uname -r 
6.5.0-18-generic

### Kubernetes Version

```
[root@wluo cilium-lb-dsr-dsrDispatch]$ dip
NAME                                   STATUS   ROLES           AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION     CONTAINER-RUNTIME
cilium-lb-dsr-dispatch-control-plane   Ready    control-plane   6m49s   v1.27.3   172.18.0.4    <none>        Debian GNU/Linux 11 (bullseye)   6.5.0-18-generic   containerd://1.7.1
cilium-lb-dsr-dispatch-worker          Ready    <none>          6m25s   v1.27.3   172.18.0.2    <none>        Debian GNU/Linux 11 (bullseye)   6.5.0-18-generic   containerd://1.7.1
cilium-lb-dsr-dispatch-worker2         Ready    <none>          6m27s   v1.27.3   172.18.0.3    <none>        Debian GNU/Linux 11 (bullseye)   6.5.0-18-generic   containerd://1.7.1
[root@wluo cilium-lb-dsr-dsrDispatch]$ 
```

### Sysdump

[cilium-sysdump-20240219-201537.zip](https://github.com/cilium/cilium/files/14330980/cilium-sysdump-20240219-201537.zip)

### Relevant log output

```shell
level=info msg="Stop hook executed" duration="193.613µs" function="gops.registerGopsHooks.func2 (pkg/gops/cell.go:51)" subsys=hive
level=fatal msg="failed to start: daemon creation failed: unable to initialize kube-proxy replacement options: Node Port \"dsr\" mode with geneve dispatch requires geneve tunnel protocol.\nfailed to stop: unable to find controller ipcache-inject-labels" subsys=daemon
[root@wluo cilium-lb-dsr-dsrDispatch]$ 


if with geneve tunnel mode, it can be worked as expected.
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
:wave: that's right, see the part about DSR Geneve in https://docs.cilium.io/en/stable/operations/upgrade/#upgrade-notes. I'll go and update the docs, thank you!

**Comment by julianwiedmann** [comment]
Please check whether the config change from https://github.com/cilium/cilium/pull/30854 helps :pray:.

**Comment by BurlyLuo** [comment]
Sure, thank a lot.
![image](https://github.com/cilium/cilium/assets/35321202/fdd3e6fc-fd19-4e5d-9c16-72a97f77778b)
```
how to understand the option: 
 --set routingMode=native \\
 --set tunnelProtocol=geneve 
Tunnel Mode or Native Mode?
```

**Comment by julianwiedmann** [comment]
> Tunnel Mode or Native Mode?

native routing, but using `geneve` as tunnel protocol for features that require it (eg DSR-Geneve).
