### ISSUE TITLE
loadBalancerSourceRanges doesn't block access

### ISSUE THREAD

**Issue by judge-red** [cilium/cilium#30843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've set .spec.loadBalancerSourceRanges like this on a Service of type LoadBalancer:
```
spec:
  loadBalancerSourceRanges:
  - 1.1.1.1/32
```
And I haven't disabled enable-svc-source-range-check in Cilium:
```
$ cilium config view | grep -i source
enable-svc-source-range-check                     true
```
Yet I can access this LB from my IP (which definitely isn't 1.1.1.1/32) just fine. First time I'm trying this as previously our external LB supported loadBalancerSourceRanges natively but the one we're using now doesn't, so I can't be sure I'm missing some other required configuration but couldn't find anything.

### Cilium Version

```
$ cilium version
cilium-cli: v0.15.23 compiled with go1.22.0 on darwin/amd64
cilium image (default): v1.15.0
cilium image (stable): v1.15.1
cilium image (running): 1.14.7
```

### Kernel Version

```
Linux <hostname> 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.10
WARNING: version difference between client (1.29) and server (1.27) exceeds the supported minor version skew of +/-1
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
Thanks for the issue! Could you upload the sysdump?

**Comment by judge-red** [comment]
@brb Sure! But GitHub doesn't allow to upload files that big. Is there a best practice where to put it instead or just anywhere?

**Comment by brb** [comment]
Google Drive should do the job.

**Comment by judge-red** [comment]
sysdump:
https://drive.switch.ch/index.php/s/gQDbJGjtnTAhgrj/download

**Comment by judge-red** [comment]
Outside, from my laptop, which is not in any way joined to the k8s cluster.

**Comment by brb** [comment]
Which service from the sysdump did you access?

**Comment by judge-red** [comment]
Service `front-loadbalancer` in namespace `cluster-elqrlxtlfs`. Note that a service of the same name exists in many namespaces.

**Comment by brb** [comment]
Everything (the BPF maps) seems to be plumbed correctly. Also, we have an e2e test which is passing to test the `loadBalancerSourceRanges` filtering - https://github.com/cilium/cilium/blob/main/test/k8s/bgp.go#L160.

**Comment by judge-red** [comment]
That's great to know, but definitely doesn't seem to match reality :/

Any idea how to further debug this? Unfortunately I'm still very new to Cilium and not sure what to look at or how to look at it.

**Comment by brb** [comment]
This function is the starting point - https://github.com/cilium/cilium/blob/v1.15/bpf/lib/lb.h#L1213

**Comment by judge-red** [comment]
Ah, I was thinking on more on the operational layer. Unfortunately I'm not very good with code. Anyway, thanks for your help until here! I'll see if I can find anything more.
