### ISSUE TITLE
DNS Mostly Unresponsive After Cilium Deploy

### ISSUE THREAD

**Issue by reed-hanger** [cilium/cilium#30857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm attempting to deploy a new EKS cluster using the same settings as our previously working cluster but with an updated cilium helm chart. Once cilium is deployed, DNS resolution mostly breaks (it intermittently works but generally stops receiving responses from the DNS server, 172.20.0.10) on our flux & gatekeeper pods. The broken DNS stops further services from deploying as flux is no longer able to download artifacts. 

When I remote into the flux-system/source-controller container as the cluster starts, I'm initially able to resolve source-controller.flux-system.svc.cluster.local, but it generally fails just a few minutes later:
```
~ $ nslookup source-controller.flux-system.svc.cluster.local
Server:         172.20.0.10
Address:        172.20.0.10:53


Name:   source-controller.flux-system.svc.cluster.local
Address: 172.20.140.195

~ $ nslookup google.com
Server:         172.20.0.10
Address:        172.20.0.10:53

Non-authoritative answer:
Name:   google.com
Address: 142.251.32.14

Non-authoritative answer:
Name:   google.com
Address: 2607:f8b0:4009:802::200e

~ $ nslookup notification-controller
Server:         172.20.0.10
Address:        172.20.0.10:53

Name:   notification-controller.flux-system.svc.cluster.local
Address: 172.20.145.96

** server can't find notification-controller.svc.cluster.local: NXDOMAIN


** server can't find notification-controller.svc.cluster.local: NXDOMAIN

** server can't find notification-controller.cluster.local: NXDOMAIN

** server can't find notification-controller.cluster.local: NXDOMAIN

** server can't find notification-controller.us-east-2.compute.internal: NXDOMAIN

** server can't find notification-controller.us-east-2.compute.internal: NXDOMAIN

~ $ nslookup source-controller.flux-system.svc.cluster.local
;; connection timed out; no servers could be reached

~ $ nslookup notification-controller.flux-system.svc.cluster.local
Server:         172.20.0.10
Address:        172.20.0.10:53


Name:   notification-controller.flux-system.svc.cluster.local
Address: 172.20.145.96


~ $ nslookup google.com
;; connection timed out; no servers could be reached

~ $ nslookup google.com
Server:         172.20.0.10
Address:        172.20.0.10:53

Non-authoritative answer:
Name:   google.com
Address: 172.217.0.174

Non-authoritative answer:
Name:   google.com
Address: 2607:f8b0:4009:802::200e

~ $ nslookup google.com
;; connection timed out; no servers could be reached
```

I deployed a network troubleshooting containers in the cilium pods, and it's able to consistently resolve DNS.
We do not have any network policies defined.
`cilium status` reports that it is not managing all cluster pods:
```
$ cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        disabled

Deployment             cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
DaemonSet              cilium             Desired: 4, Ready: 4/4, Available: 4/4
Containers:            cilium             Running: 4
                       cilium-operator    Running: 2
Cluster Pods:          2/6 managed by Cilium
Helm chart version:    1.15.1
Image versions         cilium             <my-company-pull-thru-cache>/cilium/cilium:v1.15.1@sha256:351d6685dc6f6ffbcd5451043167cfa8842c6decf80d8c8e426a417c73fb56d4: 4
                       cilium-operator    <my-company-pull-thru-cache>/cilium/operator-generic:v1.15.1@sha256:819c7281f5a4f25ee1ce2ec4c76b6fbc69a660c68b7825e9580b1813833fa743: 2
```

After reviewing the v14 and v15 upgrade notes, I expected DNS functionality to work, as long as I made the proper `tunnel: disabled` replacement with `routingMode: native` in the helm chart.

### Cilium Version

v1.14.4, v1.14.7, and v1.15.1

### Kernel Version

6.1.72

### Kubernetes Version

Tested on both v1.26.12-eks-5e0fdde (v1.14.7) and v1.29.0-eks-c417bb3 (v1.15.1)

### Regression

Yes, v1.13.10

### Sysdump

[cilium-sysdump-20240219-172211.zip](https://github.com/cilium/cilium/files/14337350/cilium-sysdump-20240219-172211.zip)

### Relevant log output

```shell
# We are only seeing these errors in v1.15.0 and v1.15.1, from the cilium-agent logs:
2024-02-19T22:11:01.940150236Z level=info msg="Serving cilium health API at unix:///var/run/cilium/health.sock" subsys=health-server
2024-02-19T22:11:01.954748991Z level=info msg="Node updated" clusterName=default nodeName=ip-10-37-6-109.us-east-2.compute.internal subsys=nodemanager
2024-02-19T22:11:01.955077828Z level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eth1 ipAddr=10.37.6.109 subsys=node-neigh-debug
2024-02-19T22:11:02.002827344Z level=info msg="Node updated" clusterName=default nodeName=ip-10-37-6-239.us-east-2.compute.internal subsys=nodemanager
2024-02-19T22:11:02.003173162Z level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eth1 ipAddr=10.37.6.239 subsys=node-neigh-debug
2024-02-19T22:11:02.088324021Z level=info msg="Node updated" clusterName=default nodeName=ip-10-37-6-109.us-east-2.compute.internal subsys=nodemanager
2024-02-19T22:11:02.088721840Z level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eth1 ipAddr=10.37.6.109 subsys=node-neigh-debug
2024-02-19T22:11:02.135144746Z level=info msg="Node updated" clusterName=default nodeName=ip-10-37-6-239.us-east-2.compute.internal subsys=nodemanager
2024-02-19T22:11:02.135686278Z level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eth1 ipAddr=10.37.6.239 subsys=node-neigh-debug
2024-02-19T22:11:04.074591980Z level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2024-02-19T22:11:59.857526660Z level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eth1 ipAddr=10.37.6.239 subsys=node-neigh-debug
2024-02-19T22:11:59.857752215Z level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eth1 ipAddr=10.37.6.122 subsys=node-neigh-debug
2024-02-19T22:11:59.857808706Z level=info msg="Unable to determine next hop address" error="remote node IP is non-routable" interface=eth1 ipAddr=10.37.6.109 subsys=node-neigh-debug
```

### Anything else?

I don't see the hop/non-routable node IP errors or any others for the cilium-agent DaemonSet or cilium-operator pods in v1.14.7, which makes me believe it's NOT the primary issue here.
I don't have an easy way to run the cilium CLI connectivity test as the only running nodes are all tainted. We roll out untainted nodes sometime after cilium is deployed, but with this bug we don't get that far.

This is all fairly new to me. I didn't configure the initial network or cilium on our working clusters. The nodes I tested v1.15.1 on are running bottlerocket-aws-k8s-1.29-x86_64-v1.19.1-c325a08b. The v1.13.10 & v1.14.7 nodes are running bottlerocket-aws-k8s-1.26-x86_64-v1.19.1-c325a08b.

Our Helm Values for v1.15.1:
```
cgroup: # All child values added for v1.15.1
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cni:
  uninstall: false
  chainingMode: aws-cni
  exclusive: false
encryption:
  enabled: true
  type: wireguard
endpointRoutes:
  enabled: true
envoy: # Added for v1.15.1
  create: false
enableIPv4Masquerade: false
l7Proxy: false
nodeinit: # Added for v1.15.1
  create: false
routingMode: native # Switched from `tunnel: disabled` for v1.15.1
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
Hi @reed-hanger, what leads you to believe `remote node IP is non-routable` is not relevant to the issue? Do the logs roughly correspond to connectivity interruptions? Even though from a user POV it's absolutely expected for things to continue to work the same way as long as you follow the upgrade instructions, the context you provided around 1.14 is rather confusing.

This is a clean 1.15 deployment, correct? Just with a ported Helm config.

I'd look into the root cause of `Unable to determine next hop address`, since the code emitting those logs is directly responsible for populating the route table(s). No routes, no traffic. Since you're running in chaining mode, changes in aws-cni can upset assumptions made by Cilium.

**Comment by reed-hanger** [comment]
Hello, after further troubleshooting, I found that simply killing the flux pods after deploying v1.15.1 of cilium resolved the issue. I guess in v1.13.x, the flux pods somehow automatically became managed by cilium, but starting in v1.14.x, that is no longer the case.
I am still seeing frequent `remote node IP is non-routable` errors, however this doesn't appear to have any adverse effect on the network. All of my pods deployed successfully, then I deployed some web applications to the cluster, hit them with a load tester, and none of the +100000 requests were dropped.

In case you'd like to continue reviewing this issue, I've attached the 
[cilium-sysdump zip](https://github.com/cilium/cilium/files/14440228/cilium-sysdump-20240228-164256.zip). If not, I'm content with closing this issue.

**Comment by ti-mo** [comment]
@reed-hanger `cilium-operator` emits a log line if it decides to kill an unmanaged pod. I'm not 100% sure what the criteria are for detecting unmanaged pods today, it has evolved over the years.

Thanks for reporting back your findings, appreciate it!

**Comment by reed-hanger** [comment]
Hello, after some further digging and looking through other issues, I found that I could replicate the v1.13.x behavior by adding this setting to my helm release to make cilium-operator restart *any* pods it's not managing, which is the behavior I'd like.:

```
operator:
  extraArgs:
    - --pod-restart-selector=
```

My final working helm release for v1.15.1 used these values:

```
        operator:
          extraArgs:
          - --pod-restart-selector=
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        cni:
          uninstall: false
          chainingMode: aws-cni
          exclusive: false
        nodeinit:
          create: false
        routingMode: native
        envoy:
          create: false
        enableIPv4Masquerade: false
        endpointRoutes:
          enabled: true
        encryption:
          enabled: true
          type: wireguard
        l7Proxy: false
```

I'll go ahead and close this issue since the cluster is operational.
