### ISSUE TITLE
CI: Conformance Cluster Mesh - check-log-errors - bind: address already in use

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#30901]
## CI failure

Hit on https://github.com/cilium/cilium/pull/30883
Link: https://github.com/cilium/cilium/actions/runs/8001948757/job/21854165755
Sysdump: [cilium-sysdumps.zip](https://github.com/cilium/cilium/files/14374396/cilium-sysdumps.zip)

```
[=] Test [check-log-errors] [71/71]
.
  [-] Scenario [check-log-errors/no-errors-in-logs]
  [.] Action [check-log-errors/no-errors-in-logs/kind-cluster1-8001948757/kube-system/cilium-v5wdd (cilium-agent)]
  ❌ Found 2 logs in kind-cluster1-8001948757/kube-system/cilium-v5wdd (cilium-agent) matching list of errors that must be investigated:
level=error msg="Cannot forward proxied DNS lookup" DNSRequestID=11879 dnsName=google.com.cluster.local. endpointID=3911 error="failed to dial connection to 10.242.1.245:53: dial udp 10.242.1.208:51871->10.242.1.245:53: bind: address already in use" identity=57932 ipAddr="10.242.1.208:51871" subsys=fqdn/dnsproxy (1 occurrences)
level=error msg="Cannot forward proxied DNS lookup" DNSRequestID=11649 dnsName=google.com.cluster.local. endpointID=3911 error="failed to dial connection to 10.242.1.245:53: dial udp 10.242.1.208:51871->10.242.1.245:53: bind: address already in use" identity=57932 ipAddr="10.242.1.208:51871" subsys=fqdn/dnsproxy (1 occurrences)
```

**Comment by thorn3r** [comment]
Hit again on https://github.com/cilium/cilium/pull/30361
Workflow: https://github.com/cilium/cilium/actions/runs/8088292225/job/22102054567
Sysdump: 
[cilium-sysdump-9-final.zip](https://github.com/cilium/cilium/files/14442905/cilium-sysdump-9-final.zip)

**Comment by tommyp1ckles** [comment]
Seeing this a lot failing conformance-e2e as well

@giorio94 I think is potentially a bug in fqdn-proxy, I've created a bug issue to describe the problem: https://github.com/cilium/cilium/issues/31535

**Comment by tommyp1ckles** [comment]
Hit this here (conformance-e2e) https://github.com/cilium/cilium/actions/runs/8335345820/job/22810714342

**Comment by tommyp1ckles** [comment]
Found another one here: https://github.com/cilium/cilium/actions/runs/8304177112/job/22729484505

**Comment by tommyp1ckles** [comment]
Another one here: https://github.com/cilium/cilium/actions/runs/8357822062/job/22877789573

**Comment by tommyp1ckles** [comment]
Closing as https://github.com/cilium/cilium-cli/pull/2438 should now prevent this known issue from causing CI flakes.
