### ISSUE TITLE
Reject policies that contain rules with more than one L3 match in a single rule

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#3092]
Update CRD validation

**Comment by ianvernon** [comment]
I presume there is a mismatch after the PR related to the title was merged between the CRD validation - Is there a way that this can be caught by the CI?

**Comment by aanm** [comment]
Not for this specific case.

For the differences between structs and CRD validation there's a proposal / PR in k8s that will allow the auto generation of the CRD based on the structures
