### ISSUE TITLE
Cilium must fail if k8s watcher can't be started

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3093]
When running in a Kubernetes environment:
 - Relevant environment variables are set
 - API server is configured via agent option

then users are expecting the pod health to represent the health of Cilium. The following failures must result in Cilium being reported as unhealthy:
 - Failure to create any of the k8s watchers
 - Failure to connect to etcd
 - Failure to connect to the apiserver

If any of the above fails, the Kubernetes component status must be to failed and `cilium status` must return an error code.

**Comment by raybejjani** [comment]
> * Failure to create any of the k8s watchers

I'm not sure how to enforce this. The calls to start informers and event handlers don't seem to return errors, or even have a way to check an error. We also don't seem to have any errors returned in the callbacks we pass in. I'll try to find a good way to detect a catastrophic failure in parsing k8s and report that.

> * Failure to connect to etcd

All places we call kvstore.Setup are already fatal (https://github.com/cilium/cilium/blob/master/cilium/cmd/kvstore.go#L55 and https://github.com/cilium/cilium/blob/master/daemon/main.go#L629-L635)
This will also apply to consul.

> * Failure to connect to the apiserver

https://github.com/cilium/cilium/pull/3142 enforces this more stringently and earlier in the setup process. This will mark the cilium pod as bad, but it doesn't actually set a status field.

**Comment by raybejjani** [comment]
So, we exit(1) from `cilium status` when the agent state is not OK. This is set server-side after it checks the k8s state (Along with kvstore and container runtime). The k8s state relies on ComponentStatus which I hope contains all the watchers and whether they have errors. I'll verify this in a little bit.

**Comment by tgraf** [comment]
> I'm not sure how to enforce this. The calls to start informers and event handlers don't seem to return errors, or even have a way to check an error. We also don't seem to have any errors returned in the callbacks we pass in. I'll try to find a good way to detect a catastrophic failure in parsing k8s and report that.

I think there is an error handler which was used to restart some of the watchers on error. The watcher itself will just restart on error I think.

**Comment by tgraf** [comment]
k8s watcher failures cannot be detected reliably. Closing this.
