### ISSUE TITLE
Envoy DaemonSet fails probes on IPv6 single-stack cluster

### ISSUE THREAD

**Issue by iandrewt** [cilium/cilium#30968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On a true IPv6 only cluster (nodes and pods only have IPv6 addresses, except for the standard 127.0.0.1 loopback, no IPv4 routes), the readiness/liveness/startup probes for the Envoy DaemonSet fail with connection refused as the kubelet does not fall back to IPv6 after failing to probe over IPv4.

Changing the readiness probes to specifically query `::1` works, as I'm sure the reverse would if encountering a similar issue on an IPv4 only cluster.

I'm not entirely sure how k8s does DNS lookups for probes (I presume it's just part of the `net` library) but given there's no need for the readiness probe to resolve `localhost` to do its probe, this should probably be set to the localhost IP directly. Happy to raise a PR for that.

### Cilium Version

v1.15.1

### Kernel Version

`Linux i-0f0d5a7c8c89a74cb 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

Ubuntu 22.04.3 LTS

### Kubernetes Version

v1.29.2

### Relevant log output

```shell
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  BackOff    7m50s (x58 over 34m)    kubelet  Back-off restarting failed container cilium-envoy in pod cilium-envoy-jfxr5_kube-system(42b62c37-9f54-442b-84d4-4d70e03b8e98)
  Warning  Unhealthy  2m49s (x1306 over 62m)  kubelet  Startup probe failed: Get "http://localhost:9878/healthz": dial tcp 127.0.0.1:9878: connect: connection refused
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ldelossa** [comment]
@iandrewt thanks for the bug report. Are you able to provide a sysdump?

**Comment by sayboras** [comment]
Thanks for reporting this issue, the host value in all probes is hard coded as localhost in the helm chart. Can you help to test out the below change?

https://github.com/cilium/cilium/pull/30994
