### ISSUE TITLE
question to get invited to slack

### ISSUE THREAD

**Issue by bramm98** [cilium/cilium#30983]
Hi,

I'm so sorry to post here, but I need to ask a question about cilium on slack, but I don't know how to get in contact with the CIlium worspace administrator, this is my only contact option.

Many thanks,

Bram Jansen

**Comment by bramm98** [comment]
Hi Ryan,

 
Thanks for replying.

For some reason, maybe I’m missing something, I cannot get on the slack workspace from Cilium. They say contact a workspace admin to get an invitation. And then there is nowehere to find out how. Please see the link you gave me yourself, when not logged in.

 
I would like to ask a question about eBPF usage

 
Thank you

 
Bram

**Comment by thebsdbox** [comment]
Hello, the invite link has been fixed. Apologies for any confusion.
