### ISSUE TITLE
LXCMap truncates identities to 16 bits

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3098]
https://github.com/cilium/cilium/blob/36e5df58600e5072e5c4c9027509e2bd38fc46e2/pkg/endpoint/endpoint.go#L1048

Currently the BPF map value definition only supports 16-bit identities:

https://github.com/cilium/cilium/blob/36e5df58600e5072e5c4c9027509e2bd38fc46e2/bpf/lib/common.h#L171

I'll put together a patch proposing that we just add a 32-bit identity later in the structure and shift everything over to use that. ~~It may cause an outage during upgrade, but after the first `regenerateBPF` the new map should be populated correctly.~~

Nice catch by @ianvernon .

**Comment by tgraf** [comment]
I'm not sure this has to be priority high. We can't support 32 bits in the vxlan tunnel id anyway. I think it was just lazy coding on the user space side with the intent to eventually support more than 16 bits.

**Comment by joestringer** [comment]
@tgraf I see. Is anything stopping us from generating a large identity number and truncating it, then allowing traffic from the wrong identities on a remote node?

**Comment by tgraf** [comment]
> @tgraf I see. Is anything stopping us from generating a large identity number and truncating it, then allowing traffic from the wrong identities on a remote node?

Yes:
``` go
                minID := allocator.ID(MinimalNumericIdentity)
                maxID := allocator.ID(^uint16(0))
                a, err := allocator.NewAllocator(IdentitiesPath, globalIdentity{},
                        allocator.WithMax(maxID), allocator.WithMin(minID),
                        allocator.WithSuffix(owner.GetNodeSuffix()))
```

**Comment by joestringer** [comment]
Relevant code was removed.
