### ISSUE TITLE
Socket-lb: Handling active connections to legacy backends when using ciliumlocalredirectpolicies.

### ISSUE THREAD

**Issue by AndreyPavlovFlant** [cilium/cilium#31012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The main problem is the same as in issue [12859](https://github.com/cilium/cilium/issues/12859). 
When using socket-lb, if the backends are deleted, there is a problem with hanging UDP sockets.
For the case of `hostns`, [PR25169](https://github.com/cilium/cilium/pull/25169) has been made, which mostly solves this problem.

But if `ciliumlocalredirectpolicies` is used (in my case for [node-local-dns](https://docs.cilium.io/en/stable/network/kubernetes/local-redirect-policy/#node-local-dns-cache)), and the pod to which the redirection is directed has been deleted, then such sockets are not detected and are not deleted.

### Cilium Version

cilium image (default): v1.15.0

### Kernel Version

Linux sandbox-master-0 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.7
Server Version: v1.28.7

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Hi! You can disable socket-LB in the meantime to counter the shortcomings, and rely on cilium's per packet LB datapath instead.

**Comment by AndreyPavlovFlant** [comment]
I apologize for not specifying that we use the "kubeproxy-free" mode (kubeProxyReplacement=true + socket LB.hostNamespaceOnly=true).

It seems that in this case, disabling socket-lb is not possible.
As a workaround, we are currently restarting the "source pod" or manually removing the hanging sockets.

**Comment by aditighag** [comment]
Hi! You can enable socket-LB only in the host netns, and have per-packet LB enabled for the pods. The latter doesn't have this stale backend issue. Are you using [this guide](https://docs.cilium.io/en/stable/network/kubernetes/local-redirect-policy/#node-local-dns-cache) to deploy node-local dns with socket-LB?

Can you explain in more details how you are seeing the stale backends issue with this configuration? Do you have the relevant Hubble flows?

**Comment by AndreyPavlovFlant** [comment]
## initial state

- We have cilium 1.15.3
```
root@sandbox-master-0:/home/cilium# cilium version
Client: 1.15.3 22dfbc58 2024-03-26T11:45:10+01:00 go version go1.21.8 linux/amd64
Daemon: 1.15.3 22dfbc58 2024-03-26T11:45:10+01:00 go version go1.21.8 linux/amd64
```
- We have kube-dns and node-local-dns pods and their svc
```
NAME                           READY  STATUS    RESTARTS AGE   IP            NODE                                 NOMINATED NODE READINESS GATES
d8-kube-dns-56cff74bb7-cx2ss   2/2    Running   0        124m  10.111.0.150  sandbox-master-0                     <none>         <none>
d8-kube-dns-56cff74bb7-gcgkl   2/2    Running   0        124m  10.111.3.84   sandbox-worker-02334ee2-7694f-gj4j6  <none>         <none>
node-local-dns-6bjlz           2/2    Running   0        115m  10.111.3.31   sandbox-worker-02334ee2-7694f-gj4j6  <none>         <none>
node-local-dns-lb4mf           2/2    Running   0        115m  10.111.1.64   sandbox-worker-02334ee2-7694f-vl55g  <none>         <none>
node-local-dns-xwm44           2/2    Running   0        115m  10.111.0.254  sandbox-master-0                     <none>         <none>
```
```
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP                                 PORT(S)         AGE    SELECTOR
d8-kube-dns     ClusterIP      10.222.0.10     <none>                                      53/UDP,53/TCP   133d   k8s-app=kube-dns
kube-dns        ExternalName   <none>          d8-kube-dns.kube-system.svc.cluster.local   <none>          133d   <none>
```
- We have CiliumLocalRedirectPolicy
```
apiVersion: cilium.io/v2
kind: CiliumLocalRedirectPolicy
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        app: node-local-dns
    toPorts:
    - name: dns
      port: "53"
      protocol: UDP
    - name: dns-tcp
      port: "53"
      protocol: TCP
  redirectFrontend:
    serviceMatcher:
      namespace: kube-system
      serviceName: d8-kube-dns
```
- We use `kubernetes/ingress-nginx` as the `ingress-controller`. In which the nameserver is set to 10.222.0.10(cluster ip of svc kube-dns).
```
NAME                    READY   STATUS    RESTARTS   AGE    IP                NODE               NOMINATED NODE   READINESS GATES
controller-main-vsk27   3/3     Running   0          116m   192.168.199.228   sandbox-master-0   <none>           <none>
```
- `ingress-nginx` uses a long-lived udp session for DNS. If we exec into the pod, we will see sessions to the ip address of the `node-local-dns` pod, that is running on the same node.
```
root@sandbox-master-0:~/tmp14# kubectl -n d8-ingress-nginx exec -ti controller-main-vsk27 -- bash
Defaulted container "controller" out of: controller, protobuf-exporter, kube-rbac-proxy
bash-4.4$ ss -tupan dport 53
Netid               State           Recv-Q          Send-Q        Local Address:Port        Peer Address:Port               Process
udp                 ESTAB           0               0              10.111.0.178:64241       10.111.0.254:53
udp                 ESTAB           0               0              10.111.0.178:56172       10.111.0.254:53
udp                 ESTAB           0               0              10.111.0.178:32924       10.111.0.254:53
```

## Case 1

- Let's restart the `node-local-dns` pod `node-local-dns-xwm44` (10.111.0.254) and wait until the new pod is ready
```
node-local-dns-jlmj5    2/2     Running   0      5m    10.111.0.203      sandbox-master-0     <none>      <none>
```
- Now all requests to `ingress-nginx` after a 30-second delay return error 500. I see the following errors in the log
```
2024/03/28 16:01:24 [error] 31#31: *182794 cilium-hubble-dex-authenticator.d8-cni-cilium.svc.cluster.local could not be resolved (110: Operation timed out), server: hubble.sandbox.testdomain.com, request: "GET /?namespace=cilium-test HTTP/2.0", subrequest: "/_external-auth-Lw-Prefix", host: "hubble.sandbox.testdomain.com"
```
- Let's check dns connections in `ingress-nginx`
```
root@sandbox-master-0:~/tmp14# kubectl -n d8-ingress-nginx exec -ti controller-main-vsk27 -- bash
Defaulted container "controller" out of: controller, protobuf-exporter, kube-rbac-proxy
bash-4.4$ ss -tupan dport 53
Netid               State            Recv-Q         Send-Q          Local Address:Port       Peer Address:Port               Process
udp                 ESTAB            0              0                10.111.0.178:64241      10.111.0.254:53
udp                 ESTAB            0              0                10.111.0.178:56172      10.111.0.254:53
udp                 ESTAB            0              0                10.111.0.178:32924      10.111.0.254:53
```
- All connections still pointed to the ip of the `node-local-dns`, which had already been destroyed
- I am deleting these connections
```
ss -K dport 53
```
- After that, all web pages began to open correctly, and new connections to node-local-dns pod(which is now running) were created in the ingress-nginx
```
bash-4.4$ ss -tupan dport 53
Netid               State           Recv-Q           Send-Q         Local Address:Port         Peer Address:Port               Process
udp                 ESTAB           0                0               10.111.0.178:47431        10.111.0.203:53
udp                 ESTAB           0                0               10.111.0.178:14726        10.111.0.203:53
udp                 ESTAB           0                0               10.111.0.178:39490        10.111.0.203:53
```

## Case 2

- Now let's remove the `CiliumLocalRedirectPolicy` and restart the `ingress-nginx` module. After it starts, we will check the connections to dns
```
bash-4.4$ ss -tupan dport 5353
Netid               State           Recv-Q           Send-Q         Local Address:Port        Peer Address:Port               Process
bash-4.4$ ss -tupan dport 5353
Netid               State           Recv-Q           Send-Q         Local Address:Port        Peer Address:Port               Process
udp                 ESTAB           0                0            192.168.199.228:43218       10.111.0.150:5353
udp                 ESTAB           0                0            192.168.199.228:12272       10.111.0.150:5353
udp                 ESTAB           0                0            192.168.199.228:49778       10.111.0.150:5353
```
- We see that now `ingress-nginx` connects to one of the `kube-dns` pods, and not to the `node-local-dns`
- Let's restart the `kube-dns` pod `d8-kube-dns-56cff74bb7-cx2ss` (10.111.0.150) and wait until the new pod is ready
```
d8-kube-dns-56cff74bb7-2mdsw     2/2     Running   0      51s  10.111.0.231      sandbox-master-0       <none>       <none>
```
- I checked the requests to `ingress-nginx` - everything returned 200 OK
- Let's check dns connections in ingress-nginx
```
bash-4.4$ ss -tupan dport 5353
Netid          State       Recv-Q     Send-Q        Local Address:Port       Peer Address:Port               Process
udp            ESTAB       0          0           192.168.199.228:39449       10.111.3.84:5353
udp            ESTAB       0          0           192.168.199.228:57644       10.111.3.84:5353
udp            ESTAB       0          0              10.111.0.178:42295      10.111.0.231:5353
```
- All connections pointed to the ip of other kube-dns pods that are currently running

- Unlike the previous case, this time I saw the following lines in the log:
```
2024-03-28T16:48:18.590677288Z level=debug msg="handling connections to deleted backend {10.111.0.150 {UDP 5353} 0}" subsys=service
2024-03-28T16:48:18.590680283Z level=info msg="socket {43218 5353 192.168.199.228 10.111.0.150 0 [400611 0]}" subsys=datapath-sockets
2024-03-28T16:48:18.590683029Z level=debug msg="Destroyed socket: {43218 5353 192.168.199.228 10.111.0.150 0 [400611 0]}" subsys=datapath-sockets
2024-03-28T16:48:18.590685844Z level=info msg="socket {12272 5353 192.168.199.228 10.111.0.150 0 [409703 0]}" subsys=datapath-sockets
2024-03-28T16:48:18.590688349Z level=debug msg="Destroyed socket: {12272 5353 192.168.199.228 10.111.0.150 0 [409703 0]}" subsys=datapath-sockets
2024-03-28T16:48:18.590690933Z level=info msg="socket {49778 5353 192.168.199.228 10.111.0.150 0 [409691 0]}" subsys=datapath-sockets
2024-03-28T16:48:18.590693558Z level=debug msg="Destroyed socket: {49778 5353 192.168.199.228 10.111.0.150 0 [409691 0]}" subsys=datapath-sockets
2024-03-28T16:48:18.590697235Z level=info msg="Forcefully terminated sockets" errors="<nil>" failed=0 filter="{10.111.0.150 5353 2 17 0x2ad0ae0}" subsys=datapath-sockets success=3
```

**Comment by aditighag** [comment]
>ingress-nginx uses a long-lived udp session for DNS. If we exec into the pod, we will see sessions to the ip address of the node-local-dns pod, that is running on the same node.

Is ingress-nginx pod deployed in the `hostNetwork`, or as a regular pod?

**Comment by aditighag** [comment]
Hi @AndreyPavlovFlant Can you test this fix - https://github.com/cilium/cilium/actions/runs/8745939939/job/24002052985?pr=32074?

**Comment by aditighag** [comment]
Hi @AndreyPavlovFlant Can you give test out this fix - https://github.com/cilium/cilium/actions/runs/8759676157/job/24043493605?pr=32074?

**Comment by AndreyPavlovFlant** [comment]
Hi! This is great news!

> Is ingress-nginx pod deployed in the hostNetwork, or as a regular pod?

Yes, ingress-nginx pod has been deployed in the host-network.

At the beginning of next week, I will be able to run tests based on the image from the link above.

**Comment by AndreyPavlovFlant** [comment]
Hi
I have checked the fix and everything seems to be working fine. 
The corresponding stale sockets have been successfully deleted from the node, and in the logs, I see messages such as:
```
2024-05-02T13:49:41.197133063Z time="2024-05-02T13:49:41Z" level=debug msg="Deleting service" backends="[10.111.0.148:53]" serviceID=38 serviceIP="{10.222.0.10 {UDP 53} 0}" subsys=service
2024-05-02T13:49:41.198595680Z time="2024-05-02T13:49:41Z" level=debug msg="Deleting obsolete backend" backendID=62 backends="[10.111.0.148:53]" serviceID=38 serviceIP="{10.222.0.10 {UDP 53} 0}" subsys=service
2024-05-02T13:49:41.199147143Z time="2024-05-02T13:49:41Z" level=debug msg="handling udp connections to deleted backend 10.111.0.148:53" subsys=service
2024-05-02T13:49:41.199339027Z time="2024-05-02T13:49:41Z" level=info msg="socket {45262 53 10.111.0.182 10.111.0.148 0 [48487 0]}" subsys=datapath-sockets
2024-05-02T13:49:41.199420841Z time="2024-05-02T13:49:41Z" level=debug msg="Destroyed socket: {45262 53 10.111.0.182 10.111.0.148 0 [48487 0]}" subsys=datapath-sockets
2024-05-02T13:49:41.199427714Z time="2024-05-02T13:49:41Z" level=info msg="socket {61728 53 10.111.0.182 10.111.0.148 0 [48618 0]}" subsys=datapath-sockets
2024-05-02T13:49:41.199473140Z time="2024-05-02T13:49:41Z" level=debug msg="Destroyed socket: {61728 53 10.111.0.182 10.111.0.148 0 [48618 0]}" subsys=datapath-sockets
2024-05-02T13:49:41.199478370Z time="2024-05-02T13:49:41Z" level=info msg="socket {33623 53 10.111.0.182 10.111.0.148 0 [48570 0]}" subsys=datapath-sockets
2024-05-02T13:49:41.199638273Z time="2024-05-02T13:49:41Z" level=debug msg="Destroyed socket: {33623 53 10.111.0.182 10.111.0.148 0 [48570 0]}" subsys=datapath-sockets
2024-05-02T13:49:41.199649023Z time="2024-05-02T13:49:41Z" level=info msg="socket {46965 53 10.111.0.182 10.111.0.148 0 [58110 0]}" subsys=datapath-sockets
2024-05-02T13:49:41.199652059Z time="2024-05-02T13:49:41Z" level=debug msg="Destroyed socket: {46965 53 10.111.0.182 10.111.0.148 0 [58110 0]}" subsys=datapath-sockets
```

**Comment by aditighag** [comment]
> I have checked the fix and everything seems to be working fine.
> The corresponding stale sockets have been successfully deleted from the node, and in the logs, I see messages such as:

Great! Thanks for testing. What's your Github email so that I can attribute the credit for reporting and testing in the PR commit?

**Comment by AndreyPavlovFlant** [comment]
My github email is andrey.pavlov@flant.com.
