### ISSUE TITLE
VTEP traffic is dropped when cluster is configured in VXLAN tunnel mode.

### ISSUE THREAD

**Issue by jhaprins** [cilium/cilium#31023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have configured my K8S cluster with Cilium as CNI. Cilium is installed with the following command:
````/oem/bin/cilium install --version=v1.15.1 \
                        --set tunnel=vxlan \
                        --set etcd.clusterDomain="cluster01.domain" \
                        --set hubble.peerService.clusterDomain="cluster01.domain" \
                        --set ipam.mode="kubernetes" \
                        --set hubble.relay.enabled=true \
                        --set hubble.ui.enabled=true \
                        --set encryption.enabled=true \
                        --set encryption.type=wireguard \
                        --set gatewayAPI.enabled=true \
````

This config works fine and traffic is tunneled between pods fully encrypted. 
When testing the new VTEP options introduced in version 1.15 I modified the install to the following command:

````/oem/bin/cilium install --version=v1.15.1 \
                        --set tunnel=vxlan \
                        --set etcd.clusterDomain="cluster01.domain" \
                        --set hubble.peerService.clusterDomain="cluster01.domain" \
                        --set ipam.mode="kubernetes" \
                        --set hubble.relay.enabled=true \
                        --set hubble.ui.enabled=true \
                        --set encryption.enabled=false \
                        --set encryption.type=wireguard \
                        --set gatewayAPI.enabled=true \
                        --set vtep.enabled=true \
                        --set vtep.endpoint="172.30.19.30" \
                        --set vtep.cidr="10.125.1.0/24" \
                        --set vtep.mask="255.255.255.0" \
                        --set vtep.mac="ba:53:5b:a2:5b:cb"
````

With this configured I expected to be able to ping from my VTEP node to a pod within the cluster. This didn't work though at all, even though I did receive arp responses. Tracing into the Cilium pod on the worker node running the pod I was trying to ping I noticed the following messages:

Feb 28 09:31:50.732: 10.125.1.1 (world) <> default/busybox2 (ID:58041) Incorrect VNI from VTEP DROPPED (ICMPv4 EchoRequest)
Feb 28 09:31:51.766: 10.125.1.1 (world) <> default/busybox2 (ID:58041) Incorrect VNI from VTEP DROPPED (ICMPv4 EchoRequest)
Feb 28 09:31:52.790: 10.125.1.1 (world) <> default/busybox2 (ID:58041) Incorrect VNI from VTEP DROPPED (ICMPv4 EchoRequest)

Looking into the packets on the network I noticed the following:
- Packets from the VTEP are in VNI 2, which is correct according to the documentation.
- Packets within the cluster between pods are all in VNI 4, even though the documentation states that different kinds of traffic should be in different VNI's for different kinds of traffic. [Reference](https://docs.cilium.io/en/stable/gettingstarted/terminology/#reserved-labels)

### Cilium Version

1.15.1

### Kernel Version

6.1.73-flatcar

### Kubernetes Version

# kubectl version
Client Version: v1.28.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6

### Regression

Probably not, this is probably a bug in the new introduced functionality, but might also be related to other things / maybe bugs in the whole VXLAN tunneling (different VNI's for different kinds of traffic?)

### Sysdump

[cilium-sysdump-20240228-095755.zip](https://github.com/cilium/cilium/files/14431992/cilium-sysdump-20240228-095755.zip)

### Relevant log output

```shell
Feb 28 09:31:50.732: 10.125.1.1 (world) <> default/busybox2 (ID:58041) Incorrect VNI from VTEP DROPPED (ICMPv4 EchoRequest)
Feb 28 09:31:51.766: 10.125.1.1 (world) <> default/busybox2 (ID:58041) Incorrect VNI from VTEP DROPPED (ICMPv4 EchoRequest)
Feb 28 09:31:52.790: 10.125.1.1 (world) <> default/busybox2 (ID:58041) Incorrect VNI from VTEP DROPPED (ICMPv4 EchoRequest)
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
It looks to me like https://github.com/cilium/cilium/pull/22625 broke the VTEP feature:

```
@@ -345,7 +349,7 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
                        if (!vtep)
                                goto skip_vtep;
                        if (vtep->tunnel_endpoint) {
-                               if (*identity != WORLD_ID)
+                               if (identity_is_world_ipv4(*identity))
                                        return DROP_INVALID_VNI;
                        }
                }
```

You could try applying this patch and see if it fixes the issue:

```
index 9add857e85ad..ec1c295f667b 100644
--- a/bpf/bpf_overlay.c
+++ b/bpf/bpf_overlay.c
@@ -342,7 +342,7 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
                        if (!vtep)
                                goto skip_vtep;
                        if (vtep->tunnel_endpoint) {
-                               if (identity_is_world_ipv4(*identity))
+                               if (!identity_is_world_ipv4(*identity))
                                        return DROP_INVALID_VNI;
                        }
                }
```

cc @vincentmli looks like the lack of VTEP testsuite coverage makes this pretty brittle.

**Comment by vincentmli** [comment]
@joestringer sorry I have not followed cilium development for a long while and not familiar with cilium testsuite when I contributed the VTEP feature, I am not sure if I have time to look into it in near future.

**Comment by vincentmli** [comment]
@joestringer here to confirm  PR #31039   fixes the issue
