### ISSUE TITLE
Improve performance of FQDN proxy

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#31032]
We are working with @squeed together on improving the performance of the FQDN proxy.

This issue is meant to be a placeholder to link related improvements in PRs to easily keep track of all of them and compare before/after results.

**Comment by squeed** [comment]
Some more relevant PRs:
https://github.com/cilium/cilium/pull/32049, which saves some wasted logging time
https://github.com/cilium/cilium/pull/30897, which significantly reduces memory usage
https://github.com/cilium/cilium/pull/32769, which is a **huge** reduction in resources for S3-style names

We might be able to close tnis.

**Comment by marseel** [comment]
Yes, let's close this. Thanks for all the contributions :heart:
