### ISSUE TITLE
Cilium proxy visibility annotations don't work in Cilium 1.15.x or later

### ISSUE THREAD

**Issue by kahirokunn** [cilium/cilium#31063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've annotated the pod with `io.cilium.proxy-visibility: <Egress/53/UDP/DNS>`, yet there are flows getting mixed in that do not become `->DNS`. Consequently, some of the flows to Github are showing as 'world'.

![CleanShot 2024-02-29 at 23 11 39@2x](https://github.com/cilium/cilium/assets/22343391/7107f41a-24d5-4d87-b7b3-1f1f2d3aa415)
![CleanShot 2024-02-29 at 23 12 50@2x](https://github.com/cilium/cilium/assets/22343391/9a421823-1167-4555-84c8-09842c7134c2)

### Cilium Version

Client: 1.15.1 a368c8f0 2024-02-14T22:16:57+00:00 go version go1.21.6 linux/arm64
Daemon: 1.15.1 a368c8f0 2024-02-14T22:16:57+00:00 go version go1.21.6 linux/arm64

### Kernel Version

Linux ip-10-0-67-27.ap-northeast-1.compute.internal 6.1.77 #1 SMP Fri Feb 23 02:34:40 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Server Version: v1.29.0-eks-c417bb3

### Regression

There is not a single flow with "world" and all DNS records can be referenced.

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi, according to https://docs.cilium.io/en/v1.15/operations/upgrade/#upgrade-notes the proxy visibility annotations are no longer supported as of v1.15.x or later. The new docs for this functionality suggest alternative ways to configure this:

https://docs.cilium.io/en/v1.15/observability/visibility/#proxy-visibility

**Comment by kahirokunn** [comment]
Thx 🙏
