### ISSUE TITLE
CI: update tests to use BeforeAll / AfterAll constructs

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3109]
#3059 adds functionality to run certain functionality "before all" and "after all" [It blocks](https://onsi.github.io/ginkgo/#individual-specs-it) for the [Describe or Context](https://onsi.github.io/ginkgo/#organizing-specs-with-containers-describe-and-context) that the It belongs to. Currently, #3059 only migrated over the runtime tests for the Cilium monitor to use these new constructs. Migrate over all tests to use these constructs. We should do this after the changes merged by #3059 have proven to be stable.

TODO: add list of tests that need to be migrated over to using this.

**Comment by eloycoto** [comment]
Duplicate of https://github.com/cilium/cilium/issues/2119

**Comment by ianvernon** [comment]
We use `BeforeAll` and `AfterAll` heavily in the CI now, closing.
