### ISSUE TITLE
CI: Conformance IPsec E2E: no-ipsec-xfrm-errors: xfrm errors were changed - inbound_no_state

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#31090]
## CI failure

```
[=] Test [no-ipsec-xfrm-errors] [2/70]

  [-] Scenario [no-ipsec-xfrm-errors/no-ipsec-xfrm-error]
  🟥 Node 172.18.0.3 xfrm errors were changed (previous errors: , current errors: inbound_no_state:1)
```

- Only observed on v1.13 so far
- PR: #30965
- [Occurrence 1](https://github.com/cilium/cilium/actions/runs/8048184254/job/22150142249) (kernel 5.10) - [raw logs](https://github.com/cilium/cilium/files/14461053/job-logs.txt)
- [Occurrence 2](https://github.com/cilium/cilium/actions/runs/8048184254/job/22152905472) (kernel 6.6) - [raw logs](https://github.com/cilium/cilium/files/14461055/job-logs2.txt)
- No sysdump available for either job :cry: 

Past issues with similar symptoms:
- #27276 (August 2023)
- #27609 (August 2023)
- #28483 (October 2023)

**Comment by chancez** [comment]
Sysdump from my PR #31070  is in this slack thread: https://cilium.slack.com/archives/C7PE7V806/p1711568393213069?thread_ts=1711497007.948769&cid=C7PE7V806. It's 40MB so it's too big to add to the issue/comment.

**Comment by pchaigno** [comment]
Above is actually happening in the upgrade test, where such errors are expected (in a limited number, as is the case here). After checking the branch, it seems that occurrence was caused by https://github.com/cilium/cilium/issues/15474.
