### ISSUE TITLE
HostPort is not enabled while using partial kube-Proxy replacement

### ISSUE THREAD

**Issue by dnayar9** [cilium/cilium#31168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have manually installed cilium on a AKS cluster. According to https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kube-proxy-hybrid-modes, I can enable hostPort feature in cilium without using a strict kube-proxy replacement. 

command used to install cilium: 
```
helm install cilium cilium/cilium --version 1.14.6   --namespace kube-system   --set aksbyocni.enabled=true   --set nodeinit.enabled=true  --set kubeProxyReplacement=false --set hostPort.enabled=true
```

Cilium status output (HostPort stays disabled)- 
```
KubeProxyReplacement Details:
  Status:                 False
  Socket LB:              Disabled
  Socket LB Tracing:      Disabled
  Socket LB Coverage:     Full
  Devices:                eth0  (Direct Routing)
  Session Affinity:       Disabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Disabled 
  - LoadBalancer:   Disabled 
  - externalIPs:    Disabled 
  - HostPort:       Disabled
```

However, If I set another property, like nodePort while installing cilium, HostPort is also enabled along with nodePort. 

Command used to install cilium:
```
 helm install cilium cilium/cilium --version 1.14.6   --namespace kube-system   --set aksbyocni.enabled=true   --set nodeinit.enabled=true  --set kubeProxyReplacement=false --set hostPort.enabled=true  --set nodePort.enabled=true
```

Cilium status output - 
```
KubeProxyReplacement Details:
  Status:                 False
  Socket LB:              Disabled
  Socket LB Tracing:      Disabled
  Socket LB Coverage:     Full
  Devices:                eth0 192.168.34.7 (Direct Routing)
  Mode:                   SNAT
  Backend Selection:      Random
  Session Affinity:       Disabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  XDP Acceleration:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Disabled 
  - HostPort:       Enabled
```

Cilium is unable to only enable HostPort feature on its own. 

### Cilium Version

1.14.6

### Kernel Version

Aks Node
OS-image - Ubuntu 20.04.6 LTS
Kernel Version - 5.4.0-1121-azure-fips

### Kubernetes Version

1.28.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi, thanks for the report. I can confirm that with the first Helm command above, the Cilium configuration in the ConfigMap enables hostport (and not nodeport), and that if you install/run Cilium, it receives this configuration, but then the `cilium status` reflects that the hostport feature is not enabled. This seems like a bug.

For now I think the workaround is to either use portmap CNI for hostport, or enable more of Cilium's kube-proxy replacement feature. The vast majority of users will either commit to kube-proxy + portmap or only Cilium to implement services, so you will have the highest chance of success if you follow one of these two patterns.

**Comment by dnayar9** [comment]
@joestringer Thanks for a quick response. We are using cni chaining portmap as a workaround, but would like to have hostPort enabled directly. Any timeline on when it will be fixed? Thanks!

**Comment by joestringer** [comment]
The Cilium project relies on contributions from volunteers in the community. I can't give you any timeline on proposals from volunteers. You're welcome to investigate the issue and make proposals about how to fix the issue either here or by filing a PR with a concrete implementation.
