### ISSUE TITLE
FIXME: Many policy tests using disallowed configurations.

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#31162]
I added a small change to the PolicyRepository to ensure that all rules had passed a `.Sanitize()` before adding. To my surprise, it failed! Fortunately, only for testing code.

When I tried to fix this, I discovered that a number of unit tests are using policy constructs that are explicitly disallowed. Bummer. We need to fix this.

Tasks:

1. Temporarily require rules to be sanitized before adding to the PolicyRepository. This would be in `addListLocked()`. Since this method cannot fail, it will have to `panic()`, but that's OK for testing purposes.
3. Run all unit and integration tests
4. Fix all errors :grimacing:

**Comment by joestringer** [comment]
How would someone get started on helping with this? Do you have a link to the changes you made to identify these tests?
