### ISSUE TITLE
Conformance E2E: Found unexpected packet drops: Forbidden ICMPv6 message

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#31175]
Workflow: https://github.com/cilium/cilium/actions/runs/8155692574/job/22291744769.
```
[=] Test [no-unexpected-packet-drops] [1/70]

  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
  🟥 Found unexpected packet drops:
{
  "labels": {
    "direction": "INGRESS",
    "reason": "Forbidden ICMPv6 message"
  },
  "name": "cilium_drop_count_total",
  "value": 1
}
```
Happened with the following combination of options:
```
- name: '6'
  # renovate: datasource=docker depName=quay.io/lvh-images/kind
  kernel: '6.1-20240215.093821'
  kube-proxy: 'none'
  kpr: 'true'
  devices: '{eth0,eth1}'
  tunnel: 'vxlan'
  lb-mode: 'snat'
  egress-gateway: 'true'
  host-fw: 'true'
  lb-acceleration: 'testing-only'
  ingress-controller: 'true'
```

**Comment by giorio94** [comment]
A few days ago I opened https://github.com/cilium/cilium-cli/pull/2317 to add it to the list of expected drop reasons. The TL;DR; is that it can legitimately happen when host firewall is enabled (that's the only configuration in which Cilium emits that error message).

**Comment by giorio94** [comment]
Closing because the Cilium CLI version got bumped in https://github.com/cilium/cilium/pull/31171.
