### ISSUE TITLE
CI: Test/TunnelMapTestSuite/TestClusterAwareAddressing 

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#31232]
## CI failure

```
--- FAIL: Test (0.00s)
    --- FAIL: Test/TunnelMapTestSuite (0.00s)
        --- FAIL: Test/TunnelMapTestSuite/TestClusterAwareAddressing (0.00s)
            tunnel_test.go:37: 
                ... value *fmt.wrapError = &fmt.wrapError{msg:"creating map: pin map to /sys/fs/bpf/tc/globals/test_cilium_tunnel_map: file exists", err:(*fmt.wrapError)(0xc0000563c0)} ("creating map: pin map to /sys/fs/bpf/tc/globals/test_cilium_tunnel_map: file exists")
```

Run URL: https://github.com/cilium/cilium/actions/runs/8193113970/job/22406307012
PR: https://github.com/cilium/cilium/pull/31015
Zip: Sysdump n/a.

**Comment by tommyp1ckles** [comment]
@learnitall Was investigating this one, was going to put up this [fix](https://github.com/tommyp1ckles/cilium/blob/ac53bd7af1235b5abcae20eb93e7f7707075b706/pkg/maps/tunnel/tunnel.go), but I noticed you had a similar one as a draft, where you planning on opening that one up for review?

**Comment by learnitall** [comment]
Yep! I was making sure CI was passing on it, but I hit more flakes anyways. I just opened it up for review.

Looks like we did the [exact same fix](https://github.com/cilium/cilium/pull/31233/commits/32666a2863fc01190999d229b22a37c78eebce70) :)
