### ISSUE TITLE
L2 Announcements missing Role Permision

### ISSUE THREAD

**Issue by dalcorta** [cilium/cilium#31240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed cilium in a new dev cluster using kubeadm.  I based it on the following doc the cluster creation, [Cilium kube-proxy-free Doc](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/). After that I changed from legacy to ebpf using the cilum cli.  Then I added the load balancer CR and the L2AnnouncementPolicy. Later I used this doc [Cilium L2 Announcement doc](https://docs.cilium.io/en/latest/network/l2-announcements/) with the L2 Pod to finish configuring it.

I checked cilium logs and Role was missing all these permision

 ```
- verbs:
   - get
   - create
   - update
   apiGroups:
   - coordination.k8s.io
   resources:
   - leases
```

### Cilium Version

1.15.1

### Kernel Version

Linux cnv-svmi-ctrlp01 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7

### Sysdump

[Uploading cilium-sysdump-20240307-210254.zip…]()

### Relevant log output

```shell
error retrieving resource lock kube-system/cilium-l2announce-default-nginx: leases.coordination.k8s.io "cilium-l2announce-default-nginx" is forbidden: User "system:serviceaccount:kube-system:cilium" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @dalcorta, thanks for the report. Unfortunately the sysdump is truncated, can you re-upload that? Also, where does the "relevant log output" come from? Is that from cilium-agent, cilium-operator, another component?

Glancing at the way that the Helm charts check for the `l2announcements.enabled` setting, the relevant permissions should be granted if that option is specified. Can you share the exact commands you initially used to install and later used to upgrade Cilium? This will help others to reproduce the exact behaviour you found.

**Comment by dalcorta** [comment]
@joestringer  Hi the log is from cilium pod. I used clilium cli, not helm.  What I did first was create a cluster kube-proxy free using kubeadm as specified in the doc. I always used cilium cli to add new parameters ( cilium config set <parameters> ).

**Comment by joestringer** [comment]
@dalcorta I see. Could you be more specific about the exact commands you used? On the page that you referenced, I can see multiple commands which all directly use Helm. If you are configuring the L2 announcements feature only with the cilium CLI then it will be important for anyone to understand/reproduce the issue if they can tell exactly how you are configuring the feature.

**Comment by dalcorta** [comment]
kubeadm init --skip-phases=addon/kube-proxy --pod-network-cidr=10.244.0.0/16 --upload-certs --control-plane-endpoint=<VIP>:6443
Added 2 control plane nodes and 1 worker nodes
cilium install --version 1.15.1 --namespace kube-system --set kubeProxyReplacement=true \
    --set k8sServiceHost=<VIP> \
    --set k8sServicePort=6443
cilium config set enable-bpf-masquerade true
cilium config set enable-l2-announcements true
cilium config set l2-pod-announcements-interface ens33

**Comment by dalcorta** [comment]
Client config ended up like this

```
agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: 'false'
  bpf-lb-acceleration: disabled
  bpf-lb-external-clusterip: 'false'
  bpf-lb-map-max: '65536'
  bpf-lb-sock: 'false'
  bpf-lb-sock-hostns-only: 'true'
  bpf-map-dynamic-size-ratio: '0.0025'
  bpf-policy-map-max: '16384'
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: '0'
  cluster-name: default
  cluster-pool-ipv4-cidr: 10.0.0.0/8
  cluster-pool-ipv4-mask-size: '24'
  cni-exclusive: 'true'
  cni-log-file: /var/run/cilium/cilium-cni.log
  custom-cni-conf: 'false'
  debug: 'false'
  debug-verbose: ''
  dnsproxy-enable-transparent-mode: 'true'
  egress-gateway-reconciliation-trigger-interval: 1s
  enable-auto-protect-node-port-range: 'true'
  enable-bgp-control-plane: 'false'
  enable-bpf-clock-probe: 'false'
  enable-bpf-masquerade: 'true'
  enable-endpoint-health-checking: 'true'
  enable-health-check-loadbalancer-ip: 'false'
  enable-health-check-nodeport: 'true'
  enable-health-checking: 'true'
  enable-hubble: 'true'
  enable-ipv4: 'true'
  enable-ipv4-big-tcp: 'false'
  enable-ipv4-masquerade: 'true'
  enable-ipv6: 'false'
  enable-ipv6-big-tcp: 'false'
  enable-ipv6-masquerade: 'true'
  enable-k8s-networkpolicy: 'true'
  enable-k8s-terminating-endpoint: 'true'
  enable-l2-announcements: 'true'
  enable-l2-neigh-discovery: 'true'
  enable-l2-pod-announcements: 'true'
  enable-l7-proxy: 'true'
  enable-local-redirect-policy: 'false'
  enable-masquerade-to-route-source: 'false'
  enable-metrics: 'true'
  enable-policy: default
  enable-remote-node-identity: 'true'
  enable-sctp: 'false'
  enable-svc-source-range-check: 'true'
  enable-vtep: 'false'
  enable-well-known-identities: 'false'
  enable-xt-socket-fallback: 'true'
  external-envoy-proxy: 'false'
  hubble-disable-tls: 'false'
  hubble-export-file-max-backups: '5'
  hubble-export-file-max-size-mb: '10'
  hubble-listen-address: ':4244'
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  identity-gc-interval: 15m0s
  identity-heartbeat-timeout: 30m0s
  install-no-conntrack-iptables-rules: 'false'
  ipam: cluster-pool
  ipam-cilium-node-update-rate: 15s
  k8s-client-burst: '20'
  k8s-client-qps: '10'
  kube-proxy-replacement: strict
  kube-proxy-replacement-healthz-bind-address: ''
  l2-pod-announcements-interface: ens33
  max-connected-clusters: '255'
  mesh-auth-enabled: 'true'
  mesh-auth-gc-interval: 5m0s
  mesh-auth-queue-size: '1024'
  mesh-auth-rotated-identities-queue-size: '1024'
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: 'true'
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: ':9963'
  policy-cidr-match-mode: ''
  preallocate-bpf-maps: 'false'
  procfs: /host/proc
  proxy-connect-timeout: '2'
  proxy-max-connection-duration-seconds: '0'
  proxy-max-requests-per-connection: '0'
  proxy-prometheus-port: '9964'
  remove-cilium-node-taints: 'true'
  routing-mode: tunnel
  service-no-backend-response: reject
  set-cilium-is-up-condition: 'true'
  set-cilium-node-taints: 'true'
  sidecar-istio-proxy-image: cilium/istio_proxy
  skip-cnp-status-startup-clean: 'false'
  synchronize-k8s-nodes: 'true'
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: 'true'
  tofqdns-endpoint-max-ip-per-hostname: '50'
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: '10000'
  tofqdns-proxy-response-max-delay: 100ms
  tunnel-protocol: vxlan
  unmanaged-pod-watcher-interval: '15'
  vtep-cidr: ''
  vtep-endpoint: ''
  vtep-mac: ''
  vtep-mask: ''
  write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conflist
```

**Comment by joestringer** [comment]
OK thanks. There is currently no way to solve this problem with `cilium config set`, because this only modifies the ConfigMap and not the other resources. If you follow [the guide](https://docs.cilium.io/en/latest/network/l2-announcements/) directly, those instructions should work.

I've filed https://github.com/cilium/cilium-cli/issues/2389 to follow up on whether there is a way to support this sort of reconfiguration with `cilium config set`, but for now you'll need to use the Helm options. Any install you've created with a recent version of the `cilium` CLI should be managed by Helm under the hood, so I would expect it to be possible to apply the changes directly using Helm.
