### ISSUE TITLE
Documentation: Incorrect brace expansion in curl command for Cilium CLI installation on macOS

### ISSUE THREAD

**Issue by sethstuart** [cilium/cilium#31257]
## Cilium Documentation Update

**Description:**
The [current installation instructions](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-the-cilium-cli) for the Cilium CLI on macOS contain a curl command that uses brace expansion to download both the tarball and its corresponding SHA256 checksum file. However, the brace expansion is not performed correctly due to the braces being enclosed within double quotes. This results in a malformed URL and a 404 error when attempting to download the files.

**Affected Command:**
`curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-darwin-${CLI_ARCH}.tar.gz{,.sha256sum}
`

**Issue:**
The brace expansion {,.sha256sum} is intended to download both the cilium-darwin-${CLI_ARCH}.tar.gz file and its checksum file cilium-darwin-${CLI_ARCH}.tar.gz.sha256sum. However, the expansion does not occur because the braces are inside the double quotes, which prevents the shell from interpreting them as intended.

**Expected Behavior:**
The curl command should download both the tarball and the SHA256 checksum file.

**Actual Behavior:**
The curl command fails with a 404 error because the URL is malformed due to the incorrect brace expansion.

**Solution:**
Move the braces outside of the double quotes to allow the shell to perform the brace expansion correctly.

**Impact:**
Users following the current installation instructions on macOS will encounter a 404 error and will be unable to download the Cilium CLI and its checksum file. This issue affects the usability and accessibility of the installation process.

**Comment by joestringer** [comment]
Thanks for the report and the fix @sethstuart !
