### ISSUE TITLE
CFP: Add support for SupportGatewayPort8080 in Gateway API

### ISSUE THREAD

**Issue by sayboras** [cilium/cilium#31279]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

Cilium implementation for Gateway API should support having user-defined port number apart from 80 and 443.

**Describe the feature you'd like**

Cilium implementation for Gateway API should support having user-defined port number apart from 80 and 443.

**(Optional) Describe your proposed solution**

List of proposed tasks for this feature:

- [ ] Update translation logic to use listener-<port-number> instead of listener-{insecure,secure]
   - https://github.com/cilium/cilium/blob/a0528696705fee551c941784467d5b6dd20482c6/operator/pkg/model/translation/cec_translator.go#L250
- [x] Enable the tests in Gateway Conformance test
   - https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-gateway-api.yaml#L118
- [x] Check if there is any change in Ingress

**Comment by chaunceyjiang** [comment]
Hi @sayboras Can this issue be assigned to me? I want to implement this feature.

**Comment by sayboras** [comment]
Thanks for your interest, just a head up that this might get tricky with Ingress features. Basically, Ingress only supports port 80 and 443, and there is no clean definition if only https should be allowed.

Feel free to give it a try, and let us know if you have any questions/concerns.

**Comment by sayboras** [comment]
>  Is SupportGatewayPort8080 an official feature of the gateway-api?

I believed so, there is no official document, however, you can see the port attribute in listener spec. I normally check the conformance manifests to understand test cases and expected behavior

https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/gateway-with-attached-routes-with-port-8080.yaml

**Comment by joestringer** [comment]
Hi @sayboras, I see this is marked as a release blocker but there does not appear to be recent activity towards resolving the issue. Is this still being investigated, and does it still have high impact? If yes, we may want to figure out how to draw more attention to the issue. If not, we should remove the release-blocker label.

**Comment by sayboras** [comment]
Thanks for the ping, I have removed the release blocker label.

**Comment by sayboras** [comment]
This is completed as part of recent changes to support GAMMA, thanks to Nick.

Related PR: https://github.com/cilium/cilium/pull/32744
