### ISSUE TITLE
Migrating from calico to cilium

### ISSUE THREAD

**Issue by genseb13011** [cilium/cilium#31273]
Hi,

I'm trying to migrate from calico to cilium (with no down time).

I'm following this official guide [](https://docs.cilium.io/en/latest/installation/k8s-install-migration/) but few time after running the cilium installation command at step 5 (helm install cilium cilium/cilium --namespace kube-system --values values-initial.yaml) my calico node pods switch to not-ready state and I start facing network issues.

![Capture d’écran du 2024-03-10 14-08-27](https://github.com/cilium/cilium/assets/49025491/1af1adaa-2441-46e3-a78f-d52e3da1fc49)

- My calico is in ip-in-ip configuration and CIDR 10.0.0.0/16
- My cilium configuration CIDR is 10.1.0.0/16, VXLAN on default port 4789 (also tried with 8473)
- My values-migration.yaml content is

**operator:
  unmanagedPodWatcher:
    restart: false # Migration: Don't restart unmigrated pods
routingMode: tunnel # default value
tunnelProtocol: vxlan # default value
tunnelPort: 4789 # Default value is 8472 but the official standard IANA value is 4789
cni:
  customConf: true # Migration: Don't install a CNI configuration file
  uninstall: false # Migration: Don't remove CNI configuration on shutdown
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.1.0.0/16"] # Migration: Ensure this is distinct and unused
policyEnforcementMode: "never" # Migration: Disable policy enforcement
bpf:
  hostLegacyRouting: true # Migration: Allow for routing between Cilium and the existing overlay**

- My values-initial.yaml content is:

**bpf:
  hostLegacyRouting: true
cluster:
  name: kubernetes
cni:
  customConf: true
  uninstall: false
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
    - 10.1.0.0/16
operator:
  replicas: 1
  unmanagedPodWatcher:
    restart: false
policyEnforcementMode: never
routingMode: tunnel
tunnelPort: 4789
tunnelProtocol: vxlan**

am I missing something?

I also notice that running **calicoctl node status** command returns public VPS IP in peer address

![calico](https://github.com/cilium/cilium/assets/49025491/760617d0-a22e-43fc-a503-b5ff50946693)

but once the cilium install command has run, calico peer address switch from public VPS IP to **_CILIUM_** CIDR IP

![cilium](https://github.com/cilium/cilium/assets/49025491/1f140973-dbdc-431d-bbfa-a6c7731acdcd)

Thanks for your help.

Seb.

**Comment by squeed** [comment]
@genseb13011 I'm not familiar with all of the details of Calico; are there any logs to indicate why it is no longer functionling?
