### ISSUE TITLE
BGP route not inject into kernel FIB 

### ISSUE THREAD

**Issue by Mia1112** [cilium/cilium#31283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

bgpControlPlane seems not able to inject received route into kernel FIB, been reject? how to see the bgp export filter?

### Cilium Version

Client: 1.13.4 4061cdfc 2023-06-14T03:37:39+00:00 go version go1.19.10 linux/amd64

### Kernel Version

Linux master 5.10.0-60.18.0.50

### Kubernetes Version

v1.25.3

### Anything else?

master node 76.3.95.27 with podcidr 172.16.0.0/24；node 76.3.95.28 with podcidr 172.16.1.0/24

```
[root@master hr]# kubectl exec -it cilium-d4zln -nkube-system -- cilium bgp peers
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Local AS   Peer AS   Peer Address   Session       Uptime      Family         Received   Advertised  
64512      64512     76.3.95.28     established   73h34m19s   ipv4/unicast   1          1    
                                                              ipv6/unicast   0          0
```

BGP session established, tcpdump catched correct UPDATE Message.
![image](https://github.com/cilium/cilium/assets/27919123/66c22fee-9352-400c-adfa-9ec6b5745873)

but master node FIB don't have any route about 172.16.1.0/24

```
[root@master hr]# ip route
default via 76.3.95.1 dev eth0 
76.3.95.0/24 dev eth0 proto kernel scope link src 76.3.95.27 
172.16.0.0/24 via 172.16.0.94 dev cilium_host src 172.16.0.94 
172.16.0.94 dev cilium_host scope link
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
That is correct, Cilium doesn't inject received routes into the kernels FIB, so this isn't a bug.
