### ISSUE TITLE
CI: Cilium E2E Upgrade - unexpected packet drops due to missed tail calls

### ISSUE THREAD

**Issue by aspsk** [cilium/cilium#31317]
## CI failure

(This is similar to https://github.com/cilium/cilium/issues/29987 but happens on `INGRESS`)

* Link: https://github.com/cilium/cilium/actions/runs/8231678586/job/22507511430
* Sysdump: [cilium-sysdump-14-20240311-110903.zip](https://github.com/cilium/cilium/files/14562271/cilium-sysdump-14-20240311-110903.zip)

```
[=] Test [no-unexpected-packet-drops] [3/77]
.
  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/kind-kind/kind-worker2]
  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "INGRESS",
    "reason": "Missed tail call"
  },
  "name": "cilium_drop_count_total",
  "value": 1
}
```

**Comment by tommyp1ckles** [comment]
Found instance here: https://github.com/cilium/cilium/actions/runs/8373615571/job/22927054911

**Comment by davem-git** [comment]
I get this error on existing clusters. the test is newer. It's consistent on most of my clusters, they all fail this way.

I noticed it first after an upgrade. Then I ran it on existing clusters with the same issue.
```sh

  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
  🟥 Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "Missed tail call"
  },
  "name": "cilium_drop_count_total",
  "value": 5
}
```

**Comment by christarazi** [comment]
Seen in https://github.com/cilium/cilium/actions/runs/9979634838/job/27579362694
