### ISSUE TITLE
peer closed connection in SSL handshake

### ISSUE THREAD

**Issue by jieshiyeskey** [cilium/cilium#31330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

``` 
# kubectl get ing
NAME             CLASS    HOSTS                     ADDRESS        PORTS     AGE
myapp3-ingress   cilium   myapp3.tainengchong.com   172.16.0.203   80, 443   5s
```
```
# cat /etc/hosts |grep myapp3
172.16.0.203 myapp3.tainengchong.com
```
```
# curl https://myapp3.tainengchong.com
Hello MyApp | Version: v3 | <a href="hostname.html">Pod Name</a>
```
# All of the above are in line with expectations.
## However, when using NGINX proxy, the following error is reported:
```
2024/03/11 19:29:10 [error] 739770#739770: *1 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 114.253.241.201, server: myapp3.tainengchong.com, request: "GET / HTTP/2.0", upstream: "https://172.16.0.203:443/", host: "myapp3.tainengchong.com"
2024/03/11 19:29:10 [error] 739770#739770: *1 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 114.253.241.201, server: myapp3.tainengchong.com, request: "GET /favicon.ico HTTP/2.0", upstream: "https://172.16.0.203:443/favicon.ico", host: "myapp3.tainengchong.com", referrer: "https://myapp3.tainengchong.com/"
```
## nginx conf:
```
### /srv/tengine/conf/sites-enabled/myapp3-system-ssl
server {
    listen 443 ssl http2;
    server_name myapp3.tainengchong.com;
    include pki/cnf/tainengchong.ssl;

    set $tag_srvtype 'myapp3-system-ssl';

    location / {
    proxy_pass                https://172.16.0.203;
    access_log /data/log/tengine/myapp3-system-ssl.log main;
   }
}
```
```
### /srv/tengine/conf/pki/cnf/tainengchong.ssl
ssl_stapling on;
ssl_stapling_verify on;
ssl_certificate pki/ca/tainengchong_com.crt;
ssl_certificate_key pki/ca/tainengchong_com.key;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers HIGH:!aNULL:!MD5;
ssl_session_cache shared:SSL:20m;
ssl_session_timeout 180m;
add_header Strict-Transport-Security "max-age=31536000";
```
# The certificates in Cilium are the same as those in NGINX
# Both Kubernetes Ingress and Cilium Gateway API  encountered this problem

### Cilium Version

cilium-cli:  compiled with go1.22.0 on linux/amd64
cilium image (default): v1.15.1
cilium image (stable): v1.15.1
cilium image (running): 1.15.1

### Kernel Version

Linux cn-cp-01 5.15.0-203.146.5.1.el9uek.x86_64 #2 SMP Thu Feb 8 17:13:58 PST 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
It sounds like packets might be getting dropped from your Nginx instance. Could you submit a sysdump made while this is going on. Or if not, check hubble flows yourself https://docs.cilium.io/en/latest/gettingstarted/hubble_setup/?
