### ISSUE TITLE
BGP GR not working

### ISSUE THREAD

**Issue by wenzt** [cilium/cilium#31346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. open gr in bgppeerpolicy
2. delete cilium-agent
3. node cidr not keeped in TOR

spec:
  nodeSelector:
    matchLabels:
      cilium-bgp-peer-address: 10.16.146.254
  virtualRouters:
    - exportPodCIDR: true
      localASN: 65535
      neighbors:
        - connectRetryTimeSeconds: 120
          eBGPMultihopTTL: 1
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
          holdTimeSeconds: 180
          keepAliveTimeSeconds: 60
          peerASN: 65534
          peerAddress: 10.16.146.254/32
          peerPort: 179

TOR debug log:
%Mar 12 20:45:14:312 2024 tor-name BGP/5/BGP_STATE_CHANGED: BGP.: 10.16.146.159  state has changed from ESTABLISHED to IDLE for a notification received: Cease/Peer De-configured.
%Mar 12 20:45:14:312 2024 tor-name BGP/5/BGP_STATE_CHANGED_REASON: BGP.: 10.16.146.159  state has changed from ESTABLISHED to IDLE. (Reason: a notification was received from the peer, error code: Receive Notificationcode 6/3, local interface: )
*Mar 12 20:45:14:313 2024 tor-name BGP/7/DEBUG: 
 BGP_TIMER.: 10.16.146.159  Timer Delay Delete Created.

%Mar 12 20:45:31:562 2024 tor-name BGP/5/BGP_STATE_CHANGED: BGP.: 10.16.146.156  state has changed from OPENCONFIRM to ESTABLISHED.
*Mar 12 20:45:31:563 2024 tor-name BGP/7/DEBUG: 
 BGP_GR.: Received EOR from Peer 10.16.146.156  (IPv4-UNC).

*Mar 12 20:45:32:352 2024 tor-name BGP/7/DEBUG: 
 BGP_GR.: Sent EOR to Peer 10.16.146.156  (IPv4-UNC).

%Mar 12 20:45:35:562 2024 tor-name BGP/5/BGP_STATE_CHANGED: BGP.: 10.16.146.159  state has changed from OPENCONFIRM to ESTABLISHED.
*Mar 12 20:45:35:564 2024 tor-name BGP/7/DEBUG: 
 BGP_GR.: Received EOR from Peer 10.16.146.159  (IPv4-UNC).

*Mar 12 20:45:36:353 2024 tor-name BGP/7/DEBUG: 
 BGP_GR.: Sent EOR to Peer 10.16.146.159  (IPv4-UNC).

### Cilium Version

1.14.5

### Kernel Version

4.19

### Kubernetes Version

1.21

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YutaroHayakawa** [comment]
I couldn't reproduce this with `1.14.5`. It seems like your peer is getting a BGP Notification, which is not normal; if you just delete Cilium Pod, then Cilium BGP Control Plane just shuts down the TCP connection without sending a notification. What's the actual command to do `delete cilium-agent`? Having a sysdump (you can get it with cilium-cli `cilium sysdump`) also helps.

**Comment by wenzt** [comment]
Thank you for reply !
I use `kubectl -n kube-system delete pod cilium-xxx ` to  trigger GR. 
If delete pod not working for GR.  How to update cilium agent without pod losing connect on node? 
I mean when I update cilium-agent daemonset, k8s is going to delete pod one by one right ?
I also notice https://github.com/cilium/cilium/pull/25660, dose F bit set  included in 1.14.5 ?

**Comment by YutaroHayakawa** [comment]
Deleting the Pod should trigger the graceful restart. Could you provide your sysdump and peer config, if possible? It's hard to say without seeing it.

**Comment by wenzt** [comment]
sysdump print many logs, which file should I provide.
I update to 1.15.1, GR work in first restart,  but cilium-agent running after restart,  TOR can nott recive route again.
BGP status is established:
![image](https://github.com/cilium/cilium/assets/18086416/0883dbc2-fe67-42db-9068-31d7d3ee73a8)
Other questions is after I enable graceful restart, the ipv4 Advertised changed 1 -> 2 ?

**Comment by wenzt** [comment]
https://github.com/cilium/cilium/issues/30367

**Comment by YutaroHayakawa** [comment]
So, upgrading to 1.15.2 solved all of your problems?

**Comment by wenzt** [comment]
Yes, Thanks.
One more questions: 
If I update ciliumbgppeeringpolicies.cilium.io object, bgp control plane will reactive and lose network connections.
Even graceful restart is enabled. So update bgppeer policy config will not trigger GR?

**Comment by YutaroHayakawa** [comment]
I don't think so. It depends on which field you modified, but in general, if you modify and it resets the connection, you change the parameter that needs BGP session renegotiation (for example, hold timer, graceful restart, etc).

**Comment by wenzt** [comment]
Yes，I changed hold timer. It make sense.
Thanks again !
