### ISSUE TITLE
Add metadata labels for `cilium policy selectors` to support visibility policy L7 allow-all

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#31359]
During the investigation that led to https://github.com/cilium/cilium/pull/31358, I discovered that we are missing one source for metadata labels for the `cilium policy selectors` command in the case of visibility policies, see https://github.com/cilium/cilium/blob/687e4f8f403aa75f3e1e42005db51b29fdd9e5ef/pkg/policy/visibility.go#L136.

We would need to figure out what we should pass as the metadata here. We don't have labels because the visibility policy is not a K8s resource, however the visibility policy comes from an annotation on a pod. Potentially some way to signal that this selector is coming from an annotation, along with the namespace/name of the pod could suffice.

Mostly a cosmetic issue, but nice to fix.

**Comment by ONE7live** [comment]
Hi, @christarazi I want to pick up this issue, can you please assign it to me?
