### ISSUE TITLE
how can cilium 1.14 support lower version k8s v1.12 ? and why not 

### ISSUE THREAD

**Issue by forsakening** [cilium/cilium#31360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

how can cilium 1.14 support lower version k8s v1.12 ? and why not 

### Cilium Version

v1.14

### Kernel Version

5.10

### Kubernetes Version

v1.12

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
We don't support such old k8s versions because we don't test against them in our CI. We tend to replace older k8s versions with newer versions as time goes on and older k8s versions become unsupported. (k8s 1.12 has been End-Of-Live for years now)
