### ISSUE TITLE
CFP: Local internalTrafficPolicy support for ClusterIP advertisements with BGP Control Plane

### ISSUE THREAD

**Issue by rastislavs** [cilium/cilium#31389]
## Cilium Feature Proposal

Add support for `.spec.internalTrafficPolicy: Local` in `ClusterIP` service advertisements with BGP Control Plane.

**Is your proposed feature related to a problem?**

In PR https://github.com/cilium/cilium/pull/30963 (issue https://github.com/cilium/cilium/issues/30875) we added support for `ClusterIP` service advertisements with BGP Control Plane.

At the moment, the ClusterIP service prefixes are advertised from each BGP-enabled cilium node.

As the `ClusterIP` services can have `.spec.internalTrafficPolicy` set to `Local`, advertising a ClusterIP from a node which has no local endpoints may cause unreachability of the advertised service if the traffic is routed to that node:

> For pods on nodes with no endpoints for a given Service, the Service behaves as if it has zero endpoints (for Pods on this node) even if the service does have endpoints on other nodes.

([source](https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/#using-service-internal-traffic-policy))

**Describe the feature you'd like**

If `.spec.internalTrafficPolicy` of a service is set to `Local`, advertise its `ClusterIP` over BGP only if it has non-zero local endpoints.

**(Optional) Describe your proposed solution**

BGP control plane already supports similar handling of `spec.externalTrafficPolicy: Local` for `LoadBalancer` services, so ideally the existing logic needs to be just extended to handle  `.spec.internalTrafficPolicy: Local` as well on few places in the service reconciler (e.g. in [svcDesiredRoutes handling](https://github.com/cilium/cilium/blob/4f4b0a7460ec759dc025c91df92f29aa7b64cce1/pkg/bgpv1/manager/reconciler/service.go#L298-L302)).

**Comment by rastislavs** [comment]
cc @YutaroHayakawa , @chaunceyjiang

**Comment by chaunceyjiang** [comment]
@rastislavs OK

Please assign to me.
