### ISSUE TITLE
CI: Conformance Runtime (ci-runtime): pkg/bgpv2/cluster_test.go

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#31400]
## CI failure

```
 --- FAIL: Test_Cleanup (5.05s)
    cluster_test.go:624: 
        	Error Trace:	/host/operator/pkg/bgpv2/cluster_test.go:631
        	            				/root/sdk/go1.22.1/src/runtime/asm_amd64.s:1695
        	Error:      	"[]" should have 2 item(s), but has 0
    cluster_test.go:624: 
        	Error Trace:	/host/operator/pkg/bgpv2/cluster_test.go:624
        	Error:      	Condition never satisfied
        	Test:       	Test_Cleanup
FAIL
coverage: 2.0% of statements
FAIL	github.com/cilium/cilium/operator/pkg/bgpv2	6.817s
```

https://github.com/cilium/cilium/actions/runs/8257092301/job/22596192676

**Comment by harsimran-pabla** [comment]
Hi @christarazi , wondering if this failure was after fix introduced in this [commit](https://github.com/cilium/cilium/commit/787858c16b2a071cb8db6e4a550f29b6bf1af88c)

**Comment by christarazi** [comment]
I think the failure was seen before that commit. After rebasing at some point, it passed, so I'll close this. 

Fixed by https://github.com/cilium/cilium/pull/31381.
