### ISSUE TITLE
Docs: Document process for determining correct MTU

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#31423]
When developing applications, users may use the MTU inside a pod to understand how to segment their packet payloads. This is especially relevant for UDP-based traffic which relies on IP fragmentation to split up payloads that are larger than the configured network's MTU. However, the process for determining the correct MTU to use depends on Cilium's configuration. For example, if Cilium is configured with tunneling mode the interface's MTU can be used, however when Cilium is configured via WireGuard, the route MTU must be used:

```
 printmtu-4  ~  ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
31: eth0@if32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue state UP group default qlen 1000
    link/ether 36:e9:a6:71:70:9e brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.124.1.134/32 scope global eth0
       valid_lft forever preferred_lft forever

 printmtu-4  ~  ip r
default via 10.124.1.60 dev eth0 mtu 1380 
10.124.1.60 dev eth0 scope link 
```

We should document the correct way to determine the MTU to use based on Cilium's configuration to make it easier for users.

**Comment by joestringer** [comment]
Cilium should auto-detect and apply the appropriate MTU on the routes inside the Pods already. The user can override globally the MTU they expect, and Cilium will propagate that value + adjust for tunnel overhead etc. If there's a particular scenario (eg particular combination of features) where some overhead is added to a range of packets and Cilium is not properly calculating/applying the MTU, that could be a bug.

Searching for "MTU" in the issues brings up some known issues like https://github.com/cilium/cilium/issues/22294 in that category.

There's also an extended discussion on the Cilium MTU model here: https://github.com/cilium/cilium/issues/14339, plus a dormant CFP here: https://docs.google.com/document/d/1GLYB5-DnQmz63AiqYHubRScE9xrzAiH4XAN38LWeLUI/edit#heading=h.5mwz58y9syps

**Comment by learnitall** [comment]
Ah sorry I wasn't clear on the use case. My thinking was if someone was writing a program based on UDP and wanted to adjust their payload size to help avoid fragmentation. I definitely agree that Cilium takes care of setting the MTU for users, I'm just thinking about how users should determine the MTU that Cilium sets.

**Comment by joestringer** [comment]
Oh I see. Cilium expects MTU to be configured on the route inside the Pod. So applications could either autodetect via a netlink route lookup in the kernel, or just have a flag to configure MTU.

**Comment by learnitall** [comment]
Ah got it that makes sense. To confirm, this means that applications should not use the MTU of the primary interface in a Pod, they need to use the route?
