### ISSUE TITLE
when kvstore is true, should we store the ciliumendpoints to the kvstore?

### ISSUE THREAD

**Issue by hippo03** [cilium/cilium#31444]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

In production environment，a large Cilium-powered Kubernetes cluster's api server is crushed be the large scale of ciliumendpoints and ciliumidentities.

**Describe the feature you'd like**

When we use cilium and set kvstore to be true,  for example we use etcd. Then we will store ciliumidentities to the cilium etcd, why not we store ciliumendpoints into the cilium etcd? or has I made a mistake that when kvstore is true, ciliumendpoints is also has been stored into cilium etcd? 

**(Optional) Describe your proposed solution**

In a large Cilium-powered Kubernetes cluster, the ciliumidentities and ciliumendpoints make a big pressure to k8s api server, and may make api server crushed.
when we set kvstore is true, maybe we should store the ciliumendpoints to the new kvstore, like the ciliumidentities.

**Comment by giorio94** [comment]
Hey @hippo03,

CiliumEndpoints are already stored inside etcd in that case. That said, CiliumEndpoints are still created, but not watched by remote agents (although in older versions there may be caveats based on other settings). Are you still seeing APIServer pressure even after enabling kvstore mode?

**Comment by hippo03** [comment]
> Hey @hippo03,
> 
> CiliumEndpoints are already stored inside etcd in that case. That said, CiliumEndpoints are still created, but not watched by remote agents (although in older versions there may be caveats based on other settings). Are you still seeing APIServer pressure even after enabling kvstore mode?

@giorio94 Thanks for your reply.  
"CiliumEndpoints are still created, but not watched by remote agents " 
Do you mean we should set enable-cilium-endpoint-slice to be true? ( ciliumendpointslice is a beta feature now, I am puzzled that it has been merge for about three years, and gke has use it for some time. By the way, why it is still beta?)

I am reading the code of cilium,  in the function (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync, it call:
ciliumClient := epSync.Clientset.CiliumV2()
...
ciliumClient.CiliumEndpoints(namespace).Create(ctx, cep, meta_v1.CreateOptions{})
...
Do you mean the "ciliumClient" here in RunK8sCiliumEndpointSync is connected to the "new kvstore" when kvstore is set to be true?

**Comment by giorio94** [comment]
> Do you mean we should set enable-cilium-endpoint-slice to be true? ( ciliumendpointslice is a beta feature now, I am puzzled that it has been merge for about three years, and gke has use it for some time. By the way, why it is still beta?)

Nope, that's a different, orthogonal, feature, which also aims to improve the scalability in large clusters. But that's not compatible/useful in combination with kvstore mode, as agents would not watch the CiliumEndpoints nor the CiliumEndpointSlices. I'm not sure about the reasons why it still marked as beta, but I guess one could be lack of automated testing.

> Do you mean the "ciliumClient" here in RunK8sCiliumEndpointSync is connected to the "new kvstore" when kvstore is set to be true?

No, that logic still creates the CiliumEndpoints. [This is the function](https://github.com/cilium/cilium/blob/main/pkg/endpoint/policy.go#L810-L812) which synchronizes the endpoint information into the kvstore.

**Comment by hippo03** [comment]
> Nope, that's a different, orthogonal, feature, which also aims to improve the scalability in large clusters. But that's not compatible/useful in combination with kvstore mode, as agents would not watch the CiliumEndpoints nor the CiliumEndpointSlices. I'm not sure about the reasons why it still marked as beta, but I guess one could be lack of automated testing.
> 
Thanks!

> No, that logic still creates the CiliumEndpoints.
https://github.com/cilium/cilium/issues/31444#issuecomment-2003852213
This link is the func (k *K8sWatcher) ciliumEndpointsInit() in which it create a informer to watch "ciliumendpoints".
I think this function will work on every node. If the cluster have thousands of nodes，it will be a big pressure for api server. Is it right ?
For the main branch, the link is https://github.com/cilium/cilium/blob/fc1f87bd2285778c7fb582fa23376ee8d52d61cd/pkg/k8s/watchers/cilium_endpoint.go#L27

> [This is the function](https://github.com/cilium/cilium/blob/main/pkg/endpoint/policy.go#L810-L812) which synchronizes the endpoint information into the kvstore.
Thanks! 
This synchronizes the ipcache to other nodes. If we have synchronized ipcache and ciliumidentity to other nodes, it looks like we donot need ciliumenpoints be synchronized, is it right? Thanks.

**Comment by giorio94** [comment]
> This synchronizes the ipcache to other nodes. If we have synchronized ipcache and ciliumidentity to other nodes, it looks like we donot need ciliumenpoints be synchronized, is it right? Thanks.

Yes, that's why CiliumEndpoints are still created (as potentially needed during agent bootstrap for instance), but not watched by the agents subsequently.

**Comment by hippo03** [comment]
> > This synchronizes the ipcache to other nodes. If we have synchronized ipcache and ciliumidentity to other nodes, it looks like we donot need ciliumenpoints be synchronized, is it right? Thanks.
> 
> Yes, that's why CiliumEndpoints are still created (as potentially needed during agent bootstrap for instance), but not watched by the agents subsequently.

 I read the func (k *K8sWatcher) ciliumEndpointsInit() again, and I get it now: this informer for "ciliumendpoints" will not need to work when key-value store is connected.  
 Thanks! @giorio94
