### ISSUE TITLE
Loosen restriction on allowing rules for default CIDR (/0)

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3146]
These restrictions prevent default CIDRs from allowing all traffic:

https://github.com/cilium/cilium/blob/3157e9ad5a27b55a32c7add7426bd036ebf83bb0/pkg/policy/api/rule_validation.go#L308-L312

https://github.com/cilium/cilium/blob/3157e9ad5a27b55a32c7add7426bd036ebf83bb0/pkg/policy/rule_test.go#L651-L657

The datapath supports such CIDRs, we should be able to fix these up to support them too without too much trouble.

**Comment by joestringer** [comment]
@tgraf did we address this already?

**Comment by tgraf** [comment]
I believe yes

**Comment by joestringer** [comment]
Closing as duplicate of #3945.
