### ISSUE TITLE
Hubble Relay error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"

### ISSUE THREAD

**Issue by aleksandarilic96** [cilium/cilium#31516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi all,

I have been trying to enable Hubble on my K3S singe node cluster but have run into the same issue as in https://github.com/cilium/cilium/issues/20130

Yes, i have checked all of the steps mentioned in the issue.

Cilium and Hubble are enabled via helm only
Certs are not expired since its a fresh install.
I have compared the CA of hubble-server and hubble-realy and they are the same
I use cluster.local

I have also looked into the issue https://github.com/cilium/hubble-ui/issues/321 and tried removing httpV2 that didn't work. Also disabling TLS provided the same error just with port 80

Any Insite would be greatly appreciated since i not sure where to look anymore.

Note: SELinux is permissive and firewalld is disabled 

Thanks all

### Cilium Version

v1.15.1

### Kernel Version

Oracle Linux 8.8

Linux 5.4.17-2136.327.2.el8uek.x86_64 #2 SMP Fri Jan 5 14:55:52 PST 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.7+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7+k3s1

### Sysdump

[cilium-sysdump-20240320-003948.zip](https://github.com/cilium/cilium/files/14658923/cilium-sysdump-20240320-003948.zip)

### Relevant log output

```shell
2024-03-20T01:39:12+01:00 level=info msg="Starting gRPC health server..." addr=":4222" subsys=hubble-relay
2024-03-20T01:39:12+01:00 level=info msg="Starting gRPC server..." options="{peerTarget:hubble-peer.kube-system.svc.cluster.local:443 dialTimeout:5000000000 retryTimeout:30000000000 listenAddress::4245 healthListenAddress::4222 metricsListenAddress: log:0xc0002ae1c0 serverTLSConfig:<nil> insecureServer:true clientTLSConfig:0xc000780c18 clusterName:default insecureClient:false observerOptions:[0x1f02b40 0x1f02c20] grpcMetrics:<nil> grpcUnaryInterceptors:[] grpcStreamInterceptors:[]}" subsys=hubble-relay
2024-03-20T01:39:17+01:00 level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
2024-03-20T01:39:52+01:00 level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
2024-03-20T01:40:12+01:00 level=info msg="Stopping server..." subsys=hubble-relay
2024-03-20T01:40:12+01:00 level=info msg="Server stopped" subsys=hubble-relay
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jwitko** [comment]
I recently had this issue as well.  For me it was that the secrets cert-manager created were out of date and for whatever reason cert-manager wasn't able to update them.  deleting the actual Secret and having cert-manager automatically recreate it solved the issue for me.

**Comment by aleksandarilic96** [comment]
Its a fresh k3s so I don't have a cert-manager but I will definitely test this.

Thanks

**Comment by aleksandarilic96** [comment]
I tried using the cert-manager TLS method as before it was helm just to see if it would produce any different outcome still the same error

**Comment by aleksandarilic96** [comment]
Just to add few notes: 

I also tested DNS resolution for hubble-peer.kube-system.svc.cluster.local and its is being resloved

**Comment by tooboredtocode** [comment]
Got the same error, weirdly it only happens when I have hubble metrics enabled, without them everything works as expected...

**Comment by aleksandarilic96** [comment]
Ok i found one intrensting thing 

![image](https://github.com/cilium/cilium/assets/69651352/211485f8-222b-4a2a-a764-59deaa214215)

![image](https://github.com/cilium/cilium/assets/69651352/2ae549b3-58f1-423f-985d-ee441653de47)


I updated the peer-service: to IP-of the machine port 4244 and it was able to make connection to the hubble-peer service

So its able to make the connection outside the cluster but inside its falling to hubble-peer.kube-system.svc.cluster.local:443

**Comment by aleksandarilic96** [comment]
My best guess here is that pod-to-service communication is falling but kubeProxyReplacement is set to true

**Comment by aleksandarilic96** [comment]
Gonna leave here what I found if anyone runs into the same issue.

First Check if dnsPolicy: ClusterFirst

Then Add log in the coredns config map as mentioned here https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#are-dns-queries-being-received-processed as then you can see how coredns is resolving your queries

What I saw here is that when coredns goes through resolving my query it never reached to try the query as fqdn because of ndots=5  and it was able to resolve one of my dns suffixes (which it shouldn't) in my /etc/reslove.conf and because of that it was sending my request to aws global accelerator (this is due to our env being hybrid)
So that request would stop DNS from resolving further down the chain as the last address it should try reslove is fqdn hubble-peer.kube-system.svc.cluster.local
I removed that DNS suffix from /etc/resolve.conf and it was able to resolve it.
As always its DNS 🗡️ 

Here is github issue also for DNS resolution which explains how it works on k8s side https://github.com/kubernetes/dns/issues/159

**Comment by quangyen** [comment]
**### Resolved** with my case:
First, you should use this guide to check your case to determine why your service cannot call internal domains:
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

In my case, the K8s DNS points from hubble-peer.kube-system.svc.cluster.local to hubble-peer.kube-system.svc.cluster.local.myowndomain.com. (In my Cloudflare settings, I point A * to myowndomain.com.) This causes the K8s DNS to prefer hubble-peer.kube-system.svc.cluster.local.myowndomain.com over the internal domain, resulting in an error

**Comment by stelucz** [comment]
> Got the same error, weirdly it only happens when I have hubble metrics enabled, without them everything works as expected...
@tooboredtocode  I had similar problem, check if hubble server inside cilium agent is running fine. I had problem with enabled metrics that were invalid and thus hubble server did not start, that caused the peer-service to be unavailable and relay to not start.

**Comment by 3bbbeau** [comment]
Thank you @stelucz 

I had a configuration that looked like:

```yaml
hubble:
  metrics:
    serviceMonitor:
      enabled: true
    enabled:
      - dns_ <-- trailing underscore
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
```

From your advice, I checked the Cilium `DaemonSet` logs which sure enough showed the invalid metric name `dns_`. All good now after correcting it.

**Comment by stelucz** [comment]
@3bbbeau I am glad it helped someone :)

**Comment by raydenz** [comment]
> **Resolved** with my case: First, you should use this guide to check your case to determine why your service cannot call internal domains: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
> 
> In my case, the K8s DNS points from hubble-peer.kube-system.svc.cluster.local to hubble-peer.kube-system.svc.cluster.local.myowndomain.com. (In my Cloudflare settings, I point A * to myowndomain.com.) This causes the K8s DNS to prefer hubble-peer.kube-system.svc.cluster.local.myowndomain.com over the internal domain, resulting in an error

Thank you @quangyen  i had the same problem not it is resolved
in the configmap i added "hubble-relay-config" i add a dot in the url 
```

before: "peer-service: "hubble-peer.kube-system.svc.cluster.local:443"
after:     "peer-service: "hubble-peer.kube-system.svc.cluster.local.:443"  
```

This explicitly tells the DNS resolver to treat hubble-peer.kube-system.svc.cluster.local. as a complete domain name, preventing the appending of search domains.

**Comment by kevin-presalytics** [comment]
> **Resolved** with my case: First, you should use this guide to check your case to determine why your service cannot call internal domains: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
> 
> In my case, the K8s DNS points from hubble-peer.kube-system.svc.cluster.local to hubble-peer.kube-system.svc.cluster.local.myowndomain.com. (In my Cloudflare settings, I point A * to myowndomain.com.) This causes the K8s DNS to prefer hubble-peer.kube-system.svc.cluster.local.myowndomain.com over the internal domain, resulting in an error

This worked for me --> I had this issue with k3s.  Fixed by creating a custom `resolv.conf` file on each node and passing its path to the `--resolve-conf` setting in `kubelet-args`.

**Comment by HujinoKun** [comment]
> > **Resolved** with my case: First, you should use this guide to check your case to determine why your service cannot call internal domains: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
> > In my case, the K8s DNS points from hubble-peer.kube-system.svc.cluster.local to hubble-peer.kube-system.svc.cluster.local.myowndomain.com. (In my Cloudflare settings, I point A * to myowndomain.com.) This causes the K8s DNS to prefer hubble-peer.kube-system.svc.cluster.local.myowndomain.com over the internal domain, resulting in an error
> 
> Thank you [@quangyen](https://github.com/quangyen) i had the same problem Now it is resolved !
> 
> Explanation : in the configmap i added "hubble-relay-config" i add a dot in the url This explicitly tells the DNS resolver to treat hubble-peer.kube-system.svc.cluster.local. as a complete domain name, preventing the appending of search domains.
> 
> ```
> before: "peer-service: "hubble-peer.kube-system.svc.cluster.local:443"
> after:     "peer-service: "hubble-peer.kube-system.svc.cluster.local.:443"  
> ```
> 
> If it can helm someone :)

Thank's !!!!

**Comment by HujinoKun** [comment]
Finally, after 2 days, it came back with the same error message :(
