### ISSUE TITLE
cilium entedy always showing world

### ISSUE THREAD

**Issue by oliver-hofmann-cistec-com** [cilium/cilium#31519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we create network policies, label or namespace matching does not work, it just always shows world

### Cilium Version

v1.14.7

### Kernel Version

6.6.13-200.fc39.x86_64

### Kubernetes Version

v1.27.10+k3s2

### Regression

none

### Sysdump

[cilium-sysdump-20240320-100917.zip](https://github.com/cilium/cilium/files/14664067/cilium-sysdump-20240320-100917.zip)

### Relevant log output

```shell
Mar 14 11:50:59.882: default/alpine-pod:54750 (ID:1455433) <> 10.43.199.5:80 (world) Policy denied DROPPED (TCP Flags: SYN)
Mar 14 11:51:00.921: default/alpine-pod:54750 (ID:1455433) <> 10.43.199.5:80 (world) policy-verdict:none EGRESS DENIED (TCP Flags: SYN)
```

### Anything else?

pod cidr: 10.42.0.0/16
svc cidr: 10.43.0.0/16

k3s config:
write-kubeconfig-mode: 600
token: "redacted"

tls-san:
  - "redacted"

bind-address: "redacted"

selinux: true
secrets-encryption: true

flannel-backend: "none"
disable-network-policy: true
disable-cloud-controller: true

node-taint:
  - "node.kubernetes.io/control-plane=true:NoSchedule"

node-label:
  - "node-role.cistec.com/controle-plane=true"

disable:
  - local-storage

etcd-expose-metrics: true

protect-kernel-defaults: true

kubelet-arg: "config=/etc/rancher/k3s/kubelet.config"

# cant be all in files since this feature is not consistent
kube-apiserver-arg:
  - 'audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log'
  - 'audit-log-maxage=30'
  - 'audit-log-maxbackup=10'
  - 'audit-log-maxsize=100'
  - 'request-timeout=300s'
  - 'service-account-lookup=true'
  - 'anonymous-auth=false'
  - 'enable-admission-plugins=AlwaysPullImages'
  - 'feature-gates=AggregatedDiscoveryEndpoint=false'
kube-controller-manager-arg:
  - 'terminated-pod-gc-threshold=10'
  - 'use-service-account-credentials=true'
  - 'allocate-node-cidrs'
cluster-init: true

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Can you share one of the policies that you expect to allow traffic, but it's being denied?

>default/alpine-pod:54750 (ID:1455433) <> 10.43.199.5:80 (world) Policy denied DROPPED (TCP Flags: SYN)

This seems to be a service clusterIP based on the service cidr you shared in the report. Are you using [services based CNPs](https://docs.cilium.io/en/latest/security/policy/language/#services-based)?

**Comment by oliver-hofmann-cistec-com** [comment]
to be honest, it happens with any NP that targets using Pod or Namespaceselectors. It also does not matter if it is a Regular NetworkPolicy or a CiliumNetworkPolicy

**Comment by oliver-hofmann-cistec-com** [comment]
@aditighag can you help me or should I look somewhere else for help?

**Comment by oliver-hofmann-cistec-com** [comment]
I did now setup a k3s cluster without kube-proxy and it does work now, closing

**Comment by oliver-hofmann-cistec-com** [comment]
I did now setup a k3s cluster without kube-proxy and it does work now, closing
