### ISSUE TITLE
No connectivity between nodes after node IP changes

### ISSUE THREAD

**Issue by drigz** [cilium/cilium#31528]
[Uploading cilium-sysdump-20240320-163138.zip…]()
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If the node IP changes, Cilium loses connectivity between nodes until the cilium-agent is restarted. This happens to our edge clusters when a DHCP server misbehaves or when a static IP needs to be changed (often to take advantage of a new firewall configuration.

Repro:

```
# setup
curl -LO https://raw.githubusercontent.com/cilium/cilium/1.15.2/Documentation/installation/kind-config.yaml
kind create cluster --config=kind-config.yaml
cilium install --version 1.15.2 --set enableRuntimeDeviceDetection=true
cilium status --wait

# inside worker node: remove hardcoded node-ip, so kubelet can pick it up from the default ipv4 route
docker exec -it kind-worker /bin/bash
sed -i "s/ --node-ip=[^ ]*//" /var/lib/kubelet/kubeadm-flags.env
systemctl restart kubelet
sleep 10

# once kubelet has restarted, change the IP
ip addr flush dev eth0
ip addr add 192.168.8.123/24 dev eth0
ip route add default via 192.168.8.1 dev eth0
exit

# wait for node to be updated
kubectl get nodes -o wide -w
# ctrl+c when you see the new IP
```

then, go back to the host to test connectivity:

```
cilium connectivity test
[...]
⌛ [kind-kind] Waiting for pod cilium-test/client3-868f7b8f6b-7nkcf to reach DNS server on cilium-test/echo-same-node-6698bd45b-zb77k pod...
connectivity test failed: timeout reached waiting for lookup for localhost from pod cilium-test/client3-868f7b8f6b-7nkcf to server on pod cilium-test/echo-same-node-6698bd45b-zb77k to succeed (last error: error with exec request (pod=cilium-test/client3-868f7b8f6b-7nkcf, container=): context deadline exceeded)
```

### Cilium Version

cilium-cli: v0.16.3 compiled with go1.22.1 on linux/amd64
cilium image (default): v1.15.2
cilium image (stable): v1.15.1
cilium image (running): 1.15.2

(also repros on 1.16.0-pre.0)

### Kernel Version

6.6.13-1rodete3-amd64 #1 SMP PREEMPT_DYNAMIC

### Kubernetes Version

Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2

### Anything else?

I had a look for possible places that the old state exists - it seems like StateDB gets updated but other places do not:

```
$ netstat -ntlp | grep cilium-agent | grep 192
tcp        0      0 192.168.8.2:4240        0.0.0.0:*               LISTEN      1160/cilium-agent
$ kubectl -n kube-system exec -it cilium-tc44g -- cilium-dbg statedb node-addresses
Address         NodePort   Primary   DeviceName
10.244.2.200    false      true      cilium_host
192.168.8.123   true       true      eth0
$ kubectl -n kube-system exec -it cilium-tc44g -- cilium-dbg node list
Name                           IPv4 Address   Endpoint CIDR   IPv6 Address   Endpoint CIDR   Source
kind-kind/kind-control-plane   192.168.8.5    10.244.0.0/24                                  custom-resource
kind-kind/kind-worker          192.168.8.2    10.244.2.0/24                                  local
kind-kind/kind-worker2         192.168.8.3    10.244.3.0/24                                  custom-resource
kind-kind/kind-worker3         192.168.8.4    10.244.1.0/24                                  custom-resource
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Node IP changes require agent restart at the moment. There've been similar issues reported previously - https://github.com/cilium/cilium/issues/15406.

**Comment by drigz** [comment]
Let's close this as a duplicate of https://github.com/cilium/cilium/issues/15406.
