### ISSUE TITLE
kvstoremesh CrashLoopBackOff

### ISSUE THREAD

**Issue by alexminder** [cilium/cilium#31524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have enabled clustermesh and it works fine.
Then I have enabled new feature kvstoremesh.
Kvstoremesh can not start:

### Cilium Version

1.15.2

### Kernel Version

5.14.0-375.el9.x86_64

### Kubernetes Version

Server Version: v1.26.4-3010+c7606e743ff1b0-dirty

### Relevant log output

```shell
$ oc -n cilium logs clustermesh-apiserver-87684b5d5-zv87g -c kvstoremesh
level=info msg="  --cluster-id='1'" subsys=kvstoremesh
level=info msg="  --cluster-name='testing1'" subsys=kvstoremesh
level=info msg="  --clustermesh-config='/var/lib/cilium/clustermesh'" subsys=kvstoremesh
level=info msg="  --controller-group-metrics='all'" subsys=kvstoremesh
level=info msg="  --debug='false'" subsys=kvstoremesh
level=info msg="  --gops-port='9894'" subsys=kvstoremesh
level=info msg="  --kvstore='etcd'" subsys=kvstoremesh
level=info msg="  --kvstore-connectivity-timeout='2m0s'" subsys=kvstoremesh
level=info msg="  --kvstore-lease-ttl='15m0s'" subsys=kvstoremesh
level=info msg="  --kvstore-opt='etcd.maxInflight=10,etcd.config=/var/lib/cilium/etcd-config.yaml,etcd.qps=100'" subsys=kvstoremesh
level=info msg="  --kvstore-periodic-sync='5m0s'" subsys=kvstoremesh
level=info msg="  --max-connected-clusters='255'" subsys=kvstoremesh
level=info msg="  --pprof='false'" subsys=kvstoremesh
level=info msg="  --pprof-address='localhost'" subsys=kvstoremesh
level=info msg="  --pprof-port='6064'" subsys=kvstoremesh
level=info msg="  --prometheus-serve-addr=':9964'" subsys=kvstoremesh
level=info msg=Invoked duration="171.06µs" function="github.com/cilium/cilium/clustermesh-apiserver/kvstoremesh.registerClusterInfoValidator (go/src/github.com/cilium/cilium/clustermesh-apiserver/kvstoremesh/root.go:49)" subsys=hive
level=info msg=Invoked duration="93.435µs" function="pprof.glob..func1 (pkg/pprof/cell.go:50)" subsys=hive
level=info msg=Invoked duration="118.874µs" function="controller.Init (pkg/controller/cell.go:67)" subsys=hive
level=info msg=Invoked duration="89.315µs" function="gops.registerGopsHooks (pkg/gops/cell.go:38)" subsys=hive
level=info msg=Invoked duration="199.556µs" function="github.com/cilium/cilium/clustermesh-apiserver/metrics.registerMetricsManager (go/src/github.com/cilium/cilium/clustermesh-apiserver/metrics/metrics.go:56)" subsys=hive
level=info msg=Invoked duration="261.455µs" function="github.com/cilium/cilium/clustermesh-apiserver/kvstoremesh.glob..func2 (go/src/github.com/cilium/cilium/clustermesh-apiserver/kvstoremesh/cells.go:42)" subsys=hive
level=info msg=Starting subsys=hive
level=info msg="Start hook executed" duration="8.624µs" function="github.com/cilium/cilium/clustermesh-apiserver/kvstoremesh.registerClusterInfoValidator.func1 (go/src/github.com/cilium/cilium/clustermesh-apiserver/kvstoremesh/root.go:51)" subsys=hive
level=info msg="Started gops server" address="127.0.0.1:9894" subsys=gops
level=error msg="Start hook failed" error="open /1: permission denied" function="gops.registerGopsHooks.func1 (pkg/gops/cell.go:43)" subsys=hive
level=info msg=Stopping subsys=hive
level=fatal msg="failed to start: open /1: permission denied" subsys=kvstoremesh
```
```


### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
cc @giorio94

**Comment by giorio94** [comment]
Hi @alexminder,

The issue seems to be caused by kvstoremesh running as a non-root user, hence not having the permissions to create files in `/` (or any other directory FWIW, and [gops](https://github.com/google/gops) appears to require writing the PID files somewhere at the moment).

Have you configured anything specific concerning the `podSecurityContext/securityContext` of clustermesh-apiserver compontents, either directly or automatically via any mutating webhook? Could you share the output of `kubectl get pod -n kube-system -l app.kubernetes.io/name=clustermesh-apiserver -o yaml` please? I'm curious because the same issue should affect the clustermesh-apiserver pod as well.

I'm working on addressing this issue in the meanwhile, but a short-term fix should be explicitly configuring the kvstoremesh container to run as root.

**Comment by giorio94** [comment]
I've opened https://github.com/cilium/cilium/pull/31539 (and marked it for backport to v1.15), which should address the issue. I've also opened https://github.com/cilium/cilium/pull/31540 as a follow-up to configure restrictive security contexts by default for the clustermesh-apiserver containers.

**Comment by alexminder** [comment]
We are using OpenShift which guarded with SCC (Security Context Constraints). SCC prevents to run a container app with uid=0. For every cluster it is rundom generated UID range.

**Comment by giorio94** [comment]
> We are using OpenShift which guarded with SCC (Security Context Constraints). SCC prevents to run a container app with uid=0. For every cluster it is rundom generated UID range.

Yeah, that's what I suspected. 

My guess is that it is affecting only the kvstoremesh container because its default security context is:

```
securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
```

I could instead reproduce the issue on both the apiserver and kvstoremesh containers manually specifying a different `runAsUser` value as part of the respective security contexts. As a quick workaround, does kvstoremesh work dropping that security context?

**Comment by alexminder** [comment]
> As a quick workaround, does kvstoremesh work dropping that security context?

It does not work.

**Comment by giorio94** [comment]
> > As a quick workaround, does kvstoremesh work dropping that security context?
> 
> It does not work.

Hmm, I'm confused what's the difference with respect to the apiserver container then, as the image is the same, and both start `gops` in the same way. What if you manually specify `runAsUser: 0`?

**Comment by giorio94** [comment]
Backport in progress in https://github.com/cilium/cilium/pull/31879
