### ISSUE TITLE
Remove `hostPort` dependency on BPF `NodePort` 

### ISSUE THREAD

**Issue by clay-moss** [cilium/cilium#31532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, enabling `hostPort` requires that `nodePort` is also enabled, this requirement is listed for the `--enable-host-port` flag in the Cilium agent command reference:
 

- [Command Reference - cilium-agent](https://docs.cilium.io/en/stable/cmdref/cilium-agent/)

 
Additionally, if `NodePort` is disabled, then its dependents, including `hostPort`, are also disabled:
 
```go
// https://github.com/cilium/cilium/blob/c80018ec287dcbd2f4dfd7571e24514afcc39703/daemon/cmd/kube_proxy_replacement.go#L498

// disableNodePort disables BPF NodePort and friends who are dependent from
// the latter.
func disableNodePort() {
	option.Config.EnableNodePort = false
	option.Config.EnableHostPort = false
	option.Config.EnableExternalIPs = false
	option.Config.EnableSVCSourceRangeCheck = false
	option.Config.EnableHostLegacyRouting = true
}
```

However, despite `NodePort` seemingly being a dependency of `hostPort`, having Wireguard enabled would result in the `disableNodePort()` function not being called, which would keep `hostPort` enabled, and it is functional. 

Is `NodePort` actually a necessary requirement for `hostPort` or can we remove this limitation?

Relevant comments from @brb:

> hostPort can be accessed from outside cluster, thus it depends on nodeport. for in-cluster access it should not depend on nodeport, as it's implemented in bpf_sock/bpf_lxc (vs bpf_host for nodeport).

### Cilium Version

v1.15, v1.14, v1.13

### Kernel Version

`Linux xxx 5.15.0-1057-azure #65-Ubuntu SMP Fri Feb 9 18:39:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.5", GitCommit:"506050d61cf291218dfbd41ac93913945c9aa0da", GitTreeState:"clean", BuildDate:"2023-12-23T00:10:25Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}`

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
> However, despite NodePort seemingly being a dependency of hostPort, having Wireguard enabled would result in the disableNodePort() function not being called, which would keep hostPort enabled, and it is functional.

> Is NodePort actually a necessary requirement for hostPort or can we remove this limitation?

It is a requirement given it uses the nodeport BPF code to set up and install hostport services. What issue are you seeing?
