### ISSUE TITLE
CiliumEndpoints (CEP) not always being created

### ISSUE THREAD

**Issue by atamgp** [cilium/cilium#31555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In cilium 1.14 and above, when we delete all our nodes in the eks cluster, we always end up with unmanaged pod (no cep created).

We use karpenter with the right startup taint:
```
# Required for cilium chaining with aws vpc-cni (https://docs.cilium.io/en/stable/installation/taints/)
        startupTaints:
        - effect: NoExecute
          key: node.cilium.io/agent-not-ready
```

In the current case from which logs have been uploaded we have **2 pods with no cep on the same node**:
```
missing ceps:
gatemin-system gatemin-ext-auth-filter-7569fbbbfc-cwfbw
webhook-proxy-system pax-webhook-proxy-66f597c4b9-kqwh4


related nodes:
ip-10-116-82-93.eu-central-1.compute.internal


all pods on those nodes:
ci-pax-lujw-oneagent-rwr29  creationTimestamp:2024-03-21T12:12:07Z  priorityClassName:  hostNetwork:true
contour-envoy-4pkkn  creationTimestamp:2024-03-21T12:13:23Z  priorityClassName:  hostNetwork:null
gatemin-envoy-v9slr  creationTimestamp:2024-03-21T12:13:23Z  priorityClassName:  hostNetwork:true
gatemin-ext-auth-filter-7569fbbbfc-cwfbw  creationTimestamp:2024-03-21T12:09:51Z  priorityClassName:  hostNetwork:null
aws-node-wdp26  creationTimestamp:2024-03-21T12:10:37Z  priorityClassName:system-node-critical  hostNetwork:true
cilium-g9vh2  creationTimestamp:2024-03-21T12:10:37Z  priorityClassName:system-node-critical  hostNetwork:true
ebs-csi-node-6xm7z  creationTimestamp:2024-03-21T12:10:37Z  priorityClassName:system-node-critical  hostNetwork:null
efs-csi-node-bdtvz  creationTimestamp:2024-03-21T12:10:37Z  priorityClassName:system-node-critical  hostNetwork:true
kube-proxy-cctc7  creationTimestamp:2024-03-21T12:10:37Z  priorityClassName:system-node-critical  hostNetwork:true
default-fluentbit-82q8b  creationTimestamp:2024-03-21T12:12:08Z  priorityClassName:infra-daemonsets  hostNetwork:null
pax-webhook-proxy-66f597c4b9-kqwh4  creationTimestamp:2024-03-21T12:09:51Z  priorityClassName:  hostNetwork:null
```
   
As can be seen above, on that node critical pods are created at  2024-03-21T12:10:37Z
The 2 pods which are missing a cep, are created at 2024-03-21T12:09:51Z and  2024-03-21T12:09:51Z  **before aws-node and cilium agent.....**

aws-node ready: 
2024-03-21T12:10:47.312034783Z time="2024-03-21T12:10:47Z" level=info msg="CNI init container done"
...
2024-03-21T12:11:05.570003679Z time="2024-03-21T12:11:05Z" level=info msg="Successfully copied CNI plugin binary and config file."

cilium-g9vh2 adding its node:
2024-03-21T12:11:05.380372284Z level=info msg="Creating or updating CiliumNode resource" node=ip-10-116-82-93.eu-central-1.compute.internal subsys=nodediscovery
2024-03-21T12:11:05.380375854Z level=info msg="Creating or updating CiliumNode resource" node=ip-10-116-82-93.eu-central-1.compute.internal subsys=nodediscovery
2024-03-21T12:11:05.385671485Z level=warning msg="Unable to get node resource" error="ciliumnodes.cilium.io \"ip-10-116-82-93.eu-central-1.compute.internal\" not found" subsys=nodediscovery
2024-03-21T12:11:05.386106700Z level=warning msg="Unable to get node resource" error="ciliumnodes.cilium.io \"ip-10-116-82-93.eu-central-1.compute.internal\" not found" subsys=nodediscovery
2024-03-21T12:11:05.402886722Z level=info msg="Successfully created CiliumNode resource" subsys=nodediscovery
2024-03-21T12:11:05.434537285Z level=warning msg="Unable to create CiliumNode resource, will retry" error="ciliumnodes.cilium.io \"ip-10-116-82-93.eu-central-1.compute.internal\" already exists" subsys=nodediscovery
2024-03-21T12:11:06.022722152Z level=info msg="Retrieved node information from cilium node" nodeName=ip-10-116-82-93.eu-central-1.compute.internal subsys=k8s
2024-03-21T12:11:06.022737442Z level=warning msg="Waiting for k8s node information" error="required IPv4 PodCIDR not available" subsys=k8s
2024-03-21T12:11:06.453767055Z level=info msg="Retrieved node information from cilium node" nodeName=ip-10-116-82-93.eu-central-1.compute.internal subsys=k8s
2024-03-21T12:11:06.453793716Z level=info msg="Received own node information from API server" ipAddr.ipv4=10.116.82.93 ipAddr.ipv6="<nil>" k8sNodeIP=10.116.82.93
....

So my conclusion (may be wrong here) seems like the 2 problematic pods were started to soon.
In the logs of cilium-g9vh2 I can find a "New endpoint" event for all non-hostNetwork pods o that node, but not of the 2 pods with missing cep.

The node is started by Karpenter using the right startup taint, I cannot see in the agent's log when this taint is removed.
It seems strange that the 2 pods can be started before the agent is ready without tolerations for this taint....
The 2 problem pods both have these tolerations only:
```
tolerations:
  - key: node.kubernetes.io/ingress
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```
    
    
Could it be the case that the startup taint is removed too soon?
This is not experienced in 1.13.9 and earlier

### Cilium Version

1.14.8

### Kernel Version

[amazon_eks_ami_version = "v20240307"](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240307)

### Kubernetes Version

1.26

### Sysdump

[cilium-sysdump-20240322-104452.zip](https://github.com/cilium/cilium/files/14721472/cilium-sysdump-20240322-104452.zip)

### Anything else?
**cilium chart values:**

#### cilium-operator
operator:
  rollOutPods: true
  replicas: 3
  priorityClassName: system-cluster-critical
  nodeSelector:
    type: infra
  tolerations:
  - key: node.cilium.io/agent-not-ready
    operator: Exists
  - key: node.kubernetes.io/not-ready
    operator: Exists
  - key: node.kubernetes.io/infra
    operator: Exists
  podDisruptionBudget:
    enabled: true

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
      labelSelector:
        matchLabels:
          k8s-app: cilium
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
          - fargate

#### cilium-agent
priorityClassName: system-node-critical

#### native routing with no (tunnel) encapsulation, we use aws ci for routing in chaining mode, cilium's internal eni is disabled
routingMode: native
cni:
  chainingMode: aws-cni
  exclusive: false
eni:
  enabled: false

wellKnownIdentities:
  enabled: true
ipv4:
  enabled: true
ipv6:
  enabled: false
#### This is done by the aws cni:
enableIPv4Masquerade: false
enableIPv6Masquerade: false
endpointRoutes:
  enabled: true
endpointStatus:
  enabled: true
  status: policy health state
endpointHealthChecking:
  enabled: false
healthChecking: false

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atamgp** [comment]
### Update

I cannot reason why there were no "New endpoint" events on that agent (cilium-g9vh2) for those 2 problem pods....
gatemin-ext-auth-filter has 2 other pods on other nodes where the pods are **also started before aws-node and cilium-agent** in the same way, but there the events did kick in on the cilium-agents.....

node 2:
```
gatemin-ext-auth-filter-7569fbbbfc-tl5sc  creationTimestamp:2024-03-21T12:09:55Z  priorityClassName:  hostNetwork:null
aws-node-bh9mv  creationTimestamp:2024-03-21T12:10:42Z  priorityClassName:system-node-critical  hostNetwork:true
cilium-hmn5b  creationTimestamp:2024-03-21T12:10:43Z  priorityClassName:system-node-critical  hostNetwork:true
```
k -n kube-system logs cilium-hmn5b | grep "gatemin-ext-auth-filter"
`level=info msg="Create endpoint request" addressing="&{100.64.149.93   fe80::2819:f1ff:feea:25c8  }" containerID=6a9bbcc62841e7302049d9a48c109af835be8ead8d3191fa271c1458b2734522 datapathConfiguration="&{false true false true true 0xc0020839c8}" interface=enic246f022e82 k8sPodName=gatemin-system/gatemin-ext-auth-filter-7569fbbbfc-tl5sc labels="[]" subsys=daemon sync-build=true`

node 3:
```
gatemin-ext-auth-filter-7569fbbbfc-ttsfz  creationTimestamp:2024-03-21T12:09:50Z  priorityClassName:  hostNetwork:null
aws-node-6kn6f  creationTimestamp:2024-03-21T12:10:36Z  priorityClassName:system-node-critical  hostNetwork:true
cilium-7x5nm  creationTimestamp:2024-03-21T12:10:35Z  priorityClassName:system-node-critical  hostNetwork:true
```
k -n kube-system logs cilium-7x5nm | grep "gatemin-ext-auth-filter"
`level=info msg="Create endpoint request" addressing="&{100.64.113.109   fe80::2802:92ff:fe0e:ce2a  }" containerID=ac3c0a2e63332d4c4680737bc9e5e1b1ed20e497a8422b9bae0eabfe90cf3afc datapathConfiguration="&{false true false true true 0xc000be55b0}" interface=eniabcdf4a384f k8sPodName=gatemin-system/gatemin-ext-auth-filter-7569fbbbfc-ttsfz labels="[]" subsys=daemon sync-build=true`

**Conclusion:**
I still don't understand how these pods can start this early before the agent when we use the starttaint... but on the other nodes this has not caused an issue and the Create endpoint events are received by the agents.
So I cannot explain this behavior.

**Comment by atamgp** [comment]
Update 2:

1) Tried cilium 1.15.2, problem stays (delete all nodes, see there are unmanaged pods)

2) Strange thing, here are 3 pods recreated when all nodes got deleted:

contour-envoy-c4n6w  creationTimestamp:2024-03-22T14:36:10Z
contour-envoy-tj4pd  creationTimestamp:2024-03-22T14:36:10Z
contour-envoy-zmhtm  creationTimestamp:2024-03-22T14:36:10Z

Their cep's:
contour-envoy-c4n6w  creationTimestamp:2024-03-22T14:36:11Z
contour-envoy-tj4pd  creationTimestamp:2024-03-22T14:36:11Z
contour-envoy-zmhtm  creationTimestamp:2024-03-22T14:36:11Z

These is 1 second difference.

Here a strange occurance in same namepace which might lead to packet loss?
pods:
contour-contour-5c5cf45c5b-xm4sc  creationTimestamp:2024-03-22T14:31:53Z
contour-contour-5c5cf45c5b-xpkdx  creationTimestamp:2024-03-22T14:33:34Z
ceps:
contour-contour-5c5cf45c5b-xm4sc  creationTimestamp:2024-03-22T14:33:03Z
contour-contour-5c5cf45c5b-xpkdx  creationTimestamp:2024-03-22T14:33:35Z

xm4schas a difference of 64 seconds...

===========================

I found in the code where the taint is removed:
```
// should we remove the taint?
	scheduled, running := nodeHasCiliumPod(node.GetName())
	if running {
		if (options.RemoveNodeTaint && hasAgentNotReadyTaint(node)) ||
			(options.SetCiliumIsUpCondition && !HasCiliumIsUpCondition(node)) {
			log.WithFields(logrus.Fields{
				logfields.NodeName: node.GetName(),
			}).Info("Cilium pod running for node; marking accordingly")

			markNode(c, nodeGetter, node.GetName(), options, true)
		}
```

```
func nodeHasCiliumPod(nodeName string) (scheduled bool, ready bool) {
	ciliumPodsInNode, err := ciliumPodsStore.ByIndex(hostnameIndexer, nodeName)
	if err != nil {
		return false, false
	}
	if len(ciliumPodsInNode) == 0 {
		return false, false
	}
	for _, ciliumPodInterface := range ciliumPodsInNode {
		ciliumPod := ciliumPodInterface.(*slim_corev1.Pod)
		if ciliumPod.DeletionTimestamp != nil { // even if the pod is running, it will be down shortly
			continue
		}
		if k8sUtils.GetLatestPodReadiness(ciliumPod.Status) == slim_corev1.ConditionTrue {
			return true, true
		}
	}
	return true, false
}	
```
GetLatestPodReadiness check is the cilium agent in ready:
https://github.com/cilium/cilium/blob/main/pkg/k8s/utils/utils.go

But I cannot find readiness gates in the pod spec....
Or code where a controller tests to see if cilium agent is done and setting the ready mark.
Also not in attached log of the agent.

**Comment by atamgp** [comment]
https://github.com/cilium/cilium/issues/29405 seems to address the 'taint removed too early'

**Comment by squeed** [comment]
As you observed, this is probably caused by #29405.

There is a race condition w.r.t. CNI and startup. It looks like this:

1. AWS writes its CNI configuration file
2. The node is marked as Ready
3. Cilium agent is scheduled on the node
4. Cilium *operator* removes the taint
5. Cilium inserts itself in to the CNI chain

If a pod is scheduled to the node before step 5, then it will not have a CEP created for it. This can happen if the desired taints are missing, or if the pod is somehow scheduled to the node regardless (it tolerates the taint, it was already scheduled, etc.)

Fixing #29405 should bring this closer to done.

**Comment by atamgp** [comment]
thanks, I will retest with that future fix and give the feedback here.
