### ISSUE TITLE
Does Ipsec work with HostPort enabled

### ISSUE THREAD

**Issue by dnayar9** [cilium/cilium#31561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Ipsec encryption  does not work with cni chaining, and also a strict kube proxy replacement. Does Ipsec work with partial kube proxy replacement? I only want to enable HostPort feature. 
Its hard for me to test that because of bug - https://github.com/cilium/cilium/issues/31168

### Cilium Version

1.14.6

### Kernel Version

Aks Node
OS-image - Ubuntu 20.04.6 LTS
Kernel Version - 5.4.0-1121-azure-fips

### Kubernetes Version

1.28.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
AIUI ipsec does not work with any forms of kube-proxy replacement. However, this should be easy enough for you to test :-).
