### ISSUE TITLE
Docs: OpenShift install guide reference cilium-olm that is archived

### ISSUE THREAD

**Issue by camrossi** [cilium/cilium#31577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The install instruction on https://docs.cilium.io/en/stable/installation/k8s-install-openshift-okd/#k8s-install-openshift-okd tell the user to git clone the https://github.com/cilium/cilium-olm repo that has been archived. 

```
git clone https://github.com/cilium/cilium-olm.git
```

The correct one is https://github.com/isovalent/olm-for-cilium

### Cilium Version

1.15.2

### Kernel Version

N/A

### Kubernetes Version

N/A

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
@learnitall @fgiloux I noticed https://github.com/cilium/cilium/pull/30736 went nowhere. How do we improve this - does https://github.com/cilium/cilium/pull/29300 need stable backports?

**Comment by learnitall** [comment]
Ah yes, #29300 does need stable backports. Does "stable" mean 1.15?

**Comment by julianwiedmann** [comment]
Should be resolved by the backports for https://github.com/cilium/cilium/pull/29300.
