### ISSUE TITLE
Ipam.mode per node custom configuration

### ISSUE THREAD

**Issue by ogallart23** [cilium/cilium#31596]
Hi,

I'm trying to bootstrap a K0S where the worker nodes are in diferent kinds of bootstrap, like VM or EC2 instances on AWS. After join 2 nodes (1 node in a VM and 1 EC2 instance on AWS) and install cilium with the default options, everything seems to be ok, but I've noticed that my CoreDNS pods deployed in EC2 instance has lots of timeouts to the gateway IP and if try to use the "nslookup" command it responds with "SERVFAIL". I f I deploy it to my VM instance the errors gone out. After review some issues, it seems that the EC2 node configuration needs to be "ipam.mode=eni" and "eni.enabled=true" to work.

So the question is: can i choose diferent "ipam.mode" per node or all nodes needed the same configration? If yes, is there an "ipam.mode" to fit all types of node deployment (EKS, VM, AKS, etc..)?

Thanks in advance

**Comment by squeed** [comment]
All nodes do need to use the same IPAM mode currently.

If you're having connectivity issues, the solution is to use an overlay such as VXLAN or GENEVE. You still, however, need to ensure that there is connectivity between the nodes.

Have a look at our [troubleshooting guide](https://docs.cilium.io/en/latest/operations/troubleshooting/) and see if anything shows up.

**Comment by ErGallo23** [comment]
Hi,

I tried to use the two overlay options with the same result. 

After digging a little bit on my configuration I found that the default clusterPoolIPv4PodCIDR overlaps with my wireguard nodes IP (10.222.0.X).

So after change it, CoreDNS errors went gone and all works.

Thanks for all.
