### ISSUE TITLE
CFP: L2 Pod Announcements: Support external Gateway

### ISSUE THREAD

**Issue by camrossi** [cilium/cilium#31600]
With the L2 Pod Announcements I can easily make my pod network routable across my whole network but to do so I need to configure my switches with IPs in the POD CIDR so that routing can happen. 

This works today however there is no way to tell Cilium that a specific range of IPs in the POD CIDR is not to be used. 
For example I have a cluster deployed with `POD CIDR = 10.52.0.0/16` and I have configured my switch with `10.52.255.254` address. 

As I add nodes or pods to my cluster I will eventually end up using all the available IP and potentially schedule a POD with IP `10.52.255.254`.

I think the chance is pretty low but is not zero so ideally I would like to reserve one CIDR for my network devices or even better a set of IPs. 

This should work for both cluster-pool and MultiPool. 

The primary use case is to (partially) remove the need of Egress gateways: with Multi-Pool Support (once #31079 is address) we can map a specific CIDR to a Namespace and it will be possible to predict the Subnet Range a specific namespace is gonna use, allowing the end user to configure external firewalls for example.

**Comment by zviratko** [comment]
Those POD CIDRs are not subnets, leased addresses are akin to /32. So just specify more CIDRs that don't overlap the range used outside of the cluster?

**Comment by camrossi** [comment]
@zviratko yeah I can do that for sure but is a bit "ugly" because if I set my subnet as a say /16 then I need to pass to Cilium config now a list of subnets:

This works: 
```
clusterPoolIPv4PodCIDRList="{10.52.0.0/17,10.52.128.0/18,10.52.192.0/19,10.52.224.0/20,10.52.240.0/21,10.52.248.0/22,10.52.252.0/23,10.52.254.0/24}"
```

But would be much nicer to be able to say something like this:

```
clusterPoolIPv4PodCIDRList=10.52.0.0/16
clusterPoolIPv4PodCIDRListReserved=10.52.255.0/24
```

And then Cilium would just ignore 10.52.255.0/24
