### ISSUE TITLE
Controller backed BPF map sync for global maps

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3161]
We have a lot of code which synchronizes state to BPF maps based on events. There is no error retry on failure. All of this code will benefit from a generic layer that does:

1. Run a controller to retry on failure to update/delete
2. Periodically verifies that the in-memory state matches the BPF map state
3. Provide status of updates via the controller status
4. Bump a revision on implementation of changes.

Phase 1:
- [x] Per endpoint maps (policy)

Phase 2:
- [x] Global maps (lxcmap, tunnelmap, ipcache, lbmap)

Per Endpoint Map Sync Design:
- [x] Split endpoint policy into realized and desired state
   - [x] Collect new policy map content on recalc instead of on the fly map updates => desired state
   - [x] Keep an in memory copy of what is in the BPF map => realized state
 - [x] Run a per endpoint controller (sync-bpf-policy) to continuously sync desired state to realized state 
   - [x] every 30 sec: dump policy map and derive new realized state
   - [x] If diff exists to desired state, apply desired state
   - [x] On change of desired state due to policy calc, calculate diff to realized state and commit it to BPF map
 - [x] Maintain a policy revision in the realized and desired state
   - [x] Desired state revision gets updated every time the desired state is calculate based on a policy revision in the repo
   - [x] Realized state revision gets update every time the desired state has been successfully synced to the datapath
    - [x] `e.policyRevision` may not be bumped until both desired and realized state have been bumped

**Comment by ianvernon** [comment]
I have some concerns with the "revision" aspects of the list of requirements above. We have multiple parts of the datapath that are updated separately, and with the introduction of controllers to realize desired datapath state, concurrently for a given endpoint:

* Proxy configuration (which is configured before an endpoint's program is compiled / inserted)
* Compilation of the actual BPF program for an endpoint
* Update of the PolicyMaps for a given endpoint

Currently, the PolicyMap for an endpoint is updated *before* its updated program is inserted ( see https://github.com/cilium/cilium/issues/3897 ). If we had #3897, we could do an atomic swap of the policy map right before the bumping of the revision number.

This leads me to ask whether we should block on bumping the revision number until the proxy configuration is realized, the policy maps have their desired state realized, and the program is inserted? To me, the datapath is either configured correctly for an endpoint or it is not; the revision should only be bumped once all three of the above requirements are met. @tgraf what do you think?

**Comment by ianvernon** [comment]
I'm moving the priority on this to 1.2 since we have completed the updates per-endpoint in the 1.1 release-window.

**Comment by tgraf** [comment]
a3b409cd704027ec37232b81fde3508ea92cd5c4 has introduced a local cache for the majority of BPF maps with automatic retries on insertion errors.
