### ISSUE TITLE
CFP: Egress-Gateway: Enable masquerade only on Egress Nodes

### ISSUE THREAD

**Issue by camrossi** [cilium/cilium#31634]
**Use case:**

Nodes and Pods sharing the same  L2 Network so masquerade is disabled.

**First test:**
Use a `CiliumNodeConfig` to enable `egress gateway` and `masquerade` only on the K8s nodes designated as egress. 
The other nodes do not have these features enabled. 

**Result**
The traffic originating from the PODs is not being egress-natted. I think is probably because only the nodes where the feature is enabled have a bfp egress list:

i.e. this is present only on the 2 enabled egress nodes in my cluster:
```
kubectl -n kube-system exec ds/cilium -- cilium-dbg bpf egress list
Source IP      Destination CIDR   Egress IP   Gateway IP
10.52.53.222   0.0.0.0/0          0.0.0.0     192.168.9.246
```
**Second test:**
Enable `egress gateway` on all the nodes without enabling `masquerade` and selectively enable `masquerade` on the designated egress nodes:

**Result**
Cilium Agent does not start with the following error: `egress gateway requires --enable-ipv4-masquerade=\"true\" and --enable-bpf-masquerade=\"true\"`

This is probably expected as before `CiliumNodeConfig` it made not much sense to have such a config but now that we can override config on a per node setting this could be a nice feature to have.

As a test I disabled this check in https://github.com/cilium/cilium/blob/main/pkg/egressgateway/manager.go#L188 and now my use case seems to be working fine while the rest of the connectivity on the cluster works as expected. 

***Behaviour***:
- PODs runnings on nodes where `masquerade` is disabled are coming out with the POD IP
- PODs runnings on nodes where `masquerade` is enabled are coming out with the NodeIP
- PODs running on any node in a namespace that is selected for the egress-gw via a `CiliumEgressGatewayPolicy` are coming out with the expected egresss-IP

This is clearly inconsistent but in such scenario I would expect the egress-gw nodes to be tainted so no pod is run there and are just dedicated to egress.

**Comment by julianwiedmann** [comment]
Alternatively, it might be an option to treat EGW as a "special" Masquerading mode. So that packets pass through the SNAT path, but we then apply *only* the EGW check [here](https://github.com/cilium/cilium/blob/e2e97f3e07843f568813f90500ba75b21c462b8b/bpf/lib/nat.h#L567).

**Comment by camrossi** [comment]
In my specific use case I do not want to SNAT the POD at all (unless they are selected by an `CiliumEgressGatewayPolicy `) since the POD subnet is routable in my network.

But perhaps I am misunderstanding what you are saying ?
