### ISSUE TITLE
Unable to join Cilium Slack

### ISSUE THREAD

**Issue by zviratko** [cilium/cilium#31639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium slack can'be joined as it doesn't allow generic email domains

### Cilium Version

xxx

### Kernel Version

xxx

### Kubernetes Version

xxx

### Regression

Apparently this needs a refresh from time to time :)

### Anything else?

Thanks :)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bartwitkowski** [comment]
Same here! Cannot join Cilium Slack with Google account :-(.

**Comment by squeed** [comment]
I reached out to @thebsdbox, please try again :-)

**Comment by zviratko** [comment]
Thanks!
Works on https://cilium.herokuapp.com/
Not sure if https://cilium.slack.com is supposed to work

**Comment by thebsdbox** [comment]
I can see people joining 👍

**Comment by julianwiedmann** [comment]
I believe you managed to join Slack by now? Closing.
