### ISSUE TITLE
sporadical "Cannot forward proxied DNS lookup" when Cilium Network Policy enabled

### ISSUE THREAD

**Issue by kamikaze** [cilium/cilium#31715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Once Cilium network policy applied (has toFQDN) I'm getting following errors sometimes: Cannot forward proxied DNS lookup. Once policies removed - no errors at all.

### Cilium Version

1.15.3

### Kernel Version

Linux 6.5.0-26-generic #26-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar  5 21:19:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.29.3+k3s1

### Sysdump

[cilium-sysdump-20240402-094320.zip](https://github.com/cilium/cilium/files/14832610/cilium-sysdump-20240402-094320.zip)

### Relevant log output

```shell
level=error msg="Cannot forward proxied DNS lookup" DNSRequestID=25283 
dnsName=my_magic.host.net. endpointID=2522 
error="failed to dial connection to 10.42.4.240:53: dial udp 10.42.4.234:51871->10.42.4.240:53: 
bind: address already in use"
identity=21257 ipAddr="10.42.4.234:51871" subsys=fqdn/dnsproxy
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
`51871` is the wireguard port, so I believe this is a dup of https://github.com/cilium/cilium/issues/31535. Please follow along there.
