### ISSUE TITLE
hostNetwork client can't reach backends in remote cluster via Global Service

### ISSUE THREAD

**Issue by GabMgt** [cilium/cilium#31718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello, I believe I have encountered a bug with Cilium global services:

When setting up a global service across two clusters, if a client with hostNetwork: true attempts to access this service, it can only reach pods within the same cluster.

Here's a simple way to reproduce this issue using two clusters with a cluster mesh setup:

(It's a patch of the official documentation: https://docs.cilium.io/en/latest/network/clustermesh/services/ to add `"hostNetwork": true` to the client pod)

```shell
CILIUM_VERSION=1.15.3
CLUSTER1=eu1
CLUSTER2=eu2
kubectl config use-context $CLUSTER1
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/${CILIUM_VERSION}/examples/kubernetes/clustermesh/global-service-example/cluster1.yaml
kubectl config use-context $CLUSTER2
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/${CILIUM_VERSION}/examples/kubernetes/clustermesh/global-service-example/cluster2.yaml
kubectl patch deployment x-wing --patch '{
  "spec": {
    "template": {
      "spec": {
        "hostNetwork": true,
        "containers": [
          {
            "name": "x-wing-container",
            "command": ["sleep","infinity"],
            "livenessProbe": null,
            "readinessProbe": null
          }
        ]
      }
    }
  }
}'
while true
do
  kubectl exec -ti deployment/x-wing -- curl $(kubectl get svc rebel-base -o jsonpath='{.spec.clusterIP}')
done
```

The expected output is:
```
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
...
```

But instead I have:
```
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
...
```

### Cilium Version

1.15.3

### Kernel Version

Linux [HOSTNAME] 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### Kubernetes Version

v1.29.3

### Sysdump

[eu1-cilium-sysdump-20240402-151051.zip](https://github.com/cilium/cilium/files/14837048/eu1-cilium-sysdump-20240402-151051.zip)
[eu2-cilium-sysdump-20240402-151126.zip](https://github.com/cilium/cilium/files/14837066/eu2-cilium-sysdump-20240402-151126.zip)

### Anything else?

Here are the complete list of setup commands:

```shell
CILIUM_VERSION=1.15.3
CLUSTER1=eu1
CLUSTER2=eu2

kubectl config use-context $CLUSTER1
helm  upgrade cilium cilium/cilium --install --version 1.15.3 \
--namespace kube-system                                      \
--set encryption.enabled=true                                \
--set encryption.type=wireguard                              \
--set cluster.name=eu1                                       \
--set cluster.id=1                                           \
--set etcd.enabled=true                                      \
--set ipam.operator.clusterPoolIPv4PodCIDRList=10.201.0.0/16 \
--set ipam.operator.clusterPoolIPv4MaskSize=24               \
--set etcd.enabled=true                                      \
--set etcd.ssl=true                                          \
--set "etcd.endpoints[0]=https://167.71.79.242:2379"          \
--set nodeinit.restartPods=true
kubectl scale --replicas 1 deployment cilium-operator

kubectl config use-context $CLUSTER2
helm  upgrade cilium cilium/cilium --install --version 1.15.3 \
--namespace kube-system                                      \
--set encryption.enabled=true                                \
--set encryption.type=wireguard                              \
--set cluster.name=eu2                                       \
--set cluster.id=2                                           \
--set etcd.enabled=true                                      \
--set ipam.operator.clusterPoolIPv4PodCIDRList=10.202.0.0/16 \
--set ipam.operator.clusterPoolIPv4MaskSize=24               \
--set etcd.enabled=true                                      \
--set etcd.ssl=true                                          \
--set "etcd.endpoints[0]=https://167.71.64.106:2379"          \
--set nodeinit.restartPods=true
kubectl scale --replicas 1 deployment cilium-operator

sleep 1m

cilium status --context $CLUSTER1
cilium status --context $CLUSTER2

cilium clustermesh enable --context $CLUSTER1 --service-type NodePort
cilium clustermesh enable --context $CLUSTER2 --service-type NodePort

sleep 1m

cilium clustermesh status --context $CLUSTER1 --wait
cilium clustermesh status --context $CLUSTER2 --wait

cilium clustermesh connect --context $CLUSTER1 --destination-context $CLUSTER2

cilium clustermesh status --context $CLUSTER1 --wait
cilium clustermesh status --context $CLUSTER2 --wait
```

If you need more information or tests, feel free to ask.
Thanks in advance. Have a great day.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
I've opened https://github.com/cilium/cilium/pull/31798 to explicit this limitation.

**Comment by GabMgt** [comment]
> Hi @GabMgt, when Cilium Kube Proxy Replacement is not enabled (as in this case), NodePort services, as well as ClusterIP services accessed from host-netns pods don't target backends from the remote clusters, because kube-proxy doesn't know about them. You can make global services accessible from host-netns pods enabling [SocketLB](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#socket-loadbalancer-bypass-in-pod-namespace) through:
> 
> ```
> helm upgrade ... \
>   --set socketLB.enabled=true \
>   --set socketLB.hostNamespaceOnly=true 
> ```

I confirm that the proposed solution fixes the issue.
Thank you a lot !
