### ISSUE TITLE
proxymap full (CT: Map insertion failed)

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#3172]
### Title

CT: Map insertion failed errors in `cilium monitor` output

### General Information

- Cilium version (run `cilium version`)
Client: 0.13.13 c31ac13 2018-03-08T21:15:13+01:00 go version go1.9 linux/amd64
Daemon: 0.13.13 c31ac13 2018-03-08T21:15:13+01:00 go version go1.9 linux/amd64
- Kernel version (run `uname -a`)
4.11.9-coreos
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
1.7
- Link to relevant artifacts (policies, deployments scripts, ...)

### How to reproduce the issue

1. `cilium monitor | grep -i drop`

**Comment by joestringer** [comment]
Issue is proxymap becoming full, log message shows up as conntrack update failure due to #3176.

We need to look at garbage-collection of proxymap entries.

**Comment by joestringer** [comment]
Two areas to follow up:
* [x] proxymap entries timeout is 1 day. Issue #3181 lowers this to 5 minutes.
* [ ] Use LRU for proxymap

**Comment by ashwinp** [comment]
The problem appears to be exclusively with kafka in this case.
```
root@ip-172-0-127-27:~# cilium bpf proxy list | grep 9092 | wc -l
8173
root@ip-172-0-127-27:~# cilium bpf proxy list | grep 9092 | grep 172.201.7.230 | wc -l
3445
root@ip-172-0-127-27:~# cilium bpf proxy list | grep 9092 | grep 172.203.242.54 | wc -l
4681
root@ip-172-0-127-27:~#```

**Comment by tgraf** [comment]
I think what we are seeing here is a massive number of sequential connections. The proxy layer does not remove the proxymap entry on connection closure, it relies on the GC.

LRU will relieve this but even better is to remove the proxymap entry when we close the connection on the proxy side.

**Comment by tgraf** [comment]
```
        go func() {
                time.Sleep(portReleaseDelay)

                // The cleanup of the proxymap is delayed a bit to ensure that
                // the datapath has implemented the redirect change and we
                // cleanup the map before we release the port and allow reuse
                proxymap.CleanupIPv4Redirects(r.ProxyPort)
                proxymap.CleanupIPv6Redirects(r.ProxyPort)

```

Is the portReleseDelay too long? We could clean up the proxymap sooner
