### ISSUE TITLE
Errors with VM and VLAN already configured

### ISSUE THREAD

**Issue by musklor** [cilium/cilium#31725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Errors just after the setup, because my vm has a vlan affected.
VM is blocked.
It's like a saturation.

### Cilium Version

1.15.3

### Kernel Version

5.14.21

### Kubernetes Version

1.28.8

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
I'm sorry, but to make progress here you'd need to actually provide any kind of information / data that describes the error.
Closing for now.
