### ISSUE TITLE
Failed regeneration files `XXXXX_next_fail` may stick around after regeneration

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3175]
In a recent bugtool output, I saw state directories for failed regenerations where the endpoint no longer exists.

https://github.com/cilium/cilium/blob/2b74d2e198a87a54763606399864374bb5b7326f/pkg/endpoint/policy.go#L846

When the endpoint is deleted, we should clean up this directory.

**Comment by ishantanu** [comment]
@joestringer Are you suggesting adding `os.RemoveAll(faildir)` in place of https://github.com/cilium/cilium/blob/acdbc0cb784c6328fc47411f3d8a83ad42067ecd/pkg/endpoint/policy.go#L907 in the below code:

https://github.com/cilium/cilium/blob/acdbc0cb784c6328fc47411f3d8a83ad42067ecd/pkg/endpoint/policy.go#L903-L909

**Comment by joestringer** [comment]
@iamShantanu101 not quite. That would completely get rid of the visibility on previous failures. 

The intention is that:
* If a build fails, the objects built that failed to be loaded should be moved to `foo_fail`
* Next time it succeeds, remove `foo_fail`
* Upon endpoint delete, remove `foo_fail`.

I think it's just the last case that is missing.

**Comment by ishantanu** [comment]
Understood. So, `failDir` needs to be removed when the endpoint program is successfully regenerated.

**Comment by joestringer** [comment]
@iamShantanu101  It is already unconditionally deleted upon regeneration (though the subsequent lines may re-create it upon failure):

https://github.com/cilium/cilium/blob/acdbc0cb784c6328fc47411f3d8a83ad42067ecd/pkg/endpoint/policy.go#L901-L902

It's the endpoint delete case that I believe is missing.

**Comment by ishantanu** [comment]
Okay. I am not sure where the endpoint delete condition needs to be put :/. Thanks @joestringer  for explaining the things, I'll try this maybe later if it's still open.
