### ISSUE TITLE
Cilium policy get missing from bugtool

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3177]
Add `cilium policy get` to debuginfo / bugtool

**Comment by ianvernon** [comment]
Should this be opt-in from the user side? I'm wondering if we want output of policy to be included by default, or if we can make such information opt-in by adding it to the config file passed into bugtool.

**Comment by joestringer** [comment]
We currently tell people in the documentation that if there's anything sensitive then they should vet the output before posting it somewhere public. IMHO it's pretty clear in the documentation, so I think it's worth including everything that's relevant for debug. Otherwise there ends up being a bunch of back-and-forth attempting to get all the information we need to dig into an issue.

**Comment by ianvernon** [comment]
`cilium policy get` is ran as part of `cilium debuginfo`, the output of which is stored in the archive created by `cilium-bugtool`:

```
$ cilium-bugtool
$ tar xvf /tmp/cilium-bugtool-20180325-012704.145+0000-UTC-468350841.tar
$ grep -A31 "Policy get" cilium-bugtool-20180325-012704.145+0000-UTC-468350841/cmd/cilium-debuginfo.md 
#### Policy get
:
 [
  {
    "endpointSelector": {
      "matchLabels": {
        "any:id.server": ""
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:id.client": ""
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "id",
        "value": "example",
        "source": "unspec"
      }
    ]
  }
]
Revision: 2
```

So, the contents are actually part of the bugtool, they are just in the output of `cilium-debuginfo`. Closing.
