### ISSUE TITLE
CFP: Enable direct Pod to RDS communication using Cilium and Security Groups

### ISSUE THREAD

**Issue by kahirokunn** [cilium/cilium#31778]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**
Currently, Cilium cannot natively integrate with AWS Security Groups when deployed on EKS or other Kubernetes clusters running on AWS. This makes it difficult to secure communication between Pods and AWS resources like RDS instances that are protected by Security Groups, without also using the AWS VPC CNI plugin.

**Describe the feature you'd like**
The proposed feature is to enable Cilium NetworkPolicies to reference AWS Security Groups in the egress rules. This would allow users to define which Security Groups a Pod should be able to communicate with, without the need for the VPC CNI plugin.

**Requirements:**
- Ability to specify AWS Security Group IDs in the `egress` rules of a Cilium NetworkPolicy
- Automatic creation and management of Security Groups based on the rules defined in NetworkPolicies
- Ensuring that the generated Security Group rules match the specified egress policies

**Proposed solution**
1. Introduce a new field `awsSecurityGroups` in the `egress` rule specification of Cilium NetworkPolicies. This field would accept a list of AWS Security Group IDs.
2. When a Cilium NetworkPolicy with `awsSecurityGroups` is applied, Cilium would create a new Security Group in AWS with rules that match the specified egress policies.
3. Cilium would then automatically assign this generated Security Group to the relevant Pods, enabling them to communicate with the specified AWS resources protected by the referenced Security Groups.
4. When the NetworkPolicy is updated or deleted, Cilium would update or delete the corresponding Security Group in AWS accordingly.

This solution would require Cilium to have the necessary permissions to create, update, and delete Security Groups in AWS. Additionally, it would need to periodically sync the Security Group rules with the defined NetworkPolicies to ensure consistency.

We recommend discussing this approach with the Cilium committers before implementation to ensure alignment with the project's goals and design principles.

**Comment by Alex-Waring** [comment]
Hi @kahirokunn, Cilium already supports to groups: https://docs.cilium.io/en/stable/security/aws/.

Is there any part of this that does not meet your requirements?

**Comment by kahirokunn** [comment]
@Alex-Waring 
I was not aware of that feature.
I will try it once.
Thx 🙏
