### ISSUE TITLE
Behavior Change between 1.10 and later versions - packets exiting via the interface they arrived on.

### ISSUE THREAD

**Issue by smerfy** [cilium/cilium#31794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a k8s node with 2 NICs

NIC1 - Default Gateway, k8s network.
NIC2 - Extra NIC, with External IP for BGP link network, External Traffic come in via this NIC.

I have a k8s cluster running Cilium 1.10.19, any traffic the comes in via NIC2 exits via NIC2
Why is this and what setting allows this? It appears to just do it, without needing to set anything special. I am looking to upgrade Cilium.

So I now have a k8s cluster running Cilium 1.13.14 (but have also tried 1.11.x).
Any Traffic that comes in via NIC2 exits via NIC1, which is expected tbh, as its the default gateway.
How can I make the new versions of Cilium act like the older version of Cilium in this respect?

### Cilium Version

old behavior - 1.10.19
new behavior - 1.11.13/1.13.14

### Kernel Version

5.15.0-97-generic

### Kubernetes Version

1.26.9

### Regression

1.10.19 acts in the old way
1.13.14 acts in the new way (also tested 1.11.13, which acts like 1.13)

### Sysdump

With 1.10, the config dump fails, so have attached some config information in the txt file.

[cilium-sysdump-20240405-100956.zip](https://github.com/cilium/cilium/files/14883610/cilium-sysdump-20240405-100956.zip)
[1.10.txt](https://github.com/cilium/cilium/files/14883613/1.10.txt)

### Relevant log output

```shell
n/a
```

### Anything else?

I tried enabling XDP on the newer Cilium, because XDP_TX sounds like it should do I am after, maybe.. But didn't appear to make any difference.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Did you check which devices are managed by Cilium on the newer release? For instance what `cilium status` gives you as
>KubeProxyReplacement:   Strict   [ens160 10.0.40.55 (Direct Routing), ens224 91.240.47.223]

If you're missing NIC2, this might require tuning the `--devices` option.

**Comment by smerfy** [comment]
Hi Julian,

Cheers for the quick response, iirc that option was the one thing I had to explicitly set in the 1.10 config to make the setup work.

The newer versions appear to be able to auto detect the extra interfaces (something they improved up on in 1.11, looking at the release notes). And a Cilium Status run one a pod appears to back this up:
KubeProxyReplacement:    Strict   [enp1s0 192.168.122.188, enp2s0 91.240.47.233]

However I have also tried done this explicitly, with: cilium config set devices "enp1s0 enp2s0".

The difference in NIC names, is that I have 2 side by side environments, one libvert and one VMWare (which I am binning) I get the same behavior in both and can easily swap Cilium versions if required.

Thanks
Rich

**Comment by zviratko** [comment]
This is exactly what I am asking for here
https://github.com/cilium/cilium/issues/31640

I believe something changed in the way host network stack is involved - I worked around the issue by using policy routing for now.

**Comment by zviratko** [comment]
btw if he was missing device in the datapath then ingress wouldn't work at all - the problem is the reply gets routed according to the host routing tables, while previously it just "got sent back" which would be a lovely feature to have (again)

**Comment by smerfy** [comment]
Thanks for the reply, yes I was able to work round the issue with policy routing. I was using Cilium BGP Control Plane rather than MetalLB, so good for both setups.

I also agree it would be good to have an option to re enable this via the Cilium config, as it was default behaviour pre 1.11, and I think it's the behaviour I would expect out the box.

To save anyone digging through the posts the work round was:
echo 20 cilium >> /etc/iproute2/rt_tables
ip route replace default via <BGP Peer> table cilium
ip rule add from <IP Pool> lookup cilium

Thanks
Rich
