### ISSUE TITLE
Pod fails when /proc/modules does not exists.

### ISSUE THREAD

**Issue by nate-42** [cilium/cilium#31795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I use a custom, in-house built, Linux kernel that does not have modules loading compiled in it. Everything is built-in. Thus, /proc/modules does not exist.
The cilium pods fails to initialize with the attached error message.
The parsing of modules.builtin was added thanks to this issue https://github.com/cilium/cilium/issues/23863. But this issue dealt with /proc/modules being empty, not absent.

To my (limited) comprehension this is related to this https://github.com/cilium/cilium/blob/v1.15.3/pkg/datapath/linux/modules/modules_linux.go#L147 where it fails if it can't read the file.
Maybe we could add a fallback mechanism as if /proc/modules does not exists it is not an issue if the builtin file is available ?

I would love to have this fix to avoid to compile modules support in my kernel.

Thanks for your great software !
Best regards, 

### Cilium Version

cilium-cli: v0.16.3 compiled with go1.22.1 on linux/amd64
cilium image (default): v1.15.2
cilium image (stable): v1.15.3
cilium image (running): 1.15.3

### Kernel Version

5.10 custom kernel

### Kubernetes Version

Client Version: v1.28.8+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8+k3s1

### Relevant log output

```shell
level=info msg=Starting subsys=hive
level=info msg="Started gops server" address="127.0.0.1:9890" subsys=gops
level=info msg="Start hook executed" duration="566.279µs" function="gops.registerGopsHooks.func1 (pkg/gops/cell.go:43)" subsys=hive
level=info msg="Establishing connection to apiserver" host="https://10.43.0.1:443" subsys=k8s-client
level=info msg="Connected to apiserver" subsys=k8s-client
level=info msg="Start hook executed" duration=5.076865ms function="client.(*compositeClientset).onStart" subsys=hive
level=info msg="Start hook executed" duration="53.323µs" function="authmap.newAuthMap.func1 (pkg/maps/authmap/cell.go:27)" subsys=hive
level=info msg="Start hook executed" duration="24.695µs" function="configmap.newMap.func1 (pkg/maps/configmap/cell.go:23)" subsys=hive
level=info msg="Start hook executed" duration="110.035µs" function="signalmap.newMap.func1 (pkg/maps/signalmap/cell.go:44)" subsys=hive
level=info msg="Start hook executed" duration="21.831µs" function="nodemap.newNodeMap.func1 (pkg/maps/nodemap/cell.go:23)" subsys=hive
level=info msg="Start hook executed" duration="61.67µs" function="eventsmap.newEventsMap.func1 (pkg/maps/eventsmap/cell.go:35)" subsys=hive
level=info msg="Start hook executed" duration="7.436µs" function="*resource.resource[*v1.Node].Start" subsys=hive
level=info msg="Start hook executed" duration="1.052µs" function="*resource.resource[*cilium.io/v2.CiliumNode].Start" subsys=hive
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.1.0.0/16
level=info msg="Local boot ID is \"cba0d6ae-7b2b-4e4c-a4e8-61367e2754bd\"" subsys=node
level=info msg="Start hook executed" duration=3.581064ms function="node.NewLocalNodeStore.func1 (pkg/node/local_node_store.go:95)" subsys=hive
level=info msg="Start hook executed" duration="6.581µs" function="*statedb.DB.Start" subsys=hive
level=info msg="Start hook executed" duration="10.661µs" function="hive.New.func1.2 (pkg/hive/hive.go:105)" subsys=hive
level=info msg="Start hook executed" duration="7.777µs" function="*cell.reporterHooks.Start" subsys=hive
level=info msg="Devices changed" devices="[ens192 ens224]" subsys=devices-controller
level=info msg="Start hook executed" duration="982.685µs" function="*linux.devicesController.Start" subsys=hive
level=info msg="Node addresses updated" device=ens192 node-addresses="10.255.200.1 (ens192)" subsys=node-address
level=info msg="Node addresses updated" device=ens224 node-addresses="10.13.37.1 (ens224)" subsys=node-address
level=info msg="Start hook executed" duration="116.297µs" function="tables.(*nodeAddressController).register.func1 (pkg/datapath/tables/node_address.go:210)" subsys=hive
level=info msg="Start hook executed" duration="501.259µs" function="*bandwidth.manager.Start" subsys=hive
level=error msg="Start hook failed" error="failed to retrieve loaded modules names: failed to open loaded modules information at /proc/modules: open /proc/modules: no such file or directory" function="modules.(*Manager).Start" subsys=hive
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nate-42** [comment]
Just bumping it to avoid the issue being closed.
It would great if it could be fixed, as the fix is not complicated.

Thanks in advance !

**Comment by aanm** [comment]
@nate-42 would you like to give a shot and submit a PR? Thank you

**Comment by Infinoid** [comment]
I just ran into the same issue, for the same reason.  (purpose-built kernel for k8s nodes)

**Comment by Infinoid** [comment]
For posterity: this was still an issue in cilium v1.17.6, but v1.18.0 seems to work fine without a `/proc/modules`.
