### ISSUE TITLE
Egress rules allow traffic to a FQDN if its IP is the same as a recently accessed allowed FQDN

### ISSUE THREAD

**Issue by angeladietz** [cilium/cilium#31803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a `CiliumNetworkPolicy` is applied to enforce egress rules, the policy allows traffic to be forwarded to domains which are not allowed by the egress rule if their IP is resolved to the same IP as a domain which is allowed by the egress rules.

For example, given the following network policy:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  creationTimestamp: "2024-04-04T20:18:39Z"
  generation: 12
  name: egress-test
  namespace: us-east-1
  resourceVersion: "476002"
  uid: 40c93d1d-9f69-4b2f-b546-3c3c4d4eeeb2
spec:
  egress:
  - toFQDNs:
    - matchPattern: my.domain.com
    toPorts:
    - ports:
      - port: "80"
      - port: "443"
  endpointSelector:
    matchLabels:
      app: myapp
```
and assume the IP `my.domain.com` points to is `1.2.3.4`, and there also exists another DNS entry for `my.second.domain.com` which also points to `1.2.3.4`. 

From within the pod this network policy is applied to, initially doing a `curl https://my.second.domain.com` will fail as expected, as the egress policy doesn't allow this FQDN. Then, running `curl https://my.domain.com` will succeed, also as expected since it is allowed by the egress rule. However, subsequently running another `curl https://my.second.domain.com` will succeed. 
This is unexpected, because the policy should still deny access to this domain since it is not specified in the egress policy. Hubble logs show it as a `policy-verdict:L3-L4 ALLOWED (TCP Flags: SYN)`, but it should still not be allowed via L7. The forwarding appears to reuse the `cilium identity` which was used for `my.domain.com`.

### Cilium Version

Client: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64

### Kernel Version

Linux ip-10-244-26-43.ec2.internal 5.10.199-190.747.amzn2.x86_64 #1 SMP Sat Nov 4 16:55:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.10", GitCommit:"b8609d4dd75c5d6fba4a5eaa63a5507cb39a6e99", GitTreeState:"clean", BuildDate:"2023-10-18T11:44:31Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.14-eks-b9c9ed7", GitCommit:"7c3f2be51edd9fa5727b6ecc2c3fc3c578aa02ca", GitTreeState:"clean", BuildDate:"2024-03-02T03:46:35Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
v1.12 is already end of life. Can you reproduce this with one of the supported versions? https://github.com/cilium/cilium?tab=readme-ov-file#stable-releases

**Comment by angeladietz** [comment]
Hi @lmb, I tried again on v1.15.3 and was able to reproduce the same issue on that version as well.
```
Client: 1.15.3 22dfbc58 2024-03-26T11:45:10+01:00 go version go1.21.8 linux/amd64
Daemon: 1.15.3 22dfbc58 2024-03-26T11:45:10+01:00 go version go1.21.8 linux/amd64
```

**Comment by gandro** [comment]
Thanks for the report! This is expected behavior. ToFQDN allowlists IPs, not domains, it's implicitly stated here: https://docs.cilium.io/en/stable/security/policy/language/#dns-proxy

This is fundamentally how Cilium 's ToFQDN implementation works. There is no inherent correlation between a DNS lookup and the subsequent TCP connection. The only correlation we have on the network layer is the IP, so that's what we use for allowlisting. The IP will be disallowed once the TTL of the DNS lookup expires.

@JamesLaverack explained this very nicely:
> Very briefly — the reasoning is that enabling a toFQDN proxy (with DNS capture) instructs Cilium to intercept udp/53 DNS requests and [proxy them through the Cilium agent](https://github.com/cilium/cilium/blob/67164a81724ba803899359a9281c907e97e10f70/pkg/fqdn/dnsproxy/proxy.go#L877). When the Cilium agent[ intercepts a DNS response](https://github.com/cilium/cilium/blob/67164a81724ba803899359a9281c907e97e10f70/pkg/fqdn/dnsproxy/proxy.go#L1069), it'll[ update it's DNS map](https://github.com/cilium/cilium/blob/67164a81724ba803899359a9281c907e97e10f70/daemon/cmd/fqdn.go#L256) (on that node) [to equate the IP address(s) returned in the ](https://github.com/cilium/cilium/blob/67164a81724ba803899359a9281c907e97e10f70/daemon/cmd/fqdn.go#L425)A[ and ](https://github.com/cilium/cilium/blob/67164a81724ba803899359a9281c907e97e10f70/daemon/cmd/fqdn.go#L425)AAAA[ records with the DNS name](https://github.com/cilium/cilium/blob/67164a81724ba803899359a9281c907e97e10f70/daemon/cmd/fqdn.go#L425) and eventually update policy in the dataplane.But, that's as smart as it is. The dataplane doesn't inspect the SNI header on the packet for a TLS connection or anything (and it couldn't anyway as toFQDN works at L3, so there's no requirement that the packet processed with toFQDN is a TLS or HTTP packet, it could be anything — random UDP for example).


I think we could improve the documentation here a bit, but I'll close this as "not planned" and add the "question" tag for now as a intermediate step.
