### ISSUE TITLE
Cilium 1.16.0-pre.1 breaks with VLAN interfaces containing dots

### ISSUE THREAD

**Issue by zviratko** [cilium/cilium#31813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Huge thanks to Dylan on Slack on taking a look at this one.

Dots are not allowed as per https://elixir.bootlin.com/linux/v6.8.4/source/kernel/bpf/inode.c#L370 in BPF FS.
Talos Linux in particular names intefaces like this, but lots of people do it too.

This breaking change was introduced in https://github.com/cilium/cilium/pull/28308

### Cilium Version

1.16.0-pre.1

### Kernel Version

 6.1.82-talos

### Kubernetes Version

Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3

### Regression

1.15.3 works
1.16.0-pre.0 also worked I think

### Relevant log output

```shell
time=“2024-04-06T10:53:41Z” level=warning msg=“JoinEP: Failed to load program for physical device eth0.1001" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=2 endpointID=577 error=“creating bpffs link dir for device eth0.1001: mkdir /sys/fs/bpf/cilium/devices/eth0.1001: operation not permitted” file-path=577_next/bpf_host.o identity=1 ipv4= ipv6= k8sPodName=/ subsys=datapath-loader veth=eth0.1001
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MTRNord** [comment]
I am seeing this on the 1.15.4 tag as well (which seems to be possibly incorrectly tagged? It seems to be actually an 1.16 release in disguise?)

**Comment by andrekloster** [comment]
I had the same problem when I upgraded Cilium from 15.3 to 15.4
I use Debian and the only workaround that worked was:
```
apt-get update && apt-get install -y vlan
```

```
# /etc/network/interfaces

auto eth0
iface eth0 inet manual

auto vlan1
iface vlan1 inet static
    address 192.168.1.10
    netmask 24
    gateway 192.168.1.1
    vlan-raw-device eth0
    pre-up ip link add link eth0 name vlan1 type vlan id 1
    post-down ip link delete vlan3
```

**Comment by dylandreimerink** [comment]
The same bug also exists on v1.15.4 since it was located in code that was backported in a patch version to facilitate graceful downgrades from v1.16 to v1.15. The fix has been backported in https://github.com/cilium/cilium/pull/32103 so v1.15.5 should work as expected.

**Comment by dylandreimerink** [comment]
> I'm not sure that it's related to cilium, looks like problem with bpffs itself

Well it is and it isn't. bpffs does not allow dots (`.`) since they are reserved and might get some special purpose in the future. So its up to Cillium to ensure we create out pin paths correctly.
