### ISSUE TITLE
Sending xDS response ... message is too verbose

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3183]
@rlenglet The below log seems a bit high log level, no?

https://github.com/cilium/cilium/blob/9e0db26f6c650a36bb4ffdfa1dadab34a1ed9395/pkg/envoy/xds/server.go#L385

**Comment by rlenglet** [comment]
I'm fixing this in https://github.com/cilium/cilium/pull/3131/commits/fd43e84bd702066ce7965d14321e590662b58387.
