### ISSUE TITLE
CI: Conformance Multi Pool IPAM

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#31845]
## CI failure

```
❌ Found 1 logs in kind-chart-testing/kube-system/cilium-jmrw5 (cilium-agent) matching list of errors that must be investigated:
time="2024-04-08T15:37:44Z" level=error msg="Failed to remove obsolete netdev programs" error="retrieving all netlink devices: interrupted system call" subsys=datapath-loader (1 occurrences)
```

Sysdump

[cilium-sysdump-out.zip.zip](https://github.com/cilium/cilium/files/14908888/cilium-sysdump-out.zip.zip)

Hit in - https://github.com/cilium/cilium/actions/runs/8602854754/job/23573362072

**Comment by chattytak** [comment]
I am using k0s. k8s version is 1.29.2.

`cilium install --version 1.15.3 --set "bgpControlPlane.enabled=true" --set "hubble.relay.enabled=true" --set "hubble.ui.enabled=true"`
and
`cilium connectivity test`

I would see the exact same error.

```
  ❌ Found 1 logs in k0s-cluster/kube-system/cilium-gxhls (cilium-agent) matching list of errors that must be investigated:
level=error msg="Failed to remove obsolete netdev programs" error="retrieving all netlink devices: interrupted system call" subsys=datapath-loader (1 occurrences)
```

**Comment by thorn3r** [comment]
Hit a similar failure in Conformance AWS-CNI:
```
  ❌ Found 1 logs in cilium-cilium-9021360157-2.us-east-1.eksctl.io/kube-system/cilium-7tnzl (cilium-agent) matching list of errors that must be investigated:
time="2024-05-09T19:13:05Z" level=error msg="Failed to remove obsolete netdev programs" error="retrieving all netlink devices: interrupted system call" subsys=datapath-loader (1 occurrences)
```
Workflow: https://github.com/cilium/cilium/actions/runs/9021360157
PR: https://github.com/cilium/cilium/pull/32353
Sysdump: 
[cilium-sysdumps.zip](https://github.com/cilium/cilium/files/15267197/cilium-sysdumps.5.zip)

**Comment by chancez** [comment]
Could we be hitting https://github.com/golang/go/issues/55243 here?

**Comment by jrajahalme** [comment]
Here too: https://github.com/cilium/cilium/actions/runs/10672218369/job/29579318216
