### ISSUE TITLE
CI: Ingress Conformance Test: `timed out waiting for convergence`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#31857]
From: https://github.com/cilium/cilium/actions/runs/8600119008/job/23564431646
[cilium-sysdump-out-Without_KPR.zip](https://github.com/cilium/cilium/files/14917513/cilium-sysdump-out-Without_KPR.zip)
```
  Scenario: An Ingress with a trailing slashes in a prefix path rule should ignore the trailing slash and send traffic to the matching backend service # features/path_rules.feature:181
    When I send a "GET" request to "http://trailing-slash-path-rules/aaa/bbb"                                                                          # feature.go:94 -> iSendARequestTo
    timed out waiting for convergence
    Then the response status-code must be 200                                                                                                          # feature.go:102 -> theResponseStatuscodeMustBe
    And the response must be served by the "aaa-slash-bbb-slash-prefix" service 
```

**Comment by giorio94** [comment]
Hit on https://github.com/cilium/cilium/pull/32568 (v1.15 backport)
Link: https://github.com/cilium/cilium/actions/runs/9109143762/job/25041387557

**Comment by giorio94** [comment]
Just hit a very similar one: https://github.com/cilium/cilium/actions/runs/9379774479/job/25825394365

```
Scenario: An Ingress with a trailing slashes in a prefix path rule should ignore the trailing slash and send traffic to the matching backend service # features/path_rules.feature:181
    When I send a "GET" request to "http://trailing-slash-path-rules/aaa/bbb" # features/path_rules.feature:184
      Error: timeout while waiting after 8 attempts, 0/3 sucessess
```

**Comment by giorio94** [comment]
Another hit: https://github.com/cilium/cilium/actions/runs/9451655491/job/26033121562

**Comment by thorn3r** [comment]
Another similar hit: https://github.com/cilium/cilium/actions/runs/9598147772/job/26468772176
PR: https://github.com/cilium/cilium/pull/33240
sysdump: [cilium-sysdump-out-With_Shared_LB.zip](https://github.com/user-attachments/files/15921167/cilium-sysdump-out-With_Shared_LB.zip)
