### ISSUE TITLE
Helm chart generates duplicate ConfigMap value

### ISSUE THREAD

**Issue by remi-gelinas** [cilium/cilium#31868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Enabling the `eni` integration and explicitly enabling `endpointRoutes` in the chart should be redundant, as `eni.enabled` will enable endpoint routing, but it looks like similar to #13999 the `enable-endpoint-routes` key in the resultant `ConfigMap` is not deduplicated.

Minimal reproduction:
```console
bash-5.2$ helm template cilium cilium/cilium --version 1.15.2 \
  --namespace cilium \
  --set endpointRoutes.enabled=true \
  --set eni.enabled=true > cilium-eni.yaml
bash-5.2$ yamllint -d relaxed --no-warnings cilium-eni.yaml
cilium-eni.yaml
  191:3     error    duplication of key "enable-endpoint-routes" in mapping  (key-duplicates)
  793:1     error    trailing spaces  (trailing-spaces)
  809:1     error    trailing spaces  (trailing-spaces)
```

### Cilium Version

1.15.2

### Kernel Version

N/A

### Kubernetes Version

N/A

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by remi-gelinas** [comment]
Similar to https://github.com/cilium/cilium/issues/13999#issuecomment-732656614, it's probably safest to just add a specific guard for `endpointRoutes.enabled` here to avoid specifying it twice, which seems safest: 
https://github.com/cilium/cilium/blob/d913b6298123064f51a8b97495f956b5ebbe62b7/install/kubernetes/cilium/templates/cilium-configmap.yaml#L502-L504

like so:

```yaml
 {{- if .Values.eni.enabled }} 
  {{- if not (and .Values.endpointRoutes .Values.endpointRoutes.enabled) }}
   enable-endpoint-routes: "true" 
  {{- end }}
   auto-create-cilium-node-resource: "true" 
...
```

**Comment by lmb** [comment]
@remi-gelinas thanks for diagnosing this, would you be interested in contributing a fix?

**Comment by lmb** [comment]
I'm not very familiar with our helm setup, but since you've found a precedent of how this was handled I don't see why this shouldn't work!
