### ISSUE TITLE
EKS Windows Nodes

### ISSUE THREAD

**Issue by jessectl** [cilium/cilium#31873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Getting this error while deploying cilium on EKS Windows nodes.

**Cilium Agent Daemonset**

```
`Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    63s                default-scheduler  Successfully assigned kube-system/cilium-k5cgk to ip-10-00-00-00.ec2.internal
  Warning  FailedMount  31s (x7 over 63s)  kubelet            MountVolume.SetUp failed for volume "hostproc" : hostPath type check failed: /proc is not a directory
  Warning  FailedMount  31s (x7 over 63s)  kubelet            MountVolume.SetUp failed for volume "host-proc-sys-net" : hostPath type check failed: /proc/sys/net is not a directory
  Warning  FailedMount  31s (x7 over 63s)  kubelet            MountVolume.SetUp failed for volume "host-proc-sys-kernel" : hostPath type check failed: /proc/sys/kernel is not a directory`
```

**Cilium Operator **
```
`Warning  FailedCreatePodSandBox  8s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1fedc2ea5e203862c2d32aab03d6af024dd1cc9514f5201359cd227e57057bae": plugin type="vpc-bridge" name="vpc" failed (add): failed to parse Kubernetes args: failed to get pod IP address cilium-operator-6775dcbcd5-sj6hl: error executing k8s connector: error executing connector binary: exit status 1 with execution error: pod cilium-operator-6775dcbcd5-sj6hl does not have label vpc.amazonaws.com/PrivateIPv4Address`
```

### Cilium Version

`1.14.7`

### Kernel Version

Windows Server 2022 Full

### Kubernetes Version

1.29

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
Are you trying to deploy the cilium agent to a Windows node?

**Comment by jessectl** [comment]
> Are you trying to deploy the cilium agent to a Windows node?

Yes!

**Comment by lmb** [comment]
Cilium doesn't support Windows :( Please take a look at https://docs.cilium.io/en/stable/operations/system_requirements/

**Comment by jessectl** [comment]
> Cilium doesn't support Windows :( Please take a look at https://docs.cilium.io/en/stable/operations/system_requirements/

Ah, okay, thank you! Hopefully in the future. Feel free to close this issue.
