### ISSUE TITLE
Bug: hubble-relay fails if there is a wildcard DNS entry and a DNS search domain on nodes

### ISSUE THREAD

**Issue by isaac-mcfadyen** [cilium/cilium#31898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

This is a bit of an obscure issue so took me a bit to troubleshoot. Hubble Relay fails to connect to `hubble-peer.kube-system.svc.cluster.local` with "context deadline exceeded" if you have a search domain defined on your nodes and you have a wildcard DNS record on that domain.

Specifically, the prerequisites that result in this issue:
- you have a search domain defined on the k8s nodes resolv.conf file (for example, `search example.com`).
- you have a wildcard record defined on that search domain (for example, `*.example.com` points somewhere, it doesn't seem to matter where).

As far as I can tell, when hubble-relay tries to connect to `hubble-peer.kube-system.svc.cluster.local`, the DNS query automatically has your search domain appended (like `hubble-peer.kube-system.svc.cluster.local.example.com`) and the lookup hits the wildcard record, which fails.

If you remove the wildcard or remove the search domain, things are immediately fixed because it's resolved in-cluster properly, leading me to believe that's the reason for this (as well as some quick in-cluster debugging with `dig` and `curl`).

I believe the issue is that it's not looking up the DNS record as a fully qualified name - i.e. the system DNS resolver is appending the search domain because `hubble-peer.kube-system.svc.cluster.local` does not end in a period (`.`).

## Steps to Reproduce
1. Spin up a k8s cluster. I'm using `k3s` and `coredns` but I believe any cluster will reproduce.
2. Add a search domain to each node's `/etc/resolv.conf` and ensure K8s DNS is using the system-defined resolv.conf (it should by default).
3. Add a wildcard DNS record for your chosen search domain (like `*.example.com`) pointing anywhere, doesn't matter where.
4. Finally, deploy Hubble Relay. Observe that Hubble Relay fails to connect to `hubble-peer.kube-system.svc.cluster.local` with "context deadline exceeded" because it's resolving the hostname to your wildcard record, trying to connect, and failing.

### Cilium Version

```
cilium-cli: v0.16.4 compiled with go1.22.1 on linux/amd64
cilium image (default): v1.15.3
cilium image (stable): v1.15.3
cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found
```

### Kernel Version

`Linux k8s-server 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: v1.28.8+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8+k3s1
```

### Regression

N/A

### Sysdump

[cilium-sysdump-20240411-131520.zip](https://github.com/cilium/cilium/files/14946560/cilium-sysdump-20240411-131520.zip)

### Relevant log output

```shell
level=info msg="Starting gRPC health server..." addr=":4222" subsys=hubble-relay
level=info msg="Starting gRPC server..." options="{peerTarget:hubble-peer.kube-system.svc.cluster.local:443 dialTimeout:5000000000 retryTimeout:30000000000 listenAddress::4245 healthListenAddress::4222 metricsListenAddress: log:0xc000351f80 serverTLSConfig:<nil> insecureServer:true clientTLSConfig:0xc000649800 clusterName:default insecureClient:false observerOptions:[0x1f0eba0 0x1f0ec80] grpcMetrics:<nil> grpcUnaryInterceptors:[] grpcStreamInterceptors:[]}" subsys=hubble-relay
level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target="hubble-peer.kube-system.svc.cluster.local:443"
level=info msg="Stopping server..." subsys=hubble-relay
level=info msg="Server stopped" subsys=hubble-relay
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aw1cks** [comment]
Good find! For anyone running into this, you can adjust the helm values to make the service domain name fully qualified:
```yaml
hubble:
  peerService:
    # Note the final `.` to make this fully-qualified
    # Adjust to match your cluster's domain as necessary
    clusterDomain: cluster.local.
```

**Comment by karelvanhecke** [comment]
I had two search domains defined on the nodes, no wildcard in either of them and ran into the hubble-relay failing to connect.
Removing the search domains fixed the issue.

As far as I can remember this didn't happen on Cilium 1.13. They changed the hubble-relay image since then (scratch -> distroless static-debian), which could be the culprit.

Cilium version: 1.15.4
Kubernetes: 1.29.4

**Comment by ilbarone87** [comment]
Having same issue here
Cilium version: 1.15.4
K8s version: v1.28.9+rke2r1

Tried to remove the search domain (lan) and set hubble clusterDomain to cluster.local. did not solve it for me

**Comment by ilbarone87** [comment]
@stelucz a good old restart of the nodes fixed it for me 😅😅

**Comment by cccsss01** [comment]
Restarting the node fixed it for me as well however, I don't find this sufficient.
