### ISSUE TITLE
Connectivity issue: not enough replicas

### ISSUE THREAD

**Issue by Aym3nTN** [cilium/cilium#31919]
Hi team, 
I ran into a situation where the `cilium connectivity test` failed with the below error because, when deploying the test deployments/pods, the autoscaler couldn't scale up the node count because there was no `resources.requests` set for that specific test deployment. 

Error: connectivity test failed: timeout reached waiting for deployment cilium-test/client2 to become ready (last error: only 0 of 1 replicas are available)

One other use case is when a podaffinity is set to one of the tests deployment and there is no room for an extra pod in the node where the scheduler wants to schedule the pod to satisfy the affinity which leads to having pods in pending state.

**Comment by rburrs** [comment]
Checkout this issue thread and see if it resolves your problem https://github.com/cilium/cilium/issues/30125

**Comment by Aym3nTN** [comment]
@rburrs not exactly the same issue as in mine the pod is stuck in pending status because it couldn't get scheduled whereas in https://github.com/cilium/cilium/issues/30125 in CrashLoopBackOff status

**Comment by lmb** [comment]
@Aym3nTN can you please follow the bug report issue template? You've not provided enough information to be able to diagnose this, sorry.
