### ISSUE TITLE
CFP: Forwarding ingress labels and annotations to dedicated controllers.

### ISSUE THREAD

**Issue by mvtab** [cilium/cilium#31927]
## Ingress controller labels and annotations

**Is your proposed feature related to a problem?**
When using the Cilium ingress controller in dedicated load balancer mode (the default mode), the created ingress controllers do not get the labels and annotations from the parent ingress resources. This makes it hard to manage the resource, as all the ingress controllers appear with only the label `cilium.io/ingress=true` and there is no way to apply selectors on specific ingress controllers, except manually adding the wished labels/annotations (which may not be persistent).  

**Describe the feature you'd like**
I would like the created dedicated ingress controllers to receive the same labels and annotations as the ingress resource that triggered their creation.

**Comment by chaunceyjiang** [comment]
Perhaps the `ingress-lb-annotation-prefixes` parameter could help you with that.

**Comment by mvtab** [comment]
That is great, thanks.

**Comment by mvtab** [comment]
That is great, thanks.
