### ISSUE TITLE
Unable to provision dev environment using Vagrant

### ISSUE THREAD

**Issue by ishantanu** [cilium/cilium#3192]
### Title

Unable to provision development environment using Vagrant

### General Information

While running `contrib/vagrant/start.sh`, the script ends abruptly.

The VM gets created but error is reported while the script runs.

Error description on running `start.sh`:
```
==> runtime1: Running provisioner: bootstrap (shell)...
    runtime1: Running: inline script
    runtime1: ----------------------------------------------------------------
    runtime1: Note: checking out '930a67cf7ba41b9d9436ad7a1be70a5d5ff6e1fc'.
    runtime1:
    runtime1: You are in 'detached HEAD' state. You can look around, make experimental
    runtime1: changes and commit them, and you can discard any commits you make in this
    runtime1: state without impacting any branches by performing another checkout.
    runtime1:
    runtime1: If you want to create a new branch to retain commits you create, you may
    runtime1: do so (now or later) by using -b with the checkout command again. Example:
    runtime1:
    runtime1:   git checkout -b <new-branch-name>
    runtime1:
    runtime1: HEAD is now at 930a67c... Fix pattern rule in repeated and map field (#58)
    runtime1: # generates the PGV binary and installs it into OPATH/bin
    runtime1: go install .
    runtime1: /tmp/vagrant-shell: line 13: unexpected argument `]]' to conditional binary operator
    runtime1: /tmp/vagrant-shell: line 13: syntax error near `;'
    runtime1: /tmp/vagrant-shell: line 13: `if [[ $(command -v bazel) && "$(bazel version | grep 'label' | cut -d ' ' -f 3)" =  ]]; then'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
It looks like something's causing this error while executing inline-scripts.

- Kernel version: Linux 4.4.0-116-generic

### How to reproduce the issue

1. Clone the repository on a new Ubuntu server
2. Install Vagrant and related packages
3. Run `contrib/vagrant/start.sh`

**Comment by eloycoto** [comment]
I can not reproduce.

**Comment by raybejjani** [comment]
Based on this error `]]' to conditional binary operator`, this might be a bash vs non-bash shell issue (I think `]]` is a bash construct). @eloycoto is that script running on the host?
@iamShantanu101 is your shell a bash? Could you share the version of Vagrant you're using, and the host ubuntu?

**Comment by eloycoto** [comment]
@iamShantanu101 This finally was fixed no?

**Comment by ishantanu** [comment]
@eloycoto Yes, it's working now. This can be closed.
