### ISSUE TITLE
Gateway spec.infrastructure.annotations field cannot hold more than 8 annotations

### ISSUE THREAD

**Issue by remi-gelinas** [cilium/cilium#31939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We're using the Gateway support in Cilium 1.15, and we're using the new `spec.infrastructure.annotations` field to specify a bunch of annotations to propagate to the generated `LoadBalancer` `Service` - some for generic metadata, and a lot to configure the NLB that is generated using the alb-controller.

This ends up being a fair amount of annotations to pass through, in our case 12. When going to apply the `Gateway` manifest, we're getting the following error on apply:

```
spec.infrastructure.annotations: Too many: 12: must have at most 8 items
```

Is there a hard limit of 8 annotations that can be passed through the `spec.infrastructure.annotations` field? If so, why is that? There are going to be a lot of cases where 8 is not sufficient.

### Cilium Version

1.15.2

### Kernel Version

N/A

### Kubernetes Version

1.28

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by remi-gelinas** [comment]
Actually, digging into the Gateway repo, this is not a Cilium issue but a shortcoming of the Gateway spec. See https://github.com/kubernetes-sigs/gateway-api/issues/2734

**Comment by dudicoco** [comment]
@remi-gelinas is there another way of configuring annotations as a workaround?

For example, istio passes the annotations set on the gateway to the service, envoy gateway allows setting service annotations via a custom resource: https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/#customize-envoyproxy-service-annotations
