### ISSUE TITLE
Add support for service.kubernetes.io/topology-mode annotation

### ISSUE THREAD

**Issue by gauravkghildiyal** [cilium/cilium#31948]
### Current behaviour

Cilium supports [Kubernetes Topology Aware Routing](https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/) through the annotation `service.kubernetes.io/topology-aware-hints`

As per [this](https://isovalent.com/blog/post/2021-12-release-111/#topology-aware-hints) blog post, the support has been available since Cilium v1.11

Other references regarding this feature: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#topology-aware-hints

### Desired behaviour

The annotation `service.kubernetes.io/topology-aware-hints` had been deprecated in favour of a new annotation `service.kubernetes.io/topology-mode` since Kubernetes 1.27, but Cilium does not recognize this new annotation. It seems to be a case where the Cilium dataplane has the code for the underlying feature but it does not get enabled when using this new annotation. It's desirable that Cilium starts recognizing this new annotation as well.

/kind feature
/sig k8s

**Comment by chaunceyjiang** [comment]
https://github.com/cilium/cilium/blob/4fe2fd31b1230a7b00f929661f31caff23ee98a7/pkg/k8s/service.go#L71-L78

Looks like it's already supported?

**Comment by gauravkghildiyal** [comment]
Thanks @chaunceyjiang! Seems like using Cilium >= 1.14 should get what I want.
