### ISSUE TITLE
Kubespray, Cilium ClusterMash not working

### ISSUE THREAD

**Issue by thejvmshid** [cilium/cilium#31945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!

### Cilium Version

v1.15.1

### Kernel Version

Linux a-t-os01k-m 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.28.6

### Anything else?

Guys, I have a one problem.
Please helm me solve it
I have a two clusters installed with Kubespray
And Im trying to aggregate the clusters to ClusterMash (as specified in https://docs.cilium.io/en/stable/network/clustermesh/clustermesh/)

![image](https://github.com/cilium/cilium/assets/35526267/688bc331-6d7f-423c-843e-53e5ec74f3d9)
![image](https://github.com/cilium/cilium/assets/35526267/ce46b00f-8cea-43c2-bf7d-8f2b65abb7ab)

But when I trying to install it, giving this error:

![image](https://github.com/cilium/cilium/assets/35526267/2bf9499e-67a2-4ac5-bd2c-10b74eeaf79b)

And if I skiping installation step and trying to enable ClusterMash, I recieving this error:
![image](https://github.com/cilium/cilium/assets/35526267/f6cf021a-360a-47b6-9a9f-9affa80e6f28)

How can I aggregate these two clusters to Mash, guys?

Thank you for advance 

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
Hey @thejvmshid,

How did you install Cilium? The Cilium CLI commands leverage helm for the installation process, and they do not work if Cilium got installed differently.
