### ISSUE TITLE
Cluster Mesh K3S / RKE2

### ISSUE THREAD

**Issue by didlawowo** [cilium/cilium#31957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!
i have two cluster, one in  k3S, other in RKE2. each installed with cilium latest version and four node

the step to activate clustermesh are well passed but with K3S i have svclb who give me 4 adresses 
when i try to connect cluster mesh, seems ok on rke2 side, but not on k3S side.

### Cilium Version

1.15.4

on k3S side
```
#!/bin/bash

CILIUM_VERSION="1.15.4"
helm repo add cilium https://helm.cilium.io/
helm upgrade --install cilium cilium/cilium --version=${CILIUM_VERSION} \
    --namespace kube-system \
    --set kubeProxyReplacement="true" \
    --set bpf.masquerade="true" \
    --set ingressController.enabled=false \
    --set ingressController.default=false \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set cluster.name="k3s" \
    --set cluster.id=1 \
    --set cni.chainingMode="none" \
    --set hubble.metrics.enableOpenMetrics=true \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" \
    --set encryption.enabled=true \
    --set encryption.type=wireguard

```

on rke2 side
```
#!/bin/bash

CILIUM_VERSION="1.15.4"
helm repo add cilium https://helm.cilium.io/
helm upgrade --install cilium cilium/cilium --version=${CILIUM_VERSION} \
    --namespace kube-system \
    --create-namespace \
    --set kubeProxyReplacement="true" \
    --set bpf.masquerade="true" \
    --set k8sServiceHost="127.0.0.1" \
    --set k8sServicePort="6443" \
    --set ingressController.enabled=false \
    --set ingressController.default=false \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set hubble.ui.ingress.enabled=true \
    --set cluster.name="rke2" \
    --set cluster.id=2 \
    --set hubble.metrics.enableOpenMetrics=true \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" \
    --set encryption.enabled=true \
    --set encryption.type=wireguard

```

### Kernel Version

rke2
Ubuntu 22.04.4 LTS   5.15.0-102-generic

k3s
Debian GNU/Linux 12 (bookworm)   6.6.20+rpt-rpi-2712 

### Kubernetes Version

1.27 k3S
1.29 RKE2

### Sysdump

to big :/

### Relevant log output

```shell
➜  rke2 git:(main) ✗ cilium clustermesh status --context $CLUSTER2 -n kube-system --wait
✅ Service "clustermesh-apiserver" of type "LoadBalancer" found
✅ Cluster access information is available:
  - 192.168.1.237:2379
✅ Deployment clustermesh-apiserver is ready
✅ All 4 nodes are connected to all clusters [min:1 / avg:1.0 / max:1]
🔌 Cluster Connections:
  - k3s: 4/4 configured, 4/4 connected
🔀 Global services: [ min:1 / avg:1.0 / max:1 ]


K3S side
✅ Service "clustermesh-apiserver" of type "LoadBalancer" found
✅ Cluster access information is available:
  - 192.168.1.21:2379
  - 192.168.1.23:2379
  - 192.168.1.24:2379
  - 192.168.1.25:2379
✅ Deployment clustermesh-apiserver is ready
⌛ Waiting (1s) for clusters to be connected: 4 nodes are not ready
⌛ Waiting (12s) for clusters to be connected: 4 nodes are not ready
```

### Anything else?

<img width="1475" alt="image" src="https://github.com/cilium/cilium/assets/12622760/74eaf145-de92-482e-ad09-10b69f9c1991">

<img width="1365" alt="image" src="https://github.com/cilium/cilium/assets/12622760/100fa02f-eb90-4be8-9374-99ada73e7f41">

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
Hi @didlawowo,

Could you verify whether you can curl `192.168.1.237:2379` from the RKE nodes? 
Could you please also share a sysdump of the two clusters?

**Comment by didlawowo** [comment]
i have review the configuration
now i'm using cilium L2 with k3S cluster instead off servicelb

i can finish the setup of cluster mesh, but i'm make the connect, i have lost the dns, all control plane where down

**Comment by didlawowo** [comment]
> Hmm, that's weird. A few questions to try to troubleshoot the issue:
> 
> * Are you able to capture a sysdump of both clusters? i can, but to big to post here 
> * Did the issue occur only after meshing the two clusters? after connecting the mesh, enabling is OK
> * Are the clusters configured with non-overlapping node/pod IPs? i the same network overlapping is not possible
> * Are you using Cilium to handle the LoadBalancer services? i did loadbalancer with cilium and metal lb
> * Is there any other service associated with the same IP? i don't think so
> * Does the DNS issue resolve if you manually edit the Cilium daemonset and remove the `HostAlias` section? i can't try it.

i have to rebuild the both cluster after this problem. so i can't go further because it's take a lot of time. and for me using the same network for thoses cluster i can now use gateway api to route traffic from on cluster to another 

i'm thinking cluster mesh with k3s and rke2 need some particular configuration which i don't have. as i say before when i have servicelb, mesh not working, i have to move to only one load balancer (disable klipper) to have connection, maybe some test and more documentation could help

**Comment by giorio94** [comment]
OK, I'm then closing this issue as it doesn't really contain enough information to reproduce and troubleshoot the underlying issue. Please feel free to reopen it if you encounter the same problem again.
