### ISSUE TITLE
Cilium cannot connect to AKS Private cluster api server.

### ISSUE THREAD

**Issue by nowjean** [cilium/cilium#31981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When helm installation in AKS Private Cluster (api server is not public), cilium pod cannot connect to api server.

```
level=error msg="Unable to contact k8s api-server"
```

If i create kube-proxy, cilium working correctly and then i remove kube-proxy, cilium still working corretly.
But when i scale out nodes, the new nodes remain NotReady Status because of 
```
NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
```

I think cilium pod cannot connect to private api server without kube-proxy pod. but after connection with api server through kube-proxy, it remain working correctly.

The problem is scale out node..

### Cilium Version

1.16.0-dev

### Kernel Version

Linux 5.15.0-1059-azure #67-Ubuntu SMP Sat Mar 9 03:28:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.27.7

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Just to confirm, you are seeing the connectivity issue only on the scaled out nodes?

How's cilium installed on the scale out nodes? Can you check if you are following the instructions to install cilium with kube-proxy replacement - https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#quick-start? More specifically, this note - 

`Make sure you correctly set your API_SERVER_IP and API_SERVER_PORT below with the control-plane node IP address and the kube-apiserver port number reported by kubeadm init (Kubeadm will use port 6443 by default).`
