### ISSUE TITLE
1.15.4 and 1.14.10 releases are missing

### ISSUE THREAD

**Issue by taraspos** [cilium/cilium#32023]
### Summary

[v1.15.4 tag](https://github.com/cilium/cilium/releases/tag/v1.15.4) and [image](https://quay.io/repository/cilium/cilium?tab=history) were published:

![image](https://github.com/cilium/cilium/assets/9948629/995ece94-c34b-497b-ada2-59bc0c23699a)

But release and changelog are missing. `1.15.3` is still marked as the latest one.

--- 
This is also applicable to 1.14.10

**Comment by joestringer** [comment]
Hi @taraspos , we were doing some additional testing behind the scenes before announcing the releases. They will be forthcoming. CC @asauber
