### ISSUE TITLE
Test flake: K8sValidatedPolicyTestAcrossNamespaces

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3203]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/1401/testReport/k8s-1/9/K8sValidatedPolicyTestAcrossNamespaces_Policies_Across_Namespaces/

```
home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:712
Unable to connect between frontend-qjbcs and 10.102.69.115:80/
Expected
    <string>: 000command terminated with exit code 7
    
to equal
    <string>: 200
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:855
```

**Comment by joestringer** [comment]
```
level=error msg="Cannot create CEP" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (29898)" endpointID=29898 error="the server could not find the requested resource (post ciliumendpoints.cilium.io)" policyRevision=0
```

**Comment by tgraf** [comment]
> level=error msg="Cannot create CEP" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (29898)" endpointID=29898 error="the server could not find the requested resource (post ciliumendpoints.cilium.io)" policyRevision=0

Is this causing the failure itself or is just an error in the log? The cause is pretty obvious.

**Comment by eloycoto** [comment]
Fixed by https://github.com/cilium/cilium/pull/3209
