### ISSUE TITLE
CFP: Improve KubeProxyReplacement status on cilium status command

### ISSUE THREAD

**Issue by gcezaralmeida** [cilium/cilium#32065]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

It is not a problem, but creates confusion while interpreting the cilium status command output. When we are using tunnels instead of native mode. Cilium status command prints (Direct Routing) on the KubeProxyReplacement field. 
Eg:
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.27 (v1.27.12+rke2r1) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True   [ens3   192.168.44.37 fe80::f816:3eff:fe57:7c52 **(Direct Routing)**]
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            portmap
Cilium:                  Ok   1.15.1 (v1.15.1-a368c8f0)
NodeMonitor:             Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 2/254 allocated from 10.42.3.0/24, 
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            BPF
Masquerading:            BPF   [ens3]   10.42.3.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       21/21 healthy
Proxy Status:            OK, ip 10.42.3.252, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 7.68   Metrics: Disabled
Encryption:              Disabled        
Cluster health:          6/6 reachable   (2024-04-18T20:24:49Z)
Modules Health:          Stopped(0) Degraded(0) OK(11) Unknown(3)

Helm values: 
bpf:
  hostLegacyRouting: false
  masquerade: true
k8sServiceHost: '127.0.0.1'
k8sServicePort: '6443'
kubeProxyReplacement: true
nodePort:
  enabled: true
routingMode: tunnel
socketLB:
  enabled: true
tunnelProtocol: geneve
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

**Describe the feature you'd like**

@joestringer requested the PR https://github.com/cilium/cilium/pull/32036 which will help to clarify if cilium is using native or tunnel mode. However, keeping "Direct Routing" on the KubeProxyReplacement field when using a routing-mode tunnel still creates misunderstanding. Do I still use a tunnel with Direct Routing together? 
Maybe there is a reason to have it, and we just need to clarify this with some docs. 

Thanks again @joestringer

**Comment by gcezaralmeida** [comment]
This is where we are adding the **(Direct Routing)** string.  https://github.com/cilium/cilium/blob/a6b8538908f448a962e19730c6a34ece7c1caa81/pkg/client/client.go#L331C1-L331C11.

**Comment by joestringer** [comment]
What I find confusing here is that my impression is that both "direct routing" and "native routing" are used interchangeably in Cilium to indicate routing directly via the natively-connected network. Traditionally you might call this the "physical" network, but when Cilium runs inside VMs it may be a virtual network outside of the node where Cilium runs.

The setting here seems to be indicating the status of the `direct-routing-device` configuration as it applies to the kube-proxy-replacement feature. So perhaps one angle to this issue is to answer the question: What does that setting mean?

From the agent help text, we see that the `direct-routing-device` means:
> Device name used to connect nodes in direct routing mode (used by BPF NodePort, BPF host routing; if empty, automatically set to a device with k8s InternalIP/ExternalIP or with a default route)

However, this presumably may not apply if the agent is configured with `routing-mode=tunnel`?
