### ISSUE TITLE
/var/run/cilium/proxy.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by tesharp** [cilium/cilium#32088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running cilium on AKS using the Cilium Enterprise extension. We have a few modifications, mainly enabling hubble and prometheus metrics. See helm config below.
This works fine at the start, until we deploy a l7 policy for dns. Once we do this then every node is spamming an error message 

`controller fqdn-rules-cache-controller is failing since 48s (80x): rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/cilium/proxy.sock: connect: no such file or directory"`. 

Before we apply l7 policy this controller is not running. 

Config:

```
      "hostFirewall.enabled": "true",
      "hubble.enabled": "true",
      "hubble.relay.enabled": "true",
      "hubble.ui.enabled": "true",
      policyEnforcementMode: "always",
      "endpointStatus.enabled": "true",
      "endpointStatus.status": "policy",
      // Adjust relevant labels for identities
      // https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#identity-relevant-labels
      "labels": "k8s:!azure.workload.identity/use k8s:!batch.kubernetes.io/controller-uid k8s:!batch.kubernetes.io/job-name k8s:!cdk8s.io/metadata.addr k8s:!controller-uid k8s:!job-name k8s:!workers.spacelift.io/run-id k8s:!workers.spacelift.io/worker",
      // Observability
      // See https://docs.cilium.io/en/stable/observability/metrics/
      "prometheus.enabled": "true",
      "prometheus.metrics": "", // Fails if not setting this..
      "operator.prometheus.enabled": "true",
      "operator.prometheus.serviceMonitor.enabled": "true",
      "hubble.relay.prometheus.enabled": "true",
      "hubble.relay.prometheus.serviceMonitor.enabled": "true",
      // Export hubble metrics
      "hubble.metrics.enabled[0]": "dns:query",
      "hubble.metrics.enabled[1]": "drop:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction",
      "hubble.metrics.enabled[2]": "tcp",
      "hubble.metrics.enabled[3]": "flow",
      //"hubble.metrics.enabled[4]": "port-distribution",
      "hubble.metrics.enabled[4]": "icmp",
      "hubble.metrics.enabled[5]": "httpV2:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction",
      "hubble.metrics.enabled[6]": "kafka:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction",
      "hubble.metrics.enabled[7]": "",
      "hubble.metrics.enableOpenMetrics": "true",
      // Fix for unable to reach api server
      "k8sServiceHost": this.privateFqdn,
      "k8sServicePort": "443",
      "localRedirectPolicy": "true",
```

### Cilium Version

1.13.14-cee.1

### Kernel Version

Linux aks-spotv1-40209052-vmss000000 5.15.0-1059-azure #67-Ubuntu SMP Sat Mar 9 03:28:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.27 - 1.29.2

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hi @tesharp thank you for opening the GH issue. That version is not from a Cilium OSS release. I would suggest to contact the vendor that provided you with that release for support. Thank you.
