### ISSUE TITLE
EKS: connectivity disruption after node restart

### ISSUE THREAD

**Issue by MoneshKumar** [cilium/cilium#32083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After installing Cilium helm chart, tried restarting the EKS nodes, and could see some of the pods are going into crashloopbackoff. Also facing the same issue when I try to uninstall and re-install few other helm charts. And this is happening with some random pods, not with same pods everytime.
Would need some help.

### Cilium Version

1.15.2

### Kernel Version

5.10

### Kubernetes Version

1.28

### Anything else?

Some of the errors I could see in few random pods are as below,
```
error while trying to communicate with apiserver
failed to get restmapping: failed to get server groups
failed to request new Vault token
failed to create vault clienttimeout
Error: ec2 metadata is not available
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Please attach a sysdump. 

>After installing Cilium helm chart, tried restarting the EKS nodes, and could see some of the pods are going into crashloopbackoff. 

Did you check `kubectl describe pod <cilium-pod>` to see what the problem was?

**Comment by MoneshKumar** [comment]
[cilium-sysdump-20240424-ip-10-0-0-31.zip](https://github.com/cilium/cilium/files/15090396/cilium-sysdump-20240424-ip-10-0-0-31.zip)
Thank you for the response. Attached sysdump of one of the nodes, where one of the "apigov-efk-prometheus-elasticsearch-exporter" pods got failed when I tried re-installing this chart.

Cilium pods are working fine, no error or issue found in the cilium pod logs. There are other helm charts deployed in my cluster like prometheus, kibana, elasticsearch, etc.
So, after installing the cilium helm chart, tried restarting all these other pods. And then tried deleting and re-installing some of these charts multiple times. For example, tried deleting and re-installation of Prometheus chart, and this helm deployment is getting failed some times with few of these promethues pods going into crashloopbackoff. This is happening very randomly, with random charts. Some times could not able to replicate this issue with same chart as well.

Some of the errors I could see in few random pods are as below. However after helm deployment of respective chart if I restart them again manually by deleting the pod, they are coming up healthy.

**Pod:** ebs-csi-node-fpbkw
`Error: ec2 metadata is not available`

**Pod:** rabbitmq
`Back-off restarting failed container volume-permissions in pod rabbitmq-0_infra-services`

**Pod:** falco-k8s-metacollector-56f6bf4c9c-dqbpd
`failed to determine if \*v1.Pod is namespaced: failed to get restmapping: failed to get server groups: Get "https://172.20.0.1:443/api`

**Pod:** fluent-bit
```
[ warn] Temporary failure in name resolution
[error] kubelet upstream connection error
```

**Pod:** appdynamics-operators-appdynamics-cloud-operator
`Failed to fetch kubernetes version      {"error": "Get \"https://172.20.0.1:443/version\": dial tcp 172.20.0.1:443: connect: connection refused"}`

**Pod:** apigov-efk-fluent-bit
```
level=error msg="failed to request new Vault token" app=vault-env err="context deadline exceeded"
level=fatal msg="failed to create vault clienttimeout [30s] during waiting for Vault token" app=vault-env
```

**Pod:** prometheus-operator-kube-state-metrics
`"Failed to run kube-state-metrics" err="failed to create client: error while trying to communicate with apiserver: Get \"https://172.20.0.1:443/version\": dial tcp 172.20.0.1:443: connect: connection refused" ` 

**Note:** Without having Cilium in my cluster, all these scenarios are working fine. Could able to re-install any chart any time without any failures or error logs.

**Comment by MoneshKumar** [comment]
issue got fixed, when I use cilium chaining with default AWS-VPC-CNI in my eks cluster and disabling eni for cilium. Thank you.
