### ISSUE TITLE
CFP: Hubble DNS config option for response IPs

### ISSUE THREAD

**Issue by huntergregory** [cilium/cilium#32096]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

No

**Describe the feature you'd like**

Proposing the option to configure Hubble to include metadata for DNS response IPs, e.g.:
```
hubble_dns_responses_total{response="10.0.0.1,8.4.4.8", ...}
```

With a [Hubble configuration](https://docs.cilium.io/en/stable/observability/metrics/#hubble) option for DNS like:
```yaml
hubble-metrics: dns:response_ips
```

The DNS response IPs are already being sent to Hubble (see "Existing Code" section below).

**(Optional) Describe your proposed solution**

- Create Hubble DNS config option.
- Add label to `hubble_dns_responses_total` Prometheus metric.
  - Set label using data already present in `Flow`.

**Existing Code: Response IPs sent to Hubble**

The response IPs are part of the Flow proto used in Hubble:
https://github.com/cilium/cilium/blob/302a8b12fb6e05d505d79de1aac9c7141f055324/api/v1/flow/flow.proto#L593-L598

which is mapped from `LogRecordDNS`:
https://github.com/cilium/cilium/blob/302a8b12fb6e05d505d79de1aac9c7141f055324/pkg/hubble/parser/seven/dns.go#L16

DNS response IPs are included in the `LogRecordDNS` for the `MessageTypeAccessLog` payload sent as an `AgentEvent` to Hubble's parser. The code flow is:
https://github.com/cilium/cilium/blob/302a8b12fb6e05d505d79de1aac9c7141f055324/daemon/cmd/fqdn.go#L459-L474

https://github.com/cilium/cilium/blob/302a8b12fb6e05d505d79de1aac9c7141f055324/pkg/proxy/logger/logger.go#L221-L233

https://github.com/cilium/cilium/blob/302a8b12fb6e05d505d79de1aac9c7141f055324/pkg/proxy/logger/monitoragent_lognotifier.go#L21-L22

https://github.com/cilium/cilium/blob/302a8b12fb6e05d505d79de1aac9c7141f055324/pkg/hubble/parser/parser.go#L144-L152

**Comment by rolinh** [comment]
Hi :wave: 
This _could_ easily be implemented but I'm worried about metrics cardinality. At the very least, it'll need to be opt-in and not a default option when enabling Hubble metrics.

**Comment by huntergregory** [comment]
> Hi 👋 This _could_ easily be implemented but I'm worried about metrics cardinality. At the very least, it'll need to be opt-in and not a default option when enabling Hubble metrics.

Thanks for taking a look! I agree, this should be optional and off by default
