### ISSUE TITLE
Cilium LB DSR reply with wrong src ip when syn packet is missed.

### ISSUE THREAD

**Issue by spal-x** [cilium/cilium#32091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In our cluster we run cilium 1.13.2 and observe the following situation (also reproduced when testing 1.15.2).
We have KPR with Direct Server Return (DSR) with IPv4 option / IPv6 extension Header, launched with next options:
` --set routingMode=native \
 --set kubeProxyReplacement=true \
 --set loadBalancer.mode=dsr \
 --set loadBalancer.dsrDispatch=opt \`
Pod A and Pod B belong to the same deployment. Pod A and Pod B run on different nodes in cluster (Pod A on node A, Pod B on node B).
LB1 serves connections from outside the cluster to these pods.
Lb1 => pod A (active)
       => pod B (active)
1. Client establish a connection to the LB1 IP.
2. This connection is redirected to one of pods, for example Pod A on node A, information about service IP/port contained in Cilium-specific IPv4 Option **(but only for SYN packet)**
3. Reply from Pod A correctly SNATed with LB1 IP.
4. The connection between the client and Pod A is established correctly.
5. For some reason node A lost network, so cilium removes pod A from the list of LB1 backends.
Lb1 => pod B (active)
7. Client continues to send data on the established connection 
8. This packet now is redirected to the Pod B on node B.
9. Since node B did not receive SYN packet with information about service IP/port, answers from pod B will not be SNATed and client receive answer from pod B  with src_ip of pod B and will obviously ignore them.

In the situation described above, we will get a long downtime for the client (depends on the client`s network stack settings).
Is it possible to add a parameter for adding information about service IP/port in each packet?

### Cilium Version

1.13.2 (also observe same situation in 1.15.2)

### Kernel Version

Linux hostA 5.14.0-168.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 23 11:43:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.27.1

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spal-x** [comment]
Found a similar one issue https://github.com/cilium/cilium/issues/27730 but no fix.

**Comment by aditighag** [comment]
It looks like you are looking for the alternate mode for DSR - https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#direct-server-return-dsr-with-ipv4-option-ipv6-extension-header. Have you tried this out?

**Comment by spal-x** [comment]
> It looks like you are looking for the alternate mode for DSR - https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#direct-server-return-dsr-with-ipv4-option-ipv6-extension-header. Have you tried this out?

Thanks for answer. Yes, we have configured our cluster according to the documentation https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#direct-server-return-dsr-with-ipv4-option-ipv6-extension-header
`
--set routingMode=native \ --set kubeProxyReplacement=true \ --set loadBalancer.mode=dsr \ --set loadBalancer.dsrDispatch=opt \
`
Additionally, I attach the output of 
` cilium config --all -oyaml `
[cilium config all.yaml.txt](https://github.com/cilium/cilium/files/15047664/cilium.config.all.yaml.txt)

**Comment by acelinkio** [comment]
I think this issue might be somewhat related to the problems that I have been seeing with the ingress/gateways.  Definitely have seen the dropped packets previously.  https://github.com/cilium/cilium/issues/29928#issuecomment-1931329269

I was provided a ingress/gateway workaround by relying less on BPF with a CI image.  https://github.com/cilium/cilium/issues/20942#issuecomment-2050822038.

**Comment by spal-x** [comment]
Any info?

**Comment by aditighag** [comment]
>For some reason node A lost network, so cilium removes pod A from the list of LB1 backends.
Lb1 => pod B (active)
Client continues to send data on the established connection
This packet now is redirected to the Pod B on node B.

When the pod A was removed, and pod B was chosen as a backend, a new SYN packet would be sent out, no?

**Comment by spal-x** [comment]
> > For some reason node A lost network, so cilium removes pod A from the list of LB1 backends.
> > Lb1 => pod B (active)
> > Client continues to send data on the established connection
> > This packet now is redirected to the Pod B on node B.
> 
> When the pod A was removed, and pod B was chosen as a backend, a new SYN packet would be sent out by the client. Are you saying that this may take a while since the client never receives a RST packet, and so eventually times out?
No, the client should not resend the SYN packet. Session established, neither side (client or pod) closed the session. As a result, we get a situation where the client will consider the session established until the timeouts expire.
> 
> > Since node B did not receive SYN packet with information about service IP/port, answers from pod B will not be SNATed and client receive answer from pod B with src_ip of pod B and will obviously ignore them.
> 
> This is expected since pod B never received a SYN so there is no TCP established.
Yes, this is true, but it gives us a traffic blackhole situation.
I would like to understand the position of contributors whether this situation is normal?

**Comment by spal-x** [comment]
> > For some reason node A lost network, so cilium removes pod A from the list of LB1 backends.
> > Lb1 => pod B (active)
> > Client continues to send data on the established connection
> > This packet now is redirected to the Pod B on node B.
> 
> When the pod A was removed, and pod B was chosen as a backend, a new SYN packet would be sent out by the client. Are you saying that this may take a while since the client never receives a RST packet, and so eventually times out?

No, the client should not resend the SYN packet. Session established, neither side (client or pod) closed the session. As a result, we get a situation where the client will consider the session established until the timeouts expire.

> This is expected since pod B never received a SYN so there is no TCP established.

Yes, this is true, but it gives us a traffic blackhole situation.
I would like to understand the position of contributors whether this situation is normal?

**Comment by aditighag** [comment]
> Main question is: is it possible to somehow force cilium to send information about LB IP and LB PORT in every packet or it requeires enhancments?

This has MTU related implications, so it's not supported in cilium.

**Comment by spal-x** [comment]
> > Main question is: is it possible to somehow force cilium to send information about LB IP and LB PORT in every packet or it requeires enhancments?
> 
> This has MTU related implications, so it's not supported in cilium.

What about this feature in DSR with Geneve? In this case we already assume some overhead.

**Comment by spal-x** [comment]
Any info?

**Comment by Olichous** [comment]
Still reproducible on `main` (checked at v1.20.0-pre.4). I've opened a draft PR with a fix:
https://github.com/cilium/cilium/pull/47020 — and it's the same underlying issue as #27730.

On the point that stalled this thread — *"this has MTU related implications, so it's not
supported"* — that's addressable for **Geneve** dispatch specifically: the option's 12 bytes are
already reserved **unconditionally** by `DsrTunnelOverhead` in `pkg/mtu`, whether or not the option
is actually attached. So attaching it to a non-SYN packet does **not** change the effective MTU.

The PR takes the conservative route anyway: it attaches the DSR info only to the one non-SYN packet
that *creates* the CT service entry on a new LB node (the mid-flow re-route case you hit), so there
is **zero** extra wire cost in steady state. A simpler "attach on every packet" variant is also
described for comparison; for Geneve neither variant moves the MTU budget.

Also worth underscoring from your report: **nothing is dropped** — no `cilium monitor` drop event,
no `cilium_drop_count_total` — the reply is simply mis-sourced and silently ignored by the client,
so it's invisible to the usual tooling. Happy to share anonymized cross-node captures.
