### ISSUE TITLE
lb ip is deleted accidentally in statedb when l2announce, requestip and shardingkeys are used together

### ISSUE THREAD

**Issue by wutz** [cilium/cilium#32115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. enable l2announce
2. create multiple services with same annotations `io.cilium/lb-ipam-ips` and `io.cilium/lb-ipam-sharing-key`
3. delete some services
4. execute `cilium-dbg statedb l2-announce` to see the ip is missing

### Cilium Version

1.15.3

### Kernel Version

5.15.0-102-generic

### Kubernetes Version

v1.28.7+k3s1

### Regression

Bug

### Sysdump

https://drive.google.com/file/d/1C3Y-glpgfJ0efHDFfr5TqO5hI4KOkWar/view?usp=drive_link

### Anything else?

When creating multiple services using the same IP, you can still see the IP listed multiple times in the statedb on multiple nodes.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashertz-dev** [comment]
+1
