### ISSUE TITLE
Virtual Machine eth0 is InternalIP, nodeipam cannot access it through the external IP

### ISSUE THREAD

**Issue by w7team** [cilium/cilium#32133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the eth0 of the virtual cloud host only has an internal IP and the external IP is forwarded in, there is a bug in nodeipam, and SVC cannot access it through the external IP.
Internal network IP: 10.0.72.46, which is bound to the eth0 network card.
External IP: 118.255.15.25, which is directly forwarded by the external router to the internal IP and is not bound to the network card.

```
[root@VM-72-46-centos ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 52:54:00:6c:cc:c7 brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    altname ens5
    inet 10.0.72.46/18 brd 10.0.127.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe6c:ccc7/64 scope link 
       valid_lft forever preferred_lft forever
10: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 46:67:34:c4:bf:67 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::4467:34ff:fec4:bf67/64 scope link 
       valid_lft forever preferred_lft forever
11: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 86:0a:2d:68:a1:b2 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.35/32 scope global cilium_host
       valid_lft forever preferred_lft forever
    inet6 fe80::840a:2dff:fe68:a1b2/64 scope link 
       valid_lft forever preferred_lft forever
12: cilium_vxlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 1e:26:40:7f:37:2c brd ff:ff:ff:ff:ff:ff
    inet6 fe80::1c26:40ff:fe7f:372c/64 scope link 
       valid_lft forever preferred_lft forever

```

**false：**
```
curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | K3S_KUBECONFIG_MODE='644' INSTALL_K3S_SKIP_SELINUX_RPM=true INSTALL_K3S_SELINUX_WARN=true 
sh -s - --write-kubeconfig-mode 644 \
--tls-san "118.25.145.25" \
--node-external-ip "118.25.145.25" \
--flannel-backend "none" \
--disable-network-policy \
--disable-kube-proxy \
--disable "servicelb,local-storage"
```

```
kube-system       traefik                       LoadBalancer   10.43.41.97     118.25.145.25   80:31556/TCP,443:30912/TCP   28s
```

```
[root@VM-72-46-centos ~]# curl 118.25.145.25
curl: (7) Failed to connect to 118.25.145.25 port 80: Connection refused
[root@VM-72-46-centos ~]# curl 10.0.72.46
curl: (7) Failed to connect to 10.0.72.46 port 80: Connection refused
[root@VM-72-46-centos ~]# curl 127.0.0.1
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused
```

﻿**right：**
```
curl -sfL https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh | K3S_KUBECONFIG_MODE='644' INSTALL_K3S_SKIP_SELINUX_RPM=true INSTALL_K3S_SELINUX_WARN=true 
sh -s - --write-kubeconfig-mode 644 \
--flannel-backend "none" \
--disable-network-policy \
--disable-kube-proxy \
--disable "servicelb,local-storage"
```

```
kube-system       traefik                           LoadBalancer   10.43.228.101   10.0.72.46    80:32469/TCP,443:30104/TCP   14m
```

```
[root@VM-72-46-centos ~]# curl 127.0.0.1
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused
[root@VM-72-46-centos ~]# curl 118.25.145.25
404 page not found
[root@VM-72-46-centos ~]# curl 10.0.72.46
404 page not found
```

This pattern is common on virtual cloud hosts created by KVM, and we hope to consider the issues arising from this scenario.

### Cilium Version

1.16.0-pre.1

### Kernel Version

centos 9

### Kubernetes Version

v1.29.1+k3s2 

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrFreezeex** [comment]
Hi! I don't think that we could do much in the scenario you described :/. If the external IP is advertised, Cilium will only detect the external IP and that's about it but in your case the actual IP that Cilium see is the internal IP so it won't get load balanced properly... So as is I am not really sure if there would be a good way to fix that...

Otherwise you could not use nodeipam and use hostport or if you are still interested in getting the IP correctly advertised in the service loadbalancer/ingress (for instance to get stuff like externaldns working) you could use an hostPort + nodeipam with externalIP. This means that external IP will get advertised but effectively the internal IP will be used for load balancing. It's not pretty but it should work I believe.

**Comment by w7team** [comment]
When installing a k3s cluster, setting `--node-external-ip` is a common scenario. For example, if I need to form an edge cluster across regions, this setting is necessary. I feel that regardless of whether `--node-external-ip` is set or not, `internal IP` and `127.0.0.1` should be allowed for communication

**Comment by MrFreezeex** [comment]
NodeIPAM only works at the "cluster" (operator) level right now and reporting all those IPs inside the service directly is not right because those IP can be picked up by other tools like ExternalDNS for instance.

So what I would see as a fix (or rather feature enhancement) is probably something in the agent that detect NodeIPAM's service load balancer, detects that it is for the same node, ignore the IP already advertised and advertise all his IPs instead. I don't think I will be able to take a look at implementing this soon, but if anyone else wants to take a look at enhancing nodeipam features to do that feel free.

**Comment by w7team** [comment]
Most cloud servers in IDCs currently use a solution where external SLB forwards to the cloud server’s internal IP. The cloud server itself cannot directly obtain the public IP provided by the SLB. Therefore, when installing k3s, we use the --node-external-ip parameter to solve the problem of obtaining public IPs within the cluster. Currently, due to the characteristics of NodeIPAM, we have to abandon the --node-external-ip configuration and use --advertise-address as a substitute. k3s’s servicelb does not have this problem. It is hoped that this use case can be given more consideration.

**Comment by MrFreezeex** [comment]
> Most cloud servers in IDCs currently use a solution where external SLB forwards to the cloud server’s internal IP. The cloud server itself cannot directly obtain the public IP provided by the SLB. Therefore, when installing k3s, we use the --node-external-ip parameter to solve the problem of obtaining public IPs within the cluster. Currently, due to the characteristics of NodeIPAM, we have to abandon the --node-external-ip configuration and use --advertise-address as a substitute. k3s’s servicelb does not have this problem.

Did you try the suggestion I wrote in https://github.com/cilium/cilium/issues/32133#issuecomment-2070760399?

> It is hoped that this use case can be given more consideration.

Well I have now this in mind but my time is not unlimited + I feel like it's closer to a feature enhancement than a bug so no guarantee that I will be able to tackle it before the Cilium 1.16 release. I definitely want to have this implemented though.

**Comment by w7team** [comment]
Thank you for your understanding of the issue I raised, and I sincerely hope that this issue will not be closed.
