### ISSUE TITLE
wireguard: Enable DSR encryption of LB forwarded packets with IPIP/Geneve

### ISSUE THREAD

**Issue by brb** [cilium/cilium#32180]
Currently, WG cannot encrypt LB DSR packets. The src IP of the forwarded DSR packet is the one from the original client (outside cluster). Such a request cannot be forwarded by WG, as it drops packets if the IP does not belong to WG's allowed peer IPs.

However, when DSR is used with IPIP or Geneve, the src IP addr of the outer packet is of the LB node. Therefore, we could encrypt such packets. This requires extending the check introduced by https://github.com/cilium/cilium/pull/30240/files.

**Comment by julianwiedmann** [comment]
For DSR-Geneve - shouldn't `to-netdev` observe & handle this the same way as our "normal" overlay traffic? And end up in this code path:
https://github.com/cilium/cilium/blob/6e9c1c7ac2889e9cae79a33f694d1c2def166053/bpf/lib/wireguard.h#L106

**Comment by brb** [comment]
Don't we bypass `to-netdev` when doing DSR in `from-netdev`?

**Comment by julianwiedmann** [comment]
> Don't we bypass `to-netdev` when doing DSR in `from-netdev`?

Wut? How/where would we do that? :smile:

**Comment by brb** [comment]
Brain blip :disappointed_relieved: I thought that `from-netdev` sets the SNAT done mark, and then early return in `to-netdev`.

**Comment by brb** [comment]
Closing the issue for now until I have clarified the DSR+Geneve breakage (discussed offline).

**Comment by brb** [comment]
Please completely forget the issue. With DSR + Geneve working (had to enable BPF masq), the DSR forwarded packets are encrypted :tada:
