### ISSUE TITLE
Detected conflicting tunnel peer for prefix.

### ISSUE THREAD

**Issue by issue-account** [cilium/cilium#32188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm setting up a nomad cluster of 500 nodes.
Cilium gives  an error  message:
```
level=warning msg="Detected conflicting tunnel peer for prefix. This may cause connectivity issues for this address." cidr=172.16.42.41/32 conflictingResource=node//host2 conflictingTunnelPeer=ip-addr resource=node//host2 subsys=ipcache
level=warning msg="Detected conflicting encryption key index for prefix. This may cause connectivity issues for this address." cidr=172.16.42.41/32 conflictingKey=255 conflictingResource=node//host2 key=255 resource=node//host1 subsys=ipcache
```

### Cilium Version

Client: 1.15.3 22dfbc58 2024-03-26T11:45:10+01:00 go version go1.21.8 linux/amd64
Daemon: 1.15.3 22dfbc58 2024-03-26T11:45:10+01:00 go version go1.21.8 linux/amd64

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
Thanks for the report! The warning is emitted whenever Cilium detects conflicting information for the same IP. Without a sysdump or further information, it's unclear why this would happen. One potential reason is that two nodes in your cluster somehow claimed to have same IP. This could could for example happen if two nodes claim the same GetCiliumInternalIP. That in turn can happen if the two nodes were accidentally configured to use the same "ipv4/ipv6-alloc-cidr".

Of course, we don't test Nomad in CI and its support is "best effort", so it is very possible that there is some buggy behavior that occurs with Nomad.

If you are unable to share a sysdump, could you at least dump the kvstore nodes `cilium node list -o json` for the affected agent?

**Comment by issue-account** [comment]
@gandro 
Sorry, we stopped the load, but I can share the config of the cilium that was used:
```
  cilium-agent --kvstore consul --kvstore-opt consul.address={{ cilium_consul_address }} \
    --kvstore-periodic-sync=5m \
    --enable-ipv6=false  \
    --tunnel-protocol=geneve \
    --enable-wireguard \
    --enable-bpf-masquerade=true \
    --kube-proxy-replacement=true \
    --enable-l7-proxy=false  \
    --ipv4-range 172.16.0.0/16 \
```
We indicate the static ipv4 range, because Cilium operator is not supported by nomad

**Comment by youngnick** [comment]
Thanks for the report @issue-account, but without some more information I don't think we're going to be able to help you. Is there any way you can provide more info?

**Comment by gandro** [comment]
> We indicate the static ipv4 range, because Cilium operator is not supported by nomad

Hi yes, so need to use a different IPv4 IP range on _every_ worker node. Normally the operator takes care of that in a K8s environment, but if you set the flag manually, you need to manually allocate a unique CIDR to each one of your nodes.

**Comment by ruslan-y** [comment]
Hi! I have the same issue.

I'm using `cilium_cidr: "auto"` and every worker node is getting subnet from range `10.0.0.0/16`
This means I can run cilium on no more than 256 nodes using 65,534 IPv4 addresses in each.

What will happen when this limit is reached? And what is the reason to use the 16 subnet by default?

I suggest using 24 subnet by default, it seems more flexible

**Comment by gandro** [comment]
Yes, using a `/24` per node should be plenty sufficient. I don't know anything about Nomad, but on K8s this the default size used by Cilium's default configuration. That means you may only have ~250 pods per node, but this typically is sufficient. 

But I don't know how IPAM works on Nomad. Maybe the IPv4 alloc CIDR is only used for cilium-internal IPs, in which case very small subnet (e.g. a /29) is probably sufficient (i.e. Cilium needs 1-3 IPs from that range, depends on the configuration).

**Comment by ruslan-y** [comment]
@gandro 
Running `cilium-agent` with `--ipv4-range auto` flag gives the following

> Name    IPv4 Address      Endpoint CIDR   IPv6 Address   Endpoint CIDR   Source
host1         ext ip addr       10.58.0.0/16                                   kvstore
host2        ext ip addr       10.141.0.0/16                                  kvstore
host3        ext ip addr       10.211.0.0/16                                  kvstore
host4        ext ip addr       10.185.0.0/16                                 kvstore
host5        ext ip addr       10.197.0.0/16                                  local
host6        ext ip addr       10.146.0.0/16                                 kvstore
host7        ext ip addr       10.30.0.0/16                                   kvstore
host8        ext ip addr       10.112.0.0/16                                  kvstore
host9        ext ip addr       10.92.0.0/16                                   kvstore

is there any parameter that defines the subnet manually, but controls it in auto mode?

**Comment by gandro** [comment]
> is there any parameter that defines the subnet manually, but controls it in auto mode?

Unfortunately no, the size is hardcoded (grep for `DefaultIPv4PrefixLen`)
