### ISSUE TITLE
Bring down flannel interface if intent is to replace CNI plugin

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3219]
Several users are running into the problem that flannel keeps a VXLAN device in metadata mode around which prevents Cilium from spinning up.

**Comment by aanm** [comment]
For future reference:
```
ip link delete cni0
ip link delete flannel.1
```
should be enough to allow cilium to start in a node that was previously running with flannel.

**Comment by vadorovsky** [comment]
I guess we can have it closed and consider it as a question? I don't think that removal of flannel's interfaces is something that Cilium does automatically. It's rather a manual operation which needs to be done when someone switches CNI plugins.

Let me know and reopen if I'm wrong.
