### ISSUE TITLE
CI: Conformance E2E - check-log-errors - Cannot forward proxied DNS lookup: duplicate request id 24376

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#32229]
## CI failure

Hit on https://github.com/cilium/cilium/pull/32225
Link: https://github.com/cilium/cilium/actions/runs/8876893665/job/24369378499
Sysdump: [cilium-sysdump-3-20240429-103648.zip](https://github.com/cilium/cilium/files/15148823/cilium-sysdump-3-20240429-103648.zip)

```
❌ Found 1 logs in kind-kind/kube-system/cilium-xtqfk (cilium-agent) matching list of errors that must be investigated:
time="2024-04-29T10:36:11Z" level=error msg="Cannot forward proxied DNS lookup" DNSRequestID=64703 dnsName=one.one.one.one. endpointID=1360 error="duplicate request id 24376" identity=56588 ipAddr="10.244.1.127:48485" subsys=fqdn/dnsproxy (1 occurrences)
```

**Comment by giorio94** [comment]
New occurrence: https://github.com/cilium/cilium/actions/runs/8965984562/job/24620564572

**Comment by youngnick** [comment]
hit on #32744 
https://github.com/cilium/cilium/actions/runs/9298554153/job/25590679386
and
https://github.com/cilium/cilium/actions/runs/9298554153/job/25590680864

**Comment by giorio94** [comment]
Hit again: https://github.com/cilium/cilium/actions/runs/9416796909/job/25940684017

**Comment by julianwiedmann** [comment]
@jrajahalme would you expect this to be fully addressed by https://github.com/cilium/cilium/pull/32870, once folks have rebased their branches?
