### ISSUE TITLE
CI: Telemetry for step trace is broken

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#32241]
PR https://github.com/cilium/cilium/pull/32037 introduced telemetry to several workflows. 

We can see in the original PR that the "Step trace" breaks down the time contribution from various different steps throughout the job (triggered from PR):

https://github.com/cilium/cilium/actions/runs/8731358629

More recently the step trace reports that all of the steps happen at the same time for the same length (Ariane-triggered, from PR #32167):

https://github.com/cilium/cilium/actions/runs/8880222005

We should investigate and resolve the issue that is causing the step trace to incorrectly report step timestamps and duration.

**Comment by joestringer** [comment]
Related, this workflow run complains about misformatted gantt chart in the step trace. This is PR #32020 and a different workflow (ci-ipsec-upgrade).

https://github.com/cilium/cilium/actions/runs/8817802264

```
Unable to render rich display

Parse error on line 11:
...1713967134000 Call actions/checkout aga...
----------------------^
Expecting 'EOF', 'SPACE', 'NL', 'weekday_monday', 'weekday_tuesday', 'weekday_wednesday', 'weekday_thursday', 'weekday_friday', 'weekday_saturday', 'weekday_sunday', 'dateFormat', 'inclusiveEndDates', 'topAxis', 'axisFormat', 'tickInterval', 'excludes', 'includes', 'todayMarker', 'title', 'acc_title', 'acc_descr', 'acc_descr_multiline_value', 'section', 'taskTxt', 'click', got 'callbackname'

For more information, see https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
```

It's possible that the root cause of the misreported step trace data is that the plugin is failing to properly format the gantt chart for GitHub to then interpret and draw the results.

**Comment by joestringer** [comment]
In recent ci-aks runs, the telemetry appears to be working correctly now:

https://github.com/cilium/cilium/actions/runs/9411068391

I'm still observing the "Unable to render rich display" issue for ci-ipsec-upgrade. Perhaps there is something particular about the way that the telemetry is linked into that workflow which is triggering the issue.

**Comment by chancez** [comment]
I've traced it down to the fact that the failing gaant chart has a line starting with `Call`. Yes, literally it's that, specifically. If you change it to `CallFoo` or anything else it's fine.

(I suggest viewing the raw markdown of this comment to see the comparison).

Eg this is broken:

```mermaid
gantt
	title Setup & Test (5.4, patch)
	dateFormat x
	axisFormat %H:%M:%S
	Set up job : milestone, 1721689493000, 1721689498000
	Build aanm/junit2md@332ebf0fddd34e91b03a832cfafaa826306558f9 : 1721689498000, 1721689501000
	Collect Workflow Telemetry : 1721689501000, 1721689501000
	Checkout context ref (trusted) : 1721689501000, 1721689506000
	Set Environment Variables : 1721689506000, 1721689506000
	Set up job variables : 1721689506000, 1721689506000
	Call actions/checkout again to remove credentials : 1721689506000, 1721689507000
	Check we effectively removed Git credentials : 1721689507000, 1721689508000
	Derive stable Cilium installation config : done, 1721689508000, 1721689508000
	Derive newest Cilium installation config : done, 1721689508000, 1721689508000
	Set Kind params : done, 1721689508000, 1721689508000
	Provision K8s on LVH VM : done, 1721689508000, 1721689508000
	Install Cilium CLI : done, 1721689508000, 1721689508000
	Checkout pull request branch (NOT TRUSTED) : done, 1721689508000, 1721689508000
	Checkout  branch to get the Helm chart : done, 1721689508000, 1721689508000
	Wait for images to be available : done, 1721689508000, 1721689508000
	Install Cilium  (5) : done, 1721689508000, 1721689508000
	Setup conn-disrupt-test before upgrading (5) : done, 1721689508000, 1721689508000

```


But this is fine:

```mermaid
gantt
	title Setup & Test (5.4, patch)
	dateFormat x
	axisFormat %H:%M:%S
	Set up job : milestone, 1721689493000, 1721689498000
	Build aanm/junit2md@332ebf0fddd34e91b03a832cfafaa826306558f9 : 1721689498000, 1721689501000
	Collect Workflow Telemetry : 1721689501000, 1721689501000
	Checkout context ref (trusted) : 1721689501000, 1721689506000
	Set Environment Variables : 1721689506000, 1721689506000
	Set up job variables : 1721689506000, 1721689506000
	Calltest actions/checkout again to remove credentials : 1721689506000, 1721689507000
	Check we effectively removed Git credentials : 1721689507000, 1721689508000
	Derive stable Cilium installation config : done, 1721689508000, 1721689508000
	Derive newest Cilium installation config : done, 1721689508000, 1721689508000
	Set Kind params : done, 1721689508000, 1721689508000
	Provision K8s on LVH VM : done, 1721689508000, 1721689508000
	Install Cilium CLI : done, 1721689508000, 1721689508000
	Checkout pull request branch (NOT TRUSTED) : done, 1721689508000, 1721689508000
	Checkout  branch to get the Helm chart : done, 1721689508000, 1721689508000
	Wait for images to be available : done, 1721689508000, 1721689508000
	Install Cilium  (5) : done, 1721689508000, 1721689508000
	Setup conn-disrupt-test before upgrading (5) : done, 1721689508000, 1721689508000

```

**Comment by chancez** [comment]
https://github.com/mermaid-js/mermaid/issues/2495 🤔 this seems to be the problem?

**Comment by chancez** [comment]
Filed an issue with the workflow-telemetry action. I'll see if I can PR a simple fix for it.

**Comment by chancez** [comment]
https://github.com/catchpoint/workflow-telemetry-action/pull/77. I'm thinking we could update the IPSec upgrade workflow to use my fork/branch temporarily and then if it fixes things; we can report back in my PR.
