### ISSUE TITLE
CI: more logs from various cilium-related processes for easier debugging

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3233]
- [x] Gather Cilium-Envoy logs as part of CI runs
    - Cilium-Envoy logs are not picked up as part of CI currently. We need to be able to get these logs for triaging proxy-related issues. Long-term solution is to redirect Cilium-Envoy logs to be owned by the parent Cilium process so that we can have Cilium-Envoy logs inline with Cilium logs, and to have them gathered as part of the bugtool. 
    - See #2829 as well.
- [ ] Compile Envoy in CI with debug symbols so that it outputs more logs.
- [ ] Run Cilium with various debug modes enabled (not sure if this is done currently, need to look into this).
   - (flow, kvstore, envoy) - see `daemon/main.go`.
   - These modes should be dynamically configurable at runtime so that we do not have to restart the agent for certain tests.
- [ ] Run Cilium Monitor in background for all tests
    - @eloycoto  *RFC* https://github.com/cilium/cilium/pull/3354
    - The bash tests had the ability to run the cilium monitor in the background. Having such a capability in the CI will allow us to figure out things at the data-path layer for our tests.
    - Have functions which allow for users to do the following in both runtime / K8s tests:
        - start the monitor on a specific node / pod, and redirect all output to a file with a name like `cilium-monitor-output-<timestamp monitor was started>.log`)
        - stop the monitor on a specific node / pod, and stop writing to said file.
        - Gather this file if a test fails as part of the log-gathering steps. 
- [ ] Add checker for Envoy core dumps / segmentation faults , as these have been occurring randomly in CI. Check logs for a log message like the following *after each test* (similar to how we check for deadlock):
    - @eloycoto https://github.com/cilium/cilium/pull/3355
    - ```Mar 21 07:36:31 runtime cilium-agent[16349]: level=warning msg="Envoy: Execution failed: signal: segmentation fault (core dumped)" error="signal: segmentation fault (core dumped)"```
    - Gather this core dump as part of the tests.
- [x] Run `cilium-docker` with debug logging enabled in CI.

cc: @jrajahalme and @rlenglet . Thoughts?

**Comment by jrajahalme** [comment]
Envoy rebase will bring debug and trace option available for all builds (Envoy commit 3b8875fb78e1f2655b9c3a73dd15f3d7a88e0f01 ("logger: removed NVLOG compile flag")), still need the debug build for better backtracing but maybe not that urgently.

**Comment by eloycoto** [comment]
@ianvernon I'm closing this one, all is sorted and the only piece waiting is the microscope, that it's already in a PR.
