### ISSUE TITLE
Cilium continues to serve stale IPs from existing allocated ENIs after updating AWS subnets

### ISSUE THREAD

**Issue by cnmcavoy** [cilium/cilium#32346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have cilium v0.15.3 installed with argocd/helm in our clusters in IPAM ENI mode, with no tunneling (native routing) configured. We set the subnets and configure the ENI parameters with a configmap:
```
    {
      "cniVersion":"0.3.1",
      "name":"cilium",
      "plugins": [
        {
          "cniVersion": "0.3.1",
          "type": "cilium-cni",
          "eni": {
            "first-interface-index": 1,
            "subnet-tags": {
              "network-zone": "qa",
              "kubernetes.io/cluster/awscmhdev4": "shared"
            }
          },
          "ipam": {
            "pre-allocate": "2",
            "min-allocate": "0",
            "max-above-watermark": "0"
          }
        }
      ]
    }
```
    
We have cilium choosing from 3 subnets in us-east-2, one per AZ. Because we share the subnet range with several clusters, we recently created a set of larger subnets in the same VPC, with identical routing configurations as cilium's current pod subnets, and also tagged them with the same set of subnet tags for cilium. We then untagged the previous subnets, but left their configuration otherwise unchanged.

Cilium detected these subnets immediately from the metrics we have, but on existing nodes, would continue to give new pods IPs from the existing old subnet ranges. The behavior seemed to continue as long as the node's ENI's still had free IPs. New nodes in the cluster served the new subnet ranges to pods as expected. Is this the expected behavior? Should cluster operators expect to have to recycle all the nodes to force Cilium to serve IPs from the new subnets? Should Cilium stop serving the old subnets immediately? It's unclear from the docs what behavior is correct.

### Cilium Version

v0.15.3

### Kernel Version

5.10.214-202.855.amzn2.x86_64

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.11-eks-b9c9ed7", GitCommit:"f19f83c16ca534237fbfb65bc580d51752b98c91", GitTreeState:"clean", BuildDate:"2024-03-02T03:46:53Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this issue @cnmcavoy, I've marked it for the attention of the relevant team.
