### ISSUE TITLE
CI: check status of Docker-related commands

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3237]
In a lot of tests, we do not check the results of Docker-related commands. For example, in `test/helpers/docker.go`:
```
// SampleContainersActions creates or deletes various containers used for
// testing Cilium and adds said containers to the provided Docker network.
func (s *SSHMeta) SampleContainersActions(mode string, networkName string) {
	images := map[string]string{
		Httpd1: HttpdImage,
		Httpd2: HttpdImage,
		Httpd3: HttpdImage,
		App1:   NetperfImage,
		App2:   NetperfImage,
		App3:   NetperfImage,
	}

	switch mode {
	case Create:
		for k, v := range images {
			s.ContainerCreate(k, v, networkName, fmt.Sprintf("-l id.%s", k))
		}
	case Delete:
		for k := range images {
			s.ContainerRm(k)
		}
	}
}
```

We should check the results of the functions `ContainerCreate` and `ContainerRm` and return the corresponding CmdRes which was not successful (or an error). This will ensure that we do not run tests if there is an issue with the Docker runtime itself.

**Comment by eloycoto** [comment]
Quick thing, if the container fails, you should check the endpoint in the test itself, no?

**Comment by ianvernon** [comment]
Please clarify what you mean by "check the endpoint in the test itself"? In my opinion, if a command that we expect to succeed fails, we should check the command itself, and not in some later part of the test. This makes debugging much easier and short-circuits the tests as soon as a failure we don't expect is encountered.
