### ISSUE TITLE
ci: Add /retest option to rerun only failed test

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#32425]
To help address cases where flaky test are blocking a PR, we should add a `/retest` command which only reruns failed tests. This is a better alternative to consistently using `/test` which reruns all tests, introducing the probability to come across new flakes.

**Comment by brlbil** [comment]
I am working on an implementation that runs tests as normal with the `/test` command and re-runs only the failed test if the `/test` command is issued again. If the commit SHA changes the `/test` runs all the tests again.

**Comment by brlbil** [comment]
This future is implemented and in use now.
