### ISSUE TITLE
node.SetDefaultPrefix causing traffic blackhole using multi-pool IPAM, native routing, eBPF

### ISSUE THREAD

**Issue by bewing** [cilium/cilium#32423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`cilium-agent` is installing a route pointing to `cilium_host` local interface with a 10.x.0.0/16 prefix auto-generated by [SetDefaultPrefix](https://github.com/cilium/cilium/blob/1c2eb97e06dea9f9aef6ff5bdaef3b87dcb51e1d/pkg/node/address.go#L86)

Traffic from the node or from hostNetwork pods destined to hosts in that prefix is being blackholed instead of following the node's default route.

Traffic from pods appears to forward correctly due to following eBPF masquerade rules.

### Cilium Version

v1.15.4

### Kernel Version

5.14.0-284.11.1.el9_2.x86_64

### Kubernetes Version

v1.28.9

### Relevant log output

```shell
# ip route show
default via 10.100.100.1 dev eth0 proto static metric 100
10.68.0.0/16 via 100.64.3.170 dev cilium_host proto kernel src 100.64.3.170
10.208.144.64/26 dev eth0 proto kernel scope link src 10.208.144.68 metric 100
100.64.3.170 dev cilium_host proto kernel scope link
```

### Anything else?

This may relate to #28632 and #27018

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
Are you running with local node route disabled and running with per endpoint routes as documented here? https://docs.cilium.io/en/v1.15/network/concepts/ipam/multi-pool/#limitations

I believe disabling the local node route should disable that problematic route. The proper fix of course is to disable the auto-generated CIDR by default. [I've attempted this in the past](https://github.com/cilium/cilium/pull/28792), but have not been able to finish that work due to a lack of cycles

**Comment by bewing** [comment]
We do not have `enable-local-node-route` explicitly set in our configmap.  The documentation doesn't explicitly state what the default is for that boolean.  I'm assuming it defaults to "true" if it's the cause of my issue.

This cluster was setup via Helm, and it appears the only control knob for that setting is via cniChainingMode: https://github.com/cilium/cilium/blob/9b3f9a8c0d71bf70bc0fd3fbc256bacc67fe6c32/install/kubernetes/cilium/templates/cilium-configmap.yaml#L559C1-L564C11

I'll edit our configmap directly, but if we upgrade via Helm, I assume it will remove it

**Comment by bewing** [comment]
Can confirm that after editing the configMap and restarting the daemonset, it stopped re-adding the autogenerated route.  The daemonset will not remove the autogenerated route installed previously automatically, however, so I had to manually wipe the old routes via `ip route del`

**Comment by gandro** [comment]
Thanks for the feedback! I agree the UX around the whole local node routes setup is rather bad. On `main`, we auto-disable the local node route if endpoint routes are enabled: https://github.com/cilium/cilium/pull/28324 but the docs should be improved for sure

But the long-term fix is to disable the auto-genereated CIDR by default. It causes many issues even outside of multi-p[ool

**Comment by bewing** [comment]
I also see I can inject the config into the map via `Values.extraConfig`, so I won't have issues with future upgrades.
