### ISSUE TITLE
TCP connection drops with LB mode: DSR ON when trying to reach ingress endpoint from outside the cluster

### ISSUE THREAD

**Issue by egorp500** [cilium/cilium#32437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Components:
1. VMware (vSphere)
2. Talos Linux (`v1.6.1`)
3. Client VM (Ubuntu 22.04.4 LTS)

Cilium installed with `kubeProxyReplacement = true`.

Also we have installed some pods with configured Ingress (HTTPS disable).

When we’re trying to initialize TCP connection from Client VM to Ingress with DSR ON - it breaks the connection. Our guess it’s because we receive a response from some Node and not from our ingress endpoint (Grafana LB).

> Note.  We see that response packets coming from node IP are being rejected.
> 

Command used: `curl -k http://grafana.e2.powercom.dev`

Control Plane IP: `10.50.1.193`

Talos-node-01 IP: `10.50.1.194`

Talos-node-02 IP: `10.50.1.195`

Talos-node-03 IP: `10.50.1.196`

Grafana LB IP: `10.50.1.209`

We use Cilium L2 LB CRD

1. CiliumL2AnnouncementPolicy
[CiliumL2AnnouncementPolicy.txt](https://github.com/cilium/cilium/files/15261931/CiliumL2AnnouncementPolicy.txt)
2. CiliumLoadBalancerIPPool
[CiliumLoadBalancerIPPool.txt](https://github.com/cilium/cilium/files/15261933/CiliumLoadBalancerIPPool.txt)

Screenshot and dumpfile of **tcpdump**
![tcpdump](https://github.com/cilium/cilium/assets/165773434/4662cc31-0521-4d00-9a42-8c47622c6b0e)
[tcpdump_dsr_on.zip](https://github.com/cilium/cilium/files/15261976/tcpdump_dsr_on.zip)

**Important:** Nginx Ingress Controller is on Talos-node-01, so the response is from 10.50.1.194

### Cilium Version

Client: 1.15.4 9b3f9a8c 2024-04-11T17:25:42-04:00 go version go1.21.9 linux/amd64
Daemon: 1.15.4 9b3f9a8c 2024-04-11T17:25:42-04:00 go version go1.21.9 linux/amd64

Cilium Helm chart: 1.15.4

### Kernel Version

Linux EEOPE2_talos-01 6.1.69-talos #1 SMP PREEMPT_DYNAMIC Thu Dec 21 15:48:53 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Linux EEOPE2_talos-02 6.1.69-talos #1 SMP PREEMPT_DYNAMIC Thu Dec 21 15:48:53 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Linux EEOPE2_talos-03 6.1.69-talos #1 SMP PREEMPT_DYNAMIC Thu Dec 21 15:48:53 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0

### Sysdump

[cilium-sysdump-20240508-152222.zip](https://github.com/cilium/cilium/files/15261982/cilium-sysdump-20240508-152222.zip)

### Anything else?

This archive includes additional `cilium-config` and `cilium-pod-config` files.
[cilium-configs.zip](https://github.com/cilium/cilium/files/15261993/cilium-configs.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
This certainly looks like an issue.

Could you try and create a minimal reproducer? Ideally on kind, but other environments would be acceptable. Does it have to be a LoadBalancer service, or are other types of kubernetes services affected?

**Comment by julianwiedmann** [comment]
This might be https://github.com/cilium/cilium/issues/32189 - are you using DSR with Geneve dispatch, but BPF masquerading is disabled?

**Comment by egorp500** [comment]
> This might be #32189 - are you using DSR with Geneve dispatch, but BPF masquerading is disabled?

As you can see in configuration I attached:
1. DSR ON with Geneve
2. bpf.masquerading false by default - [docs](https://github.com/cilium/cilium/blob/9b3f9a8c0d71bf70bc0fd3fbc256bacc67fe6c32/install/kubernetes/cilium/values.yaml#L506)
3. Masquerading (ipv4/ipv6) ON
4. Masquerading-to-route-source OFF, but it's for iptables. Ref - [docs](https://docs.cilium.io/en/stable/network/concepts/masquerading/#iptables-based)
![image](https://github.com/cilium/cilium/assets/165773434/6cfde8cd-74b9-4806-9268-ffe2d9aef722)

**Comment by julianwiedmann** [comment]
Cool, thanks for confirming! Then yes, let's dup against https://github.com/cilium/cilium/issues/32189.
