### ISSUE TITLE
Linux 5.10 (minikube ISO)  crashes on "address family not supported by protocol"

### ISSUE THREAD

**Issue by medyagh** [cilium/cilium#32448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in minikube for VM drivers (using custom linux 5.10)  cilium v1.15.4 crashes simmilar to https://github.com/cilium/cilium/issues/29965
however does not happen in Docker Driver (uses ubuntu with linux kernel 6)

The log for the container
```


$ kc logs cilium-cssbc -n kube-system | grep error
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
time="2024-05-09T23:45:53Z" level=info msg="  --kvstore-max-consecutive-quorum-errors='2'" subsys=daemon
time="2024-05-09T23:45:54Z" level=error msg="Start hook failed" error="daemon creation failed: error while initializing daemon: failed while reinitializing datapath: listing routing rules: address family not supported by protocol" function="cmd.newDaemonPromise.func1 (cmd/daemon_main.go:1686)" subsys=hive
time="2024-05-09T23:45:54Z" level=error msg="Observer job stopped with an error" error="context canceled" func="auth.(*authMapGarbageCollector).handleIdentityChange" name="auth gc-identity-events" subsys=auth
time="2024-05-09T23:45:54Z" level=error msg="Observer job stopped with an error" error="context canceled" func="auth.(*AuthManager).handleAuthRequest" name="auth request-authentication" subsys=auth
time="2024-05-09T23:45:54Z" lev
```

I believe this PR meant to fix this issue https://github.com/cilium/cilium/pull/30299 but it didnt

for more information checkout 
https://github.com/kubernetes/minikube/pull/18846

### Cilium Version

v1.15.4

### Kernel Version

5.10.207

### Kubernetes Version

v1.30.0

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Believe this is a dup of https://github.com/cilium/cilium/issues/31944, and will be fixed with the next v1.15 patch release.
