### ISSUE TITLE
Gateway API 1.1.0 released

### ISSUE THREAD

**Issue by fmunteanu** [cilium/cilium#32451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Gateway API [1.1.0](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.1.0) was released yesterday. I was wondering if the developers can validate if the experimental install is still the proper way to implement Gateway API, with Cilium. I'm going to test the new release and report back.

### Cilium Version

1.15.4

### Kernel Version

6.8.0-1004-raspi

### Kubernetes Version

1.29.4

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fmunteanu** [comment]
I performed a fresh cluster installation and the experimental install is still required. The standard install renders the `Gateway` with `HTTPRoute`, non functional.

**Comment by vehagn** [comment]
I don’t think the experimental Gateway CRDs are required for basic functionality, that’s only for the experimental features like the `spec.infrastructure.annotations` to e.g. set the IP for the Gateway Service.

The [Cilium docs on Gateway API](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/) suggest the standard install of both Gateway and HTTPRoute. 

Not sure if Cilium has much say in graduating that field to the standard install of Gateway API.

**Comment by fmunteanu** [comment]
@vehagn we can check it together but on my initial tests, a standard combination of `Gateway` + `HTTPRoute` would fail to load a secure webpage.

**Comment by sayboras** [comment]
There is some works required for Gateway API v1.1.0, the details can be found in https://github.com/cilium/cilium/issues/32492

**Comment by fmunteanu** [comment]
@sayboras I only use the `HTTPRoute`, I believe this should be an issue for me upgrading to 1.1.0 release?

**Comment by networkhermit** [comment]
Seems related, might be a good opportunity to remove the hard requirements of experimental alpha/beta crds, as future releases of gateway api could break cilium-operator too.

https://github.com/kubernetes-sigs/gateway-api/issues/3075#issuecomment-2107687646

**Comment by vehagn** [comment]
> @vehagn we can check it together but on my initial tests, a combination of `Gateway` + `HTTPRoute` would fail to load a secure webpage, when installing the 1.1.0 standard install. Once I switch to experimental, everything works as expected.

@fmunteanu Could you please share the `Gateway` + `HTTPRoute` you're testing with? Then I can test similar resources on my end.

**Comment by fmunteanu** [comment]
@vehagn please look at my [Hubble setup](https://github.com/axivo/k3s-cluster/tree/main/roles/cilium/templates), as example. I have a gateway and two routes, http and https.

**Comment by squeed** [comment]
Should we close this in favor of https://github.com/cilium/cilium/issues/32492, @sayboras?

**Comment by fmunteanu** [comment]
@sayboras some small note on the current stable Cilium Gateway API [documentation](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/). You make reference of installing specific manifests, while the official documentation refers to a [single one-liner](https://gateway-api.sigs.k8s.io/guides/#installing-gateway-api).

I'm only using `HTTPRoute` with Cilium and the` standard` install one-liner fails to produce a functional URL, while the experimental install does. Can the documentation be improved in this area? I believe performing a one-liner installation is simplified, however, the current standard install limitations, must be accounted.

I'm wondering what is your input on this?

**Comment by joestringer** [comment]
@fmunteanu one way to take this forward would be to propose the PR and request review for it.

**Comment by fmunteanu** [comment]
@joestringer you make reference to the Gateway API experimental install?

**Comment by joestringer** [comment]
Sorry, I'm just doing some spring cleaning :broom: . I understood your comment to be proposing to switch the list of resources over to the "standard" install YAML. I now see that you were also pointing out problems with that.

I see this is valid:
https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml

As is this:
https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml

Given https://github.com/cilium/cilium/pull/32233, the upcoming v1.16 versions of Cilium should support Gateway API 1.1 so if the instructions can work while pointing to the standard install YAML then by all means we can do that and make sure the v1.16 Cilium docs provide that guidance.

For stable releases of Cilium, I would not expect the default documentation to point to experimental releases of Gateway API, or at least not unless the instructions are very clear to the reader what kind of risks they may be taking due to the use of experimental resources.

**Comment by sayboras** [comment]
:wave: 

Thanks for your issue and input.

The main reason that we have both standard and experimental channels is to make sure that early support for new resources/features from the upstream Gateway API. Basically, we want to support and get ready with all proposed upstream features, which could be alpha/experimental. Just a note that a particular feature will not move to standard/GA _unless_ there are at least two implementations providing the support.

There could be some improvement that we can make to _not enforce_ experimental CRDs to be available. This should help with your point on having only standard CRDs in the official docs. Tracked in https://github.com/cilium/cilium/issues/32539.

**Comment by fmunteanu** [comment]
Thank @sayboras, what is the ERA for Cilium 1.6 stable? I’m happy with 1.1.0 experimental install, I have zero issues, since I only use HttpRoute. Standard install will break it, unfortunately.

**Comment by aanm** [comment]
@fmunteanu this is available since v1.16.0-rc.0 also in v1.16.0-rc.1 if you want to try it out and provide feedback. Thank you

**Comment by fmunteanu** [comment]
@aanm I’m using the Cilium stable release, on my K3s cluster.

**Comment by joestringer** [comment]
@sayboras I understand that there is an actionable follow-up to this in https://github.com/cilium/cilium/issues/32539 . Are there any other steps we need to take to resolve/close this specific issue? It seems like we've already implemented Gateway API 1.1.0 support, this is just pending the stable v1.16.0 release that will be out in the coming weeks.

**Comment by sayboras** [comment]
> Are there any other steps we need to take to resolve/close this specific issue?

Not that I know of :+1:
