### ISSUE TITLE
CI: proposal to have wrappers around Expected output of certain helpers

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3247]
From discussion on https://github.com/cilium/cilium/pull/3234#issuecomment-375048619 , I proposed the following:

"As the helpers get more complex, we can use ExpectSuccess() and other such gomega checkers like ExpectWithOffset. This will ensure that for every command we run, even in helper functions, we get the result we expect. "

For instance, we can have a helper function before each test that assures that the setup is in a specific state (no endpoints running, configuration values are set a certain way, etc.). Currently this is done with quite a bit of boilerplate code that is duplicated throughout tests. This can result in tests missing these critical steps to ensure a sane environment before testing. 

Thoughts?

**Comment by joestringer** [comment]
```
boilerplate--
assert(infrastructureIsSane).In(helpers)
addSpecialHelpersForSpecialCases()
```

**Comment by eloycoto** [comment]
Hi!

My two cents here, as I said, I do not like to have asserts into the helpers, for me is a bad practice to create a Container and do an assertion into that. I think that docker, cilium, kubectl shouldn't have asserts only in cases that we want to assert something (Check deadlocks for example).

But I agree that some code is duplicated, like vm.WaitEndpointsReady, for that I suggest something like: 

`helpers.ExpectNoError(vm.WaitEndpointReady, "No endpoints ready")`

I mean, I'm happy with having Expect in helpers, but always when that assert is directly called from the test, which make things more clean. 

Suggestions: 

```
// Option A
err := vm.SampleContainersActions(helpers.Create, helpers.CiliumDockerNetwork)
helpers.ExpectNoError(err, "Containers cannot be created")

// Option B
vm.SampleContainersActions(helpers.Create, helpers.CiliumDockerNetwork)
helpers.ExpectSampleContainers()
```
second  suggestions: 

```
// Option A
helpers.ExpectNoError(vm.WaitEndpointsReady(), "Containers cannot be created")

// Option B
vm.WaitEndpointsReady()
vm.ExpectAllEendpointsAreReady()
```

I prefer option A, and I think that it's how kubernetes is doing right now. My idea is to have a test that all assertions are in test, so it'll be easy to know where the things fails and we follow the simple responsibility principle. IMHO

**Comment by eloycoto** [comment]
@ianvernon I think that this one can be closed no? 

Regards
