### ISSUE TITLE
CFP:  don`t EnableIPv4Masquerade=false when lb-only

### ISSUE THREAD

**Issue by hhstu** [cilium/cilium#32494]
## Cilium Feature Proposal
        
**Is your proposed feature related to a problem?**

why should we make EnableIPv4Masquerade=false when lb-only ? I want EnableIPv4Masquerade for Public gateway when use lb-only
```
switch option.Config.DatapathMode {
	case datapathOption.DatapathModeVeth:
	case datapathOption.DatapathModeLBOnly:
		log.Info("Running in LB-only mode")
		if option.Config.NodePortAcceleration != option.NodePortAccelerationDisabled {
			option.Config.EnablePMTUDiscovery = true
		}
		option.Config.KubeProxyReplacement = option.KubeProxyReplacementFalse
		option.Config.EnableSocketLB = true
		// Socket-LB tracing relies on metadata that's retrieved from Kubernetes.
		option.Config.EnableSocketLBTracing = false
		option.Config.EnableHostPort = false
		option.Config.EnableNodePort = true
		option.Config.EnableExternalIPs = true
		option.Config.RoutingMode = option.RoutingModeNative
		option.Config.EnableHealthChecking = false
		option.Config.EnableIPv4Masquerade = false
		option.Config.EnableIPv6Masquerade = false
		option.Config.InstallIptRules = false
		option.Config.EnableL7Proxy = false
```
**Describe the feature you'd like**

Include any specific requirements you need

**(Optional) Describe your proposed solution**

**Comment by brb** [comment]
Thanks for the issue.

> I want EnableIPv4Masquerade for Public gateway when use lb-only

Do you want an LB node to act as an Egress Gateway?

**Comment by hhstu** [comment]
Yes,and out of k8s cluster. @brb

**Comment by brb** [comment]
Did you check that the enabling masquerading allows traffic to be forwarded to outside?

**Comment by hhstu** [comment]
Not work, I haven't found the reason yet
