### ISSUE TITLE
Helm Values: preflight.nodeSelector Does Not Render Correctly

### ISSUE THREAD

**Issue by littlesheng19** [cilium/cilium#32497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

"preflight.nodeSelector" does not seem to work, as it appears to be not addressed in the Helm template.

https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-preflight/daemonset.yaml#L30

For example:
```
$ cat preflight.yaml

operator:
  enabled: false
agent: false
preflight:
  enabled: true
  nodeSelector:
    cnitype: cilium
  tolerations:
  - operator: Exist
```

And nodeSelector shows `<none>` as it does not render nodeSelector correctly in daemonset:
```
k get ds -n cilium 
NAME                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                           AGE
cilium                    52        52        52      52           52          cnitype=cilium,kubernetes.io/os=linux   312d
cilium-pre-flight-check   54        54        52      24           52          <none>                                  49m
```

### Cilium Version

1.15.4

### Kernel Version

Linux ip-172-30-236-195.ap-southeast-1.compute.internal 5.10.215-203.850.amzn2.x86_64 #1 SMP Tue Apr 23 20:32:19 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.26

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
whoops!

**Comment by squeed** [comment]
Filed a quick PR to fix this; good spot!
