### ISSUE TITLE
Library to load BPF programs

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#325]
Get rid of dependency to use iproute2 and tc to load BPF programs and leverage a native library instead.

**Comment by borkmann** [comment]
By native library you mean native in Go or can it be implemented in C (f.e. against elfutils library) and we add bindings? Or should this library even be linked against llvm library, so we potentially don't need to call out clang either?

**Comment by tgraf** [comment]
A C library + bindings will be great. Writing the bindings is trivial. Long term I would like to no longer depend on invoking llvm but short term that's perfectly acceptable.
