### ISSUE TITLE
In the iPam mode of CRD, the pod may allocate an IP that has already been released

### ISSUE THREAD

**Issue by weiwei02** [cilium/cilium#32531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using IPAM in CRD mode, I encountered an issue where the IP address already assigned to the pod was marked as released. After analysis, it was found that there are bugs in the current version of Cilium.

The steps and related codes to reproduce the issue are as follows:
1. The operator triggered 'PrepareIPRelease()' and marked an IP in 'CiliumNode. status. release.ips' as 'marked-for-release'. [node.go:L789](https://github.com/cilium/cilium/blob/73b3704bb96bbd90ba76992d9ad978d87e402716/pkg/ipam/node.go#L789)
2. The agent received a new 'CiliumNode' update event and triggered the 'updateLocalNodeResource()` function. [allocator.go#L196](https://github.com/cilium/cilium/blob/73b3704bb96bbd90ba76992d9ad978d87e402716/pkg/ipam/allocator.go#L196)
3. Concurrent with 2., create a new pod and allocate a new IP.
4. Finally, the newly allocated IP for the third part will be marked as' ready-for-release 'in the 2. step, and the IP address release will be completed.  The IP address of the Pod that has already been running was released..

The detailed code related to the problem is as follows:
https://github.com/cilium/cilium/blob/73b3704bb96bbd90ba76992d9ad978d87e402716/pkg/ipam/crd.go#L428-L443

### Cilium Version

1.14.6

### Kernel Version

5.15.54-051554-generic

### Kubernetes Version

1.24.4

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Thanks for the comment; this certainly looks like an issue.

**Comment by weiwei02** [comment]
reopen

**Comment by doniacld** [comment]
I reopen it since @weiwei02 has been working on a fix https://github.com/cilium/cilium/pull/34489.
