### ISSUE TITLE
Master build unstable

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3254]
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/424/testReport/
* runtime.RuntimeValidatedConntrackTable Testing proxy redirect after installing L3-L4-L7 policy over an existing L3-L4 policy
* runtime.RuntimeValidatedConntrackTable Testing L3-L4-L7 policy while the L3-L4 connection was previously made to confirm L3-L4-L7 policy enforcement over the proxy with the same source port

https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/422/testReport/
* runtime.RuntimeValidatedConntrackTable Testing L3-L4-L7 policy while the L3-L4 connection was previously made to confirm L3-L4-L7 policy enforcement over the proxy with the same source port

**Comment by ianvernon** [comment]
This is the same issue that was seen recently; I'll disable the test so it can be debugged in parallel to avoid blocking PRs.

**Comment by rlenglet** [comment]
The issue is tracked in https://github.com/cilium/cilium/issues/3208.
Can we close this one?

**Comment by ianvernon** [comment]
#3255 disabled this test in master so it can be tracked separately, so yes, let's close this.
