### ISSUE TITLE
OIDC for Hubble UI authorization

### ISSUE THREAD

**Issue by petr0ff** [cilium/cilium#32550]
Hello! Is there a way to use some oidc provider/client (like Dex, Keycloak, etc.) for authorizing in Hubble UI? So far I couldn't find any clues in helm charts.

Thank you!

**Comment by macmiranda** [comment]
You could use https://oauth2-proxy.github.io/oauth2-proxy/ in conjunction with your Ingress controller.

If you're on AWS, check out https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html and https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/

**Comment by petr0ff** [comment]
Thank you very much for your response! I'm on prem, having only Dex as a oidc proxy client and the LDAP catalog underneath.  Oauth proxy looks similar to dex, will try to integrate it with nginx ingress controller.

**Comment by squeed** [comment]
:wave: hi there, I'm going to close this for now, as it seems you've got the information you need. If you think this is in error, please reach out to re-open, or file an issue on the hubble-ui repository directly :-)
