### ISSUE TITLE
MTU issue for large UDP packets with native routing and DSR

### ISSUE THREAD

**Issue by lgyurci** [cilium/cilium#32601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have an environment with DSR and native routing, and a UDP service (SIP) with 3 endpoints, running on 3 different nodes. The MTU on the network is 1500 bytes. When a large, external 1500 byte UDP packet gets sent to the service, it gets routed to one of the nodes, which DNATs it to one of the pods. If the pod is running on a different node, it gets sent over the network to another node, and because of DSR, an 8 byte header gets added to the packet, making it 1508 bytes long, which is higher than the MTU. And in the end, some entity (either the host, or the switch [we have an L2 network], I didn't really look into that) drops the packet.

For TCP, this is not an issue as far as I know, since this 8 byte header only gets added to packets with the SYN flag, which are almost never large.

### Cilium Version

Client: 1.15.1 a368c8f0 2024-02-14T22:16:57+00:00 go version go1.21.6 linux/amd64
Daemon: 1.15.1 a368c8f0 2024-02-14T22:16:57+00:00 go version go1.21.6 linux/amd64

### Kernel Version

5.14.0-362.24.1.el9_3.0.1.x86_64

### Kubernetes Version

v1.26.15+rke2r1

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
What do you think is the bug here? That Cilium generates a packet of 1508 bytes? If yes, what else should it do (keep in mind that we can't avoid encapsulation)?

Can you either drop Cilium's MTU to 1492 or increase your underlying network to >= 1508?

**Comment by lgyurci** [comment]
I'm not sure if it's possible via ebpf, but cilium should fragment the packet, like any other router would in a scenario like this.

But I would also like to suggest what it shouldn't do: Break random network connections without any warning, and put the task of debugging onto the end-user. This issue took a significant amount of time to figure out (SIP connections breaking randomly, good luck), and I would at least expect some form of mention about this in the documentation, that "you should watch out for this if you are doing this", even if the solution is simply to increase/decrease the MTU in certain places. Make it appear in a red alert box on the native routing documentation page.

I could increase the MTU on the hosts, and that's what I did in the end, but I feel like this is more of a workaround than a solution. It turns out the host network interfaces were dropping the packets, because they automatically set the same MRU as the MTU - and also on a hardware level, so we couldn't even see those packets with tcpdump. However, now the hosts technically could send 1508 byte packets to other network entities, which is not ideal (cilium's MTU was left at 1500, which meant we had to take it out from automatic MTU mode), so we implemented another workaround: a bond interface on top of the physical one with 1500 MTU. I hope you see the absurdity of this situation. In my opinion,  you shouldn't have to manually set the MTU anywhere, anytime.

Sorry if this comment came out as aggressive, I really like what you do, and I like cilium as a software as well, I'm just through a few hours of debugging, and now a bit emotionally attached to this case.

**Comment by julianwiedmann** [comment]
:wave: maybe have a look at https://github.com/cilium/cilium/pull/21825 ?

**Comment by lmb** [comment]
> Sorry if this comment came out as aggressive, I really like what you do, and I like cilium as a software as well, I'm just through a few hours of debugging, and now a bit emotionally attached to this case.

Sure, it does come out that way. I empathise with you, but you are using software that is made available to you for free. Debugging is the price you pay. Expressing your frustration this way to a stranger trying to help is not the way to go.

> I'm not sure if it's possible via ebpf, but cilium should fragment the packet, like any other router would in a scenario like this.

Fragmentation is a tricky topic. I'm not sure we have plans to do outbound fragmentation. Enabling pmtu discovery should at least help for compliant clients.

> However, now the hosts technically could send 1508 byte packets to other network entities, which is not ideal (cilium's MTU was left at 1500, which meant we had to take it out from automatic MTU mode), so we implemented another workaround: a bond interface on top of the physical one with 1500 MTU.

Could you lower the default route MTU to 1500 instead?

Coming back to making this easier to debug: oversized packets should emit `DROP_FRAG_NEEDED` in `cilium-dbg monitor`. Did you check that output?

**Comment by xichaocn** [comment]
@lmb @lgyurci Sorry to bother you, but I encountered the same issue. I cannot modify the switch MTU to 1508 (since the switch belongs to someone else). If I only modify the node MTU to 1508, packets will still be dropped at the switch. If Cilium cannot fragment the packets, how can this issue be resolved?

**Comment by joestringer** [comment]
As far as I can tell, the [official docs around DSR](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#direct-server-return-dsr) don't actually describe the required MTU changes, they just hint at required MTU changes. Perhaps the minimal change here is to either (a) document explicitly the requirements that DSR imposes on MTU in an environment, or next step (b) in DSR mode adjust Cilium's autodetected MTU based on the potential need for additional header space for the directly-returned packets.

**Comment by DaruZero** [comment]
Hello. Sorry to bump this old issue, but I am in the exact same situation as @lgyurci. Did anyone ever find a solution to this?
Increasing the host's interface MTU is not really an option, and it seems that lowering Cilium's MTU to 1450 does not fix the problem either when the client is on a different VLAN.
I can see the ICMP response saying to lower the fragmentation at 1442 to account for the 8 bytes of the encapsulation, but the 4 bytes of the VLAN tag still make the packet above 1450, thus resulting in it being dropped.
I then tried to follow this [section](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#direct-server-return-dsr-with-geneve) on encapsulating with Geneve, because it seems to be related to this problem. Now the client sends a packet of 1500 + 16, gets dropped and pmtud says to lower MTU to 1388. The client than re-fragment to 1388, but the packet is somehow still dropped.
I can see this log from `cilium monitor -t drop`, but I don't know if it is the first 1500 packet or the 1388 one
```
xx drop (First logical datagram fragment not found) flow 0xba64724e to endpoint 0, ifindex 777, file bpf_overlay.c:880, , identity world->unknown: 10.4.0.231 -> 10.42.8.198
```
