### ISSUE TITLE
Documentation - SEE ALSO links are broken for all section of Command Reference

### ISSUE THREAD

**Issue by ishantanu** [cilium/cilium#3260]
## Bug reports
All of the `SEE ALSO` links inside the Command Reference section are dead. It is not just for `cilium prefilter SEE ALSO` section. See #2733. 

### Title

Broken `SEE ALSO` links for all sections of [cmdref](http://cilium.readthedocs.io/en/latest/cmdref/) in documentation.

### How to reproduce the issue
Some example links are mentioned below:

1. http://cilium.readthedocs.io/en/latest/cmdref/cilium/#see-also
2. http://cilium.readthedocs.io/en/latest/cmdref/cilium-health/#see-also

Likewise, all `SEE ALSO` links from http://cilium.readthedocs.io/en/latest/cmdref are non-functional.

**Comment by joestringer** [comment]
Looks like the links are nesting within the current path, eg the link on prefilter page:

http://cilium.readthedocs.io/en/latest/cmdref/cilium_prefilter/cilium.html

This should actually be:

http://cilium.readthedocs.io/en/latest/cmdref/cilium.html

**Comment by joestringer** [comment]
Looking at the latest docs, this problem seems to still be present. Reopening.

**Comment by ishantanu** [comment]
@joestringer I tried this locally using `docker` container and the issue seemed to be fixed. But looking at live docs, it's still the same.

**Comment by joestringer** [comment]
@iamShantanu101 yep, but for some reason the same fix doesn't work on the readthedocs, so if you go to the online site, eg: 
http://docs.cilium.io/en/latest/cmdref/cilium_bpf_proxy/

The links are still broken. 

Further investigation required.

**Comment by mrostecki** [comment]
> @iamShantanu101 yep, but for some reason the same fix doesn't work on the readthedocs, so if you go to the online site, eg:
> http://docs.cilium.io/en/latest/cmdref/cilium_bpf_proxy/
> 
> The links are still broken.
> 
> Further investigation required.

I see that they (and all the other `see also` links I saw) are working again now, so I'm closing this issue.
