### ISSUE TITLE
Why __builtin_memcmp() is forbidden?

### ISSUE THREAD

**Issue by tacslon** [cilium/cilium#32624]
@borkmann Hi, I saw ```__builtin_memcmp()``` is forbidden to use in this commit https://github.com/cilium/cilium/commit/239711b711740f515f301766ef20e45bbbf5621d, and I have 2 questions:

1. Why we do not use ```__builtin_memcmp()``` directly? Is there a risk of performance?
2. Why we only support several specified value of ```N``` in ```__builtin_memcmp()``` (values in switch-case block)?

Thanks!

**Comment by lmb** [comment]
This is a bug / issue tracker for Cilium, please try the development channel on our Slack.
