### ISSUE TITLE
CFP: alternative distro images for cilium

### ISSUE THREAD

**Issue by ncolondres-apptio** [cilium/cilium#32658]
## Cilium Feature Proposal
We run cilium in our FedRAMP environment and use various container scanning tools like ECR, trivy/clair, and snyk to scan containers for vulnerabilities. These tools have trouble or are unable to scan "distroless" containers which I believe cilium makes use of.

Please consider this a feature request to additionally release an alternative scannable container to something like RedHat UBI, Apline, and/or Ubuntu.

images in question:
- quay.io/cilium/hubble-relay
- quay.io/cilium/operator-aws

**Comment by joestringer** [comment]
Hi @ncolondres-apptio , the intent behind "distroless" containers is to improve security by minimizing or removing unnecessary dependencies that may either introduce vulnerabilities or create false positive reports in the images.  Changing these images to use a base with more unnecessary dependencies seems like it would introduce additional maintenance work without improving security. I would expect that the trend is towards more software using distroless images, not to move away from distroless images.

Perhaps those container scanning tools should be improved to support scanning distroless images?
