### ISSUE TITLE
UBSAN reporting an out-of-bounds array access.

### ISSUE THREAD

**Issue by dedene** [cilium/cilium#32667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading from TalosOS v1.6.7 to v.1.7.x a kernel error is logged after booting: `UBSAN: array-index-out-of-bounds in kernel/bpf/lpm_trie.c:194:14`. The node seems perfectly functioning however, but this message is not appearing on v1.6.7 or lower. I'm running Cilium 1.15.5 as CNI.

I'm not sure if this is a Cilium issue or [Talos Linux related issue](https://github.com/siderolabs/talos/issues/8780), Or even upstream due to upgrading the Linux kernel from 6.1.x to 6.6.x in Talos between 1.6.x and 1.7.x. But I'm hoping for some help or advice from the community. Feel free to close this issue if not applicable.

Many thanks in advance!

### Logs

```
kern:     err: [2024-05-22T12:30:28.7931256Z]: ================================================================================
kern:     err: [2024-05-22T12:30:28.7934956Z]: UBSAN: array-index-out-of-bounds in kernel/bpf/lpm_trie.c:194:14
kern:     err: [2024-05-22T12:30:28.7937366Z]: index 8 is out of range for type '__u8 [*]'
kern: warning: [2024-05-22T12:30:28.7939176Z]: CPU: 0 PID: 2591 Comm: cilium-agent Not tainted 6.6.30-talos #1
kern: warning: [2024-05-22T12:30:28.7941556Z]: Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 3.20230228-4 06/06/2023
kern: warning: [2024-05-22T12:30:28.7944506Z]: Call Trace:
kern: warning: [2024-05-22T12:30:28.7945456Z]:  <TASK>
kern: warning: [2024-05-22T12:30:28.7946546Z]:  dump_stack_lvl+0x47/0x60
kern: warning: [2024-05-22T12:30:28.7948526Z]:  __ubsan_handle_out_of_bounds+0xc7/0x100
kern: warning: [2024-05-22T12:30:28.7950876Z]:  longest_prefix_match.isra.0+0x18c/0x1d0
kern: warning: [2024-05-22T12:30:28.7952736Z]:  trie_update_elem+0x152/0x300
kern: warning: [2024-05-22T12:30:28.7954186Z]:  bpf_map_update_value+0xe5/0x220
kern: warning: [2024-05-22T12:30:28.7955786Z]:  __sys_bpf+0x19e2/0x26d0
kern: warning: [2024-05-22T12:30:28.7957116Z]:  __x64_sys_bpf+0x1e/0x30
kern: warning: [2024-05-22T12:30:28.7958426Z]:  do_syscall_64+0x5a/0x80
kern: warning: [2024-05-22T12:30:28.7959776Z]:  entry_SYSCALL_64_after_hwframe+0x78/0xe2
kern: warning: [2024-05-22T12:30:28.7959806Z]: RIP: 0033:0x40720e
kern: warning: [2024-05-22T12:30:28.7959826Z]: Code: 48 83 ec 38 e8 13 00 00 00 48 83 c4 38 5d c3 cc cc cc cc cc cc cc cc cc cc cc cc cc 49 89 f2 48 89 fa 48 89 ce 48 89 df 0f 05 <48> 3d 01 f0 ff ff 76 15 48 f7 d8 48 89 c1 48 c7 c0 ff ff ff ff 48
kern: warning: [2024-05-22T12:30:28.7959846Z]: RSP: 002b:000000c000dec1b0 EFLAGS: 00000216 ORIG_RAX: 0000000000000141
kern: warning: [2024-05-22T12:30:28.7959866Z]: RAX: ffffffffffffffda RBX: 0000000000000002 RCX: 000000000040720e
kern: warning: [2024-05-22T12:30:28.7959876Z]: RDX: 0000000000000020 RSI: 000000c000dec360 RDI: 0000000000000002
kern: warning: [2024-05-22T12:30:28.7959886Z]: RBP: 000000c000dec1f0 R08: 0000000000000000 R09: 0000000000000000
kern: warning: [2024-05-22T12:30:28.7959886Z]: R10: 0000000000000000 R11: 0000000000000216 R12: 000000c000debef0
kern: warning: [2024-05-22T12:30:28.7959896Z]: R13: 000000c000be5c00 R14: 000000c000cae680 R15: 00000000000001e9
kern: warning: [2024-05-22T12:30:28.7959926Z]:  </TASK>
kern:     err: [2024-05-22T12:30:28.7959936Z]: ================================================================================
```

### Cilium Version

1.15.5

### Kernel Version

6.6.28 (or later)

### Kubernetes Version

1.28.10

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dedene** [comment]
Maybe related to https://github.com/torvalds/linux/commit/896880ff30866f386ebed14ab81ce1ad3710cfc4 ?

**Comment by lmb** [comment]
Yes, this is definitely a kernel problem. Can you follow the procedure at https://docs.kernel.org/6.6/bpf/bpf_devel_QA.html#q-how-do-i-report-bugs-for-bpf-kernel-code? Thanks!

**Comment by nberlee** [comment]
See [patchwork](https://patchwork.kernel.org/project/netdevbpf/patch/20240222155612.it.533-kees@kernel.org/)
and [mailinglist](https://lore.kernel.org/lkml/202402221046.020C94D@keescook/T/)
