### ISSUE TITLE
Error attaching XDP program on device bond0.184: "operation not supported

### ISSUE THREAD

**Issue by nueavv** [cilium/cilium#32699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

failed attach xdp 

error log
`time="2024-05-24T07:36:21Z" level=info msg="  --enable-xdp-prefilter='false'" subsys=daemon
time="2024-05-24T07:36:24Z" level=info msg="No existing link found at /sys/fs/bpf/cilium/devices/bond0-184/links/cil_xdp_entry for program cil_xdp_entry" subsys=datapath-loader
time="2024-05-24T07:36:24Z" level=info msg="Failed to attach XDP program, ignoring due to best-effort mode" device=bond0.184 error="program cil_xdp_entry: attaching program cil_xdp_entry using bpf_link: create link: operation not supported" subsys=datapath-loader
`

### Cilium Version

1.15.5

### Kernel Version

5.15.0-60-generic #66~20.04.1-Ubuntu

### Kubernetes Version

1.25.5

### Anything else?

`helm install cilium cilium/cilium --version 1.15.5 \
  --namespace kube-system \
  --autoDirectNodeRoutes=true --masquerade=true --installNoConntrackIptablesRules=true --kubeProxyReplacement=true --loadbalancer.algorithm=random --loadbalancer.mode=snat --loadbalancer.acceleration=best-effort`
  
nic info
Ethernet Controller X710 for 10GbE SFP+
I350 Gigabit Network Connection

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
See https://github.com/cilium/cilium/issues/30072
