### ISSUE TITLE
CFP: ServiceImport auto creation for MCS-API

### ISSUE THREAD

**Issue by MrFreezeex** [cilium/cilium#32712]
## Cilium Feature Proposal

The goal of this issue is to discuss how we can implement ServiceImport auto creation in the context of the MCS-API implementation within Cilium (related to issue #27902 and PR #32555 that triggered this).

Here is for context how the Cilium MCS-API should look like from a somewhat high level view (and simplified): 
![Cilium_MCS-API](https://github.com/cilium/cilium/assets/3845213/50faee9b-6680-4751-b44d-15617ee1dcfb)

Each color represent one separate mechanism/kubernetes controller, the blue and green represent mechanisms outside of the scope of this issue but are included in the schema for context. Our main focus here are the red arrows which is about how the ServiceImport is created.

As you can see in the schema the goal of the controller that would auto create the ServiceImport object is to aggregate all the exported service (the ServiceExport resource + its associated Service) of the same name and manage the ServiceImport object based on that. The aggregation is supposed to take the data from the Service related to the oldest ServiceExport resource (based on the creation timestamp).

So we need to have at least the following data from each service that are exported through MCS-API:
- The creation timestamp of the ServiceExport object (to resolve conflict)
- The list of ports
- The type (in the sense of ServiceImport, meaning if it's headless or not)
- The session affinity (which for additional context is split into two fields `SessionAffinity` and `SessionAffinityConfig`)

We cannot retrieve as is these info from the derived service that is already shared and global through the traditional Cilium/non MCS-API means as the info there would be post-aggregation and we need to get the original data pre-aggregation.

Also note that we don't necessarily have to use the mcs-api struct or even the kubernetes api struct directly to share these data, we could theoretically have our own as long as we are able to reconstruct similar data noted in the list above.

**Solution 1: encoding the JSON data in a annotation in the derived Service**
This solution would involve copying the data that we need into the derived Kubernetes Service encoded in JSON through an annotation (initial proposal in PR #32555 was doing this).

This allows to reuse all the existing clustermesh infrastructure that allow to share services and build controllers (for instance the `GlobalServiceCache`) which I believe could helps keeping the MCS-API implementations much more contained in its own package. Encoding some JSON data in an annotation is probably not very common (and even a bit weird) but is also not something that was never done before in the Kubernetes world as for instance kubectl does that for its last applied annotation.

**Solution 2: Store directly the data in `ClusterService` objects without going through an annotation**
This is somewhat similar to Solution 1, but here we would instead try to store the data directly in the `ClusterService` objects without exposing it in an annotation in the derived Service.

The obvious advantage here is that we don't expose (somewhat) unnecessary info in the derived Service object through an annotation.

But from what I can see the implementation could be significantly more complex as the `ClusterService` struct is directly derived from the cilium `Service` struct which means that we would have to develop a controller (or update the existing one that create the cilium `Service` struct) that would detect derived Service and check its corresponding Service and ServiceExport and directly inject data in the cilium `Service` objects or `ClusterService`. This sounds kind of complex to do and would most likely (?) involve much more code dealing with MCS-API outside of the mcsapi go package and even a good amount of code in go packages that are not even directly related to clustermesh at all.

**Solution 3: Create a new type of objects shared in a clustermesh**
This involves creating a separate type, for instance `MCSAPIServiceExport`, shared in the clustermesh like we do for nodes, services, identities and endpoint.

The advantage is similar to solution 2 with probably a significantly less complex implementation. However, this solution would still most likely involve updating a bit more code outside of the mcsapi go package than solution 1 as we would need to add this new type in a few places in the clustermesh code + we would probably have to rebuild/refactor things to have something similar in term of features to the `GlobalServiceCache` to build the controller that would create ServiceImport.

**Comment by MrFreezeex** [comment]
Hi @giorio94 @YutaroHayakawa @joamaki :wave: , here is the issue that I promised on https://github.com/cilium/cilium/pull/32555, describing the ServiceImport creation mechanism and how we would deal with sharing the data that we need in the clustermesh.

Let me know if something is unclear or need more details and which proposed solution (or another solution if you have some other ideas to implement this) you would like to see being implemented.

**Comment by giorio94** [comment]
Thanks @MrFreezeex for the write-up, this is definitely useful to better understand the overall context.

Based on my understanding so far, I'm personally in favor of option 3, that is the introduction of new dedicated etcd path for MCS-API related information (the specs of `Services` targeted by `ServiceExports` if I'm not missing anything). To me, the biggest advantage would be the clear separation between what needs to be accessed by the MCS-API logic inside the Cilium Operator, and the already existing Cilium agents side logic to implement global services, especially considering that they depend on pretty different fields. The segregation would enable improved flexibility of the MCS-API side until the implementation is fully settled, as well as increased performance as each component needs to only retrieve the information that actually needs. For instance, the `ServiceExports` representation does not depend on the actual endpoints, and omitting them allows to reduce the number of events to be processed in that case by the MCS-API logic.

Overall, in terms of implementation, I wouldn't expect it to be much different compared to the annotation-based solution (except for the need of the additional synchronization logic, but you could mostly reuse already existing building blocks there). Yet, it avoids piggy-backing partially unrelated information into the derived services, as well as the possible fragility of annotations. 

That said, let me try to summarize my understanding of the overall flow in that case, to verify whether we are aligned there. Let's suppose we have two clusters A and B, with a Service S in cluster A to be exposed in B as well.

1. The user creates the `Service` S in cluster A, and subsequently a `ServiceExport` with matching namespace/name;
2. The clustermesh-apiserver (or cilium-operator, depending on whether Cilium operates in CRD/KVStore mode) observes the creation of the `ServiceExport`, and exposes the necessary information inside etcd.
3. The cilium-operator in every cluster combines for each ns/name the local `ServiceExport` information (if present) and the entries retrieved from the remote clusters through etcd, and creates the corresponding `ServiceImport` merging the different fields according to the conflict resolution strategy.
4. The cilium-operator in every cluster reconciles the `ServiceImport` and creates the corresponding derived service (i.e. with name `derived-$hash`). The derived service is marked as global, and optionally shared if the `ServiceExport` is present in the local cluster.
5. cilium-agents configure the BPF maps to load-balance that address using all available endpoints via the usual global service mechanisms. 
6. The cilium-operator optionally (e.g., in case of headless services) creates endpointslice objects for the endpoints in remote clusters via the logic you already introduced.
7. The already existing MCS-API controller reflects the Service's ClusterIP into the dedicated field of the `ServiceImport` resource.
8. Users in all clusters can access the exported service via the multicluster-aware DNS name.

/cc @marseel FYI, and in case you have any additional thoughts here.

**Comment by MrFreezeex** [comment]
Thanks for your input @giorio94 :pray:.

> Based on my understanding so far, I'm personally in favor of option 3 [...]

Sure, that sounds fair :+1:. Also this would allow me to decouple it from the endpointslicesync package (which I wanted to use to read remote service info), which is a good thing as it's cleaner although a bit more code would be involved.

> That said, let me try to summarize my understanding of the overall flow in that case, to verify whether we are aligned there. Let's suppose we have two clusters A and B, with a Service S in cluster A to be exposed in B as well.
> 
>     1. The user creates the `Service` S in cluster A, and subsequently a `ServiceExport` with matching namespace/name;
> 
>     2. The clustermesh-apiserver (or cilium-operator, depending on whether Cilium operates in CRD/KVStore mode) observes the creation of the `ServiceExport`, and exposes the necessary information inside etcd.
> 
>     3. The cilium-operator in every cluster combines for each ns/name the local `ServiceExport` information (if present) and the entries retrieved from the remote clusters through etcd, and creates the corresponding `ServiceImport` merging the different fields according to the conflict resolution strategy.
> 
>     4. The cilium-operator in every cluster reconciles the `ServiceImport` and creates the corresponding derived service (i.e. with name `derived-$hash`). The derived service is marked as global, and optionally shared if the `ServiceExport` is present in the local cluster.
> 
>     5. cilium-agents configure the BPF maps to load-balance that address using all available endpoints via the usual global service mechanisms.
> 
>     6. The cilium-operator optionally (e.g., in case of headless services) creates endpointslice objects for the endpoints in remote clusters via the logic you already introduced.
> 
>     7. The already existing MCS-API controller reflects the Service's ClusterIP into the dedicated field of the `ServiceImport` resource.
> 
>     8. Users in all clusters can access the exported service via the multicluster-aware DNS name.

Yep this is correct :+1:

**Comment by MrFreezeex** [comment]
not stale
