### ISSUE TITLE
CI: ci-gke tunnel-ingress-controller test failure due to error log

### ISSUE THREAD

**Issue by harsimran-pabla** [cilium/cilium#32710]
## CI failure

Error log : "failed to create or update CiliumEnvoyConfig: ciliumenvoyconfigs.cilium.io \"cilium-ingress\" already exists"
```
  ❌ Found 1 logs in gke_***_us-east1-c_cilium-cilium-9212928416-1-5/kube-system/cilium-operator-844bbb5c8d-bstp9 (cilium-operator) matching list of errors that must be investigated:
time="2024-05-23T18:28:12Z" level=error msg="Reconciler error" Ingress="{same-node cilium-test}" controller=ingress controllerGroup=networking.k8s.io controllerKind=Ingress error="failed to create or update CiliumEnvoyConfig: ciliumenvoyconfigs.cilium.io \"cilium-ingress\" already exists" name=same-node namespace=cilium-test reconcileID="\"ef60f392-b97a-4194-ac7d-6a8db992add3\"" subsys=controller-runtime (1 occurrences)
```

Sysdump : [cilium-sysdumps-ci-gke.zip](https://github.com/cilium/cilium/files/15436600/cilium-sysdumps-ci-gke.zip)
Job : https://github.com/cilium/cilium/actions/runs/9212928416/job/25345703260

**Comment by pippolo84** [comment]
Another one [here](https://github.com/cilium/cilium/actions/runs/9904400307/job/27361727705)

Full Logs: [logs_25927355270.zip](https://github.com/user-attachments/files/16194514/logs_25927355270.zip)
Sysdump: too big to upload, I'll keep a copy locally :(
