### ISSUE TITLE
Duplicate metrics with `envoy.prometheus.enabled=true` in Helm chart

### ISSUE THREAD

**Issue by seleznev** [cilium/cilium#32747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When you set `envoy.prometheus.enabled=true` both Pods (from `cilium-envoy` DaemonSet) and Service (`cilium-envoy`) have prometheus annotations which leads to double scraping:

* https://github.com/cilium/cilium/blob/v1.16.0-pre.2/install/kubernetes/cilium/templates/cilium-envoy/daemonset.yaml#L30-L31
* https://github.com/cilium/cilium/blob/v1.16.0-pre.2/install/kubernetes/cilium/templates/cilium-envoy/service.yaml#L10-L11

May be the Service should not be created at all for standalone Envoy DaemonSet (`envoy.enabled=true`)?

### Cilium Version

v1.15.5, v1.16.0-pre.2

### Kernel Version

5.15.0-97-generic

### Kubernetes Version

v1.28.8

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
I'm not sure why this is the case, seems like it could be an oversight. I've tagged in some relevant areas/SIGs to take a closer look. Alternatively, I would welcome you to propose a PR to fix this - that should trigger feedback from the relevant folks automatically.
