### ISSUE TITLE
Failure to bind envoy ingress to HTTP ports 80 and 443 on the host

### ISSUE THREAD

**Issue by wvh** [cilium/cilium#32768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running Cilium 1.16.0-rc.2 on a single host `k0s` cluster results in Envoy binding to default port 8080 on the host, both for the DaemonSet and the embedded envoy option. This is expected.

Both the `agent` container and the Envoy DaemonSet (if configured) have the `NET_BIND_SERVICE` capability.

The Cilium CLI `install` command also creates a `cilium-ingress` service of type `ClusterIP` in `kube-system` for ports 80 and 443.

Supposedly this ingress service should somehow get linked to the Envoy configuration if Envoy is to actually respond on port 80 and 443. There are no listening sockets open on the host for any HTTP traffic.

The expectation and goal is to have host port 80 and 443 routed to Envoy so it can serve as Ingress without external load balancer. I don't seem to be able to get anything bound on privileged ports nor do I get any errors in the Cilium agent or Envoy DaemonSet.

### Cilium Version

Cilium 1.16.0-rc.2

### Kernel Version

Linux harbor 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.30.1+k0s

### Sysdump

[cilium-sysdump-20240529-184639.zip](https://github.com/cilium/cilium/files/15486989/cilium-sysdump-20240529-184639.zip)

### Anything else?

These are the Cilium CLI arguments:

```shell
	./cilium install \
		--version v1.16.0-pre.2 \
		--helm-set-string cluster.name=$clusterName \
		--helm-set cluster.id=$meshID \
		--helm-set operator.replicas=1 \
		--helm-set-string kubeProxyReplacement=true \
		--helm-set envoy.securityContext.capabilities.keepCapNetBindService=true \
		--helm-set l7.backend=envoy \
		--helm-set ingressController.enabled=true \
		--helm-set ingressController.hostNetwork.enabled=true \
		--helm-set gatewayAPI.enabled=true \
		--helm-set gatewayAPI.hostNetwork.enabled=true \
		--helm-set operator.hostNetwork=true \
		--helm-set prometheus.enabled=false \
		--helm-set operator.prometheus.enabled=false
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @wvh, could you provide reproduction steps for this behaviour? This would help to confirm whether this is behaving as expected or not. Broadly what I would expect is that when the Ingress is created, Cilium will respond to the Ingress IP on ports 80 and 443 but it will not automatically bind these ports on the host IPs. Is that the IP/service you are attempting to connect to?

**Comment by wvh** [comment]
I don't know if you noticed the CLI command and arguments in the initial post,or if they are not sufficient.

If you install Cilium 1.16.x on a CNI-less `k0s` cluster with the arguments above, particularly `ingressController.hostNetwork.enabled=true`, Envoy will be listening on these ports:

```
LISTEN 0      4096         0.0.0.0:http-alt      0.0.0.0:*    users:(("cilium-envoy",pid=129602,fd=54))   
LISTEN 0      4096         0.0.0.0:http-alt      0.0.0.0:*    users:(("cilium-envoy",pid=129602,fd=53))   
LISTEN 0      4096         0.0.0.0:http-alt      0.0.0.0:*    users:(("cilium-envoy",pid=129602,fd=52))   
LISTEN 0      4096         0.0.0.0:http-alt      0.0.0.0:*    users:(("cilium-envoy",pid=129602,fd=51))   
LISTEN 0      4096         0.0.0.0:9964          0.0.0.0:*    users:(("cilium-envoy",pid=129602,fd=47))   
LISTEN 0      4096         0.0.0.0:9964          0.0.0.0:*    users:(("cilium-envoy",pid=129602,fd=46))   
LISTEN 0      4096         0.0.0.0:9964          0.0.0.0:*    users:(("cilium-envoy",pid=129602,fd=45))   
LISTEN 0      4096         0.0.0.0:9964          0.0.0.0:*    users:(("cilium-envoy",pid=129602,fd=44)) 
```

There will also be a service called `cilium-ingress`:

```
kubectl get -n kube-system svc/cilium-ingress
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
cilium-ingress   ClusterIP   10.111.225.223   <none>        80/TCP,443/TCP   35h
```

Both of these seem to work correctly.

My expectation was, after enabling Ingress Controller, for Envoy to handle the actual service listening on ports 80 and 443, and handle both unencrypted and encrypted traffic.

In the Helm chart, there is a setting `ingressController.hostNetwork.sharedListenerPort`, but it's not clear how that maps to a standard Ingress manifest that has an insecure HTTP and secure TLS configuration.

**Comment by joestringer** [comment]
Thanks for the additional context. When I install with instructions similar to yours (I had to drop the clustermesh config), I observe similar behaviour. I suspect what's going on here is that Cilium's Envoy configuration opens up alternative ports and then Cilium configures transparent proxy redirection to take traffic destined for another IP/port and directs that traffic into the Envoy instances.
