### ISSUE TITLE
Race condition between Cilium and other "control plane" workloads

### ISSUE THREAD

**Issue by jcmcken** [cilium/cilium#32770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium provides a configurable node startup taint to prevent application workloads from scheduling onto a node until Cilium is booted up and ready. This works fine with regular workloads. However it does not really work with other "control plane" workloads. A "control plane" workload typically means another ``DaemonSet`` (like a CNI) that tolerates arbitrary taints (so that it's guaranteed to start even if a node isn't "ready" for regular workloads). These are commonly things like cluster-wide infrastructure tooling, networking, security, monitoring, log ingestion, etc.

I've encountered two examples in my testing: AWS EBS CSI driver and Istio CNI. (Although there are lots of examples you could think of, and these examples are largely random -- it could've been another set of control workloads instead) In my tests, these workloads launched and came up before Cilium. Both of these workloads tolerate all taints and can't be reconfigured differently (using standard deployment artifacts). This lead to a situation where these pods did not have ``CiliumEndpoint`` objects defined, requiring them to be restarted manually.

So the claim here is that only using taints and tolerations is not really sufficient to eliminate the race condition.

You could say that this isn't Cilium's problem, that the AWS EBS driver and Istio CNI charts should be fixed. But these are only examples -- many charts have the same character: "control plane" workloads that tolerate all taints. This is a common problem that is not best solved by trying to adapt every other configuration to work better with Cilium, in my view.

You could also say that maybe Kubernetes itself needs some different way of expressing these dependencies besides just taints and tolerations (and maybe it already has that mechanism and I just missed it in my research -- happy to be corrected). And I would agree with that. Although this is more of a long-term way to address the problem, and it's not even clear if anything like that would land in Kubernetes even if it was advocated for.

I'm not sure exactly how this could be addressed. Istio CNI has a facility where it can "repair" (i.e. restart) pods which happened to start before the CNI. That could be an option, but I don't particularly like the idea of Cilium restarting the pods of other workloads necessarily. I'm not sure what other options there are except to fork all of the Helm charts for control plane components and use some different toleration configurations. But that seems like a very drastic, hard-to-maintain solution

### Cilium Version

1.15.5

### Kernel Version

Linux 6.1.84 (Bottlerocket 1.19.5)

### Kubernetes Version

1.28

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @jcmcken , what is the consequence of these control plane objects not having a corresponding CiliumEndpoint? Often the case with control plane `DaemonSets` is that they run in host network, and therefore should have a `CiliumEndpoint` but rather be represented as part of the underlying host, and hence they shouldn't be impacted by scheduling order compared to Cilium scheduling. But perhaps I misunderstand some piece of how you expect Cilium to control the behaviour of these other control plane DaemonSets.

I do think that there's a wider issue in the Kubernetes community with respect to how control plane infrastructure is provisioned, because there's a common pattern to deploy them as `DaemonSet` resources to make deployment comparatively very "easy", but this does not inherently provide many guarantees around bootstrap and ordering, which could potentially cause some issues (though I'm a little bit unclear on the exact consequences at this time).

**Comment by jcmcken** [comment]
@joestringer 

I'm not totally sure what the consequences are. I guess that's part of my question/concern. As you said, many of these use host networking, but not all of them in our case. Many of them also don't have network endpoints, except maybe metrics for Prometheus to scrape.

What's the behavior with Cilium policy if a managed pod tries to contact an unmanaged pod? For example if a policy is in place that would normally prevent a workload pod from talking to one of these daemonset pods, but the destination end is not actually managed? Does this fail closed or fail open?

**Comment by joestringer** [comment]
For host networking Pods, depending on whether you are applying host network policies, those policies should apply to all host network workloads once Cilium is installed and has synchronized with k8s and configured the policies locally.

For cases where they are not in host network, Cilium will not automatically start managing them by default. Label based policy may not apply to those Pods, which is to say that if you write policies for a Pod managed by Cilium that should allow the labels of the Pod not managed by Cilium, then the policy would not select that Pod's traffic, which could for instance lead to drops in cases where you wrote a policy to allow the traffic. The unmanaged Pods need to be restarted to ensure that Cilium network policy enforcement works for connections with that Pod, including enforcement for that Pod itself. See this docs page: https://docs.cilium.io/en/stable/installation/k8s-install-helm/#restart-unmanaged-pods

**Comment by julianwiedmann** [comment]
I'm not seeing any further docs for it, but https://github.com/cilium/cilium/pull/22911 might be of relevance here as well.
