### ISSUE TITLE
CFP: Stable release with Renovate

### ISSUE THREAD

**Issue by fmunteanu** [cilium/cilium#32825]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

I see you are currently using also Renovate. You mention the stable release version into new releases, as well into stable.txt file. 

**(Optional) Describe your proposed solution**

 I was wondering if is possible to add a tag `stable` to the stable release, so Renovate can pick it easy. I’m curious how you grab the stable releases, on your side. I see you use the same approach mentioned above, for all your products.

**Comment by aanm** [comment]
Hi, there isn't a `stable` tag as we don't use mutable tags in git. There's a mutable `stable` tag in the docker images that points out to the latest stable release.

If you want to grab the latest stable release this link will always point to the latest version https://raw.githubusercontent.com/cilium/cilium/main/stable.txt

I hope this answer your question.

**Comment by fmunteanu** [comment]
It does not @aanm. For example, K3s uses [release channels](https://update.k3s.io/v1-release/channels), which can be used with Renovate to get the latest stable release. Your text file cannot be parsed by Renovate. If you have a Renovate dependency of a stable version, you can filter it by specific branch. Still, this is not an elegant solution, best way is to have a release channel, where data is published.

How do you guys use Renovate to get a stable release from a file? Is impossible. hence the feature request.

**Comment by fmunteanu** [comment]
I found an elegant solution, see https://github.com/renovatebot/renovate/discussions/29375#discussioncomment-9624261 for reference.
