### ISSUE TITLE
Export prometheus metrics related to pkt drops and forwards

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#3284]
### Title

Expose prometheus metrics related to packet drops (L3-4/L7)

### Description of requested functionality

These are the metrics exposed by Cilium today:
```
cilium_endpoint_count 10
cilium_endpoint_regenerating 0
cilium_endpoint_regenerations{outcome="success"} 8085
cilium_event_ts{source="api"} 1.521829247812192e+09
cilium_event_ts{source="containerd"} 1.5218292444191875e+09
cilium_event_ts{source="k8s"} 1.5218292474256692e+09
cilium_policy_count 13
cilium_policy_import_errors 0
cilium_policy_max_revision 1340
cilium_process_cpu_seconds_total 4387.21
cilium_process_max_fds 1.048576e+06
cilium_process_open_fds 65
cilium_process_resident_memory_bytes 1.51744512e+08
cilium_process_start_time_seconds 1.52175297068e+09
cilium_process_virtual_memory_bytes 2.828111872e+09
```

Action Items:

- [x] Please consider adding drop metrics for L3-4 and L7 flows. They will be immensely useful for debugging issues.
- [x]  Include a datapath change to add a drop counter to the already existing forwarded counter.

**Comment by rlenglet** [comment]
This depends on https://github.com/cilium/cilium/pull/3278 first for L7.
L3/L4 is much harder to do with the current architecture (separate node-monitor daemon, etc.).

**Comment by tgraf** [comment]
> L3/L4 is much harder to do with the current architecture (separate node-monitor daemon, etc.).

Can't the node monitor push the metrics directly?

**Comment by rlenglet** [comment]
The normal way to use Prometheus is in pull mode, i.e. each pod exposes one HTTP port via a service, and Prometheus will pull metrics from that port.

We could have both cilium-agent and node-exporter expose each a distinct port, and have the cilium pod be a backend to 2 different services, each service being polled by Prometheus. But IMHO that starts to be complicated. I think it would be better to have only cilium-agent export metrics.

**Comment by rlenglet** [comment]
We could also consider moving node-exporter into its own daemon set? That would make things clearer.

**Comment by danwent** [comment]
@manalibhutiyani , we should make sure that we take L7 parser errors into consideration here as well, such as when we would see an error like: 

```
 71791 2018-05-07T21:35:05.82430428Z level=error msg="Unable to parse Kafka request; closing Kafka request connection" error="invalid array length" id="rx:10.15.254.34:54194->10.15.28.238:10236<->tx:closed"
```

**Comment by manalibhutiyani** [comment]
L3/L4 drop / forward Datapath bits are in this PR #4156

**Comment by manalibhutiyani** [comment]
Feature merged in master
