### ISSUE TITLE
proxy: Envoy crashes with segmentation fault 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3287]
Observed during CI runs:

```Mar 23 17:35:44 runtime cilium-agent[15403]: level=warning msg="Envoy: Proxy crashed" error="signal: segmentation fault (core dumped)"```

Related-to: #3233

**Comment by manalibhutiyani** [comment]
CC @jrajahalme @rlenglet

**Comment by rlenglet** [comment]
Yeah, we see that sometimes. It's harmless, even though it should be investigated.

Nothing to do with #3286. Removing from "related-to".

**Comment by tgraf** [comment]
How is an Envoy crash harmless? It destroys all state.

**Comment by rlenglet** [comment]
Sorry, that was a poor choice of words. What I meant was that it has not caused any build failure so far, AFAICT.

**Comment by tgraf** [comment]
> Sorry, that was a poor choice of words. What I meant was that it has not caused any build failure so far, AFAICT.

Are we positive that it is not introduced by our filter changes?

**Comment by rlenglet** [comment]
>> Sorry, that was a poor choice of words. What I meant was that it has not caused any build failure so far, AFAICT.
> Are we positive that it is not introduced by our filter changes?

We won't know until we get a backtrace in the Envoy logs, *and* we start collecting the Envoy logs in CI, *and/or* start redirecting the Envoy logs into the Cilium logs.
That is tracked in a separate issue (can't find it right now).

What we know is that since Cilium restarts Envoy immediately what that happens, those Envoy crashes are masked and haven't caused any CI failures so far.

**Comment by ianvernon** [comment]
We haven't seen segmentation faults in Envoy in some time in the CI. We have checks for it in the Ginkgo test framework to ensure that if such a failure occurs, we fail the build.

@rlenglet @jrajahalme can we close this in that case?

**Comment by rlenglet** [comment]
Yes, let's close this.
