### ISSUE TITLE
Excessive memory usage from cilium agents

### ISSUE THREAD

**Issue by isala404** [cilium/cilium#32940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have been running Cilium on few AKS clusters (BYOCNI) for about 10 months now. In one cluster we are observing excessive growth in memory usage for the Cilium agents running on each node. Within this cluster, we have approximately 15,000 pods running across 21,000 namespaces within ~75 nodes at any given time. Each namespace has one Cilium Network Policy, so the CNP count is around 21,000 as well. We have a pod per node limit set to 80.

Until about a month ago, we had our Memory Limit set to 2GB, and most of the pods were using approximately 1.5GB of memory. Then, we noticed that a few pods were starting to hit the 2GB memory limit. As a result, we scaled the memory request to 1.5GB and the memory limit to 3GB.

However, a month later, we are seeing some of the pods starting to hit the 3GB mark as well. We have been manually killing and restarting these pods, which temporarily brings the memory usage back down to around 2GB. We are confused as to why only 1-2 pods are experiencing such high memory usage while most of the pods are sitting around 2-2.5GB.

### Cilium Version

v1.14.7

### Kernel Version

5.15.0-1060-azure

### Kubernetes Version

1.28.5

### Anything else?

Memory Usage over time for cilium daemonset pods

![image](https://github.com/cilium/cilium/assets/29277992/ae295ab0-b7e8-4e6c-9217-15e98bf4b7d1)

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
I would suggest to upgrade to the latest Cilium version as there are some memory leaks fixed accordingly the https://github.com/cilium/cilium/blob/v1.14.11/CHANGELOG.md

**Comment by isala404** [comment]
Thanks for the pointer @aanm, we will update cilium to v1.14.11 and get back to you.

**Comment by isala404** [comment]
After upgrading to v1.14.12, memory usage of all pods started hovers around 1.2-1.5 GB (down from 2.8GB).

Thank you for the help!
