### ISSUE TITLE
Improvement on Limiting Identity-Relevant Labels page

### ISSUE THREAD

**Issue by liyihuang** [cilium/cilium#32969]
Overall this page(https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/) is confusing to a lot of new users . I can see serveral problems here. I would like to open the discussion and in this issue and can file some PR to improve it.

1. the doc is not updated with the latest code for default inclusive label patterns doc says `reserved:.*` `any:io\.kubernetes\.pod\.namespace`, `any:io\.cilium\.k8s\.namespace\.labels`  `any:app\.kubernetes\.io` where we have new one https://github.com/cilium/cilium/blob/main/pkg/labelsfilter/filter.go#L221 through PR(https://github.com/cilium/cilium/pull/31178/)

2. I think we misses some double backslash(https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#configuring-identity-relevant-labels). for example(`labels:  "k8s:io.kubernetes\\.pod\\.namespace k8s:k8s-app k8s:app k8s:name"`) should be `labels:  "k8s:io\\.kubernetes\\.pod\\.namespace k8s:k8s-app k8s:app k8s:name"
`

3. we should have a consistent way to help users to configure the label. I assume we prefer users to use plain text based on the discussion on slack than let users to configure prefix `k8s:` for labels. if that's the case, we should all use plain text in this page

4. we should have an example label config to pass the `cilium connecvitity test`(we use `kind` `other` and `io.cilium.k8s.policy.serviceaccount` labels in these manifest(https://github.com/cilium/cilium-cli/tree/9c6de693572b308960944edb812e770255574957/connectivity/builder/manifests ). I propose we should add the io.cilium.k8s.policy.serviceaccount as the default labels like what we have for this PR(https://github.com/cilium/cilium/pull/31178/)

Feel free to let me know if I need seperate these to different issues

**Comment by krokofant** [comment]
I noticed last week that the `labels` helm option isn't listed in the helm reference, and that `extraConfig` might instead be used to configure the labels.

**Comment by julianwiedmann** [comment]
:wave: I would suggest to just open a PR with the issues you identified, and discuss from there.

**Comment by liyihuang** [comment]
> I noticed last week that the `labels` helm option isn't listed in the helm reference, and that `extraConfig` might instead be used to configure the labels.

I think that's a mistake since I can see it's here 
https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml.tmpl#L1861

https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-configmap.yaml#L165-L168


I just dont know how the helm reference is generated.

**Comment by krokofant** [comment]
Still active. PR is moving forward...

**Comment by ovidiutirla** [comment]
I would like to bring some attention to https://github.com/cilium/cilium/issues/32576. I'm looking forward for any valuable input or changes in the design. The idea is to make this `labels` field dynamic and reduce the load on users to manually configure this. 
cc @liyihuang

**Comment by liyihuang** [comment]
I didn't know you proposal before and I will look into it later. I'm currently on PTO.

**Comment by liyihuang** [comment]
@ovidiutirla I read a bit on your issue and google doc. I think it's great for labels. However, as a heavy cilium user, it's not very attractive because there are too many config in cilium, some of them could work with restart and some can't. I can never remember if this change requires a restart. I always delete the operator and agent to make sure it works. Unless we can have a table or some log so we can tell if we require restart for changes, I will jut restart all the pods. I know it's beyond the scope of your issue and PR but would like to give you my honestest opinion about what I'm dealing with.

some discussion here https://github.com/cilium/cilium/issues/27867
