### ISSUE TITLE
cilium-agent binds to the "wrong" IP

### ISSUE THREAD

**Issue by figaw** [cilium/cilium#33011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "no-policies/pod-to-hostport"-tests fail.

```
📋 Test Report [cilium-test]
❌ 1/47 tests failed (3/493 actions), 33 tests skipped, 0 scenarios skipped:
Test [no-policies]:
  ❌ no-policies/pod-to-hostport/curl-1: cilium-test/client3-868f7b8f6b-48x24 (10.140.0.20) -> cilium-test/echo-same-node-7f896b84-2crf9 (10.158.97.7:4000)
  ❌ no-policies/pod-to-hostport/curl-2: cilium-test/client-69748f45d8-6rc8n (10.140.1.216) -> cilium-test/echo-other-node-58999bbffd-xxsfb (10.158.97.5:4000)
  ❌ no-policies/pod-to-hostport/curl-4: cilium-test/client2-ccd7b8bdf-mhxvw (10.140.1.121) -> cilium-test/echo-other-node-58999bbffd-xxsfb (10.158.97.5:4000)

[cilium-test] 1 tests failed
```

I've tried to test with `curl` from the two machines `10.158.97.7` and `10.158.97.5` and they're both able to reach "their own" port `4000`, but not each others.

I went into their respective agents, and noticed something funny, on e.g. the one running on `10.158.97.7`: 

```
root@control2:~# kubectl -n kube-system get po -owide | grep cilium
cilium-gs6zs                       1/1     Running   0          67m   10.158.97.9    control3   <none>           <none>
cilium-operator-854b8454fc-hf9v8   1/1     Running   0          68m   10.158.97.5    control1   <none>           <none>
cilium-xd86d                       1/1     Running   0          68m   10.158.97.7    control2   <none>           <none>
cilium-zzbmt                       1/1     Running   0          68m   10.158.97.5    control1   <none>           <none>
root@control2:~# kubectl -n kube-system exec -it cilium-xd86d -- cilium service list
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
ID   Frontend             Service Type   Backend
1    10.96.0.1:443        ClusterIP      1 => 10.158.97.7:6443 (active)
                                         2 => 10.158.97.5:6443 (active)
                                         3 => 10.158.97.9:6443 (active)
2    10.110.86.221:443    ClusterIP      1 => 10.158.97.7:4244 (active)
3    10.96.0.10:9153      ClusterIP      1 => 10.140.0.81:9153 (active)
                                         2 => 10.140.1.100:9153 (active)
4    10.96.0.10:53        ClusterIP      1 => 10.140.0.81:53 (active)
                                         2 => 10.140.1.100:53 (active)
5    10.101.210.22:8080   ClusterIP      1 => 10.140.1.225:8080 (active)
6    0.0.0.0:31992        NodePort       1 => 10.140.1.225:8080 (active)
7    10.158.96.32:31992   NodePort       1 => 10.140.1.225:8080 (active)
8    10.102.249.6:8080    ClusterIP      1 => 10.140.0.117:8080 (active)
9    10.158.96.32:32729   NodePort       1 => 10.140.0.117:8080 (active)
10   0.0.0.0:32729        NodePort       1 => 10.140.0.117:8080 (active)
11   10.158.96.32:4000    HostPort       1 => 10.140.1.225:8080 (active)
12   0.0.0.0:4000         HostPort       1 => 10.140.1.225:8080 (active)
root@control2:~# ip a show bond0
6: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 7e:bd:d5:ca:52:d1 brd ff:ff:ff:ff:ff:ff
    inet 10.158.97.7/22 metric 100 brd 10.158.99.255 scope global dynamic bond0
       valid_lft 433sec preferred_lft 433sec
    inet 10.158.96.32/32 scope global bond0
       valid_lft forever preferred_lft forever
    inet6 ... scope link
       valid_lft forever preferred_lft forever
```

The service has bound to `10.158.96.32:4000` instead of `10.158.97.7:4000`. We use the `.32`-address as a "keepalived"-ip that the nodes share, intended for the `kube-apiserver`.

When I tried from `10.158.97.5` to `curl 10.158.96.32:4000` it worked wonderfully.

When I look at the ciliumnodes, the IPs of the machines are correctly picked up as the `INTERNALIP`:

```
root@control2:~# kubectl get ciliumnodes -o wide
NAME       CILIUMINTERNALIP   INTERNALIP    AGE
control1   10.140.0.156       10.158.97.5   72m
control3   10.140.2.30        10.158.97.9   71m
control2   10.140.1.2         10.158.97.7   72m       
```

--- 

When I try the other way around.. from control2 to control1, it's the same thing.

I checked the services on `10.158.97.5` (control1,)

```
root@control1:~# kubectl -n kube-system exec -it cilium-zzbmt -- cilium service list
Defaulted container "cilium-agent" out of: cilium-agent...
ID   Frontend             Service Type   Backend
1    10.96.0.1:443        ClusterIP      1 => 10.158.97.7:6443 (active)
                                         2 => 10.158.97.5:6443 (active)
                                         3 => 10.158.97.9:6443 (active)
2    10.110.86.221:443    ClusterIP      1 => 10.158.97.5:4244 (active)
3    10.96.0.10:53        ClusterIP      1 => 10.140.0.81:53 (active)
                                         2 => 10.140.1.100:53 (active)
4    10.96.0.10:9153      ClusterIP      1 => 10.140.0.81:9153 (active)
                                         2 => 10.140.1.100:9153 (active)
5    10.101.210.22:8080   ClusterIP      1 => 10.140.1.225:8080 (active)
6    10.158.96.30:31992   NodePort       1 => 10.140.1.225:8080 (active)
7    0.0.0.0:31992        NodePort       1 => 10.140.1.225:8080 (active)
8    10.102.249.6:8080    ClusterIP      1 => 10.140.0.117:8080 (active)
9    10.158.96.30:32729   NodePort       1 => 10.140.0.117:8080 (active)
10   0.0.0.0:32729        NodePort       1 => 10.140.0.117:8080 (active)
11   10.158.96.30:4000    HostPort       1 => 10.140.0.117:8080 (active)
12   0.0.0.0:4000         HostPort       1 => 10.140.0.117:8080 (active)
root@control1:~# ip a show bond0
6: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 36:e1:91:d2:1e:ea brd ff:ff:ff:ff:ff:ff
    inet 10.158.97.5/22 metric 100 brd 10.158.99.255 scope global dynamic bond0
       valid_lft 354sec preferred_lft 354sec
    inet 10.158.96.31/32 scope global bond0
       valid_lft forever preferred_lft forever
    inet 10.158.96.30/32 scope global bond0
       valid_lft forever preferred_lft forever
    inet6 ... scope link
       valid_lft forever preferred_lft forever
```

Just as on the other one, we've allocated a bunch of extra IPs with keepalived, and it's binding on `10.158.96.30:4000` instead of `10.158.97.5:4000`.

When I try from control2 `10.158.97.7`, to run the command: `curl 10.158.96.30:4000` I get a good result.

I believe that this is a bug, or at least I struggle to figure out what configuration I have to set on the cilium-agents, so they bind to the specific "INTERNALIP" which it seems the tests at least are using (and rightfully should.)

It's a fresh kubernetes cluster, and a fresh installation of cilium.

### Cilium Version

cilium-cli: v0.16.10 compiled with go1.22.4 on linux/amd64
cilium image (default): v1.15.5
cilium image (stable): v1.15.5
cilium image (running): 1.15.5

### Kernel Version

Linux control1 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Linux control2 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.29.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5

### Sysdump

[cilium-sysdump-20240610-150636.zip](https://github.com/user-attachments/files/15767427/cilium-sysdump-20240610-150636.zip)

### Anything else?

I'm initializing the cluster with:

```shell
$ kubeadm init \
    --skip-phases=addon/kube-proxy \
    --control-plane-endpoint cluster.a.internal.mistware.eu \
    --pod-network-cidr=10.140.0.0/16 \
    --upload-certs
```

I'm installing cilium with:

```shell
$ cilium install --version 1.15.5 \
  --set ipam.mode=cluster-pool \
  --set ipam.operator.clusterPoolIPv4PodCIDRList="10.140.0.0/16"
```

The machines are using a bonded interface, called `bond0`.

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by figaw** [comment]
Just to be clear. The tests are "doing the right thing." They fail because the services aren't reachable on the IPs.

However, the services _should_ be made avaiable on the IPs by the agents. But the agents are using alternative IPs for the hosts.

**Comment by figaw** [comment]
For the record, `curl 10.158.96.30:4000` (control1) and `curl 10.158.96.32:4000` (control2) are both accessible from inside the pod running on control2:

```shell
root@control2:~# kubectl get pods -n cilium-test -o wide
NAME                               READY   STATUS    RESTARTS   AGE    IP             NODE     ...
client-69748f45d8-6rc8n            1/1     Running   0          102m   10.140.1.216   control2 ...
client2-ccd7b8bdf-mhxvw            1/1     Running   0          102m   10.140.1.121   control2 ...
client3-868f7b8f6b-48x24           1/1     Running   0          102m   10.140.0.20    control1 ...
echo-other-node-58999bbffd-xxsfb   2/2     Running   0          102m   10.140.0.117   control1 ...
echo-same-node-7f896b84-2crf9      2/2     Running   0          102m   10.140.1.225   control2 ...
host-netns-j48fx                   1/1     Running   0          102m   10.158.97.7    control2 ...
host-netns-mfntc                   1/1     Running   0          101m   10.158.97.9    control3 ...
host-netns-pbh4m                   1/1     Running   0          102m   10.158.97.5    control1 ...

root@control2:~# kubectl -n cilium-test exec -it client2-ccd7b8bdf-mhxvw -- /bin/sh
/ # curl -sI 10.158.96.30:4000 | head -1
HTTP/1.1 200 OK
/ # curl -sI 10.158.96.32:4000 | head -1
HTTP/1.1 200 OK
```

**Comment by dylandreimerink** [comment]
Looking at the statedb dump we see the following:
```
{
  "devices": [
    [...]
    {
      "Index": 6,
      "MTU": 1500,
      "Name": "bond0",
      "HardwareAddr": "36:e1:91:d2:1e:ea",
      "Flags": 19,
      "Addrs": [
        {
          "Addr": "10.158.97.5",
          "Secondary": false,
          "Scope": 0
        },
        {
          "Addr": "10.158.96.31",
          "Secondary": false,
          "Scope": 0
        },
        {
          "Addr": "10.158.96.30",
          "Secondary": false,
          "Scope": 0
        },
        {
          "Addr": "fe80::34e1:91ff:fed2:1eea",
          "Secondary": false,
          "Scope": 253
        }
      ],
      "RawFlags": 70723,
      "Type": "bond",
      "MasterIndex": 0,
      "Selected": true,
      "NotSelectedReason": ""
    },
    [...]
  ],
  "node-addresses": [
    [...]
    {
      "Addr": "10.158.96.30",
      "NodePort": true,
      "Primary": true,
      "DeviceName": "bond0"
    },
    {
      "Addr": "10.158.96.31",
      "NodePort": false,
      "Primary": false,
      "DeviceName": "bond0"
    },
    {
      "Addr": "10.158.97.5",
      "NodePort": false,
      "Primary": false,
      "DeviceName": "bond0"
    },
    [...]
  ]
}
```

So according to netlink the bond device has 3 primary IPs, Cilium currently uses the following [sorting algorithm](https://github.com/cilium/cilium/blob/v1.15.5/pkg/datapath/tables/node_address.go#L429):
```
// sortedAddresses returns a copy of the addresses sorted by following predicates
// (first predicate matching in this order wins):
// - Primary (e.g. !IFA_F_SECONDARY)
// - Scope, with lower scope going first (e.g. UNIVERSE before LINK)
// - Public addresses before private (e.g. 1.2.3.4 before 192.168.1.1)
// - By address itself (192.168.1.1 before 192.168.1.2)
//
// The sorting order affects which address is marked 'Primary' and which is picked as
// the 'NodePort' address (when --nodeport-addresses is not specified).
```

So since all your IPs are equal, we pick `10.158.96.30` since its smallest. But as the comment suggest you can use the `--nodeport-addresses` flag / `nodeport-addresses` configMap property to specify a list of CIDRs which would be preferred as nodeport addresses. Unfortunately it seems like there is no helm value exposed for this flag, so you might need to edit the configMap directly for now.

Alternatively, you could look into marking some addresses as secondary or modifying their scope, I don't know if this is possible or how that would work with bond devices, I have little experience configuring bonded devices.

**Comment by figaw** [comment]
Thank you for your answer, this is super helpful!

Just to be clear, since I have my nodes on the `10.158.97.0/24`, if I set this as the `--nodeport-addresses` it will still choose the appropriate one from there, with respect to the node, (in the example `10.158.97.5`) and not just suddenly start from `10.158.97.1`, right?

**Comment by figaw** [comment]
Just for the record, I had great success with using `--set extraConfig.nodeport-addresses="10.158.97.0/24"`

**Comment by dylandreimerink** [comment]
> Before we close this issue, would you mind telling me how you decide whether an IP is primary or secondary? (Where do you read this information from?)

That happens here: https://github.com/cilium/cilium/blob/v1.15.5/pkg/datapath/tables/node_address.go#L326. So essentially, the first IPv4 we find will be primary and the first IPv6 we find is primary. That is why the sorting order is so important.

> Just for the record, I had great success with using --set extraConfig.nodeport-addresses="10.158.97.0/24" with helm.

That is great to hear!
