### ISSUE TITLE
Handle NodePort health-checking for Cilium envoy (Ingress/GwAPI) in case of `externalTrafficPolicy=Local`

### ISSUE THREAD

**Issue by PhilipSchmid** [cilium/cilium#33038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[#32873](https://github.com/cilium/cilium/pull/32873) introduced `externalTrafficPolicy=Local` support for Cilium Ingress and GatewayAPI. However, when running on environments where the LB Service load balancer does `localEndpoints` validation of the NodePort endpoints ([via the `healthCheckNodePort ` port](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)), it will never see healthy endpoints (e.g., on Azure) due to how we currently handle Cilium Ingress/GwAPI LB service endpoints. Hence, traffic is never actually forwarded towards the K8s NodePorts.

Detailed reproduction steps are described [here](https://github.com/cilium/cilium/pull/32873#issuecomment-2154379375) (open the `Detailed Instructions for GwAPI on AKS BYOCNI E2E Testing` panel).

Here is an example health-check output fetched from within a Cilium Agent (`31220` is the `healthCheckNodePort` for this GwAPI LB Service with eTP=Local):
```bash
root@aks-nodepool1-22213563-vmss000000:/home/cilium# curl -v http://10.224.0.6:31220/healthz
*   Trying 10.224.0.6:31220...
* Connected to 10.224.0.6 (10.224.0.6) port 31220 (#0)
> GET /healthz HTTP/1.1
> Host: 10.224.0.6:31220
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< X-Load-Balancing-Endpoint-Weight: 0
< Date: Mon, 10 Jun 2024 14:45:04 GMT
< Content-Length: 92
<
{"service":{"namespace":"infra","name":"cilium-gateway-shared-gateway"},"localEndpoints":0}
* Connection #0 to host 10.224.0.6 left intact
```

The the reference, this `/healthz` endpoint (`httpHealthServer`) is created [here](https://github.com/cilium/cilium/blob/e3de64024f83af4ead2e457e26a7476ee191e68a/pkg/service/healthserver/healthserver.go#L214-L229), and the check for active backends happens [here](https://github.com/cilium/cilium/blob/fdc9bf9d2f0ff2841a12b3e09b0d0371716e113d/pkg/service/service.go#L835-L851).

I suspect we’ll never get a `localEndpoints` number higher than 0 there for Cilium Ingress/GwAPI, as we don’t (can’t?) set Envoy as a valid Service endpoint but rather use the `192.192.192.192:9999`-endpoint workaround:
```bash
$ k describe svc cilium-gateway-shared-gateway -n infra
Name:                     cilium-gateway-shared-gateway
Namespace:                infra
Labels:                   io.cilium.gateway/owning-gateway=shared-gateway
Annotations:              <none>
Selector:                 <none>
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.0.183.121
IPs:                      10.0.183.121
LoadBalancer Ingress:     4.152.250.49
Port:                     port-80  80/TCP
TargetPort:               80/TCP
NodePort:                 port-80  32299/TCP
Endpoints:                             # <- empty :-(
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     31220
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  43m   service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   43m   service-controller  Ensured load balancer
```

As we [can't get rid](https://github.com/cilium/cilium/issues/19262) of the `192.192.192.192:9999`-endpoint workaround just like that, we would probably need to consider implementing a special “HealthCheck NodePort” logic for Cilium Ingress/GwAPI. What do you think about that?
Also, another question is: Do we need to revert https://github.com/cilium/cilium/pull/32873 until we come up with a proper solution for the described issue?

### Cilium Version

`main` branch

### Kernel Version

Doesn't matter

### Kubernetes Version

Doesn't matter

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for logging this @PhilipSchmid!

Yes, because we do special handling for Ingress and Gateway API LB Services to redirect the traffic to the node Envoy, we'll need to do special handling of this as well.

Once #33040 merges, then Nodeports in Loadbalancer Services will be correctly forwarded to Envoy, so I should be able to build on that to add support for handling the `healthCheckNodeport` as well. This is a bug, so is not caught in feature freeze, so I should be able to proceed.

**Comment by PhilipSchmid** [comment]
Fixed by https://github.com/cilium/cilium/pull/33600
