### ISSUE TITLE
Replace deprecated gRPC Dial options in Hubble sub-systems

### ISSUE THREAD

**Issue by chancez** [cilium/cilium#33065]
Replace the deprecated gRPC dial options in Hubble CLI, Hubble-relay (peer client + observer client). This includes `grpc.WithBlock` at the very least, but there may be a few other options too. 

Functionally, removing the `WithBlock` option will mean connection failures will only surface when making an RPC, not on the Dial.

### Context

[gRPC  Go]( https://github.com/grpc/grpc-go) deprecated `DialContext` with version `v1.63.0`.  We consistently use `DialContext` with `grpc.WithBlock()`. So switching to the recommended `NewClient` would change the behavior.

We need to figure out if we should change the behavior or somehow keep the current behavior while using `NewClient`.

### Acceptance Criteria

* The deprecated `DialContext` calls are replaced
* Other deprecated gRPC dial options are removed/replaced.
* Verify tests are _reliable_, they may become flakey. They likely will rely on the blocking behavior.

### Related Links
* Upstream points out our current approach is an anti-pattern: https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md#dialing-in-grpc

**Comment by devodev** [comment]
Status
- Hubble CLI updated in [PR](https://github.com/cilium/cilium/pull/34241)
- Hubble Relay [PR](https://github.com/cilium/cilium/pull/34261) opened but close by author

I will try to take over the Relay changes in the coming days.
