### ISSUE TITLE
Remove non-actionable config validation warning

### ISSUE THREAD

**Issue by alex-berger** [cilium/cilium#33095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When setting Helm value `apiRateLimit` or otherwise providing the `api-rate-limit` config value in Cilium's _ConfigMap_, then Cilium Agent produces non-actionable log messages with level **warning**, like the one below:

```
level=warning msg="Unable to validate option api-rate-limit value of type stringToString" subsys=config
```

There is nothing one can do about it, the `api-rate-limit` setting is actually valid and everything works as expected. However, the log message is misleading as it suggest that something is wrong and that one might have to fix the `api-rate-limit` config.

Those log messages are generated by https://github.com/cilium/cilium/blob/v1.15.6/pkg/option/config.go#L4190, because the config validation logic does not know how to validate the `api-rate-limit` (which does not mean that the config is wrong). I suggest we either 
- (A) completely remove that log message, as it is not actionable at all
- (B) or at least change the log level from `warning` to `info` and adapt the wording to make it more clear that there is nothing wrong with the config.
- (C) or implement proper validation for the `stringToString` type and only log if that validation fails 

### Cilium Version

1.15.6

### Kernel Version

6.1.90

### Kubernetes Version

1.29.4

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
> (A) completely remove that log message, as it is not actionable at all

I worry that this is generic code that could protect users who misconfigure other flags. Not sure if this is the right path.

> (B) or at least change the log level from warning to info and adapt the wording to make it more clear that there is nothing wrong with the config.

Related to above: If there is an error but for a different flag, then setting it to info could lead the user to think that the error isn't a problem when it actually is a problem.

> (C) or implement proper validation for the stringToString type and only log if that validation fails

I think this proposal makes the most sense, add a new case to the switch for `stringToString` and validate that format.

**Comment by aanm** [comment]
@alex-berger would you like to implement (C)?

**Comment by alex-berger** [comment]
@aanm implemented (C) in https://github.com/cilium/cilium/pull/33779.

**Comment by alex-berger** [comment]
https://github.com/cilium/cilium/pull/33779 caused a regression and was reverted in https://github.com/cilium/cilium/pull/34277. 

@joestringer @aanm Can we please reopen this issue.
