### ISSUE TITLE
there's no communication for ARP from cilum to upstream server

### ISSUE THREAD

**Issue by zhongguanqun** [cilium/cilium#33090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

docker run -d --network host --privileged -v /sys/fs/bpf:/sys/fs/bpf -v /lib/modules -it cilium/cilium:v1.14.11 cilium-agent \
    --enable-ipv4=true \
    --enable-ipv6=false \
    --datapath-mode=lb-only \
    --bpf-lb-algorithm=maglev \
    --bpf-lb-dsr-dispatch=ipip \
    --bpf-lb-acceleration=native \
    --bpf-lb-mode=dsr \
    --devices="enp6s+" \
    --direct-routing-device=enp6s18

### Cilium Version

1.14.11

### Kernel Version

5.14.0-362.8.1.el9_3.x86_64

### Kubernetes Version

N/A，metal

### Regression

N/A

### Sysdump

N/A

### Anything else?

invoke a http request ingress to cilium， timeout

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
Hi, this is a bit light on details. Services such as ingresses do not respond to ARP requests to the virtual IPs by default, you should checkout https://docs.cilium.io/en/latest/network/l2-announcements/ if you want that behavior.

**Comment by ti-mo** [comment]
Closing for now, sounds like this is to be expected.
