### ISSUE TITLE
Cilium perpetually out of sync within argo-cd due to spire-agent socket mount 'readOnly'

### ISSUE THREAD

**Issue by jadedeane** [cilium/cilium#33162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium spire ds socket mount [set 'readOnly: false'](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/spire/agent/daemonset.yaml#L72) causes argo-cd to be perpetually out of sync:

![Screenshot 2024-06-14 at 4 30 18 PM](https://github.com/cilium/cilium/assets/11843794/04304ab2-e892-4aa4-a10c-7d342a7157e6)

### Cilium Version

v1.15.6

### Kernel Version

6.8.0-35-generic

### Kubernetes Version

1.30.2-1.1

### Sysdump

[cilium-sysdump-20240614-163302.zip](https://github.com/user-attachments/files/15844814/cilium-sysdump-20240614-163302.zip)

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jadedeane** [comment]
Seeing same thing w/Envoy:
![Screenshot 2024-06-15 at 10 07 47 AM](https://github.com/cilium/cilium/assets/11843794/da8a63bd-dea3-4664-9afb-139108707aeb)

**Comment by ti-mo** [comment]
Hi, thanks for the issue. Could you elaborate; why does this cause it to get out of sync? What's your proposed alternative?

**Comment by aanm** [comment]
We have a section in our documentation about ArgoCD issues in [here](https://docs.cilium.io/en/v1.15/configuration/argocd-issues/). Let us know if that documentation is not clear enough.

**Comment by jadedeane** [comment]
> We have a section in our documentation about ArgoCD issues in [here](https://docs.cilium.io/en/v1.15/configuration/argocd-issues/). Let us know if that documentation is not clear enough.

Apologies for not following-up sooner.

Yes, very familiar with that documentation, in particular vis-a-vis Hubble, certs, etc.

Updated to 1.15.7.

Something about 'readOnly: false' on the above is causing Argo CD to churn.

**Comment by jadedeane** [comment]
Resolved per Argo CD [issue](https://github.com/argoproj/argo-cd/issues/19038) (tl;dr, 'server-side apply' [here](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply))
