### ISSUE TITLE
CI / GSG : make Kafka service headless

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#3319]
The current Kafka yaml in GSG and K8ts test have the Kafka service as a ClusterIP service. When we enforce an allow-all policy, and try to consume, the Kafka broker sends out a service discovery request for the other brokers. Ideally it should resolve to itself (with a single broker configuration), but there is currently a bug in data path which does not resolve the reverse NAT for loopback address correctly. By making this service headless, we can avoid the request from leaving the node altogether.
This also fixes the "first consume delay" which we see due to drops in data path for the Kafka broker service discovery requests.

**Comment by tgraf** [comment]
> There is currently a bug in data path

What bug? Did we find something?

**Comment by manalibhutiyani** [comment]
@tgraf : I will update this with the logs in a minute, but this is the loopback address reverse NAT resolution bug we discussed.

**Comment by manalibhutiyani** [comment]
The workaround is to make the Kafka service headless. I will raise a separate GH issue for the data path bug to correctly do the reverse NAT for loopback addresses.
