### ISSUE TITLE
LB-IPAM: Add min/maxItems constraints to CiliumLoadBalancerIPPool

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#33203]
We would like to start using [CEL](https://kubernetes.io/docs/reference/using-api/cel/) for validation within Cilium, this requires that bounds are placed on the potential complexity of CRDs. So its good practice to start adding min/maxItems constraints wherever we can including on the amount of blocks / ranges that can be specified in pools.

**Comment by aanm** [comment]
@dylandreimerink are there any plans to work on this item? Is this being tracked by the lb-ipam sig?

**Comment by dylandreimerink** [comment]
I made sure this issue is being tracked, I currently don't know when work on this will start, getting it in before the next feature freeze would be nice. I created the issue on behalf of @sayboras but I have no details as to its urgency.
