### ISSUE TITLE
Cilium v.1.15 host firewall ignores virtual IPs on the localhost (lo) interface

### ISSUE THREAD

**Issue by tenyo** [cilium/cilium#33214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On our Kubernetes clusters we have (kube-vip) virtual IPs on the `lo` interface. We are running cilium with `kube-proxy-replacement` and `host-firewall`, and we have a CCNP to restrict ingress to all of the host IPs. After upgrading cilium from v1.14 to v1.15 the existing CCNP starts allowing all connections to the `lo` VIP. Connections to other host IPs (e.g. on `bond0`) are still dropped as expected.
When comparing the `cilium ip list` output between 1.14 and 1.15, I no longer see the VIP listed as `reserved:host` in the new cilium version (but it shows up as `reserved:world`).

Is this expected behavior in cilium v1.15?

### Cilium Version

v1.15 (reproduces with both v1.15.2 and v.1.15.6)

### Kernel Version

6.1.90-flatcar

### Kubernetes Version

v1.29.5

### Regression

v1.14.11

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tylerauerbeck** [comment]
Any update on this? Curious whether this is expected behavior or not.

**Comment by joestringer** [comment]
I don't see a release note in the upgrade guide here, so I'm not sure whether this was intentional:
https://docs.cilium.io/en/v1.15/operations/upgrade/#upgrade-notes

**Comment by joamaki** [comment]
This could be related to https://github.com/cilium/cilium/issues/33234. The fix for that has been merged and will be in the next v1.15 release. The loopback interface is usually ignored unless it's explicitly listed with "devices" option though, so that might also be needed in addition to this. In addition to the "cilium-dbg ip list" command you can also see addresses that Cilium considers as the node's addresses can also be inspected with "cilium-dbg statedb node-addresses".

**Comment by tenyo** [comment]
Thanks, looking forward to trying the next release to see if it fixes this issue.
In our case we do _not_ have `enable-runtime-device-detection` but from what I can tell this is related to the fix in the second commit.
We've never had to explicitly list lo under devices (and it works fine in 1.14) but maybe that's a change in 1.15. Although I've tried adding lo to the devices list in v1.15.6 and it didn't make a difference.

**Comment by tenyo** [comment]
I tested today with 1.16.0 which includes the above mentioned fix but we're still having the same problem - the lo IP is not recognized as a `reserved:host`. I also tried adding lo to the devices list but it didn't make a difference (except now it shows lo under the Host Firewall devices).
The lo VIP in our case is 150.75.xx.xx - below is relevant output after deploying v1.16.

Is there anything else we need to configure in order to get this working properly? This stopped working in v1.15.

```
cilium-dbg status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.29 (v1.29.2) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    True      [lo    127.0.0.1 150.75.xx.xx, bond0     140.28.xx.xx 10.68.77.147  (Direct Routing)]
Host firewall:           Enabled   [lo, bond0]
SRv6:                    Disabled
CNI Chaining:            none
CNI Config file:         successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                  Ok   1.16.0 (v1.16.0-82999990)
NodeMonitor:             Listening for events on 64 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 33/254 allocated from 192.168.0.0/24,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        EDT with BPF [CUBIC] [lo, bond0]
Routing:                 Network: Tunnel [vxlan]   Host: BPF
Attach Mode:             Legacy TC
Device Mode:             veth
Masquerading:            BPF   [lo, bond0]   192.168.0.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       208/208 healthy
Proxy Status:            OK, ip 192.168.0.116, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Disabled
Encryption:              Wireguard       [NodeEncryption: OptedOut, cilium_wg0 (Pubkey: WVgu2813dVKeRy9+k1bQ3WYKvRihmFtMPTUyTzvWxWY=, Port: 51871, Peers: 0)]
Cluster health:          1/1 reachable   (2024-07-24T21:30:15Z)
Modules Health:          Stopped(0) Degraded(0) OK(126)
```

```
cilium-dbg statedb node-addresses
# Address                   NodePort   Primary   DeviceName
140.28.xx.xx                false      false     bond0
10.68.77.147                true       true      bond0
150.75.xx.xx                false      true      *
192.168.0.116               false      true      cilium_host
```

The 150.75.xx.xx IP is missing below and consequently, connections to that IP are not being blocked by cilium network policies.
```
cilium-dbg ip list | grep "reserved:host"
10.68.77.147/32               reserved:host
140.28.xx.xx/32               reserved:host
192.168.0.116/32              reserved:host
```

**Comment by joamaki** [comment]
Indeed `lo` is excluded when computing the node addresses, while the devices controller is selecting it for use (https://github.com/cilium/cilium/blob/main/pkg/datapath/tables/node_address.go#L443). 
I'll prepare a fix.

A workaround for this issue is to assign the device to a non-loopback device, e.g. dummy0.

**Comment by tenyo** [comment]
Thanks a lot @joamaki ! This will allow us to keep up with the latest cilium updates as we're currently stuck on 1.14. I can also look into using a different device (like dummy0) but we have a ton of existing clusters with this setup so it will require some work to change.
From cilium perspective is what we're doing (assigning a public VIP on lo) considered an anti-pattern?

**Comment by joamaki** [comment]
I wouldn't say it's an anti-pattern, it's just slightly unusual, which is why the recent refactoring didn't manage to retain the behavior.

**Comment by tenyo** [comment]
Just tested with v1.15.8 and it appears to resolve this issue! Loopback addresses are now properly handled by the cilium network policies. Thanks a lot for the fix!
