### ISSUE TITLE
cilium endpoint get indentation is weird for rules

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3322]
```
$ cilium endpoint get <EPID>
...
      "l4": {
        "egress": [],
        "ingress": [
          {
            "rule": {
   "port": 9042,
   "protocol": "TCP"
 }
          },
...
```

The indentation of the actual rule elements is weird, probably this is the `expandNestedJSON()` function not taking into account the current level of indentation.

Note that this is for the regular `cilium endpoint get` output, **not** with `-o json` (which prints the raw JSON from the server)

**Comment by ishantanu** [comment]
Are you referring to this:
```go
		// Determine the current indentation
		for i := 0; i < loc[0]-1; i++ {
			idx := loc[0] - i - 1
			if resBytes[idx] != ' ' {
				break
			}
			indent = fmt.Sprintf("%s ", indent)
		}
```

**Comment by joestringer** [comment]
@iamShantanu101 That would be my guess. By the way, you can link directly to code by browsing it on github, hovering over a line, clicking the "..." and clicking it, then "Copy Permalink", eg:

`https://github.com/cilium/cilium/blob/f8e147bcd072638ffedad2319fae4c3e2a7e6f19/cilium/cmd/helpers.go#L129-L136`

https://github.com/cilium/cilium/blob/f8e147bcd072638ffedad2319fae4c3e2a7e6f19/cilium/cmd/helpers.go#L129-L136

**Comment by ishantanu** [comment]
After adding `-o json` to the endpoint command, I am seeing something like this:
```json
    "mac": "6a:a4:5f:56:f4:99",
    "pod-name": ":",
    "policy": {
      "allowed-egress-identities": [],
      "allowed-ingress-identities": [],
      "build": 3,
      "cidr-policy": {
        "egress": [],
        "ingress": []
      },
      "id": 57340,
      "l4": {
        "egress": [],
        "ingress": [
          {
            "derived-from-rules": [
              [
                ":name=l3-rule"
              ]
            ],
            "rule": "{\n  \"port\": 80,\n  \"protocol\": \"TCP\"\n}"
          }
        ]
      }
    },
```

Note the `:` for `pod-name` value and the l3 rule name. Related to regex?

https://github.com/cilium/cilium/blob/f8e147bcd072638ffedad2319fae4c3e2a7e6f19/cilium/cmd/helpers.go#L115-L116

**Comment by joestringer** [comment]
@iamShantanu101 the `-o json` prints the raw json response from the server. This bug is actually looking at the regular output, where we attempt to interpret nested strings like this to expand it out so it's easier to understand. This is not so much of a problem for just L4 rules, but when L7 is involved the nested JSON string can be very long and very hard to read.

I updated the description for this.

**Comment by ishantanu** [comment]
@joestringer Subsitituting the indent value
https://github.com/cilium/cilium/blob/f8e147bcd072638ffedad2319fae4c3e2a7e6f19/cilium/cmd/helpers.go#L135 with
```
indent = fmt.Sprintf("\t%s\t", indent)
```
 is resolving the issue. Tested for both L4 as well as L7 rules.
