### ISSUE TITLE
Add log ratelimiter

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3323]
Add the ability to ratelimit logs, so that cases where we're concerned that logging will be too verbose if an adverse condition is hit, we can instead just define a static ratelimiter and apply that to the logging of the particular message.

**Comment by noqcks** [comment]
@joestringer to reiterate and clarify, this static rate limit would not apply at a global level to all logs but only to logs of a specific type over a time period?

**Comment by joestringer** [comment]
@noqcks correct, the idea would be to provide granularity so that if there is a recurring log in one subsystem going crazy, then it can be silenced.

When the ratelimiter is used, it should also print periodically how many messages have been dropped due to the ratelimit, and over what period.

**Comment by joestringer** [comment]
The easiest way for this might be via some new logging hook similar to the metrics one in `pkg/logging/`.

**Comment by joestringer** [comment]
For what it's worth, this issue gives a good example of a log that should be ratelimited: https://github.com/cilium/cilium/issues/19202

**Comment by joestringer** [comment]
One fairly naive method for doing log ratelimiting could be to use trigger for individual log points:

```
	LogTrigger, _ = trigger.NewTrigger(trigger.Parameters{
		MinInterval: time.Minute,
		TriggerFunc: logTriggerFunc(log.Warning),
		Name:        "MyLogWarning",
	})
)

func logTriggerFunc(log func(args ...interface{})) func([]string) {
	return func(msgs []string) {
		for _, msg := range msgs {
			log(msg)
		}
	}
}
```

I think the downside of this is that it feels fairly heavyweight to be able to be reused in different places in the codebase. It'd be nice if we had a simpler interface to be able to declare such triggers and allow specific log messages to be ratelimited together, perhaps either by subsystem or even on a case-by-case basis for particular log messages.

The other downside of the above approach is that it breaks structured logging (`log.WithFields(...)...`). Ideally we would retain structured logging support.

**Comment by lambdanis** [comment]
There was a log rate limiter added in https://github.com/cilium/cilium/pull/12567/commits/68b56345e0c9e4b2f61b31782d66efcbf73e374f. It's a very simple wrapper around [rate.Limiter](https://pkg.go.dev/golang.org/x/time/rate#Limiter) - to rate limit a message you instantiate a `logging.Limiter` with desired interval+burst, and then wrap the log in `if logLimiter.Allow() { ... }`.

Is there a need for any extra functionality? If log rate limiting is used sparingly (and IMO it should be), then the current solution seems enough to me.

**Comment by joestringer** [comment]
LGTM thanks! Maybe we just need to reshare this capability more frequently amongst committers.
