### ISSUE TITLE
cilium does not create Gateway class

### ISSUE THREAD

**Issue by hellt** [cilium/cilium#33239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have installed the v1.0.0 Gateway API CRDs and after that performed an install of Cilium using the following:

```bash
helm template \
cilium \
cilium/cilium \
--version 1.16.0-pre.3 \
--namespace kube-system \
-f cilium-values.yml \
> talos/cilium-manifest.yml
```

the inputs file is:

```yaml
ipam:
  mode: kubernetes
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent:
      [
        CHOWN,
        KILL,
        NET_ADMIN,
        NET_RAW,
        IPC_LOCK,
        SYS_ADMIN,
        SYS_RESOURCE,
        DAC_OVERRIDE,
        FOWNER,
        SETGID,
        SETUID,
      ]
    cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445
gatewayAPI:
  enabled: true
  hostNetwork:
    enabled: true
```

Then I proceed with installing the gateway:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  namespace: test
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 8080
      name: web-gw
      allowedRoutes:
        namespaces:
          from: Same
```

But then `cilium-operator` complains that no `cilium` gateway class is available:

```
2024-06-18 16:57:07.650Z cilium-operator-c85775f8d-dcn5n time="2024-06-18T16:57:07Z" level=error msg="Unable to get GatewayClass" controller=gateway error="GatewayClass.gateway.networking.k8s.io \"cilium\" not found" resource=my-gateway subsys=gateway-controller
```

I wonder, how do I identify why the operator did not create the gateway class?

### Cilium Version

1.16.0-pre3

### Kernel Version

6.6.32-talos

### Kubernetes Version

1.30.1

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mhofstetter** [comment]
Hey @hellt :wave: 

The `GatewayClass` is part of the Cilium Helm Chart (and not created by the Cilium Operator).

https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-gateway-api-class.yaml

The `GatewayClass` only gets installed if Gateway API is enabled and the CRD with the expected API version is installed on the cluster.

It uses  `.Capabilities.APIVersions.Has` where Helm makes a request to the cluster during an installation (`helm install`).

When using `helm template` one has to manually pass the additional supported CRDs. It's also recommended to do the same with the k8s version.

https://helm.sh/docs/helm/helm_template/

```
--api-versions strings                       Kubernetes api versions used for Capabilities.APIVersions
--kube-version string                        Kubernetes version used for Capabilities.KubeVersion
```

---

Your issue should be solved by adding  `--api-versions='gateway.networking.k8s.io/v1/GatewayClass'` to your Helm templating command.

```
helm template \
cilium \
cilium/cilium \
--version 1.16.0-pre.3 \
--namespace kube-system \
--api-versions='gateway.networking.k8s.io/v1/GatewayClass' \
-f cilium-values.yml \
> talos/cilium-manifest.yml
```

**Comment by hellt** [comment]
oh wow, thanks @mhofstetter! adding this flag immediately solved the issue.
Since inline manifests are the recommended way to install Cilium CNI according to Talos docs I stepped into this trap not knowing that helm checks the presence of the certain CRDs

Thank you very much for providing this insight, it reolved my issue immediately.

**Comment by balous** [comment]
I think this could be a problem in environments where you can't influence the order of helm chart installation like CAPI helm addon (CAAPH). In such a scenario, you just upload bunch of `helmchartproxy` CRs to the cluster (containing chart parameters like repo, name and values). One of the CRs installs Cilium and the other installs GatewatAPI.

Than you instantiate a cluster - CAPI provisions some nodes and installs kubernetes inside. As soon as the new cluster's API is accessible, CAAPH installs all the charts in undefined order. This way, you end up either with cluster with class or without class. Such scenarios need a way to force creation of the class.

**Comment by hellt** [comment]
yes, I do agree with @balous 
My expectation was that the cilium controller would apply the GW API manifests on its own (as well as it knows what GW API version is supported by the controller). This seems to be a logical way of handling that.

**Comment by balous** [comment]
I have no problem in packaging the GW API CRDs separately, but need consistent behavior from the cilium chart.

CAAPH does normal reconcile, if the chart installation fails, it is retried. I have a similar example with kubernetes-prometheus-stack which installs CRDs that are used by cilium too. It works, you just see some errors in CAAPH logs as Cilium installation has to be retried.

**Comment by youngnick** [comment]
For Gateway API, the problem is that this is an upstream set of CRDs, that multiple implementations may want to install - and each of those implementations may want to install different versions. So, Cilium may want to install v1.1.0, but if you install Envoy Gateway, it may want to install v1.0.0.

Because CRDs can only have one version, if both implementations had controllers install _their_ version, you would either end up with inconsistent behavior (if they run at startup of the controller, with the active version depending on which implementation's controller has restarted more recently), or flapping CRD versions (if they both actively reconcile the version, and put their version back when the CRD changes).

There's really no great solution for this problem at the moment, which stems from the fact that you can only have one version of a CRD installed in the cluster. We've talked about a number of options upstream in Gateway API, but haven't been able to find anything that works for everyone yet.

That's why, for now, Cilium has the requirement that the CRDs are "manually" installed - which really just means that the CRDs need to be installed before Cilium is.

Sorry I can't give you better news - if it was as simple as just having the Cilium operator apply the manifests, I'd happily do that.

**Comment by hellt** [comment]
Why would then network SIG put this option on the first place? https://gateway-api.sigs.k8s.io/guides/#installing-a-gateway-controller

**Comment by balous** [comment]
@youngnick, I understand this, as I wrote, I don't have problem with installing CRDs separately. My problem is the autodetection inside Cililum chart which leads to uncertain results. I'd prefer Cilium installation to fail in case GW API CRDs are not installed (the same way it fails when Prometheus CRDs are not installed) instead of skipping the GatewayClass.

**Comment by youngnick** [comment]
Okay, that seems like a reasonable ask - I agree that having the helm chart fail if Gateway API is enabled and GatewayClass is not present probably makes more sense. It is a breaking change though, so we will need to be a little careful about it.

**Comment by youngnick** [comment]
@hellt Note the language there - _some_ implementations _may_ install automatically - that just means that they are making the call that they won't be affected too much by any of the issues I mentioned.

**Comment by balous** [comment]
> Okay, that seems like a reasonable ask - I agree that having the helm chart fail if Gateway API is enabled and GatewayClass is not present probably makes more sense. It is a breaking change though, so we will need to be a little careful about it.

I could create a PR adding a new option for this - `gatewayAPI.gwClass.create: <true|false|auto>` where `auto` is the current behavior. Seams reasonable?

**Comment by youngnick** [comment]
Yes, that seems very reasonable, thanks!

**Comment by ferhatguneri** [comment]
Hi @balous  It seems this auto option is not working properly. We do install GatewayAPI CRDs after cilium installation but still gatewayclass status is unknown and we need to restart cilium operator. 
For example in RKE2 case it handles the cilium installation. After cluster gets created then we have option to create Gateway API CRDs. But cilium operator does not detect it without restart.

**Comment by balous** [comment]
> Hi [@balous](https://github.com/balous) It seems this auto option is not working properly. We do install GatewayAPI CRDs after cilium installation but still gatewayclass status is unknown and we need to restart cilium operator. For example in RKE2 case it handles the cilium installation. After cluster gets created then we have option to create Gateway API CRDs. But cilium operator does not detect it without restart.

I am not sure if I understand that correctly - you are asking for `auto` option which makes the chart to decide whether to install `GatewayClass` or not, this decision is based on presence of CRDs in the cluster. So, in `auto` case, if you install CRDs after Cilium installation, `GatewayClass` creation should be skipped (it would fail otherwise). So do you really use `gatewayAPI.gwClass.create: auto` in you setup? What creates the `GatewayClass` if it is not created by the chart?

**Comment by ferhatguneri** [comment]
I somehow inject gateway class CRD into RKE2 and after cluster creation I can see gateway class is created by cilium but state is unknown. Because cilium is waiting for other gw api crds to be installed. So Injecting all the gateway api CRDs into RKE2 cluster definition is going to create thousands of lines of code for the cluster which is not really good idea. So Do you think cilium will not take care of this part? I mean If all the gateway API CRDs are created after cilium installation cilium operator cannot do anything about it?
and yes I tried both auto and true options. Result is same.

Here is the sequence of what I'm doing:
Create Cluster
Create GatewayClass CRD
Install Cilium
Create rest of GarewayAPI CRDs

`time=2024-11-06T08:02:36Z level=info msg=Invoked duration=30.015930993s function="gateway-api.initGatewayAPIController (pkg/gateway-api/cell.go:106)"
time="2024-11-06T08:02:36Z" level=error msg="Required GatewayAPI resources are not found, please refer to docs for installation instructions" error="Get \"https://198.18.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/gatewayclasses.gateway.networking.k8s.io\": dial tcp 198.18.0.1:443: i/o timeout\ncustomresourcedefinitions.apiextensions.k8s.io \"gateways.gateway.networking.k8s.io\" not found\ncustomresourcedefinitions.apiextensions.k8s.io \"httproutes.gateway.networking.k8s.io\" not found\ncustomresourcedefinitions.apiextensions.k8s.io \"grpcroutes.gateway.networking.k8s.io\" not found\ncustomresourcedefinitions.apiextensions.k8s.io \"referencegrants.gateway.networking.k8s.io\" not found\ncustomresourcedefinitions.apiextensions.k8s.io \"tlsroutes.gateway.networking.k8s.io\" not found" subsys=gateway-api`

**Comment by balous** [comment]
Honestly, when I was making the fix I was wondering why the `GatewayClass` is created by the chart and not by the operator (which seems more logical to me). Anyway, you question should be answered by regular Cilium maintainers, not me, I am just a contributor.

**Comment by cloudcafetech** [comment]
@ferhatguneri 

Are you able to fix ? I am facing same issue **gatewayclass Unknown"

```
k get crds | grep gateway
gatewayclasses.gateway.networking.k8s.io                 2025-05-04T13:52:00Z
gateways.gateway.networking.k8s.io                       2025-05-04T13:52:01Z
grpcroutes.gateway.networking.k8s.io                     2025-05-04T13:52:02Z
httproutes.gateway.networking.k8s.io                     2025-05-04T13:52:01Z
referencegrants.gateway.networking.k8s.io                2025-05-04T13:52:02Z
tlsroutes.gateway.networking.k8s.io                      2025-05-04T13:52:03Z

k get gatewayclasses.gateway.networking.k8s.io
NAME     CONTROLLER                     ACCEPTED   AGE
cilium   io.cilium/gateway-controller   Unknown    11m

```

Same RKE2, post cluste rsetup added gateway CRDs and my helm as  follows for gateway.

```
    gatewayAPI:
      enabled: true
      gatewayClass:
       create: auto
      hostNetwork:
        enabled: true
```

- POD status

```
kube-system   cilium-operator-7b568f985d-zh2vp                        1/1     Running     0             18m
kube-system   cilium-tn5wj                                            1/1     Running     0             18m
kube-system   cloud-controller-manager-ubuntu2004                     1/1     Running     0             18m
kube-system   etcd-ubuntu2004                                         1/1     Running     0             18m
kube-system   helm-install-rke2-cilium-n748r                          0/1     Completed   0             19m
kube-system   helm-install-rke2-coredns-2rlpf                         0/1     Completed   0             19m
kube-system   helm-install-rke2-metrics-server-l2b2k                  0/1     Completed   0             19m
kube-system   helm-install-rke2-multus-hhz82                          0/1     Completed   0             19m
kube-system   helm-install-rke2-runtimeclasses-hnpqq                  0/1     Completed   0             19m
kube-system   hubble-relay-67d5d77ccb-qskdc                           1/1     Running     0             18m
kube-system   hubble-ui-649ccfdf89-m5xzf                              2/2     Running     0             18m
kube-system   kube-apiserver-ubuntu2004                               1/1     Running     0             18m
kube-system   kube-controller-manager-ubuntu2004                      1/1     Running     0             18m
kube-system   kube-scheduler-ubuntu2004                               1/1     Running     0             18m
kube-system   rke2-coredns-rke2-coredns-86f64967bd-n9jhk              1/1     Running     0             18m
kube-system   rke2-coredns-rke2-coredns-autoscaler-5b89b754bd-s9tz9   1/1     Running     0             18m
kube-system   rke2-metrics-server-58ff89f9c7-2sqzj                    1/1     Running     0             15m
kube-system   rke2-multus-hc9ml                                       1/1     Running     4 (16m ago)   18m
kube-system   rke2-multus-rke2-whereabouts-sthln                      1/1     Running     0             18m
```

By the way. is there any POD for controller?

**Comment by JoWe112** [comment]
@cloudcafetech 
Restart the cilium-operator and it will change from Unknown to True

```
NAME     CONTROLLER                     ACCEPTED   AGE
cilium   io.cilium/gateway-controller   True       3m46s
```

**Comment by cloudcafetech** [comment]
@JoWe112 Thanks for reply.

Able to get after restart but now Gateway object is **Unknown** & description saying **waiting for controller**

```
k get gateway,svc -n kube-system
NAME                                               CLASS    ADDRESS   PROGRAMMED   AGE
gateway.gateway.networking.k8s.io/hubble-gateway   cilium             Unknown      10m

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
service/hubble-metrics              ClusterIP   None             <none>        9965/TCP        37m
service/hubble-peer                 ClusterIP   10.110.229.16    <none>        443/TCP         37m
service/hubble-relay                ClusterIP   10.109.117.188   <none>        80/TCP          37m
service/hubble-relay-metrics        ClusterIP   None             <none>        9966/TCP        37m
service/hubble-ui                   ClusterIP   10.103.102.153   <none>        80/TCP          37m
service/rke2-coredns-rke2-coredns   ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP   37m
service/rke2-metrics-server         ClusterIP   10.96.21.134     <none>        443/TCP         34m

k  describe gateway hubble-gateway -n kube-system
Name:         hubble-gateway
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2025-05-05T02:10:52Z
  Generation:          1
  Resource Version:    6777
  UID:                 775150a5-7302-4fc5-b837-cf44c2891668
Spec:
  Gateway Class Name:  cilium
  Listeners:
    Allowed Routes:
      Namespaces:
        From:  All
    Hostname:  *.192.168.0.38.nip.io
    Name:      http
    Port:      80
    Protocol:  HTTP
Status:
  Conditions:
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Accepted
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Programmed
Events:    
```

- GW

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hubble-gateway
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: "*.192.168.0.38.nip.io"
    allowedRoutes:
      namespaces:
        from: "All"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui-route
  namespace: kube-system
spec:
  parentRefs:
  - name: hubble-gateway
    namespace: kube-system
  hostnames:
  - hubble-ui.192.168.0.38.nip.io
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: "" # Empty string for Core Kubernetes
      kind: Service
      name: hubble-ui # Name of the Hubble UI service
      port: 80
      namespace: kube-system
```

- Install GatewayAPI

```
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml

cat << EOF > cilium-gateway-class.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
EOF

kubectl create -f cilium-gateway-class.yaml
```



- POD 

```
k get po -n kube-system

NAME                                                    READY   STATUS      RESTARTS      AGE
cilium-9hkg4                                            1/1     Running     0             16m
cilium-operator-9c5df7b79-42jhg                         1/1     Running     0             3m
cloud-controller-manager-ubuntu2004                     1/1     Running     0             33m
etcd-ubuntu2004                                         1/1     Running     0             34m
helm-install-rke2-cilium-f86rm                          0/1     Completed   0             34m
helm-install-rke2-coredns-zvpwn                         0/1     Completed   0             34m
helm-install-rke2-metrics-server-k4h8w                  0/1     Completed   0             34m
helm-install-rke2-multus-5m97v                          0/1     Completed   0             34m
helm-install-rke2-runtimeclasses-w78r7                  0/1     Completed   0             34m
hubble-relay-67d5d77ccb-9gmf6                           1/1     Running     0             33m
hubble-ui-649ccfdf89-rtg4n                              2/2     Running     0             33m
kube-apiserver-ubuntu2004                               1/1     Running     0             33m
kube-controller-manager-ubuntu2004                      1/1     Running     0             33m
kube-scheduler-ubuntu2004                               1/1     Running     0             33m
rke2-coredns-rke2-coredns-86f64967bd-ln6pf              1/1     Running     0             33m
rke2-coredns-rke2-coredns-autoscaler-5b89b754bd-mmcwg   1/1     Running     0             33m
rke2-metrics-server-58ff89f9c7-rbpd7                    1/1     Running     0             31m
rke2-multus-hrrft                                       1/1     Running     4 (32m ago)   33m
rke2-multus-rke2-whereabouts-j9n5l                      1/1     Running     0             33m

root@ubuntu2004:~# kubectl get gatewayclasses
NAME     CONTROLLER                     ACCEPTED   AGE
cilium   io.cilium/gateway-controller   True       27m

root@ubuntu2004:~# cilium config view | grep -w "enable-gateway-api"
enable-gateway-api                                true
enable-gateway-api-alpn                           false
enable-gateway-api-app-protocol                   false
enable-gateway-api-proxy-protocol                 false
enable-gateway-api-secrets-sync                   true

root@ubuntu2004:~# cilium config view | grep "gateway-api-hostnetwork-enabled"
gateway-api-hostnetwork-enabled                   true

root@ubuntu2004:~# cilium config view | grep "enable-l7-proxy"
enable-l7-proxy                                   true
```

**Comment by cloudcafetech** [comment]
After installing experimental CRDs https://github.com/cilium/cilium/issues/38420 I am able fix the Unknow state but **NOT assign any IP in gateway.**

```
kubectl get gateway -A
NAMESPACE     NAME             CLASS    ADDRESS   PROGRAMMED   AGE
default       test-gateway     cilium             True         4m21s
kube-system   gateway1         cilium             True         32m
kube-system   hubble-gateway   cilium             True         65m
```
