### ISSUE TITLE
Simulate world in Ginkgo CI

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3325]
I'd like to easily invoke some commands to test policy with `reserved:world` within the runtime tests. Examples are l4 policies ingress from world or egress to world.

Please comment if anything at all exists here or if you're working on this.

**Comment by ianvernon** [comment]
@joestringer we do have tests which test egress to world at L3-only, but nothing with ingress or L4.

**Comment by eloycoto** [comment]
Fixed here: 
https://github.com/cilium/cilium/commit/93aae686da740d98422e8f4c880bdc8b2c4897aa
