### ISSUE TITLE
Cilium pods fail on worker nodes RKE2 after enabling host firewall

### ISSUE THREAD

**Issue by bashilias** [cilium/cilium#33277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have RKE2-cilium deployed in a RKE2 downstream cluster. But the moment I enable host firewalling the worker nodes will be unavailable. 

It happens after appling the helmchart config and redeploying the operator and cilium daemonset.

`apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
      ipv4:
        enabled: true
      ipv6:
        enabled: false
      kubeProxyReplacement: "strict"
      k8sServiceHost: 127.0.0.1
      k8sServicePort: 6443
      hostFirewall:
        enabled: true`
        
The moment I set hostFirewall to false, the cilium daemonset and cilium-operator deployment run fine. 
It seems like that it cannot connect to the api server: 

` Last state: Terminated with 1: Error (Running time=&quot;2024-06-20T12:42:57Z&quot; level=info msg=Invoked duration=&quot;577.548µs&quot; function=&quot;github.com/cilium/cilium/cilium-dbg/cmd.glob..func39 (cmd/build-config.go:32)&quot; subsys=hive time=&quot;2024-06-20T12:42:57Z&quot; level=info msg=Starting subsys=hive time=&quot;2024-06-20T12:42:57Z&quot; level=info msg=&quot;Establishing connection to apiserver&quot; host=&quot;https://127.0.0.1:6443&quot; subsys=k8s-client time=&quot;2024-06-20T12:43:12Z&quot; level=info msg=&quot;Establishing connection to apiserver&quot; host=&quot;https://127.0.0.1:6443&quot; subsys=k8s-client time=&quot;2024-06-20T12:43:27Z&quot; level=info msg=&quot;Establishing connection to apiserver&quot; host=&quot;https://127.0.0.1:6443&quot; subsys=k8s-client time=&quot;2024-06-20T12:43:42Z&quot; level=info msg=&quot;Establishing connection to apiserver&quot; host=&quot;https://127.0.0.1:6443&quot; subsys=k8s-client time=&quot;2024-06-20T12:43:57Z&quot; level=info msg=&quot;Establishing connection to apiserver&quot; host=&quot;https://127.0.0.1:6443&quot; subsys=k8s-client time=&quot;2024-06-20T12:44:07Z&quot; level=error msg=&quot;Unable to contact k8s api-server&quot; error=&quot;Get \&quot;https://127.0.0.1:6443/api/v1/namespaces/kube-system\&quot;: net/http: TLS handshake timeout&quot; ipAddr=&quot;https://127.0.0.1:6443&quot; subsys=k8s-client time=&quot;2024-06-20T12:44:07Z&quot; level=error msg=&quot;Start hook failed&quot; error=&quot;Get \&quot;https://127.0.0.1:6443/api/v1/namespaces/kube-system\&quot;: net/http: TLS handshake timeout&quot; function=&quot;client.(*compositeClientset).onStart&quot; subsys=hive time=&quot;2024-06-20T12:44:07Z&quot; level=info msg=Stopping subsys=hive Error: Build config failed: failed to start: Get &quot;https://127.0.0.1:6443/api/v1/namespaces/kube-system&quot;: net/http: TLS ), started: Thu, Jun 20 2024 2:42:57 pm, finished: Thu, Jun 20 2024 2:44:07 pm `

I also tried the address of the upstream cluster: rancher.domain.com

Does anyone has experience setting up Cilium for host firewalling on RKE2? Tips are welcome!

### Cilium Version

v1.15.4

### Kernel Version

5.14.21-150500.55.62-default

### Kubernetes Version

Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9+rke2r1

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
Hi, could you please format your error message correctly using a multiline code block? It contains a bunch of `\&quot;` that makes it really hard to read. Thank you.
