### ISSUE TITLE
Cilium Pods crashing on Kubernetes Workers

### ISSUE THREAD

**Issue by VishnuParthasarathy** [cilium/cilium#33274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have a K8s cluster deployed on a bunch of BareMetal's deployed using kubespray. When we tried to scale the cluster with two additional workers, the Clilium Pods are not coming up. 

Did the below so far:
1. Restarted Kubelet on the workers
2. Deleted the Cilium Pods on the specific workers
3. Checked the following Dir's for Permissions, ownership etc
    - /etc/cilium/
    - /etc/cni/
    - /var/lib/cni/
4. Re-imaged the Hosts and again scaled.
Nothing seems to fix the issue.

The below is the error I am getting:
Warning  Unhealthy  81s (x3 over 101s)  kubelet            Startup probe failed: Get "http://127.0.0.1:9879/healthz": dial tcp 127.0.0.1:9879: connect: connection refused 
Warning  BackOff    78s (x4 over 95s)   kubelet            Back-off restarting failed container cilium-agent in pod cilium-7t47c_kube-system(xxxxx)

cilium-agent level=warning msg="No valid cgroup base path found: socket load-balancing tracing with Hubble will not work.See the kubeproxy-free guide for more details." subsys=cgroup-manager
cilium-agent level=fatal msg="Unable to initialize service maps" error="Unable to create map /sys/fs/bpf/tc/globals/cilium_lb4_reverse_sk: cannot allocate memory" subsys=daemon

### Cilium Version

cilium:v1.13.0

### Kernel Version

4.18.0-513.24.1.el8_9.x86_64

### Kubernetes Version

v1.27.5

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VishnuParthasarathy** [comment]
I too thought of the same, but these hosts have 1TB of memory (MemTotal: 1055937224 kB).
free -m
                 total        used        free            shared  buff/cache   available
Mem:        1031188   6135     1010756           6       14296        1020007
Swap:             0           0           0

w.r.t Memory requests & Limit, I see the same config across other Cilium pods on other nodes...

Working Node:
name: cilium-agent
resources:
      limits:
        cpu: 500m
        memory: 500M
      requests:
        cpu: 100m
        memory: 64M

Non-Working Node:
name: cilium-agent
resources:
      limits:
        cpu: 500m
        memory: 500M
      requests:
        cpu: 100m
        memory: 64M

**Comment by VishnuParthasarathy** [comment]
https://github.com/cilium/cilium/issues/23436 also looks like the same. 
I tried to reimage the node and scale the cluster, but still the same error.

Normal   Created    29m (x3 over 30m)      kubelet  Created container cilium-agent                                            │
│   Normal   Started    29m (x3 over 30m)      kubelet  Started container cilium-agent                                            │
│   Warning  Unhealthy  29m (x4 over 30m)      kubelet  Startup probe failed: Get "http://127.0.0.1:9879/healthz": dial tcp 127.0 │
│ .0.1:9879: connect: connection refused                                                                                          │
│   Warning  BackOff    4m56s (x132 over 29m)  kubelet  Back-off restarting failed container cilium-agent in pod cilium-58k25_kub │e-system(4af21328-f69d-4af8-b1dd-30b97d8c8f78)

level=info msg="Inheriting MTU from external network interface" device=nm_bond ipAddr=172.30.124.90 mtu=1500 subsys=mtu
level=warning msg="No valid cgroup base path found: socket load-balancing tracing with Hubble will not work.See the kubeproxy-free guide for more details." subsys=cgroup-manager
level=info msg="Envoy: Starting xDS gRPC server listening on /var/run/cilium/xds.sock" subsys=envoy-manager
level=fatal msg="Unable to initialize service maps" error="Unable to create map /sys/fs/bpf/tc/globals/cilium_lb4_reverse_sk: cannot allocate memory" subsys=daemon

**Comment by VishnuParthasarathy** [comment]
On the latest kernel as well.
uname -r
4.18.0-553.8.1.el8_10.x86_64

Unfortuantely, I will not be able to upgrade the cilium version since have issues with just 2 nodes, rest of the 30+ nodes are working as expected

**Comment by mhkarimi1383** [comment]
@VishnuParthasarathy 
For me fixed by making request and limit 10x more
