### ISSUE TITLE
Refactor subprocess supervisors into one place

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#3328]
cilium-agent spawns a number of subprocesses:
1- monitor (https://github.com/cilium/cilium/blob/master/monitor/launch/launcher.go#L75)
2- health (https://github.com/cilium/cilium/blob/master/cilium-health/launch/launcher.go#L46)
3- envoy (https://github.com/cilium/cilium/blob/master/pkg/envoy/envoy.go#L127)

(1 & 2 use https://sourcegraph.com/github.com/cilium/cilium@6b37ad65e156c0b88f1f35e677a3d3fa8dc5795d/-/blob/pkg/launcher/launcher.go#L39)

Each currently has it's own supervisor code to restart it or report on it. They each do some of:
- start a subprocess
- restart it if it exits
- shut down the child on agent exit
- pre/post spawn cleanup 
- wire up child stdout/stderr

It would be good to have a single way to spawn child processes with a more structured set of callbacks for each lifecycle step. Further in the future we will also need to support running these processes as separate non-child processes (for example, as another container, pod or systemd unit).
Some features would be:
1- us a single package to manage such processes (pkg/launcher is a start, perhaps)
2- clear configuration on what to do with stdin, stdout and stderr for the child
3- hooks for lifecycle steps: pre-spawn, post-spawn, pre-shutdown, post-shutdown, post-unexpected-exit (or whatever makes sense)
4- consistent status checking: isRunning, getStdOut etc. (or what make sense)
5- support different ways to run this code. This is the least clear aspect of this since some lifecycle events will not correlate and stdout/in/err may not be accessible manageable directly. The goal is not to make the same interface but to present something usable.
6- It might be worthwhile to use the controller package directly, or mimic the reporting mechanisms it has to export that to cilium status. This data is already present there, however, in ways specific to each subsystem (envoy, monitor, health).

I'm not sure if it's a good idea to try and build a real supervisor but I don't see how to avoid that in the short term since the current implementations do exactly that. Once they are all behind one interface it might be easier to reuse and existing package to do this (or use that package directly and avoid building our own).

**Comment by joestringer** [comment]
Note there's two for the health - one that runs as though it's an endpoint (via `bpf/spawn_netns.sh`), and the other that is launched directly, using `pkg/launcher` as you mentioned.

**Comment by raybejjani** [comment]
Oh, good point. I keep forgetting about that one. Does the spawn_netns.sh do anything special? I imagine it execs the shell script and then adds the endpoint to the agent. This would fit into the lifecycle stuff I listed above without too much weirdness, right?

**Comment by joestringer** [comment]
It basically just runs a network namespace and runs `cilium-health` inside the namespace, and sets up the addresses/routes for connectivity. It currently handles restarting the daemon if it fails / exits. The endpoint creation for this namespace is done from the daemon, it doesn't configure itself through the API (because we want to associate reserved labels that users can't manipulate).
