### ISSUE TITLE
Cilium agent is unable to update CiliumNode resource at startup

### ISSUE THREAD

**Issue by centromere** [cilium/cilium#33293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Cilium agent exits soon after being started (logs below). I located the relevant function [here](https://github.com/cilium/cilium/blob/3fc57b38abe6179ac4c8fc21dd515c038ab45226/pkg/nodediscovery/nodediscovery.go#L258). Is it possible that the loop is retrying too quickly?

If I modify the `cilium-config` ConfigMap and set `auto-create-cilium-node-resource: false`, it starts up just fine.

### Cilium Version

```
cilium-cli: v0.16.10 compiled with go1.22.4 on darwin/arm64
cilium image (default): v1.15.5
cilium image (stable): v1.15.6
cilium image (running): 1.15.5
```

### Kernel Version

```
Linux master-1 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.31.0-alpha.1.43+6ac60160c5729a
Kustomize Version: v5.4.2
Server Version: v1.30.1
```

### Relevant log output

```shell
time="2024-06-20T20:00:25Z" level=info msg="Creating or updating CiliumNode resource" node=master-1 subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
time="2024-06-20T20:00:25Z" level=fatal msg="Could not create or update CiliumNode resource, despite 10 retries" subsys=nodediscovery
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Thank you for opening a GH issue. You need to set `auto-create-cilium-node-resource: true` or have a component that creates the Cilium Node resource on behalf of Cilium, otherwise Cilium won't be able to start as you have seen.

**Comment by centromere** [comment]
Hi @aanm. When that value is `true`, Cilium will (intermittently) not start. That is why I've filed a bug report. I _want_ it to be `true`, but I have to set it to `false` to work around the issue. As you can see from the logs I've submitted, when the value is `true`, Cilium will try to update the Node resource, but it cannot:

```
time="2024-06-20T20:00:25Z" level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"master-1\": the object has been modified; please apply your changes to the latest version and try again" subsys=nodediscovery
```

I suspect that there exists a race condition, and there is not enough delay between retries. Notice how all retries happen within the same second.

**Comment by centromere** [comment]
1. Set up an HA Kubernetes cluster
2. Install Cilium and set `auto-create-cilium-node-resource: true`
3. Delete the Cilium CSI Pod from one of the master Nodes
4. Observe that, upon re-creation, the Pod fails to start

Because this problem is a race condition, I would be shocked if you were able to repeatedly reproduce it given the instructions above.

**Comment by aanm** [comment]
@centromere can you also share the sysdump?

**Comment by centromere** [comment]
I cannot share a sysdump without a NDA.

**Comment by aanm** [comment]
Unfortunately we can't get to the root of the issue without the sysdump as it would help us to understand the cluster where Cilium is deployed.

**Comment by lrouquette** [comment]
I'm facing the same issue, though with 1.14.11+. In most cases, it happens with #29795, making agent startup excruciating slow with serious ramifications like cluster scaling etc...

**Comment by centromere** [comment]
@lrouquette During a recent upgrade from 1.15.5 to 1.15.8 on a 48 node cluster, multiple masters and multiple workers were affected by this problem. The only recourse I had was to define this `CiliumNodeConfig`:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  name: disable-auto-create-cilium-node-resource
  namespace: kube-system
spec:
  defaults:
    auto-create-cilium-node-resource: "false"
  nodeSelector:
    matchLabels:
      disable-auto-create-cilium-node-resource: "true"
```

Then I had to label the affected nodes, delete the cilium pod, wait for the new one to come online, remove the label, and fix the health IP addresses of the `CiliumNode`.

However, the upgrade to 1.15.8 was merely transitory, as my ultimate goal was to get to 1.16.1. During the 1.16.1 upgrade, I did not experience the issue at all. However, given that it's a race condition, it's possible that the underlying issue was not fixed and I am just getting lucky. Are you able to reproduce the issue with 1.16.1?

**Comment by lrouquette** [comment]
@centromere - in most cases, the agent does start successfully after the retry, so no manual intervention is necessary. I have not tested with 1.16 (a long way out for me).

**Comment by centromere** [comment]
In my case, on some nodes the container only restarted once, but in other cases it looped indefinitely.

**Comment by lrouquette** [comment]
Yikes; yeah, I have not experienced the infinite restart loop so far...

**Comment by centromere** [comment]
Thank you!

**Comment by harsimran-pabla** [comment]
Hi @centromere Did you had a chance to test with this change? Is it resolving your issue?
