### ISSUE TITLE
Cilium external workloads

### ISSUE THREAD

**Issue by cccsss01** [cilium/cilium#33294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

run the ./install-external-workload.sh and it just continually cycles *waiting for cilium daemon to come up"

Additionally looking at the install script, it doesn't populate the correct clusterip and node port.  

CLUSTER_ADDR=${2:-<ip:port>}

In testing it is grabbing the wrong ip address of the port exposed, looks to be grabbing the control node that is not exposing that port, as the clustermesh api server is exposed on a different ip w/ the worker node.

### Cilium Version

1.15.6

### Kernel Version

5.14.0-284.30.1.el9_2.x86_64

### Kubernetes Version

1.26.15

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cccsss01** [comment]
I have manually tried chaning the cluster_ADDR as well, but get the same problem.

**Comment by cccsss01** [comment]
Seems to be occurring with Load balancer as well.

**Comment by ti-mo** [comment]
It seems like `install-external-workload.sh` is in the cilium-cli repo? Please create an issue over there with more detailed information to trace/reproduce your steps. I can't figure out what you're trying to do.

Thank you. Closing this for now.
