### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb2524d]

### ISSUE THREAD

**Issue by huangchengwu** [cilium/cilium#33340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!

### Cilium Version

1.13.3

### Kernel Version

Linux Hy-1 5.15.0-79-generic #86~20.04.2-Ubuntu SMP Mon Jul 17 23:27:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.27.3

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb2524d]

goroutine 1972 [running]:
github.com/vishvananda/netlink.parseActions({0xc0062fa000, 0x4, 0x2?})
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:981 +0x50d
github.com/vishvananda/netlink.(*Flower).decode(0xc001387680, {0xc0062f2488, 0x15, 0x411e7b?})
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:223 +0x1cb
github.com/vishvananda/netlink.parseFlowerData(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:1119
github.com/vishvananda/netlink.(*Handle).FilterList(0x690a3b0, {0x446c3b8, 0xc003fafc80}, 0xfffffff2)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:512 +0x854
github.com/vishvananda/netlink.FilterList({0x446c3b8, 0xc003fafc80}, 0xfffffff2)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:423 +0xfd
github.com/cilium/cilium/pkg/datapath/loader.removeObsoleteNetdevPrograms({0xc001c78f00, 0x4, 0x3e0a025?})
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:275 +0x427
github.com/cilium/cilium/pkg/datapath/loader.(*loader).reloadHostDatapath(0xc00100a360, {0x44c34b0, 0xc004ad03c0}, 0xc004481950, {0xc001c78f00, 0x4, 0x4})
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:429 +0x12b3
github.com/cilium/cilium/pkg/datapath/loader.(*loader).reloadDatapath(0xc00100a360, {0x44c34b0, 0xc004ad03c0}, 0xc004481950)
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:472 +0xec5
github.com/cilium/cilium/pkg/datapath/loader.(*loader).ReloadDatapath(0xc00100a360, {0x448f298, 0xc004c82540}, {0x44c34b0, 0xc004ad03c0}, 0xc004cbe230)
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:595 +0x207
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).realizeBPFState(0xc001bce408, 0xc004cbe008)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:664 +0x3b8
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc001bce408, 0xc004cbe008)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:586 +0x49f
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc001bce408, 0xc004cbe008)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:458 +0x9bd
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc001b82280, 0xc002968cc0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:57 +0x1df
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:244 +0x133
sync.(*Once).doSlow(0xc0014299e0?, 0x0?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0xc0020f2d80?)
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:232 +0x3c
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run in goroutine 1
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this report @huangchengwu, if you could provide a sysdump from a cluster that's had this occur as well, that would really help with investigation when someone can look. https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection explains how to do this.

**Comment by youngnick** [comment]
Additionally, Cilium 1.13 is also reasonably old at this point. Can you replicate this on a newer version (ideally with 1.15 or one of the 1.16 prereleases?)

**Comment by borkmann** [comment]
> github.com/vishvananda/netlink.parseActions({0xc0062fa000, 0x4, 0x2?})
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:981 +0x50d
github.com/vishvananda/netlink.(*Flower).decode(0xc001387680, {0xc0062f2488, 0x15, 0x411e7b?})
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:223 +0x1cb
github.com/vishvananda/netlink.parseFlowerData(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:1119

This looks like a bug in github.com/vishvananda/netlink library when parsing tc filters and in this particular case tc flower. I see you posted the issue there already, thanks!

xref: https://github.com/vishvananda/netlink/issues/987

**Comment by youngnick** [comment]
Given that this is a bug in a Cilium dependency, in an old version, I'll close this issue. @huangchengwu, please comment here if there's anything else you need to know.

**Comment by cardoe** [comment]
So it looks like Cillium 1.16.4 pulled a new enough version of the netlink library to have the fix in it. Versions prior to that suffer from the crash.

**Comment by cardoe** [comment]
Specific changes:
https://github.com/cilium/cilium/blob/f221719170636b0e0da2c7b8227c18967a1201c8/go.mod#L96
vs
https://github.com/cilium/cilium/blob/0380724290f01576aa053c2c2ad35532063c695e/go.mod#L97
