### ISSUE TITLE
Run `gofmt` as a non-requirement to merge PRs

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#3336]
Using `gofmt` in CI is not recommended as it can change on every go version.

Suggestion is to create a new "PR check" that runs `go fmt` but doesn't stop the tests coverage. The PR author can later re-format the code if not compliant with the recommended development version.

**Comment by ianvernon** [comment]
Sorry about closing and reopening the issue, fat finger moment :)

**Comment by ianvernon** [comment]
By 'PR Check' do you mean something similar to Hound?

**Comment by aanm** [comment]
@ianvernon correct

**Comment by ianvernon** [comment]
What about if we do the following:

`test-me-please` triggers two separate jobs, one of which runs `gofmt`, and the other which runs the tests in the VMs. We can make the compilation of Cilium no longer contingent upon `gofmt` being ran by providing a flag to the `Makefile` which disables it (i.e., it is enabled by default). Then, we can mark this second job as 'required' for something to be merged. Does this meet your expectations?

**Comment by tgraf** [comment]
Solved via local run of go fmt
