### ISSUE TITLE
Operational metrics

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3338]
- [x] Endpoint regenerations
- [x] Current policy revision
- [x] Number of endpoints
  - [x] With ingress policy enforcement
  - [x] With egress policy enforcement
- [x] Number of policies
   - [x] Number of policy import failures
   - [x] Number of policy *not* enforced
- [x] Number of services
- [x] Expose cluster health
  - [ ] latency / connectivity (@mrostecki)

**Comment by eloycoto** [comment]
@tgraf I'll close this issue, the only issue is the latency/connectivity that it's already in #5382.
