### ISSUE TITLE
bpf: kernel freeze with nfs client in xs_tcp_setup_socket

### ISSUE THREAD

**Issue by usiegl00** [cilium/cilium#33395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is a critical issue causing a kernel busy loop triggered by the interaction between Cilium and Longhorn when an share-manager pod is disrupted. This loop is caused by -EPERM errors returned by bpf_sock.c, which are currently handled by default as retry cases in the kernel's xs_tcp_setup_socket function. This issue leads to syslog flooding, degrading system performance, and causes nodes to freeze up and become unresponsive.

The main bug lies in the error codes returned by the kernel_connect function when hooked by bpf_sock.c. The current implementation returns -EPERM, -ENXIO, and -ENOMEM which xs_tcp_setup_socket is not ready to handle. Among the functions in the kernel sunrpc xprtsock.c, only xs_udp_send_request is ready to handle -EPERM and none are ready to handle the other two. xs_tcp_setup_socket handles the most amount of error codes at 11, with xs_udp_send_request coming in second at 7, however kernel_connect has more than 20 different return error codes.

@dylandreimerink and I propose that we update bpf_sock.c to fix this issue by returning error codes that xs_tcp_setup_socket has existing handlers for, thus preventing the kernel from entering an infinite retry loop. I think we should replace -EPERM with -ENETUNREACH, -ENXIO with -ENETDOWN, and -ENOMEM with -ENOBUFS. These replacements do not preserve the intended code meanings, but they do have handlers in xs_tcp_setup_socket that prevent the default retry.

I would like to open this discussion to gather feedback and, if there are no significant objections, move forward with a pull request to implement this change. This fix is crucial as it impacts all users integrating Cilium with Longhorn, including my own production cluster, and a resolution would significantly improve stability and reliability.

Thank you for considering this issue. I look forward to collaborating on a viable solution.

### Cilium Version

1.14+ with kube-proxy-replacement

### Kernel Version

v5.5+

### Kubernetes Version

1.28+

### Relevant log output

```shell
xs_tcp_setup_socket: connect returned unhandled error -1
xs_tcp_setup_socket: connect returned unhandled error -1
...
xs_tcp_setup_socket: connect returned unhandled error -1
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
Related upstream discussion: https://lore.kernel.org/bpf/20240420104801.94701-1-usiegl00@gmail.com/

EPERM is however a documented error code: https://man7.org/linux/man-pages/man2/connect.2.html

> thus preventing the kernel from entering an infinite retry loop

I still think this is a bug in xs_tcp_setup_socket and should be fixed there, let me comment in the thread. If a better error code in bpf_sock helps it might be worth doing as well.

**Comment by borkmann** [comment]
I think remap would be better fit, pushed here with an explanation: https://lore.kernel.org/bpf/72b5939b13efd4fde6e9c0f9fb00edd314f4bcce.1719392816.git.daniel@iogearbox.net/

**Comment by bitfactory-sem-denbroeder** [comment]
Hi, is there any timeline for this issue? we're experiencing the same problem on our (dev) cluster. Running longhorn and cilium

**Comment by borkmann** [comment]
Once this gets merged into net tree, and shipped to Linus within a ~week, then stable team will pick this up. I don't have experience with Longhorn, but I'd assume once its in stable tree then they can cherry pick to their downstream kernel.

**Comment by mrclrchtr** [comment]
I also had the same problem today with Talos, Longhorn and Cilium.

**Comment by borkmann** [comment]
Patch got merged here: https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=626dfed5fa3bfb41e0dffd796032b555b69f9cde

And is being shipped to Linus today, then stable will pick it some time after automatically.
