### ISSUE TITLE
Add an e2e test for node-local DNS with LRP

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#33415]
The test will - 

- Deploy node-local dns setup using [documentation](https://docs.cilium.io/en/stable/network/kubernetes/local-redirect-policy/#node-local-dns-cache).
- Add connectivity tests to validate DNS requests are resolved by node-local DNS cache pods.
- Add connectivity tests with a FQDN policy to validate DNS requests are resolved by node-local DNS cache pods..  

cilium-cli PR is merged - https://github.com/cilium/cilium-cli/pull/2669.

**Comment by borkmann** [comment]
Also, the https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/ still says "beta", I believe we moved to stable now.

One more in the context of this is to add test and documentation coverage for:
```
 bpf-lb-sock: "true"
 enable-local-redirect-policy: "true"
 kube-proxy-replacement: "false"
```

**Comment by ysksuzuki** [comment]
> Also, the https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/ still says "beta", I believe we moved to stable now.

I've sent a PR to remove the beta from the LRP doc. https://github.com/cilium/cilium/pull/33498

**Comment by ysksuzuki** [comment]
I've added the e2e test for node-local DNS with LRP
https://github.com/cilium/cilium/pull/33768

Next I will add some configurations for it.

e2e test for node-local DNS with LRP:
- socket-lb + kpr (Done)
- socket-lb without kpr
- per packet lb (aka socket-lb off)
- socket-lb in hostns only + per packet

**Comment by ysksuzuki** [comment]
Completed 

e2e test for node-local DNS with LRP: https://github.com/cilium/cilium/pull/33768
More e2e configurations for LRP: https://github.com/cilium/cilium/pull/34954
document improvement: https://github.com/cilium/cilium/pull/35030
