### ISSUE TITLE
CFP: Add discover policy enforcement mode

### ISSUE THREAD

**Issue by andrey-yakubovskiy** [cilium/cilium#33422]
## Cilium Feature Proposal
        
Problem:
At the moment setting enforcement policy to always to achieve zero-trust is a gamble in production environments as it could lead to legitimate traffic being blocked because of incomplete network policies. 

Proposal:
Introduce "discover" mode that works as "always" mode but logs traffic not matching network policy rules instead of dropping it. This allows the operator to soft-test zero-trust setup in production and easily discover any missing rules in network policies. During discovery phase operator adjusts network policies and when ready safely switches to "always" mode.

**Comment by xmulligan** [comment]
Is this similar to https://github.com/cilium/cilium/issues/9580?

**Comment by andrey-yakubovskiy** [comment]
> Is this similar to #9580?

yes, sorry missed that one.

**Comment by xmulligan** [comment]
to centralize discussion, I'm going to close this issue. Please feel free to add any more context on that one
