### ISSUE TITLE
CI: ci-ginkgo: hubble events queue is full

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#33443]
## CI failure

Seeing a failure in ci-ginkgo on a warning resulting from Hubbles ring buffer being full.  Not sure if this is happening elsewhere so I'll raise a issue to track other instances.

Link: https://github.com/cilium/cilium/actions/runs/9656874797/job/26635161828

**Comment by bimmlerd** [comment]
Hit this again in https://github.com/cilium/cilium/actions/runs/10847714072/job/30103436040#step:18:341 (E2E Test (1.31, f18-datapath-bgp-lrp))
