### ISSUE TITLE
Helm can't enable geneve protocol:  line 132: mapping key "tunnel-protocol" already defined at line 131

### ISSUE THREAD

**Issue by CompPhy** [cilium/cilium#33456]
We are attempting to change our helm config to use Geneve instead of VXLAN, so what we can use DSR in our cluster.  Unfortunately, native routing mode is not an option in our case.

When attempting to deploy the helm chart with `tunnelProtocol: geneve` we get the error:
```
line 132: mapping key "tunnel-protocol" already defined at line 131
```

I believe this is due to the fact that the line referenced below is creating the tunnel-protocol: vxlan line.

https://github.com/cilium/cilium/blob/5614531067a83e20d24bccc7b12b314330d043c3/install/kubernetes/cilium/templates/cilium-configmap.yaml#L477

Then when it gets further down and tries to insert the geneve line, this is seen as a duplicate entry.

https://github.com/cilium/cilium/blob/5614531067a83e20d24bccc7b12b314330d043c3/install/kubernetes/cilium/templates/cilium-configmap.yaml#L481

I think the "default" in helm just needs to be a little smarter here to allow for properly enabling Geneve.

We are specifically running helm chart version 1.15.6, but it looks like this issue exists in the main branch and probably also affects 1.16.x release.

**Comment by haribhusal2025** [comment]
@CompPhy  I am not 100% sure if it a bug but we have been using 'geneve' protocol in all of our ops clusters and using helm to deploy cilium. We pass values.yml file where values are placed as:
```
kubeProxyreplacement: true
loadBalancer:
  mode: dsr
  dsrDispatch: geneve
routingMode: tunnel
tunnelProtocol: geneve
```

And this been working for us during new installation or upgrade.

**Comment by joestringer** [comment]
Hi @CompPhy, your report makes sense and I agree that the Helm templates just need to be made a bit more smart. Would you be willing to send a PR to fix this up?
