### ISSUE TITLE
CFP:  limit the gateway API to choose certain nodes when forwarding from external LB to k8s cluster

### ISSUE THREAD

**Issue by liyihuang** [cilium/cilium#33461]
## Cilium Feature Proposal
        

**Is your proposed feature related to a problem?**

when using the cilium gateway API with any Cloud provider LB, the Cloud LB will try to pick up all the instances and nodes port  as the backend for the Cloud LB. that could be problematic when the cluster is big and it's hard for people to know where the traffic goes and hard to tourbleshoot when we need to look into the certain envoy for particular HTTP query.

For example I only have 4 nodes in my cluster, it's already hard for to know which cilium-agent to check for certain HTTP request. 

![image](https://github.com/cilium/cilium/assets/8106123/1f003027-1b42-4dfc-952b-d9f0d71771a1)

My understanding is cilium gateway API will generate the gateway service and the could LB controller will read the service and deploy the Cloud LB accordingly.

This is the service for the screenshot.
```
k get svc -n emojivoto cilium-gateway-my-gateway -o yaml 
Warning: short name "svc" could also match lower priority resource services.tap.linkerd.io
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: liyitest.cute.cilium.rocks
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
  creationTimestamp: "2024-06-28T17:43:04Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  - service.k8s.aws/resources
  labels:
    io.cilium.gateway/owning-gateway: my-gateway
  name: cilium-gateway-my-gateway
  namespace: emojivoto
  ownerReferences:
  - apiVersion: gateway.networking.k8s.io/v1
    controller: true
    kind: Gateway
    name: my-gateway
    uid: f052b3b2-475a-4573-84d4-3a2fd9dd3e49
  resourceVersion: "3989"
  uid: 7a577c6c-5f3b-4aeb-9dcc-369bbe0bc294
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.100.246
  clusterIPs:
  - 172.20.100.246
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-80
    nodePort: 31265
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: k8s-emojivot-ciliumga-bf8fcd23d0-5650fe84aca29cdc.elb.ca-central-1.amazonaws.com

``` 

**Describe the feature you'd like**

I hope cilium could have some method, when I configure the gateway object, I can limit that only the nodes with certain labels will be used for the ingress traffic. My understanding is we could still generate the envoy configure as normal but when generating the gateway service as I pasted above, we could have `selector` to limit it. so the Cloud LB controller will parse it and deploy the LB with certain nodes.
```
  ports:
  - name: port-80
    nodePort: 31265
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    cilium-agent-ingress-pod: true 
```  

Or is there a plan to have dedicated envoy pods for the ingress than the daemonset mode? I personally think cilium should have a dedicated ingress pod which is a better solution than the daemonset since it can provde better flexiblity and control etc than the current daemonset mode.

**Comment by arthur1542** [comment]
@liyihuang I have the same Issue. Did you found a workaround for this problem?

**Comment by liyihuang** [comment]
@arthur1542 you can check this out https://isovalent.com/blog/post/cilium-1-16/#h-host-network-mode-envoy-listeners-on-subset-of-nodes
