### ISSUE TITLE
CFP: Cilium Gateway API - more Gateway features

### ISSUE THREAD

**Issue by jansoukup** [cilium/cilium#33500]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**
No

**Describe the feature you'd like**

- Basic rate limiting based on Services, or a more advanced approach to rate limiting, which could provide higher granularity. For example, in cooperation with HPA, sizing rate limits based on deployment replicas.
- Access for a specific gateway based on roles and/or clientId in JWT.
- Handling CORS requests.

**Comment by mikemorris** [comment]
Related upstream Gateway API issues for these features:
- https://github.com/kubernetes-sigs/gateway-api/issues/326
- https://github.com/kubernetes-sigs/gateway-api/issues/1494
- https://github.com/kubernetes-sigs/gateway-api/issues/1767

**Comment by sayboras** [comment]
Thanks for your issue. 

The general  approach is to wait for features accepted in upstream first, then Cilium will plan to support them. As mentioned by above message from Mike, it seems like these GEPs are either closed or still in progress.

**Comment by jhutchins** [comment]
https://github.com/kubernetes-sigs/gateway-api/issues/1494 has now moved to experimental and has a defined API. Should a separate tracking issue be created for adding support?
