### ISSUE TITLE
unable to determine direct routing device. Use --direct-routing-device to specify it (except that option is set)

### ISSUE THREAD

**Issue by bhechinger** [cilium/cilium#33527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Attempting to setup cilium in direct routing mode (cluster shares a secondary, private L2 network).

I expected cilium to be able to route all cluster traffic over the private network.

### Cilium Version

RKE2 included helm chart. Cilium version 1.15.6.

### Kernel Version

Linux master1 6.8.12 #1-NixOS SMP PREEMPT_DYNAMIC Thu May 30 07:49:53 UTC 2024 x86_64 GNU/Linux

### Kubernetes Version

v1.28.10+rke2r1

### Sysdump

[cilium-sysdump-20240702-085709.zip](https://github.com/user-attachments/files/16065421/cilium-sysdump-20240702-085709.zip)

### Relevant log output

```shell
level=fatal msg="failed to start: daemon creation failed: failed to detect devices: unable to determine direct routing device. Use --direct-routing-device to specify it" subsys=daemon

DEBUG: userDevices: [external,internal]
DEBUG: Initial DirectRoutingDevice: internal
DEBUG: filter: [internal]
DEBUG: devs: []
DEBUG: After match DirectRoutingDevice: 
DEBUG: Final DirectRoutingDevice:
```

### Anything else?

The error produced by cilium was not useful. I'm already providing `--direct-routing-device`.

I've added some debug logging to `pkg/datapath/linux/devices.go` to produce the above logging output.

You can see I've set both `--devices` and `--direct-routing-device` but then as cilium doesn't appear to be able to get my list of network interfaces for some reason it removes them as options.

Network interfaces (the bridges were added because I thought maybe it didn't like the `@` in the vlan device name):
```
[wonko@master1:~]$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master external state UP group default qlen 1000
    link/ether 52:54:00:b2:4a:69 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5054:ff:feb2:4a69/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:4e:03:62 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5054:ff:fe4e:362/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
4: vlan4000@enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master internal state UP group default qlen 1000
    link/ether 52:54:00:4e:03:62 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5054:ff:fe4e:362/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
5: external: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:b2:4a:69 brd ff:ff:ff:ff:ff:ff
    inet 10.22.20.11/24 brd 10.22.20.255 scope global dynamic noprefixroute external
       valid_lft 2319sec preferred_lft 1718sec
    inet6 fe80::5054:ff:feb2:4a69/64 scope link 
       valid_lft forever preferred_lft forever
6: internal: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:4e:03:62 brd ff:ff:ff:ff:ff:ff
    inet 10.22.30.11/24 scope global internal
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe4e:362/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
```

Added logging:
```
diff --git a/pkg/datapath/linux/devices.go b/pkg/datapath/linux/devices.go
index 5807a71305..f1d60f99ca 100644
--- a/pkg/datapath/linux/devices.go
+++ b/pkg/datapath/linux/devices.go
@@ -31,6 +31,7 @@ type DeviceManager struct {
 func (dm *DeviceManager) Detect(k8sEnabled bool) ([]string, error) {
        hasWildcard := false
        userDevices := option.Config.GetDevices()
+       fmt.Printf("DEBUG: userDevices: %s\n", userDevices)
        for _, name := range userDevices {
                hasWildcard = hasWildcard || strings.HasSuffix(name, "+")
        }
@@ -40,8 +41,12 @@ func (dm *DeviceManager) Detect(k8sEnabled bool) ([]string, error) {
        }
 
        rxn := dm.params.DB.ReadTxn()
+       dt, _ := dm.params.DeviceTable.All(rxn)
+       fmt.Printf("DEBUG: dt: %+v\n", dt)
+
        devs, _ := tables.SelectedDevices(dm.params.DeviceTable, rxn)
        names := tables.DeviceNames(devs)
+       fmt.Printf("DEBUG: rxn: %+v devs: %+v names: %+v\n", rxn, devs, names)
 
        if len(names) == 0 && hasWildcard {
                // Fail if user provided a device wildcard which didn't match anything.
@@ -67,23 +72,29 @@ func (dm *DeviceManager) Detect(k8sEnabled bool) ([]string, error) {
        if option.Config.DirectRoutingDeviceRequired() {
                var filter deviceFilter
                if option.Config.DirectRoutingDevice != "" {
+                       fmt.Printf("DEBUG: Initial DirectRoutingDevice: %s\n", option.Config.DirectRoutingDevice)
                        filter = deviceFilter(strings.Split(option.Config.DirectRoutingDevice, ","))
+                       fmt.Printf("DEBUG: filter: %s\n", filter)
                }
                option.Config.DirectRoutingDevice = ""
                if filter.nonEmpty() {
                        // User has defined a direct-routing device. Try to find the first matching
                        // device.
+                       fmt.Printf("DEBUG: devs: %+v\n", devs)
                        for _, dev := range devs {
                                if filter.match(dev.Name) {
+                                       fmt.Printf("DEBUG: checking DRD:%s dev:%s\n", option.Config.DirectRoutingDevice, dev.Name)
                                        option.Config.DirectRoutingDevice = dev.Name
                                        break
                                }
                        }
+                       fmt.Printf("DEBUG: After match DirectRoutingDevice: %s\n", option.Config.DirectRoutingDevice)
                } else if len(devs) == 1 {
                        option.Config.DirectRoutingDevice = devs[0].Name
                } else if nodeDevice != nil {
                        option.Config.DirectRoutingDevice = nodeDevice.Name
                }
+               fmt.Printf("DEBUG: Final DirectRoutingDevice: %s\n", option.Config.DirectRoutingDevice)
                if option.Config.DirectRoutingDevice == "" {
                        return nil, fmt.Errorf("unable to determine direct routing device. Use --%s to specify it",
                                option.DirectRoutingDevice)
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bhechinger** [comment]
So after getting some advice on the Cilium/eBPF Slack I changed my devices list from a comma separated list to a space separated list. This solved the issue completely.

This appears to be a documentation error. Both on the part of the cilium agent (the docs aren't clear on the format of the devices list) and the section of the docs `Kubernetes Without kube-proxy` which states: `To change the devices, set their names in the devices Helm option, e.g. devices='{eth0,eth1,eth2}'` which is incorrect.

**Comment by djeinstine** [comment]
Hi. What is the actual answer here? I encountered the same error, and I did the following to no avail

`devices='{eth0 eth1 eth2}'`

Also, how is this solved if the docs are still wrong?

**Comment by dmfrey** [comment]
Any update on this?

**Comment by djeinstine** [comment]
@dmfrey 

I figured out from somewhere that actual lists are made without the brackets and double quotations. So in my helm values I have

`devices: "enp1s0 eth0"`

So I presume the command line option would be

`devices="enp1s0 eth0"`

I am using 1.16.6.

**Comment by dmfrey** [comment]
Ok, thank you

**Comment by guyasn** [comment]
For the issue was with detection of the --direct-routing-device. I keep getting the error:
level=fatal msg="failed to start: daemon creation failed: unable to determine direct routing device. Use --direct-routing-device to specify it

I ran the following (where bond0 is the interface I wish to pass to the --direct-routing-device):
_**podman run --rm --network host --privileged quay.io/cilium/cilium:v1.17.4 /bin/sh -c "ip route show dev bond0"**_

The output is:
_default via 172.18.32.129 proto static metric 300
172.18.32.128/25 proto kernel scope link src 172.18.32.153 metric 300_

--> so it can be seen that the bond0 interface is both accessible from the container and also has a legitimate IPv4 address, but still the boot of the Cilium container fails. Any idea what I am doing wrong/what to check further?

**Comment by Blackclaws** [comment]
@bhechinger Could you reopen this? Its a documentation error but I also just ran into this and the docs should be fixed.

**Comment by joestringer** [comment]
@Blackclaws I would suggest filing a new issue. For most users, this can be fixed by specifying the configuration `devices: eth+` (or equivalent device pattern for your distro, such as `ens+`) .
