### ISSUE TITLE
After install cilium in EKS version  1.30, droped any resources.

### ISSUE THREAD

**Issue by Hudsoncoutinho** [cilium/cilium#33605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A bug happened!"After installing Cilium version 1.15.6 on AWS EKS version 1.30, some cluster resources are stuck in `ContainerCreating` status."

![Captura de Tela 2024-07-05 às 17 11 11](https://github.com/cilium/cilium/assets/49199914/19fc6118-9e7a-4db5-b9b2-d1a5608cc104)

### Cilium Version

1.15.6

### Kernel Version

..

### Kubernetes Version

EKS 1.30

### Sysdump

[k8s-version-20240705-171715.txt](https://github.com/user-attachments/files/16113516/k8s-version-20240705-171715.txt)
[logs-cilium-8sr9l-apply-sysctl-overwrites-20240705-171715.log](https://github.com/user-attachments/files/16113518/logs-cilium-8sr9l-apply-sysctl-overwrites-20240705-171715.log)
[logs-cilium-8sr9l-cilium-agent-20240705-171715.log](https://github.com/user-attachments/files/16113519/logs-cilium-8sr9l-cilium-agent-20240705-171715.log)
[logs-cilium-8sr9l-clean-cilium-state-20240705-171715.log](https://github.com/user-attachments/files/16113520/logs-cilium-8sr9l-clean-cilium-state-20240705-171715.log)
[logs-cilium-8sr9l-config-20240705-171715.log](https://github.com/user-attachments/files/16113521/logs-cilium-8sr9l-config-20240705-171715.log)
[logs-cilium-8sr9l-install-cni-binaries-20240705-171715.log](https://github.com/user-attachments/files/16113522/logs-cilium-8sr9l-install-cni-binaries-20240705-171715.log)
[logs-cilium-8sr9l-mount-bpf-fs-20240705-171715.log](https://github.com/user-attachments/files/16113523/logs-cilium-8sr9l-mount-bpf-fs-20240705-171715.log)
[logs-cilium-8sr9l-mount-cgroup-20240705-171715.log](https://github.com/user-attachments/files/16113524/logs-cilium-8sr9l-mount-cgroup-20240705-171715.log)
[logs-cilium-hgxjq-apply-sysctl-overwrites-20240705-171715.log](https://github.com/user-attachments/files/16113525/logs-cilium-hgxjq-apply-sysctl-overwrites-20240705-171715.log)
[logs-cilium-hgxjq-cilium-agent-20240705-171715.log](https://github.com/user-attachments/files/16113526/logs-cilium-hgxjq-cilium-agent-20240705-171715.log)
[logs-cilium-hgxjq-clean-cilium-state-20240705-171715.log](https://github.com/user-attachments/files/16113528/logs-cilium-hgxjq-clean-cilium-state-20240705-171715.log)
[logs-cilium-hgxjq-install-cni-binaries-20240705-171715.log](https://github.com/user-attachments/files/16113529/logs-cilium-hgxjq-install-cni-binaries-20240705-171715.log)
[logs-cilium-hgxjq-mount-bpf-fs-20240705-171715.log](https://github.com/user-attachments/files/16113530/logs-cilium-hgxjq-mount-bpf-fs-20240705-171715.log)
[logs-cilium-hgxjq-mount-cgroup-20240705-171715.log](https://github.com/user-attachments/files/16113531/logs-cilium-hgxjq-mount-cgroup-20240705-171715.log)
[logs-cilium-operator-c6f4bb6f-2knlv-cilium-operator-20240705-171715.log](https://github.com/user-attachments/files/16113532/logs-cilium-operator-c6f4bb6f-2knlv-cilium-operator-20240705-171715.log)

### Anything else?

reference for install:

https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
In this case the k8s-event-* yaml file from the sysdump should be of help, it typically contains logs from the API server hopefully telling us why its stuck. Would you be able to provide it?

**Comment by Hudsoncoutinho** [comment]
@dylandreimerink TKS FOR YOUR HELP, IM GO CHECK THIS FILE

**Comment by Hudsoncoutinho** [comment]
@dylandreimerink all events reports this message:

**Comment by Hudsoncoutinho** [comment]
message: 'Failed to create pod sandbox: rpc error: code = Unknown desc = failed
    to setup network for sandbox "be1380067f87a3c0842bd8f71711387924e92fb1a0e3b233390578e511c21aa4":
    plugin type="cilium-cni" failed (add): unable to create endpoint: Cilium API client
    timeout exceeded'

**Comment by dylandreimerink** [comment]
Ah, that helps. It seems like Cilium is unable to allocate an identity for these pods. The agent log has this error repeated a lot:
```
024-07-05T20:16:57.955036564Z time="2024-07-05T20:16:57Z" level=warning msg="Key allocation attempt failed" attempt=0 error="unable to allocate ID 30972 for key [k8s:app.kubernetes.io/instance=external-dns k8s:app.kubernetes.io/name=external-dns k8s:io.cilium.k8s.namespace.labels.field.cattle.io/projectId=p-f2lpr k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=arn:aws:eks:us-east-1:767600734889:cluster/linker-k8s-dev-v1 k8s:io.cilium.k8s.policy.serviceaccount=external-dns k8s:io.kubernetes.pod.namespace=default]: CiliumIdentity.cilium.io \"30972\" is invalid: metadata.labels: Invalid value: \"arn:aws:eks:us-east-1:767600734889:cluster/linker-k8s-dev-v1\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" key="[k8s:app.kubernetes.io/instance=external-dns k8s:app.kubernetes.io/name=external-dns k8s:io.cilium.k8s.namespace.labels.field.cattle.io/projectId=p-f2lpr k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=arn:aws:eks:us-east-1:767600734889:cluster/linker-k8s-dev-v1 k8s:io.cilium.k8s.policy.serviceaccount=external-dns k8s:io.kubernetes.pod.namespace=default]" subsys=allocator
```

So it seems like Cilium can't handle the value of the `k8s:io.cilium.k8s.policy.cluster` label. Its the `:`s in `arn:aws:eks:us-east-1:767600734889:cluster/linker-k8s-dev-v1` that it doesn't like.

This label is set by Cilium based on the `--cluster-name` flag / `cluster.name` helm option. So modifying that value via helm or the configmap then restarting your agents should do the trick

**Comment by Hudsoncoutinho** [comment]
I understand, the problem is that I use this tag to call and address other resources and my apps for the cluster...

**Comment by vipulmalgotra** [comment]
Is this resolved. If so could you please share the resolution details.
