### ISSUE TITLE
Failed to serve cilium-health API" error="listen tcp [fe80::345d:95ff:fe9c:5bf8]:4240: bind: invalid argument

### ISSUE THREAD

**Issue by bono5150** [cilium/cilium#33648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The following commnad:
kubectl -n kube-system exec -ti cilium-wpmdx -- "cilium-health" status --verbose
shows that the HTTP to agent /hello endpoint refuses connections:

HTTP to agent:   Get "http://192.168.1.225:4240/hello": dial tcp 192.168.1.225:4240: connect: connection refused
HTTP to agent:   Get "http://[fe80::345d:95ff:fe9c:5bf8]:4240/hello": dial tcp [fe80::345d:95ff:fe9c:5bf8]:4240: connect: invalid argument

The log shows that: listen tcp [fe80::345d:95ff:fe9c:5bf8]:4240: bind: invalid argument

What should I do to provide valid argument ?
I expect from the cilium-health to connect to other nodes in a k3s bare-metal cluster without any communication issues.

### Cilium Version

cilium-cli: v0.16.11 compiled with go1.22.4 on linux/amd64
cilium image (default): v1.15.6
cilium image (stable): unknown
cilium image (running): 1.15.6

### Kernel Version

Linux k3s-control-01 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.29.6+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6+k3s1

### Relevant log output

```shell
kubectl -n kube-system exec -ti cilium-wpmdx -- "cilium-health" status --verbose
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Probe time:   2024-07-08T06:38:18Z
Nodes:
  k3s-agent-01 (localhost):
    Host connectivity to 192.168.1.225:
      ICMP to stack:   OK, RTT=886.835µs
      HTTP to agent:   Get "http://192.168.1.225:4240/hello": dial tcp 192.168.1.225:4240: connect: connection refused
      Secondary connectivity to fe80::345d:95ff:fe9c:5bf8:
        ICMP to stack:   Connection timed out
        HTTP to agent:   Get "http://[fe80::345d:95ff:fe9c:5bf8]:4240/hello": dial tcp [fe80::345d:95ff:fe9c:5bf8]:4240: connect: invalid argument
    Endpoint connectivity to 10.42.1.83:
      ICMP to stack:   OK, RTT=725.687µs
      HTTP to agent:   OK, RTT=93.582µs
      Secondary connectivity to 2001:cafe:42::103:
        ICMP to stack:   OK, RTT=1.450422ms
        HTTP to agent:   OK, RTT=81.345µs
  k3s-agent-02:
    Host connectivity to 192.168.1.226:
      ICMP to stack:   OK, RTT=917.781µs
      HTTP to agent:   Get "http://192.168.1.226:4240/hello": dial tcp 192.168.1.226:4240: connect: connection refused
      Secondary connectivity to fe80::cce9:bff:fe9c:ad1c:
        ICMP to stack:   Connection timed out
        HTTP to agent:   Get "http://[fe80::cce9:bff:fe9c:ad1c]:4240/hello": dial tcp [fe80::cce9:bff:fe9c:ad1c]:4240: connect: invalid argument
    Endpoint connectivity to 10.42.2.76:
      ICMP to stack:   OK, RTT=840.079µs
      HTTP to agent:   OK, RTT=1.045511ms
      Secondary connectivity to 2001:cafe:42::2dc:
        ICMP to stack:   OK, RTT=1.481404ms
        HTTP to agent:   OK, RTT=265.056µs
  k3s-agent-03:
    Host connectivity to 192.168.1.227:
      ICMP to stack:   OK, RTT=933.924µs
      HTTP to agent:   Get "http://192.168.1.227:4240/hello": dial tcp 192.168.1.227:4240: connect: connection refused
      Secondary connectivity to fe80::148d:afff:fe0f:f825:
        ICMP to stack:   Connection timed out
        HTTP to agent:   Get "http://[fe80::148d:afff:fe0f:f825]:4240/hello": dial tcp [fe80::148d:afff:fe0f:f825]:4240: connect: invalid argument
    Endpoint connectivity to 10.42.3.150:
      ICMP to stack:   OK, RTT=855.256µs
      HTTP to agent:   OK, RTT=408.711µs
      Secondary connectivity to 2001:cafe:42::38a:
        ICMP to stack:   OK, RTT=1.500904ms
        HTTP to agent:   OK, RTT=388.109µs
  k3s-control-01:
    Host connectivity to 192.168.1.220:
      ICMP to stack:   OK, RTT=812.469µs
      HTTP to agent:   Get "http://192.168.1.220:4240/hello": dial tcp 192.168.1.220:4240: connect: connection refused
      Secondary connectivity to fe80::78fa:a5ff:fec2:28cd:
        ICMP to stack:   Connection timed out
        HTTP to agent:   Get "http://[fe80::78fa:a5ff:fec2:28cd]:4240/hello": dial tcp [fe80::78fa:a5ff:fec2:28cd]:4240: connect: invalid argument
    Endpoint connectivity to 10.42.0.18:
      ICMP to stack:   OK, RTT=789.711µs
      HTTP to agent:   OK, RTT=379.749µs
      Secondary connectivity to 2001:cafe:42::e7:
        ICMP to stack:   OK, RTT=1.410322ms
        HTTP to agent:   OK, RTT=406.881µs
```

### Anything else?

level=error msg="Failed to serve cilium-health API" error="listen tcp [fe80::345d:95ff:fe9c:5bf8]:4240: bind: invalid argument" subsys=cilium-health-launcher

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @bono5150 , can you share the information about your kubernetes Nodes including all IP addressing information? A sysdump would also provide this. 

Also do you know if you are intending to use link-local addresses for all of your nodes? Are they all connected via L2?

**Comment by bono5150** [comment]
Hi Joe.

1. Can you share the information about your kubernetes Nodes including all IP addressing information?
There is only one control node and three agent nodes in the k3s cluster at the moment.

k3s-control-01
			   k3s.io/internal-ip: 192.168.1.220,fe80::78fa:a5ff:fec2:28cd
			   k3s.io/node-args: ['--cluster-init' ,'--cluster-cidr=10.42.0.0/16,2001:cafe:42::/56','--service-cidr=10.43.0.0/16,2001:cafe:43::/112','--node-ip=192.168.1.220,fe80::78fa:a5ff:fec2:28cd','--flannel-backend=none','--disable-kube-proxy','--disable=servicelb','--disable-network-policy','--disable=traefik','--write-kubeconfig=/home/k3s/.kube/config','--write-kubeconfig-mode=600']
k3s-agent-01
                    k3s.io/internal-ip: 192.168.1.225,fe80::345d:95ff:fe9c:5bf8
                    k3s.io/node-args: ["agent","--node-ip","192.168.1.225,fe80::345d:95ff:fe9c:5bf8"]
k3s-agent-02
                    k3s.io/internal-ip: 192.168.1.226,fe80::cce9:bff:fe9c:ad1c
                    k3s.io/node-args: ["agent","--node-ip","192.168.1.226,fe80::cce9:bff:fe9c:ad1c"]
k3s-agent-03
                    k3s.io/internal-ip: 192.168.1.227,fe80::148d:afff:fe0f:f825
                    k3s.io/node-args: ["agent","--node-ip","192.168.1.227,fe80::148d:afff:fe0f:f825"]

2. Do you know if you are intending to use link-local addresses?
Yes, link-local addresses are assigned for all of the nodes.

2.1 assigned from router DHCP service for ipv4:
	192.168.1.220, 192.168.1.225, 192.168.1.226, 192.168.1.227
2.2 assigned statically (router DHCP service doesn't support ipv6 adressing):
	fe80::78fa:a5ff:fec2:28cd, fe80::345d:95ff:fe9c:5bf8, 192.168.1.226,fe80::cce9:bff:fe9c:ad1c, fe80::148d:afff:fe0f:f825

All hosts are running by Xen virtualization server (XCP-NG).

3. Are they all connected via L2?

All nodes are connected to the same switch working in L2. On L2 layer there is only one VLAN at the moment. It is the very basic configuration. The switch is connected to a router and the router to Internet WAN.
[nodes-20240712-085846.json](https://github.com/user-attachments/files/16189985/nodes-20240712-085846.json)

**Comment by joestringer** [comment]
I see, thanks for providing the details. I strongly suspect that the connectivity health checker simply doesn't support link-local addressing for health probes, and the `invalid argument` error is bubbling up from the kernel somewhere. As a workaround you can disable the feature with `endpointHealthChecking.enabled=false`.

If you're interested in investigating this further and submitting a PR to add support here, you are welcome to do so - the code is [here](https://github.com/cilium/cilium/blob/af7f165f7882330f753763c78916e810dd65a5be/pkg/health/server/prober.go#L280).
