### ISSUE TITLE
Cilium agents fall into an infinite restarts loop after update

### ISSUE THREAD

**Issue by bufonNocy** [cilium/cilium#33675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When update Cilium to vr 1.16.0-rc.1 in EKS cluster with up to 150+ nodes Cilium agents fall into an infinite restarts loop with error:  `error="timed out after 3m0s since receiving last event for resource \"core/v1::Service\`. The API endpoint is different every time, usually I can catche: `Service`, `CiliumCIDRGroup` or `CiliumNetworkPolicy`. Same installation works fine in EKS cluster with ~30 nodes.

### Cilium Version

1.16.0-rc.1

### Kernel Version

EKS 1.26

### Kubernetes Version

Client Version: v1.27.12
Kustomize Version: v5.0.1
Server Version: v1.26.15-eks-3af477

### Relevant log output

```shell
EnableDefaultDeny:{Ingress:0xc0062a1fdc Egress:0xc0062a1fdb} Description:}]" policyAddRequest=4f3d96ae-3db6-427b-807d-5351a2f2cea4 subsys=daemon
time="2024-07-09T11:35:18Z" level=info msg="Policy imported via API, recalculating..." policyAddRequest=4f3d96ae-3db6-427b-807d-5351a2f2cea4 policyRevision=12 subsys=daemon
time="2024-07-09T11:35:18Z" level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=sip k8sApiVersion=cilium.io/v2 k8sNamespace=sip subsys=policy-k8s-watcher
time="2024-07-09T11:35:38Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-07-09T11:35:39Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=2
time="2024-07-09T11:38:18Z" level=fatal msg="Timed out waiting for pre-existing resources to be received; exiting" error="timed out after 3m0s since receiving last event for resource \"core/v1::Service\"" subsys=k8s-watcher
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bufonNocy** [comment]
@aanm I updated same cluster to vr `1.15.6` and everything went smoothly

**Comment by aanm** [comment]
@bufonNocy can you share a sysdump of the failing cluster? Thank you

**Comment by bufonNocy** [comment]
Yes I can but it has more then 632 MB where here here is limit up to 25 MB

**Comment by aanm** [comment]
> Yes I can but it has more then 632 MB where here is limit up to 25 MB

Can you do `cilium sysdump --node-list <name of one of the nodes failing>`

**Comment by bufonNocy** [comment]
@aanm here you have `sysdump` from failing node, I anonymized it a little bit. [cilium-sysdump-20240710-084544-anon.zip](https://github.com/user-attachments/files/16159575/cilium-sysdump-20240710-084544-anon.zip)

Some stats from the cluster:
Nodes: 135
PODs: 1290
Deployments: 630
DemonSets: 124
CiliumNetworkPolicies: 124 (only 1 global)
CLRP: 1 (dns)
Ingresses: 980
Services: 1110

Do you need something more?

**Comment by aanm** [comment]
There's a deadlock where go routine A grabs the mutex in https://github.com/cilium/cilium/blob/f1b533405c77d7bce3c76f0db4beeea650730d16/pkg/k8s/service_cache.go#L347

and then it gets stuck because it can't send more events to the channel X.

```
1 occurences. Sample stack trace:
github.com/cilium/stream.ToChannel[...].func1()
	./vendor/github.com/cilium/stream/sinks.go:137 +0x1c
github.com/cilium/stream.Multicast[...].func1()
	./vendor/github.com/cilium/stream/sources.go:205 +0x1fe
github.com/cilium/cilium/pkg/k8s.(*ServiceCache).emitEvent(0xc002348630, {0x0, {{0x0, 0x0}, {0xc001fafdd0, 0x13}, {0xc001512418, 0x6}}, 0xc005633b80, 0x0, ...})
	./pkg/k8s/service_cache.go:206 +0x115
github.com/cilium/cilium/pkg/k8s.(*ServiceCache).UpdateService(0xc002348630, 0xc002683c20, 0xc0013daab0)
	./pkg/k8s/service_cache.go:363 +0x645
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sServiceWatcher).upsertK8sServiceV1(0xc0003dd180, 0xc002683c20, 0x10?)
	./pkg/k8s/watchers/service.go:136 +0x39
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sServiceWatcher).serviceEventLoop(0xc0003dd180, 0xc0017b6178, 0xc0013daab0)
	./pkg/k8s/watchers/service.go:124 +0x25f
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sServiceWatcher).servicesInit in goroutine 1
	./pkg/k8s/watchers/service.go:95 +0x15e
```

That channel X should be read in https://github.com/cilium/cilium/blob/99a15397fc830a5d67a89e3095aafc65811c3cea/pkg/policy/k8s/watcher.go#L179 but it can't because go routine B is stuck while trying to grab the same lock being held by go routine A in https://github.com/cilium/cilium/blob/f1b533405c77d7bce3c76f0db4beeea650730d16/pkg/k8s/service_cache.go#L305

```
1 occurences. Sample stack trace:
sync.runtime_SemacquireRWMutexR(0x41ad98?, 0xe0?, 0xc0013b8a00?)
	/usr/local/go/src/runtime/sema.go:82 +0x25
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:70
github.com/cilium/cilium/pkg/k8s.(*ServiceCache).ForEachService(0xc002348630, 0xc0013b8a00)
	./pkg/k8s/service_cache.go:305 +0x5c
github.com/cilium/cilium/pkg/policy/k8s.(*policyWatcher).resolveToServices(...)
	./pkg/policy/k8s/service.go:116
github.com/cilium/cilium/pkg/policy/k8s.(*policyWatcher).resolveCiliumNetworkPolicyRefs(0xc001509450, 0xc00144b1f8, {{0xc005234126, 0x6}, {0xc005234130, 0x6}}, {0x3?, 0xccc432?, 0x6947420?}, {0xc004472018, ...})
	./pkg/policy/k8s/cilium_network_policy.go:123 +0x237
github.com/cilium/cilium/pkg/policy/k8s.(*policyWatcher).onUpsert(0xc001509450, 0xc00144b1f8, {{0xc005234126, 0x6}, {0xc005234130, 0x6}}, {0x3e6cc9e, 0x1e}, {0xc004472018, 0x11})
	./pkg/policy/k8s/cilium_network_policy.go:74 +0x685
github.com/cilium/cilium/pkg/policy/k8s.(*policyWatcher).watchResources.func1()
	./pkg/policy/k8s/watcher.go:118 +0xc6d
created by github.com/cilium/cilium/pkg/policy/k8s.(*policyWatcher).watchResources in goroutine 1
	./pkg/policy/k8s/watcher.go:57 +0x74

```

**Comment by aanm** [comment]
@bufonNocy thank you, the sysdump was helpful to get the root cause.

**Comment by gandro** [comment]
I have been able to reproduce the issue by `extraConfig.k8s-service-cache-size=2` and creating some service churn. This indeed indicates that the buffered channel here is to blame:

https://github.com/cilium/cilium/blob/99a15397fc830a5d67a89e3095aafc65811c3cea/pkg/policy/k8s/watcher.go#L179

Looking into potential solutions now

**Comment by aanm** [comment]
@bufonNocy please try out v1.16.0-rc.2 as the issue is fixed on that version.

**Comment by bufonNocy** [comment]
@aanm I updated the cluster to `v1.16.0-rc.2` and everything went smoothly, 145 nodes has been updated and I don't see any other issues for this moment.
