### ISSUE TITLE
Azure Docs not Clear for Chain Mode -  Services timesout to call API Server 

### ISSUE THREAD

**Issue by Mais316** [cilium/cilium#33678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Unclear docs https://docs.cilium.io/en/stable/installation/cni-chaining-azure-cni/

I am trying to follow docs but I have below issues:
- Why it didnt mention cni.execlusive=false, also why do I have to manually create a configmap, why helm chart doesnt support that it can take the data as block and create the configmap, installing it like that using fleet or argocd doesnt really look clean everything should be in same chart.

Updates 
- Tested with cni.execlusive=false > cilium is healthy but all services calls to API server is timing out so for example coredns is not working and removing cilium fix the cluster. So not sure what I missed.
- Cluster has Azure CNI and Azure NPM 

### Cilium Version

1.15.7

### Kernel Version

# uname -a
Linux aks-wrk0 5.15.0-1066-azure #75-Ubuntu SMP Thu May 30 14:29:45 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.28.10

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mais316** [comment]
updates > followed doc and used cni.execlsuive=false 

My cluster has Azure CNI and NPM but after installing cilium as described, cilium is healthy but all other services calls to apiserver is timing out 

I am using k8s version 1.28.10 and cilium upgraded to 1.15.7, any help would be appreciated if anyone managed to get that setup working.

**Comment by amitmavgupta** [comment]
@Mais316 Thanks for reporting the issue.

- The document was written with Azure CNI (Legacy), which is deprecated or a legacy way of installing Cilium in an AKS cluster.
- We recommend users to either use BYOCNI or Azure CNI powered by Cilium- https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-cilium & https://docs.cilium.io/en/stable/installation/k8s-install-aks/
- Also, I can see that you are trying to use Azure NPM in this chaining configuration, which I am not sure has been tested/validated.
- In either case, chaining for BYOCNI would have to be validated. If you can try that out and submit a docs PR that would be great validation for your use-case.

**Comment by Mais316** [comment]
@amitmavgupta thanks for your kind reply, issue here is based on reading `Kubernetes
Networking and Cilium` > found statement

```yaml
If you'd like access to all Cilium features, you can, for example, use AKS?s ?Bring-Your-Own-CNI? option. It
lets you deploy a cluster without a CNI and install the one of your choice. While this model enables you to
install and customize Cilium fully, it comes with the caveat that Microsoft support couldn't help with
CNI- related issues.
```

I am trying to test chaining as our environment can not take the risk of not getting Microsoft support in case of critical issues. 

Next I will try to remove Azure NPM, also based on my troubleshooting, I see calls goes to API server but its not replying back,
DNS service is impacted so everything else is not working.

Do we have a matrix for what would be the proper coredns version for cilium 1.15.7 and k8s, I am stuck on that testing for days now :(?

**Comment by joestringer** [comment]
Cilium should work with any coredns version, I'm not aware of any constraints that would make certain versions not work.

One common reason why the API server does not reply back is that the source address of the Pods is not routable at the API server. You could try to better understand this using `hubble observe` or tcpdump at the source node for one of your applications to understand what addressing that the Pods are using and check that the traffic is being successfully transmitted out from the source node.

But yes as Amit describes above, there are two more modern options for deploying in Azure environments that you are more likely to have success with. For reference the Cilium OSS project tests only the BYOCNI option. I imagine that Microsoft as a vendor has its own testing for the Azure CNI powered by Cilium option.

**Comment by Mais316** [comment]
@joestringer Had a call with Azure support and they could re-produce the issue from their side as well. 

Issues I see:
- Doc here https://docs.cilium.io/en/stable/installation/cni-chaining-azure-cni/ should mention this is legacy and not tested setup
- So proper doc would be https://docs.cilium.io/en/stable/installation/cni-chaining-generic-veth/ but it should as well mention that we shall not have any other policy manager in place.
- Today will destroy cluster and build it without NPM as agreed with azure support.

**Comment by joestringer** [comment]
@Mais316 The very first thing on the page describes that this is not the preferred option and provides the other two options that are more likely to result in success:

https://docs.cilium.io/en/stable/installation/cni-chaining-azure-cni/

> For most users, the best way to run Cilium on AKS is either AKS BYO CNI as described in [Cilium Quick Installation](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#k8s-install-quick) or [Azure CNI Powered by Cilium](https://aka.ms/aks/cilium-dataplane). This guide provides alternative instructions to run Cilium with Azure CNI in a chaining configuration.

Using generic-veth chaining for this is going even further away from tested integrations, so no I don't think we should link to that one.

I think it's reasonable to extend the docs to recommend against using NPM :+1: .

**Comment by Mais316** [comment]
I totally understand but we can't give Azure support away so I can't go for BYOCNI.

For azure cni powered by cilium there is no way to customise anything even as per my reading CRDs are not there, we care about pod to pod encryption this is not possible in Azure cni powered by cilium.

We only need cilium as a service mesh we don't need it to do routing or ipam.
________________________________

**Comment by joestringer** [comment]
What you say makes sense yep, and I welcome you to report back your findings so we can make the guides better.

> Using generic-veth chaining for this is going even further away from tested integrations, so no I don't think we should link to that one.

Just double-checking this.. currently the difference is:

[Azure chaining docs](https://docs.cilium.io/en/stable/installation/cni-chaining-azure-cni/):

```
helm install cilium cilium/cilium --version 1.15.7 \
  --namespace kube-system \
  --set cni.chainingMode=generic-veth \
  --set cni.customConf=true \
  --set nodeinit.enabled=true \
  --set cni.configMap=cni-configuration \
  --set routingMode=native \
  --set enableIPv4Masquerade=false \
  --set endpointRoutes.enabled=true
```

[Generic chaining docs](https://docs.cilium.io/en/stable/installation/cni-chaining-generic-veth/):
```
helm install cilium cilium/cilium --version 1.15.7 \
  --namespace=kube-system \
  --set cni.chainingMode=generic-veth \
  --set cni.customConf=true \
  --set cni.configMap=cni-configuration \
  --set routingMode=native \
  --set enableIPv4Masquerade=false
```

And, the Azure chaining docs specify exactly how the `cni-configuration` should look, whereas the generic-veth guide leaves this up to you to figure out.

So it looks like it's mainly just two settings that differ - `nodeinit.enabled` and `endpointRoutes.enabled`. If you experience different/better behaviour then it is possible that one of these options is the cause.

**Comment by Mais316** [comment]
@joestringer @amitmavgupta its working now, thanks for your kind help

I used https://docs.cilium.io/en/stable/installation/cni-chaining-generic-veth/ and removed npm :)

**Comment by Mais316** [comment]
@joestringer @amitmavgupta its working now, thanks for your kind help

I used https://docs.cilium.io/en/stable/installation/cni-chaining-generic-veth/ and removed npm :)

One more change I did is `cni.exclusive=false`

**Comment by joestringer** [comment]
For my curiousity, I see that the CNI config has this line:
```
              "ipsToRouteViaHost":["169.254.20.10"],
```

Does this IP address have significance in standard Azure environments such that we should potentially recommend this in general in those environments? Or is this something for your own infrastructure? I do see some references to it being an example IP for node-local DNS but I don't know the significance.

**Comment by Mais316** [comment]
I copied current Azure cni config file as is and added cilium part, so no customization from my side that was default file.
________________________________

**Comment by Mais316** [comment]
> Great to hear that @Mais316 once you have everything sorted out would you be kind to submit a docs PR to update the same? cc @joestringer

Should I update the azure docs here https://docs.cilium.io/en/stable/installation/cni-chaining-azure-cni/ you mean or this would be part of the generic veth chaining?

**Comment by amitmavgupta** [comment]
@joestringer The local listen IP address for NodeLocal DNSCache can be any IP in the 169.254.20.0/16 space or any other IP address that can be guaranteed to not collide with any existing IP. The first 10 IPs in that space are reserved, and across all deployments, I have seen 169.254.20.10 as the DNS IP by all means. :)
