### ISSUE TITLE
DNS Proxy opens multiple upstream TCP connections for a single downstream connection

### ISSUE THREAD

**Issue by bimmlerd** [cilium/cilium#33672]
# Motivation

As part of investigating https://github.com/cilium/cilium/issues/31197, @gandro and I realized that the TCP proxying of DNS queries opens multiple TCP connections to the upstream server, one for each query by the downstream client.

[In transparent mode](https://github.com/cilium/cilium/pull/28928), this breaks in interesting ways, as trying to open multiple TCP connections using the same source port is not really a well-supported use case. (Wireshark will flag TCP traffic for reusing the local port; we've seem to have found a kernel bug related to this, ...)

Even without transparent mode, creating multiple TCP connections to upstream is inefficient. [The relevant RFC](https://datatracker.ietf.org/doc/html/rfc7766) recommends reusing connections.

## Head-of-line Blocking

While investigating the existing TCP handling loop, it became clear that the current code was suffering from head-of-line blocking. The TCP server loops reads a query from the client and synchronously executes the handler callback. In our case, this meant establishing the upstream connection, exchanging query/response, tearing it down and only then reading the next query - leading to severly degraded performance.

# Goals

- Instead of opening multiple upstream TCP connections, the DNS proxy should tie the lifecycle of it's upstream/server connection to the lifecycle of the downstream/client connection.
- Avoid Head-of-line blocking by pipelining

## Non-goals

- Change the flow of UDP DNS traffic. DNS over TCP is expected to be vastly less often used than UDP, and there's little reason to change the UDP flow. 

# Design

Currently, the DNS handling code (mostly) abstracts over whether the incoming query has reached the proxy via UDP or TCP. The code uses the DNS server provided by the `cilium/dns` (our fork of `miekg/dns`), which is structured similar to `net/http` - we only have to provde a handler, implementing `ServeDNS(w ResponseWriter, m *Msg)`. This query/response orientation leads to simple implementations in most cases, but it does not easily allow for our plans - differentiating between UDP and TCP, as well as getting the open/close signals of the TCP connection are possible (by wrapping the listeners and providing custom readers), but cumbersome.

We've thought of the following three approaches to achieve the stated goals:

1. (Least effort, most tech debt) Solve the head-of-line blocking problem by replacing the serve loop of the TCP server. The underlying code assumes to be called concurrently anyway, so in theory this should just work. The remaining problem is tying the lifecycle of the shared client to the TCP connection, which replacing the serve loop also helps with since we trivially have access to the underlying connection. Altering the shared client to only perform ref-counting for UDP seems doable, though inelegant. Threading through the close signal would muddle the request/reply abstraction somewhat. Given those two flaws, I'd argue this approach is adding tech debt. The shared client code is complex as is, differentiating between TCP/UDP (which it is supposed to abstract over) seems suboptimal.
2. (Medium effort, architecturally somewhat inelegant) Separate the control flow for TCP and UDP, by moving away from a request/reply model in the TCP case and instead act more like a TCP proxy with some added business logic. A typical TCP proxy is represented by two goroutines, writing from downstream to upstream and the reverse. In our case, we'd have these same two goroutines, and a bit of shared state (`lock.Map[DNSReqID, RequestContext]`), but the goroutines would not only copy bytes, but also handle the policy logic of the DNS proxy. The drawback is that we have to split up outgoing and incoming policy logic, which arguably makes understanding it harder. The benefit is that both problems identified are easily solved.
3. (Most effort/difficulty) Think hard and figure out a new abstraction which solves the identified issues while keeping the request/reply model in-place. It's unclear to me at the moment whether I'll succeed in finding a way to unify the differences between TCP&UDP in a way which does not give rise to new bugs, but the pay-off would be that the policy logic is not muddled.

I'm leaning towards 2, with the argument that the business logic split for outgoing/incoming traffic is a natural one, whereas the downsides of 1 and the difficulty of 3 deter me from these approaches.

**Comment by Nikhil77Sharma** [comment]
@bimmlerd  nicely captured. Yeah, Option 2 makes more sense.
