### ISSUE TITLE
cilium-dbg status: Cluster health reporting unintuitive/incorrect results

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#33697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When running `cilium-dbg status` within cilium-agent, it outputs cluster health information with a list of nodes, example output:
```
Cluster health:                            10/12 reachable   (2024-06-05T09:38:52Z)
  Name                                     IP                Node          Endpoints
  cluster-1/node-1   172.21.114.19     unreachable   unreachable
```
in this case, it actually did not show one of the unreachable nodes:
```
 cluster-2/node-2               172.22.248.182    unreachable   unreachable
```
even though by default it's supposed to show up to 10 entries and print (...) at the end to indicate partial results.

Thanks @bmcustodio for reporting.

### Cilium Version

main

### Kernel Version

N/A

### Kubernetes Version

N/A

### Regression

No

### Anything else?

cilium-dbg status is supposed to print up to 10 health lines: https://github.com/cilium/cilium/blob/5f2e61a1cce749619b15aacd957641cf10814a33/cilium-dbg/cmd/status.go#L41

https://github.com/cilium/cilium/blob/5f2e61a1cce749619b15aacd957641cf10814a33/pkg/health/client/client.go#L391C1-L402C3

we can see that actually it does not count the number of lines properly:
- it doesn't take into account if any information was printed or not - this depends on flags succinct/verbose - as in the example output, it only printed a single line even though there was a second node that was also unhealthy. 
- it does not skip counting localhost in this for loop, so localhost is counted twice, first time in https://github.com/cilium/cilium/blob/5f2e61a1cce749619b15aacd957641cf10814a33/pkg/health/client/client.go#L382C1-L385C3
and then also in the loop iterating all nodes

Also, condition for printing "(...)" is incorrect:
https://github.com/cilium/cilium/blob/5f2e61a1cce749619b15aacd957641cf10814a33/pkg/health/client/client.go#L400C1-L402C3
in the case of printing all nodes including healthy nodes, it doesn't take into account for example case, when all nodes are healthy. 
It would result in check `len(sr.Nodes)-healthy = 0 > maxLines` which would be always false.

Proposed design:
Instead of counting and trying to guess if the line was printed or not, let's add boolean returned by `formatNodeStatus` to indicate if it printed a line or not. Once we get maxLines lines printed, we stop printing any remaining lines, but still check if there are remaining nodes, that we didn't iterate over and print "(...)" at the end.
We can also refactor a bit flags of `formatNodeStatus` and get rid of `succinct` flag as it's always set to true.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by darox** [comment]
I'd like to work on this.

**Comment by marseel** [comment]
Thanks @darox

**Comment by darox** [comment]
@marseel I wanted to implement the changes but it looks like that the output of `cilium-dbg status` has already been revamped on 1.17:
```
cilium-dbg status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.30 (v1.30.0) [linux/arm64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    False
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
CNI Config file:         successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                  Ok   1.17.0-dev (v1.17.0-dev-d73443647b)
NodeMonitor:             Listening for events on 9 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 5/254 allocated from 10.244.0.0/24,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Routing:                 Network: Tunnel [vxlan]   Host: Legacy
Attach Mode:             TCX
Device Mode:             veth
Masquerading:            IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:       35/35 healthy
Proxy Status:            OK, ip 10.244.0.77, 0 redirects active on ports 10000-20000, Envoy: external
Global Identity Range:   min 256, max 65535
Hubble:                  Ok         Current/Max Flows: 4095/4095 (100.00%), Flows/s: 145.06   Metrics: Disabled
Encryption:              Disabled
Probe time:              2024-07-15T15:55:13Z
Nodes:
  kind-kind/kind-control-plane (localhost):
    Host connectivity to 172.19.0.3:
      ICMP to stack:   OK, RTT=502.908µs
      HTTP to agent:   OK, RTT=219.372µs
    Endpoint connectivity to 10.244.0.122:
      ICMP to stack:   OK, RTT=469.659µs
      HTTP to agent:   OK, RTT=1.0199ms
  kind-kind/kind-worker:
    Host connectivity to 172.19.0.2:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://172.19.0.2:4240/hello": dial tcp 172.19.0.2:4240: connect: no route to host
    Endpoint connectivity to 10.244.1.193:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.244.1.193:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Modules Health:        Stopped(0) Degraded(0) OK(42)
```

I disabled one of the nodes and as we can see it's shown under nodes.

**Comment by marseel** [comment]
@darox are you sure?
When I spin up clustermesh on the main and disable cilium-agent on one of the clusters, I get on the other one:
```
cilium-dbg status
Cluster health:                             2/4 reachable             (2024-07-17T12:45:45Z)
  Name                                      IP                        Node          Endpoints
  clustermesh1/clustermesh1-control-plane   172.19.0.3,fc00:c111::3   unreachable   unreachable
  clustermesh1/clustermesh1-worker          172.19.0.2,fc00:c111::2   unreachable   unreachable
```
or with `--verbose` output:
```
Cluster health:                                  2/4 reachable             (2024-07-17T12:45:45Z)
  Name                                           IP                        Node          Endpoints
  clustermesh2/clustermesh2-worker (localhost)   172.19.0.4,fc00:c111::4   reachable     reachable
  clustermesh1/clustermesh1-control-plane        172.19.0.3,fc00:c111::3   unreachable   unreachable
  clustermesh1/clustermesh1-worker               172.19.0.2,fc00:c111::2   unreachable   unreachable
  clustermesh2/clustermesh2-control-plane        172.19.0.5,fc00:c111::5   reachable     reachable
```

**Comment by darox** [comment]
I just pulled the last changes from `1.17.0-dev (v1.17.0-dev-7a097b5075)`

I stopped the kind-worker and it shows the following on the control-plane:

```
Cluster health:           1/2 reachable   (2024-07-17T14:30:27Z)
  Name                    IP              Node          Endpoints
  kind-kind/kind-worker   172.19.0.2      unreachable   unreachable
Modules Health:           Stopped(0) Degraded(0) OK(33)
```

Though this is for single cluster, the kind mesh setup doesn't work on my machine. 

I will continue my investigation tomorrow.

**Comment by darox** [comment]
So even with a clustermesh setup I see:
```
Cluster health:                      3/4 reachable   (2024-07-18T12:48:12Z)
  Name                               IP              Node          Endpoints
  clustermesh2/clustermesh2-worker   172.19.0.4      unreachable   unreachable
```

**Comment by darox** [comment]
I made significant progress today, but will still need some time next week, to get it finished:

```
Cluster health:                        18/32 reachable   (2024-07-19T20:13:45Z)
  clustermesh1/clustermesh1-worker10   172.19.0.14       unreachable   unreachable
  clustermesh1/clustermesh1-worker11   172.19.0.17       unreachable   unreachable
  clustermesh1/clustermesh1-worker12   172.19.0.6        unreachable   unreachable
  clustermesh1/clustermesh1-worker13   172.19.0.16       unreachable   unreachable
  clustermesh1/clustermesh1-worker14   172.19.0.3        unreachable   unreachable
  clustermesh1/clustermesh1-worker15   172.19.0.5        unreachable   unreachable
  clustermesh1/clustermesh1-worker4    172.19.0.12       unreachable   unreachable
  clustermesh1/clustermesh1-worker5    172.19.0.13       unreachable   unreachable
  clustermesh1/clustermesh1-worker6    172.19.0.15       unreachable   unreachable
  clustermesh1/clustermesh1-worker7    172.19.0.7        unreachable   unreachable
  ...
```
