### ISSUE TITLE
CFP:  Add a testing-only flag to override channel capacity

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#33720]
## Cilium Feature Proposal
        
Over time we've occasionally hit issues like https://github.com/cilium/cilium/issues/33675#issuecomment-2220511230 where channels can become full and then block a caller, and this then leads to subsequent issues. It's often the case that the defaults in Cilium provide a buffered channel in this scenario with a larger capacity, so we don't notice the potential for such issues during automated testing.

This issue proposes to modify all usage of channels in the agent to accept an override parameter for max-channel-capacity. In CI we can add extra config like this to override the max channel size to 1:

https://github.com/cilium/cilium/blob/f534200249dac2eb018ddbe3ac840a1fd1333ac2/test/helpers/kubectl.go#L126

This can force dependencies between goroutines across channels to be highlighted earlier during testing, so we catch such bugs before releasing them to the broader userbase.

**Comment by giorio94** [comment]
I wonder whether a first step couldn't be just auditing the codebase to check whether channels with large buffer capacity are actually meaningful in the given context, or should be just modified to have capacity=1 even in production environments. In most cases, unless the maximum number of elements is known a priory or used for synchronization purposes, a capacity greater than one is likely to end up being problematic as it intrinsically introduces an assumption on the limit of elements, which may not be correct in all cases. Additionally, it also has the problem of introducing intermediate buffering areas, which would for instance defeat the point of coalescencing automatically performed by working queues (e.g., by `Resource[T]`).

On a first check (imperfect, as it doesn't cover all type aliases), I could find the following occurrences:

```
$ g grep -P 'make\(.*(c|C)han[^,]*, ([^1]|[^,)][^,)]+)\)' -- ':!vendor' ':!*test*' ':!*fake*' ':!*generated*' 

daemon/cmd/endpoint.go:        epsCh := make(chan *endpoint.Endpoint, maxGoroutines)
daemon/cmd/endpoint.go:        epModelsCh := make(chan *models.Endpoint, maxGoroutines)
daemon/cmd/state.go:        epRegenerated := make(chan bool, len(state.restored))
pkg/auth/cell.go:        var signalChannel = make(chan signalAuthKey, config.MeshAuthQueueSize)
pkg/auth/spire/delegate.go:                rotatedIdentitiesChan: make(chan certs.CertificateRotationEvent, cfg.RotatedQueueSize),
pkg/bpf/events.go:                c:      make(chan *Event, eventSubChanBufferSize),
pkg/cgroups/manager/manager.go:                podEvents:                 make(chan podEvent, channelSize),
pkg/eventqueue/eventqueue.go:                events:       make(chan *Event, numBufferedEvents),
pkg/hubble/container/ring_reader.go:                        r.followChan = make(chan *v1.Event, r.followChanLen)
pkg/hubble/observer/local_observer.go:                events:           make(chan *observerTypes.MonitorEvent, opts.MonitorBuffer),
pkg/hubble/recorder/sink/sink.go:                queue:     make(chan record, queueSize),
pkg/hubble/relay/observer/observer.go:        sortedFlows := make(chan *observerpb.GetFlowsResponse, qlen)
pkg/hubble/relay/observer/observer.go:        aggregated := make(chan *observerpb.GetFlowsResponse, cap(responses))
pkg/hubble/relay/observer/server.go:        flows := make(chan *observerpb.GetFlowsResponse, qlen)
pkg/hubble/relay/observer/server.go:        statuses := make(chan *observerpb.ServerStatusResponse, len(peers))
pkg/hubble/relay/pool/manager.go:                updated:              make(chan string, 100),
pkg/identity/cache/allocator.go:                m.events = make(allocator.AllocatorEventChan, eventsQueueSize)
pkg/identity/cache/allocator.go:                events:                             make(allocator.AllocatorEventChan, eventsQueueSize),
pkg/k8s/service_cache.go:        events := make(chan ServiceEvent, option.Config.K8sServiceCacheSize)
pkg/kvstore/consul.go:                statusCheckErrors: make(chan error, 128),
pkg/kvstore/etcd.go:        errChan := make(chan error, 10)
pkg/kvstore/etcd.go:                statusCheckErrors:    make(chan error, 128),
pkg/kvstore/events.go:                Events:    make(EventChan, chanSize),
pkg/l2announcer/l2announcer.go:                leaderChannel:     make(chan leaderElectionEvent, leaderElectionBufferSize),
pkg/maps/ctmap/gc/signals.go:                signals: make(chan SignalData, 1024),
pkg/monitor/agent/listener1_2.go:                queue:     make(chan *payload.Payload, queueSize),
pkg/node/store/store.go:        registerObserver := NewRegisterObserver(n.GetKeyName(), make(chan *nodeTypes.RegisterNode, 10))
pkg/policy/groups/controllers.go:        sem := make(chan bool, maxConcurrentUpdates)
```
