### ISSUE TITLE
Trouble installing Cilium as the Primary CNI for AWS EKS Without Default Addons

### ISSUE THREAD

**Issue by A-LPHARM** [cilium/cilium#33780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.16.0-rc.1 or higher

### What happened?

I'm trying out the new feature to install the Cilium network on an EKS cluster deployment without the default addons. After creating the cluster without the nodes by running the following command, I faced issues when attempting to create a node, after setting up the cluster

### 1. Deployed eks cluster without addons

yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: henry-eks-app
  region: us-east-1

addonsConfig:
  disableDefaultAddons: true

 ### 2. Deployed cilium using helm chart via helm install  
helm install cilium cilium/cilium --version 1.15.6 \
  --namespace kube-system \
  --set eni.enabled=true \
  --set ipam.mode=eni \
  --set egressMasqueradeInterfaces=eth0 \
  --set routingMode=native

### 3.Deployed the Node group 

yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: henry-eks
  region: us-east-1

managedNodeGroups:
  - name: henry-eks-node
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true

### Cilium version

v 1.15.6

**EKSCTL Version:**
eksctl version: 0.185.0

### Kubernetes Version

$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-eks-db838b0

### Sysdump

I can't provide, since it could not run on the cluster as the Network 

### Relevant log output

```shell
Lease:
  HolderIdentity:  ip-192-168-70-103.ec2.internal
  AcquireTime:     <unset>
  RenewTime:       Fri, 12 Jul 2024 21:09:59 +0100
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason
 Message
  ----             ------  -----------------                 ------------------                ------
 -------
  MemoryPressure   False   Fri, 12 Jul 2024 21:08:37 +0100   Fri, 12 Jul 2024 20:57:51 +0100   KubeletHasSufficientMemory  
 kubelet has sufficient memory available
  DiskPressure     False   Fri, 12 Jul 2024 21:08:37 +0100   Fri, 12 Jul 2024 20:57:51 +0100   KubeletHasNoDiskPressure    
 kubelet has no disk pressure
  PIDPressure      False   Fri, 12 Jul 2024 21:08:37 +0100   Fri, 12 Jul 2024 20:57:51 +0100   KubeletHasSufficientPID     
 kubelet has sufficient PID available
  Ready            False   Fri, 12 Jul 2024 21:08:37 +0100   Fri, 12 Jul 2024 20:57:51 +0100   KubeletNotReady
 container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joelddiaz** [comment]
Not sure if this is the issue being hit here, but one thing I ran into while trying this kind of Cilium deployment was the need to set additional tolerations for the cilium-operator. Otherwise the CRDs wouldn't get installed and the nodes/node-group would never enter the Ready status.

It took something like this in the helm values.yaml file:
```
operator:
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
```

**Comment by joestringer** [comment]
> I can't provide, since it could not run on the cluster as the Network

Could you describe this in a bit more detail? I don't quite follow why the sysdump can't run. Unfortunately also without a sysdump it's hard to dig deeper into things like cilium-agent, cilium-operator logs or general cilium status to understand the state of the cluster.

I would suggest using `cilium status` at a minimum to see whether the Cilium components are reporting that they are healthy or not. Also let us know if the pointer from @joelddiaz helps, this could potentially help for future when we update the docs to use this new deployment mode.

**Comment by A-LPHARM** [comment]
> Not sure if this is the issue being hit here, but one thing I ran into while trying this kind of Cilium deployment was the need to set additional tolerations for the cilium-operator. Otherwise the CRDs wouldn't get installed and the nodes/node-group would never enter the Ready status.
> 
> It took something like this in the helm values.yaml file:
> 
> ```
> operator:
>   tolerations:
>   - effect: NoSchedule
>     key: node.kubernetes.io/not-ready
> ```

Thank you for the suggestion @joelddiaz I attempted to set the additional tolerations for the `cilium-operator` as recommended, but I still encountered issues with the node deployment.

```
helm install cilium cilium/cilium --version 1.15.6 \
> --namespace kube-system \
> --set eni.enabled=true \
> --set ipam.mode=eni \
> --set egressMasqueradeInterfaces=eth0 \
> --set routingMode=native \
> -f  ./values.yaml
```
the network plugin still refuses to get installed

```plaintext
2024-07-18 11:42:10 [ℹ]  will create a CloudFormation stack for each of 1 managed nodegroups in cluster "henry-eks-app"
2024-07-18 11:42:11 [!]  "aws-node" was not found
2024-07-18 11:42:11 [ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "henry-eks-app" } } }
2024-07-18 11:42:11 [!]  "aws-node" was not found
2024-07-18 11:42:11 [ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create managed nodegroup "henry-eks-app" } } }
2024-07-18 11:42:11 [!]  "aws-node" was not found
2024-07-18 11:42:11 [ℹ]  checking cluster stack for missing resources
2024-07-18 11:42:11 [ℹ]  checking cluster stack for missing resources
2024-07-18 11:42:12 [ℹ]  cluster stack has all required resources
2024-07-18 11:42:13 [ℹ]  building managed nodegroup stack "eksctl-henry-eks-app-nodegroup-henry-eks-app"
2024-07-18 11:42:14 [ℹ]  deploying stack "eksctl-henry-eks-app-nodegroup-henry-eks-app"
2024-07-18 11:42:14 [ℹ]  waiting for CloudFormation stack "eksctl-henry-eks-app-nodegroup-henry-eks-app"
2024-07-18 11:42:45 [ℹ]  waiting for CloudFormation stack "eksctl-henry-eks-app-nodegroup-henry-eks-app"
2024-07-18 11:43:28 [ℹ]  waiting for CloudFormation stack "eksctl-henry-eks-app-nodegroup-henry-eks-app"
2024-07-18 11:44:07 [ℹ]  waiting for CloudFormation stack "eksctl-henry-eks-app-nodegroup-henry-eks-app"
2024-07-18 11:45:27 [ℹ]  waiting for CloudFormation stack "eksctl-henry-eks-app-nodegroup-henry-eks-app"
2024-07-18 11:47:11 [ℹ]  waiting for CloudFormation stack "eksctl-henry-eks-app-nodegroup-henry-eks-app"
2024-07-18 11:47:57 [ℹ]  waiting for CloudFormation stack "eksctl-henry-eks-app-nodegroup-henry-eks-app"
```

Additionally, the `kubectl describe node` command shows:

```plaintext
kubelet has no disk pressure
PIDPressure      False   Thu, 18 Jul 2024 11:49:53 +0100   Thu, 18 Jul 2024 11:44:13 +0100   KubeletHasSufficientPID     
kubelet has sufficient PID available
Ready            False   Thu, 18 Jul 2024 11:49:53 +0100   Thu, 18 Jul 2024 11:44:13 +0100   KubeletNotReady
container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
Addresses:
  InternalIP:   192.168.72.168
  InternalDNS:  ip-192-168-72-168.ec2.internal
  Hostname:     ip-192-168-72-168.ec2.internal
```

Despite applying the suggested tolerations, the nodes failed to be deployed successfully with the `NetworkPluginNotReady` error. Could you help me with me with how the deployment was done

**Comment by squeed** [comment]
@A-LPHARM thanks for the follow-up. Could you post the output of `kubectl describe -n kube-system daemonset cilium`? Thanks! Hopefully this gets us somewhere.

**Comment by amitmavgupta** [comment]
@A-LPHARM 

- You need to be on eksctl version 0.186.0 or higher. My suggestion would be to use the latest which is 0.187.0
- You don't need to apply taints anymore.
- With no core-DNS plugin available, how are the DNS requests going to be handled?
- When you are configuring the EKS cluster minus any add-on, it thus becomes imperative that with no kube-proxy being set you will need to install Cilium with kube proxy replacement set to true.
- While installing Cilium, can you make sure you install it like this
helm install cilium cilium/cilium --version 1.15.6   --namespace kube-system   --set eni.enabled=true   --set ipam.mode=eni   --set egressMasqueradeInterfaces=eth0   --set routingMode=native --set k8sServiceHost=################################.eks.amazonaws.com --set k8sServicePort=443 --set kubeProxyReplacement=true

You can read more here if this helps- https://isovalent.com/blog/post/eks-isovalent-enterprise-for-cilium/ ( the only difference is that I am using the core-dns add-on but aws-vpc-cni and kube-proxy are not being used).

**Comment by amitmavgupta** [comment]
@A-LPHARM I re-ran your scenario without the core-dns plugin as well. 

- Created a cluster minus any add-ons
- Installed Cilium as indicated below

`helm install cilium cilium/cilium --version 1.15.6   --namespace kube-system   --set eni.enabled=true   --set ipam.mode=eni   --set egressMasqueradeInterfaces=eth0   --set routingMode=native --set k8sServiceHost=################################.eks.amazonaws.com --set k8sServicePort=443 --set kubeProxyReplacement=true`

- Created a nodegroup and the nodegroup came up fine and so did all the other pods as well.

**Comment by techthumb** [comment]
Thanks, this worked for us with version `1.15.7`.

However, it failed with `1.16.0`.

Thanks for posting this solution.

**Comment by A-LPHARM** [comment]
thanks @amitmavgupta it worked

**Comment by A-LPHARM** [comment]
thanks @amitmavgupta it worked

**Comment by techthumb** [comment]
Thanks, I am experiencing the same error. @amitmavgupta Should we re-open this ticket?

**Comment by amitmavgupta** [comment]
@techthumb @A-LPHARM, it would help if you could open a new ticket with a sysdump that can help understand what the issue is. 

Logs from the crashing pods would help as well. From the above output, I can see the envoy being used as well, so some other configuration is being tested that could have led to this issue.

**Comment by elJoeyJojo** [comment]
> thanks [@amitmavgupta](https://github.com/amitmavgupta) it worked

OK I tried to replicate what y'all did and I'm still getting the same issue. How long should this take? My nodes are still Not Ready and it's been 15 minutes and all my pods are still crashing

```
NAMESPACE     NAME                               READY   STATUS                  RESTARTS      AGE
kube-system   cilium-bfvng                       0/1     Init:CrashLoopBackOff   7 (42s ago)   11m
kube-system   cilium-operator-7d46c6f4c7-9czdv   0/1     CrashLoopBackOff        7 (22s ago)   14m
kube-system   cilium-operator-7d46c6f4c7-bnqbh   0/1     CrashLoopBackOff        7 (27s ago)   14m
kube-system   cilium-sr747                       0/1     Init:CrashLoopBackOff   7 (41s ago)   11m
kube-system   coredns-54d6f577c6-5n8xm           0/1     Pending                 0             152m
kube-system   coredns-54d6f577c6-gxnzq           0/1     Pending                 0             152m
```

My EKS Cluster Config is 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cilium
  region: us-east-1
  version: "1.29"

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true
addons:
  - name: coredns
```

Nodegroup Config

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cilium
  region: us-east-1

managedNodeGroups:
  - name: cilium
    instanceType: t3a.medium
    desiredCapacity: 2
    privateNetworking: true
```

**Comment by elJoeyJojo** [comment]
Nevermind, stupid silly mistake though I wonder how it even managed to provision pods if the _k8sServiceHost_ was not set correctly. For anyone having the same issue, DO NOT use _https://_ before the URL in the Helm command as that was my mistake 

```
--set k8sServiceHost=https://****************.gr7.us-east-1.eks.amazonaws.com
```

Once I corrected it, it started working

```
--set k8sServiceHost=****************.gr7.us-east-1.eks.amazonaws.com
```
