### ISSUE TITLE
Helm Chart extraConfig's comments generating invalid ConfigMap

### ISSUE THREAD

**Issue by alcidesmig** [cilium/cilium#33829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.16.0-rc.1 or higher

### What happened?

The `extraConfig` field description comments are incorrectly indented. When the option is used the generated ConfigMap gets invalid, causing the installation to fail.

### How it happened?

1. Install cilium with `helm install cilium cilium/cilium --version 1.15.3 --set extraConfig.enable-direct-routing="false"`

```
Error: UPGRADE FAILED: cannot patch "cilium-config" with kind ConfigMap:  "" is invalid: patch: Invalid value: ... : json: cannot unmarshal bool into Go struct field ConfigMap.data of type string
```

The generated ConfigMap, that causes the error, will be:

```
#### Source: cilium/templates/cilium-configmap.yaml
...
# Extra config allows adding arbitrary properties to the cilium config.
# By putting it at the end of the ConfigMap, it's also possible to override existing properties.

  enable-direct-routing: false
```

### Kernel Version

6.6.32-1-lts

### Kubernetes Version

Client Version: v1.30.2
Server Version: v1.28.5

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
The reason why it fails is because the `false` is being considered a boolean and not a string. You need to as such:
```
helm install cilium cilium/cilium --version 1.15.3 --set-string extraConfig.enable-direct-routing="false"
```

**Comment by alcidesmig** [comment]
> The reason why it fails is because the `false` is being considered a boolean and not a string. You need to as such:
> 
> ```
> helm install cilium cilium/cilium --version 1.15.3 --set-string extraConfig.enable-direct-routing="false"
> ```


Hey @aanm, I replied in the PR but will also do it here. I tried with the quotes and the problem continued. When I removed extraConfigs, it resolved. I believe the problem is really the unindented comments.

**Comment by aanm** [comment]
> > The reason why it fails is because the `false` is being considered a boolean and not a string. You need to as such:
> > ```
> > helm install cilium cilium/cilium --version 1.15.3 --set-string extraConfig.enable-direct-routing="false"
> > ```
> 
> Hey @aanm, I replied in the PR but will also do it here. I tried with the quotes and the problem continued. When I removed extraConfigs, it resolved. I believe the problem is really the unindented comments.

Make sure you use `--set-string` instead of `--set` as pointed out before.

**Comment by alcidesmig** [comment]
> > > The reason why it fails is because the `false` is being considered a boolean and not a string. You need to as such:
> > > ```
> > > helm install cilium cilium/cilium --version 1.15.3 --set-string extraConfig.enable-direct-routing="false"
> > > ```
> > 
> > 
> > Hey @aanm, I replied in the PR but will also do it here. I tried with the quotes and the problem continued. When I removed extraConfigs, it resolved. I believe the problem is really the unindented comments.
> 
> Make sure you use `--set-string` instead of `--set` as pointed out before.

Thanks for emphasizing --set-string, I had only tested with --set.
Actually, the quotes are passed forward only with --set-string, and it worked using it.

Thank you for your help and insistence.

Despite working, the generated ConfigMap had non-standard identation. Do you think it is worth making this change (renaming the MR)?

```
# Extra config allows adding arbitrary properties to the cilium config.
# By putting it at the end of the ConfigMap, it's also possible to override existing properties.

 enable-direct-routing: "false"
```

**Comment by joestringer** [comment]
I provided some feedback about the comment indentation in the linked PR. Let's follow up there.

Given that this issue as originally reported is resolved by using `--set-string`, I'll close this out as completed.
