### ISSUE TITLE
Documentation: Header too large for phone viewing

### ISSUE THREAD

**Issue by samip5** [cilium/cilium#33837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.16.0-rc.1 or higher

### What happened?

In the docs page, the header is too large to be able to view hamburger menu. 

### How it happened?

Use a mobile browser and go to docs. 

### Kernel Version

Not relevant

### Kubernetes Version

Not relevant

### Anything else?

![IMG_0351](https://github.com/user-attachments/assets/a69d9833-73d7-4ab9-b9b9-fb8379c1ecec)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report. Indeed the Cilium docs are not designed for mobile viewing today. We would welcome contributions to improve this.
