### ISSUE TITLE
helm upgrade failed

### ISSUE THREAD

**Issue by chenparty** [cilium/cilium#33841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

vv1.15.7 or higher

### What happened?

helm upgrade --reuse-values failed

### How it happened?

1. helm upgrade cilium cilium/cilium --namespace kube-system --reuse-values --set kubeProxyReplacement=true --set gatewayAPI.enabled=true --debug

### Kernel Version

Linux k8s-master-1 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux

### Kubernetes Version

1.30.2

### Sysdump

[cilium-sysdump-20240716-175111.zip](https://github.com/user-attachments/files/16246820/cilium-sysdump-20240716-175111.zip)

### Relevant log output

```shell
upgrade.go:158: [debug] preparing upgrade for cilium
upgrade.go:550: [debug] reusing the old release's values
Error: UPGRADE FAILED: template: cilium/templates/cilium-agent/daemonset.yaml:530:20: executing "cilium/templates/cilium-agent/daemonset.yaml" at <.Values.sysctlfix.enabled>: nil pointer evaluating interface {}.enabled
helm.go:84: [debug] template: cilium/templates/cilium-agent/daemonset.yaml:530:20: executing "cilium/templates/cilium-agent/daemonset.yaml" at <.Values.sysctlfix.enabled>: nil pointer evaluating interface {}.enabled
UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:240
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:271
runtime.goexit
        runtime/asm_amd64.s:1695
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hello, thanks for opening the GH issue, please provide steps to reproduce the issue and a cilium sysdump otherwise the issue can't be fixed. Thank you.

**Comment by chenparty** [comment]
i added "--set sysctlfix.enabled=true" ,then resolved this.

**Comment by jqueuniet** [comment]
I get a similar issue using cilium-cli with the `--reuse-values` flag.

```bash
❯ cilium upgrade --reuse-values --version v1.15.7
ℹ️  Using Cilium version 1.15.7
🔮 Auto-detected cluster name: summary-cyclone
🔮 Auto-detected kube-proxy has not been installed
ℹ️  Cilium will fully replace all functionalities of kube-proxy

Error: Unable to upgrade Cilium: template: cilium/templates/cilium-agent/daemonset.yaml:530:20: executing "cilium/templates/cilium-agent/daemonset.yaml" at <.Values.sysctlfix.enabled>: nil pointer evaluating interface {}.enabled
```

The update works if I reset the Helm values like this.

```bash
cilium upgrade --set ipam.mode=kubernetes --version v1.15.7
```

Here is the sysdump.

[cilium-sysdump-20240717-103100.zip](https://github.com/user-attachments/files/16262655/cilium-sysdump-20240717-103100.zip)
