### ISSUE TITLE
Cilium Operator stops serving IPs to new CiliumNodes

### ISSUE THREAD

**Issue by cnmcavoy** [cilium/cilium#33849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

vv1.14.13 or higher

### What happened?

The Cilium operator deployment seems to enter a deadlock or stall and stops handing out new IPs for new CiliumNodes. This manifests as nodes never becoming untainted. There are no errors or warnings in the cilium operator logs that indicate anything is wrong when this occurs. In the cilium agent logs on new nodes, the agent complains that the operator is unhealthy, but the operator is ready and healthy.

After the bug occurs, restarting the cilium operator deployment seems to resolve the deadlock and the cilium-agent on the nodes can retrieve IPs. Cilium-agent on the nodes recovers without any further intervention.

This doesn't seem to happen deterministically, but has been observed dozen times in the last week across our fleet of clusters.

Detected on both Cilium v1.15.5 and v1.15.6. Will upgrade to v1.15.7 to see if that improves things.

### How it happened?

 Cilium installed with Helm (via ArgoCD), running as a strict kube proxy replacement mode with IPAM ENI mode in AWS. 

### Kernel Version

```5.10.219-208.866.amzn2.x86_64```

### Kubernetes Version

```Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.9-eks-036c24b", GitCommit:"f75443c988661ca0a6dfa0dc01ea82dd42d31278", GitTreeState:"clean", BuildDate:"2024-04-30T23:54:04Z", GoVersion:"go1.21.9", Compiler:"gc", Platform:"linux/amd64"}```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @cnmcavoy , thanks for the report. In order to further debug this, I think we're likely to need `gops` output from the cilium-operator component while it is experiencing the issue. Unfortunately at the moment it doesn't look like this is part of the standard sysdump. I submitted a PR into cilium-cli to add that: https://github.com/cilium/cilium-cli/pull/2693 .

In the mean time though if you can reproduce this issue and report back with the gops stack output from this command, that would help a lot:

```
kubectl exec -n kube-system pod/cilium-operator-xxxxxxxxxx-xxxxx -- gops stack 1
```

**Comment by cnmcavoy** [comment]
@joestringer thanks for the quick response.

We've upgraded to Cilium v1.15.7 across all our clusters, and I also enabled the pprof endpoint on the operator (through helm values), so we can port-forward to the operator pods and capture stacktraces and maybe spot the deadlock. 

I'll also be sure to run the `gops` tool as well, sounds useful. Is it doing something similar to pprof?

**Comment by joestringer** [comment]
Yep, as I understand gops is a CLI to access pprof endpoints. Cilium ships it in most of the base images in order to ease debugging, but enabling pprof endpoints and grabbing a stack trace through there should be sufficient if this is caused by a deadlock.

**Comment by cnmcavoy** [comment]
Attached is the gops output from the cilium operator leader. I also noticed something interesting in the operator's logs:

```
time="2024-07-22T17:26:29Z" level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-03b3c98c28605d8e4 name=ip-10-127-218-131.ap-southeast-2.compute.internal subsys=ipam
```
The node name there is the name of the node that Cilium has not released any IPs to, and is still in the cluster. The CiliumNode in question:

```
apiVersion: cilium.io/v2
kind: CiliumNode
metadata:
  creationTimestamp: "2024-07-19T05:46:13Z"
  generation: 1
  labels:
    apps.indeed.com/karpenter: "true"
    apps.indeed.com/karpenter-node-pool: rad-worker-prod
    apps.indeed.com/network-zone: prod
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: c7i-flex.4xlarge
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: ap-southeast-2
    failure-domain.beta.kubernetes.io/zone: ap-southeast-2b
    k8s.io/cloud-provider-aws: df33a109c7ea743dca0a2e682a78b070
    karpenter.k8s.aws/instance-category: c
    karpenter.k8s.aws/instance-cpu: "16"
    karpenter.k8s.aws/instance-cpu-manufacturer: intel
    karpenter.k8s.aws/instance-ebs-bandwidth: "10000"
    karpenter.k8s.aws/instance-encryption-in-transit-supported: "true"
    karpenter.k8s.aws/instance-family: c7i-flex
    karpenter.k8s.aws/instance-generation: "7"
    karpenter.k8s.aws/instance-hypervisor: nitro
    karpenter.k8s.aws/instance-memory: "32768"
    karpenter.k8s.aws/instance-network-bandwidth: "3125"
    karpenter.k8s.aws/instance-size: 4xlarge
    karpenter.sh/capacity-type: on-demand
    karpenter.sh/nodepool: rad-worker-prod
    karpenter.sh/registered: "true"
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ip-10-127-218-131.ap-southeast-2.compute.internal
    kubernetes.io/os: linux
    node.indeed.com/env: prod
    node.kubernetes.io/instance-type: c7i-flex.4xlarge
    role.node.kubernetes.io/rad-worker: "true"
    role.node.kubernetes.io/worker: "true"
    topology.istio.io/subzone: awssyd2
    topology.k8s.aws/zone-id: apse2-az3
    topology.kubernetes.io/region: ap-southeast-2
    topology.kubernetes.io/zone: ap-southeast-2b
  name: ip-10-127-218-131.ap-southeast-2.compute.internal
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: ip-10-127-218-131.ap-southeast-2.compute.internal
    uid: 729de071-cf02-4c81-b8a1-4a41a8f1344a
  resourceVersion: "565033105"
  uid: 7a1a8969-5f00-42cd-b40d-363f584418f1
spec:
  addresses:
  - ip: 10.127.218.131
    type: InternalIP
  alibaba-cloud: {}
  azure: {}
  bootid: d39c0fb1-988a-46fb-a64d-460b99c8fa61
  encryption: {}
  eni:
    availability-zone: ap-southeast-2b
    disable-prefix-delegation: false
    first-interface-index: 1
    instance-type: c7i-flex.4xlarge
    node-subnet-id: subnet-0ee53e071e9a822ff
    subnet-tags:
      kubernetes.io/cluster/awssyd2: shared
      network-zone: prod
    use-primary-address: false
    vpc-id: vpc-0319e223f93afa20f
  health: {}
  ingress: {}
  instance-id: i-03b3c98c28605d8e4
  ipam:
    min-allocate: 16
    pools: {}
    pre-allocate: 8
status:
  alibaba-cloud: {}
  azure: {}
  eni:
    enis:
      eni-0219a3e2ba3458177:
        id: eni-0219a3e2ba3458177
        ip: 10.127.218.131
        mac: 06:3f:56:af:3d:71
        security-groups:
        - sg-0b3055510657cb0d7
        - sg-0313f40859fb22b3e
        - sg-036012f5c38006af1
        subnet:
          cidr: 10.127.208.0/20
          id: subnet-0ee53e071e9a822ff
        tags:
          indeed:contact: cluster-platform-team@indeed.com
          indeed:data-tier: "2"
          indeed:environment: prod
          indeed:kube_cluster_name: awssyd2
          indeed:owner: compute-cluster
          karpenter.k8s.aws/ec2nodeclass: rad-worker-prod
          karpenter.sh/managed-by: awssyd2
          karpenter.sh/nodepool: rad-worker-prod
          kubernetes.io/cluster/awssyd2: owned
        vpc:
          cidrs:
          - 10.127.0.0/16
          - 100.120.1.128/25
          id: vpc-0319e223f93afa20f
          primary-cidr: 10.124.0.0/16
  ipam:
    operator-status: {}
    ```
    [cilium-operator-5868f6c4d4-ldjgh.awssyd2.txt](https://github.com/user-attachments/files/16337733/cilium-operator-5868f6c4d4-ldjgh.awssyd2.txt)

**Comment by squeed** [comment]
@cnmcavoy thanks for the update. Just to clarify, is the sysdump from an operator experiencing this condition?

**Comment by cnmcavoy** [comment]
> @cnmcavoy thanks for the update. Just to clarify, is the sysdump from an operator experiencing this condition?

These are from the leader, the operator had 2 pods and this was the leader. After I collected all this, restarting the operator resolved the issue in the cluster.

**Comment by squeed** [comment]
@cnmcavoy perfect, makes sense. I'll pass this to those more knowledgeable about IPAM.

In the mean time, would you consider setting `debug: "true"` in the cilium-config ConfigMap and restarting the operator? That may help them diagnose this the next time it occurs. Just need to run `kubectl -n kube-system patch cm cilium-config  --patch '{ "data": { "debug": "true" }} && kubectl -n kube-system rollout restart deployment cilium-operator'

**Comment by marseel** [comment]
> These are from the leader, the operator had 2 pods and this was the leader. After I collected all this, restarting the operator resolved the issue in the cluster.

This is probably related to https://github.com/cilium/cilium/issues/28424 and https://github.com/cilium/cilium/pull/30308
Essentially, up until 1.16 operator was picking up instance types from AWS EC2 API only during startup once.  c7i-flex instance type is not in our static mappings so restarting operator helped in this case as it refetched instance types from AWS API.

**Comment by cnmcavoy** [comment]
That... tracks. We switched to Karpenter a few months ago, which does correspond to us starting to see this error more frequently. Looking forward to the 1.16 release.

**Comment by julianwiedmann** [comment]
Have you already had a chance to see whether v1.16 helps here?

**Comment by cnmcavoy** [comment]
1.16 has resolved this, we haven't seen this come up after upgrading.
