### ISSUE TITLE
clusterPoolIPv4PodCIDRList not work at 1.15.7 version 

### ISSUE THREAD

**Issue by heroes1412** [cilium/cilium#33861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

vv1.15.7 or higher

### What happened?

i completely installed rke2 cluster without cni, and manually install cilium by helmchart. 
my rke2 config.yaml (install on Ubuntu 24.04 LTS)
cluster-cidr: "192.168.0.0/16"
service-cidr: "192.169.0.0/16"
cluster-dns: "192.169.0.10"
after cluster is bootstraped, in kube-controller-manager.yaml, i saw the option "--cluster-cidr=192.168.0.0/16" in there.

helm cilium install:
helm upgrade --install cilium cilium/cilium --namespace kube-system --version 1.15.7 --set ipam.operator.clusterPoolIPv4PodCIDRList[0]=192.168.0.0/16  

i already tried:
helm upgrade --install cilium cilium/cilium --namespace kube-system --version 1.15.7 --set ipam.operator.clusterPoolIPv4PodCIDRList=192.168.0.0/16  

--set ipam.mode=cluster-pool is default, so i didnt set in helm cmd

BUT i see pods are assigned IP from 10.0.0.0/8 (default in cilium)
[cilium-sysdump-20240717-101210.zip](https://github.com/user-attachments/files/16258788/cilium-sysdump-20240717-101210.zip)

### How it happened?

pods are assigned IP from 10.0.0.0/8 (default in cilium)

### Kernel Version

Linux rke2 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.28.11+rke2r1

### Sysdump

[cilium-sysdump-20240717-101210.zip](https://github.com/user-attachments/files/16258844/cilium-sysdump-20240717-101210.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @heroes1412 , I see that you used the `helm upgrade -i ...` command, implying that there was already a Cilium environment set up before deploying Cilium with this setup. When I did the same thing in my environment, I experienced the same issue.

In order to properly change the IPAM mode, I found that I had to not only uninstall Cilium, but also delete all of the `ciliumnodes` resources in the cluster. Then I could reinstall Cilium with the new IPAM mode and Pods would be created in the new IPAM range.

**Comment by heroes1412** [comment]
Dont mind it, it is my common way to take note. Im sure our lab is clean, havent install any cni before.
Just new ubuntu 24.04 lts os, new rke2 without cni, install cilium from helm chart

**Comment by joestringer** [comment]
This works fine for me on a fresh cluster:

```
$ helm upgrade --install cilium cilium/cilium --namespace kube-system --version 1.15.7 --set ipam.operator.clusterPoolIPv4PodCIDRList=192.168.0.0/16
Release "cilium" does not exist. Installing it now.
NAME: cilium
LAST DEPLOYED: Thu Jul 18 11:24:38 2024
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.15.7.

For any further help, visit https://docs.cilium.io/en/v1.15/gettinghelp
$ kubectl create -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes-dns/dns-sw-app.yaml
pod/mediabot created
$ kubectl get pods -o wide
NAME       READY   STATUS    RESTARTS   AGE   IP              NODE          NOMINATED NODE   READINESS GATES
mediabot   1/1     Running   0          21s   192.168.0.189   kind-worker   <none>           <none>
```

**Comment by squeed** [comment]
I agree, something is very wrong here! When looking at logs from your sysdump, I see that the operator is in cluster-pool mode. I also see CiliumNode objects with IPAM allocations in 10.0.0.0/8 space.

Is there a chance that these are stale CiliumNode objects from a previous installation? It would be the simplest possible explanation.

**Comment by joestringer** [comment]
@squeed yeah, in [this comment](https://github.com/cilium/cilium/issues/33861#issuecomment-2235329594) I mentioned that I can reproduce it if there are stale CiliumNode resources in the cluster. It seems that current versions of Cilium CLI do not remove these when uninstalling, so they stick around and impact the new install of Cilium if you reinstall with different settings.
