### ISSUE TITLE
Pods get stuck in ContainerCreating if netkit mode is enabled

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#33878]
If you deploy Cilium with `bpf.datapathMode: netkit` on a kernel that doesn't support netkit (example, before Linux 6.8), then Cilium will happily start up, report no errors, but then fail to provision the network for Pods.

Expected behaviour: Cilium probes for support on startup and crashes out with a friendly message telling the user that netkit is not supported on their kernel.

**Comment by joestringer** [comment]
cc @borkmann

**Comment by borkmann** [comment]
Makes sense, I'll work on it. We probably need to extend probes first in cilium/ebpf lib.

**Comment by rgo3** [comment]
IIRC, we already have an internal netkit probe in cilium/ebpf for the `AttachNetkit` API. Maybe we can just use `AttachNetkit` for a probe in cilium, or export the c/ebpf internal feature probe.
