### ISSUE TITLE
Run LRP e2e test for per-packet LB

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#33918]
Related to PR - https://github.com/cilium/cilium/pull/33721, run the e2e test - https://github.com/cilium/cilium-cli/blob/main/connectivity/builder/local_redirect_policy.go#L43 with per-packet LB configuration. 

/cc @ysksuzuki

**Comment by pravk03** [comment]
Created https://github.com/cilium/cilium-cli/pull/2701 to add the tests.

**Comment by ysksuzuki** [comment]
https://github.com/cilium/cilium/pull/34954 has added LRP e2e test for per-packet LB
