### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by gtuminauskas** [cilium/cilium#33923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0-rc.1 and lower than v1.17.0

### What happened?

I was trying to set up Gateway api for new service, to be exposes on non-kubernetes cluster

### How can we reproduce the issue?

https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/http/#gs-gateway-http

When following documentation, deployment and service and app are using the same name, which is a bit confusing, when sonebody is using different names for each of them

### Cilium Version

1.15.7

### Kernel Version

5.14.0-427.24.1.el9_4.x86_64

### Kubernetes Version

1.30.2

### Anything else?

Documentation is a bit vague, where it is quite difficult to distinguish what names to use, even for novice user.
From kubernetes documentation: each service, deployment and app can have different names - though you are using same names.. - which makes documentation more complex and unreadable and also hard to understand and create new issues... and so on.. 
Keep the maintenance index as low as possible [so any new users can post new issues, not just senior users!!]  - keep it simple, don't make it too complex to use!

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Could you please open a PR with suggested improvements to the documentation? Thank you!
