### ISSUE TITLE
Cilium-operator-generic: "cilium-operator-generic": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by cccsss01** [cilium/cilium#33978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.16.0

### What happened?

Finding 1.15.7 cilium operator weird when pulling from a private repo
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "cilium-operator-generic": executable file not found in $PATH: unknown

I ran into a similiar issue in 1.13.x where the chart would automatically add generic at the end, does anyone have any ideas?

### How can we reproduce the issue?

pull operator image to private repo and deploy.

for 1.15.3 had to rename image to cilium-operator-generic

### Cilium Version

1.15.6 & 1.15.7

Working in 1.15.3

### Kernel Version

5.14.0-427.26.1.el9_4.x86_64

### Kubernetes Version

1.27.14

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Please provide your Helm configuration / values.yaml to see if this is reproducible with the standard Helm charts.

**Comment by cccsss01** [comment]
helm install cilium v1.15.7-cilium/  \
  --namespace kube-system                  \
  --set imagePullSecrets[0].name="pullsecret" \
  --set operator.image.repository="mylocalregistry.com/cilium-operator" \
  --set operator.image.tag="v1.15.7" \
  --set operator.image.useDigest=false \
  --set operator.image.pullPolicy="Always" 
  
  Testing 1.16.0 now

**Comment by cccsss01** [comment]
Same issue with 1.16.0

**Comment by joestringer** [comment]
I can't reproduce this locally with a similar values configuration. After some initial delay in pulling images, all Cilium Pods started successfully.

```
$ cat values.yaml 
operator:
  image:
    repository: "quay.io/cilium/operator"
  tag: "v1.15.7"
  useDigest: false
  pullPolicy: "Always"
$ cilium install --values values.yaml --version v1.16.0
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
✅ Detected kind version "0.22.0"
ℹ️  Using Cilium version 1.16.0
🔮 Auto-detected cluster name: kind-kind
🔮 Auto-detected kube-proxy has been installed
$ kubectl -n kube-system get pods -w | grep cilium
cilium-envoy-7gq2t                           0/1     ContainerCreating   0          8s
cilium-envoy-qk59f                           0/1     ContainerCreating   0          8s
cilium-operator-676d46f99b-zgdjs             0/1     ContainerCreating   0          8s
cilium-qnhxh                                 0/1     Init:0/6            0          8s
cilium-r5pf5                                 0/1     Init:0/6            0          8s
cilium-r5pf5                                 0/1     Init:0/6            0          11s
cilium-r5pf5                                 0/1     Init:1/6            0          12s
cilium-r5pf5                                 0/1     Init:2/6            0          13s
cilium-operator-676d46f99b-zgdjs             0/1     Running             0          14s
cilium-operator-676d46f99b-zgdjs             1/1     Running             0          14s
cilium-r5pf5                                 0/1     Init:3/6            0          15s
cilium-qnhxh                                 0/1     Init:1/6            0          15s
cilium-r5pf5                                 0/1     Init:4/6            0          15s
cilium-qnhxh                                 0/1     Init:2/6            0          16s
cilium-envoy-qk59f                           0/1     Running             0          16s
cilium-r5pf5                                 0/1     Init:5/6            0          17s
cilium-qnhxh                                 0/1     Init:3/6            0          17s
cilium-r5pf5                                 0/1     PodInitializing     0          18s
cilium-qnhxh                                 0/1     Init:4/6            0          18s
cilium-r5pf5                                 0/1     Running             0          19s
cilium-qnhxh                                 0/1     Init:5/6            0          19s
cilium-qnhxh                                 0/1     PodInitializing     0          20s
cilium-qnhxh                                 0/1     Running             0          21s
cilium-envoy-qk59f                           0/1     Running             0          26s
cilium-envoy-qk59f                           1/1     Running             0          26s
cilium-envoy-7gq2t                           0/1     ErrImagePull        0          26s
cilium-r5pf5                                 0/1     Running             0          27s
cilium-r5pf5                                 1/1     Running             0          27s
cilium-qnhxh                                 0/1     Running             0          29s
cilium-qnhxh                                 1/1     Running             0          29s
cilium-envoy-7gq2t                           0/1     ImagePullBackOff    0          38s
cilium-envoy-7gq2t                           0/1     Running             0          42s
cilium-envoy-7gq2t                           0/1     Running             0          46s
cilium-envoy-7gq2t                           1/1     Running             0          46s
```

Most likely the private repository is making a clone of the wrong operator images.

**Comment by cccsss01** [comment]
you've tried you own repository?  I have no issues w/ quay.io/cilium/operator

**Comment by joestringer** [comment]
I suggest double-checking how you are pushing images into your private repository, and compare those with the various flavors of operator image from the different `quay.io/cilium/operator*` repositories.

**Comment by cccsss01** [comment]
I will, i'm in the middle of eliminating the repo, and just going to do it locally w/ a different name and see where i'm at.   Having done this 200+ times we'll see.

**Comment by cccsss01** [comment]
Can no longer pull quay.io/cilium/operator have to pull quay.io/cilium/operator-generic

**Comment by febri4n** [comment]
> Can no longer pull quay.io/cilium/operator have to pull quay.io/cilium/operator-generic

Thank you, i build my own repo and use quay.io/cilium/operator have same error like you. And then use quay.io/cilium/operator-generic error solved.
