### ISSUE TITLE
CI: 

### ISSUE THREAD

**Issue by rainlay001** [cilium/cilium#33987]
## CI failure

- Set title to be in the format `CI: <test-name>`.
- Copy-paste the output the test failure.
- Upload the zip file generated from that test failure.
- Copy-paste the link of the CI build where that test failure has happen.
- Include any output from logs that you think may be relevant (to ease GitHub searches).

**Comment by tommyp1ckles** [comment]
@rainlay001 Was opening this issue intentional?

**Comment by tommyp1ckles** [comment]
Going to close for now as the description is empty, feel free to reopen later.
