### ISSUE TITLE
cilium.io/no-schedule cannot easily be used without installing via the cilium-cli

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#34003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.16.0

### What happened?

I was running a test inside of a cluster that required an external target, so I labeled a node with `cilium.io/no-schedule=true`, however, Cilium was still scheduled onto the node. When I dug into the cause, I learned that the necessary node anti-affinity rules are only applied to Cilium manifests when the `--nodes-without-cilium` flag is passed to the `install` subcommand.

### How can we reproduce the issue?

1. Create a kind cluster with a single node, labeled with `cilium.io/no-schedule=true`

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: egw-scale-test
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
nodes:
- role: worker
  labels:
    cilium.io/no-schedule: "true"
```

2. Install Cilium using the cilium-cli:

```$ cilium install```

3. Observe Cilium being installed onto the node.

### Cilium Version

```
cilium-cli: v0.16.13 compiled with go1.22.5 on linux/amd64
cilium image (default): v1.15.6
cilium image (stable): v1.15.7
cilium image (running): 1.15.5
```

### Kernel Version

Linux houston 6.9.8-zen1 #1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

### Anything else?

This is a feature of the cilium-cil, but I'm reporting this as a bug because users who install Cilium without the cilium-cli, ie purely in helm, would have to manually add the node affinities if they wanted to utilize the `cilium.io/no-schedule` label. We recently added these affinity labels to the cilium-envoy DS in commit 44aeb535b1d328734f8faac07669fbfa4683bc6f. I think it would make sense to consider adding these affinities by default to other components and removing the option from the cilium-cil. This would have the advantage of helping helm users while centralizing the implementation of the `cilium.io/no-schedule` label.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
For scalability reasons, https://github.com/cilium/cilium/issues/33462 is proposing what seems to be almost the opposite solution. cc @sypakine

**Comment by sypakine** [comment]
There are two parts, the podAffinity section and the nodeAffinity. Pod affinity will certainly run afoul of scheduler throughput. However -- based on my reading of the OSS [docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity), which specifically mentions inter-pod (anti)affinity -- I suspect that the node affinity portion will have less impact on throughput.

Let me look into how nodeAffinity would affect the scheduler.

As for the Pod affinity section, is it strictly necessary for a component?

I need to think through the state / transition matrix for components that would contain the node affinity section with and without the pod affinity section. Thinking through it quickly, the only difference I see would be that a component (e.g. cilium-envoy) may be scheduled to a Node before the cilium-agent (such as when the `cilium.io/no-schedule` was removed from a Node). With eventually-consistency, that should fine (although I lack cilium-envoy context to say definitively).

---

With the above stated (and pending Node affinity determination), would a nodeAffinity-only approach work? Another discussion is whether  a label similar to `cilium.io/no-schedule` should exist that could be set directly on the nodeSelector?

**Comment by sypakine** [comment]
As expected, `nodeAffinity` selector is not affected by the same scale limitations as inter-pod selector.
