### ISSUE TITLE
Enhancement: make ToServices selectors work for in-cluster services too / add FromServices

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#34021]
CiliumNetworkPolicy supports selecting [peers by service](https://docs.cilium.io/en/latest/security/policy/language/#services-based):

```yaml
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toServices:
    - k8sService:
        serviceName: myservice
        namespace: default
```

However, this has a significant limitation, in that it only supports selectorless services with Endpoints external to the cluster. In other words, the service acts as a sort of CIDRGroup. Internally, the policy is translated in to a ToCIDR selector with the IPs of the endpoints.

It would be nice if this limitation was relaxed. Instead, we could translate a label-selected service to its component endpointSelector. We already have most of the infrastructure for this -- the policy ingestion layer in `pkg/policy/k8s` already watches all services and already has most of the needed logic.

Additionally, toServices cannot be used with toPorts. This is an artificial limitation that should be removed.

-----

To generalize `toServices`, we need some code that:
1. Translates a `toServices` block in to *either* a set of CIDR selectors or an endpointSelector, depending on whether or not the service has a selector. The endpointSelector should be copied from the Service's selector
2. Tracks all policy to service mappings, and efficiently updates policies when services change, are created, or are deleted
3. Removes the restriction that `toServices` and `toPorts` cannot be used together.
4. (optional) adds a `fromServices` block that works the same as `toServices`

**Comment by bdecoste** [comment]
Related issue is that a CNP with toServices to a K8s Service with a selector is silently accepted by Cilium leading the user to believe the policy is valid. There is no indication in the logs that toService is invalid.

**Comment by fy-openai** [comment]
Before this is supported, maybe in short term, cilium can at least throw out a validation error in log, or maybe simply document this in a better place than comments in the source code. I tested with the default kubernetes service initially (which worked because it doesn't have a selector) and was surprised later it's actually not supported for the common case.

**Comment by fy-openai** [comment]
> Before this is supported, maybe in short term, cilium can at least throw out a validation error in log, or maybe simply document this in a better place than comments in the source code. I tested with the default kubernetes service initially (which worked because it doesn't have a selector) and was surprised later it's actually not supported for the common case.

glad to see it's documented https://docs.cilium.io/en/stable/security/policy/language/#services-based (I failed to find it)! 
@bdecoste thx for sharing
