### ISSUE TITLE
cilium 1.16 breaks pod connectivity to host docker bridge

### ISSUE THREAD

**Issue by networkhermit** [cilium/cilium#34050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

Cilium 1.16 breaks pod connectivity to host docker bridge, 1.15.7 works fine.

### How can we reproduce the issue?

1. install k3s with cilium 1.16.0 alongside some docker containers in the host

2. create a test pod to test the connectivity with the docker bridge, might be like simple ping `bridge_ip` or curl `bridge_ip:port`:
```console
$ ping 172.17.0.1
Ping 172.17.0.1 (172.17.0.1): 56(84) bytes.

--- 172.17.0.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss
```

3. check cilium monitor output:
```console
# cilium monitor -t drop -D
Listening for events on 8 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
time="2024-07-28T05:39:03Z" level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (FIB lookup failed, 4) flow 0x0 to endpoint 0, ifindex 61, file bpf_lxc.c:1325, , identity 3007->world-ipv4: 10.42.0.226 -> 172.17.0.1 EchoRequest
xx drop (FIB lookup failed, 4) flow 0x0 to endpoint 0, ifindex 61, file bpf_lxc.c:1325, , identity 3007->world-ipv4: 10.42.0.226 -> 172.17.0.1 EchoRequest
xx drop (FIB lookup failed, 4) flow 0x0 to endpoint 0, ifindex 61, file bpf_lxc.c:1325, , identity 3007->world-ipv4: 10.42.0.226 -> 172.17.0.1 EchoRequest
xx drop (FIB lookup failed, 4) flow 0x0 to endpoint 0, ifindex 61, file bpf_lxc.c:1325, , identity 3007->world-ipv4: 10.42.0.226 -> 172.24.0.1 EchoRequest
xx drop (FIB lookup failed, 4) flow 0x0 to endpoint 0, ifindex 61, file bpf_lxc.c:1325, , identity 3007->world-ipv4: 10.42.0.226 -> 172.24.0.1 EchoRequest
xx drop (FIB lookup failed, 4) flow 0x0 to endpoint 0, ifindex 61, file bpf_lxc.c:1325, , identity 3007->world-ipv4: 10.42.0.226 -> 172.24.0.1 EchoRequest
^C
Received an interrupt, disconnecting from monitor...
```

### Cilium Version

1.16.0

### Kernel Version

6.8.11

### Kubernetes Version

v1.30.2+k3s1

### Regression

1.15.7

### Sysdump

[cilium-sysdump-20240728-135349.zip](https://github.com/user-attachments/files/16402351/cilium-sysdump-20240728-135349.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
The drop is due to `BPF_FIB_LKUP_RET_NOT_FWDED`, indicating a problem in the [actual FIB lookup](https://github.com/torvalds/linux/blob/e8f897f4afef0031fe618a8e94127a0934896aba/net/core/filter.c#L5832).

Do you have a sysdump from the working setup on `v1.15.7`, so that you can compare the `Devices` output for `cilium-dbg status --verbose`? I'd wager that Cilium was attaching to a smaller number of devices, allowing us to bypass the FIB lookup.

**Comment by networkhermit** [comment]
sysdump of v1.15.7: 

[cilium-sysdump-20240806-222024.zip](https://github.com/user-attachments/files/16511636/cilium-sysdump-20240806-222024.zip)

I can't see any difference in `Devices`:

```console
❯ grep -r Devices
1.16.0.txt:  Devices:                wlan0   192.168.124.102 fe80::fd0a:6d2:d3fd:a1b8, eth0   192.168.124.118 fe80::c5c5:2cc6:1963:6c77, tailscale0    100.121.44.117 fd7a:115c:a1e0:ab12:4843:cd96:6279:2c75 fe80::9f46:adcc:aa21:2812, wg0   172.20.24.10 fd00:ebee:172:2024::10 (Direct Routing)
1.15.7.txt:  Devices:                wlan0   192.168.124.102 fe80::fd0a:6d2:d3fd:a1b8, eth0   192.168.124.118 fe80::c5c5:2cc6:1963:6c77, tailscale0    100.121.44.117 fd7a:115c:a1e0:ab12:4843:cd96:6279:2c75 fe80::9f46:adcc:aa21:2812, wg0   172.20.24.10 fd00:ebee:172:2024::10 (Direct Routing)
```

**Comment by networkhermit** [comment]
Not stale.

**Comment by julianwiedmann** [comment]
> I can't see any difference in `Devices`:

yep, that looks good. Nothing comes to mind - maybe fire up `pwru` and see whether the packet is even taking the same kernel path on v1.15 and v1.16 ?
