### ISSUE TITLE
Gateway, lbipam.cilium.io/ips and CiliumLoadBalancerIPPool issue

### ISSUE THREAD

**Issue by christiancadieux** [cilium/cilium#34099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

the CiliumLoadBalancerIPPool is only used to assign an IP to a gateway/load-balancer when the corresponding 
annotation is present "lbipam.cilium.io/ips"

### How can we reproduce the issue?

cilium 1.16

**using these single-ip pools and corresponding Gateways:**
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    tsf.io/service: service1
    tsf.io/tenant: tenant1
  name: gateway1
spec:
  gatewayClassName: cilium
  # addresses:
  # - type: IPAddress
  #   value: 10.112.182.64
  infrastructure:
    annotations:
      "lbipam.cilium.io/ips": "10.112.182.65"
    labels:
      tsf.io/service: service1
      tsf.io/tenant: tenant1
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http
    port: 8080
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    tsf.io/service: service2
    tsf.io/tenant: tenant1
  name: gateway2
spec:
  gatewayClassName: cilium
  #addresses:
  # - type: IPAddress
  #   value: 10.112.182.65
  infrastructure:
    annotations:
      #"lbipam.cilium.io/ips": "10.112.182.64"
    labels:
      tsf.io/service: service1
      tsf.io/tenant: tenant1
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http
    port: 8080
    protocol: HTTP

---
### POOLS

apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  labels:
    managed-by: rdei
    rdei.io/team: tsf-account01
    tsf.io/account: tsf-account01
    tsf.io/tenant: tenant-1
  name: pool1
spec:
  allowFirstLastIPs: "Yes"
  blocks:
  - cidr: 10.112.182.65/32
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: tenant1-ns1
      io.kubernetes.service.name: cilium-gateway-gateway1
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  labels:
    managed-by: rdei
    rdei.io/team: tsf-account01
    tsf.io/account: tsf-account01
    tsf.io/tenant: tenant-1
  name: pool2
spec:
  allowFirstLastIPs: "Yes"
  blocks:
  - cidr: 10.112.182.64/32
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: tenant1-ns1
      io.kubernetes.service.name: cilium-gateway-gateway2
---
```
**generate the correct services:**

```CiliumLoadBalancerIPPool
NAME    DISABLED   CONFLICTING   IPS AVAILABLE   AGE
pool1   false      False         0               22m
pool2   false      False         0               22m
pool1	[{"cidr":"10.112.182.65/32"}]	
pool2	[{"cidr":"10.112.182.64/32"}]	
Gateway
NAME       CLASS    ADDRESS         PROGRAMMED   AGE
gateway1   cilium   10.112.182.65   True         2s
gateway2   cilium   10.112.182.64   True         2s
Service
NAME                      TYPE           CLUSTER-IP        EXTERNAL-IP     PORT(S)         AGE
backend                   ClusterIP      192.168.213.117   <none>          3000/TCP        42d
cilium-gateway-gateway1   LoadBalancer   192.168.219.139   10.112.182.65   8080:9941/TCP   2s
cilium-gateway-gateway2   LoadBalancer   192.168.19.133    10.112.182.64   8080:9924/TCP   2s
```
**But if the annotation is missing, then cilium ignores the pool:**
```
CiliumLoadBalancerIPPool
NAME    DISABLED   CONFLICTING   IPS AVAILABLE   AGE
pool1   false      False         1               24m
pool2   false      False         1               24m
pool1	[{"cidr":"10.112.182.65/32"}]	
pool2	[{"cidr":"10.112.182.64/32"}]	
Gateway
NAME       CLASS    ADDRESS         PROGRAMMED   AGE
gateway1   cilium   10.112.182.56   True         2s
gateway2   cilium   10.112.182.51   True         2s
Service
NAME                      TYPE           CLUSTER-IP        EXTERNAL-IP     PORT(S)         AGE
backend                   ClusterIP      192.168.213.117   <none>          3000/TCP        42d
cilium-gateway-gateway1   LoadBalancer   192.168.243.109   10.112.182.56   8080:9158/TCP   2s
cilium-gateway-gateway2   LoadBalancer   192.168.149.173   10.112.182.51   8080:9536/TCP   2s
```
**addresses section of the Gateway seems to have no effect.**

The pool should match the service every time since it has the correct selector, 
and you can see that the Pool IPs available goes to zero correctly, but only when the gateway has the 
matching annotation

### Cilium Version

1.16

### Kernel Version

 v1.25.15

### Kubernetes Version

Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.15

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaunceyjiang** [comment]
> addresses section of the Gateway seems to have no effect.

Are you referring to the following? If so, this feature has not been implemented yet. See https://github.com/cilium/cilium/pull/33042 for more information.

``` yaml
spec:
  gatewayClassName: cilium
    addresses:
    - type: IPAddress
      value: 10.112.182.64
```

**Comment by christiancadieux** [comment]
that explains it. but that's the not the bug that I am describing - that was just extra information that I included in case it was relevant - but it's not.

**Comment by dylandreimerink** [comment]
Could you check the status of the services when they are not receiving an IP. Usually when this happens LB-IPAM will leave a message in the status of that service explaining what the issue is https://docs.cilium.io/en/stable/network/lb-ipam/#status

**Comment by christiancadieux** [comment]
here is the pool: 
```
NAME               DISABLED   CONFLICTING   IPS AVAILABLE   AGE
cilium-2-lb-pool   false      False         65531           120d
pool1              false      False         1               2d20h

$  get  CiliumLoadBalancerIPPool pool1 -o=yaml

apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cilium.io/v2alpha1","kind":"CiliumLoadBalancerIPPool","metadata":{"annotations":{},"labels":{"managed-by":"rdei","rdei.io/team":"tsf-account01","tsf.io/account":"tsf-account01","tsf.io/tenant":"tenant-1"},"name":"pool1"},"spec":{"allowFirstLastIPs":"Yes","blocks":[{"cidr":"10.112.182.65/32"}],"serviceSelector":{"matchLabels":{"io.kubernetes.service.name":"cilium-gateway-gateway1","io.kubernetes.service.namespace":"tenant1-ns1"}}}}
  creationTimestamp: "2024-07-31T02:21:33Z"
  generation: 5
  labels:
    managed-by: rdei
    rdei.io/team: tsf-account01
    tsf.io/account: tsf-account01
    tsf.io/tenant: tenant-1
  name: pool1
  resourceVersion: "43734702"
  uid: 226ef720-f1af-43a7-8cae-922ab66317a1
spec:
  allowFirstLastIPs: "Yes"
  blocks:
  - cidr: 10.112.182.65/32
  disabled: false
  serviceSelector:
    matchLabels:
      io.kubernetes.service.name: cilium-gateway-gateway1
      io.kubernetes.service.namespace: tenant1-eg
status:
  conditions:
  - lastTransitionTime: "2024-07-31T02:31:53Z"
    message: ""
    observedGeneration: 3
    reason: resolved
    status: "False"
    type: cilium.io/PoolConflict
  - lastTransitionTime: "2024-07-31T02:21:33Z"
    message: "1"
    observedGeneration: 5
    reason: noreason
    status: Unknown
    type: cilium.io/IPsTotal
  - lastTransitionTime: "2024-07-31T02:21:33Z"
    message: "1"
    observedGeneration: 5
    reason: noreason
    status: Unknown
    type: cilium.io/IPsAvailable
  - lastTransitionTime: "2024-07-31T02:21:33Z"
    message: "0"
    observedGeneration: 5
    reason: noreason
    status: Unknown
    type: cilium.io/IPsUsed

```
it says it will give ..182.65 to namespace tenant1-eg, service  cilium-gateway-gateway1.

I deleted the service, which is managed by a gateway and the gateway operator re-created the service with a different IP
(182.63)


```
NAME                      TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)         AGE
cilium-gateway-gateway1   LoadBalancer   192.168.153.13   10.112.182.63   8080:9529/TCP   3m8s

$ k get service cilium-gateway-gateway1 -n tenant1-eg -o=yaml

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-08-02T23:07:57Z"
  labels:
    io.cilium.gateway/owning-gateway: gateway1
    tsf.io/service: service1
    tsf.io/tenant: tenant1
  name: cilium-gateway-gateway1
  namespace: tenant1-eg
  ownerReferences:
  - apiVersion: gateway.networking.k8s.io/v1
    controller: true
    kind: Gateway
    name: gateway1
    uid: 362e2cc0-4957-462b-83a4-6678dac84006
  resourceVersion: "43734757"
  uid: 5b970fa4-f1bf-4412-8e2e-2ede820dc698
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 192.168.153.13
  clusterIPs:
  - 192.168.153.13
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-8080
    nodePort: 9529
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: LoadBalancer
status:
  conditions:
  - lastTransitionTime: "2024-08-02T23:07:57Z"
    message: ""
    reason: satisfied
    status: "True"
    type: cilium.io/IPAMRequestSatisfied
  loadBalancer:
    ingress:
    - ip: 10.112.182.63

```

**Comment by dylandreimerink** [comment]
I think I understand. LB-IPAM as it stands today doesn't do explicit ordering on which pools it allocates IPs from. It internally maintains a list of all pools it know about, ordering isn't guaranteed, lets say its random. Whenever it needs to assign an IP it will loop over all pools, and the first pool it finds that is allowed to give an IP based on the selectors will be used. So a pool without selector is just as likely to be used as a pool with one.

From what I understand, you expect the pool without selector to be used only when there is no other option correct?

**Comment by christiancadieux** [comment]
right.
the selectors 'io.kubernetes.service.namespace|name' allows to pick a specific service .
randomly select an IP using the 'default' pool makes these very narrow selectors not very useful.
need to order the pools from most to least specific , or from smallest to largest pool (easier to do).

**Comment by dylandreimerink** [comment]
> he selectors 'io.kubernetes.service.namespace|name' allows to pick a specific service .
randomly select an IP using the 'default' pool makes these very narrow selectors not very useful.
need to order the pools from most to least specific , or from smallest to largest pool (easier to implement).

I do think that a mechanism for ordering would be a neat feature to have. Though I do think we should make this an explicit mechanism, since going from most specific to least specific or smallest to largest might not always be what a user wants. We should give the exact design some thought. MetalLB the closest thing has priority numbers on pools for ordering but also an annotation which allows services to request from a specific pool for example.

> so the control-plane can create a pool for a service and guarantee that when that service is created by the tenant, a specfic IP will be allocated. Not sure what happens when a pool is created for a service and the service also mentions the "lbipam.cilium.io/ips" - but the pool should win (I can test that also).

Whatever ordering mechanism we end up with, it shouldn't interfere with the `lbipam.cilium.io/ips` annotation, that would be very messy. Pool selectors are leading for determining which pools a service can use.

The ordering will most likely be best effort. It would be challenging and high churn to for example reassign IPs whenever the priorities of pools change or a new high priority pool is added. Ordering would likely only apply when an allocation is made such as for new services or changes to selectors which forces a service to re-allocate.

**Comment by christiancadieux** [comment]
explicit ordering would work .
I assumed that since it was possible to use very narrow selector like ' io.kubernetes.service.namespace|name', there was some kind of hierarchy being used.
otherwise, If I needed a pool for a specific 'namespace-a', and there is no hierarchy, then I would need a second pool for 'all namespaces except namespace-a' - but I don't know if   the pool selector syntax allows for that.
doe the pool selector syntax allow for this syntax - https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

```
selector:
  matchLabels:
    component: redis
  matchExpressions:
    - { key: tier, operator: In, values: [cache] }
    - { key: environment, operator: NotIn, values: [dev] }
```
