### ISSUE TITLE
option api-rate-limit: invalid character 'e' looking for beginning of value

### ISSUE THREAD

**Issue by adamw-linadm** [cilium/cilium#34129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

I wanted to check the installation of version 1.16.0 using helm. I ran the command:
```
helm install cilium cilium/cilium --version 1.16.0 --namespace kube-system --set ipam.mode=kubernetes --set ipam.operator.clusterPoolIPv4PodCIDR=172.0.0.0 --set hubble.enable=true --set hubble.relay.enabled=true --set hubble.ui.enabled=true --set bpf.policyMapMax=65536 --set prometheus.enabled=true --set operator.prometheus.enabled=true --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" --set dnsProxy.endpointMaxIpPerHostname=300 --set kubeProxyReplacement=true --set envoy.enabled=false --set k8sServicePort=6443 --set k8sServiceHost=k8s.endpoint.dot --set apiRateLimit="endpoint-create=rate-limit:100/s\,rate-burst:300\,max-wait-duration:60s\,parallel-requests:300\,log:true"
```
And Cilium pods started to CrashLoopBackOff with error in logs:
```
 cilium-agent time="2024-08-01T11:47:42Z" level=fatal msg="Incorrect config-map flag value" error="option api-rate-limit: invalid character 'e' looking for beginning of value" subsys=config
 ```
 Above helm command worked in version 1.15.x:
 ```
 kubectl -n kube-system exec ds/cilium -- cat /tmp/cilium/config-map/api-rate-limit
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
endpoint-create=rate-limit:100/s,rate-burst:300,max-wait-duration:60s,parallel-requests:300,log:true
```
I didn't see anything in the changelog that could change the behavior.

### How can we reproduce the issue?

Helm install with option:
```
--set apiRateLimit="endpoint-create=rate-limit:100/s\,rate-burst:300\,max-wait-duration:60s\,parallel-requests:300\,log:true"
```

### Cilium Version

1.16.0

### Kernel Version

4.18.0-553.8.1.el8_10.x86_64

### Kubernetes Version

1.29.6

### Regression

1.15.7

### Relevant log output

```shell
cilium-agent time="2024-08-01T11:50:56Z" level=fatal msg="Incorrect config-map flag value" error="option api-rate-limit: invalid character 'e' looking for beginning of value" subsys=config
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Thank you for opening this GH issue, this is a regression caused by https://github.com/cilium/cilium/pull/33779

**Comment by jrajahalme** [comment]
The commit causing the regression has now been reverted from v1.15 (https://github.com/cilium/cilium/pull/34306) and from v1.16 (https://github.com/cilium/cilium/pull/34305)
