### ISSUE TITLE
Update 'twitter.com' links to 'x.com' links in Documentations.

### ISSUE THREAD

**Issue by BishalJena** [cilium/cilium#34138]
One of many example: 
![image](https://github.com/user-attachments/assets/3b18c7b5-1384-4539-b5fe-6b9819d81c64)

**Comment by BishalJena** [comment]
I'm working on this, should be a quick fix.

**Comment by BishalJena** [comment]
can any maintainer kindly tag this issue, so i can raise PR to fix this issue!

**Comment by sayboras** [comment]
As per https://github.com/cilium/cilium/pull/34149#issuecomment-2265662344, closing this issue, feel free to re-open if  there is any other reference  of twitter in Cilium owned file. Thanks.
