### ISSUE TITLE
Helm chart fails to apply on Kubernetes <1.30 if hubble.tls.auto.method=cronJob

### ISSUE THREAD

**Issue by stygian-coffee** [cilium/cilium#34145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

If applying the Cilium Helm chart to a Kubernetes cluster with Kubernetes version <1.30 with `hubble.tls.auto.method=cronJob` then the Hubble TLS CronJob contains an AppArmor profile. Hence the apply fails since `securityContext.appArmorProfile` is not supported before Kubernetes 1.30.

### How can we reproduce the issue?

1. `helm repo add` the Cilium repo.
2. `helm repo update` to ensure the latest version (currently 1.16.0) is available.
3. Run `helm template cilium/cilium --kube-version=1.29.0 --namespace=kube-system --set hubble.tls.auto.method=cronJob`.

Observe the following:
```
$ helm template cilium/cilium --kube-version=1.29.0 --namespace=kube-system --set hubble.tls.auto.method=cronJob | grep appArmor
            appArmorProfile:
        appArmorProfile:
```

This is related to this line of code: https://github.com/cilium/cilium/blob/badf9252c8f7cbeca14383ef43e1b6c8964c4864/install/kubernetes/cilium/templates/hubble/tls-cronjob/_job-spec.tpl#L13. Namely, I believe that `<1.30.0` should be replaced with `>=1.30.0`.

### Cilium Version

N/A

### Kernel Version

N/A

### Kubernetes Version

```
$ kubectl version
Client Version: v1.29.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6
```

### Regression

1.15.7

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rolinh** [comment]
Thanks for the report. This issue will be fixed once #34100 is merged.
