### ISSUE TITLE
CFP: support network programming latency SLI

### ISSUE THREAD

**Issue by weiwei02** [cilium/cilium#34147]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**
---
Our business scenarios have strict requirements on the unavailable time during instance changes. Therefore, when the workload changes, we expect the old Pods to be removed from the Endpoint as soon as possible, and the new ready Pods to be added to the Endpoint in a short time and accessible by all nodes.

The time duration from the start of our workload changes until it affects the packet forwarding rules (such as eBPF) of each node is called 'network programming latency'. In Cilium, this network programming latency is invisible.

**Describe the feature you'd like**
It is strongly hoped that Cilium can achieve metrics for network programming latency like kube-proxy. This SLI is a proposal from sig-scalability [network_programming_latency](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/network_programming_latency.md).
As described in the document, the measurement method for network programming latency is as follows:
> 1. We assume that for the in-cluster load-balancing programming we are using Kubernetes Endpoints objects.
> 2. We will introduce a dedicated annotation for Endpoints object (name TBD).
> 3. Endpoints controller (while updating a given Endpoints object) will be setting value of that annotation to the timestamp of the change that triggered this update:
> * for pod transition between Ready and NotReady states, its timestamp is simply part of pod condition
> * TBD for service updates (ideally we will add LastUpdateTimestamp field in object metadata next to already existing CreationTimestamp. The data is already present at storage layer, so it won't be hard to propagate that.

**How to implement**
---
As well-know k8s has already implemented metrics for network programming latency SLI:

* kube-controller-manager watch the status of pods and services, and adds the `endpoints.kubernetes.io/last-change-trigger-time` annotation for Endpoint/EndpointSlice and service. This represents the timestamp of the last change of a Pod or Service object that triggered the change of the endpoint object (stored as an RFC 3339 format date-time string, e.g., `2018-10-22T19:32:52.1Z`).
* It is expected that after implement network programming on Cilium to record the network programming latency using the time marked by this annotation as the start time.
 
Since the programming of Cilium’s eBPF map update rules is asynchronous from the processing of Endpoint time in terms of code implementation, directly modifying Cilium may have a significant impact on the existing code structure. It is suggested that Cilium can implement network programming latency SLI in multiple stages, such as:
1. first implementing in-cluster service load, 
2.  then implementing programming latency related to network policies.

**Comment by ovidiutirla** [comment]
Hey,
Have a look over https://github.com/cilium/cilium/pull/32055

**Comment by weiwei02** [comment]
> Hey, Have a look over #32055
@ovidiutirla 

Thank you very much for your reply., but #32055  PR does not fully implement the network programming latency scenario described in the [network_programming_latency](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/network_programming_latency.md).

* #32055 only measures the time consumed by processing service events in Cilium.
* The [network_programming_latency](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/network_programming_latency.md) requires measuring the total time from when a pod’s status becomes ready to when the network programming on a single machine is completed. This is a total time span that involves multiple components such as `kube-controller-manager` and `Cilium`.
