### ISSUE TITLE
Cilium 1.16.x loses outgoing packets for the lbipam LoadBalancer service

### ISSUE THREAD

**Issue by prehor** [cilium/cilium#34162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

After upgrade from 1.15.7 to 1.16.0, cilium start to loose outgoing packets for k8s-gateway lbipam LoadBalancer service.

Host is Debian 12, network interface `lan` is a bridge.

I checked (see attached log outputs, DNS domain changed to example.com):
- L2 Announcement of IP address - OK
- Incoming packets arrives to node interface - OK
- Cilium handle incoming packets - OK
- Incoming packets arrives to pod interface - OK
- K8S-Gateway get DNS requests and send DNS responses - OK
- Outgoing packets arrives to pod interface - OK
- Cilium handle outgoing packets - OK
- Outgoing packets NEVER arrives to host interface - PACKETS ARE LOST

Cilium does not drop the outgoing packets (checked with `cilium monitor --type drop`) but packets does not arrive to host interface.

I have two Kubernetes clusters and cilium 1.16.0 behaves the same on both.

I'm using multus togheter with cilium. I tested this bug with and without multus and cilium behaves the same on both.

### How can we reproduce the issue?

- [Cilium Helm Chart with Values](https://github.com/prehor/home-ops/blob/main/kubernetes/storage/apps/kube-system/cilium/app/helmrelease.yaml) (now reverted back to 1.15.7)
- [Cilium Config Maps](https://github.com/prehor/home-ops/blob/main/kubernetes/storage/apps/kube-system/cilium/config/cilium-l2.yaml)
- [K8S-Gateway Helm Chart with Values](https://github.com/prehor/home-ops/blob/main/kubernetes/storage/apps/network/k8s-gateway/app/helmrelease.yaml)

### Cilium Version

1.16.0

### Kernel Version

Linux h1 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.30.2+k3s2

### Regression

1.15.7

### Sysdump

[cilium-sysdump-20240804-184144.zip](https://github.com/user-attachments/files/16488291/cilium-sysdump-20240804-184144.zip)

### Relevant log output

```shell
root@h1:~# hubble observe --since 1s --pod network/k8s-gateway-5864fb4465-w8twj
Aug  4 12:58:58.339: 192.168.1.43:41698 (world) -> network/k8s-gateway-5864fb4465-w8twj:1053 (ID:68187) to-endpoint FORWARDED (UDP)
Aug  4 12:58:58.339: 192.168.1.43:41698 (world) <> network/k8s-gateway-5864fb4465-w8twj (ID:68187) pre-xlate-rev TRACED (UDP)
Aug  4 12:58:58.340: 192.168.1.43:41698 (world) <- network/k8s-gateway-5864fb4465-w8twj:1053 (ID:68187) to-stack FORWARDED (UDP)
Aug  4 12:58:58.341: 192.168.1.43:51645 (world) -> network/k8s-gateway-5864fb4465-w8twj:1053 (ID:68187) to-endpoint FORWARDED (UDP)
Aug  4 12:58:58.341: 192.168.1.43:51645 (world) <> network/k8s-gateway-5864fb4465-w8twj (ID:68187) pre-xlate-rev TRACED (UDP)
Aug  4 12:58:58.341: 192.168.1.43:51645 (world) <- network/k8s-gateway-5864fb4465-w8twj:1053 (ID:68187) to-stack FORWARDED (UDP)

root@h1:~# cilium-dbg monitor --related-to 1037
Listening for events on 8 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
time="2024-08-04T15:55:55Z" level=info msg="Initializing dissection cache..." subsys=monitor
-> endpoint 1037 flow 0xb75c3c5b , identity world->68187 state new ifindex lxce3e3ac922558 orig-ip 192.168.1.41: 192.168.1.41:49089 -> 10.10.0.29:1053 udp
-> stack flow 0xe1eace6d , identity 68187->119669 state established ifindex 0 orig-ip 0.0.0.0: 10.10.0.29:53712 -> 10.10.0.148:53 udp
-> endpoint 1037 flow 0x0 , identity 119669->68187 state reply ifindex lxce3e3ac922558 orig-ip 10.10.0.148: 10.10.0.148:53 -> 10.10.0.29:53712 udp
-> stack flow 0x0 , identity 68187->world state reply ifindex 0 orig-ip 0.0.0.0: 10.10.0.29:1053 -> 192.168.1.41:49089 udp

root@h1:~# tshark -i lxce3e3ac922558
Running as user "root" and group "root". This could be dangerous.
Capturing on 'lxce3e3ac922558'
 ** (tshark:12303) 15:06:10.213716 [Main MESSAGE] -- Capture started.
 ** (tshark:12303) 15:06:10.213954 [Main MESSAGE] -- File: "/tmp/wireshark_lxce3e3ac92255872TUR2.pcapng"
    1 0.000000000 192.168.1.43 → 10.10.0.95   DNS 86 Standard query 0x2481 A flux-webhook.storage.example.com
    2 0.000488014   10.10.0.95 → 192.168.1.43 DNS 128 Standard query response 0x2481 A flux-webhook.storage.example.com A 192.168.1.17

root@h1:~# tshark -i lan udp port 53
Running as user "root" and group "root". This could be dangerous.
Capturing on 'lan'
 ** (tshark:12563) 15:08:47.458703 [Main MESSAGE] -- Capture started.
 ** (tshark:12563) 15:08:47.458919 [Main MESSAGE] -- File: "/tmp/wireshark_lan1VZQR2.pcapng"
    1 0.000000000 192.168.1.42 → 192.168.1.19 DNS 86 Standard query 0x49ab A flux-webhook.storage.example.com
    2 0.000908983 192.168.1.41 → 192.168.1.19 DNS 86 Standard query 0xbe7b A flux-webhook.storage.example.com
    3 0.001404371 192.168.1.42 → 192.168.1.19 DNS 86 Standard query 0xdc5e AAAA flux-webhook.storage.example.com
    4 0.001945286 192.168.1.42 → 192.168.1.19 DNS 86 Standard query 0x5d14 AAAA flux-webhook.storage.example.com
    5 0.003560785 192.168.1.42 → 192.168.1.19 DNS 86 Standard query 0x02cd A flux-webhook.storage.example.com
    6 0.005669545 192.168.1.42 → 192.168.1.19 DNS 86 Standard query 0x4de8 AAAA flux-webhook.storage.example.com
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
Looking at the sysdump, the `k8s-gateway` is still assigned IP `192.168.1.19`, so it doesn't seem like LB-IPAM withdrew the IP or anything of the sort. So it seems we can rule it out.

**Comment by prehor** [comment]
I upgraded k3s to v1.31.0+k3s1 and tried to upgrade Cilium to 1.16.1. The behavior is the same as with Cilium 1.16.0 - K8S-Gateway does not respond to DNS requests. After downgrading back to Cilium 1.15.7, K8S-Gateway responds to DNS requests.

**Comment by julianwiedmann** [comment]
Tracing down the missing packets seems like a good case for https://github.com/cilium/pwru

**Comment by prehor** [comment]
Thanks. I will try it tomorrow.
