### ISSUE TITLE
Consider table-driven tests for policy

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3417]
http://onsi.github.io/ginkgo/#extensions

It's difficult to assess the state of policy testing of various combinations of policies, direction, in-cluster/out-cluster, etc. It might be easier to build a giant table of all expected policy combinations using something like the table tests in the above link and run the tests via this kind of model. Or even we may consider a few smaller tables which cover different verticals such as ingress L3, egress L3, ingress L4, egress L4, ingress L7, egress L7, then a few that combine these categories.

**Comment by eloycoto** [comment]
This are the nightly test no? Helpers/policygen/policygen.go cover this

**Comment by joestringer** [comment]
@eloycoto ah, this looks like the kind of thing I was thinking about. What's the intention behind the split between the aforementioned policygen policy checks vs. something like the `test/runtime/Policies.go` tests? Is there any target we can use to just run like `test-policies-please` or do we have to use the nightlies request?

**Comment by joestringer** [comment]
Offline discussion today resulted in the following suggestions:
* [ ] There should be a `test-policies-please` target for PRs touching policy
* [ ] Basic policy stuff should be tested on all PRs
* [ ] Longer-running, larger scale policy tests should be run in nightlies.
