### ISSUE TITLE
Remove extraneous `waitEndpointsReady()` calls after `PolicyRenderAndImport()`

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3419]
Usage of `PolicyRenderAndImport()` is inconsistent and error-prone. Examples:

https://github.com/cilium/cilium/blob/82fbce193a79eea9c82e7a4f57de24375b5423e1/test/runtime/Policies.go#L716-L720

https://github.com/cilium/cilium/blob/82fbce193a79eea9c82e7a4f57de24375b5423e1/test/runtime/Policies.go#L984-L991

IMHO we should have something more like:

```
vm.ExpectSuccessfulPolicyImport(policy)
```

This would render the policy to a file, import it, ensure that everything succeeds, and wait for endpoints to be ready. Any failure would be consistently handled and we can improve the output upon failure.

If there are cases where we need to check failure to import policy can either open code as it does today, or we could introduce a `vm.ExpectPolicyImportFailure()` or similar.

**Comment by eloycoto** [comment]
Hi @joestringer  ATM `PolicyRenderAndImport` already wait until endpoints are ready. 

Regards

**Comment by joestringer** [comment]
Perfect, then we can remove the `areEndpointsReady()` calls from those tests.
