### ISSUE TITLE
Egress Gateway does not work if Egress Interface is a VLAN interface

### ISSUE THREAD

**Issue by henry-spanka** [cilium/cilium#34217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.16.0

### What happened?

Since v1.15.6 Egress Gateway does not work anymore if the Egress GW interface is a VLAN interface in the format `ens2f0np0.201`

It seems this issue was introduced by commit https://github.com/cilium/cilium/commit/56e5133ccddafa48ebcef5fb7ff7da33f7ea9148

The "." in the interface name is interpreted by sysctl as another "directory" in the /proc/sys/net path. This results in the sysctl value `net.ipv4.conf.ens2f0np0.201.rp_filter`. As a result it tries to write to `/proc/sys/net/ipv4/conf/ens2f0np0/201/rp_filter`

### How can we reproduce the issue?

1. Install Cilium >= v1.15.6
2. Create CiliumEgressGatewayPolicy for pod

### Cilium Version

v1.15.6 to v1.16.0 (latest)

### Kernel Version

6.9.5-zabbly+ #debian12 SMP PREEMPT_DYNAMIC Mon Jun 17 04:03:53 UTC 2024 x86_64 GNU/Linux

### Kubernetes Version

v.1.29.5

### Regression

This worked in v1.15.5 or below.

### Relevant log output

```shell
FAIL queued &{net.ipv4.conf.ens2f0np0.201.rp_filter 2 false  Pending (1.4s ago)} for retry due to could not open the sysctl file /proc/sys/net/ipv4/conf/ens2f0np0/201/rp_filter: open /proc/sys/net/ipv4/conf/ens2f0np0/201/rp_filter: no such file or directory ! revision not equal
FAIL queued &{net.ipv4.conf.ens2f0np0.201.rp_filter 2 false  Pending (1.4s ago)} for retry due to could not open the sysctl file /proc/sys/net/ipv4/conf/ens2f0np0/201/rp_filter: open /proc/sys/net/ipv4/conf/ens2f0np0/201/rp_filter: no such file or directory ! revision not equal
```

### Anything else?

Workaround is to change interface name to a name without a dot (".") inside, e.g.
```shell
ip link add link ens2f0np0 name vlan201 type vlan id 201
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by haribhusal2025** [comment]
We have v1.15.7 Cilium running on ops cluster and egressgateway is on VLAN interface with name bond.xxx270 and it is working fine. I was going to upgrade to 1.16.0 and see if any issues.
