### ISSUE TITLE
BUG: With ebpf host routing and masquerading enabled container interfaces doesn't update receive counters

### ISSUE THREAD

**Issue by AlexMaksimkin** [cilium/cilium#34245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.16.0

### What happened?

After migrating from Hybrid routing mode (no ebpf, but without kubeproxy) into full ebpf (host routing with enabled ebpf masquerading) we discovered that CAdvisor `container_network_receive_bytes_total` metric stopped to be updated, showing no incoming traffic to container (while it definitely should be there).

Cadvisor using counters coming from `/proc/<pid>/net/dev` where pid - is a pid of container process, so after checking this counters it clearly show that received counter aren't updated at different timestamps (example below).

```
bash-5.1# cat /proc/5312/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0:    1437      16    0    0    0     0          0         0 265617752  269586    0    0    0     0       0          0
bash-5.1# cat /proc/5312/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0:    1437      16    0    0    0     0          0         0 265676096  269936    0    0    0     0       0          0
bash-5.1# cat /proc/5312/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0:    1437      16    0    0    0     0          0         0 265723510  270208    0    0    0     0       0          0
bash-5.1# cat /proc/5312/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0:    1437      16    0    0    0     0          0         0 265734092  270269    0    0    0     0       0          0
bash-5.1# cat /proc/5312/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0:    1437      16    0    0    0     0          0         0 265741762  270315    0    0    0     0       0          0
bash-5.1# cat /proc/5312/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0:    1437      16    0    0    0     0          0         0 265747890  270356    0    0    0     0       0          0
bash-5.1# cat /proc/5312/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0:    1437      16    0    0    0     0          0         0 265757114  270403    0    0    0     0       0          0
bash-5.1# cat /proc/5312/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0:    1437      16    0    0    0     0          0         0 265773988  270497    0    0    0     0       0          0
```
This container handling bidirectional data processing, so it should have both counters updated at roughly similar rates.
When we disabling ebpf and rolling back into hybrid routing mode - counters starting to work as expected.

I suppose that enabling ebpf changing datapath in the kernel level, but it should still update vif counters as expected.

### How can we reproduce the issue?

Cilium v1.15.6 with helm values:
bpf:
    masquerade: true
egressMasqueradeInterfaces: "

Cadvisor built-in into kubelet (kubernetes 1.29 / cadvisor v0.48.1)

### Cilium Version

v1.15.6

### Kernel Version

Linux 5.10.215-203.850.amzn2.x86_64

### Kubernetes Version

1.29+ (v1.29.13-eks-3af4770) [linux/amd64]

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
I suspect this is a dup of https://github.com/cilium/cilium/issues/30566, can you please have a look there? Thank you!
