### ISSUE TITLE
Disable virtual address space randomization for vbox

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3425]
Disable randomization of virtual address space in order to simplify debugging of backtraces:

```
echo 0 > /proc/sys/kernel/randomize_va_space
```

**Comment by tgraf** [comment]
cc @jrajahalme

**Comment by ianvernon** [comment]
Closing due to https://github.com/cilium/packer-ci-build/pull/44 being merged.

**Comment by eloycoto** [comment]
Related to https://github.com/cilium/cilium/pull/3354

Vagrant box is still not updated in the project

**Comment by eloycoto** [comment]
Vagrant box is already updated. Close this one.
