### ISSUE TITLE
Gateway API SupportedFeatures API change

### ISSUE THREAD

**Issue by LiorLieberman** [cilium/cilium#34266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

https://github.com/kubernetes-sigs/gateway-api/pull/3200 introduced a breaking change to SupportedFeatures experimental API. 

https://github.com/cilium/cilium/blob/69a626c336098dd7ced33994680aad4cdc7426ea/operator/pkg/gateway-api/gatewayclass_reconcile.go#L47-L66 has to be changed.

I believe it will broke the controller otherwise. 

/cc @youngnick 

### How can we reproduce the issue?

N/A

### Cilium Version

N/A

### Kernel Version

N/A

### Kubernetes Version

Gateway API prospective version 1.2

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Thank you! Looks like https://github.com/cilium/cilium/pull/34262 just [tripped](https://github.com/cilium/cilium/actions/runs/10315963481/job/28557196549?pr=34262) over this as well :)

**Comment by LiorLieberman** [comment]
I will open a PR to fix it now, trying to understand what are the supported features. 

https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-gateway-api.yaml#L268-L271 shows `all-features` with a few exempt features, however `--conformance-profiles` are also provided, so I am a bit confused

**Comment by LiorLieberman** [comment]
Though I think all profiles are provided, so I think this flag is essentially redundant

**Comment by sayboras** [comment]
> https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-gateway-api.yaml#L268-L271 shows all-features with a few exempt features, however --conformance-profiles are also provided, so I am a bit confused

:wave:

Thanks for your question, it was a workaround to make sure that the report is showing extended features,  the diff can be found in the below upstream PR. 

Honestly, I think that there is some corner case in upstream profile test, but I didn't have time to look deeper.

Cilium PR: https://github.com/cilium/cilium/pull/34098
Upstream PR: https://github.com/kubernetes-sigs/gateway-api/pull/3242
