### ISSUE TITLE
invalid sysctl parameter for Interfaces with uppercase chars 

### ISSUE THREAD

**Issue by lukasmrtvy** [cilium/cilium#34287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.16.0

### What happened?

Cillium does not respect interface names with upper char, resulting in:

```
time="2024-07-19T00:28:18Z" level=fatal msg="failed to start: daemon creation failed: error while initializing daemon: failed while reinitializing datapath: Failed to sysctl -w net.ipv4.conf.enX0.rp_filter=2: invalid sysctl parameter: \"net.ipv4.conf.enX0.rp_filter\"" 
```

- Setting manually ` sysctl -w net.ipv4.conf.enX0.rp_filter=2` works OK ( Agen will still try to set value )
- Renaming interface from `enX0` to `enx0` works OK

### How can we reproduce the issue?

1. Create instance with an interface name containing upper char, for example, `enP2p4s0`, which is the default for some AWS instance types
2. Install Cillium
3. Wait for Agent fail

### Cilium Version

1.15.7

### Kernel Version

6.8.0-1012-aws

### Kubernetes Version

1.29.7

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
thanks for reporting! Something like https://github.com/cilium/cilium/pull/34298 should do the trick, in case you want to give it a spin.
