### ISSUE TITLE
Cilium Helm - Hubble Exporter Allow List Flag

### ISSUE THREAD

**Issue by berke581** [cilium/cilium#34308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

I am following the documentation on adding filters to my Hubble export config.
https://docs.cilium.io/en/latest/observability/hubble-exporter/#filters

While attempting to install via Helm and set the value flag using the following command:
```
helm upgrade cilium ./cilium \
   --set hubble.enabled=true \
   --set hubble.export.static.enabled=true \
   --set hubble.export.static.allowList[0]='{"verdict":["DROPPED"]}'
```
I'm encountering errors. When I check the pod logs, I see that the issue is related to the cilium-config ConfigMap. Here’s the relevant section of the ConfigMap when I run the `helm upgrade`:
`hubble-export-allowlist: '[verdict:[DROPPED]]'`
The error message in the pods is:
`level=fatal msg="failed to decode hubble-export-allowlist '[verdict:[DROPPED]]': invalid character 'v' looking for beginning of value" subsys=config`

However, when I manually configure the ConfigMap, the following version works without issues:
`hubble-export-allowlist: '{"verdict":["DROPPED"]}'`

Thanks in advance for your assistance!

### How can we reproduce the issue?

1. Install Cilium With Helm and Enable Hubble Export with Necessary Flags
```
helm upgrade cilium ./cilium \
   --set hubble.enabled=true \
   --set hubble.export.static.enabled=true \
   --set hubble.export.static.allowList[0]='{"verdict":["DROPPED"]}'
```
2. Check the cilium-config ConfigMap to see `hubble-export-allowlist` under `data`
3. Additionally check the pod logs to see the fatal error

### Cilium Version

1.16.0

### Kernel Version

5.15.153.1-microsoft-standard-WSL2

### Kubernetes Version

v1.30.0

### Relevant log output

```shell
time="2024-08-12T12:09:42Z" level=info msg="Memory available for map entries (0.003% of 16654721024B): 41636802B" subsys=config
time="2024-08-12T12:09:42Z" level=info msg="option bpf-ct-global-tcp-max set by dynamic sizing to 146094" subsys=config
time="2024-08-12T12:09:42Z" level=info msg="option bpf-ct-global-any-max set by dynamic sizing to 73047" subsys=config
time="2024-08-12T12:09:42Z" level=info msg="option bpf-nat-global-max set by dynamic sizing to 146094" subsys=config
time="2024-08-12T12:09:42Z" level=info msg="option bpf-neigh-global-max set by dynamic sizing to 146094" subsys=config
time="2024-08-12T12:09:42Z" level=info msg="option bpf-sock-rev-map-max set by dynamic sizing to 73047" subsys=config
time="2024-08-12T12:09:42Z" level=fatal msg="failed to decode hubble-export-allowlist '\"verdict\":[\"DROPPED\"]': proto:\u00a0syntax error (line 1:1): unexpected token \
"verdict\"" subsys=config
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by berke581** [comment]
It seems like Helm was manipulating values containing `{...}` when using the `--set` flag. This was resolved by switching to the `--set-literal` flag instead (I also had to escape double quotes), which preserved the intended values without modification.

`--set-literal hubble.export.static.allowList[0]='{\"verdict\":[\"DROPPED\"]}'`

To help others who might face a similar problem, it might be worth updating the documentation to reflect this workaround.

Has anyone else experienced this issue?

**Comment by youngnick** [comment]
Yes, Helm allows you to use its templating language when using `--set`, so `--set-literal` is the way to go here. I'd argue this is a pretty good argument for using a values.yaml file instead of passing command-line flags, as the escaping can get very complicated very quickly.

That said, agreed that it would be nice to have an update in the docs noting this. I'll label this with `area/documentation` so anyone interested might be able to pick it up.
