### ISSUE TITLE
Clustermesh apiserver failure using helm chart

### ISSUE THREAD

**Issue by oblogic7** [cilium/cilium#34312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.15.7 and lower than v1.17.0

### What happened?

The clustermesh-apiserver pod fails to start with the following error:

```
Error: unknown flag: --cluster-name
```

### How can we reproduce the issue?

Enable clustermesh (`.Values.clustermesh.useAPIServer`) via helm chart and deploy to a cluster.

### Cilium Version

Client: 1.16.0 82999990 2024-07-23T22:22:14-07:00 go version go1.22.5 linux/amd64
Daemon: 1.16.0 82999990 2024-07-23T22:22:14-07:00 go version go1.22.5 linux/amd64

### Kernel Version

Linux ip-10-145-130-201.ec2.internal 6.1.97 #1 SMP PREEMPT_DYNAMIC Fri Jul 26 22:55:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-eks-db838b0

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marseel** [comment]
From what I can see, it was not removed, it was just moved to another place:
https://github.com/cilium/cilium/blob/b1f10bcb26d71f046d8ad108d5f4b9e42aa5d486/pkg/clustermesh/types/option.go#L43-L44
It is also used by clustermesh-apiserver so I don't think we can just remove it. Here is an example from my testing:

I've used the following values:
```
cluster:
  name: clustermesh1
  id: 1
debug:
  enabled: true
ipam:
  mode: kubernetes
ipv6:
  enabled: true
ipv4:
  enabled: true
clustermesh:
  useAPIServer: true
```
and the following command:
```
helm install cilium cilium/cilium --version 1.16.0   --namespace kube-system -f values.yaml --wait
```
and it was working just fine:
```
k logs -n kube-system clustermesh-apiserver-54499f9dc4-442pd -c apiserver
time="2024-08-13T10:39:52Z" level=info msg="  --cluster-id='1'" subsys=clustermesh-apiserver
time="2024-08-13T10:39:52Z" level=info msg="  --cluster-name='clustermesh1'" subsys=clustermesh-apiserver
...
Cilium ClusterMesh 1.16.0 82999990
```
so it is working. 

After deleting the section "cluster" from helm values:
```
cluster:
  name: clustermesh1
  id: 1
```
I'm getting a different error though on kvstoremesh container:
```
2024/08/13 10:46:10 ERROR Start hook failed function="kvstoremesh.registerClusterInfoValidator.func1 (.../clustermesh-apiserver/kvstoremesh/root.go:55) (kvstoremesh)" error="ClusterID 0 is reserved"
2024/08/13 10:46:10 ERROR Start failed error="ClusterID 0 is reserved" duration=13.166µs
```

so... I've deleted only the "name" field from cluster and got:
```
helm install cilium cilium/cilium --version 1.16.0   --namespace kube-system -f values.yaml --wait
Error: INSTALLATION FAILED: execution error at (cilium/templates/validate.yaml:107:5): The cluster name is invalid: cannot use default value with cluster.id != 0
```

so I am not able to reproduce it :thinking: 
Could you provide the exact commands that you used to deploy it or sysdump so we can take a look?

**Comment by oblogic7** [comment]
I'm not sure what sent me down this rabbit hole, but I'm unable to reproduce after starting fresh.  This particular deployment was handled via Crossplane, so there was likely some wire crossed on my end.
