### ISSUE TITLE
HostPort type service is created on the wrong node when cilium-agent enable disable-endpoint-crd config

### ISSUE THREAD

**Issue by haozhangami** [cilium/cilium#34342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

When cilium-agent enable `disable-endpoint-crd` config，it will watch all pods in the cluster until it connects to the kvstore. pod with a hostPort container may be watched, causing the hostport type service to be created on the wrong node.

We are currently using cilium version 1.12.19, the latest cilium version seems to follow the same logic.

### How can we reproduce the issue?

1. cilium-agent enable `disable-endpoint-crd` config
2. create a PodA with a hostPort container on NodeA
3. restart cilium-agent on NodeB, and execute `cilium service list |grep PodA_IP ` commad

### Cilium Version

1.12.19

### Kernel Version

5.15.80

### Kubernetes Version

1.28.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by haozhangami** [comment]
When creating the HostPort service, it looks like the code should check if nodeAddrAll contains the pod hostIP.

https://github.com/cilium/cilium/blob/main/pkg/k8s/watchers/pod.go#L696

In addition, I would like to know whether it is recommended to enable the `disable-endpoint-crd` configuration when cilium runs in kvstore mode.

**Comment by youngnick** [comment]
Thanks for logging this issue @haozhangami, looks like your PR is almost good to go. Great to see an issue and a fix logged together, nice work!
