### ISSUE TITLE
[cilium-dbg] pretty-print the IPv4 fragmentation map

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#34348]
Implement a `bpf frag list` for https://github.com/cilium/cilium/tree/main/pkg/maps/fragmap.

**Comment by Huweicai** [comment]
@julianwiedmann  Can I work on this issue? ❤

We can get fragmentation by `cilium map get cilium_ipv4_frag_datagrams` now.

But we want a dedicated new command with prettier output, am I right?

**Comment by Huweicai** [comment]
OK, I'll try it!

**Comment by StLeoX** [comment]
Also focusing

**Comment by StLeoX** [comment]
![image](https://github.com/user-attachments/assets/8c764083-2253-4870-8bad-5aa832213e01)

Can't find `cilium_ipv4_frag_datagrams`, setting helm value `fragmentTracking`.

**Comment by Huweicai** [comment]
@julianwiedmann Hello, i have implemented it, you can have a check to see if that's what you want.

https://github.com/cilium/cilium/pull/34751

Example:

<img width="589" alt="image" src="https://github.com/user-attachments/assets/438e9a12-9256-414c-9234-d61761416e87">
