### ISSUE TITLE
Layer-2-only link between pods

### ISSUE THREAD

**Issue by hmntsharma** [cilium/cilium#34396]
Hello,

Is it possible to create L2 links between the pods, so that containerized network images can be used to create a network topology and run network emulation labs? 
It could be also useful in production environment too.

Thanks,
Hemant

**Comment by joestringer** [comment]
This should technically be possible with ARP passthrough mode, but YMMV - you may need additional code changes to support this use case. It's not the common case that most Cilium users use.

**Comment by networkop** [comment]
this is also possible with other [special-purpose CNI plugins](https://github.com/networkop/meshnet-cni) which can be chained with Cilium.
