### ISSUE TITLE
bnxt_en version number confusing in the cilium documentation

### ISSUE THREAD

**Issue by rockc2020** [cilium/cilium#34419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.14.13 and lower than v1.15.0

### What happened?

We're running cilium in a bare metal K8s cluster:
- k8s version: v1.21.14
- cilium version: v1.11.4
- os: Linux n62-250-235.sin2a 5.10.135.bsk.3-amd64 #5.10.135.bsk.3 SMP Debian 5.10.135.bsk.3 Thu Mar 9 03:06:59 UTC x86_64 GNU/Linux
cilium is running with kubeproxy replacement strict mode.

the cilium agent pod failed to start with:

`
level=fatal msg="Failed to compile XDP program" error="program cil_xdp_root: attaching XDP program to interface eth0: cannot allocate memory" subsys=datapath-loader
`

And the NIC driver info is:
```
> ethtool -i eth0
driver: bnxt_en
version: 1.10.2-[225.4.8.0](http://225.4.8.0/)
firmware-version: [225.4.4.0/pkg](http://225.4.4.0/pkg) [225.4.6.0](http://225.4.6.0/)
expansion-rom-version:
bus-info: 0000:17:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
```
The version is `1.10.2-[225.4.8.0]`.
Per cilium documentation here: https://docs.cilium.io/en/latest/bpf/progtypes/ , it required broadcom bnxt_en `>= 4.11` in order to support XDP.
However, when we checked bnxt_en drivers, there is no such a format of bnxt_en version like 4.11 or higher.
for example, here is an output from apt:
```
apt list bnxt-en-dkms -a
Listing... Done
bnxt-en-dkms/buster-private,now 1.10.2.225.4.8.0 all [installed]
bnxt-en-dkms/buster-private 1.10.2.222.0.142.0 all
bnxt-en-dkms/buster-private 1.10.2.218.1.236.1 all
bnxt-en-dkms/buster-private 1.10.2.218.1.88.0 all
```
also here:
https://www.broadcom.com/products/ethernet-connectivity/network-adapters/n425g
https://www.broadcom.com/products/ethernet-connectivity/network-adapters/p425g

### How can we reproduce the issue?

In the environment above, the cilium agent failed every time with the exact same error.

### Cilium Version

`v1.11.4`

### Kernel Version

`Linux 5.10.135.bsk.3-amd64 #5.10.135.bsk.3 SMP Debian 5.10.135.bsk.3 Thu Mar 9 03:06:59 UTC x86_64 GNU/Linux`

### Kubernetes Version

`v1.21.14`

### Relevant log output

```shell
level=fatal msg="Failed to compile XDP program" error="program cil_xdp_root: attaching XDP program to interface eth0: cannot allocate memory" subsys=datapath-loader
```
```


### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for logging this issue @rockc2020.

Part of the reason that this discrepancy exists is that the documentation you were looking at is for the `latest` version of Cilium - which is the currently-in-development 1.17 release, not for the 1.11 version that you are using.

In fact, the 1.11 Cilium release has been unsupported for nearly a year, and the 1.21 Kubernetes version for even longer. I'd recommend upggrading both as soon as possible.

**Comment by rockc2020** [comment]
> Thanks for logging this issue @rockc2020.
> 
> Part of the reason that this discrepancy exists is that the documentation you were looking at is for the `latest` version of Cilium - which is the currently-in-development 1.17 release, not for the 1.11 version that you are using.
> 
> In fact, the 1.11 Cilium release has been unsupported for nearly a year, and the 1.21 Kubernetes version for even longer. I'd recommend upggrading both as soon as possible.

Thank you for the reply. Yeah, both versions are quite old and upgrade is a bit complicated on bare metal :( I'd also check doc for 1.11 for some references.

**Comment by julianwiedmann** [comment]
> Per cilium documentation here: https://docs.cilium.io/en/latest/bpf/progtypes/ , it required broadcom bnxt_en `>= 4.11` in order to support XDP.

The documentation refers to the minimum **kernel version** that includes a broadcom driver with XDP support. So you being on a `5.10` based kernel should be fine.

Let's please revisit this once you're on a current Cilium release.
