### ISSUE TITLE
Service ID conflict causes existing service IP to be disconnected after upgrade

### ISSUE THREAD

**Issue by haozhangami** [cilium/cilium#34411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Cilium 1.11 restores services from `cilium_lb4_backends_v2` map. cilium 1.12 and later versions restore services from `cilium_lb4_services_v2` map. a service fails to be restored due to service ID has been registered after cilium-agent upgrade 1.12, one of the conflicting services will be deleted because the k8s service no longer exists, which will cause the existing service IP to be unreachable, such as k8s service ClusterIP. 

Through `cilium monitor` capture packet , it was found that when the lxc NIC processed the `to-container` traffic, it did not convert the service backend IP into the service frontend IP.

### How can we reproduce the issue?

1.Use bpftool to insert a conflicting service ID entry in `cilium_lb4_services_v2` map
2.Restart cilium-agent, and ping service IP from the container

### Cilium Version

1.12.19

### Kernel Version

5.15.80

### Kubernetes Version

1.28.3

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by haozhangami** [comment]
This problem can be fixed manually by using bpftool to insert a correct entry(key: service ID <-> value: service IP) in `cilium_lb4_reverse_nat` map.

I tried to check revNATValue before deleting revNATKey in `deleteRevNatLocked` and it seems to fix this problem.

https://github.com/cilium/cilium/blob/main/pkg/maps/lbmap/lbmap.go#L231

**Comment by youngnick** [comment]
Hi @haozhangami, thanks for logging this issue.

Thanks also for documenting a workaround, that will be useful for other folks who might run into this issue. However, given that both Cilium 1.11 and Cilium 1.12 have been out of support for some time, I'm not sure there are any actions for the project to take here. We no longer release updates for those two versions.

What actions would you like to see?

**Comment by haozhangami** [comment]
Hi @youngnick 

The latest version seems to have this problem. Based on the existing `LB4_REVERSE_NAT_MAP` struct, it is necessary to check the value to prevent conflicting services from being deleted by mistake.

**Comment by squeed** [comment]
@haozhangami what do you mean about the latest version? As in, packets are dropped on an upgrade from v1.15 to v1.16?

**Comment by julianwiedmann** [comment]
If you are able to reproduce this on latest `main` branch, I would **strongly** encourage you to open a fresh issue that describes the problem there. I don't see how anyone would realistically want to get involved into this issue while it's related to Cilium versions that are already end-of-life.

**Comment by haozhangami** [comment]
I reproduce this problem on cilium version 1.16.1. 
```
cilium version
Client: 1.16.1 68579055 2024-08-13T13:29:59+00:00 go version go1.22.5 linux/amd64
Daemon: 1.16.1 68579055 2024-08-13T13:29:59+00:00 go version go1.22.5 linux/amd64
```

The specific steps to reproduce are as follows:
1. Query the ID of the `cilium_lb4_services_v2` map.
```
bpftool map show pinned /sys/fs/bpf/tc/globals/cilium_lb4_services_v2 
608: hash  name cilium_lb4_serv  flags 0x1
	key 12B  value 12B  max_entries 65536  memlock 1572864B
```
2. Add a entry with service ID 1 and the service IP does not exist in the k8s service.
```
bpftool map update id 608 key hex 0a 60 00 0b 23 c1 00 00 00 00 00 00 value hex 00 00 00 00 00 00 00 01 00 00 00 00

bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_services_v2 
key: 0a 60 00 0b 23 c1 00 00  00 00 00 00  value: 00 00 00 00 00 00 00 01  00 00 00 00
key: 0a 60 00 01 01 bb 01 00  00 00 00 00  value: 01 00 00 00 00 00 00 01  00 00 00 00
key: 0a 60 00 0a 23 c1 00 00  00 00 00 00  value: 00 00 00 00 01 00 00 04  00 00 00 00
key: 0a 60 00 01 01 bb 00 00  00 00 00 00  value: 00 00 00 00 01 00 00 01  00 00 00 00
key: 0a 6e 1f 4e 01 bb 01 00  00 00 00 00  value: 02 00 00 00 00 00 00 02  00 00 00 00
key: 0a 6e 1f 4e 01 bb 00 00  00 00 00 00  value: 00 00 00 00 01 00 00 02  00 10 00 00
key: 0a 60 00 0a 00 35 01 00  00 00 00 00  value: 03 00 00 00 00 00 00 03  00 00 00 00
key: 0a 60 00 0a 00 35 00 00  00 00 00 00  value: 00 00 00 00 01 00 00 03  00 00 00 00
key: 0a 60 00 0a 23 c1 01 00  00 00 00 00  value: 04 00 00 00 00 00 00 04  00 00 00 00
Found 9 elements
```

3. Query the reverse NAT entry with service ID 1.
```
bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_reverse_nat |grep 'key: 00 01'
key: 00 01  value: 0a 60 00 01 01 bb
```

4. restart cilium-agent.
```
docker restart 3e6d52e718da
3e6d52e718da

docker logs --timestamps 3e6d52e718da 2>&1 |grep "10.96.0.1"
2024-09-20T10:00:05.319025552Z time="2024-09-20T10:00:05Z" level=warning msg="Unable to restore service ID" error="Service ID 1 is already registered to \"10.96.0.11:9153\"" serviceID=1 serviceIP="10.96.0.1:443" subsys=service
2024-09-20T10:00:07.920725223Z time="2024-09-20T10:00:07Z" level=warning msg="Deleting no longer present service" l3n4Addr="{AddrCluster:10.96.0.11 L4Addr:{Protocol:NONE Port:9153} Scope:0}" serviceID=1 subsys=service
```

5. Query the reverse NAT entry with service ID 1 again, it becomes empty, affecting access to the existing service IP.
```
bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_reverse_nat |grep 'key: 00 01'
```

@julianwiedmann @joamaki Please take a look, I can open a new issue if necessary, thanks.
