### ISSUE TITLE
test: Re-enable K8sValidatedUpdates

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3442]
Re-enable once test is stable

**Comment by eloycoto** [comment]
Related with: https://github.com/cilium/cilium/issues/3383

**Comment by aanm** [comment]
Related with https://github.com/cilium/cilium/pull/3125/

**Comment by ianvernon** [comment]
@eloycoto can this be closed since 60a4b5270bd2fc5e71f505e31513b924c610f170 re-enabled the test?
