### ISSUE TITLE
cilium mesh etcd old

### ISSUE THREAD

**Issue by cccsss01** [cilium/cilium#34434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

A bug happened!
etcd-client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007b2000/127.0.0.1:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: revision of auth store is old"

### How can we reproduce the issue?

Install latest 1.16.1, and i see this in the logs

### Cilium Version

1.16.1

### Kernel Version

5.14.0-284.30.1.el9_2.x86_64

### Kubernetes Version

1.28.1

### Sysdump

unfortunately I can't

### Anything else?

Is the etcd container inside clustermesh api server too old?

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Hi @cccsss01, thanks for opening this issue, which appears to be related to problems with the clustermesh etcd server. 

Unfortunately, without access to at least the etcd server logs from as many nodes as possible, it won't be possible for anyone to troubleshoot this issue. I suggest seeing if you can grab those logs at least and add them to this issue.

**Comment by cccsss01** [comment]
I figured this one out, i'll great a pr for clustermesh trouble shooting.
