### ISSUE TITLE
Cilium mesh host alias and port wrong

### ISSUE THREAD

**Issue by cccsss01** [cilium/cilium#34441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Very weird, when using node port and setting node selector to a specific node of a cluster with mesh enabled, it is routing traffic to the wrong node

host alias =
name: bob1
192.1.1.15
-port 31000

bob1 has label test=mesh and clustermeshapi server has nodeSelector test: mesh

it will send traffic to bob2 that does not clustermesh running and does not have the label, yet traffic is being routed there @ port 31000

### How can we reproduce the issue?

use nodeport and labels to schedule clustermesh accordingly, use a non flat network, have more than two worker nodes, one labeled and one not to specify which clustermesh node runs on, use network monitorting to view outbound traffic going to the node w/o clustermesh running on it.

### Cilium Version

v1.16.1

### Kernel Version

5.14.0-427.16.1.el9_4.x86_64

### Kubernetes Version

v1.27.14

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for logging this issue @cccsss01, but we'll need a lot more information before anyone will be able to help you.

This sounds like a complicated setup, so folks will need at least:
- a more detailed explanation of what you're trying to achieve
- some details on how you installed Cilium and where it's running
- ideally a full sysdump, since exactly what will be needed to troubleshoot this is not clear.

**Comment by cccsss01** [comment]
unfortunately I can't provide a sysdump, is there something specifically you need?

Essentially a non flat network, when I run cilium clustermesh status from one cluster, it's looking saying clustermesh detected to an ip address of another cluster that is not running the clustermesh api on the ip it's stated, but was the most recent addition to the cluster.

I have clustemresh config setup with ips: and port: set correctly, but it's grabbing a different ip

While my permanent solution is to leverage an ELB, that's not the case atm.

**Comment by youngnick** [comment]
I'm sorry, I don't understand what you mean. The requirements for cluster mesh on the documentation page (https://docs.cilium.io/en/stable/network/clustermesh/clustermesh/#cluster-addressing-requirements) says that:

* All clusters must be configured with the same datapath mode. Cilium install may default to [Encapsulation](https://docs.cilium.io/en/stable/network/concepts/routing/#arch-overlay) or [Native-Routing](https://docs.cilium.io/en/stable/network/concepts/routing/#native-routing) mode depending on the specific cloud environment.

* PodCIDR ranges in all clusters and all nodes must be non-conflicting and unique IP addresses.

* Nodes in all clusters must have IP connectivity between each other using the configured InternalIP for each node. This requirement is typically met by establishing peering or VPN tunnels between the networks of the nodes of each cluster.

* The network between clusters must allow the inter-cluster communication. The exact ports are documented in the [Firewall Rules](https://docs.cilium.io/en/stable/operations/system_requirements/#firewall-requirements) section.

It seems from your description like maybe the third item doesn't apply?

Also, have you gone through the steps on the Clustermesh troubleshooting page? https://docs.cilium.io/en/stable/operations/troubleshooting/#troubleshooting-clustermesh
