### ISSUE TITLE
cilium-cli: streamline the behavior of `cilium upgrade` to preserve previous configurations

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#34464]
The Cilium CLI install and upgrade commands build on top of the corresponding helm commands, adding a bit of extra logic on top to automatically configure certain parameters based on the target cluster configuration (e.g., cloud provider, presence of kube proxy replacement, ...). However, `cilium upgrade` inherits the same confusing behavior as helm with respect to modifying already set parameters on upgrade (and the `--reset-values` and `--reuse-values` flags, whose default depends on whether additional parameters are configured). In turn, this can cause previously automatically configured parameters to be silently reset on upgrade, silently breaking Cilium. We hit this pitfall in the clustermesh and ipsec upgrade workflows in CI, and it is likely that most users are affected as well.

Helm [recently introduced](https://github.com/helm/helm/pull/9653) the support for the `--reset-then-reuse-values` merge strategy, which looks like a good candidate as default policy for `cilium upgrade`, given that it matches the behavior expected by most people:

> --reset-then-reuse-values:  when upgrading, reset the values to the ones built into the chart, apply the last release's values and merge in any overrides from the command line via --set and -f. If '--reset-values' or '--reuse-values' is specified, this is ignored

Related: https://github.com/cilium/cilium-cli/issues/1725

**Comment by ManidharVutla** [comment]
I want to work on this. Please don't hesitate to assign this to me. Thanks!

**Comment by giorio94** [comment]
Thanks, I've assigned you!

**Comment by saiaunghlyanhtet** [comment]
@giorio94 I think that ManidharVutla is not working on this issue. So I created a PR #36347
