### ISSUE TITLE
Creating metrics services is tied to the creation of service monitors

### ISSUE THREAD

**Issue by tschlaepfer** [cilium/cilium#34466]
### Issue
In the Cilium Helm chart is the creation of the metrics services for the cilium-agent and cilium-operator currently tied to the creation of service monitors, due to the IF statement requiring:

https://github.com/cilium/cilium/blob/0f768339754246bd4c85d27953bc71cab7490006/install/kubernetes/cilium/templates/cilium-agent/service.yaml#L3
https://github.com/cilium/cilium/blob/0f768339754246bd4c85d27953bc71cab7490006/install/kubernetes/cilium/templates/cilium-operator/service.yaml#L1

This prevents use cases where the metrics are scraped but not using service monitors.

### Solution
Remove the requirement for the service monitors to be enabled.

**Comment by michaeljsaenz** [comment]
i can take this one? please assign
