### ISSUE TITLE
Low CiliumIdentity GC speed leading to ID running out

### ISSUE THREAD

**Issue by charlie0129** [cilium/cilium#34512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.14.13 and lower than v1.15.0

### What happened?

With a relatively fast Pod creation/deletion speed (around 40 Pods/s) and creating Pods for around half an hour, we are seeing CNI timeouts.

<img width="777" alt="image" src="https://github.com/user-attachments/assets/d2402e12-2343-4dcc-8450-0059749c7eca">

The Cilium Agent is saying no more available IDs:

```
level=warning msg="Key allocation attempt failed" attempt=3 error="no more available IDs in configured space" key="[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=redacted k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=redacted redacted]" subsys=allocator
```

We are getting over 60000 CiliumIdentity CRs (which is around the max, 16bit uint):

![image](https://github.com/user-attachments/assets/92c8d21e-f0a6-4904-928f-b745a886e70d)

And it takes several hours to recycle them (around 5/s). The picture below is the cilium operator log (filtering by identity-related keywords `Marking identity|Deleting unused identity`) of over 16000 identites (not the 60000 above, we lost the logs).

<img width="1449" alt="image" src="https://github.com/user-attachments/assets/6eb0cd17-770d-4f3f-93b0-49a6c95c227a">

After taking a look at the code `operator/identitygc/crd_gc.go`, I didn't see an option to increase the gc speed.

### Expectations

We expect the CiliumIdentity recycle speed to be faster so we don't have to wait hours to create another Pod.

### How can we reproduce the issue?

1. Install Cilium (we use 1.14.4)
2. Create/Delete lots of Pods in a short period of time. (see what we did above)

### Cilium Version

cilium image (default): v1.16.0
cilium image (stable): v1.16.1
cilium image (running): 1.14.4

### Kernel Version

Linux redacted 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.28.4

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi, off the top of my head I think that it's a red flag if you're seeing 60K cluster-wide identities. Unless you really have that many unique security domains (groups of applications with unique policies between them), it is likely that the security labels being considered for security identities are too specific. I'd suggest as a potential mitigation to take a look through these docs and see if they can help to resolve the issue: https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#identity-relevant-labels

**Comment by charlie0129** [comment]
Thank you for your suggestion. We indeed missed that one. We will figure out which identity-relevant labels are needed and update here if the problem is resolved.
