### ISSUE TITLE
CI: Installation and Connectivity Test (1.29, us-east-1, true, true)

### ISSUE THREAD

**Issue by antonipp** [cilium/cilium#34525]
## CI failure
Example failure: https://github.com/cilium/cilium/actions/runs/10505731987/job/29103920446

Looks like the test failed because of
```
"The maximum number of VPCs has been reached. (Service: Ec2, Status Code: 400, Request ID: 8484ce11-4dcc-49f4-b404-3d0d55b4ad9c)"
```

This looks similar to https://github.com/cilium/cilium/issues/30770

[logs_27469034880.zip](https://github.com/user-attachments/files/16710693/logs_27469034880.zip)

**Comment by pchaigno** [comment]
Thanks for the report! We're looking into it :slightly_smiling_face:

**Comment by pchaigno** [comment]
This should be fixed since 4:45pm CET thanks to Viktor who cleaned up stale resources while a longer term solution is discussed.
