### ISSUE TITLE
 A question about gateway-api support servcie-type

### ISSUE THREAD

**Issue by peterleezzzZflps** [cilium/cilium#34533]
I saw that the type of svc creation can be specified in ingress support ingress.cilium.io/service-type: NodePort | ClusterIP | LoadBalancer. Is there a corresponding parameter that can be set in gateway-api?

**Comment by HoKim98** [comment]
You may want to toggle `gatewayAPI.hostNetwork.enabled`.

> By default, the Gateway API controller creates a service of LoadBalancer type, so your environment will need to support this. Alternatively, since Cilium 1.16+, you can directly expose the Cilium L7 proxy on the [host network](https://docs.cilium.io/en/v1.16/network/servicemesh/gateway-api/gateway-api/#gs-gateway-host-network-mode).

> Enabling the Cilium Gateway API host network mode automatically disables the LoadBalancer type Service mode. They are mutually exclusive.

* https://docs.cilium.io/en/v1.16/network/servicemesh/gateway-api/gateway-api/#host-network-mode

**Comment by peterleezzzZflps** [comment]
OK, I have enabled public service access in this way, but will nodeport support this requirement in the future? Because nodeport and hostnetwork are not completely equivalent.

**Comment by joseguerrero** [comment]
[This issue](https://github.com/cilium/cilium/issues/27273) may be of interest for your question, in case you haven't seen it already

**Comment by peterleezzzZflps** [comment]
Yes, thank you for your feedback. I am aware of the related issues you mentioned. I just want to know if you will consider implementing NodePort in the future? Is there any relevant plan?

**Comment by joseguerrero** [comment]
Oh I am not a maintainer here, I just thought it would be useful to gather all the interest about this topic on that conversation 😅 sorry for the confusion.

**Comment by peterleezzzZflps** [comment]
Ok, thanks for your reply anyway
