### ISSUE TITLE
Update the smoke tests to fail more quickly and more clearly when there is a fatal error in the agent

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#34537]
### Problem Statement

Currently if there is a fatal error introduced during development into the cilium-agent, the smoke tests will attempt to [Wait for Cilium Status to be ready](https://github.com/cilium/cilium/blob/983bb6f2307a219b50610ed6b2d0098c0cd942ec/.github/workflows/tests-smoke.yaml#L166), which times out after five minutes by default.

The output from the test will flood the logs with repeated `cilium status` attempts, which ultimately will look a bit like this, repeated for around 4000 lines:

```
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             3 errors
 \__/¯¯\__/    Operator:           1 errors
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       1 errors, 1 warnings
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 2, Unavailable: 2/2
Deployment             hubble-relay       Desired: 1, Unavailable: 1/1
DaemonSet              cilium-envoy       Desired: 2, Ready: 2/2, Available: 2/2
Deployment             cilium-operator    Desired: 1, Unavailable: 1/1
Containers:            cilium             Running: 2
                       hubble-relay       Pending: 1
                       cilium-envoy       Running: 2
                       cilium-operator    Running: 1
Cluster Pods:          0/4 managed by Cilium
Helm chart version:    
Image versions         cilium             quay.io/cilium-dev/cilium-ci:<tag>: 2
                       hubble-relay       quay.io/cilium-dev/hubble-relay-ci:<tag>: 1
                       cilium-envoy       quay.io/cilium/cilium-envoy:<tag>: 2
                       cilium-operator    quay.io/cilium-dev/operator-generic-ci:<tag>: 1
Errors:                cilium             cilium                           2 pods of DaemonSet cilium are not ready
                       cilium             cilium-jzk7s                     unable to retrieve cilium status: container cilium-agent is in CrashLoopBackOff, exited with code 2:     /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1194 +0x51
                       cilium             cilium-r6lrd                     unable to retrieve cilium status: container cilium-agent is in CrashLoopBackOff, exited with code 2:     /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1194 +0x51
                       hubble-relay       hubble-relay                     1 pods of Deployment hubble-relay are not ready
                       cilium-operator    cilium-operator                  1 pods of Deployment cilium-operator are not ready
Warnings:              hubble-relay       hubble-relay-798d7c889d-dznck    pod is pending
Error: Process completed with exit code 1.
```

In order to resolve this issue, I can go into the workflow Summary, download the sysdump, then start investigating the logs for more details. This is good, it's possible to solve the underlying problem. It could be better though.

### Proposal

This proposal is to make cilium-cli a bit smarter to detect when there is a fatal error in the previous cilium logs, then print those fatal errors in their entirety (probably involves listing the last ~50 messages in the previous agent log), then exit with a non-zero code immediately rather than retrying for the rest of the 5-minute timeout.

### Details

This could be implemented by making the Cilium CLI `cilium status --wait` command check if a Cilium pod has failed / has restarts, then check the previous run's logs for any message with `level=fatal`. In that case, maybe rather than retrying, the CLI should fail out the status wait command instead.

Some details that could help make an implementation easier:
- If the fatal error is detected, we could just list the last 50 messages from the _previous_ agent run to provide a baseline. This is probably the easiest while providing the info developers are likely to need. Alternatives would be to print a higher number by default, or print all non-debug messages, or only print logs with "warning" level or above. The only downside with filtering the logs by level is that I think that some things like Hive might print useful stack traces and I'm not sure those output messages use proper log-structuring, so this could filter out useful info.
- It would be nice to have this enabled by default even for user environments, but it would not be required to work this way in user environment by default. If necessary to simplify rollout we could enable it with a custom hidden flag, then update the workflows to use the flag.
- This could be tested by introducing a deliberate failure like a panic into the main function of the agent, then check that the CLI more quickly detects the failure and prints error output that is easy to understand.

**Comment by nimishamehta5** [comment]
I was recently near the Cilium CLI code and thought of looking into this issue, there was a commit to add an "interactive" flag that at the very least will not spam the workflow logs: https://github.com/cilium/cilium/commit/8f0cb35524fb7099a293e60befd96460e69d20a7#diff-56370550ce46836dae5d8d23169d396fe1bfb3042b66ed68bfcd44b8f95c733bR55

However, this will still wait the full timeout / five minutes.

**Comment by nimishamehta5** [comment]
Could you please assign this issue to me? Thanks
