### ISSUE TITLE
1.0 Testing Week Coordination

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3460]
Tracking issue to coordinate all testing effort this week:

Add testing tasks here:
- [x] Debug all Jenkins master failures and make it reliable (https://github.com/cilium/cilium/issues/3459)
- [ ] Provide policy example for 5 demo apps (TBD)

Documentation gaps found:
- [ ] ToEndpoints need to specify that it does *NOT* apply to pods which are running in host networking (TBD)
- [ ] fromCIDR currently includes all ingress, packets are accepted if either CIDR, host or labels allow it (TBD)
- [ ] Review all hands week: https://docs.google.com/document/d/16ijEy6vNDcZ2RqZXMjFGCzuevDPE_4nH3AK25Ab04OM/edit?usp=sharing
- [x] https://github.com/cilium/cilium/issues/2556: general ToEndpoints documentation

**Comment by manalibhutiyani** [comment]
I can take the Kafka demo app.

**Comment by ackerman80** [comment]
I will take couchdb (arvind)

**Comment by tgraf** [comment]
> I can take the Kafka demo app.

Please take a non Kafka demo app as you are very familiar with Kafka already ;-)

**Comment by manalibhutiyani** [comment]
@tgraf : Haha :) Yes I thought that too after writing here.  I can take` grpc ` then

**Comment by ackerman80** [comment]
couchdb example which has
- couchdb-server
- client1
- clinet2
I modified the policy file to be a little simple : just allow client1 GET/PUT access for all paths
client1 gets the access but client 2 calls hang there for quite some time and result in `command terminated with exit code 7`
attached the policy file
[cdb_policy.yaml.txt](https://github.com/cilium/cilium/files/1870300/cdb_policy.yaml.txt)

```
kubectl exec client1  -- curl -XGET -s http://couchdb-svc:5984/public-db
{"db_name":"public-db","update_seq":"1-g1AAAAEzeJzLYWBg4MhgTmHgzcvPy09JdcjLz8gvLskBCjMlMiTJ____PyuRAYeCJAUgmWSPX40DSE08fjUJIDX1eNXksQBJhgYgBVQ2PyuREa-6BRB1-wmZdwCi7j4hdQ8g6kDuywIAiQxi9w","sizes":{"file":38048,"external":47,"active":332},"purge_seq":0,"other":{"data_size":47},"doc_del_count":0,"doc_count":1,"disk_size":38048,"disk_format_version":6,"data_size":332,"compact_running":false,"cluster":{"q":8,"n":1,"w":1,"r":1},"instance_start_time":"0"}
```
```
kubectl exec client2  -- curl -XGET -s http://couchdb-svc:5984/public-db
command terminated with exit code 7
```

**Comment by ianvernon** [comment]
> "ToEndpoints need to specify that it does NOT apply to pods which are running in host networking (TBD)" 

@tgraf what does this mean? Does the same apply to `FromEndpoints`?

**Comment by tgraf** [comment]
> @tgraf what does this mean? Does the same apply to FromEndpoints?

Yes, same applies to FromEndpoints. I noticed that it is not obvious that From and ToEndpoints only works for pod labels which are in fact not using host networking right now. It's obvious to us but is not obvious to users.

**Comment by aanm** [comment]
1.0 was already released. Closing
