### ISSUE TITLE
CFP: Provide `cilium ip get` command enhancements to filter output by CIDR or labels.

### ISSUE THREAD

**Issue by vasu-dasari** [cilium/cilium#34632]
## Cilium Feature Proposal
At present, there is no option to display information about the IP cache (ipcache) by CIDR or labels. This necessitates capturing all ipcache information using the "cilium ip list" command and parsing it subsequently. The suggested feature aims to display ipcache information based on CIDR or labels.

Once implemented, users can utilize the `cilium ip` command as follows:
```
Usage:
  cilium ip get ( <cidr> |-l <identity labels> ) [flags]

Flags: -h, --help             help for get
  -l, --labels strings   list of labels
  -o, --output string    json| yaml| jsonpath='{}'
  -v, --verbose          Print all fields of ipcache
```
**Is your proposed feature related to a problem?**
No

**Describe the feature you'd like**

Include any specific requirements you need

**(Optional) Describe your proposed solution**

I will contribute the code to provide above CLI.

**Comment by vasu-dasari** [comment]
Ability display Ip cache entries by cidr was implemented in the backend but not exposed. This was done by @gandro here [daemon/cmd/ipcache.go](https://github.com/cilium/cilium/blob/5e5be1c55d3a55ccc5c0430a89557a1f25f38554/daemon/cmd/ipcache.go#L65). But this was not exposed via CLI.

I am adding another option to expose ip cache by Labels as part of this effort.

**Comment by chaunceyjiang** [comment]
Hi @vasu-dasari. Do you have time to handle this issue? If not, I can go ahead and complete this issue.

**Comment by vasu-dasari** [comment]
I have the code. Will raise PR this weekend.
