### ISSUE TITLE
CFP: Customable tc action 

### ISSUE THREAD

**Issue by l1b0k** [cilium/cilium#34680]
## Cilium Feature Proposal

Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](https://slack.cilium.io) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

If so, please describe the problem

**Describe the feature you'd like**

The BPF program utilizes TC_ACT_OK as its return value, as a result other tc program won't be executed.
In our case , we use tc to add vlan tag to the traffic leaving the node. I hack the code to use TC_ACT_PIPE to make it work.
The idea is to set the customable return value instead of TC_ACT_OK.

**(Optional) Describe your proposed solution**

**Comment by joestringer** [comment]
cc @cilium/sig-datapath 

This seems nominally fine to me as a new hidden flag to customize the default return value to either TC_ACT_OK (default) or TC_ACT_PIPE. For L7 it should still use TC_ACT_OK to ensure the traffic is delivered to the proxy, but for other L3/L4 return values it is likely OK to switch over.

**Comment by borkmann** [comment]
This needs to be configurable. TC_ACT_PIPE will not work with tcx which is the default for Cilium on newer kernels. See also:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/bpf.h#n6414

I'd suggest two steps:
- Migrate the Cilium TC_* opcodes over to TCX_* in a first step
- Add agent config knob (default: false) to switch TCX_PASS into TCX_NEXT at the appropriate locations.

**Comment by l1b0k** [comment]
Another idea is to enable VLAN support in Cilium, allowing each endpoint to have its own VLAN tag. 
VLAN tagging only needs to be handled when entering or leaving a node, and there is no need for VLAN tags inside node.
Is this approach more flexible than the one mentioned above?

**Comment by borkmann** [comment]
This sounds like a separate CFP, that is, proper VLAN supports e.g. via Pod annotations or such.
