### ISSUE TITLE
The Join Slack does not work if you don't have @linuxfoundation.org or @meetingtomorrow.org

### ISSUE THREAD

**Issue by ecerulm** [cilium/cilium#34689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I tried to join the Slack channel but all the links I can find lead to https://cilium.slack.com/signup which requires a @linuxfoundation.org or @meetingtomorrow.org address 

When I try to signup with my google account I get  `The email address must match one of the domains listed below. Please try another email.` and `You can use any account with the domain:
linuxfoundation.org
meetingtomorrow.com
Don’t have an email address from one of those domains?
Contact the workspace administrator at Cilium & eBPF for an invitation.`

![image](https://github.com/user-attachments/assets/523742a2-5167-470f-8930-17bd1b192b8b)

### How can we reproduce the issue?

N/A

### Cilium Version

N/A

### Kernel Version

N/A

### Kubernetes Version

N/A

### Anything else?

I think there was a http://cilium.herokuapp.com in the past but no longer works. 

http://slack.cilium.io/ has the same problem, it redirects to https://cilium.slack.com/signup#/domain-signup

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ecerulm** [comment]
This has been solved already by @lizrice

**Comment by nogweii** [comment]
I believe this is happening again, what was the fix @ecerulm ?

**Comment by ecerulm** [comment]
@lizrice solved it, I don’t know how
