### ISSUE TITLE
Documentation framework

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#347]

**Comment by aalemayhu** [comment]
Maybe [Sphinx](http://www.sphinx-doc.org/en/stable/) could be used? Can we
rename `doc` to `Documentation`? It has the nice side effect of putting the
documentation directory at the top.

**Comment by tgraf** [comment]
> Maybe Sphinx could be used?

Yes! I've already started using sphinx, see ongoing branch:
https://github.com/cilium/cilium/tree/doc/doc

> Can we
> rename doc to Documentation? It has the nice side effect of putting the
> documentation directory at the top.

Very good point. I will do this.
