### ISSUE TITLE
CFP: vlan support

### ISSUE THREAD

**Issue by l1b0k** [cilium/cilium#34702]
## Cilium Feature Proposal

**Describe the feature you'd like**

To enhance density and isolation, cloud providers often use trunk NICs with VLANs.  
Suggests adding a VLAN field to endpoints, which can be managed by bpf_host for endpoint traffic.
VLAN tagging is only required at node entry or exit, not internally.

**(Optional) Describe your proposed solution**

**Comment by joestringer** [comment]
Hi, at a high level the request to support VLAN seems reasonable, but there will be a lot of detail to work out. I would suggest starting from considering the "user journey" of how you expect a user of Cilium to configure VLAN mappings, and we can explore the idea from there.

**Comment by l1b0k** [comment]
Thanks for your advice, i write more detailed in this [doc](https://docs.google.com/document/d/1-tW3ZI8DiwUeoyFW3lmDrlaNhDv41fQJDGjVu1P-9ak/edit)
