### ISSUE TITLE
CFP: Envoy: allow configuration of preserve_external_request_id in HttpConnectionManager

### ISSUE THREAD

**Issue by yesterdays-vigilante** [cilium/cilium#34703]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

For us, yes - our application relies on `x-request-id` being propagated from external requests.

I think there's also a more general problem, if only narrowly so: because Envoy by default creates a new value for `x-request-id` for every external request, in a multi-cluster setup this means one request which traverses multiple clusters will also end up getting different `request-id`s in each cluster, which makes stable tracing harder.

**Describe the feature you'd like**

Envoy supports preservation of external request IDs through the `preserve_external_request_id` config item on the HttpConnectionManager extension - I'd like this to be configurable through Cilium. 

**Describe your proposed solution**

I'd propose adding an additional value to the Cilium helm chart, perhaps:

```
envoy:
  preserveExternalRequestIds: false
```

but, as I'm not part of the Cilium project I would be very open to any other options here. I'd be very happy to contribute code for this as necessary.

**Comment by an-luu-ts** [comment]
any update on this?

**Comment by movergan** [comment]
That would be an important feature.
