### ISSUE TITLE
CI: Fix k8s log gathering

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3475]
Example output is attached to Issue #3470.

Need to:
* [x] Fix gathering cilium-bugtool to collect artifacts from k8s nodes upon test failure (#3411)
* [x] Timestamps are missing from `cilium_logs.txt`
* [x] Can we annotate `cilium_logs.txt` with the cilium node they apply to?
    * Alternatively, gather also node-by-node log files

From test-output.log:
```
time="2018-04-01T02:33:19Z" level=debug msg="running command: kubectl exec -n kube-system cilium-jqsxw -- ls /tmp/"
cmd: "kubectl exec -n kube-system cilium-jqsxw -- ls /tmp/" exitCode: 0 
 cilium-bugtool-20180401-023314.707+0000-UTC-293011469.tar

time="2018-04-01T02:33:20Z" level=debug msg="running command: kubectl cp kube-system/cilium-jqsxw:/tmp/cilium-bugtool-20180401-023314.707+0000-UTC-293011469.tar /tmp/"
time="2018-04-01T02:33:20Z" level=error msg="'kubectl cp kube-system/cilium-jqsxw:/tmp/cilium-bugtool-20180401-023314.707+0000-UTC-293011469.tar /tmp/' failed: error: open /tmp: is a directory\n" CiliumPod=cilium-jqsxw testName=K8sServiceTest
time="2018-04-01T02:33:20Z" level=debug msg="running command: cp /tmp/cilium-bugtool-20180401-023314.707+0000-UTC-293011469.tar /home/vagrant/go/src/github.com/cilium/cilium/test/test_results/17-/K8sValidatedServicesTestCNPSpecsTest/cilium-jqsxw-cilium-bugtool-20180401-023314.707+0000-UTC-293011469.tar"
time="2018-04-01T02:33:20Z" level=error msg="'cp /tmp/cilium-bugtool-20180401-023314.707+0000-UTC-293011469.tar /home/vagrant/go/src/github.com/cilium/cilium/test/test_results/17-/K8sValidatedServicesTestCNPSpecsTest/cilium-jqsxw-cilium-bugtool-20180401-023314.707+0000-UTC-293011469.tar' failed: cp: cannot stat '/tmp/cilium-bugtool-20180401-023314.707+0000-UTC-293011469.tar': No such file or directory\n" CiliumPod=cilium-jqsxw testName=K8sServiceTest
```

cilium-logs collection code:

https://github.com/cilium/cilium/blob/f9000c886f1f1c29b7d2c2f8608c9d41278ac016/test/helpers/kubectl.go#L907

**Comment by ianvernon** [comment]
First bulletpoint (`cilium-bugtool` from K8s nodes) was addressed by #3411 . However, the fix was merged after the issue in https://github.com/cilium/cilium/issues/3470 was hit on Jenkins. I will create a ticket for adding a test to ensure that the cilium-bugtool / associated log-gathering commands are functioning correctly.

**Comment by ianvernon** [comment]
Second / third bulletpoints were fixed by https://github.com/cilium/cilium/issues/3636, so am checking that box, and K8s tests now have logs per pod with timestamps if tests fail. Can we close this @joestringer ?

**Comment by joestringer** [comment]
Sounds good, thanks for following up @ianvernon !
