### ISSUE TITLE
CFP: E2E tests for delegated IPAM

### ISSUE THREAD

**Issue by wedaly** [cilium/cilium#34788]
**Is your proposed feature related to a problem?**

None of the E2E tests currently use Cilium with a delegated IPAM plugin.

**Describe the feature you'd like**

Add an E2E test that runs Cilium in delegated IPAM mode, preferrably validating both IPv4 and IPv6.

**(Optional) Describe your proposed solution**

It should be possible to validate this in a kind cluster using one of the [reference CNI IPAM plugins](https://www.cni.dev/plugins/current/#ipam-ip-address-allocation).

The default CNI (kindnet) does not support overriding the conflist (see Antonio's response here https://github.com/aojea/kindnet/pull/22) , so we would need to [disable the default CNI in kind](https://kind.sigs.k8s.io/docs/user/configuration/#disable-default-cni) and install everything ourselves.

**Comment by joestringer** [comment]
I think this makes sense. Given the effort to categorize tests into pre-merge vs. post-merge in https://github.com/cilium/cilium/issues/34688 , I would think we should probably add this testing to post-merge with the option to manually trigger via Ariane if a PR is making changes to delegated-ipam areas.
