### ISSUE TITLE
ClusterIP Service routes traffic to incorrect destination pod after upgrading EKS masters to 1.29

### ISSUE THREAD

**Issue by m00lecule** [cilium/cilium#34782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.14.13 and lower than v1.15.0

### What happened?

Hi,

We are running EKS cluster with Cilium in overlay mode without kube-proxy replacement.

We are facing plenty of connection reset by peer error, on a traffic between two separate deployments after upgrading EKS to 1.29 and Cilium to 1.12.16. To mitigate the issue we have tried to upgrade Cilium to 1.13.X and 1.14.Y without a success.

The source pod is reaching out to destination pod over ClusterIP Service, which initially looked like issue with iptables/conntrack, which is out of Cilium scope. Source application is using tcp session pooling for subsequent http requests, which is considered a normal thing. After making a `tcpdump` we have discovered that connection reset by peer occurs when ClusterIP service is routing traffic to a wrong destination pod within the same tcp session. The incorrectly selected pod is not aware of that tcp session, thus responding with TCP RST.

![Screenshot from 2024-09-09 10-14-26](https://github.com/user-attachments/assets/e3700618-1fd2-4cca-9db6-3efdc9db40d8)

Initially we were suspecting the conntrack's `net.netfilter.nf_conntrack_tcp_timeout_established` parameter. However there were conntrack DNAT session missing - `sudo conntrack -E -p tcp --dst-nat`.

Turned out that Cilium is always by-passing kube-proxy iptables chains, even if running in kube-proxy replacement disabled mode, by implementing ClusterIP Service using ebpf.

We have successfully found some evidences of ClusterIP Service DNAT sesssions stored in Cilium's conntrack.

```console
$ cilium status --verbose | grep -i ClusterIP -C 10
Hubble:                  Disabled
KubeProxyReplacement Details:
  Status:                 Disabled
  Socket LB:              Disabled
  Socket LB Tracing:      Disabled
  Socket LB Coverage:     Full
  Session Affinity:       Disabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Disabled 
  - LoadBalancer:   Disabled 
  - externalIPs:    Disabled 
  - HostPort:       Disabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Auth                          524288
  Non-TCP connection tracking   145459
  TCP connection tracking       290919
  Endpoint policy               65535
(...)
$ curl -vvv SVC_B:5000
*   Trying 172.20.78.159:5000...
* Connected to SVC_B (172.20.78.159) port 5000 (#0)
> GET / HTTP/1.1
> Host: SVC_B:5000
> User-Agent: curl/7.88.1
> Accept: */*
> 
(...)
$ cilium monitor --to 56966
Press Ctrl-C to quit
time="2024-08-29T15:48:06Z" level=info msg="Initializing dissection cache..." subsys=monitor
Policy verdict log: flow 0x7b12ec80 local EP ID 1860, remote ID 56966, proto 6, egress, action allow, auth: disabled, match L3-Only, 10.0.62.70:58930 -> 10.0.255.90:5000 tcp SYN
^C
Received an interrupt, disconnecting from monitor...
(...)
$ cilium bpf ct list global | grep -i 10.0.62.70:58930
TCP OUT 172.20.78.159:5000 -> 10.0.62.70:58930 service expires=2635967 RxPackets=0 RxBytes=21229 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1b LastTxReport=2614367 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=179 SourceSecurityID=0 IfIndex=0 
TCP OUT 10.0.62.70:58930 -> 10.0.255.90:5000 expires=2614377 RxPackets=4 RxBytes=428 RxFlagsSeen=0x1b LastRxReport=2614367 TxPackets=6 TxBytes=492 TxFlagsSeen=0x1b LastTxReport=2614367 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=179 SourceSecurityID=22515 IfIndex=
```

We have increased the `bpf-ct-timeout-service-tcp` and `bpf-ct-timeout-regular-tcp` cilium-agents parameters, but without a success -  (https://docs.cilium.io/en/stable/cmdref/cilium-agent/).

We would appreciate some help related to both debugging and fixing the issue. Unfortunately I can't upload `cilium sysdump` due to ~250mb archive size.

### How can we reproduce the issue?

Unfortunately we can't reproduce this issue. 

### Cilium Version

cilium-cli: v0.15.16 compiled with go1.21.4 on linux/amd64
cilium image (default): v1.14.4
cilium image (stable): v1.16.1
cilium image (running): 1.14.13

### Kernel Version

5.10.215-203.850.amzn2.x86_64

### Kubernetes Version

Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7-eks-2f46c53

### Regression

It is regression after upgrading EKS from 1.28 to 1.29 and Cilium from 1.12.10 to 1.12.16. We have tried also other Cilium versions - 1.13.X and 1.14.Y but without success.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Hi, thank you for opening the GH issue. Unfortunately, without some steps to reproduce the issue we won't be able to help you. I would suggest to keep trying with a more recent version to see if the issue gets fixed.
