### ISSUE TITLE
CES fast and standard queues - Improvements

### ISSUE THREAD

**Issue by dlapcevic** [cilium/cilium#34801]
Improvements to https://github.com/cilium/cilium/pull/34199

1. Concurrency
a) Refactor - make workqueues thread safe (read, write)
b) Testing - Find out how we can test it
2. Consider adding default namespaces that are added to priority namespaces (e.g. kube-system)
3. Add comments with a "graph" of how the queues are used
4. Add tests that verify that CES name is generated without using namespace.
5. Block on the initial sync of namespaces `job.OneShot("proc-ns-events"` in /endpointslice.go

**Comment by dlapcevic** [comment]
cc @Kaczyniec @ovidiutirla

**Comment by marseel** [comment]
Some more followups from https://github.com/cilium/cilium/pull/34199
- Block on initial sync from namespaces to properly choose priority namespaces for CES updates on operator restarts
- I would try to make it more "fair" so priority namespace can't starve non-prioirty namespaces, something like (pseudocode):
```
select {
case el := <-priorityQueue:
process(el)
case el := <-slowQueue:
process(el)
}
```
This would still give at least half of qps to priority namespace, while ensuring that non-priority namespaces don't starve.

**Comment by dlapcevic** [comment]
Thanks Marcel. I updated the description, to add points about blocking namespace sync on startup and new tests that will verify that CES name isn't generated using namespace.

About making the priority fair I think we could discuss it more.
I think it boils down to what the user cares more about.
To me it makes sense that the standard queue can be starved because of the fast queue over a short period.
If it's getting to a longer period, then we have a bigger problems anyway -- queues growing faster than being processed and long delays regardless of priority.
