### ISSUE TITLE
CI: some tests remove resources before logs are gathered

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3481]
Within Ginkgo, there is the notion of `Context`, which allows subsets of tests to occur within a `Describe`. For instance, Within a `Describe`, one can have the following:

- Describe
    - BeforeEach (for each `It` within Describe)
    - AfterEach (for each `It` within Describe)
    - JustAfterEach
    - AfterFailed
    - It
    - Context
        - BeforeEach (for each `It` within Context)
        - AfterEach (for each `It` within Context)
            - It 

For the 'It' within the context, the following would occur if a test fails:

BeforeEach (for each `It` within Describe) -->  BeforeEach (for each `It` within Context) --> It --> AfterEach (for each `It` within Context) --> JustAfterEach --> AfterFailed --> AfterEach (for each `It` within Describe) 
  

This means that if within the `AfterEach` for the `Context`, if we delete any resources provisioned within the `Context`, but gather logs in the `Describe`'s `AfterEach`, we will have no resources to analyze. This can be solved by moving the `JustAfterEach` and `AfterFailed` to be within each `Context`, and if a `Describe` has a `Context` within it, ensuring that all `It`s are covered by a `Context` which contains `AfterEach` and `AfterFailed` within it. 

Tests that need fixing:
- [ ] `test/runtime/connectivity.go:RuntimeValidatedConnectivityTest`

TODO: need to go through all tests and see what are affected by this.

**Comment by eloycoto** [comment]
I think that the JustAfterEach will run just before all other context, but let me check and I'll come back to you. 

Regards

**Comment by eloycoto** [comment]
@ianvernon I've just check and the problem exits, I'll try to get the solution in the night. It'll no difficult to solve.

**Comment by eloycoto** [comment]
Hi @ianvernon made a PR, good catch
