### ISSUE TITLE
cilium-cni is not friendly enough to support ntp

### ISSUE THREAD

**Issue by fzu-huang** [cilium/cilium#34816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When ntp 4.2.6p5 obtains the local network card address, there is no problem in obtaining the ipv4 address through ioctl. However, there is a problem in obtaining the ipv6 address when reading `/proc/net/if_inet6`, resulting in no monitoring of the ipv6 address: `1:123`, so ntpq-pn access `::1: 123` failed. The specific reason is that the code uses char entry [62] to read a line in `/proc/net/if_inet6 `such as:
`fe80000000000000883a34fffed626cb 2f6c 40 20 80 Ixcb22cOff2eb87` If the length exceeds 62, it will fail and cause the traversal of ipv6 addresses to be interrupted, resulting in many ipv6 addresses that are not monitored.

This problem will occur if the name of the Ixc network card on the node is relatively long and the Ixc network card is located in front of the lo network card.

![QQ_1726025619874](https://github.com/user-attachments/assets/7d7be95b-b2a5-48fc-bbe5-d6b46a5a0a06)

### How can we reproduce the issue?

This problem will occur if the name of the Ixc network card on the node is relatively long and the Ixc network card is located in front of the lo network card.

### Cilium Version

since cilium 1.12 , but I think even newest cilium still has this problem

### Kernel Version

5.4.119-19.0009.32

### Kubernetes Version

v1.22

### Anything else?

In fact, the maintainers of ntp should take the initiative to fix this problem, but the current update progress of ntp is very slow. Considering the wide range of use of ntp, it would be very helpful if cilium could provide an option to control the length of the network card name.

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
> The specific reason is that the code uses char entry [62] to read a line in /proc/net/if_inet6 such as:
fe80000000000000883a34fffed626cb 2f6c 40 20 80 Ixcb22cOff2eb87 If the length exceeds 62, it will fail and cause the traversal of ipv6 addresses to be interrupted, resulting in many ipv6 addresses that are not monitored.

> In fact, the maintainers of ntp should take the initiative to fix this problem, but the current update progress of ntp is very slow.

I agree, seems pretty clear this is an issue with ntpd. The current length of of the interface names are 15 bytes, which is the max allowed by the kernel. I do not find update speed of the ntpd project a compelling argument to patch every piece of software that uses long yet valid network interface names.
