### ISSUE TITLE
Egress policy works for RFC1918 gateway, not non-RFC1918

### ISSUE THREAD

**Issue by denefoster** [cilium/cilium#34814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

All my nodes have two interfaces, eno1 == 192.168.1.0/24 and eno1.205 == 205.233.128.0/24

If I set an egress gateway policy with an egressIP to the RFC1918 address it behaves as expected. 

If I set the same policy egressIP to the 205.233.128.0/24 address I get unexpected behaviour, no MASQ rule gets created and traffic exists the pod without getting masqueraded at all, it's native 10.0.0.0/8 address is seen on the wire.

### How can we reproduce the issue?

Follow the egress gateway documentation at https://docs.cilium.io/en/stable/network/egress-gateway/egress-gateway/.

The non-working egress policy looks like:
```apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: egress-sample
spec:
  selectors:
  - podSelector:
      matchLabels:
        io.kubernetes.pod.namespace: egresstest

  destinationCIDRs:
  - "34.160.111.145/32"

  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: cn3

    egressIP: 205.233.128.12
   ```

While changing the egressIP: to 192.168.1.50 works as per the documentation.

### Cilium Version

cilium-cli: v0.16.16 compiled with go1.23.0 on darwin/arm64
cilium image (default): v1.16.0
cilium image (stable): v1.16.1
cilium image (running): 1.16.1

### Kernel Version

Linux cn1 6.6.48-flatcar #1 SMP PREEMPT_DYNAMIC Wed Sep  4 15:49:08 -00 2024 x86_64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz GenuineIntel GNU/Linux

### Kubernetes Version

Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.4+k0s

### Sysdump

[cilium-sysdump-20240911-140300.zip](https://github.com/user-attachments/files/16956857/cilium-sysdump-20240911-140300.zip)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
>eno1.205

This makes me think you're actually hitting the same problem as described in https://github.com/cilium/cilium/pull/34220 (at least, you *should* be affected :)). Worth a try to rename that interface (to remove the `dot`), and then apply your CEGP again?

https://github.com/cilium/cilium/pull/34220#issuecomment-2349223328 describes the planned resolution - for v1.16, you'd just need to wait for the next patch release.

**Comment by denefoster** [comment]
Can confirm renaming without the dot fixes it, feel free to close. Thank you!
