### ISSUE TITLE
spec.loadBalancerSourceRanges on LoadBalancer service is not enforced

### ISSUE THREAD

**Issue by judge-red** [cilium/cilium#34903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

According to the following page, it's possible to specify the field `spec.loadBalancerSourceRanges` in `LoadBalancer` services in order for Cilium to enforce an IP range allowlist even if the infrastructure (i.e. external load balancer) doesn't support it. That's awesome - except, it doesn't seem to work at all. I specified an IP range of `1.1.1.1/32`, an IP which I'm definitely not using, but I can still access the workload behind that service.

https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#loadbalancer-source-ranges-checks

The only requirement seems to be that 

### How can we reproduce the issue?

1. Install Cilium, set `kube-proxy-replacement` / `kubeProxyReplacement` to `true` (and make sure there's no kube-proxy running in the cluster)
2. Create a `LoadBalancer` service with `spec.loadBalancerSourceRanges: [1.1.1.1/32]` and some workload behind it to answer requests
3. Access the load balancer and notice you don't get blocked

### Cilium Version

```
cilium-cli: v0.16.16 compiled with go1.23.0 on darwin/arm64
cilium image (default): v1.16.0
cilium image (stable): v1.16.1
cilium image (running): 1.15.8
```

### Kernel Version

```
Linux hostname-redacted 5.15.0-121-generic #131-Ubuntu SMP Fri Aug 9 08:29:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.4
```

### Sysdump

https://drive.switch.ch/index.php/s/eo9Q5M7yLSO9Nng

### Relevant log output

```shell
None found
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judge-red** [comment]
It seems that this issue goes back to #17440. The problem is that the suggested solution doesn't work. The nodeports (together with all nodes, of course) are the backend members in the OpenStack loadbalancer, so they can't be disabled.

**Comment by borkmann** [comment]
Which IP are you accessing, the loadbalancer IP or the nodeport IP? Does the loadBalancerSourceRanges work with loadbalancer IP?

**Comment by judge-red** [comment]
The loadbalancer IP.  No.

**Comment by borkmann** [comment]
I just tried it and it is working as expected for me:

```
apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 192.168.2.0/24
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
```
Services:
```
# ./cilium-dbg/cilium-dbg service list
ID   Frontend                  Service Type   Backend                                
[...]                               
12   10.96.87.74:80/TCP        ClusterIP      1 => 1.1.1.1:80/TCP (active)           
13   192.168.1.119:32197/TCP   NodePort       1 => 1.1.1.1:80/TCP (active)           
14   0.0.0.0:32197/TCP         NodePort       1 => 1.1.1.1:80/TCP (active)           
15   10.0.100.0:80/TCP         LoadBalancer   1 => 1.1.1.1:80/TCP (active)           
```
BPF view:
```
# ./cilium-dbg/cilium-dbg bpf lb list
SERVICE ADDRESS               BACKEND ADDRESS (REVNAT_ID) (SLOT)
10.0.100.0:80/TCP (1)         1.1.1.1:80/TCP (15) (1)                                  
192.168.1.119:32197/TCP (0)   0.0.0.0:0 (13) (0) [NodePort]                            
10.96.0.10:9153/TCP (0)       0.0.0.0:0 (4) (0) [ClusterIP, non-routable]              
10.96.0.10:53/TCP (0)         0.0.0.0:0 (3) (0) [ClusterIP, non-routable]              
10.96.87.74:80/TCP (1)        1.1.1.1:80/TCP (12) (1)                                  
10.96.0.10:53/UDP (0)         0.0.0.0:0 (2) (0) [ClusterIP, non-routable]              
192.168.1.119:32197/TCP (1)   1.1.1.1:80/TCP (13) (1)                                  
10.96.0.1:443/TCP (0)         0.0.0.0:0 (1) (0) [ClusterIP, non-routable]              
10.96.87.74:80/TCP (0)        0.0.0.0:0 (12) (0) [ClusterIP, non-routable]             
10.96.0.1:443/TCP (1)         192.168.1.119:6443/TCP (1) (1)                           
0.0.0.0:32197/TCP (1)         1.1.1.1:80/TCP (14) (1)                                  
10.0.100.0:80/TCP (0)         0.0.0.0:0 (15) (0) [LoadBalancer, check source-range]    
0.0.0.0:32197/TCP (0)         0.0.0.0:0 (14) (0) [NodePort, non-routable]  
```
(the check source-range flag is set)
```
# ./cilium-dbg/cilium-dbg bpf lb list --source-ranges
SOURCE RANGE (REVNAT_ID)   
192.168.2.0/24 (15)            
```
From a node outside the cluster with source IP of 192.168.1.114:
```
# curl --verbose 10.0.100.0:80
*   Trying 10.0.100.0:80...
```
The traffic is dropped correctly.

The same node to the NodePort address:
```
# curl --verbose 192.168.1.119:31328
*   Trying 192.168.1.119:31328...
* Connected to 192.168.1.119 (192.168.1.119) port 31328 (#0)
> GET / HTTP/1.1
> Host: 192.168.1.119:31328
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
```
Traffic goes through as expected.

If I change the loadBalancerSourceRanges to allow 192.168.1.0/24 then traffic also goes through for the LoadBalancer service.

This is also what the doc mentions: https://docs.cilium.io/en/v1.17.0-pre.1/network/kubernetes/kubeproxy-free/#loadbalancer-source-ranges-checks

If the NodePort allocation should be disabled for LoadBalancer service, then https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-nodeport-allocation can be followed.

I'm closing for now since it seems to be working as expected. Feel free to reopen if this does not match on your side.

**Comment by borkmann** [comment]
Ok, makes sense, I'll post a fix tomorrow.

**Comment by borkmann** [comment]
I've used latest main branch of Cilium. Nevertheless, I think having this option as proposed makes sense as I've seen this ask also elsewhere. But yes, if you could try latest Cilium, that would be great to confirm it works for you.

**Comment by judge-red** [comment]
Uh, how can I deploy a version that includes the patch?

**Comment by borkmann** [comment]
Are you doing the curl from within the K8s cluster or from an external node which is outside the cluster? The enforcement happens for external traffic which arrives into the cluster.

**Comment by judge-red** [comment]
From my laptop, which is not part of the Kubernetes cluster or the Cilium mesh/whatever.

**Comment by borkmann** [comment]
This goes through GKE, right? I wonder if they do DNAT and forward to the NodePort vip:ports.. could you do tcpdump to see what kind of traffic arrives on the k8s node?

**Comment by judge-red** [comment]
No, on-prem OpenStack. But yea, Openstack with the OVN LB provider does indeed use DNAT to forward the traffic.

**Comment by borkmann** [comment]
PR got merged, so you could use the image from Cilium main branch: 

https://github.com/cilium/cilium?tab=readme-ov-file#development
