### ISSUE TITLE
next reader: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by bernardgut** [cilium/cilium#34939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Long running websocket connections unexpectedly get closed after a while.

I am trying to copy 100TB of data from a PVC to another. For this I decided to `k exec ... -- bash` into a pod and run `rsync...`. The connection between my terminal and my pod invariably gets closed after a while with :

```
/ # rsync -ah --info=progress2 /hdd-1/media/* /opt-pvc/
          1.57T  28%   92.60MB/s   11:44:01  E0917 22:36:35.883489 1700160 v2.go:129] "Unhandled Error" err="next reader: websocket: close 1006 (abnormal closure): unexpected EOF"
                                                                                                                                                                                   E0917 22:36:35.883493 1700160 v2.go:150] "Unhandled Error" err="next reader: websocket: close 1006 (abnormal closure): unexpected EOF"
                                                                                                                            warning: couldn't attach to pod/nsenter-po0a9r, falling back to streaming logs: error reading from error stream: next reader: websocket: close 1006 (abnormal closure): unexpected EOF
Opening in existing browser session.
E0917 22:36:38.826425 1700160 websocket.go:499] Websocket Ping failed: use of closed network connection
error: get-token: authentication error: authcode-browser error: authentication error: authorization code flow error: oauth2 error: authorization error: authorization error: context deadline exceeded
Unable to connect to the server: getting credentials: exec: executable kubectl failed with exit code 1
Opening in existing browser session.
error: get-token: authentication error: authcode-browser error: authentication error: authorization code flow error: oauth2 error: authorization error: authorization error: context deadline exceeded
Unable to connect to the server: getting credentials: exec: executable kubectl failed with exit code 1
```

Now I know I could just create a Job to do this and let it run. But I want to see the logs in my terminal while this runs for days. Now I am not sure it is a 100% Cilium issue but it looks like the websocket timeouts even though the backend is streaming info to my terminal about what is being copied. Is there an annotation I can add somewhere so that the websocket doesn't get killed by Cilium ? (Assuming that is the issue)

thanks 
B.

### How can we reproduce the issue?

1. Install Cilium
2. Run `k exec ...  -- bash` in a pod and run some long task
3. wait until you get 1006 error

### Cilium Version

1.16.1

### Kernel Version

6.6.43-talos

### Kubernetes Version

1.30.5

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gustysap** [comment]
I have same issue, but not sure its because cilium or my api gateway proxy

**Comment by youngnick** [comment]
For issues like this, the data flow really matters. For each of you, do you have network policy covering this traffic? Does it go through Envoy for routing or observability?

@bernardgut, as you say, there are a lot of reasons why these connections might be being killed, and not all of them are Cilium related.
