### ISSUE TITLE
CI: Image CI Build

### ISSUE THREAD

**Issue by jsoref** [cilium/cilium#34947]
## CI failure

> [Image CI Build](https://github.com/check-spelling-sandbox/cilium/actions/runs/10925110001/workflow)
Error when evaluating 'runs-on' for job 'build-and-push-prs'. .github/workflows/build-images-ci.yaml (Line: 39, Col: 14): Unexpected value ''

https://github.com/check-spelling-sandbox/cilium/actions/runs/10925110001

---

The fix is to add an `if: ${{ vars.GH_RUNNER_EXTRA_POWER }}`

**Comment by aanm** [comment]
Fixed by https://github.com/cilium/cilium/pull/35267
