### ISSUE TITLE
Add `cilium version` to bugtool

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3497]

**Comment by ianvernon** [comment]
Cilium is compiled as a static binary; how would this be helpful? We'd have to get the version of go that built Cilium, a-la https://dave.cheney.net/2017/06/20/how-to-find-out-which-go-version-built-your-binary . I don't think we need this.

**Comment by joestringer** [comment]
Hmm, good point. Perhaps the cilium version contains the relavant information already.

**Comment by ianvernon** [comment]
`cilium version` is already part of `cilium debuginfo`:

```
vagrant@k8s1:~/cilium-bugtool-20180403-182429.654+0000-UTC-269206681/cmd$ head -n 7 cilium-debuginfo.md 
```  

# Cilium debug information

#### Cilium version

```
1.0.0-rc9 0a358b705 2018-04-03T10:58:57-07:00 go version go1.9 linux/amd64
```

**Comment by ianvernon** [comment]
@joestringer can we close since we are already gathering output of `cilium debuginfo` in bugtool?

**Comment by ianvernon** [comment]
Discussed offline, closing.
