### ISSUE TITLE
single stack ipv6 causes panic

### ISSUE THREAD

**Issue by bobloblian** [cilium/cilium#34997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Installing kubernetes for the first time, via kubeadm as per the kubernetes.io website; using Debian testing on a virtualbox VM.  My environment is ipv4 capable, but only for network hosts where I manually configure it, by default things are ipv6 only.

Following the cilium install docs, I used the ciliumcli install method, not much of anything worked there until I found I needed to enable ipv6, so this ended up being my install command:

cilium install --version 1.16.1 --helm-set ipv6.enabled=true

After I did that, things got a lot farther, but the cilium-agent pod was still refusing to install and I was able to identify the problem in the logs:

Allocating identities between range" cluster-id=0 max=65535 min=256 subsys=identity-cache
stderr F panic: runtime error: index out of range [3] with length 0

Searching about this error, I found the following issue was opened:

https://github.com/cilium/cilium/issues/30746

Which describes pretty much the exact same log entries.  Reading that issue, I found that while we had different environments, we did seem to share the common denominator of no ipv4 addresses.  Chasing links on that issue down, it seems that a patch was written and published, however it seems I have run into it again.

After some time it occurred to add an ipv4 address to each node's interface, and after I did that cilium installed and reports no errors.  This suggests, to me at least, that cilium does not support an ipv4-less environment, though I did read a few places where it said it should.

It was suggested to me on slack that cilium shouldn't panic, and given that it seems from what I have read about ipv6 and cilium that an ipv6-only environment should be supported, it seems the responsible thing to do is open an issue to report this.

Thanks for reading.

### How can we reproduce the issue?

Presumably running a cilium install command on an ipv6-only host will produce the error.

### Cilium Version

cilium-cli: v0.16.18 compiled with go1.23.1 on linux/amd64
cilium image (default): v1.16.1
cilium image (stable): v1.16.1
cilium image (running): 1.16.1

### Kernel Version

Linux kube0 6.10.9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.9-1 (2024-09-08) x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.0

### Regression

Possibly, since it seems a fix was previously published.  However, I did not test any older versions.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by netops2devops** [comment]
Hi! I am running Cilium 1.16.1 in a pure IPv6 only environment and it's been holding up just fine. If your nodes are IPv6 only you will need to install Cilium explicitly with IPv4 disabled. Please note that by default Cilium uses `routingMode=tunnel` but if you are running in a pure IPv6 only environment as of now due to #17240 the only way to make Cilium work with pure IPv6 is by using `routingMode=native` for which you will need to provide a few more config bits all of which I am listing below. All the best!  

Documentation about native routing https://docs.cilium.io/en/stable/network/concepts/routing/#routing
```
ipv4.enabled=false
ipv6.enabled=true 
routingMode=native
set autodirectnoderoutes=true
ipv6NativeRoutingCIDR= 
ipam.operator.clusterPoolIPv6PodCIDRList=
k8s.requireIPv6PodCIDR=
```

**Comment by cade-thomas** [comment]
> Hi! I am running Cilium 1.16.1 in a pure IPv6 only environment and it's been holding up just fine. If your nodes are IPv6 only you will need to install Cilium explicitly with IPv4 disabled. Please note that by default Cilium uses `routingMode=tunnel` but if you are running in a pure IPv6 only environment as of now due to [#17240](https://github.com/cilium/cilium/issues/17240) the only way to make Cilium work with pure IPv6 is by using `routingMode=native` for which you will need to provide a few more config bits all of which I am listing below. All the best!
> 
> Documentation about native routing https://docs.cilium.io/en/stable/network/concepts/routing/#routing
> 
> ```
> ipv4.enabled=false
> ipv6.enabled=true 
> routingMode=native
> set autodirectnoderoutes=true
> ipv6NativeRoutingCIDR= 
> ipam.operator.clusterPoolIPv6PodCIDRList=
> k8s.requireIPv6PodCIDR=
> ```

New to ipv6 so im not 100% sure what to set
ipv6NativeRoutingCIDR= 
ipam.operator.clusterPoolIPv6PodCIDRList=
to. 
I have two different IPv6 subnets set for rke2 service and cluster CIDRs one is a /112 and one is a /56

**Comment by bobloblian** [comment]
As best as I can tell, they should both be set to the same value you used for the podSubnet when you initialized the cluster, or the equivalent depending on your method.

**Comment by netops2devops** [comment]
If you are running Cilium 1.18.x which recently just came out running single stack IPv6 cluster is much easier now. You no longer need native routing and can use the default tunnel mode. You will need to provide helm values as shown below 

```
helm install cilium cilium/cilium -n kube-system \
      --version 1.18.0 \
      --set ipv6.enabled=true \
      --set ipv4.enabled=false \
      --set underlayProtocol=ipv6
```
