### ISSUE TITLE
Cilium BGP stops announcing shared IP

### ISSUE THREAD

**Issue by usiegl00** [cilium/cilium#35018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

There is a bug when a service with a sharing key gets deleted. Cilium stops announcing the IP even if there are other LoadBalancer services that are still using it.

### How can we reproduce the issue?

1. Create 2 services that share an IP by using the `lbipam.cilium.io/sharing-key` annotation.
2. Announce those services via bgp.
3. Delete one of the services.
4. See that the announcement of the ip was removed.

### Cilium Version

1.15.8

### Kernel Version

6.10.7

### Kubernetes Version

1.28.13

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rastislavs** [comment]
The current BGP service reconciler implementation relies on 1:1 mapping between VIPs and services, this needs to be fixed in both BGPv1 & BGPv2 reconciler logic.
