### ISSUE TITLE
Regression in v1.16.X: a reply to an outgoing connection from a pod is registered as new incoming on host level

### ISSUE THREAD

**Issue by Cajga** [cilium/cilium#35056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When our pods initiate an outgoing connection to an external host the reply (with the syn-ack) is registered as a new incoming connection into the ct table (and would be dropped if we would not be in AUDIT mode).

Here is the `cilium-dbg monitor` of the traffic (it is a monitoring traffic that does an HTTP GET):
```
# cilium-dbg monitor |grep 172.27.210.23
Listening for events on 56 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
time="2024-09-26T14:45:06Z" level=info msg="Initializing dissection cache..." subsys=monitor
Policy verdict log: flow 0x8e7c81d1 local EP ID 3807, remote ID 16777226, proto 6, egress, action allow, auth: disabled, match L3-Only, 100.80.3.228:36946 -> 172.27.210.23:443 tcp SYN
-> stack flow 0x8e7c81d1 , identity 49712->16777226 state new ifindex 0 orig-ip 0.0.0.0: 100.80.3.228:36946 -> 172.27.210.23:443 tcp SYN
Policy verdict log: flow 0x0 local EP ID 594, remote ID 16777226, proto 6, ingress, action audit, auth: disabled, match none, 172.27.210.23:443 -> 172.27.50.155:36946 tcp SYN, ACK
-> endpoint 3807 flow 0x0 , identity 16777226->49712 state reply ifindex lxc7fb4017156e7 orig-ip 172.27.210.23: 172.27.210.23:443 -> 100.80.3.228:36946 tcp SYN, ACK
-> stack flow 0x8e7c81d1 , identity 49712->16777226 state established ifindex 0 orig-ip 0.0.0.0: 100.80.3.228:36946 -> 172.27.210.23:443 tcp ACK
-> stack flow 0x8e7c81d1 , identity 49712->16777226 state established ifindex 0 orig-ip 0.0.0.0: 100.80.3.228:36946 -> 172.27.210.23:443 tcp ACK
-> endpoint 3807 flow 0x0 , identity 16777226->49712 state reply ifindex lxc7fb4017156e7 orig-ip 172.27.210.23: 172.27.210.23:443 -> 100.80.3.228:36946 tcp ACK
-> endpoint 3807 flow 0x0 , identity 16777226->49712 state reply ifindex lxc7fb4017156e7 orig-ip 172.27.210.23: 172.27.210.23:443 -> 100.80.3.228:36946 tcp ACK, FIN
-> stack flow 0x8e7c81d1 , identity 49712->16777226 state established ifindex 0 orig-ip 0.0.0.0: 100.80.3.228:36946 -> 172.27.210.23:443 tcp ACK, FIN
```

The same traffic registers two entries in the ct map (the second is a TCP IN which is clearly wrong):
```
# cilium-dbg bpf ct list global |grep 100.80.3.228:36946
TCP OUT 100.80.3.228:36946 -> 172.27.210.23:443 expires=3026763 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=3026753 TxFlagsSeen=0x1b LastTxReport=3026753 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=49712 IfIndex=0 BackendID=0 
# cilium-dbg bpf ct list global |grep 172.27.50.155:36946
TCP IN 172.27.210.23:443 -> 172.27.50.155:36946 expires=3034753 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=3026753 TxFlagsSeen=0x00 LastTxReport=0 Flags=0x0011 [ RxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=16777226 IfIndex=0 BackendID=0 
```

While the "TCP OUT" entry disappears (I guess cleaned up as it finished properly), we have many "TCP IN" hanging there:
```
# cilium-dbg bpf ct list global|grep "^TCP IN 172.27.210.23:443"|wc -l
2368
```

We have cilium in default-deny and audit is enabled:
```
$ cilium config view |egrep  -e enable-policy -e policy-audit-mode
enable-policy                                     always
policy-audit-mode                                 true
```

Each and every traffic produces an entry in the audit log (where it says that the syn-ack packet is not a reply):
```
{
  "flow": {
    "time": "2024-09-26T12:17:05.377566426Z",
    "verdict": "AUDIT",
    "ethernet": {
      "source": "MAC1",
      "destination": "MAC2"
    },
    "IP": {
      "source": "172.27.210.23",
      "destination": "172.27.50.155",
      "ipVersion": "IPv4"
    },
    "l4": {
      "TCP": {
        "source_port": 443,
        "destination_port": 36582,
        "flags": {
          "SYN": true,
          "ACK": true
        }
      }
    },
    "source": {
      "identity": 16777226
    },
    "destination": {
      "identity": 1
    },
    "Type": "L3_L4",
    "node_name": "NODENAME",
    "event_type": {
      "type": 5
    },
    "is_reply": false,
    "Summary": "TCP Flags: SYN, ACK"
  },
  "node_name": "NODENAME",
  "time": "2024-09-26T12:17:05.377566426Z"
}
```

### How can we reproduce the issue?

1. Install cilium with cilium cli (note the `hostFirewall.enabled=true`):
```
cilium install --version=v1.16.0 --helm-set cni.exclusive=false --helm-set ipam.mode=kubernetes --helm-set identityAllocationMode=crd --helm-set tunnelProtocol=geneve --helm-set cni.chainingMode=portmap --helm-set prometheus.enabled=true --helm-set operator.prometheus.enabled=true --helm-set hostFirewall.enabled=true --helm-set operator.replicas=2 --helm-set policyAuditMode=true --helm-set policyEnforcementMode=always --helm-set hubble.enabled=true --helm-set hubble.export.static.enabled=true --helm-set hubble.export.fileMaxSizeMb=100 --helm-set hubble.export.static.filePath=/var/run/cilium/hubble/events.log --helm-set hubble.export.static.allowList[0]='\{"verdict":["DROPPED"\,"ERROR"\,"AUDIT"]\}' --helm-set hubble.export.static.fieldMask="{time,source.identity,source.namespace,source.pod_name,destination.identity,destination.namespace,destination.pod_name,source_service,destination_service,l4,IP,ethernet,l7,Type,node_name,is_reply,event_type,verdict,Summary}"
```

2. enable hubble manually:
```
cilium hubble enable
```

3. create a pod
4. use curl and target a node outside of the cluster

### Cilium Version

```
$ cilium version
cilium-cli: v0.16.13 compiled with go1.22.5 on linux/amd64
cilium image (default): v1.15.6
cilium image (stable): v1.16.2
cilium image (running): 1.16.0
```

### Kernel Version

```
# uname -a
Linux NODENAME 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1-eks-e564799
```

NOTE: we are using EKS Anywhere that runs on our own HW

### Regression

**seems to be a regression as the problem is not there with v1.15.9**

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Cajga** [comment]
I can confirm that the same is happening on v1.16.2.
Two AUDIT log entries are generated for a single curl request:

The egress from the pod:
{code}
{
  "flow": {
    "time": "2024-09-27T09:21:01.533632804Z",
    "verdict": "AUDIT",
    "ethernet": {
      "source": "MAC1",
      "destination": "MAC2"
    },
    "IP": {
      "source": "100.82.2.211",
      "destination": "172.27.210.22",
      "ipVersion": "IPv4"
    },
    "l4": {
      "TCP": {
        "source_port": 49764,
        "destination_port": 443,
        "flags": {
          "SYN": true
        }
      }
    },
    "source": {
      "identity": 9730,
      "namespace": "default",
      "pod_name": "curly"
    },
    "destination": {
      "identity": 2
    },
    "Type": "L3_L4",
    "node_name": "NODENAME",
    "event_type": {
      "type": 5
    },
    "is_reply": false,
    "Summary": "TCP Flags: SYN"
  },
  "node_name": "NODENAME",
  "time": "2024-09-27T09:21:01.533632804Z"
}
{code}

And the "false ingress" for the host:
{code}
{
  "flow": {
    "time": "2024-09-27T09:21:01.533876105Z",
    "verdict": "AUDIT",
    "ethernet": {
      "source": "MAC1",
      "destination": "MAC2"
    },
    "IP": {
      "source": "172.27.210.22",
      "destination": "172.27.51.133",
      "ipVersion": "IPv4"
    },
    "l4": {
      "TCP": {
        "source_port": 443,
        "destination_port": 49764,
        "flags": {
          "SYN": true,
          "ACK": true
        }
      }
    },
    "source": {
      "identity": 2
    },
    "destination": {
      "identity": 1
    },
    "Type": "L3_L4",
    "node_name": "NODENAME",
    "event_type": {
      "type": 5
    },
    "is_reply": false,
    "Summary": "TCP Flags: SYN, ACK"
  },
  "node_name": "NODENAME",
  "time": "2024-09-27T09:21:01.533876105Z"
}
{code}

**Comment by Cajga** [comment]
Ohh, this seems to be a regression as it is not there with cilium v1.15.9!

```
# cilium_v0.16.18 status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

Deployment             cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
DaemonSet              cilium             Desired: 3, Ready: 3/3, Available: 3/3
Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium             Running: 3
                       hubble-relay       Running: 1
                       cilium-operator    Running: 2
Cluster Pods:          22/22 managed by Cilium
Helm chart version:    
Image versions         cilium             quay.io/cilium/cilium:v1.15.9@sha256:c2a4c57a6baf758e975fbefbf638476906d1bb0c970e9547d216d9ea7b6471e3: 3
                       hubble-relay       quay.io/cilium/hubble-relay:v1.15.9@sha256:421afd9f4e46a7b9834f0542ceca6e8652ec0598982126dc2dd1dcf0dd690631: 1
                       cilium-operator    quay.io/cilium/operator-generic:v1.15.9@sha256:0ec30b4df0d097aedcbcb41748f10ce397f9656c128bea7e227b6bfd820f6d76: 2
```

With this version, I only receive an audit entry for the pod egress traffic. No false ingress on the host level!

One diff apart from the version is that v1.15.9 is using `Envoy DaemonSet:    disabled (using embedded mode)` while with v1.16.2 we use `Envoy DaemonSet:    OK` as that is the default...

**Comment by julianwiedmann** [comment]
From a quick glance, I believe what you're seeing is
1. a `TCP OUT` CT entry that's created when the first packet exits the pod.
2. (two NAT entries (SNAT + RevSNAT) for this connection, created when the first packet exits the node on some native interface)
3. a `TCP IN` CT entry that's created by the HostFW code, when the first reply enters the node on some native interface.

The `TCP IN` entry is unexpected, as the reply should be RevSNATed first. And from then on the datapath code should understand that the packet is in fact **not** destined for the host (but rather some pod), and thus skip the HostFW logic.

So one thing you can verify is whether there is a NAT entry that matches the `TCP OUT` entry and translates the SRC to `172.27.50.155:36946`. And then whether a NAT entry exist for `172.27.210.23:443 -> 172.27.50.155:36946` that would translate the DST back to `100.80.3.228:36946`.

**Comment by Cajga** [comment]
@julianwiedmann thank you for looking into this. May I ask you to elaborate a bit on how can I check this?

I tried:
```
# cilium-dbg bpf nat list
Error: Unable to open /sys/fs/bpf/tc/globals/cilium_snat_v4_external: loading pinned map /sys/fs/bpf/tc/globals/cilium_snat_v4_external: no such file or directory
```

I guess this is because we use it **with** kubeproxy? So I also looked into the iptables config but also could not find the relevant entries in the NAT table (also not with v1.15.9 where everything works as expected).

**Comment by julianwiedmann** [comment]
Ah, so netfilter-based masquerading then :). Note that without attaching a sysdump and/or detailed cilium-config, you're limiting yourself quite a bit here. Makes it difficult for anyone interested to jump in.

That changes the story to
1. a TCP OUT CT entry that's created when the first packet exits the pod.
2. [... packet passes through netfilter, gets masqueraded ...]
3. packet passes through `to-netdev` @ native interface, the HostFW should be creating a TCP OUT CT entry to track the host-level connection and match replies. Apparently that's not the case for you.
4. consequently when the first reply enters the node, the HostFW code in `from-netdev` @ native interface creates an unexpected TCP IN CT entry (instead of matching against the TCP OUT entry created by `to-netdev`).

Hope that helps, and this matches what you see in your cluster. Then it's just a matter of understanding why (3.) doesn't happen.

**Comment by Cajga** [comment]
Sry. for the delay but we had to downgrade to 1.15.9 to avoid issues with policies. I will try to reproduce this in our playground env and report back by end of next week.

**Comment by michaelsovik** [comment]
I have similar issues, what I found is when I set up a brand new Kubernetes setup and install 1.16 I get this behavior, then if I downgrade to 1.15 or install that version first and then upgrade to 1.16 it behaves normally.

**Comment by Cajga** [comment]
@julianwiedmann,

I reproduced the problem with `1.16.3` with the following steps:
* install cilium on a brand new k8s cluster: `cilium_v0.16.19 install --version=v1.16.3 --helm-set cni.exclusive=false --helm-set ipam.mode=kubernetes --helm-set identityAllocationMode=crd --helm-set tunnelProtocol=geneve --helm-set cni.chainingMode=portmap --helm-set hostFirewall.enabled=true --helm-set operator.replicas=2 --helm-set policyAuditMode=true --helm-set policyEnforcementMode=always --helm-set hubble.enabled=true`
* start a pod using curly: `kubectl run -it --rm --image=curlimages/curl curly -- /bin/sh`
* do a `curl` call from the pod to one of the external destinations: `curl http://192.168.1.12`

Check hubble flow logs (see the second AUDITED line with the SYN,ACK TCP flags):
```
# hubble observe flows -f |grep '192.168.1.12'
Oct 20 13:01:30.093: default/curly:46694 (ID:8439) -> 192.168.1.12:80 (world) policy-verdict:none EGRESS AUDITED (TCP Flags: SYN)
Oct 20 13:01:30.093: default/curly:46694 (ID:8439) -> 192.168.1.12:80 (world) to-stack FORWARDED (TCP Flags: SYN)
Oct 20 13:01:30.094: 192.168.1.12:80 (world) -> 172.27.51.134:46694 (host) policy-verdict:none INGRESS AUDITED (TCP Flags: SYN, ACK)
Oct 20 13:01:30.094: default/curly:46694 (ID:8439) <- 192.168.1.12:80 (world) to-endpoint FORWARDED (TCP Flags: SYN, ACK)
Oct 20 13:01:30.094: default/curly:46694 (ID:8439) -> 192.168.1.12:80 (world) to-stack FORWARDED (TCP Flags: ACK)
Oct 20 13:01:30.094: default/curly:46694 (ID:8439) -> 192.168.1.12:80 (world) to-stack FORWARDED (TCP Flags: ACK, PSH)
Oct 20 13:01:30.095: default/curly:46694 (ID:8439) <- 192.168.1.12:80 (world) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Oct 20 13:01:30.095: default/curly:46694 (ID:8439) -> 192.168.1.12:80 (world) to-stack FORWARDED (TCP Flags: ACK, FIN)
Oct 20 13:01:30.095: default/curly:46694 (ID:8439) <- 192.168.1.12:80 (world) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Oct 20 13:01:30.095: default/curly:46694 (ID:8439) -> 192.168.1.12:80 (world) to-stack FORWARDED (TCP Flags: ACK)
```

As multiple people wrote that a sysdump contains "confidential" information I cannot share it here but here is the Cilium config-map:
```
# kubectl get cm -n kube-system cilium-config -o yaml
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: "false"
  bpf-events-drop-enabled: "true"
  bpf-events-policy-verdict-enabled: "true"
  bpf-events-trace-enabled: "true"
  bpf-lb-acceleration: disabled
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-sock: "false"
  bpf-lb-sock-terminate-pod-connections: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: eks-a-test01
  clustermesh-enable-endpoint-sync: "false"
  clustermesh-enable-mcs-api: "false"
  cni-chaining-mode: portmap
  cni-exclusive: "false"
  cni-log-file: /var/run/cilium/cilium-cni.log
  custom-cni-conf: "false"
  datapath-mode: veth
  debug: "false"
  debug-verbose: ""
  direct-routing-skip-unreachable: "false"
  dnsproxy-socket-linger-timeout: "10"
  egress-gateway-reconciliation-trigger-interval: 1s
  enable-auto-protect-node-port-range: "true"
  enable-bpf-clock-probe: "false"
  enable-endpoint-health-checking: "true"
  enable-external-ips: "false"
  enable-health-check-loadbalancer-ip: "false"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-host-firewall: "true"
  enable-host-legacy-routing: "true"
  enable-host-port: "false"
  enable-hubble: "true"
  enable-ipv4: "true"
  enable-ipv4-big-tcp: "false"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-big-tcp: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-networkpolicy: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "false"
  enable-masquerade-to-route-source: "false"
  enable-metrics: "true"
  enable-node-port: "false"
  enable-node-selector-labels: "false"
  enable-policy: always
  enable-runtime-device-detection: "true"
  enable-sctp: "false"
  enable-svc-source-range-check: "true"
  enable-tcx: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  envoy-base-id: "0"
  envoy-keep-cap-netbindservice: "false"
  external-envoy-proxy: "true"
  hubble-disable-tls: "false"
  hubble-export-file-max-backups: "5"
  hubble-export-file-max-size-mb: "10"
  hubble-listen-address: :4244
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  identity-gc-interval: 15m0s
  identity-heartbeat-timeout: 30m0s
  install-no-conntrack-iptables-rules: "false"
  ipam: kubernetes
  ipam-cilium-node-update-rate: 15s
  k8s-client-burst: "20"
  k8s-client-qps: "10"
  k8s-require-ipv4-pod-cidr: "false"
  k8s-require-ipv6-pod-cidr: "false"
  kube-proxy-replacement: "false"
  kube-proxy-replacement-healthz-bind-address: ""
  max-connected-clusters: "255"
  mesh-auth-enabled: "true"
  mesh-auth-gc-interval: 5m0s
  mesh-auth-queue-size: "1024"
  mesh-auth-rotated-identities-queue-size: "1024"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  nat-map-stats-entries: "32"
  nat-map-stats-interval: 30s
  node-port-bind-protection: "true"
  nodeport-addresses: ""
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  policy-audit-mode: "true"
  policy-cidr-match-mode: ""
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  proxy-connect-timeout: "2"
  proxy-idle-timeout-seconds: "60"
  proxy-max-connection-duration-seconds: "0"
  proxy-max-requests-per-connection: "0"
  proxy-xff-num-trusted-hops-egress: "0"
  proxy-xff-num-trusted-hops-ingress: "0"
  remove-cilium-node-taints: "true"
  routing-mode: tunnel
  service-no-backend-response: reject
  set-cilium-is-up-condition: "true"
  set-cilium-node-taints: "true"
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-proxy-response-max-delay: 100ms
  tunnel-protocol: geneve
  unmanaged-pod-watcher-interval: "15"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
  write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conflist
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-10-20T12:57:29Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cilium-config
  namespace: kube-system
  resourceVersion: "7912"
  uid: 0aa612e7-3e98-4145-ad5d-42767c7f2804
```

I would be available to debug this next week. Please let me know if you need the output of any other command.

**Comment by Cajga** [comment]
NOTE: I've re-installed the cluster without the bonding config and the problem persist even with single interfaces

**Comment by Cajga** [comment]
I managed to reproduce the problem in a kind cluster and as such I could attach more information to that ticket:
https://github.com/cilium/cilium/issues/35535

Closing this in favor of that.
