### ISSUE TITLE
Unable to resolve mimir using Cilium Cluster Mesh

### ISSUE THREAD

**Issue by mkm29** [cilium/cilium#35073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

I want to have a single cluster for centralized logging, where other clusters that belong to the mesh can forward their logs/metrics to. I am using the Grafana LGTM-distributed stack (Helm) as the observability platform and Grafana Alloy as a collector/forwarder. Other clusters are not able to resolve the global services (mimir and loki) on the monitoring cluster.

### How can we reproduce the issue?

1. Install Cilium using the cilium binary and values that can be found [here](https://github.com/mkm29/cilium-rke2-ansible/blob/main/templates/cilium/cilium-values.yaml.j2)
2. Connect the clusters using `cilium clustermesh connect --context $CLUSTER1 --detination-context $CLUSTER2`
3. Alloy installed via Helm, the configuration can be found [here](https://github.com/mkm29/cilium-rke2-ansible/blob/main/argocd/alloy/config/config.alloy)
4. I temporarily disabled `firewalld` (running on Rocky Linux 9.4)

### Cilium Version

1.16.0

### Kernel Version

6.10.10-1

### Kubernetes Version

1.31.0

### Sysdump

[cilium-sysdump-20240928-163259-cluster1.zip](https://github.com/user-attachments/files/17176211/cilium-sysdump-20240928-163259-cluster1.zip)

### Anything else?

- I set the coredns service to type LoadBalancer in CLUSTER2,
- Added a zone to the coredns ConfigMap in CLUSTER1 to rewrite and forward requests that contained .cluster.monitoring to the IP address of the coredns service on CLUSTER2
  - rewrite name substring cluster.monitoring svc.cluster.local
- nslookup lgtm-distributed-mimir-nginx.monitoring.cluster.monitoring resolves to the IP adddress of the service residing in CLUSTER2
- curl http://lgtm-distributed-mimir-nginx.monitoring.cluster.monitoring/api/v1/status/buildinfo hangs and returns:
  - curl: (28) Failed to connect to lgtm-distributed-mimir-nginx.monitoring.cluster.monitoring port 80 after 133057 ms: Couldn't connect to **server**

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrFreezeex** [comment]
Hi!

> nslookup lgtm-distributed-mimir-nginx.monitoring.cluster.monitoring resolves to the IP adddress of the service residing in CLUSTER2

You cannot contact a Service IP of another cluster, only pod IPs are supposed to be reachable that way. To make this work you probably need to use a global service, see the associated doc about this: https://docs.cilium.io/en/latest/network/clustermesh/services/.

**Comment by mkm29** [comment]
Thanks!

I am using global services, however, the difference I find with my setup compared to the docs is that only one cluster will actually have backend pods for the service. Since Cilium will load balance over all the pods for that service, I would think it would just choose one of the pods from the monitoring cluster. I have also enabled clustermesh.enableEndpointSliceSynchronization and clustermesh.enableMCSAPISupport

I have that example rebel-base service deployed to multiple clusters and I have tested that it does load balance between the 3 so I am not sure what is going on. This is the error I get from the alloy pods:

```
ts=2024-09-28T23:05:45.050095506Z level=warn msg="error sending batch, will retry" component_path=/ component_id=loki.write.default component=client host=lgtm-distributed-loki-gateway.monitoring.svc.cluster.local status=-1 tenant=cilium-demo-cluster2 error="Post \"http://lgtm-distributed-loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push\": context deadline exceeded"
ts=2024-09-28T23:05:58.949414193Z level=warn msg="Failed to send batch, retrying" component_path=/ component_id=prometheus.remote_write.mimir subcomponent=rw remote_name=0e6c2b url=http://lgtm-distributed-mimir-nginx.monitoring.svc.cluster.local/api/v1/push err="Post \"http://lgtm-distributed-mimir-nginx.monitoring.svc.cluster.local/api/v1/push\": context deadline exceeded"
```

**Comment by MrFreezeex** [comment]
> I have also enabled clustermesh.enableEndpointSliceSynchronization and clustermesh.enableMCSAPISupport

I would advise you to disable enableMCSAPISupport this feature is not yet complete in Cilium 1.16.x and undocumented.

Now for you issue, just to confirm, do you have a Service `lgtm-distributed-mimir-nginx` in the monitoring namespace with the right global service annotations in both of your clusters? The current implementation of ClusterMesh in Cilium requires Service to be created on every clusters (even if there are no backing pods!).

**Comment by mkm29** [comment]
Thanks, I disabled mcs. The same service exists on both clusters, and both have the annotations:

```
service.cilium.io/global: true
service.cilium.io/global-sync-endpoint-slices: true
```

Initially I thought that it must be a headless service, but I recently changed it to ClusterIp.

**Comment by mkm29** [comment]
I simplified my cilium values for initial installation, I had to wait until cilium was first installed before enabling clustermesh,  now Alloy can send Loki logs, however I when Alloy attempts to send prom logs to mimir-nginx I get the error: `connect: operation not permitted`...I will look into this.
