### ISSUE TITLE
argocd can't use cilium 1.16.2 helm version when k8sServiceHost set to auto

### ISSUE THREAD

**Issue by kotyara85** [cilium/cilium#35094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Setting k8sServiceHost=auto when installing using argocd returns this error - 

```
Unable to save changes: application spec for cilium is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = `helm template . --name-template cilium --namespace kube-system --kube-version 1.30 --values /tmp/e1416a6f-b6c5-4a8c-bb6c-dcd4aa41abc2 <api versions removed> --include-crds` failed exit status 1: Error: template: cilium/templates/cilium-operator/deployment.yaml:141:20: executing "cilium/templates/cilium-operator/deployment.yaml" at <include "k8sServiceHost" .>: error calling include: template: cilium/templates/_helpers.tpl:120:37: executing "k8sServiceHost" at <$configmap.data>: wrong type for value; expected map[string]interface {}; got interface {} Use --debug flag to render out invalid YAML
```

### How can we reproduce the issue?

you can just run `helm template cilium x-helm-virtual/cilium --set k8sServiceHost=auto` to reproduce this error

### Cilium Version

1.16.2

### Kernel Version

5+

### Kubernetes Version

1.30.3

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @kreeuwijk, does this look familiar to you at all?

**Comment by kreeuwijk** [comment]
Why would you use Argo to deploy Cilium?

**Comment by kotyara85** [comment]
> Why would you use Argo to deploy Cilium?

We use it to enforce configuration. It’s deployed with a helm command beforehand.

**Comment by joestringer** [comment]
The part about Argo doesn't seem that interesting to me, but what's more interesting is that this seems reproducible directly with Helm. I'm wondering why this occurs and whether there should be other helm settings also applied or if it's a bug in the helm chart.

```
$ helm template cilium cilium/cilium --set k8sServiceHost=auto
Error: template: cilium/templates/cilium-operator/deployment.yaml:141:20: executing "cilium/templates/cilium-operator/deployment.yaml" at <include "k8sServiceHost" .>: error calling include: template: cilium/templates/_helpers.tpl:120:37: executing "k8sServiceHost" at <$configmap.data>: wrong type for value; expected map[string]interface {}; got interface {}

Use --debug flag to render out invalid YAML
```

(The reason I pinged is you were the author on https://github.com/cilium/cilium/pull/31885, so you probably have the best understanding of how the feature is intended to work).

**Comment by kreeuwijk** [comment]
Yes, I'll take a look at this. There must be a schema issue somewhere

**Comment by kreeuwijk** [comment]
@joestringer can you confirm this worked normally in Cilium 1.16.0?

**Comment by kreeuwijk** [comment]
Never mind I can replicate it with 1.16.0 as well

**Comment by kreeuwijk** [comment]
So what's failing is this piece in `_helpers.tpl`:
```
$configmap := (lookup "v1" "ConfigMap" "kube-public" "cluster-info")
```
Which does a lookup in the target cluster to attempt to find the `cluster-info` configmap. However this doesn't work in the `helm template` command as [lookup functions don't work locally on the client](https://github.com/operator-framework/operator-sdk/issues/5728). If you ran it on the server, you'll see that it does work.
```
helm template . --set k8sServiceHost=auto --dry-run=server
```

I see there's been [requests](https://github.com/argoproj/argo-cd/issues/16367) to add this option to ArgoCD, but it looks like that never got approved.

I submitted a fix [here](https://github.com/cilium/cilium/pull/35184)
