### ISSUE TITLE
Cilium Slack invite link doesn't work again, redirects to domain login only. And docs have incorrect link.

### ISSUE THREAD

**Issue by nogweii** [cilium/cilium#35128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Trying to access `slack.cilium.io` results in me being redirected to `https://cilium.slack.com/signup#/domain-signup` where I can only sign in with an email from a couple of domains. It does not take me to an invite form.

In the [main documentation pages for cilium](https://docs.cilium.io/en/stable/) the "Join Slack" button links to the herokuapp domain, which no longer works.

### How can we reproduce the issue?

1. Access `https://slack.cilium.io/` in a browser without a session to Slack
2. Observe that it redirects you to the domain signup page, rather than the invitation page.

### Cilium Version

Latest

### Kernel Version

6.6 LTS

### Kubernetes Version

1.30.5

### Regression

It appears to be a recurring regression, as there have been multiple reports of the app breaking:

- #34689 
- #32207 
- #30069 
- #29103 

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nogweii** [comment]
It works now! Thanks for updating it.

**Comment by taliastocks** [comment]
Still happening

**Comment by mattfysh** [comment]
and again

<img width="476" alt="Image" src="https://github.com/user-attachments/assets/442cd322-7746-4400-9c4a-36a1ba31af4c" />

**Comment by paularah** [comment]
@mattfysh, it's fixed it now. Let me know if you still run into troubles
