### ISSUE TITLE
Connectivity check is checking ipv4 features when injecting ipv6

### ISSUE THREAD

**Issue by vincepri** [cilium/cilium#35125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

https://github.com/cilium/cilium/blob/1a47a11cd18367a6c36a88c3674ef63171c617ca/cilium-cli/connectivity/check/deployment.go#L1560-L1567

### How can we reproduce the issue?

The check for pod ipv6 is checking for ipv4 features

### Cilium Version

N/A

### Kernel Version

N/A

### Kubernetes Version

N/A

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
agree, that does look odd. Would you want to send a patch?
