### ISSUE TITLE
CI: Check if build works for every commit

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#35148]
## CI failure

- Set title to be in the format `CI: <test-name>`.

Done

- Copy-paste the output the test failure.

# k8s.io/client-go/applyconfigurations/core/v1
compile: writing output: write $WORK/b777/_pkg_.a: no space left on device
# golang.org/x/text/encoding/simplifiedchinese
compile: writing output: write $WORK/b969/_pkg_.a: no space left on device

- Upload the zip file generated from that test failure.

N/A (no artifacts)

- Copy-paste the link of the CI build where that test failure has happen.

https://github.com/cilium/cilium/actions/runs/11120928434/job/30898906476?pr=34692

- Include any output from logs that you think may be relevant (to ease GitHub searches).

# k8s.io/client-go/applyconfigurations/core/v1
compile: writing output: write $WORK/b777/_pkg_.a: no space left on device
# golang.org/x/text/encoding/simplifiedchinese
compile: writing output: write $WORK/b969/_pkg_.a: no space left on device

**Comment by aanm** [comment]
fixed by https://github.com/cilium/cilium/pull/35141
