### ISSUE TITLE
Widespread `error: implicit conversion loses integer precision: '__u64' (aka 'unsigned long long') to '__u32' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]" subsys=datapath-loader` when compiling with Clang 19

### ISSUE THREAD

**Issue by jingyuanliang** [cilium/cilium#35162]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Clang 19 introduced:
```
The -Wshorten-64-to-32 diagnostic is now grouped under -Wimplicit-int-conversion instead
of -Wconversion. Fixes #GH69444.
```
which causes the current code to fail compilation with the flags currently in use.

### How can we reproduce the issue?

Run tests on a system with Clang 19 installed, such as running `make -C bpf/tests all`, but this also affects unit tests like:

```
=== RUN   TestCompile
=== RUN   TestCompile/obj:bpf_lxc.o
time="2024-10-01T22:39:35Z" level=error msg="Failed to compile bpf_lxc.o: exit status 1" compiler-pid=66176 subsys=datapath-loader
time="2024-10-01T22:39:35Z" level=warning msg="In file included from ../../../bpf/bpf_lxc.c:20:" subsys=datapath-loader
time="2024-10-01T22:39:35Z" level=warning msg="In file included from ../../../bpf/lib/auth.h:7:" subsys=datapath-loader
time="2024-10-01T22:39:35Z" level=warning msg="../../../bpf/lib/common.h:202:22: error: implicit conversion loses integer precision: 'const __u64' (aka 'const unsigned long long') to '__u32' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]" subsys=datapath-loader
time="2024-10-01T22:39:35Z" level=warning msg="  202 |                 ctx_pull_data(ctx, tot_len);" subsys=datapath-loader
time="2024-10-01T22:39:35Z" level=warning msg="      |                 ~~~~~~~~~~~~~      ^~~~~~~" subsys=datapath-loader
time="2024-10-01T22:39:35Z" level=warning msg="In file included from ../../../bpf/bpf_lxc.c:20:" subsys=datapath-loader
```

### Cilium Version

1.16.2

### Kernel Version

N/A

### Kubernetes Version

N/a

### Anything else?

Regardless how we handle this, we should publish the "highest tested" clang version, instead of a broad "clang+LLVM >= 10.0".

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bowei** [comment]
It would help if you edited the above description with the specific commands run to hit the issue. I'm assuming this is some form of `git clone; ... ; make test`.

**Comment by bowei** [comment]
Also, did you patch the repo to update to clang-19? Post the patch as well if that is the case.

**Comment by jingyuanliang** [comment]
> It would help if you edited the above description with the specific commands run to hit the issue. I'm assuming this is some form of `git clone; ... ; make test`.

done

**Comment by jingyuanliang** [comment]
> Also, did you patch the repo to update to clang-19? Post the patch as well if that is the case.

Didn't patch the repo. Those tests (running from `make`) take clang from the running system.

**Comment by julianwiedmann** [comment]
as bowei suggested, Cilium currently doesn't support LLVM 19. There's [ongoing work](https://github.com/cilium/cilium/pulls?q=is%3Aopen+is%3Apr+label%3Aarea%2Fllvm) to bump us from 17 to 18, maybe you'd like to contribute there?

**Comment by sayboras** [comment]
The current main is with clang 18 now. For the mentioned issue, appreciate if you can test it out with https://github.com/cilium/cilium/pull/36186
