### ISSUE TITLE
Gateway API 1.2.0 released

### ISSUE THREAD

**Issue by fmunteanu** [cilium/cilium#35213]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

As title says, Gateway API 1.2.0 is released, any concerns we should look into, related to Cilium?

https://github.com/kubernetes-sigs/gateway-api

### How can we reproduce the issue?

N/A

### Cilium Version

1.16.1

### Kernel Version

N/A

### Kubernetes Version

N/A

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Seems like [no](https://github.com/cilium/cilium/pull/35216) :).

If there's nothing specific you'd want to address here, I'd suggest to celebrate & discuss the release on Slack?

**Comment by fmunteanu** [comment]
I just wanted to make sure there are no issues on Cilium side, thank you for confirming.

**Comment by blmhemu** [comment]
Gateway API 1.2.x does not work well with cilium 1.16.4 (latest stable at this time). Reason being
> The Experimental supportedFeatures field in GatewayClass status has changed
from being a list of strings to being a list of objects/structs with a name
field.
