### ISSUE TITLE
bugtool: gather CNP, CEP output

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3522]
As part of the bugtool, we should get CNP and CEP information from Kubernetes:

```
kubectl get cnp -n kube-system -o json
kubectl get cep -n kube-system -o json
```

It would be up to the user who runs this tooling to remove any information they deem sensitive if they do not want it provided in a bug report.

**Comment by aanm** [comment]
This should actually be
```
kubectl get cnp --all-namespaces -o json
kubectl get cep --all-namespaces -o json
```

**Comment by joestringer** [comment]
Resolved in https://github.com/cilium/cluster-diagnosis/commit/9a45f7ac34f73eb3b0407e7c515f20a24083fc66 / https://github.com/cilium/cluster-diagnosis/commit/62948f03766f386acdec0c28ef90720675e9bd84.
