### ISSUE TITLE
GoBGP dependency update blocked as of v3.30.0

### ISSUE THREAD

**Issue by rastislavs** [cilium/cilium#35271]
GoBGP [v3.30.0](https://github.com/osrg/gobgp/releases/tag/v3.30.0) contains a regression which breaks peering with unspecified local IPv6 address (https://github.com/osrg/gobgp/issues/2844).

Due to this, dependency update to GoBGP v3.30 is blocked until the regression is resolved and a new version is released. This issue should remain open until automatic GoBGP dependency updates are enabled again.

Upstream fix PR: https://github.com/osrg/gobgp/pull/2843

**Comment by julianwiedmann** [comment]
@rastislavs should we maybe pull in `v3.31.0` manually to confirm the fix, before re-enabling upgrades via renovate?

**Comment by rastislavs** [comment]
@julianwiedmann 
> should we maybe pull in `v3.31.0` manually to confirm the fix, before re-enabling upgrades via renovate?

Doing both manual update & re-enabling renovate in https://github.com/cilium/cilium/pull/35795
