### ISSUE TITLE
After some normal usage, one particular deployment lost pod network access

### ISSUE THREAD

**Issue by feisuzhu** [cilium/cilium#35338]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

After some normal usage, one particular deployment's pods (say IllPod) lost pod network access (external network access is working).

1. IllPod can't ping every other pods, except itself, the same applies to the other direction.
2. Networking of pods on the same node is OK.
3. Removing the IllPod and the new started IllPod does not work either, including pods scheduled to different nodes.
4. Killing and restarting all cilium related containers does not resolve this.
5. Manually removing `CiliumIdentity` and `CiliumEndpoints` then restarts IllPod does not resolve this.
6. Adding a nonsense label to the IllPod deployment RESOLVES this.
7. Removing the nonsense label and the problem comes back.
8. There are no `NetworkPolicy`s and `CiliumNetworkPolicy`s.
9. A `tcpdump` shows the IllPod CAN receive the ping request and reply appears in `lxc` and `cilium_vxlan` interfaces, but does not appear in host iface.
10. IllPod CAN ping 8.8.8.8

### How can we reproduce the issue?

I don't know, sorry.

### Cilium Version

```
cilium-cli: v0.16.18 compiled with go1.23.1 on linux/amd64
cilium image (default): v1.16.1
cilium image (stable): v1.16.2
cilium image (running): 1.16.2
```

I can confirm all running cilium containers are using `quay.io/cilium/cilium:v1.16.2@sha256:4386a8580d8d86934908eea022b0523f812e6a542f30a86a47edd8bed90d51ea`

### Kernel Version & Kubernetes Version
```
NAME    STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
ai-01   Ready    <none>          50d   v1.31.0   100.64.11.5   <none>        Ubuntu 22.04.4 LTS   5.15.0-113-generic   containerd://1.7.19
ai-02   Ready    <none>          50d   v1.31.0   100.64.11.4   <none>        Ubuntu 22.04.4 LTS   5.15.0-113-generic   containerd://1.6.24
ai-03   Ready    <none>          50d   v1.31.0   100.64.11.3   <none>        Ubuntu 22.04.4 LTS   5.15.0-105-generic   containerd://1.6.31
ai-04   Ready    <none>          50d   v1.31.0   100.64.11.2   <none>        Ubuntu 22.04.4 LTS   5.15.0-107-generic   containerd://1.6.31
ai-08   Ready    <none>          50d   v1.31.0   100.64.11.7   <none>        Ubuntu 22.04.4 LTS   5.15.0-105-generic   containerd://1.6.31
ai-09   Ready    <none>          50d   v1.31.0   100.64.11.8   <none>        Ubuntu 22.04.3 LTS   5.15.0-89-generic    containerd://1.6.25
ai-10   Ready    <none>          50d   v1.31.0   100.64.11.6   <none>        Ubuntu 22.04.4 LTS   5.15.0-107-generic   containerd://1.6.31
master  Ready    control-plane   50d   v1.31.0   100.64.11.1   <none>        Ubuntu 24.04 LTS     6.8.0-1009-aws       containerd://1.7.20
```

### Sysdump

https://s3-speed-test-oregon-666.s3.dualstack.us-west-2.amazonaws.com/cilium-sysdump-20241010-165534.zip

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by feisuzhu** [comment]
`cilium-dbg` output when pinging problematic pod ip:
```
root@ai-08:/home/cilium# cilium-dbg monitor | grep 3\\.3
-> endpoint 1003 flow 0x0 , identity remote-node->47624 state new ifindex lxc1a4980b4feca orig-ip 10.232.4.35: 10.232.4.35 -> 10.232.3.3 EchoRequest
-> overlay flow 0x0 , identity 47624->remote-node state reply ifindex cilium_vxlan orig-ip 0.0.0.0: 10.232.3.3 -> 10.232.4.35 EchoReply
```

pinging normal pod ip on the same node does not produce output like above.

**Comment by squeed** [comment]
@feisuzhu thanks for the sysdump. I took a quick look, but there were no smoking guns. Can you give me a bit more hints?

- was the problem occurring when the sysdump was taken, or after it was resolved?
- If it was occurring, when did you notice it? Which were the source and destination IPs? Was there a service involved.

thanks!

**Comment by feisuzhu** [comment]
> was the problem occurring when the sysdump was taken, or after it was resolved?

The problem was occurring.

> If it was occurring, when did you notice it? Which were the source and destination IPs? Was there a service involved.

Destination IP is 10.232.3.3, source ip does not matter, all other pods won't connect to it.

**Comment by squeed** [comment]
Then I'm missing something. I don't see any packets going to or from 10.232.3.3 in any of the Hubble flows. Even if networking for the pod in question is totally broken, I would expect to see some packets from an originating pod. Do you know why they might be missing?

**Comment by squeed** [comment]
Nothing obvious to me shows up in the sysdump (but who knows what it could be yet). Do you think you could try and get some Hubble traces from some packets being lost? You can do this by doing `kubectl exec -n kube-system -ti <cilium_pod>` and running `hubble observe -f --ip <broken ip>`?

I would also like to know if it makes a difference if the ping comes from the node, a pod on the same node, and a pod on a different node.

Thanks! There'

**Comment by feisuzhu** [comment]
A new sysdump: https://s3-speed-test-oregon-666.s3.dualstack.us-west-2.amazonaws.com/cilium-sysdump-20241018-161013.zip

ping from:
- debug: pod to pod, different node, does not receive reply
- debug2: pod to pod, same node, ping works
- 10.232.5.42: node to pod, different node does not receive reply

```
root@cilium-container:/home/cilium# clear;hubble observe -f --ip 10.232.8.158
Oct 18 08:17:33.823: kube-system/debug2-786f5d9f47-xr64n (ID:869) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
Oct 18 08:17:33.824: kube-system/debug2-786f5d9f47-xr64n (ID:869) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoReply)
Oct 18 08:17:34.341: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
Oct 18 08:17:34.341: kube-system/debug-784c78d64-vlgfc (ID:45292) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoReply)
Oct 18 08:17:39.092: 10.232.5.42 (remote-node) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
Oct 18 08:17:39.092: 10.232.5.42 (remote-node) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoReply)
Oct 18 08:17:39.829: kube-system/debug2-786f5d9f47-xr64n (ID:869) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
Oct 18 08:17:39.829: kube-system/debug2-786f5d9f47-xr64n (ID:869) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoReply)
Oct 18 08:17:40.348: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
Oct 18 08:17:40.348: kube-system/debug-784c78d64-vlgfc (ID:45292) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoReply)
Oct 18 08:17:45.235: 10.232.5.42 (remote-node) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
Oct 18 08:17:45.235: 10.232.5.42 (remote-node) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoReply)
Oct 18 08:17:45.834: kube-system/debug2-786f5d9f47-xr64n (ID:869) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
Oct 18 08:17:45.834: kube-system/debug2-786f5d9f47-xr64n (ID:869) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoReply)
Oct 18 08:17:46.353: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
Oct 18 08:17:46.353: kube-system/debug-784c78d64-vlgfc (ID:45292) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoReply)

```


`nvidia-device-plugin-node-feature-discovery-worker-jhm48          57352` is problematic

```
NAME                                                              SECURITY IDENTITY   ENDPOINT STATE   IPV4           IPV6
coredns-c876c97db-dz9k2                                           14911               ready            10.232.4.141
debug-784c78d64-vlgfc                                             45292               ready            10.232.5.16
debug2-786f5d9f47-xr64n                                           869                 ready            10.232.8.129
hubble-relay-d9495cdc-sf22p                                       4309                ready            10.232.4.108
hubble-ui-77555d5dcf-t469l                                        29629               ready            10.232.4.110
nvidia-device-plugin-5hqbk                                        8752                ready            10.232.5.141
nvidia-device-plugin-8r6tt                                        8752                ready            10.232.7.81
nvidia-device-plugin-c5xh4                                        8752                ready            10.232.3.167
nvidia-device-plugin-fmd7m                                        8752                ready            10.232.8.23
nvidia-device-plugin-gpu-feature-discovery-8sl9h                  8752                ready            10.232.2.172
nvidia-device-plugin-gpu-feature-discovery-ck58c                  8752                ready            10.232.8.200
nvidia-device-plugin-gpu-feature-discovery-fcrpf                  8752                ready            10.232.1.188
nvidia-device-plugin-gpu-feature-discovery-fdlvb                  8752                ready            10.232.6.237
nvidia-device-plugin-gpu-feature-discovery-kkx5c                  8752                ready            10.232.5.55
nvidia-device-plugin-gpu-feature-discovery-t2d7t                  8752                ready            10.232.4.169
nvidia-device-plugin-gpu-feature-discovery-wxvlq                  8752                ready            10.232.7.211
nvidia-device-plugin-gpu-feature-discovery-z4zwv                  8752                ready            10.232.3.217
nvidia-device-plugin-j9h4d                                        8752                ready            10.232.4.79
nvidia-device-plugin-mq7sm                                        8752                ready            10.232.6.64
nvidia-device-plugin-node-feature-discovery-master-5d84fbdnw86j   6444                ready            10.232.0.77
nvidia-device-plugin-node-feature-discovery-worker-67zg8          20914               ready            10.232.6.47
nvidia-device-plugin-node-feature-discovery-worker-dh6jb          20914               ready            10.232.4.163
nvidia-device-plugin-node-feature-discovery-worker-g8p4g          20914               ready            10.232.3.66
nvidia-device-plugin-node-feature-discovery-worker-hkmc4          20914               ready            10.232.2.223
nvidia-device-plugin-node-feature-discovery-worker-hqfrf          20914               ready            10.232.7.115
nvidia-device-plugin-node-feature-discovery-worker-jhm48          57352               ready            10.232.8.158
nvidia-device-plugin-node-feature-discovery-worker-ph6kx          20914               ready            10.232.5.193
nvidia-device-plugin-node-feature-discovery-worker-qxhpc          20914               ready            10.232.1.146
nvidia-device-plugin-s4rfw                                        8752                ready            10.232.2.129
nvidia-device-plugin-spjnr                                        8752                ready            10.232.1.137
traefik-d9cd668fd-zgntv                                           40156               ready            10.232.4.45
```

**Comment by squeed** [comment]
This is an extremely helpful sysdump, thank you! And I'm totally stumped. I'll think about it a bit more next week.

One thing I do notice is that Cilium is considering the TailScale IPs as the primary IP. That's probably not ideal; I'd suggest ignoring the tailscale interfaces when doing address detection. IIRC there is a way to select interfaces by a wildcard; I'll look further.

**Comment by feisuzhu** [comment]
> One thing I do notice is that Cilium is considering the TailScale IPs as the primary IP.

It SHOULD consider it as the primary IP, we are deploying a single cluster over several disjoint DCs.

**Comment by feisuzhu** [comment]
Any updates?

We kept experiencing this during these days, we can't go prod with this issue unresolved.

**Comment by joestringer** [comment]
Just passing through, but I noticed a discrepancy between the description of the problem and the observations in hubble:

> * debug: pod to pod, different node, does not receive reply
> ...
> ```
> Oct 18 08:17:34.341: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
> Oct 18 08:17:34.341: kube-system/debug-784c78d64-vlgfc (ID:45292) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoReply)
> ```

At the target node where you are running `hubble observe`, we see here that the ICMP request is delivered to the affected Pod and the Pod responds with an EchoReply. This node sends the response back to the source node. However, since hubble is run on the destination node, we cannot confirm whether the response arrives back at the source node.

> * 10.232.5.42: node to pod, different node does not receive reply
> ...
> ```
> Oct 18 08:17:39.092: 10.232.5.42 (remote-node) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-endpoint FORWARDED (ICMPv4 EchoRequest)
> Oct 18 08:17:39.092: 10.232.5.42 (remote-node) <- kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoReply)
> ```

Same behaviour here.

Since the requests are received and the responses are sent from the destination node with the affected workload, I would suggest investigating the Hubble output for the same IP but at the source node (source of debug pod or `10.232.5.42`).

**Comment by feisuzhu** [comment]
> I would suggest investigating the Hubble output for the same IP but at the source node (source of debug pod or 10.232.5.42).

```
Oct 27 12:47:27.853: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:47:33.860: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:47:39.867: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:47:45.873: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:47:51.880: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:47:57.887: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:03.893: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:09.900: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:15.907: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:21.914: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:22.270: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:23.279: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:24.302: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:25.326: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:26.350: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:27.375: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:27.921: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:28.398: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:29.422: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:30.446: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:31.470: 10.232.5.42 (remote-node) <> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
Oct 27 12:48:33.927: kube-system/debug-784c78d64-vlgfc (ID:45292) -> kube-system/nvidia-device-plugin-node-feature-discovery-worker-jhm48 (ID:57352) to-overlay FORWARDED (ICMPv4 EchoRequest)
^Croot@ai-01:/home/cilium#
```

**Comment by feisuzhu** [comment]
@squeed @joestringer Could you please point me some docs about how to debug this situation? For example, what I want most now is to inspect various internal states of Cilium components, eBPF, agent, or whatever

**Comment by feisuzhu** [comment]
Found that packets are dropped by `cil_from_netdev` filter, don't know why at the moment.

**Comment by feisuzhu** [comment]
Sorry about the noise above, pcap shows the VXLAN encapped ping didn't go to `tailscale0` interface as expected, don't know why at the moment.

pcap file attached

[bad-and-good.pcapng.gz](https://github.com/user-attachments/files/17789525/bad-and-good.pcapng.gz)

Captured at `172.16.8.9`
The first segment is bad and the second segment is good (can observe wireguard packet going out)

In first segment, the last packet is the VXLAN encapped ping with dest `100.64.11.5` but src `172.16.8.9`, and went to physical interface (rather than `tailscale0`)

**Comment by feisuzhu** [comment]
Turns out to be a `skb->mark` conflict, tailscale is using `0x40000` and `0x80000` which falls in identity number according to cilium code.

**Comment by feisuzhu** [comment]
Don't know if this is considered relevant to you guys, I'm going to workaround at tailscale side, so feel free to close this.

**Comment by joestringer** [comment]
Thanks for sharing @feisuzhu . I've filed https://github.com/cilium/cilium/issues/36104 in order to make the issue easier to search and find. Given that you have a mitigation for now I think it's fine to close out this issue.

**Comment by b4stien** [comment]
> Don't know if this is considered relevant to you guys, I'm going to workaround at tailscale side, so feel free to close this.

@feisuzhu have you find such a workaround on tailscale side?

**Comment by feisuzhu** [comment]
@b4stien Sorry about the late reply, please see https://github.com/taichi-dev/tailscale/commit/6807d6625270f0aace96f195a41ddead7bb54263

**Comment by abh** [comment]
This is still an issue, unless you build your own tailscale binary with @feisuzhu's patch (which I don't think was sent upstream?)

**Comment by markasoftware-tc** [comment]
still an issue in 2026
