### ISSUE TITLE
SyncLBMap() kvstore access may block for a significant periods

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3533]
It's possible for `SyncLBMap()` to block for a significant time upon the KVstore if many nodes are doing the same thing at the same time: 

https://github.com/cilium/cilium/blob/f3376543097590d6cbb1b1488e486ce10fe5de41/daemon/loadbalancer.go#L439-L443

https://github.com/cilium/cilium/blob/f3376543097590d6cbb1b1488e486ce10fe5de41/daemon/loadbalancer.go#L569-L571

https://github.com/cilium/cilium/blob/f3376543097590d6cbb1b1488e486ce10fe5de41/daemon/services.go#L57-L58

https://github.com/cilium/cilium/blob/f3376543097590d6cbb1b1488e486ce10fe5de41/daemon/services.go#L78

https://github.com/cilium/cilium/blob/f3376543097590d6cbb1b1488e486ce10fe5de41/pkg/kvstore/etcd.go#L424

**Comment by ianvernon** [comment]
Fixing this can be coupled with the refactoring of the service-kvstore interaction to use the updated key-value store code which is used by the identity allocator.

**Comment by joestringer** [comment]
Fixed by #3535

**Comment by joestringer** [comment]
Ah, @ianvernon I was thinking the issue behind this is effectively solved by #3535. If you'd rather leave this open as the issue to refactor the service<->kvstore interaction then feel free to reopen.
