### ISSUE TITLE
Cilium Operator dashboard doesn't work

### ISSUE THREAD

**Issue by maxpain** [cilium/cilium#35335]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Hello. I installed Cilium using Helm. Two dashboards were installed successfully: `Cilium Operator` and `Cilium Metrics`, but only `Cilium Metrics` works.
There is an error: "Datasource ${DS_PROMETHEUS} was not found" when I open the `Cilium Operator` dashboard.

![Image](https://github.com/user-attachments/assets/292f2901-37cf-4ccf-945e-c5981fd094d0)

### How can we reproduce the issue?

Install Cilium with helm with the following values

```yaml
dashboards:
  enabled: true

operator:
  dashboards:
    enabled: true
```

### Cilium Version

1.16.2

### Kernel Version

doesn't matter

### Kubernetes Version

doesn't matter

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report @maxpain . I just tried this myself locally and I can't reproduce the behaviour you're reporting. I'm following the instructions at https://github.com/cilium/cilium/tree/main/examples/kubernetes/addons/prometheus . I'm not sure what I am doing differently from you, but I wonder whether it might help to restart the operator after applying the configuration?

```
$ make kind
...
$ make kind-install-cilium
...
$ cat dashboards.yaml 
dashboards:
  enabled: true

operator:
  dashboards:
    enabled: true
$ cilium upgrade --chart-directory=/var/git/cilium/install/kubernetes/cilium --helm-values=/var/git/cilium/contrib/testing/kind-common.yaml --helm-values=/var/git/cilium/contrib/testing/kind-values.yaml --helm-values=dashboards.yaml --version=                                                                                          
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
✅ Detected kind version "0.22.0"
ℹ️  Using Cilium version 1.17.0
🔮 Auto-detected cluster name: kind-kind
🔮 Auto-detected kube-proxy has been installed
$ kubectl patch -n kube-system configmap cilium-config --type merge --patch '{"data":{"prometheus-serve-addr":":9962"}}'
configmap/cilium-config patched
$ # (delete all cilium-agent pods to pick up the new config)
$ kubectl create -f examples/kubernetes/addons/prometheus/monitoring-example.yaml
namespace/cilium-monitoring created
serviceaccount/prometheus-k8s created
configmap/grafana-config created
configmap/grafana-cilium-dashboard created
configmap/grafana-cilium-operator-dashboard created
configmap/grafana-hubble-dashboard created
configmap/grafana-hubble-l7-http-metrics-by-workload created
configmap/prometheus created
clusterrole.rbac.authorization.k8s.io/prometheus created
clusterrolebinding.rbac.authorization.k8s.io/prometheus created
service/grafana created
service/prometheus created
deployment.apps/grafana created
deployment.apps/prometheus created
$ kubectl -n cilium-monitoring port-forward service/grafana --address 0.0.0.0 --address :: 3000:3000
Forwarding from 0.0.0.0:3000 -> 3000
Forwarding from [::]:3000 -> 3000
Handling connection for 3000
...
```

![Image](https://github.com/user-attachments/assets/26a0cdbe-61cf-4fab-80da-8e401e55fb4f)

**Comment by maxpain** [comment]
I use VictoriaMetrics stack
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/README.md

**Comment by joestringer** [comment]
I see. I don't know how that works. Looking at the image, it seems like somehow there is a variable that is not being substituted correctly for the cilium-operator when deploying with that stack.

I would welcome you to share if you're able to find a solution to this problem. If something can be changed in Cilium that can make this integration easier for you, then you are welcome to submit a PR to improve that part of the tree.

**Comment by maxpain** [comment]
@joestringer I found the problem. The `Cilium Metrics` dashboard has `DS_PROMETHEUS=prometheus` variable, while `Cilium Operator` doesn't:

![Image](https://github.com/user-attachments/assets/5bd057aa-6c0e-4a32-9a56-47f348f79cfb)
![Image](https://github.com/user-attachments/assets/7ad665da-0e97-4ae1-bb23-5d0554893516)

**Comment by maxpain** [comment]
@joestringer, we need to add the `DS_PROMETHEUS` variable to the `Cilium Operator` dashboard.

**Comment by joestringer** [comment]
Hmm, interesting. When I search for the error, I see https://github.com/grafana/grafana/issues/10786 which reports that it is a feature request to be able to deploy variables during dashboard provisioning. It sounds like there's no official way to do this today, but there are workarounds.
