### ISSUE TITLE
Add identity for proxy traffic

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3534]
The proxy traffic is already tagged accordingly for the datapath but it is assigned the identity `reserved:host`. 

- [ ] Introduce a new identity `reserved:proxy`
- [ ] Tag packets in `bpf_netdev` with this identity if traffic is from a proxy
- [ ] Change the automatic policy to allow from proxy to `reserved:proxy`.

**Comment by joestringer** [comment]
Doesn't the proxy reliably set the upper 16 bits of the `skb->mark` to the identity? Is there ever a case where this is not set to the original identity?

The only case that comes to mind is if the BPF datapath thinks that it can forward traffic to the proxy, but the proxy isn't listening.. in that case, the Linux stack will return back a RST, which could perhaps be classified as `proxy`, but we don't have a good identifier to determine that this traffic is associated with the proxy. Perhaps if we stored a map of "known proxy ports" and performed a lookup of the RST's source port, this could work. Not sure if this is really useful though with #3940.

**Comment by joestringer** [comment]
I'm dropping this to a lower priority because it's a pretty rare happening, and marking the traffic as `reserved:host` now that https://github.com/cilium/cilium/pull/3988 is merged is a reasonable way to represent such traffic. Happy to reconsider if there's another more pressing use case for this functionality.

**Comment by joestringer** [comment]
FWIW "known proxy ports" is a much more tractable issue since v1.6 introduced tproxy support.

But anyhow there's been no movement on this issue and it's not clear that there's any motivation to solve this in the near term. Closing.
