### ISSUE TITLE
Review policy documentation

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3539]
### Concepts

* [x] Update "Special Identities"
  * http://docs.cilium.io/en/latest/concepts/#special-identities
  * [x] cluster?

### Kubernetes Network Policy

* [x] Review
* [ ] Fix up CiliumNetworkPolicy section here:
  * http://docs.cilium.io/en/latest/kubernetes/policy/#ciliumnetworkpolicy
  * [ ] Link to more generic section (not just L3 examples?)
    * This is just an artifact of the label it's linking to
  * [x] Update structure definition
* [x] Document behaviour when NP/CNP is both applied?

#### Intro

* [x] Review
* [x] Improve wording for KVstore policy distribution? Consider whether to keep it?
  * http://docs.cilium.io/en/latest/policy/#id1
  * New in version future: Use of the KVstore to distribute security policies is on the roadmap but has not been implemented yet.
* [x] Document that the config options can be set per-endpoint
* [ ] "If both ingress and egress are omitted, the rule has no effect."
  * Is this true?
  * http://docs.cilium.io/en/latest/policy/intro/#rule-basics
* [x] Fix issue links here:
  * http://docs.cilium.io/en/latest/kubernetes/policy/#networkpolicy-state
  * Add CIDR-dependent L4
    * https://github.com/cilium/cilium/issues/1684
    * [ ] Describe workaround with world entity
* [x] High-level summary of the guiding "whitelist" design approach to defining policy?

#### Language

* [x] Review
* [ ] Make L3 summary direction-independent
* [x] Add cluster to entities
* [x] Document egress policy (#2556)
* [x] Document CIDR ingress vs. egress behaviour
  * [x] Document the desired behaviour
  * [x] Make behaviour consistent (#3565)
* [ ] Entity-dependent L4

#### Troubleshooting

* [ ] Review
* [ ] Your observations here

**Comment by ianvernon** [comment]
Will work on this at priority on 4/6.
