### ISSUE TITLE
docs: stated Cilium version `1.16.3` does not exist

### ISSUE THREAD

**Issue by pmatulis** [cilium/cilium#35393]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

The [Install Cilium][install-cilium] section on the documentation **Cilium Quick Installation** page requires an update. The instructions say to install Cilium version `1.16.3` but this version does not exist. I get the following output:

    chart "cilium" version "1.16.3" not found in https://helm.cilium.io repository

Indeed, the above [repository][cilium-versions] does not list this version. (I used `1.16.2` instead.)

[install-cilium]: https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/#install-cilium
[cilium-versions]: https://helm.cilium.io/

### How can we reproduce the issue?

1. Follow the given documentation page

What I did:

    cilium install --version 1.16.3
    chart "cilium" version "1.16.3" not found in https://helm.cilium.io repository

### Cilium Version

n/a

### Kernel Version

The Cilium CLI was running on:

    Linux cisco 6.11.0-8-generic #8-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep 16 13:41:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

n/a

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
I think there was a blip while updating the chart repository; please try now :-).

**Comment by pmatulis** [comment]
Works now.
