### ISSUE TITLE
Error opening the netns dir while updating MTU for endpoints

### ISSUE THREAD

**Issue by tamilmani1989** [cilium/cilium#35417]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Cilium agent logs this error every minute. 

> time=2024-10-17T02:22:47Z level=error msg="Error opening the netns dir while updating MTU for endpoints" module=agent.datapath.mtu netns-dir=/var/run/cilium/netns error="open /var/run/cilium/netns: no such file or directory"

This is something we noticed pretty recently and not 1.16. This error message introduced with this PR https://github.com/cilium/cilium/pull/34314 
cc: @dylandreimerink 

### How can we reproduce the issue?

Deploy latest cilium with native routing mode 

### Cilium Version

 1.17.0-dev 

### Kernel Version

5.15

### Kubernetes Version

1.29

### Regression

Yes. Didnt notice this in 1.16

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by tamilmani1989** [comment]
couldn't find `netns` directory under `/var/run/cilium` both in host and in cilium agent

**Comment by tamilmani1989** [comment]
yep that was the issue. Thanks for pointing out.

**Comment by borkmann** [comment]
@dylandreimerink I've been hitting this when running the Cilium agent as standalone process in the hostns for my dev k8s cluster. Should this Error be reduced to Debug?

**Comment by dylandreimerink** [comment]
Yes i think so. Not having the mount means we cant update the pod MTU at runtime, so not critcal other than fragmentation if a dev with lower MTU is added at runtime. 

The module health should still degrade and warn users without the log message

**Comment by alephpt** [comment]
is there a straight forward way to fix this via the values.yaml?
