### ISSUE TITLE
MTU 9000 larger than 3502 without XDP frag support

### ISSUE THREAD

**Issue by maxpain** [cilium/cilium#35426]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Hello. I Installed Cilium on Bare Metal cluster with 2x25G NICs with LACP bond and MTU 9000 (Jumbo), and sometimes I'm getting this warning in dmesg:

```
kern: warning: [2024-10-17T17:24:54.392043526Z]: bnxt_en 0000:c3:00.0 enp195s0f0: MTU 9000 larger than 3502 without XDP frag support.
 SUBSYSTEM=pci
 DEVICE=+pci:0000:c3:00.0
```

Can I ignore it?

### How can we reproduce the issue?

Yes

### Cilium Version

1.16.3

### Kernel Version

6.6.54-talos

### Kubernetes Version

1.31.1

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
XDP support for jumbo frames depends on the nic driver itself. It seems like the `bnxt_en` driver does not.

Do you have the XDP datapath enabled? You can check this with this command:

```shell
$ kubectl -n kube-system exec ds/cilium -- cilium-dbg status --verbose | grep XDP
```

If Cilium is indeed responsible for loading xdp progras, you can disable it by setting the Helm value `loadBalancer.acceleration=disabled`

**Comment by maxpain** [comment]
I have these NICs:

- `bond0` (`enp195s0f0` + `enp195s0f0` in LACP) Broadcom P225p NetXtreme-E Dual-port 10Gb/25Gb — for private networking (pods/services subnets). It has MTU 9000.
- `enp1s0f0` Intel(R) Ethernet Converged Network Adapter X710 — for public IP and internet. It has MTU 1500.
- `enp1s0f0.4000` — to connect Hetzner Cloud via vSwitch. It has MTU 1400.

```
  XDP Acceleration:       Best-Effort
```

```
time="2024-10-18T15:01:45Z" level=info msg="No existing link found at /sys/fs/bpf/cilium/devices/bond0/links/cil_xdp_entry for program cil_xdp_entry" subsys=datapath-loader
time="2024-10-18T15:01:45Z" level=info msg="Failed to attach XDP program, ignoring due to best-effort mode" device=bond0 error="interface bond0: attaching program cil_xdp_entry using bpf_link: create link: operation not supported" subsys=datapath-loader
time="2024-10-18T15:01:45Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=2
time="2024-10-18T15:01:48Z" level=info msg="Updated link /sys/fs/bpf/cilium/devices/enp1s0f0/links/cil_xdp_entry for program cil_xdp_entry" subsys=datapath-loader
time="2024-10-18T15:01:51Z" level=info msg="No existing link found at /sys/fs/bpf/cilium/devices/enp1s0f0-4000/links/cil_xdp_entry for program cil_xdp_entry" subsys=datapath-loader
time="2024-10-18T15:01:51Z" level=info msg="Failed to attach XDP program, ignoring due to best-effort mode" device=enp1s0f0.4000 error="interface enp1s0f0.4000: attaching program cil_xdp_entry using bpf_link: create link: operation not supported" subsys=datapath-loader
```

**Comment by julianwiedmann** [comment]
`Best-effort` opportunistically tries to attach Cilium's XDP program to the network interfaces. But as the warning text suggests, `bnxt_en` driver does not support Cilium's XDP program at this MTU.

**Comment by dudeisbrendan03** [comment]
I know this is a closed issue, but for reference for people looking into this!

XDP was built around a single-buffer design for faster packet processing, currently there isn't multi-buffer support so packets over 3505 bits cant be guaranteed to fit in a single page.

So sadly you cannot Tx/Rx Jumbo Frames or support LRO </3

There is [active work on trying to come up with an approach for multi-buffer support in XDP ](https://github.com/xdp-project/xdp-project/blob/main/areas/core/xdp-multi-buffer01-design.org)without slowing things down and figuring out a way to efficiently track data that may need to be split across multiple pages.

I'm not sure if any NICs support this- as I think this does prevent driver-level support too (but I may be completely wrong here)!
