### ISSUE TITLE
Cilium 1.16.3 on Linux 6.11.4 misclassifies cluster traffic as world

### ISSUE THREAD

**Issue by jfroy** [cilium/cilium#35436]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

After upgrading a node in my cluster from linux 6.11.2 to 6.11.4, most pods started failing their liveness/readiness probes. After looking into it, it appears cilium is classifying the probes as world traffic, which gets blocked by a default network policy.

This may be related to https://github.com/cilium/cilium/issues/34042 or https://github.com/cilium/cilium/issues/35060, but I am using veth mode.

### How can we reproduce the issue?

1. Install cilium from helm on any node running Linux 6.11.4
2. Install a network policy that blocks world traffic by default.
3. Watch pod probes start failing.

### Cilium Version

cilium-cli: v0.16.19 compiled with go1.23.2 on darwin/arm64
cilium image (default): v1.16.2
cilium image (stable): v1.16.2
cilium image (running): 1.16.3

### Kernel Version

6.11.4 (custom configuration based on Talos Linux)

### Kubernetes Version

Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.1

### Regression

This is a regression from Linux 6.11.2 to 6.11.4. Exact same kernel configuration, cilium version and configuration, kubernetes version and resource objects.

### Sysdump

[cilium-sysdump-20241019-182459.zip](https://github.com/user-attachments/files/17447973/cilium-sysdump-20241019-182459.zip)

### Relevant log output

```
xx drop (Policy denied) flow 0x179beb9b to endpoint 2284, ifindex 13, file bpf_lxc.c:2064, , identity world-ipv4->77519: 10.11.0.213:50322 -> 10.11.0.86:8080 tcp SYN
Policy verdict log: flow 0x81a4c6b8 local EP ID 932, remote ID world-ipv4, proto 6, ingress, action deny, auth: disabled, match none, 10.11.0.213:58570 -> 10.11.0.210:3300 tcp SYN
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jfroy** [comment]
I have a feeling in part [this patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/net/netfilter/xt_mark.c?h=v6.12-rc3&id=0bfcb7b71e735560077a42847f69597ec7dcc326) is bad. It at least clearly misassigns `NFPROTO_IPV4` to the IPv6 one.

**Comment by jfroy** [comment]
I've now tested linux 6.11.3 and I cannot reproduce. So something definitely broke cilium, at least in some configurations, between 6.11.3 and 6.11.4.

**Comment by julianwiedmann** [comment]
> I have a feeling in part [this patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/net/netfilter/xt_mark.c?h=v6.12-rc3&id=0bfcb7b71e735560077a42847f69597ec7dcc326) is bad. It at least clearly misassigns `NFPROTO_IPV4` to the IPv6 one.

yep, good catch! Looks like a kernel fix is already in progress: https://patchwork.ozlabs.org/project/netfilter-devel/patch/20241020124951.180350-1-pablo@netfilter.org/

**Comment by borkmann** [comment]
given this was applied and will make it into Linus' tree this week + stable after that, we can close this one
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=306ed1728e8438caed30332e1ab46b28c25fe3d8
