### ISSUE TITLE
Lbipam sharing-cross-namespace

### ISSUE THREAD

**Issue by batleforc** [cilium/cilium#35460]
### Test Category

New Feature

### Test Details

Hello, i'm testing the sharing-cross-namespace feature where I can share load balancer's IP who perfectly fit my need.
I try to share the main ip across my Traefik and my DNS (and more in the future), but the services that come second doesn't get an IP and the message:

```
    - type: cilium.io/IPAMRequestSatisfied
      status: 'False'
      lastTransitionTime: '2024-10-21T20:17:16Z'
      reason: already_allocated_incompatible_service
      message: >-
        The IP 'MY WONDERFUL IP' is already allocated to an incompatible service.
        Reason: different and not permitted namespace 
```

The ns are setup here :

- https://github.com/batleforc/Weebo4GitOps/blob/main/infra/app-main/sys-ns/outdns.yaml
- https://github.com/batleforc/Weebo4GitOps/blob/main/infra/app-main/sys-ns/traefik.yaml

The annotations was tested with :

lbipam.cilium.io/sharing-cross-namespace: "outdns,traefik,Outdns,Traefik,\*"
lbipam.cilium.io/sharing-cross-namespace: "*"
lbipam.cilium.io/sharing-cross-namespace: "outdns,traefik"

and the services:

- https://github.com/batleforc/Weebo4GitOps/blob/main/infra/helm/outdns/templates/service.yaml
- https://github.com/batleforc/Weebo4GitOps/blob/main/infra/ingress/traefik/app.yaml#L25-L27

and the cilium values:

- https://github.com/batleforc/Weebo4GitOps/blob/main/0.task/cilium/cilium-values.yaml
- https://github.com/batleforc/Weebo4GitOps/blob/main/infra/app-main/cni/l2.yaml

### Time

It took 3 hour to attempt this test

### Test Status

Failure: Reproducible bug encountered/filed

### Cilium Version

cilium-cli: v0.16.19 compiled with go1.23.1 on linux/amd64
cilium image (default): v1.16.2
cilium image (stable): v1.16.3
cilium image (running): 1.17.0-pre.1

### Kernel Version

Linux weebo3 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.5+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5+k3s1

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by batleforc** [comment]
I may or may not have missed something but i don't know what

**Comment by MustDie95** [comment]
Hi @batleforc, you should place lbipam.cilium.io/sharing-cross-namespace: "*" annotation on both services, not namespaces

"By default, sharing IPs across namespaces is not allowed. To allow sharing across a namespace, set the lbipam.cilium.io/sharing-cross-namespace annotation to the namespaces the service can be shared with. The value must be a comma-separated list of namespaces. **The annotation must be present on both services.** You can allow all namespaces with *."

**Comment by dylandreimerink** [comment]
@MustDie95 That is correct. Both services need the `lbipam.cilium.io/sharing-cross-namespace` annotation to be able to share it, this is a security feature to ensure both services agree to IP sharing. Otherwise this feature could be used to redirect traffic, in a multi-tenant cluster.

**Comment by batleforc** [comment]
Yes, and has of now the feature work perfectly for me, thanks for the quick answer
