### ISSUE TITLE
How to test latency in BPF+EDT

### ISSUE THREAD

**Issue by weli-l** [cilium/cilium#35464]
I have read this [Better Bandwidth Management with eBPF](https://kccnceu2022.sched.com/event/ytsQ/better-bandwidth-management-with-ebpf-daniel-borkmann-christopher-m-luciano-isovalent) in kubecon, but I cannot reproduce this test result with netperf. How can I use netperf to test the results shown below? Perhaps you can provide a test script or command?![Image](https://github.com/user-attachments/assets/e3d9b85b-a22d-4479-bb2c-9f4d381cbd94)

**Comment by weli-l** [comment]
@borkmann

**Comment by borkmann** [comment]
this was with netperf TCP_RR which can provide the p50, p90, p99 metrics.
