### ISSUE TITLE
1.14.16 Helm Chart renders broken image value

### ISSUE THREAD

**Issue by xrstf** [cilium/cilium#35487]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.14.13 and lower than v1.15.0

### What happened?

I downloaded the 1.14.16 Helm chart from https://github.com/cilium/charts, extracted it and ran `helm template .`.

In the output the Cilium Operator Daemonset uses `image: "quay.io/cilium/operator-generic:v1.14.16@%!s(<nil>)"`.

v1.14.15 works just fine. It also works fine to clone the Cilium repository, checkout the v1.14.16 tag and render the Chart in `install/kubernetes/cilium/`.

### How can we reproduce the issue?

1. Download the 1.14.16 Helm chart from https://github.com/cilium/charts
2. extracted it
3. run `helm template ./cilium`

### Cilium Version

v1.14.16

### Kernel Version

N/A

### Kubernetes Version

N/A

### Regression

The .tgz for 1.14.15 work fine.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
@xrstf thank you for the report. It's now fixed.
