### ISSUE TITLE
Add support for user-defined entities

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3553]
Allow users to define entities which contain specific CIDRs, so that policy can be written against these custom entities and the management of IPs that belong to the entity can be performed separately.

**Comment by julianwiedmann** [comment]
@joestringer there's an old doc reference to this issue:
https://github.com/cilium/cilium/blob/dff7aa1288febbba7eab15c7553cb4880806b1fc/Documentation/security/policy/language.rst?plain=1#L365

Is that still valid, or can we remove it from the docs?

**Comment by joestringer** [comment]
I think that https://github.com/cilium/cilium/pull/24638 provides pretty close to this functionality, but with two deviations: (1) They're defined in a new CIDRSet CRD, and (2) they can only select peers outside the cluster. That seems pretty good to me, the rest is likely syntactic sugar.

I'd be OK with removing that part of the docs at this point.
