### ISSUE TITLE
CI: Cilium E2E Upgrade - node-to-node-encryption - captured unexpected packets

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#35554]
## CI failure

It seems to have started occurring pretty frequently on scheduled runs (matrix entries 11 and 12) since yesterday:

* https://github.com/cilium/cilium/actions/runs/11518839863/job/32066517100
* https://github.com/cilium/cilium/actions/runs/11512190239/job/32046834021
* https://github.com/cilium/cilium/actions/runs/11507425344/job/32033587309
* https://github.com/cilium/cilium/actions/runs/11499967981/job/32009153158

```
❌ Captured unexpected packets (count=2 packets)
  ℹ️  Capture executed on cilium-test-2/host-netns-4mwr9 (kind-worker): tcpdump -i eth0 --immediate-mode -w /tmp/node-to-node-encryption.pcap ((udp and (udp[8:2] = 0x0800 or dst port 8472 or dst port 6081)) and host 172.18.0.2 and host 172.18.0.5) or (host 172.18.0.2 and host 172.18.0.5 and icmp)
  ℹ️  Captured packets:
13:26:27.230010 IP kind-worker > 172.18.0.5: ICMP echo request, id 1, seq 1, length 64
13:26:27.230210 IP 172.18.0.5 > kind-worker: ICMP echo reply, id 1, seq 1, length 64
```

**Comment by sayboras** [comment]
happened in https://github.com/cilium/cilium/pull/35538 as well 

https://github.com/cilium/cilium/actions/runs/11515486055/job/32097821408
