### ISSUE TITLE
Add support for Cilium connectivity test on IPv6-only clusters

### ISSUE THREAD

**Issue by Lattyware** [cilium/cilium#35553]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When running `cilium connectivity test` there is the assumption that the user can reach `1.1.1.1` which isn't the case in IPv6-only deployments, and as it is an IP, even with NAT64.

I did also try `cilium connectivity test --external-ip "2606:4700:4700::1111" --external-other-ip "2606:4700:4700::1001" --external-cidr "2606:4700:4700::/48"`, but it parses the last segment of IPv6 address to ports (putting them in square brackets straight up crashes it, and specifying a port like `2606:4700:4700::1111:443` after seems to work-ish but is surprising and non-obvious, and seems to still cause the tests to fail).

### How can we reproduce the issue?

- Install with IPv6 connectivity only.
- Run `cilium connectivity test`

### Cilium Version

1.16.2

### Kernel Version

6.8.0-47-generic

### Kubernetes Version

v1.30.5+k3s1

### Sysdump

N/a

### Relevant log output

N/a

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report. I think it makes sense for the CLI connectivity tests to work in IPv6-only environments, we can treat this as an enhancement request.

**Comment by wedaly** [comment]
I'd be interested in working on this. If no one else has started it yet, feel free to assign to me.
