### ISSUE TITLE
envoy: Log new connections at info or below

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3557]
https://github.com/cilium/cilium/blob/4e5f05048166603b631147e63328e4e8b0b6d074/envoy/cilium_network_filter.cc#L55

**Comment by ishantanu** [comment]
@joestringer If I am not mistaken, as the decription says, the loglevel of new connections should be changed from `warn` to `info`, right? Is there anything else which needs to be taken care of? If not, I'll send a PR for this.
