### ISSUE TITLE
cilium-cli: install --repository flag doesn't take effect when there is a cached version

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#35629]
reported by @giorio94 if a helm chart with a given version is cached, cilium-cli always uses the cached version even when you override the helm repo with --repository flag.

**Comment by michi-covalent** [comment]
@renyunkang are you interested in working on it? sorry there is no `/assign` command in cilium repo but i can assign the issue to you if you are interested.

fyi this is the function that downloads and caches helm charts => https://github.com/cilium/cilium/blob/aac7cf581801dded5e0177ae3a89e43d79467909/cilium-cli/internal/helm/helm.go#L74

**Comment by renyunkang** [comment]
> interested in working on it

Yes, I'm interested in working on this. Could you please assign it to me?
