### ISSUE TITLE
Micro: Convert pkg/maps/ctmap to use Map interface of pkg/bpf/

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#357]
Allows to get rid of cgo usage in pkg/maps/

**Comment by aalemayhu** [comment]
Is this referring to some other branch? Not seeing see that path on master.

    $ ls pkg/maps/
    ls: cannot access 'pkg/maps/': No such file or directory

**Comment by tgraf** [comment]
I noticed this will working on #354, the path will exist after that PR is merged.

**Comment by ianvernon** [comment]
I'm going to rename this ticket to only cover ctmap, and then have other tickets for each map type to make the changes more modular, as the changes were ctmap were fairly extensive.
