### ISSUE TITLE
Reject non-TCP L4 rules if L7 rules are specified

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3573]
We currently ignore L7 rules for non UDP in `pkg/policy/l4.go:CreateL4*Filter()`. We should instead reject such rules in verification instead of ignoring the rules.

**Comment by ianvernon** [comment]
Also related-to https://github.com/cilium/cilium/issues/3401 . We need to do more sanitization of L7 rules.

**Comment by ianvernon** [comment]
Related: https://github.com/cilium/cilium/issues/1997 .
