### ISSUE TITLE
[hubble] hubble_kafka_requests_total error_code contains undefined unicode character �

### ISSUE THREAD

**Issue by nddq** [cilium/cilium#35749]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

I’m testing Hubble Kafka metrics in a BYO CNI AKS cluster and observed that the hubble_kafka_requests_total metric displays an undefined Unicode character for the error code:

![Image](https://github.com/user-attachments/assets/8e3fd2d9-ca83-46e7-a270-8383d791c68a)

Upon reviewing the code, I found that Hubble uses `string()` to convert `kafka.ErrorCode`:

![Image](https://github.com/user-attachments/assets/eea6e24f-ff86-4cb3-b12d-5f62f53f8bad)

Is this the intended behavior? Would it be more appropriate to use `strconv.Itoa` instead?

### How can we reproduce the issue?

Installed Cilium with this command
```
cilium install --version 1.15.10 --set azure.resourceGroup="${AZURE_RESOURCE_GROUP}" --set envoy.enabled=true --set prometheus.enabled=true --set hubble.enabled=true --set hubble.metrics.enabled="{flow:sourceEgressContext=pod;destinationIngressContext=pod,flows-to-world:sourceEgressContext=pod;destinationIngressContext=pod,httpV2:sourceEgressContext=pod;destinationIngressContext=pod,kafka:sourceEgressContext=pod;destinationIngressContext=pod}"
```

### Cilium Version

v1.15.10

### Kernel Version

5.15.0-1073-azure

### Kubernetes Version

v1.30.5

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Nice find! I'd suggest to open a PR with the suggested change, and take it from there.
