### ISSUE TITLE
Warning `Unable to translate all CIDR groups to CIDRs`

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#35772]
This warning is popping up in upgrade tests:
```
msg="Unable to translate all CIDR groups to CIDRs" cidrGroupRef="[cilium-test-external-cidr]" ciliumNetworkPolicyName=client-egress-to-cidrgroup-deny error="cidr group \"cilium-test-external-cidr\" not found, skipping translation" k8sApiVersion= k8sNamespace=cilium-test-1 subsys=policy-k8s-watcher
```
For example, in https://github.com/cilium/cilium/actions/runs/11666057454/job/32480491151.

cc @squeed @joestringer

**Comment by squeed** [comment]
So, the cause of this is that we added testing for CiliumCIDRGroups in v1.17, and we're executing these tests against a v1.16 cluster as part of the upgrade-downgrade test.

(This error message doesn't even exist in v1.17+, as it's been removed).

It should probably be ignored; there's no good way to wait to see that the daemon has processed the CCG. It doesn't indicate any sort of new logic issue or error condition.

**Comment by joestringer** [comment]
@squeed how will a user know if they've made a typo in the policy or didn't yet create the CCG?

**Comment by squeed** [comment]
@joestringer I don’t have a good answer for this; the selector mechanism in general doesn’t consider empty selectors to be an error or warning condition.

Agent error logs may not be accessible to policy authors regardless.

Perhaps the time is ripe for a Warnings column in the policy validation controller.

**Comment by joestringer** [comment]
Ah right, yes the cilium-operator could "validate" the policy and report in the status when the CCG is not present.
