### ISSUE TITLE
Cilium agents start duplicate Service/Endpointslice informers

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#35797]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Starting from v1.16, each Cilium agent starts two services and endpointslices informers, introducing extra load on the Kubernetes API Server. The main commits that appear to contribute to the regression are 99268e7ba1c7, cce40804c3ac and 0e8c5a64f37a,  because a few consumers leverage the filtered resources, while a few others the unfiltered ones.

The best fix is probably dropping the filtered resource altogether (assuming it is possible, adapting the consumers accordingly), to prevent regressions in the future due to the mixed usage of the two resources.

### How can we reproduce the issue?

This issue can be validated checking the `apiserver_longrunning_requests` Kubernetes API Server metric. For instance, on a four nodes kind cluster:

```
# Cilium agents are not running
$ kubectl get --raw /metrics | grep apiserver_longrunning_requests | egrep '"services|endpointslices"'
apiserver_longrunning_requests{component="apiserver",group="",resource="services",scope="cluster",subresource="",verb="WATCH",version="v1"} 13
apiserver_longrunning_requests{component="apiserver",group="discovery.k8s.io",resource="endpointslices",scope="cluster",subresource="",verb="WATCH",version="v1"} 7

# Cilium agents are running
$ kubectl get --raw /metrics | grep apiserver_longrunning_requests | egrep '"services|endpointslices"'
apiserver_longrunning_requests{component="apiserver",group="",resource="services",scope="cluster",subresource="",verb="WATCH",version="v1"} 21
apiserver_longrunning_requests{component="apiserver",group="discovery.k8s.io",resource="endpointslices",scope="cluster",subresource="",verb="WATCH",version="v1"} 15
```

### Cilium Version

Cilium v1.16 and above

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MrFreezeex** [comment]
Ah indeed that's a very nice catch!

> The best fix is probably dropping the filtered resource altogether (assuming it is possible, adapting the consumers accordingly), to prevent regressions in the future due to the mixed usage of the two resources.
> /cc @MrFreezeex FYI. Would you be interested working on the fix?

Yes I agree, I can definitely check to do that fix indeed! :D
