### ISSUE TITLE
CFP: Enhance Limiting Identity-Relevant Labels user journey

### ISSUE THREAD

**Issue by ovidiutirla** [cilium/cilium#35833]
### Problem: 
Currently, modifying the [cilium/identity-relevant-labels](https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/) filter requires restarting all Cilium agents. As we move towards operator-managed CIDs, this will also necessitate restarting the operator, adding complexity for cluster administrators.

### Proposal: 
Leverage dynamic configuration ([CFP: Dynamic ConfigMap](https://github.com/cilium/cilium/issues/34101)) to allow both agents and operator to watch the labels filter config key and react to changes without requiring a restart. Reconciliation would be triggered by manually modifying the labels filter in the ConfigMap.

### Next Steps: 
I am seeking feedback on this proposal and am happy to draft a more detailed design document if there is sufficient interest. Please share your thoughts and opinions.

### Discussion from Slack so far:

> @aanm: Changing the filter labels for all agents at the same time might have scale implications since they could cause DDoS of the identity-backend. How could we avoid such scenario?
@marseel: I would say if operator manages identities - this is fine in terms of identities. Reconciliation of CiliumEndpoint/CES with new identities is more problematic imho.
@ovidiutirla: I think there are two scenarios here: When Operator Manages CIDs, When Agent Manages CIDs
with 2, we could add a random delay depending on the cluster size; with 1, the identities will be handled by the operator and agents will just wait for the identity propagation, while the old identities will still be present until all agents moves to the new identity. From the above proposal, the labels filter will only change during manual interaction (i.e modifying the ConfigMap). We can also rate limit the number of changes from the ConfigMap to ensure the manual interactions will not overload
@aanm We would need to understand how big the delay is and if it had any security implications associated with it as well as have a way to report that to users.
@ovidiutirla My goal here is to simplify the user journey when updating the labels filter as it becomes more and more complex to update these filters when the CIDs will be managed by Operator. I understand your concern, and I think is totally valid, so I hope we'll get some great ideas to enhance this area. :slightly_smiling_face: Similarly, right now there is manual interaction to restart cilium-agents so the delay will still be there tho, we could expose a metric to highlight the drift delay for applying the propagation at agent side too. Applying the labels update and new identities propagation would still cause less load (from kube-apiserver/KCP perspective and nodes itself as we do not need to re-create all the watchers etc)

> @joestringer: At a high level, this option should not be changing dynamically - we should be able to establish very clear outlines with users when they set up the clusters about which labels are security-relevant or not. I can understand if the wrong decision was made in the first place that having a process to update it would be good, but I don't think that we should be designing the solution to this in order to try to support dynamic updates of this setting on a regular basis.
In the extreme case, it's impossible to reconcile a change in this configuration setting. That's the biggest danger.
My gut feeling would be to tackle this problem more as something we resolve with outside structured tooling to perform the migration rather than integrating it into Cilium to dynamically react to changes in the cluster.
That is, even if the code / process / etc is in the Cilium codebase, build specific tools for the migration rather than expecting cilium-agent/cilium-operator to dynamically react to arbitrary requests to change security-relevant properties.
At some level, cilium-agent would have to learn about the change in security identity for an Endpoint and make that happen, so I guess there is a question about exactly where the line is there and how that could work well
But let's say we have a dedicated tool to assess the change and calculate how the migration is going to work, how the identity pool will be used, and then be responsible for gradually performing the migration.
I think that structure would make it much less likely to shoot yourself in the foot. Another big concern would be if we have to reuse numeric identities, then there needs to be proper separation of the usage to make sure that some agent doesn't make the wrong network policy decision due to the change in meaning for the numeric identity
anyway all of these thoughts are why I think we shouldn't be discussing this on Slack - all of this context will be lost if we don't move it somewhere more permanent.

Let's keep the discussion ongoing and align on the solution.
/cc @aanm @cilium/sig-scalability @joestringer @liyihuang @sypakine @dlapcevic @wedaly

**Comment by liyihuang** [comment]
it's a good idea but I personally think the dynamic configmap will cause more confusing and more problems. 
1. which config can be hot reload and which can't, and it's hard to be remembered. If there are some config can be reloaded and some can't.  I tend to restart the pods anyway to make sure the new config got reloaded.
2. some label change can be very expensive. As far as I know label change on namespace can be very expensive to CPU and memory. Alibaba cloud shared their experience in their kubecon China this year(https://static.sched.com/hosted_files/kccncossaidevchn2024/bf/KubeCon%20China%20%202024%20slides.pdf?_gl=1*1t3rhpw*_gcl_au*OTY4MTY4MzkyLjE3MzA5OTY4OTA.*FPAU*OTY4MTY4MzkyLjE3MzA5OTY4OTA.) search Real world disasters page from the slides. Dynamic config might cause some issues that users might not expect.

Is the concern restarting agent and operator will cause the network disruption?
