### ISSUE TITLE
Warnings on clustermesh startup

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#35865]
On clustermesh startup, we're getting a bunch of warnings as follows. Those probably shouldn't be warnings (or should be happening) given they're just signaling transitory startup issues while everything settles down.
```
msg="Unable to get remote cluster configuration" clusterName=c1 error="failed to retrieve cluster configuration: not found" hint="If KVStoreMesh is enabled, check whether it is connected to the target cluster. Additionally, ensure that the cluster name is correct."
msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/c1 endpoints="[https://clustermesh-apiserver.kube-system.svc:2379/]" error="context canceled" prefix=cilium/.heartbeat
msg="Error observed on etcd connection, reconnecting etcd" clusterName=cluster2-with-long-name-01234567 error="etcd cluster ID has changed: expected 11231715032166824766, got 10786513292270824672"
msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/cluster2-with-long-name-01234567 endpoints="[https://cluster2-with-long-name-01234567.mesh.cilium.io:32380/]" error="etcdserver: permission denied" prefix=cilium/.heartbeat
```
From https://github.com/cilium/cilium/actions/runs/11661644313.

cc @giorio94

**Comment by giorio94** [comment]
I've opened https://github.com/cilium/cilium/pull/35867 to silence most spurious logs. 

I'd honestly prefer to leave `Error observed on etcd connection, reconnecting etcd` at warning level, and ignore it in the CLI though. Although it is expected that it occurs if the remote clustermesh-apiserver is restarted, IMO it is still better to keep it visible given that it triggers expensive operations, and a high number of occurrences is typically a symptom of other problems.

**Comment by pchaigno** [comment]
What's a high number of occurrences? You know what I'm going to suggest next 😅 

More seriously, I don't mind either way.

**Comment by giorio94** [comment]
> What's a high number of occurrences? You know what I'm going to suggest next 😅

Yes, I thought about having some sort of counter, or making it based on the time since the last occurrence, but it can get quickly pretty messy (especially because in the upgrade/downgrade tests it would fail a few times in a short time window) for relatively little value. I'd keep things simple and just ignore it.

> Another one:
>```
>time="2024-11-08T11:32:23.000648396Z" level=warning msg="Error getting CEP" ciliumEndpointName=kube-system/clustermesh-apiserver-c8d8885c4-8chqs containerID=c6a50cc764 containerInterface=eth0 controller="sync-to-k8s-ciliumendpoint (1336)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1336 error="Get \"[https://10.243.0.1:443/apis/cilium.io/v2/namespaces/kube-system/ciliumendpoints/clustermesh-apiserver-c8d8885c4-8chqs?resourceVersion=0\](https://10.243.0.1/apis/cilium.io/v2/namespaces/kube-system/ciliumendpoints/clustermesh-apiserver-c8d8885c4-8chqs?resourceVersion=0\)": context canceled" identity=77535 ipv4=10.242.1.81 ipv6="fd00:10:242:1::b043" k8sPodName=kube-system/clustermesh-apiserver-c8d8885c4-8chqs subsys=endpointsynchronizer (1 occurrences)
>```

Hmm, this is not clustermesh related actually. The fix looks pretty easy, likely just skipping the warning log if the error is _context canceled_ [here](https://github.com/cilium/cilium/blob/aa0a7d7c781a6f9ecdac52c62b367a3f40cc2815/pkg/endpointmanager/endpointsynchronizer.go#L208-L210). However, I guess there will be quite a few more of this type that may come up from time to time.

**Comment by tommyp1ckles** [comment]
Hitting this on a test doing downgrade to v1.14: https://github.com/cilium/cilium/actions/runs/12058380700/job/33624971131

Do we need to backport this to 1.14/1.15?

**Comment by tommyp1ckles** [comment]
I see the fix is marked for backport, reopening until then 🙂
