### ISSUE TITLE
CI: Runtime L3L4  Test connect timeout

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#3588]
```
time="2018-04-07T19:48:22Z" level=debug msg="running command: docker exec -i  app3 curl -s --fail --connect-timeout 5 --max-time 5 http://10.15.80.29:80/public"
cmd: "docker exec -i  app3 curl -s --fail --connect-timeout 5 --max-time 5 http://10.15.80.29:80/public" exitCode: 28 
```

It happen here https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/2138/testReport/junit/(root)/runtime/RuntimeValidatedPolicies_L3_L4_Checks/

Logs: 
[test_results_Cilium-PR-Ginkgo-Tests-Validated_2138.tar.zip](https://github.com/cilium/cilium/files/1896872/test_results_Cilium-PR-Ginkgo-Tests-Validated_2138.tar.zip)

**Comment by eloycoto** [comment]
@aanm this issue is not related with no space left on device, the exit code means connection timeout: 
https://curl.haxx.se/libcurl/c/libcurl-errors.html

**Comment by aanm** [comment]
@eloycoto Exactly but why did we get out of space in the first place?

**Comment by eloycoto** [comment]
@aanm where do you see that the server is running out of space?

**Comment by aanm** [comment]
@eloycoto ah sorry I misread your answer. You're right

**Comment by ianvernon** [comment]
@aanm this failure was during a PR run. I see that it failed in your 'race detector' PR. Does this mean we should treat this as a master build since there aren't really any code changes apart from running with race detection?

**Comment by aanm** [comment]
@ianvernon I can't really tell, but I just want to keep track on all test flakes to get a better knowledge when they start showing up

**Comment by ianvernon** [comment]
Updated the description with the logs from the build since we auto-delete builds from Jenkins after some time. 

@aanm makes sense. In this case, given that while it was ran in a branch, but that the only delta in the branch from master was running Cilium with race detection, this makes sense to triage.

**Comment by tgraf** [comment]
Never seen again
