### ISSUE TITLE
Unable to join cilium slack....again

### ISSUE THREAD

**Issue by taliastocks** [cilium/cilium#35901]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Trying to access slack.cilium.io results in me being redirected to https://cilium.slack.com/signup#/domain-signup where I can only sign in with an email from a couple of domains. It does not take me to an invite form.

In the [main documentation pages for cilium](https://docs.cilium.io/en/stable/) the "Join Slack" button links to the [herokuapp](https://cilium.herokuapp.com/) domain, which no longer works.

### How can we reproduce the issue?

Access https://slack.cilium.io/ in a browser without a session to Slack
Observe that it redirects you to the domain signup page, rather than the invitation page.

### Cilium Version

Latest

### Kernel Version

n/a

### Kubernetes Version

n/a

### Regression

Yes, this is reopening https://github.com/cilium/cilium/issues/35128 again, which reopened https://github.com/cilium/cilium/issues/34689, which I believe reopened https://github.com/cilium/cilium/issues/25045. Also reported previously:

- https://github.com/cilium/cilium/issues/24447
- https://github.com/cilium/cilium/issues/32207
- https://github.com/cilium/cilium/issues/29103
- https://github.com/cilium/cilium/issues/31639

### Sysdump

n/a

### Relevant log output

```shell
n/a
```

### Anything else?

n/a

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by xmulligan** [comment]
Can you check again? It should be working now

cc: @paularah

**Comment by taliastocks** [comment]
Thank you!

**Comment by rptaylor** [comment]
Same issue, https://cilium.herokuapp.com/ gives a Heroku error.  How can I get an invitation to Cilium Slack? Thanks!  @xmulligan @paularah

**Comment by xmulligan** [comment]
https://slack.cilium.io/

That link has been updated in all but the latest branches. Will be soon there too https://github.com/cilium/cilium/issues/37227#issuecomment-2657448513

**Comment by rptaylor** [comment]
> https://slack.cilium.io/

I tried that link earlier and it did not work, but now it does. Just now it allowed me to join with a non-Linux Foundation email domain. Thanks!
