### ISSUE TITLE
Packet drop during policy import

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3592]
When repeatedly importing a label-dependent l4 ingress policy, I observe packet drops in monitor:

```
Apr 07 00:33:40 xx drop (Policy denied (L3)) flow 0x85b0f1ff to endpoint 38939, identity 48165->42447: 10.11.42.252:38506 -> 10.11.250.189:80 tcp SYN
```

Create Cilium Docker network:
* `docker network create --ipv6 --subnet ::1/112 --ipam-driver cilium --driver cilium cilium-net`

Running two containers:
* `docker run -d --name app1 --net cilium-net -l "id=app1" cilium/demo-httpd`
* `docker run -d --name client --net cilium-net -l "id=app1" -l "extra=client" cilium/demo-client`

I set up three windows, running:
* `cilium monitor -t drop`
* Repeated calls to `curl` from `client` to `app1` (every 0.02 seconds)
* Repeatedly import a policy at a similar rate

Policy:
```
[{                                            
    "endpointSelector": {"matchLabels":{"container:id":"app1"}},                            
    "ingress": [{                             
        "toEndpoints": [                      
            {"matchLabels":{"id":"app1"}}     
        ],                                    
        "toPorts": [                          
            {"ports":[ {"port": "80", "protocol": "TCP"}]}                                  
        ]                                     
    }]                                        
}]
```

The effective policy does not change, so there's no reason to drop packets via policy. The datapath drop due to `DROP_POLICY` suggests that a map is momentarily not populated with the policy entry for the datapath, which further suggests that userspace is removing and reinserting the entry during policy import when unnecessary.

---

NOTE: Running this for more than a few seconds will likely get Cilium into a bad state due to #3593, symptoms include high CPU usage, journald high CPU due to becoming swamped with logging requests. Keep an eye out for /var/log/syslog becoming too large due to all the debug output.

**Comment by ianvernon** [comment]
Do you have Cilium logs from when this was ran? Would be interesting to correlate these drops with timestamps in the Cilium logs.

**Comment by joestringer** [comment]
@ianvernon not currently, because CT logging is too verbose and bug #3593 DoSes journald.

**Comment by joestringer** [comment]
Briefly discussed offline, an alternative next step would be to reproduce as per above, but disable `flowdebug` logging.

**Comment by ianvernon** [comment]
Noted that this still occurs on latest master (commit 1df6acc7e545ae8a2be4c9cb9af008dbfb72d493).

**Comment by ianvernon** [comment]
I'm going to remove my assignment from this as I am not actively working on it right now.

**Comment by joestringer** [comment]
This would be interesting to look again at with latest master after several changes were made during the v1.3 dev cycle.

**Comment by joestringer** [comment]
Many changes have been made in this area since the original report, it is likely to be fixed already. Closing.
