### ISSUE TITLE
Memory leakage warning related to mutation detector in klog

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#35929]
```
level=warning msg="Mutation detector is enabled, this will result in memory leakage." subsys=klog
```
From https://github.com/cilium/cilium/actions/runs/11800209320/job/32870588612?pr=35723.

**Comment by squeed** [comment]
Is this a bug? It should only appear when the environment variable `KUBE_CACHE_MUTATION_DETECTOR` is set. I assume we should ignore this error message?

**Comment by pchaigno** [comment]
If this is expected, we can close this issue 🙂
