### ISSUE TITLE
BGPV2: Support Node Level LocalASN Overrides

### ISSUE THREAD

**Issue by TechABC** [cilium/cilium#35925]
Hello,

We recently started using Cilium as our main CNI on several on-premises clusters and it has been working well so far. We're leveraging external BGP peering between our nodes and our top-of-rack switches.

One area we're currently finding verbose in our BGP configuration resources is the lack of a `LocalASN` field in the `CiliumBGPNodeConfigOverride` CRD. Having this field would allow us to define only one `CiliumBGPClusterConfig` per rack instead of needing to redefine one for each node.

Is this something you would consider adding in a future version of the `CiliumBGPNodeConfigOverride` CRD?

Thank you for your time and consideration.
Best regards

**Comment by YutaroHayakawa** [comment]
I think it's easy to add it, but my gut feeling is your problem should be solved by auto-assigning local ASN with some sort of cluster-wide ASN allocator instead of creating override for each node. I have presented the similar idea here (https://github.com/cilium/cilium/issues/22133) and probably we need the similar one for RouterID to achieve it (https://github.com/cilium/cilium/issues/30333). WDYT?

**Comment by TechABC** [comment]
Hi @YutaroHayakawa, thank you for your feedback.

We completely agree that a cluster-wide ASN allocator would be a great solution to streamline the process and address the need for consistency across nodes.

That being said, we believe there could still be value in allowing the explicit assignment of a `LocalASN` at the node level through the `CiliumBGPNodeConfigOverride` CRD. Having the flexibility to handle both use cases, automatic allocation via a cluster-wide allocator and manual assignment when needed, would provide greater versatility and adaptability to various deployment contexts.

Thanks & regards

**Comment by YutaroHayakawa** [comment]
Sure, I don't have any objection for having that option. Any thoughts @harsimran-pabla @rastislavs?

**Comment by harsimran-pabla** [comment]
Yep, we can add node specific override. @TechABC will you contribute to introduce this change in Cilium?

**Comment by TechABC** [comment]
We’re willing to give it a try, but we have very limited experience contributing to Cilium, so our progress might not be the fastest. We'll do our best to move this forward.

Thanks & regards
