### ISSUE TITLE
Every time a policy import occurs, a new goroutine cleaning CT is started

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3593]
These should always eventually complete, however if someone makes repeated requests to change policy from the API, it can queue hundreds of goroutines, all sweeping the BPF maps attempting to clean CT.

https://github.com/cilium/cilium/blob/f3511952f1ea1a27d403e8bba9098a9e5334c8db/pkg/endpoint/bpf.go#L434-L457

We should probably wrap this in some queue as we don't need more than one running at a time.

**Comment by aanm** [comment]
`pkg/serializer/func_queue` please :smile:

**Comment by joestringer** [comment]
@aanm didn't realise this was already librarized, awesome!

**Comment by joestringer** [comment]
Looks like we'll need another variation on the `Enqueue()` because there's no point in serializing dozens of goroutines to execute the conntrack cleanup, if there's one queued then that's enough and the subsequent API check just needs to wait on the existing queued function to complete before it returns.

**Comment by ianvernon** [comment]
Given that #3605 was merged, I think this can be closed; @joestringer can you confirm?

**Comment by joestringer** [comment]
LGTM.
