### ISSUE TITLE
1.0 Documentation Review

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3597]
We are performing a complete review of the Documentation for 1.0. Please look at the following sections according to your assignment and leave commands on gaps that need to be addressed.

## Main Docs:
- [ ] Introduction to Cilium (@tgraf)
- [ ] Getting Started Guides
  - [x] Minikube (@manalibhutiyani)
  - [x] Kafka (@aanm)
  - [x] gRPC (@eloycoto) PR out for review https://github.com/cilium/cilium/pull/3644
  - [ ] Mesos
  - [ ] Docker Compose
- [ ] Concepts (@tgraf, @raybejjani, @jrajahalme)
- [x] Getting Help (@eloycoto) PR out for review https://github.com/cilium/cilium/pull/3650
- [ ] Integrations
  - [ ] Kubernetes (@jrajahalme)
  - [ ] Istio (@rlenglet, @tgraf)
  - [x] Docker (@raybejjani)
  - [ ] Mesos
- [x] System Requirements (@raybejjani)
- [ ] Installation Guides (@manalibhutiyani)
- [x] Upgrade Guide (@nebril)
- [ ] Network Policy (@ianvernon, @joestringer, @jrajahalme, @manalibhutiyani)
  - *Please independently review and extend #3539*
- [x] Monitoring & Metrics (@raybejjani)
- [x] Troubleshooting (@aanm)
- [ ] Developer & Contributor Guide (Excluded for now)
- [x] BPF & XDP Reference Guide (@borkmann)
- [x] API Reference (@nebril) #3652 under review
- [x] Command Cheatsheet (@eloycoto) PR https://github.com/cilium/cilium/pull/3617 ready to review
- [ ] Command Reference (@ianvernon)
    - Reviewed the docs and fixed some misc. things: https://github.com/cilium/cilium/pull/3759
    - Issue with dead links depending on what page you are on: https://github.com/cilium/cilium/issues/3260
- [ ] Further Reading

## Auxiliary docs
- [ ] README

**Comment by borkmann** [comment]
Linking #1413 here as well.

**Comment by nebril** [comment]
API Reference: http://docs.cilium.io/en/latest/api/#compatibility-guarantees mentions that we will declare the overall API stable with the release of version 1.0.

**Comment by nebril** [comment]
API Reference: API object schema would be nice to have, but it seems like `openapi` directive we use doesn't support rendering schema from swagger yaml file.

**Comment by manalibhutiyani** [comment]
Minikube GSG audit:  #3670

**Comment by manalibhutiyani** [comment]
Top 3 documentation gaps:

 1. Keep the `cilium cheatsheet` and `cilium command reference` updated with recent bpf commands, missing commands et al.

- cilium monitor -t L7 missing
- Many ct/bpf commands are missing.
- Microscope commands missing. Have a separate section for this
- set config missing
- policy tracing `-v` option

2. `Cilium related K8s commands:` on cheat sheet as well as command docs
 - kubectl get cnp
 - Kubectl get cep.
   More documentation/examples on `kubectl get cep`? 
   Will be good to have a brief summary of what this command does?


3. A diagrammatic view of CILUM data path and cilium internal module interaction —> Also requested by an external user on slack. This can be part of the `concepts` section in the docs.

**Comment by raybejjani** [comment]
@manalibhutiyani funny you mention CEP docs. I have it on my list to do this week :)
