### ISSUE TITLE
Is `ipam.mode=kubernetes` required for local kind clusters?

### ISSUE THREAD

**Issue by shinebayar-g** [cilium/cilium#36010]
[Documentation](https://docs.cilium.io/en/stable/installation/kind/) uses `ipam.mode=kubernetes` option but doesn't explain why. Is this option required on kind clusters? Default `cilium install` command seems to be working fine. I don't know what I'd be missing if this option is not set.

**Comment by joestringer** [comment]
There are various options for IPAM documented here: https://docs.cilium.io/en/stable/network/concepts/ipam/#address-management . Kubernetes is a simple general purpose option, but you can choose an alternative if you like.

**Comment by shinebayar-g** [comment]
Ah okay. Good to know that it wasn't something specific to kind.
