### ISSUE TITLE
bugtool: heap profile not usable

### ISSUE THREAD

**Issue by espringsteen** [cilium/cilium#36057]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.10 and lower than v1.16.0

### What happened?

We are trying to investigate an increase in memory used by cilium pods when we upgraded to 1.15.7 a few weeks ago. We have a number of pods using more than the 2GB memory request (some even getting killed after surpassing 2.5 memory limit). We were trying to investigate the issue by taking a memory profile following the [debugging docs](https://docs.cilium.io/en/stable/contributing/development/debugging/#cpu-profiling-and-memory-leaks). But the profile looked like this
![Image](https://github.com/user-attachments/assets/47922c90-cb34-4a1c-81c4-9c756edb5db2)

Note the CPU profile looks normal.

As a workaround I used `kubectl -n kube-system exec cilium-XXXXX -- gops pprof-heap 1` to get a graph that is usable. It however does not account for the full amount of memory I see Cilium taking at the time, so I thought I needed to have a higher trace duration which I saw was possible with the bugtool.

### How can we reproduce the issue?

1. Add the following to the cilium-config
``` 
 pprof: "true"
 pprof-address: localhost
 pprof-port: "6062"
```
2. Run `kubectl exec -it -n kube-system <cilium-pod-name> -- cilium-bugtool --get-pprof --pprof-trace-seconds 30 --pprof-port 6062`
3.  Copy out the file `kubectl cp -n kube-system <cilium-pod-name>:/tmp/cilium-bugtool-<time-generated-name>.tar ./cilium-pprof.tar`
4. `tar -xvf ./cilium-pprof.tar`
5. `cd cilium-bugtool-<time-generated-name>/cmd`
6. `go tool pprof -http localhost:9090 pprof-heap`

### Cilium Version

v1.15.7

### Kernel Version

5.15.168-114.166.amzn2.x86_64

### Kubernetes Version

1.29

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
You need to do `go tool pprof -http localhost:9090 pprof-heap <cilium-agent-binary>`

**Comment by giorio94** [comment]
Related: https://github.com/cilium/cilium/pull/33707

**Comment by espringsteen** [comment]
Thank you @giorio94 using `cilium-bugtool --get-pprof --pprof-trace-seconds 30 --pprof-port 6062 --pprof-debug 0` created a graph that is more usable.
