### ISSUE TITLE
[v1.14 / v1.15] renovate: re-enable updates for complexity image

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/cilium#36184]
https://github.com/cilium/cilium/pull/36135/commits/375d0acce75e2b9bfcfec40ebe40facb696c8090 disabled the updates for the `complexity-test` LVH image on v1.14 and v1.15. Once https://github.com/cilium/little-vm-helper-images/issues/674 is resolved, we should re-enable the renovate updates.

**Comment by tklauser** [comment]
Updates to LVH images are Currently blocked by https://github.com/cilium/little-vm-helper-images/issues/778, so working on that one first.

**Comment by julianwiedmann** [comment]
Of note - we recently bumped the LLVM version for Cilium v1.17. So I think now we need LVH images with
* LLVM 10: Cilium v1.14, v1.15
* LLVM 17: Cilium v1.16
* LLVM 18: Cilium v1.17

**Comment by tklauser** [comment]
The [linked issue](https://github.com/cilium/little-vm-helper-images/issues/674) states:

> Build Cilium minor-specific variants of complexity-test, which pull in the LLVM version of that minor release.

Given the [LLVM<->Cilium list above](https://github.com/cilium/cilium/issues/36184#issuecomment-2536356320), it seems to me that we could also have one `complexity-test` image per LLVM version not necessarily per Cilium version, i.e. 3 images instead of 4? Or better play it safe and always have one `complexity-test` image per Cilium version?

**Comment by julianwiedmann** [comment]
> Given the [LLVM<->Cilium list above](https://github.com/cilium/cilium/issues/36184#issuecomment-2536356320), it seems to me that we could also have one `complexity-test` image per LLVM version not necessarily per Cilium version, i.e. 3 images instead of 4? Or better play it safe and always have one `complexity-test` image per Cilium version?

Ack that's the trade-off I had in my mind as well. I think either one is fair - the needed infrastructure work should roughly be the same? So we can probably start with the "one image per LLVM version" approach. And maintain some sort of mapping in the lvh repo which cilium image should be used to pull those LLVM versions from.

Also given that v1.14 is EOL fairly soon, I'd not invest too much into that distinction between v1.14 and v1.15.

**Comment by tklauser** [comment]
> > Given the [LLVM<->Cilium list above](https://github.com/cilium/cilium/issues/36184#issuecomment-2536356320), it seems to me that we could also have one `complexity-test` image per LLVM version not necessarily per Cilium version, i.e. 3 images instead of 4? Or better play it safe and always have one `complexity-test` image per Cilium version?
> 
> Ack that's the trade-off I had in my mind as well. I think either one is fair - the needed infrastructure work should roughly be the same? So we can probably start with the "one image per LLVM version" approach. And maintain some sort of mapping in the lvh repo which cilium image should be used to pull those LLVM versions from.

Yeah, I think the infrastructure work would be roughly the same so it won't make a huge difference which approach we take from a image build perspective.
 
> Also given that v1.14 is EOL fairly soon, I'd not invest too much into that distinction between v1.14 and v1.15.

👍

**Comment by tklauser** [comment]
This might be relevant: https://github.com/cilium/cilium/blob/5c08f9593c3e1c6f2012087a67ff1e2f3e4b1e87/.github/workflows/tests-datapath-verifier.yaml#L151-L155

The workflow is overwriting the LLVM version shipped in the image by the one extracted from the cilium-builder image corresponding to the branch the PR was opened against.

**Comment by tklauser** [comment]
So maybe the easier solution is to backport that snippet to `v1.14` and `v1.15` instead of having to build even more lvh images.

**Comment by julianwiedmann** [comment]
> The workflow is overwriting the LLVM version shipped in the image by the one extracted from the cilium-builder image corresponding to the branch the PR was opened against.
> 
> For more details, see [#31754](https://github.com/cilium/cilium/pull/31754) which added the above snippet.

uff that completely dropped from my memory - and I even commented on the PR whether the LVH part can go away now ...

yep let's give that a try!

**Comment by tklauser** [comment]
Looks like it's straight forward to backport the commit that introduced the extraction of LLVM from cilium-builder:

* `v1.14`: https://github.com/cilium/cilium/pull/36688
* `v1.15`: https://github.com/cilium/cilium/pull/36689

These PRs also manually bump the complexity-test image to verify that newer images work again.
