### ISSUE TITLE
CI: nightly test failed when upgrading from stable to latest

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3624]
Build link: https://jenkins.cilium.io/job/Cilium-Master-Nightly-Tests-All/172/testReport/

Relevant output: 
```
Stacktrace

/home/jenkins/workspace/Cilium-Master-Nightly-Tests-All/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:227
Cilium image didn't update correctly
Expected
    <string>: cilium/cilium:latest
to equal
    <string>: cilium/cilium:stable
/home/jenkins/workspace/Cilium-Master-Nightly-Tests-All/src/github.com/cilium/cilium/test/k8sT/Nightly.go:390
```

Logs: 
[test_results_Cilium-Master-Nightly-Tests-All_172.tar.zip](https://github.com/cilium/cilium/files/1896300/test_results_Cilium-Master-Nightly-Tests-All_172.tar.zip)

**Comment by eloycoto** [comment]
Fixed by https://github.com/cilium/cilium/pull/3590#event-1567118418

**Comment by ianvernon** [comment]
@eloycoto awesome, thanks! Closing.
