### ISSUE TITLE
CI: Cilium IPsec upgrade (ci-ipsec-upgrade): warn msg="Health check status"

### ISSUE THREAD

**Issue by rastislavs** [cilium/cilium#36251]
## CI failure

Failure due to emitting a warning message:
```
❌ Found 1 logs in kind-kind/kube-system/cilium-operator-5d688cd4b7-7lqnv (cilium-operator) matching list of errors that must be investigated:
time=2024-11-29T01:39:12Z level=warn msg="Health check status" module=operator.operator-controlplane.health-handler error="Waiting for initial connection to be established" (1 occurrences)
```

Job: https://github.com/cilium/cilium/actions/runs/12077531456/job/33680567524

[cilium-junits.zip](https://github.com/user-attachments/files/17956704/cilium-junits.zip)
[cilium-sysdumps.zip](https://drive.google.com/file/d/1ksm99kBFj1i6owpRjc1_jROFLCnPTIhq/view?usp=drive_link)

**Comment by harsimran-pabla** [comment]
Should be fixed by https://github.com/cilium/cilium/pull/36238
