### ISSUE TITLE
CI: add Runtime DROP_ALL test

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3625]
Steps:
1. Immediately start a container with cilium in default enforcement mode with a default deny policy (ingress, egress) enabled that selects the labels of the container
2. ping the container: no packets should get through *ever* to the endpoint.

**Comment by manalibhutiyani** [comment]
I can take a look at this.

**Comment by manalibhutiyani** [comment]
Working on writing the test, but this requires GH #3705 to support DROP_ALL bpf program regeneration correctly to test on docker
