### ISSUE TITLE
nil pointer evaluating interface {}.cert

### ISSUE THREAD

**Issue by sherwoodzern** [cilium/cilium#36287]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

helm upgrade cilium cilium/cilium --version 1.11.6 \
   --namespace kube-system \
   --reuse-values \
   --set hubble.relay.enabled=true \
   --set hubble.ui.enabled=true \
   --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http}"
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/sherwood/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/sherwood/.kube/config
Error: UPGRADE FAILED: template: cilium/templates/hubble/tls-helm/server-secret.yaml:2:10: executing "cilium/templates/hubble/tls-helm/server-secret.yaml" at <include "hubble-generate-certs.helm.setup-ca" .>: error calling include: template: cilium/templates/hubble/tls-helm/_helpers.tpl:15:18: executing "hubble-generate-certs.helm.setup-ca" at <.Values.hubble.tls.ca.cert>: nil pointer evaluating interface {}.cert

### How can we reproduce the issue?

helm upgrade cilium cilium/cilium --version 1.11.6 \
   --namespace kube-system \
   --reuse-values \
   --set hubble.relay.enabled=true \
   --set hubble.ui.enabled=true \
   --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http}"

### Cilium Version

1.16.4

### Kernel Version

 Darwin Kernel Version 22.6.0:

### Kubernetes Version

Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.2

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
@sherwoodzern did you intend to specify the version as `1.11.6` in your command lines? That version reached end of life around 18 months ago.

**Comment by sherwoodzern** [comment]
@joestringer That is probably the issue. I was following the instructions from the doc. What version should I be specifying?

**Comment by joestringer** [comment]
Here's the list of actively maintained releases: https://github.com/cilium/cilium?tab=readme-ov-file#stable-releases
