### ISSUE TITLE
make build-rpm fails

### ISSUE THREAD

**Issue by mskarbek** [cilium/cilium#363]
`make build-rpm` fails with:
```Step 6 : RUN rpmdev-setuptree && export VERSION_PATH="cilium_$(cat VERSION)" && export DESTDIR="~/rpmbuild/" && export GOPATH=/tmp/cilium-net-build && export GOROOT=/usr/local/go && export PATH="$GOROOT/bin:$PATH" && export PKG_BUILD=1 && export VERSION="$(cat VERSION)" && ./create-rpm.sh
 ---> Running in 11d60ff6ba28
/usr/lib/python2.7/site-packages/pyrpkg/cli.py:37: DeprecationWarning: --dist is deprecated and will be removed in future version. Use --release instead.
  'Use --release instead.', DeprecationWarning)
sources file doesn't exist. Source files download skipped.
error: Name field must be present in package: (main package)
error: Version field must be present in package: (main package)
error: Release field must be present in package: (main package)
error: Summary field must be present in package: (main package)
error: License field must be present in package: (main package)
error: query of specfile /tmp/cilium-net-build/src/github.com/cilium/cilium/cilium.spec failed, can't parse

Could not execute local: Could not get n-v-r-e from '\n'
The command '/bin/sh -c rpmdev-setuptree && export VERSION_PATH="cilium_$(cat VERSION)" && export DESTDIR="~/rpmbuild/" && export GOPATH=/tmp/cilium-net-build && export GOROOT=/usr/local/go && export PATH="$GOROOT/bin:$PATH" && export PKG_BUILD=1 && export VERSION="$(cat VERSION)" && ./create-rpm.sh' returned a non-zero code: 1
Makefile:6: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/marcin.skarbek/projects/cilium/contrib/packaging/rpm'
Makefile:83: recipe for target 'build-rpm' failed
make: *** [build-rpm] Error 2
```

It wouldn't hurt also to update Dockerfile to the newest Fedora image.

Is there anyone assigned to maintain rpm-based packages for cilium or this is provided as a best effort from the team working mainly on a different distributions?

**Comment by tgraf** [comment]
> Is there anyone assigned to maintain rpm-based packages for cilium or this is provided as a best effort from the team working mainly on a different distributions?

We currently don't have a dedicated maintainer for this so this is mostly best effort. We are currently developing on Ubuntu. Feel free to take on this task if you are interested.

**Comment by mskarbek** [comment]
Ok, so I'll try to provide support in that matter.

**Comment by aanm** [comment]
@mskarbek Like @tgraf said, we are doing it as best effort, I start working on this in #364, if you can contribute with your feedback that would be awesome, can you take look if it's ok?

We might need some help with `debian` packages, any experience with that?

**Comment by mskarbek** [comment]
@aanm I can help with Red Hat based distributions and rpm-based packaging, unfortunately I have no experience with maintaining deb packages.
I'll take a look at `build-rpm` and spec file.

**Comment by aalemayhu** [comment]
@aanm I created a [Request For Package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858303). That might attract other Debian contributors. My neighbour who is a Debian developer said 

>suspect a separate repo based on the upstream repo might be a good way to go.
>similar to how we did plinth in freedombox, where we import tarballs but connect
>the releases to the git history from upstream.

>the debian/control file lack build dependencies and uses a string
>standards-version.  but besides that, the build rules seem ok to me.  will need
>patches to d/changelog, so a separate repo with a copy in debian/ (instead of
>the symlink) might be a good idea anyway.

**Comment by tgraf** [comment]
> @aanm I created a Request For Package. That might attract other Debian contributors. My neighbour who is a Debian developer said

We are planning on shipping a first release next week.
