### ISSUE TITLE
Encounter cluster has nodes with different OS images issue when using 1.17.0-pre.3

### ISSUE THREAD

**Issue by truongnht** [cilium/cilium#36320]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

environment: 1.17.0-pre.3
cilium-cli: built locally with 1.17.0-pre.3 source

When trying out new 1.17.0-pre.3, I noticed that the old cli is not compatible with new cilium version, so a new cli is built and used. In our EKS cluster, we do have two different OSes: 
* AL2 which is used in fargate node hosting Karpenter
* Bottlerocket is configured on nodes provisioned by Karpenter 

we do have nodeSelector in cilium values file for cilium agents/ operators/ envoys workloads. And in earlier version, our approach works well. This behavior breaks in 1.17.0-pre.3 (not in .2) with below error
```
cilium upgrade cilium cilium/cilium --namespace kube-system --version "$cilium_version" --values cilium-values.yaml       --set cluster.id=1       --set "cluster.name=${cluster_name}"       --set "eni.iamRole=${cilium_role_arn}"       --set "serviceAccounts.operator.annotations.eks\.amazonaws\.com/role-arn=${cilium_role_arn}" --set "k8sServiceHost=${cluster_api_endpoint}"
🔮 Auto-detected Kubernetes kind: EKS
ℹ️  Using Cilium version 1.17.0-pre.3
ℹ️  Using cluster name "truong-test-cluster"
🔮 Auto-detected kube-proxy has been installed
❌ Could not detect AWS node image family, defaulted to fallback value: Custom

Error: Unable to upgrade Cilium: cluster has nodes with different OS images: 'AmazonLinux2' and 'Bottlerocket'
```

 I guess it might be related to [this feature](https://github.com/cilium/cilium/pull/36076/files#diff-0b6dc304261e14febe58bbc9f05a9358eb47cfb9e85673ab0c7aec413dfd6ed7).

### How can we reproduce the issue?

environment: 1.17.0-pre.3
cilium-cli: built locally with 1.17.0-pre.3 source

When trying out new 1.17.0-pre.3, I noticed that the old cli is not compatible with new cilium version, so a new cli is built and used. In our EKS cluster, we do have two different OSes: 
* AL2 which is used in fargate node hosting Karpenter
* Bottlerocket is configured on nodes provisioned by Karpenter 

we do have nodeSelector in cilium values file for cilium agents/ operators/ envoys workloads. And in earlier version, our approach works well. This behavior breaks in 1.17.0-pre.3 (not in .2) with below error
```
cilium upgrade cilium cilium/cilium --namespace kube-system --version "$cilium_version" --values cilium-values.yaml       --set cluster.id=1       --set "cluster.name=${cluster_name}"       --set "eni.iamRole=${cilium_role_arn}"       --set "serviceAccounts.operator.annotations.eks\.amazonaws\.com/role-arn=${cilium_role_arn}" --set "k8sServiceHost=${cluster_api_endpoint}"
🔮 Auto-detected Kubernetes kind: EKS
ℹ️  Using Cilium version 1.17.0-pre.3
ℹ️  Using cluster name "truong-test-cluster"
🔮 Auto-detected kube-proxy has been installed
❌ Could not detect AWS node image family, defaulted to fallback value: Custom

Error: Unable to upgrade Cilium: cluster has nodes with different OS images: 'AmazonLinux2' and 'Bottlerocket'
```

 I guess it might be related to [this feature](https://github.com/cilium/cilium/pull/36076/files#diff-0b6dc304261e14febe58bbc9f05a9358eb47cfb9e85673ab0c7aec413dfd6ed7).

### Cilium Version

1.17.0-pre.3

### Kernel Version

NA

### Kubernetes Version

1.31

### Relevant log output

```shell

```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by truongnht** [comment]
@viktor-kurchenko FYI

**Comment by nbusseneau** [comment]
Hello, can you share an example of your `nodeSelector`-based approach for handling values in a mixed OS cluster?

**Comment by truongnht** [comment]
sure, @nbusseneau an excerpt of our cilium values file
```yaml
nodeSelector:
  kubernetes.io/os: linux
  karpenter.sh/registered: "true"

envoy:
  rolloutPods: true
  nodeSelector:
    kubernetes.io/os: linux
    karpenter.sh/registered: "true"
```

**Comment by nbusseneau** [comment]
Ah sorry I misunderstood, I thought you were using `nodeSelector` to dispatch different values to different nodes in a mixed OS cluster, but this is "just" the regular `nodeSelector` field in the Cilium values for pod assignment. In other words, the issue you have is only because of the new block on mixed OS clusters, it is unrelated to `nodeSelector` setup => I got confused because it was mentioned in OP but this is only context and not directly related to the issue.

**Comment by nbusseneau** [comment]
Technically it works in your case of mixed OS because both OS have a similar network interface setup (or you don't use masquerade), so even though Cilium is indeed currently unable to handle masquerading over a mixed cluster with different naming schemes for network interfaces, in your case the block is actively preventing a previously working situation.

I think we should switch from error to warning in the CLI, allowing such a use case.

**Comment by viktor-kurchenko** [comment]
@truongnht thanks for reporting the issue!
I've raised [the PR](https://github.com/cilium/cilium/pull/36336) to replace error with warning as a quick fix.

**Comment by truongnht** [comment]
@viktor-kurchenko thanks raising the PR and letting me know. I believe it also needs to be fixed [here](https://github.com/cilium/cilium/pull/36076/files#diff-0b6dc304261e14febe58bbc9f05a9358eb47cfb9e85673ab0c7aec413dfd6ed7R106-R111)

**Comment by viktor-kurchenko** [comment]
Well, the new PR will just [log the error without returning it](https://github.com/cilium/cilium/pull/36336/files#diff-0b6dc304261e14febe58bbc9f05a9358eb47cfb9e85673ab0c7aec413dfd6ed7R46-R47).
Does it make sense?

**Comment by truongnht** [comment]
Yes but not complete, see my errors, there are two different (however related) errors

**Comment by marcofranssen** [comment]
Encountering the same problem on cilium `1.16.4`. On cilium `1.16.3` it still works.

Our cluster uses karpenter nodes for cilium, but it also runs one Fargate instance to run karpenter itself. That Fargate Karpenter Pod isn't managed by cilium. Maybe that is the problem?

**Comment by gordonm** [comment]
Assuming it's safe to ignore Fargate nodes completely, how about something like:

```
labelSelector := "eks.amazonaws.com/compute-type notin (fargate)"
nodes, err := k.client.ListNodes(context.Background(), metav1.ListOptions{
	LabelSelector: labelSelector,
})
```

**Comment by marcofranssen** [comment]
Found the last working cli release

`0.16.20` still works, after it breaks the upgrade for our cluster. So problem is in since the last 2 cli releases.

**Comment by viktor-kurchenko** [comment]
Hey @marcofranssen and @gordonm 
This [PR](https://github.com/cilium/cilium/pull/36336) should fix the error.
But still waiting for review...

**Comment by marcofranssen** [comment]
I have also added another solution for the problem, in case it is decided to keep the AMI OS check. https://github.com/cilium/cilium/pull/36687

I'm fine either way, as long it gets fixed. Lets see what the maintainers think is the best way forward.
