### ISSUE TITLE
CI: forced regenerations of endpoints due to key-value store event causes CI failures

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3635]
We are reliant in the CI upon endpoints transitioning into "ready" state and staying in that state. However, since Cilium is event-driven, we might receive some sort of key-value store event that triggers endpoint regenerations. This causes failures like the following:

 * https://github.com/cilium/cilium/issues/3622
* https://github.com/cilium/cilium/issues/3467

For a more detailed analysis of how this occurs, see : https://github.com/cilium/cilium/issues/3467#issuecomment-378035614

We need to figure out how to make the CI resilient to such issues. Specifically:

> It is entirely possible that we can have endpoints go from being into ready state, to having a key-value store event consumed for an identity, which then forces a policy recalculation for all endpoints, thus putting them into waiting-to-regenerate state. Thus, this isn't a cilium bug; we need a better way in the test framework of having some sort of guarantee that the endpoints are in ready state and that they will not change such state unless the user performs some sort of operation which triggers change of state (policy imported, deleted, endpoint forcibly regenerated, labels changed on endpoints, etc.).

I don't know how feasible this is. Is this feasible with the current state of Cilium?

**Comment by tgraf** [comment]
Long solved
