### ISSUE TITLE
Worker node DNS resolution fails when Cilium is installed

### ISSUE THREAD

**Issue by dumlutimuralp** [cilium/cilium#36406]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

A bug happened!
I am running an EKS cluster v.1.31 with a single node. Cilium installation seems to be breaking the DNS resolution at the Node level. Basically the worker node cannot resolve any DNS names right after the Cilium installation. None of the worker nodes can communicate with the DNS server set in the resolv.conf file. When you create a pod the worker nodes are unable to pull the container image. Below error.

`  Warning  Failed     1s    kubelet            Failed to pull image "dumlutimuralp/networktest": failed to pull and unpack image "docker.io/dumlutimuralp/networktest:latest": failed to resolve reference "docker.io/dumlutimuralp/networktest:latest": failed to do request: Head "https://registry-1.docker.io/v2/dumlutimuralp/networktest/manifests/latest": dial tcp: lookup registry-1.docker.io on 10.0.0.2:53: read udp 10.0.3.182:42924->10.0.0.2:53: i/o timeout`

Details are in the reproduce section. 

### How can we reproduce the issue?

1. Deploy an EKS cluster with v1.131 and a node group with a single node. Node has SSM agent and it is running  in a private subnet. NAT Gateway is used in tje public subnet.
2. Check the DNS resolution on the worker node using `dig www.example.com` verify it works.
3. Follow [Cilium Helm Installation Guide for EKS](https://docs.cilium.io/en/stable/installation/k8s-install-helm/) and deploy Cilium using the following command `helm install cilium cilium/cilium --version 1.16.4  --namespace kube-system  --set egressMasqueradeInterfaces=eth0`
4. Check DNS resolution on the worker node using `dig www.example.com` observe that DNS resolution fails. 
5. Change the DNS server in resolv.conf from Amazon Provided DNS server (.2) to another DNS server and verify that `dig www.example.com` resolves successfully.
6. Remove Cilium using `helm uninstall cilium -n kube-system`
7. Change DNS server in resolv.conf back to Amazon PRovided DNS server again and verify `dig www.example.com` starts working again. 

### Cilium Version

1.16.4

### Kernel Version

Amazon AL2 Linux 
5.10.228-219.884.amzn2.x86_64 #1 SMP Wed Oct 23 17:17:00 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.31.2

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dumlutimuralp** [comment]
I got tcpdump output from the worker node and apparently when I install Cilium the worker node starts using the `cilium_vxlan` interface when sending the DNS requests. When I do `ip addess` the output does not show any IP address for the `cilium_vxlan` interface. 

But for some reason in the tcpdump output itself I can see an overlay IP as the source IP in those DNS requests. Obviously those packets will be dropped at the ENI level due to src/dst IP check and also the VPC networking layer wont be aware of the overlay IP.

Why is this the behaviour ? I tested this scenario with a Kubernetes 1.30 and 1.29 versions as well ?

**Comment by dumlutimuralp** [comment]
I understand what is going on. Cilium uses the cilium_vxlan interface when sending DNS requests to the DNS server which seems to be in the same subnet as cilium_vxlan interface. But I do not see any IP address bound to the cilium_vxlan interface. I only see it in the route table. It seems I created an overlapping IP subnets issue here. 

```
00:08:35.577136 Out 2e:0b:e5:89:87:47 ethertype IPv4 (0x0800), length 144: 10.0.1.65.57547 > 10.0.0.2.domain: 65512+ [1au] AAAA? 602401143452.dkr.ecr.eu-west-1.amazonaws.com.eu-west-1.compute.internal. (100)
00:08:35.577063   P e6:5b:f7:1d:b8:f7 ethertype IPv4 (0x0800), length 144: 10.0.1.65.33056 > 10.0.0.2.domain: 62688+ [1au] A? 602401143452.dkr.ecr.eu-west-1.amazonaws.com.eu-west-1.compute.internal. (100)
00:08:35.577140 Out 2e:0b:e5:89:87:47 ethertype IPv4 (0x0800), length 144: 10.0.1.65.33056 > 10.0.0.2.domain: 62688+ [1au] A? 602401143452.dkr.ecr.eu-west-1.amazonaws.com.eu-west-1.compute.internal. (100)
00:08:35.577138  In 2e:0b:e5:89:87:47 ethertype IPv4 (0x0800), length 144: 10.0.1.65.57547 > 10.0.0.2.domain: 65512+ [1au] AAAA? 602401143452.dkr.ecr.eu-west-1.amazonaws.com.eu-west-1.compute.internal. (100)
00:08:35.577141  In 2e:0b:e5:89:87:47 ethertype IPv4 (0x0800), length 144: 10.0.1.65.33056 > 10.0.0.2.domain: 62688+ [1au] A? 602401143452.dkr.ecr.eu-west-1.amazonaws.com.eu-west-1.compute.internal. (100)
00:08:37.106950   P e6:5b:f7:1d:b8:f7 ethertype IPv4 (0x0800), length 100: 10.0.1.65.49584 > 10.0.0.2.domain: 63472+ [1au] AAAA? ssm.eu-west-1.amazonaws.com. (56)
00:08:37.107007 Out 2e:0b:e5:89:87:47 ethertype IPv4 (0x0800), length 100: 10.0.1.65.49584 > 10.0.0.2.domain: 63472+ [1au] AAAA? ssm.eu-west-1.amazonaws.com. (56)
00:08:37.107021   P e6:5b:f7:1d:b8:f7 ethertype IPv4 (0x0800), length 100: 10.0.1.65.53491 > 10.0.0.2.domain: 61616+ [1au] A? ssm.eu-west-1.amazonaws.com. (56)
00:08:37.107040 Out 2e:0b:e5:89:87:47 ethertype IPv4 (0x0800), length 100: 10.0.1.65.53491 > 10.0.0.2.domain: 61616+ [1au] A? ssm.eu-west-1.amazonaws.com. (56)
00:08:37.107041  In 2e:0b:e5:89:87:47 ethertype IPv4 (0x0800), length 100: 10.0.1.65.53491 > 10.0.0.2.domain: 61616+ [1au] A? ssm.eu-west-1.amazonaws.com. (56)
00:08:37.107009  In 2e:0b:e5:89:87:47 ethertype IPv4 (0x0800), length 100: 10.0.1.65.49584 > 10.0.0.2.domain: 63472+ [1au] AAAA? ssm.eu-west-1.amazonaws.com. (56)
^C
957 packets captured
957 packets received by filter
0 packets dropped by kernel
```

```
sh-4.2$ ip route
default via 10.0.5.1 dev eth0
10.0.0.0/24 via 10.0.0.156 dev cilium_host proto kernel src 10.0.0.156
10.0.0.156 dev cilium_host proto kernel scope link
10.0.1.0/24 via 10.0.0.156 dev cilium_host proto kernel src 10.0.0.156 mtu 8951
10.0.5.0/24 dev eth0 proto kernel scope link src 10.0.5.223
169.254.169.254 dev eth0
169.254.170.23 dev pod-id-link0
```

```
sh-4.2$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 02:22:af:83:b2:95 brd ff:ff:ff:ff:ff:ff
3: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 8a:aa:a3:a9:d8:8d brd ff:ff:ff:ff:ff:ff
4: pod-id-link0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether e2:07:fc:06:41:c5 brd ff:ff:ff:ff:ff:ff
5: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 4a:18:7e:49:2b:b3 brd ff:ff:ff:ff:ff:ff
6: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 66:4c:c0:d9:ea:01 brd ff:ff:ff:ff:ff:ff
7: cilium_vxlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 2e:0b:e5:89:87:47 brd ff:ff:ff:ff:ff:ff
9: lxc_health@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether ce:b2:2d:97:e7:7f brd ff:ff:ff:ff:ff:ff link-netnsid 0
11: lxce67f13460fc9@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 6e:6b:b5:f2:8b:c9 brd ff:ff:ff:ff:ff:ff link-netns cni-8bb48436-bea3-3a31-10e3-b303129130d5
```

**Comment by dumlutimuralp** [comment]
Ok. I managed to fix the behaviour by 
1. Deleting the Cilium Node (CN) CRDs. Apparently when you uninstall Cilium this Cilium Node CRDs still stays with mapping of CIDD to the specific node. 
2. Using a completely different CIDR for Pods (172.16.0.0/16) . Nodes are in 10.0.0.0/16. 

I dont understand why overlapping ip cidr case and needing to delete CN crd is not mentioned in the current docs.

**Comment by joestringer** [comment]
It looks like step (3) in the issue description is installing with the generic (tunneling/vxlan) instructions rather than integrating with EKS IPAM, which is likely part of the underlying issue here. In that case yes you will need to be careful about IPAM ranges to avoid overwriting the routing decisions for the underlying network. I feel like we can probably make some improvements to the docs to make the IPAM selection more obvious during installation.

> I dont understand why overlapping ip cidr case and needing to delete CN crd is not mentioned in the current docs.

Currently, changing IPAM configurations post-install is discouraged per the [IP Address Management](https://docs.cilium.io/en/stable/network/concepts/ipam/#address-management) documentation. It may be possible to lift this restriction in future, but so far it looks like no-one is working on it: https://github.com/cilium/cilium/issues/27164 . It's great that you have found the workaround by deleting CiliumNode resources, but we are unlikely to document those steps in the documentation just because these are intended to be managed entirely by Cilium itself and not by the user. I'd expect that if we solve this problem of modifying IPAM after install, that workflow should also take care of this step automatically.

**Comment by joestringer** [comment]
I understand that you were able to resolve this problem, so this issue can serve as documentation for how to mitigate it. I've filed https://github.com/cilium/cilium/issues/36518 to review the installation documentation. Other than that I don't think there is anything else to follow up on this issue, so I'll close it out.
