### ISSUE TITLE
Proxy: Excessive `EADDRNOTAVAIL` errors when connect()ing to upstreams

### ISSUE THREAD

**Issue by aetimmes** [cilium/cilium#36427]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

`tl;DR`: cilium-envoy is intermittently returning 503s due to ephemeral port collision.

In our production environment:

- EKS 1.29
- Bottlerocket 1.27
  - Linux 6.1.115
- Kong Gateway Enterprise v3.7.1.2
- Cilium v1.16.2

requests going through our Kong dataplane pods are returning 503 responses with the header `x-envoy-response-code-details: upstream_reset_before_response_started{remote_connection_failure,immediate_connect_error:_Cannot_assign_requested_address}`.

Using [retsnoop](https://github.com/anakryiko/retsnoop), we've narrowed the connect failures down to [__inet_check_established](https://github.com/torvalds/linux/blob/b8f52214c61a5b99a54168145378e91b40d10c90/net/ipv4/inet_hashtables.c#L538) propagating an `EADDRNOTAVAIL` error (ostensibly because of ephemeral port collision):

```
# /retsnoop -T -e  '__sys_connect' -x EADDRNOTAVAIL -a '*connect*' -a '*sock*' -a '*inet*'

18:15:49.710872 -> 18:15:49.710987 TID/PID 6424/2869 (wrk:worker_11/cilium-envoy):

FUNCTION CALLS                                               RESULT             DURATION
----------------------------------------------------------   ----------------  ---------
→ __sys_connect
    → __sys_connect_file
        → security_socket_connect
            → selinux_socket_connect
                → selinux_socket_connect_helper.isra.0
                    ↔ sock_has_perm                          [0]                 2.654us
                ← selinux_socket_connect_helper.isra.0       [0]                11.877us
                → selinux_netlbl_socket_connect
                    ↔ lock_sock_nested                       [void]              0.466us
                    ↔ selinux_netlbl_socket_connect_locked   [0]                 4.497us
                    ↔ release_sock                           [void]              4.318us
                ← selinux_netlbl_socket_connect              [0]                23.669us
            ← selinux_socket_connect                         [0]                41.968us
            ↔ bpf_lsm_socket_connect                         [0]                 2.304us
        ← security_socket_connect                            [0]                55.632us
        → inet_stream_connect
            ↔ lock_sock_nested                               [void]              0.436us
            → __inet_stream_connect
                → tcp_v4_connect
                    ↔ inet_sk_state_store                    [void]              4.633us
                    → inet_hash_connect
                        → __inet_hash_connect
                            → __inet_check_established
                                ↔ inet_ehashfn               [0x569ed867]        0.517us
                            ← __inet_check_established       [-EADDRNOTAVAIL]    2.103us
                        ← __inet_hash_connect                [-EADDRNOTAVAIL]    9.944us
                    ← inet_hash_connect                      [-EADDRNOTAVAIL]   12.648us
                    ↔ inet_unhash                            [void]              0.767us
                    ↔ inet_sk_state_store                    [void]              0.321us
                    ↔ inet_bhash2_reset_saddr                [void]              2.318us
                ← tcp_v4_connect                             [-EADDRNOTAVAIL]   34.722us
            ← __inet_stream_connect                          [-EADDRNOTAVAIL]   37.360us
            ↔ release_sock                                   [void]              0.422us
        ← inet_stream_connect                                [-EADDRNOTAVAIL]   41.439us
    ← __sys_connect_file                                     [-EADDRNOTAVAIL]  102.672us
← __sys_connect                                              [-EADDRNOTAVAIL]  111.272us
```

We're fairly sure that the involvement of Kong is correlation and not causation; we think it's Envoy load-related and Kong is just the thing generating said load.

We've got retries enabled on the relevant CECs, but we experience bursts of collisions that exceed the retry limits and we're hesitant to dial up the retry count further to avoid causing a thundering herd scenario.

### How can we reproduce the issue?

1. Install Cilium with our config (attached)
2. Create a service with a CEC
3. Run a large number of requests through cilium-envoy via L7 CECs

### Cilium Version

v1.16.2

### Kernel Version

6.1.115

### Kubernetes Version

1.29

### Sysdump

redacting; contact @aetimmes on the Cilium Slack and I can provide

### Relevant log output

```shell

```

### Anything else?

[api-external.svc.txt](https://github.com/user-attachments/files/18040380/api-external.svc.txt)
[api.cec.txt](https://github.com/user-attachments/files/18040379/api.cec.txt)
[api.svc.txt](https://github.com/user-attachments/files/18040378/api.svc.txt)

I've got a ~100MB trace log file as well that I likely cannot upload here; I can provide that via Slack if needed.

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
Do you have this problem when using "ordinary" L7 filters, or only with the CiliumEnvoyConfig?

**Comment by aetimmes** [comment]
Hmm - define "ordinary L7 filters"? If you can provide some alternate config to try, I can see if I can reproduce in test.

In doing some more investigation, we think this issue might be related to https://github.com/cilium/cilium/issues/30406 in that making multiple concurrent requests to a ClusterIP service with a small number of backend pods seems to be the primary trigger - but we're not _exhausting_ ports (since we never go above ~2k total sockets on the host), so there's likely a 5-tuple collision happening.

We've been flipping some toggles back and forth on the CECs, notably `connectionPoolPerDownstreamConnection` which alleviates the issue _most_ of the time, but we still get random 5-8 minute stretches of intermittent `Cannot assign requested address` errors (we've nicknamed this particular error CARA) on the nodes running Kong when we have that enabled.

We noticed when running `tcpconnect` on a system where `EADDRNOTAVAIL` was being thrown, cilium-envoy was reusing the source address and port from the downstream connection:

```
189.031  185530  reactor-http 4  10.135.150.169   44052  172.20.210.249   80
189.034  3715    wrk:worker_3 4  10.135.150.169   44052  10.135.127.217   8888
189.038  185530  reactor-http 4  10.135.150.169   49828  172.20.54.65     80
189.040  3715    wrk:worker_2 4  10.135.150.169   49828  10.135.127.219   8888
189.042  185530  reactor-http 4  10.135.150.169   51312  172.20.197.194   80
189.044  3715    wrk:worker_3 4  10.135.150.169   51312  10.135.37.153    8888
189.156  185530  reactor-http 4  10.135.150.169   51324  172.20.197.194   80
189.156  185530  reactor-http 4  10.135.150.169   51326  172.20.197.194   80
189.156  185530  reactor-http 4  10.135.150.169   51328  172.20.197.194   80
189.157  185530  reactor-http 4  10.135.150.169   51334  172.20.197.194   80
189.157  185530  reactor-http 4  10.135.150.169   51336  172.20.197.194   80
189.157  185530  reactor-http 4  10.135.150.169   51350  172.20.197.194   80
189.157  185530  reactor-http 4  10.135.150.169   51356  172.20.197.194   80
189.157  185530  reactor-http 4  10.135.150.169   51370  172.20.197.194   80
189.157  185530  reactor-http 4  10.135.150.169   51378  172.20.197.194   80
189.158  185530  reactor-http 4  10.135.150.169   51382  172.20.197.194   80
189.158  185530  reactor-http 4  10.135.150.169   51396  172.20.197.194   80
189.159  185530  reactor-http 4  10.135.150.169   51404  172.20.197.194   80
189.159  185530  reactor-http 4  10.135.150.169   51410  172.20.197.194   80
189.160  185530  reactor-http 4  10.135.150.169   51414  172.20.197.194   80
189.160  185530  reactor-http 4  10.135.150.169   51426  172.20.197.194   80
189.160  185530  reactor-http 4  10.135.150.169   51436  172.20.197.194   80
189.164  3715    wrk:worker_3 4  10.135.150.169   51324  10.135.133.51    8888
189.165  3715    wrk:worker_2 4  10.135.150.169   51334  10.135.133.51    8888
189.165  3715    wrk:worker_3 4  10.135.150.169   51326  10.135.37.153    8888
189.166  3715    wrk:worker_3 4  10.135.150.169   51328  10.135.133.51    8888
189.166  3715    wrk:worker_0 4  10.135.150.169   51336  10.135.37.153    8888
189.168  3715    wrk:worker_3 4  10.135.150.169   51350  10.135.37.153    8888
189.168  3715    wrk:worker_2 4  10.135.150.169   51370  10.135.37.153    8888
189.169  3715    wrk:worker_0 4  10.135.150.169   51378  10.135.133.51    8888
189.170  3715    wrk:worker_3 4  10.135.150.169   51356  10.135.133.51    8888
189.172  3715    wrk:worker_0 4  10.135.150.169   51410  10.135.37.153    8888
189.172  3715    wrk:worker_3 4  10.135.150.169   51382  10.135.37.153    8888
189.173  3715    wrk:worker_1 4  10.135.150.169   51414  10.135.133.51    8888
189.173  3715    wrk:worker_3 4  10.135.150.169   51396  10.135.133.51    8888
189.174  3715    wrk:worker_3 4  10.135.150.169   51404  10.135.37.153    8888
189.174  3715    wrk:worker_0 4  10.135.150.169   51426  10.135.133.51    8888
189.175  3715    wrk:worker_1 4  10.135.150.169   51436  10.135.37.153    8888
189.210  3715    wrk:worker_3 4  10.135.150.169   51312  10.135.133.51    8888```

so we thought that the 5-tuple collision was potentially from multiple different envoy threads/connpools getting multiple requests over the same http/1.1 downstream connection and colliding that way? But even when setting `--concurrency=1`, if we don't set `connectionPoolPerDownstreamConnection`, we still see CARAs.

**Comment by aetimmes** [comment]
Looks like this might be a subset of https://github.com/cilium/cilium/issues/25613.

**Comment by aetimmes** [comment]
With our original setup, if I run `fortio load -allow-initial-errors -abort-on 599 -qps 0 -c 20 -n 10000 http://destination-svc`; I get ~15% 503 errors with EADDRNOTAVAIL return values from `connect`.

So if I enable a CiliumNetworkPolicy as such:

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: http
  namespace: destination-service-ns
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: source-service
            io.kubernetes.pod.namespace: source-service-ns
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "8888"
              protocol: TCP
            - port: "80"
              protocol: TCP
          rules:
            http: [{}]
```

and remove the CiliumNetworkPolicy, the fortio command runs to completion.

**Comment by aetimmes** [comment]
I need to double-check after re-baselining the configuration in my test cluster, but it appears that the major difference is that when requests go through the normal envoy listener, none of the sockets connecting to upstreams bind, so the collision scenario no longer exists.

**Comment by aetimmes** [comment]
Resolved by setting `cilium.io/use-original-source-address: false` on our CECs to prevent cilium-envoy from binding to to original source/port of the upstream request. Frustrating that this flag/behavior was undocumented, but happy to have a fix.
