### ISSUE TITLE
CI: output of some `journalctl` commands is saved to `test-output.log`

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3642]
This clogs the log of the test with a bunch of duplicate logs, and makes it hard to navigate the file. Do not log the results of commands which get logs from Cilium to `test-output.log`.

**Comment by eloycoto** [comment]
sadly, I found that super useful in my debugging, the Journalctl for the cilium logs meanwhile the test are running. So you have all the cilium logs for the time of the test. 

https://github.com/cilium/cilium/blob/master/test/helpers/cilium.go#L555

Big loss for me, I used this feature every single day a dozen of times. :-(

**Comment by ianvernon** [comment]
Why can't we just dump that output to a separate file? Having the logs inline in the file is the main gripe I have, not that the logs themselves are present. If they are dumped into a separate file, then you still have the Cilium logs from the duration of the test. 

I think that `test-output.log` should only contain data that is not dumped into other files, especially logs, because otherwise the file is enormous and hard to navigate.

**Comment by eloycoto** [comment]
I prefer to have in the same file, IMHO I think that ATM we're creating too many files and debugging a issue right now takes more time.

For me, having the logs of the test in the test-output.log is a feature. Having multiple files make things difficult to search, need to open dozen of tabs in the editor. For how I work I prefer to have all in the same file.

**Comment by ianvernon** [comment]
OK, given that you are the CI owner I will defer to you on this. Closing.
