### ISSUE TITLE
Editing or deleting service `spec.loadBalancerSourceRanges` causes all traffic to be blocked

### ISSUE THREAD

**Issue by architkulkarni** [cilium/cilium#36473]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

When working with a service and using a loadbalancer, if the field `spec.loadBalancerSourceRanges` is present at first and is subsequently edited or deleted, the service stops accepting all traffic.  A workaround is to delete the `spec.loadBalancerSourceRanges` field entirely, `kubectl apply` to update the service, then add the field back with the desired new values, and `kubectl apply` again, at which point the service starts accepting traffic again.

When the issue happens, packets get dropped with `Denied by LB src range check`.  Upon editing or deleting the field, the following error appears in the Cilium agent pod logs: `{"error":"unable to delete element 0.0.0.0/0 (23) from map cilium_lb4_source_range: delete: key does not exist","k8sNamespace":"default","k8sSvcName":"my-ext-load-balancer","level":"error","msg":"Error while inserting service in LB map","subsys":"k8s-watcher"}` Finally, the output of `bpftool map dump name cilium_lb4_sour` is empty.

This points to two potential issues:
- As noted in https://github.com/cilium/cilium/issues/22658#issuecomment-1368147411, updating the source ranges is done by deleting old values followed by adding new values, but if an error is hit during deletion, it will exit before adding the new values: https://github.com/cilium/cilium/blob/12be4924bce309acdc3203f58f8e17075799f734/pkg/maps/lbmap/lbmap.go#L420-L434  I don't know why the delete is failing ("key does not exist" suggests it's trying to delete a key that was already deleted, but I don't know why it's trying to delete it again).  But this explains why the resulting map is empty, because it didn't get a chance to add the new values before exiting.
- I notice that in the case where we delete the field `spec.loadBalancerSourceRanges` entirely, the flag `check source-range` is still present, which might be a bug. Because it behaves as if there is an empty list of allowed source ranges (therefore blocking everything), maybe it's a bug related to distinguishing between `nil` and an empty slice.

### How can we reproduce the issue?

I don't have an end-to-end local reproduction of the packets being blocked, because I haven't figured out how to get a load balancer working external IPs with `kind`, but I can share steps to reproduce the bug of `cilium_lb4_source_range` being empty and of the flag `check source-range` remaining true.

Not all of the steps below might be relevant, these are just the steps I used.

From the root of the Cilium directory:

```
REPO_ROOT=$PWD
KUBEPROXY_MODE="none" \
WORKERS=1 \
CONTROLPLANES=1 \
CLUSTER_NAME=kind \
make kind && \
make kind-image && \
kind export kubeconfig --name kind

helm upgrade -i cilium ./install/kubernetes/cilium --wait --namespace kube-system --set k8sServiceHost="kind-control-plane" --set k8sServicePort="6443" --set debug.enabled=true --set debug.verbose=datapath --set pprof.enabled=true --set enableIPv4Masquerade=false --set enableIPv6Masquerade=false --set hostFirewall.enabled=false --set socketLB.hostNamespaceOnly=true --set kubeProxyReplacement=true --set nodeinit.enabled=true --set ipam.mode=kubernetes --set ipv4.enabled=true --set ipv4NativeRoutingCIDR=10.244.0.0/16 --set ipv6.enabled=true --set ipv6NativeRoutingCIDR=fd00::/104 --set image.override="localhost:5000/cilium/cilium-dev:local" --set image.pullPolicy=Never --set operator.image.override="localhost:5000/cilium/operator-generic:local" --set operator.image.pullPolicy=Never --set operator.image.suffix="" --set securityContext.privileged=true --set gatewayAPI.enabled=false --set socketLB.enabled=false --set bpf.hostLegacyRouting=true --set endpointRoutes.enabled=true --set localRedirectPolicy=true
```

Find a CIDR range within the output of 

`ip route | grep "br-"`

Add it below:

```
kubectl apply -f - <<EOF
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default"
spec:
  blocks:
  - cidr: 172.19.250.0/24
EOF
```

Now use this `service.yaml` file:

```
apiVersion: v1
kind: Service
metadata:
  name: my-ext-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalTrafficPolicy: Local
  # loadBalancerSourceRanges:
  #   - 0.0.0.0/0
  #   - ::/0
```

When you add the `loadBalancerSourceRanges` field and run `kubectl apply -f service.yaml`, you can run `bpftool map dump name cilium_lb_source_range_v4` from the cilium agent pod, and see that it is populated correctly.  

Now remove the field entirely or edit the `0.0.0.0/0` to some other IP range, and run `kubectl apply -f service.yaml` again, and `bpftool map dump name cilium_lb4_sour` will be empty.  Also, if you removed the field entirely, `cilium bpf lb list` will still show the service with the `check source-range` tag: `34.57.152.242:80/i (0)    0.0.0.0:0 (23) (0) [LoadBalancer, Local, two-scopes, check source-range]`.

 

### Cilium Version

1.14.3, but the relevant source code seems unchanged on `main`

### Kernel Version

`Linux gke-lb-source-debug-default-pool-a0cffe9c-wphg 6.1.100+ #1 SMP PREEMPT_DYNAMIC Sat Aug 24 16:19:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: v1.30.6-dispatcher
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5-gke.1014003
```

### Relevant log output

```shell

```

### Anything else?

This issue may be related: https://github.com/cilium/cilium/issues/30843

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
this fixes it: https://github.com/cilium/cilium/pull/36517
