### ISSUE TITLE
CI: run make render-docs as part of CI

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#3653]
Apparently we are not running any tests in our documentation a part of CI, does this means we are not checking for dead links as well?

This will allow us to catch misspelled words in the beginning once we merge https://github.com/cilium/cilium/pull/3649

- [ ] run `render-docs` a part of pre-checks
- [ ] check for 404 links in the documentation

**Comment by nebril** [comment]
This is true, neither linkcheck, nor render-docs is run in our CI suite.

linkcheck implementation is in tests/98-documentation-link-check.sh

Both of these can be added as stages to ginkgo.Jenkinsfile.

**Comment by joestringer** [comment]
We run `make -C Documentation dummy/` in the regular make, but currently we ignore the exit code.

It makes sense to me to run a separate documentation target in CI, but `make render-docs` doesn't make sense to me. This is for running an HTTP server to serve the pages locally.

**Comment by aanm** [comment]
>but make `render-docs` doesn't make sense to me. 

@joestringer it's where the misspelled words are checked.

**Comment by joestringer** [comment]
Whatever gets us the testing we need:) I always saw the point of `render-docs` as a way to host the documentation server in a container locally, which seems like overkill if we just want to achieve a bit of linting.
