### ISSUE TITLE
CI: nightly tests do not gather logs for K8s stages

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3656]
Nightly tests suffered failures in the K8s-1.7 stage, but no logs for K8s-1.7 were gathered; only Nightly test results were gathered. 

Build link: https://jenkins.cilium.io/job/Cilium-Master-Nightly-Tests-All/173/

Fix the logic in the nightly tests to ensure that all logs are gathered for all stages.

**Comment by nathanjsweet** [comment]
[Latest failure](https://jenkins.cilium.io/job/cilium-master-Nightly/330/#showFailuresLink) shows this isn't true. Closing...
