### ISSUE TITLE
Quickstart make targets do not build `bugtool`

### ISSUE THREAD

**Issue by pmatulis** [cilium/cilium#36562]
The first make target listed in the [Development Setup Quick Start](https://docs.cilium.io/en/stable/contributing/development/dev_setup/#quick-start) documentation page is `make kind`.

The end of the output to the above command is:

```
Kind is up! Time to install cilium:
  make kind-image
  make kind-install-cilium

On Linux, the below can be used for faster feedback:
  make kind-image-fast
  make kind-install-cilium-fast
```

Since I am on Linux (Ubuntu 22.04 LTS), I executed `make kind-image-fast`. This however failed with:

```
lstat /home/ubuntu/git/cilium/bugtool/cilium-bugtool: no such file or directory
make: *** [Makefile.kind:239: kind-image-fast-agent] Error 1
```

Evidently `bugtool` is not built. I invoked `make -C bugtool`, which worked.

I went on to repeat `make kind-image-fast` and then `make kind-install-cilium-fast`, both of which succeeded.

It's unknown to me whether the same issue would result from the non-Linux-specific commands given above.

**Comment by joestringer** [comment]
I see this has been actively iterated upon recently in https://github.com/cilium/cilium/pull/36516 and https://github.com/cilium/cilium/pull/36545 , it looks like the makefile didn't previously copy the bugtool in. Now it's copying it in, but the target doesn't depend on the bugtool subdirectory so the make may fail from scratch. I've submitted https://github.com/cilium/cilium/pull/36587 to fix the target so future developers shouldn't hit this.
