### ISSUE TITLE
RFC: k8s CEP improperly nests models.Endpoint under .Status

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#3659]
The current 1.0 RCs and master have the finalized 1.0 API. Unfortunately, the k8s CEP CRD continued to export the `models.Endpoint` struct instead of `models.EndpointStatus`. The JSON currently looks like:
```json
{
  ...k8s metadata...
  "status": {
                     "id": 0,
                     "status": {...models.EndpointStatus...},
                     "spec": {...models.EndpointSpec... }
}
```
This is unfortunate since all accesses to the CEPs will need to `.Status.Status` before accessing the useful data content. Worse, the  `.Spec` isn't intended to be there since `.Status` is supposed to be read-only to users. The original intent was to mirror models.Endpoint as the CRD (so all the fields shown above under .Status are one level higher). This would allow us, in the future, to support editing the endpoint configuration by editing the top-level spec field (shown below but it wouldn't be present in 1.0)

```json
{
  ...k8s metadata...
  "id": 0,
  "status": {...models.EndpointStatus...},
  "spec": {...models.EndpointSpec... }
}
```

Unfortunately, there are already some users of the CEPs and this change would be disruptive. I'm not sure if it's possible to fix this after the final 1.0 release either. One option is that when we merge https://github.com/cilium/cilium/pull/3222 part of that transition would be to do this. Unfortunately, that will not fix usages like `kubectl get cep -o json`

The fixup is relatively simple code-wise, and our current tests only use the agent API directly (but there is future work to begin using the CEPs).

Thoughts?

**Comment by raybejjani** [comment]
cc @michi-covalent @cilium/agent

**Comment by aanm** [comment]
@raybejjani you mean `models.EndpointConfigurationSpec` under `spec` and `models.EndpointStatus` under `status`?

**Comment by raybejjani** [comment]
Yes. Note that models.Endpoint also has a top-level ID field, which is the endpoint ID on that node. The CRD would then have 3 top-level keys apart from the k8s metadata stuff: `id`, `spec`, `status`. `spec` wouldn't be present in the near term, and would only make sense if we wanted to allow configuration changes via the CEPs.

**Comment by raybejjani** [comment]
A matching PR https://github.com/cilium/cilium/pull/3737 I'd like some feedback around whether we should do this before 1.0. If we don't we are stuck with the current scheme until API 2.0

**Comment by raybejjani** [comment]
This was shipped, and it's fine :)
