### ISSUE TITLE
cilium gatewayClass does not gets accepted.

### ISSUE THREAD

**Issue by zozo6015** [cilium/cilium#36702]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

in a kubernetes cluster created with kubeadm used cilium as cni, enable gateway-api via cilium-cli by running the following command:

```
cilium install --version "v1.16.4" --set authentication.mutual.spire.enabled=true --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" --set hubble.enabled=true --set hubble.metrics.enableOpenMetrics=true \
    --set authentication.mutual.spire.install.enabled=true --set gatewayAPI.enabled=true --set gatewayAPI.externalTrafficPolicy=Local --set gatewayAPI.enableAlpn=true --set gatewayAPI.enableProxyProtocol=false

```

The gatewayClass is being created but it never gets accepted. 
There is no sign in the cilium operator pod that anything is happening that would try to approve the gatewayClass.

### How can we reproduce the issue?

1 install cilium cli
2 cilium install --version "v1.16.4" --set authentication.mutual.spire.enabled=true --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" --set hubble.enabled=true --set hubble.metrics.enableOpenMetrics=true \
    --set authentication.mutual.spire.install.enabled=true --set gatewayAPI.enabled=true --set gatewayAPI.externalTrafficPolicy=Local --set gatewayAPI.enableAlpn=true --set gatewayAPI.enableProxyProtocol=false

### Cilium Version

1.16.4

### Kernel Version

Linux ny2-slave-6b4d 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux

### Kubernetes Version

1.28,2

### Sysdump

[cilium-sysdump-20241218-222620.zip](https://github.com/user-attachments/files/18188463/cilium-sysdump-20241218-222620.zip)

### Relevant log output

```shell
Nothing related to this issue in the logs.
```

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mwielgosz-esky** [comment]
In my case similar problem was caused by using >=1.2.0 gateway-api CRDs (despite it is mentioned in docs as prerequisite). When used v1.1 (1.1.0 and 1.1.1) it started work. Kubernetes version doesn't matter (performed tests on 1.29, 1.30 and 1.31), helm chart used by me 1.16.5.

**Comment by zozo6015** [comment]
Will test and report back

**Comment by zozo6015** [comment]
I deployed the TLSRoute experimental CRD and restarted the operator and it does work.
