### ISSUE TITLE
CI: add function which waits for DNS to resolve host names of services

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3694]
Add a function implement some waiting function which waits until the host names for services resolve. Also revert the changes in #3695 so that tests are querying host names again instead of service IPs.

**Comment by rlenglet** [comment]
I think the issue linked in the description is incorrect. This has nothing to do with #3693.

**Comment by manalibhutiyani** [comment]
He was referring to #3695 Updated the link

**Comment by ianvernon** [comment]
My bad, thanks for fixing the issue link @manalibhutiyani .
