### ISSUE TITLE
Fix L3 only rules to wildcard L7

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3698]
- [x] Add an L7 wildcard for all L3 and L4 only rules after the L4 policy resolution step to ensure that the L4PolicyMap contains L7 wildcards (empty rule) for all source and destination selectors of L3 and L4 only rules.
- [x] Remove logic in `mergeL4*()` to delete rules on L4 only rules

**Comment by ianvernon** [comment]
My work for #3697 might cause conflicts with this. @rlenglet let's work together on solving this.

**Comment by ianvernon** [comment]
@tgraf can we close given that #3732 and https://github.com/cilium/cilium/pull/3634 are merged ?

**Comment by ianvernon** [comment]
Discussed with @tgraf offline, can be closed since the above are merged.

**Comment by joestringer** [comment]
@ianvernon does this apply for CIDR rule + L7 rule too?
