### ISSUE TITLE
Improve Policy Docs for traffic between K8s cluster + outside world

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#3708]
I was checking http://cilium.readthedocs.io/en/latest/policy/language/#entities-based to see if an example was there, and I also noticed that there are a few other things that might be confusing about the examples we have in the Entities section.  In particular, someone using K8s would probably be very confused that traffic from a pod to the outside world will match an "egress toEntities world" rule, but the traffic from the outside world to pods would most likely be coming from nodePort, and therefore be shown as "ingress fromEntities host".   In that sense, our two examples are flipped from the common case in K8s, as we make no mention of the role of NodePort in K8s.  

I know we have a separate K8s policy section, but at this point so many of our users are K8s (and we even default to showing k8s YAML) that I think its worth noting the NodePort basics on this page (possibly with a link to a detailed write-up in the k8s section which describes various nuances of K8s policy like that the source IP of something from NodePort will be the host, that HTTP healthchecks show up as coming from the host, etc.)

**Comment by tgraf** [comment]
https://github.com/cilium/cilium/issues/3539 is tracking the high level 1.0 review effort
