### ISSUE TITLE
Cilium unable to mount BPF fs

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#3717]
Nirmoy reported:
```
level=info msg=" ___|_| |_|_ _ _____"                                                                                                                                                                   
level=info msg="|  _| | | | | |     |"
level=info msg="|___|_|_|_|___|_|_|_|"
level=info msg="Cilium 1.0.0-rc10  go version go1.9.4 linux/amd64"
level=info msg="Envoy version check disabled"
level=info msg="clang (6.0.0) and kernel (4.12.14) versions: OK!"
level=info msg="linking environment: OK!"
level=info msg="bpf_requirements check: OK!"
level=warning msg="BPF root is not a BPF filesystem (0x62656572 != 0xcafe4a11)" file-path=/sys/fs/bpf
level=info msg="Mounted BPF filesystem /sys/fs/bpf"
level=info msg="Waiting for etcd client to be ready"
level=info msg="Valid label prefix configuration:"
level=info msg=" - :io.kubernetes.pod.namespace"
level=info msg=" - :io.cilium.k8s.namespace.labels"
level=info msg=" - !:io.kubernetes"
level=info msg=" - !:.*kubernetes.io"
level=info msg=" - !:pod-template-generation"
level=info msg=" - !:pod-template-hash"
level=info msg=" - !:controller-revision-hash"
level=info msg=" - !:annotation.cilium.io/"
level=info msg=" - !:annotation.cilium-identity"
level=info msg=" - !:annotation.sidecar.istio.io"
level=info msg="Container runtimes being used: \"docker\" on endpoint \"unix:///var/run/docker.sock\""
level=info msg="Waiting for k8s api-server to be ready..." subsys=k8s
[...]
level=info msg="  IPv6 router address: f00d::ac1c:400:0:81d6"
level=error msg="bpf: Unable to update in tunnel endpoint map" error="Unable to get object /sys/fs/bpf/tc/globals/tunnel_endpoint_map: no such file or directory" ipAddr=172.16.xxx.xxx/23
level=error msg="bpf: Unable to update in tunnel endpoint map" error="Unable to get object /sys/fs/bpf/tc/globals/tunnel_endpoint_map: no such file or directory" ipAddr="f00d::ac1c:400:0:0/112"
level=info msg="Loopback IPv4: 172.16.xxx.xxx"
```

Whereas worked on `cilium/stable`.

BPF fs was not mounted by Cilium:
```
caasp-master-0:~ # mount | grep bpf
caasp-master-0:~ # find /sys/fs/bpf/
/sys/fs/bpf/
```
Manually mounting and restarting resolved the issue (kubectl delete -f cilium.yaml then recreate).
```
caasp-master-0:~ # mount | grep bpf
bpf on /sys/fs/bpf type bpf (rw,relatime)
```

On top of: https://github.com/cilium/cilium/commit/42b330c4a14358a7100b70c82e39169ad7bcdd7f

Potentially bug in mountFS() where `mountpoint` could have failed for some reason where daemon instead assumed it was mounted but in reality it wasn't. 0x62656572 is the sysfs superblock magic, so mounting BPF fs should have been fine here.

**Comment by eloycoto** [comment]
Does this happen inside a container? If it's inside the container, the mount need to be in the host. I recommend the following systemd script: 
https://github.com/cilium/cilium/blob/master/contrib/systemd/sys-fs-bpf.mount

**Comment by borkmann** [comment]
@eloycoto: looping @nirmoy in here for above question.

**Comment by ianvernon** [comment]
@nirmoy is this a Minikube environment? We have only ever seen such behavior in minikube. 

An issue where we saw similar behavior is. https://github.com/cilium/cilium/issues/3519 . See @joestringer 's comment : https://github.com/cilium/cilium/issues/3519#issuecomment-378757566.

**Comment by vadorovsky** [comment]
I think that the cause of this issue is that we rely on the host - we expect the host to have `/sys/fs/bpf` mounted and we just mount that directory to the container. Of course that will fail in many environments (including Minikube), because the most of distros don't mount bpffs by default. The solution with systemd service linked by @eloycoto is tricky, because we cannot inject that service into Minikube VM without ugly hacks.

So I'd propose the other solution. `SYS_ADMIN` capability allows containers to moint bpffs. I think we can just give that capability to the Cilium daemonset, don't mount `/sys/fs/bpf` from host and just let Cilium do its job with mounting bpffs.

That approach works for me. After the changes from my PR, I cannot reproduce that issue in Minikube anymore and it seems that Cilium just mounts bpffs succesfully inside container:

```
 mrostecki   master  …  cilium  examples  minikube  minikube start
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
 mrostecki   master  …  cilium  examples  minikube  kubectl create -f cilium-ds.yaml 
configmap "cilium-config" created
secret "cilium-etcd-secrets" created
serviceaccount "cilium" created
clusterrolebinding "cilium" created
daemonset "cilium" created
clusterrole "cilium" created
 mrostecki   master  …  cilium  examples  minikube  kubectl --namespace=kube-system get all
NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-dns   1         1         1            1           3m

NAME                     DESIRED   CURRENT   READY     AGE
rs/kube-dns-2190035132   1         1         1         3m

NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/kube-dns   1         1         1            1           3m

NAME                             READY     STATUS    RESTARTS   AGE
po/cilium-w4rp1                  0/1       Running   0          1m
po/kube-addon-manager-minikube   1/1       Running   0          3m
po/kube-dns-2190035132-wz3zh     3/3       Running   0          3m
po/kubernetes-dashboard-0t63x    1/1       Running   0          3m

NAME                      DESIRED   CURRENT   READY     AGE
rc/kubernetes-dashboard   1         1         1         3m
 mrostecki   master  …  cilium  examples  minikube  kubectl create -f demo.yaml 
service "app1-service" created
deployment "app1" created
pod "app2" created
pod "app3" created
 mrostecki   master  …  cilium  examples  minikube  kubectl create -f l3_l4_l7_policy.yaml 
ciliumnetworkpolicy "rule1" created
 mrostecki   master  …  cilium  examples  minikube  kubectl --namespace=kube-system logs po/cilium-w4rp1
level=info msg="     _ _ _"
level=info msg=" ___|_| |_|_ _ _____"
level=info msg="|  _| | | | | |     |"
level=info msg="|___|_|_|_|___|_|_|_|"
level=info msg="Cilium 1.0.0-rc9 cdfb40c8a 2018-03-30T20:56:14+02:00 go version go1.9 linux/amd64"
level=info msg="cilium-envoy  version: cdfb40c8aa4c26b83061555984d9a65788fdb2ae/1.7.0-dev/Distribution/RELEASE"
level=info msg="clang (3.8.1) and kernel (4.9.13) versions: OK!"
level=info msg="linking environment: OK!"
level=info msg="bpf_requirements check: OK!"
level=info msg="Mounted BPF filesystem /sys/fs/bpf"
level=info msg="Waiting for etcd client to be ready"
level=info msg="Valid label prefix configuration:"
level=info msg=" - :io.kubernetes.pod.namespace"
level=info msg=" - :io.cilium.k8s.namespace.labels"
level=info msg=" - !:io.kubernetes"
level=info msg=" - !:.*kubernetes.io"
level=info msg=" - !:pod-template-generation"
level=info msg=" - !:pod-template-hash"
level=info msg=" - !:controller-revision-hash"
level=info msg=" - !:annotation.cilium.io/"
level=info msg=" - !:annotation.cilium-identity"
level=info msg="Container runtimes being used: \"docker\" on endpoint \"unix:///var/run/docker.sock\""
level=info msg="Waiting for k8s api-server to be ready..." subsys=k8s
level=info msg="Connected to k8s api-server" ipAddr="https://10.0.0.1:443" subsys=k8s
level=info msg="Retrieved node information from kubernetes" nodeName=minikube subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=192.168.99.101 ipAddr.ipv6="<nil>" nodeName=minikube subsys=k8s
level=info msg="Automatically retrieved IP for node. Using it for ipv4-node" ipAddr=192.168.99.101 node=minikube
level=info msg="k8s mode: Allowing localhost to reach local endpoints"
level=info msg="Using autogenerated IPv4 allocation range" v4Prefix=10.15.0.0/16
level=info msg="Using autogenerated IPv6 allocation range" v6Prefix="f00d::a0f:0:0:0/96"
level=info msg="Addressing information:"
level=info msg="  Local node-name: minikube"
level=info msg="  Node-IPv6: fc00::10ca:1"
level=info msg="  External-Node IPv4: 192.168.99.101"
level=info msg="  Internal-Node IPv4: 10.15.28.238"
level=info msg="  Cluster IPv6 prefix: f00d::/64"
level=info msg="  Cluster IPv4 prefix: 10.0.0.0/8"
level=info msg="  IPv6 node prefix: f00d::a0f:0:0:0/96"
level=info msg="  IPv6 allocation prefix: f00d::a0f:0:0:0/112"
level=info msg="  IPv4 allocation prefix: 10.15.0.0/16"
level=info msg="  IPv6 router address: f00d::a0f:0:0:8ad6"
level=info msg="Loopback IPv4: 10.15.247.232"
level=info msg="Added L2 nexthop route" route="{Ifindex: 19 Dst: 10.15.28.238/32 Src: <nil> Gw: <nil> Flags: [] Table: 0}"
level=info msg="Installed node route" route="{Ifindex: 19 Dst: 10.15.0.0/16 Src: 10.15.28.238 Gw: 10.15.28.238 Flags: [] Table: 0}"
level=info msg="Added L2 nexthop route" route="{Ifindex: 19 Dst: f00d::a0f:0:0:8ad6/128 Src: <nil> Gw: <nil> Flags: [] Table: 0}"
level=info msg="Installed node route" route="{Ifindex: 19 Dst: f00d::a0f:0:0:0/112 Src: fc00::10ca:1 Gw: f00d::a0f:0:0:8ad6 Flags: [] Table: 0}"
level=info msg="Setting sysctl net.core.bpf_jit_enable=1"
level=info msg="Setting sysctl net.ipv4.conf.all.rp_filter=0"
level=info msg="Setting sysctl net.ipv6.conf.all.disable_ipv6=0"
level=info msg="Restoring endpoints from former life..."
level=info msg="No old endpoints found."
level=info msg="Envoy: Starting xDS gRPC server listening on /var/run/cilium/xds.sock"
level=info msg="Serving cilium node monitor at unix:///var/run/cilium/monitor.sock"
level=info msg="level=info msg=\"Serving cilium health at http://[::]:4240\"" netns=cilium-health
level=info msg="Endpoint policy recalculated" containerID=cilium-loc endpointID=29898 policyRevision=0
level=info msg="Adding route" command="ip route add 10.15.28.238/32 dev cilium" netns=cilium-health
level=info msg="Adding route" command="ip route add 0.0.0.0/0 via 10.15.28.238 dev cilium" netns=cilium-health
level=info msg="Adding route" command="ip -6 route add f00d::a0f:0:0:8ad6/128 dev cilium" netns=cilium-health
level=info msg="Adding route" command="ip -6 route add ::/0 via f00d::a0f:0:0:8ad6 dev cilium" netns=cilium-health
level=error msg="Cannot create CEP" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (29898)" endpointID=29898 error="the server could not find the requested resource (post ciliumendpoints.cilium.io)" policyRevision=0
level=info msg="Creating CRD (CustomResourceDefinition)..." name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="No request received to manage networking for container" containerID=9d52e023e1 maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=032745cd29 maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=657a68de8e maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=1112ea0d81 maxRetry=20 subsys=containerd-watcher
level=error msg="Cannot create CEP" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (29898)" endpointID=29898 error="the server could not find the requested resource (post ciliumendpoints.cilium.io)" policyRevision=0
level=info msg="No request received to manage networking for container" containerID=88a16a5919 maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=8051d0d880 maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=77f70f6fed maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=4597ed4bc5 maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=2cc8c88c6b maxRetry=20 subsys=containerd-watcher
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="Creating CRD (CustomResourceDefinition)..." name=v2.CiliumEndpoint subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=v2.CiliumEndpoint subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=v2.CiliumEndpoint subsys=k8s
level=info msg="Installed node route" route="{Ifindex: 19 Dst: 10.15.0.0/16 Src: 10.15.28.238 Gw: 10.15.28.238 Flags: [] Table: 0}"
level=info msg="Added L2 nexthop route" route="{Ifindex: 19 Dst: f00d::a0f:0:0:8ad6/128 Src: <nil> Gw: <nil> Flags: [] Table: 0}"
level=info msg="Installed node route" route="{Ifindex: 19 Dst: f00d::a0f:0:0:0/96 Src: fc00::10ca:1 Gw: f00d::a0f:0:0:8ad6 Flags: [] Table: 0}"
level=info msg="Endpoint policy recalculated" containerID=cilium-loc endpointID=29898 policyRevision=1
level=info msg="Serving prometheus metrics on :9090"
level=info msg="Serving cilium at unix:///var/run/cilium/cilium.sock"
level=info msg="Serving cilium health at http://[::]:4240"
level=info msg="Serving cilium health at unix:///var/run/cilium/health.sock"
level=info msg="Policy imported via API, recalculating..." policyRevision=2
level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=rule1 k8sApiVersion= k8sNamespace=default
level=info msg="No request received to manage networking for container" containerID=741c5e779a maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=eb56575f7f maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=a99c3a18d2 maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=b5dcf961bd maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=6392b81b6e maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=4b2b59e213 maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=8178fb8b32 maxRetry=20 subsys=containerd-watcher
level=info msg="No request received to manage networking for container" containerID=a89ca0527e maxRetry=20 subsys=containerd-watcher
 mrostecki   master  …  cilium  examples  minikube  minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ docker ps | grep cilium-agent
8178fb8b3222        cilium/cilium@sha256:9cfd32e1cfc06c7f5a50a1b3e2b5b782e53344b4a518fd1c67cd5c161940cc31                                          "cilium-agent --debug"   About a minute ago   Up About a minute                       k8s_cilium-agent_cilium-w4rp1_kube-system_a4be969a-4223-11e8-ab36-0800273d08fb_0
$ docker exec -ti 8178fb8b3222 bash
root@minikube:~# mount | grep bpf
bpffs on /sys/fs/bpf type bpf (rw,relatime)
bpffs on /sys/fs/bpf/xdp type bpf (rw,relatime)
bpffs on /sys/fs/bpf/ip type bpf (rw,relatime)
```

As you can see, the error doesn't occur anymore and bpffs is mounted inside the container.

**Comment by vadorovsky** [comment]
If you agree with that solution, I'm going to update every DaemonSet yaml file with that change.

**Comment by nirmoy** [comment]
@eloycoto  I dont have that issue anymore but I still get "level=warning msg="BPF root is not a BPF filesystem (0x62656572 != 0xcafe4a11)" file-path=/sys/fs/bpf" but cilium works. 
@ianvernon  Its not in minikube, I am using SUSE container platform(caasp). 

(Sorry for late reply, I haven't receive any notification for some reason)

**Comment by nirmoy** [comment]
@mrostecki When I mount it on host machine(mount -t bpf bpf /sys/fs/bpf/) the warning goes off, so I would prefer orchestration engine to make sure bpffs is mounted before running cilium. It is more secure I think.

**Comment by vadorovsky** [comment]
@nirmoy Mounting it on host is a little bit more secure (just a bit, we already give the `NET_ADMIN` capability and do a lot of "insecure" stuff in the container :) ), but with that approach you need to tell everyone to configure the host, to modify fstab or inject a systemd service, which is really painful - especially on public clouds or VM environments which already have their complicated provisioning systems.

I know that we can do everything we want in openSUSE, but I would like to have a more general solution which will be painless for everyone.

Also, if you want to keep the approach of mounting on the host, do you have any proposition how to fix Minikube example?

**Comment by mrostecki** [comment]
@nirmoy One more thing. The warning:

```
"level=warning msg="BPF root is not a BPF filesystem (0x62656572 != 0xcafe4a11)" file-path=/sys/fs/bpf"
```

is caused exactly by the hostMount. Cilium tries to manage the bpffs mount by itself, but it already sees that this directory is mounted with the other filesystem by runc..

The majority of Cilium users will use Cilium with Kubernetes, inside containers. So we end up with that warning for the majority of users! Isn't it a bit inappropriate?

**Comment by vadorovsky** [comment]
Regarding the security concerns once again - the most popular CNI providers (Calico and Flannel) run in privileged containers, which gives them *all* capablities:

https://github.com/projectcalico/calico/blob/master/v2.6/getting-started/kubernetes/installation/hosted/calico.yaml#L176
https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L135

So I don't see any reason why we should restrict ourselves from mounting bpffs from the container.

**Comment by nirmoy** [comment]
@mrostecki cilium too
 https://github.com/cilium/cilium/blob/master/examples/minikube/cilium-ds.yaml#L186
So its  mountFS() related issue. But I can't reproduce the same behavior in my setup to get more details.

**Comment by nirmoy** [comment]
@eloycoto do we need 
 capabilities:
            add:
- "NET_ADMIN"

when  privileged: true ?
[update] I tested on my setup, "privileged: true" indeed enough to run cilium.

**Comment by vadorovsky** [comment]
No, we don't, I missed that line with `privileged: true`, I'm sorry.

We can either get rid of the list of capabilities (easier solution) and just rely on `privileged` mode, or list the specific capabilities we need like `SYS_ADMIN`, `NET_ADMIN` etc. (harder solution, but might be slightly more secure).

I will update my PR with the easier solution.

**Comment by vadorovsky** [comment]
OK, I closed the old pull request - I realized that BPFFS mount on the host is needed and recommended.

I created the new PR with an another approach to solve the problem. If Cilium is running inside container, but BPFFS is not mount on the host, then IMO we should unmount `/sys/fs/bpf` and mount BPFFS in the container. And also warn the user that we recommend to mount BPFFS on the host.

@aanm @tgraf What do you think?

**Comment by aanm** [comment]
@mrostecki I am afraid that way you will potentially create harmful changes to the user host, by unmounting a path without the user's consent.

**Comment by vadorovsky** [comment]
I don't think that unmounting `/sys/fs/cgroup` inside container can do anything harmful for the host, especially if it's the empty mount. But I understand your concern if potentially something goes wrong with non-containerized Cilium.

I can try to add some code which will check whether Cilium is running inside container (`/proc/1/cgroup`) and remount only in that case. Does is sound better to you?

**Comment by borkmann** [comment]
What happens if the mountpoint is a shared mount with the init mountns? Could we check whether it's a private mountpoint instance in the container and only then proceed if not mounted yet at /sys/fs/bpf/? A completely different approach is to create a new mountpoint specifically for cilium somewhere under Cilium's run dir or such and mount a bpf fs instance from there to not interfere with anything else.

**Comment by vadorovsky** [comment]
>What happens if the mountpoint is a shared mount with the init mountns?

It will always happen for containerized Cilium. Every mount that Docker/runc creates is a `--bind` mount. So yeah, in container's mount ns, it always will be a shared mount with the init mountns.

>Could we check whether it's a private mountpoint instance in the container and only then proceed if not mounted yet at /sys/fs/bpf/?

Same answer as above - if you are running Cilium in container, the `/sys/fs/bpf` is a shared mount from host mountns to the container mountns. In my pull requrest, if the filesystem of `/sys/fs/bpf` is not `bpffs`, then Cilium is going to unmount it and then mount `bpffs` again, privately. I guess that's what might be concerning for you.

>A completely different approach is to create a new mountpoint specifically for cilium somewhere under Cilium's run dir or such and mount a bpf fs instance from there to not interfere with anything else.

OK, this sounds like a better idea. Maybe our steps with bpffs mounting should be:

- Checking whether `/sys/fs/bpf` is mounted with BPFFS filesystem.
- If yes, just use that mount.
- If not, mount bpffs in `/run/cilium/bpffs` (or smth like that) and use that. And of course show the warning to used - that we recommend to mount `/sys/fs/bpf` on the host.

If that sounds good to you, I will switch to that approach.

**Comment by borkmann** [comment]
> In my pull requrest, if the filesystem of /sys/fs/bpf is not bpffs, then Cilium is going to unmount it and then mount bpffs again, privately. I guess that's what might be concerning for you.

Ok, if the magic number is neither 0x62656572 (pointing to sysfs /sys/ mount instance higher in the hierarchy) nor 0xcafe4a11 (bpf fs instance), then the setup is bogus and utterly broken. The expectation is that this location / mount point is reserved for bpf fs only, so either it's mounted there or not. Therefore, unmounting some completely different file system instance (e.g. tmpfs) I would consider okay since this is not an expected location for it. Btw, new systemd releases will mount bpf fs there automatically.

**Comment by borkmann** [comment]
> OK, this sounds like a better idea. Maybe our steps with bpffs mounting should be:

The approach you describe sounds sane to me, although if we go that route we might as well switch unconditionally to some private `/run/cilium/bpf/fs` mount instance. @tgraf thoughts?

**Comment by nirmoy** [comment]
I like the idea of mounting bpffs to Cilium's run dir.

**Comment by vadorovsky** [comment]
>although if we go that route we might as well switch unconditionally to some private /run/cilium/bpf/fs mount instance

That's a good idea too. I think we can use names `/run/cilium/bpf/fs_host` and `/run/cilium/bpf/fs_internal`, it will make debugging easier and even looking at `/proc/mounts` will make it clear which kind of mount we are using.

**Comment by techcet** [comment]
Hit a similar issue with minikube 0.25.2, k8s 1.9.4, cilium v1.0.2.

**Comment by joestringer** [comment]
Reopening due to revert.
