### ISSUE TITLE
Better log indication on monitor disconnect

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3723]
Better log message on monitor disconnect:
```
level=info msg="New monitor connected." count.listener=1
level=warning msg="Monitor removed due to write failure" error="write unix /var/run/cilium/monitor.sock->@: write: broken pipe"
```

This indicates a problem when there is in fact no problem

**Comment by raybejjani** [comment]
@tgraf Is the issue that the Warn is scary? or that the error attached to it is scary? We can mask a subset of error messages or we can just make everything an Info.
