### ISSUE TITLE
5b03fb86 broke agent-labels and access-log config via env

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3751]
It looks like 5b03fb8635551b1ae3c3012beecebe0e16e606b1 unintentionally broke setting the agent-label and access-log via environment variables by replacing the `viper.GetString()`.

Cilium uses `viper.AutomaticEnv()` which will make all configuration parameters accessed via `GetString()` available as environment variables.

**Comment by rlenglet** [comment]
I’ll add `viper.BindEnv` calls.
Out of curiosity, where have we been relying on those environment variables?
