### ISSUE TITLE
Documentation: some dead links to commands generated via cmdref 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3756]
If I want to access a specific command from the latest documentation for the [Command Reference](http://docs.cilium.io/en/latest/cmdref/cilium/), for instance [cilium bpf](http://docs.cilium.io/en/latest/cmdref/cilium_bpf/), the link works ( http://docs.cilium.io/en/latest/cmdref/cilium_bpf/ ) . However, if I go to the following link http://docs.cilium.io/en/latest/cmdref/cilium/ , none of the links under `SEE ALSO` work correctly.

**Comment by joestringer** [comment]
Duplicate of https://github.com/cilium/cilium/issues/3260
