### ISSUE TITLE
Develop test to simulate temporary API server failure

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3779]
- [ ] Develop a manual test to simulate the behavior when 1-all k8s apiservers are down
- [ ] Verify that all endpoints are being restored properly even if Cilium continue to be restarted, possibly in the middle of restoring an endpoint
- [ ] Document the behavior when external dependencies such as the apiserver fail

**Comment by raybejjani** [comment]
As a counter example. I've turned off kube-apiserver when testing things in a dev VM and cilium recovered well. We might need to simulate connection timeouts or traffic being blackholed instead of just stopping the server, or it may be related to the number of endpoints.

**Comment by ianvernon** [comment]
Is this related to #3790 ?

**Comment by tgraf** [comment]
This has been resolved by extensive manual testing
