### ISSUE TITLE
Split debuginfo into separate files in bugtool

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3799]
We should be able to split the debuginfo file into multiple files, if someone wants to simply compare a bugtool output from multiple nodes such as `cilium endpoint list`, it is nontrivial to try to filter the debuginfo file for each bugtool archive just to find this specific piece of information for all of the cilium instances.

**Comment by ianvernon** [comment]
This could be done via an argument to `cilium debuginfo` itself? I.e., `cilium debuginfo --file-per-command` or some other CLI argument. This could be done by default in the bugtool. What do you think?
