### ISSUE TITLE
CI: audit tests to ensure resources are not deleted within `It`

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3821]
Audit the tests to find instances where resources are deleted with `defer`. Move these deferred deletions to be within `AfterEach` 

- [x] `test/k8sT/Policies.go: KubernetesNetworkPolicy between server and client `
    - PR: https://github.com/cilium/cilium/pull/3823
- [x] `test/k8sT/Policies.go: Same Policy in the different namespaces`
    - PR: https://github.com/cilium/cilium/pull/3823
- [x] `test/k8sT/Services.go: Check Service`
    - PR: https://github.com/cilium/cilium/pull/3823
- [x] `test/k8sT/Services.go: Checks service across nodes`
    - PR: https://github.com/cilium/cilium/pull/3823
- [x] `test/k8sT/Services.go Check NodePort`
    - PR: https://github.com/cilium/cilium/pull/3823
- [x] `test/runtime/Policies.go: Policy cmd`
    - PR: https://github.com/cilium/cilium/pull/4112
- [x] `test/runtime/cli.go`
    - PR: https://github.com/cilium/cilium/pull/4112
- [x] `test/runtime/monitor.go: Cilium monitor event types`
    - PR: https://github.com/cilium/cilium/pull/4112
- [x] `test/k8sT/Policies.go: testCanConnect`
    - The test which uses this function needs to be refactored to achieve the goal outlined above.
- [x] `test/k8sT/Tunnels.go: Check VXLAN mode`
    - PR: #3854
- [x] `test/k8sT/Tunnels.go: Check Geneve mode`
    - PR: #3854
- [x] `test/k8sT/Services.go: External services`
    - PR:  #4114 
- [x] `test/k8sT/Nightly.go: Test TCP Keepalive with L7 Policy`
    - PR: https://github.com/cilium/cilium/pull/4115
- [x] `test/k8sT/Nightly.go: Test TCP Keepalive without L7 Policy`
    - PR: https://github.com/cilium/cilium/pull/4115
- [x] `test/k8sT/Nightly.go: GRPC example`
   -  PR: #4115

**Comment by jrfastab** [comment]
This is old, dropping needs-backport tag. Feel free to add it back on specific PRs if needed.

**Comment by eloycoto** [comment]
review the k8st/Policies.go and all is correct. Task finished.
