### ISSUE TITLE
Move GetMaxLabelID() to outer loop

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#384]
Move `maxID, err := owner.GetMaxLabelID()` in `regenerateConsumable` to outer loop to avoid refetching for every consumable.

**Comment by stevenceuppens** [comment]
@tgraf i think this is fixed by @aanm 
commit bc0ceb228ae49b9f8a77dc9a404200aea6e1b7d7
daemon: implemented GetCachedMaxLabelID

**Comment by tgraf** [comment]
Agreed, thanks @stevenceuppens
