### ISSUE TITLE
Ingress allow-all fromEndpoints allows from world

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3847]
http://docs.cilium.io/en/latest/policy/language/#ingress-allow-all

In non-kubernetes environments, this policy matches all labels, which includes entity labels such as "reserved:world" and "reserved:host".

```
[{
    "labels": [{"key": "name", "value": "allow-all-to-victim"}],
    "endpointSelector": {"matchLabels": {"role":"victim"}},
    "ingress": [{
        "fromEndpoints": [
          {"matchLabels":{}}
        ]
    }]
}]
```

This is a bit counter-intuitive when the name of the field is `fromEndpoints`.

For 1.0, perhaps we should just document this.

For a future version, policy v3 should attempt to unify this.

**Comment by tgraf** [comment]
fromEndpoints has evolved to support everything that can be addressed as a label so it includes CIDR and label compatible entities.

However, I'm surprised that the above works in the context of a k8s policy as the labelSelector should get extended to include a namespace label match. I think it will work when imported as JSON or when performing unit tests but it should not work when actually imported as a CNP via k8s.

**Comment by joestringer** [comment]
I was testing in a non-kubernetes environment, so that explains the behaviour I observed.
