### ISSUE TITLE
Pre Identity Policy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3855]
When an endpoint is being bootstrapped, we put each endpoint into a drop-all mode which drops all packets except for ARP resolution of the default gateway IP until the identity of the endpoint has been resolved. This requires two pre conditions to be met:

* Labels (container and k8s) have been retrieved
* Identity has been resolved via kvstore

With standard TCP timeouts, this never causes issues as the above process typically happens within 1-2 seconds.

Under severe load and in combination with applications that impose a very short timeout (1-2 seconds context deadline), the above practice can lead to problems.

Design proposal:
- [ ] Introduce new reserved identity `reserved:init`
- [ ] Endpoints that are in pre identity state are being assigned this identity. Init identity is the new default.
- [ ] Policy can be defined using standard APIs using the label `reserved:init` and entity `init`
   - [ ] Open question: Conformance with k8s namespaces. Default endpointSelector in k8s will add match on k8s namespace label. I think this is a good start.
- [ ] An endpoint in `!e.policyCalculated()` state resolves the policy based on the init identity and falls back to DROP_ALL if no policy is applied.
   - [ ] If endpoint has identity init, then DROP_ALL has to be defined if no policy rules apply to the endpoint.
   - [ ] Important: An init policy on egress and no ingress does not mean that ingress should be default-allow.

**Comment by ianvernon** [comment]
Assigned to Romain since he already started working on this.
