### ISSUE TITLE
CI: cilium.log cut off too early

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#3860]
Looking at master build regression https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/705/testReport/junit/(root)/runtime/RuntimeValidatedPolicies_L3_Dependent_L7_Egress/:

Failing test command is given in the above log as:
```
�[1mSTEP�[0m: Client "app3" attempting to curl public URL on httpd1
time="2018-04-23T11:28:51Z" level=debug msg="running command: docker exec -i  app3 curl -s --fail --connect-timeout 5 --max-time 5 http://10.15.129.91:80/public"
```

However, in the build artifacts the last logs in `cilium.log` are:
```
Apr 23 11:28:45 runtime cilium-agent[2652]: level=debug msg="level=debug msg=\"external/envoy/source/server/listener_manager_impl.cc:30]     name: envoy.http_connection_manager\" subsys=envoy-config thread=10093"
Apr 23 11:28:45 runtime cilium-agent[2652]: level=debug msg="level=debug msg=\"external/envoy/source/server/listener_manager_impl.cc:33]   config: {\"stat_prefix\":\"proxy\",\"route_config\":{\"virtual_hosts\":[{\"domains\":[\"*\"],\"routes\":[{\"match\":{\"prefix\":\"/\"},\"route\":{\"cluster\":\"cluster1\"}}],\"name\":\"default_route\"}]},\"http_filters\":[{\"config\":{\"denied_403_body\":\"\",\"access_log_path\":\"/var/run/cilium/access_log.sock\",\"policy_name\":\"10.15.13.37\"},\"name\":\"cilium.l7policy\"},{\"config\":{},\"name\":\"envoy.router\"}]}\" subsys=envoy-config thread=10093"
```

Basically `cilium.log` is missing the critical output right before and during the test command.

**Comment by jrajahalme** [comment]
The regression in the test is that L3-dependent L7 policy does not take effect. The last policy for the endpoint that is visible in the logs does not have L7 at all, but we see from the very last line of the log that a L7 redirect/listener is being installed to Envoy. This should only happen if there is a L7 policy for that endpoint. Due to logs being cut off we don't see of such L7 policy is installed, and what the timing of that is in relation to the test command.

**Comment by ianvernon** [comment]
Playing devil's advocate here - what if Cilium wasn't outputting any logs?

**Comment by jrajahalme** [comment]
The way the logs end tells me that they are somehow cut off, as the test log has evidence that cilium-agent was running after the logs end (e.g., successful `cilium policy wait 17`). That happening would have more logs indicating the xDS ACKs, etc.

Another thing that may explain this is some kind of log rotation on, but do we have it on the cilium logs?

**Comment by jrajahalme** [comment]
Log outage also in #3991

**Comment by ianvernon** [comment]
@jrajahalme in an effort to do some ticket cleanup, I'm closing this since #4054 was merged. We can reopen if we see this again.
