### ISSUE TITLE
Add metrics to report Endpoint build failures and count of current endpoint state

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#3863]
We export some prometheus metrics today (https://github.com/cilium/cilium/blob/master/pkg/metrics/metrics.go) but they are sparse. As part of monitoring cluster health, it would be useful to report:
- a counter of endpoint build failures
- a count of endpoints, labelled by the endpoint state (i.e. the same metric name but with different labels, similar to https://github.com/cilium/cilium/blob/master/pkg/metrics/metrics.go#L105-L131 although dynamic labels may be possible).

Note that the prometheus collector will add node-name or pod-name labels if configured. `cilium-agent` only needs to present the simplest of names.

It may be useful to keep in mind the metrics we want to add in https://github.com/cilium/cilium/issues/3338 when building the internal tooling to collect these.

**Comment by manalibhutiyani** [comment]
@raybejjani @tgraf Regarding adding   `a counter of endpoint build failures`
We already have this code in place

```
// Called with e.Mutex UNlocked
func (e *Endpoint) regenerate(owner Owner, reason string) (retErr error) {
    metrics.EndpointCountRegenerating.Inc()
    defer func() {
        metrics.EndpointCountRegenerating.Dec()
        if retErr == nil {
            metrics.EndpointRegenerationCount.
                WithLabelValues(metrics.LabelValueOutcomeSuccess).Inc()
        } else {
            metrics.EndpointRegenerationCount.
                WithLabelValues(metrics.LabelValueOutcomeFail).Inc()
        }
    }()
```
Hence endpoint regeneration count is already in place labelled by either `success` or `failure` i.e build failure. Is something else needed here or am I missing something here?

**Comment by raybejjani** [comment]
@manalibhutiyani I think you're correct. I can't remember if there was a specific, and different, thing I had mind for this but what we have today does what that bullet says.

**Comment by tgraf** [comment]
Agreed, looks good regarding endpoint failures.
