### ISSUE TITLE
Single flag to configure kvstore

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#387]
Consolidate multiple flags into a single kvstore flag which allows configuring either etcd, consul, local, ...

Currently the kvstore configuration is done via a mixture of flags which have grown over time:
 -         flags.StringVar(&consulAddr, "consul", "", "Consul agent address [127.0.0.1:8500]")
 -         flags.StringSliceVar(&etcdAddr, "etcd", []string{}, "Etcd agent address [http://127.0.0.1:2379]")
 -         flags.StringVar(&config.EtcdCfgPath, "etcd-config-path", "", "Absolute path to the etcd configuration file"

This should be replaced with a single `--kvstore` flag or similar which takes a type and then options. Currently the behaviour is even unclear if someone specifies both consul and etcd.

**Comment by ianvernon** [comment]
This one is fun. Providing a simple flag is easy enough. I'm thinking that keeping the other options around though at this time is good (e.g., consulAddr, etcAddr), as only primitive types / slices are supported as types for flags in the Cobra / pflag library. Is that sufficient? Then, based on the kvstore flag type passed in we can check for presence of other configuration values that are passed into the daemon.

**Comment by tgraf** [comment]
I think both is fine, either doing `--kvstore TYPE` with a generic `--kvstore-opts=SLICE` which parses a list of options or having specific options that we group in a kvstore section that cobra supports.

**Comment by ianvernon** [comment]
@tgraf: @aanm and I were discussing whether we should have default values or not for etcdAddr, EtcdConfigPath, consulAddr, etc. Currently the defaults are blank and we error out in other parts of the code if these values are not set as expected. Since we now have the kvstore flag, we can provide default values, since before the kvstore flag change, the only way of figuring out which key-value store to use was to check whether certain flags had values set or not. What do you think?

**Comment by tgraf** [comment]
> @tgraf: @aanm and I were discussing whether we should have default values or not for etcdAddr, EtcdConfigPath, consulAddr, etc. Currently the defaults are blank and we error out in other parts of the code if these values are not set as expected. Since we now have the kvstore flag, we can provide default values, since before the kvstore flag change, the only way of figuring out which key-value store to use was to check whether certain flags had values set or not. What do you think?

👍 for default values as we no longer depend on the values to figure out if kvstore should be enabeld.
