### ISSUE TITLE
Move common kvstore code into interface

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#388]
Each kvstore backend implementation has some duplicated code which can be moved into a common interface.

**Comment by travissalascox** [comment]
@tgraf was looking at the kvstore and was wonder if this issue has already been completed?

saw this under the kvstore package in kvstore.go

```
type KVClient interface {
	LockPath(path string) (KVLocker, error)
	GetValue(k string) (json.RawMessage, error)
	SetValue(k string, v interface{}) error
	InitializeFreeID(path string, firstID uint32) error
	GetMaxID(key string, firstID uint32) (uint32, error)
	SetMaxID(key string, firstID, maxID uint32) error

	GASNewSecLabelID(baseKeyPath string, baseID uint32, secCtxLabels *policy.Identity) error
	GASNewL3n4AddrID(basePath string, baseID uint32, lAddrID *types.L3n4AddrID) error

	DeleteTree(path string) error

	GetWatcher(key string, timeSleep time.Duration) <-chan []policy.NumericIdentity

	Status() (string, error)
}

type KVLocker interface {
	Unlock() error
}
```

was just wondering if there more you were wanting to do with this issue?

**Comment by tgraf** [comment]
@travissalascox I think it's mostly complete. I noticed some code duplication while doing the local kvstore backend which ideally would be factored out into a common piece of code. Not supercritical though.
