### ISSUE TITLE
CI: KubernetesNetworkPolicy performs deferred cleanup in test function

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3900]
This call cleans up state as part of the test:

https://github.com/cilium/cilium/blob/4fd4e09ce6c94102cf46f4d918042c0868b64d4d/test/k8sT/Policies.go#L861

https://github.com/cilium/cilium/blob/4fd4e09ce6c94102cf46f4d918042c0868b64d4d/test/k8sT/Policies.go#L1187-L1191

This is poor form, it prevents appropriate log gathering on failure.

**Comment by ianvernon** [comment]
This duplicates https://github.com/cilium/cilium/issues/3821

**Comment by ianvernon** [comment]
Closing since it duplicates #3821 .
