### ISSUE TITLE
Disable drop-all policy mode when no policies are loaded

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3933]
There is no point to go through drop-all mode if the policy enforcement is set to "default" and no policies are loaded at all. Skip the drop-all step alltogether.

**Comment by jrajahalme** [comment]
@manalibhutiyani Would DROP_ALL test start failing due to this change?

**Comment by manalibhutiyani** [comment]
I believe that it will. We will need to adjust the DROP_ALL tests to have a policy enforced (similar to the pre-identity changes that @rlenglet is working on)

**Comment by manalibhutiyani** [comment]
But I think your change on this PR might conflict with what @rlenglet  was planning to implement for pre-identity. We should sync up to make sure there is no confusion there.

**Comment by rlenglet** [comment]
Agreed, this should not be needed after https://github.com/cilium/cilium/pull/3911 is in.

**Comment by jrajahalme** [comment]
#3938 implements this

**Comment by tgraf** [comment]
> Agreed, this should not be needed after #3911 is in.

What is not needed?

**Comment by rlenglet** [comment]
Because I think it's redundant.

**Comment by tgraf** [comment]
Discussed in person. The goal of this issue is to never require user intervention if the user does not have the intent to ever load policies rules.

Always requiring an init identity policy for certain use cases only makes sense if the user intents to lock down the environment in some form. This issue is exclusively addressing the use case of a user running the default configuration but never loading policy.
