### ISSUE TITLE
Improve cilium status error if agent is still down

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3934]
When cilium is starting, kubelet will invoke readiness probes. We have a short readiness delay to indicate readiness as early as possible. The error message does not make this very clear though and can be improved.

```
Warning  Unhealthy              2m (x3 over 2m)  kubelet, ip-10-202-138-139.ec2.internal  Readiness probe failed: Get http:///var/run/cilium/cilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
```

**Comment by FlogFr** [comment]
Hello, I'm having the same issue with a fresh install with kubeadm, following the documentation.
My cluster with the single master/control plane and 2 cluster nodes are communicating with private VLAN I setup over IP tunnel and IP Sec. I changed the the --node-ip of the kubelet on the nodes to use the private IP.
Now, I'm checking the Cilium DaemonSet from the master and I notice the same error as this issue.
```
  Warning  Unhealthy  4m (x35 over 8m35s)    kubelet, k8s-node-1  Readiness probe failed: Get http:///var/run/cilium/cilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
```

Do you have a workaround?

Thank you

**Comment by tgraf** [comment]
@FlogFr The error indicates that the cilium agent is not running at all. Is the cilium pod marked as running?

**Comment by FlogFr** [comment]
The cilium pod is marked as crashed:
```
cilium-d4zbw                           0/1     CrashLoopBackOff   202        20h   10.110.0.2      k8s-node-1     <none>           <none>
```

**Comment by tgraf** [comment]
@FlogFr Then it's most likely a different issue. Join our slack channel and we are happy to help debug it.

**Comment by tgraf** [comment]
This has since been fixed
