### ISSUE TITLE
Extract monitor daemon into different container

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#3954]
Monitor daemon can be extracted from Cilium container to new container within the pod.

AFAIK all communication between Cilium agent and monitor daemon happens through unix domain sockets, they can be shared between containers as pod volumes.

First step would be to run `cilium-node-monitor` in second container based on `cilium/cilium` image and disable agent code starting monitor inside main cilium container.

**Comment by nebril** [comment]
@raybejjani any comments here?

**Comment by raybejjani** [comment]
However we do this, we should keep in mind that we will want to do the same thing with envoy & co.
I'm not sure if the agent crashes or exits when the monitor is not detected. Another thing to consider is that we currently pipe stdout and stderr to the agent (I think. I might be wrong). We would need to restructure that appropriately. In a similar vein, we also need to consider how annoying it will be to have to now type `kubectl log cilium agent-container`. Perhaps there is a way to pick a default?

The context for this ticket was to allow for someone running the monitor independently as a log source, while supporting some of the newer features we might add to the monitor (in addition to forwarding identity and label changes to microscope, we would also include IP and podname. This is mostly to avoid the monitor itself talking to anything but the cilium-agent).

**Comment by raybejjani** [comment]
We also need to be careful about how we version the image for this. There is an API between the agent and monitor but we just don't track it well. It wouldn't be terribly good to split these up, then create an incompatibility down the line.
