### ISSUE TITLE
CI: add sanity checks before any test runs

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3958]
* Container creation
* DNS working

Add more below :)

**Comment by jrajahalme** [comment]
* endpoint IP/ID mappings are found from the bpf ip cache?

If not a CI sanity check, this is a basic Cilium invariant, failures of which show as (intermittent) test failures on test cases that depend on the mapping (label based egress policy rules). It would be nice to have this kind of check be done before running any end-to-end policy tests that may depend on the IP/ID mapping, as having a failure that directly indicates the problem would save time in triaging.

Reasons for this failing may include bugs in kv-store interactions, so a basic kv-store sanity check should be performed *before* this test.

**Comment by jrajahalme** [comment]
* basic kv-store connectivity test

**Comment by ianvernon** [comment]
Closing this, we have the PreflightChecks option, which has proven quite useful.
