### ISSUE TITLE
Fix LB WRR code to work with kernel 4.8.x

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#399]
Given we can't depend on the 4.9 LTS yet, we really need to fix this so it runs on 4.8. I'm sure we can fix the pseudo c code to llvm produces the instructions in the right order. In particular as we are limiting the llvm release to 3.8.x

**Comment by borkmann** [comment]
@mchalla You can test for `HAVE_MAP_VAL_ADJ` define.

**Comment by mchalla** [comment]
Thanks. I already sent out a pull request.

**Comment by mchalla** [comment]
https://github.com/cilium/cilium/pull/406
