### ISSUE TITLE
Represent cilium status as metrics

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3997]
The idea is to be able to monitor the health of Cilium via Prometheus metrics to get a cluster wide overview.

- [ ] Number of controller failing (`Controller Status:      7/7 healthy`)
- [ ] Number of addresses allocated (`IPv4 address pool:      3/65535 allocated`)
- [ ] Kubernetes Status (`Kubernetes:             Disabled`)
- [ ] Cluster health (`Cluster health:          1/1 reachable   (2018-05-01T13:36:49Z)`)
   - [ ] Number of nodes that cannot be reached
   - [ ] Number of health endpoints that cannot be reached
   - [ ] Average Latency to nodes, Maximum latency to nodes
   - [ ] Average Latency to health endpoints, Maximum latency to health endpoints
- [ ] Number of warnings/errors generated
   - [ ] Overall counter
   - [ ] Fine grained specific counters

**Comment by manalibhutiyani** [comment]
@tgraf : Is there an overlap here with the prometheus metrics work assigned to me? I can co-ordinate with Michal if that's the case
#3863
#3337 
#3284

**Comment by tgraf** [comment]
> @tgraf : Is there an overlap here with the prometheus metrics work assigned to me? I can co-ordinate with Michal if that's the case

There should be no direct overlap but both issues track the addition of Prometheus metrics. This issue tracks the addition of metrics to represent `cilium status` with corresponding metrics.

But yes, please co-ordindate with @mrostecki and also involve @raybejjani to ensure we use a uniform way of adding metrics.

**Comment by vadorovsky** [comment]
@manalibhutiyani I don't see overlap with metrics in different issues, so hopefully we will only have tiny merge conflicts in `pkg/metrics/metrics.go`.
