### ISSUE TITLE
Cannot configure IPv6 CIDR policy in k8s (CRV rejects it)

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4000]
We're currently rejecting valid IPv6 CIDR policies because of an over-restrictive CustomResourceValidator in kubernetes cases:

https://github.com/cilium/cilium/blob/e9b182cdf6dde5136e9534a2b03e4fd3bce806a4/pkg/k8s/apis/cilium.io/v2/register.go#L362-L380

Error:

```
validation failure list:
must validate one and only one schema (oneOf)
spec.egress.toCIDR in body should match '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/([0-9]|[1-2][0-9]|3[0-2])$'
```

/cc @cilium/kubernetes  Was there a particular reason we are avoiding this for now? I believe that the underlying support for this should work, was it just a matter of figuring out a reasonable IPv6 regex pattern?

Adding tags `priority/1.1` and `stable/needs-backport`, we can always remove them if the fix for this doesn't seem appropriate for backport.

Tasks:
* [x] Prepare change (#4004)
* [x] Test regex (included in #4004)
* [x] Test IPv6 CIDR behaviour manually
* [ ] Add Ginkgo test for IPv6 CIDR behaviour

**Comment by raybejjani** [comment]
aanm likely remembers better. I think we didn't support something IPv6 at the time. It's also possible the regex was buggy :/

**Comment by aanm** [comment]
>aanm likely remembers better. I think we didn't support something IPv6 at the time. It's also possible the regex was buggy :/

@raybejjani It's because there are no tests for IPv6 so I just prevented the users from using IPv6 addresses at all. We need to improve the IPv6 tests. cc @joestringer

**Comment by joestringer** [comment]
@aanm :+1: I manually tested on Friday. I can put together a ginkgo test based on how I tested it.

**Comment by aanm** [comment]
@joestringer I'm not referring to the CRD tests itself. I was referring to everything around IPv6, from LB to CIDR policy.

**Comment by joestringer** [comment]
@aanm I tested CIDR policies with IPv6, specifically by adding CIDR rules that do not match a CIDR of a known IP accessible within a Minikube environment and seeing that traffic is dropped, then changing the CIDR to match and saw that the IPv6 traffic passed through.

What are you thinking might be missing for LB? Configure a ClusterIP service and see that traffic successfully passes between something external to k8s into the cilium service, gets translated and traffic returns correctly?

**Comment by aanm** [comment]
>What are you thinking might be missing for LB? Configure a ClusterIP service and see that traffic successfully passes between something external to k8s into the cilium service, gets translated and traffic returns correctly?

@joestringer something like that yes, because we don't have e2e tests for IPv6 in kubernetes.
