### ISSUE TITLE
Integration with SPIFFE for identity

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4016]
Cilium already uses an identity based security enforcement model.

- [x] Research feasibility of using the SPIFFE spec for identity management and tagging
- [ ] Create compatibility matrix with different identity marking methods
- [ ] Implementation
- [ ] Documentation
- [ ] Guide

**Comment by evan2645** [comment]
Would love to see this go in, please let me know if I can be of any help.

**Comment by tgraf** [comment]
@evan2645 We would love to work with you guys to get this in. We already have an identity concept but do not use the spiffe spec yet.

The main question is this:
Unlike other projects, we encode the identity into every individual network packet. This has great advantages as the identity concept works for all IP based protocols and is completely transparent to the application. The downside of the model is the limited space available to encode an identity. We therefore rely on encryption underneath to secure a 24bit identity with additional metadata stored in a kvstore that can be referred to by the 24bit identity.

We also have a working model to store metadata in TCP options and will have several hundred bytes available. 

What are your thoughts on this?

**Comment by evan2645** [comment]
> Unlike other projects, we encode the identity into every individual network packet. This has great advantages as the identity concept works for all IP based protocols and is completely transparent to the application. The downside of the model is the limited space available to encode an identity. We therefore rely on encryption underneath to secure a 24bit identity with additional metadata stored in a kvstore that can be referred to by the 24bit identity.

Hmm that is interesting... I'd like to learn a little more about how exactly this information is stored and where... is there a diagram or detailed text somewhere that I could read up on?

> We also have a working model to store metadata in TCP options and will have several hundred bytes available.

Sounds better, but ultimately the constraint will be challenging I think. There is no length constraint on SPIFFE IDs, and truncating them seems like it could be dangerous. I am curious - with these kinds of space constraints, plus raw IP support (so presumably no inherent idea of a session), are there any cryptographic assertions that the specified identity is authentic? Or do we trust the wire?

**Comment by tgraf** [comment]
> Hmm that is interesting... I'd like to learn a little more about how exactly this information is stored and where... is there a diagram or detailed text somewhere that I could read up on?

It's a bit outdated but this is a good start:
http://docs.cilium.io/en/v1.1/concepts/#arch-id-security

To keep it simple, we derive metadata from the workload in form of labels and map it to a numeric integer (32 bits) via a kvstore. The user can define what portion of labels should be used to derive the identity. It's not bound to a numeric identity though, we basically map a unique set of labels to a binary blob that is transmitted in packets.

> Sounds better, but ultimately the constraint will be challenging I think. There is no length constraint on SPIFFE IDs, and truncating them seems like it could be dangerous. I am curious - with these kinds of space constraints, plus raw IP support (so presumably no inherent idea of a session), are there any cryptographic assertions that the specified identity is authentic? Or do we trust the wire?

We currently rely on node to node encryption being provided to trust the wire but would like to introduce the notion of cryptographic authentication.

**Comment by platten** [comment]
Any chance SPIFFE support would be included in the 1.7 release?

**Comment by tgraf** [comment]
@platten Yes, @jrfastab has been doing the necessary investigation. It's currently under consideration.

**Comment by evan2645** [comment]
@jrfastab please let me know if there's anything I can do to help. Happy to have a quick hangout or something to talk through it if that would be useful, just let me know!

**Comment by platten** [comment]
@tgraf @jrfastab Gentlemen, any news on the SPIFFE front?

**Comment by nyrahul** [comment]
@tgraf @jrfastab @evan2645 I am interested in doing this integration and have compiled some thoughts in the attached slides. Would be great to get some initial feedback and to understand if something basic is amiss. The primary point is the handling of Cilium's Identity value and mapping it to SPIFFE ID.

[SPIFFE Integration to Cilium.pdf](https://github.com/cilium/cilium/files/4918177/SPIFFE.Integration.to.Cilium.pdf)

**Comment by tgraf** [comment]
@nyrahul This looks awesome and is aligned with what we have discussed previously.

To address the questions mentioned in the slide "Cilium Identity Handling":

> Per-packet verification overhead:

This concept is intentional and not outdated. There is no practical overhead but a massive advantage: by validating each packet, changes to network policy are applied mid-connection. This is important for long-lived or persistent connections. Concepts that enforce a policy decision only on the establishment of a connection (mTLS, policy decision on SYN, ...) will continue to allow a connection even after policy changes no longer allow such a connection.

> Overloading of existing protocol headers:

This is not required. Several options are available and if header embedding is not desirable, then mapping from IP address via the IP cache is also an option. This concept is also not new but basically an evolution of previous usages of overlays or VLANs to achieve segmentation.

> Additional state information, More state -> more attack possibility:

Can you provide some more context on the additional attack possibilities? Even in a world of mTLS, it will still be required to inspect and enforce policy decisions on non-TLS traffic to f.e. limit egress abilities of a workload. For such enforcement, stateful enforcement is more secure. I don't see how any mTLS approach can help avoid the need for this.

> Why Cilium decided to use this notion?, Any background (?)

* The concept works for any protocol and does not depend on the ability to use TLS.
* It works for scenarios where Cilium controls both ends or only one side.
* It allows enforcing mid-connection, e.g. change policy decision or start blocking and already established but undesirable connection.
* IPSec or Wireguard based authentication and encryption can be applied on top with either a single PSK or service specific keys.
* It scales well (even across many clusters with localized identity allocation) and has almost no overhead to achieve segmentation.

Comments on implementation plans:
* Cilium has already gained the ability to program Envoy with certificates for particular connections of endpoints. It may be possible to re-use this work.
* While the goal to avoid embedding the security identity in network packets for end to end managed connection is the right one. It may not be achievable for all workloads. The ability to fall-back to the existing packet-based approach will provide the best of both worlds.
* By using the numeric SPIFFEE ID and enforcing it in the eBPF datapath as well, we would gain an interesting ability that mTLS alone doesn't provide. SPIRE and mTLS will ensure proper authentication of the initial connection and the eBPF datapath will drop packets mid-connection if the policy no longer allows it.

I hope this makes some sense. Definitely very excited to see progress on this.

**Comment by nyrahul** [comment]
There was a discussion with the Cilium tech community with regards to this integration.
Posting the documents used in the context:
1. [Comparison of Identity marking solutions](https://docs.google.com/document/d/19Zh0Y9NUuw0o0txfPKF67BTNKjlfzicMEBRteqlVPPc/edit?usp=sharing)
2. [Cilium-SPIRE integration points](https://docs.google.com/document/d/16YowSttiQVNA4vqRzW22tHyntZvJKdYslEy-tpK2d6w/edit?usp=sharing)

**Comment by mauriciovasquezbernal** [comment]
Hi folks, I'll start working on this one, please feel free to assign this issue to me.

**Comment by mauriciovasquezbernal** [comment]
I prepared a [design document](https://docs.google.com/document/d/1QB3JIomGmEqg34sCQCmn9A-RqrCwBJMQgj7hoFkwTE0/edit#) based on the previous ideas / discussions on this topic. Feel free to leave comments there if you have any. I'll be discussing it on next community meetings.

**Comment by margamanterola** [comment]
Mauricio stopped working on this after the acquisition by Microsoft. Removing the assignment. Thanks Mauricio for the work you did in getting this started!

**Comment by evan2645** [comment]
What's the latest on this integration?

**Comment by mattbates** [comment]
I'm also very interested to track this. This is the meta/epic issue I found that has just recently been updated by @youngnick.

https://github.com/cilium/cilium/issues/22215

It's great to see this kick off following the addition of mTLS datapath capability in 1.13.

**Comment by youngnick** [comment]
Yes, we're definitely still interested in some sort of solution here, but we're currently prioritizing getting the identity-handling bits working for the transparent, service-mesh use case. Keep an eye here or on #22215 for further updates.
