### ISSUE TITLE
CI: Request: Only provide artifacts for failed test

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4037]
Currently, when we generate the artifacts file for a failure, without browsing to the jenkins page for the failure, it's difficult to know which test failed. A common procedure we follow is to file an issue and attach the zip file of the failure result. In this case, sometimes people leave out the name of the test (or which of k8s 1.7 vs 1.10 failed), or sometimes leave out the link to the actual failure... or if looking into it later on, the jenkins link may become dead.

It would be useful if the artifacts from a failed zip only included the relevant failure directory.

**Comment by eloycoto** [comment]
Fixed by https://github.com/cilium/cilium/pull/4176
