### ISSUE TITLE
Make envoy upstream request timeout configurable

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#4058]
Right now envoy upstream request timeout is not configurable, and envoy returns 504 when upstream requests time out. This causes long running requests to fail when requests are forwarded to proxy.

**Comment by rlenglet** [comment]
Note that if the intent is to make Cilium's Envoy proxy work with gRPC streams, this is a known Envoy bug upstream: https://github.com/envoyproxy/envoy/issues/1778

**Comment by jrajahalme** [comment]
#4508 solved the underlying issue with gRPC timeouts; now the default timeout is infinite but gRPC clients can shorten this with the `grpc-timout` header.

Closing for now, please re-open if configurable max timeouts are needed.
