### ISSUE TITLE
Update all demo VMs images to ubuntu 18.04

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4064]
Since ubuntu 18.04 (LTS) was released we should update the demo VMs (and developer VMs) to ubuntu 18.04 so that we don't get 404 in the repositories for the current ubuntu release that we are using once it reached EOL

**Comment by joestringer** [comment]
Duplicate: https://github.com/cilium/cilium/issues/2688

**Comment by joestringer** [comment]
Note also this will affect branch v1.0 in a few months time.
