### ISSUE TITLE
Fix controller update to not generate new UUID on every update

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4066]
b6d894a4137ed493fdbd371e08198178628db67b has changed the logic to always generate a new UUID on every controller update. This is wrong and leaks controllers in the global status map.

**Comment by raybejjani** [comment]
I pushed a simple fix in #4067.
I'm not sure I understand why using a new uuid per controller update is wrong. It's the only way we have to indicate, in the logs, that the controller has been updated or changed. In the sense that you want to have the controller be in a single slot somewhere, why did we add the uuid to begin with? Couldn't we just use the names we give, and require them to be unique? Duplicate names would confuse us in logs and status outputs in any case. The UUID isn't useful unless you unpack it, and it can't be used to distinguish between instances of the same type of controller (you can't associate it to the endpoint or thing it manages).

**Comment by tgraf** [comment]
I'm fine to switch over to unique names
