### ISSUE TITLE
Incorrect link for Kubernetes iptables overview diagram on cilium concepts page.

### ISSUE THREAD

**Issue by ishantanu** [cilium/cilium#4125]
### Title

Incorrect image link for `kubernetes iptables` diagram on concepts page in cilium docs

### General Information

The image link in [kubernetes-integration](http://cilium.readthedocs.io/en/doc-1.0/concepts/#kubernetes-integration) on concepts page is incorrect.

Failing link - http://cilium.readthedocs.io/en/doc-1.0/concepts/_static/kubernetes_iptables.svg
Appropriate link - http://cilium.readthedocs.io/en/doc-1.0/_static/kubernetes_iptables.svg

### How to reproduce the issue
Click on `kubernetes iptables overview` link in [kubernetes-integration](http://cilium.readthedocs.io/en/doc-1.0/concepts/#kubernetes-integration) section.

**Comment by joestringer** [comment]
Hmm, I think that the image itself displays correctly, it's just the link for when you click on it.

**Comment by joestringer** [comment]
@iamShantanu101 thanks for the report, I think I managed to find the root cause and fix it. PR incoming.

**Comment by joestringer** [comment]
Links are still not working on readthedocs with the absolute paths patch.

Currently it's generating:

http://docs.cilium.io/_static/kubernetes_iptables.svg

Previously it was generating:

http://docs.cilium.io/en/latest/concepts/_static/kubernetes_iptables.svg

What we want is this:

http://docs.cilium.io/en/latest/_static/kubernetes_iptables.svg

However, if we use relative paths with `../_static/kubernetes_iptables.svg` then it breaks the link in docs locally.
