### ISSUE TITLE
CI: Add Kubernetes upstream test to run once a day. 

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#4132]
At the moment the Kubernetes Upstream only works on demand, and it does not run once a day. These test need to run once a day on the master branch.

**Comment by aanm** [comment]
I think they should be executed for a PR that contains `area/k8s`

**Comment by eloycoto** [comment]
@aanm already in there
https://github.com/cilium/cilium/blob/659aea26230134920fa519da2a603bc636a07a13/ginkgo.Jenkinsfile#L23

**Comment by eloycoto** [comment]
Already in there: 
https://jenkins.cilium.io/view/BETA-Cilium-master/job/BETA-cilium-master-K8s-Upstream/
