### ISSUE TITLE
Use code-block: shell-session for highlighting shell commands/output in docs

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4143]
In each documentation file, there are often shell-session examples in the form of:

```
::

    $ some-shell-command
    output lines
```

If we update each of the `::` to `.. code-block:: shell-session`, then it will improve the highlighting of the output to make it clearer which part is the command you need to highlight and which part is the output example of that command.

We might be able to convert these over with a simple sed script, something like `sed -i 's/^::$/^.. code-block:: shell-session/g' Documentation/*`. That said, we would still need to review each change in the docs to ensure that the output that is being changed is actually for a shell session.

To see all files that still have the `::` in the docs file, this command may be useful: `$ git grep -l "^::$" Documentation/`

**Comment by joestringer** [comment]
An alternative to updating each entry in the docs may be to figure out how `highlight_language` works and use this to default all of these `::` sphinx expressions to using the `shell-session` lexer for syntax highlighting.

**Comment by ishantanu** [comment]
@joestringer Just a question, why is it that at some places `::` is used for shell code and at other places `.. code:: bash`?

An alternative to doing a `sed` might be using `highlight_language = 'guess'`. It guesses the syntax highlighting language. 

Also, for C code snippets, syntax highlighting seems to be missing. `highlight_language = 'guess'` also does highlighting for this.

**Comment by joestringer** [comment]
@iamShantanu101 I believe that the `::` form is a lazy way to say something like "format this in a box as a text literal", without indicating the type of highlighting that is required - or even saying that it's not code, just some text. I suspect that if you want to add syntax highlighting, then the indent block needs to be at least something like `.. code::` or `.. code-block::`.

`.. code:: bash` seems to mostly be used in the Cilium docs for interactive shell sessions, although really those should be using something like `.. code:: shell-session` because they include commands and example output. This is a bit different from straight bash scripts, and the highlighter would treat this better. For instance, lines starting with `#` in shell sessions typically indicate a command being run as root; whereas in a bash script, the `#` indicates the beginning of a comment line. The syntax highlighting may take this into account and end up putting lower emphasis on the lines that appear to be comments, while putting more emphasis on lines that appear to be commands.

Maybe `guess` would be a reasonable approach. I think that this will just require someone to sit down and play with these options, use `make render-docs` to render them locally, and try different approaches until the output all looks nicely highlighted.

I agree, the C code syntax highlighting is missing too. I doubt that this is intentional, and if someone were to propose a patch to add that syntax highlighting to the relevant bits in the docs then I'm sure the PRs would be welcomed for that as well.

**Comment by ishantanu** [comment]
Got the point. I'll look into this.

**Comment by joestringer** [comment]
By the way, it looks like `.. code:: type` doesn't trigger the highlighting. It looks like it needs to be `.. code-block:: type`.

**Comment by joestringer** [comment]
A more recent suggestion in addition to this is to break out the commands vs. shell output, eg:

```
.. tabs::

   .. group-tab:: Commands       
                            
      ::                                   
                                     
         pip install -r Documentation/requirements.txt

   .. group-tab:: Shell Output                       
          
      .. code-block:: shell-session            
                
         $ pip install -r Documentation/requirements.txt
         Collecting alabaster==0.7.12 (from -r Documentation/requirements.txt (line 1))
           Downloading https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
         ...
         Successfully installed Babel-2.6.0 Jinja2-2.10 MarkupSafe-1.0 PyEnchant-2.0.0 PyYAML-4.2b1 Pygments-2.2.0 Sphinx-1.8.1 alabaster-0.7.12 certifi-2018.10.15 chardet-3.0.4 commonmark-0.5.4 docutils-0.14 functools32-3.2.3.post2 idna-2.7 imagesize-1.1.0 jsonschema-2.6.0 packaging-19.0 pyparsing-2.3.1 pytz-2018.7 #                                                                
```

![tabbed-shell](https://user-images.githubusercontent.com/1243336/52232149-9dc6a400-2870-11e9-953e-db4e3b1e272c.png)

Commands should appear in the left box by default, contrary to this example image.
