### ISSUE TITLE
nil pointer dereference in syncPolicyMapController

### ISSUE THREAD

**Issue by rlenglet** [cilium/cilium#4145]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10f4a0a]

goroutine 1004 [running]:
github.com/cilium/cilium/pkg/maps/policymap.(*PolicyMap).DumpToSlice(0x0, 0x12227bce0, 0x0, 0x3, 0x3, 0x3)
	/go/src/github.com/cilium/cilium/pkg/maps/policymap/policymap.go:208 +0xea
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).syncPolicyMap(0xc42152bb80, 0x1ed6500, 0xc42152bb84)
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2421 +0x61
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).syncPolicyMapController.func1(0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:2475 +0x84
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc4244dc820)
	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:185 +0x87
created by github.com/cilium/cilium/pkg/controller.(*Manager).UpdateController
	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:82 +0x30c
level=fatal msg="Agent pipe unexpectedly closed, shutting down"
```

**Comment by ianvernon** [comment]
I believe the following code got executed: 

https://github.com/cilium/cilium/blob/76f6f62da26f84d96cda7cad855374fe2e045a0c/pkg/endpoint/bpf.go#L584-L589

a build most likely failed for an endpoint, and the PolicyMap for it was set to nil. However, in `regeneratePolicy` we start a controller for syncing state to the PolicyMap for an endpoint which runs asynchronously:

https://github.com/cilium/cilium/blob/76f6f62da26f84d96cda7cad855374fe2e045a0c/pkg/endpoint/policy.go#L516-L518

This means that if a build failed, and another one was not re-triggered soon after, the PolicyMap will be nil:

https://github.com/cilium/cilium/blob/76f6f62da26f84d96cda7cad855374fe2e045a0c/pkg/endpoint/endpoint.go#L2384-L2390

We should do a nil check in that controller.
