### ISSUE TITLE
Support for Docker Swarm

### ISSUE THREAD

**Issue by sandys** [cilium/cilium#4159]
--------------

### Description of requested functionality
Cilium Project must support Docker Swarm which is the other popular (and more importantly built-in) orchestrator.
From what I understand from the Kubernetes+Cilium documentation, it will not be very hard to setup using Docker Swarm global mode (https://docs.docker.com/engine/swarm/services/#replicated-or-global-services)

Interesting issues here could be 
1. compatibility with Docker Swarm encrypted network mode
2. Docker Swarm comes with a built-in ingress. How do you replace that with Cilium Project ingress/routing.

**Comment by swift1911** [comment]
+1

**Comment by nea** [comment]
+1

**Comment by gurayyildirim** [comment]
+1

**Comment by sandys** [comment]
the problem here is that the plugin architecture is too old. Docker networks need the v2 plugin system. it would be great if cilium devs can look into this. This is not swarm specific - this is core docker.

https://docs.docker.com/engine/extend/

https://www.weave.works/docs/net/latest/install/plugin/plugin-v2/

**Comment by qLb** [comment]
+1

**Comment by zez3** [comment]
+1

**Comment by cblomart** [comment]
+1

**Comment by zez3** [comment]
Bummer

**Comment by zez3** [comment]
Aldough I know that docker enterprise now comes with included k8s and some security stuff included. What would be the CE version of those features?

**Comment by qLb** [comment]
+1

**Comment by zez3** [comment]
Too bad that Nobody has the resources to invest on this :(

**Comment by dazinator** [comment]
shame :-(
