### ISSUE TITLE
CI: SW Demo pods never become ready 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4162]
I've noticed this failing in multiple PRs which have no effect on actual compiled code (for Cilium or for the CI).

Build link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3298

Stacktrace:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:338
Alliance pods are not ready after timeout
Expected
    <*errors.errorString | 0xc4202e23f0>: {
        s: "Timeout reached: could not get Pods",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/demos.go:135
```

Logs: 
[test_results_Cilium-PR-Ginkgo-Tests-Validated_3298.zip](https://github.com/cilium/cilium/files/2014620/test_results_Cilium-PR-Ginkgo-Tests-Validated_3298.zip)

**Comment by ianvernon** [comment]
Seeing if I can reproduce locally.

**Comment by ianvernon** [comment]
Similar failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3300/

**Comment by raybejjani** [comment]
Skimming the test output for build 3300 I noticed:
`Error: cannot get endpoint list: context deadline exceeded`
on one of the two `cilium endpoint list` execs. All the app pods happened to be on node k8s2 so I'm guessing it was the same node... and that we have a deadlock or some other really slow endpoint generation :/

**Comment by ianvernon** [comment]
This might have been due to high memory consumption in the K8s tests which was caused by https://github.com/cilium/cilium/pull/4166 . I'm closing this as we haven't seen this failure since https://github.com/cilium/cilium/pull/4166 was merged.
