### ISSUE TITLE
Cilium policy import command does not specify the format of the expected policy file

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#4165]
### Title

Cilium policy import command does not specify the format of the expected policy file

### General Information

- Cilium version (run `cilium version`)
```
kubectl exec -it cilium-sq7xr -n kube-system -- cilium version
Client: 1.0.90 ac4b37c 2018-05-06T22:01:46+02:00 go version go1.9 linux/amd64
Daemon: 1.0.90 ac4b37c 2018-05-06T22:01:46+02:00 go version go1.9 linux/amd64
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
k8s

### How to reproduce the issue

1. Execute the following command:
```
kubectl exec -it cilium-sq7xr -n kube-system -- cilium policy import
Error: Missing path argument

Import security policy

Usage:
  cilium policy import <path> [flags]

Examples:
  cilium policy import ~/app.policy
  cilium policy import ./policies/app/

Flags:
  -o, --output string   json| jsonpath='{}'
      --print           Print policy after import

Global Flags:
      --config string   config file (default is $HOME/.cilium.yaml)
  -D, --debug           Enable debug messages
  -H, --host string     URI to server-side API
```

Do we expect the file to be in YAML format? Or JSON? Or are both the formats accepted?

**Comment by tgraf** [comment]
> Do we expect the file to be in YAML format? Or JSON? Or are both the formats accepted?

JSON for now. Needs to be properly documented.
