### ISSUE TITLE
Envoy proxy integration

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#418]
- [x] Add plugin to envoy to receive Cilium metadata from BPF maps
- [x] Potentially extend envoy API to be able to open up proxy ports on demand
- [x] Convert CiliumNetworkPolicy L7 rules to Envoy HTTP filters
- [x] Write guide on how to set it up

**Comment by josephjacks** [comment]
+1 for Envoy! :)

**Comment by tgraf** [comment]
Upstream envoy work is ongoing. Moving to 0.12.

**Comment by tgraf** [comment]
Preliminary container image with envoy support is available under `cilium/cilium:envoy`

**Comment by joestringer** [comment]
Is anything else needed on this?

**Comment by ianvernon** [comment]
@jrajahalme is anything else needed here?

**Comment by jrajahalme** [comment]
I'm still working on log integration, but it was never articulated here so IMO this can be closed.

**Comment by jrajahalme** [comment]
It's integrated so there are no Envoy-specific docs we need.
