### ISSUE TITLE
CI: RuntimeValidatedConnectivityTest test flake

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#4180]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3351/flowGraphTable/

15:27:57 Running Suite: runtime
15:27:57 ======================
15:27:57 Random Seed: 1526657219
15:27:57 Will run 58 of 285 specs
15:27:57 
15:27:57 RuntimeValidatedConnectivityTest Basic Connectivity test 
15:27:57   Test connectivity between containers without policies imported
15:27:57   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:338
15:30:36 
15:30:36 • Failure in Spec Setup (BeforeEach) [153.726 seconds]
15:30:36 RuntimeValidatedConnectivityTest [BeforeEach]
15:30:36 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:306
15:30:36   Basic Connectivity test
15:30:36   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:306
15:30:36     Test connectivity between containers without policies imported
15:30:36     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:338
15:30:36 
15:30:36     error starting VM "runtime": exit status 1
15:30:36

**Comment by joestringer** [comment]
@manalibhutiyani Please download the test artifacts and iinvestigate the `test-output.log` before filing an issue. In this case it appears to be related to the PR.

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3351/
->
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3351/artifact/test_results_Cilium-PR-Ginkgo-Tests-Validated_3351.zip
->
```
    runtime: go build -i -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.0.90 c32c22508 2018-05-18T15:12:10+00:00 go version go1.9.3 linux/amd64"' -tags lockdebug -o cilium
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
    runtime: ../contrib/scripts/bindata.sh 3c9f4d50ad45a35882330320a47b74240bc1471b
    runtime: bindata.go: FAILED
    runtime: sha1sum: WARNING: 1 computed checksum did NOT match
    runtime: ########################################################################
    runtime:                   ERROR: bindata.go is out of date.
    runtime: 
    runtime:  This can happen for two reasons:
    runtime:  1. You are using a go-bindata binary compiled with a different version
    runtime:     of golang (not 1.9). If so, please up/downgrade.
    runtime:  2. You have made changes to the bpf/ directory. Please run the
    runtime:     following command to update the SHA in daemon/bpf.sha:
    runtime: 
    runtime:     $ make -C daemon apply-bindata
    runtime: ########################################################################
    runtime: Makefile:46: recipe for target 'check-bindata' failed
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
    runtime: Makefile:25: recipe for target 'daemon' failed
    runtime: make[1]: *** [check-bindata] Error 1
    runtime: make: *** [daemon] Error 2
```

The reason this is not more obvious is #4170, which should be fixed soon.

Closing, not a CI issue.
