### ISSUE TITLE
Upgrade guide for older branches doesn't point to latest point release

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4183]
This upgrade guide:
http://cilium.readthedocs.io/en/doc-1.0/install/upgrade/

This tells people to fetch the DS from here:

https://raw.githubusercontent.com/cilium/cilium/doc-1.0/examples/kubernetes/1.9/cilium-ds.yaml

This contains cilium tag version `1.0.0`, even though `1.0.3` has been released.

I suspect that this is because it's pointing to branch `doc-1.0` rather than `v1.0`. When we switch this over properly, it should be resolved.

**Comment by aanm** [comment]
@joestringer `doc-1.0` should be changed to `v1.0` entirely.

But still `doc-1.0` spec files should have `1.0.3`

**Comment by joestringer** [comment]
If we can set up a redirect from `doc-1.0` to `v1.0` then it should be resolved, it looks like `v1.0` branch contains the correct tag. We aren't yet generating `v1.0` tagged docs on readthedocs though.
