### ISSUE TITLE
Split cilium log out from test-output.log

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4189]
In local testing, I found that spinning up a simple test that runs Cilium, then `Expect(true).To(BeFalse())`, the `test-output.log` contained 4500 lines of cilium logs, and 200 lines of actual test output.

It would be great to split the cilium logs out and put them in a separate file so that the `test-output.log` can reflect exactly what's going on in the test. This can be cross-referenced against the logs separately.

**Comment by eloycoto** [comment]
I'm open to this, but for me this is a feature. That cilium logs are the logs that happens during the test, and have all in the same file help me a lot to do a simple search instead of looking for a bunch of files.

I think @ianvernon want to have this one in another file too, so as you prefer.

**Comment by joestringer** [comment]
I think one of the main problems I have with this approach is that I can't easily find the actual end of the test output. IMO this would be the best approach to solve this problem.

That said, if we covers the various use cases better, then why not both? We can have one file with test-output, one with the logs, and one with both. Something like `test-output-only.log`, `test-output-agent.log`, `test-output-all.log`.

**Comment by eloycoto** [comment]
What about if we add something like: 
```
--------BeforeEach-------------
--------Test Started------------
........
.......
-----------Test Finished------------
........
.......
-----------JustAfterEach-----------
........
.......
-----------AfterFailed-----------
........
........
-----------AfterEach-----------
........
.......
```

You will have the same problem, because the test will fail, but the output of AfterEach will be in there. Does this works for you? 

PS: Maybe we can found a way that vim can detect and fold it.

**Comment by joestringer** [comment]
> What about if we add something like:
> ...

This proposal above improves the ability to find where the error occurs, so that could work for the case where I just want to find the end of the test output. That would be a positive step forward.

More generally though, I think that we often hit this general question of the library vs. the catalog. Some people just find it easier to browse through a list of files (like books in a library), picking which information they think looks relevant or interesting based on the filename, while others find it easier to remember the names of things they are looking for and search within a single file (like a catalog). I've had similar discussions with others regarding the `cilium debuginfo` output that's used in bugtool, which also aggregates a bunch of information in a single file.

Personally I often don't know the names of what I'm looking for, so the ability to "browse" the files is easier for me. I like the ability to see an overview of the information available, pick file by name and glance through, decide whether the contents are relevant, then move on to the next file. If I don't think that some files are relevant, then I will often just skip them. Also, when I look in a file called `test-output.log`, I expect it to be the output of the test, not some other state from Cilium or somewhere else.

It seems to me like it's easier to have everything split out in separate files, then run `cat * >> all_output.txt` or `for f in *; do echo "### $f" >> all_output.txt; cat "$f" >> all_output.txt; done` to look at all the output at once, rather than to start with a giant file and try to split it out into separate files for the browsing use case.
