### ISSUE TITLE
Use pointer receivers in ipcache map key functions

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4192]
https://github.com/cilium/cilium/blob/ae39ed96f2821e30a2a6670ac1f2e5d838b73f52/pkg/maps/ipcache/ipcache.go#L59

These should use pointers in the receivers, not copies of the struct.

/cc @jrajahalme do you remember the implications of this kind of change? Do you think it will be necessary to backport such a fix?

**Comment by jrajahalme** [comment]
@joestringer Symptoms depend on the use. For the bpf maps the symptom was that lookups never worked, but then we never did any lookups until I needed to add some.

**Comment by jrajahalme** [comment]
It it likely that these are implemented just because an interface requires them and they are actually not used?
