### ISSUE TITLE
Endpoints not always regenerated when daemon config or bpf datapath sources change.

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#4215]
- [x] Cilium agent misses a trigger for endpoint bpf program regeneration if node config changes in a way that may affect the endpoint programs, except for the policy enforcement mode, for which a special case exists. However, node configuration may change in other ways, either at runtime, or across restarts, e.g.:

- IPv4 enabled or not
- Gateway addresses
- Cluster ranges
- Bpf Map sizes
- cilium_host/cilium_net MAC addresses, ifindex

It seems changes to most of these would also be reflected in endpoint's `lxc_config.h` but likely not all of them are thusly reflected.
    - Fixed-by: #4239

- [x] Endpoint policy recomputation may return with "no changes needed" even if the recomputation is triggered after such daemon config changes and/or restart, must make sure forced regeneration actually works as intended.
    - Fixed by: #4239 

- [x] Endpoint bpf regeneration is currently skipped if the endpoint's `lxc_config.h`remains the same. However, the endpoint programs also include the `node_config.h`, which should be included in the hash/change detection logic. Finally, the endpoint bpf sources themselves may change over a restart (say, a point upgrade), so maybe the `bpf.sha` file should also be included in the hash/change detection logic.
    - Fixed by: #4240 

- [x] Add test which confirms that endpoint regeneration occurs correctly after daemon configuration update ( https://github.com/cilium/cilium/issues/4198#issuecomment-391094191 )

**Comment by ianvernon** [comment]
@jrajahalme all fixes have been merged. I will create a Ginkgo test which tests the reproducer that you referenced here: https://github.com/cilium/cilium/issues/4198#issuecomment-391094191 . Before I sent out the referenced PRs, I validated that the manual test you created worked.

**Comment by ianvernon** [comment]
Reducing priority since the required changes are merged; all that is left is the integration test, which is out for review in #4291 .
