### ISSUE TITLE
Add locking when accessing metrics map from user space

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#4257]
Currently we are iterating the metrics map in user space using `updatePrometheusMetrics`
If the map is being dumped without the Dump and DumpWithCallback functions, we should RLock the map which is done in pkg/bpf/map/DumpWithCallback to ensure that it is not modified from userspace while accessing it. Currently since we are only reading from user space, this is not an issue, but that might change in future.

See https://github.com/cilium/cilium/pull/4225 for reference

**Comment by joestringer** [comment]
Might as well just switch to using one of the regular Dump functions instead.
