### ISSUE TITLE
examples/kubernetes config has broken v6 when cluster is v4 with dual-stack nodes

### ISSUE THREAD

**Issue by mx-shift** [cilium/cilium#4261]
### General Information

- Cilium version (run `cilium version`)

Client: 1.0.3 a2ebe00a5 2018-05-16T19:13:52+00:00 go version go1.9 linux/amd64
Daemon: 1.0.3 a2ebe00a5 2018-05-16T19:13:52+00:00 go version go1.9 linux/amd64

- Kernel version (run `uname -a`)

Linux alpha 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)

https://github.com/cilium/cilium/tree/master/examples/kubernetes/1.10

- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

[cilium-sysdump-20180527-140139.zip](https://github.com/cilium/cilium/files/2043008/cilium-sysdump-20180527-140139.zip)

### How to reproduce the issue

1. Setup dual-stack network
2. Install Ubuntu 18.04 on nodes. Ensure nodes obtain both v4 and v6 addresses.
3. Use kubeadm to install Kubernetes on nodes using v4 addresses
4. Deploy Cilium to the cluster using the YAML from https://github.com/cilium/cilium/tree/master/examples/kubernetes/1.10
5. Verify that pods receive both v4 and v6 pod addresses. v4 comes from cluster pod CIDR. v6 comes from Cilium default (f00d:0:0:0:<ipv4-address>::/9).
6. Verify pod-to-pod v6 works
7. Verify pod-to-external v6 is broken (f00d is in reserved address space and isn't NAT'd to node's public v6 address)

### Expected behavior

One of:
* Seeing cluster is using v4, disable v6 for pods
* Require operator to specify per-node io.cilium.network.ipv6-pod-cidr annotations before allocation v6 addresses to pods
* Refuse to start until operator provides v6 cluster range

**Comment by tgraf** [comment]
Attempted to change the default IPv6 CIDR (#4298) to the private IPv6 CIDR range `fd00::/8`. We can't change it without breaking upgrades while guaranteeing endpoint restores.
