### ISSUE TITLE
1.2 Release Process

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4289]
# Cilium 1.2 planning

* Release Committments: https://github.com/cilium/cilium/projects/9
 
## Release Dates
* Feature Freeze: 2018-07-06
* 1.2.0-rc1: 2018-07-30
* 1.2.0-rc2: 2018-08-03
* 1.2.0-rc3: 2018-08-13
* 1.2.0: 2018-08-15

## Release Checklist
- [x] Planning
- [x] Development Phase
- [x] Feature Freeze
- [x] Feature Exception Freeze
- [x] Testing & Addressing bugs
- [x] Final Release
- [x] Upgrade & downgrade instructions
- [x] Tag Release
- [ ] Release Blog
- [ ] Announcement

**Comment by manalibhutiyani** [comment]
1.2 additional metrics feature work assigned to me is complete and merged today.

**Comment by vadorovsky** [comment]
>1.2 additional metrics feature work is complete and merged today.

Mine (latency metrics from `cilium-health`) are not done yet and they need to be moved to 1.3. Feel free to remove my nick from this issue.
