### ISSUE TITLE
Make BPF asm output dependant on DEBUG option

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#429]
We currently invoke clang twice, once to generate ASM output, once for the actual bytecode. Limit ASM generation to debug mode to speed up build. See `bpf/join_ep.sh`.

```
clang $CLANG_OPTS -c $LIB/bpf_lxc.c -S -o $DIR/bpf_lxc.asm
clang $CLANG_OPTS -c $LIB/bpf_lxc.c -o $DIR/bpf_lxc.o
```

Another option is to generate the ASM and bytecode at the same time if it doesn't result in longer build times.

**Comment by ianvernon** [comment]
Merged by PR #599
