### ISSUE TITLE
Stabilize master CI builds

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4292]
## Who
@cilium/team 

## Goal
Get the CI master build success rate to >=95%

## Issues that need to fixed before the release: 
- [x] https://github.com/cilium/cilium/issues/3621 
- [x] https://github.com/cilium/cilium/issues/3993#issuecomment-394645783

## List of master build failures:

(Mark as done when *NOT* a regression)

- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/936/ (@aanm) [#4229]
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/934/ (@nebril)
      - PodCIDR issue, already fixed by @eloycoto
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/931/ (@tgraf) [#4300]
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/929/ (@tgraf) [#4300]
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/928 (@eloycoto) [#4304]
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/925/ (@aanm)
    - This is the PodCIDR issue. Fixed by @eloycoto
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/920/ (@raybejjani) [#3878]
    - One failing [test](https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/920/testReport/junit/k8s-1/7/K8sValidatedPolicyTest_KubernetesNetworkPolicy_between_server_and_client_should_enforce_policy_based_on_NamespaceSelector/) is fixed on #4304 (@eloycoto)
- [x] https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/2617/ (@raybejjani)
  - https://github.com/cilium/cilium/issues/3621
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/917/
  - @ianvernon did initial triage (https://github.com/cilium/cilium/issues/4275)
  -  Should be fixed by https://github.com/cilium/cilium/pull/4315 @eloycoto
- [ ]  https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/973/
   - Dupe of #4384
- [ ] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/972/ 
   - Tracked by #4329 
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/970/ 
   - Tracked by #4393
- [ ] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/974/ 
   - Upgrade test failing. Tracked by #4329
- [ ] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1004/
  - [ ] k8s-1.7.K8sValidatedKafkaPolicyTest KafkaPolicies
     - #4431
  - [x] k8s-1.7.K8sValidatedPolicyTest Basic Test Denies traffic with cnp default-deny egress policy
    - #4438
- [ ] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1005/
  - [x] k8s-1.7.K8sValidatedPolicyTest GuestBook Examples checks policy example
    - DNS not ready (#3878)
  - [x] k8s-1.7.K8sValidatedPolicyTest Basic Test Denies traffic with cnp default-deny egress policy
    - #4438
  - [ ] k8s-1.7.K8sValidatedKafkaPolicyTest KafkaPolicies
     - #4431
 - [ ] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1007/
   - [ ] k8s-1.10.K8sValidatedPolicyTestAcrossNamespaces Policies Across Namespaces
   - [ ] k8s-1.10.K8sValidatedUpdates Updating Cilium stable to master
- [x] https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1009/
   - All tests: runtime: install: cannot stat 'cilium-docker': No such file or directory (#4440)

## Nightly builds:
- [x] All are failing: https://jenkins.cilium.io/job/Cilium-Master-Nightly-Tests-All/ (Fixed on #4123)

## Process
1. Pick a failing build, add your name to the brackets at the end to assign it to you
2. Add a comment below with your triage report
3. If a bug, open a GH issue and start resolving it.

**Comment by raybejjani** [comment]
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/920/console  is due to a mystery kube-dns "failure" it doesn't ever return IPs for the redis-master service.

**Comment by raybejjani** [comment]
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/2617/ is a case where an endpoint is reported not-ready and stays there. We had a fix for some of this earlier, this latest instance seems to be that the endpoint was deleted (the errors say things like not found etc. but it started with an invalid element).

**Comment by ianvernon** [comment]
The fixes for #3621 and #3993 have been merged. There are other CI failures which are marked with priority/1.1. Is this ticket needed for anything else? We can tackle each ticket that marks a test failure that needs investigation as priority/1.1 which will inherently mark it as a release blocker; thus, I think we can close this in favor of that model.

**Comment by tgraf** [comment]
> Is this ticket needed for anything else?

This ticket is to coordinate who is triaging which master failure and to serve as a summary. We need to have an overview of what failure is real or a flake so we can make a call when to release. We seem to open issues for both flakes and real ones so it's difficult to have an overview of what is failing for real.

**Comment by manalibhutiyani** [comment]
@eloycoto @ianvernon https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/973/execution/node/70/log/?consoleFull
Seems to have the same failure as https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/917/  #4275 #4315 
This is a regression since the fix was already merged in master 5 days ago, but the failure is from today i.e 6th June.

**Comment by manalibhutiyani** [comment]
Triaged/Filed GH issues for master CI failure:
 1. https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/973/
     - Dupe of #4384
 2.  https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/972/
     - Tracked by #4329
 3.  https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/970/
     - Tracked by #4393
 4. https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/974/
     - Upgrade test failing. Tracked by #4329

**Comment by eloycoto** [comment]
@manalibhutiyani 
- 973 is a dupe of https://github.com/cilium/cilium/issues/4384 
- 972 was tracked on https://github.com/cilium/cilium/issues/4329
- 970 is already fixed: https://cilium.slack.com/archives/C2B917YHE/p1528276188000067

**Comment by manalibhutiyani** [comment]
Updated new master failure : K8sValidatedKafkaPolicyTest KafkaPolicies #4431

**Comment by tgraf** [comment]
- https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1007/
   - k8s-1.10.K8sValidatedPolicyTestAcrossNamespaces Policies Across Namespaces
   - k8s-1.10.K8sValidatedUpdates Updating Cilium stable to master

These seems to be the failures that we still want to look into. We have not seen them recently though.

**Comment by tgraf** [comment]
Handled by #4459
