### ISSUE TITLE
Document / resolve host => world identity change for NodePort

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4297]
The commit #3988 has introducing a behavioral change because Cilium can now properly differentiate between host and world for traffic that is coming in via NodePort even if the traffic is being SNATed. There are two scenarios where host to endpoint is allowed:

- Manual policy that allows from host
- Kubernetes mode where host to pod is always allowed

In either of the above scenarios, traffic via NodePort was automatically allowed if the traffic was SNATed Cilium 1.1 as-is would no longer allow such traffic. This is a API breakage.

**Proposal:**
- [x] Introduce flag `--k8s-legacy-host-allows-world[=true]` which defaults to `true`.
  - [x] The flag is only effective in Kubernetes mode and continues to allow world when host is allowed.
- [x] Add the flag to the DaemonSet file and set it via an env variable that is defined in the ConfigMap.
- [x] In the ConfigMap, disable the flag by default. This leads to the following backwards compatible behavior:
   - Existing users will not upgrade the ConfigMap and thus will continue to see the existing behavior.
   - New users will see the new behavior where host and world are properly separate for NodePort.
- [x] Update the ginkgo upgrade tests to install stable Cilium without the new parameter
- [x] Document this in the upgrade instructions and make sure existing users that upgrade know how to opt into the new behavior.

**Comment by joestringer** [comment]
Extra side-effect: Adding a new flag to the `DaemonSet` means we need to change the existing upgrade tests. If we use the new example DS YAMLs to install stable, then stable won't understand the new `--k8s-legacy-host-allows-world` parameter and will fail immediately.
