### ISSUE TITLE
Chaos testing in nightly tests

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4302]
- [ ] Randomly delete an app pod and ensure that it comes back up and regains connectivity via endpoint restore
- [ ] Randomly restart cilium-agent and ensure it does not disrupt L3/L4 connectivity
- [ ] Policy enforcer probe pod which attempts to reach destinations which are prohibited by policy, report on unexpected success (negative case to existing policy tests in nightly)

**Comment by eloycoto** [comment]
@tgraf about `Randomly restart cilium-agent and ensure it does not disrupt L3/L4 connectivity` is this one no? 

https://github.com/cilium/cilium/blob/fce115e3875eeb023c941530407de5cd8134ef72/test/k8sT/Chaos.go#L100-L143
