### ISSUE TITLE
Re-allocate IPs of restored endpoints before allocating IPs for loopback / cilium_host

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4317]
It has been observed that the allocated loopback address is conflicting with an old endpoint IP that is required to be restored. This caused the endpoint to not be restored.

IPs to allocate after endpoint restore:
- loopback
- health endpoint (already done)

**Comment by aanm** [comment]
Don't you mean "Re-allocate IPs of restored endpoints **after** allocating IPs for loopback / cilium_host?"

cilium_host / loopback should take precedence otherwise an endpoint can be assigned with the cilium_host IP

**Comment by tgraf** [comment]
The loopback IP can be different on each run:
```
        if !option.Config.IPv4Disabled {
                // Allocate IPv4 service loopback IP
                loopbackIPv4, _, err := ipam.AllocateNext("ipv4")
```

**Comment by joestringer** [comment]
Can we read the `cilium_host` device IPs on startup and attempt to reuse that IP as an upgrade path?

**Comment by aanm** [comment]
@joestringer we are already doing that for the cilium_host v4 and and the v6 router. I just thought the lookbackIPv4 was not necessary
