### ISSUE TITLE
BPF_MAP_TYPE_PERCPU_HASH not handled and gives Property mismatch error.

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#4321]
We get `Property mismatch in /sys/fs/bpf/tc/globals/cilium_metrics` error 

I changed the cilium_metrics code from `BPF_MAP_TYPE_HASH ` to `BPF_MAP_TYPE_PERCPU_HASH`
We need to handle this special case where BPF definition is different from user space definition for `BPF_MAP_TYPE_PERCPU_HASH`
This is because the BPF definition does not account for all the values across all the CPUs.
But in user space we need to account for this? 

The BPF changes were very trivial:
```

diff --git a/bpf/lib/maps.h b/bpf/lib/maps.h
index e399054fa..c3107ba78 100644
--- a/bpf/lib/maps.h
+++ b/bpf/lib/maps.h
@@ -35,7 +35,7 @@ struct bpf_elf_map __section_maps cilium_lxc = {
 // Change this to BPF_MAP_TYPE_PERCPU_HASH for better
 // performance. GH #4196
 struct bpf_elf_map __section_maps cilium_metrics = {
-       .type           = BPF_MAP_TYPE_HASH,
+       .type           = BPF_MAP_TYPE_PERCPU_HASH,
        .size_key       = sizeof(struct metrics_key),
        .size_value     = sizeof(struct metrics_value),
        .pinning        = PIN_GLOBAL_NS,
diff --git a/bpf/lib/metrics.h b/bpf/lib/metrics.h
index 1b0a6b88f..3e56c1908 100644
--- a/bpf/lib/metrics.h
+++ b/bpf/lib/metrics.h
@@ -50,8 +50,8 @@ static inline void update_metrics(__u32 bytes, __u8 direction, __u8 reason)
 
 
     if ((entry = map_lookup_elem(&cilium_metrics, &key))) {
-            __sync_fetch_and_add(&entry->count, 1);
-            __sync_fetch_and_add(&entry->bytes, (__u64)bytes);
+            entry->count += 1;
+            entry->bytes += (__u64)bytes;
     } else {
             newEntry.count = 1;
             newEntry.bytes = (__u64)bytes;
diff --git a/daemon/bpf.sha b/daemon/bpf.sha
index 0c7c23bea..03fea4c03 100644
--- a/daemon/bpf.sha
+++ b/daemon/bpf.sha
@@ -1,2 +1,2 @@
-GO_BINDATA_SHA1SUM=ba0beb6e75d38323e4ba6f90a2febf5b1239671a
+GO_BINDATA_SHA1SUM=9e443795b02cada9f400dc46c19742bf10266415
```

However, the golang side needs to now change from `Value` size to `Value Size * num_possible_CPUs`
```
func init() {
	calculate_num_cpus()
	// Metrics is a mapping of all packet drops and forwards associated with
	// the node on ingress/egress direction
	Metrics = bpf.NewMap(
		MapName,
		bpf.BPF_MAP_TYPE_PERCPU_HASH,
		int(unsafe.Sizeof(Key{})),
		int(unsafe.Sizeof(Value{}))*possible_cpus, >>>> Changed!
		MaxEntries,
		0,
		func(key []byte, value []byte) (bpf.MapKey, bpf.MapValue, error) {
			k, v := Key{}, Value{}

			if err := bpf.ConvertKeyValue(key, value, &k, &v); err != nil {
				return nil, nil, err
			}
			return &k, &v, nil
		})

	err := bpf.OpenAfterMount(Metrics)
	if err != nil {
		log.WithError(err).Error("unable to open metrics map")
	}
}
```

This gives the error : `Property mismatch in /sys/fs/bpf/tc/globals/cilium_metrics` because we don't handle the special case of `BPF_MAP_TYPE_PERCPU_HASH` of having different sized values in userspace and BPF land.

Related to: #4196 
@joestringer @borkmann @jrfastab

**Comment by manalibhutiyani** [comment]
Please let me know where this needs to change? My understanding is in the upgrade function i.e `bpf_handle_pending` we need to handle the special case for `BPF_MAP_TYPE_PERCPU_HASH`?

**Comment by joestringer** [comment]
My guess is that the value size for the map should still be `Sizeof(Value{})`, but then in the dump you can use an array of values which is sized based on the number of possible CPUs. As far as I know, the bpf call to fetch the values from the kernel should populate multiple elements in the array, then you should be able to iterate them in the dump function and aggregate them.
