### ISSUE TITLE
Validate documentation with 1.1.0

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4326]
Validate documentation  with 1.1.0, includes running the getting started guides and verify if some concepts no longer make sense with 1.1.

**Very important**: Be a user, not a developer. If something is not clear enough, please change it.

- [ ] Getting Started Guides
  - [x] [Getting Started Using Minikube](http://cilium.readthedocs.io/en/latest/gettingstarted/minikube/) @eloycoto (PR https://github.com/cilium/cilium/pull/4550)
  - [x] [Getting Started Using Istio](http://cilium.readthedocs.io/en/latest/gettingstarted/istio/) @manalibhutiyani
  - [ ] [Getting Started Securing Kafka](http://cilium.readthedocs.io/en/latest/gettingstarted/kafka/) @borkmann
  - [x] [Getting Started Securing gRPC](http://cilium.readthedocs.io/en/latest/gettingstarted/grpc/) @raybejjani 
  - [x] [Getting Started Securing Elasticsearch](http://cilium.readthedocs.io/en/latest/gettingstarted/elasticsearch/) @jrfastab
  - [x] [Getting Started Using Mesos/Marathon](http://cilium.readthedocs.io/en/latest/gettingstarted/mesos/) @aanm (PR https://github.com/cilium/cilium/pull/4558)
  - [ ] [Getting Started Using Docker Compose](http://cilium.readthedocs.io/en/latest/gettingstarted/docker/) @ackerman80

- [ ] Network Policy
  - [x] [Policy Enforcement Modes](http://cilium.readthedocs.io/en/latest/policy/intro/) @techcet
  - [x] [Rule Basics](http://cilium.readthedocs.io/en/latest/policy/intro/#rule-basics) @raybejjani (https://github.com/cilium/cilium/pull/4554)
  - [x] [Layer 3 Examples](http://cilium.readthedocs.io/en/latest/policy/language/#layer-3-examples) @nebril
  - [x] [Layer 4 Examples](http://cilium.readthedocs.io/en/latest/policy/language/#layer-4-examples) @aanm
  - [x] [Layer 7 Examples](http://cilium.readthedocs.io/en/latest/policy/language/#layer-7-examples) @techcet
  - [x] [Endpoint Lifecycle](http://cilium.readthedocs.io/en/latest/policy/lifecycle/) @nebril
  - [x] [Troubleshooting](http://cilium.readthedocs.io/en/latest/policy/troubleshooting/) @nebril

- [x] [System Requirements](http://cilium.readthedocs.io/en/latest/install/system_requirements/) @eloycoto (PR https://github.com/cilium/cilium/pull/4550)

- [ ] Installation Guides
  - [ ] [Kubernetes Installation Guide (Generic)](http://cilium.readthedocs.io/en/latest/install/guides/kubernetes/) @techcet
  - [x] [CoreOS Installation Guide](http://cilium.readthedocs.io/en/latest/install/guides/coreos/) @jrajahalme
  - [ ] [Installation From Source](http://cilium.readthedocs.io/en/latest/install/guides/from_source/) @nebril (#4630)
  - [x] [Advanced Options](http://cilium.readthedocs.io/en/latest/install/guides/advanced_options/) @manalibhutiyani
  - [x] [Kubernetes Kops Installation Guide](http://cilium.readthedocs.io/en/latest/install/guides/kops/) @ianvernon
  - [x] [Upgrade Guide](http://cilium.readthedocs.io/en/latest/install/upgrade/) @ianvernon

- [x] [Monitoring & Metrics](http://cilium.readthedocs.io/en/latest/configuration/metrics/) @eloycoto 

- [x] Troubleshooting
  - [x] [Overall Health](http://cilium.readthedocs.io/en/latest/troubleshooting/#overall-health) @jrajahalme
  - [x] [Connectivity Issues](http://cilium.readthedocs.io/en/latest/troubleshooting/#connectivity-issues) @jrajahalme
  - [x] [Cluster Diagnosis Tool](http://cilium.readthedocs.io/en/latest/troubleshooting/#cluster-diagnosis-tool) @jrajahalme
  - [x] [Cluster connectivity check](http://cilium.readthedocs.io/en/latest/troubleshooting/#cluster-connectivity-check) @jrajahalme
  - [x] [Kubernetes](http://cilium.readthedocs.io/en/latest/troubleshooting/#id1) @jrajahalme
  - [x] [Monitoring Packet Drops](http://cilium.readthedocs.io/en/latest/troubleshooting/#monitoring-packet-drops) @ackerman80 
  - [x] [Policy Tracing](http://cilium.readthedocs.io/en/latest/troubleshooting/#policy-tracing) @ackerman80 
  - [x] [Debugging the datapath](http://cilium.readthedocs.io/en/latest/troubleshooting/#debugging-the-datapath) @ackerman80 
  - [x] [Debugging information](http://cilium.readthedocs.io/en/latest/troubleshooting/#debugging-information) @ackerman80 
  - [x] [Single Node Bugtool](http://cilium.readthedocs.io/en/latest/troubleshooting/#single-node-bugtool) @ackerman80

**Comment by manalibhutiyani** [comment]
Tested Istio GSG:
Raised https://github.com/cilium/cilium/issues/4564 @rlenglet is putting a fix out soon.

**Comment by jrajahalme** [comment]
Started on [CoreOS Installation Guide](http://cilium.readthedocs.io/en/latest/install/guides/coreos/), but domain registration (needed to follow the instructions) may take upto 3 days.

**Comment by jrajahalme** [comment]
Items under Troubleshooting do not math the document. AFAIK, these refer to the same text:
- [Overall Health](http://cilium.readthedocs.io/en/latest/troubleshooting/#component-cluster-health) & [Kubernetes](http://cilium.readthedocs.io/en/latest/troubleshooting/#kubernetes), and
- [Connectivity Issues](http://cilium.readthedocs.io/en/latest/troubleshooting/#connectivity-problems) & [Cluster connectivity check](http://cilium.readthedocs.io/en/latest/troubleshooting/#checking-cluster-connectivity-health)

**Comment by ackerman80** [comment]
fixed few documentation issues: https://github.com/cilium/cilium/pull/4563

**Comment by jrajahalme** [comment]
`cluster-diagnosis` tool installed with `curl -sLO releases.cilium.io/tools/cluster-diagnosis.zip` tries to access `etcd-cilium-0` as a cilium pod and fails.

**Comment by jrajahalme** [comment]
Minor troubleshooting updates: #4569

**Comment by jrajahalme** [comment]
@tgraf CoreOS guide links to https://coreos.com/kubernetes/docs/latest/getting-started.html, but this redirects to https://coreos.com/tectonic/docs/latest/tutorials/kubernetes/getting-started.html. I have followed through the Tectonic installation guides and am almost there, but I don't know if the rest of our guide applies to k8s installed with Tectonic.

**Comment by ianvernon** [comment]
@jrajahalme oof, not sure how helpful that will be, then. If you get stuck, please let me know as I wrote the original guide! I wanted to reduce the amount of hardcoded stuff listed outside the Cilium repo, but looks like that may bite us. IMO, since we can deploy via kops now, maybe we can get rid of that guide? It's pretty nitty-gritty at this point. @tgraf what do you think?

**Comment by ianvernon** [comment]
Validated kops deployment with `v1.1.0-rc-4.2`, and then redeployed via kops with v1.0.4 , and upgraded following the upgrade guide to `v1.1.0-rc-4.2`. Both went well, and I made some mistakes during upgrade (due to my own error, not due to the guides), and the guide actually helped me realize what I had done wrong :)

**Comment by jrajahalme** [comment]
@ianvernon I got Kubernetes installed with Tectonic, but the very next steps, creating TLS assets does not work. The links redirect to the same Tectonic page that has no info on TLS.

**Comment by jrajahalme** [comment]
So I managed to validate the CoreOS Tectonic installation guides (they worked), but not much more.

**Comment by jrajahalme** [comment]
Discussed with @ianvernon, concluded that the CoreOS guide should be removed, as it would require extensive re-work to work and there has been no interest in this guide for a while, as it has likely been broken for some time already.

**Comment by jrajahalme** [comment]
@ianvernon @tgraf Updated #4569 to remove CoreOS Installation Guide.

**Comment by ianvernon** [comment]
@tgraf is there anything left to do here?
