### ISSUE TITLE
Build errors show up in vagrant start.sh output, even for successful run

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#433]
Not a big deal, but when starting the vagrant VM, several of the build steps output errors, which may be confusing to end users.  These mostly seem to be build-stage.   For example: 

==> cilium-master: go-bindata -prefix ../ -ignore Makefile -ignore '.+\.o$' ../bpf/...
==> cilium-master: make[1]: go-bindata: Command not found
==> cilium-master: make[1]: 
==> cilium-master: *** [bindata.go] Error 127

==> cilium-master: make: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium'
==> cilium-master: make: *** [daemon] Error 2

==> cilium-master: Running provisioner: config-install (shell)...
    cilium-master: Running: /var/folders/1s/y3wg_w6n04d3h5cv2jdd_jpw0000gn/T/vagrant-shell20170323-36573-491zo2.sh
==> cilium-master: stdin: is not a tty
==> cilium-master: stop: Unknown instance: 

Definitely a 'minor' issues, but it would be nice to silence these errors to avoid confusing first time users who are exploring cilium for the first time using the vagrant box tutorial.

**Comment by tgraf** [comment]
This was fixed in commit 8309376248579c732a2ac8fb8d9e3b3e308b66f7 which relieved the requirement to include go-bindata for the build.

Author: Thomas Graf <thomas@cilium.io>
Date:   Wed Mar 15 03:56:16 2017 +0100

    cilium: Check in bindata.go

    Relieves requirement of having go-bindata available at build time.
    Requires make bindata.go to be run whenever bpf/ changes.

    Signed-off-by: Thomas Graf <thomas@cilium.io>
