### ISSUE TITLE
cilium health pings drops in cilium monitor output after restarting/upgrading cilium

### ISSUE THREAD

**Issue by abhide15** [cilium/cilium#4363]
Cilium pods got restarted after upgrading cilium.
In cilium monitor output; I see drops to cilium health API port 4240

```
$ kubectl exec cilium-x6zl4 -it -n kube-system -- sh
# bash
$ cilium monitor -t drop
Listening for events on 8 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
xx drop (Not a local target address) flow 0x700327e2 to endpoint 0, identity 0->0: 10.2.1.187:38754 -> 10.2.4.11:4240 tcp SYN
xx drop (Not a local target address) flow 0x700327e2 to endpoint 0, identity 0->0: 10.2.1.187:38754 -> 10.2.4.11:4240 tcp SYN
xx drop (Not a local target address) flow 0x700327e2 to endpoint 0, identity 0->0: 10.2.1.187:38754 -> 10.2.4.11:4240 tcp SYN
xx drop (Not a local target address) flow 0x8d02651a to endpoint 0, identity 0->0: 10.2.2.51:47334 -> 10.2.4.11:4240 tcp SYN
xx drop (Not a local target address) flow 0xa64c73db to endpoint 0, identity 0->0: 10.2.0.157 -> 10.2.4.11 EchoRequest
xx drop (Not a local target address) flow 0x700327e2 to endpoint 0, identity 0->0: 10.2.1.187:38754 -> 10.2.4.11:4240 tcp SYN
^C
Received an interrupt, disconnecting from monitor...
```
EchoRequest drop seems like cilium-health ping is getting dropped. 
Port 4240 is the API endpoint for cilium health API

Seems like these requests are still going to the old IP address assigned to `cilium_host` link.

**Comment by tgraf** [comment]
The symptoms indicate that the health endpoint IPs are never updated when we receive node updates

**Comment by joestringer** [comment]
We are seeing the latest 10.2.x.y health endpoint IPs in cilium-health output:

```
# cilium-health status | grep -A 2 "10\.2"
    Endpoint connectivity to 10.2.4.82:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=539.298µs
--
    Endpoint connectivity to 10.2.3.123:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=2.565275ms
--
    Endpoint connectivity to 10.2.0.225:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=1.870546ms
--
    Endpoint connectivity to 10.2.1.147:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=2.020404ms
--
    Endpoint connectivity to 10.2.2.116:
      ICMP:          Connection timed out
      HTTP via L3:   OK, RTT=1.990166ms
```

And these match the kubernetes annotations:

```
$ kubectl get nodes -o yaml | grep ipv4-health
      io.cilium.network.ipv4-health-ip: 10.2.4.82
      io.cilium.network.ipv4-health-ip: 10.2.3.123
      io.cilium.network.ipv4-health-ip: 10.2.0.225
      io.cilium.network.ipv4-health-ip: 10.2.1.147
      io.cilium.network.ipv4-health-ip: 10.2.2.116
```

I was also able to confirm that the IP being pinged was previously annotated on the node as a health IP.

So, I think we just left a goroutine behind in `cilium-health` pinging what was previously the health IP. This is probably not being cleaned up. Potentially related to:

https://github.com/cilium/cilium/blob/5b888d6792f6c310c04ab2d76e71ca93375cad05/pkg/health/server/prober.go#L52-L53

**Comment by joestringer** [comment]
I'm not sure that this should be a release blocker. `cilium-health status` appears to still be providing the visibility that's expected, it's just that there's some extraneous pinging going on in the background.

**Comment by tgraf** [comment]
I agree, severity is not high enough for release blocker. Removing label.
