### ISSUE TITLE
CI flake: "error: no objects passed to apply" creating jsonnet objects

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4366]
Hit this on PR #4360, but AFAICT it's not related to the PR:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3816/testReport/k8s-1/7/K8sValidatedServicesTest_Checks_ClusterIP_Connectivity_Checks_service_on_same_node/

### Stacktrace

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:330
Cilium cannot be installed
Expected
    <*errors.errorString | 0xc4204639f0>: {
        s: "cmd: kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/9acb0442_cilium_ds.jsonnet\nerror: no objects passed to apply\n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:54
```

[f0c5341e_K8sValidatedServicesTest_Checks_ClusterIP_Connectivity_Checks_service_on_same_node.zip](https://github.com/cilium/cilium/files/2070973/f0c5341e_K8sValidatedServicesTest_Checks_ClusterIP_Connectivity_Checks_service_on_same_node.zip)

The `test-output.log` inside the zip seems to show a proper-looking YAML, however the previous command does this:

https://github.com/cilium/cilium/blob/a5910535291914762cd80d6b596d4cd40f115362/test/helpers/kubectl.go#L722-L723

I wonder if the output is successfully flushed to stdout in `tee`, but is delayed from flushing to the filesystem for some reason, leading to the following kubectl apply to read an empty file and fail on this line:

https://github.com/cilium/cilium/blob/a5910535291914762cd80d6b596d4cd40f115362/test/helpers/kubectl.go#L727

**Comment by eloycoto** [comment]
Duplicated https://github.com/cilium/cilium/issues/4356

**Comment by joestringer** [comment]
Ah, I saw that but I wasn't sure. I'll close this one.
