### ISSUE TITLE
race condition with starting of L7 Proxy and regenerating endpoint

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4390]
In #4329, the following build failed: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/974/testReport/junit/k8s-1/7/K8sValidatedUpdates_Updating_Cilium_stable_to_master/

Logs: [f0c5341e_K8sValidatedUpdates_Updating_Cilium_stable_to_master.2.zip](https://github.com/cilium/cilium/files/2078265/f0c5341e_K8sValidatedUpdates_Updating_Cilium_stable_to_master.2.zip)

The pod `cilium-j5tqp` was not marked as 'ready' by the output of `kubectl get pods`:

```
cmd: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME                           READY     STATUS    RESTARTS   AGE       IP              NODE
default       app1-3318830813-4c3cq          1/1       Running   0          9m        10.10.0.32      k8s1
default       app1-3318830813-hv6zr          1/1       Running   0          9m        10.10.0.66      k8s1
default       app2-3691078314-qrdzw          1/1       Running   0          9m        10.10.0.59      k8s1
default       app3-753781860-8dzzn           1/1       Running   0          9m        10.10.0.225     k8s1
kube-system   cilium-5xm73                   1/1       Running   0          5m        192.168.36.12   k8s2
kube-system   cilium-j5tqp                   0/1       Running   1          5m        192.168.36.11   k8s1
kube-system   etcd-k8s1                      1/1       Running   0          47m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1            1/1       Running   0          47m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1   1/1       Running   0          47m       192.168.36.11   k8s1
kube-system   kube-dns-1992960195-w0vp9      3/3       Running   0          47m       10.10.1.27      k8s2
kube-system   kube-proxy-d2k7g               1/1       Running   0          19m       192.168.36.12   k8s2
kube-system   kube-proxy-ng786               1/1       Running   0          47m       192.168.36.11   k8s1
kube-system   kube-scheduler-k8s1            1/1       Running   0          47m       192.168.36.11   k8s1
```

When trying to debug #4329 , I noticed that the logs had endpoints regenerating before the call to restore them.

In the attached archive, the logs for `cilium-j5tqp` had the following ordering of logs:

```
2018-06-06T15:57:56.923139812Z level=info msg="Restoring endpoints from former life..."
...
2018-06-06T15:57:56.988674269Z level=info msg="Initializing identity allocator"
...
2018-06-06T15:57:57.000360223Z level=debug msg="Forced policy recalculation triggered"
2018-06-06T15:57:57.00058318Z level=debug msg="Forced policy recalculation triggered"
2018-06-06T15:57:57.000796957Z level=debug msg="Forced policy recalculation triggered"
2018-06-06T15:57:57.001006206Z level=debug msg="Forced policy recalculation triggered"
2018-06-06T15:57:57.001319466Z level=debug msg="Forced policy recalculation triggered"
...
2018-06-06T15:57:57.004242003Z level=debug msg="Regenerating endpoint..." containerID=08cd77e1b4 endpointID=29381 ipv4=10.10.0.59 ipv6="f00d::a0a:0:0:72c5" k8sPodName=":" policyRevision=0
...
2018-06-06T15:57:57.050352649Z level=warning msg="Regeneration of endpoint program failed" containerID=bd1258b3a6 endpointID=25729 error="can't update network policy, proxy disabled" ipv4=10.10.0.225 ipv6="f00d::a0a:0:0:6481" k8sPodName=":" policyRevision=0
2018-06-06T15:57:57.050703775Z level=debug msg="Error regenerating endpoint: can't update network policy, proxy disabled" code=Failure containerID=bd1258b3a6 endpointID=25729 endpointState=ready ipv4=10.10.0.225 ipv6="f00d::a0a:0:0:6481" k8sPodName=":" policyRevision=0 type=200
...
2018-06-06T15:58:02.211073997Z level=info msg="Regenerating 4 restored endpoints"
...
2018-06-06T15:58:02.211122952Z level=info msg="Starting IP identity watcher"
...
2018-06-06T15:58:19.219401821Z level=info msg="Finished regenerating restored endpoints" regenerated=4 total=4
...
2018-06-06T15:58:19.416073671Z level=info msg="Envoy: Accepted access log connection"
```

The logs above indicate that the regeneration of endpoint BPF programs / configuration of the proxy is done before the proxy is done in `daemon/daemon.go:NewDaemon`:

```
restoredEndpoints, err := d.restoreOldEndpoints(option.Config.StateDir, true)
...
identity.InitIdentityAllocator(&d)
...
d.l7Proxy = proxy.StartProxySupport(10000, 20000, option.Config.RunDir, option.Config.AccessLog, &d, option.Config.AgentLabels)

if option.Config.RestoreState {
    d.regenerateRestoredEndpoints(restoredEndpoints)
...
```

In the call to `d.restoreOldEndpoints`, the endpoint is not regenerated yet, but is inserted into the endpoint manager:

https://github.com/cilium/cilium/blob/91287b9f0665ddd22fa4933eece6ae276e4157af/daemon/state.go#L113

And then, in the call to `InitIdentityAllocator`, whenever an Identity is received from the key-value store, we forcibly trigger policy updates:

https://github.com/cilium/cilium/blob/91287b9f0665ddd22fa4933eece6ae276e4157af/pkg/identity/cache.go#L66-L78

This in turn triggers regeneration of the endpoints, which can occur before the `l7Proxy` for `daemon` is initialized. This results in endpoints failing to regenerate upon restart of the agent. Luckily, in the call to `d.regenerateRestoredEndpoints`, the endpoints are able to be put into an OK state, but this means that we are trying to regenerate endpoints before all of the initialization of various subsystems in `cilium-agent` is complete.

This will impact running endpoints and their BPF programs because the endpoints will be put into `not-ready` state, as the error with the `l7Proxy` being nil is hit in the code path started here:

https://github.com/cilium/cilium/blob/91287b9f0665ddd22fa4933eece6ae276e4157af/pkg/endpoint/bpf.go#L687-L691

This will result in the destruction of the BPF PolicyMap / CIDR policy maps for the endpoints, which may cause a loss of packets for existing workloads.

**Comment by ianvernon** [comment]
Note that this may or may not be the cause of the pod not being 'ready', which is why it has been filed as a separate issue.

**Comment by ianvernon** [comment]
One thought @joestringer and I had was whether we can initialize the `l7Proxy` for the daemon earlier, ideally before we initialize the Identity watcher. We should document in the change *why* the ordering of certain bootstrapping is performed so that we do not introduce bugs like this in the future.

**Comment by ianvernon** [comment]
cc: @jrajahalme and @rlenglet

**Comment by joestringer** [comment]
Even if we put the `daemon.l7Proxy` initialization earlier, it might not completely resolve the warning `can't update network policy`, because while it would allow us to push down a policy update into XDS, it may still take some time before the main goroutine is able to spin up Envoy and Envoy is able to ack the resource (/cc @rlenglet @jrajahalme). If this took too long, then the network policy timeout would likely be hit from that path. Ideally I think we would queue up these rebuilds as part of the `identityWatcher` later on, after we've ensured that the proxy is likely to be ready.

**Comment by ianvernon** [comment]
Alternatively, we could simply add not insert into the endpoint manager in `restoreOldEndpoints` and instead do it in `regenerateRestoredEndpoints`.

Actually, this is the correct way to do it; we will have access to the list of endpoints returned by `restoreOldEndpoints` which is passed into  `regenerateRestoredEndpoints` anyway. This seems like the correct fix.

**Comment by ianvernon** [comment]
Will put out a PR with the above proposed fix.

**Comment by tgraf** [comment]
Great catch @ianvernon!

**Comment by ianvernon** [comment]
Noted that 
```
2018-06-06T15:57:57.050703775Z level=debug msg="Error regenerating endpoint: can't update network policy, proxy disabled" code=Failure containerID=bd1258b3a6 endpointID=25729 endpointState=ready ipv4=10.10.0.225 ipv6="f00d::a0a:0:0:6481" k8sPodName=":" policyRevision=0 type=200
``` 

was at debug level, seems like it should be higher.
