### ISSUE TITLE
Measure endpoint and policy computation time

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4396]
Similar to how we measure `buildDuration` in `regenerateBPF()`, it would be nice to also measure the time to compute policy. For reference:

https://github.com/cilium/cilium/blob/91287b9f0665ddd22fa4933eece6ae276e4157af/pkg/endpoint/bpf.go#L538-L548

This could be something as simple as adding timers and extending the debug logs.

* [x] Measure `regeneratePolicy()` (Full policy regeneration)
* [x] Measure `regenerate()` (Full endpoint regeneration)
* [ ] Measure `updateNetworkPolicy()` (Proxy policy calculation)

**Comment by manalibhutiyani** [comment]
I can see if I have cycles for this.

**Comment by manalibhutiyani** [comment]
I am adding`endpoint regeneration` time too. Spoke to @rlenglet and to have an idea of the distribution, assuming a normal form, we need all 3:
- count of regenerations
- sum of time taken to regenerate 
- sum of squares time taken to regenerate
