### ISSUE TITLE
Fix two issues found in test cases

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#440]
- [ ] in 06-lb test case the ping6 from host to container doesn't work while ping works.
- [ ] in 01-ct test when also adding a UDP_STREAM test, it fails to connect while TCP_STREAM works.

**Comment by tgraf** [comment]
Is this still an issue?

**Comment by borkmann** [comment]
Both are still an issue, for 01-ct case, UDP_STREAM in v6 works, but not for v4.

**Comment by ianvernon** [comment]
@borkmann this is quite stale; the CI has been migrated to a different framework. Should the issue description be changed accordingly, or can this be closed?

**Comment by borkmann** [comment]
Closing since stale and migration to Ginko
