### ISSUE TITLE
k8s host (and legacy-host-allows-world) logic preventing L7 redirects

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4401]
The following logic I believe is preventing L7 redirects, leading to host / world traffic never going to the proxy. I think that the intended behaviour is that if there's an L7 policy on a port from these identities, then traffic should be forwarded to the proxy, but the proxy should allow all traffic?

https://github.com/cilium/cilium/blob/91287b9f0665ddd22fa4933eece6ae276e4157af/pkg/endpoint/policy.go#L224-L230

https://github.com/cilium/cilium/blob/91287b9f0665ddd22fa4933eece6ae276e4157af/pkg/endpoint/policy.go#L252-L258

Commit b666ceeb286f ("policy: Overwrite eventual L4 localhost policies when AllowLocalhost=true")  introduced the localHost version of this, which allows the policy to work correctly, but I suspect that it prevents the traffic from going to the proxy. Wondering if the logic should actually be introduced earlier during the L4Filter creation so that l3-dependent L4 entries can be generated and get picked up in the following datapath code:

https://github.com/cilium/cilium/blob/91287b9f0665ddd22fa4933eece6ae276e4157af/bpf/lib/policy.h#L60-L71

https://github.com/cilium/cilium/blob/91287b9f0665ddd22fa4933eece6ae276e4157af/bpf/lib/policy.h#L101-L109

Related: #4245

**Comment by tgraf** [comment]
> Commit b666cee ("policy: Overwrite eventual L4 localhost policies when AllowLocalhost=true") introduced the localHost version of this, which allows the policy to work correctly, but I suspect that it prevents the traffic from going to the proxy. Wondering if the logic should actually be introduced earlier during the L4Filter creation so that l3-dependent L4 entries can be generated and get picked up in the following datapath code:

Yes, you are absolutely right. Good catch!
