### ISSUE TITLE
CI: no logs from fail on BeforeEach/BeforeAll

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4414]
Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/2751/testReport/junit/k8s-1/7/K8sValidatedKafkaPolicyTest_KafkaPolicies/

Logs: [f0c5341e_K8sValidatedKafkaPolicyTest_KafkaPolicies.zip](https://github.com/cilium/cilium/files/2082551/f0c5341e_K8sValidatedKafkaPolicyTest_KafkaPolicies.zip)

There is no bugtool output, or anything related to Cilium for further triage. Fix the offending test to correctly gather logs / any potential Ginkgo framework bugs.

**Comment by eloycoto** [comment]
The issue, is the Fail happens in `Before*` functions, no After* functions are in place yet. I need to find a workaround for this one.

**Comment by eloycoto** [comment]
BTW: kinda hard to fix this for 1.1 release, need to say that it'll be super difficult to fix without changes in Ginkgo upstream.

**Comment by ianvernon** [comment]
Not necessarily; we can make assertions within the `It`s  instead?
