### ISSUE TITLE
daemon: do not restore services that have been deleted by K8s

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4457]
If service A is added via K8s, Cilium will watch for events and plumb that service into the datapath. When the Cilium DaemonSet / pod is deleted, the service-related entries in the datapath are still present because the BPF filesystem is mounted from the host into the pod. If a service is deleted while Cilium is not running, then if Cilium is configured to restore prior state from the datapath when it reloads, then it will re-add the service entries found in the datapath even if the services have been deleted via K8s. When running with K8s as the orchestration system, only restore services in the BPF datapath that are still present in Kubernetes. 

This is tracking the issue discovered in #4455 .

**Comment by aanm** [comment]
Possible solution: Sync with bpf, then sync with k8s and delete old services that no longer exist.
