### ISSUE TITLE
Cilium Tutorial - Base Container Image

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#446]
Our docs / tutorials / examples / demos use a mix of base container images, and a lot of them don't have most of the things we'd want in them to do basic connectivity testing and debugging. 

I'd suggest we create a "demo" base which includes: 
-  curl
-  ping
- arp
- netstate
- tcpdump
- host or other DNS lookup. 
- tail / less (for looking at logs) 

It would probably also be convenient to have a simple way to create "simple" demo webservices.  One simple idea would be to have a basic webserver that will just serve of the filesystem, and then we can just create directories + text files.  Though I think this would be mostly limited to running "get" requests.   We would obviously need a reasonable set of text editors in this case (my vote: vim). 

A more advanced option would be making it easy to run an auto-generated app based on a swagger spec, as tgraf did for some of the demos already.    Would need text editors here too.

**Comment by mskarbek** [comment]
Something like that? ;)
https://gist.github.com/mskarbek/b31be1655e859cf81cec58869365058d

**Comment by aanm** [comment]
I think we can mark this as solved since we already got this one https://github.com/cilium/demo-image

**Comment by tgraf** [comment]
We have been using `cilium/demo-image` successfully, closing this.
