### ISSUE TITLE
staleMapWalker should also remove obj local pinnings

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#447]
After running test cases, there's lots of stale tail call maps that are not taken into consideration for cleanup. We should also consider them to not waste memory (although these maps are small).
```
[...]
/sys/fs/bpf/tc/9b15f23b9b38378e5ab70fc73bba0590898a89a3
/sys/fs/bpf/tc/9b15f23b9b38378e5ab70fc73bba0590898a89a3/cilium_calls
/sys/fs/bpf/tc/0d509b16cf5a98608d46d3379a6d15fb6fae9efe
/sys/fs/bpf/tc/0d509b16cf5a98608d46d3379a6d15fb6fae9efe/cilium_calls
/sys/fs/bpf/tc/3103cfc34e91f690c07b6d64474c1d80382509a3
/sys/fs/bpf/tc/3103cfc34e91f690c07b6d64474c1d80382509a3/cilium_calls
/sys/fs/bpf/tc/50a81782d2059cec1c2726f6f3be425c370881da
/sys/fs/bpf/tc/50a81782d2059cec1c2726f6f3be425c370881da/cilium_calls
[...]
```
One possibility could be to make them as global pinning as well with ep ID appended that staleMapWalker matches on. Or let tc have a custom scheme in how to generate these dirs (f.e. similar to MODULE_LICENSE() section, we have a MODULE_ALIAS() section containing a string which gets used to create a symlink to this path) and cilium could place the ep ID there when compiling the prog.

**Comment by borkmann** [comment]
#630 (by accident opened a duplicate) has some more information as well.

**Comment by aalemayhu** [comment]
Some number of entries before and after

```bash
$ sudo find /sys/fs/bpf/tc/ > /tmp/{after,before}
$ wc -l /tmp/before /tmp/after 
   19 /tmp/before
  155 /tmp/after
  174 total
```

**Comment by tgraf** [comment]
Running into this frequently now :-)

**Comment by aalemayhu** [comment]
I was going to wrap this up but reassigned to @aanm. He seemed interested in getting it done faster.

**Comment by borkmann** [comment]
#732
