### ISSUE TITLE
Cilium.yaml manifest refers to bad docker image version

### ISSUE THREAD

**Issue by cvila84** [cilium/cilium#4480]
### Title

Cilium.yaml manifest refers to bad docker image version when working with fixed version

### General Information

- Cilium version : Any tagged version (ex: v1.0.4, v1.1.0-rc4)
- Kernel version 4.15.0-22 x86_64
- Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

### How to reproduce the issue

1. kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.1.0-rc3/examples/kubernetes/1.10/cilium.yaml 

## Feature Requests

Cilium should be deployed in the cluster but docker cannot pull the image as the manifest wants
`image: docker.io/cilium/cilium:1.1.0-rc2`
Where as docker version tag is v1.1.0-rc2 (the 'v' is missing) according to [https://hub.docker.com/r/cilium/cilium/tags/](url)
Please note it works well when using the manifest from master (as in this case, it refers to latest)

**Comment by tgraf** [comment]
@cvila84 Good catch. The tag is wrong. Which documentation branch is still referring to this?

**Comment by cvila84** [comment]
I tried with 1.1.0-rc4, 1.1.0-rc3, 1.0.4, all of these have the issue
I guess the manifest file is generated through a template that includes the actual version, so I think the error is for all versions (except for 'latest')

**Comment by aanm** [comment]
@cvila84 Can you try with `v1.1.0-rc4`? (notice the 'v' before the version)

**Comment by tgraf** [comment]
@aanm @cvila84 already noticed the missing v prefix, see description of the bug report.

**Comment by aanm** [comment]
@tgraf I thought @cvila84 was referring to the docker image tag and not the repository tag

**Comment by tgraf** [comment]
@cvila84 The image tag references have been fixed in the v1.1 branch
