### ISSUE TITLE
Add `--version` flag to all binaries

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#449]
Ideally with:
- version
- git commit
- go version used to compile
- date?

**Comment by aalemayhu** [comment]
If there was a tag, `git describe --tags` would work for $version+$git_commit. Maybe these values can be added at link time? Printing the date seems useful for users not using git, how about something like?

```bash
$ cilium --version
cilium version 0.8 (20170324) compiled with go version go1.7.5 linux/amd64
# or if there is actually changes after 0.8
$ cilium --version
cilium version 0.8-g863aa311f4b8 (20170324) compiled with go version go1.7.5 linux/amd64
```
