### ISSUE TITLE
Request fails in scale out scenario for pod to pod networking

### ISSUE THREAD

**Issue by eldin77** [cilium/cilium#4510]
## Bug reports

I have tried to communicate from a pod to pods which are scaling out at a moment using Service's Cluster IP. In Kubernetes, grouped Endpoints as one Service can be scaled out in some cases.(either manually and auto-scaling).
In this case, when pods are scaling out, requests fail must happen.

Request fails should not be happened in scaling out scenario. If connection sync is not correct  in HTTP, web server sends RST-packet.. then request fails. (It doesn't happen in Calico)

---
In my polite opinion, it happens because of hash algorithm.
--> https://github.com/cilium/cilium/blob/master/bpf/lib/lb.h#L184 

### Title

Request fails in scale out scenario for pod to pod networking

### General Information

- Cilium version (run `cilium version`
```
Client: 1.0.90 aef051d 2018-05-23T12:01:01-07:00 go version go1.9 linux/amd64
Daemon: 1.0.90 aef051d 2018-05-23T12:01:01-07:00 go version go1.9 linux/amd64
```
- Kernel version (run `uname -a`)
```
4.12.2-1.20180114.el7.centos.x86_64
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Kubernetes v1.9.6
```

### How to reproduce the issue

1. Make 2 sets of Deployment and target Service(ClusterIP) in Kubernetes
2. Generate packets(I used locust - https://github.com/kubernetes/charts/tree/master/stable/locust) from a pod to the ClusterIP.
3. Check correct connectivity 
4. Try to change Replica in a Deployment. The target Deployment is web servers(SimpleNodeJS...just helloworld)
5. Check request fails

---

If you have any discussion, then please contact me anytime. I'm very interested in Cillium.
Thank you.

**Comment by tgraf** [comment]
@eldin77 Your analysis is correct, the LB is not yet stateful

**Comment by eldin77** [comment]
@tgraf Thank you for fast reply. lol.. I think it is an essential feature of Kubernetes. When should I retry this test? I have the environment to test this for all.

**Comment by tgraf** [comment]
> When should I retry this test? I have the environment to test this for all.

We will fix it and ping you when this is available.

**Comment by eldin77** [comment]
@tgraf Thank you.

**Comment by jrfastab** [comment]
@joestringer working on this now should have a proposed fix shortly.
