### ISSUE TITLE
Make MAC address of a Service configurable

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#4515]
### Description of requested functionality

I would like to be able to statically set a MAC address for a given service.

### Example use cases

I would like to migrate a FlexLM license server to k8s.

In a traditional setup, a FlexLM server is bound to its host based on the primary network interface's mac address. When running on k8s, the license server would instead use the pod's/container's primary MAC instead.

In order to be useful, the MAC address of the FlexLM pod would need to persist between pod restarts. It would be even better if I were able to explicitly set the MAC address so I don't have to ask our vendors for updated licenses.

**Comment by runiq** [comment]
(Just for the record, it was me who asked for this feature, I switched accounts)
