### ISSUE TITLE
Policy generation can take a long time for a large number of unique labels

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4526]
Currently, if you import a very large CIDR policy when there are several pods being managed by Cilium, then endpoint regeneration may be triggered several times, and each endpoint regeneration takes a long time to calculate policy, and they fight for attention from the CPU. If it takes too long, then the 10s timeout below will expire and policy won't be applied to the proxy within this time (because not enough CPU is available to calculate the `allowedIdentities`, push through XDS, have Envoy ack all within the timeframe). This leads to failure to apply policy. In k8s mode where the policy application is triggered from events from k8s, this will retry and Cilium will get stuck in a state where it constantly attempts to apply the policies, regenerate endpoints, fail to apply policy to the proxy, fail out, and retry again.

https://github.com/cilium/cilium/blob/5d39d0e41b193a9e891495709b151839056026b1/pkg/endpoint/bpf.go#L674-L681

https://github.com/cilium/cilium/blob/5d39d0e41b193a9e891495709b151839056026b1/pkg/endpoint/bpf.go#L781-L785

~If we limit the number of concurrent pod regenerations to the number of available CPUs, then this may mitigate issues like the above because enough CPU should be available to push through even a fairly large policy.~

*Apparently we already do this, see the first comments below.*

Other avenues for investigation:
* Make policy computation more efficient (@ianvernon has some WIP on this)
* Figure out the limitations on number of rules we can configure and consider gating policies based on this, before they cause Cilium to get into a bad state

Related: https://github.com/cilium/cilium/issues/4396

**Comment by aanm** [comment]
@joestringer perhaps setting up `ncpu := runtime.NumCPU() - 1` would help?

https://github.com/cilium/cilium/blob/812eee2c8035747ee3292600ade6fb5a3cf40285/daemon/daemon.go#L1574-L1583

**Comment by joestringer** [comment]
@aanm I wonder if even that is reasonable. What if a CPU-heavy workload is running while we attempt to install policy? Cilium assumes it can burst to almost the entire CPU?

**Comment by joestringer** [comment]
Upon further investigation, I'm noticing these callstacks:

```
goroutine 26448088 [semacquire]:                                                
sync.runtime_SemacquireMutex(0xc42012e084, 0xffffff00)                          
        /usr/local/go/src/runtime/sema.go:71 +0x3d                              
sync.(*Mutex).Lock(0xc42012e080)                                                
        /usr/local/go/src/sync/mutex.go:134 +0xee                               
regexp.(*Regexp).get(0xc42012e000, 0x0)                                         
        /usr/local/go/src/regexp/regexp.go:211 +0x3d                            
regexp.(*Regexp).doExecute(0xc42012e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42c2d9875, 0x2, 0x0, 0x0, ...)
        /usr/local/go/src/regexp/exec.go:420 +0x40                              
regexp.(*Regexp).doMatch(0xc42012e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42c2d9875, 0x2, 0x2)
        /usr/local/go/src/regexp/exec.go:412 +0xc8                              
regexp.(*Regexp).MatchString(0xc42012e000, 0xc42c2d9875, 0x2, 0x0)              
        /usr/local/go/src/regexp/regexp.go:435 +0x6c                            
github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/validation.IsQualifiedName(0xc42c2d9860, 0x17, 0xf, 0x1b, 0xc421ea3370)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/validation/validation.go:66 +0xe4
github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/labels.validateLabelKey(0xc42c2d9860, 0x17, 0x7f5a16f466c8, 0x0)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/labels/selector.go:822 +0x42
github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/labels.NewRequirement(0xc42c2d9860, 0x17, 0x2b6b351, 0x1, 0xc428657110, 0x1, 0x1, 0x22, 0x40, 0xc42c2d9860)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/labels/selector.go:135 +0x3f
github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelectorAsSelector(0xc42337a9a0, 0x18, 0x29eb940, 0x0, 0x60000000000)
        /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go:40 +0x1f5
github.com/cilium/cilium/pkg/policy/api.(*EndpointSelector).Matches(0xc4219182d8, 0x3be7260, 0xc42cdd5b80, 0xc42cdd5b80)
        /go/src/github.com/cilium/cilium/pkg/policy/api/selector.go:209 +0x43   
github.com/cilium/cilium/pkg/endpoint.getSecurityIdentities(0xc4294047e0, 0xc4219182d8, 0xc4305f4e50, 0x1, 0x2)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:75 +0x184       
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).convertL4FilterToPolicyMapKeys(0xc4200cdb80, 0xc421ea3a10, 0x10610620000b501, 0xc42e4e3a78, 0x7d4, 0x900)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:96 +0x1ea       
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).computeDesiredL4PolicyMapEntries(0xc4200cdb80, 0xc4257cfc50)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:128 +0x325      
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).computeDesiredPolicyMapState(0xc4200cdb80, 0x3c0d080, 0xc421bdb200, 0xc421f4c018, 0xc4204a5c00)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:207 +0x96       
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc4200cdb80, 0x3c0d080, 0xc421bdb200, 0xc421ea3d48, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:557 +0x507      
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).TriggerPolicyUpdatesLocked(0xc4200cdb80, 0x3c0d080, 0xc421bdb200, 0x0, 0x150f609, 0xc4256a43c0, 0x3bd9201)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:785 +0x77       
github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates.func1(0x3c0d080, 0xc421bdb200, 0xc42d6d5701, 0xc4200cdb80, 0xc429a0ea40)
        /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:266 +0x6e
created by github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates    
        /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:264 +0xbf
```

Seems like we're constructing brand new labelselectors every time we attempt to match a label in policy, and this is doing various bits of validation, including grabbing global regex mutexes. This basically serializes each of the threads.

**Comment by aanm** [comment]
Removed the 1.2-bugfix as the first part of this issue was already fixed by @ianvernon

**Comment by joestringer** [comment]
The spirit of this issue should be addressed in https://github.com/cilium/cilium/projects/23 ; Closing.
