### ISSUE TITLE
CI: Add timestamps to monitor.log

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4566]
It'd be good to get timestamps for the monitor log so the traffic can be cross-referenced with timestamps in testsuite failures.

This might just be a matter of installing and using the `ts` command.

**Comment by eloycoto** [comment]
is it already in there no? 
https://github.com/cilium/cilium/blob/63f3676dfbce11a4d80d209246c0dcfe30906ad7/test/helpers/cilium.go#L391

**Comment by ianvernon** [comment]
@eloycoto that looks like it's for the Docker tests, which run the monitor directly, but not for the K8s tests, which run microscope.

**Comment by eloycoto** [comment]
Btw: For the track: 

I search about this one:
``` 
/usr/src/microscope # apk add moreutils
ERROR: unsatisfiable constraints:
  moreutils (missing):
    required by: world[moreutils]
/usr/src/microscope # apk search moreutils
perl-list-moreutils-doc-0.419-r1
perl-list-moreutils-xs-doc-0.426-r0
perl-list-moreutils-0.419-r1
perl-list-moreutils-xs-0.426-r0
/usr/src/microscope # 
```

But looks like that moreutils is not in the alpinelinux, but I found online: 
https://pkgs.alpinelinux.org/package/edge/testing/x86/moreutils
