### ISSUE TITLE
Upgrade notes for 1.1 are improperly indented

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4606]
http://docs.cilium.io/en/v1.1/install/upgrade/#mtu-handling-behavior-change-in-cilium-1-1

The above link is nested wrong. There should be

* Upgrade guide
  * Upgrade notes
    * Issue 1
      * ...
    * Issue 2
      * ...

**Comment by ishantanu** [comment]
@joestringer Out of the below two, which is the kind of nesting you're expecting? Or is it different than these two?
1. 
![Cilium Nesting 1](https://user-images.githubusercontent.com/6175822/41832837-6e935d82-786b-11e8-8764-e8800b8a6a69.PNG)

2. 
![Cilium Nesting 2](https://user-images.githubusercontent.com/6175822/41832838-6ec6319e-786b-11e8-9b39-496c4bce4463.PNG)

**Comment by joestringer** [comment]
@iamShantanu101 I'm expecting the second one.

**Comment by ishantanu** [comment]
Fix is on its way.
