### ISSUE TITLE
vagrant: Kubernetes installation fails if VM already exists

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium#4628]
When you create a Vagrant VM with `K8S=1` env variable, execute `start.sh`, then halt the VM and execute `start.sh` again, then the following error occurs:

```
    k8s1: ----- 01-install-etcd.sh: main: Installing etcd... DONE!
    k8s1: ----- 02-install-kubernetes-master.sh: main: Installing kubernetes master components...
    k8s1: cp: cannot create regular file '/usr/bin/kube-apiserver': Text file busy
    k8s1: cp: cannot create regular file '/usr/bin/kube-controller-manager': Text file busy
    k8s1: cp: cannot create regular file '/usr/bin/kube-scheduler': Text file busy
```

Steps to reproduce:

```
export K8S=1
./contrib/vagrant/start.sh
vagrant halt
./contrib/vagrant/start.sh
```

The only workaround is to do `vagrant destroy`. There is no possible way to reuse already existing VM.

**Comment by aanm** [comment]
@mrostecki can you try
```
export K8S=1
./contrib/vagrant/start.sh
vagrant halt
RELOAD=1 ./contrib/vagrant/start.sh
```

**Comment by vadorovsky** [comment]
@aanm OK, it's working, although it's quite confusing. Can we document it somewhere or set `RELOAD` variable inside `start.sh` when VM already exists?

**Comment by aanm** [comment]
@mrostecki the documentation exists http://cilium.readthedocs.io/en/latest/contributing/?highlight=RELOAD#options

Please check if this helps https://github.com/cilium/cilium/pull/4631

**Comment by vadorovsky** [comment]
@aanm This documentation only mentions that `RELOAD` env variable is a replacement for `vagrant reload`. `vagrant reload` is used when VM is running and user wants to restart it. After shutting down the VM (`vagrant halt`), usually `vagrant up` is used. That's why it's confusing and this doc doesn't explain the issue with existing **but shutdown** VM.

**Comment by vadorovsky** [comment]
@aanm But yes, your PR seems to fix the issue. :) Let me test and review it.
