### ISSUE TITLE
CI: K8sValidatedPolicyTestAcrossNamespaces - Microscope does not get started

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4644]
In one of the PRs the CI did not finish because of this message:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:1010
Microscope cannot be started
Expected
    <*errors.errorString | 0xc420538070>: {
        s: "Timeout reached: could not get Pods",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:1012
```

Unfortunately, inside the zip file there are no logs from microscope nor from kube-apiserver to know the pods' state.

[test_results_Cilium-PR-Ginkgo-Tests-Validated_4426.zip](https://github.com/cilium/cilium/files/2137077/test_results_Cilium-PR-Ginkgo-Tests-Validated_4426.zip)

Adding @eloycoto as I believe the CI has a bug which should get the logs if microscope fails to be setup.

Adding @nebril to be the first point of contact for microscope.

**Comment by eloycoto** [comment]
These Describe function was deleted, so this issue can be close. 
https://github.com/cilium/cilium/pull/4694
