### ISSUE TITLE
Documentation issue for Direct routing

### ISSUE THREAD

**Issue by subrnath** [cilium/cilium#4658]
**Important:** Join our [slack channel](http://cilium.io/slack) for immediate
support and an opportunity to ask questions. Please also have a look at our
[FAQ](https://goo.gl/qG2YmU) for frequently asked questions first.

If you open a GitHub issue, please follow these guidelines:

1. It must be a bug or a feature request.
2. The form below must be filled out.

--------------

### Title
Documentation issue for Direct routing

### General Information

- Cilium version (run `cilium version`)  - 

v1.0.4

- Kernel version (run `uname -a`) - 
Linux worker3 4.10.0-27-generic #30~16.04.2-Ubuntu SMP Thu Jun 29 16:07:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Kubernetes "v1.10.0"

- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

### How to reproduce the issue

As per http://docs.cilium.io/en/doc-1.0/concepts/#arch-direct-routing, 

_Direct / Native Routing Mode
This is an advanced networking mode which requires the underlying network to be made aware of container IPs. You can enable this mode by running Cilium with the option --tunnel disabled._

If we give, --tunnel=disable, following error comes -
level=fatal msg="Invalid setting for -t, must be {vxlan, geneve}"

it seems correct option is --device flag.

**Comment by eloycoto** [comment]
Hi @subrnath 

The direct routing is only enabled on Cilium 1.1. Could you update your base image? 

Regards.

**Comment by subrnath** [comment]
Problem is not seen in docker image cilium/cilium:v1.0.4 but seen in docker.io/cilium/cilium:latest.
