### ISSUE TITLE
IPAM support 

### ISSUE THREAD

**Issue by subrnath** [cilium/cilium#4668]
### Description of requested functionality

Can cilium support ipam plugin which will be useful if we need to know the IP of the POD before hand.

### Example use cases
I am using cilium with direct routing mode. Routes have been created by kube-router. It works fine with the new cilium fix provided in https://github.com/cilium/cilium/pull/4547. Now PODS created on Node-0 gets an IP address from 10.244.0.0/24 and Node-1 gets IP address from 10.244.1.0/24. Kubeadm was started with  --pod-network-cidr=10.244.0.0/16.

Now, I would like to PODs to have predefined IP from the nodes subnet prefix. For example, POD-1 created on Node-0 to get 10.244.0.168 or 10.244.0.169 instead of any random IP address from  10.244.0.0/24. 

We work with CRD and define ipam section in this.

apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: cilium-conf-network-first
plugin: cilium-cni
args: '[
                {
                "name": "cilium-conf-network-first",
                "type": "cilium-cni",
                "mtu": 1500,
                "ipam": {
                         "type": "host-local",
                         "subnet": "10.244.0.0/24",
                         "rangeStart": "10.244.0.168",
                         "rangeEnd": "10.244.0.169"
                     }
        }
]'

POD is created with network name as "cilium-conf-network-first". It seems cilium doesn't support this ipam section and POD got the IP address as 10.244.0.250.

### List of sub tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by tgraf** [comment]
@subrnath We don't implement the IPAM configuration yet and rely on the the k8s PodCIDR configuration.

What I don't understand in your example is how it ties an IP to a particular pod. The configuration of the IPAM pool is cluster wide.

**Comment by subrnath** [comment]
In this scenario, we are scheduling the POD to a particular node and that node specific label is put in the nodeselector field of the manifest. 

OK. Agree with you, with as the IP allocation from  k8s PodCIDR configuration, it might not be feasible to  have IPAM.
