### ISSUE TITLE
re-triggering tests in PRs does not stop previous tests that are still running

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4673]
a new `test-me-please` does not stop old builds, at least for `Cilium-PR-Ginkgo-Tests-K8s` as seen here https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/ build 424, 425, 426, 427 and 428 are running in parallel for the same PR

**Comment by eloycoto** [comment]
Quick question here: 

- If the build fails should the job stop all other builds? 
- If the builds is cancelled, all the downstream jobs need to be cancelled too?

**Comment by aanm** [comment]
>If the build fails should the job stop all other builds?

You mean, if `k8s-test-upstream` fails it should fail the ginko tests? No

>If the builds is cancelled, all the downstream jobs need to be cancelled too?

You mean, if I run `k8s-test-upstream` and then `test-me-please`, should `test-me-please` stop the tests running by `k8s-test-upstream`? No.

**Comment by eloycoto** [comment]
Current issues: 

1) If the ginkgo-test fails, it should stop all k8s tests? or keep it running
2) Not possible to do. If we stop with test-me-please all others will stop. The only way that we can do, it's block the test-me-please to finish the k8s and continue with the test. Will be 4hours test.

**Comment by aanm** [comment]
These are my requirements:
 - `test-me-please` should stop all previous builds triggered by the previous `test-me-please`.
 - `test-missed-k8s` should stop all previous builds triggered by the previous `test-missed-k8s`.

**Comment by eloycoto** [comment]
sadly, that can't be done :-(
