### ISSUE TITLE
tgraf/nettools fails with permission denied when running ping6

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#469]

**Comment by tgraf** [comment]
Might be related to `net.ipv4.ping_group_range` setting

**Comment by aanm** [comment]
This seems to work, no?
`docker run --cap-add NET_ADMIN -ti tgraf/nettools ping 8.8.8.8`

**Comment by tgraf** [comment]
> This seems to work, no?
> docker run --cap-add NET_ADMIN -ti tgraf/nettools ping 8.8.8.8

Yes, this works. Will fix up the test scripts.

**Comment by aanm** [comment]
The other options is that if you change the base image to ubuntu instead of fedora.
```
$ docker run -ti ubuntu sh -c 'apt-get update && apt-get install -y iputils-ping && ping -c4 8.8.8.8'
...
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=46 time=61.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=46 time=59.1 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=46 time=57.6 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=46 time=66.0 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 57.630/60.998/66.018/3.161 ms
```
```
$ docker run -ti fedora sh -c 'dnf install -y iputils && ping -c4 8.8.8.8'
...
Installed:
  iputils.x86_64 20161105-1.fc25                                                                                                                                                                                                                                                

Complete!
sh: /usr/sbin/ping: Operation not permitted
```

**Comment by tgraf** [comment]
> The other options is that if you change the base image to ubuntu instead of fedora.

Is the difference that the ubuntu container image modifies `net.ipv4.ping_group_range` or what is the actual difference?

**Comment by mskarbek** [comment]
Actual difference is in the way both pings are installed:
- in Ubuntu `postinst` script just runs `chmod u+s /bin/ping`
- in Fedora `setcap` is used with `cap_net_admin+ep,cap_net_raw+ep` which makes `execve()` to fail:
   `execve("/bin/ping", ["/bin/ping", "-h"], [/* 15 vars */]) = -1 EPERM (Operation not permitted)`

If we remove `cap_net_admin+ep` from `ping` then everything works:
```
docker run -it fedora:25 /bin/bash -c 'dnf install -y iputils && /usr/sbin/setcap cap_net_raw+ep /bin/ping && /bin/ping -c4 8.8.8.8'
...
Installed:
  iputils.x86_64 20161105-1.fc25
Complete!
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=53 time=37.9 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=53 time=38.0 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=53 time=37.9 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=53 time=37.9 ms

--- 8.8.8.8 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 37.913/37.970/38.079/0.205 ms
```

**Comment by tgraf** [comment]
Thanks @mskarbek 
Fixed in https://github.com/tgraf/nettools-docker/commit/862dc300dfdc20d35a380360337b3de19e726713
