### ISSUE TITLE
policy: how are requirements treated when coupled with entities?

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4696]
We currently have five special 'entities' in Cilium, which are used in `FromEntities` and `ToEntities` when computing policy. These entities correspond to 'special' identities and encode certain meaning about the source / destination traffic accordingly. 

They are:

* Host
* World
* Cluster
* Init
* Health

After this point, the term "requirements" refers to "ToRequires" and "FromRequires".
Currently, when policy is synthesized in relation to an identity / set of labels / an endpoint in Cilium, we gather entities, endpoint selectors from ToEndpoints / FromEndpoints, and CIDRs and transform them into EndpointSelectors. 

The side effect of this, is that entities and egress CIDRs are also affected by requirements.

My question, is whether CIDR policy and entity-related policy should be affected by requirements; do requirements only affect 'FromEndpoints', or do they affect everything that is transformed to a label (CIDR, entities, etc.)?

Take, for example, the following policy:

```
[{
    "endpointSelector": {
        "matchLabels":{"id.app1":""}
    },
    "ingress": [{
        "fromEntities": [
           "world"
        ]
    }]
},
{
    "endpointSelector": {
        "matchLabels":{"id.app1":""}
    },
    "ingress": [{
        "fromRequires": [
	    {"matchLabels":{"id.app2":""}}
	]
    }]
}]  
```

Nothing from the world will ever have the label `id.app2`, so effectively, all traffic from the world is denied in the current policy implementation within Cilium. Is this desired behavior?

**Comment by tgraf** [comment]
Initially we had no entities at all and everything was represented as reserved labels so requirements always applied to what we call entities today. However, the policy repository was initially a tree which allowed to define rules in a parent of which child requirements would not apply. We simplified the language and this is a current gap.

We have to address this of course. Two obvious options come to mind but we should discuss it and explore more of course:

* Allow to define that certain fromEndpoints are not subject to requirements. This is probably not ideal as it defeats the purpose of requirements which is to impose additional requirements on others.
* Extend requirements to allow specifying a matchLabels which limits the peer identity subject to policy evaluation to which a requirement applies. This would allow to exclude certain labels from a requiremens, e.g.

```
{
    "endpointSelector": {
        "matchLabels":{"id.app1":""}
    },
    "ingress": [{
        "fromRequires": [
	    {"matchLabels":{"id.app2":""},
             "except":{"reserved:world":""}} 
	]
    }]
}
```

**Comment by rlenglet** [comment]
Instead of an `except`, I think it would be cleaner from a user's viewpoint to support disjunctions ("OR") of label selectors in each `from/toRequires`, e.g. to support expressing "requires from app=foo OR reserved:world". And we'd keep a conjunction ("AND") semantics among all the `from/toRequires` that apply to a particular endpoint.

That would be relatively easy to implement by manipulating sets of identities, but would be quite hard to do with the current implementation which manipulates labels and selectors. I.e. this will require first to merge https://github.com/cilium/cilium/pull/4625.

**Comment by tgraf** [comment]
> I think it would be cleaner from a user's viewpoint to support disjunctions ("OR") of label selectors in each from/toRequires

I like the approach a lot. We can use k8s set based approach for this as well.

Challenge:
Require does not allow on its own. Any requirement needs to be extended with an actual allow so the user would write: allow from app2, allow from world, require from world or teamA. I think it's still fine but it's not as pretty anymore.
