### ISSUE TITLE
policy: store proxy redirect ports in PolicyMap keys

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4711]
#2918 modified the BPF datapath to look up proxy ports from policy map entries. However, the Cilium agent is not populating those fields. The proxy ports are still compiled into arrays in the BPF programs (`lxc_config.h`), e.g.:
```
#define CFG_L3L4_EGRESS 0,20480,57930,6, (), 0
#define NR_CFG_L3L4_EGRESS 1
#define CFG_L3L4_INGRESS 0,36895,7754,6,1,16415,31278,6,2,20480,59212,6, (), 0
#define NR_CFG_L3L4_INGRESS 3
```
Those arrays are generated by method `Endpoint.writeL4Policy` in `pkg/endpoint/bpf.go`.

**Comment by rlenglet** [comment]
That was already done in https://github.com/cilium/cilium/pull/2918.

**Comment by rlenglet** [comment]
#2918 only fixed the BPF datapath. The Cilium agent is still not populating the proxy port in policy map entries.
