### ISSUE TITLE
use CRDs for storage instead of etcd directly

### ISSUE THREAD

**Issue by colemickens** [cilium/cilium#4726]
**Important:** Join our [slack channel](http://cilium.io/slack) for immediate
support and an opportunity to ask questions. Please also have a look at our
[FAQ](https://goo.gl/qG2YmU) for frequently asked questions first.

If you open a GitHub issue, please follow these guidelines:

1. It must be a bug or a feature request.
2. The form below must be filled out.

--------------

### Title

Choose a descriptive title that summarizes the symptom of the bug

### General Information

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

### How to reproduce the issue

1. instruction 1
2. instruction 2

### Title

Choose a descriptive title, e.g. "Support delivering pizzas"

### Description of requested functionality

Paragraph goes here

### Example use cases

Use case description goes here

### List of sub tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by colemickens** [comment]
Sorry, fat fingered on my mobile...

**Comment by aanm** [comment]
@colemickens no worries. Let me know if this will solve problem https://github.com/cilium/cilium/issues/4314

**Comment by colemickens** [comment]
I had seen that. It seems to have more dependencies and operational
concerns than using CRDs as a data store, like some other
kubernetes-adjacent projects do. I'm also not aware of how much data Cilium
needs to store, though.  (I inquired on Slack as well...)
