### ISSUE TITLE
Proposal: Remove PodCIDR dependency in multi node routing

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4729]
This is not a concrete proposal yet but a dump of thoughts on this topic. It requires future research and discussion.

*Status Quo*

The datapath is aware of individual node CIDR ranges (PodCIDR) and will perform a lookup of `destinationIP/PodCIDR.Mask` to derive the destination node. This lookup is performed in the tunnel map and executed when the destination IP does not belong to a local endpoint.

This has the following advantages:
- The tunnel map remains small in size
- Routing can happen without requiring for all nodes to be aware of all endpoint IPs

This has the following disadvantages:
- We need to understand the PodCIDR structure and allocation
- This requires an additional BPF map lookup which can be avoided if we have to already do a ipcache lookup anyway for egress.
- This has limitations on IPAM model and is the only detail that binds us to requiring a host scope allocator

*Potential future options*
1. Stuff an endpoint_key into the ipcache and derive the destination node based on the ipcache
2. Listen to Pod or CEP notifications and build the initial version of the local ipcache based on this. This allows us to map PodIP to HostIP and establish a tunnel mesh without requiring to understand the full node structure.

This has the following advantages:
- We can support random IPAM
- We no longer need to understand the PodCIDR configuration
- We can support routing without requiring node discovery. We can route to any pod with a Cilium identity annotation.

This has the following disadvantages:
- We will only route once we have received the notification of that pod vs routing optimistically to the known destination node
- This requires us to build an ipcache of all possible remote IPs. This is not entirely unrealistic, even a BPF map with several M entries is feasible.

**Comment by PaulFurtado** [comment]
Any idea where this falls on the roadmap? Would really love to use cilium on AWS with the lyft-ipvlan plugin  or similar.

By dedicating an ec2 VPC subnet to kubernetes nodes, it's possible for us to carefully pre-allocate contiguous subnets to nodes, however, it'd be awesome to avoid needing to do that if you're planning on tackling this issue soon enough.

Thanks!

**Comment by tgraf** [comment]
@PaulFurtado Discussed this with some users at KubeCon. We will move this into 1.5

**Comment by tgraf** [comment]
This has been fully implemented in 1.5. The tunnel map still falls back to the PodCIDR and perform an optimistic route but only if the ipcache does not contain a tunnel endpoint.
