### ISSUE TITLE
Feature: Add filtering to cilium monitor

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#473]
Add ability to filter events
 - [ ] endpoint id / names
 - [ ] L3/L4 flow
 - [ ] event type (only show drops)

**Comment by aalemayhu** [comment]
@tgraf Have started looking at this, but some questions

- When you say `event type (only show drops)` you mean `.MessageTypeDrop`?
- Does this feature require changes in pkg/bpf/? Not sure yet if there is a need to expose
more things on the bpf / perf side.

Please elaborate on L3/L4 flow and endpoint names.

Thanks.

**Comment by tgraf** [comment]
Ability to say:
 - Show me all events which are triggered by packets coming from endpoint ID 110. Same for destination. Ability to filter on the network packet headers as provided in packet capture data.

If you run cilium monitor you see a lot of metadata that is being printed out. The idea is to be able to filter on that.
