### ISSUE TITLE
Fix CLI for service entries

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4758]
PR #4667 introduced a new usage of the connection tracker which resulted in more entries, with the new ones marked with `tuple->flags |= TUPLE_F_SERVICE`:

https://github.com/cilium/cilium/blob/b41f63a53582c9153ddc74ef167c7aa177643b39/bpf/lib/conntrack.h#L221

The CLI doesn't print this new information, however. It should be added to each of the IPv4, IPv6 global / local `Dump()` functions:

https://github.com/cilium/cilium/blob/b41f63a53582c9153ddc74ef167c7aa177643b39/pkg/maps/ctmap/ipv4.go#L66

https://github.com/cilium/cilium/blob/b41f63a53582c9153ddc74ef167c7aa177643b39/pkg/maps/ctmap/ipv4.go#L135

https://github.com/cilium/cilium/blob/b41f63a53582c9153ddc74ef167c7aa177643b39/pkg/maps/ctmap/ipv6.go#L66

https://github.com/cilium/cilium/blob/b41f63a53582c9153ddc74ef167c7aa177643b39/pkg/maps/ctmap/ipv6.go#L132

**Comment by ishantanu** [comment]
@joestringer Can you give an idea what needs to be written in the buffer for `TUPLE_F_SERVICE`? Is it something like `buffer.WriteString("service")` (similar to `TUPLE_F_RELATED`)?

**Comment by joestringer** [comment]
@iamShantanu101 apologies about the delay, I missed your message.

Yes, what you propose sounds like a good option.
