### ISSUE TITLE
The Istio sidecar proxy image name is not configurable

### ISSUE THREAD

**Issue by rlenglet** [cilium/cilium#4760]
The sidecar proxy mode is enabled automatically for a k8s endpoint if:
- the pod has the `sidecar.istio.io/status` annotation
- the pod has a container named `istio-proxy`
- the `istio-proxy` container uses an image which names contains the string `cilium/istio_proxy`
- the `istio-proxy` container mounts `/var/run/cilium`

The issue is that the container image name is hardcoded, which prevents using compatible third-party images.
Make the image name regexp configurable with a `sidecar-istio-proxy-image` flag.

**Comment by vsxen** [comment]
what is the different between istio/proxy and cilium/proxy?

and use https://github.com/cilium/istio will inject istio-proxy container mounts /var/run/cilium？
