### ISSUE TITLE
policy: decouple configuration updates of an endpoint from generation of policy for that endpoint

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4767]
Currently, configuration updates are coupled with policy regeneration:

https://github.com/cilium/cilium/blob/master/pkg/endpoint/policy.go#L436

This is because regeneratePolicy has been used to determine whether we should regenerate the BPF program for the endpoint or not:

https://github.com/cilium/cilium/blob/8d15cc962c44b3a8461c54e542eaa7395f787257/pkg/endpoint/policy.go#L786-L812

With changes like https://github.com/cilium/cilium/pull/4724 going into Cilium, need for regeneration of BPF for an endpoint based off of policy change for that endpoint is becoming less and less common. The thread after  https://github.com/cilium/cilium/pull/4724#issuecomment-402542338 specifies that with newer kernels, we can even decouple generation of BPF entirely from policy updates, which only require configuration of the PolicyMaps, and of the proxy. 

Thus, checking whether regeneratePolicy returns "true" is somewhat outdated; we only need to recompile the BPF program for an endpoint if the configuration has changed for that endpoint. One small caveat here, is that based off of the generated policy for the endpoint, we currently override the configuration options provided by the user:

https://github.com/cilium/cilium/blob/8d15cc962c44b3a8461c54e542eaa7395f787257/pkg/endpoint/policy.go#L564-L606

Whether overriding the configuration options is the correct thing is another question, but it is the current behavior.

Instead of regenerating policy when updating these configuration values though, we can check the existing policy which has been generated for the endpoint; if we need to override the configuration provided by the user, we can do so. Given that we have a small set of configuration options that are even available for the endpoint, we can iterate over the options provided by the user and only check the policy for the endpoint if necessary.

The current options for the endpoint that affect the policy which is generated for it (and vice-versa) include: 

* ConnTrack
    - Enabled if L4 Policy is enabled: https://github.com/cilium/cilium/blob/8d15cc962c44b3a8461c54e542eaa7395f787257/pkg/endpoint/policy.go#L575-L581
* Policy enforcement
    - Depending upon the daemon's policy enforcement mode, we override the endpoint's policy enforcement mode. See https://github.com/cilium/cilium/issues/2199 

So, I think we can make the change as follows in the code:

* configuration update is received for the endpoint
    - if configuration can affect policy (either of the two above options), check the policy that is generated for the endpoint, and override if needed(?)
        -  If no change *to these options only*, do not regenerate policy
        -  If change to these options, regenerate policy. 
    - If configuration does not affect policy (not the two above options), just apply the configuration.
* if there is a net configuration change for the endpoint (i.e., options have changed even after being overridden), regenerate BPF program for the endpoint.

**Comment by aanm** [comment]
Related with https://github.com/cilium/cilium/issues/2496

**Comment by ianvernon** [comment]
Now that policy updates do not affect the configuration of an endpoint, (#5294), this is being done over a variety of tickets:

* https://github.com/cilium/cilium/pull/5410
* https://github.com/cilium/cilium/pull/5324

This means that policy generation is no longer aware of endpoint configuration at all.

**Comment by ianvernon** [comment]
#5410 and #5324 have decoupled endpoint configuration updates from endpoint policy generation. Closing this.
