### ISSUE TITLE
Vagrant assumes that this means the command failed! /sbin/ifdown eth1 2> /dev/null

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#478]
If you are seeing the following error when running `contrib/vagrant/start.sh`:
```
==> cilium-master: Setting hostname...
==> cilium-master: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
/sbin/ifdown eth1 2> /dev/null
Stdout from the command:
Stderr from the command:
mesg: ttyname failed: Inappropriate ioctl for device
```

**Cause:**
This is an known vagrant issue with the Ubuntu 16.10 image
https://github.com/mitchellh/vagrant/issues/6871

**Solution:**
Upgrade to >= vagrant 1.8.5

**Comment by dunnleaddress** [comment]
@tgraf Your solution works for me thank you so much. As well here is instruction how to upgrade vagrant to a specific version https://stackoverflow.com/questions/46998883/upgrading-vagrant-in-ubuntu-16-04

**Comment by aceqbaceq** [comment]
i can confirm that upgrading vagrant version has solved the error
