### ISSUE TITLE
dns is very slow and ns lookup timeout in standalone k8s  

### ISSUE THREAD

**Issue by swimablefish** [cilium/cilium#4782]
### Title

DNS is very slow and lookup domain name timeout in standalone k8s.  

### General Information

- Cilium version (run `cilium version`): 1.1.0
- Kernel version (run `uname -a`):Linux ip-10-12-3-68 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): k8s 1.10.2
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

### How to reproduce the issue

1. Start a standalone k8s node
2. Our program will keep downloading images from different urls
3. After a while(3 ~ 5 hours), our program will report lookup domain name timeout
4. If we use flannel, that won't happen

**Comment by swimablefish** [comment]
[cilium-sysdump-20180709-031858.zip](https://github.com/cilium/cilium/files/2174562/cilium-sysdump-20180709-031858.zip)

**Comment by raybejjani** [comment]
@swimablefish do you recall any pods that had the timeouts? and perhaps the times?
Separately, I have some more general questions:
1- Did you update the K8s NetworkPolicy (or CiliumNetworkPolicy) regularly 30 minutes or so before you took the dump?
I see a bursts of regenerations of both DNS pods every few seconds starting at `2018-07-09T02:21:26.892598062Z`. They all complete quickly so it shouldn't be a problem (the policy likely did no impact those pods hence the no-op) but I want to rule out a bug in the policy sync.

2- Do you recall a specific pod having a timeout at a specific time (or rough time, even!).
When a pod is new, and cilium hasn't fully synced its label information it receives a `reserved:init` identity that has its own policy. When this is the case the pod may have no connectivity. This should usually switch to the real identity (and policy) quickly, but system load or a long build queue might cause it to take a little longer (this may be related to the policy churn seen in (1) but for pods impacted by the policy change they may not keep up when building).


I noticed errors like `2018-07-09T02:19:55.340081129Z level=warning msg="Regeneration of endpoint program failed" containerID=cilium-loc endpointID=44994 error="Unable to rename current endpoint directory: rename /var/run/cilium/state/44994 /var/run/cilium/state/44994_stale: no such file or directory" ipv4=172.16.0.84 ipv6="f00d::ac10:0:0:afc2" k8sPodName=":" policyRevision=0` and that is a little odd, but it seems to be transient (that endpoint is a cilium internal healthcheck endpoint so it isn't critical)

**Comment by tgraf** [comment]
> I noticed errors like 2018-07-09T02:19:55.340081129Z level=warning msg="Regeneration of endpoint program failed" containerID=cilium-loc endpointID=44994 error="Unable to rename current endpoint directory: rename /var/run/cilium/state/44994 /var/run/cilium/state/44994_stale: no such file or directory" ipv4=172.16.0.84 ipv6="f00d::ac10:0:0:afc2" k8sPodName=":" policyRevision=0 and that is a little odd, but it seems to be transient (that endpoint is a cilium internal healthcheck endpoint so it isn't critical)

The above error in the log is a known harmless bug (#4652) and will be fixed in the next release.

**Comment by tgraf** [comment]
@swimablefish Do you happen to have a tcpdump capture of a slow DNS request?

I couldn't spot anything unusual in the sysdump besides the conntrack table being somewhat large with 200K entries. This could indicate that TCP connections are not closed properly or Cilium doesn't see the connection close properly.

**Comment by swimablefish** [comment]
@raybejjani 
1. I didn't update update the K8s NetworkPolicy (or CiliumNetworkPolicy)
2. Is there default timeout for the system, in my log, it doesn't show the timeout
: dial tcp: lookup my-live.slatic.net on 10.254.0.10:53: read udp
Http Get failed, Get https://my-live.slatic.net/original/ae3b8b2ae8edb9721249ff08b7ba688e.jpg: dial tcp: lookup my-live.slatic.net on 10.254.0.10:53: read udp 172.16.0.237:46000->10.254.0.10:53: i/o timeout

**Comment by raybejjani** [comment]
@swimablefish The default timeout would depend on your system. It's a few seconds usually (perhaps a little more, 5 seconds). The line you posted looks like a DNS timeout, where it did not receive a response (I'm assuming `172.16.0.237` is the  IP of the pod that gave you this log).
You can configure the timeout in `resolv.conf` inside the container image (see http://man7.org/linux/man-pages/man5/resolv.conf.5.html) but depending on the runtime of your server, it may not derive configuration from there. It is likely that resolv.conf is being used, since it is written by kubernetes with the 172.254.0.10 address.

You can also look at the kubedns logs to see if it received the requests. You may have to run in a more verbose mode, however. I think the option is per-container and you might need `-v=5` for both the kubedns and dsnmasq containers.

Finally, related to your other issue (https://github.com/cilium/cilium/issues/4781) did this occur with the `--disable-conntrack` option? I'll post more information in https://github.com/cilium/cilium/issues/4781 and https://github.com/cilium/cilium/issues/4814.

**Comment by tgraf** [comment]
Likely a dup of #4853

**Comment by tgraf** [comment]
@swimablefish Are you still seeing this with the latest 1.2.3 release? We have not been able to reproduce this.

**Comment by tgraf** [comment]
Closing for now, please reopen if problem is being observed again.
