### ISSUE TITLE
Unable to Start Cilium on GCP K8s Cluster 

### ISSUE THREAD

**Issue by KSanthanam** [cilium/cilium#4794]
I tried running cilium inside GCP's Kubernetes Cluster (version 1.10.5-gke.0) with but I get error in creating the cilium pods.

> Error: failed to start container "cilium-agent": Error response from daemon: error while creating mount source path '/opt/cni/bin': mkdir /opt/cni: read-only file system

Attached are the description of the cluster and pod
**Cilium Pod Desc**
 
Name:           cilium-7rfcx
Namespace:      kube-system
Node:           gke-cluster-exchange-default-pool-032aad99-062c/10.152.0.3
Start Time:     Tue, 10 Jul 2018 15:09:34 +1000
Labels:         controller-revision-hash=822413316
                k8s-app=cilium
                kubernetes.io/cluster-service=true
                pod-template-generation=1
Annotations:    prometheus.io/port=9090
                prometheus.io/scrape=true
                scheduler.alpha.kubernetes.io/critical-pod=
                scheduler.alpha.kubernetes.io/tolerations=[{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]
Status:         Running
IP:             10.152.0.3
Controlled By:  DaemonSet/cilium
Init Containers:
  clean-cilium-state:
    Container ID:  docker://e147ea8e094ab0a805caee0c39c71fbcbe7622da2f8334a2a76ce6b4f96653ef
    Image:         docker.io/library/busybox:1.28.4
    Image ID:      docker-pullable://busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      if [ "${CLEAN_CILIUM_STATE}" = "true" ]; then rm -rf /var/run/cilium/state; rm -rf /sys/fs/bpf/tc/globals/cilium_*; fi
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 10 Jul 2018 15:09:34 +1000
      Finished:     Tue, 10 Jul 2018 15:09:34 +1000
    Ready:          True
    Restart Count:  0
    Environment:
      CLEAN_CILIUM_STATE:  <set to the key 'clean-cilium-state' of config map 'cilium-config'>  Optional: true
    Mounts:
      /sys/fs/bpf from bpf-maps (rw)
      /var/run/cilium from cilium-run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cilium-token-ff7wg (ro)
Containers:
  cilium-agent:
    Container ID:  docker://4b2c9d48de4ca710d71c84d42d711e601e0db2320e3bf9178a5e253ad721c266
    Image:         docker.io/cilium/cilium:latest
    Image ID:      docker-pullable://cilium/cilium@sha256:9c8e1a29ec4696a79a6a894bb24d8d0983616c2dfd130ada241ab7456ebfdf27
    Port:          9090/TCP
    Host Port:     9090/TCP
    Command:
      cilium-agent
    Args:
      --debug=$(CILIUM_DEBUG)
      --kvstore=etcd
      --kvstore-opt=etcd.config=/var/lib/etcd-config/etcd.config
      --disable-ipv4=$(DISABLE_IPV4)
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      error while creating mount source path '/opt/cni/bin': mkdir /opt/cni: read-only file system
      Exit Code:    128
      Started:      Tue, 10 Jul 2018 15:10:20 +1000
      Finished:     Tue, 10 Jul 2018 15:10:20 +1000
    Ready:          False
    Restart Count:  3
    Liveness:       exec [cilium status] delay=120s timeout=1s period=10s #success=1 #failure=10
    Readiness:      exec [cilium status] delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:
      K8S_NODE_NAME:                     (v1:spec.nodeName)
      CILIUM_DEBUG:                     <set to the key 'debug' of config map 'cilium-config'>                          Optional: false
      DISABLE_IPV4:                     <set to the key 'disable-ipv4' of config map 'cilium-config'>                   Optional: false
      CILIUM_PROMETHEUS_SERVE_ADDR:     <set to the key 'prometheus-serve-addr' of config map 'cilium-metrics-config'>  Optional: true
      CILIUM_LEGACY_HOST_ALLOWS_WORLD:  <set to the key 'legacy-host-allows-world' of config map 'cilium-config'>       Optional: true
      CILIUM_TUNNEL:                    <set to the key 'tunnel' of config map 'cilium-config'>                         Optional: true
    Mounts:
      /host/etc/cni/net.d from etc-cni-netd (rw)
      /host/opt/cni/bin from cni-path (rw)
      /sys/fs/bpf from bpf-maps (rw)
      /var/lib/etcd-config from etcd-config-path (ro)
      /var/lib/etcd-secrets from etcd-secrets (ro)
      /var/run/cilium from cilium-run (rw)
      /var/run/docker.sock from docker-socket (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from cilium-token-ff7wg (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  cilium-run:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/cilium
    HostPathType:  
  bpf-maps:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/bpf
    HostPathType:  
  docker-socket:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  
  cni-path:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  
  etc-cni-netd:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  etcd-config-path:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      cilium-config
    Optional:  false
  etcd-secrets:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cilium-etcd-secrets
    Optional:    true
  cilium-token-ff7wg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cilium-token-ff7wg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
Events:
  Type     Reason                 Age                From                                                      Message
  ----     ------                 ----               ----                                                      -------
  Normal   Started                1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  Started container
  Normal   SuccessfulMountVolume  1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  MountVolume.SetUp succeeded for volume "docker-socket"
  Normal   SuccessfulMountVolume  1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  MountVolume.SetUp succeeded for volume "etc-cni-netd"
  Normal   SuccessfulMountVolume  1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  MountVolume.SetUp succeeded for volume "cni-path"
  Normal   SuccessfulMountVolume  1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  MountVolume.SetUp succeeded for volume "bpf-maps"
  Normal   SuccessfulMountVolume  1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  MountVolume.SetUp succeeded for volume "etcd-config-path"
  Normal   SuccessfulMountVolume  1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  MountVolume.SetUp succeeded for volume "etcd-secrets"
  Normal   SuccessfulMountVolume  1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  MountVolume.SetUp succeeded for volume "cilium-token-ff7wg"
  Normal   Pulled                 1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  Container image "docker.io/library/busybox:1.28.4" already present on machine
  Normal   Created                1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  Created container
  Normal   SuccessfulMountVolume  1m                 kubelet, gke-cluster-exchange-default-pool-032aad99-062c  MountVolume.SetUp succeeded for volume "cilium-run"
  Normal   Pulling                47s (x3 over 1m)   kubelet, gke-cluster-exchange-default-pool-032aad99-062c  pulling image "docker.io/cilium/cilium:latest"
  Normal   Pulled                 47s (x3 over 1m)   kubelet, gke-cluster-exchange-default-pool-032aad99-062c  Successfully pulled image "docker.io/cilium/cilium:latest"
  Normal   Created                47s (x3 over 1m)   kubelet, gke-cluster-exchange-default-pool-032aad99-062c  Created container
  Warning  Failed                 47s (x3 over 1m)   kubelet, gke-cluster-exchange-default-pool-032aad99-062c  Error: failed to start container "cilium-agent": Error response from daemon: error while creating mount source path '/opt/cni/bin': mkdir /opt/cni: read-only file system
  Warning  BackOff                34s (x2 over 56s)  kubelet, gke-cluster-exchange-default-pool-032aad99-062c  Back-off restarting failed container

**Cluster Description**
addonsConfig:
  horizontalPodAutoscaling: {}
  httpLoadBalancing: {}
  kubernetesDashboard:
    disabled: true
  networkPolicyConfig: {}
clusterIpv4Cidr: 10.40.0.0/14
createTime: '2018-07-10T04:46:03+00:00'
currentMasterVersion: 1.10.5-gke.0
currentNodeCount: 3
currentNodeVersion: 1.10.5-gke.0
endpoint: 35.197.168.49
initialClusterVersion: 1.10.5-gke.0
instanceGroupUrls:
- https://www.googleapis.com/compute/v1/projects/crypto-exchange-fin-x/zones/australia-southeast1-a/instanceGroupManagers/gke-cluster-exchange-default-pool-032aad99-grp
labelFingerprint: a9dc16a7
legacyAbac: {}
locations:
- australia-southeast1-a
loggingService: logging.googleapis.com
masterAuth:
  clientCertificate: ***
  clientKey: ***==
  clusterCaCertificate: ***
  password: ****
  username: admin
monitoringService: monitoring.googleapis.com
name: cluster-exchange
network: default
networkConfig:
  network: projects/crypto-exchange-fin-x/global/networks/default
  subnetwork: projects/crypto-exchange-fin-x/regions/australia-southeast1/subnetworks/default
networkPolicy:
  enabled: true
  provider: CALICO
nodeConfig:
  diskSizeGb: 100
  diskType: pd-standard
  imageType: COS
  machineType: n1-standard-4
  oauthScopes:
  - https://www.googleapis.com/auth/compute
  - https://www.googleapis.com/auth/devstorage.read_only
  - https://www.googleapis.com/auth/logging.write
  - https://www.googleapis.com/auth/monitoring
  - https://www.googleapis.com/auth/service.management.readonly
  - https://www.googleapis.com/auth/servicecontrol
  - https://www.googleapis.com/auth/trace.append
  serviceAccount: default
nodeIpv4CidrSize: 24
nodePools:
- config:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS
    machineType: n1-standard-4
    oauthScopes:
    - https://www.googleapis.com/auth/compute
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/service.management.readonly
    - https://www.googleapis.com/auth/servicecontrol
    - https://www.googleapis.com/auth/trace.append
    serviceAccount: default
  initialNodeCount: 3
  instanceGroupUrls:
  - https://www.googleapis.com/compute/v1/projects/crypto-exchange-fin-x/zones/australia-southeast1-a/instanceGroupManagers/gke-cluster-exchange-default-pool-032aad99-grp
  management: {}
  name: default-pool
  selfLink: https://container.googleapis.com/v1beta1/projects/crypto-exchange-fin-x/zones/australia-southeast1-a/clusters/cluster-exchange/nodePools/default-pool
  status: RUNNING
  version: 1.10.5-gke.0
selfLink: https://container.googleapis.com/v1beta1/projects/crypto-exchange-fin-x/zones/australia-southeast1-a/clusters/cluster-exchange
servicesIpv4Cidr: 10.43.240.0/20
status: RUNNING
subnetwork: default
zone: australia-southeast1-a

**Comment by tgraf** [comment]
The reason seems to be this:
```
Message: error while creating mount source path '/opt/cni/bin': mkdir /opt/cni: read-only file system
```

**Comment by raybejjani** [comment]
@KSanthanam The fix is merged and will be in our next release. I'm closing this for now. Thank you for the bug report!

**Comment by KSanthanam** [comment]
Hi @tgraf and @raybejjani thank you for fixing this. Fantastic! I will test on next version.

**Comment by KSanthanam** [comment]
Hi @tgraf How do I use your version with the fix?

**Comment by raybejjani** [comment]
@KSanthanam It will be in the `cilium/v1.2` image, but that hasn't been released. In the meantime, you can try it with `cilium/latest` but note that that image tag changes very often (so I only recommend testing and not production).

**Comment by tgraf** [comment]
@KSanthanam We can backport it to 1.1 as well.

**Comment by dorkolog** [comment]
@KSanthanam I was also trying to deploy cilium on GKE. 

In my case -  GKE uses non default locations for cni binaries so I had to change the ``containers.mountPath`` for ``cni-path``  and the ``volumes.hostPath`` for ``cni-path`` in order to ``cni-install.sh`` to work properly. 
Also, the ``kubelet.service`` is configured with ``--network-plugin=kubenet``. 

Unfortunately I haven't find a way to configure it prior of launching the cluster so I changed it manually at restarted kubelet service (``systemctl restart kubelet.service``).

**Comment by KSanthanam** [comment]
@dorkolog Thank you for your feedback.  @tgraf has fixed it. I am waiting for the next release. Hopefully we don't have to do this manually

**Comment by tgraf** [comment]
@dorkolog Can you share what you changed it to? We will publish a guide to provide the alternative locations. We can't change the defaults as the defaults correspond to the official Kubernetes paths and work on all self managed installations.

**Comment by dorkolog** [comment]
@tgraf 
volumes.cni-path - /host/opt/cni/bin -> /home/kubernetes/bin, as GKE configures kubelet with ``--cni-bin-dir=/home/kubernetes/bin``. I thought I had another config change but it seems thats only one.

the other steps mentioned above (configuring ``kubelet.service`` and restarting) are still needed.
