### ISSUE TITLE
--disable-conntrack incorrectly disables/breaks load-balancing

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#4814]
From triaging https://github.com/cilium/cilium/issues/4781

I tested this in minikube on both 1.1.0 and lastest. Both exhibited this behaviour. I'm not sure if this is intended. If so we should simply document it. If not, a more involved fix is needed. I suspect this is intended behaviour based on https://github.com/cilium/cilium/pull/4667 but I'm not sure.

### How to reproduce the issue
Following http://cilium.readthedocs.io/en/latest/gettingstarted/minikube/
1. setup the etcd
2. Setup cilium
Add `- "--disable-conntrack"` to the cilium daemonset. This can also be done on a running cilium pod.
3. Run the demo pods
3. Try to make a connection to a service frontend IP (`xwing` to `deathstar`) . This will fail. 
Note: use `kubectl get svc` to get the actual IP since the DNS will be broken.
4. Try to make a connection to a service backend IP. This will work
Note: Grab this with `kubectl get pods -o wide`

**Comment by raybejjani** [comment]
After some offline discussion it seems LB depends on conntrack, at least for endpoint to LB-backend session pinning. As such, it's unfortunately intended behaviour.

I'll update our LB docs to make this clear.

**Comment by aanm** [comment]
Maybe we should consider removing/deprecate this option as no one has a use case for this? cc @tgraf

**Comment by tgraf** [comment]
> Maybe we should consider removing/deprecate this option as no one has a use case for this?

Agreed. Since requiring conntrack for consistent hashing for load-balancing, conntrack is not really optional anymore unless load-balancing is disabled.
