### ISSUE TITLE
Error regenerating endpoint: Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4818]
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1212/testReport/k8s-1/7/K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo/

[9acb0442_K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip](https://github.com/cilium/cilium/files/2184375/9acb0442_K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip)

Error reported:
```
Timeout reached: cannot change state of resource correctly; command timed out
```

Underlying problem: Endpoints are not reaching the desired policy revision
```
Waiting for endpoints to run policy revision 77: 0/5
```

Reason build does not succeed:
```
Error regenerating endpoint: Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded
```

**Comment by tgraf** [comment]
System is subject to high load while test fails:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %!C(MISSING)PU %!M(MISSING)EM     TIME+ COMMAND
10538 root      20   0  346596  17868  12060 R  25.0  0.6   0:00.04 cilium
10543 root      20   0  346596  17632  12060 R  25.0  0.6   0:00.04 cilium
10542 root      20   0  345540  17060  12124 R  12.5  0.6   0:00.02 cilium
10544 root      20   0  345476  16808  12188 R  12.5  0.5   0:00.02 cilium
```

```
 23:23:53 up 49 min,  0 users,  load average: 9.72, 8.35, 6.44
```

**Comment by ianvernon** [comment]
@tgraf any insight into what is causing this high load? Number of concurrent regenerations, goroutines holding locks, etc.?

**Comment by tgraf** [comment]
Still debugging. Could be the same cause as #4815

**Comment by tgraf** [comment]
Fixed in master.
