### ISSUE TITLE
CI: all Cilium logs dumped to console results in Jenkins being unable to load

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4835]
We have a test helper to ensure that the logs for Cilium do not contain certain strings (panics, deadlocks, segfaults, NACKs from Envoy) to ensure that we are not glossing over potential regressions which Cilium recovers from upon restart: 
https://github.com/cilium/cilium/blob/272fb386c44157a06a126e3c5a50dbf2f40cf7e2/test/helpers/cilium.go#L636-L649

However, we make an assertion on the string containing the logs directly, which results in Ginkgo dumping the entire contents of Cilium logs to console, which are quite verbose because we run in debug mode in the CI. This makes it virtually impossible to load the Jenkins Console output for a build that fails if one of the unallowed strings is found in the logs. Instead, check first whether the logs contain the specified strings, and then make an assert on the result of the boolean, so that we do not dump the entire contents of the Cilium logs to console.

**Comment by eloycoto** [comment]
Will be fixed by: https://github.com/cilium/cilium/pull/4823

**Comment by eloycoto** [comment]
Fixed by https://github.com/cilium/cilium/pull/4823
