### ISSUE TITLE
Automatic policy for Kubernetes natives services such as kube-dns

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#495]
Add a `--kubernetes` flag which automatically takes care of allowing access to Kubernetes DNS, allows health checking to pods, ... without requiring the user to inject such policy manually.

**Comment by aanm** [comment]
Do we need the flag? I thought it should be automatic once we are connected to a kube-apiserver

**Comment by tgraf** [comment]
> Do we need the flag? I thought it should be automatic once we are connected to a kube-apiserver

I was hoping that we could derive the API server address from an environment variable. It must be available somehow. If we don't have an opt-in flag, then at least we need an opt-out flag to disable this behaviour.

**Comment by tgraf** [comment]
Given that namespace isolation is not coming, we should probably have a default policy which allows communication within and into "kube-system" namespace.

**Comment by tgraf** [comment]
It looks like Kubernetes upstream is going with the #788  approach which will make this unnecessary.

**Comment by aanm** [comment]
Fixed by #788
