### ISSUE TITLE
CNP output is missing `enforcing` key value pair for one of the nodes in a multi-node cluster

### ISSUE THREAD

**Issue by ashwinp** [cilium/cilium#4967]
### Title

kubectl get cnp output is missing `enforcing` key value pair in status>nodes section for one of the nodes in a multi-node cluster

### General Information

- Cilium version (run `cilium version`)
`v1.1.1`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.9", GitCommit:"57729ea3d9a1b75f3fc7bbbadc597ba707d47c8a", GitTreeState:"clean", BuildDate:"2018-06-29T01:07:01Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
### How to reproduce the issue

1. Run any getting started guide on a multi-node cluster in a continuous manner. You'll observe that one of the cilium agents gets into a state where it stops reporting the enforcing flag in the `kubectl get cnp` output.
```
    "status": {
        "nodes": {
            "ip-172-0-125-30.us-west-2.compute.internal": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": ====snip=====
                },
                "lastUpdated": "2018-07-24T16:56:51.595751474Z",
                "localPolicyRevision": 1238,
                "ok": true
            },
            "ip-172-0-189-174.us-west-2.compute.internal": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": ====snip=====
                },
                "enforcing": true,
                "lastUpdated": "2018-07-24T16:54:52.571476755Z",
                "localPolicyRevision": 1238,
                "ok": true
            },
            "ip-172-0-39-235.us-west-2.compute.internal": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": ====snip=====
                },
                "enforcing": true,
                "lastUpdated": "2018-07-24T16:54:54.241040249Z",
                "localPolicyRevision": 1236,
                "ok": true
            },
            "ip-172-0-41-94.us-west-2.compute.internal": {
                "annotations": {
                    "kubectl.kubernetes.io/last-applied-configuration": ====snip=====
                },
                "enforcing": true,
                "lastUpdated": "2018-07-24T16:54:45.494347441Z",
                "localPolicyRevision": 1236,
                "ok": true
            }
        }
    }
```

**Comment by nebril** [comment]
This one seems to be caused by this area of code:

https://github.com/cilium/cilium/blob/v1.1.1/daemon/k8s_watcher.go#L1369

`Enforcing` field has an `omitempty` tag: https://github.com/cilium/cilium/blob/v1.1.1/pkg/k8s/apis/cilium.io/v2/types.go#L89 , which means it won't populate json if it's not set to true.

The only combination of errors that can cause `Enforcing` to be false and `OK` to be true is if `waitForEPsErr` is not nil, while `err` and `err2` are nil. This seems to be a bug in logic, since `OK` should also be set to false if we encounter `waitForEpsErr`. Will file a PR.

**Comment by ianvernon** [comment]
What is the meaning of 'OK' vs. 'Enforcing'?

https://github.com/cilium/cilium/blob/def269753511ec8c8240d2eba3a989137797cd1d/pkg/k8s/apis/cilium.io/v2/types.go#L73-L74

https://github.com/cilium/cilium/blob/def269753511ec8c8240d2eba3a989137797cd1d/pkg/k8s/apis/cilium.io/v2/types.go#L86-L88

Can these two ever be different ? OK "is true when the policy has been installed successfully" - this is rather vague; by 'installed' does that mean 'inserted into the in-memory policy repository for the given cilium instance running on the specified node'?

**Comment by nebril** [comment]
@ianvernon  It seems like right now policy can be ok, but not all endpoints are enforcing it yet? Not sure what is the definition of OK too.

**Comment by ianvernon** [comment]
cc: @aanm can you provide insight as to what 'installed' means in this context?

**Comment by nebril** [comment]
Talked with @aanm, it seems like OK means that the policy got pulled into the node, and Enforcing means that all appropriate endpoints are actually enforcing this policy.

**Comment by ashwinp** [comment]
As part of this fix, can we also rename `ok` to `pulled` or something more explicit? Thanks!

**Comment by ianvernon** [comment]
Are we able to rename the field in the API? It is public.

We can update the documentation accordingly. @ashwinp given that OK does not mean that the endpoints were actually enforcing the policy, was the policy actually enforced on the node which did not have 'Enforcing' set to 'true'? There may be a BPF compilation issue for an endpoint on that node, proxy configuration issue, etc.

**Comment by tgraf** [comment]
We can't rename the field. It's public API.

**Comment by ianvernon** [comment]
#4492 will always set the `Enforcing` field to `true` or `false`.
