### ISSUE TITLE
Add --ipv4-cluster-alloc-cidr option to specify IPv4 cluster prefix

### ISSUE THREAD

**Issue by anitgandhi** [cilium/cilium#4975]
### Description of requested functionality

I think it would be useful to have functionality like #4313 but for ipv4. 

### Example use cases

I'd like to specify an overall cluster CIDR for k8s pods. I can't use the `--allocate-node-cidrs` because I don't want the cloud provider to be aware of the overlay CIDR. The alternative is to specify `--ipv4-range` on each node's cilium-agent, but that's not easy to distribute via ConfigMaps in a unique way. 

The `--ipv4-cluster-cidr-mask-size` is insufficient because I may want to choose a non 10.0.0.0/8 based CIDR, perhaps a different RFC1918 CIDR that I know will not conflict with any other valid IP range in my corporate network. 

According to [this page](https://cilium.readthedocs.io/en/v1.1/concepts/#address-management), a node's cluster cidr subnet is chosen based on the last octet of effectively, the eth0 cidr. This means it could pick a node cidr that may conflict with another subnet in my larger private network, which would create a routing ambiguity.

**Comment by tgraf** [comment]
> I'd like to specify an overall cluster CIDR for k8s pods. I can't use the --allocate-node-cidrs because I don't want the cloud provider to be aware of the overlay CIDR. The alternative is to specify --ipv4-range on each node's cilium-agent, but that's not easy to distribute via ConfigMaps in a unique way.

Makes sense.

> According to this page, a node's cluster cidr subnet is chosen based on the last octet of effectively, the eth0 cidr. This means it could pick a node cidr that may conflict with another subnet in my larger private network, which would create a routing ambiguity.

Agreed. This is meant as a default to get a cluster up and running without providing any configuration. We are thinking about deprecating this behavior.

Can you clarify about what you want specifically? IPv6 has the benefit that we can use a full public IPv4 address in the IPv6 prefix to make it unique. For IPv4, we will probably need a more sophisticated allocation logic.

Let's assume we add `--ipv4-cluster-alloc-cidr=10.10.0.0/16` option to define a base prefix. We would probably need an additional parameter to specify the size of the per node CIDR, let's assume this is `--ipv4-node-cidr-size=24`. This would then mean we need to allocate the unique per node portion. This could be done in several ways:

**kvstore:**
Using the existing allocator which would allocate the X in `10.10.x.0/24`. The existing lease based system would allow to reuse CIDRs which have been claimed by agents that then disappeared and never reappear.

**k8s CRD:**
Have a tool which populates a CRD for each available node CIDR and let agents claim from this pool. This has the advantage of not depending on the kvstore but it becomes more difficult to garbage collector CIDR that have been claimed by nodes that then disappear and never disappear.

**Node annotations:**
We offload the problem entirely to the use and require to annotate the k8s node resource with the PodCIDR to be used. This could be done today already.

**Comment by anitgandhi** [comment]
> Let's assume we add --ipv4-cluster-alloc-cidr=10.10.0.0/16 option to define a base prefix. We would probably need an additional parameter to specify the size of the per node CIDR, let's assume this is --ipv4-node-cidr-size=24

I was thinking exactly along these lines. If these 2 options are added, then that would preclude the use of either `--ipv4-range` on a per-node basis, and/or the `--ipv4-cluster-cidr-mask-size` as well. Just to give another concrete example, I may want to use a different RFC1918 space is like `192.168.0.0/16` for my base prefix, to absolutely ensure there are no conflicts with the rest of the network. 

I assume the existing behavior around `--ipv4-range` uses the kvstore option, and I've had good luck with that already. My personal take is that the kvstore option is best, since it doesn't directly get coupled to k8s then, just the kvstore. In theory, there could be situations where a user might want to use cilium with plain Docker containers and k8s using Docker for its choice of container runtime. The kvstore option feels generic enough to support this.

**Comment by anitgandhi** [comment]
For what it's worth... I was able to use `--allocate-node-cidrs` to fix my issue in tandem with the `--configure-cloud-routes=false` flag, but I think having the option of the same behavior manually with the above additions is still worth it.

**Comment by tgraf** [comment]
The CRD based IPAM made available in the 1.6 release allows to plug in arbitrary specification of PodCIDR or list of IPs for pods on a particular node.

**Comment by rnsv** [comment]
My existing cidr range for pods is 172.24.0.0/13.  I am using weave and want to test with cilium.  What should be the appropriate args that I need to pass to cilium-agent.
