### ISSUE TITLE
Cannot update CEP: StorageError: invalid object

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4979]
Likely not a serious error so the work here may be to hide this error to not raise unnecessary concerns:

```
level=error msg="Cannot update CEP" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (45702)" endpointID=45702 error="Operation cannot be fulfilled on ciliumendpoints.cilium.io \"cilium-health-ip-172-0-52-103.us-west-2.compute.internal\": StorageError: invalid object, Code: 4, Key: /registry/cilium.io/ciliumendpoints/kube-system/cilium-health-ip-172-0-52-103.us-west-2.compute.internal, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 9118baef-8e28-11e8-a7dc-029cdb62bcae, UID in object meta: " ipv4=10.2.1.195 ipv6="f00d::a02:100:0:b286" k8sPodName=":" policyRevision=0
```

**Comment by raybejjani** [comment]
@tgraf Did this resolve after a while? Did it happen with any other endpoints? (this one was a cilium-health EP)
I have, in any case, just disabled the CEP for the cilium-health endpoint in #4981

**Comment by tgraf** [comment]
@raybejjani Yes, the error was temporary. I'm going through log files of testing clusters and looking for errors. We should try and only emit on real issues.

**Comment by raybejjani** [comment]
hmm... if it "never" happens with normal endpoints, I'd rather not suppress any errors. If we do see it on the non-health EPs then I'll start only emitting the error if it fails for some minutes... In the case of the CEPs, I'm worried that they may not be updated and that would be unclear during a debug.
