### ISSUE TITLE
CI: Make sure that cleanups happens

### ISSUE THREAD

**Issue by eloycoto** [cilium/cilium#5008]
Had a chat with @joestringer about the cleanup, we should make sure that the cleanup happens and fails if something fail: 

- On AfterEach the ExpectSuccess should not happen. 
- We should have something like send a string to CheckLog in the afterEach and fail in the global AfterEach. 
- All the test will try to cleanup, but we fail just in the finish.

**Comment by joestringer** [comment]
The underlying context for this issue is now lost and there has been a lot of time in between. If any equivalent issue affects the latest codebase, I would suggest opening a fresh issue and we can target the specific cases that need improvement.

Closing.
