### ISSUE TITLE
Authentication based network policy between endpoints

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#502]
Network policy is currently based on the identity carried in the network packet. This requires to either encrypt or trust the underlying network to provide the right identity. A host that has been compromised could present itself as an arbitrary identity.

This issue tracks the addition of:
 - [ ] Ability to specify a certificate or IPSec key in the policy which must be hold by the sender
 - [ ] Enforcement of authentication based security.

**Comment by danehans** [comment]
It would be nice to see a reference implementation for Istio. For example, to use Istio’s application layer policies to interact with the network-layer policies as used by Cilium and the Kubernetes Network Policy API.

**Comment by darkdatter** [comment]
Are there any updates/details on this feature's progress?

**Comment by tgraf** [comment]
@MS52390 @jrfastab is working on this right now. Progress will be tracked in #504
