### ISSUE TITLE
Wait to restore endpoints until k8s CNP and NP informer have listed the already loaded policy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5038]
This ensures that restored endpoints are loaded with currently installed policies instead of dropping all traffic or enforcing based on an incomplete policy repository.

**Comment by ianvernon** [comment]
Been working on this, had to familiarize myself with a bunch of the K8s code. Will have a fix soon, hopefully by Monday.

**Comment by aanm** [comment]
This can still happen. I've re-open it.

**Comment by ianvernon** [comment]
@aanm can you clarify?

**Comment by aanm** [comment]
@ianvernon https://github.com/cilium/cilium/pull/5486#issue-213324402

**Comment by tgraf** [comment]
@aanm Fantastic catch!
