### ISSUE TITLE
Avoid cgo in dependencies used by cilium-cni

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5055]
Use of cgo prevents proper static linking of `cilium-cni` and thus prevents use of `cilium-cni` on non-glibc based host platforms.

**Comment by ianvernon** [comment]
I've fixed one dependency locally (use of `pkg/node` in `pkg/endpoint/connector`), by moving `pkg/node/defaults.go` to `pkg/defaults/node.go`. Thereare multiple transitive dependencies that use cgo, based on the use of [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints). I managed to get `cilium-cni` to compile locally with `CGO_ENABLED=0` provided as part of the `go build` command for `cilium-cni`:

```
$ CGO_ENABLED=0 go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.2.90 0385c51a0 2018-08-15T15:53:08-07:00 go version go1.10.3 linux/amd64"' -o cilium-cni ./cilium-cni.go
$ # compiled successfully
```

For more information about this environment variable, see: https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command

> You can control this by setting the CGO_ENABLED environment variable when running the go tool: set it to 1 to enable the use of cgo, and to 0 to disable it. The go tool will set the build constraint "cgo" if cgo is enabled.

Compare this with trying to build `cilium-cni` off of latest master by disabling `cgo`:
```
$ CGO_ENABLED=0 go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.2.90 0385c51a0 2018-08-15T15:53:08-07:00 go version go1.10.3 linux/amd64"' -o cilium-cni ./cilium-cni.go
# github.com/cilium/cilium/pkg/bpf
../../pkg/bpf/bpffs.go:82:4: undefined: log
../../pkg/bpf/bpffs.go:92:3: undefined: log
../../pkg/bpf/bpffs.go:138:2: undefined: log
../../pkg/bpf/bpffs.go:275:3: undefined: log
../../pkg/bpf/bpffs.go:292:4: undefined: log
../../pkg/bpf/bpffs.go:321:4: undefined: log
../../pkg/bpf/bpffs.go:338:4: undefined: log
../../pkg/bpf/bpffs.go:341:3: undefined: log
../../pkg/bpf/map.go:335:13: undefined: ObjGet
../../pkg/bpf/map.go:396:20: undefined: OpenOrCreateMap
../../pkg/bpf/map.go:396:20: too many errors
```

Does this fulfill the expectations of this issue @tgraf ?

**Comment by ianvernon** [comment]
I will add `CGO_ENABLED=0` to the build flags for `cilium-cni` as part of this effort too.

**Comment by tgraf** [comment]
> Does this fulfill the expectations of this issue @tgraf ?

100%. Awesome. This will allow us to run on non glibc hosts.
