### ISSUE TITLE
Vagrant Kubernetes Demo only works with IPV4 Disabled

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#506]
Currently running the kubernetes vagrant demo requires the IPV4=0 flag, otherwise cilium-agent hangs while waiting for etcd to start, as etcd is failing with the error message: 

Apr 02 11:19:50 cilium-k8s-master etcd[4623]: listen tcp [fd00::b]:2380: bind: cannot assign requested address

The cilium-agent log has the following error: 

 NewEtcdClient > Waiting for etcd client to be ready...

**Comment by aanm** [comment]
@danwent I can't replicate this I ran:
```
K8S=1 ./contrib/vagrant/start.sh
```
and inside the VM I get:
```
$ kubectl get cs 
NAME                 STATUS    MESSAGE              ERROR
etcd-0               Healthy   {"health": "true"}   
controller-manager   Healthy   ok                   
scheduler            Healthy   ok
```

**Comment by ianvernon** [comment]
Similar to @aanm , I get:
```
vagrant@cilium-k8s-master:~/go/src/github.com/cilium/cilium$ kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
scheduler            Healthy   ok                   
etcd-0               Healthy   {"health": "true"} 
```

The logs do show the message @danwent saw, but then immediately after show that the client is ready:
```
May 12 15:16:52 ubuntu cilium-agent[13286]: INFO Waiting for etcd client to be ready...
May 12 15:16:52 ubuntu cilium-agent[13286]: INFO Etcd client ready
```

No such string "cannot assign requested address" appears in the startup of the VM / in /var/log/syslog. Looks like this might no longer be an issue?

**Comment by tgraf** [comment]
Let's close it for now. We can reopen when it reappears.
