### ISSUE TITLE
CI: remove need to manually update versions used for upgrade tests

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5060]
We should be able to maintain a list of branches which contain `VERSION` files that the CI can query directly from the internet to perform upgrade tests. This removes the need to constantly update the upgrade tests to have the latest versions of each branch (e.g., v1.0.5 for v1.0, v1.1.1 of v1.1, etc.).

**Comment by eloycoto** [comment]
The thing here, and we already discussed this with @tgraf, is that the update should happens always from the first version no? 

On the other hand, if we upgrade using internet, we're going to lost the availability of the CI, let's say that on 1.1 we want to upgrade from 1.0 and from 1.2 from 1.1. Meanwhile if the variable is in the CI will keep the data as we need. 

I do not see anything wrong with the test at the moment.

**Comment by ianvernon** [comment]
> update should happen always from the first version

Please clarify. What constitutes the "first version" in reference to say v1.0, v1.1, v1.2? Maybe we can have a discussion with various folks about how we want to validate our upgrade / downgrade strategy, and clearly delineate what we do / do not support, like Kubernetes does. 

I think the best we can do currently in the CI is to validate upgrade from the latest release of any minor version to the latest release of any subsequent minor versions / `HEAD` of master.

I.e., we test upgrade of the latest release of any `v1.y.z` branch to `HEAD` of the current branch, e.g. `v1.0.5` to HEAD of master, `v1.0.5` to `HEAD` of the `v1.1` branch, and `v1.0.5` to `HEAD` of the `v1.2` branch. The same goes for `v1.1.2` to `HEAD` of master and `HEAD` of the `v1.2` branch.

>  if we upgrade using internet, we're going to lost the availability of the CI

"We're going to lost the availability of the CI" - please be more specific. What do you mean by using the internet? Our CI currently requires internet connectivity, and will fail in provisioning VMs if we do not have internet connectivity, so I don't understand your concerns about internet connectivity here. The main benefit I am proposing is that if we grab the contents of the `VERSION` file in the specified release branches (e.g., v1.0, v1.1), we automatically validate upgrade from that version to whatever branches test upgrade from the latest release of those branches (v1.1 would test the latest VERSION of v1.0, for instance). Otherwise, we will assuredly forget to update the constants in multiple release branches and lose important visibility into upgrade validation. 

> let's say that on 1.1 we want to upgrade from 1.0 and from 1.2 from 1.1.

Then we can contain a list of release branches that we support upgrade from, i.e., in 1.2, we have a slice of release branches that we say we support upgrade from:

```branchesToValidateUpgrade := []string{"v1.0", "v1.1", "1.2"}```

We'd test upgrade against the latest version of v1.0 to `HEAD` of v1.2, latest version of v1.1 to `HEAD` of v1.2, and the latest released version of v1.2 to `HEAD`.

For 1.1, we'd similarly have:

```branchesToValidateUpgrade := []string{"v1.0", "v1.1}```

> Meanwhile if the variable is in the CI will keep the data as we need.

I don't understand this. What does "keep the data as we need" mean?

> I do not see anything wrong with the test at the moment.

The problem is that the hardcoded versions will inevitably fall out of sync with the latest released versions, and we will no longer be validating upgrade from the latest releases of each minor version of Cilium. We will inevitably forget to do this if it is a manual process to update constants in a variety of release branches. My proposal automates this need away, and ensures we are always validating upgrade from the latest versions of each release.
