### ISSUE TITLE
CI: consider adding stage which provisions VMs before running tests in said VMs

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5063]
Currently, the provisioning of VMs in the build for runtime and K8s tests is done in parallel, and is coupled with running the tests themselves. Consider separating provisioning of the VMs into a separate stage, which provisions all VMs in parallel, i.e.:
```
stage('Provision VMs') {
            environment {
                GOPATH="${WORKSPACE}"
                TESTDIR="${WORKSPACE}/${PROJ_PATH}/test"
            }

            options {
                timeout(time: 20, unit: 'MINUTES')
            }

            steps {
                parallel(
                    "Runtime":{
                        sh 'cd ${TESTDIR}; vagrant up runtime'
                    },
                    "K8s-1.7":{
                        sh 'cd ${TESTDIR}; K8S_VERSION=1.7 vagrant up '
                    },
                    "K8s-1.10":{
                        sh 'cd ${TESTDIR}; K8S_VERSION=1.10 vagrant up'
                    },
                    failFast: true
                )
            }
```

This would make it much clearer if provisioning / booting the VMs failed (say, when downloading Docker images). Right now, if provisioning fails, it looks like all of the tests for a specific suite failed, which is not the case.

We could then update the running of `ginkgo` within the tests to not provision Cilium, e.g.:

```
"K8s-1.10":{
                        sh 'cd ${TESTDIR}; K8S_VERSION=1.10 ginkgo --focus=" K8sValidated*" -v --failFast=${FAILFAST} -- -cilium.provision=false'
                    },
```

**Comment by eloycoto** [comment]
There is a reason why the VMs are running in serialize mode: 

- If we do the vagrant up in parallel Virtualbox locks do not work well and we're going to have a lot of flakes. As we had in the past. 
- If we do the vagrant up for kubernetes like that will create another runtime and will fail.

I'm not agree with this one. If the BeforeSuite fails on the start the fail on provision is marked and the data is in there, maybe the solution is to populate that data to all the test, but that is a different behaviour. 

What you propose I do not liked at all, will be hard to maintain and a lot of flakes will happen. 
Regards

**Comment by ianvernon** [comment]
@eloycoto note that this would not get rid of the “Boot VMs” stage. If you boot a VM with the `--no-provision` option, (e.g., `vagrant up runtime --no-provision`) and then run `vagrant up runtime` , you are effectively provisioning the VMs with the second command because you have already booted it. We can change `vagrant up runtime` --> `vagrant provision runtime`.

Your second argument can be addressed if we specify the VM names in the provisioning stage, e.g. `K8S_VERSION=1.7 vagrant provision k8s1-1.7; K8S_VERSION=1.7 vagrant provision k8s2-1.7` 

> If the BeforeSuite fails on the start the fail on provision is marked and the data is in there, maybe the solution is to populate that data to all the test, but that is a different behaviour.

I don’t understand what this means. Can you clarify ? The motivation behind my proposal is to separate provisioning of infrastructure from the actual tests themselves. Coupling the two together makes it look like tests failed when no tests were actually ran because the VMs were never able to be provisioned appropriately.

**Comment by ianvernon** [comment]
@eloycoto any thoughts on this proposal? Another motivation to split these stages is to gain more insight into how long tests take vs. how long provisioning takes, which is useful in evaluating performance. I.e., if downloading something for provisioning the environment for testing is taking a long time, we can see clearly observe that. I'm happy to take this on / explore if it is even possible to configure parallel stages this way in a Jenkinsfile.

**Comment by eloycoto** [comment]
I think that make things difficult, and does not add a real value. If you want to know how long it take, you'll see in the junit output, so for me it's not a real value and It'll make things difficult (No Junit output, if one stage fails, the other will not run)

But your points are all valid.

**Comment by eloycoto** [comment]
Already made by @ianvernon
