### ISSUE TITLE
Cilium not working with Docker Multi Host (Mesos)

### ISSUE THREAD

**Issue by krishnabigdata** [cilium/cilium#5069]
We want to use IP per container using cilium, here are problems we have.

We have 2 EC2 instance for test purpose.

1) **Host 1** (for e.g., 172.0.1.1) setup using steps provided in "Getting Started Using Docker Compose" but using central consul.
- IFACE device - ens3
- _cilium-agent  --debug -d ens3 --kvstore consul --kvstore-opt consul.address 172.16.*.*:8500 --tunnel vxlan_
2) **Host 2** (for e.g., 172.0.1.2) same as **Host 1**.
- IFACE device - ens3
- _cilium-agent  --debug -d ens3 --kvstore consul --kvstore-opt consul.address 172.16.*.*:8500 --tunnel vxlan_

**_Host 1_**

- Running a simple docker application using cilium network, produces a IP address for container(_10.94.254.135_)
- Able to access the application  using _http://10.94.254.135:4000_

**Problems:**
============

**_Unable to access application from Host 2_**

- Wanted to access the application running in **Host 1** using http://10.94.254.135:4000 from **Host 2**,  It doesn't work.
- Problem in accessing vice versa as well.

**Cilium not forming a cluster mesh**

- When I run _cilium status --all-controllers --all-health --all-redirects_ in **Host 1** I get the below result.
`KVStore:             Ok         Consul: 172.16.*.*:8300
ContainerRuntime:    Ok         docker daemon: OK
Kubernetes:          Disabled
Cilium:              Ok         OK
NodeMonitor:         Disabled
IPv4 address pool:   3/65535 allocated
IPv6 address pool:   2/65535 allocated
Controller Status:   4/4 healthy
  Name                       Last success   Last error   Count   Message
  cilium-health-ep           never          never        0       no error
  kvstore-lease-keepalive    5s ago         never        0       no error
  lxcmap-bpf-host-sync       3s ago         never        0       no error
  metricsmap-bpf-prom-sync   3s ago         never        0       no error
Proxy Status:   OK, ip 10.94.0.1, port-range 10000-20000
Cluster health:                1/1 reachable   (2018-08-01T14:59:58Z)
  Name                         IP              Reachable   Endpoints reachable
  ip-172-0-1-1 (localhost)   172.0.1.1     true        false`

- When I run _cilium status --all-controllers --all-health --all-redirects_ in **Host 2** I get the below result.
`KVStore:             Ok         Consul: 172.16.*.*:8300
ContainerRuntime:    Ok         docker daemon: OK
Kubernetes:          Disabled
Cilium:              Ok         OK
NodeMonitor:         Disabled
IPv4 address pool:   3/65535 allocated
IPv6 address pool:   2/65535 allocated
Controller Status:   4/4 healthy
  Name                       Last success   Last error   Count   Message
  cilium-health-ep           never          never        0       no error
  kvstore-lease-keepalive    5s ago         never        0       no error
  lxcmap-bpf-host-sync       3s ago         never        0       no error
  metricsmap-bpf-prom-sync   3s ago         never        0       no error
Proxy Status:   OK, ip 10.139.0.1, port-range 10000-20000
Cluster health:                1/1 reachable   (2018-08-01T14:59:58Z)
  Name                         IP              Reachable   Endpoints reachable
  ip-172-0-1-2 (localhost)   172.0.1.2     true        false`

**Tried:**
==========
**On Host2**

- Added  _ip route add 10.94.0.0/16 via 172.0.1.1  dev ens3_ still it doesn't work.

**Old Cilium Version**

- Used v1.0.0-rc9 with   _--tunnel disabled_ and adding route entry as above still have the same problem

**Cilium Version:** v1.1.2
**Kernel version:** 4.15.0-29-generic

can you please help on this problem. May be I am doing something wrong.

Please let me know if you need anymore details.

**Comment by tgraf** [comment]
> cilium-agent --debug -d ens3 --kvstore consul --kvstore-opt consul.address 172.16..:8500 --tunnel vxlan

Direct routing mode requires you to run a routing daemon or install routes manually to tell each node how to reach container IPs on other nodes. Alternatively you can run in tunnel mode to avoid this.

> Cilium not forming a cluster mesh

The node discovery was relying on k8s in 1.1. 1.2 will feature kvstore based node discovery:
https://github.com/cilium/cilium/pull/4270

It's available in `:latest` already.

**Comment by krishnabigdata** [comment]
Its working now. Thanks

**Comment by kasasxav** [comment]
Hi,
I want to do the exact same thing as @krishnabigdata but it's not clear for me how it was fixed?
I don't want to use kubernetes but only docker.

You (@tgraf) said he should add the ip routes manually but isn't this what he did in (Added ip route add 10.94.0.0/16 via 172.0.1.1 dev ens3 ) ?
