### ISSUE TITLE
Monitor debug messages for IPCache mapping may be misleading

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5073]
These debug messages might be mapping the source address or the destination address, depending on where it's called from, so specifying "daddr" here is misleading.

https://github.com/cilium/cilium/blob/31d053c64abc581bb43c4c744ce51861afefbaea/pkg/monitor/datapath_debug.go#L339-L346

For example, at the start of the following program that handles traffic from a node (bpf_netdev), we may perform a source address lookup, then later in the same function we perform a lookup with the destination address:

https://github.com/cilium/cilium/blob/31d053c64abc581bb43c4c744ce51861afefbaea/bpf/bpf_netdev.c#L202-L252

This could be fixed by either:
* Changing the monitor message to say "addr"
* Adding a new parameter to these messages to identify whether they represent source or destination, or
* Introducing a new set of these monitor messages for saddr lookup.

**Comment by joestringer** [comment]
I think that just renaming the message should be sufficient.

**Comment by joestringer** [comment]
I think that if these `cilium_dbg()` calls used `cilium_dbg3()` instead, then we could pass an enum or something to identify the address that was looked up. Then the monitor side of the code could just pick up on that bit and represent the output as "saddr" or "daddr" depending on which was used.

**Comment by umesh3034** [comment]
Hi @joestringer ,

is it ok if i pass new arg to cilium_dbg, which would be checked at monitor code for direction(src/dst)?
Downside is that we need to pass the arg at around 40 odd places.

**Comment by joestringer** [comment]
@umesh3034 `cilium_dbg()` is just the 2-argument version of `cilium_dbg3()`. As far as I know, you shouldn't need to change these definitions, just substitute the `cilium_dbg()` calls with `cilium_dbg3()` and pass the extra argument that you want to pass. The arguments are generic at this layer, they're just integers that are passed through the perf channel up into the userspace-side monitor. Then there should be type-specific handling of the arguments in `pkg/monitor`, which is what the first code snippet highlights in the description of this issue. Does that make sense?

**Comment by umesh3034** [comment]
Ok, got confused, i thought cilium_dbg3() was a later version of cilium_dbg(). I would like to spend sometime looking at the code how cilium_dbg3() works and how the typecasting is done at the monitor side. Once i have a fair idea , maybe 2-3 days, i will come back with more  questions/tentative solution..thanks for the tips Joe..

**Comment by joestringer** [comment]
@umesh3034 that confused me at first too. Perhaps a separate patch to change the name of `cilium_dbg()` to `cilium_dbg2()` (and a comment for the function?) would prevent additional confusion in future.
