### ISSUE TITLE
hostPort support feature request

### ISSUE THREAD

**Issue by Kami-no** [cilium/cilium#5088]
Please add hostPort support.

It is useful for Ingress DaemonSets in bare-metal installations to reduce network overhead (nodePort -> Service -> host with container -> container).

**Comment by RobertTheProfessional** [comment]
I got hostPort working with the Cilium CNI by configuring a custom CNI plugin chain as followed:

```json
{
        "cniVersion": "0.3.1",
        "name": "cilium-portmap",
        "plugins": [
                {
                        "type": "cilium-cni",
                        "mtu": 8950
                },
                {
                        "type": "portmap",
                        "capabilities": { "portMappings": true }
                }
        ]
}
```

Should be a simple fix, no?

**Comment by tgraf** [comment]
@RobertTheProfessional Awesome. We should definitely add this to the docs. We will likely still consider adding native support

**Comment by RobertTheProfessional** [comment]
Sounds good to me!

**Comment by anitgandhi** [comment]
@RobertTheProfessional did you just save that as an additional `.conf` in `/etc/cni/net.d/` and restart kubelet?

**Comment by RobertTheProfessional** [comment]
Yes, however only one CNI plugin can be loaded at a time. Therefore, the configuration must be prefixed with a value that will denote it as the first file in the path.

**Comment by anitgandhi** [comment]
Thanks; I saved it as `000-cilium-portmap.conflist` and it worked 👍

**Comment by anitgandhi** [comment]
For what it's worth to anyone else that comes along:

I had to save this in `/etc/cni/net.d/000-cilium-portmap.conflist`:

```
{
    "name": "cilium-portmap",
    "plugins": [
        {
            "type": "cilium-cni"
        },
        {
            "type": "portmap",
            "capabilities": {
                "portMappings": true
            }
        }
    ]
}
```

either before kubelet comes up, or save that file then restart kubelet

**Comment by tgraf** [comment]
Moving to bugfix milestone as this can be solved with documentation primarily.
