### ISSUE TITLE
CI: builds timing out due to blocking commands in WithTimeout

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5163]
k8s 1.7 build timed out on one of the regular master runs at Aug 10, 2018 6:02 AM UTC:

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3611/flowGraphTable/

Most recent logs:

```
06:57:46 K8sServicesTest Bookinfo Demo 
06:57:46   Tests bookinfo demo
06:57:46   /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
06:57:46 STEP: Creating objects in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1.yaml"
06:57:46 STEP: Creating objects in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2.yaml"
06:57:59 STEP: Waiting for pods to be ready
06:58:04 STEP: Waiting for services to be ready
06:58:04 STEP: Validating DNS without Policy
06:58:06 STEP: All pods should be able to connect without policy
06:58:07 STEP: Checking that "reviews-v1-1217721402-b0wfr" can connect to "ratings.default.svc.cluster.local:9080/health"
06:58:07 STEP: Checking that "reviews-v1-1217721402-b0wfr" can connect to "ratings.default.svc.cluster.local:9080/ratings/0"
06:58:07 STEP: Checking that "productpage-v1-407527135-ntkwc" can connect to "details.default.svc.cluster.local:9080/health"
06:58:09 STEP: Checking that "productpage-v1-407527135-ntkwc" can connect to "ratings.default.svc.cluster.local:9080/health"
06:58:10 STEP: Checking that "productpage-v1-407527135-ntkwc" can connect to "ratings.default.svc.cluster.local:9080/ratings/0"
06:58:10 STEP: Importing policy
07:22:12 === Test Finished at 2018-08-10T07:22:10Z====
07:22:40 ===================== TEST FAILED =====================
```

[test_results_Cilium-PR-Ginkgo-Tests-Validated_5542_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/2277364/test_results_Cilium-PR-Ginkgo-Tests-Validated_5542_BDD-Test-PR.zip)

Seen also similar basic behaviour (builds timing out) in these PR runs:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5542/flowGraphTable/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5553/flowGraphTable/

**Comment by joestringer** [comment]
@eloycoto Do we fetch the final Cilium logs if the build is timed out like this? I can't seem to find any logs for K8sServicesTest for k8s 1.7 in the above zip.

**Comment by eloycoto** [comment]
Hi, 

On timeouts there is no logs (I also hate that), need to reproduce locally to found what happens. 

If you think that there is a way to fix this one: 
- If we add the timeout on ginkgo, to 1 min less of the stage, logs for that test will not be in there, because it happens on the AfterFailed function, and is not reach. (Or does not look like)
- If we add a Timeout for a ginkgo function, also didn't work, I need to investigate that one. 

The only way that I can think is to do another wrapper that execute the test and the timeout in background.. but I'm not sure that will work. 

Regards

**Comment by joestringer** [comment]
Hit issue again in #5118:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5542/

We seem to lose chunks of time randomly during VM initialization:
```
13:53:5713:53:57  [Cilium-PR-Ginkgo-Tests-Validated] Running shell script
...
13:59:30     k8s1-1.7: 701b4d847147: Download complete
14:06:10     k8s1-1.7: a221aee506c9: 
...
14:09:08     k8s1-1.7: 7f80f6cda1cc: 
14:09:08     k8s1-1.7: Pull complete
14:58:52     k8s1-1.7: 96649a2a4ebe: Verifying Checksum
...
15:03:56     k8s1-1.7: 9e65a62c4127: Download complete
15:19:41     k8s1-1.7: c64513b74145: 
...
15:19:54     k8s1-1.7: a98c60236860: Download complete
15:23:18     k8s1-1.7: 473d8689cf91: 
...
15:23:18     k8s1-1.7: Download complete
15:32:29     k8s1-1.7: 2e02b3453911: 
...
15:33:22     k8s2-1.7: 84a0e9b41119: Pull complete
15:33:22     k8s2-1.7: Digest: sha256:1bc57ccba5a9fc17ae243520996dfc757a4c379aebd13531d302e61200b52a79
15:33:22     k8s2-1.7: Status: Downloaded newer image for k8s1:5000/cilium/cilium-dev:latest
15:34:46 STEP: Applying deployments
```

**Comment by ianvernon** [comment]
The fact that the final log output by the test before timeout indicates that there is some step that is taking far too long and timing out the entire build:
```
 STEP: Importing policy
```

This should not happen for any of our helpers. We need to see if there is something happening in the CI code that is affecting this.

The code where the timeout occurred is here:

https://github.com/cilium/cilium/blob/b88afa221afc56b8ac34d304a7af64ac99e9f4b3/test/k8sT/Services.go#L413-L415

This eventually calls `cilium policy wait` in every Cilium pod:

https://github.com/cilium/cilium/blob/b88afa221afc56b8ac34d304a7af64ac99e9f4b3/test/helpers/kubectl.go#L995-L1007

I suspect that these blocking calls to `cilium policy wait` are what are causing the build to get stuck. @eloycoto maybe we can add calls to `ginkgo.By` before blocking calls to `cilium policy wait`? This would put information onto console to make this easier to debug.

**Comment by eloycoto** [comment]
Cilium policy wait has a timeout of 60 seconds. 

Plus is used with timeout, if is over 300 seconds helper will kill the function and return error

**Comment by ianvernon** [comment]
@eloycoto the fact that the build is timing out after a large amount of time suggests that your assertion may not be true. I am not saying it is false; what I am saying is that we do not have enough information to make such an assertion-  how can we definitively say that that is the case if the only output we have in Joe's case is the final log of "Importing policy"? To determine this, we should add more informative output to be displayed console for long-running operations in the CI, at least in the `CiliumPolicyAction` function.

**Comment by eloycoto** [comment]
Close this one due 5821 PR
