### ISSUE TITLE
Make bpf.OpenMap() always check against golang types which are expected

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#5168]
In CT (e.g. flush), metricsmap and others they use `bpf.OpenMap()` and don't check their expectations in terms of key/value size from map info, which will have implications once their key/values size are changing.

* [x] Adjust policymap to use OpenOrCreate
* [ ] Adjust CT maps to use OpenOrCreate
* [x] Remove mapValidateWalker() (#5559)
* [ ] Remove cilium_map_migrate
* [x] Update IPCache to use feature detection to choose the map type correctly
  * [x] Need to make the `bpf_features.h` feature detection available earlier (as part of OpenAfterMount)

**Comment by joestringer** [comment]
If they don't match, do we just delete the map? I guess this should in general be safe as the next time something is regenerated, the map should be recreated with the new details.

**Comment by tgraf** [comment]
Is that safe? Even after the program has been loaded?

**Comment by borkmann** [comment]
If we would delete the map after a program using it has been loaded it would mean that the program continues to using the old map (since it holds refcount on it) while daemon side would use the new map until the prog is regenerated which would then pick up the new map. If we always know that a given map will first get created through the object loader, and only later on accessed by the daemon, it could also bail out if properties mismatch there, such that at least we will be aware that `bpf.OpenMap()` failed instead of silently corrupting golang stack. Potentially this failure could then already get caught at CI tests.

**Comment by tgraf** [comment]
We already do this for some maps:

```
func mapValidateWalker(path string) error {
        prefixToValidator := map[string]bpf.MapValidator{
                policymap.MapName: policymap.Validate,
        }

        filename := filepath.Base(path)
        for m, validate := range prefixToValidator {
                if strings.HasPrefix(filename, m) {
                        valid, err := validate(path)
                        switch {
                        case err != nil:
                                return err
                        case !valid:
                                log.WithField(logfields.Path, filename).Info("Outdated non-persistent BPF map found, removing...")

                                if err := os.Remove(path); err != nil {
                                        return err
                                }
                        }
                }
        }

        return nil
}
```

This is done before regeneration happens and ensures that we re-create these maps. I think we should simply do this for *all* maps early on and ensure that we re-create as needed.

**Comment by borkmann** [comment]
> We already do this for some maps

So we do this right now according to a05b59ae4cd for cilium policy maps. Looks like functionality is partially similar to 3d82a4b46517 which probes object files and has `objCheck()` for the daemon's pinned maps. Probably best to consolidate everything, also including fa12caf597f92a.

**Comment by joestringer** [comment]
OK, so to take inventory:

* Policy maps are migrated on `Daemon.init()` via `mapValidateWalker()` -> ... -> `MetadataDiff()`
  * a05b59ae4cd56391edc457ccf16e3fcf4b24ffb1
* CT maps are migrated prior to restore by `DeleteIfUpgradeNeeded()` -> ... -> `objCheck()`
  * fa12caf597f92a6020becf572035f39a89a2c2d7
* CIDR (prefilter), Policy maps are migrated via `OpenOrCreate()` -> ... -> `objCheck()`
  * 3d82a4b46517bef70e867128ab3b34dd3d7322ff
  * CIDR (prefilter) maps are done on startup (`init()`)
  * Policy is done the first time policy is generated for the endpoint (`regenerateBPF`)
* LB maps are migrated the first time a service is added from userspace, or when the BPF is first generated - most likely the latter via `cilium_map_migrate` (though could be via `OpenOrCreate()`)
  * 3d82a4b46517bef70e867128ab3b34dd3d7322ff
* IPCache, LXCMap, MetricsMap, ProxyMap, TunnelMap are migrated on startup inside `init()` functions via `OpenAfterMount()` -> `OpenOrCreate()` -> ... -> `objCheck()`.
  * 3d82a4b46517bef70e867128ab3b34dd3d7322ff

**Comment by joestringer** [comment]
@borkmann and I discussed a path forward on this yesterday:

* Adjust policymap to use OpenOrCreate
* Adjust CT maps to use OpenOrCreate
* Remove `mapValidateWalker()`
* Remove `cilium_map_migrate`
  * The idea is that if the BPF would attempt to install a map with the wrong attributes, it will complain like it did previously, and fail to install the BPF program. This should force developers to consider how to properly migrate the map from userspace, and prevent issues like conflicts between userspace/kernel leading to constant recreation of maps or userspace/kernel operating on independent copies of maps.
* Update IPCache to use feature detection to choose the map type correctly
  * Need to make the `bpf_features.h` feature detection available earlier (as part of `OpenAfterMount`)
