### ISSUE TITLE
CI: Unable to provision and start VM "k8s1-1.7": exit status 255", vm, err

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#5183]
I haven't had a chance to look too deeply yet, so I'll leave triage on there.

Jenkins job https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1401/ failed in two ways:
1. VM provision on k8s-1.7.K8sChaosTest Endpoint can still connect while Cilium is not running
[Uploading bc0c43ba_K8sChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running.zip…]()

make seems to have seen this error and exited:
```
    k8s1-1.7: service "kube-dns" deleted
    k8s1-1.7: serviceaccount "kube-dns" deleted
    k8s1-1.7: deployment "kube-dns" deleted
    k8s1-1.7: Error from server (NotFound): error when deleting "/tmp/provision//manifest/dns_deployment.yaml": configmaps "kube-dns" not found
    k8s1-1.7: service "kube-dns" created
    k8s1-1.7: serviceaccount "kube-dns" created
    k8s1-1.7: configmap "kube-dns" created
    k8s1-1.7: deployment "kube-dns" created
```

I'm not sure, though, since `make clean` is run after this error, so maybe it's ignored. We do intend to delete dns_deployment.yaml and re-add it (test/provision/k8s_install.sh:187/188).

<details>
  <summary>Stacktrace</summary>
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:333

        ===================== ERROR - VM PROVISION FAILED =====================

        Unable to provision and start VM "k8s1-1.7": exit status 255", vm, err

        =======================================================================
        
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:460
Standard Output
Standard Error
==> k8s1-1.7: Running provisioner: ipv6-config (shell)...
    k8s1-1.7: Running: inline script
==> k8s1-1.7: Running provisioner: shell...
    k8s1-1.7: Running: inline script
==> k8s1-1.7: Running provisioner: file...
==> k8s1-1.7: Running provisioner: shell...
    k8s1-1.7: Running: /tmp/vagrant-shell20180813-5125-1p5ktz9.sh
    k8s1-1.7: updating /etc/resolv.conf
    k8s1-1.7: beginning trying up to 10 times function "wget https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    k8s1-1.7: ***************************************
    k8s1-1.7: *
    k8s1-1.7: *
    k8s1-1.7: * on attempt 0 of function "wget https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    k8s1-1.7: *
    k8s1-1.7: *
    k8s1-1.7: ***************************************
    k8s1-1.7: --2018-08-13 08:53:43--  https://packages.cloud.google.com/apt/doc/apt-key.gpg
    k8s1-1.7: Resolving packages.cloud.google.com (packages.cloud.google.com)... 
    k8s1-1.7: 173.194.206.101
    k8s1-1.7: , 
    k8s1-1.7: 173.194.206.139
    k8s1-1.7: , 
    k8s1-1.7: 173.194.206.102
    k8s1-1.7: , ...
    k8s1-1.7: Connecting to packages.cloud.google.com (packages.cloud.google.com)|173.194.206.101|:443... 
    k8s1-1.7: connected.
    k8s1-1.7: HTTP request sent, awaiting response... 
    k8s1-1.7: 200 OK
    k8s1-1.7: Length: 
    k8s1-1.7: 1326
    k8s1-1.7:  (1.3K)
    k8s1-1.7:  [application/octet-stream]
    k8s1-1.7: Saving to: 'apt-key.gpg'
    k8s1-1.7: 
    k8s1-1.7:      0K
    k8s1-1.7:  
    k8s1-1.7: .
    k8s1-1.7:  
    k8s1-1.7:  
    k8s1-1.7:  
    k8s1-1.7:  
    k8s1-1.7:  
    k8s1-1.7:  
    k8s1-1.7:  
    k8s1-1.7:  
    k8s1-1.7:  
    k8s1-1.7:  
    k8s1-1.7:                                            100% 1.09M=0.001s
    k8s1-1.7: 
    k8s1-1.7: 2018-08-13 08:53:44 (1.09 MB/s) - 'apt-key.gpg' saved [1326/1326]
    k8s1-1.7: running of "wget https://packages.cloud.google.com/apt/doc/apt-key.gpg" successful
    k8s1-1.7: Warning: apt-key output should not be parsed (stdout is not a terminal)
    k8s1-1.7: OK
    k8s1-1.7: Disabling crio CNI bridge
    k8s1-1.7: removed '/etc/cni/net.d/100-crio-bridge.conf'
    k8s1-1.7: removed '/etc/cni/net.d/200-loopback.conf'
    k8s1-1.7: Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
    k8s1-1.7: Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
    k8s1-1.7: Hit:4 http://ppa.launchpad.net/projectatomic/ppa/ubuntu xenial InRelease
    k8s1-1.7: Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
    k8s1-1.7: Hit:6 https://download.docker.com/linux/ubuntu bionic InRelease
    k8s1-1.7: Hit:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
    k8s1-1.7: Hit:1 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
    k8s1-1.7: Reading package lists...
    k8s1-1.7: Reading package lists...
    k8s1-1.7: Building dependency tree...
    k8s1-1.7: 
    k8s1-1.7: Reading state information...
    k8s1-1.7: The following NEW packages will be installed:
    k8s1-1.7:   kubeadm kubectl kubelet kubernetes-cni
    k8s1-1.7: 0 upgraded, 4 newly installed, 0 to remove and 17 not upgraded.
    k8s1-1.7: Need to get 45.1 MB of archives.
    k8s1-1.7: After this operation, 333 MB of additional disk space will be used.
    k8s1-1.7: Get:1 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 kubernetes-cni amd64 0.5.1-00 [5,560 kB]
    k8s1-1.7: Get:2 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 kubelet amd64 1.7.15-00 [19.6 MB]
    k8s1-1.7: Get:3 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 kubectl amd64 1.7.15-00 [10.1 MB]
    k8s1-1.7: Get:4 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 kubeadm amd64 1.7.15-00 [9,792 kB]
    k8s1-1.7: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    k8s1-1.7: Fetched 45.1 MB in 4s (12.2 MB/s)
    k8s1-1.7: Selecting previously unselected package kubernetes-cni.
    k8s1-1.7: (Reading database ... 
    k8s1-1.7: (Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
    k8s1-1.7: (Reading database ... 65%
    k8s1-1.7: (Reading database ... 70%
    k8s1-1.7: (Reading database ... 75%
    k8s1-1.7: (Reading database ... 80%
    k8s1-1.7: (Reading database ... 85%
    k8s1-1.7: (Reading database ... 90%
    k8s1-1.7: (Reading database ... 95%
    k8s1-1.7: (Reading database ... 100%
(Reading database ... 143660 files and directories currently installed.)
    k8s1-1.7: Preparing to unpack .../kubernetes-cni_0.5.1-00_amd64.deb ...
    k8s1-1.7: Unpacking kubernetes-cni (0.5.1-00) ...
    k8s1-1.7: Selecting previously unselected package kubelet.
    k8s1-1.7: Preparing to unpack .../kubelet_1.7.15-00_amd64.deb ...
    k8s1-1.7: Unpacking kubelet (1.7.15-00) ...
    k8s1-1.7: Selecting previously unselected package kubectl.
    k8s1-1.7: Preparing to unpack .../kubectl_1.7.15-00_amd64.deb ...
    k8s1-1.7: Unpacking kubectl (1.7.15-00) ...
    k8s1-1.7: Selecting previously unselected package kubeadm.
    k8s1-1.7: Preparing to unpack .../kubeadm_1.7.15-00_amd64.deb ...
    k8s1-1.7: Unpacking kubeadm (1.7.15-00) ...
    k8s1-1.7: Setting up kubernetes-cni (0.5.1-00) ...
    k8s1-1.7: Setting up kubelet (1.7.15-00) ...
    k8s1-1.7: Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service -> /lib/systemd/system/kubelet.service.
    k8s1-1.7: Setting up kubectl (1.7.15-00) ...
    k8s1-1.7: Setting up kubeadm (1.7.15-00) ...
    k8s1-1.7: Created symlink /etc/systemd/system/multi-user.target.wants/sys-fs-bpf.mount -> /etc/systemd/system/sys-fs-bpf.mount.
    k8s1-1.7: [kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
    k8s1-1.7: [init] Using Kubernetes version: v1.7.15
    k8s1-1.7: [init] Using Authorization modes: [Node RBAC]
    k8s1-1.7: [preflight] Running pre-flight checks
    k8s1-1.7: [preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 18.06.0-ce. Max validated version: 1.12
    k8s1-1.7: [kubeadm] WARNING: starting in 1.8, tokens expire after 24 hours by default (if you require a non-expiring token use --token-ttl 0)
    k8s1-1.7: [certificates] Generated CA certificate and key.
    k8s1-1.7: [certificates] Generated API server certificate and key.
    k8s1-1.7: [certificates] API Server serving cert is signed for DNS names [k8s1 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.36.11]
    k8s1-1.7: [certificates] Generated API server kubelet client certificate and key.
    k8s1-1.7: [certificates] Generated service account token signing key and public key.
    k8s1-1.7: [certificates] Generated front-proxy CA certificate and key.
    k8s1-1.7: [certificates] Generated front-proxy client certificate and key.
    k8s1-1.7: [certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
    k8s1-1.7: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
    k8s1-1.7: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
    k8s1-1.7: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
    k8s1-1.7: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
    k8s1-1.7: [apiclient] Created API client, waiting for the control plane to become ready
    k8s1-1.7: [apiclient] All control plane components are healthy after 80.502629 seconds
    k8s1-1.7: [token] Using token: 258062.5d84c017c9b2796c
    k8s1-1.7: [apiconfig] Created RBAC rules
    k8s1-1.7: [addons] Applied essential addon: kube-proxy
    k8s1-1.7: [addons] Applied essential addon: kube-dns
    k8s1-1.7: 
    k8s1-1.7: Your Kubernetes master has initialized successfully!
    k8s1-1.7: 
    k8s1-1.7: To start using your cluster, you need to run (as a regular user):
    k8s1-1.7: 
    k8s1-1.7:   mkdir -p $HOME/.kube
    k8s1-1.7:   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    k8s1-1.7:   sudo chown $(id -u):$(id -g) $HOME/.kube/config
    k8s1-1.7: 
    k8s1-1.7: You should now deploy a pod network to the cluster.
    k8s1-1.7: Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
    k8s1-1.7:   http://kubernetes.io/docs/admin/addons/
    k8s1-1.7: 
    k8s1-1.7: You can now join any number of machines by running the following on each node
    k8s1-1.7: as root:
    k8s1-1.7: 
    k8s1-1.7:   kubeadm join --token 258062.5d84c017c9b2796c 192.168.36.11:6443
    k8s1-1.7: node "k8s1" untainted
    k8s1-1.7: service "kube-dns" deleted
    k8s1-1.7: serviceaccount "kube-dns" deleted
    k8s1-1.7: deployment "kube-dns" deleted
    k8s1-1.7: Error from server (NotFound): error when deleting "/tmp/provision//manifest/dns_deployment.yaml": configmaps "kube-dns" not found
    k8s1-1.7: service "kube-dns" created
    k8s1-1.7: serviceaccount "kube-dns" created
    k8s1-1.7: configmap "kube-dns" created
    k8s1-1.7: deployment "kube-dns" created
    k8s1-1.7: building cilium/cilium container image...
    k8s1-1.7: can't load package: package ./test/bpf: C source files not allowed when not using cgo or SWIG: bpf-event-test.c unit-test.c
    k8s1-1.7: for i in envoy plugins bpf cilium daemon monitor cilium-health bugtool; do make -C $i clean; done
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/envoy'
    k8s1-1.7: rm -f ./bazel-bin/envoy ./bazel-bin/istio-envoy ./istio-envoy ./bazel-bin/cilium_integration_test \
    k8s1-1.7: 	Dockerfile.istio_proxy \
    k8s1-1.7: 	Dockerfile.istio_proxy_debug
    k8s1-1.7: Bazel clean skipped, try 'make veryclean' instead.
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/envoy'
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins'
    k8s1-1.7: for i in cilium-docker cilium-cni; do make -C $i clean; done
    k8s1-1.7: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
    k8s1-1.7: go clean
    k8s1-1.7: rm -f cilium-docker
    k8s1-1.7: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
    k8s1-1.7: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
    k8s1-1.7: go clean
    k8s1-1.7: rm -f cilium-cni
    k8s1-1.7: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins'
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
    k8s1-1.7: rm -fr *.o
    k8s1-1.7: rm -f cilium-map-migrate
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium'
    k8s1-1.7: rm -f cilium
    k8s1-1.7: go clean
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium'
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
    k8s1-1.7: rm -f cilium-agent
    k8s1-1.7: go clean
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/monitor'
    k8s1-1.7: rm -f cilium-node-monitor
    k8s1-1.7: go clean
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/monitor'
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium-health'
    k8s1-1.7: rm -f cilium-health
    k8s1-1.7: go clean
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium-health'
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/bugtool'
    k8s1-1.7: rm -f .cilium-bugtool.config cilium-bugtool
    k8s1-1.7: go clean
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bugtool'
    k8s1-1.7: make -C ./contrib/packaging/deb clean
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/deb'
    k8s1-1.7: rm -rf cilium output version_*
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/deb'
    k8s1-1.7: make -C ./contrib/packaging/rpm clean
    k8s1-1.7: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/rpm'
    k8s1-1.7: rm -rf env cilium output version_* cilium-*.tar.gz
    k8s1-1.7: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/rpm'
    k8s1-1.7: rm -f GIT_VERSION
    k8s1-1.7: echo "94c02bb8 2018-08-10T18:49:12+02:00" >GIT_VERSION
    k8s1-1.7: git rev-parse HEAD >envoy/SOURCE_VERSION
    k8s1-1.7: grep -v -E "(SOURCE|GIT)_VERSION" .gitignore >.dockerignore
    k8s1-1.7: echo ".*" >>.dockerignore # .git pruned out
    k8s1-1.7: echo "Documentation" >>.dockerignore # Not needed
    k8s1-1.7: docker build --build-arg LOCKDEBUG=1 -t "cilium/cilium:"latest"" .

        ===================== ERROR - VM PROVISION FAILED =====================

        Unable to provision and start VM "k8s1-1.7": exit status 255", vm, err

        =======================================================================
<br><br></details>

2. The runtime tests also fail in this build, but I haven't looked into it. It seems like a slow regeneration, but it could be more serious.
[b97ddaa0_RuntimePolicies_Init_Policy_Test_Init_Ingress_Policy_Test.zip](https://github.com/cilium/cilium/files/2283574/b97ddaa0_RuntimePolicies_Init_Policy_Test_Init_Ingress_Policy_Test.zip)

**Comment by raybejjani** [comment]
Hmm. Looking some more, the error is actually suppressed (https://github.com/cilium/cilium/blob/master/test/provision/k8s_install.sh#L187). We also make it as far as tagging the image (the cleans are the first thing `make docker-image` does) https://github.com/cilium/cilium/blob/master/test/provision/compile.sh#L20 and https://github.com/cilium/cilium/blob/master/Makefile#L129.

**Comment by eloycoto** [comment]
We're not supporting kuberntes 1.7, so I'll close this issue.
