### ISSUE TITLE
The CNI configuration name should have a lower priority for seamless overriding of the CNI implementation

### ISSUE THREAD

**Issue by RobertTheProfessional** [cilium/cilium#5190]
### General Information

- Cilium version
    - Client: 1.1.90 0261426 2018-08-10T16:08:51+02:00 go version go1.10.3 linux/amd64
    - Daemon: 1.1.90 0261426 2018-08-10T16:08:51+02:00 go version go1.10.3 linux/amd64

- Kernel version
    - 4.14.35-1818.0.14.el7uek.x86_64

- Orchestration system version in use (e.g. `kubectl version`, Mesos, . . .)
    - Kubernetes v1.11.1
    - kubectl version:
      - Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
      - Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

### How to reproduce the issue

Not necessarily a large issue, but when implementing a custom CNI configuration I have to prefix my configuration with a word starting with the letter **a** or **b** in order to override the default CNI configuration *00-cilium.conf* that is installed by the cilium-agent.

For example, I currently use *00-alpha-cilium.conflist* for my custom configuration using HostPort mapping, which works fine but has immediately prompted questions from my team as to why my configuration is named alpha.

If I recall correctly, Calico defines their CNI configuration as *10-calico.conflist* which allows for a simple override, especially since the cilium-agent will persistently apply the *00-cilium.conf* on the next pod initialization.

**Comment by tgraf** [comment]
We initially used `10-cilium.conf` but other CNI plugins such as Calico do not remove their CNI configuration files even if the DaemonSet is removed. This lead to a lot of bug reports where Cilium was not the CNI of choice after the installation process. This lead to the decision to use `00-cilium.conf`. We are open to using a different prefix such as `05-cilium.conf` though to allow `00-` to be reserved for overwrites. Would that work for you?

**Comment by RobertTheProfessional** [comment]
Funny thing is I ran into that exact issue with Canal where it didn't clean up its CNI configuration and IPTables policies so I understand where you're coming from. I don't see any issue with using `05-cilium.conf` though, I haven't personally come across any other CNI plugin using that prefix.
