### ISSUE TITLE
1.3 Release Process

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5195]
* Release Committments: https://github.com/cilium/cilium/projects/10
 
## Release Dates
* Feature Freeze: 2018-07-06
* 1.3.0-rc1: 2018-08-31
* 1.3.0-rc2: 2018-09-07 Feature Freeze (1.3-feature)
* 1.3.0-rc3: 2018-09-14 Feature Exception Freeze (1.3-feature-exception)
* 1.3.0-rc4: 2018-09-21 Bugfix freeze (1.3-bugfix)
* 1.3.0: 2018-10-01 (1.3-bugfix-exception)

## Release Checklist
- [x] Planning
- [x] Development Phase
- [x] Feature Freeze
- [x] Feature Exception Freeze
- [x] Testing & Addressing bugs
- [x] Branch off `v1.3`
- [x] Final Release
- [x] Upgrade & downgrade instructions
- [x] Tag Release
- [x] Release Blog
- [x] Announcement

**Comment by ianvernon** [comment]
1.3 has been released, we can close this.
