### ISSUE TITLE
CI: wait for zookeeper pod and service to be ready before deploying kafka broker 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5204]
Discovered during #5192.

Build failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5657

Kafka pod went into `CrashLoopBackoff` because it could not resolve the `zook` hostname. 

We apply the 'demo path' (kafka-sw-app.yaml) and then wait for the pods to be ready. However, if zookeeper takes too long to get launched / have its service configured in DNS, then the kafka-broker will go into `CrashLoopBackOff`. We should install zookeeper and its corresponding service separately, then wait for DNS to resolve for it before we install the Kafka broker. This ensures that the kafka-broker pod will not crash upon startup.

**Comment by eloycoto** [comment]
I do not agree with this one, Kafka has a livenessProbe and in 300 seconds the service should be up. Added another step will not fix the issue at all. IMHO.

I'm more to use a image that contains Kafka and zookeper in the same deploy:
https://hub.docker.com/r/spotify/kafka

The main problem is that we're now in 1h 25 min, there are a new test for @aanm that adds another ~6 min add another two minutes here will end that we will run test for 1h 35 min.

**Comment by ianvernon** [comment]
@eloycoto fixed this in 01096d866c8deee85f519b437fe0c7e4a1297a41 by using the aforementioned image, so I'm closing this.
