### ISSUE TITLE
Documentation: remove unnecessary page 'Indices and tables'

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#522]
It's not really useful because there is already a TOC which has more info. Something like the below removes it.

```diff
diff --git a/Documentation/index.rst b/Documentation/index.rst
index 222b9e977fdc..9f996a7c8090 100644
--- a/Documentation/index.rst
+++ b/Documentation/index.rst
@@ -15,10 +15,3 @@ Welcome to Cilium's documentation!
    architecture
    admin
    contributing
-
-Indices and tables
-==================
-
-* :ref:`genindex`
-* :ref:`modindex`
-* :ref:`search`
```

**Comment by aalemayhu** [comment]
Please note I am referring to the PDF, not sure if it is needed by the website. https://media.readthedocs.org/pdf/cilium/latest/cilium.pdf

**Comment by tgraf** [comment]
> It's not really useful because there is already a TOC which has more info. Something like the below removes it.

Go ahead and remove it, this is coming from the template files that `sphinx-doc` generated automatically.
