### ISSUE TITLE
Strip down LLVM version in container

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5223]
Currently we test Cilium with LLVM 3.8 on a regular basis.

To expand the range of compilers that we test with, and to make newer features available, we can upgrade the LLVM version in the container image to, eg, LLVM 6 or 7.
   * LLVM 7 release is ETA September 5

Newer LLVM versions may generate better code (I have heard ~5% decrease in instructions, which we have limitations on), and also have better support for BPF (eg, probe CPU type which allows detection of the correct BPF backend at compile time), and support for generating debug symbols (eg BTF).

If we update the container image, then naturally all of the Ginkgo k8s tests would begin testing with newer LLVM. For now, we can retain LLVM 3.8 in the regular VM image so the runtime tests would continue to test with the older LLVM. This will allow us to test with multiple compilers without needing to add additional CI jobs.

Tasks:
* [x] Switch the container image to use a newer LLVM (#7153)
  * [ ] Compile our own LLVM for the image to strip out non-BPF architecture backends
  * [ ] Evaluate whether we can move BPF verifier probes into golang to avoid compiler requirement from there as well
    * Consider piggy-backing upon libbpf feature detection with libbpf go bindings
* [x] Update builder image to use the same version

**Comment by borkmann** [comment]
Related commits for dwarfris:
- https://github.com/llvm-mirror/llvm/commit/e4507fb8c94b605c8f89bb204ecdd7b51cc78758
- https://github.com/llvm-mirror/llvm/commit/0e0047f8c9ada2f0fe0c5f01579a80e2455b8df5

They will first appear in LLVM7, I checked and they are not part of earlier releases.

**Comment by joestringer** [comment]
I compiled the current codebase with LLVM 7 (development version) and attempted to load into Linux 4.9.17 and hit this:

```
$ sudo ./test/bpf/verifier-test.sh
=> Loading ./test/bpf/../../bpf/bpf_lb.c:from-netdev...
```
...
```
Prog section 'from-netdev' rejected: Invalid argument (22)!
 - Type:         3
 - Instructions: 293 (0 over limit)
 - License:      GPL

Verifier analysis:

0: (bf) r6 = r1
1: (b7) r7 = 0
2: (63) *(u32 *)(r6 +60) = r7
3: (63) *(u32 *)(r6 +56) = r7
4: (63) *(u32 *)(r6 +52) = r7
5: (63) *(u32 *)(r6 +48) = r7
6: (63) *(u32 *)(r6 +64) = r7
7: (61) r1 = *(u32 *)(r6 +16)
8: (15) if r1 == 0x8 goto pc+51
 R1=inv R6=ctx R7=imm0,min_value=0,max_value=0 R10=fp
9: (55) if r1 != 0xdd86 goto pc+262
 R1=inv,min_value=56710,max_value=56710 R6=ctx R7=imm0,min_value=0,max_value=0 R10=fp
10: (18) r8 = 0xffffff7a
12: (61) r1 = *(u32 *)(r6 +80)
13: (61) r9 = *(u32 *)(r6 +76)
14: (bf) r2 = r9
15: (07) r2 += 54
16: (2d) if r2 > r1 goto pc+211
 R1=pkt_end R2=pkt(id=0,off=54,r=54) R6=ctx R7=imm0,min_value=0,max_value=0 R8=inv R9=pkt(id=0,off=0,r=54) R10=fp
17: (61) r7 = *(u32 *)(r6 +0)
18: (61) r8 = *(u32 *)(r6 +36)
19: (bf) r1 = r6
20: (85) call 34
21: (63) *(u32 *)(r10 -28) = r0
22: (b7) r1 = 1283
23: (63) *(u32 *)(r10 -32) = r1
24: (63) *(u32 *)(r10 -16) = r8
25: (b7) r1 = 0
26: (63) *(u32 *)(r10 -12) = r1
27: (63) *(u32 *)(r10 -24) = r7
28: (a5) if r7 (null) 0x80 goto pc+1
invalid BPF_JMP opcode a0
```

**Comment by joestringer** [comment]
^ ~Jump code is likely to be `BPF_CALL` instruction. Adding more `__always_inline` around the codebase should mitigate this.~

BPF_JMP opcode `0xa0` is `BPF_JLT`, introduced here in Linux 4.14:

https://github.com/torvalds/linux/commit/b4e432f1000a171d901e42551459059831925770

**Comment by joestringer** [comment]
Looks like `-mcpu=probe` and compiling on a machine with the target kernel should work. In the above example I compiled on my host with Linux 4.15 then attempted to load on a 4.9 kernel.

FWIW to test this in the above environment I did this:

```
$ git diff
diff --git a/bpf/Makefile b/bpf/Makefile
index 201f84335f66..f09b10c8f49b 100644
--- a/bpf/Makefile
+++ b/bpf/Makefile
@@ -6,7 +6,7 @@ CLANG_FLAGS :=  ${FLAGS} -target bpf -emit-llvm
 # eBPF verifier enforces unaligned access checks where necessary, so don't
 # let clang complain too early.
 CLANG_FLAGS += -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option
-LLC_FLAGS   := -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj
+LLC_FLAGS   := -march=bpf -mcpu=v1 -mattr=dwarfris -filetype=obj
 
 BPF = bpf_lxc.o bpf_netdev.o bpf_overlay.o bpf_lb.o bpf_xdp.o
 SCRIPTS = init.sh join_ep.sh run_probes.sh spawn_netns.sh
```

**Comment by eloycoto** [comment]
Add the new llvm version to packer-ci-project please ;-)
