### ISSUE TITLE
Opimize Microscope in CI

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#5224]
right now spinning up microscope pod takes some time before each e2e test, we can lower this time by either running microscope directly on host or not deleting microscope pod.

related: #4976

**Comment by aanm** [comment]
@nebril Can microscope be resilient to failures where the cilium-agent is killed? This way we could start microscope since the beginning and stop it at the end. But I believe we didn't make that approach to avoid getting traffic for every single thing that was happening in the test framework.
