### ISSUE TITLE
CI: add test-all-supported-kernels label

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#5225]
Add a new command for GH PRs which will run the CI tests on all kernel versions we support (4.9 ... latest release) to make sure there are no regressions. This would help in a variety of use cases:

- Making sure there are no verifier or loader surprises in some of the supported kernels and that probes work as expected
- Making sure we can upgrade the container image safely wrt LLVM/clang/iproute2 versions building or loading the progs (but would also be needed if we move compilation out of runtime to check LLVM upgrades there). Related: #5223
- Making sure that in future k{ret}probes/tracepoints keep working across kernel versions we support

Such label could be triggered e.g. for RC releases to make sure they have the needed test coverage.

**Comment by aanm** [comment]
@borkmann Should we close this https://github.com/cilium/cilium/issues/824?

**Comment by borkmann** [comment]
Kind of related, though nightly might be done at a second step once we have this coverage here in place initially with the command trigger.

**Comment by eloycoto** [comment]
I started this a few months back, this PR is still waiting for review. 
https://github.com/cilium/packer-ci-build/pull/39

**Comment by borkmann** [comment]
@eloycoto Anything still blocking above from review side? /cc @aanm @ianvernon

**Comment by ianvernon** [comment]
@borkmann thanks for tagging me, I lost track of the PR. Approved. The real test of the new image though, will be how it works in the Cilium CI.

**Comment by eloycoto** [comment]
we had this with the net-next label.
