### ISSUE TITLE
New chaos monkey: Latency test

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5274]
- [ ] Chaos monkey to test latency to a URL or IP
   - [ ] curl a URL
   - [ ] perform a k8s apiserver operation
- [ ] Ability to configure a watermark above which test should be considered a failure

**Comment by ianvernon** [comment]
https://github.com/cilium/chaos-monkeys/pull/23

**Comment by ianvernon** [comment]
Closing ; 
https://github.com/cilium/chaos-monkeys/pull/23 is merged.
