### ISSUE TITLE
Clean up docker hub repositories

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#5279]
In case of disagreement please remove check and leave a comment bellow the repository

**The following automatic-build repositories will be deleted:**

- [X] https://hub.docker.com/r/cilium/build/
- [X] https://hub.docker.com/r/cilium/build-image/
- [X] https://hub.docker.com/r/cilium/cilium-builder-2/
- [X] https://hub.docker.com/r/cilium/cilium-runtime-2/
- [X] https://hub.docker.com/r/cilium/compose-example/
- [X] https://hub.docker.com/r/cilium/debug_shell/
- [X] https://hub.docker.com/r/cilium/docker-collector/
- [X] https://hub.docker.com/r/cilium/docker-dns-rest/
- [X] https://hub.docker.com/r/cilium/powerstrip/
- [X] https://hub.docker.com/r/cilium/runtime/
- [X] https://hub.docker.com/r/cilium/runtime-image/

**The following repositories will be deleted as they lack where the Dockerfile used to build the image is stored:**

- [ ] ~https://hub.docker.com/r/cilium/cc-grpc-demo/~
  Converted to an automatic build in https://github.com/cilium/cilium/pull/5280
- [ ] https://hub.docker.com/r/cilium/chaos-test-base/
- [X] https://hub.docker.com/r/cilium/chaos-test-daltons/
- [X] https://hub.docker.com/r/cilium/cilium-builder/
- [X] https://hub.docker.com/r/cilium/cilium-runtime/
- [ ] https://hub.docker.com/r/cilium/demo-httpd/
- [X] https://hub.docker.com/r/cilium/demo-httpd-health/
- [ ] https://hub.docker.com/r/cilium/docs-builder/
    Currently being used; has enough information to be transformed into an automatic build.
- [X] https://hub.docker.com/r/cilium/envoytest/
- [X] https://hub.docker.com/r/cilium/esindexclient/
- [X] https://hub.docker.com/r/cilium/grpc-demo/
- [X] https://hub.docker.com/r/cilium/guestbook/
- [ ] https://hub.docker.com/r/cilium/identity-scale-test/
- [ ] https://hub.docker.com/r/cilium/istio-examples-bookinfo-productpage-v2/
    Used in Istio Getting Started Guide.
- [ ] https://hub.docker.com/r/cilium/istio_pilot/
    Production Istio integration image for Istio 0.8+.
- [ ] https://hub.docker.com/r/cilium/istio_proxy/
    Production Istio integration image for Istio 0.8+.
- [ ] https://hub.docker.com/r/cilium/istio_proxy_debug/
    Production Istio integration image for Istio 0.8+.
- [ ] https://hub.docker.com/r/cilium/istio_proxy_debugv2/
    Production Istio integration image for Istio 0.7.
- [ ] https://hub.docker.com/r/cilium/istio_proxy_init/
    Production Istio integration image for Istio 0.7.
- [ ] https://hub.docker.com/r/cilium/istio_proxyv2/
    Production Istio integration image for Istio 0.7.
- [X] https://hub.docker.com/r/cilium/k8s-cni/
- [X] https://hub.docker.com/r/cilium/kafkacat/
- [X] https://hub.docker.com/r/cilium/kafkaclient/
- [X] https://hub.docker.com/r/cilium/kafkaclient2/
- [X] https://hub.docker.com/r/cilium/kafka-python-client/
- [X] https://hub.docker.com/r/cilium/mtu-update/
- [ ] https://hub.docker.com/r/cilium/nightly/
- [X] https://hub.docker.com/r/cilium/python-kafka-client/
- [X] https://hub.docker.com/r/cilium/test/
- [X] https://hub.docker.com/r/cilium/v1.2.0-rc2/

I obviously won't going to delete them without making sure they aren't used in demos/tests

**Comment by nebril** [comment]
https://hub.docker.com/r/cilium/nightly/ is an artifact from our nightly builds
