### ISSUE TITLE
Documentation: mention eBPF

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#528]
The current documentation presents BPF as a new thing without any mention of eBPF.
I don't hear people distinguishing much between classic BPF and eBPF, but IMO there is educational value for the documentation to at least mention eBPF.

**Comment by tgraf** [comment]
> The current documentation presents BPF as a new thing without any mention of eBPF.
> I don't hear people distinguishing much between classic BPF and eBPF, but IMO there is educational value for the documentation to at least mention eBPF.

Agreed. We should have an extensive section about BPF and also explain difference and origin.

**Comment by borkmann** [comment]
Makes sense, I think it could be a chapter by itself discussing this (incl. tc and xdp hook).

**Comment by borkmann** [comment]
Here's the built version from the PR, see `BPF and XDP Guide` chapter for an initial start:

http://cilium.readthedocs.io/en/doc-bpf-wip/

**Comment by aalemayhu** [comment]
Sweet, will print out and read soon. This issue can be closed when it's merged or you could also just add a `Fixes: #528` in the commit message that should close this when it hits master.

Thanks.
