### ISSUE TITLE
Add metric to account for latency of BPF compilation

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5299]
It's currently a debug but we need this to be a metric

```
                start := time.Now()
                // Compile and install BPF programs for this endpoint
                err = e.runInit(libdir, rundir, epdir, epInfoCache.ifName, debug)
                logger.WithError(err).
                        WithField(logfields.BPFCompilationTime, time.Since(start).String()).
                        Debugf("BPF compilation completed")
```

**Comment by joestringer** [comment]
Isn't this already taken into account here?

https://github.com/cilium/cilium/blob/c4edf467732baea250a7b283e50dace2e95b90d4/pkg/endpoint/policy.go#L678-L686

**Comment by tgraf** [comment]
That is the overall regeneration and it can be very misleading as the vast majority of the regeneration only require policy eval and will never compile. We can extend this with a label to mark samples that have included a compilation but we need some visibility into how long actual compilations take.

**Comment by joestringer** [comment]
@tgraf Using the `EndpointRegenerationTimeSquare`, shouldn't we be able to determine the distribution of endpoint regeneration times and observe a bimodal distribution in a graph where the higher average time would include compilation time?

I appreciate that it's not strictly the same metric, though.

**Comment by tgraf** [comment]
I'm fine using that same metric as long as we can tell whether it is the actual compilation that takes long or whether it is potentially the endpoint lock.

**Comment by joestringer** [comment]
@tgraf I see, in that case I suspect that `EndpointRegenerationTimeSquare` won't provide that level of granularity.

**Comment by tgraf** [comment]
We can return a stats structure which includes whether:
- compilation was performed
- policy eval was performed but no compilation was needed
- policy was already calculated and thus policy eval was skipped

We can then add a label for each case. That will let us show exactly what the build latency is for all three major build cases.

**Comment by joestringer** [comment]
@eloycoto Is this issue done now?

**Comment by eloycoto** [comment]
Yes, all sorted.
