### ISSUE TITLE
Request: Improve metrics by folding related metrics into a single metric, differentiated by labels

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5314]
@Kami-no suggested on slack that it would be useful to fold the l7 packet totals into a single metric that uses labels to differentiate denied/forwarded/parse_errors/received:

```
cilium_policy_l7_denied_total
cilium_policy_l7_forwarded_total
cilium_policy_l7_parse_errors_total
cilium_policy_l7_received_total
```
->
```
cilium_policy_l7_total{rule="denied"}
cilium_policy_l7_total{rule="forwarded"}
cilium_policy_l7_total{rule="parse_errors"}
cilium_policy_l7_total{rule="received"}
```

Note: The old metrics cannot be just renamed. They should be marked as deprecated and removed in a subsequent release.

**Comment by Kami-no** [comment]
also move `cilium_unreachable_health_endpoints` to `cilium_endpoint_state`
or join `cilium_unreachable_health_endpoints` and `cilium_unreachable_nodes`

**Comment by joestringer** [comment]
@Kami-no I think that those last ones are displaying distinct information:

* `cilium_unreachable_health_endpoints` reports failures in connectivity from the current node to a dedicated endpoint (hosting an HTTP API) on another node.
* `cilium_unreachable_nodes` reports failures in connectivity from the current node to another node (eg, network fabric issue).
* `cilium_endpoint_state` reports the known state of a local pod

So it's possible for `cilium_unreachable_nodes` to be 0, but there is either an L4-L7 disruption or other connectivity issue to the health endpoint on another node which results in non-zero cilium_unreachable_health_endpoints`. In this case, it is likely that the issue is within the source or destination node rather than on the underlying network between the nodes.

`cilium_endpoint_state` I believe is only reporting the state of local endpoints (eg creating, ready, disconnecting, waiting to regenerate). This doesn't have anything to do with network connectivity currently.

**Comment by Kami-no** [comment]
If `cilium_unreachable_health_endpoints` is for remote than it could be smth like this:
```
cilium_unreachable_remote{item="node"}
cilium_unreachable_remote{item="health_endpoints"}
```

**Comment by tgraf** [comment]
@Kami-no What is the benefit of merged metrics like this? I understand the first example as denied + forwarded + parse_errors = total_received and we can get rid of that label but what is the advantage to you as a user?

**Comment by Kami-no** [comment]
When you make a dashboard in grafana with "remote problems" you need only one query for the graph.
When new labels for the metric will be created it'll appear in dashboard without human.

**Comment by tgraf** [comment]
Good point. That definitely makes sense and I agree with the proposal then.
