### ISSUE TITLE
`Cilium monitor -t drop` doesn't show L7 drops

### ISSUE THREAD

**Issue by techcet** [cilium/cilium#5320]
### Title

`Cilium monitor -t drop` doesn't show L7 drops

### General Information

- Cilium version (run `cilium version`)
root@minikube:~# cilium version 
Client: 1.2.0 23fde20 2018-08-15T17:30:44+02:00 go version go1.10.3 linux/amd64
Daemon: 1.2.0 23fde20 2018-08-15T17:30:44+02:00 go version go1.10.3 linux/amd64

- Kernel version (run `uname -a`)

minikube v0.28.0

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:43Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
http://docs.cilium.io/en/v1.2/gettingstarted/minikube/

### How to reproduce the issue

1. Deploy SW app
2. Implement L7 policy from GSG
3. Run `cilium monitor -t drop`
4. Run `kubectl exec tiefighter -- curl -s -XPUT deathstar.default.svc.cluster.local/v1/exhaust-port`. Policy will deny traffic and return "Access denied" but no entry shows in `cilium monitor` output.

[cilium-sysdump-20180823-083758.zip](https://github.com/cilium/cilium/files/2315171/cilium-sysdump-20180823-083758.zip)

**Comment by tgraf** [comment]
They are not drops. You need to run with `-t l7`.
