### ISSUE TITLE
`Cilium policy trace` result conflicts with actual behaviour

### ISSUE THREAD

**Issue by techcet** [cilium/cilium#5327]
### General Information

- Cilium version (run `cilium version`)
``` # cilium version
Client: 1.2.0 23fde20 2018-08-15T17:30:44+02:00 go version go1.10.3 linux/amd64
Daemon: 1.2.0 23fde20 2018-08-15T17:30:44+02:00 go version go1.10.3 linux/amd64
```
[cilium-sysdump-20180823-192558.zip](https://github.com/cilium/cilium/files/2316811/cilium-sysdump-20180823-192558.zip)

[test0yaml.txt](https://github.com/cilium/cilium/files/2316813/test0yaml.txt)
[kube-dnsyaml.txt](https://github.com/cilium/cilium/files/2316814/kube-dnsyaml.txt)

### How to reproduce the issue
1. deploy starwars http gsg app
2. deploy kube-dns.yaml allow policy
3. deploy ingress policy test0.yaml
4. run `cilium monitor -t -drop` and 
5. run `kubectl exec tiefighter -ti -- curl -s -XPOST deathstar.default.svc.cluster.local/v1/request-landing`

6. observe:  xx drop (Policy denied (L3)) flow 0xdaa177e1 to endpoint 0, identity 29687->55020: 10.15.187.0:57826 -> 10.15.209.16:80 tcp SYN
xx drop (Policy denied (L3)) flow 0x37327629 to endpoint 0, identity 29687->55020: 10.15.187.0:57826 -> 10.15.209.16:80 tcp SYN

7. run `cilium policy get`:

```# cilium policy trace --src-identity 29687 --dst-identity 55020 
----------------------------------------------------------------
Tracing From: [k8s:class=tiefighter, k8s:org=empire, k8s:io.kubernetes.pod.namespace=default, k8s:io.cilium.k8s.policy.serviceaccount=default] => To: [k8s:class=deathstar, k8s:io.cilium.k8s.policy.serviceaccount=default, k8s:io.kubernetes.pod.namespace=default, k8s:org=empire]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"default"}}: selected
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"default"}}: selected
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"default"}}
      Found all required labels
+       No L4 restrictions
2/2 rules selected
Found allow rule
Label verdict: allowed
L4 ingress policies skipped

Final verdict: ALLOWED
```

**Comment by tgraf** [comment]
This is an egress drop and policy trace does not support egress yet. Duplicate of https://github.com/cilium/cilium/issues/3394
