### ISSUE TITLE
Map security identities to labels in `cilium monitor -t drop` messages

### ISSUE THREAD

**Issue by techcet** [cilium/cilium#5349]
### Title

Improve cilium monitor -t drop messages

### Description of requested functionality

L7 flow entries show great information on src/dst labels for drop. It would be great to provide similar user-friendly data in the L3 drops.

### Example use cases

User visibility and simplified troubleshooting. 

e.g. 
 L7 deny logs show tons of informative data:
```# cilium monitor -t l7  
Listening for events on 2 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
<- Request http from 0 ([k8s:io.cilium.k8s.policy.serviceaccount=default k8s:class=tiefighter k8s:io.kubernetes.pod.namespace=default k8s:org=empire]) to 46872 ([k8s:class=deathstar k8s:org=empire k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default]), identity 21945->49776, verdict Denied PUT http://deathstar.default.svc.cluster.local/v1/exhaust-port => 403
```

but L3 drop logs require the user to map numerical identities to labels:

``` xx drop (Policy denied (L3)) flow 0x627de7f0 to endpoint 0, identity 3062->2: 10.15.56.202:33598 -> 64.233.185.100:80 tcp SYN```

**Comment by lkpdn** [comment]
@joestringer 
Hi, I'm just curious but do you think it's acceptable to change `perfEventReader` (or `listener{v1_0, v1_2}` drainers) behaviour to be more flexible like:
- do not queue (and drain) the read data as is but redefine the notification messages in golang struct
- then do `LookupIdentityByID()` as needed, send to cilium-monitor via gob as current NodeMonitor's drainer does

Not only this particular Issue but any other similar ones would become easily handled once this change be done. Any thoughts on this?

**Comment by joestringer** [comment]
Hi @lkpdn, at a glance that sounds like a reasonable approach, though I'll defer to @raybejjani / @nebril (@cilium/monitor team) who are more familiar with this area to see if they have any thoughts/guidance.

**Comment by lkpdn** [comment]
OK, thanks. Maybe I'll cook a PR then.
