### ISSUE TITLE
proposal: update Cilium requirements to use go 1.11

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5366]
Go 1.11 has been released: https://golang.org/doc/go1.11

We should see if we can leverage it in Cilium. 

* Update Documentation
* See if any code changes are needed in Cilium
* Update packer-ci-build to consume this
* Update Cilium builder images to contain go 1.11

**Comment by joestringer** [comment]
Are there particular features we wish to take advantage of?

**Comment by ianvernon** [comment]
@joestringer I'm interested in how we can utilize go modules, but it is still experimental. I'd love to be able to move away from having the `vendor` directory in our repo.
