### ISSUE TITLE
proposal: explore use of go modules for dependencies in Cilium

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5367]
Now that go 1.11 has been released ( https://golang.org/doc/go1.11 ) we can explore whether using go modules is feasible for Cilium: https://golang.org/doc/go1.11#modules

**Comment by aanm** [comment]
I think we should hold on changing to go modules as it doesn't currently support importing a package that is used for code-generation, e.g., k8s code-generator.

**Comment by joestringer** [comment]
@aanm any progress on this?

EDIT: Maybe this helps?
https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by aanm** [comment]
@joestringer 

https://github.com/golang/go/issues/27271

https://github.com/golang/go/issues/27272

and https://github.com/kubernetes/kubernetes/issues/63607

**Comment by glibsm** [comment]
As of writing this comment, k8s is fully on go modules, including code generation and local import paths through a clever use of `replace`.
