### ISSUE TITLE
Documentation: maybe mention dependencies for building or create new target `setup`?

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#538]
I tried building the docs but got the following error

```bash
Extension error:
Could not import extension sphinxcontrib.openapi (exception: No module named sphinxcontrib.openapi)
```

This was easily fixed by `pip install sphinxcontrib-openapi`.

Others might be experiencing more errors. Users shouldn't need to build the
manuals themselves but contributors might need / want to and having a smooth
path to go from new setup to building the manual is worth it. Not sure if the
best place is listing the packages / modules required in the documentation or
just installing them with pip in the Makefile. @danwent what do you think?

**Comment by tgraf** [comment]
The required modules are listed in the `requirements.txt` which readthedocs.io will respect. We can add a check to the Makefile and suggest to run `pip install` if `pip list` does not list the required packages.
