### ISSUE TITLE
Cilium upgrade does not proceed when a node is lost

### ISSUE THREAD

**Issue by techcet** [cilium/cilium#5390]
Encountered an issue with Cilium upgrade when a node is lost. Updated the Cilium DaemonSet and the older Cilium containers proceeded to terminate. One out of 6 did not, and it appears because a node is `NotReady` and the node is lost. New Cilium agents never came up.

Also, cluster-diagnosis takes more than 35 mins to run. 

- Cilium version (run `cilium version`)
-> moving from 1.2.0-rc3 to 1.2.1

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:43Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

### How to reproduce the issue

1. Have older Cilium release installed (like 1.2.0-rc3)
2. With one node lost, edit ds for Cilium image 1.2.1.

**Comment by tgraf** [comment]
@techcet What exactly is your expectation? The node is lost and the apiserver cannot give the instruction to that node to shut down the cilium pod. I'm not sure Cilium can do much here.

**Comment by techcet** [comment]
@tgraf It was a worker node that was lost so I expected all the other nodes to bring up Cilium agents.

**Comment by tgraf** [comment]
The DaemonSet as shipped in 1.2 includes a `maxUnavailable: 2` update strategy which would likely prevent this as it would cause k8s to bring up cilium pods before all pods are shut down. It's not really Cilium that prevents the bootstrapping from happening. The default behavior of k8s is to wait with starting new pods until all replicas of an old DaemonSet have been shut down.
