### ISSUE TITLE
Feature: Allow running with IPv6 disabled

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#542]
- [ ] Automatically disable IPv6 support if IPv6 is disabled in kernel
- [ ] Disable IPv6 if system has IPv6 disabled or if `--disable-ipv6` flag is specified

If the system has IPv6 disabled (`net.ipv6.conf.all.disable_ipv6 = 1`) cilium will currently fail because addition of IPv6 addresses will fail:

```
cilium           | + ip addr add f00d::a00:20f:0:ffff/128 dev cilium_host
cilium           | RTNETLINK answers: Permission denied
cilium           | ERRO Error while initializing daemon: exit status 2
cilium           | CRIT Error while creating daemon: exit status 2
```

**Comment by ianvernon** [comment]
@tgraf can this be closed given your recent work?

**Comment by tgraf** [comment]
This has been completed
