### ISSUE TITLE
Tunnel routes for remote nodes are not removed when the node is removed

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5421]
Reported by @anitgandhi:

The `deleteIPRoute()` call at the top of the following code only handles removing the IPv6 route for the specified node:

https://github.com/cilium/cilium/blob/ba414289ecebd7e9fb1adbca91e857d8fc72b3cd/pkg/node/manager.go#L304-L308

So, when the node is removed from the clusterConfiguration and `replaceHostRoutes()` is called, it will not remove the local routes which direct traffic for the remote node into the `cilium_host` device:

https://github.com/cilium/cilium/blob/ba414289ecebd7e9fb1adbca91e857d8fc72b3cd/pkg/node/manager.go#L156-L170

This at least affects 1.2, we may want to also consider backporting further. I don't know how much further a solution may smoothly backport.

**Comment by tgraf** [comment]
I was originally hesitant to remove the routes so we don't just stop all communication just because a node is temporarily lost but given that we back it up with the kvstore these days I think it's fine to remove the routes.
