### ISSUE TITLE
value of numWorkerThreads

### ISSUE THREAD

**Issue by jiaxuanzhou** [cilium/cilium#5429]
https://github.com/cilium/cilium/blob/ba414289ecebd7e9fb1adbca91e857d8fc72b3cd/daemon/daemon.go#L1672
due to the definitions, should not the value of numWorkerThreads inited to 4?

**Comment by aanm** [comment]
Hey @jiaxuanzhou , the definition is not correct. `numWorkerThreads` should be initiated with 2. Feel free to make a pull request with that fix :smiley:
