### ISSUE TITLE
endpoint: save headerfile contents in memory to avoid hashing to determine if program recompilation is needed

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5438]
We can store the current state of the endpoint headerfile in some type of "realized state" within the endpoint. When computing policy, we can populate the endpoint's "desired state" for its headerfile. This will reduce the amount of IO we have to perform, specifically hashing headerfile contents from the host and comparing with the next headerfile for the endpoint.

The following dummy `lxc_config.h` contains a list of fields that are necessary to examine to see if they have changed:

https://github.com/cilium/cilium/blob/716730cd4c8db1eb55c85a392febcda4ae8a880e/bpf/lxc_config.h#L23-L62

**Comment by ianvernon** [comment]
Endpoint fields which are used during compilation:

* LXCMac
* IPv6
* IPv4
* NodeMAC
* Endpoint ID (host and network byte order)
* Security Identity (host and network byte order)
* Policy map
* Calls map
* CT Map Size
* CT Map 6
* CT Map 4
* LB_L3 (always enabled)
* LB_L4 (always enabled)
* IPCACHE_6_PREFIXES
* IPCACHE_4_PREFIXES

And the configurable endpoint options:

* ConntrackAccounting
* ConntrackLocal
* Conntrack
* Debug
* DebugLB
* DropNotify
* TraceNotify
* MonitorAggregation
* NAT46

**Comment by joestringer** [comment]
For what it's worth, `bpf/lxc_config.h` may be out-of-date compared to exactly what is generated in a real config file. Might be good to get a real, generated `lxc_config.h` file to compare.

**Comment by ianvernon** [comment]
Removing this from v1.4 since this wasn't completed in v1.4.

**Comment by ianvernon** [comment]
This was practically achieved via both the hashing of the configuration options for the endpoint in memory, as well as ensuring that we only write the headerfile for the endpoint if it hasn't been written, or the actual options have changed in https://github.com/cilium/cilium/pull/8268 . Closing.
