### ISSUE TITLE
Downgrade from 1.2 to 1.0 requires CT  clean state

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#5454]
### General Information

#5197 
#5230

Upstream fixes exist (above PRs) but a direct backport would have required a larger rework then simply pushing patches onto 1.x branches. To resolve this,
```
During the release meeting, we suggested rather than backporting as-is to 1.0, we can reduce the scope of changes by instead creating a version of CLEAN_CILIUM_STATE that just removes BPF-related pieces, and document that users should set this variable to true when downgrading from 1.2 or later.
```

### How to reproduce the issue

Downgrade from 1.2 to 1.0 on a newer kernel with LRU support.

**Comment by jrfastab** [comment]
Update description and title to only include 1.0 the 1.1 has necessary patches.

**Comment by joestringer** [comment]
Just need #5504 merged and a minor doc change to set `clean-cilium-bpf-state` to true.
