### ISSUE TITLE
 runtime.RuntimeVerifier runs the kernel verifier against the tree copy of the BPF datapath

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#5472]
I think `RuntimePolicies_TestsEgressToHost_Tests_Egress_To_Host` ran before this, grepping for the minute timestamps (`grep -inr '2018-09-01T15:47' *`) but the logs there look ok, although the cilium logs end sooner than the test logs.

Since the verifier test simply restarts cilium once it is done, and the only endpoint is the health endpoint, it's a little odd to me.

https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1540/testReport/junit/(root)/runtime/RuntimeVerifier_runs_the_kernel_verifier_against_the_tree_copy_of_the_BPF_datapath/

```
Stacktrace
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:306
restarting Cilium failed
Expected
    <*errors.errorString | 0xc4204dc1f0>: {
        s: "Endpoints are not ready after timeout",
    }
to be nil
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:110
Standard Output
Standard Error

```
<details>
==> runtime: Running provisioner: shell...
    runtime: Running: inline script
==> runtime: Running provisioner: file...
==> runtime: Running provisioner: shell...
    runtime: Running: /tmp/vagrant-shell20180901-14720-1q7e9az.sh
    runtime: updating /etc/resolv.conf
    runtime: compiling cilium...
    runtime: can't load package: package github.com/cilium/cilium/test/bpf: C source files not allowed when not using cgo or SWIG: bpf-event-test.c unit-test.c
    runtime: go tool vet api pkg envoy plugins bpf cilium daemon monitor cilium-health bugtool
    runtime: contrib/scripts/check-ineffassign.sh
    runtime: contrib/scripts/check-fmt.sh
    runtime: contrib/scripts/check-log-newlines.sh
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/envoy'
    runtime: rm -f ./bazel-bin/envoy ./bazel-bin/istio-envoy ./istio-envoy ./bazel-bin/cilium_integration_test \
    runtime: 	Dockerfile.istio_proxy \
    runtime: 	Dockerfile.istio_proxy_debug
    runtime: rm -f bazel-out/k8-fastbuild/bin/_objs/envoy/external/envoy/source/common/common/version_linkstamp.o
    runtime: bazel  build --experimental_strict_action_env --local_resources 2048,2.0,1.0 //:envoy 2>&1 | grep -v -e "bazel-out/.*/genfiles/external/.*: warning: directory does not exist."
    runtime: Starting local Bazel server and connecting to it...
    runtime: ..................
    runtime: Loading: 
    runtime: Loading: 0 packages loaded
    runtime: Loading: 0 packages loaded
    runtime:     currently loading: 
    runtime: Analyzing: target //:envoy (6 packages loaded)
    runtime: Analyzing: target //:envoy (8 packages loaded)
    runtime: External dependency cache directory /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f
    runtime: make[2]: Entering directory '/home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps'
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/benchmark.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/libevent.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gperftools.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/luajit.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/nghttp2.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/yaml-cpp.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/zlib.dep.env
    runtime: make[2]: Leaving directory '/home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps'
    runtime: 
    runtime: real	0m0.517s
    runtime: user	0m0.000s
    runtime: sys	0m0.000s
    runtime: Analyzing: target //:envoy (56 packages loaded)
    runtime: DEBUG: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy/bazel/repositories.bzl:106:5: Fetching external dependencies...
    runtime: DEBUG: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy/bazel/repositories.bzl:112:5: 
    runtime: DEBUG: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy/bazel/repositories.bzl:113:5: External dependency cache directory /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f
    runtime: make[2]: Entering directory '/home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps'
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/cares.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/benchmark.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/libevent.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/gperftools.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/luajit.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/nghttp2.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/yaml-cpp.dep.env
    runtime: No need to rebuild /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e380
    runtime: 73dd9828a920a71f484/external/envoy_deps_cache_2c744dffd279d7e9e0910ce594eb4f4f/zlib.dep.env
    runtime: make[2]: Leaving directory '/home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy_deps'
    runtime: 
    runtime: real	0m0.517s
    runtime: user	0m0.000s
    runtime: sys	0m0.000s
    runtime: DEBUG: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/envoy/bazel/repositories.bzl:114:5: External dep build exited with return code: 0
    runtime: Analyzing: target //:envoy (73 packages loaded)
    runtime: Analyzing: target //:envoy (103 packages loaded)
    runtime: Analyzing: target //:envoy (248 packages loaded)
    runtime: WARNING: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/com_github_grpc_grpc/BUILD:1972:1: in srcs attribute of cc_library rule @com_github_grpc_grpc//:grpc_nanopb: please do not import '@com_github_grpc_grpc//third_party/nanopb:pb_common.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl:172:12
    runtime: WARNING: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/com_github_grpc_grpc/BUILD:1972:1: in srcs attribute of cc_library rule @com_github_grpc_grpc//:grpc_nanopb: please do not import '@com_github_grpc_grpc//third_party/nanopb:pb_decode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl:172:12
    runtime: WARNING: /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/com_github_grpc_grpc/BUILD:1972:1: in srcs attribute of cc_library rule @com_github_grpc_grpc//:grpc_nanopb: please do not import '@com_github_grpc_grpc//third_party/nanopb:pb_encode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /home/vagrant/.cache/bazel/_bazel_vagrant/502ef5068e38073dd9828a920a71f484/external/com_github_grpc_grpc/bazel/grpc_build_system.bzl:172:12
    runtime: Analyzing: target //:envoy (295 packages loaded)
    runtime: INFO: Analysed target //:envoy (300 packages loaded).
    runtime: INFO: Found 1 target...
    runtime: [0 / 2] [-----] BazelWorkspaceStatusAction stable-status.txt
    runtime: [4 / 86] [-----] BazelWorkspaceStatusAction stable-status.txt
    runtime: [10 / 177] Compiling external/com_google_protobuf/src/google/protobuf/util/field_comparator.cc [for host]; 0s linux-sandbox ... (2 actions, 1 running)
    runtime: [16 / 177] Compiling external/com_google_protobuf/src/google/protobuf/stubs/common.cc [for host]; 0s linux-sandbox ... (2 actions running)
    runtime: [23 / 177] Compiling external/com_google_protobuf/src/google/protobuf/io/zero_copy_stream.cc [for host]; 0s linux-sandbox ... (2 actions running)
    runtime: [31 / 177] Compiling external/com_google_protobuf/src/google/protobuf/util/internal/json_escaping.cc [for host]; 0s linux-sandbox ... (2 actions running)
    runtime: [39 / 177] Compiling external/com_google_protobuf/src/google/protobuf/stubs/strutil.cc [for host]; 1s linux-sandbox ... (2 actions running)
    runtime: [46 / 177] Compiling external/com_google_protobuf/src/google/protobuf/dynamic_message.cc [for host]; 1s linux-sandbox ... (2 actions running)
    runtime: [52 / 177] Compiling external/com_google_protobuf/src/google/protobuf/message.cc [for host]; 0s linux-sandbox ... (2 actions running)
    runtime: [59 / 177] Compiling external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_message.cc [for host]; 0s linux-sandbox ... (2 actions running)
    runtime: [67 / 177] Compiling external/com_google_protobuf/src/google/protobuf/compiler/ruby/ruby_generator.cc [for host]; 0s linux-sand
    runtime: box ... (2 actions running)
    runtime: [76 / 177] Compiling external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_field.cc [for host]; 0s linux-sandbox ... (2 actions running)
    runtime: [82 / 177] Compiling external/com_google_protobuf/src/google/protobuf/descriptor.cc [for host]; 6s linux-sandbox ... (2 actions running)
    runtime: [89 / 177] Compiling external/com_google_protobuf/src/google/protobuf/compiler/cpp/cpp_file.cc [for host]; 3s linux-sandbox ... (2 actions running)
    runtime: [101 / 177] Compiling external/com_google_protobuf/src/google/protobuf/compiler/csharp/csharp_field_base.cc [for host]; 1s linux-sandbox ... (2 actions running)
    runtime: [110 / 177] Compiling external/com_google_protobuf/src/google/protobuf/compiler/csharp/csharp_message_field.cc [for host]; 0s linux-sandbox ... (2 actions running)
    runtime: [124 / 177] Compiling external/com_google_protobuf/src/google/protobuf/util/type_resolver_util.cc [for host]; 1s linux-sandbox ... (2 actions running)
    runtime: [139 / 177] Compiling external/com_google_protobuf/src/google/protobuf/compiler/objectivec/objectivec_generator.cc [for host]; 0s linux-sandbox ... (2 actions running)
    runtime: [158 / 177] Compiling external/com_google_protobuf/src/google/protobuf/compiler/objectivec/objectivec_extension.cc [for host]; 1s linux-sandbox ... (2 actions running)
    runtime: [625 / 834] no action
    runtime: Target //:envoy up-to-date:
    runtime:   bazel-bin/envoy
    runtime: INFO: Elapsed time: 153.667s, Critical Path: 11.03s
    runtime: INFO: 186 processes: 183 linux-sandbox, 3 local.
    runtime: INFO: Build completed successfully, 189 total actions
    runtime: INFO: Build completed successfully, 189 total actions
    runtime: make -f Makefile.api all
    runtime: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/envoy'
    runtime: make[2]: Nothing to be done for 'all'.
    runtime: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/envoy'
    runtime: bazel shutdown
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/envoy'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins'
    runtime: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
    runtime: go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.2.90 9a2555a35 2018-08-31T19:57:40+02:00 go version go1.10.3 linux/amd64"' -tags lockdebug -o cilium-docker
    runtime: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
    runtime: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
    runtime: # Compile without cgo to allow use of cilium-cni on non-glibc platforms - see GH-5055
    runtime: CGO_ENABLED=0 go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.2.90 9a2555a35 2018-08-31T19:57:40+02:00 go version go1.10.3 linux/amd64"' -tags lockdebug -o cilium-cni ./cilium-cni.go
    runtime: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
    runtime: set -e; \
    runtime:  :  " [-DSKIP_DEBUG]"; clang -DSKIP_DEBUG -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o /dev/null bpf_lxc.ll;   :  " [-DHAVE_LPM_MAP_TYPE]"; clang -DHAVE_LPM_MAP_TYPE -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o /dev/null bpf_lxc.ll;   :  " [-DHAVE_LRU_MAP_TYPE]"; clang -DHAVE_LRU_MAP_TYPE -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lxc.c -o bpf_lxc.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o /dev/null bpf_lxc.ll; 
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: clang -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lxc.c -o bpf_lxc.ll
    runtime: llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o bpf_lxc.o bpf_lxc.ll
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: clang -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_netdev.c -o bpf_netdev.ll
    runtime: llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o bpf_netdev.o bpf_netdev.ll
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: clang -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_overlay.c -o bpf_overlay.ll
    runtime: llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o bpf_overlay.o bpf_overlay.ll
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: set -e; \
    runtime:  :  " [-DSKIP_DEBUG]"; clang -DSKIP_DEBUG -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lb.c -o bpf_lb.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o /dev/null bpf_lb.ll;   :  " [-DLB_L3]"; clang -DLB_L3 -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lb.c -o bpf_lb.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o /dev/null bpf_lb.ll;   :  " [-DLB_L4]"; clang -DLB_L4 -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lb.c -o bpf_lb.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o /dev/null bpf_lb.ll;   :  " [-DLB_L3]"; clang -DLB_L3 -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lb.c -o bpf_lb.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o /dev/null bpf_lb.ll;   :  " [-DLB_L4]"; clang -DLB_L4 -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lb.c -o bpf_lb.ll; llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o /dev/null bpf_lb.ll; 
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: '
    runtime: probe
    runtime: ' is not a recognized processor for this target
    runtime:  (ignoring processor)
    runtime: clang -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_lb.c -o bpf_lb.ll
    runtime: llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o bpf_lb.o bpf_lb.ll
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: clang -Iinclude -I. -D__NR_CPUS__=2 -O2 -g -target bpf -emit-llvm -Wall -Werror -Wno-address-of-packed-member -Wno-unknown-warning-option -c bpf_xdp.c -o bpf_xdp.ll
    runtime: llc -march=bpf -mcpu=probe -mattr=dwarfris -filetype=obj -o bpf_xdp.o bpf_xdp.ll
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: 'probe' is not a recognized processor for this target (ignoring processor)
    runtime: gcc -Wall -O2 -Wno-format-truncation -I include/ cilium-map-migrate.c -lelf -o cilium-map-migrate
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium'
    runtime: go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.2.90 9a2555a35 2018-08-31T19:57:40+02:00 go version go1.10.3 linux/amd64"' -tags lockdebug -o cilium
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
    runtime: ../contrib/scripts/bindata.sh 7a69e06ed046704562d6983fb3807f63eb76332f
    runtime: go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.2.90 9a2555a35 2018-08-31T19:57:40+02:00 go version go1.10.3 linux/amd64"' -tags lockdebug -o cilium-agent
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/monitor'
    runtime: go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.2.90 9a2555a35 2018-08-31T19:57:40+02:00 go version go1.10.3 linux/amd64"' -tags lockdebug -o cilium-node-monitor
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/monitor'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium-health'
    runtime: go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.2.90 9a2555a35 2018-08-31T19:57:40+02:00 go version go1.10.3 linux/amd64"' -tags lockdebug -o cilium-health
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium-health'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/bugtool'
    runtime: go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.2.90 9a2555a35 2018-08-31T19:57:40+02:00 go version go1.10.3 linux/amd64"' -tags lockdebug -o cilium-bugtool
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bugtool'
    runtime: MAKE=make contrib/scripts/check-cmdref.sh
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
    runtime: # We don't know what changed so recreate the directory
    runtime: rm -rvf /tmp/tmp.hTYZU3b6QR/cilium*
    runtime: ../cilium/cilium cmdref -d /tmp/tmp.hTYZU3b6QR
    runtime: ../bugtool/cilium-bugtool cmdref -d /tmp/tmp.hTYZU3b6QR
    runtime: ../daemon/cilium-agent --cmdref /tmp/tmp.hTYZU3b6QR
    runtime: level=info msg="Detected MTU 1500" subsys=mtu
    runtime: ../cilium-health/cilium-health --cmdref /tmp/tmp.hTYZU3b6QR
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
    runtime: contrib/scripts/lock-check.sh
    runtime: make -C Documentation/ dummy SPHINXOPTS="-q" 2>&1 | grep -v "tabs assets"
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
    runtime: Documentation dependency 'snowballstemmer' not found.
    runtime: Run 'pip install -r Documentation/requirements.txt'
    runtime: Makefile:25: recipe for target 'check-requirements' failed
    runtime: make[1]: *** [check-requirements] Error 2
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
    runtime: Build finished.
    runtime: installing cilium...
    runtime: can't load package: package ./test/bpf: C source files not allowed when not using cgo or SWIG: bpf-event-test.c unit-test.c
    runtime: install -m 0755 -d /usr/bin
    runtime: for i in envoy plugins bpf cilium daemon monitor cilium-health bugtool; do make -C $i install; done
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/envoy'
    runtime: install -m 0755 -d /usr/bin
    runtime: install -m 0755 -T ./bazel-bin/envoy /usr/bin/cilium-envoy
    runtime: strip /usr/bin/cilium-envoy
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/envoy'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins'
    runtime: for i in cilium-docker cilium-cni; do make -C $i install; done
    runtime: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
    runtime: install -m 0755 cilium-docker /usr/bin
    runtime: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
    runtime: make[2]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
    runtime: install -m 0755 -d /etc/cni/net.d
    runtime: install -m 0644 05-cilium-cni.conf /etc/cni/net.d
    runtime: install -m 0755 -d /opt/cni/bin
    runtime: install -m 0755 cilium-cni /opt/cni/bin
    runtime: make[2]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/plugins'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
    runtime: install -m 0755 cilium-map-migrate /usr/bin
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium'
    runtime: install -m 0755 -d /usr/bin
    runtime: install -m 0755 cilium /usr/bin
    runtime: install -m 0755 -d /etc/bash_completion.d
    runtime: ./cilium generate-bash-completion > bash_autocomplete
    runtime: install -m 0644 -T bash_autocomplete /etc/bash_completion.d/cilium
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
    runtime: groupadd -f cilium
    runtime: install -m 0755 -d /usr/bin
    runtime: install -m 0755 cilium-agent /usr/bin
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/daemon'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/monitor'
    runtime: install -m 0755 -d /usr/bin
    runtime: install -m 0755 cilium-node-monitor /usr/bin
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/monitor'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium-health'
    runtime: install -m 0755 -d /usr/bin
    runtime: install -m 0755 cilium-health /usr/bin
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/cilium-health'
    runtime: make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/bugtool'
    runtime: install -m 0755 -d /usr/bin
    runtime: install -m 0755 cilium-bugtool /usr/bin
    runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bugtool'
    runtime: service cilium-consul.service
    runtime: Created symlink /etc/systemd/system/multi-user.target.wants/cilium-consul.service -> /etc/systemd/system/cilium-consul.service.
    runtime: service cilium-docker.service
    runtime: Created symlink /etc/systemd/system/multi-user.target.wants/cilium-docker.service -> /etc/systemd/system/cilium-docker.service.
    runtime: service cilium-etcd.service
    runtime: Created symlink /etc/systemd/system/multi-user.target.wants/cilium-etcd.service -> /etc/systemd/system/cilium-etcd.service.
    runtime: service cilium.service
    runtime: Created symlink /etc/systemd/system/multi-user.target.wants/cilium.service -> /etc/systemd/system/cilium.service.
    runtime: service sys-fs-bpf.mount
    runtime: Created symlink /etc/systemd/system/multi-user.target.wants/sys-fs-bpf.mount -> /etc/systemd/system/sys-fs-bpf.mount.
    runtime: running "sudo adduser vagrant cilium" 
    runtime: Adding user `vagrant' to group `cilium' ...
    runtime: Adding user vagrant to group cilium
    runtime: Done.
STEP: Stopping Cilium
STEP: Building BPF objects from the tree
STEP: Running the verifier test script
=== Test Finished at 2018-09-01T15:56:03Z====
STEP: Restarting Cilium
</details>

[test_results_master_1540_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/2348106/test_results_master_1540_BDD-Test-PR.zip)

**Comment by ianvernon** [comment]
Stale issue. Hasn't been observed in almost 2 months. Got approval from @raybejjani to close.
