### ISSUE TITLE
CI: Failed to compile bpf_lxc.o: signal: killed

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#5492]
I got this error in one of the builds.

I don't know why it did happen nor if it's a real bug.

[cb2dcde2_K8sUpdates_Updating_Cilium_stable_to_master.zip](https://github.com/cilium/cilium/files/2356024/cb2dcde2_K8sUpdates_Updating_Cilium_stable_to_master.zip)

Build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/779/
PR: https://github.com/cilium/cilium/pull/5430

**Comment by joestringer** [comment]
Seems like the process was terminated by something. Not sure if this is how it shows if context deadline is exceeded from Cilium Golang code, or could otherwise occur if for example there is memory pressure and the kernel OOM-killer kills the clang process (Check the kernel logs?).

**Comment by tgraf** [comment]
This is a DUP of #5489

**Comment by joestringer** [comment]
Closing as duplicate.
