### ISSUE TITLE
Better error message with link to FAQ entry when no IP is available

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5516]
The error

```
level=fatal msg="Error while allocating cilium-health IP" error="range is full" subsys=daemon
```

is an indication of a host misconfiguration which does not allow CIlium to use any IPs out of the proposed range. This is typically the case when a local route hinders use of any of the IPs. We can check for the number of available IPs and error out specifically if none are available and point to a FAQ or doc entry which explains the situation.

**Comment by joestringer** [comment]
Here's a FAQ, I can improve the log message and also add a comment there: https://github.com/cilium/cilium/issues/5517

**Comment by joestringer** [comment]
Also, this error is inherited from k8s vendor library but maybe we can wrap it better:

```
$ git grep "range is full" vendor
vendor/k8s.io/kubernetes/pkg/registry/core/service/ipallocator/allocator.go:    ErrFull              = errors.New("range is full")
```
