### ISSUE TITLE
Respect isolation setting in Namespace spec

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#552]
If Kubernetes NetworkPolicy is loaded, only apply them if isolation is set to `DefaultDeny`

```
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    net.beta.kubernetes.io/network-policy: |
      {
        "ingress": {
          "isolation": "DefaultDeny"
        }
      }
```

**Comment by danwent** [comment]
hehe, was just thinking I needed to send a note on this... great to see its already in plan.

**Comment by tgraf** [comment]
The namespace annotation was dropped for k8s 1.7 GA. Deferring to 0.10 until situation is clear.

**Comment by tgraf** [comment]
Given upstream k8s has dropped this annotation, closing for now.
