### ISSUE TITLE
Potential bug in service translation after label and/or backend IP update

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#5524]
0. eks
1. deploy kube-dns
2. deploy cilium
3. change labels of kube-dns
4. delete old kube-dns replica set

check if cilium has same old kube-dns service IP with new kube-dns IPs. The bug might be a missed service IP-backend IP translation.

cilium version 1.2.2

**Comment by tgraf** [comment]
@aanm Can you be more specific on what exactly you changed? We are relying load-balancing on the endpoints resource so changing pod or deployment labels will not matter. I assume you did not change the endpoints resource directly.

**Comment by aanm** [comment]
@tgraf by changing the labels of kube-dns a new pod is created, with a new IP. Is the new IP in the service map and being loadbalanced correctly?

Also, before executing step 4, is the old IP still in the loadbalancer map and being loadbalanced correctly?

**Comment by tgraf** [comment]
> by changing the labels of kube-dns a new pod is created, with a new IP. Is the new IP in the service map and being loadbalanced correctly?

That's basically the same as scaling up the backends, i.e. adding more backends. So it should be covered by the following chaos monkey. Right?
https://github.com/cilium/chaos-monkeys/tree/master/monkeys/shuffler

> Also, before executing step 4, is the old IP still in the loadbalancer map and being loadbalanced correctly?

It would have to be. Did you observe anything else?

**Comment by aanm** [comment]
@tgraf the bug was that dns requests were not being served. there was no policy involved at that time.

**Comment by tgraf** [comment]
@nebril @joestringer is currently looking into the et-call-google failures. Please start looking into this. We also see failures of the shuffler chaos monkey which could be related to this so I would recommend looking into those first.

**Comment by eloycoto** [comment]
Hi, 

My two cents here, I added a service connectivity test for kubernetes, and some connectivity lost during the scale up: 

Deployment scale:
```
time="2018-10-04T10:10:21Z" level=debug msg="running command: kubectl scale deployment app1 --replicas=4"
cmd: "kubectl scale deployment app1 --replicas=4" exitCode: 0 duration: 163.850599ms stdout:
deployment.extensions/app1 scaled
```

Test failed:
```
time="2018-10-04T10:10:21Z" level=info msg="WaitforPods: pods are not ready" data="true false false true true true" filter="-l zgroup=testapp" namespace=default
cmd: "kubectl exec -n default app2-69f6b59665-fdrfx -- curl -s -D /dev/stderr --fail --connect-timeout 3 --max-time 8 http://10.106.6.22/public -w \"time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'\"" exitCode: 28 duration: 3.209974917s stdout:
time-> DNS: '0.000019()', Connect: '0.000000',Transfer '0.000000', total '3.000636'
stderr:
command terminated with exit code 28
```

Pod autoscaled to 2:
```
STEP: Autoscaling app1 to 2 replicas
time="2018-10-04T10:10:27Z" level=debug msg="running command: kubectl scale deployment app1 --replicas=2"
cmd: "kubectl scale deployment app1 --replicas=2" exitCode: 0 duration: 195.913743ms stdout:
deployment.extensions/app1 scaled
```

Looks like that something is not correct when a new pods are added and connectivity is lost in the middle. 

Changes: 
https://github.com/cilium/cilium/pull/5765
Error: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/6944/

**Comment by tgraf** [comment]
Shuffler chaos monkey did not reveal any failures in the last 18h. Closing.
