### ISSUE TITLE
endpoint: have controller which attempts regeneration if past builds failed

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5526]
* Summary
    * This controller would check what state the endpoint was in, and if the state is any state indicating the endpoint needs to be regenerated, try to regenerate the endpoint. If the endpoint is in a good state, do not regenerate it.
    * Controller would be marked as failed when an endpoint is failing
* Metrics
    * At what point did we have to retry a regeneration based on a policy change (i.e., conflicting protocols on same port, too many prefix lengths)

**Comment by joestringer** [comment]
For discussion, what types of problems are likely to be resolved by trying again and again?

Failure to regenerate due to BPF compilation or complexity issues are unlikely to ever recover, this really says that developers haven't put good enough safeguards around the datapath code generation.

Perhaps L7 proxy configuration? Temporary outage or failure to configure a proxyport?

**Comment by joestringer** [comment]
Do you intend that there should be this "endpoint regeneration watcher" controller always running, or would it be started when a regeneration first fails and remove itself when it causes a good regeneration?

**Comment by ianvernon** [comment]
@joestringer I don't know of exact cases where this may remediate the issue - say we have an intermittent error connecting to the proxy, or some PolicyMap plumbing operation goes wrong (not sure entirely whether this is possible). I think at least trying again with some form of a backoff is better than sitting there without attempting to realize the desired state if the desired state was unable to be realized before.

What would be ideal, is if in the controller, we checked not just the state of the endpoint, but whether the realized state does not match the desired state. I think that to start, checking the state of the endpoint is a good starting point.

**Comment by ianvernon** [comment]
This is blocked by the state machine changes for the endpoint which @tgraf is working on.

**Comment by ianvernon** [comment]
Removing this from v1.4 since this wasn't completed in v1.4.

**Comment by ianvernon** [comment]
Fixed by https://github.com/cilium/cilium/pull/9203
