### ISSUE TITLE
Reserved identity does not have namespace label

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5529]
When following the etcd-operator, the fixed identity does not include the namespace or serviceaccount label so policy rules are not matching for fixed identity pods in namespaces or with particular service accounts attached.

**Comment by joestringer** [comment]
Related: #5527

**Comment by tgraf** [comment]
It's not as simple as to just add the namespace label as the same fixed identity may be used in multiple namespaces.

It may be better to just start treating kube-dns in kube-system as a special entity and reserve a numeric identity for it but keep the original labels.
