### ISSUE TITLE
Update policy docs on reserved entities

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#5537]
The current docs do not list all entities  (e.g., reserved:cluster, reserved:health)

We should also be clear about what is tagged as reserved:world vs. reserved:host, especially wrt NodePort traffic.   

it would also be nice to have the number values in the table.   These numeric values show up in cilium monitor, etc, but I did not see where they are documented, and without a running cilium instance I wasn't sure where to find them other than trying to find it in the source code.  

Current text as of filing is below: 

```
Entities Based
fromEntities is used to describe the entities that can access the selected endpoints. toEntities is used to describe the entities that can be accessed by the selected endpoints.

The following entities are defined:

host
The local host serving the endpoint. On ingress, this also includes the host of other Cilium cluster nodes.
world
All traffic outside of the cluster.
all
All traffic both within the cluster and outside of the cluster.
```

Here are the numeric entities from "cilium identity list": 

```
$ cilium identity list
ID      LABELS
2       reserved:world
4       reserved:health
3       reserved:cluster
5       reserved:init
1       reserved:host
```

**Comment by joestringer** [comment]
If anyone sees this and wonders what these entities are, the text was already updated:

http://docs.cilium.io/en/stable/policy/language/#entities-based
