### ISSUE TITLE
Feature: Dokku integration 

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#556]
For those not familiar with Dokku according to their website Dokku is 
>The smallest PaaS implementation you've ever seen

and from their Github description

>A docker-powered PaaS that helps you build and manage the lifecycle of
>applications http://dokku.viewdocs.io/dokku/

I use it because it provides a simple deployment option for web applications.
Shortly summarized you deal with Git and Docker no extra things unless you want.

I am using Dokku on 2nft.alemayhu.com and would like to use Cilium there. I also
have some other web apps where I would like to use Dokku + Cilium but
official support would be nice vs random hacks to get it to play nice together.

After thinking about it a good integration could look something like

0. User installs plugin `dokku plugin:install https://github.com/cilium/dokku-cilium.git cilium`
0. User creates a Cilium directory in their project with the policies to be
loaded.
0. User pushes to Dokku where if the Cilium directory is detected the plugin runs.
The plugin checks if user has the Cilium agent running on the machine.  If
the agent is missing it gets installed and / or started.
0. The plugin asks Cilium agent to perform validation and then loads the policy if
all is okay.

I don't know if the above suggestion will work with the Dokku plugins system,
but from eye balling the documentation below I don't see why it shouldn't be
feasible.

- [Plugins](http://dokku.viewdocs.io/dokku/community/plugins/)
- [Plugin Creation](http://dokku.viewdocs.io/dokku/development/plugin-creation/)

**Comment by tgraf** [comment]
Sounds great! Would love to see this.

**Comment by aalemayhu** [comment]
Maybe this can somehow be tied into the [Policy Repository](http://cilium.readthedocs.io/en/latest/architecture/?highlight=policy%20repository#policy-repository), the git tree part seems relevant
>Use of a git tree to maintain the policy in combination with a post-merge hook which automatically imports the policy. (TODO: Write & link to guide)
