### ISSUE TITLE
Cilium integration with Flannel

### ISSUE THREAD

**Issue by cristi-** [cilium/cilium#5566]
## Feature Requests

Hi,

I would like to ask if there's any way to run cilium with flannel as a CNI (similar to how cilium is running with kube-router). 

The use case for this would be using cilium in pre-existing clusters that already run with flannel. Upgrading a 100+ node cluster to cilium involves downtime, while adding it as a policy enforcer would be seamless.

I ran the following test:
- 2 node cluster with flannel
- deployed cilium having   tunnel: "disabled" 
- ran the deployment from https://cilium.readthedocs.io/en/latest/gettingstarted/minikube/ with 4 replicas  (no master taints so that pods can go on both nodes)
- added the l3_l4 policy
and the policy worked as expected.

Thank you!

**Comment by mrostecki** [comment]
@cristi- But what's the CNI config you are using? Policies probably work as expected, because just Cilium CNI is used and Flannel CNI is not.

**Comment by vadorovsky** [comment]
@aanm we can close this, right? :)

**Comment by aanm** [comment]
@cristi- This will be present in v1.4.0. The final PR is being performed here.
