### ISSUE TITLE
Document which Jenkins jobs are supported for which release versions of Cilium

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5607]
Also ensure that for these release branches that said jobs are *required* builds to avoid introducing regressions.

**Comment by aanm** [comment]
Shouldn't all of them be required? If a test is fixed upstream it should be backported.

**Comment by ianvernon** [comment]
There may be some cases where we add additional jobs / functionality to newer versions of Cilium, but said jobs are too invasive to backport to prior branches. That is the use case I am imagining here. For instance, the upstream K8s tests do not run for Cilium v1.0.

**Comment by ianvernon** [comment]
Closing, this is stale. Our Jenkins jobs run for all of our release branches now.
