### ISSUE TITLE
Provide alternative download URLs to releases

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#561]
The Github [releases page](https://github.com/cilium/cilium/releases) works fine if you want to download manually. Running curl on those files just returns HTML which has to be read to get the real download links. It would be convenient if only the files were returned to ease headless setup. Can the Cilium project host own downloads (`cilium.io/releases/`) ?

Thanks.

**Comment by tgraf** [comment]
Do these URLs like this work for you?

`https://github.com/cilium/cilium/releases/download/v0.8.2/cilium-agent-x86_64`

**Comment by aalemayhu** [comment]
No, but adding the redirect location option works. Did not know about it earlier.

**Comment by tgraf** [comment]
Btw, curl works great:
```
curl -sS -L "https://github.com/cilium/cilium/releases/download/#{cilium_version}/cilium-x86_64" -o /usr/local/bin/cilium
```

**Comment by aalemayhu** [comment]
Yes when you know to add `-L`. Found that out yesterday.

Thanks.
