### ISSUE TITLE
CI: Cannot contact jenkins-node-8: java.lang.InterruptedException

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#5610]
It seems jenkins is failing for k8s 1.12 for some reason, it happen 3 times for this PR https://github.com/cilium/cilium/pull/5449

One of the builds that failed https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/875/

**Comment by tgraf** [comment]
Believed to be fixed
