### ISSUE TITLE
Envoy build deletes proxylib/libcilium.so on CI

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#5654]
It seems like bazel call from `envoy-default` step in `envoy/Makefile` somehow deletes previously built `proxylib/libcilium.so` in CI (didn't have this behaviour while running ginkgo tests locally), which resulted in #5547 builds failing.

**Comment by eloycoto** [comment]
Maybe is related with this comment?
https://github.com/cilium/cilium/pull/5174#issuecomment-420698240

**Comment by jrajahalme** [comment]
This is likely due to a parallel step running "make clean" in the meanwhile you can just remove the rm from the clean target, on the longer run we should make sure parallel jenkins steps interfere like this.

**Comment by jrajahalme** [comment]
proxylib/Makefile in master already does not remove libcilium.so, so I don't know what deletes it.

**Comment by nebril** [comment]
Eloy was right, this is a parallel build issue, calling `clean` during our builds still needs to be fixed, but the issue is not in bazel build. The workaround was to completely clean `proxylib` `clean` makefile target.
