### ISSUE TITLE
timed out waiting for pods with filter -l k8s-app=microscope to be ready"

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5667]
See comment below for link and sysdump
vvv

**Comment by eloycoto** [comment]
That is not the file: 

Build link: 
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1651/testReport/junit/k8s-1/11/K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies/

File: 
[2af42f3f_K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies.zip](https://github.com/cilium/cilium/files/2409985/2af42f3f_K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies.zip)

Issue with microscope, redinessProbe failed: 

```
closing
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/bin/microscope/__main__.py", line 153, in <module>
  File "/bin/microscope/__main__.py", line 138, in main
  File "/bin/microscope/microscope/monitor/runner.py", line 98, in run
  File "/bin/microscope/microscope/monitor/runner.py", line 205, in retrieve_endpoint_data
  File "/bin/microscope/microscope/monitor/runner.py", line 205, in <listcomp>
KeyError: 'status'
```

@nebril this happened before no? The status key that it's not present no?

**Comment by nebril** [comment]
It's possible that API changed in a way that microscope was not ready for. Will investigate.

**Comment by nebril** [comment]
Seems like there are empty Cilium endpoints in our Endpoint CRD that contain only metadata:
```
 {
            "apiVersion": "cilium.io/v2",
            "kind": "CiliumEndpoint",
            "metadata": {
                "creationTimestamp": "2018-09-22T08:08:15Z",
                "generation": 1,
                "name": "testclient-2h8xl",
                "namespace": "default",
                "resourceVersion": "5781",
                "selfLink": "/apis/cilium.io/v2/namespaces/default/ciliumendpoints/testclient-2h8xl",
                "uid": "a80a17f4-be3e-11e8-a815-080027b66966"
            }
        },
```

I will add a check for "status" key in endpoint retrieval code.

**Comment by nebril** [comment]
Fixed in microscope 1.1.1, waiting for CI microscope version to be bumped

**Comment by ianvernon** [comment]
> Seems like there are empty Cilium endpoints in our Endpoint CRD that contain only metadata

This seems like a bug? That sounds to me like the CiliumEndpoint information is getting left behind? cc: @raybejjani

**Comment by raybejjani** [comment]
Endpoint CRD instances are supposed to be cleaned up on exit, but we don't have a mechanism in the agent for a graceful shutdown. I suspect any time the agent exits the CEPs are left behind. There is a GC controller that runs on all agents, however, so another agent should clean it up in a few minutes*.
In this case, though, I'm not sure how the empty CEP happens. That seems like a bug. The CEP controller calls `.GetModel` which returns something if the endpoint exists (which it would, since the controller was created and is running).

@nebril Did any CEP objects have a status field? Did you notice if the count of ones with status was the same as the number of actual endpoints?


* The code is a little strange. It's probabilistic right now but it can be made more deterministic by using the node list we keep.

**Comment by ianvernon** [comment]
Re-opening; this happened again:

Build link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1693/execution/node/99/log/?consoleFull

No logs unfortunately.

**Comment by nebril** [comment]
@raybejjani yeah, there were "normal" endpoints with "status" field in them, as well as some leftover metadata-only endpoints.

**Comment by raybejjani** [comment]
Hmm, the thing is these "leftovers" shouldn't be leftovers. The CEPs can't be empty. We never update a CEP (or create it) without some data in it (the json `cilium endpoint get` would show). We explicitly delete it on endpoint remove so the resource shouldn't even show up (and be empty). This is definitely a bug... but where? :/

**Comment by eloycoto** [comment]
Another fail: 
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/4343/execution/node/99/log/?consoleFull
