### ISSUE TITLE
Remove CIDR->Identity IPCache mapping from kvstore

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5686]
When a CIDR policy is imported, it goes through two phases with respect to the kvstore:

1. Convert the CIDR into a set of labels, and allocate an identity for this set of labels.
2. Map the CIDR to this identity

Given that (1) provides a reliable programmatic way to convert a CIDR into a specific identity, the identities will be consistent across nodes. This identity is based on the labels-generation code in a particular version of Cilium.

(2) was originally introduced to follow the standard IPCache paths for configuration when the IPCache was exclusively configured via the KVstore. It ensures that each node in the cluster will notify the IPCache in all other nodes of the mapping from the CIDR to Identity when the policy is imported, so for instance if one node imports the policy, all other nodes will receive notifications and begin to update their caches. This guarantees that the KVstore is the "source of truth" for the identity of the CIDR across the cluster.

(2) is not strictly necessary for consistent handling of CIDR identities. There are some disadvantages to this approach:
* Cost of additional kvstore operations.
* Inability to synchronously guarantee that the local node has successfully populated the ipcache corresponding to a policy that has been imported locally.
* Potential upgrade/downgrade inconsistencies (see below).

Regarding upgrade/downgrade, if two versions of Cilium exist in the cluster and the labels-generation code differs, then the step (1) will generate different identities (and policy maps will be populated based on these identities), then in step (2) the two versions of Cilium may "argue" about which identity corresponds to the CIDR. Some nodes may map the CIDR to an identity that hasn't had the corresponding policy computed yet; even if the policy is computed, the behaviour on the older Cilium may be inconsistent with the expectations of the policy on the newer Cilium.

I propose removing (2) in favour of plumbing the IPCache more directly within the same daemon. The infrastructure to support this didn't exist when label-based CIDR policy was initially introduced, but now it should be straightforward to fix up.

* [x] Stop pushing CIDR->Identity mappings into the KVstore
* [x] Push the CIDR->Identity mappings into the local IPCache
  * [x] Through to xDS
  * [x] Through to BPF
* [x] Figure out how to garbage-collect these mappings

**Comment by joestringer** [comment]
#6465 was merged, we should double-check the upgrade/downgrade considerations described in the description above.

**Comment by joestringer** [comment]
@tgraf I confirmed after upgrade from v1.2 with thousands of identities in kvstore to v1.4.0-rc5, after about half an hour there were no identities or IPs corresponding to CIDRs. Are there any other items you are concerned about on this issue?

**Comment by tgraf** [comment]
Sounds great. No further requests.
