### ISSUE TITLE
Install BPFtool in the dev VM

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5700]
Some time ago, we introduced `bpftool`  to supersede `bpf-map` in the containers, but it's not yet available in the dev VM. Add it there.

**Comment by vadorovsky** [comment]
Shall we use `bpftool` at the same version as the kernel which is in the dev VM image? Or `bpf-next`? Or some other version?

**Comment by joestringer** [comment]
@mrostecki Should probably pick up the latest, `bpf-next` would be good.

**Comment by joestringer** [comment]
I guess that until we upgrade our kernel, this might not be that useful (I tried it locally):

```
$ sudo bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_ipcache
Error: can't get map info: Invalid argument
```

**Comment by aanm** [comment]
@joestringer Don't forget that we have an developer VM with kernel net-next available as well :smile:

**Comment by joestringer** [comment]
Resolved in latest dev VM images.
