### ISSUE TITLE
unit tests fail in local dev vm

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5707]
Reproducing steps

1.  Checkout latest master

2. Launch the dev VM in K8s mode:

```
K8S=1 ./contrib/vagrant/start.sh
```

3. Run the unit tests:

```
make unit-tests
```

4. The daemon state test will fail:

```
...
level=info msg="C header file not found. Ignoring endpoint" endpointID=259 file-path= subsys=daemon
state_test.go:187:
    c.Assert(len(eps), Equals, len(epsWanted))
... obtained int = 0
... expected int = 4
...
```

**Comment by tgraf** [comment]
I'm hitting this as well. I wonder whether it is related to #5684 somehow

**Comment by ianvernon** [comment]
Duplicated by #5716 , which has been closed.
