### ISSUE TITLE
Add support for CNI traffic shaping

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#5718]
Introduced in k8s 1.12

https://github.com/kubernetes/kubernetes/pull/63194

I believe this can be easily done with a `tc` call for container's interface?

**Comment by mvisonneau** [comment]
is there some documentation available on how to implement the plugin chaining ? 🤔 

https://github.com/containernetworking/plugins/tree/master/plugins/meta/bandwidth

**Comment by borkmann** [comment]
Fixed in upstream Cilium and on track for 1.9. (https://docs.cilium.io/en/latest/gettingstarted/bandwidth-manager/ cc @mvisonneau)
