### ISSUE TITLE
1.2 docs already point to cilium/cilium:v1.2.4

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5722]
It's a side effect of the docs being built from the `v1.2` branch instead of the latest tagged release.

**Comment by joestringer** [comment]
That's why we set `stable` to point to the latest tagged release, it knows about rc tags and will only change when a real release occurs:

http://docs.cilium.io/en/stable/

**Comment by ianvernon** [comment]
Discussed during the community meeting. I will do the following:

* Revert k8s yaml version changes so docs point to existing stable image tag
* Update k8s yaml version just before the release of v1.2.4.

**Comment by tgraf** [comment]
Fixed via #5781
