### ISSUE TITLE
"exit when cilium-agent flags are not valid or available"

### ISSUE THREAD

**Issue by Lakers817** [cilium/cilium#5759]
### General Information

- Cilium version (run `cilium version`)
cilium 1.2.3
- Kernel version (run `uname -a`)
Linux ip-172- 4.13.0-041300-generic #201709031731 SMP Sun Sep 3 21:33:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

### How to reproduce the issue

1. instruction 1
I mention the wrong flag in sysconfig  systemd file file `etcd-config` correct flag is `etcd.config`

CILIUM_OPTS=--kvstore etcd --kvstore-opt=etcd-config=/home/ubuntu/my-etcd-config.yaml

This shoulld fail, and cilium agent should be exited . But it ran 
2. instruction 2
This is the correct flag in sysconfig systemd file:
after adding in sysconfig file CILIUM_OPTS=--kvstore etcd --kvstore-opt=etcd.config=/home/ubuntu/my-etcd-config.yaml

## Feature Requests
logs should call out flag is not correct and should suggest to use the correct flag like it should have
said `etcd-config`  is not a valid flag and have suggested etcd.config --- expected but found different
flag( in my case `etcd-config`).

**Comment by nebril** [comment]
In `v1.2.3`, I am getting following logs:

```
cilium-agent[11931]: level=error msg="unknown kvstore configuration key \"etcd-config\"" subsys=kvstore
cilium-agent[11931]: level=error msg="Supported configuration keys:" subsys=kvstore
cilium-agent[11931]: level=error msg="  etcd.address Addresses of etcd cluster" subsys=kvstore
cilium-agent[11931]: level=error msg="  etcd.config  Path to etcd configuration file" subsys=kvstore
cilium-agent[11931]: level=fatal msg="Unable to setup kvstore" address= error="invalid kvstore configuration, see log
```

After this output `cilium-agent` exits.

@Lakers817 I was unable to reproduce your issue, can you give some more details about how you ran `cilium-agent`?

**Comment by aanm** [comment]
>@Lakers817 I was unable to reproduce your issue, can you give some more details about how you ran cilium-agent?

@nebril bare-metal

**Comment by nebril** [comment]
Discussed offline, turned out to be a systemd config issue, closing.

**Comment by rverma-nsl** [comment]
@nebril faced same issue, can you suggest what was the fix.
`"unknown kvstore configuration key" key="{\"etcd.config\": \"/var/lib/etcd-config/etcd.config\"}" subsys=kvstore`
