### ISSUE TITLE
don't copy data to new slices in memcache parser

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#5770]

**Comment by christarazi** [comment]
@nebril Is this issue still relevant given that we've removed memcache tests (7a4ca6e1d4319aec4306f2c74bf00866c41bedf6)?

**Comment by squeed** [comment]
@nebril can we close this? Anything else to do?

**Comment by christarazi** [comment]
I vote to just close it. The tests have been clearly removed so I don't think we care to make an optimization about slices here.
