### ISSUE TITLE
CI: monitor was not ran for test "restart with long lived connections"

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5814]
The CI failure associated with #5813 had no monitor logs attached, which made it difficult to debug why the test failed. Use the monitor in these tests. Not sure if this is possible since we restart Cilium and thus kill the monitor :/

**Comment by eloycoto** [comment]
As we spoke in cilium developer meeting, the Tcpdump daemon set: 
https://github.com/cilium/cilium/pull/5843

**Comment by ianvernon** [comment]
We do not run microscope in the CI for K8s anymore because of the amount of load it put on the host; closing.
