### ISSUE TITLE
Documentation: add glossary

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#582]
The documentation very well tries to simplify things, but  since there is a lot
of domain specific words to networking, Linux and BPF it would be useful to
have a glossary which could be linked to throughout the manual and could
refresh memory. I think this will help new people.

For some examples see

- [OpenGL ES Programming Guide](https://developer.apple.com/library/content/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Glossary/Glossary.html)
- [Android](https://developer.android.com/guide/appendix/glossary.html)

**Comment by tgraf** [comment]
Do you want to start working on this @scanf and then others can join in and add stuff?

**Comment by aalemayhu** [comment]
Yes, can add a new page with some of the words.

**Comment by aalemayhu** [comment]
@tgraf This is how it looks like https://alemayhu.com/cilium/glossary.html
Not linking yet throughout the document, don't know how to link to specific sections in sphinx.
Let me know what to reword.
