### ISSUE TITLE
CI enhancement: gather loadinfo from VMs as well

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5852]
It could prove useful to run a small agent on each node in the CI that periodically logs the load within the VMs to some log:

```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/cilium/pkg/loadinfo"
	"github.com/cilium/cilium/pkg/logging"
)

func main() {
	sigs := make(chan os.Signal, 1)
	done := make(chan bool, 1)

	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	logOpts := make(map[string]string)
	// Logging should always be bootstrapped first. Do not add any code above this!
	logging.SetupLogging([]string{}, logOpts, "loadr", true)

	log := logging.DefaultLogger
	loadinfo.StartBackgroundLogger()

	go func() {
		sig := <-sigs
		log.Infof("received signal: %s", sig)
		done <- true
	}()

	select {
	case <-done:
		log.Infof("exiting due to signal")
	}
}
```

We can gather the logs of this agent as part of the CI. If there are extreme load scenarios which are causing the build to be quite slow, we can analyze the logs from this agent.

For the runtime tests, this can be deployed via systemd:

```
[Unit]
Description=load-info

[Service]
Type=simple
LimitCORE=infinity
ExecStart=/usr/bin/load-info
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

We will have to manually gather the logs by SSHing into the VM and running `journalctl -au load-info`.

For the K8s tests, we can deploy it as a DaemonSet. We will get all logs automatically via the K8s log-gathering functionality built into the K8s CI.

**Comment by aanm** [comment]
@ianvernon What about integration with prometheus?

**Comment by ianvernon** [comment]
@aanm this change is fairly low-hanging fruit, and could be added fairly quickly. I'm unsure how we'd get prometheus working in the runtime tests as well. I'd like to have Prometheus run in the CI for K8s regardless since it would allow for dogfooding our Prometheus metrics.

**Comment by aanm** [comment]
@ianvernon I think we are talking about 2 different things. I was proposing running a prometheus job inside the server where the VMs are running that would push the CPU and Memory usage statistics to an external prometheus push gateway. AFAIK we already have a graphana server running somewhere

**Comment by ianvernon** [comment]
@aanm I understood what you said, but what I am saying is that adding this small agent is pretty cheap in terms of amount of effort + immediate return. I'm not against adding Prometheus, I'm saying it would be more involved and a larger change. My proposal here could be addressed now, then we can add Prometheus integration later too.
