### ISSUE TITLE
CI enhancement: have external connectivity precheck on baremetal directly 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#5853]
Given that sometimes the CI fails due to issues connecting to external resources (i.e., outside of the baremetal nodes for Cilium CI) it'd be useful to have a basic ping / curl pre-check before provisioning the VMs, to avoid confusion in thinking there are failures related to Cilium's datapath when in actuality they are due to infrastructure problems.

**Comment by eloycoto** [comment]
I'm happy to add this one, but builds are now 1h 20 min, it's going to be a bit hard to make sure that after a hour the node still has internet address.

**Comment by ianvernon** [comment]
We could also have it as a precheck within the tests themselves that perform external access? I.e., ping from the VM itself vs containers / pods managed by Cilium.

**Comment by tgraf** [comment]
Agreed with @ianvernon but let's please curl instead of ping.
