### ISSUE TITLE
kubeadm guide: jsonpath does not retrieve all kube-dns pods

### ISSUE THREAD

**Issue by Svintooo** [cilium/cilium#5862]
This: https://github.com/kubernetes/website/pull/9889/files#diff-f4e313457c4b62245b4d7a92238a6d44R302

The problem is found under the **# Label kube-dns with fixed identity label** in the cilium instructions at https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

When I set up a cluster with kubeadm I get 2 pending kube-dns pods. But the following command only returns the name of one of them:
```
$ kubectl -n kube-system get pods -l k8s-app=kube-dns -o jsonpath='{range .items[]}{.metadata.name}{" "}{end}'
coredns-99b9bb8bd-7cfrm
```

Adding an asterisk (*) in the `[]` block seems to solve the problem:
```
$ kubectl -n kube-system get pods -l k8s-app=kube-dns -o jsonpath='{range .items[*]}{.metadata.name}{" "}{end}'
coredns-99b9bb8bd-7cfrm coredns-99b9bb8bd-vmzxm
```

**Comment by aanm** [comment]
We should also update the guide and point it to the last version of v1.2

**Comment by Svintooo** [comment]
Forgot to mention: Running kubernetes v1.11.3 and kubectl v1.12.1.
