### ISSUE TITLE
Endpoint in inconsistent state

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5929]
This PR build failed from #5713: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7294/

The PR moves `cilium-health` daemon to its own container inside the cilium pod, which should not result in any changes to pod connectivity on startup so filing this issue in case it's a generic issue on master.

Failure:
```
15:34:26 K8sChaosTest
15:34:26 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
15:34:26   Restart with long lived connections
15:34:26   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
15:34:26     TCP connection is not dropped when cilium restarts [It]
15:34:26     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
15:34:26 
15:34:26     Failed while cilium was restarting
15:34:26     Expected command: kubectl exec -n default netperf-client -- netperf -l 300 -t TCP_STREAM -H 10.10.0.126 
15:34:26     To succeed, but it failed:
15:34:26     Exitcode: 1 
15:34:26     Stdout:
15:34:26      	 MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.10.0.126 (10.10.0) port 0 AF_INET
15:34:26     	 recv_response_timed_n: no response received. errno 104 counter 0
15:34:26     	 command terminated with exit code 1
15:34:26     	 
15:34:26     Stderr:
15:34:26      	 
15:34:26     
15:34:26 
15:34:26     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Chaos.go:247
```

The cilium-9pmz4 agent log contains this message:
```
2018-10-16T15:30:25.162833723Z level=warning msg="Endpoint in inconsistent state" endpointID=40525 endpointState=waiting-to-regenerate subsys=daemon
```

Not sure whether the above message is indicative of why the test failed, or just an extraneous log message.

[f4d0b392_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip](https://github.com/cilium/cilium/files/2489782/f4d0b392_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip)

**Comment by tgraf** [comment]
I think this is caused by the new grace period on endpoint restore which delays the identity change and follow-up build after that. In the meantime, the endpoint can be built using the original identity.

**Comment by aanm** [comment]
[2b36d476_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip](https://github.com/cilium/cilium/files/2525175/2b36d476_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip)

happened twice for a single PR

**Comment by aanm** [comment]
[c2eb2abd_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip](https://github.com/cilium/cilium/files/2529505/c2eb2abd_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip)

happened again in https://github.com/cilium/cilium/pull/6088

**Comment by ianvernon** [comment]
This hasn't been hit in some time ; closing.
