### ISSUE TITLE
CI: No such file or directory while deploying etcd-operator

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#5932]
```
time="2018-10-18T09:50:39Z" level=debug msg="running command: /home/vagrant/go/src/github.com/cilium/cilium/test/../examples/kubernetes/addons/etcd-operator/tls/certs/gen-cert.sh 'cluster.local'"
cmd: "/home/vagrant/go/src/github.com/cilium/cilium/test/../examples/kubernetes/addons/etcd-operator/tls/certs/gen-cert.sh 'cluster.local'" exitCode: 0 duration: 1.133915503s stdout:
generating CA certs ===
generating etcd peer.json for cluster domain cluster.local ===
generating etcd peer certs ===
generating etcd server certs ===
generating etcd client certs ===
/home/vagrant

stderr:
2018/10/18 09:50:38 [INFO] generating a new CA key and certificate from CSR
2018/10/18 09:50:38 [INFO] generate received request
2018/10/18 09:50:38 [INFO] received CSR
2018/10/18 09:50:38 [INFO] generating key: rsa-2048
2018/10/18 09:50:39 [INFO] encoded CSR
2018/10/18 09:50:39 [INFO] signed certificate with serial number 284809818533175052216350004297467697272463967
2018/10/18 09:50:39 [INFO] generate received request
2018/10/18 09:50:39 [INFO] received CSR
2018/10/18 09:50:39 [INFO] generating key: rsa-2048
2018/10/18 09:50:39 [INFO] encoded CSR
{"code":1001,"message":"open ca-key.pem: no such file or directory"}
Failed to parse input: unexpected end of JSON input
2018/10/18 09:50:39 [INFO] generate received request
2018/10/18 09:50:39 [INFO] received CSR
2018/10/18 09:50:39 [INFO] generating key: rsa-2048
2018/10/18 09:50:39 [INFO] encoded CSR
{"code":1001,"message":"open ca-key.pem: no such file or directory"}
Failed to parse input: unexpected end of JSON input
2018/10/18 09:50:39 [INFO] generate received request
2018/10/18 09:50:39 [INFO] received CSR
2018/10/18 09:50:39 [INFO] generating key: rsa-2048
2018/10/18 09:50:40 [INFO] encoded CSR
{"code":1001,"message":"open ca-key.pem: no such file or directory"}
Failed to parse input: unexpected end of JSON input
mv: cannot stat 'etcd-client.pem': No such file or directory
mv: cannot stat 'etcd-client-key.pem': No such file or directory
mv: cannot stat 'server.pem': No such file or directory
mv: cannot stat 'server-key.pem': No such file or directory
mv: cannot stat 'peer.pem': No such file or directory
mv: cannot stat 'peer-key.pem': No such file or directory
rm: cannot remove 'ca-key.pem': No such file or directory
```

[fe9fef2b_K8sServicesTest_Checks_ClusterIP_Connectivity_Checks_service_on_same_node.zip](https://github.com/cilium/cilium/files/2491759/fe9fef2b_K8sServicesTest_Checks_ClusterIP_Connectivity_Checks_service_on_same_node.zip)

**Comment by raybejjani** [comment]
Two on master https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1788/

[54aaa263_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies (1).zip](https://github.com/cilium/cilium/files/2496050/54aaa263_K8sKafkaPolicyTest_Kafka_Policy_Tests_KafkaPolicies.1.zip)

https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1779/

[281e3632_K8sTunnelTest_VXLan_Check_VXLAN_mode.zip](https://github.com/cilium/cilium/files/2496075/281e3632_K8sTunnelTest_VXLan_Check_VXLAN_mode.zip)

**Comment by nebril** [comment]
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1796/ also failed because of that.
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1796/artifact/1175f160_K8sHealthTest_checks_cilium-health_status_between_nodes.zip

**Comment by joestringer** [comment]
Hit again:
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1801/

[d29678c6_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip](https://github.com/cilium/cilium/files/2511652/d29678c6_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip)

**Comment by eloycoto** [comment]
Fixed by https://github.com/cilium/cilium/pull/6049

**Comment by nebril** [comment]
Seems like hit again: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1823/

**Comment by ruigulala** [comment]
Hit again: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7795/
