### ISSUE TITLE
RFE: trim cilium pod size by compiling cilium bits into a single blob

### ISSUE THREAD

**Issue by AntonioMeireles** [cilium/cilium#5938]
Hi all, 

```
$ sudo crictl images | grep cilium
docker.io/cilium/cilium              v1.2.4              f7af61e2094e5       652MB
```

AFAICT a large part of the XXL size of the cilium pod (other than the clang/llvm bits) is the size of the cilium blobs. IMHO it would make sense to research shipping just one that would then behave according to the name it is being called (like hyperkube).  At sight, this should reduce the overall pod size a fair bit. 

All the Best, and keep the great work!

António

**Comment by vadorovsky** [comment]
It's done. @nebril, can you confirm and close?

**Comment by AntonioMeireles** [comment]
**THANKS**!
