### ISSUE TITLE
daemon: add default values for key-value store configuration objects 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#602]
Currently we have empty values for the following configuration flags in the daemon:
```
flags.StringVar(&consulAddr, "consul", "", "Consul agent address [127.0.0.1:8500]")
```

```
flags.StringSliceVar(&etcdAddr, "etcd", []string{}, "Etcd agent address [http://127.0.0.1:2379]")
```

```
flags.StringVar(&config.EtcdCfgPath, "etcd-config-path", "", "Absolute path to the etcd configuration file")
```

Change the values to defaults that are acceptable for the case when a user uses --kvstore=<kvstore type> but does not provide necessary configuration for the given kvstore type (e.g., consul address, etc agent address, etc.).

**Comment by tgraf** [comment]
Attempting to reach the default port of each kvstore flavour on the loopback should be the default value.

**Comment by tgraf** [comment]
Decided to always require kvstore configuration to make requirement for configuration obvious.
