### ISSUE TITLE
Question: go extension performance

### ISSUE THREAD

**Issue by mandarjog** [cilium/cilium#6027]
I did not find any measurements on the blog.
I would like to know what is the memory and CPU cost of using a go extensions.

What kind of performance benchmarking has been done for go extensions?

**Comment by raybejjani** [comment]
Thanks for opening an issue, mandarjog.
@jrajahalme, do you have any measurements we can share?

**Comment by jrajahalme** [comment]
@mandarjog @raybejjani Based on some quick testing a Cilium dev VM with netperf, picking the middle sample out of three test runs:

1. L3/4 enforcement policy *without* any proxy redirection
```
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ docker exec -i netperf-client netperf -C -H 10.11.41.46 -- -P 44444
MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 44444 AF_INET to 10.11.41.46 (10.11.4) port 44444 AF_INET
Recv   Send    Send                          Utilization       Service Demand
Socket Socket  Message  Elapsed              Send     Recv     Send    Recv
Size   Size    Size     Time     Throughput  local    remote   local   remote
bytes  bytes   bytes    secs.    10^6bits/s  % U      % S      us/KB   us/KB

 87380  16384  16384    10.00      16622.52   -1.00    23.07    -1.000  0.682  
```

2. L3/4 enforcement policy *with* L7 Go proxy redirection (Envoy + Cilium Go extension)
```
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ docker exec -i netperf-client netperf -C -H 10.11.41.46 -- -P 44444
MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 44444 AF_INET to 10.11.41.46 (10.11.4) port 44444 AF_INET
Recv   Send    Send                          Utilization       Service Demand
Socket Socket  Message  Elapsed              Send     Recv     Send    Recv
Size   Size    Size     Time     Throughput  local    remote   local   remote
bytes  bytes   bytes    secs.    10^6bits/s  % U      % S      us/KB   us/KB

 87380  16384  16384    10.00      15077.76   -1.00    24.02    -1.000  0.783  
```

Based on the above Envoy and Go parser (`proxylib/testparsers/passer.go`) *together* decrease the throughput by about 10% and increase the CPU utilization from 23% to 24% during the throughput test.

Note that Cilium currently does not support setting up Envoy TCP (i.e., non-HTTP TCP) redirects without calling into the Go library. However, I tried this out with a trivial change that results in the TCP connection data being proxied via Envoy but not passed to the Go extensions. With this running we get:

3. L3/4 enforcement policy *with* L7 Envoy proxy redirection (*without* Go extension):
```
vagrant@runtime1:~/go/src/github.com/cilium/cilium$ docker exec -i netperf-client netperf -C -H 10.11.41.46 -- -P 44444
MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 44444 AF_INET to 10.11.41.46 (10.11.4) port 44444 AF_INET
Recv   Send    Send                          Utilization       Service Demand
Socket Socket  Message  Elapsed              Send     Recv     Send    Recv
Size   Size    Size     Time     Throughput  local    remote   local   remote
bytes  bytes   bytes    secs.    10^6bits/s  % U      % S      us/KB   us/KB

 87380  16384  16384    10.01      16421.45   -1.00    24.76    -1.000  0.741  
```
So it seems that the 10% throughput cost mostly comes from the Go runtime, but the additional CPU utilization cost of the Go library is small.

I should note that this was just a basic TCP throughput test with the `test.passer` Go parser which does not actually parse the data at all, but all the data of the test is being run through the Go library and the parser framework logic. An actual parser will add cost proportional to the protocol complexity and implementation efficiency of the parser. For example, many of the existing parsers copy all data from the gatter/gather list to a single byte buffer to make it easier to parse, and this causes some additional overhead.

**Comment by jrajahalme** [comment]
Quick results from netperf TCP_RR test in the same environment (one netperf session between two containers in a 6-vCPU VM):

1. L3/4 enforcement policy without any proxy redirection

16200 - 25000 TCP requests/sec varying a bit between test runs.

2. L3/4 enforcement policy with L7 Go proxy redirection (Envoy + Cilium Go extension)

6100 - 6550 TCP requests/sec varying quite a little between test runs.

3. L3/4 enforcement policy with L7 Envoy proxy redirection (without Go extension):

6500 - 7300 TCP requests/sec depending on the test run

This test is the worst case for the proxy redirection overhead as the packets are small and no request pipelining is used. But even here the additional overhead of the Go extension on top of Envoy is relatively small considering the transition to/from Go runtime for each TCP request.

**Comment by mandarjog** [comment]
This is very helpful.
I am specifically interested in the difference between 2 and 3. From your setup it looks like that is at most 10%.
