### ISSUE TITLE
Unable to add route because has some invalid argument ??

### ISSUE THREAD

**Issue by wenma** [cilium/cilium#6033]
**General Information**

- Cilium version (run `cilium version`)
1.2.4
- Kernel version (run `uname -a`)
Linux l-mesos6.ops.cna 4.14.71-1.el7.centos.x86_64 #1 SMP Thu Sep 20 18:40:04 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
k8s:  1.12.1
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**

New install Cilium,  follow the guide of the offical website,   but the cilium agent logs show some errors:

```sh
level=error msg="Unable to add route" error="invalid argument" interface=cilium_host local="fc00::10ca:1" nexthop="fc00::10ca:1" prefix="{f00d::a5f:e4c0:0:0 ffffffffffffffffffffffffffff0000}" subsys=route
level=error msg="Unable to add route" error="invalid argument" interface=cilium_host local="fc00::10ca:1" nexthop="fc00::10ca:1" prefix="{f00d::a5f:e100:0:0 ffffffffffffffffffffffffffff0000}" subsys=route
level=error msg="Unable to add route" error="invalid argument" interface=cilium_host local="fc00::10ca:1" nexthop="fc00::10ca:1" prefix="{f00d::a5f:e540:0:0 ffffffffffffffffffffffffffff0000}" subsys=route
level=error msg="Unable to add route" error="invalid argument" interface=cilium_host local="fc00::10ca:1" nexthop="fc00::10ca:1" prefix="{f00d::a5f:e140:0:0 ffffffffffffffffffffffffffff0000}" subsys=route
level=error msg="Unable to add route" error="invalid argument" interface=cilium_host local="fc00::10ca:1" nexthop="fc00::10ca:1" prefix="{f00d::a5f:e180:0:0 ffffffffffffffffffffffffffff0000}" subsys=route
level=error msg="Unable to add route" error="invalid argument" interface=cilium_host local="fc00::10ca:1" nexthop="fc00::10ca:1" prefix="{f00d::a5f:e580:0:0 ffffffffffffffffffffffffffff0000}" subsys=route
level=error msg="Unable to add route" error="invalid argument" interface=cilium_host local="fc00::10ca:1" nexthop="fc00::10ca:1" prefix="{f00d::a5f:e440:0:0 ffffffffffffffffffffffffffff0000}" subsys=route
```
Something wrong ?

**Comment by aanm** [comment]
hello @wenma, can you provide the sysdump generated by `curl -sLO releases.cilium.io/tools/cluster-diagnosis.zip && python cluster-diagnosis.zip sysdump`?

**Comment by wenma** [comment]
@aanm  sure,  but the script doesn't work,  Perhaps because of  ```/dev/init``` I guess.
```
# cat cilium-279zx-20181024-195901-stats.txt
Couldn't resolve addr or pid 1 to TCPAddress: couldn't get port for PID 1: open /root/.config/gops/1: no such file or directory

# cat cilium-mrjq9-20181024-195911-memstats.txt
Couldn't resolve addr or pid 1 to TCPAddress: couldn't get port for PID 1: open /root/.config/gops/1: no such file or directory
```
except nodes, pods, services dump file,  but, due to safety concerns,  This information is not convenient to paste,  Sorry ~

**Comment by aanm** [comment]
>except nodes, pods, services dump file, but, due to safety concerns, This information is not convenient to paste, Sorry ~

@wenma do you prefer to send it to me privately over slack or e-mail?

**Comment by tgraf** [comment]
@wenma For debugging, it would be useful to have the addressing information of the node:
* `ip -6 a`
* `ip -6 r`
* `ip link list`

Do you have any specific IPv6 addressing configuration on these nodes?

**Comment by cokabug** [comment]
base the error log , issue the commad: 
`sudo ip -6 r add f00d::a5f:e5c0:0:0/112 via  fc00::10ca:1 dev cilium_host src fc00::10ca:1`
the system return:
`RTNETLINK answers: Invalid argument.`

but the system ipv6 route already have the route to  f00d::a5f:e5c0:0:0/112 is: 
`f00d::a5f:e5c0:0:0/112 via f00d::a5f:e300:0:1 dev cilium_host  src fc00::10ca:1  metric 1024`

ipv6 info:
```
ip -6 a s | grep -B1 fc00::10ca:1
27: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fc00::10ca:1/128 scope global
```

**Comment by wenma** [comment]
@aanm  @tgraf  Thank you for respond.  My problem has been solved.  I do these as follow:
1.I find the route item seems to wrong
```sh
> ip -6 r s
 ......
f00d::a5f:e300:0:0/112 via f00d::a5f:e300:0:1 dev cilium_host  src fc00::10ca:1  metric 1024 
f00d::a5f:e340:0:0/112 via f00d::a5f:e300:0:1 dev cilium_host  src fc00::10ca:1  metric 1024 
......
fc00::10ca:1 dev cilium_host  proto kernel  metric 256
f00d::a5f:e300:0:1 dev cilium_host  metric 1024          #   same as below, maybe
fc00::10ca:1 dev cilium_host  metric 1024 
fe80::/64 dev cilium_host  proto kernel  metric 256
......
```
2.so,  I uninstall the cilium by run the command ```kubectl delete -f cilium.yaml```,  then,  I login the k8s node host,  and I find the ```cilium_host``` interface status is still up
```sh
> ip a s cilium_host
15: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 86:a8:4f:0f:b6:df brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/32 scope link cilium_host
       valid_lft forever preferred_lft forever
    inet6 fc00::10ca:1/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::84a8:4fff:fe0f:b6df/64 scope link 
       valid_lft forever preferred_lft forever
```
 3. then,  I restart the ```cilium_host``` interface
```sh
> ip link set dev cilium_host down
> ip link set dev cilium_host up
```
4. In the end,  I re-install the cilium with ```kubectl apply -f cilium.yaml```,  and  check the agent log,  everything is OK.    check the route info again:
```sh
> ip -6 r s | grep 'dev cilium_host  metric'
f00d::a5f:e6c0:0:1 dev cilium_host  metric 1024      # just one
```

I think it should clean the route info when cleaning bpf state,  if config the clean flag.  Especially when re-
installing and upgrading.

**Comment by tgraf** [comment]
@wenma The reason the route is kept in place is that ensure that when you upgrade Cilium and thus delete the pod and start a new version, networking connectivity continues to flow. We'll look it into why it errored out in this case. It should re-use the existing route.
