### ISSUE TITLE
v1.3 CI: build failure 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6036]
Build link: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1129/

This occurred in a PR which changed no code, and thus means that v1.3 master is affected. I haven't triaged this, so this may be a duplicate issue. But, I want to make sure this is tracked.

**Comment by tgraf** [comment]
Build information is gone so no way to track this further. Likely covered by another issue if it persisted.
