### ISSUE TITLE
Add Cilium to the Kubernets documentation for Network Policy plugins

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#604]
Cilium should be listed here:  https://kubernetes.io/docs/tasks/configure-pod-container/declare-network-policy/

Likely our section should mimic other sections, giving a pointer to documentation for how to use Cilium with Kubernetes (e.g., our kubernetes getting started guide, as well as admin guide sections that cover kubernetes installation).    

We should also highlight differences in what Cilium can do with kubernetes beyond the standard Network Policies (e.g., HTTP-layer filtering).

**Comment by danwent** [comment]
https://github.com/kubernetes/kubernetes.github.io/pull/4725

I'm taking care of this.  Things are hung-up as the K8s mechanism for validating that we have signed the CLA seems broken.

**Comment by tgraf** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/cilium-network-policy/
