### ISSUE TITLE
1.4 Release

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6040]
* 1.4 Project https://github.com/cilium/cilium/projects/11

## Release Dates

No release dates were documented as part of this.

## Release Checklist
- [x] Planning
- [x] Development Phase
- [x] Feature Freeze
- [x] Feature Exception Freeze
- [x] Bugfix Freeze
- [x] Bugfix Exception Freeze
- [x] Branch off `v1.4`
- [x] Final Release
- [x] Upgrade & downgrade instructions
- [x] Tag Release
- [x] Release Blog
- [x] Announcement

**Comment by ianvernon** [comment]
1.4.0 has been released: https://github.com/cilium/cilium/releases/tag/v1.4.0 , closing this.
