### ISSUE TITLE
Documentation / examples: etcd-operator Cilium deployments can fall out of sync with latest released version

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6041]
@tgraf proposed "We should get rid of the additional DaemonSet in the addons".

I asked the following: 

"how can we avoid this happening again? should we include the etcd-operator YAMLs in the substitution of Cilium versions that we do in step 6 of the release process? https://cilium.readthedocs.io/en/v1.3/contributing/#release-management "

**Comment by aanm** [comment]
Duplicate of https://github.com/cilium/cilium/issues/5968
