### ISSUE TITLE
K8S=1 vagrant does not create RBAC rules for coredns

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6081]
```
E1029 00:19:38.902888       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:348: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:kube-system:coredns" cannot list resource "services" in API group "" at the cluster scope
```

Fix:
```
kubectl -n kube-system apply -f test/provision/manifest/1.12/coredns_deployment.yaml
```

**Comment by aanm** [comment]
It is part of the provision scripts. Do you have more detail?

**Comment by vadorovsky** [comment]
It's probably included in the test VM, but not in the dev VM. I see that coredns is added only in `test/provision/k8s_install.sh`.

**Comment by aanm** [comment]
https://github.com/cilium/cilium/blob/46292fcee05a41691d2a7b80c2c6ea6be2c24644/contrib/vagrant/start.sh#L270

https://github.com/cilium/cilium/blob/d83bc8d7c9e545f642a043a33dadad373dde43e0/examples/kubernetes-ingress/scripts/06-install-coredns.sh#L39-L38
