### ISSUE TITLE
Reduce to single binary with aliases

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6100]
- [x] Use a single binary and use symlinks to detect whether [`cilium`, `cilium-agent`, `cilium-bugtool`, `cilium-node-monitor`] is used
- [x] Modify the Dockerfile to ship the new single binary while maintaining backward compatibility
- [x] Adjust the release scripts

**Comment by ianvernon** [comment]
https://github.com/cilium/cilium/pull/6125 did the first step .

**Comment by tgraf** [comment]
@ianvernon completed the release script modification in #7168
