### ISSUE TITLE
Reduce go dependency within project

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6101]
- [x] Identify the top 20 reasons for dependency explosion and break the dependency tree to allow inclusion of packages without pulling in the entire codebase.

**Comment by ianvernon** [comment]
Biggest dependencies that blow up the dependency graph for us are:

- pkg/kvstore
- pkg/k8s
- sp13/viper
- pkg/metrics

Dependencies that should be abstracted out of packages if possible

- anything BPF-related. We should abstract out the datapath if possible from consumers of it (e.g., pkg/policy, pkg/endpoint, etc.).

Also as part of this we should consider splitting up the daemon code into easier-to-read files.

**Comment by ianvernon** [comment]
We can definitely gain a lot from doing dependency injection from the daemon. This can reduce dependencies across a lot of packages.

**Comment by ianvernon** [comment]
Other potential follow-ups:

- [ ] removing dependency on `pkg/policy/api` from `pkg/monitor`. This could be trivial as only one function consumes lists of rules currently
- [ ] removing dependency on `pkg/metrics` from `pkg/controller` - factoring out metrics into an interface would be nice, but this may be difficult given how Prometheus dependency works.
- [ ] factor out kvstore backend interface into separate package maybe? - would remove kvstore dependency from `pkg/clustermesh`, although that is tightly coupled with etcd.
- [ ] remove dependency on `pkg/bpf` from endpoint. This will be quite difficult. This would allow us to abstract out datapath implementation from the endpoint (not sure how feasible this is).
- [ ] factor out dependency on `pkg/identity/cache` from endpoint. This could be done via dependency injection as well.
- [ ] inject monitor dependency into endpoint
- [ ] inject monitor dependency into endpointmanager
- [ ] consider removing syslog, fluentd dependencies out of our logging package. this code is almost 2 years old at this point, not sure how often it is being used.

This is a good enough starting point for future work. 

EDIT: will put this in a separate follow-up issue and close this one.

**Comment by ianvernon** [comment]
Created 
https://github.com/cilium/cilium/issues/6195 for follow-up.
