### ISSUE TITLE
Update external documentation with Cilium installation steps

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#6116]
update cilium with v1.6.0
(@aanm did it for v1.4.0)
(@brb did it for v1.5.0)

- [ ] https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy/
- [ ] https://kubernetes.io/docs/concepts/cluster-administration/networking/
- [ ] https://kubernetes.io/docs/concepts/cluster-administration/addons/
- [x] https://github.com/kubermatic/kubeone/issues/462

**Comment by brb** [comment]
Updated.

**Comment by brb** [comment]
Removed the `needs-backport/1.5` label, as all changes were external.

**Comment by joestringer** [comment]
These days we track these from the release issues right? This issue falls far enough down my queue that I don't end up looking at it.
