### ISSUE TITLE
Re-enable microscope after fixing CPU utilization issue

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6121]
#6110 has disabled microscope in the CI due to excessive CPU usage. Re-enable microscope after fixing:
- [ ] CPU utilization issue
- [ ] Pod termination issue (not handling SIGTERM due to use of alpine spawn sleep)
- [ ] Readiness check consuming a lot of CPU and having a long delay when ran in a pod

**Comment by joestringer** [comment]
Superseded by #11127.
