### ISSUE TITLE
Connection reset during agent restart

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6122]
Failed test instances:
 * https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1836/testReport/k8s-1/8/K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts/

```
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
Failed while cilium was restarting
Expected command: kubectl exec -n default netperf-client -- netperf -l 300 -t TCP_STREAM -H 10.10.1.90 
To succeed, but it failed:
Exitcode: 1 
Stdout:
 	 MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.10.1.90 (10.10.1) port 0 AF_INET
	 recv_response_timed_n: no response received. errno 104 counter 0
	 command terminated with exit code 1
	 
Stderr:
```
[26dc90c0_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip](https://github.com/cilium/cilium/files/2532161/26dc90c0_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip)

**Comment by tgraf** [comment]
Another hit:
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1833/

**Comment by jrajahalme** [comment]
Hit here as well: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7766/execution/node/93/log/?consoleFull

**Comment by joestringer** [comment]
Seen again on master:
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1929/execution/node/89/log/?consoleFull

**Comment by ianvernon** [comment]
Seen again on master: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1976/testReport/junit/k8s-1/8/K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts/

**Comment by ianvernon** [comment]
Seen again on master: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/4951/testReport/junit/k8s-1/8/K8sChaosTest_Restart_with_long_lived_connections_L3_L4_policies_still_work_while_Cilium_is_restarted/

**Comment by aanm** [comment]
Seen again on: https://github.com/cilium/cilium/pull/6540

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/1451/testReport/junit/k8s-1/9/K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts/

[4b7d6b75_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip](https://github.com/cilium/cilium/files/2729421/4b7d6b75_K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts.zip)

**Comment by brb** [comment]
Seen again on master: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5437/testReport/junit/k8s-1/8/K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts/

**Comment by brb** [comment]
Again: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2105/testReport/junit/k8s-1/8/K8sChaosTest_Restart_with_long_lived_connections_TCP_connection_is_not_dropped_when_cilium_restarts/

**Comment by brb** [comment]
Again: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5507/testReport/junit/k8s-1/8/K8sChaosTest_Restart_with_long_lived_connections_L3_L4_policies_still_work_while_Cilium_is_restarted/

**Comment by tgraf** [comment]
Dup of #6730
