### ISSUE TITLE
proxylib: Make test/accesslog_server's Close wait longer if expected messages have not been received yet.

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#6135]
When testing the access logging functionality we can't keep waiting forever if messages are not received as expected, but we should wait longer than the current 10ms as we've seen test failures due to the accesslog server lagging behind, likely due to resource constraints in the CI.

**Comment by jrajahalme** [comment]
Ci fail due to this: https://travis-ci.org/cilium/cilium/builds/449078231?utm_source=github_status&utm_medium=notification

**Comment by aanm** [comment]
@jrajahalme I've seen a failure in the CI (https://api.travis-ci.org/v3/job/448906786/log.txt) with: 
```
--- FAIL: TestOnDataNoPolicy (0.01s)
    proxylib_test.go:160: Inject buffer too small, data truncated
    proxylib_test.go:175: OnData: Unexpected access log entries, expected 0 passes (got 0) and 2 drops (got 0).
```

Is it related?

**Comment by aanm** [comment]
https://api.travis-ci.org/v3/job/449882812/log.txt
```
generic_l7:<proto:\"test.headerparser\" fields:<key:\"status\" value:\"PASS\" > > "
time="2018-11-02T15:14:12Z" level=info msg="Closing access log connection"
time="2018-11-02T15:14:12Z" level=info msg="CloseInstance(44): Remaining open count: 0"
--- FAIL: TestAllowAllPolicy (0.10s)
    proxylib_test.go:583: OnData: Unexpected access log entries, expected 4 passes (got 1) and 0 drops (got 0).
```

**Comment by ianvernon** [comment]
Similar failure here: ```time="2018-11-06T20:45:54Z" level=info msg="CloseInstance(44): Remaining open count: 0"
--- FAIL: TestAllowAllPolicy (0.10s)
    proxylib_test.go:583: OnData: Unexpected access log entries, expected 4 passes (got 2) and 0 drops (got 0).
=== RUN   TestAllowEmptyPolicy```

**Comment by ianvernon** [comment]
Occurred again: https://travis-ci.org/cilium/cilium/builds/461897887?utm_medium=notification&utm_source=email
