### ISSUE TITLE
Adding clarification in Contributor Guide regarding running unit test

### ISSUE THREAD

**Issue by ruigulala** [cilium/cilium#6139]
## Proposal / RFE

**Is your feature request related to a problem?**
When following the unit test part of the Contributor Guide, if people follow the command directly, they'll run into the following error. This is due to the kv-store test server hasn't been set up before running the test.
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium/pkg/kvstore$ go test
level=info msg="Waiting for consul to elect a leader" subsys=kvstore
level=info msg="Waiting for consul to elect a leader" subsys=kvstore
level=fatal msg="Unable to contact consul server" error="Get http://127.0.0.1:8501/v1/status/leader: dial tcp 127.0.0.1:8501: connect: connection refused" subsys=kvstore
exit status 1
FAIL	github.com/cilium/cilium/pkg/kvstore	1.442s
```

**Describe the solution you'd like**
Some extra clarifications may be needed. For example, the following command can be suggested as a complement. Because the makefile target also handles removing the kv-store server container.
```
make unit-tests TESTPKGS=github.com/cilium/cilium/pkg/kvstore
```

**Comment by aanm** [comment]
LGTM
