### ISSUE TITLE
CI: K8sHealthTest checks cilium-health

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#6157]
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
cannot retrieve filter "{.nodes[1].endpoint.icmp.status}" from health output
Expected
    <*errors.errorString | 0xc4203784f0>: {
        s: "array index out of bounds: index 1, length 1",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Health.go:101
```

[33226627_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/2543309/33226627_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by eloycoto** [comment]
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6226/testReport/junit/k8s-1/13/K8sHealthTest_checks_cilium_health_status_between_nodes/
