### ISSUE TITLE
DockerHub unable to build Cilium from Dockerfile

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#6163]
```
Could not find or parse Dockerfile: First line in Dockerfile isn't FROM
```

**Comment by jrajahalme** [comment]
Would be helpful if you'd tell where this error message is from. Docker seems to be happy with the Dockerfile.

Either way, the ARG that was used in the Dockerfile is not really needed anymore, so I'll remove it.

**Comment by jrajahalme** [comment]
@aanm Just saw from the title it is from DockerHub...
