### ISSUE TITLE
CI/Proposal: Use travis for unit testing instead of Jenkins

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6165]
Given that we have re-enabled Travis to runt he unit test framework to retrieve unit test coverage in each PR. Does it make sense to disable the unit test framework in Jenkins to save the 4 minutes in the pipeline. This is in particular useful as the unit tests are not ran in parallel to anything else.

cc @eloycoto @ianvernon @aanm

**Comment by ianvernon** [comment]
Makes sense to me. The only potential downside now is that if the unit tests fail, the CI may run for the entire duration of the tests, which is around 40 minutes. But, given that unit tests don't fail often, the reduction of 4 minutes across all test runs would end up with us saving a net amount of time per build.

**Comment by aanm** [comment]
It was suggested by @eloycoto 
https://github.com/cilium/cilium/pull/6094#pullrequestreview-170026969

The only downside is the cost of saving 4 minutes the expense of running 80 minutes of CI. (40 minutes of 1st build, realizing unit tests are failed + 40 minutes of 2nd build)

**Comment by tgraf** [comment]
Travis runs automatically. A PR author can wait for Travis to complete before kicking off Jenkins.

**Comment by joestringer** [comment]
I am proposing to walk back this change for the privileged unit tests in the following PR: 

https://github.com/cilium/cilium/pull/6117
