### ISSUE TITLE
Deadlock cause by "hidden" panics in metrics

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#6183]
Unfortunately is not possible to retrieve the exact cilium commit has this was tested of a branch.

```
goroutine 175044 [semacquire, 484 minutes]:
sync.runtime_SemacquireMutex(0xc42020b208, 0xfda300)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42020b204)
	/usr/local/go/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0xc42020b204)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).UnconditionalLock(0xc42020b200)
	/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:55 +0x31
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF.func2(0xc42556daf8, 0xc42020b200, 0xc42556d920, 0xc42556d908)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:569 +0x234
panic(0x26c8cc0, 0xc425fe6ed0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc4202da540, 0xbef4a2cf4d5aa6c0)
	/go/src/github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus/counter.go:63 +0xb2
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc42020b200, 0x2c0a8a0, 0xc4222f7400, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:582 +0x609
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc42020b200, 0x2c0a8a0, 0xc4222f7400, 0xc4214b7600, 0x1b, 0xc4239f9760, 0xa, 0xc425df16c0, 0x0, 0xf87200, ...)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:591 +0x19c2
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc42020b200, 0x2c0a8a0, 0xc4222f7400, 0xc425df16c0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:763 +0x7a6
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc425df16c0, 0x2c0a8a0, 0xc4222f7400, 0xc421881780, 0xc42020b200)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:842 +0x1fc
created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:820 +0x123
```

The panic above was inside the "Add" of this line: https://github.com/cilium/cilium/blob/ccd371c9acc761f0d37c045ff344f71341c91dcc/pkg/endpoint/policy.go#L584

Which was called inside this function
https://github.com/cilium/cilium/blob/ccd371c9acc761f0d37c045ff344f71341c91dcc/pkg/endpoint/policy.go#L483-L484

As we can see, the function can only be called with the endpoint mutex held, as the function panicked, the mutex was still held. Although we have a "defer" function, that defer function also wanted to Lock the endpoint. Unfortunately, the endpoint mutex was not Unlocked because of the panic, the defer is never executed and the mutex is never unlocked.

>When the function F calls panic, execution of F stops, any deferred functions in F are executed normally, and then F returns to its caller.

**Comment by ianvernon** [comment]
I think @jrajahalme's PR 
https://github.com/cilium/cilium/pull/5616 is meant to solve the problem of acquiring endpoint locks in `defer` statements within `regenerateBPF`.

**Comment by joestringer** [comment]
Invalid `regenerateTimeSec` ?

> regenerateTimeSec := float64(time.Since(regenerateStart)) / float64(time.Second)
> ...
> metrics.PolicyRegenerationTime.Add(regenerateTimeSec)

https://godoc.org/github.com/prometheus/client_golang/prometheus#Counter

>     // Add adds the given value to the counter. It panics if the value is <
>     // 0.

**Comment by jrajahalme** [comment]
Unfortunately #5616 seems impossible to rebase without basically re-doing it from scratch. I closed it for now.

**Comment by ianvernon** [comment]
https://github.com/cilium/cilium/issues/6209 appears related.

**Comment by aanm** [comment]
```
goroutine 49164 [semacquire, 608 minutes]:
sync.runtime_SemacquireMutex(0xc0003ae6c8, 0xc005074000)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0003ae6c4)
	/usr/local/go/src/sync/mutex.go:134 +0xff
sync.(*RWMutex).Lock(0xc0003ae6c4)
	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).UnconditionalLock(0xc0003ae6c0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:55 +0x31
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF.func2(0xc006257b00, 0xc0003ae6c0, 0xc006257928, 0xc006257910)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:571 +0x232
panic(0x27b3480, 0xc005074100)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc0000e4300, 0xbee83c9dfc3b0aa9)
	/go/src/github.com/cilium/cilium/vendor/github.com/prometheus/client_golang/prometheus/counter.go:63 +0xa3
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc0003ae6c0, 0x2d97640, 0xc001984f20, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:584 +0x5e3
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc0003ae6c0, 0x2d97640, 0xc001984f20, 0xc001eac000, 0x1a, 0xc0034da040, 0x9, 0xc004dba000, 0x0, 0xc00195eb00, ...)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:593 +0x1a6f
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc0003ae6c0, 0x2d97640, 0xc001984f20, 0xc004dba000, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:765 +0x782
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc004dba000, 0x2d97640, 0xc001984f20, 0xc0017e03c0, 0xc0003ae6c0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:851 +0x1fe
created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:822 +0x116
```

as we can see in the stack trace the value is really negative at the point the Add is called. `bee83c9dfc3b0aa9` or `-0.00001155699999999999963266623242974517893344454933` seconds to be precise

Although, before the "Add" is being executed there's `Info` message being printed, which shows `policyRegenerationTime="105.661µs"`, that should be roughly the same number being set to the Add function.

```
2018-11-09T00:10:41.562384318Z level=info msg="Completed endpoint policy recalculation" containerID=6a8426379e datapathPolicyRevision=1652 desiredPolicyRevision=1657 endpointID=4077 forcedRegeneration=false ipv4=10.2.3.81 ipv6="f00d::a02:300:0:fed" k8sPodName=xxxxxx policyChanged=false policyRegenerationTime="105.661µs" subsys=endpoint
```

**Comment by ianvernon** [comment]
@aanm what's even weirder about the stack trace is that the time variables which are causing the panic are local to `regeneratePolicy`, and are not modified asynchronously / in any goroutines, so how can they be negative? This is bizarre. Is the floating point conversion we are doing incorrect / causing some type of underflow / inaccuracy?

```
regenerateTimeSec := float64(time.Since(regenerateStart)) / float64(time.Second)
...
metrics.PolicyRegenerationTime.Add(regenerateTimeSec)
```

That's the only explanation I can think of that would cause the value to be negative.

**Comment by tgraf** [comment]
@ianvernon Yes, floats are not 100% accurate. The division can obviously result in a very small number. What is new to me is that a very small number can become negative.

**Comment by ianvernon** [comment]
@tgraf that's why I'm wondering if there's some type of problem with division that is causing some type of underflow problem :/ I see no other possible explanation . The log that @aanm pasted above  shows the time is logged before any floating point calculations are performed. 

Looking at the following:

```
regenerateTimeSec := float64(time.Since(regenerateStart)) / float64(time.Second)
```

`time.Since(Time)` returns a duration as a Duration (`int64`), which we then divide by `float64(time.Second)`. Dividing `int64` by `float64` seems fishy to me.
