### ISSUE TITLE
consider removing use of init functions for packages that are imported by daemon

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6197]
Because we now have a single binary for the CLI, bugtool, and cilium-agent, anything which is imported into the `daemon` package now runs all init functions which are used by the daemon package, e.g.:

```
$ cilium debuginfo
level=info msg="Detected MTU 1500" subsys=mtu
...
```

This may affect the ability of the debugging tooling to run efficiently depending on what packages are being ran with init functions.

**Comment by joestringer** [comment]
Even from `cilium-agent`, this occurs when generating cmdref (which it really shouldn't need to).
