### ISSUE TITLE
Policy support to protect the host

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6203]
The request is coming up more and more frequently to support specifying policy rules to protect the host itself. This issue is tracking this feature addition.

Asks that have come up:
- Ability to install policy rules to only allow traffic to local endpoints plus an additional
- Ability to whitelist and blacklist traffic to a particular host port while delegating policy for local containers to the policy of that container/pod

Feel free to add additional asks/requirements.

**Comment by andrewhowdencom** [comment]
Practically this is interesting in the case of services that run on HostPort. It's an easy layer to miss stuff bound to the public interface; particularly from within that host.

Practical examples would be like:

- 169.254.169.254
- Prometheus node exporter
- Any other weird daemonsets

**Comment by pchaigno** [comment]
This feature is available since Cilium 1.8 through the host firewall.
