### ISSUE TITLE
FQDN related identity disappeared

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6221]
The testing cluster got into a state where an IP cache entry pointed to an identity that no longer existed. Based on the IP in the ipcache entry, it is reasonable to assume that the ipcache entry was created as a result of an FQDN policy rule. Several FQDN rules are loaded.

- The kvstore did not know about the identity referred to in the ipcache entry
- Removing the ipcache manually from kvstore resulted for it to be re-created instantly which indicates that at least one agent was still holding a reference count to the ipcache entry.
- Restarting all agents resolved the situation. The ipcache entries first disappeared and where then re-created together with a new identity. Likely when the DNS poller queried the name again.

**Comment by raybejjani** [comment]
I think https://github.com/cilium/cilium/pull/6250 fixed this, so I'll close this optimistically.
