### ISSUE TITLE
Wrap time.Since to avoid negative durations in metrics 

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#6222]
We've encountered odd time shifts when using time.Since that caused the duration to be negative (e.g. https://github.com/cilium/cilium/pull/6214). This seems to be related to the clock moving backwards :/
To save our sanity, and avoid metrics panicing on <0 counter increments, it would be good to:
- wrap `time.Since` usage (and perhaps `time.Time.Since as well) with a wrapper that always return >=0 and logs negative durations
- Replace all places we use `.Since` for timing (where a negative duration is bad)
- Add some sort of compile time check (this may not be really easy, without breaking normal usage of `time.Time.Since`)

**Comment by brb** [comment]
After checking all `time.{Since,After}` and `timeSince` occurrences, IMO it doesn't make sense to introduce the wrapper at this moment, as there is only one place in the code which is sensitive to a negative duration and it has been already fixed in #6214.
