### ISSUE TITLE
Cilium: BPF API to getNextKey does not correctly handle array maps

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#6228]
Issue is syscall GetNextKey for Arrays with key = 0 does will return the next key, namely whatever is in slot 1. However on Hashmap will return the key in slot 0. The Cilium API expects the hash map behavior and calling the get next key bpf apis from Cilium side will not work as expected on Arrays. [TBD confirm the above and fix Cilium side]

Reproduce:
1. Create BPF Array Map of size 1
2. Call a Cilium API call that uses get next key API (using the Dump map is probably the easiest to realize this)
3. Notice that not all entries or "Dump"ed. With size of 1 nothing is dumped.

**Comment by joestringer** [comment]
Might be worth looking at bpftool too, just check it doesn't have the same issue

**Comment by Zebaz** [comment]
I've identified the same issue as well in the Dump function in map.go where a key with value "0" is not printed when iterating over all the entries in a map.
This has to do with the fact that said Dump function uses the bpf_map_get_next syscall to find the next key in the map, but initially using "0" as the first key in the loop.
bpf_map_get_next then returns the subsequent key following "0" and skips over this specific key.

This issue pops up in particular when using array map types, as the key 0x00 0x00 0x00 0x00 is always initialized here.
To illustrate this issue I create an array map using bpftool, containing 2 entries:

```
# bpftool map create /sys/fs/bpf/test_array type array key 4 value 1 entries 2 name test

# bpf-map info /sys/fs/bpf/test_array
Type:           Array
Key size:       4
Value size:     1
Max entries:    2
Flags:          0x0
Owner prog type:        Unknown
```

When dumping this array using bpf-map, only one key is printed:
```
# bpf-map dump /sys/fs/bpf/test_array
Key:
00000000  01 00 00 00                                       |....|
Value:
00000000  00                                                |.|
```

A patch has been accepted into the kernel several years ago where passing NULL as the key would returns the first key:

[](https://patchwork.ozlabs.org/project/netdev/patch/20170425020037.1114047-1-ast@fb.com/)
> "When iterating through a map, we need to find a key that does not exist
> in the map so map_get_next_key will give us the first key of the map.
> This often requires a lot of guessing in production systems.
> 
> This patch makes map_get_next_key return the first key when the key
> pointer in the parameter is NULL."

Notice how bpftool uses this approach to find the first key in a map:

```
# bpftool map getnext id 9
key: None
next key:
00 00 00 00
```
From [](https://github.com/torvalds/linux/blob/master/tools/bpf/bpftool/map.c):
```
prev_key = NULL;
...
while (true) {
    err = bpf_map_get_next_key(fd, prev_key, key);
    if (err) {
        if (errno == ENOENT)
            err = 0;
        break;
    }
    num_elems += dump_map_elem(fd, key, value, info, btf, wtr);
    prev_key = key;
}
....
```

A possible solution to this for the Dump function in Map.go would be to pass a NULL/nil pointer in the first iteration.

**Comment by joestringer** [comment]
Closing stale.
