### ISSUE TITLE
cilium-agent connects to local storage with --consul flag provided

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#623]
If the cilium-agent is called with `--consul "127.0.0.1:8500"`, the agent connects to the local storage.

It would be helpful to provide a mechanism that allow us to use the `--consul` and `--etcd` flags without writing `--kvstore <kvstore>` otherwise the upgrade from `0.8.x` won't be smooth.

**Comment by tgraf** [comment]
I think we should error out if `--consul` is provided and `--kvstore` is not equal to  "consul".

**Comment by ianvernon** [comment]
I agree with @tgraf.

**Comment by ianvernon** [comment]
On top of that, could we error out if a kvstore flag isn't provided? It would ensure that the user explicitly has to specify it.
