### ISSUE TITLE
Check if pods contain security identities before running test

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#6243]
I recently got this flake:
```
time="2018-11-14T10:41:41Z" level=debug msg="running command: kubectl exec -n kube-system cilium-m5xs7 -- cilium policy trace --src-k8s-pod default:app2-85b74b9c79-gvfjc --dst-k8s-pod default:app1-9d8945dc9-4lxnh --dport 80"
cmd: "kubectl exec -n kube-system cilium-m5xs7 -- cilium policy trace --src-k8s-pod default:app2-85b74b9c79-gvfjc --dst-k8s-pod default:app1-9d8945dc9-4lxnh --dport 80" exitCode: 1 duration: 288.554522ms stdout:

stderr:
level=info msg="Detected MTU 1500" subsys=mtu
level=info msg="Waiting for k8s api-server to be ready..." subsys=k8s
level=info msg="Connected to k8s api-server" ipAddr="https://10.96.0.1:443" subsys=k8s
level=info msg="Waiting for k8s api-server to be ready..." subsys=k8s
level=info msg="Connected to k8s api-server" ipAddr="https://10.96.0.1:443" subsys=k8s
Error: Cannot get security id from k8s pod name: cilium-identity annotation not set for pod app1-9d8945dc9-4lxnh in namespace default
command terminated with exit code 1
```

The annotation was set but it was not set with the command was executed. The output of controller status shows it was successfully 5s ago.
```
Controller Status:   58/58 healthy
  Name                                               Last success   Last error   Count   Message
  sync-identity-to-k8s-pod (24821)                   5s ago         never        0       no error   
```

https://github.com/cilium/cilium/blob/f4cc278c5cc9de3ee62c7633f0470c36f7abbc6d/test/k8sT/Policies.go#L199-L205

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/8048/testReport/junit/k8s-1/12/K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies/

[6c7aa6c4_K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies.zip](https://github.com/cilium/cilium/files/2582194/6c7aa6c4_K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies.zip)

**Comment by ianvernon** [comment]
Happened again: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/4941/testReport/junit/k8s-1/12/K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies/

**Comment by ianvernon** [comment]
Happened again: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/4964/testReport/junit/k8s-1/12/K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies/

**Comment by ianvernon** [comment]
Again: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/4972/

**Comment by brb** [comment]
Happened again: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5448/testReport/junit/k8s-1/8/K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies/

**Comment by joestringer** [comment]
Not seen in a long time.
