### ISSUE TITLE
Could not reach service1-instance1/private on port 80 or `docker run --rm` exits with error

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#629]
`docker run --rm -i --net cilium-net -l id.service2 cilium/demo-client curl -si http://service1-instance1/public`

A `docker run` command can be split in 3 separate events: `docker create`, `docker start` and `docker exec`.

For `docker create` it calls:
- docker cilium libnetwork plugin, which calls:
  - the cilium-agent via `PUT /endpoint/{id} request` which generates
    - (1) bpf program build
  - send response back to docker cilium libnetwork plugin
- docker concludes the `create` step

For `docker start` it creates a docker event:
- cilium-agent receives the event via docker listener
  - builds a (2) bpf program
    - replace the program from (1) with this new bpf program.

For `docker exec`, docker runs the specified command:
- `curl -si http://service1-instance1/public`
  - some ARP requests are sent, never receive the responses
 - docker exec errors out with code != 0

Why does `docker exec` error out if the bpf program is already in place?
Although bpf program (1) is build and attached to the interface by the time the `docker create` step is complete, that bpf program has no policy loaded, meaning ALL packets will be dropped.

By the time the `curl` command from `docker exec` is sending the ARP requests, the bpf program (2) is being build, with the proper policy. While this bpf program is being build and attached to the network interface, `docker exec` has already exited.

**Comment by tgraf** [comment]
Excellent analysis. We need to have bpf program (1) respond to ARP requests. That should not be difficult.

**Comment by aanm** [comment]
For future reference, we can read the labels when we receive `docker create` event, because the labels are sent along with the event since docker 1.10 (IIRC), but that doesn't help us because we also need the IP associated with the container so we can derive the endpoint ID and create an endpoint, and that is only present after we receive the `docker start` event.

**Comment by tgraf** [comment]
> For future reference, we can read the labels when we receive docker create event, because the labels are sent along with the event since docker 1.10 (IIRC), but that doesn't help us because we also need the IP associated with the container so we can derive the endpoint ID and create an endpoint, and that is only present after we receive the docker start event.

We could allocate an IP earlier if we wanted. It takes away the IP allocation feature via Docker though.

In either case, I think we agree that the first step is to enable ARP during the unknown-policy block phase.

**Comment by jrajahalme** [comment]
@tgraf Could you give be a simple policy file that allows all traffic, I'm not up too speed with the new policy model yet and getting started guide is not yet up-to-date?

**Comment by jrajahalme** [comment]
Never mind, I used this:

[{
    "endpointSelector": ["id.service1"],
    "ingress": [{
        "fromEndpoints": [
            ["reserved:host"], ["id.service2"]
        ]
    }]
}]
