### ISSUE TITLE
Kubernetes ClusterIP services: Wrong source IP in case of IP fragmentation  

### ISSUE THREAD

**Issue by mrik3110** [cilium/cilium#6323]
## Bug report

**General Information**

- Cilium version: 1.3.0
- Kernel version: 4.15.0-1030-azure # 31~16.04.1-Ubuntu SMP Tue Oct 30 19:40:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use: Kubernetes 1.10.9 and 1.12.1

**Summary**

When a pod accesses a Kubernetes Service (ClusterIp), if a response packet (in our case a UDP packet) is fragmented, the first fragment is having the service IP as source address but the next ones have the Pod IP as source address thus the reassembling fails.

Non fragmented packets are always having the service IP as source address.

The following tcpdump extract highlights the issue: [frag.zip](https://github.com/cilium/cilium/files/2629009/frag.zip)

**Comment by tgraf** [comment]
Duplicate of #8185
