### ISSUE TITLE
[FQDN]: research rfc2673 (Binary Labels)

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#6330]
We might want to check our fqdn implementation for dns names that are allowed by above RFC and test for wanted behaviour.

**Comment by tgraf** [comment]
@raybejjani Is this still needed in the context of the DNS proxy?

**Comment by raybejjani** [comment]
This was originally triggered via a `qname '0x40' - RFC 2673 unsupported yet` from gopacket running on monitor sniffed DNS requests (but possibly any old traffic in monitor).
The new proxy code doesn't show the same errors and RFC 2673 was obsoleted by EDNS so I think we are good not dealing with this.
