### ISSUE TITLE
CI: policy trace had unexpected identity returned

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6347]
Link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1978/testReport/junit/(root)/runtime/RuntimePolicyImportTests_checks_policy_trace_output/

Failure output:

```
/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
Expected allowed identities [1 28734], but instead got [1 28734 36324]
Expected
    <[]int64 | len:2, cap:2>: [1, 28734]
to equal
    <[]int64 | len:3, cap:4>: [1, 28734, 36324]
/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/runtime/Policies.go:1802
```
Logs: [9cc32cb8_RuntimePolicyImportTests_checks_policy_trace_output.zip](https://github.com/cilium/cilium/files/2634377/9cc32cb8_RuntimePolicyImportTests_checks_policy_trace_output.zip)

**Comment by ianvernon** [comment]
I believe this is due to test pollution leftover from the newly added FQDN tests.

**Comment by ianvernon** [comment]
I can't reproduce this locally by running the `RuntimeFQDNPolicies` test, and then running the `RuntimePolicyImport` test.

**Comment by ianvernon** [comment]
Reopening, issue is still occurring.

**Comment by ianvernon** [comment]
Issue re-occurred in the following builds:

* https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1988/testReport/junit/(root)/runtime/RuntimePolicyImportTests_checks_policy_trace_output/
* https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1983/testReport/junit/(root)/runtime/RuntimePolicyImportTests_checks_policy_trace_output/

**Comment by joestringer** [comment]
This issue reoccurred several times today on master (see #6449).

**Comment by ianvernon** [comment]
Picking up work on this again now.

**Comment by ianvernon** [comment]
The most recent documented failure:
https://github.com/cilium/cilium/issues/6449#issue-390470923

```
Expected
    <[]int64 | len:2, cap:2>: [1, 31542]
to equal
    <[]int64 | len:3, cap:4>: [1, 29722, 31542]
```

When retrieving the identities with label `container:id.httpd2`, only one was returned : 

```
STEP: Getting all identities which contain label container:id.httpd2
time="2018-12-12T17:49:57Z" level=debug msg="running command: sudo cilium identity get --label=container:id.httpd2 -o json"
cmd: "sudo cilium identity get --label=container:id.httpd2 -o json" exitCode: 0 duration: 71.822034ms stdout:
[
  {
    "id": 31542,
    "labels": [
      "container:id.httpd2"
    ],
    "labelsSHA256": "6bc43f32a6e1ba7dd732cc2541be8fb702ba8008f7f81cd0f4d13ce29e64bbcb"
  }
]
```

But, `cilium identity list` in the bugtool shows the identity from the ToFQDNs test still exists:

```
29722   container:app=test
        container:id.httpd2
        container:id.service1
31542   container:id.httpd2
        container:id.service1
```

I don't understand why `29722` doesn't show up in the output of `cilium identity get`, but shows up in the output of `cilium identity list`. 

The code paths for which identities are retrieved are different if no labels are provided (list) vs. labels being provided (get):

https://github.com/cilium/cilium/blob/0cfc70c18f2423718741c37f53ef48b0972837d9/daemon/identity.go#L32-L50

**Comment by ianvernon** [comment]
The behavior where the identity is still in the output of `cilium identity list` but not in the output of `cilium identity get` is easy to reproduce.

1. Run the RuntimeToFQDNs test:
```
 ginkgo --focus="RuntimeFQDNPolicies" -v 
```

2. Check that `cilium identity list` contains an identity with label `container:id.httpd2`:

```
...
46580   container:app=test
        container:id.httpd2
        container:id.service1
...
```

but `cilium identity get --label=container:id.httpd2 -o json` returns nothing:
```
$ cilium identity get --label=container:id.httpd2 -o json
level=info msg="Detected MTU 1500" subsys=mtu
Error: Cannot get identity for labels [container:id.httpd2]: [GET /identity][404] getIdentityNotFound 
```

**Comment by ianvernon** [comment]
Turns out you need to specify *all* labels for the identity to resolve with `cilium identity get`, not a subset of the labels:

```
$ cilium identity get --label=container:id.httpd2,container:id.service1,container:app=test -o json
level=info msg="Detected MTU 1500" subsys=mtu
[
  {
    "id": 46580,
    "labels": [
      "container:app=test",
      "container:id.httpd2",
      "container:id.service1"
    ],
    "labelsSHA256": "fd4881d7b289628c17b00b3aef9768ab5c6a91bf9cc9c27064de3c03490aa7f0"
  }
]
```

This differs from how rules are computed in Cilium, because label matching does not require exact matching of labels (i.e., if a rule allows traffic from anything with label id=app1, it will allow traffic from the following identities: {id=app1}, {id=app1, env=prod}, etc.

**Comment by joestringer** [comment]
The latest hit of this issue was due to a test pollution issue from a prior test:

```
Expected allowed identities [1 13687 15810], but instead got [1 13687]
Expected
    <[]int64 | len:3, cap:3>: [1, 13687, 15810]
to consist of
    <[]int64 | len:2, cap:2>: [1, 13687]
the extra elements were
    <[]int64 | len:1, cap:1>: [15810]
```

Agent logs:
```
Nov 17 20:47:06 runtime cilium-agent[24319]: level=debug msg="UpdateIdentities: Adding a new identity" identity=15810 labels="[container:app=test container:id.httpd2 container:id.service1]" subsys=policy
...
Nov 17 20:50:15 runtime cilium-agent[9261]: level=debug msg="Removing identity references from policy cache" identity=15810 subsys=policy
...
Nov 17 20:50:20 runtime cilium-agent[9261]: level=debug msg="UpdateIdentities: Adding a new identity" identity=13687 labels="[container:id.httpd2 container:id.service1]" subsys=policy
```

```
$ git grep -C 3 app=test
test/runtime/fqdn.go-           vm.SampleContainersActions(
test/runtime/fqdn.go-                   helpers.Create,
test/runtime/fqdn.go-                   helpers.CiliumDockerNetwork,
test/runtime/fqdn.go:                   fmt.Sprintf("--dns=%s -l app=test", DNSServerIP))
test/runtime/fqdn.go-
test/runtime/fqdn.go-           Expect(vm.WaitEndpointsReady()).Should(BeTrue(), "Endpoints are not ready after timeout")
test/runtime/fqdn.go-   })
```

This is a different test creating pods with different identities, running immediately prior to the policies test here. The identity is not yet released at the time that this policies test runs. This policies test then prepares an exact list of expected identities, assuming that there are no other identities in the cluster remaining from prior tests. However, if the identity from the container in the earlier test is not yet garbage collected, it could interfere with this check in the test.
