### ISSUE TITLE
Reproduce reported performance deficits

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6351]
The following article has reported several performance related issues:
https://itnext.io/benchmark-results-of-kubernetes-network-plugins-cni-over-10gbit-s-network-36475925a560

Scripts:
https://github.com/InfraBuilder/k8s-cni-benchmark

This issue will track the investigation and resolution.

Blog post with published analysis:
https://cilium.io/blog/2018/12/03/cni-performance

### Performance regression of HTTP and FTP over TCP
  * Turned out to be caused by how curl measures download speed in combination with Cilium's optimistic pod scheduling strategy which treats CNI requests mostly asynchronously. This allows a pod to start running before the networking has been fully setup while ensuring that policy enforcement is always enforced correctly. This helps reduce the time to schedule a pod and thus allows to schedule pods quicker. The consequence is that the TCP connection started by curl to be established later. Unfortunately, curl measures the time of the transfer from the initial connection attempt (unlike iperf3 and netperf) and thus includes the time in which the connection is waiting to be established to the total transfer time. This leads to a lower bitrate to be reported.

 * The latest development tree already had this behavior changed but the change was not released yet. Cilium versions 1.2.6, 1.3.1 and 1.4.0 will include the commit and change this default setting to block the CNI call until all network plumbing has been completed. We will make the functionality of asynchronous network bootstrapping available to advanced users via an option.

### Increased memory consumption
   * Pre-allocated connection tracking table. The size is configurable but it is at the larger end of the spectrum and is not yet adjusted to system size / total memory available. (https://github.com/cilium/cilium/pull/6357)
   * Enabling IPv6 by default. This causes datapath structures to be allocated unnecessarily even if IPv6 is not used (https://github.com/cilium/cilium/pull/6082)
   * Large Cilium container images and binary sizes. This has already been partially addressed in 1.4 by reducing the binary sizes. Upcoming templating will remove the need to ship a compiler and will dramatically reduce the container image size.

### Increased CPU consumption
  * Not able to reproduce numbers themselves
  * Work on the roadmap to reduce CPU overhead overall:
    * BPF templating will help drive down CPU consumption on pod startup by no longer requiring an LLVM invocation. It will also reduce the time to bootstrap network and allow to shrink the container image size considerably. (@ianvernon)
    * Optimize connection tracking scanning and interval for kernels supporting LRU. (GH TBD)

**Comment by tgraf** [comment]
I've managed to partially reproduce the performance problem on 4.15 kernels. The MTU autodetection seems to not work correctly. Manually setting the MTU and adjusting for the encapsulation headers leads to increased performance.

I can see no difference between TCP and HTTP. It is possible that due to using iperf, multiple connections versus a single curl connection can hide some of the problem in the TCP-only case.

**Comment by aanm** [comment]
Autodetect mtu for VxLAN device #6368

**Comment by tgraf** [comment]
Blog post with detailed analysis:
https://cilium.io/blog/2018/12/03/cni-performance

**Comment by tgraf** [comment]
* CNI default mode has been changed
* IPv6 has been made optional and switched off by default
* Several minor optimizations regarding memory have been made. What remains seems to mainly caused by imported golang dependencies.

**Comment by tgraf** [comment]
* BPF Map pre-allocation has been merged and turned off by default for new deployments.
* BPF templating is on the way for 1.5
* There is some memory optimization work left to be done in 1.5 but overall this is addressed.
