### ISSUE TITLE
external kubeadm guide: installation is not working

### ISSUE THREAD

**Issue by brb** [cilium/cilium#6365]
As https://itnext.io/benchmark-results-of-kubernetes-network-plugins-cni-over-10gbit-s-network-36475925a560 pointed out, there are some problems when installing Cilium from [the kubeadm guide](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#tabs-pod-install-3).

First, I've tried with Cilium v1.2.0 which is used in the guide. The result is that `etcd-operator` can't get scheduled due to `0/2 nodes are available: 2 node(s) had taints that the pod didn't tolerate`.

Next, I've tried to follow the instructions with Cilium v1.3.0. This time `etcd-operator` got scheduled, but `cilium-agent` was not ready on each node due to `Not able to connect to any etcd endpoints - etcd: 0/1 connected: https://cilium-etcd-client.kube-system.svc:2379 - context deadline exceeded`.

We should fix the installation guide, as many new comers are using it when choosing a CNI plugin.

Ubuntu 18.04 LTS, Linux s02 4.15.0-20-generic, Kubernetes v1.12.3, kubeadm v1.12.2.

Related to https://github.com/cilium/cilium/issues/6116.

**Comment by BoHoehne** [comment]
Thanks for the benchmark test. 
I tested all of the cilium documentation examples and none (zero) worked out of the box.
As a result, i switched to calico.

**Comment by brb** [comment]
[The installation guide](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#tabs-pod-install-3) got fixed by https://github.com/kubernetes/website/commit/0a5ff4417d89e742b906ffcd5909921259b9cf31.
