### ISSUE TITLE
policy: look into removing ResolveCIDRPolicy functionality

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6372]
This function is currently used to generate the list of allowed CIDRs per-endpoint. It does an iteration over all rules in the repository, which is costly in terms of matching on EndpointSelectors. 

It is also used to determine the number of prefix lengths of the CIDRs which apply. @joestringer suggested we could potentially just calculate a global list of prefix-lengths across all rules, instead of per-endpoint. This may increase complexity of programs for endpoints on older kernels, since not all the rules may select all endpoints, but it would increase the scalability of policy calculation itself. This only affects kernels which do not have LPM (4.9-4.11 IIRC).

@joestringer let me know if I synthesized our discussion about this correctly here, and feel free to add any additional context.

**Comment by joestringer** [comment]
The functionality of generating the list of allowed CIDRs per-endpoint is not currently plumbed to the datapath, it is only used to determine the specific prefix lengths that are required for each endpoint to implement the CIDR policy that applies to that endpoint.

Only kernels 4.9 and 4.10 would be affected by global prefix lengths.

The best implementation of this prefix length tracking logic in the codebase today is here:

https://github.com/cilium/cilium/blob/27f149c88a23687737ac9144cb38a20d7f3c717c/pkg/counter/prefixes.go#L24-L27

This is already created and tracked inside the daemon here:

https://github.com/cilium/cilium/blob/27f149c88a23687737ac9144cb38a20d7f3c717c/daemon/daemon.go#L780-L782

There's also another somewhat duplicated copy of this logic under `pkg/ipcache`:

https://github.com/cilium/cilium/blob/27f149c88a23687737ac9144cb38a20d7f3c717c/pkg/ipcache/ipcache.go#L126

https://github.com/cilium/cilium/blob/27f149c88a23687737ac9144cb38a20d7f3c717c/pkg/ipcache/ipcache.go#L164-L181

Ideally we can shift all of this prefix length tracking code into a single point and reuse it in each of these places. For CIDRPolicy, we could consider moving the kernel defines for the ipcache prefixes into the `node_config.h` and trigger regeneration of all endpoints whenever it changes (when LPM is not in use), and this would mean that we don't need to plumb the daemon's `PrefixLengthCounter` down into the endpoints. The IPCache bits could be handled separately in another PR, which I think can simplify that code.

**Comment by ianvernon** [comment]
Looks like this has already been removed. Do we really even need the CIDRPolicy construct?

**Comment by ianvernon** [comment]
From recent performance analysis, we should try to tackle this soon, as it's clear that policy generation with a lot of CIDRs is being affected performance-wise by this:


```
(pprof) list resolvePolicyLocked
Total: 3.58s
ROUTINE ======================== github.com/cilium/cilium/pkg/policy.(*Repository).resolvePolicyLocked in /Users/ianvernon/go/src/github.com/cilium/cilium/pkg/policy/repository.go
         0      2.72s (flat, cum) 75.98% of Total
         .          .    590:	// First obtain whether policy applies in both traffic directions, as well
         .          .    591:	// as list of rules which actually select this endpoint. This allows us
         .          .    592:	// to not have to iterate through the entire rule list multiple times and
         .          .    593:	// perform the matching decision again when computing policy for each
         .          .    594:	// protocol layer, which is quite costly in terms of performance.
         .       70ms    595:	ingressEnabled, egressEnabled, matchingRules := p.computePolicyEnforcementAndRules(securityIdentity)
         .          .    596:
         .          .    597:	calculatedPolicy := &selectorPolicy{
         .          .    598:		Revision:             p.GetRevision(),
         .          .    599:		SelectorCache:        p.GetSelectorCache(),
         .          .    600:		L4Policy:             NewL4Policy(p.GetRevision()),
         .       10ms    601:		CIDRPolicy:           NewCIDRPolicy(),
         .          .    602:		IngressPolicyEnabled: ingressEnabled,
         .          .    603:		EgressPolicyEnabled:  egressEnabled,
         .          .    604:	}
         .          .    605:	calculatedPolicy.IngressPolicyEnabled = ingressEnabled
         .          .    606:	calculatedPolicy.EgressPolicyEnabled = egressEnabled
         .          .    607:
         .          .    608:	labels := securityIdentity.LabelArray
         .          .    609:	ingressCtx := SearchContext{
         .          .    610:		To:          labels,
         .          .    611:		rulesSelect: true,
         .          .    612:	}
         .          .    613:
         .          .    614:	egressCtx := SearchContext{
         .          .    615:		From:        labels,
         .          .    616:		rulesSelect: true,
         .          .    617:	}
         .          .    618:
         .          .    619:	if option.Config.TracingEnabled() {
         .          .    620:		ingressCtx.Trace = TRACE_ENABLED
         .          .    621:		egressCtx.Trace = TRACE_ENABLED
         .          .    622:	}
         .          .    623:
         .          .    624:	if ingressEnabled {
         .          .    625:		newL4IngressPolicy, err := matchingRules.resolveL4IngressPolicy(&ingressCtx, p.GetRevision(), p.GetSelectorCache())
         .          .    626:		if err != nil {
         .          .    627:			return nil, err
         .          .    628:		}
         .          .    629:
         .          .    630:		newCIDRIngressPolicy := matchingRules.resolveCIDRPolicy(&ingressCtx)
         .          .    631:		if err := newCIDRIngressPolicy.Validate(); err != nil {
         .          .    632:			return nil, err
         .          .    633:		}
         .          .    634:
         .          .    635:		calculatedPolicy.CIDRPolicy.Ingress = newCIDRIngressPolicy.Ingress
         .          .    636:		calculatedPolicy.L4Policy.Ingress = newL4IngressPolicy
         .          .    637:	}
         .          .    638:
         .          .    639:	if egressEnabled {
         .      2.02s    640:		newL4EgressPolicy, err := matchingRules.resolveL4EgressPolicy(&egressCtx, p.GetRevision(), p.GetSelectorCache())
         .          .    641:		if err != nil {
         .          .    642:			return nil, err
         .          .    643:		}
         .          .    644:
         .      620ms    645:		newCIDREgressPolicy := matchingRules.resolveCIDRPolicy(&egressCtx)
         .          .    646:		if err := newCIDREgressPolicy.Validate(); err != nil {
         .          .    647:			return nil, err
         .          .    648:		}
         .          .    649:
         .          .    650:		calculatedPolicy.CIDRPolicy.Egress = newCIDREgressPolicy.Egress
```

Approximately 17% of policy calculation time is taken by `resolveCIDRPolicy`.

**Comment by ianvernon** [comment]
Related-to https://github.com/cilium/cilium/issues/6282
