### ISSUE TITLE
Accessing NodePort via loopback address doesn't work

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#6381]
When attempting to access a service behind a NodePort via `127.0.0.1:myport`, the traffic gets routed into the appropriate endpoint with the source address `127.0.0.1`. This causes the container's replies to be sent to 127.0.0.1 loopback inside the container, rather than routing back out to the host namespace to deliver to the loopback address there.

To fix this, we should perform some sort of source address translation similar to this for locally-sourced loopback traffic:

https://github.com/cilium/cilium/blob/27f149c88a23687737ac9144cb38a20d7f3c717c/bpf/lib/lb.h#L761-L773

**Comment by danwent** [comment]
From other reports, it seems like this issue is just an issue for the worker node where the destination pod is running.   The SNAT seems to happen properly when the destination pod is running on a different node.

**Comment by joestringer** [comment]
Possibly broken by https://github.com/cilium/cilium/pull/5608.
