### ISSUE TITLE
Proposal: Add Cilium deployment configuration for health monitor

### ISSUE THREAD

**Issue by TimEvens** [cilium/cilium#6394]
We would like to have the ability to configure health monitor settings via the deployment of cilium (e.g. cni config, conflist, cilium args, etc.).  We currently deploy cilium using kubespray.  Today there are no options for us to configure the various health monitor settings, such as the **interval**.  
 
We are planning to use the health monitor to proactively monitor the L3 reachability between each node. It is critical for us to ensure that each node has reachability to each other node via the overlay. The node may be reachable but vxlan reachability may not be (e.g. acl/fw issue or similar).   

For us, the interval of 60 seconds is too long. We would like it to be 1 to 5 seconds.  Considering a shorter interval, it would make sense to have **two counters** exposed that indicate number of **failed** probes and number of **successful** probes.   We may monitor the failed counter to raise an action if the count increases X amount over a given period.  We need the success counter so that we can validate that probes are in fact running.   If there is a stall, then something is wrong.  These counters should be per node probe. 

Probes at a shorter interval raise additional questions, such as: 
* **global sync** - we do not want all probes on each node probing exactly at the same time.  Randomizing should mitigate this
* **probe timeout** - Probe that does not respond in less than the interval results in failed probe.  IMO, this is a failed probe
* **toppling over** - Monitor process cannot keep up with the number of probes based on short interval.  This is normally mitigated by keeping probes strictly simple and running asynchronously.

**Comment by joestringer** [comment]
Great thoughts. I have been involved in projects before that use an implementation of [Bi-directional Forwarding Detection](https://tools.ietf.org/html/rfc5880) (BFD) for this sort of link-monitoring and reachability. Perhaps we could use or extend something like https://github.com/jthurman42/go-bfd in the cilium-health daemon for this purpose.

Separately, there is an outstanding PR (#5713) to split `cilium-health` into a separate DaemonSet which will help in the direction of customising and improving the configuration of the daemon.
