### ISSUE TITLE
cilium run CrashLoopBackOff

### ISSUE THREAD

**Issue by Jack-qing** [cilium/cilium#6424]
docker:v17
etcd:v3.1.12-linux-amd64.tar.gz 
kubernetes:v1.10.11-linux-amd64 
cilium:v1.0
system:ubuntu:18.04

Tutorial operation:
#
[cilium.txt](https://github.com/cilium/cilium/files/2660299/cilium.txt)

 mount BPF filesystem on all nodes
$ mount bpffs /sys/fs/bpf -t bpf
$ wget https://raw.githubusercontent.com/cilium/cilium/doc-1.0/examples/kubernetes/1.10/cilium.yaml
$ vim cilium.yaml
[adjust the etcd address]
$ kubectl create -f ./cilium.yaml
The attachment is to configure txt file information

[describe-cilium.txt](https://github.com/cilium/cilium/files/2660303/describe-cilium.txt)

command: kubectl get pods -o wide --all-namespaces
NAMESPACE     NAME           READY     STATUS             RESTARTS   AGE       IP               NODE
kube-system   cilium-46bqh   0/1       CrashLoopBackOff   6          12m       192.168.10.111   k8s-slave3
kube-system   cilium-lgrpv   0/1       CrashLoopBackOff   6          12m       192.168.10.112   k8s-slave2
kube-system   cilium-z526h   0/1       CrashLoopBackOff   6          12m       192.168.10.108   k8s-slave1

ETCD+kubernetesIt runs successfully.
I want cilium to run, but it's not going to work. Ask for help.

**Comment by aanm** [comment]
Hello @Jack-qing in your cilium configuration try putting the etcd endpoints in the following format:

```
    endpoints:
    - https://192.168.10.120:2380
    - https://192.168.10.106:2380
    - https://192.168.10.117:2380
```

I don't know what is your etcd configuration but usually the clients connect to the port 2379.

Also, where did you get the instructions to install cilium? Cilium 1.0 is end of life, please use cilium 1.3.0.

Let me know if that helps!

**Comment by Jack-qing** [comment]
@aanm Thank
http://docs.cilium.io/en/stable/kubernetes/install/standard/#k8s-install-standard
Official Standard Installation Guidelines

There is no meaning in the attachment. Can you explain it for me?
Look for etcd certificates in yaml

[clilum.txt](https://github.com/cilium/cilium/files/2660353/clilum.txt)

**Comment by aanm** [comment]
@Jack-qing use this configuration map:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  # This etcd-config contains the etcd endpoints of your cluster. If you use
  # TLS please make sure you uncomment the ca-file line and add the respective
  # certificate has a k8s secret, see explanation below in the comment labeled
  # "ETCD-CERT"
  etcd-config: |-
    ---
    endpoints:
    - https://192.168.10.120:2380
    - https://192.168.10.106:2380
    - https://192.168.10.117:2380
    #
    # In case you want to use TLS in etcd, uncomment the following line
    # and add the certificate as explained in the comment labeled "ETCD-CERT"
    ca-file: '/var/lib/etcd-secrets/etcd-ca'
    #
    # In case you want client to server authentication, uncomment the following
    # lines and add the certificate and key in cilium-etcd-secrets below
    key-file: '/var/lib/etcd-secrets/etcd-client-key'
    cert-file: '/var/lib/etcd-secrets/etcd-client-crt'

  # If you want to run cilium in debug mode change this value to true
  debug: "false"
  disable-ipv4: "false"
  sidecar-http-proxy: "false"
```

**Comment by Jack-qing** [comment]
@aanm  Thank，

**Comment by Jack-qing** [comment]
@aanm Hello 
I need your help,
Wrong information：Readiness probe failed: level=info msg="Detected MTU 1500" subsys=mtu
Get http:///var/run/cilium/cilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory Is the agent running?

ETCD To configure：
[Unit]                                                                                                                                            
Description=Etcd Server                                                                                                                           
After=network.target                                                                                                                              
After=network-online.target                                                                                                                       
Wants=network-online.target                                                                                                                       
[Service]                                                                                                                                         
Type=notify                                                                                                                                       
WorkingDirectory=/opt/etcd/                                                                                                                       
User=etcd                                                                                                                                         
# set GOMAXPROCS to number of processors                                                                                                          
ExecStart=/usr/local/bin/etcd \                                                                                                                   
  --name=etcd1 \                                                                                                                                  
  --cert-file=/etc/kubernetes/ssl/etcd.pem \                                                                                                      
  --key-file=/etc/kubernetes/ssl/etcd-key.pem \                                                                                                   
  --peer-cert-file=/etc/kubernetes/ssl/etcd.pem \                                                                                                 
  --peer-key-file=/etc/kubernetes/ssl/etcd-key.pem \                                                                                              
  --trusted-ca-file=/etc/kubernetes/ssl/ca.pem \                                                                                                  
  --peer-trusted-ca-file=/etc/kubernetes/ssl/ca.pem \                                                                                             
  --initial-advertise-peer-urls=https://192.168.10.120:2380 \                                                                                     
  --listen-peer-urls=https://192.168.10.120:2380 \                                                                                                
  --listen-client-urls=https://192.168.10.120:2379,http://127.0.0.1:2379 \                                                                        
  --advertise-client-urls=https://192.168.10.120:2379 \                                                                                           
  --initial-cluster-token=k8s-etcd-cluster \                                                                                                      
  --initial-cluster=etcd1=https://192.168.10.120:2380,etcd2=https://192.168.10.106:2380,etcd3=https://192.168.10.117:2380 \                       
  --initial-cluster-state=new \                                                                                                                   
  --data-dir=/opt/etcd/                                                                                                                           
Restart=on-failure                                                                                                                                
RestartSec=5                                                                                                                                      
LimitNOFILE=65536                                                                                                                                 
[Install]                                                                                                                                         
WantedBy=multi-user.target                                                                                                                        

cilium To configure：
Enclosure yaml file
[cilium.txt](https://github.com/cilium/cilium/files/2662783/cilium.txt)

commad:  kubectl get pods --all-namespaces 
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
kube-system   cilium-2mvlb                            0/1       CrashLoopBackOff   8          30m
kube-system   cilium-6xjdl                            0/1       CrashLoopBackOff   8          30m
kube-system   cilium-bggzp                            0/1       CrashLoopBackOff   8          30m
kube-system   cilium-c575s                            0/1       CrashLoopBackOff   8          30m
kube-system   cilium-etcd-operator-6bfd6c7457-5kz7n   1/1       Running            0          30m
kube-system   cilium-operator-7d75f5fcc-xc2lh         0/1       CrashLoopBackOff   6          30m
kube-system   cilium-wgfwc                            0/1       Running            7          30m
kube-system   cilium-xg5qc                            0/1       Running            7          30m
kube-system   etcd-operator-58cf6d756d-zrmrb          1/1       Running            0          29m

commad: kubectl describe po xxx -n kube-system
Enclosure cilium describe file

Standard Installation Guide
https://cilium.readthedocs.io/en/latest/kubernetes/install/standard/

wget https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes/1.10/cilium.yaml

Uncomment both lines #key-file: '/var/lib/etcd-secrets/etcd-client-key' and #cert-file: '/var/lib/etcd-secrets/etcd-client-crt';

Create a kubernetes secret with client.key and client.crt files in kubernetes.

Use the file with the name client.key that contains the client key;

Use the file with the name client.crt that contains the client certificate;

Create the secret by executing:
kubectl create secret generic -n kube-system cilium-etcd-secrets \ 
 --from-file = etcd-ca = /opt/ssl/ca.pem \ 
 --from-file = etcd-client-key = /opt/ssl/etcd-key.pem \ 
    --from-file = etcd-client-crt = /opt/ssl/etcd.pem

**Comment by aanm** [comment]
@Jack-qing use this configuration map:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  # This etcd-config contains the etcd endpoints of your cluster. If you use
  # TLS please make sure you uncomment the ca-file line and add the respective
  # certificate has a k8s secret, see explanation below in the comment labeled
  # "ETCD-CERT"
  etcd-config: |-
    ---
    endpoints:
    - https://192.168.10.120:2379
    - https://192.168.10.106:2379
    - https://192.168.10.117:2379
    #
    # In case you want to use TLS in etcd, uncomment the following line
    # and add the certificate as explained in the comment labeled "ETCD-CERT"
    ca-file: '/var/lib/etcd-secrets/etcd-ca'
    #
    # In case you want client to server authentication, uncomment the following
    # lines and add the certificate and key in cilium-etcd-secrets below
    key-file: '/var/lib/etcd-secrets/etcd-client-key'
    cert-file: '/var/lib/etcd-secrets/etcd-client-crt'

  # If you want to run cilium in debug mode change this value to true
  debug: "false"
  disable-ipv4: "false"
  sidecar-http-proxy: "false"
```

**Comment by Jack-qing** [comment]
@aanm Thanks very much
cilium Much better than before.

-masters: Three machine
cilium failed
[erres.txt](https://github.com/cilium/cilium/files/2667431/erres.txt)

Can not find  problem. Help analysis
Report errors：
Get http:///var/run/cilium/cilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory Is the agent running?

-slaves： Three machine
cilium running 

cilium To configure:
[yaml.txt](https://github.com/cilium/cilium/files/2667479/yaml.txt)

 

NAMESPACE     NAME           READY     STATUS             RESTARTS   AGE
kube-system   cilium-445xn   0/1       CrashLoopBackOff   36         3h
kube-system   cilium-4ldxc   1/1       Running            0          3h
kube-system   cilium-5ps5w   0/1       CrashLoopBackOff   36         3h
kube-system   cilium-c5ll4   0/1       Running            37         3h
kube-system   cilium-ctcjg   1/1       Running            0          3h
kube-system   cilium-rjpgh   1/1       Running            22         3h

**Comment by aanm** [comment]
@Jack-qing use this file 
wget https://raw.githubusercontent.com/cilium/cilium/v1.3.0/examples/kubernetes/1.10/cilium.yaml

**Comment by Jack-qing** [comment]
@aanm Thank  
Find no solution  Ask for your help

In accordance with the connection：
wget https://raw.githubusercontent.com/cilium/cilium/v1.3.0/examples/kubernetes/1.10/cilium.yaml

To configure yaml：
[cilium.txt](https://github.com/cilium/cilium/files/2670381/cilium.txt)

operation：
kubectl create secret generic -n kube-system cilium-etcd-secrets --from-file=etcd-ca=/opt/ssl/ca.pem --from-file=etcd-client-key=/opt/ssl/etcd-key.pem --from-file=etcd-client-crt=/opt/ssl/etcd.pem


-masters: -slaves: Startup failure
NAMESPACE     NAME           READY     STATUS             RESTARTS   AGE
kube-system   cilium-4qx7m   0/1       Running            5          16m
kube-system   cilium-7kqfs   0/1       CrashLoopBackOff   6          16m
kube-system   cilium-92zsh   0/1       CrashLoopBackOff   6          16m
kube-system   cilium-bq267   0/1       Running            5          16m
kube-system   cilium-nclgj   0/1       Running            5          16m
kube-system   cilium-qm7ml   0/1       CrashLoopBackOff   6          16m

inspect kubectl logs -f xxx
Error from server: Get https://k8s-masters1:10250/containerLogs/kube-system/cilium-7kqfs/cilium-agent?follow=true: dial tcp: lookup k8s-masters1 on 127.0.1.1:53: no such host

inspect docker logs image: docker.io/library/busybox:1.28.4
rm: can't remove '/var/run/cilium/cilium.pid': No such file or directory

inspect docker logs  image: docker.io/cilium/cilium:v1.3.0
level=fatal msg="timed out while waiting for etcd session. Ensure that etcd is running on [https://192.168.10.120:2379 https://192.168.10.106:2379 https://192.168.10.117:2379]" subsys=kvstore

**Comment by Jack-qing** [comment]
@aanm I'm sorry. I have many questions.
I found the problem.

cilium file run  Need 2 containers
busybox containers Operating unsuccessfully，this busybox can running  The problem can be solved.

image: docker.io/cilium/cilium:v1.3.0
image: docker.io/library/busybox:1.28.4

 spec:
      serviceAccountName: cilium
      initContainers:
        - name: clean-cilium-state
          image: docker.io/library/busybox:1.28.4
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'rm /var/run/cilium/cilium.pid; rm /var/run/cilium/state/health-endpoint.pid; if [ "${CLEAN_CILIUM_STATE}" = "true" ]; then rm -rf /var/run/cilium/state; fi; if [ "${CLEAN_CILIUM_STATE}" = "true" ] || [ "${CLEAN_CILIUM_BPF_STATE}" = "true" ]; then rm -rf /sys/fs/bpf/tc/globals/cilium_* /var/run/cilium/bpffs/tc/globals/cilium_*; fi']
          securityContext:
            capabilities:
              add:
                - "NET_ADMIN"
            privileged: true
          volumeMounts:
            - name: bpf-maps
              mountPath: /sys/fs/bpf
            - name: cilium-run
              mountPath: /var/run/cilium
          env:
            - name: "CLEAN_CILIUM_STATE"
              valueFrom:
                configMapKeyRef:
                  name: cilium-config
                  optional: true
                  key: clean-cilium-state
            - name: "CLEAN_CILIUM_BPF_STATE"
              valueFrom:
                configMapKeyRef:
                  name: cilium-config
                  optional: true
                  key: clean-cilium-bpf-state

command:  kubectl get pods --all-namespaces

NAMESPACE     NAME           READY     STATUS             RESTARTS   AGE
kube-system   cilium-55vk8   0/1       CrashLoopBackOff   11         46m
kube-system   cilium-6bg7v   1/1       Running            0          46m
kube-system   cilium-f9fx7   1/1       Running            0          46m
kube-system   cilium-fhm74   0/1       CrashLoopBackOff   11         46m
kube-system   cilium-pkrdh   0/1       CrashLoopBackOff   11         46m
kube-system   cilium-scrj4   1/1       Running            0          46m

commnd: docker ps -a

CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                      PORTS               NAMES
d8a056b83fed        f2f9f80ed41e                       "cilium-agent --debu…"   34 minutes ago      Up 34 minutes                                   k8s_cilium-agent_cilium-scrj4_kube-system_de39ef97-fdd0-11e8-9a13-fa163ea10f6b_0
9eb84570a9d7        8c811b4aec35                       "sh -c 'rm /var/run/…"   34 minutes ago      Exited (0) 34 minutes ago                       k8s_clean-cilium-state_cilium-scrj4_kube-system_de39ef97-fdd0-11e8-9a13-fa163ea10f6b_0
158f021d5651        mirrorgooglecontainers/pause:3.1   "/pause"                 34 minutes ago      Up 34 minutes                                   k8s_POD_cilium-scrj4_kube-system_de39ef97-fdd0-11e8-9a13-fa163ea10f6b_0

**Comment by Jack-qing** [comment]
@aanm  Hello

Why masters node：
Report errors：
Error from server: Get https://k8s-masters1:10250/containerLogs/kube-system/cilium-29lvx/cilium-agent?follow=true: dial tcp: lookup k8s-masters1 on 127.0.1.1:53: no such host

127.0.1.1：53  because  ubnntu There's a local one next. dns Service Be called dnsmasq It is from NetworkManager control 

root@guyi-KVM:/home/guyi# kubectl get pods --all-namespaces
NAMESPACE     NAME           READY     STATUS    RESTARTS   AGE
kube-system   cilium-29lvx   1/1       Running   0          14h         masters 
kube-system   cilium-bz5v6   1/1       Running   0          14h
kube-system   cilium-ndslr   1/1       Running   0          14h         masters
kube-system   cilium-ptnrn   1/1       Running   0          14h
kube-system   cilium-xkhgz   1/1       Running   0          14h
kube-system   cilium-zwtl8   1/1       Running   0          14h        masters

**Comment by aanm** [comment]
Hello @Jack-qing !

sorry for the slow response, I was at KubeCon this week.

Are you still facing any issues?

`kubectl get pods --all-namespaces -o wide` should show you the Cilium pod status. They should all be in `Running` state.

**Comment by Jack-qing** [comment]
@aanm Hello  to bother you.

I did the following to make it look successful

kube-proxy install All （masters / slaves） 

It's beautiful to see the results.    Printing Cilium logs   Find out this problem

root@guyi-KVM:/home/guyi# kubectl logs -f cilium-29lvx -n kube-system
Error from server: Get https://k8s-masters1:10250/containerLogs/kube-system/cilium-29lvx/cilium-agent?follow=true: dial tcp: lookup k8s-masters1 on 127.0.1.1:53: no such host

No deployment in the cluster CoreDNS

root@guyi-KVM:/home/guyi# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME           READY     STATUS    RESTARTS   AGE       IP               NODE
kube-system   cilium-29lvx   1/1       Running   0          1d        192.168.10.120   k8s-masters1
kube-system   cilium-6vk8f   1/1       Running   0          15h       192.168.10.106   k8s-masters2
kube-system   cilium-bz5v6   1/1       Running   0          1d        192.168.10.112   k8s-slave2
kube-system   cilium-ptnrn   1/1       Running   0          1d        192.168.10.108   k8s-slave1
kube-system   cilium-xkhgz   1/1       Running   0          1d        192.168.10.111   k8s-slave3
kube-system   cilium-zwtl8   1/1       Running   0          1d        192.168.10.117   k8s-masters3


There is a container.  No successful startup.  No Answer can be solved.

root@guyi-KVM:/home/guyi# docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                    PORTS               NAMES
7297b0ebd28f        f2f9f80ed41e                       "cilium-agent --debu…"   42 hours ago        Up 42 hours                                   k8s_cilium-agent_cilium-ptnrn_kube-system_9b757ae4-fed6-11e8-9a13-fa163ea10f6b_0
31d257b3cb9f        8c811b4aec35                       "sh -c 'rm /var/run/…"   42 hours ago        Exited (0) 42 hours ago                       k8s_clean-cilium-state_cilium-ptnrn_kube-system_9b757ae4-fed6-11e8-9a13-fa163ea10f6b_0
05e47c37faeb        mirrorgooglecontainers/pause:3.1   "/pause"                 42 hours ago        Up 42 hours                                   k8s_POD_cilium-ptnrn_kube-system_9b757ae4-fed6-11e8-9a13-fa163ea10f6b_0
2abcb2d34ed0        nginx:1.13.7-alpine                "nginx -g 'daemon of…"   4 days ago          Up 4 days                                     nginx-proxy

docker logs
root@guyi-KVM:/home/guyi# docker logs 31d257b3cb9f                                                                                                  
rm: can't remove '/var/run/cilium/cilium.pid': No such file or directory

**Comment by tgraf** [comment]
@Jack-qing Do you have a DNS server running at 127.0.0.1:53?

**Comment by Jack-qing** [comment]
@tgraf Hello     ubuntn Is a local DNS Service

It bothers me. I tried many different ways to solve the problem.

Investigation reasons：

Under ubuntu, there is a local DNS service called dnsmasq, which is controlled by Network Manager.
It listens for a local address, - - listen-address = 127.0.1.1, which is a localloopback address The real DNS server address is maintained by this service management
ocal process -> local dnsmasq -> router -> ISP dns


/home/guyi# ps -ef | grep dnsmasq
root       422 24445  0 09:58 pts/0    00:00:00 grep dnsmasq
nobody    1391   845  0 12月11 ?      00:00:20 /usr/sbin/dnsmasq --no-resolv --keep-in-foreground --no-hosts --bind-interfaces --pid-file=/var/run/NetworkManager/dnsmasq.pid --listen-address=127.0.1.1 --cache-size=0 --conf-file=/dev/null --proxy-dnssec --enable-dbus=org.freedesktop.NetworkManager.dnsmasq --conf-dir=/etc/NetworkManager/dnsmasq.d


Generate files in my directory
/home/guyi/ # ls
 examples.desktop  ISP    local  router


vim  /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)                                                                                         
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN                                                                                                
nameserver 127.0.1.1                                                                                                                                                   
search openstacklocal 

/home/guyi# kubectl get pods -n kube-system -o wide                                                                                 
NAME           READY     STATUS    RESTARTS   AGE       IP               NODE
cilium-29lvx   1/1       Running   0          3d        192.168.10.120   k8s-masters1
cilium-bz5v6   1/1       Running   0          3d        192.168.10.112   k8s-slave2
cilium-fq7g5   1/1       Running   0          1d        192.168.10.106   k8s-masters2
cilium-ptnrn   1/1       Running   0          3d        192.168.10.108   k8s-slave1
cilium-xkhgz   1/1       Running   0          3d        192.168.10.111   k8s-slave3
cilium-zwtl8   1/1       Running   0          3d        192.168.10.117   k8s-masters3

 kubectl logs -f cilium-29lvx -n kube-system
Error from server: Get https://k8s-masters1:10250/containerLogs/kube-system/cilium-29lvx/cilium-agent?follow=true: dial tcp: lookup k8s-masters1 on 127.0.1.1:53: no such host
