### ISSUE TITLE
AWS ENI support

### ISSUE THREAD

**Issue by Globegitter** [cilium/cilium#6430]
## Proposal / RFE

Mentioned this on Slack and @tgraf mentioned to create a new issue about my request:

I have just been looking at the aws alb ingress controller (https://github.com/kubernetes-sigs/aws-alb-ingress-controller) to consider its use for us - it says traffic can be routed either through the service's nodeport (default) or directly through the pod IP if the CNI uses secondary IP addresses on the Elastic Network Interface: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/78f88a583465714c9e554edf9746f43336a60b72/docs/guide/ingress/annotation.md#traffic-routing

Would be nice to be able to get "native" AWS support.

**Comment by kekoav** [comment]
Any details on the future implementation of this? I'd be interested to see if the CNI from AWS can be leveraged to do the heavy lifting: https://github.com/aws/amazon-vpc-cni-k8s .
