### ISSUE TITLE
kernel: sockmap redirect sockets need to due additional TCP layer accounting

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#6431]
## Bug report

Currently sockmap redirect BPF API only does socket level accounting however it omits doing tcp_wmem and tcp_rmem accounting. Because sockmap is transparent to the administrator we can not require other memory limits and should honor any existing limits.

**General Information**

Upstream kernel bug.

**How to reproduce the issue**

 Have fast client and slow(er) server. Send as much data as possible at server and observe wmem/rmem are not being accounted. Note, socket level accounting is done however.

**Comment by zachidan** [comment]
@jrfastab what is the status of this issue ? any idea if there is a plan to fix it ?

**Comment by jrfastab** [comment]
@zachidan I still need to fix this. I expect to get to it sometime in the next month or two most likely.

**Comment by xu1zhou** [comment]
@jrfastab ,  is this issue has been resolved? or any progress?

**Comment by jrfastab** [comment]
This is mostly resolved upstream but there are still a few problems about what to do when limits are reached. Will fix upstream. Closing from Cilium side.
