### ISSUE TITLE
cilium and coredns restart continuously due to timed out while waiting for etcd session

### ISSUE THREAD

**Issue by TCiPongor** [cilium/cilium#6437]
## Bug report

**General Information**

- Cilium version 
cilium images info ： 
cilium/cilium: v1.2.2
etcd-operator images info ： 
etcd-operator: v0.9.2

- Kernel version
Linux master1 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- kubernetes version
kubernetes：v1.11.0
kubeadm: 1.11.0-00 
kubectl : 1.11.0-00 
kubelet: 1.11.0-00 

- steps of installation 
---part 1:kubernetes install---
1.sudo swapoff -a 
2.sudo apt-get install -qy docker.io
3.sudo apt-get install -y  kubelet=1.11.0-00   kubeadm=1.11.0-00 kubectl=1.11.0-00
4.kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.10.101 --kubernetes-version=v1.11.0
-----part 2:cilium install------
5.sudo mount bpffs /sys/fs/bpf -t bpf
6.sudo sed -i.bak '$a bpffs   /sys/fs/bpf     bpf     rw,relatime     0       0' /etc/fstab
7.sudo apt install golang-cfssl 
8.wget https://github.com/cilium/cilium/archive/v1.3.0.tar.gz
9.tar xvf v1.3.0.tar.gz
10.cd cilium-1.3.0/examples/kubernetes/addons/etcd-operator/
11.tls/certs/gen-cert.sh cluster.local
12.tls/deploy-certs.sh
13.kubectl label -n kube-system pod $(kubectl -n kube-system get pods -l k8s-app=kube-dns -o jsonpath='{range .items[]}{.metadata.name}{" "}{end}') io.cilium.fixed-identity=kube-dns
14.kubectl -n kube-system delete pod -l k8s-app=kube-dns
15.kubectl create -f ./
**Wait several minutes for Cilium, coredns and etcd pods to converge to a working state**
kubectl get pods -n kube-system

**How to reproduce the issue**

1.cilium and coredns restart continuously 
-cilium status:
$kubectl describe po -n kube-system cilium-jhsj8
Warning  Unhealthy  44m (x11 over 54m)  kubelet, master1  Readiness probe failed: KVStore:                Failure   Err: Not able to connect to any etcd endpoints - etcd: 0/1 connected: https://cilium-etcd-client.kube-system.svc:2379 - context deadline exceeded

$kubectl -n kube-system exec -ti cilium-jhsj8  -- cilium status
Cilium:                 Failure   Kvstore service is not ready
NodeMonitor:            Disabled

$kubectl logs -n kube-system cilium-jhsj8
level=warning msg="Unable to verify version of etcd endpoint" error="context deadline exceeded" etcdEndpoint="https://cilium-etcd-client.kube-system.svc:2379" subsys=kvstore

more  info:
[cilium-bugtool-20181211-012808.181+0000-UTC-083540489.zip](https://github.com/cilium/cilium/files/2665646/cilium-bugtool-20181211-012808.181%2B0000-UTC-083540489.zip)

2. etcd-operator logs:"tcp ... i/o timeout"

$kubectl describe po -n kube-system etcd-operator-759954d8db-xh9zz 
Name:           etcd-operator-759954d8db-xh9zz
Namespace:      kube-system
Node:           master1/192.168.10.101
Start Time:     Tue, 11 Dec 2018 09:07:22 +0800
Labels:         io.cilium/app=etcd-operator
                pod-template-hash=3155108486
Annotations:    cilium.io/identity=5
Status:         Running
IP:             10.244.0.60

$kubectl logs -n kube-system etcd-operator-759954d8db-xh9zz
E1211 02:12:09.516095       1 leaderelection.go:224] error retrieving resource lock kube-system/etcd-operator: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/endpoints/etcd-operator: dial tcp 10.96.0.1:443: i/o timeout

**Comment by aanm** [comment]
Hello @PTEpzb!

sorry for the slow response, I was at KubeCon this week.

Please follow the following steps and let me know if you're still facing issues:
```
---part 1:kubernetes install---
1.sudo swapoff -a
2.sudo apt-get install -qy docker.io
3.sudo apt-get install -y kubelet=1.11.0-00 kubeadm=1.11.0-00 kubectl=1.11.0-00
4.kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.10.101 --kubernetes-version=v1.11.0
-----part 2:cilium install------
5.sudo mount bpffs /sys/fs/bpf -t bpf
6.sudo sed -i.bak '$a bpffs /sys/fs/bpf bpf rw,relatime 0 0' /etc/fstab
7.kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.4.0-rc1/examples/kubernetes/1.11/cilium.yaml
Wait several minutes for Cilium, coredns and etcd pods to converge to a working state
kubectl get pods -n kube-system
```

**Comment by TCiPongor** [comment]
> Hello @PTEpzb!
> 
> sorry for the slow response, I was at KubeCon this week.
> 
> Please follow the following steps and let me know if you're still facing issues:
> 
> ```
> ---part 1:kubernetes install---
> 1.sudo swapoff -a
> 2.sudo apt-get install -qy docker.io
> 3.sudo apt-get install -y kubelet=1.11.0-00 kubeadm=1.11.0-00 kubectl=1.11.0-00
> 4.kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.10.101 --kubernetes-version=v1.11.0
> -----part 2:cilium install------
> 5.sudo mount bpffs /sys/fs/bpf -t bpf
> 6.sudo sed -i.bak '$a bpffs /sys/fs/bpf bpf rw,relatime 0 0' /etc/fstab
> 7.kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.4.0-rc1/examples/kubernetes/1.11/cilium.yaml
> Wait several minutes for Cilium, coredns and etcd pods to converge to a working state
> kubectl get pods -n kube-system
> ```

Hi @aanm !
thanks for your reply,I will reply to you in time after following the steps.

**Comment by aanm** [comment]
@PTEpzb Any luck so far?

**Comment by TCiPongor** [comment]
> @PTEpzb Any luck so far?

sorry for the slow response, I was at another project  this period.I forgot to reply to you until  receive your email.
thanks for your help,it worked,after following the steps.

kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.4.0-rc1/examples/kubernetes/1.13/cilium.yaml


after following this step,the pod of cilium worked.

**Comment by aanm** [comment]
@PTEpzb glad it work out, let us know if you have any questions. I'll close the issue since it's solved.
