### ISSUE TITLE
kernel: sockmap support for blocking redirects

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#6438]
Sockmap doesn't support blocking the rational is that it could induce head of line blocking. However in the point to point case (or if the BPF author "knows" its ok) its useful to introduce a blocking flag to the redirect API.

**Comment by SPYFF** [comment]
Is #1797 related to this one? Or that is already merged? Because this blocking scenario would be really interesting with skb gifting.

**Comment by zoobab** [comment]
Is it fixed yet?

**Comment by jrfastab** [comment]
closing from Cilium portal and tracking in a new PR with complete fix across multiple issues.

**Comment by mestery** [comment]
@jrfastab Can you link to the new PR here please, I'd like to follow along with that one as well. Thanks!
