### ISSUE TITLE
kernel/bpftool: sockmap and hashmap insert creates different entries

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#6439]
Report from bpf Cilium channel: (Note this does not impact Cilium datapath but could cause potential confusion during debugging.)

I'm seeing different things when getting `local_port` from the sockops and from the sk_msg programs, I'm using the same functions as cilium (https://github.com/cilium/cilium/blob/fe3626c67c7/bpf/sockops/bpf_sockops.h#L56) and in the sockops program I write `key` to the sockmap and in sk_msg I write it to a hashmap so I can compare with `bpftool` from userspace. I see this:

```sockmap:
key:
7f 00 00 01 7f 00 00 01  01 00 00 00 cd 2a 00 00
23 82 00 00
value:
<no entry>

hashmap (sk_msg):
key:
7f 00 00 01 7f 00 00 01  01 00 00 00 00 00 00 00
23 82 00 00
value:
01 00 00 00```

**Comment by iaguis** [comment]
What I'm doing to get this is the following:

I have a sockops program attached to the root cgroupv2 that extracts the key with one of the [cilium functions](https://github.com/cilium/cilium/blob/fe3626c67c7/bpf/sockops/bpf_sockops.h#L56) and, if the destination IP is localhost, adds it to the sockmap with swapped source/destination tuples.

Then I have a sk_msg program attached to the sockmap that extracts the key (again with one of the cilium functions) and updates a "debug" hashmap.

Comparing the sockmap and the "debug" hashmaps with bpftool I see the results mentioned in the OP.

I can make it work doing some bit manipulations that please the verifier, for example:

```go
key->sport = ((sport >> 8) | (sport << 8)) & 0xffff
```

**Comment by jrfastab** [comment]
Closing I don't care much if bpftool is incorrect although would be nice to fix.
