### ISSUE TITLE
Do not fail agent when etcd connection attempt times out

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6457]
Failing the agent can make it complicated to get everything up and running as exponential backoff can cause cilium to not be running for a while which can delay cilium-etcd from bootstrapping. This makes troubleshooting more difficult.

**Comment by aanm** [comment]
Agree, we can increase the timeout for 10 minutes or, since we can reach the kube-apiserver at that time, remove the timeout if we know there's an etcd-operator involved.
