### ISSUE TITLE
CONFIG_MAP bpf map created

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6491]
A file called `CONFIG_MAP` is created in `/run/cilium/bpffs/tc/globals/` which indicates that a BPF program is created which does not have the CONFIG_MAP define set.  Is is likely one of the global programs.

**Comment by joestringer** [comment]
~~Which kernel?~~

Ah, I see what you man about it likely being the global programs. Perhaps the simplest fix would be to wrap the config-map declaration in the BPF side with `#ifdef CONFIG_MAP ...`.

**Comment by ianvernon** [comment]
@tgraf @joestringer what is the desired fix for this issue? Should the config map be created for the global programs, or should we only do it when `#ifdef CONFIG_MAP` evaluates to `true`, and put `CONFIG_MAP` as a boolean option for the endpoints within the cilium agent? Or can I define that in `bpf_lxc.c`?
