### ISSUE TITLE
Deleting cilium pods messes with hostport mappings

### ISSUE THREAD

**Issue by felipejfc** [cilium/cilium#6499]
Hi guys, we've been using cilium in production for some time now and our kubernetes use case includes a lot of pods that runs with hostPort (using portmap plugin).

We observed today that these pods became unreachable by the hostport after a cilium update, so after some research I found that after I restart cilium pods, iptables rules that are necessary for hostPort to work always get deleted, to be more specific, these are the rules in iptables before deleting cilium pod:
```
-A CNI-DN-c20774ee0bf22c7e19507 -p udp -m udp --dport 41529 -j DNAT --to-destination 10.56.4.152:7788
-A CNI-DN-9b37bc50e0ab952351885 -p udp -m udp --dport 43407 -j DNAT --to-destination 10.56.4.13:7788
-A CNI-HOSTPORT-DNAT -m comment --comment "dnat name: \"cilium-portmap\" id: \"883b02f84c3cdd3e5e8432fecab3306a6a180c32aa0a6c78a0378d532cbe9d13\"" -j CNI-DN-c20774ee0bf22c7e19507
-A CNI-HOSTPORT-DNAT -m comment --comment "dnat name: \"cilium-portmap\" id: \"00f324f7e68994294c2a2edde64e823d93d7338ba6e9646f252ea412d8ae1163\"" -j CNI-DN-9b37bc50e0ab952351885
-A CNI-HOSTPORT-SNAT -m comment --comment "snat name: \"cilium-portmap\" id: \"883b02f84c3cdd3e5e8432fecab3306a6a180c32aa0a6c78a0378d532cbe9d13\"" -j CNI-SN-c20774ee0bf22c7e19507
-A CNI-HOSTPORT-SNAT -m comment --comment "snat name: \"cilium-portmap\" id: \"00f324f7e68994294c2a2edde64e823d93d7338ba6e9646f252ea412d8ae1163\"" -j CNI-SN-9b37bc50e0ab952351885
-A CNI-SN-9b37bc50e0ab952351885 -s 127.0.0.1/32 -d 10.56.4.13/32 -p udp -m udp --dport 7788 -j MASQUERADE
-A CNI-SN-c20774ee0bf22c7e19507 -s 127.0.0.1/32 -d 10.56.4.152/32 -p udp -m udp --dport 7788 -j MASQUERADE
```

after deleting cilium pods and seeing they be recreated only this two rules exist:
```
-A CNI-DN-9b37bc50e0ab952351885 -p udp -m udp --dport 43407 -j DNAT --to-destination 10.56.4.13:7788
-A CNI-DN-c20774ee0bf22c7e19507 -p udp -m udp --dport 41529 -j DNAT --to-destination 10.56.4.152:7788
```

so the chain in being messed up somehow when I delete cilium pods.

**General Information**

- Cilium version: 1.3.1
- Kernel version: Linux ip-172-23-47-184 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use: kube 1.10.11

**How to reproduce the issue**

1. run with portmap enabled
2. create a pod that has a hostPort configured
3. see that its accessible
4. delete cilium pod and wait for it to be recreated
5. see that pod will no longer be accessible using the node port
6. if delete the pod and wait for it to be rescheduled, it will be accessible again

**Comment by tgraf** [comment]
The issue has been tracked down to the following logic:
When Cilium starts up. It removes all iptables rules with the word `cilium` in it. This is done to remove rules which have been installed by prior versions of Cilium but are no longer in use. By calling the hostPort plugin `cilium-portmap` this leads to rules being removed incorrectly.
