### ISSUE TITLE
Where could I find Dockerfile for cilium-envoy 、cilium-builder and  cilium-runtime 

### ISSUE THREAD

**Issue by bianhua2015** [cilium/cilium#6508]

**Comment by bianhua2015** [comment]
I want to modify cilium's code and build cilium:1.3 by myself,but I cant find related documents

**Comment by joestringer** [comment]
Hi, you can find the Dockerfiles at the following locations:

`cilium-envoy`: https://github.com/cilium/proxy/blob/master/Dockerfile
`cilium-builder`: https://github.com/cilium/cilium/blob/master/Dockerfile.builder
`cilium-runtime`: https://github.com/cilium/cilium/blob/master/contrib/packaging/docker/Dockerfile.runtime
`cilium`: https://github.com/cilium/cilium/blob/master/Dockerfile
