### ISSUE TITLE
cilium-kube-inject script breaks with istio v1.0.3 and newer

### ISSUE THREAD

**Issue by jeckhart** [cilium/cilium#6510]
## Bug report

**General Information**

- Cilium version 1.3
- Kernel version 'n/a'
- Orchestration system version in use: kubernetes v1.9.3 / kubectl v1.11.2
- Link to relevant artifacts
https://github.com/istio/istio/pull/8624/commits/7618f89318480cc951088f597dc26685ad230d76
https://github.com/istio/istio/blame/1.0.3/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml

**How to reproduce the issue**

1. Follow the istio directions in the getting started docs:
https://cilium.readthedocs.io/en/latest/gettingstarted/istio/
2. Use a recent version of istio (v1.0.3 or later)
3. The step where you run `awk -f cilium-kube-inject.awk` generates incorrect yaml because the format of https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml changed between istio-v1.0.2 and istio-v1.0.3 .

**Comment by ianvernon** [comment]
@jeckhart sorry for letting this issue rot. We have support up until Istio 1.2 now which should work. I will close this in a few weeks if it receives no reply.
