### ISSUE TITLE
configure podcidr through cilium flags

### ISSUE THREAD

**Issue by manojbadam** [cilium/cilium#6519]
## PodCIDR configurable through cilium configMap file

**Is your feature request related to a problem?**
Currently Cilium checks the control plane configs for assigning Pod IPs.  In EKS, we don't own the Control plane and `--cluster-cidr` variable is not configurable. So it is not possible to configure the Pod IPs 

**Describe the solution you'd like**
I came to know about the node annotation `io.cilium.network.ipv4-pod-cidr: 10.16.0.0/16` for doing this (Not sure how to set this annotation through kubelet configs). If we could configure this value through cilium [configMap file](https://github.com/cilium/cilium/blob/93c115a616671264cfd1fdc235f42c0f18047abe/examples/kubernetes/1.10/cilium-cm.yaml) that will be really helpful.

**Comment by tgraf** [comment]
@manojbadam Are you OK with the auto-allocation of PodCIDR based on the last 8 bits of the first public IPv4 address found on the node or do you need to be able to dictate the PodCIDR per node? Making the cluster range configurable is not difficult, providing a different allocation mechanism would be more work.

**Comment by manojbadam** [comment]
@tgraf - That is acceptable, as long as the last octet doesn’t overlap with the cluster’s IP space. So it couldn’t use 10. for example if you do something like “if 4th octet of IP == 10, cidr=101” or something

**Comment by manojbadam** [comment]
Since we need more deterministic podCidr to apply all network policies, above method could be little tricky solution and couldn't lead us to a single cidr.  We took the kubelet annotations mechanism and setting up our own custom CIDR spanning `100.64.0.0/10`  

we added a systemd unit after the kubelet startup and whenever it registers to the control plane, the one-time job will add ipv4 cidr annotation computed from node Primary IP address within the range of `100.64.0.0/10`.

**Comment by tgraf** [comment]
still alive

**Comment by sleerssen** [comment]
I have a similar issue in AWS with peered VPCs.  The current node subnet allocation using the last octet is overlapping subnets in other VPCs and causing routing issues.  If I could specify the overlay subnet with a reserved range (e.g. 10.111.X.0/16) where the last octet of the node IP is used to for X, it would greatly simplify the configuration.  Even being able to specify something like 192.168.X.0/16, where I'm guaranteed there will not be a conflict with the 10.0.0.0/8 address space would solve my problem.

**Comment by tgraf** [comment]
This is now available via the new `cluster-pool` IPAM mode:
https://docs.cilium.io/en/v1.8/concepts/networking/ipam/cluster-pool/
