### ISSUE TITLE
Can Cilium implement ClusterIP and replace kube-proxy?

### ISSUE THREAD

**Issue by waret** [cilium/cilium#6534]
## Support

According to [here](https://cilium.readthedocs.io/en/stable/kubernetes/intro/#service-load-balancing), can I use Cilium in my Kubernetes Cluster without kube-proxy deployed? And how?
Thanks!

**Comment by tgraf** [comment]
@Waret Yes. Cilium automatically implements ClusterIP. No special configuration required. You still need to run kube-proxy if you need NodePort services. Cilium does not implement those right now.

**Comment by davitmadoyan** [comment]
When you say "Cilium automatically implements ClusterIP", do you mean that still clusterIP is being forwarded to Pods IP's via IP tables? if not then how is it done in Cilium?

**Comment by brb** [comment]
> do you mean that still clusterIP is being forwarded to Pods IP's via IP tables?

No, forwarding is done by a BPF program which checks whether a destination IP address is of a service: https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L427. The service mappings are maintained by cilium-agent which subscribes to kube-apiserver for service-related events.
