### ISSUE TITLE
Write guide how to use kubeadm w/ Cilium

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#654]

**Comment by amit-handa** [comment]
eagerly looking to try cilium with kubeadm. however, cilium daemonset refuses to start 
```
level=fatal msg="Unable to setup kvstore" address= error="Unable to contact etcd: Timed out while waiting for etcd session. Ensure that etcd version is at least >= 3.1.0" kvstore=etcd
```
i just installed cilium 
```
kubectl create -f https://raw.githubusercontent.com/cilium/cilium/master/examples/kubernetes/cilium.yaml
```
etcd is listed as 127.0.0.1:2379 there. I aint sure what should be put there.

**Comment by tgraf** [comment]
@amit-handa We'll make this a priority. We have recently switched over to using kubeadm for internal testing. We'll craft a guide.

**Comment by drpaneas** [comment]
Any updates on that?

**Comment by nebril** [comment]
@drpaneas we made a PR for kubeadm docs here: https://github.com/kubernetes/website/pull/9625 , but since we are adding easier etcd deployment for 1.2 we will probably write an easier guide targeting Cilium 1.2. Feel free to reach out to us on [Slack](https://cilium.slack.com/) if you have any questions!

**Comment by tgraf** [comment]
Scott Lowe has published a blog post which includes instructions on how to setup Cilium with kubeadm.
https://blog.scottlowe.org/2018/09/06/kubernetes-cilium-containerd-using-kubeadm/

**Comment by adamelliotfields** [comment]
Stumbled upon this while my pods were in CrashLoopBackOff when attempting to reinstall Cilium without ETCD (everything is back up now).

I did read the blog post, but I'm running Docker 18.06 without `containerd` or `cri-o`.

Here's how I got it to work on Debian Stretch with Kubeadm.

First, make sure your firewall allows traffic to port 2379 on your master node (which should be the same IP address that ETCD is advertising). I'm specifically referring to your cloud provider firewall, not IP Tables.

Create the `cilium-etcd-secrets` Secret (note that sudo was required):

```bash
sudo kubectl create secret generic cilium-etcd-secrets \
-n kube-system \
--kubeconfig=/home/<USER>/.kube/config \
--from-file=/etc/kubernetes/pki/etcd/ca.crt \
--from-file=/etc/kubernetes/pki/etcd/server.key \
--from-file=/etc/kubernetes/pki/etcd/server.crt
```

Download the Cilium manifest:

```bash
wget https://raw.githubusercontent.com/cilium/cilium/v1.4/examples/kubernetes/1.13/cilium-external-etcd.yaml
```

Get the ETCD advertise URL (`--advertise-client-urls`):

```bash
kubectl get pod etcd-kubernetes -o=jsonpath='{.spec.containers[0].command}'
```

Edit the ConfigMap in the manifest (leave everything before/after `...`):

```yaml
...
data:
  etcd-config: |-
    ---
    endpoints:
      - https://<ETCD_ADVERTISE_URL>:2379
    ca-file: '/var/lib/etcd-secrets/ca.crt'
    key-file: '/var/lib/etcd-secrets/server.key'
    cert-file: '/var/lib/etcd-secrets/server.crt'
...
```

Deploy Cilium:

```bash
kubectl apply -f ./cilium-external-etcd.yaml
```

Notes:
  1. I had to use the public IP for my master node - private network IP didn't work.
  2. I had to explicitly use the public IP, not `kubernetes.default.svc`.

**Comment by drpaneas** [comment]
https://github.com/cilium/cilium/pull/4826 has been merged and released with Cilium 1.2 helping with the deployment of ETCD, however I still don't see any official deployment guide for kubeadm apart from random blog posts. What is the status on this?

**Comment by tgraf** [comment]
@drpaneas The installation guide section links to the following external guide that has been written by an external user:
https://blog.scottlowe.org/2018/09/06/kubernetes-cilium-containerd-using-kubeadm/

Does that work for you?

**Comment by vadorovsky** [comment]
@drpaneas cilium-etcd-operator Deployment is included in example yaml files[0], so you don't really need any additional steps. Everything happens automatically when you do `kubectl apply -f cilium-crio.yaml` and from my experience it's the only thing you have to do after running kubeadm - I'm always doing that on top of Kubic.

[0] https://github.com/cilium/cilium/blob/master/examples/kubernetes/1.13/cilium-crio.yaml#L716-L780

**Comment by vadorovsky** [comment]
@r0ckarong and me will take care of writing the guide

**Comment by vadorovsky** [comment]
^ Disregard my previous comment, please.

There is a documentation for Cilium+kubeadm already, here:
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

If there are any concerns or things which need to be described better, I would suggest to edit the upstream k8s docs.

To make things easier for people who rely mainly on Cilium's documentation, maybe we should just provide a link to the k8s website? I will make a PR.
