### ISSUE TITLE
alignchecker reports failure when compiled with Go 1.11.4

### ISSUE THREAD

**Issue by brb** [cilium/cilium#6559]
Trying to compile cilium (master) with Go 1.11.4 fails:

```
different structure types for CGO and GO: alignchecker._Ctype_struct_endpoint_info != lxcmap.EndpointInfo
panic: C struct field "flags" (8) has different size than GoStruct field "Flags" (4)
```

Indeed, the offsets are different (no padding after `flags`):

```
type EndpointInfo struct { 
	IfIndex uint32
	Unused  uint16
	LxcID   uint16
	Flags   uint32
	// go alignment
	_       uint32
	MAC     MAC
	NodeMAC MAC
	Pad     [4]uint32
}
```

vs

```
type _Ctype_struct_endpoint_info struct {
	ifindex		_Ctype_uint32_t
	unused		_Ctype_uint16_t
	lxc_id		_Ctype_uint16_t
	flags		_Ctype_uint32_t
	mac		_Ctype_mac_t
	node_mac	_Ctype_mac_t
	pad		[4]_Ctype_uint32_t
}
```

Seems that we got bit by https://go-review.googlesource.com/c/go/+/151778/.

**Comment by aanm** [comment]
@brb so once we upgrade to go 1.11.4 we need to remove the go alignment in the endpoint info?

**Comment by joestringer** [comment]
Even more weirdly, once you resolve this issue with `struct endpoint_info`, the next complaint has a uint8_t padded out to 16 bits:

```
different structure types for CGO and GO: alignchecker._Ctype_struct_metrics_key != metricsmap.Key                                                                                      
panic: C struct field "reason" (2) has different size than GoStruct field "Reason" (1)

goroutine 1 [running]:
github.com/cilium/cilium/pkg/alignchecker.init.0()
        /home/joe/work/src/github.com/cilium/cilium/pkg/alignchecker/alignchecker.go:162 +0x1e1 
```

cf.:
https://github.com/cilium/cilium/blob/945ad33d4e2d01b29046ffc204d8de35950a16a4/pkg/maps/metricsmap/metricsmap.go#L66-L72

https://github.com/cilium/cilium/blob/945ad33d4e2d01b29046ffc204d8de35950a16a4/bpf/lib/common.h#L199-L204

With version compiled from the tree via LLVM/Clang:
```
$ pahole bpf/bpf_lxc.o | grep -A 9 metrics_key
struct metrics_key {
        uint8_t                    reason;               /*     0     1 */
        uint8_t                    dir:2;                /*     1: 6  1 */
        uint8_t                    pad:6;                /*     1: 0  1 */
        uint16_t                   reserved[0];          /*     2     0 */

        /* size: 8, cachelines: 1, members: 4 */
        /* padding: 6 */
        /* last cacheline: 8 bytes */
};
```

My Go version:
```
$ snap list go
Name  Version  Rev   Tracking  Publisher  Notes
go    1.11.4   3095  1.11      mwhudson   classic
$ go version
go version go1.11.4 linux/amd64
```

**Comment by brb** [comment]
It's because the `dir` field is being eliminated. So, when `alignchecker` checks the offset of `reserved` (`cStruct.Field(i = 1)`), it compares against the offset of `Dir` (`goStruct.Field(i = 1)`):

https://github.com/cilium/cilium/blob/945ad33d4e2d01b29046ffc204d8de35950a16a4/pkg/alignchecker/alignchecker.go#L53-L62 

```
// go 1.11.4:
type _Ctype_struct_metrics_key struct {
	reason		_Ctype_uint8_t
	reserved	[3]_Ctype_uint16_t
}

// go 1.11.3
type _Ctype_struct_metrics_key struct {
	reason		_Ctype_uint8_t
	_		[1]byte
	reserved	[3]_Ctype_uint16_t
}
```

Regarding the eliminated field, we should file a bug report for Golang (update: filled the issue https://github.com/golang/go/issues/29611).

**Comment by brb** [comment]
I think it's a false alert - we do not use structs generated by cgo, so we shouldn't compare against them in `alignchecker` and do assumptions on their underlying representation. 

Instead, we could create a dummy BPF object which includes all struct definitions, call `pahole` for it and compare the offsets in Go against corresponding Go struct field offsets.
