### ISSUE TITLE
Ginkgo tests may hang when a timeout is reached

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#6593]
Using local annotation, I found that when the Cilium endpoints fail to become ready, the waitgroup never becomes ready:

https://github.com/cilium/cilium/blob/945ad33d4e2d01b29046ffc204d8de35950a16a4/test/helpers/kubectl.go#L995-L1048

Some part of this appears to be that the context is exceeded, then `kub.CiliumEndpointsList()` gets blocked here: 

https://github.com/cilium/cilium/blob/945ad33d4e2d01b29046ffc204d8de35950a16a4/test/helpers/ssh_command.go#L260-L286

Basically the `runCommand()` call doesn't start the process (because the context is already exceeded), and returns an error, then it blocks on the waitgroup. The other goroutine waits for the process to finish, but it was never started, so blocks forever.

I have a commit here to fix the above issue: https://github.com/joestringer/cilium/commit/4be7fc978528d84a419d7d8b757069fe4dcd379c

Seems like there's still another hang waiting in the wings, so even once this is fixed the underlying behaviour is similar.

One way to test is to apply the following diff on top of PR #6357 and focus the upgrade test:

```
diff --git a/test/k8sT/manifests/cilium-cm-patch.yaml b/test/k8sT/manifests/cilium-cm-patch.yaml
index fad12ac11d44..5eda44d6e37b 100644
--- a/test/k8sT/manifests/cilium-cm-patch.yaml
+++ b/test/k8sT/manifests/cilium-cm-patch.yaml
@@ -23,4 +23,3 @@ data:

   enable-ipv4: "true"
   enable-ipv6: "true"
-  preallocate-bpf-maps: "true"
```

**Comment by eloycoto** [comment]
@joestringer made a PR with that commit and merge it, makes total sense.
