### ISSUE TITLE
Daemonset with resource request can sometimes not be recreated

### ISSUE THREAD

**Issue by Globegitter** [cilium/cilium#6603]
## Bug report

**General Information**

- Cilium version (run `cilium version`): 1.2.5 & 1.3.2
- Kernel version (run `uname -a`) 4.14.88
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) k8s 1.11.6
- Link to relevant artifacts (policies, deployments scripts, ...) using the default k8s 1.11 daemonset just with following section added:
```
          resources:
            requests:
              cpu: "250m"
              memory: "300Mi"
```
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**

1. Fill a node up with other deployments that have resource requests set until the node is at full capacity
2. Reroll the daemonset / restart the pod on the node at full capacity
3. Note how the pod does not get deployed
4. when checking `kubectl -n kube-system describe daemonset cilium` see the following warning:

```
Warning  FailedPlacement  3m19s (x380 over 4h17m)  daemonset-controller  failed to place pod on "ip-xxxl-1.compute.internal": Node didn't have enough resource: cpu, requested: 250, used: 1970, capacity: 2000
```

**Comment by aanm** [comment]
@Globegitter I've tried on my machine and I could replicate what you were seeing. I was able to get it to working, here are the steps:

1. Verify if you have `system-node-critical` priority class
```
$ kubectl get pc system-node-critical
NAME                   VALUE        GLOBAL-DEFAULT   AGE
system-node-critical   2000001000   false            25h
```

2. Verify if Cilium pod has that priority value and priority class name set set:
```
$ kubectl get pod -n kube-system cilium-5q5wn  -o yaml | grep priority
  priority: 2000001000
  priorityClassName: system-node-critical
```

3. Check if you kube-apiserver is running with the Priority Admission Controller:
```
/usr/bin/kube-apiserver --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeClaimResize,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority ....
```

I was testing against k8s 1.13.0 and on my environment I didn't specify the "Priority" field in the `enable-admission-plugins` flag, which enables the Priority Admission Controller.

Let me know if that helps!

**Comment by tgraf** [comment]
@aanm Very good information. I'll add this to the docs.

**Comment by Globegitter** [comment]
@aanm thanks for looking into this and it still is not working on our cluster. Maybe it is a difference between k8s 1.11.6 and 1.13.0 - the feature is still officially in beta. But here our output:

1.
```
kubectl get pc system-node-critical
NAME                   CREATED AT
system-node-critical   2019-01-10T10:54:08Z
```

2.
```
kubectl get pod -n kube-system cilium-4xnjr -o yaml | grep priority
  priority: 2000001000
  priorityClassName: system-node-critical
```

3.
```
/usr/local/bin/kube-apiserver --enable-admission-plugins=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,NodeRestriction,ResourceQuota,Priority ...
```

**Comment by aanm** [comment]
@Globegitter I could replicate what you are seeing with k8s 1.11.6. However, one of the k8s developers have informed me in k8s 1.13.0 they finally switch to having the scheduler bind daemon set pods, rather than the DS controller doing it.

```
  Warning  FailedPlacement  1m (x9 over 1m)  daemonset-controller  failed to place pod on "k8s1": Node didn't have enough resource: cpu, requested: 500, used: 1850, capacity: 2000
```

Which might explain what you are seeing

**Comment by Globegitter** [comment]
@aanm Thanks for figuring that out - so then I suppose this is resolved. I just wonder if it makes sense to add documentation for that?

**Comment by aanm** [comment]
@tgraf did this make it to the docs?

**Comment by tgraf** [comment]
This now works out of the box with common Kubernetes versions so closing this.
