### ISSUE TITLE
Build istio-proxy, istio-pilot images for v1.0.3, v1.0.4, v1.0.5, v1.1.0 of Istio for integration with CIlium

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6615]
The cilium istio-proxy image is only built for up until v1.0.2 of Istio. Build proxy versions using all images, and manually run the GSG against each version to ensure that no breakage occurs.

- [ ] v1.0.3
- [ ] v1.0.4
- [ ] v1.0.5
- [ ] v1.0.6
- [ ] v1.1.10

**Comment by joestringer** [comment]
@ianvernon Do we need to support anything other than the latest version?

**Comment by ianvernon** [comment]
@joestringer I'm not sure. I figure we should catch up with what we've missed since v1.0.2 and then work on being current with the latest version in the future for completeness's sake.

**Comment by ianvernon** [comment]
We have images supporting the latest versions (v1.2.2 as of this comment), closing this.
