### ISSUE TITLE
Check for Kernel BPF feature rather than hardcode a specific version

### ISSUE THREAD

**Issue by mvazquezc** [cilium/cilium#6630]
## Proposal / RFE

In the current Cilium daemon, the required Kernel version [is hardcoded](https://github.com/cilium/cilium/blob/master/daemon/daemon_main.go#L74-L78). 

That causes startup errors when running K8s/OCP/OKD on operating systems RHEL based.

For example, on RHEL 7.6 the kernel `3.10.0-940.el7.x86_64` [has BPF support](https://www.redhat.com/en/blog/introduction-ebpf-red-hat-enterprise-linux-7), so Cilium should work fine.

My proposal here is instead of hardcode the required Kernel versions, check if the running Kernel has all the required bits for Cilium to work.

I'm not a Golang expert, but I'm willing to help if someone could provide guidance.

Thanks in advance,

**Comment by borkmann** [comment]
> ## Proposal / RFE
> In the current Cilium daemon, the required Kernel version [is hardcoded](https://github.com/cilium/cilium/blob/master/daemon/daemon_main.go#L74-L78).
> 
> That causes startup errors when running K8s/OCP/OKD on operating systems RHEL based.
> 
> For example, on RHEL 7.6 the kernel `3.10.0-940.el7.x86_64` [has BPF support](https://www.redhat.com/en/blog/introduction-ebpf-red-hat-enterprise-linux-7), so Cilium should work fine.
> 
> My proposal here is instead of hardcode the required Kernel versions, check if the running Kernel has all the required bits for Cilium to work.

Definitely agree on the latter. We have various tests under `bpf/probes/`, so they could be extended as one option, for example.

With regards to RHEL, my understanding is that RHEL7.6 only has tracing enabled for eBPF at this stage unless there is something new I'm not yet aware of. RHEL8 should have the full feature set, though.

Can you elaborate on your finding with "Cilium should work fine"?

**Comment by mvazquezc** [comment]
> Can you elaborate on your finding with "Cilium should work fine"?

I've been testing Cilium on RHEL based O.S with OKD and K8s and it works when using Kernel >4.8.0.

Providing that the Kernel has all the required features backported it should work. I've been reading about BPF and eBPF, I thought they were the same, my bad. My confusion came from the [Cilium project readme](https://github.com/cilium/cilium#what-is-ebpf-and-xdp) where eBPF/BPF are referenced without distinction.

**Comment by borkmann** [comment]
> > Can you elaborate on your finding with "Cilium should work fine"?
> 
> I've been testing Cilium on RHEL based O.S with OKD and K8s and it works when using Kernel >4.8.0.

Nice! Are you using a custom kernel or a RHEL7.6 provided one? If the latter, is it the arm64 alt kernel that RHEL ships or something else as above you mentioned earlier `3.10.0-940.el7.x86_64`?

Cilium should be running for RHEL8 though, presumably that's what you tested with above `kernel >4.8.0`?

> Providing that the Kernel has all the required features backported it should work. I've been reading about BPF and eBPF, I thought they were the same, my bad. My confusion came from the [Cilium project readme](https://github.com/cilium/cilium#what-is-ebpf-and-xdp) where eBPF/BPF are referenced without distinction.

Yeah, it should work with only a few backports for 7.6 kernel that afaik are still needed.

In kernel-land we just use the term BPF so BPF usually means eBPF implicitly.  (The reference guide mentions it right at the beginning that we use BPF terminology and mean eBPF by that.)

**Comment by mvazquezc** [comment]
> Nice! Are you using a custom kernel or a RHEL7.6 provided one? If the latter, is it the arm64 alt kernel that RHEL ships or something else as above you mentioned earlier `3.10.0-940.el7.x86_64`?

I've used 4.X from elrepo, this one to be more specific: `4.20.1-1.el7.elrepo.x86_64`

> Cilium should be running for RHEL8 though, presumably that's what you tested with above `kernel >4.8.0`?

I haven't tested this on RHEL8 yet.
 
> Yeah, it should work with only a few backports for 7.6 kernel that afaik are still needed.

Do you have some links where this work is being tracked?

> In kernel-land we just use the term BPF so BPF usually means eBPF implicitly. (The reference guide mentions it right at the beginning that we use BPF terminology and mean eBPF by that.)

Thanks for the clarification!
