### ISSUE TITLE
bump minimum supported K8s version for Cilium

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6637]
v1.13 of K8s has been released, and is currently at [v1.13.2](https://github.com/kubernetes/kubernetes/releases/tag/v1.13.2) . We still run against K8s 1.8 in the CI. We should consider bumping to v1.9 or even 1.10 for supported K8s versions in Cilium v1.4 so we can consume new K8s behavior (e.g. CRD versioning) in the future and not have to deal with non-maintained K8s versions with new Cilium releases.

**Comment by aanm** [comment]
@ianvernon what is preventing us from using CRD versioning and support k8s 1.8 at the same time?

**Comment by ianvernon** [comment]
@aanm does k8s 1.8 support CRD versioning? I was under the impression that it didn't.

I guess this is also a good time to ask what our policy is for supporting specific K8s versions, specifically those that are deprecated?

**Comment by aanm** [comment]
>@aanm does k8s 1.8 support CRD versioning? I was under the impression that it didn't.

It doesn't but I still don't understand what's the relation between that and removing support for v1.8. There's no harm in running k8s 1.8 in our CI, we only need to check this once k8s libraries don't have support for k8s 1.8 structures that we use in our code.
