### ISSUE TITLE
Stale local kvstore lock prevents successful identity allocation

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6667]
Observed with 1.2.6, later versions likely affected as well.

Cilium does distributed locking via etcd. For this purpose we first acquire a local lock indexed by the etcd key path. This is needed because etcd locks only protect against other clients and not from mutual access from the same etcd client. We then acquire the lock in etcd itself. We store locally that we are currently holding the etcd lock. When the etcd lock is unlocked, this local state is removed.

For some reason, it’s unclear why, the local state was left behind and the local unlocking never took place. etcd was identified to have crashed several times based on logs which could have caused the etcd client returning something unexpected.

When unable to acquire the local lock, we ignore this state and ask etcd directly. Unfortunately the original request requiring the etcd lock, in this case identity allocation, has typically already timed out.  The current code never corrects the local state until the cilium pod is restarted.

It is still unclear why exactly the unlock never happened. An initial code audit suggests that only a panic with later recovery could cause this. No indication was found in the logs though.

In parallel to the continued investigation how we can potentially get into this state, the local state must be corrected when it is bypassed for the first time. The etcd lock will time out and will become available again eventually even if the unlocking is missed whereas the current Cilium code never recovers unless Cilium is restarted.

**Comment by ianvernon** [comment]
Does this need backport to v1.3 as well @tgraf ?

**Comment by tgraf** [comment]
@ianvernon Yes, thanks for catching.
