### ISSUE TITLE
* `path` for shell provisioner does not exist on the host system: G:/cilium/contrib/vagrant/cilium-master.sh

### ISSUE THREAD

**Issue by mevam** [cilium/cilium#667]
{ cilium } master » ./contrib/vagrant/start.sh                     /cygdrive/g/Development/cilium
Bringing machine 'cilium-master' up with 'virtualbox' provider...
Bringing machine 'cilium-node-2' up with 'virtualbox' provider...
Bringing machine 'cilium-node-3' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* `path` for shell provisioner does not exist on the host system: G:/cygdrive/g/Development/cilium/contrib/vagrant/cilium-master.sh

**Comment by tgraf** [comment]
You seem to be passing a path into the `./contrib/vagrant/start.sh` script for some reason but it should still work.

You can also try the getting started vagrant box by doing:
```
$ cd examples/getting-started
$ vagrant up
```

That box is a lot simpler and uses a simple Vagrantfile
