### ISSUE TITLE
No pod connectivity with kops 1.11 / cilium v1.4 / tunnel: disabled

### ISSUE THREAD

**Issue by arthur-c** [cilium/cilium#6711]
I'm not able to get any connectivity inside pods when I add the option `tunnel : disabled` to kops (It's ok without the option). Node connectivity seems fine : the cluster is ready and I'm able to pull external docker images.

This Cilium logs tells me it should be a permission misconfiguration from kops:

```
level=error msg="Cannot update CEP" containerID=2c0d33d777 controller="sync-to-k8s-ciliumendpoint (1791)" datapathPolicyRevision=5 desiredPolicyRevision=5 endpointID=1791 error="ciliumendpoints.cilium.io \"net-utils-bf6cc649b-qfqgr\" is forbidden: User \"system:serviceaccount:kube-system:cilium\" cannot update ciliumendpoints.cilium.io/status in the namespace \"default\"" identity=18138 ipv4= ipv6= k8sPodName=default/net-utils-bf6cc649b-qfqgr subsys=endpointsynchronizer
level=error msg="Unable to delete route" error="no such process" interface=cilium_host local=100.96.5.1 nexthop=100.96.5.1 prefix="{100.96.0.0 ffffff00}" subsys=route
level=error msg="Unable to delete route" error="no such process" interface=cilium_host local="fc00::10ca:1" nexthop="f00d::6460:500:0:1" prefix="{f00d::6460:0:0:0 ffffffffffffffffffffffffffff0000}" subsys=route
````

```
# kops 1.11
  networking:
    cilium:
      version: v1.4
      tunnel: disabled
```

```
%  kubectl get cep --all-namespaces
NAMESPACE     NAME                                   ENDPOINT ID   IDENTITY ID   POLICY ENFORCEMENT   ENDPOINT STATE   IPV4   IPV6
default       net-utils-bf6cc649b-qfqgr
default       ubuntu-65c557cd9f-96sl2
kube-system   kube-dns-6b4f4b544c-5xfl7
kube-system   kube-dns-6b4f4b544c-zkfn7
kube-system   kube-dns-autoscaler-6b658bd4d5-p5qhk
```

the sysdump: 
[cilium-sysdump-20190122-074728.zip](https://github.com/cilium/cilium/files/2781625/cilium-sysdump-20190122-074728.zip)

**Comment by aanm** [comment]
with tunnel disabled, AWS will drop all packets coming from the VMs because their source IP belong to the pod CIDRs. AWS is not aware of that CIDR as it only knows the IPs allocated to the VMs and so, will drop all packets with that "unknown" source IP.

you can disable this behavior in AWS console https://docs.aws.amazon.com/vpc/latest/userguide/VPC_NAT_Instance.html#EIP_Disable_SrcDestCheck

**Comment by arthur-c** [comment]
Thanks for noticing, I forgot about this as I'm used to Calico and Kops disables the source check when choosing this networking.

So I disabled the AWS source check but no success.

But his guide solved my problems (I used 1.11 instead 1.10):
http://docs.cilium.io/en/stable/kubernetes/install/kops/?highlight=kops#upgrading-cilium

I reenabled the source checking and I still have connectivity.

**Comment by aanm** [comment]
@arthur-c I'll re-open the issue so we don't forget it when we update kops for k8s 1.4

**Comment by aanm** [comment]
note to self: also look at etcd-manager integration

**Comment by arthur-c** [comment]
You might be interested by these issues when working on the etcd-manager part:
https://github.com/kubernetes/kops/issues/5675
https://github.com/kopeio/etcd-manager/issues/126
