### ISSUE TITLE
CI: runtime.RuntimeFQDNPolicies CNAME follow

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6727]
```
/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:408
Container "app1" cannot access to "http://level1CNAME.cilium.test" when should work
Expected command: docker exec -i  app1 curl -s -D /dev/stderr --fail --connect-timeout 3 --max-time 8 http://level1CNAME.cilium.test -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.006274()', Connect: '0.000000',Transfer '0.000000', total '3.001439'
Stderr:
 	 

/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/runtime/fqdn.go:677
```
[3ebefcdc_RuntimeFQDNPolicies_CNAME_follow.zip](https://github.com/cilium/cilium/files/2787841/3ebefcdc_RuntimeFQDNPolicies_CNAME_follow.zip)

**Comment by tgraf** [comment]
Discussed with @eloycoto, will increase the timeout until policy calculation is more optimized

**Comment by aanm** [comment]
Hit again in https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10578/testReport/junit/(root)/runtime/RuntimeFQDNPolicies_CNAME_follow/

[b8aa3fd9_RuntimeFQDNPolicies_CNAME_follow.zip](https://github.com/cilium/cilium/files/2941357/b8aa3fd9_RuntimeFQDNPolicies_CNAME_follow.zip)

**Comment by ianvernon** [comment]
@eloycoto is this fixed by the policy queueing / race condition fixes that have gone in recently?

**Comment by ianvernon** [comment]
Closing, haven't seen this for a long time.
