### ISSUE TITLE
CI:  K8sHealthTest checks cilium-health status between nodes: Expected string not to be empty

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6728]
```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
Expected
    <string>: 
not to be empty
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.10-gopath/src/github.com/cilium/cilium/test/k8sT/Health.go:108
```

**Comment by tgraf** [comment]
[6856953c_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/2788197/6856953c_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by tgraf** [comment]
Seen again in https://github.com/cilium/cilium/pull/8513

**Comment by tgraf** [comment]
[48a2eb71_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/3377983/48a2eb71_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by jrajahalme** [comment]
Seen here: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13806/testReport/junit/Suite-k8s-1/10/K8sHealthTest_checks_cilium_health_status_between_nodes/

**Comment by raybejjani** [comment]
https://jenkins.cilium.io/view/Cilium-v1.6/job/cilium-v1.6-standard/89/

**Comment by tgraf** [comment]
We are not seeing this anymore.

**Comment by joestringer** [comment]
Seen again in https://github.com/cilium/cilium/pull/11625 .

**Comment by aanm** [comment]
Seen again in https://github.com/cilium/cilium/pull/11368

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/2048/

[1b063a65_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/4770217/1b063a65_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by christarazi** [comment]
Seen again in https://github.com/cilium/cilium/pull/12536

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3312/

**Comment by joestringer** [comment]
Hit again:

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.19/17/

[e887b1d1_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/5419577/e887b1d1_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by christarazi** [comment]
Hit again in https://github.com/cilium/cilium/pull/14539:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3863
[859f42f6_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/5797385/859f42f6_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by pchaigno** [comment]
Hit again at https://github.com/cilium/cilium/pull/15597 with https://jenkins.cilium.io/job/Cilium-PR-K8s-1.17-kernel-4.9/122/testReport/junit/Suite-k8s-1/17/K8sHealthTest_checks_cilium_health_status_between_nodes/.
[6c162469_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/6287203/6c162469_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by tklauser** [comment]
Hit again in #16655 (v1.8 backport): https://jenkins.cilium.io/job/Cilium-PR-K8s-1.11-net-next/1652 

[12b9dec0_K8sHealthTest_checks_cilium-health_status_between_nodes.zip](https://github.com/cilium/cilium/files/6726409/12b9dec0_K8sHealthTest_checks_cilium-health_status_between_nodes.zip)

**Comment by pchaigno** [comment]
This happens because the JSON response doesn't contain `http` fields:
```
cmd: "kubectl exec -n kube-system cilium-hqkdz -- cilium-health status -o json" exitCode: 0 duration: 1.506059687s stdout:
{
  "local": {
    "name": "k8s1"
  },
  "nodes": [
    {
      "endpoint": {
        "icmp": {
          "latency": 749009
        },
        "ip": "10.10.0.35"
      },
```
(to compare to a previous response: <details><summary>Click to show)</summary>

```
cmd: "kubectl exec -n kube-system cilium-hqkdz -- cilium-health status -o json" exitCode: 0 duration: 158.002268ms stdout:
{
  "local": {
    "name": "k8s1"
  },
  "nodes": [
    {
      "endpoint": {
        "http": {
          "latency": 287049
        },
        "icmp": {
          "latency": 864000
        },
        "ip": "10.10.0.35"
      },
```
</details>

Is it expected for the `http` field to be missing when that probe failed?

**Comment by joestringer** [comment]
> Is it expected for the http field to be missing when that probe failed?

No, typically I'd expect it to have an http section with an error describing the failure (typically some sort of timeout message).
