### ISSUE TITLE
Support cilium endpoint get { pod-name | docker-container-name | ... }

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#675]
Simplify the process of identifying endpoints by supporting to specify
- pod name
- docker container name
- labels

**Comment by ianvernon** [comment]
I've added support for Docker container name, and rudimentary support for labels in a private branch. 
Question re: labels.
Say there are multiple endpoints with label "env=prod"; should I return all such endpoints? Or do we only want to return an endpoint if the set of labels provided exactly matches the endpoint's set of labels, and not a subset of the labels?

**Comment by tgraf** [comment]
> Say there are multiple endpoints with label "env=prod"; should I return all such endpoints? Or do we only want to return an endpoint if the set of labels provided exactly matches the endpoint's set of labels, and not a subset of the labels?

We want to return all endpoints which include all of the specified labels. The endpoint may have additional labels.
