### ISSUE TITLE
Update documentation for cilium-etcd-operator

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#6783]
These instructions are now out-of-date with respect to etcd, as it suggests downloading the YAML with cilium-etcd-operator then requires the user to go through etcd setup instructions in addition:

http://docs.cilium.io/en/latest/kubernetes/install/standard/

**Comment by tgraf** [comment]
I'm already working on this.

**Comment by joestringer** [comment]
There may be other docs that need updates too, for instance the "quickstart" option tells the user to specify the etcd address, which is not necessary.
