### ISSUE TITLE
Invalid message formatting when CNI plugin cannot connect to agent

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6801]
`
  Warning  FailedCreatePodSandBox  20s   kubelet, ip-192-168-4-64.us-west-2.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "7cf45c4df81512373b370ffe526ce61fad423a1c801f6d0136f389314a4fac1c" network for pod "cilium-etcd-zj5wtgvx9d": NetworkPlugin cni failed to set up pod "cilium-etcd-zj5wtgvx9d_kube-system" network: unable to connect to Cilium daemon: Failed to create cilium agent client after 30.000000 seconds timeout: %!!(MISSING)s(<nil>), failed to clean up sandbox container "7cf45c4df81512373b370ffe526ce61fad423a1c801f6d0136f389314a4fac1c" network for pod "cilium-etcd-zj5wtgvx9d": NetworkPlugin cni failed to teardown pod "cilium-etcd-zj5wtgvx9d_kube-system" network: unable to connect to Cilium daemon: Failed to create cilium agent client after 30.000000 seconds timeout: %!!(MISSING)s(<nil>)]
`

**Comment by aanm** [comment]
@tgraf when that happens it means the cilium-cni client could not connect to cilium-agent within 30 seconds.

**Comment by tgraf** [comment]
The message is clear, it's the formatting that is off.
