### ISSUE TITLE
Accept error: accept unix /var/run/cilium/cilium.sock: accept4: too many open files

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6803]
```
Jan 27 21:15:12 k8s1 cilium-agent[12422]: 2019/01/27 21:15:12 http: Accept error: accept unix /var/run/cilium/cilium.sock: accept4: too many open files; retrying in 1s
```

**Comment by aanm** [comment]
likely related with https://github.com/cilium/cilium/commit/d48af6ab5c286fd91b751eed90a7d1b715a55231#diff-e747ac6894495747def86f189ee986fc

**Comment by jrfastab** [comment]
ConfigMap is not properly released on endpoint deletion leaking fds resulting in fd exhaustion at some point. 
#6890
