### ISSUE TITLE
Validate sonobuoy is passing before 1.4.0

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6830]
A user has reported a failure in running sonobuoy [0] with 1.4.0-rc4. Validate that the tests are passing.

[0] https://github.com/heptio/sonobuoy

**Comment by nebril** [comment]
Tried running `sonobuoy` cli on GKE cluster created with cilium/gke script, all e2e tests are passing.

Running the browser-based scanner now to make sure that I didn't miss anything from the results.

**Comment by nebril** [comment]
Running on 1.11 showed a bug in k8s e2e tests, fix here: https://github.com/kubernetes/kubernetes/pull/73476

Running on 1.13 didn't show any test failures

Closing for now.

**Comment by marc-barry** [comment]
Hey @nebril and @tgraf. I ran `Sonobuoy` against our `1.13.2` cluster build which has release [v1.4.0-rc5](https://github.com/cilium/cilium/releases/tag/v1.4.0-rc5) and ended up with the following failures:
```
Summarizing 10 Failures:

[Fail] [sig-cli] Kubectl client [k8s.io] Update Demo [It] should create and stop a replication controller  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/rc_util.go:292

[Fail] [sig-apps] ReplicaSet [It] should serve a basic image on each replica with a public image  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/replica_set.go:170

[Fail] [sig-cli] Kubectl client [k8s.io] Update Demo [It] should do a rolling update of a replication controller  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/rc_util.go:292

[Fail] [sig-cli] Kubectl client [k8s.io] Update Demo [It] should scale a replication controller  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/rc_util.go:292

[Fail] [sig-apps] ReplicationController [It] should serve a basic image on each replica with a public image  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/rc.go:164

[Fail] [sig-network] Proxy version v1 [It] should proxy through a service and a pod  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:255

[Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:526

[Fail] [k8s.io] [sig-node] PreStop [It] should call prestop when killing a pod  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pre_stop.go:158

[Fail] [sig-cli] Kubectl client [k8s.io] Guestbook application [It] should create and stop a working application  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:1996

[Fail] [sig-network] DNS [It] should provide DNS for the cluster  [Conformance]
/workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:526

Ran 200 of 1946 Specs in 9507.477 seconds
FAIL! -- 190 Passed | 10 Failed | 0 Pending | 1746 Skipped --- FAIL: TestE2E (9507.89s)
FAIL

Ginkgo ran 1 suite in 2h38m30.106175741s
Test Suite Failed
```
I ran the test with [`v0.13.0`](https://github.com/heptio/sonobuoy/releases/tag/v0.13.0).

**Comment by tgraf** [comment]
@marc-barry How did you set up the cluster? I think we need to reproduce this in an environment that matches yours.

**Comment by marc-barry** [comment]
> @marc-barry How did you set up the cluster? I think we need to reproduce this in an environment that matches yours.

I've provided @nebril with access to the cluster.

**Comment by tgraf** [comment]
From Nan Zhong on Slack:

> I had some time this weekend to look into this issue as well. I think I've found the cause of the failing tests, however, I also feel like I may be missing some key part of the cilium installation process. The issue appears to be k8s api proxy access to the pods that are part of the conformance tests that are failing. The master node we run after switching over to our cilium image does not have a route to the cluster ips. We previously ran flannel on the master node as well to allow this.

> All the documentation I've read so far only suggest running cilium on the worker nodes via a daemon set which is what we are doing, but how is the master node supposed to have access to the cluster ips? The master node we run isn't really a "node" in the cluster, rather it's just a vm that runs a number of the control plane components for the cluster; it does not appear as a k8s node, and workloads cannot be scheduled there.

**Comment by nanzhong** [comment]
Yup, thanks for cross posting here @tgraf!

I've verified that conformance passes for 1.11.7, 1.12.5, and 1.13.2 running cilium 1.4.0-rc5. The solution was indeed to run cilium on the master node so that it can proxy to the cluster ips.

Good to close this issue, and like you suggested, some documentation for this would be great!

**Comment by tgraf** [comment]
Great, thanks a lot for all the effort @marc-barry and @nanzhong
