### ISSUE TITLE
Add k8s integrations for toqfdns options

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#6870]
AFAICT there's no examples in the configmap and no environment variable binding in the daemonset, nor upgrade instructions for how to `tofqdns-enable-poller`. We should consider whether to add these.

**Comment by vadorovsky** [comment]
Shall we also expose `tofqdns-enable-poller-events` in the configmap?

**Comment by joestringer** [comment]
@mrostecki Honestly I think that the proxy-based approach to DNS is much more robust, currently I'm just trying to figure out whether it's at all reasonable to use the DNS poller approach in 1.4. The docs in https://github.com/cilium/cilium/pull/6886 suggest maybe not.

Regarding the poller events flag, the default settings will effectively follow `tofqdns-enable-poller` (ie enabled if you enable polling, disabled if you disable), so unless we get some particular user asking for this I figure we can avoid exposing configuration for that option.
