### ISSUE TITLE
Test standard installation guide

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6875]
Guide: https://docs.cilium.io/en/latest/gettingstarted/k8s-install-etcd-operator/

- [x] Write down unclear steps in the documentation
- [x] Report failures

**Comment by jrajahalme** [comment]
Validating the CodeDNS reverse lookups section was a bit unclear, as `host` tool is not available in the cilium container. Don't know if it would have been available in any other container started during the GSG.

**Comment by tgraf** [comment]
> Validating the CodeDNS reverse lookups section was a bit unclear, as `host` tool is not available in the cilium container. Don't know if it would have been available in any other container started during the GSG.

Good point. It's probably clear to advanced users but probably not to beginners.
