### ISSUE TITLE
unable to build cilium in dev VM

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#6896]
```
pkg/controller/manager.go:258: return copies lock value: controller.Manager contains github.com/cilium/cilium/pkg/lock.RWMutex
```

**Comment by joestringer** [comment]
AFAIK this fails as part of the `govet` target, invoked by `make` but not by something like `make -C daemon` so there's at least a basic workaround to unblock anyone directly blocked on this.

**Comment by joestringer** [comment]
(How this breaks the dev VM and local environments but not the CI, I'm not sure..)
