### ISSUE TITLE
Allow to use podman instead of docker

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium#6908]
Currently building and running tests in Cilium requires docker. It would be nice to support Cilium development with podman and using podman as a workload.

Action items:
- [x] Allow to override `docker` commands (i.e. `docker run`, `docker rm` etc.) in Makefile
- [ ] Allow to use `podman pod create` instead of `docker compose`
- [ ] ~Add `workloads` module for podman~
- [ ] Check if podman can be used with Cilium as a CNI plugin, if yes - document that, if no - fix what's needed

**Comment by joestringer** [comment]
@mrostecki Are there any remaining items here? I was under the impression that the workloads package was deprecated in a recent release, so it seems like we could close this issue.

**Comment by mrostecki** [comment]
@joestringer Yes, there are remaining items.

- We still have some scripts using docker-compose, I would like to check if there is a possibility to use podman instead.
- I would like to check if it's possible to use Cilium as a CNI plugin for podman and use it in similar way on local machines like you can do with Docker and libnetwork.

I will work on that this week.

**Comment by joestringer** [comment]
OK, no pressure. Just checking in on old issues to see if they're still relevant :)

**Comment by vadorovsky** [comment]
Nobody else shared an interest, so I'm closing
