### ISSUE TITLE
cilium policy delete root, does not flush CT table

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#691]
With newer kernels, where bpf probes detects and uses LRU maps, deleting the policy does not flush the conntrack state allowing connections to remain even after policy has been removed.

Reproduction steps below.

> cilium config Policy=enabled
> docker start client
> docker start httpd
> docker exec -ti client ping6 -c1 f00d::c0a8:102:0:f236 --debug          <- as expected ping6 fails
PING f00d::c0a8:102:0:f236 (f00d::c0a8:102:0:f236): 56 data bytes
--- f00d::c0a8:102:0:f236 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

> cilium policy import ~/go/src/github.com/cilium/cilium/examples/demo/policy.json 
> sudo cilium policy get root
{
  "name": "root",
  "rules": [
    {
      "coverage": [
        {
          "key": "id.server",
          "source": "cilium"
        }
      ],
      "allow": [
        {
          "action": "accept",
          "matchLabels": [
            {
              "key": "host",
              "source": "reserved"
            }
          ]
        },
        {
          "action": "accept",
          "matchLabels": [
            {
              "key": "id.client",
              "source": "cilium"
            }
          ]
        }
      ]
    }
  ]
}

>  docker exec -ti client ping6 -c1 f00d::c0a8:102:0:f236 --debug            <- ping works with valid policy
PING f00d::c0a8:102:0:f236 (f00d::c0a8:102:0:f236): 56 data bytes
64 bytes from httpd.cilium: icmp_seq=0 ttl=63 time=0.135 ms
--- f00d::c0a8:102:0:f236 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.135/0.135/0.135/0.000 ms

> cilium policy delete root
> docker exec -ti client ping6 -c1 f00d::c0a8:102:0:f236 --debug            <- ping still works :(
PING f00d::c0a8:102:0:f236 (f00d::c0a8:102:0:f236): 56 data bytes
64 bytes from httpd.cilium: icmp_seq=0 ttl=63 time=0.105 ms
--- f00d::c0a8:102:0:f236 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.105/0.105/0.105/0.000 ms

**Comment by aanm** [comment]
Closing this issue since it can't be fixed due #815 where the policy is automatically set to disabled when the number of policy rules == 0. This means when all policy is removed, all endpoints will be allowed to receive any traffic.

I've open a new issue #839
