### ISSUE TITLE
Add option to apply config changes to existing endpoints after 'cilium config policy=enabled'

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#692]
Running 'cilium config policy=enabled' does not apply to existing endpoints. However, this is by design but did cause a bit of confusion on my side because I had a different expectation.

To allow changing the policy config after endpoints are created add a '--regenerate-endpoints' option to 'config policy' so that the policy is regenerated and applied to all endpoints. 

Also adding a note in 'config --list-options' would help clarify the expected behavior.

**Comment by ianvernon** [comment]
This should be done now; when running `cilium config PolicyEnforcement=enabled`, the endpoint configuration is changed accordingly. I think this can be closed. @jrfastab please confirm.

**Comment by jrfastab** [comment]
LGTM.
