### ISSUE TITLE
Track DNS Poller data like endpoint DNS data

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#6951]
and is exposed under /fqdn/cache API

We need to manage the poller as a first class entity and this requires at least two steps:
1- Store DNS poller data in a way that honours per-host limits (like in https://github.com/cilium/cilium/pull/6740). Hopefully using the same limit as endpoints is adequate.
2- Expose the DNS data from (1) under `/fqdn/cache`. This is more annoying, as that API takes /endpoint-id as the way to specialise to specific endpoints. The DELETE verb can only apply to the global URL `/fqdn/cache` so that may also pose a challenge around clearing just poller data when upgrading.

**Comment by aanm** [comment]
Not relevant anymore
