### ISSUE TITLE
CI: Allows traffic with k8s default-allow egress policy: could not resolve DNS for google.com

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6960]
## CI failure

Link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/5785/testReport/junit/k8s-1/13/K8sPolicyTest_Basic_Test_Allows_traffic_with_k8s_default_allow_egress_policy/

```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:408
Egress DNS connectivity should be allowed for pod "app2-5b49d5dd9-s7tjl"
Expected command: kubectl exec -n default app2-5b49d5dd9-s7tjl -- host www.google.com 
To succeed, but it failed:
Exitcode: 1 
Stdout:
 	 www.google.com has address 216.58.212.164
	 www.google.com has IPv6 address 2a00:1450:400e:801::2004
	 Host www.google.com not found: 2(SERVFAIL)
	 
Stderr:
 	 command terminated with exit code 1
	 

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/k8sT/Policies.go:501
```
Logs: [abc9e67a_K8sPolicyTest_Basic_Test_Allows_traffic_with_k8s_default-allow_egress_policy.zip](https://github.com/cilium/cilium/files/2837744/abc9e67a_K8sPolicyTest_Basic_Test_Allows_traffic_with_k8s_default-allow_egress_policy.zip)

**Comment by tgraf** [comment]
Couple of options:
 - Google screwed up temporarily
 - kube-dns was not able to reach the Google DNS and returned both the cached result and SERVFAIL to indicate the upstream connectivity problem.

**Comment by ianvernon** [comment]
Not observed for a month, closing.
