### ISSUE TITLE
Cilium agent fails to start with bpf file system mounted on the host

### ISSUE THREAD

**Issue by amshinde** [cilium/cilium#6966]
Followed the instructions to install the Cilium etcd operator here:
https://cilium.readthedocs.io/en/latest/gettingstarted/k8s-install-etcd-operator/

The instructions recommend mounting the bpf file system on the host.
But with this, the agent fails to start.  Logs from the cilium pod show this error message:
```
level=fatal msg="Unable to mount BPF filesystem" error="multiple mount points detected at /sys/fs/bpf" subsys=bpf
```
**General Information**

- Cilium version 
Client: 1.4.90 [d96d205](https://github.com/cilium/cilium/commit/d96d205a58fc1329b23915bfa588ebab1efeb84c) 2019-02-05T20:21:04+01:00 go version go1.11.1 linux/amd64
Daemon: 1.4.90 [d96d205](https://github.com/cilium/cilium/commit/d96d205a58fc1329b23915bfa588ebab1efeb84c) 2019-02-05T20:21:04+01:00 go version go1.11.1 linux/amd64
- Kernel version (run `uname -a`) - 4.15
- Orchestration system version in use
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"archive", BuildDate:"2019-02-03T06:32:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Seen the same behaviour with docker as well as cri-o.

**Comment by amshinde** [comment]
cc @jrfastab

**Comment by aanm** [comment]
@amshinde I saw that you have open the #6965 , are you using cri-o? If yes please use the exact version available in https://github.com/cilium/cilium/tree/master/examples/kubernetes where they are different depending on each k8s version. For example, since k8s 1.11 the cilium DaemonSet for crio does not have the volumes for bpf directories set in the k8s descriptor.

Let me know if that is the issue.

**Comment by amshinde** [comment]
@aanm Just updated the issue description with the exact version of k8s.

**Comment by vadorovsky** [comment]
Could you `kubectl exec` the Cilium pod and provide the content of `/proc/self/mountinfo`? That would be very helpful.

**Comment by aanm** [comment]
@amshinde I'm not able to reproduce this issue.

I've set up a machine with cri-o and I've installed cilium using
```
kubectl create -f https://raw.githubusercontent.com/cilium/cilium/master/examples/kubernetes/1.13/cilium-crio.yaml
```

Can you describe the steps you have performed to mount the bpf file system on the host?

Also, it would be extremely helpful if you could provide a cilium sysdump [0]

Thanks!

[0] https://cilium.readthedocs.io/en/latest/troubleshooting/#automatic-log-state-collection

**Comment by amshinde** [comment]
@aanm I tried this with k8s 1.12 as well as 1.13 with cri-o. I can no longer see this issue :)
Was able to reproduce this a couple of days back..maybe there was an update pushed to the image?
Closing this.

**Comment by amshinde** [comment]
cc @mcastelino

**Comment by manicole** [comment]
Hello, up on this issue.

I'm installing a multi-cri cluster via Kubespray :
- master, node1,  node2 using docker as container runtime
- node3 using containerd as CR
- node4 using cri-o as CR

When adding node3, I had to reinstalll cilium-operator (https://raw.githubusercontent.com/cilium/cilium/v1.6/install/kubernetes/quick-install.yaml) to make it agnostic to the used CR. Now "container-runtime" is set to "none" in cilium-config configmap.

When addind node4, I get the same error as @ToroNZ 
 ```txt
level=fatal msg="Unable to mount BPF filesystem" error="multiple mount points detected at /sys/fs/bpf" subsys=bpf
```
The thing is I do not want to set a "global.containerRuntime.integration" other than "none" as advised in http://docs.cilium.io/en/latest/kubernetes/configuration/?#crio, as you can understand.

Any clue on how to make Cilium work on my node4 ? Thanks

Versions used :
- Kubernetes 1.16
- Cilium 1.6.5
- Kubespray 2.12

**Comment by danielsand** [comment]
if you landed here searching for a current kubernetes + cri-o + cilium solution -> 
https://docs.cilium.io/en/v1.6/kubernetes/configuration/#crio
