### ISSUE TITLE
Do not log any INFO message after daemon initializes

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#6989]
It is always useful to retrieve log messages but with the new metrics introduced in v1.4 it seems redundant to log every single BPF regeneration that happens in Cilium.

This issue proposes to stop logging any message, except Warn and Fatal, after the Daemon initializes. This means there will always be Info messages in the beginning, which are always useful for users to debug initialization problems with Cilium but after that initialization they don't give any value as we provide numerous tools that should be enough.

**Comment by tgraf** [comment]
I agree with it as we continue to scale up but I'm sure there will be times where we regret it.
