### ISSUE TITLE
clustermesh issue: cluster2 rebel-base pods restart and cluster1 is never able to get to cluster2 rebel-base

### ISSUE THREAD

**Issue by bjethwan** [cilium/cilium#7059]
## Bug report
I was following the doc on setting up clustermesh using your sample rebel-base service.

cluster2 rebel-base pods restart by themselves (I couldn't find out the reason using "k logs rebel-base-595fb48c9c-5h52h --previous" as it was filled with logs for readiness/liveness probes"

And then cluster1 is never able to get to cluster2 rebel-base service pods.

I figured using "cilium service list" on a cilium pod in cluster1 that it's still holding the old cluster2 IP(s).
Please check the attached screenshots.
![cluster2 - pod restart](https://user-images.githubusercontent.com/5045325/52699124-0b727e80-2f9b-11e9-9d55-87bab8c6c29f.png)
![cluster1 still holding old ep or pod ip](https://user-images.githubusercontent.com/5045325/52699134-11685f80-2f9b-11e9-9f19-4ebcd3855fa3.png)

**General Information**

- Cilium version (run `cilium version`)
Client: 1.4.90 4f02ade 2019-02-12T16:50:21-08:00 go version go1.11.1 linux/amd64
Daemon: 1.4.90 4f02ade 2019-02-12T16:50:21-08:00 go version go1.11.1 linux/amd64

- Kernel version (run `uname -a`)
4.14.96-coreos

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
kubernetes 1.11.6 using kops with coreDNS
 
- Link to relevant artifacts (policies, deployments scripts, ...)
same as your clustermesh rebel-base example

- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**

check the screenshots

**Comment by tgraf** [comment]
@bjethwan We'll need a bit more information than what is visible in the screenshot. Please collect a system dump:
```
curl -sLO releases.cilium.io/tools/cluster-diagnosis.zip && python cluster-diagnosis.zip sysdump
```

or follow the clustermesh troubleshooting section and report where things are off:
http://docs.cilium.io/en/v1.4/gettingstarted/clustermesh/#troubleshooting

**Comment by bjethwan** [comment]
@tgraf 
I destroyed both the clusters, I use kops/aws and destroy the cluster if I am struck.
I can try reproducing it again.
Can you tell me how to make the liveness probe fail for this pod?
As deleting the rebel-base pods won't help.

**Comment by tgraf** [comment]
We'll need either a system dump or the output of the commands in the troubleshooting guide to make any progress in looking into this. It is likely that something went wrong with the cluster mesh setup in general but it's hard to say without any log files.

Cilium does not influence any liveness probes. The pod IPs are removed from the Endpoints structure as the pods get deleted. The Kubernetes apiserver is responsible to do that.

**Comment by bjethwan** [comment]
@tgraf 
I didn't do anything fancy here, just made your rebel-base example work, took a long 2hr break, and came back and found the rebel-base pods in cluster2 had restarted and the pod IPs had changed, I should have taken the logs using --previous, but I missed.  And cause the pod IPs changed for pod restart (not re-scheduler), your example had broken. So if you like you can close this till I run into another time. I will sure catch the diagnostic dump. Thanks

**Comment by tgraf** [comment]
Great, thanks.
