### ISSUE TITLE
clustermesh issue: io.cilium/global-service=true is not working for an existing service

### ISSUE THREAD

**Issue by bjethwan** [cilium/cilium#7061]
## Bug report
Here's what I did
1. I took your clustermesh/rebel-base example and downloaded your cluster1.yml and cluster2.yml.
2. Removed the "io.cilium/global-service=true" from the rebel-base service.
3. Renamed rebel-base to bipin-base as I was having your original service running to test the environment.

alias kl='kubectl config get-contexts'
alias ka='kubectl config use-context a.xxxxxxxxxxxx'
alias kb='kubectl config use-context b.xxxxxxxxxxx'
alias ks='kubectl -n kube-system'
alias k='kubectl'

ka
k apply -f k8s-yaml/nginx/cluster1.yml
kb
k apply -f k8s-yaml/nginx/cluster2.yml

ka
kubectl annotate svc bipin-base io.cilium/global-service=true
kb
kubectl annotate svc bipin-base io.cilium/global-service=true

k get svc
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
bipin-base   ClusterIP   100.64.9.182   <none>        80/TCP    10m
kubernetes   ClusterIP   100.64.0.1     <none>        443/TCP   4h

ks exec cilium-cq9vw -- cilium service list
ID   Frontend             Backend
1    100.64.0.1:443       1 => 10.0.1.206:443
3    100.64.0.10:53       1 => 100.64.129.212:53
                          2 => 100.64.129.245:53
4    100.64.26.37:2379    1 => 100.64.129.101:2379
                          2 => 100.64.129.193:2379
                          3 => 100.64.129.27:2379
5    100.64.18.136:2379   1 => 100.64.129.101:2379
                          2 => 100.64.129.193:2379
                          3 => 100.64.129.27:2379
8    100.64.9.182:80      1 => 100.64.129.102:80
                          2 => 100.64.129.128:80
Please look at the service-id=8 
It show only the local ips.

The cluster1 and cluster2 YAML files which came with your examples works file.

That proves that this global-service annotation is not being picked for an existing service.

As a workaround if you can tell me how to update the service definition manually for time being for demo'ing this to team...it would help greatly

**General Information**

- Cilium version (run `cilium version`)
ks exec cilium-cq9vw -- cilium version
Client: 1.4.90 3adbd7f 2019-02-12T19:27:16-08:00 go version go1.11.1 linux/amd64
Daemon: 1.4.90 3adbd7f 2019-02-12T19:27:16-08:00 go version go1.11.1 linux/amd64

- Kernel version (run `uname -a`)
4.14.96-coreos

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
[nginx.zip](https://github.com/cilium/cilium/files/2860741/nginx.zip)

- Upload a system dump (run `curl -sLO
[cluster-diagnosis.zip](https://github.com/cilium/cilium/files/2860756/cluster-diagnosis.zip)

releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)
[cluster-diagnosis.zip](https://github.com/cilium/cilium/files/2860757/cluster-diagnosis.zip)

**How to reproduce the issue**

1. instruction 1
2. instruction 2

**Comment by bjethwan** [comment]
I faced this again today.
And the diagnostic report generating script is failing too 
curl -sLO releases.cilium.io/tools/cluster-diagnosis.zip && python cluster-diagnosis.zip sysdump
INFO collecting kubernetes version info ...
INFO collected kubernetes version info: k8s-version-info-20190214-035358.txt
INFO collecting nodes overview ...
INFO collected nodes overview: nodes-20190214-035359.json
INFO collecting pods overview ...
INFO collected pods overview: pods-20190214-035359.json
INFO collecting pods summary ...
INFO collected pods summary: pods-20190214-035359.txt
INFO collecting services overview ...
INFO collected svc overview: services-20190214-035359.yaml
INFO collecting cilium gops stats ...
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "cluster-diagnosis.zip/__main__.py", line 109, in <module>
  File "cluster-diagnosis.zip/sysdumpcollector.py", line 363, in collect
  File "cluster-diagnosis.zip/sysdumpcollector.py", line 142, in collect_gops_stats
  File "cluster-diagnosis.zip/sysdumpcollector.py", line 147, in collect_gops
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 732, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 154, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
[cluster-diagnosis.zip](https://github.com/cilium/cilium/files/2863220/cluster-diagnosis.zip)

**Comment by bjethwan** [comment]
Then I deleted my bipin-base, wherein I was annotating after the service creation...and used below to use your example...and everything worked fine.

ka
k delete -f k8s-yaml/nginx/cluster1.yml
kb
k delete -f k8s-yaml/nginx/cluster2.yml

ka
k apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes/clustermesh/global-service-example/cluster1.yaml
kb
k apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes/clustermesh/global-service-example/cluster2.yaml


$ for i in {1..10}; do k exec x-wing-7c89fcfb9f-gwqr2 -- curl -sS rebel-base; done
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-1"}
{"Galaxy": "Alderaan", "Cluster": "Cluster-2"}


SO THIS GLOBAL-SERVICE ANNOTATION IS NOT WORKING FOR EXISTING SERVICE.
KINDLY GIVE ME SOME WORKAROUND TO MAKE A PROGRESS.

**Comment by bjethwan** [comment]
And guess what....it worked if I delete the svc and re-create it with the said global-service annotation...so that means that global-service registration is happening only at service creation time.

**Comment by tgraf** [comment]
I've seen this before. The apiserver simply does not send a Service update notification for an annotation only change. You can work around it by changing another aspect of the service along with the annotation. What Kubernetes version are you using?

**Comment by bjethwan** [comment]
@tgraf 
I was using kubernetes 1.11.6.
Can we expect kubernetes fixing this issue in future?
Thanks for suggesting the workaround. I will sure give it a try.

**Comment by bjethwan** [comment]
@aanm 
How about documenting this so that, others don't break their head over this issue?

**Comment by brb** [comment]
A user reported similar instance of the problem - removing the annotation doesn't remove the registered remote endpoints.

I just checked that indeed kube-apiserver doesn't send any event when an annotation of a service changes.

**Comment by tgraf** [comment]
I've attempted to reproduce this but did not succeed in reproducing it. Please reopen when this is being observed again.
