### ISSUE TITLE
CT list does not print source IP

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#7064]
@joestringer it's probably because the DumpEntries is casting to `CtKey` and not `CtGlobalKey`

https://github.com/cilium/cilium/blob/bc911162fb7bc62dd718350caa06049f7b85e5fe/pkg/maps/ctmap/ctmap.go#L184-L201

Command is `cilium bpf ct list global`

**Comment by joestringer** [comment]
@aanm Ah, `CtKey` here is an interface but we use `key.ToHost().Dump()`, and `ToHost()` is only implemented in `CtKey[46]` (which is embedded in `CtKey[46]Global`, so it's implicitly converted into the local keys version even if you call it against a global key. I'll fix it.
