### ISSUE TITLE
kernel: Add delete operation to LPM BPF map

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#709]
The LPM bpf map type is currently lacking a delete operation

Workaround:
- Delete and recreate LPM bpf map
- Reload same BPF program

**Comment by borkmann** [comment]
kernel/bpf/lpm_trie.c
```
static int trie_delete_elem(struct bpf_map *map, void *key)
{
	/* TODO */
	return -ENOSYS;
}
```

**Comment by borkmann** [comment]
Can be closed, patch landed at netdev list:
https://patchwork.ozlabs.org/project/netdev/list/?series=3720
