### ISSUE TITLE
cilium-envoy: statically link against glibc

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#7097]
Been trying to copy the cilium-envoy binary out of the container image for testing on Ubuntu 16.04, but it refuses to run as Ubuntu 16.04 does not have glibc 2.27. Would be nice to have this statically linked for the image itself. /cc @jrajahalme @aanm

**Comment by jrajahalme** [comment]
Faced the same problem with Istio proxy, the container of which does not have glibc 2.27. Solved by installing glibc 2.27 into the container. Would be more robust to statically link instead!

**Comment by jrajahalme** [comment]
Envoy links external dependencies statically, but system dependencies dynamically. There is no into around on how to change this, so some experimentation will be needed.
