### ISSUE TITLE
lb: Avoid creating duplicate backend entries

### ISSUE THREAD

**Issue by brb** [cilium/cilium#7106]
Currently, the loadbalancer service maps can contain duplicate backend entries (1) to prevent from breaking existing connections when the backend entries configuration changes. This can lead to an unexpected growth (2) of the service maps in scale-up/scale-down scenarios. 

To keep the existing behavior of non-breaking existing connection, we can introduce additional map to store backend entries which solves (1) and (2).

This issue is for tracking all work required to solve the issues.

**Comment by brb** [comment]
RFC: https://docs.google.com/document/d/1zAqme6Blk-brIG6K-Y_1k3lpUB2Ql0xXwpvR0YpCLNs/edit

**Comment by joulaud** [comment]
In presence of autoscaling or even only with frequent deployment rolling-updates this is not only a theoretical problem but a complete failure of expected fairness with load-balancing. And the problem only gets worse as the time goes on.

The only workaround (complete deletion of the cilium_l4_services map) involves a lot of connection loss.
