### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes with L7 policy Tests NodePort with L7 Policy

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7124]
Output:
```
/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:408
Pod "testclient-tx5mj" can not connect to service "http://10.105.254.198:10080"
Expected command: kubectl exec -n default testclient-tx5mj -- curl -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://10.105.254.198:10080 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000023()', Connect: '0.000000',Transfer '0.000000', total '5.000961'
Stderr:
 	 

/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/k8sT/Services.go:184
```
Link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2380/testReport/junit/k8s-1/13/K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy/

Logs: 
[1f4cb98d_K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy.zip](https://github.com/cilium/cilium/files/2877145/1f4cb98d_K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy.zip)

**Comment by brb** [comment]
One more: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2410/testReport/junit/k8s-1/8/K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy/

**Comment by brb** [comment]
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6017/testReport/junit/k8s-1/8/K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy/

**Comment by ianvernon** [comment]
Hit in v1.4 as well:

https://jenkins.cilium.io/view/Cilium-v1.4/job/cilium-v1.4-standard/41/testReport/junit/k8s-1/13/K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy/
