### ISSUE TITLE
elf: dump dwarf debug output

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#714]
When kernel verifier complains, dump the kernel log and also output the dwarf info along with it, so we can correlate the code line that causes issues. Eases development.

**Comment by joestringer** [comment]
Looks like the recent BTF support in LLVM and kernel should facilitate this type of debugging, which makes dwarf support unnecessary.

**Comment by borkmann** [comment]
Yeah, lets close it. llvm-objdump tool will additionally also provide C source annotation, so no need to duplicate this into the loader anymore.
