### ISSUE TITLE
IPv6 LB handling has no special case for loopback LB

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7150]
In the IPv4 local loadbalancing code, we have this code to handle the case where a pod attempts to reach out to a service which is backed by its own IP (see the `DISABLE_LOOPBACK_IP` section):

https://github.com/cilium/cilium/blob/dbb89a1d594d12c0880264ee74cb29df5b9a9afd/bpf/lib/lb.h#L767-L795

However, this case is missing from the IPv6 local loadbalancing case:

https://github.com/cilium/cilium/blob/dbb89a1d594d12c0880264ee74cb29df5b9a9afd/bpf/lib/lb.h#L484-L495

Presumably as a result, any endpoints that attempt this path via IPv6 will fail to connect to themselves.

Found by inspection, I haven't manually tested this.

**Comment by joestringer** [comment]
Is this expected to be handled by some other mechanism, or does Linux not consider this as martian source?

**Comment by julianwiedmann** [comment]
Closing in favor of https://github.com/cilium/cilium/issues/26733.
