### ISSUE TITLE
Pods get stuck in ContainerCreating status with repeating agent errors: "rlock failed: endpoint is in the process of being removed"

### ISSUE THREAD

**Issue by utkuozdemir** [cilium/cilium#7225]
## Bug report

**General Information**

- Cilium version: 1.4.1
- Kernel version: Linux ccp-server-5-11 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use: Kubernetes 1.12.5 - **fresh** 3 master 5 worker cluster initialized via kubeadm
- Deployment script:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - image: nginx:stable-alpine
        name: simple-nginx
```

- System dump:
[cilium-sysdump-20190227-173006.zip](https://github.com/cilium/cilium/files/2911533/cilium-sysdump-20190227-173006.zip)

- Cilium Config: Drop-in `cilium.yaml`: https://github.com/cilium/cilium/blob/1.4.1/examples/kubernetes/1.12/cilium.yaml . 
- BPF fs is mounted to the nodes via systemd method. They report active&mounted on `systemctl status sys-fs-bpf.mount`. 

**How to reproduce the issue**

1. Start with a freshly installed cluster, with no workload.
2. Apply the deployment script above, wait for it to run the initial pod.
3. Scale it to a high number, in our case 500 - `kubectl scale deployment simple-nginx --replicas 500` (Note: We have max-pods number configured to be 512 per node, not the default 110).
4. Track the number of pods that are in `ContainerCreating` status via `kubectl get pod | grep ContainerCreating | wc -l`. It will get stuck at a number and won't go down (in our case it is stuck at 108)
5. `kubectl describe pod <ANY_STUCK_POD>` shows repeated events like:
```
  Normal   SandboxChanged          13m (x14 over 33m)  kubelet, ccp-server-5-35  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  89s (x13 over 19m)  kubelet, ccp-server-5-35  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "248c77b7b40d09439af32863050ebf51c7155287106642909ccd3fe34794d9fc" network for pod "simple-nginx-f6d45564f-zvh8z": NetworkPlugin cni failed to set up pod "simple-nginx-f6d45564f-zvh8z_default" network: Unable to create endpoint: Cilium API client timeout exceeded
```
6. Tailing/grep-ing "error" in any of the cilium pod logs that are on a node with stuck pods shows the repeated errors like:
```
level=error msg="Endpoint cannot be created" containerID=0821f0aa9cd1d6fa7a39fa5caf4dcbff592e830515fb258a423b3cc15c08996d error="aborting endpoint 414 join due client connection closed" eventID=241fb156-3ab2-11e9-8c32-02a962f32133 subsys=daemon
level=error msg="before regeneration" containerID=0821f0aa9c datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=414 error="rlock failed: endpoint is in the process of being removed" identity=35147 ipv4= ipv6= k8sPodName=default/simple-nginx-f6d45564f-27ckn subsys=endpoint
level=warning msg="Aborting endpoint join due client connection closed" error="context canceled" subsys=daemon
level=warning msg="Ignoring error while deleting endpoint" endpointID=2969 error="Unable to delete key 10.218.5.139 from /sys/fs/bpf/tc/globals/cilium_lxc: Unable to delete element from map cilium_lxc: no such file or directory" subsys=daemon
level=error msg="Endpoint cannot be created" containerID=c2764295371c743cbc2f63d6297d08ec52960db90395598330d163ee8155f033 error="aborting endpoint 2969 join due client connection closed" eventID=24619b48-3ab2-11e9-8c32-02a962f32133 subsys=daemon
level=error msg="before regeneration" containerID=c276429537 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2969 error="rlock failed: endpoint is in the process of being removed" identity=35147 ipv4= ipv6= k8sPodName=default/simple-nginx-f6d45564f-lfw5l subsys=endpoint
```

**Comment by utkuozdemir** [comment]
Update - After discussing and debugging the issue in Slack,
https://cilium.slack.com/archives/C1MATJ5U5/p1551289535072900
we tried passing `--container-runtime=none` to the cilium-agent and it helped as a workaround.
Seems Cilium was hitting the go client QPS limit when too many endpoints are requested at once.

**Comment by trevex** [comment]
We ran into the same issue, when we deployed cilium in a very very busy cluster. The aforementioned flag worked. :+1:
