### ISSUE TITLE
metrics: add metrics, benchmarks for PolicyAdd, PolicyDelete

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7229]
We need visibility into insight about how the `PolicyAdd` function scales. 

We have metrics to see how long it takes for a given policy to be 'implemented' for a given endpoint, which was added in 
https://github.com/cilium/cilium/pull/7160 . 

- [x] Similar to endpoint regeneration, we should have timing / metrics for how long certain operations in `PolicyAdd` take.
- [ ] Benchmark how long it takes to add 1000 REST API calls for adding policy
- [ ] Benchmark how long it takes to add a CNP with 1000 rules
    - Question: what should the content of the rules be? 

Things to note:

* we do not do rule sanitization as part of `PolicyAdd` - maybe we should benchmark this as well?

**Comment by joestringer** [comment]
@vadorovsky are you still interested in pursuing this? Otherwise we can unassign you. Anyone is welcome to volunteer to take up this issue, if we wish to improve this area further or understand the performance profile of policy calculation.

**Comment by vadorovsky** [comment]
@joestringer I unassigned myself, sorry!
