### ISSUE TITLE
investigate whether Cilium doesn't need key-value store to be set up for local identity allocation

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7231]
Follow-up to [discussion](https://docs.google.com/document/d/1bxO9gG76DvZTn0s4yRz-2U_s2X58Ea5xh_goabV1YhM/edit#bookmark=id.ssu135ps0q6l) in the biweekly SIG-policy meeting for Cilium . We should not need the key-value store to be up for local identity allocation. This ticket tracks whether or not that is the case, and fix said functionality in Cilium if necessary.

**Comment by tgraf** [comment]
@aanm The local identity handling is before we wait for the kvstore to be connected

https://github.com/cilium/cilium/blob/554d6b4d0ef146094af6f47817f70d3852412566/pkg/identity/cache/allocator.go#L184-L194
