### ISSUE TITLE
Add high-level runtime test for delete protection of in-use IPCache entries

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#7240]
We rely on each agent to recreate ipcache keys for which they see a delete event, but where the ipcache entry is still in use on this node (https://github.com/cilium/cilium/blob/master/pkg/ipcache/kvstore.go#L336-L342). This is augmented by doing a periodic full resync. We want to remove the resync and so should ensure the delete protection is reliable. The implementation details of how this works may change, and so a runtime/k8s test that actually uses etcd might be more reliable.

**Comment by aanm** [comment]
Not relevant anymore
