### ISSUE TITLE
Alignchecker is missing some structures

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7245]
I noticed a few map types that the alignchecker doesn't cover:
* EPPolicyMap
* PolicyMap
* Tunnel

Is there a reason to exclude these?

**Comment by joestringer** [comment]
Excluding policy_map was an important omission, because the alignment of these structs is otherwise not validated. For EPPolicyMap / Tunnel, they reuse endpoint_key which is validated so it's only important if in future we adjust the key/value of these map types.

**Comment by brb** [comment]
> Is there a reason to exclude these?

I got a list of structs to check from the old alignchecker, so that's why these were excluded.
