### ISSUE TITLE
permission denided on https://cilium.link/err-bpf-mount

### ISSUE THREAD

**Issue by nirmoy** [cilium/cilium#7269]
## Bug report
cilium warning which points to https://cilium.link/err-bpf-mount is not accessible 
`level=warning msg="BPF filesystem is going to be mounted automatically in /run/cilium/bpffs. However, it probably means that Cilium is running inside container and BPFFS is not mounted on the host. for more information, see: https://cilium.link/err-bpf-mount" subsys=bpf`

**Comment by joestringer** [comment]
Thanks for the report @nirmoy , I've left a note in the #sig-docs slack channel to follow up on fixing this link. In the mean time, the correct link is here:

https://docs.cilium.io/en/stable/kubernetes/requirements/#mounted-bpf-filesystem

**Comment by brb** [comment]
Thanks for the report, I've fixed the cilium.link.
