### ISSUE TITLE
Add 'configuration' action to policy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#73]
Allow endpoint options (IPv4/IPv6/NAT46/Conntrack/...) to be set via policy

> "coverage": ["io.foo.groupA"] 
> "configuration": [{ "IPv4": "true", "NAT46": "false" }]

**Comment by aanm** [comment]
@tgraf This can be difficult to implement. Supposing we have the following setup:

```
container A -> [io.foo.groupA, io.foo.groupB]
container B -> [io.foo.groupB]
container C -> [io.foo.groupA]
```

With the following policy

```
"coverage": ["io.foo.groupA"] 
"configuration": [{ "IPv4": "true", "NAT46": "false" }]
...
"coverage": ["io.foo.groupB"] 
"configuration": [{ "IPv4": "false", "NAT46": "true" }]
```

What will be the container A's configuration?

**Comment by tgraf** [comment]
The precedence follows the same logic as the precedence for connectivity policy.
