### ISSUE TITLE
Transparent Encryption: Key Rotation

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#7304]
Support changing keys in cluster without disruption.

- [x] implement rolling key updates
- [ ] document key versioning scheme
- [ ] fsnotify hook to update without restart
- [ ] generate key if it is not specified

**Comment by brb** [comment]
In the past I asked strongswan developers whether a key rotation makes sense when ESN is enabled, and they said "no, it's not required". Unfortunately, I cannot find freenode logs.

**Comment by jrfastab** [comment]
User request on #general we can fix up existing PR a bit and submit.

**Comment by dsx** [comment]
It would be nice to have IPsec keys to rotate automatically (and/or get created if none exists in config).

**Comment by jrfastab** [comment]
Automatically generating them seems like a nice addition IMO.
