### ISSUE TITLE
CI: Remote call on jenkins-fixed-2 failed

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7316]
The step "Archive JUnit-formatted test results - (7.7 sec in self)" fails with:

```
03:14:55  Recording test results
03:15:03  Remote call on jenkins-fixed-2 failed
```
Found in:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10504/ (https://github.com/cilium/cilium/pull/7095)

```
06:51:57  Recording test results
06:51:57  Remote call on jenkins-fixed-2 failed
```
Found in:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10506/ (https://github.com/cilium/cilium/pull/7299)

**Comment by eloycoto** [comment]
Node without space on disk. Already took care.

**Comment by joestringer** [comment]
@eloycoto hit again on master:

https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2500/execution/node/101/log/
