### ISSUE TITLE
CI: Provide reason why endpoint is not ready

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#7317]
The following example of a test failure is practically impossible to debug:

```
00:15:41.393  STEP: Checking that installed image is "k8s1:5000/cilium/cilium-dev:latest"
00:15:41.393  STEP: Validate that endpoints are ready before making any connection
01:17:32.430  Sending interrupt signal to process
01:17:34.137  cleaning up VMs started for k8s tests
01:17:34.137  
01:17:34.137  ---------------------------------------------------------
01:17:34.137  Received interrupt.  Running AfterSuite...
01:17:34.137  ^C again to terminate immediately
```

Similar to how 5aba0b63a3efa8a49cdb526e4a6fa8a92b6d1c65 introduced the reason for the pre flight check. Provide the reason for this check as well. The same logic should be used to not repeat the error if it is the same one unless a certain repetition limit is reached to avoid spamming while also allowing to see when a test no longer progresses.

**Comment by eloycoto** [comment]
@tgraf I was working on this for the whole week, some progress made here: 
https://github.com/cilium/cilium/pull/7295

**Comment by jrajahalme** [comment]
@eloycoto Is there any way to see what happened (when this happens) in the build artifacts? This happened for k8s 1.8 CI tests for me, but artifacts contain only `.pprof` files (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10493/).

**Comment by ianvernon** [comment]
We have added timeouts for the ginkgo tests themselves which are shorter than the Jenkins timeouts; this should be fixed now.
