### ISSUE TITLE
QA: Run XDP on Cilium

### ISSUE THREAD

**Issue by felix0080** [cilium/cilium#7335]
## Support

 I deployed cilium in cluster,whether to need the support of network card. I'm afraid my network card doesn't support XDP

**Comment by nirmoy** [comment]
@felix0080 There is no need of XDP support in nic to run cilium. XDP comes into picture only if you wants to use prefilters but that also can be mitigate by using `cilium-agent .. --prefilter-mode=generic`

**Comment by felix0080** [comment]
> @felix0080 There is no need of XDP support in nic to run cilium. XDP comes into picture only if you wants to use prefilters but that also can be mitigate by using `cilium-agent .. --prefilter-mode=generic`

; ) Thank you , I got it
