### ISSUE TITLE
images and imagePullPolicy for `examples/kubernetes/node-init` are not updated in release branches

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7342]
Add according sed scripts, template files, etc.

**Comment by tgraf** [comment]
@ianvernon Looked into this, the images and policy used are:
```
          image: gcr.io/google-containers/startup-script:v1
          imagePullPolicy: IfNotPresent
```

What exactly needs to be changed/automated?

**Comment by ianvernon** [comment]
I think I meant `cilium-with-node-init.yaml`, but I cursed myself by not giving a good issue description. Said files are OK in v1.5, so we can close this.
