### ISSUE TITLE
Test etcd scalability

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#7396]
Tasks:
 - [x] Test whether we can maintain 1k connections to an etcd cluster
 - [x] Test whether we can maintain 2k connections to an etcd cluster
 - [x] Derive number of etcd nodes required per 1k nodes
 - [x] Derive disk size requirements per 1k nodes
 - [x] Measure Disk IO per 1k nodes

**Comment by aanm** [comment]
Cilium doesn't stress out too much the etcd's disk with 2k nodes.

Right now we are shooting for 3x 4vCPUs with 2GB of memory for 1k cilium-agents.
