### ISSUE TITLE
Print service ID in cilium service list

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#744]
```
cilium service list
10.0.0.10:53 =>
		1 => 10.1.0.3:53 (1)
10.0.0.131:80 =>
		1 => 10.15.148.179:80 (4)
		2 => 10.15.226.3:80 (4)
10.0.0.1:443 =>
		1 => 10.0.2.15:8443 (2)
```

- [ ] print proper header to explain flag, ID, backend IPs
- [ ] use `text/tabwriter`
- [ ] consider a more compact format to print backend IPs

**Comment by aanm** [comment]
> consider a more compact format to print backend IPs

Can you clarify this a bit?
