### ISSUE TITLE
container id in BPF debug message is wrong

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#746]
```
CPU 00: MARK 0x4d3d3f0d FROM 42910 DEBUG: Attempting local delivery for container id 56326 from seclabel 259
```

The `container id 56326` is wrong. Should be `33115` in this case. Possibly in wrong byte order.

**Comment by aalemayhu** [comment]
The line printing this is from [debug.go](https://github.com/cilium/cilium/blob/ce146133d540241e2bd70d5cd8ef2080fdd534cf/pkg/bpfdebug/debug.go#L169)
```
		fmt.Printf("Attempting local delivery for container id %d from seclabel %d\n", n.Arg1, n.Arg2)
```
I don't get why not all of the printing lines in `Dump(...)` are not using `.Swab*`.

How did you notice this was wrong? I was considering writing a test to verify before fixing.

**Comment by tgraf** [comment]
I noticed while debugging. A test would be great.

**Comment by aalemayhu** [comment]
I suspect this is only for ipv4. Tried reproducing with ipv6 but failed. Have a test now but need to fix root cause and cleanup before pull request.

**Comment by aalemayhu** [comment]
@tgraf I believe this is fixed by the byte order pull request. If you could take a closer look at the test added that would be great. https://github.com/scanf/cilium/commit/377944d0171a637bcd4e6f20b74c0836e1254e84

Thanks!

**Comment by aalemayhu** [comment]
Suspect this is fixed, if not please re-open.
