### ISSUE TITLE
Support WireGuard for encryption

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#7519]
As WireGuard is merged into the kernel [0]. Add support for it as encryption alternative compared to IPSec

[0] https://lwn.net/Articles/768826/

**Comment by joestringer** [comment]
#10398 explains a bit more detail on wireguard.

**Comment by amon-ra** [comment]
This can be used as reference:
- https://github.com/rancher/k3s/blob/master/scripts/wg-add.sh
- https://github.com/gravitational/wormhole

**Comment by blinkiz** [comment]
Maybe talk to Lucas Servén Marín, Red Hat, and see if ideas from Kilo project can be integrated into Cilium. Written in Go just like Cilium.

https://github.com/squat/kilo

**Comment by ve2xe4** [comment]
Had this been de-prioritized? Don't see the issue in any GitHub project. Originally targeted for cilium 1.7 / 1.8.

**Comment by ZaMaZaN4iK** [comment]
Any updates? Is there any plans about Wireguard integration into Cilium?

**Comment by lyind** [comment]
We are using Wireguard in an IPv6-only K8s + Cilium setup to protect routes between the cluster and certain node-balancer nodes.

Right now that requires maintaining explicit routes via the wireguard interface and into the pod-networks of each node in the cluster.

The usual "connect all pods via encrypted links" feature wouldn't make too much sense for us, as we require fast (10G+) links between most of our cluster nodes/pods.

Sounds like Kilo (mentioned above) would suit us pretty well, but we like Cilium.

**Comment by blinkiz** [comment]
Here is an article about [WireGuard Endpoint Discovery and NAT Traversal using DNS-SD](https://www.jordanwhited.com/posts/wireguard-endpoint-discovery-nat-traversal/) exploring possibilities with UDP hole punching. It maybe will give some ideas and inspiration when trying to design this feature.
