### ISSUE TITLE
Support PROXY protocol

### ISSUE THREAD

**Issue by tumasgiu** [cilium/cilium#7531]
Hello,
We deployed a Vault HA setup on a Digital Ocean Kubernetes cluster. Traffic from services in other namespaces is direct (controlled via network policies) but we would also like to provide access to the staff via a load balancer with whitelisted IPs. 

Unfortunately, Digital Ocean does not support firewall on load balancers or the `loadBalancerSourceRanges` parameter. 

We do not want to terminate TLS on the LB so we've chosen to set up the LB in TCP mode with [PROXY protocol](http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) and therefore can't use filtering using X-Forwarded-For. 

It would be useful to be able to use the source address from the PROXY protocol to filter authorized clients at the pod level.

**Comment by Preisschild** [comment]
Hetzner LoadBalancers also only support the PROXY Protocol to get source ip information. I think this would be a great addition to cilium.
