### ISSUE TITLE
cilium-health doesn't stop pinging nodes when cluster is scaled down

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7533]
The logic in #5185 does not appear to be having the intended effect, or may potentially not work when significantly scaling down the cluster. The `cilium status -o json` output shows only a few nodes (this is where `cilium-health` gets its node list from), however we see `cilium-health` reports based on a large cluster size:

```
$ cilium status
...
Cluster health:                                         60/2004 reachable   (2019-03-27T18:17:25Z)
```

Tasks:
* [ ] Refactor `cilium-health` to ease unit-testing
* [ ] Write a unit test to test that resizing a cluster will cause cilium-health to learn new nodes and forget old nodes
* [ ] Fix the bug

**Comment by joestringer** [comment]
Likely caused by the node tracking in the Cilium daemon side, as cilium-health just picks up the list from there and uses it.

**Comment by joestringer** [comment]
I'd be interested to hear from any users that observe this behaviour for extended periods of time.

It appears that the `baseBackgroundSyncInterval` (scaled by size of the cluster via `ClusterSizeDependantInterval()`) should cause this to resynchronize within 10 minutes or so in most clusters (even less in smaller clusters).

**Comment by jrfastab** [comment]
~Duplicated this but after ./node/mangaer sync interval this got back in-sync. The sync interval is dependent on the number of nodes so with 10+ nodes it may take a few minutes or so to sync.~

That was something else... Is it possible cilium-agent's are not being shutdown through daemon Close() path and so the kvstore keeps all the keys.

**Comment by jrfastab** [comment]
Here is the root cause,

https://github.com/cilium/cilium/issues/7805

**Comment by joestringer** [comment]
Thanks @jrfastab, I will close this issue then since the issue #7805 defines the issue more clearly.
