### ISSUE TITLE
CI: v1.4: k8sChaosTest: Timeout reached: timed out waiting for pods with filter -l k8s-app=cilium to be ready

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7546]
v1.4 backports failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11164/execution/node/84/log/

```
21:22:36  • Failure [312.660 seconds]
21:22:36  K8sChaosTest
21:22:36  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
21:22:36    Restart with long lived connections
21:22:36    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
21:22:36      L3/L4 policies still work while Cilium is restarted [It]
21:22:36      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:408
21:22:36  
21:22:36      Pods are not ready after timeout
[2019-03-29T21:22:36.562Z]     Expected
[2019-03-29T21:22:36.562Z]         <*errors.errorString | 0xc4234b0110>: {
[2019-03-29T21:22:36.562Z]             s: "Timeout reached: timed out waiting for pods with filter -l k8s-app=cilium to be ready",
[2019-03-29T21:22:36.562Z]         }
[2019-03-29T21:22:36.562Z]     to be nil
21:22:36  
21:22:36      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Chaos.go:217
```

First failure:
[e369f6d6_K8sChaosTest_Restart_with_long_lived_connections_L3-L4_policies_still_work_while_Cilium_is_restarted.zip](https://github.com/cilium/cilium/files/3024723/e369f6d6_K8sChaosTest_Restart_with_long_lived_connections_L3-L4_policies_still_work_while_Cilium_is_restarted.zip)

This likely caused the follow-on test to also fail:
[f5c45edb_K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip](https://github.com/cilium/cilium/files/3024727/f5c45edb_K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip)

**Comment by joestringer** [comment]
CI didn't gather proper bugtool for some reason, the archives have only four files, primarily the test output txt.

**Comment by jrajahalme** [comment]
Similar flake at https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12707/testReport/junit/Suite-k8s-1/14/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_automatic_direct_nodes_routes/
