### ISSUE TITLE
Support hostport via CNI chain in cni-install script

### ISSUE THREAD

**Issue by DerekV** [cilium/cilium#7556]
## Proposal / RFE

**Is your feature request related to a problem?**

When using kops to install a cluster with cilium, hostPort is not supported out of the box.  It would be nice to have this supported out of the box, or have the option for it, without need to implement additional hooks or overrides.

**Describe the solution you'd like**

As per conversation with @tgraf on slack, It seems like `cni-install.sh` https://github.com/cilium/cilium/blob/master/plugins/cilium-cni/cni-install.sh would be a logical place to add this.  I'm not sure myself if it should always be configured, or if it should be controllable with a flag (and what the default would be), since I'm not sure what the drawbacks might be.

**Comment by mrostecki** [comment]
Implemented in #7901
