### ISSUE TITLE
CI: runtime.RuntimeChaos Checking that during restart no traffic is dropped using Egress + Ingress Traffic

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#7591]
Hit on master, https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2645/testReport/junit/(root)/runtime/RuntimeChaos_Checking_that_during_restart_no_traffic_is_dropped_using_Egress___Ingress_Traffic/

```
Stacktrace
/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
Curl from app2 to httpd1 should work but it failed at 2019-04-03 22:58:19.002809005 +0000 UTC m=+1661.733638929
Expected command: docker exec -i  app1 curl -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://10.15.37.211/ -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000022()', Connect: '0.000000',Transfer '0.000000', total '5.001817'
Stderr:
 	 

/home/jenkins/workspace/cilium-ginkgo_cilium_master/src/github.com/cilium/cilium/test/runtime/chaos.go:195
```

**Comment by borkmann** [comment]
Hit from CI run in  #7583

**Comment by tgraf** [comment]
Could be related to https://github.com/cilium/cilium/issues/7637

**Comment by raybejjani** [comment]
Another master flake https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2666

**Comment by tgraf** [comment]
Hit in CI pipeline:
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6545/testReport/(root)/runtime/RuntimeChaos_Checking_that_during_restart_no_traffic_is_dropped_using_Egress___Ingress_Traffic/

**Comment by tgraf** [comment]
Possibly related with #7641

**Comment by nebril** [comment]
I am getting this on master every ~20 local ginkgo runs.

**Comment by raybejjani** [comment]
We're hopeful that this was sorted out in https://github.com/cilium/cilium/pull/7682 nebril and I are trying to test this out.

**Comment by nebril** [comment]
I ran the test over 40 times
`while ginkgo -v --focus "RuntimeChaos Checking that during restart no traffic is dropped " -- --cilium.provision=false; do COUNT=$((COUNT+1)); echo $COUNT; done`
And didn't get a flake.

Seems like #7682 fixed this issue.
