### ISSUE TITLE
CI: K8sDatapathConfig Encapsulation Check connectivity with transparent encryption and VXLAN encapsulation

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7615]
This ticket is for tracking purposes - the underlying cause to this test failure is expected to be https://github.com/cilium/cilium/issues/7598 .

**Comment by tgraf** [comment]
I'm able to reproduce this. It is not related to #7598

**Comment by tgraf** [comment]
I see that some traffic is not encrypted on `cilium_vxlan`:
```
12:25:05.971251 IP 10.10.0.142.47873 > 10.10.1.33.53: 17035+ AAAA? cilium-etcd-x5wz7pshsq.cilium-etcd.kube-system.svc. (68)
12:25:05.971293 IP 10.10.0.142.33479 > 10.10.1.33.53: 16015+ A? cilium-etcd-x5wz7pshsq.cilium-etcd.kube-system.svc. (68)
```

ipcache:
```
IP PREFIX/ADDRESS          IDENTITY
f00d::a0a:100:0:eed5/128   6226 5
f00d::a0a:100:0:1/128      1 5
fd04::12/128               1 5
10.10.1.33/32              104 5
f00d::a0a:100:0:24d/128    104 5
0.0.0.0/0                  2 5
f00d::a0a:100:0:56b3/128   4 5
f00d::a0a:100:0:2872/128   101 5
192.168.36.12/32           1 5
::/0                       2 5
10.10.1.31/32              100 5
10.10.1.75/32              26935 5
10.10.1.85/32              101 5
10.10.1.199/32             6226 5
f00d::a0a:100:0:8953/128   101 5
10.10.1.1/32               1 5
10.10.1.110/32             4 5
f00d::a0a:100:0:b98b/128   26935 5
f00d::a0a:100:0:db97/128   100 5
10.10.1.14/32              101 5
```

xfrm policy:
```
src ::/0 dst f00d::a0a:100:0:1/112
	dir fwd priority 0
	mark 0x5d00/0xf00
	tmpl src :: dst f00d::a0a:100:0:1
		proto esp spi 0x00000005 reqid 1 mode tunnel
src ::/0 dst f00d::a0a:100:0:1/112
	dir in priority 0
	mark 0x5d00/0xf00
	tmpl src :: dst f00d::a0a:100:0:1
		proto esp spi 0x00000005 reqid 1 mode tunnel
src 0.0.0.0/0 dst 10.10.1.1/24
	dir fwd priority 0
	mark 0x5d00/0xf00
	tmpl src 0.0.0.0 dst 10.10.1.1
		proto esp spi 0x00000005 reqid 1 mode tunnel
src 0.0.0.0/0 dst 10.10.1.1/24
	dir in priority 0
	mark 0x5d00/0xf00
	tmpl src 0.0.0.0 dst 10.10.1.1
		proto esp spi 0x00000005 reqid 1 mode tunnel
src ::/0 dst f00d::a0a:0:0:1/112
	dir out priority 0
	mark 0x5e00/0xff00
	tmpl src :: dst f00d::a0a:0:0:1
		proto esp spi 0x00000005 reqid 1 mode tunnel
src 10.10.1.1/24 dst 10.10.0.1/24
	dir out priority 0
	mark 0x5e00/0xff00
	tmpl src 10.10.1.1 dst 10.10.0.1
		proto esp spi 0x00000005 reqid 1 mode tunnel
src ::/0 dst f00d::a0a:0:0:1/96
	dir out priority 0
	mark 0x5e00/0xff00
	tmpl src :: dst f00d::a0a:0:0:1
		proto esp spi 0x00000005 reqid 1 mode tunnel
```

xfrm state:
```
src :: dst f00d::a0a:0:0:1
	proto esp spi 0x00000005 reqid 1 mode tunnel
	replay-window 0
	auth-trunc hmac(sha256) 0x0123456789abcdef0123456789abcdef 96
	enc cbc(aes) 0x0123456789abcdef0123456789abcdef
	anti-replay context: seq 0x0, oseq 0x1a, bitmap 0x00000000
	sel src ::/0 dst ::/0
src 10.10.1.1 dst 10.10.0.1
	proto esp spi 0x00000005 reqid 1 mode tunnel
	replay-window 0
	auth-trunc hmac(sha256) 0x0123456789abcdef0123456789abcdef 96
	enc cbc(aes) 0x0123456789abcdef0123456789abcdef
	anti-replay context: seq 0x0, oseq 0x13bb3, bitmap 0x00000000
	sel src 0.0.0.0/0 dst 0.0.0.0/0
src :: dst f00d::a0a:100:0:1
	proto esp spi 0x00000005 reqid 1 mode tunnel
	replay-window 0
	auth-trunc hmac(sha256) 0x0123456789abcdef0123456789abcdef 96
	enc cbc(aes) 0x0123456789abcdef0123456789abcdef
	anti-replay context: seq 0x0, oseq 0x0, bitmap 0x00000000
	sel src ::/0 dst ::/0
src 0.0.0.0 dst 10.10.1.1
	proto esp spi 0x00000005 reqid 1 mode tunnel
	replay-window 0
	auth-trunc hmac(sha256) 0x0123456789abcdef0123456789abcdef 96
	enc cbc(aes) 0x0123456789abcdef0123456789abcdef
	anti-replay context: seq 0x0, oseq 0x0, bitmap 0x00000000
	sel src 0.0.0.0/0 dst 0.0.0.0/0
```

**Comment by tgraf** [comment]
@jrfastab I can hit this consistently by doing:
```
cd test
ginkgo --focus "K8sDatapathConfig*" -v -- -cilium.holdEnvironment=true
```

Please have a look. I see that some connectivity fails due to encryption

**Comment by ianvernon** [comment]
Still being hit after being re-enabled :( 

* https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6600/
* https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6601/

**Comment by jrajahalme** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11584/execution/node/83/log/

**Comment by jrajahalme** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11585/execution/node/83/log/

**Comment by jrajahalme** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11586/execution/node/83/log/

**Comment by jrajahalme** [comment]
Here as well: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11741/

**Comment by ianvernon** [comment]
Hit in master: 

* [Ginkgo-CI-Tests-Pipeline-6660](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6660/testReport/junit/Suite-k8s-1/14/K8sDatapathConfig_Encapsulation_Check_connectivity_with_transparent_encryption_and_VXLAN_encapsulation/)
    - One thing to note here is that identities could not be allocated for the entire K8sDatapathConfig run. This indicates that etcd-operator got in a bad state, and could never recover. 
* [Master 2743](https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2743/testReport/junit/Suite-k8s-1/10/K8sDatapathConfig_Encapsulation_Check_connectivity_with_transparent_encryption_and_VXLAN_encapsulation/)
    - All other tests in the K8sDatapathConfig suite ran OK.
* [Master 2744](https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2744)
    - CI got stuck after ( see #7796 ).
* [Master 2745](https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2745/)
* [Master 2747](https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2747/)
* [Ginkgo-CI-Tests-Pipeline-6656](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6656/)
* [Ginkgo-CI-Tests-Pipeline-6657](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6657/)
* [Ginkgo-CI-Tests-Pipeline-6673](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6673/)
* [Ginkgo-CI-Tests-Pipeline-6672](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6672/)
* [Ginkgo-CI-Tests-Pipeline-6668](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6668/)
* [Ginkgo-CI-Tests-Pipeline-6664](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6664/)
* [Ginkgo-CI-Tests-Pipline-6659](https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6659/)
* [Master 2747](https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2747/)

Things to note:

* Occurs in K8s 1.10 and K8s1.14 (e.g., not tied to specific K8s version).

**Comment by tgraf** [comment]
We are no longer seeing this. Closing

**Comment by jrajahalme** [comment]
Still seeing this ([here](https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13710/testReport/Suite-k8s-1/10/K8sDatapathConfig_Encapsulation_Check_connectivity_with_transparent_encryption_and_VXLAN_encapsulation/)): 

```
Failed
Suite-k8s-1.10.K8sDatapathConfig Encapsulation Check connectivity with transparent encryption and VXLAN encapsulation

Stacktrace
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
cilium pre-flight checks failed
Expected
    <*errors.errorString | 0xc00067e050>: {
        s: "CiliumPreFlightCheck error: Timeout reached: PreflightCheck failed: Last polled error: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-b7wxs': Exitcode: 255 \nStdout:\n \t \nStderr:\n \t Error: Cannot get status/probe: Put http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe: context deadline exceeded\n\t \n\t command terminated with exit code 255\n\t \n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:92
Standard Output
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
⚠️  Number of "level=warning" in logs: 27
Number of "Cilium API handler panicked" in logs: 0
⚠️  Number of "Goroutine took lock for more than" in logs: 15
Top 5 errors/warnings:
Received kvstore delete notification for alive ipcache entry
Received delete event for local key. Re-creating the key in the kvstore
Unable to update ipcache entry of Kubernetes node
Received node delete event for node default/k8s2 which re-appeared within 30s
Received node delete event for node default/k8s1 which re-appeared within 30s
```

**Comment by joestringer** [comment]
Hasn't been seen in a long time, closing.
