### ISSUE TITLE
Deletion of NOTRACK rule fails in the CI

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#7619]
```
level=error msg="Command execution failed" cmd="[iptables -t raw -D PREROUTING -m mark --mark 0x00000e00/0x00000f00 -m comment --comment cilium-xfrm-notrack: -j NOTRACK]" error="exit status 1" subsys=iptables
```

Please avoid unnecessary error messages

**Comment by jrajahalme** [comment]
Looking at the artifacts of a recent master build (https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2746/), I can't find these messages in the logs any more.
