### ISSUE TITLE
split up Developer / Contributing guide into separate pages

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7632]
This document is huge now, and hard to navigate. We can have a single 'landing page' which points to logically-divided-up pages.

**Comment by joestringer** [comment]
Agree. A lot of the contributing guide is about release management which is not relevant to some developers.

I see at least a few logically separate guides out of it:
* Basic development workflow
* Dealing with the CI
* Release management
* Backporting

**Comment by ianvernon** [comment]
I've partially completed this so far...

**Comment by ianvernon** [comment]
Fixed-by #9456
