### ISSUE TITLE
Set user agent for k8s clients

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#7634]
Set a static user agent for the k8s client that we are using. We should add cilium's commit and version to that user agent

**Comment by ianvernon** [comment]
Can you clarify what a user agent is?

**Comment by aanm** [comment]
> Can you clarify what a user agent is?

https://github.com/cilium/cilium/blob/521ee8357011958d9a099413a7b64688e1180df8/vendor/k8s.io/client-go/rest/config.go#L94-L95

**Comment by jukie** [comment]
Where should this get added? I'm digging through the code still but would like to contribute
