### ISSUE TITLE
CI: Istio test failed due to 'unexpected end of JSON input' returned from CNI ADD

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7718]
Kubelet logs from k8s2-1.10:

```
Apr 14 03:52:03 k8s2 kubelet[4464]: E0414 03:52:03.457282    4464 cni.go:259] Error adding network: unexpected end of JSON input
Apr 14 03:52:03 k8s2 kubelet[4464]: E0414 03:52:03.457541    4464 cni.go:227] Error while adding to cni network: unexpected end of JSON input
Apr 14 03:52:03 k8s2 kubelet[4464]: E0414 03:52:03.633419    4464 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "productpage-v1-5f9d4dcd9c-wxbg2_default" network: unexpected end of JSON input
Apr 14 03:52:03 k8s2 kubelet[4464]: E0414 03:52:03.633779    4464 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "productpage-v1-5f9d4dcd9c-wxbg2_default(735d02b4-5e68-11e9-8c63-080027a49cd9)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "productpage-v1-5f9d4dcd9c-wxbg2_default" network: unexpected end of JSON input
Apr 14 03:52:03 k8s2 kubelet[4464]: E0414 03:52:03.634034    4464 kuberuntime_manager.go:646] createPodSandbox for pod "productpage-v1-5f9d4dcd9c-wxbg2_default(735d02b4-5e68-11e9-8c63-080027a49cd9)" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "productpage-v1-5f9d4dcd9c-wxbg2_default" network: unexpected end of JSON input
```

Endpoint unable to replace qdisc because after this, CNI DELETE was invoked, which removed the network namespace / associated network devices :

```
2019-04-14T03:52:06.23150625Z level=warning msg="JoinEP: Failed to load program" containerID=92f6a9f68c datapathPolicyRevision=0 desiredPolicyRevision=29 endpointID=1945 error="Failed to replace Qdisc for lxc86a47dd64fc1: Link not found" file-path=1945_next/bpf_lxc.o identity=7905 ipv4=10.10.1.25 ipv6="f00d::a0a:100:0:26e1" k8sPodName=default/productpage-v1-5f9d4dcd9c-wxbg2 subsys=datapath-loader veth=lxc86a47dd64fc1
...
2019-04-14T03:52:06.28416682Z level=warning msg="Creation of endpoint failed" containerID=92f6a9f68c datapathPolicyRevision=0 desiredPolicyRevision=29 endpointID=1945 error="timeout while waiting for initial endpoint generation to complete" identity=7905 ipv4=10.10.1.25 ipv6="f00d::a0a:100:0:26e1" k8sPodName=default/productpage-v1-5f9d4dcd9c-wxbg2 subsys=daemon
```

This is from a CI run, and doesn't appear to be related to the changes in the branch: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11582/testReport/junit/Suite-k8s-1/10/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/

Logs: 
[K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip](https://github.com/cilium/cilium/files/3077041/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip)

**Comment by ianvernon** [comment]
Happened again in a CI run for functionality which is unrelated to the Istio test functionality AFAICT: [K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip](https://github.com/cilium/cilium/files/3081443/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip)

PR link: https://github.com/cilium/cilium/pull/7616
Build link: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11576/

**Comment by tgraf** [comment]
Removing the release blocker flag. This seems to be very rare and kubelet will retry and succeed. This is primarily a CI flake problem.

**Comment by jrajahalme** [comment]
Apparently kubelet expects well-formed JSON input also on CNI failure cases. Could it be that we fail to do that when creation of endpoint fails?

**Comment by ianvernon** [comment]
https://github.com/cilium/cilium/pull/7978 purportedly fixed this issue, and we haven't see this failure since. Closing.
