### ISSUE TITLE
Getting started guide "vagrant up" not working.

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#775]
On OS X I get this on master when doing:

$ vagrant destroy
...
$ vagrant up
Bringing machine 'cilium-1' up with 'virtualbox' provider...
...
==> cilium-1: Checking for guest additions in VM...
    cilium-1: No guest additions were detected on the base box for this VM! Guest
    cilium-1: additions are required for forwarded ports, shared folders, host only
    cilium-1: networking, and more. If SSH fails on this machine, please install
    cilium-1: the guest additions and repackage the box to continue.
    cilium-1: 
    cilium-1: This is not an error message; everything may continue to work properly,
    cilium-1: in which case you may ignore this message.
==> cilium-1: Setting hostname...
==> cilium-1: Configuring and enabling network interfaces...
==> cilium-1: Mounting shared folders...
    cilium-1: /vagrant => /Users/jarno/dev/cilium/examples/getting-started
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: unknown filesystem type 'vboxsf'
$ vagrant version
Installed Version: 1.9.4
Latest Version: 1.9.5
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/mitchellh/vagrant/blob/v1.9.5/CHANGELOG.md

**Comment by aanm** [comment]
Possible caused by: https://github.com/cilium/cilium/pull/687

**Comment by danwent** [comment]
@aanm  I can confirm that when I switch the Vagrant file back to bento (i.e., revert #687) the VM boots again.
