### ISSUE TITLE
CI: run one of K8s test runs with later kernel version

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7751]
The feature set of Cilium has grown significantly since its inception. Along with these new features come additional requirements on the kernel side. We currently have no way of seeing if an individual PR breaks this functionality without running the CI with `test-me-please` and `test-me-please` with the `ci/net-next` label. This is not a tenable way of testing this functionality, because it requires two whole iterations through the CI to test with a different kernel version.

The K8s tests should be fairly insulated from the version of the kernel running (ideally). Given that we are already running all K8s tests in parallel, we should run one of the K8s suites against a newer kernel. In this test suite, we could run tests which test additional functionality in Cilium that only specific kernel versions support (BPF SNAT, IPVLAN, etc.). This would ensure that we do not regress with these features, as well as not significantly hamper turnaround time for developers to get feedback on whether their code is stable.

**Comment by brb** [comment]
I think it's OK to close this issue as #7752, which addresses the issue, got merged. Please re-open if you think otherwise.
