### ISSUE TITLE
CI: build box with stable kernel version for use in CI

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7765]
While we have a box with the latest net-next kernel installed, we should use a stable, vetted kernel version for testing with newer kernel versions

**Comment by eloycoto** [comment]
Maybe If we use the default kernel for the Ubuntu is the closest installation that we can do ;-)

**Comment by joestringer** [comment]
Yeah, Ubuntu just came out with Ubuntu 19.04 with kernel 5.0 which is probably a good recent choice to test with.
