### ISSUE TITLE
CI: bugtool fails sometimes due to `template.o` files being present

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7774]
In https://github.com/cilium/cilium/issues/7770 , there is a bugtool where the test code appears to have successfully gathered a bunch of logs, including gathering information directly, for example `cilium-b7sg7_status.txt` is populated and appears happy, and yet there is no bugtool directory inside the zip that corresponds to this pod.

[bf0b2125_K8sDatapathConfig_IPv4Only_Check_connectivity_with_IPv6_disabled.zip](https://github.com/cilium/cilium/files/3091772/bf0b2125_K8sDatapathConfig_IPv4Only_Check_connectivity_with_IPv6_disabled.zip)

**Comment by ianvernon** [comment]
from `test-output.log`:


```
time="2019-04-17T20:15:51Z" level=error msg="kubectl exec -n kube-system cilium-b7sg7 -- cilium-bugtool failed: Deleted empty directory /tmp/cilium-bugtool-20190417-201548.689+0000-UTC-926144978/cmd\nDeleted empty directory /tmp/cilium-bugtool-20190417-201548.689+0000-UTC-926144978/conf\nFailed to open /tmp/cilium-bugtool-20190417-201548.689+0000-UTC-926144978/cmd/state/64/template.o open /tmp/cilium-bugtool-20190417-201548.689+0000-UTC-926144978/cmd/state/64/template.o: no such file or directoryFailed to create archive File information cannot get retrieved: invalid argument\ncommand terminated with exit code 1\n" CiliumPod=cilium-b7sg7
time="2019-04-17T20:15:51Z" level=error msg="kubectl exec -n kube-system cilium-b7sg7 -- cilium-bugtool failed: Deleted empty directory /tmp/cilium-bugtool-20190417-201548.689+0000-UTC-926144978/cmd\nDeleted empty directory /tmp/cilium-bugtool-20190417-201548.689+0000-UTC-926144978/conf\nFailed to open /tmp/cilium-bugtool-20190417-201548.689+0000-UTC-926144978/cmd/state/64/template.o open /tmp/cilium-bugtool-20190417-201548.689+0000-UTC-926144978/cmd/state/64/template.o: no such file or directoryFailed to create archive File information cannot get retrieved: invalid argument\ncommand terminated with exit code 1\n" CiliumPod=cilium-b7sg7
```

**Comment by joestringer** [comment]
Is the bugtool trying to take a deep copy of all files, where in the symlink case it's not linking to a full path on the filesystem but instead linking relatively? If so, we could consider either changing the link to full path, or preventing following symlinks, or ignoring symlinks.
