### ISSUE TITLE
cilium_{host|net} veth pair not be removed when cilium-agent stopped

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#779]
In some cases cilium-agent is not removing the cilium_{host|net} veth pair when it exits.

**Comment by tgraf** [comment]
This is done on purpose because we want packets to continue flowing while we upgrade the agent. We could think about using a special signal to keep everything running instead though.

**Comment by jrfastab** [comment]
OK, this is just from inspection, but shouldn't init.sh be doing a 'tc filter replace' call then instead of a 'tc filter add'. or is the filter going to be deleted somewhere before hand.
