### ISSUE TITLE
CI: entire test suite occasionally gets stuck while performing Cilium Pre-Flight Check

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#7796]
I have increasingly been seeing issues like the following in the CI:

```
12:42:02  STEP: Performing Cilium preflight check
13:19:28  Sending interrupt signal to process
13:19:32  cleaning up VMs started for k8s tests
13:19:32  
13:19:32  ---------------------------------------------------------
13:19:32  Received interrupt.  Running AfterSuite...
13:19:32  ^C again to terminate immediately
13:19:34  
13:19:34  Ran 45 of 297 Specs in 4082.881 seconds
```

That's a 40 minute gap between anything visible happening! Plus, to make things worse, we don't gather logs because the suite itself times out.

Something must be getting stuck in our code. Perhaps we can use some `context.WithTimeout` to handle these cases to debug this further?

**Comment by ianvernon** [comment]
List of current failures in master:

*  https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2743/execution/node/90/
* https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2744/execution/node/91/log/
* https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6674/execution/node/91/log/
* https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6663/execution/node/91/log/
* https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/6661/

This always seems to occur during the Cilium preflight check.

**Comment by ianvernon** [comment]
Also affects v1.5:

* https://jenkins.cilium.io/view/Cilium-v1.5/job/cilium-v1.5-K8s-all/4/

**Comment by jrajahalme** [comment]
Here too: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11766/execution/node/83/log/

**Comment by jrajahalme** [comment]
`CiliumPreFlightCheck()` already uses `WithTimeout()`. The problem here is that the given timeout is not passed on to the "body", meaning that if "body" hangs, then the `WithTimeout()` call hangs as well. In this case the body is `ciliumPreFlightCheck()`. Note that propagating the timeout into the body  and all the functions that are executed there seems non-trivial. To gain some visibility on this maybe we could:

1. Instrument `ciliumPreFlightCheck()` with Ginkgo output before each step that would be visible in the console output even if no logs/files are collected? (Not fluent enough in Ginkgo to know how to do this)

2. Collect logs/files any time we need to interrupt a test run due to the overall timeout, assuming that the job that needed to be interrupted has been stuck. (Not fluent enough in Jenkins/Ginkgo to know if this is doable)

**Comment by raybejjani** [comment]
> Instrument ciliumPreFlightCheck() with Ginkgo output before each step that would be visible in the console output even if no logs/files are collected? (Not fluent enough in Ginkgo to know how to do this)

This should already be in "test_output.log" but, as you point out, we don't always collect it :( We had much more output in the jenkins console then people complained and we moved it all (so the problem is social, not technical, like all tech issues ;) ).

**Comment by raybejjani** [comment]
master: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2762

**Comment by raybejjani** [comment]
master: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2770/

These are variants that time out in GetCiliumPods (assuming that jrajahalme is correct, and I think he is).
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2772/
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2773/

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11858/execution/node/84/log/

**Comment by ianvernon** [comment]
I discussed this offline with @raybejjani , the following is a distillation of what we think is necessary:

The first thing we need to do is a change of `WithTimeout` to execute the function that it is executing with some timeout in an async manner, and closing on a channel based on the result. The problem is that the function is executed in the same goroutine as the one which handles the timeout logic. This is broken, because if the `body()` function hangs infinitely due to not using timeouts itself correctly, deadlocks, etc., the logic to exit on timeout will never actually be reached. We should instead do something like the following:


```
// WithTimeout executes body using the time interval specified in config until
// the timeout in config is reached. Returns an error if the timeout is
// exceeded for body to execute successfully.
func WithTimeout(body func() bool, msg string, config *TimeoutConfig) error {
    if config.Timeout < 10*time.Second {
        return fmt.Errorf("Timeout too short (must be at least 10 seconds): %v", config.Timeout)
    }
    if config.Ticker == 0 {
        config.Ticker = 5 * time.Second
    } else if config.Ticker < time.Second {
        return fmt.Errorf("Timeout config Ticker interval too short (must be at least 1 second): %v", config.Ticker)
    }

    bodyChan := make(chan bool)
    defer close(bodyChan)

    asyncBody := func(ch chan bool) {
        ch <- body()
    }

    go asyncBody(bodyChan)

    done := time.After(config.Timeout)
    //ticker := time.NewTicker(config.Ticker)
    //defer ticker.Stop()
    for {
        select {
        case success := <-bodyChan:
            if success {
                return nil
            }
            go asyncBody(bodyChan)
        case <-done:
            return fmt.Errorf("Timeout reached: %s", msg)
        }
    }
}
```

This removes the use of the ticker, but that could be re-added to have some type of rate-limiting if a command continuously fails. 

We should also update the `body` function used as a parameter within `WithTimeout` to take in a  `context.Context` here, as we pass `context` to functions to run SSH commands, etc., but using `context.Background()`. If those commands get stuck, the body function will never return and may leak resources.

**Comment by ianvernon** [comment]
https://github.com/cilium/cilium/pull/7865 was merged to address the test suite getting stuck. The test suites should fail if the preflight checks get stuck now (or anything using `WithTimeout` gets stuck, for that matter). This should help us debug what exactly is getting stuck since we should get logs now in such cases.

**Comment by raybejjani** [comment]
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2871/

**Comment by ianvernon** [comment]
The addition of more narration to the preflight check steps added in #8040 reveals that the preflight check always gets stuck after the line "Performing K8s service preflight check" is emitted to the console:

```
22:51:56  K8sFQDNTest 
22:51:56    Restart Cilium validate that FQDN is still working
22:51:56    /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
22:51:58  STEP: Installing DNS Deployment
22:51:58  STEP: Deploying etcd-operator
22:51:58  STEP: Installing Cilium
22:51:59  STEP: Installing Cilium-Operator
22:51:59  STEP: Waiting for all etcd-operator pods are ready
22:51:59  STEP: Performing Cilium preflight check
22:51:59  STEP: Performing Cilium status preflight check
22:52:00  STEP: Performing Cilium controllers preflight check
22:52:00  STEP: Performing Cilium health check
22:52:05  STEP: Performing Cilium service preflight check
22:52:05  STEP: Performing K8s service preflight check
22:52:06  STEP: Performing K8s service preflight check
22:52:29  STEP: Testing that connection from "app2-5c44ff87c-z8p42" to "http://world1.cilium.test" should work
22:52:29  STEP: Testing that connection from "app2-5c44ff87c-z8p42" to "http://world1.cilium.test" shouldn't work
22:52:35  STEP: Testing that connection from "app2-5c44ff87c-z8p42" to "http://world2.cilium.test" works
22:52:35  STEP: Testing that connection from "app2-5c44ff87c-z8p42" to "192.168.9.11" should not work
22:52:40  STEP: Deleting cilium pods
22:52:40  STEP: Testing connectivity when cilium is restoring using IPS without DNS
22:53:53  STEP: Performing Cilium preflight check
22:53:53  STEP: Performing Cilium status preflight check
22:53:53  STEP: Performing Cilium controllers preflight check
22:53:53  STEP: Performing Cilium health check
22:53:53  STEP: Performing Cilium service preflight check
22:53:53  STEP: Performing K8s service preflight check
00:01:11  Sending interrupt signal to process
00:01:31  After 20s process did not stop
```

Link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7026/execution/node/141/log/

The code for this part of the preflight check is here: https://github.com/cilium/cilium/blob/d083f789c96450cc91762f767cfbb7d4c5ada34a/test/helpers/kubectl.go#L2056-L2080

I suspect that the Ginkgo test suite is panicking here somehow, and we need to account for nil dereferences, which we are not doing in this function at this time.

We could add a `recover()` in a `defer` block at the start of this function to get additional data, and also in parallel add nil checks.

**Comment by nebril** [comment]
@ianvernon #8105 should help here, I did not find any more nil checks that could be added to `servicePreFlightCheck`, but if we get panic information from ginkgo that indicates that this occurs, we will know what happened.

**Comment by raybejjani** [comment]
:( this has happened again, albeit not in the preflight (it's the same thing, though, so I'll add it here).
https://jenkins.cilium.io/job/cilium-master-Nightly/191/

There is a stacktrace in there so I'll try to look into it a bit more.

**Comment by raybejjani** [comment]
This is now showing up pretty regularly :( stuck at  `STEP: Checking pod connectivity between nodes` and other places

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7209/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7197/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7212/

**Comment by ianvernon** [comment]
This is likely fixed by https://github.com/cilium/cilium/pull/8223 . I have a feeling that we will be seeing legitimate CI failures as a result.
