### ISSUE TITLE
Document what's possible with a compromised node

### ISSUE THREAD

**Issue by bobrik** [cilium/cilium#780]
Relevant documentation section:

* http://docs.cilium.io/en/latest/architecture/#arch-id-security

Cilium doesn't rely on centralized view of what is scheduled where to enforce policies, instead it uses container identities derived from labels. If I manage to compromise a single node, I can run anything I want and assign any labels I want. This in turn means, that I can access any container with my fake identity.

Does this sound right? In any case, it'd be nice to explain this part in documentation.

**Comment by tgraf** [comment]
> Does this sound right? In any case, it'd be nice to explain this part in documentation.

Yes, that is right. We rely on someone ensuring the integrity of the node itself. Going forward, we will add support for signing of the hash to ensure that the identity has not be tempered with. Avoiding that a compromised node performs identity theft will be a next step and I don't have specific ideas yet. We could potentially work together with Docker swarm and use their cluster protection. I haven't looked into whether something similar exists for Kubernetes.

Advice and ideas are certainly very welcome on this topic.

**Comment by bobrik** [comment]
I think it's achievable with a scalability compromise. Instead of checking just for identity, cilium could also check whether this identity is allowed to be in the node range where it's coming from. It's similar to IP address filtering described in the docs and has similar drawbacks, but has slightly better scalability if you have multiple services with the same identity per host, because you check IP ranges instead of separate IPs.

* IP address filtering: need to distribute what IPs belong to what, filter on IP.
* Identity based filtering: need to distribute identity, filter on identity.
* Identity + scheduler filtering: need to distribute identity and what node ranges allow what identities, filter on identity + check if identity is allowed from node range.

This only works if you only allow identity assignment from locked down nodes where scheduler runs. If a worker node is compromised, it can't gain more identities (no writes to the store should be allowed), and therefore can't gain more network privileges than it had before.
