### ISSUE TITLE
Cilium endpoint restore from ipv4-only to ipv6-only does not allocate IP address for pods

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7807]
Cilium master in v1.6 cycle.

Steps:

1. Create cluster with IPv4 enabled and IPv6 disabled
1. Deploy app into cluster
1. Change `ConfigMap` to disable IPv4 and enable IPv6
1. Observe warnings in the logs about not substituting symbols in the elf for `LXC_IP_1`, `LXC_IP_2`, ...

Basically the IPv6 address here is nil:

https://github.com/cilium/cilium/blob/3c71bc7b029899ad2c88ac82c55632e6c0d876e9/pkg/datapath/loader/template.go#L186-L192

**Comment by aanm** [comment]
I don't think the expectation should be that cilium would create new addresses for already going pods which might disrupt connectivity for already running pods.

**Comment by joestringer** [comment]
Why would it disrupt ongoing pod connectivity if we transition from no ipv6 -> having ipv6?

**Comment by aanm** [comment]
> Why would it disrupt ongoing pod connectivity if we transition from no ipv6 -> having ipv6?

The title of the GH issue specifies from `ipv4-only` to `ipv6-only` if I understood correctly, the v4 connectivity will be lost.

**Comment by joestringer** [comment]
> The title of the GH issue specifies from ipv4-only to ipv6-only if I understood correctly, the v4 connectivity will be lost.

Ah, sorry, my bad. The user would definitely be reconfiguring Cilium in a way that breaks connectivity in this case. What I'd expect is that if the user configures IPv4-only, then IPv6-only, then first the pod would get an IPv4 address and no IPv6 address, then when Cilium is reconfigured, we would give it an IPv6 address.

Currently the app would not work after Cilium redeployment until the user deletes/redeploys their app. If they're changing configurations in this way, then it's likely a test environment anyway where this isn't a big deal. I'll close this out.
