### ISSUE TITLE
daemonset failed: no such file /home/with-cni.sh

### ISSUE THREAD

**Issue by bretagne-peiqi** [cilium/cilium#781]
I deployed the ds file in the guide:  http://docs.cilium.io/en/latest/admin/#installing-cilium

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cilium-net-controller
spec:
  template:
    metadata:
      labels:
        name: cilium-net-controller
        io.cilium.admin.daemon-set: "cilium"
    spec:
      nodeSelector:
        with-network-plugin: cilium
      containers:
      - image: cilium/cilium:cilium-ubuntu-16-04
        imagePullPolicy: Always
        name: cilium-net-daemon
        command: [ "/home/with-cni.sh", "--debug", "daemon", "run" ]
        args:
          - "-t"
          - "vxlan"
          - "--etcd-config-path"
          - "/var/lib/cilium/etcd-config.yml"
          - "--k8s-kubeconfig-path"
          - "/var/lib/kubelet/kubeconfig"
        env:
          - name: "K8S_NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - name: cilium-run
            mountPath: /var/run/cilium
          - name: cni-path
            mountPath: /tmp/cni/bin
          - name: bpf-maps
            mountPath: /sys/fs/bpf
          - name: docker-socket
            mountPath: /var/run/docker.sock
            readOnly: true
          - name: etcd-config
            mountPath: /var/lib/cilium/etcd-config.yml
            readOnly: true
          - name: kubeconfig-path
            mountPath: /var/lib/kubelet/kubeconfig
            readOnly: true
          - name: kubeconfig-cert
            mountPath: /var/lib/kubernetes/ca.pem
            readOnly: true
        securityContext:
          capabilities:
            add:
              - "NET_ADMIN"
          privileged: true
      hostNetwork: true
      volumes:
        - name: cilium-run
          hostPath:
              path: /var/run/cilium
        - name: cni-path
          hostPath:
              path: /opt/cni/bin
        - name: bpf-maps
          hostPath:
              path: /sys/fs/bpf
        - name: docker-socket
          hostPath:
              path: /var/run/docker.sock
        - name: etcd-config
          hostPath:
              path: /var/lib/cilium/etcd-config.yml
        - name: kubeconfig-path
          hostPath:
              path: /var/lib/kubelet/kubeconfig
        - name: kubeconfig-cert
          hostPath:
              path: /var/lib/kubernetes/ca.pem

**result:**

root@cilium-3:/home/peiqi/cilium# kubectl logs cilium-net-controller-t4lwf 
container_linux.go:247: starting container process caused "exec: \"/home/with-cni.sh\": stat /home/with-cni.sh: no such file or directory"
root@cilium-3:/home/peiqi/cilium# docker images
REPOSITORY                       TAG                   IMAGE ID            CREATED             SIZE
cilium/cilium                    cilium-ubuntu-16-04   0d4900c17cb6        30 hours ago        520.4 MB

**Comment by aanm** [comment]
@peiqi-caicloud I see that you close this issue, is this still an issue or you were able to solve it?

**Comment by bretagne-peiqi** [comment]
Hello, thank you for your response.
I saw @tgraf committed the patch https://github.com/cilium/cilium/commit/7ebeeb9c430a2d2137c54fd87e2bb1f75d576f0f

So I think this ds is out of date: command: [ "/home/with-cni.sh", "--debug", "daemon", "run" ].
