### ISSUE TITLE
Cilium metrics report endpoints in "restoring" state after they become ready

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7868]
Reported by luanguimaraesla in Slack.

In Cilium v1.4.4, it appears that after upgrade from v1.4.3 and the cluster has run for 12 hours or more, there may still be Cilium instances that have pods with `endpoint_state="restoring"`. This should not happen.

May potentially also affect v1.5.x.

**Comment by joestringer** [comment]
I'm seeing 31 total endpoints in the related bugtool, with 31 in `cilium_endpoint_state="ready"` and 23 in `cilium_endpoint_state="restoring"` state. This doesn't add up to 31, so perhaps it's just that the metric is not properly decremented when shifting from `restoring` into another state.

**Comment by aanm** [comment]
@joestringer yes it is the metric. I saw during my scale testing but I couldn't find the problem with why the metric was wrong.

Does this gives any clue?

https://github.com/cilium/cilium/blob/e6e5133c6a06bd50f80ae5f7ec4fb19fd83e4ef4/pkg/endpoint/endpoint.go#L1603-L1607

**Comment by joestringer** [comment]
Interesting, yeah this may give some clue. Perhaps we actually set an endpoint into restoring twice (or another state first), and second/subsequent sets into restoring increment the count without a corresponding decrement?
