### ISSUE TITLE
CI: DEBUG not in output of monitor

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#7872]
Message: "Timeout reached: DEBUG: is not in the output after timeout"

Failure link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2791/testReport/junit/(root)/Suite-runtime/RuntimeMonitorTest_With_Sample_Containers_Cilium_monitor_event_types/

**Comment by raybejjani** [comment]
Comparing the output of the same test when it succeeds or fails monitor seems to run correctly, but no traffic happens:
```
cmd: "cilium monitor --type capture -v" exitCode: 0 duration: 10.357093484s stdout:
Listening for events on 2 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
^C
Received an interrupt, disconnecting from monitor...
```
[success](https://github.com/cilium/cilium/files/3127492/test-output.log)
[fail](https://github.com/cilium/cilium/files/3127494/test-output.log)

**Comment by raybejjani** [comment]
edit: nevermind. This is a runtime test so this cannot be true.

Looking at this a little more, all the failures seem to be on K8s=1.10 and `NETNEXT=true`. This roughly correlates with the oldest instance of this failure (commit 4be6b7cf3d518f0a04d344b9adc652d211da4eb6).

I'll disable this test for now, but also try to run the tests with that commit reverted.

**Comment by raybejjani** [comment]
Disabled in https://github.com/cilium/cilium/pull/7874
