### ISSUE TITLE
Support L3 dependent L4 policy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#789]
- [x] Extend BPF with the ability
  - Option 1: map in map lookup
  - Option 2: embed a fixed array in L3 policy map
  - Option 3: tail call to source specific section (memory hungry)
- [x] Represent this in the policy model

**Comment by ashwinp** [comment]
Related issue: https://github.com/cilium/cilium/issues/1496

**Comment by tgraf** [comment]
Duplicate of #1496
