### ISSUE TITLE
Do we have a config guide  about overlay/direct networking for multi-host  

### ISSUE THREAD

**Issue by bretagne-peiqi** [cilium/cilium#793]
I setup a multi host environs for k8s cluster, the devices host_vxlan host_net, host_cilium are setup by default.  I found connection between containers in different node not work, neither between container and host.

**Comment by bretagne-peiqi** [comment]
do we have an overlay network topology for multi host ? @tgraf  @aanm

**Comment by tgraf** [comment]
@peiqi-caicloud Yes, running with `-t vxlan` will enable overlay mode using VXLAN. Cilium will use the first public IPv4 address it finds as the VXLAN VTEP.

**Comment by bretagne-peiqi** [comment]
Hello, I have several questions:
1. in my vxlan_cilium device, there is no ip, is it normal ？ from the dump, the packets arrive at vxlan_cilium, but it does not do encapsulation, I am thinking it dropped the packet?  Am i missed some configuration for that? I read some code like bpf_overlay.c but I have not found related code.  @aanm @tgraf   any advice is welcome 

2 what is gre0 and gretap devices used for, cause I saw them in container netns.

**root@cilium-3:/home/peiqi# tcpdump -i cilium_vxlan -nee**
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on cilium_vxlan, link-type EN10MB (Ethernet), capture size 262144 bytes
22:53:16.580859 42:28:cf:a3:99:92 > fe:8f:0e:cf:aa:a7, ethertype IPv4 (0x0800), length 98: 10.183.0.173 > 10.182.0.173: ICMP echo request, id 48, seq 346, length 64
22:53:17.581462 42:28:cf:a3:99:92 > fe:8f:0e:cf:aa:a7, ethertype IPv4 (0x0800), length 98: 10.183.0.173 > 10.182.0.173: ICMP echo request, id 48, seq 347, length 64
22:53:18.582748 42:28:cf:a3:99:92 > fe:8f:0e:cf:aa:a7, ethertype IPv4 (0x0800), length 98: 10.183.0.173 > 10.182.0.173: ICMP echo request, id 48, seq 348, length 64
22:53:19.583976 42:28:cf:a3:99:92 > fe:8f:0e:cf:aa:a7, ethertype IPv4 (0x0800), length 98: 10.183.0.173 > 10.182.0.173: ICMP echo request, id 48, seq 349, length 64


**root@cilium-3:/home/peiqi# cilium monitor -d**
Listening for events on 4 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: 98 bytes Incoming packet from container ifindex 15170
Ethernet	{Contents=[..14..] Payload=[..90..] SrcMAC=42:28:cf:a3:99:92 DstMAC=fe:8f:0e:cf:aa:a7 EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=13813 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=60909 SrcIP=10.183.0.173 DstIP=10.182.0.173 Options=[] Padding=[]}
ICMPv4	{Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=63513 Id=48 Seq=519}
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT reverse lookup: sport=2048 dport=0 nexthdr=1 flags=1
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT lookup address: 10.182.0.173
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT lookup: sport=0 dport=2048 nexthdr=1 flags=0
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT entry found lifetime=360, proxy_port=0 revnat=0
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT verdict: Established, proxy_port=0 revnat=0
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: Encapsulating to node 179699713 (0xab60001) from seclabel 256
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: 98 bytes Incoming packet from container ifindex 15170
Ethernet	{Contents=[..14..] Payload=[..90..] SrcMAC=42:28:cf:a3:99:92 DstMAC=fe:8f:0e:cf:aa:a7 EthernetType=IPv4 Length=0}
IPv4	{Contents=[..20..] Payload=[..64..] Version=4 IHL=5 TOS=0 Length=84 Id=13853 Flags=DF FragOffset=0 TTL=64 Protocol=ICMPv4 Checksum=60869 SrcIP=10.183.0.173 DstIP=10.182.0.173 Options=[] Padding=[]}
ICMPv4	{Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=17172 Id=48 Seq=520}
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT reverse lookup: sport=2048 dport=0 nexthdr=1 flags=1
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT lookup address: 10.182.0.173
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT lookup: sport=0 dport=2048 nexthdr=1 flags=0
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT entry found lifetime=360, proxy_port=0 revnat=0
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: CT verdict: Established, proxy_port=0 revnat=0
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: Encapsulating to node 179699713 (0xab60001) from seclabel 256
CPU 00: MARK 0x430e008f FROM 38061 DEBUG: 98 bytes Incoming packet from container ifindex 15170


**root@cilium-3:/home/peiqi# ip a**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:06:18:32 brd ff:ff:ff:ff:ff:ff
    inet 10.35.48.183/22 brd 10.35.51.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe06:1832/64 scope link 
       valid_lft forever preferred_lft forever
3: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
4: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
5: gre1@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1476 qdisc noqueue state UNKNOWN group default qlen 1000
    link/gre 10.35.48.183 peer 10.35.59.1
    inet 192.168.84.183/24 scope global gre1
       valid_lft forever preferred_lft forever
    inet6 fe80::5efe:a23:30b7/64 scope link 
       valid_lft forever preferred_lft forever
9: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:6f:3e:36:04 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:6fff:fe3e:3604/64 scope link 
       valid_lft forever preferred_lft forever
15162: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:8b:0e:2d:a7:80 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::ec8b:eff:fe2d:a780/64 scope link 
       valid_lft forever preferred_lft forever
15163: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 6e:77:74:22:e1:17 brd ff:ff:ff:ff:ff:ff
    inet 10.183.0.1/32 scope global cilium_host
       valid_lft forever preferred_lft forever
    inet6 f00d::a23:30b7:0:ffff/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::6c77:74ff:fe22:e117/64 scope link 
       valid_lft forever preferred_lft forever
15164: cilium_vxlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 42:9c:bf:20:21:7d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::409c:bfff:fe20:217d/64 scope link 
       valid_lft forever preferred_lft forever
15170: lxc71a94@if15169: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether fe:8f:0e:cf:aa:a7 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::fc8f:eff:fecf:aaa7/64 scope link 
       valid_lft forever preferred_lft forever
15174: lxc00076@if15173: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 96:16:59:0a:3b:14 brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::9416:59ff:fe0a:3b14/64 scope link 
       valid_lft forever preferred_lft forever
15178: lxcc556f@if15177: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether da:7d:0d:1e:49:de brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::d87d:dff:fe1e:49de/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by tgraf** [comment]
> in my vxlan_cilium device, there is no ip, is it normal ？ from the dump, the packets arrive at vxlan_cilium, but it does not do encapsulation, I am thinking it dropped the packet? Am i missed some configuration for that? I read some code like bpf_overlay.c but I have not found related code. @aanm @tgraf any advice is welcome

This is correct. Cilium uses the VXLAN device in metadata mode which means it can send and receive on multiple addresses. The packets you see on `vxlan_cilium` are not yet encapsulated or already decapsulated. You can see the encapsulated packets on the underlying ethernet device, e.g. `eth0` or `enp0s3`.

> 3: gre0@NONE: mtu 1476 qdisc noop state DOWN group default qlen 1000
> link/gre 0.0.0.0 brd 0.0.0.0
> 4: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
> link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
> 5: gre1@NONE: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1476 qdisc noqueue state UNKNOWN group default qlen 1000
> link/gre 10.35.48.183 peer 10.35.59.1
> inet 192.168.84.183/24 scope global gre1
> valid_lft forever preferred_lft forever
> inet6 fe80::5efe:a23:30b7/64 scope link
> valid_lft forever preferred_lft forever

These are not created by Cilium.

**Comment by bretagne-peiqi** [comment]
@tgraf  hello, what mechanism do we use to populate the VTEP entries as control plane ?  does it rely on the etcd server ?  In my case, I found cilium_vxlan device can't find the destination node and encapsulate with my gateway address...

**Comment by tgraf** [comment]
> what mechanism do we use to populate the VTEP entries as control plane ? does it rely on the etcd server ? In my case, I found cilium_vxlan device can't find the destination node and encapsulate with my gateway address...

The Cilium addressing model allows to derive the node address from each container address. This is also used to derive the VTEP address which means you do not need to run a control plane protocol to distribute these addresses. All you need to have are routes to make the node addresses routeable.

**Comment by bretagne-peiqi** [comment]
> to derive the node address from each container address.

@tgraf  I am sorry, but I have not yet to reach network connectivity between different containers in different nodes.  Have you implemented this function?  I have not seen the code. "IPV4 derive" ?

I run 6 pods in 3 different nodes, 
following are strange points to me (I did nothing for policy part, and run pods without CiliumLabel...):

**first**: all containers get an identity of 260, same "SECLABEL", is it normal ?

and the route in container: 
 **# ip r**
default via 10.183.0.1 dev eth0 
10.183.0.1 dev eth0 scope link 
which is strange to me for the LAN part (**not 10.183.0.0/16 dev eth0** ... ?).

**what I captured after ping from a container to another in a different node.** (I am thinking the cilium_vxlan device **has not derived the good dst node address（10.35.48.181） from dst container address (10.181.0.173)? )**
root@cilium-3:~ tcpdump -i ens3 icmp -nne
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on ens3, link-type EN10MB (Ethernet), capture size 262144 bytes
05:19:45.639935 **70:3d:15:52:96:93** > 52:54:00:06:18:32, ethertype IPv4 (0x0800), length 70: 170.168.3.2 > 10.35.48.183: ICMP time exceeded in-transit, length 36
05:19:45.826687 70:3d:15:52:96:93 > 52:54:00:06:18:32, ethertype IPv4 (0x0800), length 70: 170.168.3.2 > 10.35.48.183: ICMP time exceeded in-transit, length 36
05:19:46.616261 70:3d:15:52:96:93 > 52:54:00:06:18:32, ethertype IPv4 (0x0800), length 70: 170.168.3.2 > 10.35.48.183: ICMP time exceeded in-transit, length 36
05:19:46.830740 70:3d:15:52:96:93 > 52:54:00:06:18:32, ethertype IPv4 (0x0800), length 70: 170.168.3.2 > 10.35.48.183: ICMP time exceeded in-transit, length 36
4 packets captured
6 packets received by filter
0 packets dropped by kernel
root@cilium-3:~# arp -a
cilium-2 (10.35.48.182) at 52:54:00:d0:2b:48 [ether] on ens3
gateway (10.35.51.254) at **70:3d:15:52:96:93** [ether] on ens3
cilium-1 (10.35.48.181) at 52:54:00:70:8b:b4 [ether] on ens3

**node_config.h file in /var/run/cilium/state/global/..**
/*
 * Node-IPv6: f00d::a23:30b7:0:0
 * Host-IPv6: f00d::a23:30b7:0:ffff
 * Host-IPv4: 10.183.0.1
 */

#define ENABLE_IPV4
#define NODE_ID 0xa2330b7
#define ROUTER_IP { 0xf0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0x23, 0x30, 0xb7, 0x0, 0x0, 0x0, 0x0 }
#define IPV4_GATEWAY 0x100b70a
#define IPV4_LOOPBACK 0xee1cb70a
#define IPV4_RANGE 0xb70a
#define IPV4_MASK 0xffff
#define IPV4_CLUSTER_RANGE 0xa
#define IPV4_CLUSTER_MASK 0xff
#define NAT46_PREFIX { .addr = { 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0 } }
#define HOST_IP { .addr = { 0xf0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0x23, 0x30, 0xb7, 0x0, 0x0, 0xff, 0xff } }
#define HOST_ID 1
#define WORLD_ID 2
#define LB_RR_MAX_SEQ 31
#define HOST_IFINDEX 4
#define HOST_IFINDEX_MAC { .addr = {0x56,0xd9,0xc0,0x49,0x91,0x73}}
#define ENCAP_VXLAN 1
#define ENCAP_IFINDEX 6

Because I am the only engineer who work on the network part in my side, So could please do me a favor.

**Comment by bretagne-peiqi** [comment]
besides, I found #define IPV4_GATEWAY 0x100b70a is in little endian,  does it work as designed ?.

**Comment by bretagne-peiqi** [comment]
I think the ipv4 derive is not yet completed, I will take it.
