### ISSUE TITLE
Update Cilium version in kops

### ISSUE THREAD

**Issue by brb** [cilium/cilium#7933]
The latest version of kops installs the very old version of Cilium - `v1.0` (see https://github.com/kubernetes/kops/blob/master/pkg/apis/kops/networking.go#L146).

We have spotted in the wild some users running Cilium v1.0 and asking for help. Also, some have raised a concern about the old version in kops in the Cilium users survey: https://cilium.io/blog/2019/05/03/cilium-user-survey-march-2019#additional-feedback-provided.

In addition, we need to update our kops guide as well: https://docs.cilium.io/en/stable/gettingstarted/k8s-install-kops/#installation-using-kops as it points to an old version of kops.

We might need to include the cilium-etcd-operator into the kops Cilium installation, as according to a user: `Probably worth waiting for cilium 1.6 with CRDs. That will make it easier to provision cilium given that kops k8s etcd cluster is not accessible anymore` ([link](https://cilium.slack.com/archives/C53TG4J4R/p1557212981111800?thread_ts=1557211552.109600&cid=C53TG4J4R)).

**Comment by brb** [comment]
See the linked thread on Slack about more problems with cilium-etcd-operator raised by @olemarkus.

**Comment by olemarkus** [comment]
You can close this one now 😊
