### ISSUE TITLE
Stop supporting legacy services

### ISSUE THREAD

**Issue by brb** [cilium/cilium#7967]
For Cilium v1.6 we should stop supporting legacy services introduced in #7540 for the backward-compatibility. This would allow us to:

- Reduce memory footprint (no need for the legacy LB service BPF maps).
- Increase performance of lxc egress path.
- Improve stability (e.g. failures when updating the legacy maps can prevent from updating the v2 maps).
- Reduce complexity of the related code.

Ideally, this should be done at the later stage of the v1.6 cycle, as otherwise, any backporting to v1.5 of the svc related changes will cause a lot of burden. 

After implementing this, users will be no longer able to upgrade Cilium from < v1.5 to v1.6 without terminating established connections.

**Comment by aanm** [comment]
This should probably be pushed to v1.7.0 as we will support upgrade from v1.3 to v1.6

**Comment by joestringer** [comment]
We discussed during today's Cilium developer meeting that the potential impact of this on 1.3->1.6 upgrade would be disruption of long-lived connections. Applications would be able to reconnect and re-establish connectivity. In general, we do not specifically support the 1.4 or earlier ->1.6 direct upgrade path, we document that users should upgrade to each minor release 1.3 -> 1.4 -> 1.5 -> 1.6. That said, even in that case, persistent long-lived connections would be disrupted in the same way so it should not affect the deprecation timeline of this option. To minimize disruption, users could upgrade to 1.5 with the option enabled, then run it for a while, and turn it off / upgrade to 1.6.

We do need to document this, however.
