### ISSUE TITLE
seems cilium daemon cann't connect to etcd client

### ISSUE THREAD

**Issue by bretagne-peiqi** [cilium/cilium#798]
I configure cilium as follows:
ExecStart=/usr/bin/daemon --kvstore etcd --kvstore-opt etcd.address=http://10.35.48.183:2379 --ipv4-range="10.183.0.1/16"

then: 

the service is blocked at "Waiting for etcd client to be ready..."
● cilium.service - cilium
   Loaded: loaded (/lib/systemd/system/cilium.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-05-22 04:45:17 PDT; 22min ago
     Docs: https://github.com/cilium/cilium
 Main PID: 4072 (daemon)
    Tasks: 10 (limit: 4915)
   Memory: 106.8M
      CPU: 55min 29.288s
   CGroup: /system.slice/cilium.service
           └─4072 /usr/bin/daemon --etcd=http://10.35.48.183:2379 --ipv4-range=10.182.0.1/16

May 22 04:45:17 cilium-2 daemon[4072]: 2017-05-22T04:45:17-07:00 INFO Cilium 0.8.2 4ff751a Thu, 13 Apr 2017 05:52:06 +0200 go version go1.7.5 linux/amd64
May 22 04:45:17 cilium-2 daemon[4072]: 2017-05-22T04:45:17-07:00 INFO Checking minimal requirements...
May 22 04:45:17 cilium-2 daemon[4072]: 2017-05-22T04:45:17-07:00 INFO clang 3.8.x version: OK!
May 22 04:45:17 cilium-2 daemon[4072]: 2017-05-22T04:45:17-07:00 INFO libraries: OK!
May 22 04:45:18 cilium-2 daemon[4072]: 2017-05-22T04:45:18-07:00 INFO BPF Verifier: OK!
May 22 04:45:18 cilium-2 daemon[4072]: 2017-05-22T04:45:18-07:00 INFO Valid label prefix configuration:
May 22 04:45:18 cilium-2 daemon[4072]: 2017-05-22T04:45:18-07:00 INFO  - :id.
May 22 04:45:18 cilium-2 daemon[4072]: 2017-05-22T04:45:18-07:00 INFO  - :io.cilium.
May 22 04:45:18 cilium-2 daemon[4072]: 2017-05-22T04:45:18-07:00 INFO  - k8s:io.kubernetes.pod.namespace
May 22 04:45:18 cilium-2 daemon[4072]: 2017-05-22T04:45:18-07:00 INFO Waiting for etcd client to be ready...

I use etcd version: 3.1.4 and my k8s service can connect to it. 

Any suggestions ？

**Comment by knightXun** [comment]
I met this error too.

**Comment by tgraf** [comment]
I just tried in minikube and it worked fine.  Does it eventually error out? (connection timed out?)

**Comment by ianvernon** [comment]
It looks like you are using the 0.8.2 release of Cilium:
```May 22 04:45:17 cilium-2 daemon[4072]: 2017-05-22T04:45:17-07:00 INFO Cilium 0.8.2 4ff751a Thu, 13 Apr 2017 05:52:06 +0200 go version go1.7.5 linux/amd64```

But with the configuration options used in the 0.8.9 version (i.e., master) of Cilium for key-value store.

**Comment by bretagne-peiqi** [comment]
@ianvernon yes, I used 0.8.2 release at first, then I build the master and replace daemon and cilium binaries. with new kvstore-opts..., but it seems has no change.

**Comment by bretagne-peiqi** [comment]
@tgraf, It simply blocked and has now error messages.  I tested with bad config, e.x. --kvstore-opt EAADR=http://10.35.48.183:2379, then it failed to start and print error message.

 It receives no reponse from concurrency.NewSession. I am not sure the problem is from cilium, config or etcd version.  I build the master with go 1.7.4

	log.Info("Waiting for etcd client to be ready...")
	**s, err := concurrency.NewSession(c)**
	if err != nil {
		return nil, fmt.Errorf("Unable to contact etcd: %s", err)
	}
	log.Info("Etcd client ready")

**Comment by tgraf** [comment]
> It receives no reponse from concurrency.NewSession. I am not sure the problem is from cilium, config or etcd version. I build the master with go 1.7.4

Given that you closed this issue, did you find the root of the issue, is it a Cilium issue?

**Comment by bretagne-peiqi** [comment]
@tgraf thanks. 
I rebuild the master and it works but I don't know why...  I dont think it related to Cilium code, because depends the strace, it was blocked by etcdv3 Client.
