### ISSUE TITLE
K8sServicesTest fail due to timeout

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#7995]
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2865/

**Comment by brb** [comment]
```
Timeout reached: timed out waiting for pods with filter  to be ready
```

Yet another example where some Pods are removed and `WaitforNPods` is waiting for them nevertheless. Having something like https://github.com/cilium/cilium/pull/7993#discussion_r283611833 would eliminate such flakes.

Also, it would be good if you include the test dump into the Github issue, as the dumps get removed in Jenkins after awhile.

[c23c97af_K8sServicesTest_External_services_To_Services_first_endpoint_creation.zip](https://github.com/cilium/cilium/files/3176741/c23c97af_K8sServicesTest_External_services_To_Services_first_endpoint_creation.zip)
