### ISSUE TITLE
CI: write ^C error: EOF

### ISSUE THREAD

**Issue by brb** [cilium/cilium#8003]
It has been observed, that the test executor output logs contain many `write ^C error: EOF` errors. E.g.:

```
time="2019-05-10T19:46:27Z" level=error msg="write ^C error: EOF"
time="2019-05-10T19:46:27Z" level=error msg="write ^C error: EOF"
time="2019-05-10T19:46:32Z" level=debug msg="running command: kubectl -n default get pods  -o json"
cmd: "kubectl -n default get pods  -o json" exitCode: 0 duration: 73.49103ms stdout:
{
<..>
```
@raybejjani says:

> I added cancellable contexts to commands without a timeout so a bunch of goroutines that would block forever now actually do something. In this case, it does this. Sadly, I haven't figured out why https://github.com/cilium/cilium/pull/7847 so it'll be a little time before I fix the ordering

While these appear to be harmless, they pollute test executor output quite a lot.

**Comment by ianvernon** [comment]
@brb are you still observing this? I did a lot of work around fixing up how we are handling SSH session timeouts in the CI a few months ago; this should be resolved.

**Comment by brb** [comment]
I've just checked some test outputs of some test runs, and I don't see any `write ^C error: EOF` messages. Thanks.
