### ISSUE TITLE
bad ip define comment in header when v6 is disabled

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#8032]
Looks harmless, but found in one the lxc_configs.h.  In the comment above the v6 was: ` * IPv6 address: ` (none). And later it wrote for `LXC_IP`: `/* BUG: bad ip define LXC_IP  */`

**Comment by joestringer** [comment]
Looks like it the write of this variable in `writeStaticData` (and also for IPv4) needs to be triggered upon enablement of ipv4/ipv6 in the options.
