### ISSUE TITLE
[needs triage] [1.5] Refcount leak in lbmap backends during restore

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#8078]
I noticed that when we restore services, we don't increment the refcount for the backend in [lbmapCache.addBackendIDs](https://github.com/cilium/cilium/blob/master/pkg/maps/lbmap/bpfservice.go#L370-L377). The callchain is:
[daemon/daemon.go:NewDaemon](https://github.com/cilium/cilium/blob/master/daemon/daemon.go#L1011)
[daemon/loadbalancer.go:restoreServices](https://github.com/cilium/cilium/blob/master/daemon/loadbalancer.go#L843)
[lbmap.AddBackendIDsToCache](https://github.com/cilium/cilium/blob/master/pkg/maps/lbmap/https://github.com/cilium/cilium/blob/master/pkg/maps/lbmap/bpfservice.go#L898-L900)
[lbmapCache.addBackendIDs](https://github.com/cilium/cilium/blob/master/pkg/maps/lbmap/bpfservice.go#L370-L377)

Later in daemon/loadbalancer.go:restoreServices we call [lbmap.UpdateService](https://github.com/cilium/cilium/blob/master/pkg/maps/lbmap/lbmap.go#L250) and that calls  l[bmapCache.prepareUpdate](https://github.com/cilium/cilium/blob/master/pkg/maps/lbmap/bpfservice.go#L251). In lbmapCache.prepareUpdate we remove deleted backends that are no longer used. Note that we check if `count == 1` to do this.

If we restore services & backends, and then add and remove other services that use these backends, would we end up with a refcount 1 less than it should be, and would delete the restored backends too early?

@brb I assigned to you only so you see it. I have no proof this is happening.

**Comment by aanm** [comment]
@raybejjani we have been tracking something related with this for the last week. Do you have any debug logs? @brb wants debug logs badly.

**Comment by brb** [comment]
Thanks! I'm triaging it.

**Comment by raybejjani** [comment]
@aanm alas, no, I was looking at all this code because we were tracking this. :/

**Comment by brb** [comment]
I think this issue is invalid, as `lbmapCache.addBackendIDs()` populates only `lbmap.backendIDByAddr`, and any to-be restored service goes through `lbmap.UpdateService` which does the refcounting of backends:

```
$ cilium service update --frontend '1.2.3.4:6666' --backends '10.1.50.164:80,10.1.118.18:80' --id 1234
Creating new service with id '1234'
Added service with 2 backends

# <-- restart cilium -->

$ cilium service update --frontend '1.2.3.5:6666' --backends '10.1.50.164:80,10.1.118.19:80' --id 1235
Creating new service with id '1235'
Added service with 2 backends

$ cilium service delete 1235
Service 1235 deleted successfully
$ sudo cilium bpf lb list # <-- checks whether backend exists in the cilium_lb4_backends map; reports "backend $ID not found" if it doesn't.

SERVICE ADDRESS   BACKEND ADDRESS
1.2.3.4:6666      10.1.118.18:80 (1234)
                  10.1.50.164:80 (1234)
                  0.0.0.0:0 (1234)
```
