### ISSUE TITLE
Use more efficient data structures to maintain IPAM blacklist

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#8120]
The IPAM blacklist is currently maintained as hash table for individual IPs. This is inefficient if large subnets are being blacklisted. Use a list of `net.IPNet` or similar to represent the blacklist more efficiently. The current approach consumes about 6MB of memory:

```
 4624.55kB 28.03% 28.03%  5136.56kB 31.14%  github.com/cilium/cilium/pkg/ipam.(*IPAM).Blacklist
 2048.06kB 12.41% 40.45%  7184.62kB 43.55%  github.com/cilium/cilium/pkg/ipam.(*IPAM).reserveLocalRoutes
```

**Comment by fristonio** [comment]
Hey @tgraf the Blacklist method for IPAM takes in an ip address and adds it to the blacklist. If I understand the issue correctly then we want to be able to blacklist a complete IPNet right?
If so how are we going to handle situations like if individual IPs are blacklisted first and then the whole subnet is blacklisted the older entries should not be present. Also, how are we going to aggregate individual IPs blacklisted to an IPNet?

**Comment by tgraf** [comment]
@fristonio Correct, the primary use case is:

```
func (ipam *IPAM) reserveLocalRoutes() {
[...]
        routes, err := netlink.RouteList(nil, netlink.FAMILY_V4)
[...]
        for _, r := range routes {
[...]
                for ip := r.Dst.IP.Mask(r.Dst.Mask); r.Dst.Contains(ip); nextIP(ip) {
                        ipam.Blacklist(ip, "local route: "+r.Dst.String())
                }
       }
[...]
}
```

For the above, unrolling the route is pointless.

We can maintain a list of `net.IPNet` which can handle subnets but also individual IPs with a mask of `/32` respectively `/128`.

**Comment by tgraf** [comment]
Blacklist does not need to solve the case where an already allocated IP is then blacklisted, blacklisting always occurs before the first allocation happens.

**Comment by fristonio** [comment]
Ok, sounds good. I just have one more question, what happens if we try to find out if a rule is blacklisted or not we will have to iterate over the entire list of blacklisted IPNets. This will be of O(n) complexity in contrast to hash table with O(1).

**Comment by tgraf** [comment]
@fristonio Worst case, yes. The majority will be large subnets in which case it will iterate over a small number of subnets and then use `Contains()`. One option is to maintain both a list and a hash table and push subnets into the list and individual IPs into the hashtable.

**Comment by fristonio** [comment]
Maintaining both a hashmap and a list of IPNet seems more reasonable to me. To check if an IP is blacklisted we can first check in hashmap and then in the blocked subnet list iteratively.
If this sounds good I would like to work on the issue :sweat_smile:
