### ISSUE TITLE
[NetPol] Allow ICMP messages of a certain type/code

### ISSUE THREAD

**Issue by jpmondet** [cilium/cilium#8129]
## Proposal / RFE

As discussed with @tgraf on Slack, I'm opening an issue :

**Is your feature request related to a problem?**

Yes, Path MTU Discovery breaks when applying L4 Network Policies since ICMP unreachable messages from routers in the path are filtered.

**Describe the solution you'd like**

It would be great to be able to allow all ICMP messages of a certain type (and/or with a certain code) to be allowed. Either with a specific policy, or with an option.

For example, being able to allow ICMP/type 3/code 4 (more details [here](https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml#icmp-parameters-codes-3)) would prevent MTU issues.

Thanks a lot !

**Comment by tgraf** [comment]
To simplify the initial implementation of this feature, I suggest we make it an agent option as it seems like the most likely use case for this is to allow this for all connections.

The implementation can use `#define` to indicate this mode and whitelist ICMPs of the specified types in `canAccess()` for ingress and egress.
