### ISSUE TITLE
reduce amount of time taken per-build by `writeHeaderfile` for each endpoint regeneration

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#8144]
This takes about 50 ms per endpoint regeneration. Figure out ways to not have to write the headerfile every time we do an endpoint regeneration - e.g., check if nothing has changed that matters to the endpoint's base64 representation. We could define some equality check which checks for these fields which matter. Only then would we actually write the headerfile. This would reduce writing of a lot of strings as well as file I/O. 

This affects policy performance because we cap the number of concurrent regenerations (which includes policy regeneration) to be equal to the number of CPUs. Every 50 ms taken for one build takes away 50 ms queued up for the next build!

*Tasks*

- [ ] Figure out what is causing this to take so long by doing some type of profiling of endpoints

**Comment by joestringer** [comment]
Using microk8s directly on my laptop, here are the values I was getting for a similar test:

![identity-churn-20190606-with-headerfile-breakdown](https://user-images.githubusercontent.com/1243336/59054896-819c3900-8849-11e9-9db9-5c08b61ab42b.png)

I also wrote some benchmarks (https://github.com/cilium/cilium/pull/8239), but in those I get much lower values, more like tens of microseconds per operation:

```
$ make bench TESTPKGS=pkg/endpoint
can't load package: package github.com/cilium/cilium/test/bpf: C source files not allowed when not using cgo or SWIG: bpf-event-test.c elf-demo.c unit-test.c
Starting key-value store containers...
a8a55ad236995b7b9b2591e04404eaf83ffc3a25aec0e5a47a85661871e35ae9
ef0361cd42b30a504183c1936bb2a83300015dc2c5b0f9b0a83dd3c9c96d6c21
goos: linux
goarch: amd64
pkg: github.com/cilium/cilium/pkg/endpoint
BenchmarkWriteInformationalComments-4              50000             25666 ns/op
BenchmarkWriteEndpointConfig-4                    200000             12052 ns/op
PASS
ok      github.com/cilium/cilium/pkg/endpoint   4.287s
can't load package: package github.com/cilium/cilium/test/bpf: C source files not allowed when not using cgo or SWIG: bpf-event-test.c elf-demo.c unit-test.c
cilium-etcd-test-container
cilium-consul-test-container
```

**Comment by joestringer** [comment]
OK, minor update, the graph above is likely from the 90th percentile regeneration; I'm now observing closer to 20ms headerfilePrep times under the 99th percentile. Seems like there's just a long tail where if filesystem write latency goes high, then we get a corresponding jump to the endpoint regeneration time.

We need the headerfile to be serialized *somewhere* to perform the check and determine whether existing, previously-compiled datapath template objects can be reused for this endpoint. Perhaps we could consider initially populating this information in an in-memory buffer, then perform the comparison, and defer writing this buffer to the filesystem, perhaps even completely decoupling it from the general regeneration cycle (at least in the common cases where recompilation is not necessary).
