### ISSUE TITLE
change "Allocating Key" logs to debug level

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#8162]
These are verbose - fix in v1.5 branch.

**Comment by tgraf** [comment]
@ianvernon It should only happen once when a new pod comes up. Are you seeing it more often?

**Comment by ianvernon** [comment]
@tgraf getting back to this finally. I think that having logs that scale proportionally to the presence of workloads being scheduled on a node should not be at `Info` level. IMO we should have info level logs for things like bootstrap and for operations which are one-offs throughout the agent's lifecycle. What do you think? I realize this is a matter of opinion, so if you feel differently than me, I'm fine closing this.

**Comment by tgraf** [comment]
@ianvernon I'm OK to change it to debug. I just wasn't sure whether there is an underlying bug that causes it to show up more frequently than it should.

**Comment by borancar** [comment]
This seems to be already implemented in 9b5ba08f135d36297c6f9b35c7ae70bce7197fbc. Is this issue solely about backporting it to a previous version?

**Comment by ianvernon** [comment]
@borancar you are right, closing.
