### ISSUE TITLE
grpc/http2 load balancing

### ISSUE THREAD

**Issue by stongo** [cilium/cilium#817]
Really interested in Cilium as an ingress controller and load balancer. does it proxy grpc and http/2?

**Comment by tgraf** [comment]
> Really interested in Cilium as an ingress controller and load balancer. does it proxy grpc and http/2?

We are currently integrating with envoy proxy which will bring grpc and http/2 support.

**Comment by danwent** [comment]
Hi @stongo , just an FYI that we posted a Cilium + gRPC getting-started-guide here: www.cilium.io/try-grpc  .  Feedback appreciated :)
