### ISSUE TITLE
CI: Test hang in post-test framework code (k8s1.14)

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#8175]
CI hung for an hour and a half during #8150 jenkins run during auto direct nodes routes datapathconfig test:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/12691/execution/node/136/log/

```
19:56:45  ------------------------------
19:56:45  K8sDatapathConfig DirectRouting 
19:56:45    Check connectivity with automatic direct nodes routes
19:56:45    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
19:57:23  STEP: Performing Cilium preflight check
19:57:23  STEP: Performing Cilium status preflight check
19:57:24  STEP: Performing Cilium controllers preflight check
19:57:24  STEP: Performing Cilium health check
19:57:28  STEP: Performing Cilium service preflight check
19:57:28  STEP: Performing K8s service preflight check
19:57:28  STEP: Waiting for all etcd-operator pods are ready
19:57:29  STEP: Making sure all endpoints are in ready state
19:57:30  STEP: Checking pod connectivity between nodes
19:57:35  === Test Finished at 2019-05-29T19:57:34Z====
21:31:09  Sending interrupt signal to process
21:31:12  cleaning up VMs started for k8s tests
```

Last message before hang is that the test finished, so this is likely a problem in the framework code from immediately after the test code itself is run. Not sure which of the ginkgo aftereach/afterall/etc. may be the culprit.

[test_results_Cilium-PR-Ginkgo-Tests-Validated_12691_BDD-Test-PR-K8s-1.14.zip](https://github.com/cilium/cilium/files/3237964/test_results_Cilium-PR-Ginkgo-Tests-Validated_12691_BDD-Test-PR-K8s-1.14.zip)

(The zip doesn't immediately seem very useful, this may be an issue where we have to insert additional logging into master and track over time)

**Comment by ianvernon** [comment]
@joestringer this should be fixed by the recent fixes surrounding correctly dealing with context deadlines / asynchronous SSH executions.

**Comment by joestringer** [comment]
Let's close, we can always re-open. With all the recent changes, even if it shows up again it may be an entirely different cause.
