### ISSUE TITLE
Fragmented UDP datagrams larger than MTU fail with service IPs

### ISSUE THREAD

**Issue by brichins** [cilium/cilium#8185]
## Bug report

**General Information**
When UDP datagrams larger than the MTU are sent to service IPs, Cilium does not successfully deliver fragmented packets.

- Cilium version: 1.5.1
- Kernel version: `Linux minikube 4.15.0 #1 SMP Tue May 21 00:14:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: kubernetes 1.14.2
- Upload a system dump -- attached

**How to reproduce the issue**
Steps to reproduce with minikube are shown running from a Mac but the behavior has been also observed on Linux clusters.

1. `minikube start --network-plugin=cni --memory=4096`
2. `kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/1.14/cilium-minikube.yaml`
3. Deploy attached openssl-server.yaml manifest.  This creates a service and deployment that generates a self signed certificate and runs `openssl s_server -cert cert.pem -key key.pem -dtls1_2 -accept 1111 -mtu $(MTU) -state -timeout`

```bash
kubectl apply -f openssl-server.yaml
```

4. Verify the OpenSSL pod successfully starts with `kubectl get pods` and `kubectl logs <podname>`
5.  Run `kubectl get pods -o wide` and record the IP of the openssl server pod
6.  Run `kubectl get services` and record the service ip for openssl
7.  Run `kubectl run -it --rm troubleshoot --image buildpack-deps:18.04`.  This will create an interactive terminal to run debugging commands from.
8. Exec into the troubleshoot container with `kubectl exec -it <podname> bash`
9. Run `echo "" | openssl s_client -dtls1_2 -connect ${OPENSSL_S_SERVER_SERVICE_HOST}:1111`.  The command will hang as the fragmented datagram from the service is lost.
10. Edit the `openssl-server.yaml` . change the MTU to 1024 and redeploy.
11.   Run `echo "" | openssl s_client -dtls1_2 -connect ${OPENSSL_S_SERVER_SERVICE_HOST}:1111`.  This time the command will succeed since the MTU size from the openssl s_server is less than the default MTU of 1500 and the packet is not fragmented.

**Comment by brichins** [comment]
Rename the openssl-server.txt to openssl-server.yaml

[openssl-server.txt](https://github.com/cilium/cilium/files/3242710/openssl-server.txt)
[cilium-sysdump-20190531-133949.zip](https://github.com/cilium/cilium/files/3242711/cilium-sysdump-20190531-133949.zip)

**Comment by brichins** [comment]
**Workaround:** Cilium community members recommended adding `--disable-k8s-services` to the cilium agent to force services to use kube-proxy as a workaround.  Tested this on minikube and Linux cluster and workaround proved to be successful.  

**Caveat:** I had to delete and recreate the services before it worked though.  I'm guessing I could have restarted the nodes or reset the cilium/bpf states instead.

Many thanks to @tgraf and @danwent for the help to find the workaround and troubleshooting this issue.

**Comment by brichins** [comment]
#6323 -- Wondering if this is related

**Comment by brichins** [comment]
@tgraf -- Any progress on this issue?  Hoping it doesn't get closed because it's stale.

**Comment by brichins** [comment]
Any progress on this?  Anything I can do to move the ball forward?

**Comment by danwent** [comment]
https://github.com/cilium/cilium/pull/10264  

CC @brichins

**Comment by brichins** [comment]
Looks like this was resolved with 1.7.  I just verified the problem is gone in this use case with cilium 1.7.4 and 1.8.0-rc1.  Thanks folks for fixing this.  Feel free to close this issue.
