### ISSUE TITLE
Clarification on event monitoring for auditing

### ISSUE THREAD

**Issue by chrismessiah** [cilium/cilium#8221]
## Support

Hi! In the *Monitoring and Troubleshooting* section of the docs, event monitoring with metadata is highlighted as a feature as follows:

_Event monitoring with metadata: When a packet is dropped, the tool doesn’t just report the source and destination IP of the packet, the tool provides the full label information of both the sender and receiver among a lot of other information._

To test this I have written a L3 `CiliumNetworkPolicy` and deployed it to a K8s cluster. I have tried `cilium monitor` as can be seen in the following example 

```
~# cilium monitor --type drop
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Policy denied (L3)) flow 0xd6b1738a to endpoint 2749, identity 57700->36043: 10.232.86.92:60734 -> 10.232.248.150:3000 tcp SYN
xx drop (Policy denied (L3)) flow 0x75296917 to endpoint 2749, identity 57700->36043: 10.232.86.92:60734 -> 10.232.248.150:3000 tcp SYN
```

My questions are

1. How do i get that _full label information_ and _a lot of other information_ which is mentioned above? Is it through `cilium monitor` or does `cilium monitor` only show a subset of the metadata?
2. Let's say the pod which corresponds to the identity 57700 is deleted. Is there any way to resolve which pod that had that identity? Is the identity still stored in the kv-store or will it be flushed? Basically the idea is to store the `cilium monitor` logs away and then look at them later when the pod might have been restarted, relocated or might not exist anymore.

Thanks!

**Comment by danwent** [comment]
Hi @chrismessiah .   The source and destination identities listed in each row of monitor output (identity 57700->36043 in your example above) can be directly mapped to the full labels using the following command: 

```
cilium identity get <numeric identity>
```

Printing each label for each line would be extremely verbose.   

Here is an example from my setup of monitor output and the corresponding identity get output: 

```
# cilium monitor
Listening for events on 1 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
-> endpoint 3717 flow 0x9a568d09 identity 101->101 state established ifindex lxc6d265bb069c4: 10.44.2.65:60282 -> 10.44.0.182:2380 tcp ACK
^C
Received an interrupt, disconnecting from monitor...

root@gke-cluster1-default-pool-cf3a0d17-c49k:~# cilium identity get 101
ID    LABELS
101   k8s:app=etcd
      k8s:etcd_cluster=cilium-etcd
      k8s:io.cilium.k8s.policy.cluster=default
      k8s:io.cilium.k8s.policy.serviceaccount=default
      k8s:io.cilium/app=etcd-operator
      k8s:io.kubernetes.pod.namespace=cilium
```

Identities are also available programmatically via the cilium api.    

Identities will only exist for the lifetime of of the workloads using that identity, and in certain circumstances, for example, the loss of an etcd cluster, might change.    So in general, the identities must be persistent along with the flow data. 

Isovalent, the company behind cilium, has a commercial product that provides a mgmt plane on top of cilium that solves these and many other kubernetes visibility and security challenges.   Would be happy to share more info if you're interested (https://cilium.io/contact-us) but we strive to keep cilium channels focused on Cilium itself.

**Comment by chrismessiah** [comment]
Thanks @danwent ! Thats neat really neat. While I suppose the logs could also be aggregated using fluentd/logstash and finally stored in elasticsearch I can imagine that the commercial product is more robust and more in-depth. 

I'm currently researching on the logging capabilities of K8s-compatible network implementations. While the commercial-track is not in scope for the moment it's great to know that Cilium is available with commercial support.

Closing this as my question was answered. Keep up the fantastic work 👍
