### ISSUE TITLE
Add testing with lower lease duration

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#8222]
Issues such as the one fixed in #8214 can be more easily found by lowering the lease duration and performing general connectivity testing with the lower lease duration. We should make the kvstore lease duration configurable and either add tests specifically for this case, or set it low in general across the testsuite.

**Comment by tgraf** [comment]
The values that need to become configurable are:
```
var (
        // LeaseTTL is the time-to-live ofthe lease
        LeaseTTL = 15 * time.Minute // 15 minutes

        // KeepAliveInterval is the interval in which the lease is being
        // renewed. This must be set to a value lesser than the LeaseTTL
        KeepAliveInterval = 5 * time.Minute
```

If `LeaseTTL` is made configurable, then `KeepAliveInternal` must be automatically calculated to be lesser than `LeaseTTL`, ideally by a factor of 3.

The patch file to modify the settings of default CI runs is here:
test/k8sT/manifests/cilium-cm-patch.yaml

When an option is introduced, the option can be set to a lower value in the above patch file.

**Comment by fristonio** [comment]
Should we add this option to `DaemonConfig` itself or update this once we have parsed the command line flags(This will make `pkg/options` depend on `pkg/kvstore`)?

**Comment by joestringer** [comment]
@fristonio I believe tit should be fine under `DaemonConfig`. `pkg/option` should have minimal dependencies, I don't think it should have a dependency on `pkg/kvstore`.
