### ISSUE TITLE
Improve memory & CPU consumption of connectivity health checks

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#8230]
The connectivity health checking is costly primarily from a memory consumption perspective:
 * Separate binary of 22M due to including health API, server and probe
 * Binary is being run twice for each node, one to serve the health API and run probes, once inside of a network namespace to simulate an endpoint, respond to probes and probe other endpoints.
 * Shell script continues running after setting up network namespace

**Comment by gandro** [comment]
Addressed via #8317, #8349, and #8376.
