### ISSUE TITLE
RuntimeMonitorTest monitor tests broken

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#8233]
It seems the monitor tests are broken although they never fail in the CI.

https://github.com/cilium/cilium/blob/625f93677695b33cd4c6e53511ddfe86cbc7d00c/test/runtime/monitor.go#L87-L112

Line 94 configures the cilium daemon to run in debug mode, after the endpoints were already configured. However the current implementation, (also tested with v1.3), does not configure the endpoints to also run with debug mode.

```
$ cilium config
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Enabled
DebugLB                  Disabled
DropNotification         Enabled
MonitorAggregationLevel  None
PolicyTracing            Disabled
TraceNotification        Enabled
k8s-configuration        
k8s-endpoint             
PolicyEnforcement        default
MonitorNumPages          64
```

```
$ cilium endpoint config 18349 
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Disabled
DebugLB                  Disabled
DropNotification         Enabled
MonitorAggregationLevel  None
NAT46                    Disabled
TraceNotification        Enabled
```

The test expects to see a DEBUG message in the cilium monitor with the ID of the endpoint but that can't, and shouldn't, ever happen as the endpoint is not running in debug mode. So the question is, how come the tests are passing?

**Comment by aanm** [comment]
The fix would probably fix the https://github.com/cilium/cilium/issues/8035 as well

**Comment by nebril** [comment]
Cilium runs in debug mode by default. I will remove setting debug to true in monitor tests to avoid confusion.

**Comment by ianvernon** [comment]
This isn't reproducing anymore when running the test against the `v1.3` branch locally.

**Comment by ianvernon** [comment]
Removing backport labels for the following reasons:
* v1.3 is going to be EOL'd with the release of v1.6
* v1.4 is moving to a security-fix-only backport model

**Comment by joestringer** [comment]
From my reading of the issue and the comments, this is expected behaviour: Cilium-agent is run in debug mode which overrides the endpoint debug mode.
