### ISSUE TITLE
CI coverage: parallel tests for different kernel/llvm/iproute2 versions.

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#824]
For nightly test runs, it would be awesome to run the cilium test suite in parallel on several instances to avoid time consuming manual testing of different combinations mentioned below.

Combinations:
- Every major kernel tree since 4.8, plus latest -net/-net-next git tree.
- Corresponding iproute2 versions to kernel.
- Every official LLVM release since 3.8.1 up to latest git tree.

**Comment by jrfastab** [comment]
+1 it would be awesome.

**Comment by ianvernon** [comment]
@borkmann can you please provide an answer / information regarding the following?
* Can you please provide an exact list of what versions we need for (kernel, LLVM, iproute2)? How many different combinations will this result in? I.e., for a given kernel version and its according iproute2 package, should I be running tests with a many different LLVM versions? 
* What tests should be ran as part of these different kernel tests? Should they be the same as what is ran for each PR along with performance / stress tests? Or should there be another set of tests entirely?

**Comment by borkmann** [comment]
@ianvernon @jrfastab Here's the list:

For kernels, the following list:

- Upstream kernels from https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/refs/
  - 4.8, 4.9, 4.10, 4.11, 4.12, 4.13 and every new major release coming in the future
- Stable kernels from https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/refs/
  - the latest 4.9.y, 4.13.y and every new stable tree in the future
- Development kernels from David Miller https://git.kernel.org/?q=davem
  - Latest net.git and net-next.git

For iproute2 from https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/refs/ it's enough to check iproute2 version that corresponds to the kernel version, so 4.8 kernel should run 4.8 iproute2 as that is the usual expectation. For net.git kernel tree, the master branch of iproute2 should be used https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/log/ . For net-next.git tree, the corresponding net-next branch should be used https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/log/?h=net-next .

For LLVM, I would ideally like to have it that for a specific kernel, we iterate over the test suite with different LLVM versions from http://releases.llvm.org/ starting with 3.8.1, 3.9.0, 3.9.1, 4.0.0, 4.0.1, 5.0.0 and future official releases as well as the latest code from the git tree https://github.com/llvm-mirror/llvm. For each, cilium should run in i) non-debug mode, ii) debug mode.

Initially, the test suite could just run the local cilium tests, but would be nice later on to extend this to be able to track performance data and run on multinode, but this shouldn't be in the initial scope. With that, this should provide sufficient coverage for BPF data path side to catch regressions.

**Comment by borkmann** [comment]
Almost completed by @scanf .

**Comment by ianvernon** [comment]
Would be useful to test latest llvm release from Git tree - allows for proactive fixing of issues in llvm before release. Main worry is that some users would deploy outside of the container that we control (is possible) - those users want LLVM version X, which we don't test, and it's DOA. Allows us to be proactive.

What do we need here?

- [ ] really simple basic connectivity test; load programs in kernel, pass traffic through.
- [ ] trigger phrase to test (`test-llvm-please`) 
- [ ] cadence of test? (nightly build?) 
- [ ] ownership of tests? need to make sure it doesn't rot and continuously fail.
