### ISSUE TITLE
Cilium agent does not boot when above 20k pods

### ISSUE THREAD

**Issue by leoh0** [cilium/cilium#8247]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.5.1 78e2cf4b6 2019-05-08T18:14:37-07:00 go version go1.12.1 linux/amd64
Daemon: 1.5.1 78e2cf4b6 2019-05-08T18:14:37-07:00 go version go1.12.1 linux/amd64
```
- Kernel version (run `uname -a`)
```
4.20.14-1
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:46:28Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**

1. instruction 1
* build large cluster(mycase are using 600 nodes and 20000 pods)
2. instruction 2
* add more nodes and pods(add 400 nodes and 10000 pods)

Hi! Cilium team.

I have tested 30000 nginx pods on 1000 nodes with 20 masters.
There were no problems with 600 nodes and 20000 pods, but after that I add more nodes and pods then the cilium-agent is not booting with below fail messages.

```
...
level=fatal msg="Timed out waiting for pre-existing resources related to policy to be received; exiting" subsys=daemon
level=fatal msg="Agent pipe unexpectedly closed, shutting down" subsys=cilium-node-monitor
```

When I analyzed the logs, it seemed that other resource could be synced in 3 minutes but `core/v1::Pods` could not sync the data in 3 minutes.

```
level=debug msg="waiting for cache to synchronize" kubernetesResource="networking.k8s.io/v1::NetworkPolicy" subsys=daemon
level=debug msg="waiting for cache to synchronize" kubernetesResource="core/v1::Service" subsys=daemon
level=debug msg="waiting for cache to synchronize" kubernetesResource="core/v1::Endpoint" subsys=daemon
level=debug msg="waiting for cache to synchronize" kubernetesResource="cilium/v2::CiliumNetworkPolicy" subsys=daemon
level=debug msg="waiting for cache to synchronize" kubernetesResource="core/v1::Pods" subsys=daemon
level=debug msg="waiting for cache to synchronize" kubernetesResource="core/v1::Node" subsys=daemon
...
level=debug msg="cache synced" kubernetesResource="networking.k8s.io/v1::NetworkPolicy" subsys=daemon
level=debug msg="cache synced" kubernetesResource="core/v1::Service" subsys=daemon
level=debug msg="cache synced" kubernetesResource="core/v1::Endpoint" subsys=daemon
level=debug msg="cache synced" kubernetesResource="cilium/v2::CiliumNetworkPolicy" subsys=daemon
level=debug msg="cache synced" kubernetesResource="core/v1::Node" subsys=daemon
...
```

May be this is our test environment's network or master API performance are poor.
Is it possible to increase below timeout variable or how about adding the below variable to the configuration?

```
	cacheSyncTimeout            = time.Duration(3 * time.Minute)
```

**Comment by aanm** [comment]
hello @leoh0 , please try the following settings:
```yaml
  enable-k8s-event-handover: "true"
  debug: "false"
```

**Comment by leoh0** [comment]
@aanm 
Hi, `cilium-operator` is running and looks good. I try those parameter first.

**Comment by leoh0** [comment]
Thanks @aanm !

I set those variables and it works perfectly.
I create 50k pods with 1k nodes then `cilium-operator` is under heavy loaded but after a while it's all good.
