### ISSUE TITLE
Extraneous error message "Cannot cleanup previous encryption rule state" (address family not supported)

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#8299]
In minikube 1.1.1, I saw this error message printed by Cilium in the logs:

```
level=warning msg="Cannot cleanup previous encryption rule state." error="Delete previous IPv6 decrypt rule failed: address family not supported by protocol" subsys=linux-datapath
```

Ideally I think we could pick up on the lack of support for IPv6 (based upon the error being returned here) and skip logging such an error.

Here's the error number and name:
```
$ errno --search "address family"
EAFNOSUPPORT 97 Address family not supported by protocol
```

We could likely create a function like this:

```
func IsUnsupportedAddressFamily(err Error) bool {
    return err == syscall.Errno(syscall.EAFNOSUPPORT)
}
```

Then use that function to determine whether to log here:

https://github.com/cilium/cilium/blob/85d2e7f210961781326ed2c3c1e3e62ec9fa8100/pkg/datapath/linux/node.go#L775-L797

Tasks:
* [ ] Investigate whether the above approach allows us to identify the unsupported address family error
* [ ] Extend the node functions to either directly perform the syscall.Errno() comparison check, or introduce a package for syscall errno wrapper helper functions and declare/use a function like the above.

**Comment by fristonio** [comment]
@joestringer Can I take this up?

**Comment by joestringer** [comment]
@fristinio sure!

**Comment by joestringer** [comment]
@fristonio sure!

**Comment by joestringer** [comment]
In all likelihood this is probably no longer present; there's been barely any interactions on this issue for the past three years, and during that time the ipsec implementation has changed quite a bit. I'll close this. If you see this error, feel free to comment below and we can reopen the issue.
