### ISSUE TITLE
In clustermesh mode, `cilium node list` reports local cluster twice

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#8327]
Reported on Slack, Cilium v1.5.3:

```
osboxes@osboxes:~/multicloud/onprem$ kubectl -n kube-system exec -it cilium-j9dww -- cilium node list
Name               IPv4 Address   Endpoint CIDR   IPv6 Address   Endpoint CIDR
cluster1/tbh       192.168.1.10   20.0.0.0/24     <nil>          
cluster2/osboxes   192.168.1.23   10.0.0.0/24     <nil>          
osboxes            192.168.1.23   10.0.0.0/24     <nil> 
```

Looks like the "osboxes" is the local cluster and it's printed twice, once with the cluster name and once without. We should only print each cluster once.

**Comment by bharaththiruveedula** [comment]
can I work on it?

**Comment by joestringer** [comment]
@bharaththiruveedula let us know if you would like any pointers, or join us in Slack to discuss :)

**Comment by aanm** [comment]
@bharaththiruveedula are you still working on this?
