### ISSUE TITLE
Remove policy dependency from `pkg/endpoint/regeneration.Owner` interface

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#8364]
It is possible to remove the policy dependency in the `pkg/endpoint/regeneration` package
The easiest way to do it is to implement the methods required by the users of this policy.
For `GetPolicyRepository() *policy.Repository` one would have to check where that
method is used. For example, one of these usages is being done in `pkg/endpoint/policy.go

```
repo := owner.GetPolicyRepository()
repo.Mutex.RLock()
revision := repo.GetRevision()
defer repo.Mutex.RUnlock()
```
The interface returned by `GetPolicyRepository()` would then need to implement
the `GetRevision() int` function. Also in this case, the field "Mutex" is being accessed directly,
this can be avoided by implementing the function `RLock()` and `RUnlock()` in the `policy.Repository`, of which both of those functions would then call `repo.Mutex.RLock()` and `repo.Mutex.RUnlock()` internally.

For the `policy.L4Filter` and `policy.L4Policy`, present in the `owner` interface, will be the same method explained before, wrapping the fields being directly accessed with Getter functions.

**Comment by ianvernon** [comment]
What is the rationale behind having this removed?
