### ISSUE TITLE
ct: removing CT entries when policy no longer allows it

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#839]
When the policy is modified, all CT entries that belong to an endpoint that had its policy changed should be removed.

Since we don't know which IP belongs to which source ID, it will be required to add a new field, source ID, in CT's key. That way we can easily remove all entries where the `srcID` is not allowed to consume `dstIP`

**Comment by aanm** [comment]
After an initial discussion with @borkmann we thought it is necessary to add a new field in CtKey describing the alien's label ID. For example, `12345` represents the security label ID of `10.11.148.173` (the endpoint's IP of a different host)
```
TCP IN 12345 10.11.148.173:60184 -> 10.11.42.252:4833  expires=2262 rx_packets=11 rx_bytes=782 tx_packets=8 tx_bytes=687 flags=0 revnat=0 proxyport=0
TCP OUT 12345 10.11.42.252:4833 -> 10.11.148.173:3807  expires=2095 rx_packets=0 rx_bytes=0 tx_packets=1 tx_bytes=74 flags=0 revnat=3 proxyport=0
```

This way we can easily remove the entries where the new policy does not allow the tuple of `10.11.42.252`'s security label ID, easily calculated since it's local, and the alien's ID, already present in the CT map.

**Comment by tgraf** [comment]
Are we actively working on this?

**Comment by aanm** [comment]
I am, that's what I've being focus the last couple days.
