### ISSUE TITLE
cilium bpf sha get ... CLI issues

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#8423]
### Issue 1

```
# cilium bpf sha get
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/cilium/cilium/cilium/cmd.glob..func18(0x2f95180, 0x3551240, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/cilium/cmd/bpf_sha_get.go:34 +0x69
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x2f95180, 0x3551240, 0x0, 0x0, 0x2f95180, 0x3551240)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2f90ca0, 0xc0002c1f68, 0x16649ee, 0x2f9d8e0)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:800
github.com/cilium/cilium/cilium/cmd.Execute()
        /go/src/github.com/cilium/cilium/cilium/cmd/root.go:47 +0x32
main.main()
        /go/src/github.com/cilium/cilium/cilium/main.go:22 +0x20
```

This should print the CLI usage instead of a stack trace.

### Issue 2

```
# cilium bpf sha get dfe53981733b0f602689eb9c04fcc1259578a32c -o json
"#include \"lib/utils.h\"\n\nDEFINE_IPV6(LXC_IP, 0x20, 0x1, 0xdb, 0x8, 0xb, 0xad, 0xca, 0xfe, 0x60, 0xd, 0xbe, 0xe2, 0xb, 0xad, 0xca, 0xfe);\nDEFINE_U32(LXC_IPV4, 0x030200c0);\t/* 50462912 */\n#define LXC_IPV4 fetch_u32(LXC_IPV4)\nDEFINE_MAC(NODE_MAC, 0x2, 0x0, 0x60, 0xd, 0xf0, 0xd);\n#define NODE_MAC fetch_mac(NODE_MAC)\nDEFINE_U32(LXC_ID, 0x0000ffff);\t/* 65535 */\n#define LXC_ID fetch_u32(LXC_ID)\nDEFINE_U32(SECLABEL, 0x00000002);\t/* 2 */\n#define SECLABEL fetch_u32(SECLABEL)\nDEFINE_U32(SECLABEL_NB, 0x02000000);\t/* 33554432 */\n#define SECLABEL_NB fetch_u32(SECLABEL_NB)\n#define POLICY_MAP cilium_policy_65535\n#define CALLS_MAP cilium_calls_65535\n#define CONFIG_MAP cilium_ep_config_65535\n#define FORCE_LOCAL_POLICY_EVAL_AT_SOURCE 1\n#define ENABLE_ROUTING 1\n#define ENABLE_ARP_RESPONDER 1\n#define ENABLE_HOST_REDIRECT 1\n#define CT_MAP_TCP4 cilium_ct4_global\n#define CT_MAP_ANY4 cilium_ct_any4_global\n#define CT_MAP_TCP6 cilium_ct6_global\n#define CT_MAP_ANY6 cilium_ct_any6_global\n#define CT_MAP_SIZE_TCP 524288\n#define CT_MAP_SIZE_ANY 262144\n#define LB_L3 1\n#define LB_L4 1\n#define LOCAL_DELIVERY_METRICS 1\n#define CONNTRACK 1\n#define CONNTRACK_ACCOUNTING 1\n#undef CONNTRACK_LOCAL\n#undef DEBUG\n#undef LB_DEBUG\n#define DROP_NOTIFY 1\n#define MONITOR_AGGREGATION 3\n#undef ENABLE_NAT46\n#define TRACE_NOTIFY 1\n"
```

Maybe in some form, this is kind-of json? Because it's just a string. However I'd expect something like this instead:

```
# cilium bpf sha get <sha> -o json
{
  "LXC_IP": "2001:db08:0bad:cafe:600d:bee2:0bad:cafe",
  "LXC_IPV4": 10.0.2.3",
  ...
}
```

**Comment by fristonio** [comment]
Hey @joestringer for the second issue I don't understand how you want the JSON to be printed out of the C header file. Is it like we want the macros value to reported as JSON in the output?

**Comment by joestringer** [comment]
@fristonio that was the idea. I discussed with @iffyio on slack about maybe just using something like regex from the CLI to filter the headerfile and pull keys/values from there; alternatively we could look at changing the template write function in `pkg/datapath/linux/config.go` to add a base64-encoded json blob in the top of the headerfile, which the CLI could read out; the downside to the latter approach would be that it pushes the cost of json serialization into every headerfile write.

I would suggest co-ordinating between the two of you, either here or on Slack, if you are both interested in looking at the second issue.

**Comment by joestringer** [comment]
Also, I would treat the two issues separately, the first one can be fixed easily with a short PR. The second is more involved.

**Comment by iffyio** [comment]
@fristonio I was looking into the json-encoding route on the second issue but since you already started with the ticket obviously you have first dibs :)

**Comment by fristonio** [comment]
Hey @iffyio, Sorry I didn't have the idea that you were looking into the issue.
@joestringer The PR for the first issue is [here](https://github.com/cilium/cilium/pull/8449)

Regarding the second one, the second one seems more neat to me we can decide the approach on the basis of how often are write to headerfile made?
Also, @iffyio do you have any take on the approach for this?

**Comment by fristonio** [comment]
The second part of the issue still needs to be addressed.

**Comment by joestringer** [comment]
@fristonio I've recently merged changes that should minimize the frequency of headerfile writes, so it's not as big of a deal any more (https://github.com/cilium/cilium/pull/8268).

**Comment by fristonio** [comment]
That's great. :tada: 
I will start working on embedding base64 encoded JSON data to the header file then.
