### ISSUE TITLE
policy: add reserved identity for doing ingress, egress traces

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#8454]
This would simplify the helper functions within the policy library. It would replace the `To` and `From` fields within a `SearchContext` to be pointers to identities, instead of LabelArrays. Thus, policy calculation would always be done in terms of identities. Special logic would be added to the SelectorCache and to the caches within the rules to not add any identity with these reserved identities into the SelectorCache - this would be cheap to add as it is a simple numerical comparison. This way, multiple traces can be done concurrently using the same source / destination identities.

**Comment by ianvernon** [comment]
Related: https://github.com/cilium/cilium/issues/6418

**Comment by joestringer** [comment]
We've deprecated policy trace in v1.11, so no point in tracking this item any longer.
