### ISSUE TITLE
Change WORKDIR away from /root

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#8456]
The current `Dockerfile` uses `WORKDIR=/root` which prevents running Cilium as non-root.

- [ ] Change the WORKDIR
- [ ] Build a container image with the change `DOCKER_IMAGE_TAG=test make dev-docker-image`
- [ ] Make any additional required changes which may depend on WORKDIR=/root

**Comment by errordeveloper** [comment]
This was closed by #10561.
