### ISSUE TITLE
Cilium-pre-flight.yaml namespace is incorrect for Google (GKE)

### ISSUE THREAD

**Issue by Robert-Stam** [cilium/cilium#8459]
## Bug report

The pre-flight yaml creates the DaemonSet in the kube-system namespace, however for GKE this should be Cilium.

**General Information**

- Cilium version: 1.5.3
- Orchestration system: Kubernetes
- Link to relevant artifacts:
  - examples/kubernetes/1.[minor]/cilium-pre-flight.yaml

**How to reproduce the issue**

1. Create an installation inside GKE (e.g. version 1.5.2)
2. Upgrade to v 1.5.3 (using the pre-flight method as recommended).
This leads to PodUnschedulable errors. 
 
Note that `kubectl apply -n cilium -f <path>` will not work because the namespace is specified in the yaml.

My proposal is to remove the namespace from the yaml and specify it during the apply.

Please see: https://cilium.slack.com/archives/C2B917YHE/p1561827335092600

**Comment by mrostecki** [comment]
Since we already auto-generate a lot of different yaml files for different use cases, I think that we should just have a separate `cilium-pre-flight-gke.yaml` and mention it in the documentation.

**Comment by Robert-Stam** [comment]
That's fine.

I just discovered another issue with the file on Google (I am testing the update from 1.5.3 to 1.5.5 and changed the namespace locally), however I run into the following:

```Error creating: pods "cilium-pre-flight-check-" is forbidden: pods with system-node-critical priorityClass is not permitted in cilium namespace```

You should remove that was well, or replace with something else?

**Comment by Robert-Stam** [comment]
Both issues are addressed in 1.6 I tested with [1.6.3], so closing the issue.
