### ISSUE TITLE
Unable to update ip cache entry message fails to include an action

### ISSUE THREAD

**Issue by mdaniel** [cilium/cilium#8472]
## Support

In my cluster, [this "error"](https://github.com/cilium/cilium/blob/v1.5.4/daemon/k8s_watcher.go#L1832) becomes [this "warning"](https://github.com/cilium/cilium/blob/v1.5.4/daemon/k8s_watcher.go#L1843) over **670** times per Node, however according to [a Slack message in #testing on May 9th](https://cilium.slack.com/archives/C7PE7V806/p1557388946119000?thread_ts=1557348316.114000&cid=C7PE7V806) it shouldn't be a warning at all:
>> it's a warning because the developer forgot to change that warning to a debug

> Do you mind if I change this to debug (or to info)? Recently I got bugged by at least two users about this

It would be great if one, or both, of two things happened:
1. downgrade that to an actual Debug message as Slack advised
1. or include some _action_ that the user can take in the face of a warning plus error

**Comment by gandro** [comment]
It looks like this has been addressed by #8388 and is expected to be part the next release (it looks like it will be backported to 1.5 as well!)
