### ISSUE TITLE
Update or discontinue Cilium Grafana Dashboard

### ISSUE THREAD

**Issue by brb** [cilium/cilium#8502]
A user reported that Cilium Metrics dashboard https://grafana.com/dashboards/6658 is very old. We should either update it or discontinue considering that we have our own (maintained) installation for the dashboard - https://docs.cilium.io/en/stable/gettingstarted/grafana/.

**Comment by gandro** [comment]
We have updated the dashboards for all supported Cilium versions: https://grafana.com/orgs/cilium
