### ISSUE TITLE
microk8s-ds.yaml does not exist in examples/kubernetes

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#8523]
running `make -C examples/kubernetes clean all` does not generate the `microk8s-ds.yaml` file since the `microk8s-ds.yaml.sed` does not exist in the repo.

@joestringer Does it needs to be backported?

**Comment by aanm** [comment]
Please rebase against https://github.com/cilium/cilium/pull/8522 once it's merged.

**Comment by joestringer** [comment]
Why do we need `cilium-microk8s-ds.yaml` at all? The GSG uses `cilium-microk8s.yaml`

**Comment by joestringer** [comment]
Looks like these YAMLs are already removed in v1.5 branch, so no backport necessary.
