### ISSUE TITLE
vagrant: install go-bindata by default

### ISSUE THREAD

**Issue by aalemayhu** [cilium/cilium#859]
The negative side effect of not having go-bindata available in the VM is

- Changes to the BPF sources are not going to be applied to the daemon.
- The Jenkins environment can be testing outdated stuff without the committer realising it because go-bindata changes were not committed. 

If installing go-bindata by default is a no go then IMO least the user should get warned that it's not there and BPF changes are not tracked properly when running `make`. Maybe something like

```
Warning: missing go-bindata. BPF source changes won't be tracked.
You can install go-bindata by running: go get -u github.com/jteeuwen/go-bindata/...
```

**Comment by tgraf** [comment]
BPF changes are never automatically taken into account. I'm fine with adding go-bindata to vagrant though.
