### ISSUE TITLE
CI: move toward using native Go client for interacting with Kubernetes API

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#8590]
Move away from running SSH commands on specific instances. This allows us to load in a kubeconfig to be able to run K8s commands against remote clusters while running Ginkgo tests. 

- [x] move away from using SSH and use local `kubectl` with `kubeconfig` for Ginkgo tests
- [ ] move to using native Go client
    - move individual functions one at a time?
- [ ] Use cluster-diagnosis in the CI via using the same kubeconfig that the test framework uses: https://github.com/cilium/cilium/issues/3495

**Comment by ianvernon** [comment]
I think good preparation for this is to move functions that are using `jq` currently into getting the output as JSON and then unmarshaling directly into Kubernetes structures. We can then hide whatever is getting us the information from those structures in utility functions and swap them out transparently. What do you think @nebril ?

**Comment by ianvernon** [comment]
Initial work to use `kubectl` binary and kubeconfig here: https://github.com/cilium/cilium/pull/8683

**Comment by ti-mo** [comment]
Closing this as we're porting many tests to cilium-cli and we're not going to invest much more time into evolving the ginkgo test framework.
