### ISSUE TITLE
cilium-health is several minutes down when recreating cilium-agent pod

### ISSUE THREAD

**Issue by joulaud** [cilium/cilium#8595]
## Bug report

When deleting a cilium pod of the kubernetes DaemonSet, the pod created to replace it is really long to have a correct status.

This impacts the observability of the health of cilium and is particularly bad when doing upgrades (it makes very difficult to know if it works or not).

The scenario is:
- T-X: deletion of old pod
- T0: new cilium pod starting
- T0 to T+20s: `Error: Cannot get health for local instance: Get http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/healthz: dial unix /var/run/cilium/health.sock: connect: no such file or directory`
- T+20s to T+15m: `Error: Cannot get health for local instance: Get http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/healthz: dial unix /var/run/cilium/health.sock: connect: connection refused`
- T+15m0s to T+15m10s:
  ```
  Daemon uptime:          14m32.625536782s
  Node load:              1.85 2.58 3.36
  KVStore:                Ok   etcd: 3/3 connected, [...]
  ContainerRuntime:       Ok   docker daemon: OK
  Kubernetes:             Ok   1.11 (v1.11.8) [linux/amd64]
  Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumNetworkPolicy", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
  Cilium:                 Ok   OK
  NodeMonitor:            Disabled
  Cilium health daemon:   Warning   Get http:///var/run/cilium/health.sock/v1beta/hello: dial unix /var/run/cilium/health.sock: connect: no such file or directory
  IPv4 address pool:      85/255 allocated from 100.[...]
  IPv6 address pool:      85/65535 allocated from f00d::[...]
  Controller Status:      344/344 healthy
  Proxy Status:           OK, ip [...]
  ```
- T+15m10s and after:
  ```
  Daemon uptime:          14m51.83676135s
  Node load:              1.53 2.46 3.30
  KVStore:                Ok   etcd: 3/3 connected,[...]
  ContainerRuntime:       Ok   docker daemon: OK
  Kubernetes:             Ok   1.11 (v1.11.8) [linux/amd64]
  Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumNetworkPolicy", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
  Cilium:                 Ok   OK
  NodeMonitor:            Disabled
  Cilium health daemon:   Ok   
  IPv4 address pool:      85/255 allocated from 100.[...]
  IPv6 address pool:      85/65535 allocated from f00d::[...]
  Controller Status:      344/344 healthy
  Proxy Status:           OK, ip [...]
  ```

**General Information**

- Cilium version
  ```
  Client: 1.5.5 9ba05044c 2019-07-11T12:56:13-07:00 go version go1.12.5 linux/amd64
  Daemon: 1.5.5 9ba05044c 2019-07-11T12:56:13-07:00 go version go1.12.5 linux/amd64
  ```
- Kernel version `Linux ip-XX-XX-XX-XX 4.19.0-0.bpo.2-amd64 #1 SMP Debian 4.19.16-1~bpo9+1 (2019-02-07) x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: kubernetes `Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

**How to reproduce the issue**

1. `kubectl delete pod cilium-abcdef`
2. `watch kubectl exec cilium-new -- cilium-health get`

**Comment by gandro** [comment]
Thanks for the report! It looks like it recovers after almost exactly 15 Minutes (thanks a lot for timing it), which could mean that it might be an issue with a stale lease.

**Comment by joulaud** [comment]
Just for precision, the timings have precision around +/- 10s. It does not change the analysis but I prefer to be explicit.

**Comment by riaan53** [comment]
The 15min jumped out when I saw it, have a look at this issue might help: https://github.com/kubernetes/client-go/issues/374#issuecomment-484532911

**Comment by gandro** [comment]
@joulaud Unfortunately, I'm unable to reproduce the issue locally. I'm however still assuming the delay is caused by stale node information. Would you mind sharing the health node IPs before and after recovery?

Execute the following commands before and after health recovers (on the new pod):
```
kubectl get pod cilium-new -o wide
kubectl exec -ti cilium-new -- cilium node list -o jsonpath='{range [*]}{@.name}{": "}{@.health-endpoint-address.ipv4.ip}{" "}{@.health-endpoint-address.ipv6.ip}{"\n"}{end}'
```

Could you also share the output of `kubectl logs cilium-new` at the end? Thanks.
