### ISSUE TITLE
Deprecate DNS Poller in v1.8, remove in v1.9

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#8604]
1.8:
* [x] Mark flag as deprecated
* [x] Add deprecation notice to the upgrade guide
* [x] Remove all other non-upgrade explanations around DNS poller

1.9:
* [x] Remove all code related to DNS poller

**Comment by joestringer** [comment]
@raybejjani Do you have any objections to deprecating DNS poller this release cycle?

**Comment by tklauser** [comment]
Reopening as the DNS poller was deprecated in 1.8 but not removed yet (probably due to the `Fixes` tag in the PR description). See https://github.com/cilium/cilium/pull/10629#pullrequestreview-377460588 and related discussion. It should be removed during the 1.9 cycle.
