### ISSUE TITLE
netlink: 'cilium-agent': attribute type 1 has an invalid length

### ISSUE THREAD

**Issue by brb** [cilium/cilium#8613]
Observed in dmesg with the latest Cilium master (`v1.6.0-rc2-124-g6ed91c7c0`) and on the 5.2 kernel:

```
netlink: 'cilium-agent': attribute type 1 has an invalid length
```

**Comment by brb** [comment]
I haven't observed in a while, so closing.

**Comment by gpl** [comment]
Hello,

We're able to consistently see this message pop up on our Kubernetes cluster, running v1.19 and Cilium 1.9.7 on a host reboot.

I can PM the sysdump on request, thank you!

**Comment by aanm** [comment]
cc @brb

**Comment by gpl** [comment]
Didn't have time to dig too deeply but I some more research on this and it looks like disabling auto direct node routes "fixed" the problem for me, bare metal, kernel 5.10.

**Comment by ti-mo** [comment]
@brb @aanm Mind adding some more context? The Slack link given above is already dead.

**Comment by aanm** [comment]
@gpl can you provide more context here? Steps to reproduce it and which environment?

**Comment by gpl** [comment]
Bare metal, kernel 5.10.50, cilium v1.10.x, kubernetes 1.21.x.  It looks like the issue went away after I disabled auto direct node routes, so I'm assuming something is off there.  We use bridge interfaces for the primary network.

If needed I can try to get a lab setup to test this out & reproduce.

**Comment by ithilgore** [comment]
Having the same issue with k8s 1.21.x and Cilium 1.9.4 and even with 'auto direct node routes' disabled.

**Comment by brb** [comment]
It's been awhile. Closing as stale.
