### ISSUE TITLE
using ipvlan mode, pods between hosts failed communicate.

### ISSUE THREAD

**Issue by bretagne-peiqi** [cilium/cilium#8619]
## Support

env: 
     centos 7.2；   linux kernel: 4.20.0-1.el7.elrepo.x86_64
     kubernetes       1.11.2
     etcd version     3.2.6
     cilium version    1.4.6

trace:
     
![Screen Shot 2019-07-19 at 10 21 43 AM](https://user-images.githubusercontent.com/5621794/61504835-55aad080-aa0f-11e9-90df-bc14546c7558.png)
![Screen Shot 2019-07-19 at 10 22 45 AM](https://user-images.githubusercontent.com/5621794/61504839-57749400-aa0f-11e9-961c-1b2781aa2bbd.png)
![Screen Shot 2019-07-19 at 10 23 02 AM](https://user-images.githubusercontent.com/5621794/61504842-593e5780-aa0f-11e9-98a7-9c3d6e4595fb.png)

tcpdump can't see any trace in cilium_host dev and bond1 dev.

**Comment by bretagne-peiqi** [comment]
It seems the router gateway cilium_host drops the packets

**Comment by brb** [comment]
I've tried with your configuration, but with the latest Cilium v1.5.5, and it works - I was able to ping `cilium_host` of a local and of a remote node from a Pod.

Please try the following:

- Upgrade Cilium to v1.5.5.
- Check that underlay network is not dropping packets from an unknown subnet.
- Try changing ipvlan master device to a non-bond iface.

**Comment by brb** [comment]
Please re-open if the issue persists.
