### ISSUE TITLE
cilium bpf metrics list pollutes the screen

### ISSUE THREAD

**Issue by ArthurChiao** [cilium/cilium#8620]
## Bug report

```shell
# cilium bpf metrics list
REASON             DIRECTION                          PACKETS   BYTES
|▒Z     count:19167137 bytes:94163499922
1⎼▒   ↓$°
S┤cce⎽⎽            E±⎼e⎽⎽                             3568      3▮83▮4
   ⎻1
⎼⎺⎺├184▮:·#
```

**Not every run will fail, but at least `50%` percent reproducible in my case.**

## General Information

- Cilium version: `1.5.1`
- Kernel version: `4.14`
- Host OS: CentOS 7.1
- Orchestration system version in use: `k8s`

## How to reproduce the issue

1. Attach to container: `docker exec -it <cilium container> bash`
2. Issue command: `cilium bpf metrics list`

Or in one shot: `docker exec <cilium container> cilium bpf metrics list`

## Dig into the problem

By some debugging, I found the problem comes from method `Dump` in [pkg/bpf/map_linux.go](https://github.com/cilium/cilium/blob/master/pkg/bpf/map_linux.go):

```go
// Dump returns the map (type map[string][]string) which contains all
// data stored in BPF map.
func (m *Map) Dump(hash map[string][]string) error {
	callback := func(key MapKey, value MapValue) {
		// No need to deep copy since we are creating strings.
		hash[key.String()] = append(hash[key.String()], value.String())
	}

	if err := m.DumpWithCallback(callback); err != nil {
		return err
	}

	return nil
}
```

Following line seems to be misbehaving.:

```go
hash[key.String()] = append(hash[key.String()], value.String())
```

If I replace it with (force to deep copy the key string):

```go
k := fmt.Sprintf("%s", key.String())
hash[k] = append(hash[k], value.String())
```

the problem will disappear. 

But note that following version doesn't work:

```go
k := key.String()
hash[k] = append(hash[k], value.String())
```

Look at the code, `key.String()` really returns a new string by `fmt.Sprintf()`, in [pkg/maps/metricsmap/metricsmap.go](https://github.com/cilium/cilium/blob/master/pkg/maps/metricsmap/metricsmap.go), just as the comment line goes: `// No need to deep copy since we are creating strings.`

**Comment by ArthurChiao** [comment]
I also added some logs before and after the problematic line:

```go
               fmt.Println("before append ...")
               for k, _ := range hash {
                       fmt.Println("key[", k, "], len[", len(k), "]")
               }
               hash[key.String()] = append(hash[key.String()], value.String())
               fmt.Println("after append ...")
               for k, _ := range hash {
                      fmt.Println("key[", k, "], len[", len(k), "]")
               }
```

This is what the output looks like:

```shell
# c bpf metrics list
before append ...
--------
after append ...
key[ reason:139 dir:2 ], len[ 16 ]


before append ...
key[ ▒ ], len[ 16 ]
--------
after append ...
key[ reason:151 dir:1 ], len[ 16 ]
key[ ▒ ], len[ 16 ]


before append ...
key[ ▒ ], len[ 16 ]
key[ reason:151 dir:1 ], len[ 16 ]
--------
after append ...
key[ ▒ ], len[ 16 ]
key[ reason:151 dir:1 ], len[ 16 ]
key[ reason:0 dir:2 ], len[ 14 ]
```

Seems the key has been corrupted by later rounds (loops).

**Comment by aanm** [comment]
@ArthurChiao Thanks for the detailed GH issue. Can you try with cilium `v1.5.5` and `v1.6.0-rc2`? You don't need to restart Cilium, just using that CLIs provided for that versions should be enough.

**Comment by ArthurChiao** [comment]
OK, I will have a try, thanks! @aanm

**Comment by ArthurChiao** [comment]
Tested with `1.5.5`, the problem disappeared.

I noticed the dump parser changes, which provided default values for the keys and values to be printed:

`v1.5.5`:

```go
func init() {
        possibleCpus = getNumPossibleCPUs()
        // Metrics is a mapping of all packet drops and forwards associated with
        // the node on ingress/egress direction
        Metrics = bpf.NewMap(
                MapName,
                bpf.BPF_MAP_TYPE_PERCPU_HASH,
                int(unsafe.Sizeof(Key{})),
                int(unsafe.Sizeof(Value{})),
                MaxEntries,
                0, 0,
                func(key []byte, value []byte) (bpf.MapKey, bpf.MapValue, error) {
                        k, v := Key{}, Value{}

                        if err := bpf.ConvertKeyValue(key, value, &k, &v); err != nil {
                                return nil, nil, err
                        }
                        return &k, &v, nil
                })
}
```

`v.1.5.1`:

```go
func init() {
        possibleCpus = getNumPossibleCPUs()
        // Metrics is a mapping of all packet drops and forwards associated with
        // the node on ingress/egress direction
        Metrics = bpf.NewMap(
                MapName,
                bpf.BPF_MAP_TYPE_PERCPU_HASH,
                &Key{},
                int(unsafe.Sizeof(Key{})),
                &Value{},
                int(unsafe.Sizeof(Value{})),
                MaxEntries,
                0, 0,
                bpf.ConvertKeyValue,
        )
}
```

But still not sure how the data was corrupted in `1.5.1`?

**Comment by aanm** [comment]
@ArthurChiao there were some regressions introduced by https://github.com/cilium/cilium/commit/79c247a955f8c3e02f05dc172fce67e2dd268b2b which they were reverted back in the v1.5 branch. Did you try it out with `v1.6.0-rc2`?

**Comment by ArthurChiao** [comment]
thanks, I'd like to have a look at the commit.

`v.1.6.0-rc2` not tested, using the CLI with `1.5.1` OK? I can verify it later today.

**Comment by ArthurChiao** [comment]
`v1.6.0-rc2` verified. Problem solved.
