### ISSUE TITLE
why do not 'cilium map list' list all map ?

### ISSUE THREAD

**Issue by aaron-ai** [cilium/cilium#8628]
I hava already seen that many maps in the map directory(`/run/cilium/bpffs/tc/globals`), such as `cilium_calls_netdev_ns_1`，but when I use `cilium map list` , I can not see the map name of `cilium_calls_netdev_ns_1`，why? and even when I use `bpf-map` tool, there will generate a mistake:`Unable to lookup element: no such file or directory`, so what is the difference between the map `cilium_calls_netdev_ns_1` and other map ,such as `cilium_ipcache`?

**Comment by brb** [comment]
`cilium_calls_*` are BPF tail call maps (https://docs.cilium.io/en/latest/bpf/#tail-calls) used by the Cilium datapath programs.

`cilium map list` dumps only those maps which are opened by `cilium-agent`, therefore you don't see any `cilium_calls_*` map within its output.
