### ISSUE TITLE
add gops support for cilium-health, cilium-health-responder

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#8633]
We are seeing `context deadline exceeded` when running `cilium-health status --probe`, but we can't introspect the state of these processes to see what is getting hung up where. add support for `gops` like we do for `cilium-agent`.

**Comment by joestringer** [comment]
`cilium-health` is just the CLI. Do you want the CLI to have gops output?

The main `cilium-health` logic is running inside the `cilium` agent daemon now so regular gops from there should be useful.

`cilium-health-responder` is super simple so I'd be surprised if there's a nuanced bug there.
