### ISSUE TITLE
wait-bpf-mount: "true" does not work as intended

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#8646]
How to reproduce:
1. Create minikube cluster
2. Deploy standard `cilium.yaml` with `wait-bpf-mount: "true"` in ConfigMap.
3. Cilium pod is started beyond init container despite BPF filesystem not being mounted

**Comment by tgraf** [comment]
I saw this issue with the standard yaml which has the environment variable defined in the init conainer section.

**Comment by tgraf** [comment]
Same can be reproduced on EKS, deploying with `wait-bpf-mount: "true"` will still result in:
```
level=warning msg="================================= WARNING ==========================================" subsys=bpf
level=warning msg="BPF filesystem is not mounted. This will lead to network disruption when Cilium pods" subsys=bpf
level=warning msg="are restarted. Ensure that the BPF filesystem is mounted in the host." subsys=bpf
level=warning msg="https://docs.cilium.io/en/stable/kubernetes/requirements/#mounted-bpf-filesystem" subsys=bpf
level=warning msg="====================================================================================" subsys=bpf
```

**Comment by mrostecki** [comment]
@tgraf Thanks for clarification! I found the issue. The init container script was always succesful, because `mount | grep bpf` will always succeed inside containers - if there is no BPFFS mount, we will have a kubernetes host mount anyway, of a different type:

```
sysfs on /sys/fs/bpf type sysfs (rw,relatime)
``´

We need to explicitly look for a bpffs type of mount. I will test and submit a fix soon.
