### ISSUE TITLE
encryption: encrypt-node node to pod encryption only works in subnet modes

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#8712]
The encrypt-node option is used to encrypt traffic on a node that would typically not be seen by Cilium. However, node to pod traffic is only encrypted if using subnet modes. In subnet mode traffic to pod IPs is sent to cilium_host via an additional route and then encrypted using the cilium_ipcache map to lookup keys. But, if using direct routing modes with out subnet mode then no route is installed to route the pod traffic, when sent from the node, to cilium_host and so it is never encrypted. The result is traffic is only encrypted from pod to node but node to pod half is in plaintext.

Fix is to add additional routes to catch this case.

**Comment by pchaigno** [comment]
Node encryption was deprecated and is being removed.
