### ISSUE TITLE
Investigate 1.6 CI errors/warnings

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#8722]
https://jenkins.cilium.io/view/Cilium-v1.6/job/cilium-v1.6-standard/8/testReport/Suite-k8s-1/10/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

```
Top 5 errors/warnings:
Unable to parse node IP while processing CiliumEndpoint update
Key allocation attempt failed
Received kvstore delete notification for alive ipcache entry
Received delete event for local key. Re-creating the key in the kvstore
Received node delete event for node default/k8s1 which re-appeared within 30s
```

**Comment by tgraf** [comment]
```
Key allocation attempt failed
```

This is caused by:
```
2019-08-05T02:51:04.578143734Z level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:app=empire-outpost;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:outpostid=9999;k8s:zgroup=kafkaTestApp;': identity does not exist" key="[k8s:app=empire-outpost k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:outpostid=9999 k8s:zgroup=kafkaTestApp]" subsys=allocator
```

The first attempt fails, the 2nd attempt then succeeds so this is primarily a cosmetic issue right now.

**Comment by Antiarchitect** [comment]
Some logs from my case:
```
level=warning msg="Key allocation attempt failed" attempt=9 error="unable to create slave key 'k8s:app=rook-ceph-osd;k8s:ceph-osd-id=2;k8s:failure-domain=worker-2.prod.lwams1.enapter.ninja;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=rook-ceph-osd;k8s:io.kubernetes.pod.namespace=core-rook;k8s:portable=false;k8s:rook_cluster=core-rook;': Operation cannot be fulfilled on ciliumidentities.cilium.io \"39243\": StorageError: invalid object, Code: 4, Key: /registry/cilium.io/ciliumidentities/39243, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 626b3b0a-fa53-11e9-81d6-005056b1aae6, UID in object meta: " key="[k8s:app=rook-ceph-osd k8s:ceph-osd-id=2 k8s:failure-domain=worker-2.prod.lwams1.enapter.ninja k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=rook-ceph-osd k8s:io.kubernetes.pod.namespace=core-rook k8s:portable=false k8s:rook_cluster=core-rook]" subsys=allocator
```

**Comment by aanm** [comment]
> Some logs from my case:
> 
> ```
> level=warning msg="Key allocation attempt failed" attempt=9 error="unable to create slave key 'k8s:app=rook-ceph-osd;k8s:ceph-osd-id=2;k8s:failure-domain=worker-2.prod.lwams1.enapter.ninja;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=rook-ceph-osd;k8s:io.kubernetes.pod.namespace=core-rook;k8s:portable=false;k8s:rook_cluster=core-rook;': Operation cannot be fulfilled on ciliumidentities.cilium.io \"39243\": StorageError: invalid object, Code: 4, Key: /registry/cilium.io/ciliumidentities/39243, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 626b3b0a-fa53-11e9-81d6-005056b1aae6, UID in object meta: " key="[k8s:app=rook-ceph-osd k8s:ceph-osd-id=2 k8s:failure-domain=worker-2.prod.xxx.xxx.xxx k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=rook-ceph-osd k8s:io.kubernetes.pod.namespace=core-rook k8s:portable=false k8s:rook_cluster=core-rook]" subsys=allocator
> ```

Can you check if you are mounting BPF filesystem?

https://docs.cilium.io/en/v1.6/kubernetes/requirements/#mounted-bpf-filesystem

**Comment by aanm** [comment]
> Cluster health seems OK by report, but I don't know why some reachability lost on some nodes:
> Cluster health: 2/7 reachable (2019-10-30T17:59:54Z)
> Name IP Reachable Endpoints reachable
> kube-2.prod.acit1.xxx Unavailable false true
> kube-3.prod.acit1.xxx Unavailable false true
> worker-1.prod.acit1.xxx Unavailable false true
> worker-1.prod.lwams1.xxx Unavailable false true
> worker-3.prod.lwams1.xxx Unavailable false true
> Actually in Troubleshooting I have not found the answer what does it mean
> There is absolutely random count of unavailable nodes for each node and I don't see any pattern

usually it takes a couple minutes for status node to be updated by the prober. Make sure you are also using the last version as there was a bug in cilium with regarding this. Some nodes were not properly clean up after they were removed.

**Comment by Antiarchitect** [comment]
Seems like I've had several issues at once. First of all my firewall rules didn't allow 10.32.0.0/12 - my internal CIDR as a source in some cases. And BPF wasn't mounted properly.
Thank you so much - I see perfect network connectivity for the first time.

**Comment by Antiarchitect** [comment]
Great docs change! Thank you so much once again!

**Comment by tgraf** [comment]
Not observing this anymore. Closing for now.
