### ISSUE TITLE
host-lb: unexpected rev NAT xlation for non-service connections

### ISSUE THREAD

**Issue by brb** [cilium/cilium#8739]
It has been observed that a connection from host netns to a Pod via PodIP can be unexpectedly rev-NAT translated. For example (`10.217.1.119` is IP addr of kube-dns Pod, `10.96.0.10` is kube-dns ClusterIP):
```
host # nslookup google.com 10.217.1.119
;; reply from unexpected source: 10.96.0.10#53, expected 10.217.1.119#53
```

This can happen when a socket cookie + PodIP + port combination is not unique in `LB{4,6}_REVERSE_NAT_SK_MAP`, which can happen due a guarantee that the cookie is unique only within netns.

Unfortunately, src IP / port is not available in the relevant CGROUPS hooks used by host-lb. So, to fix this, we should either make a cookie globally unique in the kernel or add a BPF helper to retrieve a netns ID (?) which could be used in the map key.

**Comment by borkmann** [comment]
Submitted: https://lore.kernel.org/bpf/20190808094937.26918-1-daniel@iogearbox.net/T/
