### ISSUE TITLE
bpf: Verifier complaint for list of L4 ports

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#877]
If a NetworkPolicy with multiple L4 ports is configured, the BPF verifier complains

```
#define CFG_L4_INGRESS { {80, 8080, 0}, {81, 8181, 0} }
```

**Comment by jrfastab** [comment]
Looks like another relocation error, `ELF contains non-map related relo data in entry 19 pointing to section 23!`. I was hoping to force it to work with some pragma/attribute but didn't come up with anything clever, so will need to brute force it with another macro.

**Comment by jrfastab** [comment]
I believe this is resolved now and I added a couple tests to the 10-proxy test case to catch this in the future.
