### ISSUE TITLE
Final testing of guides for 1.6

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#8774]
- [x] Sandbox
  - [x] minikube
  - [x] microk8s (@joestringer) (#8796)
- [x] Self-Managed k8s
  - [x] Quick installation (@ianvernon)
  - [x] Managed etcd (etcd-operator) (@tgraf) [#8871]
  - [x] External etcd (@tgraf)
- [x] Managed k8s
  - [x] EKS (@tgraf)
  - [x] GKE (@glibsm, @tgraf)
- [ ] Installer integrations (To be done post release)
  - [ ] kops (@nebril) (under review upstream)
  - [x] kubeadm (@brb)
  - [ ] kubespray
  - [ ] https://github.com/cilium/cilium/issues/6116 (tgraf)
- [x] CNI Chaining
  - [x] aws-cni (@gandro)
  - [x] Portmap (@tgraf) [#8847]
  - [x] Calico (@tgraf) [#8874]
  - [x] Weave Net (@tgraf) [#8874]
- [x] Advanced topics
  - [x] Istio (@tgraf)
  - [x] Flannel guide (@joestringer)
  - [x] IPVLAN (@brb)
  - [x] Transparent encryption (@jrfastab)
  - [x] Host reachable services (@borkmann)
  - [x] NodePort (@brb)
  - [x] Kata (@tgraf)
  - [x] ENI (@joestringer, @michi-covalent)
- [x] Operations
  - [x] Prometheus & Grafana (@gandro)
- [x] Upgrade instructions
  - [x] External etcd -> external etcd (@jrajahalme)
  - [x] etcd-operator -> CRD (@raybejjani)

**Comment by jrfastab** [comment]
@tgraf two issues documented in slack wrt transparent encryption.
 (a) tarball extracts to cilium_master not master
 (b) need global in encryptNode references.

**Comment by tgraf** [comment]
> (a) tarball extracts to cilium_master not master

Fixed via https://github.com/cilium/cilium/pull/8790



> (b) need global in encryptNode references.

Fixed via https://github.com/cilium/cilium/pull/8797

**Comment by brb** [comment]
NodePort can be ticked after https://github.com/cilium/cilium/pull/8858 has been merged.

**Comment by borkmann** [comment]
Host reachable services can be ticked after https://github.com/cilium/cilium/pull/8861 got merged.

**Comment by joestringer** [comment]
I had to remove the interface in the flannel.yaml but otherwise it worked for me with microk8s (had to copy the CNI conflist into the right directory but that's a microk8s thing)

**Comment by jrajahalme** [comment]
Minor tweaks in #8881 for external etcd guide. 

Tested upgrade from 1.5 to master and roll back.

**Comment by brb** [comment]
ipvlan can be ticked after https://github.com/cilium/cilium/pull/8905.

**Comment by tgraf** [comment]
All items pre-release have been ticked off. Removing release-blocker flag.

**Comment by brb** [comment]
kubeadm can be ticked after https://github.com/kubernetes/website/pull/16002 has been merged.
