### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes with L7 policy Tests NodePort with L7 Policy

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#8776]
## CI failure
Worth noting - the test was unable to curl to 127.0.0.1

```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.15-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
k8s1 host can not connect to service "http://127.0.0.1:30600"
Expected command: curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://127.0.0.1:30600 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000020()', Connect: '0.000000',Transfer '0.000000', total '5.006275'
Stderr:
 	 

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.15-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:231
```

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7972/

[30c8f5e7_K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy.zip](https://github.com/cilium/cilium/files/3467610/30c8f5e7_K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy.zip)

**Comment by tgraf** [comment]
A potential explanation is that the test fails if the chosen backend is non-local or local. There is a 50% chance. May have been broken with one of the recent `pkg/datapath/iptables` changes.

**Comment by brb** [comment]
From what I saw when re-produced the issue locally (unfortunately the cilium-agent got restarted which fixed the issue):

- k8s readiness probe was failing for `testDS` pods which prevented them to be added as endpoints to the NodePort service. Bacause of this, curl to `http://127.0.0.1:$NODE_PORT` failed.
- There was no connectivity from the host to a `testDS` pod running on the same host. The TCP SYN packet entered the relevant TPROXY rule, but nothing happened afterwards. Might be related to L7 + direct routing issue which I'm currently debugging, albeit the symptoms are different - in the direct routing case, SYN+ACK is lost: https://cilium.slack.com/archives/C2B917YHE/p1565107102114200?thread_ts=1565022657.102800&cid=C2B917YHE.

**Comment by tgraf** [comment]
This could also explain various other test issues such as #8781

**Comment by brb** [comment]
More info, as managed to reproduce again:

- As said above, the problem is that SYN packet enters TPROXY rule and nothing happens afterwards.
- I checked with strace whether `cilium-envoy` process accepts the connection from the socket listening on the TPROXY redirect port - it doesn't (expected, as `accept4(2)` should return after the TCP handshake).
- Enabled dynamic debugging, and saw the following (expected):
```
[62365.379728] xt_TPROXY: tproxy socket lookup: proto 6 0a0a006a:52128 -> 0a0a00b5:80, lookup type: 1, sock           (null)
[62365.379733] xt_TPROXY: tproxy socket lookup: proto 6 0a0a006a:52128 -> 0a0a00b5:15334, lookup type: 0, sock ffff8f73e51f8000
[62365.379738] xt_TPROXY: redirecting: proto 6 10.10.0.181:80 -> 10.10.0.181:15334, mark: 200
```

**Comment by brb** [comment]
I should have started with top-down approach...

```
-> proxy port 15334: 10.10.0.106:57092 -> 10.10.0.181:80 tcp SYN
xx drop (Stale or unroutable IP) flow 0x85f6c785 to endpoint 0, identity 0->0: 10.10.0.181:80 -> 10.10.0.106:57092 tcp SYN, ACK
```

**Comment by tgraf** [comment]
`10.10.0.106` is the local cilium_host IP?

**Comment by brb** [comment]
> 10.10.0.106 is the local cilium_host IP?
Yes, it's.
