### ISSUE TITLE
CI: K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#8778]
## CI failure
```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
migrate-svc-server pods are not ready after timeout
Expected
    <*errors.errorString | 0xc000530720>: {
        s: "Timeout reached: timed out waiting for pods with filter -l app=migrate-svc-server to be ready",
    }
to be nil
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.10-gopath/src/github.com/cilium/cilium/test/k8sT/Updates.go:269
```
[38714225_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip](https://github.com/cilium/cilium/files/3467693/38714225_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip)

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7963/testReport/junit/Suite-k8s-1/10/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

**Comment by tgraf** [comment]
Looked into https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7980/

The reason is the kvstore lock not being unlocked:
```
2019-08-05T23:37:08.131379355Z level=warning msg="Timeout while waiting for lock, forcefully unlocking..." path="cilium/state/identities/v1/locks/k8s:app=migrate-svc-server;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:zgroup=migrate-svc;" subsys=kvstore
```

**Comment by tgraf** [comment]
Looked into https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/7980/testReport/Suite-k8s-1/10/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

1. According to the kubelet log. Pods can't be scheduled because CNI ADD times out

2. etcd has quorum:
```
KVStore:                Ok   etcd: 1/1 connected, lease-ID=6816c64222eac04, lock lease-ID=6816c64222eac06, has-quorum=true: https://cilium-etcd-client.kube-system.svc:2379 - 3.3.12 (Leader)
```

3. Forceful unlocking is required:
```
pod-kube-system-cilium-9sqmd-cilium-agent.log:2019-08-05T23:40:12.050086528Z level=warning msg="Timeout while waiting for lock, forcefully unlocking..." path="cilium/state/identities/v1/locks/k8s:app=migrate-svc-server;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:zgroup=migrate-svc;" subsys=kvstore
```

**Comment by tgraf** [comment]
Most failures of these tests were related to the readiness probe. Other failures happened while Cilium 1.5 was bootstrapped so it should not be considered a release blocker for 1.6
