### ISSUE TITLE
bug: using ipv4 is not reachable from different cluster nodes

### ISSUE THREAD

**Issue by bretagne-peiqi** [cilium/cilium#878]
encapsulation with dst_host_ip,  which should use dst_node_ip to encap packet to different nodes.

CPU 02: MARK 0x9168bc2f FROM 29381 DEBUG: Encapsulating to node 179634177 (0xab50001) from seclabel 275

**Comment by bretagne-peiqi** [comment]
I think the pb should in common/addressing/ip.go ipv4 section.

**Comment by tgraf** [comment]
Did this turn out to be a non-issue?
