### ISSUE TITLE
ENI: Cilium operator allocates more ENIs than required

### ISSUE THREAD

**Issue by bsiravara** [cilium/cilium#8808]
Can result in exhaustion of IPs in the subnet particularly for large environments

Could be correlated to the cluster scaling up to a higher # of nodes

**Comment by danwent** [comment]
I believe this was fixed and merged into master with https://github.com/cilium/cilium/commit/06bce43ab84170ea281d6741f5adc31a91be6c46 .   @tgraf , please re-open if I am not correct.
