### ISSUE TITLE
Cilium agent fails to install feeder rule

### ISSUE THREAD

**Issue by bsiravara** [cilium/cilium#8814]
INFO [2019-08-03T14:04:26.767554987Z] cilium.io/agent: "Setting up base BPF datapath" subsys=daemon
ERROR [2019-08-03T14:04:28.279607007Z] cilium.io/agent: "Error while initializing daemon" error="cannot install feeder rule []: exit status 4" subsys=daemon
ERROR [2019-08-03T14:04:28.27965417Z] cilium.io/agent: "Error while creating daemon" error="cannot install feeder rule []: exit status 4" subsys=daemon

**Comment by danwent** [comment]
Based on discussion with @brb , this issue is fixed by https://github.com/cilium/cilium/pull/8701 .
