### ISSUE TITLE
Cilium agent fails to install certain IPtables rules into custom chains (“CILIUM_POST”, “CILIUM_FORWARD”) at startup time

### ISSUE THREAD

**Issue by bsiravara** [cilium/cilium#8815]
```
ERROR [2019-08-03T01:46:01.007195625Z] cilium.io/agent: "Command execution failed" cmd="[iptables -t filter -N CILIUM_FORWARD]" error="exit status 1" subsys=iptables
WARN [2019-08-03T01:46:01.0072483Z] cilium.io/agent: "iptables: Chain already exists." subsys=iptables
 ERROR [2019-08-03T01:46:01.007285127Z] cilium.io/agent: "Error while initializing daemon" error="cannot add custom chain CILIUM_FORWARD: exit status 1" subsys=daemon
ERROR [2019-08-03T01:46:01.007329866Z] cilium.io/agent: "Error while creating daemon" error="cannot add custom chain CILIUM_FORWARD: exit status 1" subsys=daemon
```

**Comment by brb** [comment]
This could have happened due to multiple cilium-agent instances running at the same time. However, once there was a single instance, it should have been able to recover from the error.

**Comment by brb** [comment]
https://github.com/cilium/cilium/issues/8856 should fix.

**Comment by danwent** [comment]
we've now had multiple end-user reports that this issue can at least in some circumstances persist across many restarts of the cilium pod.   One user mentioned 15+ minutes.   Another mentioned ~8 restarts while still in CrashloopBackoff.   

So it seems like fixing this is higher priority than when we believe it was just resulting in transient restarts that resolved on their own.

**Comment by tgraf** [comment]
This has been fixed by the user by mounting the tables lock file into the pod.
