### ISSUE TITLE
Operator disregards adaptor limit when doing ENI allocation

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#8830]
```
level=warning msg="Unable to resolve IP deficit of node" error="unable to attach ENI at index 3: AttachmentLimitExceeded: Interface count 4 exceeds the limit for m5.large\n\tstatus code: 400, request id: 76e06519-1ee4-47eb-99cc-2b1f89bea995" instanceID=i-03257a25208a0412c name=ip-192-168-60-230.us-west-2.compute.internal subsys=eni
```

**Comment by ungureanuvladvictor** [comment]
@tgraf I tried to repro this but I'm not unable to do it anymore. I scaled a deployment on my stack to more than 45 replicas which is the limit of an m5.2xl (excluding eth0 allocations). The operator assigned all the IPs to the ENIs and then logged once:

`level=warning msg="Instance is out of ENIs" allocated=4 instanceID=i-0b2c222593d8c4889 max=4 name=ip-192-168-14-23.ec2.internal subsys=eni`

After that you see just the resync kicking in via:
`level=info msg="Resolving IP deficit of node" available=45 instanceID=i-0b2c222593d8c4889 name=ip-192-168-14-23.ec2.internal remainingInterfaces=0 subsys=eni toAlloc=8 used=45`

I'm inclined to close this given I cannot repro anymore. Let me know what do you think.

**Comment by ungureanuvladvictor** [comment]
@tgraf ping on ^^

**Comment by tgraf** [comment]
@ungureanuvladvictor OK, let's close it. Feel free to reopen when you see it again.
