### ISSUE TITLE
Cilium CLI binary is huge

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#8834]
The Cilium CLI binary is too big:

```
$ curl -L http://releases.cilium.io/v1.5.5/cilium-x86_64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 96.9M  100 96.9M    0     0  1182k      0  0:01:23  0:01:23 --:--:-- 1451k
```

On a modest internet connection, it took over a minute to download.

Can we put it on a diet?

**Comment by aanm** [comment]
zipping the file in a tar ball maybe?

1.7 will likely remove 25M as we will remove the code related with container workloads (`pkg/workloads`)

also, don't download random binaries of "http" addresses ;-)

**Comment by joestringer** [comment]
Zipping seems like a reasonable compromise.

Apparently the releases page points to binaries over HTTP, I will follow up with the relevant parties to have this fixed.

**Comment by joestringer** [comment]
I worked around this by not relying upon the binary downloads from the cilium releases website and instead extracting the binary directly from a local pod.
