### ISSUE TITLE
Controller to monitor Cilium iptables rules

### ISSUE THREAD

**Issue by brb** [cilium/cilium#8856]
Currently, the Cilium iptables chains and rules are inserted by `(*Daemon) compileBase()` method. It first removes all the chains and rules, and then tries to install them. The method is being called from multiple places.

The problem with this approach is that during invocation of the method, the chains and rules gets removed which can cause transient connectivity / policy enforcement issues.

To address the problem, the following can be done:

1. Remove / install only the chains and rules which are missing / are in a wrong position.
2. Start a controller which would monitor rules, and in the case a user removes any of the rules, would re-install that rule without removing the rest.

**Comment by brb** [comment]
A user reported an actual drop due to the remove & add: in Docker deployments, removing `CILIUM_FORWARD` chain causes to drop forwarded packets to `cilium_host` due to the default `FORWARD` policy set to `DROP` by Docker.

**Comment by joestringer** [comment]
From cilium weekly meeting: Given the longer-term direction to remove iptables entirely, and how complicated this feature is becoming, it's worthwhile to reconsider whether we want this.

**Comment by brb** [comment]
No longer relevant.
