### ISSUE TITLE
Support security policies for arbitrary interface types inside of pods in chaining mode

### ISSUE THREAD

**Issue by PaulFurtado** [cilium/cilium#8866]
We use ipvlan l2 interfaces in EC2, similar to the lyft CNI plugin, where LAN traffic hits the network via ipvlan interfaces tied to a number of ENI interfaces and some routing is done via a veth interface through the host. Currently cilium supports ipvlan in l3 mode, but not when chaining. I started hacking on making it work with chaining by calling the existing ipvlan setup functions on an interface already created, and that worked, but didn't handle the veth interface and also dropped all packets if the ipvlan interface was in l2 mode. Additionally, for some critical performance pods, we pass in an entire ENI adapter rather than an ipvlan slave device so they get dedicated queuing/buffers/interrupts/etc.

I think the cilium datapath optimizations are amazing, but we really need the security policies more than anything. It seems like it should be possible to have it support a chaining mode where it simply applies ingress (and maybe egress) policies to every interface it discovers inside the pod, leaves the datapath alone, and does nothing on the host side other than writing BPF datastructures that it uses globally in the namespaces and the service routing mode that hooks `connect`/`sendmsg`. If this worked, then it could support chaining on top of absolutely any CNI plugin, and then have optimizations for specific configurations. So it'd be something like treating pods NICs as if they were normal server NICs, but sharing whatever maps possible for efficiency.

Is there anything technical that makes this challenging to support?

Thanks!

**Comment by tgraf** [comment]
> I think the cilium datapath optimizations are amazing, but we really need the security policies more than anything. It seems like it should be possible to have it support a chaining mode where it simply applies ingress (and maybe egress) policies to every interface it discovers inside the pod, leaves the datapath alone

Yes, this is exactly what the new chaining architecture is about in 1.6. The PR to document the feature for several plugins is available here:
https://github.com/cilium/cilium/pull/8874

It currently works for veth based CNI plugins. @lbernail and others are running this mode on top of lyft-cni and can provide more details as well.

> Currently cilium supports ipvlan in l3 mode, but not when chaining. I started hacking on making it work with chaining by calling the existing ipvlan setup functions on an interface already created, and that worked, but didn't handle the veth interface and also dropped all packets if the ipvlan interface was in l2 mode

The "generic-veth" chaining plugin will disable ARP handling entirely and just pass it through so it will be compatible with any L2 plugin as well. See https://github.com/cilium/cilium/blob/master/plugins/cilium-cni/chaining/generic-veth/generic-veth.go for details

> If this worked, then it could support chaining on top of absolutely any CNI plugin, and then have optimizations for specific configurations. So it'd be something like treating pods NICs as if they were normal server NICs, but sharing whatever maps possible for efficiency.

Yes, exactly. This is exactly what the generic-veth plugin does. It looks for a veth inside the pod namespace, tracks the host-facing peer and attaches the BPF program there to perform policy, load-balancing and whatever else you want.

If you are interested in ENI, you might also want to have a look at the new native ENI mode:
https://docs.cilium.io/en/latest/concepts/ipam/eni/
https://docs.cilium.io/en/latest/concepts/datapath/#aws-eni

**Comment by lbernail** [comment]
> It currently works for veth based CNI plugins. @lbernail and others are running this mode on top of lyft-cni and can provide more details as well.

In our case we use the Lyft ipam plugin and a custom interface plugin (single veth instead of ipvlan + veth to host, similar to the aws eks cni plugin) to benefit from cilium generic chaining

Down the road we would be interested in a single ipvlan interface in pods without a veth but that would require traffic redirection to access the host (probably in the ebpf code loaded on the ipvlan interface)

**Comment by tgraf** [comment]
This has been implemented with the "generic veth chaining" feature.
http://docs.cilium.io/en/v1.6/gettingstarted/cni-chaining-generic-veth/
