### ISSUE TITLE
Quick Install - Fails mounting BPF crio due to multiple mount points

### ISSUE THREAD

**Issue by ToroNZ** [cilium/cilium#8869]
**General Information**

- Cilium version (run `cilium version`)
  - v1.6.90
- Kernel version (run `uname -a`)
  - 5.2.7-816.native
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
  - v1.15.2
- Link to relevant artifacts (policies, deployments scripts, ...)
  - https://raw.githubusercontent.com/cilium/cilium/master/install/kubernetes/quick-install.yaml
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**

1. Paso 1
  - kubeadm init on master running on Clear Linux using crio
2. Paso 2
  - kubectl apply -f https://.../quick-install.yaml
3. Paso 3
  - Get the following error on the cilium pods:
```
level=info msg="Cilium 1.6.90 a96d7f4fe 2019-08-06T11:32:30-07:00 go version go1.12.7 linux/amd64" subsys=daemon                                                                                                                    
level=info msg="cilium-envoy  version: 2e42144f26667ddee9f5d2506019f16c57386b29/1.11.0-dev/Modified/RELEASE/BoringSSL" subsys=daemon                                                                                                
level=info msg="clang (7.0.0) and kernel (5.2.7) versions: OK!" subsys=daemon                                                                                                                                                       
level=info msg="linking environment: OK!" subsys=daemon                                                                                                                                                                             
level=info msg="bpf_requirements check: OK!" subsys=daemon                                                                                                                                                                          
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf                                                                                                                                                          
level=fatal msg="Unable to mount BPF filesystem" error="multiple mount points detected at /sys/fs/bpf" subsys=bpf
```
FYI - Deploying the old way works every time:
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/1.6-backports-19-07-25/examples/kubernetes/1.15/cilium-crio.yaml

From a quick look it seems that the crio specific deployment doesn't mount /sys/fs/bpf which looks to be the main issue.

Cheers

**Comment by aanm** [comment]
Hello @ToroNZ thanks for open this issues. To install Cilium with crio one should follow the following http://docs.cilium.io/en/latest/kubernetes/configuration/?#crio please let us know if you are still having issues.

**Comment by tgraf** [comment]
@ToroNZ Did this resolve your issue?

**Comment by ToroNZ** [comment]
Folks... Yes, that'd do it.

Thanks for the pointer, not a fan of Helm but hopefully Helm3 changes my mind.

Gracias!

close #8869

**Comment by manicole** [comment]
Hello, up on this issue.

I'm installing a multi-cri cluster via Kubespray :
- master, node1,  node2 using docker as container runtime
- node3 using containerd as CR
- node4 using cri-o as CR

When adding node3, I had to reinstalll cilium-operator (https://raw.githubusercontent.com/cilium/cilium/v1.6/install/kubernetes/quick-install.yaml) to make it agnostic to the used CR. Now "container-runtime" is set to "none" in cilium-config configmap.

When addind node4, I get the same error as @ToroNZ 
 ```txt
level=fatal msg="Unable to mount BPF filesystem" error="multiple mount points detected at /sys/fs/bpf" subsys=bpf
```
The thing is I do not want to set a "global.containerRuntime.integration" other than "none" as advised in http://docs.cilium.io/en/latest/kubernetes/configuration/?#crio, as you can understand.

Any clue on how to make Cilium work on my node4 ? Thanks

**Comment by aanm** [comment]
@manicole for node4 you need a different daemonset, a daemonset specific for crio. Because CRIO already mounts the bpf fs the daemon set does not need to contain such volume. My advise here is to use 2 daemonsets, one for master, node1, node2 and node3, and other for node4. You can specify which nodes the daemonset will be running by specifying nodeselector field.

**Comment by manicole** [comment]
@aanm, thanks for answering. I tried it and it worked (hm, or at least it led me to the next error). Thank you !

**Comment by aanm** [comment]
> @aanm, thanks for answering. I tried it and it worked (hm, or at least it led me to the next error). Thank you !

@manicole feel free to open a new GH issue if you face any issue. Thanks

**Comment by manicole** [comment]
@aanm, thanks for answering. I tried to deploy a new Cilium daemonset, identical to the previous one excepted it focuses on node4. It worked ok for a while (pods from node4 & node2 can curl each another), but node4 turned out to be NotReady due to Cilium Daemonset being not ready himself ...

Cilium original operator (deploying Cilium pods on node1, node2, node3) : 
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  creationTimestamp: "2020-01-07T10:38:37Z"
  generation: 1
  labels:
    k8s-app: cilium
    kubernetes.io/cluster-service: "true"
  name: cilium-crio
  namespace: kube-system
  resourceVersion: "922944"
  selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/cilium-crio
  uid: a951b074-72ae-4a5e-8a5e-9edd7de6f577
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: cilium
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]'
      creationTimestamp: null
      labels:
        k8s-app: cilium
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - args:
        - --config-dir=/tmp/cilium/config-map
        command:
        - cilium-agent
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CILIUM_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CILIUM_FLANNEL_MASTER_DEVICE
          valueFrom:
            configMapKeyRef:
              key: flannel-master-device
              name: cilium-config
              optional: true
        - name: CILIUM_FLANNEL_UNINSTALL_ON_EXIT
          valueFrom:
            configMapKeyRef:
              key: flannel-uninstall-on-exit
              name: cilium-config
              optional: true
        - name: CILIUM_CLUSTERMESH_CONFIG
          value: /var/lib/cilium/clustermesh/
        - name: CILIUM_CNI_CHAINING_MODE
          valueFrom:
            configMapKeyRef:
              key: cni-chaining-mode
              name: cilium-config
              optional: true
        - name: CILIUM_CUSTOM_CNI_CONF
          valueFrom:
            configMapKeyRef:
              key: custom-cni-conf
              name: cilium-config
              optional: true
        image: docker.io/cilium/cilium:v1.6.5
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - /cni-install.sh
          preStop:
            exec:
              command:
              - /cni-uninstall.sh
        livenessProbe:
          exec:
            command:
            - cilium
            - status
            - --brief
          failureThreshold: 10
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: cilium-agent
        readinessProbe:
          exec:
            command:
            - cilium
            - status
            - --brief
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/cilium
          name: cilium-run
        - mountPath: /host/opt/cni/bin
          name: cni-path
        - mountPath: /host/etc/cni/net.d
          name: etc-cni-netd
        - mountPath: /var/lib/cilium/clustermesh
          name: clustermesh-secrets
          readOnly: true
        - mountPath: /tmp/cilium/config-map
          name: cilium-config-path
          readOnly: true
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /run/xtables.lock
          name: xtables-lock
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command:
        - /init-container.sh
        env:
        - name: CILIUM_ALL_STATE
          valueFrom:
            configMapKeyRef:
              key: clean-cilium-state
              name: cilium-config
              optional: true
        - name: CILIUM_BPF_STATE
          valueFrom:
            configMapKeyRef:
              key: clean-cilium-bpf-state
              name: cilium-config
              optional: true
        - name: CILIUM_WAIT_BPF_MOUNT
          valueFrom:
            configMapKeyRef:
              key: wait-bpf-mount
              name: cilium-config
              optional: true
        image: docker.io/cilium/cilium:v1.6.5
        imagePullPolicy: IfNotPresent
        name: clean-cilium-state
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/cilium
          name: cilium-run
      nodeSelector:
        kubernetes.io/hostname: node4
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cilium
      serviceAccountName: cilium
      terminationGracePeriodSeconds: 1
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
        name: cilium-run
      - hostPath:
          path: /opt/cni/bin
          type: DirectoryOrCreate
        name: cni-path
      - hostPath:
          path: /etc/cni/net.d
          type: DirectoryOrCreate
        name: etc-cni-netd
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - name: clustermesh-secrets
        secret:
          defaultMode: 420
          optional: true
          secretName: cilium-clustermesh
      - configMap:
          defaultMode: 420
          name: cilium-config
        name: cilium-config-path
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
```

Cilium operator foor node4 : 
```yaml
```

**Comment by aanm** [comment]
@manicole did you write anything in this issue? I see a notification on my email but I don't see anything here.

**Comment by manicole** [comment]
I did, but removed it. I was not sure if the issue I met was related to Cilium or Kubespray, and it actually seem to be relevant to post it here.

As I said, I deployed another Cilium DaemonSet, similar to the original one but removing Volumes and VolumeMounts /sys/fs/bpf and using a nodeSelector to deploy a Cilium Pod on node4 exclusively.

It seemed to work, I could even curl pods (nginx) from any node to node4, so communication was working.

Then suddenly my Cilium Pod on node4 failed (running but not ready anymore), causing my node4 to be NotReady ...
I tried
*  ```sh kubectl get event``` returns no event
*  ```sh kubectl describe daemonset <newly-created-ds> -n kubesystem``` returns no event
*  ```sh kubectl describe pod <newly-created-cilium-pod-from-ds> -n kubesystem``` returns no event
*  ```sh kubectl logs <newly-created-cilium-pod-from-ds> -n kubesystem``` returns connection refused

Any clue of what's happening and/or how to debug ? Thanks

**Comment by Rolinh** [comment]
@manicole Did you apply https://github.com/kubernetes-sigs/kubespray/pull/5438 to adjust the cilium config for 1.6.5 or did you just bump the cilium version in your kubespray config? If not, would you try the patch and report back?

**Comment by aanm** [comment]
Also, try getting the `kubectl logs --previous`

**Comment by manicole** [comment]
I used Cilium v1.6.4 on my previous try.

I now upgraded it to v1.6.5 (resetting the cluster with Cilium v1.6.4 and creating it again with Cilium v1.6.5) and now I get

```txt
`FAILED! => {"changed": false, "msg": "Unable to start service crio: A dependency job for crio.service failed. See 'journalctl -xe' for details.\n"}`
```

when installing cri-o on node4 ... I guess it's now another problem I should deal with in cri-o / Kubespray GitHubs.
Thanks for helping !
