### ISSUE TITLE
Uninstall Cilium Completely

### ISSUE THREAD

**Issue by vjykrthk** [cilium/cilium#8872]
I ran this command to uninstall Cilium since my kernel does not meet the requirement.

kubectl --namespace kube-system delete ds cilium

But I am getting this error

  Warning  FailedCreatePodSandBox  52m  kubelet, k8s-node-1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "cc28ec6aaf65c6267067a75d13ab2c2ce92112e9b47d155f2c9117779e913b66" network for pod "grpc-hello-client-864496cc65-6rdqs": NetworkPlugin cni failed to set up pod "grpc-hello-client-864496cc65-6rdqs_default" network: unable to retrieve configuration from cilium-agent: Get http:///var/run/cilium/cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
  Normal   SandboxChanged          25m (x142 over 54m)  kubelet, k8s-node-1  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  20m (x158 over 51m)  kubelet, k8s-node-1  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "8b8f16e354055d27c62fb22e9596d94a092fec3e0f8f5d4b027e7eee46da0c7e" network for pod "grpc-hello-client-864496cc65-6rdqs": NetworkPlugin cni failed to set up pod "grpc-hello-client-864496cc65-6rdqs_default" network: unable to retrieve configuration from cilium-agent: Get http:///var/run/cilium/cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory

**Comment by tgraf** [comment]
The CNI configuration is left behind and you need to remove it from the node.
