### ISSUE TITLE
Do not create CT entries if the packet is a fragmented IP

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#8884]
Have a CT map based on the 5 tuple is not enough, one should account for the ID of the IP packet in the CT entry to handle IP fragments as IP fragments do not have TCP ports. If we do not support IP fragmentation the datapath should not even handle such packets.

More info: https://github.com/cilium/cilium/pull/8882

**Comment by pchaigno** [comment]
@probot #10264 will fix this.

**Comment by tgraf** [comment]
Fixed by https://github.com/cilium/cilium/pull/10264
