### ISSUE TITLE
CNP NodeStatus update scalability issues

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#8897]
CNP NodeStatus updates the state of each CNP, per-node. In a large environment, this means that even with rate-limiting of the Kubernetes apiserver interactions, that a ton of patches will be made against the apiserver. 

- [x] short-term: Provide a means of opting out of this behavior for scalability.
- [x] long-term: offload apiserver interactions to `cilium-operator` in conduit with `kvstore` updates.

**Comment by ianvernon** [comment]
The logical move is to do what we have done to reduce apiserver load, which is to offload this responsibility to `cilium-operator`. Each `cilium-agent` can update the key-value store with the key being the K8s UUID of the resource + a reference (like we have for identities - `prefix/identity/IP of node`) and then information about that node's realization of that CNP. `cilium-operator` can then watch for this prefix from the key-value store, and then patch each CNP at a given cadence with the current status of nodes in the cluster, removing old node status updates as it does now. The operator can also bound the number of total CNP updates with some form of rate-limiter as well. 

We can maintain the existing functionality for the kvstore-free mode.

**Comment by ianvernon** [comment]
Requirements for scalable CNP Status updates using the kvstore:

* We only use the kvstore if there is `Patch` capability in Kubernetes for CNP NodeStatus.
    - This is so we can directly update the resource in K8s from `cilium-operator` without having to do a `Get` first. This will halve the interactions with `kube-apiserver`, reducing the load put upon it.

Design proposal:


* CNP update is pushed to us from our Kubernetes watcher logic
* Determine whether we can offload to kvstore based off configuration + current state
    - if `option.Config.K8sEventHandover` is not enabled, do not offload to kvstore (update the status in the CNPs directly)
    - if `option.Config.K8sEventHandover` is enabled, but we do not meet `Patch` capabilities, do not offload to kvstore
    - if `option.Config.K8sEventHandover` is enabled, and we do meet `Patch` capabilities, but the kvstore isn't configured yet, Patch the CNP directly
        - Disadvantage: this means that if Cilium is deployed a cluster all at once (e.g., after restart), that the kube-apiserver will receive an update per-node * per-CNP at bootstrap. This might put undue load on the kubernetes-apiserver
        - Alternatively, we could queue up events locally until we have kvstore connectivity and then send them all at once to the kvstore. This may result in memory spikes if kvstore connectivity takes a while and there are a lot of CNPs.
    - if `option.Config.K8sHandover` is enabled, and we meet `Patch` capabilities, and the kvstore isn't configured yet, add key-value pair to kvstore with prefix `cilium/state/cnpstatus/<cnp namespace>/<cnp name>/<node identifier>`
* `cilium-operator` will watch for the `cilium/state/cnpstatus` prefix
    - Upon deletion of a given CNP, all keys with prefix `cilium/state/cnpstatus/<cnp namespace>/<cnp name` will be deleted as well.
    - Upon receiving a modify / creation event for a given key, `cilium-operator` will aggregate patches to perform on the CNP's status and perform them in a bounded manner (e.g., limited number of goroutines), with updates being ratelimited in some manner (perhaps per-CNP or for all CNPs to avoid undue stress on the K8s apiserver).

**Comment by aanm** [comment]
> Requirements for scalable CNP Status updates using the kvstore:
> 
> * We only use the kvstore if there is `Patch` capability in Kubernetes for CNP NodeStatus.
>   
>   * This is so we can directly update the resource in K8s from `cilium-operator` without having to do a `Get` first. This will halve the interactions with `kube-apiserver`, reducing the load put upon it.
> 

This shouldn't be required. We always use the kvstore regardless of the capabilities available.

> Design proposal:
> 
> * CNP update is pushed to us from our Kubernetes watcher logic

By 'us' I assume `cilium-agent` and `cilium-operator`.

> * Determine whether we can offload to kvstore based off configuration + current state
>   
>   * if `option.Config.K8sEventHandover` is not enabled, do not offload to kvstore (update the status in the CNPs directly)

^ This should be the only condition.

>   * if `option.Config.K8sEventHandover` is enabled, but we do not meet `Patch` capabilities, do not offload to kvstore
>   * if `option.Config.K8sEventHandover` is enabled, and we do meet `Patch` capabilities, but the kvstore isn't configured yet, Patch the CNP directly
>     
>     * Disadvantage: this means that if Cilium is deployed a cluster all at once (e.g., after restart), that the kube-apiserver will receive an update per-node * per-CNP at bootstrap. This might put undue load on the kubernetes-apiserver
>     * Alternatively, we could queue up events locally until we have kvstore connectivity and then send them all at once to the kvstore. This may result in memory spikes if kvstore connectivity takes a while and there are a lot of CNPs, since we stream all of these at once from Kubernetes upon agent bootstrap.

^ we can ignore this

>   * if `option.Config.K8sHandover` is enabled, and we meet `Patch` capabilities, and the kvstore is configured, add key-value pair to kvstore with prefix `cilium/state/cnpstatus/<cnp namespace>/<cnp name>/<node identifier>`

^ If the kvstore is not configured the `option.Config.K8sHandover` should not be considered, i.e., the handover does not happen.

> * `cilium-operator` will watch for the `cilium/state/cnpstatus` prefix
>   
>   * Upon deletion of a given CNP, all keys with prefix `cilium/state/cnpstatus/<cnp namespace>/<cnp name` will be deleted as well.
>   * Upon receiving a modify / creation event for a given key, `cilium-operator` will aggregate patches to perform on the CNP's status and perform them in a bounded manner (e.g., limited number of goroutines), with updates being ratelimited in some manner (perhaps per-CNP or for all CNPs to avoid undue stress on the K8s apiserver).

Should be per-CNP, the global rate limiting already happens in the k8s client. The update/patch should happen every N seconds or whenever all nodes have updated their status, whichever comes first.

**Comment by ianvernon** [comment]
> This shouldn't be required. We always use the kvstore regardless of the capabilities available.

My motivation here was not having to fetch the resource from K8s to update it if patching is not available. But, I think that measuring empirically is the way to go to see how much stress is put on the K8s apiserver in the current mode vs. in the kvstore mode, so I will unconditionally send to kvstore.

> ^ we can ignore this

Do you mean ignoring the case entirely due to the fact that we will always send to kvstore regardless of if patching is enabled or not?

The kvstore not being configured yet is a case I am wondering about. What are your thoughts on queueing up events for CNPs locally and then sending once we receive kvstore connectivity?

> Should be per-CNP, the global rate limiting already happens in the k8s client. The update/patch should happen every N seconds or whenever all nodes have updated their status, whichever comes first.

👍

**Comment by ianvernon** [comment]
One thing I am unsure of is how we are going to pass the `Annotations` of the CNP as part of the value. This could create quite large values in the kvstore. Should this be of concern?

**Comment by aanm** [comment]
@ianvernon if the kvstore is not configured there's not really any scalability issue with CNPs.

**Comment by aanm** [comment]
> One thing I am unsure of is how we are going to pass the `Annotations` of the CNP as part of the value. This could create quite large values in the kvstore. Should this be of concern?

@ianvernon No, the full CNP is already a value in the etcd's PoV.

The key will be `cilium/state/cnpstatus/<cnp namespace>/<cnp name>/<node identifier>` for which it has the node lease attached to it.
The value will be the `CiliumNetworkPolicyNodeStatus` structure marshaled into JSON.

**Comment by ianvernon** [comment]
Some thoughts I've had while auditing my code for potentially race-condition-y behavior (answer - there is some!) in https://github.com/cilium/cilium/pull/9384 with respect to the cilium-operator handling the CiliumNetworkPolicyNodeStatus updates. On the operator side, I have the key-value store watcher which watches for create / modify events for the keys (<prefix/namespace/name/nodeName --> marshaled CNPNodeStatus). My thought was that I can create a controller per CNP which we communicate with via a channel created in the key-value store watcher. The lifecycle of this channel / controller is that it is created for the given CNP by namespace/name if it doesn’t exist in the mapping of namespace/name --> event channel. When we receive an event for a given CNP, we send the information to this channel, and the controller handles it at a bounded interval to avoid overloading the K8s apiserver.
The issue I am having though, is that I need to know when to stop these controllers... Simply stopping them / deleting the channel upon CNP deletion from the watcher side in the cilium-operator isn’t enough because the key-value store watcher may be ‘slower’ than the CNP watcher from K8s - and we will clean up the channel / controller in the watcher, only to create it again from the key-value store side. We treat the entry not being in the map as an impetus to create an entry, but this ignores these ordering problems. Basically, the lack of ordering between the key-value store watcher and the CNP watcher is somewhat stumping me given how I’ve designed it currently, so I think it’s back to the drawing board in terms of how to handle these events in the cilium-operator.
I’m trying to think of other ways to manage the lifecycle of these controllers launched per-CNP. One way was tracking the number of NodeStatus keys in the key-value store for the given CNP and using that as some means of reference counting; zero keys for a CNP would mean that it was deleted, and we’d eventually GC those controllers over time once the amount of keys goes to zero. This would require periodically listing all of the keys for the prefix <prefix/namespace/name in the key-value store. In terms of making sure that this is a good way to ensure that we can clean up the controllers, I think that the ways the keys would be deleted would be the following: lease expiry some time after node deletion, and deletion explicitly from each node when the CNP is deleted. However, I’m not sure if we can reliably guarantee that every node will receive the delete event for a CNP (due to the DeletedFinalStateUnknown aspect of things on the K8s side).
