### ISSUE TITLE
SpecsEqual method on CiliumNetworkPolicy object could be more nuanced

### ISSUE THREAD

**Issue by willdeuschle** [cilium/cilium#8902]
## Proposal / RFE

**Is your feature request related to a problem?**

When creating a CNP whose endpoint selector is the wildcard, it is not possible to test for equality using the `SpecsEqual` method on the CNP struct.

Consider my workflow: I have a controller that creates CNPs in response to some event. The first time that event occurs:
1. I instantiate the CNP I wish to create. It happens to have a wildcard endpoint selector (either by leaving the `EndpointSelector` field blank or by adding it with empty LabelSelectors)
2. I try to get that CNP from the k8s apiserver using a CiliumNetworkPolicy client (this is to check to see if the CNP already exists, in which case I need to update)
3. That CNP doesn't yet exist, so I submit the CNP I instantiated to the apiserver

The second time that event occurs:
1. I instantiate the CNP I wish to create (it will be an update in this case, because a CNP with the same name and in the same namespace already exists). Again, it has the wildcard endpoint selector (either by leaving the `EndpointSelector` field blank or by adding it with empty LabelSelectors)
2. I try to get that CNP from the k8s apiserver using a CiliumNetworkPolicy client (this is to check to see if it already exists, in which case I need to update)
3. That CNP already exists! This means I need to update the CNP. However, first I'd like to make sure that the one I've instantiated and the one I've retrieved from the apiserver aren't identical (because then there's no reason to resubmit)
4. I compare the CNP I've instantiated with the existing CNP. However, using the `SpecsEqual` method will always return false, even if they are the exact same CNP created via the same codepath. The reason seems to have to do with how CNPs are deserialized when getting them from the k8s apiserver using a CiliumNetworkPolicy client. The implementation of `SpecsEqual` just uses `reflect.DeepEqual`, which is insufficient.

**Describe the solution you'd like**

The `SpecsEqual` method could be more nuanced. I've gotten around this for now by checking that the CNP `Spec` and `Specs` are either
1) deeply equal (using the `SpecsEqual` method)
Or
2) each field in the `Spec`/`Specs` is deeply equal except for the `EndpointSelector` (using `reflect.DeepEqual`), and the `EndpointSelector` is the wildcard (via the `isWildcard` method)

**Comment by aanm** [comment]
@willdeuschle just one thing to be clarified, in your `1.` you say that `Spec` and `Specs` should be deeply equaled, using the `SpecsEqual`. But isn't this the case already?

https://github.com/cilium/cilium/blob/fa2629c4e1c8009a65ba25c2e7dafc7b76b5e1ba/pkg/k8s/apis/cilium.io/v2/types.go#L170-L177

**Comment by willdeuschle** [comment]
yes @aanm. I was trying to indicate that I first use the `SpecEquals`, but that is not always sufficient, so then I also need to check via number 2. It ends up being an OR of 1. and 2.

**Comment by joestringer** [comment]
> it has the wildcard endpoint selector (either by leaving the EndpointSelector field blank or by adding it with empty LabelSelectors)

I don't think that `EndpointSelector` being "blank" (`nil`) is a valid setting. In Cilium we will call `r.Spec.Sanitize()` or `rule.Sanitize()` on each rule inside `r.Specs` to ensure that we get a valid, canonical form of the selector.

**Comment by joestringer** [comment]
It would be good to get example `pkg/checker/checker.DeepEqual()` comparison output between the different CNP objects to determine what is being considered different between the `Spec`/`Specs`/ in the different CNPs.

**Comment by willdeuschle** [comment]
To follow up here - @joestringer and I determined that this was ultimately a difference between the submitted CNP and the sanitized version that was actually persisted. Specifically, a nil endpoint selector becomes 

```EndpointSelector: ciliumapi.EndpointSelector{
				LabelSelector: &metav1.LabelSelector{
					MatchLabels:      map[string]string{},
					MatchExpressions: []metav1.LabelSelectorRequirement{},
				},```

This was causing problems because the codepath that creates this CNP also checks to see if it's equivalent to one that is already persisted. The only follow up here may be to perform the sanitization during the equality check so that others don't hit this edge case. I'll defer to you on what you want to do about this @joestringer

**Comment by joestringer** [comment]
I was thinking about this, and figured that it's a bit weird conceptually to mix up sanitization and equality checks together; for one thing, this requires more effort to validate potentially both structures every time you check if they're equal.

I have a different proposal (already briefly discussed with @willdeuschle out-of-band): Maybe we can provide better rule constructor functions that will ensure that right from CNP creation, the CNPs are sanitized such that if you programmatically construct these objects and inject them into k8s, then when you retrieve the same CNP back out from k8s, it will already be equal.

We have some basics of this, but I think there are ways that library users can shoot themselves in the foot:

https://github.com/cilium/cilium/blob/e7bc8918daf8a3c8b599f1ec84a3ee7544249f62/pkg/policy/api/rule.go#L65-L86

Specifically, Cilium doesn't really assign a meaning to an empty set of selectors. It's not meaningful for a rule to select nothing; such a rule is by definition ineffective. So we might consider changing `NewRule()` to match all traffic by default. Perhaps something like this:

```
// NewRule builds a new rule that applies policy to all endpoints.
// To select specific endpoints, extend this Rule using WithEndpointSelector(). 
// This rule will not deny any traffic by default. To place the selected endpoints
// into default deny and allow specific communication with this endpoint,
// extend this rule using `WithIngressRules()` or `WithEgressRules()`.
func NewRule() *Rule {
    ...
}
```

Then we could perhaps add constructors that alternatively only put a single direction for selected endpoints into default deny:

```
// NewIngressWhitelist creates a new rule that places endpoints selected by the
// specified selector into default deny mode. Traffic matched by the specified
// rules will be allowed to access the endpoint.
func NewIngressWhitelist(es EndpointSelector, rules []IngressRule) {
    ... 
}
```

Beyond something like this, there may be ways that we can ease the construction of `CiliumNetworkPolicy` objects using the above as well.

**Comment by willdeuschle** [comment]
After having thought about this for a little while and considered our own use cases, the bespoke constructors like `NewIngressWhitelist` are probably overworked. They would be convenient, but are likely not worth maintaining IMO.

That being said, I think the modification to `NewRule` that you're proposing would be great.

Right now, for all of my CNPs (because they are namespace-local and thus select all endpoints), I end up tacking this onto all of our CNPs to avoid the sanitization issue described above:

```
EndpointSelector: ciliumapi.EndpointSelector{
    LabelSelector: &metav1.LabelSelector{
	MatchLabels:      map[string]string{},
	MatchExpressions: []metav1.LabelSelectorRequirement{},
    },
},
```

I'd much prefer to do something like `NewRule().WithEgressRules(...)` and know that I won't have issues with sanitization inconsistencies. Given a nil endpoint selector defaults to selecting all endpoints right now anyways, it seems logical that `NewRule` should explicitly set this up.

**Comment by joestringer** [comment]
@willdeuschle given the lack of activity on this issue, I think you've managed to figure out a path forward so I'm going to go ahead and close the issue. Feel free to respond here or file a new issue if there are other improvements that could be made.
