### ISSUE TITLE
Enable DSR for LoadBalancer traffic

### ISSUE THREAD

**Issue by danderson** [cilium/cilium#8979]
## Proposal / RFE

(filing this per request on Twitter, https://twitter.com/ciliumproject/status/1163916359878754306)

**Is your feature request related to a problem?**

LoadBalancer traffic on Kubernetes must currently choose between two not-great options. If you use `externalTrafficPolicy: Cluster`, the traffic gets SNATed and you lose client IP information. If you use `externalTrafficPolicy: Local`, with most LB implementations you get uneven traffic distribution between pods if there is >1 pod/node.

**Describe the solution you'd like**

The ideal state for LoadBalancer traffic is: preserve the source IP, _and_ do LB to spread connections evenly across all pods. But to make this work, the network layer has to do DSR for the response packets, or have enough conntrack state to forward the packet back along the same datapath as the input (which requires either fancy tunneling, or cross-node distribution of conntrack data).

So, with `externalTrafficPolicy: Cluster`, the input packet path should be `<somewhere outside the cluster> -> Node A (does LB, picks a target pod, does DNAT but _not_ SNAT) -> Node B (forwards to target pod) -> Pod`, and the output path should be `Pod -> Node B (does SNAT so that src=service IP) -> <somewhere outside the cluster, back to the client IP>`.

With `externalTrafficPolicy: Local`, the path doesn't change, you still do balancing to pods on localhost only, same as today, no fancy logic required.

I don't know if Cilium can execute this safely (respecting network policies etc.), but if it can, it would be the obviously best network addon to use for LoadBalancers on bare-metal clusters. On clouds, it's a little bit more complicated because some clouds make smart balancing decisions outside the cluster when `externalTrafficPolicy: Local` is enabled... But most of them do not, and for those, this DSR balancing should also be a significant improvement.

The context I'm coming from is that I wrote MetalLB (https://metallb.universe.tf), and the limitation of "source IP _or_ evenly spread connections" is a common source of frustration for bare metal cluster owners. I would love to be able to tell them "just use Cilium, you will get all the good behaviors and none of the bad ones" :)

**Comment by danderson** [comment]
I should add: the description above of how `externalTrafficPolicy` behaves is based on how kube-proxy implements it today. It's possible Cilium already does something smarter than this, I haven't had time to test-drive Cilium 1.6 and its "100% kube-proxy replacement" yet :)

**Comment by brb** [comment]
@danderson Thanks for opening the issue.

We are currently discussing the DSR support, as this would significantly simplify the NodePort BPF implementation due to making the BPF SNAT obsolete in the case NodePort.

As we do not distribute conntrack entries among nodes, either tunneling or embedding a service ID into the IP header of a packet will be required which could be not feasible for IPv4.

OT: MetalLB in the L2 mode currently doesn't work with the BPF replacement of kube-proxy - https://github.com/cilium/cilium/issues/9116.

**Comment by borkmann** [comment]
Initial DSR support merged into master via #9473 #9895. Thanks a lot @danderson!
