### ISSUE TITLE
Fix extraneous warning messages for CEP synchronization of health endpoint

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9017]
### Summary

If the cilium-health endpoint is broken, then each time it is restarted a log shows up like this in the logs for the previous iteration of the health endpoint:

```
level=warning msg="Unable to delete CEP" containerID= controller="sync-to-k8s-ciliumendpoint (1532)" datapathPolicyRevision=2 desiredPolicyRevision=2 endpointID=1532 error="resource name may not be empty" identity=4 ipv4=192.168.30.159 ipv6= k8sPodName=/ 
subsys=endpointsynchronizer
```

### Impact

Extraneous warning messages in the logs in some corner cases.

### Discussion

I'm not sure whether the health EP is successfully added into the k8s CEP in the first place, but clearly the `k8sPodName` above looks invalid. We should investigate and silence this warning (For instance by ensuring that the resource name is non-empty before attempting to delete the CEP).

The log message from above can be found here:
https://github.com/cilium/cilium/blob/1233b1fa85eb1429dc3448d230eaef52016b7ef0/pkg/k8s/endpointsynchronizer/cep.go#L245

**Comment by mrostecki** [comment]
I did the same which was already done on update. https://github.com/cilium/cilium/blob/1233b1fa85eb1429dc3448d230eaef52016b7ef0/pkg/k8s/endpointsynchronizer/cep.go#L97-L107

Debug messages will still allow to investigate the issue deeper if we will want to.
