### ISSUE TITLE
kube-proxy-free: connect to multiple kube-apiservers

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9018]
Currently, for Kubernetes deployments w/o kube-proxy, we ask users to specify only one kube-apiserver non-virtual IP addr + port. This overrides the `KUBE_SERVICE_{HOST,PORT}` env vars of the cilium-agent pod, which makes cilium-agent's k8s client to connect to that particular kube-apiserver (see #8995 for this hack reasoning).

In the case of multi-master setup, cilium-agent won't be able to connect to any other than the specified kube-apiserver, as the non-virtual IP addr + port is used. This is not ideal, as a) HA property is lost, b) load is non-evenly distributed among masters.

Instead, we should ask users to provide kube-apiserver non-virtual IP addr + port just for bootstrapping, so that all master could be used after a list of kube-apiserver endpoints has been received.

**Comment by JrCs** [comment]
Is it possible to use a vip (manage by an external LoadBalancer) for the kube-apiserver ?
In my case i use openstack as my cloud provider and use it's loadbalancer (haproxy) to proxy connections to the kube-apiserver to the kube-apiservers that are listen on the master nodes.

**Comment by brb** [comment]
@JrCs If that VIP is reachable from hosts running Cilium, then yes. You can pass the VIP (and port) via the `global.k8sService{Host,Port}` params, see http://docs.cilium.io/en/v1.6/gettingstarted/kubeproxy-free/.

**Comment by brb** [comment]
As mentioned by @aanm in https://github.com/cilium/cilium/pull/9089#issuecomment-526646341, most of HA installations have an external LB which points to kube-apiserver instances. Therefore, this issue is not relevant at the moment.

If anyone has a non-standard HA architecture which might benefit from this issue, please comment it here. Otherwise, I'm closing the issue for now.
