### ISSUE TITLE
CI: cilium-operator sometimes takes 5+ minutes to become ready in k8s 1.10 tests

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#9041]
The 1.10 tests seem to take about 30 minutes longer than the 1.15 tests. It also runs net-next and so runs some more tests. In any case, there are clear gaps in the logs when bringing up cilium-operator (grep for "waiting for cilium-operator"). This happens in 1.15 but it is much less severe (a few seconds vs minutes).

**Comment by raybejjani** [comment]
Running some sanity checks, it seems to be something between 1.10 and net-next
k8s 1.10 with not-net-next: doesn't happen
k8s 1.15 with net-next: doesn't happen
Disabling DatapathConfiguration tests: still happens

**Comment by tgraf** [comment]
Theory: Could be related to the componentstatus related ping

**Comment by raybejjani** [comment]
This is now gone on master, since we updated to k8s 1.11 :/ it still happens on the 1.6 branch, however.

**Comment by raybejjani** [comment]
I'll close this for now but I'll keep an eye out for it (I've definitely told everyone about it ;) )
