### ISSUE TITLE
Support datapath of choice CNI chained with Cilium networking inside pod netns

### ISSUE THREAD

**Issue by krsna1729** [cilium/cilium#9042]
## Proposal / RFE

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Ability to use other CNIs to plumb datapath (only) in which most/all stack processing happens within pod netns to exit the machine - ipvlan L2, macvlan, sriov, etc.,. In a way this can be thought of as making the current ipvlan logic, plus missing pieces, an option in CNI chaining framework, `cni.chainingMode=podnetns`. The other CNI would bring in just pipe of choice into pod ns, and networking is done by cilium, inside the pod netns.

https://cilium.slack.com/archives/CDKG8NNHK/p1566508318010500

**Comment by krsna1729** [comment]
@brb does socket based load balancing (and DSR) make the above easier? The routing part will still be missing when exiting from within the namespace I think.

**Comment by brb** [comment]
@krsna1729 The socket-level LB helps only with enabling k8s SVC for the above. However, have you seen https://github.com/cilium/cilium/pull/10251?

**Comment by krsna1729** [comment]
@brb thanks for referencing. On the surface it looks like it is ipvlan specific vs generic-veth. Will read up more.
