### ISSUE TITLE
Support Service sessionAffinity

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9076]
Kubernetes allows to specify a session affinity for a Service: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#sessionaffinityconfig-v1-core. Currently, only `clientIP` is supported. This makes connections from a particular client to be routed to the same backend.

The implementation of the affinity in `kube-proxy` is based on the `recent` iptables module: https://github.com/kubernetes/kubernetes/blob/v1.15.3/pkg/proxy/iptables/proxier.go#L1163.

**Comment by borkmann** [comment]
User bug report in Cilium slack: https://cilium.slack.com/archives/C1MATJ5U5/p1573561149107300

**Comment by borkmann** [comment]
Context: JrCs from slack: ```Seem to have "another" bug. I've update the sessionAffinity in the service (of type LB) to ClientIP, but the sticky session is not working. The traffic is always distribute to all the pods. [...] yes i use nodeport with external lb [...] do i just need to start kube-proxy without changing anything the values of the cilium 1.6.x deployment ? [...]```
