### ISSUE TITLE
DNS matchpatterns only allow host name syntax, not full domain name syntax

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9083]
We have had user reports that they are attempting to use DNS policy in conjunction with domain names in their network that begin with an underscore (`_`).

Reviewing the `pkg/fqdn/matchpattern/matchpattern.go` code it appears that we have restricted users to the RFC1123 [host name syntax](https://tools.ietf.org/html/rfc1123#page-13) rather than the RFC2181 [DNS name syntax](https://tools.ietf.org/html/rfc2181#section-11) (excerpt below):

> The DNS itself places only one restriction on the particular labels
   that can be used to identify resource records.  That one restriction
   relates to the length of the label and the full name.  The length of
   any one label is limited to between 1 and 63 octets.  A full domain
   name is limited to 255 octets (including the separators).

This means that if any L7 DNS policy is in place (including basic FQDN allow-all), requests to such domains will be denied and there is no way to allow them without changing the code or relaxing the policy.

**Comment by joestringer** [comment]
Should we really continue to limit the character set handled by the proxy given that we do not match more specifically on particular record types that could otherwise further restrict the character set that is allowed?

https://tools.ietf.org/html/rfc1123#page-79
>  The DNS defines domain name syntax very generally -- a
                 string of labels each containing up to 63 8-bit octets,
                 separated by dots, and with a maximum total of 255
                 octets.  Particular applications of the DNS are
                 permitted to further constrain the syntax of the domain
                 names they use, although the DNS deployment has led to
                 some applications allowing more general names.

**Comment by raybejjani** [comment]
With ascii characters (but really any unicode since we're using go regexes) this is just a validation side limitation. The issue arises when the matchers we use are on arbitrary data and not on a subset of ascii. This might make the lookups faster if we end up with the right data structure but it is more complex.
In the no-limits case, what is the syntax we support? and how do we define the wildcard? (I mean how we type it in, not how we match it internally). Would we add a new `match*` field to do this?

**Comment by joestringer** [comment]
One dimension to this is that the matchers must be able to be validly encoded in both JSON and YAML for the policy to be imported (I guess technically only JSON is required since we serve the policy as JSON but most users will configure it in YAML which we must then be able to render in JSON), related links..

https://tools.ietf.org/html/rfc7159#section-8
https://yaml.org/spec/1.2/spec.html#id2770814

I'm not really aware of a particular language specification that attempts to define the language we're accepting in the policy right now, but the very basics seem to be something like:
1. Asterisk (`*`) represents a match on anything, equivalent to regex `.*`
1. All other characters, including period (`.`) are treated as a literal
1. The match is anchored, that is to say, it will not apply if it only selects part of the domain name. For example, `foo.*` will not match `bar.foo.*`.

But then if we're going to allow a wider set of characters and translate to regex then we should ensure that any other special regex characters should be properly escaped to follow rule #2 above..

I don't mind just adding `_` to the accepted set for now, users can and will complain when it's too restrictive, just means they have to wait for a subsequent release to fix up the use case for them. Just means we have to rinse & repeat each time there is another corner case.

**Comment by joestringer** [comment]
I believe that the primary issue affecting users was addressed and backported to v1.5. We haven't heard anything more recently, so opting to close the issue.

Please comment or open an issue if this restriction affects your use of policy.
