### ISSUE TITLE
Enable proxy visibility without influencing policy

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#9088]
When enabling proxy redirection, it currently requires a policy with L7 rules to be configured. This obviously has side effects as it enables default deny for applied endpoints.

Many use cases require L7 visibility without the side effect of affecting policy enforcement as well, i.e. enablement of L7 visibility should not change the default allow behavior of a pod and combination with additional policy rules should not be overwritten via the L7 visibility configuration.

- [x] Add ability to add an annotation to a pod to enable L7 visibility via configurable proxy on configurable port.
- [x] L7 visibility enables proxy redirect but does not change policy enforcement.
- [x] L7 visibility policy is applied if policy would allow the visibility redirect

TODO's / follow-ups:

- [ ] Remove need to force policy computation to make sure that pointer comparison in policy map syncing fails.
- [ ] Make L4Filter compose VisibilityMetadata.
- [x] Apply visibility policy in cases where policy does apply for a given l4 port / protocol.

**Comment by ianvernon** [comment]
A few questions regarding the annotation - what constitutes a "configurable proxy" - would this be something like `io.cilium.annotation:80/HTTP`? is the "configurable" part of the proxy based off of the protocol used? Envoy is for HTTP + Golang extensions, Kafka is for the kafka proxy, and DNS is for the DNS proxy. Is this what you were envisioning, @tgraf ?

**Comment by ianvernon** [comment]
Things to investigate - lifecycle of an annotation - can we apply it per-deployment and have that annotation present on all pods launched by that deployment? This is simple to experiment with in a sandbox environment.

**Comment by ianvernon** [comment]
Need to consider the following combinations:

* Proxy visibility without policy imported
* Proxy visibility + policy enforcement

How does traffic direction come into play here?

**Comment by ianvernon** [comment]
Something similar had previously been done with 'ingress visibility policy' - would be good to resurrect that code, which will not be implemented the same, but may provide us with useful insight into various use cases that need consideration.

**Comment by joestringer** [comment]
Be aware that https://github.com/cilium/cilium/issues/9083 could plausibly lead to DNS denies if we implement a simple redirect with DNS rules that allow `*`. That said it's pretty unlikely and dependent on FQDN schemes used within the cluster.

**Comment by joestringer** [comment]
Additional questions:

* Is it fine for this visibility policy to apply to all L3 peers or should there be an L3-dependent mechanism?
* When folding against a network policy that is l3-only or l3-dependent l4, will it result in a change to denial behaviour, ie should visibility policy also convert L4 denies into L7 denies, thereby providing visibility into L3/L4 policy rejections in addition to the L3/L4 allows?

**Comment by joestringer** [comment]
Answering my questions from the Cilium meeting today:

* Visibility policy will apply to all L3 peers for a given direction, port, protocol.
* L4 drop will not be converted to L7 deny when visibility is applied to traffic which is otherwise dropped.

Main target is that this L7 visibility will integrate on top of, for example, no policy; or regular L3 policy, without having any impact on enforcement.

**Comment by ianvernon** [comment]
First PR with visibility applying only when policy enforcement does not apply is coming soon. I am writing an end-to-end test, after which it will be ready for review.

**Comment by ianvernon** [comment]
Right now, the only way to tell if the proxy-visibility annotation is correctly plumbed is via doing `cilium bpf policy get <endpoint ID>`. It would be nice to specify via some user-facing API (`kubectl describe pod`, `cilium endpoint get`) that the visibility policy is implemented. One possibility is removing the visibility policy stuff from being done via annotations, and performed via a CRD instead. This would give us validation, status, etc. cc: @genbit

**Comment by joestringer** [comment]
The base functionality of this works right now, we're looking for more feedback from users on how it works and whether it needs to be supported in conjunction with policy before diving into the remaining items.
