### ISSUE TITLE
MTU issue when using "encrypt-node"

### ISSUE THREAD

**Issue by lbernail** [cilium/cilium#9112]
When we send packets at MTU size (or close to it) between 2 nodes with encrypt-node enabled they are dropped.

All tests on a host with jumbo frames enabled on the physical interface (MTU=9001)

Using a simple ping command I found out that the maximum size I can use is 8842 for ping which results in and ethernet payload of 8850 bytes and an encrypted payload of 8904 bytes
After 8843 (payload: 8851) I see the clear packet on cilium_host but not on the main interface (after encryption)
After 8897 bytes (payload: 8905) I see that the clear packet is fragmented on cilium_host (which makes sense because the IP header is 20 bytes and the route mtu is set to 8924 to account for encryption overhead).

If I understand the datapath correctly, this happens:
1 - packet is routed to cilium_host by the main table
2 - additional metadata (in particular encryption mark) is added by eBPF code
3 - packet is routed again to cilium_host by table 200
4 - packet is encrypted
5 - packet is routed again to cilium_host by table 200
6 - eBPF code rewrites IP/mac addresses

My initial guess was that the packet was dropped at step 5 (because the payload was too large for the route). I assumed removing the mtu for the route in table 200 would work but it does not solve the issue

It seems that after the packet is encrypted at step 4, the lookup is done using the main table and not table 200 (if I change the MTU on this route, everything works). I think this behavior depends on the kernel version (I tested on the last Ubuntu releases, which use kernels 4.18 and 5.0).

**General Information**

- Cilium version (run `cilium version`): 1.6 rc6
- Kernel version (run `uname -a`): `5.0.0-1011-aw`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): Kubernetes 1.14
- Tunneling disabled
- Subnet mode (no pod cidrs on hosts)

**How to reproduce the issue**

1. Enable `encrypt-node`
2. Send a packet with a size close to the MTU

**Additional notes**
Since we use the same interface and the same route at step 1 (initial packet routing and MTU setting) and 5 I don't think we can use the MTU. I have a prototype that instead of modifying the MTU is modifying advmss on the routes and initial results look promising (but of course, this means TCP only). Very simple prototype commit here: https://github.com/DataDog/cilium/commit/58a65589c9293c599eea74e772dd5d79ef58f624

Down the road, for kernels not necessarily relying on the main route table for the post-encryption lookup I think we could have different MTUs on the main route table and in table 200 which should solve the problem better. We could for instance modify the route Upsert function and add a boolean to specify whether we want to take the encryption overhead into account (for routes on the main table) or not (for routes in table 200)

cc @jrfastab

**Comment by jrfastab** [comment]
Resolved. 
```
commit 4fa378534d02d7a8502c144076a01c8b26470b56
Author: Laurent Bernaille <laurent.bernaille@datadoghq.com>
Date:   Thu Sep 19 16:43:40 2019 +0200

    Use output-mark to use table 200 post-encryption and set different MTU for main/200 tables
```
