### ISSUE TITLE
NodePort BPF does not work with MetalLB

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9116]
Reported by a user, that MetalLB in L2 mode doesn't work with the BPF NodePort.

AFAIK, MetalLB L2 responds to an ARP request for a virtual IP assigned to LB. So, a request to a service has a dstIP=the virtual IP which makes the request to bypass the BPF NodePort SVC lookup as it doesn't have an IP addr of a netdev running the NodePort BPF program.

We should probably introduce a flag which would enable the wildcard SVC lookup on bpf_netdev.

**Comment by brb** [comment]
> We should probably introduce a flag which would enable the wildcard SVC lookup on bpf_netdev.

Alternatively, we could create the mapping `LB VIP => backends` in the BPF SVC map, as the LB VIP should be known to cilium-agent: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#finding-your-ip-address. However, with this approach we would run into the same SNAT remote backend issue as ExternalIP did, because an LB port can be outside the NodePort range.

**Comment by brb** [comment]
As per https://twitter.com/bradfitz/status/1173379692377718785, it seems that Cilium w/o kube-proxy doesn't work with MetalLB in BGP mode either.

**Comment by cehoffman** [comment]
Sorry if this doesn't add any knew information, but since there had been a few related MRs close to this issue I had hoped it might be working in the new RC.

I tried with 1.7.0-rc1 (no kube-proxy) and MetalLB 0.8.3 in L2 mode and had no luck. I see that traffic enters the node on the the load balancer IP and service port, but it doesn't appear to go anywhere.  I can access the service on the associated node port that is created.

I have the same setup with flannel networking, calico policy, kube-proxy services, and MetalLB working.

I think this is obvious, but adding kube-proxy back into the mix gets the load balancer working.

**Comment by brb** [comment]
@cehoffman Thanks for reporting. Can you attach `kubectl get svc -o yaml` output for the LoadBalancer services?

With the ExternalIP feature being merged, fixing this issue should be trivial.

**Comment by cehoffman** [comment]
Sure, and I think I have an idea where things may be getting messed up. The nodes default devices share the network segment with the load balancer, so I think the line

`level=info msg="Blacklisting local route as no-alloc" route=192.168.1.0/24 subsys=ipam` 

maybe indicative of why there is not a listener created.

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-04-19T03:52:32Z"
  labels:
    app.kubernetes.io/name: sab
  name: sab
  namespace: default
  resourceVersion: "109628405"
  selfLink: /api/v1/namespaces/default/services/sab
  uid: 8fad1bf6-6256-11e9-b0f6-26c6b08ddf2d
spec:
  clusterIP: 10.3.154.48
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.52
  ports:
  - name: http
    nodePort: 30255
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: sab
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.52
```

**Comment by brb** [comment]
> Sure, and I think I have an idea where things may be getting messed up. 

The problem is that we currently do not provision services with the `loadBalancerIP` field being set. I'm going to fix this soon.

**Comment by cehoffman** [comment]
Alright, look forward to that. Had hoped a temporary solution might be to just remove the field and take whatever IP metalLB gives out, but that didn't change the experience.

**Comment by brb** [comment]
@cehoffman Could you try the `cilium/cilium-dev:metallb-v0` image to test whether MetalLB works in your case? Thanks.

**Comment by cehoffman** [comment]
@brb happy to report that `cilium/cilium-dev:metallb-v0` results in routable traffic to the backend pods for the MetalLB IPs. Verified with no kube-proxy running and a full reboot of nodes to clear any state.
