### ISSUE TITLE
Reuse client when doing http probing

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9136]
The client that should be reused is on line 246

https://github.com/cilium/cilium/blob/9a9aa413d4b8fde1c1efd14e373f75026383d437/pkg/health/server/prober.go#L235-L246

**Comment by ArthurChiao** [comment]
I've looked at this piece of code during investigation. But, won't this `client` be garbage-collected and its connection released after this function finishes? @aanm

**Comment by aanm** [comment]
@ArthurChiao it will but the `http.DefaultTransport` reuses connections already established so there's no point in creating a new client for each `httpProbe`

**Comment by ArthurChiao** [comment]
Yes, so this is an improvement, not the root cause of the increasing of `OpenFDs`, am I right?

**Comment by aanm** [comment]
@ArthurChiao it can be the root cause the increase of `OpenFDs` because they are not reused.

**Comment by brb** [comment]
> it can be the root cause the increase of OpenFDs because they are not reused.

I think all instances of `client` will be GC'd, and thus the corresponding FDs will be closed.
