### ISSUE TITLE
CiliumIdentities (in CRD) are never GC

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9147]
https://github.com/cilium/cilium/blob/32d6166f7f0dd4bf1fdbc5953c6d5ebe19b1c6d1/pkg/k8s/identitybackend/identity.go#L207-L209

**Comment by aanm** [comment]
Fixed #9152

**Comment by Sh4d1** [comment]
@aanm is it really fixed ? The function still return nil :thinking: 
I have a cluster with more than 50 000 entries of cilum identity in etcd
