### ISSUE TITLE
kvstore: Transaction support for multiple key/value pairs

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#915]
## Summary:
Proposal to improve the kvstore interactions.

## kvstore requirements:
 - Must be implementable with etcdv3 and consul
 - Multiple agents interact with the kvstore in parallel
 - Retrieve or allocate the identity (uint32) for a list of labels (binary key). The same label key must resolve to the same identity for all nodes.
 - Retrieve list of all security identities
 - Retrieve or allocate ID (uint32) of a service (loadbalancer). The same service (matching IP, port, protocol) must resolve to the same service ID.
 - Store node prefix => node IP mapping

## Status Quo:
All atomic operations are performed by taking a distributed lock on the key to allocate the IDs. This is expensive and slow. The kvstore has no way to optimize write operations by keeping order of write correct.

### Step 1: ID allocation
- key: { service | identity | ... } definition, value: identity
1. GET(key), if found, return
2. GET range of keys, pick key in sequence that is not taken
3. CAS create with NotExists condition, no TTL, on failure: repeat
4. On success, use ID

Special case: agent crashes between step 3 and 4: A GC go subroutine in each agent will run every 10 min or hour and look for IDs which have no users (see reference counting in next section) and remove the allocated IDs.

## Step 2: Reference counting
1. In addition, each node inserts a key. Keys share a common prefix which is the current key followed by a suffix which is node specific. This allows to list all keys matching the existing key prefix which will return the keys of all nodes. This avoids nodes to fight over a key to update the reference count.
2. Each node inserts the key with a ttl/lease which expires if not renewed accordingly.
3. When the last key has expired, the resource is automatically deleted. Each node has a GC which does a CAS operation to watch for keys which have expired to remove the mapping.

**Comment by aanm** [comment]
From the cilium meeting my understanding is that you don't want to see any holes in the available security IDs assigned. If that's correct we might have a problem:

Assuming something happens to the cilium-agent, the containers on that host will have some security ID associated, `foo=bar => 1`. If the cilium-agent never comes up after, for example, an hour, we might end up with conflicting IDs assigned to a different containers running different labels on a second host `foo=world => 1`.

containers `foo=bar` will be able to talk with whatever node that accepts `foo=world`

**Comment by tgraf** [comment]
> Assuming something happens to the cilium-agent, the containers on that host will have some security ID associated, foo=bar => 1. If the cilium-agent never comes up after, for example, an hour, we might end up with conflicting IDs assigned to a different containers running different labels on a second host foo=world => 1.
> 
> containers foo=bar will be able to talk with whatever node that accepts foo=world

How is this related to having holes in the allocation map or not? This is a generic problem in how we do reference counting. The TTL should probably be longer than an hour. Can you think of an alternative?

**Comment by tgraf** [comment]
Partially merged in #1365
