### ISSUE TITLE
CI: Support for managed k8s:

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#9167]
- EKS
- GKE
- minikube
- microk8s

Supporting issues:
Refactor CI container registry to allow remote test execution https://github.com/cilium/cilium/issues/9245
Add override scheme for common CI dev targets https://github.com/cilium/cilium/issues/9246

**Comment by raybejjani** [comment]
Not complete, but https://github.com/cilium/cilium/pull/9189 is a start

**Comment by ianvernon** [comment]
Based off of discussion in Slack, we should also decouple the requirement that we have nodes with specific names (k8s1 and k8s2), for instance - we should ideally be able to templatize this based off of state in the cluster, or be able to pick pods which are not running on the same node to test multinode connectivity. 

Context: https://cilium.slack.com/archives/C7PE7V806/p1570133729028700

**Comment by tgraf** [comment]
This has been completed
