### ISSUE TITLE
Porting init.sh logic to Go

### ISSUE THREAD

**Issue by bretagne-peiqi** [cilium/cilium#920]
could it be better if we refactor init.sh scripts  into go language ? or there is no necessary for that.
（I saw we use directly iproute2 for network config）

**Comment by tgraf** [comment]
We would love to move to native golang implementation and remove the dependency on the scripts and iproute2. Issue #325 covers the creation of a library to load BPF programs directly but we can start moving code from init.sh into golang right away.

**Comment by ti-mo** [comment]
@vadorovsky I've reassigned this to @nathanjsweet, this is now on the roadmap for 1.11.

The goal is to lift & shift the script verbatim to Go, so at least we can remove the shell script and start swapping out specific parts with native Go code. (e.g. in the middle of the script)

As long as it's written in shell, we can only migrate logic at the start or end of the script, or the script needs to be modified to be executed in multiple phases. This would become rather messy.

**Comment by ti-mo** [comment]
Closing this in favor of milestone https://github.com/cilium/cilium/milestone/38.
