### ISSUE TITLE
Support policies across all namespaces

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9200]
Sometimes there are situations where it would be convenient to have a way to configure a set of common hosts that everything can talk to (for example, DNS, or other common infrastructure), regardless of namespace. Currently the user must create one policy for each namespace of their app, and recreate the common policy pieces for every other policy.

This feature request is to track demand for allowing some sort of global policy that could apply across all namespaces.

**Comment by ianvernon** [comment]
We could support having annotations which remove the namespace selector if it is not explicitly set.

**Comment by olemarkus** [comment]
Very interested in this
