### ISSUE TITLE
BPF map dump_interrupts should not be considerd as cilium_datapath_errors

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9212]
A user got confused by the following metric:

```
# HELP cilium_datapath_errors_total Number of errors that occurred in the datapath or datapath management
# TYPE cilium_datapath_errors_total counter
cilium_datapath_errors_total{area="conntrack",family="ipv4",name="dump_interrupts"} 515950
```

`dump_interrupts` happens when a BPF entry gets removed while dumping the map is in progress. This is not an error, thus we should move it to some other counter which doesn't have `error` in its name.

**Comment by Antiarchitect** [comment]
Having many of this (~400K) in my dashboard.

**Comment by Antiarchitect** [comment]
bump maybe

**Comment by youssefazrak** [comment]
@brb regarding the `DatapathErrors` counter, it seems to be used only for the `dump_interrupts`.
Wouldn't it be simpler to rename `DatapathErrors` and all the string prints by removing the error part? `Subsystem` will stay the same.
Also, I can take care of this one.

**Comment by brb** [comment]
@youssefazrak Your suggestion makes sense. Just make sure that we don't forget to document the metrics name in [the upgrade guide](https://github.com/cilium/cilium/blob/master/Documentation/operations/upgrade.rst).
