### ISSUE TITLE
For k8s dual-stack POD ipv6 addresses are not assigned from the configured CIDR

### ISSUE THREAD

**Issue by uablrek** [cilium/cilium#9214]
## Bug report

I file this as a bug, but it is a bit unfair since k8s dual-stack is not release yet.

When using `cilium` in k8s dual-stack the ipv6 addresses for PODs seems to be taken from `f00d::b00:0:0:0/80` (`f00d::11.0.0.0:0:0:0/80`). While this works, that is not the configured range.

In k8s dual-stack the `kube-controller-manager` is configured with a 2-item array, for example;
```
--cluster-cidr=11.0.0.0/16,1100::/16
```
In the first release both ipv4 and ipv6 must have the same maskbits /16 in this case. This is a temporary constraint and will be fixed later.

K8s will assign ranges to each node, but the new in dual-stack is the `podCIDRs` attribute in the k8s node objects;
```
    "spec": {
        "podCIDR": "11.0.3.0/24",
        "podCIDRs": [
            "11.0.3.0/24",
            "1100:300::/24"
        ]
    },
```
The POD ipv6 addresses shall be taken from "1100:300::/24" in this case.

**General Information**

- Cilium version (run `cilium version`)
  v1.6.1
- Kernel version (run `uname -a`)
  `Linux vm-005 5.1.7 #11 SMP Tue Sep 17 10:09:10 CEST 2019 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
  K8s; `v1.16.0-rc.1`
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO

**How to reproduce the issue**

1. Use K8s v1.16.0-rc.1 which includes the dual-stack support
2. Use `--feature-gates IPv6DualStack=true` to k8s binaries and configure ranges where appropriate
3. Install cilium with `quick-install.yaml` but with `enable-ipv6: "true"`
4. Check the assigned podIPs

**Comment by aanm** [comment]
I already have the patch on my side that fixes this. I was waiting for #9139 to be merged first.

**Comment by khenidak** [comment]
we really didn't work on any CNI support for dualstack yet :-) it is coming in phase 3 (v1.17)

**Comment by uablrek** [comment]
But CNI-plugins with dual-stack support seem to work fine. So what is the K8s part in this? Is it not more a CNI-plugin problem. I think cilium and calico support for dual-stack enables more users.

**Comment by khenidak** [comment]
It was not in scope. If dualstack works fine for anything other than kubenet, then it was not due to work we have been testing or working on hence i can not trust it or advise deploying. I know it sounds silly, but we progress piece by piece, having CNI as part of our initial work would have over complicated things as we will have to have worked on too many fronts at the same time.
