### ISSUE TITLE
CI log gathering is broken on master

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9224]
Fix the following issues in the Jenkins CI sysdump gathering:

* [ ] Runtime tests gather empty files (also affects eg `cmds.log` in k8s test runs)
* [x] K8s tests gather files with the following contents:
  ```
  OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"kubectl\": executable file not found in $PATH": unknown
  command terminated with exit code 126
  ```

**Comment by joestringer** [comment]
Runtime example build: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/3522/testReport/junit/(root)/Suite-runtime/RuntimeConnectivityInVethModeTest_Basic_Connectivity_test_Test_NAT46_connectivity_between_containers/

(Empty files)

K8s PR example: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/8630/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan/

(Note inside the zip files prefixed with `log-gatherer` have the `OCI runtime exec failed` contents.)

**Comment by raybejjani** [comment]
I'm not sure that it's related but when my tests have failed on EKS the run is stuck collecting logs forever. I don't remember if the log-gatherer stuff replaced everything but in case it's related...

**Comment by joestringer** [comment]
`cmds.log` is still empty in k8s test runs. Everything else in k8s seems to be working correctly.

**Comment by joestringer** [comment]
Apparently this doesn't bother anyone enough to do something about it, so I'll close it out.
