### ISSUE TITLE
Cannot configure datapath config for debug dynamically

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9225]
At runtime, after running `cilium config Debug=true`, the endpoints are not reconfigured to gather debug notifications at the datapath level; `cilium monitor -v` does not print any of the debug notifications.

Should this reconfigure each endpoint's configuration to enable this option?

**Comment by joestringer** [comment]
Note that there is also `cilium endpoint config xxx Debug=True`.

**Comment by aanm** [comment]
> At runtime, after running `cilium config Debug=true`, the endpoints are not reconfigured to gather debug notifications at the datapath level; `cilium monitor -v` does not print any of the debug notifications.
> 
> Should this reconfigure each endpoint's configuration to enable this option?

IMO, yes. It will be enabled for new created endpoints so why isn't configured for old endpoints? There's also this GH issue standing #8035 which is related
