### ISSUE TITLE
encryption: document kernel requirements for various encrypt features

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#9230]
Documentation does not state minimum required kernel versions for the various encryption modes. Basic encryption with default options works all the way back to 4.9 but advanced usage, such as encrypt-node with subnets, requires kernel helper calls that do not exist back that far.

Add some documentation to track these.

**Comment by joestringer** [comment]
Seems like we've collected many of the requirements here (#14852) and we don't need two issues to track this. I've assigned that one to you, will close this out.
