### ISSUE TITLE
The performance of cilium-istio is not good

### ISSUE THREAD

**Issue by wsdlll** [cilium/cilium#9244]
## Support

linux version: 4.20.17-042017-generic
kubernetes version: v1.15.3
istio version: v1.2.5
cillium verion: v1.4 (i have try the 1.6.1, but not good)

I have try to use the guide in "https://docs.cilium.io/en/v1.5/gettingstarted/istio/" to test the perf of cilium-istio.

And there is the follow error happen when enable the sockmap.

Name                               Last success   Last error   Count   Message
  bpf-map-sync-cilium_ep_to_policy   never          37s ago      156     64 map sync errors

And the performance of cilium-istio is not better than native istio

200 thread, 4U8G

cilium-istio about 5000 QPS
native istio about 8000 QPS

Please help me
Have can i improve it

**Comment by aanm** [comment]
@wsdlll sorry to hear that. Can you attach a cilium sysdump? https://cilium.readthedocs.io/en/v1.6/troubleshooting/?#automatic-diagnosis

**Comment by wsdlll** [comment]
There are too many files in output .zip to find the useful information.

How can i find the problem?

Unable to sync EpToPolicy Map continue with Sockmap support: %!s(<nil>)

Is there a problem with the kernel version?
__________________

- apiVersion: cilium.io/v2
  kind: CiliumEndpoint
  metadata:
    creationTimestamp: "2019-09-21T09:10:50Z"
    generation: 1
    name: nginx-644479448b-s2f2c
    namespace: default
    resourceVersion: "372822"
    selfLink: /apis/cilium.io/v2/namespaces/default/ciliumendpoints/nginx-644479448b-s2f2c
    uid: a22e5812-0df6-4249-9c01-1ecfd2db8b15
  status:
    external-identifiers:
      container-id: 87845298c70a72d18f752dfaab5aadfaffe162928ab63363d33d6e8276b97278
      container-name: k8s_POD_nginx-644479448b-s2f2c_default_91682ff6-8736-46ce-a20a-b0de310cc707_0
      pod-name: default/nginx-644479448b-s2f2c
    health:
      bpf: OK
      connected: true
      overallHealth: OK
      policy: OK
    id: 2564
    identity:
      id: 30917
      labels:
      - k8s:io.cilium.k8s.policy.cluster=default
      - k8s:io.cilium.k8s.policy.istiosidecarproxy=true
      - k8s:io.cilium.k8s.policy.serviceaccount=default
      - k8s:io.kubernetes.pod.namespace=default
      - k8s:run=nginx
    log:
    - code: Warning
      message: 'Unable to sync EpToPolicy Map continue with Sockmap support: %!s(<nil>)'
      state: regenerating
      timestamp: "2019-09-21T09:10:41Z"
    networking:
      addressing:
      - ipv4: 10.217.1.13
    policy:
      egress:
        enforcing: false
      ingress:
        enforcing: false
    state: ready
    status:
      identity:
        id: 30917
        labels:
        - k8s:io.cilium.k8s.policy.cluster=default
        - k8s:io.cilium.k8s.policy.istiosidecarproxy=true
        - k8s:io.cilium.k8s.policy.serviceaccount=default
        - k8s:io.kubernetes.pod.namespace=default
        - k8s:run=nginx
      log:
      - code: Warning
        message: 'Unable to sync EpToPolicy Map continue with Sockmap support: %!s(<nil>)'
        state: regenerating
        timestamp: "2019-09-21T09:10:41Z"
      networking:
        addressing:
        - ipv4: 10.217.1.13

**Comment by aanm** [comment]
@wsdlll it would be helpful to us if you could provide the .zip cilium sysdump.

**Comment by wsdlll** [comment]
This is the .zip cilium sysdump. Please check it.

[cilium-sysdump-20190923-092103.zip](https://github.com/cilium/cilium/files/3650162/cilium-sysdump-20190923-092103.zip)

**Comment by jrajahalme** [comment]
Sockops do not currently work for Istio sidecars, see #11039.

**Comment by murphye** [comment]
Out of curiosity, what is the explanation for the performance degradation vs. plain Istio without sockops...
