### ISSUE TITLE
Refactor CI container registry to allow remote test execution

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#9245]
_This is mostly here for record-keeping. nebril may correct this ticket once it's clearer what is needed_

We currently run the docker container registry for tests inside k8s1, one of the test VMs. The tests themselves can take an arbitrary image source, however, and this means we can run CI on managed k8s but reuse the current CI infrastructure. In particular, this allows us to reuse the jenkins node to build the various cilium images without having a separate, new, build cluster.

**Comment by joestringer** [comment]
@nebril is this improvement still necessary or is it already implemented?
