### ISSUE TITLE
Add override scheme for common CI dev targets

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#9246]
We want to target various managed k8s platforms from the CI, but may also want to encode the setup to streamline developer iteration with common setups like:
- minikube
- microk8s
- EKS
- GKE

I'll also try to make it easy to encode overrides for arbitrary clusters, like the dev-vm, but I'm not sure how to do this without more yuckiness.

**Comment by joestringer** [comment]
I think this is basically achieved now, we have targets for all of the listed environments.
