### ISSUE TITLE
CI: Suite-runtime.RuntimeLB With Containers validates service recovery on restart

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9282]
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
Service list does not match
Expected
    <string>: "...p": "\u003c..."
to equal               |
    <string>: "...p": "10.15...."
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/runtime-gopath/src/github.com/cilium/cilium/test/runtime/lb.go:193
```

```
Sep 25 21:46:11 runtime cilium-agent[32692]: level=debug msg="adding frontend and backend to SVCMap" backend="10.15.113.126:80" backendIndex=2 frontend="2.2.2.2:80" subsys=loadbalancer
Sep 25 21:46:11 runtime cilium-agent[32692]: level=debug msg="Controller func execution time: 18.495112ms" name=consul-lease-keepalive-0xc0005a9200 subsys=controller uuid=e4229748-dfdd-11e9-9419-080027b8a826
Sep 25 21:46:11 runtime cilium-agent[32692]: level=warning msg="Unable to list services in services BPF map" error="Unable to lookup element in map with file descriptor 14: invalid argument" subsys=daemon
Sep 25 21:46:11 runtime cilium-agent[32692]: level=debug msg="Restoring service" l3n4Addr="{IP:2.2.2.2 L4Addr:{Protocol:NONE Port:80}}" subsys=service
Sep 25 21:46:11 runtime cilium-agent[32692]: level=info msg="Restored services from BPF maps" failedServices=0 restoredServices=1 subsys=daemon
```

```
cmd: "sudo cilium service list -o json" exitCode: 0 duration: 58.125921ms stdout:
[
  {
    "spec": {
      "backend-addresses": [
        {
          "ip": "\u003cnil\u003e"
        },
        {
          "ip": "10.15.113.126",
          "port": 80
        }
      ],
      "flags": {},
      "frontend-address": {
        "ip": "2.2.2.2",
        "port": 80
      },
      "id": 1
    },
    "status": {
      "realized": {
        "backend-addresses": [
          {
            "ip": "\u003cnil\u003e"
          },
          {
            "ip": "10.15.113.126",
            "port": 80
          }
        ],
        "flags": {},
        "frontend-address": {
          "ip": "2.2.2.2",
          "port": 80
        },
        "id": 1
      }
    }
  }
]
```

[62321914_RuntimeLB_With_Containers_validates_service_recovery_on_restart.zip](https://github.com/cilium/cilium/files/3656946/62321914_RuntimeLB_With_Containers_validates_service_recovery_on_restart.zip)

**Comment by brb** [comment]
`BPF_MAP_LOOKUP_ELEM` failed with `EINVAL` invoked by `LookupElementFromPointers` (https://github.com/cilium/cilium/blob/master/pkg/bpf/bpf_linux.go#L142). Unfortunately, I can't see which BPF map corresponded to `fd=14`.

There are a few cases for `EINVAL` to be returned to the `BPF_MAP_LOOKUP_ELEM` syscall - https://github.com/torvalds/linux/blob/v4.9/kernel/bpf/syscall.c:

- The unused attribute fields contained some garbage: https://github.com/torvalds/linux/blob/v4.9/kernel/bpf/syscall.c#L283.
- The map FD ops didn't match the BPF map ops: https://github.com/torvalds/linux/blob/v4.9/kernel/bpf/syscall.c#L222.

/cc @borkmann

**Comment by brb** [comment]
Could be related: https://github.com/cilium/cilium/blob/886c2c82e7381cfb3f37b94c9d98caafe657afa1/pkg/maps/lbmap/ipv6.go#L325 has a wrong padding. `u32` is the correct one (I'm going to open a PR).

**Comment by joestringer** [comment]
This is not being tracked in context of any particular project, and from the PR comments seems like it's only been hit a couple of times.

Looks like it's not that pressing of an issue and is unlikely to see movement without more information.

Closing. Feel free to reopen if you have a build + sysdump.
