### ISSUE TITLE
ExternalIP service fails to apply rev NAT xlation when running w/o kube-proxy

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9285]
Reported by a user:

> We found that when accessing an endpoint B whose has an ExternalIP from Pod A, if A and B are in the same host, there are always connection resets. Digging into the problem, we found that A connects to B via B's ExternalIP (VIP), but B acks with its real IP (PodIP), so A will treat this as an invalid packet and RESET it, and continue to waiting B's VIP's response.

Cilium: v1.6.0
Kernel: v4.14

**Comment by joestringer** [comment]
I would suggest upgrading to confirm that the bug is still present. We had already some fixes in 1.6.1/1.6.2 for this kind of issue.

**Comment by ArthurChiao** [comment]
Thanks, then I will try `1.6.2` (later) and come back to report the result. @joestringer @brb 

Could you list those commits related to this?  @joestringer

**Comment by joestringer** [comment]
It depends on the datapath configuration you have, but here's a couple of them:

https://github.com/cilium/cilium/pull/8975
https://github.com/cilium/cilium/pull/8978

**Comment by ArthurChiao** [comment]
Thanks. Our configurations:

1. `--enable-endpoint-routes=false` (using default configuration)
1.  Source pod has **no** ingress policy

**Comment by joestringer** [comment]
@ArthurChiao were you able to reproduce the issue on v1.6.2?

> Source pod has **no** ingress policy

Note that source pod ingress policy in the above cases caused packets to be dropped due to `POLICY_DENIED (L3)`; if no ingress policy applies at the source, then the packet will be passed with incorrect NAT which I would expect to lead to something like a RST issue (because the stack then receives a packet for a connection that it does not recognize).

**Comment by ArthurChiao** [comment]
hi @joestringer , apologize for that, the verification of `1.6.2` will be delayed as we are on a 7-day national holiday. We could only check this when we back to work.

**Comment by ArthurChiao** [comment]
@joestringer According to our tests, the problem still exists after upgrading to `v1.6.2`.

**Comment by joestringer** [comment]
@ArthurChiao thanks for confirming.

Are you able to post an example of the `cilium monitor` output you see for this connection?

It would be helpful to have this with:
* Standard `cilium monitor` output, also
* Configure the relevant endpoint (or agent) in debug mode then get `cilium monitor -v` output.

For the `-v` case we are looking for full debug monitor output that would include statements that look like this:

```
CPU 01: MARK 0xe9a15552 FROM 0 DEBUG: Attempting local delivery for container id 724 from seclabel 1
```

Also, to know exactly what datapath options are enabled, it would be good to have either:
* Cilium agent logs from the beginning of startup, including all of the options output; or
* The `cilium bpf template get XXX` output. You can find the template for the related endpoint using `cilium bpf template list`.

**Comment by ArthurChiao** [comment]
OK, I'll have a try. @joestringer

**Comment by ArthurChiao** [comment]
# Environment

* Service A: endpoint `1217`, identity `38829`
* Service B: endpoint `229`, identity `27638`

where Service B has an External IP.

# Test Traffic

Telnet B's 15020 port from A:

```shell
$ telnet <External IP> 15020
```

# Cilium Monitor Captures

## Capture standard output

```shell
$ cilium monitor | grep "27638->38829 \| 38829->27638"
-> endpoint 229 flow 0xb90758ac identity 38829->27638 state new ifindex lxc9c41458319d9: IP_A:59428 -> IP_B:15020 tcp SYN
-> endpoint 1217 flow 0x46e5b424 identity 27638->38829 state new ifindex lxccedc1041f343: IP_B:15020 -> IP_A:59428 tcp SYN, ACK
-> endpoint 229 flow 0xaebf8b99 identity 38829->27638 state established ifindex lxc9c41458319d9: IP_A:59428 -> IP_B:15020 tcp RST
-> endpoint 229 flow 0xaebf8b99 identity 38829->27638 state established ifindex lxc9c41458319d9: IP_A:59428 -> IP_B:15020 tcp RST
```

## Capture verbose output

```shell
$  cilium monitor -v | grep "27638->38829 \| 38829->27638" -B 1 -A 4
------------------------------------------------------------------------------
CPU 06: MARK 0xad0f0ae1 FROM 229 to-endpoint: 74 bytes (74 captured), state new, interface lxc9c41458319d9, identity 38829->27638, to endpoint 229
Ethernet        {Contents=[..14..] Payload=[..62..] SrcMAC=MAC_A DstMAC=MAC_B EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=16 Length=60 Id=10654 Flags=DF FragOffset=0 TTL=61 Protocol=TCP Checksum=15289 SrcIP=IP_A DstIP=IP_B Options=[] Padding=[]}
TCP     {Contents=[..40..] Payload=[] SrcPort=32782 DstPort=15020 Seq=2109241705 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=29200 Checksum=55427 Urgent=0 Options=[..5..] Padding=[]}
------------------------------------------------------------------------------
--
------------------------------------------------------------------------------
CPU 06: MARK 0x914485ce FROM 229 to-endpoint: 54 bytes (54 captured), state established, interface lxc9c41458319d9, identity 38829->27638, to endpoint 229
Ethernet        {Contents=[..14..] Payload=[..46..] SrcMAC=MAC_A DstMAC=MAC_B EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..20..] Version=4 IHL=5 TOS=0 Length=40 Id=9922 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=15545 SrcIP=IP_A DstIP=IP_B Options=[] Padding=[]}
TCP     {Contents=[..20..] Payload=[] SrcPort=32782 DstPort=15020 Seq=2109241706 Ack=0 DataOffset=5 FIN=false SYN=false RST=true PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=0 Checksum=9646 Urgent=0 Options=[] Padding=[]}
------------------------------------------------------------------------------
--
------------------------------------------------------------------------------
CPU 07: MARK 0x914485ce FROM 229 to-endpoint: 54 bytes (54 captured), state established, interface lxc9c41458319d9, identity 38829->27638, to endpoint 229
Ethernet        {Contents=[..14..] Payload=[..46..] SrcMAC=MAC_A DstMAC=MAC_B EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..20..] Version=4 IHL=5 TOS=0 Length=40 Id=10214 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=15253 SrcIP=IP_A DstIP=IP_B Options=[] Padding=[]}
TCP     {Contents=[..20..] Payload=[] SrcPort=32782 DstPort=15020 Seq=2109241706 Ack=0 DataOffset=5 FIN=false SYN=false RST=true PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=0 Checksum=9646 Urgent=0 Options=[] Padding=[]}
------------------------------------------------------------------------------
--
------------------------------------------------------------------------------
CPU 05: MARK 0x914485ce FROM 229 to-endpoint: 54 bytes (54 captured), state established, interface lxc9c41458319d9, identity 38829->27638, to endpoint 229
Ethernet        {Contents=[..14..] Payload=[..46..] SrcMAC=MAC_A DstMAC=MAC_B EthernetType=IPv4 Length=0}
IPv4    {Contents=[..20..] Payload=[..20..] Version=4 IHL=5 TOS=0 Length=40 Id=11691 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=13776 SrcIP=IP_A DstIP=IP_B Options=[] Padding=[]}
TCP     {Contents=[..20..] Payload=[] SrcPort=32782 DstPort=15020 Seq=2109241706 Ack=0 DataOffset=5 FIN=false SYN=false RST=true PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=0 Checksum=9646 Urgent=0 Options=[] Padding=[]}
------------------------------------------------------------------------------
```

# BPF Template

```shell
$ cilium bpf template get xxx
#include "lib/utils.h"

DEFINE_IPV6(LXC_IP, 0x20, 0x1, 0xdb, 0x8, 0xb, 0xad, 0xca, 0xfe, 0x60, 0xd, 0xbe, 0xe2, 0xb, 0xad, 0xca, 0xfe);
DEFINE_U32(LXC_IPV4, 0x030200c0);       /* 50462912 */
#define LXC_IPV4 fetch_u32(LXC_IPV4)
DEFINE_MAC(NODE_MAC, 0x2, 0x0, 0x60, 0xd, 0xf0, 0xd);
#define NODE_MAC fetch_mac(NODE_MAC)
DEFINE_U32(LXC_ID, 0x0000ffff); /* 65535 */
#define LXC_ID fetch_u32(LXC_ID)
DEFINE_U32(SECLABEL, 0x00000002);       /* 2 */
#define SECLABEL fetch_u32(SECLABEL)
DEFINE_U32(SECLABEL_NB, 0x02000000);    /* 33554432 */
#define SECLABEL_NB fetch_u32(SECLABEL_NB)
#define POLICY_MAP cilium_policy_65535
#define CALLS_MAP cilium_calls_65535
#define CONFIG_MAP cilium_ep_config_65535
#define FORCE_LOCAL_POLICY_EVAL_AT_SOURCE 1
#define ENABLE_ROUTING 1
#define ENABLE_ARP_RESPONDER 1
#define ENABLE_HOST_REDIRECT 1
#define CT_MAP_TCP4 cilium_ct4_global
#define CT_MAP_ANY4 cilium_ct_any4_global
#define CT_MAP_TCP6 cilium_ct6_global
#define CT_MAP_ANY6 cilium_ct_any6_global
#define CT_MAP_SIZE_TCP 524288
#define CT_MAP_SIZE_ANY 262144
#define LB_L3 1
#define LB_L4 1
#define LOCAL_DELIVERY_METRICS 1
#define CONNTRACK 1
#define CONNTRACK_ACCOUNTING 1
#undef CONNTRACK_LOCAL
#undef DEBUG
#undef LB_DEBUG
#define DROP_NOTIFY 1
#define MONITOR_AGGREGATION 3
#undef ENABLE_NAT46
#define TRACE_NOTIFY 1
```

Real IPs and MACs have been replaced in the following output. If they are helpful, I and send you via DM. @joestringer

**Comment by joestringer** [comment]
@ArthurChiao unfortunately the above output is missing some information:

* The grep is only including the outbound requests, but the reverse direction is also very important for understanding this issue. If the outbound SYN is fine but the SYN-ACK coming back from the destination is not fine, then this will result in an outbound RST. We see this in the output you posted above. However, we don't see the reply from the server. It would be useful to see the replies as well.

* The verbose output needs to contain the full set of notifications for it to be useful. Specifically, the daemon or relevant endpoint(s) must be in **debug** mode to provide additional tracing of the datapath packet-handling behaviour. I'm looking for messages that include the keyword `DEBUG`. If you identify relevant traffic and there is too much output, then I think that you can identify the `MARK 0x914485ce` and follow the handling of that packet with the same MARK value (this is the same as `flow` in the non-verbose mode), maybe just those messages will be enough. Here's an example:

```
CPU 01: MARK 0x5d51fb86 FROM 0 DEBUG: Inheriting identity=1 from stack                                                                                                                                               CPU 01: MARK 0x5d51fb86 FROM 0 DEBUG: Successfully mapped daddr=10.244.215.6 to identity=1                                                                                                                          
CPU 01: MARK 0x5d51fb86 FROM 0 DEBUG: Attempting local delivery for container id 961 from seclabel 1
CPU 01: MARK 0x5d51fb86 FROM 961 DEBUG: Conntrack lookup 1/2: src=10.244.215.6:60652 dst=10.244.6.2:8181
CPU 01: MARK 0x5d51fb86 FROM 961 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0                         
CPU 01: MARK 0x5d51fb86 FROM 961 DEBUG: CT entry found lifetime=197594, revnat=0
CPU 01: MARK 0x5d51fb86 FROM 961 DEBUG: CT verdict: Established, revnat=0
------------------------------------------------------------------------------                           
CPU 01: MARK 0x5d51fb86 FROM 961 to-endpoint: 66 bytes (66 captured), state established, interface lxc7a8c88a84381, identity 1->104, to endpoint 961
Ethernet        {Contents=[..14..] Payload=[..54..] SrcMAC=5e:8e:28:33:17:92 DstMAC=0a:6e:1c:7b:1b:e6 EthernetType=IPv4 Length=0}                                                                                   
IPv4    {Contents=[..20..] Payload=[..32..] Version=4 IHL=5 TOS=0 Length=52 Id=54909 Flags=DF FragOffset=0 TTL=63 Protocol=TCP Checksum=29270 SrcIP=10.244.215.6 DstIP=10.244.6.2 Options=[] Padding=[]}            
TCP     {Contents=[..32..] Payload=[] SrcPort=60652 DstPort=8181(intermapper) Seq=2214311246 Ack=1905325307 DataOffset=8 FIN=false SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Wind
ow=502 Checksum=62230 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:3782575177/321756271 0xe1758449132d9c6f)] Padding=[]} 
```

I also realized that I didn't specify whether to run `cilium monitor` at the source or the destination. To fully understand how the packet is handled, it would be useful to get this output on **both nodes**.

**Comment by ArthurChiao** [comment]
This is a little complicated than I expected, and looks like involving some changes to our running cluster. Let's discuss on slack later.  @joestringer

**Comment by joestringer** [comment]
@ArthurChiao sorry, I confirmed with @aanm that we don't support ExternalIP services in v1.6. There was an initial version in 1.6.0 but there were issues with it so we disabled it in v1.6.1. It's targeted for v1.7: #5293

**Comment by ArthurChiao** [comment]
@joestringer Thanks for this info, then we'll workaround this problem by limiting ExternalIP services to `kube-proxy` enabled nodes.

**Comment by brb** [comment]
@ArthurChiao When you reported the issue on Slack, did you mean ExternalIP with or without kube-proxy? I'm wondering whether the issue title `kube-proxy ExternalIP service fails to apply rev NAT xlation` is wrong.

**Comment by ArthurChiao** [comment]
@brb I mean **a Service with an ExternalIP** on normal Cilium nodes - no `kube-proxy` running on these nodes. Remove `kube-proxy` from the title seems fine.

**Comment by brb** [comment]
@ArthurChiao Thanks for the clarification. Then this issue is a duplicate of https://github.com/cilium/cilium/issues/5293.
