### ISSUE TITLE
Add ExceptName rule to support disallowing instead of allowing

### ISSUE THREAD

**Issue by onlyamessenger** [cilium/cilium#9287]
## Proposal

**Is your feature request related to a problem?** 

No

**Describe the solution you'd like** 

Domains can be allowed using the `toFQDNs` rule. A deny solution does not exist, however. Use case: Allow all ingress/egress **except** one or more domains. 

See the following comment from @aanm on Slack:

> However, since we support `ExceptCIDRs` I believe it's easy to add an `ExceptName` field in the policy

EDIT: (Thomas)
I've changed the language a bit to be more neutral

I think denies should simply be done on the DNS Rule level to not even allow the DNS requests to go through.

**Comment by errordeveloper** [comment]
@mrostecki are you still keeping this on your radar?

**Comment by mrostecki** [comment]
Sorry, I didn't start any work on this, I'm unassigning myslelf.

**Comment by youssefazrak** [comment]
@pchaigno I will take care of this one.

**Comment by youssefazrak** [comment]
I'm busy with another issue and I will re-assign myself later if no one takes it.

**Comment by youssefazrak** [comment]
@pchaigno I will work on this one

**Comment by errordeveloper** [comment]
@youssefazrak did you get a chance to investigate how this can be fixed?

**Comment by youssefazrak** [comment]
@errordeveloper Basically my initial investigation is to do it as the ExceptCIDRs implementation. I still haven't moved to the implementation phase yet.
