### ISSUE TITLE
parallel builds cause jenkins to fail

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#931]
```
[K==> cilium-master: Matching MAC address for NAT networking...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "9ffd4e6b-accb-44a1-b840-f8af5ce16b17", "--macaddress1", "080027D7135C"]

Stderr: VBoxManage: error: The machine 'ubuntu-1604-virtualbox_1496871305998_79275' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 507 of file VBoxManageModifyVM.cpp
```

More info:
https://jenkins.cilium.io/job/cilium/job/cilium/job/master/324/execution/node/20/log/
https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-926/4/execution/node/20/log/

**Comment by ianvernon** [comment]
Looks like the same MAC address is being assigned to both VMs at the same time:
```Command: ["modifyvm", "9ffd4e6b-accb-44a1-b840-f8af5ce16b17", "--macaddress1", "080027D7135C"]```

```Command: ["modifyvm", "2535a2a6-cfc0-441c-942b-1491401d5522", "--macaddress1", "080027D7135C"]```

This seems like it could cause some problems :) next step is to figure out why...

**Comment by ianvernon** [comment]
:( the second build link now 404's.
