### ISSUE TITLE
CI: Checks that monitor aggregation restricts notifications

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9330]
## CI failure
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
Monitor log contained unexpected number of egress notifications matching "SrcPort=40752"
Expected
    <int>: 2
to equal
    <int>: 3
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:160
```
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/15246/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/

[ad64b1fb_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip](https://github.com/cilium/cilium/files/3686429/ad64b1fb_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip)

cc @joestringer

**Comment by joestringer** [comment]
Looks like a test issue, the monitor log actually contains 3 + 2 notifications:

```
TCP	{Contents=[..40..] Payload=[] SrcPort=45630 DstPort=80(http) Seq=573733988 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=64860 Checksum=5676 Urgent=0 Options=[..5..] Padding=[]}
TCP	{Contents=[..40..] Payload=[] SrcPort=80(http) DstPort=45630 Seq=1473817346 Ack=573733989 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=64308 Checksum=42328 Urgent=0 Options=[..5..] Padding=[]}
TCP	{Contents=[..32..] Payload=[] SrcPort=45630 DstPort=80(http) Seq=573734064 Ack=1473817617 DataOffset=8 FIN=true SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=505 Checksum=5668 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:3326112822/3987412344 0xc6407436edab1578)] Padding=[]}
TCP	{Contents=[..32..] Payload=[] SrcPort=80(http) DstPort=45630 Seq=1473817617 Ack=573734065 DataOffset=8 FIN=true SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=502 Checksum=52176 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:3987412345/3326112822 0xedab1579c6407436)] Padding=[]}
TCP	{Contents=[..32..] Payload=[] SrcPort=45630 DstPort=80(http) Seq=573734065 Ack=1473817618 DataOffset=8 FIN=false SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=505 Checksum=5668 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:3326112822/3987412345 0xc6407436edab1579)] Padding=[]}
```

**Comment by joestringer** [comment]
Woops, wrong port. Hmm.

```
STEP: Installing Cilium
STEP: Installing DNS Deployment
STEP: Performing Cilium preflight check
STEP: Performing Cilium status preflight check
STEP: Performing Cilium controllers preflight check
STEP: Performing Cilium health check
STEP: Performing Cilium service preflight check
STEP: Performing K8s service preflight check
STEP: Waiting for cilium-operator to be ready
STEP: Waiting for kube-dns to be ready
STEP: Running kube-dns preflight check
STEP: Performing K8s service preflight check
STEP: Making sure all endpoints are in ready state
STEP: Launching cilium monitor on "cilium-8g7zb"
STEP: Checking pod connectivity between nodes
STEP: Reading the monitor log at test_results/111-/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/monitor-aggregation.log
STEP: Checking that exactly one ICMP notification in each direction was observed
STEP: Checking the set of TCP notifications received matches expectations
STEP: Looking for TCP notifications using the ephemeral port "40752"
```

**Comment by joestringer** [comment]
OK, for whatever reason on this particular occasion it seems that the server decided to close the connection:

```
TCP	{Contents=[..40..] Payload=[] SrcPort=40752 DstPort=80(http) Seq=3862836144 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=64860 Checksum=5444 Urgent=0 Options=[..5..] Padding=[]}
TCP	{Contents=[..40..] Payload=[] SrcPort=80(http) DstPort=40752 Seq=1871780886 Ack=3862836145 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=65160 Checksum=5444 Urgent=0 Options=[..5..] Padding=[]}
TCP	{Contents=[..32..] Payload=[] SrcPort=80(http) DstPort=40752 Seq=1871781176 Ack=3862836256 DataOffset=8 FIN=true SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=509 Checksum=5436 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:2795897990/316342473 0xa6a6048612db00c9)] Padding=[]}
TCP	{Contents=[..32..] Payload=[] SrcPort=40752 DstPort=80(http) Seq=3862836256 Ack=1871781177 DataOffset=8 FIN=true SYN=false RST=false PSH=false ACK=true URG=false ECE=false CWR=false NS=false Window=505 Checksum=5436 Urgent=0 Options=[TCPOption(NOP:), TCPOption(NOP:), TCPOption(Timestamps:316342474/2795897990 0x12db00caa6a60486)] Padding=[]}
```

...which means that the 3-way close inverts the notifications as 2 egress and 3 ingress. Hmm.

We can either:
* Figure out why the server closed the connection this time (timing around service deletion?)
* Make the logic agnostic as to which direction the 3 vs 2 notifications occur.
  * Maybe we could look for 2x `SYN=true`, 2x `FIN=true.*`, 1x `FIN=false SYN=false.*ACK=true`.

**Comment by joestringer** [comment]
Code link:

https://github.com/cilium/cilium/blob/bede1fea7e51bce25777f075a4374b2de6312199/test/k8sT/DatapathConfiguration.go#L129-L164

**Comment by nebril** [comment]
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10109/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10107/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/

**Comment by joestringer** [comment]
@nebril I strongly suspect that the addition of a third VM into CI makes this kind of problem more likely, due to less reliable scheduling on the underlying host.

When the issue is `Monitor log contained unexpected number of egress notifications matching "ICMPv4.*DstIP=10.10.1.167"`, this typically means that the traffic was transmitted before the monitor managed to start up successfully. The monitor startup is asynchronous here, so there's no strong guarantee that it begins before the test traffic runs:

https://github.com/cilium/cilium/blob/f543ea2367c7dfc64b3cdc2b871a2a58d5328e58/test/k8sT/DatapathConfiguration.go#L561-L562

I investigated the https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10109/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/ artifacts and confirmed that there were no ICMP packets found in the monitor output, only TCP (port 80 / 8080). This behaviour is consistent with my assertion above, as the TCP streams run after the ICMP in `testPodConnectivityAndReturnIP()`.

Overall there are two issues:
1. Ensuring that the monitor is listening before packets are sent, and
1. Ensuring that the monitor has received the final packets that were sent before it is closed.

I don't believe that there are hard checks for either condition in the testing code today.
