### ISSUE TITLE
Pod can not reach itself through clusterIP service in EKS chaining mode

### ISSUE THREAD

**Issue by genbit** [cilium/cilium#9347]
Connection from POD to itself through ClusteIP is not routable in Cilium EKS CNI chaining mode.
It works when trying EKS without Cilium

## Bug report

**General Information**

- Cilium version 1.6.2 and 1.6.1
- Kernel version Linux frontend-7976fcf949-q5br8 4.14.133-113.112.amzn2.x86_64 #1 SMP Tue Jul 30 18:29:50 UTC 2019 x86_64 GNU/Linux

- Orchestration system version in use 
AWS EKS cluster, built using eksctl
https://cilium.readthedocs.io/en/stable/gettingstarted/k8s-install-eks/
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

1. create EKS cluster with cilium following getting started guide
2. install 
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/1.6.2/examples/kubernetes/connectivity-check/connectivity-check.yaml
3. reduce number of echo pods to 1
4. perform connection from pod to itself through echo service

Result: 
Connection is stack. 

cilium monitor:
```
-> stack flow 0xc8fc37a identity 54168->2 state new ifindex 0: 169.254.42.1:55742 -> 192.168.54.56:8080 tcp SYN
```

**Comment by brandon-mcrae-hs** [comment]
Experiencing the same issue with a service of type: `NodePort`.

---
* Cilium v1.6.2
* Linux version 4.15.0-1051-aws (buildd@lgw01-amd64-005) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))
* amazon-k8s-cni v1.5.3
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brb** [comment]
In the CNI chaining mode, we disable `ENABLE_ROUTING` (https://github.com/cilium/cilium/blob/v1.6.3/bpf/bpf_lxc.c#L558-L576), so the hairpin request is being passed to stack instead of being redirected to itself (https://github.com/cilium/cilium/blob/v1.6.3/bpf/bpf_lxc.c#L602). AFAIK, the kernel should drop such request as it's going to be routed back to the device it came from. Therefore, we don't see any SYN,ACK.
