### ISSUE TITLE
Managed etcd on Azure

### ISSUE THREAD

**Issue by juanmanuel-tirado** [cilium/cilium#9352]
## Support

I have provisioned an Azure cluster running Kubernetes 1.13.10. Following the how to install on [Azure](https://docs.cilium.io/en/v1.6/gettingstarted/k8s-install-aks/) guidelines, I can install Cilium latest version with no problems. However, I was unsuccessful installing a managed etcd version.

The guidelines to install on top of Azure does not mention how to install the etcd managed version on top of azure. I tried, combining both approaches into the following helm command:

> helm template cilium   \
--namespace cilium   \
--set nodeinit.azure=true   \
--set global.cni.chainingMode=generic-veth   \
--set global.cni.customConf=true   \
--set global.nodeinit.enabled=true   \
--set global.cni.configMap=cni-configuration   \
--set global.tunnel=disabled \
--set global.etcd.enabled=true \
--set global.etcd.managed=true  > cilium_etcd.yaml

I created the cilium namespace and install the cni-configuration config map as mentioned in the guidelines. After a while pods status looks like this:

> cilium-6csxn                           1/1     Running    3          22m
cilium-7ks2n                           0/1     Running    3          22m
cilium-bf8tr                           1/1     Running    3          22m
cilium-etcd-dmcnzn6k4s                 0/1     Error      0          11m
cilium-etcd-dx9w549k2n                 0/1     Error      0          16m
cilium-etcd-operator-8dd9b487c-xbhf5   1/1     Running    0          22m
cilium-etcd-rvmtzr2k84                 0/1     Init:0/1   0          63s
cilium-etcd-tm5tn8t6mm                 0/1     Init:0/1   0          6m15s
cilium-kg5tb                           0/1     Running    3          22m
cilium-node-init-86kls                 1/1     Running    0          22m
cilium-node-init-9s4dr                 1/1     Running    0          22m
cilium-node-init-dktcb                 1/1     Running    0          22m
cilium-node-init-fxg7s                 1/1     Running    0          22m
cilium-operator-84f56477d7-t6nr4       1/1     Running    9          22m
etcd-operator-69479664f7-g8nbt         1/1     Running    0          87s

The core-dns pods are up and running in the kube-system namespace and no error logs are displayed. 

The cilium-etcd-client service is not available and the whole thing stops working. I am not sure about the helm command to be used. I have also tried to run the helm-generated yamls for the example shown in the general managed etcd guidelines, but I am having similar problems. I would appreciate any assistance. 

I append logs for cilium-etcd and the cilium-operator.

cilium-etcd logs:
> 2019-10-07 12:42:09.901877 I | pkg/flags: recognized and used environment variable ETCD_AUTO_COMPACTION_MODE=revision
2019-10-07 12:42:09.901942 I | pkg/flags: recognized and used environment variable ETCD_AUTO_COMPACTION_RETENTION=25000
2019-10-07 12:42:09.902027 I | etcdmain: etcd Version: 3.3.12
2019-10-07 12:42:09.902032 I | etcdmain: Git SHA: d57e8b8
2019-10-07 12:42:09.902035 I | etcdmain: Go Version: go1.10.8
2019-10-07 12:42:09.902038 I | etcdmain: Go OS/Arch: linux/amd64
2019-10-07 12:42:09.902042 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2019-10-07 12:42:09.902097 I | embed: peerTLS: cert = /etc/etcdtls/member/peer-tls/peer.crt, key = /etc/etcdtls/member/peer-tls/peer.key, ca = , trusted-ca = /etc/etcdtls/member/peer-tls/peer-ca.crt, client-cert-auth = true, crl-file =
2019-10-07 12:42:09.902907 I | embed: listening for peers on https://0.0.0.0:2380
2019-10-07 12:42:09.902944 I | embed: listening for client requests on 0.0.0.0:2379
2019-10-07 12:42:29.942509 I | pkg/netutil: resolving cilium-etcd-dmcnzn6k4s.cilium-etcd.cilium.svc:2380 to 10.3.0.19:2380
2019-10-07 12:42:39.940090 W | pkg/netutil: failed resolving host cilium-etcd-dmcnzn6k4s.cilium-etcd.cilium.svc:2380 (i/o timeout); retrying in 1s
2019-10-07 12:42:39.940121 E | pkg/netutil: could not resolve host cilium-etcd-dmcnzn6k4s.cilium-etcd.cilium.svc:2380
2019-10-07 12:42:39.944621 C | etcdmain: failed to resolve https://cilium-etcd-dmcnzn6k4s.cilium-etcd.cilium.svc:2380 to match --initial-cluster=cilium-etcd-dmcnzn6k4s=https://cilium-etcd-dmcnzn6k4s.cilium-etcd.cilium.svc:2380 (failed to resolve "https://cilium-etcd-dmcnzn6k4s.cilium-etcd.cilium.svc:2380" (i/o timeout))

cilium-operator logs:
> level=info msg="Cilium Operator 1.6.90 bede1fea7 2019-10-01T12:51:59-07:00 go version go1.13.1 linux/amd64" subsys=cilium-operator
level=info msg="Starting apiserver on address :9234" subsys=cilium-operator
level=info msg="Establishing connection to apiserver" host="https://10.21.0.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Retrieved node information from kubernetes" nodeName=aks-nodepool1-40474357-0 subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=10.3.0.35 ipAddr.ipv6="<nil>" nodeName=aks-nodepool1-40474357-0 subsys=k8s v4Prefix=10.35.0.0/16 v6Prefix="<nil>"
level=info msg="Starting to synchronize k8s services to kvstore..." subsys=cilium-operator
level=info msg="cilium-operator running with service synchronization: automatic etcd service translation enabled" address= kvstore=etcd subsys=cilium-operator
level=info msg="Waiting for all services to be synced with kubernetes before connecting to etcd" address= kvstore=etcd subsys=cilium-operator
level=info msg="Kubernetes services synced" address= kvstore=etcd subsys=cilium-operator
level=info msg="Connecting to kvstore..." address= kvstore=etcd subsys=cilium-operator
level=info msg="Connecting to etcd server..." config=/var/lib/etcd-config/etcd.config endpoints="[https://cilium-etcd-client.cilium.svc:2379]" subsys=kvstore
level=info msg="Starting to synchronize k8s nodes to kvstore..." subsys=cilium-operator
{"level":"warn","ts":"2019-10-07T12:49:15.682Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2019-10-07T12:49:30.682Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2019-10-07T12:49:45.683Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2019-10-07T12:50:00.684Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Health check status" error="not able to connect to any etcd endpoints" subsys=cilium-operator
{"level":"warn","ts":"2019-10-07T12:50:15.684Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Health check status" error="not able to connect to any etcd endpoints" subsys=cilium-operator
{"level":"warn","ts":"2019-10-07T12:50:30.685Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Health check status" error="not able to connect to any etcd endpoints" subsys=cilium-operator
level=fatal msg="Unable to start status api: http: Server closed" subsys=cilium-operator

**Comment by juanmanuel-tirado** [comment]
Any ideas about this issue I can explore?

**Comment by aanm** [comment]
@juanmanuel-tirado Can you explain what are you trying to achieve by running etcd with aks?

**Comment by juanmanuel-tirado** [comment]
I want to set up a cluster mesh using cilium. As mentioned in the guidelines an etcd managed version is required for that.

**Comment by aanm** [comment]
@juanmanuel-tirado, Thomas is on PTO at the moment, I'll ping him WRT once he's back

**Comment by juanmanuel-tirado** [comment]
I have continued exploring this issue. I comment some of my findings to help solving this issue.

I have enforced the mount of the bpfs in the host machine and checked that it is already working. 

```
kubectl --kubeconfig=/tmp/test_k8s.yaml -ncilium get pods -w
NAME                                    READY   STATUS    RESTARTS   AGE
cilium-clnw4                            0/1     Running   1          8m54s
cilium-etcd-operator-6cbf6d8687-5xxfz   1/1     Running   0          9m46s
cilium-operator-5df64f7456-d7cnz        1/1     Running   6          9m46s
etcd-operator-86ccfd897-j7n2q           1/1     Running   0          4m35s
```

The cilium operator crashes because it cannot access the cilium-etcd-client service.
```
kubectl --kubeconfig=/tmp/test_k8s.yaml -ncilium logs cilium-operator-5df64f7456-d7cnz
level=info msg="Cilium Operator " subsys=cilium-operator
level=info msg="Starting apiserver on address :9234" subsys=cilium-operator
level=info msg="Establishing connection to apiserver" host="https://10.0.0.1:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Retrieved node information from kubernetes" nodeName=aks-nodepool1-42185254-0 subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=10.240.0.4 ipAddr.ipv6="<nil>" nodeName=aks-nodepool1-42185254-0 subsys=k8s v4Prefix=10.4.0.0/16 v6Prefix="<nil>"
level=info msg="Starting to synchronize k8s services to kvstore..." subsys=cilium-operator
level=info msg="cilium-operator running with service synchronization: automatic etcd service translation enabled" address= kvstore=etcd subsys=cilium-operator
level=info msg="Waiting for all services to be synced with kubernetes before connecting to etcd" address= kvstore=etcd subsys=cilium-operator
level=info msg="Kubernetes services synced" address= kvstore=etcd subsys=cilium-operator
level=info msg="Connecting to kvstore..." address= kvstore=etcd subsys=cilium-operator
level=info msg="Connecting to etcd server..." config=/var/lib/etcd-config/etcd.config endpoints="[https://cilium-etcd-client.cilium.svc:2379]" subsys=kvstore
level=info msg="Starting to synchronize k8s nodes to kvstore..." subsys=cilium-operator
{"level":"warn","ts":"2019-10-16T09:17:14.704Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2019-10-16T09:17:29.704Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2019-10-16T09:17:44.705Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2019-10-16T09:17:59.706Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Health check status" error="not able to connect to any etcd endpoints" subsys=cilium-operator
{"level":"warn","ts":"2019-10-16T09:18:14.706Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Health check status" error="not able to connect to any etcd endpoints" subsys=cilium-operator
{"level":"warn","ts":"2019-10-16T09:18:29.707Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://cilium-etcd-client.cilium.svc:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Health check status" error="not able to connect to any etcd endpoints" subsys=cilium-operator
level=fatal msg="Unable to start status api: http: Server closed" subsys=cilium-operator
```

Something is going wrong with the coredns
```
kubectl --kubeconfig=/tmp/test_k8s.yaml -nkube-system get pods
azure-cni-networkmonitor-r7fzb          1/1     Running            0          36m
azure-ip-masq-agent-8shlq               1/1     Running            0          36m
coredns-544ccd699-6tzv5                 1/1     Running            9          26m
coredns-544ccd699-g94hb                 0/1     CrashLoopBackOff   9          26m
coredns-autoscaler-77799d76ff-jl8ql     1/1     Running            0          39m
kube-proxy-72znh                        1/1     Running            0          36m
kubernetes-dashboard-5fdb98dc6c-h98sw   1/1     Running            1          39m
metrics-server-67bd858859-2xbv9         1/1     Running            0          39m
tunnelfront-5d9cf99676-dg5kt            1/1     Running            0          39m
```
I'm surprised the kube-api is not any longer accessible by the coredns.

```
kubectl --kubeconfig=/tmp/test_k8s.yaml -nkube-system logs coredns-544ccd699-6tzv5
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
.:53
2019-10-16T09:19:41.009Z [INFO] CoreDNS-1.3.1
2019-10-16T09:19:41.009Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2019-10-16T09:19:41.010Z [INFO] plugin/reload: Running configuration MD5 = d8c69602fc5a3428908dc8f34f9aae58
2019-10-16T09:19:48.010Z [ERROR] plugin/errors: 2 6952057939793669868.1902039442503034456. HINFO: read udp 10.240.0.25:45817->168.63.129.16:53: i/o timeout
2019-10-16T09:19:51.011Z [ERROR] plugin/errors: 2 6952057939793669868.1902039442503034456. HINFO: read udp 10.240.0.25:36727->168.63.129.16:53: i/o timeout
2019-10-16T09:19:52.011Z [ERROR] plugin/errors: 2 6952057939793669868.1902039442503034456. HINFO: read udp 10.240.0.25:44272->168.63.129.16:53: i/o timeout
2019-10-16T09:19:53.012Z [ERROR] plugin/errors: 2 6952057939793669868.1902039442503034456. HINFO: read udp 10.240.0.25:35038->168.63.129.16:53: i/o timeout
E1016 09:19:56.012811       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:317: Failed to list *v1.Endpoints: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:36789->168.63.129.16:53: i/o timeout
2019-10-16T09:19:56.015Z [ERROR] plugin/errors: 2 6952057939793669868.1902039442503034456. HINFO: read udp 10.240.0.25:58928->168.63.129.16:53: i/o timeout
E1016 09:19:56.015446       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:36789->168.63.129.16:53: i/o timeout
E1016 09:19:56.015552       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/services?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:36789->168.63.129.16:53: i/o timeout
2019-10-16T09:19:59.014Z [ERROR] plugin/errors: 2 6952057939793669868.1902039442503034456. HINFO: read udp 10.240.0.25:32917->168.63.129.16:53: i/o timeout
2019-10-16T09:20:02.015Z [ERROR] plugin/errors: 2 6952057939793669868.1902039442503034456. HINFO: read udp 10.240.0.25:35932->168.63.129.16:53: i/o timeout
2019-10-16T09:20:05.015Z [ERROR] plugin/errors: 2 6952057939793669868.1902039442503034456. HINFO: read udp 10.240.0.25:36717->168.63.129.16:53: i/o timeout
2019-10-16T09:20:08.016Z [ERROR] plugin/errors: 2 6952057939793669868.1902039442503034456. HINFO: read udp 10.240.0.25:40370->168.63.129.16:53: i/o timeout
E1016 09:20:17.016428       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:317: Failed to list *v1.Endpoints: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:39694->168.63.129.16:53: i/o timeout
E1016 09:20:17.016428       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/services?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:39694->168.63.129.16:53: i/o timeout
E1016 09:20:17.016626       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:39694->168.63.129.16:53: i/o timeout
E1016 09:20:38.021114       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/services?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:52867->168.63.129.16:53: i/o timeout
E1016 09:20:38.021284       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:317: Failed to list *v1.Endpoints: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:52867->168.63.129.16:53: i/o timeout
E1016 09:20:38.021289       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:52867->168.63.129.16:53: i/o timeout
E1016 09:20:59.023290       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:34992->168.63.129.16:53: i/o timeout
E1016 09:20:59.023451       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/services?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:34992->168.63.129.16:53: i/o timeout
E1016 09:20:59.023497       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:317: Failed to list *v1.Endpoints: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:34992->168.63.129.16:53: i/o timeout
E1016 09:21:20.025124       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:317: Failed to list *v1.Endpoints: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:42247->168.63.129.16:53: i/o timeout
E1016 09:21:20.025139       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:322: Failed to list *v1.Namespace: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:42247->168.63.129.16:53: i/o timeout
E1016 09:21:20.025168       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io:443/api/v1/services?limit=500&resourceVersion=0: dial tcp: lookup myaksclust-juanmadev2-31e8b4-c23864cf.hcp.francecentral.azmk8s.io on 168.63.129.16:53: read udp 10.240.0.25:42247->168.63.129.16:53: i/o timeout
[INFO] SIGTERM: Shutting down servers then terminating
```

**Comment by tgraf** [comment]
While reproducing this, ran into this:
```
2020-02-10 15:55:08.110553 I | embed: rejected connection from "10.240.0.90:41128" (error "tls: \"10.240.0.90\" does not match any of DNSNames [\"*.cilium-etcd.cilium.svc\" \"*.cilium-etcd.cilium.svc.cluster.local\"]", ServerName "cilium-etcd-g6g9cp7pmh.cilium-etcd.cilium.svc", IPAddresses [], DNSNames ["*.cilium-etcd.cilium.svc" "*.cilium-etcd.cilium.svc.cluster.local"])
2020-02-10 15:55:08.112568 W | etcdserver: could not get cluster response from https://cilium-etcd-wmsg82g5b5.cilium-etcd.cilium.svc:2380: Get https://cilium-etcd-wmsg82g5b5.cilium-etcd.cilium.svc:2380/members: EOF
2020-02-10 15:55:08.112859 I | embed: rejected connection from "10.240.0.90:41130" (error "tls: \"10.240.0.90\" does not match any of DNSNames [\"*.cilium-etcd.cilium.svc\" \"*.cilium-etcd.cilium.svc.cluster.local\"]", ServerName "cilium-etcd-g6g9cp7pmh.cilium-etcd.cilium.svc", IPAddresses [], DNSNames ["*.cilium-etcd.cilium.svc" "*.cilium-etcd.cilium.svc.cluster.local"])
```

This was temporary though and I assume it is because CoreDNS was not yet updated with the latest pods scheduled.

Eventually, it succeeded though:
```
cilium-etcd-fwt7k4clkg                  1/1     Running   0          74m    10.240.0.50   aks-nodepool1-12938446-vmss000001   <none>           <none>
cilium-etcd-j95sdckchg                  1/1     Running   0          74m    10.240.0.92   aks-nodepool1-12938446-vmss000002   <none>           <none>
cilium-etcd-ktlmhmcnt6                  1/1     Running   0          73m    10.240.0.12   aks-nodepool1-12938446-vmss000000   <none>           <none>
```

So I currently can't reproduce this with master. It's possible that https://github.com/cilium/cilium/pull/10057 fixed this

**Comment by tgraf** [comment]
@juanmanuel-tirado Can you still reproduce this with `latest` or one of the 1.7rcs?

**Comment by tgraf** [comment]
I can't reproduce this anymore. Please re-open if you see this again.
