### ISSUE TITLE
CI: Figure out how to get reliable monitor output

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9357]
There's some rather elaborate usage of sleep being proposed in some tests to ensure that:
1. The monitor is in fact running before executing some test statements
1. That the monitor has in fact collected all of the notifications resulting from action in the test statements

Refer the PR comment here: https://github.com/cilium/cilium/pull/9210#discussion_r332225891

I think that this is because the initial goal of the monitor gathering was just to quietly gather log output in the background. Now that tests are being built against its output, we should implement blocking versions so that developers can write tests reliably against the monitor without resorting to these tricks.

**Comment by joestringer** [comment]
This is also likely a cause behind the CI flake #9330.

**Comment by joestringer** [comment]
Do we have CI helpers that allow waiting until the monitor output has some expected content? That'd be nice for the second point in the issue description.

**Comment by aanm** [comment]
What about the filters that we have `--related-to=<endpoint ID>` + `grep` and so on? wouldn't that help to get a reliable monitor output?

**Comment by joestringer** [comment]
By "reliable", I mean with respect to timing of (1) startup of the monitor vs (2) running test traffic vs (3) stopping the monitor.

**Comment by aanm** [comment]
discussed offline
