### ISSUE TITLE
Any plan to remove CLANG/LLVM from Cilium Agent docker image?

### ISSUE THREAD

**Issue by yongming** [cilium/cilium#9361]
## Proposal: Remove CLANG/LLVM from Cilium Agent image, only deliver eBPF bytecode

I installed cilium 1.4.8, found clang/llvm and other relevant  bpf compiler tool chain are packaged in cilium agent image. 
**Describe the solution you'd like**
Expects cilium can only deliver ebpf bytecode like go-ebpf to avoid having a runtime dependency.

**Comment by aanm** [comment]
@yongming This can be a possibility. Since cilium 1.5 that we have introduced bpf templates which does not require clang/llvm to compile bpf programs anymore. Currently clang/llvm are present because each different option setup in `cilium-agent` might require clang to compile a new bpf bytecode. Subsequent compilation are avoided wherever possible.

Is there any particular reason why you would want clang/llvm to be removed from cilium agent?

**Comment by yongming** [comment]
Docker image of Cilium agent size is about 622M (v1.4.8), LLVM/CLANG and other compiler relevant files occupy pretty much spaces. If only packaging necessary runtime libraries，the image size might be reduced greatly.

**Comment by leoluk** [comment]
> Currently clang/llvm are present because each different option setup in `cilium-agent` might require clang to compile a new bpf bytecode. Subsequent compilation are avoided wherever possible.

What options affect compilation?

We want to include Cilium in a minimum k8s distro and want to minimize our footprint and have full reproducibility for our images. Reproducing the Clang toolchain is quite an effort :-)

**Comment by pchaigno** [comment]
Our base datapath (i.e., all except BPF programs for endpoints) is currently compiled when the Cilium agent on the node starts. We have https://github.com/cilium/cilium/issues/9515 to track work on removing that requirement for Clang.

Then, as André said, we also need to compile the BPF programs whenever the Cilium agent configuration options are changed, for example if you want to disable monitor aggregation or enable audit mode on an existing cluster. One option to remove that requirement to have Clang on Cilium pods would be to let cilium-operator handle that compilation. There's a lot more work needed to implement that though.
