### ISSUE TITLE
update kubespray to consume to cilium v1.6.5

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#9374]
Currently it points to v1.5.5.

**Comment by Rolinh** [comment]
@frelon is working on this and already submitted https://github.com/kubernetes-sigs/kubespray/pull/5438.

I could deploy cilium v1.6.5 on a kubernetes v1.16.3 cluster using his patch and it seems to work fine. I've checked with @frelon, he'll bump the version in his patch to 1.6.4 as well.

As of note, the kubespray documentation for cilium is lacking.

**Comment by errordeveloper** [comment]
kubernetes-sigs/kubespray#5438 was merged 🎉
