### ISSUE TITLE
cilium-cni should conditionally enable IPv6 inside containers

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9393]
These unconditional lines in the cilium-cni should probably enable or disable IPv6 based upon `ipv6IsEnabled()` instead of unconditionally enabling it:

https://github.com/cilium/cilium/blob/8f5d408b44bc888df2af5b6e8bfcd77215938ed6/plugins/cilium-cni/cilium-cni.go#L490-L492

Furthermore, this could likely be refactored into `configureIface()`.

**Comment by aanm** [comment]
Sure this sounds a reasonable thing to do, we already have a helper function to check if IPv6 is enabled or not.

**Comment by joestringer** [comment]
@mrostecki oh, that code is actually new and it actually fixes a related bug where ipv6 was not being disabled properly for health containers.

I don't follow your logic, this disables IPv6 if the options in Cilium disable IPv6.

**Comment by mrostecki** [comment]
OK, sorry, I'm dumb. I somehow assumed that this code is setting `disable_ipv6` sysctl as 0, not 1. Please disregard.

**Comment by joestringer** [comment]
No worries, we considered even using `sysctl.Enable(...disable_ipv6)`, which would have taken the confusion one step further!
