### ISSUE TITLE
When the SOCK_OPS_MAP entry will be removed once enables sockops?

### ISSUE THREAD

**Issue by yongming** [cilium/cilium#9397]
## Support
In bpf/sockopf/bpf_sockops.c, there is code as below: 
...
if (redirect_to_proxy(verdict)) {
		__be32 host_ip = IPV4_GATEWAY;
		key.dip4 = key.sip4;
		key.dport = key.sport;
		key.sip4 = host_ip;
		key.sport = verdict;

		**sock_hash_update(skops, &SOCK_OPS_MAP, &key, BPF_NOEXIST);**
It will add a new entry into sockhash, when the entry will be deleted, I didn't find any code on it.

**Comment by jrfastab** [comment]
The entry is deleted by the kernel when the socket is closed.
