### ISSUE TITLE
Document the format of the etcd configuration file

### ISSUE THREAD

**Issue by rlguarino** [cilium/cilium#940]
The etcd configuration file is based on the struct located here: https://github.com/coreos/etcd/blob/release-3.1/clientv3/config.go#L48

The documentation should at least link to that, or iterate all of the possible fields. It would also help if the docs showed people how to set the file using a K8s ConfigMap.

**Comment by tgraf** [comment]
Documented here:
http://docs.cilium.io/en/v0.10/admin/#etcd
