### ISSUE TITLE
Improve external etcd documentation wording

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9401]
The external etcd documentation is below:

http://docs.cilium.io/en/latest/gettingstarted/k8s-install-external-etcd/

* The requirements do not list having an external etcd available.
* The section `Configure the External Etcd` is actually for configuring Cilium, not etcd.

We should tidy this up to make it easier to understand for users.

**Comment by mpeiffer** [comment]
Hello! Could I work on making the documentation for the external etcd a little more clear?

**Comment by brb** [comment]
@mpeiffer Sure, thanks! I'm assigning you to the issue.
