### ISSUE TITLE
Better handling of DNS -> IP mapping for mix of long and short-lived flows

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#9403]
We believe there can be problems related to how we cache DNS -> IP mappings and how policy enforcement happens in scenarios were there are many such mappings for a single endpoint in a short amount of time.    

Imagine that we have a scenario where:
1) Pod A creates a long-lived connection to www.foo.com, performing a DNS lookup, receiving IP-A and then having a long-lived TCP connection lasts 1+ minute. 
2) Within that minute Pod A does X more connections to other DNS names, each of which results in a DNS lookup + response.   

If X is more than the size of the per-endpoint DNS -> IP cache (--tofqdns-endpoint-max-ip-per-hostname),  it is believed that this will cause connection to IP-A to fail (unclear if this includes existing connections or just new connections to that IP without another DNS lookup, which is perfectly valid from the app perspective). 

There have been several possible options discussed here,  but some of the high-level thinking is that the core problem is that "eviction" of DNS -> IP cache entries is tied to when the DNS response was seen (i.e., evict least-recently created) rather than having an understanding of whether flows to those IPs are still in use or not (i.e., evict least recently used).   Doing LRU is potentially trickier than it sounds, as it would mean tying in with connection tracking or information at the socket level.

**Comment by joestringer** [comment]
I believe that this is the issue that @raybejjani mentioned that he was looking into during the Cilium community meeting today.
