### ISSUE TITLE
Use kubeadm in vagrant provisioning scripts for local development

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9421]
Currently, the vagrant provisioning script `contrib/vagrant/start.sh` does the manual installation of kubernetes which is spread among multiple files - https://github.com/cilium/cilium/tree/master/examples/kubernetes-ingress/scripts. Instead, we could use `kubeadm` to provision the kubernetes which would simplify the provisioning quite a lot.

**Comment by aanm** [comment]
It would yes but it would also make the deployment of self-build k8s more painful as well as the configuration of such components as their specific configuration is essential to test upcoming k8s versions.

**Comment by brb** [comment]
Can't you configure components with kubeadm?

**Comment by aanm** [comment]
> Can't you configure components with kubeadm?

I don't know.

**Comment by brb** [comment]
You can. See e.g. https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/.

**Comment by aanm** [comment]
> You can. See e.g. https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/.

I don't see kubelet in there nor etcd in there for example.

**Comment by brb** [comment]
It's not listed there, but you can configure kubelet, see https://github.com/brb/cilium-without-netfilter/blob/master/setup-master.sh#L14. Not sure about etcd though.

**Comment by pchaigno** [comment]
Half of the links have expired, it's not immediately clear how to configure components, and I doubt this is a simple change. Removing `good-first-issue` label.

**Comment by brb** [comment]
Majority of us have migrated from Vagrant to [LVH](https://docs.cilium.io/en/stable/contributing/testing/e2e/#running-tests-in-vm). Closing as no longer relevant.
