### ISSUE TITLE
Nodes lose connectivity after being teared down for > 15 min

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9422]
1) Stop node a)
2) Wait >15 min (15 min is the TTL for the lease in the kvstore)
3) Restart node a)
4) Verify the node can't connect to kube-dns, running on a different node, because coredns's node lost the route to reach node a).

Possible solutions:

1) Force key-value creation in etcd with `cilium-operator` for node a) based in k8s events. (I'm assuming we only do the creation of the key-value upon 'Create' events of that node but not upon 'Update' events)

Affected versions:
All

**Comment by christianhuening** [comment]
which version does this affect?

**Comment by aanm** [comment]
> which version does this affect?

@christianhuening all
