### ISSUE TITLE
Support non IPv6 in Kubernetes Service Endpoints

### ISSUE THREAD

**Issue by rlguarino** [cilium/cilium#944]
Would it be possible to support setting an IPv4 upstream in a Kubernetes Service via `external-ips` 
https://kubernetes.io/docs/concepts/services-networking/service/#external-ips on a cluster with disable-ipv4 set?

The idea is to have an IPv6 only Kubernetes cluster where connections to a 3rd party which only support IPv4 are done via Service =.

```[Pod] ---(IPv6)----> [Cilium Service Proxy] -----(IPv4) -----> [Thing on the internet]```

**Comment by tgraf** [comment]
@rlguarino Very interesting idea. You mention service, are you referring to a Kubernetes service in this regard? Would `[Cilium Service Proxy]` be implemented a Kubernetes Service which translates one IPv6 Service IP to a IPv4 service IP or would you expect for IPv4 addresses represented as IPv6 to be translated automatically, e.g. `::FFFF:12.155.166.101` => `12.155.166.101`.

**Comment by rlguarino** [comment]
@tgraf I totally messed up what I was trying to say here. What I was thinking was adding support for K8s services of type `ExternalName` but after reading more docs I don't really see how that will work.

The scenario I'm thinking of is a little convoluted. Image an IPv6 only cluster. If you wanted to connect to an IPv4 address you would need to connect to something over IPv6 which then speaks IPv4 to the upstream service.

The way I'm doing this now is to have an NGINX ingress controller which listens on a IPv6 addr but has access to an IPv4 network. Then a Service of type `ExternalName` is created to point at the DNS of the IPv4 only service. Finally an Ingress resource is created targeting that Service. K8s pods needing to connect to the IPv4 only service talk to the Ingress which proxies the traffic to the upstream.

I was hoping that the same thing would be possible using cilium as an ingress controller.
