### ISSUE TITLE
ENI: Node to pod connectivity issue

### ISSUE THREAD

**Issue by jaffcheng** [cilium/cilium#9446]
**General Information**

- Cilium version: 1.6.2
- Orchestration system: self-managed k8s 1.13.2 on AWS EC2 instance
- Kernel 4.16.2, Centos 7.4.1708 with service NetworkManager started
- Configurations:
```
ipam: eni
identity-allocation-mode: crd
blacklist-conflicting-routes: false
enable-endpoint-routes: true
auto-create-cilium-node-resource: true
```
- Cluster description:
```
Two k8s nodes with first ENI(eth0) on AWS subnet1 10.0.1.0/24
pods are on subnet2 192.168.1.0/24
pod ENIs (eth1) are attached to both nodes by cilium-operator

node1
eth0 10.0.1.2
eth1 192.168.1.2

node2
eth0 10.0.1.3
eth1 192.168.1.3
```

**How to reproduce the issue**

1. Create several pods on both nodes
2. Make sure the primary IP address of eth1 on node1 (192.168.1.2) is allocated to a pod
3. From node1 host namespace, ping IP address of a pod on node2 (e.g. 192.168.1.10) , failed

**Comment by jaffcheng** [comment]
Here is the cause based on my current investigation:
1. When eth1 is attached to node1 by operator, it is controlled by NetworkManager and gets its IP address 192.168.1.2 from dhcp and a direct route is generated
```
192.168.1.0/24 dev eth1 proto kernel scope link src 192.168.1.2 metric 100
```
2. A pod gets the primary IP address of eth1 (192.168.1.2) and cilium-cni configures a route:
```
192.168.1.2 dev lxcad33e3d6e955 scope link
```
3. When I ping the pod on node2 (192.168.1.10), the ICMP request hits the direct route and goes out from eth1 with source IP 192.168.1.2.
4. 192.168.1.10 sends ICMP reply back to 192.168.1.2 on node1. but when the reply is received on node1,it hits the route for pod 192.168.1.2 shown above and the reply is directed to the pod namespace, so the ping on host namespace fails.

**Comment by jaffcheng** [comment]
Removing IP from eth1 and stopping dhcp (stop and disable NetworkManager in my case) solved the problem for me.
Would be ideal to fix this in cilium or add a note to docs if the solution makes sense.

**Comment by jaffcheng** [comment]
@tgraf

**Comment by tgraf** [comment]
@jaffcheng I'm not sure we can do much from the Cilium side except adding a flag to not use the primary IP of the ENI for any pods. How have you worked around this right now?

**Comment by jaffcheng** [comment]
@tgraf  We are using the primary IPs for pods so we just make sure every EC2 instance have the service `NetworkManager` disabled and everything is perfect. I think adding a note in docs should be enough.
