### ISSUE TITLE
regression due to surpassing insns limit with nodeport on 4.19.57 aka pre 5.3

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#9451]
Happens with both v4 and v6 enabled. Only with v4 it is not exposed.

**Comment by joestringer** [comment]
`test/bpf/verifier-test.sh` is supposed to tell us this in CI ;) But I guess we only run these in the `runtime` tests VM (ie Linux `v4.9.x`).

**Comment by borkmann** [comment]
Yeap, exactly the problem. We need something >= 4.19.57 and < 5.3 to make sure no new regressions slip in for BPF nodeport on any changes to bpf_netdev/lxc/etc. The net-next has the 1mio insn limit, so it's not visible there. :-/ Maybe we need a 3rd kernel in our CI?

**Comment by joestringer** [comment]
Ah, sigh..
