### ISSUE TITLE
`endpoint-x-regeneration-recovery` controllers always use endpointid 0

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9454]
Looks like this is mostly cosmetic, but makes it a bit more difficult to understand which pods are affected and being restored correctly.

```
  endpoint-0-regeneration-recovery                                                                   7m39s ago       never        0       no error   
  endpoint-0-regeneration-recovery                                                                   never           never        0       no error   
  endpoint-0-regeneration-recovery                                                                   never           never        0       no error   
  endpoint-0-regeneration-recovery                                                                   never           never        0       no error   
  endpoint-0-regeneration-recovery                                                                   never           never        0       no error   
```

Tasks:
* [ ] Set up tests for conditions where regeneration recovery is necessary
* [ ] Figure out how to get meaningful endpointids here

**Comment by ianvernon** [comment]
Thanks for filing this! 

The core problem here is that there are different parts of the daemon which update parts of the endpoint outside of endpoint creation. IMO the endpoint should be able to get an ID from some ID allocator outside of the endpointmanager, where it currently resides.

Whenever an endpoint is attempted to be created, and fails, we should be able to call `Delete` on that Endpoint and have that function clean up all state for that Endpoint. If we do that, we can then make sure that Endpoint creation handles Endpoint ID allocation, and Endpoint deletion handles Endpoint ID deallocation

**Comment by aanm** [comment]
Fixed by https://github.com/cilium/cilium/pull/9551
