### ISSUE TITLE
document bpf macros

### ISSUE THREAD

**Issue by jrfastab** [cilium/cilium#949]
The BPF macro's used to convince _clang_ to generate correct code are not at all obvious. Please add comments to the source code so that others can read them.

**Comment by joestringer** [comment]
@jrfastab Do you have links to specific macros that need further documenting?

The main one that came to mind for me was `revalidate_data()`, which explains what it does but not the rationale:

https://github.com/cilium/cilium/blob/e7e3e72a7db645a0cbc6733429945aaf93d70e34/bpf/lib/common.h#L87-L90
