### ISSUE TITLE
Templatize BPF base programs

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9515]
PR https://github.com/cilium/cilium/pull/7095 (Issue #6618) converted Cilium's endpoint header file into a template which could be used to compile a single ELF object for all endpoints, then at runtime copy the ELF file to a new location, substituting the templated fields such as IP addresses, MAC addresses, etc.

This issue tracks making similar changes for the node header file and base programs, which would allow the base Cilium programs to also be compiled once and have fields substituted at runtime. For example:
* NAT prefix
* IP gateway, loopback address
* MTU
* MAC addresses
* Ifindexes

(See https://github.com/cilium/cilium/issues/9411#issuecomment-547169298 for how I got the above list)

When these are changed in the node config headerfile, the base program would need to use infrastructure similar to `pkg/datapath/loader/cache.go` to find an ELF and substitute configuration values for the above fields. (See also `pkg/elf/`)

Additionally, the regular endpoint ELF rewrite logic would also need to be aware of these fields and rewrite these as part of the ELF rewrite.

**Comment by joestringer** [comment]
The recent work that @pchaigno has been doing around converting the host to an endpoint makes significant strides in this direction. Related: #10994

**Comment by liggitt** [comment]
This remains relevant for making cilium work with minimal base images, shrinking image size and reducing security surface area

**Comment by brb** [comment]
Relevant issue https://github.com/cilium/cilium/issues/27320.

**Comment by joestringer** [comment]
We've had ELF templating for years for endpoint BPF programs via `bpf_lxc`, but not for the other ones. It's less relevant for the other programs since they are mostly "deploy once on startup", but I saw this as a next step on the journey towards removing the LLVM dependency. I think that https://github.com/cilium/cilium/issues/27320 does a better job of explaining the intended direction of this issue and will play the same role in the roadmap going forward, so I'm fine to close this issue out.

If any other community members watching this thread disagree or hope that this issue would resolve a different pain point for you, then please consider writing up a description of what you were looking for in this issue either here / #27446 or in a new issue on github so that we can capture the community desire for improvements in this area.
