### ISSUE TITLE
kubelet certificate missing when starting 2 worker nodes with Vagrant

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#9527]
Trying to start vagrant with 2 k8s worker nodes fails withing current master branch:

Tried both `K8S=1 NWORKERS=2 contrib/vagrant/start.sh` and `NFS=1 K8S=1 NWORKERS=2 contrib/vagrant/start.sh`, both fail with same message for worker 2 (k8s3):

k8s3: ----- 03-install-kubernetes-worker.sh: main: Copying cilium certificates to /var/lib/cilium
    k8s3: ----- 03-install-kubernetes-worker.sh: main: Copying nginx certificates to /var/lib/nginx
    k8s3: ----- 03-install-kubernetes-worker.sh: main: Copying kubelet certificates to /var/lib/kubelet
    k8s3: cp: 
    k8s3: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/contrib/vagrant/scripts/certs/k8s-kubelet-k8s3-key.pem'
    k8s3: : No such file or directory
    k8s3: cp: 
    k8s3: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/contrib/vagrant/scripts/certs/k8s-kubelet-k8s3.pem'
    k8s3: : No such file or directory
    k8s3: cp: 
    k8s3: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/contrib/vagrant/scripts/certs/kubelet-kubelet-k8s3.pem'
    k8s3: : No such file or directory
    k8s3: cp: 
    k8s3: cannot stat '/home/vagrant/go/src/github.com/cilium/cilium/contrib/vagrant/scripts/certs/kubelet-kubelet-k8s3-key.pem'
    k8s3: : No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

The first two nodes started successfully, am I doing something wrong?

Vagrant 2.2.3
Virtualbox 6.0.14

**Comment by aanm** [comment]
>The first two nodes started successfully, am I doing something wrong?

@Weil0ng no you are not, it's only because `00-create-certs.sh` has the static node names in the file as we usually only setup up to 1 k8s worker node. If you want it to run 2 worker nodes you will need to apply the following patch. Feel free to submit a PR that makes the `00-create-certs.sh` more modular.

```diff
diff --git a/contrib/vagrant/scripts/00-create-certs.sh b/contrib/vagrant/scripts/00-create-certs.sh
index 40bb82149..eddbd6814 100755
--- a/contrib/vagrant/scripts/00-create-certs.sh
+++ b/contrib/vagrant/scripts/00-create-certs.sh
@@ -12,6 +12,7 @@ cd "${certs_dir}"
 
 master="k8s1"
 worker="k8s2"
+worker2="k8s3"
 
 if [ -n "${INSTALL}" ]; then
     log "Downloading cfssl utility..."
@@ -329,8 +330,10 @@ generate_k8s_component_certs k8s controller-manager-sa k8s-controller-manager-sa
 # the correct permissions to manage its own node
 generate_kubelet_client_certs k8s system:node:${master} k8s-kubelet-${master}
 generate_kubelet_client_certs k8s system:node:${worker} k8s-kubelet-${worker}
+generate_kubelet_client_certs k8s system:node:${worker2} k8s-kubelet-${worker2}
 generate_k8s_component_certs k8s system:kube-proxy k8s-kube-proxy-${master}
 generate_k8s_component_certs k8s system:kube-proxy k8s-kube-proxy-${worker}
+generate_k8s_component_certs k8s system:kube-proxy k8s-kube-proxy-${worker2}
 
 # Generate kubelet client certificate so kube-apiserver can talk with kubelets
 generate_k8s_component_certs k8s kubelet-api-server kubelet-api-server
@@ -341,6 +344,7 @@ generate_ca_certs kubelet
 # Generate kubelet serving certificates to use to serve its endpoints
 generate_k8s_component_certs kubelet ${master} kubelet-kubelet-${master}
 generate_k8s_component_certs kubelet ${worker} kubelet-kubelet-${worker}
+generate_k8s_component_certs kubelet ${worker2} kubelet-kubelet-${worker2}
 
 # Generate each components certs
 generate_k8s_component_certs k8s system:kube-controller-manager k8s-controller-manager
```

**Comment by Weil0ng** [comment]
Hi @aanm, thank you for the response! I have a local patch that moves cert generation to each worker instead of master, which solves the issue, will submit a PR when I get a chance soon.
