### ISSUE TITLE
Cannot specify node address

### ISSUE THREAD

**Issue by rlguarino** [cilium/cilium#953]
Specifying the `--node-address` results in the cilium-daemon incorrectly invoking `ip route add`.

For example if I pass `--node-address= 2411:cb00:36:1012::0/96` cilium daemon will print: 

```
level=info msg="Cluster IPv6 prefix: 2411:cb00:36:1012::/64" 
level=info msg="Cluster IPv4 prefix: 10.0.0.0/8" 
level=info msg="IPv6 allocation prefix: 2400:cb00:36:1012:a29e:4176::/112" 
level=info msg="IPv4 allocation prefix: 10.254.0.0/16" 
```
and it will get an error from `ip route add` like: 

```
ip route add 2411:cb00:36:1012:a29e:4176::/96 via 2411:cb00:36:1012:a29e:4176::
RTNETLINK answers: Invalid argument
```

**Comment by tgraf** [comment]
@rlguarino Is `2411:cb00:36:1012::0/96` already configured as a prefix on the system?

**Comment by rlguarino** [comment]
The prefix 2411:cb00:36:1012::/64 is already configured  and I just noticed that `ip route` seems to like IPs that end with `::`  so my initial thought is wrong now. This is probably just user error.
