### ISSUE TITLE
ENI: stop operator from keeping attaching ENI to deleted instance

### ISSUE THREAD

**Issue by jaffcheng** [cilium/cilium#9533]
**General Information**

- Cilium version 1.6.3
- Kernel version 4.16.2
- Orchestration system version in use K8S v1.13.2

**How to reproduce the issue**

1. Deploy `ipam: eni` mode cilium cluster on AWS EC2 instances
2. Add an instance to cilium cluster, use default value 8 for `Spec.ENI.pre-allocate`
3. Ensure ciliumnode resource is properly created by operator
4. Delete EC2 instance. But node and ciliumnode are left over
5. Cilium-operator keeps trying to fulfill the node's deficit: creates ENI and fails from attaching ENI to non-existing instance repeatedly, making fair amount of useless EC2 API calls.
```
level=info msg="Synchronized ENI information" numENIs=xxx numSubnets=xx numVPCs=x subsys=eni
level=info msg="Resolving IP deficit of node" available=0 instanceID=xxx name=xxx remainingInterfaces=8 subsys=eni toAlloc=10 used=2
level=info msg="No more IPs available, creating new ENI" addresses=10 instanceID=xxx name=xxx securityGroups="[]" subnetID=xxx subsys=eni
level=info msg="Created new ENI" addresses=10 eniID=xxx instanceID=xxx name=xxx securityGroups="[]" subnetID=xxx subsys=eni
level=warning msg="Unable to maintain ip pool of node" error="unable to attach ENI at index 1: InvalidInstanceID.NotFound: The instance ID 'xxx' does not exist\n\tstatus code: 400, request id: 09412288-7c64-42d3-9de0-81542a740fd0" instanceID=xxx name=xxx subsys=eni
```

**Comment by ungureanuvladvictor** [comment]
@jaffcheng currently the ref owner of the CiliumOwner CR is set to be the k8s node and it relies on the fact that when the k8s node is deleted the CiliumNode will be as well.

How do you think the operator should behave in this scenario (EC2 VM being deleted from AWS but k8s node + CiliumNode still being in the APIServer)?

**Comment by jaffcheng** [comment]
@ungureanuvladvictor I think operator should stop trying to fulfill the IP deficit of deleted instances and log a warning. Currently operator doesn't check the existance of instance when calculating needed addresses. I have written a fix for this, but I found some sporadic unit test failure. see https://github.com/cilium/cilium/issues/9604 
I'll send the fix latter today, and maybe we need to make sure this patch has no impact on https://github.com/cilium/cilium/issues/9604
