### ISSUE TITLE
Multiple issues installing Cilium on latest GKE with CoS 77 (rapid channel) 

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#9556]
## Bug report

**General Information**

Cilium 1.6.3, sysdump attached.  

[cilium-sysdump-20191105-111420.zip](https://github.com/cilium/cilium/files/3810804/cilium-sysdump-20191105-111420.zip)

Main thing that seems to be new here is that Google CoS version is milestone 77, which includes a 4.19 kernel and potentially some other significant changes to the base image.  https://cloud.google.com/container-optimized-os/docs/release-notes

It is unclear how soon this new version of CoS will become part of the "regular" channel, and therefore something a user would see by default.   But for users wanting to work around potential limitations in 4.14 kernels, this seems to be their best option for GKE for now. 

**How to reproduce the issue**

1. Follow https://docs.cilium.io/en/v1.6/gettingstarted/k8s-install-gke/ , but use the following command to create the cluster: 

``
gcloud beta container clusters create cluster3  --username "admin" --image-type COS --num-nodes 2 --zone ${GKE_ZONE} --release-channel rapid
``

See this link for context:  https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels

It is possible some of these errors are cascading, hard to tell.  

Issue 1:    Node init containers are in Error state:  

It seems like perhaps our script to mount bpf filesystem needs to be updated?  

``
$ kubectl logs -n cilium cilium-node-init-b48np
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
Installing BPF filesystem mount
Installed sys-fs-bpf.mount to /etc/systemd/system/
Failed to start sys-fs-bpf.mount: Unit sys-fs-bpf.mount has a bad unit file setting.
See system logs and 'systemctl status sys-fs-bpf.mount' for details.
!!! startup-script failed! exit code '1'
``

Issue 2:  Cilium pods go into Crashloop backoff

Seems like the issue is that Cilium isn't able to reach the K8s api server.  Logs end with: 

``
level=info msg="Initializing daemon" subsys=daemon
level=warning msg="xt_socket kernel module could not be loaded" error="could not load module xt_socket: exit status 1" subsys=iptables
level=info msg="Detected MTU 1460" subsys=mtu
level=info msg="Restore service IDs from BPF maps" duration="663.979µs" failed=0 removed=0 restored=0 skipped=0 subsys=daemon
level=info msg="Removing stale endpoint interfaces" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://10.4.16.1:443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://10.4.16.1:443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://10.4.16.1:443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://10.4.16.1:443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://10.4.16.1:443" subsys=k8s
``

**Comment by danwent** [comment]
Note:  I'm going to reproduce this on another cluster later today, as some of the other "infra pods" also seem to be unhealthy, so its possible this is just an unhealthy cluster overall.   Still, issue 1 would still seem to be something we need to address.

**Comment by aanm** [comment]
@danwent I see this in the `-previous`

```
2019-11-05T19:08:19.19333073Z level=error msg="Unable to contact k8s api-server" error="Get https://10.4.16.1:443/api/v1/namespaces/kube-system: x509: certificate is valid for 104.196.230.78, 10.4.0.1, not 10.4.16.1" ipAddr="https://10.4.16.1:443" subsys=k8s
2019-11-05T19:08:19.193356983Z level=fatal msg="Unable to initialize Kubernetes subsystem" error="unable to create k8s client: unable to create k8s client: Get https://10.4.16.1:443/api/v1/namespaces/kube-system: x509: certificate is valid for 104.196.230.78, 10.4.0.1, not 10.4.16.1" subsys=daemon
```

**Comment by danwent** [comment]
@aanm , I tried creating a new cluster, and it is hanging/taking a very long time as well, which is what happened with the first cluster.    I suspect that the "rapid" channel for GKE may just be broken wtr the k8s-api-server.    

 I suspect the cilium-node-init issue is probably real, but the general failure of Cilium to start may be just the fact that it is starting on a cluster that is a bit borked.   The k8s api sever is reachable from my kubectl, but perhaps not via service clusterIP?

**Comment by aanm** [comment]
> @aanm , I tried creating a new cluster, and it is hanging/taking a very long time as well, which is what happened with the first cluster. I suspect that the "rapid" channel for GKE may just be a bit borked.
> 
> The general failure of Cilium to start may be just the fact that it is starting in an env where the cluster-ip for the k8s api server is not reachable? I can reach the api server via kubectl (needed to deploy cilium).

no, the reason is that the certificate in the GKE's kube-apiserver is signed for `104.196.230.78 and 10.4.0.1` but in the cilium pod the kube-apiserver IP set is, for some reason, `10.4.16.1`

**Comment by danwent** [comment]
New sysdump below.  

The issue with cilium-node-init seems to persist.  

Issues with k8s api server connectivity seem a bit mixed.  With a new cluster, Cilium is able to access the K8s api server, but it seems that other pods are not able to reach k8s api server via the service clusterIP (Get https://10.3.240.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.3.240.1:443: connect: no route to host).  As a result, a lot of these pods are in crashloopbackoff.   It seems like this only happens once Cilium is installed, but I can't be sure as it is not immediate. 

The cilium logs contain a few iptables related errors, not sure if they are related: 

```
level=warning msg="xt_socket kernel module could not be loaded" error="could not load module xt_socket: exit status 1" subsys=iptables
```

```
level=warning msg="Unable to flush Cilium iptables chain" error="exit status 1" obj="[-w 5 -t filter -F CILIUM_INPUT]" subsys=iptables
level=warning msg="Unable to delete Cilium iptables chain" error="exit status 1" obj="[-w 5 -t filter -X CILIUM_INPUT]" subsys=iptables
```


[cilium-sysdump-20191106-164657.zip](https://github.com/cilium/cilium/files/3817368/cilium-sysdump-20191106-164657.zip)

**Comment by danwent** [comment]
Note:  I'm seeing the same timeouts to k8s service clusterIP even on GKE clusters that are 4.14.145+ kernel, not 4.19.  

I've recently updated the GKE master + node versions in this cluster, so it may actually be about the shift from the 1.12.x or 1.13.x version I was running before to the 1.14 version I am now running.

**Comment by joestringer** [comment]
For issue 1 in the description: The `rapid` channel ships systemd version `239`, and systemd has automounted bpffs from version `238` onwards so we just need to either drop the mount configuration when this hits the regular channel, or detect the systemd version in node-init to skip the mount configuration.
