### ISSUE TITLE
DaemonSet Pods scheduled onto new Nodes sometimes are not managed 

### ISSUE THREAD

**Issue by tom-hadlaw-hs** [cilium/cilium#9571]
## Bug report

**General Information**

I am running Cilium in an EKS based Kubernetes cluster, using the AWS VPC CNI with CNI chaining. I have a DaemonSet resource which creates Pods that expose ports. While scaling in additional cluster nodes, we occasionally see newly scheduled DaemonSet pods without a corresponding CEP.

- Cilium version (run `cilium version`) v1.6.3
- Kernel version (run `uname -a`) 4.15.0
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) Kubernetes 1.14

**How to reproduce the issue**

1. On a cluster using AWS VPC CNI plugin with Cilium CNI chaining, create a DaemonSet that creates pods which expose ports.
2. Monitor for any unmanaged pods using
```
while True; do
    ALL_CEPS=$(kubectl get cep -n default -o json | jq -r '.items[].metadata | .namespace + "/" + .name')
    ALL_PODS=$(kubectl get pods -n default -o json | jq -r '.items[].metadata | .namespace + "/" + .name')

    for pod in $ALL_PODS; do
        if ! echo "$ALL_CEPS" | grep -q "$pod"; then
            echo $pod
        fi
    done
done
```
3. Continuously scale nodes into the cluster
4. After some number of new nodes (around 10 in my case), you should see DaemonSet Pods without CEPs begin to appear. These do not appear to resolve after waiting.

**Comment by joestringer** [comment]
For GKE we have nodeinit logic to handle this case:

https://github.com/cilium/cilium/blob/62195fc1676e8bb865fe934a97711aa3bc313ee2/install/kubernetes/cilium/charts/nodeinit/templates/daemonset.yaml#L102-L111

Looks like we need similar functionality for EKS.

**Comment by joestringer** [comment]
OS: Ubuntu

**Comment by joestringer** [comment]
Also relevant, from the slack thread:

> yeah, our cilium is on system-node-critical, whereas our other DaemonSets run on a lower priorityClass

**Comment by tom-hadlaw-hs** [comment]
Just to mirror what I posted on Slack, I’ve been looking into how we could do something similar to the restartPods option (https://github.com/cilium/cilium/blob/v1.6/install/kubernetes/cilium/charts/nodeinit/templates/daemonset.yaml#L102-L111) that would work with EKS+AWS-CNI. It appears that the plugin allows you to request all the cni managed pods running on that node from its introspection API. We could maybe just use those to restart all the relevant containers.

Example code:
```bash
for pod in $(curl "localhost:61679/v1/pods" 2> /dev/null | jq -r '. | keys[]'); do
    container_id=$(echo "$pod" | awk -F_ ' { print $3 } ' | cut -c1-12)
    docker rm -f ${container_id}"
done
```
