### ISSUE TITLE
Potential master regression in cilium-operator with clustermesh

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9572]
A user reported on Slack that the operator would not start up, logs like this:

https://cilium.slack.com/archives/C53TG4J4R/p1573085478010800

```
level=info msg="Cilium Operator 1.6.90 a5f496448 2019-10-30T12:31:14-04:00 go version go1.13.3 linux/amd64" subsys=cilium-operator
level=info msg="Establishing connection to apiserver" host="https://100.65.0.1:443" subsys=k8s
level=info msg="Starting apiserver on address :9234" subsys=cilium-operator
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Retrieved node information from kubernetes" nodeName=ip-10-100-1-228.ec2.internal subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=10.100.1.228 ipAddr.ipv6="<nil>" nodeName=ip-10-100-1-228.ec2.internal subsys=k8s v4Prefix=100.64.4.0/24 v6Prefix="<nil>"
level=info msg="Starting to synchronize k8s services to kvstore..." subsys=cilium-operator
level=info msg="cilium-operator running with service synchronization: automatic etcd service translation enabled" address= kvstore=etcd subsys=cilium-operator
level=info msg="Waiting for all services to be synced with kubernetes before connecting to etcd" address= kvstore=etcd subsys=cilium-operator
level=fatal msg="Unable to start status api: http: Server closed" subsys=cilium-operator
```

I don't have timestamps for it.

When I suggested downgrading `operator` from `latest` to `1.6.3`, the operator started up fine.

**Comment by diversario** [comment]
I encountered this by following [the guide](http://docs.cilium.io/en/stable/gettingstarted/clustermesh/), after installing Cilium with managed etcd as described [here](http://docs.cilium.io/en/stable/gettingstarted/k8s-install-etcd-operator/#k8s-install-etcd-operator) – but instead of downloading a tarball I cloned the repo and ran `helm template` in the repo master branch at commit 94d62d66c925abd82a47bd3a6df46d5341529173.

**Comment by Skarlso** [comment]
No Cluster Mesh here, yet still the same issue with exactly the same log and cilium operator version.

Is there any word on this issue yet? Is it being investigated? 

Cheers,
Gergely.

**Comment by joestringer** [comment]
@Skarlso Do you have full reproduction instructions or a [sysdump](http://docs.cilium.io/en/latest/troubleshooting/#automatic-log-state-collection) ? In particular I'm curious how much of the environment you share with the reported details above.

I'm wondering if there's some change in the managed etcd handling that we've put in place on master which causes this, or if it's related to some change we made to the operator. /cc @aanm

**Comment by aanm** [comment]
@joestringer Not that I'm aware of, @Skarlso a sysdump would be really useful in this case.

**Comment by Skarlso** [comment]
Sheesh sorry this dropped off my radar. I think we reverted and went ahead. I'll try to gather some more information if I can.

**Comment by joestringer** [comment]
Potentially related to #9819?

@Skarlso how many clusters were you trying to use when you hit this issue?

**Comment by tgraf** [comment]
This has been hit by user Marcel on slack with fewer than 128 services.

**Comment by tgraf** [comment]
User confirmed 1.6.5 is working whereas master is not.

**Comment by tgraf** [comment]
The race is being hit as follows:

This waits for the k8s cache to be synced:
https://github.com/cilium/cilium/blob/master/operator/main.go#L300

The k8s service update handler of the operator accesses the kvstore:
https://github.com/cilium/cilium/blob/master/operator/k8s_service_sync.go#L70

The above service handler must succeed to unblock the wait

The kvstore is only connected to after the wait blockade:
https://github.com/cilium/cilium/blob/master/operator/main.go#L312

When clustermesh is enabled with any global service, even a single global service will block bootstrap.
