### ISSUE TITLE
Support Static Egress IP

### ISSUE THREAD

**Issue by christianhuening** [cilium/cilium#9589]
## Proposal / RFE

**Is your feature request related to a problem?**
We need to connect to a service external to our cluster, which requires a static source IP in subsequent requests for the same session. Since obviously our services are set up in an H/A we cannot provide this with pure Kubernetes. We do not have VMs available and want to stay with our pure Kubernetes based solution. Our setup features a specific amount of nodes which explicitly act as network node which are connected to ISPs. Between our nodes we do pure BGP routing. 

**Describe the solution you'd like**

Ideally we would be able to use a CRD which allows to specify a labelSelector and a desired Egress IP which is then used as SourceIP in all egress traffic by the matched Pods.

For example this could then be solved by routing all traffic for one such application over exactly one of our net nodes and to have a failover option should the node die.

**Comment by christianhuening** [comment]
ping

**Comment by christianhuening** [comment]
Ping

**Comment by christianhuening** [comment]
pong

**Comment by christianhuening** [comment]
@brb 👍

**Comment by joestringer** [comment]
Seems like OVN has gone through the design process for something that looks similar, here: 

https://github.com/alexanderConstantinescu/enhancements/blob/ovn_egressip/enhancements/network/egressip_for_ovn_kubernetes.md

**Comment by pchaigno** [comment]
Our Egress IP Gateway feature introduced in v1.10 should cover this. See [the release blog post](https://cilium.io/blog/2021/05/20/cilium-110#egressgateway) for a description and pointers. I'm going to close this issue, but don't hesitate to ping me if there's something more to it than what the egress IP gateway covers.
