### ISSUE TITLE
Cluster wide l7 protocol visibility

### ISSUE THREAD

**Issue by genbit** [cilium/cilium#9593]
I can enable DNS Proxy visibility using cluster-wide cilium network policy, however it will put all endpoints into default deny on egress and be a potentially disruptive change to my workloads. 

Would be great if I can leverage L7 protocol visibility-only mode (http://docs.cilium.io/en/latest/policy/visibility) on a cluster-wide level, and just specify that all endpoints egress to 53 UDP is a DNS protocol.

reference: https://github.com/cilium/cilium/issues/9088 https://github.com/cilium/cilium/issues/9592

**Comment by Manuelraa** [comment]
Does someone have an working example we can copy&paste?
