### ISSUE TITLE
Pod that is destroyed while cilium-agent is down gets stuck attempting to restore

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9599]
Cilium v1.6.3

If an endpoint is deleted while `cilium-agent` is not running, then the state on the filesystem remains but the network links (and containers/pods) may disappear. The next time that Cilium starts up and restores the endpoints from the filesystem, Cilium constantly complaining in `cilium status` with a controller that is unhealthy:

```
$ cilium status
...
Controller Status:   52/53 healthy
...
  endpoint-2594-regeneration-recovery         never          4m25s ago    188     regeneration recovery failed
```

This message continually repeats in the endpoint log for the relevant endpoint:
```
2019-11-12T15:58:42Z   Failure   ready                   Error regenerating endpoint: Failed to replace Qdisc for lxc714f0a329989: Link not found
2019-11-12T15:58:42Z   OK        ready                   Completed endpoint regeneration with no pending regeneration requests
2019-11-12T15:58:42Z   OK        regenerating            Regenerating endpoint: one or more identities created or deleted
2019-11-12T15:58:42Z   OK        waiting-to-regenerate   Triggering endpoint regeneration due to one or more identities created or deleted

```

We should detect this case where the underlying devices/containers have been removed, log a warning that we are failing to restore an endpoint because it disappeared before Cilium started up, then either do not start the `endpoint-xxx-regeneration-recovery` controller, or stop that controller and remove the endpoint.

**Comment by joestringer** [comment]
More information:

I tried:
* Deploying a demo application
* Deploying Cilium without tolerations
* Tainting a node
* Deleting Cilium pods (so it's not redeployed)
* Deleting the demo app
* Removing the tolerations so that Cilium will redeploy/restore

In this case, upon restore, Cilium attempts to probe k8s to check that the pod is still alive, and because the resource was deleted, it reports:
```
level=warning msg="Unable to restore endpoint, ignoring" endpointID=2059 error="kubernetes pod not found" k8sPodName=default/testclient-j625r subsys=datapath
```

...which suggests that the problem is a bit more nuanced than simply removing the pod. It's possible that the pod is still available in some capacity, but not fully removed. I have not attempted recreating the pod again with the same name to see if this allows the problem to be reproduced.

**Comment by aanm** [comment]
PR https://github.com/cilium/cilium/pull/9586 should probably help with this...

**Comment by tgraf** [comment]
@aanm @joestringer Did #9586 fix this?

**Comment by joestringer** [comment]
@tgraf As far as I'm aware, the original reporter of the bug has not yet tried a release of Cilium with #9586 in it to confirm.

**Comment by aanm** [comment]
Fixed and backported by https://github.com/cilium/cilium/pull/9551
