### ISSUE TITLE
Support exposing services through multiple devices

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9620]
NodePort services are currently exposed through the native device which has the default route on the host or a user specified device. In tunneling mode, they are additionally exposed through the tunnel interface (`cilium_vxlan` or `cilium_geneve`). This issue tracks exposing services through multiple native devices.

**Comment by Frankkkkk** [comment]
We have the same problem (i.e. each bare-metal machine has two upstream connections to two different switching leafs). Routing is done using BGP-to-the-host.
