### ISSUE TITLE
eni: agent failed to restart after patching wrong value in ciliumnode

### ISSUE THREAD

**Issue by jaffcheng** [cilium/cilium#9644]
## Bug report

**General Information**

- Cilium version 1.6.2
- Orchestration system version in use k8s 1.13.2

**How to reproduce the issue**

**1. start cilium-agent in `ipam:eni` mode, ciliumnode resource is created automatically
2. set random subnet-tags for this node**
```
kubectl patch ciliumnodes.cilium.io nodename --type='json' -p='[{"op": "replace", "path": "/spec/eni/subnet-tags", "value":[{"key":"testkey","value":"testvalue"}]}]'
```
The `subnet-tags` shown in describe ciliumnode:
```
Spec:
...
  Eni:
...
    Subnet - Tags:
      Key:     testkey
      Value:   testvalue
...
```
**3. restart cilium-agent, cilium-agent exited with the following logs:**

```
level=info msg="Updating CRD (CustomResourceDefinition)..." name=v2.CiliumIdentity subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=v2.CiliumIdentity subsys=k8s
level=info msg="k8s mode: Allowing localhost to reach local endpoints" subsys=daemon
level=info msg="Initializing node addressing" subsys=daemon
level=info msg="Restored IPv4 internal node IP: xx.xx.xx.xx" subsys=node
level=info msg="Initializing CRD-based IPAM" subsys=ipam
level=info msg="Subscribed to CiliumNode custom resource" name=nodename subsys=ipam
level=fatal msg="Unable to create CiliumNode resource" error="ciliumnodes.cilium.io \"nodename\" already exists" subsys=nodediscovery

```

**Comment by ungureanuvladvictor** [comment]
@jaffcheng I think the way you're updating the cn custom resource does not match the type of the `SubnetTags` field in the eni spec (https://github.com/cilium/cilium/blob/master/pkg/k8s/apis/cilium.io/v2/types.go#L806-L810). You can see that it is a `map[string]string`. With your `kubectl` you're making the `subnets-tags` field in the CiliumNode to be an array.

**Comment by jaffcheng** [comment]
Thanks for pointing that out @ungureanuvladvictor , I just realized that and after patching the wrong value, cilium-agent prints right error logs immediately, which I missed because I have restarted cilium-agent:
```
level=error msg=k8sError error="github.com/cilium/cilium/pkg/ipam/crd.go:148: Failed to list *v2.CiliumNode: v2.CiliumNodeList.Items: []v2.CiliumNode: v2.CiliumNode.Spec: v2.NodeSpec.ENI: v2.ENISpec.SubnetTags: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|et-tags\":[{\"key\":\"se|..., ...
```
After a restart, agent log only shows:
```
level=fatal msg="Unable to create CiliumNode resource" error="ciliumnodes.cilium.io \"nodename\" already exists" subsys=nodediscovery
```
I think it would be easier to debug if cilium-agent prints the CRD validation error on restart.

**Comment by ungureanuvladvictor** [comment]
I agree with your point @jaffcheng but I suspect we can sidestep this problem entierly by having the k8s apiserver apply validation to the `ciliumnodes.cilium.io`. Without a lot of experience in this area I've found https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema and I suspect Cilium is already doing this for CNPs.

@aanm any hints in this area?

**Comment by aanm** [comment]
@ungureanuvladvictor yep, PR #9655 seems to be in the right track.
