### ISSUE TITLE
Cilium API handler panicked at url /v1/identity/12345

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9659]
Cilium v1.6.3
Using etcd for identity propagation, not CRD.

```
level="warning" msg="Cilium API handler panicked" client=@ method=GET panic_message="runtime error: invalid memory address or nil pointer dereference" subsys=api url=/v1/identity/12345
```

**Comment by joestringer** [comment]
Digging around in the API handler for identity labels fetch, I found that PR https://github.com/cilium/cilium/pull/9138 makes a bunch of changes in this area. It is intended to clean up casting in conjunction with the kvstore, and it may inadvertently fix the issue.

**Comment by joestringer** [comment]
There were identity releases occurring 8 seconds prior to this log message, but unfortunately the identity number is not known, only the labels. So there's no way to determine whether they are related to this message or not.

**Comment by joestringer** [comment]
Not sure why I linked #9636, in context the comment seems to be entirely unrelated to this issue.

**Comment by aanm** [comment]
@joestringer do you have more info regarding this? A stacktrace? Can we add more debug messages into Cilium that allow us to easily find the issue in the future?

**Comment by joestringer** [comment]
There is a backtrace, I pinged you on Slack with deeper links.

The failure is actually on line 123 of identity.go where the `Identity` is dereferenced to fetch its `NumericIdentity`:

https://github.com/cilium/cilium/blob/e6233255ff3b9f30acdc445784413f9964612cb9/pkg/identity/identity.go#L117-L126

The weird part is that there's a nil check just before the dereference which apparently passes, so that suggests that this code is being executed with the receiver being a shared pointer which gets reset or something?

The identity in this case appears to be a local identity.

**Comment by joestringer** [comment]
Given the new information above, I now doubt that #9138 fixes the issue and expect that this bug is still present on master.

**Comment by tgraf** [comment]
@joestringer @aanm What are the next steps on this issue? Do we need more information?

**Comment by aanm** [comment]
probably related to https://github.com/cilium/cilium/issues/8816

**Comment by joestringer** [comment]
@aanm Do you know if we've seen this in any recent releases?

**Comment by aanm** [comment]
@joestringer no, I think we can close this. It was probably related with #8816
