### ISSUE TITLE
v1.6.4 K8s dependency should be expanded to older versions in order to not scare people

### ISSUE THREAD

**Issue by Antiarchitect** [cilium/cilium#9683]
## Support

Please change v1.6.4 Release Notes in order to bump dependencies not only to K8s 1.16.3 but also 1.14.9 and 1.15.6. Was really scared of need to upgrade my cluster from 1.14.8

**Comment by aanm** [comment]
@Antiarchitect the golang dependencies are always updated to the latest version of kubernetes. What we usually update is the k8s versions tested in the CI for which that is missing in the release notes. However in the Cilium docs you can always find out which versions are supported by a particular Cilium release. https://docs.cilium.io/en/v1.6/kubernetes/compatibility/

**Comment by aanm** [comment]
Updated release note! Thanks for the feedback!
