### ISSUE TITLE
cilium service list is out of sync with cilium bpf lb list

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#9684]
cilium bpf lb list  and cilium service list show backend-less service:
```
10.98.23.248:8080   0.0.0.0:0 (8) [FLAGS: NONE]      <------
10.96.0.1:443       192.168.86.26:6443 (5)
                    0.0.0.0:0 (5) [FLAGS: NONE]
10.96.0.10:9153     10.217.0.146:9153 (3)
                    10.217.1.62:9153 (3)
                    0.0.0.0:0 (3) [FLAGS: NONE]
10.99.53.14:10080   10.217.1.165:80 (4)
                    0.0.0.0:0 (4) [FLAGS: NONE]
                    10.217.0.172:80 (4)
10.100.31.84:2379   0.0.0.0:0 (7) [FLAGS: NONE]
                    10.217.0.220:2379 (7)
10.102.42.155:80    10.217.0.172:80 (9)
                    10.217.1.165:80 (9)
                    0.0.0.0:0 (9) [FLAGS: NONE]
10.96.0.10:53       0.0.0.0:0 (2) [FLAGS: NONE]
                    10.217.0.146:53 (2)
                    10.217.1.62:53 (2)
```
service list:
```
2    10.96.0.10:53       ClusterIP      1 => 10.217.0.146:53      
                                        2 => 10.217.1.62:53       
3    10.96.0.10:9153     ClusterIP      1 => 10.217.0.146:9153    
                                        2 => 10.217.1.62:9153     
4    10.99.53.14:10080   ClusterIP      1 => 10.217.0.172:80      
                                        2 => 10.217.1.165:80      
5    10.96.0.1:443       ClusterIP      1 => 192.168.86.26:6443   
7    10.100.31.84:2379   ClusterIP      1 => 10.217.0.220:2379    
8    10.98.23.248:8080   ClusterIP                                
9    10.102.42.155:80    ClusterIP      1 => 10.217.0.172:80      
                                        2 => 10.217.1.165:80   
```

**Comment by jrfastab** [comment]
In above at least the service IP is in both lb and cilium but here is a case where that is not the case,
```
 $ kubectl -n kube-system exec cilium-25spp -- cilium service list
ID   Frontend              Service Type   Backend                   
1    10.101.23.188:80      ClusterIP      1 => 10.217.0.81:80       
2    10.100.80.40:2379     ClusterIP      1 => 10.217.1.131:2379    
                                          2 => 10.217.0.163:2379    
                                          3 => 10.217.1.205:2379    
3    10.96.0.10:53         ClusterIP      1 => 10.217.0.231:53      
4    10.96.0.10:9153       ClusterIP      1 => 10.217.0.231:9153    
5    10.96.0.1:443         ClusterIP      1 => 192.168.86.26:6443   
6    10.103.63.216:10080   ClusterIP      1 => 10.217.0.81:80      
```
$ kubectl -n kube-system exec cilium-25spp -- cilium bpf lb list
SERVICE ADDRESS       BACKEND ADDRESS               
10.96.0.10:9153       0.0.0.0:0 (4) [FLAGS: NONE]   
                      10.217.1.188:9153 (4)         
                      10.217.0.231:9153 (4)         
10.110.96.174:10080   0.0.0.0:0 (6) [FLAGS: NONE]   
10.96.0.1:443         0.0.0.0:0 (5) [FLAGS: NONE]   
                      192.168.86.26:6443 (5)        
10.101.23.188:80      10.217.1.108:80 (1)           
                      10.217.0.81:80 (1)            
                      0.0.0.0:0 (1) [FLAGS: NONE]   
10.103.63.216:10080   10.217.1.108:80 (6)           
                      0.0.0.0:0 (6) [FLAGS: NONE]   
                      10.217.0.81:80 (6)            
10.100.80.40:2379     0.0.0.0:0 (2) [FLAGS: NONE]   
                      10.217.1.205:2379 (2)         
                      10.217.0.163:2379 (2)         
                      10.217.1.131:2379 (2)         
10.96.0.10:53         10.217.0.231:53 (3)           
                      10.217.1.188:53 (3)           
                      0.0.0.0:0 (3) [FLAGS: NONE] 
```

**Comment by jrfastab** [comment]
Additionally once we get in this state I don't know how to get out of it, I think (if its not already done) we should be sync'ing the service list and bpf lb tables on restart but it seems not because cilium restart doesn't fix the problem.

**Comment by jrfastab** [comment]
Only work-around I've found is to do a node restart to clear the state.

**Comment by jrfastab** [comment]
Here is the yaml that was reproducing it,
```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "netperf-policy"
metadata:
  name: "netperf-policy"
spec:
  endpointSelector:
    matchLabels:
      id: netperf-server
  ingress:
  - fromEndpoints:
    - matchLabels:
        id: netperf-client
    toPorts:
    - ports:
      - port: "12865"
        protocol: TCP
```

**Comment by jrfastab** [comment]
And the diff from PR https://github.com/cilium/cilium/pull/9685
```
$ git diff
diff --git a/test/k8sT/DatapathConfiguration.go b/test/k8sT/DatapathConfiguration.go
index fd105d05a..8beecbe43 100644
--- a/test/k8sT/DatapathConfiguration.go
+++ b/test/k8sT/DatapathConfiguration.go
@@ -80,7 +80,7 @@ var _ = Describe("K8sDatapathConfig", func() {
                netperfServiceName := "netperf-service"
 
                netperfManifest := helpers.ManifestGet(kubectl.BasePath(), "netperf-deployment.yaml")
-               helpers.ManifestGet(kubectl.BasePath(), "netperf-policy.yaml")
+               //helpers.ManifestGet(kubectl.BasePath(), "netperf-policy.yaml")
 
                kubectl.ApplyDefault(netperfManifest).ExpectSuccess("Netperf cannot be deployed")
```

**Comment by brb** [comment]
@jrfastab Can you attach the cilium-agent log?

**Comment by joestringer** [comment]
@jrfastab are you still seeing this on master?

**Comment by jrfastab** [comment]
I'll try soon, I haven't seen it for awhile but haven't been stressing these bits either.

**Comment by joestringer** [comment]
Not seeing this recently on master, removing it from release blockers for 1.7.

**Comment by jrfastab** [comment]
I've also not been able to reproduce it either in my setup.

**Comment by borkmann** [comment]
Ok, closing for now. Should we hit this again, we can reopen.
