### ISSUE TITLE
Support for Service Topology Aware Hints

### ISSUE THREAD

**Issue by arzarif** [cilium/cilium#9708]
Topology-Aware Hints

https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2433-topology-aware-hints

Stale:
####

Kubernetes/kube-proxy will be supporting service topology awareness (likely as a gated alpha feature) in its upcoming 1.17 release. Feature parity with their topology-aware service routing implementation would be ideal.

Linking associated KEP and PR for additional context:

KEP:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20181024-service-topology.md

PR:
https://github.com/kubernetes/kubernetes/pull/72046

**Comment by jcrowthe** [comment]
We are definitely looking forward to this work. Where today we run node local DNS in a non-HA fashion, Service Topology would provide thorough HA.

**Comment by fristonio** [comment]
As mentioned in [this slack thread](https://kubernetes.slack.com/archives/C09QYUH5W/p1598050198062200?thread_ts=1598050198.062200&cid=C09QYUH5W), the feature will likely not make it to beta in the current state. The K8s networking team is working on pushing out a new KEP for this soon.
We are likely going to wait until the new KEP is released for the feature.

**Comment by arzarif** [comment]
@fristonio - thanks for the heads up!

**Comment by dharmab** [comment]
For the curious, the new KEP is [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2004-topology-aware-subsetting/README.md) (still in early stages).

**Comment by alex-berger** [comment]
Any news on this as Topology Aware Hints are now [alpha since k8s `v1.21`](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/). This is a very important feature to reduce network bandwidth cost for k8s clusters running highly available on public cloud providers (which usually have very expensive inter availability zone network bandwidth prices).

**Comment by brb** [comment]
@alex-berger We might consider this for the 1.12.

**Comment by olemarkus** [comment]
Just to confirm there is interest, this is quite important for us as well.

**Comment by brb** [comment]
The PR is out https://github.com/cilium/cilium/pull/17929. You can test it by using the images built by https://github.com/cilium/cilium/runs/4261822899?check_suite_focus=true.
