### ISSUE TITLE
doc: the namespace is wrong when validating cilium installation with Azure CNI

### ISSUE THREAD

**Issue by bingosummer** [cilium/cilium#9710]
In https://docs.cilium.io/en/v1.6/gettingstarted/cni-chaining-azure-cni/#validate-the-installation, the namespace should be `cilium` instead of `kube-system`, because the `chaining.yaml` and the cilium release are in the namespace `cilium`.

https://docs.cilium.io/en/v1.6/gettingstarted/cni-chaining-aws-cni/ shares the validation step, whose namespace is `kube-system`.

**Comment by borkmann** [comment]
Thanks for reporting @bingosummer ! Would you like to send a small PR for updating the ...
- https://docs.cilium.io/en/v1.6/gettingstarted/cni-chaining-azure-cni/
- https://docs.cilium.io/en/v1.6/gettingstarted/k8s-install-aks/

... to use `kubectl -n cilium get pods` in the validation step for both?
