### ISSUE TITLE
Compilation issue when building cilium-runtime

### ISSUE THREAD

**Issue by Jianlin-lv** [cilium/cilium#9719]
## Bug report

**General Information**

Cilium version: Master

**How to reproduce the issue**
Running 'make docker-image-runtime'

 Compiling bpftool in Dockerfile.runtime will encounter the issue with following error:

``Auto-detecting` system features:
...                        libelf: [ on  ]
...                           bpf: [ on  ]

/bin/sh: 1: /tmp/linux/scripts/bpf_helpers_doc.py: not found
Makefile:184: recipe for target 'bpf_helper_defs.h' failed
make[1]: Leaving directory '/tmp/linux/tools/lib/bpf'
make[1]: *** [bpf_helper_defs.h] Error 127
make[1]: *** Deleting file 'bpf_helper_defs.h'
Makefile:31: recipe for target '/tmp/linux/tools/lib/bpf/libbpf.a' failed
make: *** [/tmp/linux/tools/lib/bpf/libbpf.a] Error 2
make: *** Waiting for unfinished jobs....
``

**Comment by aanm** [comment]
Fixed by https://github.com/cilium/cilium/pull/9715
