### ISSUE TITLE
Flexible CIDR =>remote encap address mapping

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#972]
Depends on #989 

This issue tracks the feature to provide alternative to the current static container IP => VTEP mapping.

- [ ] Establish way to retrieve managed CIDR of each node
  - [ ] via k8s API server
    - [x] PodCIDR field (tests missing)
    - [x] Annotation populated by each cilium-agent on its own node resource
  - [ ] via kvstore (#204 ?)
  - [ ] via daemon flag `--derive-node-address` (#313)
 - [ ] Add vtep BPF map to map `node_id` to VTEP `remote_addr`

edits:
@aanm - add PR #204 and marked PodCIDR field as done with tests missing
@aanm - add issues #313

**Comment by aanm** [comment]
Notes:
It's possible to retrieve `PodCIDR` field from kubernetes and `cilium daemon set` can leverage that with the option
```
env:
- name: "K8S_NODE_NAME"
  valueFrom:
    fieldRef:
      fieldPath: spec.nodeName
```

The user will need to set up the kubernetes controller-manger with the following options:
```
kube-controller-manager
...
--cluster-cidr="$(cluster_cidr)" \
--allocate-node-cidrs=true \
--node-cidr-mask-size="$(node_cidr_mask_size)" \
--configure-cloud-routes=false \
...
```
where:
- `cluster-cidr`: specifies the Pods CIDR for the whole cluster, the IPs assigned to the containers, for example: `10.0.0.0/10`
- `allocate-node-cidrs`: if set `true` will allocate, to each node, a specific CIDR from the one specified in `cluster-cidr`.
- `node-cidr-mask-size`: the mask size used for PodCIDR on each node, for example `16`.
- `configure-cloud-routes`: if set `false` there **won't** be set any routes in the cloud provider.

With a `cluster-cidr` set to `10.0.0.0/10`, it means all Pods across the cluster will have an IP matching this CIDR.

With a `node-cidr-mask-size` set to `16`, a container running on node 1 will have, for example, an IP from `10.0.0.0/16`, a container running on node 2 will have an IP from `10.1.0.0/16`, node 3 from `10.3.0.0/16` and so on...

Unfortunately, `cluster-cidr` from `kube-controller-manager` **does not** support IPv6.

**Comment by tgraf** [comment]
> configure-cloud-routes: if set false there won't be set any routes in the cloud provider.

Why does this matter? I assume this is just a hint for the documentation. These routes would remain unused anyway?

**Comment by aanm** [comment]
>Why does this matter? I assume this is just a hint for the documentation. These routes would remain unused anyway?

Yeah with `--cloud-provider` unset the only difference seems to be:

```
E0613 22:33:54.806236       1 controllermanager.go:494] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail.
I0613 22:33:54.806292       1 controllermanager.go:519] Will not configure cloud provider routes for allocate-node-cidrs: true, configure-cloud-routes: false.
```
vs
```
E0613 22:28:43.110828       1 controllermanager.go:494] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail.
W0613 22:28:43.110842       1 controllermanager.go:510] configure-cloud-routes is set, but no cloud provider specified. Will not configure cloud provider routes.
```
