### ISSUE TITLE
Consider ipFamily field in Service object when running k8s in dual-stack mode

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9776]
For the semantics of the `ipFamily` field, see the docs: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services.

**Comment by brb** [comment]
Currently, the service provisioning (in particular, https://github.com/cilium/cilium/blob/v1.8.2/pkg/k8s/service.go#L62) ignores the `ipFamily` field in a `Service` object. This is not a problem for `ClusterIP` services, as kube-apiserver will decide on its own whether to create IPv4 or IPv6 service representation (see https://kubernetes.io/docs/concepts/services-networking/dual-stack/#services for the selection criteria), and cilium-agent provisions what kube-apiserver will tell it. However, in the case of `NodePort`/`LoadBalancer`/`externalIPs` service, cilium-agent makes a decision based on its `--enable-ipv{4,6}` settings and checking for `ClusterIP` IP addr family. The latter should be replaced by a check for `ipFamily` setting.

**Comment by nathanjsweet** [comment]
closing for #13074
