### ISSUE TITLE
Provide a cilium-agent flag to clean all state data

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#979]
Something like `cilium-agent --clean-all` would:
- clean all bpf maps
- unmount bpffs
- remove routes created by cilium interfaces
- remove cilium interfaces
- remove `/var/run/cilium` (and `/var/lib/cilium`?)
- remove cilium-cni configurations?

Basically restoring to the last state before cilium was installed **without** starting the agent, this would be for clean up purposes only.

**Comment by tgraf** [comment]
Sounds good, not sure it is a microtask. Might be non-trivial.
