### ISSUE TITLE
Cilium with etcd spams logs with "retrying of unary invoker failed"

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9791]
Multiple users have reported seeing these messages in the logs when running recent (eg v1.6) releases of Cilium:

```
{"level":"warn","ts":"2019-12-19T17:25:29.221Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-62c44804-9924-4add-a807-d58b11854d2f/etc-server1:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
```

Questions:
* [ ] What does this log mean?
* [ ] Does it imply broken etcd connectivity?
* [ ] What are the debugging steps?
* [ ] This log does not follow the standard Cilium log output format, can we turn it into a meaningful log or report its status through a Cilium controller?

**Comment by joestringer** [comment]
Slack user reports seeing these messages after Cilium appears to have successfully connected to etcd, with these logs:

```
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/etcd-config/etcd.config endpoints="[https://etcd-server1:2379 https://etcd-server3:2379]" etcdEndpoint="https://etcd-server2:2379" subsys=kvstore version=3.3.13
```

**Comment by joestringer** [comment]
I have seen these messages show up in a testing cluster once, just before setting up the BPF datapath. In that cluster they do not recur.

**Comment by tgraf** [comment]
Potentially related:
https://github.com/etcd-io/etcd/issues/11186
