### ISSUE TITLE
eni: modify ciliumnode spec succeeds but no change reflects

### ISSUE THREAD

**Issue by jaffcheng** [cilium/cilium#9797]
**General Information**

- Cilium version 1.6.3
- Kernel version 4.14.67
- K8S 1.13.2

**How to reproduce the issue**

1. start ENI mode cilium-agent on an EC2 instance, wait for ciliumnode CR to be created
2. as soon as the ciliumnode CR appears, modify the ciliumnode spec immediately with the following command:
```
kubectl patch ciliumnodes.cilium.io $node --type='json' -p='[{"op": "replace", "path": "/spec/eni/pre-allocate", "value":2}]'
```
3. check ciliumnode again, `pre-allocate` is still the default value 8

**Comment by jaffcheng** [comment]
Maybe related with https://github.com/cilium/cilium/issues/9604

**Comment by ungureanuvladvictor** [comment]
@jaffcheng i think this is the same as https://github.com/cilium/cilium/issues/9806
