### ISSUE TITLE
Identities not garbage-collected when using CRD backend

### ISSUE THREAD

**Issue by joe-carpenter** [cilium/cilium#9805]
## Bug report

**General Information**

- Cilium version (run `cilium version`)

```
Client: 1.6.1 161ffdb46 2019-09-09T13:14:29-07:00 go version go1.12.8 linux/amd64
Daemon: 1.6.1 161ffdb46 2019-09-09T13:14:29-07:00 go version go1.12.8 linux/amd64
```

- Kernel version (run `uname -a`)

(various) example shown:

```
Linux ip-10-29-57-199.eu-west-2.compute.internal 4.19.86-coreos #1 SMP Mon Dec 2 20:13:38 -00 2019 x86_64 Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz GenuineIntel GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Link to relevant artifacts (policies, deployments scripts, ...)

N/A

- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

N/A

**How to reproduce the issue**

1. install Cilium via `kops` with following config:

```
"cilium": {
        "IPTablesRulesNoinstall": false,
        "autoDirectNodeRoutes": false,
        "bpfCTGlobalAnyMax": 0,
        "bpfCTGlobalTCPMax": 0,
        "clusterName": "REDACTED",
        "cniBinPath": "",
        "enableNodePort": false,
        "enableipv4": false,
        "enableipv6": false,
        "monitorAggregation": "",
        "nodeInitBootstrapFile": "",
        "preallocateBPFMaps": false,
        "reconfigureKubelet": false,
        "removeCbrBridge": false,
        "restartPods": false,
        "sidecarIstioProxyImage": "",
        "toFqdnsEnablePoller": false,
        "version": "v1.6.1"
      }
```
2. Create + destroy lots of pods quickly (we -have- had a bunch of K8s cronjobs firing every minute!), which causes new identities to be created. 
3. Watch the number of `ciliumidentities.cilium.io` increasing until it hits the hard limit of `65535`, exhausting the available pool.

**Comment by joe-carpenter** [comment]
PR: https://github.com/cilium/cilium/pull/9804 created by @tgraf  to add some debug logging to aid troubleshooting.

**Comment by aanm** [comment]
@tgraf was this fixed by #9804 ?

**Comment by tgraf** [comment]
@aanm No, #9804 adds the necessary logging to get to the bottom of the issue.

**Comment by daviddyball** [comment]
@tgraf / @aanm  Any idea if we'll see another `1.6.x` release that includes the GC logging? At the moment we're having to manually garbage collect identities periodically :disappointed:

**Comment by tgraf** [comment]
@aanm Do we want to backport #9804 to 1.6?

**Comment by aanm** [comment]
@daviddyball can you give us more information about it? Is the same environment as point it out by @joe-carpenter? Is `cilium-operator` running in your cluster?

**Comment by daviddyball** [comment]
@aanm I am a colleague of @joe-carpenter's, so we're diagnosing the same issues :wink:

**Comment by aanm** [comment]
discussed offline with @daviddyball , the issue was that the cilium-operator deployment was not running with the CRD mode due the lack of [1] in the deployment file.
[1]
```
        - name: CILIUM_IDENTITY_ALLOCATION_MODE
          valueFrom:
            configMapKeyRef:
              key: identity-allocation-mode
              name: cilium-config
              optional: true
```

**Comment by aanm** [comment]
A fix was made into kops https://github.com/kubernetes/kops/pull/8445
