### ISSUE TITLE
ciliumnode spec is overwritten by default values when agent restarts

### ISSUE THREAD

**Issue by jaffcheng** [cilium/cilium#9806]
**General Information**

- Cilium version 1.6.5
- Kernel version 4.14.67
- K8S 1.13.2

**How to reproduce the issue**

1. start ENI mode cilium-agent on an EC2 instance
2. edit ciliumnode, change the value of fields in spec, e.g. set `pre-allocate` to 2
3. restart cilium-agent, the modified values are overwritten by default values.

**Comment by ungureanuvladvictor** [comment]
Just to note this down: the update happens in https://github.com/cilium/cilium/blob/b37274a83488423f76ddf223c1643c358c52ceda/pkg/nodediscovery/nodediscovery.go#L206-L325.

**Comment by ungureanuvladvictor** [comment]
I think the root problem is that we're not checking if the cilium node was updated out of band (not sure if there is a way to know that).

**Comment by aanm** [comment]
@ungureanuvladvictor these are the faulty lines
https://github.com/cilium/cilium/blob/b37274a83488423f76ddf223c1643c358c52ceda/pkg/nodediscovery/nodediscovery.go#L269-L278

We should only set them if the spec does not exist.

**Comment by jaffcheng** [comment]
I'm not sure if we should sync ciliumnode with CNI conf every time agent restarts, which implies we don't allow any updates out of band. @aanm @tgraf @ungureanuvladvictor

**Comment by jaffcheng** [comment]
> @jaffcheng Is this still an issue with a recent Cilium version? If not let's close this issue. Thank you

The behavior is not changed, but we managed to live with it. Let's close this.
