### ISSUE TITLE
CI: Flaky runtime.RuntimeMemcache

### ISSUE THREAD

**Issue by raybejjani** [cilium/cilium#9812]
This test began failing sometime over the new-year break. Some example failures:
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/9942/ 
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/9951/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/9938/

This is most likely a race, as different tests fail. This may be related to other slowdown issues we've been having with the CI, so it may be "fixable" elsewhere.

**Comment by joestringer** [comment]
Duplicate of #11412 which is now in the v1.8 disabled CI tests project.
