### ISSUE TITLE
Support for ServiceTopology

### ISSUE THREAD

**Issue by jcrowthe** [cilium/cilium#9817]
## Proposal / RFE
As part of Kubernetes 1.17, k8s services now support the ability to prefer one backing pod over others, based on node labels. This `ServiceTopology` feature allows more intelligent routing, such as first preferring a destination pod found on the same host, second in the same cloud AZ, and finally fallback to anywhere. 

Since this feature was implemented in `kube-proxy` and since Cilium no longer requires `kube-proxy` to run, I believe this feature needs to be implemented in Cilium as well. This is a request to do so.

Details: https://kubernetes.io/docs/concepts/services-networking/service-topology/

**Comment by brb** [comment]
@jcrowthe Thanks for the issue request. We have already an issue for it - #9708, so closing this issue.
