### ISSUE TITLE
Documentation Documentation/install/system_requirements.rst

### ISSUE THREAD

**Issue by tardich** [cilium/cilium#9825]
## Proposal

**General Information**

- Cilium version: 1.6.5
- Kernel version: 4.14.138-rancher
- Orchestration system version in use: k8s 1.15.5

Linux Distribution Compatibility Matrix: RancherOS 1.5.5

**Comment by aanm** [comment]
Hello @tardich can you clarify exactly what the issue is? Thanks

**Comment by tardich** [comment]
That<s not really an issue. It's an addon to the documentation. I saw this OS was missing and we have a couple of deployments with it.

**Comment by brb** [comment]
@tardich Thanks for letting us know. Was it enough just to follow the standard installation guide?
