### ISSUE TITLE
CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with MetalLB Connectivity to endpoint via LB

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9832]
## CI failure

[6ded1fae_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_MetalLB_Connectivity_to_endpoint_via_LB.zip](https://github.com/cilium/cilium/files/4040367/6ded1fae_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_MetalLB_Connectivity_to_endpoint_via_LB.zip)

```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Can not connect to service "http://192.168.36.240" from outside cluster
Expected command: docker exec -i  client-from-outside curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://192.168.36.240 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000017()', Connect: '0.000000',Transfer '0.000000', total '5.003482'
Stderr:
 	 

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:463
```

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/9980/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_MetalLB_Connectivity_to_endpoint_via_LB/

**Comment by brb** [comment]
Closing this, as the test is currently disabled, and after #9901 the test is going to be run in completely different setup.

**Comment by aanm** [comment]
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18120/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_MetalLB_Connectivity_to_endpoint_via_LB/

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Can not connect to service "http://192.168.36.241" from outside cluster
Expected command: kubectl exec -n kube-system log-gatherer-w4gq7 -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://192.168.36.241 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000025()', Connect: '0.000000',Transfer '0.000000', total '5.000174'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:430
```
[d7681bc0_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_MetalLB_Connectivity_to_endpoint_via_LB.zip](https://github.com/cilium/cilium/files/4369941/d7681bc0_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_MetalLB_Connectivity_to_endpoint_via_LB.zip)


From https://github.com/cilium/cilium/pull/10661

**Comment by joestringer** [comment]
From weekly meeting:
* Can we get virtualbox logs for this case?

**Comment by brb** [comment]
Closing this issue, as it duplicates #10763.
