### ISSUE TITLE
Lost default route when deployment cilium on MACCHIATObin

### ISSUE THREAD

**Issue by Jianlin-lv** [cilium/cilium#9834]
## Bug report

**General Information**

- Cilium version v1.6.4
- Kernel version  4.14.22-armada-18.09.3

**How to reproduce the issue**
Disable CONFIG_IP_MULTIPLE_TABLES kernel module

We have ported Cilium v1.6.4 on Arm server. 
Under this premise, try to deploying cilium on MACCHIATObin, which is an Arm-based development board.
Most of the problems encountered in this process are related to the kernel configuration. 
One of the most serious problems is that when the policy routing kernel module is not enabled,following command
	'ip route replace table 2005 default via 192.168.0.XX'
will cause the default route to be overwritten and
the external network cannot be accessed.
so it is necessary to check the kernel configuration about policy routing.

**Comment by borkmann** [comment]
Hello @Jianlin-lv, I'm aware of one kernel issue that might affect deployment on arm64, that is csum_diff() handling. Will have a kernel fix early next week for it.

In your case, is the agent coming up, do you have a full agent log?

**Comment by Jianlin-lv** [comment]
[cilium-debug-thunderx2-master-1_11-OK.log](https://github.com/cilium/cilium/files/4048307/cilium-debug-thunderx2-master-1_11-OK.log)
hi borkmann, attached is the log of cilium(master version) running on thunderx2;
I also deployed Nginx to verify and test k8s cluster that composed by three Arm nodes a few days ago.
![cilium](https://user-images.githubusercontent.com/19404437/72190617-ee5c5f00-343a-11ea-8c50-ba34311ad69d.png)

Would you explain the issue of csum_diff in more detail?
