### ISSUE TITLE
CI: K8sPolicyTest Basic Test TLS policy

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9869]
## CI failure
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Cannot connect from "app2-776cf4f9c6-lrb2q" to 'https://swapi.co:443/api/planets/1/'
Expected command: kubectl exec -n k8spolicytestbasictestchecksallkindofkubernetespolicies app2-776cf4f9c6-lrb2q -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 -4 --max-time 15 -v --cacert /cacert.pem https://swapi.co:443/api/planets/1/ -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 35 
Stdout:
 	 time-> DNS: '0.125623(104.31.76.248)', Connect: '0.126019',Transfer '0.000000', total '0.128330'
Stderr:
 	 *   Trying 104.31.76.248...
	 * TCP_NODELAY set
	 * Connected to swapi.co (104.31.76.248) port 443 (#0)
	 * ALPN, offering http/1.1
	 * successfully set certificate verify locations:
	   CAfile: /cacert.pem
	   CApath: none
	 * TLSv1.2 (OUT), TLS handshake, Client hello (1):
	 } [512 bytes data]
	 * LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to swapi.co:443 
	 * Closing connection 0
	 command terminated with exit code 35
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/k8sT/Policies.go:327
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/16358/testReport/junit/Suite-k8s-1/17/K8sPolicyTest_Basic_Test_TLS_policy/

https://github.com/cilium/cilium/pull/9866

**Comment by jrajahalme** [comment]
@aanm I'm looking at this, but for some reason there are no Envoy debug logs even though debug-verbose= flow is set via kubectl apply on the cilium.yaml. I did some local testing and it seems to me that `DeployCiliumOptionsAndDNS()` successfully applies the new yaml with the new options, but cilium-agent does NOT get restarted. If I kill the cilium-agent POD, it will be restarted by k8s with the new options applied earlier. I think in general `DeployCiliumOptionsAndDNS()` should actually restart cilium-agent with the new options, or no?

**Comment by aanm** [comment]
> @aanm I'm looking at this, but for some reason there are no Envoy debug logs even though debug-verbose= flow is set via kubectl apply on the cilium.yaml. I did some local testing and it seems to me that `DeployCiliumOptionsAndDNS()` successfully applies the new yaml with the new options, but cilium-agent does NOT get restarted. If I kill the cilium-agent POD, it will be restarted by k8s with the new options applied earlier. I think in general `DeployCiliumOptionsAndDNS()` should actually restart cilium-agent with the new options, or no?

@jrajahalme no, one needs to delete them manually, similar to:

https://github.com/cilium/cilium/blob/aab74826d7a14e4f357fb3cb3ea73a06d9235423/test/k8sT/Services.go#L403-L409

**Comment by nebril** [comment]
We are still hitting it: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10380/

**Comment by nebril** [comment]
Didn't see this happening for quite a long time, closing.
