### ISSUE TITLE
bpf: Use full destination IP when looking up local endpoints

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#989]
- [ ] Change mechanism to translate destination IP into endpoint ID
   So far we have extracted the endpoint ID from the address and then did a lookup in the table using the endpoint id as key. Instead, use the entire destination IP as key and store the endpoint as map value.

  This allows to use arbitrary addressing for local endpoints.

- [ ] Add a special entry to the table which represents the local node IP. If that entry is looked up, the existing path which causes routing into the local host is approached.

- [ ] If no match is found:
   - [ ] Match cluster prefix, if match, attempt cluster internal routing
   - [ ] otherwise, punt to local routing stack

**Comment by bretagne-peiqi** [comment]
the destination IP is VTEP IP ? If so, how could we know the VTEP IP before making a derivation.  I has always troubles in understanding the meaning of endpoint ID

**Comment by tgraf** [comment]
> the destination IP is VTEP IP ? If so, how could we know the VTEP IP before making a derivation. I has always troubles in understanding the meaning of endpoint ID

With destination IP I mean the destination IP which would refer to a container/pod.

The flexible VTEP mapping is tracked in issue #972
