### ISSUE TITLE
Add metric for dropped packets due to IP fragmentation

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9894]
Cilium datapath does not support IP fragmentation, and fragmented packets are usually dropped.

To make users aware of such cases, we need to export a metric for dropped packets. This requires adding `return DROP_FRAG_NOSUPPORT;` to the datapath and adding an adequate reason to the `cilium_drop_{count,bytes}_total` metrics.

**Comment by qmonnet** [comment]
`return DROP_FRAG_NOSUPPORT;` is used in the code, and there is an associated reason [in pkg/monitor/api/drop.go](https://github.com/cilium/cilium/blob/v1.7.2/pkg/monitor/api/drop.go#L63). Did you have something else in mind for this issue?

**Comment by brb** [comment]
Maybe it has been already resolved. However, before closing this issue one needs to check that a drop due to `DROP_FRAG_NOSUPPORT` is recorded in `cilium_drop_{count,bytes}_total` metrics with appropriate label (`cilium metrics list | grep drop_`).

**Comment by qmonnet** [comment]
Commit https://github.com/cilium/cilium/commit/938b4940f92bd3754568cad230916e64fa5b4a7a introduces checks for fragment metrics (although not for `DROP_FRAG_NOSUPPORT`, but rather for the number of fragments observed, `REASON_FRAG_PACKET`).

**Comment by pchaigno** [comment]
> Maybe it has been already resolved. However, before closing this issue one needs to check that a drop due to `DROP_FRAG_NOSUPPORT` is recorded in `cilium_drop_{count,bytes}_total` metrics with appropriate label (`cilium metrics list | grep drop_`).

I think this can be easily checked by running [our existing fragment tracking test](https://github.com/cilium/cilium/blob/1db771f25895ca8c830bd16336dc7f87df4d222a/test/k8sT/Services.go#L2643-L2650) with fragment tracking disabled.

If the metrics are missing, the same test can be used to iterate on a fix.

**Comment by navarrothiago** [comment]
I am planning take-up this issue
@pchaigno, please, could you assign it to me.

**Comment by pchaigno** [comment]
@navarrothiago I assigned you. Don't hesitate to reach out on #development or #sig-datapath if you have any question.
