### ISSUE TITLE
[CI flake] K8sDatapathConfig MonitorAggregation Checks that monitor aggregation flags send notifications

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#9902]
```
Monitor log contained unexpected number of egress notifications matching "SrcPort=37762"
Expected
    <int>: 3
to equal
    <int>: 4
---
Could not locate final FIN notification in monitor log
Expected
    <int>: 0
to be >
    <int>: 0
```

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10122/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10118/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10116/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10110/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_flags_send_notifications/

**Comment by raybejjani** [comment]
Also seen on 1.7 https://jenkins.cilium.io/view/Cilium-v1.7/job/cilium-v1.7-standard/614/

**Comment by joestringer** [comment]
Related: #9330 (likely similar style of failure although it affects a different test)
Related: #11127 which may provide a general framework to solve this kind of issue in CI.
