### ISSUE TITLE
K8sServicesTest Checks ClusterIP Connectivity Checks service on same node, K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy)

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#9904]
Seems like these two tests usually flake together.

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10110/
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10116/

**Comment by joestringer** [comment]
@nebril Please post the content of the failure in the PR description and ideally include the zip/tar from CI so that we can see what kind of failure this is later on.

If you know what this failure is, feel free to reopen and add additional detail. Closing for now.
