### ISSUE TITLE
Healthcheck fail. Different tests fail, but failures are caused by Cilium health check not passing.

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#9907]
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10118/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10109/testReport/junit/Suite-k8s-1/17/K8sDatapathConfig_ManagedEtcd_Check_connectivity_with_managed_etcd/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10108/testReport/junit/Suite-k8s-1/11/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10103/testReport/junit/Suite-k8s-1/17/K8sDatapathConfig_ManagedEtcd_Check_connectivity_with_managed_etcd/

**Comment by joestringer** [comment]
Closing as all of the links are dead.

Feel free to reopen and upload zips, copy/paste failure content here for further triage.
