### ISSUE TITLE
Add an option to run Hubble gRPC server embeded in Cilium process

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#9925]
Right now Hubble runs in a separate container and receive monitor events via unix domain socket. Also, it maintains a copy of Cilium state like fqdn cache, ip cache, endpoint list, and identity cache.

While there are some advantages in running Hubble separately from Cilium, lit would be nice to have an option to run Hubble embedded in Cilium process to reduce CPU/memory overhead.

**Comment by michi-covalent** [comment]
regarding the CLI, a standalone binary is quite a bit larger than adding a sub-command to cilium binary (+ ~20MB). just wanted to see if this is acceptable. cc @tgraf 

```
# cilium binary size without observe subcommand.
-rwxr-xr-x 1 root root 45M Mar  2 18:10 /usr/bin/cilium

# cilium binary size with observe subcommand.
-rwxr-xr-x 1 root root 47M Mar  2 18:33 /usr/bin/cilium

# hubble binary size without serve subcommand.
-rwxr-xr-x  1 michi  staff    25M Mar  2 10:34 hubble
```

**Comment by joestringer** [comment]
@michi-covalent Are there any remaining items here or can we close out this issue now?

**Comment by michi-covalent** [comment]
let's close it
