### ISSUE TITLE
Remove need for node-init DaemonSet on GKE

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#9938]
### Summary

Deployment on GKE currently requires to deploy the `node-init` DaemonSet which performs these steps:

- [ ] Mounting the BPF filesystem
- [ ] Reconfiguring kubelet to run in CNI mode

### Details

Deploying a separate DaemonSet (or adding an initContainer to the Cilium DaemonSet) has several disadvantages:

- It complicates setup
- It is fragile and breaks easily if file paths are changing
- It slows down bootstrapping of new nodes

Find a solution to deploy on GKE without requiring to deploy the node-init DaemonSet.

**Comment by joestringer** [comment]
When the current gcloud "rapid" channel beta becomes stable, it will ship a newer systemd which automounts bpffs, solving the first point.

**Comment by tgraf** [comment]
Cilium is now available natively on GKE:
https://cloud.google.com/blog/products/containers-kubernetes/bringing-ebpf-and-cilium-to-google-kubernetes-engine
