### ISSUE TITLE
BPF support for injecting layer 3 headers

### ISSUE THREAD

**Issue by Bun** [cilium/cilium#994]
It would be nice if it were possible to write a BPF program that can dynamically inject layer 3 extension headers, e.g. IPv4 options, IPv6 extension headers. This would allow injection of the IPv6 segment routing header, which can be used to do e.g. traffic engineering or network functions between containers/container clusters.

The current functionality offered by ``skb_change_head`` (only L2) and ``skb_change_tail`` (linearization, needlessly copying around data in the BPF program) are not sufficient for this purpose.

**Comment by borkmann** [comment]
Related: #909

**Comment by borkmann** [comment]
Done, for 4.13 (see #909 for further details): https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=2be7e212d5419a400d051c84ca9fdd083e5aacac
