### ISSUE TITLE
Verify the identity of incoming packets belongs to the source prefix

### ISSUE THREAD

**Issue by rlguarino** [cilium/cilium#995]
Right now if a node is compromised an attacker can modify the BPF programs on the compromised node to inject any ID into the packet. This means that any compromised node can act on behalf of any identity that exists in the cluster. It would be great if Cilium could guarantee that a node can only hyjack or act on behalf of endpoints that are already running on that node. Since in theory an attacker with root on the box could manipulate the running processes, any stronger guarantee is undermined by other attacks.

A nice stop gap that would be to verify that the identity and source IP prefix actually match. Or in other-words that a endpoint with the reported identity is actually scheduled to be running on the node that matches that source prefix.

With Kubernetes this would be pretty simple, but it will break the stateless nature of cilium's policy enforcement. A mapping of ID to valid source prefixes would need to be maintained on each host. The mapping would need to be build by querying this relationship:  ID -> K8s Labels ->  Pod -> Node -> Prefix for Every ID that a cilium node a Cilium is enforcing a policy using. This mapping could be computed by one daemon which watches K8s events and incrementally updates the mapping or each node could be responsible for managing it's own mapping.

**Comment by joestringer** [comment]
With the bpf ipcache map in recent releases, we could look up the source IP to get the expected identity to achieve this.
