### ISSUE TITLE
Pod Security Policies as part of the helm chart

### ISSUE THREAD

**Issue by uipo78** [cilium/cilium#9978]
## Proposal / RFE

**Is your feature request related to a problem?**

Installing Cilium with helm on a cluster with pod security policies enabled does not work out of the box. Additionally, there's no way to specify a service account with a particular pod security policy to be used by Cilium's components.

**Describe the solution you'd like**

Ideally a set of pod security policies will be included in the chart for each of cilium's components, enabling the least amount of attributes needed for Cilium to function.

**Comment by aanm** [comment]
@uipo78 
that's a good point. can be included if the k8s supports it. However not all users might have permissions to create pod security policies. So we might end up adding it in the generated file but comment it out. What do you think?

**Comment by uipo78** [comment]
yea, a variable such as `enablePodSecurityPolicies` in the `values.yaml` file to determine whether to render the pod security policies and all of the other necessary components (the necessary service accounts, cluster role bindings, etc) seems good to me.

**Comment by uipo78** [comment]
i'd offer to complete this ticket myself, but i'm not familiar enough with the project to know the minimal permissions needed to make the proper pod security policies.

**Comment by aanm** [comment]
@uipo78 feel free to open a PR introducing this, it's better to have a base point so we can discuss it in the next cilium developer meeting.
