### ISSUE TITLE
EPERM for sys_bpf with Ubuntu 18.04 with kernel 5.5

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9988]
While trying to update the ubuntu-next VM image in the CI to run with the latest kernel (#9657), we discovered that after cilium-agent has been installed, `bpf(2)` fails with `EPERM` which results in endpoint regeneration failures.

Creating a dummy map neither from the cilium-agent nor the host works:

```
vagrant@k8s1:~$ sudo bpftool map create /sys/fs/bpf/tc/globals/cilium_policy_01821 type hash key 16 value 16 entries 10000 name foobar
Error: map create failed: Operation not permitted
```

SELinux is not installed, and the kernel doesn't have the lockdown.

Also, the `EPERM` problem starts to occur after cilium-agent has been started on the node. I've set `ulimit -a unlimited`, but it didn't help. After ftracing, it might be that `EPERM` is returned by `security_bpf()`, as a probe for `bpf_get_file_flag()` was not fired, and there are no relevant calls in-between (unfortunately I was not able to get `$retval` for a kretprobe of `security_bpf()`).

Might be related to #9402.

**Comment by Antiarchitect** [comment]
Having similar issue:
```
level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID=e15e82f776 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=598 file-path=598_next_fail identity=24220 ipv4=10.32.0.30 ipv6= k8sPodName=core-cilium/hubble-mr2x2 subsys=endpoint
level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=0s bpfWaitForELF=0s bpfWriteELF=0s buildDuration="336.045µs" containerID=e15e82f776 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=598 error="Unable to create map /sys/fs/bpf/tc/globals/cilium_ep_config_00598: operation not permitted" identity=24220 ipv4=10.32.0.30 ipv6= k8sPodName=core-cilium/hubble-mr2x2 mapSync=0s policyCalculation=0s prepareBuild="63.781µs" proxyConfiguration=0s proxyPolicyCalculation=0s proxyWaitForAck=0s reason="retrying regeneration" subsys=endpoint waitingForCTClean=0s waitingForLock="1.125µs"
level=error msg="endpoint regeneration failed" containerID=e15e82f776 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=598 error="Unable to create map /sys/fs/bpf/tc/globals/cilium_ep_config_00598: operation not permitted" identity=24220 ipv4=10.32.0.30 ipv6= k8sPodName=core-cilium/hubble-mr2x2 subsys=endpoint
```

**Comment by Antiarchitect** [comment]
Unable to create map /sys/fs/bpf/tc/globals/cilium_ep_config_00861: operation not permitted

**Comment by brb** [comment]
@Antiarchitect Thanks for the info. Can you check in your `dmesg` whether you have lockdown enabled?

**Comment by Antiarchitect** [comment]
@brb Sry, just downgraded all my workers to 5.3

**Comment by Antiarchitect** [comment]
@brb - Please check your Slack

**Comment by joestringer** [comment]
Weirdly enough, after I upgraded my local Cilium dev VM kernel to net-next I'm observing this... but not for the `cilium-agent` process, only for `bpftrace`.

I started digging around in apparmor but I don't think that's it, bpftrace only has a "complain" mode profile, and `aa-audit` tells me there's no profile active:

```
# aa-audit bpftrace
Profile for /usr/local/bin/bpftrace not found, skipping
```

`dmesg | grep -i lock` in this setup doesn't turn up any lockdown-related things.

Feel free to reach out to me on slack if you have thoughts on what kinds of queries you'd like from that environment. I don't want to flood this thread too much given my issue is more bpftrace-related, but it seems similar enough that there may be some commonality.

**Comment by borkmann** [comment]
Fixed by: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=003461559ef7a9bd0239bae35a22ad8924d6e9ad

**Comment by brb** [comment]
@borkmann Thanks for tracking this down!
