### ISSUE TITLE
CI: Validate SVC maps preflight checks

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9989]
Since we started to store flags which indicate a SVC type in the BPF maps (with one exception - `LoadBalancer` is stored as `ExternalIP`), we can validate consistency of SVC maps in the preflight checks:
- https://github.com/cilium/cilium/blob/4d2aabcd7e103d36ee3a5800199ab2b4704add2f/test/helpers/kubectl.go#L2759
- https://github.com/cilium/cilium/blob/4d2aabcd7e103d36ee3a5800199ab2b4704add2f/test/helpers/kubectl.go#L2880

**Comment by tklauser** [comment]
Giving up on this for the moment, sorry for the commit message reference noise.

**Comment by brb** [comment]
No longer relevant.
