### ISSUE TITLE
Validate multicluster + ipsec + tunnel

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#9994]
We should figure out some automation around testing this combination and validate the functionality against a test suite for encryption in conjunction with tunneling mode, and ensure this works across clusters.

**Comment by joestringer** [comment]
Two broad options:
* Refactor existing tests to make them cluster-oblivious. This could be a lot of work but would allow high coverage for existing tests. Increases development burden for writing and maintaining tests.
* Add a new set of multicluster-aware tests. Test the pieces that are different in multicluster:
  * Connectivity
  * LB (across clusters)
  * Policy (identity is different across clusters, including cluster labels)
  * Visibility (identities / labels show up as expected in monitor output)

**Comment by aanm** [comment]
I think @seanmwinn is or was recently testing this?

**Comment by joestringer** [comment]
I believe so, but manually. We will need to integrate this into some form of regular automated tests to prevent regressions.

**Comment by joestringer** [comment]
One potential direction: Make use of kind per #11157 instructions.
