### ISSUE TITLE
Policy config's CIDR does not match pod ip

### ISSUE THREAD

**Issue by zhiyuan0x** [cilium/cilium#9998]
## Bug report
For policy's CIDRs, cilium creates  entries in ipcache map. These entries has a lower priority than pod ip  because of smaller prefix. CIDR policy rules cannot match the pod ip, even if pod ip is in CIDR's range.

**General Information**

- Cilium version (1.6.5)
- Kernel version (5.4.7-1.el7.elrepo.x86_64)
- Orchestration system version in use (kubernetes 1.17)
- Link to relevant artifacts (policies)

**How to reproduce the issue**

Create client and nginx pods. Client pods has label 'app=client', nginx pods has label 'app=nginx'.

```
$ kubectl get pods --show-labels -o wide
NAME                      READY   STATUS    RESTARTS   AGE     IP          NODE    NOMINATED NODE   READINESS GATES   LABELS
client-5fd9c76f7f-gcd74   1/1     Running   1          5d21h   10.0.2.90   node2   <none>           <none>            app=client,pod-template-hash=5fd9c76f7f
client-5fd9c76f7f-npmj4   1/1     Running   0          6m35s   10.0.2.85   node1   <none>           <none>            app=client,pod-template-hash=5fd9c76f7f
nginx-787b97f768-lwv8z    1/1     Running   1          5d21h   10.0.2.84   node1   <none>           <none>            app=nginx,pod-template-hash=787b97f768
```

Apply a policy for client pods to allow access 10.0.2.0/24. Although nginx pod’s ip (10.0.2.84) is in 10.0.2.0/24, it cannot be accessed from client pod.

```
$ kubectl get networkpolicy test-network-policy -o yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
  ...
spec:
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.2.0/24
  podSelector:
    matchLabels:
      app: client
```
```
$ kubectl exec -it client-5fd9c76f7f-gcd74 ping 10.0.2.84

PING 10.0.2.84 (10.0.2.84) 56(84) bytes of data.
^C
--- 10.0.2.84 ping statistics ---
0 packets transmitted, 0 received
```

**Comment by aanm** [comment]
@zhiyuan0x thanks for opening the GH issue, the behavior is correct as per defined in the documentation https://docs.cilium.io/en/v1.6/policy/language/#ip-cidr-based

>CIDR policies are used to define policies to and from endpoints which are not managed by Cilium and thus do not have labels associated with them.
